### PR TITLE
[master] Fix state_queue type checking to allow int values

### LINKED ISSUE #64122: [BUG] state_queue doesn't allow int
**Description**
Functionality to allow integer values in `state_queue` was introduced in 3006.0, but type checking seems to have been missed to allow it fully.

```
[WARNING ] Config option 'state_queue' with value 2 has an invalid type of int, a bool is required for this option
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.0+0na.da6403b
 
Python Version:
        Python: 3.7.3 (default, Oct 31 2022, 14:04:00)
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.3
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.5
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: 2.6.1
  pycryptodome: 3.17
        pygit2: Not Installed
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 25.0.0
        relenv: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 10.13 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-23-amd64
        system: Linux
       version: Debian GNU/Linux 10.13 buster
```
</details>

**Additional context**
Originally implemented in #63357

### PR DESCRIPTION
**Pull request by nicholasmhughes**
### What does this PR do?
See issue for details

### What issues does this PR fix or reference?
Fixes: #64122

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by s0undt3ch — CHANGES_REQUESTED** [review]
The fact that this was released broken in 3006.0 means it doesn't have proper test coverage, despite tests being added in https://github.com/saltstack/salt/pull/63357

Could you please add tests around this change too?

**Review by twangboy — APPROVED** [review]

**Review by s0undt3ch — APPROVED** [review]

**Comment by s0undt3ch** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[](https://github.com/saltstack/salt/pull/64668)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by s0undt3ch** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[](https://github.com/saltstack/salt/pull/64668)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by s0undt3ch** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[](https://github.com/saltstack/salt/pull/64668)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
