### PR TITLE
Parsing Epoch out of version provided during pkg remove

### PR DESCRIPTION
**Pull request by brejoc**
### What does this PR do?

yum doesn't seem to like the epoch information provided within the
version. Therefore it's removed before passing it to yum.

### Previous Behavior

`pkg.remove` state would choke if Epoch was included.

### New Behavior

`pkg.remove` state works even with Epoch information.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by brejoc** [comment]
@dwoz Not sure if the failing tests that we see here are related. Could you take a look please?

**Comment by brejoc** [comment]
Okay, looks like all of the tests have passed. I'll update the branch and then I guess only a review is missing. @garethgreenaway maybe?

**Review by garethgreenaway — APPROVED** [review]

**Comment by brejoc** [comment]
@garethgreenaway This there a problem with the macOS tests? I see that output for other PRs too. But that also looks truncated. How to I get the full output?

**Comment by brejoc** [comment]
> @garethgreenaway This there a problem with the macOS tests? I see that output for other PRs too. But that also looks truncated. How to I get the full output?

Ah sorry, I was blind. Okay, so those are also failing for [completely unrelated changes](https://jenkins.saltproject.io/job/pr-macosx-catalina-x86_64-py3-pytest/job/PR-59974/3/). I guess we are fine here, right?

**Review by Ch3LL — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Comment by garethgreenaway** [comment]
@brejoc Sorry I missed the comments.  We had a known issue with the OS X test runs that were unrelated to your PR, so we were ensuring that all PRs had 3 approvals from Core teams members before merging.  Your changes are not merged in.

**Pull request merged**
