### PR TITLE
Port saltsupport to master

### PR DESCRIPTION
**Pull request by terminalmage**
This PR handles porting of the following PRs, which together encompass the saltsupport functionality.

- #49480
- #50095
- #50401
- #51632
- #49936
- #50018

This is being done all at once to prevent confusion that might arise from attempting to port these PRs separately or in the wrong order.

NOTE: This builds on work started by @DmitryKuzmenko in https://github.com/saltstack/salt/pull/56830 and should probably supersede it.

### CODE REVIEW

**Comment by terminalmage** [comment]
There are some legit windows failures here, and I don't have a windows minion on which to test, so I've altered the asserts to provide more useful information along with the AssertionError.

**Review by DmitryKuzmenko — DISMISSED** [review]

**Comment by max-arnold** [comment]
This issue is probably relevant: https://github.com/saltstack/salt/issues/54814

**Comment by terminalmage** [comment]
Good catch @max-arnold, I just ported over the two PRs mentioned in that issue that weren't already part of this PR.

**Comment by max-arnold** [comment]
Were you able to run the feature? If it still doesn’t work, maybe there is no point in porting it...

**Comment by terminalmage** [comment]
@max-arnold I have not been able to try. If you want to test, there are dockerfiles for a bunch of platforms [here](https://github.com/cachedout/barnacle). You can use [this walkthrough](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally) to check out this PR branch into your local clone of Salt, and then from the root of that branch run `docker run --rm -it -v $PWD:/testing imagename` to get a shell on the container. From there, you can make whatever configuration is necessary, and when you run your salt commands they will run off the git checkout you mounted at `/testing`. You won't have an init system running but you can run `salt-master -d` and `salt-minion -d` to run the master and minion daemons in the background, and `pkill -f salt-master` or `pkill -f salt-minion` to stop the daemons.

**Review by DmitryKuzmenko — DISMISSED** [review]

**Comment by dwoz** [comment]
> Were you able to run the feature? If it still doesn’t work, maybe there is no point in porting it...

Who is able to test this to make sure it is working?

**Comment by sagetherage** [comment]
@terminalmage are you able to address the merge conflict, here? @DmitryKuzmenko when you are able, can you test this?

**Comment by terminalmage** [comment]
Rebased

**Comment by DmitryKuzmenko** [comment]
@terminalmage a couple of suggestions:
1. Windows tests failures could be fixed with a change like this: https://github.com/saltstack/salt/pull/56830/files#diff-0ddbe12a41fee1a8e552b35086f918ddR1992
2. The `cli/test_support.py` is pytest only so it should be moved to the `tests/pytest/unit/cli` directory and all checks for `pytest` module presence could be dropped like it's done here: https://github.com/saltstack/salt/pull/56830/commits/80cfdd630a8dc3c148129ff23ec4581712ee1ae2

**Review by garethgreenaway — APPROVED** [review]

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
