### PR TITLE
Mysql returner: force charset and encoding

### LINKED ISSUE #56895: [BUG] mysql returner: MYSQLdb use  'latin-1' encoding by default but tables are utf-8
**Description**
When using mysql returner, there's a traceback when saving some events because MYSQLdb use  'latin-1' encoding by default but tables are utf-8.

**Setup**
A simple master minion setup with a database.

**Steps to Reproduce the behavior**
try to run `sys.list_functions`, `sys.doc`, `sys.list_runner_functions` and `sys.runner_doc`  on the minion.

```bash
master_1  | 10:33:38 master.1 | [ERROR   ] Error in function _return:
master_1  | 10:33:38 master.1 | Traceback (most recent call last):
master_1  | 10:33:38 master.1 |   File "/usr/lib/python3/dist-packages/salt/master.py", line 1839, in run_func
master_1  | 10:33:38 master.1 |     ret = getattr(self, func)(load)
master_1  | 10:33:38 master.1 |   File "/usr/lib/python3/dist-packages/salt/master.py", line 1638, in _return
master_1  | 10:33:38 master.1 |     self.opts, load, event=self.event, mminion=self.mminion)
master_1  | 10:33:38 master.1 |   File "/usr/lib/python3/dist-packages/salt/utils/job.py", line 108, in store_job
master_1  | 10:33:38 master.1 |     mminion.returners[savefstr](load['jid'], load)
master_1  | 10:33:38 master.1 |   File "/var/cache/salt/master/extmods/returners/mysql.py", line 362, in save_load
master_1  | 10:33:38 master.1 |     cur.execute(sql, (jid, salt.utils.json.dumps(load)))
master_1  | 10:33:38 master.1 |   File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 207, in execute
master_1  | 10:33:38 master.1 |     args = tuple(map(db.literal, args))
master_1  | 10:33:38 master.1 |   File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 304, in literal
master_1  | 10:33:38 master.1 |     s = self.escape(o, self.encoders)
master_1  | 10:33:38 master.1 |   File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 226, in unicode_literal
master_1  | 10:33:38 master.1 |     return db.literal(str(u).encode(unicode_literal.charset))
master_1  | 10:33:38 master.1 | UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 73212: ordinal not in range(256)
master_1  | 10:33:38 master.1 | [ERROR   ] Could not store events - returner 'mysql.event_return' raised exception: 'latin-1' codec can't encode character '\u2019' in position 73469: ordinal not in range(256)

```

**Expected behavior**
No traceback pls.

**Versions Report**
```bash
Salt Version:
           Salt: 3000.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
         Jinja2: 2.9.4
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.11 
         locale: UTF-8
        machine: x86_64
        release: 5.5.15-200.fc31.x86_64
         system: Linux
        version: debian 9.11 
```

MYSQLdb should be forced to use 'utf-8' as an encoding.
adding options:
```python
charset="utf8",
use_unicode=True,
```
to the `MySQLdb.connect` function do the trick.

### PR DESCRIPTION
**Pull request by mattLLVW**
### What does this PR do?

This MR force charset and encoding for MYSQLdb connector.

### What issues does this PR fix or reference?
Fixes: #56895 

### Previous Behavior
Traceback when inserting some events.

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by waynew** [comment]
Should it /always/ use this option, or should we be able to specify things where we configure the database? Personally I think one should [always](http://utf8everywhere.org/) but... that's me personally.

**Comment by mattLLVW** [comment]
Well, the charset is already enforced in the db schema,It's just the connector acting up for some reason.

**Comment by waynew** [comment]
@mattLLVW would you be able/willing to add some tests for this?

**Review by waynew — CHANGES_REQUESTED** [review]
@mattLLVW If you need help writing tests, pleas reach out via #salt on IRC, Slack, or the test clinic twitch stream :+1:

**Comment by mattLLVW** [comment]
There's no tests for any database returners so I wouldn't know where to start.

**Comment by Danduriel** [comment]
Could we please bump this issue up? 
With German and French Minions it is really a hassle to patch the mysql after every salt update (Didn't want to put it in a custom module).

**Comment by Ch3LL** [comment]
@garethgreenaway can you comment here on how to add some tests here since you worked on adding the mysql module tests.

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Comment by mattLLVW** [comment]
@dwoz the issue is still there, the fix is still there. i don't understand what's the problem. Asking to add test on the database is unreasonable since there is no way to test it already.

**Comment by dwoz** [comment]
@mattLLVW Asking for a test is not un-reasonable. If this is a bug, adding a tests shows that said bug is actually fixed and will help prevent a regression in the future.

Also, doesn't this change introduce a bug if someone encodes their database in some other encoding? I.E. Maybe they do have a latin-1 encoded db?

**Pull request closed without merging**
