### PR TITLE
Add blade password example and make note of timeout

### LINKED ISSUE #28945: Dell Chassis State Example Improvements
- The example state template in the dellchassis.py docs does not include updating the idracs. The pillar data example is there, but the state example just shows cmc and switches.
- When using the following state example, the minion always returns with `[No response from the minion]`. If you extend the timeout, this response goes away. The docs should be updated to include this caveat as the dracr.py modules is much slower that regular salt. I am not sure if it is the switch state itself that is slower, or if the length of the state makes the run go to long before the time out is reached, but here is the example state where this is happening:
```
{% set details  = salt['pillar.get']('proxy:chassis', {}) %}
{% set password = salt['pillar.get']('proxy:new_password', {}) %}

chassis-setup:
 dellchassis.chassis:
   - chassis_name: {{ details['name'] }}
   - password: {{ password }}
   - datacenter: {{ details['datacenter'] }}
   
{% for k, v in details['switches'].iteritems() %}
{{ k }}:
 dellchassis.switch:
   - name: {{ k }}
   - password: {{ password }}
   - snmp: {{ v['snmp'] }}
{% endfor %}
```

FYI @cedwards and @cro

### PR DESCRIPTION
**Pull request by rallytime**
Fixes #28945

### CODE REVIEW

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Hold off on merging this for a minute. I might need to add/amend some of the details in the example.

**Comment by cachedout** [comment]
@rallytime Please let me know when this is ready to go. Thanks.

**Comment by rallytime** [comment]
@cachedout This should be ready now.

**Comment by cachedout** [comment]
@rallytime Thanks!

**Pull request merged**
