### PR TITLE
add acl unit tests

### PR DESCRIPTION
**Pull request by jfindlay**
### What does this PR do?

add acl unit tests
### Tests written?

Yes

### CODE REVIEW

**Comment by cachedout** [comment]
This says `Add ACL unit tests` but contains changes to the core ACL code.

Could you please explain what's happening in your modification to `salt.acl`?

**Comment by jfindlay** [comment]
I thought it was self-evident, sorry.

**Comment by cachedout** [comment]
These tests are not actually running. You need to add the new directory to the test runner, if I remember correctly.

**Comment by cachedout** [comment]
Bump @jfindlay

**Comment by jfindlay** [comment]
@cachedout, they seem to be running now.  I forgot to end the filename in `_test.py`.

**Pull request merged**
