### PR TITLE
Clean up in the nagios_json module

### PR DESCRIPTION
**Pull request by garethgreenaway**
Some cleanup in the nagios_json module.  Using enumerated status codes so we get ok, warning, and critical returned as the status of the nagios check.  More accurate than trying to determine this based on a numeric value which was different depending on the status of the check being used.

### CODE REVIEW

**Comment by isbm** [comment]
@garethgreenaway Oops, I did not see that (different time zone). So I basically reworked it all: #/21798

**Comment by isbm** [comment]
@garethgreenaway I also took your textual check. Please take a look into my version: there is no need in `__NAGIOS_STATUS` constant, because one method does everything as well as you do not need to loop over it in order to check if anything does not equals to "critical".

**Comment by isbm** [comment]
@jfindlay Since we worked in parallel with @garethgreenaway  I continued adding improvements to my version of this module:
* Dropped True/False returns in a status. This is not a good idea after all, because information about "Unknown" and "Warning" is truncated.
* An ability to return either numeric status or textual. So you are able to get 0, 1, 2... or "OK", "Warning", etc
* Brought to the topic "Unknown" status, which was not introduced at all.

**Comment by garethgreenaway** [comment]
The __NAGIOS_STATUS was necessary in this case since I wanted to return True or False based on the status that is returned.  You've done something similar but called it _ENUM_STATUS, which is going to be problematic since the status code returned by Nagios isn't always a 0, 1 or 2.  Which is why I added the enumerate option to the call.  The idea behind returning True or False was just that, host or service is up & responding True, anything else False.  I think there could be room to include the ability to support both scenarios.

**Comment by isbm** [comment]
@garethgreenaway No, this is not true. Nagios does not return random codes, but only from 0 to 3, which is OK, Warning, Critical and Unknown respectively. Please take a look: http://nagios.sourceforge.net/docs/3_0/pluginapi.html And you actually truncating this information, as well as you never take to the consideration "Unknown" status.

In my version Nagios returns a code and depend on what type of output you want, you get either number directly from Nagios, or text. And I just realized that this is also not needed, since Nagios can return this right through.

**Comment by isbm** [comment]
@garethgreenaway Here I completely removed the idea of "wrapping" the Nagios result and just return it as is: https://github.com/isbm/salt/commit/0c0b44ff61fd8ca1409b864a0410909a729f58d4

**Comment by garethgreenaway** [comment]
I never said they were random codes.  I've seen later versions of Nagios, specifically 4.1.x, return codes other than 0, 1, 2, or 3 depending on the status of the service.

**Comment by isbm** [comment]
@garethgreenaway In Nagios 4 there are more, sure. Here is the documentation:
http://nagios.sourceforge.net/docs/nagioscore/4/en/statetypes.html

And this is the exactly the information that Salt should **not** truncate to just True/False. Because even your current code already contains a bug: you incorrectly define 6, 7, 9, and 10 as "False", which is actually "True".

**Comment by garethgreenaway** [comment]
Correct, which is the reason for the follow up pull request where I wasn't checking return code but rather the enumerated value for the return code.  So 6, 7, 9 and 10 would be 'ok' and return True.  As I said, I think returning the return code is useful but I also think there are times when a True or False return is useful too.

**Comment by isbm** [comment]
@garethgreenaway But if you want to have True/False at module side, then you are asking for a trouble by supporting all Nagios (and derived systems) changes. Instead, I would suggest us to proxy-pass this to the user and depending what he is using (Isinga, Nagios 1.0 :) or Nagios 3 or so) he will just define something like:
```
nagios:
   scream-to-my-mobile: 2, 3
   shut-up: 0, 1, 6,7,9,10
```

Well, you've got the idea. :)

**Comment by isbm** [comment]
And one more thing: "Warning" is not _always_ True, while you hard-coding this paradigm. If warning can be OK for some low-important projects, certainly I never want to get burned that my Oracle database was about run out of a disk space and I did not asked EMC guys to add there more space, therefore my banking system today cannot boot!

**Pull request closed without merging**
