### PR TITLE
Fix file locking for gitfs see #18839

### PR DESCRIPTION
**Pull request by crasu**
Hacked together a patch for #18839.

### CODE REVIEW

**Comment by crasu** [comment]
Hmmm test test works on my machine ;-(

**Comment by rallytime** [comment]
@crasu Yeah, these are good. Those two tests that failed on CentOS 7 are a little bit flaky. Thanks!

**Comment by thatch45** [comment]
@terminalmage please review

**Comment by thatch45** [comment]
@crasu at first glance this looks good, but @terminalmage is the maintainer in here so should give us a thumbs up before we merge

**Comment by crasu** [comment]
Yeah please review this thoroughly. As I really hacked this together and it is quite hard to figure if it works.

**Comment by crasu** [comment]
Is anything happening here?

I put this fix on one of our salt machines and the problem does no longer occur on this machine. So it looks like the fix is working.

**Comment by terminalmage** [comment]
@crasu Sorry, I have been juggling several issues over the past week. The fix looks good, but I am going to personally test this today before merging. Thanks a lot for putting in the work on this.

**Comment by terminalmage** [comment]
@crasu This doesn't work for me. The update.lk is never cleared.

**Comment by crasu** [comment]
How did you test this? You are right the update.lk is not removed. But the lock should be removed in line 925.

**Comment by terminalmage** [comment]
Completely empty gitfs cachedir (/var/cache/salt/master/gitfs, with a single repo configured. The repo gets fetched but update.lk never goes away when done, so all file requests fail.

**Comment by crasu** [comment]
Ok I tried to reproduce this - but was unabled to. I cleaned /var/cache/salt/master/gitfs with a single repo configured and tried to retrieve file by calling cp.get_file - It is works as expected. However I now added code to remove the lock and delete the lock file. 

Do you get an exception or does it "just" hang?

**Comment by terminalmage** [comment]
update.lk was not being deleted at the end of the fileserver update. I'll test with the new code, but https://github.com/crasu/salt/commit/6d2ebe3311d2aa0bc917d7a318b47ed5306f5331 should be removed from this pull request.

**Comment by terminalmage** [comment]
As should https://github.com/crasu/salt/commit/50a1e0296f7487f36c0b8c124c1eab1bb0b1ded3

**Comment by terminalmage** [comment]
@crasu Make sure when you test that you are *only* using the git backend. Other backends that are working properly could be removing the lock file.

**Comment by terminalmage** [comment]
@crasu OK, I can confirm that the update.lk is now removed. It turns out that, in my initial test, I was using a repo that didn't have a "master" branch, so the "base" environment did not exist. So that would likely explain why you were not able to reproduce the same issue, it was just user error on my part.

We still needed to get the update.lk removed though, so it's good we got that change made.

Your PR won't merge cleanly, so I will rebase it and merge. Thanks again for your work on this!

**Comment by terminalmage** [comment]
OK, I have merged in the changes manually and pushed to the 2014.7 branch. I had to discard two commits (bad lint fixes), and I squashed another lint fix into the previous commit to make things a bit cleaner.

**Comment by crasu** [comment]
thank you

**Comment by terminalmage** [comment]
Thank you too, sir!

**Comment by terminalmage** [comment]
I'm going to have to revert this. It looks like this pull request made a bad assumption about ``find_file()``. It is assuming that ``find_file()`` is locking on the repo, but it is locking on the file itself. By using repo locking logic, you remove all file locking from serving files, which of course speeds things up. However, you re-introduce the potential for the race condition that the file locking was intended to resolve.

**Comment by terminalmage** [comment]
Actually, please disregard that last comment, I was misreading the code. Sorry for the confusion!

**Comment by terminalmage** [comment]
@crasu Your assumption about the call to purge_cache() [here](https://github.com/saltstack/salt/issues/18839#issuecomment-71660957) was incorrect. All that function does is remove old git checkouts (``/var/cache/salt/master/gitfs/<MD5 of gitfs remote URL>``), it has no impact on file caching.

Can you explain in more detail what your repo lock code is supposed to do? I want to make sure we are on the same page.

**Comment by ckraemer** [comment]
You are right - my assumption was wrong. Because of this the patch will not work in the way it was supposed to. Can you revert it? I will try to make this issue more reproducible.

**Comment by crasu** [comment]
You are right - my assumption was wrong. Because of this the patch will not work in the way it was supposed to. Can you revert it? I will try to make this issue more reproducible.

**Comment by terminalmage** [comment]
Yes, I have already reverted it as part of a larger changeset, see https://github.com/saltstack/salt/pull/20854. Once it is merged, I urge you to test against the updated 2014.7 branch (or the upcoming 2015.2.0 release) and see if it helps at all.

Thanks to you bringing attention to this, I did find some potential issues with repo locking which I've now fixed, so at least it wasn't all for nothing.

Looking forward to continuing to troubleshoot this with you. Thanks for helping to make Salt better!

**Pull request closed without merging**
