### PR TITLE
salt.modules.state: check gathered pillar for errors instead of in-memory pillar

### PR DESCRIPTION
**Pull request by terminalmage**
Also show errors where appropriate in other state.* functions when there
is a problem gathering pillar data.

This PR also makes a fix when ext_pillar_first is enabled, making the CLI pillar data available to ext_pillar in these instances, and adds some info-level logging to help troubleshoot makostack pillar rendering.

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Really nice. `Awesome` label applied!

**Comment by cachedout** [comment]
Some test failures to clean up, though.

**Comment by terminalmage** [comment]
Tests updated.

**Comment by tkwilliams** [comment]
Looking very promising :)

**Comment by Jlin317** [comment]
This seems cause a problem for me, when I have the custom grains being reference in pillar data. I got 'pillar rendering error' for the first state.highstate. 
Before this commit, in salt.modules.state.highstate(), salt.state.Highstate.call_highstate() is called and in which self.load_dynamic() is called before self._check_pillar(). 
After this commit, _check_pillar is called before newly-added custom grain was synced to the minion.
I am not sure whether this consider as a regression, or should I use reactor to bypass the problem, but I think this commit breaks https://github.com/saltstack/salt/pull/7630.
Test steps are included in https://github.com/saltstack/salt/pull/7630

**Comment by terminalmage** [comment]
@Jlin317 You should change your configuration. This was a legit bug that was fixed by this PR. You can use [this reactor example](https://docs.saltstack.com/en/latest/topics/reactor/#syncing-custom-types-on-minion-start) to make minions refresh their custom grains when they start up and connect to the master. However, the event name ``minion_start`` is, I think, outdated. I've updated the reactor example in https://github.com/saltstack/salt/pull/40184 and added a link to it from our FAQ. The correct event name now should be ``salt/minion/*/start``. You can also replace the ``*`` with a more restrictive glob, that ``*`` just matches any minion ID.

**Comment by Jlin317** [comment]
@terminalmage Many thanks.
I have one last related question. All I want to achieve initially is a state.highstate at minion startup, now it seems that I need a saltutil.sync_all/sync_grains fallowed by a state.highstate. Is the only way to achieve this by using Reactor to trigger an Orchestrate run or do I miss something obvious? (I have a working configuration with Reactor/Orchestrate runner to achieve want I want, just wonder if this is the only way)
(Other ways I tried:
-Previously I had 'startup_states: highstate' in minion configuration. However, it is executed before reactor's saltutil.sync_grains.
-I also tried to add another reactor event for state.highstate, failed again according to reactor Doc 'Reactor SLS files, by design, do not support Requisites, ordering, onlyif/unless conditionals...'.)

**Comment by terminalmage** [comment]
@Jlin317 For those using ``startup_states: highstate``, I can see a use case for also syncing custom types. I have opened https://github.com/saltstack/salt/issues/40220 to discuss this.

**Comment by Jlin317** [comment]
@terminalmage Many thanks!

**Comment by terminalmage** [comment]
@Jlin317 no problem!

**Pull request merged**
