### PR TITLE
ssh_port should be an int in deploy_kwargs.

### PR DESCRIPTION
**Pull request by flavianh**
Also competing for the shortest pull request ever.

### CODE REVIEW

**Comment by thatch45** [comment]
A string entry for shortest PR ever! But, the best way to get a super short pr is to make one that only removed a single extra newline at the end of a file :)
(when you see as many PRs as me you think about these things....)

**Comment by s0undt3ch** [comment]
@traxair was it failing on your end?

**Comment by traxair** [comment]
@s0undt3ch It was failing when calling `salt-cloud -p [profile] [vm_name]`.

**Comment by traxair** [comment]
@thatch45 well you have to consider the usefullness of the PR as well. I had a nice one the other day, where some data was coming out different after a JSON serialization/deserialization. Turns out I had a comma in my code `my_dict["value"] = value,` -> `my_dict["value"]` was becoming a tuple, and then it was changed into a list after the deserialization, making my unit test fail.
__#CoolStoryBrah__

**Pull request merged**
