### PR TITLE
Add multi-master-pki capability to cloud deploy.

### PR DESCRIPTION
**Pull request by freimer**
Note that salt-bootstrap needs to be updated to copy the master_sign.pub file from the temp directory to the pki minion directory for this to work with Linux.  Verified for Windows hosts.

### CODE REVIEW

**Comment by freimer** [comment]
See saltstack/salt-bootstrap#555.

**Comment by techhat** [comment]
@s0undt3ch, is it safe to assume you should be the one to update the bootstrap script in here?

**Comment by s0undt3ch** [comment]
Yew. Once i release a stable, I'll submit the PRs against salt.

**Comment by s0undt3ch** [comment]
s/Yew/Yes/

**Pull request merged**
