### PR TITLE
Back-port #25668 to 2015.8

### PR DESCRIPTION
**Pull request by rallytime**
Back-port #25668 to 2015.8

### CODE REVIEW

**Comment by cachedout** [comment]
This needs something like this included before we can get it in: https://github.com/cachedout/salt/commit/758959de994b13b050636775084e877dbfb4e94a

**Comment by rallytime** [comment]
@cachedout Sounds good. I'll take a look. I need to fix my lint error, too.

**Comment by cachedout** [comment]
@rallytime Most appreciated. Feel free to just merge this if the next set of tests pass, of course. :]

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Pull request merged**
