### PR TITLE
[RC1 Sodium] sphinx 3.0.2 has bugs

### PR DESCRIPTION
**Pull request by bryceml**
### What does this PR do?
it fixes building the docs on python3.8 and probably python3.9

### Previous Behavior
Sphinx would get stuck building the docs on python3.8 and probably python3.9

### New Behavior
Sphinx does not get stuck building the docs on python3.8 and probably python3.9

### CODE REVIEW

**Comment by bryceml** [comment]
See also https://saltstackcommunity.slack.com/archives/CRJPRHHT3/p1590891872113800

**Comment by bryceml** [comment]
See https://www.sphinx-doc.org/en/master/changes.html#release-3-0-3-released-apr-26-2020
as well.

**Review by s0undt3ch — APPROVED** [review]

**Comment by sagetherage** [comment]
@bryceml is this a legit test failure?

**Comment by bryceml** [comment]
> @bryceml is this a legit test failure?

we don't test building the docs on python3.8, so we wouldn't have caught this with the current tests.

**Review by Akm0d — APPROVED** [review]

**Pull request merged**
