### PR TITLE
Ignore return code in "run_all" and do not raise an exception therefore

### PR DESCRIPTION
**Pull request by terminalmage**
This is https://github.com/saltstack/salt/pull/51623, reopened against master. It is a bugfix for https://github.com/saltstack/salt/issues/51620, so it should be targeted for 2019.2.3.

### CODE REVIEW

**Comment by terminalmage** [comment]
Test case added.

**Comment by terminalmage** [comment]
re-run full all

**Review by waynew — DISMISSED** [review]
:rocket:

**Comment by Ch3LL** [comment]
@terminalmage would you mind fixing the merge conflicts and add a changelog. thanks!

**Comment by Ch3LL** [comment]
thanks for resolving that conflict. It looks like there are failing tests on the OS tests and pre-commit.

**Comment by Ch3LL** [comment]
Thanks. Let me know if I can help. I'm more than wiling to help wherever needed since this is not your original code.

**Comment by terminalmage** [comment]
Thanks! I think this is probably fixed now, though. The unit tests added in this PR were migrated to the `pytests` subdir and those tests are not class-based like they were originally when I added the test case. So, `self` was being referenced in the test function, and that needed to be removed.

**Comment by Ch3LL** [comment]
looks like the windows test failures are related

**Comment by terminalmage** [comment]
There's no reason to run that test on windows, so I marked it to skip on Windows.

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
