### PR TITLE
Fix/remove pack dunder

### PR DESCRIPTION
**Pull request by major0**
### What does this PR do?
Basic code maintenance:
1. Remove calls `salt.utils.compat.pack_dunder()` from all boto/boto3 modules since these calls have not been necessary since 2015.8.0.
2. Remove calls to `salt.utils.compat.pack_dunder()` from all code outside of boto/boto3 modules. This includes some tests and the module and state example templates for writing new code.
3. Update all touched code in order to make it pass the `pre-commit` tests.

_This does not fix any bugs, or add any features._

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by krionbsd — DISMISSED** [review]
LGTM

**Review by s0undt3ch — DISMISSED** [review]
And is `pack_dunder` still used anywhere?

**Comment by major0** [comment]
There are other files outside of the boto/boto3 code tree that are still using it yes.
```
salt/modules/libcloud_compute.py
salt/modules/libcloud_dns.py
salt/modules/libcloud_loadbalancer.py
salt/modules/libcloud_storage.py
salt/states/libcloud_dns.py
salt/states/libcloud_loadbalancer.py
salt/states/libcloud_storage.py
templates/module/salt/modules/{{module_name}}.py
templates/state/salt/states/{{module_name}}.py
tests/unit/modules/test_libcloud_compute.py
tests/unit/modules/test_libcloud_dns.py
tests/unit/modules/test_libcloud_loadbalancer.py
tests/unit/modules/test_libcloud_storage.py
```

**Comment by s0undt3ch** [comment]
> There are other files outside of the boto/boto3 code tree that are still using it yes.

Thanks for looking.

> I can always add these to this PR.

No, no need to mix.
It just means it needs to be addressed on a separate PR, and then we can remove that utility function.

**Comment by major0** [comment]
Too late? :)

**Review by krionbsd — DISMISSED** [review]

**Review by s0undt3ch — DISMISSED** [review]

**Review by krionbsd — APPROVED** [review]

**Review by Akm0d — APPROVED** [review]

**Review by s0undt3ch — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Pull request merged**
