### PR TITLE
Update baredoc to dump docstrings like sys.doc

### PR DESCRIPTION
**Pull request by mchugh19**
### What does this PR do?
Improves the recently merged baredoc to support display of module and module.function docstrings like sys.doc. Leverages the same formatting util as sys.doc to generate the same output, only baredoc does not require the state or execution module to be loadable by salt. Thus, it is useful in situations when you need docs for modules which cannot be loaded on the current machine. Or to export docstrings in bulk. 

### What issues does this PR fix or reference?
None

### Previous Behavior
Docstrings not suppored by baredoc

### New Behavior
(zpool module is not loadable on this machine)
```
# salt-call --local baredoc.module_docs zpool
local:
    ----------
    zpool:
        Module for running ZFS zpool command
        
        :codeauthor:    Nitin Madhok <nmadhok@clemson.edu>, Jorge Schrauwen <sjorge@blackdot.be>
...
```

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [ ] Changelog
- [x] Tests written/updated

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by mchugh19** [comment]
re-run pr-centos7-py3-pycryptodomex

**Comment by mchugh19** [comment]
re-run pr-ubuntu1604-py3-pycryptodomex

**Comment by mchugh19** [comment]
re-run pr-macosxmojave-py3

**Review by dwoz — APPROVED** [review]

**Comment by max-arnold** [comment]
@mchugh19 Hopefully it is not too late to fix the examples inside of docstrings:

```
def list_states(name=False, names_only=False):
    """
        salt myminion baredoc.modules_and_args
```

```
def list_modules(name=False, names_only=False):
   """
    .. code-block:: bash

        salt myminion baredoc.modules_and_args

        myminion:
            ----------
        [...]
          at:
          - present:
              name: null
              timespec: null
```

**Comment by mchugh19** [comment]
> @mchugh19 Hopefully it is not too late to fix the examples inside of docstrings:

Good catch! PR in https://github.com/saltstack/salt/pull/57503

**Pull request merged**
