### PR TITLE
Set the user to the actual user running the minion daemon

### PR DESCRIPTION
**Pull request by bbinet**
This PR fixes issue #39360

### CODE REVIEW

**Comment by cachedout** [comment]
This looks like the same thing as #39364. cc: @gtmanfred

**Comment by gtmanfred** [comment]
I have updated my pr to use this `salt.utils.get_user` function, but I think it goes better in `__opts__['user']` so that we have a record of what user is running the master.

**Comment by bbinet** [comment]
+1 for @gtmanfred patch in #39364

**Comment by cachedout** [comment]
@bbinet Sounds good. I am going to close this in favor of #39364 then. I assume this is your thinking on this as well. Let me know if my assumption is incorrect. :] Thanks!

**Comment by bbinet** [comment]
Yes, same thinking here. Thanks @cachedout

**Pull request closed without merging**
