### PR TITLE
Merge forward from 2014.7 to 2015.2

### PR DESCRIPTION
**Pull request by basepi**
Merge forward from 2014.7 to 2015.2

```
Conflicts:
    salt/returners/smtp_return.py
    salt/state.py
    salt/states/dockerio.py
```

### CODE REVIEW

**Comment by jfindlay** [comment]
@basepi, there may be some state.py change that is breaking these tests.  I'm not sure without looking deeper, but it seems that the test failures may be legitimate on some level.

**Comment by basepi** [comment]
Hrm, the only conflict in state.py was some STATE_RUNTIME_KEYWORDS that are in 2015.2 but not in 2014.7.

However, it looks like some non-conflicted changes may have broken some stuff. I'm going to do some investigation.

**Comment by basepi** [comment]
Go Go Jenkins!

**Comment by basepi** [comment]
I think I did have a slight problem with my merge conflict resolution, but I still don't believe that's what was causing all those failures. Guess we'll see.

**Comment by steverweber** [comment]
im no expert, but woudent life be more simple if all paches were done first in the dev branch then cherrypicked down to previous releases.

**Comment by steverweber** [comment]
If I go to patch somthing for the salt project should I be branching from develop or the latest stable branch?

**Comment by rallytime** [comment]
@steverweber We do it this way with the merge-forwards to reduce problems with regressions. If we cherry-pick all fixes from newer branches back to older ones, we may miss a lot of context. This is how we used to do things, and it led to many many regressions. This way is actually much more stable.

In regards to your last question, you should be branching from the earliest supported branch that contains the bug. For instance, if you find a bug in the 2014.7 branch, please fix it there, and then it will filter up through all of the branches that came after it so the fix can be in all places as we merge forward. If the bug was introduced in the 2015.2 branch, then it should be fixed there, etc. We have some docs on this situation here: http://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch for more information.

**Comment by steverweber** [comment]
thanks!

**Pull request merged**
