### PR TITLE
fix events endpoint not halting after token expires

### LINKED ISSUE #53742: event-stream from salt api /events does not stop at session timeout
### Description of Issue
The Salt API call `/events` gives access to the salt event stream. The Salt API has a session timeout (parameter `token_expire`). However, after a session timeout on the API, the event stream remains active. This may technically be correct, but still information is retrieved after the session timeout.

### Setup
Set up Salt API.

### Steps to Reproduce Issue
Run salt-api service.
Request an event stream using `/events`.
Consume or ignore the events.
The stream continues after a session timeout.

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: 2.6.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr 25 2019, 21:02:35)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.21.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

### PR DESCRIPTION
**Pull request by MKLeb**
### What does this PR do?
Terminates the event stream from the `/events` endpoint when the token expires.

Also, snuck in a small fix and test for some code that was removed during a PR about two weeks ago, per @s0undt3ch's suggestion

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/53742

### Previous Behavior
The stream would not terminate.

### New Behavior
Stream terminates when trying to display a new event but the token is expired.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by MKLeb** [comment]
re-run all

**Comment by MKLeb** [comment]
re-run all

**Comment by MKLeb** [comment]
re-run pr-debian-9-amd64-py3-pytest

**Comment by MKLeb** [comment]
re-run pr-debian-9-amd64-py3-pytest pr-alma-8-x86_64-py3-pytest

**Review by s0undt3ch — DISMISSED** [review]

**Review by waynew — DISMISSED** [review]
I took a glance at this and it looks good from what I see. I didn't pull it down and really try to break anything, though :upside_down_face:

**Comment by MKLeb** [comment]
re-run pr-alma-8-x86_64-py3-pytest

**Comment by MKLeb** [comment]
re-run pr-debian-9-amd64-py3-pytest

**Comment by MKLeb** [comment]
re-run pr-debian-9-amd64-py3-pytest

**Comment by MKLeb** [comment]
re-run pr-debian-9-amd64-py3-pytest

**Review by Ch3LL — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Comment by MKLeb** [comment]
re-run pr-ubuntu-2004-amd64-py3-pycryptodome-pytest

**Pull request merged**
