### PR TITLE
unique syndic job event

### LINKED ISSUE #52320: job will loop in syndic cluster mode
### Description of Issue/Question
Syndic will rebroadcast job when `masterofmaster` create new job. In syndic cluster mode, the create job event will infinite rebroadcast

### Setup 
Salt: 2019.2.0

MultiMaster with syndic in cluster mode:

```
order_master: True
syndic_mode: cluster

syndic_master:
  - master-01
  - master-02
  - master-03
```

### Steps to Reproduce Issue
Execute command in any one master:
```
salt '*' test.ping
```

### Versions Report
Salt: 2019.2.0

### PR DESCRIPTION
**Pull request by pengyao**
### What does this PR do?

Fixed 
#52320

### CODE REVIEW

**Review by dwoz — CHANGES_REQUESTED** [review]
@pengyao Please provide some test coverage for this change.

**Comment by KChandrashekhar** [comment]
Thanks for submitting this PR @pengyao. In order to ensure that functionality doesn't break in the future, we need test case written for it. Please provide test coverage. Appreciate your effort!

**Comment by sagetherage** [comment]
@pengyao this needs to be rebased against the master branch, please - or is there another PR to reference here?

**Comment by sagetherage** [comment]
Reviewed in Grooming will close as attempts have been made to update

**Pull request closed without merging**
