### PR TITLE
Resolves issue 50253 -- sdb yaml bug found when opening the yaml file to read values in

### PR DESCRIPTION
**Pull request by klafkoff**
### What does this PR do?
Fix issue https://github.com/saltstack/salt/issues/50253
### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/50253

### Tests written?

No

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by dwoz — COMMENTED** [review]
What happens if `mode` passed as a kwarg? Can we look at `f_handle.mode` instead of `args`?  We might also want to add a simple regression test since this is a bug fix.

**Comment by cachedout** [comment]
@klafkoff Did you see the comment from @doz above?

**Comment by cachedout** [comment]
Bump @klafkoff

**Comment by cachedout** [comment]
We didn't get a response here so I am closing this. If the submitter comes back and leaves a comment here, we can easily re-open it.

**Comment by klafkoff** [comment]
I was AFK, new commit PR shortly using kwargs. Digging through the unit/integration tests to see how to write a regression test as mentioned by @dwoz

**Comment by Kassec** [comment]
2018.3.3 & 2018.3.4 suffers from this annoying problem.

**Comment by dwoz** [comment]
@klafkoff Do you have a status on this?

**Comment by KChandrashekhar** [comment]
@klafkoff 
Any updates on using f_handle.mode instead of args and also a simple test case for this ? Thanks !

**Comment by dwoz** [comment]
@klafkoff This PR seems to have gone stale so I am going to close it for now. Please feel free to submit another PR with these changes if you have a chance to resolve the conflicts and address the other concerns.

**Pull request closed without merging**
