### PR TITLE
Fix test cases with PermissionError on /var/cache

### LINKED ISSUE #61148: [BUG] Tests fail with permission error for /var/cache
**Description**

Some test cases fail when run without root permission, because they want to read/write to `/var/cache`:

```
python3 -m pytest -ra tests/pytests/unit/state/test_state_format_slots.py tests/unit/utils/test_parsers.py
```

`test_format_slots_parallel` fails with:
```
Process ParallelState(always-changes-and-succeeds):
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "salt/utils/process.py", line 996, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "salt/state.py", line 2023, in _call_parallel_target
    with salt.utils.files.fopen(tfile, "wb+") as fp_:
  File "salt/utils/files.py", line 385, in fopen
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/salt/minion/123/174993d470c5f21b548d929d1904021966cb279f'
```

Similar for `tests/unit/utils/test_parsers.py`:
```
FAILED tests/unit/utils/test_parsers.py::SaltRunOptionParserTestCase::test_jid_option - salt.exceptions.SaltSystemExit: No permissions to access "/var/log/salt/master", are you running as the correct user?
FAILED tests/unit/utils/test_parsers.py::SaltRunOptionParserTestCase::test_jid_option_invalid - salt.exceptions.SaltSystemExit: No permissions to access "/var/log/salt/master", are you running as the correct user?
FAILED tests/unit/utils/test_parsers.py::SaltSSHOptionParserTestCase::test_jid_option - salt.exceptions.SaltSystemExit: No permissions to access "/var/log/salt/ssh", are you running as the correct user?
FAILED tests/unit/utils/test_parsers.py::SaltSSHOptionParserTestCase::test_jid_option_invalid - salt.exceptions.SaltSystemExit: No permissions to access "/var/log/salt/ssh", are you running as the correct user?
```

**Setup**

The test were executed on Ubuntu 21.04 (hirsute) on the git master branch from today (2021-10-29).

### PR DESCRIPTION
**Pull request by bdrung**
Some test cases fail when run without root permission, because they want to read/write to `/var/cache`:

```
python3 -m pytest -ra tests/pytests/unit/state/test_state_format_slots.py tests/unit/utils/test_parsers.py
```

`test_format_slots_parallel` fails with:

```
Process ParallelState(always-changes-and-succeeds):
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "salt/utils/process.py", line 996, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "salt/state.py", line 2023, in _call_parallel_target
    with salt.utils.files.fopen(tfile, "wb+") as fp_:
  File "salt/utils/files.py", line 385, in fopen
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/salt/minion/123/174993d470c5f21b548d929d1904021966cb279f'
```

Similar for `tests/unit/utils/test_parsers.py`:

```
FAILED tests/unit/utils/test_parsers.py::SaltRunOptionParserTestCase::test_jid_option - salt.exceptions.SaltSystemExit: No permissions to access "/var/log/salt/master", are you running as the correct user?
FAILED tests/unit/utils/test_parsers.py::SaltRunOptionParserTestCase::test_jid_option_invalid - salt.exceptions.SaltSystemExit: No permissions to access "/var/log/salt/master", are you running as the correct user?
FAILED tests/unit/utils/test_parsers.py::SaltSSHOptionParserTestCase::test_jid_option - salt.exceptions.SaltSystemExit: No permissions to access "/var/log/salt/ssh", are you running as the correct user?
FAILED tests/unit/utils/test_parsers.py::SaltSSHOptionParserTestCase::test_jid_option_invalid - salt.exceptions.SaltSystemExit: No permissions to access "/var/log/salt/ssh", are you running as the correct user?
```

fixes #61148

### CODE REVIEW

**Comment by MKLeb** [comment]
Hi @bdrung!  It seems this is failing on Windows 2016, are you able to look into these failures?  It looks to have something to do with file paths.

**Comment by bdrung** [comment]
I changed the commit to not fiddle around with the log file on Windows.

**Comment by bdrung** [comment]
@MKLeb The test failure on Windows is fixed.

**Comment by MKLeb** [comment]
@bdrung what happens if you run the tests (w/o the fix you implemented) with nox?

`nox -e 'pytest-zeromq-3(coverage=False)' -- tests/pytests/unit/state/test_state_format_slots.py tests/unit/utils/test_parsers.py`

**Comment by bdrung** [comment]
@MKLeb The result is exactly the same. I created a minimal Debian unstable schroot environment and installed the minimal requirements:
```
apt-get install -y nox libssl-dev libcurl4-openssl-dev
```
Then run the test as normal user on the current master branch:
```
mkdir -p /tmp/salt-tests-tmpdir
nox -e 'pytest-zeromq-3(coverage=False)' -- tests/pytests/unit/state/test_state_format_slots.py tests/unit/utils/test_parsers.py
```

The test spit out many warnings:
```
WARNING: CONFIG '/etc/salt' directory does not exist.
```
and the same test fail:
```
===============================================================================================================================================================================================================
SKIPPED [1] tests/pytests/unit/state/test_state_format_slots.py:34: Slow tests are disabled!
SKIPPED [1] tests/pytests/unit/state/test_state_format_slots.py:50: Slow tests are disabled!
SKIPPED [1] tests/pytests/unit/state/test_state_format_slots.py:66: Slow tests are disabled!
SKIPPED [1] tests/pytests/unit/state/test_state_format_slots.py:82: Slow tests are disabled!
SKIPPED [1] tests/pytests/unit/state/test_state_format_slots.py:98: Slow tests are disabled!
SKIPPED [1] tests/pytests/unit/state/test_state_format_slots.py:114: Slow tests are disabled!
SKIPPED [1] tests/pytests/unit/state/test_state_format_slots.py:154: Slow tests are disabled!
SKIPPED [1] tests/pytests/unit/state/test_state_format_slots.py:185: Slow tests are disabled!
SKIPPED [1] tests/pytests/unit/state/test_state_format_slots.py:202: Slow tests are disabled!
SKIPPED [1] tests/unit/utils/test_parsers.py:549: salt-key creates log file outside of parse_args.
FAILED tests/pytests/unit/state/test_state_format_slots.py::test_format_slots_parallel - PermissionError: [Errno 13] Permission denied: '/var/cache/salt'
FAILED tests/unit/utils/test_parsers.py::SaltRunOptionParserTestCase::test_jid_option - salt.exceptions.SaltSystemExit: No permissions to access "/var/log/salt/master", are you running as the correct user?
FAILED tests/unit/utils/test_parsers.py::SaltRunOptionParserTestCase::test_jid_option_invalid - salt.exceptions.SaltSystemExit: No permissions to access "/var/log/salt/master", are you running as the correct user?
FAILED tests/unit/utils/test_parsers.py::SaltSSHOptionParserTestCase::test_jid_option - salt.exceptions.SaltSystemExit: No permissions to access "/var/log/salt/ssh", are you running as the correct user?
FAILED tests/unit/utils/test_parsers.py::SaltSSHOptionParserTestCase::test_jid_option_invalid - salt.exceptions.SaltSystemExit: No permissions to access "/var/log/salt/ssh", are you running as the correct user?
=========================================================================== 5 failed, 159 passed, 10 skipped, 142 warnings in 2.02s ===========================================================================
```

**Comment by MKLeb** [comment]
@bdrung Thanks for the quick reply.  I'm going to look over this in more detail tomorrow

**Comment by MKLeb** [comment]
re-run pr-ubuntu-2004-amd64-py3-pytest

**Review by MKLeb — DISMISSED** [review]

**Comment by Ch3LL** [comment]
I'm still seeing windows failures on related to the PR: https://jenkins.saltproject.io/job/pr-windows-2016-x64-py3-pytest/job/PR-61449/3/#showFailuresLink

**Comment by bdrung** [comment]
I rebased the patch to resolve the merge conflicts. pr-windows-2016-x64-py3-pytest succeeds now.

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
