### PR TITLE
Disable some boto tests causing issues in the test suite on 2016.3

### PR DESCRIPTION
**Pull request by justinta**
### What does this PR do?

Prevents the tests suite from hanging on 2016.3. This also disables some other boto tests that weren't properly run in the initial PR. 

Takes these commits #31926 and adds to them
### What issues does this PR fix or reference?

Fixes the test suite from hanging
### Previous Behavior

The test suite would hang and not finish, at least on 2016.3
### New Behavior

Should no longer hang.
### Tests written?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jtand** [comment]
@s0undt3ch @kraney

**Comment by s0undt3ch** [comment]
:+1:

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by jtand** [comment]
Go Go Jenkins!

**Pull request merged**
