### PR TITLE
remove debug 'assert False'

### PR DESCRIPTION
**Pull request by vdloo**
This 'assert False' seems to be a debug statement that was left behind in https://github.com/saltstack/salt/pull/13844. This makes it so that if you run `salt-call state.show_states` when the salt-minion is already running this error is raised:

```
root@staging-2019-07-01-14-55-39-hes /etc/saltyparrot # salt-call state.show_states
[CRITICAL] 'master_type' set to 'failover' but 'retry_dns' is not 0. Setting 'retry_dns' to 0 to failover to the next master on DNS errors.
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AssertionError:
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 431, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 138, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 237, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1611, in show_states
    assert False
AssertionError
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 431, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 57, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 138, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 237, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 1611, in show_states
    assert False
AssertionError
```

After removing this assert False which cause the conflict to never be returned it works as expected and displays the message about a salt-minion process already running.
```
root@staging-2019-07-01-14-55-39-hes /etc/saltyparrot # salt-call state.show_states
[CRITICAL] 'master_type' set to 'failover' but 'retry_dns' is not 0. Setting 'retry_dns' to 0 to failover to the next master on DNS errors.
local:
    - The function "state.apply" is running as PID 4203 and was started at 2019, Jul 01 16:20:17.716712 with jid 20190701162017716712
```

### CODE REVIEW

**Comment by cmcmarrow** [comment]
Thanks for the fix

**Review by cmcmarrow — DISMISSED** [review]

**Review by xeacott — DISMISSED** [review]

**Comment by vdloo** [comment]
These failing tests sound related, is that something I should look at?

```
Failed
integration.modules.test_state.StateModuleTest.test_show_states (from integration.modules.test_state.StateModuleTest-20190701164105)

Failing for the past 1 build (Since Failed#1 )
Took 5 min 39 sec.
Error Message
False is not true
Stacktrace
Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\integration\modules\test_state.py", line 114, in test_show_states
    self.assertTrue(isinstance(states, list))
AssertionError: False is not true
```

```
Failed
integration.modules.test_state.StateModuleTest.test_show_highstate (from integration.modules.test_state.StateModuleTest-20190701164105)

Failing for the past 1 build (Since Failed#1 )
Took 5 min 39 sec.
Error Message
False is not true
Stacktrace
Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\integration\modules\test_state.py", line 97, in test_show_highstate
    self.assertTrue(isinstance(high, dict))
AssertionError: False is not true
```

not sure since most open PRs have failing tests and you guys already approved this PR.

**Review by rares-pop — DISMISSED** [review]

**Comment by xeacott** [comment]
Hey @vdloo these tests should be re-running now let's see what a refresh of these checks are saying.

**Comment by sagetherage** [comment]
@vdloo can you please point this to the master branch?

**Comment by vdloo** [comment]
done @sagetherage

**Review by xeacott — APPROVED** [review]

**Review by cmcmarrow — APPROVED** [review]

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
