### PR TITLE
please tell me where is the “error: 'dict' object has no …”

### PR DESCRIPTION
**Pull request by jettero**
### What does this PR do?

Tell me where the "error: 'dict' object has no attribute 'seek'" is so I can go fix it. It makes no attempt to resolve the error, just gives me a hint about what broke.

### What issues does this PR fix or reference?

#29028 and possibly others.

### Previous Behavior
complain uselessly to the minion log

### New Behavior
complain usefully to the minion log

### Tests written?

no

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by defanator** [comment]
Is that fix presents in 2016.11.3?

**Comment by jettero** [comment]
@defanator I don't think so. I thought I did my PR against 2016.11, but it looks like the merge went into develop. I think merges in 2016.11 auto merge into dev, but not the other way around.

Yeah, I updated a checkout of 2016.11 and it's not in there. 2016.11.3 is just the tag v2016.11.3; I don't think they're likely to update the tag. If it appeared anywhere, it'd be in 2016.11.4 or greater.

**Comment by rallytime** [comment]
If this needs to be in the 2016.11.4 release, then the fix needs to be submitted against the 2016.11 branch. I can back-port it right now, but just for future reference. :) Dot releases are on the branch, develop is for the next major feature release.

**Comment by jettero** [comment]
Thanks for the backport @rallytime. I think I just have just submitted the PR against the wrong branch.

**Comment by rallytime** [comment]
@jettero For sure! No problem at all. I just wanted to make sure we were all on the same page. Thanks again for the fix and discussion.

**Pull request merged**
