### PR TITLE
add connected_masters to salt.utils.minion and refactor status.master

### PR DESCRIPTION
**Pull request by hu-dabao**
### What does this PR do?
1. add connected_masters to salt.utils.minion, which will be very helpful for multi-master cases
2. refactor status.master to make it concise and use connected_masters

### New Behavior
One more useful util for multi-master setup

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @hu-dabao 

Thanks for this! We don't typically like to put refactors into release branches and we would prefer that this go into the develop branch instead. Would you mind if we moved it there?

**Comment by hu-dabao** [comment]
Please go ahead to move it to develop branch :)

**Comment by hu-dabao** [comment]
Branch updated.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Pull request merged**
