### PR TITLE
Changed all references of python 3.6 to 3.7.

### PR DESCRIPTION
**Pull request by hvbarker**
### What does this PR do?
Updated install instructions to reflect Python3.7 in place of Python3.6

### What issues does this PR fix or reference?
Fixes:
FreeBSD is not building 3.6 packages att his time.
hvb@fs-00:~[1021] pkg search salt
p5-Crypt-Salt-0.01_1           Perl extension to generate a salt to be fed into crypt
p5-Crypt-SaltedHash-0.09       Perl extension to work with salted hashes
py27-salt-2019.2.4             Distributed remote execution and configuration management system
py37-salt-2019.2.4             Distributed remote execution and configuration management system
rubygem-hammer_cli_foreman_salt-0.0.5 SaltStack integration commands for Hammer CLI
rubygem-smart_proxy_salt-2.1.9 SaltStack Plug-In for Foreman's Smart Proxy
hvb@fs-00:~[1022] 

### Previous Behavior
Remove this section if not relevant
hvb@fs-00:~[1024] sudo pkg install py36-salt
Password:
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
pkg: No packages available to install matching 'py36-salt' have been found in the repositories
[1]    40004 exit 70    sudo pkg install py36-salt
hvb@fs-00:~[1025] 

### New Behavior
Remove this section if not relevant
hvb@fs-00:~[1025] sudo pkg install py37-salt
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The most recent versions of packages are already installed
hvb@fs-00:~[1026] 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by s0undt3ch — APPROVED** [review]

**Comment by s0undt3ch** [comment]
@krionbsd could you please confirm if Salt >= 3000 is still packages Py2.7 BSD?
@hvnsweeting We should probably remove the Py2 references since we're updating

**Comment by hvbarker** [comment]
I sent email to the maintainer christer.edwards@gmail.com on 2020.05.14 asking if Salt 3000 would be added to ports tree, no response yet.  2019 is maintained and current.

Also, i do not believe bootstrap-salt.sh is mentioned for FreeBSD.  It works for 2019.2.5

**Comment by krionbsd** [comment]
> @krionbsd could you please confirm if Salt >= 3000 is still packages Py2.7 BSD?
> @hvnsweeting We should probably remove the Py2 references since we're updating

there is 2019.2.5 right now but we're going to upgrade it to 3000 kinda soon'ish, python 3.7 is now default in FreeBSD, if someone still want to use 2.7, they are still able to run `pkg install py27-salt` to get py27 but it's not recommended because of py27 EOL.

**Review by waynew — APPROVED** [review]
Hey @hvbarker thanks for the PR! Don't worry about the Python2 thing, I'm working on removing expired deprecations, of which Python2 support is one :trollface: So I'll get that one 👍

**Pull request merged**
