### PR TITLE
Fix salt api pid file

### LINKED ISSUE #57975: [BUG] Salt-api fails to start on 3001.1
**Description**
Trying to start salt-api on 3001.1 it fails with this error:
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'SaltAPI' object has no attribute 'set_pidfile'
Traceback (most recent call last):
  File "/usr/bin/salt-api", line 11, in <module>
    load_entry_point('salt==3001.1', 'console_scripts', 'salt-api')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 518, in salt_api
    sapi.start()
  File "/usr/lib/python3/dist-packages/salt/cli/api.py", line 67, in start
    super(SaltAPI, self).start()
  File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 1033, in start
    self.prepare()
  File "/usr/lib/python3/dist-packages/salt/cli/api.py", line 55, in prepare
    self.set_pidfile()
AttributeError: 'SaltAPI' object has no attribute 'set_pidfile'
Traceback (most recent call last):
  File "/usr/bin/salt-api", line 11, in <module>
    load_entry_point('salt==3001.1', 'console_scripts', 'salt-api')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 518, in salt_api
    sapi.start()
  File "/usr/lib/python3/dist-packages/salt/cli/api.py", line 67, in start
    super(SaltAPI, self).start()
  File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 1033, in start
    self.prepare()
  File "/usr/lib/python3/dist-packages/salt/cli/api.py", line 55, in prepare
    self.set_pidfile()
AttributeError: 'SaltAPI' object has no attribute 'set_pidfile'
```

Might be related to https://github.com/saltstack/salt/pull/57818

### PR DESCRIPTION
**Pull request by cmcmarrow**
### What does this PR do?
Hot fix Salt-API

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/57975

### Previous Behavior
Salt API does not work

### New Behavior
Salt API works

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by twangboy — DISMISSED** [review]

**Review by twangboy — DISMISSED** [review]

**Comment by cmcmarrow** [comment]
re-run full all

**Comment by cmcmarrow** [comment]
slow test did not run. Slow test had been tested on linux and windows.

**Review by garethgreenaway — DISMISSED** [review]

**Review by s0undt3ch — DISMISSED** [review]

**Comment by cmcmarrow** [comment]
re-run centos full

**Comment by garethgreenaway** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by cmcmarrow** [comment]
re-run full all

**Comment by cmcmarrow** [comment]
re-run full all

**Comment by cmcmarrow** [comment]
re-run full all

**Comment by cmcmarrow** [comment]
re-run full windows

**Review by twangboy — APPROVED** [review]

**Comment by sagetherage** [comment]
@dwoz ready to merge

**Pull request merged**
