### PR TITLE
Fixing mysql.py

### PR DESCRIPTION
**Pull request by gmiu**
I removed the 'r' on line 121. The whole code from that line to the end was commented because of that 'r'. Now it's fixed.

### CODE REVIEW

**Comment by terminalmage** [comment]
You seem to be mistaken. What version were you running when you noticed an issue?

**Comment by terminalmage** [comment]
Also, it looks like you mentioned this last week and I already explained to you the reasoning for the "r" flag there:

https://github.com/saltstack/salt/commit/9d1d8096e36ff2d36d7d8dea40bb80679f18fef7#commitcomment-14379647

**Comment by avb76** [comment]
First of all, it seems that I have missed your reply from last week.
Another mistake of mine was that I use 2015.8.1 and I searched for the
error in the develop branch.

Sorry for these two mistakes.

But, there still is a problem. First, here is the output that I get when I
use mysql.user_exists:

[root@vm0 ~]# salt '*' mysql.user_exists root

vm1:

    'mysql.user_exists' is not available.

vm3:

    'mysql.user_exists' is not available.

vm2:

    'mysql.user_exists' is not available.

vm0:

    'mysql.user_exists' is not available.


After I saw this output, I looked over the mysql.py code in the develop
branch (my mistake here) and I saw that 'r' and the rest of the code
commented. I decided to copy all the mysql.py code and to put it in a
module of mine. I removed the 'r' and the result was the following:

[root@vm0 ~]# salt '*' mymysql.user_exists root

vm1:

    *False*

vm2:

    *False*

vm3:

    *False*

vm0:

    *False*

The module mymysql has the same code as mysql, but with that 'r' removed.


Please, correct me if I'm not right.


Thanks,

Gabriel

**Comment by avb76** [comment]
Sorry again,

I realized that I still compare the code in 2015.8.1 with the code in the
develop branch. I will do some more tests tomorrow and I will give you a
reply.

Again, sorry.

Gabriel

**Pull request closed without merging**
