### PR TITLE
Handle thread shutdown on system exit

### PR DESCRIPTION
**Pull request by gtmanfred**
### What does this PR do?
Handle changes made for https://bugs.python.org/issue18966 in python 3.7

### What issues does this PR fix or reference?
Fix saltstack/salt-jenkins#1075

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by rallytime — APPROVED** [review]
This looks good to me, well done! But I would like some other folks to review it as well.

**Comment by garethgreenaway** [comment]
Seeing this when attempting to start the minion:
```
Process Process-1:
Traceback (most recent call last):
  File "/home/gareth/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/gareth/.pyenv/versions/3.7.0/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gareth/code/salt/salt/scripts.py", line 115, in minion_process
    lock = threading.lock()
AttributeError: module 'threading' has no attribute 'lock'
```

**Comment by garethgreenaway** [comment]
Running in the foreground with 2.7.15 and sending the KeyboardInterrupt:
```
The Salt Minion is shutdown. Minion received a SIGINT. Exited.
Process Process-1:
Traceback (most recent call last):
  File "/home/gareth/.pyenv/versions/2.7.15/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/gareth/.pyenv/versions/2.7.15/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gareth/code/salt/salt/scripts.py", line 160, in minion_process
    lock.acquire(blocking=True)
TypeError: acquire() takes no keyword arguments
```

**Comment by gtmanfred** [comment]
bah, i thought it should accept blocking as a call :/ https://docs.python.org/2/library/threading.html#threading.Lock.acquire

double checking now, might be worthwhile to just gate behind a check for python 3.7.

**Review by garethgreenaway — APPROVED** [review]

**Comment by garethgreenaway** [comment]
Looking good on both python 2.7.15 and 3.7.0.

**Review by DmitryKuzmenko — APPROVED** [review]
Tricky, smart and awesome! My best to you @gtmanfred!

**Review by dwoz — APPROVED** [review]

**Comment by gtmanfred** [comment]
Here is a running test with py37 on arch from my branch https://jenkinsci.saltstack.com/job/fluorine/view/Python3/job/gtmanfred-arch-py3/2/console

**Pull request merged**
