### PR TITLE
adding multipart/form-data file posting to http.query util

### PR DESCRIPTION
**Pull request by nicholasmhughes**
### What does this PR do?
This PR adds the ability for the requests backend to post files as multipart/form-data. I'm not really familiar with tornado, or else I'd add that too... updates welcome!

### What issues does this PR fix or reference?
N/A

### Previous Behavior
The http.query utility could not handle multipart/form-data, which is commonly used in file uploads to web servers.

### New Behavior
Now the http.query utility supports that capability in the requests backend.

### Tests written?
Yes

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by cmcmarrow** [comment]
@nicholasmhughes can you please add some test. We only ask that you test what you add it or changed.

**Comment by nicholasmhughes** [comment]
@cmcmarrow there aren't any test cases for the http utility at this time for me to model a test case after. do you have any suggestions on how to write a test for mocking an HTTP POST with a multipart/form-data upload of a file?

**Comment by waynew** [comment]
Or, the other code paths are never exercised 😰 

In tests/support/helpers.py there's a Webserver - you may be able to adapt for your needs. It's used in both tests/integration/states/test_file.py and test_archive.py

If you get stuck, let me know and I'll be happy to help out where I can!

**Comment by nicholasmhughes** [comment]
@waynew test pushed. let me know if that fits the bill.

**Comment by nicholasmhughes** [comment]
moving to #54903

**Pull request closed without merging**
