### PR TITLE
[DOCS] Fix examples in vsphere execution module

### PR DESCRIPTION
**Pull request by ggiesen**
### What does this PR do?
Fixes a small issues with the examples for the `vsphere` execution module

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by ggiesen** [comment]
re-run pr-alma-8-x86_64-py3-pytest

**Review by barbaricyawps — APPROVED** [review]
Looks good to me and I've approved from a docs clarity perspective. We might want to have someone do a quick technical review too.

Question: why does the docstrings.py file show so many modules being removed? I don't quite understand what it's doing?

**Review by waynew — APPROVED** [review]

**Comment by waynew** [comment]
@barbaricyawps that's got a list of the modules that are missing CLI Examples. So adding CLI Example to a whole bunch removes them from there :+1: (i.e. it's a good thing!)

**Comment by barbaricyawps** [comment]
Thanks, @waynew ! Cue "The More You Know" song here. 😄

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
