### PR TITLE
Add GPG Verification section to Contributing Docs

### PR DESCRIPTION
**Pull request by rallytime**
When we enable GPG Verification for pull request reviews, we should make sure there is information available in our Contributing docs about how to sign commits.

### CODE REVIEW

**Review by terminalmage — APPROVED** [review]

**Comment by damon-atkins** [comment]
Whats the impact of the PGP verification against for people who have enabled email privacy.

> Because you have email privacy enabled, EMAIL ADDRESS will be used for account-related notifications and damon-atkins@users.noreply.github.com will be used for web-based GitHub operations (e.g. edits and merges).

**Comment by cachedout** [comment]
@damon-atkins Good question. I don't know offhand. Have you approach GitHub support about this? I'd be interested to know what they say.

**Comment by damon-atkins** [comment]
Sent github a question about it.

**Comment by damon-atkins** [comment]
Response from GitHub.

> The commit will only show as verified on GitHub if the address used to commit it matches the address in the key

Sounds like can use  users.noreply.github.com  in the PGP Signature. Just need to make sure git is configured with  users.noreply.github.com and github is configured to have your email address private.

**Pull request merged**
