### PR TITLE
Fix mac brew pkg

### LINKED ISSUE #56609: [BUG] mac_brew_pkg is buggy
**Description**
https://github.com/saltstack/salt/blob/6ed2bd8c800227051cee5ad816e03795491b5bb4/salt/states/pkg.py#L3200 calls with params **pkgs=pkgs** https://github.com/saltstack/salt/blob/6ed2bd8c800227051cee5ad816e03795491b5bb4/salt/modules/mac_brew_pkg.py#L497 but these params does not exist and leads to a traceback

**Setup**
```
salt-call state.single pkg.uptodate '\*' refresh=True provider=mac_brew_pkg
```

**Steps to Reproduce the behavior**
You must at least have on update on brew

**Expected behavior**
```
----------
          ID: salt:core:brew:update:uptodate:upgrade
    Function: pkg.uptodate
        Name: *
      Result: True
     Comment: Upgrade ran successfully
     Started: 23:24:45.554339
    Duration: 43022.915 ms
     Changes:   
              ----------
              git:
                  ----------
                  new:
                      2.26.0_1
                  old:
                      2.26.0
              linux-headers:
                  ----------
                  new:
                      4.4.80
                  old:
              openssl:
                  ----------
                  new:
                      1.1.1f
                  old:
                      1.1.1d_2
              openssl@1.1:
                  ----------
                  new:
                      1.1.1f
                  old:
                      1.1.1d_2
              utf8proc:
                  ----------
                  new:
                      2.5.0
                  old:
                      2.4.0
```

### PR DESCRIPTION
**Pull request by gigi206**
### What does this PR do?
3 fixes with 3 commits:

- 1st commit: fix **pkg.uptodate** not working (missing __**kwargs__)
- 2nd commit: fix **pkg.latest**. Always detected failed changes because the function returns always results
- 3rd commit: fix brew warning at the 1st run

### What issues does this PR fix or reference?
Fixes: #56609, #56676

### Previous Behavior

- 1st commit: Cf #56609

- 2nd commit: Cf #56676 and https://travis-ci.org/github/gigi206/VSCode-Anywhere/builds/681428247#L22206 (line 22206)

```
[ERROR   ] Package jq failed to update.
local:
----------
          ID: salt:core:misc:update:jq
    Function: pkg.latest
        Name: jq
      Result: False
     Comment: Package jq failed to update.
     Started: 11:16:02.292816
    Duration: 12422.909 ms
     Changes:   
```

- 3rd commit: cf https://travis-ci.org/github/gigi206/VSCode-Anywhere/builds/681428247#L14376 (line 14376)

```
[ERROR   ] Command '['/home/linuxbrew/.linuxbrew/bin/brew', 'cask', 'info', '==>']' failed with return code: 1
[ERROR   ] stderr: Error: Cask '==>' is unavailable: No Cask with this name exists.
[ERROR   ] retcode: 1
```

### Merge requirements satisfied?
- [ ] Docs
- [ ] Changelog
- [ ] Tests written/updated

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by Akm0d** [comment]
@gigi206 Thank you for the contribution!  This can be merged as soon as a test is written for the chagnes

**Comment by Ch3LL** [comment]
looks like there is a merge conflict here. Also this will require a changelog and test coverage

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
