### PR TITLE
alternatives: Don't log error when running "alternatives --display" on nonexistant target

### PR DESCRIPTION
**Pull request by terminalmage**
These functions are used for information gathering and can result in a lot of noise for something that is not an error condition.

### CODE REVIEW

**Comment by xeacott** [comment]
Gotcha - thanks for getting this PR up. I'm going to re run these checks to see if we're good on this.

**Comment by xeacott** [comment]
re-run full all

**Comment by xeacott** [comment]
After reviewing some of the failing checks, it looks like the modification is causing failing tests. Heres an example from the Py2 Ubuntu check:
```
12:29:42         AssertionError: Expected call: mock([u'alternatives', u'--display', u'better-world'], python_shell=False)
12:29:42         Actual call: mock([u'alternatives', u'--display', u'better-world'], ignore_retcode=True, python_shell=False)
```
Fixing that should get the rest to pass too although, I did not look at them specifically.

**Comment by terminalmage** [comment]
I updated the failing unit test.

**Comment by xeacott** [comment]
Thanks! The team has been making a **ton** of changes to our testing infrastructure lately so I wanted to wait to verify some of these checks' failures were related to the PR.

**Comment by terminalmage** [comment]
I've rebased and changed the base branch to `master`, please review and merge.

**Comment by terminalmage** [comment]
This has been open for almost 9 months and all it does is insert `ignore_retcode=True` in a bunch of places to prevent spurious errors. Can we please get this merged?

**Review by DmitryKuzmenko — APPROVED** [review]

**Comment by DmitryKuzmenko** [comment]
It's good now, let's just wait for windows tests.
Thank you for patience @terminalmage

**Pull request merged**
