### PR TITLE
Fix for #55652 - Proc file naming

### LINKED ISSUE #55652: When targeting 100s of minions, some do not return.
### Description of Issue
When I target 100s of minions for any command, some minions take a bit longer to respond. Meanwhile master returns error for some of the minions without waiting them to be completed.
```
<minon_id>
Minion did not return. [Not connected]
--
```
### Reproduction and Logs:
For example, 
```
salt '<minion_id>' test.sleep 120 -l debug
```
always returning the above error.

Master sends the command to the minion. 
```
{"@timestamp":"2019-12-16T06:15:31", "message":"get_iter_returns for jid 20191216061530532724 sent to set(['<minion_id>']) will timeout at 06:15:36.476641", "lvl":"DEBUG", "op":"Process:MainProcess PyModule:salt.client line:1100", "pid":"25086", "severity_label": "DEBUG" , "severity": "10"}
```
Minion receives the command:
```
salt/job/20191216061530532724/new
{
    "_stamp": "2019-12-16T06:15:30.049766",
    "arg": [
        120
    ],
    "fun": "test.sleep",
    "jid": "20191216061530532724",
    "minions": [
        "<minon_id>"
    ],
    "missing": [],
    "tgt": "",
    "tgt_type": "glob",
    "user": "salt"
}
```
Master waits for about 5 seconds for minion to return. If it does not return, then it checks if the minion is still running the job:
```
{"@timestamp":"2019-12-16T06:15:36", "message":"Checking whether jid 20191216061530532724 is still running", "lvl":"DEBUG", "op":"Process:MainProcess PyModule:salt.client line:236", "pid":"25086", "severity_label": "DEBUG", "severity": "10"}
```
```
salt/job/20191216061536103764/new       {
    "_stamp": "2019-12-16T06:15:36.589880",
    "arg": [
        "20191216061530532724"
    ],
    "fun": "saltutil.find_job",
    "jid": "20191216061536103764",
    "minions": [
        "<minion_id>"
    ],
    "missing": [],
    "tgt": [
        "<minion_id>"
    ],
    "tgt_type": "list",
    "user": "salt"
}
```
Here, the minion always returns empty object even though the job is still running.
```
salt/job/20191216061536103764/ret/<minion_id>     {
    "_stamp": "2019-12-16T06:15:36.859919",
    "cmd": "_return",
    "fun": "saltutil.find_job",
    "fun_args": [
        "20191216061530532724"
    ],
    "id": "<minion_id>",
    "jid": "20191216061536103764",
    "retcode": 0,
    "return": {},
    "success": true
}
```
Eventually master thinks there the minion is not running the job and returns error.
```
{"@timestamp":"2019-12-16T06:16:06", "message":"return event: {'<minion_id>': {u'failed': True}}", "lvl":"DEBUG", "op":"Process:MainProcess PyModule:salt.client line:1531", "pid":"25086", "severity_label": "DEBUG", "severity": "10"}
```

### Versions Report
```
bash-4.4$ salt --versions-report
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.12.3
       cherrypy: unknown
       dateutil: 2.7.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: 0.27.7
        libnacl: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.4
         Python: 2.7.16 (default, May  6 2019, 19:35:26)
   python-gnupg: 0.4.2
         PyYAML: 5.1.1
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.5.1.el7.x86_64
         system: Linux
        version: Not Installed

```

### PR DESCRIPTION
**Pull request by sindhukothe**
### What does this PR do?
in _read_proc_file(), check for the thread names to be either 
```data['jid']```
or 
```
'{}-Job-{}'.format(data.get('jid'), data.get('jid'))
```
### What issues does this PR fix or reference?
#55652
### Previous Behavior
Master returns `Minion did not return. [Not connected]` when executing command `salt '<minion_id>' test.sleep 120 -l debug`
### New Behavior
Master waits for minion to finish the job before returning the error.

### CODE REVIEW

**Comment by garethgreenaway** [comment]
@sindhukothe Thanks for the PR, looks like a solid fix.  Would you be able to provide a test to ensure this doesn't result in a regression?  Thanks!

**Comment by sindhukothe** [comment]
> @sindhukothe Thanks for the PR, looks like a solid fix. Would you be able to provide a test to ensure this doesn't result in a regression? Thanks!

@garethgreenaway 
 Not sure what you are asking. You want me to run the tests to make sure nothing is broken? or add a new test case? Please let me know.

**Comment by garethgreenaway** [comment]
@sindhukothe If you could add a new test that tests the changes, that would be great.

**Comment by dwoz** [comment]
> ### What does this PR do?
> in _read_proc_file(), check for the thread names to be either
> `data['jid']`
> or
> 
> ```
> '{}-Job-{}'.format(data.get('jid'), data.get('jid'))
> ```
> 

It seems weird to me that we would need to check for both. I'd like to have an explanation of why there are two kinds of proc files and likely prefer to make the naming of them consistent.

**Comment by sindhukothe** [comment]
> > ### What does this PR do?
> > in _read_proc_file(), check for the thread names to be either
> > `data['jid']`
> > or
> > ```
> > '{}-Job-{}'.format(data.get('jid'), data.get('jid'))
> > ```
> 
> It seems weird to me that we would need to check for both. I'd like to have an explanation of why there are two kinds of proc files and likely prefer to make the naming of them consistent.

I am not sure why. But I thought it would be safe to check for both so that I dont change the existing functionality.

**Comment by sindhukothe** [comment]
> @sindhukothe If you could add a new test that tests the changes, that would be great.

@garethgreenaway, Unfortunately, I am not able to figure out how to add a new test case for this. If you can please point me to a similar test case, I will follow it and see if I can add a new one.

**Comment by garethgreenaway** [comment]
@sindhukothe When you were seeing the different proc files were all the minions running the same version of Salt or did you have different versions connecting to the master or masters?

**Comment by sindhukothe** [comment]
> @sindhukothe When you were seeing the different proc files were all the minions running the same version of Salt or did you have different versions connecting to the master or masters?

@garethgreenaway  You mean different "proc names" ? All the minions are running the same version in my environment.

**Comment by sagetherage** [comment]
@sindhukothe are you able to rebase this PR?

**Comment by sindhukothe** [comment]
> @sindhukothe are you able to rebase this PR?
Yes. I am able to rebase the PR.

**Comment by garethgreenaway** [comment]
@sindhukothe Apologies for the delay on this one, I tweaked your PR a bit:

```
diff --git a/salt/utils/minion.py b/salt/utils/minion.py
index c947498d2b..8dcef4f7a3 100644
--- a/salt/utils/minion.py
+++ b/salt/utils/minion.py
@@ -99,9 +99,12 @@ def _read_proc_file(path, opts):
             except IOError:
                 log.debug('Unable to remove proc file %s.', path)
             return None
-        if data.get('jid') == current_thread:
+        thread_name = '{}-Job-{}'.format(data.get('jid'), data.get('jid'))
+        if data.get('jid') == current_thread or thread_name == current_thread:
             return None
-        if not data.get('jid') in [x.name for x in threading.enumerate()]:
+        found = data.get('jid') in [x.name for x in threading.enumerate()] or \
+            thread_name in [x.name for x in threading.enumerate()]
+        if not found:
             try:
                 os.remove(path)
             except IOError:
```

and here are some tests for the `_read_proc_file` function:
```
# -*- coding: utf-8 -*-

# Import python libs
from __future__ import absolute_import, unicode_literals

# Import Salt Libs
import salt.utils.minion

# Import Salt Testing Libs
from tests.support.unit import TestCase
from tests.support.mock import patch, mock_open, MagicMock

import logging
log = logging.getLogger(__name__)


class FakeThreadingClass(object):
    name = 'thread-name'


class MinionUtilTestCase(TestCase):
    '''
    TestCase for salt.utils.minion
    '''
    def test__read_proc_file_multiprocessing_false(self):
        '''
        test get_minion_pillar when
        target exists
        '''

        opts = {'multiprocessing': False}
        proc_data = {'tgt_type': 'glob',
                     'jid': '20200310230030623022',
                     'tgt': 'minion',
                     'pid': 12345,
                     'ret': '',
                     'user': 'root',
                     'arg': [10],
                     'fun': 'test.sleep'}

        fake_thread = FakeThreadingClass()
        fake_thread.name = '20200310230030623022-Job-20200310230030623022'

        with patch('os.getpid', MagicMock(return_value=12345)):
            with patch('salt.utils.files.fopen',
                       mock_open(read_data=b'msgpack')):
                with patch('salt.payload.Serial.loads',
                           MagicMock(return_value=proc_data)):
                    with patch('salt.utils.process.os_is_running',
                               MagicMock(return_value=True)):
                        with patch('threading.enumerate',
                                   MagicMock(return_value=[fake_thread])):
                            with patch('salt.utils.minion._check_cmdline',
                                       MagicMock(return_value=True)):
                                data = salt.utils.minion._read_proc_file('/var/cache/salt/minion/proc/20200310230030623022', opts)
                                self.assertEqual(data, proc_data)

        opts = {'multiprocessing': False}
        proc_data = {'tgt_type': 'glob',
                     'jid': '20200310230030623022',
                     'tgt': 'minion',
                     'pid': 12345,
                     'ret': '',
                     'user': 'root',
                     'arg': [10],
                     'fun': 'test.sleep'}

        fake_thread = FakeThreadingClass()
        fake_thread.name = '20200310230030623022'

        with patch('os.getpid', MagicMock(return_value=12345)):
            with patch('salt.utils.files.fopen',
                       mock_open(read_data=b'msgpack')):
                with patch('salt.payload.Serial.loads',
                           MagicMock(return_value=proc_data)):
                    with patch('salt.utils.process.os_is_running',
                               MagicMock(return_value=True)):
                        with patch('threading.enumerate',
                                   MagicMock(return_value=[fake_thread])):
                            with patch('salt.utils.minion._check_cmdline',
                                       MagicMock(return_value=True)):
                                data = salt.utils.minion._read_proc_file('/var/cache/salt/minion/proc/20200310230030623022', opts)
                                self.assertEqual(data, proc_data)

        opts = {'multiprocessing': False}
        proc_data = {'tgt_type': 'glob',
                     'jid': '20200310230030623022',
                     'tgt': 'minion',
                     'pid': 12345,
                     'ret': '',
                     'user': 'root',
                     'arg': [10],
                     'fun': 'test.sleep'}

        fake_thread = FakeThreadingClass()
        fake_thread.name = '20200310230030623022'

        with patch('os.getpid', MagicMock(return_value=12345)):
            with patch('salt.utils.files.fopen',
                       mock_open(read_data=b'msgpack')):
                with patch('salt.payload.Serial.loads',
                           MagicMock(return_value=proc_data)):
                    with patch('salt.utils.process.os_is_running',
                               MagicMock(return_value=True)):
                        with patch('threading.enumerate',
                                   MagicMock(return_value=[fake_thread])):
                            with patch('salt.utils.minion._check_cmdline',
                                       MagicMock(return_value=False)):
                                with patch('os.remove',
                                           MagicMock(return_value=True)):
                                    data = salt.utils.minion._read_proc_file('/var/cache/salt/minion/proc/20200310230030623022', opts)
                                    self.assertEqual(data, None)

    def test__read_proc_file_multiprocessing_true(self):
        '''
        test get_minion_pillar when
        target exists
        '''

        opts = {'multiprocessing': True}
        proc_data = {'tgt_type': 'glob',
                     'jid': '20200310230030623022',
                     'tgt': 'minion',
                     'pid': 12345,
                     'ret': '',
                     'user': 'root',
                     'arg': [10],
                     'fun': 'test.sleep'}

        with patch('os.getpid', MagicMock(return_value=12345)):
            with patch('salt.utils.files.fopen',
                       mock_open(read_data=b'msgpack')):
                with patch('salt.payload.Serial.loads',
                           MagicMock(return_value=proc_data)):
                    with patch('salt.utils.process.os_is_running',
                               MagicMock(return_value=True)):
                        with patch('salt.utils.minion._check_cmdline',
                                   MagicMock(return_value=True)):
                            data = salt.utils.minion._read_proc_file('/var/cache/salt/minion/proc/20200310230030623022', opts)
                            self.assertEqual(data, None)
```

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
