### PR TITLE
Add support for multiline regex in file.replace

### LINKED ISSUE #7999: MULTILINE pattern cannot work in file.replace, fileinput always reads line by line.
The main problem comes from 
https://github.com/saltstack/salt/blob/develop/salt/modules/file.py#L962-964

<pre>
for line in fileinput.input(path,
            inplace=not dry_run, backup=False if dry_run else backup,
            bufsize=bufsize, mode='rb'):
</pre>

Using `salt.states.file.replace` with `flags:  ['DOTALL', 'MULTILINE']`, `bufsize: 'file'` and a pattern like `pattern: start.*end` it is impossible to match any multi-lines as `fileinput.input` is always reading the file line by line, even with bufsize set to the file size.

It seems that fileinput is made for that (http://docs.python.org/2/library/fileinput.html), a line by line read.

Documentation of `salt.modules.file.replace` states:
> Note: multiline searches must specify file as the bufsize argument below.

But this is not enough.

salt version: 0.17.0-1351-g9ba86c7
python version : Python 2.7.4

cc: @kiorky

### LINKED ISSUE #8051: Problems with fileinput.input inplace editing in salt.states.file.replace
In https://github.com/saltstack/salt/blob/develop/salt/modules/file.py#L962-964 usage of inplace editing have two unpleasant consequences
*  the file is **always modified** (except in dry_run mode), even if no difference is detected and the state reports no modifications. The modification timestamp for example is altered. This would, for example, mark this file as needed in an rsync process. This is a minor problem,but at least it should be documented.
* while the loop is running the **file is empty**, at least in backup mode. File content is back only after the end of the loop (tested with a sleep in the loop). Any process accessing the file while salt is editing may load an empty content.
* line-by-line reads prevent usage of MULTILINE regex as stated in #7999. Maybe ``salt.utils.filebuffer.BufferedReader`` should be used instead.

In #8048 I made some tests with ``salt.utils.atomicfile.atomic_open`` to avoid this parallel access problem. That may be a solution (or not).

### PR DESCRIPTION
**Pull request by lorengordon**
- use mmap to avoid reading the entire file into real memory
- mmap treats the entire file as a single string
  - `re` functions work when using the multiline flag
  - `count` parameter works as expected
  - no need to read line-by-line; should be significantly faster

Fixes #7999
Fixes #8051

### CODE REVIEW

**Comment by lorengordon** [comment]
The issues were marked as bugs, so I developed against the 2015.5 branch. There may be some conflicts merging this forward, as there were some changes to `file.replace` for 2015.8.

**Comment by lorengordon** [comment]
Also, this passed the file module tests when I ran them from a dev install. But, there is one use case I might have broken...per [this note](https://github.com/saltstack/salt/pull/28174/files#diff-7c48191b14cdf053cf954d03cc317963R1424)...
```python
#NOTE: Is there a use case for searching an empty file with an empty pattern?
```

**Comment by lorengordon** [comment]
I can't duplicate the failures from the centos7 tests. I ran all the tests from the file module and the file state locally, and everything seems fine. Can anyone else duplicate the failures?

**Comment by cachedout** [comment]
@lorengordon A number of tests failed here. Could you please take a look?

**Comment by lorengordon** [comment]
@cachedout, already on it. These last two commits should do it.

**Pull request merged**
