### PR TITLE
Fix for issue #21491 (composer install should always run)

### PR DESCRIPTION
**Pull request by ross-p**
The composer.installed state will now _always_ execute `composer install` by default.  This reinstates the previous 2014.7 default functionality.  (Fix issue #21491)

You can now pass an optional parameter always_check=False to make it only execute if/when the `vendor` sub-directory does not exist.

Changed the "did we run this before?" functionality to check for existence of the `vendor` directory rather than the `composer.lock` file since `composer.lock` is sometimes committed to the repository.

While I was in here, I modified the composer.update and composer.selfupdate modules to pass the `--no-progress` flag to `composer` which will remove the "Downloading ... X%" spam from stdout.

Also added more comments to tests to make it easier to see what they're actually trying to test.

### CODE REVIEW

**Comment by ross-p** [comment]
@rallytime Sorry to bother you again with this.  I introduced a bug for people who use composer.lock to specify exact dependency versions in my recent commit, this patch fixes the issue.

Assuming the tests complete OK, if this does not easily merge into 2014.7 I will create another PR for that.  Let me know, and thanks for your help.  :)

**Comment by rallytime** [comment]
@ross-p Sure, no problem! In the future, feel free to make bug-fixes against the "earliest supported affected branch" directly. Then we will merge them forward and the fix will apply on all branches that have the bug. (If something is a new feature, or a major refactor, though, save those for develop.) You can read up on that [here](http://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch) for more info.)

Assuming the tests pass and this all looks good I will give this backport a try. I'll let you know if I run into trouble. :)

**Comment by ross-p** [comment]
Ah OK.  I should have made the PR to the 2014.7 branch then?  I'm happy to do that now if you like.

**Comment by rallytime** [comment]
@ross-p Yeah, if you've got time and don't mind, that would be swell. Then the fix will be merged-foward to 2015.2 and develop within a couple of days.

**Comment by ross-p** [comment]
Added PR #21555 for 2014.7

**Comment by rallytime** [comment]
Awesome! Thanks much @ross-p!

**Pull request merged**
