### PR TITLE
Server Density agentv2 support

### PR DESCRIPTION
**Pull request by carlosperello**
### What does this PR do?

It improves serverdensity integration, doing some small bug fixing on the existing code and adding support to the agentv2 installation.
### What issues does this PR fix or reference?

None
### New Behavior

The pillar settings are different if it's a v1 or a v2 agent. By default everything works as without this patch and installs a v1 agent, but if the user tags a server state with agent_version: 2 the code will require an account_name entry on the pillar data.
### Tests written?

Yes, however I didn't manage to get them executed to verify them. I tried different options without success after following the instructions at https://docs.saltstack.com/en/latest/topics/development/hacking.html#running-unit-and-integration-tests without much luck :(

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @carlosperello 

Looks like that test didn't pass, unfortunately. Here's the test result: 

http://166.78.178.63:8080/job/PR/job/salt-pr-rs-cent7-n/1394/testReport/junit/unit.modules.serverdensity_device_test/ServerdensityDeviceTestCase/test_install_agent_v2/

**Comment by carlosperello** [comment]
Hi @cachedout that's fixed now. I still see some failures on the ubuntu job but I think it's not related to my changes, not sure though...

**Comment by cachedout** [comment]
Merged! Thanks, @carlosperello

**Comment by carlosperello** [comment]
@cachedout is there anything I may do to get this merged also into your 2016.03 branch so it's included in the new version that is being prepare?

**Comment by harryperks** [comment]
+1 for including it in 2016.03

**Comment by rallytime** [comment]
Hi all - back-port to 2016.3 is in #33303. :)

**Pull request merged**
