### PR TITLE
Update more files for unicode_literals, normalize yaml loader/dumper usage

### PR DESCRIPTION
**Pull request by terminalmage**
Without `allow_unicode=True`, unicode characters are processed through the str representer and on Python 2 are dumped as a Unicode code point (i.e. a literal `\u0414`). This commit makes `allow_unicode=True` the default in our `salt.utils.yamlloader.safe_dump()` helper. It also adds a new `salt.utils.yamlloader.dump()` helper which wraps `yaml.dump()` and also makes `allow_unicode=True` the default.

To make importing and using our custom yaml loader/dumper easier, a convenience module called `salt.utils.yaml` has been added, which does a wildcard import from both `salt.utils.yamldumper` and `salt.utils.yamlloader`.

Refs to yaml.load/dump and yaml.safe_load/safe_dump have been updated to salt.utils.yaml, to ensure that unicode is handled properly. The only exceptions right now are in the serializers, and those may also be updated in a future PR.

### CODE REVIEW

**Comment by rallytime** [comment]
Ah, @terminalmage now there are merge conflicts here. Probably because I merged another large fix of yours earlier today.

**Comment by terminalmage** [comment]
Rebased

**Comment by rallytime** [comment]
@terminalmage There are some test failures related to this change. Can you take a look?

The tests for `boto` are the related ones (not the `test_state_sls_id`, as you've fixed that already elsewhere): https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/17913/

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
re-run ubuntu

**Comment by rallytime** [comment]
Something funny is happening with the PY3 tests here. It's only running about 500 of them before it bails out. I am wondering if some of the fixes in #45038 might help here. Do you want to rebase this @terminalmage?

**Comment by tkwilliams** [comment]
Sweet!  This will be extra-super useful going forward (and hopefully retrofitting too...) 💯

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by terminalmage** [comment]
Doing the yaml work as part of a bigger PR has played havoc with the tests, so I'm going to split them into two separate PRs. Closing this one.

**Comment by terminalmage** [comment]
YAML stuff is in https://github.com/saltstack/salt/pull/45190

**Pull request closed without merging**
