### PR TITLE
Add virt.pool_capabilities function

### PR DESCRIPTION
**Pull request by cbosdo**
### What does this PR do?

Not all storage backends are supported for a given libvirt hypervisor. For the user
to know what is supported and what is not expose the recently added
libvirt function providing pool capabilities.

For older libvirt version, let's craft data that are reasonable by
adding a computed flag to warn these data may not be 100% accurate.

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by dwoz** [comment]
@cbosdo Can you please resolve the merge conflict?

**Comment by cbosdo** [comment]
> @cbosdo Can you please resolve the merge conflict?

done

**Comment by cbosdo** [comment]
rebased on master

**Comment by cbosdo** [comment]
rebased on master

**Review by dwoz — APPROVED** [review]

**Pull request merged**
