### PR TITLE
[RFC] Refactor error messages to have better documented errors and to allow packagers to customize them in an easy way

### PR DESCRIPTION
**Pull request by dincamihai**
### What does this PR do?

Proposes an idea to refactor the error messages in order to provide an easy way for packagers to customize them.

### CODE REVIEW

**Comment by brejoc** [comment]
How about using something like gettext? This way the error messages could also be localized.

**Comment by dincamihai** [comment]
@cachedout the simplest thing could be to have tuples of strings but maybe I better idea would be to implement a parent exception class and override some of the member functions so that it would ask for the right parameters (if needed) in order to render the output message.

tuples are simple and straight forward to implement but also starting with a simple exception class would not be that complicated (and extend it later when we know more about what is needed)
What do you think it would be best?

**Comment by isbm** [comment]
I would use just [gettext](https://docs.python.org/3/library/gettext.html) for this. We would be able to shoot two rabbits with one bullet: i18n and vendor supported messages.

**Review by gtmanfred — APPROVED** [review]
I am for centralizing error messages.

**Review by isbm — CHANGES_REQUESTED** [review]
@dincamihai looks good, but we need to specify here how exactly vendors can override the messages. And not just error messages, but all of 'em, if they need to. That way we could also get i18n/l10n done almost for free.

But I strongly suggest to use gettext, since not it is just century old reliable stuff, but also it sucks to write IDs instead of real English in the code.

**Review by terminalmage — APPROVED** [review]

**Comment by rallytime** [comment]
@dincamihai Did you want to make the change above about the specifications @isbm noted above? Once that is done, I think we can get this merged in.

**Comment by dincamihai** [comment]
@rallytime please give me a couple of days. I was on vacation. I would like to incorporate the feedback and improve the RFC a bit. Maybe even a proposed implementation.
I'll add the WIP.
Thanks!

**Comment by dincamihai** [comment]
@isbm @brejoc @cachedout I have updated my proposal to use gettext. I'm also providing an example of how this would be implemented and how it would work. Please take a look when you have time. Thanks!

**Comment by isbm** [comment]
We are using throwaways all around the code. Maybe:

```python
from salt.utils.gettext import gt
...
print(gt('something'))
```

...?

**Comment by dincamihai** [comment]
@isbm that makes sense. we don't really need to keep `_` in the real implementation. I can also change the examples in the RFC.
Do we agree to have this indirect import from salt.utils?

**Comment by dincamihai** [comment]
I have updated the example to incorporate the suggestion from @isbm 
@rallytime this could be merged if there is no objection. thank you!

**Review by cachedout — APPROVED** [review]

**Pull request merged**
