### PR TITLE
saltutil.py Fix for: #38977 non kwarg args for salt.cmd

### PR DESCRIPTION
**Pull request by DrMerlin**
### What does this PR do?
Fix for https://github.com/saltstack/salt/issues/38977
Allows non kwarg args to pass through salt.cmd

### What issues does this PR fix or reference?
#38977

### Previous Behavior
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
TypeError: cmd() takes at least 1 argument (0 given)

### New Behavior
Args passed in as fun_args, and routed to RunnerClient.cmd() as arg.

### Tests written?
No

### CODE REVIEW

**Comment by gtmanfred** [comment]
Can we make this 'args' instead of 'fun_args' so that this is consistent
with the local client and other places where we do this kind of stuff?

Otherwise :+1:

**Comment by DrMerlin** [comment]
@gtmanfred Thanks again for keeping an eye on this.  

Actually, I used args to being with, and it wouldn't make it to saltutil.runner.  I'm not sure where it's getting stripped out.  Changing it to anything but "args" seemed to make it work, and I thought fun_args was more consistent than kwargs or anything else.  Since fun_args is how it works with salt runner command line (if you inspect the event).

**Comment by cachedout** [comment]
@gtmanfred Can you please come back to this one and see the above comment? Thanks.

**Comment by gtmanfred** [comment]
@DrMerlin I have opened this PR to allow the use of args https://github.com/saltstack/salt/pull/40360

That is how I would do this.

Thanks,
Daniel

**Comment by cachedout** [comment]
We have merged #40360 and got no reply to Daniel's comment. Closing this. We can re-open it later on if we get a response.

**Pull request closed without merging**
