### PR TITLE
protect VT logs from unicode strings

### PR DESCRIPTION
**Pull request by kiorky**

### CODE REVIEW

**Comment by kiorky** [comment]
cc @s0undt3ch @thatch45

**Comment by kiorky** [comment]
to reproducte the bug
```
salt-call --hard-crash --local  -lall cmd.run 'for i in $(seq 2);do echo $i;sleep 1;done;echo é'  
python_shell=True use_vt=True
```

**Comment by s0undt3ch** [comment]
Thanks for the way to reproduce this. I have to take a closer look at this one with more time. We can't simply assume that the system is configured for utf-8.

**Comment by kiorky** [comment]
well, we can use chardet for example  to put things with a bit of logic to encoded strings, that's what i usually do when i have it.
Maybe the time to get a salt.ext.chardet, i can help to do that.

But afterall, this patch will cover 99% of the encoding problems ;)

**Comment by kiorky** [comment]
@s0undt3ch  see https://github.com/makinacorpus/makina-states/blob/master/mc_states/modules/mc_utils.py#L98

**Comment by s0undt3ch** [comment]
Chardet would only solve this problem if it could detect the encoding of the source of data(which are commonly single shell script lines an thus not that much valuable data to an accurate chardet suggestion) to turn it into Unicode; python would do the system conversion by itself afterwards.

The solution is to accurately find out what is the system encoding, which is a bit tricky since some systems don't report it correctly...

A user has even suggested to get it from `sys.stdin.encoding` but once a process is daemonized(running vt within salt matches this use case) that information gets lost or is wrongly reported.

**Comment by kiorky** [comment]
The current bug afterall is not about the output but the construction of strings by the concatenation of a pure string with the "source/input", and in other words the command or script lines to execute.
Moreover, either in  modules.cmdmod or utils.vt, this is only used to be loggued out to user, in info level for the former and debug level for the later.

If those bytes contain not only ascii chars, boom.

So here, blind utf-8 may catch mostly most situations out, and chardet would do the ultimate job.

**Comment by s0undt3ch** [comment]
I've stated my point, the bug **is** about the **output** as it is about the **input**, we need to know how to convert what comes from the system and what goes to the system and Chardet will most likely not be able to provide valid information with enough confidence for us to blindly trust it.

**Comment by kiorky** [comment]
I do not follow you, the bug is not in the vt subprocess, but in the main program loggers, @s0undt3ch.

**Comment by s0undt3ch** [comment]
PR locked waiting for me(so its not accidentally merged and then reverted.)

**Comment by thatch45** [comment]
Since we are working on getting the fix in deeper in the logging system I am going to close this one out.

**Pull request closed without merging**
