### PR TITLE
cmd.run_bg: Fixes

### PR DESCRIPTION
**Pull request by The-Loeki**
### What does this PR do?

`cmd.run_bg`:
- fix ERROR w/`output_loglevel=None`
- set loglevel to quiet 
- remove log callback
- small doc impro
### What issues does this PR fix or reference?
#6691
#29964
### Tests written?
- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
@cachedout or @terminalmage Can you review this when you get a moment?

**Comment by terminalmage** [comment]
I don't like the idea of hardcoding ``output_loglevel`` to ``quiet``. I know we're not getting output back because with_communicate is set to ``False``, but the way this code is written there will be no record in the log of the command having been run.

We should pass through the output_loglevel, so that we at least get an ``info`` level log message detailing the command that was run (see [here](https://github.com/The-Loeki/salt/blob/85fb2f9ce980c59ea2a333483a9ed2d1ac4d1095/salt/modules/cmdmod.py#L371-L383)).

We should also modify the ``msg`` passed to ``log.info()`` there such that it contains an extra blurb if the command is being run in the background.

**Comment by cachedout** [comment]
@The-Loeki Could you please have a look at the comments from @terminalmage here?

**Comment by The-Loeki** [comment]
Sorry for the delay you guys, how you like it now ?

**Comment by terminalmage** [comment]
Closed and reopened to kick off a new round of tests, the test suite was in a bad state when the tests were run berfore.

**Pull request merged**
