### PR TITLE
removing duplicate python 2 deprecation faq from development doc

### LINKED ISSUE #59117: [DOCS] Python 2 Deprecation FAQ is showing twice on the right navigation
**Description**
Python 2 Deprecation FAQ is showing twice on the right navigation
Screen Shot 2020-12-10 at 11 53 42 AM

**Suggested Fix**
Is this a duplicate on the index and then it is also pulling it into view from the .rst file? Unsure, but it looks incorrect.

**Type of documentation**
Developing Salt

**Location or format of documentation**
https://github.com/saltstack/salt/edit/master/doc/topics/development/index.rst

**Additional context**

### PR DESCRIPTION
**Pull request by vmdhhh**
### What does this PR do?
Removes duplicate doc reference of python 2 deprecation

### What issues does this PR fix or reference?
Fixes: #59117

### Previous Behavior
Python 2 Deprecation FAQ is showing twice on the right navigation

### New Behavior
Python 2 Deprecation FAQ is shown once on the right navigation

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by Ch3LL — APPROVED** [review]

**Comment by vmdhhh** [comment]
@sagetherage Will you please take a look and let me know if anything is missing?

**Review by ScriptAutomate — APPROVED** [review]

**Comment by vmdhhh** [comment]
@sagetherage Will you please merge the PR?

**Comment by sagetherage** [comment]
@vmdhhh apologies, we were on holiday, I updated this PR from master and letting those tests run, again as there were some failures. If that persists I will see about more approvals.

**Comment by vmdhhh** [comment]
> 
> 
> @vmdhhh apologies, we were on holiday, I updated this PR from master and letting those tests run, again as there were some failures. If that persists I will see about more approvals.

**Comment by vmdhhh** [comment]
Ah ! Misclicked
Christmas High :(

**Comment by sagetherage** [comment]
I am only re-running the tests that failed and if they don't pass it maybe something to dig into either from this PR or the tests. I am not sure ATM either way, but will check back on this later this week.

**Review by s0undt3ch — APPROVED** [review]

**Pull request merged**
