### PR TITLE
always return a dict object

### LINKED ISSUE #43241: Error whilst collecting napalm grains
### Description of Issue/Question

This error is raised at the first grains collection attempt, when the proxy and the pillar data is not yet ready:

```python
2017-08-29 12:06:46,748 [salt.loader      ][CRITICAL][23751] Failed to load grains defined in grain file napalm.optional_args in function <function optional_args at 0x7fb0a4114a28>, error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 738, in grains
    ret = funcs[key](proxy)
  File "/usr/lib/python2.7/dist-packages/salt/grains/napalm.py", line 453, in optional_args
    opt_args.pop(arg, None)
AttributeError: 'NoneType' object has no attribute 'pop'
```

That's just a small fix.

### PR DESCRIPTION
**Pull request by gtmanfred**
For napalm grains

### What issues does this PR fix or reference?
Fixes #43241 
### Tests written?

No

### CODE REVIEW

**Review by mirceaulinic — CHANGES_REQUESTED** [review]
I know I said in the issue that this is correct, but I just realised that this function should return None indeed, as it's used in other places such as https://github.com/gtmanfred/salt/blob/6a55b134350abb8ab6d69d2f49c070e1978e2af7/salt/grains/napalm.py#L289 where the grains doesn't need to be set as empty dict when the value is missing.

I would suggest instead to add something like `opt_args = _get_device_grain('optional_args', proxy=proxy) or {}` in the `get_opts` function.
Thanks!

**Comment by gtmanfred** [comment]
Probably just better to check if opt_args is None or not below that

**Comment by gtmanfred** [comment]
Actually after thinking about it, your method is better, incase someone
tries to call .get against that in the future.

**Comment by rallytime** [comment]
@mirceaulinic re-review requested

**Review by rallytime — APPROVED** [review]

**Review by mirceaulinic — APPROVED** [review]
Looks good.
Thanks @gtmanfred

**Pull request merged**
