### PR TITLE
boto_rds: support subnet_names when creating subnet group

### PR DESCRIPTION
**Pull request by quantonganh**

### CODE REVIEW

**Comment by cachedout** [comment]
The re-ordering of the args in this function argspec concerns me a little. We really don't like to do this, because it can break backward compability. Do we really need to move them around like this? Also, what happens in the case where they are both set to None? Will the function still work correctly?

**Comment by quantonganh** [comment]
> We really don't like to do this, because it can break backward compability.
> Do we really need to move them around like this?

Is it ok to put an optional argument in between 2 mandatory arguments?

> Also, what happens in the case where they are both set to None?

I changed the code to check if only one argument is provided.

> Will the function still work correctly?

No. We will got something like this:

```
----------
          ID: aws_rds_subnet_group
    Function: boto_rds.subnet_group_present
        Name: private-a-sg
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1591, in call
                  **cdata['kwargs'])
                File "/var/cache/salt/minion/extmods/states/boto_rds.py", line 369, in subnet_group_present
                  raise SaltInvocationError('One (but not both) of subnet_ids or '
              SaltInvocationError: One (but not both) of subnet_ids or subnet_names must be provided.
     Started: 10:45:04.815183
    Duration: 2.672 ms
     Changes:
```

**Comment by cachedout** [comment]
Hi @quantonganh. Thanks for the feedback. I think this is OK but we do need to get the lint tests to pass. Could you please have a look at them and fix the errors and then we'll get this merged? Thanks.

**Comment by basepi** [comment]
@quantonganh good call on the reorder. You're right that all keyword args must be after all positional args.

**Comment by quantonganh** [comment]
@cachedout: I fixed the pylint errors, rebased, and the test passed.

**Pull request merged**
