### PR TITLE
Complete rewrite how Minion ID is generated

### PR DESCRIPTION
**Pull request by isbm**
#### What does this PR do?

Re-implementation Minion ID generation.
#### What issues does this PR fix or reference?

Please refer to the https://github.com/saltstack/salt/issues/31383 issue why this is needed.
#### Tests written?

Yes

### CODE REVIEW

**Comment by cachedout** [comment]
I think that @thatch45 and I both agree that this can't go into a point release. What do you think about resubmitting this against develop?

**Comment by isbm** [comment]
@thatch45 @cachedout @rallytime Here is a development version: https://github.com/saltstack/salt/pull/34004

This PR I am closing, as per agreement not to let this go to any of the release. I wrote some tests, hopefully during development things will be tested in reality. :wink:

**Comment by dmacvicar** [comment]
This PR caused regressions on our end (SUSE Manager).

Minions with FQDN that used to appear with id `hostname.domain.com` now show up as `hotname`. Was this the expected behavior based on the discussion? I would expect the hostname to be the fallback if the FQDN is not available.

Looks wrong to me.

cc @renner @isbm @thatch45

**Comment by isbm** [comment]
@renner @dmacvicar @thatch45 While we decided to go with `platform.node()` like Ansible does due to this is the most reliable way, I would agree that we should keep previous behaviour, where FQDN should be always picked first.

The following PR fixes this: https://github.com/saltstack/salt/pull/34876

**Comment by thatch45** [comment]
This is why I wanted to put this in the develop branch :)

I have set this fix to be backported to the 2015.8 branch

**Comment by rallytime** [comment]
To follow-up on the last comment, this PR was originally closed against 2015.8, and then resubmitted against develop. So I won't be backporting the fix in #34876.

**Pull request closed without merging**
