### PR TITLE
Telegram beacon

### PR DESCRIPTION
**Pull request by rafaelcaricio**
### What does this PR do?

It is a new beacon to listen messages sent to a Telegram Bot inspired by Twilio SMS beacon. Example of usage is:
```yaml
beacons:
  telegram_bot_msg:
    token: "{{ token }}"
    accept_from:
      - rafaelcaricio
    interval: 10
```

More information on how to create a bot can be seen at https://core.telegram.org/bots#3-how-do-i-create-a-bot.

### What issues does this PR fix or reference?

This PR does not fix any specific issue, but adds more power to Salt.

### Tests written?

Yes

### CODE REVIEW

**Comment by cachedout** [comment]
@rafaelcaricio As a part of our transition to a new test suite, we need a modification made to the test:

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/9252/violations/file/tests/unit/beacons/telegram_bot_msg_beacon_test.py/

**Comment by rafaelcaricio** [comment]
@cachedout I made the requested changes. Seems like there are many other parts of the codebase that are making the code linting fail. Seems not related to telegram beacon code. I am not sure how to proceed now.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by rafaelcaricio** [comment]
@cachedout Thank you for accepting my PR! I am very glad! 👍

**Pull request merged**
