### PR TITLE
fix states.alternatives.install to really install alternative

### LINKED ISSUE #38802: alternatives.install module works but state fails
Module produces expected result:

```
salt 'salt01swa*' alternatives.check_installed java /usr/lib/jvm/jre-1.8.0_oracle/bin/java
salt01swa.intranet.example.org:
    False
salt 'salt01swa*' alternatives.install java /usr/bin/java /usr/lib/jvm/jre-1.8.0_oracle/bin/java 69
salt 'salt01swa*' alternatives.set java /usr/lib/jvm/jre-1.8.0_oracle/bin/java
salt 'salt01swa*' alternatives.check_installed java /usr/lib/jvm/jre-1.8.0_oracle/bin/java
salt01swa.intranet.example.org:
    True
```

State returns a failure: 
```
SLS:

java-install-alternatives:
  alternatives.install:
    - name: java
    - link: /usr/bin/java
    - path: /usr/lib/jvm/jre-1.8.0_oracle/bin/java
    - priority: '69'

# set the alternative version
java-set-alternatives:
  alternatives.set:
    - name: java
    - path: /usr/lib/jvm/jre-1.8.0_oracle/bin/java
    - require:
       - alternatives: java-install-alternatives

Salt output:

# salt 'salt01swa*' state.sls strd_tomcat
salt01swa.intranet.etnic.be:
----------
          ID: java-install-alternatives
    Function: alternatives.install
        Name: java
      Result: False
     Comment: Alternative for java not installed:
     Started: 13:10:10.289989
    Duration: 10.956 ms
     Changes:   
----------
          ID: java-set-alternatives
    Function: alternatives.set
        Name: java
      Result: False
     Comment: One or more requisite failed: strd_tomcat.java-install-alternatives
     Changes:   


```
I think I have identified the bug in `/usr/lib/python2.7/site-packages/salt/states/alternatives.py` around the condition `if current == path and master_link == link:`.

We expect a change to happen if current path or link are **different** from args passed to alternatives.install in the state.

Here's a patch, can anyone test?

```
--- alternatives.py-broken	2017-01-18 13:31:35.132866226 +0100
+++ alternatives.py	2017-01-18 13:31:46.652181596 +0100
@@ -83,7 +83,7 @@
         out = __salt__['alternatives.install'](name, link, path, priority)
         current = __salt__['alternatives.show_current'](name)
         master_link = __salt__['alternatives.show_link'](name)
-        if current == path and master_link == link:
+        if current != path or master_link != link:
             ret['comment'] = (
                 'Alternative for {0} set to path {1} with priority {2}'
             ).format(name, current, priority)
```

Version report

 ``` 
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo
 ```

### LINKED ISSUE #39417: alternatives.check_installed fails for installed alternatives that are not set
alternatives.check_installed looks for "set" alternatives rather than "installed" alternatives; therefore it fails for all alternatives that are installed except the currently selected one.

For example, I have java configured as follows:

```
[root@hkl105032 ~]# alternatives --display java
java - status is auto.
 link currently points to /usr/java/jdk1.8.0_40/bin/java
/usr/java/jdk1.8.0_40/bin/java - priority 18040
Current `best' version is /usr/java/jdk1.8.0_40/bin/java.
```
Now I use Salt to install an additional version:

`[root@hkl105032 ~]# salt 'hkl105032' alternatives.install java /usr/bin/java /usr/java/jdk1.7.0_75/bin/java 17075
`
But when I try to check if it's installed, I get:

```
[root@hkl105032 ~]# salt 'hkl105032' alternatives.check_installed java /usr/java/jdk1.7.0_75/bin/java
hkl105032:
    False
```
Even though alternatives clearly tells me it is installed:

```
[root@hkl105032 ~]# alternatives --display java
java - status is auto.
 link currently points to /usr/java/jdk1.8.0_40/bin/java
/usr/java/jdk1.8.0_40/bin/java - priority 18040
/usr/java/jdk1.7.0_75/bin/java - priority 17075
Current `best' version is /usr/java/jdk1.8.0_40/bin/java.
```

This is because the check_installed method checks to see if the symlinks in /etc/alternatives point to /usr/java/jdk1.7.0_75... but of course they don't because this alternative is merely "installed", not "set".

### PR DESCRIPTION
**Pull request by moench-tegeder**
The previous logic confused installing a new alternative and activating
that new alternative as the default link for that link group (this might
have been helped by the slightly confusing terminology here -
modules.alternatives.check_installed() checks whether the given path is
the dault link, but states.alternatives.install() should just install
another alternative). That logic failed if we installed a new alternative
with lower priority than the current default link (or with the link
group in manual mode): the default link does not change and the state
assumed that the installation of the alternative failed. Part of this
breakage resulted from commit 0e68fafb7446beb7946beecb6d379693d4585e84 .

This change puts the logic back on it's feet:
- Case 1 is when the alternative is already installed (that is, registered
  to the system as an alternative in that link group) as checked per
  modules.alternatives.check_exists(). No change there, and we just
  set a comment to that effect. It's open to debate if we should handle
  priority changes here.
- Case 2 registers the new alternative, and following that the default
  of that link group changes. That's a success, and we log a comment
  to that effect.
- Case 3 is when the link has to be installed, but the default does not
  change (link group in "manual" mode or lower priority). That too is
  to be considered a success - the new alternative can still become the
  default by either manual action or when the higher-priority alternative
  is removed later.
- Case 4 is when the alternative installation fails for some reason: we
  can detect that if modules.alternatives.check_exists() still returns
  False after link installation. That's a failure, and thus we set
  "result" to False with some comment.

Fixes: #38802
Fixes: #39417

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

Yes/No

### Commits signed with GPG?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by cachedout** [comment]
@moench-tegeder It looks like this failed a test. Could you please take a look?

**Comment by moench-tegeder** [comment]
Oh, I see... give me a few seconds, I'll fix it.

**Comment by moench-tegeder** [comment]
I think there's something else failing, too: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/23022/consoleFull#3149177260e76b7d7-9f01-494c-85a3-3ee3e5ff3147

Or am I lost in the maze of jenkins?

**Comment by rallytime** [comment]
@moench-tegeder I have restarted the tests just to be sure. There are a couple of issues on the HEAD of the branch we are working through right now.

**Comment by moench-tegeder** [comment]
This seems to be stuck? Anything I can do to usher this along?

**Comment by rallytime** [comment]
Hey @moench-tegeder The following test is still failing:

- unit.states.test_alternatives.AlternativesTestCase.test_install

Here's the output:

```
Traceback (most recent call last):
  File "/testing/tests/unit/states/test_alternatives.py", line 64, in test_install
    priority), ret)
  File "/testing/salt/states/alternatives.py", line 73, in install
    if __salt__['alternatives.check_exists'](name, path):
KeyError: u'alternatives.check_exists'
```

https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/23403/

Once that is fixed, we can get this reviewed and merged in. Thanks!

**Comment by moench-tegeder** [comment]
Ah, the test suite.
Last commits should get it done - I'm now at "code and tests work for me" :)

**Review by rallytime — APPROVED** [review]
This LGTM, but i'd like someone else to look this over, too.

**Review by terminalmage — APPROVED** [review]

**Pull request merged**
