### PR TITLE
Replace deprecated threading.currentThread with current_thread

### PR DESCRIPTION
**Pull request by hugovk**
### What does this PR do?

Fixes a deprecation.

* https://docs.python.org/3.12/whatsnew/3.10.html#deprecated

### What issues does this PR fix or reference?

* https://github.com/python/cpython/pull/25174

`threading.currentThread` was deprecated in Python 3.10 (October 2021).

Replace with `threading.current_thread`, added in Python 2.6 (October 2008).

### Previous Behavior

Uses deprecated `threading.currentThread()`.

### New Behavior

Uses `threading.current_thread()`.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [n/a] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [n/a] Tests written/updated

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by hugovk** [comment]
`salt/ext/tornado/` also uses deprecated `threading.activeCount` and `ready.isSet`, you'll need to update those once Tornado is updated.

I don't have GPG; if you need signed GPG commits, feel free to close this PR and redo it yourself :)

**Comment by twangboy** [comment]
Looks like this is breaking tests on MacOS

**Comment by hugovk** [comment]
```
assert 'retry-minion-BI4bCo' in {}
 +  where 'retry-minion-BI4bCo' = SaltMinion(id='retry-minion-BI4bCo', config_file='/private/tmp/stsuite/retry-minion-BI4bCo/conf/minion', config_dir='/private/tmp/stsuite/retry-minion-BI4bCo/conf', python_executable='/private/tmp/kitchen/testing/.nox/test-parametrized-3-crypto-none-transport-zeromq-coverage-true/bin/python', cwd=PosixPath('/private/tmp/kitchen/testing'), slow_stop=True, timeout=None, script_name='/private/tmp/stsuite/scripts/cli_salt_minion.py', base_script_args=[], check_ports=[], extra_cli_arguments_after_first_start_failure=['--log-level=debug'], display_name="SaltMinion(id='retry-minion-BI4bCo')").id
```

https://jenkins.saltproject.io/job/pr-macosx-catalina-x86_64-py3-pytest/job/PR-62156/4/testReport/tests.pytests.integration.minion/test_return_retries/test_publish_retry/

🤔 

Let's update the branch again to see if it happens again...

**Comment by twangboy** [comment]
@dwoz Any idea what could be causing the MacOS test failure here?

**Review by twangboy — APPROVED** [review]

**Comment by hugovk** [comment]
Hi! Any thoughts on this PR? I normally close them when they reach one year old. Thank you!

**Comment by s0undt3ch** [comment]
@hugovk the code in question has been updated.
If you see the changed files tab, all there is now is the changelog entry.
Sorry we couldn't get it in in time to give you the proper credits.

Closing.

**Comment by hugovk** [comment]
Ah yes! Good to hear it's been updated, credit not important :)

Thanks!

**Pull request closed without merging**
