### PR TITLE
Merge forward from 2014.7 to 2015.2

### PR DESCRIPTION
**Pull request by basepi**
Merge forward from 2014.7 to 2015.2

Resolved manpage conflicts by just reverting to the 2015.2 versions.

@ross-p it would be useful if you would glance at the composer resolution, the conflicts were substantial there.

```
Conflicts:
    doc/conf.py
    doc/man/salt-api.1
    doc/man/salt-call.1
    doc/man/salt-cloud.1
    doc/man/salt-cp.1
    doc/man/salt-key.1
    doc/man/salt-master.1
    doc/man/salt-minion.1
    doc/man/salt-run.1
    doc/man/salt-ssh.1
    doc/man/salt-syndic.1
    doc/man/salt-unity.1
    doc/man/salt.1
    doc/man/salt.7
    salt/cloud/clouds/linode.py
    salt/states/composer.py
    salt/states/win_update.py
```

```
Conflicts:
    salt/modules/virt.py
```

### CODE REVIEW

**Comment by s0undt3ch** [comment]
The next merge forward from 2014.7 will conflict on setup.py, the one from 2015.2 rules and is the one to keep intact...

**Comment by basepi** [comment]
@s0undt3ch thanks for the heads up.

**Comment by jfindlay** [comment]
@basepi, do you want to wait for @ross-p to review the composer module and state?

**Comment by ross-p** [comment]
WRT composer, any merge conflicts should replace the old with the new for 2014.7 and 2015.2.  These are the affected files:

modules/composer.py
states/composer.py
tests/composer_test.py

**Comment by jfindlay** [comment]
@ross-p, you mean the changes coming from 2014.7 should have precedent over whatever is in 2015.2?

**Comment by ross-p** [comment]
@jfindlay Correct.  2014.7 has the bug fix for #21497 and 2015.2 does not yet have it.

**Comment by jfindlay** [comment]
@ross-p, thanks.  I'll let @basepi verify since he's done the merge forward.

**Comment by ross-p** [comment]
Sorry for the confusion.  I think this is a case of me not following your procedures all that well.  To help clarify:

- I submitted code to develop
  - (I don't think that was ever merged into 2015.2)
- I backported it to 2014.7

- Fixed a bug in develop
- Backported it to 2014.7

So currently develop and 2014.7 are correct, and I believe that 2015.2 still has the old code that doesn't work with the new version of composer.

**Comment by jfindlay** [comment]
That makes sense.  Thanks for the clarification and sorry for the confusion.

**Pull request merged**
