### PR TITLE
Don't modify user git configs in tests

### PR DESCRIPTION
**Pull request by cachedout**

### CODE REVIEW

**Comment by rallytime** [comment]
Is it possible to restore the git config in the tear down? The `@destructiveTest` decorator will help avoid this, but what happens the next time you need to run the full test suite with `--run-destructive`?

**Comment by cachedout** [comment]
@rallytime In my view, if you run tests in destructive mode there should be no guarantee that terrible/amusing things won't happen. ;] But, you are right, that would be a better approach.

**Comment by rallytime** [comment]
Yeah, I agree that there shouldn't be any guarantee when running `--run-destructive` (I think there's a warning in the docs saying so), but I think we should make the effort to restore system changes as much as possible, if we can.

**Comment by terminalmage** [comment]
@cachedout I got a gentler fix for this in https://github.com/saltstack/salt/pull/26603. It now runs a ``git conffig --get --global`` on ``user.name`` and ``user.email``.

I also marked the entire test class as destructive, taking your lead here.

I'll go ahead and close this. Sorry for the oversight.

**Pull request closed without merging**
