### PR TITLE
Add master_tops support in salt-ssh

### PR DESCRIPTION
**Pull request by mateiw**
### What does this PR do?

Fixes master_tops not working with `salt-ssh`

### What issues does this PR fix or reference?

#19502

### Previous Behavior
master_tops were not evaluated when invoking the state module from `salt-ssh`

### New Behavior
master_tops will be evaluated when calling the state module from `salt-ssh`

### Tests written?

No

### CODE REVIEW

**Comment by cachedout** [comment]
@thatch45 Could you please take a look at this?

**Comment by thatch45** [comment]
Looks good to me, everything is in the right place

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Merged. Apologies for the delay, @mateiw. Thanks for your help with this!

**Pull request merged**
