### PR TITLE
[3006.x] Correct bash-completion for Debian / Ubuntu

### PR DESCRIPTION
**Pull request by dmurphy18**
### What does this PR do?
Corrects bash-completion for Debian / Ubuntu. When the relenv architecture was created, the RedHat bash completion file ```salt.bash``` was used for Debian / Ubuntu and installed into the incorrect directory. This rectifies this regression and uses the correct ```salt-common.bash-completion``` file and installs into the correct directory, namely ```/usr/share/bash-completion/completions``` with the file ```salt-common```, as previously in classic packaging and the Debian and Ubuntu forks of the Salt Project.

### What issues does this PR fix or reference?
Fixes https://github.com/saltstack/salt/issues/66560

### Previous Behavior
Bash completion did not work on Debian / Ubuntu and installed into the incorrect directory with the wrong completion file, that is, the one used for RedHat family.

### New Behavior
Bash completion now works on Debian / Ubuntu and installs into the correct directory

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [X] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices, including the
[PR Guidelines](https://docs.saltproject.io/en/master/topics/development/pull_requests.html).

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by smarsching** [comment]
@dmurphy18 In general, this looks good to me. However, I think that symlinks for the various utilities still need to be added. Otherwise, the bash-completion script is never going to be loaded. In order to avoid the situation in which a user thinks a command is present just because the respective symlink for bash-completion is present, I suggest adding the symlinks to the packages that add the respective executable. This means that the symlink for bash-completion will be installed if and only if the respective command is installed.

This means adding the following entries to the pkg/debian/*.links files:

`pkg/debian/salt-common.links`:
```
usr/share/bash-completion/completions/salt-common usr/share/bash-completion/completions/salt-call
```

`pkg/debian/salt-master.links`:
```
usr/share/bash-completion/completions/salt-common usr/share/bash-completion/completions/salt
usr/share/bash-completion/completions/salt-common usr/share/bash-completion/completions/salt-cp
usr/share/bash-completion/completions/salt-common usr/share/bash-completion/completions/salt-key
```

This should ensure that the completions are loaded when someone hits tab for one of the supported commands.

**Comment by dmurphy18** [comment]
@smarsching Can you take another review of the changes, currently doing some manual testing

**Comment by dmurphy18** [comment]
@smarsching Those symbolic links you proposed (have implemented) but thinking to remove, since they do not exist even in the Debian or Ubuntu fork of Salt when they are installed.  The tab completion is occurring due to PATH and /usr/bin/salt-***.
There are no symbolic links in ```/usr/share/bash-completion/completions/salt-XXXX``` only salt-common is there, hence removing those added symbolic links since this would make Salt Project onedir architecture different from Debian / Ubuntu forks, and from the old classic packaging.

**Comment by dmurphy18** [comment]
@smarsching I believe you are having other issues. I intend to have it install as per Debian / Ubuntu / Classic packaging forks, which is how it has been for almost a decade. Validation is done with VMs or machines, not Docker containers.  If you are having problems with Docker containers, than that is part of your environment, and not a release platform.

Team is too small for Docker and it's eccentricities, never mind podman.

Will check those extra directories you mentioned with the latest build but that did not exist in previous version with the symbolic links

**Comment by smarsching** [comment]
@dmurphy18 Sorry, it seems like my comment was a bit confusing. I don’t expect Salt to work in a Docker container (that would be asking a bit too much 🙂). I just used a Docker container to quickly check how files are extracted without having to fire up my test VM.

> How are you installing ?, should be with built packages only.

Yes, I installed the built Debian packages from the ZIP that was built by the CI pipeline (the “CI / Build Packages / DEB (x86_64, onedir) (pull_request)” job to be precise). I mentioned the link to the ZIP that I used in my previous comment. I believe that this build represents the latest commit to the branch. I installed the `salt-common` and `salt-master` packages from that ZIP using `dpkg -i …`.

> Will check those extra directories you mentioned with the latest build (when it finishes building) but that did not exist in previous build version with the symbolic links.

Thank you. Once you have checked this, I can give the packages from the CI pipeline a proper test run inside a VM.

**Comment by dmurphy18** [comment]
@smarsching Actually Salt will work on Docker, but systemd issues etc, was wondering if you were pip-installing.
The zip from this build should work for your testing.
I install as follows:
```
apt install ./salt-common-xxxxxxxx.deb ./salt-minion-xxxxxxxx.deb
```
prefer the apt install to dpkg

The old classic packaging built Salt with the following in ```rules```:
```
dh $@ --with python3,bash-completion --with=systemd --buildsystem=pybuild
```
whereas the new ```onedir``` architecture
```
build/onedir/venv/bin/tools pkg build onedir-dependencies --arch $${SALT_PACKAGE_ARCH} --relenv-version=$${SALT_RELENV_VERSION} --python-version $${SALT_PYTHON_VERSION} --package-name build/onedir/salt --platform linux
```
So also investigating what that tools build actually does.

I used to packaging all the Linux builds of Salt (classic packaging), but roles changed and the onedir architecture might have missed a few steps on Debian/Ubuntu, hence the work-arounds for systemd that I had to implement in 3006.9.

Will post what I find

**Comment by smarsching** [comment]
> @smarsching Actually Salt will work on Docker, but systemd issues etc, was wondering if you were pip-installing.
> The zip from this build should work for your testing.
> I install as follows:
>
> apt install ./salt-common-xxxxxxxx.deb ./salt-minion-xxxxxxxx.deb
>
> prefer the apt install to dpkg

Yes, I installed the `.deb`s from the ZIP. I used `dpkg`, not `apt`, but the only difference is that `apt` automatically installs dependencies while with `dpkg` the dependencies already have to present before the packages can be installed.

Please let me know what you find out and as written before, I am happy to test the packages in a proper VM when you deem them ready for testing.

**Comment by dmurphy18** [comment]
@smarsching Can you try the packages from this current build, they passed the automated testing, and is built with systemd and bash-completion using debhelper

**Comment by smarsching** [comment]
@dmurphy18 I tested the salt-common and salt-master package from [the latest run](https://github.com/saltstack/salt/actions/runs/10708741617/job/29700109666?pr=66852) of the “CI Build Packages / DEB (x86_64, onedir)” job in a Ubuntu 22.04 VM.

Bash-completion does not work after installing these packages. Hower, it does work after manually adding the following symlinks in `/usr/share/bash-completion/completions`:

```
lrwxrwxrwx 1 root root   39 Sep  6 15:22 salt -> salt-common/salt-common.bash-completion
lrwxrwxrwx 1 root root   39 Sep  6 15:22 salt-call -> salt-common/salt-common.bash-completion
lrwxrwxrwx 1 root root   39 Sep  6 15:22 salt-cp -> salt-common/salt-common.bash-completion
lrwxrwxrwx 1 root root   39 Sep  6 15:22 salt-key -> salt-common/salt-common.bash-completion
```

**Comment by dmurphy18** [comment]
@smarsching Thanks for testing that, but can you do me a favor and run your same test on a Ubuntu 20.04 with Ubuntu's fork of Salt (3004.1 I believe). I am thinking that this has never worked as you use it, even on older builds and cross-referencing against Ubuntu own fork of Salt would prove it. 

```
root@tu2004:/home/david# apt-cache policy salt-minion
salt-minion:
  Installed: 3004.1+ds-1
  Candidate: 3004.1+ds-1
  Version table:
 *** 3004.1+ds-1 500
        500 https://repo.saltproject.io/py3/ubuntu/20.04/amd64/archive/3004.1 focal/main amd64 Packages
        100 /var/lib/dpkg/status
root@tu2004:/home/david# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
root@tu2004:/home/david#
```

Also if you could include the steps you are taking for exercising bash-completion too.
Thanks

**Comment by smarsching** [comment]
@dmurphy18 In the official Ubuntu repositories, Salt is only available for Ubuntu 18.04 and 22.04 (see the list [here](https://launchpad.net/ubuntu/+source/salt)), so I tested it with Ubuntu 22.04, which provides the packages of the Ubuntu fork of Salt in version 3004.1+dfsg-2.

I can confirm that the bug is also present in that version: Bash-completion does not work after installing the packages. After creating the missing symlinks, it does work.

**Comment by dmurphy18** [comment]
:rofl: that bash-completion has not basically changed since 2015.
Wondering what you are doing exactly to test it and show the problem, requested that information in https://github.com/saltstack/salt/pull/66852#issuecomment-2334342547.  Cannot really proceed till I can duplicate your exact steps.

**Comment by smarsching** [comment]
@dmurphy18 Yes, it really is funny that it seems like on Debian / Ubuntu this has been broken like forever and no one noticed. 🤣

I am sorry that I forgot to explain the steps that I use for testing bash-completion.

1. Install packages salt-common and salt-master.
2. Open a fresh login shell (on a Desktop system, opening a new terminal window typically is sufficient, otherwise, logging out and back in is the easiest way to ensure that one has a fresh login shell).
3. Type the command followed by a space (e.g. `salt-key `) and hit the tab key.

If bash-completion works a `-` will be added to the command line. After hitting tab again **twice**, a list of all the options for the salt-key- command is printed. For example:

```
--accept-all          --out=highstate       -A
--accept=             --out=json            -D
--config-dir=         --out=key             -F
--delete-all          --out=overstatestage  -L
--delete=             --out=pprint          -P
--finger-all          --out=raw             -R
--finger=             --out=txt             -a
--gen-keys-dir=       --out=yaml            -c
--gen-keys=           --print-all           -d
--help                --print=              -f
--key-logfile=        --quiet               -h
--keysize=            --reject-all          -l
--list-all            --reject=             -p
--list=               --version             -q
--no-color            --versions-report     -r
--out-indent=         --yes                 -y
```
If bash-completion does not work, a list of the files in the local directory is printed instead.

**Comment by dmurphy18** [comment]
@smarsching Well implemented the symbolic links for salt-common and salt-master as you suggested, rebuilt and it doesn't work as you desire, that is, bash completion got list of files in local directory
```
root@tdebian12:/home/david/dev# salt-key salt
salt_3006.9+98.g462fdcd3cb_amd64.build       salt_3006.9+98.g462fdcd3cb.dsc               salt-cloud_3006.9+98.g462fdcd3cb_amd64.deb   salt-master_3006.9+98.g462fdcd3cb_amd64.deb  salt-syndic_3006.9+98.g462fdcd3cb_amd64.deb
salt_3006.9+98.g462fdcd3cb_amd64.buildinfo   salt_3006.9+98.g462fdcd3cb.tar.xz            salt-common_3006.9+98.g462fdcd3cb_amd64.deb  salt-minion_3006.9+98.g462fdcd3cb_amd64.deb  
salt_3006.9+98.g462fdcd3cb_amd64.changes     salt-api_3006.9+98.g462fdcd3cb_amd64.deb     salt-dbg_3006.9+98.g462fdcd3cb_amd64.deb     salt-ssh_3006.9+98.g462fdcd3cb_amd64.deb     
root@tdebian12:/home/david/dev# salt-key -
Accepted Keys:
Denied Keys:
Unaccepted Keys:
Rejected Keys:
root@tdebian12:/home/david/dev# l /usr/share/bash-completion/completions/salt*
lrwxrwxrwx 1 root root   11 Sep 12 11:25 /usr/share/bash-completion/completions/salt-key -> salt-common
lrwxrwxrwx 1 root root   11 Sep 12 11:25 /usr/share/bash-completion/completions/salt-cp -> salt-common
lrwxrwxrwx 1 root root   11 Sep 12 11:25 /usr/share/bash-completion/completions/salt-call -> salt-common
lrwxrwxrwx 1 root root   11 Sep 12 11:25 /usr/share/bash-completion/completions/salt -> salt-common

/usr/share/bash-completion/completions/salt-common:
total 52K
-rw-r--r-- 1 root root  10K Sep 12 11:25 salt-common.bash-completion
drw-r-xr-x 2 root root 4.0K Sep 13 10:30 .
drwxr-xr-x 3 root root  36K Sep 13 10:30 ..
root@tdebian12:/home/david/dev# 
```

Please take a look at the latest packages and see if there is anything obvious as to why it did not work as you thought it would.
Given the now small size of the Salt Core Team, it might be a while giving this more attention, but I need to re-read bash completion to see if this is working as intended, given a decade and no one complaining about it being broken.

**Comment by smarsching** [comment]
@dmurphy18 I think that I know what it is happening here:

The line `pkg/debian/salt-common.bash-completion /usr/share/bash-completion/completions/salt-common` has to be removed from `salt-common.install`.

This line causes the file from `pkg/debian/salt-comon.bash-completion` to be copied to ` /usr/share/bash-completion/completions/salt-common/salt-comon.bash-completion`. Then, `dh_bash-completion` copies it again, and because the destination of the copy operation (`/usr/share/bash-completion/completions/salt-common`) is an existing directory, the file is copied *inside* this directory instead of to the destination.

I believe that removing the aforementioned line from `salt-common.install` is going to fix this issue. This way, `dh_bash-completion` is going to copy the file to the correct location and the symlinks should work.

Can you please give it a try and remove this line? I will then test the resulting packages.

Apparently, there is a bug in `dh_bash-completion` that causes the file to be installed in the wrong location whn

**Comment by dmurphy18** [comment]
@smarsching Will do, funny ``` bug in dh_bash-completion ```, errors on top of errors :rofl:

**Review by twangboy — APPROVED** [review]

**Comment by smarsching** [comment]
@dmurphy18 I just tested the packages from the most recent CI build and bash-completion works. 🎉

Thank you for your efforts! 👍👍👍

**Comment by dmurphy18** [comment]
@smarsching But the CI/CD is done yet :rofl: , great news, once the CI/CD testing passes, will put this out for review by the team

**Comment by smarsching** [comment]
@dmurphy18 You are right, it isn’t done yet, but the job that builds the Debian / Ubuntu packages was already done, so I could test them right away. 😄

**Pull request merged**
