### PR TITLE
Fix password parsing in ssh sessions

### PR DESCRIPTION
**Pull request by dh-harald**

### CODE REVIEW

**Comment by rallytime** [comment]
Thanks @dh-harald! There is a [lint error](https://jenkins.saltstack.com/job/salt-pr-lint-n/6768/violations/file/salt/utils/cloud.py/) related to your pull request. Would you mind fixing that up?

**Comment by dh-harald** [comment]
Hi,

Sorry, somewhere i've lost that variable declaration, to fix it, you need to add is_not_checked = True

Thanks

**Comment by techhat** [comment]
@dh-harald So far looking through the history, I'm not seeing where `is_not_checked` ever existed in that file. Where did you find it?

**Comment by dh-harald** [comment]
Hi,

Here it's my fix :)

**Comment by dh-harald** [comment]
This fix about, if you need to decide, that console, asks for your password, you need to check only for first row (Password:), not the whole console output

**Comment by thatch45** [comment]
Thanks @dh-harald !

**Pull request merged**
