### PR TITLE
[master] Porting #52670 to master again

### PR DESCRIPTION
**Pull request by OrangeDog**
Porting #52670 to master again, because the last one (#54572) got reverted by #56353.

When this is merged, https://github.com/saltstack/salt-pack/issues/682 needs reverting.

### CODE REVIEW

**Review by waynew — APPROVED** [review]

**Review by waynew — CHANGES_REQUESTED** [review]
Ah, boo, looks like needs pre-commit hooks :upside_down_face:

**Comment by OrangeDog** [comment]
> Ah, boo, looks like needs pre-commit hooks 🙃

Apparently so, but it already ran them when I committed,

**Review by waynew — APPROVED** [review]
:rocket:

**Comment by bryceml** [comment]
don't ifup and ifdown set things up according to what's specified in /etc/network/interfaces as opposed to `ip link set up` which doesn't have anything to do with /etc/network/interfaces ?

This seems like it doesn't keep the same behavior at all if I understand it correctly.

**Review by s0undt3ch — APPROVED** [review]

**Review by bryceml — CHANGES_REQUESTED** [review]
This would break existing use of ifupdown on debian 10, this probably needs a much bigger PR to do the correct thing.

**Comment by OrangeDog** [comment]
@bryceml if that's true, and nobody noticed on the previous two PRs, it should be tracked with #57541 and related.

**Comment by OrangeDog** [comment]
> It would probably be more correct to do something like nmcli con up ... or nmcli con down ... if using network manager. I'm not sure how you would get the equivilant on netplan since it only really has netplan apply

`netplan` is a higher-level config management system. The alternative to `NetworkManager` is `systemd-networkd`. I don't think there is any CLI other than `ip`. You just edit the config files and reload.

**Comment by sagetherage** [comment]
@OrangeDog we want to have a deep discussion on this since likely needs to be bigger than this PR and we need to discuss a broader solution. I am putting it into blocked for now, but I will schedule a planning meeting to dive deeper. I would love your input, I know our US meeting are difficult to attend, but I am open to other ideas the use of other platforms if that is helpful.

**Comment by OrangeDog** [comment]
I have no particular investment. I just noticed this PR has at least twice already been merged and then lost.

The concept is not difficult. You should be using the recommended commands on each of your supported operating systems and not relying on deprecated and removed packages. You need to work out what they are and then write that code. I think that `ip` is the default method on every linux OS version you support, but I may be mistaken.

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
