### PR TITLE
[2019.2.1] Fix static requirements

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
Static requirements now take into account the packaging requirements for Windows and OSX

### CODE REVIEW

**Review by garethgreenaway — APPROVED** [review]

**Comment by dwoz** [comment]
re-run full all

**Review by dwoz — APPROVED** [review]

**Comment by dwoz** [comment]
re-run full all

**Review by twangboy — APPROVED** [review]

**Comment by dwoz** [comment]
Lets just wait and see what a full test run does here.

**Comment by s0undt3ch** [comment]
re-run full all

**Pull request merged**
