### PR TITLE
"file.line" minor fixes

### PR DESCRIPTION
**Pull request by isbm**
These fixes are based on a feedback.

### CODE REVIEW

**Comment by cachedout** [comment]
@isbm There is a very minor lint error here. If you could fix that then we will get this merged right away. Thanks!

**Comment by isbm** [comment]
@cachedout This is what happens when you are in a different time zone, pushing to Git almost at the doorstep! Thanks, fixed.

**Comment by isbm** [comment]
@cachedout While it was a bit a time, I've added here another feature: keep line indent with the previous line.

**Comment by isbm** [comment]
@cachedout I am going away now (end of the day) but will check this in one hour, if everything OK.

**Comment by jfindlay** [comment]
@isbm, looks great, thanks.

**Pull request merged**
