### PR TITLE
Test True support for INI state module.

### PR DESCRIPTION
**Pull request by jirikotlin**
Dry run - support for running INI state module with test=True option.

### CODE REVIEW

**Comment by cachedout** [comment]
@jirikotlin This PR does not pass the INI tests. Could you please take a look?

**Comment by jirikotlin** [comment]
Hello @cachedout ,

I am not sure about this. But I suppose that INI tests are expecting the behaviour which I actually changed. 

Running with if __opts__['test'] does not return result with comment "ini file salt shall be validated for absence of given options under...." but performs dry run.

Is this the problem please?

We were not sure why this module does not have dry run implemented, should be useful...

**Comment by jirikotlin** [comment]
These tests are expecting results from salt state module init_manage without dry run implemented (test=True allways returns True with comment 'ini file salt shall be validated for absence...'). But this is the functionality I am trying to implement. Any suggestions please?

**Comment by jirikotlin** [comment]
Modified ini_manage_test.py also, should be ok with ini tests now.

**Comment by cachedout** [comment]
Merged. Thanks, @jirikotlin

**Pull request merged**
