### PR TITLE
[DOC] Add doc page reference for schedule util module

### PR DESCRIPTION
**Pull request by vutny**
### What does this PR do?
Since Salt documentation pages do not expose docstrings for utility modules (yet?), it is unnecessary to have the same thing described it two distinct places.

Good example is `shedule` utility module. It contains a docstring which mostly copy-paste of `doc/topics/jobs/index.rst` file, but has some sections duplicated and in different order. The content is exactly the same though.

This PR aims to remove duplicate information and keep maintaining it in single place. The `schedule` docstring will contain file and rST reference to the documentation page for the module in case if utils generated docs would be available in the future.

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by vutny** [comment]
Rebased with latest `2016.11`.

**Comment by garethgreenaway** [comment]
Definitely a good idea.  Not sure if 2016.11 is the right place for it.  Would be a good change for the Oxygen release or even the release after.

**Comment by vutny** [comment]
@garethgreenaway Would consider you merge it forward up to `develop`?
Or you want me to submit a forward-port?

AFAIK, the schedule module haven't changed that much, so there wouldn't be conflicts I assume.
My main motivation behind this PR is that if you need to fix or correct the module doc, you need to remember to alter it in two distinct places.

**Comment by garethgreenaway** [comment]
@vutny Apologies for the delay.  I think it makes more sense for the change to be made against the new oxygen branch, then we start the new release off with the new location for the updated documentation.

**Comment by vutny** [comment]
Thanks @garethgreenaway , no worries. I will resubmit my PR against `oxygen` branch.

**Comment by garethgreenaway** [comment]
@vutny Much appreciated!

**Pull request closed without merging**
