### PR TITLE
Create reg salt util (2018.3)

### PR DESCRIPTION
**Pull request by twangboy**
Originally submitted against 2018.3.0rc1. https://github.com/saltstack/salt/pull/46527

### What does this PR do?
Creates a salt util for working with the registry (`salt/utils/win_reg.py`)
Use the reg salt util to get grains
Use the reg salt util in the reg module
Use the reg salt util in the reg state
Use the reg salt util to get the PowerShell version
Detect the version of PowerShell instead of the version of Windows to determine ConvertTo-JSON usage (The whole purpose for all of this)

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/pull/46501

### Previous Behavior
Basing `ConvertTo-JSON` on the version of Windows is incorrect. Although correct on a fresh install of Windows 7, PowerShell can be upgraded, at which point `ConvertTo-JSON` would be available.

### Tests written?
No

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by rallytime** [comment]
Can you write some tests for the new utils file, please? :)

**Comment by rallytime** [comment]
@twangboy Some lint here: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/20215/violations/file/salt/modules/reg.py/

**Comment by twangboy** [comment]
@rallytime Fixed the lint error

**Review by cachedout — APPROVED** [review]

**Comment by cachedout** [comment]
@twangboy There are merge conflicts here as well.

**Comment by rallytime** [comment]
@twangboy Please fix lint: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/20368/violations/file/tests/unit/utils/test_win_reg.py/

**Comment by twangboy** [comment]
@rallytime Done

**Review by rallytime — APPROVED** [review]

**Pull request merged**
