### PR TITLE
Swift rackspace fixes

### PR DESCRIPTION
**Pull request by erchn**
I was unable to get the Swift module to work correctly with Rackspace cloud files.  Setting auth_version is the first hurdle, I also allowed you to set api_key instead of password, as they are separate desired use cases, also the utils/openstack/swift.py module allows one or the other, so the module shouldn't barf on a missing `keystone.password` field.

### CODE REVIEW

**Comment by erchn** [comment]
Note, I was careful to not break any backwards compatibility, aside from this working for more people nobody should notice. :-)

**Comment by erchn** [comment]
I realized the commit to `utils/openstack/swift.py` was unnecessary, reverted.

**Comment by jfindlay** [comment]
@erchn, thanks for the fix.  In the future you are welcome to submit fixes directly to the oldest supported release branch, see https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

**Comment by erchn** [comment]
Ahh, my bad ill do that in the future. So you'd recommend 2015.5 at this point?

**Comment by jfindlay** [comment]
@erchn, no problem.  We will backport it to 2015.5 unless you would rather do it.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Pull request merged**
