### PR TITLE
[develop] Removing deprecation warnings from client/mixins.py

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Removing deprecation warnings from client/mixins.py for Fluorine release.

### What issues does this PR fix or reference?
#44739

### Tests written?
Yes.  Tests exist.

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by rallytime — APPROVED** [review]

**Review by terminalmage — COMMENTED** [review]
We made a similar change to how we accept args for 2017.7, and it turned out that salt-api needed that usage. Have we evaluated this to ensure that it's not going to break spawning jobs from the API?

**Comment by rallytime** [comment]
@garethgreenaway Can you follow up here on the question about when you get a moment?

**Comment by cachedout** [comment]
@garethgreenaway ^^

**Comment by garethgreenaway** [comment]
Circle back to this one.  @terminalmage Do you remember any particular jobs that were run through the API that caused problems?  I've tried a few basic things and they are working as expected.

**Comment by terminalmage** [comment]
@garethgreenaway I think that salt-api was affected, for one.

**Comment by rallytime** [comment]
@garethgreenaway and @terminalmage What's the status of this?

**Comment by rallytime** [comment]
Bump @garethgreenaway and @terminalmage see question above ^:)

**Comment by rallytime** [comment]
@garethgreenaway Bump

**Comment by garethgreenaway** [comment]
Circling back to this.  There are existing netapi integration tests that were passing the last time I looked at this.  I just updated the branch and will check the results once the tests are finished.

**Comment by terminalmage** [comment]
The tests do appear to be passing.

**Pull request merged**
