### PR TITLE
Some more features for napalm_network

### PR DESCRIPTION
**Pull request by mirceaulinic**
### What does this PR do?

Some more features for the napalm_network execution module (net):
- `discard_config`: essential function, no idea why not there yet
- `load_config`: to load static config on the device
- `load_template`: to render a template and load the result on the device

### Tests written?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by mirceaulinic** [comment]
I would like to ask someone to double check the documentation - I pretty sure I have some typos over there (no necessarily now, but please consider this before releasing Carbon). And also PRs from yesterday: https://github.com/saltstack/salt/pull/37275 and https://github.com/saltstack/salt/pull/37277.

Thanks!

**Comment by cachedout** [comment]
Hi @mirceaulinic 

Thanks for this. I looked at the docs for all three PRs and they look fine to me.

We do need some minor style issues cleaned up on this please: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/6369/violations/file/salt/modules/napalm_network.py/

Thanks!

**Comment by mirceaulinic** [comment]
Thanks for pointing this out @cachedout - removed that line.

**Comment by mirceaulinic** [comment]
Thanks for the fix @cachedout!

**Pull request merged**
