### PR TITLE
[oxygen] Adding tests for cron functionality.

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Adding tests for cron functionality.

### What issues does this PR fix or reference?
N/A

### Previous Behavior
No tests for cron functionality in the scheduler existed.

### New Behavior
Adding tests for cron functionality in the scheduler.

### Tests written?
Yes

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by rallytime** [comment]
Yay tests!

**Comment by rallytime** [comment]
@garethgreenaway Looks like some tests aren't happy here: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/18032/

**Comment by garethgreenaway** [comment]
@rallytime It's failing because the `croniter` module isn't installed when the tests are running.

**Comment by rallytime** [comment]
@garethgreenaway Then these tests need to be gated so they don't run when croniter is missing and get it installed in our salt-jenkins states so the tests run on our test VMs.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Review by rallytime — APPROVED** [review]

**Pull request merged**
