### PR TITLE
Fix GCE Windows instances being identified as physical by core grains

### PR DESCRIPTION
**Pull request by kvasserman**
### What does this PR do?
Fixes GCE Windows instances being identified as physical by core grains

### Previous Behavior
GCE Windows instances had 'virtual' grain set to 'physical'

### New Behavior
GCE Windows instances will have 'virtual' grain set to 'gce' (the same as Linux GCE instances)

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Review by Ch3LL — CHANGES_REQUESTED** [review]
can you write a regression test for this? thanks

**Comment by kvasserman** [comment]
@Ch3LL Maybe. Do you have any documentation on how one should approach doing this in your project? Also, if I do write the test, should it be a separate PR with just the test or do I create a completely new one with both the current changes + the test? Thank you.

**Comment by Ch3LL** [comment]
@kvasserman our test documentation is located here:

https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html

my suggestion would be a unit test for this change.

**Comment by Ch3LL** [comment]
also to answer your other question:

> Also, if I do write the test, should it be a separate PR with just the test or do I create a completely new one with both the current changes + the test?

Just keep it in this PR so we can make sure the test passes when it runs :)

**Comment by kvasserman** [comment]
Unfortunately, I don't think I will be able to find the time to write the unit tests for this.

**Pull request closed without merging**
