### PR TITLE
[develop] Update pipelines to work on old and new jenkins

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title.

### CODE REVIEW

**Review by Akm0d — APPROVED** [review]

**Review by DmitryKuzmenko — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Review by bryceml — APPROVED** [review]

**Comment by s0undt3ch** [comment]
Please DO NOT merge.

I'll merge this one.

**Comment by s0undt3ch** [comment]
Please DO NOT merge.

I'll merge this one.

**Comment by s0undt3ch** [comment]
A

**Comment by s0undt3ch** [comment]
re-run all

**Comment by s0undt3ch** [comment]
Thrice voted, merging.

**Pull request merged**
