### PR TITLE
[master] Porting #50622 to master

### PR DESCRIPTION
**Pull request by garethgreenaway**
Porting #50622 to master

### CODE REVIEW

**Comment by garethgreenaway** [comment]
re-run full all

**Comment by dwoz** [comment]
This PR needs the `salt.utils.thread_local_proxy` module to merge cleanly

**Comment by garethgreenaway** [comment]
Requires https://github.com/saltstack/salt/pull/50655

**Comment by Akm0d** [comment]
#50655 is being merged into master in https://github.com/saltstack/salt/pull/54878
Should I cherrypick commits from this PR into that one?

**Pull request closed without merging**
