### PR TITLE
Handle the situation when apt repo lines have or do not have trailing slashes properly

### LINKED ISSUE #60907: [BUG] `pkgrepo.managed` always trigger changes if url ends with `/`
**Description**
After migrating to py3, I see that salt always wants to update package repos, if their definition contains templated values. Repositories are already setup.

**Setup**

Master/minion running salt 3003.3, Debian 9 VMs in AWS
- [x] VM running on a cloud service, please be explicit and add details
  
**Steps to Reproduce the behavior**
```
php1-repo:
  pkgrepo.managed:
    - humanname: PHP7.1 repository
    - name: deb https://packages.sury.org/php/ {{ grains.lsb_distrib_codename }} main
    - file: /etc/apt/sources.list.d/php1.list
    - key_url: https://packages.sury.org/php/apt.gpg
    - refresh: False

php2-repo:
  pkgrepo.managed:
    - humanname: PHP7.1 repository
    - name: deb https://packages.sury.org/php/ stretch mainXXX # make it unique for this example
    - file: /etc/apt/sources.list.d/php2.list
    - key_url: https://packages.sury.org/php/apt.gpg
    - refresh: False
```

then run `state.apply` twice

**Expected behavior**
First run should add two package repositories. Second run should not detect any changes.

**Screenshots**
After applying state once, second (and each next) run still wants to change php1 repo:
```
local:
  Name: deb https://packages.sury.org/php/ stretch main - Function: pkgrepo.managed - Result: Differs Started: - 14:06:36.967772 Duration: 69.358 ms
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003.3

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.5.3
     docker-py: Not Installed
         gitdb: 2.0.0
     gitpython: 2.1.1
        Jinja2: 2.9.4
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.5.3 (default, Apr  5 2021, 09:00:41)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: 2.0.1
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.1

System Versions:
          dist: debian 9 stretch
        locale: UTF-8
       machine: x86_64
       release: 4.9.0-16-amd64
        system: Linux
       version: Debian GNU/Linux 9 stretch

```
</details>

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Handle the situation when apt repo lines have or do not have trailing slashes properly

### What issues does this PR fix or reference?
Fixes: #60907 #61483

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by Ch3LL** [comment]
re-run full all

**Comment by nicholasmhughes** [comment]
re-run pr-freebsd-131-amd64-py3-pytest

**Comment by garethgreenaway** [comment]
re-run full all

**Comment by garethgreenaway** [comment]
re-run full all

**Comment by nicholasmhughes** [comment]
re-run pr-ubuntu-2204-amd64-py3-pycryptodome-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-photon-3-x86_64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-fedora-35-x86_64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-centos-7-x86_64-py3-tcp-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-ubuntu-2204-amd64-py3-pycryptodome-pytest

**Comment by nicholasmhughes** [comment]
@garethgreenaway , I looked at the final test error and it seems that options aren't being passed around properly in the tests. The `rtag` variable referenced in the test is derived from the `cachedir` option, but there was a different `cachedir` being gathered from `__opts__` inside the function.


I wasn't sure of the best way to patch `__opts__` when we're referencing a virtual name instead of a direct import (`configure_loader_modules` doesn't like the `modules` fixture), so I just recreated the `modules` object inside the test with the proper options instead of using the fixture. The patch below seems to get this test passing on Ubuntu 22.04:


```diff
diff --git a/tests/pytests/functional/modules/test_pkg.py b/tests/pytests/functional/modules/test_pkg.py
index 7f2fa097ff..dd76401ba5 100644
--- a/tests/pytests/functional/modules/test_pkg.py
+++ b/tests/pytests/functional/modules/test_pkg.py
@@ -9,6 +9,7 @@ import pytest
 import salt.utils.path
 import salt.utils.pkg
 import salt.utils.platform
+from saltfactories.utils.functional import Loaders
 
 log = logging.getLogger(__name__)
 
@@ -319,7 +320,7 @@ def test_hold_unhold(grains, modules, states, test_pkg):
 @pytest.mark.requires_salt_modules("pkg.refresh_db")
 @pytest.mark.slow_test
 @pytest.mark.requires_network
-def test_refresh_db(grains, modules, tmp_path, minion_opts):
+def test_refresh_db(grains, tmp_path, minion_opts):
     """
     test refreshing the package database
     """
@@ -327,7 +328,8 @@ def test_refresh_db(grains, modules, tmp_path, minion_opts):
     salt.utils.pkg.write_rtag(minion_opts)
     assert os.path.isfile(rtag) is True
 
-    ret = modules.pkg.refresh_db()
+    loader = Loaders(minion_opts)
+    ret = loader.modules.pkg.refresh_db()
     if not isinstance(ret, dict):
         pytest.skip("Upstream repo did not return coherent results: {}".format(ret))
 
```

**Comment by nicholasmhughes** [comment]
re-run pr-debian-9-amd64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-windows-2016-x64-py3-pytest

**Review by twangboy — DISMISSED** [review]

**Review by Ch3LL — CHANGES_REQUESTED** [review]
changelog?

**Pull request merged**
