### PR TITLE
Restore support to generate thin tarballs with local packages

### PR DESCRIPTION
**Pull request by bbinet**
See: https://github.com/saltstack/salt/pull/35997#discussion_r100556792

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@bbinet Could you rebase this against develop? For some reason, the test suite thinks we're on the wrong checksum here. (Not sure why, but that may fix it.)

**Comment by bbinet** [comment]
Done.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Pull request merged**
