### PR TITLE
Support expr_form for manage.up, manage.down

### PR DESCRIPTION
**Pull request by ghost**
### What does this PR do?
Support expr_form for manage.up, manage.down. This allows a smoother transition to 2017.7

### What issues does this PR fix or reference?
2017.7 breaks the usage of `expr_form` even though there should be a transition phase where both `expr_form` and `tgt_type` should be supported.

### Previous Behavior
Fail von `expr_form`.

### New Behavior
Show transition warning and support both `expr_form` and `tgt_type` for the time being.

### Tests written?
No

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by rrroo** [comment]
This should be backported to 2017.7.

**Review by terminalmage — APPROVED** [review]
@rallytime Note that when backporting, `salt.utils.versions.warn_until` will not exist. So we'll need to use `salt.utils.warn_until`, and then correct that in Oxygen during the merge-forward.

**Comment by terminalmage** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
re-run lint

**Comment by rallytime** [comment]
Hi @rrroo - the remaining test failures are not related. Thank you for your work here!

**Comment by rrroo** [comment]
@rallytime Thanks for the merge!

**Pull request merged**
