### PR TITLE
Fix wheel module bug

### PR DESCRIPTION
**Pull request by thatch45**
### What does this PR do?

When the server is set to 0.0.0.0 then the wheel connection breaks, we found this testing master on Windows

### CODE REVIEW

**Comment by twangboy** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
This doesn't seem right to me. Even though this might be a Windows bug, wouldn't other platforms _want_ `0.0.0.0` to represent all interfaces?

**Comment by thatch45** [comment]
No, not for wheel interaction, wheel interaction is preferred to be on localhost, and if it is available then we should use it. Wheel calls to the master are always spawned locally

**Comment by cachedout** [comment]
Fair enough. We should document this then, because this sort of silent changing about of bindings is slightly evil. ;]

**Pull request merged**
