### PR TITLE
disk grain: Do not report Virtual Device as SSDs

### PR DESCRIPTION
**Pull request by wido**
Device Mapper (LVM), Bcache and VirtIO devices are reported as
SSDs by this grain, but since they are virtual we can not report
them as SSDs.

### What does this PR do?
The SSDs grain no longer reports Virtual Devices like LVM, Bcache and VirtIO as SSDs.

### What issues does this PR fix or reference?
It fixes issue #51898 

### Previous Behavior

<pre>
    SSDs:
        - sda
        - sdb
        - sdc
        - sdd
        - sde
        - sdf
        - sdg
        - sdh
        - sdi
        - dm-0
        - dm-1
        - dm-2
        - dm-3
        - dm-4
        - dm-5
        - dm-6
        - dm-7
</pre>

### New Behavior
<pre>
    SSDs:
        - sda
        - sdb
        - sdc
        - sdd
        - sde
        - sdf
        - sdg
        - sdh
        - sdi
</pre>

### Tests written?
No

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by Ch3LL — CHANGES_REQUESTED** [review]
thanks for the PR! would you mind adding a test so this does not regress in the future?

**Comment by wido** [comment]
Where would I add these tests? Unit Testing isn't my strongest point and I'm not completely sure with how this works within Salt.

**Comment by Ch3LL** [comment]
there is some documentation here: https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html on the test runner which should add some more context on how to add tests for salt.

The best place to add this test would be tests/unit/grains/test_disks.py

**Comment by dwoz** [comment]
@wido I've rebased this on top of master and changed the base branch of the PR, this still need tests though.

**Pull request closed without merging**
