### PR TITLE
INFRA-5980 - Fix test=True logic bug in boto_dynamodb.present state function

### PR DESCRIPTION
**Pull request by tkwilliams**
Tries do do stuff with a db table it has already determined doesn't exist :)

```
[INFO    ] Executing state boto_dynamodb.present for [plt-dev-fcemr-ks-01]
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1825, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1728, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/boto_dynamodb.py", line 332, in present
    profile
  File "/usr/lib/python2.7/site-packages/salt/modules/boto_dynamodb.py", line 284, in describe
    return table.describe()
  File "/usr/lib/python2.7/site-packages/boto/dynamodb2/table.py", line 356, in describe
    result = self.connection.describe_table(self.table_name)
  File "/usr/lib/python2.7/site-packages/boto/dynamodb2/layer1.py", line 978, in describe_table
    body=json.dumps(params))
  File "/usr/lib/python2.7/site-packages/boto/dynamodb2/layer1.py", line 2842, in make_request
    retry_handler=self._retry_handler)
  File "/usr/lib/python2.7/site-packages/boto/connection.py", line 954, in _mexe
    status = retry_handler(response, i, next_sleep)
  File "/usr/lib/python2.7/site-packages/boto/dynamodb2/layer1.py", line 2885, in _retry_handler
    data)
JSONResponseError: JSONResponseError: 400 Bad Request
{u'message': u'Requested resource not found: Table: plt-dev-fcemr-ks-01 not found', u'__type': u'com.amazonaws.dynamodb.v20120810#ResourceNotFoundException'}
```

### CODE REVIEW

**Comment by rallytime** [comment]
@tkwilliams This change breaks some of the tests written for this area. Can you take a look?

**Comment by tkwilliams** [comment]
@rallytime  Youbetcha :)

**Comment by ryan-lane** [comment]
Hm, yeah. Probably reasonable. +1 :)

**Comment by tkwilliams** [comment]
@rallytime Sorry, getting a "Not Found" on the links to the jenkins fails - any chance you could re-fire this puppy so I can see if it's something I broke or just general contrariness on Jenkin's part?  :)

**Comment by rallytime** [comment]
@tkwilliams Definitely 👍

**Comment by tkwilliams** [comment]
@rallytime No matter how many times I re-fire the build, I can't seem to get in fast enough to see what the failures are before they're deleted.... 
```
HTTP ERROR 404

Problem accessing /job/PR/job/salt-pr-linode-ubuntu16-py3/4057/. Reason:

    Not Found
```

We might want to increase the retention period back to something which allows people to get in and debug their issues :)

**Comment by rallytime** [comment]
@tkwilliams Yes, increasing the amount of time we keep job builds around has been on my mind. Thanks for the reminder - the number of jobs we keep around has been doubled.

If this times out before you have a chance to swing back around, here the output from the test failure:
- unit.states.test_boto_dynamodb.BotoDynamodbTestCase.test_present 
```
Traceback (most recent call last):
  File "/testing/tests/unit/states/test_boto_dynamodb.py", line 63, in test_present
    self.assertDictEqual(boto_dynamodb.present(name), ret)
AssertionError: {'comment': 'DynamoDB table new_table would be created.', 'changes': {}, 'name': [truncated]... != {'comment': 'DynamoDB table new_table would be created.,\nDynamoDB table new_tab [truncated]...
  {'changes': {},
-  'comment': 'DynamoDB table new_table would be created.',
+  'comment': 'DynamoDB table new_table would be created.,\nDynamoDB table new_table throughput matches,\nAll global secondary indexes match,\n',
   'name': 'new_table',
   'result': None}
```

**Comment by rallytime** [comment]
@tkwilliams Almost there, but still failing that same test:
```
Traceback (most recent call last):
  File "/testing/tests/unit/states/test_boto_dynamodb.py", line 61, in test_present
    self.assertDictEqual(boto_dynamodb.present(name), ret)
AssertionError: {'comment': 'DynamoDB table new_table would be created.', 'changes': {}, 'name': [truncated]... != {'comment': 'DynamoDB table new_table would be created.,\n', 'name': 'new_table' [truncated]...
  {'changes': {},
-  'comment': 'DynamoDB table new_table would be created.',
+  'comment': 'DynamoDB table new_table would be created.,\n',
?                                                        +++

   'name': 'new_table',
   'result': None}
```

**Comment by tkwilliams** [comment]
@rallytime I think we cross-posted :)  My last tweak https://github.com/saltstack/salt/pull/44526/commits/c03112dbb0b5db6a823ff6cb41210ae08184c74a resolves the leftover ',\n'

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
Oh, you're right @tkwilliams. Thanks!

**Pull request merged**
