### PR TITLE
[WIP] AWS Budgets (boto3)

### PR DESCRIPTION
**Pull request by Waples**
# AWS Budgets

### What does this PR do?
This PR adds missing functionality for (AWS) Amazon Budgets service. It introduces `salt/modules/boto3_budgets.py` and `salt/states/boto3_budgets.py` to provide this functionality.

### What issues does this PR fix or reference?
None (missing behavior).

### Previous Behavior
None (missing behavior).

### New Behavior
Adds:
- salt/modules/boto3_budgets.py
  - all boto3 functions for [AWS Budgets](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/budgets.html)
- salt/states/boto3_budgets.py _(still work in progress)_
  - budget_absent
  - budget_present
  - notification_absent
  - notification_present
  - subscriber_absent
  - subscriber_present
- salt/utils/dictdiffer.py:
  - recursive_diff2 _(adds a better working dict comparison utility)_

### Tests written?
No

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by waynew** [comment]
@Waples looking nice - are you also planning to add some tests?

**Comment by waynew** [comment]
@Waples would you be willing/interested in rebasing this on master, in addition to writing the tests?

**Comment by mchugh19** [comment]
I'm not sure if tests for the boto calls make the most sense. Every function is just a try boto call, catch boto error: 
```
conn = _get_conn(keyid=keyid, key=key, region=region, profile=profile)
try:
    res = conn.update_notification(AccountId=account_id, BudgetName=budget_name,
            OldNotification=old_notification, NewNotification=new_notification)
    return {'result': res}
except (ParamValidationError, ClientError) as err:
    return {'error': __utils__['boto3.get_error'](err)}
```
Thus, there's no logic managed by salt. Mocking each boto call wouldn't do anything other than validate the boto library. So this could possibly be covered by a boto minimum version validation test and call it a day. 

As for recursive_diff2, it isn't used in the boto budget state. What's the expected use-case? Maybe that should be split into its own PR where it is deployed into the codebase?

**Comment by Waples** [comment]
Hey @waynew, I haven't been working on this for a while and just got back from holiday. I share @mchugh19 's thoughts about the test, it would just be boto validation. 

@mchugh19, see above, I haven't worked on this for a while and it is still marked as WIP. I remember I needed the custom recursive_diff2 function for something, but can't provide the needed information at this time.

I can probably find some time during business hours this week to update this PR.

**Comment by waynew** [comment]
Hey @Waples I hope this finds you well!

Do you have any interest in driving this to completion?

**Comment by waynew** [comment]
@Waples were you able to find any time to work on this?

**Review by waynew — CHANGES_REQUESTED** [review]
Hey, @Waples, thanks again for the PR! We definitely appreciate your efforts so far! We realize that priorities can change, and contributing to Salt may not be at the top of your list. If this is the case for you, no response needed - if we haven't heard back from you after a week, we'll go ahead and close this PR and add the "on hold" label. At any point in the future if you (or someone else) is ready to pick this back up, just let us know and we'll be happy to re-open the PR so we can get it merged.

If you need help writing documentation, we have a [documentation working group](https://github.com/saltstack/docs-hub) that would love to help out.

If you're struggling with writing tests, reach out to the [testing working group](https://github.com/saltstack/community/tree/master/working_groups/wg-Testing) or attend one of the [Test Clinics on Twitch](https://www.twitch.tv/saltstackinc/schedule).

Thanks again!

**Comment by Waples** [comment]
I've abandoned work on my PRs for SaltStack since I have other priorities. Maybe see you guys again in the future.

**Pull request closed without merging**
