### PR TITLE
Carbon returner type error fix patch 1

### LINKED ISSUE #61284: [BUG] the carbon returner has a type error
**Description**
There is a type error in the carbon returner, probably caused by the python2 -> python3 migration that has not been handled yet.

**Setup**
One needs to set up a carbon instance for the carbon returner and schedule a munin plugin to be run by the salt-minion scheduler to run any munin plugin on the machine in question and return data using the carbon returner.

Please be as specific as possible and give set-up details.

- [ X] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
  
**Steps to Reproduce the behavior**
Add the following to minion.conf
```
carbon.host: 10.0.0.1
carbon.port: 2003
carbon.mode: text
schedule:
    munin:
        function: munin.run
        args:
            - cpu
        seconds: 60
        returner: carbon
```

Restart the salt minion and wait for the scheduler to run. In the logs the error below appears:
```
2021-11-23 11:42:33,024 [salt.utils.schedule:875 ][ERROR   ][4032195] Unhandled exception running munin.run
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/schedule.py", line 866, in handle_func
    self.returners[ret_str](ret)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/returners/carbon_return.py", line 297, in returner
    _send(saltdata, metric_base, opts)
  File "/usr/lib/python3/dist-packages/salt/returners/carbon_return.py", line 255, in _send
    sent_bytes = sock.send(data[total_sent_bytes:])
TypeError: a bytes-like object is required, not 'str'
```

**Expected behavior**
The data should be sent to the graphite instance.

**Screenshots**
None.

**Versions Report**
```
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: 1.4.4
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: Not Installed
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-8-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>

**Additional context**
I will post a pull request with a very simple fix to this problem.

### PR DESCRIPTION
**Pull request by kresike**
I was experimenting with munin.run and the carbon returner to send some metrics to my graphite instance using the salt minion's scheduler.
This code was obviously written some time ago, and the migration to python3 causes it to misbehave.
Simply using encode on the string to be sent solves the problem.

### What does this PR do?
Fixes the problem described in the referenced issue

### What issues does this PR fix or reference?
Fixes: #61284

### Previous Behavior
Using the carbon returner in text mode generates an error.

### New Behavior
The carbon returner properly sends the data to the graphite instance.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by waynew** [comment]
Hey @kresike thanks for the PR! This will actually be addressed as part of https://github.com/saltstack/salt/issues/61757 - which is a broad effort for adding tests to, and fixing discovered bugs, for all of the returners. If you'd like to add some tests to this PR, :+1:, otherwise we can close the PR once all of the returner API tests are completed

**Comment by MKLeb** [comment]
This needs a changelog and test case @kresike

**Comment by MKLeb** [comment]
Hi @kresike, @waynew is working on a large effort to solidify the returner API's within salt, and this will be addressed there.  Did you want to add some tests and a changelog for this, or close it in favor of Wayne's future PR?

**Comment by Ch3LL** [comment]
Closing due to inactivity. Please let me know if you want me to re-open this PR, or re-open again the master branch. It looks like there are also plans for @waynew to tackle this in his upcoming assigned work.

**Pull request closed without merging**
