### PR TITLE
Backport #20497 to 2015.2

### PR DESCRIPTION
**Pull request by rallytime**
Backport #20497 to 2015.2

### CODE REVIEW

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
I think something funny is happening with the branch. I've rebased to try again.

**Comment by steverweber** [comment]
ref to close when merged.
https://github.com/saltstack/salt/issues/21860

I'll also do some testing to ensure this is a good direction.  cheers

**Comment by steverweber** [comment]
sadly im going to request a revert here... the influxdb python lib is not ready for the new version of influxdb yet and this back-port will likely cause more harm than good at this time.

once the developer has these issues checked off...
https://github.com/influxdb/influxdb-python/issues/109

this influxdb module can be updated.
Sorry for the lost cycles.

**Comment by richard-kti** [comment]
Not sure if https://github.com/influxdb/influxdb-python/issues/109 is being updated - ie issue 108 has been fixed.  The readme states that 0.9 is the recommended version now.

**Pull request merged**
