### PR TITLE
Async flag for test run

### PR DESCRIPTION
**Pull request by cachedout**
Move runners in test suite to sync mode to avoid some race conditions

### CODE REVIEW

**Comment by cachedout** [comment]
Please let the test suite run here before merging

**Comment by rallytime** [comment]
This looks good from cent-7 perspective. Ubuntu didn't run. Wanna grab the pylint error?

**Comment by cachedout** [comment]
That error is actually from a mismatch between this code salt-testing and has already been resolved. You may need to upgrade salt-testing on jenkins however so it doesn't keep complaining.

**Comment by rallytime** [comment]
OK cool. I've updated the salt-testing code on Jenkins, so this should be resolved now.

**Pull request merged**
