### PR TITLE
Correct detect service toggling

### LINKED ISSUE #23713: service.dead is no more stateful
on a ubuntu/trusty host
```
firewalld-conflicting-services:
  service.dead:
    - names: [iptables, ebtables,
              shorewall, shorewall6]
    - enable: false

```
Where  a shorewall6 upstart job does not exists but where an /etc/init.d/shorewall6 exists

```
----------
          ID: firewalld-conflicting-services
    Function: service.dead
        Name: shorewall
      Result: True
     Comment: Service shorewall is already disabled, and is dead
     Started: 16:34:20.959354
    Duration: 21.164 ms
     Changes:
              ----------
              shorewall:
                  True
```

Even if the service is already dead && disabled.

### PR DESCRIPTION
**Pull request by kiorky**
This fixes #23713

the one for #23715 should be merged first
This is  the #23717 one
Signed-off-by: Mathieu Le Marec - Pasquet kiorky@cryptelium.net

### CODE REVIEW

**Comment by kiorky** [comment]
oups, a failed git foo :) i remaking the neccessary stuff.

**Comment by kiorky** [comment]
done

**Comment by jfindlay** [comment]
@kiorky, will you also update the failing unit tests?  Thanks.

**Comment by kiorky** [comment]
Yep, whenever i have the time too

**Comment by kiorky** [comment]
@jfindlay PTAL

**Comment by jfindlay** [comment]
@kiorky, excellent, thank you.

**Pull request merged**
