### PR TITLE
Various documentation fixes

### PR DESCRIPTION
**Pull request by multani**
These are various documentation fixes that I accumulated over time. I'm not sure how to properly send them since they touch various topics.

### CODE REVIEW

**Comment by jfindlay** [comment]
@multani, thanks for the fix.  In the future you are welcome to submit fixes directly to the oldest supported release branch, see https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

@jacobhammons, please review.

**Comment by jacobhammons** [comment]
Thanks @multani!

**Comment by multani** [comment]
Thanks for the merge!
@jfindlay I'll push the fixes on top of the release branch next time, sorry for that.

**Comment by jfindlay** [comment]
@multani, no problem, and thanks for contributing to salt.

**Pull request merged**
