### PR TITLE
[carbon] Merge forward from 2016.3 to carbon

### PR DESCRIPTION
**Pull request by rallytime**
Conflicts:

  - pkg/windows/modules/get-settings.psm1
  - salt/modules/mac_power.py
  - salt/modules/win_dsc.py
  - salt/modules/win_servermanager.py
  - salt/states/file.py
  - salt/utils/event.py
  - salt/utils/gitfs.py

### CODE REVIEW

**Comment by damon-atkins** [comment]
@twangboy  Was their stuff you did not want merged forward?

**Comment by twangboy** [comment]
@rallytime The following should NOT be merged forward:

`Check for Server os before checking` (https://github.com/saltstack/salt/pull/37445)
`Use cmd.run_all instead of cmd.shell` (https://github.com/saltstack/salt/pull/37459)

Sorry, I put it in the Title of the PR. I thought that was what I needed to do. How else should this be handled?

**Comment by twangboy** [comment]
@rallytime Those are probably your `win_dsc.py` and `win_servermanager.py` conflicts...

**Comment by rallytime** [comment]
@twangboy The commits themselves are merged-forward as part of the regular process, I just made sure that the changes you made did not come through during the merge-conflict resolution step. If you look at the file changes in this pull request, you'll see that your changes are not present here.

**Pull request merged**
