### PR TITLE
Allow netbox pillar to pull IPs and interfaces (fixes #51490)

### LINKED ISSUE #51490: salt.pillar.netbox: interfaces?
### Description of Issue/Question

I set up the salt.pillar.netbox external pillar. eveything works fine. With `pillar.items` I get the data and with `'netbox:...'` I can filter for keys.

But: I do not see interface information in the pillar data.

Is is possible to retrieve the interface and VLAN data from netbox?

Michael

### PR DESCRIPTION
**Pull request by maznu**
### What does this PR do?

I want to close 
#51490 (add interfaces to netbox pillar).

### What issues does this PR fix or reference?

#51490

### Previous Behavior

No interfaces or IP addresses in `pillar['netbox']`

### New Behavior

Set:

```yaml
ext_pillar:
  - netbox:
      api_url: https://netbox.example.com/api/
      api_token: XXX
      device_interfaces: True
      ip_addresses: True
```

And ye shall receive:

```
testbox.example.com:
    ----------
    netbox:
        ----------
        interfaces:
            ----------
            eth0:
                ----------
                addresses:
                    |_
                      ----------
                      address:
                          192.0.2.1/22
                      ...etc...
```

### Tests written?

No, but has been tested on my own SaltStack deployment and "works for me".

### Commits signed with GPG?

No

### CODE REVIEW

**Review by twangboy — CHANGES_REQUESTED** [review]
This change needs some tests

**Comment by waynew** [comment]
Hi @maznu thanks for the PR!

Would it be possible to write some tests for this change?

**Comment by waynew** [comment]
@maznu Are you still interested in working on this?

**Comment by waynew** [comment]
@maznu Are you interested in pushing this over the line? Do you need any help?

**Comment by sagetherage** [comment]
closing as abandoned

**Pull request closed without merging**
