### PR TITLE
support for identifier matching/updating in boto_route53.present/absent

### PR DESCRIPTION
**Pull request by lomeroe**
#28813

### CODE REVIEW

**Comment by cachedout** [comment]
@lomeroe This has a small lint error and it looks like it's causing a test to fail. Could you please investigate before we get this merged? Thanks!

**Comment by multani** [comment]
Any reason why ``identifier``/``new_identifier`` is a list of this kind? It looks really counter-intuitive this way.
Why can't it be instead:
```yaml
identifier:
  - my_set_id: 20
# or
identifier:
  - my_west_server: us-west-1
```
Or even better, just a dict with ID/values?
That would be much much clearer IMO.

**Comment by lomeroe** [comment]
@multani that's just how the boto API expects "identifier" - a more complex change to process something like that would be more intuitive.  Admittedly, I was trying to make the update w/minimal changes.

**Comment by cachedout** [comment]
@lomeroe When you get a minute, could you please clean up that lint error?

@multani Did you see the above reply to your comment?

**Comment by multani** [comment]
Sorry @cachedout, I forgot to answer @lomeroe reply.
@lomeroe I understand it is how boto exposes the implementation. What I actually like about Salt is that it provides a way to "abstract" and to manipulate in a much saner way all the these things, and although it makes the implementation slightly more complicated, it has the IMO huge benefit to make the actual use of Salt much more pleasant, and also the documentation clearer.

Actually, when i offered to do the implementation in #28813, I was looking for a way to use the Salt identifier as part of the "Set ID" identifier of Route 53 and expose the actual "set value" (the weight or region in theses cases) as a custom attribute, somehow (hence why I asked for guidance on how to proceed). The state and execution modules would have then wrapped more intelligently (granted, with more code) the actual boto call.

**Comment by lomeroe** [comment]
Totally understand and agree, I've been meaning to come cancel this PR in favor of it being re-done it in a more obvious/salty way.

**Pull request closed without merging**
