### PR TITLE
log and return an error code in AWS_MAX_RETRIES situations

### PR DESCRIPTION
**Pull request by TTimo**
### What does this PR do?

Fix an exception in salt-cloud AWS support, log an error and return an error response as the code originally intended in case of AWS_MAX_RETRIES.

### What issues does this PR fix or reference?

No corresponding issue in the salt issue tracker, but this would happen if starting virtual machines for an instance type that AWS runs out of capacity for (in our case, g4dn instance family in the us-east-2 region).

### Previous Behavior

salt raises an internal exception, caller (python API `salt.cloud.CloudClient`) is not able to obtain an error code.

### New Behavior

AWS error codes are correctly reported to the caller after AWS_MAX_RETRIES (such as `InsufficientInstanceCapacity` in our case).

### CODE REVIEW

**Review by waynew — CHANGES_REQUESTED** [review]
Hey, this looks pretty good, but could you add some tests for this? Typically the moto module is used if you want to mock some things out.

If you need help adding tests, I can help either tomorrow or Thursday during the Test Clinic

**Comment by TTimo** [comment]
Right .. tests would be good .. this PR exists because that code path doesn't have a test to begin with. I'll put that on the pile but I don't know when I might have time to look into this further.

**Comment by TTimo** [comment]
I had a look what it would take to setup a unit test for this but couldn't finish. I don't know that `moto` is particularly necessary, the problem being fixed does not depend on mocking a complex behavior from the ec2 side - it will trigger if a query to ec2 returns one of the `AWS_RETRY_CODES` errors enough times.

Our code now avoids this by removing `"InsufficientInstanceCapacity"` out of `AWS_RETRY_CODES` so we abort on the first error without repeating up to `AWS_MAX_RETRIES` and hitting the bad code (that ec2 error is unlikely to fix itself in the handful of retries anyway, might as well abort immediately).

This is something so trivial to fix, I don't think I can justify spending more time pushing this forward, sorry.

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
