### PR TITLE
Add functions from network.py to win_network.py

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?
Adds functions from `network.py` that should work on Windows to `win_network.py`. Similar to what we do with the `file.py` and `win_file.py` modules.

Specifically:
- network.wol
- network.get_hostname
- network.interface
- network.interface_ip
- network.subnets6
- network.ip_in_subnet
- network.convert_cidr
- network.calc_net
- network.get_fqdn
- network.ifacestartswith
- network.iphexval

Fixes `network.iphexval`. Was returning the hex for only the last octet. Now returns a zero padded hex value for the passed IP address.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/36735
https://github.com/saltstack/salt/issues/36708

### Previous Behavior
Some functions from `network.py` that work on Windows weren't available. Specifically, `network.get_hostname` and `network.wol`.

### New Behavior
The above functions are now available.

### Tests written?
No

### CODE REVIEW

**Comment by cachedout** [comment]
Please lint this.

Additionally, this makes a change to the `iphexval` function but the description you've given for the PR doesn't explain why. Could you please clarify?

**Comment by twangboy** [comment]
@cachedout The `iphexval` function should convert an IP address to a hex value, as I understand it. So, for example, `192.168.1.10` should convert to `C0A8010A`.

```
192.168.001.010
C0  A8  01  0A
```

As the function was written it was only giving you the hex for the last octet. I think they were using the join command incorrectly. And it wasn't zero padding. The above IP would return `A`:

```
salt '*' network.iphexval 192.168.1.10
minion
------
    A
```

With these changes it now returns correctly:

```
salt-call --local network.iphexval 192.168.1.10
local:
    C0A8010A
````

**Comment by cachedout** [comment]
@twangboy Thanks for the explanation. I think you're right-on.

We're still not quite there on the lint fixes though. Could you please finish them up? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/7134/violations/file/salt/modules/win_network.py/

**Comment by cachedout** [comment]
Lint test didn't run but I linted it by hand and it looks fine. Merging.

**Pull request merged**
