### PR TITLE
[master] Fix await None error

### LINKED ISSUE #66177: installed 3007 TypeError: object NoneType can't be used in 'await' expression
Upgraded 3006.7 to 3007 on both salt-master and a single salt-minion
Salt minion log is recording the following errors constantly

/var/log/salt/minion
2024-03-07 15:53:49,411 [salt.transport.zeromq:396 ][ERROR   ][2127705] Exception while running callback
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/transport/zeromq.py", line 394, in consume
    await callback(msg)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/channel/client.py", line 484, in wrap_callback
    await callback(decoded)
TypeError: object NoneType can't be used in 'await' expression

/var/log/salt/master
2024-03-07 15:54:59,908 [salt.loader.lazy :531 ][ERROR   ][1084696] Module/package collision: '/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/__pycache__/vault.cpython-310.pyc' and '/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/vault'
2024-03-07 15:54:59,979 [salt.loader.lazy :531 ][ERROR   ][1084696] Module/package collision: '/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/__pycache__/vault.cpython-310.pyc' and '/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/vault'
2024-03-07 15:54:59,980 [salt.loader.lazy :531 ][ERROR   ][1084696] Module/package collision: '/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/__pycache__/vault.cpython-310.pyc' and '/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/vault'

Initially spotted when doing a manual salt-call
looked in  /opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/__pycache__/ and spotted an old file after upgrade:

-rw-r--r--  1 root root  9832 Mar  7 14:12 user.cpython-310.pyc
-rw-r--r--  1 root root   440 Mar  7 14:12 value.cpython-310.pyc
**-rw-r--r--  1 root root 14016 Feb 26 09:08 vault.cpython-310.pyc**
-rw-r--r--  1 root root 15913 Mar  7 14:12 verify.cpython-310.pyc
-rw-r--r--  1 root root 14925 Mar  7 14:12 versions.cpython-310.pyc

Salt Version:
          Salt: 3007.0

Python Version:
        Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.16.0
      cherrypy: 18.8.0
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.15.1
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.4

Salt Package Information:
  Package Type: onedir

System Versions:
          dist: oracle 8.9
        locale: utf-8
       machine: x86_64
       release: 5.15.0-101.103.2.1.el8uek.x86_64
        system: Linux
       version: Oracle Linux Server 8.9

### PR DESCRIPTION
**Pull request by merlinz01**
### What does this PR do?
Adds @tornado.gen.coroutine decorator to Minion._handle_payload method (also ProxyMinion and Syndic).

### What issues does this PR fix or reference?
Fixes: #66177

### Previous Behavior
```
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/transport/zeromq.py", line 394, in consume
     await callback(msg)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/channel/client.py", line 484, in wrap_callback
    await callback(decoded)
TypeError: object NoneType can't be used in 'await' expression
```

### New Behavior
No errors!

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by tjyang** [comment]
https://github.com/saltstack/salt/issues/66282, I opened this ticket to track  time out issue.

**Comment by dwoz** [comment]
Please hold off on merging this until I have a chance to look at it in more detail.

**Comment by merlinz01** [comment]
Have updated this PR according to the recommendations in [this comment](https://github.com/saltstack/salt/pull/66335#issuecomment-2047847453).

**Review by twangboy — APPROVED** [review]

**Comment by dwoz** [comment]
superseded by #66335

**Pull request closed without merging**
