### PR TITLE
adding states/file unit test case

### PR DESCRIPTION
**Pull request by jayeshka**
Implemented states/file_test unit test case.

### CODE REVIEW

**Comment by jayeshka** [comment]
Failures are due to changes required in states/file.py module.
As soon as #23936 gets merge this tests should pass.
@jfindlay after you merge #23936 please re-run this test.

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
@jayeshka, there are still a few test failures.

**Comment by rallytime** [comment]
If these new tests passing is dependent on changes from another pull request, this will need to be rebased before the tests will succeed as expected.

**Comment by jfindlay** [comment]
#24100 has been merged, so I'm closing this one.  Thanks, @jayeshka.

**Pull request closed without merging**
