### PR TITLE
Move 13 functions from salt.utils to salt.utils.data

### PR DESCRIPTION
**Pull request by terminalmage**
These functions are:

- salt.utils.compare_dicts
- salt.utils.compare_lists
- salt.utils.decode_dict
- salt.utils.decode_list
- salt.utils.exactly_n
- salt.utils.exactly_one
- salt.utils.traverse_dict
- salt.utils.filter_by
- salt.utils.traverse_dict_and_list
- salt.utils.subdict_match
- salt.utils.substr_in_list
- salt.utils.is_dictlist
- salt.utils.repack_dictlist

### CODE REVIEW

**Comment by cachedout** [comment]
Some lint fixes, please. https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/15438/violations/

**Comment by terminalmage** [comment]
re-run ubuntu

**Comment by terminalmage** [comment]
re-run ubuntu

**Comment by terminalmage** [comment]
All test failures appear to be due to a pyOpenSSL mismatch in the boto tests.

**Review by rallytime — APPROVED** [review]
This looks great

**Comment by rallytime** [comment]
Yes, those test failures are not related to this PR. I'm working on a fix for those currently (waiting on tests).

**Pull request merged**
