### PR TITLE
Add support for user roles in present state

### PR DESCRIPTION
**Pull request by ni3mm4nd**
## What does this PR do?

Adds support for user roles in present state

## What issues does this PR fix or reference?
#39681

## New Behavior

sls file:
```
  mongodb_user.present:
    - name: myapp
    - passwd: admin
    - user: root
    - host: mongo-data-02
    - port: 27017
    - authdb: admin
    - password: admin
    - roles:
        - readWrite
        - userAdmin
        - dbOwner
```
```
salt mongo-data-01 state.apply mongo-test
mongo-data-01:
----------
          ID: mongouser-myapp
    Function: mongodb_user.present
        Name: myapp
      Result: True
     Comment: User myapp is already present
     Started: 11:01:22.007496
    Duration: 55.557 ms
     Changes:   
              ----------
              myapp:
                  ----------
                  database:
                      admin
                  roles:
                      ----------
                      new:
                          - readWrite
                          - userAdmin
                          - dbOwner
                      old:

Summary for mongo-data-01
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  55.557 ms
```

```
rsdata1:PRIMARY> db.getUser("myapp")
{
	"_id" : "admin.myapp",
	"user" : "myapp",
	"db" : "admin",
	"roles" : [
		{
			"role" : "readWrite",
			"db" : "admin"
		},
		{
			"role" : "userAdmin",
			"db" : "admin"
		},
		{
			"role" : "dbOwner",
			"db" : "admin"
		}
	]
}
rsdata1:PRIMARY> 
```

sls file:
```
  mongodb_user.present:
    - name: myapp
    - passwd: admin
    - user: root
    - host: mongo-data-02
    - port: 27017
    - authdb: admin
    - password: admin
    - roles:
        - readWrite
```
```
salt mongo-data-01 state.apply mongo-test
mongo-data-01:
----------
          ID: mongouser-myapp
    Function: mongodb_user.present
        Name: myapp
      Result: True
     Comment: User myapp is already present
     Started: 11:02:33.549042
    Duration: 55.897 ms
     Changes:   
              ----------
              myapp:
                  ----------
                  database:
                      admin
                  roles:
                      ----------
                      new:
                          - readWrite
                      old:
                          - readWrite
                          - userAdmin
                          - dbOwner

Summary for mongo-data-01
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  55.897 ms
```
```
rsdata1:PRIMARY> db.getUser("myapp")
{
	"_id" : "admin.myapp",
	"user" : "myapp",
	"db" : "admin",
	"roles" : [
		{
			"role" : "readWrite",
			"db" : "admin"
		}
	]
}
rsdata1:PRIMARY> 
```

Tests written?
No

Please review Salt's Contributing Guide for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
@ni3mm4nd This looks good but it looks like one test might need to be adjusted: https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/9173/testReport/junit/unit.states.mongodb_user_test/MongodbUserTestCase/test_present/

Can you take a look? Let me know if you have questions on the test suite at all. Thanks!

**Comment by ni3mm4nd** [comment]
Hi @cachedout . I think it can be caused by #39638. Once it will be merged it should pass as well. What do you think? Thanks!

**Comment by cachedout** [comment]
Hi @ni3mm4nd 

I went ahead and merged #39368. Could you please rebase this against the HEAD of develop and we'll see if it passes now? Thanks!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by ni3mm4nd** [comment]
Hello @cachedout . I'm having troubles with that unit tests. Could you help me please?
Seems line __opts__ are not injecting properly into the function hence I'm getting that key word 'test' is invalid error. Thanks

**Comment by cachedout** [comment]
Hi @ni3mm4nd I committed a change to this PR that fixes this for me locally. Let's see what Jenkins says now. :]

**Pull request merged**
