### PR TITLE
There is no support for ECDSA on OpenSSH < 5.7.

### PR DESCRIPTION
**Pull request by cachedout**
This fixes long-broken tests on several platforms, including Ubuntu 10.04 and some of the older CentOS distros.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
This script is not in use

**Comment by s0undt3ch** [comment]
salttesting/jenkjns.py is

**Comment by cachedout** [comment]
Can we remove it if it's not in use? Or is it reserved for future use?

**Comment by rallytime** [comment]
I'll make a commit to that file with this change, then. Thanks @s0undt3ch!

**Comment by s0undt3ch** [comment]
#19394

**Pull request merged**
