### PR TITLE
Unit tests in place of integration tests for sys.list_{functions,modules}

### PR DESCRIPTION
**Pull request by jf**
(Why unit tests? Because these make more sense over integration tests)
### What does this PR do?

Use unit tests in place of integration tests for sys.list_{functions,modules}
### What issues does this PR fix or reference?

Old PRs written using integration tests: #33774, #33775
*NOTE if this PR is accepted, pls ignore #35077
### Tests written?

duh

### CODE REVIEW

**Comment by terminalmage** [comment]
I reject the premise of this pull request.

**Comment by jf** [comment]
Just to be clear, what exact premise are you rejecting here?

**Comment by terminalmage** [comment]
I just don't see how unit tests make more sense. If you could elaborate on _why_ unit tests would make more sense, then I'm happy to be persuaded, but simply stating that they "make more sense" doesn't make an actual case for why the existing integration tests should be abandoned.

When possible we should be writing integration tests. The arguments for unit tests over integration tests usually amount to one of the following:

- We're testing something with finicky network-based behavior (such as parsing ``dig`` CLI output for a domain we don't control, and thus can't guarantee the stability of the test)
- All we are trying to test is that the function signature (arguments, return data) hasn't drastically changed
- Only a very small subset of code that isn't an actual state or remote execution function is being tested (e.g. testing functionality of various modules under ``salt.utils``)

Were the existing integration tests failing unexpectedly? Is there something you feel we gain by switching them to unit tests?

**Comment by jf** [comment]
ok, thanks for the explanation. I suppose it's clear, but just to reiterate - I am talking specifically about the tests for sys.list_{functions,modules}. I have been working on the existing integration tests for the 2 functions as a default (see those PRs I've listed)... but coming back again, I see that what we're testing in there is really the logic of the methods (so if we `sys.listmodules u*`, we should expect the list to contain 'user', but not 'bigip').

Given that this is purely testing the logic of the methods, over something like network comms, I thought that unit tests made more sense (and will be faster too!). I think you could also say that this fits with the second reason you give above: "All we are trying to test is that the function signature (arguments, return data) hasn't drastically changed". Does that make sense?

**Comment by terminalmage** [comment]
Ahh OK, given that explanation it seems to make more sense, though when I referred to "return data" earlier I was more referring to a specific data structure that we want to make sure doesn't change. My bad for not explaining that more clearly.

After a closer look at these two functions, I would say that unit tests are acceptable. The fact that we don't actually invoke anything in ``__salt__`` is key, once we get into executing functions then we have to worry about mocking the return from these functions. This is when unit tests can be less reliable, because improper mocking can give us a passing test when the function is not operating correctly.

**Comment by terminalmage** [comment]
Before we merge this, can you address the lint issues identified here? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/3784/violations/file/tests/unit/modules/sysmod_test.py/

The linter does not like the extra whitespace between the list elements.

**Comment by jf** [comment]
> The fact that we don't actually invoke anything in __salt__ is key, once we get into executing functions then we have to worry about mocking the return from these functions. This is when unit tests can be less reliable, because improper mocking can give us a passing test when the function is not operating correctly.

Gotcha, and understood. Thanks for the note!

I'll have a look at the linting issues and push up something shortly.

**Comment by terminalmage** [comment]
No problem, and thanks for bearing with my short and surly initial reply. :smile:

**Comment by jf** [comment]
:) glad we worked things out! I've added more tests, btw. It's me being pedantic - but I thought it'll be useful to specify exactly how we expect the methods to behave with what input (`sys.list_functions sys.` with the extra period at the end was a surprise to me, btw, when I saw it in the integration test. I'd like to remove any ambiguity and wondering).

(I've also rebased, so it'll be easier to merge)

**Comment by cachedout** [comment]
Merged. Thanks, @jf. Much appreciated. :]

**Comment by jf** [comment]
hey Mike! nice to see you again in a PR :D

**Comment by cachedout** [comment]
Hi Jeffrey! Great to run into you as well!

**Comment by terminalmage** [comment]
@jf Good call on the additional test cases. This is behavior I've been aware of in the sys module for a few years now, but it certainly can't hurt to have this behavior enforced with well-written unit tests.

**Comment by jf** [comment]
FYI @twangboy : pls see the discussion here for why the integration tests for sys.list_functions and sys.list_modules were removed.

**Pull request merged**
