### PR TITLE
Improve the Capirca and related modules for ACL config generation

### PR DESCRIPTION
**Pull request by mirceaulinic**
Since I added these modules in 2017.7.0, Capirca has been released on PyPI,
now available to be installed as a regular Python library.

Besides that, in the past there were various issues due to the way the modules
are interacting with the underlying library, solved by adding a hardcoded list
for the policy term fields. This has caused some issues in the past, and had
to be patches, e.g., db255d37020f0d8f60881ac3176cd86e7f44c5c2 or
1e74141cc08b704cc9d289f02eba2f009ce523d1.
While the changes referenced above are not particularly big, it's tedious to
always keep an eye on Capirca and be aware of what's newly added or changed.
Besides, this may have caused issues for users in the past when using other
Capirca versions.

CC @ankenyr

### CODE REVIEW

**Comment by mirceaulinic** [comment]
@saltstack/team-triage this PR is probably blocked due to the linter complaining about: https://jenkinsci.saltstack.com/job/pr-lint/job/PR-50852/6/warnings52Result/new/, however this is the line in cause: https://github.com/saltstack/salt/blob/3d567508d09a275311b36abc7fdcbbcfaf3e5cff/salt/modules/capirca_acl.py#L79 - can you please advise?

**Comment by mirceaulinic** [comment]
Any ideas @saltstack/team-core?

**Comment by terminalmage** [comment]
@mirceaulinic I believe that the comment lines are what is tripping up pylint. Try adding a blank line before the comment on line 76, and see if that clears up the lint failure.

**Comment by mirceaulinic** [comment]
It looks like this fixed it - thanks @terminalmage!

**Comment by mirceaulinic** [comment]
I'm checking in here: @saltstack/team-core is there anything waiting on my end before we can get this in? Thanks!

**Review by thatch45 — APPROVED** [review]
I think this looks good to merge

**Review by dwoz — APPROVED** [review]

**Pull request merged**
