### PR TITLE
Group gid fixed as integer 

### PR DESCRIPTION
**Pull request by rainecurtis**
### What does this PR do?

Fixes the _changes() function to correctly evaluate  the group id.

### What issues does this PR fix or reference?

gid was being passed as a string, while the lgrp['gid'] was being passed as an integer.

Added casting or string ``gid`` to integer for accurate comparison.

### Previous Behavior

The return was false even though the group was successfully created.

### New Behavior

This updated code now compares an integer with an integer for the gid.

### Tests written?

No

### Commits signed with GPG?

No

###  Previous Error 

**Evaluation**

``` python
gid  == <type 'str'>
lgrp['gid'] == <type 'int'>
```

**Output**

```

    [ERROR   ] {'Failed': {'gid': '1030'}}
    local:
    ----------
           ID: oinstall_group
     Function: group.present
        Name: oinstall
      Result: False
      Comment: Group {0} has been created but, some changes could not be applied
     Started: 08:59:43.531683
     Duration: 88.538 ms
     Changes:   
              ----------
              Failed:
                  ----------
                  gid:
                      1030
```
###  Fixed Evaluation

**Evaluation**

``` python
    if gid:
       try:
           gid = int(gid)
           if lgrp['gid'] != gid:
                change['gid'] = gid
       except (TypeError, ValueError):
           ret['result'] = False
           ret['comment'] = 'Invalid gid'
           return ret

```

Changed evaluation from (string != int) to (int != int) 

###  Versions tested

**SLES12SP3** / Salt 2016.11.4 (Carbon)
**Oracle Linux 7** / Salt 2018.3.1 (Oxygen)

State used for testing:

```
oinstall_group:
  group.present:
    - name: oinstall
    - gid: '1030'
```

### CODE REVIEW

**Comment by grokrecursion** [comment]
I'm not sure what needs to be fixed. Please advise.

**Comment by rallytime** [comment]
Hi @grokrecursion - we are not accepting bug fixes to the 2017.7.7 branch as that branch has already been released. Can you move this to the `2017.7` branch?

**Review by gtmanfred — CHANGES_REQUESTED** [review]
This will need to be rebased to remove the extra commits from the branch.

**Comment by grokrecursion** [comment]
Tried to rebase. Please advise.

**Comment by gtmanfred** [comment]
do a `git rebase -i HEAD~24` and remove the commits that you are not submitting for your PR.

Then do a `git pull --rebase origin 2017.7` to pull anything else down and rebase your changes on top of the HEAD of the 2017.7 branch.

**Comment by gtmanfred** [comment]
I fixed the rebase.

**Comment by gtmanfred** [comment]
Make sure to not force push over this branch, you will need to fix your local branch, and then you can push for anything else that you wanted to change.

**Review by gtmanfred — APPROVED** [review]

**Comment by grokrecursion** [comment]
Thanks @gtmanfred  for the help! I only  had to add a ``--force`` to the push to make it work.

**Comment by grokrecursion** [comment]
Got it, no force. Thanks!

**Review by rallytime — APPROVED** [review]
Thanks @grokrecursion!

**Pull request merged**
