### PR TITLE
Fix virtual network generated DNS XML for SRV records

### PR DESCRIPTION
**Pull request by cbosdo**
### What does this PR do?

libvirt network's srv element doesn't take a `name` property but a
`service` one.

### What issues does this PR fix or reference?

Fixes: an issue introduced by PR #59146 generating a wrong libvirt virtual network XML.

### Merge requirements satisfied?
- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by garethgreenaway — APPROVED** [review]

**Comment by cbosdo** [comment]
re-run centos7-py3-m2crypto-pytest

**Comment by cbosdo** [comment]
re-run windows2019-py3-pytest

**Comment by cbosdo** [comment]
re-run windows2019-py3-pytest

**Comment by cbosdo** [comment]
re-run centos7-py3-pycryptodome-pytest

**Comment by cbosdo** [comment]
@dwoz this PR has been ACK'ed and is green. Could you merge it please?

**Comment by waynew** [comment]
@cbosdo Nice! Is this a fix for code that has been released or is this just patching some unreleased code? If it's the former then we'll want to have a changelog. Otherwise let me know and I'll go ahead and approve.

**Comment by cbosdo** [comment]
> @cbosdo Nice! Is this a fix for code that has been released or is this just patching some unreleased code? If it's the former then we'll want to have a changelog. Otherwise let me know and I'll go ahead and approve.

It's a fix for code that hasn't been released yet... that's why there is no changelog entry

**Review by Ch3LL — CHANGES_REQUESTED** [review]
Looks like the tests did not catch this. Is there a test case that can be added to ensure the template's elements are checked and work with the libvirt module?

**Comment by cbosdo** [comment]
@Ch3LL the PR includes a unit test change to specifically catch it... we haven't caught it before because the test was bogus too! Ideally we would need to run all tests against real libvirt to catch those, but then that would make the tests way more complex due to the need of a running hypervisor.

**Comment by Ch3LL** [comment]
K I'm fine merging this for now. Wanted to see if it could be added to the current virt integration tests, but looks like it cannot.

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
