### PR TITLE
integration state test_pkg war-room optimiazation

### PR DESCRIPTION
**Pull request by Akm0d**
### What does this PR do?
Completely refactor the test_pkg.py test so that it doesn't take 30 seconds to skip a test.  Also refactored so that each test runs in significantly less amount of time

### Commits signed with GPG?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by twangboy** [comment]
@Akm0d Windows tests are failing

**Comment by Akm0d** [comment]
re-run windows

**Comment by Akm0d** [comment]
re-run fedora

**Comment by Akm0d** [comment]
re-run fedora

**Comment by Akm0d** [comment]
re-run fedora

**Comment by DmitryKuzmenko** [comment]
Something's wrong on that fedora test run. @team-core thoughts?

**Review by dwoz — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Comment by Akm0d** [comment]
re-run fedora

**Comment by Akm0d** [comment]
re-run fedora29

**Comment by Akm0d** [comment]
re-run py3

**Comment by Akm0d** [comment]
re-run full all`

**Pull request closed without merging**
