### PR TITLE
[2016.3] Merge forward from 2015.8 to 2016.3

### PR DESCRIPTION
**Pull request by rallytime**
Conflicts:
- doc/topics/netapi/index.rst
- salt/modules/win_servermanager.py
- salt/modules/zypper.py

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@rallytime There may have been some extra lines that snuck into the Tornado test. It was caught by the linter. Could you please have another look?

**Comment by rallytime** [comment]
Git seemed to have had a problem in that file for some reason. All fixed.

**Comment by cachedout** [comment]
QA has approved this for a post-freeze merge.

**Pull request merged**
