### PR TITLE
[3006.x] return event greednes fix.

### PR DESCRIPTION
**Pull request by whytewolf**
### What issues does this PR fix or reference?
Fixes: #65727 

### Previous Behavior
catch all salt/job/{jid}/ret*

### New Behavior
catch only salt/job/{jid}/ret/*

@dwoz wanted to see about tests for this. i couldn't figure out how to thread the class function that this is happening in. 

the fix is super simple. testing it not so much.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [X] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### CODE REVIEW

**Review by twangboy — DISMISSED** [review]

**Review by dwoz — DISMISSED** [review]

**Comment by twangboy** [comment]
Looks like we have some pretty consistent test failures here

**Comment by whytewolf** [comment]
> Looks like we have some pretty consistent test failures here

those should be fixed now. turns out there was a test that injected an ret event that didn't include enough info to count as a real ret event.

**Review by twangboy — APPROVED** [review]

**Comment by twangboy** [comment]
I think it's still happening... at least on MacOS

**Comment by whytewolf** [comment]
> I think it's still happening... at least on MacOS

the mac errors look to be unrelated.

```
 ERROR tests/pytests/functional/modules/state/test_jinja_filters.py::test_filter[hmac] - AttributeError: module 'py' has no attribute 'io'
ERROR tests/pytests/functional/modules/state/test_jinja_filters.py::test_filter[gen_mac] - AttributeError: module 'py' has no attribute 'io'
```

**Pull request merged**
