### PR TITLE
Fix cron module logic regarding working from non-root user

### PR DESCRIPTION
**Pull request by Oloremo**
### What does this PR do?
Fix cron module\state execution in case of Salt running from non-root user

### What issues does this PR fix or reference?
Fixes https://github.com/saltstack/salt/issues/51872

### Previous Behavior
cron state trying to run commands using the privilege escalation via `runas` arg in different modules.

### New Behavior
If the current Salt process owner UID equals specified user in cron state it won't do a privilege escalation.

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by garethgreenaway** [comment]
@Oloremo Thanks for the PR.  I think it might make more sense to break out the other if...else situations as you did for the `raw_cron` function in the others, to ensure that the Solaris/AIX functionality remains consistent.

**Comment by Oloremo** [comment]
@garethgreenaway I felt like I didn't break any logic and `raw_cron` func is just a bit different from the other, but if you like I can make them in the same style

**Comment by Oloremo** [comment]
Ok, so I tried to do some unification of the logic and updated tests according to it.
Problem is now I have new kind of condition which isn't covered by tests - when I check if salt running from a root user:

`_check_instance_uid_match('root'):`

And I'm not sure how to mock it properly to test this condition.

**Comment by Oloremo** [comment]
@garethgreenaway mind to look at this PR again?

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
