### PR TITLE
Isbm fix coregrains constants bsc#1032931

### PR DESCRIPTION
**Pull request by isbm**
### What does this PR do?

- Fixes bugs in `timezone` for SUSE series
- Adds ton of unit tests for `timezone` module

### CODE REVIEW

**Comment by cachedout** [comment]
Looks like a test failure here: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/10594/

**Comment by isbm** [comment]
@cachedout How this is happening?? :confused: I am running with Salt's `runtests.py` and `pytest`, all passes:

```
$ ./runtests.py -n unit.modules.timezone_test
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Transplanting configuration files to '/tmp/salt-tests-tmpdir/config'
 * Current Directory: /home/bo/work/salt
 * Test suite is running under PID 29856
 * Logging tests on /tmp/salt-runtests.log
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Starting unit.modules.timezone_test Tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.......................
----------------------------------------------------------------------
Ran 23 tests in 0.047s

OK

==================================  Overall Tests Report  ==================================
***  No Problems Found While Running Tests  ************************************************
============================================================================================
OK (total=23, skipped=0, passed=23, failures=0, errors=0) 
==================================  Overall Tests Report  ==================================
```

And pytest (in which you, guys, _should_ move to :laughing: ):
```
s$ pytest unit/modules/timezone_test.py
=========================  timezone_test.py  =========================
.......................
----------------------------------------------------------------------
Ran 23 tests in 0.023s

OK
*******************************************************************************
```

Sorry, cannot reproduce this.

**Comment by s0undt3ch** [comment]
You know @isbm, the develop branch is now capable of running the full test suite under pytest. There's still no official move because we're still taking care of some rough edges on py3 :)

Anyway, about the failing test.
When I was cleaning some of the rough edges on py3, and after reading https://engblog.nextdoor.com/what-your-mocks-do-when-you-aren-t-looking-b278e0d9e201 and verified the behavior myself, I ended up removing all `@patch` decorators from salt(there's still an open PR with these changes).
One of the things I noticed was that, some of the mocks changed bahvior when not using `@patch`, ie, they apparently _leaked_ between test functions.

So, to rule that out, if that test module is using `@patch`(sorry can can't look up myself, I'm still half awake drinking my morning coffee), switch all `@patch` occurrences to `with patch` to rule out this possible "outside noise".

**Comment by s0undt3ch** [comment]
See, still half awake.

:)

not

:(

**Comment by isbm** [comment]
> You know @isbm, the develop branch is now capable of running the full test suite under pytest. There's still no official move because we're still taking care of some rough edges on py3 :)

I am going to eat rainbow now, really?? Share please the trick. :-) It still spits me up things like `ImportError: No module named pytestsalt.utils` if I _just_ run it inside the `tests/unit`. Currently I am only run it over individual tests.

> So, to rule that out, if that test module is using @patch(sorry can can't look up myself, I'm still half awake drinking my morning coffee), switch all @patch occurrences to with patch to rule out this possible "outside noise".

You gotta be kidding me:
```
 cat timezone_test.py | grep '@patch' | wc
     80     160    4219
```
Of course I use it heavily. But why it supposed to be wrong? We use this across everywhere, it cannot be just forbidden practice. :-(

**Review by s0undt3ch — COMMENTED** [review]
Yeah, you're using `@patch`. That would be my guess about the failure.

**Comment by isbm** [comment]
@s0undt3ch and if we would move to pytest, we could stop using this ugly `self.assertCamelCodeHere` things. I am waiting when I can do:

```python
with pytest.raises(AnyPossibleError):
   ...
```
...instead.

**Comment by isbm** [comment]
@s0undt3ch no, but that doesn't really makes any sense. This decorator is used everywhere. Should we all stop using it and rewrite the entire UT to `with`, having it like:
```
with ...
   with ...
      with ...
         with ...
            with ...
```
...??? And it doesn't fail on RH. Neither on mine Ubuntu/SUSE/RH environments.

**Comment by s0undt3ch** [comment]
_"Should we all stop using it and rewrite the entire UT to `with`"_

Yes.

Though, each patch call does not need its own `with` statement. On Py2.6 use, `contextlib.nested(patch(), patch()`, and on py2.7 onward:
```python
with patch(), \
            patch(), \
            patch():
    do_stuff()
```

**Comment by s0undt3ch** [comment]
About the rewrite, I've done that on my open PR for existing tests, for Nitrogen and forward branches.
For older branches, we don't need to rewrite but we should start avoiding.

**Comment by isbm** [comment]
:confused: While it _might_ be a problem with the `@patch(...` decorator, it still doesn't really answers me why:

- Your CentOS7 environment doesn't fail
- My environment on Ubuntu 16.04 and Leap 42 doesn't fail

**Comment by s0undt3ch** [comment]
Ubuntu and RH should be using the same mock version, https://github.com/saltstack/salt-jenkins/blob/master/python/mock.sls

**Comment by isbm** [comment]
It actually doesn't say '1.3.0', but "more than 1.1.0". This doesn't make a fact that one is using 1.2.0 and another 1.3.0, or I am missing something?

**Comment by isbm** [comment]
@s0undt3ch LOL http://packages.ubuntu.com/trusty/python/python-mock

**Comment by s0undt3ch** [comment]
Because patch leaks between tests and because we directly update `<module>.__salt__` on tests and this  definitely changes behavior if not reset after the tests like you're doing.

On Nitrogen I've fixed that behavior, but not for older branches since its a too intrusive change.

**Comment by s0undt3ch** [comment]
No, it states that mock should be `< 1.1.0` and since that's installed using `pip` both systems should be using the previous(to 1.1.0) release of mock.
Its not installing mock from the system packages.

**Comment by s0undt3ch** [comment]
And don't ask me why its locked to `< 1.1.0`, I don't know, there was probably an issue with that version.

**Comment by isbm** [comment]
Aha! So you are using pre 1.1.0, while I am on 1.3.0 and probably this is the reason. Why we should stay on old mock? pre 1.1.0 is just way too old and actually there was issues with it. We are running 1.3.0 everywhere and it just works fine (at least in our case). Maybe time to upgrade?

As of `__salt__` update, `self.setUp` should do the trick, no? I am resetting it there all the time on each test, so it should work, unless Python Unit test is fundamentally wrong.

**Comment by isbm** [comment]
@s0undt3ch and it also kind of sucks without `@patch` decorator. Because it should be like this:
```python
@patch('things.that.changed.permanently.on.this.test')
@patch('things.that.changed.permanently.on.this.test')
@patch('things.that.changed.permanently.on.this.test')
def test_foo_bar():
    with patch('things.that.are.only.for.this.particular.call'):
        blah()
    with patch('things.that.are.only.for.this.particular.call'):
        blah2()
    with patch('things.that.are.only.for.this.particular.call'):
        blah3()
```

@cachedout @thatch45 so can we move on to 1.3.0 version of Mock, please? :-)

**Comment by s0undt3ch** [comment]
Yes, it sucks but it doesn't leak objects, when running the full test suite we have thousands of mock objects that never get garbage collected.

Also, the right thing is not to set `__salt__` directly. Look at `tests.support.mixins` and see how the mock mixin does it.

**Comment by isbm** [comment]
@s0undt3ch it is still not the fact that leak is not due to the buggy Mock version. And I'd also like to hear your version what kind of problems you have with the pytest. Because we are running it pretty much successfully without needing all that custom things or leaking. :-/

**Comment by s0undt3ch** [comment]
Mock leaks objects(or better said, blocks mock objects from being garbage collected) when using `@patch`, period. And I say period because it leaks with latest mock, the mock shipped with python 3.5, 3.6, any version.
The reason why those mocks are not garbage collected is because the `@patch` decorator adds a list as an attribute to the test function which holds references to any mock objects that should be used when the test function runs. Ideally, it should clear that list once the test function has been executed but it doesn't, it just keeps holding references to the mock objects until the test suite finishes or the test class is garbage collected. Now each attribute accessed on a mock object creates another mock object and so forth and this *will* consume memory.

On smaller test suites, this probably does not cause any memory issues, but on salt's test suite, under py3 specially, it does.

This alone is not the reason why we consume all of the available memory when running the test suite under py3, but it is a chunk of memory that should be freed as soon as possible.

We currently use VMs with 4Gig of RAM to run salt's test suite. Smaller VMS will make the test suite OOM killed or swap too much which will make it extremely slow.

So, any steps we can take to make our memory footprint smaller will be taken, even if that means stop using the `@patch` decorator.

You should read that article I posted above for additional insight.

**Comment by s0undt3ch** [comment]
Also, the reason why it happens on one VM and not on another is not necessarily because we are using different versions of mock. We don't run the same set of tests on different distro VMs because some tests are specily targeted for a specific distro or skipped if not the target distro.

**Comment by rallytime** [comment]
> And don't ask me why its locked to < 1.1.0, I don't know, there was probably an issue with that version.

This is locked at this version because that is the last version that supports Python 2.6, which is still needed in the 2016.3 and 2016.11 branches. @s0undt3ch That version can probably be bumped up now for the nitrogen and develop branches.

**Comment by s0undt3ch** [comment]
Sounds like a good plan Nicole! Thanks!

**Comment by isbm** [comment]
@rallytime @s0undt3ch @cachedout  Well, unfortunately, no matter I do, (just downgraded to mock 1.0.1), I still end up that it _does not_ fails for me:
```
     sysbench_test.py ......
     syslog_ng_test.py ............
     sysmod_test.py ...................
     system_test.py ......
     systemd_test.py ...................
     test_network.py ..
---> timezone_test.py .......................
     tls_test.py ssssssssssssssssssss
     tuned_test.py ..
     twilio_notify_test.py .
     udev_test.py ...
     uptime_test.py ....
```

I found though that `modules/cp_test.py` is hanging at mocking call, by eating lots of memory and leaking something. It is completely unrelated to this PR though, but that is possibly can be a bit that adds problems.

That said, I would question your testing environment. Maybe even if you say there are some leaks etc, but this still needs to be proven and tracked down. Even assuming you are right with your theory of leaking Mock objects, still at first, _your_ environment should not be inconsistent: all distribution-agnostic Unit tests on Ubuntu should _not_ fail, if they are passing on RedHat!

**Comment by isbm** [comment]
Update: I threw away Mock 1.0.1, installed to the latest available on PIP (2.0.0). Now `cp_test.py` passes without any problems (same was with the 1.3.0 though). Still the timezone test above also passes. Some boto tests and CMDMODTestCase.test_run fails though, but they were failing anyway.

**Comment by isbm** [comment]
@s0undt3ch any updates here? :-]

**Comment by isbm** [comment]
@cachedout @s0undt3ch anything? On Friday we kind of decided that Ubuntu14 indeed may have problems, but they aren't due to the test itself, but due to the polluted env, that can't be actually replicated elsewhere at the moment.

**Comment by cachedout** [comment]
@isbm After talking to @s0undt3ch we think that the thing to do here might be to disable this failing test in this PR, and then test it again in develop where we've made improvements to the test suite to prevent this sort of thing.

**Comment by isbm** [comment]
@cachedout @s0undt3ch OK, so it is _not_ the `@patch` problem (see https://github.com/saltstack/salt/pull/40852/commits/76cb1b7150d3187b29e7b2ca50503a2753c88014). I give up here, seriously. Guys, please fix your test env. :-(

**Review by s0undt3ch — COMMENTED** [review]
Why exactly? Which PyLint version complained? Which Lint error?
4 nested `with` statements is not a big deal but with some tests having 7 or 8, it becomes a big deal(too much nesting). If lint complained about multiple calls in single `with` statement, lint is wrong or we need to tell it what's acceptable...

**Comment by isbm** [comment]
@s0undt3ch get it while it is [still there](https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/11005/violations/file/tests/unit/modules/timezone_test.py/).

**Comment by s0undt3ch** [comment]
Bah! Dam you py2.6

OK this last change is good for this branch but should be reverted once it reaches the nitrogen or develop branches....

**Comment by isbm** [comment]
@s0undt3ch but the _main problem_ is that your environment still cannot to digest even if I remove decorators. So it means, it was _not_ the problem. Can you please assist here? Because I kind of ran out of ideas.

**Comment by isbm** [comment]
@s0undt3ch what you've done? :laughing: now seems green. Maybe we can drop that commit with the nested `with` and put decorators back?

**Comment by s0undt3ch** [comment]
Nope, leave it as it is.

It's green! :)

PS: I didn't do anything :)

**Comment by isbm** [comment]
:confused: 
@cachedout no idea why, but we are... good to go... :cry:

**Comment by thatch45** [comment]
Huzzah!

**Comment by isbm** [comment]
@cachedout just to double-check here: should I separately open a PR for `develop` or that will automagically appear there? Because there is already a test that regard (a little bit only).

**Comment by s0undt3ch** [comment]
It will get merged forward into develop, no need for a separate PR.

**Comment by isbm** [comment]
@s0undt3ch thanks for the clarification!

**Pull request merged**
