### PR TITLE
Glance state module for 2015.8 "Beryllium"

### PR DESCRIPTION
**Pull request by 0xf10e**
OK, a basic state module for OpenStack Glance, now based on the salt/2015.8 rev cef746159d!

@jfindlay: Only took me like 20 minutes to do this :D

### CODE REVIEW

**Comment by 0xf10e** [comment]
btw: can I get your Jenkin's .testing.pylintrc pretty please?
I'd prefer to clean up my code beforehand and my local pylint seems to be much less strict

**Comment by jfindlay** [comment]
Thanks, @0xf10e.  You can find .testing.pylintrc in the root directory of the salt repository.

**Comment by thatch45** [comment]
This looks great @0xf10e ! Can you add support for test = True? We just need the check to not run if test == true, here is an example:
https://github.com/saltstack/salt/blob/develop/salt/states/kmod.py#L52

**Comment by 0xf10e** [comment]
Probably. Has to wait for few days until I got a less other things on my todolist.

Am 20. Juli 2015 17:28:31 MESZ, schrieb Thomas S Hatch <notifications@github.com>:

**Comment by jfindlay** [comment]
@0xf10e, any progress on this?

**Comment by 0xf10e** [comment]
No, sorry, not yet. Was busy with "OMG my workstation is on fire!" kinda stuff I had to get off my to do list first.
But I /think/ there shouldn't be anything urgent left so can concentrate on not breaking my code when adding the ``test=True`` stuff tomorrow.

**Comment by 0xf10e** [comment]
Here we go, first try.
Had to add the 'name' parameter to the ``glance.image_list`` exec function.

**Comment by 0xf10e** [comment]
Argh, I can't return multiple images with the same name (in exec func ``glance.image_list``) when the dict is keyed by the images' names!

I guess I shouldn't change this behavior before the next release so I have to throw an error instead...

**Comment by 0xf10e** [comment]
The only error in [jenkins/salt-pr-rs-ubuntu14.04-n log](https://jenkins.saltstack.com/job/salt-pr-rs-ubuntu14.04-n/7375/consoleFull) is this:
```
10:32:30 ----------
10:32:30           ID: lxc
10:32:30     Function: pkg.latest
10:32:30       Result: False
10:32:30      Comment: Package lxc failed to update. The following packages were already up-to-date: libcgmanager0
10:32:30      Started: 10:31:06.768897
10:32:30     Duration: 1255.52 ms
10:32:30      Changes:   
10:32:30 ----------
```
I don't think that's my fault ;)

**Comment by 0xf10e** [comment]
Why didn't anyone tell me 2015.8 is Beryllium, not Boron? :(
Bunch of corrections coming in in the next 20 minutes...

**Comment by 0xf10e** [comment]
Just to make sure I got this right now:

2015.5: Lithium, current stable
2015.8: Beryllium, the version to import this into
2016.x: Boron, when to change behavior (not wrapping dicts around stuff)
2016.y: Carbon, when to raise RuntimeError (via ``warn_until()``) when obsolete code (to unwrap stuff) is used

**Comment by 0xf10e** [comment]
If you don't mind I'll add fixes for @whytewolf's #25814 here, too

**Comment by thatch45** [comment]
Go for it, this is good to merge on my side so just say when you are ready @0xf10e !

**Comment by basepi** [comment]
This was inadvertently closed. Sorry!

**Comment by 0xf10e** [comment]
Looks like  jenkins/salt-pr-rs-ubuntu14.04-n failed because it got  fa0b784 instead of 2991e40...

**Comment by 0xf10e** [comment]
Same thing for jenkins/salt-pr-rs-cent7-n:
```
16:42:05 Commits don't match fa0b78435f4e7457d67cd2eb7c3c7dda77b25035 == 2991e4028e8333c945d54d2eb9cd740c07a859b0
```

**Pull request merged**
