### PR TITLE
Interactive test suite

### PR DESCRIPTION
**Pull request by cachedout**
Provide a way to run the test suite in "interactive" mode. This means it will start up the necessary deamons and then sleep, giving you information on how to interact with those daemons directly. So with a single command, you can now spin up a master, two minions, a syndic and a secondary master, perform all module/grain syncing and then interact with them easily.

Use `python ./runtests --interactive` for an example. A sample output is as follows:

``
mp@silver ...devel/salt/tests % sudo python2 ./runtests.py --interactive                                                                                                                               (git)-[daemons_only] 

```
 * Transplanting configuration files to '/tmp/salt-tests-tmpdir/config'
 * Current Directory: /home/mp/devel/salt/tests
 * Test suite is running under PID 15937
 * Logging tests on /tmp/salt-runtests.log
```
- Max open files setting is too low(1024) for running the tests
- Trying to raise the limit to 3072

```
 * Setting up Salt daemons for interactive use
```
- Waiting at most 0:02:00 for minions(minion, sub_minion) to connect back
  - minion connected.  
  - sub_minion connected.  
- Syncing minion's modules (saltutil.sync_modules)
#  \* Syncing minion's states (saltutil.sync_states)                                                                                                                                                                            

```
 * Salt daemons started
```
- Syndic master configuration values

```
interface: 0.0.0.0
publish port: 54505
return port: 54506


```
- Master configuration values

```
interface: 0.0.0.0
publish port: 64505
return port: 64506


```
- Minion configuration values

```
interface: 0.0.0.0


```
- Syndic configuration values

```
interface: 0.0.0.0
syndic master port: localhost


```

 Your client configuration is at /tmp/salt-tests-tmpdir/config

```
To access the minion: `salt -c /tmp/salt-tests-tmpdir/config minion test.ping

``
```

### CODE REVIEW

**Comment by cachedout** [comment]
This also dials down the ``loop_interval`` on the minion, which was set so high that it was just chewing CPU. The test suite sees performance improvements in numerous places as a result.

**Comment by jfindlay** [comment]
Very nice!

**Comment by jfindlay** [comment]
@cachedout, do you mind if we backport this to 2015.2?

**Comment by cachedout** [comment]
That is just fine. Thanks for checking!

**Comment by jfindlay** [comment]
Awesome, thanks.

**Pull request merged**
