### PR TITLE
Add engine for fluent to master

### PR DESCRIPTION
**Pull request by mchugh19**
### What does this PR do?
Master port of #51942
Adds new engine to export events to fluentd

### What issues does this PR fix or reference?
None

### Tests written?
No - as discussed in PR #51942...
> Having a bit of trouble here. The other engine test examples are the sqs engine which validates sqs messages can be resent on the salt event bus, while the slack tests validate the complex configuration. For the fluent engine, it really is just:

```
while True:
    salt_event = event_bus.get_event_block()
    if salt_event:
        event.Event(app, salt_event)
```

> where I'm struggling to come up with a meaningful test. As long as the fluent event module is functional, and the event_bus.get_event_block() works as expected, there isn't much else to validate here.

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by dwoz** [comment]
@mchugh19 Can you please rebase to the current `head` of master and resolve the change log conflicts?

**Comment by mchugh19** [comment]
Resolved conflicts on release notes

**Comment by dwoz** [comment]
@mchugh19 Please have a look at the docs failure.

**Comment by mchugh19** [comment]
@dwoz docs should be better. Go go jenkins doc build

**Comment by dwoz** [comment]
re-run full centos-8

**Review by dwoz — APPROVED** [review]

**Pull request merged**
