### PR TITLE
Fix default values for master_tops and file_ignore_regex

### PR DESCRIPTION
**Pull request by sjorge**
### What does this PR do?

About a weak ago some salt-master started complaining about master_tops and file_ignore_regex having incorrect value types.

I took me a while to figure out I managed to fix it (at least for master_tops and file_ignore_regex).
I verified with the documentation for the correct type of dict and list respectively.
### What issues does this PR fix or reference?
#31563
### Previous Behavior

Complain about master_tops and file_ignore_regex value types
### New Behavior

Value types changed from bool to the proper dict and list.
### Tests written?
- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by sjorge** [comment]
Wrong branch

**Comment by cro** [comment]
Hey @sgeorge, I think we just merged a fix for master_tops. I haven't seen the file_ignore_regex problem, so you might want to check the relevant branches to see if it's fixed there as well.

**Comment by sjorge** [comment]
I checked in 2016.3 (only one I can get to run reliably on illumos) with a checkout from a hour ago and it still had the wrong stuff in salt/config/__init__.py. (Like wise for current develop).

The file is not present on 2015.8.

**Comment by rallytime** [comment]
The master tops fix is in the 2015.8 branch. I'm doing a merge-forward for that today.

**Comment by sjorge** [comment]
That still leaves file_ignore_regex, as I can't run 2015.8... I can do a PR for that but can't test it :-1: 
I found the file too in 2015.8.

**Comment by sjorge** [comment]
@rallytime #31723 fixes the file_ignore_regex stuff in 2015.8 (I only could do limited testing, as 2015.8 + illumos/SmartOS are not the best of friends)

But it's basically the same fix as #31707 which is a copy of this PR but against 2016.3 which fixed the problem for me.

**Pull request closed without merging**
