### PR TITLE
cherry-picking of smartos virt and vmadm module

### PR DESCRIPTION
**Pull request by sjorge**
This is a cherry picked branch of PR #26733 for develop.\
note: I will now mention virtual names instead of file names for clarity
- keep the updated 'virt' module by @isbm around as smartos_virt.py
- cherry picked 'vmadm' module by @sjorge as the new smartos_vmadm.py

With the 'virt' module that is now more or less inline with 'virt' for other platforms closing issue #26507 for develop branch. One more PR will follow later today to do the same for 2015.8 branch.

I may revisit 'virt' module for a bit more cleanup after my trip.

### CODE REVIEW

**Comment by sjorge** [comment]
Test fail doesn't look like it is code related?

**Comment by sjorge** [comment]
go go jenkins!

**Comment by isbm** [comment]
@sjorge, thanks cleaning this up. That was my plans, although yet I was unable to find a free hardware for SmartOS to finish this, and this OS does not like to run on a VM... :cry: 

Thanks a lot!

**Comment by sjorge** [comment]
@isbm newish (last month?) platform iso/images for smartos now vioblk and vioif drivers. So they should work pretty OK under qemu-kvm (vmware is likewise pretty OK). 

Once I am back from my trip I'll probably make smartos_virt.py do calls to the vmadm replacement internally.

**Pull request merged**
