### PR TITLE
Fixes #39901 for RH/CentOS 7

### LINKED ISSUE #39901: network.managed ipaddrs ignored
### Description of Issue/Question
Using network.managed for any interface and using ippaddrs, all ips w/in the ipaddrs list are ignored instead of generating a IPADDR0...X and GATEWAY/SUBNET0...X

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
lo:
  network.managed:
    - name: lo
    - type: eth
    - onboot: yes
    - userctl: no
    - ipaddrs:
      - 127.0.0.1/8
      - 10.234.0.73/32
```
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Use above state and note that your original ifcfg-lo which would look like this:
```
DEVICE=lo
IPADDR=127.0.0.1
NETMASK=255.0.0.0
NETWORK=127.0.0.0
# If you're having problems with gated making 127.0.0.0/8 a martian,
# you can change this to something else (255.255.255.255, for example)
BROADCAST=127.255.255.255
ONBOOT=yes
NAME=loopback
```

now looks like this:
```
DEVICE="lo"
HWADDR="00:00:00:00:00:00"
USERCTL="no"
TYPE="Ethernet"
ONBOOT="yes"
```

instead of something more realistic like this:
```
DEVICE="lo"
HWADDR="00:00:00:00:00:00"
USERCTL="no"
TYPE="Ethernet"
ONBOOT="yes"
IPADDR0="127.0.0.1"
NETMASK0="255.0.0.0"
IPADDR1="10.234.0.73"
NETMASK1="255.255.255.255"
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 4.9.13-2.el7.centos.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```
Even on salt v2016.3.5, I get the same results, and it doesn't matter what IP ranges, subnets, interfaces, etc.. I choose.  Also, I used the example straight from https://docs.saltstack.com/en/latest/ref/states/all/salt.states.network.html#configuration-of-network-interfaces for configuration the loopback device and same results.  I'm trying to avoid keep doing the rc.local hack to add VIPs to servers or having to setup an ifcfg-lo template when ideally ipaddrs for network.managed should work.

### PR DESCRIPTION
**Pull request by seanjnkns**
### What does this PR do?
Corrects the functionality of ipaddrs and ipv6addrs in network.managed state for RH/CentOS 7.

### What issues does this PR fix or reference?
#39901

### Previous Behavior
ipaddrs and ipv6addrs opts were passed to rh_ip.py module, but were ignored in the template.

### New Behavior
ipaddrs and ipv6addrs now correctly populate the template

### Tests written?

No

### Commits signed with GPG?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by gtmanfred — APPROVED** [review]

**Comment by seanjnkns** [comment]
@gtmanfred, please don't merge this yet.  I hadn't noticed the salt.utils.validate.net.* options so I can validate a CIDR is given for ipaddrs and ipv6addrs, until just now.  I'd like to get that validation and _raise_error_iface try/exception block entry in there first, if that's ok.

**Comment by cachedout** [comment]
@seanjnkns Ready for us to review this now that you've pushed some changes?

**Comment by seanjnkns** [comment]
Yeah, go ahead.  Sorry, I should have said something earlier.

**Review by gtmanfred — APPROVED** [review]

**Comment by seanjnkns** [comment]
Anything I can do to help get this merged?

**Comment by cachedout** [comment]
@seanjnkns Can we get this fix covered by a unit test?

**Comment by seanjnkns** [comment]
Sure, I'll see if between SaltConf 2017 sessions, or after hours, I can whip something up.  Otherwise, it'll be this weekend.

**Comment by seanjnkns** [comment]
Added unit tests to cover ipaddrs and ipv6addrs.  In addition, because the unit test only tested the RH6 templates, added logic to test all templates, and then because ipaddrs and ipv6addrs is only being added to the RH7 template, an osrelease check to perform the appropriate checks on just those 2 items.

**Comment by seanjnkns** [comment]
It's worth mentioning that a number of unit tests need to be written for the templates that currently don't exist (unrelated to this PR).  I'm hoping my changes to the unit tests can lay the ground work for further tests that should be performed.

**Review by rallytime — APPROVED** [review]

**Pull request merged**
