### PR TITLE
[Salt-cloud] Allow to ignore ssl with Xen provider

### PR DESCRIPTION
**Pull request by vberthet**
Allow to ignore ssl verification for xen providers

# /etc/salt/cloud.providers.d/xentest.conf
xentest:
  ignore_ssl: True
  driver: xen

Require a recent XenAPI.py which can be found here: https://github.com/xapi-project/xen-api/blob/master/scripts/examples/python/XenAPI.py

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by rallytime** [comment]
Hi @vberthet - can you fix up this lint error? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/12655/violations/file/salt/cloud/clouds/xen.py/

**Comment by vberthet** [comment]
Hi @rallytime it should be fixed.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by vberthet** [comment]
Hi,
I'm not a Jenkins user, so i'm quite lost.
But it seems to me that the failing test is related to missing/wrong doc on that functions : 
- libcloud_compute.get_driver   
- libcloud_loadbalancer.get_driver   
- libcloud_storage.get_driver

I haven't change those functions, i don't even know where there are.
Do i've correctly understand falling test ?  
What should be done to fix that ?

**Comment by rallytime** [comment]
Hi @vberthet - yeah those are unrelated. I've updated your branch to the latest upstream of `develop`, which should have these tests fixed already. Thanks!

**Review by rallytime — APPROVED** [review]

**Pull request merged**
