### PR TITLE
Fix: salt.modules.yumpkg: ConfigParser to read ini like files.

### LINKED ISSUE #42041: pkg.list_repo_pkgs fails to find pkgs with spaces around yum repo enabled value
### Description of Issue/Question

`pkg.list_repo_pkgs` fails to find pkgs if the "enabled" line in the yum repo definition contains spaces around the value. i.e.:

works: `enabled=1`
fails: `enabled = 1`

The problem is in the parser used by `pkg.list_repos`:

- https://github.com/saltstack/salt/blob/2016.11/salt/modules/yumpkg.py#L2539-L2540

### Setup

Modify a .repo file in /etc/yum.repos.d and change an enabled repo from `enabled=1` to `enabled = 1`.

### Steps to Reproduce Issue

Run `salt-call --local pkg.list_repo_pkgs <pkg-in-modified-repo>`.

### Versions Report
```
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.21.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

### PR DESCRIPTION
**Pull request by arount**
### What does this PR do?

Use `configparser` within `salt.modules.yumpkg._parse_repo_file` instead of homemade loopy stuff.

It fix an issue, but more important it sanitize this function.

### What issues does this PR fix or reference?

Fix https://github.com/saltstack/salt/issues/42041

Btw, this PR is done to be a cleaner solution than https://github.com/saltstack/salt/pull/42044 where fellow @lorengordon fixed issue in a _non really clean way_.

## Changes

The only functional change is `comments` key is not available anymore, but 

1. Comments in old code say it's useless to keep comments
2. Users always can use comments, but only inline ones.

I don't think `headers` (aka leading comments) are really useful too, but I kept it for regression issue.

Last thing, I made this function return empty config if error happends when reading raw file, maybe should I raise exception ?

### CODE REVIEW

**Comment by lorengordon** [comment]
@arount Yep, this patch also fixes the issue I reported! Thanks!

For the salt devs, note that my PR is against 2016.11, as I think the least intrusive way to address the bug. This PR is against develop, as the approach is much cleaner overall, but is a bit of a bigger change.

**Comment by cachedout** [comment]
This looks very clean. I'd like @terminalmage to also look at it.

@lorengordon Do you want to close your PR and have us backport this one?

**Comment by lorengordon** [comment]
@cachedout no objections from me, if you're cool with this change in 2016.11! :)

**Review by terminalmage — APPROVED** [review]

**Comment by cachedout** [comment]
I would definitely prefer to have this in the develop branch.

@arount Could you close this PR and re-open it against develop?

**Comment by arount** [comment]
k :)

**Comment by rallytime** [comment]
@cachedout and @arount So it looks like this is currently against `develop`, but it looks like you were saying it should be in 2016.11. Does this need to be back-ported to 2016.11? Or what was the final decision?

**Comment by arount** [comment]
@rallytime @cachedout tell me if i need to rebase on a specific branch

**Comment by rallytime** [comment]
@arount It looks like this now has a merge conflict. Can you resolve the conflict?

**Comment by arount** [comment]
done

**Comment by cachedout** [comment]
python3 tests are raising an exception here.

**Comment by arount** [comment]
Hm, I will check that today

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@arount Any news on that Py3 failed test?

**Comment by rallytime** [comment]
@arount Just a bump to see if you have had time to look into the test failures listed above.

**Comment by arount** [comment]
Hi there, sorry I was offline for a while and don't have any time right now :/
I close this PR hoping somebody would re-open it on another fork..

Thx

**Comment by rallytime** [comment]
@lorengordon Is this something you are interested in looking at? I know you were involved in the other fix.

**Comment by lorengordon** [comment]
Sure, I just checked out arount's branch, rebased from current develop, and will open a new PR to see what the tests look like now.

**Pull request closed without merging**
