### PR TITLE
Log the error generated that causes returns.mysql.returner to except.

### PR DESCRIPTION
**Pull request by kaithar**
Got frustrated with it eating the mysql error that was making things blow up :)

### CODE REVIEW

**Comment by jfindlay** [comment]
Nice, thanks @kaithar.  I hate disappearing errors too.

**Comment by jfindlay** [comment]
In the future, please feel free to submit bug fixes directly to the oldest supported and applicable release branch as the branches are regularly merged forward, see https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

**Comment by kaithar** [comment]
Oh, yeah, suppose this would be considered a bug fix.  I didn't think of it that way since it felt more like I was adding the message logging rather than restoring it.  Thanks for merging.

**Comment by jfindlay** [comment]
No problem, thanks for the 'fix'. :-)

**Pull request merged**
