### PR TITLE
Rewrite git state and execution modules

### LINKED ISSUE #10141: Git state doesn't fetch tags before trying to checkout to it
In git.latest state, salt try to run git fetch (https://github.com/saltstack/salt/blob/develop/salt/states/git.py#L222) before trying to checkout to rev (https://github.com/saltstack/salt/blob/develop/salt/states/git.py#L227).

The problem is when we use tags which are not retrieved via git fetch (a multi head on master branch). Salt should run git fetch with "--tags" option in order to retrieve them.

The usecase is not common and we maybe need to work on our release workflow but it's an easy fix, so if it's a good idea, I will add a pull-request.

### PR DESCRIPTION
**Pull request by terminalmage**
This rewrite does the following:
1. Renames git.config state to git.config_set (while also adding multivar support)
2. Adds git.config_unset state
3. Rewrites other git states
4. Changes all functions in the execution module to passing arguments in a list
   of strings (obsoletes any issues caused by not properly escaping CLI
   arguments)
5. Adds a bunch of new functions to the execution module to help further fill
   out coverage of git commands
6. Adds worktree support to the execution module (and recognition of worktrees
   to the states)
7. Fixes #10141, #14719, #15517, #15833, #16152, #19603, #25969

### CODE REVIEW

**Comment by terminalmage** [comment]
Looking at the tests now. As expected, all the git tests are failing. Most (if not all) are likely due to state outcomes changing.

**Comment by terminalmage** [comment]
Failures were legit. I might not have gotten all the lint failures, there were a couple in the test suite but I want to see if the fixes I just pushed take care of those. If not, I'll handle them (and any remaining failing tests) over the weekend.

**Comment by terminalmage** [comment]
I can't reproduce any of these test failures. Can someone else take a look?

**Comment by terminalmage** [comment]
I've removed my git tests temporarily to see if this affects the other failing tests.

**Comment by terminalmage** [comment]
OK clearly the failures are being caused in some way by my tests. The culprit is probably somewhere in my setUp function. I'm going to add back the tests and comment out all but one of them and see if the failures come back.

**Comment by terminalmage** [comment]
Problem narrowed down to setUp func, doing a little more work to try to narrow it further.

**Comment by terminalmage** [comment]
OK, I found a python 2.7-specific function call that I replaced, and there were additional unrelated issues in setUp (missing global `user.name` and `user.email`) that were keeping me from committing to the test repo in the setUp function.

Both are fixed, and I've reset to remove the debugging commits and force-pushed. New tests queued now, we'll see how they shake out.

**Comment by terminalmage** [comment]
:tada: :laughing: :cry: :sleeping:

**Comment by cachedout** [comment]
W00t!

**Comment by terminalmage** [comment]
Also fixes the following:

https://github.com/saltstack/salt/issues/24386

**Pull request merged**
