### PR TITLE
Replace custom decorators with pytest markers

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title

### CODE REVIEW

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run all

**Comment by s0undt3ch** [comment]
re-run windows-2016-pytest

**Comment by s0undt3ch** [comment]
re-run py3-windows-2016-pytest

**Comment by s0undt3ch** [comment]
re-run all

**Review by krionbsd — DISMISSED** [review]

**Pull request merged**
