### PR TITLE
Use identity for LFS objects during git checkout

### LINKED ISSUE #54789: git lfs requires identity to perform checkout
### Description of Issue
When attempting to clone a repo containing LFS files with `git.latest`, I'm encountering a `Permission denied` error during the `checkout` step:
```
salt.exceptions.CommandExecutionError: Command 'git checkout --force -b lfs-test origin/lfs-test' failed: Downloading testfile.lfstest (13 B)
Error downloading object: testfile.lfstest (1099f81): Smudge error: Error downloading testfile.lfstest (1099f819239adba18116089276ef35482bfea486a58aa759802eb1e7b7443f15): batch request: Permission denied (publickey).: exit status 255
```

I see the `identity` argument got added to several of the git commands in #51319, but not to `checkout`.  I've managed to fix the issue by adding it in, will submit a PR a bit later.

### Setup
Running the following SLS with `sudo salt-call --local --file-root=/home/vagrant/testsalt -linfo state.apply testgit`:
```
ensure git lfs is installed:
  pkg.installed:
    - name: git-lfs

ensure repo is cloned:
  git.latest:
    - name: <private_repo_uri>
    - target: <target_directory>
    - rev: lfs-test
    - branch: lfs-test
    - identity: <ssh_key_file>
    - force_checkout: True
    - force_fetch: True
    - force_reset: True
    - user: vagrant
    - require:
      - pkg: ensure git lfs is installed
      - cmd: ensure git lfs is configured for root

ensure git lfs is configured for root:
  cmd.run:
    # In 2019.2.1 (the first version with LFS support), it hard checks global user
    # config, and we run as root
    - name: git lfs install
    - unless: grep -q 'git-lfs smudge' /root/.gitconfig
    - require:
      - pkg: ensure git lfs is installed

### Steps to Reproduce Issue
1. Have a private repo with LFS files
2. Apply the state above

### Versions Report
This is reproducable running locally, I haven't tested it in a master-minion setup.
```
$ salt-call --version
salt-call 2019.2.1 (Fluorine)
```

### PR DESCRIPTION
**Pull request by feinu**
Fixes #54789

I based this largely off of #51319 .

It's my first PR on this repo, so hope I got everything right.

Edit: The original issue got tagged with 2019.2.1, but I noticed that this was present in 2018.3 as well, so I based the PR off that.

### What does this PR do?
* Adds an `identity` kwarg to `checkout` in the `git` module.
* Changes calls to `checkout` from `git.latest` to also pass `**lfs_opts`, which contains the identity.

### What issues does this PR fix or reference?
#54789 

### Previous Behavior
Failed when using `git.latest` to clone a repo with LFS objects in a branch.
```
     Comment: Downloading testfile.lfstest (13 B)
              Error downloading object: testfile.lfstest (1099f81): Smudge error: Error downloading testfile.lfstest (1099f819239adba18116089276ef35482bfea486a58aa759802eb1e7b7443f15): batch request: Permission denied (publickey).: exit status 255  
```                                                                              

### New Behavior
It works!

### Tests written?
No

I'm not really sure how to go about doing so.  As I understand it, the test conditions would require a private repo with SSH key authentication, having LFS objects in a branch that are not in the default branch.

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by feinu** [comment]
The doc build failure looks related to this PR's changes, I'm not sure about the others.

**Comment by feinu** [comment]
What is the next step here? As far as I can tell the failing checks are unrelated to this PR.

**Comment by waynew** [comment]
Thanks for the PR!

> Edit: The original issue got tagged with 2019.2.1, but I noticed that this was present in 2018.3 as well, so I based the PR off that.

@feinu Well, that *had* been the correct approach, but we are no longer releasing on older branches, so if you could rebase this change on `master`, and edit the PR to point to master, that would be awesome!

**Comment by feinu** [comment]
@waynew Oh ok, I thought it had to be based off the oldest supported main release branch (per https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch), since it's a bugfix PR.  Is that no longer the policy?

**Comment by waynew** [comment]
@feinu we're in the process of changing the process 🙃 We'll be updating the docs in the near future

**Comment by feinu** [comment]
I have messed up the source branch.  Will recreate the PR with a different source branch.

**Comment by feinu** [comment]
@waynew I have created a clean branch off `master`, and combined the changes for this PR into a single commit.  That PR is at #55069.

I'm closing this PR now, as it's no longer relevant.  Sorry for the hassle.

**Pull request closed without merging**
