### PR TITLE
Allow cherrypy to gzip json and yaml responses

### PR DESCRIPTION
**Pull request by mbirtwell**
### What does this PR do?

Sets some cherrypy configuration so that it will gzip json and yaml responses from the salt API. Only applies if the client sends Accept-Encoding: gzip

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by krionbsd — CHANGES_REQUESTED** [review]
@mbirtwell thanks for contribution, could you please run pre-commit hook on your changes and re-commit it? It would be nice if you could add a test case for this change as well, if possible.

**Comment by mbirtwell** [comment]
I think that the unit tests were interacting with cherrypy at a level which didn't run the middleware responsible for gzipping responses. So I've gone for an integration test.

**Comment by krionbsd** [comment]
> I think that the unit tests were interacting with cherrypy at a level which didn't run the middleware responsible for gzipping responses. So I've gone for an integration test.

Awesome @mbirtwell, thanks a lot, we'll merge it soon

**Review by krionbsd — APPROVED** [review]

**Comment by mbirtwell** [comment]
I stand by this PR, my former employer had been using this in production for more than a year when I left and I believe that the check failures were flakes and not to do with the changes in this PR. But I want to close this to get it off my dashboard.

**Pull request closed without merging**
