### PR TITLE
Add next gen win_servermanager execution and state modules for newer Windows minions

### PR DESCRIPTION
**Pull request by iamseth**
### What does this PR do?

Adds a new win_servermanager_ng module to support Windows 8 and 2012 and above minions.
### What issues does this PR fix or reference?
#31841
### Previous Behavior

Windows minions above 8.x and 2012.x  would use the now deprecated Add-WindowsFeature Powershell cmdlet.
### New Behavior

Newer Windows minions will use the Install-WindowsFeature cmdlet and support the 'management' and 'restart' options.
### Tests written?
- [ ] Yes
- [X ] No

### CODE REVIEW

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Hi @iamseth 

Thanks for this. I've read your PR and gone back and read the original issue as well.

From the looks of things here, the differences are very minor between the functionality in the old execution module and the new one, save some small adjustments in the actual Powershell commands which are called. Is this a fair assessment? If so, I'm a little reluctant to merge an entirely new `_ng` module just to solve this, when we could easily just put these behind some conditionals in each function.

I do know this was the original suggestion that came from your issue that you filed, so apologies for any run-around. I just want to make sure we come up with the best solution here. :]

Let me know what you think. Thanks.

**Comment by iamseth** [comment]
@cachedout you're right, the change is pretty minor. Initially I wanted to replace the underlying PowerShell call but it would break older minions.

I don't mind refactoring out the new '_ng' modules. Do you have a suggestion on handling the 2 new arguments? 1 of them is applicable to the old PowerShell cmdlet but the other is not. Would something like the following pseudocode be acceptable?

```python
def install(feature, recurse=False, restart=False, management=False):
    if _windows8():
      _install_feature(feature, recurse, restart, management)
    else:
      _add_feature(feature, recurse, restart)
```

That would make the 'management' argument a no-op for older Windows minions and I'd update the documentation to reflect that.

I could also remove the 'management' argument completely and make it implicit on newer minions. I believe this is the behavior of the old PowerShell cmdlet according to the Microsoft doc though I don't have an old Windows server around to confirm.

**Comment by cachedout** [comment]
Yup, that pseudocode is exactly the direction I'm thinking!

**Comment by iamseth** [comment]
@cachedout good call. I think this worked out much cleaner than it was originally.

**Comment by cachedout** [comment]
Agreed. This is very clean. Well done.

**Pull request merged**
