### PR TITLE
Pillar-based cloud providers still forcing use of deprecated 'provider'

### PR DESCRIPTION
**Pull request by The-Loeki**
Similar to #27953

### CODE REVIEW

**Comment by cachedout** [comment]
@The-Loeki There are some minor lint errors here. Could you please have a look?

@techhat or @rallytime Could one of you please sign-off here?

**Comment by rallytime** [comment]
LGTM. Thanks @The-Loeki!

**Comment by cachedout** [comment]
Thanks, @rallytime 

@The-Loeki Please let me know when the lint issues have been fixed and we will get this in. Thanks!

**Comment by The-Loeki** [comment]
sorry 'bout that @rallytime/@cachedout; all good now.

**Comment by cachedout** [comment]
No problem at all. Looks good now! Thanks, @The-Loeki

**Pull request merged**
