### PR TITLE
Handle bogus newline before newly added keys

### PR DESCRIPTION
**Pull request by 3add3287**
### What does this PR do?
modules/ssh.py adds bogus newlines before a newly added key. This patch fixes it.
It seems the intention of the original code was to detect if the existing authorized keys file needed to have a newline added in the end when adding a new key to the file. The code's check
for the existence of a new line was:
  _fh.seek(1024, 2)
  if not _fh.read(1024).rstrip(' ').endswith('\n'):
This couldn't work. Seeking to a positive 1024 byte offset from the end of the file (2) would seek to the end of the file. From there no bytes could be read as we were already at the end of the file. Hence the check failed and a new line was being added.

The patch does seek to -1 from the end of the file, reads one byte and checks if that is a newline.
This should work even if the file is UTF-8 encoded because a new line character at the end of a UTF-8 encoded line would still be \n. Since we're checking the end of the file, there's either a \n or there isn't. If there is, we have a new line. If there isn't,  we don't care what the last character is and add a new line.

### What issues does this PR fix or reference?
#33793

### Previous Behavior
modules/ssh.py and hence the ssh_auth state would add bogus empty lines in authorized_keys when new keys are being added. 

### New Behavior
No more bogus empty lines in authorized_keys

### Tests written?
No

### CODE REVIEW

**Review by cachedout — APPROVED** [review]

**Comment by 3add3287** [comment]
Thanks!

Is there anything I can do to get it into the 2017.7.2 release? I noticed the branch for that on GitHub, but there doesn't seem to be a release just yet.

**Comment by cachedout** [comment]
@3add3287 I'm afraid the cutoff for that release has passed but I will mark this for backporting and we will get it into a future point release as soon as we can.

**Comment by 3add3287** [comment]
Thanks!

**Comment by rallytime** [comment]
Hi @3add3287 and congrats on your first Salt pull request!

There are some lint errors that need to be cleaned up before we can get this in: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/14570/violations/

Can you fix those? Please let us know if you have any questions.

**Comment by 3add3287** [comment]
Had to edit this on another machine due to internet access to GitHub issues and it seems tabs sneaked in. Changed them to spaces & updated. Sorry for that!

**Review by rallytime — APPROVED** [review]

**Pull request merged**
