### PR TITLE
refactor gpg renderer; removing dependency on python-gnupg

### PR DESCRIPTION
**Pull request by cedwards**
This patch updates the gpg renderer to avoid the dependency on python-gnupg. I feel this patch is useful for two reasons:
1. fewer package dependencies are always better.
2. python-gnupg essentially calls out to the GPG binary anyway, so this just cuts out the middle man.

### CODE REVIEW

**Comment by jfindlay** [comment]
@cedwards, will you also look at the gpg test failures?  Thanks.

**Comment by cedwards** [comment]
@jfindlay - Yes, I will look into the unit tests. I'm not immediately sure why it's failing--the updated module works as expected in my infrastructure. I'll let you know what I discover.

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@cedwards A friendly ping. Have you been able to investigate these failures? This is a great addition and we would really like to get it merged! :]

**Comment by cedwards** [comment]
I have not yet had time to dig into the test failures. I need to be more familiar with the unit tests to understand why it's failing. 

Not to be "that guy", but I'm using this patch on my production systems and it's working as expected, so I assume it's something specifically related to the unit tests expecting GPG. I'll hopefully be able to look into it soon.

**Comment by cachedout** [comment]
Totally fine. I'd much rather you let us know versus letting this sit. I'll have a look-see tomorrow as well and we'll hopefully get this thing merged. Many thanks!

**Comment by cachedout** [comment]
I played around with this a bit this morning. Since the test suite relies on mocking the `GPG` python module, we'll need to basically rewrite the GPG renderer tests. I will create a ticket for the QA folks to do so.

**Comment by cachedout** [comment]
@jfindlay is going to write some tests for this and then we'll get it merged. Apologies for the delay here.

**Comment by jfindlay** [comment]
#25470 has these changes and the rewritten tests, so I'm going to close this.  Thanks @cedwards.

**Comment by cachedout** [comment]
This is awesome! Thanks very much @jfindlay and @cedwards

**Comment by cedwards** [comment]
@jfindlay @cachedout - I notice this merge continues to be skipped with each point release. Are we planning on including this at any point? I'd really like to remove the dependency on ``python-gnupg``.

**Comment by jfindlay** [comment]
@cedwards, this has been backported in #28921.

**Pull request closed without merging**
