### PR TITLE
update centos8 ami

### PR DESCRIPTION
**Pull request by bryceml**
### What does this PR do?
updates the centos8 ami to latest
It has problems that need fixed: https://jenkinsci.saltstack.com/job/Full-PR/job/full-pr-centos-8/job/master/9/

### CODE REVIEW

**Review by Ch3LL — DISMISSED** [review]

**Comment by bryceml** [comment]
re-run full centos8

**Comment by bryceml** [comment]
It appears that bower is in a different location on the new ami:

old:
/usr/bin/bower

new:
/usr/local/bin/bower

Is that supported?

**Comment by s0undt3ch** [comment]
Should we update root's default `PATH` to include `/usr/local/bin`?

**Comment by s0undt3ch** [comment]
Actually, I think the Bower module should use `salt.utils.path.which("bower")` and not assume `bower` is in path, since salt can actually find it if it's not in `PATH`

**Comment by Ch3LL** [comment]
re-run full centos8

**Comment by Ch3LL** [comment]
re-run full centos8

**Comment by Ch3LL** [comment]
re-run full centos8

**Review by dwoz — APPROVED** [review]

**Pull request merged**
