### PR TITLE
Added Garuda to the _OS_ lists

### PR DESCRIPTION
**Pull request by vuurvoske**
### What issues does this PR fix or reference?
Fixes:
Add Garuda Linux to the _OS_NAME_MAP and _OS_FAMILY_MAP

### Previous Behavior
Garuda linux was not present

### New Behavior
This will allow pacman to be run from salt on Garuda linux

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Other notes:
- It might be handy to backport
- https://gitlab.com/garuda-linux/themes-and-settings/settings/garuda-common-settings/-/issues/1
- 
### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by MidgardWarrior** [comment]
@vuuroske, you might want to check the commit. There might be a problem with your implementation in the _OS_FAMILY_MAP.

The comment above states:
```
# Map the 'os' grain to the 'os_family' grain
# These should always be capitalized entries as the lookup comes
# post-_OS_NAME_MAP. If your system is having trouble with detection, please
# make sure that the 'os' grain is capitalized and working correctly first.
```

Plese note the following:
-**These should always be capitalized entries as the lookup comes post-_OS_NAME_MAP**
-**please make sure that the 'os' grain is capitalized and working correctly first**

I see your key in the _OS_FAMILY_MAP is not capitalized, and this might be a problem. I see the **pr-debian-9-amd64-py3-pytest** test and this might be the cause of the problem. I'm not sure as I don't use this suite, but it could be an issue.

Regards

**Review by vuurvoske — COMMENTED** [review]
hotfixed, see new commit:

>  Update core.py

hotfixed the g-> G

Also salt 'hostname*' grains.items gives it in capatalized form, so you are problably right:

    os:
        Garuda
    os_family:
        Garuda
    osarch:
        x86_64
    oscodename:
        Bateleur
    osfinger:
        Garuda-Soaring
    osfullname:
        Garuda
    osrelease:
        Soaring
    osrelease_info:
        - Soaring

**Comment by bdrung** [comment]
I worked on cleaning up the OS grain calculation on Linux in https://github.com/saltstack/salt/pull/61626. We should address this bug after the pull request got reviewed and merged.

`/etc/os-release` from the downloaded ISO files (mount ISO, unsquashfs garuda/x86_64/rootfs.sfs):
```
NAME="Garuda Linux"
PRETTY_NAME="Garuda Linux"
ID=garuda
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://garudalinux.org/"
DOCUMENTATION_URL="https://wiki.garudalinux.org/"
SUPPORT_URL="https://forum.garudalinux.org/"
BUG_REPORT_URL="https://gitlab.com/groups/garuda-linux/"
LOGO=garudalinux
```

Since Garuda is an Arch derivative, it is affected by https://github.com/saltstack/salt/issues/54344 as well.

**Review by Ch3LL — CHANGES_REQUESTED** [review]
If you could resolve the merge conflict.

This will also require test coverage and a changelog

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
