### PR TITLE
[3006.x] fixes #65340 correct use of egrep to parse semanage output

### LINKED ISSUE #65340: [BUG] selinux.fcontext_policy_present can fail when the filespec is a regex
**Description**
A change introduced in 3006.3 to the selinux module function `_fcontext_add_or_delete_policy` checks for the presence of an existing matching context, and if one is found changes the action from "add" to "modify".

In certain corner cases, where regex are used for the filespec, this detection can match other contexts - which then changes the action to "modify", however since the policy does not actually exist, the attempt to modify fails.

**Setup**

- [ ] on-prem machine
- [X] VM (KVM)
- [X] Google Cloud
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [X] onedir packaging
- [X] used bootstrap to install

Use a state file `selinux.sls` containing:

```
context1:
  selinux.fcontext_policy_present:
    - name: /srv/ssl/ldap/.*[.]key
    - sel_type: slapd_cert_t

context2:
  selinux.fcontext_policy_present:
    - name: /srv/ssl/ldap(/.*[.](pem|crt))?
    - sel_type: cert_t
```

**Steps to Reproduce the behavior**

Given the above state file, and neither, fcontext policy already existing, `salt <minion_id> state.sls selinux` will create the first selinux fcontext policy but not the second.

Output will be:

```
minion_id:
----------
          ID: context1
    Function: selinux.fcontext_policy_present
        Name: /srv/ssl/ldap/.*[.]key
      Result: True
     Comment: 
     Started: 09:00:08.369900
    Duration: 1480.618 ms
     Changes:   
              ----------
              new:
                  ----------
                  /srv/ssl/ldap/.*[.]key:
                      ----------
                      filetype:
                          all files
                      sel_type:
                          slapd_cert_t
              old:
                  ----------
----------
          ID: context2
    Function: selinux.fcontext_policy_present
        Name: /srv/ssl/ldap(/.*[.](pem|crt))?
      Result: False
     Comment: Error adding new rule: {'pid': 52772, 'retcode': 1, 'stdout': '', 'stderr': 'ValueError: File context for /srv/ssl/ldap(/.*[.](pem|crt))? is not defined'}
     Started: 09:00:09.850697
    Duration: 946.32 ms
     Changes:   

Summary for minion_id
------------
Succeeded: 1 (changed=1)
Failed:    1
------------
Total states run:     2
```

**Expected behavior**
Both states should have succeeded.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.3
 
Python Version:
        Python: 3.10.13 (main, Sep  6 2023, 02:11:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.10
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: rocky 9.2 Blue Onyx
        locale: utf-8
       machine: x86_64
       release: 5.14.0-284.25.1.el9_2.x86_64
        system: Linux
       version: Rocky Linux 9.2 Blue Onyx
```
</details>

### PR DESCRIPTION
**Pull request by ndptech**
### What issues does this PR fix or reference?
Fixes: #65340 

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by Ch3LL — CHANGES_REQUESTED** [review]
This will require test coverage and a changelog

**Comment by dmurphy18** [comment]
@ndptech FYI for any PR to be accepted, it requires tests (written using pytest) and a changelog, these were requested a month ago.  Are you still interested in continuing this PR ?

**Comment by ndptech** [comment]
@dmurphy18 I am still interested in continuing, but have been very busy.
I'm not familiar with your test suite, and there didn't appear to be any existing tests that were in the same area to use as a base for building new tests - so it may take a while for me to work out what is really needed.
Ultimately there is a fault in 3006.3 and 3006.4 which this patch resolves.

**Comment by dmurphy18** [comment]
@ndptech Do you mind if I take your PR and run with it, making the changelog and tests for it, and have you review the changes, along with the core team.

**Comment by ndptech** [comment]
@dmurphy18 That's absolutely fine.

**Comment by dmurphy18** [comment]
@ndptech This PR is superseded by PR https://github.com/saltstack/salt/pull/65524, please review that PR at your leisure and consider closing this PR.

**Pull request closed without merging**
