### PR TITLE
Fix for issue #17198

### PR DESCRIPTION
**Pull request by AlexanderHaase**
Link to relevant issue: https://github.com/saltstack/salt/issues/17198

Promised implimentation of match_on criteria in mount.mounted, mount.set_fstab, mount.rm_fstab. Centralizes fstab parsing into DRY _fstab_entry class, and integrates that class into mount.fstab. All changes made with and tested against backwards compatibility.

Open issues: 
- fstab code doesn't normalize paths prior to comparison, leading to '/tmp' and '/tmp/' being interpreted as non-matching.
- We haven't specified how we should handle degenerate fstab entries. The current behavior is for set_fstab to modify all matching entries, and fstab to report the last matching entry. 
- match_on's auto mode only knows about common CentOS/RHEL fstypes requiring special handling. It's possible that several common options have been omitted. We could also consider options for detecting and warning the user when we have no idea if match_on's choice is sane, such as a known fstype dictionary, or detecting if device exists, and, if not, if we have a non-default behavior for this fstype.

### CODE REVIEW

**Comment by AlexanderHaase** [comment]
After much fun with pylint, pep8, local unit tests, and the automated build system, it seems like the remaining check failures are from upstream: my commits only modified salt {modules,states}/mount.py, and many other pull requests report the exact same failures regardless of topic. Guidance on how to proceed?

**Comment by thatch45** [comment]
Thanks @AlexanderHaase !

**Comment by rallytime** [comment]
2014.7 if possible.

**Comment by rallytime** [comment]
The changes were too great between 2014.7 and develop, but this did backport very nicely to 2015.2.

**Pull request merged**
