### PR TITLE
Beacons!!!!

### PR DESCRIPTION
**Pull request by thatch45**
Beacons allow for system queues, resources and anything else you can async watch on a system to be watched and translated into events sent back to the master, there is but one beacon system so far, inotiry, we need to get some log ones in, systemd-login, systemd-journal etc.

### CODE REVIEW

**Comment by cachedout** [comment]
YES!

**Comment by techhat** [comment]
@thatch45, did you mean `queue` instead of `que`?

**Comment by rallytime** [comment]
salt-beacon ftw!

**Comment by ryan-lane** [comment]
Does this add support for https://github.com/saltstack/salt/issues/11330!?

**Comment by cachedout** [comment]
Simply put, yes. :]

(Not that exact implementation, but the same idea!)

We should talk more about this at SaltConf. I really want to hear more
about how you might use this sort of approach.

**Comment by thatch45** [comment]
Yes

**Comment by thatch45** [comment]
More specifically, the config can be set in the minion config or the pillar, and I need to add grains to config.merge so that it can be set in the grains as well.
the inotify beacon also supports looking for specific file change properties, and the config can be dynamically updated

**Comment by UtahDave** [comment]
+1 for a dbus beacon per Ryan's feature request linked above

**Comment by thatch45** [comment]
I just made a journald beacon and am halfway through a wtmp beacon (login tracking)
A dbus one would be fairly easy, and much more efficient that using journald

**Comment by thatch45** [comment]
#20098 has a couple more beacons and some more beacon ideas

**Comment by ryan-lane** [comment]
This is *awesome*. I'd really love to be able to use this with masterless minions too. I'd definitely be keen to discuss this at SaltConf.

**Comment by thatch45** [comment]
Yes, right now it just forwards events to the master, we still need a minion side reactor option and to make beacons optionally fire on the minion event bus

**Pull request merged**
