### PR TITLE
maintain the fallabck because I am totally sick of this crap

### PR DESCRIPTION
**Pull request by thatch45**
### What does this PR do?

Fix for #33376

### CODE REVIEW

**Comment by tmehlinger** [comment]
👍

**Comment by babilen** [comment]
Why was this merged into 2015.5 and not 2015.8 ? It doesn't appear to have made it into 2015.8.10 due to this and:

```
babilen@clavain: ~/src/github.com/saltstack/salt (2015.5 u=) $ git branch --contains 081e6c5
* 2015.5
babilen@clavain: ~/src/github.com/saltstack/salt (2015.5 u=) $ git branch --contains 1d8b289
* 2015.5
babilen@clavain: ~/src/github.com/saltstack/salt (2015.5 u=) $ git branch --contains f5ebcba
* 2015.5
```
the commits have also not yet been merged forward (to either develop or 2015.8)

**Comment by thatch45** [comment]
heh, the problem is that we hurried to get the packages for 2015.8.10 out last night and we did not push the commits and the tag just because we finished the packages too late last night. So this fix IS in 2015.8.10 and we are getting that tag and changelog pushed etc this morning. Sorry for being a little out of order, we will have it all cleaned up in just a few more minutes

**Comment by babilen** [comment]
Cool, thank you!

**Comment by thatch45** [comment]
yep, sorry for being a little inconsistent this time! Thanks!

**Comment by babilen** [comment]
No problem. It is just that I ran into https://github.com/saltstack/salt/issues/33393 this morning and immediately thought about this issue.

**Pull request merged**
