### PR TITLE
Multi-command salt calls return highest exit

### PR DESCRIPTION
**Pull request by KaiSforza**
### What does this PR do?

Running a multiple command salt call will currently make salt think that
all of the minions returned with a failed state regardless of the return
values of the modules actually run. Right now it just returns the value
of `retcode` in the return dictionary if the return value is a
dictionary.

This checks if the `retcode` value is a dictionary itself, and then
returns the maximum return code that we recieved. This means that we
will continue to fail if the jobs did fail, but will return a zero if
all the jobs did so.

### What issues does this PR fix or reference?

#18510 

### Previous Behavior

The salt summary would say that any multi-module salt call had failed, because it did not know how to parse returns with a dictionary `retcode`.

### New Behavior

Salt now handles dictionary `retcode` values by taking the highest return value from multi-module call and using that to determine if it failed.

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by KaiSforza** [comment]
Updated the default value from the `.get()` to be a `dict` so it actually has `.values()`

**Comment by KaiSforza** [comment]
Fixed code lint check failure

`18:16:33 salt/cli/salt.py:405: [C0325(superfluous-parens), ] Unnecessary parens after u'return' keyword`

**Review by isbm — APPROVED** [review]
@rallytime the code looks good dealing with the different exit code types and structures :wink: but it would be still good to run a tests over it.

**Review by gtmanfred — APPROVED** [review]

**Comment by KaiSforza** [comment]
Okay it looks like the tests are failing outside of my changes.

**Review by terminalmage — APPROVED** [review]

**Pull request merged**
