### PR TITLE
Add support for nacl renderer for encrypted data

### PR DESCRIPTION
**Pull request by yagnik**
### Addition
- New renderer on top of nacl sealed boxes to allow encrypted data in sls files

### Tests written?
Yes

### Requires
https://github.com/saltstack/salt/pull/41833

### CODE REVIEW

**Comment by yagnik** [comment]
Build on top of the work done by @steverweber

**Comment by yagnik** [comment]
cc @cachedout because you already have context with other mr :)

**Comment by yagnik** [comment]
cc @coolstone16

**Comment by mirceaulinic** [comment]
This is very cool. Thanks @yagnik

**Comment by steverweber** [comment]
perhaps `NACLENC` should be `NACLDEC`

A bigger question Is the renderer really needed?

the renderer reduced:
```
{{salt.nacl.dec_pub('CTpZyxS6hXO54ivbmUlbGSRlJIIJWj0llou3vJ4=')}}
```
to
```
NACLENC[CTpZyxS6hXO54ivbmUlbGSRlJIIJWj0llou3vJ4=]
```

also im a little worried about people that will encrypt larger items like ssl certs.  these have new line chars that will cause issues with the other renders like yaml.  that is why `|json` is used to encode new lines.

```
cert_contents: {{salt.nacl.dec_pub('CTpZyxS6hXO54ivbmUlbGSRlJIIJWj0llou3vJ4=')|json}}
```

**Comment by yagnik** [comment]
- I prefer NACLENC to signify that this is "nacl encrypted string"

- As for whether the renderer is needed, I see it same as the gpg renderer but with a different encryption mechanism. My understanding with renderers is that the reason they are part of salt is for this very use case, wherein we don't need to call salt functions all over our sls file

- Moreover my thoughts on not using jinja is because I want to extend this to support a similar functionality as [ansible vault](http://docs.ansible.com/ansible/playbooks_vault.html) and ability to manage similar to [ejson](https://github.com/shopify/ejson) from my past life.

- On the above note, I'm thinking that my pr is not complete and I should consider using yaml tag to signify encrypted fields similar to ansible, I'll update this pr with that support.

- Finally, I agree that multiline could be a concern, I'll play with that before coming to a conclusion. I naively assumed that given the nacl module does base64 encoding, I won't have to worry about multiline myself. 

@steverweber let me know what you think ?

**Comment by mirceaulinic** [comment]
> A bigger question Is the renderer really needed?
the renderer reduced:
{{salt.nacl.dec_pub('CTpZyxS6hXO54ivbmUlbGSRlJIIJWj0llou3vJ4=')}}
to
NACLENC[CTpZyxS6hXO54ivbmUlbGSRlJIIJWj0llou3vJ4=]

I believe it is needed. The pattern you provided can be well reproduced with ```salt.gpg.decryp```, but there's also a GPG rendered making our lives easier and the pillars more human readable. As an aside, ```{{salt.nacl.dec_pub('CTpZyxS6hXO54ivbmUlbGSRlJIIJWj0llou3vJ4=')}}``` implies that Jinja is enabled, while the pillar could easily just have the header ```#!yaml|nacl``` etc. I believe this is a nice addition.

**Comment by steverweber** [comment]
I often play devil's advocate. i'm glad there is buyin for this renderer.

 > I prefer NACLENC to signify that this is "nacl encrypted string"

perhaps `NACL` its shorter :)

 >  ansible vault 

looks interesting

 > multiline

perhaps have somthing like 'NACL_JSON|' to encode the string/binary as json.
and `NACL_BASE64|`

**Comment by yagnik** [comment]
@steverweber 
> I often play devil's advocate. i'm glad there is buyin for this renderer.

We got that one common, I think uw teaches that somewhere :)

> perhaps NACL its shorter :)

👍 done

> perhaps have somthing like NACL_JSON| to encode the string/binary as json. and NACL_BASE64|

given that nacl module already does base64 by default: https://github.com/saltstack/salt/blob/e9bb2b6fdc1dab94397189e4a61ebbcf357b2b6f/salt/modules/nacl.py#L202 should it really be needed. I tried with couple multiline string and didn't see random behaviour.

> Support for encrypted tag: https://github.com/saltstack/salt/issues/41881

**Comment by steverweber** [comment]
> given that nacl module already does base64 by default

I might be misunderstanding how your render works... I thought it would be decrypting the pillar data so the minion has the unencrypted data to work with.

im thinking: line 220 not line 202 you are using the decrypt function.
https://github.com/saltstack/salt/blob/e9bb2b6fdc1dab94397189e4a61ebbcf357b2b6f/salt/modules/nacl.py#L220

or in the current PR: function `def dec_pub(data, **kwargs):` returns data that is decoded base64 `return b.decrypt(base64.b64decode(data))`

**Comment by steverweber** [comment]
ah i think I see where the confusions is coming from.

`NACL_JSON| to encode the string/binary as json. and NACL_BASE64| for base64`

this is not the input format but how to format the data on the output.

so something like.,
```
if isinstance(obj, six.string_types):
  if re.search(NACL_BASE64, obj) is not None:
    return base64.b64encode(__salt__['nacl.dec_pub'](re.search(NACL_BASE64, obj).group(1), **kwargs))
  if re.search(NACL_JSON, obj) is not None:
    return json.encode(__salt__['nacl.dec_pub'](re.search(NACL_JSON, obj).group(1), **kwargs))
  if re.search(NACL, obj) is not None:
    return __salt__['nacl.dec_pub'](re.search(NACL, obj).group(1), **kwargs)
```

anyways i haven't took a good look over the code and not sure how the renders work.
i could have this wrong.

**Comment by steverweber** [comment]
err does `#!yaml|nacl` first convert the file to yaml then run the nacl render?
if that is the ordering the "NACL_JSON" idea is pointless. "NACL_BASE64" might still be kinda helpful for binary data.

**Comment by yagnik** [comment]
Yes, renderers work from left to right so first yaml then nacl.
In its current form, I only decrypt strings so the output object will be a string. I didn't actually test what happens if we give an encrypted object yet but I'll give it a whirl.

**Comment by epcim** [comment]
[**@steverweber**](https://github.com/steverweber) commented on [Jun 21, 2017, 6:15 PM GMT+2](https://github.com/saltstack/salt/pull/41868#issuecomment-310129914 "2017-06-21T16:15:26Z - Replied by Github Reply Comments"):
> I often play devil's advocate. i'm glad there is buyin for this renderer.
> 
> > I prefer NACLENC to signify that this is "nacl encrypted string"
> 
> perhaps `NACL` its shorter :)
> 
> > ansible vault
> 
> looks interesting
> 
> > multiline
> 
> perhaps have somthing like `NACL_JSON|` to encode the string/binary as json.  
> 
> and `NACL_BASE64|`

why not just `| nacal | json`

**Comment by steverweber** [comment]
> `why not just | nacal | json`

this could be a feature request outside this PR.

a jinja SerializerExtension for nacl
https://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.jinja.html#salt.utils.jinja.SerializerExtension.

**Review by cachedout — APPROVED** [review]

**Pull request merged**
