### PR TITLE
Clean up doc build warnings, add best practices for writing states

### PR DESCRIPTION
**Pull request by terminalmage**
This reduces the number of build warnings from 2986 to 1. We can't get rid of that last one because it is triggered due to our custom autofunction plugin (which overrides the default autofunction from Sphinx).

Additionally, this PR adds some best practices documentation for writing states.

### CODE REVIEW

**Comment by cachedout** [comment]
This is awesome!

Can you swing by and clean up a few lint errors, please?

**Review by gtmanfred — APPROVED** [review]

**Comment by terminalmage** [comment]
@cachedout lint is fixed

**Comment by cachedout** [comment]
Hmm. We went sideways on some tests here, too.

**Comment by terminalmage** [comment]
@cachedout mocking just needed to be updated. I couldn't reproduce the gitfs unit test failures, and they don't seem to be related.

**Comment by rallytime** [comment]
`2986 to 1` WOW!

**Review by rallytime — APPROVED** [review]
This is awesome. We should figure out how to monitor for these kinds of warnings/errors on the doc build test. (Right now all it does is check for whether or not the docs can build - very simple, nothing fancy.)

**Comment by rallytime** [comment]
@terminalmage One final lint error to fix, and then this will be good.

**Comment by terminalmage** [comment]
@rallytime should be fixed now.

**Pull request merged**
