### PR TITLE
add toml module

### LINKED ISSUE #14802: Write States in TOML
I have recently been introduced to TOML and it seems like a very simple, easy, and powerful data structure language. I think it would be nice if Salt allowed for writing States in TOML -- Just one more option.

https://github.com/toml-lang/toml

### PR DESCRIPTION
**Pull request by mchugh19**
### What does this PR do?
Leverages the existing toml serializer to add a toml renderer. Also updates the serializer from pytoml to the supported toml library.

### What issues does this PR fix or reference?
Updated library fixes: #56323
Fixes: #14802

### Previous Behavior
Serializer used old pytoml library and no toml renderer.

### New Behavior
Now you can write salt states in toml:
```
#!jinja|toml

{% set myvar = "sometext" %}

[["some id"."test.nop"]]
name = "{{ myvar }}"
[["some id"."test.nop"]]
txt = "hello"
[["some id"."test.nop"]]
wow = "thing"
```

### Docs & changelog written?
Yes & No 
- [x] Docs
- [ ] Changelog

### Tests written?
Yes

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by mchugh19** [comment]
Looks like this may require adding the toml dependency. What's the appropriate way of marking that in the test suite?

**Comment by mchugh19** [comment]
re-run pr-ubuntu1804-py3

**Comment by mchugh19** [comment]
re-run pr-ubuntu1804-py3

**Comment by mchugh19** [comment]
Almost all working. Ubuntu seems pretty stuck with 
```
An un-handled exception was caught by salt's testing global exception handler:
07:11:39         RuntimeError: Failed to load filename map: while constructing a mapping
07:11:39           in "/tmp/kitchen/testing/tests/filename_map.yml", line 1, column 1
07:11:39         found conflicting ID 'salt/utils/vt.py'
```

**Review by dwoz — APPROVED** [review]

**Pull request merged**
