### PR TITLE
Add optional sleep parameter to status func

### PR DESCRIPTION
**Pull request by carsonoid**
Slow master_job_cache modules can cause the runner to improperly report
minions as down when they return too quickly. This commit does not
fix the race condition but does give a way to avoid it

Signed-off-by: Carson Anderson <ca@carsonoid.net>

### What does this PR do?

Adds an optional sleep time to the manage runner.

### What issues does this PR fix or reference?

Issue #42858

### Previous Behavior

Always used test.ping as minion health check.

### New Behavior

Uses test.sleep 0 as minion health check unless the sleep_time option is given.

There is no noticeable difference for any user that doesn't explicitly pass the sleep_time option.

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by carsonoid** [comment]
A better fix for this would probably be to use run_job_async for testing, So that there is no race condition at all. However, I couldn't find documentation on how to use that feature of the client.

**Comment by cachedout** [comment]
I am really not a very big fan of moving away from `test.ping` here. I would prefer that we address the fundamental issue in the runner client itself.

**Comment by carsonoid** [comment]
Honestly, I don't think it's the best way to solve it either. It's what I'm doing now for my own salt installations but only because I'm not sure how to properly solve the actual issue. #42858 hasn't had any work done yet so I had to do something in the meantime.

**Comment by thatch45** [comment]
yes, I agree with @cachedout , but we should find a better solution beyond turning this one down

**Comment by cachedout** [comment]
It appears that the decision here is not to accept this, I'm afraid. I'm going to go ahead and close this and we'll need to find a new approach. Sorry we can't get this one in, @carsonoid

**Pull request closed without merging**
