### PR TITLE
file.get_selinux_context: fix directory path behaviour

### PR DESCRIPTION
**Pull request by alexminder**
### What does this PR do?

Fix directory path behaviour for module `file.get_selinux_context`

### What issues does this PR fix or reference?
issue #55152

### CODE REVIEW

**Comment by waynew** [comment]
@alexminder Thanks for the PR!

Looks like there aren't any tests written here. Could you add tests to verify that this is working correctly?

**Comment by alexminder** [comment]
> @alexminder Thanks for the PR!
> 
> Looks like there aren't any tests written here. Could you add tests to verify that this is working correctly?

There are no new functionality in this PR. I don't know what tests do you want.

**Comment by waynew** [comment]
In the case of this change the minimum is to verify that `cmd.run` is called with the correct arguments.

Yes, it's a minimal test, but it still protects against regressions, and is worth writing.

**Comment by waynew** [comment]
It looks like this was also fixed in a different way in https://github.com/saltstack/salt/pull/56558/files which also had tests, so I'm going to go ahead and close this PR

**Pull request closed without merging**
