### PR TITLE
Refactor virt.migrate

### PR DESCRIPTION
**Pull request by rst0git**
This PR is rebased on https://github.com/saltstack/salt/pull/57736, which provides  integration tests for live migration. 

### What does this PR do?
This PR modifies the existing `virt.migrate` functionality to use the Python bindings of libvirt instead of the `virsh` command-line tool. This approach allows to make of the libvirt migration options available to users via a generic interface that doesn't require an increased number functions. Although backwards comparability is preserved, the `ssh` parameter of `virt.migrate`, `virt.migrate_non_shared` and `virt.migrate_non_shared_inc` have been marked as deprecated.

### Previous Behavior
```bash
salt src virt.migrate guest dst True
salt src virt.migrate_non_shared guest dst True
salt src virt.migrate_non_shared_inc guest-vm dst True
```

### New Behavior

```bash
salt src virt.migrate guest dst True
salt src virt.migrate_non_shared guest dst True
salt src virt.migrate_non_shared_inc guest-vm dst True

salt src virt.migrate guest qemu+ssh://dst/system
salt src virt.migrate guest qemu+tcp://dst/system
salt src virt.migrate guest qemu+tls://dst/system
salt src virt.migrate guest qemu+tls://dst/system copy_storage=all
salt src virt.migrate guest qemu+tls://dst/system copy_storage=incremental
```

### Merge requirements satisfied?
- [x] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### CODE REVIEW

**Comment by rst0git** [comment]
cc: @cbosdo

**Comment by cmcmarrow** [comment]
@rst0git thanks for the PR and tests! Once I look over the PR and give it the green light this should be merge ready and will probably make it into Magnesium.

**Review by cmcmarrow — DISMISSED** [review]

**Comment by rst0git** [comment]
@cmcmarrow Thank you for the review! I rebased the PR on master and added two commits with changelog information.

**Review by cmcmarrow — DISMISSED** [review]

**Comment by s0undt3ch** [comment]
Please do not merge this PR, it's blocked on external changes happening first.
Please read https://github.com/saltstack/salt/pull/57897#issuecomment-663855892 for context.

I will reply once the issues have been resolved to unblock this PR.

**Review by s0undt3ch — CHANGES_REQUESTED** [review]
Forgot to revert the fixtures. Could you please remove them?

**Review by s0undt3ch — CHANGES_REQUESTED** [review]
Sorry, left some more debug code around....

**Review by s0undt3ch — DISMISSED** [review]

**Review by dwoz — APPROVED** [review]

**Pull request merged**
