### PR TITLE
Decommission DigitalOcean APIv1 and have users use the new DigitalOcean APIv2

### PR DESCRIPTION
**Pull request by dmyerscough**
DigitalOcean APIv2 is now officially out of beta and they are encouragng users to start using this API as they will decommission version one of the API

### CODE REVIEW

**Comment by rallytime** [comment]
Do we know how long the original Digital Ocean API will be available/in use? I feel like this kind of change should be on a deprecation path with warnings to give people a chance to update their configs before switching this over. That is, unless that isn't possible if APIv1 is going to be gone before we can get those warnings in.

@techhat Thoughts?

**Comment by dmyerscough** [comment]
Sorry @rallytime for a slow response. The DigitalOcean APIv2 announcement can be found here:-

https://www.digitalocean.com/company/blog/apiv2-officially-leaves-beta/

I thought it would be good to remove it from the latest release and maybe backport a deprecation message?

**Comment by techhat** [comment]
Hey @dmyerscough. It doesn't seem right to backport a deprecation message. I would rather mark it as deprecated in develop, and then remove it after that... unless Digital Ocean is scheduled to remove it themselves sooner.

**Comment by jfindlay** [comment]
The announcement doesn't mention removing v1 of the API.  What is the status on this pull request, can it be merged?  @techhat?

**Comment by jfindlay** [comment]
We can update the code in the release branches as necessary if/when DO deprecates their API v1, but I don't see any reason to prevent us from supporting v2 in develop.

**Comment by techhat** [comment]
If v1 isn't being removed, then I would rather we not merge this.

**Comment by jfindlay** [comment]
What about a revised pull request that preserves the v1 API support while adding v2 support in parallel?

**Comment by techhat** [comment]
v2 is already supported in develop.

**Comment by dmyerscough** [comment]
I thought it would be good to move users over to APIv2 since DigitalOcean are providing it :)

**Comment by techhat** [comment]
Your efforts are appreciated @dmyerscough!

**Comment by rallytime** [comment]
@dmyerscough and @techhat: After doing some research, the Digital Ocean v1 API is officially deprecated and will be removed Nov 1, 2015, which is pretty soon after Salt Beryllium is scheduled to be released. After speaking with @cro, we've decided to put some deprecation warnings into 2015.5 branch to warn people to migrate their configs. 

I think it's safe to say that this deprecation can move forward as @dmyerscough planned. However, in the interim of this PR, I've already changed the tests around to only work with the "v2" driver, so we won't be able to just open this up again. @dmyerscough If it's ok with you, I am just going to move forward with the deprecation plan, even though much of this work was done by you already here. I'm adding the "deprecation warning" to 2015.5 right now.

**Comment by dmyerscough** [comment]
@rallytime awesome :+1:

**Comment by techhat** [comment]
Sounds like a plan.

**Pull request closed without merging**
