### PR TITLE
hard-code ami ids

### PR DESCRIPTION
**Pull request by bryceml**
### What does this PR do?
This changes to hard-coded amis, this reduces the complexity of introducing new batches of golden images.  It also makes it easier for cve releases to use the proper amis they used when the branch was active.

### CODE REVIEW

**Review by krionbsd — DISMISSED** [review]

**Review by s0undt3ch — DISMISSED** [review]

**Review by Ch3LL — DISMISSED** [review]

**Review by s0undt3ch — APPROVED** [review]

**Review by Ch3LL — APPROVED** [review]
just a thought, but is there a way to verify that these are indeed the OSs we intend on testing. I could see a mistake being made in the future where someone updates the ami but its for the wrong OS and we are not aware.

**Comment by bryceml** [comment]
> just a thought, but is there a way to verify that these are indeed the OSs we intend on testing. I could see a mistake being made in the future where someone updates the ami but its for the wrong OS and we are not aware.

it wouldn't be hard to write a script that for the ami in each file, checks the ami name of each of them using the aws cli locally before committing.


```bash
IFS=$'\n'
for i in `grep -r ami-`; do echo $i; aws ec2 describe-images --image-id $(echo $i|cut -d\' -f2) --query 'Images[].ImageLocation' --output text;  done
```

**Comment by bryceml** [comment]
Megan and I talked and we should add a check, probably part of init_environment https://gitlab.com/saltstack/open/cicd/kitchen-conf/-/blob/master/nox-platforms.yml#L69

or sometime close to the kitchen converge that makes sure we're running the right os.

**Review by krionbsd — APPROVED** [review]

**Comment by s0undt3ch** [comment]
We should a really use a pre-commit hook, even if we only run it on PRs?

**Comment by bryceml** [comment]
yeah, that could work well once we move to the new images that are named correctly, then we could problematically make sure the names match up.

The names like 540082622920/saltstack/ci/ubuntu/xenial.1604/master/1573754156
would be annoying to work around.  

After the next batch of golden images are ready to go, we should talk about adding a pre-commit job.

**Pull request merged**
