### PR TITLE
Fix saltclass

### PR DESCRIPTION
**Pull request by a-a-abramov**
### What does this PR do?
Fixes several saltclass pillar expansion issues.
Note that @olivier-mauras 's commit is essential and I had to cherry pick it into my branch from develop. Also it's worth noting that I had to amend half of @awerner 's commit since it introduced #49175.
And since I didn't have much time code quality is not very high to say the least. Module needs to be heavily refactored.

### What issues does this PR fix or reference?
#50262, #49175, #48170 and possibly others

### Previous Behavior
Check issues from previous section for the examples of malfunctions.  

### New Behavior
Everything works as expected.

### Tests written?
No

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by rbthomp** [comment]
@a-a-abramov 

Can you also remove   

```dict_merge(salt_data['__pillar__'], node_dict[minion_id].get('pillars', {}))```

This breaks, pillars added in node files. It also screws with salts ability to merge and order multiple external pillar sources. There are reason we return the pillars, and not dynamically modify them in place. 

If we need the ability to reference pillars from saltclass in saltclass using jinja there is probably a better way, then modify existing pillars.

**Comment by a-a-abramov** [comment]
@rbthomp 

Could you provide a little more detail on this (preferably with an example)? I don't see how this line screws salt's ability to merge and order external sources.

A few days ago I was thinking exactly about referencing saltclass pillars inside saltclass jinja. I believe we definitely should implement this. Absence of this feature greatly reduces saltclass'es flexibility. Say, for example, we have a state for each version of an application - sls/X/vers8, sls/X/vers11, etc. They provide common functions but are deployed differently and can't simply be parametrized with pillar (X:version) without severe refactoring of states. Now imagine if we also had a dependent application Y. X and Y are deployed onto two hosts - one with X/vers8, another - with X/vers11. If we could simply template states by host pillars with jinja this would be simple. We can do this with simple tops, but not this saltclass. 
So I was thinking that @awerner 's idea was actually very good, but in order for it to work traversing algorithm needs to be changed. Good news - I think I solved this problem, bad news - it would take some time to actually code, debug and test new implementation. I'll let y'all know if I manage to do this.

**Comment by rbthomp** [comment]
@a-a-abramov 

The issue I've ran into is any pillar declared in the node file overwrite existing keys instead of merging which is what we expect, except for lists when "^" is used. I've also encountered #48895. I don't have a complete understanding of what creates this condition, but when  ``` dict_merge(salt_data['__pillar__'], node_dict[minion_id].get('pillars', {}))``` is remove merging works as expected. 

I generally try and keep my logic in the states and not in pillars. I'm able to avoid this by using classes, with a couple of exceptions, like the one you described of using an existing state you don't want to modify. 

### Steps to Reproduce Issue
Pillars from class:
```
pillars:
    test:
      - classdata
```

PIllars from node:
```
pillars:
     test:
        - nodedata
```

Will result in:
```
pillars:
    test:
        - nodedata
```

expected result:
```
pillars:
    test:
        - classdata
        - nodedata

```

**Comment by a-a-abramov** [comment]
@rbthomp 
Yeah, you're right, I see it now. Once I have time I'll fix this and probably refactor the whole `utils/saltclass.py` (if someone except us is interested, really).

**Comment by a-a-abramov** [comment]
Changes from this PR are included in #52407

**Pull request closed without merging**
