### PR TITLE
[2018.8] salt-ssh jinja filters tests

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Adding a new integration test and corresponding state files to test availability of jinja filters when using salt-ssh.

### What issues does this PR fix or reference?
#46668 
#46834 

### Tests written?
Yes

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by terminalmage — CHANGES_REQUESTED** [review]
As noted in https://github.com/saltstack/salt/issues/46834, this doesn't seem to appear to be confined to salt-ssh.

Given that information, we should be running these same tests in the integration suite as well. This can easily be done by moving the test class from `tests/integration/ssh/test_jinja_filters.py` to `tests/support/jinja_filters.py`. For example:

```python
class JinjaFiltersTest(object):
    def test_data_compare_dicts(self):
        .....
        .....
```

You can then do this in `tests/integration/ssh/test_jinja_filters.py`:

```python
from tests.support.jinja_filters import JinjaFiltersTest

class SSHJinjaFiltersTest(SSHCase, JinjaFiltersTest):
    pass
```

You could then do something similar wherever you decide to add the tests to the main integration suite (`tests/integration/modules/test_state.py`?). This method would allow you to re-use the tests you wrote and have them run in salt-ssh as well as "normal" salt.

One other note: with `unicode_literals` imported, the `u` prefixes on the string literals are redundant.

**Review by terminalmage — APPROVED** [review]

**Comment by rallytime** [comment]
re-run all

**Comment by rallytime** [comment]
@garethgreenaway There's a lint error here: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/20755/violations/file/tests/support/jinja_filters.py/

I haven't seen that one before!

**Comment by garethgreenaway** [comment]
Failing tests. Investigating.

**Comment by cachedout** [comment]
@garethgreenaway How are we coming along on this one?

**Comment by garethgreenaway** [comment]
@cachedout need to circle back and look at the failing Py3 tests.

**Pull request merged**
