### PR TITLE
Update Windows amis

### PR DESCRIPTION
**Pull request by xeacott**
### What does this PR do?
Use the updated AMIs that includes this change: https://github.com/saltstack/salt-jenkins/pull/1713

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/pull/60399

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by bryceml** [comment]
re-run full all

**Review by garethgreenaway — DISMISSED** [review]

**Review by s0undt3ch — DISMISSED** [review]

**Review by Ch3LL — APPROVED** [review]

**Review by Ch3LL — CHANGES_REQUESTED** [review]
Looks like the ami's are not pulling from this file. When I check the windows test runs its using the ami's ami-015e1fedb71c9afbf and ami-0594ccae396fdcb60 from the files `cicd/jenkins/pr-windows-*`

**Comment by bryceml** [comment]
it looks like some PR got merged that re-added ami_image_id to cicd/jenkins/pr-windows*

we should delete those lines from those 2 files as they are given higher priority than cicd/amis.yml

**Review by bryceml — APPROVED** [review]

**Comment by bryceml** [comment]
re-run full all

**Review by twangboy — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Review by s0undt3ch — APPROVED** [review]

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
