### PR TITLE
Document controlled failure in state files

### PR DESCRIPTION
**Pull request by cebe**
### What does this PR do?

Added documentations for the solution pointed out by @bwesemann-cxp here https://github.com/saltstack/salt/issues/10723#issuecomment-449181053

### What issues does this PR fix or reference?

https://github.com/saltstack/salt/issues/10723

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by Ch3LL — CHANGES_REQUESTED** [review]
thanks for this doc addition :) looks like there is a doc failure that needs to be cleaned up

**Comment by cebe** [comment]
anything to do or change from my side?

**Comment by Ch3LL** [comment]
yeah if you could clean up the doc build failure. since you are using jinja in your code block you need to change the code block from yaml to jinja. That should clean up that error. If you want to test your change before pushing you can try to build the docs locally using these instructions: https://docs.saltstack.com/en/latest/topics/development/conventions/documentation.html#docs-building

**Comment by cebe** [comment]
@Ch3LL thanks for the hint, changed the code block type to `jinja` and rebased on `develop`, ready to merge from my side.

**Pull request merged**
