### PR TITLE
Added some unit tests for GCE and Dimension Data modules

### PR DESCRIPTION
**Pull request by tonybaloney**
### Improve test coverage of the GCE and Dimension Data modules

CC @erjohnso @rallytime

### CODE REVIEW

**Comment by cachedout** [comment]
@tonybaloney Would you mind cleaning up the line formatting? http://166.78.178.63:8080/job/PR/job/salt-pr-lint-n/1149/violations/file/tests/unit/cloud/clouds/gce_test.py/

**Comment by tonybaloney** [comment]
@cachedout what is the project preference? CRLF or LF consistently?

**Comment by rallytime** [comment]
Thanks!

**Comment by erjohnso** [comment]
You are a fine citizen @tonybaloney, thanks for this!

**Pull request merged**
