### PR TITLE
use existing set() function (fixes #14888, get_or_set_hash corrupts grains)

### LINKED ISSUE #14888: grains.get_or_set_hash  broken for multiple entries under the same key
I haven't quite figured out the circumstances that make this break, but hopefully this will provide some insight. It seems to be related to calling `grains.get_or_set_hash('a:a')` and `grains.get_or_set_hash('a:b')` in the same run.

First example state file:

```
test:
  w.p:
    - test1: '{{ salt['grains.get_or_set_hash']('test:test1') }}'
```

produces the expected result from show_sls:

```
local:
    ----------
    test:
        ----------
        __env__:
            base
        __sls__:
            test1
        w:
            ----------
            - test1:
                y0m_e0f%
            - p
            ----------
            - order:
                10000
```

and /etc/salt/grains contains

```
test:
  test1: y0m_e0f%
```

Changing the state file to:

```
test:
  w.p:
    - test1: '{{ salt['grains.get_or_set_hash']('test:test1') }}'
    - test2: '{{ salt['grains.get_or_set_hash']('test:test2') }}'
```

and show_sls produces:

```
local:
    - Rendering SLS test1 failed, render error: while parsing a block mapping
    -   in "<unicode string>", line 4, column 7:
    -         - test2: '{'test2': 'd@nw6dd^'}'
```

/etc/salt/grains now contains only

```
test:
  test2: d@nw6dd^
```

Note that test:test1 is missing, despite being there in the previous run.

This is with the Ubuntu package of 2014.1.10 (2014.1.10+ds-1trusty1).

### PR DESCRIPTION
**Pull request by maznu**
### What does this PR do?
Fixes issue #14888, a six year old bug which is causing corruption of grains.

### What issues does this PR fix or reference?
Fixes: #14888

### Previous Behavior
Destruction of data

### New Behavior
Preserving existing grain data

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by Akm0d** [comment]
Thank you for the PR!  Once we have a testcase to prevent regression of this issue it will get merged in

**Comment by maznu** [comment]
Cool. I think you can use my last few posts in #14888 as the basis of a minimal test case, as that configuration of grains was pretty reliable at failing in exactly the same way.

**Comment by waynew** [comment]
@maznu Are you interested in writing tests for this? If so, the [Test Clinics on Twitch](https://www.twitch.tv/saltprojectoss/schedule) would probably help (though they're out until next Thursday, due to holidays)

If you're not interested in writing tests, please let us know so we can add the help-wanted label.

**Comment by maznu** [comment]
I don't have bandwidth for the next 4 months, unfortunately.

**Comment by waynew** [comment]
@maznu for now I went ahead and added the help-wanted label - if you manage to get back to this before then, awesome! If not, maybe someone else may pick it up :+1:

**Comment by Ch3LL** [comment]
This method is actually getting removed in the 3005 release as seen here: https://github.com/saltstack/salt/pull/61702 It was on a deprecation path before this. I will go ahead and close this PR since the code its touching is now removed.

**Comment by maznu** [comment]
Is it normal to deprecate something and remove it in the next release without any documentation to the fact?

https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.grains.html#salt.modules.grains.get_or_set_hash says nothing about this.

**Comment by Ch3LL** [comment]
Yes it is normal. The process to deprecate is documented here: https://docs.saltproject.io/en/latest/topics/development/deprecations.html

The user would see the warning while using the function.

**Pull request closed without merging**
