### PR TITLE
fix for #30651 grains.list_present and grains.list_absent

### LINKED ISSUE #30651: salt.states.grains.list_present should not show changes if none are made!
```
          ID: package:install:salt::completed
    Function: grains.list_present
        Name: packages:salt
      Result: True
     Comment: Append value 2016.1.2-dev to grain packages:salt
     Started: 23:21:55.939789
    Duration: 4.641 ms
     Changes:
              ----------
              new:
                  The val 2016.1.2-dev was already in the list packages:salt
```

Nothing was actually! ```changes``` should be empty, the ```comment``` should probably be what is in changes.new at the moment.

2016.1.2-dev was present in the list, so the state = OK, no changes made.

### PR DESCRIPTION
**Pull request by sjorge**
…orting the ":" separator

This fixes #30651

Sorry it took me so long to track this down and fix. It was a super easy one actually.

### CODE REVIEW

**Comment by sjorge** [comment]
Looks like only a unrelated tornado error in jenkins.

**Comment by sjorge** [comment]
@rallytime any idea if this will get merged before the weekend?

**Comment by sjorge** [comment]
@cachedout can you glance over this one too? I keep hitting this one because my local tests builds track develop + my changes.

**Comment by cachedout** [comment]
This one actually concerns me a little. It is probably safe but I would like to give it my full attention. I am currently traveling on business but I will get to it as soon as I can. It might not be today though. Apologies.

**Comment by sjorge** [comment]
No worries, given the amount of time I spend on figuring out exactly why it was failing (see issue) I can see why you might have some concerns.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
This looks good. Great job, @sjorge

**Comment by sjorge** [comment]
Time to do another build and update my 3 minions now :+1: (slowly expanding)

**Comment by sjorge** [comment]
@cachedout can this be backported to 2016.3 I am hitting it on that branch too.

**Comment by rallytime** [comment]
@sjorge Since the bug is present even on the 2015.8 branch, I've back-ported it to there. In the future, and in case you haven't seen [these docs](https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch), bugfixes should be submitted against the "earliest supported release branch" that they apply to and features should go against develop.

**Comment by sjorge** [comment]
@rallytime thanks, yeah mike explained it to me yesterday :) Will do my best to target the oldest supported release in the future. It could be tricky for testing as my environment is illumos/solaris anything <2016.3 is kind of 'eh' support wise.

**Pull request merged**
