### PR TITLE
add btrfs unit test case

### PR DESCRIPTION
**Pull request by jayeshka**
Hi @rallytime , Please review the btrfs_test case and let me know if you have any review comments.

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
@jayeshka It looks like you have a couple of failing tests here. Can you clean those up? 

Otherwise, this looks good!

**Comment by jayeshka** [comment]
Hi, @rallytime failure for "jenkins/salt-pr-lint-n" does not show any error in btrfs_test script.
And Failure for  "jenkins/salt-pr-rs-ubuntu14.04-n"  & "jenkins/salt-pr-rs-cent7-n" does not get open. Gives an Http error 404.

**Comment by rallytime** [comment]
@jayeshka Yes, the pylint failures are unrelated. I'll run the tests again so we can see the test data. Thanks!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
@jayeshka I triggered another test run, so those results should be viewable now. If not, here's a list of the failing tests:

CentOS 7:
- unit.modules.btrfs_test.BtrfsTestCase.test_convert
- unit.modules.btrfs_test.BtrfsTestCase.test_defragment

Ubuntu 14:
- unit.modules.btrfs_test.BtrfsTestCase.test_defragment

**Comment by jayeshka** [comment]
@rallytime I am not able to reproduce the above errors on my side.
I am using Ubuntu 14.04-64  bit machine.

**Comment by rallytime** [comment]
I just ran these tests locally and it looks like you're not mocking something out quite correctly. I am also running on Ubuntu 14.04 64-bit and here is the result I get locally from the test run:
```
   -> unit.modules.btrfs_test.BtrfsTestCase.test_defragment  ...................................................................
       Traceback (most recent call last):
         File "/usr/local/lib/python2.7/dist-packages/mock.py", line 1201, in patched
           return func(*args, **keywargs)
         File "/root/SaltStack/salt/tests/unit/modules/btrfs_test.py", line 85, in test_defragment
           self.assertListEqual(btrfs.defragment('/dev/sda1'), ret)
       AssertionError: Lists differ: [{'range': False, 'mount_point... != [{'range': '/dev/sda1', 'mount...

       First differing element 0:
       {'range': False, 'mount_point': False, 'log': False, 'passed': True}
       {'range': '/dev/sda1', 'mount_point': False, 'log': False, 'passed': True}

       - [{'log': False, 'mount_point': False, 'passed': True, 'range': False}]
       ?                                                                ^ ^^^

       + [{'log': False, 'mount_point': False, 'passed': True, 'range': '/dev/sda1'}]
       ?                                                                ^^^^^^^^ ^^
```
I'll spin up a new CentOS 7 box and get the stacktrace from those failures to post here as well.

**Comment by rallytime** [comment]
Ok, so the CentOS 7 VM is also seeing the same test failure as I posted above with the stacktrace on Ubuntu 14 (same stacktrace) and it is also failing this test as well, like so:
```
unit.modules.btrfs_test.BtrfsTestCase.test_convert  .................................................................................... Traceback (most recent call last):
         File "/usr/lib/python2.7/site-packages/mock.py", line 1201, in patched
           return func(*args, **keywargs)
         File "/testing/tests/unit/modules/btrfs_test.py", line 244, in test_convert
           self.assertEqual(btrfs.convert('/dev/sda1'), ret)
       AssertionError: {'after': {'ext4_image_info': 'None/ext2_saved/image: cannot open (No such file  [truncated]... != {'after': {'ext4_image': 'None/ext2_saved', 'type': 'ext4', 'mount_point': None, [truncated]...
       Diff is 725 characters long. Set self.maxDiff to None to see it.
```
So, I expect something isn't getting mocked out completely in both of these tests. Take a look and please let me know if you have any questions.

**Comment by jayeshka** [comment]
Hi, @rallytime the pylint failures are unrelated now.

**Comment by rallytime** [comment]
@jayeshka Thanks for taking another look here. Did you mean to close this pull request?

**Comment by jayeshka** [comment]
Sorry I accidently closed it. I didn't mean to close it.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Ok great! I'll run these tests again as the last run didn't make it all of the way through.

**Pull request closed without merging**
