### PR TITLE
When building Windows installer, setup.py install will not print each file

### PR DESCRIPTION
**Pull request by marbx**
### What does this PR do?

adds `--quiet` to `setup.py install` for the Windows installer build script.
### What issues does this PR fix or reference?

Issue https://github.com/saltstack/salt/issues/34495
Issue https://github.com/saltstack/salt/issues/34500
### Previous Behavior

setup.py install prints 2,500 file names to the console.
### New Behavior

setup.py install does not print 2,500 file names to the console.
### Tests written?

Yes

### CODE REVIEW

**Comment by rallytime** [comment]
This PR doesn't need to be back-ported as the change is already preset in the 2016.3 branch: https://github.com/saltstack/salt/blob/a7fb5aa09d5dd283b98822254f25d57fbbe3f3e8/pkg/windows/build.bat#L48

**Comment by markuskramerIgitt** [comment]
Thank you, @rallytime 
So much to learn about git...
When I ```git checkout v2016.3.2```, the PR is not (yet) present.
When I ```git checkout v2016.3``` the file is removed (???)

How do you lookup a file in the 2016.3 branch?

**Comment by rallytime** [comment]
Hi @markuskramerIgitt - You're correct in that the change represented in this pull request is not present in the `v2016.3.2` tag. That change must have come into the 2016.3 branch after we released. 

Note that there is a difference between `v2016.3` and the `2016.3` branch. `v2016.3` is the git tag of the moment that the 2016.3 branch was created from `develop` many months ago. `2016.3` (no `v` on the front) is the actively developed bug-fix branch that we'll be releasing 2016.3.3 (and all subsequent 2016.3.x releases) from. Does that help?

Note that when I checkout the 2016.3 _branch_, the file is there, with the `--quiet` change, as expected:
```
rally:salt pinyon$ git checkout 2016.3
Switched to branch '2016.3'
Your branch is up-to-date with 'upstream/2016.3'.
rally:salt pinyon$ ls pkg/windows/build
build.bat      build_env.ps1  build_pkg.bat  buildenv/
```

**Comment by markuskramerIgitt** [comment]
Hi @rallytime, thank you a lot for your explanation - I was totally unaware of the difference and I now fully understand.

**Comment by markuskramerIgitt** [comment]
@rallytime, could I ask for yet another help?

I can ```git checkout v2015.2.0-737-gd8f1cff``` and get a "minor version" (I am not sure how to call 737-gd8f1cff)

Where do I find the "minor versions" of 2016.3.2?
The last "minor version" would be enough.

I am working on the Windows installer https://github.com/saltstack/salt/issues/19137
and the building of the installer (currently) requires the checkout to an explicit "minor version". 

Thank you

**Comment by rallytime** [comment]
@markuskramerIgitt Hm. What do you mean by "minor version"? The `x` in `2016.3.x` is the minor point release version on the `2016.3` branch. The numbering in the version numbers work like this: https://docs.saltstack.com/en/latest/topics/releases/version_numbers.html

When you are looking at the version number from doing something like a `salt --versions-report` and you have something like `2016.3.2-99-gf2eb3dc`, the `2016.3.2` is the release number, the next portion, `-99-` in this case, is the number of commits on the branch since the version was tagged. (So in this case, I am on the 2016.3 branch, and there have been 99 commits on the branch since the last tag. If I check out develop, that number is much bigger.) And the final portion is the git sha. The `g` at the front stands for `git` and then the `f2eb3dc` is the sha of the commit at the HEAD of the branch at this point in time:
```
# git log -1
commit f2eb3dc10520f04144e67fc5c197e09e4775ab1d
Merge: 5cbd5eb bbf7ce1
Author: Mike Place <mp@saltstack.com>
Date:   Thu Aug 18 16:16:03 2016 +0900

    Merge pull request #35489 from rallytime/bp-35463

    Back-port #35463 to 2016.3
```
See how the first several characters of the `commit` in the log report matches the `Salt: 2016.3.2-99-gf2eb3dc`?

I am actually not that familiar with the Windows installer, but I think this explanation might help you understand what you need a little bit better. Please let me know if you have any questions. (Note that the git tags do start with a `v`, but our versions-report strips that off for the CLI output. I _think_ you should be able to but the `v` back on there for the Windows installer.)

**Comment by markuskramerIgitt** [comment]
Hello @rallytime,
thank your for guiding me through.
Is commit 99 counted from ```v2016.6``` or ```v2016.6.3```?

I tried to assemble what you said:
```
Things you can use for `git checkout`
+---------------+-------------------------------------------------------------------------------------------------+
|    Argument   |                                           Explanation                                           |
+===============+=================================================================================================+
| v2016.3       | Tag of the moment that the 2016.3 branch was created from develop.                              |
+---------------+-------------------------------------------------------------------------------------------------+
| v2016.3.2     | Tag of the release.                                                                             |
+---------------+-------------------------------------------------------------------------------------------------+
| 2016.3        | Actively developed bug-fix branch that we'll be releasing all 2016.3.x releases from.           |
+---------------+-------------------------------------------------------------------------------------------------+


Understanding 2016.3.2-99-gf2eb3dc
+---------------+-------------------------------------------------------------------------------------------------+
|     Part      |                                           Explanation                                           |
+===============+=================================================================================================+
|2016.3.2       | Release.                                                                                        |
+---------------+-------------------------------------------------------------------------------------------------+
|99             | Commits on the 2016.3 branch since the (...?) version was tagged.                               |
+---------------+-------------------------------------------------------------------------------------------------+
|gf2eb3dc       | Literal 'g' + git SHA of the commit at the HEAD of the branch.                                  |
+---------------+-------------------------------------------------------------------------------------------------+

```

I'd like to add this to https://docs.saltstack.com/en/latest/topics/releases/version_numbers.html
What do you think?

**Comment by rallytime** [comment]
@markuskramerIgitt Yes, I think that would be helpful to add to the docs!

> Is commit 99 counted from v2016.6 or v2016.6.3?

Technically it is counted from the last tag on your system. So if you have the v2016.3.2 tag pulled down on your system, like I do, then it is 99 commits since v2016.3.2. This number is not always exact, but is mostly just helpful for determining a ball-park of your salt-version. For example, the develop branch doesn't have any tags on it, since it is our rolling feature release branch. So if you're running off of develop, then that number still looks for the most recent tag on your system (v2016.3.2 in this case), but will have *many* more commits than 99 since that tag was made. When I check out the develop branch on my system, the versions report for my current HEAD of the branch looks like this `Salt: 2016.3.0-1184-g3863045`.

**Comment by rallytime** [comment]
Hmm, and maybe develop goes from the 2016.3.0 tag instead of 2016.3.2? I am not entirely sure of the exact details there. I'd need to look at the code. But bascially that number is useful for us being able to say "Oh! You're on develop!" or "Oh, you're on 2016.3!".

**Comment by markuskramerIgitt** [comment]
Hi @rallytime,
thank you for you continuing support.


What I would add to salt/doc/topics/releases/version_numbers.rst, could you please have a look?


```
Arguments for `git checkout`
+------------+---------------------------------------------------------------------+
|  Argument  |                                           Comment                   |
+============+=====================================================================+
| v2016.11   | Tag of the moment that the 2016.11 branch was created from develop  |
+------------+---------------------------------------------------------------------+
| 2016.11    | Actively developed bug-fix branch for all 2016.11.* releases        |
+------------+---------------------------------------------------------------------+
| v2016.11.1 | Tag of the moment that the 2016.11.1 branch was created             |
+------------+---------------------------------------------------------------------+
| develop    | The HEAD of Git                                                     |
+------------+---------------------------------------------------------------------+


Influence of `git checkout` on `git describe`
+------------+---------------------------------------------------------------------+
| checkout   | describe                   |               Comment                  |
+============+=====================================================================+
| v2016.11   | v2016.11                   | (tag is fixed point in time)           |
+------------+---------------------------------------------------------------------+
| 2016.11    | v2016.11.1-220-g9a1550d    | Commit of most recent tag in 2016.11   |
+------------+---------------------------------------------------------------------+
| v2016.11.1 | 2016.11.1                  | (tag is fixed point in time)           |
+------------+---------------------------------------------------------------------+
| develop    | v2016.11.1-1741-g10d5dec   | Commit of most recent tag in develop   |
+------------+---------------------------------------------------------------------+
  


Details of v2016.11.1-220-g9a1550d (from `git describe` after `git checkout 2016.11`)
+---------------+------------------------------------------------------------------+
|     Part      |                       Comment                                    |
+===============+==================================================================+
|v2016.11.1     | git describe finds the most recent tag on the 2016.11 branch     |
+---------------+------------------------------------------------------------------+
|220            | Commits on top of the (most recent) tag                          |
+---------------+------------------------------------------------------------------+
|gf2eb3dc       | 'g' + git SHA ("abbreviated name") of the most recent commit     |
+---------------+------------------------------------------------------------------+

```

Can one "pull down v2016.3.2" when it is no longer the most recent tag?
I can only pull down the most recent tag of 2016.3 (which is 2016.3.4).
I could use this for creating 'historic' installers, and would need the commit count and sha of the last commit.

What I tried:

```
$ git checkout v2016.3.2
Previous HEAD position was f44724c... Merge pull request #37726 from cloudflare/2016.11
HEAD is now at 721e6dc... Merge pull request #34988 from rallytime/release-notes-update

$ git describe
v2016.3.2

$ git pull
You are not currently on a branch.

```

**Comment by rallytime** [comment]
@markuskramerIgitt That looks good! Thank you for putting that together. I expect that this will be helpful for people. I have a couple of suggestions, as follows:

```
| develop    | The HEAD of Git                                                     |
```
`develop` is just another branch name, not necessarily the `HEAD of Git`. It's the branch that all feature additions should be added to for the next feature release. It might be useful to read [these docs](https://docs.saltstack.com/en/latest/topics/development/git/index.html#release-branching) and [these docs](https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch) for some more clarifications. A cross-reference link from your new addition to these other sections might be a good idea.

One thing to clarify here is the relationship of the `git describe` command to the `Salt Version:` section of the output from the `salt --versions` command  (or `salt-call --versions`, etc). You have some of the pieces there with the `Details of v2016.11.1-220-g9a1550d` listed, but it's not explicit that you're actually describing all of the pieces that salt uses to determine and report on the version of Salt that you're on.

The last comment I have is that it would be good to mention that all of these sections with the various git tags are _relative to your local git fetch_. The `salt --version` command (and hence git checkout) looks for the most recent recognized tag on the system, which may not necessarily be the most recent tag up on GitHub. 

> Can one "pull down v2016.3.2" when it is no longer the most recent tag?

Yes, you should have access to all of the tags available on your system. All of the tags that were available on the initial clone of the repository should be accessible initially. New tags will come down after doing a `git fetch <upstream-name>`. You can checkout a tag at anytime using `git checkout <tag-name>`. You can see which tags are available on your system with `git tag --list`.

However, note that when you've checked out a specific tag, there isn't anything to "pull down" into that tag. A tag is just a reference to a specific point in time. Pulling changes into this reference point doesn't apply. You'll need to either check out an existing branch to pull new changes into (such as 2016.11), or you can create a new branch off of the tag. 

Hopefully that explanation makes sense. Please let me know if you have any questions. I am happy to help. We look forward to seeing your pull request submission with your additions!

**Comment by markuskramerIgitt** [comment]
Hi @rallytime,
I just opened pull request https://github.com/saltstack/salt/pull/38849 for salt/doc/topics/releases/version_numbers.rst

You are right, the relationship between `git describe` and  `salt --version` needs to be clarified.
I noted it as issue https://github.com/markuskramerIgitt/salt-windows-msi/issues/49
Only after that, I can think about pulling down historic releases.

**Comment by markuskramerIgitt** [comment]
Hi @rallytime,
I am about to release the first Salt Minion msi-installer into our company.
One of the two remaining problems  is that I don't know how to download the sources for the 2016.11.3 release.

Could you please have a look at https://github.com/markuskramerIgitt/salt-windows-msi/issues/49 and comment? 

Thank you!
Markus

**Comment by rallytime** [comment]
@markuskramerIgitt Sure thing. I commented on your linked issue. :)

**Pull request merged**
