### PR TITLE
fix incorrect smartos grains

### PR DESCRIPTION
**Pull request by sjorge**
- fix OS grain to report SmartOS again (was apparently broken)
- only try and collect zone related SmartOS grains if we are in a zone on SmartOS
- expose mdata (metadata specific for SmartOS) as grains
- map special 'salt:role' metadata to role grain

``` json
...
  "customer_metadata": {
    "salt:roles": "salt-master",
    "user-script": "/srv/salt/bootstrap/zoneinit"
  },
...
```

```
[root@cronos ~]# mdata-list
user-script
salt:roles
```

```
[root@cronos ~]# mdata-get salt:roles
salt-master,test-server
```

`[root@cronos ~]# salt-call --local grains.get roles`

``` yaml
local:
    - salt-master
    - test-serverl
```

`[root@cronos ~]# salt-call --local grains.get mdata`

``` yaml
local:
    ----------
    user_script:
        /srv/salt/bootstrap/zoneinit
```

### CODE REVIEW

**Comment by sjorge** [comment]
Seems a commit is missing! Let me push it after dinner.

**Comment by cachedout** [comment]
@sjorge Sounds good. Please let me know when this is one all ready. Thanks!

**Comment by sjorge** [comment]
Will do, someone pointed out that it's 'roles' not 'role' and that it can be a list, so fixing that too... and testing again of course.

**Comment by sjorge** [comment]
Done

**Comment by sjorge** [comment]
The test failures don't seem to be related to this change.

**Comment by cachedout** [comment]
Cool! Thanks again, @sjorge

**Pull request merged**
