### PR TITLE
Various fixes for boto_route53 and boto_elb

### PR DESCRIPTION
**Pull request by ryan-lane**
- Fix for route53 entries with \* in their names
- Have boto_elb use boto_route53's state module directly
- Fix for boto_elb alarms

### CODE REVIEW

**Comment by rallytime** [comment]
Thanks @ryan-lane! Can you also take a look at the `unit.states.boto_elb_test.BotoElbTestCase.test_present` failure? I am not sure if it is a change in mocking or if there is a bug there or not, but that failure is relevant to your changes.

**Comment by ryan-lane** [comment]
The unit tests were kind of a mess for boto_elb, so I rewrote them in a way that should be easier to maintain and also more reliable.

**Comment by jfindlay** [comment]
Fixes #23034.

**Comment by rallytime** [comment]
Nice! Thanks @ryan-lane!

**Pull request merged**
