### PR TITLE
Added git_pillar branch to environment mapping

### PR DESCRIPTION
**Pull request by whiteinge**

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
@whiteinge looks like some legit failures

**Comment by whiteinge** [comment]
Go Go Jenkins!

**Comment by whiteinge** [comment]
Go Go Jenkins!

**Comment by whiteinge** [comment]
Go Go Jenkins?

**Comment by whiteinge** [comment]
Go Go Go Go Jenkins!!

**Comment by thatch45** [comment]
@whiteinge I think Jenkins is in a bad way right now.......
If you run them locally and they pass let me know and I will merge

**Comment by rallytime** [comment]
The clone was failing, but it's working now. I'm not sure about the state of the tests yet though. So...yeah. We're so close!!

**Comment by whiteinge** [comment]
Are you saying I shouldn't troll the Jenkins? :-)

All the `integration.modules.pillar.*` tests are passing locally.

**Comment by whiteinge** [comment]
Go Go Jenkins!

**Comment by whiteinge** [comment]
Test failure is unrelated. The test added in this pull req indeed passed.

**Comment by thatch45** [comment]
Thanks @whiteinge

**Pull request merged**
