### PR TITLE
Fix #62281

### LINKED ISSUE #62281: [BUG] module 'os' has no attribute 'getcwdu'
**Description**
Salt Package Manager (SPM) is using a deprecated Python method called `os.getcwdu()`, which used to exist in Python 2.x, but not anymore on Python 3.x. This causes the following exception when calling `spm create_repo .` on SPM version 3004:

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: module 'os' has no attribute 'getcwdu'
Traceback (most recent call last):
  File "/usr/bin/spm", line 11, in <module>
    salt_spm()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 533, in salt_spm
    spm.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/spm.py", line 38, in run
    client.run(self.args)
  File "/usr/lib/python3.6/site-packages/salt/spm/__init__.py", line 129, in run
    self._create_repo(args)
  File "/usr/lib/python3.6/site-packages/salt/spm/__init__.py", line 750, in _create_repo
    repo_path = os.getcwdu()
AttributeError: module 'os' has no attribute 'getcwdu'
Traceback (most recent call last):
  File "/usr/bin/spm", line 11, in <module>
    salt_spm()
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 533, in salt_spm
    spm.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/spm.py", line 38, in run
    client.run(self.args)
  File "/usr/lib/python3.6/site-packages/salt/spm/__init__.py", line 129, in run
    self._create_repo(args)
  File "/usr/lib/python3.6/site-packages/salt/spm/__init__.py", line 750, in _create_repo
    repo_path = os.getcwdu()
AttributeError: module 'os' has no attribute 'getcwdu'
```

**Setup**

Docker container. Image is build with the following Dockerfile:

```
FROM opensuse/leap

RUN zypper refresh && zypper install -y salt-master

ENTRYPOINT ["sleep","infinity"]
```
  
**Steps to Reproduce the behavior**
1. Install salt-master
2. Run `spm create_repo .` on any directory

**Expected behavior**
The repository is correctly initialized on the current working directory.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: 1.13.2
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3
 
System Versions:
          dist: opensuse-leap 15.4 
        locale: UTF-8
       machine: x86_64
       release: 5.13.0-51-generic
        system: Linux
       version: openSUSE Leap 15.4 
```
</details>

### PR DESCRIPTION
**Pull request by itspooya**
### What does this PR do?
added if-else block to check the python version and fill repo_path with correct data regarding the python major version

### What issues does this PR fix or reference?
Fixes: #62281

### CODE REVIEW

**Comment by itspooya** [comment]
Second commit's code has better performance than if-else's code block 
repo_path = os.getcwd()
if sys.version_info.major == 2:
  repo_path = os.getcwdu()

**Comment by whytewolf** [comment]
this is going to need a testcase and changelog.

**Comment by itspooya** [comment]
Thank you for your comment
I will add following changes(test case and changelog)

**Comment by itspooya** [comment]
@whytewolf 
Could you please take a look at this PR? I would be happy to make any changes needed to this PR since it's been open for a while

**Comment by whytewolf** [comment]
did you see the comment about python2 not being supported? I would be happier if we were not importing python2 code.

**Comment by itspooya** [comment]
@whytewolf 
> did you see the comment about python2 not being supported? I would be happier if we were not importing python2 code.

Sorry, I haven't seen that comment, I removed Python-2 code and sent another commit to remove it
Could you check it now?

**Review by whytewolf — DISMISSED** [review]

**Comment by whytewolf** [comment]
looks like there is a precommit issue. fix that and I'll approve again.

**Comment by itspooya** [comment]
@whytewolf 
Hi again
Sorry for taking your time too much, it's my first time contributing to a big opensource project
I think this time I got it right

**Comment by whytewolf** [comment]
looks like the precommit is still failing. 

you might need to install it locally and see if you can get it to pass. 

What I normally do is 

```
git add .
precommit
git add .
precommit
```

the second one should pass unless there is something that the precommit doesn't fix automatically.

**Comment by itspooya** [comment]
@whytewolf 
Thank you for guiding me
I got it right this time by setting up local environment
Please check this
Thanks

**Review by whytewolf — APPROVED** [review]

**Comment by whytewolf** [comment]
> @whytewolf Thank you for guiding me I got it right this time by setting up local environment Please check this Thanks

yeap. approved. pending tests now.

**Comment by itspooya** [comment]
@whytewolf 
That one test I think it needs to re run?

**Comment by itspooya** [comment]
@whytewolf 
Everything is done and checks passed

**Comment by itspooya** [comment]
@whytewolf 
Just wanted to check whether everything is okay

**Comment by whytewolf** [comment]
> @whytewolf Just wanted to check whether everything is okay

yeap things are looking good. I"ll get this in front of the team today to get merged.

**Pull request merged**
