### PR TITLE
Fix ldap token groups auth.

### LINKED ISSUE #42459: Broken ldap groups retrieval in salt.auth.ldap after upgrade to 2017.7
### Description of Issue/Question
LDAP eauth stopped working for salt-api after upgrade to 2017.7
pepper-0.5 is used as a client

### Setup
Ldap-related settings
```
auth.ldap.server: ldap.example.com
auth.ldap.port: 389
auth.ldap.tls: False
auth.ldap.no_verify: True
auth.ldap.anonymous: False
auth.ldap.binddn: 'cn=root,o=company'
auth.ldap.bindpw: 'root'
auth.ldap.basedn: 'ou=users,o=company'
auth.ldap.filter: '(uid={{ username }})'
auth.ldap.freeipa: True
auth.ldap.group_basedn: 'ou=groups,o=company'
auth.ldap.group_filter: '(&(memberUid={{ username }})(objectClass=posixGroup))'
auth.ldap.accountattributename: 'memberUid'

external_auth:
  ldap:
    'admins%':
      - '.*'
      - '@jobs'
      - '@wheel'
      - '@runners'
```

### Steps to Reproduce Issue
API calls return 401 and there these strings in logs
```
2017-07-21 18:22:31,228 [salt.loaded.int.auth.ldap][DEBUG   ][28333] Running LDAP user dn search with filter:(uid=admin1), dn:ou=users,o=company, scope:2
2017-07-21 18:22:31,229 [salt.loaded.int.auth.ldap][DEBUG   ][28333] Attempting LDAP bind with user dn: cn=admin1,ou=users,o=company
2017-07-21 18:22:31,232 [salt.loaded.int.auth.ldap][DEBUG   ][28333] Successfully authenticated user dn via LDAP: cn=admin1,ou=users,o=company
2017-07-21 18:22:31,232 [salt.loaded.int.auth.ldap][DEBUG   ][28333] LDAP authentication successful
2017-07-21 18:22:31,288 [salt.utils.lazy  ][DEBUG   ][28337] Could not LazyLoad ldap.acl: 'ldap.acl' is not available.
2017-07-21 18:22:31,289 [salt.auth        ][WARNING ][28337] Authorization failure occurred.
2017-07-21 18:22:31,289 [salt.master      ][WARNING ][28337] Authentication failure of type "token" occurred.
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 4.9.20-1.company.el7.centos.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

python-ldap package version is 2.4.15-2.el7.x86_64

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
### What does this PR do?
Implemented back the logic that retrieves the user's group list and places it into the token during making token procedure and correctly provide it to `get_auth_list` during authorization.
It was missed during auth redesign.
Also corrected groups retrieving in ldap module (for some cases).

### What issues does this PR fix or reference?
Fixes #42459

### Tests written?
No

### CODE REVIEW

**Comment by cachedout** [comment]
Original reporter of this issue is reviewing and testing this today.

**Comment by austinpapp** [comment]
@cachedout this looks much much better
```
return:
- eauth: ldap
  expire: 1504331112.674505
  perms:
  - .*
  - '@runner'
  - '@jobs'
  start: 1504287912.674504
  token: 61d68429790fd85575d2aad445dcfeeb09aa4c9e
  user: ****
```

**Review by cachedout — APPROVED** [review]

**Comment by austinpapp** [comment]
FYI - i did test this with an individual user and a group (%)

**Comment by cachedout** [comment]
@austinpapp Thank you very much for the quick turnaround as always.

@DmitryKuzmenko You continue to be amazing. :]

**Pull request merged**
