### PR TITLE
[WIP][2019.2] Pillar refresh fixes

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Updates `__pillar__` in addition to self.opts['pillar'] when a state run happens.

### What issues does this PR fix or reference?
#52354

### Previous Behavior
During a state run if a pillar error occurred it would be preserved in `__pillar__`, so on subsequent state runs during the error checking the run would be flagged as having an error even if the issue has been corrected.

### New Behavior
When self.opts['pillar'] is updated, update `__pillar__` as well.

### Tests written?
No

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by DmitryKuzmenko** [comment]
@garethgreenaway it's not finished yet. Am I right?

**Comment by garethgreenaway** [comment]
@dmitrykuzmenko just not sure if my approach is 100% correct.

**Comment by DmitryKuzmenko** [comment]
I don't see how it could help. Is the `salt.state.__pillar__` dunder used anywhere? I don't see local usages in that file.

**Comment by garethgreenaway** [comment]
@DmitryKuzmenko `__pillar__` is used in other places but wasn't being updated in this location when `salt.opts['pillar']` was being updated.

**Comment by DmitryKuzmenko** [comment]
@garethgreenaway ping! Does this PR make any sense now?

**Comment by sagetherage** [comment]
@garethgreenaway want to rebase this against `master` branch?

**Review by dmurphy18 — CHANGES_REQUESTED** [review]
No point in reviewing until the changes are against the master branch
Redo changes against the master branch

**Comment by Oloremo** [comment]
I wonder if this still needed

**Comment by Ch3LL** [comment]
@garethgreenaway is this still needed or can it be closed?

**Comment by garethgreenaway** [comment]
@Ch3LL Looks like another PR fixed the issue. Closing.

**Pull request closed without merging**
