### PR TITLE
Splat serializer default configs into the serializer kwargs

### LINKED ISSUE #33525: file.serialize no longer indents/pretty-prints in 2016.3
Upgrading to 2016.3, running `state.apply` showed that `file.serialize` states with `formatter: json` now produces a harder to read format with no whitespace.

Guessing this is the cause: 53dd9ae13822e181febfad66647cea9024096562 - https://github.com/saltstack/salt/pull/28906

### PR DESCRIPTION
**Pull request by cachedout**
Fixes #33525

### CODE REVIEW

**Comment by rallytime** [comment]
@cachedout Some related tests are failing here. Can you take a look when you get a moment?

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
I should have posted the links to the test before. It's two unit tests for the file state:

- https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/4662/testReport/unit.states.file_test/FileTestCase/test_serialize/
- https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/4662/testReport/unit.states.file_test/TestFileState/test_serialize/

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
I think some mocks might just need to be adjusted. Both of the test failures have the following stack trace:
```
Traceback (most recent call last):
  File "/testing/tests/unit/states/file_test.py", line 76, in test_serialize
    filestate.serialize('/tmp', dataset, formatter="python")
  File "/testing/salt/states/file.py", line 4616, in serialize
    contents = __serializers__[serializer_name](dataset, **default_serializer_opts[serializer_name])
KeyError: 'python.serialize'
```

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@rallytime This needs to make its way to Carbon, please.

**Pull request merged**
