### PR TITLE
Add scheduled actions (like scaleup/scaledown actions) to boto_asg

### PR DESCRIPTION
**Pull request by ryan-lane**
This adds the ability to define scheduled actions to boto_asg, like scaleup/scaledown events. It also adds some additional bug fixes.

### CODE REVIEW

**Comment by ryan-lane** [comment]
Missing the execution module changes....

**Comment by ryan-lane** [comment]
OK. This is good to go.

**Comment by cachedout** [comment]
@ryan-lane Looks like a tiny lint issue and a failing test. Could you take a peek please? Thanks!

**Comment by ryan-lane** [comment]
I don't understand the test failure. config.option definitely exists...

**Comment by basepi** [comment]
It's likely because it's a unit test. For unit tests, you have to mock the contents of the `__salt__` dictionary, we don't actually load the states as normal.

**Comment by rallytime** [comment]
Awesome!

**Pull request merged**
