### PR TITLE
[develop] changes to nacl module & runner

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Consolidating shared code from modules/nacl.py & runners/nacl.py to utils/nacl.py.  Adding some new tests to test sealedbox & secretbox encryption & decryption.

### What issues does this PR fix or reference?
N/A

### Tests written?
Yes

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by cachedout** [comment]
@garethgreenaway Looks like tests went sideways here.

**Comment by garethgreenaway** [comment]
@cachedout not sure if these failures are related to my changes.

**Comment by cachedout** [comment]
@garethgreenaway We have a merge conflict here that needs to be resolved, please.

**Review by rallytime — APPROVED** [review]
This is really nice and I love it when we can clean things up like this. 👍

**Pull request merged**
