### PR TITLE
Fixes to versions function in manage runner

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Updating the versions function inside the manage runner to account for when a minion is offline and we are unable to determine it's version.

### What issues does this PR fix or reference?
#42374

### Previous Behavior
If a minion was offline, this would result in a traceback.

### New Behavior
Minions that are offline are now listed as being offline and their versions are marked as False.

### Tests written?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by rallytime** [comment]
@garethgreenaway Should this be against 2017.7?

**Comment by garethgreenaway** [comment]
@rallytime Yup!  I'll resubmit it.

**Comment by tyhunt99** [comment]
This fixes the issue and the output is clear. Thanks!

**Comment by garethgreenaway** [comment]
Resubmitting against 2017.7.0

**Comment by rallytime** [comment]
Replaced by #42436

**Pull request closed without merging**
