### PR TITLE
Bugfix: Exit on configuration read (backport)

### PR DESCRIPTION
**Pull request by isbm**
Backport of https://github.com/saltstack/salt/pull/34604

### CODE REVIEW

**Comment by rallytime** [comment]
@isbm Thanks for updating the backport PRs with your new commits from the original in develop. It looks like there is still a related unit test failure here, however.

https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/3439/testReport/junit/unit.config_test/ConfigTestCase/test_issue_6714_parsing_errors_logged/

Can you take another look?

**Comment by isbm** [comment]
@cachedout is this one you forgot or?

**Comment by isbm** [comment]
@cachedout :pray:

**Comment by thatch45** [comment]
Thanks for getting this test fixed up!

**Pull request merged**
