### PR TITLE
import and namespace _mkstemp_copy

### LINKED ISSUE #22779: file.replace breaks on windows
```
c:\salt>salt-call --versions-report
           Salt: 2015.2.0rc2
         Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.5
   msgpack-pure: Not Installed
       pycrypto: 2.6
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```
c:\salt>salt-call --local file.replace "C:/Cloud Backend/WebRoot/
Cloud.Backend/Web.Config" pattern='(.*)@SERVICEID@(.*)' repl='\1 TEST123 \2' 
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler
:
NameError: global name '_mkstemp_copy' is not defined
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "c:\salt\bin\lib\site-packages\salt\scripts.py", line 225, in salt_call
    client.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\call.py", line 69, in run
    caller.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 236, in run
    ret = self.call()
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\file.py", line 1315, in repla
ce
    temp_file = _mkstemp_copy(path=path, preserve_inode=False)
NameError: global name '_mkstemp_copy' is not defined
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "c:\salt\bin\lib\site-packages\salt\scripts.py", line 225, in salt_call
    client.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\call.py", line 69, in run
    caller.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 236, in run
    ret = self.call()
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 138, in call
    ret['return'] = func(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\file.py", line 1315, in repla
ce
    temp_file = _mkstemp_copy(path=path, preserve_inode=False)
NameError: global name '_mkstemp_copy' is not defined
```

### PR DESCRIPTION
**Pull request by UtahDave**
Fixes #22779

### CODE REVIEW

**Comment by lorengordon** [comment]
Ahh... *that's* what was happening. I saw the issue but had no idea how it could be that the function was not defined. Is there a better way to reference local functions within a module to avoid this? Or will every time we factor out some functionality, where there is a windows-specific module, will we have to remember to also import and namespace the function in the windows module?

**Comment by UtahDave** [comment]
@lorengordon as far as I know we'll have to import and namespace each function we need. I'd like to simplify this, but better Pythonistas than me have told me this is the only way.

If someone comes up with a better way to make this work I'm definitely open to improvements.

**Comment by lorengordon** [comment]
@UtahDave, if there isn't a better approach, perhaps add a note somewhere in the [Developing Salt](http://docs.saltstack.com/en/latest/topics/development/) docs discussing gotchas when contributing to modules that have Windows-specific implementations? Including an example of the NameError exception (so searches find it), and the fix (such as your commit) showing how to import and namespace any new functions...

**Comment by jfindlay** [comment]
@lorengordon, will you create a new issue for that?  Thanks.

**Comment by lorengordon** [comment]
Done, https://github.com/saltstack/salt/issues/23226.

**Pull request merged**
