### PR TITLE
new feature: add saltenv directory to file_roots, pillar_roots and ext_pillar.stack for dynamic environments 

### LINKED ISSUE #55747: new feature: add saltenv directory to file_roots and pillar_roots for dynamic environments
#50784 from @sathieu as requested by @BenjaminSchiborr in #48132 allows for one (and only one I think?) default catch-all saltenv` __env__` in file_roots definitions that maps all saltenvs to a single directory.

If the requestor's saltenv can be prepended to a requested file-path for a particular file_root entry this would allow for a roots variant of the gitfs, svnfs and hgfs behavior where branches and tags are translated into salt environments; salt environments are translated into directories. This allows for adding saltenvs dynamically without restarting the salt-master.

One might config this by setting a `append_saltenv` flag:

```
file_roots:
  __env__:
    - /path_to_dir_with_multiple_environments: 
           - append_saltenv: true

filesystem contents:
/path_to_dir_with_multiple_environments/base/top.sls
/path_to_dir_with_multiple_environments/dev/top.sls
/path_to_dir_with_multiple_environments/prod/top.sls
```

#52392 from @mattp is about a similar subject: dynamic file roots that can be configured runtime via the utils/ LazyLoader mechanism without restarting the salt-master. 

My proposed feature would imply that the salt-master perhaps doesn't even know about these saltenvs, but can find the requested file with the saltenv prepended to the file's path nevertheless.

A similar scheme would be needed for pillar_roots. 

NB: The `__env__` for `pillar_roots` is implemented in #46309. It is not mentioned in the [master.conf](https://docs.saltstack.com/en/latest/ref/configuration/master.html#pillar-roots) documentation though.

### PR DESCRIPTION
**Pull request by morgana2313**
### What does this PR do?

Extends dynamic environments for file_roots, pillar_roots and ext_pillar.stack; the requestor's saltenv/pillarenv can be inserted to a requested file-path with the token `__env__`. Glob-style wildcard matching for environments in file_roots, pillar_roots and ext_pillar.stack.

This allows for file_roots, pillar_roots and ext_pillar.stack variants of the gitfs, svnfs and hgfs behavior where branches and tags are translated into salt environments; salt environments are translated into directories. This allows for adding saltenvs dynamically without restarting the salt-master.

### What issues does this PR fix or reference?

Fixes: #55747. Extends #50784 and #46309

### New Behavior

1. glob-style wildcard matching of saltenv/pillarenv. Backwards compatible; specifying `__env__`  as environment has the same effect as '*' and matches all environments. The first matching saltenv/pillarenv is used.

2. `__env__` in a path is replaced by the requistor's saltenv/pillarenv. 

3. new option for ext_pillar stack: pillarenv
```
file_roots:
  foo*:
    - /path/__env__/salt    # becomes /path/foo-bar/salt for saltenv foo-bar
    - /path2/__env__        # becomes /path2/foo-foo for saltenv foo-foo
  '*':
    - /path/__env__/salt    # becomes /path/bar-bar/salt for saltenv bar-bar
    - /path2/__env__        # becomes /path2/bar-foo for saltenv bar-foo

pillar_roots:
  foo*:
    - /path/__env__/pillar    # becomes /path/foo-bar/pillar for saltenv foo-bar
    - /path2/__env__          # becomes /path2/foo-foo for saltenv foo-foo
  '*':
    - /path/__env__/pillar    # becomes /path/bar-bar/pillar for saltenv bar-bar
    - /path2/__env__          # becomes /path2/bar-foo for saltenv bar-foo

ext_pillar:
  - stack:
      pillarenv:
        foo*: /path/__env__/pillar/stack.cfg
        '*': /path2/__env__/pillar/stack.cfg
```

### Tests written?

Yes: Existing unit tests modified to expect new behavior.

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by morgana2313** [comment]
@garethgreenaway, @sathieu, @dwoz : I would like to know if this approach (globstyle matching of environments and __env__ replacement in paths) for dynamic environments for file_roots, pillar_roots and ext_pillar.stack is viable before I proceed. The code in this pull request functions OK as far as I can tell.
 
I am concerned about the pillar cache; Saltstack cannot cache pillar files for a pillarenv before a request, because the path depends on the pillarenv parameter from request:

```
pillar_roots:
  foo*:
    - /path/__env__/pillar    # becomes /path/foo-bar/pillar for saltenv foo-bar
```
 
What would be the best way to pass the requested pillarenv (for replacing __env__  in a path) to the functions fileclient.file_list and extpillar/stack? For this moment I hardcoded them at `master`, because my attempts to pass them seems to breaks other code.

I would appreciate tips!

**Comment by morgana2313** [comment]
I think the failed checks are perhaps artifacts of the check process?

**Comment by morgana2313** [comment]
@garethgreenaway, @dwoz: I think this pull request is ready to merge and has been for a week, how do I get somebody to review it? 
I think it passes all checks, but a few seem to fail at random without informatie that I can understand as to why.
Regards, Jasper

**Review by waynew — CHANGES_REQUESTED** [review]
@morgana2313 thanks for the PR!

It's looking good, but it's definitely missing some test coverage. I will be OOO this week but I'll put it on the list of things to discuss with our architecture team. At the very least, we will require some more tests - if you struggle with writing tests please let us know and we can figure out a time to help train on testing.

**Comment by mikisch81** [comment]
Hello,
Is this PR still in progress?

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
