### PR TITLE
fix logic problem that prevented name change

### LINKED ISSUE #36243: system.set_computer_name not working
When trying to set the computer name on the Windows Machine using `system.set_computer_name`, it returns false

### Setup
Linux Master and Windows Minion

### Steps to Reproduce Issue
```
salt \* system.set_computer_name win-test
win:
    False
```
```
salt \* system.get_pending_computer_name
win:
    ????
```
### Versions Report
```
Master

Salt Version:
           Salt: 2016.9.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.0.1406 Core
        machine: x86_64
        release: 4.6.5-x86_64-linode71
         system: Linux
        version: CentOS Linux 7.0.1406 Core
```

```
Minion

win:
    Salt Version:
               Salt: 2016.9.0
     
    Dependency Versions:
               cffi: 1.7.0
           cherrypy: 7.1.0
           dateutil: 2.5.3
              gitdb: 0.6.4
          gitpython: 2.0.8
              ioflo: 1.5.5
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: 1.4.5
           M2Crypto: Not Installed
               Mako: 1.0.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: 0.2.4
            Tornado: 4.4.1
                ZMQ: 4.1.5
     
    System Versions:
               dist:   
            machine: AMD64
            release: 7
             system: Windows
            version: 7 6.1.7601 SP1 Multiprocessor Free
```

### PR DESCRIPTION
**Pull request by UtahDave**
### What does this PR do?

Allows for Windows computer name change on python 2.7
### What issues does this PR fix or reference?

Fixes #36243 
### Previous Behavior

computer name change fails on windows with python 2.7

Introduced by https://github.com/saltstack/salt/pull/34788/commits/586ce6d0d2c81e68fbf672ad02f7d82573e26aab
### Tests written?

No

### CODE REVIEW

**Comment by cachedout** [comment]
This will break Py3 support.

**Comment by UtahDave** [comment]
Hm. We'll have to figure something else out then, because the line they added to add Py3 support broke Py2 support.  And we ship with Py2.

**Comment by cachedout** [comment]
Let's just gate it between between a check for the python version. We've done that in a few other places.

**Comment by lorengordon** [comment]
Is the issue just a string type check between py2 and py3? Does salt dep `six` already? If so, this is compatible with both, `isinstance(name, six.string_types)`.

Or, if not dep'ing `six`, maybe this, http://stackoverflow.com/a/22679982

**Comment by lorengordon** [comment]
nvm, it helps when i read the prior patch.

**Comment by lorengordon** [comment]
How about:
```
    if name and hasattr(name, 'decode'):
         name = name.decode('utf-8')	
```

**Comment by damon-atkins** [comment]
From https://docs.python.org/3/library/ctypes.html

> Note that win32 system dlls like kernel32 and user32 often export ANSI as well as UNICODE versions of a function. The UNICODE version is exported with an W appended to the name, while the ANSI version is exported with an A appended to the name. The win32 GetModuleHandle function, which returns a module handle for a given module name, has the following C prototype, and a macro is used to expose one of them as GetModuleHandle depending on whether UNICODE is defined or not

I introduce into reg.py some str conversion functions 
```
def _mbcs_to_unicode(instr):
    '''
    Converts from current users character encoding to Unicode.
    When instr has a value of None, the return value of the function
    will also be None.
    '''
    if instr is None or isinstance(instr, six.text_type):
        return instr
    else:
        return six.text_type(instr, 'mbcs')
```

Suggest you add
```
from __future__ import unicode_literals  # at some stage this will need to be in all files to give
    if PY2:
        local_hostname = _mbcs_to_unicode(hostname)
    else:
        local_hostname = hostname # Assume Unicode already and PY3 default of UTF-8
```
As your using the UNICODE version of the function SetComputerNameExW

**Comment by UtahDave** [comment]
Go Go Jenkins!

**Comment by damon-atkins** [comment]
if name and not six.PY3:      This logic means "if name and PY1 PY2 PY4 PY5 ...". It's a future bug.
Assuming no one is using PY1 and the future is unicode from PY3 onward
Code should assume Unicode is the Norm, and change stuff based on it being PY2 
i.e. if PY2   rather than if not PY3

**Comment by cachedout** [comment]
I agree with @damon-atkins here. Tweaking that logic slightly will make this future-proof. :]

**Comment by UtahDave** [comment]
Great point. Thanks! I'll make that change

**Comment by UtahDave** [comment]
@cachedout change made.

**Pull request merged**
