### PR TITLE
Add a new git.cloned state

### PR DESCRIPTION
**Pull request by terminalmage**
See https://github.com/saltstack/salt/issues/47937

### CODE REVIEW

**Comment by cachedout** [comment]
2018.3 and not develop?

**Comment by terminalmage** [comment]
Yes, I made the choice to put it in 2018.3 because it doesn't touch any existing code (i.e. no code was changed in the git module, and code was only _added_ to the state module), and it satisfied use case from someone who wanted `git.latest` to not check for updates if the repo was already cloned.

**Review by cachedout — APPROVED** [review]

**Comment by andreasnuesslein** [comment]
just a heads up, for others who might land here after trying to run `git.cloned`:
although it's already in the [docs](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.git.html#salt.states.git.cloned), it refers to 2018.3.**3** . the latest release as of now is 2018.3.**2**.

**Comment by terminalmage** [comment]
Yes, 2018.3.3 is nearing release, so within a few weeks it will be available.

**Pull request merged**
