### PR TITLE
Salt.modules.mysql.query custom conversions fixes

### PR DESCRIPTION
**Pull request by ChellsChen**
### What does this PR do?
Salt.modules.mysql.query custom conversions fixes
### What issues does this PR fix or reference?
[#39561](https://github.com/saltstack/salt/issues/39561)
### Previous Behavior
execute query sql error when mysql return result.

### New Behavior
run ok!

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by terminalmage** [comment]
@rallytime this needs a backport to 2016.3

I'm not familiar with this code though, despite mentionbot's insistence.

**Comment by gtmanfred** [comment]
I am not sure this needs to be committed, I am unable to replicate the error that is mentioned in the issue.

**Review by gtmanfred — COMMENTED** [review]
I am not sure that we need to remove these lines.  It works correctly with MySQLdb which is what we use, it does appear to have some problems with pyMySQL, so we should figure out why this is the case before deleting this section.

**Comment by gtmanfred** [comment]
@regilero it looks like you original wrote this.  It doesn't appear to work with the pymysql version of MySQLdb, do you happen to know why?  

https://github.com/saltstack/salt/blob/develop/salt/modules/mysql.py#L67

Thanks,
Daniel

**Comment by ChellsChen** [comment]
MySQLdb support  onverters that are list，but pymysql converting is not support it. In pymysql,  These converters have been defined： FIELD_TYPE.BLOB,   FIELD_TYPE.STRING,   FIELD_TYPE.VAR_STRING,    FIELD_TYPE.VARCHAR;    
https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/converters.py#L404，

In  MySQLdb,  These converters are lists need to reload.  
https://github.com/farcepest/MySQLdb1/blob/master/MySQLdb/converters.py#L167

**Comment by gtmanfred** [comment]
:+1: thanks @ChellsChen

**Review by gtmanfred — APPROVED** [review]

**Pull request merged**
