### PR TITLE
Support new apidocs content for Proxmox 7+

### PR DESCRIPTION
**Pull request by SndR85**
With this change the call to apidocs on the Proxmox interface will succeed on Proxmox 7. In Proxmox they changed the JavaScript content so that `var pveapi = ...` became `var apiSchema = ...`. With this change the regex is fixed to support both. I've tested it with Proxmox 6.x and Proxmox 7.x.

### CODE REVIEW

**Comment by christophlsa** [comment]
I have the same problem and can confirm that this change fixed the issue.

**Comment by sanderc85** [comment]
@krionbsd Can I do also something to get this PR forward? Proxmox 7 was released 9 months ago, but Salt-cloud can't use Proxmox 7 out-of-the box when this change isn't merged. In my environment we don't use Proxmox 6 anymore and we have patched `proxmox.py` everywere to make Salt-cloud work on Proxmox 7.

**Comment by sanderc85** [comment]
I see that #62166 fixed this? I think that this PR isn't required anymore?

**Comment by whytewolf** [comment]
@sanderc85 Thank you or the update it does look like #62166 did fix this issue. I"ll go a head and close this PR as that one is already merged.

**Pull request closed without merging**
