### PR TITLE
Corrected Python package referenced

### PR DESCRIPTION
**Pull request by salt-lick**
Corrected the name of the Python package that is referenced and specified the Python3 version.

### What issues does this PR fix or reference?
Fixes:
Python package referenced

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by leifliddy** [comment]
Packages names vary between distributions. So on Redhat-based distros: RHEL, CentOS, Rocky Linux, Fedora...etc that package is either called ```python-inotify``` (python2 version for EL7 and below) or ```python3-inotify```
I'm not exactly sure how the documentation should deal with variations in packages names between distros, but I don't see how the community as a whole would benefit from simply swapping out the package name that corresponds to your distro of choice. 
Perhaps we should just list the package name for ```Redhat-based, Debian-based, and Arch-based distros```. I think that would cover that vast majority of Linux users. Will see what the devs think....

**Comment by Ch3LL** [comment]
We no longer support python2, so I think its fine to change it to python3-inotify. But I do agree that other distro's might have a different name. We could add a warning that the package name could be different depending on the distro and also include instructions on how to pip install the package.

**Comment by whytewolf** [comment]
as we move towards onedir. package names become less important and pip names will need to be used anyway.

**Review by whytewolf — DISMISSED** [review]

**Comment by leifliddy** [comment]
@Ch3LL Just an FYI, this PR is not changing the package name to  ``` python3-inotify``` (Redhat name) but rather to ```python3-pyinotify``` (Debian name).

**Comment by Ch3LL** [comment]
thanks for pointing that out @leifliddy . I actually did not notice that slight difference. I'm still okay with just adding a warning that the package name can be different for different distros and to add instructions on how to install it using the `pip.install` execution module. Would you mind submitting those changes @salt-lick ?

**Comment by Ch3LL** [comment]
bump @salt-lick ^

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
