### PR TITLE
log.setup: only assign user if defined

### PR DESCRIPTION
**Pull request by jfindlay**
### What does this PR do?

Fix the stack trace:

``` py
Process Process-1:
Traceback (most recent call last):
  File "/opt/salt/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/salt/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/testing/salt/log/setup.py", line 934, in __process_multiprocessing_logging_queue
    check_user(opts['user'])
AttributeError: Values instance has no attribute '__getitem__'
```
### What issues does this PR fix or reference?
#36203
### Tests written?

No

### CODE REVIEW

**Comment by jfindlay** [comment]
This function is called twice, once from `salt/utils/parsers.py` and once from `tests/integration/__init__.py`, the first passes a legitimate `dict`, the second a `Values` instance.
```console
$ git grep -En setup_multiprocessing_logging_listener --
salt/log/setup.py:786:def setup_multiprocessing_logging_listener(opts, queue=None):
salt/utils/parsers.py:790:            log.setup_multiprocessing_logging_listener(
tests/integration/__init__.py:186:        salt_log_setup.setup_multiprocessing_logging_listener(
```

**Comment by s0undt3ch** [comment]
I believe the fix should be done instead on the integrations module? To pass a dict?

**Comment by jfindlay** [comment]
@s0undt3ch, updated.  What do you think?

**Review by s0undt3ch — APPROVED** [review]

**Comment by s0undt3ch** [comment]
Looks good.

**Comment by cachedout** [comment]
:+1:

**Pull request merged**
