### PR TITLE
Reinstate ignore_cidr option in salt-cloud openstack driver

### LINKED ISSUE #57127: [BUG] - salt-cloud: openstack driver post 2017.x can't select which private network to connect via ssh.
**Description**
When using salt-cloud to spin up new instances in an environment with multiple private networks there is no way to select which 'private' network to use for ssh access from the master to the minion. In some cases there will be no public network to connect to.

(e.g. rackconnect version 3 in the rackspace public cloud has the standard private `servicenet` network and a private `rackconnect` network like `RC-XXXX` as a shared network between cloud and dedicated environments, and potentially no public network IP) 

By setting `ssh_interface: private_ips` I can tell salt-cloud to use a private IP instead of trying a public IP but cannot select which network to use. From my reading of the code the `preferred_ip` function will return the first private IP it gets back from the API.

In many cases, where there are 2 _private_ networks, the first IP to come back will be for the `servicenet` ip which is not accessible from the salt master (which is a non-cloud server sitting in the dedicated environment) so the salt-cloud command loops waiting for abilty to connect to the 10.x address and then fails.

In earlier versions (pre-2018) the older libcloud based openstack driver had the `ignore_cidr` parameter which could be set in the cloud config to blacklist the 'servicenet' private ip range (10.x.x.x) and ensure that it only connects over the other RC network.

However this option does not exist in the current (shade based) versions of the openstack driver, and so this is a blocker to our ability to upgrade from 2017.7.8 which is now EOL.

Ideally I'd like: 
 `ignore_cidr: 10.0.0.0/8`
to be re-implemented as it exists in 2017.7.8
OR 
Alternatively have a way to specify the private network to use by name:
e.g.
```
...
...
    network:
      # RC-XXX network
      - id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      # ServiceNet private network    
      - id: 11111111-1111-1111-1111-111111111111
  ssh_interface: private_ips
  ssh_interface_name: RC_XXX
```

**Setup**
You will need:
* Rackspace cloud user and api key
    (I've been testing in LON region)
* Create a cloud network 'private_salt_net' (172.17.117.0/24)
* Create a centos7 salt-cloud-master node with PublicNet,ServiceNet,private_salt_net
        (private_salt_net IP of master is 172.17.117.X - adjust config as needed)
* Install latest 3000.x versions of salt, salt-cloud, salt-master on salt-cloud-master
* Install extra python dependencies (pip3 install shade rackspaceauth )
* Instances will be built with only the ServiceNet,private_salt_net networks
* salt-cloud will interact with instances over the private_salt_net network

`# cat /etc/salt/cloud.providers.d/rackspace.conf`
```
rslon:
  minion:
    master: 172.17.117.2
  driver: openstack
  profile: rackspace
  auth:
    username: xxxxxxxx
    api_key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 
  region_name: LON
  auth_type: rackspace_apikey
  # We need to pass the network parameters in `extra` because `network` only allows a dict not a list
  extra:
    network:
    ## ServiceNet (private)
    - id: 11111111-1111-1111-1111-111111111111
    ## private_salt_net
    - id: 4581631a-ec34-4c05-9fae-394686b66a49
    ## PublicNet (disabled
    #- id: 00000000-0000-0000-0000-000000000000
  ssh_interface: private_ips

  # Below is what we use in salt-2017.7.8 but has no effect in later versions:
  ignore_cidr: 10.0.0.0/8

  # However if work is done to solve this then an alternative syntax could be:
  # ssh_interface_name: private_salt_net
```

`# cat /etc/salt/cloud.profiles.d/profiles.conf`
```
centos_7:
  provider: rslon
  # centos_7_pvhvm
  image: fa756e3a-0fe3-4bbf-8f78-e675d8968142
  #size: 1 GB General Purpose v1
  size: general1-1
  ssh_key_file: /root/.ssh/id_rsa
  ssh_key_name: salt_cloud_test
  wait_for_metadata:
    rax_service_level_automation: Complete
  meta:
    build_config: monitoring_defaults,updates
```
The purpose here is to simulate a rackconnect v3 environment where the external IPs are allocated on the loadbalancer, but the salt-cloud-master only interacts with the cloud instances via the private network

**Steps to Reproduce the behavior**

`# salt-cloud -p centos_7 minion1.example.com -l debug`

**Expected behaviour**
salt-cloud should build a new centos7 device with the name minion.example.com, connect to it over ssh on its private `salt_private_net` address, and then install salt and configure the minion accordingly.

**Screenshots**
-- NONE

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000.2
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.8.2003 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.el7.x86_64
         system: Linux
        version: CentOS Linux 7.8.2003 Core
```
</details>

**Additional context**
`ignore_cidr` looks like it was introduced in https://github.com/saltstack/salt/commit/b9d8f8ab86d99a62e6fe0c3ca00467c1b6f04347 and https://github.com/saltstack/salt/commit/562dccc95b0395174dec8311673f2f0ca5058291

Previous related issue which includes steps to illustrate the desired behaviour on 2017.7: https://github.com/saltstack/salt/issues/46215

### PR DESCRIPTION
**Pull request by mark-hyde**
### What does this PR do?
Re-implements the 'ignore_cidr' option last present in v2017.7.8.

This option was present in v2017.7, but was not carried over when the openstack driver was reimplemented using the shade library.  It's absence has prevented us from upgrading beyond 2017.7.8 as 'rackconnect v3' typically creates devices with 2 private ip addresses, one of  which is not reachable from the salt-master, and more often than not the first ip in the private_ips list was the wrong one!

### What issues does this PR fix or reference?
Fixes: #57127

### Previous Behaviour
When creating device with multiple private_ips and no public_ip, where one of the private_ips is not reachable from the salt-master, salt would attempt to connect to the first IP found in the list (which might be unreachable), and then fail to complete when this was not possible. 

### New Behaviour
By setting the ignore_cidr option you can ensure salt-cloud ignores any private_ips within the cidr range so that you can filter out any IPs unreachable from the salt master.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [X] Docs
- [X] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by mark-hyde** [comment]
(I haven't written any tests as I don't really know how to do so for this.)

**Comment by mark-hyde** [comment]
My commit history is now mucky as anything! 
Is it convention to squash commits once everything is tested and passes?

**Comment by mark-hyde** [comment]
re-run ci/py3/macosxcatalina/pytest

**Comment by mark-hyde** [comment]
re-run pr-ubuntu1604-py3-pytest

**Comment by mark-hyde** [comment]
rerun pr-windows2019-py3-pytest

**Comment by mark-hyde** [comment]
rerun pr-windows2016-py3-pytest

**Comment by sagetherage** [comment]
the mac tests are not related, but I did get confirmation the windows tests are related, can you please take a look at those @mark-hyde?

**Comment by mark-hyde** [comment]
> the mac tests are not related, but I did get confirmation the windows tests are related, can you please take a look at those @mark-hyde?

These look like the failing tests. 
```
17:39:51         FAILED tests/pytests/unit/cloud/clouds/test_openstack.py::test_when_ignore_cidr_is_configured_and_ip_is_provided_result_is_expected[ip is in ignore_cidr-203.0.113.1-203.0.113.0/24-True]
17:39:51         FAILED tests/pytests/unit/cloud/clouds/test_openstack.py::test_preferred_ip_function_returns_expected[ignore_cidr matches first 2 ips, expected value will be first ip that doesn't match cidr.-example_ips0-203.0.113.0/24-192.0.2.1]
17:39:51         FAILED tests/pytests/unit/cloud/clouds/test_openstack.py::test_preferred_ip_function_returns_expected[ignore_cidr matches all IPs, expected value will be False.-example_ips3-203.0.113.0/24-False]
17:39:51         FAILED tests/unit/cloud/clouds/test_openstack.py::OpenstackTestCase::test_get_dependencies
17:39:51         = 4 failed, 9836 passed, 3316 skipped, 2 xfailed, 580 warnings in 3334.92s (0:55:34) =
```
I managed to navigate myself to https://jenkins.saltproject.io/job/pr-windows-2019-x64-py3-pytest/job/PR-59778/2/consoleText which shows it returning the first IP instead of one filtered by netaddr.all_matching_cidrs

I suspect that netaddr isn't installed as part of the windows tests, but is as part of the linux ones.
Is there a way to get this dependency included somehow?

**Comment by Ch3LL** [comment]
If you add the requirement to the file `requirements/static/ci/common.in` and run pre-commit, it will propagate the requirement to all the necessary files.

**Comment by mark-hyde** [comment]
Having edited `requirements/static/ci/common.in` , `git add`(ed) the file and then `git commit` the precommit runs but then I get errors like:

```
Exception raised when processing requirements/static/ci/windows.in
Traceback (most recent call last):
  File "/home/markhyde/.cache/pre-commit/repobf9tm69z/py_env-python3/bin/pip-tools-compile", line 272, in compile_requirement_file
    piptools.scripts.compile.cli()
  File "/home/markhyde/.cache/pre-commit/repobf9tm69z/py_env-python3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/markhyde/.cache/pre-commit/repobf9tm69z/py_env-python3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/markhyde/.cache/pre-commit/repobf9tm69z/py_env-python3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)


...
...
...
  File "/home/markhyde/.cache/pre-commit/repobf9tm69z/py_env-python3/lib/python3.7/site-packages/pip/_vendor/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/home/markhyde/.cache/pre-commit/repobf9tm69z/py_env-python3/lib/python3.7/site-packages/pip/_vendor/urllib3/util/ssl_.py", line 332, in ssl_wrap_socket
    context.load_default_certs()
  File "/home/markhyde/.pyenv/versions/3.7.0/lib/python3.7/ssl.py", line 479, in load_default_certs
    self._load_windows_store_certs(storename, purpose)
  File "/home/markhyde/.pyenv/versions/3.7.0/lib/python3.7/ssl.py", line 463, in _load_windows_store_certs
    for cert, encoding, trust in enum_certificates(storename):
NameError: name 'enum_certificates' is not defined
```

Is this because I am running it on a linux device? 
```
 168 if sys.platform == "win32":
 169     from _ssl import enum_certificates, enum_crls
```

I'm not sure how to resolve this?

**Comment by mark-hyde** [comment]
re-run pr-macosx-catalina-x86_64-py3-pytest

**Comment by sagetherage** [comment]
@mark-hyde that test is still being a problem child and we do have someone looking into it.

**Review by Ch3LL — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
