### PR TITLE
list_pkg attr parameter: add support for epoch, release

### PR DESCRIPTION
**Pull request by moio**
### What does this PR do?
It adds support for two more attributes to the `attr` parameter of `list_pkg` introduced in #42310 and #42718 (for both the `zypper` and the `yumpkg` backends).

### What issues does this PR fix or reference?
None.

### New Behavior
More parameter values can be specified and are honoured. Output of the `version` attribute is now consistent with `pkg_info` as a nice side effect.

### Tests written?
Yes, existing tests were adapted.

### CODE REVIEW

**Comment by moio** [comment]
Note: Jenkins failure looks unrelated to me, and the order of commits shown here in GitHub seems incorrect.

**Comment by moio** [comment]
@brejoc if you have time could you please take a look?

**Comment by moio** [comment]
Rebased on top of current `develop`

**Comment by cachedout** [comment]
@terminalmage Can you swing by here when you get a moment? Thanks.

**Review by terminalmage — APPROVED** [review]

**Pull request merged**
