### PR TITLE
Bump deprecation version to Sodium, update docs for module state

### PR DESCRIPTION
**Pull request by rallytime**
At the request of @thatch45, this deprecation warning is being removed.

@isbm - It appears this change might need some more work before the deprecation warning is officially issued. @thatch45 can you comment with some more details?

References PR #39891

### CODE REVIEW

**Comment by thatch45** [comment]
Thanks @rallytime 
@isbm I am confused by xrun, but moreso by the deprecation, if the old syntax works, why would we ever deprecate it? and how does the deprecation check work? It needs to have very clear instructions. Also, if you use the function `module.xrun` then it errors out, as suggested in the doc.
Thanks!

**Comment by isbm** [comment]
@thatch45 `xrun`? There is no anymore `xrun`, but we decided to _rename_ it to `run`, as it is even [in this current PR](https://github.com/saltstack/salt/pull/41708/files#diff-963ee4c224de95290617e29aa063d07cR218). Therefore we deprecated previous behaviour (syntax). BTW, you requested to deprecate this the other day... :laughing:

**Comment by isbm** [comment]
The only thing that seems like we had docstring update this regard lost in merges (again?), where it should say `module.run` instead of `module.xrun` as it is right now...

@rallytime since you've already PR'ed this, maybe un-comment the deprecation and simply remove "x" character from the docstring example?

>  and how does the deprecation check work? It needs to have very clear instructions.

Sure. Instructions [are here](https://github.com/saltstack/salt/blob/develop/salt/utils/decorators/__init__.py#L341) and [here](https://github.com/saltstack/salt/blob/develop/salt/utils/decorators/__init__.py#L437).

**Comment by thatch45** [comment]
I guess the issue is that I think we had some miss communication along the way as we continually morphed what this was intended to do, no no harm or foul here of course :) just trying to figure out the best solution. I know how the deprecation systems work but the issue is that we are firing a deprecation warning that looks like the function is deprecated when we are trying to deprecate old syntax.
I am under the impression that the old syntax and the new syntax works, so we should leave support for the old syntax in for the foreseeable future and remove the deprecation warning. Please let me know if I have miss interpreted this.

**Comment by isbm** [comment]
Almost there. The policy `policy=with_deprecated.OPT_IN` says that "by default you use the old syntax, so please migrate and turn on the new syntax`. Hence the deprecation warning of the _syntax_.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
Ok, I see now that I miss understood a few things originally. Since this is going to mandate that users change their states (which I hate to do) I think that we should move the deprecation out much further, to `Sodium`. Second we need to make sure that the deprecation warning better explains that the syntax is changing and that we need to explain that they should set the config value. I think it would also make sense given that I have a better view of this than I did before that we add an additional function called xrun that does the new syntax and we just explain the eventually run will work like xrun.
I just see this causing a lot of people a lot of pain if we don't do it right, and we should avoid that, this is a very widely used module :)
What do you think @isbm ?
Sorry for the late reply, I have been under the weather

**Comment by rallytime** [comment]
@isbm and @thatch45 I have uncommented the deprecated decorator and bumped it to "Sodium" in this PR. I think the rest of the suggestions/discussion from @thatch45 should be done in a separate PR since @isbm is more familiar with the way he wrote the decorator.

**Comment by isbm** [comment]
@thatch45 I completely agree to get it right, if something missed. However, let's drop away the `xrun` thing, because it was a very short term patch into a development branch that was almost next day overwritten with the new `run`. This means, users never were actually used `xrun` in their lifetime.

What I understood is the following:

- Make the old syntax last till Sodium. This was the original idea anyway (done).
- Make the deprecation message more clear regarding to the syntax change.

The rest would be nice if you re-phrase it once again. :wink:

**Comment by thatch45** [comment]
ok, I think we are on the same page here, the only thing I would still think would be a good idea would be to make it easier to use the new syntax by allowing something like a flag in the state or an alternative function so there is an easy migration path that lines up with the state execution rather than the minion operation.
But with that said, I think we are on the same page

**Comment by rallytime** [comment]
Ok, I updated the documentation to not refer to `xrun` anymore, and just use `run`. I also made the `Sodium` release version available in `version.py` which was causing some test failures earlier.

From my perspective, this PR is finished and @isbm can add a new PR to the new deprecation utilities that he added sometime ago for @thatch45's suggestion of:

> I would still think would be a good idea would be to make it easier to use the new syntax by allowing something like a flag in the state or an alternative function so there is an easy migration path that lines up with the state execution rather than the minion operation.

Do I have that all understood correctly? Am I missing anything?

**Comment by thatch45** [comment]
Yes, this should be good to go, thanks @rallytime !

**Comment by isbm** [comment]
> ok, I think we are on the same page here, the only thing I would still think would be a good idea would be to make it easier to use the new syntax by allowing something like a flag in the state or an alternative function so there is an easy migration path that lines up with the state execution rather than the minion operation.

The flag in the state is actually an interesting idea. And I would rather add all that to everywhere. Something like `use_deprecated` or `use_superseded` right inside the state:
```yaml
my_foo:
    use_superseded:
        - module.run
    module.run:
        zypper.remove
            - vim
            - vim-data
```
The state above will run a new version of the `module.run` implementation. Hmm, let me think about it. :wink:

**Comment by cachedout** [comment]
@isbm We really need to get this into today to tag the RC. Any chance you can look at it and let us know if you're OK with us putting this in as-is?

**Comment by thatch45** [comment]
I am ok with putting this in as is for the RC since to complete the goals for it as is we really only need to update some docs to make them a little clearer

**Comment by cachedout** [comment]
Merged per @thatch45

**Comment by isbm** [comment]
@cachedout yes. :wink: It is 0:10 in Germany at the moment... :laughing: But yes, this PR goes as is, I will add such discussed above functionality _anyway_ since it is very important.

**Comment by cachedout** [comment]
@isbm Just so you are aware, we are tagging the RC _very_ soon. Likely in the next twenty-four to forty-eight hours.

**Comment by isbm** [comment]
@meaksh see above. *RUN!* @cachedout another follow-up is soon coming!

**Comment by cachedout** [comment]
@isbm We'll need them ASAP, likely mid-morning our time tomorrow if possible (MST). Please email me if you don't think that's possible. Thanks. :]

**Comment by isbm** [comment]
@cachedout "them" — what exactly? The #41856 is going to be fixed ASAP now. Anything else till mid-morning MST?

**Comment by cachedout** [comment]
@isbm I already have it in so I think we're set. Just waiting on the k8s stuff from @flavio and we'll be all done and I have worked things out with him. We're close! Thanks for all your help.

**Pull request merged**
