### PR TITLE
Alias moby to docker in Nitrogen (and later)

### PR DESCRIPTION
**Pull request by terminalmage**

### CODE REVIEW

**Comment by terminalmage** [comment]
The other thing we have to consider is whether or not we just want to rename everything to "moby" (docstrings, etc.) and alias it back to ``docker``, which is more work but may be the better long-term solution.

**Comment by cachedout** [comment]
@terminalmage I think that aliasing back to `docker` from `moby` would be a better long-term plan but Nitrogen feels too early for that. Maybe Oxygen?

**Comment by terminalmage** [comment]
@cachedout I agree. I've added a blurb in the Nitrogen release notes. This should be good to merge.

**Comment by damon-atkins** [comment]
Mmm.  I read that as docker will use Moby not replace it.   And then other vendors can develop their own interface into Moby.  ??

**Pull request merged**
