### PR TITLE
Migrate `tests/integration/modules/test_vault.py` to functional 

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title

### CODE REVIEW

**Review by twangboy — APPROVED** [review]

**Comment by Ch3LL** [comment]
which OS should I expect to see these tests running? I'm not seeing them run on centos 7: https://jenkins.saltproject.io/job/pr-centos-7-x86_64-py3-pycryptodome-pytest/job/PR-62512/2/testReport/tests.pytests.functional.modules/test_vault/

**Comment by s0undt3ch** [comment]
> which OS should I expect to see these tests running? I'm not seeing them run on centos 7: https://jenkins.saltproject.io/job/pr-centos-7-x86_64-py3-pycryptodome-pytest/job/PR-62512/2/testReport/tests.pytests.functional.modules/test_vault/

None since the current golden images don't have vault installed. The newer golden images will contain vault installed. I've tested and these tests are passing.

**Comment by s0undt3ch** [comment]
To be precise, Arch Linux and the Debian and RedHat OS families will have vault installed.

**Review by twangboy — APPROVED** [review]

**Comment by s0undt3ch** [comment]
Approved, and tests are passing. Merging.

**Pull request merged**
