### PR TITLE
Added support for instance start and stop actions in GCE

### PR DESCRIPTION
**Pull request by Cidan**
### What does this PR do?

It adds start and stop actions to Google Cloud instances.
### What issues does this PR fix or reference?

https://github.com/saltstack/salt/issues/35589
### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by erjohnso** [comment]
Looks good to me @Cidan!

wdyt @Ch3LL?

**Comment by rallytime** [comment]
Looks good @Cidan. The pylint test didn't run, so I am just triggering these again. Thanks for the review @erjohnso.

**Comment by erjohnso** [comment]
Yay @rallytime! :)

**Comment by rallytime** [comment]
@Cidan There are a couple of small [lint errors](https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/4943/violations/file/salt/cloud/clouds/gce.py/) on this. Would you mind cleaning those up?

Also, adding a `.. versionadded:: Nitrogen` tag in the docs to the new functions you've added here would be fanctastic!

**Comment by Cidan** [comment]
@rallytime All set.

**Comment by Cidan** [comment]
Sorry @rallytime, I totally spaced out and didn't see your docs comment. I don't think it applies (at least to the GCE doc) in this case, because actions aren't really listed out to begin with. Is there somewhere specific you had in mind that I should add the document tag?

**Comment by rallytime** [comment]
@Cidan No problem. I can grab those tags really quickly. These new functions will be displayed as docs (once this is merged) on [this page](https://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.gce.html), so I just wanted a record of when those functions were added. I'm happy to add those really quickly so we can just get this in. Thanks for your addition! :D

**Pull request merged**
