### PR TITLE
Allow salt's test suite to run under pytest

### PR DESCRIPTION
**Pull request by s0undt3ch**
This is still barebones, but is apparently working.

I'll be fixing it/complementing it as I move along with the py3 work.

### CODE REVIEW

**Comment by cachedout** [comment]
More merge conflicts I'm afraid.

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Still one more merge conflict. :-/

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Don't merge this PR until a more recent version of saltt-testing can be used in our Jenkins setup without breaking the test suite.

**Comment by s0undt3ch** [comment]
Closing to avoid an accidental merge.

**Pull request closed without merging**
