### PR TITLE
Remove deprecated version of status.uptime module function

### PR DESCRIPTION
**Pull request by rallytime**
### What does this PR do?
- Removes the deprecated version of the status.uptime function. The deprecated version of the function was set to be removed in Carbon.
- Updates the Carbon release notes with this removal
- Removes the test_deprecated_uptime unit test. The deprecated version of uptime no longer exists.

Refs #35196
### Tests written?

No - This just removes an old function, so let's see how the current tests do now that this code has been removed.

@isbm - This is your code, and I haven't handled anything with your new deprecation decorators yet. Did I do this correctly?

### CODE REVIEW

**Comment by isbm** [comment]
@rallytime Yep, you got it right. :wink: The main idea is when one needs to change poorly done API to something better and prevent clutter, we implement a better version with a possibility to still use previous. Once time is up, we simply kill the old thing, just like you do.

Thanks!

**Comment by rallytime** [comment]
@isbm Great! Thank you for reviewing. :)

**Comment by cachedout** [comment]
@rallytime Some lint, please: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/4306/violations/file/salt/modules/status.py/

**Comment by rallytime** [comment]
@cachedout Thanks - I have fixed that. However, I think @sjorge should be aware of this change, as he was the one who put the kernel grain check in to use the old/deprecated version of the `_uptime()` function. Is there a reason the new one won't work here, @sjorge?

**Comment by sjorge** [comment]
_uptime() works fine on Solaris-like systems (Solaris 10, illumos, SmartOS,...) uptime() does not.

```bash
SunOS core 5.11 joyent_20160818T234814Z i86pc i386 i86pc
[root@core ~]# ls /proc | grep uptime
[root@core ~]#
```

However uptime binary is present
```
[root@core ~]# uptime
22:04:21    up 1 day(s),  3:50,  2 users,  load average: 0.66, 0.36, 0.27
```

Can you open a new issue about uptime not working on Solaris-like systems (so I won't forget)
I will fix up uptime() by adding a different code path if kernel = SunOS. Although it will probably default to just the command output on those systems (better than no output I guess)

**Comment by sjorge** [comment]
Actually... it may be better to have a fall back if /proc/uptime is missing.

I propose we only raise the exception when running on linux, and fall back to the stdout of uptime IF the binary is within path, else raise a different error?

/proc/uptime seems to not be available in OpenBSD either. (Same for the NetScaler (FreeBSD) at work, but that may not apply to FreeBSD-current)
```bash
[!]$ uname -a
OpenBSD exosphere.acheron.be 5.9 GENERIC.MP#3 amd64
[exosphere :: sjorge][~]
[.]$ ls /proc | grep uptime
colorls: /proc: No such file or directory
[exosphere :: sjorge][~]
[!]$ uptime
12:08AM  up 1 day,  3:39, 1 user, load averages: 0.25, 0.36, 0.33
```

**Comment by sjorge** [comment]
Untested as I am writing this from my bed on my tablet:

```python
def uptime():
     '''
     Return the uptime for this system.
 
     .. versionchanged:: 2015.8.9
         When running on Linux, the uptime function was changed to return
         a dictionary of easy-to-read key/value pairs containing uptime
         information, instead of the output from a ``cmd.run`` call.

     CLI Example:
 
     .. code-block:: bash
 
         salt '*' status.uptime
     '''
     ut_path = "/proc/uptime"
     if not os.path.exists(ut_path):
          if not __grains__['kernel'] == 'Linux':
               raise CommandExecutionError("File {ut_path} was not found.".format(ut_path=ut_path))
          elif not salt.utils.which('uptime'):
               raise CommandExecutionError("uptime binary not available.")
          else:
               return __salt__['cmd.run']('uptime')
 
     ut_ret = {
         'seconds': int(float(open(ut_path).read().strip().split()[0]))
     }
 
     utc_time = datetime.datetime.utcfromtimestamp(time.time() - ut_ret['seconds'])
     ut_ret['since_iso'] = utc_time.isoformat()
     ut_ret['since_t'] = time.mktime(utc_time.timetuple())
     ut_ret['days'] = ut_ret['seconds'] // 60 // 60 // 24
     hours = (ut_ret['seconds'] - (ut_ret['days'] * 24 * 60 * 60)) // 60 // 60
     minutes = ((ut_ret['seconds'] - (ut_ret['days'] * 24 * 60 * 60)) // 60) - hours * 60
     ut_ret['time'] = '{0}:{1}'.format(hours, minutes)
     ut_ret['users'] = len(__salt__['cmd.run']("who -s").split(os.linesep))
 
     return ut_ret

```

Whitespacing is probably off as the editor in Firefox on Android is kind of very much bleh.

**Comment by isbm** [comment]
@sjorge I always wanted to support Slowlaris, but there is no good way to install Salt on this stuff. Have you any reproducible way how to do that? Yes, there are no `/proc/uptime` on this thing, but there are better and more correct ways how to get `uptime` than just parse output...

I would actually fix that stuff if I would not need spend few days banging my head onto the table how to install Salt on Slowlaris, where no useful packages. I tried OpenIndiana, and it was a miserable experience. :-(

**Comment by sjorge** [comment]
@isbm 
For SmartOS I have a esky package (For use in the global zone) here:
http://pkg.blackdot.be/extras/

Pkgsrc also comes with 2015.8 (trying to get them to bump it to 2016.3 also), I have an experimental one here: http://pkg.blackdot.be/packages/2015Q4/x86_64/sysutils/

For OmniOS/OpenIndiana you can use the generic pkgsrc illumos from here:
https://pkgsrc.joyent.com/install-on-illumos/ they are also still at 2015.8

However you for those I usually install the package then use pip to upgrade it.

**Comment by isbm** [comment]
@sjorge except I never succeeded installing SmartOS. :cry: I don't have enough hardware at the moment to blow up, while on VM (KVM) it refuses to install and never even finishes to load its services, unfortunately. OpenIndiana works like a charm though, but their repos were tragic, last time I looked at it.

I will try again as per your links.

**Comment by sjorge** [comment]
SmartOS still flaky on qemu but doing better the last couple releases. Works OK on VMware and vbox.

**Comment by rallytime** [comment]
@sjorge I've submitted a new issue to help track the need to update the `uptime()` function as you've described above. I think your fix should be submitted as a separate PR, associated with the issue I just filed, #35660.

**Comment by sjorge** [comment]
@rallytime sounds good, I will try to get a PR for that somewhere this week.

**Comment by rallytime** [comment]
@sjorge Great! Thank you!

**Pull request merged**
