### PR TITLE
zypper.list_pkgs: add parameter for returned attribute selection

### PR DESCRIPTION
**Pull request by brejoc**
### What does this PR do?

Backport of merged PR https://github.com/saltstack/salt/pull/42310 to 2016.11.

### What issues does this PR fix or reference?

https://github.com/saltstack/salt/pull/42310

### CODE REVIEW

**Comment by cachedout** [comment]
@brejoc This is failing some tests. I suspect the function you were using isn't available on this branch.

**Comment by cachedout** [comment]
@brejoc Are you going to be able to fix the issues with the failing tests? We'll have to close this if we don't get a response. Thanks.

**Comment by brejoc** [comment]
@cachedout Sorry for the delay. I'll be looking into this this week again.

**Comment by rallytime** [comment]
Hi again @brejoc :)

Can you swing by here again? There are still some pylint errors and test failures on this PR.

**Comment by cachedout** [comment]
Just let me know when you've had a chance to look at this. Thanks, @brejoc

**Comment by cachedout** [comment]
I've closed this for the time being. When you're ready to work on it, @brejoc, just let us know and we'll get it re-opened or you can submit a new PR. Thanks!

**Pull request closed without merging**
