### PR TITLE
Clean up IPC Singletons

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
* Reverts #50798 
* Keep track and close IPC singleton instances
* Replaces `__del__` with [`weakref.finalize`](https://docs.python.org/3.5/library/weakref.html?highlight=weakref#weakref.finalize) under Py3.

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by thatch45 — APPROVED** [review]

**Review by DmitryKuzmenko — APPROVED** [review]

**Comment by s0undt3ch** [comment]
@thatch45, @DmitryKuzmenko please review again. I changed the singleton pattern used.

**Comment by s0undt3ch** [comment]
Re-run py

**Comment by s0undt3ch** [comment]
Rerun py

**Comment by DmitryKuzmenko** [comment]
@s0undt3ch I'm okay with new code.

**Review by DmitryKuzmenko — APPROVED** [review]

**Comment by s0undt3ch** [comment]
The final implementation will be different.

**Pull request closed without merging**
