### PR TITLE
fix memory leak in modules/lxd.py

### PR DESCRIPTION
**Pull request by sakateka**
`Container.FilesManager` leaks through the inheritance chain
in the external pylxd module. Every time the LazyLoader reimports
via the importlib `module/lxd.py`, a proxy FilesManager class is created,
which inherits from itself in the external module and then
it overwrites the `FilesManager` class in the external module by itself.
The result is an ever-growing chain of inheritance.

### What does this PR do?
fix memory leak
### What issues does this PR fix or reference?
Fixes:
may be #61988

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by sakateka** [comment]
This is the most intense leak I've found.
#62007
#62021

**Comment by sakateka** [comment]
@Ch3LL  Hi, this is a very simple patch, can you help merge it?

**Comment by sakateka** [comment]
re-run  pr-windows-2019-x64-py3-pytest
re-run pr-macosx-catalina-x86_64-py3-pytest

**Comment by sakateka** [comment]
@Ch3LL all the required tests have been passed, please merge this PR

**Review by twangboy — APPROVED** [review]

**Review by Ch3LL — APPROVED** [review]

**Review by MKLeb — APPROVED** [review]

**Pull request merged**
