### PR TITLE
Don't pollute the TZ environment variable

### LINKED ISSUE #24480: [CRITICAL] [2015.5] tls breaks tzinfo
introduced by 161f913
on https://github.com/saltstack/salt/blob/2015.5/salt/modules/tls.py#L43 

THis shoud not mess the entire environ ...
cc @basepi 
searching a fix.

### PR DESCRIPTION
**Pull request by joejulian**
Fixes #24480

### CODE REVIEW

**Comment by jfindlay** [comment]
@joejulian, it is not necessary to submit pull requests against 2015.5 and develop since 2015.5 is merged into develop almost every day.

**Comment by joejulian** [comment]
Yes, I'm aware, but since I wanted to test it against both before I submitted the first PR, I figured it couldn't hurt to go ahead and add the PR for this as well since it was done.

**Comment by thatch45** [comment]
Perfectly understandable to test on both, thanks for the additions @joejulian !

**Comment by jfindlay** [comment]
Sorry @joejulian, sometimes I get grumpy dealing with so many people every day.  Thanks for the fixes.

**Pull request merged**
