### PR TITLE
Use dashes instead of underscores in Debian based bonding networking options

### LINKED ISSUE #21892: Debian network config for bonding uses obscure syntax
Currently when Salt is used to configure bonding on a Debian based system the `/etc/network/interfaces` file is generated with `bond_*` style options.  However, this is a more obscure form than the typically seen `bond-*` style options found in most documentation.  For example, the official [Linux Ethernet Bonding Driver HOWTO](https://www.kernel.org/doc/Documentation/networking/bonding.txt) only references `bond-*` style options, and makes no reference to underscore style `bond_*` options.  This is also the case for the official [Ubuntu Bonding](https://help.ubuntu.com/community/UbuntuBonding) documentation. The official [Debian Bonding Guide](https://wiki.debian.org/Bonding) shows both dash and underscore styles.

Also, using dashes instead of underscores is more consistent with most other options typically seen in `/etc/network/interfaces` files. The options in Salt's `debian_eth.jinja` file that use dashes:

    allow-hotplug
    vlan-raw-device
    dns-nameservers
    dns-search
    wireless-essid
    wireless-mode
    wpa-ap-scan
    wpa-conf
    wpa-driver
    wpa-group
    wpa-key-mgmt
    wpa-pairwise
    wpa-proto
    wpa-psk
    wpa-roam
    wpa-ssid
    pre-up
    post-up
    pre-down
    post-down

Compare this with the only other options that seem to typically be used with underscores are the various `bridge_*` options.

It would be more consistent with most online bonding documentation, as well as the rest of the other Salt Debian based network options, if dashes were used instead of underscores in the bonding options.

### PR DESCRIPTION
**Pull request by corywright**
Fixes #21892

### CODE REVIEW

**Comment by jfindlay** [comment]
@corywright, thanks for the fix.  In the future, please feel free to submit fixes directly against feature branches, as they're regularly merged forward into develop, see http://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

**Comment by corywright** [comment]
@jfindlay Should I resubmit this against 2015.2 then?

I don't think it would be a good idea to make a change like this in the existing stable 2014.7 branch.

**Comment by jfindlay** [comment]
@corywright, yes, that would be great, thanks.

**Comment by corywright** [comment]
This is now in pull request #21894

**Comment by jfindlay** [comment]
Awesome, thanks @corywright.

**Pull request closed without merging**
