### PR TITLE
[Documentation] Cleanup docs related to Pushover

### PR DESCRIPTION
**Pull request by jasperla**
## What does this PR do?

- the service name is *Pushover*, not *PushOver* so update the documentation to reflect that
- add missing newline states.pushover which broke the codeblock: see [this page](https://docs.saltstack.com/en/master/ref/states/all/salt.states.pushover.html)

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by jasperla** [comment]
@dwoz Here too, what kind of testcases should I be writing for these comment/documentation fixes? Or are you saying I should write new tests for these four modules?

**Comment by jasperla** [comment]
re-run full all

**Review by waynew — CHANGES_REQUESTED** [review]
@jasperla can you go ahead and revert the changes to the manpage? They should be generated automagically (or partially manually during the release process). Then this should be 🚀

**Review by waynew — APPROVED** [review]
🚀

**Comment by jasperla** [comment]
re-run macos

**Comment by jasperla** [comment]
Let's close this, I have lost all interest so it's not fair to keep this open any longer.

**Pull request closed without merging**
