### PR TITLE
Allow proxy minions to load static grains

### PR DESCRIPTION
**Pull request by mirceaulinic**
### What does this PR do?

Add the `__proxyenabled__` global var so the extra grains are loaded.
Inside the `config` function of the extra grains check if the minion
is a proxy, then try loading from `<conf_file>/proxy.d/<proxy id>/grains`.

### What issues does this PR fix or reference?

#42074

### Previous Behavior

Unable to configure static grains on Proxy Minions.

### New Behavior

Can configure static grains on Proxy Minions.

### Tests written?

No.

### Commits signed with GPG?

Yes.

### CODE REVIEW

**Review by gtmanfred — APPROVED** [review]

**Comment by gtmanfred** [comment]
Thanks @mirceaulinic !
Daniel

**Comment by rallytime** [comment]
I know this is a relatively simple addition, but you would mind moving this to `develop` @mirceaulinic? A note about how this works in the Oxygen release notes would be great as well after it is moved over.

**Comment by mirceaulinic** [comment]
Hi @rallytime - https://docs.saltstack.com/en/latest/topics/grains/#grains-in-etc-salt-grains states something that doesn't work, which in my opinion is a bug. I'm not sure why we'd like to postpone a bug in a feature request - I can see a trend to move everything into the develop branch, but I always had the feeling that dot releases are to tackle this kind of discrepancy between what you expect and what actually happens.
But if you believe that's the best way, feel free to change the target branch.

**Comment by wasabi222** [comment]
I recently ran into this issue trying to set grains as well, following the documentation on the grains page. This would be great if it could go into the next dot release!

**Comment by rallytime** [comment]
@mirceaulinic Thank you for the explanation. That makes sense. It looked like a new feature to me. :) 

We are trying to keep things as stable as possible in the dot releases, which means moving all features, refactors, or large changes to `develop`, which is probably why you're seeing "move to develop" comments. We want to keep fixing things in the dot releases, certainly. Thank you again for all of your hard work.

**Review by rallytime — APPROVED** [review]

**Comment by mirceaulinic** [comment]
Sure, makes sense @rallytime - that was my fault I didn't explain this properly. Thanks!

**Pull request merged**
