### PR TITLE
Add __all__ attribute to Mock class for docs

### PR DESCRIPTION
**Pull request by whiteinge**

### CODE REVIEW

**Comment by jfindlay** [comment]
Fixes #23916.

**Comment by nmadhok** [comment]
@whiteinge @jfindlay After applying this fix, the docs build but I get the following message:

```
Failed to import 'salt.modules.ps': no module named salt.modules.ps
```

**Comment by nmadhok** [comment]
@whiteinge @jfindlay After applying this fix, the docs do get built but I get the following message:

```
Failed to import 'salt.modules.ps': no module named salt.modules.ps
WARNING: [autosummary] failed to import u'salt.modules.ps': no module named salt.modules.ps
```
& the following traceback:
```
reading sources... [100%] ref/modules/all/salt.modules.ps                                                                                                                            
/root/salt/doc/ref/modules/all/salt.modules.ps.rst:11: WARNING: autodoc: failed to import module u'salt.modules.ps'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/root/salt/salt/modules/ps.py", line 25, in <module>
    PSUTIL2 = psutil.version_info >= (2, 0)
AttributeError: 'module' object has no attribute 'version_info'
```

Full build:
```
sphinx-build -b html -d _build/doctrees    . _build/html
Running Sphinx v1.3.1
loading translations [en]... done
loading pickled environment... done
[autosummary] generating autosummary for: contents-1.rst, contents-2.rst, contents-3.rst, contents-4.rst, contents.rst, faq.rst, glossary.rst, index.rst, ref/auth/all/index.rst, ref/auth/all/salt.auth.auto.rst, ..., topics/tutorials/walkthrough.rst, topics/tutorials/walkthrough_macosx.rst, topics/tutorials/writing_tests.rst, topics/virt/disk.rst, topics/virt/index.rst, topics/virt/nic.rst, topics/windows/index.rst, topics/windows/windows-package-manager.rst, topics/windows/windows-specific-behavior.rst, topics/yaml/index.rst
Failed to import 'salt.modules.ps': no module named salt.modules.ps
WARNING: [autosummary] failed to import u'salt.modules.ps': no module named salt.modules.ps
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 3 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] ref/modules/all/salt.modules.ps                                                                                                                            
/root/salt/doc/ref/modules/all/salt.modules.ps.rst:11: WARNING: autodoc: failed to import module u'salt.modules.ps'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/root/salt/salt/modules/ps.py", line 25, in <module>
    PSUTIL2 = psutil.version_info >= (2, 0)
AttributeError: 'module' object has no attribute 'version_info'
looking for now-outdated files... 47 found
pickling environment... done
```

**Comment by jfindlay** [comment]
I'm going to merge this, and we can work out the other issues in further fixes.

**Pull request merged**
