### PR TITLE
Adding options to Jenkins pipline builds

### PR DESCRIPTION
**Pull request by dubb-b**
### What does this PR do?
This adds timestamps and ansi Color output to the Jenkins Jobs

### New Behavior
This will add timestamps and color to the Job Console output.

### Tests written?

No

### Commits signed with GPG?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by gtmanfred** [comment]
This doesn't look like it has exposed any color in the pylint commands.

The success is still grey.

**Comment by dubb-b** [comment]
@gtmanfred Yeah we will need to code up a bunch of color to the pipelines. If the program we are executing doesn't support color we cannot really control that, I think. We probably need to add the environment variable for Python, not sure on things like pylint, tox, or others yet.

**Comment by gtmanfred** [comment]
screen shot 2018-07-17 at 2 00 20 pm

It isn't having any problem output colors for me in my terminal, so i am not sure that this PR does anything.

**Comment by dubb-b** [comment]
It still is adding timestamps, we can add more to the ansi colors later on.
No harm in keeping it there.

**Pull request merged**
