### PR TITLE
Backport #19165 and #21920 to 2014.7

### PR DESCRIPTION
**Pull request by rallytime**
Backport #19165 and #21920 to 2014.7

The optimizations in the nested outputter needed the `color_theme` additions in order to backport the optimizations to 2014.7. Let's see how the tests do here.

### CODE REVIEW

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jacksontj** [comment]
@rallytime are you going to open a PR for 2015.2 as well?

**Comment by rallytime** [comment]
BAH. This isn't working at all. I was hoping that the additional backport of would take care of these testing issues. I'll have to come back around here again.

@jacksontj Once I can figure out what is going on here (I was hoping it would be easier), and this gets merged, it should be merged forward to 2015.2. I tried backporting this just to 2015.2 earlier (to see if the merge conflicts were less) but the problems looked remarkably the same.

**Comment by jacksontj** [comment]
I *think* the interfaces are the same in all of these versions so you might be better off trying a straight up copy onto this branch and see what all breaks ;)

**Comment by rallytime** [comment]
Wait a second...I think I was looking at something different before - I thought I saw the tests being all sad and had failed/bailed out. Now they're running again.

**Comment by rallytime** [comment]
Ok, hopefully #21962 will work better here instead of this one.

**Pull request closed without merging**
