### PR TITLE
split return key value correctly

### PR DESCRIPTION
**Pull request by gtmanfred**
### What does this PR do?
Using the old way, it could split on something that happens to have | in the name for things like cmd.run or something else

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by rallytime** [comment]
Can you write a test for this? We wouldn't want that to regress,

**Comment by gtmanfred** [comment]
Can do.

**Comment by gtmanfred** [comment]
test added

**Comment by gtmanfred** [comment]
re-run all

**Comment by rallytime** [comment]
@gtmanfred Lint: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/19981/violations/file/tests/unit/returners/test_highstate_return.py/

**Review by rallytime — APPROVED** [review]

**Pull request merged**
