### PR TITLE
Merge branch '2014.7' into 2015.2

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by thatch45** [comment]
Lets get these brew tests fixed on 2015.2

**Comment by s0undt3ch** [comment]
This PR does fix the brew tests on 2015.2... Were you referring to another branch?

**Comment by s0undt3ch** [comment]
The remaining test to fix is that local SLS test. I'll try to fix it tonight...

**Comment by thatch45** [comment]
yes, I might have :)

**Pull request merged**
