### PR TITLE
add support for PillarStack ext_pillar

### PR DESCRIPTION
**Pull request by bbinet**
as discussed on the mailing list with @whiteinge, I propose to include the PillarStack ext_pillar in salt itself to make it directly available (no installation required)

https://github.com/bbinet/pillarstack

### CODE REVIEW

**Comment by jfindlay** [comment]
@bbinet, there are some [lint errors](https://jenkins.saltstack.com/job/salt-pr-lint-n/7230/violations/file/salt/pillar/stack.py/).

**Comment by bechtoldt** [comment]
@bbinet cool thing, can we have some tests so it won't break after the next Salt release and keeps its expected behaviour? :)

**Comment by whiteinge** [comment]
Awesome! @bbinet thanks for sending it in. Ping us if you want help tracking down the lint errors. (Hint: they're buried under the "Violations" link in the Jenkins sidebar.) The test failures are unrelated and can be ignored.

**Comment by bbinet** [comment]
@bechtoldt I'm not used to writing tests for salt, but as soon as the `ext_pillar` interface compatibility is maintained in salt future releases, it should not break.
I may add some internal tests to the https://github.com/bbinet/pillarstack repository in the future, but I don't have time right now.

**Comment by bbinet** [comment]
lint errors are now fixed

**Comment by whiteinge** [comment]
Cool. Thanks for the addition!

**Comment by DanyC97** [comment]
Under which version will this merge be available ?

thx

**Comment by whiteinge** [comment]
Looks like it will be in the Boron release (the release after 2015.8).

If you don't want to wait you can grab the module off GitHub and toss it on your master:

1. Edit the master config: `extension_modules: /srv/modules`
2. `mkdir -p /srv/modules/pillar`
3. Put the `stack.py` file in that directory.

**Comment by vr-jack** [comment]
Might I suggest that some of this functionality can be included inside core pillar? Primarily, providing jinja access to already imported/merged pillar data without the need to import_yaml everything. The only exception then would be top.sls, which reprocessing top after every pillar import might be construed as obsessive and would still leave this module as useful.

**Pull request merged**
