### PR TITLE
Don't call os.getppid() on Windows

### LINKED ISSUE #33927: Salt - windows minion cannot do anything
### Description of Issue/Question

all salt interaction bring this errors on windows 7 (64)

let me know what info you need to investigate this

C:\salt>salt-minion restart
[INFO    ] Setting up the Salt Minion "phil"
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'module' object has no attribute 'getppid'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 112, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 344, in start
    super(Minion, self).start()
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 932, in start
    self.prepare()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 307, in prepare
    if self.check_running():
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 915, in check_running
    if self.check_pidfile() and self.is_daemonized(pid) and not os.getppid() == pid:
AttributeError: 'module' object has no attribute 'getppid'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-minion", line 26, in <module>
    salt_minion()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 112, in salt_minion
    minion.start()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 344, in start
    super(Minion, self).start()
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 932, in start
    self.prepare()
  File "C:\salt\bin\lib\site-packages\salt\cli\daemons.py", line 307, in prepare
    if self.check_running():
  File "C:\salt\bin\lib\site-packages\salt\utils\parsers.py", line 915, in check_running
    if self.check_pidfile() and self.is_daemonized(pid) and not os.getppid() == pid:
AttributeError: 'module' object has no attribute 'getppid'

### Setup
steps : https://docs.saltstack.com/en/latest/topics/installation/windows.html

### Steps to Reproduce Issue
steps : https://docs.saltstack.com/en/latest/topics/installation/windows.html

### Versions Report
...

### PR DESCRIPTION
**Pull request by cachedout**
Fixes #33927

@twangboy Can you verify this works correctly on Windows, please?

### CODE REVIEW

**Comment by twangboy** [comment]
I thought we already fixed this on develop. I added a salt util that added
that functionality.

**Comment by cachedout** [comment]
Why would we fix this on develop when it's a bug in 2016.3?

**Comment by twangboy** [comment]
It was fixed to get the master running on Windows.

**Comment by cachedout** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cachedout** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cachedout** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cachedout** [comment]
@twangboy Can you please point me to your PR which addresses this? It would probably be best just to pull in the pieces of that which address this issue so that we don't end up with merge conflicts.

**Comment by twangboy** [comment]
@cachedout https://github.com/saltstack/salt/pull/33062

**Pull request merged**
