### PR TITLE
smartos.vm_present could not handle nics with vrrp_vrid property

### PR DESCRIPTION
**Pull request by sjorge**
### What does this PR do?
SmartOS will automatically calculate (and override) the mac property of any nics that have `vrrp_vrid` property set.

This causes a lot of issues:
- we keep trying to add a new nic if the mac that was provided is incorrect
- we keep trying to delete the existing nic with the mac based on the vrid
- we keep trying to incorrect update a nic if the vrid was change (cannot be update, remove and add new nic)

### What issues does this PR fix or reference?
n/a

### Previous Behavior
We would try to add/remove/update the incorrect nic when `vrrp_vrid` property was present making the state module fail.

### New Behavior
We now account for this in `_parse_vmconfig()`, this function is used to map unique identifiers for various smartos resource types (nics, disks, ...)

We will use the provided mac address from the resource key **unless* the `vrrp_vrid` property is present, then generate the mac based on the provided vrid.

This results in the nic being correctly added, when the vrid is changes this results in a remove of the old nic and adding of the new nic as is expected by vmadm.

### Tests written?
Yes, I've added tests to test the mac handling of `_parse_vmconfig()`

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by sjorge** [comment]
Tests are working local, but that was with py3... will look into py2

**Comment by sjorge** [comment]
Interesting, the order is different between versions!

python3:
```
00:00:5e:00:01:01
00:00:5e:00:01:f0
00:22:06:00:00:01
```

```OrderedDict([('nics', [OrderedDict([('vrrp_vrid', 1), ('vrrp_primary_ip', '12.34.5.6'), ('mac', '00:00:5e:00:01:01')]), OrderedDict([('vrrp_vrid', 240), ('vrrp_primary_ip', '12.34.5.6'), ('mac', '00:00:5e:00:01:f0')]), OrderedDict([('ips', ['12.34.5.6/24']), ('mac', '00:22:06:00:00:01')])])])```

python2
```
00:22:06:00:00:01
00:00:5e:00:01:01
00:00:5e:00:01:f0
```

```OrderedDict([(u'nics', [OrderedDict([(u'ips', [u'12.34.5.6/24']), (u'mac', u'00:22:06:00:00:01')]), OrderedDict([(u'vrrp_vrid', 1), (u'vrrp_primary_ip', u'12.34.5.6'), (u'mac', u'00:00:5e:00:01:01')]), OrderedDict([(u'vrrp_vrid', 240), (u'vrrp_primary_ip', u'12.34.5.6'), (u'mac', u'00:00:5e:00:01:f0')])])])```

This is very weird, because the input is also an ordereddict and the order should not change, as we see on python3... I am unsure why it is changing on python2...

@Ch3LL any ideas? Have you seen this before?

**Comment by sjorge** [comment]
I can change the tests and call the function 3 times with a seperate ret object to test... as the order is not important for this test... but I do believe OrderedDict might be broken?

**Comment by sjorge** [comment]
nvm, I am dumb as a rock and incorrectly create the OrderedDict.

**Comment by sjorge** [comment]
Current test failures look to be for different modules?

**Review by Ch3LL — APPROVED** [review]

**Review by cmcmarrow — APPROVED** [review]

**Comment by sjorge** [comment]
@Ch3LL bump

**Pull request merged**
