### PR TITLE
Allow file_map in salt-cloud to handle folders.

### PR DESCRIPTION
**Pull request by ericfode**
Logic has been added to sftp_file and the file_map decoder for salt-cloud allowing you to list folders as well as files in file_map.

The use case was seeding the /srv directory and /etc/salt directory on a salt master that is isolated.

### CODE REVIEW

**Comment by rallytime** [comment]
Thanks @ericfode! Mind grabbing the pylint errors here? https://jenkins.saltstack.com/job/salt-pr-lint-n/5012/violations/

Also, does this fix a bug in an earlier release branch such as 2014.7 or 2015.2? I am wondering if you think this fix should be applied there. We can backport it easily.

**Comment by ericfode** [comment]
I think it should be backported if possible. Thanks for the quick response! (also fixed the linting).

**Comment by rallytime** [comment]
Sure! For future fixes, please feel free to submit the fix directly to the "oldest release branch" that the fix applies to. We merge branches forward, so it's easy to make sure the fix applies to all relevant branches. There's some more info about that [here](http://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch)

Don't worry about this one, though. I will be happy to backport it. Thanks again for the fix!

**Comment by ericfode** [comment]
@rallytime Thank you so much! you guys are a pleasure to work with.

**Comment by techhat** [comment]
@ericfode, +1 on this!

**Comment by rallytime** [comment]
@ericfode No problem! Thanks again for this excellent fix!

**Comment by nmadhok** [comment]
@ericfode +1

**Pull request merged**
