### PR TITLE
Fix AttributeError: module 'salt.config' has no attribute '_DFLT_LOG_FMT_JID'

### PR DESCRIPTION
**Pull request by bdrung**
```
$ python3 -m pytest -ra tests/pytests/integration/_logging/test_jid_logging.py
_______________________________ test_jid_in_logs _______________________________

    @PRE_PYTEST_SKIP
    def test_jid_in_logs(caplog, salt_call_cli):
        """
        Test JID in log_format
        """
>       jid_formatted_str = salt.config._DFLT_LOG_FMT_JID.split("%")[0]
E       AttributeError: module 'salt.config' has no attribute '_DFLT_LOG_FMT_JID'

tests/pytests/integration/_logging/test_jid_logging.py:15: AttributeError
```

Commit a9d5e75b528b711412b8fa30eb61c54413a254e9 changed the private variable to a public one.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Hmm, why didn't we catch this sooner.....

**Comment by s0undt3ch** [comment]
Ah, yes, it's being skipped.

**Review by s0undt3ch — CHANGES_REQUESTED** [review]
```python
import logging

from salt._logging import DFLT_LOG_FMT_JID


def test_jid_in_logs(caplog, salt_call_cli):
    """
    Test JID in log_format
    """
    jid_formatted_str = DFLT_LOG_FMT_JID.split("%")[0]
    formatter = logging.Formatter(fmt="%(jid)s %(message)s")
    with caplog.at_level(logging.DEBUG):
        previous_formatter = caplog.handler.formatter
        try:
            caplog.handler.setFormatter(formatter)
            ret = salt_call_cli.run("test.ping")
            assert ret.exitcode == 0
            assert ret.json is True

            assert_error_msg = (
                "'{}' not found in log messages:\n>>>>>>>>>{}\n<<<<<<<<<".format(
                    jid_formatted_str, caplog.text
                )
            )
            assert jid_formatted_str in caplog.text, assert_error_msg
        finally:
            caplog.handler.setFormatter(previous_formatter)
```
Since you're making this change, let's import from the right package and unskip the test, please.

**Comment by bdrung** [comment]
Done. The test took 0:02:43.

**Comment by Ch3LL** [comment]
@s0undt3ch can you re-review please

**Review by s0undt3ch — DISMISSED** [review]

**Comment by s0undt3ch** [comment]
Test failures do look related though.

**Comment by Ch3LL** [comment]
@bdrung can you resolve the test failures?

**Comment by twangboy** [comment]
Looks like the test failures are related

**Comment by bdrung** [comment]
Then let's keep the test case disabled and leave it to a later merge request to actual fix the test case.

**Review by twangboy — CHANGES_REQUESTED** [review]
This needs a changelog and a testcase

**Review by s0undt3ch — APPROVED** [review]

**Comment by s0undt3ch** [comment]
Removed the needs test case label. There are tests already, though, being slipped.

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
