### PR TITLE
Fix broken lookup in salt/utils/dns.py

### PR DESCRIPTION
**Pull request by yosnoop**
### What does this PR do?
Fix _lookup_ function in salt/utils/dns.py.

### What issues does this PR fix or reference?
#51249

### Previous Behavior
1. the __multi_srvr_ recursively called since _resolver_ in the function points to __multi_srvr_ and causes the following error.
`Passed invalid arguments: _multi_srvr() got multiple values for keyword argument 'server'.`
2. method _host_ fails to query the resolver when the _servers_ argument specified.

### New Behavior
1. instead of pointing the _resolver_ to _multi_srvr, it now generates wrapper functions and assign that to _resolver_.
2. _host_ properly specifies the resolver to query.

### Tests written?
Work in progress.

### Commits signed with GPG?
Yes.

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by dwoz — CHANGES_REQUESTED** [review]
@yosnoop Would you mind writing a regression test for `salt.utils.dns.lookup`?

**Comment by yosnoop** [comment]
@dwoz Let me try! :)

**Comment by yosnoop** [comment]
@dwoz I wrote a test for `salt.utils.dns.lookup`. Could you take a look?

**Comment by dwoz** [comment]
@yosnoop Looks good, thanks!

**Pull request merged**
