### PR TITLE
Fixed duplicate mtu entry in RedHat 7  network configuration.

### PR DESCRIPTION
**Pull request by abednarik**
Removed duplicate mtu entry in jinja template for RedHat 7 Systems.

This will fix issue #29598

### CODE REVIEW

**Comment by cachedout** [comment]
@abednarik This will not merge cleanly. Would you mind rebasing it, please?

**Comment by abednarik** [comment]
Will do.

**Comment by cachedout** [comment]
Thanks for the quick repsonse!

**Comment by abednarik** [comment]
HI @cachedout  hope now is fine.

This was really weird, but now should be fine.

**Comment by cachedout** [comment]
Looks good now. Thanks!

**Comment by abednarik** [comment]
Thanks.

**Pull request merged**
