### PR TITLE
[2017.7] Ensure failed tags are added to self.pre

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Ensure failed tags are added to self.pre.

### What issues does this PR fix or reference?
#46762 

### Tests written?
Not yet.

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by gtmanfred** [comment]
re-run py2

**Comment by gtmanfred** [comment]
re-run py2

**Review by thatch45 — APPROVED** [review]
This makes perfect sense for the bug in question

**Comment by garethgreenaway** [comment]
Still need to add a test before this is merged.

**Comment by cachedout** [comment]
Oops. Can you get that test in a follow-up?

**Comment by garethgreenaway** [comment]
Will do.

**Pull request merged**
