### PR TITLE
Initial grafana state and elasticache execution modules

### PR DESCRIPTION
**Pull request by ryan-lane**
This state/execution module combo is for managing elasticsearch backed grafana dashboards. It manages rows and panels and will create dashboards if they don't exist, but only manages the specified rows and panels. It will not modify existing dashboards or unmanaged rows. This allows you to have control over your dashboards while still having managed portions.

### CODE REVIEW

**Comment by techhat** [comment]
@ryan-lane, could I get you to add some CLI Examples to the execution module? Also, if you could add a docstring to `_parse_profile()` in the state, it would be most appreciated.

**Comment by ryan-lane** [comment]
Can this be backported to 2015.2? It's a new module add and would be nice for the release :).

**Comment by techhat** [comment]
Ping @rallytime.

**Comment by rallytime** [comment]
Yep! Done!

**Pull request merged**
