### PR TITLE
Add NetBox execution module

### PR DESCRIPTION
**Pull request by zachmoody**
### What does this PR do?
Adds an execution module for querying [Netbox](http://github.com/digitalocean/netbox).

### What issues does this PR fix or reference?
None

### New Behavior
Allows Salt to query NetBox's API.

### Tests written?

Yes

### Commits signed with GPG?

No

### CODE REVIEW

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
Thank you for submitting this @zachmoody and with tests! 👍 

Welcome and congrats on your first Salt PR. :)

Unfortunately, the tests results expired before I had a chance to review them, so I've restarted them so we can see some new results.

**Comment by rallytime** [comment]
Hi @zachmoody can you fix up the lint error? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/16684/violations/file/tests/unit/modules/test_netbox.py/

**Comment by zachmoody** [comment]
👋  @rallytime - sure thing, just pushed them, hope that's what you were looking for.

**Comment by rallytime** [comment]
re-run docs

**Comment by rallytime** [comment]
re-run ubuntu

**Comment by garethgreenaway** [comment]
re-run ubuntu

**Pull request merged**
