### PR TITLE
Fix indentation, whitespace, and remove duplicate example

### PR DESCRIPTION
**Pull request by rjc**
### What does this PR do?

- fixes indentation in one of the examples
- separates two example states with a blank new line
- removes identical duplicate example

### Merge requirements satisfied?
- [x] Docs

### Commits signed with GPG?
No

### CODE REVIEW

**Review by Ch3LL — CHANGES_REQUESTED** [review]
looks like there is a pre-commit failure that needs to be cleaned up.

**Comment by Ch3LL** [comment]
That pre-commit hook is part of our effort to convert our python2 code to python3 at a slower pace rather than one massive PR. You should be able to apply the diff in the error output of the tests to your branch and push it up. Or you can run pre-commit and it should apply the changes for you.

**Comment by rjc** [comment]
As requested - I ran `pre-commit`. I had to remove `six` manually as another check was failing.

While we're at checks/tests, one doesn't run at all:

```
[...]
Collecting pyinotify==0.9.6
  Using cached pyinotify-0.9.6.tar.gz (60 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/rjc/.cache/pre-commit/repoq27cvmrc/py_env-python3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0hv5i53n/pyinoti
fyfy_aa45717690c24626a69d1432ffd0ccf1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0hv5i53n/pyinotify_aa45717690c24626a69d1432ffd0ccf1/setup.py'"'"';f = getattr(tokenize, '"'"'op
en'"'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.cl
ose(ec);exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-nuoxr82c
         cwd: /tmp/pip-install-0hv5i53n/pyinotify_aa45717690c24626a69d1432ffd0ccf1/
    Complete output (1 lines):
    inotify is not available on openbsd-6.9-amd64
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e3/c0/fd5b18dde17c1249658521f69598f3252f11d9d7a980c5be8619970646e1/pyinotify-0.9.6.tar.gz#sha256=9c998a5d7606ca835065cd
ababc013ae6c66eb9ea76a00a1e3bc6e0cfe2b4f71f4 (from https://pypi.org/simple/pyinotify/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full co
mmd and output.
ERROR: Could not find a version that satisfies the requirement pyinotify==0.9.6 (from versions: 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6)
ERROR: No matching distribution found for pyinotify==0.9.6
nox > Session lint-salt-pre-commit failed.
```

This is self-explanatory... Where do I report it? As in, "please don't run checks, which rely in inotify on `$(uname -s) != Linux`".

**Comment by Ch3LL** [comment]
ping @s0undt3ch do you know where this ^ needs to be reported.

**Comment by rjc** [comment]
Hi @s0undt3ch,

Thanks for a quick reply. Here it is:
```
$ python3.8 ./openbsd.py 
{'os.name': 'posix',
 'platform.machine': 'amd64',
 'platform.python_version': '3.8.8',
 'platform.release': '6.9',
 'platform.system': 'OpenBSD',
 'platform.version': 'GENERIC.MP#28',
 'sys.platform': 'openbsd6'}
```

**Review by rjc — COMMENTED** [review]
In terms of the PR itself, Is there anything else I need to do here?

**Review by Ch3LL — APPROVED** [review]

**Comment by Ch3LL** [comment]
nothing more you need to do for hte PR itself. Thanks for fixing that up and I just need 2 more reviews and we will get this merged in.

**Review by s0undt3ch — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Review by krionbsd — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
