### PR TITLE
Restructure git.latest rewrite to work better when following HEAD

### PR DESCRIPTION
**Pull request by terminalmage**
@anlutro, could you check out this PR and test to see if it solves the issue
you raised yesterday?

### CODE REVIEW

**Comment by terminalmage** [comment]
To check out this PR, use the following commands

```
git fetch upstream "pull/26678/head:pr-26678"
git checkout pr-26678
```

This assumes you have the main saltstack/salt repository configured as a git remote named "upstream", replace "upstream" with whatever you're using if that is not the case.

**Comment by basepi** [comment]
[Lint](https://jenkins.saltstack.com/job/salt-pr-lint-n/8796/violations/file/salt/states/git.py/)

**Comment by anlutro** [comment]
@terminalmage Seems to work. Only issue I can see is that in test mode, git repositories that are at the latest revision show up as having changes (probably just a matter of returning `True` instead of `None`).

**Comment by terminalmage** [comment]
@anlutro weird, it doesn't do that for me. Are you still leaving off the ``rev`` param (i.e. letting it follow "HEAD")?

**Comment by anlutro** [comment]
Whether I provide the rev argument or not doesn't seem to have an effect on the test result. It always returns `None` which signalises a change.

**Comment by terminalmage** [comment]
Returning ``None`` doesn't signify a change, it is expected when ``test=True``.

Are you referring to there being changes shown below (such as old/new revision)? We do include changes in ``test=True`` output, but those are the *expected* changes, and are used to facilitate [prereq requisites](http://docs.saltstack.com/en/latest/ref/states/requisites.html#prereq).

Can you post example state output so I can better understand what you're experiencing?

If an up-to-date repo is still showing expected changes, this is something we should look at. Is the repo with which you're testing public? If so, please post the SLS and I'll take a look.

**Comment by anlutro** [comment]
@terminalmage see https://github.com/saltstack/salt/blob/develop/doc/ref/states/writing.rst#return-data

In test mode, True indicates no changes, None indicates changes with unknown results.

Here's some sample output:

```
$ salt-ssh odin state.apply git.repos test=True
odin:
----------
          ID: git-repo-/home/andreas/dotfiles
    Function: git.latest
        Name: https://github.com/anlutro/dotfiles.git
      Result: None
     Comment: 
     Started: 07:05:39.458484
    Duration: 810.573 ms
     Changes:   
----------
          ID: git-repo-/home/andreas/git/ircbot.git-deploy-/home/andreas/scripts/ircbot
    Function: git.latest
        Name: /home/andreas/git/ircbot.git
      Result: None
     Comment: 
     Started: 07:05:40.273021
    Duration: 370.709 ms
     Changes:   
----------
          ID: git-repo-/home/andreas/git/qdb.git-deploy-/var/www/qdb
    Function: git.latest
        Name: /home/andreas/git/qdb.git
      Result: None
     Comment: 
     Started: 07:05:40.661029
    Duration: 301.415 ms
     Changes:   

Summary for odin
-------------
Succeeded: 22 (unchanged=3)
Failed:     0
-------------
Total states run:     22
Total run time:    1.957 s

$ salt-ssh odin state.apply git.repos
odin:

Summary for odin
-------------
Succeeded: 22
Failed:     0
-------------
Total states run:     22
Total run time:    2.070 s

**Comment by terminalmage** [comment]
Ah! So, before this PR, the code would return a ``True`` result earlier because all it cared about was whether or not the local SHA1 matches the remote SHA1. However, part of the restructuring I did in this PR removed that SHA1 check because the state was ignoring the other things it manages (the remote name, the tracking branch, etc.), and I wanted it to be able to update these things when the SHA1s matched. However, this means that the up-to-date check came further down than the ``test=True`` check.

I fixed this by checking the changes dict and returning a ``True`` result when it is empty.

Can you update your copy of this PR and test again?

**Comment by anlutro** [comment]
Seems to work fine now!

**Comment by terminalmage** [comment]
Excellent. Could you also test some non-fast-forward changes? Thinks like changing the ``rev`` to point to a tag or a branch other than the one represented by the remote HEAD.

What you should see is a False result letting you know the update is not a fast-forward, and requiring you to pass ``- force_reset: True`` to proceed with the update. Adding this argument to the SLS should then allow the non-fast-forward change to proceed.

**Comment by anlutro** [comment]
I'll have to set up a test SLS with a dummy repo as none of the repositories I have states for have all of that, but I tried setting rev to a tag and it fails saying the tag doesn't exist:

```
$ salt-ssh intern01 state.apply php.satis
intern01:
----------
          ID: /var/www/satis
    Function: git.latest
        Name: https://github.com/composer/satis
      Result: False
     Comment: No revision matching '1.0.0-alpha1' exists in the remote repository
     Started: 08:26:19.457096
    Duration: 845.256 ms
     Changes:   
```

**Comment by anlutro** [comment]
Other than the tag, the fast-forward behavior seems to be working great.

**Comment by terminalmage** [comment]
OK, I'll give this a look... It worked for me but I didn't have any dots in the tags I tested (not sure why that would matter, or if that is even the issue).

Thanks very much for your assistance @anlutro, you've been great! I'll let you know what I find with the tag, but it's quite late here and I will have to resume this in the morning.

**Comment by terminalmage** [comment]
Ah! I decided to check one quick thing before going to bed, and the problem lies with the difference between annotated and non-annotated tags. I'll get a fix for this in when I wake up. Thanks again!

**Comment by anlutro** [comment]
Awesome :+1:

**Comment by terminalmage** [comment]
@anlutro I ended up having to stay up a bit longer and got those fixes in. Should work now.

**Comment by anlutro** [comment]
Works, indeed! I don't know how important it is, or if it's solvable, but when updating between a (non-annotated) tag and a branch (master), it doesn't specify the tag as the old/new upstream.

```
     Changes:   
              ----------
              revision:
                  ----------
                  new:
                      0dd53e18696aab506504c48932a77fcd71fffc19
                  old:
                      b20fd944ec40ad65c1e54bb0860fe844f4efd56e
              upstream:
                  ----------
                  new:
                      origin/master
                  old:
                      False
```

Similar when going the other way around:

```
     Changes:   
              ----------
              forced update:
                  True
              revision:
                  ----------
                  new:
                      b20fd944ec40ad65c1e54bb0860fe844f4efd56e
                  old:
                      0dd53e18696aab506504c48932a77fcd71fffc19
              upstream:
                  ----------
                  new:
                      None
                  old:
                      origin/master
```

**Comment by terminalmage** [comment]
@anlutro "upstream" here refers to the tracking branch. Tracking branches are only applicable when you have checked out a branch, so we unset them when following tags and SHA1s, and ignore them when following HEAD.

Would it be clearer if I changed the word "upstream" there to "tracking branch"?

**Comment by anlutro** [comment]
I see. Maybe, but "upstream" sounds just as correct to me.

**Comment by terminalmage** [comment]
"Upstream" is what was used before, so I just kept it. This likely came from the ``--set-upstream-to`` argument to ``git branch``.

If you think it's OK as is, then I think we're good to merge. Thanks again for helping me work out the bugs here @anlutro, you've been _very_ helpful.

**Pull request merged**
