### PR TITLE
clarifying the pillar_opts is configured on both master and minion.

### LINKED ISSUE #56116: docs clarification for pillar_opts configuration option
### Description of Issue
This [salt doc](https://docs.saltstack.com/en/latest/topics/tutorials/pillar.html#setting-up-pillar) has a section about the `pillar_opts` option for sharing the master config file as a pillar for the minions to see. It doesnt make it clear that there are actually two `pillar_opts` to be enabled/disabled. One is on the master and one is on the minion.

### relevant section
```
By default, the contents of the master configuration
file are not loaded into pillar for all minions. This 
default is stored in the pillar_opts setting, which 
defaults to False.

The contents of the master configuration file can 
be made available to minion pillar files. This makes 
global configuration of services and systems very 
easy, but note that this may not be desired or 
appropriate if sensitive data is stored in the master's 
configuration file. To enable the master configuration 
file to be available to a minion's pillar files, set 
pillar_opts to True in the minion configuration file.
```

### Recommended Solution
Just a clarification to explicitly state what `pillar_opts` toggle for master and `pillar_opts` toggle for minions accomplishes.

***
- beginner friendly
- issue for docs-working group
- single person task

### PR DESCRIPTION
**Pull request by alan-cugler**
### What does this PR do?
Rewrites the `pillar_opts` to specify that it exists and is used on both the minion and master configuration files.

### What issues does this PR fix or reference?
Fixes #56116

### Commits signed with GPG?
Yes

### Concerns
Its been a few weeks since I dealt with this issue, so let me know if this wording is also misleading or incorrect.

### CODE REVIEW

**Comment by alan-cugler** [comment]
This is what is looks like when rendered
pillar_opts

**Review by cmcmarrow — DISMISSED** [review]
Thanks @alan-cugler

**Comment by cmcmarrow** [comment]
Looks like ci/docs is failing for you. Because this is docs only you should need to worry about that other tests

**Comment by alan-cugler** [comment]
That docs error looks unrelated to this pull request? If I am correct we should make a new separate issue for it. If not correct, can you point out how my changes caused it please?

**Comment by bryceml** [comment]
merge requests into 2019.2 are not accepted, it is a CVE only branch now.  This should work correctly on master.

**Comment by alan-cugler** [comment]
Oh I thought we followed the two releases back for docs updates? maybe I am confused.

**Comment by dwoz** [comment]
Covered by #58599

**Pull request closed without merging**
