### PR TITLE
shell completion: test the correct cache for minions

### PR DESCRIPTION
**Pull request by llua**
fixed my copy paste for caching modules.

### CODE REVIEW

**Comment by jfindlay** [comment]
@llua, do you think this should go into 2014.7 or 2015.2?

**Comment by rallytime** [comment]
This is a fix for #21115, which went into develop. So if either of those PRs are backported, we need both of these.

**Comment by llua** [comment]
New contributor here (very ignorant of salt's development process), but i agree with @rallytime 's opinion.

**Comment by llua** [comment]
2014.7 is fine, I am not in much of a rush. Just scratching an itch.

**Pull request merged**
