### PR TITLE
Update docs for pass renderer

### PR DESCRIPTION
**Pull request by viq**
### What does this PR do?

Update docs for pass renderer, adding an example of how to use it.

### What issues does this PR fix or reference?
Supersedes #53286 because I don't know how to rebase properly.

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by viq** [comment]
I don't know why the test is failing, it's showing as changed lines that "view changes" here doesn't show as changed.

**Comment by waynew** [comment]
@viq I think I may have mentioned this in Slack, but basically the problem is with a pre-commit hook we have that checks/rewrites to remove python2-isms.

I went ahead and ran:

```
pre-commit run --files salt/renderers/pass.py
git add salt
git commit
```

which fixed the file, though it also broke it with the unused six import. So I removed that from the file and ran

```
git add salt
git commit
```

Then I went ahead and pushed the changes. Presumably everything will pass *now* :+1:

**Review by waynew — DISMISSED** [review]

**Comment by viq** [comment]
I saw your comment on slack, but not here, so I just did the same things locally ;D

**Comment by s0undt3ch** [comment]
There are too many changes in this PR, it needs to be rebased.

**Pull request closed without merging**
