### PR TITLE
Reformat ret correctly for returners

### PR DESCRIPTION
**Pull request by cachedout**

### CODE REVIEW

**Comment by cachedout** [comment]
cc: @pass-by-value

**Comment by pass-by-value** [comment]
:+1:

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
Every time the tests are (re)triggered, they [error out](https://jenkins.saltstack.com/job/salt-pr-rs-cent7-n/1712/consoleFull) here:
```
Waiting for minion, sub_minionBuild timed out (after 60 minutes). Marking the build as aborted.
```

I even submitted a new pull request Saturday after rebasing this change, but the result was the same.

**Comment by cachedout** [comment]
OK. I will investigate. Thanks @jfindlay

**Pull request closed without merging**
