### PR TITLE
Minion maintenance process

### PR DESCRIPTION
**Pull request by sbrennan4**
### What does this PR do?

This PR replaces the `grains_refresh_every` mechanism with a new sub-process that will manage the cache independently of the main salt-minion process. This process has been modeled after the maintenance process that runs on the master and could be extended with additional features if desired.

### Previous Behavior

Refreshing grains on the minion was a blocking process. This was causing sporadic timeouts for us when running jobs on some minions if that job initiated a grain refresh, particularly on Solaris minions.

### New Behavior

By turning on `grains_cache` and setting `grains_refresh_every` to a value less than `grains_cache_expiration`, the grains will be refreshed by a non-blocking process on a periodic basis. This way, the minion will never need to refresh its grains as part of a job initiated on the minion, which will prevent the timeouts seen as a result.

### Tests written?
**[NOTICE] Bug fixes or features added to Salt require tests.**
Please review the [test documentation](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html) for details on how to implement tests into Salt's test suite.

Yes

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by thatch45** [comment]
My concern here is making the minion run an additional process, this will double the latent memory use of the minion. We have avoided running multiple procs on the minion and when we have it has created serious problems for many deployments.
I would strongly discourage running an additional process like this on the minion

**Comment by sbrennan4** [comment]
@thatch45 thanks for your feedback. To avoid running a permanent process, how would you feel about adding the grains refresh to `self.periodic_callbacks` as a `MultiprocessingProcess`?

**Comment by thatch45** [comment]
I think that would be a better path. We might want to make it configurable

**Comment by thatch45** [comment]
I also think it should be configurable because most installs don't need this if there are specific grains that are taking too long to generate that should be considered a bug in the grain itself

**Comment by sbrennan4** [comment]
https://github.com/saltstack/salt/pull/56130

**Pull request closed without merging**
