### PR TITLE
pkgrepo Clean debian repo uri before checking if it's present.

### LINKED ISSUE #58807: [BUG] pkgrepo.managed keeps applying changes
**Description**
When a trailing slash is added to a repo's name, Salt keeps triggering a change.

OK: `deb http://ftp.ch.debian.org/debian bullseye main non-free contrib`
NOK: `deb http://ftp.ch.debian.org/debian/ bullseye main non-free contrib`

**Setup**
```
debian:
  pkgrepo.managed:
    - humanname: debian
    - name: deb http://ftp.ch.debian.org/{{ grains['os_family'].lower() }}/ bullseye main non-free contrib
    - file: /etc/apt/sources.list
    - gpgcheck: 1
```

**Steps to Reproduce the behavior**
run `state.apply`

**Expected behavior**
Once applied, it shouldn't be applied again upon next `state.apply`.

**Screenshots**
OK
```
local:

Summary for local
-------------
Succeeded: 62
Failed:     0
-------------
Total states run:     62
Total run time:    2.908 s
```
NOK:
```
local:
----------
          ID: debian
    Function: pkgrepo.managed
        Name: deb http://ftp.ch.debian.org/debian/ bullseye main non-free contrib
      Result: True
     Comment: Configured package repo 'deb http://ftp.ch.debian.org/debian/ bullseye main non-free contrib'
     Started: 12:34:11.800862
    Duration: 2483.958 ms
     Changes:
              ----------
              repo:
                  deb http://ftp.ch.debian.org/debian bullseye main non-free contrib
```

**Versions Report**
```
Salt Version:
           Salt: 3002

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.8.6 (default, Sep 25 2020, 09:36:53)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.3

System Versions:
           dist: debian testing bullseye
         locale: utf-8
        machine: x86_64
        release: 5.8.0-2-amd64
         system: Linux
        version: Debian GNU/Linux testing bullseye
```
</details>

**Additional context**
This was witnessed on both Bullseye and Buster.

### PR DESCRIPTION
**Pull request by Vaarlion**
### What issues does this PR fix or reference?
Fixes: #58807

### Previous Behavior
the code remove the trailing / from the URI after checking that the string in the file was the same as in the state.
So the applied state was never the same as the one checked, and the state would always return a change.

### New Behavior
check if the repo **without the tailing** space is already there first.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [X] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by Vaarlion** [comment]
I don't feel like the Error I am getting from the test are actual linked to my change. So i am making this ready once again.

**Comment by Vaarlion** [comment]
Hello @xeacott !
I know you must be busy, but with 3003 coming, i would really like to see this included.
Is it to late ? Salt bug-fix are usually for big stuff and I am afraid this will be push back to 3005 ...

Thank's!

**Review by Ch3LL — CHANGES_REQUESTED** [review]
This will require test coverage to ensure it does not regress.

**Comment by Vaarlion** [comment]
I need to find the time to learn more about how unit testing work before i can create a test like that.
It is a bit more involved than what i had to do before.

**Comment by Ch3LL** [comment]
Here is the test documentation: https://docs.saltproject.io/en/latest/topics/tutorials/writing_tests.html

And a good place to add a test would be here: tests/pytests/unit/states/test_pkgrepo.py

We also have a test clinic that occurs often as shown on the schedule here: https://www.twitch.tv/saltprojectoss/schedule  They can help you with writing a test there if needed as well, or I can help answer any further questions you may have.

**Comment by nicholasmhughes** [comment]
closing in favor of #61986

**Pull request closed without merging**
