### PR TITLE
MOAR beacons docs

### PR DESCRIPTION
**Pull request by thatch45**

### CODE REVIEW

**Comment by jfindlay** [comment]
Looks like all complete sentences; no unfinished anecdotes: great PR!

**Comment by thatch45** [comment]
Thanks, I have been known to leave docs in Salt for years that end with unfinished sentences :)

**Comment by UtahDave** [comment]
@thatch45 could you add a pretty printed example of a valid beacon return data structure? For my sake?  :)

**Comment by cachedout** [comment]
They're not unfinished. They're just very asynchronous.

**Comment by thatch45** [comment]
Can Haz @UtahDave

**Comment by UtahDave** [comment]
Awesome! Thanks, @thatch45 !

**Pull request merged**
