### PR TITLE
[master] Porting #52001 to master

### PR DESCRIPTION
**Pull request by garethgreenaway**
Porting #52001 to master

### CODE REVIEW

**Comment by max-arnold** [comment]
@garethgreenaway I'm not 100% sure, but maybe there is no need to merge this. PR #53167 (unmerged) makes this backport unnecessary: https://github.com/saltstack/salt/pull/53167#issuecomment-497920055

In other words, #52001 was obsoleted by #53167

/CC @aplanas

**Comment by aplanas** [comment]
@max-arnold That is right, there is a pending PR to develop. IIUC this is to master. I am fine to closing the one to develop in favor of this one, or I can rebase all my patches on top of master, instead of develop.

How is the transition designed? Is there something that I can do to help from my side?

**Comment by waynew** [comment]
@aplanas if you'd like to rebase your PR against master that would be 💯 

We are planning to migrate all the PRs as we can, but if authors can handle the rebasing themselves that's much preferred (and will make things go much quicker!)

**Comment by waynew** [comment]
Closing this PR in favor of #53167

**Pull request closed without merging**
