### PR TITLE
SaltSSH: fix delay when creating thin TAR

### PR DESCRIPTION
**Pull request by isbm**
### What does this PR do?

Integration bugfix.

### What issues does this PR fix or reference?

Thin generation is not atomic. If command is issued to re-generate `thin.tgz` and other command in parallel is using it already via e.g. API, you get the following:

```
2018-05-14 14:27:38,544 [ajp-apr-127.0.0.1-8009-exec-4] ERROR com.suse.manager.webui.controllers.utils.AbstractMinionBootstrapper - Error during bootstrap: Traceback (most recent call last):
  File "<string>", line 149, in <module>
  File "<string>", line 255, in <module>
  File "<string>", line 156, in main
  File "<string>", line 117, in unpack_thin
  File "/usr/lib64/python2.7/tarfile.py", line 2064, in extractall
    for tarinfo in members:
  File "/usr/lib64/python2.7/tarfile.py", line 2494, in next
    tarinfo = self.tarfile.next()
  File "/usr/lib64/python2.7/tarfile.py", line 2342, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib64/python2.7/tarfile.py", line 1244, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/usr/lib64/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib64/python2.7/gzip.py", line 303, in _read
    self._read_gzip_header()
  File "/usr/lib64/python2.7/gzip.py", line 197, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file
```
The problem is solved, if `thin.tgz` is created in a temporary file, then copied over in one go.

### CODE REVIEW

**Comment by isbm** [comment]
@Ch3LL @dwoz take a look please.

**Comment by mantel** [comment]
Great catch! And explains nicely why this one cannot be reliably reproduced!

**Review by dwoz — APPROVED** [review]

**Comment by dwoz** [comment]
@isbm Looks like these are related to this change: https://jenkinsci.saltstack.com/job/pr-kitchen-centos7-py2/job/PR-51561/2/

**Review by brejoc — APPROVED** [review]
Apart from the failing tests, this lgtm.

**Comment by isbm** [comment]
@dwoz should be probably good now.

**Comment by isbm** [comment]
@dwoz forgot about py2. Now seems Ok finally.

**Pull request merged**
