### PR TITLE
Batch ckminions

### PR DESCRIPTION
**Pull request by cachedout**
Refs #18358

### CODE REVIEW

**Comment by thatch45** [comment]
@cachedout these test failures seem to be related

**Comment by cachedout** [comment]
Gah. Will fix!

**Comment by cachedout** [comment]
OK, that should do it.

**Comment by thatch45** [comment]
Still broken?

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Shouldn't be broken. At least it passed on my machine. (Famous last words!)

**Comment by thatch45** [comment]
The failures are due to the transport key not being in opts, which is unrelated, and very odd

**Pull request merged**
