### PR TITLE
Add ability to specify a custom SSL certificate or disable SSL verification in KeystoneAuth v3

### PR DESCRIPTION
**Pull request by Enquier**
### What does this PR do?
Adds support for specifying a verification certificate when using Keystone v3 auth in the Nova driver

### What issues does this PR fix or reference?
#37824
@gtmanfred 

### Previous Behavior
If the SSL certificate is not automatically available a connection could not be made to the OpenStack Server

### New Behavior
User can now either specify a SSL Verification certificate or set verification to false (default=True)

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Review by gtmanfred — APPROVED** [review]

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by Enquier** [comment]
I went in and fixed the pylint errors

**Comment by Enquier** [comment]
@gtmanfred I had to pull #37696 out of my branch will it be pulled into 2016.11 at some point?

**Comment by gtmanfred** [comment]
I tagged it to be backported to 2016.11

**Pull request merged**
