### PR TITLE
Fix pillar include regression

### LINKED ISSUE #52134: Regression: Include list of pillar files under different keys in 2019.2
### Description of Issue/Question

When including different pillar files under different keys, the content of each file should be available under the specific key. After upgrading from 2018.3 to 2019.2 the content of the included files gets included under the last defined key. 
This behaviour affects the python3 as well as the python2 version of salt 2019.2.

### Setup
pillar/temp/a.sls
```
a:
  - 'Entry A'
```
pillar/temp/b.sls
```
b:
  - 'Entry B'
```
pillar/temp/init.sls

```
include:
  - temp.a:
      key: element:a
  - temp.b:
      key: element:b
```

### Steps to Reproduce Issue
```
salt-call pillar.get element
```

```
> local:
>     ----------
>     b:
>         ----------
>         a:
>             - Entry A
>         b:
>             - Entry B
```

expected behaviour:

```
> local:
>     ----------
>     a:
>         ----------
>         a:
>             - Entry A
>     b:
>         ----------
>         b:
>             - Entry B
```

### Versions Report
local:
    Salt Version:
               Salt: 2019.2.0
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.4.9 (default, Feb  5 2019, 14:36:09)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.4.2
                ZMQ: 4.1.4
     
    System Versions:
               dist: centos 7.6.1810 Core
             locale: UTF-8
            machine: x86_64
            release: 3.10.0-957.5.1.el7.x86_64
             system: Linux
            version: CentOS Linux 7.6.1810 Core

### PR DESCRIPTION
**Pull request by dwoz**
### What does this PR do?

- Fixes pillar include regression while preserving wildcard include functionality.
- Adds regression tests for both.

Fixes #52134
Wild card include issue #22063

### Previous Behavior

Including from multiple files stomped on pillar key

### New Behavior

Fixes key stomping regression

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by waynew** [comment]
Hm... does this make https://github.com/saltstack/salt/pull/52008/files irrelevant? Or is this change for a different problem?

**Comment by dwoz** [comment]
@waynew Looks like this is a separate issue. I think we should merge this change into your PR.

**Comment by waynew** [comment]
The thing I'm most concerned about is that this PR is removing the matched_pstates (or changing it to assignment rather than .extend)

**Comment by dwoz** [comment]
@waynew I took a look at this again and everything still looks right to me. Is there a test we can write that would confirm there is or is not an issue? Or would you like me to merge this into your change so you can test it?

**Comment by dwoz** [comment]
@waynew Since you're PR's (#52008) tests have passed I'll merge your changes then update my branch accordingly

**Review by waynew — APPROVED** [review]
👍

**Pull request merged**
