### PR TITLE
Back-port #32665 to 2015.8

### PR DESCRIPTION
**Pull request by rallytime**
Back-port #32665 to 2015.8

Refs #30809

### CODE REVIEW

**Comment by cachedout** [comment]
Hrm, we really need to decide what to do here. I really don't like this in a point release.

@thatch45 do you have any thoughts?

**Comment by thatch45** [comment]
Yes, I dont' think this is a good idea to put in a point release

**Comment by cachedout** [comment]
I'm closing it then.

**Comment by rallytime** [comment]
Sounds good to me!

**Comment by MorphBonehunter** [comment]
@rallytime could it be, that this got lost in recent versions?
i've tried the option "pillar_merge_lists" today and could not get it to work.
So i looked at the code (we use 2016.3.4) and could not find the additions from this merge request in salt/modules/pillar.py.
So i look in branch 2015.8 and 2016.3 branches and could not find it there.
So maybe i missed something?

**Comment by rallytime** [comment]
@MorphBonehunter We decided that this change was not something we wanted to put into a point release, but should rather stay in the develop branch. I closed this back-porting pull request. The change will be available in the upcoming feature realease, 2016.11.0.

**Comment by MorphBonehunter** [comment]
@rallytime ... ahhh...i should read the whole comments bevor asking...sorry for that!

**Comment by rallytime** [comment]
No problem! :)

**Pull request closed without merging**
