### PR TITLE
Remove invalid JSON for Mac OS X

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?

Fixes a problem with the npm module on OS X. An extra line is being added to the return that is not valid JSON but is not being removed by the `_extract_json` function because it starts with a `[`.
### What issues does this PR fix or reference?

https://github.com/saltstack/qa/issues/236
### Previous Behavior

The npm.install function would return the raw return data instead of a dictionary, which would break the npm.installed state.
### New Behavior

Remove's the offending line and returns a proper dictionary.
### Tests written?

This fixes the npm.installed state test on OS X

### CODE REVIEW

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
This has nothing to do with the version of `npm` as suggested in the comment. I think that what is happening here is that this is output that's being produced by cases where the `fsm` module is installed and it's reporting on file changes. Since not all OS X installations have the `fsm` module installed, gating this behind a check for Darwin is overly broad.

More critically, I am worried that this change has the potential to _badly_ break `npm` support for OS X.

What this does, in effect, is to say that the only line in the output that should be considered a marker for the beginning of valid JSON is a line which begins with a `{`. It disregards lines which begin with `[`, which of course is _also_ valid JSON.

**Comment by twangboy** [comment]
@cachedout Does this work better?

**Comment by cachedout** [comment]
This is an improvement. An ideal solution would be to include the detection in the first loop but the output is relatively small and thus inexpensive given that we're processing something in-memory. Thanks.

**Pull request merged**
