### PR TITLE
[3007.x] transport: tcp check that pull_path exists before chmod

### PR DESCRIPTION
**Pull request by Sxderp**
### What does this PR do?
Check that pull_path is used before attempting to chmod. This was an oversight in the patch to open up the socket permissions. I'm not entirely sure how this doesn't break tests / functionality.. but whatever. The fix removes a traceback, which is good I suppose.

I'm not actually sure what kind of tests would be needed ... since the current tests seem not to have caught this?

### What issues does this PR fix or reference?
Fixes

### Previous Behavior
I noticed this traceback in some testing artifacts:
```
14:06:15,138 [tornado.application                                                             :758 ][ERROR   ][PublishServer(268624)] Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7f83475315e0>>, <Task finished name='Task-10' coro=<PublishServer.publisher() done, defined at /home/sdaniele3/salt/salt/transport/tcp.py:1372> exception=TypeError('chmod: path should be string, bytes, os.PathLike or integer, not NoneType')>)
Traceback (most recent call last):
  File "/home/sdaniele3/salt/.nox/test-parametrized-3-crypto-none-transport-zeromq-coverage-false/lib64/python3.9/site-packages/tornado/ioloop.py", line 738, in _run_callback
    ret = callback()
  File "/home/sdaniele3/salt/.nox/test-parametrized-3-crypto-none-transport-zeromq-coverage-false/lib64/python3.9/site-packages/tornado/ioloop.py", line 762, in _discard_future_result
    future.result()
  File "/home/sdaniele3/salt/salt/transport/tcp.py", line 1438, in publisher
    os.chmod(self.pull_path, self.pull_path_perms)
TypeError: chmod: path should be string, bytes, os.PathLike or integer, not NoneType
```

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### CODE REVIEW

**Comment by Sxderp** [comment]
@dwoz You did the initial permission fixup. You're probably the best one to review.

**Comment by twangboy** [comment]
Could we get a changelog and a test for this, please?

**Comment by Sxderp** [comment]
I'm not actually sure the best way to test. There's no functional issues. The async task just cancels right before it was going to exit anyway, but the other tasks it spawns are successful. In the codepath that causes the traceback the server is binding to a TCP port the chmod is also inconsequential.

I /could/ make a specific test for TCP that the "publisher" method is successful, but that seems a little silly to make one for a specific transport. Ideally all transports have the same "interface". Unfortunately making a generic one doesn't make sense either as each transport treats "publisher" differently (which maybe should be normalized?). For example WebSocket will hang indefinitely ([on purpose](https://github.com/saltstack/salt/blob/44d96002e927353ab148ecec0d7da2551f83412b/salt/transport/ws.py#L378-L379)) in that function and at the moment ZeroMQ publisher is "broken" (see #66751).

Do you have any suggestions?

**Comment by dwoz** [comment]
> I'm not actually sure the best way to test. There's no functional issues. The async task just cancels right before it was going to exit anyway, but the other tasks it spawns are successful. In the codepath that causes the traceback the server is binding to a TCP port and thus chmod is also inconsequential.
> 
> I /could/ make a specific test for TCP that the "publisher" method is successful, but that seems a little silly to make one for a specific transport. Ideally all transports have the same "interface". Unfortunately making a generic one doesn't make sense either as each transport treats "publisher" differently (which maybe should be normalized?). For example WebSocket will hang indefinitely ([on purpose](https://github.com/saltstack/salt/blob/44d96002e927353ab148ecec0d7da2551f83412b/salt/transport/ws.py#L378-L379)) in that function and at the moment ZeroMQ publisher is "broken" (see #66751).
> 
> Do you have any suggestions?

It is fine to test each transport implementation separately. As well as testing the overall interfaces. In this case since the but is in the tcp transport a regression test specific for this case is what we are looking for.

See https://github.com/saltstack/salt/pull/66994/commits/1959ca946bed6d68a0074ea9806cfe1a6cf63a17

It's worth nothing that while writing the test I noticed chmod was getting called twice instead just once. So, this happens to be a good example of why we want tests.

**Comment by Sxderp** [comment]
Cool. That looks good. I was really struggling with how to approach the tests.

**Comment by dwoz** [comment]
> Cool. That looks good. I was really struggling with how to approach the tests.

There are also a few example in the test suite of running tests against all three transports:

https://github.com/saltstack/salt/blob/3007.x/tests/pytests/functional/channel/test_server.py#L59

I think this PR can be closed since mine was merged.

**Pull request closed without merging**
