### PR TITLE
Adding the first napalm beacon

### PR DESCRIPTION
**Pull request by mirceaulinic**
### What does this PR do?

A simple beacon that invokes napalm functions and fires events on various triggers referring to the output of the functions executed.

### CODE REVIEW

**Review by cachedout — APPROVED** [review]
This LGTM but I think that @garethgreenaway should also have a look here and sign off on this.

**Comment by garethgreenaway** [comment]
Apologies for the delay in reviewing this.  Looks great, but I'd love to see a `validate` function added to ensure configurations are validated.  Check the other beacons for examples.

**Comment by mirceaulinic** [comment]
Thanks @garethgreenaway for reviewing - I have added the validate function, please have a look again when you got a minute.

**Review by garethgreenaway — APPROVED** [review]

**Comment by garethgreenaway** [comment]
@mirceaulinic Looks good!

**Pull request merged**
