### PR TITLE
Add FreeBSD detection for VirtualBox

### PR DESCRIPTION
**Pull request by JaseFace**

### CODE REVIEW

**Comment by kev009** [comment]
LGTM

**Comment by kev009** [comment]
Will need BP to 2015.8 and 2015.5

**Comment by jfindlay** [comment]
@JaseFace, thanks for the fix.  In the future you are welcome to submit fixes directly to the oldest supported release branch, see https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

**Comment by jfindlay** [comment]
Fixes #28383.

**Comment by JaseFace** [comment]
Sorry about that.. I guess I saw this as a new feature, but since we'd like it backported I should have pushed it against 2015.5.

**Comment by rallytime** [comment]
Thanks @JaseFace! These test failures are unrelated.

**Comment by jfindlay** [comment]
@JaseFace, no problem.  It looked like a bug to me. :-)

**Pull request merged**
