### PR TITLE
Handle yum.Errors.YumBaseError

### LINKED ISSUE #44331: rpmdb error causes traceback
### Description of Issue/Question
rpm database is in a bad state. Salt returns a traceback rather than an elegant message. 
I know it is an edge-case but I thought I would report you want to catch this error and present a better message to the user. Otherwise, feel free to close this Issue.

error: rpmdb: BDB0113 Thread/process 25361/140576677242688 failed: BDB1507 Thread died in Berkeley DB library
error: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
error: cannot open Packages index using db5 -  (-30973)
error: cannot open Packages database in /var/lib/rpm

          ID: soe-packages
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1843, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 1631, in installed
                  **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 1284, in install
                  _available = list_repo_pkgs(*has_wildcards, byrepo=False, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 792, in list_repo_pkgs
                  repo_name for repo_name, repo_info in six.iteritems(list_repos())
                File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 2456, in list_repos
                  basedirs = _normalize_basedir(basedir)
                File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 382, in _normalize_basedir
                  basedir = _get_yum_config_value('reposdir')
                File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 359, in _get_yum_config_value
                  conf = _get_yum_config()
                File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 308, in _get_yum_config
                  for name, value in six.iteritems(yb.conf):
                File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 1078, in <lambda>
                  conf = property(fget=lambda self: self._getConfig(),
                File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 349, in _getConfig
                  startupconf = config.readStartupConfig(fn, root, releasever)
                File "/usr/lib/python2.7/site-packages/yum/config.py", line 1093, in readStartupConfig
                  startupconf.distroverpkg)
                File "/usr/lib/python2.7/site-packages/yum/config.py", line 1235, in _getsysver
                  raise Errors.YumBaseError("Error: " + str(e))
              YumBaseError: Error: rpmdb open failed
     Started: 17:29:53.115194
    Duration: 28718.161 ms
     Changes:

### Setup
soe-packages:
  pkg.installed:
    - pkgs:
      - bind-utils
      - ntpdate
      - resolvconf
      - less
      - vim
      - nfs-common
      - at
      - git
      - snmpd
      - openssh-server
      - denyhosts
      - ssmtp
      - zsh
      - nethogs
      - iftop
      - sysstat
      - psacct
      - net-tools
      - pv
      - rsyslog
      - nmap-ncat
    - require:
      - file: /etc/yum.repos.d/

### Steps to Reproduce Issue
salt-call --local state.apply

### Versions Report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.4 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.2.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo

### PR DESCRIPTION
**Pull request by leeclemens**
Happens at least in event rpmdb is corrupt/cannot be opened

### What does this PR do?

Excepts `yum.Errors.YumBaseError` and raises `CommandExecutionError` for consistency and simplified display

### What issues does this PR fix or reference?

Fixes #44331

### Previous Behavior

Full Traceback was printed in Comment

### New Behavior

`CommandExecutionError` is raised with simplified message from the original `yum.Errors.YumBaseError`

### Tests written?

No

### Commits signed with GPG?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by leeclemens** [comment]
Please know that I have _not_ tested this. If anyone is able to, please confirm the message is cleaned up (see Issue addressed) or if there is a good way to reproduce the rpmdb corruption/open issue?

**Comment by isbm** [comment]
@leeclemens actually you could just corrupt the RPM database to see it in a real action (just don't touch `Packages` Berkeley db hash as mainly the `rpm --rebuilddb` uses it, but you can corrupt any other of these). And do it on docker or disposable VM. :wink: Also you could just write a unit test for this, simply mock the corrupted database exception and see in action your code working.

**Review by isbm — CHANGES_REQUESTED** [review]
I would rather write a unit test for this. The `yum.YumBase()` can be just a mock that raises `YumBaseError` exception.

**Comment by leeclemens** [comment]
Thanks @isbm , I'll look into this more!

**Comment by leeclemens** [comment]
I added the test case, but I could only reproduce the issue with 2017.7.2 and after corrupting `Packages`. Behavior between 2017.7.2 and 2018.3/develop was similar when corruption various other files. I could not reproduce the issue in `develop` after corruption `Packages` (the only way I was able to get a traceback), so I think this and the Issue can be closed.

**Comment by isbm** [comment]
@leeclemens what actually happens on `develop`? It prior to this automatically rebuilds its RPM database or?..

**Comment by leeclemens** [comment]
@isbm I put one example output in https://github.com/saltstack/salt/issues/44331#issuecomment-383754182, but basically it prints errors cleanly with useful information and not the Traceback (which I believe is why the original issue was created).

**Review by cachedout — APPROVED** [review]

**Comment by leeclemens** [comment]
@cachedout I just want to clarify, as this has gotten a little confusing, but I was unable to reproduce the OP's issue with the current version. Although this fix shouldn't introduce any issues, it doesn't necessary resolve any either. I haven't debugged it, but it seems the error is gracefully handled somewhere before the `except` block I added.

**Review by isbm — APPROVED** [review]

**Comment by rallytime** [comment]
Hi @leeclemens - It appears there is a merge conflict on this change now. Can you rebase and fix the conflict?

**Comment by rallytime** [comment]
re-run py

**Comment by rallytime** [comment]
@leeclemens There is a related test failing with your change that needs to be adjusted:

- unit.modules.test_yumpkg.YumTestCase.test_yum_base_error

https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/23233/

**Comment by leeclemens** [comment]
@rallytime That makes sense since there may not be a yum module available on Ubuntu. It may make sense to skip all of `YumTestCase` if not on a platform where it is available. Is there a best/preferred way to approach that?

**Comment by rallytime** [comment]
@leeclemens Theoretically, you should be able to mock the test so that the test could be run on any distro. However, if that's not possible you can use the `skipIf` decorator to skip tests that should only apply to certain distros.

**Pull request merged**
