### PR TITLE
adds user and cwd params to pip.version execution

### LINKED ISSUE #59088: [BUG]
**Description**
Commands triggered by virtualenv.managed might not respect the user parameter, which result in a __pycache__ folder owned by root, triggering permission issues later on.
This bug is the same as #57550

**Setup**
Ubuntu 20.04, python 3.7, salt 3002.2

Example of state used:
`virtualenv_init:
  virtualenv.managed:
    - venv_bin: virtualenv
    - name: /opt/chimera/env/chimera
    - python: /usr/bin/python3.8
    - distribute: False
    - user: chimera
    - no_chown: True

virtualenv_setup_requirements/production.txt:
  pip.installed:
    - bin_env: /opt/chimera/env/chimera
    - user: chimera
    - no_chown: True
    - requirements: /opt/chimera/chimera/requirements/production.txt`

**Expected behavior**
Execution of the above state is partially executed as root and .pyc files are written as such.
`[ERROR   ] stderr: ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/opt/penta/env/chimera/lib/python3.7/site-packages/__pycache__/zipp.cpython-37.pyc'
Consider using the `--user` option or check the permissions.`

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-51-generic
        system: Linux
       version: Ubuntu 20.04 focal

```
</details>

### PR DESCRIPTION
**Pull request by marangonico**
### What does this PR do?
Adds a user parameter to 'pip.version'

### What issues does this PR fix or reference?
Fixes: #59088 

### Previous Behavior
running pip.installed as a non root user, would still write some files as such.

### New Behavior
Now pip.version is called with user param

### CODE REVIEW

**Comment by krionbsd** [comment]
@marangonico could you please apply this diff to fix pre-commit failure, I couldn't push into your branch unfortunately

**Comment by krionbsd** [comment]
```
diff --git a/salt/states/pip_state.py b/salt/states/pip_state.py
index 87e86514b4..c0458c533f 100644
--- a/salt/states/pip_state.py
+++ b/salt/states/pip_state.py
@@ -1,4 +1,3 @@
-# -*- coding: utf-8 -*-
 """
 Installation of Python Packages Using pip
 =========================================
@@ -19,18 +18,12 @@ requisite to a pkg.installed state for the package which provides pip
           - pkg: python-pip
 """
 
-# Import python libs
-from __future__ import absolute_import, print_function, unicode_literals
 
 import logging
 import re
 import sys
 import types
 
-# Import 3rd-party libs
-import salt.ext.six as six
-
-# Import salt libs
 import salt.utils.data
 import salt.utils.versions
 from salt.exceptions import CommandExecutionError, CommandNotFoundError
@@ -201,7 +194,7 @@ def _check_pkg_version_format(pkg):
                 for vcs in supported_vcs:
                     if pkg.startswith(vcs):
                         from_vcs = True
-                        install_req = _from_line(pkg.split("{0}+".format(vcs))[-1])
+                        install_req = _from_line(pkg.split("{}+".format(vcs))[-1])
                         break
             else:
                 install_req = _from_line(pkg)
@@ -209,11 +202,11 @@ def _check_pkg_version_format(pkg):
         ret["result"] = False
         if not from_vcs and "=" in pkg and "==" not in pkg:
             ret["comment"] = (
-                "Invalid version specification in package {0}. '=' is "
+                "Invalid version specification in package {}. '=' is "
                 "not supported, use '==' instead.".format(pkg)
             )
             return ret
-        ret["comment"] = "pip raised an exception while parsing '{0}': {1}".format(
+        ret["comment"] = "pip raised an exception while parsing '{}': {}".format(
             pkg, exc
         )
         return ret
@@ -291,7 +284,7 @@ def _check_if_installed(
                 and _fulfills_version_spec(pip_list[prefix], version_spec)
             ) or (not any(version_spec)):
                 ret["result"] = True
-                ret["comment"] = "Python package {0} was already " "installed".format(
+                ret["comment"] = "Python package {} was already " "installed".format(
                     state_pkg_name
                 )
                 return ret
@@ -330,7 +323,7 @@ def _check_if_installed(
             if not desired_version:
                 ret["result"] = True
                 ret["comment"] = (
-                    "Python package {0} was already "
+                    "Python package {} was already "
                     "installed and\nthe available upgrade "
                     "doesn't fulfills the version "
                     "requirements".format(prefix)
@@ -338,7 +331,7 @@ def _check_if_installed(
                 return ret
             if _pep440_version_cmp(pip_list[prefix], desired_version) == 0:
                 ret["result"] = True
-                ret["comment"] = "Python package {0} was already " "installed".format(
+                ret["comment"] = "Python package {} was already " "installed".format(
                     state_pkg_name
                 )
                 return ret
@@ -358,11 +351,7 @@ def _pep440_version_cmp(pkg1, pkg2, ignore_epoch=False):
             "The pkg_resources packages was not loaded. Please install setuptools."
         )
         return None
-    normalize = (
-        lambda x: six.text_type(x).split("!", 1)[-1]
-        if ignore_epoch
-        else six.text_type(x)
-    )
+    normalize = lambda x: str(x).split("!", 1)[-1] if ignore_epoch else str(x)
     pkg1 = normalize(pkg1)
     pkg2 = normalize(pkg2)
 
@@ -728,8 +717,8 @@ def installed(
     # pkgs = ','.join([prepro(pkg) for pkg in pkgs])
     prepro = (
         lambda pkg: pkg
-        if isinstance(pkg, six.string_types)
-        else " ".join((six.iteritems(pkg)[0][0], six.iteritems(pkg)[0][1]))
+        if isinstance(pkg, str)
+        else " ".join((pkg.items()[0][0], pkg.items()[0][1]))
     )
     pkgs = [prepro(pkg) for pkg in pkgs]
 
@@ -739,7 +728,7 @@ def installed(
         cur_version = __salt__["pip.version"](bin_env=bin_env, user=user, cwd=cwd)
     except (CommandNotFoundError, CommandExecutionError) as err:
         ret["result"] = None
-        ret["comment"] = "Error installing '{0}': {1}".format(name, err)
+        ret["comment"] = "Error installing '{}': {}".format(name, err)
         return ret
     # Check that the pip binary supports the 'use_wheel' option
     if use_wheel:
@@ -755,8 +744,8 @@ def installed(
             ret["result"] = False
             ret["comment"] = (
                 "The 'use_wheel' option is only supported in "
-                "pip between {0} and {1}. The version of pip detected "
-                "was {2}."
+                "pip between {} and {}. The version of pip detected "
+                "was {}."
             ).format(min_version, max_version, cur_version)
             return ret
 
@@ -774,8 +763,8 @@ def installed(
             ret["result"] = False
             ret["comment"] = (
                 "The 'no_use_wheel' option is only supported in "
-                "pip between {0} and {1}. The version of pip detected "
-                "was {2}."
+                "pip between {} and {}. The version of pip detected "
+                "was {}."
             ).format(min_version, max_version, cur_version)
             return ret
 
@@ -789,8 +778,8 @@ def installed(
             ret["result"] = False
             ret["comment"] = (
                 "The 'no_binary' option is only supported in "
-                "pip {0} and newer. The version of pip detected "
-                "was {1}."
+                "pip {} and newer. The version of pip detected "
+                "was {}."
             ).format(min_version, cur_version)
             return ret
 
@@ -825,12 +814,12 @@ def installed(
                 # TODO: Check requirements file against currently-installed
                 # packages to provide more accurate state output.
                 comments.append(
-                    "Requirements file '{0}' will be " "processed.".format(requirements)
+                    "Requirements file '{}' will be " "processed.".format(requirements)
                 )
             if editable:
                 comments.append(
                     "Package will be installed in editable mode (i.e. "
-                    'setuptools "develop mode") from {0}.'.format(editable)
+                    'setuptools "develop mode") from {}.'.format(editable)
                 )
             ret["comment"] = " ".join(comments)
             return ret
@@ -925,7 +914,7 @@ def installed(
 
     # Call to install the package. Actual installation takes place here
     pip_install_call = __salt__["pip.install"](
-        pkgs="{0}".format(pkgs_str) if pkgs_str else "",
+        pkgs="{}".format(pkgs_str) if pkgs_str else "",
         requirements=requirements,
         bin_env=bin_env,
         use_wheel=use_wheel,
@@ -995,7 +984,7 @@ def installed(
                 if ret["changes"].get("requirements"):
                     comments.append(
                         "Successfully processed requirements file "
-                        "{0}.".format(requirements)
+                        "{}.".format(requirements)
                     )
                 else:
                     comments.append("Requirements were already installed.")
@@ -1003,7 +992,7 @@ def installed(
             if editable:
                 comments.append(
                     "Package successfully installed from VCS "
-                    "checkout {0}.".format(editable)
+                    "checkout {}.".format(editable)
                 )
                 ret["changes"]["editable"] = True
             ret["comment"] = " ".join(comments)
@@ -1040,7 +1029,7 @@ def installed(
                     # installing it report it
                     if not pipsearch:
                         pkg_404_comms.append(
-                            "There was no error installing package '{0}' "
+                            "There was no error installing package '{}' "
                             "although it does not show when calling "
                             "'pip.freeze'.".format(pkg)
                         )
@@ -1050,10 +1039,10 @@ def installed(
                             and prefix.lower() not in already_installed_packages
                         ):
                             ver = pipsearch[prefix]
-                            ret["changes"]["{0}=={1}".format(prefix, ver)] = "Installed"
+                            ret["changes"]["{}=={}".format(prefix, ver)] = "Installed"
                 # Case for packages that are an URL
                 else:
-                    ret["changes"]["{0}==???".format(state_name)] = "Installed"
+                    ret["changes"]["{}==???".format(state_name)] = "Installed"
 
             # Set comments
             aicomms = "\n".join(already_installed_comments)
@@ -1069,30 +1058,28 @@ def installed(
     elif pip_install_call:
         ret["result"] = False
         if "stdout" in pip_install_call:
-            error = "Error: {0} {1}".format(
+            error = "Error: {} {}".format(
                 pip_install_call["stdout"], pip_install_call["stderr"]
             )
         else:
-            error = "Error: {0}".format(pip_install_call["comment"])
+            error = "Error: {}".format(pip_install_call["comment"])
 
         if requirements or editable:
             comments = []
             if requirements:
                 comments.append(
-                    "Unable to process requirements file " '"{0}".'.format(requirements)
+                    "Unable to process requirements file " '"{}".'.format(requirements)
                 )
             if editable:
                 comments.append(
-                    "Unable to install from VCS checkout" "{0}.".format(editable)
+                    "Unable to install from VCS checkout" "{}.".format(editable)
                 )
             comments.append(error)
             ret["comment"] = " ".join(comments)
         else:
             pkgs_str = ", ".join([state_name for _, state_name in target_pkgs])
             aicomms = "\n".join(already_installed_comments)
-            error_comm = "Failed to install packages: {0}. " "{1}".format(
-                pkgs_str, error
-            )
+            error_comm = "Failed to install packages: {}. " "{}".format(pkgs_str, error)
             ret["comment"] = aicomms + ("\n" if aicomms else "") + error_comm
     else:
         ret["result"] = False
@@ -1130,7 +1117,7 @@ def removed(
         pip_list = __salt__["pip.list"](bin_env=bin_env, user=user, cwd=cwd)
     except (CommandExecutionError, CommandNotFoundError) as err:
         ret["result"] = False
-        ret["comment"] = "Error uninstalling '{0}': {1}".format(name, err)
+        ret["comment"] = "Error uninstalling '{}': {}".format(name, err)
         return ret
 
     if name not in pip_list:
@@ -1140,7 +1127,7 @@ def removed(
 
     if __opts__["test"]:
         ret["result"] = None
-        ret["comment"] = "Package {0} is set to be removed".format(name)
+        ret["comment"] = "Package {} is set to be removed".format(name)
         return ret
 
     if __salt__["pip.uninstall"](
@@ -1184,7 +1171,7 @@ def uptodate(name, bin_env=None, user=None, cwd=None, use_vt=False):
     try:
         packages = __salt__["pip.list_upgrades"](bin_env=bin_env, user=user, cwd=cwd)
     except Exception as e:  # pylint: disable=broad-except
-        ret["comment"] = six.text_type(e)
+        ret["comment"] = str(e)
         return ret
 
     if not packages:
```

**Comment by krionbsd** [comment]
@marangonico we've to write the test case for this change as well

**Review by s0undt3ch — CHANGES_REQUESTED** [review]
We should cover these changes with tests.

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
