### PR TITLE
Fix for Solaris virtual grain detection

### PR DESCRIPTION
**Pull request by clallen**
### What does this PR do?
Fixes a bug that I inadvertently introduced in commit  f7f8a8f, as well as adds better detection for zones on Solaris 11.

### What issues does this PR fix or reference?
Issue #55444 

### Previous Behavior
When on a non-LDOM platform, the virtual grain would always detect as "LDOM", due to lack of adequate parsing of "virtinfo" command output.

### New Behavior
Output of the "virtinfo" command is now parsed correctly, and detection of zones is more accurate.

### Tests written?
Output of nox test unit.grains.test_core:
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Python Version: 2.7.15+ (default, Oct 7 2019, 17:39:04) [GCC 7.4.0]
 * Transplanting configuration files to '/tmp/salt-tests-tmpdir/config'
 * Transplanting multimaster configuration files to '/tmp/salt-tests-tmpdir/config'
 * Current Directory: /salt-fork
 * Test suite is running under PID 575
 * Logging tests on artifacts/logs/runtests-20191203010050.773101.log
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Starting unit.grains.test_core Tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.s...............s......................s.
----------------------------------------------------------------------
Ran 42 tests in 0.112s

OK (skipped=3)

==========================================================================================================  Overall Tests Report  ==========================================================================================================
*** unit.grains.test_core Tests  ***********************************************************************************************************************************************************************************************************
 --------  Skipped Tests  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
   -> unit.grains.test_core.CoreGrainsTestCase.test__windows_platform_data    ->  System is not Windows
   -> unit.grains.test_core.CoreGrainsTestCase.test_locale_info_no_tz_tzname  ->  Not Missing dateutil.tz
   -> unit.grains.test_core.CoreGrainsTestCase.test_windows_platform_data     ->  System is not Windows
 -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
============================================================================================================================================================================================================================================
OK (total=42, skipped=3, passed=39, failures=0, errors=0)
==========================================================================================================  Overall Tests Report  ==========================================================================================================
Test suite execution finalized with exit code: 0
nox > Session runtests-parametrized-2.7(coverage=False, crypto=None, transport='zeromq') was successful.
nox > Ran multiple sessions:
nox > * runtests-zeromq-2.7(coverage=False): success
nox > * runtests-parametrized-2.7(coverage=False, crypto=None, transport='zeromq'): success
```

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by DmitryKuzmenko** [comment]
@clallen sorry for the long delay. I've updated your PR: merged to the head of the current master resolving conflicts. Let's wait for tests.
Are you still interested in this? Could you please write a test for this?

**Comment by clallen** [comment]
I don't mind writing a test, but I'm not sure what is required.  Could you point me to an example?

**Comment by DmitryKuzmenko** [comment]
@clallen we already have a unit test for grains `tests/unit/grains/test_core.py`. All you need is to ensure your code is covered with tests.

**Review by dwoz — APPROVED** [review]
@clallen I'm going to merge this in for Sodium. In the future we'll definitely need tests along with bug fixes like this.

**Comment by clallen** [comment]
@dwoz My apologies, I have not had much time to get familiar with the tests system.  If there is anything else you need from me let me know.

**Comment by sjorge** [comment]
This seems to have completely broken virtual detection on illumos :(
Everything ends up as physical now.

**Comment by DmitryKuzmenko** [comment]
@sjorge is it easily reproducible? Could you try to bisect it and create a separate issue?

**Comment by DmitryKuzmenko** [comment]
Or either just create an issue describing reproduction steps, and we'll do it.

**Comment by sjorge** [comment]
Yep, already did https://github.com/saltstack/salt/issues/57714

I think I found what is going wrong, not yet why/when it changed.

**Pull request merged**
