### PR TITLE
Fix global injection for state cross calls

### LINKED ISSUE #27481: Fix issues with cross-calling states
Refs #26747
Refs #21214

Need to figure out how to propagate `__running__` and `__instance_id__` and similar magic variables to lower-level calls in the loader. Packing probably won't work, unless I do a call-time packing.

### PR DESCRIPTION
**Pull request by basepi**
Fixes #27481 

Basically, if we define last-minute globals to be injected in the LazyLoader, the `__getitem__` decorates the returned function to inject using the func_globals_inject context manager. This means that all states will have those variables injected and cleaned up, at call time.

@jacksontj  @thatch45  @cachedout

### CODE REVIEW

**Comment by thatch45** [comment]
+1

**Comment by jacksontj** [comment]
+1 :)

**Comment by bechtoldt** [comment]
will those injected states also be listed in the job result/output?

**Comment by jacksontj** [comment]
Did we add tests to check for these?

**Comment by basepi** [comment]
No tests yet. And no, @bechtoldt, the state compiler is completely unaware those states ever even ran. If you need the output, you (as the author of the custom state which is cross-calling) are responsible for adding that output to the return dictionary yourself.

**Pull request merged**
