### PR TITLE
ssdp discovery: multimaster support

### PR DESCRIPTION
**Pull request by mattp-**
### What does this PR do?
a user can now specify an accept: all (default 'any' for original behavior) to connect to all masters that match the ssdp config specified. this meant moving ssdp discovery from eval_master to tune_in phase of the MinionManager, as such discovery only happens once per process start, so reconnections don't collide (ie, if eval_master call remained, the list order is not guaranteed).

@isbm, I know you were the main author of this functionality. Was your original usecase relying on dynamic rehoming if a disconnection occurs? or is this behavior change ok. We could still support a discovery in eval_master, but only if 'accept: any' (ie single master) is configured.

### What issues does this PR fix or reference?
n/a

### Previous Behavior
ssdp discovery happened at eval_master time

### New Behavior
ssdp discovery happened at minionmanager time, to allow for multimaster

### Tests written?
No

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by gtmanfred — APPROVED** [review]
This looks good, i would really like to see all these options documented, but as it isn't already, we should just make a documentation issue for that and do it in another pr.

**Comment by isbm** [comment]
@mattp- This is interesting. But I would recommend join slack channel in saltstack community and let's discuss this a bit. This is basic feature that I wanted soon to extend. Currently it joins "first win" packet. But this should be extended to:

- Join to less loaded.
- Re-join elsewhere if current master goes offline.

Also this feature has one major security flaw: you can put to the circle malicious master and gain full control on the machine with the minion. Therefore there I would propose a mechanism of "trusted circle" of masters. If you put to the circle untrusted master, all trusted masters marks that one as "untrusted" and minions avoiding it automatically.

**Comment by cachedout** [comment]
@isbm I'm not sure how I understand how multi-master support is functionally different than single-master support from a security perspective. If SSDP is advertising a malicious master, it seems like there is already a serious breach, no?

**Comment by isbm** [comment]
@cachedout no, there is no difference.

**Comment by cachedout** [comment]
@mattp- Can you please grab the lint errors described here? https://jenkinsci.saltstack.com/job/pr-lint/job/PR-50341/12/warnings52Result/new/

**Comment by mattp-** [comment]
@cachedout woops, fixed.

**Review by isbm — APPROVED** [review]

**Comment by cachedout** [comment]
So, given that we agree that there is no security threat _introduced_ by this PR, I think it is fine to go in. That said, certainly the ideas from @isbm are worthy of consideration and it would be good to see them go through the RFC process. Everybody cool with that?

**Comment by mattp-** [comment]
sounds good to me :+1:

**Comment by isbm** [comment]
This PR is not introducing problems, on top of existing ones. :grinning:

The security mechanism should be through the RFC without questions.

**Pull request merged**
