### PR TITLE
salt-minion 2016.3.1

### PR DESCRIPTION
**Pull request by GPadierna1**
### What does this PR do?

On SunOS (Solaris 10, at least), intends to more reliably produce output for the grains.item cpu_model
### What issues does this PR fix or reference?

On a Solaris box for which the CPU-IDs don't start with 0, the grains.item cpu_model is not detected and return 'None'.
### Previous Behavior

When run e.g. salt-call grains.item cpu_model, 'None' is returned instead of the correct string
### New Behavior

Covers more use cases, as it doesn't assume the first cpu in use is id=0, and therefore produces more accurate output.
### Tests written?

No.

The proposed change to salt.core.py would be this:

```
--- core.py.orig    Wed Jul  6 12:29:04 2016
+++ core.py Wed Jul  6 12:44:04 2016
@@ -360,7 +360,8 @@
     grains['cpuarch'] = __salt__['cmd.run']('isainfo -k')
     psrinfo = '/usr/sbin/psrinfo 2>/dev/null'
     grains['num_cpus'] = len(__salt__['cmd.run'](psrinfo, python_shell=True).splitlines())
-    kstat_info = 'kstat -p cpu_info:0:*:brand'
+    first_cpu_num = __salt__['cmd.run'](psrinfo, python_shell=True).splitlines()[0].split()[0]
+    kstat_info = 'kstat -p cpu_info:%d:*:brand' %int(first_cpu_num)
     for line in __salt__['cmd.run'](kstat_info).splitlines():
         match = re.match(r'(\w+:\d+:\w+\d+:\w+)\s+(.+)', line)
         if match:
```

Update:
- tested on several Solaris boxes with versions 9, 10 and 11 (SPARC)

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @GPadierna1 

Looks like this PR perhaps didn't get submitted against the correct branch and as a result, includes some commits that were not authored by you. Could you either update this PR to include only your commits or close this PR and open another? Thanks!

**Comment by GPadierna1** [comment]
Ups, sorry, I though I was creating a new PR, not updating one that already existed.
I'll create a new PR then.

**Comment by rallytime** [comment]
@GPadierna1 This still isn't quite right and seems to be pulling in more commits and re-running tests. I am going to close this. We'd still love to have your changes, but submitted against the correct branch. Let us know if you run into troubles or need any help/pointers.

**Comment by GPadierna1** [comment]
Hi Nicole,

yes, that's fine if you close it, thanks.
It's my first contribution and I'm more a sysadmin than a developer, so 
I'm really a newby here.
And well, yes, I could need some help :)

First I thought this should be a PR, but now that I think of it, maybe 
it's actually a bug. Here's the thing:
A feature that's already available (print the 'cpu_model' though the 
grains.core.py module) incorrectly assumes that the first cpu-id will be 
0, which isn't always the case (in one out of 200+ Solaris boxes, I have 
one where it's 2).

What is that, a bug then? Shoul file a bug report and append the 
proposed patch?

Thanks a lot!

Cheers,
Gerardo

**Comment by rallytime** [comment]
Hi @GPadierna1 - Welcome to Salt! Apologies for closing your first contribution on you. 

If you've found a bug, definitely use the [Issue Tracker](https://github.com/saltstack/salt/issues/new) to submit an issue using the writing prompts. Even if you're unsure of whether or not you've found a bug, this is a great place to at least start a conversation for one of use to look into or others in the community to comment on.

If you have a proposed fix for the bug, you can certainly post it in the bug report. Or you can submit a pull request referencing the new bug report, too. Either way is fine. We have some documentation on this process, if you'd like to know more: 
- [Developing Salt Tutorial](https://docs.saltstack.com/en/latest/topics/development/tutorial.html)
- [Contributing Docs](https://docs.saltstack.com/en/latest/topics/development/contributing.html)

I also recently answered some git-related questions on pull request #34502, in case that is helpful for you.

If you still have questions, definitely let us know. We are happy to help. :)

**Pull request closed without merging**
