### PR TITLE
[develop] Move PR #44602 forward to develop

### PR DESCRIPTION
**Pull request by rallytime**
Move PR #44602 to develop

Refs #44614

PR #44584 is blocking merge forwards from 2017.7 to develop. In order to get the CherryPy test failures cleared up ASAP, I have just ported the fix in #44602 to develop.

### CODE REVIEW

**Comment by rallytime** [comment]
re-run py2

**Comment by rallytime** [comment]
re-run py2

**Comment by rallytime** [comment]
re-run py2

**Review by garethgreenaway — APPROVED** [review]

**Comment by rallytime** [comment]
Test failures are unrelated.

**Pull request merged**
