### PR TITLE
Detect OpenBSD guest running under VMM(4)

### PR DESCRIPTION
**Pull request by eradman**
### What does this PR do?

Properly report `grains['virtual']` when OpenBSD is running under the [VMM](https://man.openbsd.org/vmm) hypervisor

### Previous Behavior

    $ salt-call --local grains.items
    ...
        virtual:
            physical

### New Behavior

    $ salt-call --local grains.items
    ...
        virtual:
            vmm

Tested using OpenBSD 6.1

### CODE REVIEW

**Review by cachedout — CHANGES_REQUESTED** [review]
Thanks for this. I do like to make sure we prominently display any change at all to core grains in the release notes. Could you make a note there and include it in this PR? Then we'll happily merge it. Thanks!

**Comment by eradman** [comment]
You're referring to `doc/topics/releases/oxygen.rst` and a new section called "Grains Changes"?

**Comment by rallytime** [comment]
@eradman Yes, that looks great for the release notes. There is also a pylint error: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/15164/violations/file/salt/grains/core.py/

**Comment by eradman** [comment]
Thanks for pointing out the pylint error--fixed and release notes updated.

**Comment by eradman** [comment]
I think this change is good to go.

(I ran `push -f` so github doesn't acknowledge as a response to the change requested by @cachedout)

**Review by cachedout — APPROVED** [review]

**Pull request merged**
