### PR TITLE
Adding missing authentication information for _disbatch_local in rest_tornado.

### PR DESCRIPTION
**Pull request by kstreee**
### What does this PR do?

Adding missing authentication information for looking up executed jobs logics in `_disbatch_local`.

### What issues does this PR fix or reference?

#42377

### Previous Behavior

salt api have raised the authentication failure exception while handling valid requests (only for the client 'local'), because of #42377. The other clients (i.e. `local_async`, ...) are using requested payloads' authentication information, which are `token`, `eauth` inform, ..., to trigger salt jobs. However, the client `local` uses another authetnication information, '[key](https://github.com/saltstack/salt/blob/2016.11/salt/client/__init__.py#L1565)', when they are looking up executed jobs ([1](https://github.com/saltstack/salt/blob/2016.11/salt/netapi/rest_tornado/saltnado.py#L994-L997), [2](https://github.com/saltstack/salt/blob/2016.11/salt/netapi/rest_tornado/saltnado.py#L1011-L1014)).

### New Behavior

salt api doesn't raise the authentication failure exception for valid requests. Even the key file isn't valid, salt api will proceed even the [key data](https://github.com/saltstack/salt/blob/2016.11/salt/client/__init__.py#L1565) isn't valid for some reason (i.e, #42377)

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
@jacksontj Any comments here?

**Comment by cachedout** [comment]
@whiteinge Is this something you might be able to look at?

**Comment by whiteinge** [comment]
@kstreee Thanks for the contribution. It's always great when someone is willing to sling code.

I'm afraid I don't follow the intent of this change. I believe the `saltutil.find_job` calls here are an attempt to mimic the "synchronous" CLI behavior and are used to decide whether the HTTP response should be kept open. As such they're entirely internal bookkeeping and so shouldn't rely on the credentials of the current user.

**Comment by kstreee** [comment]
@whiteinge  Thanks for your comment. In normal cases, there aren't any problems while calling `saltutil.find_job` to mimic "synchronous" behavior. But some tricky cases, like key file disruption, the current code could fail to authenticate using system's authentication information, even user passed correct authentication information.

Following examples will helps to discuss this issue.

1. run salt master, i.e. `salt-master -d`
2. remove `.root_key` file on the cache directory
3. run salt api, i.e. `salt-api -d`
4. Authentication failure exception is raised only on 'local' requests, because of the system's authentication information is disrupted (2. remove `.root_key`...)

Like above case, the other methods, like 'local_async', can be processed using user's authentication information. But for 'local', current code will fail to authenticate because the saltnado doesn't rely credentials of the requests while mimicking the "synchronous" CLI behavior.

The disruption of system's credentials could happen, and details about it are in #42377.

I hope that this comment helps to understand what I try to fix. If you have any questions about it, comments for me. Thanks.

**Comment by whiteinge** [comment]
Thank you for the thorough explanation.

I see how this change avoids the problem, however we will need to find another way to fix or prevent the key disruption. We can't rely on the current eauth user to have `saltutil.find_job` whitelisted -- some users will want fairly restricted eauth configs -- and we shouldn't rely on the current eauth user for internal-only behavior.

**Comment by kstreee** [comment]
I aware what you are concerning, and also I think it is reasonable to avoid passing the user credentials to `saltutil.find_job`.
In my case, we use a single and global super auth account, and check authentication and authorization using external systems by wrapping salt api and it's payload format, so I couldn't realize the auth issues of user credentials what you explained.  Thanks for your explanation. 👍
I suppose I'm going to make another pr to fix this issue, like as you said earlier. By the way, this pr should be closed. 

Thanks for your comments.

**Pull request closed without merging**
