### PR TITLE
provided more flexibility for the lookup of lambda functions

### PR DESCRIPTION
**Pull request by winstonliu1111**
### What does this PR do?

it offered a little more flexibility than previously on how the lambda name is derived for lookup.  we now take in a format string as input into the present state, and allow the user to use the following substitutable kwargs: api, stage, resource, method
### What issues does this PR fix or reference?

None
### Previous Behavior

lambda function name is derived as stage_name+api_name+resource_path+httpmethod (hard coded)
### New Behavior

the default behavior is still same as the previous behavior since the default lambda_funcname_format is set to be `"{stage}_{api}_{resource}_{method}"`

the user now is able to organize his lambda naming differently if desired.  for example, he can use the following format instead, `"myuserid_{api}_{stage}_{resource}_{method}"`
### Tests written?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by rallytime** [comment]
@winstonliu1111 I have one small comment that should be addressed before this can be merge in.

@kraney Since this is your code, would you mind looking over this as well?

**Comment by kraney** [comment]
Actually, it's my git repo but the change is in winstonliu1111's original code. We've been working together. I looked over the change and it looks good, aside from the risk from kwargs ordering you mention.

**Comment by rallytime** [comment]
@kraney Oh, great! Thanks for commenting/looking it over.

**Comment by rallytime** [comment]
Thanks all!

**Pull request merged**
