### PR TITLE
Fix bug in top file ordering

### LINKED ISSUE #26234: minions appear to be ignoring the 'order' in highdata
It does not appear to be correctly using the order to run the states.

```
----------
          ID: redis30u
    Function: service.running
        Name: redis
      Result: True
     Comment: Service redis has been enabled, and is running
     Started: 05:18:55.545201
    Duration: 710.252 ms
     Changes:   
              ----------
              redis:
                  True
----------
          ID: redis slaveof
    Function: file.append
        Name: /etc/redis.conf
      Result: True
     Comment: Appended 1 lines
     Started: 05:18:56.255867
    Duration: 7.221 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -936,3 +936,4 @@
                   # in order to commit the file to the disk more incrementally and avoid
                   # big latency spikes.
                   aof-rewrite-incremental-fsync yes
                  +slaveof 172.16.0.13 6379
----------
          ID: redis-sentinel
    Function: file.replace
        Name: /etc/redis-sentinel.conf
      Result: True
     Comment: Changes were made
     Started: 05:18:56.263374
    Duration: 7.2 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -50,7 +50,7 @@
                   #
                   # Note: master name should not include special characters or spaces.
                   # The valid charset is A-z 0-9 and the three characters ".-_".
                  -sentinel monitor mymaster 127.0.0.1 6379 2
                  +sentinel monitor mymaster 172.16.0.13 6379 2
                   
                   # sentinel auth-pass <master-name> <password>
                   #
----------
          ID: redis-sentinel
    Function: service.running
      Result: True
     Comment: Service redis-sentinel has been enabled, and is running
     Started: 05:18:56.270827
    Duration: 687.584 ms
     Changes:   
              ----------
              redis-sentinel:
                  True
----------
          ID: nginx
    Function: pkg.installed
      Result: True
     Comment: The following packages were installed/updated: nginx
     Started: 05:18:56.959652
    Duration: 11075.971 ms
     Changes:   
              ----------
              GeoIP:
                  ----------
                  new:
                      1.5.0-9.el7
                  old:
              fontconfig:
                  ----------
                  new:
                      2.10.95-7.el7
                  old:
              fontpackages-filesystem:
                  ----------
                  new:
                      1.44-8.el7
                  old:
              gd:
                  ----------
                  new:
                      2.0.35-26.el7
                  old:
              gperftools-libs:
                  ----------
                  new:
                      2.1-1.el7
                  old:
              libXpm:
                  ----------
                  new:
                      3.5.10-5.1.el7
                  old:
              libunwind:
                  ----------
                  new:
                      1.1-10.el7
                  old:
              libxslt:
                  ----------
                  new:
                      1.1.28-5.el7
                  old:
              nginx:
                  ----------
                  new:
                      1.6.3-6.el7
                  old:
              nginx-filesystem:
                  ----------
                  new:
                      1.6.3-6.el7
                  old:
----------
          ID: nginx
    Function: service.running
      Result: True
     Comment: Service nginx has been enabled, and is running
     Started: 05:19:08.227116
    Duration: 834.341 ms
     Changes:   
              ----------
              nginx:
                  True
----------
          ID: nginx
    Function: user.present
      Result: False
     Comment: The following group(s) are not present: taplist
     Started: 05:19:09.062484
    Duration: 1.243 ms
     Changes:   
----------
          ID: listener_redis30u
    Function: service.mod_watch
        Name: redis
      Result: True
     Comment: Service restarted
     Started: 05:19:09.064325
    Duration: 271.343 ms
     Changes:   
              ----------
              redis:
                  True
----------
          ID: listener_redis-sentinel
    Function: service.mod_watch
        Name: redis-sentinel
      Result: True
     Comment: Service restarted
     Started: 05:19:09.336013
    Duration: 246.407 ms
     Changes:   
              ----------
              redis-sentinel:
                  True

Summary for local
-------------
Succeeded: 29 (changed=28)
Failed:     1
-------------
Total states run:     30
Total run time:   45.299 s
```

This is the output of where everything fails.

### PR DESCRIPTION
**Pull request by cachedout**
Fixes #26234
cc: @gtmanfred

### CODE REVIEW

**Comment by gtmanfred** [comment]
yup, confirmed.

Thanks!

**Comment by cachedout** [comment]
Sweet! Thanks again for the help @gtmanfred

**Comment by bbinet** [comment]
Should this PR be backported to 2015.5 branch before 2015.5.4 is released?

**Comment by bbinet** [comment]
Nevermind, I misread #26234 and in fact the issue didn't apply to the 2015.5 branch.

**Comment by gtmanfred** [comment]
yup, sorry about the confusion with that.

It does look like it might have been some left over pyc files from when I was initially testing it.

**Comment by jfindlay** [comment]
@cachedout, it looks like there is a failed unit test.

**Comment by gtmanfred** [comment]
@cachedout did you get a chance to look at these so it can be merged into develop?

Thanks

**Comment by cachedout** [comment]
@gtmanfred Test fix pushed. WIll merge shortly.

**Comment by gtmanfred** [comment]
awesome, thanks!

**Pull request merged**
