### PR TITLE
Engines support on Minions!

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by garethgreenaway** [comment]
:+1:

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
This looks good but I'd like to see the tests pass first.

**Comment by s0undt3ch** [comment]
Of course :)

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@s0undt3ch I think these signal changes need to be extended to the syndic as well. Firing up the test suite shows the following:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mp/devel/salt/tests/integration/__init__.py", line 249, in start
    getattr(daemon, start_fun)()
  File "/home/mp/devel/salt/salt/minion.py", line 1955, in tune_in
    signal.signal(signal.SIGTERM, self.clean_die)
AttributeError: 'Syndic' object has no attribute 'clean_die'
```

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by pass-by-value** [comment]
:stars:

**Pull request merged**
