### PR TITLE
Fix beacon test flakiness

### PR DESCRIPTION
**Pull request by dwoz**
Fix flakiness in `integration.states.test_beacon.BeaconStateTestCase.test_present_absent` test

https://jenkinsci.saltstack.com/job/2018.3/view/Python3/job/salt-fedora-28-py3/187/testReport/junit/integration.states.test_beacon/BeaconStateTestCase/test_present_absent/

**Do not approve and merge until this build passes: https://jenkinsci.saltstack.com/job/2018.3/view/Python3/job/dwoz-fedora28-py3/**
### Tests written?

No - Fixing test flakiness

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by dwoz** [comment]
re-run ubuntu

**Comment by dwoz** [comment]
re-run full all

**Comment by dwoz** [comment]
re-run full all

**Review by twangboy — APPROVED** [review]

**Review by Ch3LL — APPROVED** [review]

**Comment by Ch3LL** [comment]
@dwoz is this ready to be merged?

**Review by s0undt3ch — APPROVED** [review]

**Comment by dwoz** [comment]
@Ch3LL Yes, I just pushed another change. Adding `listen=True` here makes the `integration.states.test_beacon.BeaconStateTestCase.test_present_absent` test case reliable.

**Comment by s0undt3ch** [comment]
Tests passed :fireworks:

**Pull request merged**
