### PR TITLE
test_git_pillar: passphrase-protected actually works on current Debian

### PR DESCRIPTION
**Pull request by sathieu**
# What does this PR do?
Improve test coverage

### CODE REVIEW

**Review by DmitryKuzmenko — DISMISSED** [review]

**Comment by DmitryKuzmenko** [comment]
re-run full all

**Comment by DmitryKuzmenko** [comment]
@sathieu thank you for PR! Changes look good just let's wait for full test suite including slow tests to ensure it works on Debian 9 and 10.

**Comment by sathieu** [comment]
@DmitryKuzmenko Could you force a re-run :running_woman:  of [the failed check](https://jenkinsci.saltstack.com/job/pr-centos8-py3/job/PR-57684/2/display/redirect). It should not be affected by this change. Thx

**Comment by sathieu** [comment]
The failure is because of  #57722. Not related to this PR. @DmitryKuzmenko Could it be marked merge-ready?

**Comment by sathieu** [comment]
Rebased on top of #57917.

**Review by DmitryKuzmenko — APPROVED** [review]

**Pull request merged**
