### PR TITLE
Updated list_users to query for 16 users as that is what DRACs support. ...

### PR DESCRIPTION
**Pull request by PeterS242**
... Cleaned up the DRAC racadm output/input handling for list_users.

I've tested this on Dell PowerEdge 2950 (very old hardware) and PowerEdge 730 (very new hardware.)

### CODE REVIEW

**Comment by jfindlay** [comment]
@PeterS242, do you consider this a fix for a bug?  Should it be applied to the current release branches?

**Comment by PeterS242** [comment]
In the **EPEL 6** RPM version that I'm running, which is **2014.7.1**, there is no `drac.py` at all.  However, I see that there is one in the **2015.2** branch.

Without this fix, the `drac.py` will not function on brand-new **Dell** hardware (**PowerEdge R730xd** in my case.)  Ultimately a lot more work will have to go into this module for it to work with Dell hardware going forward as the reason it is actually breaking is that the results coming back from the `racadm` command include a warning:

>RAC1168: The RACADM "getconfig" command will be deprecated in a
>future version of iDRAC firmware. Run the RACADM 
>"racadm get" command to retrieve the iDRAC configuration parameters.
>For more information on the get command, run the RACADM command
>"racadm help get".

At some point more code will be needed to switch to this alternate form of commands to `racadm` as only newer systems will be using it.

**Comment by PeterS242** [comment]
In other words, in the release candidate of **2015.2**, the `drac.py` is broken on new Dell servers _without_ this fix.

**Comment by jfindlay** [comment]
@PeterS242, thanks for the information.  In the future, please feel free to submit bug fixes directly against the oldest release branch it applies to, see http://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

**Comment by jfindlay** [comment]
@PeterS242, do you think you can get the [test error](https://jenkins.saltstack.com/job/salt-pr-rs-cent7-n/2565/testReport/junit/unit.modules.drac_test/DracTestCase/test_list_users/)?  It looks to be a simple change.  If not, then I can fix it, thanks.

**Comment by PeterS242** [comment]
@jfindlay I will do what I can to provide a back-port to the non-develop branch as well, and to determine why those unit tests are failing.

I also discovered immediately after commiting that the `range` part needs to be 1 to **17** as opposed to my commited **16**--I found this after-the-fact that `16` is not within the set unless the range is `17`.  I'm very familiar with **for** loops under **C**, **Perl**, etc, however on **Python** for some reason it didn't occur to me to consider this!  Should we just deny this commit and I'll work on all the above bits and re-commit?  I'm uncertain what the correct process is.

**Comment by jfindlay** [comment]
@PeterS242.  You can add or rewrite commits on the same branch that you have used in this pull request.  Once you push those changes to your github account, they will be automatically updated here.  For now, @rallytime or I can just backport your changes to the 2015.2 branch.

Depending on your git knowledge you could do this yourself, but if not, please don't worry about it.  I consider myself an intelligent person and it took me a long time before I became comfortable with git (and github)'s workflow.  We have instructions about which branch to choose here, http://docs.saltstack.com/en/latest/topics/development/contributing.html.  I am always looking for ways to simplify that doc; to get more power into the hands of our users and contributors.

Thanks for your attention to this issue.

**Comment by PeterS242** [comment]
@jfindlay I'm starting to think that the failures in **jenkins/salt-pr-rs-cent7-n** and **jenkins/salt-pr-rs-ubuntu14.04-n** are due to the parameters in the Unit tests themselves.  Specifically the code at https://github.com/saltstack/salt/blob/develop/tests/unit/modules/drac_test.py#L94

    def test_list_users(self):
        '''
        Test for list all DRAC users
        '''
        mock = MagicMock(return_value={'retcode': 0,
                                       'stdout': 'cfgUserAdminUserName=value'})
        with patch.dict(drac.__salt__, {'cmd.run_all': mock}):
            self.assertEqual(drac.list_users(), {'value': {'index': 11}})

I think because I updated the `index` to be able to use **16** user slots perhaps the unit test is failling because it now returns **16** instead of **11**.  Should I patch the unit test code as well?

**Comment by jfindlay** [comment]
@PeterS242, yeah, that would be awesome, thanks.

**Comment by rallytime** [comment]
@PeterS242 Yes, please do patch that unit test. It was written against the code that you're fixing and we didn't catch that it was a bug.

Also, once that is done and it's merged in, I can backport this pull request, no problem. :)

**Comment by PeterS242** [comment]
I additionally updated the Unit test file now.

**Comment by PeterS242** [comment]
Although I don't really understand how the Mock system works (yet,) I managed to get the Unit Test scripts to run without error on a VM, which required setting the index to 16 as opposed to the original 11 or (what I thought would be correct) 17.

**Comment by jfindlay** [comment]
@PeterS242, I've been using MagicMock for several months now and there are things that still confuse me. :-)  16 makes sense because your range statement is `range(1, 17)`, which iterates over the list [1..16].

**Comment by PeterS242** [comment]
@jfindlay, @rallytime, it looks like it passed, so if you wouldn't mind commiting and/or backporting that would be great!  I'll work on figuring out how to do that in the future, time permitting.

**Comment by jfindlay** [comment]
@PeterS242, excellent, thank you.

**Pull request merged**
