### PR TITLE
Fix for temp files being left over by salt-cloud execution

### PR DESCRIPTION
**Pull request by terminalmage**
See #36482.

### CODE REVIEW

**Comment by clarkperkins** [comment]
I like that it closes the file descriptor, but this patch still doesn't remove the tmp file when it's finished

**Comment by terminalmage** [comment]
Yeah you're right, I thought I added that but I only added the `os.close()`. I'm in the process of taking care of that now.

**Comment by terminalmage** [comment]
Can you try now?

**Comment by clarkperkins** [comment]
Seems to look good, but something else isn't working in my setup - I'm guessing something in my setup just doesn't work on carbon.  (i'm setup to use boron)

**Comment by terminalmage** [comment]
Oh, I should have submitted against 2016.3, I'll do that now.

**Comment by terminalmage** [comment]
OK, I've resubmitted this PR against 2016.3 and rebased my changes on-top of it. You should now be able to try this directly on a 2016.3 release now.

**Comment by clarkperkins** [comment]
ok, looks good!

**Comment by terminalmage** [comment]
Awesome. Thanks a lot for the review and for bringing this up to begin with.

**Pull request merged**
