### PR TITLE
Verify the key has a value.

### PR DESCRIPTION
**Pull request by ryanwohara**
https://github.com/saltstack/salt/issues/21391

### CODE REVIEW

**Comment by jfindlay** [comment]
@ryanwohara, thanks for the fix.  In the future, please feel free to merge fixes directly against release branches as they are regularly merged forward to keep all branches in sync, see http://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

**Comment by ryanwohara** [comment]
Thank you @jfindlay. I appreciate the feedback and the link.

**Comment by jfindlay** [comment]
@ryanwohara, there's just one [lint error](https://jenkins.saltstack.com/job/salt-pr-lint-n/3366/violations/file/salt/utils/dictupdate.py/).

**Comment by ryanwohara** [comment]
Thanks again @jfindlay! That's what I get for using nano.

**Comment by jfindlay** [comment]
@ryanwohara, lol, no problem.  Thanks for the fix.

**Comment by rallytime** [comment]
This particular code has been refactored in develop, so this is not back-porting cleanly. I think a fix directly to the 2014.7 branch would probably be better, rather than trying to get the backport to play nicely.

**Comment by ryanwohara** [comment]
Thank you @rallytime :+1:

**Comment by rallytime** [comment]
Nah, thank you @ryanwohara for redoing the fix for the 2014.7 branch! :) 

Once your PR gets merged, we'll merge it forward into 2015.2, so the fix will be everywhere. Cheers!

**Pull request merged**
