### PR TITLE
allow passing args to saltutil.runner

### PR DESCRIPTION
**Pull request by gtmanfred**
### What does this PR do?
Allow for the passing of non keyword arguments, so that runners like the survey runner can be used from the saltutil.runner module.

### What issues does this PR fix or reference?
#38977

### Previous Behavior
File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low
data['return'] = self.functions[fun](*args, **kwargs)
TypeError: cmd() takes at least 1 argument (0 given)

### New Behavior
Args passed in as args, and routed to RunnerClient.cmd() as arg.

### Tests written?

No

### CODE REVIEW

**Review by whiteinge — CHANGES_REQUESTED** [review]
I'd suggest `arg` (singular) to match RunnerClient. Not that we're super consistent with this but I think the public-facing argument name should match.

**Comment by gtmanfred** [comment]
I am going to move this to be off of develop, and deprecate kwargs too then.

**Review by whiteinge — APPROVED** [review]
Good stuff.

**Comment by gtmanfred** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Review by terminalmage — APPROVED** [review]

**Pull request merged**
