### PR TITLE
file.retention_schedule state

### PR DESCRIPTION
**Pull request by ahammond**
### What does this PR do?

Adds file.retention_schedule state
### What issues does this PR fix or reference?

New feature. Please update the `.. versionadded:` in the docstring when / if it gets merged.
### Tests written?

Yes: full UT coverage.

I handles time and uses recursion... twice so... testing was necessary to debug.

### CODE REVIEW

**Comment by rallytime** [comment]
@ahammond This looks good and thank you for writing these new tests!

Can you clean up these [lint errors](http://166.78.178.63:8080/job/PR/job/salt-pr-lint-n/1286/violations/)? Also, FWIW, the versionadded tag should be `Carbon`.

**Comment by ahammond** [comment]
@rallytime lint errors cleaned up (thanks for that link!) and versionadded tag set to Carbon.

**Comment by rallytime** [comment]
Thanks!

**Comment by rallytime** [comment]
Oops. Accidentally closed.

**Pull request merged**
