### PR TITLE
- Added new proxy module for managing Blue Coat SSL Visibility devices.

### PR DESCRIPTION
**Pull request by spenceation**
- Added execution and state module for managing domain name, distinguished name, and IP address lists for Blue Coat SSL Visibility devices.

### What does this PR do?
This pull request adds the modules needed to manage Blue Coat SSL Visibility devices as proxy minions.

### What issues does this PR fix or reference?
N/A

### New Behavior
A new module to manage Blue Coat SSL Visibility devices is added. It include execution and state modules to manage configuration lists on the device.

### Tests written?
No

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by cachedout** [comment]
@cro or @mirceaulinic Could one or both of you help out here, possibly?

**Comment by cro** [comment]
@spenceation Thanks for this!  It looks like the remaining test failures are not related.

Would you be willing to change the module/proxy/state names to something more descriptive like `bluecoat_sslv`?  `sslv` is somewhat short and non-descriptive, I'm concerned that in the future folks searching for this support may not find it.

**Review by cro — CHANGES_REQUESTED** [review]
See my comment regarding requested name change.

**Comment by spenceation** [comment]
@cro That change sounds good to me. Makes sense to make it more descriptive.

**Review by cro — APPROVED** [review]

**Pull request merged**
