### PR TITLE
[minionproxy] example modules fixes

### PR DESCRIPTION
**Pull request by arthurzenika**

### CODE REVIEW

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cro** [comment]
Hey @arthurlogilab I think these items are fixed in another PR that hasn't been merged forward yet.  I will leave this PR open for now in case I'm mistaken.

**Comment by cro** [comment]
Or..maybe we'll just merge it. :smile:

**Comment by cachedout** [comment]
Heh. Sorry. ;]

**Pull request merged**
