### PR TITLE
Add watch_in integration test

### PR DESCRIPTION
**Pull request by Ch3LL**
### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/43549

### CODE REVIEW

**Review by rallytime — APPROVED** [review]
Well done

**Comment by rallytime** [comment]
@Ch3LL The Python 3 tests didn't like this so much, unfortunately.

**Comment by cachedout** [comment]
@Ch3LL Saw the commits you pushed but it appears as though the Py3 tests still aren't quite there. Is this passing locally?

**Comment by Ch3LL** [comment]
I re-submitted another fix and I don't think it re-started the tests but looks like they are going now. So will wait for results here.

**Pull request merged**
