### PR TITLE
Added the ability to manage Zabbix usergroup permissions

### PR DESCRIPTION
**Pull request by q1x**
### What does this PR do?
Zabbix 3.0.0 and newer have the ability to list user group permissions via the `usergroup.get` method.
Using this, we can detect if user group permissions should be updated while applying a state.

This PR adds the ability to manage Zabbix user group permissions via the rights attribute.

State example:
```
Zabbix users:
  zabbix_usergroup.present:
    - rights:
       - { id: "8", permission: "0" }
       - { id: "6", permission: "3" }
```

### What issues does this PR fix or reference?
None

### Previous Behavior
User group rights were only setup during user group creation and changes in the state files would not be propagated.

### New Behavior
User group rights are compared to the desired state and updated if needed.

### Tests written?
No

### CODE REVIEW

**Review by cachedout — CHANGES_REQUESTED** [review]
There are some minor lint fixes that need to be made here, please: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/10085/violations/file/salt/states/zabbix_usergroup.py/

**Comment by q1x** [comment]
Thanks for the review, I've corrected the cause of the lint errors. Can we retry?

**Comment by cachedout** [comment]
@q1x Yes. The tests are running now and will take about ninety minutes.

**Comment by q1x** [comment]
Hi @cachedout, is this ok now or do I need to do anything else to get the PR approved?

**Comment by q1x** [comment]
Thank you for your time, @cachedout !

**Pull request merged**
