### PR TITLE
Allow scheduled job to run if run time is in the past

### PR DESCRIPTION
**Pull request by YuriGrigorov**
### What does this PR do?

Allows scheduled job to run if run time is in the past for `interval` and `when` criteria (like it was before #39527).

### What issues does this PR fix or reference?

#40022

### Tests written?

No

### CODE REVIEW

**Comment by cachedout** [comment]
@garethgreenaway how does this look to you?

**Comment by garethgreenaway** [comment]
@cachedout Looks good.  The only thing I'm uncertain about is the scenario of when `seconds` would be equal to -1.

**Comment by YuriGrigorov** [comment]
1217: if `seconds` is -1 then job will fire (window between -1 and 0 is when wee allow jobs to run).
1274: while -1 is in that window we don't show additional message that runtime is missed.

**Comment by garethgreenaway** [comment]
I'd need to go back and look at previous versions, but before once `seconds` reached zero then the job would fire.  I don't recall any point in the sequence when it would reach -1, that would indicate something went wrong.

**Comment by YuriGrigorov** [comment]
I agree.

**Comment by YuriGrigorov** [comment]
I've removed this extra second.

**Pull request merged**
