### PR TITLE
git_pillar: Fix all_saltenvs on base env

### PR DESCRIPTION
**Pull request by sathieu**
### What does this PR do?

Fixes #50768.

### What issues does this PR fix or reference?

PR #50768.

### Previous Behavior
```
minion:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Specified SLS 'projects.gitlab' in environment 'prod' is not available on the salt master
```

### New Behavior

State applies succesfully.

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by sathieu** [comment]
After #51317 was merged, the [following](https://github.com/saltstack/salt/blob/2018.3.4/salt/pillar/git_pillar.py#L464-L467) was not matching any pillar_dir:
```python
            pillar_roots.extend(
                [d for (d, e) in six.iteritems(git_pillar.pillar_dirs)
                 if env == e and d != pillar_dir]
            )
```

because `e` = `base` and `env` = `prod` (i.e the `all_saltenvs` value)

**Comment by sathieu** [comment]
@terminalmage please review

**Review by terminalmage — COMMENTED** [review]
@saltstack/team-core are we still accepting pull requests to the 2018.3.4 branch?

**Comment by sathieu** [comment]
Please accept this for 2018.3.4, otherwise #50768 is broken.

**Comment by thatch45** [comment]
We are not, it is in final freeze. Does this only impact the all_saltenvs feature?

Also, am I reading this right? Did we accept a feature into 2018.3.4?

**Comment by sathieu** [comment]
@thatch45 this only impact the all_saltenvs feature, which was implemented in #50768 for git_pillar but is in gifts since 2018.3.0.

**Comment by thatch45** [comment]
Thank you for the clarification, I am afraid that it would stall the release quite a bit at this point to get this in.

**Comment by sathieu** [comment]
Sad. Would this mean that a known broken feature will be is 2018.3.4? Maybe it's better to revert it then?

**Comment by thatch45** [comment]
as it is a very new feature I think it is worth pointing it out, but I think we should be fine. Sorry this did not get in in time! The point release was already past due....

**Comment by sathieu** [comment]
OK. Thanks for releasing it soon.

I will make a new PR on the 2018.3 branch and hope 2018.3.5 and 2019.2.1 will come soon.

**Comment by dwoz** [comment]
@sathieu Since you are going to create a new PR to 2018.3, I'm closing this one. Thanks for understanding we're pushing 2018.3.4 as soon as possible.

**Pull request closed without merging**
