### PR TITLE
Fixes to debian_ip

### PR DESCRIPTION
**Pull request by garethgreenaway**
Fixing a typo in the debian_ip module.

### CODE REVIEW

**Comment by jfindlay** [comment]
@garethgreenaway, should this go into 2014.7 or 2015.2 instead?

**Comment by garethgreenaway** [comment]
@jfindlay 2015.2.  It's a fix for a bug I introduced in develop.

**Comment by rallytime** [comment]
@garethgreenaway This actually isn't backporting cleanly to 2015.2 and the merge conflict has code that doesn't exist on 2015.2. Therefore, I will merge this into develop for sure but I don't think I will backport this particular fix.

If there is something that was introduced in 2015.2 that perhaps needs to be addressed, would you mind taking a look there and fixing it on that branch?

**Comment by rallytime** [comment]
Actually, I misunderstood you I think earlier. You said you introduced the bug in develop, so we only need to fix the bug that is in develop. The 2015.2 threw me! Thanks @garethgreenaway!

**Comment by garethgreenaway** [comment]
My fault.  I misspoke I said 2015.2 when in fact it's develop and not 2015.2, apologies for the confusion.

**Comment by rallytime** [comment]
All good! Thanks again. :)

**Pull request merged**
