### PR TITLE
Master fix aptpkg systemd call

### PR DESCRIPTION
**Pull request by brejoc**
### What does this PR do?

Sets a `--description` for the systemd-run command called by aptpkg to avoid long description strings that would cause crashes.
The description comes from `__name__` and it would be `salt.modules.aptpkg`

### What issues does this PR fix or reference?

Fixes: aptpkg module causes systemd to crash in Ubuntu 18.04.
When no description is provided to systemd-run, the description is autogenerated from the apt-get command.
If we have a long list of packages the description will be longer than what systemd-run supports and it will crash (https://github.com/systemd/systemd/commit/a7419dbc59da5c8cc9e90b3d96bc947cad91ae16)

Setting the description ourselves prevents this even if the systemd doesn't have the fix.

### Previous Behavior

See above

### New Behavior

Sets the description to `salt.modules.aptpkg`

### Tests written?

Yes

### CODE REVIEW

**Comment by brejoc** [comment]
This PR replaces https://github.com/saltstack/salt/pull/54077.

**Review by cmcmarrow — DISMISSED** [review]

**Comment by brejoc** [comment]
I've just merged master again. Anything else that needs to be done?

**Review by DmitryKuzmenko — DISMISSED** [review]

**Comment by DmitryKuzmenko** [comment]
@brejoc could you please resolve merge conflicts?

**Comment by brejoc** [comment]
@DmitryKuzmenko PR now complies with black formatting.

**Review by DmitryKuzmenko — APPROVED** [review]

**Pull request merged**
