### PR TITLE
new Xen cloud driver

### PR DESCRIPTION
**Pull request by grep4linux**
### What does this PR do?
Add new xen cloud driver

### Tests written?

No

### CODE REVIEW

**Review by gtmanfred — CHANGES_REQUESTED** [review]
This looks great!

I only have one request, please add the node caching stuff to this driver.

https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/nova.py#L1062
https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/nova.py#L557

https://docs.saltstack.com/en/latest/topics/cloud/misc.html#salt-cloud-cache

Thanks,
Daniel

**Review by gtmanfred — APPROVED** [review]

**Comment by grep4linux** [comment]
Cloud caching options added as requested by @gtmanfred

**Review by cachedout — CHANGES_REQUESTED** [review]
This has a large number of lint errors that need to be fixed before we can get this in: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/10412/violations/file/salt/cloud/clouds/xen.py/

**Comment by grep4linux** [comment]
I'll get the lint errors cleaned up. thanks.

**Comment by grep4linux** [comment]
cleaned up PEP8 issues, and pylint problems.

**Comment by grep4linux** [comment]
I fixed the majority of the errors. Please let me know if I need to make
further changes.

Thanks,


Raine Curtis

Training Services Manager / Services Engineer

SaltStack, Inc.

web: http://www.saltstack.com/training

mobile: 801-615-3480

office: 801-341-1861

email: rcurtis@saltstack.com

**Comment by gtmanfred** [comment]
Looks like there are still some more

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/10437/violations/file/salt/cloud/clouds/xen.py/

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/10437/console (you can ignore the output pylint errors)

Thanks,
Daniel

**Comment by grep4linux** [comment]
Okay, I'll work on it again. Thanks!


Raine Curtis

Training Services Manager / Services Engineer

SaltStack, Inc.

web: http://www.saltstack.com/training

mobile: 801-615-3480

office: 801-341-1861

email: rcurtis@saltstack.com

**Comment by sergeizv** [comment]
1ba2d4e80582c8d249ea5b0af02a1481cedf6971 adds cloud cache index support, but nodes' information still isn't cached, so stuff like cloud roster won't work. The EC2 driver is a good example of implementing that:
https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/ec2.py

**Comment by grep4linux** [comment]
Updates: 

- Cleaned up more to pep8 standards.
- Fixed cloud cache functions

**Comment by grep4linux** [comment]
I just pushed new changes to the xen.py.

Let me know if there are still problems.

Thanks.


Raine Curtis

Training Services Manager / Services Engineer

SaltStack, Inc.

web: http://www.saltstack.com/training

mobile: 801-615-3480

office: 801-341-1861

email: rcurtis@saltstack.com

**Comment by gtmanfred** [comment]
Looks like you just have 2 more pylint errors and you should be all done!

```
00:21:36.771 ************* Module salt.cloud.clouds.xen
00:21:36.771 salt/cloud/clouds/xen.py:291: [C0325(superfluous-parens), ] Unnecessary parens after u'not' keyword
00:21:36.772 salt/cloud/clouds/xen.py:450: [C0325(superfluous-parens), ] Unnecessary parens after u'not' keyword
```

**Comment by grep4linux** [comment]
superfluous-parens removed.

**Review by cachedout — APPROVED** [review]

**Pull request merged**
