### PR TITLE
Moar Py3

### PR DESCRIPTION
**Pull request by s0undt3ch**
/cc @saltstack/team-core, @thatch45, @cachedout: There's a protocol breakage in this PR, see https://github.com/saltstack/salt/commit/56f2668fb8dcc818eefdec388adc071e94cf07aa

### CODE REVIEW

**Comment by s0undt3ch** [comment]
@rallytime: yes, and that's a port of that with class support. There's still no near solution to upgrade salt testing, hence the port. It can probably be removed there now too.

**Comment by rallytime** [comment]
Ah ok, cool! That makes sense. :)

**Comment by s0undt3ch** [comment]
Since we're breaking the protocol, perhaps we should take the opportunity to switch to use_bin_type and encoding for all msgpack related dumps/loads...

**Comment by cachedout** [comment]
This appears to be a protocol incompatibility that would break our upgrade contract with users which says, in effect, it's always safe to upgrade the master(s) first. We have broken this in the past, but it's been a few years. IMHO, this begs the question of whether we want to *try* to maintain comptability or whether we're OK with a hard break. Personally, I'd like to see us do whatever we can to maintain it. I'm curious what others think here.

**Comment by s0undt3ch** [comment]
Oh, believe me, I would also love to maintain that upgrade contract.

Perhaps we add additional data to the serialized object to know how we should load it, release that in a minor release, and tell the users that they must upgrade to that release prior to the next major release? This is, if we find a way to load the data in the correct type after losing it when serializing...

**Comment by thatch45** [comment]
I think this may also break the fileserver, the reason I did not make this change originally was because we can't assume that messages are utf-8 like this when transmitting files, since they need to maintain a byte for byte representation.

**Comment by s0undt3ch** [comment]
@thatch45: yes, but on python 3, we really need bytes vs string differentiation, hence the `use_bin_type` to separate those and handle them differently.

**Comment by s0undt3ch** [comment]
In py2 we got away with it because they were kind of the same....

**Comment by s0undt3ch** [comment]
On February 27, 2017 6:41:46 PM GMT+00:00, Thomas S Hatch <notifications@github.com> wrote:
>I think this may also break the fileserver, the reason I did not make
>this change originally was because we can't assume that messages are
>utf-8 like this when transmitting files, since they need to maintain a
>byte for byte representation.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/saltstack/salt/pull/39649#issuecomment-282810204

Also, this was a fix to the fileserver, under py3 :)
Pedro Algarvio @ Phone

**Comment by thatch45** [comment]
How is the breakage characterized? Can master and minion just not talk to each other unless they both have this? If so we can't do it, we will need to figure out a deprecation path....

**Comment by damon-atkins** [comment]
If you do break compatibility suggest you look back at this thread
https://github.com/saltstack/salt/issues/36303#issuecomment-248542880

**Comment by s0undt3ch** [comment]
I will be working on this some more in order not break compatibility.

**Comment by cachedout** [comment]
@s0undt3ch Sounds good. Might want to close this in the meantime. It already has a number of merge conflict.

**Comment by s0undt3ch** [comment]
Removed the commit that caused the protocol breakage for now.

**Comment by s0undt3ch** [comment]
Who would have known, the PR jobs passed :)

**Comment by s0undt3ch** [comment]
Selfie...

**Pull request merged**
