### PR TITLE
Report failures and error information from tuned module

### LINKED ISSUE #60500: [BUG] tuned state does not report error
**Description**
If `tuned-adm profile xyz` fails, the output is ignored. If setting the state, the returned `new` value is `False` and the state is reported as changed and Succeeded.

If the profile does not exist at all, a Traceback is returned. This could perhaps be formatted nicer, at least for this known error condition.

Minor: The state example does not appear to be formatted correctly.

**Setup**
```
tunedtest_invalid:
  tuned.profile:
    - name: invalid
tunedtest_noexist:
  tuned.profile:
    - name: noexist
```
testit.sls
```
include:
  - tunedtest.invalid
  - tunedtest.noexist
```

**Steps to Reproduce the behavior**
Create a malformed custom tuned profile and use the state to set it. I had two `include` keywords in `[main]`.

**Expected behavior**
The state's response could include useful information (not currently returned by module) and at a minimum indicate an error occurred (not Succeeded/changed).

**Screenshots**
<details><summary>tuned-adm output</summary>

```
# tuned-adm profile invalid
Cannot load profile(s) 'invalid': (u"Cannot parse '/usr/lib/tuned/invalid/tuned.conf'.", DuplicateError('Duplicate keyword name at line 4.',))
# tuned-adm profile noexist
Requested profile 'noexist' doesn't exist.
```
</details>
<details><summary>tuned.profile module</summary>

```
# salt `hostname` tuned.profile invalid
minion:
    False
ERROR: Minions returned with non-zero exit code
# salt `hostname` tuned.profile noexist
minion:
    False
```
</details>
<details><summary>state.sls</summary>

```
minion:
----------
          ID: tunedtest_invalid
    Function: tuned.profile
        Name: invalid
      Result: True
     Comment: The state of "invalid" was changed!
     Started: 17:20:49.600399
    Duration: 2837.899 ms
     Changes:   
              ----------
              new:
                  False
              old:
                  virtual-guest
----------
          ID: tunedtest_noexist
    Function: tuned.profile
        Name: noexist
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/state.py", line 2172, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1241, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2274, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
                  return callable(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2289, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2322, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/states/tuned.py", line 49, in profile
                  raise salt.exceptions.SaltInvocationError("Invalid Profile Name")
              salt.exceptions.SaltInvocationError: Invalid Profile Name
     Started: 17:20:52.440581
    Duration: 1464.783 ms
     Changes:   

Summary for minion
------------
Succeeded: 1 (changed=1)
Failed:    1
------------
Total states run:     2
Total run time:   4.303 s
```
</details>

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.31.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by leeclemens**
Replace stdout in cases of success with known value for state to evaluate.
Update response handling in states.

### What does this PR do?
Returns cmd results from module for better processing and error handling.

### What issues does this PR fix or reference?
Fixes: #60500

### Previous Behavior
Errors were ignored and cmd output was ignored, specifically from the state. State was reported as successful/changed in some failed executions.

### New Behavior
The module returns the full output from the cmd and modifies it when useful (success with the new expected profile being returned in stdout). Report failed execution as failure back to state.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Comment by leeclemens** [comment]
@dwoz can you clarify what you mean by Abandoned? I don't see any feedback from SaltStack beyond tags and being Approved in 2021.

**Comment by dwoz** [comment]
@leeclemens We are making an effort to clean up out-dated PRs. This was closed purely because there was no activity in 2 years. If you want to get it into a release please rebase and re-open the PR. We'll get it in.

**Comment by leeclemens** [comment]
@dwoz thanks for the feedback. I suppose I was confused by the "if they want to see it through to the end in one release cycle" comment since you closing the PR was the first feedback I received on either the Issue or the PR created over 2 years ago. The PR was submitted 3 days after opening the Issue. I also marked this PR for review and the first response was to close it as Abandoned.

**Comment by leeclemens** [comment]
It seems like the rebase issue was that the tests were moved to pytests about 1.5 years after the PR was created. I copied them and submitted #65720 .

**Pull request closed without merging**
