### PR TITLE
If the thin does not match, then redeploy, don't error

### PR DESCRIPTION
**Pull request by thatch45**
### What does this PR do?

@plastikos is there any reason not to do this? If the thin is bad we can just redeploy right?
### What issues does this PR fix or reference?
#34509
### Previous Behavior

Threw an error
### New Behavior

Silently recovers

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Could we enter in a non ending loop if something is way wrong and we just keep re-deploying?
Or, in this context, my comment is just absurd?

**Comment by thatch45** [comment]
This has also been my concern, that if the tarball fails to deploy over and over again what are the implications? I don't think it should be an issue, since we very rarely have gotten reports of the checksum missmatch error. I think the optimal solution would be to add a notification to the user that it is not downloading properly when it retries

**Comment by plastikos** [comment]
Seems reasonable to fold this into a re-deploy.

**Comment by thatch45** [comment]
Thanks @plastikos ! Also I think it is good that more people are aware of this change in case something goes awry. But I think this should be fine

**Pull request merged**
