### PR TITLE
Workaround for grains loading

### LINKED ISSUE #22561: since recently, grains or pillar can be empty in certain sls executions
I have not a simple reproduction test case, but in many sls executions i get
```
Rendering SLS 'base:makina-states.controllers.salt_master' failed: Jinja variable 'dict object' has no attribute 'os'
/var/cache/salt/salt-minion/files/base/makina-states/_macros/salt.jinja(689):

```

### PR DESCRIPTION
**Pull request by kiorky**
This fixes #22561

### CODE REVIEW

**Comment by kiorky** [comment]
cc @jacksontj

**Comment by kiorky** [comment]
damn conlict :(

**Comment by kiorky** [comment]
@thatch45 series of patches also address the problem in a different way, i have merged it and it seems to also work, so i close it for now, thx @thatch45 !

**Comment by kiorky** [comment]
i mean saltstack/salt#22723

**Comment by kiorky** [comment]
Damn seems its falling again: https://travis-ci.org/makinacorpus/makina-states/builds/58974787

**Comment by thatch45** [comment]
Thanks @kiorky it took me a while to get around to testing this one

**Comment by jacksontj** [comment]
This patch seems like a really bad workaround... why is the loader being called with empty grains? And why should the loader enforce that it could never happen? Do you have a specific case to reproduce this grains not loading?

**Comment by kiorky** [comment]
As i said in the commit message, it's a workaround :).
With the help of makina-states case, i reproduced a lot.
To reproduce ...
Well you ll have to install makina-states and install for instance the makina-states.controllers.salt_master SLS in 'salt' mode to reproduce it.

It fails here: https://github.com/makinacorpus/makina-states/blob/master/_macros/salt.jinja#L711
The macro is loaded from here : https://github.com/makinacorpus/makina-states/blob/master/controllers/salt_master-standalone.sls#L15

As you see, nothing really spectacular, but the grains {} is empty when coming in the macro, when calling from an highstate;..

**Comment by kiorky** [comment]
oups, ping: @jacksontj

**Comment by thatch45** [comment]
Thanks for the additional data @kiorky ! I think we can get a better fix in, but it does need to be fixed

**Pull request merged**
