### PR TITLE
Fix zypper upgrade fromrepo again

### PR DESCRIPTION
**Pull request by pkwestm**
As asked in #53687, reopend pull request to master branch.

### What does this PR do?
See #53687
 
### What issues does this PR fix or reference?
See #53687

### Tests written?
Yes

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by dwoz** [comment]
@pkwestm Thanks!

**Comment by dwoz** [comment]
@pkwestm please see this test failure: https://jenkinsci.saltstack.com/job/pr-centos7-py2/job/PR-55705/1/testReport/junit/unit.modules.test_zypperpkg/ZypperTestCase/test_upgrade_success/

**Comment by pkwestm** [comment]
Was abit fast in my port from previous PR. Hopefully fixed in latest commit :)

**Comment by dwoz** [comment]
re-run full centos

**Review by dwoz — APPROVED** [review]

**Pull request merged**
