### PR TITLE
Improve macOS homebrew cask support

### PR DESCRIPTION
**Pull request by cdalvaro**
### What does this PR do?

When listing Homebrew packages, cask packages do not have the right namespace when they are from a tap different from the default one.

This PR fixes this issue recovering the right namespace for each cask package.

**Note:** This PR comes from #53756 

### Previous Behavior

```sh
local:
----------
          ID: FiraCode Nerd Font
    Function: pkg.installed
        Name: homebrew/cask-fonts/font-firacode-nerd-font
      Result: False
     Comment: The following packages failed to install/update: homebrew/cask-fonts/font-firacode-nerd-font
     Started: 17:59:08.334054
    Duration: 14324.087 ms
     Changes:
```

### New Behavior

```sh
local:
----------
          ID: FiraCode Nerd Font
    Function: pkg.installed
        Name: homebrew/cask-fonts/font-firacode-nerd-font
      Result: True
     Comment: All specified packages are already installed
     Started: 18:56:36.057920
    Duration: 48438.613 ms
     Changes:
```

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by weswhet** [comment]
I like this idea from the previous PR. 

```
if name.startswith('caskroom/cask/'):
  salt.utils.versions.warn_until(
            'Neon',
            'The \'caskroom/cask/\' namespace for brew-cask packages'
            'is deprecated. Use \'homebrew/cask/\' instead.'
        )
  name = name.replace("caskroom/cask/", "homebrew/cask/")
```

**Comment by weswhet** [comment]
@eligundry any thoughts on this as you originally added support for casks?

**Comment by cdalvaro** [comment]
ping @weswhet @eligundry @xeacott

**Comment by weswhet** [comment]
LGTM.

**Review by xeacott — APPROVED** [review]

**Comment by cdalvaro** [comment]
Will this PR be merged?

**Comment by waynew** [comment]
Hey @cdalvaro - as you may have heard, we're changing to a single branch release strategy. What does that mean for this PR?

Well, you've got tests so 👍 

We will be working to migrate all PRs from non-`master` branches to `master`. If you'd like to get your PR in sooner, please rebase it against `master`, force push to your branch, and edit this PR to be against `master`. If you need any help with any of those steps, please let us know!

**Comment by cdalvaro** [comment]
> Hey @cdalvaro - as you may have heard, we're changing to a single branch release strategy. What does that mean for this PR?
> 
> Well, you've got tests so 👍
> 
> We will be working to migrate all PRs from non-`master` branches to `master`. If you'd like to get your PR in sooner, please rebase it against `master`, force push to your branch, and edit this PR to be against `master`. If you need any help with any of those steps, please let us know!

I'll begin working on it!

**Comment by dwoz** [comment]
re-run full all

**Comment by cdalvaro** [comment]
I would like to know if this PR will be finally merged

**Comment by cdalvaro** [comment]
Please @xeacott, could you revise this PR, it was opened three months ago.

Thank you in advance.

**Review by dwoz — APPROVED** [review]

**Review by Akm0d — APPROVED** [review]

**Comment by cdalvaro** [comment]
✅ All tests are OK now, please @xeacott, could you merge this PR??

Thank you in advance!

**Comment by weswhet** [comment]
Thanks @dwoz 🚀 

Happy holidays! 🎄

**Comment by cdalvaro** [comment]
Thank you very much @dwoz !!!

Happy holidays!

**Pull request merged**
