### PR TITLE
Switch OpenNebula to salt.utils.cloud.bootstrap()

### PR DESCRIPTION
**Pull request by techhat**
@rallytime, would you please take a look at this?

### CODE REVIEW

**Comment by rallytime** [comment]
I am actually working on getting this function fixed up in my OpenNebula work that I am doing. This function doesn't actually work as-is because in the examples that I have tried, there is a key-error in `data['private_ips'][0]` on the first line and so it will need to be changed. I am still working on it.

I was going to backport my changes to this function from develop to 2015.8 when I was finished.

**Comment by techhat** [comment]
@rallytime do you want me to close this then?

**Comment by rallytime** [comment]
Yeah I think so. Sorry for the extra work. :(

**Comment by techhat** [comment]
No worries.

**Pull request closed without merging**
