### PR TITLE
Update to mixins for Salt tests

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Updating the assert tests for develop based on changes from #41569 

### What issues does this PR fix or reference?
N/A

### Previous Behavior
Various Salt assert tests only checked the first element in return data, this updates them to check all elements.

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Review by gtmanfred — APPROVED** [review]

**Comment by gtmanfred** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
The test runs on these VMs keep timing out. Is that expected with this change?

**Comment by garethgreenaway** [comment]
@rallytime That's a weird one.  It shouldn't be timing out and it shouldn't be waiting for anything.

**Comment by rallytime** [comment]
@garethgreenaway I updated the branch to see if that changes anything.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@garethgreenaway Something is wrong with this one. We're just not getting any test results. Can you please revisit it?

**Comment by garethgreenaway** [comment]
@cachedout Yup!  I'll take a look.

**Comment by garethgreenaway** [comment]
@cachedout @rallytime Final failures on this are warnings about deprecated functions for Py3:
```
Traceback (most recent call last):
  File "/testing/tests/integration/states/test_git.py", line 621, in test_renamed_default_branch
    'New branch \'develop\' was checked out, with origin/develop '
  File "/testing/tests/support/mixins.py", line 603, in assertSaltCommentRegexpMatches
    return self.assertInSaltReturnRegexpMatches(ret, pattern, 'comment')
  File "/testing/tests/support/mixins.py", line 623, in assertInSaltReturnRegexpMatches
    self.assertRegexpMatches(saltret, pattern)
  File "/testing/tests/support/unit.py", line 314, in assertRegexpMatches
    'assertRegex'
DeprecationWarning: The assertRegexpMatches() function will be deprecated in python 3. Please start using assertRegex() instead.
```

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
Thanks @garethgreenaway!

**Pull request merged**
