### PR TITLE
gitfs: Add two new options to affect saltenv mapping

### LINKED ISSUE #34775: Please allow users to disable branch environment mapping in GitFS
### Description of Issue/Question

GitFS currently treats branches as environment and allows users to blacklist and whitelist env names. It would be wonderful if one could simply turn off the environment mapping altogether as nothing but pain comes from it.

### PR DESCRIPTION
**Pull request by terminalmage**
This adds 2 new config options:

- ``gitfs_disable_saltenv_mapping`` - This allows a user to disable the environment mapping logic and rely solely on per-saltenv configuration
- ``gitfs_ref_types`` - This allows individual ref types to be ignored

It also includes a performance improvement in retrieving tree objects matching the desired ref name. Before, we would iterate through the different refs and check if the name matched the desired ref's name.  Now we just check for a head/tag ref based on the ref path in the gitdir (e.g. ``refs/remotes/origin/master`` or ``refs/tags/v1.2.3``). This prevents us from needlessly iterating through all refs until a match is found, which does not scale well when the number of branches and tags is larger.

I will probably backport this performance improvement to Nitrogen, because this release introduces the ability to customize the refspecs. If people use this feature, dozens/hundreds of new refs will be fetched, which could impact performace.

Resolves #34775.

### CODE REVIEW

**Comment by terminalmage** [comment]
Go Go Jenkins!

**Comment by terminalmage** [comment]
The failing unit tests are unrelated to this PR, and also were coming up when I was working on https://github.com/saltstack/salt/pull/41117. The tests are fixed there, so I can rebase once https://github.com/saltstack/salt/pull/41117 has been merged.

**Comment by rallytime** [comment]
@terminalmage Looks like this is ready for a rebase now that #41117 is merged in. :)

**Comment by terminalmage** [comment]
Rebased.

**Comment by terminalmage** [comment]
OK, the mocked opts in the unit tests were missing the two new config options. I just added them, the tests should pass now.

**Comment by cachedout** [comment]
@terminalmage Looks like merge conflicts. Could you please rebase this?

**Comment by terminalmage** [comment]
Sorry, missed this request to rebase while I was at PyCon. It's been rebased and tests are running.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by garethgreenaway** [comment]
@terminalmage Looks like two more conflicts exist on this one.

**Comment by terminalmage** [comment]
@garethgreenaway thanks, I've rebased

**Comment by garethgreenaway** [comment]
Go Go Jenkins!

**Review by cachedout — APPROVED** [review]

**Pull request merged**
