### PR TITLE
Catch a race condition...

### PR DESCRIPTION
**Pull request by thatch45**
Just catch a race condition where two procs could both make the directory making on stack trace, see #39839 comments

### CODE REVIEW

**Comment by ninja-** [comment]
@thatch45 shoudn't the jid be unique anyway?

**Comment by thatch45** [comment]
No, the jid is for the state run, the tfile will be unique to the function but the jid is a directory for all state functions executed under the singe call to state.apply

**Comment by ninja-** [comment]
okey, looks good 👍

**Comment by ninja-** [comment]
but why not create the folder in parent process anyway

**Comment by ninja-** [comment]
I am pretty sure it won't race if you move it to call_parallel :D

**Comment by thatch45** [comment]
Thats a good point, and that would likely be cleaner and faster. Let me know if this fix solves you issue and then we at least know that this fix works and we can focus on the more elegant solution.

**Comment by cachedout** [comment]
@ninja- Any final feedback here?

**Comment by thatch45** [comment]
Any way about it not having a catch he is clearly just an oversight by me, it should be in here

**Pull request merged**
