### PR TITLE
Ini issues fixed

### PR DESCRIPTION
**Pull request by Akilesh1597**
I have addressed the following issues 
Issue #16294 - No need to use 'DEFAULT_IMPLICIT' for ini files without sections. key, value pairs without nesting(a section as parent) will be considered as having no sections. They will be directly written to the file. In short, the system behaves exactly as the reporter had wanted. 

Issue #16958 - If any options are commented out instead of creating a new option, the comment shall be removed. This would help preserving the ordering of comments and their respective config option

Issue #21219 - The parse logic (_Ini.refresh) and the update logic (_Ini.update) will make sure only genuine changes are reported. Not sure what was wrong with previous logic but the current one is clearly has better performance(parse logic) , cleaner and more readable (lesser methods and classes), more maintainable(usage of ordered dict as base class with proper method overriding)

Also added the below features
1. Both '#' and ';' can be used for commenting
2. Multi line options are supported. Lines indented more than previous line shall be considered as continuation of previous line. This is a standard Ini feature

Below issues are partially fixed
Issue #22214 - Comment lines will be written exactly as they were earlier. 

Issue #21592 - Lines with unsupported syntax will be written back exactly as earlier and there shall be a space between key, '=' or ':' and value.

Only changed files are 'ini_manage.py' execution module and 'ini_managed.py' state module. 
Ignore the commits on glance/neutron. The are the result of a manual merge. 

A thorough testing is needed.

### CODE REVIEW

**Comment by Akilesh1597** [comment]
I've been working with salt for a while and started to wonder 'how do i write unit tests for my modules?', 'Where does jenkins pick them up from?'
Please create of it exists point me to a document explaining how to write and commit unit tests along with modules.

**Comment by Akilesh1597** [comment]
I've been working with salt for a while and started to wonder 'how do i write unit tests for my modules?', 'Where does jenkins pick them up from?'
Please create of it exists point me to a document explaining how to write and commit unit tests along with modules.

**Comment by Akilesh1597** [comment]
closed by mistake

**Comment by Akilesh1597** [comment]
done with manual testing

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@Akilesh1597 There are a number of failed tests here. Could you take a look?

**Comment by Akilesh1597** [comment]
Not sure what failed 'unit.utils.event_test.TestSaltEvent.test_event_timeout'

Everything else I have addressed.

**Comment by jfindlay** [comment]
@Akilesh1597, there are some more [lint errors](https://jenkins.saltstack.com/job/salt-pr-lint-n/8585/violations/) and some [unit tests](https://jenkins.saltstack.com/job/salt-pr-rs-ubuntu14.04-n/8129/#showFailuresLink) that need to be updated.  The rest_tornado failures are unrelated.  Let me know if you need any help figuring out the tests.

**Comment by Akilesh1597** [comment]
The lint is confusing.
1. It says I can not use collections.OrderedDict, which I inherit to create an Ini class. Without this the code would become too complicated and unreadable.
2. Are we not allowed to use dictionary comprehensions? Why?
3. Are we not allowed to call a generator object's next method?

Are there any alternatives for these ??

The unit tests I can take care of.

**Comment by jfindlay** [comment]
@Akilesh1597, salt needs to run on python 2.6 and python 3.  For OrderedDict, you can use `from salt.utils.odict import OrderedDict`.  It is unfortunately not possible to use a dictionary comprehension and be python 2.6 compatible, so you will need to create that with a traditional loop construct.  As for the `next` issue, you'll need to do `next(ini_gen)` to make it python 3 compatible.  Let me know if you have any other questions.

**Comment by Akilesh1597** [comment]
@jfindlay I have fixed most bugs related to ini. Two still remain(in the state module) that I have no idea why, because when I run in my system it is just fine. Can you take a look?

**Comment by jfindlay** [comment]
@Akilesh1597, I have created a pull request against your github fork to fix the tests.

**Comment by basepi** [comment]
Thanks @Akilesh1597, this is great!

**Pull request merged**
