### PR TITLE
Update versionadded and release notes

### PR DESCRIPTION
**Pull request by pass-by-value**
### What does this PR do?

Updates the versionadded and release notes for [patch](https://github.com/saltstack/salt/pull/36238) submitted yesterday
### What issues does this PR fix or reference?

Info related to version and release notes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by rallytime** [comment]
We talked about this offline, but I wanted to mention this here so that we are all on the same page: The patch referenced here went into 2016.3, so this change to go into that branch and the versionadded and release notes need to be updated accordingly.

**Comment by pass-by-value** [comment]
@rallytime: Updated, thanks!

**Comment by rallytime** [comment]
Great! Can you also change the branch this is submitted against? GH let's you do that from the web interface now. Click `Edit` near the title and you'll see the branch drop down.

**Comment by pass-by-value** [comment]
@rallytime: Updated the base to 2016.3 and rebased.

**Comment by rallytime** [comment]
Thank you!

**Pull request merged**
