### PR TITLE
Allow zabbix module to call api from any host, not just the zabbix server

### PR DESCRIPTION
**Pull request by mchugh19**
### What does this PR do?
Previously the zabbix module would only run from the zabbix server. But since it only calls the zabbix api, this restriction is not needed.

### What issues does this PR fix or reference?
#42467

### Previous Behavior
Zabbix module only ran on a host with the zabbix_server binary

### New Behavior
Zabbix module now loads from any host

### Tests written?
No

### CODE REVIEW

**Review by garethgreenaway — APPROVED** [review]

**Review by cachedout — APPROVED** [review]

**Comment by gtmanfred** [comment]
actually looks like this was broken in a mergeforward from 2017.7 to 2018.3 for salt.utils.* stuff

**Comment by gtmanfred** [comment]
https://github.com/saltstack/salt/commit/3184168365f35e2a22381a7282e65d8c76a778a6#diff-48649b036902f9e3cd75a774e29e1b91R46-R52

**Comment by thatch45** [comment]
Ok, so we don't need to backport, correct?

**Comment by gtmanfred** [comment]
We don't need a backport, but we do need the forward merge to be fixed.

**Comment by gtmanfred** [comment]
https://github.com/saltstack/salt/blob/2018.3/salt/modules/zabbix.py#L47-53

**Comment by OrangeDog** [comment]
@saltstack/team-core any update on fixing this in 2018.3.4?

**Pull request merged**
