### PR TITLE
Fixes for 2015.8

### PR DESCRIPTION
**Pull request by jacksontj**
Handle errors sending mine datas to master
Fix for #25720

### CODE REVIEW

**Comment by jacksontj** [comment]
Also including a fix for some weird race conditions in the minion init (event related)

**Comment by jacksontj** [comment]
Also including a fix for the weird binary output in the debug log from the tcp publisher

**Comment by jacksontj** [comment]
Also including a fix for #25716

**Comment by jfindlay** [comment]
Nice, thanks @jacksontj.

**Pull request merged**
