### PR TITLE
pkg.update: Fix invalid dnf command when obsoletes=True

### LINKED ISSUE #54224: Yumpkg module fails for DNF on pkg.update
### Yumpkg module fails for DNF on pkg.update

The `obsoletes` flag was added for DNF on version 2019.02. This causes a failure on running the `pkg.update` module on a system using DNF as `--obsoletes` is an invalid flag and instead requires `--setopt obsoletes=False`.

https://github.com/saltstack/salt/blob/develop/salt/modules/yumpkg.py#L1906

### Setup

No configuration needed. Run `pkg.update` module on a system using DNF.

### Steps to Reproduce Issue

No configuration needed. Run `pkg.update` module on a system using DNF.

```
[root@desktop ~]# salt-call pkg.update
[ERROR   ] Command '[u'systemd-run', u'--scope', u'dnf', u'--quiet', u'-y', u'--obsoletes=False', u'upgrade']' failed with return code: 2
[ERROR   ] stderr: Running scope as unit: run-rd1bf071763854e45bed67e78b0f34e40.scope
usage: dnf [-c [config file]] [-q] [-v] [--version] [--installroot [path]]
           [--nodocs] [--noplugins] [--enableplugin [plugin]]
           [--disableplugin [plugin]] [--releasever RELEASEVER]
           [--setopt SETOPTS] [--skip-broken] [-h] [--allowerasing]
           [-b | --nobest] [-C] [-R [minutes]] [-d [debug level]]
           [--debugsolver] [--showduplicates] [-e ERRORLEVEL] [--obsoletes]
           [--rpmverbosity [debug level name]] [-y] [--assumeno]
           [--enablerepo [repo]] [--disablerepo [repo] | --repo [repo]]
           [--enable | --disable] [-x [package]] [--disableexcludes [repo]]
           [--repofrompath [repo,path]] [--noautoremove] [--nogpgcheck]
           [--color COLOR] [--refresh] [-4] [-6] [--destdir DESTDIR]
           [--downloadonly] [--comment COMMENT] [--bugfix] [--enhancement]
           [--newpackage] [--security] [--advisory ADVISORY] [--bz BUGZILLA]
           [--cve CVES] [--sec-severity {Critical,Important,Moderate,Low}]
           [--forcearch ARCH]
dnf: error: argument --obsoletes: ignored explicit argument 'False'
[ERROR   ] retcode: 2
Error running 'pkg.update': Problem encountered upgrading packages. Additional info follows:

changes:
    ----------
result:
    ----------
    pid:
        32486
    retcode:
        2
    stderr:
        Running scope as unit: run-rd1bf071763854e45bed67e78b0f34e40.scope
        usage: dnf [-c [config file]] [-q] [-v] [--version] [--installroot [path]]
                   [--nodocs] [--noplugins] [--enableplugin [plugin]]
                   [--disableplugin [plugin]] [--releasever RELEASEVER]
                   [--setopt SETOPTS] [--skip-broken] [-h] [--allowerasing]
                   [-b | --nobest] [-C] [-R [minutes]] [-d [debug level]]
                   [--debugsolver] [--showduplicates] [-e ERRORLEVEL] [--obsoletes]
                   [--rpmverbosity [debug level name]] [-y] [--assumeno]
                   [--enablerepo [repo]] [--disablerepo [repo] | --repo [repo]]
                   [--enable | --disable] [-x [package]] [--disableexcludes [repo]]
                   [--repofrompath [repo,path]] [--noautoremove] [--nogpgcheck]
                   [--color COLOR] [--refresh] [-4] [-6] [--destdir DESTDIR]
                   [--downloadonly] [--comment COMMENT] [--bugfix] [--enhancement]
                   [--newpackage] [--security] [--advisory ADVISORY] [--bz BUGZILLA]
                   [--cve CVES] [--sec-severity {Critical,Important,Moderate,Low}]
                   [--forcearch ARCH]
        dnf: error: argument --obsoletes: ignored explicit argument 'False'
    stdout:

```

### Versions Report

```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.16 (default, Apr 30 2019, 15:54:59)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.0.2
            ZMQ: 4.1.6
 
System Versions:
           dist: fedora 29 Twenty Nine
         locale: UTF-8
        machine: x86_64
        release: 5.2.7-100.fc29.x86_64
         system: Linux
        version: Fedora 29 Twenty Nine
```

### PR DESCRIPTION
**Pull request by terminalmage**
Resolves #54224

### CODE REVIEW

**Comment by terminalmage** [comment]
re-run arch

**Review by Akm0d — DISMISSED** [review]

**Comment by alipievg** [comment]
Any plan to merge ?

**Review by s0undt3ch — DISMISSED** [review]

**Review by Ch3LL — CHANGES_REQUESTED** [review]
This just needs a changelog. I can push one if you aren't able to @terminalmage

**Comment by terminalmage** [comment]
@Ch3LL added one just now

**Review by Ch3LL — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Pull request merged**
