### PR TITLE
Added module win_wua.py for managing windows updates

### PR DESCRIPTION
**Pull request by twangboy**
New module for better control of windows updates
- Search by KB, Name, and GUID
- Search by Category, Severity, etc
- Switch to download or install results of search
- More detailed documentation

### CODE REVIEW

**Comment by rallytime** [comment]
Thanks @twangboy!

Can you clean up these pylint errors? https://jenkins.saltstack.com/job/salt-pr-lint-n/6001/violations/file/salt/modules/win_wua.py/

**Comment by twangboy** [comment]
Working on it...

On Thu, May 28, 2015 at 4:33 PM, Nicole Thomas <notifications@github.com>
wrote:

> Thanks @twangboy <https://github.com/twangboy>!
>
> Can you clean up these pylint errors?
> https://jenkins.saltstack.com/job/salt-pr-lint-n/6001/violations/file/salt/modules/win_wua.py/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt/pull/24223#issuecomment-106618793>.
>



-- 
*Shane Lee*
*Windows Platform Engineer*
Salt Stack, Inc.

Join us at SaltConf15 <http://www.saltconf.com/> - March 3-5, 2015 - Salt
Lake City

**Comment by eliasp** [comment]
I'd be interested in the technical differences between this one and the existing `salt/modules/win_update.py`. 

- Will this replace the existing one?
- Does it something fundamentally different?
- Would it probably make sense to merge this one + the existing one into a single module?

**Comment by eliasp** [comment]
Looking at the code, this looks like a refactoring of the existing code to make it more Salt-ish - is that correct? Are there any further differences?

**Comment by twangboy** [comment]
@eliasp Yes, I tried to make it more salt-ish. This one returns a dictionary object instead of stdout. Added better documentation. This one also allows you to download a single specific update by KB, Name, or GUID. The win_update allowed you to search by category but you had no way of selecting a specific update to download. The plan is to eventually make this stateful as well. We didn't want to change win_update in case people were using it, so we'll encourage use of the new one and eventually phase the old one out. There were also a lot of references to Quidditch in win_update.py that we wanted to get rid of, so...

**Comment by eliasp** [comment]
@twangboy Thanks a lot for the efforts and your detailed response! Will give it a try soon!

**Pull request merged**
