### PR TITLE
Replace deprecated inspect.formatargspec

### LINKED ISSUE #50911: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
### Description of Issue/Question
Getting the below warning messages on salt 2018.3.3 with python3.7.1. Due to these warning messages the automation not behaving properly which uses salt.

```
/usr/local/python371/lib/python3.7/site-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  *salt.utils.args.get_function_argspec(original_function)
```

### Steps to Reproduce Issue
Compiled python 3.7.1 on centos 6 and installed salt using pip. When I try to apply any states, started seeing the above warning message on the minion log file. 

### Versions Report
```
# salt --versions-report
Salt Version:
Salt: 2018.3.3

Dependency Versions:
cffi: Not Installed
cherrypy: Not Installed
dateutil: 2.7.5
docker-py: Not Installed
gitdb: Not Installed
gitpython: Not Installed
ioflo: Not Installed
Jinja2: 2.10
libgit2: Not Installed
libnacl: Not Installed
M2Crypto: Not Installed
Mako: Not Installed
msgpack-pure: Not Installed
msgpack-python: 0.5.6
mysql-python: Not Installed
pycparser: Not Installed
pycrypto: 2.6.1
pycryptodome: Not Installed
pygit2: Not Installed
Python: 3.7.1 (default, Nov 23 2018, 02:59:05)
python-gnupg: Not Installed
PyYAML: 3.13
PyZMQ: 17.1.2
RAET: Not Installed
smmap: Not Installed
timelib: Not Installed
Tornado: 4.5.3
ZMQ: 4.2.5

System Versions:
dist: redhat 6.9 Santiago
locale: UTF-8
machine: x86_64
release: 2.6.39-400.296.2.el6.x86_64
system: Linux
version: Red Hat Enterprise Linux Server 6.9 Santiago
```

### PR DESCRIPTION
**Pull request by bdrung**
Python 3.7 raises a deprecation warning:

salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly

`inspect.formatargspec` is only used in `salt.utils.decorators.signature.identical_signature_wrapper` which is only used in `salt.utils.decorators.path` for decorating the `which` and `which_bin` functions. The function `identical_signature_wrapper` can be simply replaced by Python's `functools.wraps` which is available since at least Python 2.7.

When inspecting those wrapped functions, the underlying function (stored in the `__wrapped__` attribute) needs to be inspect instead.

fixes #50911

### CODE REVIEW

**Comment by achamoux** [comment]
I'm a certified newbie as far as OVM is concerned, and I face a similar problem when installing OVM5 onto my Rpi 4 4G. The save process often provokes the following exception : 
"Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run mdadm 2>&1' with exit code '1': /usr/lib/python3/dist-packages/salt/utils/path.py:265: **DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working** if not isinstance(exes, collections.Iterable): raspberrypi: ---------- etc.etc.
See also https://forum.openmediavault.org/index.php/Thread/30843-Failed-to-execute-command-export-PATH-bin-sbin-usr-collections-instead-of-from-c/?postID=228371#post228371

Is there a possible relationship with the two problems ?

**Comment by sferia82** [comment]
> Soy un novato certificado en lo que respecta a OVM, y enfrento un problema similar al instalar OVM5 en mi Rpi 4 4G. El proceso de guardado a menudo provoca la siguiente excepción:
> "Error al ejecutar el comando 'export PATH = / bin: / sbin: / usr / bin: / usr / sbin: / usr / local / bin: / usr / local / sbin; export LANG = C.UTF-8; despliegue omv-salt ejecute mdadm 2> & 1 'con el código de salida' 1 ': /usr/lib/python3/dist-packages/salt/utils/path.py:265: **DeprecationWarning: Uso o importación el ABC de 'collections' en lugar de 'collections.abc' está en desuso, y en 3.8 dejará de funcionar** si no es instancia (exes, collections.Iterable): raspberrypi: ---------- etc.etc .
> Véase también[https://forum.openmediavault.org/index.php/Thread/30843-Failed-to-execute-command-export-PATH-bin-sbin-usr-collections-instead-of-from-c/?postID=228371 # post228371](https://forum.openmediavault.org/index.php/Thread/30843-Failed-to-execute-command-export-PATH-bin-sbin-usr-collections-instead-of-from-c/?postID=228371#post228371)
> 
> ¿Existe una posible relación con los dos problemas?

any solution? It also gave me that error in the installation and it is coming out while I am using the web portal.

**Review by s0undt3ch — DISMISSED** [review]

**Review by s0undt3ch — DISMISSED** [review]

**Comment by bdrung** [comment]
It took me several hours to troubleshoot why `integration.modules.test_archive.ArchiveTest.test_gzip` and other tests failed: When replacing `identical_signature_wrapper` by `functools.wraps` it will change the signature. When inspecting the wrapped function, inspect the underlying function instead.

**Comment by Akm0d** [comment]
@bdrung Thank you for the contribution!  We appreciate the time you put into resolving this issue.  Before merging there needs to be a test written for the changes.

**Comment by s0undt3ch** [comment]
Updated PR to latest master. Current changes just switch our own implementation of `wraps` with the stdlib one, as such, I feel like this does not warrant a test case, and if so, how and what is advisable.
Also, this **needs** to go in before the code freeze.

Once fast tests finish, I will trigger a slow test run.

**Review by twangboy — APPROVED** [review]

**Pull request merged**
