### PR TITLE
Fix issue with duplicates in user.list_users on OSX

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?
Fixes the issue where `user.list_users` was showing duplicate users names. Uses a set to do this as a set does not allow duplicates.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/48608

### Tests written?
No

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by cachedout** [comment]
This does not strike me as the right fix. IMHO, we need to figure out why the duplication is happening to begin with.

**Comment by DmitryKuzmenko** [comment]
At least it's interesting why
```
>>> for p in pwd.getpwall():
...     print p[0]
```
gets a list of non-dups, but `[user.pw_name for user in pwd.getpwall()]` returns duplications. o_O

**Comment by twangboy** [comment]
@DmitryKuzmenko There are still dups. The list is not sorted, so it's hard to tell

**Comment by twangboy** [comment]
@cachedout I think the issue is with the `pwd.getpwall` command on osx. I don't get dupes on linux boxes. Is there a problem with filtering them out?

**Comment by twangboy** [comment]
@cachedout @DmitryKuzmenko Changed it to use dscl

**Review by terminalmage — APPROVED** [review]
I usually see this as `/Users` and not `/users`. If dscl can use case-insensitive names, then I think this is fine.

**Comment by twangboy** [comment]
@terminalmage Works fine with `/users` or `/Users`. Seems to be NOT case sensitive.

**Comment by cachedout** [comment]
@twangboy We have a failed test here I'm afraid.

**Pull request merged**
