### PR TITLE
Altering validation of windows directory ownership to compare SID instead of username

### LINKED ISSUE #50880: Windows file.directory fails to determine owner correctly
### Description of Issue/Question

**file.directory** state incorrectly checks owner on Windows and forces change every time.   The state determines the current user is **LOCALDEV\vagrant** while the file owner is **vagrant**.

Just for reference, I was able to alter [_check_directory_win](https://github.com/saltstack/salt/blob/develop/salt/states/file.py#L773) in order to compare the SID instead of name. This fixes the issue for my case. 

```
        # Check owner
        if win_owner is not None:
            expected_owner_sid = salt.utils.win_dacl.get_sid_string(
                    salt.utils.win_dacl.get_sid(win_owner))
            current_owner_sid = salt.utils.win_dacl.get_sid_string(
                    salt.utils.win_dacl.get_sid(salt.utils.win_dacl.get_owner(name)))
            if not expected_owner_sid == current_owner_sid:
                changes['owner'] = win_owner
```

### Setup

Very minimal SaltState for **file.directory**.

```
Testing:
  file.directory:
    - name: 'C:\testing'
    - makedirs: True
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

First Run:
```
      ID: Testing
Function: file.directory
    Name: C:\testing
  Result: True
 Comment: Directory c:\testing updated
 Started: 23:48:23.842000
Duration: 47.0 ms
 Changes:   
          ----------
          c:\testing:
              New Dir

```

Second Run:
```
      ID: Testing
Function: file.directory
    Name: C:\testing
  Result: True
 Comment: Directory c:\testing is in the correct state
 Started: 23:58:43.818000
Duration: 0.0 ms
 Changes:   
          ----------
          owner:
              LOCALDEV\vagrant
```

### Versions Report
Provisioning Windows 2008 server through Vagrant.

```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:   
         locale: cp1252
        machine: AMD64
        release: 2008ServerR2
         system: Windows
        version: 2008ServerR2 6.1.7601 SP1 Multiprocessor Free
```

### PR DESCRIPTION
**Pull request by jalandis**
### What does this PR do?

Alters logic checking Windows directory ownership to avoid unnecessary updates.

### What issues does this PR fix or reference?

Fixes #50880

### Previous Behavior

Windows folder ownership was tested by username with **username** and **domain\username** not matching properly.

### New Behavior

Windows folder ownership is tested by more uniform SID.

### Tests written?

Yes

### Commits signed with GPG?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by jalandis** [comment]
In order to facilitate getting this pull request merged in, I am going to work on adding an integration test `tests/integration/states/test_file.py`.

If there are any other changes that you would like to recommend, please let me know.

**Comment by zbarr** [comment]
What is the status on this? I have just upgraded all of my minions to 2018.3.3 and am seeing this issue consistently. I would like to patch it if I could see the code change.

**Review by twangboy — APPROVED** [review]

**Comment by twangboy** [comment]
I'd like to see this on the older branches as well... 2018.3 and forward...

**Comment by zbarr** [comment]
I made a bad patch in my environment so I am now aware it is not particularly easy to backport to 2018.3.3. I am personally just interested in seeing this in the 2018.3.4 release now and we are just going to deal with the bug until then. I will continue to watch for a merge. Thank you to whoever has contributed.

**Pull request merged**
