### PR TITLE
Handle unicode custom grains on Windows

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?
Handles the creation of custom grains with Unicode Characters properly in Windows. The grains config file needs to be encoded UTF-8 in order to write and read the grains properly. If you don't specify the encoding with fopen, then it will use the system encoding which is usually cp437. This issue may pop up elsewhere in salt as we move to Python 3.7+

### What issues does this PR fix or reference?
This will need to go in after the following:
https://github.com/saltstack/salt/pull/56077

### Previous Behavior
Unable to decode a custom grain with unicode characters if the file encoding isn't UTF-8

### New Behavior
Custom grains are written using UTF-8 and is decoded properly as a result

### Tests written?
No

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by waynew** [comment]
Are you planning to write tests for this?

**Comment by max-arnold** [comment]
Does that fix https://github.com/saltstack/salt/issues/53340 ?

**Comment by twangboy** [comment]
@max-arnold The transition to Python37 should take care of https://github.com/saltstack/salt/issues/53340. This handles an issue when creating custom grains.

@waynew I do intend to write some tests for this... they're gonna be awesome.

**Comment by max-arnold** [comment]
>  The transition to Python37 should take care of #53340

Transition from Python27 or from Python35? This issue happened on 3.5.3 and I don’t understand what is going to change on 3.7.

**Review by waynew — CHANGES_REQUESTED** [review]
Needs tests :joy:

**Pull request closed without merging**
