### PR TITLE
[develop] Merge forward from 2017.7 to develop

### PR DESCRIPTION
**Pull request by rallytime**
No conflicts.

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
haproxyconn unit tests should be fixed in #42101

**Comment by rallytime** [comment]
kernelpkg tests should be fixed in #42102

**Comment by rallytime** [comment]
saltmod unit test is fixed in #42138

**Review by cachedout — APPROVED** [review]

**Pull request merged**
