### PR TITLE
Fix #59161

### LINKED ISSUE #59161: 3002.6 regression salt minion broken in CentOS Stream
### Description of Issue
When I run a previously working sls file on a system that was CentOS 8 which I upgraded to CentOS Stream, I get error messages. I made a simple vim install sls for a test. The error is (yes, the minion name is CentSO8):

CentSO8:
----------
          ID: vim
    Function: pkg.installed
        Name: vim-enhanced
      Result: False
     Comment: State 'pkg.installed' was not found in SLS 'vim_test'
              Reason: 'pkg' __virtual__ returned False: pkg module could not be loaded
     Changes: 

### Setup
sls file contains:

vim:
  pkg:
    - installed
{% if 'CentOS' in grains['os'] %}
    - name: vim-enhanced
{% else %}
    - name: vim
{% endif %}

### Steps to Reproduce Issue
Created test sls file named vim_test and then ran

salt <minion_name> state.sls vim_test

### Versions Report
CentSO8:
    Salt Version:
              Salt: 3002.2
     
    Dependency Versions:
              cffi: 1.11.5
          cherrypy: Not Installed
          dateutil: 2.6.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 2.10.1
           libgit2: Not Installed
          M2Crypto: 0.35.2
              Mako: Not Installed
           msgpack: 0.6.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.14
          pycrypto: Not Installed
      pycryptodome: Not Installed
            pygit2: Not Installed
            Python: 3.6.8 (default, Dec  3 2020, 18:11:24)
      python-gnupg: Not Installed
            PyYAML: 3.12
             PyZMQ: 19.0.0
             smmap: Not Installed
           timelib: Not Installed
           Tornado: 4.5.3
               ZMQ: 4.3.3
     
    System Versions:
              dist: centos 8 
            locale: UTF-8
           machine: x86_64
           release: 4.18.0-257.el8.x86_64
            system: Linux
           version: CentOS Stream 8

### PR DESCRIPTION
**Pull request by avkvl**
### What does this PR do?
add "CentOS Stream" to _OS_FAMILY_MAP

### What issues does this PR fix or reference?
Fixes: #59161

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by krionbsd — APPROVED** [review]

**Comment by krionbsd** [comment]
@avkvl PR 59201 should fix this issue

**Comment by avkvl** [comment]
> @avkvl PR 59201 should fix this issue

Yes, PR 59201 will fix package installation, but will not set grain os_family to RedHat.

**Comment by krionbsd** [comment]
> > @avkvl PR 59201 should fix this issue
> 
> Yes, PR 59201 will fix package installation, but will not set grain os_family to RedHat.

yes, sorry I missed this part

**Comment by ScriptAutomate** [comment]
Potentially related: https://github.com/saltstack/salt/issues/59061

**Pull request merged**
