### PR TITLE
Multi Headed Master

### PR DESCRIPTION
**Pull request by thatch45**
This allows for the ZeroMQ master to be run alongside a RAET master, so that the master can seamlessly handle zmq and RAET minions.

This is only partially done, it still needs some salt-key additions (which will also be needed for the master cluster we are working on) and needs to be updated with some of @jacksontj 's recent PRs, primarily the key sharing one for the workers.

BTW, the multiheaded master uses fewer processes then the zmq master, because RAET and ioflo are AWESOME!!!!

### CODE REVIEW

**Comment by thatch45** [comment]
@jacksontj
Take a look, this is virtually all that needs to be done now for a transport to be added, we could get a tornado transport in easily. I want to make an ssh one :)

**Comment by jacksontj** [comment]
Tornado is an async framework not a transport ;) but there are still
questions on how this runs. It seems that all it does is run the other
daemons in separate processes which seems fairly heavy handed given the
only thing different is transport. I'm working on factoring the transport
into a separate class so we won't have to duplicate so much code.

Also in this setup we haven't done anything about parallelizing requests on
the master when something would block, it just runs the daemon of today.

**Comment by thatch45** [comment]
This is because of how zmq works, I tried to run the zmq device in the main process but it blocks. Also, what do you see as blocking? this is set up to use the existing worker processes and we only spin up one more process to handle the zmq routing device.
What do you propose that would be better? The transports work so differently that they cannot be reasonably normalized into a single class on the master.

**Comment by jacksontj** [comment]
They can be abstracted out into an interface that we can use. IMO we need to pull transport out so that we can separate "getting" the job and "executing" the job. I have it started on a fork of mine, I should have the master side of it done in the next week or so. Once we separate those then we can start to async-up the core and it will benefit *all* transport types-- instead of having to maintain almost separate code bases.

**Comment by thatch45** [comment]
I don't follow, because the transports are so different, but I assume you have a good track in place, so I will wait for what you have. Again, I agree that we should localize more of the code, but it is something that we need to be very careful with, so I will await to see your solution.

**Comment by thatch45** [comment]
More precisely though, my plan is to move all of the transport components into as normalized a situation as possible under ioflo

**Comment by jacksontj** [comment]
My work is in my transport branch (https://github.com/jacksontj/salt/tree/transport) I haven't yet committed my master side stuff yet, but I think it'll be easier to explain the direction I'm going once its done. After seeing this PR it seems that the refactor I'm doing will help both the normal daemons and your migration to ioflo

**Comment by thatch45** [comment]
Your work over there looks great, I wish I had more time to work on all of this nowdays, I am looking forward to getting all of this merged in.
Moving forward I would like to consider moveing towards defaulting to a multi head master so that migrating is easier

**Comment by jacksontj** [comment]
Yea, thats why i wanted to get all this stuff in :) Once I'm done I think
we can change the config on the master from "transport" to "transports" and
just default to both (similar for minions). To successfully transition to
anything from zmq we are going to have to interoperate for quite some time
;)

**Comment by thatch45** [comment]
Sounds like a plan! Do you think then that we will need multi headed minions as well? Or am I miss interpreting that one?

**Comment by jacksontj** [comment]
Well, the people running multi minion will want that :) I don't think it'll
be hard though

**Comment by jacksontj** [comment]
@thatch45 I just updated my transport branch with the work from today (thats all for today, don't want to spend the *entire* holiday on it). Its a little rough around the edges still, but hopefully you can get the idea. Basically with these Req and Pub channels we can push all of the auth/crypto/transport into these classes that are responsible for it. We could then consolidate "auth" into a class to be used by transports that don't do that themselves and we could do the same with crypto. 

Ideally these transport classes would have a few more APIs to let you use them in IOLoops, then it would be really simple to add one in (such as tornado's IOLoop).

**Pull request merged**
