### PR TITLE
Issue 21167

### PR DESCRIPTION
**Pull request by freimer**
Windows deploy now works for AWS again.

### CODE REVIEW

**Comment by techhat** [comment]
This is good stuff, @freimer. If the tests pass, it looks good to me.

**Comment by freimer** [comment]
Thanks @techhat.  It works, but there still needs to be a test when stopping and starting the minion.  Although the minion gets installed, it is not left in a running state and I have to RDP to the instance and start it manually (or through winexe on the command line on the Linux master).  It may be because it is in the "stopping" state when the sc start salt-minion command is run.  I'm trying to create a small for loop to catch for that.  I could put that in a separate pull request, which is likely what I will do.

**Comment by freimer** [comment]
@techhat - yes, there needs to be a delay.  I added a 5 second wait.  wincmd doesn't support retrieving the text output of commands, and sc query returns true regardless of whether the services is running or not, and it doesn't look like wincmd supports pipelines either.  So, there's more work to get this working "properly" but a 5 second delay appears to work for me.

**Comment by techhat** [comment]
Thanks @freimer. I have a chunk of winexe replacement code sitting locally on my machine. It's not done, and I won't be able to get to it for at least a week, but if you want to hack on it, you're more than welcome to contact me for a copy.

**Comment by freimer** [comment]
Sure, don't know how to contact you though ;-)

**Comment by rallytime** [comment]
@techhat Some of the work in this PR or at least some of the comments here might be relevant to #15984.

**Comment by rallytime** [comment]
ping @UtahDave

**Pull request merged**
