### PR TITLE
Fix webutil.user_exists grep error on first run

### LINKED ISSUE #53977: webutil.user_exists logs grep error on first run
### Description of Issue
The first time this state is executed an error level output is logged on the minion. I believe this is because an attempt is made to grep the file without first checking that the file exists.

### Setup
```
htpasswd_file:
  webutil.user_exists:  # Im really not sure why this is under webutil, not htpasswd as per the docs.
    - name: <user>
    - password: <password>
    - htpasswd_file: /etc/nginx/.htpasswd
    - force: true
    - require:
      - pkg: apache2-utils
```

### Steps to Reproduce Issue
```
[ERROR   ] Command '['grep', '<user>', '/etc/nginx/.htpasswd']' failed with return code: 2
[ERROR   ] stderr: grep: /etc/nginx/.htpasswd: No such file or directory
[ERROR   ] retcode: 2
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.3.10
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-47-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

### PR DESCRIPTION
**Pull request by alexjsmac**
Fixes #53977

### What does this PR do?

Checks for the existence of /etc/nginx/.htpasswd before grepping it to avoid error messages in the minion log.

### What issues does this PR fix or reference?

#53977

### CODE REVIEW

**Comment by amaclean199** [comment]
Oh hmm I'm getting a key error on my change:
```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/states/test_webutil.py", line 80, in test_new_user_error
    '/etc/httpd/htpasswd')
  File "/tmp/kitchen/testing/salt/states/webutil.py", line 69, in user_exists
    if __salt__['file.file_exists'](htpasswd_file):
KeyError: u'file.file_exists'
```
I'm really not sure why `__salt__['file.grep']` would be available but `__salt__['file.file_exists']` would not be though.

**Comment by waynew** [comment]
Hey @amaclean199 thanks for the PR!

Are you seeing this problem when running the test(s) locally? You probably should be - `file.grep` is being mocked out in those tests, but `file.exists` is not 🙃 

If you're using fish shell you can use this function - otherwise you can create an alias with the same command:

```
# Defined in /Users/wwerner/.config/fish/functions/saltt.fish @ line 1
function saltt
	docker run --rm -it -v "$PWD/salt":/usr/lib/python2.7/dist-packages/salt -v "$PWD/salt":/usr/local/lib64/python3.6/site-packages/salt -v "$PWD":/testing $argv
end
```
Then all you have to do to run the tests is run this:

    saltt waynew/salt-sprints python3 /testing/tests/runtests.py -n unit.states.test_webutil;

assuming you have docker installed. If you're not on mac, you'll probably need to add a `sudo` in front of that `docker`, of course. HTH

**Review by waynew — CHANGES_REQUESTED** [review]
Could we also get a test to ensure that if the file does not exist, it returns that the user does not exist (as opposed to erroring out)?

It should be pretty straight forward - you could use the `@with_tempdir` to get a clean directory, and just do something like assert that `os.path.join(tempdir, '.htpasswd')` does not exist, then run this `user_exists` and assert that the result is what we expect.

**Review by waynew — DISMISSED** [review]

**Review by twangboy — DISMISSED** [review]

**Comment by amaclean199** [comment]
I don't believe those remaining build failures are caused by my changes but if so please let me know.

**Comment by waynew** [comment]
re-run full all

**Comment by dwoz** [comment]
re-run full all

**Review by xeacott — DISMISSED** [review]

**Comment by amaclean199** [comment]
@waynew @dwoz apologies but I am unsure what to do with that command. Is that related to running the tests locally or re-running the ci tests?

**Comment by waynew** [comment]
@amaclean199 it triggers a CI re-run.

**Comment by amaclean199** [comment]
re-run full all

**Comment by waynew** [comment]
@amaclean199 Hey, we've recently changed our branching/release strategy, could you go ahead and rebase this PR on `master`? That would be awesome!

**Comment by dwoz** [comment]
This needs to go to the `master` branch.

**Review by waynew — CHANGES_REQUESTED** [review]
Hey @amaclean199 looks like we're *almost* there - we've adopted black code formatting for Salt. The *easiest* way to get this to run is to follow the [quickstart guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html#quickstart) and install pre-commit.

When you use pre-commit it will automatically format your code and run lint before each commit. You don't *have* to use it, but it makes life much easier, in exchange for waiting a moment before writing your commit message :grin:

**Comment by amaclean199** [comment]
Thanks @dwoz I was having trouble getting the pre-commit to work

**Comment by waynew** [comment]
@amaclean199 Looks like this has some merge conflicts - can you take a look at those and either rebase or merge in master?

**Comment by waynew** [comment]
@amaclean199 Just in case you hadn't seen the above :point_up:  - looks like this still has some merge conflicts

**Comment by waynew** [comment]
@amaclean199 Just another follow up. Are you interested in completing this, or should we put it in the help wanted queue?

**Review by twangboy — APPROVED** [review]

**Review by waynew — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Pull request merged**
