### PR TITLE
Revert "Added bypass features to pkg.installed"

### PR DESCRIPTION
**Pull request by justindesilets**
Reverts saltstack/salt#50922. It was determined that this was a duplicate function of another feature and less native to the salt method. I would like to revert it and will close out my current PR that has fixes in place for it here https://github.com/saltstack/salt/pull/53320. Additionally, I will open up a new PR in the next week to update the pkg.installed documentation to include how to use the unless feature with the aggregate feature.

### CODE REVIEW

**Review by Ch3LL — APPROVED** [review]

**Comment by Ch3LL** [comment]
I checked that this is not currently in a release so it should be fine to revert. Since this is in develop we will need to backport to neon before we release there to ensure the feature is not released.

**Comment by sagetherage** [comment]
@justindesilets this needs to be rebased against the master branch - or is there a different PR?

**Comment by justindesilets** [comment]
@sagetherage this was just to revert a feature that had been merged in but was then later determined should be left out. Do I still actually need to debase this or can it just be merged in?

**Comment by sagetherage** [comment]
@justindesilets good question - we are no longer accepting PRs against the `develop` branch, so if you want the change it needs to point to the active branch for changes = `master`

**Comment by justindesilets** [comment]
@sagetherage I'm looking at the current master branch for the state/pkg.py and I don't see the bypass code in there. It looks like it was never merged in the transition from develop to master. I believe this PR can be closed at this point as there isn't a change to revert.

**Pull request closed without merging**
