### PR TITLE
Slack webhook returner

### PR DESCRIPTION
**Pull request by cdalvaro**
### What does this PR do?

Merge slack_webhook returner from develop branch.

50071631-bbfa1700-01d2-11e9-87a8-b13f612bbff2

### What issues does this PR fix or reference?

More information is available in PR #50879

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by Akm0d** [comment]
re-run full proxy

**Comment by Akm0d** [comment]
re-run full m2crypto

**Comment by Akm0d** [comment]
re-run full m2crypto

**Comment by Akm0d** [comment]
re-run full amazon2

**Review by Akm0d — APPROVED** [review]

**Comment by max-arnold** [comment]
@cdalvaro The returner crashes for simple functions like `test.ping`:

`sudo salt minion1 test.ping --return slack_webhook`

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 1805, in _thread_return
    minion_instance.returners[returner_str](ret)
  File "/usr/lib/python3/dist-packages/salt/returners/slack_webhook_return.py", line 330, in returner
    report = _generate_report(ret, show_tasks)
  File "/usr/lib/python3/dist-packages/salt/returners/slack_webhook_return.py", line 220, in _generate_report
    returns.items(),
AttributeError: 'bool' object has no attribute 'items'
```

The reason is that the `ret` dictionary looks like this:

```
{'success': True, 'return': True, 'retcode': 0, 'jid': '20200112092012145203', 'fun': 'test.ping', 'fun_args': [], 'id': 'minion1'}
```
and the returner tries to iterate over `True.items()`.   The `return` key can contain arbitrary values and data structures.

**Comment by max-arnold** [comment]
Also, it is not mentioned in the docs: https://docs.saltstack.com/en/master/ref/returners/all/index.html

**Comment by cdalvaro** [comment]
Thank you for the reporting @max-arnold, I will fix it asap! 🛠

Have you detected more issues related with this returner??

**Comment by max-arnold** [comment]
@cdalvaro I haven't used it heavily yet, so those two problems is all I was able to find. 

Overall, the resulting Slack message looks much nicer than raw json dump from the old `slack` returner.

**Pull request merged**
