### PR TITLE
Work around upstream pygit2 bug

### LINKED ISSUE #28072: pygit 0.23.2 is not supported in Salt 2015.8.1
I just rolled a fresh Salt master running 2015.8.1, freshly installed libgit2 from source and hit this issue:
```
[ERROR   ] Exception 'authentication required but no callback set' caught while fetching git_pillar remote 'production git@gitlab.com:...'
[ERROR   ] Exception 'authentication required but no callback set' caught while fetching gitfs remote 'git@gitlab.com:...
```

Rolling back to pygit/libgit 0.22.x solved my issue, but I didn't see an open issue regarding this problem, so I figured it'd be good to at least have an issue open about it. I don't have time to produce a fix right now - sorry! For anyone curious, I believe the problem ties to this pull request: https://github.com/libgit2/pygit2/pull/568

### PR DESCRIPTION
**Pull request by terminalmage**
See https://github.com/saltstack/salt/issues/28072 and https://github.com/libgit2/pygit2/issues/583.

Fixes #28072.

### CODE REVIEW

**Comment by cachedout** [comment]
@terminalmage The linter seems unhappy. Could you please take a look?

**Comment by cachedout** [comment]
@terminalmage This no longer merges cleanly. Could you take a peek please?

**Comment by terminalmage** [comment]
Looking, probably no longer merges cleanly because of the other PR that was just merged.

**Comment by terminalmage** [comment]
Rebased.

**Pull request merged**
