### PR TITLE
Fix csvpillar.py read file as binary

### PR DESCRIPTION
**Pull request by que5o**
### What does this PR do?
Resolves an error in csvpillar.py (at least when run in Python 3) where it attempted to read csv files from disk in binary format.

### What issues does this PR fix or reference?
saltstack/salt#52538

### Previous Behavior
csvpillar.py attempted to read csv files in binary format

### New Behavior
csvpillar.py now reads csv files in text format

### Tests written?

Yes

### Commits signed with GPG?

No

### CODE REVIEW

**Review by waynew — CHANGES_REQUESTED** [review]
Looks mostly great - a couple of lint issues from your tests file:

https://jenkinsci.saltstack.com/job/pr-lint/job/PR-52747/1/warnings52Result/new/

**Comment by que5o** [comment]
> 
> 
> Looks mostly great - a couple of lint issues from your tests file:
> 
> https://jenkinsci.saltstack.com/job/pr-lint/job/PR-52747/1/warnings52Result/new/

New commit pushed addressing linting

**Review by waynew — APPROVED** [review]

**Comment by que5o** [comment]
When does this show up merged into the 2019.2 and develop branch?

**Comment by waynew** [comment]
We're working on some better documentation on our merge forward process, but this should get picked up in the next merge forward from `2018.3`.

**Pull request merged**
