### PR TITLE
Fix memory leaks in master's maintenance process

### LINKED ISSUE #58785: [BUG] extreme memory leak in Maintenance process.
**Description**
salt 3002 just installed last night. woke up this morning to find all memory and most of the swap taken up. checked `ps aux | grep salt` before restarting service to get memory back. found that the maintenance processes was the only large memory hog. 

**Setup**
install 3002 and wait.

**Steps to Reproduce the behavior**
install 3002 and have minions. 

**Expected behavior**
I have memory on my system after only a day of having a newly updated system.

**Screenshots**
mem leak

the little uptick at 18:00 is when I installed 3002. 

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:                                                                    
           Salt: 3002                                                            
                                                                                 
Dependency Versions:                                                             
           cffi: 1.14.0                                                          
       cherrypy: unknown                                                         
       dateutil: Not Installed                                                   
      docker-py: Not Installed                                                   
          gitdb: Not Installed                                                   
      gitpython: Not Installed                                                   
         Jinja2: 2.11.1                                                          
        libgit2: 0.26.6                                                          
       M2Crypto: 0.35.2                                                          
           Mako: Not Installed                                                   
   msgpack-pure: Not Installed                                                   
 msgpack-python: 1.0.0                                                           
   mysql-python: Not Installed                                                   
      pycparser: 2.20                                                            
       pycrypto: Not Installed                                                   
   pycryptodome: 3.9.8                                                           
         pygit2: 0.26.4                                                          
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)                          
   python-gnupg: 2.3.1                                                           
         PyYAML: 3.13                                                            
          PyZMQ: 17.0.0                                                          
          smmap: Not Installed                                                   
        timelib: Not Installed                                                   
        Tornado: 4.5.3                                                           
            ZMQ: 4.1.4                                                           
                                                                                 
System Versions:                                                                 
           dist: centos 7 Core                                                   
         locale: UTF-8                                                           
        machine: x86_64                                                          
        release: 3.10.0-1127.13.1.el7.x86_64                                     
         system: Linux                                                           
        version: CentOS Linux 7 Core                                             
```
</details>

**Additional context**

### PR DESCRIPTION
**Pull request by dwoz**
### What does this PR do?

Fix memory leaks in Master's Maintenance process 

### What issues does this PR fix or reference?

<strike>Fixes: #58785 #58791 #58813</strike>

We will be partially reverting the loader changes from 3002 in #58862

This PR is still valid to fix a minor memory leak that happened in the salt master's maintenance process prior to the 3002 release.

### Previous Behavior

The methods to clean expired jobs and clean old tokens both created multiple loader instances every time they ran.

### New Behavior

Create an object that uses a single instance of the objects which create multiple loaders so that loaders are re-used.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ x] Tests written/updated

### CODE REVIEW

**Review by garethgreenaway — DISMISSED** [review]

**Review by s0undt3ch — DISMISSED** [review]

**Comment by ixs** [comment]
Just so that it's clearly spelled out here as well:

I've been running this on a local build and the memory consumption of the maintenance worker seems mostly stable.

But this is _not_ a fix for #58791, which is happening due to MWorkers having massive memory consumption and being killed by the oom worker.

**Comment by ixs** [comment]
@sagetherage I really hate being the bearer of bad news, but #58791 is *not* fixed by this issue. I am running a local build with this fix and it does _not_ solve the specific problem.

**Comment by OrlandoArcapix** [comment]
+1 for this patch - we noticed that our salt-master (3002.1) was growing at about 1MByte per minute, even with all the minions and api clients turned off. After applying this patch, it's sat completely stable.

**Comment by OrlandoArcapix** [comment]
> +1 for this patch - we noticed that our salt-master (3002.1) was growing at about 1MByte per minute, even with all the minions and api clients turned off. After applying this patch, it's sat completely stable.

Only required on salt < 3002.2 - after testing this patch in situ, I then updated to salt 3002.2 and that has also resolved this leak (along with a leak on a salt-proxy). Hurrah!

Would suggest that this PR is closed.

**Comment by TheBirdsNest** [comment]
Sadly this is still an issue for salt-proxy by the looks of it. Running 3003.2 and my proxies are using 8GB ram and climbing...

**Pull request closed without merging**
