### PR TITLE
Move 4 functions from salt.utils

### PR DESCRIPTION
**Pull request by terminalmage**
- salt.utils.reinit_crypto -> salt.utils.crypt.reinit_crypto
- salt.utils.appendproctitle -> salt.utils.process.appendproctitle
- salt.utils.daemonize -> salt.utils.process.daemonize
- salt.utils.daemonize_if -> salt.utils.process.daemonize_if

### CODE REVIEW

**Comment by cachedout** [comment]
@terminalmage We hit some lint issues here I'm afraid.

**Comment by terminalmage** [comment]
OK, lint is fixed locally, I'm going to wait for https://github.com/saltstack/salt/pull/43982 to be merged and then rebase against develop before pushing, though.

**Comment by terminalmage** [comment]
Some legit failures I need to fix here.

**Comment by terminalmage** [comment]
Tests fixed.

**Comment by terminalmage** [comment]
All test failures are due to the changes in the boto deps.

**Review by rallytime — APPROVED** [review]

**Pull request merged**
