### PR TITLE
Port #51814 to master

### PR DESCRIPTION
**Pull request by alexey-zhukovin**
### What does this PR do?
Master port #51814

### CODE REVIEW

**Comment by bryceml** [comment]
re-run all full

**Comment by myii** [comment]
Thanks for porting this @alexey-zhukovin.  Unfortunately, as @max-arnold has pointed out in https://github.com/saltstack/salt/issues/41195#issuecomment-577159561, there is a least one situation where `tplroot` won't evaluate in a useful manner:

> One potential workaround is to introduce the `tplroot` variable (see #51814, however if you place a formula into a deeply nested dir (e.g., `blah/blah/blah/blah/template-formula`), the `tplroot` variable will be just `blah` and all the import paths inside the formula will be broken.

From a purely formulas' perspective, the workaround being considered is to work back through the directory tree from `tpldir` to find `map.jinja` and use that directory as the `tplroot`.  That's not going to cut it here, though.  I'd love to hear any further suggestions because `tpldir` is too unwieldy, as mentioned in the original PR.

**Comment by waynew** [comment]
@myii Thanks for checking this!

---

Tests *should* be passing now - apparently you can `'foo'.join(Path(...), Path(...))` on newer Python but not on our Ubuntu 16.04 :upside_down_face: :tada:

**Comment by waynew** [comment]
re-run archlts

**Review by twangboy — DISMISSED** [review]

**Comment by waynew** [comment]
re-run centos7-py3-pycryptodome

**Comment by myii** [comment]
@waynew I was just commenting in Slack about how `tplroot` in now available in Salt, so we could start using it directly -- then I remembered that this PR might have not been merged -- which it isn't!  Is there anything else to be done to get this in?

**Comment by Ch3LL** [comment]
I resolved the merge conflict and added the 3006 label so we do not loose track of this fix.

**Comment by twangboy** [comment]
Failing tests:
```
    def file_client(self):
        """
        Return a file client. Instantiates on first call.
        """
        # If there was no file_client passed to the class, create a cache_client
        # and use that. This avoids opening a new file_client every time this
        # class is instantiated
        if (
            self._file_client is None
            or not hasattr(self._file_client, "opts")
            or self._file_client.opts["file_roots"] != self.opts["file_roots"]
        ):
            attr = "_cached_pillar_client" if self.pillar_rend else "_cached_client"
            cached_client = getattr(self, attr, None)
            if (
                cached_client is None
                or not hasattr(cached_client, "opts")
>               or cached_client.opts["file_roots"] != self.opts["file_roots"]
            ):
E           KeyError: 'file_roots'
```

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
