### PR TITLE
Fix parameter handling for boto_rds with boto3

### PR DESCRIPTION
**Pull request by blarghmatey**
### What does this PR do?
Fixes improper handling of parameters in call to create and modify RDS instances using the boto3 library.

### What issues does this PR fix or reference?
#37528

### Previous Behavior
When optional parameters were not defined the call would fail due to passing `None` to parameters that were expecting values of a different type.

### New Behavior
Optional parameters can be properly excluded without causing errors.

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

The way that optional parameters are handled forces some of them to be
defined even when that is not necessary. Updated handling to use a
mapping of snake_case to CamelCase names and only include defined
parameters in the call to boto for the `create` and `modify` actions.

### CODE REVIEW

**Comment by cachedout** [comment]
@blarghmatey There are a number of lint errors here. Would you mind taking a look? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/6681/violations/file/salt/modules/boto_rds.py/

**Comment by blarghmatey** [comment]
Thanks for pointing that out @cachedout 

This PR is currently against develop but it should also be merged into the Carbon release branch as it addresses a number of critical bugs in the state/execution modules for boto_rds as they exist in the current release candidates. Let me know if I need to do anything on my end to make that happen.

**Comment by cachedout** [comment]
We're not quite there on the lint fixes. A few remain:

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/6694/violations/

I have marked this as a backport so we can get it in for you.

**Comment by rallytime** [comment]
@blarghmatey Please see #37637 for the back-port to 2016.11 (this is the carbon release).

**Pull request merged**
