### PR TITLE
Docs sphinx ref and role terminology dead link replaced

### PR DESCRIPTION
**Pull request by alan-cugler**
### What does this PR do?
two links to old sphinx docs replaced to new valid sphinx docs.

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by waynew — CHANGES_REQUESTED** [review]
Hey, thanks for the PR!

There are actually a couple of other links in our docs: `grep -Inr sphinx-doc doc` will show you where the rest of them are. If you could update those as well, that'd be great!

**Comment by alan-cugler** [comment]
Alright, all dead links replaced.

**Comment by alan-cugler** [comment]
This is ready to be merged if the PR passes review, let me know if there are any problems.

**Review by twangboy — APPROVED** [review]

**Comment by twangboy** [comment]
@waynew Could you mark it resolved?

**Review by waynew — APPROVED** [review]

**Comment by waynew** [comment]
@twangboy done!

**Pull request merged**
