### PR TITLE
Only override attributes that we do not have

### PR DESCRIPTION
**Pull request by jacksontj**
Fixes #22940

### CODE REVIEW

**Comment by kiorky** [comment]
this does not solve at all my problem.

**Comment by jacksontj** [comment]
If i'm reading your other code right its trying to access copy-- which is a method of dict. This __getattr__ function wasn't allowing access to local attributes, now it is. Can you try it?

**Comment by kiorky** [comment]
No, no need.
see my comment in my pr.

**Comment by thatch45** [comment]
This is a good check regardless :)

**Pull request merged**
