### PR TITLE
Don't call close on singletons

### LINKED ISSUE #43395: StreamClosedError
### Description of Issue/Question
On specific VMs I am getting the below error message.

```
                                                         ][CRITICAL][21632] Unexpected error while connecting to saltsyndic04.domain.com
Traceback (most recent call last):
  File "/opt/salt/lib/python2.6/site-packages/salt/minion.py", line 875, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "/opt/salt/lib64/python2.6/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/opt/salt/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/opt/salt/lib64/python2.6/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/salt/lib/python2.6/site-packages/salt/minion.py", line 1053, in connect_master
    yield self._post_master_init(master)
  File "/opt/salt/lib64/python2.6/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/opt/salt/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/opt/salt/lib64/python2.6/site-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/opt/salt/lib/python2.6/site-packages/salt/minion.py", line 1128, in _post_master_init
    }, persist=True)
  File "/opt/salt/lib/python2.6/site-packages/salt/utils/schedule.py", line 577, in add_job
    tag='/salt/minion/minion_schedule_add_complete')
  File "/opt/salt/lib/python2.6/site-packages/salt/utils/event.py", line 752, in fire_event
    self.io_loop.run_sync(lambda: self.pusher.send(msg))
  File "/opt/salt/lib64/python2.6/site-packages/tornado/ioloop.py", line 444, in run_sync
    return future_cell[0].result()
  File "/opt/salt/lib64/python2.6/site-packages/tornado/concurrent.py", line 214, in result 
    raise_exc_info(self._exc_info)
  File "/opt/salt/lib64/python2.6/site-packages/tornado/gen.py", line 879, in run 
    yielded = self.gen.send(value)
  File "/opt/salt/lib/python2.6/site-packages/salt/transport/ipc.py", line 413, in send
    yield self.stream.write(pack)
  File "/opt/salt/lib64/python2.6/site-packages/tornado/iostream.py", line 367, in write
    self._check_closed()
  File "/opt/salt/lib64/python2.6/site-packages/tornado/iostream.py", line 877, in _check_closed
    raise StreamClosedError("Stream is closed")
StreamClosedError: Stream is closed
```

Looking at the code it made sense to me to add retries to IPCMessageClient since they are not implemented.
https://github.com/saltstack/salt/blob/develop/salt/transport/ipc.py#L414

I would like to suggest the following 

```
    @tornado.gen.coroutine
    def send(self, msg, timeout=None, tries=3):
        '''
        Send a message to an IPC socket

        If the socket is not currently connected, a connection will be established.

        :param dict msg: The message to be sent
        :param int timeout: Timeout when sending message (Currently unimplemented)
        '''
        if not self.connected():
            yield self.connect()
        while tries > 0:
            try:
                pack = salt.transport.frame.frame_msg_ipc(msg, raw_body=True)
                yield self.stream.write(pack)
            except tornado.iostream.StreamClosedError as exc:
                log.error('Could not connect to ips stream with error {0}.'.format(exc))
                yield self.connect()
            tries -= 1
```
@DmitryKuzmenko , @skizunov do you think this is the proper solution ?
Any suggestions ? 

### Steps to Reproduce Issue
Cannot reproduce except for the existing vms. 
Not sure why it only happens there. Any troubleshooting steps would be welcome.

### Versions Report
2016.11.5

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
### What does this PR do?
Removed direct closing of singletons objects. This makes the objects unusable when somebody could still have a reference to them and can use them.
So `close()` should be called on singletons from the only `__del__` when GC is collecting them.

### What issues does this PR fix or reference?
Fixes #43395

### Previous Behavior
Example:
* IPCClient singleton is shared between 3 objects and each of them is sent something and waiting for a response.
* The first one receiving the response calls `close` on the client that closes singleton's socket and sets others into inconsistent condition.

### New Behavior
In the example it would:
* Each of three responses are received and there are no reference to the client singleton thus GC calls `__del__` that calls `close`.

### Tests written?
No

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by DmitryKuzmenko** [comment]
@rallytime Could you please correct me if I've chosen a wrong target branch. I'll rebase then.

**Comment by rallytime** [comment]
@DmitryKuzmenko Yeah, can you change it to `2017.7`? We've already tagged `2017.7.3` :)

**Comment by DmitryKuzmenko** [comment]
@rallytime done. Thank you!

**Review by garethgreenaway — APPROVED** [review]

**Review by cachedout — CHANGES_REQUESTED** [review]
@DmitryKuzmenko There were some test failures here. Could you investigate?

**Comment by rallytime** [comment]
re-run py

**Comment by DmitryKuzmenko** [comment]
There are some related issues. I'll investigate it later after Oxygen works.

**Comment by rallytime** [comment]
Hi @DmitryKuzmenko - Just a bump on this one to see if you were able to come back to this.

**Comment by DmitryKuzmenko** [comment]
@rallytime for sure. A bit later when I'll have time.

**Comment by cachedout** [comment]
Hi @DmitryKuzmenko. Please let me know when you are able to come back to this. Thanks.

**Comment by DmitryKuzmenko** [comment]
Busy for now. I'll continue in a week.

**Comment by DmitryKuzmenko** [comment]
re-run py

**Comment by DmitryKuzmenko** [comment]
Hi @cachedout =)
I'm not finished it because I'm working on Tornado50 related redesign and this will be touched (and partially included there). So I'll finish this after that work.
Shall I just close this for now to hide this from "pending" issues?

**Comment by cachedout** [comment]
@DmitryKuzmenko We can leave it open for now since you're planning to get to it somewhat soon, I believe. Thanks.

**Comment by damon-atkins** [comment]
re-run lint

**Comment by damon-atkins** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
Closing in favor of #50862

**Pull request closed without merging**
