### PR TITLE
recomply modules/napalm_network.py to file.get_managed

### PR DESCRIPTION
**Pull request by mc**
### What does this PR do?
* adding (new) parameter attrs from modules/file.py:get_managed() to modules/napalm_network.py

It seems `modules/file.py:get_managed()` got the new mandatory parameter `attrs`, this patch makes `modules/napalm_network.py:load_template()` comply with the former change; by 
* now accepting the parameter to `load_template()`, with a (*hopefully reasonable*) default and
* adding the parameter to the call of `__salt__['file.get_managed']()`

### Tests written?

manually patched and tested

### CODE REVIEW

**Review by mirceaulinic — CHANGES_REQUESTED** [review]
As this is preparing for Oxygen only, we have plenty of time and I would suggest a couple of things:

- Add the same argument also to the `netconfig` state modules.
- Document the new field and add the `versionadded` tag (in both modules).

Thanks!

**Comment by cachedout** [comment]
@mc Did you see the above suggestions from @mirceaulinic ?

**Comment by mc** [comment]
/* 
to help search engines find this PR when someone googles the error message, 
the original error message (this PR will fix) will be:
              TypeError: get_managed() takes at least 12 arguments (12 given)
*/

**Review by mirceaulinic — APPROVED** [review]
Thanks @mc

**Review by cachedout — APPROVED** [review]

**Pull request merged**
