### PR TITLE
Ignore return code in "run_all" and do not raise an exception therefore

### PR DESCRIPTION
**Pull request by isbm**
### What does this PR do?

Addresses concerns of https://github.com/saltstack/salt/issues/51620

### Tests written?

Existing

### CODE REVIEW

**Comment by dincamihai** [comment]
Correct me if I'm wrong, but isn't this hiding any error raised by rpm?

```
try:
    rpm()
except:
    pass
```

**Comment by thatch45** [comment]
@dincamihai raises a valid point, we should likely make sure that we at least set the final retcode for the function itself as well as make sure things are logged.

**Comment by dwoz** [comment]
@isbm Ping. We're getting close to freezing 2019.2.1.

**Comment by dwoz** [comment]
@isbm This needs to be re-opened against the `master` branch. We are no
longer accepting PRs to the `2019.2`. If this fixes a bug in a `2019.2.x`
release, please make note of it in your PR to `master`. Thanks!

**Comment by terminalmage** [comment]
@dwoz this was intended as a bugfix in the 2019.2 release cycle, from the looks of it. I took the liberty of cherry-picking this onto master in https://github.com/saltstack/salt/pull/55587.

**Pull request closed without merging**
