### PR TITLE
VMware: Enable CPU and memory hot-add support

### PR DESCRIPTION
**Pull request by nicholasmhughes**
### What does this PR do?
Allows for the VMware provider to handle CPU and memory hot-add in newer versions of the software.

### What issues does this PR fix or reference?
#56144 

### Previous Behavior
Older versions of VMware handled CPU and memory hot-add through extra configs.

### New Behavior
In newer versions, it is a dedicated attribute of the config spec.
https://communities.vmware.com/thread/619066

### Tests written?
Yes. Current tests cover use.

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by cmcmarrow — CHANGES_REQUESTED** [review]
@nicholasmhughes can we get some tests?

**Comment by nicholasmhughes** [comment]
@cmcmarrow take it or leave it. this is a super minor change to a cloud provider that I made for someone else that requested it. I don't have any deployed VMware.

**Comment by nicholasmhughes** [comment]
re-run centos8

**Comment by nicholasmhughes** [comment]
re-run fedora32

**Comment by ggiesen** [comment]
@nicholasmhughes would it be too much to ask to add the following config options as well? I can open another PR but that means we won't see them before Xmas.

cpuHotRemoveEnabled
nestedHVEnabled

https://vdc-download.vmware.com/vmwb-repository/dcr-public/790263bc-bd30-48f1-af12-ed36055d718b/e5f17bfc-ecba-40bf-a04f-376bbb11e811/vim.vm.ConfigSpec.html

**Comment by ggiesen** [comment]
> 
> 
> @nicholasmhughes would it be too much to ask to add the following config options as well? I can open another PR but that means we won't see them before Xmas.
> 
> cpuHotRemoveEnabled = cpu_hot_remove
> nestedHVEnabled = nested_hv
> vPMCEnabled = vpmc
> 
> https://vdc-download.vmware.com/vmwb-repository/dcr-public/790263bc-bd30-48f1-af12-ed36055d718b/e5f17bfc-ecba-40bf-a04f-376bbb11e811/vim.vm.ConfigSpec.html

@nicholasmhughes I sent you a PR against your branch which if you accept should get merged into this PR

**Comment by nicholasmhughes** [comment]
Closing. Assume that the new VMware Salt Extension handles this.

**Pull request closed without merging**
