### PR TITLE
Pass in 'pack' variable to utils.boto.assign_funcs function from ALL boto modules

### PR DESCRIPTION
**Pull request by rallytime**
Refs #30279, #30300, #30808, and #30843.

ping @cachedout

### CODE REVIEW

**Comment by HeathNaylor** [comment]
Still not working, now when I run my highstate I get the following:
```

**Comment by rallytime** [comment]
@HeathNaylor Can you please post the output of `salt --versions` and your affected state?

**Comment by HeathNaylor** [comment]
@rallytime 
```
Salt Version:
           Salt: 2015.8.4

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: 0.9.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.1.5-x86_64-linode61
         system: Ubuntu 14.04 trusty
```

elb state file
```
Ensure staging-elb ELB exists:
    boto_elb.present:
        - name: staging-elb
        - region: us-east-1
        - availability_zones:
            - us-east-1a
            - us-east-1d
        - keyid: {{ pillar['aws']['keyid'] }}
        - key: {{ pillar['aws']['key'] }}
        - listeners:
            - elb_port: 443
              instance_port: 80
              elb_protocol: HTTPS
              instance_protocol: HTTP
              certificate: '<cert_hidden>'
            - elb_port: 8210
              instance_port: 8210
              elb_protocol: TCP
        - health_check:
            target: 'HTTP:80/'
        - attributes:
            cross_zone_load_balancing:
              enabled: true
            access_log:
              enabled: true
              s3_bucket_name: 'elb-logs'
              s3_bucket_prefix: 'my-logs'
              emit_interval: 5
        - cnames:
            - name: staging.example.com.
              zone: example.com.
              ttl: 60

add-instances:
  boto_elb.register_instances:
    - name: staging-elb
    - instances:
      - Salt-Minion-1
      - Salt-Minion-2

```

**Comment by rallytime** [comment]
@HeathNaylor Hrm...That appears to be a different problem, though I am not sure why, unless the minion you're running this test against doesn't have the correct version of boto installed on it. 

I took your state and was able to reproduce the `__salt__` stacktrace on version 2015.8.4, but then applied this pull request, and no longer get the stacktrace.

**Comment by HeathNaylor** [comment]
Does the minion need the boto_elb.py module with the `pack=__salt__` or just the master?

**Comment by rallytime** [comment]
@HeathNaylor The minion needs it, too. You can sync the module down to the minion easily by putting the `boto_elb.py` module (with the `pack=__salt__` fix) in `/srv/salt/_modules/` and using the [saltutil.sync_modules function](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.sync_modules).

Here is some more references about that in the docs:
https://docs.saltstack.com/en/latest/ref/file_server/dynamic-modules.html

**Comment by HeathNaylor** [comment]
@rallytime got it working.

**Comment by rallytime** [comment]
@HeathNaylor :+1: 

@cachedout I know why the tests are failing, but I need to take a closer look as to how to fix them.

**Comment by cachedout** [comment]
@rallytime Sounds good. You know the drill. :] Let me know when we're ready to go.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Pull request merged**
