### PR TITLE
Upgrade to ``pytest-salt-factories==0.912.1``

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title

### CODE REVIEW

**Comment by s0undt3ch** [comment]
re-run all

**Comment by garethgreenaway** [comment]
re-run all

**Comment by s0undt3ch** [comment]
re-run all

**Comment by s0undt3ch** [comment]
Arch failure is also present in the master branch: https://jenkins.saltproject.io/job/pr-arch-lts-x86_64-py3-pytest/job/master/860/testReport/
CentOS 7 TCP failures are also present in the master branch: https://jenkins.saltproject.io/job/pr-centos-7-x86_64-py3-tcp-pytest/job/master/856/testReport/
Ubuntu 20.04 TCP tests are also present in the master branch: https://jenkins.saltproject.io/job/pr-ubuntu-2004-amd64-py3-tcp-pytest/job/master/866/testReport/

**Review by waynew — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
