### PR TITLE
Fix some leftover non portable exitcodes.

### LINKED ISSUE #26773: salt-call minor breakage on Windows
Salt 2015.5.2 on Windows 2012R2. Doesn't prevent the command working, just sprinkles ugly tracebacks throughout the output. eg:

```python-traceback
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 227, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 67, in run
    self.exit(os.EX_OK)
AttributeError: 'module' object has no attribute 'EX_OK'
```

Looks like there's a few exitcode stragglers still using `os._EX_*` instead of `salt.defaults.exitcodes.EX_*`

### PR DESCRIPTION
**Pull request by styro**
Fixes #26773. Hitting some leftovers from https://github.com/saltstack/salt/pull/18897.

### CODE REVIEW

**Comment by styro** [comment]
Doh, forgot an import. I'll fix that up...

**Comment by jfindlay** [comment]
Nice, thanks @styro.  There is some [lint](https://jenkins.saltstack.com/job/salt-pr-lint-n/8926/violations/file/salt/cli/run.py/).

**Comment by styro** [comment]
Yeah, I saw that but it seems erroneous. As far as I can tell, that supposedly unused import is actually used on line 47 exactly the same way that passed OK in call.py

Am I missing something? I'm not that familiar with the vagaries of pylint :)

**Comment by jfindlay** [comment]
@styro, sorry, I should have read more closely.  I don't know why pylint is complaining about that import, so I have disabled the warning on that line in #26775.

**Pull request merged**
