### PR TITLE
Add ci scripts for windows PR builds

### PR DESCRIPTION
**Pull request by dwoz**
### What does this PR do?

Adding Jenkins ci scripts for windows PR builds. These won't actually run until Jenkins is configured to use them.

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by twangboy — APPROVED** [review]

**Comment by gtmanfred** [comment]
I used replay to setup the py2/3-windows-2016 tests

**Comment by dwoz** [comment]
At least one of the failures in these windows PR builds would have been caught by actual PR builds (see #49337). The others look flakey. I'll be making a pass on marking flakey tests as such soon.

**Review by gtmanfred — APPROVED** [review]

**Comment by cachedout** [comment]
@KaiSforza Please let us know as soon as those workers are ready to go.

**Comment by dwoz** [comment]
This PR fixes the boto test errors:

https://github.com/saltstack/salt-jenkins/pull/1095

**Comment by cachedout** [comment]
Bump @KaiSforza. Are the workers ready?

**Review by cachedout — APPROVED** [review]

**Comment by KaiSforza** [comment]
We now have 180 executors (9 nodes, 20 executors each) ready for kitchen. We should be good @cachedout

**Comment by KaiSforza** [comment]
If needed we can bump it back up to 25 or 30 and get to 225 or 270.

**Pull request merged**
