### PR TITLE
Python 3 compatibility to `salt.transport.ipc`

### PR DESCRIPTION
**Pull request by s0undt3ch**
@cachedout, @jacksontj: Objections?

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Trying something else...

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by jacksontj** [comment]
Does this work against my larger open PR for the rest of the IPC?

**Comment by s0undt3ch** [comment]
I think it won't cause any issues with your PR and this fix probably needs to be expanded to any other code which is using `salt.protocol.frame`

**Comment by s0undt3ch** [comment]
I'm closing this and I'll submit my PR against @jacksontj branch, we'll test everything on his PR.

**Comment by cachedout** [comment]
Sounds good. Thanks @s0undt3ch

**Pull request closed without merging**
