### PR TITLE
fine tuning systemd support (or, how not to destroy open-file limits when upgrading your salt-master)

### PR DESCRIPTION
**Pull request by gladiatr72**
_systemd_ completely ignores /etc/security/limits*.

It uses its own directives and requires them to be listed under [service] and above the EXECSTART directive.

Thus:

```
[Unit]
Description=The Salt Master Server
After=syslog.target network.target

[Service]
Type=notify
LimitNOFILE=49152
ExecStart=/usr/bin/salt-master

[Install]
WantedBy=multi-user.target
```

The committed spec file is based on @terminalmage 's EPEL package.

### CODE REVIEW

**Comment by gladiatr72** [comment]
The only modification to Erik's spec file is setting the _noreplace_ directive for the systemd service files.

**Comment by thatch45** [comment]
Should we be commenting out the LimitNOFILE line? Am I not reading this right?

**Comment by gladiatr72** [comment]
Yes.

**Comment by gladiatr72** [comment]
Ok, so I was thinking about this some more.  

I've run into the situation on several occasions where I've hit the (default) open-file limit even on relatively small installations.  I don't like the idea of system affecting configuration bits being set in a file buried in /usr/lib, but there's no changing that.

With that said, what do you think about *not* commenting LimitNOFILE but setting it to a (reasonable) value higher than the 4k that seems to be the default on most systems?  At least then the user would see the error in the logs and not immediately equate it with the limits.* configuration bits.

**Comment by cachedout** [comment]
@gladiatr72 Apologies for the delay here. @thatch45 will get back to you shortly.

**Comment by thatch45** [comment]
I agree completely with you @gladiatr72, w should NOT comment the LimitNOFILE line and set a reasonable default. Should we also make this configurable via /etc/{sysconfig,conf.d} by making the number we pass in a variable?

**Comment by gladiatr72** [comment]
@cachedout, no worries.  Weekends should be for Other Things :D 

@thatch45 even more ideal.

**Comment by gladiatr72** [comment]
Well, isn't that special...

It would seem that systemd restricts the use of Environment/EnvironmentFile variables to the ExecStart directive.  Still looking at this.

**Comment by gladiatr72** [comment]
It would appear that there are two options:

Set DefaultLimitFILENO in /etc/systemd/system.conf or hard set a value in the unit file. The DefaultLimit, I think, is a wash as it is not reset with a daemon-reload, plus that makes a lot of assumptions regarding whatever else might be running on the box.

**Comment by thatch45** [comment]
Sounds like we should just hard code it

**Pull request merged**
