### PR TITLE
Make system.reboot use `shutdown -r` when available

### PR DESCRIPTION
**Pull request by anlutro**
see issue #27710

### CODE REVIEW

**Comment by anlutro** [comment]
Actually, I now see that the module's `__virtual__` returns false if `salt.util.which('shutdown')` returns false... so I guess there's absolutely no reason not to use `shutdown` everywhere?

**Comment by cachedout** [comment]
@anlutro Yes, agreed. Let's use it everywhere and let __virtual__ be the gateway.

**Comment by anlutro** [comment]
Pushed a new commit where we only use `shutdown`.

**Comment by cachedout** [comment]
Great! Thanks @anlutro

**Pull request merged**
