### PR TITLE
Improve management of interfaces in debian-based distributions

### LINKED ISSUE #38672: IPv6 Network states is incomplete
### Description of Issue/Question

I'm trying to deploy IPv6 Addresses to my minions, but following documentation, it doesn't work.

I have looked at states/modules in develop branch about networking and debian.IP but can't be able to find some usefull thinks for v6. 

### Setup
*networking.sls* : 
```
lo:
  network.managed:
    - name: lo
    - type: eth
    - onboot: yes
    - userctl: no
    - ipv6_autoconf: no
    - enable_ipv6: true
    - ipv6addrs:
      - fc00::1/128
```

The output in `/etc/networking/interfaces` : 
```
auto lo
iface lo inet6 static
    netmask 64
```
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2016.11.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-57-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

### PR DESCRIPTION
**Pull request by MTecknology**
### What does this PR do?

This commit fixes a lot of issues with managing network interfaces on Debian-based distributions.

- Cleaned up documentation/examples in states.network:
  + Updated debian-based distro comment
  + Fixed example of configuring a loopback device
  + Cleaned up copy/paste mistakes
  + Added more examples
  + Verified examples work on Debian 9
- Added support for -ipaddrs and -ipv6ipaddrs to modules.debian_ip().
- Added support for loopback devices to modules.debian_ip(). (Fixes: #38672)
- Added a bunch of unit tests for modules.debian_ip.build_interface().
- Added support for dns_{nameservers,search} being a list or string.
- Added support for multiple addresses per interface

### What issues does this PR fix or reference?

- #38672
- #46388
- #46980
- #40262

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by cachedout** [comment]
@MTecknology Thanks for this. I'm afraid there is a failing test, though. Could you please take a look?

**Review by garethgreenaway — APPROVED** [review]

**Review by rallytime — APPROVED** [review]
Thank you for writing that test!

**Comment by rallytime** [comment]
@MTecknology That test is failing on CentOS 7. Can you take another look?

https://jenkinsci.saltstack.com/job/pr-kitchen-centos7-py3/job/PR-49355/10/

**Comment by MTecknology** [comment]
Go Go Jenkins!

**Comment by Ch3LL** [comment]
@garethgreenaway what branch do you need this backported to?

**Comment by garethgreenaway** [comment]
@ch3ll should go back to 2018.3

**Pull request merged**
