### PR TITLE
Add grain to list LVM volumes implement issue 57629

### LINKED ISSUE #57629: [FEATURE REQUEST]: Grain with the LVM volumes
**Is your feature request related to a problem? Please describe.**
The LVM makes easier to manage the machine storage, providing a logical abstraction over the physical disks. The logical volumes  are dynamical and could span for several disks or use only part of them. It's very common to use LVM in Linux Servers, so the filesystems could easily grow as needed and new disks are added.

But no LVM information is provided by the default grains. There is information about the disks,  ZFS information and even the Linux software RAID, mdadm, but nothing about the LVM volume groups and the logical volumes associated.

I would like to have access to the information about volume groups and logical volumes as a grain for all my Linux machines.

**Describe the solution you'd like**
I would like to have a grain with the information about the LVM volumes groups and their logical volumes

**Describe alternatives you've considered**
I considered setting up a custom grain to bring this information.  But I guess that this a useful information for everyone managing a Linux server.

### PR DESCRIPTION
**Pull request by piterpunk**
### What does this PR do?
This initial support implements a grain called "lvm" which returns a dictionary with the volume groups, each one with a list of their logical volumes inside.

LVM is an important information about a Linux machine. Usually Linux servers have most or all their disk filesystems using a logical volume as mountpoint.

### What issues does this PR fix or reference?
Implements and resolves #57629 

### New Behavior
To have a grain with the list of LVM volumes:
```
root@marvin:~# salt-call grains.get lvm
local:
    ----------
    marvinvg00:
        - opt
        - root
        - swap
        - tmp
        - usr
        - var
    marvinvg01:
        - home
        - srv
        - usrlocal
```

### Merge requirements satisfied?
[salt-runtests-20200610192428.log](https://github.com/saltstack/salt/files/4761571/salt-runtests-20200610192428.log)

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by DmitryKuzmenko** [comment]
@piterpunk thank you for contribution! Could you please cover your changes with tests?

**Comment by piterpunk** [comment]
> @piterpunk thank you for contribution! Could you please cover your changes with tests?

Hi Dmitry, tests added. I hope they are Ok.

The tests for Linux and AIX are not the same because in AIX the LVM is part of base system, so it's always installed and with at least one volume group created.

**Comment by DmitryKuzmenko** [comment]
@piterpunk thank you! I've restarted macos x mojave tests the failure looked not related to your changes.

**Comment by piterpunk** [comment]
@DmitryKuzmenko , seeing the console logs, the failure at MacOSX seems to be while setting up the environment, it didn't even began to run the tests.

**Review by DmitryKuzmenko — DISMISSED** [review]

**Comment by DmitryKuzmenko** [comment]
@piterpunk Everything passed. Thank you for your work!

**Comment by piterpunk** [comment]
@DmitryKuzmenko , I did some changes to pass the new pre-commit tests, removing the usage of six and Py2 support.

**Review by DmitryKuzmenko — APPROVED** [review]

**Comment by DmitryKuzmenko** [comment]
@piterpunk thank you!

**Comment by DmitryKuzmenko** [comment]
Tests are passing now (again).

**Comment by piterpunk** [comment]
> Tests are passing now (again).

@DmitryKuzmenko , it's a lottery. Most tests fails by timeout, no available space, or error cloning the repository. I don't know if and how I can re-run only the failed tests, so my alternative is to merge from master until all tests passed.

**Pull request merged**
