### PR TITLE
influx: Drop unhandled kwargs for InfluxDBClient initializer

### PR DESCRIPTION
**Pull request by bbczeuz**
### What does this PR do?
It drops selected `kwargs` from the InfluxDBClient initializer. They are unhandled and InfluxDBClient throws an exception.
I'm not sure if filtering on a module level is the best thing to do, as this issue might happen with other modules, too. Therefore I provide an alternate diff that drops the kwargs at the central place:
```
diff --git a/salt/state.py b/salt/state.py
index c423066702..1785922262 100644
--- a/salt/state.py
+++ b/salt/state.py
@@ -115,8 +115,11 @@ STATE_RUNTIME_KEYWORDS = frozenset([
     '__orchestration_jid__',
     '__pub_user',
     '__pub_arg',
+    '__pub_id',
     '__pub_jid',
     '__pub_fun',
+    '__pub_fun_args',
+    '__pub_schedule',
     '__pub_tgt',
     '__pub_ret',
     '__pub_pid',
```

### What issues does this PR fix or reference?
#47614

### Previous Behavior
influxdb module crashes during initialization

### New Behavior
influxdb module usable

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by cachedout** [comment]
I don't think that filtering at the module level is the way to go here. This will almost assuredly break at some point in the future. I think we should try filtering at the state level as you suggest and see how the test suite likes it.

**Comment by cachedout** [comment]
@bbczeuz Did you see my comment above?

**Comment by bbczeuz** [comment]
@cachedout Sorry, I missed that. I'll rebase and adapt the PR to filter on the state level and push it for testing. Expect an update in the next days.

**Comment by cachedout** [comment]
@bbczeuz Sounds great. Thank you!

**Comment by bbczeuz** [comment]
Now, the params are filtered at STATE_INTERNAL_KEYWORDS in salt/state.py. This dict is used by several other states (nftables, iptables, pkgrepo) and modules (x509, nftables, iptables) for the same purpose. Let's see how this behaves in testing.

**Comment by cachedout** [comment]
Doesn't look like things went too well with the test suite, sadly.

**Comment by cachedout** [comment]
@bbczeuz We'll need you to please investigate the test failures here before we can merge this.

**Comment by dwoz** [comment]
@bbczeuz Are you able to look at the test failures?

**Comment by dwoz** [comment]
@cachedout The tests passed this go around. Do you approve this change?

**Review by cachedout — APPROVED** [review]

**Pull request merged**
