### PR TITLE
Several gitfs/git_pillar fixes

### LINKED ISSUE #27432: Using specific tag as GitFS remote
The [GitFS docs](https://docs.saltstack.com/en/latest/ref/configuration/master.html#std:conf_master-gitfs_base) say that I can set `gitfs_base` to point at a tag in my remote. This doesn't work; after highstate the `gitfs_remote` repo points at `master`.

My `/etc/salt/minion`:

    file_client: local

    fileserver_backend:
      - roots
      - git

    gitfs_base: v0.2.0

    gitfs_remotes:
      - git://github.com/mafrosis/salt-formulae

    file_roots:
      base:
        - /srv/salt

Some commands after running a `highstate`

    > cat /var/cache/salt/minion/gitfs/remote_map.txt
    # gitfs_remote map as of 26 Sep 2015 08:55:10.497089
    6fa7938d35062aedfd594b8359245491 = https://github.com/mafrosis/salt-formulae
    >
    > cat /var/cache/salt/minion/gitfs/6fa7938d35062aedfd594b8359245491/.git/HEAD
    ref: refs/heads/master

Further to that:
- If `gitfs_base` is included, states from the `gitfs_remote` are not found at all.
- If `gitfs_base` is removed, a highstate will finish using states from `master` branch on the remote.

### LINKED ISSUE #28311: git_pillar conflicts
When I installed salt-master on CentOS 7 and use git_pillar for the backend, I get "Failed to checkout qa from git_pillar remote 'qa git@git.apparatus.net:beta/pepper.git': 37 conflicts prevent checkout". If I navigate to /var/cache/salt/master/git_pillar/<long string>/ and run 'git pull origin qa' then it creates a "master" branch. If I 'git checkout qa' then everything seems to work fine. 

This happens even if I remove /var/cache/salt/master/git_pillar/. Curious why we get the "37 conflicts" when there is nothing in the gitfs_pillar/<long_string> directory to begin with. 

```
Salt Version:
           Salt: 2015.8.1
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Jun 24 2015, 00:41:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.3.0
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: 1.4.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.23.1
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-123.el7.x86_64
         system: CentOS Linux 7.1.1503 Core
```

### LINKED ISSUE #29015: git_pillar not honoring git_pillar_base
Consider the following master config:

```
fileserver_backend:
  - git

gitfs_provider: gitpython
gitfs_base: dl
gitfs_root: salt

gitfs_remotes:
    - ssh://git@source.gitlab.com/devops/ops.git

ext_pillar:
    - git:
      - dl ssh://git@source.gitlab.com/devops/ops.git:
        - root: salt/pillar
```

From that I would assume that the branch that would be referenced would be the 'dl' branch yes?

In my cache dir I see the following here: /var/cache/salt/master/gitfs/5eac921619e32e399818342f847b05a9/.git/HEAD

```
ref: refs/heads/master
```

I would expect it refer to ref: refs/heads/dl 

git status in my gitfs cache repo shows

```
On branch master

Initial commit
```

Which is incorrect even for the master.. seeing as there are a lot more commits than just the initial one. :)

It seems my ext_pillar is correct. My git_pillar git status shows:
```
HEAD detached at origin/dl
```

It would seem as though the gitfs is not honoring the aforementioned gitfs_base property.

### PR DESCRIPTION
**Pull request by terminalmage**
**DON'T MERGE, I NEED TO INVESTIGATE A POTENTIAL ISSUE WITH STALE REF CLEANING**
1. Properly detect base branch/tag in git_pillar (fixes #29015)
2. Properly resolve base saltenv from tag ref (fixes #27432)
3. Add ref for local HEAD if not present (fixes #28311)

### CODE REVIEW

**Comment by mafrosis** [comment]
Thanks for this @terminalmage. Looks like it will clear up all the problems I've had trying to use branches with gitfs/git_pillar :+1:

**Comment by terminalmage** [comment]
No problem. Sorry for the delay, I had hoped to get this fixed in time for the 2015.8.2 release but it will have to wait for 2015.8.3.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@terminalmage Please let me know when this is ready to go. Thanks!

**Comment by terminalmage** [comment]
Looking at it right now. The issue is that, from time to time, the local refs are being cleared when they shouldn't be. For pygit2 we use the git CLI to do a dry run of ``git prune`` to detect stale refs (since no means of determining them is present in pygit2), so my guess is that something is going funny with that command and it's exiting without any stdout, so the function that cleans the stale refs thinks that there are no remote refs and clears out all local refs to make it match what it thinks is on the remote side.

**Comment by terminalmage** [comment]
OK, I found the reason. For git_pillar/winrepo using pygit2, the act of checking out a remote ref does not create a local head for that ref, so we have to create one so there is something to checkout. The problem though, is that as this is not a remote ref, we mistakenly remove that ref when we go to clean the local copies of remote refs that have been removed on the remote repo. We have to clean these refs for anything that uses salt.utils.gitfs to be able to reflect the fact that a tag or branch has been removed from the remote repo and thus remove it locally so it is not detected as an environment anymore.

It turns out that this was a pre-existing issue with pygit2 that was (as far as I know) not yet reported. I've fixed it now in the commits I just pushed to this PR.

I also made a fix to fac588c when the non-default branch is also the remote HEAD, so we don't try to add a reference that already exists.

Finally, I realized that my fix for #27432 only really applied to pygit2, so I modified the code so that the environment detection uses common code irrespective of which provider is being used, effectively making this fix work for GitPython and dulwich in addition to pygit2.

**Comment by cachedout** [comment]
@terminalmage Sounds good. Does that this mean that this PR is ready to go or do you have additional changes you'd like to get in?

**Comment by terminalmage** [comment]
I don't have any additional changes to make. Merge away.

**Comment by snarfmonkey** [comment]
We use Dulwich for a gitfs backend, and our states gitfs very much stopped working after upgrading from 2015.8.1 to 2015.8.3. I admit I am not 100% clear on what the issue was, but the contents of the repo were not being written to /var/cache/salt/master/gitfs and no states could be run as a result. Pillar seemed to work but could have been reading from disk cache. Reverting the version to 2015.8.1 fixed the issue.

Some relevant config:
fileserver_backend:
  - git
  - roots # nothing in /srv/salt though
gitfs_provider: dulwich
gitfs_remotes:
  - git+ssh://git@github.com/our-supersweet-saltstates-repo
gitfs_env_whitelist:
  - base*
  - master*
gitfs_base: master

None of the logs indicate that gitfs is having any trouble accessing the repo. 

When trying to update the gitfs repo in /var/cache/salt/master/gitfs, we observe the following:

"There is no tracking information for the current branch.
Please specify which branch you want to merge with."

Could be related.

**Comment by terminalmage** [comment]
@snarfmonkey This is the comment thread of a pull request. Please open a new report, and include additional relevant information to assist in troubleshooting, such as the version of Dulwich being used. In addition to that, please explain how you are handling authentication. I've not yet attempted it with Dulwich, so are you just using a passphraseless SSH private key? Include this sort of information in your report.

**Comment by snarfmonkey** [comment]
My bad. I was eager to get to the holiday party. Here we go: https://github.com/saltstack/salt/issues/29684

**Comment by tehmaspc** [comment]
It seems like you guys changed the merging strategy by default for gitfs (ext_pillar) in 2015.8.3 from 2015.8.1. We've been racking our brains today trying to figure out why our git pillars were not working as they did a few days ago before the 2015.8.3 upgrade.

can you guys confirm this? @terminalmage 

```
2015.8.1 - `update` behaves like merge_lists=True
 
2015.8.3 - `update` introduces merge_lists, defaults to False; breaks previous default behavior 
```

```
diff --git a/salt/utils/dictupdate.py b/salt/utils/dictupdate.py
index d7feed1..033b227 100644
--- a/salt/utils/dictupdate.py
+++ b/salt/utils/dictupdate.py
@@ -17,7 +17,7 @@ from salt.serializers.yamlex import merge_recursive as _yamlex_merge_recursive
 log = logging.getLogger(__name__)
 
 
-def update(dest, upd, recursive_update=True):
+def update(dest, upd, recursive_update=True, merge_lists=False):
     '''
     Recursive version of the default dict.update
 
@@ -25,6 +25,10 @@ def update(dest, upd, recursive_update=True):
 
     If recursive_update=False, will use the classic dict.update, or fall back
     on a manual merge (helpful for non-dict types like FunctionWrapper)
+
+    If merge_lists=True, will aggregate list object types instead of replace.
+    This behavior is only activated when recursive_update=True. By default
+    merge_lists=False.
     '''
     if (not isinstance(dest, collections.Mapping)) \
             or (not isinstance(upd, collections.Mapping)):
@@ -41,11 +45,14 @@ def update(dest, upd, recursive_update=True):
                 dest_subkey = None
             if isinstance(dest_subkey, collections.Mapping) \
                     and isinstance(val, collections.Mapping):
-                ret = update(dest_subkey, val)
+                ret = update(dest_subkey, val, merge_lists=merge_lists)
                 dest[key] = ret
             elif isinstance(dest_subkey, list) \
                      and isinstance(val, list):
-                dest[key] = dest.get(key, []) + val
+                if merge_lists:
+                    dest[key] = dest.get(key, []) + val
+                else:
+                    dest[key] = upd[key]
             else:
                 dest[key] = upd[key]
         return dest
```

**Pull request merged**
