### PR TITLE
Support directory symlinks

### PR DESCRIPTION
**Pull request by TheLocehiliosan**
### What does this PR do?
This PR added initial support for directory symlinks in GitFS backends. Support has been added for Pygit2 and GitPython.

This bug is a large problem for me, so I didn't want to wait for it to be implemented. I made the initial changes in an older version of Salt (2017.7.3), but this part of the code base is barely changed going all the way up to the develop branch, so porting it forwards/and backwards is pretty simple.
 
### What issues does this PR fix or reference?
#21413

### Previous Behavior
Symlinks which reference files, work correctly. Symlinks which reference directories are broken.

### New Behavior
Symlinks which reference directories are now followed.

### Tests written?
No

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by terminalmage — CHANGES_REQUESTED** [review]
This needs some unit tests added. The `setUpClass` in tests/unit/fileserver/test_gitfs.py will need to be modified to add a symlink before we init the temporary repo, however. That function basically copies the contents of `tests/integration/files/file/base/` into a tempdir and then does a git init and commit using GitPython, and uses that repo as the one against which to run unit tests. However, there aren't currently any directory symlinks there. So the following two changes would need to be made to the `setUpClass`:

1. A directory symlink would need to be added, preferably to one of the dirs in `tests/integration/files/file/base/`. For example, cd to that dir and run something like `ln -sf test_deep subdir`.
2. The call to `shutil.copytree()` would need to have the `symlinks=True` argument added, to ensure that when we copy the files to create the temporary repo, we preserve the symlinks.

In addition to the above, unit tests would need to be added under the `GitFSTestFuncs` class so that they are tested under both GitPython and Pygit2.

Tests that should be added would include some for `dir_list` and `file_list` which show that the expected files are found.

**Comment by cachedout** [comment]
Closed due to lack of response to review comments.

@TheLocehiliosan if you would like to continue work on this, please let us know by leaving a comment or just push code to your branch and it should re-open.

**Comment by TheLocehiliosan** [comment]
@cachedout I do plan to have a go at writing unit tests for this. A few weeks back I managed to get the existing tests working via Docker/Barnacle, but I haven't had the time to work on it yet.

**Comment by theY4Kman** [comment]
Heads-up, when
 - Using `root: ...` under the gitfs root
 - With a relative symlink pointing above the specified root

```
Exception occurred in runner fileserver.symlink_list: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/runners/fileserver.py", line 239, in symlink_list
    return fileserver.symlink_list(load=load)
  File "/usr/lib/python2.7/dist-packages/salt/utils/decorators/__init__.py", line 594, in wrapped
    **salt.utils.data.decode_dict(kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 827, in symlink_list
    ret = self.servers[symlstr](load)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/gitfs.py", line 207, in symlink_list
    return _gitfs().symlink_list(load)
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 3100, in symlink_list
    symlinks = self._file_lists(load, 'symlinks')
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 3053, in _file_lists
    repo_files, repo_symlinks = repo.file_list(load['saltenv'])
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1908, in file_list
    _traverse(tree, blobs, self.root(tgt_env))
  File "/usr/lib/python2.7/dist-packages/salt/utils/gitfs.py", line 1873, in _traverse
    if tree[link_tgt].type == 'tree':
KeyError: '../formulas/nginx-formula/nginx/'
```

**Comment by TheLocehiliosan** [comment]
I've updated this for a few bugs found. I've added unit tests, and rebased off of the develop branch. I'm not sure why, but this PR hasn't updated with the pushed commits.

**Comment by TheLocehiliosan** [comment]
@theY4Kman You can checkout the latest version in my branch, it should resolve the KeyError you encountered.

**Comment by TheLocehiliosan** [comment]
@cachedout I thought commenting would re-open this PR. Maybe the reason the new commits don't show up in the PR is because it is closed? I can't see how to re-open it myself.

**Comment by TheLocehiliosan** [comment]
@cachedout / @terminalmage - Is it possible to re-open this PR? Or do I need to create a new PR?

**Pull request closed without merging**
