### PR TITLE
Merge forward #41429 into Nitrogen

### PR DESCRIPTION
**Pull request by mirceaulinic**
### What does this PR do?

Merge forward #41429 into Nitrogen

#41338 exists also in current Nitrogen codebase. Porting @ricohouse's commit to make sure we kill the bug in the next release.

### CODE REVIEW

**Comment by rallytime** [comment]
hey @mirceaulinic - thanks for submitting this, however, we do merge forwards frequently from each branch. I haven't done one into nitrogen yet since #41429 was merged just yesterday. Instead of porting fixes individually, I'll close this out so the affected change is merged forward with everything else in the 2016.11 branch.

**Comment by mirceaulinic** [comment]
Ah, alright, thanks for info ;)

**Comment by rallytime** [comment]
I'll be sure to get that merge-forward in today ;)

**Comment by rallytime** [comment]
@mirceaulinic See #41463

**Comment by mirceaulinic** [comment]
Thanks @rallytime - it wasn't urgent, just that I wanted to make sure it won't fall off my radar.

**Pull request closed without merging**
