### PR TITLE
state_top value also affects pillar top file

### PR DESCRIPTION
**Pull request by ghost**
Hi,
thanks for making Saltstack. It's terrific. 
When I was looking for an option to change the name of the pillar top file I couldn't find anything, but I found out that 'state_top' also affects the name of pillar top file. My change tries to make this behaviour explicit.
Greetings,
Peter

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Review by terminalmage — APPROVED** [review]
This looks good, though I don't see why we can't also separate this out so that the pillar top file has its own config setting. Maybe open a separate issue for that?

**Comment by letsmakesense** [comment]
A separate setting for 'pillar_top' would make it clearer. It is not self-explanatory that the pillar top file is configured by the setting 'state_top'

**Comment by rallytime** [comment]
Thanks for this update @letsmakesense. Let's get this documentation change in, but would you like to open an issue about the config setting? Then we can get that fixed and be more explicit.

**Comment by letsmakesense** [comment]
Thanks for merging @rallytime. I opened a new issue for the 'pillar_top' setting: #42630

**Pull request merged**
