### PR TITLE
Add new slack returner based on incoming webhooks

### PR DESCRIPTION
**Pull request by cdalvaro**
### What does this PR do?

Add a new slack returner based on incoming webhooks

slack_webhook_returner

### Tests written?

No

### Commits signed with GPG?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by damon-atkins** [comment]
What is the difference between salt/returners/slack_returner and this code?

**Comment by cdalvaro** [comment]
> So can you keep them compatible? What else needs to be changed in salt to work with the new API?

Do you mean, what changes are necessary to be made in `slack_returner` in order to make compatible with the new API too?

If that is your question, I think that changes should be minimum. Just adding the parameter for the webhook url and based on whether a webhook is passed or an api_token choose the post method.

**Review by thatch45 — APPROVED** [review]

**Comment by cdalvaro** [comment]
Will this PR finally be approved? Or it is needed some change?

**Comment by cdalvaro** [comment]
Thank you very much, @thatch45 !

**Comment by thatch45** [comment]
Sure thing, but I likely should not have merged this without tests. If you can get some tests in it would be greatly appreciated!

**Pull request merged**
