### PR TITLE
[WIP] requisites without explicitly providing the state module

### PR DESCRIPTION
**Pull request by anlutro**
See issue #4597

### CODE REVIEW

**Comment by anlutro** [comment]
This currently causes an infinite loop, and I have no idea why.

```
RuntimeError: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/tmp/.vagrant_6a32f1_salt/salt-call", line 15, in <module>
    salt_call()
  File "/tmp/.vagrant_6a32f1_salt/py2/salt/scripts.py", line 333, in salt_call
    client.run()
  File "/tmp/.vagrant_6a32f1_salt/py2/salt/cli/call.py", line 58, in run
    caller.run()
  File "/tmp/.vagrant_6a32f1_salt/py2/salt/cli/caller.py", line 133, in run
    ret = self.call()
  File "/tmp/.vagrant_6a32f1_salt/py2/salt/cli/caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "/tmp/.vagrant_6a32f1_salt/py2/salt/modules/state.py", line 1300, in pkg
    ret = st_.call_chunks(lowstate)
  File "/tmp/.vagrant_6a32f1_salt/py2/salt/state.py", line 1727, in call_chunks
    running = self.call_chunk(low, running, chunks)
  File "/tmp/.vagrant_6a32f1_salt/py2/salt/state.py", line 1999, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/tmp/.vagrant_6a32f1_salt/py2/salt/state.py", line 1999, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/tmp/.vagrant_6a32f1_salt/py2/salt/state.py", line 1999, in call_chunk
...
```

**Comment by anlutro** [comment]
Fixed the infinite recursion. Seems to work with a simple test state locally.

**Comment by anlutro** [comment]
Since it (surprisingly) seems to be working fine, I added some documentation.

**Comment by thatch45** [comment]
This is very well done, and yes, the state system can be modified this easily :)
Thanks, I am surprised I did not think of this! Very nice!

**Pull request merged**
