### PR TITLE
Junos specific documentation for topic Network Automation

### PR DESCRIPTION
**Pull request by vnitinv**
### What does this PR do?
Adds junos specific documentation in the "Network Automation" topic. The content added includes:
* Getting started
* CLI examples
* State file examples
* Junos syslog engine

### What issues does this PR fix or reference?
saltstack#41028

### Previous Behavior
NA

### New Behavior
NA

### Tests written?
Documentation. No test cases required.

### CODE REVIEW

**Review by mirceaulinic — CHANGES_REQUESTED** [review]
Great addition.
Please, don't change the order.

**Comment by vnitinv** [comment]
@mirceaulinic We just changed that to be in Alphabetical order. We have many others which will come even above junos in future.

**Comment by mirceaulinic** [comment]
Ack @vnitinv. My initial idea was to sort them depending on the number of platforms covered, while vendor-specific would serve a smaller group of target users. Also, usually changes are added historically. But I'm not keen on doing this...

**Comment by cachedout** [comment]
I agree with @mirceaulinic. IMHO, these should be historical and not alphabetical.

**Comment by vnitinv** [comment]
@mirceaulinic @cachedout Did the changes as per feedback. Please review

**Review by cachedout — APPROVED** [review]

**Pull request merged**
