### PR TITLE
Ignore errors on reading license info with dpkg_lowpkg

### PR DESCRIPTION
**Pull request by vzhestkov**
### What does this PR do?

`/usr/share/doc/*/copyright` could contain symbols invalid for UTF-8 and it causes the traceback on reading it.
In general it's safe just to ignore it.

### Previous Behavior
Possible tracebacks on any operations on getting packages data for Debian based distros

### New Behavior
Normal behavior

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by garethgreenaway** [comment]
@vzhestkov This one needs a changelog and tests.

**Comment by vzhestkov** [comment]
Will add the changelog, but I'm bit confused with the test. It's possible to check if the parameter was specified on calling `salt.utils.files.fopen`, but in this case it looks a bit strange for testing. Or we need to create a file for testing, and in this case it sounds more sutable for integration testing than for unit testing.

**Comment by garethgreenaway** [comment]
@vzhestkov Thought a bit more about this and I'm wondering what errors are going to be ignored with that addition?  Is this going to mask a problem down the road?

**Comment by vzhestkov** [comment]
This parameter prevents errors while reading the `copyright` files to get the License information from.
We can use `add-apt-key/copyright` from Ubuntu 18.04 as an example.
```
Copyright � 2007 Sun Microsystems, Inc.
```
The copyright symbol there is 0xA9 what causing errors while reading the file.
For me it looks totally safe to just ignore such errors as the data from the file just informative and not causing any difference in logic of processing.

**Review by twangboy — APPROVED** [review]

**Review by twangboy — CHANGES_REQUESTED** [review]
Needs tests and changelog

**Comment by vzhestkov** [comment]
@twangboy changelog is there already, but for the test could you please give a hint how to properly test such issues. The problem that for proper testing mocking `salt.utils.files.fopen` is not really a good idea, proper testing is only possible in case of reading the file with such symbols causing reading errors, but as I see in general it's out of unit test scope, with integration testing it requires way more effort than the idea of the fix itself. Does it make sense to create such test?

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
