### PR TITLE
Fix cloud roster results in py3 #44449

### PR DESCRIPTION
**Pull request by dwoz**
### What does this PR do?

Fixes cloud roster so newly created could minions can be found by salt-ssh

### What issues does this PR fix or reference?

#44449 

### Previous Behavior

Cache files failed to load because of encoding issues

### New Behavior

Cache files load cleanly

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Review by gtmanfred — CHANGES_REQUESTED** [review]
Looks like mode was set, but not used for one of the fopens

**Comment by rallytime** [comment]
@dwoz Did you get a chance to review the comments above? This change also has a merge conflict now and will need to be rebased.

**Comment by dwoz** [comment]
@gtmanfred Thanks for catching that, I've push fix.

@rallytime I've resolved the issues found in code review and also the merge conflict.

**Review by gtmanfred — APPROVED** [review]

**Comment by rallytime** [comment]
Thanks @dwoz!

**Comment by rallytime** [comment]
@dwoz This change was marked for back-porting (likely because the bug was reported against the 2017.7.2 release). However, I am unable to back-port it cleanly. Can you make this fix against the 2017.7 branch as well?

**Comment by dwoz** [comment]
@rallytime, sure I will look into this.

**Comment by rallytime** [comment]
Thank you so much!

**Comment by dwoz** [comment]
@rallytime I've opened #45720 to address the issue in 2017.7.

**Pull request merged**
