### PR TITLE
Fix pkg.version_cmp on openEuler

### LINKED ISSUE #62248: [BUG] pkg.version_cmp on openEuler systems fails
**Description**
Runnig pkg.version_cmp on openEuler systems fails 

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Salt master is a uyuni server, latest available version (based on opensuse 15.4). Salt minion is an openEuler 22.03 LTS with latest patches.

- [ ] on-prem machine
- [X] VM (KVM)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)
```
uyuni:~ # salt '192*' pkg.version_cmp 4.10.0-3.oe2203 4
192.168.122.173:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/minion.py", line 1916, in _thread_return
        return_data = minion_instance._execute_job_function(
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/minion.py", line 1873, in _execute_job_function
        return_data = self.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/executors/venv.py", line 24, in execute
        return __executors__["direct_call.execute"](opts, data, func, args, kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/executors/direct_call.py", line 10, in execute
        return func(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/modules/yumpkg.py", line 685, in version_cmp
        return __salt__["lowpkg.version_cmp"](pkg1, pkg2, ignore_epoch=ignore_epoch)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/context.py", line 78, in __getitem__
        return self.value()[item]
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 334, in __getitem__
        super().__getitem__(item)  # try to get the item from the dictionary
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/utils/lazy.py", line 105, in __getitem__
        raise KeyError(key)
    KeyError: 'lowpkg.version_cmp'
ERROR: Minions returned with non-zero exit code

uyuni:~ # salt '192*' grains.get os_family
192.168.122.173:
    openEuler
```

**Expected behavior**
A basic patch fixes the issue (will be added in a PR soon). When running the same command again with the patch, this is the output:

```
uyuni:~ # salt '192*' pkg.version_cmp 4.10.0-3.oe2203 4
192.168.122.173:
    1
```

**Screenshots**
Console output will act as screenshot.

**Versions Report**
Master:
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
uyuni:~ # salt --versions-report
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: 1.13.2
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 1.3.0
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: 3.9.0
  pycryptodome: Not Installed
        pygit2: 1.7.0
        Python: 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3
 
System Versions:
          dist: opensuse-leap 15.4 
        locale: UTF-8
       machine: x86_64
       release: 5.14.21-150400.22-default
        system: Linux
       version: openSUSE Leap 15.4 
```
</details>

Minion:
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
[root@openeuler ~]# venv-salt-call --versions-report
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: 4.2.0
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.10.2 (main, Mar 01 2022, 07:23:53) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.2.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3
 
System Versions:
          dist: openeuler 22.03 
        locale: utf-8
       machine: x86_64
       release: 5.10.0-60.18.0.50.oe2203.x86_64
        system: Linux
       version: openEuler 22.03 

```
</details>

**Additional context**

### PR DESCRIPTION
**Pull request by raulillo82**
### What does this PR do?
Fixes pkg.version_cmp on openEuler systems (and a few other os flavors that were affected as well).

### What issues does this PR fix or reference?
Fixes: #62248

### Previous Behavior
```
uyuni:~ # salt '192*' pkg.version_cmp 4.10.0-3.oe2203 4
192.168.122.173:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/minion.py", line 1916, in _thread_return
        return_data = minion_instance._execute_job_function(
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/minion.py", line 1873, in _execute_job_function
        return_data = self.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/executors/venv.py", line 24, in execute
        return __executors__["direct_call.execute"](opts, data, func, args, kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/executors/direct_call.py", line 10, in execute
        return func(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/modules/yumpkg.py", line 685, in version_cmp
        return __salt__["lowpkg.version_cmp"](pkg1, pkg2, ignore_epoch=ignore_epoch)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/context.py", line 78, in __getitem__
        return self.value()[item]
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 334, in __getitem__
        super().__getitem__(item)  # try to get the item from the dictionary
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/utils/lazy.py", line 105, in __getitem__
        raise KeyError(key)
    KeyError: 'lowpkg.version_cmp'
ERROR: Minions returned with non-zero exit code

uyuni:~ # salt '192*' grains.get os_family
192.168.122.173:
    openEuler
```

### New Behavior
```
uyuni:~ # salt '192*' pkg.version_cmp 4.10.0-3.oe2203 4
192.168.122.173:
    1
```

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by raulillo82** [comment]
Related test passes successfully:

```
(salt) raul@laptop:~/gh-forked-projects/saltstack/salt-1>  (fix_issue_62248)$ python3 -m nox -e "pytest-3.7(coverage=False)" -- tests/pytests/unit/modules/test_rpm_lowpkg.py
nox > Running session pytest-3.7(coverage=False)
nox > Re-using existing virtual environment at .nox/pytest-3-7-coverage-false.
nox > Session pytest-3.7(coverage=False) was successful.
nox > Running session pytest-parametrized-3.7(crypto=None, transport='zeromq', coverage=False)
nox > Re-using existing virtual environment at .nox/pytest-parametrized-3-7-crypto-none-transport-zeromq-coverage-false.
nox > python -m pip install --progress-bar=off -U 'pip>=20.2.4,<21.2' 'setuptools!=50.*,!=51.*,!=52.*,<59' wheel
nox > python -m pip install --progress-bar=off -r requirements/static/ci/py3.7/linux.txt
nox > python -m pytest --rootdir /home/raul/gh-forked-projects/saltstack/salt-1 --log-file=/home/raul/gh-forked-projects/saltstack/salt-1/artifacts/logs/runtests-20220630130202.869038.log --log-file-level=debug --show-capture=no -ra -s --showlocals --transport=zeromq tests/pytests/unit/modules/test_rpm_lowpkg.py
============================================================================================== test session starts ==============================================================================================
platform linux -- Python 3.7.0, pytest-7.0.1, pluggy-0.13.0
tempdir: /tmp/stsuite
max open files; soft: 3072; hard: 524288
rootdir: /home/raul/gh-forked-projects/saltstack/salt-1, configfile: pytest.ini
plugins: skip-markers-1.2.0, helpers-namespace-2021.4.29, tempdir-2019.10.12, system-statistics-1.0.2, shell-utilities-1.4.0, salt-factories-1.0.0rc17, timeout-1.4.2, subtests-0.4.0, httpserver-1.0.4, flaky-3.7.0
collected 19 items                                                                                                                                                                                              

tests/pytests/unit/modules/test_rpm_lowpkg.py ............s.s....

============================================================================================ short test summary info ============================================================================================
SKIPPED [1] tests/pytests/unit/modules/test_rpm_lowpkg.py:232: The RPM lib is not installed, skipping
SKIPPED [1] tests/pytests/unit/modules/test_rpm_lowpkg.py:226: The rpmdev-vercmp binary is not installed
========================================================================================= 17 passed, 2 skipped in 1.00s =========================================================================================
nox > Session pytest-parametrized-3.7(crypto=None, transport='zeromq', coverage=False) was successful.
nox > Ran multiple sessions:
nox > * pytest-3.7(coverage=False): success
nox > * pytest-parametrized-3.7(crypto=None, transport='zeromq', coverage=False): success
```

**Comment by raulillo82** [comment]
Additional tests after noticing some were missing:
```

(salt) raul@laptop:~/gh-forked-projects/saltstack/salt-1>  (fix_issue_62248)$ python3 -m nox -e "pytest-3.7(coverage=False)" -- tests/pytests/unit/modules/test_rpm_lowpkg.py
nox > Running session pytest-3.7(coverage=False)
nox > Re-using existing virtual environment at .nox/pytest-3-7-coverage-false.
nox > Session pytest-3.7(coverage=False) was successful.
nox > Running session pytest-parametrized-3.7(crypto=None, transport='zeromq', coverage=False)
nox > Re-using existing virtual environment at .nox/pytest-parametrized-3-7-crypto-none-transport-zeromq-coverage-false.
nox > python -m pip install --progress-bar=off -U 'pip>=20.2.4,<21.2' 'setuptools!=50.*,!=51.*,!=52.*,<59' wheel
nox > python -m pip install --progress-bar=off -r requirements/static/ci/py3.7/linux.txt
nox > python -m pytest --rootdir /home/raul/gh-forked-projects/saltstack/salt-1 --log-file=/home/raul/gh-forked-projects/saltstack/salt-1/artifacts/logs/runtests-20220630132110.514809.log --log-file-level=debug --show-capture=no -ra -s --showlocals --transport=zeromq tests/pytests/unit/modules/test_rpm_lowpkg.py
============================================================================================== test session starts ==============================================================================================
platform linux -- Python 3.7.0, pytest-7.0.1, pluggy-0.13.0
tempdir: /tmp/stsuite
max open files; soft: 3072; hard: 524288
rootdir: /home/raul/gh-forked-projects/saltstack/salt-1, configfile: pytest.ini
plugins: skip-markers-1.2.0, helpers-namespace-2021.4.29, tempdir-2019.10.12, system-statistics-1.0.2, shell-utilities-1.4.0, salt-factories-1.0.0rc17, timeout-1.4.2, subtests-0.4.0, httpserver-1.0.4, flaky-3.7.0
collected 19 items                                                                                                                                                                                              

tests/pytests/unit/modules/test_rpm_lowpkg.py ............s......

============================================================================================ short test summary info ============================================================================================
SKIPPED [1] tests/pytests/unit/modules/test_rpm_lowpkg.py:232: The RPM lib is not installed, skipping
========================================================================================= 18 passed, 1 skipped in 1.00s =========================================================================================
nox > Session pytest-parametrized-3.7(crypto=None, transport='zeromq', coverage=False) was successful.
nox > Ran multiple sessions:
nox > * pytest-3.7(coverage=False): success
nox > * pytest-parametrized-3.7(crypto=None, transport='zeromq', coverage=False): success

```

**Review by meaksh — COMMENTED** [review]
@raulillo82 just noticed and I think we should also fix the error message at: https://github.com/saltstack/salt/blob/918ec805449ea5917c1984d0479d7eb104382c82/salt/modules/rpm_lowpkg.py#L77-L81 to in order to make it consistent on the available systems.

**Comment by MKLeb** [comment]
Hi @raulillo82, thanks for the contribution.  We will need tests for this in order to get it merged.

**Review by agraul — CHANGES_REQUESTED** [review]
As explained in https://github.com/saltstack/salt/issues/62248#issuecomment-1180360613, I think this is the wrong approach

**Comment by MKLeb** [comment]
@raulillo82 It seems there is some debate about whether this is the correct fix or if openEuler should be added to the RHEL family.  I don't know enough about openEuler, but @OrangeDog and @agraul have raised some valid points.  I think it makes sense to add it to the RHEL family if it's essentially a fork of RHEL, and as @OrangeDog said, openEuler is not officially supported by salt.

**Review by twangboy — APPROVED** [review]

**Comment by OrangeDog** [comment]
@twangboy you don't think that openEuler should just be in the RedHat family?

**Comment by garethgreenaway** [comment]
Taking a quick look at an openEuler system it does appear to use and have similar tools to Red Hat / CentOS systems but is different enough that it should be considered it's own `os_family`.

**Pull request merged**
