### PR TITLE
Fixed the periodic call to beacons

### PR DESCRIPTION
**Pull request by opdude**
This solves the bug where all beacons are no longer being checked for changes

### CODE REVIEW

**Comment by cachedout** [comment]
@opdude I'm a little confused here. Why should we run beacons if none were found during their processing? Could you explain what's happening here in a little more detail, please? Thanks.

**Comment by opdude** [comment]
I was also confused by this code. But this line I moved out of this function because it should be the original caller to the function itself.

**Comment by cachedout** [comment]
You're totally right. I think this was a mistake. Thanks for catching it!

**Comment by opdude** [comment]
No problem :)

**Pull request merged**
