### PR TITLE
Put 'syndic_log_file' and 'syndic_pidfile' vars in master config by default

### PR DESCRIPTION
**Pull request by gongled**

### CODE REVIEW

**Comment by cachedout** [comment]
What's the reasoning here? Syndics are special types of minions. It's not clear to me why these should be moved to the master config block.

**Comment by gongled** [comment]
Because of https://github.com/saltstack/salt/blob/develop/conf/master#L647, for example.

**Comment by cachedout** [comment]
@gongled Gotcha. Could you please take a look at the failing test?

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Added a test fixup in #29338 which includes these commits. When that is merged, this will be closed.

**Pull request merged**
