### PR TITLE
Improve macOS homebrew support for cask packages

### PR DESCRIPTION
**Pull request by cdalvaro**
### What does this PR do?

When listing Homebrew packages, cask packages do not have the right namespace when they are from a tap different from the default one.

This PR fixes this issue recovering the right namespace for each cask package.

### Previous Behavior

```sh
local:
----------
          ID: FiraCode Nerd Font
    Function: pkg.installed
        Name: homebrew/cask-fonts/font-firacode-nerd-font
      Result: False
     Comment: The following packages failed to install/update: homebrew/cask-fonts/font-firacode-nerd-font
     Started: 17:59:08.334054
    Duration: 14324.087 ms
     Changes:
```

### New Behavior

```sh
local:
----------
          ID: FiraCode Nerd Font
    Function: pkg.installed
        Name: homebrew/cask-fonts/font-firacode-nerd-font
      Result: True
     Comment: All specified packages are already installed
     Started: 18:56:36.057920
    Duration: 48438.613 ms
     Changes:
```

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by cdalvaro** [comment]
This PR breaks backward compatibility in terms that all salt formulas that install *brew-cask* packages with the namespace `caskroom/cask` won’t be verified properly although the installation has been performed successfully.

Those formulas must be changed from `caskroom/cask/foo` to `homebrew/cask/foo` in order to be verified again.

I tried sometime ago to get the same behaviour for *brew-cask* as with `brew info --json=v1 --installed`.
The request was intended to return the whole namespace for a *brew-cask* package, but my PR https://github.com/Homebrew/homebrew-cask/issues/56837 was discarded.

So I have used a second approach to get the correct namespace for each package.

As mention in the [official documentation](https://docs.brew.sh/Taps), you can make your custom @Homebrew tap by creating a GitHub repository that begins by `homebrew-` so your tap would be something like `username/homebrew-something`.

This behaviour also applies to official taps, so this is the reason why I have change the old namespace (`caskroom/cask`) to the new one (`homebrew/cask`).

**Comment by cdalvaro** [comment]
This PR is ready for review 🔍

**Comment by Ch3LL** [comment]
It concerns me that we are making a backwards compatible change here. Normally if there is a backwards compatible change we have to follow the deprecating code docs here: https://docs.saltstack.com/en/latest/topics/development/deprecations.html and only deprecate it in two releases in the future.

Is there a way we can allow both recipes going forward?

also @weswhet can you review here as well?

**Comment by weswhet** [comment]
I’ll have a look when I get in the office. Thanks for the ping.

**Comment by cdalvaro** [comment]
> It concerns me that we are making a backwards compatible change here. Normally if there is a backwards compatible change we have to follow the deprecating code docs here: https://docs.saltstack.com/en/latest/topics/development/deprecations.html and only deprecate it in two releases in the future.
> 
> Is there a way we can allow both recipes going forward?
> 
> also @weswhet can you review here as well?

Thank you for your response @Ch3LL 

One workaround to maintain backward compatibility could be to check in methods `install`, `remove` and `upgrade` if the given package (or packages) begins with `caskroom/cask`, and in that case, replace it with `homebrew/cask`.

If this change looks good to you I can make it. 😀

**Comment by Ch3LL** [comment]
would like to get @weswhet 's input on that approach as he is more familiar with these modules

**Comment by Ch3LL** [comment]
Also forgot to mention. We are very close to tagging v2019.2.1 and only merging in test fixes and pre-defined PRs. Are you okay moving this to the 2019.2 branch?

**Comment by cdalvaro** [comment]
> Also forgot to mention. We are very close to tagging v2019.2.1 and only merging in test fixes and pre-defined PRs. Are you okay moving this to the 2019.2 branch?

No problem!

Is this something that depends on me?

**Comment by Ch3LL** [comment]
It would be easier if you do it. You can try to change the branch in Github but there is likely to be some conflicts. Its probably easiest to just close here and re-submit against the 2019.2 branch. If you can't do it i can though.

**Comment by cdalvaro** [comment]
> It would be easier if you do it. You can try to change the branch in Github but there is likely to be some conflicts. Its probably easiest to just close here and re-submit against the 2019.2 branch. If you can't do it i can though.

No problem! I'll do the change tomorrow!

**Comment by cdalvaro** [comment]
I have created PR #54216 as requested by @Ch3LL to merge my changes into branch 2019.2

I have added backward compatibility for old recipes and added the deprecation warning too.

I close this PR now in favour of #54216

**Pull request closed without merging**
