### PR TITLE
Improvement of the recursion of the permissions

### PR DESCRIPTION
**Pull request by BnGx**
### What does this PR do?
The changes that I propose allow within the _directory_ function a more accurate management of the _user_, _group_ and _mode_ options when applied recursively.

### Previous Behavior
If permissions are managed at subpath level, by _directory_ or _managed_ function, the application of the permissions in recursive mode by parents _directory_ function is applied repeatedly with each application of the states.

### New Behavior
When a _directory_ function applies the options marked recursively, they are overwritten by other _directory_ functions if they correspond to a managed subpath. To do this, each directory function auto-requires the _directory_ and _managed_ functions with managed subpath.

In this way **no unnecessary changes will be applied and displayed** during the application of a state even if multiple functions interact on the same directory or file.

### Test
It is possible to test what has been said with the following states:
`cat test.sls`

```
/tmp/user:
  file.directory:
    - user: root
    - group: root
    - mode: '0755'
    - recurse:
        - user
        - group

/tmp/user/dir:
  file.directory:
    - user: named
    - group: named
    - mode: '0750'
    - recurse:
        - user
        - group
        - mode
        - ignore_dirs

/tmp/user/dir/subdir:
  file.directory

/tmp/user/dir/subfile1:
  file.managed:
    - user: cron
    - group: cron
    - mode: '600'

/tmp/user/dir/subfile2:
  file.managed

/tmp/user/file:
  file.managed:
    - group: mail
    - mode: '0600'
```

### CODE REVIEW

**Comment by bryceml** [comment]
re-run all full

**Comment by BnGx** [comment]
How can I do it?

**Comment by mchugh19** [comment]
> How can I do it?

There are a few jenkins trigger words. So you can use the same one as above, or `re-run pr-centos7-py3` to trigger just the ci/py3/centos7 job (the name you use should match the job name in Jenkins).

Also, looks like states/file.py need to be blackened. From the pre-commit job...
```
20:49:21  black....................................................................Failed
20:49:21  [2m- hook id: b
20:49:21  [2m- files were modified by this 
20:49:21  
20:49:21  reformatted salt/states/file.py
```

**Comment by Akm0d** [comment]
@BnGx Thank you for the PR! This can be merged once a test is written with the example states you gave

**Review by twangboy — CHANGES_REQUESTED** [review]
We'll need some tests for this

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
