### PR TITLE
Remove _locals from the final exec call in pyobjects

### LINKED ISSUE #21796: pyobjects behaving weirdly when calling python stdlib package
I am using pyobjects, silly me...
The following code doesn't work: 
```
    password = ''.join(random.SystemRandom().choice(
        string.ascii_letters + string.digits) for _ in range(20))
```
it fails with this message:
```
    Data failed to compile:
----------
    Rendering SLS failed, render error: global name 'random' is not defined
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2425, in render_state
    sls, rendered_sls=mods
  File "/usr/lib/python2.7/dist-packages/salt/template.py", line 84, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/pyobjects.py", line 450, in render
    exec final_template in _globals, _locals
  File "<string>", line 12, in <module>
  File "<string>", line 12, in <genexpr>
NameError: global name 'random' is not defined
```
However, it works fine when I separate the line.
```
    charlist = [random.SystemRandom().choice(
        string.ascii_letters + string.digits) for _ in range(20)]
    password = ''.join(charlist)
```

Of course, I have `import random, string` at the top of the file

Does this really hand-parse python up to an arbitrary level of complexity? If yes, please document this, so people don't expect too much.

### PR DESCRIPTION
**Pull request by borgstrom**
This PR fixes #21796

From the Python docs on the `exec` statement:

> Remember that at module level, globals and locals are the same dictionary. If two separate objects are given as globals and locals, the code will be executed as if it were embedded in a class definition.

We were providing a specific object for locals and in the specific case reported in #21796 this caused a very strange name error when used in a specific way.  By removing the explicit locals dictionary and just having the globals dictionary be shared fixes the issue, and we weren't using the specific locals anyway.

### CODE REVIEW

**Comment by jfindlay** [comment]
@borgstrom, awesome, thanks.  There are a couple of [lint errors](https://jenkins.saltstack.com/job/salt-pr-lint-n/3321/violations/file/tests/unit/pyobjects_test.py/).  Also, feel free to submit fixes directly to the oldest release branch that has the bug, as these branches are regularly merged forward.  See, http://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

**Comment by borgstrom** [comment]
@jfindlay good point.  This should definitely be fixed in the 2014.7 branch, but it's diverged quite a bit from where develop/2015.2 is.  What's the best course here?  Should I submit two pulls?  It's not entirely clear from the docs.

**Comment by jfindlay** [comment]
@borgstrom, the best thing would be if you can submit a separate pull for 2014.7, thanks.

**Comment by borgstrom** [comment]
Closing this pull.

See #21872 for the 2014.7 pull, and see #21873 for the 2015.2.

**Pull request closed without merging**
