### PR TITLE
Addition of -sa flag to allow for revision numbers other than -0 or -1

### PR DESCRIPTION
**Pull request by dmurphy18**
### What does this PR do?
Allows for building Debian and Ubuntu packages with revision numbers great than -0 or -1

### What issues does this PR fix or reference?
Allows for building Python 3 packages for Debian and Ubuntu for Oxygen

### Previous Behavior
original tarball would not be included in source for package, for example:
The following packages were not built: timelib_0.2.4.orig.tar.gz where the revision is '-2'

### New Behavior
Original tarball is now included in source packages for Debian and Ubuntu

### Tests written?
No, used to build successfully

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by dmurphy18** [comment]
Want to get this in for the next point release 2017.7.5 to ensure building packages runs smoothly

**Comment by garethgreenaway** [comment]
re-run all

**Comment by rallytime** [comment]
re-run all

**Comment by rallytime** [comment]
re-run all

**Comment by garethgreenaway** [comment]
re-run all

**Comment by garethgreenaway** [comment]
re-run all

**Comment by rallytime** [comment]
re-run all

**Comment by rallytime** [comment]
re-run py

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
