### PR TITLE
Add or remove path from salt-minon or salt-call enviroment.  Issue 17062

### PR DESCRIPTION
**Pull request by deuscapturus**
https://github.com/saltstack/salt/issues/17062

### CODE REVIEW

**Comment by jfindlay** [comment]
@deuscapturus, there's some lint errors.

**Comment by deuscapturus** [comment]
I don't know how to make the lint check happy.  It's asking for indentation on a line that should not have any indentation.

**Comment by rallytime** [comment]
@deuscapturus Looks like all you need is another line above where you define __virtual__. But I can grab that really quickly for ya. :)

**Comment by jfindlay** [comment]
@deuscapturus, yeah, sorry about the confusing lint errors.  It's easy for me to forget that not everyone who contributes to salt is near as familiar with jenkins and pylint as I am.  I am interested if you have feedback about our contrib documentation as to whether it can be improved or clarified, etc.  Thanks.

**Pull request merged**
