### PR TITLE
Backport #20457 to 2014.7

### PR DESCRIPTION
**Pull request by rallytime**
Backport #20457 to 2014.7

### CODE REVIEW

**Comment by rallytime** [comment]
This should help clear up the SREQ tests that are still flaky on older branches. There were some merge conflicts, and I think I resolved them appropriately, but let's make sure the tests pass with flying (green) colors in case I missed something.

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
On the previous run, `integration.client.runner.RunnerModuleTest.test_cmd_sync_w_arg` failed on CentOS 7 - let's see if that's the case again or if that was a flaky fluke. (Everything else was green.)

**Comment by jfindlay** [comment]
Actually, [this test failed](https://jenkins.saltstack.com/job/salt-pr-rs-cent7-n/1594/testReport/junit/integration.client.runner/RunnerModuleTest/test_cmd_sync/).  I guess I shouldn't have merged this?  Was this backport supposed to fix such test failures?

**Comment by jfindlay** [comment]
Or fix the SREQ test failures rather.

**Comment by rallytime** [comment]
I think it's ok. I just checked the 2014.7 branch on Jenkins and everything is blue. I'm not sure why that test was failing here... :-\

**Pull request merged**
