### PR TITLE
Adds the possibility to also use downloadonly in kwargs

### LINKED ISSUE #54790: downloadonly vs download_only
### Description of Issue

[This merged PR](https://github.com/saltstack/salt/pull/41210) clashes with the downloadonly parameter we already had for the [yum](https://github.com/Da-Juan/salt/blob/ed8dde469a34b00532b0e0eafa57d1de6fb00aa4/salt/modules/yumpkg.py#L1113) and [zypper](https://github.com/Da-Juan/salt/blob/ed8dde469a34b00532b0e0eafa57d1de6fb00aa4/salt/modules/zypper.py#L898) module. The parameter should be `downloadonly` and not `download_only`.

### Versions Report
Salt >= 2017.7.0.

### PR DESCRIPTION
**Pull request by brejoc**
### What does this PR do?

The download_only parameter in the apt module is not in line with the yum and zypper modules. Both of them use downloadonly without the underline.

With this change apt now additionally supports the downloadonly parameter.

### What issues does this PR fix or reference?

Fixes #54790

### Previous Behavior
The apt module had to be used with `download_only`.

### New Behavior
The apt module can now also be used with `downloadonly`.

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by brejoc** [comment]
I'll add a tests once I know that we'd like to take this route.

**Review by cmcmarrow — APPROVED** [review]

**Comment by cmcmarrow** [comment]
Thanks you for the test and keeping backwards compatibility in mind.

**Comment by dwoz** [comment]
@brejoc The `unit.modules.test_aptpkg.AptPkgTestCase.test_upgrade_downloadonly` test is failing.

**Comment by brejoc** [comment]
This is really strange. Locally the tests are passing and I can see the download-only parameter in the args list. But when run here, the args are just empty:

```
=============================================================

()
{}
=============================================================

()
{}
```

**Comment by brejoc** [comment]
@dwoz looks like this is good to go now. Would it make sense to rebase to master?

**Comment by brejoc** [comment]
@saltstack/core-pr-reviewers Would it make more sense to close this and open an other PR with these changes against master?

**Comment by brejoc** [comment]
@dwoz Since this was closed, I opened the same for master: #55448

**Pull request closed without merging**
