### PR TITLE
Fixes #51797 - '<' not supported between instances of 'dict' and 'dict'

### LINKED ISSUE #51797: netbox.openconfig_interfaces fails: '<' not supported between instances of 'dict' and 'dict'
### Description of Issue/Question
In my setup netbox.get_interfaces works. Now I tried netbox.openconfig_interfaces. This fails with:
Passed invalid arguments to netbox.openconfig_interfaces: '<' not supported between instances of 'dict' and 'dict'

### Setup
Plain setup of salt-2019.2.0-rc2, netbox with python 3.6

### Steps to Reproduce Issue
salt -l debug nms3 netbox.openconfig_interfaces device_name='switch03'
(...)
[DEBUG   ] return event: {'nms3': {'ret': "Passed invalid arguments to netbox.openconfig_interfaces: '<' not supported between instances of 'dict' and 'dict' .. versionadded:: 2019.2.0\n\n    Return a dictionary structured as standardised in the\n    `openconfig-interfaces <http://ops.openconfig.net/branches/master/openconfig-interfaces.html>`_\n    YANG model, containing physical and configuration data available in Netbox,\n    e.g., IP addresses, MTU, enabled / disabled, etc.\n\n    device_name: ``None``\n        The name of the device to query the interface data for. If not provided,\n        will use the Minion ID.\n\n    CLI Example:\n\n    .. code-block:: bash\n\n        salt '*' netbox.openconfig_interfaces\n        salt '*' netbox.openconfig_interfaces device_name=cr1.thn.lon\n    ", 'out': 'nested', 'retcode': 1, 'jid': '20190225154145768780'}}
[DEBUG   ] LazyLoaded nested.output
nms3:
    Passed invalid arguments to netbox.openconfig_interfaces: '<' not supported between instances of 'dict' and 'dict'
(...)

### Versions Report
Salt Version:
           Salt: 2019.2.0rc2
 
Dependency Versions:
           cffi: 1.12.1
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.7.2
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.7 (default, Oct 22 2018, 11:32:17)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-45-generic
         system: Linux
        version: Ubuntu 18.04 bionic

### PR DESCRIPTION
**Pull request by zachmoody**
### What does this PR do?
Fixes issuing in py3 of sorting dicts by returning results from
`filter_()` unsorted.

### What issues does this PR fix or reference?
#51797 

### Previous Behavior
Sorted return from `filter_()`.

### New Behavior
Does not sort return from `filter_()`.

### Tests written?

No

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by misch42** [comment]
Cool. Works for me.

**Comment by dwoz** [comment]
@zachmoody 
I'm not sure why this has so many conflicting files. Can you look into what happened?

**Comment by zachmoody** [comment]
@dwoz I think because I'd originally opened the PR against `develop` and now it wants to base it on 2019.2.1, but I'm not sure. I didn't have much luck sorting it out on this PR so I opened a new one #52631 which is based on the 2019.2.1 branch.

**Comment by maznu** [comment]
Would be great in 2019 and 3000 trees alike, because this is still a bug.

**Pull request closed without merging**
