### PR TITLE
[Magnesium RC] Fix bug introduced in #58238 feature flag implementation

### PR DESCRIPTION
**Pull request by mlasevich**
### What does this PR do?
Fix bug introduced in https://github.com/saltstack/salt/commit/9380b56692ca04a043731fcaeb0ca049a7251e9b in  #58238 

### What issues does this PR fix or reference?
Fixes bug in #58238 

### Previous Behavior
A typo in commit dropped a return statement from a function

### New Behavior
add return statement 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by max-arnold** [comment]
@krionbsd Could you please tag this PR with the `Magnesium` milestone? The referenced PR was shipped in the Magnesium RC and this follow-up PR should fix the issue found while testing the RC.

**Comment by max-arnold** [comment]
The docs still contain feature flag name that differs from the actual implementation. And something needs to be improved in the unit-test so it actually checks the desired behaviour.

**Comment by myii** [comment]
@mlasevich It would be useful to fix the typos from #58238 here as well:

* https://github.com/saltstack/salt/pull/58238#pullrequestreview-511145310

**Comment by mlasevich** [comment]
> @mlasevich It would be useful to fix the typos from #58238 here as well:
> 
> * [#58238 (review)](https://github.com/saltstack/salt/pull/58238#pullrequestreview-511145310)

I am a bit hesitant to update those as they were not added by me, but typos are typos - so might as we update :-)

**Review by dwoz — DISMISSED** [review]

**Comment by dwoz** [comment]
@mlasevich  Please address @max-arnold's comment about adding a test to actually verify this functionality.

**Comment by mlasevich** [comment]
> @mlasevich Please address @max-arnold's comment about adding a test to actually verify this functionality.

Yeah, I looked at it yesterday - the only thing that was not covered was the feature flag wrapper, which is why the unit tests passed despite the bug. I wrote a unit test for feature flag stuff, but have not been able to test it as for whatever reason, nox does not work with this project for me. I'll throw together a VM this morning and get it tested and committed.

**Comment by myii** [comment]
After @max-arnold suggested the idea, I've run tests across ~85 formulas, including this fix and using the feature flag in the minion configuration, for both `master` and `tiamat` pre-salted images:

* https://saltstack-formulas.zulipchat.com/#narrow/stream/239693-CI/topic/master.2F2020-W43a
  - (Currently requires logging in such as using the GitHub integration).

Generally, all is working well.  Having a problem with the `tiamat` jobs but that appears unrelated to this PR:

* https://travis-ci.org/github/myii/nut-formula/jobs/737010324#L1115-L1124

Testing locally, the issue is the configuration passed through to `kitchen-salt`:

```yaml
provisioner:
  name: salt_solo
  ...
  salt_minion_extra_config:
    features:
      enable_slsvars_fixes: true
```

**Comment by mlasevich** [comment]
> After @max-arnold suggested the idea, I've run tests across ~85 formulas, including this fix and using the feature flag in the minion configuration, for both `master` and `tiamat` pre-salted images:

I just wanted to start with unit tests. If unit tests cover functionality AND flag selection (which they do in this case now), this sort of a thing would not be a problem :-) There is some value in higher level tests, but those are more to catch deficiencies in unit tests :-)

**Comment by mlasevich** [comment]
> @mlasevich Please address @max-arnold's comment about adding a test to actually verify this functionality.

Added unit tests to cover flag selection.

**Review by dwoz — APPROVED** [review]

**Review by s0undt3ch — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Pull request merged**
