### PR TITLE
SmartOS Esky: fix build version identification (backport of saltstack/salt#19936)

### PR DESCRIPTION
**Pull request by nshalman**
"bdist" doesn't do the right thing in the absence of
version files produced by "sdist".
Run "sdist" then extract out the contents of the tarball
into place

### CODE REVIEW

**Comment by rallytime** [comment]
@nshalman Thanks for submitting these fixes! Are all of these (this PR, #19938 against 2015.2, and #19936 against develop) the same change? We've updated our branching strategy starting in the 2014.7 where we merge any bugfixes made in earlier branches will be merged forward all the way through to develop. So in this case, this pull request, when merged into 2014.7 will be merged forward into 2015.2 and then again into develop, so the fix will be in all three branches. This streamlines the process greatly, so we don't have to remember to submit fixes against all of the branches. 

If these fixes are different, then pay no mind here, but I thought I would mention it, just in case. If you'd like to see more about this topic, check out the docs here: http://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch

**Comment by nshalman** [comment]
@rallytime They are indeed all the exact same change. I am glad to hear about the new merging procedures in place and will make all future pull requests against the oldest affected branch accordingly.

**Comment by nshalman** [comment]
See #19936 for additional comments relevant to this PR.

**Comment by rallytime** [comment]
Awesome! Thanks @nshalman!

**Pull request merged**
