### PR TITLE
handle exceptions when received data is not in good shape

### PR DESCRIPTION
**Pull request by hvnsweeting**
I got this exception on one of my minion, it received data == `""`.

```
[ERROR   ] Data is
local:
    Data failed to compile:
----------
    Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2874, in call_highstate
    top = self.get_top()
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2376, in get_top
    tops = self.get_tops()
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2249, in get_tops
    saltenv
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 147, in cache_file
    return self.get_url(path, '', True, saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 522, in get_url
    return self.get_file(url, dest, makedirs, saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 993, in get_file
    if not data['data']:
TypeError: string indices must be integers, not str
```

### CODE REVIEW

**Comment by jfindlay** [comment]
@hvnsweeting, thanks for the fix.  2014.7 is no longer supported.  @basepi, will you make sure this gets into 2015.5?  Thanks.

**Comment by hvnsweeting** [comment]
@jfindlay then how can I know when a branch is deprecated?  Because this is not the first time I done a fix against a deprecated branch.
Thanks.

**Comment by jfindlay** [comment]
@hvnsweeting, that's a good question.  Probably the best way is to see which branch the latest release comes from.

**Comment by hvnsweeting** [comment]
that's not really the reliable way to use, because I pushed (and got merged) a lot of 2014.7 fixes after 2015.5.0 is released.

**Comment by rallytime** [comment]
Thanks for the questions @hvnsweeting. We will continue to do merge-forwards from this branch so you can certainly submit fixes to it, and we will continue to review and merge them. However, we won't be officially releasing from this branch again, which means we're pushing people to submit their fixes against the 2015.5 branch. 

Our typical workflow is that once a new release branch is officially release (2015.5.0 in this case) the older branch becomes "deprecated". We'll still accept fixes, but the newer branch then become the more active one, at that point.

**Comment by hvnsweeting** [comment]
@rallytime okay I got it, thanks.

will this fix https://github.com/saltstack/salt/issues/23186 and https://github.com/saltstack/salt/issues/21480  ?

**Pull request merged**
