### PR TITLE
[master] fix: slack bolt engine name is slack_bolt

### PR DESCRIPTION
**Pull request by raddessi**
### What issues does this PR fix or reference?
Fixes: The new slack bolt module docs appear to be referencing the old engine name.

### Previous Behavior
The bolt engine is not actually started.

### New Behavior
The bolt engine is started.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by whytewolf — DISMISSED** [review]

**Comment by whytewolf** [comment]
@raddessi I know the pre-commit issues are not you directly. Do you think you can make the updates being requested by black? which are changing from .format to f strings?

**Review by s0undt3ch — DISMISSED** [review]

**Comment by s0undt3ch** [comment]
> @raddessi I know the pre-commit issues are not you directly. Do you think you can make the updates being requested by black? which are changing from .format to f strings?

Or submitting against `3006.x` instead of `master`

**Comment by raddessi** [comment]
can do!

**Comment by raddessi** [comment]
Actually for my own reference can you clarify how this change would make it t .master if I were to only commit to the 3006.x branch? I thought these were essentially tagged release branches according to SEP14 so they would not get merged back in to master and only receive hotfixes. I probably misunderstand something

**Comment by s0undt3ch** [comment]
> Actually for my own reference can you clarify how this change would make it to master if I were to only commit to the 3006.x branch? I thought these were essentially tagged release branches according to SEP14 so they would not get merged back in to master and only receive hotfixes. I probably misunderstand something

This is also a bug present in 3006.x, so, since you committed to master, we backport the fix.

If you had committed to the release branch 3006.x, that branch gets merged forward into master, so the fix would also land in master.

Features do not work like this, of course

**Review by s0undt3ch — APPROVED** [review]

**Comment by raddessi** [comment]
Ahhh I didn't realize you merged the last point release branched forward to master! I'll open up against those from now on. Thank you for the clarification

**Comment by s0undt3ch** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[](https://github.com/saltstack/salt/pull/64670)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by s0undt3ch** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[](https://github.com/saltstack/salt/pull/64670)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
