### PR TITLE
correct formatting issue with highstate output module

### PR DESCRIPTION
**Pull request by leifliddy**
### What does this PR do?
Corrects a formatting issue when ```cmd.run``` is run from an orchestration and returns multiple lines of output. This PR ensures every line of output under ```Changes``` is indented properly.

### What issues does this PR fix or reference?
#56554

### Previous Behavior

given the orchestration state

```
command_1:
  salt.function:
    - name: cmd.run
    - tgt: 'server'
    - arg:
      - ls /tmp
```
the files listed under ```Changes``` would not be indented properly
```
[root@server ~]# salt-run state.orch orch.test --out highstate
server.example.com_master:
----------
          ID: command_1
    Function: salt.function
        Name: cmd.run
      Result: True
     Comment: Function ran successfully. Function cmd.run ran on server.
     Started: 19:02:44.195687
    Duration: 413.993 ms
     Changes:   
              server:
                  file1
              file2
              file3
```

### New Behavior
```
[root@server ~]# salt-run state.orch orch.test --out highstate
server.example.com_master:
----------
          ID: command_1
    Function: salt.function
        Name: cmd.run
      Result: True
     Comment: Function ran successfully. Function cmd.run ran on server.
     Started: 19:03:19.668603
    Duration: 418.08 ms
     Changes:   
              server:
                  file1
                  file2
                  file3
```
### Tests written?
No. I've read through the ```Writing Unit Tests``` page and I'm completely lost. If we're just testing a function's logic then can't we just use the the existing ```salt/tests/unit/output/test_highstate.py``` test?

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by leifliddy** [comment]
What's the issue this PR? I don't understand what check it's failing?

**Comment by DmitryKuzmenko** [comment]
The only failure I see is `codecov` check that could be ignored.
What about `Needs Testcase` label: I'm sorry I thought I put a comment about it. Could you please modify the `tests/unit/output/test_highstate.py` to have a multiline data in `changes` filed to check the outputter formatting. It's needed at least to control regressions in the future to not lose your fix some day.

**Comment by mchugh19** [comment]
@leifliddy if you have an example of raw output (json?) which previously exhibited the broken behavior, it can be added to test_highstate.py to validate that things aren't proper before your fix, but are okay with your new code.

**Comment by leifliddy** [comment]
@mchugh19 Given the following raw output
```{'data': {'cloud.example.com_master': {'salt_|-command_1_|-cmd.run_|-function': {'name': 'cmd.run', 'changes': {'out': 'highstate', 'ret': {'cloud': 'file1\nfile2\nfile3'}}, 'comment': 'Function ran successfully. Function cmd.run ran on cloud.', 'result': True, '__jid__': '20200411151536814628', '__sls__': 'orch.test', '__run_num__': 0, 'start_time': '17:15:36.702239', 'duration': 419.665, '__id__': 'command_1'}}}, 'outputter': 'highstate', 'retcode': 0}```

The original highstate.py code would take the output  ```file1\nfile2\nfile3```  
ie 
```data = 'file1\nfile2\nfile3'```

It would then append ```data``` to the hstrs list as such
```hstrs.append(("{0}    {1}{2[ENDC]}".format(hcolor, data, colors)))```

which would result in ```file1``` being indented by four spaces (spaces found between {0} and {1}), 
but, not ```file2```, or ```file3```

My change does exactly what the ```nested``` output module does. Which is to check for '''Number/int''' data types first, and then check for ```six.string_types``` data, and then loop through it
```
salt/salt/output/nested.py
...
        elif isinstance(ret, six.string_types):
            first_line = True
            for line in ret.splitlines():
```

I'll take a look at ```test_highstate.py``` later this weekend.

**Comment by leifliddy** [comment]
I'm trying to replicate the output of the ```JsonTestCase```  class in ```test_highstate.py```
```
           "data": {
                "master": {
                    "salt_|-call_sleep_state_|-call_sleep_state_|-state": {
                        "__id__": "call_sleep_state",
                        "__jid__": "20170418153529810135",
                        "__run_num__": 0,
                        "__sls__": "orch.simple",
                        "changes": {
                            "out": "highstate",
                            "ret": {
                                "minion": {
                                    "module_|-simple-ping_|-test.ping_|-run": {
                                        "__id__": "simple-ping",
                                        "__run_num__": 0,
                                        "__sls__": "simple-ping",
                                        "changes": {"ret": True},
                                        "comment": "Module function test.ping executed",
                                        "duration": 56.179,
                                        "name": "test.ping",
                                        "result": True,
                                        "start_time": "15:35:31.282099",
                                    }
```

The output shows that it was called from an orchestration state: ```"__sls__": "orch.simple"```
The the output shows ``` "comment": "Module function test.ping executed"```

Maybe, this is just due to my general lack of knowledge of saltstack, but how do you run the ```test.ping``` module from an orchestration state?

I know you can run salt function from an orch state:
```
command_1:
  salt.function:
    - name: test.ping
    - tgt: 'cloud'
```

But, that would result in different output. If you specified more then one minion, ( I believe) the results should be collated together. 
ie
```{'out': 'highstate', 'ret': {'minion': True, 'sub_minion': True}}```

The ```test_highstate.py``` shows that will ran on two separate minions, yet the results weren't collated together. 
 "comment": "States ran successfully. Updating sub_minion, minion.",

I'm guessing that the examples listed in the test modules should be able to be replicated using salt. 
As I said, it's probably due to my lack of knowledge. But, I'd like to be able to replicate this output so I can just append my changes to it more easily.

**Comment by leifliddy** [comment]
Ok, I see that the example in ```test_highstate``` was run as run by ```salt.state```
```"salt_|-call_sleep_state_|-call_sleep_state_|-state": {```
```"__sls__": "simple-ping",```

But, ```test.ping``` doesn't exist as a ```state_function```
```
[root@master ~]# salt master sys.list_state_functions test.ping
master:
```

How would you run ```test.ping``` from a state file?

**Comment by leifliddy** [comment]
@mchugh19 test has been added to ```test_highstate.py ```

**Comment by mchugh19** [comment]
@DmitryKuzmenko test added

**Comment by DmitryKuzmenko** [comment]
@leifliddy The pre-commit failure is related. Could you please update your branch, install the pre-commit hook with `pre-commit install` and run pre-commit to blaken your code `pre-commit run tests/unit/output/test_highstate.py`?
Windows failures are unrelated.

**Comment by leifliddy** [comment]
I've never used this tool before and am a bit lost.
```
[leif.liddy@black salt]$ pre-commit install
pre-commit installed at .git/hooks/pre-commit

[leif.liddy@black salt]$ pre-commit run tests/unit/output/test_highstate.py 
[INFO] Initializing environment for https://github.com/saltstack/pip-tools-compile-impersonate.
[INFO] Initializing environment for https://github.com/timothycrosley/isort.
[INFO] Initializing environment for https://github.com/timothycrosley/isort:toml.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/saltstack/salt-nox-pre-commit.
No hook with id `tests/unit/output/test_highstate.py` in stage `commit`
```

**Comment by leifliddy** [comment]
So, I reverted the commit, and re-added the ```test_highstate.py``` to staging. 
When I try to commit the change, this happens. 

```
Lint Py3.7 Requirements..............................(no files to check)Skipped
isort....................................................................Passed
black....................................................................Passed
Lint Salt............................................(no files to check)Skipped
Lint Tests...............................................................Failed
- hook id: nox-py2
- exit code: 1

Running session lint-tests-pre-commit
pip install --progress-bar=off distro
distro -j
Distro information:
{'codename': '',
 'id': 'fedora',
 'like': '',
 'version': '31',
 'version_parts': {'build_number': '', 'major': '31', 'minor': ''}}
Processing requirements/static/linux.in
pip install --progress-bar=off -r requirements/base.txt --constraint requirements/static/py3.7/linux.txt --constraint requirements/static/py3.7/linux-crypto.txt
pip install --progress-bar=off -r requirements/zeromq.txt --constraint requirements/static/py3.7/linux.txt --constraint requirements/static/py3.7/linux-crypto.txt
pip install --progress-bar=off -r requirements/pytest.txt --constraint requirements/static/py3.7/linux.txt --constraint requirements/static/py3.7/linux-crypto.txt
pip install --progress-bar=off -r requirements/static/linux.in --constraint requirements/static/py3.7/linux.txt --constraint requirements/static/py3.7/linux-crypto.txt
pip install --progress-bar=off -r requirements/static/lint.in --constraint requirements/static/py3.7/lint.txt
pylint --rcfile=.pylintrc --disable=I tests/unit/output/test_highstate.py
************* Module tests.unit.output.test_highstate
tests/unit/output/test_highstate.py:1: [E0599(file-perms), ] Module file has the wrong file permissions(expected 0o644): 0o664
/home/leif.liddy/.cache/pre-commit/reposibtw3jg/py_env-python3/lib/python3.7/site-packages/isort/settings.py:295: UserWarning: Found /home/leif.liddy/salt/pyproject.toml with [tool.isort] section, but toml package is not installed. To configure isort with /home/leif.liddy/salt/pyproject.toml, install with 'isort[pyproject]'.
  file_path))

-----------------------------------
Your code has been rated at 8.98/10

Command pylint --rcfile=.pylintrc --disable=I tests/unit/output/test_highstate.py failed with exit code 2
Session lint-tests-pre-commit failed.
```

**Comment by leifliddy** [comment]
It's failing this check:
```
[leif.liddy@black salt]$ pylint --rcfile=.pylintrc --disable=I tests/unit/output/test_highstate.py
************* Module tests.unit.output.test_highstate
tests/unit/output/test_highstate.py:1: [E0599(file-perms), ] Module file has the wrong file permissions(expected 0o644): 0o664

-----------------------------------
Your code has been rated at 8.98/10
```

**Comment by leifliddy** [comment]
@DmitryKuzmenko Can you please let me know why these commit checks are failing?

**Comment by leifliddy** [comment]
@DmitryKuzmenko @waynew Could someone please check this out today and let me know if everything's good?

**Review by DmitryKuzmenko — APPROVED** [review]

**Comment by DmitryKuzmenko** [comment]
Looks good @leifliddy ! Windows test failure looks unrelated. I've re-started the ci build.

**Comment by leifliddy** [comment]
@DmitryKuzmenko Thanks. It looks like ci isn't building, should I restart it?

**Comment by leifliddy** [comment]
@DmitryKuzmenko All checks have passed!

**Pull request merged**
