### PR TITLE
git.latest: Add a hint for possible rev changes resulting in non-fast-forward failures

### PR DESCRIPTION
**Pull request by terminalmage**
See https://github.com/saltstack/salt/issues/34790#issuecomment-238857462

This should help people understand the new behavior of the branch
parameter, when they run into non-fast-forward failures in git.latest
states when the remote rev differs from the name of the local branch.

### CODE REVIEW

**Comment by terminalmage** [comment]
Adding another case to this hint, hold off on merging.

**Comment by terminalmage** [comment]
OK, I added another hint. I'd like to test this before merging and potentially write a couple integration tests, so let's still hold off on merging.

**Comment by cachedout** [comment]
@terminalmage Please let me know when this is ready to go. Thanks, sir.

**Comment by terminalmage** [comment]
@cachedout I'll need to wait to finish this until Carbon is branched later this week, at least. Too much to do before then.

**Comment by terminalmage** [comment]
OK, I rebased this because of the time passed since I initially submitted, and added two integration tests to cover the two hints I added here. Pending successful tests, this is good to merge.

**Pull request merged**
