### PR TITLE
[3006.x] Add latest golden images, drop Fedora 36

### PR DESCRIPTION
**Pull request by ScriptAutomate**
- Updates CI/CD to latest golden images
- Drops Fedora 36
- Shows the following images as available, but will introduce new workflows in separate PRs
  - Debian 12 (workflows will be added later into `master` only, as will be in 3007)
  - Photon OS 5 (workflows will be added later into `master` only, as will be in 3007)
  - Photon OS 4 ARM (workflows will be added later into `3006.x`)

### CODE REVIEW

**Review by s0undt3ch — DISMISSED** [review]

**Comment by ScriptAutomate** [comment]
@s0undt3ch Looks like tests pass, for the most part, except for some caching issue on the Windows systems?

Example:

> Error: Failed to restore cache entry. Exiting as fail-on-cache-miss is set. Input key: SEED-3|3.10.11|testrun-deps|windows-2016|test-pkgs-onedir|ac7cf8beda8b62f86e1ce579a9439a7fab8bbaa607c2116c9b17f0ae9d563291

Is this known flaky behavior?

**Comment by ScriptAutomate** [comment]
@s0undt3ch
Additional problems:

https://github.com/saltstack/salt/actions/runs/5556636318/jobs/10218180917?pr=64635

```
# Several pip-related problems?
            FAILED tests/unit/states/test_pip_state.py::PipStateInstallationErrorTest::test_importable_installation_error - AssertionError: Failed to get InstallationError exception under at least one pip version:
           pip<19.0: Command failed return code check
```

https://github.com/saltstack/salt/actions/runs/5556636318/jobs/10218180917?pr=64635

```
# Chocolatey related problems?
# The traceback that follows looks like more is happening rather than just the choco command failure, but cannot tell
           _______________________ ChocolateyModuleTest.test_list_ _______________________
           
           self = <tests.integration.modules.test_chocolatey.ChocolateyModuleTest testMethod=test_list_>
           
               def test_list_(self):
                   ret = self.run_function("chocolatey.list", narrow="adobereader", exact=True)
           >       self.assertTrue("adobereader" in ret)
           E       AssertionError: False is not true
           
           ret        = {}
           self       = <tests.integration.modules.test_chocolatey.ChocolateyModuleTest testMethod=test_list_>
           
           tests\integration\modules\test_chocolatey.py:29: AssertionError
```

The choco one may be related to:
- https://github.com/saltstack/salt-jenkins/pull/1814
- https://github.com/saltstack/salt/issues/64427

There also were permissions errors in attempting to connect to Windows instances, but the logs I'm unable to retrieve now that I'm re-running on one of the jobs that had cache problems.

Are these issues also considered part of flaky tests?

**Comment by ScriptAutomate** [comment]
Looks like it may be related to needing Chocolatey v2 support, due to the test attempting a search for adobereader (which isn't installed, but should appear in a choco search):
- https://github.com/saltstack/salt/pull/64673

**Review by Ch3LL — APPROVED** [review]

**Review by Ch3LL — DISMISSED** [review]

**Comment by Ch3LL** [comment]
Looks like there are SSH errors on Windows.

**Comment by ScriptAutomate** [comment]
Confirmed that the SSH connections are not just flaky issues, but that the 2016 AMI isn't being properly setup with the SSH public key. Going to keep this PR in draft for now.

**Pull request closed without merging**
