### PR TITLE
Addition of ACME / Let's Encrypt client module & state

### LINKED ISSUE #24818: Support for ACME/letsencrypt.org
I think an important factor for the adoption of [ACME](https://github.com/letsencrypt/acme-spec) which will be used by the [Let's Encrypt](https://letsencrypt.org/) initiative is the support for ACME in config management tools as otherwise people need to rely on the tools provided by "Let's Encrypt" which will lead to conflicts between the tools and config management processes.

So I'd like to suggest to add execution and state modules for the ACME protocol.
The modules could possibly transparently extend the existing [x509](https://docs.saltstack.com/en/develop/ref/states/all/salt.states.x509.html) modules.

### PR DESCRIPTION
**Pull request by The-Loeki**
Incidentally fixes #24818 

I've created a wrapper around `letsencrypt-auto` to interface with ACME CA's (Let's Encrypt).
The reason I did that is because the `acme` pip package/API interface seems in no condition yet to build upon. Once it is and the protocol/code/documentation stabilize, we might overhaul this to directly talk ACME and handle everything from within Salt.

I know Boron is officially in feature freeze already, but a lot of people including me would love to include this one! Also it's a simple addition of a module, nothing more. 

The module lightly utilize the `tls` module, but has graceful fallback if that's not available.

Tnx @martinhoefling for getting the formula started, it helped me a lot building this one.

I consider this RC; I've done some light testing overall (rolling it out into production now), and continue to commit updates as I encounter them.

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @The-Loeki 

Sweet! The only issue here is that we've feature-frozen 2016.3 and we need to have you please re-submit this against the develop branch. Once you do that, we'll happily review it and hopefully get it merged. Thanks.

**Comment by The-Loeki** [comment]
Hi @cachedout I was kinda hoping to get it in 2016.3, since it has no impact on the rest of the codebase whatsoever?

**Comment by thatch45** [comment]
@The-Loeki we spent the last few hours off and on debating about this and we want to keep to the feature freeze, it is easy enough to put these in develop and for you to distribute them in your _modules and _states directories.

**Comment by cachedout** [comment]
@The-Loeki Could you please resubmit this against develop? We do really want to get this in, albeit in the correct branch. :] Thanks very much.

**Comment by The-Loeki** [comment]
Well, that was a horrible git snafu :D 

Close this one, new PR is in #31483

**Pull request closed without merging**
