### PR TITLE
begin adding tests for the openstack cloud provider

### PR DESCRIPTION
**Pull request by gtmanfred**
### Tests written?

Yes

### CODE REVIEW

**Comment by gtmanfred** [comment]
In order to fully tests this, we need the glance and nova running on the instance, but this should make sure that our stuff continues to run correctly until then.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Pull request merged**
