### PR TITLE
fix #54521; failhard not being respected in batch/orch

### LINKED ISSUE #54521: [Regression] Failhard, batch and retcodes
### Description of Issue
Seems like there are long forgotten issue regarding `failhard` support with `batch`.

Seems like an ability to stop batch execution after a first encountered error was added here: https://github.com/saltstack/salt/pull/22855/

After that it was many times reported to be broken or not working as expected:
https://github.com/saltstack/salt/issues/29643 - supposed to be fixed by https://github.com/saltstack/salt/pull/31164
https://github.com/saltstack/salt/issues/44256 - not resolved, closed as stale.
https://github.com/saltstack/salt/issues/24996 - supposed to be fixed by https://github.com/saltstack/salt/pull/33048

As for 2019.2.0 Salt orchestration with `failhard: True` **don't stop** after a first error but continue to execute all hosts batch by batch.

This behavior is very dangerous and could lead to applying broken state on the whole fleet before you even notice or to loss data and just a huge pain for any network consensus type of bootstrapping like Mysql Galera.

### Steps to Reproduce Issue
Create an orchestration file:
```
issue:
  salt.state:
    - tgt: '*'
    - sls:
      - bug
    - batch: 1
```
Create a state file `bug`:
```
first:
  cmd.run:
    - name: echo "first"

will_fail:
  http.query:
    - name: 'http://127.0.0.1:10000'
    - status: 200

unreachable:
  cmd.run:
    - name: echo "unreachable"
```

execute this orchestration with `failhard: True` set in configs.

**Expected**: Execution stopped after the first node returned an error from non-working state `will_fail`.
**Currently**: Execution of the state failing on `will_fail` but all nodes execute the state, batch by batch.

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.6 (default, Aug 13 2018, 18:24:23)
   python-gnupg: 0.4.4
         PyYAML: 5.1
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

### PR DESCRIPTION
**Pull request by mattp-**
also noticed a bug in cli.batch itself, probably from backport mistake.
fixed that as well with the unindent.

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?
**[NOTICE] Bug fixes or features added to Salt require tests.**
Please review the [test documentation](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html) for details on how to implement tests into Salt's test suite.

Yes/No

### Commits signed with GPG?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by dwoz** [comment]
@mattp- Can you rebase this and open it against `master`?

**Comment by mattp-** [comment]
Sure, will try to get to it tomorrow

**Comment by Oloremo** [comment]
@dwoz @mattp-  Folks, I'm pretty sure it was already merged here https://github.com/saltstack/salt/pull/54806 and I was under impression that master was created from 2019.2.1

**Review by cmcmarrow — CHANGES_REQUESTED** [review]
Thanks for the code! But we still need some test.

**Comment by sagetherage** [comment]
closing since this is pointing to develop instead of master and it may be merged already from the comments above

**Pull request closed without merging**
