### PR TITLE
Consider comments in pkgrepo.managed.

### LINKED ISSUE #32605: pkgrepo.managed with apt does not add comments value later
### Description of Issue/Question
If one add `comments:` (see [comments](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkgrepo.html#salt.states.pkgrepo.managed)) state option later after state has once ran (and .list file is already created), comments are no actually added to the file. If file is deleted and state is run, then new file is created with `comments` present.

### Setup
Let's say we have initial pgdg.sls state:
```
{% set codename = grains.get('lsb_distrib_codename')|lower %}

repository_pgdg:
  pkgrepo.managed:
    - humanname: {{ codename }}-backports
    - file: /etc/apt/sources.list.d/pgdg.list
    - refresh_db: True
    - clean_file: True
    - name: deb http://apt.postgresql.org/pub/repos/apt/ {{ codename }}-pgdg main
    - key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    - require:
        - pkg: ca_certificates
```
Execute highstate so file with this content is created:
```
deb http://apt.postgresql.org/pub/repos/apt wheezy-pgdg main
```

Later, update original pgdg.sls state to look like this:
```
{% set codename = grains.get('lsb_distrib_codename')|lower %}

repository_pgdg:
  pkgrepo.managed:
    - humanname: {{ codename }}-backports
    - file: /etc/apt/sources.list.d/pgdg.list
    - refresh_db: True
    - clean_file: True
    - name: deb http://apt.postgresql.org/pub/repos/apt/ {{ codename }}-pgdg main
    - comments: 
        - 'THIS FILE IS MANAGED BY SALT! DO NOT EDIT MANUALLY!'
    - key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    - require:
        - pkg: ca_certificates
```

Note that `comments` option was added. 

Now, after state.highstate, there is _no actual changes are made_ to `/etc/apt/sources.list.d/pgdg.list` file.

If I delete `/etc/apt/sources.list.d/pgdg.list` and run this state again, file is created with comments as it should:
```
 deb http://apt.postgresql.org/pub/repos/apt wheezy-pgdg main #THIS FILE IS MANAGED BY SALT! DO NOT EDIT MANUALLY!
```

### Steps to Reproduce Issue

Repleat state changes in previous section.

### Versions Report
```
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.6
       M2Crypto: Not Installed
           Mako: 0.7.0
         PyYAML: 3.10
          PyZMQ: 13.1.0
         Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.3
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 7.10 
        machine: x86_64
        release: 3.2.0-4-amd64
         system: debian 7.10 
``` 

Both master and minion are the same Debian Wheezy amd64 with same salt versions:
```
# salt-run manage.versions
Master:
    2015.8.8.2
Up to date:
    ----------
    minion:
        2015.8.8.2
    master:
        2015.8.8.2

```

### PR DESCRIPTION
**Pull request by abednarik**
### What does this PR do?

Include comments in order to decide or not if a repo file in debian family systems
should be updated or not.
### What issues does this PR fix or reference?

Fixes #32605.
### Previous Behavior

If a repo file already exsists and a comment is added, not change are applied to the file so no comments are added to the repo file.
### New Behavior

Considerer comment before taking the decision to update or not the repo file
### Tests written?

No

### CODE REVIEW

**Comment by Talkless** [comment]
If I understood correctly, this searches for comment in whole file. Since there is possibility to use single file for multiple repos, this will not allow to add duplicate comments.

Let's say before:
```
deb http://some.postgresql.repo.org # MUSTHAVE FOR OUR WEBAPP!!1
deb http://some.php7.repo.org
```
But this will not make it into:
```
deb http://some.postgresql.repo.org # MUSTHAVE FOR OUR WEBAPP!!1
deb http://some.php7.repo.org # MUSTHAVE FOR OUR WEBAPP!!1
```
Because that comment was already in file.

Maybe it would be more robust to search for comment in that particular repo line?

By the way thanks for your time @abednarik .

**Comment by abednarik** [comment]
You are right. I will see what I can do about that. In the meantime I think this is better than nothing.

**Comment by cachedout** [comment]
@abednarik I would like to hold off on this until the concerns from @Talkless can be address. His use case seems very valid. A fix shouldn't be too hard. Let me know what you think.

**Comment by abednarik** [comment]
Closing since this does not looks like a bug for me . [Docs](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.aptpkg.html#salt.modules.aptpkg.mod_repo) are clear regarding the options available in order to change a repo.
Maybe this is a new feature or something similar?

**Comment by cachedout** [comment]
Sounds good. Thanks, @abednarik

**Pull request closed without merging**
