### PR TITLE
Add docker-ng module

### PR DESCRIPTION
**Pull request by terminalmage**
States to come later, likely in a separate pull request.

### CODE REVIEW

**Comment by ticosax** [comment]
Thanks for this.
I think `lxc-attach` and `nsenter` are legacy now. `client.execute()` is probably the way to go with recent versions of docker.

Also it would be great to document in `modules.dockerio` that this module is now deprecated.

**Comment by terminalmage** [comment]
@ticosax ``client.execute()`` does not return stdout and stderr separately, which we need to be able to replicate [cmd.run_all](http://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cmdmod.html?highlight=cmdmod.run#salt.modules.cmdmod.run_all). I'll clarify this in the docstring.

Also, good call on the message in dockerio.py. I had intended to do this but forgot. Thanks for the reminder!

**Comment by terminalmage** [comment]
I might be able to use ``docker exec`` on the CLI though... I'll investigate.

**Comment by terminalmage** [comment]
@ticosax Yeah I can use ``docker exec`` on the CLI. I'm most of the way there on getting this added.

**Comment by terminalmage** [comment]
@ticosax I've implemented ``docker exec`` support. The documentation at the top of dockerng.py has also been modified to reflect this. Let me know what you think. Thanks again for the suggestion!

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by ticosax** [comment]
@terminalmage This is great ! I'm looking forward to try this new module, I believe it will speed up execution of states drastically thanks to the `client` cached in `__context__`.

**Comment by terminalmage** [comment]
@ticosax Sweet! I'm working on a state module today, should hopefully have it ready by later this week.

One major change is that there will not be pulled/loaded/built/etc. states. These are not idempotent and are little more than wrappers around remote execution functions. Those actions can be taken via a ``module.run`` state. Instead, we will have the (more "salty") ``present`` and ``absent`` states, with arguments to the ``present`` state controlling whether an image is pulled/loaded/built, etc.

Let me know if you have any feedback on this. I'll be sure to ping you when I submit a pull request for the new state module.

**Comment by iggy** [comment]
Some things could use version annotations (changes to container_resource, additional args all over the place, etc).

**Comment by terminalmage** [comment]
@iggy could you clarify what you mean by this?

**Comment by terminalmage** [comment]
The container_resource module is not designed to be run from the CLI, so I'm not really concerned with having ``.. versionadded::`` directives there.

**Comment by iggy** [comment]
Okay. I just look through all new stuff I see to look for version annotations these days (because I'm tired of answering the questions in IRC that innevitably arise when the docs aren't versioned). If you think everything that needs to be version annotated is done correctly, then carry on.

**Comment by terminalmage** [comment]
@iggy I can go ahead and add them (it certainly won't hurt anything to do so), but the impact of not having them would be minimal since this module is only used by other container modules. If I could, I'd put this logic somewhere in ``salt.utils``, but ``salt.utils`` doesn't get the ``__salt__`` dictionary added to it, which we need.

Can you clarify what you mean by "additional args all over the place"? Did you mean the new arguments in ``container_resource.run``? If so, keep in mind that this module is new in develop so I think a top-level ``.. versionadded::`` will work for this.

**Comment by terminalmage** [comment]
@iggy have a look at this: https://github.com/saltstack/salt/commit/8c93dec3c8da7d902bb8c180e059e30c5cb838be

**Comment by thatch45** [comment]
@terminalmage let me know when this is ready to merge it is all thumbs up from me!

**Comment by iggy** [comment]
:+1:

**Comment by terminalmage** [comment]
@thatch45 I've got no other changes to make for now. Any changes I need based on the new states I'm writing, I'll submit with the PR when I am done with the states.

**Comment by cachedout** [comment]
Merged!

**Comment by terminalmage** [comment]
Sweet! Thanks to @ticosax and @iggy for the great feedback.

**Comment by ticosax** [comment]
@terminalmage in reply of your comment https://github.com/saltstack/salt/pull/22129#issuecomment-87695150
I'm a heavy user of `docker.pulled` state because if the download fails I have a nice error message that is easier to debug. Also, `pulled` can be idempotent (unlike `push` and `build`, that I agree to be removed).

Therefore I know `docker.pulled` is not strictly necessary because the `docker daemon` will download the image for me automatically when this state will be executed:

```yaml
container-lambda:
  docker.running:
    - image: lambda
    - tag: v1.1.1
```
It will also pull the image from the registry implicitely, but in case of download failure the error message is not as good as `docker.pulled`, because I do not know what failed.

I'm saying: maybe you can keep `docker.pulled`.

**Comment by terminalmage** [comment]
@ticosax If there is a good use case for a ``pulled`` state, then I have no objections to having one. I'm starting with a ``docker-ng.running`` state which will accept ``pull``, ``build``, and ``load`` arguments. If the named container doesn't exist, then whichever of those three types of ways of getting the image will be used to do so. If the named container already exists, then Salt doesn't even need to try to pull. That is the optimal way of doing it, in my opinion. But if you just want an image there and don't necessarily care if a container is associated with it, then yeah, I see the use case for a ``pulled`` state.

I'll ping you when I open the pull request for the states once they're ready, and you can let me know what you think. Thanks again for your input.

**Comment by terminalmage** [comment]
Actually I think I might just make it a ``docker-ng.present`` state, with a ``- running: True`` if you want it to be running. Then the same state can be use to manage the running state and ensure the container exists.

**Comment by ticosax** [comment]
Merging states is maybe not a so good idea,
because some parameters are usefull for `docker.pulled` or `docker.runnig` only.
For instance if we want to refresh the image to the latest version available,
today we do:

```yaml
docker-image:
  docker.pulled:
     - tag: latest
     - force: True
```
 Inside `docker-ng.present` is going to be confusing.

Same with `kill_signal` parameter:
```yaml
docker-container:
  docker.running:
    - kill_signal: SIGHUP
```
I do not see how it fits into `docker-ng.present`.

And the `mod_watch` implementation is going to be a plate of :spaghetti: if all states are merged.

Anyway, I will wait until you make a pull request and I will see how it could work before I critisize :smile: .

**Pull request merged**
