### PR TITLE
rpm: Properly detect other ARMv7 (32 Bit) arches

### LINKED ISSUE #60994: [BUG] Doesn't recognize some packages as installed on ARMv7 Fedora 34
**Description**
Salt doesn't recognize some packages as installed on ARMv7 Fedora 34, due to them being in a different, but compatible, arch. This leads to `pkg.installed` failing on subsequent runs, as it tries to install already installed packages.
For example `ffmpeg` from rpmfusion is currently `ffmpeg-4.4-6.fc34.armv7hnl` while the Fedora default is `armv7hl` (per `rpm --eval %{_host_cpu}`).

**Setup**
```
{%- if not salt['file.file_exists' ]('/etc/yum.repos.d/rpmfusion-free.repo') %}
Enable rpmfusion free:
  cmd.run:
   - name: "dnf -y install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm"
{%- endif %}
Install packages I need:
  pkg.installed:
    - pkgs:
      - ffmpeg
```
Ran on a ARMv7 device with Fedora 34.

  
**Steps to Reproduce the behavior**
Apply the above state. When ffmpeg is already installed (=> on the second run), it will fail with "The following packages failed to install/update: ffmpeg".

**Expected behavior**
`ffmpeg` correctly recognized as already installed.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003.3
 
Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: 0.37.1
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: 2.6.1
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.9.7 (default, Aug 30 2021, 00:00:00)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.0.3
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: fedora 34 
        locale: utf-8
       machine: armv7l
       release: 5.14.9-200.fc34.armv7hl
        system: Linux
       version: Fedora 34
```
</details>

**Additional context**

### PR DESCRIPTION
**Pull request by mariushoch**
Similar to x86 32bit (i386, i486, …) there are several ARMv7 architectures that can be found alongside on one device. Salt should properly handle these and treat them all the same (if on such a ARMv7 device).
See also the current list at https://github.com/rpm-software-management/yum/blob/master/rpmUtils/arch.py (from which salt's list is derived).

### What does this PR do?
This enables salt to properly detect other, usually compatible, ARM arches when handling rpm packages on a ARMv7 device.

### What issues does this PR fix or reference?
Fixes: #60994

### Previous Behavior
(on an ARMv7 device running Fedora 34)
```
# salt-call pkg.normalize_name ffmpeg-4.4-6.fc34.armv7hnl
local:
    ffmpeg-4.4-6.fc34.armv7hnl
```

### New Behavior
(on an ARMv7 device running Fedora 34)
```
# salt-call pkg.normalize_name ffmpeg-4.4-6.fc34.armv7hnl
local:
    ffmpeg-4.4-6.fc34
```

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [X] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by dmurphy18 — COMMENTED** [review]
Needs to pass tests, otherwise looks good

**Review by dmurphy18 — APPROVED** [review]

**Review by dmurphy18 — CHANGES_REQUESTED** [review]
Need to add a changelog for the changes

**Comment by dmurphy18** [comment]
@mariushoch Are you still interested in this PR ?, if unresponsive the PR shall be closed after several days.
Everything is good except need to add a changelog entry

**Comment by mariushoch** [comment]
> @mariushoch Are you still interested in this PR ?, if unresponsive the PR shall be closed after several days. Everything is good except need to add a changelog entry

Thanks for having a look. Added :+1:

**Review by dmurphy18 — APPROVED** [review]

**Review by Ch3LL — APPROVED** [review]

**Review by whytewolf — APPROVED** [review]

**Pull request merged**
