### PR TITLE
salt.utils.cache: add some guards against zero byte files

### PR DESCRIPTION
**Pull request by mattp-**
### What does this PR do?
if an io error occurs, and/or msgpack failure, the cache could
tentatively be left in a state  of zero byte file. on these exceptions,
check to ensure we clean up after ourselves.

### Tests written?
Pending

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by cachedout** [comment]
@mattp- Some test failures I'm afraid.

**Comment by cachedout** [comment]
@mattp- Almost there. :) Still some cache test failures, interestingly.

**Comment by dwoz** [comment]
@mattp- Can you look into the merge conflict and linter failures?

**Comment by dwoz** [comment]
@mattp- Looks like we still have a merge conflict here. Please have a look.

**Comment by mattp-** [comment]
@dwoz rebased and passing now, thank you

**Comment by Ch3LL** [comment]
FYI I migrated this PR from develop to neon to ensure it is included in the upcoming neon release. Let me know if this caused any issues. Thanks

**Comment by dwoz** [comment]
@mattp- Is this something that should get rebased to the master branch?

**Comment by sagetherage** [comment]
this is still pointing to neon so I am removing the `Sodium` label and removing it from the Sodium project board unless @mattp- you are going to update this PR this week

**Comment by sagetherage** [comment]
@mattp- looks like this is older and maybe no longer needed?

**Comment by mattp-** [comment]
yep that's fine, thanks

**Pull request closed without merging**
