### PR TITLE
Adding preliminary support for Rocky.

### PR DESCRIPTION
**Pull request by StackKorora**
### What does this PR do?
This PR is adding Rocky as a 1:1 Red Hat derivative https://rockylinux.org/ . The hope is to have initial release at the end of this month. Also, I realize that this is a preliminary future-change as Rocky isn't released yet. I'm trying to help out in the community where I can. :-)

### What issues does this PR fix or reference?
Adds Rocky Linux as a recognized OS. https://rockylinux.org/

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by StackKorora** [comment]
Not sure what to do about the doc's checkbox...

**Review by twangboy — DISMISSED** [review]

**Comment by Ch3LL** [comment]
Looks like there is a merge conflict that needs to be cleaned up here.

**Comment by StackKorora** [comment]
Greetings,
I've looked through the error files and poked around in the jenkins.saltproject.io job output. I'm not sure what it's telling me about those jobs failing. Can someone please help me understand what the problem is?
Thanks!

**Comment by Ch3LL** [comment]
Those should not be related. I'll re-run the tests, because we had some issues with the tests this morning that should be cleaned up now.

**Review by Ch3LL — APPROVED** [review]

**Review by krionbsd — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Comment by mjtrangoni** [comment]
@twangboy @KaloBeshWork @barneysowood after 5 months, this is still not part of 3003.3. Any ETA for releasing it?

**Comment by falcantaralinode** [comment]
Same any ETA for Rocky linux support for 3003.3 or higher?

**Comment by mjtrangoni** [comment]
> Same any ETA for Rocky linux support for 3003.3 or higher? 

Read the changelogs! This is already released.

**Pull request merged**
