### PR TITLE
runners/net.py napalm-base ImportError fix

### PR DESCRIPTION
**Pull request by leec-666**
### What does this PR do?

Fixed napalm_base module import based on utils/napalm.py code

```
[root@salt salt]# salt --versions-report
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
```

### What issues does this PR fix or reference?

```
[root@salt runners]# salt-run net.find 1.2.3.4       
'net' __virtual__ returned False: The napalm-base module could not be imported
```

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Review by dwoz — CHANGES_REQUESTED** [review]
@chonty This needs to be opened against the `master` branch.

**Comment by chonty** [comment]
Alright, done.  The [Contributing guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) makes no mention of this I'll add.

**Comment by dwoz** [comment]
> Alright, done. The [Contributing guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) makes no mention of this I'll add.

@chonty Valid point. We are aware of the inconsistencies in the contributing guide and have a couple open PRs that should address them.

**Review by bryceml — CHANGES_REQUESTED** [review]
the changes to layout.html seem unrelated and pointless at a quick glance.  I would take out those changes.

**Review by bryceml — COMMENTED** [review]
👍

**Comment by bryceml** [comment]
@chonty this needs a review from someone on @saltstack/team-core for the rest of the changes, I only had comments to make about the doc changes.

**Review by bryceml — COMMENTED** [review]
Leaving a review here so Pull Reminders leaves me alone, we still need a review from a core team member.

**Comment by chonty** [comment]
Merged PR #55421 fixes the same problems.

**Pull request closed without merging**
