### PR TITLE
adding states/postgres_extension unit test case.

### PR DESCRIPTION
**Pull request by jayeshka**
Implemented states/postgres_extension_test unit test case.

### CODE REVIEW

**Comment by jfindlay** [comment]
@jayeshka, https://jenkins.saltstack.com/job/salt-pr-rs-cent7-n/5705/

**Comment by jayeshka** [comment]
@jfindlay test are passing at my end.
Pulled updated branch of 2015.5 and try to run th test. I don't get any failures.
Tried for both #24329 and #24330.

**Comment by jfindlay** [comment]
@jayeshka, I'll look into this as well, thanks for the extra effort.

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Pull request merged**
