### PR TITLE
22822 file directory clean

### PR DESCRIPTION
**Pull request by hvnsweeting**

### CODE REVIEW

**Comment by jfindlay** [comment]
@hvnsweeting, there are some legitimate test failures here, one lint test and two integration tests.

**Comment by cachedout** [comment]
@hvnsweeting Have you been able to re-examine this PR to resolve the test failures? Please let us know how we can help.

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Pull request merged**
