### PR TITLE
Pass grains in minion startup event

### PR DESCRIPTION
**Pull request by admd**
### Note
The previous PR against develop branch https://github.com/saltstack/salt/pull/54087 has more discussion about the background for this change.

### What does this PR do?
Adds a configuration option to have a selection of grains in the minion start event.

Reason behind this is better integration with [Uyuni]( https://github.com/uyuni-project/uyuni), especially when a lot of minions are starting in a short time frame - we need to get some minimal data (at least the `machine_id`) and getting it separately as a reaction to the minion start event (via a separate call or a startup state) generates considerable load on the master.

By default, there will be no grains passed to the event.

### Previous Behavior
```
salt/minion/test-minion.tf.local/start	{
    "_stamp": "2019-08-01T10:46:22.840597", 
    "cmd": "_minion_event", 
    "data": "Minion test-minion.tf.local started at Thu Aug  1 12:46:22 2019", 
    "id": "test-minion.tf.local", 
    "pretag": null, 
    "tag": "salt/minion/test-minion.tf.local/start"
}
```

### New Behavior
```
salt/minion/test-minion.tf.local/start	{
    "_stamp": "2019-08-01T10:46:58.696390", 
    "cmd": "_minion_event", 
    "data": "Minion test-minion.tf.local started at Thu Aug  1 12:46:58 2019", 
    "grains": {
        "uuid": "f4cd2a8c-eb73-11e9-81b4-2a2ae2dbcce4", 
        "machine_id": "21ee22c6906887c2dd6adeed5d404145"
    }, 
    "id": "test-minion.tf.local", 
    "pretag": null, 
    "tag": "salt/minion/test-minion.tf.local/start"
}
```

### Tests written?

Yes

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by admd** [comment]
@waynew

**Comment by brejoc** [comment]
@saltstack/core-pr-reviewers Could you please take a look here? Seems like the tests aren't running.

**Comment by admd** [comment]
Any update here, please.

**Comment by moio** [comment]
@saltstack/core-pr-reviewers @DmitryKuzmenko this is now waiting since October, could you have a look in the near future by any chance?

**Comment by brejoc** [comment]
Hey @s0undt3ch, thanks for taking a look here. Tests are looking good!

**Review by dwoz — APPROVED** [review]

**Comment by max-arnold** [comment]
I just discovered that this feature (when enabled) will append grains to other events sent from a minion (not just the start event):

Both commands

```
sudo salt minion1 state.single event.send name='tag' data='{"data":"my event data"}'
sudo salt minion1 event.fire_master '{"data":"my event data"}' 'tag'
```

result in the following master event:

```
tag	{
    "_stamp": "2020-01-15T07:55:24.548188",
    "cmd": "_minion_event",
    "data": {
        "data": "my event data"
    },
    "grains": {
        "machine_id": "599118d5b9619443ac3166fb0e59349e",
        "uuid": "599118d5-b961-9443-ac31-66fb0e59349e"
    },
    "id": "minion1",
    "pretag": null,
    "tag": "tag"
}
```

`def _fire_master_minion_start(self)` seems to be better suited for this code.

**Comment by waynew** [comment]
@max-arnold just passing through on this PR - was that a suggestion that we should create a new PR to update this behavior? If so, would you mind opening an issue so it doesn't get lost here in the PR? Otherwise feel free to ignore this comment :slightly_smiling_face:

**Pull request merged**
