### PR TITLE
Docs update for function args limit in pub acl.

### LINKED ISSUE #42626: new args and kwargs options for publisher_acl are not documented at all and very little for external_auth
`publisher_acl` and `external_auth` authentication have been improved upon to allow for args and kwargs to be whitelisted for functions.

The only documentation I could find was for the `external_auth` option here:  https://docs.saltstack.com/en/latest/topics/eauth/index.html#limiting-by-function-arguments

The docs aren't very clear on what exactly is being allowed and disallowed and the examples aren't very helpful.

I could find absolutely no docs on these options for `publisher_acl`,
https://docs.saltstack.com/en/latest/ref/publisheracl.html

but another user had spoken with a SaltStack PS engineer and has found the following to work:

```
publisher_acl:                                                                  
  user01:                                                                       
    - '*hdpmb*':                                                                
      - state.sls:                                                              
          args:                                                                 
          - 'config.linux.hadoop.*'                                             
      - test.ping                                                               
  user02:                                                                    
    - '*':                                                                      
      - test.ping                                                               
      - state.sls:                                                              
          args:                                                                 
          - 'config.linux.generic.motd'                                         
  user03:                                                                      
    - '*':                                                                      
      - test.ping                                                               
      - cmd.run:                                                                
          args:                                                                 
          - 'cat /etc/issue'                                                    
      - state.sls:                                                              
          args:                                                                 
          - 'config.linux.generic.motd'                                         
  user04:                                                                       
    - 'G@sid:*':                                                                
      - test.ping                                                               
      - grains.item                                                             
      - grains.items                                                            
      - state.sls:                                                              
          args:                                                                 
          - 'sap_basis.*'                                                       
      - state.show_sls:                                                         
          args:                                                                 
          - 'sap_basis.*'
```

Due to the sensitive nature of dealing with security, the documentation for these new options needs to be completed and filled out with examples. Preferably by the engineer who originally wrote it and understands what these options are supposed to be allowing

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
### What does this PR do?
Updates `publisher_acl` documentation adding an example of function arguments restrictions and a reference to the `external_auth` documentation that has the same syntax and feature list.

### What issues does this PR fix or reference?
Fix #42626

### Tests written?
No

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by rallytime — APPROVED** [review]

**Comment by UtahDave** [comment]
@DmitryKuzmenko can you add an example that shows off the regex capabilities a little more?

Does the following work?

```
publisher_acl:
  (user1|user2):
    - .*
```

**Comment by DmitryKuzmenko** [comment]
@UtahDave  you're right, I've re-read the docs and found no explicit note about how user names are matched. I've added one more commit. Could you re-review it please?

**Comment by UtahDave** [comment]
I think that helps a lot @DmitryKuzmenko .  Thanks!

**Review by UtahDave — APPROVED** [review]
I think that helps clear that up.  Thanks!

**Comment by DmitryKuzmenko** [comment]
@UtahDave thank you for routing me the right way. 👍

**Comment by DmitryKuzmenko** [comment]
Just want to remind that it's good to have it in Oxygen.

**Pull request merged**
