### PR TITLE
grains: Remove dmesg path and add additional detection path for virtu…

### PR DESCRIPTION
**Pull request by eousphoros**
…albox, rhev, ovirt, and gce

Improves behavior mentioned in #25101 

dmesg has a limited buffer size and will eventually drop the lines we are trying to match against. This patch removes calling dmesg and adds an additional detection path.

### CODE REVIEW

**Comment by eousphoros** [comment]
Any comments here? I can back out the dmesg change if thats what is holding this up. The issue that I have using dmesg is it creates an opportunity for the virtual fact to change unexpectedly during the provision of docker hosts. Though the additional detection path will fix that issue with my personal setup (virtualbox), it still leaves that as an opportunity for someone to hit the same issue.

**Comment by thatch45** [comment]
Thanks, the point that dmesg is not going to give us consistent data is valid. We will see if this causes any other problems but I think this is the right move. Thanks @eousphoros

**Comment by jfindlay** [comment]
Fixes #25101.

**Comment by rallytime** [comment]
@eousphoros Since this is fixing a bug that is present on 2015.5, I was going to back-port this so we could have the fix in a newer release. Unfortunately, there are some merge conflicts that I am not certain how to resolve as I am not very familiar with this area of the code...

Would you be willing to submit this fix against 2015.5?

**Comment by eousphoros** [comment]
Sure thing, let me read up on the process for doing backups and I will get something put together. Thank you for merging this in. It will make my life better.

**Comment by jfindlay** [comment]
Thanks @eousphoros.  We have [documentation](http://docs.saltstack.com/en/latest/topics/development/contributing.html#backporting-pull-requests) if it helps.

**Pull request merged**
