### PR TITLE
Fix puppet.fact and puppet.facts to use stdout.

### PR DESCRIPTION
**Pull request by myinitialsarepm**
### What does this PR do?
facter prints non-fatal errors to stderr if cmd.run is used then this is
merged into the output and breaks the parsing. This commit changes the
`puppet.fact` and `puppet.facts` functions to use `cmd.run_all` instead.

### What issues does this PR fix or reference?
#46581

### Previous Behavior
`puppet.facts` and `puppet.fact` would merge stderr into stdout which caused errors when `facter` printed non-fatal errors to `stderr`

### New Behavior
`cmd.run_all` is used to separate the `stderr` and `stdout` streams.

### Tests written?

No

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by rallytime** [comment]
Hi @myinitialsarepm and welcome!

We're not merging changes into the `2015.8` branch anymore. Can you change the base branch for this to the `2017.7` branch instead? That's the currently supported bug fix release now. :)

**Comment by myinitialsarepm** [comment]
Hi sorry about that, I shouldn't have skimmed the supported versions page. Hopefully this fixes is as it should be :)

**Review by cachedout — APPROVED** [review]

**Comment by rallytime** [comment]
@myinitialsarepm Thanks for updating the base branch. :)

There are some test failures here that need to be addressed: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-cent7-py3/3369/

**Comment by cachedout** [comment]
@myinitialsarepm Are you going to be able to come back to investigate the test failures that @rallytime mentioned?

**Comment by myinitialsarepm** [comment]
Hi @cachedout I have been unable to reproduce the failures on my machine and the output no longer seems available in your Jenkins. From memory the error was the "cmd.run_all" was unavailable in the __salt__ dict and I don't quite understand how that could be possible.

**Comment by cachedout** [comment]
Hi @myinitialsarepm

All we need to do here is add a mock to the test to cover this. If you take a look at `test_puppet.py` in `salt/tests/unit/modules` and it should be easy to see where to make the changes for `cmd.run_all`. Let me know if you have questions.

**Comment by rallytime** [comment]
re-run py3

**Pull request merged**
