### PR TITLE
Backport ini_manage fixes to 2018.3

### PR DESCRIPTION
**Pull request by mtorromeo**
### What does this PR do?

Backports fixes to the ini_manage.py state and module that is currently broken in 2018.3 since the latest refactor of the DEFAULT_IMPLICIT section handling.

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by rallytime** [comment]
Hi @mtorromeo - Can you explain a little more about what this back-port is fixing? There aren't any associated issues listed above, so it's a little difficult to tell what needs to be fixed. Especially since this looks like a rather large change for a back-port.

**Comment by mtorromeo** [comment]
Sorry for the lack of details.

This PR backports the fix to the issue described here https://github.com/saltstack/salt/issues/33668#issuecomment-275701019 that was probably introduced by https://github.com/saltstack/salt/commit/7ac43c777ffa3ffa2289ed299a2369b32adb8146#diff-eb79e653514582e519a513098124d9b1 which removed the DEFAULT_IMPLICIT special section but left over some references and more importantly caused a different behaviour between testing a state and applying it.

The bulk of the changes are in commit https://github.com/saltstack/salt/commit/479c8deeeaf26b20a425f6a3513dbd4a464c7fb0 (backported as https://github.com/saltstack/salt/pull/48310/commits/c179b82422ac8c6ef74347404ddc1d98bc396dda) which includes the mentioned fix.

I didn't want to create a new distinct fix for that issue since it was already fixed but I agree that the changes are quite laarge.

Commit https://github.com/saltstack/salt/pull/48310/commits/0a32f936916884bc14a2f2702fe3368e038a66af fixes an unreported issue introduces by the previous change.

The "pylint fixes" and "uniformed reports" commits may be skipped but are rather small changes.

**Comment by rallytime** [comment]
re-run lint

**Comment by rallytime** [comment]
@mtorromeo Ok, thank you for that explanation. Lint failed in the last run, but the results timed out, so I have started the test again. If you could fix that up with it's finished running, then we can review this. :)

**Comment by mtorromeo** [comment]
The lint is fixed in commit https://github.com/saltstack/salt/commit/c13e79d8b6c4299f12fe5118a9131c4c1b093d9d. Should I backport that also?

**Comment by rallytime** [comment]
@mtorromeo Yeah, I think so.

**Comment by mtorromeo** [comment]
Done, I also rebased on 2018.3

**Review by rallytime — APPROVED** [review]

**Pull request merged**
