### PR TITLE
Lxc seed and prof ports

### PR DESCRIPTION
**Pull request by kiorky**
refs #23772 #23833 #23847

Third of the patch series

Port of the two others to develop + the reconfigure bits

### CODE REVIEW

**Comment by kiorky** [comment]
refs #23807 #23806

**Comment by jfindlay** [comment]
@kiorky, it's not necessary to submit commits to two branches at the same time as they are regularly merged forward.

**Comment by kiorky** [comment]
@jfindlay no it neccessary here, the two branches are diverging, and only me and @terminalmage know the nuances.

**Comment by kiorky** [comment]
please hold on merge, i have few commits more for systemd based containers

**Comment by kiorky** [comment]
(always hold, i ll ping when ready)

**Comment by kiorky** [comment]
@terminalmage PTAL now, seems a bit more stable.

**Comment by kiorky** [comment]
wont be approved.

**Comment by basepi** [comment]
See my comment here: https://github.com/saltstack/salt/pull/23805#issuecomment-103238312

**Comment by basepi** [comment]
@kiorky Please wait for #23893 then you can make your changes on top.

**Pull request closed without merging**
