### PR TITLE
make saltify provider use standard boostrap procedure

### PR DESCRIPTION
**Pull request by ahus1**
Using this all options like master_sign_pub_file are now supported. 

If possible please merge this to the 2015.5 branch. I tested it by putting it into a _clouds folder in my files_root and it works fine with 2015.5.0

Thanks!

### CODE REVIEW

**Comment by techhat** [comment]
@ahus1, if you would like, you may submit this against the 2015.5 branch yourself. We can backport, but it's cleaner if the PR is already submitted against that branch.

Also, thank you for addressing this!

**Comment by ahus1** [comment]
@techhat - I first wanted a +1 for this to be allowed in branch 2015.5. 

Do you give a "+1" here? 

Would I need to close and re-open the PR for 2015.5? Or keep this and add a second?

**Comment by techhat** [comment]
@ahus1 this is an official +1. ^_^

You will need to open up a new PR against the other branch, if you're willing to go that way. You can go ahead and close this one too, since the other PR will be merged forward into develop.

**Comment by ahus1** [comment]
This is obsolete due to PR #23832

**Pull request closed without merging**
