### PR TITLE
Backport DNF support to 2015.5 branch

### LINKED ISSUE #23553: dnf a new package provider for fedora 22
fedora 22 will use dnf by default and won't be shipping yum:
http://dnf.baseurl.org/2015/05/11/yum-is-dead-long-live-dnf/

more information
http://dnf.baseurl.org/2015/05/11/dnf-1-0-and-dnf-plugins-core-0-1-7-released/

reference use case python api:
http://dnf.readthedocs.org/en/latest/use_cases.html#id6

### PR DESCRIPTION
**Pull request by terminalmage**
This will allow 2015.5 releases to operate successfully on Fedora 22 and
newer.

Resolves #23553.

### CODE REVIEW

**Comment by terminalmage** [comment]
Working on lint issues now.

**Comment by cachedout** [comment]
@terminalmage Would you grabbing that final lint issue please?

**Comment by terminalmage** [comment]
Lint is passing now.

**Comment by terminalmage** [comment]
Failed tests are due to known issues with new version of boto, and are unrelated.

**Pull request merged**
