### PR TITLE
Add splay support for all scheduling criteria

### PR DESCRIPTION
**Pull request by YuriGrigorov**
### What does this PR do?

Adds splay support for all scheduling criteria

### What issues does this PR fix or reference?

https://github.com/saltstack/salt/issues/39322

### Tests written?

No

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@garethgreenaway Any chance you can help review this?

**Comment by garethgreenaway** [comment]
@cachedout Apologies for the delay.  PR looked good!

**Comment by cachedout** [comment]
@garethgreenaway Thanks for following up! I appreciate it. :]

**Comment by gtmanfred** [comment]
I am running into a problem with this commit.

When running with the following config.

```
# cat /etc/salt/master
schedule:
  job1:
    function: test.stdout_print
    minutes: 1
```

I am seeing the process get run when the master is started, but ever time the schedule gets iterated over after that, nothing is run.  If I rever this commit, then it works every minute.

```
2017-03-14 19:37:18,895 [salt.utils.schedule                      ][INFO    ][4985] Running scheduled job: job1
2017-03-14 19:37:18,895 [salt.utils.schedule                      ][DEBUG   ][4985] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
2017-03-14 19:37:18,896 [salt.utils.schedule                      ][DEBUG   ][4985] schedule: This job was scheduled with a max number of 1
```

Thanks,
Daniel

**Pull request merged**
