### PR TITLE
[2017.7] Merge forward from 2016.11 to 2017.7

### PR DESCRIPTION
**Pull request by rallytime**
Conflicts:
  - salt/config/__init__.py
  - salt/master.py
  - salt/modules/zypper.py
  - tests/unit/modules/timezone_test.py

### CODE REVIEW

**Comment by cachedout** [comment]
I'm guessing that this is not playing well with the PR that @cro put in.

**Comment by rallytime** [comment]
@cachedout Yeah. The odd thing is that I can't reproduce these failures locally. I think you're right that it has to do with @cro's changes. 

@cro anything in this stacktrace jump out at you? I am not sure what to do on this one.
```
16:59:32  * Starting salt-master ... 
                                                                                                                                                                
 * Starting salt-master ... STARTED!
16:59:34  * Starting salt-minion ... 16:59:34,150 [salt.transport.zeromq                      :622 ][ERROR   ] Some exception handling a payload from minion
16:59:34 Traceback (most recent call last):
16:59:34   File "/testing/salt/transport/zeromq.py", line 618, in handle_message
16:59:34     ret, req_opts = yield self.payload_handler(payload)
16:59:34   File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1015, in run
16:59:34     value = future.result()
16:59:34   File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
16:59:34     raise_exc_info(self._exc_info)
16:59:34   File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 270, in wrapper
16:59:34     result = func(*args, **kwargs)
16:59:34   File "/testing/salt/master.py", line 894, in _handle_payload
16:59:34     'clear': self._handle_clear}[key](load)
16:59:34   File "/testing/salt/master.py", line 908, in _handle_clear
16:59:34     return getattr(self.clear_funcs, load['cmd'])(load), {'fun': 'send_clear'}
16:59:34   File "/testing/salt/master.py", line 2004, in publish
16:59:34     self._send_pub(payload)
16:59:34   File "/testing/salt/master.py", line 2045, in _send_pub
16:59:34     chan.publish(load)
16:59:34   File "/testing/salt/transport/zeromq.py", line 815, in publish
16:59:34     payload['sig'] = salt.crypt.sign_message(master_pem_path, payload['load'])
16:59:34   File "/testing/salt/crypt.py", line 176, in sign_message
16:59:34     key = _get_rsa_key(privkey_path)
16:59:34   File "/testing/salt/crypt.py", line 169, in _get_rsa_key
16:59:34     return _get_key_with_evict(path, os.path.getmtime(path))
16:59:34   File "/testing/salt/utils/decorators/__init__.py", line 248, in _memoize
16:59:34     args_ = ','.join(list(args) + ['{0}={1}'.format(k, kwargs[k]) for k in sorted(kwargs)])
16:59:34 TypeError: sequence item 1: expected string, float found
16:59:34 16:59:34,151 [salt.payload                               :145 ][CRITICAL] Could not deserialize msgpack message.This often happens when trying to read a file not in binary modeTo see message payload, enable debug logging and retry. Exception: unpack(b) received extra data.
16:59:34 16:59:34,193 [tornado.general                            :410 ][ERROR   ] Uncaught exception, closing connection.
16:59:34 Traceback (most recent call last):
16:59:34   File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
16:59:34     callback(*args, **kwargs)
16:59:34   File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
16:59:34     return fn(*args, **kwargs)
16:59:34   File "/testing/salt/transport/zeromq.py", line 975, in mark_future
16:59:34     data = self.serial.loads(msg[0])
16:59:34   File "/testing/salt/payload.py", line 137, in loads
16:59:34     ret = msgpack.loads(msg, use_list=True, encoding=encoding)
16:59:34   File "msgpack/_unpacker.pyx", line 143, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:2143)
16:59:34 ExtraData: unpack(b) received extra data.
16:59:34 16:59:34,195 [tornado.general                            :445 ][ERROR   ] Uncaught exception, closing connection.
16:59:34 Traceback (most recent call last):
16:59:34   File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 433, in _handle_events
16:59:34     self._handle_recv()
16:59:34   File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
16:59:34     self._run_callback(callback, msg)
16:59:34   File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
16:59:34     callback(*args, **kwargs)
16:59:34   File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
16:59:34     return fn(*args, **kwargs)
16:59:34   File "/testing/salt/transport/zeromq.py", line 975, in mark_future
16:59:34     data = self.serial.loads(msg[0])
16:59:34   File "/testing/salt/payload.py", line 137, in loads
16:59:34     ret = msgpack.loads(msg, use_list=True, encoding=encoding)
16:59:34   File "msgpack/_unpacker.pyx", line 143, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:2143)
16:59:34 ExtraData: unpack(b) received extra data.
16:59:34 16:59:34,195 [tornado.application                        :633 ][ERROR   ] Exception in callback None
16:59:34 Traceback (most recent call last):
16:59:34 
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 887, in start
16:59:34     handler_func(fd_obj, events)
16:59:35   File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
16:59:35     return fn(*args, **kwargs)
16:59:35   File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 433, in _handle_events
16:59:35     self._handle_recv()
16:59:35   File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
16:59:35     self._run_callback(callback, msg)
16:59:35   File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
16:59:35     callback(*args, **kwargs)
16:59:35   File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
16:59:35     return fn(*args, **kwargs)
16:59:35   File "/testing/salt/transport/zeromq.py", line 975, in mark_future
16:59:35     data = self.serial.loads(msg[0])
16:59:35   File "/testing/salt/payload.py", line 137, in loads
16:59:35     ret = msgpack.loads(msg, use_list=True, encoding=encoding)
16:59:35   File "msgpack/_unpacker.pyx", line 143, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:2143)
16:59:35 ExtraData: unpack(b) received extra data.
```

**Comment by cro** [comment]
Yeah, I can see how what I put in might have caused this.  Let me take a look.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Thanks @cro for the quick fix. That worked perfectly.

**Pull request merged**
