### PR TITLE
Backport Python 3 async fixes (and shadow fix)

### PR DESCRIPTION
**Pull request by waynew**
### What does this PR do?

Backports Python3 async/syntax changes to 2017, from https://github.com/saltstack/salt/pull/48705/commits

### What issues does this PR fix or reference?

https://github.com/saltstack/salt-jenkins/issues/1274

### Previous Behavior

Kitchen tests failed running via Jenkins

### New Behavior

Tests *should* pass (still double checking locally, might be a change I still need to fix). At the very least they should run!

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by waynew** [comment]
My tests are still failing locally - I've solved the async thing, but I think there may have been another change to the shadow functionality - maybe on Fedora 29(?) - if a salt is not passed, it appears to return None. I think. I haven't rigorously tested this, but running the full test suite fails, however starting it in interactive mode and running the shadow function does work with enough parameters.

I still need to see if it's just some updates that need to happen to the functionality that's failing.

**Comment by Ch3LL** [comment]
@waynew did you mean to submit this to the 2017.7 branch? looks like its currently on the develop branch.  Also if you are seeing shadow tests failing, this might be the fix you are looking for: https://github.com/saltstack/salt/pull/51079

**Comment by waynew** [comment]
🤦‍♂️ yeah, I did.

**Comment by waynew** [comment]
Well, I've got it pointing to the right target now 😆 Also, looks like that changeset is required to run my tests. Just cherry-picked it over here.

**Comment by waynew** [comment]
So... I'm not sure where the heck the lint was running against, because it's reporting some lines that don't even exist... Oh. I wonder if it failed to pick up the target branch change... should I go ahead and delete this PR and open another?

**Comment by Ch3LL** [comment]
those lint failures are currently failing on the head of 2017.7 branch lint tests. I plan on fixing those up today or tomorrow.

**Comment by Ch3LL** [comment]
we decided previously not to include the async change to 2017.7 here: https://github.com/saltstack/salt/issues/48556#issuecomment-405297312

ping @thatch45 are you okay if we do not include these changes,which will mean this issue https://github.com/saltstack/salt-jenkins/issues/1274 will not be fixed for the 2017.7.9 release

**Comment by thatch45** [comment]
yes, I am good not including this change in 2017.7 :)

**Comment by dwoz** [comment]
This won't make it into the last 2017.7 release. Just closing it for now.

**Pull request closed without merging**
