### PR TITLE
Fix typo for enable_fqdns_grains key

### PR DESCRIPTION
**Pull request by clburlison**
### What does this PR do?
Fixes a typo in the default minion config file. 
### What issues does this PR fix or reference?
Fixes: This typo was introduced with https://github.com/saltstack/salt/pull/57576

### Previous Behavior
If you copy/pasted this key from the minion.dist it wouldn't work

### New Behavior
Copy/paste from the default minion.dist **will** work

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by weswhet** [comment]
good catch @clburlison ! Thanks

**Comment by frebib** [comment]
This caught me out. I ended up working out what had happened after I looked into the code. Thanks

**Review by frebib — APPROVED** [review]

**Comment by clburlison** [comment]
@twangboy Maybe you can review this one since it's so simple.

**Review by garethgreenaway — APPROVED** [review]

**Comment by clburlison** [comment]
Resolved with https://github.com/saltstack/salt/pull/58457

**Pull request closed without merging**
