### PR TITLE
dockerng: Allow both cmd and command to be used to specify command

### PR DESCRIPTION
**Pull request by terminalmage**

### CODE REVIEW

**Comment by isbm** [comment]
Thanks @terminalmage :wink:

**Comment by ticosax** [comment]
It breaks `docker.Client.create_container` as only `command` is accepted, not `cmd`.

**Comment by terminalmage** [comment]
OK, I'll have a look, thanks.

**Comment by ticosax** [comment]
https://github.com/saltstack/salt/pull/27444

**Pull request merged**
