### PR TITLE
Allow binary source files for salt-cp

### PR DESCRIPTION
**Pull request by johnj**
# What does this PR do?

Allow binary source files for salt-cp

### What issues does this PR fix or reference?

Currently, if you reference a binary file as the source file a unicode error (python3) is thrown:

```
Traceback (most recent call last):                                       
  File "/usr/bin/salt-cp", line 10, in <module>                          
    salt_cp()                                                                              
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 387, in salt_cp              
    client.run()                                                         
  File "/usr/lib/python3/dist-packages/salt/cli/cp.py", line 52, in run                                                                 
    cp_.run()                                                                                                                            
  File "/usr/lib/python3/dist-packages/salt/cli/cp.py", line 142, in run                                          
    ret = self.run_oldstyle()                                                                                                              
  File "/usr/lib/python3/dist-packages/salt/cli/cp.py", line 153, in run_oldstyle                                                    
    arg = [self._load_files(), self.opts['dest']]                                          
  File "/usr/lib/python3/dist-packages/salt/cli/cp.py", line 126, in _load_files           
    files.update(self._file_dict(fn_))                                   
  File "/usr/lib/python3/dist-packages/salt/cli/cp.py", line 115, in _file_dict
    data = fp_.read()                                                                      
  File "/usr/lib/python3.6/codecs.py", line 321, in decode                                 
    (result, consumed) = self._buffer_decode(data, self.errors, final)   
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 40: invalid start byte
```

### New behavior

Binary files are allowed as a source file

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Review by twangboy — APPROVED** [review]

**Comment by xeacott** [comment]
I know that this is adding a _minuscule_ amount of code, but Salt does now require a partnering test of some sort. This can even be just writing a test that confirms a binary file has been broadcasted properly.

**Comment by johnj** [comment]
Good call out, I’ll work on this. I think we need to take a deeper look into how salt-cp works on our end as we are seeing a lot of scale issues with masters having many minions connected to them.

**Comment by xeacott** [comment]
Cool. I looked around a little bit, but was unable to find any tests myself. There might be some buried if you dig around, but if not I can help provide some examples/help. Thanks for the PR.

**Comment by dwoz** [comment]
re-run full all

**Comment by dwoz** [comment]
re-run full centos

**Comment by xeacott** [comment]
@johnj Any chance you get get pre-commit passing on this PR too?

**Comment by adcpdk** [comment]
Hi Team! @johnj  @twangboy @garethgreenaway Is there any plan to go proceed with the change?

**Review by twangboy — CHANGES_REQUESTED** [review]
Please rebase this and fix the conflicts. This also needs a changelog and a testcase.

**Comment by Ch3LL** [comment]
Closing due to inactivity. Please let me know if I need to re-open or open a new PR against master including the requested feedback.

**Pull request closed without merging**
