### PR TITLE
[WIP] Do not error out when running version.py on windows

### PR DESCRIPTION
**Pull request by xeacott**
## What does this PR do?
Fix running version.py from a windows environment.

### What issues does this PR fix or reference?
N/A

### Previous Behavior
```
λ python version.py
Traceback (most recent call last):
  File "version.py", line 15, in <module>
    from platform import linux_distribution as _deprecated_linux_distribution
ImportError: cannot import name 'linux_distribution'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "version.py", line 22, in <module>
    from distro import linux_distribution
ImportError: No module named 'distro'
```

### New Behavior
```
λ python version.py
2019.2.1-15-g8cb56bc
```

### Tests written?
Yes

### Commits signed with GPG?
No

### CODE REVIEW

**Review by cmcmarrow — APPROVED** [review]

**Review by marbx — COMMENTED** [review]
Isn't linux_distribution() called uncondtionally at line 636?

If yes, you would have make the call dependent on the OS, too.

**Comment by xeacott** [comment]
That call you mentioned @markuskramerIgitt is called conditionally.

**Review by marbx — APPROVED** [review]
Nice!

**Review by s0undt3ch — APPROVED** [review]

**Comment by xeacott** [comment]
Closing due to much larger changes to version.py that have occurred since this.

**Pull request closed without merging**
