### PR TITLE
Back-port #36257 to carbon

### PR DESCRIPTION
**Pull request by rallytime**
Back-port saltstack/salt#36257 to carbon

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Cool. Thanks.

**Pull request merged**
