### PR TITLE
Several Py3.10 Fixes & Git >=2.35.0 fix

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title.

### What issues does this PR fix or reference?
Closes #61686

### CODE REVIEW

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
Windows failures started at https://jenkins.saltproject.io/job/pr-windows-2016-x64-py3-pytest/job/master/1029 
The offending PR https://github.com/saltstack/salt/pull/61659

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Review by Ch3LL — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Review by MKLeb — APPROVED** [review]

**Review by waynew — APPROVED** [review]
Looks great, couple of questions but not blockers

**Pull request merged**
