### PR TITLE
[RC1 Sodium] Uncap msgpack version

### LINKED ISSUE #57536: [BUG] [RC1 Sodium] msgpack requirements are incorrectly pinned <1.0.0
**Description**

We've merged https://github.com/saltstack/salt/pull/57122 to support msgpack >=1.0, but our requirements files prevent installing with a greater msgpack.

We need to fix that.

### PR DESCRIPTION
**Pull request by aplanas**
### What does this PR do?

After merging PR#57122 we can install `msgpack` versions equal or bigger than 1.0.0

fixes #57536

### CODE REVIEW

**Comment by cmcmarrow** [comment]
rerun windows

**Comment by cmcmarrow** [comment]
re-run full windows

**Comment by dwoz** [comment]
re-run full all

**Review by cmcmarrow — APPROVED** [review]

**Comment by dwoz** [comment]
@aplanas @cmcmarrow I had to revert this change. I merged it before realizing the static requirement files hadn't been updated so the full test run didn't run with msgpack 1.0.0, I don't believe the full test suite passes when the static requirement files are updated.

**Comment by aplanas** [comment]
Well done, somehow I am not able to generate the static files for all the platform. The error that I have for darwin suggest that is expected to be running in darwin

For linux, funny enought, the final static still shows the old version of msgpack, as is also required by another package.

**Comment by prometheanfire** [comment]
can https://github.com/saltstack/salt/issues/57536 be reopened?

**Comment by prometheanfire** [comment]
what other requirement brought in 0.6.1?

**Comment by aplanas** [comment]
+msgpack==0.5.6            # via -r requirements/base.txt,
pytest-salt-factories

**Comment by cmcmarrow** [comment]
@prometheanfire for sure

**Comment by prometheanfire** [comment]
looks like that's a saltstack project

https://github.com/saltstack/pytest-salt-factories/blob/master/requirements/base.txt#L6

not sure what goes into managing it, but would need to be removed there as well.

codesearch on it shows little usage at least https://github.com/saltstack/pytest-salt-factories/search?q=msgpack&unscoped_q=msgpack

**Comment by s0undt3ch** [comment]
The `msgpack<1.0.0` on pytest-salt-factories has been lifted and a new release is done.
I believe @cmcmarrow is working on this.

**Comment by cmcmarrow** [comment]
@aplanas
We don’t see this as a bug because no platform “that we support” requires/uses msgpack 1.0.0 and no part of salt needs the upgrade. 
Why do you need msgpack 1.0.0? 
msgpack 1.0.0 is be worked on in #57571. We currently have 7 – 8 failing test.

**Pull request merged**
