### PR TITLE
Update debian systemd unit files to use default KillMode, Type=notify

### PR DESCRIPTION
**Pull request by terminalmage**
This was done for the rest of the unit files in https://github.com/saltstack/salt/pull/35577 but I did not realize we maintain separate unit files for Debian.

This incorporates #36806 from @l2ol33rt (which removes the use of `KillMode=process`), and also changes the unit type to `notify`.

@rallytime This will need to be backported to the 2015.8 branch.

### CODE REVIEW

**Comment by l2ol33rt** [comment]
@terminalmage I was trying these systemd service files out against `2016.3` branch (1284de2) and it looks like the `minion.service` doesnt want to start unless I add `NotifyAccess=all` to it:
```
● salt-minion.service - The Salt Minion daemon
   Loaded: loaded (/lib/systemd/system/salt-minion.service; enabled)
   Active: failed (Result: timeout) since Fri 2016-10-07 16:58:29 GMT; 2min 31s ago
  Process: 2461 ExecStart=/usr/lib/virtualenvs/salt/bin/salt-minion (code=exited, status=0/SUCCESS)
 Main PID: 2461 (code=exited, status=0/SUCCESS)

Oct 07 16:58:29 saltmaster systemd[1]: Failed to start The Salt Minion daemon.
Oct 07 16:58:29 saltmaster systemd[1]: Unit salt-minion.service entered failed state.
```

My working salt-minion.service file looks like:
```
[Unit]
Description=The Salt Minion daemon
After=network.target

[Service]
EnvironmentFile=/etc/default/salt-minion
Type=notify
LimitNOFILE=8192
ExecStart=/usr/lib/virtualenvs/salt/bin/salt-minion
NotifyAccess=all
Restart=$RESTART

[Install]
WantedBy=multi-user.target
```

Not sure if Im missing something, but figured Id let you know.

**Comment by terminalmage** [comment]
@l2ol33rt Thanks for the information. The code I added in the 2016.3 branch should be notifying the main PID, so this shouldn't be an issue, but there is a possibility that recently-modified code in the 2016.3 branch could be dropping that systemd notification into a different process. I will investigate.

**Comment by terminalmage** [comment]
@l2ol33rt I just checked the code at the head of the 2016.3 branch and this should not be happening, we do the notification as soon as the salt-minion script is started so it wouldn't have had time to fork its subprocesses yet. Maybe this is related to the way you're starting the minion? It doesn't look like that's the case though, I'm assuming that the path you're using in your unit file is the path to where the salt-minion command was installed within your virtualenv, right?

I did find something else that needed to be removed in the debian unit files, which I've just pushed a commit to handle, but I don't think this would have caused your issue. If you could test with the additional lines removed though, that would help rule it out.

**Comment by l2ol33rt** [comment]
@terminalmage appreciate you looking into this further! Ill try some more things on my end and see if I can figure out what's going on. And as far as starting the minion, thats correct. Its just pointing to the `salt-minion` command that was installed in the virtualenv.

**Comment by l2ol33rt** [comment]
@terminalmage Ok so after some digging here's what I found:

* The `salt-common_20163.3.3+ds-1_all.deb` has a dependency of `python-systemd` which does not get installed when I install salt into a virtualenv from git because its not in the `requirements.txt` for salt.
* In `process.py` there is a check to see if it can `import systemd.daemon` but falls back on the `systemd-notify` binary:
https://github.com/saltstack/salt/blob/2016.3/salt/utils/process.py#L54-L59 However, `systemd-notify` will refuse reception of status updates unless `NotifyAccess=all` is set for the service unit (which is the behaviour Im getting with the minion service timing out). This is according to the manpage for `systemd-notify`:
```
DESCRIPTION
        ....
        Note that systemd will refuse reception of status updates from this command unless NotifyAccess=all is set
       for the service unit this command is called from.
```

So setting `NotifyAccess=all` for the `salt-minion` service without installing `systemd-python`(pip pkg equivalent to python-systemd .deb pkg ) fixes the issue. Since this fallback to `systemd-notify` is already in `process.py` I think its best to ensure its working correctly by setting `NotifyAccess=all`. It should probably be set on the `salt-syndic` service unit as well. Im not sure if there are security implications with doing this but what do you think?


Just so you have it, the output from `pip freeze` with the virtualenv activated:
```
(salt) root@saltmaster:/vagrant# pip freeze
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
boto==2.40.0
boto3==1.3.1
botocore==1.4.60
certifi==2016.9.26
credstash==1.11.0
docker-py==1.8.1
docutils==0.12
futures==3.0.5
gitdb==0.6.4
GitPython==2.0.2
ipaddress==1.0.17
Jinja2==2.8
jmespath==0.9.0
MarkupSafe==0.23
msgpack-python==0.4.8
pycrypto==2.6.1
python-dateutil==2.5.3
PyYAML==3.12
pyzmq==15.4.0
requests==2.11.1
salt===2016.3.3-178-g0ccf789
singledispatch==3.4.0.3
six==1.10.0
smmap==0.9.0
tornado==4.4.2
websocket-client==0.37.0
```

**Comment by terminalmage** [comment]
Thanks a lot @l2ol33rt, I'll look into the potential security implications but I think you're probably right.

Really appreciate the investigative work. Seriously, thanks!

**Comment by terminalmage** [comment]
@l2ol33rt Sorry for the delay, I went ahead and made the edit in d83a187 and pushed the update to this PR.

Thanks again for your work in investigating this.

**Comment by l2ol33rt** [comment]
@terminalmage awesome! I'm glad I could help!

**Comment by terminalmage** [comment]
@l2ol33rt Is the commit message in d83a187 accurate, in your opinion, based on your investigation?

**Comment by l2ol33rt** [comment]
@terminalmage The first paragraph sounds good. Id change the second paragraph to something like the following since its not necessarily `virtualenv` specific but any kind of `pip` install:
```
The particular use case for this is when Salt is installed using pip. 
We don't put systemd-python into the requirements.txt
because we can't be sure that the minion supports systemd, so pip
installs won't necessarily have systemd-python available.
```

**Comment by terminalmage** [comment]
Good point. I amended the commit message, the new commit ID is fb6e545.

**Comment by l2ol33rt** [comment]
@terminalmage perfect :+1:

**Comment by cachedout** [comment]
For the comments, it sounds like the concerns have been resolved so I'll get this in. Thanks all!

**Pull request merged**
