### PR TITLE
Isbm disable custom roster for api 2016.11

### PR DESCRIPTION
**Pull request by isbm**
### What does this PR do?

Backport of https://github.com/saltstack/salt/pull/38596

### CODE REVIEW

**Comment by cachedout** [comment]
Backport? Wasn't the original also against develop?

**Comment by isbm** [comment]
Oh my. #facepalm.

**Comment by isbm** [comment]
@cachedout That's what happens when you're about to open a PR and your phone is ringing you have to be in 10 minutes picking up kids from the kindergarten/school... :cry:

**Comment by isbm** [comment]
@cachedout no idea why checks are stopped at the moment, but anyways, during making the original PR I simply mis-watched against what branch. Now should be all fine.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by isbm** [comment]
@cachedout Jenkins came... :smile:

**Comment by cachedout** [comment]
@isbm Looks like there is a merge conflict. Could you please rebase?

**Comment by isbm** [comment]
@cachedout boils down to a typo fix...

**Comment by cachedout** [comment]
@isbm Thank you for resolving the conflict. :]

**Pull request merged**
