### PR TITLE
lxc: add wrappers for cmd_run alike

### PR DESCRIPTION
**Pull request by kiorky**
cc @terminalmage

### CODE REVIEW

**Comment by terminalmage** [comment]
These wrappers aren't necessary. None of these functions exist prior to the 2015.2 branch when LXC was refactored. As this change was made prior to the final release of 2015.2.0, there is no reason to provide backwards compatibility, since this functions did not exist in any publicly-released version of Salt.

**Comment by kiorky** [comment]
they do not exists, but users can still have used them in the wild, both on develop; my fork; or in 2015.2 from github, this is not harmful, just a gain and a chance not to hardfail.

**Comment by terminalmage** [comment]
I'm not concerned with that. Code changes in the process of development. If these functions had existed in 2014.7.x, or this change was made after the release of 2015.2.0, then I would think this was necessary.

**Comment by kiorky** [comment]
You are not, but users which will get tracebacks or me are ;)

**Comment by terminalmage** [comment]
I don't consider these wrappers to be necessary for reasons I have already stated, but if we end up keeping the wrappers, then there's no reason for docstrings. We'd just update the test_valid_docs test to ignore them, and then hide the ``cmd_*`` function variants using sphinx' **exclude-members** directive. For example: https://raw.githubusercontent.com/saltstack/salt/develop/doc/ref/modules/all/salt.modules.lxc.rst

**Comment by kiorky** [comment]
Ok, yep i totally agree i was annoyed adding them, let me exclude them correctly.

**Comment by kiorky** [comment]
rebased on top of 2015.2

**Comment by kiorky** [comment]
strange, lint failures dont reflect my lxc.py !

**Comment by kiorky** [comment]
oh wait, no, i know pfff, will push a rebase.

**Comment by kiorky** [comment]
unrelated failure

**Comment by thatch45** [comment]
I am agreeing with @terminalmage and don't think we need these wrappers, it is just adding unneeded bloat to an otherwise already large module.

**Pull request closed without merging**
