### PR TITLE
[FEATURE] retcode passthrough exitstatus (take 3)

### PR DESCRIPTION
**Pull request by plastikos**
### What does this PR do?

It passes the `retcode` through to the `salt` and `salt-call` executable exit status.

This is a rebase of #35282
This no longer requires commit back-outs used in #35986 
### What issues does this PR fix or reference?
#18510
### Previous Behavior

The `retcode` from states was not reflected in the command line executable exit status
### New Behavior

Non-zero `retcode` from salt states is used for the exit status of `salt` and `salt-call` - unless a "higher priority" error occurs in the specific executables.
### Tests written?

Yes

### CODE REVIEW

**Comment by edgan** [comment]
I really want to see this happen. @plastikos If there is anyway I can help.

**Comment by plastikos** [comment]
@edgan , please test it and provide any feedback.  I am hopeful it will go in now that Carbon is branched (unfortunate that it didn't go in prior - but that ship has sailed).

Ultimately I'm waiting to hear from @cachedout - but he's likely snowed-under with work getting Carbon out rather than new P.R.s.

We'll see what happens.  (thanks for the "thumbs up")

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
Once this passes tests it can be merged, the code looks great!

**Comment by rallytime** [comment]
@plastikos Unfortunately, there are merge conflicts with this PR. Can you rebase it? Hopefully we can get this in really quickly once it is rebased so you don't have to keep re-doing this change.

@thatch45 and @cachedout let's all keep an eye on this so we can get it into develop when it's ready.

**Comment by thatch45** [comment]
Agreed, we really want it in, but we do need to pass tests first.

**Comment by rallytime** [comment]
Definitely. The PR tests are looking better in general than when they were running last week, so hopefully we can get some useful/good results.

**Comment by thatch45** [comment]
@rallytime if the tests pass I am willing to attempt a manual merge, so just ping me if they pass :)

**Comment by rallytime** [comment]
Ok, the Ubuntu build timed out after only running ~900 tests, but the CentOS build finished all ~5,000 and has 16 failures. These are largely in the pip state integration tests and the state module integration tests (plus some other one-off tests in other places). 

Here's a list of the test failures (build result is [here](https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/5441/#showFailuresLink)) in case the artifacts disappear before we all look at these again:
- unit.utils.schema_test.ConfigTestCase.test_ipv4_config_validation
- integration.modules.state.StateModuleTest.test_issue_2068_template_str
- integration.modules.state.StateModuleTest.test_onchanges_in_requisite
- integration.modules.state.StateModuleTest.test_onchanges_requisite
- integration.modules.state.StateModuleTest.test_onchanges_requisite_multiple
- unit.states.pip_test.PipStateTest.test_install_in_editable_mode
- unit.states.pip_test.PipStateTest.test_install_requirements_parsing
- integration.states.pip.PipStateTest.test_22359_pip_installed_unless_does_not_trigger_warnings
- integration.states.pip.PipStateTest.test_issue_2028_pip_installed_state
- integration.states.pip.PipStateTest.test_issue_6833_pip_upgrade_pip
- integration.states.pip.PipStateTest.test_issue_6912_wrong_owner
- integration.states.pip.PipStateTest.test_pip_installed_errors
- integration.states.pip.PipStateTest.test_pip_installed_removed
- integration.states.pip.PipStateTest.test_pip_installed_specific_env
- integration.states.pip.PipStateTest.test_pip_installed_weird_install
- unit.modules.rh_service_test.RhServiceTestCase.test_start

@plastikos If you aren't able to resolve these failures on your own, we'd be happy to sit down and go through these with you and help fix them up. Let us know if/when/how we can help!

**Comment by plastikos** [comment]
I'll get after this today and see what I can do.

**Comment by rallytime** [comment]
I'll close this in favor of #36577, but do note that all of the offers stated above still stand. Just let us know. :)

**Pull request closed without merging**
