### PR TITLE
Command logging output fixes

### PR DESCRIPTION
**Pull request by boltronics**
### What does this PR do?

Removes line breaks from various logging lines.
### What issues does this PR fix or reference?

https://github.com/saltstack/salt/issues/36102
### Previous Behavior

Lots of log lines broken up by unwanted newline characters, as per the issue above.
### New Behavior

Fixes all the state and cmdmod entries I came across.
### Tests written?

No

### CODE REVIEW

**Comment by cachedout** [comment]
@boltronics This failed some tests. Could you please have another look?

**Comment by boltronics** [comment]
It looks like the logged value of low['name'] does not have to be a string. I'll update my PR to add in an instance type check.

**Comment by boltronics** [comment]
I also added the angled brackets around the state for the "Executing state" line, which looks more consistent with the "Running state" and "Completed state" entries. Makes it easier to match up the log entries too IMO.

**Comment by boltronics** [comment]
@cachedout I'm not clear on what that ubuntu14 build failure is about. I'm guessing it's unrelated to my PR. Should I force-push my changes again?

**Comment by cachedout** [comment]
@boltronics Something else is going on there. Unrelated to your change. No need for you to do anything. Thanks.

**Comment by cachedout** [comment]
@boltronics Unfortunately this now has a merge conflict. (Sorry!) Would you mind rebasing it? Thanks very much.

**Comment by boltronics** [comment]
@cachedout Assuming the tests pass, that's done.

**Comment by cachedout** [comment]
@boltronics Many thanks. I'll have a look when the tests finish. I appreciate your quick response!

**Comment by boltronics** [comment]
Did I do that? :open_mouth:

**Comment by rallytime** [comment]
@boltronics Nah, that's on us and we need to get taht fixed.

Thank you for submitting this!

**Comment by boltronics** [comment]
No worries. Thanks!

**Comment by boltronics** [comment]
Hmm... it seemed to get merged in a weird way. It doesn't have my name in the commit message, and the commits got squashed into one. I don't mind too much, but I'm not sure if that was intentional. I do sign my commits since I think that's good practice, and squashing them destroys that.

**Comment by boltronics** [comment]
@rallytime Possible to get clarification? Curious if that was a mistake or intentional, and if there's something I should do in future to avoid it happening. Thanks.

**Comment by cachedout** [comment]
Hi @boltronics 

GitHub has started defaulting to squashed commits by default and we have followed suit. Here is their blog post: https://github.com/blog/2141-squash-your-commits

**Comment by boltronics** [comment]
That's a shame, since signed commits will always be broken for the project. However it doesn't explain why my name was scrubbed.

**Pull request merged**
