### PR TITLE
setup.py: Work around bad code in distutils

### PR DESCRIPTION
**Pull request by terminalmage**
While running an sdist, distutils logs when it creates paths. However, if the paths are unicode _and_ contain unicode code points, the log message results in a `UnicodeEncodeError` as distutils attempts to perform string replacement using a str format string and a unicode path.

Paths recently added in the test suite's files to test unicode compatibility have caused this issue to surface.

This fixes the resulting traceback by ensuring that Python 2 only passes utf-8 encoded bytestrings when making the release tree.

### CODE REVIEW

**Review by dmurphy18 — APPROVED** [review]
looks good

**Comment by rallytime** [comment]
@terminalmage Lint: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/19294/violations/file/setup.py/ :)

**Comment by terminalmage** [comment]
I disabled that check inline, WTF.

**Comment by terminalmage** [comment]
@rallytime I pushed a commit to get rid of the lint error.

**Pull request merged**
