### PR TITLE
Add the __sls__ field to the highstate output (the running dict)

### PR DESCRIPTION
**Pull request by whiteinge**
Request for comments:

There's a bunch of cool info in the running dictionary that is useful for summarizing a state run. I'd like to be able to show 'N states from M files' as well but I need the `__sls__` attribute from the low data to do that.

### CODE REVIEW

**Comment by cachedout** [comment]
Fine by me. @terminalmage or @thatch45 ?

**Comment by terminalmage** [comment]
This looks fine. I'll add that if we're using dict.get because we're not sure that the ``__sls__`` key will be in the low data, we'll need to properly handle checking the value wherever this data ends up being used, because attempting to reference it as a dictionary when it is ``None`` will raise an exception.

**Comment by whiteinge** [comment]
I'm not aware of any reason that __sls__won't be present but I'm using
.get() because Salt occasionally surprises me.

If present, the value will be a string. If not present falling back to null
strikes me as reasonable but we could default to an empty string if you
feel strongly about it. Nothing downstream is using this yet so we're free
to dictate the desired behavior.

**Comment by terminalmage** [comment]
I don't feel strongly, and figured nothing would be using this yet. Just wanted to bring up that wherever we end up using this, we need to account for the value potentially being ``None``, if it is left as-is. I don't have a problem with this, but deep-dark stuff like this is rarely documented so we should find a way to get it documented if possible so people who do use this information can write their code accordingly.

**Comment by lorengordon** [comment]
Would this close #9628?

**Comment by whiteinge** [comment]
Well that's interesting. Thanks for the find, @lorengordon.

This would indeed close that. But it looks like this was already in the running dictionary at some point. But it's not now. I wonder if that was an accident or if there's a reason.

**Comment by whiteinge** [comment]
Ah, I see now. It was added to the running dictionary only for some requisite failure conditions to make the error message more helpful. This PR adds it to the main running dict all the time.

**Comment by thatch45** [comment]
Looks great to me!

**Comment by cachedout** [comment]
@whiteinge Let me know if you want to implement the suggestions from Erik. Otherwise I will get this in.

**Comment by whiteinge** [comment]
I don't see any existing documentation for the running dictionary so I vote we handle that separately from this.

**Comment by whiteinge** [comment]
Actually, scratch that. I see a place to add an integration test for the running dictionary.

**Comment by whiteinge** [comment]
Huzzah. The running dictionary now has integration tests.

Turns out the `__sls__` field can indeed be none for `state.single`/`state.template_str` etc. Thanks for the suggestion, Erik.

**Comment by terminalmage** [comment]
No prob. I always try to think of the edge cases. :smile:

**Comment by whiteinge** [comment]
No, I'm saying thanks for pushing for adding docs (or tests as it turned out). It will be nice to have the running dict interface checked and enforced going forward.

**Comment by cachedout** [comment]
@whiteinge Some minor lint fixes and we'll be all set here! https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/7298/violations/file/tests/integration/modules/state.py/

**Comment by whiteinge** [comment]
Ah, isinstance is better here. Good rule.

**Pull request merged**
