### PR TITLE
add saltutil state to wrap saltutil.sync* modules

### PR DESCRIPTION
**Pull request by mchugh19**
### What does this PR do?
Adds saltutil state to wrap the `saltutil.sync_*` modules.

### What issues does this PR fix or reference?
#45264

### Previous Behavior
`salutil.sync-*` was run in states via `module.run`, and always ran and reported changes

### New Behavior
new saltutil.sync_* states properly report if changes occured supporting on_changes

### Tests written?
Yes

### CODE REVIEW

**Review by cachedout — APPROVED** [review]
This is a great idea. I like it.

**Comment by cachedout** [comment]
Looks like one of these tests does need a fixup though.

**Comment by mchugh19** [comment]
Corrected state and test

**Comment by max-arnold** [comment]
@mchugh19 Are `sync_matchers` and `sync_serializers` intentionally missing from the state module?

Also you may want to mention this state module here https://docs.saltstack.com/en/develop/topics/development/modules/#sync-via-the-saltutil-module (these docs were significantly improved in #50633).

**Comment by mchugh19** [comment]
Nope! I think they are new and didn't exist at the time. So they can be added anytime.

**Pull request merged**
