### PR TITLE
[3006.x] Fix 63920: Fix valuerror when destroying client 

### LINKED ISSUE #63920: [BUG] [3006] [3006.0rc2] file.managed gives ValueError: I/O operation on closed file on seccond state.apply
**Description**
ValueError: I/O operation on closed file when running state.apply with file.maged twice.

**Setup**
testing.sls
```
file_testing:
  file.managed:
    - name: /testing
    - contents: |
        testing
```

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**

```
$ sudo salt-call state.apply --output-diff testing
local:
----------
          ID: file_foobar
    Function: file.managed
        Name: /testing
      Result: True
     Comment: File /testing updated
     Started: 10:06:40.248795
    Duration: 14.089 ms
     Changes:   
              ----------
              diff:
                  New file

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  14.089 ms
```

run again
```
$ sudo salt-call state.apply --output-diff testing
local:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   7.983 ms
Exception ignored in: <function RemoteClient.__del__ at 0x7f95c57c3760>
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileclient.py", line 1142, in __del__
    self.destroy()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/fileclient.py", line 1157, in destroy
    channel.close()
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/asynchronous.py", line 105, in close
    io_loop.close(all_fds=True)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/ext/tornado/ioloop.py", line 718, in close
    self.remove_handler(self._waker.fileno())
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/ext/tornado/platform/posix.py", line 49, in fileno
    return self.reader.fileno()
ValueError: I/O operation on closed file
```

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3006.0rc2
 
Python Version:
        Python: 3.10.10 (main, Feb 23 2023, 05:21:34) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.7.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: centos 7 Core
        locale: utf-8
       machine: x86_64
       release: 3.10.0-1160.81.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core

```
</details>

**Additional context**
state.apply was run on the salt-master itself, salt-minion already running or not makes no difference.

### PR DESCRIPTION
**Pull request by Ch3LL**
### What does this PR do?
Properly closes the file client instead of relying on `__del__` 

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/63920

### Previous Behavior
ValueError when running salt-call with a file.managed state with contents

### New Behavior
No ValueError and the file client is cleaned up properly.

### CODE REVIEW

**Review by MKLeb — DISMISSED** [review]

**Comment by MKLeb** [comment]
Everything looks good so far.  One question, are there any tests that specifically test whether the file client is closed in any of the scenarios that this PR has altered to use the new context manager syntax?

**Review by s0undt3ch — DISMISSED** [review]
Approved, but @dwoz should have a final say in the merge decision.

**Review by twangboy — DISMISSED** [review]

**Review by dwoz — DISMISSED** [review]

**Comment by Ch3LL** [comment]
@MKLeb no, but I can add a test

**Comment by Ch3LL** [comment]
@MKLeb pushed up a test. Ready for your review.

**Review by MKLeb — APPROVED** [review]

**Pull request merged**
