### PR TITLE
SmartOS Esky: fix build version identification

### PR DESCRIPTION
**Pull request by nshalman**
"bdist" doesn't do the right thing in the absence of
version files produced by "sdist".
Run "sdist" then extract out the contents of the tarball
into place

### CODE REVIEW

**Comment by nshalman** [comment]
fixes SmartOS Esky build.

@jfindlay can find fresh 2014.7.1 build products available from:
http://us-east.manta.joyent.com/nahamu/public/salt/salt-2014.7.1-esky-smartos.tar.gz
http://us-east.manta.joyent.com/nahamu/public/salt/salt-2014.7.1.solaris-2_11-i86pc_64bit.zip

Backport PRs to follow.

**Comment by nshalman** [comment]
Also, @cro should probably be made aware of this commit as well.

**Comment by jfindlay** [comment]
@nshalman, in our git setup, you only need to submit a pull request containing the fix against the oldest branch having the problem and within a day or two, all changes are merged forward from older to newer branches, so it is not necessary to create duplicate patches separately for each branch.

**Comment by nshalman** [comment]
@jfindlay I'm glad to hear that as it wasn't always the case. I will certainly make my pull requests that way going forward.

**Comment by nshalman** [comment]
This will get fixed everywhere when #19937 gets merged.

**Pull request closed without merging**
