### PR TITLE
More Py3 Fixes

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by cachedout** [comment]
@s0undt3ch Some lint errors and I think one failing test here.

**Comment by s0undt3ch** [comment]
Let's see what Jenkins tells us now.

**Comment by damon-atkins** [comment]
Guys, I can not understand why your not using #37692 `unicode_literals`  as the current  path is creating differences.   The idea of  unicode_literals is to keep the code path the same as much as possible.

Once unicode_literals is in use, only the external outputs and inputs need to be adjusted.  
When PY2 dies one day, your going to have a heap of code to remove everywhere

A lot of the code seems to be PY2 is normal and PY3 is the exception.

PY3 is the future. So the code should be PY3 is normal and PY2 is the exception. Which means a slight different way of coding.

This is an example of wrong future direction.
```
+        if data and six.PY3 and not salt.utils.is_bin_file(fpath):
 +            data = data.decode(__salt_system_encoding__)
```

ping @thatch45

**Comment by s0undt3ch** [comment]
@damon-atkins: While I agree that using unicode literals will make the code eventually cleaner, this will also mean changing ALL of salt's modules which can introduce some hard to find bugs with subtle nuances on string handling, see [the against perspective here](http://python-future.org/unicode_literals.html#against-unicode-literals). We're a python 2 project trying to bring python 3 compatibility in. If it was the other way around, unicode literals would be the number one choice.

Additionally, we already know that our test suite passes(most of it unless we're releasing and in such case, all of it) on Python 2, just not on Python 3.
If we use the unicode literals approach, out test suite will most likely fail under both Python 2 and Python 3 until we fix all of our string handling code which has been written from the ground up thinking on Python 2(and we weren't event passing around strings internally as unicode making this task even harder).

So, we should consider this Py3 effort as the first stage into Python 3 compatibility. Once this is done and we know our test suite works and passes for both python 2 and 3, we can probably start working on migrating to unicode literals at a slower pace knowing that we won't break all of our code, just, probably, parts of it, making it simpler to fix.
And yes, this will multiply the amount of work required.

**Comment by damon-atkins** [comment]
The win package and win register are using Unicode_literals and some other windows modules They always return Unicode, but except non-Unicode in as well, as the salt core is non-Unicode.

Here is a large project which went from PY2 to PY3 which shows how they did it.
https://docs.djangoproject.com/en/1.10/topics/python3/ link was also in  #37692 


In PY3 all your outputs will be Unicode, you still need someone to check each module to see if that is suitable for the function. e.g some API might not except Unicode.  The effort is the same. Its a false sense of security not to check the output of every module.  This is why `unicode_literals` should be used with a long release date for the next release, with many beta releases.  It would be worth the effort.

 unicode_literals you can make PY2 and PY3 code better.

I once comment on some PY3 code change and said

If you test for PY3 then you will also need to add test for PY4

```
if PY3 or PY4  do this
else this 
```
vs
```
if PY2 do this
else all other newer versions of python.
```

Salt needs to support more languages than ASCII,  you can have multiple languages in use on a Windows..

**Comment by cachedout** [comment]
@s0undt3ch Merge conflict here I'm afraid.

**Comment by s0undt3ch** [comment]
Rebased. Let's see what Jenkins has to say about this now.

**Pull request merged**
