### PR TITLE
Support passing a saltenv to slsutil.renderer

### PR DESCRIPTION
**Pull request by ghost**
### What does this PR do?

There is currently no way to use the module function `slsutil.renderer` for rendering files available on the salts fileserver, which are not available on the base environment, as the parameter for the saltenv is not passed to the method providing the file from the salt fileserver. 

### What issues does this PR fix or reference?

Not filed

### Previous Behavior
```
salt '*' slsutil.renderer salt://path/to/file
salt '*' slsutil.renderer salt://path/to/file saltenv=banana
```
Both render `salt://path/to/file` from the base environment

### New Behavior
```
salt '*' slsutil.renderer salt://path/to/file
salt '*' slsutil.renderer salt://path/to/file saltenv=banana
```
The first call renders the file `salt://path/to/file` available on the `saltenv=base` while the latter renders the file from the `saltenv=banana`

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by twangboy — APPROVED** [review]

**Comment by afischer-opentext-com** [comment]
What is needed to remove this forward?

**Comment by afischer-opentext-com** [comment]
@twangboy, what can I do to increase likelyhood of a merge approval? The last failing test looks like a new test issue (slack integration).

**Comment by max-arnold** [comment]
@waynew Could you please backport this PR to master branch?

**Comment by max-arnold** [comment]
Master backport: https://github.com/saltstack/salt/pull/55723

**Pull request merged**
