### PR TITLE
Use OrderedSet instead of set to allow handling of OpenLDAP X-ORDERED…

### PR DESCRIPTION
**Pull request by pwdng**
… attributes.

### What does this PR do?
Allow handling of OpenLDAP X-ORDERED attributes

### Previous Behavior
Attributes of type X-ORDERED would be sent in the wrong order

### New Behavior
Attributes of type X-ORDERED are sent correctly

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by pwdng** [comment]
Any feedback on this?

**Comment by cachedout** [comment]
@pwdng Apologies for the delay. I have asked @cro to look at this today.

**Review by cro — APPROVED** [review]
Nice clean code, thank you for the tests!

**Review by cachedout — APPROVED** [review]

**Pull request merged**
