### PR TITLE
Runner command

### PR DESCRIPTION
**Pull request by pass-by-value**
### What does this PR do?

Adds code to encapsulate invocations to salt's python clients. This only covers the `RunnerClient` for now. Will add support for others (depending on how this goes).

Example usage:

``` python
from salt.command import get_command_for_low_data, APIClient

low = {
 ...snip
}
command = get_command_for_low_data(low)  # low is the dictionary with salt's low data
APIClient.submit(command)  # calls runner client
```
### What issues does this PR fix or reference?

This references the feature #32778
### Previous Behavior

``` python
from salt.runner import RunnerClient

low = {
 ...snip
}

opts = ...

client = RunnerClient(opts)  # could be WheelClient or LocalClient as well

client.cmd_sync(low)  # cmd_async is also an option
```
### New Behavior

``` python
from salt.command import get_command_for_low_data, APIClient

# low is the dictionary with salt's low data
low = {
 ...snip
}

command = get_command_for_low_data(low)  # let the code figure out what client to instantiate
APIClient.submit(command)  # calls runner client's cmd_sync (or cmd_async) method, depending on what low data was passed in. No need to be aware of the internal implementation.
```
### Tests written?

Yes, there are unit tests for the code.
Look at notes for info about integration tests.
### Notes:

This isn't yet integrated into the code base (there are no places in the code that make use of this functionality). 

The reasons are
- This is still experimental. (Feedback is appreciated!). Let's check if this is useful before integrating this with the code base.
- Some efforts might still be required to make sure that `WheelClient` class can be called with args and kwargs. Once that is in place I'll write the `Receiver` and concrete command for `WheelClient`.
- Need to write the `Receiver` and concrete command for Local Client.
  Once the above are satisfied we can start to integrate this.

### CODE REVIEW

**Comment by cachedout** [comment]
Hmm, interesting.

I'm not totally sold on the benefit here. It feels a little bit like we're just shifting the workload around.

In your examples above, you reference a `get_command_for_low_data(low)` which it sounds like to me just determines which back-end client to use but then passes this data into a single, known interface abstracted out as `APIClient` which then does the work of actually instantiating that client and doing the work and returning it. I think my concern is that there just doesn't feel like there's all that much benefit to a unified interface if we have to tell that interface which back-end client we want anyway, since it's not really that much work to create that client in the caller itself.

I think I'd be more inclined toward this if the APIClient could figure out which back-end to use on its own, but absent that, I'm not a terribly big fan of adding another abstraction layer if there isn't a clear benefit.

Totally possible that I'm missing a huge benefit here though. Is the thinking that there should be a set of known-methods across all clients that one can always call? If that's the case, would writing an ABC or mixin that those clients all share make sense? (IIRC, we do this in some clients already.)

Anyhow, that's my initial feedback. I'm sure that there is a use case here that I'm just not seeing, so I'd like to continue the discussion and bring in others.

cc: @thatch45 @s0undt3ch @terminalmage @rallytime @DmitryKuzmenko

**Comment by whiteinge** [comment]
The primary reason for a single interface IMO, is that all the existing interfaces have different semantics and syntax for class instantiation (getting opts), different syntax for calling the local methods, different syntax for passing arguments to the ultimate function, and different semantics on whether eauth is enforced or even consulted. (I should detail all this in the issue referenced above.) It's impossible to keep the differences in your head -- I can't, anyway.

Adi and I discussed adding a method that takes a single low data payload and instantiates the correct backend transparently. (NetapiClient does this.) It would be a good addition and probably the one most commonly called by users when the additional proposed functionality of the "command patten" isn't needed (like queuing).

All that said, it's very important we go slow and get this interface right. Because we've got such a problem with interface drift if this addition doesn't help it's only adding to the problem.

**Comment by cachedout** [comment]
In that case, this sort of feels like covering up some bad design decisions with some wallpaper. Have we investigated the possibility of simply unifying the various client interfaces underneath the umbrella of a single parent class which enforces an interface? (Preserving backward compatibility, in theory.) ;] I just feel like this wrapper approach moves us further down the road away from the proper solution in a way.

**Comment by whiteinge** [comment]
The current state of all the *client interfaces is the usual: organic growth over time -- different authors with differing needs.

> unifying the various client interfaces underneath the umbrella of a single parent class which enforces an interface

I could be convinced. A benefit of the facade/command pattern approach is that it gives us a single place to declare which interfaces are public and which are not. The classes behind that can change their implementations/internals so long as the public interface is stable.

LocalClient is a good example: If we were to add an ABC that enforces an interface and add LocalClient to inherit from that, then instances would still be chock-full of all the historical, overlapping *cmd and *returns methods. We can document that they're not intended to be public but that feels a bit like pulling the rug out because they're still plenty visible and we've never weighed in on whether those should be consumed by users or not. In fact they were added in the first place instead of being replaced because we didn't know if they were being used or not -- this was long before we had a deprecation policy. We could start deprecating them now and renaming private methods into `_<private>` variants.

Part of me likes the smaller surface area of cleaning, updating, and fixing the existing *client interfaces;
Part of me likes the flexibility of having a single place in Salt with a declared, understood, public interface and letting the various *client interfaces do whatever they need or want to do (meaning transitioning away from Local/Runner/Wheel/NetapiClient being the public interface).

**Comment by cachedout** [comment]
I think your analysis of the pros and cons is excellent. This is a high-level project direction question at this point.

I'm summoning @thatch45

**Comment by thatch45** [comment]
I am just plain out of time today, if I don't have an answer for this by Monday remind me and I will come back when I have the time to really study this out.

**Comment by whiteinge** [comment]
I updated the issue description in #32778 with a matrix of all the existing client interfaces and the common/overlapping features that each one has.

**Comment by whiteinge** [comment]
Another consideration (mentioned at SaltConf by @jacksontj) is now that we can support coroutines, perhaps we should make a single coroutine interface then add simple sync/async wrapper methods.

**Comment by pass-by-value** [comment]
Completely agree with you guys in that we need to analyze benefit before adding this in. Having no abstraction at all is better than applying the wrong pattern.

IMO we need to consider a `Command` abstraction as separate from `Clients`.

 Some reasons we might need commands:
* When executing commands users wouldn't have to commit low data keys to memory. Command classes like `RunnerCommand`, `WheelCommand`, `MinionCommand` (and others) expose required keys as keyword arguments. That way users get tab completion / ide help etc.
* Addition of new command types. These can also be composite types (composed of existing types, perhaps). One example I can think of is when we used to make calls to runners and use the returned result to execute commands on minions (but that whole sequence was one "unit" of work for us).
* Users get to think in terms of commands, which seems closer to their objective of executing commands programmatically. (As a contrived example, if tomorrow the WheelClient starts executing LocalClient's commands an end user shouldn't need to update their code).

It was a mistake on my part to name the class APIClient as `APIClient`. That piece of code is really an `Invoker`. (Client being the calling code - according to the command pattern at least).

The expected sequence of events (for this command pattern implementation) is:
1. User creates an instance of `Command` (they'll explicitly create a command type like runner, wheel, local etc)
2. User submits the command by calling `submit` on the `Invoker`.
3. `Invoker` calls `execute` on the `Command` (it can also add the command to a queue, it doesn't atm).
4. Command's `execute` then calls `action` on the `Receiver`. The `action` method is the one responsible for doing the actual work. The `Receiver` is the only one that knows how to get the work done.

I agree with @cachedout in that we don't need to add a "wallpaper" on top of existing implementations. I feel that the Receivers should allow us to share common functionality while revisiting any design decisions.

> I think I'd be more inclined toward this if the APIClient could figure out which back-end to use on its own, but absent that, I'm not a terribly big fan of adding another abstraction layer if there isn't a clear benefit.

The reason I added the `get_command_for_low_data(low)` is because `NetAPIClient`s accept low data as a dict and some way is required to go from that to an instance of `Command`.
However, it makes me nervous to have the Invoker figure out what to call by looking at the low data. The reason being, if any changes are made to any clients the Invoker will probably also need to be updated (since it would end up knowing about all of them).

**Comment by whiteinge** [comment]
> However, it makes me nervous to have the Invoker figure out what to call by looking at the low data.

Could you go into more detail on this? Say changes are made to one of the clients like you mentioned, how would executing lowdata vs. command/invoker differ before and after the client change?

**Comment by jacksontj** [comment]
To clarify some, my main point when talking about a unified interface was not intended to say that all subsystems of salt must have the same interface, but that a given subsystem of salt should have one good interface (today we have ~3-4 depending).

I think we'll want to probably tackle the clients separately since they are different (although some such as runner, wheel, etc. are the same). I'd really like to focus on the client experience using the API-- to make it feel very "pythonic"-- and this one seems less so.

**Comment by cachedout** [comment]
+1 to the comments from @jacksontj . Agreed on all counts.

**Comment by thatch45** [comment]
Yes, while I agree on unification, I also agree with @jacksontj here, this feels clunky and forced, also, we have started to make unified interfaces before but never finished, I don't want to just start again and not finish either

**Comment by cachedout** [comment]
I think it's clear at this point that we aren't going to merge this as it sits. I'm going to mark the PR as closed. By all means, let's continue the discussion though.

**Pull request closed without merging**
