### PR TITLE
[DOC] Link cache module index to its topic

### PR DESCRIPTION
**Pull request by marbx**
### What does this PR do?
Links the cache module index to the cache topic, as discussed in https://github.com/saltstack/salt/issues/60280 with @sagetherage

### CODE REVIEW

**Review by twangboy — DISMISSED** [review]

**Review by sagetherage — DISMISSED** [review]

**Review by xeacott — DISMISSED** [review]

**Comment by xeacott** [comment]
Checked out the failure, perhaps there was another test that was added in the testware that is not cleaning up after itself. I ran that test locally, and it passes the first time, however continue to fail because it cannot remove:
`C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\salt-tests-tmpdir/package.accept_keywords`

however, `package.accept_keywords` is a dir anyways, and if we are passing that path as an argument to (which it appears we are from the test's output...)
```
with salt.utils.files.fopen(path, "a") as fh:
```
we'd see the same error -> PermissionError: [Errno 13] Permission denied

**Comment by marbx** [comment]
The failing test is for the [portage_config. module](https://docs.saltproject.io/en/latest/ref/states/all/salt.states.portage_config.html) which has the description "A state module to manage Portage configuration on Gentoo"

Could you please disable this test on all platforms other than Gentoo?

Some module have a "platform" token. I think that these tokens should be mandatory.

**Comment by marbx** [comment]
Only saw PR #60457  after the comment :-)

**Comment by xeacott** [comment]
> Only saw PR #60457 after the comment :-)

Yep! Going to get that fast-tracked.

**Comment by marbx** [comment]
This request started with a single commit adding line 7 to `doc/ref/cache/all/index.rst`

    For understanding and usage of the cache modules see the :ref:`cache` topic.

These line is already merged in PR #60282 (because I mistakenly used the master branch).

Therefore I close this PR. 

### Please help me to better understand Git

This PR now contains 30 commits, and I don't want "to merge 30 commits" (as written in the top):
- why the other commits appear in this commit?
- how can I prevent that in the future? Is working from a separate branch enough?

**Pull request closed without merging**
