### PR TITLE
Make DaemonMixin subclass PidfileMixin and move check_running to DaemonMixin

### PR DESCRIPTION
**Pull request by s0undt3ch**
The pidfile and daemon mixins only make sense together, so, they are now
one and only DaemonMixin needs to be passed as a subclass. Additionally,
it only makes sense that a parser inheriting from DaemonMixin needs to have
access to `check_running`, not just a subset of our daemons.

PidfileMixin is left for backwards compat.

Finally, before trying to read a pidfile, make sure it exists first.

@cachedout we probably didn't see this before because pidfiles are left behind, and because our test suite does not start our daemons from CLI, it uses multiprocessing processes...

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Bonus: Make sure we clean up pidfiles on exit

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@s0undt3ch Looks like one lint error?

**Comment by s0undt3ch** [comment]
Lint? where?

**Comment by cachedout** [comment]
@s0undt3ch My bad. It was failing and now it's not. Gremlins.

**Pull request merged**
