### PR TITLE
Cache the napalm object and fetched grains separately

### LINKED ISSUE #39983: Missing napalm grains in develop
### Some default grains are missing in napalm in develop branch

Most notably, in "develop", "os" is reported as None when testing both vEOS and vSRX.

### Setup
Provisioned new salt master with Vagrant salt provisioner, install "git", source "develop"

### Steps to Reproduce Issue
Configure napalm proxy for vEOS device and retrieve grains.

### Output from "stable":
```
[root@saltmaster:~] # salt --versions-report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-110-generic
         system: Linux
        version: Ubuntu 14.04 trusty

[root@saltmaster:~] # salt veos1 grains.items
veos1:
    ----------
    cpuarch:
        x86_64
    dns:
        ----------
        domain:
        ip4_nameservers:
            - 10.0.2.3
        ip6_nameservers:
        nameservers:
            - 10.0.2.3
        options:
        search:
        sortlist:
    gpus:
    hwaddr_interfaces:
        ----------
        eth0:
            08:00:27:41:9a:fb
        eth1:
            08:00:27:90:55:63
        lo:
            00:00:00:00:00:00
    id:
        veos1.trading.imc.intra
    interfaces:
        - Ethernet1
        - Management1
    kernel:
        proxy
    kernelrelease:
        proxy
    locale_info:
        ----------
    machine_id:
        6d8476cdd65de59207caf74f58b883d8
    master:
        localhost
    mem_total:
        0
    model:
        vEOS
    nodename:
        saltmaster
    num_gpus:
        0
    os:
        eos
    os_family:
        proxy
    osarch:
        x86_64
    osfinger:
        proxy-proxy
    osfullname:
        proxy
    osmajorrelease:
        proxy
    osrelease:
        proxy
    osrelease_info:
        - proxy
    path:
        /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
    ps:
        ps -efH
    pythonexecutable:
        /usr/bin/python
    pythonpath:
        - /usr/bin
        - /root/src/napalm-eos
        - /root/src/aclgen
        - /usr/lib/python2.7
        - /usr/lib/python2.7/plat-x86_64-linux-gnu
        - /usr/lib/python2.7/lib-tk
        - /usr/lib/python2.7/lib-old
        - /usr/lib/python2.7/lib-dynload
        - /usr/local/lib/python2.7/dist-packages
        - /usr/lib/python2.7/dist-packages
        - /usr/lib/python2.7/dist-packages/git/ext/gitdb
        - /usr/lib/python2.7/dist-packages/gitdb/ext/async
        - /usr/lib/python2.7/dist-packages/gitdb/ext/smmap
    pythonversion:
        - 2
        - 7
        - 6
        - final
        - 0
    saltpath:
        /usr/lib/python2.7/dist-packages/salt
    saltversion:
        2016.11.3
    saltversioninfo:
        - 2016
        - 11
        - 3
        - 0
    serial:
    uptime:
        92092
    vendor:
        Arista
    version:
        4.16.9M-3799680.4169M
    virtual:
        VirtualBox
    zmqversion:
        4.0.5
```

### Output from "develop"
```
[root@saltmaster:~] 1 # salt --versions-report
Salt Version:
           Salt: 2016.11.0-965-g0b8a9c4
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-110-generic
         system: Linux
        version: Ubuntu 14.04 trusty
[root@saltmaster:~] # salt veos1 grains.items
veos1:
    ----------
    cpuarch:
        x86_64
    dns:
        ----------
        domain:
        ip4_nameservers:
            - 10.0.2.3
        ip6_nameservers:
        nameservers:
            - 10.0.2.3
        options:
        search:
        sortlist:
    gpus:
    host:
        None
    hostname:
        veos1
    hwaddr_interfaces:
        ----------
        eth0:
            08:00:27:41:9a:fb
        eth1:
            08:00:27:27:fd:92
        lo:
            00:00:00:00:00:00
    id:
        veos1
    interfaces:
        - Ethernet1
        - Management1
    kernel:
        proxy
    kernelrelease:
        proxy
    locale_info:
        ----------
    machine_id:
        6d8476cdd65de59207caf74f58b883d8
    master:
        localhost
    mem_total:
        0
    model:
        vEOS
    nodename:
        saltmaster
    num_gpus:
        0
    optional_args:
        ----------
        config_lock:
            False
    os:
        None
    os_family:
        proxy
    osarch:
        x86_64
    osfinger:
        proxy-proxy
    osfullname:
        proxy
    osmajorrelease:
        proxy
    osrelease:
        proxy
    osrelease_info:
        - proxy
    path:
        /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
    ps:
        ps -efHww
    pythonexecutable:
        /usr/bin/python
    pythonpath:
        - /usr/bin
        - /root/src/napalm-eos
        - /root/src/aclgen
        - /usr/lib/python2.7
        - /usr/lib/python2.7/plat-x86_64-linux-gnu
        - /usr/lib/python2.7/lib-tk
        - /usr/lib/python2.7/lib-old
        - /usr/lib/python2.7/lib-dynload
        - /usr/local/lib/python2.7/dist-packages
        - /usr/lib/python2.7/dist-packages
    pythonversion:
        - 2
        - 7
        - 6
        - final
        - 0
    saltpath:
        /usr/lib/python2.7/dist-packages/salt
    saltversion:
        2016.11.0-965-g0b8a9c4
    saltversioninfo:
        - 2016
        - 11
        - 0
        - 0
    serial:
    uptime:
        92910
    username:
        admin
    vendor:
        Arista
    version:
        4.16.9M-3799680.4169M
    virtual:
        VirtualBox
    zmqversion:
        4.0.5
```

### PR DESCRIPTION
**Pull request by mirceaulinic**
### What issues does this PR fix or reference?

Closes #39983

### Previous Behavior

It cached grains object and device details at the firs call. It worked fine when the function providing the `os` grain was called `os`. But the function name has been changes pretty recently to `getos` which is actually the first function loaded under this module. Therefore the napalm object was not available up to that point, hence the `os` and `host` grains disappeared.

### New Behavior

Separate cache fetch of the network devices and of the grains retrieved from the NAPALM's `get_facts`, without extra load.

### CODE REVIEW

**Comment by mirceaulinic** [comment]
@bewing would you mind testing this branch again and see if it's still good in your environment. I pushed some more changes.

**Comment by bewing** [comment]
Sanity check may be needed -- It's showing config_lock as false, when it's not an option for the EOS driver.

```
[root@saltmaster:~] # salt --versions-report
Salt Version:
           Salt: 2016.11.0-970-gff7be3a
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-110-generic
         system: Linux
        version: Ubuntu 14.04 trusty
 
[root@saltmaster:~] # salt veos1 grains.items
veos1:
    ----------
    cpuarch:
        x86_64
    dns:
        ----------
        domain:
        ip4_nameservers:
            - 10.0.2.3
        ip6_nameservers:
        nameservers:
            - 10.0.2.3
        options:
        search:
        sortlist:
    gpus:
    host:
        veos1
    hostname:
        veos1
    hwaddr_interfaces:
        ----------
        eth0:
            08:00:27:41:9a:fb
        eth1:
            08:00:27:89:eb:b0
        lo:
            00:00:00:00:00:00
    id:
        veos1
    interfaces:
        - Ethernet1
        - Management1
    kernel:
        proxy
    kernelrelease:
        proxy
    locale_info:
        ----------
    machine_id:
        6d8476cdd65de59207caf74f58b883d8
    master:
        localhost
    mem_total:
        0
    model:
        vEOS
    nodename:
        saltmaster
    num_gpus:
        0
    optional_args:
        ----------
        config_lock:
            False
    os:
        eos
    os_family:
        proxy
    osarch:
        x86_64
    osfinger:
        proxy-proxy
    osfullname:
        proxy
    osmajorrelease:
        proxy
    osrelease:
        proxy
    osrelease_info:
        - proxy
    path:
        /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
    ps:
        ps -efHww
    pythonexecutable:
        /usr/bin/python
    pythonpath:
        - /usr/bin
        - /root/src/napalm-eos
        - /root/src/aclgen
        - /usr/lib/python2.7
        - /usr/lib/python2.7/plat-x86_64-linux-gnu
        - /usr/lib/python2.7/lib-tk
        - /usr/lib/python2.7/lib-old
        - /usr/lib/python2.7/lib-dynload
        - /usr/local/lib/python2.7/dist-packages
        - /usr/lib/python2.7/dist-packages
    pythonversion:
        - 2
        - 7
        - 6
        - final
        - 0
    saltpath:
        /usr/lib/python2.7/dist-packages/salt
    saltversion:
        2016.11.0-970-gff7be3a
    saltversioninfo:
        - 2016
        - 11
        - 0
        - 0
    serial:
    uptime:
        114804
    username:
        admin
    vendor:
        Arista
    version:
        4.16.9M-3799680.4169M
    virtual:
        VirtualBox
    zmqversion:
        4.0.5
```

**Comment by mirceaulinic** [comment]
That's fine @bewing, for the moment it should not be a concern. The optional args are filtered before returned, to avoid sensible data.
The `config_lock` is set to `False` by default, for all drivers as some NAPALM drivers default it to `True`. This will be changed pretty soon, and that grains removed later.

**Review by rallytime — APPROVED** [review]
Thanks @mirceaulinic this looks good.

**Pull request merged**
