### PR TITLE
k8s namespace and secrets management

### PR DESCRIPTION
**Pull request by onorua**
### What does this PR do?

adds support for kuberenetes namespaces and secrets 
I've also removed `requests` dependency
### Previous Behavior

only node labels were supported 
### New Behavior

add Secret and Namespace
delete/update Secrets
get Secrets and Namespaces
### Tests written?
- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by cachedout** [comment]
These tests looks like the require a local Kubernetes installation? Is that correct?

**Comment by onorua** [comment]
yeah, do you want me to add skip for them? I was thinking of it, but decided to check what would you prefer - local kubernetes installation or skip for the tests or maybe some changes to the tests

**Comment by cachedout** [comment]
Please add a skip for them if it's not installed. Thanks.

**Comment by rallytime** [comment]
FYI @jtand

**Comment by onorua** [comment]
done

**Comment by cachedout** [comment]
@onorua Will what's in `salt.utils.dictdiffer` meet your needs?

**Comment by cachedout** [comment]
We just need these lint errors cleaned up and then we can get this in. Thanks! http://166.78.178.63:8080/job/PR/job/salt-pr-lint-n/382/violations/

**Comment by cachedout** [comment]
@onorua Just a bump to see if you saw the above comments?

**Pull request merged**
