### PR TITLE
Surpress boto WARNING during SQS msg decode in sqs_engine

### PR DESCRIPTION
**Pull request by Quarky9**
### What does this PR do?
Surpress boto WARNING during decode

### What issues does this PR fix or reference?
reference: https://github.com/boto/boto/issues/2965

### Previous Behavior
Salt master Log messages e.g.:
2018-01-29 21:48:16,500 [boto             ][WARNING ][9278] Unable to decode message

### New Behavior
No more logs

### Tests written?
No

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by garethgreenaway — APPROVED** [review]

**Comment by rallytime** [comment]
Thanks @Quarky9!

**Comment by danlsgiga** [comment]
Is it possible to backport this fix to 2017.7?

**Comment by rallytime** [comment]
@danlsgiga Yeah, I'll mark it for back-porting. Thanks!

**Comment by danlsgiga** [comment]
Fantastic!!! Thanks @rallytime

**Pull request merged**
