### PR TITLE
INFRA-4506 - various fixes as detailed below

### PR DESCRIPTION
**Pull request by tkwilliams**
- utils/boto3.py:
  - \_ordered() -> ordered() because this function is generally useful
- modules/boto_asg.py:
  - update() was not deleting tags NOT in the requested list, leading to non-idempotent runs
- states/boto_asg.py:
  - update test=True code to provide details of proposed changes when an update is indicated
  - replace \_recursive_compare() with \_\_utils__['boto3.json_objs_equal'] and / or \_\_utils__['boto3.ordered']
- states/boto_s3_bucket.py:
  - \_compare_policy() was not reliable, leading to unneeded policy updates, fix so updates can be idempotent
  - update test=True code to provide details of proposed changes when an update is indicated

### CODE REVIEW

**Comment by tkwilliams** [comment]
Hrm.  I don't understand the testing framework well enough to know how to fix the failing unit test.

The code in the module works flawlessly (e.g. \_\_utils__ is available at runtime) but I have no clue why \_\_utils__ would NOT be available within the unit test..

Any thoughts or pointers would be extra-awesome :)

**Comment by tkwilliams** [comment]
@rallytime Any thoughts on how to approach the above unit test?  The code itself runs brilliantly, but for some reason even though __utils__ is available at runtime, it doesn't seem to be during the test, which causes it to fail on the same code that works live.... :-/

**Comment by rallytime** [comment]
@tkwilliams Yeah, I can take a look here for sure. I'll do that right now. It looks like there are couple of related pylint failures. (Hard to see since that run went a little sideways.) I'll grab those as well while I am in here.

Once I have the test fixed up, I'll submit a PR to your branch for you to review. Sound good?

**Comment by tkwilliams** [comment]
Extra-swell!  Thanks - I'll eyeball it when you're done so I have more of a clue next time :)

**Comment by rallytime** [comment]
@tkwilliams I made a PR against your branch here: https://github.com/bodhi-space/salt/pull/1

If you merge that in, this PR will be automatically updated and the tests will begin again. Let me know if you have any questions, or need me to do this differently.

**Review by rallytime — APPROVED** [review]

**Pull request merged**
