### PR TITLE
Unit test to require execution module documentation

### PR DESCRIPTION
**Pull request by mchugh19**
### What does this PR do?
Adds unit test to validate that salt module, state, returners, wheel, etc files have a matching rst in docs and checks that doc rst files have matching py.
Also adds missing docs so that the tests pass

### Previous Behavior
Modules could be added without documentation link

### New Behavior
Unit test will catch that modules do not have associated docs
```
python tests\runtests.py -n unit.test_doc.DocTestCase.test_states_doc_files

AssertionError: 'zabbix_usermacro' not found in ['acme', 'alias', '...
'zone', 'zookeeper', 'zpool'] : State file zabbix_usermacro is missing documentation in ...salt/doc/ref/states/all
```

### Tests written?
Yes

### Commits signed with GPG?
No

### CODE REVIEW

**Review by waynew — APPROVED** [review]
Nice! I :heart: better docs!

**Comment by waynew** [comment]
```02:09:36 Warning, treated as error:
02:09:36 /var/jenkins/workspace/pr-doc_PR-52368-YBQWFDKYTXAEE66QNONYBROXKZYDY3U4XQ4FDLNWAOWZLXEJGTKA/salt/states/azurearm_dns.py:docstring of salt.states.azurearm_dns:22:Field list ends without a blank line; unexpected unindent.
02:09:36 make: *** [html] Error 2
02:09:36 make: Leaving directory `/var/jenkins/workspace/pr-doc_PR-52368-YBQWFDKYTXAEE66QNONYBROXKZYDY3U4XQ4FDLNWAOWZLXEJGTKA/doc'```

**Review by waynew — DISMISSED** [review]
Looks like the doc build failed

**Comment by mchugh19** [comment]
Yep. Since the test finds missing docs, I then added lots of missing ref files. Because they've never been used, it turns out there are many typos and errors that Sphinx chokes on. I've then started going through those errors and I'm now up to working through the state errors. So it will probably be another couple of days until I can get everything building again.

While needed it's turned out to be a suckier project than first expected. But I now know a bit more about ref syntax than I did before 😋


Relatedly, once it works, we'll want to get this merged quickly as it has required touching lots of module files to fix their documentation. Letting it linger risks constant merge conflicts.

**Comment by waynew** [comment]
That makes sense :)

Ping me when it's (re)-ready to merge and I'll make sure to get it shepherded 🐑 🚀 😀

**Comment by mchugh19** [comment]
Down to the last doc error of:
```
Warning, treated as error:
<autosummary>:1:Unknown target name: "aws kms envelope encryption".
```

I'm not sure where that is coming from. Grepping the whole repo turns up only:
```
Binary file ./doc/_build/doctrees/ref/renderers/all/index.doctree matches
Binary file ./doc/_build/doctrees/ref/renderers/all/salt.renderers.aws_kms.doctree matches
Binary file ./doc/_build/html/.doctrees/ref/renderers/all/salt.renderers.aws_kms.doctree matches
```

Which has only the standard autosummary bits:
```
.. autosummary::
    :toctree:
    :template: autosummary.rst.tmpl
```

So something there must be pulling in a bad target/link name.

Any thoughts? Otherwise this looks good to go! 

Pshew!

**Comment by mchugh19** [comment]
I think we've got a clean build!

The unit test only checks that each python file has a corresponding rst file. The doc build process errors if the rst file isn't referenced, forcing the human to add the entry to an index file, but it doesn't clearly state that process. Not sure how often that comes up, but in PRs it should be discovered.

Anyway, I think this is all set to go. @waynew care to look it over once more with the team and merge?

**Review by mchugh19 — COMMENTED** [review]
build is now clean

**Comment by mchugh19** [comment]
ping @waynew. This should go in before too many conflicting files are updated.

**Comment by waynew** [comment]
Hey @mchugh19 It appears that something is wonky with the PR builds. Specifically, they're failing before the tests even start. Could you try rebasing? If that doesn't clear up the tests then we may want to try just opening a new PR, but 🤞

**Comment by mchugh19** [comment]
Can do, but I'm away on holiday for the next couple of weeks. If anyone
wants to give it a go, please do. Otherwise I'll be back around the start
of May.

**Comment by mchugh19** [comment]
@waynew just rebased and force pushed. Hopefully that works! Please let me know about any issues. I'd really like to see this get in sooner than later as it touches a bunch of code for doc fixes.

**Comment by mchugh19** [comment]
@waynew @Ch3LL @garethgreenaway I'm not sure what's going on with the ubuntu tests `RuntimeError: Ping Minions Failed`. That doesn't seem related to doc updates. Do we have clean test builds these days, or is there something I should investigate? 

As mentioned, this is a pretty big doc update, and will likely have conflicts with module, state, etc updates. So I'd like to see this helped along as it will get painful if stale.

**Comment by mchugh19** [comment]
The failed lint job doesn't appear related to this PR

**Comment by dwoz** [comment]
re-run lint

**Comment by waynew** [comment]
Pretty sure these other failures are also unrelated - re-running now (they look like they failed in the setup step)

**Comment by mchugh19** [comment]
Can we get this backported to earlier releases? Docs should probably be accurate for supported releases.

**Comment by Ch3LL** [comment]
of course! I'll add the backport label and it will get backported when its merged.

**Review by waynew — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Review by Ch3LL — APPROVED** [review]

**Comment by Ch3LL** [comment]
thanks for this one @mchugh19 ! This will be great to have. I'll try to backporting it tomorrow or monday :)

**Pull request merged**
