### PR TITLE
State schedule doc formatting

### PR DESCRIPTION
**Pull request by brd**
### What does this PR do?
Fix the formatting of the docs for [state.scheduler](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.schedule.html)

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by cmcmarrow** [comment]
re-run full all

**Comment by cmcmarrow** [comment]
@brd we do not push to develop any more. Please push the doc changes to master.

**Comment by brd** [comment]
@cmcmarrow Sorry, I had not noticed that!

**Comment by bryceml** [comment]
it would be a bit easier to understand (and be more in line with other docs) if the explanation came before the code block for each example.

**Comment by cmcmarrow** [comment]
@brd pre-commit is still failing. This link should help you with the pre-commit setup https://docs.saltstack.com/en/latest/topics/development/contributing.html.

**Review by cmcmarrow — CHANGES_REQUESTED** [review]
Also please ping me if you have any questions.

**Review by Ch3LL — APPROVED** [review]

**Review by cmcmarrow — APPROVED** [review]

**Pull request merged**
