### PR TITLE
 Fix file.replace idempotency

### PR DESCRIPTION
**Pull request by slaws**
### What does this PR do?
It should prevent file.replace to modify mtime

### What issues does this PR fix or reference?
 Issue  #55297

### Tests written?
Yes

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by cmcmarrow** [comment]
@slaws ci/lint failed

**Comment by cmcmarrow** [comment]
Other than that looks good right now

**Review by cmcmarrow — DISMISSED** [review]

**Comment by ymasson** [comment]
Hello,

This PR is a bugfix. Please accept it.

**Review by DmitryKuzmenko — DISMISSED** [review]

**Comment by DmitryKuzmenko** [comment]
@slaws could you please resolve merge conflicts?

**Review by DmitryKuzmenko — APPROVED** [review]

**Pull request merged**
