### PR TITLE
implimented unit test cases for mount module

### PR DESCRIPTION
**Pull request by rupeshta**
implimented unit test cases for mount module

### CODE REVIEW

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
@rupeshta please fix these failing tests

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
@rupeshta, I have fixed the errors your code was having [here](https://github.com/saltstack/salt/pull/19808).  Please review these changes.  Your use of the `@patch` decorator should have worked for `test_swaps`, but sometimes MagicMock does not behave as expected, so I reimplemented that function using a `with patch...` statement.  Also one of your `test_set_fstab` tests was failing because the expected error wasn't being raised.  Otherwise the tests look great.

**Pull request merged**
