### PR TITLE
Correct ordering of arguments to SaltEvent()

### PR DESCRIPTION
**Pull request by plastikos**
Correct argument ordering to SaltEvent().

### CODE REVIEW

**Comment by plastikos** [comment]
Ha!  Silly me - forgot to select 2015.5.  Yes, I know it's crufty old.

**Comment by rallytime** [comment]
@plastikos That Lint run looks off, but i think you're missing a comma on your change.

**Comment by plastikos** [comment]
I weep small tears for my sloppiness. <sniff/>

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by basepi** [comment]
This is perfect. Great catch!

**Comment by plastikos** [comment]
Yeah . . . it only took me four tries to get "perfect".  ;-)

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
This is hanging on the npm test, which is a bit odd.

@plastikos would you mind rebasing this just to see if there's something that snuck into that branch unrelated to this PR that's causing that issue?

**Comment by plastikos** [comment]
Hmmm.  There were several locations where the arguments to ``SaltEvent()`` were transposed or incorrect when 2015.5 was initially released.  This was the last remaining location where it had not been fixed.  Apparently this particular line *mysteriously* disappeared in 1502a3977951.  I have no explanation because it is in one parent, but the specific ``self.event = SaltEvent(opts, 'minion')`` is not shown in the applied diff.  Odd.  Maybe I just don't know what I'm doing.

**Comment by plastikos** [comment]
This can be closed - I'm just uncomfortable about the disappearance of the ``self.event = SaltEvent(opts, 'minion')`` line without mention in the patch.

**Pull request closed without merging**
