### PR TITLE
Fix handling of trailing newlines on Windows

### LINKED ISSUE #39842: File module removes trailing newline on Windows
There is a bug in `salt/modules/file.py` that causes trailing newlines in files to be removed when the minion is running on Windows.

### Setup
mystate.sls:
```
my_file:
  file.managed:
    - name: 'C:\myfile.txt'
    - contents: 'Hello World!'
    - contents_newline: true
```

### Steps to Reproduce Issue
`salt windows-minion.example.com state.apply mystate`

#### Minion

> Salt Version:
>            Salt: 2016.11.3
> 
> Dependency Versions:
>            cffi: 1.7.0
>        cherrypy: unknown
>        dateutil: 2.5.3
>           gitdb: 0.6.4
>       gitpython: 2.0.8
>           ioflo: 1.5.5
>          Jinja2: 2.9.4
>         libgit2: Not Installed
>         libnacl: 1.4.5
>        M2Crypto: Not Installed
>            Mako: 1.0.4
>    msgpack-pure: Not Installed
>  msgpack-python: 0.4.8
>    mysql-python: Not Installed
>       pycparser: 2.14
>        pycrypto: 2.6.1
>          pygit2: Not Installed
>          Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
>    python-gnupg: 0.3.8
>          PyYAML: 3.11
>           PyZMQ: 16.0.1
>            RAET: Not Installed
>           smmap: 0.9.0
>         timelib: 0.2.4
>         Tornado: 4.4.1
>             ZMQ: 4.1.6
> 
> System Versions:
>            dist:
>         machine: AMD64
>         release: 2012ServerR2
>          system: Windows
>         version: 2012ServerR2 6.3.9600  Multiprocessor Free

### Investigation Results

The problem seems to be caused by the following code in `salt/modules/file.py` (it is used in several places):

```
if salt.utils.is_windows():
    contents = os.linesep.join(contents.splitlines())
```

Python’s `splitlines()` method ignores any trailing newline characters ([Python API documentation](https://docs.python.org/2/library/stdtypes.html#str.splitlines)).

I think this problem can be fixed by replacing the code with the following logic:
```
if salt.utils.is_windows():
    trailing_newline = contents.endswith('\r') or contents.endswith('\n')
    contents = os.linesep.join(contents.splitlines())
    if trailing_newline:
        contents += os.linesep
```

This issue is vaguely related to #14135 and #36502, but unlike these issues it can be fixed without adding any new features.

### PR DESCRIPTION
**Pull request by smarsching**
### What does this PR do?

The `file` module incorrectly handled trailing newline characters in files when running on Windows. This hand the consequence that a trailing newline character was always removed from a file handled by the file module, even if it was present in the reference file or contents.

On Windows, the `file` module uses Python’s `splitlines` method in order to split the lines of a file and reassembles them using `join`, in order to convert to the platform’s newline character sequence (CR LF).

This has the unintentional side effect that a trailing newline (as it actually appears in most configuration files) is removed because the `splitlines` method always removes the last line if it is empty.

This PR fixes this issue by specifically checking whether the reference contents (regardless of their source) end with a newline character. If so, an empty line is added to the list of lines, so that the code finally joining the lines will generate a trailing newline sequence.

### What issues does this PR fix or reference?

This PR fixes #39842.

### Previous Behavior
When using `file.managed` on Windows, a trailing newline character would always be removed.

### New Behavior
A trailing newline character (or sequence) is preserved if it is present in the reference. Thus the managed file on the minion will have a trailing newline sequence if (and only if) the reference has a trailing newline character (or sequence). This is actually the same behavior that we already had on non-Windows platforms.

### Tests written?

No

I tested that `file.managed` now works as expected on Windows, while keeping the (correct) behavior on Linux. I explicitly tested that the following cases are now handled correctly:

- Reference has trailing newline, file on minion does not => trailing newline is added.
- Reference has trailing newline, file on minion does => no changes made (and no changes reported)
- Reference has no trailing newline, file on minion does not => no changes made (and no changes reported)
- Reference has no trailing newline, file on minion does => trailing newline is removed.

### CODE REVIEW

**Comment by twangboy** [comment]
@smarsching There's more that needs to be done in the `__virtual__` function to properly namespace the `_splitlines_preserving_trailing_newline` function in the `win_file.py` module. Please see how the other namespaced functions are handled.

**Comment by smarsching** [comment]
@twangboy You are right. I submitted the PR before I had fully understood the import logic of the `win_file` module. In this case, it did not case any problems because the `_splitlines_preserving_trailing_newline` function did not call any other functions, but of course you are right that it should use the same context binding logic for consistency (and possible future changes). I have now fixed this. Please check whether the import logic is now okay.

**Review by twangboy — COMMENTED** [review]
@smarsching Thanks for making the requested changes. I approve this request.

**Comment by damon-atkins** [comment]
file and win_file should use mmap for everything. It seems some bits does others do not.  If this function was using mmap a different approach to fixing this would happen.

**Comment by smarsching** [comment]
@damon-atkins This PR is a simple, low-impact bugfix for a stable release. I do not think that a major redesign of the I/O logic should go into such an update.

Having said this, I am aware of some inconsistencies in the `file` and `win_file` modules and I have created #39960 for discussing a redesign. I would be interested in learning why you think that mmap based I/O should be used for all file operations. According to my experience, when processing files sequentially, there is no significant advantage in using mmap based I/O over reading file contents through the regular read/write functions (assuming reasonably sized buffers are being used). However, handling I/O errors correctly gets very difficult when using mmap, in particular when a process is multithreaded.

For this reason, I would rather avoid mmap-based I/O when possible, but maybe you could add a comment with the advantages of mmap-based I/O to #39960.

**Comment by damon-atkins** [comment]
Thanks, I have added comments to the new issue.  Python is not multi-threaded also see my comments in the new issue you have created.

**Comment by cachedout** [comment]
@terminalmage Could you please swing by here and review this? Thanks.

**Comment by cachedout** [comment]
Bump to @terminalmage this is blocking some other stuff so if you could please prioritize looking at this it would be very helpful. Many thanks. :]

**Review by terminalmage — APPROVED** [review]

**Pull request merged**
