### PR TITLE
add more clone options to virtualbox and add better dhcp handling

### PR DESCRIPTION
**Pull request by mz-bmcqueen**
### What does this PR do?

Salt-cloud for Virtualbox:

* adding __opts__ to the bootstrap call
* it also fixes dhcp handling
* wait on an arbitrary Guest Property
* exposed two other clone options

It properly waits until the dhcp sets an address, where it used to take the address too early, resulting in the wrong address in many circumstances (see comments in the old code indicating the dev's uncertainty about cached values).  It also adds some new config parameters, one of which allow admins to wait on an arbitrary Guest Property.  I've also exposed two other clone options, which were previously defaulting, and allow the admin to use the second network interface, instead of always taking the first.  Usin the default value for clone type made it impossible to clone more than one server, so you couldn't really get a "cloud" going on your local with virtualbox, because non-full clones share their disk storage, and that storage gets locked by the first clone.

### Previous Behavior
I could not clone more than one server with salt-cloud.
The server bootstrap would often fail since the ip addresses were pulled before dhcp had run.
The call to bootstrap would fail because it needed __opts__.

### New Behavior
Can start many virtualbox servers via salt cloud with the virtualbox driver, and salt is properly setup with the salt-master running on the host machine and the minions are all guest vms.

### Tests written?

No

### Commits signed with GPG?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by mz-bmcqueen** [comment]
@rallytime, I redid the PR  #44806 starting from 2017.7.  It was my best guess at how to do what you wanted me to do about rebasing.  I tried rebasing 2017.7 onto the other branch (2017.7.2) and there were way too many changes.

For some reason its showing my commit is not gpg signed.  I cherry-picked it over to this branch and fixed conflicts (didn't really rebase).  It prompted me for my gpg password on commit, so I don't know why its showing a gpg signature problem.

Do I need to redo something to fix the gpg problem?

**Comment by mz-bmcqueen** [comment]
The lint complaints look easy.  I don't what this stuff means: jenkins/PR/salt-pr-linode-ubuntu16-py3

**Review by gtmanfred — APPROVED** [review]

**Comment by mz-bmcqueen** [comment]
2017.7 is pretty fast moving!  Do I need to hit this "Update branch" button to stay up-to-date on this or does somebody over there do that? I've already hit it once today.

**Comment by rallytime** [comment]
@mz-bmcqueen Thanks for moving this PR to 2017.7. You don't need to keep using the `Update branch` button. These branches all move quickly, that is definitely true!

Also, welcome and congrats on your first salt PR! We're glad to have you here.

**Comment by rallytime** [comment]
re-run lint

**Review by rallytime — APPROVED** [review]

**Pull request merged**
