### PR TITLE
Format load to have required keys

### PR DESCRIPTION
**Pull request by pass-by-value**

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by pass-by-value** [comment]
Running 2 masters on `192.168.1.114` and `192.168.1.112`

My DB lives on `192.168.1.112`

Master config file for `192.168.1.112`
```yaml
external_auth:
    pam:
      salt:
        - '.*'
        - '@runner'
        - '@wheel'

rest_cherrypy:
  port: 8000
  # Don't do this in production!
  disable_ssl: True
  debug: True

# Please replace mysql.host by your hostname
mysql.host: '127.0.0.1'
mysql.user: 'saltadmin'
# Please replace the password to use your password
mysql.pass: 'saltadmin'
mysql.db: 'saltdb'

master_job_cache: mysql

loop_interval: 5
presence_events: True
```

Master config file for `192.168.1.114`
```yaml
external_auth:
    salt:
      vagrant:
        - '.*'
        - '@runner'
        - '@wheel'

rest_cherrypy:
  port: 8000
  # Don't do this in production!
  disable_ssl: True
  debug: True

# Please replace mysql.host by your hostname
mysql.host: '192.168.1.112'
mysql.user: 'saltadmin'
# Please replace the password to use your password
mysql.pass: 'saltadmin'
mysql.db: 'saltdb'

master_job_cache: mysql

loop_interval: 5
presence_events: True
```

In both cases there are no salt_returns or salt_events coming back to the db

Salt version = `Salt: 2015.2.0rc1-120-g128b461`


This patch should resolve above errors

**Comment by UtahDave** [comment]
@pass-by-value hey, can you test this in 2014.7 branch too? I'm pretty sure this needs to be fixed there as well.

**Comment by rallytime** [comment]
@pass-by-value Yeah, should this be backported? Seems like a bug fix we'd want in a newer branch than develop, though I am not sure if it should go back to 2015.2 or 2014.7, as @UtahDave stated.

**Pull request merged**
