### PR TITLE
Adjusted the expected output to match the actual results

### PR DESCRIPTION
**Pull request by justinta**

### CODE REVIEW

**Comment by cachedout** [comment]
@jtand Was this tested against Python 2.7 or just 2.6?

**Comment by jtand** [comment]
@cachedout yeah, I only tested against 2.6, which I realized after I left to lunch. I'm reworking to fit both now.

**Comment by cachedout** [comment]
@jtand Thank you. Please let me know when this is ready to go.

**Comment by jfindlay** [comment]
@cachedout, done.

**Pull request merged**
