### PR TITLE
Fix docker mine module for py3

### PR DESCRIPTION
**Pull request by cachedout**

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Its supposed to be py3 **and** py2 compatible using `six.iter<foo>`...

What issues did you hit?
Should we upgrade salt's six lib?

**Comment by cachedout** [comment]
@s0undt3ch The values weren't iterated in the same order as they were in Py2. This approach did do that. That said, if we aren't running the latest six lib we should definitely start there...

**Comment by s0undt3ch** [comment]
Hmm, interesting.... Could it be the different kind of iterator objects from py2 and py3? ....

You should probably add a comment on why we're not iterating, since its more memory friendly or this will get changed back to iter at some point....

**Comment by s0undt3ch** [comment]
On Py3 `.values()` returns a dict view, to get the same for py2 we need to call `.viewvalues()`. Maybe six supports that? While maintaining order and not creating a new list of the values at runtime?

Just some ideas to keep resource usage to a minimum while maintaining behavior....

**Comment by s0undt3ch** [comment]
https://pythonhosted.org/six/#six.viewvalues

**Comment by cachedout** [comment]
@s0undt3ch Good find. I will give that a try here.

**Comment by s0undt3ch** [comment]
Let me know if it doesn't work out, thats valuable info.

**Comment by cachedout** [comment]
`viewvalues()` didn't work and on further investigation of this approach, it didn't work either. I'm closing this until I can understand what's going on here.

**Comment by s0undt3ch** [comment]
OK.

**Pull request closed without merging**
