### PR TITLE
Speed up zfs.filesystem_present

### PR DESCRIPTION
**Pull request by asomers**
Only look up the requested properties in ZFS, instead of all properties.
This affects zfs.volume_present, too.

Sponsored by: Axcient

### What does this PR do?

Speeds up the `zfs.filesystem_present` and `zfs.volume_present` states.

### Previous Behavior
`zfs.filesystem_present` would run `zfs get -Hp -o name,value,source all <dataset>` to look up all properties of the dataset.  That's slow, because some of those properties can be overridden at mount time, and libzfs searches through _all_ mounted file systems to find them.

### New Behavior
A state like this:
```yaml
mypool/mydataset:
  zfs.filesystem_present:
    - properties:
      compression: lz4
```
Will run `zfs get -Hp -o name,value,source compression <dataset>`, which is much faster.

### Merge requirements satisfied?
- [N/A] Docs
- [Not required for performance enhancements?] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by alek-p — DISMISSED** [review]

**Comment by asomers** [comment]
Hm.  The macosx and freebsd test failures are unrelated, but the debian9 failure is my fault.  I'll try to fix that.

**Comment by asomers** [comment]
I just rebased onto master, which I hope will fix the libgit2-related test failures on freebsd.

**Comment by asomers** [comment]
Ok, I don't think any of the remaining test failures are related to the PR.  @xeacott if you approve the changes, I'll squash my commits.

**Comment by xeacott** [comment]
No worries on squashing the commits, keeping all the history is fine but I think I'm good with this

**Comment by xeacott** [comment]
@krionbsd review once more?

**Review by xeacott — DISMISSED** [review]

**Review by krionbsd — DISMISSED** [review]

**Comment by waynew** [comment]
@asomers looks like there's a conflict, do you think you can rebase this?

**Comment by asomers-ax** [comment]
rebased, @waynew .

**Comment by asomers-ax** [comment]
The test failures look unrelated to this PR.

**Comment by waynew** [comment]
Thanks! Let's see if the failures are just flaky tests

**Review by waynew — APPROVED** [review]
Looks good - I think there are some improvements that could be made here but given this is blocking a related PR, and everything is passing, I think we should go ahead and merge this and the changes can be made in the other PR

**Review by krionbsd — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
