### PR TITLE
adding range interface support and ability to turn arpcheck off to redhat related system, 

### PR DESCRIPTION
**Pull request by cxfcxf**
add ability for users using redhat/centos/fedora to turn off ARPCHECK in their network setting.

### CODE REVIEW

**Comment by cxfcxf** [comment]
Hi, i am adding range support for redhat based interface
all the changes only go to rh6_eth.jinja, but it should be also safe for rhel 5 and 7.

i am trying to add more supports for ranged interface for vlan and bond.

**Comment by jfindlay** [comment]
@cxfcxf, there is a [lint error](https://jenkins.saltstack.com/job/salt-pr-lint-n/1861/violations/file/salt/states/network.py/).  Also, are you planning on adding further commits?  Thanks.

**Comment by cxfcxf** [comment]
@jfindlay, Hi yeah, the Exception error i saw, i am actuualy trying to add ranged support for redhat/centos, i think i should submit pull separately.

**Comment by cxfcxf** [comment]
fixed status on ranged interface and exception error ( should )

**Comment by thatch45** [comment]
I fixed the lint error @jfindlay 
Thanks for the addition @cxfcxf !

**Pull request merged**
