### PR TITLE
Improve macOS service naming support

### LINKED ISSUE #57878: macOS salt-minion service not found
**Description**
Documentation throughout the salt universe mentions running commands like `salt service.restart salt-minion` this is valid on many OSes that salt runs on but on macOS the default service name/label for the salt-minion is `com.saltstack.salt.minion`. So when your run `salt service.restart salt-minion` you get the following error

```
Error running 'service.restart': Service not found: salt-minion
```

**Setup**
macOS device with salt installed

**Steps to Reproduce the behavior**
`salt service.restart salt-minion`

**Expected behavior**
salt should restart the salt-minion service.

### PR DESCRIPTION
**Pull request by weswhet**
### What does this PR do?

This PR makes it so if you specify a service on macOS by the naming convention similar to that of other platforms like `salt-minion` it will convert it over to its proper name `com.saltstack.salt.minion`. It will do the same for `salt-master`, `salt-api`, `salt-syndic`.
### What issues does this PR fix or reference?
Fixes:

I've seen multi times where people mention that documentation mentions restarting a service by running `salt * service.restart salt-minion` they do this on macOS not knowing that the naming convention is different. This will automatically handle it for them.

Helps support the [Formula PR here.](https://github.com/saltstack-formulas/salt-formula/pull/447)

### Previous Behavior
macOS would fail with `Service not found: salt-master`

### New Behavior
macOS will now know which service to look for and perform the correct action.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### CODE REVIEW

**Comment by weswhet** [comment]
Test failure isn't related to this PR.

**Comment by weswhet** [comment]
re-run ci/py3/ubuntu1604

**Comment by weswhet** [comment]
re-run ubuntu1604

**Review by noelmcloughlin — DISMISSED** [review]
LGTM. We need to get MacOS added to CI sometime soon.

**Review by DmitryKuzmenko — DISMISSED** [review]

**Comment by DmitryKuzmenko** [comment]
@weswhet thank you for contribution! I'm good with this but since I'm not very familiar to MacOS specifics I want also @garethgreenaway to review this.

**Review by garethgreenaway — DISMISSED** [review]

**Comment by weswhet** [comment]
Thanks @DmitryKuzmenko @garethgreenaway!

**Comment by garethgreenaway** [comment]
@weswhet No worries.  Can we get a changelog file with the changes documented?

**Comment by weswhet** [comment]
@garethgreenaway thanks! Added the changelog for this fix.

**Review by s0undt3ch — DISMISSED** [review]

**Review by garethgreenaway — DISMISSED** [review]

**Comment by weswhet** [comment]
another all green one for ya @garethgreenaway 💚

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
