### PR TITLE
Updates win_update module and state.

### PR DESCRIPTION
**Pull request by mpreziuso**
Should fix https://github.com/saltstack/salt/issues/30081.
This update brings consistency between the two module/state, renames 'includes' to 'skips' as it makes more sense, adds full support for "hidden updates", adds documentation on the module, and bit more.

Cc @cachedout, @Narcolapser please review, thanks :)

### CODE REVIEW

**Comment by jtand** [comment]
@mpreziuso It looks like there are some [lint failures here](https://jenkins.saltstack.com/job/salt-pr-lint-n/12882/violations/) and some test failures. Mind taking a look at those? Thanks!

**Comment by mpreziuso** [comment]
Hi @jtand, yes definitely! I was working on it a few hours ago, but with not much luck: perhaps I'm not getting it right, but I can't see any whitespaces before the end of the line, so I'm kind of puzzled on what pylint exactly means, can you advise? 
Thanks!

**Comment by jtand** [comment]
@mpreziuso Sure thing. I checked out your latest commit and it looks like on lines 35, 50, 228, 233 you have some random spaces that the lint is complaining about. On lines 51 and 52 you have an extra space and the end of the lines. 

Hope that helps!

**Comment by cachedout** [comment]
Hi @mpreziuso 

Thanks for sending this in. I have a few concerns. First, it looks like you've renamed some arguments as you mention. This is going to break existing states that utilize this module. If we're going to rename them, we need to have a full deprecation path that accepts both the new and the old for a period of time and throws warnings if the old values are used.

Also, as mentioned above, there are some lint failures and some failing tests here. Please let me know when you've had a chance to take a look. Thanks.

**Comment by mpreziuso** [comment]
Hi both,

@jtand thanks for the hint, I'll try and fix that ASAP!

@cachedout thanks for the feedback! I completely agree with you, I'll re-add 'includes' in the function arguments and (if set) add `skips = includes`, or something similar.
That being said, I believe ensuring complete backwards compatibility cannot be ensured this easily: changing the if logic in `AutoSearch` and changing the way `includes.software` and `includes.driver` work are breaking changes as well.
 
The first change simply makes WinUpdate behave differently as it explicitly includes or skips update categories.

The second change actually inverts behaviour: if you were to set `software=True` (or driver) that would include those categories, while it will now skip them and follow the same behaviour of the other options (reboot, present, installed,...).

Do we have a documented policy for breaking changes or deprecations?

**Comment by mpreziuso** [comment]
@jtand there you go :D https://github.com/mpreziuso/salt/commit/f558f68e0ab8e9bb50baabdaa3e46b5b440bb2c5
Shame on me, I was looking at the wrong file.

**Comment by Narcolapser** [comment]
getting close. I remember when I went through the Jenkins gauntlet when I first submitted this module. The good news is you got through all those pylint errors. I had done a completely different style when I first wrote this so that took me forever to fix.

**Comment by cachedout** [comment]
@mpreziuso Looks like we still have some failing tests here. Could you take a look? Let me know if I can help. Thanks.

**Comment by mpreziuso** [comment]
Hi @cachedout,
so sorry I missed this out! I thought those tests were broken on their own (?): so I didn't look at them. Am I wrong?

**Pull request merged**
