### PR TITLE
Fixing KeyError when there are no additional pages

### PR DESCRIPTION
**Pull request by dmyerscough**
When you have only one page you will get a KeyError

``` python
[ERROR   ] There was an error running the function: 'pages'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/cli.py", line 245, in run
    self.function_provider, self.function_name, kwargs
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1492, in do_function
    driver: self.clouds[fun](call='function')
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 42, in func_globals_inject
    yield
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1492, in do_function
    driver: self.clouds[fun](call='function')
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/digital_ocean_v2.py", line 167, in list_nodes
    fetch = 'next' in items['links']['pages']
KeyError: 'pages'
```

### CODE REVIEW

**Comment by jfindlay** [comment]
@dmyerscough, does this also apply to the 2015.2 branch?

**Comment by dmyerscough** [comment]
Yeah, I found another bug too which I will open a pull request for shortly.

**Comment by rallytime** [comment]
This isn't back-porting cleanly. The code that this fix affects is not in the 2015.2 branch.

**Comment by dmyerscough** [comment]
@rallytime can yo let me know the process for back-porting cleanly.

**Comment by rallytime** [comment]
I basically just following the process outlined here: http://docs.saltstack.com/en/latest/topics/development/contributing.html#backporting-pull-requests

However, I think it might just be useful to make the appropriate change directly on the 2015.2 branch as needed.

**Comment by jfindlay** [comment]
Merges forward are usually easier and simpler than backports.

**Comment by rallytime** [comment]
I'll try this again once #23955 is merged.

**Pull request merged**
