### PR TITLE
[dockerng] Fix pulled image comparison

### PR DESCRIPTION
**Pull request by ticosax**
<strike>Please do not merge yet.</strike>

@terminalmage here again, please can you have a look ?

<strike>build on top of #23912 that needs to be merged first.</strike>

### CODE REVIEW

**Comment by ticosax** [comment]
has been rebased, and ready for review.

**Comment by ticosax** [comment]
rebased again.

@terminalmage I do not know if you saw it ?

**Comment by terminalmage** [comment]
Can you explain the use case this fixes? Your fix is likely OK, but there's no mention of the error case that makes this fix necessary.

**Comment by terminalmage** [comment]
Also, it looks like this needs a rebase after I merged https://github.com/saltstack/salt/pull/24011

**Comment by ticosax** [comment]
First, this PR fix a bug, images were always downloaded.
then, if `image:latest` is already downloaded locally the state should not report changes.
event if `force is True`.

**Comment by ticosax** [comment]
rebased

**Comment by ticosax** [comment]
thank you @thatch45 , I was really eager for this one.

**Pull request merged**
