### PR TITLE
Fix for issue #22880, this should be **kwarg, not kwarg=None.

### PR DESCRIPTION
**Pull request by freimer**
Without this fix, and kwargs passed results in a TypeError

### CODE REVIEW

**Comment by jfindlay** [comment]
#22880

**Comment by jfindlay** [comment]
This code should also be removed:
```python
          if kwarg is None:
             kwarg = {}
```

**Comment by freimer** [comment]
@jfindlay I am using orchestrate to do a salt.wheel key.accept just like in the docs:

```
accept_key:
  salt.wheel:
    - name: key.accept
    - match: {{ pillar.minion_id }}
```
I pass the minion_id to the orch state from the reactor for salt/auth.  So I get a traceback when this is run, because the cmd method of this class will not accept a "match" parameter.  It has to be **kwarg in order to accept any number of non-specific keyword arguments and pass them along to the actual function called.  Frankly, I'm surprised that this hasn't caused tons of other issues for many other Salt users.

And no, you don't want to delete:

```python
        if kwarg is None:
            kwarg = {}
```

If you do, and no keyword args are passed, then you will get an exception raised.

I'm using 2015.2, specifically 2015.2.0rc2-477-gd5d1ddc.  The patched file works fine on my system, the non-patched throws a traceback.

**Comment by jfindlay** [comment]
@freimer, thanks for fixing this.  In my experience `**kwargs` will default to `{}` rather than `None`, but it seems you may know more about this than I.

**Comment by freimer** [comment]
@jfindlay no, I think you are correct, if you change it to **kwarg then it should default to {} if no kwargs are passed.  I didn't catch that with the change.

**Comment by freimer** [comment]
@jfindlay hold off on this merge.  There are other issues.  Specifically, it now tracebacks if you don't include any kwargs:

```
An exception occurred in this state: Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/salt/state.py\", line 1563, in call\n    **cdata['kwargs'])\n  File \"/usr/lib/python2.7/site-packages/salt/states/saltmod.py\", line 553, in runner\n    out = __salt__['saltutil.runner'](name, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/salt/modules/saltutil.py\", line 779, in runner\n    return rclient.cmd(fun, [], kwarg=kwargs)\n  File \"/usr/lib/python2.7/site-packages/salt/client/mixins.py\", line 206, in cmd\n    self.functions[fun], arglist, pub_data\n  File \"/usr/lib/python2.7/site-packages/salt/minion.py\", line 278, in load_args_and_kwargs\n    .format(', '.join(invalid_kwargs))\nSaltInvocationError: The following keyword arguments are not valid: kwarg={}\n
```

This was trying to call salt.runner:

```
sleep_10:
  salt.runner:
    - name: test.sleep
```

I can probably get around this by specifying the s_time parameter, but that doesn't fix the bug.

**Comment by freimer** [comment]
So the comment doesn't make much sense, because I'm using PyCharm and it pushed to multiple repositories I have setup in my project(s).  However, I think this is the proper place to fix this; in the call to cmd, not in the implementation of cmd itself.  This is based on the implementation in saltutil.runner, where it uses kwarg=kwargs instead of just passing the "raw" **kwargs.  Another push to follow reverting the changes in mixins.

**Comment by jfindlay** [comment]
@freimer, thank you for working on this.  Do you think it is ready to merge yet?

**Comment by freimer** [comment]
If the merge works, then yes.

**Pull request merged**
