### PR TITLE
update debian based images

### PR DESCRIPTION
**Pull request by bryceml**
updates debian based images for https://github.com/saltstack/salt-jenkins/pull/1675

### CODE REVIEW

**Review by Ch3LL — APPROVED** [review]

**Comment by Ch3LL** [comment]
re-run full all

**Review by s0undt3ch — APPROVED** [review]

**Comment by dwoz** [comment]
Seems like historically these kinds of changes in a point release have caused things to break. Does this need to go in for 3002.1?

**Comment by bryceml** [comment]
@dwoz I marked it 3002.1 because https://github.com/saltstack/salt/pull/58868 was tagged 3002.1 and this is needed there.  That's now Aluminum, so this can be changed to Aluminum.

**Comment by bryceml** [comment]
closed in favor of https://github.com/saltstack/salt/pull/58868

**Pull request closed without merging**
