### PR TITLE
Fix smartos_imgadm doesn't handle orphan images

### PR DESCRIPTION
**Pull request by sjorge**
### What does this PR do?
Update `_parse_image_meta` so that it handles orphan images.
Additionally we also pull in the changes from #51563 to master as those are also needed.

### What issues does this PR fix or reference?
#55136 

### Previous Behavior
`_parse_image_meta`  would not handle orphan image data e.g.
```json
{
  "manifest": {
    "uuid": "07f360fd-12d5-e624-a279-eb8a15b630f6"
  },
  "zpool": "zones",
  "cloneNames": [],
  "clones": 0
}
```

### New Behavior
`_parse_image_meta` will now check if the 'name' field is present.

### Tests written?
Yes, there were no tests for smartos_imgadm yet. Tests for `_parse_image_meta` were added that feed is various kinds of image data. Currently those are 'orphan', 'native', 'lx', and 'zvol'.

Those cover the currently available image types available in SmartOS

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by sjorge** [comment]
I'm not sure how to fix the ci/py3 failures?

**Comment by sjorge** [comment]
@Ch3LL aside from a rebase, anything blocking this? CI seems to always fail for a bunch of distros but it are just unit tests which is weird as they work fine locally and on some targets?

**Comment by sjorge** [comment]
@Ch3LL bump

**Review by dwoz — APPROVED** [review]

**Comment by sjorge** [comment]
Thanks for merging!

**Pull request merged**
