### PR TITLE
Mount.mounted: Include example for bind mounts

### PR DESCRIPTION
**Pull request by The-Loeki**
Add an example of how to do a bind mount using this state

### CODE REVIEW

**Comment by The-Loeki** [comment]
Wow those red crosses are alarming :dango:

**Comment by rallytime** [comment]
@The-Loeki Yes, we're trying out some new things for PR management. :)

Thank you for submitting this example. Looks like you have a small lint error: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/11576/violations/file/salt/states/mount.py/

**Comment by The-Loeki** [comment]
I'm liking it, but the red crosses do give something of a DEFCON-1 sensation, I think the same orange as the checker will be a bit more friendly for my eyes & heart ;)

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
@The-Loeki Yes, the red is a bit striking. However, that is a GitHub default. Hopefully we will all get used to it sooner rather than later. :)

**Review by cachedout — APPROVED** [review]

**Pull request merged**
