### PR TITLE
Config file patches

### PR DESCRIPTION
**Pull request by jf**
### What does this PR do?

Fix typos, and errors in the config files
### What issues does this PR fix or reference?
#32460

### CODE REVIEW

**Comment by cachedout** [comment]
Great! Thank you, @jf

**Comment by jf** [comment]
Woah, that was fast. Thanks!

**Comment by cachedout** [comment]
@jf We stay busy around here. ;] Thanks for the contribution. It's much appreciated.

**Comment by jf** [comment]
No prob! I have one more update to this PR, though. (Just confirmed that sha1 is in the list for the client as well. Should I do a new PR for that?)

**Comment by cachedout** [comment]
@jf I'd rather have it in another PR if you don't mind. Thanks.

**Comment by jf** [comment]
sure. Thanks.

**Pull request merged**
