### PR TITLE
Postgresql schema

### LINKED ISSUE #42543: postgres_schema.py state not following other postgres state convention of using system user
### Description of Issue/Question
Some states inconsistently use system users for auth to postgres

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Last lines of pg_hba.conf on server
```
# This is a requirement of postgres_user and postgres_schema salt formula
local   all             postgres                                     peer
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
https://github.com/saltstack/salt/blob/develop/salt/states/postgres_database.py line 68-69 documents performing a db operation as a system user
 https://github.com/saltstack/salt/blob/develop/salt/states/postgres_schema.py have no similar option, this prevents using the same peer auth in pg_hba for a db and the tablespace(or enforces using different users for both, which I did for a while)

### Versions Report
Patch taken from develop, I am however running salt 2015.8.11 (Beryllium) in production.

### PR DESCRIPTION
**Pull request by perlchild**
### What does this PR do?
Attempt to fix where a parameter is missing/inconsistently used in postgresql_schema.py state

### What issues does this PR fix or reference?
Fixes https://github.com/saltstack/salt/issues/42543

### Previous Behavior
Previous behaviour is not consistent across postgres states

### New Behavior
This behaviour should be more consistent, but I welcome feedback(runas/user seems confusingly used)

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by perlchild** [comment]
I guess I need to wait for the jenkins jobs to run, do you need anything else from me?

**Comment by perlchild** [comment]
Ok, it finished, it tells me it's failed, but it's not clear(to me, because I'm obviously a newb) what failed.  Can someone help?

**Comment by gtmanfred** [comment]
sometimes the one build test failed, it is fine, these are passing.

You should be good once someone gets to reviewing it.

**Comment by perlchild** [comment]
Oh thanks, I got a message mentioning potential reviewers, do I need to do anything to kick that off?

**Comment by gtmanfred** [comment]
No, you should be all set.

**Comment by lukasz-baranowski** [comment]
Guys, after this commit postgres_schema.present is not working...

Module method postgres.schema_get expects _user_ parameter but gets _runas_ instead from postgres_schema state.

**Pull request merged**
