### PR TITLE
fix git state for git version older than 1.9.2 

### PR DESCRIPTION
**Pull request by jespada**
This try to address issue #30999 , feedback welcome :)

### CODE REVIEW

**Comment by cachedout** [comment]
@jespada Thanks! We'll get this reviewed and hopefully merged as quickly as we can.

@terminalmage Please take a look when you have a moment.

**Comment by terminalmage** [comment]
This seems incorrect on a couple fronts:

1. When ``--unset-upstream`` is unavailable, this commit still will report that the tracking branch was unset.

2. ``--unset-upstream`` seems to have been added in 1.8.0, *not* 1.9.2, according to the following inspection I did on the git project's source code:

```bash
%  for tag in `git tag --list`; do git checkout -q --force $tag 2>/dev/null; fgrep -rq -- '--unset-upstream' Documentation/git-branch.txt 2>/dev/null && echo $tag; done | head; git checkout -q --force master
v1.8.0
v1.8.0-rc0
v1.8.0-rc1
v1.8.0-rc2
v1.8.0-rc3
v1.8.0.1
v1.8.0.2
v1.8.0.3
v1.8.1
v1.8.1-rc0
```

In addition, the pull request was opened against the develop branch, and should have been opened against the 2015.8 branch, per our [contributing guidelines](https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch).

I am about to open a pull request against the appropriate branch, which will preserve your work but include a 2nd commit from myself which fixes the problems I explained above.

**Comment by terminalmage** [comment]
https://github.com/saltstack/salt/pull/31301 has been opened and includes @jespada's commit above, along with my corrections. I'm going to close this pull request as it has been superseded by #31301.

Thanks @jespada, for helping identify this issue and helping to get it resolved.

**Comment by jespada** [comment]
@terminalmage thanks for your comments, sorry about opening it against dev branch was looking for feedback to see if I was going in the right direction :). Glad you fix it!

**Pull request closed without merging**
