### PR TITLE
[2019.2.1] Switch docs building under Py3

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title.

### What issues does this PR fix or reference?
#53137

### CODE REVIEW

**Review by bryceml — APPROVED** [review]

**Review by Akm0d — APPROVED** [review]

**Comment by dwoz** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
Hold off on merging, @bryceml point out a missing flag that should be passed to Sphinx.
Also, why do you want to re-run the full test suite for a docs build change?

**Comment by s0undt3ch** [comment]
We're good to go again if docs builds pass

**Comment by s0undt3ch** [comment]
re-run all full

**Comment by s0undt3ch** [comment]
Approved and tests pass, merging.

**Pull request merged**
