### PR TITLE
Feature retcode passthrough exitstatus.4

### PR DESCRIPTION
**Pull request by plastikos**
### What does this PR do?

It passes the `retcode` through to the `salt` and `salt-call` executable exit status.

This is a rebase of #35282
This no longer requires commit back-outs used in #35986 
### What issues does this PR fix or reference?
#18510
### Previous Behavior

The `retcode` from states was not reflected in the command line executable exit status
### New Behavior

Non-zero `retcode` from salt states is used for the exit status of `salt` and `salt-call` - unless a "higher priority" error occurs in the specific executables.
### Tests written?

Yes

Re #36065 
This is a rebase of #36065 to test current test suite failures.

### CODE REVIEW

**Comment by cachedout** [comment]
I've been finally able to go through this and I think we're getting there but I do need a rebase. Apologies that this is taking so long.

**Comment by edgan** [comment]
I am tired of waiting on this. I am going to try patching my own version, and see how it works.

**Comment by cachedout** [comment]
@plastikos Can you either rebase this or break it into smaller PRs?

**Comment by edgan** [comment]
I managed to get the patch recreated against 2016.11.1. I am testing it now.

So far the only issue I have had is in my master file for salt-ssh I have the configuration option below, but get the error below. This wasn't an issue before the patch. The /var/log/salt directory was owned by root and the user running salt-ssh was jenkins. The workaround was to "chown jenkins /var/log/salt".

master configuration:
log_file: /dev/null

error:
No permissions to access "/var/log/salt/ssh", are you running as the correct user?

**Comment by cachedout** [comment]
@edgan Could you put your work that you've done to resolve merge conflicts into a PR and open it against the develop branch? I'll close this one and we can continue things there.

**Comment by rallytime** [comment]
I am going to close this pull request since it hasn't received any updates recently. We can certainly come back to it in the future, but this kind of an effort will need to be broken up into smaller PRs. Thanks all!

**Pull request closed without merging**
