### PR TITLE
Add shutdown and reboot functions to win_system state module

### PR DESCRIPTION
**Pull request by morganwillcock**
### What does this PR do?
- Adds shutdown and reboot functions to win_system state module.
- Changes the documentation of the win_system execution module to suggest use of the state module instead, for some use cases.

### What issues does this PR fix or reference?
As discussed in #39243.

Allows optional reboot or shutdown from a highstate run. A shutdown or reboot returns changes so that a dependant state may prevent additional functions from running.

e.g.
<pre>reboot_if_needed:
  system.reboot:
    - timeout: 60
    - in_seconds: True

failhard_for_reboot:
  test.fail_without_changes:
    - failhard: True
    - onchanges:
      - system: reboot_if_needed

something_else:
  test.succeed_without_changes</pre>

Default values were chosen to be similar to the win_system execution module.

### Tests written?

No

### CODE REVIEW

**Comment by hrumph** [comment]
I think this is good. I think it's ready for merge.

**Comment by hrumph** [comment]
Actually one problem. I don't think the changes dictionary has been done right. "Old" and "new" aren't supposed to be direct children of "changes". There's supposed to be a key in between, which you might call something like "system-state" in this case. (see the example at https://docs.saltstack.com/en/latest/ref/states/writing.html). After that, and lint fixes I would think that it's time for a PR but I don't think that this will be the end of this. I'm investigating some possible improvements.

**Comment by morganwillcock** [comment]
Ah yes, looks like that is missing. When it came to the return I used the `computer_desc` function as a reference (just because it was the first one in the file) and it's also missing the name:
<pre>ret['changes'] = {'old': before_desc, 'new': name}</pre>

What's the easiest way to run a lint check?

**Comment by hrumph** [comment]
@morganwillcock to see lint problems click on the _details_ link for _jenkins/PR/salt-pr-lint-n_ and from there click on "console output".

**Comment by hrumph** [comment]
@morganwillcock to see lint problems click on the details link for jenkins/PR/salt-pr-lint-n and from there click on "console output". I've seen some looseness wrt the changes dictionary but I think that what's written in the guide should be the standard.

**Pull request merged**
