### PR TITLE
More dictupdate tools

### PR DESCRIPTION
**Pull request by github-abcde**
### What does this PR do?
This PR adds functions to write to nested dicts, like `traverse_dict` does for reading from nested dicts.
The four basic functionalities (set, update, append, extend) that can be applied to a nested dict are also made available as jinja filters.
The key/keys provided to these functions need not exist in the provided dict yet, they will be created.
Support has been included for configurable delimiters and the use of OrderedDicts instead of dicts (when new nested entries are created).

Added two pylint-inspired fixes (line 58-59, 69-77).

### What issues does this PR fix or reference?
None that I know of.

### Previous Behavior
Unable to update nested dictionaries easily (in salt and in Jinja)

### New Behavior
Updating nested dictionaries in salt (for example to set the changes in a state):
```
salt.utils.dictupdate.set_dict_key_value(ret, 'changes:old:sub_item', old_value)
salt.utils.dictupdate.set_dict_key_value(ret, 'changes:new:sub_item', new_value)
```
Though the above could also be used if multiple changes need to be presented in a list, by using:
```
for item in list_of_items_to_process:
  ... code ...
  salt.utils.dictupdate.append_dict_key_value(ret, 'changes:new:sub_item', new_value)
```

Updating nested dictionaries in Jinja:
```
{%- set foo = {} %}
Test dictupdate:
  module.run:
  - test.outputter:
    - data: {{ foo | set_dict_key_value('bar:baz', 42) }}
```
Results in:
```
          ID: Test dictupdate
    Function: module.run
      Result: True
     Comment: test.outputter: Success
     Started: 12:10:25.985492
    Duration: 18.949 ms
     Changes:   
              ----------
              test.outputter:
                  ----------
                  bar:
                      ----------
                      baz:
                          42
```

Another Jinja example:
```
{%- set foo = {'bar': [1, 2]} %}
Test dictupdate:
  module.run:
  - test.outputter:
    - data: {{ foo | append_dict_key_value('bar', 42) }}
```
Results in:
```
          ID: Test dictupdate
    Function: module.run
      Result: True
     Comment: test.outputter: Success
     Started: 12:14:42.047802
    Duration: 21.165 ms
     Changes:   
              ----------
              test.outputter:
                  ----------
                  bar:
                      - 1
                      - 2
                      - 42
```

### Tests written?
Yes

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by twangboy** [comment]
@github-abcde This looks great. Could we get some Unit tests on these new functions please?

**Comment by github-abcde** [comment]
Working on the unit tests...There are a lot of things to test :)

**Review by twangboy — APPROVED** [review]
This looks great. Thanks for the tests!

**Comment by github-abcde** [comment]
Not sure if I fixed all the failing python3 tests, will monitor the test results and fix things tomorrow should any still fail.

**Comment by github-abcde** [comment]
@twangboy Is there something else that I can (or need to) do in order for this branch to be merged?

**Review by twangboy — APPROVED** [review]

**Pull request merged**
