### PR TITLE
[WIP] Setuptools is smart enough to understand requirement markers

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title

### CODE REVIEW

**Review by dmurphy18 — COMMENTED** [review]
This looks good, but are there version limitations with setuptools for parsing line, for example: using v10.2.1 of setuptools, otherwise usually v33+ or v36+

**Comment by s0undt3ch** [comment]
@dmurphy18 good call. setuptools 10.2.1 doesn't know how to parse these requirements

**Comment by s0undt3ch** [comment]
This change will bump the setuptools requirement to `>=20` when doing a `python setup.py install`

**Comment by s0undt3ch** [comment]
Added `WIP` since this setuptools minimum version bump is most likely not desirable.

**Pull request closed without merging**
