### PR TITLE
Make systemd service state less slow

### PR DESCRIPTION
**Pull request by k00mi**
As has been noted in #10710, execution of a systemd service state is quite slow. The suggested solution of using `systemctl is-enabled` only helps for the enable operation. Instead, these commits address the expensive function `_untracked_custom_unit_found()`, which is used in several other places.

Previously our highstate runs took about 45s to several minutes due to a bug in systemd/logind which leaks unit files. With these patches we are down to about 36s in all cases.

### CODE REVIEW

**Comment by cachedout** [comment]
@k00mi Thanks for this. I am concerned that this may regress the fix that was made here: https://github.com/saltstack/salt/pull/11921

Thoughts?

**Comment by cachedout** [comment]
@k00mi Additionally, it looks like this is causing a test to fail so if we were to merge this, we would need to have that fixed. Could you please take a look? Thanks.

**Comment by k00mi** [comment]
@cachedout Indeed parametrized units were not handled correctly. I think I fixed it now by asking `systemctl list-unit-files` if the unit was not found in `list-units` and added a comment explaining why both are necessary. `systemd-sysv-generator` takes care of legacy units in /etc/init.d, so they appear as regular units in `list-units`.

The CentOS VMs don't even bootstrap properly and those tests that actually reach the systemd module fail with `KeyError: 'cmd.run_stdout'`. I have zero clue why this happens. Other functions in this module use that function, as did the previous version and I can't reproduce said error on any of our systems.

Looking at the definition of `test_available()`, I think the issue is with the test itself. It mocks `get_all()` (which would later call `cmd.run_stdout`), but instead of calling that I use `cmd.run_stdout` directly. I don't know enough about your test system to fix this, can someone more familiar take a look?

**Comment by cachedout** [comment]
@k00mi That all sounds great. Thank you!

@jfindlay Any chance you could jump in here and help with the test errors?

**Comment by jfindlay** [comment]
@k00mi, I have updated the test on your branch.

**Pull request merged**
