### PR TITLE
[FIX]: Fix for Issue 63695

### LINKED ISSUE #63695: [BUG]
**Description**
salt-ssh fails to run the ssh_pre_flight script due to undetected failure to copy script to target due to mismatch of temporary directory. On MacOS, TMPDIR is set to a long random directory, several levels deep. This directory varies among different MacOS hosts.
```
bash-3.2$ python3 -c 'import tempfile; print(tempfile.gettempdir())'
/var/folders/35/5t5gx5ks461477_zm6dr3jm80000gn/T
bash-3.2$ ssh remotemac "python3 -c 'import tempfile; print(tempfile.gettempdir())'"
/var/folders/s4/11zm225n0gz5pysnqcg4qzyh0000gn/T
bash-3.2$ ssh remotemac "ls -ld /var/folders/35/5t5gx5ks461477_zm6dr3jm80000gn/T"
ls: /var/folders/35/5t5gx5ks461477_zm6dr3jm80000gn/T: No such file or directory
bash-3.2$ uname -a
Darwin laptop 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:53:49 PST 2023; root:xnu-8792.81.2~2/RELEASE_X86_64 x86_64
bash-3.2$ ssh remotemac "uname -a"
Darwin remotemac 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64 x86_64
```
[Line of code which determines path on remote system via local-system `gettempdir()` call.](https://github.com/saltstack/salt/blob/1e54e400d4dd17fc4d30be3ee1b6141a7cacac63/salt/client/ssh/__init__.py#L1010)

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install
- [x] on-prem MacOS laptop used to manage MacOS machine at datacenter

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)
```
bash-3.2$ cat roster
remotemac:
  host: remotemac
  user: administrator
  priv: ~/.ssh/remotemac
  ssh_pre_flight: install/ssh_pre_flight.sh

bash-3.2$ cat install/ssh_pre_flight.sh
#!/bin/sh -e

hostname

bash-3.2$ salt-ssh -l debug --pre-flight remotemac test.ping
...
[DEBUG   ] Adding minions for job 20230208205856447376: ['administrator-remotemac']
[DEBUG   ] Executing command: scp -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=~/.ssh/mac_metal_admin_salt -o User=administrator  install/ssh_pre_flight.sh remotemac:/var/folders/35/5t5gx5ks461477_zm6dr3jm80000gn/T/ssh_pre_flight.sh
[DEBUG   ] Child Forked! PID: 69987  STDOUT_FD: 20  STDERR_FD: 22
[DEBUG   ] Terminal Command: scp -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=~/.ssh/mac_metal_admin_salt -o User=administrator install/ssh_pre_flight.sh remotemac:/var/folders/35/5t5gx5ks461477_zm6dr3jm80000gn/T/ssh_pre_flight.sh
[DEBUG   ] Executing command: ssh remotemac -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=~/.ssh/mac_metal_admin_salt -o User=administrator  /bin/sh '/var/folders/35/5t5gx5ks461477_zm6dr3jm80000gn/T/ssh_pre_flight.sh'
[DEBUG   ] Child Forked! PID: 69990  STDOUT_FD: 20  STDERR_FD: 22
[DEBUG   ] Terminal Command: ssh remotemac -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=~/.ssh/mac_metal_admin_salt -o User=administrator /bin/sh  '/var/folders/35/5t5gx5ks461477_zm6dr3jm80000gn/T/ssh_pre_flight.sh'
[DEBUG   ] Executing command: ssh remotemac -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=~/.ssh/mac_metal_admin_salt -o User=administrator  rm '/var/folders/35/5t5gx5ks461477_zm6dr3jm80000gn/T/ssh_pre_flight.sh'
[DEBUG   ] Child Forked! PID: 69993  STDOUT_FD: 20  STDERR_FD: 22
[DEBUG   ] Terminal Command: ssh remotemac -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=~/.ssh/mac_metal_admin_salt -o User=administrator rm /var/folders/35/5t5gx5ks461477_zm6dr3jm80000gn/T/ssh_pre_flight.sh
[ERROR   ] Error running ssh_pre_flight script ssh_pre_flight.sh
[DEBUG   ] LazyLoaded nested.output
administrator-10-246-2-12:
    ----------
    retcode:
        127
    stderr:
        /bin/sh: /var/folders/35/5t5gx5ks461477_zm6dr3jm80000gn/T/ssh_pre_flight.sh: No such file or directory
    stdout:
bash-3.2$
```

**Expected behavior**
Preflight script will run successfully.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
bash-3.2$ salt --versions-report
Salt Version:
          Salt: 3004.2
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.0
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.12
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.13 (default, May 10 2022, 16:32:48)
  python-gnupg: 0.4.4
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: 3.0.2
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: darwin 22.3.0 
        locale: UTF-8
       machine: x86_64
       release: 22.3.0
        system: Darwin
       version: 13.2 x86_64
 
bash-3.2$ ```
</details>

**Additional context**
Add any other context about the problem here.
A work-around is to run `salt-ssh` with a TMPDIR=<common-dir> env-var setting: 
```
TMPDIR=/var/tmp salt-ssh --pre-flight remotemac test.ping
```

### PR DESCRIPTION
**Pull request by rthille**
### What does this PR do?
This addresses [Issue
63695](https://github.com/saltstack/salt/issues/63695) by ensuring the destination tempdir on the target host is created before copying the ssh_pre_flight script to that target host.

### What issues does this PR fix or reference?
Fixes: [63695](https://github.com/saltstack/salt/issues/63695)

### Previous Behavior
salt-ssh from Mac to Mac or Linux would fail to execute ssh_preflight_hook due to locally determined tempdir not existing on target.

### New Behavior
Locally determined tempdir is created on the target prior to copying the script.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [-] Docs - Don't think any doc changes are needed.
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated - TBD

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by Ch3LL — CHANGES_REQUESTED** [review]
Thanks for this, can you add test coverage to ensure this doesn't regress in the future.

**Comment by Ch3LL** [comment]
Any updates here?

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Comment by dwoz** [comment]
@rthille We can re-open this if you want to get it into a release.

**Pull request closed without merging**
