### PR TITLE
Netapi docs rework

### LINKED ISSUE #63362: [DOCS] Need to document how to adding net-api clients to the master config
**Description**
As a result of https://github.com/saltstack/salt/pull/63050 , which is a breaking change, we need to add documentation to the NetAPI module introduction that explains in-depth how to add clients to the master config in order to prevent disruption of services.

**Type of documentation**
Core Salt documentation.

**Location or format of documentation**
The doc that needs to be updated is in `doc > topics > netapi > index.rst` .

We could put it in a different location if you think that would be more helpful.

### PR DESCRIPTION
**Pull request by barneysowood**
### What issues does this PR fix or reference?
Fixes: #63362

* Reworks the netapi modules documentation to make it clearer. Existing docs mixed information required to develop netapi modules into the main netapi modules docs in a way that made it difficult to understand for users just wanting to use netapi/salt-api.

* Add documentation on how to use the netapi_enable_clients config option and the required steps to test that (#63362)

### CODE REVIEW

**Comment by barneysowood** [comment]
@barbaricyawps - can you take a look at this? Ended up trying to re-work the netapi docs first as it I was struggling to add the new info on netapi_enable_clients without just making it even more difficult to follow.

Happy to split this into two PRs if that would be preferrable.

**Comment by barbaricyawps** [comment]
@barneysowood , this PR looks awesome to me. I only have a minor request, which is to make sure that you link to the new `netapi-enable-clients` topic in the 3006 release notes as well. That will ensure that impacted users can find these docs a little easier.

I'm also going to tap one of the core team members to do a technical review for accuracy.

**Review by barbaricyawps — DISMISSED** [review]

**Comment by barneysowood** [comment]
> @barneysowood , this PR looks awesome to me. I only have a minor request, which is to make sure that you link to the new `netapi-enable-clients` topic in the 3006 release notes as well. That will ensure that impacted users can find these docs a little easier.

Thanks for picking up on that - I've updated the ref in the 3006.0 release doc.

**Review by Ch3LL — APPROVED** [review]

**Review by barbaricyawps — APPROVED** [review]

**Comment by barbaricyawps** [comment]
@barneysowood , since the docs building tests are what matters, you're good. The others are purely due to flaky tests. If we get one more approval on this PR, I believe we can merge it in. I'll find another reviewer. 😄

**Comment by Ch3LL** [comment]
Since this is a docs only change, we only need to ensure the docs are passing. It does not require 3 reviews.

**Pull request merged**
