### PR TITLE
Carbon -> develop

### PR DESCRIPTION
**Pull request by cachedout**
Merge forward from carbon to develop

No conflicts.

### CODE REVIEW

**Comment by cachedout** [comment]
@meaksh or @isbm 

The new zypper tests are failing in this merge forward. Is there any chance either of you could take a look?

**Comment by meaksh** [comment]
@cachedout sure, lets take a look

**Comment by cachedout** [comment]
@meaksh Thanks! I am looking also but I'm sure you know this area much better than I do. :] I appreciate your quick response.

**Comment by cachedout** [comment]
@meaksh Take a look here and let me know if this is along the lines with what you're thinking: https://github.com/saltstack/salt/pull/37216

**Comment by rallytime** [comment]
I made a new merge-forward from carbon to develop in #37230. That has the zypper test fixes in it from Carbon. We'll see how that one runs. If the tests pass, I'll merge that one and close this one. Please stand by. :)

**Comment by rallytime** [comment]
Tests were green on #37230, so I think we can close. @cachedout Please feel free to reopen if you think we need it, but everything should be in the other merge forward.

**Pull request closed without merging**
