### PR TITLE
Add clone for qemu

### PR DESCRIPTION
**Pull request by Pixcell**
We needed a way to clone VM on Proxmox.

Looking on the API (http://pve.proxmox.com/pve2-api-doc/), we found a way to clone.
You can now use 'qemu' as technology, it supports 'sata0', 'ide2', 'net0', and 'ostype'.

You can also clone an existing VM (or template) by providing 
'clone' : True
'clone_from' : VMID to clone

Optional for clone : 'clone_name', 'clone_description', 'clone_format' (raw, qcow2, vmdk), 'clone_full' (0 or 1 (linked clone or full clone))

### CODE REVIEW

**Comment by jtand** [comment]
@Pixcell Thanks for this PR!

**Comment by rallytime** [comment]
Thanks @Pixcell!

It looks like you have a couple of [pylint errors](https://jenkins.saltstack.com/job/salt-pr-lint-n/10122/violations/file/salt/cloud/clouds/proxmox.py/). Would you mind cleaning those up?

Also, it'd be good to get some documentation added to the [Getting Started with Proxmox](https://docs.saltstack.com/en/latest/topics/cloud/proxmox.html) page to explain to others how to get this working.

**Comment by jfindlay** [comment]
Fixes #27941.

**Comment by Pixcell** [comment]
@rallytime I cleaned the pylint errors, how can I update the 'Getting started with Proxmox' guide ?

**Comment by rallytime** [comment]
@Pixcell Thanks! The Getting Started Docs are located in `salt/doc/topics/cloud/proxmox.rst`.

**Comment by cachedout** [comment]
I'll wait until the docs are updated before merging this, since it sounds like they're being written.

**Comment by Pixcell** [comment]
I updated the doc file. My english is far from perfect, so you may need to rewrite some of it. I'm truly sorry about that.

The note at the end gives some hints for further upgrade of the proxmox provider coverage.

I hope the new doc is good enough

**Comment by cachedout** [comment]
@Pixcell This is great, thank you! I'll just cc: @jacobhammons here who can clean up any small language errors that might be there but it looks good.

**Comment by rallytime** [comment]
Thanks @Pixcell! :D

**Pull request merged**
