### PR TITLE
[dockerng] Disable notset check

### LINKED ISSUE #29727: dockerng.running does not pull image as documented
According to https://docs.saltstack.com/en/latest/ref/states/all/salt.states.dockerng.html#salt.states.dockerng.running, "\[t]his state will pull the image if it is not present".  However, this doesn't seem to be the case:

```text
$ sudo salt-call -l info state.single dockerng.running name=hello image=ubuntu:14.04 cmd="/bin/echo 'Hello world'"
[INFO    ] Loading fresh modules for state activity
[INFO    ] Running state [hello] at time 22:12:37.878405
[INFO    ] Executing state dockerng.running for hello
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1594, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/dockerng.py", line 1411, in running
    image_id = __salt__['dockerng.inspect_image'](image)['Id']
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 2176, in inspect_image
    ret = _client_wrapper('inspect_image', name)
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 601, in wrapper
    return wrapped(*args, **salt.utils.clean_kwargs(**kwargs))
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 867, in _client_wrapper
    exc.explanation)
CommandExecutionError: Error 404: No such image: ubuntu:14.04

[INFO    ] Completed state [hello] at time 22:12:37.884175
local:
----------
          ID: hello
    Function: dockerng.running
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1594, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1491, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/dockerng.py", line 1411, in running
                  image_id = __salt__['dockerng.inspect_image'](image)['Id']
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 2176, in inspect_image
                  ret = _client_wrapper('inspect_image', name)
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 601, in wrapper
                  return wrapped(*args, **salt.utils.clean_kwargs(**kwargs))
                File "/usr/lib/python2.7/dist-packages/salt/modules/dockerng.py", line 867, in _client_wrapper
                  exc.explanation)
              CommandExecutionError: Error 404: No such image: ubuntu:14.04
     Started: 22:12:37.878405
    Duration: 5.77 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   5.770 ms
```

```text
$ sudo salt-call --versions-report
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-55-generic
         system: Ubuntu 14.04 trusty
```

(The version of `docker-py` is `1.4.0`.)

### PR DESCRIPTION
**Pull request by ticosax**
`_api_mismatch()` was a good idea.

But impractical since dockerd doesn't necessarily return all configuration items.

/cc @terminalmage 

fixes #29727

### CODE REVIEW

**Comment by oeuftete** [comment]
@ticosax I tested this change against the 2015.8 branch (using [my own fork](https://github.com/oeuftete/salt/tree/notset-check)) on my work's states.  Getting some issues when I run a subsequent highstate after my initial containers are created.  I can try to set up a minimal state if necessary to reproduce:

```text
[ERROR   ] Uncaught exception "'NoneType' object is not iterable" encountered while comparing existing container against desired configuration. Exception info follows:
  File "/usr/lib/python2.7/dist-packages/salt/states/dockerng.py", line 1561, in running
    defaults_from_image)
  File "/usr/lib/python2.7/dist-packages/salt/states/dockerng.py", line 191, in _compare
    actual_ports = sorted(actual_data)
```

**Comment by cachedout** [comment]
Let's hold on this until we can work out the possible issue reported by @oeuftete

**Comment by rallytime** [comment]
Some of the tests that were refactored/improved in #31326 are now failing in the merge-forward I am doing from 2016.3 to develop in #31462. I noticed that the test failures were similar to what this change is trying to solve (hitting the "Unable to compare configuration ..." message.) I just wanted to note that applying this change to my merge-forward branch fixes the test failures.

**Comment by ticosax** [comment]
@rallytime thanks for the notification.

@oeuftete I could reproduce your use case with
```
sudo salt-call -l error state.single dockerng.running name=hello image=alpine:3.3 ports=[8000] cmd="/bin/echo 'Hello world'"
```

I pushed a new commit to that branch.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Pull request merged**
