### PR TITLE
Add states to ensure an ENI has private ips present or absent.

### PR DESCRIPTION
**Pull request by ameneau**
### What does this PR do?
It adds two states to boto_ec2, private_ips_present and private_ips_absent

### What issues does this PR fix or reference?
N/A

### Tests written?
No

### CODE REVIEW

**Review by cachedout — APPROVED** [review]

**Comment by ryan-lane** [comment]
Missing test mode. Please revert.

**Comment by ameneau** [comment]
whoops, I did not notice test mode, thanks for pointing that out... I'll add it in now and have a commit for you shortly

**Comment by ryan-lane** [comment]
Thanks!

**Comment by ameneau** [comment]
Just double checking proper workflow here, this is the first time I've run into a pull request that's been merged and needed to be reverted.

1. Revert this merge, creating a new pull request
2. Have the revert merged in
3. Create a new pull request with the fixes in place

Or is there another way you'd prefer I get the changes in?

**Comment by ryan-lane** [comment]
Assuming we get a fix in for this, it can be a separate commit. I just want to make sure we don't do a release with a state that doesn't respect test mode :)

**Comment by ameneau** [comment]
Thanks @ryan-lane, I submitted a new commit adding test mode to the states, but it's not showing up in this pull request (I'm assuming, due to it already having been merged).

From your response, it sounds like this is just a one step process of creating a new pull request with the commit in this branch. Is that correct?

Thanks again!

**Pull request merged**
