### PR TITLE
allow 127 to be at the start of a hostname

### LINKED ISSUE #41241: salt minion ignores hostnames starting with 127, when generating minion id
### Description of Issue/Question
If we do not specify minion id in the minion configuration file explicitly, salt will try to come up with one and usually should take the hostname. However, if the hostname starts with 127 - it ignores it.

We believe this is caused by incorrect filter expression in https://github.com/saltstack/salt/blob/2016.11/salt/utils/network.py#L98

### Steps to Reproduce Issue
```
root@127foo:/# hostname
127foo
root@127foo:/# salt-call -l debug test.ping
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Guessing ID. The id can be explicitly set in /etc/salt/minion
[WARNING ] Cannot resolve address None info via socket: <class 'socket.gaierror'>
[DEBUG   ] Found minion id from generate_minion_id(): 172.18.0.4
...
root@127foo:/# cat /etc/salt/minion_id
172.18.0.4
```

### Versions Report
```
# salt-call --versions-report
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: 0.3.6
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.7
        machine: x86_64
        release: 4.4.44
         system: Linux
        version: debian 8.7
```
Applies to `2016.3.X` as well.

### PR DESCRIPTION
**Pull request by gtmanfred**
### What does this PR do?
We should only excempt ip addresses here, so there should be a dot after the 127.

### What issues does this PR fix or reference?
Fixes #41241

### Tests written?

No

### CODE REVIEW

**Comment by secumod** [comment]
This still somewhat limits the hostname selection. What if I want to have `127.foo` as a hostname?

**Comment by isbm** [comment]
@gtmanfred No. Because of [RFC 1123](https://tools.ietf.org/html/rfc1123) :smile:

**Comment by secumod** [comment]
@isbm can you elaborate? As I (quickly) read through the RFC - `127.foo` is pretty much allowed (not as a hostname, but full domain name to be exact), but does not change the point of this bug, because salt should use FQDN as a minion ID by default

**Comment by isbm** [comment]
@secumod yes, `127.foo` is `name.domain`. But we are looking at `name`. You _cannot_ have a dot in the _hostname_ as it is a separator between domain.

**Comment by secumod** [comment]
@isbm nope. salt looks at `fqdn`: https://github.com/saltstack/salt/blob/2016.11/salt/utils/network.py#L120

**Comment by isbm** [comment]
@secumod I wrote all that, actually. :-) It _first_ looks at the FQDN. And if there is one, you will get it on the exit. If none (which means you are in a trouble anyway), it will still try to fall-back to see what do you have inside the local names, where normally you should not place the domain (having no DNS).

**Comment by secumod** [comment]
I got it. But the point is if I do have FQDN and decide to use it as minion ID in my setup, for some reason I can use `123.foo.bar`, but cannot use `127.foo.bar` which is confusing.

My point is that `127.*` filter should be applied only to data, which passes full syntax check (according to the RFC mentioned by you) and classified as an IPv4 address.

**Comment by isbm** [comment]
@secumod uhm. Let me check (adding another unit test for it)

**Comment by isbm** [comment]
@secumod OK. That sux. Confirmed. I am fixing it. Thanks!

**Pull request closed without merging**
