### PR TITLE
Syndic fix: don't strip 'retcode' and 'success' from events.

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
### What does this PR do?

Keeps `retcode` and `success` job ret fields when it's forwarded by syndic.
### What issues does this PR fix or reference?
#34992
### Tests written?

No

### CODE REVIEW

**Comment by cachedout** [comment]
Excellent as always, @DmitryKuzmenko

**Comment by DmitryKuzmenko** [comment]
Thanks! =)

**Comment by szjur** [comment]
Excellent guys! :-) Now make it go to the job cache on the master (https://github.com/saltstack/salt/issues/35691) and I'll start loving SaltStack ;-)

**Comment by cachedout** [comment]
@szjur Tough crowd! ;]

If @DmitryKuzmenko has a little extra time he might be able to take a look. I'll investigate otherwise.

**Pull request merged**
