### PR TITLE
Adding the ability to specify a metric for static routes

### PR DESCRIPTION
**Pull request by jdito**
### What does this PR do?
Adds the ability to specify a metric for static routes. Useful if you have multiple routes to the same destination.
### What issues does this PR fix or reference?
None
### Previous Behavior
All routes entered with metric 0

### New Behavior
Routes entered with metric 0 if a metric is unset, or entered with custom metric

### Tests written?

No automated tests written. Have tested on CentOS 7.4 boxes, no Debian in my environment.

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

metric_test.sls:
```
{% for interface, args in pillar.get('routes', {}).items() %}
{{ interface }}:
  network.routes:
    - name: {{ interface }}
    - routes:
      {% for route, routeargs in args.items() %}
      - name: {{ route }}
        gateway: {{ routeargs.get('gateway') }}
        ipaddr: {{ routeargs.get('ipaddr') }}
        netmask: {{ routeargs.get('netmask') }}
        {% if routeargs.get('metric') %}
        metric: {{ routeargs.get('metric') }}
        {% endif %}
      {% endfor %}
{% endfor %}
```

metric_test.pillar:
```
routes:
  eth0:
    route-1:
      ipaddr: 192.168.2.0
      netmask: 255.255.255.0
      gateway: 10.1.1.1

  eth1:
    route-1:
      ipaddr: 192.168.2.0
      netmask: 255.255.255.0
      gateway: 10.1.2.1
      metric: 100
```

### CODE REVIEW

**Comment by cachedout** [comment]
I'm not comfortable merging this until it has been tested against Debian. 

@jdito is that something you can do?

**Comment by jdito** [comment]
Scrounged up a Ubuntu box, confirmed working.
```
local:
----------
          ID: eth0
    Function: network.routes
      Result: True
     Comment: Interface eth0 routes added.
     Started: 13:06:11.382600
    Duration: 13415.317 ms
     Changes:   
              ----------
              network_routes:
                  Added interface eth0 routes.
----------
          ID: eth1
    Function: network.routes
      Result: True
     Comment: Interface eth1 routes added.
     Started: 13:06:24.798274
    Duration: 2154.984 ms
     Changes:   
              ----------
              network_routes:
                  Added interface eth1 routes.

Summary for local
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
```

```
root@arch-miner-03:/etc# grep -r "gateway 10.1" .
./network/if-down.d/route-eth0:route del -net 192.168.2.0 netmask 255.255.255.0 gateway 10.1.1.1 dev eth0
./network/if-down.d/route-eth1:route del -net 192.168.2.0 netmask 255.255.255.0 gateway 10.1.2.1 dev eth1 metric 100
./network/if-up.d/route-eth0:route add -net 192.168.2.0 netmask 255.255.255.0 gateway 10.1.1.1 dev eth0
./network/if-up.d/route-eth1:route add -net 192.168.2.0 netmask 255.255.255.0 gateway 10.1.2.1 dev eth1 metric 100

```

**Comment by jdito** [comment]
Scrounged up an Ubuntu box, confirmed working in limited testing.
```
root@arch-miner-03:/etc# grep -r "ip route" .
./network/if-down.d/route-eth0:ip route del 192.168.2.0/255.255.255.0 via 10.1.1.1 dev eth0
./network/if-down.d/route-eth1:ip route del 192.168.2.0/255.255.255.0 via 10.1.2.1 dev eth1 metric 100
./network/if-up.d/route-eth0:ip route add 192.168.2.0/255.255.255.0 via 10.1.1.1 dev eth0
./network/if-up.d/route-eth1:ip route add 192.168.2.0/255.255.255.0 via 10.1.2.1 dev eth1 metric 100
```

**Review by cachedout — APPROVED** [review]

**Comment by rallytime** [comment]
Welcome @jdito! Thanks for submitting this.

**Pull request merged**
