### PR TITLE
Fix Jinja template cache loading

### LINKED ISSUE #62042: [BUG] removed Jinja templates can still be loaded from cache
**Description**
Found a bug where an included Jinja template can still be loaded from the cache despite being removed from the Salt filesystem.

**Setup**

Create two test files on the Salt filesystem:

```yaml
# /srv/salt/jinja_cache.sls
{% from "jinja_cache.jinja" import myvar -%}

test:
  test.show_notification:
    - text: {{ myvar }}
```

```yaml
# /srv/salt/jinja_cache.jinja
{% set myvar = "hello" -%}
```
  
**Steps to Reproduce the behavior**

Applying the state file as-is produces the expected "hello" notification:

```bash
# salt-call state.apply jinja_cache
local:
----------
          ID: test
    Function: test.show_notification
      Result: True
     Comment: hello
     Started: 21:19:26.078569
    Duration: 0.329 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   0.329 ms
```

...and changing the variable text like so:

```yaml
{% set myvar = "world" -%}
```

...results in a changed notification text to match "world" from the variable as expected:

```bash
# salt-call state.apply jinja_cache
local:
----------
          ID: test
    Function: test.show_notification
      Result: True
     Comment: world
     Started: 21:19:37.647817
    Duration: 0.894 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   0.894 ms
```

However, removing the included jinja file _after it has already been cached_ can result in the file being loaded from cache despite no longer being present on the Salt filesystem:

```bash
# mv jinja_cache.jinja{,.bak}
```

```bash
# salt-call state.apply jinja_cache
local:
----------
          ID: test
    Function: test.show_notification
      Result: True
     Comment: world
     Started: 21:22:55.004962
    Duration: 0.386 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   0.386 ms
```

**Expected behavior**
After the Jinja file is removed from the Salt filesystem, the state should failed to run with a `TemplateNotFound` error. Loading cached files can result in user surprise when complex map loading decisions are made.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3004.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: 2.1.11
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-20-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```
</details>

### PR DESCRIPTION
**Pull request by nicholasmhughes**
### What does this PR do?
This PR fixes an issue where Jinja templates can be loaded from the cache despite being removed from the Salt filesystem. See issue for more details.

### What issues does this PR fix or reference?
Fixes: #62042 

### Previous Behavior
Salt would load cached Jinja templates if the files were removed from the Salt filesystem.

### New Behavior
If a file is cached but no longer present on the Salt filesystem, it will not be loaded.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by nicholasmhughes** [comment]
re-run pr-amazon-2-x86_64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-fedora-35-x86_64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-centos-7-x86_64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-freebsd-130-amd64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-macosx-catalina-x86_64-py3-pytest

**Review by waynew — CHANGES_REQUESTED** [review]

**Comment by waynew** [comment]
Well. That's fun. Looks like it's still failing for both freebsd & mac :suspect:

**Comment by nicholasmhughes** [comment]
re-run pr-amazon-2-x86_64-py3-pytest

**Comment by nicholasmhughes** [comment]
@waynew I had to build a FreeBSD box... but I was able to clear those last two checks.

**Comment by Ch3LL** [comment]
@waynew can you re-review please

**Review by waynew — APPROVED** [review]
:+1: Pretty sure that I poked at this locally last time I reviewed. LGTM

**Comment by myii** [comment]
Unfortunately, this PR appears to have resulted in a regression when working with Jinja relative imports, at least across all Linux platforms:

* https://gitlab.com/myii/salt-image-builder/-/pipelines/546881711

```salt
local:
    Data failed to compile:
----------
    Rendering SLS 'base:test_jinja.grains' failed: Jinja error: ./grains.jinja
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/salt/utils/templates.py", line 469, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.7/dist-packages/salt/utils/jinja.py", line 219, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./grains.jinja
; line 1
---
{%- from "./grains.jinja" import grains with context %}    <======================
test_jinja/grains/cmd.run:
  cmd.run:
    - name: pwd
[...]
```

I'm a bit short of time at the moment but I'll try to debug further when I get a chance.

**Comment by myii** [comment]
OK, this seems to confirm that the regression has been introduced by the merge of this PR.

I've rerun the pipeline without this PR's commits and all passing fine again (all four states are using Jinja relative imports):

* https://gitlab.com/myii/salt-image-builder/-/pipelines/546923757

```sls
local:
----------
          ID: test_jinja/grains/cmd.run
    Function: cmd.run
        Name: pwd
      Result: True
     Comment: Command "pwd" run
     Started: 14:14:49.481086
    Duration: 6.682 ms
     Changes:   
              ----------
              pid:
                  145
              retcode:
                  0
              stderr:
              stdout:
                  /root
Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   6.682 ms
local:
----------
          ID: test_jinja/opts/cmd.run
    Function: cmd.run
        Name: pwd
      Result: True
     Comment: Command "pwd" run
     Started: 14:14:51.407127
    Duration: 6.81 ms
     Changes:   
              ----------
              pid:
                  175
              retcode:
                  0
              stderr:
              stdout:
                  /root
Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   6.810 ms
local:
----------
          ID: test_jinja/pillar/cmd.run
    Function: cmd.run
        Name: pwd
      Result: True
     Comment: Command "pwd" run
     Started: 14:14:53.373170
    Duration: 6.791 ms
     Changes:   
              ----------
              pid:
                  205
              retcode:
                  0
              stderr:
              stdout:
                  /root
Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   6.791 ms
local:
----------
          ID: test_jinja/salt/cmd.run
    Function: cmd.run
        Name: pwd
      Result: True
     Comment: Command "pwd" run
     Started: 14:14:55.344258
    Duration: 6.793 ms
     Changes:   
              ----------
              pid:
                  235
              retcode:
                  0
              stderr:
              stdout:
                  /root
Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   6.793 ms
```

**Comment by myii** [comment]
The following bisect should help (b3dacf1188a6507dc01efa6ab7d480a82c11f6b6):

```console
b3dacf1188a6507dc01efa6ab7d480a82c11f6b6 is the first bad commit
commit b3dacf1188a6507dc01efa6ab7d480a82c11f6b6
...
...

    handle local paths properly

 salt/utils/jinja.py | 3 +++
 1 file changed, 3 insertions(+)
```

**Comment by nicholasmhughes** [comment]
@myii , I was able to reproduce in an operational environment. I installed Salt from the master branch today on a fresh Debian 10 machine using the bootstrap script.

```bash
curl -L https://bootstrap.saltproject.io | sudo sh -s -- -M git master
```

Versions Report:

```yaml
Salt Version:
          Salt: 3005+0na.b18281e
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.14.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 22.3.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-18-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```

And then pulled down the test files the pipeline is running onto the master:

```bash
root@d10-saltgit-01:/srv# pwd
/srv

root@d10-saltgit-01:/srv# git clone https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder.git
Cloning into 'salt-image-builder'...
remote: Enumerating objects: 4012, done.
remote: Counting objects: 100% (714/714), done.
remote: Compressing objects: 100% (162/162), done.
remote: Total 4012 (delta 579), reused 662 (delta 544), pack-reused 3298
Receiving objects: 100% (4012/4012), 2.48 MiB | 6.01 MiB/s, done.
Resolving deltas: 100% (3144/3144), done.

root@d10-saltgit-01:/srv# mkdir salt

root@d10-saltgit-01:/srv# cp -r salt-image-builder/test/test_jinja /srv/salt/

root@d10-saltgit-01:/srv# ll salt/test_jinja
total 48
-rw-r--r-- 1 root root  45 May 27 20:37 grains.jinja
-rw-r--r-- 1 root root 111 May 27 20:37 grains.sls
-rw-r--r-- 1 root root  41 May 27 20:37 grains.yaml
-rw-r--r-- 1 root root  41 May 27 20:37 opts.jinja
-rw-r--r-- 1 root root 105 May 27 20:37 opts.sls
-rw-r--r-- 1 root root  40 May 27 20:37 opts.yaml
-rw-r--r-- 1 root root  45 May 27 20:37 pillar.jinja
-rw-r--r-- 1 root root 111 May 27 20:37 pillar.sls
-rw-r--r-- 1 root root  45 May 27 20:37 pillar.yaml
-rw-r--r-- 1 root root  41 May 27 20:37 salt.jinja
-rw-r--r-- 1 root root 105 May 27 20:37 salt.sls
-rw-r--r-- 1 root root  49 May 27 20:37 salt.yaml
```

"Normal" runs work, but local doesn't:

```bash
root@d10-saltgit-01:/srv# salt-call state.apply test_jinja.grains
local:
----------
          ID: test_jinja/grains/cmd.run
    Function: cmd.run
        Name: pwd
      Result: True
     Comment: Command "pwd" run
     Started: 21:13:51.801142
    Duration: 3.235 ms
     Changes:   
              ----------
              pid:
                  15193
              retcode:
                  0
              stderr:
              stdout:
                  /root

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   3.235 ms

root@d10-saltgit-01:/srv# salt-call --local state.apply test_jinja.grains
[ERROR   ] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/salt/utils/templates.py", line 469, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.7/dist-packages/salt/utils/jinja.py", line 219, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./grains.jinja

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/salt/utils/templates.py", line 216, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/local/lib/python3.7/dist-packages/salt/utils/templates.py", line 514, in render_jinja_tmpl
    "Jinja error: {}{}".format(exc, out), line, tmplstr, trace=tracestr
salt.exceptions.SaltRenderError: Jinja error: ./grains.jinja
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/salt/utils/templates.py", line 469, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.7/dist-packages/salt/utils/jinja.py", line 219, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./grains.jinja

; line 1

---
{%- from "./grains.jinja" import grains with context %}    <======================

test_jinja/grains/cmd.run:
  cmd.run:
    - name: pwd

[...]
---
[CRITICAL] Rendering SLS 'base:test_jinja.grains' failed: Jinja error: ./grains.jinja
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/salt/utils/templates.py", line 469, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.7/dist-packages/salt/utils/jinja.py", line 219, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./grains.jinja

; line 1

---
{%- from "./grains.jinja" import grains with context %}    <======================

test_jinja/grains/cmd.run:
  cmd.run:
    - name: pwd

[...]
---
local:
    Data failed to compile:
----------
    Rendering SLS 'base:test_jinja.grains' failed: Jinja error: ./grains.jinja
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/salt/utils/templates.py", line 469, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.7/dist-packages/salt/utils/jinja.py", line 219, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./grains.jinja

; line 1

---
{%- from "./grains.jinja" import grains with context %}    <======================

test_jinja/grains/cmd.run:
  cmd.run:
    - name: pwd

[...]
---
```

The lines in question were actually added to satisfy an existing test... which seems to have absolute paths in local mode. Changing that logic to check for an absolute path seems to solve the problem for both cases. I'll put in a PR presently.

**Pull request merged**
