### PR TITLE
Fix connect issue in event init

### PR DESCRIPTION
**Pull request by cachedout**
Fix issue with 100% CPU. Refs #26366 and #26301.

Refs the original PR where this issue was introduced in #26000

### CODE REVIEW

**Comment by aboe76** [comment]
@cachedout 

on develop the event.py file is different than
but I have tested it with this and I can confirm that cpu load drops

```
class SaltEvent(object):
    '''
    Warning! Use the get_event function or the code will not be
    RAET compatible
    The base class used to manage salt events
    '''
    def __init__(self, node, sock_dir=None, opts=None, listen=True):
        self.serial = salt.payload.Serial({'serial': 'msgpack'})
        self.context = zmq.Context()
        self.poller = zmq.Poller()
        self.cpub = False
        self.cpush = False
        if opts is None:
            opts = {}
        self.opts = opts
        if sock_dir is None:
            sock_dir = opts.get('sock_dir', None)
        if salt.utils.is_windows() and not hasattr(opts, 'ipc_mode'):
            opts['ipc_mode'] = 'tcp'
        self.puburi, self.pulluri = self.__load_uri(sock_dir, node)
        if listen:
            self.connect_pub()
        self.pending_tags = []
        self.pending_rtags = []
        self.pending_events = []
        if not self.cpub:
            self.connect_pub()
        self.__load_cache_regex()
```

**Comment by cachedout** [comment]
@aboe76 Yes, this will not merge cleanly but the idea is the same. Glad it's working! Thanks for testing.

**Comment by aboe76** [comment]
ow I have just updated with a question after looking somewhat longer at the code.

**Comment by driskell** [comment]
Could be related to the merge duplicating the `connect_pub`? After it has two calls in I if, one surrounded by `if listen` and the one in this PR. Maybe that's related - poll is returning true but when reading it's reading wrong one? The duplication needs sorting either way. I didn't spot it when I fixed up the merge bits.

**Comment by aboe76** [comment]
ow testing, it now with my change, and salt-call works on minion but not from a salt \* state.highstate.

**Comment by aboe76** [comment]
the if statement is necessary, so I removed the broken code.

**Comment by waynew** [comment]
@cachedout what branch is this on?

**Comment by waynew** [comment]
@cachedout  Never mind, I found it :)

I pulled from your clone and checked out that branch. It gave me a different version on the versions report, but everything appeared to be fine.

To make sure, though, I went back and installed the version from the AUR and verified that it pegged out my CPU (it did), and then I manually made this change to my own `event.py` and restarted my salt master service.

:+1: 

CPU usage is now a-OK!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Pull request merged**
