### PR TITLE
Add support for 'virt-what' in the 'virtual' grain.

### PR DESCRIPTION
**Pull request by eliasp**
This add support for [`virt-what`](http://people.redhat.com/~rjones/virt-what/) to `salt/grains/core.py` to determine the `virtual` grain.
`virt-what` has become the defacto standard-tool to determine whether a system is running on bare-metal or in a virtualized environment.
It supports a wide range of OS' and is able to detect a big number of virtualization technologies.

I implemented the support for `virt-what` in a way which makes the result from `virt-what` the #1 prioritized result in case it was found as it covers way more platforms/technologies than the rest of the code for the `virtual` grain which should IMHO only serve as fallback in case `virt-what` is not available.

`virt-what` is (at least) on RHEL/CentOS 7 installed by default.

### CODE REVIEW

**Comment by jfindlay** [comment]
@eliasp, since 2015.2.0 is in the rc phase, I am easily convinced otherwise, but since we're trying to stabilize 2015.2.0 I think we should be putting new features in develop.  I'll let @thatch45 make the final decision here, though.

**Comment by eliasp** [comment]
Oh, sorry… completely missed that. Feel free to close this PR, then I'll rebase against develop and open a new PR.

**Comment by jfindlay** [comment]
@eliasp, no problem.  Thanks for the excellent contribution.

**Comment by eliasp** [comment]
@jfindlay Opened a new PR now: #21356

**Pull request closed without merging**
