### PR TITLE
add files.abspath to the file module

### PR DESCRIPTION
**Pull request by vernondcole**
### What does this PR do?

Creates an additional function in the `files` module for `abspath`.

### What issues does this PR fix or reference?

Occasionally in complex scripts, it is necessary to supply a parameter which is required to be an absolute path. This is trivial in most cases.  

In my use case, my user is (indirectly) running salt-call to deploy a build environment into a child of his source directory -- wherever that might be. Inside the system, I have a number of salt state calls (like virtualenv.managed) which require an absolute path. My final solution requires that the user execute `sudo salt-call --config-dir=a_local_directory ...` from which I can determine my absolute path based on `opts['config_dir']`. That is both obscure and brittle, and took me a day to discover. 

My first instinct was to simply call `files.abspath` -- but I found that it did not exist.

### Tests written?

Yes, also includes a unit test for files.normpath.

### Commits signed with GPG?

Yes, except for the first one.

### CODE REVIEW

**Review by twangboy — DISMISSED** [review]

**Comment by twangboy** [comment]
Please create a test for this. We're requiring tests for all new code. We'll have to got back and create a test for `normpath` at some point.... technical debt... and stuff

**Comment by vernondcole** [comment]
Okay. Here is a unit test for abspath.  I also threw in the one for normpath for free. Bon apetit.

**Comment by vernondcole** [comment]
@twangboy Looks like this is ready to merge at this point.

**Comment by vernondcole** [comment]
This checked successfully yesterday. This morning it was no longer merge ready, so I clicked "Update branch". The error on Centos-7 is not my code, it's machine setup.

**Comment by waynew** [comment]
I restarted the centos-7 build. 🤞 Let's see if that runs...

**Comment by waynew** [comment]
Looks like we've either got to pin against an older version of requests, since Python 3.4 is EOL, or ensure we have a more modern Python3 on Centos 7

**Comment by waynew** [comment]
Hey @vernondcole would you mind rebasing this on `master`? We've changed our branching/release strategy. With a rebase on master we should be able to get this in for Sodium (3001), assuming all the tests are passing.

**Comment by waynew** [comment]
@vernondcole are you still willing/able to drive this to completion? It should be relatively simple to rebase this on master. Feel free to reach out to me on IRC (#salt on freenode) or community slack if you need help! 👍

**Comment by vernondcole** [comment]
Sorry. I have been unusually busy, and I get burned every time I ask git to
do a rebase. I will see if PyCharm can get it right, anon.

**Comment by waynew** [comment]
@vernondcole I went ahead and rebased this on master. Feel free to double check it does what you expected.

**Comment by vernondcole** [comment]
@waynew Thank you!  Yes it looks perfect.

**Comment by waynew** [comment]
re-run all

**Comment by waynew** [comment]
re-run all

**Comment by waynew** [comment]
Okay, rebased on master, let's try this one, shall we?

**Comment by waynew** [comment]
re-run opensuse15-py3

**Review by waynew — APPROVED** [review]
FINALLY! 🚀 🍰 ✨ 🎸 🎉 🌮 👍 🖤

**Comment by dwoz** [comment]
Closing due to lack of activity. Anyone should feel free to re-open or create a new PR if they want to see this through to the end.

**Pull request closed without merging**
