### PR TITLE
Fixes min_docker_py for VALID_CREATE_OPTS

### PR DESCRIPTION
**Pull request by rbjorklin**
### What does this PR do?

Fixes min_docker_py for VALID_CREATE_OPTS
### What issues does this PR fix or reference?
#32886 #32887
### Previous Behavior

Crash with stack trace
### New Behavior

Functional
### Tests written?

No

### CODE REVIEW

**Comment by rallytime** [comment]
Hi @rbjorklin - does the change in #32886 depend on this PR? I'm wondering because once that PR is resolved, if that needs to go back to an earlier branch, then this one will likely need to be moved as well. But we can cross that bridge later. 

In the meantime, this change appears to be causing many test failures. I suspect the mocking for the tests just needs to be updated for the new reference to `dockerng.version`. Can you take a look? Let us know if you run into trouble.

**Comment by rbjorklin** [comment]
Yes #32886 depends on this since I decided to use the min_docker_py functionality which turned out to be broken. I'll have a look at the tests and see if I can figure it out!

**Comment by ticosax** [comment]
The error reported in #32887 is not very pythonic because this undefined function is availalble in the namespace of the originated function, both come from the same module.
When I checked the source code of the state execution module, I spotted [this](https://github.com/saltstack/salt/blob/develop/salt/states/dockerng.py#L66-76).

It seems the call of `salt.utils.namespaced_function(_validate_input, globals())` is responsible the reported bug. Because `globals()` from `states.dockerng` doesn't contains `_get_docker_py_versioninfo()` from `modules.dockerng`. This is a nasty bug.

I'd rather remove `salt.utils.namespaced_function()` call if possible. It should fix the issue.

`__context__` act like a cache and caching requires invalidation under certain circumstances. I'd rather avoid using it more than necessary in order to limit potential regressions. Accessing `docker.version_info` is not causing performance hit. So relying on a caching mechanism seems not best suited to solve that bug.

@terminalmage Do you recall why you had to rely on `salt.utils.namespaced_function()` ?

**Comment by rbjorklin** [comment]
@ticosax & @terminalmage Do you guys want try and solve this in a better way or should I just fix the tests?

**Comment by rbjorklin** [comment]
Noticed that someone had already named the key for the docker-py version so I changed mine in accordance with [this](https://github.com/saltstack/salt/blob/develop/salt/modules/dockerng.py#L701-L717).

**Comment by ticosax** [comment]
@rbjorklin Fair enough, I'll try to do something about it.

**Comment by ticosax** [comment]
Another attempt to fix same bug #32943

**Comment by ticosax** [comment]
I can explain what `salt.utils.namespaced_function()` is doing.
It is related to the way salt is monkey patching all states and execution modules.

`salt.utils.namespaced_function()` makes sure, when globals namespace is modified (dunder dictionaries like `__salt__` or `__context__` are added), the imported function from `salt.modules.dockerng` can see them. 
Once the function `_validate_input` is imported in `salt.states.dockerng` its `__globals__` is detached from `salt.modules.dockerng`.
So, `__context__` dunder dicts are not available...

yep it looks like a hack over a hack. But I'm not going to fix monkey patching done by salt on all execution modules.

**Comment by rbjorklin** [comment]
Superseeded by #32943

**Pull request closed without merging**
