### PR TITLE
[WIP] Fix proxmox list images

### PR DESCRIPTION
**Pull request by laundry-96**
### What does this PR do?
When running the list-images function, passing in the location to list now works properly
### What issues does this PR fix or reference?
Fixes:
https://github.com/saltstack/salt/issues/40621
### Previous Behavior
Only listed images on the local drive
### New Behavior
Lists images on the specified drive
### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by DmitryKuzmenko** [comment]
@laundry-96 it looks you've done your changes against another branch. Please always create you development branch on top of master branch in salt repo.

**Comment by waynew** [comment]
Hey @laundry-96 thanks for the PR! It looks like you might be on the wrong branch where you've done your work - if you can rebase against `master` that would be a good thing 👍

**Review by waynew — CHANGES_REQUESTED** [review]
Hey @laundry-96 are you still planning on finishing this? We definitely appreciate your efforts so far! We realize that priorities can change, and contributing to Salt may not be at the top of your list. If this is the case for you, no response needed - if we haven't heard back from you after a week, we'll go ahead and close this PR and add the "on hold" label. At any point in the future if you (or someone else) is ready to pick this back up, just let us know and we'll be happy to re-open the PR so we can get it merged.

If you need help writing documentation, we have a [documentation working group](https://github.com/saltstack/docs-hub) that would love to help out.

If you're struggling with writing tests, reach out to the [testing working group](https://github.com/saltstack/community/tree/master/working_groups/wg-Testing) or attend one of the [Test Clinics on Twitch](https://www.twitch.tv/saltstackinc/schedule).

Thanks again!

**Comment by laundry-96** [comment]
Hello!

Sorry, been busy ;) 

I should make my changes off of master, right?

**Comment by ScriptAutomate** [comment]
> Hello!
> 
> Sorry, been busy ;)
> 
> I should make my changes off of master, right?

@laundry-96 To make things a bit easier, I'm closing this PR out. Your best bet would be to checkout a new branch from the latest `master` in your fork, and then make your commit/update there before pushing a new PR. It looks like you meant to only make this change if I understand correctly:
- https://github.com/saltstack/salt/pull/58619/commits/9e9bf9223fc0fef18c0d959defb58dcfe5f8d8c2

Otherwise, as can be seen, the PR is stuffed with over 300k line changes with all the tests breaking. Your new PR will look fresh, and will be more easily welcomed into the salt universe. Feel free to reach out with any questions on the Salt community slack. Both @waynew and I are on there, along with other maintainers and community members. :)

**Note:** We are also in the midst of updating our docs to remove references to the `develop` branch, as we know this has caused confusion and grief in the contributing process! Lots of updates in progress, many seen here: #57645

**Pull request closed without merging**
