### PR TITLE
Virt aluminium fixes

### PR DESCRIPTION
**Pull request by cbosdo**
### What does this PR do?

Fixes the iothread parameter introduced in PR #59007 before it's released.
Also remove the deprecated `update` parameter in `virt.defined` and `virt.running` states.

### Merge requirements satisfied?
- [X] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by s0undt3ch — APPROVED** [review]

**Comment by cbosdo** [comment]
@dwoz could you merge that one PR? it's all green, ACKed and not too complex

**Comment by cbosdo** [comment]
re-run pr-freebsd122-py3-pytest

**Comment by cbosdo** [comment]
re-run pr-centos7-py3-tcp-pytest

**Comment by cbosdo** [comment]
re-run pr-debian9-py3-pytest

**Review by s0undt3ch — APPROVED** [review]

**Comment by cbosdo** [comment]
re-run macosxmojave-py3-pytest

**Comment by cbosdo** [comment]
re-run opensuse15-py3-pytest

**Comment by cbosdo** [comment]
re-run ubuntu2004-py3-pytest

**Comment by cbosdo** [comment]
@dwoz this one is ACKed and green after a long time to keep up with the rebase and tests randomly failing or timing out. Could you merge it?

**Comment by cbosdo** [comment]
The commits from this PR are also contained in the bigger (and ACKed) PR #59146

**Comment by cbosdo** [comment]
Closing since #59146 has been merged

**Pull request closed without merging**
