### PR TITLE
Git present mod run check

### PR DESCRIPTION
**Pull request by tyhunt99**
### What does this PR do?
Adds ability to specify unless and onlyif for git.present

### What issues does this PR fix or reference?
#54206 

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by dmurphy18 — CHANGES_REQUESTED** [review]
@tyhunt99 Can you also supply some tests to exercise your PR's changes.  SaltStack is now asking for tests with PRs to ensure higher stability of Salt

**Comment by waynew** [comment]
@tyhunt99 thanks for the PR! As David mentioned, we are asking for tests to go with PRs - you don't have to test the rest of this function, just the changes that you've made. If you're unsure where to start, please let us know and we'll do what we can to help. Thanks again!

**Comment by mchugh19** [comment]
If #55974 is accepted, this can be closed out. Various state modules had their own requisites system. As the global requisites have gained functionality, these individual ones have not kept up (as this PR attempts to partially correct). #55974 removes the local state requisites in favor of the super set globals and thus this PR would no longer be needed.

**Comment by sagetherage** [comment]
> If #55974 is accepted, this can be closed out. Various state modules had their own requisites system. As the global requisites have gained functionality, these individual ones have not kept up (as this PR attempts to partially correct). #55974 removes the local state requisites in favor of the super set globals and thus this PR would no longer be needed.

closing

**Pull request closed without merging**
