### PR TITLE
Fix for roster grains in jinja templates

### PR DESCRIPTION
**Pull request by edgan**
### What does this PR do?
It fixes an issue where roster grains worked for processing on the machine where salt-ssh is run from, but didn't work for any process, like jinja templates, that is processed on the remote machine.

### What issues does this PR fix or reference?
#36313

### Previous Behavior
Roster grains would be missing in jinja templates

### New Behavior
Roster grains are not missing in jinja templates

### Tests written?
No

### CODE REVIEW

**Comment by cachedout** [comment]
Go Go Jenkins!

**Review by cachedout — CHANGES_REQUESTED** [review]
A test failed here: https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/10351/testReport/junit/unit.config.schemas.ssh_test/RosterItemTest/test_roster_config_validate/

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@edgan Did you see my above comment about the failing test? We can't merge this until that is resolved.

**Comment by edgan** [comment]
Yes, I think the test is bogus, or needs to be rewritten. I can't see how my code change would cause it. But I have been trying to get the test suite running on CentOS 7 in vagrant to prove my point. If I am wrong then I can debug it, and see what is causing it.

**Comment by edgan** [comment]
I get the impression this was a transient error on the jenkins slave, or an issue at the time based on the rest of the code in develop.

The output.txt file is the test output on CentOS 7 running the full salt test suite, "./runtests.py --ssh", on the current develop branch with my patch. I would attach salt-runtests.log, but it is 31mb, and GitHub won't let me. If you really want it I will give you a link.

Here is the part of salt-runtests.log that mentions test_roster_config_validate.

```
salt-runtests.log:
20:30:31,692 [tests.support.unit                                        :378 ][DEBUG   ] >>>>> START >>>>> unit.config.schemas.test_ssh.RosterItemTest.test_roster_config_validate
20:30:31,703 [tests.support.unit                                        :382 ][DEBUG   ] <<<<< END <<<<<<< unit.config.schemas.test_ssh.RosterItemTest.test_roster_config_validate
```
[output.txt](https://github.com/saltstack/salt/files/920797/output.txt)

**Comment by cachedout** [comment]
@edgan OK. Let's have you rebase this against the head of develop and see if the error re-occurs when the test runs then.

**Comment by cachedout** [comment]
@edgan Would you mind please rebasing this? Thanks very much.

**Comment by edgan** [comment]
I have rebased to develop.

**Comment by cachedout** [comment]
@edgan This doesn't look like it was rebased against the develop branch. It contains a lot of unrelated commits. Can you either try again or close this PR and open a new one that's based against the head of develop? Thanks.

**Comment by edgan** [comment]
Closing this pull request. I am going to remake it fresh.

**Pull request closed without merging**
