### PR TITLE
LXC cloud fixes

### PR DESCRIPTION
**Pull request by cellscape**
This pull request includes changes that I had to do in order to make salt-cloud with LXC and cloud state management work on my side.

Changes include mostly fixes for minor bugs like using incorrect variables and proper cloud state handling with changes reported back and test=True honoured.

I don't yet know salt internals good enough to make proper changes however I believe those can be a good start for review. I've tried hard to not break other clouds functionality but tested only with LXC. Please let me know if there is something wrong, I'll fix it.

I'm especially not confident of last 3 commits, they are workarounds and not proper fixes. Still work for me but I'll be happy to do it right way if someone shows the direction.

As for 2015.2 and develop branches, couple of changes were backported from 2015.2, few are not applicable anymore because of LXC revamp but some changes can still be applied.

### CODE REVIEW

**Comment by thatch45** [comment]
@terminalmage do you see any issues in here?

**Comment by cellscape** [comment]
I've also applied some of those changes on top of 2015.5.0 and added another new fix for it. How to better proceed with that? May be just rebase this on 2015.5 since it seems I'm the only one who wants to use salt-cloud with LXC? :) Or should I create new pull request after (and if) this one is merged?

**Comment by rallytime** [comment]
@cellscape Thanks very much for contributing! As far as the 2015.5 branch goes, we merge the 2014.7 branch into 2015.5, and then 2015.5 into develop every day or two to help keep fixes consistent and applied to all applicable branches, so a new pull request for 2015.5 won't be needed. This fix, once merged, will propagate through to the other branches as we merge forward. You can read more information about that [here](http://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch).

**Comment by basepi** [comment]
In most cases, what @rallytime said would be true; however, LXC support was rewritten in 2015.5 and so I will not be merging any of the salt/modules/lxc changes forward. I'm still evaluating the changes to salt/states/cloud.py in my merge forward.

**Comment by basepi** [comment]
Final merge forward can be seen here: https://github.com/saltstack/salt/pull/23783

**Comment by cellscape** [comment]
@basepi I still would like to see cellscape@fb24f0cf02efe4a35b533060156abda3f03916b8 merged in. `salt.modules.lxc.init` in 2015.5 sets result to `False` when failed to clone container but not when failed to create.

I would also like to still be able to pass LXC template options in `salt.modules.lxc.cloud_init_interface` similar to cellscape@792e1021f260a10cb9c5f986967b0e7f1be611d6 . However in 2015.5 profile keywords overriding no longer works, need to explicitly set `options` value in returned dictionary. I'm willing to provide new pull request if such change and argument naming are fine. 

What do you think?

**Pull request merged**
