### PR TITLE
Fix dockerng.network_* name matching

### LINKED ISSUE #41982: dockerng.network_* matches too easily
### Description of Issue/Question
The `dockerng.image_present` and `dockerng.image_absent` states both incorrectly think that a network is present if another network whose name partially matches the specified network is present.

For example, if the network `abcdef` already exists and `dockerng.image_present` is used to create the network `cde`, it'll just return with a message saying no action's required because the network already exists.

### Setup
```
# ./docker/network/test_present.sls
test_network_present:
  dockerng.network_present:
    - name: cde
```
```
# ./docker/network/test_absent.sls
test_network_absent:
  dockerng.network_absent:
    - name: cde
```

### Steps to Reproduce Issue
The steps below show that if the network `abcdef` already exists then `dockerng.image_present` doesn't think it needs to create the network `cde`, and `dockerng.image_absent` attempts to remove `cde` it even though it's not actually present:
```
user@host ~ $ sudo docker network ls | grep cde
e982840fa7a1        abcdef              bridge              local
user@host ~ $ sudo salt '*' state.apply docker.network.test_present test=True
host.domain:
----------
          ID: test_network_present
    Function: dockerng.network_present
        Name: cde
      Result: True
     Comment: Network 'cde' already exists.
     Started: 15:14:34.886654
    Duration: 5.399 ms
     Changes:   

Summary for host.domain
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   5.399 ms
user@host ~ $ sudo salt '*' state.apply docker.network.test_present
host.domain:
----------
          ID: test_network_present
    Function: dockerng.network_present
        Name: cde
      Result: True
     Comment: Network 'cde' already exists.
     Started: 15:14:41.984847
    Duration: 9.433 ms
     Changes:   

Summary for host.domain
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   9.433 ms
user@host ~ $ sudo salt '*' state.apply docker.network.test_absent test=True
host.domain:
----------
          ID: test_network_absent
    Function: dockerng.network_absent
        Name: cde
      Result: None
     Comment: The network 'cde' will be removed
     Started: 15:16:26.964736
    Duration: 4.956 ms
     Changes:   

Summary for host.domain
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
Total run time:   4.956 ms
user@host ~ $ sudo salt '*' state.apply docker.network.test_absent
host.domain:
----------
          ID: test_network_absent
    Function: dockerng.network_absent
        Name: cde
      Result: False
     Comment: Failed to remove network 'cde': Error 404: {"message":"network cde not found"}
     Started: 15:16:14.349035
    Duration: 9.475 ms
     Changes:   

Summary for host.domain
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   9.475 ms
ERROR: Minions returned with non-zero exit code
```

Note that in this example the `test=True` is working because I've tested this on top of my changes in #41977.

### Versions Report
```
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.16.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

### PR DESCRIPTION
**Pull request by abulford**
Fixes #41982

### What does this PR do?
Updates the states so that they loop through the list of networks returned from `dockerng.networks` to check that one of the networks returned fully matches the name of the network that needs to be ensured to be present or absent.

Another option would be to add an argument to the `dockerng.networks` execution module to enable strict matching.  This would probably be preferable to repeating the logic in the states, but I didn't want to meddle too much as the execution module is currently just wrapping the docker-py library.

### What issues does this PR fix or reference?
#41982

### Previous Behavior
`dockerng.network_present` would not create a network if another network with a partially matching name already existed, `docker.network_absent` would try to remove a network which didn't exist if there was another network in existence with a partially matching name.

```
user@host ~ $ sudo docker network ls | grep cde
e982840fa7a1        abcdef              bridge              local
user@host ~ $ sudo salt '*' state.apply docker.network.test_present test=True
host.domain:
----------
          ID: test_network_present
    Function: dockerng.network_present
        Name: cde
      Result: True
     Comment: Network 'cde' already exists.
     Started: 15:14:34.886654
    Duration: 5.399 ms
     Changes:   

Summary for host.domain
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   5.399 ms
user@host ~ $ sudo salt '*' state.apply docker.network.test_present
host.domain:
----------
          ID: test_network_present
    Function: dockerng.network_present
        Name: cde
      Result: True
     Comment: Network 'cde' already exists.
     Started: 15:14:41.984847
    Duration: 9.433 ms
     Changes:   

Summary for host.domain
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   9.433 ms
user@host ~ $ sudo salt '*' state.apply docker.network.test_absent test=True
host.domain:
----------
          ID: test_network_absent
    Function: dockerng.network_absent
        Name: cde
      Result: None
     Comment: The network 'cde' will be removed
     Started: 15:16:26.964736
    Duration: 4.956 ms
     Changes:   

Summary for host.domain
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
Total run time:   4.956 ms
user@host ~ $ sudo salt '*' state.apply docker.network.test_absent
host.domain:
----------
          ID: test_network_absent
    Function: dockerng.network_absent
        Name: cde
      Result: False
     Comment: Failed to remove network 'cde': Error 404: {"message":"network cde not found"}
     Started: 15:16:14.349035
    Duration: 9.475 ms
     Changes:   

Summary for host.domain
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   9.475 ms
ERROR: Minions returned with non-zero exit code
```

### New Behavior
The `dockerng.network_present` and `dockerng.network_absent` states correctly recognise whether a network is present or absent, even if another network with a partially matching name exists:
```
user@host ~ $ sudo docker network ls | grep cde
e982840fa7a1        abcdef              bridge              local
user@host ~ $ sudo salt '*' state.apply .docker.network.test_present test=True
host.domain.com:
----------
          ID: test_network_present
    Function: dockerng.network_present
        Name: cde
      Result: None
     Comment: The network 'cde' will be created
     Started: 16:21:02.715381
    Duration: 4.757 ms
     Changes:   

Summary for host.domain.com
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
Total run time:   4.757 ms
user@host ~ $ sudo salt '*' state.apply .docker.network.test_present
host.domain.com:
----------
          ID: test_network_present
    Function: dockerng.network_present
        Name: cde
      Result: True
     Comment: 
     Started: 16:21:41.720032
    Duration: 501.139 ms
     Changes:   
              ----------
              created:
                  ----------
                  Id:
                      246079aa13211fe681949b2f6f5066c2b425e631645296e078a0acff4fafbf9a
                  Warning:

Summary for host.domain.com
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 501.139 ms
user@host ~ $ sudo docker network ls | grep cde
e982840fa7a1        abcdef              bridge              local
246079aa1321        cde                 bridge              local
user@host ~ $ sudo salt '*' state.apply .docker.network.test_absent test=True
host.domain.com:
----------
          ID: test_network_absent
    Function: dockerng.network_absent
        Name: cde
      Result: None
     Comment: The network 'cde' will be removed
     Started: 16:21:52.552362
    Duration: 5.432 ms
     Changes:   

Summary for host.domain.com
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
Total run time:   5.432 ms
user@host ~ $ sudo salt '*' state.apply .docker.network.test_absent
host.domain.com:
----------
          ID: test_network_absent
    Function: dockerng.network_absent
        Name: cde
      Result: True
     Comment: 
     Started: 16:22:09.832561
    Duration: 383.447 ms
     Changes:   
              ----------
              removed:
                  None

Summary for host.domain.com
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 383.447 ms
user@host ~ $ sudo docker network ls | grep cde
e982840fa7a1        abcdef              bridge              local
user@host ~ $ sudo salt '*' state.apply .docker.network.test_absent test=True
host.domain.com:
----------
          ID: test_network_absent
    Function: dockerng.network_absent
        Name: cde
      Result: True
     Comment: Network 'cde' already absent
     Started: 16:22:18.913120
    Duration: 5.008 ms
     Changes:   

Summary for host.domain.com
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   5.008 ms
user@host ~ $ sudo salt '*' state.apply .docker.network.test_absent
host.domain.com:
----------
          ID: test_network_absent
    Function: dockerng.network_absent
        Name: cde
      Result: True
     Comment: Network 'cde' already absent
     Started: 16:22:24.240611
    Duration: 5.547 ms
     Changes:   

Summary for host.domain.com
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   5.547 ms
```

### Tests written?
No

### CODE REVIEW

**Comment by terminalmage** [comment]
These changes will need to be made separately in the 2017.7 branch, since this state has been moved into salt/states/docker_network.py. Can you open up a separate PR against 2017.7?

**Comment by abulford** [comment]
@terminalmage I've created #42006 to get this change put into 2017.7.

**Comment by rallytime** [comment]
@abulford It looks like there is a related test failing with this change: https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/12525/ 

Do you mind taking a look?

**Comment by abulford** [comment]
@rallytime sorry about that, I saw there were failures as a result of my first PR (#41977) which didn't seem to be related and stupidly assumed they would be the same failures showing up here.  I think I can see where the problem is, I'll try to get the tests running locally and submit a fix.

**Comment by abulford** [comment]
@rallytime I've updated the PR with the fixed test, I also added a regression test and modified an existing test so that it covers this scenario.  This is my first foray into SaltStack code (and Python...!) so I'm not sure how well I've complied with coding standards etc, please let me know if you need me to make any changes.  I'll wait for some feedback on these changes before updating 2017.7 to save myself any wasted effort.

**Comment by rallytime** [comment]
@abulford Nice work and welcome to Salt (and Python)! I think this looks good, but it would probably be good to get another review from @terminalmage as well.

Thank you for your contributions!

**Review by rallytime — APPROVED** [review]

**Comment by abulford** [comment]
@rallytime thanks :), glad to help!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
@terminalmage bump - can you review this when you get a moment? I think everything here is ready to go as the test failure here is not relevant to this change. (It's an old one that has been fixed upstream in the branch.)

**Review by terminalmage — APPROVED** [review]
Sorry, I didn't catch the ping a few weeks ago, I thought this had been merged.

**Comment by rallytime** [comment]
Thanks all! Let's get this in. :)

**Pull request merged**
