### PR TITLE
Nagios module bugfix and additional refactoring

### PR DESCRIPTION
**Pull request by isbm**

### CODE REVIEW

**Comment by isbm** [comment]
While lint fix is valid and I just fixed it, I still have a trouble to understand what is going on with the tests...

**Comment by rallytime** [comment]
Oh, I meant to comment on here earlier. We had some test failures (quite a few, as you can see) merged into the develop branch. It has since been resolved, but when you pulled develop down to make your changes, the failures came down too. I don't see any in there that are related to your code.

**Comment by isbm** [comment]
Jenkins time. :)

**Comment by isbm** [comment]
Something funky is happening with the tests... :fire:

**Comment by rallytime** [comment]
@isbm If you want those test failures to clear up, you'll need to rebase your pull request with the current develop. You can do that like so:
```
git fetch upstream
git checkout isbm-nagios-module-opts
git rebase upstream/develop
git push --force origin isbm-nagios-module-opts  # carefully
```

**Comment by isbm** [comment]
@rallytime @thatch45 @jfindlay Seems alright now?

**Comment by rallytime** [comment]
Yep, from a testing perspective this looks good! I'll defer to @thatch45 for the final review here.

**Pull request merged**
