### PR TITLE
Add k8s module and state documentation

### PR DESCRIPTION
**Pull request by titilambert**
Hello,
I just forgot to add Kubernetes module and state to the documentation.

### CODE REVIEW

**Comment by cachedout** [comment]
Great! Thanks, @titilambert

**Comment by titilambert** [comment]
Could you add my name to contributor file ? please :)

**Comment by titilambert** [comment]
BTW @cachedout 2min to merged it !!! your respond time is really awesome !

**Comment by cachedout** [comment]
@titilambert We're always here! :] 

Feel free to submit another PR to add yourself to the contributors file and I will get it merged for you.

**Comment by titilambert** [comment]
Ok ! thanks !

**Comment by cachedout** [comment]
You're welcome. :]

**Pull request merged**
