### PR TITLE
Bug: syspaths all or nothing

### PR DESCRIPTION
**Pull request by plastikos**
Allow partial override of syspaths:

Previously if any one option was missing in salt/_syspaths.py then an
exception was raised and none of the existing settings were used - only
defaults.  BOOTSTRAP is not set in the setup.py template and causes
an exception thus preventing all of the _syspaths.py settings from being
utilized.  Maybe it should be added to the template in setup.py too.

### CODE REVIEW

**Comment by thatch45** [comment]
@s0undt3ch please review

**Comment by s0undt3ch** [comment]
The issue were syspaths would only be evaluated to defaults was already fixed and is what you're changing now.

Are you saying that with this last version of syspaths the issue still occurs?

At first glance your fix seems over-engineered to an already too much engineered but needed approach....

Can you tell me how exactly you're triggering the syspaths issue?

Thanks!

**Comment by plastikos** [comment]
My bad: looks like this is a failure in 2014.7.1 that was later fixed - I failed to test salt/syspaths.py from the develop branch.

I personally believe that what I submitted is more concise and understandable then what is there, but ultimately I realize that's quite subjective.

**Comment by thatch45** [comment]
Has the bug you are referencing been fixed in the 2014.7 branch? Do we need to backport anything?

**Comment by plastikos** [comment]
It is broken in the 2014.7 branch.  Notice in salt/syspaths.py it tries to import ROOT_DIR, CONFIG_DIR, . . ., CLOUD_DIR, INSTALL_DIR, BOOTSTRAP from _syspaths.py.  If that fails with an ImportError then it uses defaults for *all* of the imports.  The trouble is that CLOUD_DIR, INSTALL_DIR and BOOTSTRAP are never written into _syspaths.py by setup.py (look for INSTALL_SYSPATHS_TEMPLATE).

**Comment by plastikos** [comment]
Notice that the salt/syspaths.py in develop branch never tries to import CLOUD_DIR, INSTALL_DIR, BOOTSTRAP (which are all detectable run-time).

**Comment by s0undt3ch** [comment]
I'll fix 2014.7, can't remember why I didn't fix that branch too...

**Comment by plastikos** [comment]
I'm curious to know what this line is syspaths.py does:

           ROOT_DIR = r'c:\salt' or '/'

Am I missing something or is the "or '/'" superfluous?

**Comment by s0undt3ch** [comment]
Windows vs Linux, ie, not superfluous.

**Comment by s0undt3ch** [comment]
@plastikos bah! yes, superfluous.....

**Comment by thatch45** [comment]
@plastikos @s0undt3ch what is the status here? If you give it the thumbs up @s0undt3ch you can merge this

**Comment by plastikos** [comment]
As far as I'm concerned this fixes an old bug that is no longer existent.  This pull request can be discarded.

I personally believe that this is cleaner than the existent code - but that's personal taste and calling my baby beautiful.

   * this has fewer lines of code
   * this has less repetition which means that adding options is easier
   * this has fewer conditionals which make it easier to understand
   * this has more comments describing what is happening
   * this has more flexibility for what is written to _syspaths.py (no longer requires all settings to be written there)

It was written because we pulled up to 2014.7.1 which failed to start because it could not find installation paths.  I failed to check if this had been fixed in develop.

Merging it is up to you.  I won't cry either way.

**Comment by s0undt3ch** [comment]
I'm closing this PR since its not really broken and the 2014.7 branch is now also fixed.

The other changes you have in this PR, can you please submit them in a new PR?

Thanks!

**Comment by plastikos** [comment]
Two of the changes were specifically for syspaths.py; the other has already been merged.

**Comment by s0undt3ch** [comment]
Thanks!

**Pull request closed without merging**
