### PR TITLE
WIP:Add path utils and directory modules / states

### PR DESCRIPTION
**Pull request by ArthurREGNARD**
### What does this PR do?
Add new utils to manage paths. 

Add Modules and States to managed directories. To be powerfull than a file.managed or copy_recurse. 

### What issues does this PR fix or reference?
None

### New Behavior
Add some utils / modules / states to manage paths and directories. 
### Tests written?
Yes

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by Ch3LL — CHANGES_REQUESTED** [review]
Looks like there is a merge conflict. Is this still a WIP? Let me know when it is not and I'll give it a thorough review.

**Comment by Ch3LL** [comment]
@ArthurREGNARD any updates here?

**Comment by ArthurREGNARD** [comment]
It’s an old pull request, if you are interested in, I can manage conflicts, else, I close it ..,

**Comment by Ch3LL** [comment]
Yeah, I think there is value if your willing to work it to completion it would be appreciated.

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
