### PR TITLE
[2017.7] Fix scheduled jobs if `when` parameter is a list

### PR DESCRIPTION
**Pull request by vutny**
### What does this PR do?
It makes master-side scheduled jobs great again. 🇺🇸 🎆 

### What issues does this PR fix or reference?
This is a port of PR #42077 to properly resolve possible merge-forward conflicts.

### Previous Behavior
Salt Master just skips last `when` time definition if it should be triggered on next loop cycle after previous job run.
For example: UTC time is 12:00pm. You have following job scheduled:
```yaml
schedule:
  Test Job:
    function: test.stdout_print
    when:
      - 12:01pm
      - 12:02pm
```
In this case, Master would successfully run the job at `12:01pm`, but skip the jobs at `12:02pm`.

### New Behavior
Salt Master executes all scheduled jobs specified as `when` list on next loop cycle after each job's time has come.

### Tests written?
No.

### CODE REVIEW

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@garethgreenaway Can you please have a look at this?

**Review by garethgreenaway — APPROVED** [review]

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Pull request merged**
