### PR TITLE
Move build files to salt/pkg/windows

### PR DESCRIPTION
**Pull request by twangboy**
This mirrors the way osx and other build scripts are maintained
This was originally hosted on salt-windows-dev

https://github.com/saltstack/zh/issues/492

### CODE REVIEW

**Comment by cachedout** [comment]
@twangboy Please rebase this.

**Comment by twangboy** [comment]
@cachedout It says it's up to date. I've fetched and pulled but to no avail...

**Comment by cachedout** [comment]
It looks fine now. Your most recent commit may have pulled in the needed changes.

**Comment by cachedout** [comment]
@meggiebot Can we get this in?

**Pull request merged**
