### PR TITLE
Catch `CommandExecutionError` when stopping a service

### PR DESCRIPTION
**Pull request by eliasp**
### What does this PR do?

It adds handling of a previously unhandled exception in `states.service.dead`.

### What issues does this PR fix or reference?

None

### Previous Behavior
The state `service.dead` could fail like this:
```
An exception occurred in this state: Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 1913, in call
    **cdata['kwargs'])
  File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1898, in wrapper
    return f(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\states\service.py", line 593, in dead
    func_ret = __salt__['service.stop'](name, **stop_kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\win_service.py", line 453, in stop
    'Failed To Stop {0}: {1}'.format(name, exc[2]))
CommandExecutionError: Failed To Stop w3svc: The service cannot accept control messages at this time.
```

### New Behavior
The state will now handle this case properly with `Result: False` and show the corresponding exception error string as comment instead.

### Tests written?
No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by eliasp** [comment]
The CI failures look to me like an issue with the Win2016 build environments...

**Comment by waynew** [comment]
A couple of comments on the PR:

We're now requiring tests for all PRs. If you're not sure how to write them [you can schedule time with me to help](https://calendar.google.com/calendar/selfsched?sstoken=UURWQ2dRZDlKU0twfGRlZmF1bHR8OWU3N2NmZjgwODY5ODVjNGU3NWRhMTRhYTI4MDM3ZmY).

We're also changing to a single branch release strategy, so if you could rebase this PR against `master`, force push to your branch, and then edit this PR to be against `master`, that would be swell!

---

Aside from that, this *seems* reasonable, though I'm kind of surprised it's presenting like this. I'll have to look at other places in the code that are getting/raising this error to see how they're doing it 🤔

**Comment by dwoz** [comment]
@eliasp This needs to be re-opened against the `master` branch. We are no
longer accepting PRs to the `2019.2`. If this fixes a bug in a `2019.2.x`
release, please make note of it in your PR to `master`. Thanks!

**Comment by eliasp** [comment]
Re-filed again `master` in #55508

**Pull request closed without merging**
