### PR TITLE
better atom extraction from portage version string

### PR DESCRIPTION
**Pull request by ribx**
portage_config: use dep_getkey for atom extraction to allow non existing versions and packages, added unit test to verify behaviour

### What does this PR do?
1. Fixes problem where _portage_config.enforce_nice_config_ aborts because of non existing packages or non existing versions.
2. Add Unit Tests to test the behaviour
3. Fix some other minor issues that appeared after writing the unit tests

### Changes in behaviour
Package definitions like _category/*_ had been written to a file called _/etc/portage.*/category_, which will break if there is also a definition of _category/package_, which will create a directory at _/etc/portage.*/category/_. As a solution to this I place _category/*_ definitions in _/etc/portage.*/category__.

### What issues does this PR fix or reference?
#35004
#34424

### Tests written?
Yes, unit tests in _test_portage_config.py_.

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
@terminalmage Didn't you write much of this back in the day? I'm wondering if you might be a good choice to review this.

**Comment by terminalmage** [comment]
@cachedout I did not. The code I contributed to ebuild.py mostly has had to do with putting in the code required to support pkgs/sources, and other things supported among most or all of the pkg virtuals. I'm not really familiar with how Gentoo's package database works, to be honest.

**Review by cachedout — CHANGES_REQUESTED** [review]
Hi @ribx 

There are a few style errors that need to be cleaned up. They are here: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/14320/violations/file/tests/unit/modules/test_portage_config.py/

**Comment by cachedout** [comment]
@ribx Did you see the request above for some additional changes here?

**Comment by ribx** [comment]
I saw them, but I am not sure, what I have to do to apply them. Also: all jenkins pages I try to access return 404.

**Comment by cachedout** [comment]
Sorry about that, @ribx. Here is the correct URL.

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/14510/violations/file/tests/unit/modules/test_portage_config.py/

**Review by cachedout — APPROVED** [review]

**Pull request merged**
