### PR TITLE
Salt Virt cleanup

### PR DESCRIPTION
**Pull request by techhat**
This PR largely contains cleanup work, but it also includes switching key management from auto-accept to manually creating and pre-populating keys.

Ping @Ch3LL.

### CODE REVIEW

**Comment by techhat** [comment]
Also, deprecated "hyper" in favor of "host".

**Comment by cachedout** [comment]
@techhat There is a lint error that suggests that a variable might need to be renamed. Could you please take a look?

**Comment by techhat** [comment]
@cachedout, fixed.

**Comment by cachedout** [comment]
@techhat Thanks!

**Pull request merged**
