### PR TITLE
Windows Perms for file.directory and file.managed

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?
Adds ability to set owner and user/group permissions for ``file.directory`` and ``file.managed``. Also fixes an issue with ``salt.utils.win_dacl.set_owner`` where you couldn't set ownership to a group you weren't a member of or another group. Tried to make minimal changes to the ``file.py`` state module and make changes in ``win_file.py`` execution module where possible.

Adds 4 new parameters to ``file.directory`` and ``file.managed``.

win_owner (str)
win_perms (dict)
win_deny_perms (dict)
win_inheritance (bool)

Ultimately the goal is to implement this into the rest of the state functions in the ``file.py`` state module.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/28920

### Previous Behavior
Permissions settings weren't being set on ``file.directory`` and ``file.managed``

### New Behavior
You can now set permissions for ``file.directory`` and ``file.managed``

### Tests written?
No

### CODE REVIEW

**Review by cachedout — COMMENTED** [review]
It looks to me like a number of these functions are just copied and pasted directly from the Linux file management module. Could we cross-call in these instances instead?

**Comment by damon-atkins** [comment]
I think the better approach is to create a shared code library.
file_lib.py  that windows and posix import.  I am sure their is a better name.

**Comment by thatch45** [comment]
I would push that these functions differ enough that we should separate them out. We have too long of a history of having windows/linux issues crop up in the file modules. I think this approach is wiser at this point. Also the function signatures differ, windows file management is just plain too different. What do you think @cachedout ?

**Comment by cachedout** [comment]
@thatch45 Do you mean breaking out just the exec module or the state module as well? I think that splitting out the exec module might make some sense but splitting the state seems kind of like a pity.

**Comment by thatch45** [comment]
Good point, @twangboy do you think we could keep the state modules together? Even with the extra arguments the module layer should be able to abstract enough to allow us to keep the states together

**Comment by twangboy** [comment]
@thatch45 The state module is NOT separated. Just the execution module.

**Comment by thatch45** [comment]
Doh! You are right!
Everything looks fine here to me

**Comment by cachedout** [comment]
But we still haven't addressed my original concern or the follow-up by @damon-atkins. :-/

We still have a whole pile of code that's been copy and pasted around yet again.

**Comment by damon-atkins** [comment]
Open, Read, Write are all the same in general. It's just perms which are different.
In general one should do a create new temp file, and rename over the top when updating files, just to make sure you have the disk space to complete the operation.
i.e Share Code on temp file, apply access controls to temp file, and rename to target

I said in different ticket, to read the first few lines of a file to determine the line feed.

There was a short  discussion within https://github.com/saltstack/salt/issues/36991#issuecomment-256347428 on platform specific arguments. 

You have POSIX.1e ACL on Unix/Linux/BSD/OSX/etc , NFS ACL on ZFS & FreeBSD UFS & OSX 10.4+  , and Windows ACL

POSIX Example in one line
`u::rw-,u:lisa:rw-,g::r--,g:toolies:rw-,m::r--,o::r,g:toolies:rw,u:lisa:rw,u::wr,g::r,o::r,m::r`
ZFS/NFS Example
`chmod A=owner@:rwxpcCosRrWaAdD:fd:allow,group@:rwxp:fd:allow,everyone@::fd:allow test1.dir`
Windows
`icacls "C:\demo\example" /grant:r Administrators:(OI)(CI)F /T /grant:r ss64Dom\jsmith:(OI)(CI)M /T`

Please look at it as a plan solution to have a common interface.  
e.g. acl_nfs, acl_win, acl_posix or something.

I am not saying implement it all, but to map out the interface for all.

**Comment by twangboy** [comment]
@damon-atkins The problem is that user, group, and mode don't translate to the Windows ACL. New parameters were added to handle ownership and permissions in Windows. All permissions are set using the `win_dacl` utility to avoid shelling out in Windows (unicode translation problems).

@cachedout I assume you're talking about the mkdir, makedirs, and makedirs_perms functions. I did change these in `win_file.py` so that all directory creation is handled by the `mkdir` function. Some of the logic is similar but differs greatly when it goes to set permissions and ownership. I wouldn't think you'd want a bunch of gated Windows calls in `file.py` when we already have a `win_file.py`. 
Additionally, I kept the function names the same so I wouldn't have to edit the state module too much.

**Pull request merged**
