### PR TITLE
Catch CommandExecutionError in pkg states

### LINKED ISSUE #33873: refresh: True not working with pkg.installed state
### Description of Issue/Question
Hi, first of all this is a bug with Windows minions that appears to affect minions with version 2015.8.0+, and I believe this to be a regression introduced at the same time that winrepo-ng was introduced).

Specifically, I am trying to use  *refresh: True* with the *pkg.latest* state, but it's not working. pkg.installed won't work unless pkg.refresh_db has been ran first.

### Setup
Here is an example sls file
```
chrome installed:
   pkg.latest:
     - name: chrome
     - refresh: true
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

```
salt '011000' saltutil.clear_cache
salt '011000' state.apply chrome_managed
```

The eventual output includes the following
```
011000:
----------
          ID: chrome installed
    Function: pkg.latest
        Name: chrome
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1591, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\states\pkg.py", line 1392, in latest
                  cur = __salt__['pkg.version'](*desired_pkgs, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 197, in version
                  val = __salt__['pkg_resource.version'](*names, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\modules\pkg_resource.py", line 184, in version
                  pkgs = __salt__['pkg.list_pkgs'](versions_as_list=True, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 236, in list_pkgs
                  name_map = _get_name_map()
                File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 951, in _get_name_map
                  name_map = get_repo_data().get('name_map', {})
                File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 934, in get_repo_data
                  'Windows repo cache doesn\'t exist, pkg.refresh_db likely '
              CommandExecutionError: Windows repo cache doesn't exist, pkg.refresh_db likely needed
     Started: 15:15:23.521000
    Duration: 10.0 ms
     Changes:
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

salt-master is 2015.8.8.2

minions tried were 2015.8.8.0-3, 2015.8.8-2.

### PR DESCRIPTION
**Pull request by terminalmage**
Recent changes to winrepo cause a CommandExecutionError to be raised
when there is no winrepo cache. This catches these and gracefully fails
the state.

Resolves #33873.

### CODE REVIEW

**Comment by terminalmage** [comment]
This likely needs a secondary fix, hold off on merging.

**Comment by hrumph** [comment]
I now think that it makes sense to merge this and the rest of the work can be done in the devel branch as soon as this gets to the devel branch.

**Comment by hrumph** [comment]
I am not happy with this PR. I ask that this not be merged at least until I understand it.

**Comment by hrumph** [comment]
ok I'm sorry everyone. merge it and i'll try it out.

**Comment by cachedout** [comment]
@terminalmage Linter caught an issue: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/2740/violations/file/salt/states/pkg.py/

**Comment by terminalmage** [comment]
Lint error should now be resolved.

**Pull request merged**
