### PR TITLE
[WIP] boto3_vpc

### PR DESCRIPTION
**Pull request by github-abcde**
### What does this PR do?
It adds a pure boto3-based execution-module (state-module will be added when execution module is done).
It seemed to me that it was better to create a separate module than to hack the old one (`boto_vpc`) into bits to keep and bits to deprecate.
The module is setup in such a way that new functions are easily added and current functions easily updated. Most functions are taken literally from the boto3 spec, with the exception that all resources that must be specified by id can now also be specified by the filters used in the `describe`-function for that resource (via `lookup_X`-functions). My experience from using this (and other boto) module(s) is that you rarely know the resource ID beforehand, and work mostly using either name tags or other attributes for which you know the value. So being able to lookup resources by any allowed filter value helps temendously.

Update: After noticing a lot of duplicate code, I have generalized certain functions: `describe_resource`, `lookup_resource`, `create_resource`, `wait_resource`, as well as created an easier way to add boto waiter configurations to salt.
These generalized functions have been added to `salt/utils/boto3mod.py` and `salt/modules/boto3_generic.py` (the latter only contains `lookup_resource` and needs to be in a module because it uses `__salt__` to call lookup-functions for variable services).
As such, since the service used here is named `ec2`, I have renamed the module from `boto3_vpc` to `boto3_ec2`. (the unit-testfile has been appropriately renamed as well).

The following is a list of functions that I intend to implement and write tests for. Checked items have tests:
- [ ] accept_vpc_endpoint_connections
- [ ] accept_vpc_peering_connection
- [ ] allocate_address
- [ ] associate_address
- [ ] associate_dhcp_options
- [ ] associate_route_table
- [x] associate_subnet_cidr_block
- [x] associate_vpc_cidr_block
- [x] attach_internet_gateway
- [ ] attach_network_interface
- [ ] attach_volume
- [ ] attach_vpn_gateway
- [ ] authorize_security_group_egress
- [ ] authorize_security_group_ingress
- [ ] cancel_spot_fleet_requests
- [ ] cancel_spot_instance_requests
- [ ] copy_image
- [ ] copy_snapshot
- [ ] create_customer_gateway
- [ ] create_dhcp_options
- [ ] create_image
- [x] create_internet_gateway
- [ ] create_key_pair
- [ ] create_launch_template
- [ ] create_nat_gateway
- [ ] create_network_acl
- [ ] create_network_acl_entry
- [ ] create_network_interface
- [ ] create_route
- [ ] create_route_table
- [ ] create_security_group
- [ ] create_snapshot
- [x] create_subnet
- [ ] create_tags
- [ ] create_volume
- [x] create_vpc
- [ ] create_vpc_endpoint
- [ ] create_vpc_endpoint_service_configuration
- [ ] create_vpc_peering_connection
- [ ] create_vpn_connection
- [ ] create_vpn_gateway
- [ ] crud_security_group_rule
- [ ] delete_customer_gateway
- [ ] delete_dhcp_options
- [x] delete_internet_gateway
- [ ] delete_key_pair
- [ ] delete_nat_gateway
- [ ] delete_network_acl
- [ ] delete_network_acl_entry
- [ ] delete_network_interface
- [ ] delete_route
- [ ] delete_route_table
- [ ] delete_security_group
- [ ] delete_snapshot
- [x] delete_subnet
- [ ] delete_tags
- [ ] delete_volume
- [x] delete_vpc
- [ ] delete_vpc_endpoint_service_configurations
- [ ] delete_vpc_endpoints
- [ ] delete_vpc_peering_connection
- [ ] delete_vpn_connection
- [ ] delete_vpn_gateway
- [ ] deregister_image
- [ ] describe_account_attributes
- [ ] describe_addresses
- [ ] describe_availability_zones
- [ ] describe_customer_gateways
- [ ] describe_dhcp_options
- [ ] describe_egress_only_internet_gateways
- [ ] describe_elastic_gpus
- [ ] describe_fleets
- [ ] describe_fpga_image_attribute
- [ ] describe_fpga_images
- [ ] describe_hosts
- [ ] describe_iam_instance_profile_associations
- [ ] describe_image_attribute
- [ ] describe_images
- [ ] describe_instance_attribute
- [ ] describe_instance_credit_specifications
- [ ] describe_instance_status
- [ ] describe_instances
- [x] describe_internet_gateways
- [ ] describe_ipv6_pools
- [ ] describe_launch_templates
- [ ] describe_key_pairs
- [ ] describe_local_gateway_route_tables
- [ ] describe_local_gateways
- [ ] describe_managed_prefix_lists
- [ ] describe_nat_gateways
- [ ] describe_network_acls
- [ ] describe_network_interface_attribute
- [ ] desribe_network_interface_permissions
- [ ] describe_network_interfaces
- [ ] describe_placement_groups
- [ ] describe_public_ipv4_pools
- [ ] describe_regions
- [ ] describe_route_tables
- [ ] describe_security_group_references
- [ ] describe_security_groups
- [ ] describe_snapshot_attribute
- [ ] describe_snapshots
- [ ] describe_spot_fleet_instances
- [ ] describe_spot_fleet_requests
- [ ] describe_spot_instance_requests
- [ ] describe_stale_security_groups
- [x] describe_subnets
- [ ] describe_tags
- [ ] describe_transit_gateways
- [ ] describe_volume_attribute
- [ ] describe_volumes
- [ ] describe_volumes_modifications
- [x] describe_vpc_attribute
- [x] describe_vpc_classic_link
- [x] describe_vpc_classic_link_dns_support
- [ ] describe_vpc_endpoint_connections
- [ ] describe_vpc_endpoint_service_configurations
- [ ] describe_vpc_endpoint_service_permissions
- [ ] describe_vpc_endpoint_services
- [ ] describe_vpc_endpoints
- [ ] describe_vpc_peering_connections
- [x] describe_vpcs
- [ ] describe_vpn_connections
- [ ] describe_vpn_gateways
- [x] detach_internet_gateway
- [ ] detach_network_interface
- [ ] detach_volume
- [ ] detach_vpn_gateway
- [x] disable_vpc_classic_link
- [x] disable_vpc_classic_link_dns_support
- [ ] disassociate_address
- [ ] disassociate_route_table
- [x] disassociate_subnet_cidr_block
- [x] disassociate_vpc_cidr_block
- [x] enable_vpc_classic_link
- [x] enable_vpc_classic_link_dns_support
- [ ] import_key_pair
- [ ] lookup_availability_zone
- [ ] lookup_address
- [ ] lookup_customer_gateway
- [ ] lookup_dhcp_options
- [ ] lookup_egress_only_internet_gateway
- [ ] lookup_fpga_image
- [ ] lookup_image
- [ ] lookup_instance
- [x] lookup_internet_gateway
- [ ] lookup_key_pair
- [ ] lookup_local_gateway
- [ ] lookup_managed_prefix_list
- [ ] lookup_nat_gateway
- [ ] lookup_network_acl
- [ ] lookup_network_interface
- [ ] lookup_route_table
- [ ] lookup_security_group
- [ ] lookup_snapshot
- [ ] lookup_spot_instance_request
- [x] lookup_subnet
- [ ] lookup_tag
- [ ] lookup_transit_gateway
- [ ] lookup_volume
- [x] lookup_vpc
- [ ] lookup_vpc_endpoint
- [ ] lookup_vpc_endpoint_service
- [ ] lookup_vpc_endpoint_service_configuration
- [ ] lookup_vpc_peering_connection
- [ ] lookup_vpn_connection
- [ ] lookup_vpn_gateway
- [ ] modify_network_interface_attribute
- [ ] modify_spot_fleet_request
- [x] modify_subnet_attribute
- [x] modify_vpc_attribute
- [ ] modify_vpc_endpoint_service_configuration
- [ ] modify_vpc_endpoint_service_permissions
- [ ] modify_vpc_tenancy
- [ ] reboot_instances
- [ ] register_image
- [ ] reject_vpc_peering_connection
- [ ] release_address
- [ ] replace_network_acl_association
- [ ] replace_network_acl_entry
- [ ] replace_route
- [ ] replace_route_table_association
- [ ] request_spot_fleet
- [ ] request_spot_instances
- [ ] revoke_security_group_egress
- [ ] revoke_security_group_ingress
- [ ] start_instances
- [ ] stop_instances
- [ ] terminate_instances

I will probably add more functions to the above list, as I intend to implement all functions that Moto supports, so they can also be tested. However, a few extra functions are already added which I thought to be a good idea (and in hindsight might not have been that good), or allow for a lot of convenience (`crud_security_group_rule` for instance).
It is my hope that eventually all functions supported by boto3 will be implemented, not just for EC2, but for all services. But I'm taking this one step at a time.

### What issues does this PR fix or reference?
None that I'm aware of. It is one (small) step in deprecating anything based on boto2.

### Previous Behavior
`boto_vpc` uses a mix of boto2 and boto3. Features have not been updated for years. (for example no support for IPv6 attributes is present).

### New Behavior
~`boto3_vpc`~ `boto3_ec2` only uses boto3. Not all functions have been implemented but a framework has been made to easily allow adding/updating functions (and to avoid having to copypaste code everywhere, which is actually the root cause for creating the framework).
Unittests have been fixed and extended (and will be extended more as work progresses).
The framework is as follows:
- All `describe_x`-functions call `__utils__['boto3.describe_resource']` mostly without doing anything else. `describe_resource` handles errors that Boto might raise.
- All resources have a `lookup_x`-function that accepts all filters (for describe) as arguments, builds the filter parameter and calls `__utils__['boto3.lookup_resource']`, which passes everything to `__utils__['boto3.describe_resource']` and does additional errorhandling with regard to the size of the result-set.
- All resources have a `create_X`-function that handles resource-specific pre- and post-requisites around calling `__utils__['boto3.create_resource']` that does the actual boto call (with errorhandling).
- A function `__utils__['boto3.handle_response']` has been added that wraps a 2nd function call and handles any expected boto errors that could occur, as well as standardizing the returned value.
- A generic `__utils__['boto3.wait_resource']`-function has been added to allow for easier access to boto-waiters. These are either provided by botocore, or by custom waiters in `salt.utils.boto3_waiters` similar to `salt.utils.boto3_elasticsearch`.
- All `delete_x`-functions call `__utils__['boto3.handle_response']` and use the `__salt__['boto3.lookup_resources']`-context handler to lookup required and optional resources beforehand.
- Most other functions also use `__utils__['boto3.handle_response']` combined with `__salt__['boto3.lookup_resources']` to implement the action with any required resources.

### Merge requirements satisfied?
- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by anitakrueger** [comment]
@github-abcde just wanted to say that this is awesome! I've been using the boto states and modules for years and it's been increasingly difficult because there has been no tlc for any of them :( love this! thank you!

**Comment by github-abcde** [comment]
@anitakrueger Thank you for your kind words. Unfortunately I have been occupied with another project since the last commit, so progress has paused somewhat. I hope to be able to put some more time into this next month.

**Comment by anitakrueger** [comment]
@github-abcde Have you had a chance to look at this again? I'm still stuck with a few features that I just can't get done in Salt and we have now resorted to terraform to do some of our infrastructure deployment.

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
