### PR TITLE
Set state_output_profile as option and update docs

### PR DESCRIPTION
**Pull request by ScriptAutomate**
### What does this PR do?

- Documents `state_output_profile` as an option in `master` and `minion` configs
- Adds `state_output_profile` as an option to `salt/config/__init__.py`, validating as a `bool`
- Adds `state_output_profile` as having default value of `True` in `minion` and `master` configs
- Updates `salt/output/highstate.py` to no longer hard-code default value for `state_output_profile`

### What issues does this PR fix or reference?

Ongoing work related to: #58112

It looks like `state_output_profile` was meant to be an _option_, but was instead hard-coded into `salt/output/highstate.py` when the value and option should have been documented for minion/master configurations.

- Fixes changes done by old PR: #35271
- Fixes original issue: #35166

### Previous Behavior

Undocumented option.

### New Behavior

Documented option.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by ScriptAutomate** [comment]
Of note: I also opened #59166 after noticing that we may need to extend the `salt/output/highstate.py` docstring documentation to include `state_output_diff` and `state_output_profile` information. The issue also notes that `show_output` documentation in the `highstate.py` docstring docs differs from the master/minion config definition of what valid values are acceptable.

**Review by waynew — APPROVED** [review]
:rocket: Looks great!

**Review by waynew — CHANGES_REQUESTED** [review]
Looks like in JsonNestedTestCase in the `setup_loader_modules` function you'll need to add `"state_output_profile": True,` as well

**Comment by ScriptAutomate** [comment]
> Looks like in JsonNestedTestCase in the `setup_loader_modules` function you'll need to add `"state_output_profile": True,` as well

Thanks!

I've now changed here:
- https://github.com/saltstack/salt/pull/59165/commits/2c5ee7639b07d88c7e29ef771354c6befb62d551

`pre-commit` applied everything else here:
- https://github.com/saltstack/salt/pull/59165/commits/279c9a404f571a17f675e1ab87cc82eaee5399db

**Review by waynew — APPROVED** [review]
🚀

**Review by Ch3LL — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Pull request merged**
