### PR TITLE
Passphrase protect master private key

### PR DESCRIPTION
**Pull request by akabraab**
### What does this PR do?
This feature adds the ability to passphrase protect the master private key and/or the master signing key.  This is the second attempt at getting [this closed PR 35542](https://github.com/saltstack/salt/pull/35542) revived.
### What issues does this PR fix or reference?
Background for this PR can be found [salt/issues/35303](https://github.com/saltstack/salt/issues/35303)

### Previous Behavior
salt-master creates a private key without passphrase
salt-master loads a private key without passphrase
salt-master creates signing key without passphrase
salt-master loads signing key without passphrase
salt-key generates signature without passphrase needed for existing signing key
salt-key creates new signing key without a passphrase (--auto-create on)
### New Behavior
salt-master creates a private key with a passphrase
salt-master loads a private key with passphrase
salt-master creates signing key with passphrase
salt-master loads signing key with passphrase
salt-key generates signature with passphrase needed for existing signing key
salt-key creates new signing key with a passphrase (--auto-create on)
passphrases are configured within the master config. Best pracitces is to utilize external vaulting mechanism but if a string is used as the passphrase values, it will be accepted. (this is due to sdb passing the string along if it can't resolve the query).

The private key and the signing key both can have their own unique passphrase and one is not dependent on the other. If the user would like to manage one password I figured they can use the same sdb query to retrieve the same password for both. It is also possible to set a passphrase for the private key but not the signing key and vice versa.

The following configuration options being proposed are as followed.
```
#####        Security settings       #####
##########################################
# Enable passphrase protection of Master private key.  Although a string value
# is acceptable; passwords should be stored in an external vaulting mechanism
# and retrieved via sdb. See https://docs.saltstack.com/en/latest/topics/sdb/.
# Passphrase protection is off by default but an example of an sdb profile and
# query is as follows.
# masterkeyring:
#  driver: keyring
#  service: system
#
# key_pass: sdb://masterkeyring/key_pass

# Enable passphrase protection of the Master signing_key. This only applies if
# master_sign_pubkey is set to True.  This is disabled by default.
# master_sign_pubkey: True
# signing_key_pass: sdb://masterkeyring/signing_pass
```
### Tests written?

No
Need help

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by rickh563** [comment]
ZD-1635

**Comment by cachedout** [comment]
Hi @akabraab. This has merge conflicts. Could you please rebase this and resolve the conflicts and then update this PR? Thanks.

**Comment by garethgreenaway** [comment]
@akabraab Looks like the new tests for testing with a passphrase are failing.  Mind taking a look?

**Comment by akabraab** [comment]
Looks like the failures now are due to the Jenkins job not being able to update status back on the Mastercard git repo.  Do I need to authorize a certain github user to enable that?

**Comment by akabraab** [comment]
All checks are now passing.  Can this PR be reviewed and merged now?

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
