### PR TITLE
hide duplicate function in saltcheck docs

### PR DESCRIPTION
**Pull request by mchugh19**
### What does this PR do?
Minor fix in saltcheck docs to hide function alias not pertinent to human users

### Previous Behavior
saltcheck docs displayed an alias doc line
```
salt.modules.saltcheck.run_state_tests_ssh(state, saltenv=None, check_all=False)
```

### New Behavior
The run_state_tests_ssh function is not displayed in documentation

### Tests written?
No
Doc fix only

### Commits signed with GPG?
No

### CODE REVIEW

**Review by Ch3LL — APPROVED** [review]

**Review by s0undt3ch — APPROVED** [review]

**Review by DmitryKuzmenko — APPROVED** [review]

**Comment by DmitryKuzmenko** [comment]
re-run full macosxmojave-py2

**Review by s0undt3ch — APPROVED** [review]

**Comment by DmitryKuzmenko** [comment]
@mchugh19 could you please resolve merge conflicts?

**Comment by mchugh19** [comment]
Appears to be merge conflict free

**Comment by DmitryKuzmenko** [comment]
Yes sorry. That was a multicast. =)

**Pull request merged**
