### PR TITLE
Fixed linter errors in file test

### PR DESCRIPTION
**Pull request by Akm0d**
### What does this PR do?
Fixes failing lint and FileTest tests on master

### CODE REVIEW

**Review by garethgreenaway — APPROVED** [review]

**Comment by xeacott** [comment]
Thank you @akm0d

**Review by xeacott — APPROVED** [review]

**Comment by Akm0d** [comment]
re-run full centos7

**Comment by s0undt3ch** [comment]
https://github.com/saltstack/salt/commit/84b930bac6d1abe192501b1a367677bf8cdac315

**Comment by s0undt3ch** [comment]
https://github.com/saltstack/salt/pull/55570

**Comment by s0undt3ch** [comment]
Sorry, closing in favor of https://github.com/saltstack/salt/pull/55570

**Pull request closed without merging**
