### PR TITLE
Add features to CSF module

### PR DESCRIPTION
**Pull request by kevinquinnyo**
### What does this PR do?

Adds features to the csf module
### Tests written?

No

Probably needs tests at this point.

I'm not sure if it would be better to send a PR to the maintainer @mostafahussein fork for now instead?  I'll be happy to do that if preferred

### CODE REVIEW

**Comment by mostafahussein** [comment]
Hello @kevinquinnyo,
Thanks for your PR :D

I wasn't able to find enought time in order to continue working on this module. so thanks again for the assist.
I am wondering if we can discuss some features related to this module, maybe through email if available ?


I see that you have removed `which`. i think we might need it as some distros may not be able  to call `csf` as it is. or maybe its a rare case that happened to me only?

**Comment by kevinquinnyo** [comment]
The `which` still exists in your `__csf_cmd(cmd)` function.  I just replaced it in the `_status_csf()` function with what I think is a more universal way to check that csf is enabled.  When you disable csf it creates a file at `/etc/csf/csf.disabled` and removes it when it's re-enabled.

That seemed to me the best way to check if csf is enabled or not.

That said, there are probably some bugs in my PR.  I think it might make more sense for me to submit these changes to your fork of salt, just to keep a single point of entry for the csf module, and submit a single PR to salt with tests.  I was planning to also build a corresponding state module this week that utilizes the execution module, e.g. - `csf.allowed()`, `csf.denied()`, etc...

And I completely understand about not having the time for these kinds of things.

**Comment by kevinquinnyo** [comment]
I added a lot to this.

Basically I wrote this in a way that's good enough for my current needs, but I realize it's probably not up to snuff for salt coding standards / linting.  If someone can provide some style guides, or pointers on what's not good, I'll be happy to adjust.

**Comment by kevinquinnyo** [comment]
Also @mostafahussein as far as discussing the changes with you, I would be happy to -- I just don't want to paste my email here.  I'm in the #salt IRC channel almost daily, user kevinquinnyo.  That might be the best place to chat, or exchange emails.  Otherwise we can just discuss it here as well.

**Comment by mostafahussein** [comment]
I started to work on this module, currently working on [linting its code](https://github.com/mostafahussein/salt-1/commit/900cd85c74d0527b934fc33d92003948d106f370) by using pylint. also I have installed this [salt linter](https://github.com/saltstack/salt-pylint) to get full report of what salt jenkins jobs trying to check

**Comment by cachedout** [comment]
@kevinquinnyo How is this looking? It is ready for us to review or do you want to work with @mostafahussein on this some more.

**Comment by kevinquinnyo** [comment]
@cachedout Probably need some more time.  I have fixed a lot of bugs while using the module on my own, and haven't pushed them up.  I was probably going to try to merge in the code lint / anything else @mostafahussein might have had time to correct.

I think we're definitely going to need tests for this as well.

**Comment by cachedout** [comment]
@kevinquinnyo Just checking in here. Let me know how it's going. Thanks!

**Comment by kevinquinnyo** [comment]
@cachedout Hey thanks for reminding me.  I got caught up in another project recently.  Is there a timeline on this?  I'd like to push up some improvements for this and write some tests, since I think it will be useful to at least a few more people than just me and @mostafahussein but I'm not sure on the Saltstack release schedule.

**Comment by cachedout** [comment]
Thanks for the response, @kevinquinnyo. We'd want this in no later than two weeks from today, give or take a day or so. Let me know if I can help.

**Comment by kevinquinnyo** [comment]
Hey @cachedout I'd like to try to finish this up this coming week.  Is it ok if I do my best to clean up the code, and submit as is for review?  I've only ever written a few tests for saltstack, and I know it's going to need some.  Writing tests is probably the biggest challenge for me.

**Comment by cachedout** [comment]
@kevinquinnyo Absolutely! We're here to help with whatever you need. If you run into trouble, drop me a line here or ask somebody in the IRC channel to come and find me. :] Thanks!

**Comment by kevinquinnyo** [comment]
I went ahead and pushed up what I have because I just don't have the time to work on this :( .  I wish I did.  This module + state needs a lot of general code cleanup/review and some tests.

If anyone wants to take it over please feel free, and sorry I couldn't properly finish this up.

**Comment by cachedout** [comment]
No problem at all. I'll get this in and then whomever wants to pick up the torch from here can carry it. Thanks for much for your great work here, @kevinquinnyo

**Pull request merged**
