### PR TITLE
allow nova driver to be boot from volume

### PR DESCRIPTION
**Pull request by gtmanfred**
Thanks,
Daniel

### CODE REVIEW

**Comment by gtmanfred** [comment]
@techhat :)

**Comment by cachedout** [comment]
Nice! Thanks, @gtmanfred

**Comment by tehsu** [comment]
Seeing this error when I try to deploy, 

[ERROR   ] The required 'image' configuration setting is missing from the 'profile_test' profile, which is configured under the 'rackspace' alias.

the driver should be nova correct?

**Comment by gtmanfred** [comment]
That looks like you are not on 2015.8.4

(which granted has a bug in it right now, but was just announced)

https://github.com/saltstack/salt/issues/30820

```
+--------------------------------------+----------------------------------------------------------+
| Property                             | Value                                                    |
+--------------------------------------+----------------------------------------------------------+
| OS-DCF:diskConfig                    | MANUAL                                                   |
| OS-EXT-STS:power_state               | 0                                                        |
| OS-EXT-STS:task_state                | block_device_mapping                                     |
| OS-EXT-STS:vm_state                  | building                                                 |
| RAX-PUBLIC-IP-ZONE-ID:publicIPZoneId | 669bb7b5bd0c29d4d8617968275eb1d24bc6748537d40af594f1d799 |
| accessIPv4                           |                                                          |
| accessIPv6                           |                                                          |
| config_drive                         |                                                          |
| created                              | 2016-02-02T21:06:08Z                                     |
| flavor                               | 8 GB General Purpose v1 (general1-8)                     |
| hostId                               | 7963ea7616e67ee1b43749e919cbab5b8d3fee2ac45197cf2ba9332b |
| id                                   | 0f684e3d-07e0-4f21-afb3-d7109ccc6afc                     |
| image                                | Attempt to boot from volume - no image supplied          |
| key_name                             | gtmanfred                                                |
| metadata                             | {}                                                       |
| name                                 | testbfv.manfred.io                                       |
| neutron network                      | 172.16.1.36                                              |
| openstack network                    | 172.16.0.5                                               |
| progress                             | 0                                                        |
| public network                       | 2001:4802:7805:102:be76:4eff:fe20:6c00, 104.130.239.70   |
| status                               | BUILD                                                    |
| tenant_id                            | <redacted>                                                   |
| updated                              | 2016-02-02T21:06:10Z                                     |
| user_id                              | <redacted>                                                 |
+--------------------------------------+----------------------------------------------------------+
```

```
cent7-bfv-iad:
      provider: iad
      size: general1-8
      block_device:
        - source: image
          id: 9d29f10e-4fc2-4556-8d25-532d1784329a
          dest: volume
          size: 50
          shutdown: preserve
          bootindex: 0
```

**Comment by tehsu** [comment]
I'm actually on enterprise. 

Salt Version:
           Salt: 4.1.3

**Comment by tehsu** [comment]
Which driver do you use? I'm assuming nova? Or does it stay openstack

**Comment by tehsu** [comment]
Got it working, thanks for your help.

**Comment by tehsu** [comment]
Have you tried using the following? I'm running it on a fresh salt build with 2015.8.5

cent6:
  provider: rackspace
  size: general1-1
  block_volume: 2ceba925-daf9-4f2c-aa20-686e04ca2e2d

I'm getting [ERROR   ] The required 'image' configuration setting is missing from the 'cent6' profile, which is configured under the 'rackspace' alias.

I built it using salt-cloud

**Comment by tehsu** [comment]
ok so, spoke to you on IRC, for anyone looking at this, the correct way to do 

cent6:
provider: rackspace
size: general1-1
boot_volume: 2ceba925-daf9-4f2c-aa20-686e04ca2e2d

**Pull request merged**
