### PR TITLE
Fix Windows failures in pip module due to raw string formatting

### LINKED ISSUE #9592: pip module fails on Windows because of quoting
```
salt -G 'os:Windows' pip.install mako
```

gives:
```
    pid:
        1112
    retcode:
        2
    stderr:

    stdout:
        Exception:
        Traceback (most recent call last):
          File "C:\Python27\lib\site-packages\pip\basecommand.py", line 134, in main
            status = self.run(options, args)
          File "C:\Python27\lib\site-packages\pip\commands\install.py", line 215, in run
            InstallRequirement.from_line(name, None))
          File "C:\Python27\lib\site-packages\pip\req.py", line 129, in from_line
            return cls(req, comes_from, url=url, prereleases=prereleases)
          File "C:\Python27\lib\site-packages\pip\req.py", line 44, in __init__
            req = pkg_resources.Requirement.parse(req)
          File "build\bdist.win32\egg\pkg_resources.py", line 2700, in parse
            reqs = list(parse_requirements(s))
          File "build\bdist.win32\egg\pkg_resources.py", line 2626, in parse_requirements
            raise ValueError("Missing distribution spec", line)
        ValueError: ('Missing distribution spec', "'mako'")

        Storing complete log in C:\Windows\system32\config\systemprofile\pip\pip.log
```

In this changeset fcbed9a, quoting was added to package names with the "!r" format flag. Packages are then appended to the pip command as strings enclosed in single quotes:

" 'packagename' "

On linux, this works fine. On Windows, the Package resource API (lib/site-packages/pkg_resources.py) cannot properly parse package names quoted like this, hence raising this "Missing distribution spec" error.

I am not sure what would be the right way to fix this. Using the "!s" flag instead of the "!r" flag would fix this, but could potentially break something else. I am not fully aware of the all the pip module subtleties, so I cannot for sure propose a solution.

### PR DESCRIPTION
**Pull request by terminalmage**
Fixes #9592.

### CODE REVIEW

**Comment by terminalmage** [comment]
Test failures are due to changing list of command arguments. I will update these (and fix the lint errors) later tonight.

**Comment by terminalmage** [comment]
OK, tests have been updated and the module now passes the args to ``cmd.run_all`` as lists instead of joining the lists before calling.

Please don't merge yet, I want to do manual testing in the morning before I am comfortable signing off on it.

**Comment by basepi** [comment]
Just closing until you do your manual testing. Since tests passed someone could accidentally merge this. =)

**Comment by terminalmage** [comment]
OK, manual testing went fine, I just ended up making one change unrelated to the rest of the changes to ensure that we return a useful error when non-list input is specified for pip.installed's "pkgs" argument.

**Pull request merged**
