### PR TITLE
SUSE leftovers for 2017.7.0 RC

### PR DESCRIPTION
**Pull request by meaksh**
### What does this PR do?

As commented on https://github.com/saltstack/salt/pull/41795 and https://github.com/saltstack/salt/pull/41708 , this PR brings the rest of patches we are carrying from version to version to include them into 2017.7.0 RC.

/cc @isbm

### CODE REVIEW

**Comment by cachedout** [comment]
@meaksh or @isbm can one of you please grab those lint errors?

**Comment by cachedout** [comment]
@isbm and @meaksh Additionally, there are failing tests here which will need to be fixed.

**Comment by meaksh** [comment]
@cachedout - I think this is ready now 😄

**Comment by isbm** [comment]
@cachedout, here. You have it! :sunglasses:

**Comment by cachedout** [comment]
@meaksh and @isbm You both are great! Thanks so much!

**Comment by cachedout** [comment]
@meaksh There is one small issue with this.

On Python 3, we are getting the following error:

https://jenkins.saltstack.com/job/branch_tests/job/2017.7/view/Python%203/job/salt-linode-py3-cent7/143/testReport/junit/unit.test_zypp_plugins/ZyppPluginsTestCase/test_drift_detector/

```
Failed

unit.test_zypp_plugins.ZyppPluginsTestCase.test_drift_detector (from unit.test_zypp_plugins.ZyppPluginsTestCase-20170623223733)

Failing for the past 1 build (Since Failed#143 )
Took 4 ms.
Error Message

No module named '__builtin__'
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/unit/test_zypp_plugins.py", line 41, in test_drift_detector
    with patch('__builtin__.open', bogus_io):
  File "/usr/lib64/python3.4/unittest/mock.py", line 1187, in __enter__
    self.target = self.getter()
  File "/usr/lib64/python3.4/unittest/mock.py", line 1354, in <lambda>
    getter = lambda: _importer(target)
  File "/usr/lib64/python3.4/unittest/mock.py", line 1043, in _importer
    thing = __import__(import_path)
ImportError: No module named '__builtin__'
		```

**Comment by meaksh** [comment]
@cachedout - Should be fixed on https://github.com/saltstack/salt/pull/41952 👍

**Pull request merged**
