### PR TITLE
Remove streamed response for fileclient to avoid HTTP redirection problems

### PR DESCRIPTION
**Pull request by jacksontj**
Fixes: #27093 
Replaces: #27163 

By using the stream response the client was concatenating all bodies in the redirect path. This means if you have a URL which redirects to a second one the resulting string (previously) was both put together (which causes a LOT of problems).

To fix this we either need to stop streaming, or don't automatically follow redirects. The previous attempt at fixing this (which I have a revert for in this PR) attempted to check content-length. This is problematic because not all HTTP responses have content-length (for example: https://en.wikipedia.org/wiki/Chunked_transfer_encoding). 

Since we aren't doing any actual processing or writing to disk with the streaming I've removed it for now-- to fix the regression. Later we can look into on_headers and on_chunk to do streaming.

### CODE REVIEW

**Comment by jacksontj** [comment]
For some reason github isn't showing my reverts correctly... you'll need to revert both below commits.

cdbb2704d060799f24c9f57cec9240f639f1937b
6c81c6532de8988f1f8a23984a5fcd12e4fa9334

**Comment by jacksontj** [comment]
ping @cachedout @terminalmage

**Comment by jacksontj** [comment]
Figured out the revert commits, just had a weird detached head state locally :)

**Comment by terminalmage** [comment]
I'm all for a better solution, thanks!

Just one lint error here: https://jenkins.saltstack.com/job/salt-pr-lint-n/9462/violations/file/salt/fileclient.py/

**Comment by jacksontj** [comment]
@cachedout @jfindlay one of you guys mind merging this in? Somewhat of an urgent fix :)

**Comment by terminalmage** [comment]
Please change this to use salt.utils.files.rename(), which was added to incorporate the special handling for Windows.

**Comment by jacksontj** [comment]
@terminalmage Do you happen to have the exception that rename causes? I'd rather make it do a rename, catch-- delete-- and rename instead of always remove (so we only do work on windows clients that need it)

**Comment by jacksontj** [comment]
@terminalmage there we go :)

**Comment by terminalmage** [comment]
That last commit can be removed as this is handled more comprehensively in https://github.com/saltstack/salt/pull/27418

**Comment by jacksontj** [comment]
@terminalmage done :)

**Comment by jacksontj** [comment]
@jfindlay you around to merge this in? I want to get this merged in upstream before I backport the fix internally

**Comment by terminalmage** [comment]
Waiting on tests right now.

**Pull request merged**
