### PR TITLE
Use more concise status info

### PR DESCRIPTION
**Pull request by techhat**
### What does this PR do?

This offers more concise information using the `ps` module instead of the `status` module. Ping @thatch45.
### What issues does this PR fix or reference?
#34752.
### Tests written?

No.

### CODE REVIEW

**Comment by thatch45** [comment]
Does this require psutil?

**Comment by techhat** [comment]
@thatch45 looks like it does.

**Comment by thatch45** [comment]
As this is not a hard dep we should probably not use it here

**Comment by techhat** [comment]
Sounds good.

**Pull request closed without merging**
