### PR TITLE
refactor a bit to clean up the mess, no functionality changes

### PR DESCRIPTION
**Pull request by hu-dabao**
### What does this PR do?

Clean the mess in cli/salt.py for better readability and style. No logic, functionality changes. 

(It looks like a lot of changes because clean up one not needed if else logic by adding a return [here](https://github.com/saltstack/salt/compare/develop...hu-dabao:clean-mess?diff=unified&expand=1&name=clean-mess#diff-9aee05789b5cd3b8332fd74ad544d758R54) and change try except block to fit properly [here](https://github.com/saltstack/salt/compare/develop...hu-dabao:clean-mess?diff=unified&expand=1&name=clean-mess#diff-9aee05789b5cd3b8332fd74ad544d758R130), which cause a lot of unindents)

One more question if anyone knows what are these two [lines](https://github.com/saltstack/salt/compare/develop...hu-dabao:clean-mess?diff=unified&expand=1&name=clean-mess#diff-9aee05789b5cd3b8332fd74ad544d758R133) (and the following) about. I check the code base, looks like they are not useful. 
### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by hu-dabao** [comment]
@cachedout 
Hi there, 
Do you know how to trigger a build without committing the code? 
(Since I think the Jenkins failure is not related to the code change, or if you know some practice how to debug Jenkins failures?)

Any help will be appreciated. 

Thanks

**Comment by hu-dabao** [comment]
@cachedout 
One more thing, since this is develop branch, which is unstable, the failure may be not caused by my change :)

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
@hu-dabao If you want to trigger test restarts yourself with out pushing any new commits, you can close, and then reopen your pull request. The tests will start again after that. However, I just restarted these again with my comment above (which Salt Stack members like Mike and myself are whitelisted to execute).

**Comment by hu-dabao** [comment]
```

**Comment by cachedout** [comment]
We're in the process of fixing those GitPillar tests. You can safely ignore them in this PR.

**Pull request merged**
