### PR TITLE
INFRA-5737 - add new auth options to boto3 utils module

### PR DESCRIPTION
**Pull request by tkwilliams**
Transparently adds several new auth options to boto3 based modules.  That is, they all default to None, so they'll have no effect on existing modules; but new modules can be written to leverage them, and old modules updated, if and when desired.  Specifically, this adds:
- aws_session_token:  Utilize a previously generated AWS session token to bind
- botocore_session:  Use a previously generated botocore internal connection ID
- aws_profile:  Most usefully, use creds stored in ~/.aws/credentials or ~/.aws/config (or any other profile location supported by boto3).  This is essentially equivalent to using the AWS_PROFILE environment variable, except the latter only works when calling boto exec functions locally, not when running states or otherwise running through the master.

These are all native auth types for boto3, above and beyond the normal practice of passing in literal key/keyid strings (which to me has always presented several uncomfortable security issues).

The new auth options are leveraged in (and required by) the new boto3 EMR modules I'm working on, which will be in a separate PR very shortly...

### CODE REVIEW

**Comment by ryan-lane** [comment]
+1

**Comment by cachedout** [comment]
@tkwilliams Quite a few test failures here, I'm afraid.

**Comment by tkwilliams** [comment]
Yah, I had a strong suspicion a lot of tests would blow up on this one :)  I'll spend some cycles this week to get them all fixed up and happy again...

**Comment by cachedout** [comment]
Thanks, @tkwilliams. I'm looking forward to getting this in. Keep us posted.

**Comment by cachedout** [comment]
@tkwilliams Just checking in with you to see how things are going on this one.

**Comment by tkwilliams** [comment]
Sorry, been under a huge deadline for a project the past couple of weeks.  It's largely done and winding down now and I'm praying I can slice out some time this week to address all these dangly bits ....

**Comment by tkwilliams** [comment]
@cachedout 

OK, I spent a lot of today clearing out some low hanging fruit PRs I've been sitting on for too long (e.g. https://github.com/saltstack/salt/issues/40655) :-/   I'm gonna try damned hard to finish up my patches for https://github.com/saltstack/salt/pull/43296 tomorrow, and then -- God willing and the creek don't rise -- I'll hit this one up on Wednesday.

**Comment by rallytime** [comment]
Hi @tkwilliams - just a reminder about this pull request. Have you had a chance to come back to this one?

**Comment by tkwilliams** [comment]
I wish I had - at work I've been maxed out on one critical project after another for a couple of months now.  The latest is at the 99.9% complete point, but sadly it's been there since last Friday...  The app dev is having major problems getting his EMR code to work, and he requires constant handholding from my side.  When I can get him self-sufficient, my utilization should drop to low levels and I'll be able to divert some real cycles to all these PRs I've been blocking on.

I REALLY am sorry to be blocking others on this stuff - at the time I was writing it I had reason to expect free bandwidth to complete them in a reasonably timely fashion, but I WILL get to them soon, even if I spend vacation on them :)

**Comment by rallytime** [comment]
@tkwilliams No problem and thanks for the update. Thank you again for your hard work. Keep us posted. :)

**Comment by tkwilliams** [comment]
Updating to current develop so I can get a handle on which tests are failing

**Comment by rallytime** [comment]
Hi @tkwilliams - We're having some trouble right now with our cloud provider, which is why we are seeing these kinds of results. Once those are resolved, I'll start these again and we can see something more accurate.

**Comment by rallytime** [comment]
re-run lint

**Comment by rallytime** [comment]
@tkwilliams Yeah, something isn't quite right here. Are you able to reproduce the failures when you run the unit tests in sequence (`runtests.py -u`)? If you're not able to reproduce them individually, that's usually what that indicates. Something in a previous test is not cleaning up after itself and the other tests don't get a clean run.

**Comment by rallytime** [comment]
Since we haven't heard back on this for a while, and there are now some commits included here that shouldn't be, I am going to close this. Please feel free to open a new PR rebased against current `develop` when you're ready. Thanks! :)

**Pull request closed without merging**
