### PR TITLE
Add timeout test fixture

### PR DESCRIPTION
**Pull request by waynew**
### What does this PR do? 

Inspired by https://github.com/saltstack/salt/pull/59861 this allows us to interrupt currently running loops via SIGALRM. The exception can either be re-raised or by default it will be trapped and the context manager will simply exit. By making it a test fixture it becomes available across the test suite

- [x] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by MKLeb — DISMISSED** [review]

**Review by s0undt3ch — DISMISSED** [review]
For a moment I though this was referring to timing out tests so I grabbed this URL https://github.com/pytest-dev/pytest-timeout
Then I noticed that this was to **actually trigger** a timeout **WHILE** running the test.

:+1:

**Comment by s0undt3ch** [comment]
We should also make it clear that `SIGALRM` is not available on windows...

**Comment by waynew** [comment]
> We should also make it clear that `SIGALRM` is not available on windows...

I should go ahead and mark that test with `skip_on_windows` then, eh?

**Review by twangboy — DISMISSED** [review]

**Review by whytewolf — DISMISSED** [review]

**Review by MKLeb — DISMISSED** [review]

**Comment by Ch3LL** [comment]
@waynew can you investigate the test failures and see if they are related?

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
