### PR TITLE
Use correct keys from group_info in group_install.

### LINKED ISSUE #54458: yumpkg.group_install/group_info "packages" key mismatch
### Description of Issue
group_info has been updated to use more accurate keys, i.e.:

> The ``mandatory packages``,
>        ``optional packages``, and ``default packages`` keys have been renamed
>        to ``mandatory``, ``optional``, and ``default`` for accuracy ...

However, group_install is still looking for 'mandatory packages' and 'default packages' so it can only install packages explicitly mentioned in include.

### Setup
Master running on CentOS 7.6, minion running on CloudLinux 7.6, based on CentOS.

### Steps to Reproduce Issue

Try to install any package group on yum based system. In our case:
```
# yum groupinfo alt-nodejs11
Modules complémentaires chargés : fastestmirror, langpacks, rhnplugin
This system is receiving updates from CLN.
Aucun fichier de groupe n'est installé.
Maybe run: yum groups mark convert (see man yum)
Loading mirror speeds from cached hostfile
 * cloudlinux-x86_64-server-7: de-proxy.cloudlinux.com

Groupe : alt-nodejs11
 ID du groupe : alt-nodejs11
 Description : nodejs 11.x packages for cloudlinux os nodejs selector
 Paquets par défaut :
   +alt-nodejs11
   +alt-nodejs11-http-parser
   +alt-nodejs11-icu
   +alt-nodejs11-libicu
   +alt-nodejs11-libuv
   +alt-nodejs11-nodejs
   +alt-nodejs11-npm
   +alt-nodejs11-openssl
   +alt-nodejs11-runtime
   +alt-nodejs11-zlib
```
And:
```
# salt-call pkg.group_info alt-nodejs11
local:
    ----------
    conditional:
    default:
        - alt-nodejs11
        - alt-nodejs11-http-parser
        - alt-nodejs11-icu
        - alt-nodejs11-libicu
        - alt-nodejs11-libuv
        - alt-nodejs11-nodejs
        - alt-nodejs11-npm
        - alt-nodejs11-openssl
        - alt-nodejs11-runtime
        - alt-nodejs11-zlib
    description:
        nodejs 11.x packages for cloudlinux os nodejs selector
    group:
        alt-nodejs11
    id:
        alt-nodejs11
    mandatory:
    optional:
    type:
        package group
```
But:
```
# salt-call pkg.group_install alt-nodejs11
local:
    ----------
```

### Versions Report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 24 2019, 08:54:15)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.6 Vladimir Lyakhov
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-714.10.2.lve1.5.19.9.el7.x86_64
         system: Linux
        version: CloudLinux 7.6 Vladimir Lyakhov

### PR DESCRIPTION
**Pull request by cvedel**
Fixes #54458

### What does this PR do?
Use correct packages keys from group_info in group_install.

### What issues does this PR fix or reference?
54458

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?
**[NOTICE] Bug fixes or features added to Salt require tests.**
Please review the [test documentation](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html) for details on how to implement tests into Salt's test suite.

Yes, added unit.modules.test_yumpkg.YumTestCase.test_group_install.

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by xeacott** [comment]
Hi @cvedel would you be able to rebase against `master` and then change the target branch to master, also? We've changed our branching strategy and we're using `master` branch moving forward.

**Review by cmcmarrow — CHANGES_REQUESTED** [review]
This PR still need some test.

**Comment by cvedel** [comment]
@cmcmarrow Sorry, looks like I left the test out of the commit. It is now in.

**Review by DmitryKuzmenko — DISMISSED** [review]

**Review by DmitryKuzmenko — APPROVED** [review]

**Comment by DmitryKuzmenko** [comment]
@cmcmarrow re-review please.

**Pull request merged**
