### PR TITLE
Adding delete_den to delete denied keys  See issue #24836

### PR DESCRIPTION
**Pull request by moali87**
This just adds the backend api, not the front-end call.  Will need to figure how those are being called and add methods as necessary.

This regards issue #24836

### CODE REVIEW

**Comment by AkhterAli** [comment]
Closing.  Syntactical error did not get pushed before creating request.

**Comment by AkhterAli** [comment]
Fixed, reopening.

**Comment by jfindlay** [comment]
@AkhterAli, thanks for working on this.  For future reference, if you find an error in your pull request, you can fix it by committing it to the same branch (or even rewriting commits on that branch) and then pushing that branch to your GitHub account will automatically update the pull request.

**Comment by AkhterAli** [comment]
@jfindlay Thanks.  I did not know that.  Still new to all this.

**Comment by AkhterAli** [comment]
Not sure what's causing the failure here.

**Comment by jfindlay** [comment]
@AkhterAli, those failures are bogus artifacts that got left over by jenkins.

@thatch45 or @cachedout, please review, thanks.

**Comment by cachedout** [comment]
Thanks for this. There is a lot of code duplication here. What do you think about refactoring other delete functions to accept arguments about which keys to delete, instead?

**Comment by AkhterAli** [comment]
@cachedout This is one of my first commits after taking a few Python courses and I can foresee my current employer needing such code.  We are in no rush so if you believe that we can shorten the code here, I would really love to see it as it would further improve my skills.  I would love to use the delete_all function to accept an argument and use and intrinsic function to perform the deletion based on the argument passed.  I just don't know how the arguments are being passed currently from salt-key cli to call these specific methods.  

I would love to read your input on this.  

Thank you.

**Comment by cachedout** [comment]
Hi @AkhterAli 

While I think we can probably shorten this down the road, let's go ahead and get it merged for now. It should be straightforward to optimize in the future. Thanks.

**Comment by babilen** [comment]
It appears as if this was never integrated into the salt-key CLI interface in into salt/utils/parsers.py (SaltKeyOptionParser) and salt/key.py (KeyCLI.run()).

**Comment by thatch45** [comment]
Yes, as it stands this can only be called directly from the key api, so it would be nice to add an option to salt-key

**Comment by babilen** [comment]
Opned #36258 about that. Ta!

**Pull request merged**
