### PR TITLE
Revert "fix 45195 - add ignore to sysctl state and module"

### LINKED ISSUE #57826: [BUG] sysctl.present broken in FreeBSD
```
          ID: security.jail.sysvipc_allowed
    Function: sysctl.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python3.7/site-packages/salt/state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/local/lib/python3.7/site-packages/salt/loader.py", line 2085, in wrapper
                  return f(*args, **kwargs)
                File "/usr/local/lib/python3.7/site-packages/salt/states/sysctl.py", line 117, in present
                  update = __salt__["sysctl.persist"](name, value, config, ignore)
              TypeError: persist() takes from 2 to 3 positional arguments but 4 were given
```

Looks like it was broken by this https://github.com/saltstack/salt/pull/55719 since the author of that commit didn't do any testing or review on any platform other than linux.

### PR DESCRIPTION
**Pull request by asomers**
Reverts saltstack/salt#55719

That PR changed the signature of Linux's sysctl.persist, but did not update the persist module of any other OS.  The result is a `TypeError` exception in the sysctl state on FreeBSD, NetBSD, and OpenBSD.  On OSX the problem is worse: runtime misbehavior.

Fixes #57826

### CODE REVIEW

**Comment by mchugh19** [comment]
Alternatively, #57841 was just created to fix #55719

**Comment by asomers** [comment]
I don't know why gitlab failed.  The link is dead.

**Comment by asomers** [comment]
Rebased.

**Comment by asomers** [comment]
The two CI failures are not the fault of this PR:
1) ci/pre-commit is complaining about some string formatting expressions that weren't modified by this PR
2) ci/lint is complaining about import expressions in files that weren't modified by this PR.

**Comment by krionbsd** [comment]
re-run all

**Review by krionbsd — APPROVED** [review]

**Comment by asomers-ax** [comment]
Thank you!

**Pull request merged**
