### PR TITLE
fileclient: decode file list from master

### LINKED ISSUE #29918: UnicodeDecodeError when saltutil.sync_modules for Windows  salt-minion  2015.8.3
UnicodeDecodeError when saltutil.sync_modules for Windows  salt-minion  2015.8.3

```
salt '<minion_id>' saltutil.sync_modules
<minion_id>:
    The minion function caused an exception: Traceback (most recent call last):
      File "C:\salt\bin\lib\site-packages\salt\minion.py", line 1039, in _thread_return
        return_data = func(*args, **kwargs)
      File "C:\salt\bin\lib\site-packages\salt\modules\saltutil.py", line 331, in sync_modules
        ret = _sync('modules', saltenv)
      File "C:\salt\bin\lib\site-packages\salt\modules\saltutil.py", line 112, in _sync
        source, sub_env, include_pat=r'E@\.(pyx?|so|zip)$'
      File "C:\salt\bin\lib\site-packages\salt\modules\cp.py", line 444, in cache_dir
        path, saltenv, include_empty, include_pat, exclude_pat
      File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 233, in cache_dir
        if fn_.strip() and fn_.startswith(path):
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 85: ordinal not in range(128)

```

### PR DESCRIPTION
**Pull request by jfindlay**
Fixes #29918.

### CODE REVIEW

**Comment by cachedout** [comment]
@jfindlay This doesn't pass the test suite.

@terminalmage Could you also have a look at this, please?

**Comment by s0undt3ch** [comment]
One VM failed to deploy and the 3 failures on the other VM seem unrelated, let's re-trigger it.

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by basepi** [comment]
I think we'll probably hold off on this until we can get the test suite running properly again.

**Comment by cachedout** [comment]
@jfindlay Can you please rebase this today?

**Pull request merged**
