### PR TITLE
Fixes bug in modules/pillar.py

### PR DESCRIPTION
**Pull request by tommygrumheden**
### What does this PR do?

The method obfuscate needs **kwargs in parameters so its able to use items() fully, as intended.
This fixes that problem.

No tests / changelog / docs supplied in PR. 

### What issues does this PR fix or reference?
Fixes: No issue created.

### Previous Behavior
`ERROR executing 'pillar.obfuscate': The following keyword arguments are not valid: saltenv=XXX`

### New Behavior
saltenv works.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by twangboy — DISMISSED** [review]

**Comment by garethgreenaway** [comment]
@tommygrumheden What is the reason for the change blindly accepting `kwargs` instead of specific keyword arguments?

**Comment by tommygrumheden** [comment]
> @tommygrumheden What is the reason for the change blindly accepting `kwargs` instead of specific keyword arguments?

Hi @garethgreenaway 
Sincerely I don't remember. And probably no good reason for using kwargs other that it quickly fixed our problems with saltenv.  :)

**Comment by garethgreenaway** [comment]
@tommygrumheden Thanks.  I see why this is needed and it looks like we include it in other functions in the pillar module.  I added a quick test to ensure that kwargs such as saltenv are passed along to `pillar.items` where it's used.

**Review by MKLeb — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Comment by tommygrumheden** [comment]
> @tommygrumheden Thanks. I see why this is needed and it looks like we include it in other functions in the pillar module. I added a quick test to ensure that kwargs such as saltenv are passed along to `pillar.items` where it's used.

Thanks for fixing a test! Happy to be contributing :) :)

**Pull request merged**
