### PR TITLE
Clarified functionality of reg module, fixed state to work with new module

### PR DESCRIPTION
**Pull request by twangboy**
reg module now differentiates between keys and values
reg state uses new functions in reg module
Fixes: #25352

### CODE REVIEW

**Comment by twangboy** [comment]
@jfindlay I don't know how to fix these test issues

**Comment by twangboy** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@twangboy These tests are still failing. Could you please take another look?

**Comment by twangboy** [comment]
@jfindlay Don't know what to do here.
https://jenkins.saltstack.com/job/salt-pr-rs-cent7-n/6511/testReport/junit/unit.states.reg_test/RegTestCase/test_absent/

**Comment by jfindlay** [comment]
@twangboy, I'll look at it and let you know, thanks.

**Pull request merged**
