### PR TITLE
Salt cp out

### PR DESCRIPTION
**Pull request by thatch45**
Add outputter support to salt-cp

### CODE REVIEW

**Comment by thatch45** [comment]
Fix #22704

**Comment by jfindlay** [comment]
@thatch45, there are a few errors.

**Comment by thatch45** [comment]
Wow! we have tests for salt-cp! I think I wrote them acctually

**Comment by cachedout** [comment]
I love that supporting outputters can be done in 3 lines of code. :]

**Comment by thatch45** [comment]
Maybe not, these errors are CRAZY

**Comment by jfindlay** [comment]
Looks good.

**Pull request merged**
