### PR TITLE
Bugs/49147 ipc subscriber develop

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
### What does this PR do?
Port of #51963 to develop.

### What issues does this PR fix or reference?
Fixes merge forward from 2018.3 to develop #52398

### Tests written?
Yes

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by dwoz** [comment]
@DmitryKuzmenko Can you merge [these](https://github.com/saltstack/salt/pull/52445) changes into your branch here?

**Comment by Ch3LL** [comment]
bump @DmitryKuzmenko

**Comment by DmitryKuzmenko** [comment]
@Ch3LL  Working.

**Comment by DmitryKuzmenko** [comment]
@Ch3LL I've reverted the PR #51963 (except the test) and re-implemented removing of singletons for IPCMessageSubscriber class. The PR is here: #52564. It passed the tests so now it could be pushed to 2018.3 and merged forward to 2019.2.
Anyway it looks it will have conflicts on merge. Please let me know how I can help with that.

**Pull request closed without merging**
