### PR TITLE
[modules/hg] hg.status: multiple repositories

### PR DESCRIPTION
**Pull request by rominf**

### CODE REVIEW

**Comment by cachedout** [comment]
@rominf This is causing some tests to fail. Could you please have another look? Thanks.

**Comment by rominf** [comment]
I guess I've fixed it.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Thanks, @rominf

**Pull request merged**
