### PR TITLE
Add test to catch sample config files that are not commented out

### LINKED ISSUE #36045: Line is not commented out in minion config file, gives warning when running commands.
### Description of Issue/Question
When testing Carbon, there is one line that is not commented out in the minion config file.
```
grep -E -v '^$|#' /etc/salt/minion
whitelist_modules:
```

When running commands often it gives me this 
```
[WARNING ] Key 'whitelist_modules' with value None has an invalid type of NoneType, a list is required for this value
```
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
Salt Version:
           Salt: 2016.9.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.0.1406 Core
        machine: x86_64
        release: 4.6.5-x86_64-linode71
         system: Linux
        version: CentOS Linux 7.0.1406 Core

### PR DESCRIPTION
**Pull request by rallytime**
### What does this PR do?

Adds some unit tests to read in the files in the `salt/conf` directory to make sure all of the lines in those files are commented out. It's easy to miss commenting out a line when adding docs for new options, but when we forget the `#`, we run into problems in #36045.
### What issues does this PR fix or reference?

Fixes #36045
### Previous Behavior

```
[WARNING ] Key 'whitelist_modules' with value None has an invalid type of NoneType, a list is required for this value
```
### New Behavior

No more warnings.
### Tests written?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by rallytime** [comment]
I just want to back port these new tests and see what they'll maybe catch, or not catch, on the other branches. The docs that originally triggered those warnings are new to the `carbon` branch.

**Comment by rallytime** [comment]
Oh, I also want to add three more tests to check the files contained in `salt/conf/cloud.profiles.d/*`, `salt/conf/cloud.providers.d/*` and `salt/conf/cloud.maps.d/`.

**Comment by rallytime** [comment]
Ok - this should be good to go pending the test run.

**Comment by cachedout** [comment]
Nice one.

**Pull request merged**
