### PR TITLE
Don't refresh modules twice per sync or refresh ops

### LINKED ISSUE #43941: Custom grains are evaluated twice per master at salt-minion startup time and grains refresh
[issue1839_grain.py.txt](https://github.com/saltstack/salt/files/1360860/issue1839_grain.py.txt)
### Description of Issue/Question
When grains are evaluated at startup time or when ordered to do a grains refresh, custom grains are executed twice per master.  I'm not sure if the internal grains are executed twice or not.

### Setup
To set this up put the following file in your `/srv/salt/_grains/` directory:

```
[root@syndic01-2017 salt]# cat /srv/salt/_grains/custom_grain.py 
#!/usr/bin/env python

import logging
log = logging.getLogger(__name__)


def custom_grain():
    '''
    This is a custom grain to test how often a grain is run.
    '''
    log.warning('Ran custom grain!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
    grains = {}
    grains['z_grain_repeat_issue'] = 'Hello_world'
    return grains
```

I've also attached the file to this issue.

### Steps to Reproduce Issue
On the salt-minion stop the salt-minion daemon and then start up the minion in the foreground.

```
[root@minion01-syndic01-2017 ~]# salt-minion
[WARNING ] Ran custom grain!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[WARNING ] Ran custom grain!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[WARNING ] Ran custom grain!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[WARNING ] Ran custom grain!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


[WARNING ] Ran custom grain!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[WARNING ] Ran custom grain!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[WARNING ] Ran custom grain!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[WARNING ] Ran custom grain!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Then you can run the following on the salt master and you'll see that for each Salt Master your minion is connected to it will evaluate the grains twice.  

```
[root@MOM-2017 ~]# salt minion01-syndic01-2017 saltutil.sync_grains
minion01-syndic01-2017:
```

In this example the minion is connected to two salt syndics as masters so when I run a command from the master of masters I get 4 warning log entries:

```
master:
  - syndic01-2017
  - syndic02-2017
```

```
### Versions Report

[root@MOM-2017 ~]# salt-master --versions-report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 5.6.0
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.13.0-132-generic
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

```

[root@minion01-syndic01-2017 ~]# salt-minion --versions-report
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.13.0-132-generic
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

I also tested on 2017.7.1 and got the same exact behavior.

```
[root@minion01-syndic01-2017 ~]# salt-minion --versions-report
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.13.0-132-generic
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
### What does this PR do?
Some of `saltutil` functions makes grains calculated twice per call. This happens because these functions fire both `refresh_modules` and `refresh_pillar` events while `refresh_pillar` event refreshes modules already by itself. `refresh_modules` reloads `grains` so firing both events we are getting double-grains calculation.
This PR avoids calling of `refresh_modules` in case `refresh_pillar` is called.

### What issues does this PR fix or reference?
Fix #43941

### Tests written?
No

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by cachedout — APPROVED** [review]

**Comment by cachedout** [comment]
I think this is fine but I'm a little curious about the failing test here.

**Comment by DmitryKuzmenko** [comment]
That tests are surprising me too.. I'll work on it.

**Comment by cachedout** [comment]
@DmitryKuzmenko Any update here?

**Comment by DmitryKuzmenko** [comment]
@cachedout I'll probably have time for this on the next week.

**Comment by DmitryKuzmenko** [comment]
re-run py

**Comment by DmitryKuzmenko** [comment]
As for me it looks like removal of one unneeded refresh made the test work faster that produced the failures not because of my changes but because this made the test more reliable. I bet the updated grains module test will fail without my fixes on Jenkins.
I'll continue investigate the reason of the failure.

**Comment by DmitryKuzmenko** [comment]
@rallytime working on it. I've wrote "tomorrow" but it was my last working day before vacation =))) Sorry for confusion

**Comment by cachedout** [comment]
@DmitryKuzmenko When you're ready to come back to this, we'll need a merge conflict resolved, please.

**Comment by cachedout** [comment]
@DmitryKuzmenko Any updates here?

**Comment by DmitryKuzmenko** [comment]
@cachedout currently working on Tornado 5.0. Will done this later.

**Comment by damon-atkins** [comment]
re-run lint

**Comment by Ch3LL** [comment]
ping @DmitryKuzmenko any update here? We just branched 2017.7.9 which is the last bug fix release for 2017.7, so if this needs to get into the release it needs to be cleaned up and migrated to the 2017.7.9 release branch. thanks :)

**Comment by DmitryKuzmenko** [comment]
@Ch3ll This PR looks like a proper solution but it's not completed without fixing the race conditions I've described above. I have no solution for that race condition right now and have no time I can spend on it for now. So I don't believe we have a chance to include it to 2017.7 unless we have some free hands.

**Comment by Ch3LL** [comment]
no worries. When you do have time to get back to this lets move it to the 2018.3 branch, since there will be no more 2017.7 bug releases after 7.9.

**Comment by DmitryKuzmenko** [comment]
I've rebased to master. Also cherry-picked commits from #55233.

**Comment by dwoz** [comment]
@DmitryKuzmenko Linter

**Review by cmcmarrow — APPROVED** [review]

**Pull request merged**
