### PR TITLE
URL auditor with URL fixes

### LINKED ISSUE #60720: [DOCS] Automatically audit and flag broken URLs in codebase/docs
**Description**

Automatically audit and flag broken URLs in codebase/docs

**Suggested Fix**

Use GitHub Actions to verify that links across the codebase/docs are not broken.

Using Sphinx's built-in linkcheck doesn't include validating links across the rest of the project, such as within any `*.md` files, or configuration files.

**Type of documentation**

- Salt documentation
- Salt modules

### LINKED ISSUE #62981: [DOCS] Install broken link checker into the docs and fix all the broken links
There's a lot of docs issues for broken links: https://github.com/saltstack/salt/labels/broken%20links

It would be nice to install a pre-commit hook that checks for broken links before merging. Then we can have one massive PR that fixes them all or something. I'll investigate how feasible this would be for this repo.

### PR DESCRIPTION
**Pull request by ScriptAutomate**
### What does this PR do?

Tests URLs, to validate when links have become out-dated.

### What issues does this PR fix or reference?

- Fixes: #60720
- Fixes: #62981

### CODE REVIEW

**Review by barbaricyawps — APPROVED** [review]
@ScriptAutomate , this is marked as a draft. Do you still need it to be a draft? It looks fine to me.

**Comment by dwoz** [comment]
@ScriptAutomate Is this still a draft?

**Comment by dwoz** [comment]
@ScriptAutomate I thought this was ready but it caused failures when I merged it. So I've reverted the change. Please open a new PR when you are ready.

**Comment by ScriptAutomate** [comment]
@dwoz Sorry, this was an old in-progress PR that I wasn't able to prioritize for expanding as it requires fixing a lot of broken URLs prior to completion. May open a new PR in the future.

**Pull request merged**
