### PR TITLE
Improve SSH_SH_SHIM code to detect Python from RHSCL

### PR DESCRIPTION
**Pull request by moises-silva**
Red Hat Software Collections (RHSCL) installs the python interpreter
in custom locations and then provides a wrapper python script that
sets up some environment variables to be able to run the interpreter
from a different location. In such cases the ssh shim code needs to
also export those variables, otherwise the python interpreter will
fail to execute any code (or even be launched due to missing libraries).

This commit also improves readability for the ssh shim code by adding
indentation to the shim string and then stripping the indentation when
the ssh client module is imported.

### CODE REVIEW

**Comment by jfindlay** [comment]
@moises-silva, it looks like this is confusing the linter, https://jenkins.saltstack.com/job/salt-pr-lint-n/10505/violations/file/salt/client/ssh/__init__.py/.

**Comment by moises-silva** [comment]
@jfindlay I wonder why my linter is not saying anything ... I'll check it out

**Comment by moises-silva** [comment]
@jfindlay ok I found how to execute the linter you use in salt with your own rules. It should be fixed now.

**Comment by jfindlay** [comment]
Thanks, @moises-silva.  If it doesn't work, I think it is perfectly acceptable to disable that lint error in this case, since the code is definitely not python anyway.

**Comment by basepi** [comment]
This is great cleanup, thanks! Everything appears to be in order in my testing, so I'm going to go ahead and close this one. (Test failures are unrelated.)

**Pull request merged**
