### PR TITLE
allow adding extra remotes to a repository

### LINKED ISSUE #42690: git.latest state with remote set fails on first try
### Description of Issue/Question
When adding a second remote to an existing repository the first try fails with a python error. The remote is added but not set as remote.

The stacktrace points to https://github.com/saltstack/salt/blob/develop/salt/states/git.py#L1145 where it seems that `fetch_url` is `None` when it should not be.

### Setup
Simple config to illustrate issue:
```
repository-create:
  git.latest:
    - name: "https://github.com/octocat/Spoon-Knife.git"
    - target: "/srv/test/repository/."
    - rev: master
    - branch: master

repository-add-remote:
  git.latest:
    - name: "https://github.com/ChristianBeer/Spoon-Knife.git"
    - target: "/srv/test/repository/."
    - remote: downstream
    - rev: master
    - branch: master
    - require:
      - git: repository-create
```

### Steps to Reproduce Issue
minion log:
```
2017-08-02 16:01:03,403 [salt.loaded.int.module.cmdmod][ERROR   ][12884] Command '['git', 'rev-parse', '--show-toplevel']' failed with return code: 128
2017-08-02 16:01:03,403 [salt.loaded.int.module.cmdmod][ERROR   ][12884] stderr: fatal: Not a git repository (or any of the parent directories): .git
2017-08-02 16:01:03,403 [salt.loaded.int.module.cmdmod][ERROR   ][12884] retcode: 128
2017-08-02 16:01:05,874 [salt.loaded.int.states.git][ERROR   ][12884] Unexpected exception in git.latest state
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/states/git.py", line 1144, in latest
    salt.utils.url.redact_http_basic_auth(fetch_url),
  File "/usr/lib/python2.7/dist-packages/salt/utils/url.py", line 196, in redact_http_basic_auth
    return re.sub(url_re, redacted, output, flags=re.IGNORECASE)
  File "/usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
2017-08-02 16:01:05,876 [salt.state       ][ERROR   ][12884] expected string or buffer
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.1
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-3-amd64
         system: Linux
        version: debian 9.1
```

### PR DESCRIPTION
**Pull request by gtmanfred**
### What does this PR do?
This allows for adding more than one remote to a repository with git.latest

### What issues does this PR fix or reference?
Fixes #42690 

### Tests written?

No

### CODE REVIEW

**Comment by gtmanfred** [comment]
Go Go Jenkins!

**Comment by garethgreenaway** [comment]
@terminalmage Mind taking a look at this PR?  Thanks!

**Review by terminalmage — APPROVED** [review]
:+1:

**Comment by rallytime** [comment]
Linted by hand.

**Pull request merged**
