### PR TITLE
Remove buggy start parameter from virt.pool_running docstring

### LINKED ISSUE #57275: [BUG] salt.states.virt.pool_running doesn't accept start as parameter
**Description**
Docstring for `salt.states.virt.pool_running` mentions `start` as a parameter, but it is not defined as a parameter in the function.

**Setup**
`test.sls`:
```
test_pool:
  virt.pool_running:
    - start: True
    - ptype: dir
    - target: /tmp
    - autostart: True
```
**Steps to Reproduce the behavior**
Running a `state.apply` of the above `test.sls` state results in the following error:

```
    ERROR executing 'state.apply': 'start' is an invalid keyword argument for 'virt.pool_running'
``` 

**Expected behavior**
State should accept `start` as a valid parameter as indicated in docs.

**Screenshots**
Current docstring of `salt.states.virt.pool_running`:
```
    '''
    Defines and starts a new pool with specified arguments.

    .. versionadded:: 2019.2.0

    :param ptype: libvirt pool type
    :param target: full path to the target device or folder. (Default: ``None``)
    :param permissions:
        target permissions. See :ref:`pool-define-permissions` for more details on this structure.
    :param source:
        dictionary containing keys matching the ``source_*`` parameters in function
        :func:`salt.modules.virt.pool_define`.
    :param transient:
        when set to ``True``, the pool will be automatically undefined after being stopped. (Default: ``False``)
    :param autostart:
        Whether to start the pool when booting the host. (Default: ``True``)
    :param start:
        When ``True``, define and start the pool, otherwise the pool will be left stopped.
    :param connection: libvirt connection URI, overriding defaults
    :param username: username to connect with, overriding defaults
    :param password: password to connect with, overriding defaults

    .. code-block:: yaml

        pool_name:
          virt.pool_define

    .. code-block:: yaml

        pool_name:
          virt.pool_define:
            - ptype: netfs
            - target: /mnt/cifs
            - permissions:
                - mode: 0770
                - owner: 1000
                - group: 100
            - source:
                dir: samba_share
                hosts:
                  - one.example.com
                  - two.example.com
                format: cifs
            - autostart: True

    '''
```
**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: 4.0.4
      gitpython: 3.1.1
         Jinja2: 2.10.1
        libgit2: 0.28.3
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 1.0.3
         Python: 3.8.3rc1 (default, Apr 30 2020, 07:33:30)
   python-gnupg: 0.4.6
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: 3.0.2
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: debian testing bullseye
         locale: utf-8
        machine: x86_64
        release: 5.5.0-2-amd64
         system: Linux
        version: Debian GNU/Linux testing bullseye
```
</details>

**Additional context**
As a side note, the docstring example refers to `virt.pool_define` (twice) instead of `virt.pool_running`. 
This should probably be changed as well to prevent confusion.

### PR DESCRIPTION
**Pull request by cbosdo**
### What does this PR do?

As mentioned by issue #57275, the start parameter in virt.pool_running
documentation is not implemented at all. Remove it from the doc.

### What issues does this PR fix or reference?
Fixes: #57275 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [X] Docs
- [X] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated: Documentation-only change

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by Akm0d — DISMISSED** [review]

**Comment by cbosdo** [comment]
arg, rebased on master and review lost!

**Comment by cbosdo** [comment]
Rebased on latest master

**Comment by cbosdo** [comment]
rebased on master. @dwoz Since this is a doc-only fix, could this be merged?

**Comment by ScriptAutomate** [comment]
Just want to confirm that this an error in the documentation and not an error in the functionality of the state:

The referenced execution module `salt.modules.virt.pool_define` by `states.virt.pool_defined` does have a `start` param, which is defaulted to `True`:
- https://github.com/saltstack/salt/blob/master/salt/modules/virt.py#L5718

But, the state where you are modifying the documentation is defaulting to using `start=False` (`states.virt.pool_running` which calls `states.virt.pool_defined` has this within it) when calling the execution module: 
- https://github.com/saltstack/salt/blob/master/salt/states/virt.py#L1252

Was this param documented because the state function for `virt.pool_defined` is meant to have a `start` param with a default value?

If this is not the case, and it is just a documented parameter that doesn't exist (and wasn't meant to exist) for `states.virt.pool_running`, then I'll approve this change.

**Review by Akm0d — APPROVED** [review]

**Comment by cbosdo** [comment]
> Was this param documented because the state function for `virt.pool_defined` is meant to have a `start` param with a default value?
> 
> If this is not the case, and it is just a documented parameter that doesn't exist (and wasn't meant to exist) for `states.virt.pool_running`, then I'll approve this change.

The `start` parameter isn't supposed to exist since there are two separate states for that. The documentation was added simply with a careless copy/paste of mine.

**Pull request merged**
