### PR TITLE
Transport: misc cleanup

### PR DESCRIPTION
**Pull request by jacksontj**

### CODE REVIEW

**Comment by jacksontj** [comment]
FYI it seems that the beacons system has *no* test coverage, not only am I fairly certain they were broken in develop before a540f0a, I can't find anything with the word "beacon" in the tests dir :/

**Comment by jacksontj** [comment]
Looks like jenkins didn't start the VMs? (the output there is a bit hard to read)

**Comment by thatch45** [comment]
Yes, we have no test coverage on the beacons yet. Last I was using them off develop they were working but we do need to get tests in

**Comment by jfindlay** [comment]
@jacksontj, the test failure looks to be legitimate.

**Comment by jacksontj** [comment]
@jfindlay Sorry about the slow response, been out of town at an ATS summit ;) Looks like I typo'd and failed my FD leak check. Fix just pushed.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by jacksontj** [comment]
All passing now :)

**Pull request merged**
