### PR TITLE
* Replace ifilter to filter in module/upstart for python3 compatability

### PR DESCRIPTION
**Pull request by epikhinm**
Hi.

I have error on system with upstart, salt 2018.3 and python3, when i'm trying to enable service.
https://gist.github.com/epikhinm/3e0bed59df83ba7a14e14d096d3fb5b3
So, this PR will fix it. I didn’t find this error in other places.

Thanks.

### CODE REVIEW

**Comment by dwoz** [comment]
@epikhinm I'm sorry for the late turn around on this PR. Can you please resolve the inter issues?

**Comment by dwoz** [comment]
@epikhinm ping

**Comment by dwoz** [comment]
@epikhinm Are you able to resolve the merge conflict on this?

**Comment by sagetherage** [comment]
@epikhinm we are no longer taking changes against the develop branch. Can you rebase this against master? It looks as though this hasn't been reviewed in sometime and may be closed as abandoned by the author.

**Comment by sagetherage** [comment]
Reviewed in Grooming 2021-APR-05 #59934 will replace this

**Pull request closed without merging**
