### PR TITLE
Remove Sodium related deprecation warnings

### LINKED ISSUE #57516: [BUG] [RC1 Sodium] python 2 deprecation warnings  and halt salt-call
**Description**
Missed deprecation warnings:

 https://github.com/saltstack/salt/blob/master/salt/scripts.py#L106 and https://github.com/saltstack/salt/blob/master/salt/scripts.py#L215-L227

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title.
### What issues does this PR fix or reference?
Fixes #57516

### CODE REVIEW

**Comment by s0undt3ch** [comment]
This is blocked. We should just exit under Py2.

**Review by waynew — APPROVED** [review]

**Review by waynew — CHANGES_REQUESTED** [review]
Too soon. Looks like Windows builds are failing 😝

**Comment by s0undt3ch** [comment]
Removed some of the changes outside the scope of the issue. Let's wait and see.

**Comment by s0undt3ch** [comment]
Good to go.

**Pull request merged**
