### PR TITLE
Add docs and tests to disk state

### PR DESCRIPTION
**Pull request by jfindlay**
### What does this PR do?

Add docs and tests to disk state to remove ambiguity about what 'capacity' means and reinforce correct behavior.  Port of #33984 to develop branch.  Also fixes an error in #33918 where using `absolute: True` switched the meaning of `minimum` and `maximum`.  Ping, @cachedout.
### What issues does this PR fix or reference?

ZD-754
### Tests written?

Yes

### CODE REVIEW

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
Would it be possible to make these integration tests?

**Comment by jfindlay** [comment]
We could if you want, but it would be difficult to test numbers from a live disk as there is no guarantee what they will be.

**Comment by thatch45** [comment]
yes, good point, ok :)

**Pull request merged**
