### PR TITLE
Loader overhaul to LazyLoader

### PR DESCRIPTION
**Pull request by jacksontj**
DO NOT IMMEDIATELY MERGE!

This is a _major_ overhaul of the loader system (which was started back in #12327). In addition to lazily loading the modules, we create a singleton loader for each tag-type, meaning if someone asks for the modules (without passing them around) they will _not_ re-load all of them again (which is done in salt core LOTS). 

From my local testing this cuts 50% off of a local test.ping:

```
# old
(salt-github)[root@thjackso-ld salt-github]# time salt-call --local test.ping
local:
    True

real    0m2.908s
user    0m1.976s
sys 0m0.906s


# new
(salt-github)[root@thjackso-ld salt-github]# time salt-call --local test.ping
[ERROR   ] Template does not exists: 
local:
    True

real    0m1.562s
user    0m0.920s
sys 0m0.631s
```

An additional benefit to lazy loading, besides the performance, is sandboxing. Since modules are now only loaded when asked for the main salt-daemon process will only ever load up to all internal modules (since the core doesn't access user modules). This means if you were to (for example) ship a module which monkey patches all system stdlibraries etc. you would only be able to break the daemonized process that your job runs in. 

In addition, this somewhat alleviates the need for the modules_max_memory feature, since the modules will now only be loaded when they are asked for-- although I still find it useful :)

TODO before merge:
- ~~code review~~
- ~~tests!~~
- ~~proxy-minion~~
- ~~reload submodules~~

### CODE REVIEW

**Comment by cachedout** [comment]
Go Go Jenkins

**Comment by jacksontj** [comment]
That last run didn't seem to pick up the new commit fixing pyobjects... Re-running (hopefully)

**Comment by jacksontj** [comment]
@rallytime Did a new build start? I don't see anything in the UI, but I know there was some bug with that...

**Comment by rallytime** [comment]
@jacksontj Yep, looks like everything is good.

**Comment by jacksontj** [comment]
@rallytime Oh, all of them passed? If not, could I get links?

**Comment by rallytime** [comment]
Sorry, that was confusing. I just meant hat the build had started and and that a new trigger was running. The new run has finished up now, so the links above are correct. It looks like some of your refactoring is not what our test suite is expecting. :)

**Comment by jacksontj** [comment]
@rallytime weird... a bunch of those tests for pyobjects (such as unit.pyobjects_test.StateTests.test_duplicates) doesn't have that failure locally after my last commit. It seems that jenkins isn't pulling in the newest code :/

**Comment by rallytime** [comment]
Ok then let's try again.

**Comment by rallytime** [comment]
In case there is a problem with what results get posted, here are the build links for the latest run (I have verified that all builds are running off of the latest code, which is commit 5fd4d833f9bd969a046dd6af6b2aaa9be3fc65f6):
- Pylint: https://jenkins.saltstack.com/job/salt-pr-lint-n/1493/
- Ubuntu 14: https://jenkins.saltstack.com/job/salt-pr-rs-ubuntu14.04-n/1061/
- CentOS 7: https://jenkins.saltstack.com/job/salt-pr-rs-cent7-n/1061/

**Comment by jacksontj** [comment]
Thanks!

**Comment by jacksontj** [comment]
Hmm, getting some weird test output on the ubuntu boxes. https://jenkins.saltstack.com/job/salt-pr-rs-ubuntu14.04-n/1061/testReport/junit/unit.renderers.gpg_test/GPGTestCase/test_homedir_is_passed_to_gpg/ looks like dmidecode wasn't on the box which is odd. also odd that I don't get any similar failures over on the centos box :/

**Comment by jacksontj** [comment]
Rebasing on a newer develop... I'm unable to reproduce the test failures of the centos box locally-- they all pass :/

**Comment by jacksontj** [comment]
I *think * I know why its failing. I had changed the loader over to a singleton, but sometimes people pass in "functions" which gets packed into the modules. As a singleton the first one wins. So I've made the singleton return optional, and disabled it for the few function calls that pass in functions

**Comment by jacksontj** [comment]
Found the issue with the pyobjects renderer-- when I switched it to the new loader I didn't realize the old one ignored the virtual functions, so just added that in and all those test pass locally.

**Comment by rallytime** [comment]
Nice! @jacksontj The majority of the pylint failures are unrelated. I think they're a result of @s0undt3ch's changes to checking for python 3 compatibility that was merged recently. However, there was was one that I found that was related to your changes. Mind grabbing it?

https://jenkins.saltstack.com/job/salt-pr-lint-n/1528/violations/file/salt/modules/test.py/

**Comment by rallytime** [comment]
Cent 7 is looking better! Looks like something is still up with some of those Ubuntu tests though. None of the ones failing there are present on develop (nor have I seen them lately).

**Comment by jacksontj** [comment]
Found the utf-8 problems. The yaml renderer was doing some checks which involved the type of __salt__, which I changed ;) The stacktrace was a bit misleading, but that should fix it. I have both of those centos tests passing locally, so we'll see if the Ubuntu one's magically clear up ;)

**Comment by jacksontj** [comment]
@rallytime the 2 remaining gitfs failures seem unrelated-- esp since they pass locally...

**Comment by rallytime** [comment]
Yes, gitfs tests are spurious at best right now. We're working on getting those stabilized.

I'm still not sure what's happening with those Ubunut 14 tests. We'll need to clean those up, because they're definitely not a problem on develop right now. I'll see if I can reproduce them today.

**Comment by jacksontj** [comment]
@rallytime Can i get the debug log output? I can't seem to figure out how to view it on jenkins

**Comment by rallytime** [comment]
Do you just mean the stacktrace that comes from the test runner? Something like this? https://jenkins.saltstack.com/job/salt-pr-rs-ubuntu14.04-n/1120/testReport/junit/unit.renderers.gpg_test/GPGTestCase/test_encrypted_string_is_decrypted/
(You can get to that information my clicking each individual test failure listed underneath "Test Result")

I don't have access to any other logs either, as the VMs get destroyed after running the tests. Though I though we usually had more build artifacts listed like minon logs and such. I'm not sure why those aren't posting.

**Comment by jacksontj** [comment]
Yea, I was referring to the test run logs.. I'm setting up a local docker container to see if I can repro :/

**Comment by jacksontj** [comment]
@rallytime yea, with my local docker I don't get those errors about dmidecode. It seems like something is wrong with the VM :/

**Comment by rallytime** [comment]
Ok. I will have to look at this in the morning, or maybe later tonight. I wasn't able to get to this today. Thanks for your patience @jacksontj and for fixing up the CentOS tests. :)

**Comment by jacksontj** [comment]
@rallytime does jenkins run the tests in a docker container? If so, where can I pull that image down? I don't mind debugging the issue, but since I can't reproduce its difficult ;)

**Comment by s0undt3ch** [comment]
@jacksontj tests are not run in docker, they run in a cloud instance, we're currently using RackSpace.

**Comment by jacksontj** [comment]
@s0undt3ch Any way for me to pull the image down to run locally? Or a way to build an equivalent VM?

**Comment by cachedout** [comment]
@jacksontj We could probably arrange access to one of the testing containers but the steps I usually take are:

1) Spin up container/image/whatever
2) Use bootstrap script to install salt
3) Git clone salt-testing repo
4) Setup python paths
5) Pull down salt-jenkins repo
6) salt-call --local state.sls git.salt

That should give you a pretty close approximation.

**Comment by s0undt3ch** [comment]
The last step needs pillar information to use the right checkout

**Comment by s0undt3ch** [comment]
@jacksontj which vm would you prefer? the Cent7 or the Ubuntu 14?

**Comment by jacksontj** [comment]
@s0undt3ch Ubuntu, since the centos tests are passing :)

**Comment by s0undt3ch** [comment]
@jacksontj getting you "rigged up"...

**Comment by s0undt3ch** [comment]
I'll get you the VM details on IRC once it's up

**Comment by jacksontj** [comment]
Now that I have the rackspace host I have more data.
 - The gpg tests all pass
 - the SSH test failures where related, fixed though :)
 - pydsl_tests all but unit.pydsl_test.PyDSLRendererIncludeTestCase.test_rendering_includes pass on the VM, and that one fails on develop as well (so unrelated)

So I believe that means we are good to go.

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by jacksontj** [comment]
@rallytime @s0undt3ch That should do it. Tests pass locally, and I expect these to pass in jenkins (except for the few that seem to *always* fail on the Ubuntu VMs).

**Comment by cachedout** [comment]
Those errors were a result of the environ tests munging the system environment and affecting these tests down the line. I agree that we are ready to merge this. 

You ready for us to merge this today @jacksontj ?

**Comment by rallytime** [comment]
Thanks for looking into those Ubuntu failures @cachedout! I didn't realize that had been fixed upstream.

@jacksontj Mind grabbing these final pylint errors?
https://jenkins.saltstack.com/job/salt-pr-lint-n/1628/violations/file/salt/loader.py/
https://jenkins.saltstack.com/job/salt-pr-lint-n/1628/violations/file/salt/modules/test_virtual.py/
https://jenkins.saltstack.com/job/salt-pr-lint-n/1628/violations/file/tests/unit/loader.py/
https://jenkins.saltstack.com/job/salt-pr-lint-n/1628/violations/file/salt/client/ssh/wrapper/__init__.py/
https://jenkins.saltstack.com/job/salt-pr-lint-n/1628/violations/file/tests/integration/cli/custom_module.py/

The other files are unrelated to this change.

**Comment by jacksontj** [comment]
That should cover the pylint errors, and a rebase on newer develop :)

**Comment by jacksontj** [comment]
@rallytime That should do it :)

**Comment by cachedout** [comment]
So far this is performing quite well for me. Strong work, as always!

**Comment by jacksontj** [comment]
@cachedout in my local testing it cuts the time of a salt-call test.ping by ~50% Assuming develop doesn't explode I plan on opening a PR to backport this to 2015.2.

**Comment by cachedout** [comment]
Yeah, that's about what I see too. It's performing really well. There is an unrelated issue in the loader right now somewhere that's incurring 5s pauses seemingly at random with ``salt-call --local`` but it pre-dates this PR. Possibly an attempt to contact the master for some reason. Do let me know if you happen to see that, because I would like to confirm that I'm not the only person who has seen it.

**Comment by jacksontj** [comment]
IIRC that is expected, as salt-call will grab the pillar from the master on
start. I have a branch around here somewhere that makes that lazy... let me
see if I can find it.

**Comment by cachedout** [comment]
Even with --local? If that's expected, I wasn't aware of it.

Either way, if you do have a LazyLoader for it, that's a net-win either way.

**Comment by jacksontj** [comment]
Yea.. its kinda quirky ;) --local only means "dont send the ret to the master". The minion doesn't keep the pillar on disk anywhere for the salt-call process to read in. Probably a good place for some IPC or something on the minion.

**Comment by jacksontj** [comment]
Actually, looks like --local does attempt to generate a pillar, but locally (which is odd in and of itself). So, the 3s repro on my box was with it remote :/

**Comment by jacksontj** [comment]
LazyPillar on the minion in #20449

**Pull request merged**
