### PR TITLE
 Add service.status integration test

### PR DESCRIPTION
**Pull request by Ch3LL**
### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/43632

### CODE REVIEW

**Review by cachedout — COMMENTED** [review]
This looks right but we may need `crond` explicitly installed on our test machines. See: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/16107/testReport/integration.modules.test_service/ServiceModuleTest/

**Comment by Ch3LL** [comment]
Okay i used crond because I noticed tests/integration/states/test_service.py was using that service so we will need to change that too if this service change works. I changed it to docker because it looks like that is installed via the salt-jenkins states. Will see results of tests

**Comment by rallytime** [comment]
@Ch3LL That isn't quite right either as these tests are still skipped. This is because the system installed docker package is only installed on CentOS 7, while the pip package for docker is installed on all VMs for unit tests. The docker service is not available in the latter case. See [here](https://github.com/saltstack/salt-jenkins/blob/a434027c46cfad61dfab769e48d53a263ff770c8/git/salt.sls#L48) for more info.

**Comment by Ch3LL** [comment]
Okay I think I figured out the issue. `crond` is the name of cron service on only redhat OSs, and cron on debian. I built a couple of VMs for ubuntu/cent and cron was indeed an installed default service so I will just change i back to cron but add some logic to use different service name for the applicable OS.

**Comment by rallytime** [comment]
@Ch3LL Quick lint error, but other than that this looks good now.

**Review by rallytime — APPROVED** [review]

**Pull request merged**
