### PR TITLE
Whitespace bugfix in linux acl.getfacl

### PR DESCRIPTION
**Pull request by pakdel**
### What does this PR do?

bugfix: Whitespace in linux_acl.getfacl
### Previous Behavior

```
[root@saltmaster ~]# salt minion file.touch '/tmp/acl issue'
minion:
    True
[root@saltmaster ~]# salt minion file.stats '/tmp/acl issue'
minion:
    ----------
    atime:
        1475773217.09
    ctime:
        1475773217.09
    gid:
        0
    group:
        root
    inode:
        279473
    mode:
        0644
    mtime:
        1475773217.09
    size:
        0
    target:
        /tmp/acl issue
    type:
        file
    uid:
        0
    user:
        root
[root@saltmaster ~]# salt minion acl.getfacl '/tmp/acl issue'
minion:
    ----------
ERROR: Minions returned with non-zero exit code
```
### New Behavior

```
[root@saltmaster ~]# salt minion saltutil.sync_modules
minion:
    - modules.linux_acl

[root@saltmaster ~]# salt minion acl.getfacl '/tmp/acl issue'
minion:
    ----------
    /tmp/acl issue:
        ----------
        comment:
            ----------
            file:
                /tmp/acl issue
            group:
                root
            owner:
                root
        group:
            |_
              ----------
              root:
                  ----------
                  octal:
                      4
                  permissions:
                      ----------
                      execute:
                          False
                      read:
                          True
                      write:
                          False
        other:
            |_
              ----------
              :
                  ----------
                  octal:
                      4
                  permissions:
                      ----------
                      execute:
                          False
                      read:
                          True
                      write:
                          False
        user:
            |_
              ----------
              root:
                  ----------
                  octal:
                      6
                  permissions:
                      ----------
                      execute:
                          False
                      read:
                          True
                      write:
                          True
```
### Tests written?

Updated existing tests

It is a trivial fix

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
@pakdel It looks like some of the linux_acl unit tests are failing from this fix. Can you take a look at those?

**Comment by pakdel** [comment]
@rallytime I am setting up my test environment to fix it....

**Comment by pakdel** [comment]
Go Go Jenkins!

**Comment by pakdel** [comment]
Current failures seem to be unrelated.

**Comment by pakdel** [comment]
Will this be back-ported to 2015.8 ?

**Pull request merged**
