### PR TITLE
Feature: Add namecheap api modules and boto efs

### PR DESCRIPTION
**Pull request by mikelodder7**
Namecheap Domain name and SSL management apis
Added Amazon EFS execution module via boto3
Updated Minion master: func to allow a list of master addresses
Tests written?
No, but currently used in our production environment.

### CODE REVIEW

**Comment by cachedout** [comment]
@mikelodder7 Could you please fix these lint errors before we merge this? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/7698/violations/file/salt/modules/namecheap_ssl.py/

**Comment by mikelodder7** [comment]
Sure will do.

**Comment by mikelodder7** [comment]
Can you direct to as to why these failed the build again?

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by mikelodder7** [comment]
So are you wanting the docstrings with three double quotes or is three single quotes acceptable because the test results say no docstrings are found but they are clearly there.

**Comment by cachedout** [comment]
Something happened during your last git push and a number of files have been included which I don't think were intended. Could you either rebase this against develop and then re-push or close this PR and open a new one with just the files in question? Thanks and sorry for the trouble.

**Pull request closed without merging**
