### PR TITLE
Switch Jenkins pipeline libs to ``master-2.0``

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
Switch Jenkins pipeline libs to ``master-2.0``

### CODE REVIEW

**Comment by s0undt3ch** [comment]
re-run all

**Comment by s0undt3ch** [comment]
re-run all

**Comment by s0undt3ch** [comment]
re-run full all

**Review by MKLeb — DISMISSED** [review]

**Review by twangboy — DISMISSED** [review]

**Comment by krionbsd** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Review by twangboy — DISMISSED** [review]

**Review by MKLeb — DISMISSED** [review]

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by Ch3LL** [comment]
@s0undt3ch can this be closed now that we are migrating to github actions?

**Comment by s0undt3ch** [comment]
Yes.

**Pull request closed without merging**
