### PR TITLE
Back-port #30796 to 2015.8

### PR DESCRIPTION
**Pull request by rallytime**
Back-port #30796 to 2015.8

### CODE REVIEW

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by jtand** [comment]
@rallytime How do you want to handle that lint issue?

**Comment by rallytime** [comment]
I'll figure it out later. It's probably pointing out a legitimate problem where the 2015.8 branch is different than the 2016.3 version of the `self._load_modules()` function.

**Comment by rallytime** [comment]
@DmitryKuzmenko In issue #30796 @meggiebot marked it for back-porting based on [your comment](https://github.com/saltstack/salt/issues/29567#issuecomment-189311175) in #29567. 

However, this change relies on the return of the `_load_modules()` function in minion.py, which was refactored in #26758 to return 4 objects rather than 3. I am not sure what the correct course of action is here, since the change you made in #26758 was a fairly large change that I am hesitant to completely back-port the whole change to 2015.8. What are your thoughts on this matter, given your comment in #29567?

**Comment by DmitryKuzmenko** [comment]
@rallytime #30796 is already back-ported by #31525

**Comment by rallytime** [comment]
Ok. Thanks!

**Pull request closed without merging**
