### PR TITLE
Fixes 'docker_container does not support ipv6 port bindings' https://…

### LINKED ISSUE #53709: docker_container does not support ipv6 port bindings
Here's the example to reproduce

```yaml
include:
  - sys.docker  # installs and configures docker (enables v6 support)

duo-access-gateway_volume:
  docker_volume.present:
    - name: duo-access-gateway
    - driver: local

duo-container:
  docker_container.running:
    - name: duo-access-gateway
    - image: duosecurity/access-gateway@sha256:ba065e9a04478fc17fd5b61b8c558616b7e9acba105668ef786f084545c32778
    - labels:
      - 'com.duo.access-gateway.builder.version': '62dc4eaf'
      - 'com.duo.access-gateway.code.version': 'v1.5.6'
      - 'com.duo.access-gateway.built': 'Fri, 14 Dec 2018 20:50:35 -0000'
    - restart_policy: always
    - log_driver: json-file
    - log_opt:
      - max-size: '50m'
      - max-file: '20'
    - port_bindings:
      - 'foo:bar:baz::foobar:80:8000'
      - '443:4443'
      - '8443:8443'
    - binds:
      - duo-access-gateway:/data
    - require:
      - docker_volume: duo-access-gateway_volume
```

You'll get an error like

```
local:
----------
          ID: duo-container
    Function: docker_container.running
        Name: duo-access-gateway
      Result: False
     Comment: Failed to translate input. Additional info follows:
              
              invalid:
                  ----------
                  port_bindings:
                      'foo:bar:baz::foobar:80:8000' is an invalid port binding definition (at most 3 components are allowed, found 7)
              
              If you feel this information is incorrect, the skip_translate argument can be used to skip input translation for the argument(s) identified as invalid. See the documentation for details.
```

I've tried the skip_translate option but it didn't help.

https://github.com/docker/docker-py/blob/master/docker/utils/ports.py#L3 is how upstream suports it (crazy regex).

https://github.com/saltstack/salt/blob/develop/salt/utils/docker/translate/container.py#L388 is why it's broken (it does a basic split on ':', which does not work for ipv6...)

### PR DESCRIPTION
**Pull request by HenriWahl**
### What does this PR do?
Allows to define IPv6 addresses in port_bindings directive of docker_container state. Use brackets as widely done: 
```
  - port_bindings: 
      - 172.16.0.1:443:443
      - '[2001:db8::1]:443:443'
```

### What issues does this PR fix or reference?
Closes https://github.com/saltstack/salt/issues/53709

### Previous Behavior
Error thrown because of too many ':' in address+ports-combo

### New Behavior
Accept IPv6-addresses in brackets by temporarily hiding the IPv6-related ':' to keep number of maximal binding elements on 3 - 1 address, 1 external and 1 internal port.

### Tests written?
Surely already exists for previously written module - this fix does not change anything big, just makes things work.

**Edit:** Yes, extended existing file tests/unit/utils/docker_test.py.

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by HenriWahl** [comment]
@dwoz what does the label mean? Should I give an example config?

**Comment by HenriWahl** [comment]
I extendend the existing file tests/unit/utils/docker_test.py to cover bracketed IPv6 addresses too and hope this will do it.

**Comment by HenriWahl** [comment]
Apparently the testing in Jenkins failed:
```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/utils/test_docker.py", line 1342, in test_port_bindings
    port_bindings=val,
  File "/tmp/kitchen/testing/salt/utils/docker/__init__.py", line 271, in translate_input
    'Failed to translate input', info=error_data)
CommandExecutionError: Failed to translate input. Additional info follows:

invalid:
    ----------
    port_bindings:
        Empty port binding definition found
```
@cmcmarrow @team-core can you give me a hint how I can run this single test for tests/unit/utils/test_docker.py locally?

**Comment by HenriWahl** [comment]
Can somehome help and tell me what https://jenkinsci.saltstack.com/job/pr-kitchen-ubuntu1804-py3/job/PR-55315/5/testReport/junit/unit.utils.test_docker/TranslateContainerInputTestCase/test_port_bindings/ means?

**Comment by HenriWahl** [comment]
@dwoz apparently finally the tests related to my change work. I learned a lot..

**Comment by HenriWahl** [comment]
@cmcmarrow is it ok when the tests relevant to my changes are ok?

**Comment by HenriWahl** [comment]
@dwoz @cmcmarrow @saltstack/team-core what else is missing to be merged?

**Comment by HenriWahl** [comment]
How can I help to merge?

**Comment by HenriWahl** [comment]
Hellohello - any chance IPv6 address support will find a way into Saltstack Docker?

**Comment by cmcmarrow** [comment]
I apologies for the late response @HenriWahl. The test changes look okay to me!

**Comment by cmcmarrow** [comment]
re-run all

**Comment by cmcmarrow** [comment]
I restarted for you. I’ll check in on this PR sometime tomorrow.

**Comment by cmcmarrow** [comment]
@HenriWahl I’m happy you learned a lot about tests. Its always a win when you learn something new.

**Comment by cmcmarrow** [comment]
re-run full all

**Comment by cmcmarrow** [comment]
re-run all full

**Comment by cmcmarrow** [comment]
It looks like we also have some conflicts that we need to handle. Once that is done we just need all the test to pass and it will be merge ready!

**Comment by sagetherage** [comment]
@HenriWahl are you able to address the merge conflicts, here?

**Comment by HenriWahl** [comment]
> @HenriWahl are you able to address the merge conflicts, here?

Hi, sorry for the late answer. What exactly can I do?

**Comment by HenriWahl** [comment]
What a mess... some months ago I deleted my fork of salt because of nothing happened - so I do not know how to access my changes. Next thing: the failed checks above are not retrievable to find out what causes the failures so I do not know where to start with and what with.

**Comment by sagetherage** [comment]
@HenriWahl we have not done well, here and I apologize! I will get some help, in the meantime you can recreate your fork and  then I believe there are several ways to get the change from this PR into your fork, but I am not sure what is the best way - maybe a patch, but I will get an engineer to help very soon!

**Comment by HenriWahl** [comment]
@sagetherage I would like to do this but I wish I knew how to restore it. Or be able to get the changes into a current codebase.

**Comment by sagetherage** [comment]
@HenriWahl oh yes, and Chad who I have assigned, is busy with something ATM, let me see if @waynew can also help.

**Comment by waynew** [comment]
@HenriWahl yeah, no problem, I can help! Most of what you're looking for *should* be pretty straightforward:

If you go ahead and recreate your fork, you can do this:

```
git clone -o salt git@github.com:saltstack/salt.git
cd salt
git remote add henri git@github.com:HenriWahl/salt.git  # change henri for whatever reminds you it's your own personal repo
git fetch salt refs/pull/55315/head
git checkout salt/master
git cherry-pick <commits go here>
git push henri HEAD:master   # assumes henri as your own fork
```

you can get the commits that you want to cherry pick from https://github.com/saltstack/salt/pull/55315/commits

The cherry pick process will probably have a ton of confilcts - it may be easier to just start from the current `salt/master` and manually add whatever changes you want to make from this PR.

If you have any problems, especially with writing tests, attend one of the [Test Clinics on Twitch](https://www.twitch.tv/saltstackinc/schedule), and I'd be more than happy to walk you through things. Or ping me on here :+1:

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it they want to see it through to the end in a release cycle.

**Pull request closed without merging**
