### PR TITLE
Use dsn if specified as all recent raven libraries can init via dsn

### PR DESCRIPTION
**Pull request by nasenbaer13**
### What does this PR do?

Removes deprecated sentry functionality, make clear distinction between setting up sentry via dsn (supported by all recent sentry client libraries) and setting up using 'project', 'servers', 'public_key' and 'secret_key'.

### What issues does this PR fix or reference?

Renders mod_sentry functional with recent sentry versions.

### Tests written?

No

### CODE REVIEW

**Comment by nasenbaer13** [comment]
please also merge to 2017.7.

**Comment by cachedout** [comment]
Hi @nasenbaer13

I want to make sure that I understand this. Are you saying that functionality has changed upstream with the raven libs and that these changes are needed to preserve compatability? If so, have these changes compatible with older versions of Raven as well?

**Comment by nasenbaer13** [comment]
Yes, the current sentry raven clients are initialized via dsn only (https://docs.sentry.io/clients/python/advanced/#python-client-config), 'project', 'servers', 'public_key', 'secret_key' are not supported according to the doc. So specifying a dsn now correctly initialises an up to date raven client.

It's still possible with the code above to use an old raven client library if one does not specify a dsn but the individual parts. The functionality to specify a dsn and initialize an old style raven is not supported. I doubt that anyone is using this setup.

**Comment by cachedout** [comment]
@nasenbaer13 Do you know exactly where that deprecation occurred in Raven? My concern here is that I want to make sure we clearly explain this change in release notes.

**Comment by nasenbaer13** [comment]
@cachedout https://github.com/getsentry/raven-python/blob/master/CHANGES

The relevant changes are probably:

Raven-Python Version 5.3.0 (Mar 2015)
...
* Server configuration *must* now be specified with a DSN.
...

-> No client with version >=5.3 will work without dsn specified.
-> Salt won't work at the moment with more than 2 year old clients :-)

Raven-Python Version 3.0.0 (Dec 2012)
...
* Configuring the client with an empty DSN value will disable sending of messages.
...

-> No client with version >= 3.0 will send messages without dsn?

Support for dsn is in there since Raven-Python Version 1.2.0 (Jan 2012)

-> All clients starting from 1.2 can make use of a dsn instead of server config.

Does that help for the changelog?

**Comment by cachedout** [comment]
@nasenbaer13 It does! Would you mind updating the changelog with a summary? It is here:

https://github.com/saltstack/salt/blob/develop/doc/topics/releases/oxygen.rst

Once that's in, I think we can merge this.

**Comment by nasenbaer13** [comment]
@cachedout : section added to release notes. Do you see a chance to fix this in 2017.7 as well? If so, I can prepare a backport and adapt the release notes there as well.

**Comment by rallytime** [comment]
Hi @nasenbaer13 - since this is a feature addition, we should keep it in the `develop` branch. It will be available in the next feature release, which is code-named `Oxygen`. Thanks for submitting this!

**Review by rallytime — APPROVED** [review]

**Pull request merged**
