### PR TITLE
Port #50189 to master

### PR DESCRIPTION
**Pull request by terminalmage**
See https://github.com/saltstack/salt/pull/50189

### CODE REVIEW

**Review by Ch3LL — CHANGES_REQUESTED** [review]
looks like this needs a testcase. I know you did not originally write this code so let me know if i can help write a test here.

**Comment by terminalmage** [comment]
Thanks @Ch3LL, I had added some tests already in a different PR I ported for this cloud driver, but hadn't been able to figure out how to add one for this.

**Comment by Ch3LL** [comment]
do you have a link to that PR with the tests?

**Comment by terminalmage** [comment]
@Ch3LL https://github.com/saltstack/salt/pull/56707

Thanks!

**Comment by Ch3LL** [comment]
im not seeing where in that test its covering `agent_get_ip`. I'm more than willing to write a test, just let me know if you arent able to and i'll take look at writing one.

**Comment by terminalmage** [comment]
Yeah, that other PR wasn't for this feature, it was a different one. I mentioned that I had already written tests for this driver for a different PR, but hadn't figured out the best way to add one for this `agent_get_ip` option.

**Comment by terminalmage** [comment]
Just FYI, I just rebased to resolve merge conflicts (and removed six usage), so you'll need to pull and hard-reset if you've already checked out this PR branch locally.

**Comment by Ch3LL** [comment]
thanks. i'll add this on my backlog of tests to write. thanks

**Comment by dsaard** [comment]
This change would be nice to be ported to the master branch :+1:

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
