### PR TITLE
add missing parenthis to keep integration with python3

### PR DESCRIPTION
**Pull request by pkruk**
### What does this PR do?
Fix spotted missing parenthis in issue: https://github.com/saltstack/salt/issues/44863
### Tests written?

No

### Commits signed with GPG?

OLD: No
I added a GPG signature, a moment ago

### CODE REVIEW

**Review by rallytime — APPROVED** [review]
Welcome @pkruk! Good find and thank you for submitting this fix.

**Comment by pkruk** [comment]
@rallytime Hi :) thanks ;) From what I see couldn't pass a tests, there is some problems at now with tests in jenkins?

**Comment by rallytime** [comment]
@pkruk Those test failures are not related to your change.

**Comment by pkruk** [comment]
Ok :) thanks:)

**Pull request merged**
