### PR TITLE
Use the generic `text` attribute, not .body of the handler

### LINKED ISSUE #27794: Requests backend for HTTP fetches is broken after removing streamed response handlers
Commit acf2d51440af97836b48adb18276df5263590f51 modified `salt/fileclient.py` to directly write out the `.body` of the response rather than a streaming handler.

This is all well & good, but the `requests` backend result does not contain a `.body`, resulting in 
```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1590, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1483, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/pkg.py", line 1081, in installed
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py", line 520, in install
    name, pkgs, sources, **kwargs
  File "/usr/lib/python2.7/dist-packages/salt/modules/pkg_resource.py", line 140, in parse_targets
    srcinfo.append(__salt__['cp.cache_file'](pkg_src, saltenv))
  File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 365, in cache_file
    result = __context__['cp.fileclient'].cache_file(path, saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 155, in cache_file
    return self.get_url(path, '', True, saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 614, in get_url
    destfp.write(query['handle'].body)
AttributeError: 'Response' object has no attribute 'body'
```

The result is actually in `.content` for a `requests` Response.

The problem is rather pressing for us because of #8177/#23617/#21985. Currently the *only* way to get Salt's HTTP requests to use a proxy is by utilizing the `requests` backend & specifiying the environment variables.

### PR DESCRIPTION
**Pull request by jacksontj**
fixes #27794 until we can simplify this somewhat crazy HTTP lib :/

### CODE REVIEW

**Comment by The-Loeki** [comment]
Euhm

```
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1592, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1490, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/pkg.py", line 1081, in installed
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py", line 520, in install
                  name, pkgs, sources, **kwargs
                File "/usr/lib/python2.7/dist-packages/salt/modules/pkg_resource.py", line 140, in parse_targets
                  srcinfo.append(__salt__['cp.cache_file'](pkg_src, saltenv))
                File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 365, in cache_file
                  result = __context__['cp.fileclient'].cache_file(path, saltenv)
                File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 155, in cache_file
                  return self.get_url(path, '', True, saltenv)
                File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 616, in get_url
                  destfp.write(query['text'])
              KeyError: 'text'
```
???

**Comment by The-Loeki** [comment]
It sortakinda works if I use `query['handle'].text` for `requests`, but, not entirely against expectations, fails horribly with a binary file:

```
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1592, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1490, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/pkg.py", line 1081, in installed
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/aptpkg.py", line 520, in install
                  name, pkgs, sources, **kwargs
                File "/usr/lib/python2.7/dist-packages/salt/modules/pkg_resource.py", line 140, in parse_targets
                  srcinfo.append(__salt__['cp.cache_file'](pkg_src, saltenv))
                File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 365, in cache_file
                  result = __context__['cp.fileclient'].cache_file(path, saltenv)
                File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 155, in cache_file
                  return self.get_url(path, '', True, saltenv)
                File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 617, in get_url
                  destfp.write(query['handle'].text)
              UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd' in position 133: ordinal not in range(128)
```

**Comment by jacksontj** [comment]
Just giving me many more reasons to dislike this http function :/ We really need to clean up the lib and remove the multiple implementations. Let me set this up locally again and look at it some more :/

**Comment by The-Loeki** [comment]
No argument here ;) In the meantime though I'd advise you to revert to old behaviour; having pplz like me using `requests` break is a lot less invasive than have everybody break ;)

**Comment by jacksontj** [comment]
I've opened #28092 for the revert of this. I wonder if someone has a list of all of the bugs with the tornado impl-- if they aren't terribly long it'll probably be less work to just finish that :/

**Comment by The-Loeki** [comment]
Well that'd be nice, but in order for Tornado to use proxy, you'd have to be able to switch to `curl_httpclient` (http://tornadokevinlee.readthedocs.org/en/latest/httpclient.html).

If that's a possibility I see little to no reason to keep requests if you guys like Tornado so much better :)

**Comment by jacksontj** [comment]
Well, I like requests-- but since we already require tornado for the core-- it would be nice to drop a dep :)

**Pull request merged**
