### PR TITLE
fix: load elasticsearch module conditionally to the elasticsearch-py version.

### PR DESCRIPTION
**Pull request by cesan3**
### What issues does this PR fix or reference?
Fixes: 61973

### Previous Behavior
Unable to use elasticsearch module with ES8+

### New Behavior
New elasticsearch8 module with virtualname->elasticsearch that loads if ES8 python library is loaded.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by whytewolf** [comment]
Thank you for the work. Since this is a new module instead of the continuation of an existing module, at this time we would like to please ask that this be created as a salt-extension instead of something directly in salt. 

you can make this transition easier with 
https://github.com/saltstack/salt-extension

an example of an extension module a can be found at https://github.com/saltstack/salt-ext-modules-vmware

**Comment by cesan3** [comment]
> Thank you for the work. Since this is a new module instead of the continuation of an existing module, at this time we would like to please ask that this be created as a salt-extension instead of something directly in salt.
> 
> you can make this transition easier with https://github.com/saltstack/salt-extension
> 
> an example of an extension module a can be found at https://github.com/saltstack/salt-ext-modules-vmware

Thanks @whytewolf for the suggestion, however, I have some questions.
1.  In this patch, I also update the current module, to load only if ES8 version is lower than 8.  Where shall I work that part? keep it here?  I guess so if I understand your policy of current modules update vs new modules.
2. How is the external module integrated with latest version of salt?
3. Where should I create that module? New private/personal repo with the name 'salt-ext-elasticsearch8' for example?

Thanks again...

**Comment by cesan3** [comment]
Hello @whytewolf .  I would really appreciate your feedback on the extension module I prepared to use alternatively for ES8 and to be used in conjunction with this MR.  https://github.com/cesan3/salt-ext-elasticsearch8 I had a hard time making it work and as a caveat, I had to remove the workflow for Windows at least to have a successful pass.

**Comment by whytewolf** [comment]
I like it, but was wondering. just to make sure it works and stays working. is it possible to run a test tat checks what happens when ES 8 is installed. make sure it fails properly.

**Comment by cesan3** [comment]
> I like it, but was wondering. just to make sure it works and stays working. is it possible to run a test that checks what happens when ES 8 is installed. make sure it fails properly.

Sure, I'll check it.

**Comment by cesan3** [comment]
> I like it, but was wondering. just to make sure it works and stays working. is it possible to run a test tat checks what happens when ES 8 is installed. make sure it fails properly.

Hey Tomas @whytewolf, I think there's some WIP regarding integration tests for elasticsearch [here:](https://github.com/saltstack/salt/pull/60486). 

The best I can do in this case without implementing integration tests and updating the requirements as implemented in the PR (https://github.com/saltstack/salt/pull/60486), is to condition the tests execution. So, if the library is missing, we report Skipping elasticsearch tests, missing library:
```
 pytest tests/pytests/unit/modules/test_elasticsearch.py -k virtual -v
===================================================================================== test session starts ======================================================================================
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.0.0 -- /Users/csanchez/virtualenvs/venv_salt3.9/bin/python
cachedir: .pytest_cache
tempdir: /tmp/stsuite
max open files; soft: 1048576; hard: 1048576
rootdir: /salt
configfile: pytest.ini
plugins: shell-utilities-1.7.0, skip-markers-1.4.0, httpserver-1.0.8, system-statistics-1.0.2, flaky-3.7.0, salt-factories-1.0.0rc23, helpers-namespace-2021.12.29, tempdir-2019.10.12, custom-exit-code-0.3.0, subtests-0.11.0, timeout-2.1.0
collected 113 items / 111 deselected / 2 selected

tests/pytests/unit/modules/test_elasticsearch.py::test__virtual_no_elasticsearch_lib SKIPPED (Skipping elasticsearch tests, missing library)                                             [ 50%]
tests/pytests/unit/modules/test_elasticsearch.py::test__virtual_with_elasticsearch_lib SKIPPED (Skipping elasticsearch tests, missing library)                                           [100%]

============================================================================== 2 skipped, 111 deselected in 0.04s ==============================================================================
```
And if it's the wrong version, 8+: (Skipping elasticsearch tests, incompatible version)
```
 pytest tests/pytests/unit/modules/test_elasticsearch.py -k virtual -v
===================================================================================== test session starts ======================================================================================
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.0.0 -- /Users/csanchez/virtualenvs/venv_salt3.9/bin/python
cachedir: .pytest_cache
tempdir: /tmp/stsuite
max open files; soft: 1048576; hard: 1048576
rootdir: /salt
configfile: pytest.ini
plugins: shell-utilities-1.7.0, skip-markers-1.4.0, httpserver-1.0.8, system-statistics-1.0.2, flaky-3.7.0, salt-factories-1.0.0rc23, helpers-namespace-2021.12.29, tempdir-2019.10.12, custom-exit-code-0.3.0, subtests-0.11.0, timeout-2.1.0
collected 113 items / 111 deselected / 2 selected

tests/pytests/unit/modules/test_elasticsearch.py::test__virtual_no_elasticsearch_lib SKIPPED (Skipping elasticsearch tests, incompatible version)                                        [ 50%]
tests/pytests/unit/modules/test_elasticsearch.py::test__virtual_with_elasticsearch_lib SKIPPED (Skipping elasticsearch tests, incompatible version)                                      [100%]

============================================================================== 2 skipped, 111 deselected in 0.08s ==============================================================================
```
But when ES version < 8:
```
pytest tests/pytests/unit/modules/test_elasticsearch.py -k virtual -v
===================================================================================== test session starts ======================================================================================
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.0.0 -- /Users/csanchez/virtualenvs/venv_salt3.9/bin/python
cachedir: .pytest_cache
tempdir: /tmp/stsuite
max open files; soft: 1048576; hard: 1048576
rootdir: /salt
configfile: pytest.ini
plugins: shell-utilities-1.7.0, skip-markers-1.4.0, httpserver-1.0.8, system-statistics-1.0.2, flaky-3.7.0, salt-factories-1.0.0rc23, helpers-namespace-2021.12.29, tempdir-2019.10.12, custom-exit-code-0.3.0, subtests-0.11.0, timeout-2.1.0
collected 113 items / 111 deselected / 2 selected

tests/pytests/unit/modules/test_elasticsearch.py::test__virtual_no_elasticsearch_lib PASSED                                                                                              [ 50%]
tests/pytests/unit/modules/test_elasticsearch.py::test__virtual_with_elasticsearch_lib PASSED                                                                                            [100%]

============================================================================== 2 passed, 111 deselected in 1.06s ===============================================================================
```

What do you think?

**Comment by whytewolf** [comment]
I think that will work. I"ll get some other reviewers added in after that is implemented just to see what they think as well.

**Pull request closed without merging**
