### PR TITLE
Fix deployment when umask is non-standard. Fixes #28830

### LINKED ISSUE #28830: non-standard umask breaks salt-ssh deployement
With umask 0133, salt-ssh is not able to properly deploy its archive, due to tar being expanded without changing system umask.

### PR DESCRIPTION
**Pull request by fcrozat**

### CODE REVIEW

**Comment by cachedout** [comment]
Ping @basepi

**Comment by basepi** [comment]
I think this actually may explode for non-root users. I think I'll have to do some testing.

**Comment by fcrozat** [comment]
My test is done as a non-root user (to do non-root tasks) but I haven't finished testing everything is working out of the box..

**Comment by basepi** [comment]
Thanks @fcrozat! After further thought I think this is a good fix.

**Pull request merged**
