### PR TITLE
Enable pillar/compound matching in mine/publish, with no pillar globbing support

### PR DESCRIPTION
**Pull request by basepi**
STATUS: Merge away! (Assuming tests pass, of course)

I have manually tested both mine and publish for compound/pillar matching and it's working now, and successfully preventing pillar globbing.

This should be reviewed carefully. With this patch, pillar and compound matching will work for both mine and publish functions. However, pillar matches will use exact matching, globbing is disabled. This is primarily accomplished with the changes to `subdict_match` in `salt.utils.minions.CkMinions`. I also added two new match types, `pillar_exact` and `compound_pillar_exact`, and ensure that those matches are used instead of `pillar` and `compound` respectively for all publish and mine queries.

### CODE REVIEW

**Comment by bcarpio** [comment]
Hi,

Possibly this is due to my lack of understand about how the mine actually works, but here is what I see and I'm not sure this is correct. 

On salt master when I run:

salt 'salt-master' mine.get 'G@roles:zookeeper and G@zookeeper:cluster_name:dev-mesos-cluster' network.ip_addrs compound

I get nothing back, however when I run 'salt-call' instead of just salt I get the list of hosts I expect. 

When I run the following:

salt 'salt-master' mine.get 'G@roles:zookeeper and G@zookeeper:cluster_name:dev-mesos-cluster' network.ip_addrs compound_pillar_exact

I get the list of hosts and their associated IP addresses, also when using salt-call and passing 'compound_pillar_exact' I also get the list of hosts and their associated IP addresses. 

I'm not sure I fully understand the difference between compond and compound_pillar_exact. Also compound_pillar_exact doesn't seem to work at all in a vagrant environment which doesn't have a salt master, and relies upon salt-call for provisioning.

**Comment by basepi** [comment]
Hrm, that's strange. It should work with just `compound`. And the fact that it's working with `salt-call` leads me to believe that something else is going on with the returns, rather than a problem with the actual `mine.get` routines.

I would be interested to hear whether your return are consistent across multiple runs, or maybe with a longer timeout:

```
salt 'salt-master' mine.get 'G@roles:zookeeper and G@zookeeper:cluster_name:dev-mesos-cluster' network.ip_addrs compound -t 60
```

**Comment by bcarpio** [comment]
So I just tried this with the compound -t 60, and it doesn't even wait 60 seconds, the command returns:

```
salt 'salt-master' mine.get 'G@roles:zookeeper and G@zookeeper:cluster_name:dev-mesos-cluster' network.ip_addrs compound -t 60
```

```
Executing job with jid 20150204021034698067
-------------------------------------------

salt-master:
```

Per your suggestion I tried this multiple times with no luck, however when I run the same command:

```
salt 'salt-master' mine.get 'G@roles:zookeeper and G@zookeeper:cluster_name:dev-mesos-cluster' network.ip_addrs compound_pillar_exact 
```

Time and time again I get the correct output:

```
Executing job with jid 20150204021049186235
-------------------------------------------

salt-master:
    ----------
    master-meso-0001:
        - 10.10.10.10
    master-meso-0002:
        - 10.10.20.10
    master-meso-0003:
        - 10.10.30.10
```

**Comment by basepi** [comment]
Very strange. You definitely shouldn't have to add the `_pillar_exact` on the end there, so there may be a bug here. Would you mind opening a new issue and including all the information you've included here?

**Pull request merged**
