### PR TITLE
Fix exception in boto_iam.create_policy_version

### PR DESCRIPTION
**Pull request by donkopotamus**
### What issues does this PR fix or reference?

It is currently possible for an exception to occur before a version identifier could be resolved,
resulting in an exception **during exception handling**.

### Previous Behavior
```
local:
----------
          ID: <redacted>
    Function: boto_iam.policy_present
        Name: <redacted>
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/boto_iam.py", line 1529, in policy_present
                  keyid=keyid, profile=profile)
                File "/usr/lib/python2.7/site-packages/salt/modules/boto_iam.py", line 1850, in create_policy_version
                  log.error('Failed to create IAM policy %s version %s.', policy_name, vid)
              UnboundLocalError: local variable 'vid' referenced before assignment
     Started: 21:15:56.936631
    Duration: 2185.593 ms
     Changes:
```

### New Behavior
```
[ERROR   ] Failed to create IAM policy <redacted>.
...
local:
----------
          ID: aws s3 iam policy rrt-app-instance-policy
    Function: boto_iam.policy_present
        Name: rrt-app-instance-policy
      Result: False
     Comment: Failed to update policy: Bad Request: <reason here>
     Started: 21:17:31.295869
    Duration: 2189.172 ms
     Changes:
```

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by waynew** [comment]
@donkopotamus would you be able to rebase this on master? It also needs a changelog entry and some tests. If you'd like some help on that, I'm running a test clinic tomorrow on our twitch stream: https://www.twitch.tv/saltstackinc

**Review by waynew — CHANGES_REQUESTED** [review]
Hey, thanks for the PR! We definitely appreciate your efforts so far! We realize that priorities can change, and contributing to Salt may not be at the top of your list. If this is the case for you, no response needed - if we haven't heard back from you after a week, we'll go ahead and close this PR and add the "on hold" label. At any point in the future if you (or someone else) is ready to pick this back up, just let us know and we'll be happy to re-open the PR so we can get it merged.

If you need help writing documentation, we have a [documentation working group](https://github.com/saltstack/docs-hub) that would love to help out.

If you're struggling with writing tests, reach out to the [testing working group](https://github.com/saltstack/community/tree/master/working_groups/wg-Testing) or attend one of the [Test Clinics on Twitch](https://www.twitch.tv/saltstackinc/schedule).

Thanks again!

**Comment by donkopotamus** [comment]
@waynew This was just a simple attempt to provide an obvious fix to an obvious exception, done as a drive by in github itself.  Its a three line fix that is pretty easy to reason about.

Unfortunately I have to be honest and say I just don't have enough free time at present to learn the `salt` test infrastructure enough to generate additional unit tests for what is, lets face it, a simple fix to a simple problem.

If fixing such tiny bugs takes contributors extra hours to write changelogs and unit tests and documentation, then its inevitable such tiny bugs won't get fixed.  Like this one, probably.

**Comment by donkopotamus** [comment]
(Having said that, I have rebased it and added a changelog entry)

**Comment by waynew** [comment]
> @waynew This was just a simple attempt to provide an obvious fix to an obvious exception, done as a drive by in github itself. Its a three line fix that is pretty easy to reason about.
> 
> Unfortunately I have to be honest and say I just don't have enough free time at present to learn the `salt` test infrastructure enough to generate additional unit tests for what is, lets face it, a simple fix to a simple problem.

No worries - a contribution is a contribution :smiley: 
 
> If fixing such tiny bugs takes contributors extra hours to write changelogs and unit tests and documentation, then its inevitable such tiny bugs won't get fixed. Like this one, probably.

We do welcome contributions that we won't merge as-is - as you point out it's a small fix that's easy to reason about, which is great! What I've seen, repeatedly, is eventually some change will come along that breaks this kind of fix, or there's other bugs near small changes like this that are exposed when we start to write tests :upside_down_face: 

I will tackle this during Thursday's [Test Clinic on Twitch](https://www.twitch.tv/saltstackinc/schedule) - my guess is for something this small there won't be more than one or two tests to write to finish this up... unless I uncover some other bugs :joy: Then we'll have some regression tests to ensure that this bug isn't re-introduced at some later date :+1:

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
