### PR TITLE
Fix few typos in salt man page

### PR DESCRIPTION
**Pull request by onovy**
### What does this PR do?
Fixing few english typos in salt man page

### What issues does this PR fix or reference?
none

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by cachedout** [comment]
This page is compiled automatically. I don't believe these typos are present in the source code from which the man page is compiled.

**Comment by rallytime** [comment]
Hi @onovy - yes @cachedout is right that we compile the man pages automatically from the docs. Therefore, I am going to close this PR. If you see errors in the docs, please submit a change for those so the spelling errors can be corrected in the man pages. 

Thank you so much for contributing!

**Comment by onovy** [comment]
ok, fixed in docs:
https://github.com/saltstack/salt/pull/45607

And you should rebuild man pages, because there are more typos in man page, which are not in docs/source code. So it looks like mans are outdated.

Thanks.

**Comment by rallytime** [comment]
@onovy Thank you so much! Yes, we will be working on this now as we complete our next round of releases. :)

**Pull request closed without merging**
