### PR TITLE
Revising cron for OS agnostic support of cron when running non-root

### PR DESCRIPTION
**Pull request by madflojo**
### What does this PR do?

This pull request adds an OS agnostic approach to manage crontabs that adds the ability for Salt to manage crontabs when Salt is running as an unprivileged user (i.e. with `salt-ssh`).

### What issues does this PR fix or reference?

On RedHat systems the following is seen when Salt is running as a unprivileged user (via `salt-ssh`) and trying to manage a user's crontab.

```console
# salt-ssh 'salty' -i state.sls cron
salty:
----------
          ID: /bin/bash testing
    Function: cron.present
      Result: False
     Comment: Cron /bin/bash testing for user salty failed to commit with error 
              must be privileged to use -u
     Started: 21:53:57.649601
    Duration: 12.413 ms
     Changes:   

Summary for salty
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  12.413 ms
```

The reason this failed is because the **salty** target is a non-privileged user trying to manage it's own crontab on a RedHat system. RedHat Linux (at least RHEL v5) does not allow non-root users to specify the `-u` flag.

### Previous Behavior

Previously Salt was identifying if the minion is a Solaris or AIX system. If it was, it would run the `crontab` command as the target user without the `-u` flag.

```python
    appUser = __opts__['user']
    if __grains__.get('os_family') in ('Solaris', 'AIX') and appUser != user:
        return __salt__['cmd.retcode'](_get_cron_cmdstr(path, user),
                                       runas=user,
                                       python_shell=False) == 0
```
If the minion was not Solaris or AIX, it would run the `crontab` command with the `-u` flag as the `root` user.

```python
    else:
        return __salt__['cmd.retcode'](_get_cron_cmdstr(path, user),
                                       python_shell=False) == 0
```

With RedHat only the `root` user is allowed to specify the `-u` flag. As such this would fail (with the error message above) when running salt as a non-root user.

### New Behavior

Rather than checking a hard coded list of OS' that do not support the `-u` flag for the `crontab` command. I revised the cron module to always run the `crontab` command as the desired user.

```python
    return __salt__['cmd.retcode'](_get_cron_cmdstr(path, user),
                                   runas=user,
                                   python_shell=False) == 0
```

With the changes I've made, Salt will always run the `crontab` command as the specified user. The state will default the user to `root` if not specified, which is documented behavior today.

Using this method the `crontab` command will work on any system that supports cron. If Salt is unable to execute the `crontab` command as the specified user (from the state) than the execution will return an error to the end user.

While modifying the module, I found the `cron.file` state also required some revision. For this state, I modified the `file.manage_file`, `file.get_managed` and `file.check_managed` calls to use the specified user for `tmpfile`s that are created as part of the state. To do this I also added a statement to find the specified users group, if no group is found, an error is returned to the user and the state returns immediately.

### Tests written?

Yes - There are 3 new unit tests that mock the `__grains__.get('os_family')` return to verify Solaris, AIX and RedHat get `crontab /tmp` rather than `crontab -u user /tmp`.

### CODE REVIEW

**Comment by madflojo** [comment]
Fixing the conflict right now, looks like a new addition since I did a `fetch` this morning.

**Comment by madflojo** [comment]
Merge conflict fixed.

**Comment by cachedout** [comment]
@madflojo This looks great! Thanks also for the solid explanation that you've written in the PR. That's really helpful.

I'd like @anlutro to look at this before we merge it, since I know he did some work in this area of the crontab module a few months ago. It's a :+1: from me though.

**Comment by anlutro** [comment]
Any reason to do `salt.modules.useradd.info` instead of `__salt__['modules.useradd']` in the state?

**Comment by madflojo** [comment]
@cachedout thanks!

@anlutro when I first was working with the state I tried to use `__salt__['useradd.info']` but I would get a key error. After doing some reading, my guess is that's because the `useradd` module is not loaded by default.

I couldn't find any examples of someone loading a module into the `__salt__` object in the `modules` or `states` directories. I did however, find some examples of importing the modules.

If you have some suggestions on how to do that better I'm all ears.

**Comment by damon-atkins** [comment]
crontab -u fred is allowed even if user fred is in cron.deny on some OS.   This is why the code only treated Solaris and AIX differently.

**Comment by damon-atkins** [comment]
If salt is going to support many ways to run something,
-  either Salt runs in sudo mode
-  root
-  a particular user as per minion configuration
- or the user its running as
Then it would be good if salt testing runs all of these combinations.  (maybe if the root one success first)

**Comment by anlutro** [comment]
@madflojo sorry, replied too fast. It's `__salt['user.add']` as indicated [here](https://github.com/saltstack/salt/blob/develop/salt/modules/useradd.py#L31).

**Comment by madflojo** [comment]
@anlutro ah, now things make so much more sense. I've updated the PR with that change.

@damon-atkins I can see what you mean with `cron.deny` and since Salt today manages the crontab regardless of the user being in `cron.deny` it would be best to maintain that.

After looking through your steps I was thinking this approach would work and still keep it generic.

```python
    # Try as root
    ret = __salt__['cmd.retcode'](_get_cron_cmdstr(path, user),
                                   python_shell=False) == 0
    if ret:
        return ret
    else:
        # Try as user if root fails
        return __salt__['cmd.retcode'](_get_cron_cmdstr(path),
                                        runas=user,
                                        python_shell=False) == 0
```

Essentially, like you said try it as `root` first, if it doesn't succeed then try as the user. Thoughts?

**Comment by damon-atkins** [comment]
@madflojo   thats dangerous, could end up take roots crontab out and replacing it with one targeted at a user.  It needs a lot more logic to support the multiple options that salt can run.

**Comment by madflojo** [comment]
@damon-atkins do you mean in some cases crontab will assume the `-u` is a file? From what I can see Solaris returns an illegal usage error if `-u` is specified. I'll have a buddy check on AIX later this morning to see if it also returns an error when `-u` is added.

**Comment by madflojo** [comment]
@damon-atkins, Just had my buddy check on AIX and it also kicks back an error when `-u` is specified. Thinking about it though, if there ever were older versions that could run into this we could still keep the existing OS check in place for Solaris and AIX and retry for any other OS.

```python
    # Execute as root first
    if __grains__.get('os_family') not in ('Solaris', 'AIX'):
        ret = __salt__['cmd.run_all'](_get_cron_cmdstr(path, user),
                                       python_shell=False)
        if ret['retcode'] == 0:
            return ret

    # If failure, execute as user
    return __salt__['cmd.run_all'](_get_cron_cmdstr(path),
                                    runas=user,
                                    python_shell=False)
```

The above would keep the safety check as it is today but in instances where the `-u` is used and execution fails, it tries again as the specified user. This would allow for both root and non-root instances to manage user crontabs and still keep it somewhat simple.

It's essentially the same logic today with a second execution as the specified user if the first execution fails.

**Comment by madflojo** [comment]
@cachedout, What do you think of the proposed changes?

First, attempt to execute a `crontab -u user path` formatted command as the salt instance user. If that fails, attempt to run `crontab path` as the crontab owner. If the OS is Solaris or AIX, always run as the crontab owner.

This would achieve the goal of allowing an approach that works even if `-u` is not supported for unprivileged users. It also maintains the functionality of the `root` user being able to add crontabs even if the user is in `/etc/cron.deny`. The only catch is that it may mean attempting the `crontab` command twice.

**Comment by damon-atkins** [comment]
crontab cmd could fail for many reasons, e.g. user is in cron.deny, pam disallows it, different cron software, crontab is invalid, etc, or even command not found.

For example crontab -u may not be valid when run by a non-root user.

By using try then try again, you lose the error messages from the first try.  As a result the person running this may not be able to determine why it failed.  Its better code to know what to do and try once with confidence.

You seem to have removed the -u option, in the current commit. But it is in your comments above.

You raised this PR for
>Salt is running as an unprivileged user

However your solution does not allow for this.  The first step would be to check if you are root, and then check if the user id your are, is the target user.  

If you are not the user, you could use sudo to execute as root (I am ignoring Solaris Roles).  I think their is a flag for use of sudo.

Then their are the security issues, crontab needs to be pointed at the file and this file needs to be created in a way it can not be interfered with, between the time it is written and crontab reads it.  And then temp file removed.

I am not saying, the code can't be improved.

ping @sjorge

**Comment by madflojo** [comment]
@damon-atkins,

I didn't update the PR with earlier comments because I wanted to align on an approach before doing so.

Also I wasn't a huge fan of trying multiple times either, just at the time I didn't see an easy way of keeping it super simple. The goal I was aiming for was to remove OS specific logic and use a solution that works across the board. After thinking about some of the caveats I went back to the drawing board and approached it a different way.

Rather than removing the Solaris and AIX logic I left that in and defaulted them to always running as the desired user without a `-u`.

I also added a check to verify if the running instance is running as root or not as per your suggestion. However, I approached it differently. At the moment in order to check for the instance's running user the `__opt__` dictionary is used. Rather than using `__opt__` I used `os.geteuid()` to pull the instance user ID and check if it matches the target user ID. I did this by adding a new function.

```python
def _check_instance_uid_match(user):
    '''
    Returns true if running instance's UID matches the specified user UID
    '''
    return os.geteuid() == __salt__['file.user_to_uid'](user)
```

The reason I used `os.geteuid()` is because the `__opt__` dictionary is populated from the configuration files. When running the `salt-minion` agent as a non-privileged user that would be fine (assuming the configuration file was updated).

However, when using `salt-ssh`, the `__opt__` dictionary is pulled from the master's configuration file. This means with `salt-ssh` the `__opt__['user']` value will always reflect the `salt-master`'s user rather than the target systems running user.

The actual execution of the `crontab` command now looks like the following.

```python
    if _check_instance_uid_match(user) or __grains__.get('os_family') in ('Solaris', 'AIX'):
        return __salt__['cmd.retcode'](_get_cron_cmdstr(path),
                                       runas=user,
                                       python_shell=False) == 0
    else:
        return __salt__['cmd.retcode'](_get_cron_cmdstr(path, user),
                                       python_shell=False) == 0
```

The above will check if the Salt instance is running as the targeted user. If it is, the `crontab` command will not have the `-u` flag, and will be executed as the targeted user.

This works with both non-privileged and privileged instances of Salt. This is true even if the crontab is destined for the `root` user. As the command executed would simply be along the lines of `crontab -u root /tmp/foo`. 

Basically with the above, if Salt is running as root with the exception of Solaris and AIX the crontab command will be executed as root in the format of `crontab -u user path`. If Salt is not running as root, and the crontab user matches the user the Salt instance is running as, the format will be `crontab path` and be executed as that user.

In the event that a non-root instance is running and the target user is a different user, Salt will execute the `crontab` command in the format of `crontab -u user path` without attempting to use the `runas` key.

Now, in earlier comments you mentioned running the command as Sudo. I'm assuming that you mean the `sudo: True` flag within the `/etc/salt/roster` file with `salt-ssh`. When using the `sudo` flag with `salt-ssh` the entire thin client is executed as root. This means that an instance executed with `sudo` will follow the same path that a privileged instance would. Since that is the case there isn't a need to use `sudo` directly, though the `runas` option seems to use `sudo` if it is available.

I've updated the PR this time with the changes described and have included quite a few unit tests as well.

tagging: @cachedout to re-review since the approach is quite different from the original request.

**Comment by sjorge** [comment]
Solaris unfortunately is often different from Linux.

Like @damon-atkins mention I had a hard time getting this to work on both reliably also. I guess if it is easier we could separate this into two modules one for Linux and friends and one for Solaris and AIX.

Ping me once you are done, I'll drop the new code in my Solaris environment where I use it a lot, both for root and non-root crontabs so if something breaks we should notice it quickly.

**Comment by madflojo** [comment]
@sjorge this should be good to go at the moment. If you wanted to give it a run on Solaris.

**Comment by sjorge** [comment]
@madflojo doesn't seem to apply cleanly on current develop

```
[.]# patch -p1 < 37647.patch
patching file salt/modules/cron.py
patching file salt/states/cron.py
Hunk #2 succeeded at 512 (offset 40 lines).
Hunk #3 FAILED at 508.
Hunk #4 succeeded at 574 (offset 41 lines).
Hunk #5 succeeded at 602 (offset 41 lines).
Hunk #6 succeeded at 615 (offset 41 lines).
1 out of 6 hunks FAILED -- saving rejects to file salt/states/cron.py.rej
patching file tests/unit/modules/cron_test.py
patching file tests/unit/modules/cron_test.py
patching file salt/modules/cron.py
patching file tests/unit/modules/cron_test.py
patching file salt/states/cron.py
patching file salt/modules/cron.py
patching file tests/unit/modules/cron_test.py
patching file tests/unit/modules/cron_test.py
[isotope :: root][/workspace/salt]
[!]# cat salt/states/cron.py.rej
--- salt/states/cron.py
+++ salt/states/cron.py
@@ -508,7 +517,7 @@ def file(name,
         fcm = __salt__['file.check_managed'](cron_path,
                                              source,
                                              source_hash,
-                                             owner,
+                                             user,
                                              group,
                                              mode,
                                              template,
```

**Comment by madflojo** [comment]
Thanks @sjorge for giving it a go with Solaris.

**Comment by cachedout** [comment]
Last call for any feedback on this. If I don't hear by tomorrow, I'm going to go ahead and merge this. Thanks all.

**Comment by sjorge** [comment]
As mentioned above, all OK on Solaris.

**Comment by damon-atkins** [comment]
Had a quick look, seems ok

**Comment by cachedout** [comment]
Thanks, all.

@madflojo Sorry this took a bit to get in. Thanks for working with everybody to get this done. It will be an excellent improvement! Thank you.

**Comment by madflojo** [comment]
Thanks @cachedout! Glad to add support for those running non-root instances of Salt! Appreciate all of the great feedback on potential gotchas as well.

**Pull request merged**
