### PR TITLE
[master] Deprecate proxmox cloud

### LINKED ISSUE #64224: [TECH DEBT] Deprecate Proxmox Cloud Modules
### Description of the tech debt to be addressed, include links and screenshots

Deprecating all Proxmox functionality in Salt and moving it to: 
https://github.com/salt-extensions/saltext-proxmox

First Salt version with Proxmox no longer present in the core: 3008.0

See this PR for an idea of how to deprecate the Proxmox cloud modules:
https://github.com/saltstack/salt/pull/62184

### PR DESCRIPTION
**Pull request by I3urny**
### What does this PR do?
Deprecate proxmox cloud

### What issues does this PR fix or reference?
Fixes: #64224 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by Ch3LL — CHANGES_REQUESTED** [review]
https://docs.saltproject.io/en/latest/topics/development/deprecations.html

The version should be 3009. "A deprecation warning should be in place for at least two major releases"

**Comment by Ch3LL** [comment]
Looks like pre-commit is just failing

**Comment by Ch3LL** [comment]
Yes its required. Just ensure the changes are its own commit to make it easier to discern the pre-commit changes vs. your changes.

**Review by Ch3LL — CHANGES_REQUESTED** [review]

**Review by Ch3LL — DISMISSED** [review]

**Review by whytewolf — DISMISSED** [review]

**Comment by Ch3LL** [comment]
@I3urny thanks, Apologies for leading you astray there, just commit whatever pre-commit is suggesting. Also nice catch on preventing that error from showing up for everyone.

**Review by Ch3LL — DISMISSED** [review]

**Comment by garethgreenaway** [comment]
@I3urny Thanks for this PR and for taking over the maintainer-ship of these modules.  One quick note, I saw that you included a deprecation decorator specific to proxmox and included tests for that decorator.  I didn't want to make additional work for you, but we've added a global decorator (once https://github.com/saltstack/salt/pull/64569 is merged) that can be added into modules through the use of a dunder variable and doesn't require the decorator to be added to each function.  Once that is merged if you want to update your PR to use that decorator, if not then we can certainly merge this PR as is.  Thanks!

**Comment by garethgreenaway** [comment]
@I3urny Makes sense, perhaps the decorator needs an additional argument with a list of functions that it should ignore and not include the deprecation warning for.

**Review by garethgreenaway — DISMISSED** [review]

**Review by Ch3LL — DISMISSED** [review]

**Review by Ch3LL — APPROVED** [review]

**Comment by Ch3LL** [comment]
Yeah I can take it from here, I'll monitor this.

**Review by whytewolf — APPROVED** [review]

**Pull request merged**
