### PR TITLE
Add boto_asg.enter_standby and boto_asg.exit_standby

### PR DESCRIPTION
**Pull request by ticosax**
### What does this PR do?

Add new features to `boto_asg` execution module
### Tests written?

No, sorry.

### CODE REVIEW

**Comment by cachedout** [comment]
Just one lint issue here, please: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/2365/violations/file/salt/modules/boto_asg.py/

**Comment by ticosax** [comment]
@cachedout Thank you for the notification. I added `# noqa`. Unless you see something else ?

**Comment by cachedout** [comment]
@ticosax To disable the pylint check for that line, I think it needs to actually be `# pylint: disable=import-error`

**Comment by ticosax** [comment]
@cachedout got it, thanks.

**Pull request merged**
