### PR TITLE
Updates postgres returner to new api

### PR DESCRIPTION
**Pull request by kriberg**
### What does this PR do?

Updates the postgres returner to be feature compatible with the pgjsonb returner. Adopted some of the code from pgjsonb. 
- Updated full_ret columns to the table
- Adopted some of the code from the pgjsonb returner
- Added support for events
### What issues does this PR fix or reference?

No current issue listed for the postgres returner.
### Tests written?

No

### CODE REVIEW

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@kriberg Could you please address the lint issues shown here? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/2767/violations/file/salt/returners/postgres.py/

Thanks.

**Comment by kriberg** [comment]
My github fu might've gotten the better of me, but commited some changes to fix the linter issues. Changed the timestamping additionally.

**Comment by cachedout** [comment]
@kriberg Something went wrong with your last push. I'm going to close this PR and just have you please open a new one. Thanks.

**Pull request closed without merging**
