### PR TITLE
Pip module/state -- handle requirements chaining

### PR DESCRIPTION
**Pull request by gladiatr72**
With regards to #4648, #4805

Because #4832 and http://www.frankwiles.com/posts/saltstack-and-multiple-pip-requirements-files/

I love you guys, but the whole `no_chown` business makes me want to go sit around naked in a tree and fling poop at innocent passers-by.   

I figured this could be tackled in one of three ways:
- fix the docs 
- fix the error message
- fix the module function

I chose the box.

Let me know if you have questions/comments/etc.

### CODE REVIEW

**Comment by cachedout** [comment]
@gladiatr72 This all seems excellent. We do have a couple test failures and some lint issues to investigate though. Would you mind taking a look?

**Comment by gladiatr72** [comment]
@cachedout in progress!

**Comment by gladiatr72** [comment]
looks like someone might have forgotten to put coins in the Linode meter!

**Comment by cachedout** [comment]
Heh, yeah. It's looking like they've blacklisted us. We're working with them on it. :]

**Comment by gladiatr72** [comment]
This patch set provides:
* arbitrary support of chaining within requirements files. Currently uses a recursive call to process requirements chains.  Unless someone goes completely off the rails this won't be a problem.
* handles sequences of requirements files without breaking the existing functionality of accepting a comma-delimited string. 
* the `no_chown` option is still present--it just doesn't do anything.

This fleshes out the copy/chown/change user/execute that already existed.  Now, rather than just copying the root request file (provided to the exec module call) to a temp file and failing when `-r` is encountered, the file is copied to a temp directory and scanned for `-r` lines using the absolute path to the root file to derive the location of subsequent links in the chain. This continues til a requirements file is scanned that contains no additional `-r` directives. Each file is copied to the same location within the temp directory relative to its parent.  Once the chain is complete, control is returned to pip.install(). 

This fixes two deficiencies with using the `no_chown` option:
  1.  `no_chown` short circuits the protection from the real scenario where the specified `user` can't read the specified requirements file(s) in their original location. Creating a temporary directory and copying 1-n number of files adds insignificant overhead and provides consistent results to the state writer.
  2. unless someone is familiar with how the code works, `no_chown`, both in name and function is very unintuitive

**Comment by cachedout** [comment]
Looks good! Thanks for your hard work here, @gladiatr72

**Comment by ryan-lane** [comment]
Did you test this on a user squashed file system? In

**Comment by gladiatr72** [comment]
@ryan-lane I have not. What context are you using squashfs? All of this module's chowning bits take place in /tmp/tmpd[random] directories.  The biggest part of this change is extending the existing paradigm of copy/chown/execute to include any referenced/chained requirements files. 

So, yeah--is the squashfs volume a source or destination for pip?  If its the destination, I think the extension should smooth things out since file creation/writing will occur as the specified (non-salt) user. I haven't used squashfs directly, but from a couple quick search/skims,  the only problem I could see would be if someone were running the minion within the confines of a squashfs volume.  

If it's something along those lines that you've run into, I could definitely see adding a modules.pip.installed() arg that would take and pass a prefix for filetemp.mkdtemp(). That would allow for having a required states.mount.mounted state for mounting a tmpfs volume somewhere to use as a landing spot for the copy/chown/exec dance.

**Comment by ryan-lane** [comment]
The most usual place squashfs is used is volume mounts in vagrant for development. If I volume mount in a repo, generate a venv inside of it, then pip install into that venv, it could cause problems. It looks like your changes don't actively check to see if the chown succeeded or not, so it may be fine.

**Pull request merged**
