### PR TITLE
INFRA-3943 - Bug fix - too many volumes getting tagged

### PR DESCRIPTION
**Pull request by tkwilliams**
Previous code would ignore errors when converting instance_name to instance_id, which led to matching all volumes fitting the other filter criteria (or all volumes in the account, if no other filters were provided), which is a Bad Thing™.  Fixed to not apply the tags if parsing the filters fails.

Also added the option to pass in optional instance states to match against.  Defaults to the usual "running" states -- ('pending', 'rebooting', 'running', 'stopping', 'stopped')

Also a tiny bit of docstring cleanup.

### CODE REVIEW

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@tkwilliams Just some lint fixes please and then we'll be there. Thanks! https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/5039/violations/

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Lint didn't have any results on that last commit run, so let's rerun the tests...

**Comment by rallytime** [comment]
There is still a small lint error, but I can grab it really quickly.

**Comment by tkwilliams** [comment]
Cool, Thanks @rallytime  :)

**Comment by rallytime** [comment]
@tkwilliams Sure thing! Thanks for the fix.

**Pull request merged**
