### PR TITLE
Fix use of random shuffle and sample functions as Jinja filters

### PR DESCRIPTION
**Pull request by nicholasmhughes**
### What does this PR do?
See issue for details

### What issues does this PR fix or reference?
Fixes: #62372

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by nicholasmhughes** [comment]
@Ch3LL , will this get back-ported to master or do I need to get another PR in?

**Comment by nicholasmhughes** [comment]
re-run pr-centosstream-9-x86_64-py3-pytest

**Comment by whytewolf** [comment]
hey @nicholasmhughes we would rather not push more includes as a work around. if the functions are only meant as jinja filters they should be added/moved to salt/utils/jinja.py.

Also thank you for all the PR's you have been submitting.

**Comment by nicholasmhughes** [comment]
@whytewolf , near as I can tell this is the intended operation for including the decorator and not a workaround. As an example, the `salt.utils.network` module is imported in that file but not used at all.

**Comment by whytewolf** [comment]
@nicholasmhughes  I would be much more comfortable if the item being included in the render state wasn't coming from the modules. there are a couple of minor exceptions. modules that existed before utils was a thing like cmdmod and selinux. but overall importing from modules into utils is bad. 

Also. from the original discussion about the decorator it isn't working as expected. it shouldn't need to be imported directly if it was working right.

**Review by whytewolf — APPROVED** [review]

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
