### PR TITLE
virt state fixes

### PR DESCRIPTION
**Pull request by cbosdo**
### What does this PR do?

Fixes a number of tiny annoying issues preventing the `virt.pool_running` and `virt.network_running` states to be used.

Also fixes idempotency of `virt.running` state.

### What issues does this PR fix or reference?

One of the commits fixes issue #53107.
I was too lazy to write an issue for each of the other issues I fixed. Hopefully the commits messages are helpful enough to explain those.

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by cbosdo** [comment]
@rallytime could you have a look at this PR? Not sure if it's still OK for 2019.2.1

**Review by rallytime — APPROVED** [review]

**Review by cmcmarrow — APPROVED** [review]

**Comment by joesusecom** [comment]
Does this also fix the virt.stopped state? I've tested with two paused VMs, and the result should have been that they are stopped. But I get a result "False" with comment "No changes had happened" and Changes details that have an issue "Requested operation is not valid: domain is not running". Completely bogus and not idempotent at all. :-(

**Comment by joesusecom** [comment]
Same result if the VMs are fully stopped. This should just report green (nothing to do).

**Comment by cbosdo** [comment]
@joesusecom no that one is not fixed. I'll need to go over all the existing virt states to fix that and add support for the test parameter.

**Comment by cbosdo** [comment]
> Same result if the VMs are fully stopped. This should just report green (nothing to do).

Fixed in this PR now. The test parameter is not yet handled though.
I also rebased that PR against master branch.

**Comment by cbosdo** [comment]
Strange, there are a number of failing tests that aren't related to the PR.

**Review by dwoz — APPROVED** [review]

**Pull request merged**
