### PR TITLE
Add support for consul tokens

### PR DESCRIPTION
**Pull request by akissa**
### What does this PR do?

Adds support for tokens and fixes various bugs

Add support for consul tokens
- Tokens can now be set for servers that require auth

Fix event_fire

- Params were not sent correctly and payload was not included

Fix acl_list

- The id should not be required as this function is for listing all

Fix _query

- When the server returns a 401 response the error should be raised

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by garethgreenaway** [comment]
Seems to be a duplicate of #43406

**Comment by cachedout** [comment]
@akissa Did you see the comment above from @garethgreenaway ?

**Comment by akissa** [comment]
@cachedout Yes, i did. There are other fixes in the PR that are not covered by #43578. I am not sure what the way forward is, to wait for that to get merged then rebase on that ?

**Comment by cachedout** [comment]
@akissa Sure thing. That works for me if it works for you.

**Comment by akissa** [comment]
Works for me.

**Comment by garethgreenaway** [comment]
:+1:

**Comment by rallytime** [comment]
@akissa This PR has been submitted against `2016.11`, but since it is a feature addition, it should be submitted against `develop`.

I realize this contains similar code to #43406 as discussed above, but #43406 is against `develop`. Once #43406 is merged it, this PR should rebased against `develop` and submitted to `develop` as well.

**Comment by rallytime** [comment]
Hi @akissa - just checking in here. Did you see my comments above?

**Comment by akissa** [comment]
@rallytime You can close the pull request. I will maintain my changes outside. Develop using python >= 2.7 which i have no interest in for now.

**Comment by rallytime** [comment]
@akissa Ok, sounds good. If you do ever come back to this and are ready to fix this on `develop`, then please do open a new PR. We'd love to have the change. Thank you!

**Pull request closed without merging**
