### PR TITLE
New AWS SSM parameter module

### PR DESCRIPTION
**Pull request by mchugh19**
### What does this PR do?
Creates new module to set/get/put secrets in AWS SSM parameters
@blade2005 @rv-ptighe

### What issues does this PR fix or reference?
#46510

### New Behavior
```
# salt-call boto_ssm.put_parameter test-first test_value1 Type=SecureString KeyId=alias/aws/ssm Description='test encrypted key'
local
    1

# salt-call boto_ssm.get_parameter test-first withdecryption=True
local:
    test_value

# salt-call boto_ssm.delete_parameter test-first
local:
    True
```

### Tests written?
No

### Todo: 
 - tests
 - sdb?

### CODE REVIEW

**Review by gtmanfred — APPROVED** [review]
I would love to see this used to make an sdb module.

**Review by cachedout — APPROVED** [review]
LGTM

**Comment by rallytime** [comment]
@mchugh19 There's a merge conflict in the release notes file. Can you fix that up? Then we should be able to get this in. :)

**Comment by cachedout** [comment]
I went ahead and resolved the conflict and this is ready for merge.

**Pull request merged**
