### PR TITLE
Fixed the gem module to work on windows

### PR DESCRIPTION
**Pull request by twangboy**
Fixes issue: #21041

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @twangboy. Could you explain why this requires enabling a shell? Since this takes arbitrary arguments, this could have some undesired side-effects. Thanks.

**Comment by basepi** [comment]
The shell commands often include environment prefixes: `RBENV_VERSION=1.2.1 <the actual command>`. But just switching python_shell=True is not the answer, we need to also quote the command for security, using shlex or similar.

**Comment by basepi** [comment]
Go Go Jenkins!

**Comment by UtahDave** [comment]
@cachedout and @basepi the command would utterly fail without python_shell=True.

Do you have a better way to make that work?

**Comment by cachedout** [comment]
@UtahDave It depends what the real problem is. If it's a shell env that needs to be set, we can explicitely pass that into `cmd.run`. If it's something else, we may be able to handle this with pre-processing using `shlex` or similar as @basepi suggested.

**Comment by jfindlay** [comment]
@UtahDave, when I audited the windows modules, I quoted the user input and also verified that this did prevent shell injection in the same manner as for posix systems.

```python
try:
    from shlex import quote as _cmd_quote  # pylint: disable=E0611
except ImportError:
    from pipes import quote as _cmd_quote
...
def func(var):
    ...
    __salt__['cmd.run']('win_func {0}'.format(_cmd_quote(var)))
```

**Comment by jfindlay** [comment]
If it is a matter of providing environment variables, they can be passed to the command with `__salt__['cmd.run'](cmd, env={'RBENV_VERSION':rb_ver})`.

**Comment by basepi** [comment]
Yep, this needs explicit quoting or the separate `env=` from @jfindlay. As this pull request currently stands, it would result in a CVE, from shell injection vulnerability.

**Comment by cachedout** [comment]
I am going to close this PR as it represents a potential security flaw as it sits right now and I don't want it errantly merged. Please re-open when we have another approach. Thanks.

**Pull request closed without merging**
