### PR TITLE
Corrected documentation to state default keep_job param is set to 24 and not 0.

### PR DESCRIPTION
**Pull request by xeacott**
### What does this PR do?
This PR changes MySQL's documentation to state that the default setting for keep_job is in fact set to 24 and not to 0.

### What issues does this PR fix or reference?
This addresses #43409  

### Tests written?

No

### Commits signed with GPG?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by cachedout — APPROVED** [review]

**Review by dwoz — CHANGES_REQUESTED** [review]
@xeacott The linter and docs builds are unhappy with this change. Please have a look.

**Comment by xeacott** [comment]
@dwoz Looks like both lint and docs are failing 
16:18:52 Session docs raised exception UnicodeEncodeError('ascii', u'Corrected documentation to state default keep_job param is set to 24 \u2026', 69, 70, 'ordinal not in range(128)'), which is the triple dots in the title of the PR to continue the comment. I've never seen a doc fail for that reason, but would that be the case?

**Review by Ch3LL — APPROVED** [review]

**Review by Ch3LL — CHANGES_REQUESTED** [review]
just realized this is posted to the 2017.7 branch. Can you add this to the 2018.3 branch instead since >=2018.3 branches are the current branches.

**Comment by xeacott** [comment]
@Ch3LL Yes!

**Review by Ch3LL — APPROVED** [review]

**Review by dwoz — APPROVED** [review]

**Pull request merged**
