### PR TITLE
[master] Porting #53923 to master

### PR DESCRIPTION
**Pull request by garethgreenaway**
Porting #53923 to master

### CODE REVIEW

**Review by Ch3LL — APPROVED** [review]

**Comment by Ch3LL** [comment]
i believe this change is no longer needed due to this change https://github.com/saltstack/salt/pull/55101

is that correct @s0undt3ch

**Comment by Ch3LL** [comment]
oh nevermind, just need to resolve the conflict.

**Comment by s0undt3ch** [comment]
:+1:

**Comment by Ch3LL** [comment]
looks like the merge resolve ended up with no changes so will close.

**Comment by s0undt3ch** [comment]
But now there are no changes to commit, so this PR can actually be closed.

**Comment by s0undt3ch** [comment]
Heheheh, you beat me to it.

**Pull request closed without merging**
