### PR TITLE
Updated the boto_cfn.py to once again add the parameters and capabilitie...

### PR DESCRIPTION
**Pull request by polliard**
...s to the boto_cfn.create().  Fixed some indention and modified a few error/trace messages.

### CODE REVIEW

**Comment by jfindlay** [comment]
@polliard, there is a [lint error](https://jenkins.saltstack.com/job/salt-pr-lint-n/4060/violations/file/salt/modules/boto_cfn.py/).  You will need to replace `{}` with `None` to fix it and then later
```python
if not parameters:
    parameters = []
```
Thanks.

**Comment by tsaridas** [comment]
@jfindlay @polliard I made a complete PR for this module and state in the develop branch. Please check.

**Comment by thatch45** [comment]
@tsaridas what was the PR number?

**Comment by tsaridas** [comment]
#22347

**Comment by jfindlay** [comment]
@polliard, it seems that @tsaridas has already implemented these changes with some others in #22347.  Do you mind if we close this pull request?

**Comment by cachedout** [comment]
Closed for lack of response.

**Pull request closed without merging**
