### PR TITLE
consul_pillar support for limiting pillar exposure via minion targeting

### PR DESCRIPTION
**Pull request by rbjorklin**
### What does this PR do?
Adds the possibility to limit pillar exposure on the master via minion targeting. Should maintain full backwards compatibility.

### Previous Behavior
All minions always received all of the data available in consul.

### New Behavior
Optional minion targeting to limit the exposure of consul data.

### Tests written?
No

New attempt at pull request after aborting #37985

### CODE REVIEW

**Comment by cachedout** [comment]
@rbjorklin This is cool!

I would like to change this to go into develop. We like to keep all feature work there and restrict the release branches to bug fixes only. Do you mind if I change the base branch here?

**Comment by rbjorklin** [comment]
It's fine by me but that means I'll be monkey-patching this in after each 2016.11.X release for the next 6 months 😛

**Comment by cachedout** [comment]
@rbjorklin Thanks. I know it's a pain but sticking to this policy helps us out a lot. Much appreciated.

**Comment by rbjorklin** [comment]
Do I need to fix the conflict or will you take care of that?

**Comment by cachedout** [comment]
@rbjorklin If you could, then we'll know I didn't make a mistake in trying to parse your intention :] Otherwise, I will take care of it when I have a free moment. Much appreciated!

**Comment by damon-atkins** [comment]
Would have thought data leakage is a security issue? If I read this PR correctly.

**Comment by cachedout** [comment]
Grr. Something didn't work right with changing the base branch. We might need this totally rebased.

**Comment by rbjorklin** [comment]
@damon-atkins This is indeed a security issue and I would personally like for it to be merged into 2016.11 however this issue has been present ever since the consul_pillar was first introduced so one could argue it's also a new feature.

@cachedout If you can pass the final judgment I will follow up whatever you decide with a new PR.

**Comment by cachedout** [comment]
That's enough to convince me that we should get into 2016.11. I'll change the base branch back.

**Comment by cachedout** [comment]
@rbjorklin If you could fix up the lint issues outlined here then I will get this merged today. Thanks!

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/7225/violations/file/salt/pillar/consul_pillar.py/

**Comment by cachedout** [comment]
Merged. Apologies for the run-around there. Thanks for being patient. :]

**Pull request merged**
