### PR TITLE
Fix pyenv installation into the state.pyenv.install_pyenv

### LINKED ISSUE #37648: salt.states.pyenv.install_pyenv broken since at least 2015.8.8
### Description of Issue/Question

The `pyenv.install_pyenv` state [uses the wrong signature when calling `_check_and_install_python()`](https://github.com/saltstack/salt/blob/develop/salt/states/pyenv.py#L219), passing `user` in for the `python` arg. Since `user` defaults to `None`, this causes a fun-to-debug traceback when it later tries to run a regex search against `python`:

```
----------
          ID: install-pyenv
    Function: pyenv.install_pyenv
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1626, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1492, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/pyenv.py", line 215, in install_pyenv
                  return _check_and_install_python(ret, user)
                File "/usr/lib/python2.7/dist-packages/salt/states/pyenv.py", line 84, in _check_and_install_python
                  if __salt__['pyenv.install_python'](python, runas=user):
                File "/usr/lib/python2.7/dist-packages/salt/modules/pyenv.py", line 159, in install_python
                  python = re.sub(r'^python-', '', python)
                File "/usr/lib/python2.7/re.py", line 151, in sub
                  return _compile(pattern, flags).sub(repl, string, count)
              TypeError: expected string or buffer
     Started: 12:14:18.916348
    Duration: 2.586 ms
     Changes:   
```

### Setup

This state will adequately demonstrate the bug:

```
    pyenv-install:
      pyenv.install_pyenv
```

### Versions Report

```
$ salt --versions-report
Salt Version:
           Salt: 2015.8.8
 
Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.8.3
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-30-generic
         system: Ubuntu 14.04 trusty
```

We ran into the problem on a masterless VM.

/cc @ryanmrubin

### PR DESCRIPTION
**Pull request by bayaro**
I suggest to merge these changes to "develop" and to "2018.3" branches

### What does this PR do?
Add real request for pyenv installation inside then states.pyenv.install_pyenv

### What issues does this PR fix or reference?
Fixes #37648

### Previous Behavior
The function states.pyenv.install_pyenv just requested an installation of python with the username for pyenv instead of a real python version

### New Behavior
if pyenv is not installed the function requests the installation

### Tests written?
No

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by Ch3LL — COMMENTED** [review]
Can you add a regression test for this change? thanks

**Comment by bayaro** [comment]
> Can you add a regression test for this change? thanks

Hi Megan,
Unfortunately I know no how tests are formulated in this project no how to write them for this project.

**Comment by Ch3LL** [comment]
The test documentation is right here: https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html please let me know if i can help out

**Comment by bayaro** [comment]
> The test documentation is right here: https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html please let me know if i can help out

You are so nice. Thank you very much. I'm extremely appreciate it. I'll learn it when I have a time.

**Pull request closed without merging**
