### PR TITLE
Fix context clash.

### PR DESCRIPTION
**Pull request by garionphx**
### What does this PR do?

Fixes a context cache naming clash between utils/boto.py and utils/boto3.py
### What issues does this PR fix or reference?

Fixes an exception being thrown: AttributeError: 'EC2Connection' object has no attribute 'describe_route_tables'

I have a set of states that more or less builds an entire EC2/VPC environment from scratch. The mixing of boto and boto3 in modules/boto_vpc.py confused it.
### Previous Behavior

Would throw an exception if you happened to mix boto and boto3.
### Tests written?

[Edited] Yes. Added boto_test.BotoBoto3CacheContextCollisionTest.test_context_conflict_between_boto_and_boto3_utils

boto_vpc uses both boto and boto3. Both utils for those use the same name for their connection context. If you used states that required both boto and boto3, the get_conn would return the object.

### CODE REVIEW

**Comment by cachedout** [comment]
@garionphx Looks like some test failures here. Could you please take a look? Thanks.

**Comment by garionphx** [comment]
I looked at the failure. I ran it with and without my change, and its fails in both cases.

From the looks of it, something changed where it returning unexpected data in the "rules_egress" part of the secgroup response. Definitely an issue, but unrelated to this change.

If I get some time, I'll look more closely at that, and submit a patch for that separately.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by garionphx** [comment]
I added a unit test that duplicated my issue, and shows that its fixed with my change.

**Comment by garionphx** [comment]
Did more research into the failure.

Its failing because of a newer version of the moto library. It fails with moto 0.4.24, but passes on version 0.4.24 (which was release on May 02).

Should I change the test results, or should we open a ticket upstream?

**Comment by cachedout** [comment]
@garionphx Could you clean up the lint failures here, please? http://166.78.178.63:8080/job/PR/job/salt-pr-lint-n/1619/violations/file/tests/unit/utils/boto_test.py/

**Comment by cachedout** [comment]
I've asked @rallytime to please lint this and get it in. Thanks!

**Comment by rallytime** [comment]
These changes and commits were pulled into develop with PR #32985, so I'll close this. Thank you for fixing this and writing the test.

**Pull request closed without merging**
