### PR TITLE
Chocolatey - Lowered name of local and remote packages before comparing versions.

### PR DESCRIPTION
**Pull request by Kimol**
### What does this PR do?
Fixes issue #46150
### What issues does this PR fix or reference?
#46150

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by twangboy** [comment]
@Kimol So is the issue here that the `list_` function returns package names all in lowercase?

**Comment by Kimol** [comment]
@twangboy list_ returns original package names (camelcase in many cases). And the issue in function version() is that only the local package name is lowered (probably to provide case insensitivity). Remote package name is left without conversion, so in this function it's always comparing lowercase local package name with original remote package name. Which will only work when remote package name is originally also lowercase.

**Comment by twangboy** [comment]
yeah, I was going to suggest lowering the case of both.

**Review by twangboy — APPROVED** [review]

**Comment by twangboy** [comment]
Looks like the failing tests are unrelated

**Comment by rallytime** [comment]
Welcome @Kimol! Thanks for submitting this fix.

**Pull request merged**
