### PR TITLE
Add handling for client-side certs to http.query()

### PR DESCRIPTION
**Pull request by techhat**

### CODE REVIEW

**Comment by thatch45** [comment]
@techhat the lint errors look legit

**Comment by techhat** [comment]
@thatch45, fixed the missing import. The other lint error is likely because `context` doesn't show up in the `HTTPSHandler` until Python 2.7.9, which I'm guessing is not on the server. But SSLContext also doesn't show up in `ssl` until that version, so I thought it was a reasonable check. Should I use a different check, or pylint disable the error?

**Comment by thatch45** [comment]
We should disable the pylint error

**Comment by techhat** [comment]
@thatch45, done.

**Pull request merged**
