### PR TITLE
WIP - grafana2_datasource state

### PR DESCRIPTION
**Pull request by anlutro**

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @anlutro Looks like a number of lint errors here, mostly due to the mixing of spaces and tabs. Could you please have a look? Thanks.

**Comment by anlutro** [comment]
@cachedout oops, silly mistake - should be OK now.

**Comment by cachedout** [comment]
@anlutro Thanks for your quick response!

**Comment by cachedout** [comment]
Hi @anlutro. Just one more fixup needed and we'll have it. Please define `__virtualname__` before it's used in `__virtual__`. Thanks!

**Comment by anlutro** [comment]
Did it in the other pull request, forgot I had to do it here as well!

**Comment by cachedout** [comment]
Yup, saw that! No worries. After the tests finish we'll get this in. Thanks, @anlutro

**Pull request merged**
