### PR TITLE
adding states/boto_ec2 unit test case

### PR DESCRIPTION
**Pull request by jayeshka**
Implemented states/boto_ec2_test unit test case.

### CODE REVIEW

**Comment by jayeshka** [comment]
@jfindlay some how salt/states/boto_ec2.py modules is not present in 2015.2 branch.
But is present in develop branch. That is why the testcase if failing.

**Comment by jfindlay** [comment]
@jayeshka, this file was added after the 2015.2 branch was forked, so I resubmitted your pull request against develop in #22967.

**Comment by jayeshka** [comment]
Thank you @jfindlay 
This pull request can now be closed ?

**Comment by jfindlay** [comment]
@jayeshka, yes, thanks.

**Pull request closed without merging**
