### PR TITLE
TCP: Fix salt-master in bad state if remote side closed connection

### PR DESCRIPTION
**Pull request by skizunov**
### What does this PR do?

If the remote side closes the connection (which could happen if its own
timeout is hit due to the master taking too long to respond or if it
is shutting down), it puts the salt-master in a bad state where further
minions cannot connect to it. This fixes the issue by absorbing the
`StreamClosedError` exception so that
`TCPReqServerChannel.handle_message` doesn't leak any exceptions
which would put the salt-master in a bad state. Absorb other
exceptions as well just in case.

### Tests written?

No

### CODE REVIEW

**Comment by garethgreenaway** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@skizunov Can you please rebase this against the head of 2016.11? I'm not sure why these tests are failing. It's curious..

**Comment by skizunov** [comment]
@cachedout : I rebased it

**Comment by cachedout** [comment]
@skizunov Thanks very much. Let's see what the tests do this time. :]

**Comment by Ch3LL** [comment]
Go Go Jenkins!

**Pull request merged**
