### PR TITLE
Increase sleep time after stop minion command

### PR DESCRIPTION
**Pull request by Mapel88**
When installing windows with salt cloud, salt minion fails to start sporadically. 

### What does this PR do?
increase sleep time after stop minion command

### What issues does this PR fix or reference?
bug #53533

### Previous Behavior
Sometimes salt minion takes longer than 5 seconds to stop and therefore the start command fails with error:
```
[DEBUG   ] [SC] StartService FAILED 1056:

An instance of the service is already running.
```

### New Behavior
Hopefully salt-minion will be stopped in 10 sec.

### Tests written?
No

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by xeacott** [comment]
If this fixes, I'm okay with this change. For the future, adding optional argument to pass in something larger than 10 seconds may be necessary.

**Comment by xeacott** [comment]
re-run full all

**Review by xeacott — APPROVED** [review]

**Comment by waynew** [comment]
Would it make more sense to do an increasing (exponential?) backoff while waiting? e.g. check, then wait 1, 2, 4, 8s, and then finally fail?

**Review by Akm0d — APPROVED** [review]

**Review by waynew — CHANGES_REQUESTED** [review]
Hey @Mapel88, thanks for this PR! You may have noticed that we've been changing our development strategy to work off the `master` branch only, as well as requiring tests.

We also discussed this in our architecture meeting and came up with an alternate approach. The result of the discussion was that we should be able to check for the failures that you provided in the log, and there shouldn't be any harm in retrying the start command until it succeeds.

That is, the code should look something like this:

```
# stop minion here
started = False
while not started:
    try:
        # run start command
        started = True
    except SomeException as e:
        if '[SC] StartService FAILED 1056' in e.output:  # or, whatever
            time.sleep(1)  # one second should be plenty here
        else:
            six.reraise(e)


```

This is certainly not the *exact* code that we want, but it should be a helpful starting place. We want to test this too, namely:

- if the command run is successful, it doesn't get called twice
- if it's not successful, we keep trying until it is
- if a different error is raised, we appropriately re-rase it

Does that sound like something that you're interested in? If not, I'm sure we can figure out an alternate approach. Thanks!

It would also be good to have some tests confirming that it will continue to call the start command if the results contain

**Comment by Mapel88** [comment]
@waynew I already changed it to a while loop to validate service stopped properly before starting it in another PR, but no progress there... Waiting for approval.
Please see PR #54911

Thanks

**Comment by waynew** [comment]
@Mapel88 Looks like you'd probably want to close this PR, (and any other dupes) and edit that other PR to point against `master`. The same advice applies there, of course.

**Comment by Mapel88** [comment]
Closing this PR. Newer fix available at PR #54911

**Pull request closed without merging**
