### PR TITLE
Issue 24621 - AD/LDAP Group Auth Issue

### PR DESCRIPTION
**Pull request by TheScriptSage**
This is for https://github.com/saltstack/salt/issues/24621.

I -think- this will work.  I tested it locally and was able to authenticate and use pepper properly for people inside of the group but not people outside of it.  Tested on python2.6, I ran the unit.auth_test tests, not the whole thing as it appears the tests were failing due to unrelated issues.

I believe the tests need to be updated but I'm not sure how to go about adding them.  I'm not familiar enough with the codebase and wanted to submit this sooner rather than later.

Thanks for checking, sorry if I submitted this wrong.

### CODE REVIEW

**Comment by TheScriptSage** [comment]
I'm not sure what to do about these failed tests.  Anyone able to help?

**Comment by TheScriptSage** [comment]
I think these tests are failing for reasons that aren't related to my change.  What do you guys think?  I'll check back later tonight.  I'd like to get this approved.  Thanks.

**Comment by jfindlay** [comment]
@TheScriptSage, the CentOS 7 tests are busted.

**Comment by jfindlay** [comment]
@TheScriptSage, also please feel free to submit fixes directly to the oldest, supported release branch as they are regularly merged forward, see https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

**Comment by TheScriptSage** [comment]
Do you want me to find the oldest release branch that has the bug and submit a new pull request or are you guys going to backport this for me?

Thanks for looking into the test failures - I was looking at them for a while and figured it wasn't my change, but I wanted to at least do some checking.

**Comment by rallytime** [comment]
@TheScriptSage I've grabbed the back-port for you. :)

Thanks for the fix!

**Comment by TheScriptSage** [comment]
No problem, glad to help.  I'll try to keep that in mind next time I find a bug to find the oldest supported release branch.  Thanks guys!

**Comment by rallytime** [comment]
No problem! Thanks again!

**Comment by danlsgiga** [comment]
Unfortunately, group authentication using LDAP still doesn't work. If we set the LDAP username instead then it works fine.

**Pull request merged**
