### PR TITLE
Added Packet cloud driver

### PR DESCRIPTION
**Pull request by dominno**
Added Packet cloud driver

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @dominno This is great!

Could you please fix up these lint errors? Then we can likely get this merged. Thanks!

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/6658/violations/file/salt/cloud/clouds/packet.py/

**Comment by dominno** [comment]
@cachedout I fixed pylint errors please check

**Comment by rallytime** [comment]
@dominno Looks like there are a couple more pylint errors. Mind taking one more look? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/6691/violations/file/salt/cloud/clouds/packet.py/

**Comment by dominno** [comment]
@rallytime Fixed. Please check now

**Comment by rallytime** [comment]
Thanks @dominno!

**Pull request merged**
