### PR TITLE
Fix minion start retry on Windows (2016.3)

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?

Fixes problem where minion would try to connect to the master 7 times and then fail
### What issues does this PR fix or reference?

https://github.com/saltstack/salt/issues/33277
### Previous Behavior

Minion would try to connect to the master 7 times and then fail.
### New Behavior

Minion continues to try to connect to the master.... forever...
### Tests written?

No

### CODE REVIEW

**Comment by twangboy** [comment]
DO NOT MERGE....

**Comment by skizunov** [comment]
@twangboy : Looking at the code, I can't see how moving this code down:

```
minion = salt.cli.daemons.Minion()
minion.start()
```

Would change the behavior. Could you explain?

**Comment by skizunov** [comment]
@twangboy : Starting in 2016.3, there is a configuration way of fixing this issue. If you add this to the minion config file, it will work:

```
master_tries: -1
```

This is what my company does for this issue. It also works well when using multi-master since it will properly round-robin the various masters. One way of solving this issue is by making this the configuration default in `salt/conf/__init__.py`. That way, if the user wanted it to fail after 1 try, they can get the old behavior back by changing this setting in their configuration.

**Comment by twangboy** [comment]
@skizunov I implemented your fix. Thanks for the help!

**Comment by twangboy** [comment]
@cachedout This can now be merged when tests pass if you're good with it

**Comment by cachedout** [comment]
@twangboy Looking...

**Pull request merged**
