### PR TITLE
LVM module bugfixes

### PR DESCRIPTION
**Pull request by isbm**
Among other bugs, this PR also fixes the following issues:
https://groups.google.com/forum/#!topic/salt-users/u7q_f8SQz7g

### CODE REVIEW

**Comment by cachedout** [comment]
@isbm It looks like there are two failing tests here. Would you mind taking a look before we get this merged? Thanks!

**Comment by isbm** [comment]
@cachedout I have no idea why `cmd.run_all` fails with `Key not found`. :warning:

**Comment by cachedout** [comment]
@isbm Sounds good. Let us know what you find or if you have questions and if we can help in any way. Thanks!

**Comment by isbm** [comment]
@cachedout Let's see if this fixes the issue. I don't know what to do if the testcase cannot handle _correct_ calls (the other one with `__salt__['cmd.run_all']...`. That's somewhere bug in the testsuite, likely.

**Comment by cachedout** [comment]
@isbm Sounds good. We'll see what this test run says. Thanks!

**Comment by isbm** [comment]
@cachedout Any ideas why test does not likes `run_all`?

**Comment by jfindlay** [comment]
@isbm, I've created a [pull request](https://github.com/isbm/salt/pull/1) against your branch to fix the unit tests.  I only did the minimal amount of work to get the tests passing, but hopefully that is enough for you to understand the failures related to `cmd.run_all`.  Ideally we try to test each `raise` and `return` statement in the unit tests, see http://docs.saltstack.com/en/latest/topics/development/tests/unit.html.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by isbm** [comment]
@cachedout seems like the tests actually fixed (thanks to @jfindlay) but it is not yet clean. :cry:

**Comment by jfindlay** [comment]
@isbm, that seems to be some sort of infrastructure failure, you know, the cloud ... sigh.

**Pull request merged**
