### PR TITLE
rework salt.module.zpool

### PR DESCRIPTION
**Pull request by sjorge**
Part of #28779, the zpool module has been reworked to parse data where possible.
Missing feature were also implemented.

``` bash
/opt/local/salt/bin/salt-call --local zpool.status zones
```

``` yaml
local:
    ----------
    zones:
        ----------
        config:
            ----------
            zones:
                ----------
                cksum:
                    0
                mirror-0:
                    ----------
                    c2t0d0:
                        ----------
                        cksum:
                            0
                        read:
                            0
                        state:
                            ONLINE
                        write:
                            0
                    c2t1d0:
                        ----------
                        cksum:
                            0
                        read:
                            0
                        state:
                            ONLINE
                        write:
                            0
                    cksum:
                        0
                    read:
                        0
                    state:
                        ONLINE
                    write:
                        0
                read:
                    0
                state:
                    ONLINE
                write:
                    0
        errors:
            No known data errors
        scan:
            scrub repaired 0 in 0h5m with 0 errors on Mon Dec 14 02
        state:
            ONLINE
```

``` bash
/opt/local/salt/bin/salt-call --local zpool.iostat zones sample_time=60
```

``` yaml
local:
    ----------
    zones:
        ----------
        zones:
            ----------
            bandwith-read:
                0
            bandwith-write:
                690K
            capacity-alloc:
                42.7G
            capacity-free:
                68.3G
            mirror:
                ----------
                bandwith-read:
                    0
                bandwith-write:
                    690K
                c2t0d0:
                    ----------
                    bandwith-read:
                        0
                    bandwith-write:
                        692K
                    operations-read:
                        0
                    operations-write:
                        12
                c2t1d0:
                    ----------
                    bandwith-read:
                        0
                    bandwith-write:
                        692K
                    operations-read:
                        0
                    operations-write:
                        12
                capacity-alloc:
                    42.7G
                capacity-free:
                    68.3G
                operations-read:
                    0
                operations-write:
                    20
            operations-read:
                0
            operations-write:
                20
```

``` bash
/opt/local/salt/bin/salt-call --local zpool.detach test /tmp/disk2
```

``` yaml
local:
    ----------
    test:
        ----------
        detached:
            - /tmp/disk2
```

``` bash
/opt/local/salt/bin/salt-call --local zpool.attach test /tmp/disk1 /tmp/disk2 force=True
```

``` yaml
local:
    ----------
    test:
        ----------
        attached:
            - /tmp/disk2
```

``` bash
/opt/local/salt/bin/salt-call --local zpool.reguid test
```

``` yaml
local:
    ----------
    test:
        reguided
```

``` bash
/opt/local/salt/bin/salt-call --local zpool.reopen test
```

``` yaml
local:
    ----------
    test:
        reopened
```

``` bash
 /opt/local/salt/bin/salt-call --local zpool.get test readonly
```

``` yaml
local:
    ----------
    test:
        ----------
        readonly:
            off
```

``` bash
 /opt/local/salt/bin/salt-call --local zpool.get test
```

``` yaml
local:
    ----------
    test:
        ----------
        allocated:
            118K
        altroot:
            -
        autoexpand:
            off
        autoreplace:
            off
        bootfs:
            -
        cachefile:
            -
        capacity:
            0%
        comment:
            -
        dedupditto:
            0
        dedupratio:
            1.00x
        delegation:
            on
        expandsize:
            -
        failmode:
            wait
        feature@async_destroy:
            enabled
        feature@bookmarks:
            enabled
        feature@edonr:
            enabled
        feature@embedded_data:
            active
        feature@empty_bpobj:
            enabled
        feature@enabled_txg:
            active
        feature@extensible_dataset:
            enabled
        feature@filesystem_limits:
            enabled
        feature@hole_birth:
            active
        feature@large_blocks:
            enabled
        feature@lz4_compress:
            active
        feature@multi_vdev_crash_dump:
            enabled
        feature@sha512:
            enabled
        feature@skein:
            enabled
        feature@spacemap_histogram:
            active
        fragmentation:
            0%
        free:
            224M
        freeing:
            0
        guid:
            5784117219602689890
        health:
            ONLINE
        leaked:
            0
        listsnapshots:
            off
        readonly:
            off
        size:
            224M
        version:
            -
```

``` bash
/opt/local/salt/bin/salt-call --local zpool.set test comment 'hello world'
```

``` yaml
local:
    ----------
    test:
        ----------
        comment:
            'hello world'
```

``` bash
/opt/local/salt/bin/salt-call --local zpool.history test
```

``` yaml
local:
    ----------
    test:
        - 2015-12-20.19:34:07 zpool create -f test /tmp/disk0
        - 2015-12-20.19:52:52 zpool add -f test /tmp/disk1
        - 2015-12-20.19:54:37 zpool attach -f test /tmp/disk1 /tmp/disk2
        - 2015-12-20.19:54:48 zpool offline test /tmp/disk1
        - 2015-12-20.19:54:57 zpool online test /tmp/disk1
        - 2015-12-20.19:55:05 zpool online test /tmp/disk1 /tmp/disk0
        - 2015-12-20.20:01:05 zpool offline test /tmp/disk1
        - 2015-12-20.20:01:11 zpool offline test /tmp/disk1
        - 2015-12-20.20:12:47 zpool online test /tmp/disk1
        - 2015-12-20.20:16:32 zpool offline test /tmp/disk1
        - 2015-12-20.20:18:46 zpool online test /tmp/disk1
        - 2015-12-20.20:19:11 zpool reguid test
        - 2015-12-20.20:21:31 zpool reopen test
        - 2015-12-20.20:45:17 zpool set autoexpand=on test
        - 2015-12-20.20:45:28 zpool set autoexpand=off test
        - 2015-12-20.21:36:17 zpool detach test /tmp/disk2
        - 2015-12-20.21:38:12 zpool attach -f test /tmp/disk1 /tmp/disk2
        - 2015-12-20.21:38:29 zpool reguid test
        - 2015-12-20.21:38:54 zpool reopen test
        - 2015-12-20.21:41:28 zpool set comment=hello test
        - 2015-12-20.21:44:25 zpool set comment=hello world test
```

### CODE REVIEW

**Comment by cachedout** [comment]
Wow, nice work @sjorge !

I would like to give @nmadhok a chance to look at this as well, since a lot of this touches code that he wrote. 

In the meantime, there is a failing test. Could you take a look at that? Let me know if you need any help at all. Thanks!

**Comment by nmadhok** [comment]
@cachedout Looks good to me except for the failing test. I would also suggest updating the unit tests as well to work with the changes to the functions.

**Comment by sjorge** [comment]
I'll have a look at the failing test tomorrow.

**Comment by cachedout** [comment]
@sjorge and @nmadhok Thanks to you both! Much appreciated.

**Comment by sjorge** [comment]
Is there an easy way to run a unit test locally? Also what other unit tests use the zpool module? I only found zpool_test.py, which I hopefully fixed with the commit above.

**Comment by sjorge** [comment]
Done, hopefully the tests pass in jenkins too now.
They pass locally, I added tests for most functions that query information.

**Comment by cachedout** [comment]
Looks great! Thanks so much, @sjorge. Another excellent PR!

**Pull request merged**
