### PR TITLE
Refactoring cassandra module to use DataStax Python Driver

### PR DESCRIPTION
**Pull request by anitakrueger**
The cassandra module has been refactored to use the DataStax Python Driver.
The following functions were added to be able to manage keyspaces, users and permissions:
- list_keyspaces
- list_column_families
- keyspace_exists
- create_keyspace
- drop_keyspace
- list_users
- create_user
- list_permissions
- grant_permission

A state to manage keyspaces, users and permissions will follow.

### CODE REVIEW

**Comment by whiteinge** [comment]
Awesome!

**Comment by whiteinge** [comment]
@anitakrueger do you see value in submitting this alongside, instead of updating, the existing Cassandra execution module to preserve access to older non-cql Cassandra versions? I've been puzzling over this same question with an update to the Cassandra returner module. The idea being there will be two modules, `cassandra.py` and `cassandra_cql.py`. Salt will happily have both modules, but I don't know if that also makes sense from a Cassandra point-of-view.

**Comment by anitakrueger** [comment]
I had talked to @techhat about this a couple months ago and he said we might as well update if there is so much more functionality and it basically replaces all functions in the older module.

**Comment by anitakrueger** [comment]
Having said that, I am happy to submit it as cassandra_cql.py if you think that's the right thing to do.
I just looked at the current module again and this new one is missing functions like compactionstats or netstats.
I haven't used nodetool that much to be honest. In our environment we only use cqlsh.

**Comment by techhat** [comment]
@anitakrueger, I must defer to @whiteinge's judgement in this case; he has spent a lot of time in the Cassandra driver the last couple of months.

**Comment by whiteinge** [comment]
@anitakrueger do you have a sense of how common older, pre-CQL Cassandra installations are still out in the wild -- and whether any are likely to still fall under active support contracts? (I don't know the answer to that question.)

It may be best to play it safe and support both interfaces with two Cassandra modules for a year or two.

**Comment by thatch45** [comment]
@anitakrueger this is masterfully done, and I am sorry to change the verdict after @techhat gave advice, but I do think this should be in a separate module, changing module deps can pull the rug out from under people, we should be more explicit. So yes, we should make this a new module.

With that said, if you don't have time to do it I will be happy to try to split the code out for you, this is great stuff and we want it in!

**Comment by anitakrueger** [comment]
No worries at all. Was gonna do it yesterday and then my little boy needed all my attention :) I'll submit it as cassandra_cql.py.

**Comment by anitakrueger** [comment]
Sorry this took so long. New pull request is at https://github.com/saltstack/salt/pull/21766

**Pull request closed without merging**
