### PR TITLE
[DOC] Fix example for `defaults.merge` function

### PR DESCRIPTION
**Pull request by vutny**
### What does this PR do?
It corrects documentation for the `defaults` execution module.

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by vutny** [comment]
Hi @twangboy . This is a small correction of the docs, would you mind to take a look?
Thanks.

**Comment by vutny** [comment]
Does CI fail because of outdated KItchen config in `2018.3`?
```
Failed to complete #create action: [Neither image_id nor an image_search specified for instance py2-amazon-2! Please specify one or the other.]
```

**Review by twangboy — APPROVED** [review]

**Comment by vutny** [comment]
Wow, I already lost hope... :smiley:

**Comment by frogunder** [comment]
@vutny I see this PR is pointing to 2018.3, we do not merge PR's into that branch anymore.

Here is the SEP for that change https://github.com/saltstack/salt-enhancement-proposals/pull/20

Can you point it to master instead?

Thanks.

**Comment by vutny** [comment]
Alright, I decline this one and open new PR against `master`.

**Pull request closed without merging**
