### PR TITLE
Unset PYTHONHOME when starting the service

### PR DESCRIPTION
**Pull request by Sacro**
Bug https://github.com/saltstack/salt/issues/24238

### CODE REVIEW

**Comment by Sacro** [comment]
Bug https://github.com/saltstack/salt/issues/24238

**Comment by jfindlay** [comment]
@Sacro, thanks for the fix.  In the future, please feel free to submit fixes directly to the oldest supported release branch as they are regularly merged forward, see https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

**Comment by jfindlay** [comment]
@twangboy

**Comment by Sacro** [comment]
@jfindlay Ah sorry, want me to redo it against 2015.5? Should be exactly the same change anyway!

**Comment by jfindlay** [comment]
@Sacro, that would be great, thanks.

**Pull request closed without merging**
