### PR TITLE
Root dir prepend fix gh

### PR DESCRIPTION
**Pull request by alexbleotu**
### What issues does this PR fix or reference?

The PR fixes how the root_dir is prependend to relative paths. Also it fixes how the log_file path is derived when the log_dir override is set in the config file.

### Previous Behavior
The previous logic of prepending the root_dir to relative locations has a bug in which if the default root_dir (set in the code) is included in the overriden file locations (specified in the config file), the default root_dir segment is replaced by the the override root_dir, even if those paths should be skipped. Also the prepend logic is faulty when the default root_dir is included in the overriden root_dir.

Also, the default path assigned to the default log_file won't be overriden if the log_dir override is specified in the config file.

### New Behavior
The prepend and log_file bugs are fixed. The default log_file path is adjusted if the log_dir override is specified. The logic to prepend the root_dir (either the default one in code or the override in the config) is fixed. 

### Tests written?

Yes 

- test added to check that the prepend logic works correctly when the default root_dir is included in the override root_dir.
- fixed tests that didn't take into account the existence of the default root_dir override (in test_api)

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by alexbleotu** [comment]
I think the test jobs failed so they need a rerun

**Comment by alexbleotu** [comment]
@cro please have a look as well

**Comment by rallytime** [comment]
Go Go Jenkins!

**Review by cro — COMMENTED** [review]
Just waiting for the tests to pass--I am concerned about the excised chunk of code prefaced with the comment 'when running testsuite, salt.syspaths.ROOT_DIR is often empty'.

**Comment by cro** [comment]
Yeah, @alexbleotu, it looks like we still have some path inconsistencies re: the tests.  For example:

`AssertionError: '/var/log/salt/api' != '//var/log/salt/api'`

(note double //)

**Review by cro — CHANGES_REQUESTED** [review]
Have some path inconsistencies in the tests, e.g.

`AssertionError: '/var/log/salt/api' != '//var/log/salt/api'`

**Comment by alexbleotu** [comment]
I thought I fixed it. Will fix it fully when I get back, next Monday.

**Comment by cachedout** [comment]
@alexbleotu Thanks very much. We're looking forward to getting this one in!

**Comment by alexbleotu** [comment]
Almost there

**Comment by cachedout** [comment]
@cro Re-review requested.

**Comment by alexbleotu** [comment]
Ok fixing this test is not that easy and highlights a problem with the current logic in specifying default paths:

All the default paths in salt are absolute. The prepend logic currently has a hack, which I attempted to fix, but ended up failing the test (unfortunately it didn't run on my box because it was marked as destructive).

The current logic is that absolute paths are returned "as is", except if they happen to start with the default path (in this case `/var/tmp`) in which case the `root_dir` is prependend. This is a buggy, inconsistent logic in my opinion because it has unexpected effects if the users specify absolute overrides that contain the default path. 

I propose to change all defaults to relative, in which case the root_dir is prependend and the hack can be taken out; if the `root_dir` is not set, the file system root is prependend anyway. This will mimic exactly the existing logic.

@cro What do you think?

**Comment by alexbleotu** [comment]
Tried it, other tests fail... various modules assume that the config defaults are absolute. I will close this PR and open a new one that includes the hack but a few more checks

**Pull request closed without merging**
