### PR TITLE
Add function for matching key/value grains

### PR DESCRIPTION
**Pull request by ni3mm4nd**
### What does this PR do?
Add function for matching key/value grains.

### What issues does this PR fix or reference?
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.grains.html#module-salt.modules.grains

There is no function which can be used for matching key/value.

### New Behavior
```
[root@master ~]# salt salt-client-01 grains.equals fqdn salt-client-01
salt-client-01:
    True
[root@master ~]# salt salt-client-01 grains.equals systemd:version 219
salt-client-01:
    True
[root@master ~]# salt salt-client-01 grains.equals systemd:version 218
salt-client-01:
    False
```
### Tests written?

Yes

### CODE REVIEW

**Review by cachedout — COMMENTED** [review]
Would it make sense to shorten function name? I am wondering if it would make sense to do `grain.is` so you could do `grain.is foo bar`

Thoughts?

**Comment by ni3mm4nd** [comment]
Hello @cachedout . I have doubts that it will work. Seems like "is" is somehow reserved word. I've change it as you requested so you can take a look at the errors. 

What about ```grains.match```? Is it suitable for you?

**Comment by rallytime** [comment]
@ni3mm4nd Yes, you're right that `is` will not work as it is a reserved word. I think `grain.match` will work, or maybe even `grain.equals`?

**Comment by ni3mm4nd** [comment]
I'm gonna use ```equals``` as @rallytime suggested. Thanks! :-)

**Review by rallytime — APPROVED** [review]

**Pull request merged**
