### PR TITLE
Ignore ancestor processes when checking for concurrent states

### PR DESCRIPTION
**Pull request by bbh-kmd**
### What does this PR do?
Build list of ancestor processes, and check possible concurrent processes against this ancestor list. If a process is found as an ancestor, then we are probably running salt in a sudo setup, which sometimes require that a state be restarted with sudo, which makes it seem that there are multiple processes running the same state.

### What issues does this PR fix or reference?
Issue #50651 

### Previous Behavior
Only check if concurrent is True

### New Behavior
Create list of ancestral processes, then ignore processes that are in this list.

### Tests written?
No

### Commits signed with GPG?
No

### CODE REVIEW

**Review by DmitryKuzmenko — APPROVED** [review]
I'm okay with this PR just not sure what's happening with the tests. I updated it to develop branch, let's see how tests will pass.

**Comment by terminalmage** [comment]
@DmitryKuzmenko I found the problem. `ppid` is a function, it needs to be invoked to get the PID. Otherwise, you're just passing a function reference.

I pushed a commit to this PR to fix it.

**Comment by DmitryKuzmenko** [comment]
@terminalmage you're awesome you know it? =)

**Comment by terminalmage** [comment]
Actually it looks like I need to add one more commit. Seems that pre-2.0 versions of psutil have most of the functions as simple attributes. @bbh-kmd likely developed this on psutil < 2.0.

**Comment by bbh-kmd** [comment]
The one installed on the system used is the one that comes with an SLES12sp3 (python-psutil-1.2.1-15.3.3), so I think you're right in your assumption about versions of the psutil, and it's just a bit behind on enterprise versions of various Linux distributions. I thought it was psutil_compat that overrode default behaviour, but as I don't know much about python, I may be wrong in that regard.

**Comment by bbh-kmd** [comment]
Hmm... I don't know much about windows, but if a process list on Windows  doesn't end with 0 or 1 as the final originating ancestral process, it might be that the loop tries to continue past the last process in the chain. I don't know what that would result in. Does windows even hava a psutil module?

Is it possible to test for empty as well as 0 and 1 in Python? 

Or, according to stacktrace, it hits a "NoSuchProcess", which to my untrained mind seem to indicate that the chain has stopped, or the process has been removed before we look it up. That would mean no more ancestor processes, and we have thus reached the end of the process line on Windows. I don't know exactly where the exception occur.

If it's in the line just before the try-except, then we might try to catch the "NoSuchProcess" and set init_found = True at that point and then continue (skips rest of loop, right?).

I'm not sure how that would look, but probably something like the following:

...
while not init_found:
   try:
      cur_ppid = psutil.Process(cur_pid).ppid
   except psutil.NoSuchProcess:
      init_found = True
      continue
   try:
      ...

Sanity check, please.

**Comment by dwoz** [comment]
@bbh-kmd We are no longer accepting PRs to the `develop` branch. This needs to be re-opened against the `master` branch. You can link to this PR from the new one to preserve any disscussion history. Sorry for the confusion.

**Pull request closed without merging**
