### PR TITLE
INFRA-856 - Expand handling of block_device_map in boto_ec2.run() to …

### PR DESCRIPTION
**Pull request by tkwilliams**
- Expand handling of block_device_map in boto_ec2.run() to accept string and dict representations of device mappings.
- Add boto_ec2.get_all_volumes()
- Add boto_ec2.create_tags()
- Add boto_ec2.detach_volume()
- Add boto_ec2.delete_volume()
- Add state function boto_ec2.volume_absent().

### CODE REVIEW

**Comment by rallytime** [comment]
Very nice. Thanks @tkwilliams!

**Comment by tkwilliams** [comment]
@rallytime - Is the above jenkins error spurious or is it somehow related to my PR?  I'm not clear on what my change might have broken in netapi.tornado :)

**Comment by rallytime** [comment]
@tkwilliams Correct - that test is not related to your change. It's on QA's list of things to clean up and make more stable. Thanks again for the PR!

**Comment by tkwilliams** [comment]
Oh, sweet!  Thanks @rallytime  :)

**Pull request merged**
