### PR TITLE
add support to enc and dec passwords in pillar

### PR DESCRIPTION
**Pull request by steverweber**
add support to enc and dec passwords in pillar

### CODE REVIEW

**Comment by steverweber** [comment]
yap that will most diffidently fail lint

**Comment by steverweber** [comment]
I find this module more helpful vs the pgp render... Simple for others using the salt system to understand and use, work well with git repo diffs.

**Comment by steverweber** [comment]
need to update the docs in the file and a few other things ... but thought i would get some feedback befor spending to much time.

**Comment by steverweber** [comment]
meh... im going to redue this module and support RSA keys.

**Comment by thatch45** [comment]
@steverweber please take a look at libnacl:
https://libnacl.readthedocs.org/en/latest/

It is much easier and safer to use then the OpenSSL libs and a RAET dep so we make sure it is packaged

**Comment by steverweber** [comment]
I'll do that. Thanks.

**Comment by steverweber** [comment]
libnacl dosen't seem to be installed on any of my systems, salt is not including it as a dependency.

it only seems to be used once.  That is in the class RaetKey
https://github.com/saltstack/salt/search?utf8=%E2%9C%93&q=libnacl
this call to gen_key would mostly fail on my system...

thoughts?

**Comment by thatch45** [comment]
Right, libnacl is a salt raet dep, so it is available and an easy install, I am fine with supporting either but libnacl is just a lot easier and safer to use, so we would still prefer using it

**Comment by steverweber** [comment]
libnacl is in that commit.

**Comment by steverweber** [comment]
i'll spend some time cleaning up the docs.

**Pull request closed without merging**
