### PR TITLE
Add grains/minion_process.py - grains describing the minion process

### PR DESCRIPTION
**Pull request by plastikos**
- UID
- username
- GID
- groupname
- PID

### CODE REVIEW

**Comment by cachedout** [comment]
@plastikos There are some lint errors here. Would you mind having a look?

**Comment by cachedout** [comment]
@plastikos I think that `integration.shell.call.CallTest.test_issue_15074_output_file_append` might also be failing because of this PR. Probably just needs a quick adjustment to the test. If you wouldn't mind having a look at that, then we can get this merged in today. Thanks.

**Comment by plastikos** [comment]
@cachedout, I'll check it out - thanks.

**Comment by plastikos** [comment]
Ahhh, it dumps the grains - but the minion PID changes with each new minion process. I'll need to tweak something.

**Comment by cachedout** [comment]
Cool. We're good to go. Thanks, @plastikos . This is great!

**Pull request merged**
