### PR TITLE
Set changed = true if the file has changed when using file.copy state

### PR DESCRIPTION
**Pull request by cetra3**
Fix for issue #24295

### CODE REVIEW

**Comment by jfindlay** [comment]
@cetra3, thanks for the fix.  In the future, please feel free to submit fixes directly to the oldest supported release branch as they are regularly merged forward, see https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

**Comment by jfindlay** [comment]
@cetra3, actually I think the fix needed here is
```python
            if hash1 == hash2:
                changed = False
```

**Comment by cetra3** [comment]
@jfindlay Thanks,

I agree that maybe it should be `hash1 == hash2`

I still think a test should be written for this to prevent regressions.

**Comment by jfindlay** [comment]
@cetra3, good point, thanks.

**Pull request merged**
