### PR TITLE
#27998 Cleanup pkgin isatty mess

### PR DESCRIPTION
**Pull request by papertigers**
This is a fix for issue #27998

### CODE REVIEW

**Comment by jfindlay** [comment]
@papertigers, thanks for the fix.  In the future you are welcome to submit fixes directly to the oldest supported release branch, see https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

**Comment by papertigers** [comment]
@jfindlay thanks for the heads up, and yea this does need to be in older releases.  So, sorry about that!

**Comment by jfindlay** [comment]
@papertigers, no problem.  There are a few [lint errors](https://jenkins.saltstack.com/job/salt-pr-lint-n/10035/violations/file/salt/modules/pkgin.py/).

**Comment by papertigers** [comment]
I *think* I fixed the lint issues.  Jenkins is running now, so I guess we will know shortly.

**Pull request merged**
