### PR TITLE
Improve Key.gen_keys() method to be more flexible

### PR DESCRIPTION
**Pull request by moises-silva**
### What does this PR do?

Improve Key.gen_keys() method to be more flexible and have better defaults
- Allow passing extra keyword arguments to tweak the key generation
  process through the API without requiring special options to be
  present in the minion configuration options.
- Default the key generation directory to pki_dir when gen_keys_dir
  is not provided rather than failing with a KeyError exception.
- Default the keyname to 'minion' if no gen_keys option was provided.
- Return the fingerprint of the generated pub key.

Generating keys for a minion programatically with the default minion
configuration can now be done simply doing:

from salt.config import minion_config
from salt.key import Key

Key(minion_config(None)).gen_keys()

This will return the generated key fingerprint.
### Previous Behavior

Previously the gen_keys() method would rely completely on the options dictionary to be populated with some gen_keys options that are not set by default in minion configurations, which makes it a bit quirky to use as an API from the minion side (perhaps same applies to the master, have not checked that).
### New Behavior

Backwards compatibility is kept for the most part. The only change that I see as a bit intrusive is that now I attempt to return the generated key fingerprint.
### Tests written?

No, but I ran the unit test suite and worked. Let me know if I should submit this with a unit test and I'll look into what's needed for that.

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @moises-silva 

Thanks for this! Looks like the linter has one complaint. If you could take a look at that then once you've updated the PR, I'll do a full review and get this merged. This should be great! Thanks.

http://166.78.178.63:8080/job/PR/job/salt-pr-lint-n/837/violations/file/salt/key.py/

**Comment by moises-silva** [comment]
@cachedout Sorry about that. I've adjusted that.

I've run the linter now locally with the same args as the jenkins job and looks good now. The issue stemmed from the fact that the RaetKey class inherits from Key, but the gen_keys() method really has a different interface as it doesn't generate a pair of PKI keys AFAICS. I've tried to adjust the interface to make it as similar as possible, but, for example, can't return a fingerprint for the pub key because RaetKey.gen_keys() doesn't generate a pub key.

**Comment by cachedout** [comment]
@moises-silva Yup, looks great. Thanks very much for the quick response and your excellent work here.

**Comment by moises-silva** [comment]
@cachedout On the contrary! thanks for the great work on salt and the quick turn around to merge this.

**Comment by cachedout** [comment]
@moises-silva Very kind. :] Thank you!

**Pull request merged**
