### PR TITLE
Feat/boto describe default vpc

### PR DESCRIPTION
**Pull request by major0**
### What does this PR do?
Allow looking up the default AWS VPC which is automatically created at account creation time.

### Previous Behavior
Previously the `boto_vpc` module only allowed looking up a VPC via the `vpc_id` or the `vpc_name`. The default VPC does not have a `vpc_name` and as such it is not possible to look it up.

### New Behavior
If neither the `vpc_id` nor the `vpc_name` are supplied to `boto_vpc.describe()` then it will describe the default VPC.

The following functions were modified to make this possible:
- `_find_vpcs()`
- `describe()`

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [X] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by Akm0d — DISMISSED** [review]

**Comment by major0** [comment]
I am curious if it wouldn't be better to simply lookup the default vpc if no vpc_id and no vpc_name are specified.

**Comment by major0** [comment]
Reworked the PR to modify fewer functions by allowing the calling of `boto_vpc.describe` w/out a `vpc_id` or `vpc_name`.  This required a minor rework to `_find_vpcs()` to support this, and replaces the `check_vpc()` call with `_find_vpcs()` in `boto_vpc.describe()`.  This also avoids problems with other uses of `check_vpc()` in which we do not want to return the default VPC is no id/name is specified.

**Review by Akm0d — DISMISSED** [review]

**Comment by Akm0d** [comment]
Thanks for the PR!  Once there's a test for the changes we can merge.  A unit test should do the trick.

**Comment by major0** [comment]
I have updated the test case, but while I was doing so I discovered that none of the VPC tests are running.

From the code:
```
@skipIf(
    sys.version_info > (3, 6),
    "Disabled for 3.7+ pending https://github.com/spulec/moto/issues/1706.",
)
class BotoVpcTestCase(BotoVpcTestCaseBase, BotoVpcTestCaseMixin):
```

**Comment by major0** [comment]
I suppose it is worth pointing out that a number of individual tests in `tests/unit/modules/test_boto_vpc.py` have likely never been operational:
```
SKIPPED [100] .nox/pytest-parametrized-3-crypto-none-transport-zeromq-coverage-false/lib/python3.8/site-packages/_pytest/unittest.py:126: Disabled for 3.7+ pending https://github.com/spulec/moto/issues/1706.
SKIPPED [1] tests/unit/modules/test_boto_vpc.py:1264: Moto has not implemented this feature. Skipping for now.
SKIPPED [1] tests/unit/modules/test_boto_vpc.py:1247: Moto has not implemented this feature. Skipping for now.
SKIPPED [1] tests/unit/modules/test_boto_vpc.py:1233: Moto has not implemented this feature. Skipping for now.
SKIPPED [1] tests/unit/modules/test_boto_vpc.py:2062: Moto has not implemented this feature. Skipping for now.
SKIPPED [1] tests/unit/modules/test_boto_vpc.py:2080: Moto has not implemented this feature. Skipping for now.
SKIPPED [1] tests/unit/modules/test_boto_vpc.py:2097: Moto has not implemented this feature. Skipping for now.
SKIPPED [1] tests/unit/modules/test_boto_vpc.py:2048: Disabled pending https://github.com/spulec/moto/issues/493
SKIPPED [1] tests/unit/modules/test_boto_vpc.py:2134: Moto has not implemented this feature. Skipping for now.
SKIPPED [1] tests/unit/modules/test_boto_vpc.py:1972: Moto has not implemented this feature. Skipping for now.
SKIPPED [1] tests/unit/modules/test_boto_vpc.py:1956: Moto has not implemented this feature. Skipping for now.
SKIPPED [1] tests/unit/modules/test_boto_vpc.py:2151: Moto has not implemented this feature. Skipping for now.
SKIPPED [1] tests/unit/modules/test_boto_vpc.py:2003: Moto has not implemented this feature. Skipping for now.
SKIPPED [1] tests/unit/modules/test_boto_vpc.py:2165: Moto has not implemented this feature. Skipping for now.
SKIPPED [1] tests/unit/modules/test_boto_vpc.py:1986: Moto has not implemented this feature. Skipping for now.
SKIPPED [1] tests/unit/modules/test_boto_vpc.py:2182: Moto has not implemented this feature. Skipping for now.
SKIPPED [1] tests/unit/modules/test_boto_vpc.py:2114: Moto has not implemented this feature. Skipping for now.
SKIPPED [1] tests/unit/modules/test_boto_vpc.py:2196: Moto has not implemented this feature. Skipping for now.
SKIPPED [1] tests/unit/modules/test_boto_vpc.py:2213: Moto has not implemented this feature. Skipping for now.
SKIPPED [1] tests/unit/modules/test_boto_vpc.py:2034: Moto has not implemented this feature. Skipping for now.
SKIPPED [1] tests/unit/modules/test_boto_vpc.py:2017: Moto has not implemented this feature. Skipping for now.
```

**Comment by major0** [comment]
According to the linked issue (https://github.com/spulec/moto/issues/1706), this problem should have been resolved in `moto`, so I have re-enabled the VPC tests and made certain they all pass on my local system.

**Comment by major0** [comment]
I have created a new PR to re-enable a large swath of boto unit tests: https://github.com/saltstack/salt/pull/58660

**Review by Akm0d — APPROVED** [review]

**Pull request merged**
