### PR TITLE
Start upgrading codebase to Py3 for every changed file

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
Starts upgrading the codebase to Py3 for every changed file by running [`pyupgrade`](https://github.com/asottile/pyupgrade) against it.
We only do this for each changed file and not the whole code base to avoid MASSIVE code churn.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
The pipeline changes worked, see https://jenkinsci.saltstack.com/job/pr-pre-commit/job/PR-57936/1/console

**Comment by s0undt3ch** [comment]
This PR only "works" as expected once https://github.com/saltstack/salt-jenkins-pipeline-libs/pull/33 is merged

**Review by waynew — APPROVED** [review]
Does this mean that everyone who submits code will be running pyupgrade as part of their PR?

**Comment by s0undt3ch** [comment]
If they have pre-commit configured, yes, for the files they change, only those.
It's either that or we do it ourselves in one go.

**Comment by s0undt3ch** [comment]
To the whole codebase.

**Review by waynew — APPROVED** [review]

**Pull request merged**
