### PR TITLE
Req channel singletons

### PR DESCRIPTION
**Pull request by jacksontj**
Reduces the number of sockets we create/destroy :)

### CODE REVIEW

**Comment by cachedout** [comment]
I was actually going to ask you about this very thing today and you beat me to it. :] Sweet!

**Comment by jacksontj** [comment]
Hmm, something is up with this guy, the integration tests aren't working, but the unittests are... I'll have to look some more

**Comment by jacksontj** [comment]
I think this is another case where the test harnesses are getting in the way ;) I have some ideas on how to make this work, I'll get back to it tomorrow :)

**Comment by cachedout** [comment]
How are we looking here @jacksontj?

**Comment by jacksontj** [comment]
Haven't had a chance to look yet, I should be able to take a look tomorrow
morning.

**Comment by cachedout** [comment]
@jacksontj No worries, just checking in. Thanks!

**Comment by jacksontj** [comment]
That should fix it ;)

**Comment by jfindlay** [comment]
@jacksontj, @cachedout, is this pull request ready to go?

**Comment by jacksontj** [comment]
Yea, should be good to merge :) The test failure looks unrelated.

**Comment by cachedout** [comment]
This appears to be the cause of filehandle leaks inside LocalClient. Normally, of course, these are not a problem in Salt CLI commands but they are causing the test suite to run out of filehandles and could be problematic for anybody using LocalClient programatically. At present, this is blocking the release of 2015.8.

A test to illustrate the issue is as follows:

```
import os
import salt.config
import salt.runner

o = salt.config.master_config('/etc/salt/master')
r = salt.runner.RunnerClient(o)
pre_h = len(os.listdir('/proc/%d/fd' % os.getpid()))

print('Open handles BEFORE command: {0}'.format(pre_h))

r.low('manage.up', {})

post_h = len(os.listdir('/proc/%d/fd' % os.getpid()))

print('Open handles AFTER command: {0}'.format(post_h))
print('Leaked handles: {0}'.format(post_h - pre_h))
````

**Comment by jacksontj** [comment]
@cachedout I'm still catching up (was on vacation for a couple weeks), These leaks seem to be resolved by your other PR #26757 right?

**Comment by cachedout** [comment]
Thus far, yes. (And welcome back from vacation!) :]

**Pull request merged**
