### PR TITLE
Fix master crash on ctl-c for long-running job

### LINKED ISSUE #34439: Fast memory leak on ctrl-c out of  salt '*' state.highstate
### Description of Issue/Question
I run state.highstate and ctrl-c out. There are hosts that are in the list, but down. So they take time to time out. When I ctrl-c memory usage of one of the salt-master processes starts to shoot up very fast, and will out of memory the box.

### Versions Report
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 6.0.1
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.11+ (default, Apr 17 2016, 14:00:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-28-generic
         system: Linux
        version: Ubuntu 16.04 xenial

### PR DESCRIPTION
**Pull request by cachedout**
This was causing events to loop into the reactor, spiking CPU and leaking memory.

Fixes #34439

### CODE REVIEW

**Comment by rallytime** [comment]
@cachedout Just a tiny [lint error](https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/3105/violations/file/salt/utils/event.py/). :)

**Comment by ahammond** [comment]
I think I've seen this or similar to this a number of times.

**Comment by cachedout** [comment]
@ahammond I wouldn't be surprised. The loop is spinning and chews through memory as fast as the CPU can malloc it.

**Comment by cachedout** [comment]
@rallytime Thanks. Fixed.

**Comment by edgan** [comment]
Confirmed, that fixes it for me.

**Pull request merged**
