### PR TITLE
Support empty repositories in git.latest

### LINKED ISSUE #26809: git.latest and empty repositories
Currently, it's not possible to have a `git.latest` pointing towards an empty repository. This was possible in 2015.5 and earlier.

The code that triggers the error: https://github.com/saltstack/salt/blob/f0c9dff9bf74c8a988ad1c60c77a8877166b2eb4/salt/states/git.py#L514-L521

An easy(?) fix could be to add an `allow_empty` argument to the state.

Ping @terminalmage

### PR DESCRIPTION
**Pull request by terminalmage**
Fixes #26809.

### CODE REVIEW

**Comment by jfindlay** [comment]
@terminalmage, just some [lint](https://jenkins.saltstack.com/job/salt-pr-lint-n/8962/violations/file/salt/states/git.py/).

**Comment by terminalmage** [comment]
Lint fix pushed.

**Comment by anlutro** [comment]
Tested on my end, works great! :+1:

**Comment by terminalmage** [comment]
Thanks @anlutro for continuing to test and find these issues. This was a pretty complex rewrite, and as much as I tried to maintain backwards compatibility there are some things I have missed. You've been invaluable at helping to find these issues so we can make the git.latest state as awesome as possible in 2015.8.0.

**Pull request merged**
