### PR TITLE
Keystore abstraction

### PR DESCRIPTION
**Pull request by felskrone**
Currently salt stores its keys on the salt-master in the pki-directories. In Mutlimaster-(PKI)-Modes, that requires a shared keystore over all salt-masters to have the keystore always in sync. A shared-storage for multiple servers adds a lot of complexity and also requires even more complex failover-strategies for desaster-scenarios.
A keystore abstracted from the salt-master-service and implemented (for example) in a redis-database would make such a setup a lot easier. 

This is a first approach to abstract the keystore from the master itself and make it more modular. The goal is to have various keystores like redis, mysql, etc. while still keeping the default local file-keystore for zeromq and raet (which could of course also be moved to a keystore-module). 

While this PR only extends salt-key to query a sample mysql-keystore-module, the salt-master would of course also be extended to query the same keystore for auth-requests, etc. 

This is not intended as a real PR yet. Its more a request for comments, if this is something that would be welcomed by the salt-developers and if the approach is in a way thats acceptable.

### CODE REVIEW

**Comment by felskrone** [comment]
@thatch45 has anyone else taken a shot at this yet? I would be willing to, unless its already being worked on by someone else.

**Comment by cachedout** [comment]
I am not aware of current work in this area unless @jacksontj has something cooking in his secret kitchen. ;]

(@felskrone, I'm fairly certain you should be good to go ahead and start working on this. It should be awesome!)

**Comment by jacksontj** [comment]
I believe @thatch45 was working on something similar, but not quite the same. We will need something similar at least once I finish up my transport overhaul ;)

**Comment by felskrone** [comment]
@cachedout @jacksontj @thatch45 
Alright, here we go with the very first implementation of a mysql-keystore.

https://github.com/felskrone/salt/blob/mysql_keystore/salt/keystores/mysql_keystore.py

While not complete, it shows what im trying to do here with mimicing(?) the behaviour of salt.key.Key.

The goal is, that it can be used as a drop-in replacement for the filesystem keystore once finished. There would be no changes necessary within salt itself besides having a logic within salt.key that decides, what keystore to query o course.

Questions:
For now i dont see a reason to not have a flat table for the minions in mysql. Am i forgetting something here?

Todos:
translate globbing/PCRE to SQL-Queries properly (=~in queries)
implement dict_match()
implement finger*()
support RAET-keys

Am i missing something thats obvious?

Let me know what you think, just keep in mind that it is at its very early stages and i just want to make sure, we're on the same page as to what we are trying to achieve here :-)

**Comment by cachedout** [comment]
This direction looks solid to me. Well done, Volker.

**Comment by felskrone** [comment]
Anyone else care to share their opinion? I can take a -1's :-)

**Comment by jacksontj** [comment]
The concept is okay, but the module interface is a bit clunky. Since the Key object is a class it does seem weird that the module only implements methods (meaning it has no access to class attributes). I'd suggest either making the modules subclass *or* pass an instance of some shared keyclass to these functions.

**Pull request closed without merging**
