### PR TITLE
Fix GlusterFS module for version 4.0 and above

### PR DESCRIPTION
**Pull request by Martin819**
### What does this PR do?
Fix for versions of GlusterFS 4.0 and above. In the GlusterFS module, there are conditions checking the version of GFS lower than 3.6, because it uses different syntax to parse the response. Unfortunately, the condition on checks minor version, so when running a version 4.0, it fails, because 0 < 6 = true. 

### What issues does this PR fix or reference?
Fixed by changing the condition to compare both minor and major versions.

### Previous Behavior
Failed to parse the response causing the state to fail.

```ID: glusterfs_peers
    Function: glusterfs.peered
        Name: 172.16.10.93
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1905, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1830, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/glusterfs.py", line 84, in peered
                  peers = __salt__['glusterfs.peer_status']()
                File "/usr/lib/python2.7/dist-packages/salt/modules/glusterfs.py", line 162, in peer_status
                  root = _gluster_xml('peer status')
                File "/usr/lib/python2.7/dist-packages/salt/modules/glusterfs.py", line 86, in _gluster_xml
                  raise CommandExecutionError('\n'.join(result.splitlines()[:-1]))
              CommandExecutionError: peer status
              gluster> peer status
              <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
              <cliOutput>
                <opRet>0</opRet>
                <opErrno>0</opErrno>
                <opErrstr/>
                <peerStatus>
                   <peer>
                    <uuid>28df4ec7-066d-411a-8025-62f6389175aa</uuid>
                    <hostname>172.16.10.92</hostname>
                    <hostnames>
                      <hostname>172.16.10.92</hostname>
                    </hostnames>
                    <connected>1</connected>
                    <state>3</state>
                    <stateStr>Peer in Cluster</stateStr>
                  </peer>
                </peerStatus>
              </cliOutput>
     Started: 15:31:27.224687
    Duration: 488.657 ms
```
### New Behavior
State successfully finished.

```----------
          ID: glusterfs_peers
    Function: glusterfs.peered
        Name: 172.16.10.93
      Result: True
     Comment: Host 172.16.10.93 successfully peered
     Started: 08:10:31.702237
    Duration: 647.8 ms
     Changes:   
              ----------
              new:
                  ----------
                  28df4ec7-066d-411a-8025-62f6389175aa:
                      ----------
                      connected:
                          1
                      hostnames:
                          - 172.16.10.92
                      state:
                          3
                      stateStr:
                          Peer in Cluster
                  7688e4c0-2eab-402f-90cb-dc52dc306d30:
                      ----------
                      connected:
                          1
                      hostnames:
                          - 172.16.10.93
                      state:
                          4
                      stateStr:
                          Accepted peer request
              old:
                  ----------
                  28df4ec7-066d-411a-8025-62f6389175aa:
                      ----------
                      connected:
                          1
                      hostnames:
                          - 172.16.10.92
                      state:
                          3
                      stateStr:
                          Peer in Cluster
```

### CODE REVIEW

**Comment by rallytime** [comment]
Hi @Martin819 - This is failing some tests. Can you take a look?

unit.modules.test_glusterfs.GlusterfsTestCase.test_add_volume_bricks
unit.modules.test_glusterfs.GlusterfsTestCase.test_create_volume
unit.modules.test_glusterfs.GlusterfsTestCase.test_delete_volume
unit.modules.test_glusterfs.GlusterfsTestCase.test_get_max_op_version
unit.modules.test_glusterfs.GlusterfsTestCase.test_get_op_version
unit.modules.test_glusterfs.GlusterfsTestCase.test_list_volumes
unit.modules.test_glusterfs.GlusterfsTestCase.test_peer
unit.modules.test_glusterfs.GlusterfsTestCase.test_peer_status
unit.modules.test_glusterfs.GlusterfsTestCase.test_set_op_version
unit.modules.test_glusterfs.GlusterfsTestCase.test_start_volume
unit.modules.test_glusterfs.GlusterfsTestCase.test_status
unit.modules.test_glusterfs.GlusterfsTestCase.test_stop_volume
unit.modules.test_glusterfs.GlusterfsTestCase.test_volume_info

https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-cent7-py3/5912/#showFailuresLink

**Comment by Martin819** [comment]
@rallytime Hi, thanks for pinging me about it. 
It was a stupid mistake. Should be fixed now.

**Review by rallytime — APPROVED** [review]
Thanks @Martin819 for submitting this.

**Comment by rallytime** [comment]
Hi @Martin819 - There's just one more glusterfs test failure that needs to be fixed.

- unit.modules.test_glusterfs.GlusterfsTestCase.test_get_max_op_version

https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/23969/

**Comment by Martin819** [comment]
@rallytime This should be fixed now by updating the test case. It uses mocked version so I had to adjust it to the new format.

**Comment by Martin819** [comment]
@rallytime
Thanks for merging. Do you think this could be backported to 2017.7?

**Comment by rallytime** [comment]
Yeah, for sure.

**Comment by rallytime** [comment]
Hi @Martin819 - It looks like this module has diverged in develop from the earlier branches and this won't back-port cleanly. If you'd like this fix to be in 2017.7, then you'll need to make a separate fix against that branch. Would you mind submitting that?

**Comment by Martin819** [comment]
Hi @rallytime I can do that for sure.

**Pull request merged**
