### PR TITLE
DOCS: Update link to Doug Hellman's blog entry on dictionary initalization performance in Salt Coding Style guide

### LINKED ISSUE #59650: [DOCS] Link to Doug Hellmann's blog in Salt Coding Style guide is broken
**Description**
The link to Doug Hellmann's blog entry on The Performance Impact of Using dict() Instead of {} in CPython 2.7 is broken in the Salt Coding Style guide

**Suggested Fix**
Update link to https://doughellmann.com/posts/the-performance-impact-of-using-dict-instead-of-in-cpython-2-7-2/

**Type of documentation**
Salt Coding Style guide

**Location or format of documentation**
https://docs.saltproject.io/en/latest/topics/development/conventions/style.html#dictionaries

**Additional context**

### PR DESCRIPTION
**Pull request by ggiesen**
### What does this PR do?
Fixes link to Doug Hellmann's blog in the Salt Coding Style guide.

### What issues does this PR fix or reference?
Fixes: #59650

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by krionbsd — APPROVED** [review]

**Comment by ggiesen** [comment]
re-run pr-ubuntu1804-py3-pytest

**Comment by ggiesen** [comment]
re-run pr-ubuntu1604-py3-pytest

**Comment by ggiesen** [comment]
re-run pr-amazon2-py3-pytest
re-run pr-centos8-py3-pytest

**Comment by ggiesen** [comment]
re-run pr-opensuse15-py3-pytest

**Review by ScriptAutomate — APPROVED** [review]

**Review by Ch3LL — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Pull request merged**
