### PR TITLE
[PR port] Port #54047 -  auth: correct typos in docstrings

### PR DESCRIPTION
**Pull request by piterpunk**
PR port #54047
- [X] Docs

### CODE REVIEW

**Comment by krionbsd** [comment]
re-run all

**Comment by piterpunk** [comment]
@dwoz which kind of test case should be provided? The original PR had only two or three typos to fix, the changes in code are related to lint, black and removing the py2 support and did automatically.

**Review by krionbsd — DISMISSED** [review]

**Comment by waynew** [comment]
Went ahead and rebased/pushed changes here. This is only a docs change so as long as docs build is :+1: it should be good to go.

**Review by barbaricyawps — DISMISSED** [review]
@piterpunk , looks good to me! Approved.

**Comment by Ch3LL** [comment]
@piterpunk doc only changes do not require changelogs. I went ahead and removed. Everything else looks good and i'll merge when doc tests pass

**Review by Ch3LL — APPROVED** [review]

**Review by barbaricyawps — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Pull request merged**
