### PR TITLE
Refactor publish func in master/masterapi to use check_authentication

### LINKED ISSUE #6420: Differentiate between permissions and authentication failure
If the user has successfully authenticated and the token is still valid, raise an authorization exception not an authentication exception. The authorization exception is a subclass of the authentication exception so no salt code has to change but the salt-api can detect the difference.

### PR DESCRIPTION
**Pull request by rallytime**
### What does this PR do?
Refactors the `publish` function in `master.py` and `masterapi.py` to use `salt.auth.check_authentication` and reworks the publish function in each file to be more concise.

In a previous PR, the `runner` and `wheel` functions in `master.py` and `masterapi.py` were refactored to reduce common code via the `salt.auth.check_authentication` method.

The `publish` function also can utilize the `check_authentication` function in `master.py` and `masterapi.py`.

Consolidation of this code will help us be able to differentiate between `authorization` and `authentication` errors in the future.

### What issues does this PR fix or reference?
Builds on the work done in PR #43203.

This is necessary to fix (eventually) #6420, #34750, and #35160.

### Tests written?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by rallytime** [comment]
Ah, this isn't _quite_ right. I need to look at this a little bit more.

**Comment by rallytime** [comment]
Ok, this should be ready to review now, pending tests.

**Review by thatch45 — APPROVED** [review]
This looks good!

**Comment by rallytime** [comment]
re-run py3

**Comment by rallytime** [comment]
re-run py3

**Review by terminalmage — APPROVED** [review]

**Comment by rallytime** [comment]
re-run py3

**Review by DmitryKuzmenko — APPROVED** [review]
I like this approach!

**Comment by rallytime** [comment]
Test failures are not related.

**Review by cachedout — APPROVED** [review]

**Comment by cachedout** [comment]
re-run py3

**Comment by keesbos** [comment]
See salt/scripts.py:
```
salt/scripts.py:

86 def salt_master():
87     '''
88     Start the salt master.
89     '''
90      import salt.cli.daemons
91      master = salt.cli.daemons.Master()
92      master.start()
```
This is the normal flow (salt.minion effectively imported at line 92):
```
  File "/usr/local/src/tests/develop/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/scripts.py", line 92, in salt_master
    master.start()
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/cli/daemons.py", line 205, in start
    super(Master, self).start()
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/utils/parsers.py", line 1044, in start
    self.prepare()
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/cli/daemons.py", line 185, in prepare
    import salt.master
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/master.py", line 52, in <module>
    import salt.pillar
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/pillar/__init__.py", line 21, in <module>
    import salt.minion
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/minion.py", line 115, in <module>
```

This is the wrong flow (salt.minion effectively imported at line 90):
```
  File "/usr/local/src/tests/develop/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/scripts.py", line 90, in salt_master
    import salt.cli.daemons
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/cli/daemons.py", line 48, in <module>
    import salt.utils.parsers
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/utils/parsers.py", line 28, in <module>
    import salt.config as config
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/config/__init__.py", line 100, in <module>
    _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/config/__init__.py", line 90, in _gather_buffer_space
    import salt.grains.core
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/grains/core.py", line 46, in <module>
    import salt.utils.dns
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/utils/dns.py", line 31, in <module>
    import salt.modules.cmdmod
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 34, in <module>
    import salt.utils.templates
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/utils/templates.py", line 41, in <module>
    import salt.utils.jinja
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/utils/jinja.py", line 30, in <module>
    import salt.fileclient
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/fileclient.py", line 21, in <module>
    import salt.client
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/client/__init__.py", line 39, in <module>
    import salt.utils.minions
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/utils/minions.py", line 23, in <module>
    import salt.auth.ldap
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/auth/__init__.py", line 32, in <module>
    import salt.utils.master
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/utils/master.py", line 21, in <module>
    import salt.pillar
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/pillar/__init__.py", line 21, in <module>
    import salt.minion
  File "/usr/local/src/tests/develop/local/lib/python2.7/site-packages/salt/minion.py", line 115, in <module>
    from salt.config import DEFAULT_MINION_OPTS
ImportError: cannot import name DEFAULT_MINION_OPTS
```

Delayed import of `salt.utils.master` to just before `auth_list = salt.utils.master.get_values_of_matching_keys` (only place where `salt.utils.master` is used) will fix this. But I'm not sure that that's the right way to go.

**Comment by rallytime** [comment]
@keesbos Thanks for adding that information. I think you're on the right track. I will dig into this more right now and submit a fix.

**Comment by rallytime** [comment]
@keesbos You're absolutely right that we need to move that import down. There was already a "late import" declaration in the original code, but I missed it during the refactor. I've moved this back down in PR #44445. Thanks again for your help.

**Pull request merged**
