### PR TITLE
Fix EC2 volume creation logic

### PR DESCRIPTION
**Pull request by clarkperkins**
Currently, you can't create a volume from a snapshot and also specify the type, so it defaults to a standard magnetic disk.  This PR allows you to specify other types so that you can create an SSD volume from a snapshot.  It also lets you set `iops` and `encrypted` from a snapshot, too.

I also made a change will give a better error message than `KeyError` if you don't specify `volume_id`, `snapshot`, or `size`.

### CODE REVIEW

**Comment by techhat** [comment]
+1

**Comment by clarkperkins** [comment]
Also want to make sure this gets in the develop branch for releases outside of 2015.8

**Comment by rallytime** [comment]
@clarkperkins This functionality will be added to the develop branch on the next merge-forward (after this PR in merged). Can you also add some documentation about how to use this functionality? The best place would probably be on this page: https://docs.saltstack.com/en/latest/topics/cloud/aws.html, which you can find in `salt/doc/topics/cloud/aws.rst`.

**Comment by clarkperkins** [comment]
@rallytime I can do that, but it should be noted that this PR doesn't add new functionality.  I just fixed an issue that wouldn't let you use existing functionality in certain situations.

**Comment by rallytime** [comment]
@clarkperkins Oh, you're right! There's an example already in there. I just wasn't reading carefully. Sorry about that. Thank you for fixing this.

**Comment by clarkperkins** [comment]
@rallytime no worries!  I went ahead and added more explanation about the extra params.

**Comment by rallytime** [comment]
Awesome! Thank you!

**Pull request merged**
