### PR TITLE
Replace option 'i' with an explicit queryformat

### PR DESCRIPTION
**Pull request by redmcg**
Option 'i' uses a predefined queryformat that is not necessarily compatible with the code used to parse it.

For example: an exception was being thrown on my CentOS 6.7 machines because the default queryformat was placing multiple keys on a signle line.

I have therefore replaced the 'i' option with a hardcoded queryformat to ensure consistancy across all systems.

### CODE REVIEW

**Comment by redmcg** [comment]
This is related to issue #28075 which I've only just raised. With this code I now get the expected result.

**Comment by cachedout** [comment]
@terminalmage Could you please have a look here?

**Comment by terminalmage** [comment]
Why all the use of "27" in the format strings?

**Comment by terminalmage** [comment]
Please remove the padding, there's no use for it here.

**Comment by terminalmage** [comment]
Also, thanks very much for this, I had identified this a couple weeks ago and had a fix in-progress when my laptop died. This saves me some work, though it might need further tweaks after we get this merged.

**Comment by redmcg** [comment]
"Please remove the padding" - this has been done in 07413ec162bf233449b0b8ce11cbd924ceb5270f. I copy and pasted the string from the RPM code (to minimise impact as much as possible) but I had overlooked this padding (which is no longer required with every value on its own line).

**Comment by terminalmage** [comment]
Thanks!

**Pull request merged**
