### PR TITLE
fix sorting by latest version when called with an attribute

### PR DESCRIPTION
**Pull request by mcalmer**
### What does this PR do?

Fix a bug.
### What issues does this PR fix or reference?

Fix ensure installed latest in case it is called with an attribute list.
Additionally it sort by EVR (called edition).
### Tests written?

No

### CODE REVIEW

**Comment by mcalmer** [comment]
Follow up for https://github.com/saltstack/salt/pull/32243

**Comment by cachedout** [comment]
Have asked @terminalmage to help with this review. Also, @isbm this might be something you have an opinion on.

**Comment by isbm** [comment]
@cachedout This is a correct patch, since RPM will cut off `version`, once `pkg.info_installed` is called with only specific parameters, where no `version` is passed.

**Comment by cachedout** [comment]
@isbm Thank you very much for the quick response. I will wait for @terminalmage to comment as well and then hopefully merge this.

**Pull request merged**
