### PR TITLE
Fix pkgrepo.managed PPA handling for newer Ubuntu versions

### LINKED ISSUE #59065: [BUG] pkgrepo.managed fails to configure ppa on Ubuntu 20.10
**Description**
After upgrade to Ubuntu 20.10, I can't setup my ppa repositories. Running high.state fails with error:
```
          ID: ppa keepassxc
    Function: pkgrepo.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2153, in call
                  ret = self.states[cdata["full"]](
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2087, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/pkgrepo.py", line 396, in managed
                  pre = __salt__["pkg.get_repo"](repo=repo, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/modules/aptpkg.py", line 1735, in get_repo
                  repo = softwareproperties.ppa.PPAShortcutHandler(repo).expand(
              AttributeError: 'PPAShortcutHandler' object has no attribute 'expand'
     Started: 09:03:34.633592
    Duration: 1068.175 ms
```
Looks, like changes in `python3-software-properties` break salt.

**Setup**
I'm using masterless salt configuration.

sls that fails to run:

```
ppa keepassxc:
  pkgrepo.managed:
    - ppa: phoerious/keepassxc
```

**Steps to Reproduce the behavior**
1. set sls to configure ppa with `pkgrepo.managed`
2. run high.state

**Expected behavior**
ppa is properly configured.

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: 4.1.0
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.8.6 (default, Sep 25 2020, 09:36:53)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: ubuntu 20.10 groovy
         locale: utf-8
        machine: x86_64
        release: 5.8.0-29-lowlatency
         system: Linux
        version: Ubuntu 20.10 groovy
```
</details>

<details><summary>python3-software-properties version</summary>

```
||/ Name                        Version
+++-===================================
ii  python3-software-properties 0.99.3 
```
</details>

**Additional context**
Salt installed from official Ubuntu 20.10 packages. Problem also exists on latest 3002.2 provided from saltstack repositories.

### PR DESCRIPTION
**Pull request by theblazehen**
### What does this PR do?

Fixed PPA handling in newer Ubuntu versions with patch provided in https://github.com/saltstack/salt/issues/59065#issuecomment-1118112165

### What issues does this PR fix or reference?
Fixes: #59065 

### Previous Behavior
It would fail to manage PPA repos

### New Behavior
It now handles PPA repos

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by whytewolf** [comment]
so, I'm wondering about onedir here. as onedir will not have access to softwareproperties. your code doesn't touch anything that doesn't have softwareproperties. so while this will work in a pip installed environment. if there anything that needs to be changed in the other side of the if statmnts that check if HAS_SOFTWAREPROPERTIES

**Comment by chielboogaard** [comment]
Would love to get the PR merged because we are running in to the issue and cannot deploy ppa packages.

**Comment by whytewolf** [comment]
> Would love to get the PR merged because we are running in to the issue and cannot deploy ppa packages.

with the question i brought up in is unknown if this will fix the issue with onedir based installs. the user also needs to add tests and a changelog.  so this is very unlikely to get merged in it's current state.

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
