### PR TITLE
[master] Drop Python 3.7 support.

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Same cloud test failures as seen on the master branch

https://jenkins.saltproject.io/job/pr-centosstream-9-x86_64-py3-cloud-pytest/job/master/409

**Review by twangboy — APPROVED** [review]

**Review by dmurphy18 — APPROVED** [review]

**Review by Ch3LL — COMMENTED** [review]
I think it would be relevant to add a changelog and a note to the release notes that python 3.7 is no longer supported in 3007.0. I'm okay if you want to do this in a follow up PR as well.

**Comment by s0undt3ch** [comment]
> I think it would be relevant to add a changelog and a note to the release notes that python 3.7 is no longer supported in 3007.0. I'm okay if you want to do this in a follow up PR as well.

Since this is already passing and has 3 review, yeah, I'll submit it separately.

**Comment by s0undt3ch** [comment]
> > I think it would be relevant to add a changelog and a note to the release notes that python 3.7 is no longer supported in 3007.0. I'm okay if you want to do this in a follow up PR as well.
> 
> Since this is already passing and has 3 review, yeah, I'll submit it separately.

Wait, only 2, not 3. But a separate PR will save build time

**Review by dmurphy18 — COMMENTED** [review]
does this line in noxfile.py
```
_PYTHON_VERSIONS = ("3", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10")
``` 
need to change

**Review by Ch3LL — APPROVED** [review]

**Comment by s0undt3ch** [comment]
@dmurphy18 will submit the issue you flagged when I also submit the changelog.

Merging.

**Comment by s0undt3ch** [comment]
https://github.com/saltstack/salt/pull/64424

**Pull request merged**
