### PR TITLE
[3006.x] Fix for Nightly build Package test report failures

### PR DESCRIPTION
**Pull request by dmurphy18**
### What does this PR do?
Resolves Windows Package Test failures in Test Reports on the Nightly Build.
Also seen occasional failures on Linux package test report too.

### What issues does this PR fix or reference?
Fixes Windows Package Test failures in Test Reports on the Nightly Build

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices, including the
[PR Guidelines](https://docs.saltproject.io/en/master/topics/development/pull_requests.html).

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by twangboy — DISMISSED** [review]

**Review by twangboy — DISMISSED** [review]
It's interesting that the step right before it is also a randomized sleep of sorts

**Review by twangboy — DISMISSED** [review]

**Review by twangboy — DISMISSED** [review]

**Review by twangboy — DISMISSED** [review]

**Review by twangboy — APPROVED** [review]

**Review by dwoz — CHANGES_REQUESTED** [review]
Looks like the only changes we really need, for now, are in `tools/`.

**Comment by dmurphy18** [comment]
@dwoz Want to leave the other changes in there, since once we re-enable code coverage, we shall need them.

**Comment by dwoz** [comment]
> @dwoz Want to leave the other changes in there, since once we re-enable code coverage, we shall need them.

I'm skeptical that we need all those changes since we've been un-able to resolve the problem. Especially the sleeps.

**Review by Akm0d — APPROVED** [review]

**Pull request merged**
