### PR TITLE
[Documentation] Clarify that it is execution modules that sync returners

### PR DESCRIPTION
**Pull request by faivirol**
### What does this PR do?
I tried using the `saltutil.sync_returners` runner module instead of the execution module to refresh my custom returner. I only noticed my error when actually clicking the linked module. This PR clarifies the module type in the text as well.

### Merge requirements satisfied?
- [x] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### CODE REVIEW

**Comment by faivirol** [comment]
@cmcmarrow Could we get this merge?

**Review by barbaricyawps — DISMISSED** [review]
Seems pretty straightforward and since it's a tiny change, I don't see why we can't merge this in.

**Review by dmurphy18 — COMMENTED** [review]
I wonder about this since the next lines have a state.apply, sync_returners and sync_all but no execution modules ?

Wondering if the sentence needs further work ?

**Comment by barbaricyawps** [comment]
Good point, @dmurphy18 . @faivirol , what was the point of confusion that you were trying to clear up?

**Comment by lkubb** [comment]
Afaik the custom returner, like all Salt modules, needs to be present in the context you want to use it in. I'm not sure if there is a general explanation about this behavior (which could be linked) though.

Returners are usually relevant on minions, but when you are using some kind of job cache, the master will need the custom returner [either in addition to the minions (for `ext_job_cache`) or exclusively (for `master_job_cache`)].

**Comment by dmurphy18** [comment]
@faivirol 
```
I wonder about this since the next lines have a state.apply, sync_returners and sync_all but no execution modules ?

Those are execution modules.
```

State.apply is specifically for state files and is NOT an 'execution module', 
please refer to state handling in https://github.com/saltstack/salt/tree/master/salt/states
and execution modules in https://github.com/saltstack/salt/tree/master/salt/modules

An example of using an execution module would be
```
salt myminion cmd.run 'ls -alh /'
```

**Comment by faivirol** [comment]
Ah, I think we're talking about different things. I'm referring to the [execution module providing the `state.apply` function itself](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.state.html), not which modules are used when it applies states. The execution module function `state.apply` would be what is called to sync the returner modules though.

**Comment by dmurphy18** [comment]
Usually don't think of state.apply as an execution module, even though it is in salt/modules/state.py, probably since it was added in 2015.5.0 and I predate that.  Usually when referring to execution modules, referring to other modules in salt/modules, hence using the addition of 'execution modules' for sync_returners would be confusing to most users of Salt.

**Comment by lkubb** [comment]
To avoid confusion, I would propose just noting that the custom returner will need to be synced before it can be used with a link to https://github.com/saltstack/salt/blob/master/doc/topics/development/modules/index.rst#the-salt-file-server

I still see merit in the idea of writing an overview describing a few concepts that are common to most module types, probably here: https://github.com/saltstack/salt/blob/master/doc/topics/development/modules/developing.rst

**Comment by faivirol** [comment]
> Usually don't think of state.apply as an execution module, even though it is in salt/modules/state.py, probably since it was added in 2015.5.0 and I predate that. Usually when referring to execution modules, referring to other modules in salt/modules, hence using the addition of 'execution modules' for sync_returners would be confusing to most users of Salt.

I don't agree with you, but I see your point regarding `state.apply`, and if the others agree that it would be clearer for most then there's no point in me arguing. Nevertheless, I still think `saltutil.sync_returners` and `saltutil.sync_all` should be labeled as execution modules to distinguish them from their runner counterparts.

> To avoid confusion, I would propose just noting that the custom returner will need to be synced before it can be used

Good idea, but I still think how they are synced need to be described better.

> overview describing a few concepts that are common to the development of most module types

I disagree with this being a development-only issue. I've seen several beginner help posts where the difference between state and execution modules are not understood. Adding other types (like runners) on top of that without clearly explaining the difference would be even more confusing. I think it deserves more visibility than a for-developers page.

**Comment by dmurphy18** [comment]
@faivirol Would not argue against better documentation. Salt has had a long and varied history as to its documentation, hopefully it is getting better and @barbaricyawps is doing great work on improving it.

As for ```saltutil.sync_returners``` as an example, the function exists in salt/modules, salt/states and salt/runners, therefore labeling it as an execution modules is only one of its existence.

I like @lkubb 's suggestion ```propose just noting that the custom returner will need to be synced before it can be used```, and think this is a better solution.

**Comment by barbaricyawps** [comment]
That sounds like a good compromise here. @faivirol , would you be willing to update your PR with that suggestion from @lkubb ?

And yes, the Salt Docs working group does have an active project working in the community to improve how we explain the differences between the different types of modules and how to navigate them. It's a large project with multiple phases that I hope will be complete this year.

**Review by dmurphy18 — APPROVED** [review]

**Review by barbaricyawps — APPROVED** [review]
Looks good to me. I've also approved it. Thanks, @faivirol !

**Review by MKLeb — APPROVED** [review]

**Review by cmcmarrow — APPROVED** [review]

**Pull request merged**
