### PR TITLE
Upgrade msgpack to 1.0.2

### PR DESCRIPTION
**Pull request by krionbsd**
### What does this PR do?
Upgrade msgpack to 1.0.1

### CODE REVIEW

**Review by s0undt3ch — DISMISSED** [review]

**Review by s0undt3ch — APPROVED** [review]

**Comment by s0undt3ch** [comment]
@bryceml, @krionbsd: this doesn't bring any packaging issues?

**Review by bryceml — DISMISSED** [review]
No packaging issues as far as I can tell.

**Comment by s0undt3ch** [comment]
> No packaging issues as far as I can tell.

Thanks.

**Review by s0undt3ch — CHANGES_REQUESTED** [review]
@krionbsd this needs to be rebased.

**Comment by krionbsd** [comment]
> @krionbsd this needs to be rebased.

yes, all done

**Review by bryceml — APPROVED** [review]

**Comment by krionbsd** [comment]
re-run all

**Comment by krionbsd** [comment]
re-run all

**Review by s0undt3ch — APPROVED** [review]

**Pull request merged**
