### PR TITLE
Fix broken batch results

### LINKED ISSUE #24875: ValueError: list.remove(x): x not in list  in   File "/usr/lib/python2.6/site-packages/salt/cli/batch.py", line 179, in run active.remove(minion)
Was running salt 2015.5.2-3.el6

Downgraded back to 2015.5.0 and it is working correctly again. Details follow

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ValueError: list.remove(x): x not in list
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/salt.py", line 98, in run
    for res in batch.run():
  File "/usr/lib/python2.6/site-packages/salt/cli/batch.py", line 179, in run
    active.remove(minion)
ValueError: list.remove(x): x not in list
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 349, in salt_main
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/salt.py", line 98, in run
    for res in batch.run():
  File "/usr/lib/python2.6/site-packages/salt/cli/batch.py", line 179, in run
    active.remove(minion)
ValueError: list.remove(x): x not in list
```

### PR DESCRIPTION
**Pull request by driskell**
Fixes #24875

a34b74a70c8ebcabdf5096b0af02ae5d5770b531 fixed the ValueError but caused results to be overwritten as if a minion did not return, when actually it did.

The problem originates from the `StopIterator`:

```
                        # add all minions that belong to this iterator and
                        # that have not responded to parts{} with an empty response
                        for minion in minion_tracker[queue]['minions']:
                            if minion not in parts:
                                parts[minion] = {}
                                parts[minion]['ret'] = {}
```

Because the minions list is never reduced, it will populate parts with empty results for all minions that have not responded within the _last iteration_ as opposed to minions that have not responded within _any iteration_

Before a34b74a70c8ebcabdf5096b0af02ae5d5770b531 this meant a `ValueError` because the result set on the last iteration would contain empty responses for minions that weren't in the active queue anymore, because they responded in a previous iteration.

The fix, however, just skipped removing from active and carried on anyway, meaning the responses for minions that responded in earlier iterations were overwritten by the empty response generated in the last iteration.

This PR clears back the queue minion list as each minion responds, so only those that did not respond _at all_ are set to an empty response.

An alternative fix could be to check if the minion is in active and _skip_ so that the result is not overwritten. Not sure which is preferred - so I followed my own logical approach, which is to ensure `parts` only ever contains new information (it's weird that it contains empty responses for something that had already responded previously). Alternative smaller fix is at line 187 to do this instead, but I think it's more a bodge since `parts` would still be confusing:

```
                if minion not in active:
                    continue
                active.remove(minion)
```

### CODE REVIEW

**Comment by driskell** [comment]
To give an example, my original Gist on the `ValueError` problem is here: https://gist.github.com/driskell/141184f97476720819df

After applying the commit mentioned above, it stopped the `ValueError` but instead I would intermittently receive missing results, and upon debugging I could see the results did return, but were overwritten - in essence only the LAST batch to return was displayed, all previous batches were lost.

```
$ salt -s -t 5 '*' test.ping
server-01:
    ----------
server-02:
    ----------
server-11:
    ----------
server-12:
    True
server-13:
    ----------
server-14:
    ----------
server-15:
    ----------
server-16:
    ----------
server-17:
    ----------
server-18:
    ----------
server-19:
    ----------
server-20:
    ----------
server-21:
    ----------
server-22:
    ----------
server-25:
    ----------
server-26:
    ----------
server-27:
    ----------
server-28:
    ----------
server-29:
    ----------
server-30:
    ----------
server-31:
    ----------
server-32:
    ----------
server-33:
    ----------
server-34:
    ----------
server-35:
    ----------
server-36:
    ----------
server-37:
    ----------
server-38:
    ----------
```

**Comment by jfindlay** [comment]
@driskell, thanks for the fix. Next time you are welcome to send fixes directly to the oldest supported release branch as they are regularly merged forward, see https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

**Comment by driskell** [comment]
@jfindlay Ah sorry! I was meant to! I can update the PR later if it's not too late?

**Comment by jfindlay** [comment]
@driskell, if you want, you can close this PR and reopen it against 2015.5, depending on your git confidence.  Otherwise we'll merge this and backport it.

**Comment by driskell** [comment]
Closing to change target

**Comment by driskell** [comment]
Replaced by #25099 into 2015.5 branch

**Pull request closed without merging**
