### PR TITLE
Remove more unnecessary explicit unicode literals

### PR DESCRIPTION
**Pull request by terminalmage**

### CODE REVIEW

**Comment by rallytime** [comment]
@terminalmage Lint: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/17334/violations/

**Comment by terminalmage** [comment]
Should be fixed.

**Comment by rallytime** [comment]
@terminalmage I think there are two new test failures on this:
- unit.modules.test_parallels.ParallelsTestCase.test_snapshot_name_to_id
- unit.templates.test_jinja.TestCustomExtensions.test_nested_structures

Can you take a look?

**Comment by rallytime** [comment]
@terminalmage Those test failures might be fixed from your work in other PRs. However, now there is a merge conflict. Can you rebase?

**Comment by rallytime** [comment]
Ah, so the `unit.modules.test_parallels.ParallelsTestCase.test_snapshot_name_to_id` test failure is still related to this one. @terminalmage Please take a look when you get a moment.

**Comment by terminalmage** [comment]
The test failure should be fixed now.

**Comment by rallytime** [comment]
@terminalmage This needs a rebase now.

**Comment by terminalmage** [comment]
rebased

**Comment by terminalmage** [comment]
rebased

**Comment by terminalmage** [comment]
One more rebase to pull in the fixes for a couple of the failures. I _think_ they were all unrelated, but I'm not sure.

**Review by rallytime — APPROVED** [review]
🎉

**Pull request merged**
