### PR TITLE
X509

### PR DESCRIPTION
**Pull request by clinta**
Added the ability to omit the serial number from the authoritykeyidentifier extension to avoid the issues described here: https://www.v13.gr/blog/?p=293

Other bug fixes for more accurately determining if a state requires a change.

### CODE REVIEW

**Comment by jfindlay** [comment]
@clinta, thanks for the pull request.  Did you intend for this to go into the 2014.7 branch?  In the future, please feel free to submit bug fixes directly to the oldest, supported, applicable release branch as this prevents us from needing to backport commits as the branches are regularly merged forward, see https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

**Comment by clinta** [comment]
I don't think this needs to be backported. According to the tag in the docs, this module and state are going in until Beryllium.

**Comment by jfindlay** [comment]
I didn't check for that, I was responding to your comment about state internal keywords in 2014.7.2.  Thanks for fixing this stuff.

**Comment by jfindlay** [comment]
It is an insignificant detail, but I've just verified that `listen_in` and `preqrequired` are included in `_STATE_INTERNAL_KEYWORDS` on the head of 2014.7.

**Pull request merged**
