### PR TITLE
Use packaged json module for ThreadsafeProxy

### PR DESCRIPTION
**Pull request by Akm0d**
### What does this PR do?
Separate json lib import changes from #54878 
This is in preparation for the threadsafe loader PR

### CODE REVIEW

**Comment by Akm0d** [comment]
re-run full debian8

**Comment by Akm0d** [comment]
re-run full centos6

**Review by garethgreenaway — APPROVED** [review]

**Review by s0undt3ch — APPROVED** [review]

**Review by s0undt3ch — COMMENTED** [review]
Any reason why we're maintaining code like:
```python
from salt.utils.json import loads, dumps
```
As opposed to something like, for example:
```python
import salt.utils.json as json

x = json.loads()
y = json.dumps()
```

**Comment by Akm0d** [comment]
re-run full debian8

**Comment by Akm0d** [comment]
re-run full windows2019

**Pull request merged**
