### PR TITLE
[2018.3] Fixes to logic behind ipv6 filter

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Updating the logic in `IPv6InterfaceScoped` to handle situation when this code is running on Python 2 where bytes & strings are treated as the same.  Previously when an IPv6 network with a netmask was included it would be treated as a string and handled in the wrong block, which would result in the passed string as invalid.

### What issues does this PR fix or reference?
#52518

### Previous Behavior
`ipv6` filter did not work as expected

### New Behavior
`ipv6` works again as expected

### Tests written?
Yes

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by dwoz — APPROVED** [review]

**Comment by dwoz** [comment]
re-run full all

**Review by Ch3LL — APPROVED** [review]

**Review by s0undt3ch — APPROVED** [review]

**Comment by waynew** [comment]
@b-a-t I'll bring this up in our meeting today

**Comment by Ch3LL** [comment]
@garethgreenaway can you re-base against master

**Comment by Ch3LL** [comment]
bump @garethgreenaway

**Comment by Ch3LL** [comment]
@garethgreenaway can you re-base against master

**Comment by garethgreenaway** [comment]
Redone in #55979

**Pull request closed without merging**
