### PR TITLE
#46504 Fix

### LINKED ISSUE #46504: ntp.managed fails on non-english systems
### Description of Issue
It is impossible to use `ntp.managed` function on non-english versions of Windows Server 2016. I think the problem is in `win_ntp.py`:
```
if 'command completed successfully' not in ret:
            return False
```
A `command completed successfully` string is only returned in EN version of Windows. In other languages this string differs.

### Setup
```
win_ntp:
  ntp.managed:
    - servers:
      - ntp21.vniiftri.ru,0x8
      - pool.ntp.org,0x8
      - time.windows.com,0x8
```

### Steps to Reproduce Issue
1. Run `ntp.managed` on Windows Server 2016 (EN) and get (as expected):
```
ID: win_ntp
  Function: ntp.managed
    Result: True
```
2. Run the same `ntp.managed` on Windows Server 2016 (RU) and get:
```
ID: win_ntp
  Function: ntp.managed
    Result: False
   Comment: Failed to update NTP servers
```

### Versions Report
Salt Master:
```
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

Salt Minion: 2017.7.3

### PR DESCRIPTION
**Pull request by jfoboss**
### What does this PR do?

This patch allows `ntp.managed` to work on Windows with non-English locales.

### What issues does this PR fix or reference?
Fixes #46504 

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Review by twangboy — APPROVED** [review]

**Comment by rallytime** [comment]
@jfoboss This change is causing the following test to fail:

- unit.modules.test_win_ntp.WinNtpTestCase.test_set_servers

https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/20819/

Can you take a look?

**Comment by jfoboss** [comment]
@rallytime yes, I'll try.

**Comment by rallytime** [comment]
Hi @jfoboss - just checking in here to see if you had a chance to look at that test failure.

**Comment by jfoboss** [comment]
Hi @rallytime 

I've looked at it, but unfortunately wasn't able to fix the issue :( I do not know python so well.

**Comment by rallytime** [comment]
@twangboy Would you be willing to jump in here and adjust the tests for this change?

**Review by cachedout — APPROVED** [review]

**Comment by cachedout** [comment]
@twangboy Can you give us an update here? We need to get going with this. Thanks.

**Comment by twangboy** [comment]
Added to my list.

**Comment by twangboy** [comment]
@jfoboss I submitted a PR against your branch that will add tests. Please merge.

**Comment by twangboy** [comment]
https://github.com/jfoboss/salt/pull/1

**Comment by jfoboss** [comment]
Merged! @twangboy thank you very much!

**Comment by rallytime** [comment]
Thanks @jfoboss and @twangboy!

**Pull request merged**
