### PR TITLE
docs: add VIRTUALENV_ALWAYS_COPY option example

### PR DESCRIPTION
**Pull request by binary1230**
### What does this PR do?
Show how a user can specify VIRTUALENV_ALWAYS_COPY to copy files instead of using symlinks

This is necessary for some filesystems (particularly vboxfs mounted in a linux VM from a windows host) where trying to create symlinks isn't allowed and results in a 'protocol error'.

See https://github.com/pypa/pipenv/issues/2084 for non-salt-related discussion about the underlying issue

In the future, it might be good to explicitly support the --always-copy switch on the virtualenv command so we don't have to use environment vars this way in Salt.

Open for other suggestions on how to document this, or how to handle this situation in Salt.

I didn't have a way to test the doc generation here, will make a fix if it's needed

### What issues does this PR fix or reference?
None

### Tests written?
N/a, documentation only

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by dwoz** [comment]
@binary1230 Can you please resolve the linter failures?

**Comment by dwoz** [comment]
@binary1230 ping

**Comment by dwoz** [comment]
@binary1230 Can you find time to address the linter failures?

**Comment by binary1230** [comment]
Hey, sorry I haven't had a chance to come back to this. I may have time in
next two weeks to give it a look.

**Comment by dwoz** [comment]
@binary1230 pointed this to master

**Comment by binary1230** [comment]
like a year later got around to hopefully fixing the linting errors, I'll ping when this is ready to go.

**Review by dwoz — APPROVED** [review]

**Pull request merged**
