### PR TITLE
Fixes unicode output issue

### LINKED ISSUE #45525: UnicodeDecodeError in highstate output
### Description of Issue/Question
I have a issue with unicode and the highstate i don't know where is is comming from

I get the following error:

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 26767: ordinal not in range(128)
Traceback (most recent call last):
File "/usr/bin/salt-call", line 11, in <module>
salt_call()
File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 391, in salt_call
client.run()
File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
caller.run()
File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 149, in run
self.opts)
File "/usr/lib/python2.7/site-packages/salt/output/__init__.py", line 92, in display_output
display_data = try_printout(data, out, opts, **kwargs)
File "/usr/lib/python2.7/site-packages/salt/output/__init__.py", line 39, in try_printout
printout = get_printout(out, opts)(data, **kwargs)
File "/usr/lib/python2.7/site-packages/salt/output/highstate.py", line 145, in output
for host, hostdata in six.iteritems(data)
File "/usr/lib/python2.7/site-packages/salt/output/highstate.py", line 349, in _format_host
comment = '{0}\n\t\t{1}: {2}'.format(comment, key, value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 26767: ordinal not in range(128)
Traceback (most recent call last):
File "/usr/bin/salt-call", line 11, in <module>
salt_call()
File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 391, in salt_call
client.run()
File "/usr/lib/python2.7/site-packages/salt/cli/call.py", line 58, in run
caller.run()
File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 149, in run
self.opts)
File "/usr/lib/python2.7/site-packages/salt/output/__init__.py", line 92, in display_output
display_data = try_printout(data, out, opts, **kwargs)
File "/usr/lib/python2.7/site-packages/salt/output/__init__.py", line 39, in try_printout
printout = get_printout(out, opts)(data, **kwargs)
File "/usr/lib/python2.7/site-packages/salt/output/highstate.py", line 145, in output
for host, hostdata in six.iteritems(data)
File "/usr/lib/python2.7/site-packages/salt/output/highstate.py", line 349, in _format_host
comment = '{0}\n\t\t{1}: {2}'.format(comment, key, value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 26767: ordinal not in range(128)
```

### Versions Report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.5.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

### PR DESCRIPTION
**Pull request by dverbeek84**
### What does this PR do?
It fix unicode error output on a highstate run.

### What issues does this PR fix or reference?
Fixes #45525

### Tests written?
No

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by damon-atkins** [comment]
You need to wait until oxygen is release please or at least RC1.  Please close the pull request.
As  "u" prefixing will not be used from oxygen onwards.

**Comment by rallytime** [comment]
Hi @dverbeek84 - thank you so much for submitting this fix and welcome to Salt! We are working on unicode support right now for the oxygen release, as @damon-atkins stated above. I am curious if those updates will fix the issue you've seen, as using the `u` prefix is not the way we're approaching these fixes.

Can you test at the HEAD of the `oxygen` branch by chance and see if this has been resolved for you?

**Comment by dverbeek84** [comment]
Sorry for the late respons, i will test is.

**Comment by rallytime** [comment]
@dverbeek84 No worries. I'm just checking in here to see if you were able to test this. :)

**Comment by rallytime** [comment]
@dverbeek84 Since we won't be handling a bug in this way by adding the `u`, I'm going to close this PR. Please fee free to comment once you've had a change to test the latest develop and if you are still seeing issues. Thanks!

**Pull request closed without merging**
