### PR TITLE
Default http.query() to urllib2, but still allow requests

### PR DESCRIPTION
**Pull request by techhat**
Replaces #19691.

### CODE REVIEW

**Comment by techhat** [comment]
Don't merge yet, need to finish up `get_ca_bundle()`.

**Comment by thatch45** [comment]
Don't merge yet, we still need the config.py changes to add ca_bundle option

**Comment by techhat** [comment]
@thatch45, I decided not to go with `config.py`. This PR is now ready to be merged, once SSL testing is finished.

**Comment by techhat** [comment]
Go Go Jenkins!

**Comment by techhat** [comment]
Lint failures are unrelated.

**Pull request merged**
