### PR TITLE
Fix pillar and salt fileserver mixed

### PR DESCRIPTION
**Pull request by bersace**
Fixes saltstack/salt#22844

### CODE REVIEW

**Comment by bersace** [comment]
The build fails du to missing JUnit file. Any clue ?

**Comment by rallytime** [comment]
We're having some difficulties with Jenkins. We'll run these again when we've got it all squared away. Thanks!

**Comment by bersace** [comment]
@rallytime Thanks ! Can i have some feedback on the changes ?

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by bersace** [comment]
Nice !! :-)

**Comment by bersace** [comment]
Looks like a timeout. https://jenkins.saltstack.com/job/salt-pr-rs-cent7-n/4077/testReport/integration.client.runner/RunnerModuleTest/test_cmd_sync_w_arg/

How to fix that ?

**Comment by jfindlay** [comment]
@bersace, that error is a known intermittent test failure unrelated to your code.  We haven't figured out what is causing it yet.

**Comment by bersace** [comment]
Thank you very much !! :-)

**Comment by basepi** [comment]
@bersace FYI, [this change](https://github.com/basepi/salt/commit/31b98e72ebad094f8692085d74479a758a7527ce) is causing [some test failures on 2015.2](https://jenkins.saltstack.com/job/salt-pr-rs-ubuntu14.04-n/4173/). Probably due to the introduction of the lazyloader. If #22844 is still present in 2015.2 (which it may not be) then we'll need to find a different fix there. Thanks!

**Comment by bersace** [comment]
Thanks for pointing it. I'm pretty sure there is a better solution.

@basepi don't you think we should refactor pillar and state fileserver/fileclient backends loading ? We should not put pillar_roots in file_roots.

**Comment by basepi** [comment]
I've never been able to reproduce your issue of pillar_roots showing up in file_roots, so I'm not sure if it needs a refactor or not... =\

**Comment by bersace** [comment]
@basepi did you tried the setup of #22844 ? Here we reproduce it regularily. It triggrers when you use jinja loader (e.g. by using extends).

**Comment by bersace** [comment]
Anyway, that would be more explicit to be able to pass `file_roots` or `pillar_roots` as an argument to backends. Wathever the way.

**Comment by basepi** [comment]
I guess I haven't done it with an extends. I realize my comment above almost seemed dismissive of your issue, and I didn't mean it that way. We just need to find a way to fix this without breaking the LazyLoader.

**Comment by bersace** [comment]
That's ok, i'll fix that. I'm not working with 2015.2 right now. I will poke you with a PR asap.

**Pull request merged**
