### PR TITLE
runas user for FreeBSD should be 'postgres' not pgsql

### PR DESCRIPTION
**Pull request by kgbsd**
### What does this PR do?
....rebased and duplicate of dead pr: https://github.com/saltstack/salt/pull/53327#
Fix postgresql user on FreeBSD.
That user was updated from 'pgsql' to 'postgresql' in 2016:
https://svnweb.freebsd.org/ports/head/UPDATING?revision=502290&view=co
20160905:
AFFECTS: users of databases/postgresql96-server
AUTHOR: girgen@FreeBSD.org

The default unix user used by the PostgreSQL daemon has changed to
postgres' to reflect the long time upstream's convention. Any scripts you have using the old pgsql' unix user should be modified when upgrading to
PostgreSQL version 9.6. Older versions of PostgreSQL will continue using
`pgsql' until their end-of-life.

### What issues does this PR fix or reference?
Fixes: able to manage postgresql databases with salt

### Previous Behavior
 Result: False
 Comment: An exception occurred in this state: Traceback (most recent call last):
            File "/usr/local/lib/python3.6/site-packages/salt/modules/cmdmod.py", line 425, in _run
              pwd.getpwnam(runas)
          KeyError: "getpwnam(): name not found: 'pgsql'"
          
          During handling of the above exception, another exception occurred:
          
          Traceback (most recent call last):
            File "/usr/local/lib/python3.6/site-packages/salt/state.py", line 1933, in call
              **cdata['kwargs'])
            File "/usr/local/lib/python3.6/site-packages/salt/loader.py", line 1939, in wrapper
              return f(*args, **kwargs)
            File "/usr/local/lib/python3.6/site-packages/salt/states/postgres_database.py", line 98, in present
              dbs = __salt__['postgres.db_list'](**db_args)
            File "/usr/local/lib/python3.6/site-packages/salt/modules/postgres.py", line 488, in db_list
              password=password)
            File "/usr/local/lib/python3.6/site-packages/salt/modules/postgres.py", line 438, in psql_query
              password=password)
            File "/usr/local/lib/python3.6/site-packages/salt/modules/postgres.py", line 377, in _psql_prepare_and_run
              rcmd, runas=runas, password=password, host=host, port=port, user=user)
            File "/usr/local/lib/python3.6/site-packages/salt/modules/postgres.py", line 186, in _run_psql
              ret = __salt__['cmd.run_all'](cmd, python_shell=False, **kwargs)
            File "/usr/local/lib/python3.6/site-packages/salt/modules/cmdmod.py", line 2069, in run_all
              **kwargs)
            File "/usr/local/lib/python3.6/site-packages/salt/modules/cmdmod.py", line 428, in _run
              'User \'{0}\' is not available'.format(runas)
          salt.exceptions.CommandExecutionError: User 'pgsql' is not available
 Started: 09:44:32.474881
Duration: 7.452 ms
 Changes:  

### New Behavior
use postgres is found

### Merge requirements satisfied?
afaict

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by kgbsd** [comment]
bug report in FreeBSD world: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=250186

**Comment by piterpunk** [comment]
This one fixes #53393

**Review by Ch3LL — CHANGES_REQUESTED** [review]
I know this is a big ask, but I would love to get test coverage for this change, so we can catch these sort of things in the future. Since there is not any current test coverage that I could find if you are not able to add the tests I definitely am.

**Comment by kgbsd** [comment]
hmm, not sure what 'test coverage' is.
This was caught as soon as I tried to manage a postgresql server on 
FreeBSD via salt state.
   manage:
     add user
     add database

]Peter[

**Review by Ch3LL — DISMISSED** [review]
After discussing with @krionbsd the package maintainer is deprecating the older postgres package and removing in May that used to use this old username (9.5), so we are going to go ahead and approve this. I will push a changelog file later today so we can get this merged.

**Comment by krionbsd** [comment]
girgen@FreeBSD will mark `postgresql95-server` port as deprecated and will remove it on 2021-05-13, so we might safely change default user to `postgresql` for FreeBSD

**Review by krionbsd — DISMISSED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
