### PR TITLE
fix: boto_vpc.route_table_present honors updated module interface

### LINKED ISSUE #59281: [BUG] boto_vpc.route_table_present fails with TypeError
**Description**

The `boto_vpc.route_table_present` state can fail in ordinary cases now (since 3002 AFAICT):

```
[ERROR ] An exception occurred in this state: Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/salt/state.py", line 2154, in call
*cdata["args"], **cdata["kwargs"]
File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2106, in wrapper
return f(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/salt/states/boto_vpc.py", line 1123, in route_table_present
profile=profile,
File "/usr/lib/python3.6/site-packages/salt/states/boto_vpc.py", line 1438, in _subnets_present
assoc_ids = [x["subnet_id"] for x in route_table["associations"]]
TypeError: list indices must be integers or slices, not str
```

https://github.com/saltstack/salt/commit/f78706934ffb83c8d215c7c7ec12bcbdd7d8bd45#diff-1f72651468451cc4bde8de43a9b68cdf21e63dcf0f2f5804943bb92a7f780c70R1491 in #58636 broke this AFAICT.  The deprecated method and the new method have different returns and so a drop-in replacement was not appropriate.  The new method returns a list.  Other places in the code do... https://github.com/saltstack/salt/blob/da6819735ce055f16e326472cb1768faece72ad6/salt/states/boto_vpc.py#L1216 ... to handle this.

**Setup**

`foo.sls`:

```sls
create_route_table:
  boto_vpc.route_table_present:
    - name: foo
    - vpc_id: vpc-4321dbca
    - routes:
      - destination_cidr_block: 0.0.0.0/0
        instance_id: i-abcd1234
```

**Steps to Reproduce the behavior**

AWS setup, then `state.apply foo`.

**Expected behavior**

No exception, state completes.

**Versions Report**
<details><summary>salt --versions-report</summary>

Also includes latest `boto` and `boto3`.

```text
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: 1.14.4
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-60-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Additional context**

ZD-6200.

Workaround is to directly patch `salt/states/boto_vpc.py` with `route_table = route_table[0]` above the problem line.

### PR DESCRIPTION
**Pull request by defanator**
### What does this PR do?

Allows to use `boto_vpc.route_table_present` state in 3002.5.

### Previous Behavior
```
local:
----------
          ID: pdx1-mgmt Default Routing Table
    Function: boto_vpc.route_table_present
        Name: pdx1-mgmt-default-rtb
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2153, in call
                  ret = self.states[cdata["full"]](
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2106, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/boto_vpc.py", line 1115, in route_table_present
                  _ret = _subnets_present(
                File "/usr/lib/python3/dist-packages/salt/states/boto_vpc.py", line 1438, in _subnets_present
                  assoc_ids = [x["subnet_id"] for x in route_table["associations"]]
              TypeError: list indices must be integers or slices, not str
     Started: 10:34:43.092049
    Duration: 290.465 ms
     Changes:   
```

### New Behavior

No errors in test mode; actual changes are being pushed in real mode.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

### Versions

```
# salt --versions
Salt Version:
          Salt: 3002.5
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 0.28.3
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: 1.0.3
        Python: 3.8.5 (default, Jan 27 2021, 15:41:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-1038-aws
        system: Linux
       version: Ubuntu 20.04 focal
```

### CODE REVIEW

**Comment by defanator** [comment]
Unfortunately I haven't had a chance to look into tests yet - will try to provide corresponding update ASAP.

**Comment by sagetherage** [comment]
closing as addressed in Aluminium release

**Comment by sagetherage** [comment]
fixed here: https://github.com/saltstack/salt/commit/32ed7d05f0af1f07a0144cf5594370a5d65e70b3

**Comment by defanator** [comment]
@sagetherage unfortunately, I'm still seeing the same error with 3003.3:

```
# salt --versions
Salt Version:
          Salt: 3003.3
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 0.28.3
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: 1.0.3
        Python: 3.8.10 (default, Sep 28 2021, 16:10:42)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.11.0-1019-aws
        system: Linux
       version: Ubuntu 20.04 focal
```

```
# salt-call state.apply datacenters.pdx1.nonprod.vpc test=True
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/state.py", line 2171, in call
    ret = self.states[cdata["full"]](
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1241, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2274, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2289, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2322, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/states/boto_vpc.py", line 1115, in route_table_present
    _ret = _subnets_present(
  File "/usr/lib/python3/dist-packages/salt/states/boto_vpc.py", line 1438, in _subnets_present
    assoc_ids = [x["subnet_id"] for x in route_table["associations"]]
TypeError: list indices must be integers or slices, not str

local:
----------
          ID: pdx1-nonprod Default Routing Table
    Function: boto_vpc.route_table_present
        Name: pdx1-nonprod-default-rtb
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2171, in call
                  ret = self.states[cdata["full"]](
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1241, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2274, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2289, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2322, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/boto_vpc.py", line 1115, in route_table_present
                  _ret = _subnets_present(
                File "/usr/lib/python3/dist-packages/salt/states/boto_vpc.py", line 1438, in _subnets_present
                  assoc_ids = [x["subnet_id"] for x in route_table["associations"]]
              TypeError: list indices must be integers or slices, not str
     Started: 15:28:08.862631
    Duration: 126.419 ms
     Changes:   

Summary for local
-------------
Succeeded: 12
Failed:     1
-------------
Total states run:     13
Total run time:    2.227 s```

Collecting more data to debug this.

**Comment by defanator** [comment]
FWIW, I'm still seeing the issue this PR originally meant to fix in 3006.5:

```
2024-01-10 13:14:13,342 [salt.state       :323 ][ERROR   ][2482442] An exception occurred in this state: Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/state.py", line 2423, in call
    ret = self.states[cdata["full"]](
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 159, in __call__
    ret = self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1293, in wrapper
    return f(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/boto_vpc.py", line 1115, in route_table_present
    _ret = _subnets_present(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/states/boto_vpc.py", line 1440, in _subnets_present
    assoc_ids = [x["subnet_id"] for x in route_table["associations"]]
TypeError: list indices must be integers or slices, not str
```

Patch still can be applied with minor offset, and fixes this.

cc/ @sagetherage @dwoz

**Pull request closed without merging**
