### PR TITLE
Add a GitConfigParser class for manipulating git config files

### PR DESCRIPTION
**Pull request by terminalmage**
This class is designed to be used for (among other things) gitfs and git_pillar, to enforce config settings which reside in a git config file without resorting to using the git CLI.

**EDIT: I've updated this PR to make salt.utils.gitfs use this new parser class.**

### CODE REVIEW

**Comment by rallytime** [comment]
@terminalmage There are some lint errors for this PR: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/14407/

**Review by cachedout — APPROVED** [review]
Really, really nice. ++

**Comment by terminalmage** [comment]
@rallytime The lint errors, at least the ones in the new configparser, appear to be false-positives. I've fixed the legit failures, added pylint disables where needed, and rebased to fix a merge conflict.

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
Awesome! Thanks @terminalmage

**Pull request merged**
