### PR TITLE
pass opts to SSHClient for enable_ssh_minions

### PR DESCRIPTION
**Pull request by gtmanfred**
### What does this PR do?
The loaded opts for the salt master should be passed to the SSHClient so that the same state directories are used

### Tests written?

YES!

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by garethgreenaway — APPROVED** [review]

**Comment by gtmanfred** [comment]
I think i found another bug in this maybe, working on adding tests too.

**Comment by gtmanfred** [comment]
This should be good to merge if the tests pass

**Comment by gtmanfred** [comment]
re-run py

**Comment by gtmanfred** [comment]
Working on the related test failures now

**Comment by gtmanfred** [comment]
re-run py

**Comment by gtmanfred** [comment]
Ok, all the tests pass on my laptop now.

**Comment by gtmanfred** [comment]
re-run py

**Review by rallytime — APPROVED** [review]

**Comment by gtmanfred** [comment]
re-run ubuntu

**Pull request merged**
