### PR TITLE
adding states/postgres_group unit test case.

### PR DESCRIPTION
**Pull request by jayeshka**
Implemented states/postgres_group_test unit test case.

### CODE REVIEW

**Comment by jfindlay** [comment]
@jayeshka, there are some failures.

**Comment by jayeshka** [comment]
@jfindlay test are passing at my end.
Pulled updated branch of 2015.5 and try to run th test. I don't get any failures.
Tried for both #24329 and #24331.

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Pull request merged**
