### PR TITLE
Handle PermissionError when importing crypt when FIPS is enabled.

### PR DESCRIPTION
**Pull request by takeda**
### What does this PR do?

When salt runs on a machine where FIPS is enabled, it produces:
```
PermissionError: [Errno 1] Operation not permitted
```
on import.

This error shows up in certain circumstances, for example when trying to get documentation from a module.

```
salt-call saltutil
```

### What issues does this PR fix or reference?
Fixes: not created

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by whytewolf** [comment]
Thank you for the PR. Is there anyway we can get some tests to make sure the functionality doesn't break in the future. as well as a changelog file.

**Comment by takeda** [comment]
@whytewolf I'm not sure how this could be tested. To enable FIPS you switch a sysctl in the kernel `crypto.fips_enabled = 1`. I don't see how this could be incorporated in an unit test.

**Comment by whytewolf** [comment]
@takeda sorry. I missed this was only catching on import. in theory you could mock the `__import__` function but that is tricky business that can cause all sorts of nightmares. I"ll go ahead and see if we can bypass the test requirement.

**Comment by whytewolf** [comment]
it does still need a changelog though

**Review by s0undt3ch — DISMISSED** [review]

**Review by whytewolf — DISMISSED** [review]

**Review by s0undt3ch — APPROVED** [review]

**Comment by Ch3LL** [comment]
Merging as tests passed previously before the changelog was added.

**Review by twangboy — APPROVED** [review]

**Pull request merged**
