### PR TITLE
Fix timezones states on OS X

### PR DESCRIPTION
**Pull request by opdude**
### What does this PR do?

Fixes timezones on OS X
### Previous Behavior

Crashes with stack trace when setting timezone
### New Behavior

Timezone correctly set
### Tests written?

No

### CODE REVIEW

**Comment by rallytime** [comment]
Hi @opdude thank you for submitting this. Can you fixup [these lint errors](https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/5121/violations/file/salt/modules/mac_timezone.py/)?

**Comment by opdude** [comment]
@rallytime Actually I think I must have been tired when I committed the above, we should just have empty functions for this. Updated the PR here I can start fresh if you prefer?

**Comment by rallytime** [comment]
@opdude This is fine the way it is. Lint didn't run on the last commit, though, so i am going to restart these.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Pull request merged**
