### PR TITLE
Bugfix #47984 messed up cert serial

### PR DESCRIPTION
**Pull request by lusche**
### What does this PR do?

Fix the Problem described in #47984 in the 2017 branch

### What issues does this PR fix or reference?

#47984

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by cachedout** [comment]
I would rather we just backport #47984 instead. @rallytime what do you think?

**Comment by lusche** [comment]
I'm sure that is possible but some parts of the PR are not available in the 2017 branch.

For example: ```import salt.utils.stringutils``` 

To be honest my fix is quick an not so "nice" but should do the job. But if anyone is willing to backport the original fix that's ok to.

 I hope that this issue gets a fix soon. At this time we had a ugly workaround to make it work.

**Comment by jeduardo** [comment]
Hey all, chiming in here :)

My original fix actually targeted at 2017.7 and was even simpler than the one suggested here. Removing the offending line `serial_number = str(int(serial_number, 16))` was enough to get the correct serial into the CRL. This is what is running on my 2017.7 environment though the magic of `_modules/x509.py`.

However as current Salt has unicode strings everywhere (which is a _Good Thing(tm)_) simply removing the line ended up not being enough.

**Comment by cachedout** [comment]
@jeduardo Thanks for the info. Are you in favor of this being merged then? I couldn't quite get your opinion from your comment.

**Comment by jeduardo** [comment]
@cachedout I've meant to say that the patch is in the right direction but can be simplified by removing the buggy line altogether instead of replacing it by `serial_number = str(serial_number)`. 

The `serial_number` variable will already be a string at that point in the code (as its value is returned from string.replace() as a string already), thus making the `str(serial_number)` call redundant.

**Comment by rallytime** [comment]
Ah, I missed my original ping somehow. I can backport #47986 to the 2018.3 branch, but as stated above, it won't back-port nicely to 2017.7. I'll do the 2018.3 back-port right now so it will be included in 2018.3.3.

In the mean time, @lusche - what do you think about @jeduardo's latest comment.

**Comment by lusche** [comment]
@rallytime i pushed the suggested changes. @jeduardo hint sounds plausible.

**Comment by garethgreenaway** [comment]
In 2017.7 we should be fine just removing that line since we're not enforcing Unicode like we are in 2018.3.  This looks good to me.

**Review by garethgreenaway — APPROVED** [review]

**Comment by jeduardo** [comment]
@rallytime well, @garethgreenaway already approved it but indeed it does look just like the patch I initially did when I've faced the problem on 2017.7. 

I'm also really glad this is getting in as we are not yet ready to migrate to 2018.3 at $WORKPLACE. :)

**Pull request merged**
