### PR TITLE
Ensure rh_service not used on CloudLinux 7

### PR DESCRIPTION
**Pull request by afletch**
Adds CloudLinux to list of distros excluded from rh_service if osrelease >= 7

### CODE REVIEW

**Comment by afletch** [comment]
@cachedout Is this likely to make it into the next release? Pretty big problem for CloudLinux users, no service management works.

**Comment by rallytime** [comment]
@afletch As this PR stands right now, it won't come out until the "Carbon" feature release of Salt. But we can backport the fix to a bugfix branch. How far should this go back? 2015.8?

Also, note that in the future, if a bugfix needs to go into an earlier branch, you can submit the fix directly against the bugfix branch directly, and then we'll merge the fix forward to newer branches. You can learn more about this process [here](https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch), if you're interested.

**Comment by afletch** [comment]
@rallytime 2015.8 would be ideal, please
Thanks for the link, will digest.

**Comment by rallytime** [comment]
@afletch Done!

**Pull request merged**
