### PR TITLE
Sodium is Py3 only. Disable our Pylint Py3 compatible code plugin.

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title

### CODE REVIEW

**Comment by s0undt3ch** [comment]
This needs a fix

**Comment by s0undt3ch** [comment]
Fix pushed

**Review by dwoz — APPROVED** [review]

**Comment by dwoz** [comment]
Don't we want to catch incompatible py3 code since that's all we support?

**Comment by s0undt3ch** [comment]
This plugin was probably badly named.
The purpose was to have py2 code which was compatible with py3.
We now run on py3 only, so, no need for these checks.

**Review by dwoz — APPROVED** [review]

**Pull request merged**
