### PR TITLE
Add initscripts, SystemD service units and environment files for Debian

### PR DESCRIPTION
**Pull request by vutny**
### What does this PR do?

Adds necessary files for complete bootstrapping (via [bootstrap-salt.sh](https://github.com/saltstack/salt-bootstrap)) Salt components on Debian GNU/Linux from Git without downloading from external repos and sources. 

This PR is required for replacing workarounds in the bootstrap script which set up Salt services.
It will complement PR saltstack/salt-bootstrap#828 for better support of git installations on Debian.

### CODE REVIEW

**Comment by rallytime** [comment]
Thanks @vutny. I think this need review from someone other than me. @terminalmage @cachedout or maybe @s0undt3ch? Can you guys check this one out when you get a moment?

**Comment by vutny** [comment]
Actually these files are from official Salt packages build by [salt-pack](https://github.com/saltstack/salt-pack). I've just corrected service descriptions are removed useless comments from units.
At the moment, the files are only supposed to be used in the bootstrap process.

**Comment by cachedout** [comment]
@vutny Could you please further explain the intention here? It looks like you changed the bootstrap script to expect these? Where were they being pulled from prior to this?

**Comment by cachedout** [comment]
@vutny Could you please respond to my question above when you get a moment? Thanks.

**Comment by vutny** [comment]
@cachedout Sorry for the delay.

Main intention for adding these files is to have consistent bootstrapping from Git on Debian systems.
Currently Salt git repository contains only SysV initscripts and SystemD units only suitable for `rpm` based distros and Ubuntu.

Available SystemD service units don't work on Debian 8 and we need to edit them in-line after copying from the repo checkout directory.
To be able to successfully do a git installation on Debian 7, develop version of bootstrap script downloads the service init files from [Debian VCS](https://anonscm.debian.org/cgit/pkg-salt/salt.git/plain/debian/). That's not very reliable way though.

In any case, old behavior will be kept as fallback if required files are missing in the git branch that used to bootstrap from.

This PR eliminates unnecessary external sources needed for bootstrapping Debian GNU/Linux from Git and makes the installation straight-forward like on other systems.

**Comment by cachedout** [comment]
@s0undt3ch You have any input here?

**Comment by s0undt3ch** [comment]
If we already provide these kind of files for other distros, is there really any reason why we shouldn't also provide the Debian ones?

**Comment by cachedout** [comment]
@s0undt3ch Seems sensible enough to me. Let's do it.

**Pull request merged**
