### PR TITLE
Use 'rpm -qa' instead of repoquery to list installed packages

### LINKED ISSUE #26338: A couple yumpkg Modules Use Flawed Primary Check-Method
Currently working on placing a self-installing SHell ARchive under the control of Salt. The SHAR's behavior needs to be modified depending on whether RPMs within the SHAR are already present. I was initially going to use pkg.version as a simple test to govern how to run the SHAR. Discovered that pkg.version was always returning false:

~~~
# salt-call --local pkg.version MFErt MFEcma kernel
[INFO    ] Executing command "repoquery --plugins --queryformat '%{NAME}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-%{REPOID}' --all --pkgnarrow=installed" in directory '/root'
local:
    ----------
    MFEcma:
    MFErt:
    kernel:
        2.6.32-573.1.1.el6
~~~

even if the RPMs were already installed:
~~~
# rpm -qa MFE* kernel
MFEcma-4.8.0-1500.i686
MFErt-2.0-0.i686
kernel-2.6.32-573.1.1.el6.x86_64
~~~
When looking for other `pkg.*` options to use, also found that `pkg.check_db` similarly fails if the queried RPM exists in the local installation but not within a defined repo.

Use of `repoquery` probably should not be the primary check-method used. Its results are mostly relevant when comparing local/repo, but not useful when trying to check local only/first.

### PR DESCRIPTION
**Pull request by terminalmage**
Resolves #26338

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by terminalmage** [comment]
@s0undt3ch That Ubuntu test is still being flaky. Given that this PR deals with yum only, and the Cent7 tests all passed, should we just merge it?

**Comment by s0undt3ch** [comment]
I'm using your job to debug the new jenkins slave for prs, we can consider this as tests passed(since you looked at the output) but let me re-trigger until we can get that slave in a good mood?

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Pull request merged**
