### PR TITLE
Added beacon for tracing string within log

### PR DESCRIPTION
**Pull request by iddocohen**
The idea, be able to fire an event with given tag, for a particular regex's within one file.

The beacon configuration would be as follows.

    .. code-block:: yaml

        beacons:
            log:
              file: <path>
              <tag>:
                   regex: <pattern>
              <tag2>:
                   regex: <pattern2>

The salt-minion sends then the raw matched line with given tag to the salt-master.

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @iddocohen 

Thanks very much for this. I have a two initial comments:

I'm curious why you selected a beacon for this instead of an engine. It seems like a beacon would just fire again and again so long as the file it opened contained the string(s) in question whereas an engine would be long-running and could tail the fail and only fire an event when the lines were written out.

Second, the Juniper license here might be problematic for the Salt project. I didn't read it thoroughly but a glance at it suggests it might not be compatible with Apache 2.

Please let me know what you think. Thanks!

**Comment by cachedout** [comment]
@iddocohen Did you see my comments above? Looking forward to your feedback.

**Comment by cachedout** [comment]
@iddocohen I'll need to close this if I don't hear back from you. I'd love to work with you to find a good solution though. Let me know. Thanks.

**Comment by iddocohen** [comment]
@cachedout I am sorry for my late reply, I am just busy with work...

Let me comment on both mentioned points. I chose a beacon approach to solve a use-case where an existing log file, at remote/local site, needs to be monitored for a particular regex. For example, monitor DHCP leases, for a particular IP and trigger (provisioning use-case), monitor an existing log-file and trigger an event, and so on. 

Regarding the code itself. The code has a "tail -f" approach. It will not trigger "every-time finding the regex" in the log but only from its last position until end-of-file (it saves the last position within the beacon object, like wtmp beacon does). 

Regarding licence, please check if it is possible to have Juniper licence included. If not, I will need to do homework, if I can use Apache 2. If both do not work, then please close the request.

**Comment by cachedout** [comment]
@iddocohen Thanks for the reply. Salt is licensed under Apache2 so if you just remove the license here it will fall under the Salt's license. That's what we would prefer.

**Comment by iddocohen** [comment]
@cachedout will come back to you, if it is possible. You agree with code?

**Comment by cachedout** [comment]
@iddocohen Yup, your explanation cleared up my concerns. Code looks good.

**Comment by iddocohen** [comment]
@cachedout ok Juniper licence can be removed. Shall I close this request and request a new pull?

**Comment by iddocohen** [comment]
@cachedout I think that is the best idea to close and re-create a pull because there is also some indent errors. Please suggest what to do.

**Comment by cachedout** [comment]
@iddocohen No need for a new pull request. Just make the needed changes on your local checkout and then push them to your GitHub fork of SaltStack. Doing so will automatically update this pull request.

**Comment by iddocohen** [comment]
@cachedout  I was just thinking you guys are handling it differently :-). So have done so.

**Comment by cachedout** [comment]
OK, hopefully last thing. :]

We need these lint issues cleaned up before we can get this in. https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/7228/violations/file/salt/beacons/log.py/

Thanks!

**Comment by iddocohen** [comment]
@cachedout done

**Comment by cachedout** [comment]
Merged. Thanks so much, @iddocohen !

**Comment by iddocohen** [comment]
@cachedout There is an error which needs to be fixed. Putting new pull request in.

**Pull request merged**
