### PR TITLE
Update kubernetesmod.py

### LINKED ISSUE #62245: [BUG] kubernetes.* is not available
**Description**
When trying to use the `kubernetesmod` or kubernetes state, I get errors similar to the following:
```kubernetes.nodes is not available```

This occurs when using `salt-call` on the minion or `salt` on the master to talk to the minion.

Output from both:

*master*
```
salt 'bgk8smaster.dev.' kubernetes.nodes -l debug kubeconfig=/etc/salt/kubeconfig/bgk8smaster.dev
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Changed git to gitfs in master opts' fileserver_backend list
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt.ena.net
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Using importlib_metadata to load entry points
[DEBUG   ] Override  __grains__: <module 'salt.loaded.int.log_handlers.sentry_mod' from '/usr/lib/python3.6/site-packages/salt/log/handlers/sentry_mod.py'>
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Changed git to gitfs in master opts' fileserver_backend list
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt.ena.net
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/45/55e1a4b4f289d1dfd1dfa3de73b396926018442340bb55a38082ab22ef4967/.minions.p
[DEBUG   ] get_iter_returns for jid 20220629194620976861 sent to {'bgk8smaster.dev'} will timeout at 14:46:25.985021
[DEBUG   ] jid 20220629194620976861 return from bgk8smaster.dev
[DEBUG   ] return event: {'bgk8smaster.dev': {'ret': "'kubernetes.nodes' is not available.", 'out': 'nested', 'retcode': 1, 'jid': '20220629194620976861'}}
[DEBUG   ] Using importlib_metadata to load entry points
[DEBUG   ] LazyLoaded nested.output
bgk8smaster.dev:
    'kubernetes.nodes' is not available.
[DEBUG   ] jid 20220629194620976861 found all minions {'bgk8smaster.dev'}
[DEBUG   ] Closing IPCMessageSubscriber instance
ERROR: Minions returned with non-zero exit code
```

*minion*
```
salt-call --local kubernetes.nodes -l debug
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: bgk8smaster.dev
[DEBUG   ] Using importlib_metadata to load entry points
[DEBUG   ] Override  __grains__: <module 'salt.loaded.int.log_handlers.sentry_mod' from '/usr/lib/python3.6/site-packages/salt/log/handlers/sentry_mod.py'>
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Override  __utils__: <module 'salt.loaded.int.grains.zfs' from '/usr/lib/python3.6/site-packages/salt/grains/zfs.py'>
[DEBUG   ] Elapsed time getting FQDNs: 0.11486482620239258 seconds
[DEBUG   ] LazyLoaded zfs.is_supported
[DEBUG   ] Determining pillar cache
[DEBUG   ] Using importlib_metadata to load entry points
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[INFO    ] The functions from module 'ansible' are being loaded from the provided __load__ attribute
[DEBUG   ] LazyLoaded path.which
[DEBUG   ] Override  __salt__: <module 'salt.loaded.int.module.dracr' from '/usr/lib/python3.6/site-packages/salt/modules/dracr.py'>
[DEBUG   ] Override  __grains__: <module 'salt.loaded.int.module.grains' from '/usr/lib/python3.6/site-packages/salt/modules/grains.py'>
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: bgk8smaster.dev
[DEBUG   ] Using importlib_metadata to load entry points
[DEBUG   ] Could not LazyLoad idem.hub: 'idem' __virtual__ returned False: No module named 'pop'
[DEBUG   ] Override  __salt__: <module 'salt.loaded.int.module.kubeadm' from '/usr/lib/python3.6/site-packages/salt/modules/kubeadm.py'>
[DEBUG   ] Override  __salt__: <module 'salt.loaded.int.module.udev' from '/usr/lib/python3.6/site-packages/salt/modules/udev.py'>
[DEBUG   ] Override  __pillar__: <module 'salt.loaded.int.module.virtualenv_mod' from '/usr/lib/python3.6/site-packages/salt/modules/virtualenv_mod.py'>
[DEBUG   ] DSC: Only available on Windows systems
[DEBUG   ] Module PSGet: Only available on Windows systems
[DEBUG   ] Could not LazyLoad kubernetes.nodes: 'kubernetes.nodes' is not available.
'kubernetes.nodes' is not available.
```

**Setup**
For simplicity, I'm only troubleshooting the module and not the state (since the state will not work if the module does not). Unless otherwise needed, I will focus in on the minion only for simplicity as well.

Minion pip packages:
```
# pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
Babel (2.5.1)
cachetools (4.2.4)
certifi (2022.6.15)
chardet (3.0.4)
contextvars (2.4)
dbus-python (1.2.4)
decorator (4.2.1)
distro (1.4.0)
google-auth (2.8.0)
gpg (1.13.1)
idna (2.5)
immutables (0.15)
isc (2.0)
Jinja2 (2.10.1)
jmespath (0.9.0)
kubernetes (24.2.0)
libcomps (0.1.18)
M2Crypto (0.35.2)
MarkupSafe (0.23)
msgpack (0.6.2)
nftables (0.1)
oauthlib (3.2.0)
perf (0.1)
pip (9.0.3)
ply (3.9)
psutil (5.4.3)
pyasn1 (0.4.8)
pyasn1-modules (0.2.8)
pycurl (7.43.0.2)
pygobject (3.28.3)
PySocks (1.6.8)
python-dateutil (2.6.1)
python-linux-procfs (0.7.0)
pytz (2017.2)
pyudev (0.21.0)
PyYAML (6.0)
pyzmq (19.0.0)
requests (2.20.0)
requests-oauthlib (1.3.1)
rpm (4.14.3)
rsa (4.8)
salt (3004.1)
selinux (2.9)
sepolicy (1.1)
setools (4.3.0)
setuptools (39.2.0)
six (1.11.0)
slip (0.6.4)
slip.dbus (0.6.4)
syspurpose (1.28.29)
urllib3 (1.24.2)
websocket-client (1.3.1)
```

Minion config:
```
# cat /etc/salt/minion
---
grains:
    server_type: k8smaster
    server_role: kubernetes
    environment: dev
    site: dev

master: salt.redacted.domain
```

Please be as specific as possible and give set-up details.

- [ x ] VM (Virtualbox, KVM, etc. please specify) (saltmaster and minion on Cloudstack backed KVM)

  
**Steps to Reproduce the behavior**
- Install salt minion
- Install `kubernetes` using the pip binary that is relevant to the version of Python that salt/minion is using (in my case pip3 or pip3.6)
- Install a basic setup of Kubernetes and a CNI (for me this is `runc`, `containerd`, `weavenet`, `kubelet`). Ensure that the controlplane is in a Ready state.
```
# kubectl get nodes
NAME                      STATUS   ROLES           AGE   VERSION
bgk8smaster.dev Ready    control-plane   5d    v1.24.2
```
- Run `salt-call --local kubernetes.nodes kubeconfig=/path/to/your/kubeconfig.conf`

**Expected behavior**
Expected behavior is that salt will return a list of nodes.

*NOTE*: This is not just for `kubernetes.nodes` -- all other functions fail with a similar error.

**Versions Report**
<details><summary>salt --versions-report</summary>
# salt-call --versions-report
Salt Version:
          Salt: 3004.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Apr 29 2022, 13:46:02)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: almalinux 8.6 Sky Tiger
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-372.9.1.el8.x86_64
        system: Linux
       version: AlmaLinux 8.6 Sky Tiger
</details>

**Additional context**
I am somewhat new to using salt. I still think that I could be doing something wrong, but I've been bashing my head against this for a few days. Documentation around the kubernetesmod setup is a little lacking for my taste, but according to the docs this should be working. (I will be glad to contribute documentation updates if we can get this working).

### PR DESCRIPTION
**Pull request by steaksauce-**
Updating documentation around required python package versions.

What does this PR do?
This PR adds to the kubernetes documentation to reflect the versions of PyYAML and kubernetes needed by pip.

What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/62245

New Behavior
Users should now easily be able to find the required python packge versions to make kubernetesmod work.

Merge requirements satisfied?
[NOTICE] Bug fixes or features added to Salt require tests.

[ * ] Docs
Commits signed with GPG?
No

### CODE REVIEW

**Review by barbaricyawps — DISMISSED** [review]
Thanks for improving the dependencies in the docs.

**Comment by steaksauce-** [comment]
> Thanks for improving the dependencies in the docs.

No problem! I bashed my head on this for a week, figured I might save someone else the trouble.

**Review by MKLeb — DISMISSED** [review]

**Comment by steaksauce-** [comment]
There's ~5 CLI examples that are missing -- I'll work on adding these while I test out the module.

**Comment by steaksauce-** [comment]
@barbaricyawps @MKLeb can I bother one of you for another review? :)

**Review by MKLeb — APPROVED** [review]

**Review by barbaricyawps — APPROVED** [review]
Looks good to me. Thanks!

**Comment by steaksauce-** [comment]
I think this just needs merged (no write access on my end).

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
