### PR TITLE
Added Citrix Netscaler Proxy module and execution modules.

### PR DESCRIPTION
**Pull request by spenceation**
### What does this PR do?
Add new Citrix Netscaler proxy module. This will allow the Netscalers to run as Salt proxies. Also, this module utilizes the direct API and removes dependency of the NSNitro Python library.

This pull request will include all the available API requests. Due to the size, this is distributed to multiple modules.

### What issues does this PR fix or reference?
N/A

### New Behavior
New proxy module for Citrix Netscalers.

### Tests written?
No

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by rallytime** [comment]
Hi @spenceation - Wow! There are a lot of files in here. :) My apologies for not commenting on this sooner. 

Offhand, it looks like there's some lint to take care of, but the test results have timed out. I am also going to see if @mirceaulinic can give some help reviewing this.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by spenceation** [comment]
Hi @rallytime - Thanks for taking a look at this. I was able to clean up the lint issues except for one. This looks like a custom lint check, but I'm not sure exactly what the final issue is.  It seems to error on a blank line? [Lint error](https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/19115/violations/file/salt/proxy/citrixns.py/)

**Comment by rallytime** [comment]
@spenceation Oh! Yeah the PY3 compatibility checked isn't great at showing what the problem is. In the future, you can find it in the console logs. Here's the error and proposed fix:
```
15:24:59 ************* Module salt.proxy.citrixns
15:24:59 salt/proxy/citrixns.py:75: [W1699(incompatible-py3-code), ] Incompatible Python 3 code found. Proposed fix:
15:24:59  
15:24:59  # Import Salt Libs
15:24:59  import salt.exceptions
15:24:59 +from salt.ext.six.moves import range
```
Hopefully that helps :)

**Comment by spenceation** [comment]
Hi @rallytime the lint issues should be resolved now.

**Comment by cachedout** [comment]
This needs to be rebased. It's clearly against the wrong branch. I'm closing this. @spenceation could you please re-submit this? Thanks and sorry for the trouble.

**Pull request closed without merging**
