### PR TITLE
Replace resolv.conf if nameserver is 127.0.0.1

### PR DESCRIPTION
**Pull request by kaaelhaa**
Debian OpenStack images has resolv.conf with "nameserver 127.0.0.1". If not overwritten minion seeding will fail (after a long period of time - network timeout) as no name lookups can be made.
Upon VM boot DHCP settings will overwrite resolv.conf again.

A more elegant approach which probably deserves an issue would be to inject a temporal resolv.conf to the mounted volume and roll back to the original after seeding has finished.

### What does this PR do?
Modified `_check_resolv` to also replace resolv.conf with the minions resolv.conf if the mount point has a resolv.conf with `nameserver 127.0.0.1`

### Previous Behavior
Only replace resolv.conf with the mount points' resolv.conf does not contain any `nameserver` lines.

### New Behavior
Also replace resolv.conf if there is a `nameserver 127.0.0.1` line.

### Tests written?
No

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by damon-atkins** [comment]
Why is this not a bug with the Debian OpenStack images

**Review by garethgreenaway — APPROVED** [review]

**Comment by kaaelhaa** [comment]
@damon-atkins It seems there are no alignment in the resolv.conf across various distributions' cloud images. I've done some digging by mounting the cloud images and inspecting them like the `_check_resolv` function is doing. These are my findings:

| Distribution | resolv.conf contents | Note |
| ----------- | -------------------- | ------- |
| Debian 9 | `nameserver 127.0.0.1` | Handled by this PR |
| Ubuntu 16.04 | Broken symlink | resolv.conf will be replaced by current code |
| CentOS 7 | `nameserver 10.0.2.3` | Will probably fail seeding unless host has access to a DNS server on this IP address |
| Fedora 27 | Empty file | resolv.conf will be replaced by current code |
| OpenSUSE 42 | No resolv.conf file | resolv.conf will be created by current code |

I don't see why this should be a bug in Debians' OpenStack images, as the behaviour is very different across distributions. It however suggests that temporarily replacing resolv.conf would be a better long-term approach, which I'd gladly work on at some point.

**Comment by kaaelhaa** [comment]
Created issue #45344 with a description of the long-term fix for this.

**Comment by damon-atkins** [comment]
@kaaelhaa  pls log an issue with Debian OpenStack.
A resolv.conf should only have something useful in it at all times.

**Comment by rallytime** [comment]
re-run py

**Comment by rallytime** [comment]
Thank you @kaaelhaa and congratulations on your first Salt PR. :)

**Pull request merged**
