### PR TITLE
decode pillar on minion side on receiving

### PR DESCRIPTION
**Pull request by xofyarg**
### What does this PR do?

(WIP) Fix issues when pillar contains non-ascii characters.

Not sure if it's the best place to add, so only RemotePillar is considered. Should put into AsyncRemotePillar as well if confirmed.
### What issues does this PR fix or reference?
saltstack/salt#3436 #32975
### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

Fix a set of encoding issue when non-ascii is used in pillar, e.g. #3436, saltstack/salt#32975

### CODE REVIEW

**Comment by cachedout** [comment]
This looks reasonable to me. Any thoughts, @terminalmage or @thatch45 ?

**Review by cachedout — APPROVED** [review]

**Comment by terminalmage** [comment]
Code looks solid to me.

**Review by thatch45 — APPROVED** [review]
Looks good to me

**Comment by Ch3LL** [comment]
@xofyarg we had to revert your PR here: https://github.com/saltstack/salt/pull/42139 due to the issue caused here: https://github.com/saltstack/salt/issues/42120 . Any chance you can look at this to esnure your issue is resolved and doesn't cause the issue in 42120? Thanks

**Pull request merged**
