### PR TITLE
Reduce digital_ocean_v2 API call frequency

### PR DESCRIPTION
**Pull request by rallytime**
Refs #25431

### CODE REVIEW

**Comment by techhat** [comment]
I'm all for reducing calls, but shouldn't this number be user-defined? Some people with low resources may actually want only 20 at a time.

**Comment by rallytime** [comment]
@techhat Aren't we querying all of the pages anyway at once? I think right now we are getting everything back, but making multiple API calls to do so (where 20 VMs is the page).

**Comment by rallytime** [comment]
@cro suggested that I should add this change to the release notes to help reduce confusion.

**Comment by techhat** [comment]
I agree that 200 is a good default for now. However, there are ways that this can be problematic. What if DO changes their API to not allow calls that big? What if somebody has limited bandwidth (perhaps they're tethered to their phone in a coffee shop)? Making it configurable isn't a huge step, and makes quick fixes easier.

**Pull request merged**
