### PR TITLE
Make nxos guestshell minion work with python3

### PR DESCRIPTION
**Pull request by mikewiebe**
### What does this PR do?

Fixes the NXOS Guestshell minion to work with python3 and updates the NXOS Guestshell minion installation guide.

Please backport this to the Sodium `3001` release.  Without this fix the native minion will not startup in the Guestshell using the python3 RPM.

### Previous Behavior
Saltstack minion would generate an error when when starting up in the guestshell due to apython3 incompatibility.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ x ] Docs
- [ x ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ x ] Tests written/updated

### Commits signed with GPG?
No

### CODE REVIEW

**Review by waynew — CHANGES_REQUESTED** [review]
Hey @mikewiebe thanks for the PR! Looks like there's a bit of code change going on in here, so we'll definitely need some tests to cover those cases. If you need help writing tests you can attend one of the [Test Clinics on Twitch](https://www.twitch.tv/saltstackinc/schedule).

**Comment by mikewiebe** [comment]
@waynew I can certainly add the tests.  I don't believe we have any tests that cover utils currently so this will be a new addition.

Couple of quick questions:

1. Will it be possible to backport this since the native minion will not start in our NX-OS GS without it?
2. I don't understand the build failure above.  These don't look related to my changes.

**Comment by waynew** [comment]
Yeah, there are definitely too many parts of Salt lacking tests 🙃 

But on the plus side, you can use `pytest` to write the tests (stick the files in `tests/pytests/unit/utils/test_nxos.py`, probably). If you check out the most recent Test Clinic recordings I'm pretty sure that you'll see an example on how to start a new test suite. There may even have been one where I did utils as well 🤔 

Yeah, the test failure was just a timeout. Also looks like we're not requiring passing tests on BSD yet. We've also currently got some failures in the upstream setuptools, but we should have a PR to workaround that in soon, so it should be a non-issue by the time you get your tests written 👍

**Comment by mikewiebe** [comment]
@waynew just wanted to let you know that another person from my team @praveenramoorthy will be adding the unit tests for this PR and the functions that we modified in the utils library.

**Comment by mikewiebe** [comment]
@waynew , @praveenramoorthy has completed adding the unit tests and fixed all of the formatting issues but we still see a few failures that don't look like they are related to our changes.

**Comment by mikewiebe** [comment]
Hi @waynew!  Just checking with you again on the failures since these don't appear to be at all related to our changes.  Is there anything else needed to proceed to the next step for this PR?  Thanks!

**Comment by mikewiebe** [comment]
@waynew Checking on this PR again.  We have added new tests and fixed issues that appear to be related to our changes.

**Comment by waynew** [comment]
@mikewiebe Hey, sorry for the late response - I was OOO and am just working to catch up on things. I'll be taking a look through PRs through the rest of this week 👍

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
