### PR TITLE
Make sure tmp_dir does not end in a slash, and remove extra escapes.

### PR DESCRIPTION
**Pull request by ndenev**
Avoid escaping tmp_dir as this causes issues on FreeBSD's tcsh shell (default for root). Also this is more consistent with rest of the code where tmp_dir is not escaped.
Without this provisioning with salt.cloud fails. Example:

**zsh**:

```
[11:23][ndenev@nas:~]%sh -c "( mkdir -p \"/tmp/.saltcloud-786a57cf-507e-4d1b-a1b9-305a047639d2\" && chmod 700 \"/tmp/.saltcloud-786a57cf-507e-4d1b-a1b9-305a047639d2\" )"
[11:23][ndenev@nas:~]%
```

**tcsh**:

```
nas$ sh -c "( mkdir -p \"/tmp/.saltcloud-786a57cf-507e-4d1b-a1b9-305a047639d2\" && chmod 700 \"/tmp/.saltcloud-786a57cf-507e-4d1b-a1b9-305a047639d2\" )"
Unmatched ".
nas$
```

```
 salt --versions-report
           Salt: 2014.7.2
         Python: 2.7.9 (default, Jan  8 2015, 21:47:19)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

### CODE REVIEW

**Comment by rallytime** [comment]
ping @techhat or @s0undt3ch

**Comment by s0undt3ch** [comment]
This will break paths containing spaces... Yeah I know, who uses those :) but we support it...

If its single(`'`), non escaped, quotes does it work for you?

**Comment by ndenev** [comment]
Sure, but I'm not sure those are even working now? There are some other places in this file where tmp_dir is used in root_cmd() calls and is not escaped at all.
I'll test with single quotes, and update the pull request.

**Comment by ndenev** [comment]
Looks like with the updated patch the tests fail on the CentOS test instance. I'll look into this shortly.

**Comment by jfindlay** [comment]
Why not use unescaped double quotes?

**Comment by ndenev** [comment]
Some commands are executed as ```sh -c "xyz"```, so double quotes inside have to be escaped, and this was the case, however this is failing if the current shell is tcsh. Also since it's shell, maybe single quotes are better to avoid variable expansion, etc.

**Comment by jfindlay** [comment]
@ndenev, sounds fine to me.  The [CentOS 7 failed test](https://jenkins.saltstack.com/job/salt-pr-rs-cent7-n/2157/testReport/junit/integration.client.runner/RunnerModuleTest/test_wildcard_auth/) is a known intermittent failure.

**Comment by s0undt3ch** [comment]
Thanks!

**Pull request merged**
