### PR TITLE
make multimaster minionmanager create master_uri_list

### PR DESCRIPTION
**Pull request by mattp-**
### What does this PR do?
a similar snippet of code exists in minion tune_in for letting
masterless mode work / callerClient, unfortunately it isn't hit in
multimaster because multimaster creates N minion objects with a single master: ip
value. This fills in that deficiency.

### Tests written?
no

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by mattp-** [comment]
if I had all the time in the world I'd untangle the master wrangling code in minion tune_in, but that is a significant undertaking

**Comment by waynew** [comment]
I don't see anything (obviously) wrong with this. I'm not super familiar with this area of the codebase, though 🤷‍♂️

**Review by dwoz — COMMENTED** [review]
@mattp- Looks good but I'd love to see some kind of tests with this.

**Comment by mattp-** [comment]
@dwoz sure, I’ll try to sort something out

**Comment by mattp-** [comment]
@dwoz added a test exercising this for ya. the ubuntu passed, seems github api barfed and is hung:
```
11:38:58        OK (total=1076, skipped=57, passed=1019, failures=0, errors=0) 
```
py3 centos7 failure looks completely unrelated.
thanks 👍

**Review by garethgreenaway — APPROVED** [review]

**Comment by terminalmage** [comment]
This needs to be tagged as having a master port, because I chose it at random from the "PRs to port to master" list, spent 20 minutes backporting it, only to realize that it was backported 5 months ago.

**Pull request merged**
