### PR TITLE
Add findup function to slsutil execution module

### PR DESCRIPTION
**Pull request by amendlik**
### What does this PR do?
Add a new function, `findup`, to the slsutil execution module. This function will find the first path matching a filename or list of filenames in a specified directory or the nearest ancestor directory. It provides a feature similar to how Vagrant and Git will start from the current directory locate their configuration/data by traversing ancestor directories.

It was originally written to help state files locate a Jinja file to be imported. Formulas typically contain a `map.jinja` that needs to be included by every state file. However, those state files must import it using the fully qualified path name. Those imports stop working if the the formula is moved/renamed, or even if a state file is moved to another directory.

The `findup` function enables state files to dynamically locate the `map.jinja` file (or any other file) by searching ancestor directories.

### What issues does this PR fix or reference?
Fixes: None

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by Ch3LL — CHANGES_REQUESTED** [review]
Also, would you be willing to add some integration tests (tests/pytests/integration/states?)

**Comment by amendlik** [comment]
@Ch3LL Thank you for the code review - all great advice. I ran into 2 problems:

1. As soon as I moved my test module to `tests/pytests`, it broke `pylint`. See https://github.com/saltstack/salt-pylint/issues/45.
2. I cannot run Nox tests or the pre-commit tasks in my development environment. Both fail with this error:
```
Installing collected packages: wrapt
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.10.11
ERROR: Cannot uninstall 'wrapt'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```
I posted a message about this to the development Slack channel, but received no reply. How do you suggest I proceed?

**Comment by Ch3LL** [comment]
Can you try deleting your `.nox` directory and trying again? Also, if you move the file back does it pass?

**Comment by Ch3LL** [comment]
actually a user ran into this previously here: https://github.com/saltstack/salt/pull/59864#issuecomment-814084280

**Comment by amendlik** [comment]
@Ch3LL I tried deleting the `.nox` directory but that had no effect. I was able to get tests to run by removing `wrapt` in the `requirements` file. That is only a temporary measure and does not fix the `pre-commit` checks, so we still need a solution for that.

**Comment by Ch3LL** [comment]
What version of python are you running nox on?

Also, looks like there is a legitimate test failure on windows that needs to be cleaned up.

**Comment by amendlik** [comment]
> What version of python are you running nox on?
> Also, looks like there is a legitimate test failure on windows that needs to be cleaned up.

Python 3.7.3 in my Debian test environment

@Ch3LL, can you point me to some documentation for setting up a Windows test environment? Running `nox` produces this error:
```
nox > Running session runtests-parametrized-3(crypto=None, transport='zeromq', coverage=False)
nox > Creating virtual environment (virtualenv) using python.EXE in .nox\runtests-parametrized-3-crypto-none-transport-zeromq-coverage-false
nox > Session runtests-parametrized-3(crypto=None, transport='zeromq', coverage=False) raised exception TypeError("'NoneType' object is not subscriptable")
Traceback (most recent call last):
  File "c:\users\amendlik\appdata\local\programs\python\python38\lib\site-packages\nox\sessions.py", line 549, in execute
    self.func(session)
  File "c:\users\amendlik\appdata\local\programs\python\python38\lib\site-packages\nox\_decorators.py", line 83, in __call__
    return super().__call__(*args, **kwargs)
  File "c:\users\amendlik\appdata\local\programs\python\python38\lib\site-packages\nox\_decorators.py", line 53, in __call__
    return self.func(*args, **kwargs)
  File "c:\users\amendlik\appdata\local\programs\python\python38\lib\site-packages\nox\_decorators.py", line 53, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\amendlik\develop\saltstack\salt\noxfile.py", line 403, in runtests_parametrized
    _runtests(session)
  File "C:\Users\amendlik\develop\saltstack\salt\noxfile.py", line 390, in _runtests
    session._runner.global_config.sessions[0].replace("runtests", "pytest")
TypeError: 'NoneType' object is not subscriptable
nox > Session runtests-parametrized-3(crypto=None, transport='zeromq', coverage=False) failed.
nox > Running session runtests-parametrized-3(crypto='m2crypto', transport='zeromq', coverage=False)
```

**Comment by Ch3LL** [comment]
we no longer use the runtests runner. Can you try with `pytest-zeromq-3(coverage=True)`?

**Comment by amendlik** [comment]
Same error:
```
nox > Running session pytest-zeromq-3(coverage=False)
nox > Creating virtual environment (virtualenv) using python.EXE in .nox\pytest-zeromq-3-coverage-false
nox > Session pytest-zeromq-3(coverage=False) was successful.
nox > Running session pytest-parametrized-3(crypto=None, transport='zeromq', coverage=False)
nox > Creating virtual environment (virtualenv) using python.EXE in .nox\pytest-parametrized-3-crypto-none-transport-zeromq-coverage-false
nox > python -m pip install --progress-bar=off -U pip setuptools!=50.*,!=51.*,!=52.*
nox > Session pytest-parametrized-3(crypto=None, transport='zeromq', coverage=False) raised exception TypeError('sequence item 5: expected str instance, NoneType found')
Traceback (most recent call last):
  File "c:\users\amendlik\appdata\local\programs\python\python38\lib\site-packages\nox\sessions.py", line 549, in execute
    self.func(session)
  File "c:\users\amendlik\appdata\local\programs\python\python38\lib\site-packages\nox\_decorators.py", line 83, in __call__
    return super().__call__(*args, **kwargs)
  File "c:\users\amendlik\appdata\local\programs\python\python38\lib\site-packages\nox\_decorators.py", line 53, in __call__
    return self.func(*args, **kwargs)
  File "c:\users\amendlik\appdata\local\programs\python\python38\lib\site-packages\nox\_decorators.py", line 53, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\amendlik\develop\saltstack\salt\noxfile.py", line 514, in pytest_parametrized
    _install_requirements(session, transport)
  File "C:\Users\amendlik\develop\saltstack\salt\noxfile.py", line 301, in _install_requirements
    session.install(*install_command, silent=PIP_INSTALL_SILENT)
  File "c:\users\amendlik\appdata\local\programs\python\python38\lib\site-packages\nox\sessions.py", line 426, in install
    self._run("python", "-m", "pip", "install", *args, external="error", **kwargs)
  File "c:\users\amendlik\appdata\local\programs\python\python38\lib\site-packages\nox\sessions.py", line 318, in _run
    return nox.command.run(args, env=env, paths=self.bin_paths, **kwargs)
  File "c:\users\amendlik\appdata\local\programs\python\python38\lib\site-packages\nox\command.py", line 81, in run
    full_cmd = "{} {}".format(cmd, " ".join(args))
TypeError: sequence item 5: expected str instance, NoneType found
nox > Session pytest-parametrized-3(crypto=None, transport='zeromq', coverage=False) failed.
nox > Ran multiple sessions:
nox > * pytest-zeromq-3(coverage=False): success
nox > * pytest-parametrized-3(crypto=None, transport='zeromq', coverage=False): failed
```

**Comment by amendlik** [comment]
@Ch3LL Perhaps one of the Windows developers could provide some guidance on setting up a dev/test environment on Windows. I have never found any documentation on it.

**Comment by Ch3LL** [comment]
ping @twangboy or @s0undt3ch any idea here ^

**Comment by s0undt3ch** [comment]
@amendlik what's the version of nox?

**Comment by amendlik** [comment]
> @amendlik what's the version of nox?

@s0undt3ch I have 2020.12.31

**Review by Ch3LL — DISMISSED** [review]

**Comment by Ch3LL** [comment]
We are freezing the merge of PRs on master this week so we can try to clean up the flaky test failures? Hopefully we can get this merged in for you next week. Thanks!

**Review by xeacott — DISMISSED** [review]

**Review by dwoz — APPROVED** [review]

**Pull request merged**
