### PR TITLE
Fixing bugs causing errors when creating VM using VMware cloud driver

### LINKED ISSUE #23213: Cloud: Unable to create VM using VMware driver due to hostname error
I saw @nmadhok is working on a VMware driver for Salt-cloud (to replace the vsphere one?). 
Pretty cool! We're using the stable version of Salt-{master|minion} but it appears I can just simply add in the `vmware.py` from develop to the correct folder and it seems to work fine. :)

Querying information works great, and after creating a Template VM and a `cloud.profile` for my VM I issued the command to spin it up:

```
salt-cloud -p vmware-ubuntu14.04 testvm.example.com
```

vSphere shows an active cloning task which around >90% completionfailed with an error about it not having a hostname:
```
A specified parameter was not correct. spec.identity.hostName
```

The VM was created though and had the correct name in the VM-tree.
Salt-cloud displayed an error and did not proceed with the provisioning:

```
[ERROR   ] Error creating testvm.example.com: (vmodl.fault.InvalidArgument) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'A specified parameter was not correct. \nspec.identity.hostName',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   invalidProperty = u'spec.identity.hostName'
}
Error: There was a profile error: Failed to deploy VM
```

Version details:
```
                  Salt: 2014.7.5
                Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
       Apache Libcloud: 0.14.1
 Debian source package: 2014.7.5+ds-1ubuntu1
```

### LINKED ISSUE #23301: VMware cloud driver create function fails with error if network not specified under devices or if network adapter is changed from distributed portgroup to standard network switch
```
[INFO    ] [ salt-oel-1 ] Waiting for clone task to finish [0 s]
[INFO    ] [ salt-oel-1 ] Waiting for clone task to finish [5 s]
[INFO    ] [ salt-oel-1 ] Waiting for clone task to finish [10 s]
[INFO    ] [ salt-oel-1 ] Waiting for clone task to finish [15 s]
[INFO    ] [ salt-oel-1 ] Waiting for clone task to finish [20 s]
[INFO    ] [ salt-oel-1 ] Waiting for clone task to finish [25 s]
[INFO    ] [ salt-oel-1 ] Waiting for clone task to finish [30 s]
[ERROR   ] Error creating salt-oel-1: (vim.fault.NicSettingMismatch) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'fault.NicSettingMismatch.summary',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   numberOfNicsInSpec = 0,
   numberOfNicsInVM = 1
}
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/vmware.py", line 1975, in create
    _wait_for_task(task, vm_name, "clone", 5, 'info')
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/vmware.py", line 673, in _wait_for_task
    raise task.info.error
vim.fault.NicSettingMismatch: (vim.fault.NicSettingMismatch) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'fault.NicSettingMismatch.summary',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   numberOfNicsInSpec = 0,
   numberOfNicsInVM = 1
}
[ERROR   ] Caught Exception, terminating workers
TRACE: 'bool' object has no attribute 'pop'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 54, in _call
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 2188, in create_multiprocessing
    output.pop('deploy_kwargs', None)
AttributeError: 'bool' object has no attribute 'pop'



Error: There was a query error: Exception caught
Caught Exception, terminating workers
TRACE: 'bool' object has no attribute 'pop'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 54, in _call
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 2188, in create_multiprocessing
    output.pop('deploy_kwargs', None)
AttributeError: 'bool' object has no attribute 'pop'
```

Fix for this coming in soon!

### PR DESCRIPTION
**Pull request by nmadhok**
Fixed bug that caused hostname error when using FQDN as the vm name
Fixed bug that caused error during creation of VM if `network` was not specified under devices
Fixed bug that caused error during creation of VM if the present network adapter was edited from distributed virtual portgroup to a standard network switch

Fixes #23213
Fixes #23301

### CODE REVIEW

**Comment by syphernl** [comment]
Hmm, this change now requires a

**Comment by syphernl** [comment]
Hmm, it seems that this change now requires a `switch_type` parameter to be defined under the VM's NIC's?

Also, spinning up a new VM results in an error:
```
[ERROR   ] Error creating testvm.example.com: exceptions must be old-style classes or derived from BaseException, not NoneType
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 1908, in create
    _wait_for_task(task, vm_name, "clone", 5, 'info')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/vmware.py", line 608, in _wait_for_task
    raise task.info.error
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
Error: There was a profile error: Failed to deploy VM
```

**Comment by nmadhok** [comment]
@syphernl Also make sure you you change ``type`` to ``adapter_type``. Please run in debug mode and paste the output if it still fails.

**Comment by syphernl** [comment]
@nmadhok There is no `type` (or `adapter_type`) in our profile, this was optional and defaults to VMXNET3 right?

The only `type` I have is for the SCSI Controller.

**Comment by nmadhok** [comment]
@syphernl Yes that's the default. In that case you don't have to specify it. Can you try to create the VM again in debug log level and paste the output?

**Comment by nmadhok** [comment]
@syphernl Also, can you open up a new issue and paste the information there? Please make sure to include the profile you're using as well.

**Pull request merged**
