### PR TITLE
Add syndic forward job log

### PR DESCRIPTION
**Pull request by pengyao**
### What does this PR do?

Add syndic forward job log

### What issues does this PR fix or reference?

No

### Previous Behavior

No log for syndic forwarded job.

### New Behavior

Add debug log for syndic forwarded job. It will more clearly to debug syndic

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by waynew** [comment]
re-run py3-windows-2016

**Review by DmitryKuzmenko — APPROVED** [review]

**Comment by sagetherage** [comment]
@pengyao please rebase this against the master branch

**Comment by sagetherage** [comment]
Reviewed in Grooming 2021-APR-05 could port to master considering

**Comment by sagetherage** [comment]
@pengyao would you rebase this against the master branch?

Discussed in Grooming 2021-APR-19 it has been 2 weeks and we have not heard anything on this PR. I will leave it open for 2 more weeks, but we are considering closing.

**Comment by pengyao** [comment]
Rebase master branch with #60054, close this PR

**Pull request closed without merging**
