### PR TITLE
[2017.7] Introduce pre-commit

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
Introduce pre-commit into the workflow.
Right now, it has some bare minimum checks because once pre-commit is enabled for a repo, it will complain about missing configuration.
To solve that, we add pre-commit to all active branches(again, a minimal setup).
Additional pre-commit checks will land most likely only on develop and some documentation about it still needs to be written.

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by terminalmage** [comment]
What happened to the line endings in so many of these files?

**Comment by s0undt3ch** [comment]
The pre-commit fixes were applied.
* No mixed line endings.
* A new line at the end of file
* Strip trailing white-space

**Comment by s0undt3ch** [comment]
Once pre-commit is installed locally(one time setup), the above checks/fixes will be enforced for all the changed files being committed.

**Review by garethgreenaway — APPROVED** [review]

**Comment by terminalmage** [comment]
OK thanks... that wasn't clear from the commit message, and I was also (incorrectly) thinking that line-ending/noeol changes would get some other visual distinction in the diff, like you see when removing trailing whitespace.

**Comment by Ch3LL** [comment]
@s0undt3ch does this still need to be merged here since 2017.7.9 will be the last bug fix release?

**Comment by s0undt3ch** [comment]
Nope.

**Pull request closed without merging**
