### PR TITLE
Fix base64 encoding/decoding of Secrets in Kubernetes module

### LINKED ISSUE #55292: Kubernetes Secrets Fail To Base64 Encode Under Python 3
### Description of Issue
Kubernetes secrets are not correctly base64 encoded under Python 3. An error is generated:
```
local:
----------
          ID: test-secret
    Function: kubernetes.secret_present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/Users/<redacted>g/tools/saltstack/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/Users/<redacted>g/tools/saltstack/salt/loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "/Users/<redacted>g/tools/saltstack/salt/states/kubernetes.py", line 583, in secret_present
                  **kwargs)
                File "/Users/<redacted>g/tools/saltstack/salt/modules/kubernetesmod.py", line 1358, in replace_secret
                  data[key] = base64.b64encode(data[key])
                File "/Users/<redacted>g/tools/python/lib/python3.7/base64.py", line 58, in b64encode
                  encoded = binascii.b2a_base64(s, newline=False)
              TypeError: a bytes-like object is required, not 'str'
     Started: 13:32:56.827595
    Duration: 22.805 ms
     Changes:
```

### Setup
Example sls:
```
test-secret:
  kubernetes.secret_present:
    - namespace: default
      metadata:
        name: test-secret
      data:
        tls.crt: test cert data
        tls.key: test key data
```

### Steps to Reproduce Issue
Execute the above sls using state.sls and receive the error

### Versions Report
This bug has been reproduced against `develop`, `2018.3`, and `2019.2` branches:
```
Salt Version:
           Salt: 2019.2.0-339-g779bc17

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: 4.0.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.4 (default, Sep 23 2019, 10:32:33)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.1.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 18.7.0
         system: Darwin
        version: 10.14.6 x86_64
```

### PR DESCRIPTION
**Pull request by streamler**
### What does this PR do?
This PR is a first attempt to fix #55292 . Handling Kubernetes secrets has always been broken on Python >= 3.5 due to a change in the signature of *base64.b64encode* (and *base64.b64decode*).

Python 3.4 : https://docs.python.org/3.4/library/base64.html#base64.b64encode
Python 3.5 : https://docs.python.org/3.5/library/base64.html#base64.b64encode

The fix consists in converting string to bytes and then, encode byes into base 64 when Python version >= 3.5. No behavior change when Python version < 3.5.

Why it is a first attempt? Because Kubernetes Secrets are actually binary objects (manipulated thanks to base64 encoding). They are not necessarily UTF-8 strings, or any strings. We could imagine having a PNG image as secret for example (sure it's far from common). This is clearly documented here: https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1Secret.md

### What issues does this PR fix or reference?
Fixes: #55292

### Previous Behavior
Kubernetes Secrets management was broken when Python version >= 3.5

### New Behavior
Kubernetes module now handles UTF-8 string Secrets when Python version >= 3.5

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by anitakrueger** [comment]
What does it take to get this PR merged? We have run into this issue in our production environment and the PR seems to fix it, but I had to apply it manually.

**Comment by anitakrueger** [comment]
Any news on this PR @twangboy @streamler ?

**Comment by streamler** [comment]
Hello @anitakrueger ,
Absolutely no news on my side. I also don't know why this pull request is stuck...

**Comment by anitakrueger** [comment]
@twangboy @waynew @sagetherage Would you mind looking into this PR please and see what it takes to get this merged? The kubernetes module has been broken because of this for more than half a year now.

**Comment by L4rS6** [comment]
Any chance that this PR will be checked and merged? I'm running in to the same issue.

**Comment by Tontaube** [comment]
Is it possible that this pr needs a rebase? Anything we can help with? Running in the same issue..

**Review by twangboy — CHANGES_REQUESTED** [review]
Please provide a test case for this change.

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open t if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
