### PR TITLE
fix blockdev.tune issue, where blockdev.tune doesn't report changes for ...

### PR DESCRIPTION
**Pull request by RobertFach**
...read-write option and where it didn't translate boolean options properly, causing the underlying blockdev call to fail, fixes issue #21543

### CODE REVIEW

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
@RobertFach Mind grabbing that lint failure? https://jenkins.saltstack.com/job/salt-pr-lint-n/2909/violations/file/salt/modules/blockdev.py/

The other test failures are unrelated.

**Comment by RobertFach** [comment]
Yup, sorry, didn't had yet the time to look for lint issues. Let me fix my fix :)

**Comment by RobertFach** [comment]
Note: This pull request is included in #21587

**Pull request merged**
