### PR TITLE
Master Syndic feature

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
@cachedout 
Salt syndic functionality is moved to master workers.
Scripts/salt-syndic now prints a warning message and exits immediately. To stat syndic just start master with syndic_master option set in config.
Also there is one extra-option `syndic_forward_sync` that is True by default. In this case syndic forwards collected events with sync-wrapped request channel as it was before and as minion does. If the option is set to False syndic forwards events using async channel, probably it could help in high load cases.

### CODE REVIEW

**Comment by cachedout** [comment]
I'll start leaving comments in-line. I've also sent a fix to your privately to fix the issues with the test suite starting.

I'll also cc: @jacksontj and @skizunov who might be interested in looking at this before we get this merged.

Thanks!

**Comment by skizunov** [comment]
It looks fine to me.

**Comment by jacksontj** [comment]
I like the concept (fewer processes, yay!) but from my quick reading, I don't quite understand the `slave` flag being passed around. It seems like we're basically having the master process just create the syndic process (same class etc) right?

**Comment by DmitryKuzmenko** [comment]
@jacksontj no, syndic functionality is integrated to the master workers. Syndic has 2 main functions:
1. Connect to the upstream master(s) and forward jobs to the local master.
2. Get returns and events from the local master and forward to the upstream master.
And the 2nd function works good for multiple workers by workers design: each event is handled once by the only one of the workers, handler calls syndic method that schedules the event forwarding.
But the 1st function should be done by the only one process: it could be a special separate master subprocess or if it's done inside worker process then the only one worker have to connect to the upstream master. Or any job will be multiplicated by the worker count.
I thought that it's not a good idea to have additional master subprocess for this and made one worker "master" and others "slave". Slave workers just don't connect their Syndic to the upstream master. If it will cause performance issues it could be reworked, but I don't expect this: worker could be overloaded on sending jobs and receiving events to/from a lot of minions, but there are not such a big count of upstream masters.

**Comment by cachedout** [comment]
@DmitryKuzmenko FYI. Looks like some merge conflicts.

**Comment by DmitryKuzmenko** [comment]
Thank you @cachedout 
Short changelist:
* removed 'syndic_forward_sync' config option: now syndic always forwards asynchronous (never block io_loop) The only synchronous operation Syndic does now is auth on the upstream master.
* aggregate returns on send (less upstream master load)
* don't publish new returns until the previous publish has done (less upstream master load)
* fixed bug with double sending requests through REQ-REP sockets.
TBD:
* test Salt still correctly handling timeouts with ZeroMQ transport.
* update MultiMaster Syndic code: now it lacks the 3rd point

**Comment by cachedout** [comment]
@DmitryKuzmenko Is this now ready to be re-tested with a large number of minions?

**Comment by DmitryKuzmenko** [comment]
@cachedout not in MultiSyndic mode yet.

**Comment by cachedout** [comment]
@DmitryKuzmenko Sounds good. Let me know.

**Comment by cachedout** [comment]
Ping @junster1. Any chance you could pull down the latest changes here and retest this?

**Comment by junster1** [comment]
Yes, will pull tomorrow and throw some load at it.

**Comment by DmitryKuzmenko** [comment]
@junster1 FYI, I've just pushed update that makes multi master syndic working.
Now upstream master doesn't overloaded because returns are aggregated. Also timeouts handled correctly, so if you see the timeout message it's not fatal. It could be verified by running ```salt``` cmd with ```--summary``` flag. It will provide statistic report: how much minions respond, not respond and so on.

If you'll still get a lot of timeout messages try to increase ```return_retry_timer``` and ```return_retry_timer_max```. The actual timeout is a random between these values. Default values are 5 and 10.

**Comment by DmitryKuzmenko** [comment]
@cachedout could you please take a closer look to the changes I've done in transport modules? There was a bug when reusing of REQ channel produced the second request sending before the first reply is received. But in ZeroMQ transport there also some tricky logic with timeouts, not sure my changes are 100% right. (But at least it works =))

**Comment by cachedout** [comment]
@junster1 Any updates on the performance of this one?

**Comment by cachedout** [comment]
Refs https://github.com/saltstack/qa/issues/108

**Comment by cachedout** [comment]
We're holding here until we get a full test plan delivered from QA.

**Comment by cachedout** [comment]
Now that we've branched 2016.3, we're ready to get this in for Carbon, I think.

@DmitryKuzmenko Could you rebase this? I'd like to merge this later this week.

**Comment by DmitryKuzmenko** [comment]
@cachedout will do

**Comment by DmitryKuzmenko** [comment]
@thatch45 BTW, after I've updated the syndic to work asynchronously it looks there's no need to move it into master's workers processes. Async code works good and looses nothing because always listens master events.
Do we still need to have syndic inside master by some another reason? If not all I should rebase from here is support of events aggregation and bunch sending to the MoM.

**Comment by thatch45** [comment]
Nope, I think you are good

**Comment by DmitryKuzmenko** [comment]
@thatch45 got it. So I'll update this patch.

**Comment by DmitryKuzmenko** [comment]
This PR was broken-down to a number of more clear and simple updates: #31962, #31966, #31993 and #32650.
Those PRs completely replaces this one so it could be closed.
The only thing containing here that wasn't included is "syndic as a part of MWorker". But since Syndic was updated to be asynchronous this is not needed anymore because the main reliability problem was caused by Syndic's synchronous nature: it wasn't reading the bus while was sending (or trying to send) events to the upstream master.

**Pull request closed without merging**
