### PR TITLE
Merge forward from 2015.8 to develop

### PR DESCRIPTION
**Pull request by basepi**
Merge forward from 2015.8 to develop

```
Conflicts:
    salt/minion.py
    salt/modules/network.py
    salt/scripts.py
    salt/states/file.py
    salt/states/git.py
    salt/utils/event.py
```

### CODE REVIEW

**Comment by cachedout** [comment]
There's a lint error in one of the files that had a merge conflict. That's a little worrisome. Could you investigate before we merge this?

**Comment by basepi** [comment]
Wasn't actually a bad merge conflict, it was a bug in the original pull request I think. Pushed a commit that should fix it, I'm going to go fix it in 2015.8 as well.

**Comment by basepi** [comment]
Nevermind, no bug in 2015.8. Just an interesting interaction between changes made in 2015.8 and changes made in develop. Should be fixed in any case.

**Comment by cachedout** [comment]
Sweet! Thanks, sir.

**Pull request merged**
