### PR TITLE
New cmd.shell_info. Fixed win_dsc & win_psget  Slowdown of Minion (36252) Add defensive programming to win_dsc & win_psget

### PR DESCRIPTION
**Pull request by damon-atkins**
### What does this PR do?
1. Issue:  Carbon Release Fix for #36252 `win_dsc` & `win_psget` both called powershell binary to find out the version number of powershell. Powershell on windows as a large startup overhead. Also output a lot of errors when running salt-call
   Solution:  Add cmd.shell_info to check the windows registry and return powershell version and other information, changed `win_dsc` & `win_psget`  to use  `cmd.shell_info('powershell')`
2. Issue: `win_dsc` & `win_psget` `_pshell` function called `cmd.shell` which just provides `stdout`and not error reporting or stderr.
   Solution:  Change to use `cmd.run_all` and if a non zero return code is return raise an error and report back stdout, stderr and returncode.  Update  JSON Conversion depth from the default of 2 to 2147483647 (max 32bit int)
3. Added new function `cmd.shell_info`. This returns version information for various shells and `#!`. It includes support for bash, cmd, perl, php, powershell, python, ruby and zsh. The reported data includes  installed True or False (i.e. found),  version str, major version str, and major minor version str. If an issue happens it will also report error and stdout (which includes stderr)
4. Both `win_dsc` & `win_psget` provided a `psversion` function this has been depreciated. As `win_dsc` & `win_psget` are not available unless  Powershell 5+ is installed.
### What issues does this PR fix or reference?
#36252 Windows Slow Down win_psget & win_dsc determine version is costly, Change to Registry
### Previous Behavior

Windows Slow Down win_psget & win_dsc determine version is costly, Change to Registry

```
C:\salt>salt-call -l info dsc.psversion
[INFO    ] cmdmod._run Executing command 'Powershell -NonInteractive "$PSVersionTable.PSVersion.Major | ConvertTo-Json"' in directory 'C:\Users\djatkins'
[INFO    ] cmdmod._run Executing command 'Powershell -NonInteractive "$PSVersionTable.PSVersion.Major | ConvertTo-Json"' in directory 'C:\Users\djatkins'
local:
    5
```
### New Behavior

```
C:\salt>salt-call -l info psget.psversion
[WARNING ] __init__.warn_until C:\salt\bin\lib\site-packages\salt\modules\win_psget.py:90: DeprecationWarning: The 'psversion' has been deprecated and has been replaced by 'cmd.shell_info'.

local:
    5
```

Powershell on windows reports some extra info

```
C:\salt>salt-call cmd.shell_info powershell
local:
    ----------
    applicationbase:
        C:\Windows\System32\WindowsPowerShell\v1.0
    consolehostassemblyname:
        Microsoft.PowerShell.ConsoleHost, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, ProcessorArchitecture=msil
    consolehostmodulename:
        C:\Windows\System32\WindowsPowerShell\v1.0\Microsoft.PowerShell.ConsoleHost.dll
    crlversion:
        4.0.30319
    installed:
        True
    path:
        C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    pscompatibleversions:
        1.0, 2.0, 3.0, 4.0, 5.0
    pspluginwkrmodulename:
        C:\Windows\System32\WindowsPowerShell\v1.0\system.management.automation.dll
    psversion:
        5.0.10586.0
    version:
        5.0.10586.0
    version_major:
        5
    version_major_minor:
        5.0
```

The following is example of the more standard output for shells etc.

```
C:\salt>salt-call cmd.shell_info cmd
local:
    ----------
    installed:
        True
    path:
        C:\WINDOWS\system32\cmd.exe
    version:
        10.0.10586
    version_major:
        10
    version_major_minor:
        10.0
```

```
windowsNEW:
    ERROR: Issue executing powershell Find-Module | ConvertTo-Json -Depth 2147483647. Additional info follows:

    retcode:
        1
    stderr:
        Exception calling "ShouldContinue" with "2" argument(s): "Windows PowerShell
        is in NonInteractive mode. Read and Prompt functionality is not available."
        At C:\Program
        Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:5908 char:8
        +     if($Force -or $PSCmdlet.ShouldContinue($shouldContinueQueryMessag ...
        +        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
            + FullyQualifiedErrorId : PSInvalidOperationException

        Find-Module : NuGet provider is required to interact with NuGet-based
        repositories. Please ensure that '2.8.5.201' or newer version of NuGet
        provider is installed.
        At line:1 char:1
        + Find-Module | ConvertTo-Json -Depth 2147483647
        + ~~~~~~~~~~~
            + CategoryInfo          : InvalidOperation: (:) [Find-Module], InvalidOper
           ationException
            + FullyQualifiedErrorId : CouldNotInstallNuGetProvider,Find-Module
    stdout:

WindowsOLD:
    Passed invalid arguments to dsc.avail_modules: string indices must be integers, not str

        List available modules in registered Powershell module repositories.

        desc : False
             If ``True``, the verbose description will be returned.

        CLI Example:

        .. code-block:: bash

            salt 'win01' dsc.avail_modules
            salt 'win01' dsc.avail_modules desc=True

```
### Tests written?

No.  Original Author should test the code. i.e. win_psget @tonybaloney and win_dsc @twangboy or @UtahDave

### CODE REVIEW

**Comment by damon-atkins** [comment]
Hi @Ch3LL this is ready to be test

**Comment by damon-atkins** [comment]
Or @meggiebot this can be tested and then merged into Carbon

**Comment by cachedout** [comment]
@UtahDave and @twangboy could you both review this? Thank you.

**Comment by twangboy** [comment]
@cachedout Seems to be working fine. Much faster.

**Pull request merged**
