### PR TITLE
[oxygen] Track the next scheduled fire time and when jobs are skipped.

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Track the next scheduled fire time and when jobs are skipped.

### What issues does this PR fix or reference?
#45865

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by cachedout — APPROVED** [review]

**Comment by cachedout** [comment]
Tests?

**Comment by garethgreenaway** [comment]
@cachedout I have some tests and some other changes to push to this PR.

**Comment by cachedout** [comment]
@garethgreenaway Would it be a good idea to add a unit test specifically for the `_check_max_running` function?

**Comment by alexpeay** [comment]
I am assuming this is the Max Parallel portion of the code, right? If there is a way to differentiate when a job is skipped due to a user request to skip vs a skip due to already running at the Max Parallel level (effectively a system Skip) that would be great.

**Comment by garethgreenaway** [comment]
@alexpeay There are a few different skip reasons that this change introduces including the maxrunning reason, the others include when the job is in a time range specified by `skip_during_range` and when a job is set to skip at a specific time using `skip_explicit`.

**Pull request merged**
