### PR TITLE
Update PillarStack stack.py to latest upstream version

### PR DESCRIPTION
**Pull request by bbinet**
Provides a fix for Windows minions:
https://github.com/bbinet/pillarstack/pull/29

And the following enhancements:
https://github.com/bbinet/pillarstack/pull/26
https://github.com/bbinet/pillarstack/pull/27

### CODE REVIEW

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by n-rodriguez** [comment]
Hi! Do you know when this patch will be released?
A new version has been released a few days ago (2016.11.4) but without the patch :(

**Comment by bbinet** [comment]
Will be available in the coming major release (Nitrogen).

**Comment by n-rodriguez** [comment]
Ok. Thank you!

**Pull request merged**
