### PR TITLE
Only pop the key if the key exists otherwise do nothing

### PR DESCRIPTION
**Pull request by nmadhok**
If we pop the key when it doesn't exist, it gives the following error:

```
[ERROR   ] Caught Exception, terminating workers
TRACE: 'bool' object has no attribute 'pop'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 60, in _call
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 2207, in create_multiprocessing
    output.pop('deploy_kwargs', None)
AttributeError: 'bool' object has no attribute 'pop'



Error: There was a query error: Exception caught
Caught Exception, terminating workers
TRACE: 'bool' object has no attribute 'pop'
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 60, in _call
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 2207, in create_multiprocessing
    output.pop('deploy_kwargs', None)
AttributeError: 'bool' object has no attribute 'pop'
```

### CODE REVIEW

**Comment by nmadhok** [comment]
@rallytime Do not merge yet. Still have to test a few cases.

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by nmadhok** [comment]
Ready to be merged!

**Comment by rallytime** [comment]
Hrm. Pylint didn't run.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by nmadhok** [comment]
@rallytime Ping

**Pull request merged**
