### PR TITLE
Adding a little module as a helper for template rendering on the fly

### PR DESCRIPTION
**Pull request by mirceaulinic**
### What does this PR do?

Nothing really spectacular, this is sort of in-line with other little modules I proposed in the past, e.g., https://github.com/saltstack/salt/pull/39099 or https://github.com/saltstack/salt/pull/42018, so not mind blowing this time either. But I often need to render various templates, and rather than saving the rendered result into a file, I need the text. And here's exactly what this function does, aiming to avoid repeating this code over and over again, and hopefully saving other people's time as well. Being an execution module, can easily be used also from the CLI for checks, or endless alternatives. Hope you're also finding it helpful.

### CODE REVIEW

**Comment by gtmanfred** [comment]
This looks good, but what does it offer that slsutil.renderer doesn't? Or could the context and default stuff be added to slsutil?

**Comment by mirceaulinic** [comment]
`slsutil.render` tries to return an object, the Python representation of some structured input (data), while this one returns text.

**Comment by mirceaulinic** [comment]
Oh, damn, you are right @gtmanfred. Silly me... I had this module in my branch for other reasons actually (the support for the Salt fileserver has been added to 2018.3 only, and I'm still running 2017.7).

**Comment by mirceaulinic** [comment]
Reopening as discussed in private: `slsutil.render` seems to try to parse the data instead of trying to render: `salt '*' slsutil.renderer https://bit.ly/2yuSs2Y hostname=aaa default_renderer=jinja`

**Review by gtmanfred — APPROVED** [review]
This adds the ability to test templates for other other stuff besides sls files

**Review by rallytime — APPROVED** [review]

**Pull request merged**
