### PR TITLE
Better check for pillar for jinja templating

### PR DESCRIPTION
**Pull request by terminalmage**
Since `self.opts['pillar_roots']` is assigned to `self.opts['file_roots']`,
an "is" comparison here will be sufficient to let us know that it is
pillar that is being requested.

This should be refactored eventually so that the search path is an
argument, but for now this should fix any lingering issues.

### CODE REVIEW

**Comment by terminalmage** [comment]
This does not fix the issue, hold off on merging.

**Comment by terminalmage** [comment]
This has been rebased, I am testing to make sure this works.

**Comment by thatch45** [comment]
Looks like it does not work.....

**Comment by terminalmage** [comment]
It does work, so this might just be some weirdness in the tests. I will investigate.

**Comment by terminalmage** [comment]
Ahh, I see what caused the failures. I should have been referencing ``self.opts`` instead of ``opts``. ``opts`` works when I am running salt, but not in the mocked opts dict in the test suite. Changing these references so they use ``self.opts`` should fix this.

**Comment by terminalmage** [comment]
OK, it was more than that actually, it was the fact that utils/jinja. I added a few commits, we should see the jinja tests clear up.

**Comment by terminalmage** [comment]
Odd, now we have test failures in the cache loader. Perhaps for the same reason as the template test failures. Investigating.

**Comment by terminalmage** [comment]
OK, just pushed a fix for those tests, waiting on results now.

**Comment by thatch45** [comment]
Cool, this is #20000 !!

**Comment by terminalmage** [comment]
@thatch45 Jenkins seems to be on the fritz, but all Jinja tests are now all passing on my laptop.

**Comment by thatch45** [comment]
I think jenkins got hit too hard in the head or something

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Test failures are unrelated.

**Comment by terminalmage** [comment]
OK, looks like it's good to merge then.

**Pull request merged**
