### PR TITLE
draft support for parsing slot results and appending text

### PR DESCRIPTION
**Pull request by mchugh19**
### What does this PR do?
Extends slot syntax to support parsing resulting dictionaries and appending text. Note: the appending process only functions on slot results which are strings.

Next steps:
- Since python structures are now injected with raw unicode: `{u'shell': u'/bin/bash'}` we could also force to json output if desired.

### What issues does this PR fix or reference?
#50462
#46771

### Previous Behavior
Using `__slots__` with modules which return dictionaries required custom modules to parse result
Also, unable to append text

### New Behavior
Support dictionary results by appending the slot function with period delimited dictionary keys to traverse
`__slot__:salt:user.info(root).shell` returns `/bin/bash`

Support appending data by using a tilde delimiter followed by text
` __slot__:salt:user.info(root).shell ~ /appended~` returns `/bin/bash/appended~`

### Tests written?
Yes

### Commits signed with GPG?
No

### CODE REVIEW

**Review by dwoz — CHANGES_REQUESTED** [review]
@mchugh19 Can you please add a test or two that cover this?

**Comment by mchugh19** [comment]
Tests have been added for the traverse and append functions. 

In thinking about this a little bit more, the parsing for the append function looks for a tilde character and appends everything afterwards. It is possible that the slot text itself could contain that character as you might have `cmd.run('ls ~user')` or something. Should this behavior be updated to a more complicated regex?

**Review by mchugh19 — COMMENTED** [review]
Tests added

**Review by dwoz — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Comment by mchugh19** [comment]
@DmitryKuzmenko you should take a look here as well

**Review by DmitryKuzmenko — APPROVED** [review]

**Review by thatch45 — APPROVED** [review]

**Pull request merged**
