### PR TITLE
minion: don't hang on compound-command

### LINKED ISSUE #44280: compound command -- minion hangs
### Description of Issue/Question

While running compound-command (that takes some time), the minion becomes unresponsive.

### Steps to Reproduce Issue

```
salt $(hostname) test.sleep,cmd.run 10,hostname &
sleep 1 ; time salt $(hostname) grains.get fqdn
```

The 1 second sleep in here to ensure the minion actualy started the compound command.

Expected behaviour:

  * The `grains.get` should return about immediately (after the 1s delay)

Observer behaviour:

  * The `grains.get` takes an additional 9s (`sleep 10` from compound command, minus the `sleep 1` delay) before returning

### Versions Report

```
Salt Version:
           Salt: 2016.11.6
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.1 
        machine: x86_64
        release: 3.14.79-cerberhost-0.11.1deb8+nbs20170131-grsec
         system: Linux
        version: debian 9.1 
```

From the code, it seems to also affect latest develop versions.

(Incoming PR attempt)

### PR DESCRIPTION
**Pull request by ze42**
### What does this PR do?

Currently, launching long-running compound-command seems to hang, and prevent any other command from being handled by the minion.

### What issues does this PR fix or reference?
Fixes: #44280 

### Previous Behavior
Compound-command blocks until finished.

### New Behavior
Compound-command forks like single commands, letting minion handle other commands.

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by rallytime** [comment]
This looks good to me, but I am thinking that rather than pulling all of that code from `_thread_return` and putting it here, maybe a helper function would be better so we don't have to maintain any changes with this behavior in two places.

Thoughts @ze42 and @cachedout?

**Comment by cachedout** [comment]
I'm really struggling with this one. On one hand, I can understand how it would be surprising that a minion would basically queue jobs in the way that you've pointed out.

On the other hand, incurring the overhead of a process daemonization for _every_ case here seems like a big price to pay and I'm not truly convinced that it's worth the tradeoff.

I'm going to bring some others into this issue for discussion.

Paging @saltstack/team-core and @thatch45

**Comment by ze42** [comment]
@rallytime I wouldn't mind having it in a decorator, though to be honest, I'm not too sure what those functions really do.

@cachedout Well, launching a *single* command already launches the daemonization. Why should a *compound*-command should not behave the same? If you think not all commands should have the daemonization, it surely should also be applied to current single-commands...



As a current workaround for my specific needs, I've built a module that takes multiple commands, and launch them one after an other. Calling that module in a single command launches the necessary daemonization I need, and helps until something adequate gets to our minions.

**Comment by DmitryKuzmenko** [comment]
@cachedout I understand you, but I agree with @ze42: why we run compound and single commands in a different ways?
Moreover it looks `_thread_multi_return` and `_thread_return` should be the same function where the single return is a specific case of a multi- version.

**Review by DmitryKuzmenko — APPROVED** [review]

**Review by thatch45 — APPROVED** [review]
This is the right way to do it, hands down

**Pull request merged**
