### PR TITLE
Improving libvirt

### PR DESCRIPTION
**Pull request by isbm**
This PR is for `libvirt` and virtual machines infrastructure.
It does the following:
- Implements missing functionality for the snapshots on `libvirt` enabled systems. Working with snapshots is now like with `virsh`, except it makes better automatic names unless you gave your own.
- Implements a cool `virt` states, where included all basic functionality to `start`, `stop`, `reboot`, take a `snapshot` of a certain domains, `revert` to a certain snapshot or previous, addressed by a wildcards or directly.
- Fixes the terminology so it stays consistent with the `libvirt`.
- Drops confusing function names (create and destroy) that are specific only to the libvirt, were aliased for the same reasons and are anyway different for other systems, like jails on BSD or zones on SmartOS. From now on `virt.start` for start the VM and `virt.stop` for stop the VM everywhere.
- Bonus: cleans up sibling module for SmartOS (more improvements on this module yet to come!) synchronizing with the main `virt` module. I haven't done much here (yet), but I'd like to have full zones support on Solaris/SmartOS.
### Examples

Perform snapshot reversion on all domains that matches `te*` pattern:

```
te*:
  virt.reversed
```

Result:

```
          ID: te*
    Function: virt.reverted
      Result: True
     Comment: Domains has been reverted
     Started: 08:56:06.079434
    Duration: 1155.665 ms
     Changes:   
              ----------
              ignored:
                  |_
                    ----------
                    domain:
                        test01
                    issue:
                        No more previous snapshots available
              reverted:
                  |_
                    ----------
                    current:
                        test02-20150715-072208
                    deleted:
                        N/A
                    domain:
                        test02

```

Delete snapshots:

```
salt 'virtux.suse.com' virt.delete_snapshots testsuite testsuite-20150714-103959
virtux.suse.com:
    ----------
    available:
        ----------
        testsuite:
            |_
              ----------
              created:
                  2015-07-14 10:37:11
              name:
                  testsuite-20150714-103711
              running:
                  True
            |_
              ----------
              created:
                  2015-07-14 09:36:36
              name:
                  testsuite-20150714-093636
              running:
                  True
    deleted:
        ----------
        testsuite-20150714-103959:
            ----------
            created:
                2015-07-14 10:39:59
            name:
                testsuite-20150714-103959
            running:
                True
```

### CODE REVIEW

**Comment by jfindlay** [comment]
@isbm, there is a [test failure](https://jenkins.saltstack.com/job/salt-pr-rs-cent7-n/6230/testReport/junit/unit.modules.xapi_test/XapiTestCase/test_vm_cputime/).

**Comment by isbm** [comment]
@jfindlay Thanks for heads up! I am monitoring this now, let's see if all tests passes.

**Comment by isbm** [comment]
@jfindlay Help, RH hates me and I don't know why...

**Comment by rallytime** [comment]
@isbm Those CentOS 7 test failures don't look related to me, though I could be wrong. It would be swell if @jfindlay or @jtand can confirm that though.

**Comment by jtand** [comment]
@isbm @rallytime @jfindlay Pretty sure the test failures are unrelated. those pop up every so often. It's a bug in zeromq, unless I'm mistaken.

**Comment by jfindlay** [comment]
@jtand, yes that looks unrelated.

**Comment by thatch45** [comment]
This looks great @isbm ! Maybe I missed the lines where you have done this but can you alias the removed functions just so that we don't have a backwards api compat issue?

**Comment by isbm** [comment]
@thatch45 no, there are no aliases yet. Is there any mechanism in Salt (a decorator?) that would enable mark a function like deprecated? E.g.:

```python
@deprecated('This will be removed in version Unicorn')
def very_bad_idea_we_want_to_drop_soon():
      ...
```

**Comment by jfindlay** [comment]
@isbm
```python
import salt.utils

def very_bad_idea_we_want_to_drop_soon():
   salt.utils.warn_until(
      'Unicorn',
      'This function has been deprecated in favor of '
      '`good_idea_which_replaces_bad_idea`, please migrate your salt usage'.
      )
   ...
```

**Comment by isbm** [comment]
@jfindlay I hope, Nitrogen is fine.

**Comment by thatch45** [comment]
Nitrogen should be good

**Comment by thatch45** [comment]
Thanks!

**Comment by isbm** [comment]
@thatch45 seems like tests are passing fine (the centos one is unrelated)

**Comment by thatch45** [comment]
This is great @isbm ! Thanks!

**Pull request merged**
