### PR TITLE
Provide option to set a display name. Defaults to instance's name.

### PR DESCRIPTION
**Pull request by kalousd**

### CODE REVIEW

**Comment by rallytime** [comment]
@nKaloussian Can you grab the the Pylint error? The CentOS 6 failures are unrelated.

https://jenkins.saltstack.com/job/salt-pr-lint-n/6182/violations/file/salt/cloud/clouds/cloudstack.py/

**Comment by cro** [comment]
Almost there @nKaloussian -- there's one more pylint error in there, we're mandating Python 3 compatible code now in anticipation of transitioning Salt to Py3.

**Comment by jtand** [comment]
@cro That lint error for rpm.py which is fixed in develop

**Comment by cro** [comment]
@jtand Thanks!

**Pull request merged**
