### PR TITLE
Changes for BUG opened: 56995

### LINKED ISSUE #56995: [BUG] Problem using zabbix.mediatype_create and zabbix.mediatype_get due to API changes on 4.4
**Description**
Problem using zabbix_mediatype.present due to API changes on zabbix 4.4

**Setup**

Using SALT 3000.1.
Downloaded the git modules to test new code as well.

When trying to create a new mediatype with zabbix_mediatype.present, salt wont do it, instead, it updates whatever is the first mediatype already created on zabbix.

For example, if there is 3 media types in the following order: Email, Script, SMS.
Salt, pickup the Email mediatype, and update that mediatype with the parameters of my state.
```
zabbix-media-xxx:
  zabbix_mediatype.present:
    - name: 'Testing'
    - mediatype: 1
    - exec_params: "{ALERT.SENDTO}\n{ALERT.SUBJECT}\n{ALERT.MESSAGE}"
    - exec_path: testing.sh
    - description: 'Whatever Needed'
    - status: 0
```
**Steps to Reproduce the behavior**

Just try to create a new mediatype (using the zabbix_mediatype.present state), using zabbix version 4.4 or higher.

**Current behavior**
It won't create a new mediatype, instead it will change configuration of an already created one at zabbix. It will pickup the first mediatype on the list[0].

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.12.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core

```
</details>

**Additional context**
Already evaluated that. There is a new attribute for mediatype. 
So in the past (until zabbix 4.4) the module used to use "description" attribute as "name", to make the call of zabbix.mediatype_get and zabbix.mediatype_create. So, as there is a new attribute called "name", it wont filter the appropriate field.

### PR DESCRIPTION
**Pull request by bfdacosta**
### What does this PR do?
Fix mediatype_create and mediatype_get usage since new API 4.4.

- Added a apiinfo_version call to check the API version when
  dealing with mediatype_create and get.
- Changed the attribute called from "description" to "name",
  when API version is greater or equal to 4.4. changed both
  mediatype_create and mediatype_get.

### What issues does this PR fix or reference?
Fixes #56995 

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by DmitryKuzmenko** [comment]
@bfdacosta thank you for contribution! Could you please also write a regression tests for your changes?

**Comment by bfdacosta** [comment]
DmitryKuzmenko, greetings! Can you point me out a regression test that is needed. Any example code for that ? Thanks !

**Comment by mchugh19** [comment]
@bfdacosta there are unit tests for the zabbix module in salt/tests/unit/modules/test_zabbix.py. You could create a test which mocks a version response of 4.3 and validate that the json is generated in the expected format. This could then be copied and modified for the 4.4 version and expected response.

**Comment by DmitryKuzmenko** [comment]
Thank you @mchugh19 .
@bfdacosta do you need any advice on that?

**Comment by bfdacosta** [comment]
I will produce the test.
The problem is not the answer, its how the call to the API is done. Thats is the difference between versions. I will lookup for the test.

**Comment by DmitryKuzmenko** [comment]
@bfdacosta I think you can mock it with stubs just checking the logic goes in a proper ways with different stubbed version values. Also you can add links to the corresponding documentation to the stubs to make it easily understandable. I don't think we have to test this particular change with a real zabbix servers.

**Comment by bfdacosta** [comment]
Test added to the code.

**Comment by bfdacosta** [comment]
@DmitryKuzmenko let me know if anything else still needed for merge! Thanks!

**Comment by DmitryKuzmenko** [comment]
@bfdacosta yes, could you please update your branch and re-run pre-commit on it? There're some issues
```
05:38:19  Drop six usage and Py2 support...........................................Failed
05:38:19  - hook id: pyupgrade
05:38:19  - exit code: 1
05:38:19  - files were modified by this hook
05:38:19  
05:38:19  Rewriting salt/modules/zabbix.py
05:38:19  Rewriting tests/unit/modules/test_zabbix.py
05:38:19  
05:38:20  isort....................................................................Passed
05:38:25  black....................................................................Failed
05:38:25  - hook id: black
05:38:25  - files were modified by this hook
05:38:25  
05:38:25  reformatted /var/jenkins/workspace/pr-pre-commit_PR-56996/salt/modules/zabbix.py
05:38:25  All done! ✨ 🍰 ✨
05:38:25  1 file reformatted, 1 file left unchanged.
```

**Comment by bfdacosta** [comment]
@DmitryKuzmenko Greetings!!! All problems solved. Thanks!

**Review by DmitryKuzmenko — APPROVED** [review]

**Pull request merged**
