### PR TITLE
[on hold] Refactor module system per #30533

### PR DESCRIPTION
**Pull request by sjorge**
Started with an easy one. 

All have `__virtualname__` set to _system_ so this should not break anything.

Please give this extra scrutiny.

### CODE REVIEW

**Comment by sjorge** [comment]
Seems the windows test still fails, looking at it now

**Comment by basepi** [comment]
This looks great to me. The thing I worry about with these changes is the provider overrides in the config. We still don't have a backwards compatibility system in place yet...

**Comment by basepi** [comment]
It may be fairly easy to add such a table, I might look later this week.

**Comment by sjorge** [comment]
Yeah that's the only thing that would potentially break in this. Let me know when you have an idea for such a system or have one implemented. I will update the PR then.

Or should I scrap it for now and make a new one later? If it takes a while this one will eventually end out of sync with develop.

**Comment by basepi** [comment]
I'm not in a huge hurry. If this one gets out of sync, we'll look at it then. I want it here to remind me to think about the problems. :)

**Comment by cachedout** [comment]
@sjorge Let's close this until it's ready to go. We have a pretty big PR backlog right now and this one might be a while. (And it won't merge cleanly right now anyway.) Sound good?

**Comment by sjorge** [comment]
Yes, I proposed that in the issue but was asked to leave it open. It wasn't a lot of work to get this PR opened so it's easy to recreat once the loader has been updated.

**Pull request closed without merging**
