### PR TITLE
Remove grains type deprecation warning from 2016.3

### LINKED ISSUE #35972: DeprecationWarning: The "osmajorrelease" will be a type of an integer.
### Description of Issue/Question

I am seeing this warning message after 6.3.2 to 6.3.3 upgrade

### Setup
 salt-run -t 60 manage.down

### Steps to Reproduce Issue

[root@salt01 ~]# salt-run -t 60 manage.down
[WARNING ] /usr/lib/python2.7/site-packages/salt/grains/core.py:1493: DeprecationWarning: The "osmajorrelease" will be a type of an integer.
### Versions Report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.2.2
       dateutil: 1.5
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.3.8
         Jinja2: 2.8
        libgit2: 0.21.0
        libnacl: 1.4.3
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: 1.2.3
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.28.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

### PR DESCRIPTION
**Pull request by rallytime**
Fixes saltstack/salt#35972 and Refs saltstack/salt#35637

### CODE REVIEW

**Comment by rallytime** [comment]
ping @isbm

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by isbm** [comment]
@rallytime @cachedout Actually, thanks removing that. I was against it anyway, but community wanted. Sorry did not replied earlier, I was away in mountains with no network for a week.

**Comment by cachedout** [comment]
@isbm Thanks for following up. I knew there was some disagreement there and I'm glad you understand. :] Hope your time in the mountains was enjoyable!

**Comment by isbm** [comment]
@cachedout I _always_ (try to) understand, and you _know_ it. :laughing:

**Comment by cachedout** [comment]
Hah. I agree with you! :]

**Pull request merged**
