### PR TITLE
loader: Fix loading grains with annotations

### PR DESCRIPTION
**Pull request by bdrung**
If custom grain modules use annotations, salt will fail to load them. Example grain:

```
from typing import Dict

def example_grain() -> Dict[str, str]:
    return {"example": "42"}
```

`salt-call grains.items` will print this exception:

```
Failed to load grains defined in grain file ... in function <...>, error:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 847, in grains
    parameters = salt.utils.args.get_function_argspec(funcs[key]).args
  File "/usr/lib/python3/dist-packages/salt/utils/args.py", line 271, in get_function_argspec
    aspec = _getargspec(func)
  File "/usr/lib/python3/dist-packages/salt/utils/args.py", line 40, in _getargspec
    "Function has keyword-only arguments or annotations"
ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them
```

Python recommends to use `inspect.signature` instead of `inspect.getfullargspec` (which is only needs to maintain compatibility with the Python 2 `inspect` module API). Since salt only supports Python 3, drop using the wrapper function `get_function_argspec` and use `inspect.signature` directly.

### CODE REVIEW

**Review by Ch3LL — CHANGES_REQUESTED** [review]
Needs a changelog and a test case to ensure we don't regress the ability to use custom grains with annotations in the future.

**Comment by bdrung** [comment]
Added a changelog entry and test cases to prevent regressions.

**Review by Ch3LL — DISMISSED** [review]

**Review by s0undt3ch — APPROVED** [review]

**Review by s0undt3ch — CHANGES_REQUESTED** [review]
This PR has conflicts that need to be solved.

**Comment by bdrung** [comment]
Rebased.

**Review by s0undt3ch — DISMISSED** [review]

**Comment by Ch3LL** [comment]
ping @bdrung I don't seem to have permissions to update the branch on your PR. We recently fixed the mac and debian test issues you are seeing, would you mind rebasing your branch again.

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
