### PR TITLE
Remove dependency on win32gui

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?
Removes dependency on win32gui

### What issues does this PR fix or reference?
https://github.com/saltstack/salt-windows-msi/issues/16

### Previous Behavior
Used the SendMessageTimeout method from win32gui

### New Behavior
Uses the SendMessage method from win32api

### Tests written?
No

### CODE REVIEW

**Comment by cachedout** [comment]
A test failed here: https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/10793/testReport/junit/unit.modules.test_win_path/WinPathTestCase/test_rehash/

**Comment by rallytime** [comment]
@twangboy This is still failing a `win` test. Can you take another look?

**Comment by cachedout** [comment]
@twangboy We're still not there even with that last change.

https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/10854/testReport/junit/unit.modules.test_win_path/WinPathTestCase/test_rehash/

Could you please have another look?

**Comment by twangboy** [comment]
I don't know what's going on. The test does not fail when run on a Windows box...

**Comment by cachedout** [comment]
Hi @twangboy.

I have submitted a PR to your fork to address this: https://github.com/twangboy/salt/pull/4

I am also moving this back into the backlog.

**Pull request merged**
