### PR TITLE
win_system: return False from a skipped reboot

### PR DESCRIPTION
**Pull request by morganwillcock**
### What does this PR do?
Return False from win_system.reboot, when the reboot wasn't required.
Clarify what the return value represents.

### What issues does this PR fix or reference?
As discussed in #39243.

### Previous Behavior
Return value of True doesn't indicate whether a reboot will occur.

### New Behavior
Return value of True indicates that a reboot will occur.

### Tests written?
No

### CODE REVIEW

**Comment by hrumph** [comment]
Code changes are OK I think, but more documentation changes are required

You need to change the description of "return" for the shutdown function too (you adjusted it for reboot but not for shutdown). Also all the stuff about usage in a final housekepeing state as well as the example I provided should be chopped because, in the future, if people want to do that, they will want to be using the new state function that we discussed.

**Comment by morganwillcock** [comment]
I thought about changing the return description on the other functions, but the other functions don't have options which could change the outcome. I can add it everywhere if that's what modules normally do. For the option description changes, I was going to put that into the develop branch with the state module.

**Comment by hrumph** [comment]
@morganwillcock Maybe i'm not understanding something but both the reboot and shutdown functions have the _only_on_pending_reboot_ paramater so both can now return false because a reboot isn't needed, so both should have their documentation changed in parallell.

THe mention of a final housekeeping state + example has to be chopped here (not in devel), because technically I don't think it will work properly, because when module.run returns a false the state system reports it as a failure (unless I'm misremembering). I'm not too concerned about it. The new state function you will be PRing (hopefully soon) is a much better solution anyway.

These are all just documentation matters. Anyway think what you think. This is just my two cents.

**Comment by hrumph** [comment]
Ok i read the accompanying devel PR and I guess I it should be merged now. (just my opinion).

**Pull request merged**
