### PR TITLE
2017.7 remove sshagent

### PR DESCRIPTION
**Pull request by bryceml**
### What does this PR do?
removes the sshagent plugin so we build pr's like we do for the branch builds

### CODE REVIEW

**Review by waynew — APPROVED** [review]

**Comment by waynew** [comment]
Should this just go into `master` now?

**Comment by bryceml** [comment]
yeah, there is a pr open to every branch for this.
we could close the old ones if they're not going to make it in before we delete them.

**Comment by bryceml** [comment]
https://github.com/saltstack/salt/pull/54735

**Comment by bryceml** [comment]
This is no longer being tested.

**Pull request closed without merging**
