### PR TITLE
[3006.x] Latest golden images; fix Arch Linux key reqs

### PR DESCRIPTION
**Pull request by ScriptAutomate**
### What does this PR do?

- Fresh golden images with latest updates
- Includes a modification to Arch Linux to ensure `pacman-key --refresh-keys` ran at image generation
  - https://github.com/saltstack/salt-ci-images/pull/1850

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by dmurphy18 — APPROVED** [review]
Restarted that failing Arch test

**Comment by ScriptAutomate** [comment]
`test_git_pillar.py::TestGitPythonSSH*` tests are all throwing `Error: unknown key type dsa` for Arch Linux LTS, but not sure if related to the updated images?

**Comment by ScriptAutomate** [comment]
Closing this PR. Arch Linux is scheduled to be dropped from Salt Project CI/CD.

**Comment by ScriptAutomate** [comment]
Superseded by:
- https://github.com/saltstack/salt/issues/66886
  - https://github.com/saltstack/salt/pull/66887

**Pull request closed without merging**
