### PR TITLE
Fix glusterfs module

### PR DESCRIPTION
**Pull request by hugo-ricateau**
### What does this PR do?
Fixes the `_gluster_output_cleanup` function in the `glusterfs` module (causing a systematic failure of `glusterfs.volume_present` among other formulas). 

### What issues does this PR fix or reference?
Fixes: -

### Previous Behavior
Retrieving the original command (after the `gluster>` prompt) is unnecessary and produces an invalid block in the xml output; resulting in an `xml.etree.ElementTree.ParseError` being raised.

### New Behavior
Filters the original command (along with the `gluster>` prompt) from the xml output; resulting in a valid xml string.

### Merge requirements satisfied?
- [x] Tests written/updated - _As this fixes a bug while preparing the output of the `gluster` cli for the subsequent parsing operation (see the `_gluster_output_cleanup`'s docstring); and as this cli is mocked in the tests; I think updating these tests might not be a relevant action_;
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html - _Should I open an issue to reference in the changelog?_
- [x] Docs - _Nothing to change_;

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by Ch3LL — CHANGES_REQUESTED** [review]
This will also require a changelog and a test.

**Comment by hugo-ricateau** [comment]
> This will also require a changelog and a test.

Please, read the PR description:
> - [x] Tests written/updated - _As this fixes a bug while preparing the output of the `gluster` cli for the subsequent parsing operation (see the `_gluster_output_cleanup`'s docstring); and as this cli is mocked in the tests; I think updating these tests might not be a relevant action_;

> - [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html - _Should I open an issue to reference in the changelog?_

**Comment by Ch3LL** [comment]
> Should I open an issue to reference in the changelog?

Yes please. 

> As this fixes a bug while preparing the output of the gluster cli for the subsequent parsing operation (see the _gluster_output_cleanup's docstring); and as this cli is mocked in the tests; I think updating these tests might not be a relevant action;

Can you include the entire stack trace and the glusterfs command output in the issue you open? I would still prefer to add a regression test since this was not caught previously by our tests, but if you include that information in the issue it will help me determine if we could add a valuable test.

**Comment by Ch3LL** [comment]
Just following up here again. Have you had time to open an issue with the stacktrace?

**Comment by Ch3LL** [comment]
Closing due to inactivity. Let me know if it needs to be re-opened.

**Pull request closed without merging**
