### PR TITLE
[PY3] Update fileserver for Unicode/PY3 compatibility

### PR DESCRIPTION
**Pull request by terminalmage**
This adds a unicode_literals import to the fileserver code, and also ensures
that we return unicode paths from the serialized file/env list caches
(which when deserialized are still encoded str types on PY2).

It also adds a test and modifies a few other existing tests to confirm
that unicode paths/envs are returned *as unicode* in the return data.

### CODE REVIEW

**Comment by terminalmage** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
re-run py

**Comment by rallytime** [comment]
@terminalmage This needs a rebase.

**Comment by terminalmage** [comment]
rebased

**Comment by rallytime** [comment]
re-run lint

**Comment by rallytime** [comment]
@terminalmage the `integration.modules.test_cp.CPModuleTest.test_cache_master` test failure on the PY2 runs is related. I reproduced it running off of this PR.

**Comment by terminalmage** [comment]
@rallytime That was caused by a unicode/str mismatch in a `.format()` call in salt.utils.url, which doesn't yet have `unicode_literals` enabled. This is actually added in a pending PR (https://github.com/saltstack/salt/pull/45438). I'm going to see if adding unicode_literals to that file in this PR fixes it.

**Comment by terminalmage** [comment]
OK this should be fixed in the next round of PR tests.

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
re-run lint

**Comment by rallytime** [comment]
re-run lint

**Comment by rallytime** [comment]
@terminalmage Some simple lint: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/18356/violations/file/salt/utils/gitfs.py/

**Pull request merged**
