### PR TITLE
move requirements files into requirements dir

### PR DESCRIPTION
**Pull request by jfindlay**

### CODE REVIEW

**Comment by aboe76** [comment]
Something went wrong with this merge, the setup.py part where the source
```
 
 SALT_VERSION = os.path.join(os.path.abspath(SETUP_DIRNAME), 'salt', 'version.py')
 SALT_VERSION_HARDCODED = os.path.join(os.path.abspath(SETUP_DIRNAME), 'salt', '_version.py')
-SALT_REQS = os.path.join(os.path.abspath(SETUP_DIRNAME), '_requirements.txt')
-SALT_ZEROMQ_REQS = os.path.join(os.path.abspath(SETUP_DIRNAME), 'zeromq-requirements.txt')
-SALT_CLOUD_REQS = os.path.join(os.path.abspath(SETUP_DIRNAME), 'cloud-requirements.txt')
-SALT_RAET_REQS = os.path.join(os.path.abspath(SETUP_DIRNAME), 'raet-requirements.txt')
+SALT_REQS = os.path.join(os.path.abspath(SETUP_DIRNAME), 'requirements', 'base.txt')
+SALT_ZEROMQ_REQS = os.path.join(os.path.abspath(SETUP_DIRNAME), 'requirements', 'zeromq.txt')
+SALT_CLOUD_REQS = os.path.join(os.path.abspath(SETUP_DIRNAME), 'requirements', 'cloud.txt')
+SALT_RAET_REQS = os.path.join(os.path.abspath(SETUP_DIRNAME), 'requirements', 'raet.txt')
 SALT_SYSPATHS = os.path.join(os.path.abspath(SETUP_DIRNAME), 'salt', 'syspaths.py')
```

should change didn't set in the latest develop version...this is stopping the build from develop branch

**Comment by s0undt3ch** [comment]
My fault.

**Comment by s0undt3ch** [comment]
I'll get this fixed.

**Comment by aboe76** [comment]
No problem, I'm glad to catch it quickly.

**Comment by s0undt3ch** [comment]
Here's the fix #19653

**Pull request merged**
