### PR TITLE
#24314 with tests

### LINKED ISSUE #24803: Rewrite GPG renderer tests
With #24314, we'll need to rewrite the GPG renderer tests accordingly. Refs #24314

### PR DESCRIPTION
**Pull request by jfindlay**
#24314 with tests; fixes #24803.

### CODE REVIEW

**Comment by cachedout** [comment]
This is really great! Thank you, @jfindlay

**Comment by cedwards** [comment]
I don't mean to resurrect ancient tickets, but not sure where else to tag this..

I just discovered that this change was NOT added to 2015.8.0. Was this intended? Perhaps an oversight? Can we review this commit and (hopefully) remove the dependency on python-gnupg in the next release?

**Comment by jfindlay** [comment]
@cedwards, we could probably backport it to 2015.8.2, but I don't think I can make that decision alone.

**Comment by cedwards** [comment]
Do we need to loop in @thatch45 or @cachedout for opinion here? I'd really like to see this included sooner than later.

**Comment by jfindlay** [comment]
@cedwards, yes, indeed.  Let's get you running officially released code. :-)  But, I'm loth to backport it without another opinion from @thatch45 or @cachedout or similar.

**Pull request merged**
