### PR TITLE
prevent eternal gitfs lock due to process crash

### PR DESCRIPTION
**Pull request by onorua**
### What does this PR do?

Enhance locking mechanism for gitfs 
### Previous Behavior

Currently when the salt-master process crashed or just restarted during the gitfs pull, master will be in a locked state forever. Until some human check the file and remove the lock, with something like:

```
salt-run cache.clear_git_lock gitfs type=update
```
### New Behavior

Currently instead of just creating the empty file, I propose to create file with `pid` of the process
The next time master wants to perform pull, it checks whether the pid exists and:
-  if it doesn't remove the lock file and create a new one.
-  If the pid is running (do current behavior), failhard with warning message. 
### Tests written?

No

### CODE REVIEW

**Comment by onorua** [comment]
I was thinking, this might be an issue with this approach for multi-master with shared cache, let say cache folder on glusterfs or any other shared storage. So, most probably this PR must be extended to have salt-master config which instructs whether use this approach or "global" lock which currently in place.

**Comment by cachedout** [comment]
@terminalmage Can you comment here, please?

**Comment by onorua** [comment]
@terminalmage what do you think about this approach? Let me know if it is generally okay or you see the fix in some other way? I'll be happy to help.

**Comment by cachedout** [comment]
@onorua This now has a merge conflict. Could you please rebase it?

**Comment by onorua** [comment]
done

**Comment by terminalmage** [comment]
```python
if self.opts.get("gitfs_global_lock") or pid and pid_exists(int(pid)):
```

This would use the "new" behavior the lock file contains a pid, irrespective of the value of ``gitfs_global_lock``.


Regardless, I think this is overkill. There are two ways that an update lock can fail to be cleared:

1. The maintenance thread or the master itself crashes during an update
2. The salt-master daemon is stopped or restarted during an update

A more elegant solution would be to simply clear any locks that are present when the master starts. That takes care of the cases where the salt-master daemon was stopped or restarted during an update. And if the maintenance thread dies, you have bigger problems from which you won't recover without restarting the salt-master daemon, so clearing the locks when the master's maintenance thread is initialized fixes both cases.

I've opened https://github.com/saltstack/salt/pull/32480 to do this.

**Comment by cachedout** [comment]
@onorua If you're satisfied with the fix from @terminalmage which has been merged, I would like to close this. Please let me know what you think. Thanks.

**Comment by onorua** [comment]
Actually I'm not really satisfied with proposed solution due to 2 reasons. 

1. Some of our environments use Bitbucket for git storage, and we face sync issues 2 times a day due to crash sync process due to some issue with git server, internet connection etc. Fix proposed by @terminalmage makes it possible to restart salt-master and get it working, but what happen if master server is still running but maintenance thread is not?

2. Also, and this is even more important, you do not check the type of storage, removing lock during salt-master start is not a good idea for shared filesystem between masters, because it means you may end up with removing lock created by some other instance running on other host. 

Proposed PR fix both of these cases, while merged fixes one only one partially, introducing other race condition problems :(

**Comment by terminalmage** [comment]
@onorua Good point.

**Comment by terminalmage** [comment]
@onorua I'm going to bundle your PR into a new PR that will revert my PR and apply yours, with some slight wording tweaks in the log message.

**Comment by onorua** [comment]
thanks guys!

**Comment by onorua** [comment]
Closed because #32558 is already merged.

**Pull request closed without merging**
