### PR TITLE
Document Windows default for ipc_mode

### PR DESCRIPTION
**Pull request by marbx**
### What does this PR do?
Resolves documentation task https://github.com/saltstack/community/issues/32 of Working group https://github.com/saltstack/community/projects/4

Replaces https://github.com/saltstack/salt/pull/54738 because merging against master

### CODE REVIEW

**Comment by markuskramerIgitt** [comment]
@twangboy I think the master branch idea is a good one. Especially "test must pass before merge".

Have you assembled the most common git command for contributors, or could you please do so?
Many git commands explicitly involved the develop branch.

**Comment by twangboy** [comment]
@waynew ^^^

**Comment by markuskramerIgitt** [comment]
With most common I meant fetch pull branch add commit.

I would like to avoid rebase

**Comment by waynew** [comment]
@markuskramerIgitt rebase is actually the preferred method, as we require tests passing with the most recent master. It's possible (and we've seen in the past) PRs that have a number of merge commits that are just merging the most recent changes into their branch. Rebasing keeps a cleaner history.

Do you have some pointers to the existing documentation that you're referring to? Or are you just talking about [the contributing page](https://docs.saltstack.com/en/latest/topics/development/contributing.html)? We will be updating that when SEP 14 gets officially accepted.

**Comment by markuskramerIgitt** [comment]
@waynew , thank you for updating the contributing page

**Comment by rares-pop** [comment]
> @markuskramerIgitt rebase is actually the preferred method, as we require tests passing with the most recent master. It's possible (and we've seen in the past) PRs that have a number of merge commits that are just merging the most recent changes into their branch. Rebasing keeps a cleaner history.

@waynew - is it? I know you should *never* rebase a branch after it went public (because you just mess up everyone with that), and creating a PR out of it, doesn't make it public? Does github know how to keep references to comments and stuff once you do the rebase?

You can rebase and merge the PR if you want to, which is described [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges).

**Comment by markuskramerIgitt** [comment]
@twangboy  could you please re-approve and merge this PR?

**Review by twangboy — APPROVED** [review]

**Pull request merged**
