### PR TITLE
Support glob pattern in file.absent state

### PR DESCRIPTION
**Pull request by ixs**
This is a rework of the older PR #44723. The original author never
finished the PR and the feature is actually worthwhile.

Changed glob import
Added simple test-case.

### What does this PR do?
Add globbing support to the file.absent state.

### What issues does this PR fix or reference?
#9183

### CODE REVIEW

**Comment by ixs** [comment]
As a general note: I find your process of closing PRs when they haven't been worked on a while a bit suboptimal as this seems to also close the referenced issue.
This is kinda unexpected as the issue actually hasn't been fixed.

Maybe there's a better way of dealing with such a situation?

**Comment by cachedout** [comment]
@ixs You are totally right. This was a mistake on our part. We'll find a better way to handle that situation.

**Review by terminalmage — CHANGES_REQUESTED** [review]
Can you please do this without the decorator? For one, I don't see the benefit of using one here when it's only being used on the one function. Secondly, using the decorator negates the docstring and will remove all documentation for this state when docs are built.

**Comment by ixs** [comment]
@terminalmage Just to clarify: You would prefer _not_ using the decorator but instead you would like the globbing support folded into the main absent state function?

**Comment by terminalmage** [comment]
Correct, that logic can be placed near the top of the function.

**Comment by rallytime** [comment]
@ixs Were you able to come back to this?

**Comment by ixs** [comment]
@rallytime I've been traveling/doing the conferenc-circuit the last four weeks. Give me a bit of time to get back to my own timezone and I'll look at implementing the requested changes.

**Comment by rallytime** [comment]
Hey @ixs - I'm going to close this for now until you've had a chance to come back here. :)

When you're ready to incorporate the feedback, this will also need a rebase as there are merge-conflicts in `file.py`.

Let us know when you're ready and we will be very happy to open this up again. Or, if it is easier for you, feel free to open a new PR and link it to think one.

Thanks again!

**Pull request closed without merging**
