### PR TITLE
utils.aws: use time lib to conver to epoch seconds

### LINKED ISSUE #30798: salt/utils/aws.py has Python 2.7 dependency
Since 2015.8.4 aws signature generation on AWS instances using instance profile credentials seems broken on Python 2.6 (e.g. Centos/RHEL 6)
```
salt-call --local s3.get xxxxx path=yyyy local_file=/tmp/yyyy location=ap-southeast-2

  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 335, in salt_call
    client.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/call.py", line 53, in run
    caller.run()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 133, in run
    ret = self.call()
  File "/usr/lib/python2.6/site-packages/salt/cli/caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/modules/s3.py", line 169, in get
    role_arn=role_arn)
  File "/usr/lib/python2.6/site-packages/salt/utils/s3.py", line 112, in query
    requesturl=requesturl,
  File "/usr/lib/python2.6/site-packages/salt/utils/aws.py", line 219, in sig4
    access_key_id, secret_access_key, token = assumed_creds(prov_dict, role_arn, location=location)
  File "/usr/lib/python2.6/site-packages/salt/utils/aws.py", line 156, in assumed_creds
    now = (datetime.utcnow() - datetime(1970, 1, 1)).total_seconds()
AttributeError: 'datetime.timedelta' object has no attribute 'total_seconds'
```
since total_seconds was only introduced in Python 2.7
https://docs.python.org/2/library/datetime.html#datetime.timedelta.total_seconds
The relevant code is
https://github.com/saltstack/salt/blob/v2015.8.4/salt/utils/aws.py#L156

```
[root@ip-10-16-1-45 ~]# salt-call --local  test.versions
local:
    Salt Version:
               Salt: 2015.8.4
     
    Dependency Versions:
             Jinja2: 2.2.1
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.5.0
             Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist: centos 6.7 Final
            machine: x86_64
            release: 2.6.32-573.12.1.el6.x86_64
             system: CentOS 6.7 Final
```

### PR DESCRIPTION
**Pull request by jfindlay**
Fixes #30798.

### CODE REVIEW

**Comment by techhat** [comment]
How about `int(time.time())`?

**Comment by jfindlay** [comment]
@techhat, I think that that value is [timezone 'naive'](https://docs.python.org/2/library/datetime.html), which would throw off a check of 120 seconds difference.

**Comment by techhat** [comment]
@jfindlay, makes sense, wasn't thinking.

**Comment by cachedout** [comment]
Thanks all.

**Pull request merged**
