### PR TITLE
if it is ipv6 ip_to_int will fail

### PR DESCRIPTION
**Pull request by gtmanfred**
fixes bug introduced in #23573

### CODE REVIEW

**Comment by gtmanfred** [comment]
@techhat against the correct branch :)

**Comment by techhat** [comment]
TY, @gtmanfred.

**Comment by gtmanfred** [comment]
@jfindlay can you make sure this one and #23823 get forward merged whereever the other things went?

Thanks!

**Comment by jfindlay** [comment]
From what I can see, this has already been merged into 2015.5 and should make it into develop tomorrow.

**Pull request merged**
