### PR TITLE
Additional unit tests for VMware cloud driver

### PR DESCRIPTION
**Pull request by nmadhok**

### CODE REVIEW

**Comment by cachedout** [comment]
@nmadhok Doesn't look like these tests passed. Would you mind having another look, please?

**Comment by nmadhok** [comment]
@cachedout All the tests ran successfully in my test environment which uses Python 2.6. I believe these tests failed because the test environment that Salt Jenkins ran these tests on uses Python 2.7. 

@rallytime How should I go about this? Do you want me to fix it to be able to run on environments that use Python 2.6, Python2.7 as well as any other environment?

**Comment by rallytime** [comment]
@nmadhok Yeah, the tests need to be able to run on both 2.6 and 2.7. If you could fix that, that would be most excellent.

**Comment by nmadhok** [comment]
@rallytime Will need to take time out for that. Working on runners atm. Don't know when i'll be able to take a look at the tests.

**Comment by cachedout** [comment]
@nmadhok Please let us know when you have a chance to look at this.

**Comment by nmadhok** [comment]
Go Go Jenkins!

**Comment by nmadhok** [comment]
@rallytime @cachedout It seem like the tests are failing because pyVmomi is not installed on the server where unit tests are run. Is there a possibility that it can be installed? 

Here's how it can be installed: ``pip install pyvmomi``

**Comment by rallytime** [comment]
Ok two things need to be done here then. First, we need to get `pyvmomi` installed on the test servers via the [salt-jenkins states](https://github.com/saltstack/salt-jenkins). @jtand or @jfindlay can one of you look at doing that really quickly?

The other thing, @nmadhok, is that we need to protect against these failures by skipping them if the library requirements aren't met. Can you add some code to `skipif` these tests if `pyvmomi` isn't installed?

**Comment by jtand** [comment]
@rallytime Yeah, I can do that.

**Comment by nmadhok** [comment]
@rallytime I will have to look into how skipif works. Any good documentation you can point me to?

**Comment by rallytime** [comment]
Oh, it's just a decorator that you can put either before an individual test or an entire test class. You can use it to tell the test runner to skip the test (or class) if a certain condition isn't met. Something like:
```
@skipIf(HAS_PYVMOMI is False, 'pyvmomi must be installed before running these tests.')
```
Check out this test file for a more thorough example: https://github.com/saltstack/salt/blob/develop/tests/unit/modules/mysql_test.py

**Comment by nmadhok** [comment]
Test Failure Unrelated.

**Comment by rallytime** [comment]
Thanks!

**Pull request merged**
