### PR TITLE
fix salt-minion & syndic with different masters

### PR DESCRIPTION
**Pull request by ze42**
work around for #35128 

dynamically remove syndic_master option from the minion as it is completely useless anyway.

### CODE REVIEW

**Comment by cachedout** [comment]
@DmitryKuzmenko What do you think about this?

**Comment by DmitryKuzmenko** [comment]
@cachedout I think "why `salt.crypt.AsyncAuth`" decides to use `syndic_master.pub` based on the `syndic_master` option? Why not `opts['__role']`?

**Comment by DmitryKuzmenko** [comment]
I'm about this part of code in the `salt/crypt.py`:
```python
        if 'syndic_master' in self.opts:
            self.mpub = 'syndic_master.pub'
        elif 'alert_master' in self.opts:
            self.mpub = 'monitor_master.pub'
        else:
            self.mpub = 'minion_master.pub'
```

I've found that `__role` appeared later when this code was already implemented. Also the `alert_master` case is an old dropped feature. So it would be better to replace this case with the following:
```python
        if self.opts['__role'] == 'syndic':
            self.mpub = 'syndic_master.pub'
        else:
            self.mpub = 'minion_master.pub'
```
Instead of cutting the option from opts.

@ze42 could you please update your PR?

**Comment by ze42** [comment]
@DmitryKuzmenko oh, didn't know about the `__role` info. Much better indeed.

Changed PR to exactly what you wrote, and it works nicely on my host.

**Comment by DmitryKuzmenko** [comment]
@ze42 thanks to you for catch, fix and testing!

**Pull request merged**
