### PR TITLE
Fix cmd batch raw

### PR DESCRIPTION
**Pull request by jeanpralo**
### What issues does this PR fix or reference?

At the moment when we use salt.client.LocalClient.cmd_batch with the raw kwargs set to True we receive an exception as the result of the minion is trying to access a key in the part dictionnary that does not exist. 

The ret dictionary is not updated either causing the main loop to iterate forever (https://github.com/jeanpralo/salt/blob/ead47e4bba6d8addd0717b28b81251e3a4a22647/salt/cli/batch.py#L133)

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
I would love to have a test written for this if you're willing. If you don't have time, I think this is fine to merge but it never hurts to ask. ;]

**Comment by jeanpralo** [comment]
@cachedout  as requested :)

Do you want me to add the test as well for #37612  ?  And by the way is two PR for the same problem the right way to go ? And do you want me to fix that problem in development or you will merge or rebase from this branch ?

**Comment by cachedout** [comment]
If you close the other PR, we'll eventually merge this forward into develop. No need for two PRs. We always merge forward from the oldest supported branch, which right now is 2016.3

**Comment by jeanpralo** [comment]
sweet done.

**Pull request merged**
