### PR TITLE
`has_classifier` need to be evaluated first

### PR DESCRIPTION
**Pull request by angeloudy**
#46029 introduced the following code at line 394
```
extension_version_dict[extension + ':' + classifier] = value
```
which combines `packaging` and `classifier` together as the key for `snapshot_versions` and thus `has_classifier` need to be evaluated in all the if branches.

### CODE REVIEW

**Review by dwoz — CHANGES_REQUESTED** [review]
Hi @angeloudy, This change looks good. Can you please also write a test that covers this?

**Comment by angeloudy** [comment]
@dwoz 
I am not sure how to write that.

**Comment by Ch3LL** [comment]
@angeloudy we have some documentation here: https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html

let me know if you have any questions or if i can help direct you in any way

**Comment by angeloudy** [comment]
tests added.

**Comment by sathieu** [comment]
Please merge this one. This currently is annoying (and the patch fixes it).

**Comment by Ch3LL** [comment]
This needs to go to master. I went ahead and cherry-picked this PR onto master here: https://github.com/saltstack/salt/pull/56604  I also ran black and fixed a lint error. I'll close here and we can merge from that PR. ping @angeloudy  if you could review this PR and ensure everything ported over okay.

**Pull request closed without merging**
