### PR TITLE
Fix for #20170

### PR DESCRIPTION
**Pull request by jacksontj**
fix bug introduced in e806ae98fc72e3b53cd5f596f07b2c180765fc2a

### CODE REVIEW

**Comment by kiorky** [comment]
with @jacksontj we just decided to use nested, grains outputter is broken and ... useless :)

**Comment by jacksontj** [comment]
@thatch45 After looking into this more with @kiorky it seems that the grains outputter has been broken for ~8 months-- since the loader is good at catching exceptions no one has noticed. We've just been falling back to nested instead-- which works fine and looks better. After looking at this grains outputter more I believe we should just remove it and use nested instead.

**Comment by kiorky** [comment]
:+1: :)

**Comment by jacksontj** [comment]
Also, there is no need to keep code around under the "grains.py" name, since right now it doesn't work and falls back to this exact module anyways :)

**Pull request merged**
