### PR TITLE
Ensure a sensible timeout for pgsql commands

### PR DESCRIPTION
**Pull request by edevil**
The psql command has no default timeout, so if the server is not
responding or if some lock cannot be obtained, we will be waiting
forever.

### What does this PR do?
Introduce a default timeout of 60s for all psql commands.

### Previous Behavior
Module would wait forever for commands to return.

### New Behavior
Module will wait at most 60s for psql command to complete.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by dmurphy18 — CHANGES_REQUESTED** [review]
Can this be made configurable with the default being 60 secs.
There should also be tests to check that the value is operational

Also needs a changelog entry (one liner describing the fix)

**Comment by MKLeb** [comment]
@edevil Have you been able to look at implementing @dmurphy18 's suggestion?

**Comment by edevil** [comment]
Hey @MKLeb. Sorry but no, I've been a bit busy.

**Review by twangboy — CHANGES_REQUESTED** [review]
This needs a test and a changelog

**Review by Ch3LL — APPROVED** [review]

**Review by dmurphy18 — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Pull request merged**
