### PR TITLE
[develop] update bootstrap to 2016.04.18 release

### PR DESCRIPTION
**Pull request by jfindlay**
https://github.com/saltstack/salt-bootstrap/releases/tag/v2016.04.18

### CODE REVIEW

**Comment by cachedout** [comment]
We're going to hold on all of these until this is resolved: https://github.com/saltstack/salt-bootstrap/issues/819

**Comment by cachedout** [comment]
@jfindlay What's the plan here. Are you going to re-tag this with the fix you put in recently for Cent7?

**Comment by jfindlay** [comment]
@cachedout, that is already part of the release.

**Comment by cachedout** [comment]
@jfindlay OK. If we're ready to go then, please rebase this and we'll get it in. Thanks.

**Pull request merged**
