### PR TITLE
Reorganize doc references

### PR DESCRIPTION
**Pull request by arnisoph**
Since we have the global modules index http://docs.saltstack.com/en/latest/salt-modindex.html that gives a nice overview of ALL salt modules I vote for removing the index articles from the references chapter.

IMHO this also helps to make the references chapter better readable which is what I requested in #20489.

ping @whiteinge @jacobhammons

### CODE REVIEW

**Comment by whiteinge** [comment]
Removing those `index.rst` files will break the full module index. That main index is generated by each one of those individual index files pulling in each Salt module. We can change what pages link to them but we need to keep the actual pages intact and included in the TOC somewhere.

**Comment by cachedout** [comment]
I am going to close this PR so that it doesn't accidentially get merged, based on the concerns raised by @whiteinge. @bechtoldt, we can certainly continue this discussion here though. :]

**Comment by bechtoldt** [comment]
@whiteinge are you sure? I've compiled the docs from scratch and AFAIR the module index was still working.

**Comment by whiteinge** [comment]
Pretty sure. Make sure you nuke your `doc/_build` directory between builds.

The autosummary directive generates the
`doc/ref/{modules,states,etc}/all/*.rst` files and it also adds the
referenced files to the main Sphinx TOC tree. The modules must be
included in the Sphinx TOC tree in order to fill out the module index.
There are other ways to include files in the TOC tree of course, but
this method grabs _all_ modules for inclusion.

http://sphinx-doc.org/ext/autosummary.html

**Comment by bechtoldt** [comment]
@whiteinge 

It definitely still works without the index files. When you think we still need those, I can get them back and create a new PR with the changes in ``doc/ref/index.rst`` only.

=> https://asciinema.org/a/2b32gyzjq592puewigxljdi5h

**Comment by whiteinge** [comment]
Odd. I'm not sure why that would be. I will investiate.

**Comment by whiteinge** [comment]
Ah. I see what is happening. Although the individual module docs are not explicitly included in the TOC Sphinx is still reading them and thus populating the module index. Since the autosummary directive is what was adding them to the TOC, removing the index pages is what is causing all the `WARNING: document isn't included in any toctree` messages. autosummary is also responsible for generating new .rst files for new module additions. Removing autosummary will require putting replacements in place for that lost functionality.

@bechtoldt I would prefer an alternate way to fix the out-of-order documentation mentioned in your original issue. This fix hides the ordering problem in some pages but it will still exist in other pages, and this change will cause different problems.

Moving _back_ to using a monolithic `doc/contents.rst` file will make it easy to globally organize and reorganize the documentation since the order will be contained within a single file. @jacobhammons what are your current thoughts on this?

**Comment by jacobhammons** [comment]
@whiteinge @bechtoldt moving back to a single contents file is still my plan. 

I am also leaning toward an alternate solution, my feeling is these mini indexes are useful in the PDF/ePub and also for new users until they discover the complete module index.

If we do ultimately remove these mini indexes I think we will need to replace them with links directly to the correct location in the master index, but I think we should wait until we re-organize the overall TOC structure to make that decision.

**Pull request closed without merging**
