### PR TITLE
Refactor ipset tests

### PR DESCRIPTION
**Pull request by ahammond**
### What does this PR do?

Refactors the UTs for ipset for readability.
### What issues does this PR fix or reference?

Also corrects some minor consistency and english usage in the comments.

Also fixes a bug where only a single entry is implemented despite multiple entries specified. See 831e743fd197e87e6985f8e32e577ae0c2d9d55b
### Tests written?

Yes - refactored and extended

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @ahammond 

Thanks for doing this.

Could you please fix the issue outlined here? http://166.78.178.63:8080/job/PR/job/salt-pr-lint-n/1481/violations/file/tests/unit/states/ipset_test.py/

Thanks!

**Comment by ahammond** [comment]
Hmmm... I didn't write it, and it doesn't look like it could ever have worked... so...

**Comment by ahammond** [comment]
@cachedout anything else? :)

**Comment by cachedout** [comment]
Nope! Thanks, @ahammond . Merged.

**Pull request merged**
