### PR TITLE
Fix test cases with PermissionError on /var/cache/salt

### PR DESCRIPTION
**Pull request by bdrung**
When running the test cases without root permission, some test cases fail:

```
$ python3 -m pytest -ra tests/pytests/unit/state/test_state_compiler.py tests/pytests/unit/test_minion.py
[...]
FAILED tests/pytests/unit/state/test_state_compiler.py::test_render_requisite_require_disabled - PermissionError: [Errno 13] Permission denied: '/var/cache/salt'
FAILED tests/pytests/unit/state/test_state_compiler.py::test_render_requisite_require_in_disabled - PermissionError: [Errno 13] Permission denied: '/var/cache/salt'
FAILED tests/pytests/unit/test_minion.py::test_minion_module_refresh - PermissionError: [Errno 13] Permission denied: '/var/cache/salt'
FAILED tests/pytests/unit/test_minion.py::test_minion_module_refresh_beacons_refresh - PermissionError: [Errno 13] Permission denied: '/var/cache/salt'
```

Fix these test cases by using a temporary directory as cache directory.

### CODE REVIEW

**Comment by bdrung** [comment]
Rebased on master.

**Review by Ch3LL — COMMENTED** [review]
I'm seeing some test failures on debian 9 that seem to be related. Usually if tests are only failing on Debian 9 its because its the only test OS that runs python 3.5

**Comment by bdrung** [comment]
Found the culprit. This PR sets the cachedir to `tmp_path` which has the type `pathlib.PosixPath` which fails to join with another string. So I convert `tmp_path` to a string first.

**Comment by bdrung** [comment]
The Debian 9 test run succeeds now. CentOS 8 and FreeBSD fail due to an unrelated test case.

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
