### PR TITLE
Refactor Elasticsearch execution and state modules

### PR DESCRIPTION
**Pull request by lukasraska**
### What does this PR do?
Addresses several issues mentioned in #40190 

### What issues does this PR fix or reference?
#40190

### Previous Behavior
- States don't report actual change
- Module doesn't handle exceptions properly
- Certain interesting features are not supported

### New Behavior
- States report actual change and can reconfigure existing managed entities
- Module reports issues via CommandExecutionError
- Module returns True if deleted entity doesn't exist
- Module supports all features mentioned in above issue

### Tests written?

Partially

### CODE REVIEW

**Comment by cachedout** [comment]
@DarkKnightCZ Could you let us know when this is no longer a WIP or if you have specific questions about your implementation that you'd like feedback on? Thanks.

**Comment by DarkKnightCZ** [comment]
Successfully tested on ES 5.2 and 1.5.2 (minimal version specified in current ES module)

@cachedout All issue-related steps are implemented, all states are unit-tested, most of module methods are unit-tested (there are still missing snapshot-related methods - around 30 tests).

One trouble I'm having is how to treat dependencies in unit tests. In ES module I'm capturing elasticsearch-py exceptions and to verify CommandExecutionError is thrown instead, I need to explicitly raise those ES exceptions. Currently I just marked the tests as skippable in case the module cannot be imported, but then it would be probably good idea to update the environment setup for tests (so incompatible changes are detected). Otherwise it's good to be merged (if there aren't any troubles with the implementation as is, lint is fine and docs are updated)

Thanks

**Comment by cachedout** [comment]
Hi @DarkKnightCZ 
In looking this over, I see many function definitions in which the keyword arguments are either not documented at all in the docstrings or incompletely documented. This might make things tricky for a new user. Could you go back through and enhance the docstrings to ensure that's it's obvious what the arguments do?

**Comment by DarkKnightCZ** [comment]
@cachedout Ah, right, missed those, thanks. I've documented all methods (with links to Elasticsearch docs where necessary - like body definitions), I haven't documented the hosts and profile keywords as they are either already described in the top header or are salt-wide. Although pylint is throwing bunch of E1123 warnings on my laptop, seems it's fine on Jenkins.

**Comment by cachedout** [comment]
Squashed and merged. Thanks, @DarkKnightCZ

**Pull request merged**
