### PR TITLE
Merge forward 2017.7 to 2018.3

### PR DESCRIPTION
**Pull request by dwoz**
Merge forward 2017.7 to 2018.3

### CODE REVIEW

**Review by s0undt3ch — APPROVED** [review]

**Review by Akm0d — APPROVED** [review]

**Comment by dwoz** [comment]
re-run full all

**Comment by Ch3LL** [comment]
Will compile a list of test fixes as they are added here before this can be merged in:

https://github.com/saltstack/salt/pull/53967

**Comment by DmitryKuzmenko** [comment]
Continuation of the list:
#54099

**Comment by Ch3LL** [comment]
the ssdp failures will be fixed by https://github.com/saltstack/salt/pull/53919

**Comment by Ch3LL** [comment]
https://github.com/saltstack/salt/pull/54515

should fix `unit.modules.test_file.FilemodLineTests.test_line_insert_ensure_beforeafter_rangelines` failure

**Review by cmcmarrow — APPROVED** [review]

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
