### PR TITLE
return dicts from all boto_vpc functions

### PR DESCRIPTION
**Pull request by mgwilliams**
This is a considerable refactor of the `boto_vpc` execution module and dependant changes in the state module (not quite complete at time of writing). Some rudimentary tests for the state module are included.

Per discussions with @thatch45, @ryan-lane, @claudiupopescu, and @tsaridas, all functions in the `boto_vpc` execution module now return dicts, allowing more detailed error reporting to bubble up to the state module.

Additionally, several new functions have been added, and in many cases `*_name` can now be optionally passed instead of `*_id`.

I'm going ahead and opening this PR while I do final review and finish up the state module, so that others can test and comment.

### CODE REVIEW

**Comment by thedrow** [comment]
Hi, I wrote the VPC module :).
I think that you need to adjust more of the VPC module tests.
All assertions like https://github.com/saltstack/salt/blob/develop/tests/unit/modules/boto_vpc_test.py#L202 , https://github.com/saltstack/salt/blob/develop/tests/unit/modules/boto_vpc_test.py#L215 should be changed to test the fact that you are now returning a dictionary that has the right keys.
Also some of the VPC state tests fail.

I can't properly review this because there are too many commits.
Can you please squash and rebase?

**Comment by mgwilliams** [comment]
I have completed the synchronization of the state module with the execution module changes, and state module tests have been added. Per discussion with @rallytime, this is now in a state that it could be merged into develop. @claudiupopescu and I will be doing additional real-world testing in the coming days and pushing any required bug fixes and regression tests. I will also be actively watching bug reports for boto_vpc.

**Comment by thatch45** [comment]
@thedrow the files_changed tab not giving you a unified view?

**Comment by mgwilliams** [comment]
@thedrow I spent a bit of time trying to rebase and squash, but would have had to have resolved some very unpleasant conflicts once again. At any rate, I think the boto_vpc module changes need to be looked at as a whole. That said, the *Files changed* view is not working for the execution module. I find `vimdiff` useful in this situation: `git checkout mgwilliams/boto_dicts && git difftool develop  -- salt/modules/boto_vpc.py`

**Comment by thedrow** [comment]
The changes to the module's unit tests look good.
Well done.

**Comment by cachedout** [comment]
Looks like we're ready to go here. Merging. Thanks for the great work, @mgwilliams!

**Pull request merged**
