### PR TITLE
Adding accept_ra 2 option to modules.debian_ip

### PR DESCRIPTION
**Pull request by Natrinicle**
```
accept_ra - INTEGER
	Accept Router Advertisements; autoconfigure using them.

	It also determines whether or not to transmit Router
	Solicitations. If and only if the functional setting is to
	accept Router Advertisements, Router Solicitations will be
	transmitted.

	Possible values are:
		0 Do not accept Router Advertisements.
		1 Accept Router Advertisements if forwarding is disabled.
		2 Overrule forwarding behaviour. Accept Router Advertisements
		  even if forwarding is enabled.

	Functional default: enabled if local forwarding is disabled.
			    disabled if local forwarding is enabled.
```
https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt

### What does this PR do?
Currently, the Debian IP module only allows 0 or 1 but 2 is a valid
and sometimes required option. This allows 0, 1, or 2 to be used
and fixes the debian_eth template that currently replaces all
underscores with dashes.

### Previous Behavior
accept_ra wouldn't be placed into the interface config on Debian
hosts. Salt would also complain if accept_ra was set to 2.

### New Behavior
accept_ra gets put into the interface config and accepts 0, 1, or 2.

### Tests written?
**[NOTICE] Bug fixes or features added to Salt require tests.**
Please review the [test documentation](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html) for details on how to implement tests into Salt's test suite.

Yes

### Commits signed with GPG?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by twangboy — APPROVED** [review]

**Comment by twangboy** [comment]
Would you mind writing a unit test for this?

**Comment by Natrinicle** [comment]
> Would you mind writing a unit test for this?

Quite the ordeal trying to track down that change in the template. Had a few red herrings as the original commit I pushed fixed the issue on an older Salt version I'm running on my server. Finally realized that the template had changed in the develop branch and found the issue in the replace all underscores with dashes.

Let me know if there's anything else I can do or if there's something I missed.

**Review by cmcmarrow — APPROVED** [review]

**Comment by cmcmarrow** [comment]
@Natrinicle looks like you have a doc error.

**Comment by cmcmarrow** [comment]
re-run docs

**Comment by cmcmarrow** [comment]
re-run full docs

**Comment by Natrinicle** [comment]
> @Natrinicle looks like you have a doc error.

Looking in the console output for that unittest, it appears to be failing installing nox-py2 with pip.

```
21:50:55  + pip install -U nox-py2
21:50:53   > git rev-list --no-walk 340aa305b77a576d4ff1743be04befb1db9a8dd5 # timeout=10
21:51:03  Looking in indexes: https://artifactory.saltstack.net/artifactory/api/pypi/pypi-open/simple, https://pypi.python.org/simple
21:51:03  Collecting nox-py2
21:51:03    Downloading https://artifactory.saltstack.net/artifactory/api/pypi/pypi-open/packages/packages/06/a8/c6d4e57241a5189248ea6d45f61f60f2c035243239efa8a8e82a70368f00/nox_py2-2019.6.25-py2.py3-none-any.whl
21:51:03  Collecting virtualenv>=14.0.0 (from nox-py2)
21:51:04    Downloading https://artifactory.saltstack.net/artifactory/api/pypi/pypi-open/packages/packages/db/9e/df208b2baad146fe3fbe750eacadd6e49bcf2f2c3c1117b7192a7b28aec4/virtualenv-16.7.2-py2.py3-none-any.whl (3.3MB)
21:51:04  Collecting colorlog<4.0.0,>=2.6.1 (from nox-py2)
21:51:04    Downloading https://artifactory.saltstack.net/artifactory/api/pypi/pypi-open/packages/packages/d7/00/defed2a2eb8e289a0b6f29b3bcc52b42a75ce7cb14a84687c4c54d58f08e/colorlog-3.2.0-py2.py3-none-any.whl
21:51:04  Collecting py<2.0.0,>=1.4.0 (from nox-py2)
21:51:05    Downloading https://artifactory.saltstack.net/artifactory/api/pypi/pypi-open/packages/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl (83kB)
21:51:05  Installing collected packages: virtualenv, colorlog, py, nox-py2
21:51:05  Exception:
21:51:05  Traceback (most recent call last):
21:51:05    File "/var/jenkins/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 143, in main
21:51:05      status = self.run(options, args)
21:51:05    File "/var/jenkins/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 366, in run
21:51:05      use_user_site=options.use_user_site,
21:51:05    File "/var/jenkins/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
21:51:05      **kwargs
21:51:05    File "/var/jenkins/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 760, in install
21:51:05      use_user_site=use_user_site, pycompile=pycompile,
21:51:05    File "/var/jenkins/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 382, in move_wheel_files
21:51:05      warn_script_location=warn_script_location,
21:51:05    File "/var/jenkins/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pip/_internal/wheel.py", line 514, in move_wheel_files
21:51:05      for row in sorted(outrows):
21:51:05  TypeError: '<' not supported between instances of 'int' and 'str'
21:51:05  You are using pip version 18.1, however version 19.2.1 is available.
21:51:05  You should consider upgrading via the 'pip install --upgrade pip' command.
```

I don't believe this has anything to do with any of my changes as I didn't change any documentation nor docstrings and pip installations are done while setting up the environment before the tests even begin.

**Comment by Natrinicle** [comment]
@cmcmarrow I haven't changed anything with my pull request but I merged in the latest upstream branch with the button provided by Github in the changes dialog several times. All tests passed proving that the previous doc failure was not to do with this pull request. Is there anything else I need to do to get this PR accepted?

**Comment by cmcmarrow** [comment]
@Natrinicle sorry the doc error was not your fault

**Pull request merged**
