### PR TITLE
module and state for pdbedit

### PR DESCRIPTION
**Pull request by sjorge**
### What does this PR do?

Allow manipulation of samba's passdb using the pdbedit tool

(I was never happy with using cmd.run with plaintext passwords, just hashes left now 👍)

I had hoped to have this finished before carbon, but other stuff got in the way. Nitrogen it is then :)
### What issues does this PR fix or reference?

N/A
### Previous Behavior

Ugly cmd.run's to pdbedit or smbpasswd which leaked paswords: e.g.
https://github.com/saltstack-formulas/samba-formula/blob/master/samba/users.sls
### New Behavior

A simple clean state with a NTHASH (or plain text if you really want to)
As a bonus some addition stuff can be set like a drive letter and custom home.

``` yaml
    kaylee:
      pdbedit.managed:
        - password: A70C708517B5DD0EDB67714FE25336EB
        - password_hashed: True
        - drive: 'X:'
        - homedir: '\\\\serenity\\mechanic\\profile'
```

Comes with docs, this time I did not forget to enable doc-generation either ;)
### Tests written?

No

### CODE REVIEW

**Comment by cachedout** [comment]
Sweet. Thanks, @sjorge

**Comment by damon-atkins** [comment]
It would be nice if salt had provider options.
e.g.

```
fred:
  user.present:
    - provider: 'samba'
    - win_homedrive: 'x:'
    - win_profile:
    - win_logonscript:
    - win_description: 
    - fullname: Fred Jones
    - shell: /bin/zsh
    - home: /home/fred
    - uid: 4000
    - gid: 4000
    - groups:
      - wheel
      - storage
      - games
```

**Comment by sjorge** [comment]
I'm confused about this provider stuff? How does it work?

**Comment by damon-atkins** [comment]
It does not.  It would be wish.   
e.g.
If an OS has more than one package manager e.g. Solaris IPS & OpenCSW .   You can select which package manager you expect to implement the task.

If an OS has more than one user management option e.g. POSIX, LDAP, Samba  you can select which user  manager you expect to implement the task.

i.e. instead of __virtual__ determining what to use, you can override it.

The Salt need would need to implement it.

What I am saying is that  `user.*` should be the only interface to manipulating users.

By having an option called provider it would allow you to select the set of commands which are used to implement the task vs a new module with a new interface for adding users.

**Comment by sjorge** [comment]
That would be cool, although in this case it should sort of be an extend I guess. Which would also be cool to have.

**Pull request merged**
