### PR TITLE
Fixed Bug  LVM has no Filesystem Type , no Filesystem is not allowed

### PR DESCRIPTION
**Pull request by tyl0re**
In the moment (when fs_type is empty) the else 
```
 if fs_type:
        cmd = ('parted', '-m', '-s', '--', device, 'mkpart', part_type, fs_type, start, end)
    else:
        cmd = ('parted', '-m', '-s', '--', device, 'mkpart', part_type, start, end)
```
 is never reached.Since
```
if not _is_fstype(fs_type):
        raise CommandExecutionError(
```
Rises the condtion earlier.

An Empty Filesystem is needed for LVM Volumes

 The Check was in earlier Versions of salt it was correct in parted.py:
```
443     if fs_type and fs_type not in set(['ext2', 'fat32', 'fat16', 'linux-swap', 'reiserfs',
444                           'hfs', 'hfs+', 'hfsx', 'NTFS', 'ufs', 'xfs', 'zfs']):
```

So the check on not defined fs_type was forgotten on recoding 

### What does this PR do?
It Fixed the Bug , that Partion without Filesystem can be created like LVM
### What issues does this PR fix or reference?
It Fixed the Bug , that Partion without Filesystem can be created like LVM
### Previous Behavior
The Exception is rised when Filesystem type is empty

### New Behavior
Empty Filesystem type is Handled correct

### Tests written?

No

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by cmcmarrow** [comment]
Thanks @tyl0re for the PR. Can you also add a few tests for just the changes you made? This is so salt wont run into this bug again.

**Comment by tyl0re** [comment]
im not a good Programmer, it was a bug we ran in SALT in our Susemanger, We compared it with an earlier Version which behaved correct. So we have patched it with the condition from the old code and tested it in our susemanager . SO i thought it is a good idea to push it pack for all users.
Im not Familiar with writing test since i normally am only an user not an programmer.
Do you have an example test for partitioning?

**Comment by Ch3LL** [comment]
@tyl0re our documentation on our test suite is here: https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html
There are currently tests here: tests/unit/modules/test_parted_partition.py that you can look at. The key is to write a test that fails before your fix and passes with it. Let me know if i can give more direction.

**Comment by daks** [comment]
ref #54456

**Comment by daks** [comment]
We were hit by the same bug, trying to create a non-fstype partition for LUKS. The proposed patch works fine, thanks @tyl0re

**Comment by waynew** [comment]
@tyl0re I will make a couple of times this week available for showing how to write and (currently) run salt tests. I'll make sure to come back here and provide the calendar for it.

**Comment by waynew** [comment]
@tyl0re I believe you should be able to schedule a time [on my calendar](https://calendar.google.com/calendar/selfsched?sstoken=UURWQ2dRZDlKU0twfGRlZmF1bHR8OWU3N2NmZjgwODY5ODVjNGU3NWRhMTRhYTI4MDM3ZmY)

If nothing works for you during that time period, let me know what days work best for you and I'll add some more time next week!

**Comment by monofumado** [comment]
I forgot about this issue and updated to Salt 2019.2.2 and...the problem still happens, any news on this?

**Comment by 9numbernine9** [comment]
I just ran into this issue myself using Salt `2019.2.3`, but I'm assuming it's still an issue in `3000.0`. Is there any chance of this patch getting merged into `master`? As previously stated, it's basically impossible to create an LVM partition with `partition.mkpart` otherwise.

**Comment by Ch3LL** [comment]
looks like this just needs a test with the associated fix and added to the master branch instead of develop. Anyone willing to write a test here to ensure this does not regress and add to master and we can get this merged in? I'm more than willing to help out here.

**Review by sagetherage — CHANGES_REQUESTED** [review]
please rebase against the master branch

**Comment by piterpunk** [comment]
@sagetherage , I just wrote the test for this fix and rebased it to master in #58213

**Comment by sagetherage** [comment]
> @sagetherage , I just wrote the test for this fix and rebased it to master in #58213

great thank you! I will close this PR in favor of the new one rebased to master :)

**Pull request closed without merging**
