### PR TITLE
Add location support to file.line ensure

### PR DESCRIPTION
**Pull request by nicholasmhughes**
### What does this PR do?
This PR adds support for using the `location` argument with `mode=ensure` in the `file.line` module.

### What issues does this PR fix or reference?
N/A

### New Behavior
You can now use the `location` argument just as you can with `mode=insert`. Therefore, you do not need to specify another line in the file via `before` or `after` if `ensure` needs to add the line when it isn't matched and replaced.

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
This looks like a really interesting feature but I am extremely hesitant to accept it without tests being written.

**Comment by nicholasmhughes** [comment]
@cachedout , I took a stab at writing tests. Please take a look when you get a chance.

**Comment by cachedout** [comment]
@nicholasmhughes Thanks There are many additional files here now, though. I think you may have pushed the wrong branch. If you need to, please feel free to close this PR and submit a new one. Thanks and let me know if I can lend a hand. :]

**Comment by nicholasmhughes** [comment]
Opened #44246

**Pull request closed without merging**
