### PR TITLE
Fix #44583: splay with cron-like scheduled jobs

### LINKED ISSUE #44583: Using splay in cron schedule throws exception "unsupported operand type(s) for +: 'NoneType' and 'int'"
### Description of Issue/Question

I want to add a scheduled job so that all my minions run a highstate every night. When I set a fixed time for the job, everything works. However, when I add a splay time, the scheduled jobs aren't executed, and the minion logs contain only:
```
2017-11-17 14:56:00,089 [salt.minion      ][ERROR   ][18156] Exception unsupported operand type(s) for +: 'NoneType' and 'int' occurred in scheduled job
```

I added logging output to `utils/schedule.py` which points to the error coming from [this line](https://github.com/saltstack/salt/blob/5d719a2219908285d20ede02635f03b8b0e35b16/salt/utils/schedule.py#L1267), which adds the randomised splay time. When it runs, `data['_next_fire_time']` is `None`, which obviously cannot be added to.

That `None`, in turn, is explicitly set [a few lines before](https://github.com/saltstack/salt/blob/5d719a2219908285d20ede02635f03b8b0e35b16/salt/utils/schedule.py#L1256), in code added by @vutny in 6f967acdd76fb7cee61f1cc1cb8ff3ab66ab2b13, which I do not know enough Salt internals to understand the rationale for.

### Setup
```yaml
nightly-highstate:
  schedule.present:
    - function: state.highstate
    - returner: pgjsonb
    - cron: '56 14 * * *'
    - splay: 10
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

### PR DESCRIPTION
**Pull request by vutny**
### What does this PR do?
Tries to add "splay" time only if next job fire time is still in the future for cron tasks.

### What issues does this PR fix or reference?
#44583 

### Previous Behavior
Using `splay` with `cron` expression in scheduled job definition makes it fail each time when execution should be triggered.

### New Behavior
Scheduled "cron" job should be triggered if next fire time with addition of "splay" time has already passed in current loop interval.

### Tests written?
YES, added 4 basic test cases for `eval()` function.

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by garethgreenaway — APPROVED** [review]

**Comment by cachedout** [comment]
Hi @vutny 

Two things. First, this needs to go into the develop branch, please. Second, it needs some unit tests added. Thanks.

**Comment by vutny** [comment]
Hi @cachedout 

This PR is intended to fix the feature, that supposed to work in releases 2017.7.X, but was probably broken with previous changes (also made by me 😈 ). It would be very sad if it would remain non-working during all `2017.7` life-time.
Please-please, consider to include it in current stable version.
I could work on some unit tests in scope of this PR if you prefer, or submit a subsequent one.

FYI @creideiki

**Comment by creideiki** [comment]
@cachedout What @vutny said.

I hit the referenced issue (#44583) while trying to use functionality that is documented to be in 2017.7, but doesn't work there. I would strongly prefer getting this bugfix in the next stable update for 2017.7, instead of having to wait for the next major.

**Comment by rallytime** [comment]
@vutny If you could add some unit tests to this PR that would be greatly appreciated. We of course want to fix bugs in the stable releases as best as we can, but we certainly don't want to add regressions there inadvertently.

**Comment by vutny** [comment]
Will do!

**Comment by vutny** [comment]
@rallytime I've added 4 very basic unit tests to verify that periodic time definitions and cron-like schedules are parsed correctly and `splay` setting is taken into an account. I hope this would be a good start.
I think I could add some more in future PRs.

**Comment by rallytime** [comment]
@vutny Great! Thank you for adding those.

**Comment by rallytime** [comment]
re-run py3

**Comment by rallytime** [comment]
re-run py3

**Pull request merged**
