### PR TITLE
Implementing freebsd-status.cpustats

### PR DESCRIPTION
**Pull request by kim0**

### CODE REVIEW

**Comment by rodrigc** [comment]
Go, Ahmed, go!! :)

**Comment by kim0** [comment]
@thatch45 .. does this one look good ? coz I'll work on a couple more like it tonight .. Thanks!

**Comment by thatch45** [comment]
Yes @kim0 ! This looks great!

**Comment by rodrigc** [comment]
@kim0 is a lean, mean, devops machine!!

**Comment by kim0** [comment]
hehe thanks :) Actually I feel quite slow and sloppy .. but it's fun, so heh

**Pull request merged**
