### PR TITLE
Add salt.utils.path

### PR DESCRIPTION
**Pull request by terminalmage**
This module provides a unified interface for symlink handling for code which needs to run on both Windows and non-Windows platforms. This will allow for Windows masters to successfully handle Windows symbolic links in the roots fileserver backend.

Code for reading and detecting links has been moved from win_file.py into this new module, and modified slightly to behave more like its *NIX counterpart.

EDIT: I've also cherry-picked @twangboy's initial commit from #39698 and made some changes on top of it, including a rewritten symlink test in the roots fileserver integration tests. This makes #39698 obsolete.

I don't have the means to test the code I wrote for Windows in the test suite, so we'll have to see how it works once this test is run on a Windows box.

### CODE REVIEW

**Review by s0undt3ch — APPROVED** [review]

**Comment by twangboy** [comment]
@terminalmage Since this is a Window specific salt util, it should have a `win_` prefix.

**Comment by terminalmage** [comment]
No, it _isn't_ Windows-specific. That's kind of the point of it. It is platform-independent, so the functions in the module can be run on any platform. This keeps you from needing to do a ``salt.utils.is_windows()`` check everywhere you need to handle something differently on Windows.

**Comment by terminalmage** [comment]
Rebased, a merged PR caused a conflict.

**Comment by terminalmage** [comment]
Tests were passing before the rebase, so they should be green.

**Review by s0undt3ch — APPROVED** [review]

**Comment by s0undt3ch** [comment]
This needs another rebase @terminalmage

**Comment by terminalmage** [comment]
rebased

**Pull request merged**
