### PR TITLE
Fix infinite recursion in state compiler for prereq of SLSs

### PR DESCRIPTION
**Pull request by jacksontj**

### CODE REVIEW

**Comment by jacksontj** [comment]
Tests are passing on ubuntu, didn't run on either centos version. Re-triggering a build.

**Comment by jacksontj** [comment]
@jfindlay Tests are passing :)

**Comment by jacksontj** [comment]
@cachedout not sure who wants to review this?

**Comment by cachedout** [comment]
@jacksontj I was asked by @thatch45 to hold on this one until after 2015.8.2. I'll see if he's around and can comment further.

**Comment by thatch45** [comment]
Thanks @jacksontj ! If it is alright I would like to wait a few more days on this one until we can tag the next point release. I don't like merging state system fixes/changes right before a point release.

**Comment by jacksontj** [comment]
We can wait, although it is a bug fix ;) If we wait I guess it'll just make it into 2015.8.3 then.

**Comment by thatch45** [comment]
right, thanks :)

**Pull request merged**
