### PR TITLE
zypperpkg: do not interfere with advisory_ids

### PR DESCRIPTION
**Pull request by aplanas**
When a patch is installed via advisory_ids, we do not want to change the
behavior of list_pkgs, via the includes field.

Currently, if a patch is installed via advisory_ids (state
pkg.patch_installed), it will call zypperpkg.install with this parameter
inside kwargs. This parameter is parsed by pkg_resource.parse_targets,
and the prefix `patch:` will be added very early, just before taking the
list of the current packages.

This last step will change the behavior of list_pkgs, as all the other
patches will be listed.

This sound OK except when we want to maintain the old behavior, when
patches are not listed in the `install` function by default.

This patch will add the `patch:` prefix in the list of targets later,
once we have the list of packages, restoring the old behavior.

Note that we can still install a patch as a normal package, if we add
the prefix in the name before calling `install`, and we do not use the
`advisory_ids` field.

### Tests written?

No. This is a partial revert of https://github.com/saltstack/salt/pull/52412, so this should be covered by the current tests.

### CODE REVIEW

**Comment by aplanas** [comment]
@brejoc @dincamihai alternative fix without adding an extra parameter (not validated in SUMA)

**Comment by dincamihai** [comment]
> Note that we can still install a patch as a normal package, if we add
the prefix in the name before calling install, and we do not use the
advisory_ids field.

does this mean we have to adapt all the calls to pkg.install and append `patch:` prefix when we install a patch?

**Comment by aplanas** [comment]
> > Note that we can still install a patch as a normal package, if we add
> > the prefix in the name before calling install, and we do not use the
> > advisory_ids field.
> 
> does this mean we have to adapt all the calls to pkg.install and append `patch:` prefix when we install a patch?

No.

This patch revert the part from https://github.com/saltstack/salt/pull/52412 that interfere with the `pkg.patch_installed` state.

Before this patch or the previous one you always can use `salt-call pkg.install 'patch:mypatch` or `salt-call pkg.install 'pattern:mypatch'`. The pattern or the patch will be installed, but the comparison at the end of the module will fail. This is what was fixed in https://github.com/saltstack/salt/pull/52412

**Review by xeacott — APPROVED** [review]

**Comment by aplanas** [comment]
I moved the patch into https://github.com/saltstack/salt/pull/54954, as this is a fix related with this change. With this I consider this patch rebased into develop. Please, review on the new place.

**Pull request closed without merging**
