### PR TITLE
Remove virt.pool_delete fast parameter

### PR DESCRIPTION
**Pull request by cbosdo**
### What does this PR do?

There are two reasons to remove this parameter without deprecating it:
 * the meaning has been mistakenly inversed
 * fast=True will raise an exception for every libvirt storage backend
since that flag has never been implemented in any of those.

### What issues does this PR fix or reference?

Fixes issue #54474

### Previous Behavior

`salt 'kvmsrv' virt.pool_delete mypool` fails with a libvirt exception

### New Behavior

`salt 'kvmsrv' virt.pool_delete mypool` actually deletes the pool is that function is supported by the libvirt storage backend.

### Tests written?

No, trivial function even when the fast parameter existed, even simpler now.

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by xeacott** [comment]
I took a look at this PR and the area of code it touches, and I am certainly no expect but I see that you @cbosdo have quite a lot of code in this file so I will approve it. However, I will ask that you rebase and target `master` with your PR. This is quite a recent change with branching strategy and we're expecting it to make releasing in the future much easier and less problematic 😄

**Review by xeacott — APPROVED** [review]

**Comment by cbosdo** [comment]
@xeacott rebased on master and added a unit tests for that function... even though it doesn't test that parameter removal

**Comment by xeacott** [comment]
Thank you!

**Comment by dwoz** [comment]
The windows tests are passing but the build failed due to some left open file handles.

**Review by dwoz — APPROVED** [review]

**Pull request merged**
