### PR TITLE
[develop] Fix to scheduler logic handling global settings

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Fixing a typo in the scheduler logic where we look for attributes in the dictionary that are global settings and not schedules.

### What issues does this PR fix or reference?
#45320

### Tests written?
Yes.  Tests exist.

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
@garethgreenaway It looks like your scheduler tests are failing here.

**Comment by vnitinv** [comment]
@garethgreenaway Can you please look into the test failures so that code can be merged as I need the fix for my use case.

**Comment by garethgreenaway** [comment]
@vnitinv the fix that I think you're referring to was already merged into develop in another PR.  This PR just contains tests.

**Comment by garethgreenaway** [comment]
This turned into a mess.  I'm going to move the changes over to the other open scheduler PR and close this one out.

**Comment by garethgreenaway** [comment]
Closing in favor of https://github.com/saltstack/salt/pull/46142

**Pull request closed without merging**
