### PR TITLE
Bugfix/rework: IPv6 scope errors

### PR DESCRIPTION
**Pull request by isbm**
### What does this PR do?

- Fixes IPv6 scope issues that aren't supported in Python `ipaddress`.
- Support IPv6 scope at `IPv6Address` object level.
- Reworks `salt._compat` for code duplication and other issues
- Fixes import of `ipaddress` across everywhere
- Uses proper `ipaddress` instance for Python 3
- Adds debug logging instead of just `pass`.

### Previous Behavior

If your `/etc/resolv.conf` has a scope in IPv6 address, something like this:

`nameserver fe80::20d:b9ff:fe01:ea8%eth0`

...then you are getting errors like this:
```
  2018-09-15 13:14:45,014 [salt.utils.dns   :1039][ERROR   ][845] 
  /etc/resolv.conf: u'fe80::20d:b9ff:fe01:ea8%eth0' does not
  appear to be an IPv4 or IPv6 address
```

This is hitting users since 2016: https://github.com/saltstack/salt/issues/37949

### New Behavior

:metal:  :sunglasses: :metal: 

### Tests written?

Existing should just pass.

### CODE REVIEW

**Comment by isbm** [comment]
OK, Py2 seems unhappy, Py3 is just fine.

**Comment by isbm** [comment]
@rallytime dat lint... JFYI: It should be muted, because we _have_ to shadow that method. But I can't find a number or a name of it to disable.

**Review by terminalmage — APPROVED** [review]

**Comment by terminalmage** [comment]
Looks good aside from the lint failures.

**Review by cachedout — APPROVED** [review]
LGTM

**Comment by terminalmage** [comment]
@isbm this should fix the lint failure. The failure was happening because you defined `_is_packed_binary` as a function and then separately also defined that attribute as a lambda in the `__init__()`.

```diff
diff --git a/salt/_compat.py b/salt/_compat.py
index c15cb84d80..3652655b7c 100644
--- a/salt/_compat.py
+++ b/salt/_compat.py
@@ -156,10 +156,6 @@ class IPv6AddressScoped(ipaddress.IPv6Address):
             ipaddress._BaseAddress.__init__(self, address)
             ipaddress._BaseV6.__init__(self, address)
         else:
-            # This method (below) won't be around for Python 3
-            # and this type is needed to be checked differently
-            self._is_packed_binary = lambda p: isinstance(p, bytes)
-
             # Python 3.4 fix. Versions higher are simply not affected
             # https://github.com/python/cpython/blob/3.4/Lib/ipaddress.py#L543-L544
             self._version = 6
@@ -185,6 +181,9 @@ class IPv6AddressScoped(ipaddress.IPv6Address):
         :param data:
         :return:
         '''
+        if sys.version_info.major != 2:
+            return isinstance(data, bytes)
+
         packed = False
         if len(data) == 16 and ':' not in data:
             try:
```

**Review by meaksh — APPROVED** [review]
Looks good :+1:

**Comment by rallytime** [comment]
Hi @isbm! 😄 

There are some test failures that are related to this change:

- integration.ssh.test_jinja_filters.SSHJinjaFiltersTest.test_network_ipaddr
- unit.utils.test_jinja.TestCustomExtensions.test_ipaddr
- unit.utils.test_jinja.TestCustomExtensions.test_ipv4
- unit.utils.test_jinja.TestCustomExtensions.test_ipv6
- unit.utils.test_jinja.TestCustomExtensions.test_is_ip
- unit.utils.test_jinja.TestCustomExtensions.test_is_ipv4
- unit.utils.test_jinja.TestCustomExtensions.test_is_ipv6

Can you take another look? 😎 

https://jenkinsci.saltstack.com/job/pr-kitchen-centos7-py3/job/PR-49705/9/

**Review by gtmanfred — APPROVED** [review]

**Comment by aphor** [comment]
FWIW, upstream in Python we have precedent to suggest upstream fixes in ipaddress module.
 * https://bugs.python.org/issue23448
 * https://bugs.python.org/issue29375

so I submitted https://bugs.python.org/issue34788

**Comment by isbm** [comment]
@aphor this doesn't really help, I've been there already. First, the issue is like three years old. Second, even they will fix in some upcoming versions, we still need this even on 2.7 and SUSE on 2.6 that is just simply EOL.

**Comment by aphor** [comment]
@isbm I agree completely salt should not wait for upstream fix, but this is technical debt which would ideally be factored out of salt, and FWIW, salt isn't the only Python utility that I need to support IPv6.

I put that stuff here, mostly because it will be useful in the future to have it here, for reference, not to imply we should not merge this PR into salt.

**Comment by isbm** [comment]
@aphor after @rallytime puts that in (I am also going to backport that to 2018.3) let's look again at your PR. I am keeping an eye on yours and if you need any help, please ping me.

**Review by twangboy — APPROVED** [review]

**Comment by avolmensky** [comment]
I have been playing around with 2019.02 and the netbox pillar module is broken with Python 3. The changes in this PR fix the problem I have been having. Will this be merged into the 2019.02 release?

**Pull request merged**
