### PR TITLE
btrfs: Add properties state

### PR DESCRIPTION
**Pull request by aplanas**
### What does this PR do?

We can set via `btrfs property` command some properties. This command
is used in the btrfs execution module.

The current state will leverate this code to make sure that some
properties al set or unset in a safe mode.

### Tests written?

Yes

### CODE REVIEW

**Comment by aplanas** [comment]
WIP: Not ready for reviews

**Comment by aplanas** [comment]
What is the opinion about the code climate complains? Some of them are weird to me.

**Comment by aplanas** [comment]
Ready for reviews : )

**Comment by waynew** [comment]
@aplanas Yeah, we're (gradually) tuning the checks. Most of them are a little aggressive for what we need. We take the advice with a heaping spoonful of salt :trollface:

**Comment by aplanas** [comment]
Rebased on top of https://github.com/saltstack/salt/pull/54962, that is also rebased on master. Once the other one is merged, I can rebase on top of the real master.

**Review by dwoz — APPROVED** [review]

**Review by dwoz — CHANGES_REQUESTED** [review]
@aplanas The copyright should be removed from these files.

**Comment by aplanas** [comment]
> @aplanas looks like there's a lint issue: https://jenkinsci.saltstack.com/job/pr-lint/job/PR-52699/21/analysis/new/source.64846dc0-56c9-4a81-9f92-004e39b0ed41/#42

Uuhm this file is not from my PR, but from some django_return.py codebase. Let me rebase and run the tests again.

**Comment by aplanas** [comment]
Yep. Ignore the lint, is not related with my code:

************* Module salt.returners.django_return
salt/returners/django_return.py:42: [E0611(no-name-in-module), ] No name 'dispatch' in module 'django'

------------------------------------
Your code has been rated at 10.00/10

**Comment by waynew** [comment]
Just merged master in - twice it was missing ` ERROR: /var/lib/jenkins/workspace/pr-pre-commit_PR-52699@script/.ci/pre-commit not found` so I *think* it was missing the ci file that Pedro added a couple of days ago. :crossed_fingers:

**Comment by waynew** [comment]
@aplanas looks like it needs some pre-commit hooks executed. If you haven't yet, [quickstart docs](https://docs.saltstack.com/en/master/topics/development/contributing.html#quickstart) has a guide on setting it up.

**Comment by aplanas** [comment]
The fails now is about missing documentation. How can I generate it?

**Comment by waynew** [comment]
Did you get the docs figured out? I'm not seeing any failure messages about that (though we did recently merge a PR that would fail if the module lacks an entry in the `docs/` folder.

I am seeing this failure, which looks definitely related: https://jenkinsci.saltstack.com/job/pr-fedora30-py3/job/PR-52699/27/testReport/junit/unit.states.test_btrfs/BtrfsTestCase/test_properties_test/

**Comment by aplanas** [comment]
Yes, documentation issue figure out. I fixed the test case, was a bad rebase.

**Comment by dwoz** [comment]
@waynew Look good now?

**Review by waynew — APPROVED** [review]
@dwoz LGTM :+1:

**Pull request merged**
