### PR TITLE
[master] Allow unsigned but trusted apt repositories

### LINKED ISSUE #64130: [BUG]pkgrepo.managed (apt) ignores [trusted=yes]
**pkgrepo.managed (apt) ignores [trusted=yes]**
Since we upgraded our system from Salt V3004.2 to V3005.1, the following problem occurs:
When trying to add an unsigned repository, e.g.: "deb [trusted=yes] http://reposerver.net/ubuntu/focal main", there is an error "E: The repository 'http://reposerver.net/ubuntu Focal Release' is unsigned."

**Setup**
```
       ID: repositories_managed_repository_ubuntu-3rd
 Function: pkgrepo.managed
     Name: deb  [trusted=yes] http://reposerver.net/ubuntu/  focal main
   Result: False
  Comment: Failed to configure repo 'deb  [trusted=yes] http://reposerver.net/ubuntu/  focal main': E: The repository 'http://reposerver.net/ubuntu focal Release' is not signed.
  Started: 10:31:53.925434
 Duration: 4487.955 ms
  Changes:   
```
Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [x] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
```yaml
test_unsigned_repo:
  pkgrepo.managed:
    - humanname: unsigned_repo
    - name: deb [trusted=yes] http://reposerver.net/ubuntu main
    - file: /etc/apt/sources.list.d/unsigned_repo_test
```

```
Reading package lists...
2023-04-21 09:47:26,053 [salt.loaded.int.module.cmdmod:909 ][ERROR   ][278327] stderr: E: The repository 'http://reposerver.net/ubuntu focal Release' is not signed.
2023-04-21 09:47:26,053 [salt.loaded.int.module.cmdmod:911 ][ERROR   ][278327] retcode: 100
2023-04-21 09:47:26,054 [salt.state       :321 ][ERROR   ][278327] Failed to configure repo 'deb  [trusted=yes] http://reposerver.net/ubuntu/  focal main': E: The repository 'http://reposerver.net/ubuntu focal Release' is not signed.
2023-04-21 09:47:30,931 [salt.loaded.int.module.cmdmod:905 ][ERROR   ][278327] Command 'apt-get' failed with return code: 100
2023-04-21 09:47:30,931 [salt.loaded.int.module.cmdmod:907 ][ERROR   ][278327] stdout: Ign:1 http://reposerver.net/ubuntu focal InRelease

```

**Expected behavior**
The expected source list file should look like this

`deb  [trusted=yes] http://reposerver.net/ubuntu/  focal main`

After completion of the state it looks like this:

`deb http://reposerver.net/ubuntu/  focal main`

**Versions Report**

<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
salt-call --versions-report
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.16 (main, Jan  6 2023, 22:49:56)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-147-generic
        system: Linux
       version: Ubuntu 20.04 focal
```

**Additional context**

### PR DESCRIPTION
**Pull request by pckroon**
### What does this PR do?
In newer salt apt repositories managed by https://docs.saltproject.io/en/latest/ref/states/all/salt.states.pkgrepo.html#salt.states.pkgrepo.managed *must* have either a signedby or a valid key. However, for locally hosted repositories, the `trusted=yes` option should also suffice.

I made the parsing of repo options a bit smarter, taking the man page of sources.list as a reference. Then I adapted `modules.aptpkg.mod_repo` to accept `trusted=yes` for unsigned repositories.

### What issues does this PR fix or reference?
Fixes: #64130

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs (N/A?)
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated (I think?)

I'm not sure changes to docs are very relevant to this, but I'm very happy to be corrected :)
I *think* I managed with the tests. I only found the testing docs when opening this PR. Nox is currently running locally, so I might have to come back with some corrections.

### Commits signed with GPG?
Yes (but github doesn't like them, never managed to figure out why)

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by Ch3LL** [comment]
Looks like there are some test failures related to this change. Mind cleaning those up and then i'll give this a proper review?

**Comment by pckroon** [comment]
I'd be happy to. I'm not sure I'll manage today though, so I may only get to it on Monday.

**Comment by pckroon** [comment]
Hellohello,

For some reason the unittest for `test_mod_repo_match` mocks the function `_split_repo_str` (https://github.com/saltstack/salt/blob/master/tests/pytests/unit/modules/test_aptpkg.py#LL790C34-L790C34), and I don't quite understand why. 
So I figured I'd ask before I rip things out of that test.

**Comment by Ch3LL** [comment]
If you can make the test consistent while not mocking that function I think its fine to take that out.

**Comment by pckroon** [comment]
Alright. I still have failing tests locally, but those also fail on master for me.
I don't quite understand how or why my change caused the failure in `test_mod_repo_match`, hence the rather heavy-handed fix. 
I also took the freedom to clean the with-mock nesting in that test a little. There's probably still some code style lint to clean

**Comment by pckroon** [comment]
I can't make heads nor tails from the code flow around the tests, so unless someone is willing to step in and give me a hand I'll abandon this.

**Comment by vveliev-tc** [comment]
@Ch3LL any update on this PR ?

**Pull request closed without merging**
