### PR TITLE
Many improvements and changes for the netacl modules

### PR DESCRIPTION
**Pull request by mirceaulinic**
### What does this PR do?

- Because the order is important, instead of requiring dictionaries for filters and terms, they should be specified as list instead.

Previously a structure example was:

```yaml
acl:
  my-filter:
    options:
      - inet6
    my-term:
      source_port: [1234, 1235]
      protocol:
        - tcp
        - udp
      source_address: 1.2.3.4
      action: reject
    my-other-term:
      source_port:
        - [5678, 5680]
      protocol: tcp
      action: accept
```

which now becomes:

```yaml
acl:
  - my-filter:
      options:
        - inet6
      terms:
        - my-term:
            source_port: [1234, 1235]
            protocol:
              - tcp
              - udp
            source_address: 1.2.3.4
            action: reject
        - my-other-term:
            source_port:
              - [5678, 5680]
            protocol: tcp
            action: accept
```

- more useful notes in the doc
- added `netacl.get_filter_pillar` and `netacl.get_term_pillar` helpers useful inside the SLS, to retrieve faster the config of a certain entity just passing its name

Ping @bewing

### CODE REVIEW

**Comment by lorengordon** [comment]
Did you try `collections.OrderedDict()`? It's a representation of a list of dictionaries, but allows you to use dictionary methods. It's a bit of a pain to convert from a an actual list of dicts to an OrderedDict, but it _can_ be done with a fairly simple list comprehension...

**Comment by lorengordon** [comment]
for example:
```
>>> import collections
>>> foo = [{'foo': 'bar'}, {'baz':'bar'}]
>>> bar = collections.OrderedDict([(list(_.keys())[0], list(_.values())[0]) for _ in foo])
>>> bar
OrderedDict([('foo', 'bar'), ('baz', 'bar')])
>>> bar['foo']
'bar'
>>> bar['baz']
'bar'
````

**Comment by mirceaulinic** [comment]
Hi @lorengordon - yes, that's a good idea. Let me investigate this and see how it would simplify the code. Thanks!

**Comment by mirceaulinic** [comment]
Hrm, the input data is hierarchical and the ordered dict must be at multiple levels so it turns out to more complicated than I thought. I think I will leave it like that for the moment and revisit later as a code improvement.

**Comment by lorengordon** [comment]
Oh, there are tiers of OrderedDicts? I was just going by the `terms` example in the PR description, which fits exactly into an OrderedDict.

**Comment by lorengordon** [comment]
Oh I see, the filter was also modified to be a list. Missed that part earlier.

**Comment by mirceaulinic** [comment]
Yes, also the first level must be ordered, for example:

```yaml
acl:
  - my-filter:
      options:
        - inet6
      terms:
        - my-term:
            source_port: [1234, 1235]
            protocol:
              - tcp
              - udp
            source_address: 1.2.3.4
            action: reject
        - my-other-term:
            source_port:
              - [5678, 5680]
            protocol: tcp
            action: accept
  - my-other-filter: {}
```

So the order matters also under `terms` as you pointer out, but also directly under `acl` so the order has to remain as `my-filter`, `my-other-filter`.

Sure, it's not rocket science to make it like that, just that I'm a bit tired right now and I'd incline to revisit later.

**Comment by lorengordon** [comment]
Gotcha, here's a simple helper to convert the list.

```
def _to_ordered_dict(lst):
    try:
        return(collections.OrderedDict([(list(_.keys())[0], list(_.values())[0]) for _ in lst]))
    except AttributeError:
        # Poorly formatted `lst`
```

**Comment by cachedout** [comment]
@mirceaulinic Will you be able to swing back to this one to follow up with @lorengordon ?

**Comment by mirceaulinic** [comment]
Hi @cachedout - Unfortunately I will not have the time till the end of April. I need to finish other priorities this week before vacation. So, please merge this and I will revisit later when I may bring some other improvements beside @lorengordon's suggestion. Thanks!

**Comment by cachedout** [comment]
Merged. Thanks, @mirceaulinic

**Pull request merged**
