### PR TITLE
ssh: AuthorizedKeysFile expands defined tokens

### PR DESCRIPTION
**Pull request by txomon**
The idea is that ssh supports %h and %u tokens, and it is a pain in the ass to make this from anywhere else, seen that ssh_auth state exists here.

### CODE REVIEW

**Comment by jfindlay** [comment]
@txomon, thanks for the changes and the tests.  Will you also fix the associated lint and test failures?  Thanks.

**Comment by txomon** [comment]
Sure, I coded that blindly from a notepad. I will try to fix it asap =)

**Comment by jfindlay** [comment]
@txomon, no problem, take the time you need, there seem to be many tests involved. :-)

**Comment by txomon** [comment]
I was just going to say that... I don't fully understand all the results,
just the one about unused variables etc

**Comment by jfindlay** [comment]
@txomon, fix what you can and I'll look at the rest, thanks.

**Comment by txomon** [comment]
I have fixed (once again) from notepad, and mainly looking at https://jenkins.saltstack.com/job/salt-pr-lint-n/5331/console

I will try to fix other stuff if I get time, but it might take me this weekend (don't have much time for this)

**Comment by txomon** [comment]
OK, I think I fixed the lint errors, but I don't understand the output of the others...

**Pull request merged**
