### PR TITLE
Fix requisites missing from pyobjects that were introduced in 2014.7

### LINKED ISSUE #20652: pyobjects renderer doesn't support onchanges/onfail requisites
Hello,

when I try to use onchanges/onfail requisite with pyobjects render it fails with message:
TypeError encountered exeuting state.highstate: 'StateRequisite' object is not iterable. See debug log for more info.

### PR DESCRIPTION
**Pull request by borgstrom**
This fixes #20652, @tomashavlas added the fix to develop in 27868d6 but it wasn't ever backported to 2014.7.

This should definitely be added to the next 2014.7 & 2015.2 releases.  Do you need me to submit a PR for 2015.2?

### CODE REVIEW

**Comment by jfindlay** [comment]
@borgstrom, if it will merge forward cleanly, then that shouldn't be necessary, thanks.

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by borgstrom** [comment]
@jfindlay cool.  Looks like the jenkins failures are something systemic.  Let me know if there's anything to be addressed.  Thanks!

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
Looks like the jenkins build just failed to run, you know, cloud....

**Pull request merged**
