### PR TITLE
State top saltenv

### PR DESCRIPTION
**Pull request by thatch45**
Add the ability to specify a single environment to pull top files from, this allows the user to set the `state_top_saltenv` config option on the master for all minions, on the minion, or via state.top execution. This will make it so that only one top file is used from the specified salt environment.

### CODE REVIEW

**Comment by whiteinge** [comment]
Hawt!

**Comment by UtahDave** [comment]
@thatch45, I'm trying to make sure I understand the intent of this PR. Does this mean that I can specify in my master config to always use the `top.sls` in my `foo` environment regardless of the existence of other `top.sls` files in other environments? Or does this just work with `state.top` ?

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by ryancurrah** [comment]
The reason we want to be able to specify the branch to use for states and pillars in a salt repo without the top files from all the branchs being merged. Which is the issue we were seeing when branching. We have a Salt repo which follows the git flow style of development. Meaning we have branch for develop, release/blah, and master. All these branchs are exactly the same, just we develop new states in develop branch, test our new features in release, and leave master for our production systems. What we saw was when we hooked gitfs backend to our repo with all the branches that it would merge all the top.sls files from every branch which was not desired at all. So our goal is to be able to Salt Master just only use the pillars and states from X branch, do merge top fles or anything.

**Comment by whiteinge** [comment]
@ryancurrah this has been a long-standing pain point for many others as well. This change will be a popular one. Thanks for the push to add an alternative!

**Comment by ryancurrah** [comment]
@whiteinge Thanks! I hope my comment gives some context as to the issue were trying to solve.

**Comment by ryancurrah** [comment]
Also based on the code, I see no reference to the pillars. I already got the states to stop merging top files by specifying a whitelist http://docs.saltstack.com/en/latest/topics/tutorials/gitfs.html#environment-whitelist-blacklist.

It's the pillars I was never able to target a specific branch.

**Comment by ryancurrah** [comment]
It's this feature that doesnt work, http://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.git_pillar.html#salt.pillar.git_pillar.GitPillar.map_branch. The following issues was created to resolve this... https://github.com/saltstack/salt/issues/22681

**Pull request merged**
