### PR TITLE
only run pylint on files that change

### PR DESCRIPTION
**Pull request by gtmanfred**
### What does this PR do?
Only run pylint on files that change

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by KaiSforza — COMMENTED** [review]
Confirmed to work. :+1:

**Review by KaiSforza — APPROVED** [review]

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
@terminalmage You'll be interested in this for #47337

**Comment by cachedout** [comment]
@gtmanfred Are you ready for a merge here?

**Comment by gtmanfred** [comment]
Yes

**Pull request merged**
