### PR TITLE
salt.modules.zfs

### LINKED ISSUE #28779: salt.module.zpool and salt.module.zfs could use some love.
Looks like the output is just a simple dump of the text output of the commands, e.g.:

```/opt/local/salt/bin/salt-call --local zpool.list```
```yaml
local:
    ----------
    pools:
        - NAME      SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
        - archive  21.8T  10.5T  11.2T         -      -    48%  1.00x  ONLINE  -
        - data     1.81T   546G  1.28T         -    13%    29%  1.00x  ONLINE  -
        - zones     111G  40.8G  70.2G         -    53%    36%  1.00x  ONLINE  -
```

```/opt/local/salt/bin/salt-call --local zpool.status zones```
```yaml
local:
    -   pool: zones
    -  state: ONLINE
    -   scan: scrub repaired 0 in 0h4m with 0 errors on Mon Nov  9 02:04:09 2015
    - config:
    -     NAME        STATE     READ WRITE CKSUM
    -     zones       ONLINE       0     0     0
    -       mirror-0  ONLINE       0     0     0
    -         c2t0d0  ONLINE       0     0     0
    -         c2t1d0  ONLINE       0     0     0
    - errors: No known data errors
```

```/opt/local/salt/bin/salt-call --local zpool.status``` does not work:
```yaml
local:
    - cannot open '': name must begin with a letter
```
While it is perfectly fine to request info for all zpools!

```bash
[root@core ~]# zpool status
  pool: zones
 state: ONLINE
status: Some supported features are not enabled on the pool. The pool can
        still be used, but some features are unavailable.
action: Enable all features using 'zpool upgrade'. Once this is done,
        the pool may no longer be accessible by software that does not support
        the features. See zpool-features(5) for details.
  scan: scrub repaired 0 in 0h4m with 0 errors on Mon Nov  9 02:04:09 2015
config:

        NAME        STATE     READ WRITE CKSUM
        zones       ONLINE       0     0     0
          mirror-0  ONLINE       0     0     0
            c2t0d0  ONLINE       0     0     0
            c2t1d0  ONLINE       0     0     0

errors: No known data errors
```

Looking at the code the seems looks to be true for salt.modules.zfs but it is not working on SmartOS at the moment, although the zfs command is available.

```
[root@core ~]# /opt/local/salt/bin/salt-call --local zfs.list
[INFO    ] Executing command 'pkg_info -Q LOCALBASE pkgin' in directory '/root'
'zfs' __virtual__ returned False
```

### PR DESCRIPTION
**Pull request by sjorge**
Last part to close #28779

Pinging @nmadhok so he is aware of the chances.

I'm not sure what to do with the 'auto-generated' commands, the code doesn't seem to work on illumos or solaris. Once all the other commands are implemented there may not be any need to keep it?

``` bash
/opt/local/salt/bin/salt-call --local zfs.list test recursive=True
```

``` yaml
local:
    ----------
    test:
        ----------
        avail:
            79.9M
        mountpoint:
            /test
        refer:
            19K
        used:
            138K
    test/dataset1:
        ----------
        avail:
            79.9M
        mountpoint:
            /test/dataset1
        refer:
            19K
        used:
            19K
    test/dataset2:
        ----------
        avail:
            79.9M
        mountpoint:
            /test/dataset2
        refer:
            19K
        used:
            19K
```

``` bash
/opt/local/salt/bin/salt-call --local zfs.diff test/ds1@clean test/ds1 show_changetime=True
```

``` yaml
local:
    - 1450886500.730159657        M       /       /test/ds1/
    - 1450886500.730258359        +       F       /test/ds1/hello
```

``` bash
/opt/local/salt/bin/salt-call --local zfs.holds test/ds1@baseline
```

``` yaml
local:
    ----------
    test/ds1@baseline:
        ----------
        important  :
            Wed Dec 23 21:06 2015
        release-1.0:
            Wed Dec 23 21:08 2015
```

``` bash
/opt/local/salt/bin/salt-call --local zfs.get test depth=1 properties='compression,canmount' type=filesystem
```

``` yaml
local:
    ----------
    test:
        ----------
        canmount:
            ----------
            source:
                default
            value:
                on
        compression:
            ----------
            source:
                default
            value:
                off
    test/ds1:
        ----------
        canmount:
            ----------
            source:
                local
            value:
                noauto
        compression:
            ----------
            source:
                local
            value:
                lz4
    test/ds2:
        ----------
        canmount:
            ----------
            source:
                default
            value:
                on
        compression:
            ----------
            source:
                default
            value:
                off
```

### CODE REVIEW

**Comment by cachedout** [comment]
Please ping me when this is done and ready to go, @sjorge . Thanks!

**Comment by sjorge** [comment]
@cachedout done, It's really late now, I will check on this PR tomorrow.

I was considering leaving the dynamic (maybe broken, but mostly useless now) code in place (last commit) but removing them has made the loading and execution of the zfs module so much faster! 

Everything aside zfs allow/unallow is now implemented in the module. Everything should also have a test/tests now.

I will probably do the zfs state module once I am back from my trip to Stockholm next year. (Or friday if I am not too tired ;) )

**Comment by sjorge** [comment]
Was thinking about the state module I want to write over the christmas dinner and came up with a few small improvements, mostly to how the errors are handled.

**Comment by cachedout** [comment]
@sjorge This all looks great! Just two small lint errors to fix up and I will get this in. Nice work!

**Comment by sjorge** [comment]
That should fix the lint error, on mobile in sweden so fingers crossed.

**Comment by cachedout** [comment]
Great! Thanks, @sjorge

**Comment by cachedout** [comment]
Merged! Thanks again @sjorge

**Pull request merged**
