### PR TITLE
adding states/postgres_user unit test case.

### PR DESCRIPTION
**Pull request by jayeshka**
Implemented states/postgres_user_test unit test case.

### CODE REVIEW

**Comment by jfindlay** [comment]
There are some failures here as well.

**Comment by jayeshka** [comment]
@jfindlay These failures are same as of #24330.
Running at my end on updated branch.

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Pull request merged**
