### PR TITLE
Implemented unit test cases for module environ

### PR DESCRIPTION
**Pull request by rupeshta**
Implemented unit test cases for module environ

### CODE REVIEW

**Comment by thatch45** [comment]
@rupeshta looks like these environ tests are failing

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
@rupeshta please fix your failing tests so that we can merge this

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
@rupeshta, I've fixed the errors your code was having [here](#19819).  In some of the functions, you needed to mock os.environ.

**Pull request merged**
