### PR TITLE
Added new options for RH interface configuration

### PR DESCRIPTION
**Pull request by t0fik**
Cleaned version of https://github.com/saltstack/salt/pull/25212 pull request, with more complete list of RedHat interface configuration options

### CODE REVIEW

**Comment by t0fik** [comment]
I belive, that Centos7 fail is not related with this pull.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@t0fik Apologies for the delay here. We're just going to re-run the CentOS 7 tests and then we'll get this merged. Thanks!

**Comment by t0fik** [comment]
No problem

**Comment by cachedout** [comment]
Merged! Thanks very much for this fix. We really appreciate it.

**Comment by t0fik** [comment]
No problem

**Pull request merged**
