### PR TITLE
Backport #37149 and #36938 to 2015.8

### PR DESCRIPTION
**Pull request by meaksh**
### What does this PR do?
This PR backport #37149 and #36938 to 2015.8 branch in order to also include these change everywhere.

Thanks!

### CODE REVIEW

**Comment by rallytime** [comment]
@meaksh Would you mind moving this back-port to the 2016.3 branch instead of 2015.8? The 2015.8 branch is currently only open to CVE-related fixes.

**Comment by meaksh** [comment]
@rallytime Oh, sure! I'm doing it right now. Thanks for the info! :+1:

**Comment by meaksh** [comment]
Closing as this PR is superseded by #37866

**Comment by rallytime** [comment]
Awesome! Thank you!

**Pull request closed without merging**
