### PR TITLE
Add more insight into failures

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title

### CODE REVIEW

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by waynew** [comment]
Does this require a newer version of saltfactories (i.e. will it break everyone's tests until they upgrade)?

**Comment by s0undt3ch** [comment]
> Does this require a newer version of saltfactories (i.e. will it break everyone's tests until they upgrade)?

Nope!

**Review by waynew — APPROVED** [review]

**Comment by s0undt3ch** [comment]
Follow up PR https://github.com/saltstack/salt/pull/58259

**Pull request closed without merging**
