### PR TITLE
Add network type to support InfiniBand interfaces on RHEL/CentOS

### PR DESCRIPTION
**Pull request by matthb2**
resolves issue #21388

### CODE REVIEW

**Comment by jfindlay** [comment]
@matthb2, thanks.

**Comment by jfindlay** [comment]
@matthb2, there's one lint error.

**Comment by matthb2** [comment]
@jfindlay Oops, sorry about that. I've pushed a second commit which should fix it. Let me know if you'd prefer I rebase and open a new request

**Comment by jfindlay** [comment]
@matthb2, no, same pull request is preferable, thanks!

**Pull request merged**
