### PR TITLE
Check all entries in result

### PR DESCRIPTION
**Pull request by gtmanfred**
### What does this PR do?
Without this change, we ony check the first return from state tests, if
there is more than one state run, we do not check subsequent results.

### Tests written?

Yes

### CODE REVIEW

**Comment by gtmanfred** [comment]
This will probably cause some tests to fail, specifically this one which @garethgreenaway found that should already be failing on the requires

https://github.com/saltstack/salt/blob/nitrogen/tests/integration/modules/test_state.py#L758

**Comment by gtmanfred** [comment]
Go Go Jenkins!

**Comment by gtmanfred** [comment]
Good News, it only causes the one test to fail.

**Comment by gtmanfred** [comment]
It looks like that failing test was added here.  https://github.com/saltstack/salt/pull/29141
But the functionality was never fixed. We have been seeing this intermittently fail in tests on python3.4 because the dictionary order is not always the same.

https://github.com/saltstack/salt/issues/10852

But the issue remains, should we disable the test or just switch it to False?

**Comment by rallytime** [comment]
@gtmanfred These changes to `ingegration/__init__.py` did not merge forward in #41614. This is due to the fact that that file was changed quite a bit in `nitrogen`. So a separate PR will need to be made for these changes for nitrogen.

**Comment by rallytime** [comment]
Ah, actually it looks like this was done already in develop with #41580, so I will just back-port that to `nitrogen`.

**Pull request merged**
