### PR TITLE
Camels and snakes

### PR DESCRIPTION
**Pull request by github-abcde**
### What does this PR do?
Add `camel_to_snake_case` and `snake_to_camel_case` functions to `salt.utils.stringutils` with decorators to also be able to use them as Jinja filters.
The only other place that this functionality already existed (be it with a slightly different name) was in `states/testinframod.py` and `modules/testinframod.py`, which have been updated to use the functions in `salt.utils.stringutils` instead.

### What issues does this PR fix or reference?
None

### Previous Behavior
No publicly available functions to convert between snake_case and camelCase (or UpperCamelCase) were available in salt or Jinja.

### New Behavior
These functions are now available to use in other modules (most notably Boto modules could benefit from this as Boto (and AWS) use UpperCamelCasing for almost all of their parameters and function names).

### Tests written?
Yes

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by twangboy** [comment]
@github-abcde This looks good. Can we get some tests for the two new salt util functions?

**Comment by mchugh19** [comment]
Isn't there a docs page for Jinja filters as well?

**Review by twangboy — APPROVED** [review]

**Review by dwoz — APPROVED** [review]

**Comment by dwoz** [comment]
@github-abcde can you reply to @mchugh19's comment please?

**Comment by github-abcde** [comment]
@mchugh19 There is, and I've added documentation in commit 43896e2

**Comment by github-abcde** [comment]
@mchugh19 or @dwoz Is there something else that I can (or need to) do in order for this branch to be merged?

**Review by twangboy — APPROVED** [review]

**Pull request merged**
