### PR TITLE
[WIP] Get static core grains from grainsv2

### LINKED ISSUE #57680: [FEATURE REQUEST] Get grains from grainsv2
Separate grains from core.py and the `grains` directory into independent platform specific projects.
The SEP for this change is [here](https://github.com/saltstack/salt-enhancement-proposals/pull/30)
The bulk of the work has been done in:
[idem-linux](https://gitlab.com/saltstack/pop/idem-linux)
[idem-bsd](https://gitlab.com/saltstack/pop/idem-bsd)
[idem-windows](https://gitlab.com/saltstack/pop/idem-windows)
[idem-darwin](https://gitlab.com/saltstack/pop/idem-darwin)
[idem-aix](https://gitlab.com/saltstack/pop/idem-aix)
[idem-solaris](https://gitlab.com/saltstack/pop/idem-solaris)
[grains-virt](https://gitlab.com/saltstack/pop/corn_virtualiztion)

### PR DESCRIPTION
**Pull request by Akm0d**
### What does this PR do?
Get grains from grainsv2 in the idem-platform projects

### What issues does this PR fix or reference?
Fixes: #57680

### Previous Behavior
Static grains were collected from core.py in salt

### New Behavior
Static grains for each platform will be collected from individually maintained repos

### Merge requirements satisfied?
- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

Tests for the new grains are in their individual repositories.  They are tested independently of salt.

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by Akm0d** [comment]
acct (dependency of idem) requires msgpack>=1.0.0 but salt requires a lower version of msgpack.  The code in  acct  needs to be fixed to work with older versions of msgpack.  This is the [line of code](https://gitlab.com/saltstack/pop/acct/-/blob/master/acct/acct/enc.py#L52) that needs changing.  It needs to recursively turn the loaded object into all strings instead of bytestrings

**Comment by s0undt3ch** [comment]
The idem requirements should be added to `base.txt` instead:
```diff
❯ git diff
diff --git a/requirements/base.txt b/requirements/base.txt
index 27923c00e4..462c73e495 100644
--- a/requirements/base.txt
+++ b/requirements/base.txt
@@ -4,3 +4,7 @@ PyYAML
 MarkupSafe
 requests>=1.0.0
 distro
+#idem-aix>=6; sys_platform == 'aix'
+idem-linux>=6; sys_platform == 'linux'
+idem-darwin>=6.1; sys_platform == 'darwin'
+idem-bsd>=2; sys_platform == 'freebsd'
```
Useful links:
* https://www.python.org/dev/peps/pep-0496/#id7
* https://docs.python.org/3/library/sys.html#sys.platform

**Comment by dwoz** [comment]
re-run full all

**Comment by Akm0d** [comment]
I need to create an idem-salt and the new tests need to be passing before this PR is ready for merging.

**Pull request closed without merging**
