### PR TITLE
Summary requires full return information.

### PR DESCRIPTION
**Pull request by plastikos**

### CODE REVIEW

**Comment by jfindlay** [comment]
@plastikos, do you think this needs to be in 2015.5 or 2015.8?

**Comment by plastikos** [comment]
Yes.  I have patched it into my production 2015.5 and have been using it for months.

**Comment by jfindlay** [comment]
@plastikos cool, thanks.  I think this is breaking the [shell matcher tests](https://jenkins.saltstack.com/job/salt-pr-linode-ubuntu14.04-n/467/).  Will you look at updating them?

**Comment by plastikos** [comment]
Yes.

**Comment by plastikos** [comment]
I'm embarrassed to admit that the patch I've been using in production and what I submitted here (originally) in #2de88e6 differ - I added a gratuitous change that cause the failed test.  My production patch is the equivalent of #2de88e6 + #7c9f4ca - which is really a single line change.

**Comment by plastikos** [comment]
Okay, I just found a previous fix for this that was incorrect and needs to be reverted: #54b33dd35948

The problem with the #54b33dd35948 fix is that there are two places calling _print_returns_summary(): one from the 'progress' section and the other from 'cli_summary'.  These two callers were not consistent in the data passed to _print_returns_summary().  That means that fixing _print_returns_summary() will only fix problems for *one* of the callers.  The callers need to be made consistent (which is what this patch does) and then _print_returns_summary() can then be fixed.  I'll submit a revert of #54b33dd35948

**Comment by plastikos** [comment]
See #27099

**Pull request merged**
