### PR TITLE
Add win_lgpo execution module

### PR DESCRIPTION
**Pull request by lomeroe**
### What does this PR do?

Add an execution module for managing Windows Local Group Policy.  Module allows viewing and setting User/Machine Policies and Administrative Templates
### What issues does this PR fix or reference?
saltstack/salt#21485
### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by lorengordon** [comment]
This is awesome! Just going to nitpick that `heirarchical` should be `hierarchical`. Wouldn't have mentioned it, except it is exposed as a param in the user-facing `get()` function.

**Comment by lorengordon** [comment]
ahh, so, there's also at least one `heirarchy`... :wink:

**Comment by cachedout** [comment]
Hi @lomeroe ! Wow this is great! Could you please add a `from salt.ext.six.moves import range` to this for Py3 compat? We'll start taking a look at the rest.

**Comment by lorengordon** [comment]
Another thought, I'm always wary of shadowing builtins, so the `set()` function makes me itch a bit.

@damon-atkins had a good question posted on the issue itself, regarding maintenance of the defined `policies` dictionary. Might be nice to put a small write-up in the module docstring so others know how to identify new/missing policies and add them over time?

**Comment by lomeroe** [comment]
@cachedout Thanks, I will add that. 

@lorengordon I thought about the "set", but liked it being short.  I am not tied to the names and have no issue changing the functions to "get_policy" and "set_policy".  There is a note in the writing module documentation about using trailing underscores to avoid keyword clashes, but I must be misinterpreting it, as it isn't working how I read it -- I read it that the function could be named "set_" but then called with "set" when actually used.

Agreed on the policies dict documentation.  It is sorely needed.

**Comment by lorengordon** [comment]
It's hard to leave line comments since the file isn't really available. Looking at [this](https://github.com/lomeroe/salt/blob/930185cd3a1c4f1cd361687b086d189caa48a195/salt/modules/win_lgpo.py#L1967-L1968) pattern, I'm guessing you're trying to work around the 80 char limit. Should be able to simplify it a bit like so:

```
                    msg = ('An adml file in the specified adml language "{0}" does not '
                           'exist for the admx "{1}", the fallback languange will be tried.')
```

or even (my preference for such things):
```
                    msg = (
                        'An adml file in the specified adml language "{0}" does not '
                        'exist for the admx "{1}", the fallback languange will be tried.'
                    )
```

**Comment by lorengordon** [comment]
Far as `set()` goes, the problem is that if the module ever needs to use the builtin `set()` function, things may get wonky. Worst case, needing to deprecate and rename the public function. I'm not aware of any way to name a function with a trailing underscore and have it called without. That would be a neat workaround for the issue. I see the "Note" in the doc, https://docs.saltstack.com/en/latest/ref/modules/#private-functions. Maybe someone on the salt team can comment on how that might be intended, or if it's not implemented.

image

**Comment by cachedout** [comment]
@lorengordon We do support this! Name your function `def _set` and put the following in the module.

```
 __func_alias__ = { '_set': 'set' }
```

That will do the trick.

**Comment by lorengordon** [comment]
@cachedout Nice! I ought to have a few min to add that to the note in the docs.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Thank you very much for your work here @lomeroe!

**Comment by lorengordon** [comment]
seconded! huge thanks! :grin:

**Comment by damon-atkins** [comment]
@lomeroe  
The reg is Unicode. I strongly suggest you add 
# Import _future_ python libs first & before any other code
from __future__ import absolute_import
**from __future__ import unicode_literals**

For example you use modules/reg.py which is all Unicode

Then most likely you can remove  code like this chr(len(' {0}'.format(chr(0)).encode('**utf-16-le**'))),

You should also give yourself some credit, add   :codeauthor:

**Comment by damon-atkins** [comment]
You will also fine salt/utils/win_functions.py   has user functions with in it.
e.g.  add _sidConversion to it or using something from it or combination.

**Pull request merged**
