### PR TITLE
SQL Pillar bugfix

### PR DESCRIPTION
**Pull request by isbm**
### What does this PR do?

Bugfix for `sql_pillar`

### What issues does this PR fix or reference?

From the https://bugzilla.suse.com/show_bug.cgi?id=1072218:
```
External SQL pillar when explicitly configured to use
a key as a list throws an error like this:

{"log":"[CRITICAL] Pillar render error: Failed to load
ext_pillar mysql: 'list' object has no attribute split'\n",
"stream":"stderr","time":"2017-12-11T16:36:53.140833238Z"}

I believe this is because it potentially tries to convert the 
with_lists argument string multiple times in salt/pillar/sql_base.py 
in lines 278ff into an int array, which only works once.
```

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

No

### CODE REVIEW

**Comment by isbm** [comment]
@rallytime bugfixes are OK to Oxygen, I believe, right?

**Comment by rallytime** [comment]
@isbm Yep! Bugfixes are OK in the oxygen branch. Thank you!

**Review by terminalmage — APPROVED** [review]

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Pull request merged**
