### PR TITLE
profile outputter

### PR DESCRIPTION
**Pull request by jettero**
### What does this PR do?

My profile outputter simply shows the 'duration' key from each state along with its name and statemodule.function

### What issues does this PR fix or reference?

(#21535)

### Tests written?

No, but I've put most of my states and my highstates through it. It could use some later tweaking probably, but it seems to do the right thing.

### CODE REVIEW

**Review by mirceaulinic — COMMENTED** [review]
Leaving aside the linter and documentation aspects, I would incline to suggest re-using the table outputter: https://github.com/saltstack/salt/blob/develop/salt/output/table_out.py, in order to avoid the `tabulate` dependency. To see how to use, you can have a look at: https://github.com/saltstack/salt/blob/develop/salt/output/table_out.py#L347-L364

**Comment by jettero** [comment]
@mirceaulinic fantastic idea, thanks.

I'm not sure if I should try to import that outputter and use the TableDisplay class directly, or is there a way to stack outputters so I can just pass my data to that outputter when I'm done pre-processing?

I looked for a way previously to make an outputter that does some preprocessing on highstate output and then passes the data to the highstate outputter. I recall getting something to work, but it wasn't at all satisfactory.

**Comment by jettero** [comment]
Oh, apparently I never noticed table_out because it's newer than my 2016.11.3. Indeed, it doesn't appear to be in the 2016.11 branch at all.

**Comment by jettero** [comment]
@mirceaulinic I rebased my commit onto 2016.11 ... I'm going to make a new PR for that using tabulate. When/if that merges, I'll come back to this PR and modify it to use table_out. Does that sound reasonable?

**Comment by mirceaulinic** [comment]
@jettero FYI: as this is a new feature it will not be included into 2016.11, but only in the next release, Nitrogen.

**Comment by jettero** [comment]
Right, that makes sense. OK, skip that idea then. I'll just use the table_out in develop

**Comment by jettero** [comment]
There's apparently really no way to re-use that TableDisplay object from another outputter @mirceaulinic. If I try to just import that outputter and use its `output()`, it'll choke due to missing __opts__ if that wasn't already populated somewhere else. So, do I populate it in my __virtual__ if possible?

So I figured skip trying to use its `output()`, I'll just use TableDisplay directly. But that expects __opts__ to be populated too. So, again, I'm left wondering if I should really be trying to populate the __opts__ over there or if I can safely expect the salt/output/__init__ to have done it for me at some point?

Can I expect a module loader (like __salt__) somewhere for outputters? Do I use salt.loaders.outputters() to load the table_out?

I think the __opts__ magic really hurts re-use in cases like this. I wish the outputters at least had some internal magic for re-using eachother.

I'm going to abort trying to use the table_out.TableDisplay for now and try to get day-job work done. Let me know what the right approach might be -- it's definitely not clear to me.

**Comment by mirceaulinic** [comment]
A straightforward solution I see would require the following changes:

1. change the header of the `__init__` to `def __init__(self, opts, ...)`
2. on the very first line inside `__init__` do `self.opts = opts`
3. Replace every `__opts__` with `self.opts` inside the `TableDisplay` class
4. When creating the instance of the class do `table = TableDisplay(__opts__, **class_kvargs)` instead of `table = TableDisplay(**class_kvargs)`

Inside of this new outputter you could import the `TableDisplay` from `salt.output.table_out` and call it similarly passing the local `__opts__`. Would that make sense?

**Comment by jettero** [comment]
Indeed, that would solve the problem. Then I could import and use the class without fretting over whether __opts__ is populated in a module outside the current namespace.

**Comment by jettero** [comment]
I do wonder if there's a way to also include much of that `__opts__` processing that's going on in the `output()` method though. The `/etc/` config preferences for table formats should apply when I try to use the `TableDisplay` class. That was why I initially thought about using the `output()` function rather than making my own instance of the `TableDisplay` class.

**Comment by cachedout** [comment]
Hi @jettero and @mirceaulinic. Where did you two land on this discussion. Should we expect additional commits to this or is it ready for review as it sits?

**Comment by jettero** [comment]
I lost track of it. I wasn't sure how to integrate it with the table outputter and wished there were better ways to re-use the stuff... and just kinda left it there.

I think I'll circle back to this later in the week or over the weekend though.

**Comment by cachedout** [comment]
Hi @jettero.

Were you able to come back around to this one?

**Comment by jettero** [comment]
I forgot about it again. I'm firing it up in the editor right now. Lemme see if I can figure something out.

**Comment by jettero** [comment]
That aught to do it. It was surprisingly difficult to test this stuff, but I think it works.

**Comment by jettero** [comment]
BTW @cachedout, thanks for keeping me on it.

Not only are the Saltstack maintainers awesome about accepting patches, carefully review things, interacting with the community; now I find they also check up on PRs that got forgotten. The enormous effort behind all this is recognized. Thanks.

**Comment by cachedout** [comment]
@jettero Such kind words -- thank you so much! We appreciate your contributions and it really means a lot to all of us that you'd take the time to send thanks. It's really nice. :]

I really like this outputter. It's been something that we've sorely needed for a long while and I think there will be a lot of interest. Thanks again!

**Pull request merged**
