### PR TITLE
Making ssh-copy-id using the provided machine name and not ip

### PR DESCRIPTION
**Pull request by matdrapeau**
This fixes: https://github.com/saltstack/salt/issues/22682

### CODE REVIEW

**Comment by matdrapeau** [comment]
Simple fix that could have big consequences... asking for input if this is the right way to go

**Comment by thatch45** [comment]
I don't think this one will work out well, @basepi we should look over this more closely

**Comment by matdrapeau** [comment]
any other input?

**Comment by thatch45** [comment]
Sorry I have not been able to go over this one yet. my worry is that this will break the other rosters, because the id should not be the same as the host, so other rosters will likely fail with this change, maybe this is a problem in the way the clusterssh roster is compiled?

**Comment by basepi** [comment]
Ya this seems like it's wrong. It will break many things, including the flat roster, if I'm not mistaken. The problem is that the minion ID has no relationship to the hostname or IP address of the host in most rosters. I can define it like this:

```
fdlfjdsklfjdksljfdklsfjkls:
    host: 255.255.255.255
    user: root
```

If salt-ssh tries to connect to the host `fdlfjdsklfjdksljfdklsfjkls` it's not going to work...

**Comment by matdrapeau** [comment]
I think this change makes more sense!

**Comment by thatch45** [comment]
Awesome! Thanks @matdrapeau !

**Pull request merged**
