### PR TITLE
Ensure that the win_pki.import_cert module doesn't fail randomly.

### PR DESCRIPTION
**Pull request by liquidgecka**
### What does this PR do?

Sometimes when running win_pki.py.import_cert will return a help message asserting that there was an argument error. This is because the underlying json coming out of PowerShell might actually return nil (None) so the .get() with a default return doesn't properly protect
against a None getting iterated.

### What issues does this PR fix or reference?

I have not filed an issue yet, but I can if needed.

### Previous Behavior

Running the module returns a help error as though the arguments are wrong when it is in fact a data parsing issue.. This leads to a very confusing experience for users:

```bash
salt 'minecraft-staging*' win_pki.import_cert name=$URL cert_format="cer" context="LocalMachine" store="Root" exportable=True password=''
host:
    Passed invalid arguments to win_pki.import_cert: 'NoneType' object is not iterable

        Import the certificate file into the given certificate store.

        :param str name: The path of the certificate file to import.
        :param str cert_format: The certificate format. Specify 'cer' for X.509, or
            'pfx' for PKCS #12.
        :param str context: The name of the certificate store location context.
        :param str store: The name of the certificate store.
        :param bool exportable: Mark the certificate as exportable. Only applicable
            to pfx format.
        :param str password: The password of the certificate. Only applicable to pfx
            format. Note that if used interactively, the password will be seen by all minions.
            To protect the password, use a state and get the password from pillar.
        :param str saltenv: The environment the file resides in.

        :return: A boolean representing whether all changes succeeded.
        :rtype: bool

        CLI Example:

        .. code-block:: bash

            salt '*' win_pki.import_cert name='salt://cert.cer'
```
Note that running with -ltrace maes it slightly clearer that this is dying after a read only call, but copy pasting from power shell over remote desktop has proven too annoying. Hopefully this case is obvious enough to see that I don't have to repo it. =)

### New Behavior

The function works as expected.

### Tests written?

No

### CODE REVIEW

**Comment by carlpett** [comment]
Hm, this looks very similar to this PR #42457. How does the data structure for the certificate look for a failing certificate? Does the cert not contain any subjectAltName entries at all?

**Comment by liquidgecka** [comment]
The certificate causing the issues looks like so (return from the MS tooling, pretty printed):

```json
{
    "DnsNameList": null,
    "SerialNumber": "46FCEBBAB4D02F0F926098233F93078F",
    "Subject": "OU=www.verisign.com/CPS Incorp.by Ref. LIABILITY LTD.(c)97 VeriSign, OU=VeriSign International Server CA - Class 3, OU=\"VeriSign, Inc.\", O=VeriSign Trust Network",
    "Thumbprint": "D559A586669B08F46A30A133F8A9ED3D038E2EA8",
    "Version": 3
}```

#42457 helped assure that items without DnsNameList don't cause the code to crash.. Thats good for obvious reasons. However it leaves open the case where DnsNameList is 'nil' in the json, like the above. My change ensures that if the return value is non iterable then we don't attempt to wlak it and end up with an unexpected and strange error case.

I just cleaned it up a bit (being awake unlike last night) so that we don't require double instantiation of default dicts to get through the code block. Hopefully it also makes it a bit easier to read as well.

**Review by twangboy — APPROVED** [review]

**Comment by liquidgecka** [comment]
Erm.. I appear to be causing tests to fail. I will look at this when I get a chance.

**Comment by liquidgecka** [comment]
Turns out I wrote the better looking check wrong.. fixed now and all the tests are back to passing. Yay for unit tests! =)

**Pull request merged**
