### PR TITLE
Do not list files for all available saltenvs until it's necessary

### PR DESCRIPTION
**Pull request by uhriap**
Improve performance of state.apply in case of many saltenvs.

### What does this PR do?
Replace listing files for each available saltenv on BaseHighState init with LazyDict which calls list_files only if given saltenv used somewhere in states.

### Previous Behavior
Minion calls list_states for every available saltenv on every highstate

### New Behavior
Minion calls list_states only for actually used saltenvs

### Tests written?

No

### Commits signed with GPG?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by dwoz — CHANGES_REQUESTED** [review]
@uhriap This looks like really good work. Can we add some unit tests for the `AvailableStates` class?

**Comment by uhriap** [comment]
@dwoz, I added some tests and fix but i'm not shure if test_state.py is proper place for it.

**Comment by mchugh19** [comment]
@uhriap can you fix up the lint errors?

**Comment by uhriap** [comment]
> @uhriap can you fix up the lint errors?
Fixed.

**Comment by dwoz** [comment]
@uhriap I've ported this PR to the master branch in #55788, closing this one.

**Comment by uhriap** [comment]
> @uhriap I've ported this PR to the master branch in #55788, closing this one.

Thanks!

**Pull request closed without merging**
