### PR TITLE
Correct capitalization in service state comment

### PR DESCRIPTION
**Pull request by amendlik**
### What does this PR do?
Correct the capitalization of a return comment in the service state to be consistent with the other comments returned by the module.

### What issues does this PR fix or reference?
Fixes: N/A

### Previous Behavior
`ret["comment"] = "Started Service {}".format(name)`

### New Behavior
`ret["comment"] = "Started service {}".format(name)`

### Merge requirements satisfied?
- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by waynew — APPROVED** [review]
Hey @amendlik thanks for the PR! Good catch!

**Review by waynew — CHANGES_REQUESTED** [review]
Ah, looks like there's a failing test - if you could update that test case, that would be awesome :+1:

**Comment by amendlik** [comment]
@waynew The tests are fixed.

**Comment by amendlik** [comment]
@waynew Any update on this PR?

**Comment by waynew** [comment]
Looks like some other tests were failing but not sure that was part of this PR. I just merged the most recent changes from master in, let's see if tests all pass now

**Review by waynew — APPROVED** [review]
:+1:

**Comment by amendlik** [comment]
@waynew Is there anything else I need to do to get this PR merged?

**Comment by waynew** [comment]
@amendlik thanks for asking! I'm pretty sure that these issues are unrelated - I've pinged the rest of the core team to see if anyone knows what's up there

**Comment by amendlik** [comment]
@waynew What else remains to get this merged?

**Comment by amendlik** [comment]
@waynew I don't mean to be a pest, but I don't know the process for contributing fixes anymore. There was a time when they would be merged within a week. Now it seems to take several months or more.

Should I be following up on my PRs, or should I assume the core team will take care of all of them eventually?

**Comment by amendlik** [comment]
@waynew I would like to get this merged. What steps remain?

**Comment by amendlik** [comment]
@waynew I would like to get this merged. What steps remain?

**Comment by sagetherage** [comment]
I am re-running that test that timed out- will check back later today for results.

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
