### PR TITLE
adding states/rabbitmq_vhost unit test case.

### PR DESCRIPTION
**Pull request by jayeshka**
Implemented states/rabbitmq_vhost_test unit test case.

### CODE REVIEW

**Comment by rallytime** [comment]
@jayeshka Looks like there are some related test failures. Can you take a look at those?

**Comment by jayeshka** [comment]
Unless #24524 is merge this wont get passed.
@rallytime please review.

**Comment by rallytime** [comment]
@jayeshka Oh good catch! I've merged in your other fix, so you should be able to rebase this pull request with current 2015.5. Once these tests run again and pass, we can get this merged in.

**Comment by jfindlay** [comment]
@rallytime, this pull will still have the old version of the branch, but I've tested it locally with the fix and it's passing.

**Pull request merged**
