### PR TITLE
Configurable AWS region & region from IAM metadata

### PR DESCRIPTION
**Pull request by stanislavb**
### Issue:

```
[DEBUG   ] Updating s3fs fileserver cache
[DEBUG   ] Refreshing buckets cache file
[INFO    ] Starting new HTTP connection (1): 169.254.169.254
[DEBUG   ] "GET /latest/meta-data/iam/security-credentials/ HTTP/1.1" 200 46
[INFO    ] Starting new HTTP connection (1): 169.254.169.254
[DEBUG   ] "GET /latest/meta-data/iam/security-credentials/saltmaster-stanislav-InstanceRole-2GXXUB0NXDND HTTP/1.1" 200 910
[DEBUG   ] S3 Request: https://salt-states.s3-eu-west-1.amazonaws.com/?
[DEBUG   ] S3 Headers::
[DEBUG   ]     Authorization: AWS4-HMAC-SHA256 Credential=[redacted]/20150724/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-date, Signature=[redacted]
[INFO    ] Starting new HTTPS connection (1): salt-states.s3-eu-west-1.amazonaws.com
[DEBUG   ] "GET / HTTP/1.1" 400 None
[DEBUG   ] S3 Response Status Code: 400
[WARNING ] 'The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'' response for bucket 'salt-states'
```
### Solution:
- Expose s3.location where possible
- Try to fetch AWS region from metadata service like we do with key and keyid

### CODE REVIEW

**Comment by techhat** [comment]
This is awesome @stanislavb, thank you! When this code was first written, there was only one S3 endpoint, but now that there's more, this is definitely needed.

**Comment by stanislavb** [comment]
I don't get why the tests are failing. Looks like JUnit cannot find xml files.

**Comment by techhat** [comment]
@jfindlay, can you please take a look?

**Comment by jfindlay** [comment]
@techhat, there are some general jenkins issues right now that we're working on.

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Pull request merged**
