### PR TITLE
WIP: Deprecate salt/modules/img.py

### PR DESCRIPTION
**Pull request by techhat**
Ping @Ch3LL, @jacobhammons, @thatch45.

### CODE REVIEW

**Comment by thatch45** [comment]
What is the motivation here? I am waffling on this one.

**Comment by techhat** [comment]
The name `img` is confusing because it could mean, say, `qcow2`/`ovf`/etc or it could mean `jpg`/`png`/`/gif`/etc. The only three functions here are mount and umount (and we already have a mount module that can be made to handle them) and bootstrap (which is broken, and genesis.bootstrap does everything it does and more).

**Comment by Ch3LL** [comment]
i've tested these changes with no issues

**Comment by thatch45** [comment]
Right, sorry, I remember us talking about this now

**Comment by rallytime** [comment]
@techhat Looks like there's some tests failing that need to be addressed here.

**Comment by techhat** [comment]
Let's not merge just yet. This PR is still pending discussion

**Comment by techhat** [comment]
Ready to merge.

**Comment by rallytime** [comment]
W00t!

**Pull request merged**
