### PR TITLE
fixed: include all items from kern.disks split

### PR DESCRIPTION
**Pull request by ghost**
salt['grains.get']('disks') always dropped the last disk (first in returned list from sysctl).
"sysctl -n" does not include sysctl-name, so the [1:] offset was wrong.

p.s. this is my first pull request to a different github repo so please be kind ;-)

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @gqgunhed Thanks for this!

Before we merge this, I would like to bring @kev009 into this conversation since he recently added this here: https://github.com/saltstack/salt/pull/26701

**Comment by kev009** [comment]
Whoops, yes this was a mistake thanks for catching it!

**Comment by kev009** [comment]
only feedback would be to PR this against 2015.8 instead of develop since it is a bugfix

**Comment by gqgunhed** [comment]
Hey guys,
thanks for the feedback. Something to do for me now?
Or am I done with the added "Bugfix - back-port" label?

**Comment by cachedout** [comment]
@gqgunhed We'll get this backported to the correct branch for you. Just remember that in the future, we like to have bug fixes go into the latest release branch that contains the bug (which is 2015.8, typically). New features always go into develop.

Thanks for this fix! We'll get it merged.

**Comment by gqgunhed** [comment]
I will remember that. Thanks for the guidance.

**Pull request merged**
