### PR TITLE
Fix executors not being called for multi-jobs

### PR DESCRIPTION
**Pull request by andzn**
### What does this PR do?
Fixes a bug where custom executors were not being called for multi-jobs

### Previous Behavior
Executors were not being called for multi-jobs

### New Behavior
Executors are now called for multi-jobs as well as for single function jobs

### Tests written?
No

### Commits signed with GPG?
No

### CODE REVIEW

**Review by rares-pop — COMMENTED** [review]
Is there a test to 'patch' or can we write a new one to ensure things happens the way we expect, having custom executors set-up?

**Comment by mattp-** [comment]
👍 nice add

**Review by rares-pop — APPROVED** [review]
LGTM

**Comment by andzn** [comment]
I created a new PR #53844 based on the 2019.2 branch that also contains a test.

**Pull request closed without merging**
