### PR TITLE
[2017.7] update ec2 pillar arguments with better names

### PR DESCRIPTION
**Pull request by damon-atkins**
### What does this PR do?

Update the arguments to a more suitable name.

### What issues does this PR fix or reference?

Relates to PR #45878 which has not been released.

### Previous Behavior

As per PR #45878

### New Behavior

PR #45878

### Commits signed with GPG?

No

### CODE REVIEW

**Review by gtmanfred — CHANGES_REQUESTED** [review]
Unfortunately because this is in a release, i don't think that we can just change it.

It would need to go through a deprecation process and be merged into develop.

**Review by gtmanfred — APPROVED** [review]

**Comment by gtmanfred** [comment]
Nevermind, i missed the part that it was added after 2017.7.3, and isn't in a release yet.

**Comment by rallytime** [comment]
re-run py

**Comment by damon-atkins** [comment]
@rallytime could you merge this before the next 2017.7 release pls if the original pr is in the next release.

**Comment by gtmanfred** [comment]
The original one will not be in 2017.7.4, we only few cherry-picked bug fixes in 2017.7.4

**Comment by damon-atkins** [comment]
I have another PR to come after this one for same file.    Heaps more doco...etc.

**Pull request merged**
