### PR TITLE
Add unicode_literals import

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?
Fixes Unicode issues in the log.debug messages in the win_wua module

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/30980

### Previous Behavior
Failing with a stack trace with Unicode characters in the title.

### Tests written?
No

### CODE REVIEW

**Comment by cachedout** [comment]
@twangboy Did you see the most recent comment [here](https://github.com/saltstack/salt/issues/11995#issuecomment-293218103)?

You may want to bring @cdunklau in on this.

**Comment by twangboy** [comment]
@cachedout I did, but it seemed to reference older versions of Python. Since Windows stays pretty current, I didn't think it was an issue. Shall I do the `u'string'` approach instead?

**Comment by cdunklau** [comment]
I'd love to help, but I know very little about the situation in Windows, or really in general when it concerns large projects... and since I know very, very little about the Salt codebase, I don't think I'll be of much help. I posted that comment mainly as a warning, I didn't intend it to be a hard "hey don't do this".

The issues caused by `unicode_literals` in polyglot code seem to revolve around certain Python APIs that expect the "native" `str` type in both versions, especially those dealing with paths.

Explicitly using bytes/unicode literals without `unicode_literals` lets one choose one or the other where appropriate, while still keeping the ability to use "native" `str` where necessary.

**Comment by damon-atkins** [comment]
This has been add to other windows execution modules `from __future__ import unicode_literals`
You can also use PY3 syntax to set the type.

There is also this recent change #40307 `System encoding detection compatibility for windows`

**Pull request merged**
