### PR TITLE
Thrown an error when the `tmpdir` fixture is used. Migrate to `tmp_path`

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title

### CODE REVIEW

**Comment by s0undt3ch** [comment]
re-run full all

**Review by garethgreenaway — DISMISSED** [review]

**Review by waynew — DISMISSED** [review]

**Comment by waynew** [comment]
@s0undt3ch looks reasonable - are these failures related?

**Comment by s0undt3ch** [comment]
They might be, I haven't had time to come back to this yet.

**Comment by waynew** [comment]
@s0undt3ch just a ping on this

**Comment by s0undt3ch** [comment]
It's down to a failing test.
I'll see when I can fix it....

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by Ch3LL** [comment]
re-run full all

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
