### PR TITLE
Update to more current SLE version numbers

### PR DESCRIPTION
**Pull request by brejoc**
### What does this PR do?

SLE 15 and SLE 15 SP1 are more current. Also those versions ship with Salt in the base repos. No need to add additional repos. Adding additional repos would actually be harmful, since those would have skipped the openQA checks.

### CODE REVIEW

**Comment by brejoc** [comment]
These two PRs are related: https://github.com/saltstack/salt/pull/55205

**Comment by brejoc** [comment]
@thatch45 Could you please take a look here? Thanks!

**Comment by brejoc** [comment]
@dwoz Could you please have a look!?

**Review by DmitryKuzmenko — APPROVED** [review]
I see no problem. SUSE guys know better how to install Salt on SUSE =)

**Pull request merged**
