### PR TITLE
fixing issue 39191.

### PR DESCRIPTION
**Pull request by narendraingale2**
What does this PR do?

This PR is fixing issue 39191.

What issues does this PR fix or reference?

issue 39191

Previous Behavior

refer this issue #39191

Tests written?

yes

### CODE REVIEW

**Review by s0undt3ch — APPROVED** [review]

**Review by s0undt3ch — COMMENTED** [review]
My aproval was just for the blacklisted import removal :)

**Review by s0undt3ch — COMMENTED** [review]
I'll let @terminalmage or @cachedout do the actual approval since they are more acquainted with the code.

**Comment by terminalmage** [comment]
I'm in the process of overhauling the docker state and module in develop, the code modified in this PR will no longer exist in develop soon. This bug presumably exists in existing releases, so this work should be resubmitted against the earliest affected version as noted in our [documentation](https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch).

**Comment by terminalmage** [comment]
If @narendraingale2 does not know how to do this, then I can work with him/her to get it done.

**Comment by narendraingale2** [comment]
@terminalmage sure. Please let me know next course of action.

I need one more help. As some changes in test suite. I am unable to run integration test. 

`Traceback (most recent call last): File "../salt/tests/runtests.py", line 59, in <module> from tests.integration import TestDaemon # pylint: disable=W0403 File "/Users/ningale/salt/tests/integration/__init__.py", line 49, in <module> from tests.support.processes import * # pylint: disable=wildcard-import File "/Users/ningale/salt/tests/support/processes.py", line 18, in <module> from pytestsalt.utils import SaltRunEventListener as PytestSaltRunEventListener ImportError: No module named pytestsalt.utils (salt-dev) ningale-L111:salt ningale$`

Am I running incorrectly ? Or do I need some more dependencies.

**Comment by cachedout** [comment]
@narendraingale2 Which branch did you intend to submit this against? It looks like this has been submitted against a different branch than the one that you created it from.

**Comment by narendraingale2** [comment]
@cachedout No. I have submitted from same branch just tried to sync forked repository.

Regards,
Narendra

**Comment by narendraingale2** [comment]
I think this script is not full proof. I am still working on it.

**Comment by narendraingale2** [comment]
@cachedout, @terminalmage , @s0undt3ch I am getting this error while starting daemons to execute test cases. Can somebody help me to resolve this. same repo is working fine on centos7 virtualbox but not working on mac.

```
Traceback (most recent call last):
  File "tests/runtests.py", line 690, in <module>
    main()
  File "tests/runtests.py", line 675, in main
    status = parser.run_integration_tests()
  File "tests/runtests.py", line 600, in run_integration_tests
    with TestDaemon(self):
  File "/Users/ningale/salt/tests/integration/__init__.py", line 252, in __enter__
    self.start_zeromq_daemons()
  File "/Users/ningale/salt/tests/integration/__init__.py", line 379, in start_zeromq_daemons
    start_timeout=30)
  File "/Users/ningale/salt/tests/support/processes.py", line 190, in start_daemon
    attempts-1
RuntimeError: The pytest salt-minion(master) has failed to start after 3 attempts
```

No exception in log files.

**Comment by narendraingale2** [comment]
@cachedout, @terminalmage , @s0undt3ch I am getting this error while starting daemons to execute test cases. Can somebody help me to resolve this. same repo is working fine on centos7 virtualbox but not working on mac.

```
Traceback (most recent call last):
  File "tests/runtests.py", line 690, in <module>
    main()
  File "tests/runtests.py", line 675, in main
    status = parser.run_integration_tests()
  File "tests/runtests.py", line 600, in run_integration_tests
    with TestDaemon(self):
  File "/Users/ningale/salt/tests/integration/__init__.py", line 252, in __enter__
    self.start_zeromq_daemons()
  File "/Users/ningale/salt/tests/integration/__init__.py", line 379, in start_zeromq_daemons
    start_timeout=30)
  File "/Users/ningale/salt/tests/support/processes.py", line 190, in start_daemon
    attempts-1
RuntimeError: The pytest salt-minion(master) has failed to start after 3 attempts
```

No exception in log files.

**Comment by narendraingale2** [comment]
@cachedout, @terminalmage , @s0undt3ch I am getting this error while starting daemons to execute test cases. Can somebody help me to resolve this. same repo is working fine on centos7 virtualbox but not working on mac.

```
Traceback (most recent call last):
  File "tests/runtests.py", line 690, in <module>
    main()
  File "tests/runtests.py", line 675, in main
    status = parser.run_integration_tests()
  File "tests/runtests.py", line 600, in run_integration_tests
    with TestDaemon(self):
  File "/Users/ningale/salt/tests/integration/__init__.py", line 252, in __enter__
    self.start_zeromq_daemons()
  File "/Users/ningale/salt/tests/integration/__init__.py", line 379, in start_zeromq_daemons
    start_timeout=30)
  File "/Users/ningale/salt/tests/support/processes.py", line 190, in start_daemon
    attempts-1
RuntimeError: The pytest salt-minion(master) has failed to start after 3 attempts
```

No exception in log files.

**Comment by s0undt3ch** [comment]
Pass `-vvv` to run tests and upload those logs to a gists. That can probably shed some more light on what's happening.

**Comment by s0undt3ch** [comment]
*`runtests.py`

**Comment by narendraingale2** [comment]
here is the link for gists.

https://gist.github.com/narendraingale2/7ec1e23eb8b6fb94e7c7367539e00422

**Comment by s0undt3ch** [comment]
From the logs, we're failing to get the minion start event even though the minion apparently starts.
I'll ask my team access to a Mac machine to debug this issue.

Meanwhile, in tests/support/process.py, there's a SaltMinion class, add the following there:
```python
    def get_check_events(self):
        if sys.platform.startswith('win'):
            return super(SaltMinion, self).get_check_events()
        return set(['salt/{0}/{1}/start'.format(self.config['__role'], self.config['id'])])

    def get_check_ports(self):
        if sys.platform.startswith('win'):
            return set([self.config['tcp_pub_port'],
                        self.config['tcp_pull_port']])
        return super(SaltMinion, self).get_check_ports()
```

But instead of special casing windows, special case Mac, you can use `salt.utils.is_darwin()`

**Comment by narendraingale2** [comment]
@terminalmage Tried but no luck.

**Comment by s0undt3ch** [comment]
Ok, so I tests running a single integration test module and I was able to without issues, on 10.12:
```
Salt Version:
           Salt: 2016.11.0-952-ga357b88

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: 2.0.0
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Dec 18 2016, 07:03:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6

System Versions:
           dist:
        machine: x86_64
        release: 16.0.0
         system: Darwin
        version: 10.12 x86_64
```

**Comment by narendraingale2** [comment]
I don't know what's wrong with my test environment. Here is my version report.

```
ningale-L111:salt-dev ningale$ sudo salt -c /tmp/salt-tests-tmpdir/config/ -V
Salt Version:
           Salt: 2016.11.0-952-g87b0ef5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.25.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.10 (default, Jul 30 2016, 19:40:32)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6
 
System Versions:
           dist:   
        machine: x86_64
        release: 16.4.0
         system: Darwin
        version: 10.12.3 x86_64
 
ningale-L111:salt-dev ningale$ 
```
When I ran test scripts manually they are running fine.

```
ningale-L111:salt-dev ningale$ sudo salt -c /tmp/salt-tests-tmpdir/config/ '*' test.ping
[WARNING ] Failed to connect to log server
sub_minion:
    True
minion:
    True
ningale-L111:salt-dev ningale$

````

**Comment by cachedout** [comment]
@s0undt3ch We just debugged what could be a similiar issue on Ubuntu 12. We saw the minion unable to connect because the master could start the publisher but crashed on the reqserver. We traced this back to a problem with the new requirement that pytest be installed. Could be the same here. @rallytime has a stacktrace if you want to see one.

**Comment by cachedout** [comment]
@narendraingale2 I'm not sure that I understand your question. If the fix is on your local copy of this branch then you can try to `git stash` your changes, switch to the base branch you need, and then create a new branch and then `git stash pop`. Not totally sure if this addresses your question though.

**Comment by rallytime** [comment]
@s0undt3ch The stacktrace @cachedout is referring to is posted here: https://github.com/saltstack/salt-jenkins/issues/284

**Comment by narendraingale2** [comment]
No @cachedout . What I am saying is I have added fix for this issue directly to develop branch. Instead of creating another branch and committing changes to that branch.

So now If I create  new branch from existing develop branch which contains these fixes would show these changes as well as new changes.

**Comment by narendraingale2** [comment]
Never mind. I have created new branch from saltstack/develop branch and pushed to forked repository.

**Comment by cachedout** [comment]
@narendraingale2 I understand now. You should push those changes to this branch. However, there is now a merge conflict that needs to be resolved first. Could you please rebase this?

**Comment by narendraingale2** [comment]
This need to resubmit again according to new changes. I will work on this.

**Comment by narendraingale2** [comment]
looks like bug is already fixed.

**Comment by cachedout** [comment]
I would like @terminalmage to do a final review here and then this is good to merge. Thanks, @narendraingale2

**Comment by cachedout** [comment]
@terminalmage Just a bump on the pending review request here. Thanks.

**Comment by terminalmage** [comment]
This PR is a bit of a mess in that it contains 50 commits but in effect just adds a single integration test. I've squashed the final three commits of this PR (those that add the test) and opened a new PR, https://github.com/saltstack/salt/pull/40375. The new PR retains the git history of the work that @narendraingale2 did here to add the test, crediting him properly, without adding the other 47 commits to our git log.

Thanks @narendraingale2 for the new test. I did have an integration test which tests for an item being removed, but it wasn't an environment variable, so it did not entirely reproduce your test case. So, it's good to get this in.

Thanks again! I'm going to close this one out since we have your test in https://github.com/saltstack/salt/pull/40375.

**Pull request closed without merging**
