### PR TITLE
new functions for junos modules (lock, unlock, load, commit_check) and changes to install_config

### PR DESCRIPTION
**Pull request by vnitinv**
### What does this PR do?
* Add new functions - lock, load, unlock, commit_check
* Update install_config to lock database before installing config.
* Minor changes in documentation for module, state and engine

### What issues does this PR fix or reference?
NA

### Previous Behavior
install_config did not lock configuration before loading the new one.

### New Behavior
Now, install_config locks the configuration first.
Add new functions - lock, load, unlock, commit_check

### Tests written?
No

### CODE REVIEW

**Comment by vnitinv** [comment]
@cachedout Is develop branch in sync with Nitrogen? If not when they will be synced?
When is the expected release date for Nitrogen?

**Comment by cachedout** [comment]
@vnitinv This will be backported to develop. Nitrogen is slated for the beginning of June.

**Comment by rallytime** [comment]
Since this change was made against `nitrogen` already, nothing needs to be done here for back-porting, and I have removed the label. However, these changes will be merged-forward from `nitrogen` to `develop` as part of the regular merge-forward process. Thanks all!

**Comment by rallytime** [comment]
Also, it looks like these changes were merged into `develop` yesterday in #40677.

**Pull request merged**
