### PR TITLE
#58747: Request addition of --addtag

### PR DESCRIPTION
**Pull request by me-coder**
saltstack#58747: Request addition of --addtag as valid kwarg to linux_lvm module
What does this PR do?

Addresses saltstack#58747
What issues does this PR fix or reference?

Fixes: added new valid argument to vgcreate method of salt module: linux_lvm
Previous Behavior

The support for --addtag was missing.
New Behavior

The vgcreate method would support valid --addtag argument.
Merge requirements satisfied?

[NOTICE] Bug fixes or features added to Salt require tests.

Docs
Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html

    Tests written/updated

Commits signed with GPG?

No

Please review Salt's Contributing Guide for best practices.

See GitHub's page on GPG signing for more information about signing commits with GPG.

### CODE REVIEW

**Comment by waynew** [comment]
Hey @me-coder thanks for the PR!

I've been OOO for a bit and am just catching up, apologies for the wait! I'll be reviewing this PR as soon as I can, thanks for your patience!

**Review by waynew — CHANGES_REQUESTED** [review]
Thanks for the PR! This definitely needs a [changelog entry](https://docs.saltstack.com/en/latest/topics/development/changelog.html) entry, at least.

I have checked the manpage for vgcreate and verified that addtag is valid option. I wonder if we should go ahead and add other options, though :thinking:

**Comment by me-coder** [comment]
> 
> 
> Thanks for the PR! This definitely needs a [changelog entry](https://docs.saltstack.com/en/latest/topics/development/changelog.html) entry, at least.
> 
> I have checked the manpage for vgcreate and verified that addtag is valid option. I wonder if we should go ahead and add other options, though 🤔

Hello @waynew,
I've been occupied with my present project, so sorry for the delay in reply.
I'll make those changes for the [changelog entry](https://docs.saltstack.com/en/latest/topics/development/changelog.html)

I've not considered the other parameters, viz.:
1. `--alloc`
1. `--autobackup`
1. `--metadatatype`
1. `--zero`

Reason for that being my lack of expertise in that area and not able to test these. I've tested `-addtag` to work as it was required in my existing engagement.

Let me know how you typically handle such situations and I'll be happy to help.

Ref: https://man7.org/linux/man-pages/man8/vgcreate.8.html

**Comment by me-coder** [comment]
@waynew 
I've updated the changelog and updated the missed parameters.
Kindly reconsider this PR.

**Review by waynew — APPROVED** [review]
Typically we would require tests, but here you're not actually adding any *behavior*, just entries to a list of valid entries. I've verified that these [are valid options](https://linux.die.net/man/8/vgcreate), so aside from a test that makes a VM and tries these commands I can't really think of a useful way to test. There's `assert these_values == other_values`, but that's not very meaningful.

**Comment by waynew** [comment]
I'm not sure what's up with that pycryptodome failure, though...

**Comment by waynew** [comment]
re-run ubuntu1604-py3-pycryptodome-pytest

**Review by Ch3LL — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
