### PR TITLE
update the schedule to include timezone data if metadata is passed

### PR DESCRIPTION
**Pull request by thatch45**
@pass-by-value I will email you some details on this one

@garethgreenaway heads up on this one, I also added the persist method, please let me know if we don't need this or if you see a better way

### CODE REVIEW

**Comment by pass-by-value** [comment]
Thanks! @thatch45

**Comment by garethgreenaway** [comment]
@thatch45 Couple questions, the persist function is saving the file to _schedule.conf under minion.d.  Is that different than the save function in the schedule module by design?

**Comment by whiteinge** [comment]
I'm seeing an error here after starting the master. Seems the module isn't loaded in time to be available for this call.

```python
[INFO    ] Process <class 'salt.master.Maintenance'> (1713) died with exit status None, restarting...
[DEBUG   ] Started 'Maintenance' with pid 1714
Process Maintenance-91:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/root/src/salt/salt/master.py", line 193, in run
    self._post_fork_init()
  File "/root/src/salt/salt/master.py", line 173, in _post_fork_init
    returners=self.returners)
  File "/root/src/salt/salt/utils/schedule.py", line 246, in __init__
    self.time_offset = self.functions['timezone.get_offset']()
KeyError: 'timezone.get_offset'
```

**Comment by rallytime** [comment]
@whiteinge does #20132 help?

**Comment by whiteinge** [comment]
Thanks, @rallytime. That does it. Good timing!

**Comment by rallytime** [comment]
Excellent! :)

**Pull request merged**
