### PR TITLE
Fix module load order. Related to #5990, #18094

### PR DESCRIPTION
**Pull request by ScoreUnder**
My attempt at fixing module loading. My use case is that I want to override a small selection of functions from an existing larger module. I found that nothing worked and it's in part due to how individual functions are loaded, and in part due to how modules are ordered.

The module ordering was lost because somewhere down the line the data was put into a normal dict.

The individual function loading logic was incorrect because it both ignored the fact that multiple modules can have the same virtual name, and the fact that "higher priority" modules are looked at _first_, so overwriting every time is doing things the wrong way around.

### CODE REVIEW

**Comment by ScoreUnder** [comment]
Transcript from IRC, edited for readability:

> 13:40 < Score_Under> On the test machine, /var/cache/salt/minion/extmods/modules/mac_user_fixes.py  http://paste.pound-python.org/show/CsP0WAqpBpFKNeOVi9KG/
13:41 < Score_Under> http://paste.pound-python.org/show/h3lr7VdVmpnyKNvIu2Rq/ sanitized out the companyname and username but here's the top of what salt-call outputs on that machine
13:42 < Score_Under> I've made a small modification to the salt state for user.present to print out the groups lists while it's modifying them, to help debug the issue
13:44 < Score_Under> The version is "`salt-call 2015.8.5 (Beryllium)`", and if I were to give my best guess I'd say that salt is loading but ignoring my module.
13:46 < AndreasLutro> Score_Under: your paste doesn't make it obvious why or even that your custom module function isn't being used... that error could be caused by a lot of things
13:48 < Score_Under> AndreasLutro: `salt.states.user.present` calls `salt.states.user._changes` which runs `__salt__['user.info']`, so to display that error which I Ctrl+C'd out from, it *must* have called user.info. My module is reporting its name as `user`, contains a function called `info` and is definitely being loaded and having `__virtual__` called. I've got a print at the very top of the `info` function in that module, but the print never fires.
13:50 < AndreasLutro> Score_Under: right, makes sense. I don't know what the problem could be then
13:52 < Score_Under> AndreasLutro: I saw a bug for this closed in 2013, I'm wondering if it is the same thing: https://github.com/saltstack/salt/issues/5990
13:52 < Score_Under> there is also this bug: https://github.com/saltstack/salt/issues/18094 (also closed)
13:56 < Score_Under> I don't believe that bug has been fixed
13:58 < Score_Under> `salt.loader.LazyLoader._load_module` has a loop near the end which copies all attributes to its dict without checking if they existed already in there. `salt.loader.LazyLoader._load(_inner_load)` calls `_load_module` on various modules until the key exists
13:58 < Score_Under> so, two scenarios:
13:58 < Score_Under> 1. `_load_module` is called on the external module first. But that means that when a function is called which exists only on the builtin module, `_load_module` will be called on that and overwrite all the functions exported by the external module
13:58 < Score_Under> or,
13:59 < Score_Under> 2. `_load_module` is called on the internal module first. Since the right function is now in the dict, the external module is never loaded

**Comment by ScoreUnder** [comment]
One more thing I want to add after thinking about this PR:

I'm aware it isn't a full solution: in the event that a .py file's name is unrelated to its virtual name (e.g. if I were to use `mac_accounts.py` instead of `mac_user_fixes.py` or whatever), the lazy loading logic will still cause the builtin module to override the external module. Unfortunately I can't see a way to fix that without removing all the benefits of lazy loading in the process.

**Comment by cachedout** [comment]
It might be a little while before I can get to this but in the meantime, let's see if @jacksontj  @s0undt3ch or @thatch45 have anything to say on this one.

**Comment by thatch45** [comment]
Just for the record, I am thumbs up on changing to an ordered dict here, I think that is the bulk of the problem

**Comment by cachedout** [comment]
This looks right. Well done!

I would love to see additional tests in this area as well, to prevent regressions which could easily happen here. I'll also add a section to the release notes detailing this change. I'll link it to this PR, so I'd love it if you could review it.

**Comment by cachedout** [comment]
Actually, before I merge this I also want @ryan-lane to look at it. I have a vague memory that he's run into this issue before but it was a long time ago.

**Comment by ryan-lane** [comment]
After reading through everything, I'm not sure what the issue is and what's being solved :)

**Comment by cachedout** [comment]
@ryan-lane No worries. I could have sworn a while back that you had an issue wherein functions from custom modules were not overriding stock modules, but I may have been mistaken. Thanks for taking a glance at this regardless.

**Pull request merged**
