### PR TITLE
Allow neutron network list to be used as pillar data

### PR DESCRIPTION
**Pull request by techhat**
@gtmanfred.

### CODE REVIEW

**Comment by gtmanfred** [comment]
nice, +1

**Comment by ljanne** [comment]
Can you backport this to 2014.7?

**Comment by rallytime** [comment]
@ljanne After speaking with @techhat and some of the other engineers, we've decided to back-port this to 2015.5. It will be available in the upcoming 2015.5.1 release. Thanks!

**Comment by ljanne** [comment]
Thank you Nicole!

**Comment by rallytime** [comment]
Sure thing!

**Pull request merged**
