### PR TITLE
add jinja filter to_yaml

### PR DESCRIPTION
**Pull request by angeloudy**
It would be nice to have this `to_yaml` filter.
I use `import_yaml` quite often. With the `to_yaml` filter, it's much easier to dump a section of the imported yaml to the new `sls` file.

### CODE REVIEW

**Comment by whytewolf** [comment]
I was just reading through the PR's and noticed this one. 

I do have one question. how does this differ from the `yaml` filter already in salt?

documentation for the yaml filter can be found here https://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.jinja.html#salt.utils.jinja.SerializerExtension

and code for it https://github.com/saltstack/salt/blob/a953c7027c5387f5dcb4dcbc260152ccb0a78597/salt/utils/jinja.py#L818-L869

I'm not saying don't add it. I'm just trying to understand the difference.

**Comment by angeloudy** [comment]
@whytewolf 
I think the `yaml` filter only formats yaml and does not convert the string to yaml string.

What I want to achieve for the `to_yaml` filter is as following:

For example, I have a pillar file `test1.sls`
```
a:
  aa: aaaa
b: 
  bb: bbbb
c:
  cc: cccc

...

```
now I want to reuse the content in `test2.sls`
```
test2:
{%- import_yaml "test1.sls"  as test %}
{% for key, item in test.items() %}
  {{ item | to_yaml }}
```

Here's where I use `to_yaml` filter, which converts variable `item` to yaml formatted string, while the `yaml` filter will generate something like `{{aa:aaaa}, {bb:bbbb}.......}`

**Comment by whytewolf** [comment]
If you use {{item|yaml(False) }} it should also render the data as you are expecting.

**Comment by angeloudy** [comment]
@whytewolf No, it wouldn't.
You didn't understand my point.
It's not about the styling.
`yaml` filter renders a string in dict format, not yaml.

**Comment by angeloudy** [comment]
@whytewolf I just tested it. And it didn't render the expected result. It seems the `yaml` filter didn't do anything at all. Not sure why.

**Comment by whytewolf** [comment]
So, I just tested. The only difference I can see in your example is that to_yaml includes the `!!python/unicode` statement. otherwise, it is identical to the yaml filter.  

Here is the output of `yaml`, your `to_yaml` and `yaml(false)` in that order.

```
test1:

 {aa: aaaa}

 {cc: cccc}

 {bb: bbbb}


test2:

 {!!python/unicode 'aa': !!python/unicode 'aaaa'}


 {!!python/unicode 'cc': !!python/unicode 'cccc'}


 {!!python/unicode 'bb': !!python/unicode 'bbbb'}



test3:

 aa: aaaa

 cc: cccc

 bb: bbbb
```

In the end, all three of these are pretty identical in functionality to yaml.

**Comment by angeloudy** [comment]
@whytewolf  in your tests, `test3` is the result I expect. But in my tests, only two yaml generates the following
```
test3:

 aa: aaaa

 cc: cccc

 bb: bbbb

```
Could it be some configuration issue?

**Comment by whytewolf** [comment]
Humm, so this might be a bug. can you post your `salt --versions` information. There really isn't config options for this it just works or doesn't. but if python version or something else is getting in the way. In the end, the yaml filter should be fixed so that the `yaml(false)` option works as expected. As this is exactly what it is made for.

**Comment by angeloudy** [comment]
@whytewolf here's the version report
```
Salt Version:
           Salt: 2018.3.1

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.3.13
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.6 (default, Jul 27 2018, 19:19:07)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3

System Versions:
           dist:
         locale: UTF-8
        machine: amd64
        release: 11.2-RELEASE-p4
         system: FreeBSD
        version: Not Installed
```

**Pull request closed without merging**
