### PR TITLE
Issue #18180 Fix fs_type vs fstype inconsistency

### PR DESCRIPTION
**Pull request by rishabhdas**

### CODE REVIEW

**Comment by jfindlay** [comment]
@rishabhdas  thanks for the pull request.  This is a somewhat major API change.  If we (@thatch45) are willing to do it, you will also need to add a note to doc/topics/releases/Beryllium.rst.

**Comment by cachedout** [comment]
@rishabhdas If we're going to do this, we need to put it on a deprecation path instead of just abrubtly breaking the existing behaviour.

I'm fine with something that warns individuals that the behaviour is going to change in a future release to give them time to update but not with this approach.

What do you think about closing this PR and re-opening a new PR that warns users about an upcoming change instead?

**Comment by rishabhdas** [comment]
@cachedout  I am okay following the path of warning the users of upcoming changes. We can close the PR if required.

**Comment by rallytime** [comment]
@rishabhdas We can either close this PR and create a new one with the suggestions from @cachedout, or you can update this one as needed, if you were looking to make those changes. Was another PR opened to address this?

**Comment by rallytime** [comment]
Refs #18180

**Comment by thatch45** [comment]
I am going to close this one out, to make this happen we will need to still support fs_type as a kwargs in the functions

**Pull request closed without merging**
