### PR TITLE
Introduce rollback to Salt States

### PR DESCRIPTION
**Pull request by thatch45**
### What does this PR do?

Introduces rollback capability to Salt State via a tight snapper integration
### What issues does this PR fix or reference?

all the ones asking for rollback
### Tests written?

No, this will require a snapper enabled test environment

@isbm @dmacvicar @meaksh please let me know what you think of how this feature is set up and if you have any feedback.

### CODE REVIEW

**Comment by cachedout** [comment]
Linter picked up some issues here: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/4145/violations/file/salt/modules/state.py/

**Comment by isbm** [comment]
Undefined variable? @thatch45, unit tests? :laughing:

**Comment by thatch45** [comment]
Makes perfect sense that I missed this, since state.pkg is used in salt-ssh which is crazy hard to unit test. But we do have integration tests for it, so I will take a look at why those did not fail. Lint fix incoming :)

**Comment by cachedout** [comment]
Go Go Jenkins!

**Pull request merged**
