### PR TITLE
Moved gitfs code to a seperate module

### PR DESCRIPTION
**Pull request by bahadir**
@terminalmage I had to open another PL. Sorry about it.

### CODE REVIEW

**Comment by jfindlay** [comment]
@bahadir, it looks like there's a gitfs test on both ubuntu and CentOS.

**Comment by bahadir** [comment]
@jfindlay Yeah, I'm on it.

**Comment by jfindlay** [comment]
Awesome, thanks.

**Comment by bahadir** [comment]
OK, tests have passed.

**Comment by thatch45** [comment]
I like this, I want a thumbs up from @terminalmage before the merge though

**Comment by terminalmage** [comment]
I'm working on some bugfixes in the 2014.7 branch, so I will wait until those fixes have been merged forward into develop and then manually resolve the merge conflict.

**Comment by thatch45** [comment]
Thanks @terminalmage

**Comment by thatch45** [comment]
Since we are waiting on @terminalmage 's changes to make this happen and since I have talked to him about a refactor here I am going to close this out for now.

**Comment by terminalmage** [comment]
Yeah. @bahadir has the right idea here, but I'm planning on making a fileserver config class to reduce code duplication, which can apply to any of the VCS fileserver backends.

**Pull request closed without merging**
