### PR TITLE
(Backport 49037) Fix case where args or kwargs are not specified in loop state

### PR DESCRIPTION
**Pull request by aplanas**
Backport to master of https://github.com/saltstack/salt/pull/49037

### CODE REVIEW

**Comment by aplanas** [comment]
Looks like that one fail in the centos6 test is in 'integration.modules.test_shadow.ShadowModuleTest', where the random users 'tu-XXXX' are expected, but not present in the system.

Is this a known error that is addressed somewhere else?

**Comment by s0undt3ch** [comment]
These do kind of seem like some flaky test failures we've seen before, @dowz?

**Review by dwoz — APPROVED** [review]

**Comment by dwoz** [comment]
@aplanas @s0undt3ch They pass now, must be flaky tests. Merging

**Comment by s0undt3ch** [comment]
:+1:

**Pull request merged**
