### PR TITLE
Use .NET to gather NIC information on newer systems

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?
Uses .NET to gather Network Interface Information. Maintains old code that uses WMI to gather that information for use on Windows 7/2008R2 which has .NET 3.5 which is incompatible with the `pythonnet` library. Though you can install .NET 4 on Windows 7, it's not there out of the box.

### What issues does this PR fix or reference?
This should fix some issues with slowness in Windows as this code is used in generating grains. Where the average run for doing so is 3.5 seconds with WMI, it is ~1 second with .NET.

Also adds the gateway in the return for Windows, which is present on other systems:
https://github.com/saltstack/salt/issues/51128

### Tests written?
Not yet, hence the WIP

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by dwoz — APPROVED** [review]

**Comment by s0undt3ch** [comment]
This actually broke develop under Linux
https://github.com/saltstack/salt/pull/53362/commits/fded9da495a3d891294455b223e818471a7c35dc

**Comment by aplanas** [comment]
yep: https://github.com/saltstack/salt/pull/53381

**Comment by aplanas** [comment]
@s0undt3ch where is the PR where this commit is living?

**Comment by s0undt3ch** [comment]
https://github.com/saltstack/salt/pull/53362

**Comment by s0undt3ch** [comment]
This also brings in another python dep `pythonnet`. Please confirm @twangboy

**Comment by twangboy** [comment]
Yes... it was added to the `salt/pkg/windows/req.txt`.  I was unaware of the additional requirement to use the static files.

**Pull request merged**
