### PR TITLE
Mac power tests

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?

Adds unit tests for the mac_power module.
https://github.com/saltstack/zh/issues/546
### Tests written?
- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by cachedout** [comment]
I'm not sure what functionality is actually tested here. These tests are effectively asserting that what's effectively a single-line function is being called exactly as it's written in the code. We've had a great deal of trouble already with these types of tests since every time the line in question modified, the test breaks.

Tests should be written in such a way that we either test _logic_ contained inside functions (if they are unit tests) or the _effect_ of the given function on a running system (as an integration test). 

In this case, there is essentially no logic inside these functions and so writing unit tests is simply tightly-coupled overhead that's likely to break and doesn't provide any real benefit.

To be honest, I don't see the benefit of testing this module this way at all. If anything, it would be better to remove these and write unit tests which attempt to exercise the functionality in `salt.utils.mac_utils`, since that's the only real place in this module where any logical decisions seem to be called.

**Comment by twangboy** [comment]
@cachedout So is the `_validate_sleep` function the only one that will need tests?

**Comment by cachedout** [comment]
This is much better. Thanks.

**Comment by cachedout** [comment]
@twangboy Some lint errors to clean up, please.

**Pull request merged**
