### PR TITLE
Port PR #48989 to master

### PR DESCRIPTION
**Pull request by nicholasmhughes**
### What does this PR do?
Port PR #48989 to master

### What issues does this PR fix or reference?
PR #48989 

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by cmcmarrow — DISMISSED** [review]
Looks good!

**Comment by nicholasmhughes** [comment]
re-run ubuntu1604-py3-m2crypto

**Comment by nicholasmhughes** [comment]
@cmcmarrow can you re-up your review?
@dwoz tests fixed

**Comment by cmcmarrow** [comment]
@nicholasmhughes sorry for the delay. Had sometime off due to the 4th.

**Review by cmcmarrow — APPROVED** [review]

**Comment by cmcmarrow** [comment]
Your PR is good to be Merged. Thanks for helping port PRs to Master!

**Pull request merged**
