### PR TITLE
Allow SMTP return to use a template

### LINKED ISSUE #23453: modifying the returner output when using smtp_returner
1- I am wondering if there is a way to customize the output which send by returner to my email to make it easy to read and understand 

currently i am receiving output in my email like this

```
id: minion_001
function: state.sls
function args: ['coreutils-viewer-formula.cv']
jid: 20150507114251356220
return: {'module_|-cv_download_|-git.clone_|-run': {'__run_num__': 2,
                                            'changes': {'ret': 'Initialized empty Git repository in /usr/local/src/cv/.git/'},
                                            'comment': 'Module function git.clone executed',
                                            'duration': 4920.6030000000001,
                                            'name': 'git.clone',
                                            'result': True,
                                            'start_time': '11:42:54.409548'},
 'module_|-cv_install_|-cmd.run_|-run': {'__run_num__': 4,
                                         'changes': {'ret': 'cc -g -Wall -D_FILE_OFFSET_BITS=64 -c cv.c\ncc -g -Wall -D_FILE_OFFSET_BITS=64 -c sizes.c\ncc -g -Wall -D_FILE_OFFSET_BITS=64 -c hlist.c\ncc -Wall cv.o sizes.o hlist.o -o cv -lncurses -lm\nInstalling program to /usr/local/bin ...\nInstalling manpage to /usr/local/share/man/man1 ...'},
                                         'comment': 'Module function cmd.run executed',
``` 
which need to be modified in order to make it readable. or it would be nice if it can be send just like highstate output!

2- is there a way to use jinja in `smtp.subject:` so i can define the minion in subject ?

### PR DESCRIPTION
**Pull request by techhat**
Fixes #23453.

### CODE REVIEW

**Comment by techhat** [comment]
@basepi and @terminalmage, my fork keeps adding these merge commits, would one of you please ping me and help me out?

**Comment by techhat** [comment]
Go Go Jenkins!

**Comment by techhat** [comment]
@jfindlay can you help me out here?

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
looks like that did it....

**Comment by techhat** [comment]
@jfindlay can you please help me troubleshoot the failure here?

**Comment by jfindlay** [comment]
@techhat: https://github.com/techhat/salt/pull/1.

**Comment by Code-Vortex** [comment]
@techhat could you explain what values should be added to the config file ? i tried smtp.template: yaml_jinja and smtp.renderer: yaml_jinja which is not working for me too

**Comment by techhat** [comment]
```
smtp.template: /path/to/template.jinja
smtp.renderer: yaml_jinja
```

**Pull request merged**
