### PR TITLE
Modularize tgt

### PR DESCRIPTION
**Pull request by kstreee**
### What does this PR do?

Modularizes targeting logic of salt stack.
The previous version of targeting logic is implemented in a single file `/salt/utils/minions.py`.
The file re-organized into  several files, such as `/salt/tgt/__init__.py` and `/salt/tgt/glob.py`, `/salt/tgt/list.py`, `/salt/tgt/compound.py`, ...
Followings are details of this pr.

1. The architecture of the modularized version of targeting logic.

- CkMinions elimination
Removed CkMinions class, and then moved every function in the class to `/salt/tgt/__init__.py` as native functions. As consequence of removing the class, each function has to take 'opts' as a function parameter. For example, `def check_minions(self, ...)` has been changed to `def check_minions(opts, ...)`, and `def spec_check(self, ...)` has been changed to `def spec_check(...)` (some functions including `spec_check` don't use `opts` at all).

- Targeting modules
Targeting modules are moved into each file in the directory `/salt/tgt/`. Original funcitons were implemented in `/salt/utils/minions.py`, for example, `_check_compound_minions`, `_check_glob_minions`, and the functions moved into `/salt/tgt/compound.py` and `/salt/tgt/glob.py` respectively.

- Patches
  + Integrated same, but dispersed code by moving it into a function.
Newly implemented functions `pki_dir_minions`, and `pki_dir_acc_path` are one of those.
  + `check_minions`, `check_compound_minions`
Patched the two functions (in `/salt/tgt/__init__.py` in our modularized version) to use lazily loaded targeting modules and `format_call`.
  + diffs
You can check function wise diffs through the following link. Git can't follow the modification, so we prepared it to compare easily.
https://github.com/GwiYeong/salt-modularize-tgt-diff/commit/b1cd599b444254113b34e3b109f0578c5fbf0f1a

2. Questions

- salt/daemons/flo/maint.py
We don't know exact meaning and intention of this file, so we just changed mechanically from CkMininos to tgts (patched version of CkMinions). We are pretty sure that it should be modified further to patch correctly. If someone let us know uses of this file, we will patch it.

- /salt/utils/thin.py
We added every file which are located in the directory `/salt/tgt/` at the data structure `min_files` in `/salt/utils/thin.py`. But we don't know exact roles of the logic, so we think someone should check this change.

### What issues does this PR fix or reference?

This pr is related to the issue #44637.

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by kstreee** [comment]
F.Y.I., We are investigating failed test cases and going to fix the cases to make all green. :)

**Comment by rallytime** [comment]
Hi @kstreee - Thanks for this! Before you look into _all_ of the test failures, you might want to rebase this with the most current version of develop, and maybe even after I get the next merge-forward completed. We've had some test issues come up that we are also working on fixing. Some of the failures here I know have been fixed downstream and I am merging forward today.

**Comment by rallytime** [comment]
Hi @kstreee - there's some merge conflicts here. Can you take a look?

**Comment by rallytime** [comment]
@kstreee The following test failures are related: 

- unit.daemons.test_masterapi.LocalFuncsTestCase.test_publish_user_authorization_error
- unit.test_master.ClearFuncsTestCase.test_publish_user_authorization_error

**Comment by kstreee** [comment]
@rallytime I haven't been aware of the failed tests  😂. Thank you for notifying me. I will fix to pass the tests.

**Comment by rallytime** [comment]
@kstreee No problem! They were a bit buried in there with many non-related failures. Thank you!

**Comment by kstreee** [comment]
@rallytime Hi, I fixed the two related failed cases. It was caused by miss-merged test cases [here](https://github.com/saltstack/salt/pull/45097/commits/679aa84203cb52ca9c0396ef21f2eb380be5a98c#diff-e3e43860f9f4b6816576771763684aa5L550) and [here](https://github.com/saltstack/salt/pull/45097/commits/679aa84203cb52ca9c0396ef21f2eb380be5a98c#diff-ce0c7e926d34c94d58a717e6c40be57aL333).

**Comment by cachedout** [comment]
I have major concerns about this.

This has every potential for serious regressions. I'm deeply uncomfortable with this until we are absolutely certain that what's being touched is totally covered by adequate test coverage. Even then, I'd like to see a more in-depth explanation of the potential benefits of modularizing this. This is major surgery on a critical function of Salt and I'm exceedingly nervous about just doing it without moving much more slowly and methodically.

**Comment by kstreee** [comment]
Hi, @cachedout ,

I totally understand what your concerns, and I also don't want to rush this pr make to be merged into mainstream branches. Even we already use salt master which is applied this pr, we haven't used a wide range of salt features, so we can't 100% sure about this too. Thus, I agree that it must be more carefully, and precisely discussed and tested before merged into other branches. I hope that committers assume this pr as a place to share opinions of the new architecture of the targeting code, not as just before being merged status.

Additionally, followings are my opinions about major benefits of the modularizing work.
1. By tearing the targeting code (`/utils/minions.py`) into several files module by module to improve the architecture of the code. In my opinion, it should be done eventually to keep maintaining the targeting code. By modularizing it, we can reduce the complexity of dependencies in the code to more intuitive forms.
2. Providing an easy environment to implement custom targeting modules.
  For example, current salt provides targeting module which uses 'SECO range'. We need similar ways to specify minions but we already use another internal system that can provide various kinds of ranges for minions. In current salt, to add 'SECO range' like targeting module, we have to modify `/utils/minions.py`. But, the modification not only isn't an easy work but also will make us hard to merge with a future version of salt stack. (Customized targeting module is necessary for us. We run salt over 10K+ minions and various ways of specifying minions to provide salt stack as a server-to-server platform, cli tools, an emergency channel, and others, but current targeting modules are not enough for us, even the current targeting modules are well designed.)


I think following topics should be discussed further.
  - is it really beneficial to salt stack?
  - (if it is beneficial enough to salt stack, ) the new forms of code is a solid approach? or is there any other better ways to modularize targeting modules?
  - (if it is beneficial enough to salt stack, ) how to make this pr be not harmful to other parts of salt?
    * (idea) Adding test cases for all `/utils/minions.py` call sites to ensure that targeting module works exactly same with the previous version. Also, every test case must cover every implemented targeting modules including compound.

**Comment by rallytime** [comment]
I realize there is already some code here, but this might be a really good candidate for using the RFC process we're starting to use: https://github.com/saltstack/salt/tree/develop/rfcs

**Comment by kstreee** [comment]
@rallytime That sounds a good idea! I will change this PR into RFC. Thanks for the suggestion.

**Comment by rallytime** [comment]
Based on the discussion above, this needs to be changed to an RFC and won't be merged as it currently stands. Therefore, I am going to close this PR. We can certainly continue the discussion and we'd love to see the PR submitted as an RFC so we can all discuss this approach a little more. Thanks!

**Pull request closed without merging**
