### PR TITLE
Fix `unit.utils.test_find` for Windows

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?
Fix skipIf statements
Use sys.maxsize instead of sys.maxint for all versions of Python

### What issues does this PR fix or reference?
https://github.com/saltstack/salt-jenkins/issues/439

### Tests written?
Yes

### CODE REVIEW

**Comment by rallytime** [comment]
re-run py3

**Comment by cachedout** [comment]
IMHO, we need to do a little more cleanup work here.

If `salt.utils.find` is not going to be supported whatsoever on Windows, it needs to be declared as-such instead of just quietly removing test coverage. Alternatively (and preferably) we need a version of this utility that _does_ work on Windows.

**Comment by twangboy** [comment]
I agree. They were already skipped for Windows, just incorrectly. This only fixes the skip statements.

**Comment by cachedout** [comment]
I will merge this but I remain concerned that those issues I brought up will remain unresolved. Let's be sure to come back to them and get them fixed properly.

**Comment by twangboy** [comment]
Created an issue ^^^

**Pull request merged**
