### PR TITLE
Fix issue #11497

### PR DESCRIPTION
**Pull request by efficks**
### What does this PR do?

Fix issue #11497
### What issues does this PR fix or reference?

Move the test for working directory presence after the should run test (unless or if).
### Previous Behavior

If the working directory does not exists, the command will failed even if check commands (unless) returns that the command should not be runned.
### New Behavior

cmd.run and cmd.wait won't failed if the working directory does not exists and unless check returns that the command should not be runned.
### Tests written?

No

### CODE REVIEW

**Comment by rallytime** [comment]
@efficks Thank you for resubmitting this against the 2015.5 branch. Would you mind rebasing this change really quickly? Based on the pylint test restult, I think this was made off of an older version of 2015.5, and since this touches code in an important piece of salt, I want to make sure the tests are running accurately. I am not sure if these current test failures are related or not.

If you run into trouble, let us know and we can help! :)

**Comment by efficks** [comment]
@rallytime I've made the change on the latest 2015.5 branch. What can I do to submit it correctly?

**Comment by rallytime** [comment]
@efficks Hrm...Perhaps your fetch was a little old? Both the pylint and branch tests are passing right now on the 2015.5 branch. The lint failures that are being reported here were ones we were seeing a week or two ago when we were transitioning to a new pylint runner that has a newer version of lint. Those files have all since been fixed up, which is what is indicating to be that your 2015.5 branch may be a little older.

We have some docs on rebasing in number six of our "contributing" docs here: https://docs.saltstack.com/en/latest/topics/development/contributing.html#sending-a-github-pull-request

**Comment by efficks** [comment]
@rallytime Done ;-)

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
@efficks Thank you very much for working on this. There were a couple of related test failures here, but I fixed them up and merged your change in with PR #32418. Thanks again!

**Pull request closed without merging**
