### PR TITLE
[2016.11] Merge forward from 2016.3 to 2016.11

### PR DESCRIPTION
**Pull request by rallytime**
Conflicts:
  - doc/ref/cli/salt-cp.rst
  - salt/config/__init__.py

### CODE REVIEW

**Comment by rallytime** [comment]
Well, the cherrypy tests passed before, but when I added the missing `StringIO` import in the gzip utils files, they now fail, and i can't reproduce this failure locally.

**Comment by rallytime** [comment]
Working on chasing this down now.

**Comment by terminalmage** [comment]
It turned out that ``test_issue_7754`` wasn't actually transmitting a file, it was copying a nonexistant path and then checking that the minion and sub-minion were in the return dict. No check for success.

So, when I "fixed" that test, it started transmitting files properly, and brought this separate issue to light. When you make a call to the ``/jobs`` salt-api endpoint, and request back JSON return data, ``json.dumps()`` chokes on the binary data left in the job cache by the salt-cp call in the earlier test.

I fixed this by base64-encoding chunks on the master-side before publishing, and decoding before writing to disk minion-side.

**Comment by rallytime** [comment]
Thanks for your help @terminalmage!

**Pull request merged**
