### PR TITLE
Fix uppercase computer names

### LINKED ISSUE #31290: Windows hostnames are dealt with in all uppercase
When using the `win_service` state execution module, I've noticed that the hostname is always set all in uppercase, e.g. `MYMINION` even if the provided hostname is `MyMinion` or `myminion`. It would be very useful if the hostname wasn't always set in all uppercase.

The Windows command `hostname` returns the hostname as-is, and not in all uppercase, and could perhaps be used instead of the current method:

    C:\> hostname
    MyMinion

Also, if Python were to be used to get the hostname, this also works fine:

    import socket
    socket.gethostname()
    >> MyMinion

Quoting @twangboy from https://github.com/saltstack/salt/pull/31222 ...

> @fredrikaverpil The function is in execution module win_system.py. It's right around line 344. (You may be looking in the state module.) It calls another function called get_system_info which returns a dictionary containing system info. The name element of the dictionary contains the Computer Name.
get_system_infocalls the windows api function `NetServerGetInfo` which returns information about the system, including a capitalized computer name.
So, the real issue here is the ability to get and set case sensitive computer names which would require a pretty big change in the way the win_service.py module works. Would you mind opening an issue on this?

### PR DESCRIPTION
**Pull request by twangboy**
Supercedes: https://github.com/saltstack/salt/pull/31375
Which superceded: https://github.com/saltstack/salt/pull/31222

Fixes: https://github.com/saltstack/salt/issues/31290

Fixes Capitalized Computer name for states and for current in set_computer_name function
No way to fix the capitalization in Pending Computer name. (That's how it's stored in the registry). I couldn't find where windows stores the un-capitalized version of the pending computer name. So, if
the pending name matches the new name, it will pass the new name. Otherwise, it will return an All Caps pending name.

Execution Module returns:

```
gringo:
    ----------
    Computer Name:
        ----------
        Current:
            Gringo
        Pending:
            Gringo-Test
```

State returns:

```
gringo:
----------
          ID: set_name
    Function: system.computer_name
        Name: Gringo-Test
      Result: True
     Comment: Computer name successfully set to 'Gringo-Test' (reboot required for change to take effect)
     Started: 16:28:24.955000
    Duration: 16.0 ms
     Changes:
              ----------
              new:
                  Gringo-Test
              old:
                  Gringo

Summary for gringo
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```

Also adds more computer information for get_system_info.

### CODE REVIEW

**Comment by cachedout** [comment]
We still need to document this change, please.

**Comment by twangboy** [comment]
@cachedout Do you want it in this PR or another one?

**Comment by cachedout** [comment]
@twangboy Please put it in this one.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Still waiting on release notes before we can get this merged.

**Comment by twangboy** [comment]
@cachedout Added release notes

**Comment by cachedout** [comment]
@twangboy Excellent. Thank you.

**Comment by fredrikaverpil** [comment]
Hey guys, this is great. How can I see when this is slated for release?

I should be fine to manually download `win_system.py` and put this in my `_modules` and `_states` folders, respectively, in the interim, right?

**Comment by twangboy** [comment]
@fredrikaverpil This was merged into the develop branch, therefore it is scheduled for our carbon release which may happen later in the year.

**Comment by fredrikaverpil** [comment]
@twangboy ok, thanks.

**Pull request merged**
