### PR TITLE
RFC: Add additional ZMQ tuning parameters necessary for 1k+ minions per master [WIP]

### PR DESCRIPTION
**Pull request by plastikos**
Do not merge

Start collecting tuning parameters together in the master config file.

### CODE REVIEW

**Comment by plastikos** [comment]
These specific tuning parameters were used with the following configuration:

   * 32 GiB RAM
   * 24 Cores
   * 2.2 GHz
   * 8,400 Minions

It seems that the most significant thing for servicing large numbers of minions is CPU cores and GHz.  If the ZMQ queues get backed-up into memory too far then the machine will get swamped, fall behind and the OOM killer will start wacking processes.  Additionally this can all be compromised by a slow job cache.

**Comment by basepi** [comment]
Updated the title in order to make it more obvious this should not be merged without more review.

**Comment by jacksontj** [comment]
We should include HWM configuration for the REQ socket as well-- since (at least in my experience) thats where most of the HWM issues are (since its the busiest socket).

**Comment by plastikos** [comment]
@jacksontj, my instrumented ZMQ has never triggered the HWM for the REQ socket - but maybe I don't have the correct use pattern to cause this.  Can you describe a use pattern where the REQ socket will trigger the HWM?

**Comment by jacksontj** [comment]
The vast majority of cases end up being that REQ socket (at least in my experience). When you do a publish-- that initially goes through the REQ socket (locally). In addition, if a lot of minions return data at close to the same time-- that all goes through the REQ socket.

What might be a bit confusing-- is I don't mean the zmq.REQ socket on the minion-- rather I mean the router/dealer/req sockets on the master.

**Comment by cachedout** [comment]
@plastikos Are we ready to go on this one?

**Comment by plastikos** [comment]
Sure, merge it if you want.  This is useful, but not complete.  I haven't pushed this because I'm not convinced the problem has been completely characterized for a complete solution.

**Comment by cachedout** [comment]
It's been in the queue for a while so I'm just going to merge it as-is and of course follow-ups are more than welcome. :]

Thanks for your good work here, @plastikos

**Comment by jtand** [comment]
@cachedout @plastikos I have a feeling that this may have broke develop. Most platforms are stacktracing in our tests until I stop them. 

Stacktrace:

```python
20:47:15 Process EventPublisher-18:
20:47:15 Traceback (most recent call last):
20:47:15   File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
20:47:15     self.run()
20:47:15   File "/testing/salt/utils/event.py", line 882, in run
20:47:15     self.epub_sock.setsockopt(zmq.SNDHWM, self.opts.get('event_publisher_pub_hwm'))
20:47:15   File "zmq/backend/cython/socket.pyx", line 390, in zmq.backend.cython.socket.Socket.set (zmq/backend/cython/socket.c:4138)
20:47:15 TypeError: expected int, got: None
```

**Comment by plastikos** [comment]
@jtand, your stack trace is due to some objects incorrectly passing opts.  I thought all of those locations had been fixed.  I'll look into it.

What has happened in the past is that default option values were put into config.py as well as the location where the option was used because opts wasn't correctly passed in to object initialization.  The object initialization should be fixed rather than scattering default values into multiple files.

**Comment by plastikos** [comment]
@jtand - some of the `opts` parameter passing was even transposed with other variables.  In the past some of it was so bad I'm not sure how anything worked.  I'm digging around on this right now.

**Comment by cachedout** [comment]
I already fixed this issue earlier today.

**Comment by plastikos** [comment]
See #28189

**Comment by cachedout** [comment]
@plastikos Would you feel comfortable if we backported this to the 2015.8 branch?

**Comment by cachedout** [comment]
@rallytime Can you backport this please?

**Comment by rallytime** [comment]
Certainly!

**Pull request merged**
