### PR TITLE
Fix issue where pyVmomi 6.0.0 raises SSL Error for systems using Python2.7+

### PR DESCRIPTION
**Pull request by nmadhok**
Fixes https://github.com/saltstack/salt/issues/29537

### CODE REVIEW

**Comment by rallytime** [comment]
I tested this on my Ubuntu 14 box that runs my proxy minion, and it's throwing a stacktrace. See [this comment](https://github.com/saltstack/salt/issues/29537#issuecomment-170066438) for more information.

**Comment by cachedout** [comment]
@nmadhok Where are we on this one? Please let me know. Thanks.

**Comment by nmadhok** [comment]
@cachedout This should be merged in my opinion. See https://github.com/saltstack/salt/issues/29537 for the followup.

**Comment by rallytime** [comment]
Please wait to merge. We're still discussing this fix in #29537.

**Comment by rallytime** [comment]
Ok, after discussing this with @cro, I think this is definitely a good fix for people to use pyvmomi 6.0, but we need to make sure we're very clear in the docs about what versions of ESXi, pyVmomi, and Python are required to make this work correctly.

@nmadhok Can you add some documentation explaining that pyVmomi >= 6.0.0 is only supported on systems using Python >= 2.7.9 and for systems using Python < 2.7.9, they should use pyVmomi 5.5.0-2014.1.1 by doing a `pip install pyvmomi==5.5.0-2014.1.1`. There should already be docs explaining the `5.5.0-2014.1.1` version installation, so we just need to add to the Python version information to work with pyVmomi 6.0, I think. After that documentation is added, I think this should be good to go in.

Thanks for your work, as always, @nmadhok!

**Comment by nmadhok** [comment]
@rallytime Already got a PR that lists it. Was waiting for this one to get merged first. Going to create the PR soon.

**Pull request merged**
