### PR TITLE
Introduce presence ping timeout parameters for sync batch

### PR DESCRIPTION
**Pull request by chiaradiamarcelo**
### What does this PR do?
- Introduce "batch_presence_ping_timeout" and "batch_presence_ping_gather_job_timeout" parameters for synchronous batching mode.
If this parameters are not sent, the "timeout" and "gather_job_timeout" are used as default instead.
- Remove duplicate code for initializing opts values

### Previous Behavior
Before, "timeout" and "gather_job_tmeout" parameters were used for the presence ping in synchronous batching mode.

### New Behavior
presence ping in synchronous batching mode uses "timeout" and "gather_job_tmeout" parameters as default values, but can be overridden in the request with  "batch_presence_ping_timeout" and "batch_presence_ping_gather_job_timeout".

### Tests written?
No 

### Commits signed with GPG?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by dwoz — CHANGES_REQUESTED** [review]
@chiaradiamarcelo Thanks for the contribution. Can you please add a test for this change?

**Comment by sagetherage** [comment]
@chiaradiamarcelo are you able to rebase this against the master branch? we are no longer accepting changes to the develop branch. We may close this as abandoned if we do not hear from you.

**Comment by sagetherage** [comment]
@chiaradiamarcelo are you able to rebase this against the master branch? we are no longer accepting changes to the develop branch.

**Comment by sagetherage** [comment]
Reviewed in Grooming 2021-MAY-03 closing

**Pull request closed without merging**
