### PR TITLE
Set the name of engine processes #60259

### LINKED ISSUE #60259: [FEATURE REQUEST] Add process titles to engines.
**Is your feature request related to a problem? Please describe.**

Engine processes are not identifiable. 

**Describe the solution you'd like**

Use setproctitle to add process titles to engines so we know which process belongs to specific engine.

### PR DESCRIPTION
**Pull request by dwoz**
### What does this PR do?

Makes engine processes identifiable by setting their process names.

### What issues does this PR fix or reference?
Fixes: #60259

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### CODE REVIEW

**Comment by max-arnold** [comment]
What do you think about displaying different process names or suffixes (possibly taken from engines config section) in case when there are multiple instances of the same engine running: https://github.com/saltstack/salt/pull/50059

**Comment by dwoz** [comment]
> What do you think about displaying different process names or suffixes (possibly taken from engines config section) in case when there are multiple instances of the same engine running: #50059

Yes, I like that idea.

**Review by krionbsd — DISMISSED** [review]

**Review by Ch3LL — CHANGES_REQUESTED** [review]
just missing a changelog

**Comment by Ch3LL** [comment]
@krionbsd can you also re-review

**Review by krionbsd — DISMISSED** [review]

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
