### PR TITLE
Fix save_load to add doc if not exists

### PR DESCRIPTION
**Pull request by kunal-bajpai**
### What does this PR do?
Fix couchbase returner to add document with key JID to couchbase if it does not already exist

### What issues does this PR fix or reference?
#43260 

### Previous Behavior
`couchbase.save_load` fails if `couchbase.prep_jid` has not been called before. This is becuase `prep_jid` writes a doc with key JID to cb that `save_load` later updates.

### New Behavior
If `couchbase.save_load` cannot find a doc with key JID, it adds one.

### Tests written?
No but tested on local cluster

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
I'm curious to know under what condition you find `prep_jid` not being called? That shouldn't happen in normal operation.

**Comment by kunal-bajpai** [comment]
@cachedout when `ext_job_cache` is set to `couchbase`, `couchbase.prep_jid` is not called
Full reference in the linked issue #43260

**Comment by kunal-bajpai** [comment]
@cachedout @gtmanfred can you review this please?

**Review by gtmanfred — APPROVED** [review]
This is the same way we are doing this for the postgres returner, if it is not already in there, we create the jid on the save_load.

https://github.com/saltstack/salt/blob/2017.7/salt/returners/postgres.py#L269-L271

prep_jid only happens when using it as a master job cache, it is not called by the external job cache.

Though I think the longer term solution should be to make sure we call prep_jid with the jid that the master has passed to the minion in the external job cache task.

**Comment by kunal-bajpai** [comment]
@gtmanfred thanks for reviewing. I believe the behaviour of every method in the interface should be explicitly defined - the criteria for success and failure of each method. I've opened another issue (#43452) which arises from the interface not being too specific about behaviour (`couchbase` fails to fetch job returns if load is not present in the cache but `local_cache` does not). A long term solution would also require establish these criteria and reviewing returners to make sure they conform to them.

**Comment by kunal-bajpai** [comment]
@gtmanfred can this be merged?

**Comment by KumarRajnish** [comment]
All,

Due to a misconfiguration on our Office365 tenant, all email addressed to your Ruckus Wireless email address (you@ruckuswireless.com) were delivered to a catch all mailbox.  This incident occurred between 11 PM to 8 AM (PST).  IT is delivering these emails with a “Reply-all” rule to all individuals on the email chain.  If you feel you are missing email attachments, please send email to helpdesk@ruckuswireless.com.

We apologize for any inconvenience this may have caused.

Regards,

IT

**Pull request merged**
