### PR TITLE
Add Windows shortcut support to salt.states.file

### PR DESCRIPTION
**Pull request by mtkennerly**
I'm still in the process of trying to write the unit tests for this, but I'd appreciate some initial feedback to make sure it's going in the right direction. I've tried to base it heavily on file.symlink, but I noticed that the unit test for file.symlink doesn't really seem to jive with the [unit test standards](https://docs.saltstack.com/en/latest/topics/development/tests/unit.html#best-practices) (namely since it's a single test function with several asserts and is tightly coupled to the exact text of the output), so I don't know if maybe I'm basing this on older code that isn't quite the encouraged style. Are there any other unit tests that I should be looking to as a model? Should I deviate from the file.symlink pattern in order to break it up into smaller functions?

### What does this PR do?
Adds a file.shortcut function for creating Windows shortcuts. These have distinct functionality that is not fulfilled by file.symlink.

### What issues does this PR fix or reference?
Although not the main point of the issue, the idea of adding a file.shortcut was mentioned in #18625 as part of enabling what the issue author was trying to accomplish.

### Tests written?
Not yet

### CODE REVIEW

**Review by cachedout — CHANGES_REQUESTED** [review]
Can you please fix the lint errors found here?

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/10192/violations/file/salt/states/file.py/

**Comment by mtkennerly** [comment]
@cachedout I fixed the pylint errors, but now there are a bunch of new errors (1000+) in unrelated files about "Blacklisted salt loader dunder usage". I'm guessing some setting on the server got changed?

**Comment by cachedout** [comment]
@mtkennerly Yes, it did. Apologies for that. Your fixes look right. We'll get this in. Sorry about the confusion there!

**Review by cachedout — APPROVED** [review]

**Comment by twangboy** [comment]
Much of the code needs to be moved into the `win_file.py` execution module. The state modules generally use execution modules to perform the actual work with the state module only ensuring that the system is in the correct state.

**Comment by mtkennerly** [comment]
@twangboy That makes sense. I'll take a look at moving it and open a new pull request.

**Pull request merged**
