### PR TITLE
Fix runner tests

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?
Fixes failing runner tests
Skips test in test_state.py that was causing pickling errors on Windows
Comment on another test that fails on Windows

Need to get more eyes on this. I don't understand the purpose of the code I removed. But it was causing all the failures on the runner tests. Valid return was being replaced with a dict with a single entry, retcode.

Perhaps @isbm could shed some light on it.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/52091

### Tests written?
Yes

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by cachedout** [comment]
IIRC this was the same code that @mattp- was concerned with the other day.

**Comment by isbm** [comment]
Leaves me wondering how that got in. Clearly my commit, according to blame, but more looks like a rebasing mistake.

**Comment by mattp-** [comment]
@dwoz I think the change in https://github.com/saltstack/salt/pull/52258 might make more sense as a fallback when ret is an empty dict, just to ensure a failure retcode is present when something definitely went wrong.

**Review by dwoz — APPROVED** [review]

**Comment by dwoz** [comment]
re-run centos-7

**Comment by Ch3LL** [comment]
FYI I migrated this PR from develop to neon to ensure it is included in the upcoming neon release. Let me know if this caused any issues. Thanks

**Pull request closed without merging**
