### PR TITLE
Properly obtain hostname fqdn in function get_fqhostname()

### PR DESCRIPTION
**Pull request by msciciel**
### What does this PR do?
If socket.getaddrinfo successfully obtain ip address it should
overwrite result of socket.getfqdn otherwise whole try/except
is superfluous.

### What issues does this PR fix or reference?
#48906 

### Previous Behavior
Use only socket.getfqdn as a source of hostname

### New Behavior
Use socket.gethostname as hostname and fallback to socket.getfqdn

### CODE REVIEW

**Review by gtmanfred — APPROVED** [review]

**Review by DmitryKuzmenko — APPROVED** [review]

**Comment by rallytime** [comment]
I'd like to see some tests written around this before we merge this in.

**Comment by msciciel** [comment]
Should I write these tests ?

**Comment by rallytime** [comment]
@msciciel yes, please. :)

**Comment by msciciel** [comment]
@rallytime please verify if provided test is enough.

**Review by cachedout — APPROVED** [review]

**Review by terminalmage — APPROVED** [review]

**Comment by msciciel** [comment]
Is it possible to backport this to `2017.7` and `2018.3` ?

**Comment by gtmanfred** [comment]
Maybe.

@rallytime why did you initially remove the `bugfix - back-port` on this issue?

**Comment by rallytime** [comment]
I removed that since this fix is in a very sensitive area of the code and wanted to give it some time to sit in develop.

**Pull request merged**
