### PR TITLE
Add caching loader, with msgpack module

### PR DESCRIPTION
**Pull request by techhat**
### What does this PR do?

Adds a loader system for caching data. A msgpack module is included.
### What issues does this PR fix or reference?

New feature, yo.
### Tests written?

Nay

### CODE REVIEW

**Comment by thatch45** [comment]
I agree, salt needs more loader instances!!

**Comment by cachedout** [comment]
A unified pluggable system here makes some sense. However, we also have some caching utils already written. Is the plan to swing those over here or to maintain them separately?

**Comment by thatch45** [comment]
good point, we should probably comment in the code that those interface need to be moved over, and preferably have a follow on PR that moves one over.

**Comment by techhat** [comment]
I'm definitely planning to switch Salt Cloud over to it, at the very least. What other utils are you talking about?

**Comment by cachedout** [comment]
@techhat salt.utils.cache is what's coming to mind.

**Comment by thatch45** [comment]
Yes, anything using that could easily be moved over to this

**Comment by cachedout** [comment]
Went ahead and merged this in. Any movement to swing additional utils over can be done in a follow-up.

**Pull request merged**
