### PR TITLE
Assert that the command didn't finish

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
Refs https://github.com/saltstack/salt/pull/60972

### CODE REVIEW

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Review by Ch3LL — COMMENTED** [review]
I see one more use of kill_children in both salt/master.py and salt/minion.py. Do those also need to be updated to call `_handl_signals` as well?

**Review by Ch3LL — APPROVED** [review]

**Review by waynew — APPROVED** [review]
Only one comment, non-blocking

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
