### PR TITLE
return ServerAlias from Apache Virtualhosts

### PR DESCRIPTION
**Pull request by cristigherman**
### What does this PR do?

Extract and display ServerAlias for Virtualhosts

### Previous Behavior
ServerAlias not displayed for any Virtualhosts

### New Behavior
ServerAlias is displayed for any Virtualhosts

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by krionbsd** [comment]
@cristigherman thank you for contribution! Could you please run `pre-commit run -av` and re-commit it. Could you write test case for this change as well?

**Comment by cristigherman** [comment]
when I run git commit with precommit hook I get this error not related with my change:

Running session lint-salt-pre-commit
pip install --progress-bar=off -U setuptools!=50.0.0
pip install --progress-bar=off -r requirements/static/py3.6/linux.txt
pip install --progress-bar=off -r requirements/static/py3.6/lint.txt
pylint --rcfile=.pylintrc --disable=I salt/modules/apache.py
************* Module salt.modules.apache
salt/modules/apache.py:25: [W0611(unused-import), ] Unused six imported from salt.ext

-----------------------------------
Your code has been rated at 9.95/10

Command pylint --rcfile=.pylintrc --disable=I salt/modules/apache.py failed with exit code 4
Session lint-salt-pre-commit failed.

**Comment by krionbsd** [comment]
> when I run git commit with precommit hook I get this error not related with my change:
> 
> Running session lint-salt-pre-commit
> pip install --progress-bar=off -U setuptools!=50.0.0
> pip install --progress-bar=off -r requirements/static/py3.6/linux.txt
> pip install --progress-bar=off -r requirements/static/py3.6/lint.txt
> pylint --rcfile=.pylintrc --disable=I salt/modules/apache.py
> ************* Module salt.modules.apache
> salt/modules/apache.py:25: [W0611(unused-import), ] Unused six imported from salt.ext
> 
> Your code has been rated at 9.95/10
> 
> Command pylint --rcfile=.pylintrc --disable=I salt/modules/apache.py failed with exit code 4
> Session lint-salt-pre-commit failed.

yeah, it happens :( just remove this import from line 25 and re-commit it

**Comment by krionbsd** [comment]
@cristigherman any chance to write a test case for apache module? I might help if it's needed.

**Comment by cristigherman** [comment]
@krionbsd sorry. my experience with python tests is none.

**Comment by krionbsd** [comment]
I checked the existing test case and it seems `ServerAlias` is included in test case for `VirtualHost` configuration, so no additional tests are required for this PR.

**Review by krionbsd — DISMISSED** [review]

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
