### PR TITLE
[RFC] Improve init script: specifically manage salt configurations rather than arbitrary salt processes

### PR DESCRIPTION
**Pull request by plastikos**
### What does this PR do?

Prevents SysV init script from killing non-salt processes.
### What issues does this PR fix or reference?

None
### Previous Behavior

Current SysV init script kills unrelated processes.
### New Behavior

Manage a specific salt minion configuration rather than anything that seems to be a salt minion.
### Tests written?
- [X] Yes, but not working . . . yet.
- [ ] No

Unfortunately SysV init scripts tend to rummage through PIDs filtering for
appropriate processes to manage.  Unfortunately the filters are usually weak
and don't account for similar processes run by other users, PIDs of dead
processes being re-used for completely different executables, etc..  These
weaknesses can result in killing unrelated processes with potentially serious
results.

These improvements to the SysV init script is a complete rewrite with the
following improvements:
- Specifically manage individual salt configurations rather than looking for
  salt minion-like processes.
- Obtain salt minion information from the salt configuration - use the
  information to manage the specifically configured process.
- Drop all of the platform-specific helper functions that allow the
  previously-mentioned weaknesses.
  - Unfortunately this means that the output information may not match the
    specific platform (this could easily be corrected).
- Now can manage multiple salt processes started by different users
  - Unfortunately starts/stops/restarts as a group and is unable to manage
    them both as a group or as individual processes (this could easily be
    corrected)

### CODE REVIEW

**Comment by plastikos** [comment]
Don't merge this yet - I need to investigate a couple things and write an integration test.

**Comment by cachedout** [comment]
Looks good to me so far. Let me know when you're ready to try and get this in.

**Comment by plastikos** [comment]
@cachedout, this is getting close to being ready.  One thing that I could use help with is how to handle the minions that need to be started/stopped/restarted by the integration test.  Unfortunately it doesn't work well with the already-spun-up minion and it's unclear to me the best way to get ``integration.TestDaemon.transplant_configs()`` to create a new config+run-root directory structure just for this.  I have some ideas, but they will require rewrite of ``TestDaemon`` and other classes in ``integration``.

**Comment by plastikos** [comment]
@cachedout, I need to figure out a good way of restarting the test minion for this test as well as testing ``minion.kill`` and ``minion.restart`` commands.

**Comment by plastikos** [comment]
Once this is cleaned up and pulled I'll do the same thing for ``salt-master``, ``salt-syndic`` and ``salt-api``.

**Comment by cachedout** [comment]
@plastikos Sounds good. Please keep me posted.

**Comment by plastikos** [comment]
@cachedout, I have *absolutely* no idea why the integration test is failing on cent7 and ubuntu14.  It works great on my Debian stretch/sid and my CentOS 7.0.  Debug information shows that in the ``jenkins/PR/salt-pr-rs-cent7-n`` test the ``salt-minion`` process does start, it just does not progress far enough to open the ZeroMQ IPC sockets.  The minion debug and logs do not indicate any errors.

I'm puzzled.  How do I go about getting a ``jenkins/PR/salt-pr-rs-cent7-n`` test image?

**Comment by cachedout** [comment]
@jtand is your man for that. @jtand can you please contact @plastikos privately and get him set up with one?

**Comment by jtand** [comment]
@plastikos if this fails again, let me know and I can get you a test VM.

**Comment by plastikos** [comment]
Yes, please!

**Comment by jtand** [comment]
@plastikos Ok, How do you want me to send you the login info?

**Comment by plastikos** [comment]
@jtand, I just sent you an email.

**Comment by cachedout** [comment]
@jtand Thanks very much.

@plastikos Keep me posted. Thanks!

**Comment by plastikos** [comment]
@cachedout ,  I've been sending emails to @jtand.  At this point I am unable to reproduce the failures of the automated testing even in the VM @jtrand provided running the same test.  The failure logged in the automated testing is quite odd and indicates that the started ``salt-minion`` is blocked somewhere in start up.  @jtrand is looking into some things and I'm picking at some things too.

The overall status is that I'm stumped for the moment and call shenanigans on the automated testing.  Yes, that's my _technical_ diagnosis.

**Comment by plastikos** [comment]
@cachedout, I don't think that the VM is running (all of) the code from my branch - although I'm not certain what it's running.  I point out the line in the ``salt-pr-rs-cent7-n`` log where the ``salt-minion`` log is dumped:

    STDERR:LOG_FILE:
    STDERR:+ tail -n 20 /tmp/salt-testdaemon-6gFOVm/minion/var/log/salt/minion
    STDERR:2016-04-14 00:01:00,533 [salt.utils.verify][WARNING ][18239] Insecure logging configuration detected! Sensitive data may be logged.
    STDERR:2016-04-14 00:01:00,533 [salt.cli.daemons ][INFO    ][18239] Setting up the Salt Minion "minion"
    STDERR:2016-04-14 00:01:00,657 [salt.cli.daemons                         ][INFO    ][18239] The salt minion is shut down
    STDERR:2016-04-14 00:01:00,659 [salt.cli.daemons                         ][INFO    ][18245] The salt minion is shut down
    STDERR:2016-04-14 00:01:00,660 [salt.utils.process                       ][DEBUG   ][18247] Created pidfile: /tmp/salt-testdaemon-6gFOVm/minion/var/run/salt-minion.pid
    STDERR:2016-04-14 00:01:00,660 [salt.config                              ][DEBUG   ][18247] Reading configuration from /tmp/salt-testdaemon-6gFOVm/minion/etc/salt/minion

Notice the last line: ``Reading configuration . . .``.  There is only one location in the code that has that - especially when narrowed to the ``salt.config`` module: ``_read_conf_file()``.  I changed that log statement to be the following:

    log.debug('TLH: Reading configuration from {0}'.format(path))

Notice the ``TLH:`` prefix?  This change was made in d84011c825ab86ca3892cec2f4c7e79dc71adc37 which the test output shows *everywhere* for being checked out, yet somehow the debug output is missing the ``TLH:``.

Clearly the tests are running a portion of my code from my ``improvement-init_script`` branch, but this particular log statement just doesn't match up.

I'm puzzled.

**Comment by plastikos** [comment]
@cachedout, I think I know what's going on.  I might have a fix . . ..

**Comment by plastikos** [comment]
@cachedout, I fixed it.  It looks like the test suite adds ``/testing`` to ``sys.path``, but it is not added to the environment in ``PYTHONPATH``.  This means that anything that fork+execs a python process is suspect and ends up using installed Salt modules rather than Salt modules from the test source tree.

I'm kicking myself that it took me this long to figure out.

I'll see about cleaning this up, ripping out the breadcrumbs and unnecessary debugging, quash some commits and get it re-submitted.

**Comment by plastikos** [comment]
@cachedout, how many places are subprocesses created that don't have ``PYTHONPATH`` specifically set and might run incorrect code?

   * ``test/jenkins.py`` Lines 22-44
   * ``salttesting/helpers.py:ensure_in_syspath()``

I think the above should be changed to add ``os.putenv('PYTHONPATH', ':'.join(sys.path))``

Thoughts?

**Comment by cachedout** [comment]
@plastikos I'm fine with those changes if @s0undt3ch is.

**Pull request closed without merging**
