### PR TITLE
[GH Actions] Store generated documentation as build artifacts

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title

----
image

### CODE REVIEW

**Review by bryceml — APPROVED** [review]

**Comment by bryceml** [comment]
It looks like only the html docs got archived

**Comment by bryceml** [comment]
re-run full pr-ubuntu1804-py3-pytest

**Comment by bryceml** [comment]
re-run full pr-macosxmojave-py3-pytest

**Comment by s0undt3ch** [comment]
Man pages are only built on `push`(merging or pushing to a branch or when we tag) or when changes are made to `doc/`

**Pull request merged**
