### PR TITLE
Multiple bugfixes for localemod 

### PR DESCRIPTION
**Pull request by isbm**
### What does this PR do?

- Bugfixes SLE15 locale getter/setter
- Rewrites some functions in more reliable way
- Adds unit tests for locale get/set

### What issues does this PR fix or reference?

Locale set/get was not working on SUSE Linux Enterprise 15 Beta.

### Tests written?

Yes

### CODE REVIEW

**Comment by rallytime** [comment]
Hi @isbm - the following test failure is related to this change: `
unit.modules.test_localemod.LocalemodTestCase.test_set_locale_with_no_systemd_debian`
https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/15950/

Can you take a look?

**Comment by isbm** [comment]
@rallytime fixd!

**Comment by rallytime** [comment]
We have cut the `oxygen.rc1` branch so we can start hardening and testing. I will move this PR to the new branch once the test run that is already going is complete.

**Comment by isbm** [comment]
@rallytime oops, forgotten lint. Now it is fixed. The other tests are failing, but seems unrelated to this PR. Thanks!

**Comment by rallytime** [comment]
@isbm Thanks for fixing the lint. And yes, those other failures are unrelated to your PR. :)

**Review by terminalmage — APPROVED** [review]

**Pull request merged**
