### PR TITLE
Add zookeeper managing module and state

### PR DESCRIPTION
**Pull request by gtmanfred**
### What does this PR do?
Adds support for putting data in zookeeper

### What issues does this PR fix or reference?

https://github.com/saltstack/zh/issues/983

### Tests written?

Not yet

### CODE REVIEW

**Comment by gtmanfred** [comment]
Opening this to get feedback.  I am still working on the integration tests.

**Comment by gtmanfred** [comment]
Go Go Jenkins

**Comment by gtmanfred** [comment]
Go Go Jenkins!

**Review by cachedout — APPROVED** [review]
This is very well done, @gtmanfred

**Pull request merged**
