### PR TITLE
Backport #21624 to 2015.2

### PR DESCRIPTION
**Pull request by isbm**

### CODE REVIEW

**Comment by isbm** [comment]
@jfindlay I am not entirely sure why Ubuntu is crying on #21716 though...

**Comment by jfindlay** [comment]
@isbm, it's likely an internal test failure.  Since you've resubmitted this here against 2015.2, do you mind if we close the other pull request as this will be merged into develop anyway?  Thanks.

**Comment by isbm** [comment]
@jfindlay Sure, you're the write-boss here! :)

**Comment by jfindlay** [comment]
@isbm, thank you.

**Comment by jfindlay** [comment]
@isbm, can you get the [lint errors](https://jenkins.saltstack.com/job/salt-pr-lint-n/3114/violations/file/salt/modules/localemod.py/)?  Thanks.

**Comment by thatch45** [comment]
These lint errors look like it is not a clean backport

**Comment by isbm** [comment]
@jfindlay Lint issues hopefully were fixed for now :)

**Comment by jfindlay** [comment]
Looks good, thanks @isbm.

**Pull request merged**
