### PR TITLE
[develop] linux_distribution_deprecated

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Updating references calling linux_distribution function to use distro intead of platform beginning with Python 3.7.0.  If the distro library is not installed, provide a warning for grains and dummy values in the case of grains and salt --versions-report.

### What issues does this PR fix or reference?
#50792 

### Tests written?
Not yet.

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by terminalmage — APPROVED** [review]

**Comment by terminalmage** [comment]
One lint failure.

**Comment by cachedout** [comment]
Grains test failure: https://jenkinsci.saltstack.com/job/pr-kitchen-ubuntu1604-py2/job/PR-50822/2/testReport/junit/integration.grains.test_custom/TestGrainsCore/test_grains_passed_to_custom_grain/

**Comment by garethgreenaway** [comment]
Failure seems unrelated to the changes, the previous run ran the test fine and the change between the two builds were lint related.

**Comment by bdrung** [comment]
I don't like this pull request, because it makes the code longer, harder to read, and requires the distro module for Python 3.7. I created pull request #51541 instead that just silences the Python warning for Python 3.7.

**Pull request merged**
