### PR TITLE
Restrict permission on accumulator files.

### PR DESCRIPTION
**Pull request by myinitialsarepm**
### What does this PR do?

This commit alters the _persist_accumulators function to explicitly set
the mode of the created file so that only the user that salt is running
as (or root) can access it.

### What issues does this PR fix or reference?
Currently when accumulators are being persisted the files are written
out using the default permission as specified by the umask. This
ususally means they are world-readable. This is a potential security
hole as the file that is being managed and accumulates said accumulators
may not be world readable.

### Previous Behavior
Accumulator files would be world readable.

### New Behavior
Accumulator files are only readable by the user salt is running as.

### Tests written?

No

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by cachedout — APPROVED** [review]

**Comment by cachedout** [comment]
@myinitialsarepm We have some test failures here.

**Comment by rallytime** [comment]
re-run py

**Comment by rallytime** [comment]
Hi @myinitialsarepm - This change is causing the following tests to fail:

- integration.states.test_file.FileTest.test_issue_11003_immutable_lazy_proxy_sum
- integration.states.test_file.FileTest.test_issue_8343_accumulated_require_in

https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/22234/

Can you take a look?

**Comment by rallytime** [comment]
Hi @myinitialsarepm - Did you get a chance to come back to this? We'd like to get this in, but the test failures need to be addressed first.

**Comment by rallytime** [comment]
Hi @myinitialsarepm - Since we haven't heard back here for a while, I am going to close this. We would be happy to reopen this PR when you're ready to look into those test failures and fix them up. Or feel free to open a new PR. Thanks!

**Pull request closed without merging**
