### PR TITLE
Port 50890

### PR DESCRIPTION
**Pull request by salty-blue-mango**
### What does this PR do?
Port of #50890 to master

### What issues does this PR fix or reference?
n/a

### Tests written?
No

### Commits signed with GPG?
No

### CODE REVIEW

**Review by dwoz — CHANGES_REQUESTED** [review]
@Nate-Watts It looks like these test failures are related. Please have a look.

**Review by DmitryKuzmenko — CHANGES_REQUESTED** [review]
Since `IPCMessageServer` is inherited from `IPCServer` that's `__init__` interface is changed, please update the `IPCMessageServer`'s usage example in the docstring.
Also `salt.transport.client.AsyncPullChannel.factory` is affected and not updated.

**Comment by DmitryKuzmenko** [comment]
Could you please resolve the merge conflicts and run the pre-commit script on your code to re-format it with `isort` and `black` we're using now.
```
pip install pre-commit
pre-commit install
FILES="$(git show --pretty="" --name-only master..HEAD)"
pre-commit run isort $FILES
pre-commit run black $FILES
```
next time you'll commit it will be ran automatically.

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
