### PR TITLE
salt-cloud: fix ipv6-only virtual machines

### PR DESCRIPTION
**Pull request by idonin**
### What does this PR do?

If **host** is IPv6 addr, add brackets around **host** in **scp_file** and **sftp_file** functions; Fix IPv6 in **wait_for_port** function
### What issues does this PR fix or reference?

One moar bugfix like https://github.com/saltstack/salt/pull/31120
### Previous Behavior

Can't upload files to created VM
### New Behavior

Can upload files to created VM
### Tests written?

No
### Disclaimer

Tested with dual-stack and ipv6-only hosts. Can't test with non-public IPv4 addresses, because i didn't have that cloud provider

### CODE REVIEW

**Comment by rallytime** [comment]
Thank you for submitting this @idonin. It looks like there are some [pylint errors](http://166.78.178.63:8080/job/PR/job/salt-pr-lint-n/1368/violations/file/salt/utils/cloud.py/) that need to be fixed.

Also, @gtmanfred a review of this change would be good, when you get a moment.

**Comment by idonin** [comment]
@rallytime all tests pass now. Whats next?

**Comment by gtmanfred** [comment]
I can review this later today when I get back, I am at the Openstack summit
this week.

**Comment by rallytime** [comment]
@idonin Thanks very much for cleaning that up. We'll get this in pending review. :)

**Comment by gtmanfred** [comment]
Sorry, forgot about this, looking now.

**Comment by gtmanfred** [comment]
I would like to instead of duplicating the if inet6 check everywhere, to move that to be in the deploy_script function which calls ssh_file and wait_for_port.  Then we just have one check, and you can have

```
if socket.inet_pton(socket.AF_INET6, host):
    sock = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
    kwargs['hostname'] = '[{0}]'.format(kwargs['hostname'])
else:
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
```

**Comment by gtmanfred** [comment]
@idonin can you take a look at my last comment?

Thanks!

**Comment by idonin** [comment]
Sorry for late reply. Rewriting _kwargs['hostname']_ it's a bad idea. This will broke _rsync_ fallback in _scp_file_ function.
Unfortunately, _sftp_, _ssh_, _rsync_ and _scp_ handles different with hostname in brackets.

**Comment by gtmanfred** [comment]
ahh ok, then that sounds good.

@cachedout this is good to merge then.

**Pull request merged**
