### PR TITLE
Private key fix

### PR DESCRIPTION
**Pull request by freimer**
This is required for Windows instances, as it uses the private_key in wait_for_instance to get the Administrator password from AWS.  I haven't gotten Windows salting to work yet, but at least it doesn't bomb out now...

### CODE REVIEW

**Comment by techhat** [comment]
Looks good to me, thanks @freimer!

**Comment by jfindlay** [comment]
@freimer, it looks like there's a [lint error](https://jenkins.saltstack.com/job/salt-pr-lint-n/2419/violations/file/salt/cloud/clouds/ec2.py/).  You need:

```diff
- from Crypto.Hash import SHA # pylint: disable=E0611
+ from Crypto.Hash import SHA # pylint: disable=E0611,W0611
```

Thanks.

**Comment by jfindlay** [comment]
@techhat, @rallytime, does this need to go into 2014.7 as well?

**Comment by techhat** [comment]
@jfindlay, if it can, yes.

**Comment by freimer** [comment]
I'm checking to see if it is applicable.

**Comment by freimer** [comment]
@techhat @jfindlay , it does not look like it is applicable.  I did a compare from 2014.7 to my change, which was based off of 2015.2, and the whole if stanza this is required in was added between (@@ -1776,6 +1919,26 @@ def wait_for_instance
So I think that 2015.2 is the earliest this can be back-ported to without other "major" work.

**Comment by jfindlay** [comment]
@freimer, awesome, thanks.

**Comment by freimer** [comment]
Glad to help.  Now just hope the auto-build works out ;-)

**Pull request merged**
