### PR TITLE
Log when the yaml filter outputs trailing ellipsis.

### PR DESCRIPTION
**Pull request by wt**

### CODE REVIEW

**Comment by jfindlay** [comment]
fixes #20807

**Comment by wt** [comment]
No. This is the logging. The actual change will need to remove the '\n...\n'. I didn't want to make that change inside the stable series as it's technically backward incompatible since someone could actually be using the side effect. This change just logs that the behavior will change. The actually fix will need to be commited to either 2015.2 or develop (depending on what you want for timing). My preference is to do it for 2015.2.

I would have already done the change for 2015.2 except that 2015.2 has not had the 2014.7 branch fully merged and there are some conflicts that I am not comfortable resolving.

**Comment by jfindlay** [comment]
@wt, https://github.com/saltstack/salt/pull/20944.

**Comment by cachedout** [comment]
Could we please add a target release for this deprecation and include that info in the error message? I am fine with it being targeted for Boron.

**Comment by wt** [comment]
Is Boron 2015.2? I don't know where to look up the code names for upcoming releases.

**Comment by rallytime** [comment]
@wt Boron will be two feature releases after 2015.2.0. The 2015.2 feature release was code-named Lithium, but as soon as 2015.2 was branched from develop and given a numerical identifier, the code-named stopped being used. For a point of reference, we're basing our code names on the periodic table, and the next targeted feature branch is Beryllium. (Beryllium comes after Lithium, then Boron.)

**Comment by wt** [comment]
Thanks for the great explanation. It would be great to have a place to look and see the release code name/version number mapping. Something like https://wiki.ubuntu.com/Releases would be wonderful.

I have some more comments about this that I'll post to the mailing list to get a wider discussion.

**Comment by rallytime** [comment]
@wt That's a great idea. If nothing else, we should at least have this documented on a basic level. Care to open a new issue with a request about this? Might be good to see what salt-users has to say first, but we don't want to lose that idea.

**Comment by wt** [comment]
I just created a page in the salt wiki for this:
https://github.com/saltstack/salt/wiki/Releases

Please check the "Release Management" section and make sure it makes sense.

**Pull request merged**
