### PR TITLE
Check to see if IPTables rule exists before appending or inserting.  RHEL6 Family of servers

### LINKED ISSUE #17217: salt.state.iptables.append and salt.state.iptables.insert keeps inserting duplicate rules with each state run
I have seen issues regarding this earlier and there has been suggested fixes. I'm still having this problem because of which using these state functions to append or insert an iptable rule seems useless. 

Here's relevant information:

Master:
```
[root@nitin-saltmaster ~]# salt --versions-report
           Salt: 2014.7.0rc6-2571-g0d6e33a
         Python: 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
[root@nitin-saltmaster ~]# 
```

Minion:
```
[root@nitin-saltmaster ~]# salt '*jenkins' test.versions_report
nitin-jenkins:
               Salt: 2014.1.13
             Python: 2.6.6 (r266:84292, Sep  4 2013, 07:46:00)
             Jinja2: 2.2.1
           M2Crypto: 0.20.2
     msgpack-python: 0.1.13
       msgpack-pure: Not Installed
           pycrypto: 2.0.1
             PyYAML: 3.10
              PyZMQ: 14.3.1
                ZMQ: 3.2.4
[root@nitin-saltmaster ~]# 
```

Both my master and minion are RHEL 6.5

### PR DESCRIPTION
**Pull request by cingeyedog**
This commit fixes #17217

### CODE REVIEW

**Comment by rallytime** [comment]
@cingeyedog It looks like there is a [related test](https://jenkins.saltstack.com/job/salt-pr-rs-ubuntu14.04-n/6498/) failing. Can you take a look at that? (Don't worry about the grains test failures, those are unrelated.)

**Comment by cingeyedog** [comment]
Changed the return code if the iptables rule exists.

**Comment by jfindlay** [comment]
@cingeyedog, will you look at updating these two tests?  Thanks.

https://jenkins.saltstack.com/job/salt-pr-rs-ubuntu14.04-n/6596/testReport/junit/unit.modules.iptables_test/IptablesTestCase/test_append/
https://jenkins.saltstack.com/job/salt-pr-rs-ubuntu14.04-n/6596/testReport/junit/unit.modules.iptables_test/IptablesTestCase/test_insert/

**Comment by driskell** [comment]
Test failures are because the insert/append test try to add:

```
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
```

On all my servers this is already preinstalled from the start, so this PR would cause it to fail I guess since it would refuse to duplicate it. Just needs the tests modifying to use something more unique that isn't expected to be there already?

**Pull request merged**
