### PR TITLE
Fix for mysql pillar's ignore_null

### PR DESCRIPTION
**Pull request by kaithar**
PR #14924 from @jond64 introduced logic to ignore null values but it appears the logic is slightly off.
I'm changing the code to compare against None rather than basing off anything that evaluates true.  As was, fields set to false, 0 or an empty string would be ignored meaning you couldn't turn off any fields from an override.

### CODE REVIEW

**Comment by kaithar** [comment]
Ping for @rallytime ... backport suitable?

**Comment by rallytime** [comment]
@kaithar Is the bug you were fixing happening on the 2014.7 branch? Then, yeah, this is likely suitable for backporting. I'll take a look.

If, in the future, you're fixing a bug that happens on a branch, such as 2014.7, then feel free to make the fix there. Then the fix will be merged forward into all of the new branches. And, if you haven't already seen it, you can check out a better explanation of this here: http://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch

**Comment by rallytime** [comment]
@kaithar How does that PR look? There was a small merge conflict, but I think that looks correct.

**Comment by kaithar** [comment]
@rallytime I opened the PR against develop mainly because it feels more like a logic fix than an implementation fix heh.

#20432 isn't going to work right, it looks like the `ignore null` option wasn't in that one.  My client took a while to work it out, but it looks like 2015.2 would be the only candidate.

**Comment by rallytime** [comment]
Ah! Ok. It will probably be a better merge then. I'll open a new PR against 2015.2. Thanks for letting me know!

**Comment by rallytime** [comment]
Alright, that one merged like a charm! We're all set now. :)

**Comment by kaithar** [comment]
@rallytime purrfic :+1:

**Pull request merged**
