### PR TITLE
Reworked modules.restartcheck: optimize code, generator, timeout

### PR DESCRIPTION
**Pull request by homolkad**
### What does this PR do?
Reworked restart check: used generator for _detete_files, added timeout in minutes for checking loops in restartcheck, added list dirs and using regex for valid deleted file. Optimize code.

### What issues does this PR fix or reference?
None

### New Behavior
Add timeout to restartcheck, default 5 min.

### Tests written?
Yes

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by garethgreenaway** [comment]
@homolkad Great work.  Are there existing tests for this module?

**Comment by homolkad** [comment]
@garethgreenaway I think, the tests never existed for this module.

**Comment by garethgreenaway** [comment]
@homolkad Looks like you're right.  Including some tests to ensure the module is functioning as expected would be great.  Let us know if you need help getting going with adding them.

**Comment by homolkad** [comment]
@garethgreenaway Ok, I am going to write the tests.

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
