### PR TITLE
2018.3: bug: executors lazyloader is missing functions and proxy args

### PR DESCRIPTION
**Pull request by mattp-**
### What does this PR do?
these are needed for this functionality to work

### What issues does this PR fix or reference?
n/a

### Tests written?
should be covered by existing tests

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by mattp-** [comment]
@waynew clean now. not sure what the ubuntu fail is from, but its unrelated to PR

**Comment by waynew** [comment]
🤦‍♂ Well. We fixed one of the msgpack failures, but it turns out there are several more that we'll have to address before getting this fix in:

```
ag "msgpack.*encoding"
tests/integration/__init__.py
156:        unpacker = msgpack.Unpacker(encoding='utf-8')

tests/integration/files/log_handlers/runtests_log_handler.py
98:            sock.sendall(msgpack.dumps(record.__dict__, encoding='utf-8'))

salt/transport/ipc.py
171:        unpacker = msgpack.Unpacker(encoding=encoding)
256:        self.unpacker = msgpack.Unpacker(encoding=encoding)

salt/utils/cloud.py
95:MSGPACK_ENCODING = 'utf-8'
2513:            index = salt.utils.data.decode(msgpack.load(fh_, encoding=MSGPACK_ENCODING))
2530:        msgpack.dump(index, fh_, encoding=MSGPACK_ENCODING)
2547:            index = salt.utils.data.decode(msgpack.load(fh_, encoding=MSGPACK_ENCODING))
2556:        msgpack.dump(index, fh_, encoding=MSGPACK_ENCODING)
2614:        msgpack.dump(data, fh_, encoding=MSGPACK_ENCODING)
2646:        cache_data = salt.utils.data.decode(msgpack.load(fh_, encoding=MSGPACK_ENCODING))
2651:        msgpack.dump(cache_data, fh_, encoding=MSGPACK_ENCODING)
2725:                    minions[driver][prov][minion_id] = salt.utils.data.decode(msgpack.load(fh_, encoding=MSGPACK_ENCODING))
2902:            msgpack.dump(nodes[node], fh_, encoding=MSGPACK_ENCODING)
2928:        msgpack.dump(node, fh_, encoding=MSGPACK_ENCODING)
3003:            cache_data = salt.utils.data.decode(msgpack.load(fh_, encoding=MSGPACK_ENCODING))

salt/utils/cache.py
142:            cache = salt.utils.data.decode(msgpack.load(fp_, encoding=__salt_system_encoding__))
```

(that, of course, is assuming that all of the msgpack and encoding calls are on the same line 😛 )

**Comment by waynew** [comment]
@mattp- would you mind rebasing this on master?

**Comment by sagetherage** [comment]
@mattp- can you rebase this on master?

**Comment by waynew** [comment]
@mattp- what help do you need here?

**Comment by dwoz** [comment]
Closing due to lack of activity. Anyone should feel free to re-open or create a new PR if they want to see this through to the end.

**Pull request closed without merging**
