### PR TITLE
Feature :: provide state.show_state_usage call

### PR DESCRIPTION
**Pull request by msiebeneicher**
### What does this PR do?

Implement `state.show_state_usage` call
### What issues does this PR fix or reference?

https://github.com/saltstack/salt/issues/36688
### New Behavior

``` sh
salt -c etc/salt '*' state.show_state_usage                                                                  

minion-882m.local:
    ----------
    base:
        ----------
        count_all:
            10
        count_unused:
            2
        count_used:
            8
        unused:
            - state.app.1
            - state.app.5
        used:
            - state.app.2
            - state.app.3
            - state.app.4
            - state.app.6
            - state.app.7
            - state.app.8
            - state.app.9
            - state.app.10
```
### Tests written?

Yes

### CODE REVIEW

**Comment by cachedout** [comment]
This looks really nice. I'd like @thatch45 to also do a review here before we get this in but I think it will be an excellent addition. Thanks, @msiebeneicher

**Comment by thatch45** [comment]
Wow, test written, impeccable clean code and a completely useful feature. This gets a 10 on the merge-ability scale.

**Review by thatch45 — APPROVED** [review]

**Comment by andygrunwald** [comment]
@cachedout Any blocker for merge? Can we do / adjust / help something?

**Comment by cachedout** [comment]
@andygrunwald Nope. This is perfect!

**Comment by msiebeneicher** [comment]
@cachedout & @thatch45 : thx - it was a pleasure ;)

**Pull request merged**
