### PR TITLE
Fix hetzner cloud create method attachments (#59872)

### LINKED ISSUE #59872: [BUG] hetzner cloud driver create method does not correctly handle volume and network attachments
**Description**
The create method of the hetzner cloud driver takes networks and volumes in its combined data. This is passed to the create function of the hetzner cloud api. Before it is passed, there is a check if the given volumes or networks are existing in the hetzner cloud project. The corresponding code lines are the following (https://github.com/saltstack/salt/blob/master/salt/cloud/clouds/hetzner.py#L298):

```python
# Get the volumes
    volumes = vm_.get("volumes", None)
    if volumes:
        volumes = [vol for vol in client.volumes.get_all() if vol in volumes]

    # Get the networks
    networks = vm_.get("networks", None)
    if networks:
        networks = [vol for vol in client.networks.get_all() if vol in networks]

    # Create the machine
    response = client.servers.create(
        name=name,
        server_type=server_type,
        image=image,
        ssh_keys=ssh_keys,
        volumes=volumes,
        networks=networks,
        location=location,
        user_data=vm_.get("user_data", None),
        labels=vm_.get("labels", None),
        datacenter=datacenter,
        automount=vm_.get("automount", None),
    )
``` 

This can't work, because the functions `client.volumes.get_all()` and `client.networks.get_all()` return a list of objects. You can't pass in object references in profiles/providers/maps/grains etc., so the `vol in volumes` or `vol in networks` will never return `True`. `networks` and `volumes` will always be empty.

This means you are not able to pass in networks or volumes at creation time, which should visibly be possible.

### PR DESCRIPTION
**Pull request by dithmer**
### What does this PR do?
Fix hetzner cloud create method attachments 

### What issues does this PR fix or reference?
Fixes: #59872 

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by dithmer** [comment]
@krionbsd 

I've just added tests to go sure the correct mechanic of adding networks and volumes while creating a machine is being called. Anything else I can do here?

**Comment by sagetherage** [comment]
@dithmer looks like your PR needs a rebase with the `master` branch

**Comment by whytewolf** [comment]
@dithmer can you update this PR as well. it looks to be out of date with the master branch to the point i can't update the merge in github.

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
