### PR TITLE
enable virtual package names in pyobjects renderer

### PR DESCRIPTION
**Pull request by grischa**
Fixes Issue https://github.com/saltstack/salt/issues/23458 for me

### CODE REVIEW

**Comment by grischa** [comment]
It's a silly issue and a trivial fix. Would be great if this could be back ported in a way that it enters packaged versions ASAP.

**Comment by jfindlay** [comment]
@grischa, we prefer fixes to be merged into the oldest supported release, since release branches are regularly merged forward, see https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.  You can either resubmit this against 2015.5 or wait for us to backport it.  The next release will come out in about 3 weeks.

**Comment by jfindlay** [comment]
@grischa, also, thanks for fixing this and would you mind looking at the failed [unit tests](https://jenkins.saltstack.com/job/salt-pr-rs-ubuntu14.04-n/6150/)?  Thanks.

**Comment by grischa** [comment]
I had a look at the failing tests, @jfindlay.
The unit tests failed because those virtual packages were disabled when no architecture is set. Now those tests set an architecture and all packages are available as expected.
However, now there is an integration test failure that I have no idea about. It passes on my test set up, only fails in Jenkins.

**Comment by jfindlay** [comment]
The CentOS 7 tests are totally wacked.  I'm not sure what that test failure on ubuntu is.  It looks unrelated to me, thanks.

**Comment by grischa** [comment]
Great, thanks!

**Pull request merged**
