### PR TITLE
Rename docker execution module to avoid shadowing in the loader

### PR DESCRIPTION
**Pull request by terminalmage**
With the merging of #39996, salt/modules/docker.py now imports
salt.utils.docker. However, our loader appends the module dir (in
this case salt/modules/) to sys.path temporarily for the length of the
loading process. So, as the docker execution module tries to import
salt.utils.docker, when salt.utils.docker attempts to do an "import
docker", and docker-py is *not* installed, this results in
salt/modules/docker.py (the docker execution module) being loaded in its
place, which results in tracebacks in the minion log.

Renaming the docker execution module keeps this import shadowing from
occurring. Note that we don't need to do this for the placeholder
salt/states/docker.py as it does not import salt.utils.docker.

@rallytime, @utahdave: We may need to make sure that the
salt.modules.docker.html is removed from docs.saltstack.com, I recall something
similar needing to be done when we moved dockerio.py to salt-contrib. Its docs
page remained on our website. This would only need to be done for the develop
branch docs, since that is the branch into which #39996 was merged.

### CODE REVIEW

**Comment by rallytime** [comment]
@terminalmage Looks like some test imports need to be adjusted here.

**Comment by terminalmage** [comment]
D'oh, I had the needed changes unstaged, I didn't commit them. Derp. Pushed an update, should pass now.

**Comment by cachedout** [comment]
@terminalmage Still not passing I'm afraid, plus a lint failure.

**Comment by terminalmage** [comment]
Fixed.

**Review by cachedout — APPROVED** [review]

**Pull request merged**
