### PR TITLE
fix difference between tag output of rabbitmq 2 and 3

### PR DESCRIPTION
**Pull request by s-schweer**
### What does this PR do?

fix difference between tag output of rabbitmq 2 and 3
### Tests written?

NO

### CODE REVIEW

**Comment by jtand** [comment]
@s-schweer This caused some [test failures](https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/2155/). Can you look at these?

**Comment by s-schweer** [comment]
Hi, i fixed the test failures, can take some time until the update appears, github is slow

**Comment by jtand** [comment]
@s-schweer Excellent, thank you!

**Comment by cachedout** [comment]
@s-schweer This needs to be rebased. I removed those tests because they're just pointless.

**Comment by s-schweer** [comment]
@cachedout OK, i'll rebase this tomorrow at work, if i'll find some time i'll try to right some better tests

Von meinem CyanogenMod-Telefon gesendet

Am 23.05.2016 10:58 nachm. schrieb Mike Place <notifications@github.com>:

@s-schweer This needs to be rebased. I removed those tests because they're just pointless.

**Comment by s-schweer** [comment]
@cachedout i rebased my branch

**Comment by cachedout** [comment]
Thanks, @s-schweer 

Just some minor lint issues to clean up and then I will merge this. Thanks!

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/2081/violations/file/tests/unit/modules/rabbitmq_test.py/

**Comment by s-schweer** [comment]
@cachedout LINT errors should be fixed now

**Comment by cachedout** [comment]
@s-schweer Great! Thank you very much.

**Pull request merged**
