### PR TITLE
[master] Fix to thin.generate runner function

### LINKED ISSUE #54317: Generating thin fails with PermissionError
### Description of Issue

Running `salt-run thin.generate overwrite=1` on openSUSE e.g. in `/root` directory fails with `PermissionError: [Errno 13] Permission denied: '/root'`.

In `thin.py` is a `os.chdir(start_dir)`, where `start_dir` is the the current directory. This is not possible for the user `salt` and that's why the error is happening.

### Setup

You can easily reproduce this with a Salt that is not running as root. Switching to a directory where the user salt is configured to use has no permissions should also work. Now run the command.

### Steps to Reproduce Issue

1. Set the user salt is using to `salt` for example.
2. `cd /root`
3. `salt-run thin.generate overwrite=1`
4. Command fails with PermissionError.

### Versions Report

```
salt --versions-report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr 30 2019, 13:27:23) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.12.14-197.15-default
         system: Linux
        version: Not Installed
```

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Verify that the user running thin.generate has read and execute permissions before attempting to chdir back to start_dir.

### What issues does this PR fix or reference?
fixes #54317 

### Previous Behavior
If Salt was configured to run as a non-root user and the thin.generate runner was executed in a directory that the user did not have access to an exception would be triggered.

### New Behavior
Check that the user has read and execute permissions before attempting the chdir.

### Tests written?
**[NOTICE] Bug fixes or features added to Salt require tests.**
Please review the [test documentation](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html) for details on how to implement tests into Salt's test suite.
Yes

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by DmitryKuzmenko** [comment]
@garethgreenaway The ci failures are related.

**Review by brejoc — DISMISSED** [review]
👍

**Comment by waynew** [comment]
@garethgreenaway looks like a wild merge conflict appeared!

**Review by waynew — DISMISSED** [review]
Looks like a weird test issue:

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/.nox/runtests-parametrized-3-coverage-true-crypto-none-transport-zeromq/lib/python3.5/site-packages/mock/mock.py", line 1330, in patched
    return func(*args, **keywargs)
  File "/tmp/kitchen/testing/tests/unit/utils/test_thin.py", line 906, in test_gen_thin_main_content_files_written_py3
    thin.gen_thin("")
  File "/tmp/kitchen/testing/salt/utils/thin.py", line 746, in gen_thin
    if start_dir and os.access(start_dir, os.R_OK) and os.access(start_dir, os.X_OK):
TypeError: access: illegal type for path parameter
```
https://jenkinsci.saltstack.com/job/pr-debian9-py3/job/PR-56610/5/testReport/junit/unit.utils.test_thin/SSHThinTestCase/test_gen_thin_main_content_files_written_py3/

**Pull request merged**
