### PR TITLE
Using .zip archives as self-contained Salt modules

### PR DESCRIPTION
**Pull request by jeremyrosenbaum**
I need a way to distribute Salt modules with their dependencies packaged up and potentially isolated from one another (e.g. module `foo` needs version 1.0 of library `bar`, but module `baz` needs version 2.0 of `bar`).  @sixninetynine gave me the idea of using Python's built-in zip archive import capabilities and it works great.  The code changes involved to allow this are minimal.  This PR is 90% documentation on how to make use of the feature :laughing: 

This should work for any type of extension module that's picked up by the LazyLoader (execution modules, state modules, custom grains, etc.)

I put `versionadded:: 2015.8.0` in the docs for the minion config option, since I figure this is probably a pretty easy backport.  Thanks!

### CODE REVIEW

**Comment by jodv** [comment]
Looks like the static modules merge over the weekend created a merge conflict.  I rebased my changes.

**Comment by jodv** [comment]
Lemme know if it would be better/easier to just open a new PR...

**Comment by thatch45** [comment]
@jodv your rebase still looks great, sorry about the conflict! No need to open a new PR

**Comment by jodv** [comment]
No problem, I was amused that I managed to get a conflict in the roughly 6 lines of actual code I added :)

**Comment by basepi** [comment]
This is awesome! Thanks @jodv!

**Comment by jodv** [comment]
Should I go ahead and submit a PR to backport into 2015.8 or will y'all take care of that?

**Comment by basepi** [comment]
Technically I think this is a new feature, but I don't see the problem with backporting it.

Backport to 2015.8, please.

**Comment by jodv** [comment]
Yeah, I just would like to make use of it ASAP and it should be pretty simple with the commits from before the rebase (unless @thatch45 's changes to allow static modules are also backported).  I had put '2015.8.0' as the `versionadded` in the documentation in a bout of wishful thinking.  Thanks! :D

**Pull request merged**
