### PR TITLE
Add ability to clone from a snapshot to salt-cloud vmware driver

### PR DESCRIPTION
**Pull request by pass-by-value**
### What does this PR do?

Add ability to clone from a snapshot to salt-cloud vmware driver
### What issues does this PR fix or reference?

ZH 926
### New Behavior

Be able to specify a snapshot number for a VM
### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by pass-by-value** [comment]
@nmadhok Could you please review this patch?

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@pass-by-value Please lint this.

**Pull request merged**
