### PR TITLE
SSH State test failures

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
### What does this PR do?
I've updated the assertions are used in the test to provide better diagnostics. Also I've increased SSH tests timeouts because for some reason CentOS 6 tests run much slower than CentOS 7 and other test machines. Currently I'm not sure why I'll try to investigate it deeper in the future.

### What issues does this PR fix or reference?
Fix https://github.com/saltstack/salt-jenkins/issues/805

### New Behavior
Most of the SSHState tests are passing.

### CODE REVIEW

**Comment by DmitryKuzmenko** [comment]
@saltstack/team-core could anybody please review?

**Review by rallytime — APPROVED** [review]

**Comment by DmitryKuzmenko** [comment]
re-run py

**Comment by rallytime** [comment]
@DmitryKuzmenko Now that 2018.3.0 is in the packaging/manual testing phase and this is just a test fix, can you move the base branch to 2018.3 instead of 2018.3.0rc1? Then we can get this merged in.

**Comment by DmitryKuzmenko** [comment]
Ah! Sure, sorry.

**Comment by rallytime** [comment]
re-run py

**Comment by rallytime** [comment]
re-run py2

**Pull request merged**
