### PR TITLE
Improve handling of non-ascii characters in terminal output. (Fixes: #49523)

### PR DESCRIPTION
**Pull request by MTecknology**
### What does this PR do?

Prevents exception when stdout contains non-ascii characters.

### What issues does this PR fix or reference?

- #49523

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by cachedout — APPROVED** [review]

**Review by rallytime — APPROVED** [review]

**Comment by damon-atkins** [comment]
Please read the comments in the original issue. #49523

**Comment by damon-atkins** [comment]
output_encoding param from cmdmod is not passed onto vt

**Comment by damon-atkins** [comment]
cmdmod uses code like:
```
            out = salt.utils.stringutils.to_unicode(
                proc.stdout,
                encoding=output_encoding)
```

**Comment by rallytime** [comment]
@MTecknology So this change caused all of our salt-ssh tests to fail, and we didn't catch it in your PR here because we made some recent updates to the way our tests run on PRs and we didn't account for the `salt.utils.vt` file to affect salt-ssh. (I've fixed that problem today in #50230.)

That being said, we need to pull back this fix. I have been looking at it today and I _think_ I have something that will work, but I am unsure because I haven't been able to reproduce the cloud error you were attempting to fix. I think the only `encode` part we need is that first line you adjusted at the `self.stream_stdout.write`. I'll submit a PR right now, but can you test it and make sure it does what you need it to do?

**Comment by MTecknology** [comment]
Yup, I can test it once I see the PR come through.

**Comment by rallytime** [comment]
@MTecknology Ok, give #50235 a try. It might not be right, since I couldn't test it. But that fixes the salt-ssh test failures. I think it would also fix the cloud problems based on the descriptions, but please give that a try and let me know how it goes.

**Comment by MTecknology** [comment]
@waynew This should not be merged into master because a newer solution is in place.

**Comment by waynew** [comment]
@MTecknology which one/where? Trying to make sure that we've got everything appropriately tracked.

**Comment by MTecknology** [comment]
I'm not sure when ``salt.utils.stringutils.to_str()`` was introduced, but it's superior to my naive ``.decode()`` solution (from this merge).

**Pull request merged**
