### PR TITLE
Re-work timeouts in saltnado

### PR DESCRIPTION
**Pull request by jacksontj**
This is a more complete fix from the issues in #21755

Comes with a re-work of timeouts and batching-- which I think end up being quite a bit nicer :)

### CODE REVIEW

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jacksontj** [comment]
@jfindlay I'm not sure why the last 2 tests are failing, seems like either a jenkins issue or a problem with runners in 2014.7

**Comment by jfindlay** [comment]
@jacksontj, yeah, those are known intermittently failing tests on 2014.7.

**Comment by jacksontj** [comment]
K, so I think these 2 PRs are good for merge then :)

**Comment by jfindlay** [comment]
@jacksontj, definitely, although I'm going to defer to @thatch45 or @cachedout or @whiteinge as I'm a novice in this area.

**Pull request merged**
