### PR TITLE
Rewrite openstack driver to use shade

### LINKED ISSUE #31762: [salt-cloud] openstack driver tries to assign new floating ip when some are available in pool
### Description of Issue/Question

When creating VMs using salt-cloud against an icehouse openstack using the openstack driver, I get a "no more floating ips", it seems to be trying to allocate new floating IPs when some are available to assign.
### Steps to Reproduce Issue

Traceback : 

```
[ERROR   ] There was a profile error: 404 Not Found No more floating ips in pool [u'ext-net'].
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 277, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1418, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1262, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/openstack.py", line 618, in create
    data, vm_ = request_instance(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/openstack.py", line 489, in request_instance
    floating = _assign_floating_ips(vm_, conn, kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/openstack.py", line 819, in _assign_floating_ips
    for idx in [pool.create_floating_ip()]:
  File "/usr/lib/python2.7/dist-packages/libcloud/compute/drivers/openstack.py", line 2336, in create_floating_ip
    data={'pool': self.name})
  File "/usr/lib/python2.7/dist-packages/libcloud/common/openstack.py", line 200, in request
    raw=raw)
  File "/usr/lib/python2.7/dist-packages/libcloud/common/base.py", line 736, in request
    response = responseCls(**kwargs)
  File "/usr/lib/python2.7/dist-packages/libcloud/compute/drivers/openstack.py", line 956, in __init__
    super(OpenStack_1_1_Response, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/libcloud/common/base.py", line 117, in __init__
    raise Exception(self.parse_error())
Exception: 404 Not Found No more floating ips in pool [u'ext-net'].
```
### Versions Report

```
$ salt --versions-report
Salt Version:
           Salt: 2015.8.7

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: 0.21.1
           Mako: 1.0.2
         PyYAML: 3.11
          PyZMQ: 14.4.1
         Python: 2.7.10 (default, Oct 14 2015, 16:09:02)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 1.1.2
       cherrypy: 3.5.0
       dateutil: 2.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.3.4
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: Ubuntu 15.10 wily
        machine: x86_64
        release: 4.2.0-30-generic
         system: Ubuntu 15.10 wily
```

### LINKED ISSUE #37443: salt-cloud and openstack :  "got an unexpected keyword argument 'auth_token' "
### Description of Issue/Question

I try to setup Salt and openstack, using the driver nova. In the cloud.providers.d folder, I created a conf file for my openstack. In it, I set the identity_url, compute_region, user, password, tenant and driver. 

When I try to query openstack with "salt-cloud -Q -l debug" I get : 

> 
Failed to execute 'nova.list_nodes()' while querying for running nodes: __init__() got an unexpected keyword argument 'auth_token', any idea ? 

(detail below)

Just in a case, I'm able to interact with openstack using "nova" command. ( nova images-list, etc,etc ).

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

The content of the file for the provider : ( /etc/salt/providers.d/ovh_openstack.conf )

> 
ovh_openstack:
  minion:
    master: salt.interdom.com
  identity_url: "https://auth.cloud.ovh.net/v2.0"
  compute_region: "GRA1"
  user: "Jjf3XXXXXXXX"
  password: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  tenant: "12821283719237213817123"
  driver: nova

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

> 

#salt-cloud -Q -l debug
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/auth_user.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/auth_user.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/rest_cherry.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/rest_cherry.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: frvmadm01.roger.com
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/ovh-openstack.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/ovh-openstack.conf
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles
[DEBUG   ] Configuration file path: /etc/salt/cloud
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Could not LazyLoad nova.optimize_providers
[DEBUG   ] The 'nova' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad parallels.avail_sizes
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.destroy
[DEBUG   ] Could not LazyLoad saltify.avail_sizes
[DEBUG   ] Could not LazyLoad saltify.avail_images
[DEBUG   ] Could not LazyLoad saltify.avail_locations
[DEBUG   ] LazyLoaded rackspace.reboot
[DEBUG   ] LazyLoaded openstack.list_locations
[DEBUG   ] LazyLoaded rackspace.list_locations
[DEBUG   ] Failed to execute 'nova.list_nodes()' while querying for running nodes: __init__() got an unexpected keyword argument 'auth_token'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 2369, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/nova.py", line 945, in list_nodes
    conn = get_conn()
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/nova.py", line 273, in get_conn
    conn = nova.SaltNova(**kwargs)
  File "/usr/lib/python2.7/site-packages/salt/utils/openstack/nova.py", line 265, in __init__
    self.compute_conn = client.Client(**self.kwargs)
  File "/usr/lib/python2.7/site-packages/novaclient/client.py", line 446, in Client
    return client_class(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'auth_token'
[DEBUG   ] LazyLoaded nested.output`

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
The salt-cloud report : 

> 

# salt-cloud --versions-report
Salt Version:
            Salt: 2016.3.3
 
Dependency Versions:
 Apache Libcloud: 1.3.0
            cffi: 1.3.1
        cherrypy: 3.2.2
        dateutil: Not Installed
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.8
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.6
    mysql-python: Not Installed
       pycparser: 2.14
        pycrypto: 2.6.1
          pygit2: Not Installed
          Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 15.3.0
            RAET: Not Installed
           smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.1.4
 
System Versions:
            dist: centos 7.2.1511 Core
         machine: x86_64
         release: 3.10.0-327.36.3.el7.x86_64
          system: Linux
         version: CentOS Linux 7.2.1511 Core

### LINKED ISSUE #43351: [salt-cloud] nova driver allocates new floating ip instead of taking free available in project pool
### Setup
provider config

```
os-project-provider:
  driver: nova
  insecure: True
  use_keystoneauth: False
  auth_version: 2
  identity_url: https://127.0.0.1:5000/v2.0
  compute_region: RegionOne
  compute_name: nova
  tenant: os-project
  user: os-project-admin
  password: XXXXXXXX
  ssh_key_name: os-project-ssh-key
  ssh_key_file: /etc/salt/pki/os-project-ssh-key.pem
  ssh_connect_timeout: 120
  wait_for_passwd_timeout: 200
  wait_for_passwd_maxtries: 500
```

profile config
```
os-project-ubuntu-16.04-m1-32_16_160:
  provider: os-project-provider
  size: m1.32_16_160
  image: ubuntu-16.04
  ssh_username: ubuntu
  networks:
    - net-id: 9ceae134-30e2-4979-9b88-c56613804abc
  floating_ip:
    auto_assign: True
    pool: floating_net
```
### Steps to Reproduce Issue
Spin up VMs using nova salt-cloud driver

### Versions Report
```
salt-cloud --versions-report                                                                    
Salt Version:
            Salt: 2016.11.7

Dependency Versions:
 Apache Libcloud: 1.5.0
            cffi: 1.10.0
        cherrypy: 8.9.1
        dateutil: 2.4.2
       docker-py: Not Installed
           gitdb: 0.6.4
       gitpython: 1.0.1
           ioflo: Not Installed
          Jinja2: 2.8
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: 1.0.3
    msgpack-pure: Not Installed
  msgpack-python: 0.4.6
    mysql-python: Not Installed
       pycparser: 2.18
        pycrypto: 2.6.1
    pycryptodome: Not Installed
          pygit2: Not Installed
          Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 15.2.0
            RAET: Not Installed
           smmap: 0.9.0
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.1.4

System Versions:
            dist: Ubuntu 16.04 xenial
         machine: x86_64
         release: 4.4.0-87-generic
          system: Linux
         version: Ubuntu 16.04 xenial
```

### LINKED ISSUE #43412: Outdated documentation for Openstack configuration
### Description of Issue/Question

While reading the salt cloud configuration for openstack, it seems that [this](https://docs.saltstack.com/en/latest/topics/cloud/config.html#openstack)  is a bit outdated, and maybe could be merged with [this](https://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.nova.html#module-salt.cloud.clouds.nova), or maybe some reference could be made for this configuration.

### PR DESCRIPTION
**Pull request by gtmanfred**
### What does this PR do?
Adds an openstack driver which uses the `shade` python module

### What issues does this PR fix or reference?
Fixes #31762
Closes #37443
Fixes #43351
Fixes #43412

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by gtmanfred** [comment]
The getting started and the docs in the release notes are still coming, but I wanted to get this in before the code freeze.

**Comment by rallytime** [comment]
@gtmanfred Yay! 🎉 

There is some lint that needs to be addressed and a related test failure:

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/17041/violations/
https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/17256/

**Review by rallytime — APPROVED** [review]
This looks great. Well done.

**Comment by gtmanfred** [comment]
https://github.com/saltstack/salt/issues/44920

**Comment by gtmanfred** [comment]
party hard

**Pull request merged**
