### PR TITLE
Return an event when salt runner has an Salt exception

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Adds the ability for events to fire back to the event bus when non-existing runner functions are called.

### What issues does this PR fix or reference?
#41618 

### Previous Behavior
Previously when running a Salt runner that did not exist, the CLI would return stating that the desired function did not exist but no event was fired to the event bus.

### New Behavior
This change changes the functionality and in the event that an exception is caught when running a salt runner is called an event is fired to the event bus with the information about the failed salt runner.

### Tests written?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by garethgreenaway** [comment]
Go Go Jenkins!

**Review by whiteinge — CHANGES_REQUESTED** [review]
I'm still fairly unfamiliar with our exit codes. How do you feel about adding `"retcode": 254` as well? Looking through other sources it looks like that value is simply hard-coded since it isn't available in our `salt/defaults/exitcodes.py` file. 😕

**Comment by whiteinge** [comment]
@garethgreenaway one other thought: how do you feel about the following change as well? I'm not sure it's very important, I just get annoyed with Salt behavior differs from one place to the next. 😛 

```diff
diff --git a/salt/runner.py b/salt/runner.py
index 3b9b3c4a68..3f8b23abbf 100644
--- a/salt/runner.py
+++ b/salt/runner.py
@@ -179,14 +179,14 @@ class Runner(RunnerClient):
                 async_pub = self._gen_async_pub()
                 self.jid = async_pub['jid']
 
+                fun_args = salt.utils.args.parse_input(
+                        self.opts['arg'],
+                        no_parse=self.opts.get('no_parse', []))
                 verify_fun(self.functions, low['fun'])
                 args, kwargs = salt.minion.load_args_and_kwargs(
                     self.functions[low['fun']],
-                    salt.utils.args.parse_input(
-                        self.opts['arg'],
-                        no_parse=self.opts.get('no_parse', [])),
                     self.opts,
-                )
+                    fun_args)
                 low['arg'] = args
                 low['kwarg'] = kwargs
 
@@ -260,6 +260,7 @@ class Runner(RunnerClient):
                 evt.fire_event({'success': False,
                                 'return':  "{0}".format(exc),
                                 'fun': low['fun'],
+                                'fun_args': fun_args,
                                 'jid': self.jid},
                                tag='salt/run/{0}/ret'.format(self.jid))
                 ret = '{0}'.format(exc)
```

**Comment by garethgreenaway** [comment]
@whiteinge I like both those of ideas.  I'll incorporate them into the PR.

**Review by terminalmage — APPROVED** [review]

**Review by whiteinge — APPROVED** [review]
Awesomes. Thank you!

**Comment by cachedout** [comment]
@garethgreenaway Could you have a look at the test failure please?

**Comment by garethgreenaway** [comment]
@cachedout Yup!  Looks to definitely be related to the change I made.

**Comment by garethgreenaway** [comment]
Go Go Jenkins!

**Comment by garethgreenaway** [comment]
Go Go Jenkins!

**Pull request merged**
