### PR TITLE
Use --json=v2 for listing macOS brew casks

### LINKED ISSUE #24653: Feature Request: Support for homebrew cask
Hey there guys, hope you're doing well :smile: 

I was wondering if you would please consider supporting [homebrew-cask](https://github.com/caskroom/homebrew-cask) in the future?

This allows OS X users to install desktop applications via the CLI.  Ansible contains [support for it](http://docs.ansible.com/homebrew_cask_module.html) and it works rather well, but I'd really like to try Salt instead for automating the build of my Mac :smile: 

Thanks heaps and have a great weekend!
Fotis

### PR DESCRIPTION
**Pull request by cdalvaro**
### What does this PR do?

It simplifies and improves support for listing macOS brew casks.

Since [Homebrew 2.6.0](https://brew.sh/2020/12/01/homebrew-2.6.0/) (Homebrew/brew#8899), all `brew cask` commands have been deprecated in favour of `brew` commands (with `--cask`) when necessary. So now, any cask from official taps can be installed/removed without specifying its corresponding tap.

For example:

```sls
visual-studio-code:
  pkg.installed
```

can be used for installing VS Code instead of using:

```sls
homebrew/cask/visual-studio-code:
  pkg.installed
```

This PR also adds support for listing casks upgrades (`mac_brew.list_upgrades(include_casks=True)`) and getting casks info (`mac_brew.info_installed("cask_name")`)

### Merge requirements satisfied?
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated
- [x] Requires PR homebrew/brew#10540

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

This PR closes #24653

### CODE REVIEW

**Comment by cdalvaro** [comment]
Please @twangboy, tell me if something is wrong with this issue. I created it more than 1 month ago and no one has commented or approved it.

**Comment by cdalvaro** [comment]
Excuse me for adding you to this PR @weswhet, but this PR has been opened for more than one year and nobody has commented on any requesting me changes or approving it.

Could you review it, please?

**Comment by cdalvaro** [comment]
Done! Many thanks @weswhet for reviewing it!

**Review by s0undt3ch — DISMISSED** [review]

**Comment by s0undt3ch** [comment]
This PR needs to be rebased due to conflicts.

Could you take care of it @cdalvaro please?

**Comment by cdalvaro** [comment]
Due to some directory changes for the file `test_mac_brew_pkg.py` I think I have lost some tests.

I'm working on recovering them...

**Comment by cdalvaro** [comment]
I think I have recovered all of them 🤞

**Comment by cdalvaro** [comment]
Done! I think that CI failures are not related with my changes

**Comment by cdalvaro** [comment]
Could this PR be merged for the next salt release, please?

**Comment by cdalvaro** [comment]
I would like to know whether this PR will be merged or not since I each time I have to make a rebase is really painful.

**Comment by cdalvaro** [comment]
1.5 years open

**Comment by cdalvaro** [comment]
Please @Ch3LL, could you review this PR?

**Review by Ch3LL — APPROVED** [review]

**Comment by cdalvaro** [comment]
Thanks @Ch3LL !!

**Pull request merged**
