### PR TITLE
Feature 19608 inline script for cloud profiles

### PR DESCRIPTION
**Pull request by alex-leonhardt**
This is an initial version with inline_script functionality working -- there are still a few things to be tested, however, I feel it'd be better to merge this now and do a bug-fix branch for eventual fixes when required.

TODO: Update documentation
TODO: Write tests (?) where possible

### CODE REVIEW

**Comment by techhat** [comment]
@alex-leonhardt, it looks like there's a couple of lint errors that you'll want to take care of here.

Also, most of the variables in `inline_script_kwargs` look like they're also in `deploy_kwargs`. Is it reasonable to just use the same dict for both?

**Comment by alex-leonhardt** [comment]
Hi,

Sure no probs re linting :) .. Am using pycharm properly the first time so
still getting the hang of it :).

Re the kwargs.. I did think that but didn't know if anyone had reservation
against that, in case it'd need to be extended / changed etc. If it's ok to
reuse deploy_kwargs, or even preferred, then I'll amend it. It just won't
be explicit and 'obvious' what those are really used for anymore.

Alex

**Comment by techhat** [comment]
You make a good point. While you're consolidating, you might want to leave some comments in there to clarify usage for future developers.

I had one other thought, which I forgot to add before. Currently your inline code executes after the bootstrap script. What about allowing separate inline code statements to be executed before, and after the bootstrap? Kind of like `%pre` and `%post` in a kickstart file.

**Comment by alex-leonhardt** [comment]
Yep, that's perfectly doable, though I took it out of the initial scope for
the feature as I wasn't quite sure how easy it was going to be :). I'd
still put it in as a separate thing for now though, just so I don't get it
all mixed up.

I'll do the linting and consolidating and update the PR after some testing
tomorrow / later this week.

Cheers!
Alex

**Comment by thatch45** [comment]
@techhat please merge this when you feel it is ready

**Comment by alex-leonhardt** [comment]
Had a look at the failing tests, they don't seem to be salt-cloud related. Who is meant to update the documentation ?

**Comment by thatch45** [comment]
Yes, these failures are not related, looks good!

**Comment by DanyC97** [comment]
quick heads-up @jacobhammons on the TODO (top), thanks !!

**Pull request merged**
