### PR TITLE
[3007.x] PubChannel on_recv callback must be a coroutine

### PR DESCRIPTION
**Pull request by dwoz**
### What does this PR do?

Make sure on_recv handlers are co-routines. This fixes several errors seen by minions and syndics.

### What issues does this PR fix or reference?
Fixes: #66177 #66237

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### CODE REVIEW

**Comment by merlinz01** [comment]
Looks like a duplicate of PR #66277.

**Comment by markschuh** [comment]
Indeed - the #66335 and #66277 are competitors for the fix. Only one of both can be applied. I'd say this one uses the better approach - but needs a few more changes.

Due to Python >=3.8 and the upgrade to tornado 6.3.3. the usage of native "async / await" in favor of tornado.gen.coroutine is recommended by tornado authors. See https://www.tornadoweb.org/en/branch6.3/gen.html

But as the failing CI checks show the the related change of the ProxyMinion._handle_payload - inherited from Minion class - is missing in this PR.

Additionally I could identify during analysis for #66237 that the `salt-syndic`, when it was patched so it could start - also generates the "await callback(..." errors. In case of the `salt-syndic` the on_recv sets the [Syndic._process_cmd_socket](https://github.com/saltstack/salt/blob/97e9395b7f1ad53c449bf166be33cea01b9f91be/salt/minion.py#L3431) as callback. 
The change into `async` definition of _process_cmd_socket should IMHO be included in this PR as well.

**Comment by dwoz** [comment]
> Looks like a duplicate of PR #66277.

Yes it's quite similar.

- This needs to go into `3007.x` instead of master.
- We should use async/await instead of `tornado.gen.coroutine` as tornado is being deprecated.
- As @markschuh points out, the changes need to be a little more comprehensive and account for sub-classes of Minion as well as any other places the `on_recv` is used.

**Comment by markschuh** [comment]
Sorry for any confusion the ref to #66237 may introduce. The "process_event" of SyndicManager is not the handler used by the on_recv by Syndic. The handler is:  class Syndic / method _process_cmd_socket

The current method naming deserves some refactoring - but this is another topic: 
  class SyndicManager / method process_event   <=>  class MinionManager / method handle_event
  class Syndic / method _process_cmd_socket  <=>  class Minion / method _handle_payload

I don't say, the WIP fix in scope of #66237 are strictly related to here. I'd suggest to not include this here. The specific detail, I detected - but not included in fix work for #66237 - is this:

```
diff --git a/salt/minion.py b/salt/minion.py
index e05d9c7a95..e908a61f55 100644
--- a/salt/minion.py
+++ b/salt/minion.py
@@ -3428,10 +3428,10 @@ class Syndic(Minion):
         self.req_channel = salt.channel.client.ReqChannel.factory(self.opts)
         self.async_req_channel = salt.channel.client.AsyncReqChannel.factory(self.opts)

-    def _process_cmd_socket(self, payload):
+    async def _process_cmd_socket(self, payload):
         if payload is not None and payload["enc"] == "aes":
             log.trace("Handling payload")
-            self._handle_decoded_payload(payload["load"])
+            await self._handle_decoded_payload(payload["load"])
         # If it's not AES, and thus has not been verified, we do nothing.
         # In the future, we could add support for some clearfuncs, but
         # the syndic currently has no need.
```

Note: Sure - the fixes for #66237 are needed to have a working v3007.0 salt-syndic.  This may be the reason you included them temp in this WIP PR. But I have some doubt, the PASS of  "test_syndic,py" is based on real salt-syndic tests. See: #58975. I have no running pytests yet in my lab- so I can't test it yet in more detail.

**Review by s0undt3ch — APPROVED** [review]

**Pull request merged**
