### PR TITLE
default load_template skip_verify to False

### PR DESCRIPTION
**Pull request by wasabi222**
### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Review by mirceaulinic — APPROVED** [review]
Approved - could you please add also a `.. versionchanged:: Nitrogen` in the docstring for this argument, as this code has been included in previous releases?

**Comment by mirceaulinic** [comment]
Also, can you send this please to Nitrogen rather than develop?

**Comment by cachedout** [comment]
I tried to change the base branch but it wasn't clean. We'll need this closed and re-opened against the `nitrogen` branch. Thanks.

**Comment by rallytime** [comment]
It looks like this change was submitted to `nitrogen` in #41532, which I just merged. Since that change will be merged-forward to `develop` in the next couple of days, I'll close this one.

**Pull request closed without merging**
