### PR TITLE
Add unit test case for fileclient

### PR DESCRIPTION
**Pull request by isbm**
### What does this PR do?

Adds a test case for https://github.com/saltstack/salt/commit/43a5e30386b9759a85bc3a26a9dddce48a877587

### CODE REVIEW

**Review by cachedout — CHANGES_REQUESTED** [review]
Hi @isbm 

Some failures here: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/10083/violations/file/tests/unit/fileclient_test.py/

**Review by cachedout — CHANGES_REQUESTED** [review]
We need to rename this file for the test runner to pick it up:

https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/10407/testReport/junit/unit.test_test_module_names/BadTestModuleNamesTestCase/test_module_name/

**Comment by cachedout** [comment]
@isbm Can you please rename the file as requested above? Thanks.

**Comment by rallytime** [comment]
Shouldn't this have already been merged-forward from an older branch? I made the changes to the file name and some of the import changes recently. 

https://github.com/saltstack/salt/blob/develop/tests/unit/test_fileclient.py

**Comment by rallytime** [comment]
Ok, let's close this as this file is the same as the other, just renamed. Thanks @isbm for these tests! :)

**Pull request closed without merging**
