### PR TITLE
[master] Populate user data / name within runners and for runner events on the event bus

### LINKED ISSUE #63148: [BUG]  orchestration does not propagate user name
**Description**
 when a runner is invoked from an orchestration state it does not pass the "user", generating a "user": UNKNOWN. 

Here you go a very simple example
```
# ORCH/test.sls
show:
  test.configurable_test_state:
    - changes: False
    - comment: this is a test

test_runner_metasyntetic:
  salt.runner:
    - name: test.metasyntactic
    - locality: uk
    - 
If you follow the events in the event bus, the salt.runner test_runner_metasyntetic invoked by the orchestration shows user: UNKNOWN.
salt/run/20221130134354984855/new	{
    ...
    "fun": "runner.state.orch",
    "fun_args": [
        "ORCH/test"
    ],
    "user": "root"
}
salt/run/20221130134414856176/args	{
    "_stamp": "2022-11-30T13:44:15.471747",
    "args": [],
    "kwargs": {
        "locality": "uk"
    },
    "name": "test.metasyntactic",
    "type": "runner"
}
salt/run/20221130134415911510/new	{
    "_stamp": "2022-11-30T13:44:15.940837",
    "fun": "runner.test.metasyntactic",
    "fun_args": [
        {
            "locality": "uk"
        }
    ],
    "jid": "20221130134415911510",
    "user": "UNKNOWN"
}
salt/run/20221130134415911510/ret	{
    "_stamp": "2022-11-30T13:44:16.154564",
    "fun": "runner.test.metasyntactic",
    "fun_args": [
        {
            "locality": "uk"
        }
    ],
    "jid": "20221130134415911510",
    "return": [
        "wibble",
        "wobble",
        "wubble",
        "flob"
    ],
    "success": true,
    "user": "UNKNOWN"
}
salt/run/20221130134354984855/ret	{
    "_stamp": "2022-11-30T13:44:16.380148",
    "fun": "runner.state.orch",
    "fun_args": [
        "ORCH/test"
    ],
 ...
    "success": true,
    "user": "root"
}
```

**Setup**
Salt Open, but affecting SSE also due it shows jobs activity by UNKNOWN user, and given it's really hard to distinguish if a job was part of an orchestration it generates some concerns.

**Steps to Reproduce the behavior**
Run the orch example included here and watch the event bus.

**Expected behavior**
Pass the user from orchestration to invoked runners.

**Screenshots**
Screen Shot 2022-11-30 at 10 56 22 AM

**Versions Report**

> 

<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```
Salt Version:
          Salt: 3004.2

Dependency Versions:
          cffi: 1.13.2
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.3
       libgit2: Not Installed
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: Not Installed
  pycryptodome: 3.15.0
        pygit2: Not Installed
        Python: 3.8.13 (default, Apr  5 2022, 17:15:15)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 21.0.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.3

Salt Extensions:
        SSEAPE: 8.8.2.4

System Versions:
          dist: rhel 7.9 Maipo
        locale: utf-8
       machine: x86_64
       release: 3.10.0-1160.71.1.el7.x86_64
        system: Linux
       version: Red Hat Enterprise Linux Server 7.9 Maipo
```
</details>

**Additional context**

### PR DESCRIPTION
**Pull request by dmurphy18**
### What does this PR do?
Populates the user correctly through out runners and reported as such on the events on the event bus.
First noticed in orchestration runners in #63148 found this problem runs much deeper.  saltutil.runner when called from the salt cli will properly propagate the user, as will the runner orchestrate

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/63148

### Previous Behavior
The user  responsible for the runner was reported as 'UNKNOWN'  in the events on the event bus.

### New Behavior
The user responsible for the runner is now correctly reported in the events on the event bus.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [X] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by Ch3LL** [comment]
@dmurphy18 Did you want to get this into 3006.0? If so, can you point the PR to the 3006.x branch?

**Comment by dmurphy18** [comment]
@Ch3LL Thanks for that, yes want it in 3006.0 GA, updated branch

**Comment by dmurphy18** [comment]
Replaced this PR with PR https://github.com/saltstack/salt/pull/64038 which is specifically against branch 3006.x for a cleaner PR.

**Comment by dmurphy18** [comment]
changed base back to master to get clean change code to try and determine why master branch changes work, but 3006.x branch fails

**Comment by dmurphy18** [comment]
Closing again now on master branch

**Pull request closed without merging**
