### PR TITLE
Back-port #41405 to nitrogen

### PR DESCRIPTION
**Pull request by rallytime**
Back-port #41405 to nitrogen

### CODE REVIEW

**Comment by cachedout** [comment]
This failed tests and lint.

**Comment by isbm** [comment]
@cachedout seems like some problems. Let me look at it tomorrow (now is 23:00 here)

**Comment by isbm** [comment]
@rallytime couldn't get to take over this one other than just re-PR the whole thing into https://github.com/saltstack/salt/pull/41495

**Comment by isbm** [comment]
@rallytime seems like you've forgot one commit that `import fnmatch` module. Hence all the failures all around the place. Seems fixed at my side, let's see what will happen.

**Comment by rallytime** [comment]
Sounds good. I'll close this.

**Pull request closed without merging**
