### PR TITLE
restart salt-syndic when salt-master restart

### PR DESCRIPTION
**Pull request by vinian**
### What does this PR do?

add salt-syndic as part of salt-master, which will make auto-restart salt-syndic when salt-master restart.  when a salt-master work as a syndic, restart salt-master but not restart salt-syndic will cause syndic cache the auth_key, and will lead to auth failed, this PR will not completely solve the problem from the source code side. but will make salt-syndic work properly.

### What issues does this PR fix or reference?

Fixes:  #48029

### Tests written?

No

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by cachedout** [comment]
What do you think of this, @gtmanfred ?

**Comment by gtmanfred** [comment]
This makes sense to me.

**Comment by cachedout** [comment]
@dmurphy18 or @terminalmage anything from either of you?

**Review by dmurphy18 — APPROVED** [review]

**Review by terminalmage — APPROVED** [review]
:+1:

**Pull request merged**
