### PR TITLE
Resolve https://github.com/saltstack/salt/issues/53567

### PR DESCRIPTION
**Pull request by fake-name**
### What does this PR do?

This removes the reactor teardown in the salt-cloud function calls.

As far as I understand it, the reactor is a global singleton, and should be torn down properly at the interpreter exit anyways. 

Right now, since it's shut down early, any calls to salt-cloud functions will subsequently explode. This makes the salt-cloud API somewhat useless, since you get *one* function call before everything is broken.

### What issues does this PR fix or reference?

https://github.com/saltstack/salt/issues/53567

### CODE REVIEW

**Comment by dwoz** [comment]
@fake-name Ideally this would get a test.

**Comment by fake-name** [comment]
I have no idea how to test this without a account at a VPS provider somewhere.

**Comment by Akm0d** [comment]
I might be able to help with a test case, but won't have time until next week to work on it

**Comment by fake-name** [comment]
Note that this now also includes support for deploying vultr VMs using SSH keys.

If you specify a ssh_key in the config file, that also exists in your vultr account, it'll use ssh-key based auth for your VM. If not, it falls back to password auth.

**Comment by whytewolf** [comment]
Since this event_get item also exists in 2019.2.0  this might be better ported to the 2019.2 releases and brought up to neon and develop. 

I can see this event_get closing the event bus in other ways that are not so obvious in other versions of python.

**Comment by whytewolf** [comment]
Also, the ssh keys stuff should be its own PR.

**Comment by fake-name** [comment]
> Since this event_get item also exists in 2019.2.0 this might be better ported to the 2019.2 releases and brought up to neon and develop.

All I want to do is use salt as a library without it exploding. Arrrrgh.

> I can see this event_get closing the event bus in other ways that are not so obvious in other versions of python.

Does that translate to "make the default to not destroy the event loop"?

**Comment by whytewolf** [comment]
> > Since this event_get item also exists in 2019.2.0 this might be better ported to the 2019.2 releases and brought up to neon and develop.
> 
> All I want to do is use salt as a library without it exploding. Arrrrgh.

I can applaud that. However, It is always good to make sure that if something breaks we get the break as early in the code as possible so that when things merge up they don't break again. Just trying to avoid later issues. as well as make sure things in earlier revisions work.

> 
> > I can see this event_get closing the event bus in other ways that are not so obvious in other versions of python.
> 
> Does that translate to "make the default to not destroy the event loop"?

No, Your fix is the right way to go. I'm just saying that while your testing showed the failure in python3. It might be a more silent failure in py2.

**Comment by DmitryKuzmenko** [comment]
@fake-name we don't accept any PRs to develop anymore. Please rebase this to master branch. Also please install the `pre-commit` hook as described in the [contribution quide](https://docs.saltstack.com/en/latest/topics/development/contributing.html)

**Comment by sagetherage** [comment]
@fake-name likely this will be closed as abandoned work, please rebase against master, use the pre-commit hook, resolve merge conflicts, and we have test clinics weekly to help with writing tests, if not then we will close this PR.

**Review by waynew — CHANGES_REQUESTED** [review]
If you need any help with writing tests, please reach out, I'm in #salt on freenode, community Slack, or I stream Test Clinics on twitch on T/Th

**Comment by ScriptAutomate** [comment]
Closing this PR. Changes can be made and submitted again, if wanted, but should now be done from `master` and to `master`. This has otherwise become too indecipherable, and is in a broken state with all the branch conflicts.

**Pull request closed without merging**
