### PR TITLE
Update chocolatey.py allow passing package_args

### PR DESCRIPTION
**Pull request by ryancurrah**
Allow passing 'package_args' to the chocolatey install state.

### CODE REVIEW

**Comment by cachedout** [comment]
@ryancurrah Could you please rebase this? There are merge conflicts.

**Comment by ryancurrah** [comment]
@cachedout roger that I will do tonight after work

**Comment by ryancurrah** [comment]
@cachedout ok i updated and i had to make the "salt.utils.warn_until" pep8 compliant it was to long.

**Comment by cachedout** [comment]
@ryancurrah Many thanks! Once the tests run we'll have a look and get this merged.

**Pull request merged**
