### PR TITLE
Update zfs.py

### PR DESCRIPTION
**Pull request by angeloudy**
salt zfs scheduled_snapshot uses gmtime() instead of localtime #43971

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
@sjorge Can you look at this please?

**Comment by sjorge** [comment]
Om mobile so the GitHub review stuff doesn’t work, look fine. But a ```.. versionchanged:``` in the docs stating a change from UTC to local time is in order.

So people can easily figure out why there schedule changed.

**Review by sjorge — CHANGES_REQUESTED** [review]
A versionchange notice for snapshot_schedule is missing, it would be nice to let people know why there schedule is suddenly different.

**Comment by cachedout** [comment]
@angeloudy Did you see the above feedback from @sjorge ?

**Comment by cachedout** [comment]
Bump @angeloudy

**Comment by sjorge** [comment]
Been rather busy at work so I haven't had much coding at home time, so not been super active lately. Sorry about that.

But perhaps we can merge this and add the versionchange note ourselves?

**Comment by sjorge** [comment]
@angeloudy @cachedout 

```patch
diff --git a/salt/states/zfs.py b/salt/states/zfs.py
index 127e89658b..2e1b83ce21 100644
--- a/salt/states/zfs.py
+++ b/salt/states/zfs.py
@@ -717,6 +717,10 @@ def scheduled_snapshot(name, prefix, recursive=True, schedule=None):
         a schedule must be setup to automatically run the state. this means that if
         you run the state daily the hourly snapshot will only be made once per day!

+    .. versionchanged:: Oxygen
+
+        switched to localtime from gmtime so times now take into account timezones.
+
     '''
     ret = {'name': name,
            'changes': {},
```

This should be enough, if you apple this patch this is good to go for me.
If there is no activity for a few days I will create a new PR were I pull in @angeloudy commit and add this patch on top of it.

**Comment by sjorge** [comment]
As mentioned I created a new PR including the small change I requested. #44502

**Comment by rallytime** [comment]
These commits were pulled in with #44502, so I'll close this.

Thanks for this change @angeloudy!

**Pull request closed without merging**
