### PR TITLE
Adding salt rendering to saltcheck tests

### PR DESCRIPTION
**Pull request by wcannon**
### What does this PR do?
Adds ability to use rendering in saltcheck test files
### What issues does this PR fix or reference?
None
### Previous Behavior
Only supported saltcheck tests in yaml format

### New Behavior
Supports standard salt rendering (e.g. yaml + jinja)

### Tests written?

No - simply calling salt rendering module

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @wcannon 

I know this is very simple code but we are trying to get everything that goes into develop to have regression tests. Can you add some basic unit tests for this new functionality?

**Comment by wcannon** [comment]
Yes.  I'll add a test in the next couple days.  My dev environment broke after pulling the latest commits from the development branch.  Will have to set it all up again from scratch.

**Comment by mchugh19** [comment]
In playing around with saltcheck, it is incredibly powerful and useful. It's worth pointing out in the documentation that since it uses the salt renders you can use pillars, and standard jinja markup to write tests. 

For example, rather than having to hardcode package names, you can reuse the same mappings as the state making the test markup super close to the actual state file.
```
{% from "openssh/map.jinja" import openssh with context %}

openssh-server-latest:
  module_and_function: pkg.latest_version
  args:
    - {{ openssh.server }}
  assertion: assertEmpty
```

**Comment by rallytime** [comment]
@wcannon Were you able to write some tests for this?

**Comment by wcannon** [comment]
No, I had some trouble with my salt dev environment.  No new tests
written.  But, I'm not sure it is really an issue.

**Review by gtmanfred — APPROVED** [review]

**Pull request merged**
