### PR TITLE
Fix for salt.utils.decorators and module.__name__ under esky

### LINKED ISSUE #25756: Esky builds on SmartOS broken in 2015.5 branch
Transferring content from an email thread at @jfindlay's request (see the last few comments on #25730)

@nshalman:
> Something in 2015.5 doesn't seem to like being packaged in an Esky and I haven't had a chance to debug it...

@dmurphy18:
> There is a problem with the use of decorators in the lazy loader where `inspect.getmodule` is not returning a module.
> Found this with the 2015.5 branch, but have not had time to research a solution for the issue yet.
> `./salt/utils/decorators/__init__.py  line 62`
> Found issues researching on Google about use of `@decorator` syntax and not using index 1 but 2 when inspecting the stack.
> I have tried replacing the `__init__.py` file without the benefit of esky and the problem still occurred. 
However esky could be affecting other files. BTW: python used was python 2.7.10.

### PR DESCRIPTION
**Pull request by sjorge**
This fixes #25756, after a few days of searching and trying lots of things... this is the only way I got it to work.

```
[root@core ~]# /opt/local/salt/bin/salt-call --local test.ping
local:
    True
```

Pinging @nshalman for possible comments.

### CODE REVIEW

**Comment by jfindlay** [comment]
@sjorge, thanks for your excellent work on this.

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by sjorge** [comment]
OK seems like it needs a bit more work :( as tests are failing

**Comment by sjorge** [comment]
Anybody have an idea why those 2 tests are still failing?

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by sjorge** [comment]
For the following
```python
module = inspect.getmodule(inspect.stack()[1][0])
kind = module.f_globals['__name__'].rsplit('.', 2)[1]
```
is the return of ```module.f_globals['__name__'].rsplit('.', 2)``` supose to be:  ```['salt', 'modules', 'test']```

**Comment by sjorge** [comment]
Ok this seems completely wrong, let me close this one for now. Bugger.

**Pull request closed without merging**
