### PR TITLE
fix returners.postgres inability to handle byte string responses

### LINKED ISSUE #55226: json/utf8 problem with pgjsonb, postgres and mysql returners
### Setup
/etc/salt/master
```
[…]
returner.pgjsonb.host: 'localhost'
returner.pgjsonb.user: ‘xxx'
returner.pgjsonb.pass: ‘xxx'
returner.pgjsonb.db: 'salt_master_cache'
returner.pgjsonb.port: 5432

master_job_cache: pgjsonb
event_return: pgjsonb
# lets keep jobs in "active" part of database for 24h and then move them to archive tables
keep_jobs: 24
archive_jobs: True
[…]
```
### Steps to Reproduce Issue
```
/var/log/salt/master:
2019-11-07 15:21:50,884 [salt.utils.event :1233][ERROR   ][524] Could not store events - returner 'pgjsonb.event_return' raised exception: 'utf8' codec can't decode byte 0xaa in position 2: invalid start byte
2019-11-07 15:21:50,885 [salt.master      :1846][ERROR   ][539] Error in function _return:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1839, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1638, in _return
    self.opts, load, event=self.event, mminion=self.mminion)
  File "/usr/lib/python2.7/dist-packages/salt/utils/job.py", line 108, in store_job
    mminion.returners[savefstr](load['jid'], load)
  File "/usr/lib/python2.7/dist-packages/salt/returners/pgjsonb.py", line 332, in save_load
    {'jid': jid, 'load': psycopg2.extras.Json(load)})
  File "/usr/lib/python2.7/dist-packages/psycopg2/_json.py", line 96, in getquoted
    s = self.dumps(self.adapted)
  File "/usr/lib/python2.7/dist-packages/psycopg2/_json.py", line 89, in dumps
    return dumps(obj)
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xaa in position 2: invalid start byte
```
Postgres:
```
postgres=# \l
                                       List of databases
       Name        |  Owner   | Encoding |   Collate   |    Ctype    |    Access privileges     
-------------------+----------+----------+-------------+-------------+--------------------------
 postgres          | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 salt_master_cache | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/postgres            +
                   |          |          |             |             | postgres=CTc/postgres   +
                   |          |          |             |             | xxx=CTc/postgres
 template0         | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres             +
                   |          |          |             |             | postgres=CTc/postgres
 template1         | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres             +
                   |          |          |             |             | postgres=CTc/postgres
```

### Versions Report
master:
```
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.24.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.11 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-11-amd64
         system: Linux
        version: debian 9.11 
```

minion:
```
    Salt Version:
               Salt: 2019.2.2
     
    Dependency Versions:
               cffi: 1.12.2
           cherrypy: 17.4.1
           dateutil: 2.8.0
          docker-py: Not Installed
              gitdb: 2.0.6
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.10.1
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: 2.19
           pycrypto: Not Installed
       pycryptodome: 3.8.1
             pygit2: Not Installed
             Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
       python-gnupg: 0.4.4
             PyYAML: 3.13
              PyZMQ: 18.0.1
               RAET: Not Installed
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.3
                ZMQ: 4.3.1
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 10
             system: Windows
            version: 10 10.0.18362 SP0 Multiprocessor Free
```

### PR DESCRIPTION
**Pull request by ITJamie**
It would probably make sense for something like this to be in a util for other returners to access. I have updated for the three mentioned returners in https://github.com/saltstack/salt/issues/55226

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/55226

### Previous Behavior
Error when supplied with binary data. for example nacl.enc_file would always cause this
```
[CRITICAL] The specified 'postgres' returner threw a stack trace
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/job.py", line 140, in store_job
    mminion.returners[fstr](load)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/returners/postgres.py", line 242, in returner
    salt.utils.json.dumps(ret["return"]),
  File "/usr/lib/python3/dist-packages/salt/utils/json.py", line 137, in dumps
    return json_module.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

### New Behavior
convert the ['return']['return'] element to an actual string instead of bytes

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by waynew** [comment]
I'm just looking at this on my phone so I have no idea if this comment is valid, but maybe there's an encoding/raw flag we should be passing to the postgres constructor/connection?

**Comment by ITJamie** [comment]
That would be based on the db schema. I believe our example db schemas on the docs already set it to utf-8.

**Comment by waynew** [comment]
Gotcha, that makes sense, and on a computer where I can actually see and grok this code a bit... yeah, I think this makes sense to be delegated to each of the returners that are storing data in a non-binary-able format.

But... it may actually make sense to extract *that* functionality into a utility, if we don't already have that within Salt :thinking:

**Comment by ITJamie** [comment]
I agree it should probably be moved to a util. I actually brought that up in the pr message.

**Comment by ITJamie** [comment]
@waynew I have de-duped the code and created a method for it in salt.returners. it is now a much more minimal change-set to the returners. 
I have not however read through the rest of the returners to see if they also need the fix implemented.
If you believe we already have this functionality elsewhere, it should be quick to update to an alternative method

**Comment by waynew** [comment]
I'm just heading out for some PTO, but I did a cursory glance and there *does* exist `salt.utils.data.decode` -- does that do what we need here?

I haven't done a full audit of the other returners (mostly operating under the assumption that as I work through the testing I'd expose any issues here), but at least at a glance my thought is that it makes sense for each individual returner to make that distinction themselves.

For example, if I'm storing data in a JSON format, I can't actually store it as binary data without some kind of conversion, like base64 encoding.

OTOH, if I'm storing data as msgpack or pickle, well I can store all kinds of binary data just fine.

So it makes sense to me that each of the returners should be deciding if they need to encode the payload or not -- and I'm totally fine with making an incremental change like these particular ones here and then converting other ones later, if necessary :+1:

**Comment by ITJamie** [comment]
Enjoy the pto!

**Comment by MKLeb** [comment]
@waynew seems to have looked at this and agrees with this approach.  It needs a changelog and test (something simple, unit is fine), and then it'll be good to go!

**Comment by MKLeb** [comment]
@ITJamie Any possibility you could add a test and changelog here?  Thanks!

**Comment by ITJamie** [comment]
Ive moved the function into salt/utils/jid's 

this seems like a sanish place for it, its already being imported into the required modules + already had unit tests i could extend

**Comment by MKLeb** [comment]
I just tried to reproduce it locally, and it worked with `salt.utils.data.decode`.  It seems your error msg and the function you pasted are unrelated because `save_load` is not called inside `returner`.  Can you try using `salt.utils.data.decode` for your `cleaned_return` in `returner`?

To test this, I created a `/tmp/foo` with some text in it and did `salt \* file.read /tmp/foo binary=True`.

**Comment by MKLeb** [comment]
Also, I forgot to mention this, but your solution seems to be breaking on something with a simple non-dict return, for instance with a `test.ping`.  Using `salt.utils.data.decode` should handle all of those cases.

**Comment by MKLeb** [comment]
@ITJamie Any updates here?

**Review by twangboy — DISMISSED** [review]

**Review by Ch3LL — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
