### PR TITLE
Fix parsing of 'renew' parameter in acme.cert

### PR DESCRIPTION
**Pull request by xuhcc**
### What does this PR do?

Fixes the incorrect handling of `renew=force` flag by `acme.cert` function.

### What issues does this PR fix or reference?

The bug was introduced in #55589

### CODE REVIEW

**Review by DmitryKuzmenko — DISMISSED** [review]

**Comment by DmitryKuzmenko** [comment]
@xuhcc could you please resolve merge conflicts?

**Comment by xuhcc** [comment]
@DmitryKuzmenko Done.

**Review by DmitryKuzmenko — DISMISSED** [review]

**Review by dwoz — CHANGES_REQUESTED** [review]
We should add a test to make sure this case is covered. The fact that this bug got introduced must mean this line of code is not tested.

**Review by DmitryKuzmenko — APPROVED** [review]

**Comment by DmitryKuzmenko** [comment]
@xuhcc thank you for update!
@dwoz test is updated. Could you please re-review this?

**Review by dwoz — APPROVED** [review]

**Pull request merged**
