### PR TITLE
Tests run py3

### PR DESCRIPTION
**Pull request by thatch45**
### What does this PR do?

This extends #32366 which gets salt running on python3 for the zeromq transport, these fixes get the salt test suite to start and run under python3!

Only merge after merging #32366

It has a lot of failures, but it runs surprisingly well!
### Previous Behavior

Remove this section if not relevant
### New Behavior

Remove this section if not relevant
### Tests written?

Yes/No

### CODE REVIEW

**Comment by thatch45** [comment]
@skizunov once this is merged then the salt test suite will run in python3, our preliminary python3 tests show about 300 tests that need to be fixed out of over 5000. So we are somewhat close to python3 support in Salt

**Comment by rallytime** [comment]
@thatch45 Is this branch perhaps a little "stale"? I haven't see that slack_notify test failing in the branch or on other PRs. Though I'm not sure what change here is causing it to fail after a quick glance.

**Comment by thatch45** [comment]
yes, this branch is like 2 weeks old, that test is unrelated, if this looks good to you it is good to merge, it is just waiting for another review

**Comment by thatch45** [comment]
if this is merged it will also merge #32366 btw

**Pull request merged**
