### PR TITLE
Feature minion restart

### PR DESCRIPTION
**Pull request by plastikos**
### What does this PR do?

It restarts the minion.
### What issues does this PR fix or reference?

None
### Tests written?

Not yet.  This needs new scaffolding for an ephemeral `salt-minion`.  The current `salt-minion` scaffolding expects the process to be started once at the beginning of tests and run throughout all of the tests.

### CODE REVIEW

**Comment by plastikos** [comment]
See #32040.  Yes, I borked-up the rebase.

**Comment by jtand** [comment]
@plastikos If this fails, ping me and I can get you a test vm like the ones we run PR tests on :)

**Comment by plastikos** [comment]
@jtand, thanks!  Although it's one of my other PR that I need to work on - so how do I get a test VM to work with?

**Comment by plastikos** [comment]
@cachedout, I'm recommending this be merged even without integration test . . . which I will eventually add with a P.R..

**Comment by cachedout** [comment]
@plastikos Will do. Could you please rebase this first? There are merge conflicts.

**Comment by plastikos** [comment]
<grumble>Rebased it yesterday</grumble>
/me rumages around . . ..

**Pull request closed without merging**
