### PR TITLE
convert jinja context to dictionary

### PR DESCRIPTION
**Pull request by gtmanfred**
### What does this PR do?
For `show_full_context`, it is useful to have this as a serializable dictionary so that it can be dumped and actually parsed using

`{{show_full_context|yaml(False)}}`

### Previous Behavior
show_full_context returns an object mapping

### New Behavior
show_full_context returns a serializable dictionary

### Tests written?

No

### CODE REVIEW

**Review by cachedout — COMMENTED** [review]
Does this fix a particular bug?

**Comment by gtmanfred** [comment]
It does not fix any particular bug, it was just something that came up in talking to someone on twitter yesterday.

https://twitter.com/rawkode/status/916028247619653632

**Comment by cachedout** [comment]
@gtmanfred IMHO it should be moved to develop then.

**Comment by gtmanfred** [comment]
Bah, i thought I did it on develop.

Yup, will move.

**Comment by cachedout** [comment]
@gtmanfred You were going to move this? :]

**Pull request closed without merging**
