### PR TITLE
Keep the only one record per module-function in depends decorator.

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
### What does this PR do?
As I see the initial design of the `depends` decorator used `set` to keep the unique seet of decorated functions determined by the module, function and it's alternative implementation.

After functions become loaded with lazyloader the same function loaded twice become another object.
Also the `module` was replaced by `frame` that is also another object each time.

What we got as a result: `depends` decorator leaks on each `lazyloader` instantiation.

### What issues does this PR fix or reference?
Fixes: #37938, #33890 

### Previous Behavior
`depends` uses a `set` of `(frame, function, alternative_function)` to reference the decorated functions.

### New Behavior
Use `dict` where the key is `(module_name, function_name)` to keep the only unique functions.

### Tests written?
No

### CODE REVIEW

**Comment by DmitryKuzmenko** [comment]
BTW, maybe it's better to rebase it to 2016.3 branch? It's also affected.

**Comment by cachedout** [comment]
@DmitryKuzmenko Yes, that is what we will want. I tried to change the base here but it did not merge cleanly at all. Could you please close this and open another PR against 2016.3? Thanks.

**Comment by DmitryKuzmenko** [comment]
@cachedout will do.

**Comment by DmitryKuzmenko** [comment]
@cachedout  I've rebased the branch and changed the base here so there's no need to open a new PR.

**Pull request merged**
