### PR TITLE
testing only running few tests if this is a doc pr

### PR DESCRIPTION
**Pull request by bryceml**
### What does this PR do?
Makes it so the pr-tests only test docs, lint, and ubuntu (since there are doc tests as part of a normal run)

### CODE REVIEW

**Comment by s0undt3ch** [comment]
I would suggest running on either Debian 9 or 10 since those are the fastest builds?

**Comment by bryceml** [comment]
Sure, I just wasn't sure all the doc tests run on anything but ubuntu, they probably do.

**Comment by s0undt3ch** [comment]
We would also have to disable the required Py3 statuses, unless the builds just maked as passed? Ie, all other builds not building docs.
An alternative would be to run all builds, but only doc related tests?

**Comment by bryceml** [comment]
that would be nice, how do we do that?

**Comment by s0undt3ch** [comment]
Once pytest lands we ciuld create a doc tests nox session and use that instead of the regular test session if it's only a doc related change.

**Comment by bryceml** [comment]
yeah, lets do that, should I leave this here until we get that work done?

**Comment by s0undt3ch** [comment]
Either that or an issue.

**Comment by bryceml** [comment]
We would need a way to know that the tests were run with doc only change easily, so if someone removes the label after the test runs, we still know.

I'll make an issue referencing this and then close this.

**Pull request closed without merging**
