### PR TITLE
Add initial unit tests and fix minor issues for aptly module

### PR DESCRIPTION
**Pull request by m03**
### What does this PR do?
- Adds unit tests for `get_config`, `list_repos`, `get_repo`, `new_repo`, and `delete_repo`.
- Changes `list_repos` to use proper dunder `__salt__['aptly.get_repo']` instead of just `get_repo`.
- Removes redundant/unused variables from `get_repo `, `get_published`, and `get_snapshot`.
- Fix code alignment.

### What issues does this PR fix or reference?

None.

### Tests written?

Yes.

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by twangboy — APPROVED** [review]

**Comment by m03** [comment]
@dwoz Looks like `master` is now the preferred target branch for changes like these, but it appears that the (https://github.com/saltstack/salt/commits/master/salt/modules/aptly.py)[master branch] is missing some (https://github.com/saltstack/salt/commits/develop/salt/modules/aptly.py)[fairly old commits that are present in the develop branch] that this PR expects to be in place. Is there anything else needed from my end, or should I wait until this disparity is resolved?

**Comment by dwoz** [comment]
@m03 Sounds good, thanks!

**Comment by dwoz** [comment]
@m03 We are no longer accepting PRs to the `develop` branch. This needs to be re-opened against the `master` branch. You can link to this PR from the new one to preserve any disscussion history. Sorry for the confusion.

**Comment by m03** [comment]
@dwoz See my previous comment that you replied to last week. I cannot re-open this PR against the `master` branch currently since the commits it depends on, commits which had been merged [over a year ago](https://github.com/saltstack/salt/pull/50398) into `develop`, [have not yet been merged](https://github.com/saltstack/salt/pull/54539) to `master`.

I can resubmit my PR once this takes place.

**Pull request closed without merging**
