### PR TITLE
Grammar fix

### PR DESCRIPTION
**Pull request by DaveQB**
Minor fix to the docos.

### CODE REVIEW

**Comment by jfindlay** [comment]
@DaveQB, thanks for the edit.  Are you sure the `ssh://` URLs are correct?  I just tried it and it didn't work for salt:
```console
$ git clone ssh://git@github.com:saltstack/salt.git
Cloning into 'salt'...
ssh: Could not resolve hostname github.com:saltstack: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by jfindlay** [comment]
Fixes #25960.

**Comment by DaveQB** [comment]
@jfindlay 
We did some more research onto this (a colleague report this issue to me)
This works:
git clone ssh://git@github.com/saltstack/salt.git

As well as what you have:

git clone git@github.com:saltstack/salt.git

The issue is using "git clone git@github.com:saltstack/salt.git" with a Atlassian Stash server with identify files. He should chime in with a comment on the exact error here soon.

**Comment by terminalmage** [comment]
This was an inaccurate change. When using ``ssh://`` you need a slash after the domain name, not a colon. The fix is included in https://github.com/saltstack/salt/pull/37604.

**Pull request merged**
