### PR TITLE
Fire event on event init

### PR DESCRIPTION
**Pull request by jacksontj**
This way once we connect there will be something for us to get to. Not a perfect fix since we are fixing a race condition by adding in another one, but in most cases it seems to finish in 0.0007s instead of 1s (on a quiet event bus)

Better workaround for #20950

### CODE REVIEW

**Comment by jacksontj** [comment]
Lets try again jenkins ;)

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
I triggered one more run, but it appears that the change you've made and `integration.shell.key.KeyTest.test_keys_generation_no_configdir` aren't getting along so well. Both test VMs timed out like so:
```
01:23:58 [CPU:100.0%|MEM:50.1%|Z:0]  ... OK (0.649s)
01:23:58   test_keys_generation_no_configdir (integration.shell.key.KeyTest)
02:00:12 Build timed out (after 60 minutes). Marking the build as aborted.
```

**Comment by jacksontj** [comment]
@rallytime that test doesn't seem to get stuck locally... I wonder if we are somehow getting stuck in the linger problems we used to have... you don't happen to have the debug log output from that failure do you?

**Comment by jacksontj** [comment]
Oh... I think I may have found a larger zmq issue here.. It seems that push/pull sockets (at least in python) don't honor the SNDTIMEO option. Meaning all sends succeed, but if no linger is set then the socket stays stuck forever. Since we only set the linger in __del__ (in interpreter shutdown) we can't gaurantee that we'll hit the code which sets the linger. So, If we move the linger setting up to the connects it *should* solve our problem.

**Comment by rallytime** [comment]
@jacksontj nice! Let's see how this latest run goes.

**Comment by jacksontj** [comment]
typo fix ;) lets go again!

**Comment by jacksontj** [comment]
@rallytime And there we go, all green :)

**Comment by cachedout** [comment]
Many thanks @jacksontj

**Comment by jacksontj** [comment]
Np, ;) One less blocker for the 2015.2 release :)

**Pull request merged**
