### PR TITLE
netapi works with ipc_mode tcp correctly

### PR DESCRIPTION
**Pull request by austinpapp**
### What does this PR do?

When using `ipc_mode: tcp`, netapi client would fail to determine if the salt master was running because using TCP does not use the ipc socket files. As a result, anything referencing netapi would fail such as the auth module. 

This fix checks the tcp port as a means to confirm the master is listening. 

### Previous Behavior

```
[~/git/saltstack/salt (develop<>)] $ salt-run -c salt27/etc/salt/ auth.mk_token username=salt password=salt eauth=auto
Exception occurred in runner auth.mk_token: Traceback (most recent call last):
  File "/home/apapp/git/saltstack/salt/salt/client/mixins.py", line 377, in low
    data['return'] = func(*args, **kwargs)
  File "/home/apapp/git/saltstack/salt/salt/runners/auth.py", line 47, in mk_token
    'Salt Master must be running.')
SaltDaemonNotRunning: Salt Master must be running.
```

### New Behavior

```
[~/git/saltstack/salt (develop<>)] $ salt-run -c salt27/etc/salt/ auth.mk_token username=salt password=salt eauth=auto
eauth:
    auto
expire:
    1550654123.110241
name:
    salt
start:
    1550610923.11024
token:
    2405c9826943f96f4d133af3e0bb20d1b2e6448612246cab376156fa6d0c2ca8
```

### Tests written?

No

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by austinpapp** [comment]
another commit broke `integration.grains.test_custom`. will track see if i can track that down.

**Review by dwoz — APPROVED** [review]

**Review by dwoz — COMMENTED** [review]
@austinpapp Is there a test that will catch this if it breaks?

**Comment by austinpapp** [comment]
i did not wrote a test for it. i should be a good citizen and do that. hang tight.

**Comment by dwoz** [comment]
@austinpapp We are no longer accepting PRs to the `develop` branch. This needs to be re-opened against the `master` branch. You can link to this PR from the new one to preserve any disscussion history. Sorry for the confusion.

**Pull request closed without merging**
