### PR TITLE
Remove the file.grep Carbon warning for multiple command line args

### PR DESCRIPTION
**Pull request by rallytime**

### CODE REVIEW

**Comment by rallytime** [comment]
ping @terminalmage This was your change/deprecation. Is there anything more I need to do here?

**Comment by terminalmage** [comment]
https://github.com/rallytime/salt/pull/15 should round this out. We don't want to just pass these improperly passed args through, as they'll break the grep command.

**Comment by cachedout** [comment]
Waiting on @rallytime to merge the PR from @terminalmage here.

**Comment by rallytime** [comment]
Merged!

**Pull request merged**
