### PR TITLE
Fix azurefs

### PR DESCRIPTION
**Pull request by basepi**
### What does this PR do?

Fixes azurefs to work with modern versions of the azure python API

### Tests written?

No

### CODE REVIEW

**Comment by techhat** [comment]
Let me take a closer look at this. @tonybaloney I would love your input too.

**Comment by tonybaloney** [comment]
@techhat it doesn't support 2.6, I remember that much. I'll take a look

**Comment by techhat** [comment]
@basepi that's true, the Azure SDK has a minimum Python version of 2.7.

**Review by techhat — APPROVED** [review]

**Comment by cachedout** [comment]
@tonybaloney Do you feel like this is OK to merge?

**Comment by cachedout** [comment]
@basepi There are some lint errors: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/10754/violations/file/salt/fileserver/azurefs.py/

**Comment by basepi** [comment]
Fixed.

**Review by tonybaloney — APPROVED** [review]

**Comment by tonybaloney** [comment]
@cachedout :+1:

**Pull request merged**
