### PR TITLE
Log file group

### PR DESCRIPTION
**Pull request by bdrung**
On Debian based system, the minion log `/var/log/minion/minion` should belong to root:adm and have the permission 640. This allows members of the adm group to read the minion log.

Please review my commits and feel free to adjust them to make them work on all platforms.

### CODE REVIEW

**Comment by thatch45** [comment]
@bdrung this is too distribution specific and will break non debian distros and windows, to the extent that about 90% of all salt installs would not start.
We can add this if the opt for the log group is none and then generated based on the os, AND if we try/except gate the grp import as that will break windows

**Comment by bdrung** [comment]
Thanks for the recommendations. Is the option name `log_file_group` okay or should I use a different name?

I will change the code to default `log_file_group` to None (and do nothing in this case). If `log_file_group` is set, it should try to import `grp` and print an error if that fails (but continue). Then the salt Debian package can set `log_file_group` to `adm` as default.

**Comment by s0undt3ch** [comment]
I think this should be handled by the package...

**Comment by thatch45** [comment]
I think I am going to side with @s0undt3ch here, this should be part of the package. I am goign to close this out, even if it is implemented correctly it will introduce a lot of un needed complexity to a system that should be handled on the package layer

**Pull request closed without merging**
