### PR TITLE
Fix grains.append in nested dictionnary grains #23411

### PR DESCRIPTION
**Pull request by dr4Ke**
A new pull request agains branch 2014.7 to replace #23440

### CODE REVIEW

**Comment by dr4Ke** [comment]
I don't know what to do with the `versionadded:: FIXME` I put in the comments for new parameter `delimiter`. Do you set it to the right value when merging? Or is it unnecessary?

**Comment by jfindlay** [comment]
In this case the versionadded will be 2014.7.6.

**Comment by dr4Ke** [comment]
OK. Do you know how it is set? Do I need to do it? Is it done as part as the release process?

**Comment by jfindlay** [comment]
Just change `FIXME` to `2014.7.6` and this will be good to merge, thanks.

**Comment by dr4Ke** [comment]
I'm writing some unit tests for this function. This could take some time since I'm not used to it (writing unit tests, and saltstack test suite).

**Comment by jfindlay** [comment]
That would be awesome.  Let me know if you have any questions.  Thanks.

**Comment by dr4Ke** [comment]
I wrote some tests. I put them in a separate branch: https://github.com/dr4Ke/salt/compare/fix_grains.append_nested...dr4Ke:grains.append_unit_tests
Would you mind looking at it? I'd like to know if I did it right or not.

**Comment by jfindlay** [comment]
@dr4Ke, those tests look great, thanks.

**Comment by dr4Ke** [comment]
Thank you for the merge. I have submitted another pull request for the unit tests: #23551

**Comment by jfindlay** [comment]
Sorry, I should have waited for your tests.

**Pull request merged**
