### PR TITLE
fileclient.RemoteClient.hash_file: query env from URL

### PR DESCRIPTION
**Pull request by jfindlay**
Related to #28822.

### CODE REVIEW

**Comment by basepi** [comment]
For a moment I thought this was a duplicate of https://github.com/saltstack/salt/pull/30166, but I guess one is fileclient and one is cp. Looks good, we'll just wait on the lint.

**Comment by cachedout** [comment]
Hmm. This function has kwargs for `saltenv` and `env` and we're grabbing the env by parsing the `path`? I'm concerned that the real source of this problem may be elsewhere.

**Comment by cachedout** [comment]
@jfindlay Did you see my comment above?

**Comment by jfindlay** [comment]
@cachedout, yes, unfortunately, I don't have time to investigate this further.  The [other change](https://github.com/saltstack/salt/pull/30166) should be enough to fix the referenced issue, so you are welcome to close this.

**Pull request closed without merging**
