### PR TITLE
Update autodoc topics for new modules added in 2016.11

### PR DESCRIPTION
**Pull request by rallytime**

### CODE REVIEW

**Comment by cachedout** [comment]
I think you mentioned this yesterday but just in case: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/7576/violations/file/salt/modules/snapper.py/

**Comment by lorengordon** [comment]
What do you think about adding a note to the [contributing doc](https://docs.saltstack.com/en/latest/topics/development/contributing.html) describing the steps to get new modules working with autodoc...

**Comment by lorengordon** [comment]
Oh, [this looks like it](https://docs.saltstack.com/en/latest/topics/development/conventions/documentation.html#adding-module-documentation-to-the-index), on the documentation page, which is linked from the contributing page.

Maybe then add a note to the [PR template](https://github.com/saltstack/salt/blob/develop/.github/PULL_REQUEST_TEMPLATE.md), "Documentation updated?" with a link to the doc page...

**Comment by rallytime** [comment]
@cachedout Yes, that is what I was asking you about yesterday.

@lorengordon I discovered recently that there is actually a script that generates this list of missing autodoc modules (see `doc/apidoc-saltmods.sh`) - very handy! As long as we remember to run it every now and then, we can make sure the autodoc modules are added in a timely manner. I think @meggiebot has added this to our release checklist, but I will confirm with her. 

Since the autodoc part only applies to new files, I am not sure if that specific thing should be added to the PR template checklist, though I do wonder if a general mention of updating documentation is a good idea to add. What do you think @cachedout?

**Comment by rallytime** [comment]
Ok, I reverted the changes to the snapper module that moved the import/error logic into `__virtual__()` as that wasn't the right approach here since we need the `snapper` object created there all through out the module. 

Thanks to @cachedout for help on adding the `__iner__()` and `next()` functions to get the docs building again. This should be good to go after the test run.

**Pull request merged**
