### PR TITLE
Adding version 3 queries for Cassandra keyspaces and columns functions

### PR DESCRIPTION
**Pull request by anitakrueger**
### What does this PR do?

Cassandra changed their system schema layout for keyspaces and other internals in version 3. This module's functions only support v2 at the moment.
https://issues.apache.org/jira/browse/CASSANDRA-6717

### What issues does this PR fix or reference?

When running agains a v3 Cassandra cluster, certain functions are broken for example list_keyspaces.

### Previous Behavior

Cassandra v2 internal queries to get keyspaces and columns were used.

### New Behavior

For certain functions, the queries to be used need distinguishing between v2 and v3 and possibly future changes. So the query for those can now be a dictionary mapping version and query together.
The query function then selects either the specific version that is being executed against for the query, or the major version or just the latest one.

### Tests written?

No

Unfortunately I am struggling very much with writing tests :( It looks like someone attempted to write some tests for this module, but the functions in there don't test the core functionality. In fact, I am not sure how this would be testable without a 3rd party integration at all. I know responses can be mocked as well as the input, but I just don't know enough about this. Would appreciate help here.

### Commits signed with GPG?

Yes

### Pylint errors

It seems the module has lots of pylint errors for lines being too long. I am pretty sure I haven't introduced any new ones, but didn't know if the "old" ones need to be fixed for this to be merged?

### CODE REVIEW

**Comment by rallytime** [comment]
Thank you for this change @anitakrueger!

In terms of your questions: for pylint, the tests we use for salt PRs is the `.testing.pylintrc` file in the root of the salt repo. We use this custom one because it has salt-specific checks in it and it doesn't worry about line lengths so much. You can use that to check your code before submitting instead of the standard one.

For your testing question, I think adding some nicely mocked tests for the core functionality would be great. Would test writing be more helpful if we installed some of the cassandra libs on our test boxes?

**Comment by cro** [comment]
Hi @anitakrueger !  This is a good change for Cassandra users, thank you.  We would appreciate if you had a few minutes to add to the release notes and/or the documentation mentioning that the module works with Cassandra v3 now.

**Review by cro — APPROVED** [review]

**Comment by rallytime** [comment]
Hi @anitakrueger - Just checking in here. Can you add some documentation to the [Oxygen release notes](https://github.com/saltstack/salt/blob/develop/doc/topics/releases/oxygen.rst) and the module documentation noting this support? Since the tests need additional work here, they can be addressed at another time.

**Comment by anitakrueger** [comment]
@rallytime I've added the documentation to state the support for v3.

Now with regards to the tests, I will use .testing.pylintrc as you said for that.
For the actual unit tests, I want to create another PR as I have updated the module once again and added 3 states for cassandra as well (cassandra_keyspace, cassandra_privileges, cassandra_user). But those will really need proper tests. So I am looking at the postgres module and state tests and they use mocked csv and `assert_called_once_with`. Is that the way to go there?

**Comment by rallytime** [comment]
@anitakrueger Thank you!

Yes, that is the way to go there. I know the mocking can be a bit tricky, so I am excited that you'll be taking a look at improving the tests. Please reach out if you have questions.

**Review by rallytime — APPROVED** [review]

**Pull request merged**
