### PR TITLE
x509: Fix "prerequired" misspellings

### PR DESCRIPTION
**Pull request by Tracerneo**
### What does this PR do?
Probably fixes some unwanted behaviour.
This is the only occurrence of "preqrequired" in the whole repo. Even the comment has different misspelling.

### Previous Behavior
Probably not wanted.

### New Behavior
Probably wanted.

### Tests written?
No.

### Commits signed with GPG?
No.

### CODE REVIEW

**Comment by waynew** [comment]
Chased the introduction to https://github.com/saltstack/salt/pull/23005

Weird: the word was used with the apparent typo several times.

But... I can't find any indication that it was actually the *correct* word 🤷‍♂

**Review by dwoz — DISMISSED** [review]

**Comment by waynew** [comment]
Since the only results that show up for me in Google for `preqrequired` are literally ones here in the x509 state in Salt, and 1 blog post by Ansible, I'm going to say that this was a bug.

---

@Tracerneo do you think you could write a test for this? It's kind of a beastly function right now, so mocking may be difficult.

But all the test really needs to do is ensure that you can create_certificate when passing in a bunch of keywords, especially `prerequired` vs `preqrequired`, and that it doesn't break anything.

Let me know if you need any help there.

**Comment by waynew** [comment]
@Tracerneo are you interested in finishing this up, or are you looking for other people to step up?

**Review by waynew — CHANGES_REQUESTED** [review]
@Tracerneo are you interested in finishing this up and adding tests, or are you looking for other people to step up?

**Comment by waynew** [comment]
@Tracerneo any updates?

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
