### PR TITLE
Fix for Issue #44404

### PR DESCRIPTION
**Pull request by sjorge**
### What does this PR do?
This PR fixes the issue described in #44404

This is done by exposing the parsable output from ```zfs list```, ```zfs get```, ```zpool list```, and ```zpool get``` via the salt zfs and zpool module to the zfs state.

We then conver the user input to what the zfs parsable output is so we can properly compare them.

### What issues does this PR fix or reference?
#44404

### Previous Behavior
A user could set a property to '1024G' without parsable output zfs would return this as '1T' on the next run, resulting in the property always being updates.

### New Behavior
We convert the user's input to the zfs parsable format, we then compare it to the output of zfs.

### Tests written?
No

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by sjorge** [comment]
This is still a work in progress, the module side of thing is done. I will work on the actual state bits later today.

**Comment by sjorge** [comment]
All working now, even some extra new tests for the salt.modules.zfs and salt.modules.zpool.

Some cleanup happened for things along the way to make the code more readable, but admittedly it could still be improved. I will give it another quick pass tonight. After that I will remove the WIP status.

There is probably a few days worth of general code readability improvements that can happen, but is something for the future, in a different.

**Comment by sjorge** [comment]
I double checked everything is working as it should and shared _conform_value between both modules as they were nearly identical.

I also create a new issue for future code cleanup because this could use some love as wel: #44801

**Comment by sjorge** [comment]
One more bug to fix, I messed up while fixing some other stuff -_-

**Comment by sjorge** [comment]
Additional tests done

```yaml
mypool:
  zpool.present:
    - config:
        import: false
        force: true
    - properties:
        comment: another salty storage pool
    - layout:
        - /tmp/disk0
        - /tmp/disk1

mypool/shares/yuki:
  zfs.filesystem_present:
    - create_parent: true
    - properties:
        quota: 32mb
        copies: 2

mypool/iscsi/haruhi:
  zfs.volume_present:
    - create_parent: true
    - volume_size: 16M
    - sparse: true
    - properties:
        readonly: on

mypool/shares/yuki@frozen:
  zfs.snapshot_present

moka_origin:
  zfs.hold_present:
    - snapshot: mypool/shares/yuki@frozen

mypool/shares/moka:
  zfs.filesystem_present:
    - cloned_from: mypool/shares/yuki@frozen

'mypool/shares/moka@tsukune':
  zfs.snapshot_absent
```

Note the copies is now numeric and one of the quotes has the '32mb' style of notation, both of these caused issues before and are now fixed.

```
[root@carbon /opt/saltdev/lib/python2.7/site-packages]# /opt/saltdev/bin/salt-call --local --file-root=/opt/saltdev/etc/states state.sls zfs_test
[ERROR   ] Command '/usr/sbin/zpool list mypool' failed with return code: 1
[ERROR   ] stderr: cannot open 'mypool': no such pool
[ERROR   ] retcode: 1
[ERROR   ] Command '/usr/sbin/zpool list mypool' failed with return code: 1
[ERROR   ] stderr: cannot open 'mypool': no such pool
[ERROR   ] retcode: 1
[ERROR   ] Command '/usr/sbin/zfs list -H -t filesystem -o name,used,avail,refer,mountpoint mypool/shares/yuki' failed with return code: 1
[ERROR   ] stderr: cannot open 'mypool/shares/yuki': dataset does not exist
[ERROR   ] retcode: 1
[ERROR   ] Command '/usr/sbin/zfs list -H -t volume -o name,used,avail,refer,mountpoint mypool/iscsi/haruhi' failed with return code: 1
[ERROR   ] stderr: cannot open 'mypool/iscsi/haruhi': dataset does not exist
[ERROR   ] retcode: 1
[ERROR   ] Command '/usr/sbin/zfs list -H -t snapshot -o name,used,avail,refer,mountpoint mypool/shares/yuki@frozen' failed with return code: 1
[ERROR   ] stderr: cannot open 'mypool/shares/yuki@frozen': dataset does not exist
[ERROR   ] retcode: 1
[ERROR   ] Command '/usr/sbin/zfs list -H -t filesystem -o name,used,avail,refer,mountpoint mypool/shares/moka' failed with return code: 1
[ERROR   ] stderr: cannot open 'mypool/shares/moka': dataset does not exist
[ERROR   ] retcode: 1
[ERROR   ] Command '/usr/sbin/zfs list -H -t snapshot -o name,used,avail,refer,mountpoint mypool/shares/moka@tsukune' failed with return code: 1
[ERROR   ] stderr: cannot open 'mypool/shares/moka@tsukune': dataset does not exist
[ERROR   ] retcode: 1
local:
----------
          ID: mypool
    Function: zpool.present
      Result: True
     Comment: storage pool mypool was created
     Started: 13:25:19.651720
    Duration: 261.175 ms
     Changes:
              ----------
              mypool:
                  created
----------
          ID: mypool/shares/yuki
    Function: zfs.filesystem_present
      Result: True
     Comment: filesystem mypool/shares/yuki was created
     Started: 13:25:19.925723
    Duration: 264.045 ms
     Changes:
              ----------
              mypool/shares/yuki:
                  ----------
                  quota:
                      33554432
                  copies:
                      2
----------
          ID: mypool/iscsi/haruhi
    Function: zfs.volume_present
      Result: True
     Comment: volume mypool/iscsi/haruhi was created
     Started: 13:25:20.190562
    Duration: 161.767 ms
     Changes:
              ----------
              mypool/iscsi/haruhi:
                  ----------
                  readonly:
                      on
----------
          ID: mypool/shares/yuki@frozen
    Function: zfs.snapshot_present
      Result: True
     Comment: snapshot mypool/shares/yuki@frozen was created
     Started: 13:25:20.353108
    Duration: 124.932 ms
     Changes:
              ----------
              mypool/shares/yuki@frozen:
                  snapshotted
----------
          ID: moka_origin
    Function: zfs.hold_present
      Result: True
     Comment: hold moka_origin added to mypool/shares/yuki@frozen
     Started: 13:25:20.478519
    Duration: 124.566 ms
     Changes:
              ----------
              moka_origin:
                  held
----------
          ID: mypool/shares/moka
    Function: zfs.filesystem_present
      Result: True
     Comment: filesystem mypool/shares/moka was created
     Started: 13:25:20.603513
    Duration: 246.777 ms
     Changes:
              ----------
              mypool/shares/moka:
                  cloned from mypool/shares/yuki@frozen
  Name: mypool/shares/moka@tsukune - Function: zfs.snapshot_absent - Result: Clean Started: - 13:25:20.851048 Duration: 64.463 ms

Summary for local
------------
Succeeded: 7 (changed=6)
Failed:    0
------------
Total states run:     7
Total run time:   1.248 s
[root@carbon /opt/saltdev/lib/python2.7/site-packages]# /opt/saltdev/bin/salt-call --local --file-root=/opt/saltdev/etc/states state.sls zfs_test
[ERROR   ] Command '/usr/sbin/zfs list -H -t snapshot -o name,used,avail,refer,mountpoint mypool/shares/moka@tsukune' failed with return code: 1
[ERROR   ] stderr: cannot open 'mypool/shares/moka@tsukune': dataset does not exist
[ERROR   ] retcode: 1
local:
  Name: mypool - Function: zpool.present - Result: Clean Started: - 13:25:34.234753 Duration: 140.178 ms
  Name: mypool/shares/yuki - Function: zfs.filesystem_present - Result: Clean Started: - 13:25:34.379551 Duration: 127.476 ms
  Name: mypool/iscsi/haruhi - Function: zfs.volume_present - Result: Clean Started: - 13:25:34.507751 Duration: 128.05 ms
  Name: mypool/shares/yuki@frozen - Function: zfs.snapshot_present - Result: Clean Started: - 13:25:34.636533 Duration: 70.876 ms
  Name: moka_origin - Function: zfs.hold_present - Result: Clean Started: - 13:25:34.707806 Duration: 65.989 ms
  Name: mypool/shares/moka - Function: zfs.filesystem_present - Result: Clean Started: - 13:25:34.774207 Duration: 196.934 ms
  Name: mypool/shares/moka@tsukune - Function: zfs.snapshot_absent - Result: Clean Started: - 13:25:34.971560 Duration: 66.345 ms

Summary for local
------------
Succeeded: 7
Failed:    0
------------
Total states run:     7
Total run time: 795.848 ms
```

**Comment by sjorge** [comment]
Lets kick of jenkins again as one of the test nodes keeps failing to bootstrap...

**Comment by rallytime** [comment]
@sjorge Yeah, we've been having some trouble with Jenkins lately and have been working on fixing those issues. Looks like this latest run is going better. 👍

**Comment by sjorge** [comment]
Some new unrelated tests are now failing :/

**Comment by sjorge** [comment]
Still 2 test failures but they don't show test failures, I guess just missing a few reviewers.

**Comment by rallytime** [comment]
We are still working on ironing out the failures. I checked some of the other runs. This is OK from a test perspective now. I'll review this first thing tomorrow. Thank you @sjorge, as always. :)

**Review by rallytime — APPROVED** [review]

**Pull request merged**
