### PR TITLE
Allow for additional module validation functions.

### PR DESCRIPTION
**Pull request by cachedout**
- Enforces validation on load for beacons.

Refs #34434

### CODE REVIEW

**Comment by cro** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
`__validate__()` for consistency with the loader related functions?

**Comment by cachedout** [comment]
@s0undt3ch Yes. Great idea! Let's do it.

**Comment by cachedout** [comment]
@s0undt3ch OK, done! :]

**Comment by s0undt3ch** [comment]
There are several calls to `validate` on some(all?) beacons which is, of course, no a function available anymore...

**Comment by cachedout** [comment]
Ack. I can't believe I missed that. Thanks, @s0undt3ch. I'll take care of it.

**Comment by s0undt3ch** [comment]
Now, why would you need to call validate internally? In case config changes?

**Comment by cachedout** [comment]
I thought about that. My main reason for leaving it in was to allow a facility for people to validate configs (if they want) if they're testing the beacon and/or using it in some manner without the salt loader. That said, I'm totally open to just removing it and having the loader do the whole thing.

**Comment by s0undt3ch** [comment]
If they were present before, we should leave them to avoid breakage. However, once validated and loaded by the loader.... ;)

**Comment by cachedout** [comment]
@s0undt3ch Right. I'm thinking we leave these in for a release or two and then consider moving them back out.

**Comment by s0undt3ch** [comment]
:+1:

I don't know what are the current known test failures or I'd merge this...

**Pull request merged**
