### PR TITLE
fix proxy tests for py3 on 2017.7

### PR DESCRIPTION
**Pull request by gtmanfred**
### What issues does this PR fix or reference?
Fixes saltstack/salt-jenkins#678

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by rallytime** [comment]
@gtmanfred Lint: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/17959/violations/file/tests/support/parser/__init__.py/

**Comment by gtmanfred** [comment]
ha, yeah that would break the test suite.

**Comment by rallytime** [comment]
re-run py

**Comment by gtmanfred** [comment]
re-run py

**Review by rallytime — APPROVED** [review]

**Pull request merged**
