### PR TITLE
CSF State Modules and CSF Remote Modules fixes

### PR DESCRIPTION
**Pull request by Nerigal**
### What issues does this PR fix or reference?
Fixed Random ports ordering on execution 
Fixed compatibly with csf port range feature 
Fixed syntax errors
Fixed the behavior where test=true parameter was ignored

Change applied for both `csf.py`state module and remote module 

### Previous Behavior
Execution of csf state module was never compliant since the ordering was random on every execution 

### New Behavior
No changes applied if the port list haven't changed 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by Nerigal** [comment]
re-run ci/py3/ubuntu1604

**Comment by Nerigal** [comment]
re-run ubuntu1604

**Comment by Nerigal** [comment]
re-run fedora29

**Comment by sagetherage** [comment]
@Nerigal we are no longer taking changes against the `develop` branch, can you rebase this against `master` please?

**Pull request closed without merging**
