### PR TITLE
Upload coverage reports on full test runs

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
Updates CI jobs to upload coverage reports on full test runs

### CODE REVIEW

**Review by dwoz — APPROVED** [review]
Sweet, can wait for the test to pass so we can merge this! :D

**Comment by pullit** [comment]
Seems there is a broken UT: unit.modules.test_kubernetesmod.KubernetesTestCase.test_setup_client_key_file

**Comment by s0undt3ch** [comment]
Needs #52705 to pass

**Comment by dwoz** [comment]
This will also need #52728 for the last failure

**Pull request merged**
