### PR TITLE
Initial openstack pull request to move to shade

### PR DESCRIPTION
**Pull request by gtmanfred**
### What does this PR do?

Begin moving openstack stuff over to using the shade library.
### Tests written?

No

### CODE REVIEW

**Comment by techhat** [comment]
Sweet!

**Comment by gtmanfred** [comment]
I am going to work on fixing the tests tomorrow

**Comment by gtmanfred** [comment]
still working on updating these unittests

**Comment by cachedout** [comment]
How we coming along on this one @gtmanfred ?

**Comment by gtmanfred** [comment]
I am going to close the PR, i need to finish cleaning up the tests and I think it is going to take a bit longer, cause I am waiting for a 2015.5 merge forward for glance and swift so that I can have shade on the jenkins servers for the testing suite.

**Pull request closed without merging**
