### PR TITLE
2014.7: Fix Batching

### PR DESCRIPTION
**Pull request by jacksontj**
Backport #22350 to 2014.7 as well.

### CODE REVIEW

**Comment by thatch45** [comment]
@jacksontj these test failures don't look like timing issues, can you please comment?

**Comment by jacksontj** [comment]
Yea, it seems that glob does some magic regarding sorting the list before it gets handed back. These tests should only check that the sets are equivalent, not that they are in the same order. I've updated the tests :)

**Comment by jfindlay** [comment]
@jacksontj (@rallytime), there are some new [lint errors](https://jenkins.saltstack.com/view/2015.2%20Branch/job/salt-2015.2-lint/418/violations/) on the 2015.2 and develop branches that are related to tornado code.  Do you have any ideas on how to fix them?  Thanks.

**Comment by jacksontj** [comment]
@jfindlay Yea, I noticed those-- its odd that they all of a sudden show up :/ Well, I've opened #22555 to fix the lint error

**Comment by jfindlay** [comment]
Thanks man.

**Pull request merged**
