### PR TITLE
Port #52756 to master

### PR DESCRIPTION
**Pull request by terminalmage**
See #52756

### CODE REVIEW

**Review by s0undt3ch — DISMISSED** [review]

**Comment by waynew** [comment]
Looked at this for a few minutes during the Testing WG 2021-06-03 - at least with the `prepare` function it looks like maybe we had solved that problem in a different way(?) Probably need to take a closer look. Also found a block of code in `salt/_logging/handlers` that should just be flat out removed (only used on Python <3.2, which is no longer supported). That should probably be part of another effort(?)

**Comment by Ch3LL** [comment]
@terminalmage would you mind adding a changelog

Also 
@waynew its not clear to me if your statement is blocking the merge of this PR or not?
And @s0undt3ch you still okay with this change since its been a while since your previous approval?

**Comment by terminalmage** [comment]
@Ch3LL done

**Comment by s0undt3ch** [comment]
We no longer use queue handlers.

**Comment by s0undt3ch** [comment]
And logging going forwards is in `salt/_logging` the old log stuff is in deprecation.

**Comment by Ch3LL** [comment]
thanks @s0undt3ch you okay closing this then @terminalmage ?

**Comment by terminalmage** [comment]
Of course!

**Pull request closed without merging**
