### PR TITLE
mount.mounted better mkmnt & test output

### PR DESCRIPTION
**Pull request by The-Loeki**
State mount.mounted: improved (and actual) fix for #14778, minor improvements to test handling & output.
`mount.mount` should already deal with `mkmnt` when `mount` is `True`, so we only need to deal with `file.mkdir` if you chose _not_ to mount (which is what #14778 was all about).

### CODE REVIEW

**Comment by cachedout** [comment]
@The-Loeki Could you please take a look at the failing test?

**Comment by The-Loeki** [comment]
@cachedout should be better now, let's see what Jenkins thinks about it. 

It does expose the limited testing coverage, but as I tried to fix that I ran into serious problems. I really need to learn these tests better :/

**Comment by The-Loeki** [comment]
Don't think the Tornado error thingy is my fault there?

**Comment by rallytime** [comment]
@The-Loeki the tornado error is a known flaky test that we're working on cleaning up.

Thank you for your work here!

**Pull request merged**
