### PR TITLE
loader uses a deep dictionary merge for the grains (core and customs)

### PR DESCRIPTION
**Pull request by dr4Ke**
This is a fix for #27881
I must say that I didn't write any unit or integration test for this change, and I don't know about the performance impact.

### CODE REVIEW

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
While this behavior does seem better, I'm a little concerned that this is going to produce surprising results for people during an upgrade. Before we merge this, I think we need to (at a minimum) config-gate this and allow people an option to restore the previous behavior as well as fully document this change in release notes. I would also like to see some tests because this is very critical functionality. Thoughts?

**Comment by dr4Ke** [comment]
I totally agree. Moreover, maybe this use case is not so common that it should be the default behavior. What about adding an option to enable deep merge for the grains, leaving the standard update as the default? This way, we won't have unexpected side effects.
I agree some tests need to be written, but I don't know how/where.

I'll try to work on these points in the next days. In the meanwhile, if anyone has suggestions…

**Comment by dr4Ke** [comment]
What do you think @yannis666?

**Comment by yannis666** [comment]
I would be happy for this to be configurable behavior. Personally I think the new behavior is more natural, but, for backward compatibility reasons and efficiency am happy with having to specify this.

**Comment by cachedout** [comment]
That works for me. @dr4Ke please let me know when this PR is ready to go. Thanks for your hard work on this. It's very much appreciated.

**Comment by dr4Ke** [comment]
Some work on this. Introducing a new minion configuration option `grains_deep_merge`, and related documentation.
What do you think about it?
I'll still have to write some tests for this PR.

**Comment by yannis666** [comment]
Sorry for my unfamiliarity  of the process. Is there a particular branch I
should look at?

**Comment by dr4Ke** [comment]
@yannis666 if you want to test this before it's properly released, you can apply the last commits of my dedicated branch at https://github.com/dr4Ke/salt/tree/custom_grains_deep_merge
Beware that the actual implementation may differ from this work in progress and/or cause unexpected issues.

**Comment by cachedout** [comment]
@dr4Ke This approach looks great!  Let me know when you're ready to go on this one and we'll get it in. Thanks for your hard work here.

**Comment by cachedout** [comment]
@dr4Ke How are we looking on this one? Let me know if there is anything we can do to help. Thanks!

**Comment by dr4Ke** [comment]
I'm just short in spare time these days. I think I can finish this work this weekend. Is that ok?

**Comment by cachedout** [comment]
@dr4Ke Of course. Thank you!

**Comment by dr4Ke** [comment]
I wrote a test for the standard behavior. I don't know how to force the loader to refresh custom grains with the option ``grains_deep_merge`` on. Do you have an idea?

**Comment by dr4Ke** [comment]
I pushed one of the way I tested for the deep merge test. It's not working, I just don't see how to reload the grains with this option enabled. If you have suggestions, I'd love to read them.

**Comment by jfindlay** [comment]
@dr4Ke, the test suite isn't very flexible regarding local/live changes to the daemon configs.  I have investigated this issue with the possibility of rerunning the loader.grains function with the updated configs, but so far haven't gotten it to succeed.  In the end it is going to be a hack even if we could get it to work.  I would say that a manual verification of both options is fine and we can auto test the backwards compatible version.  I, and I am sure @s0undt3ch, have many ideas to improve and expand the scope and of the automated tests, in which daemon config modifications can be incorporated into individual tests if necessary.

**Comment by s0undt3ch** [comment]
As @jfindley pointed out, yes, I have lots of ideas to improve Salt's test suite. Out of necessity, the first step is being done right now, which is creating a Salt py.test plugin and its being coded in such a way that we'll be able to start another salt-master and salt-minion just for a test case or a batch of tests. However, it will take quite a while for that py.test plugin to land on Salt's test suite since, even after that part is done, the whole test suite will need to be revised and migrated to py.test. As you can imagine, a TON of work...

Anyway, this is just to say that we're aware that our test suite needs to be more flexible and allow broader ways to test Salt. The work for that has started, but right now, we'll need to add this specific case to the manual testing routines....

**Comment by cachedout** [comment]
@dr4Ke Could you rebase this please? I would like to try and get this merged this week. Apologies for letting this sit so long.

**Comment by cachedout** [comment]
@dr4Ke Looks like you need to import that skipIf first: `from salttesting.unit import skipIf`

**Comment by dr4Ke** [comment]
Ouch. Sorry, I didn't try it before pushing.

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
This is a pretty big change to back-port, and unfortunately it doesn't back-port cleanly based on some updates to the init file for the integration tests. Specifically, there is functionality being used there that doesn't exist in older branches. As such, I won't be back-porting this change. 

If this fix needs to go into an earlier branch, then a separate fix will need to be applied there.

**Comment by yannis666** [comment]
I can't tell from this where the merge went to, but looking at the 2015.8 branch I can't see the change. How can I tell which release this is targeted at?

**Comment by rallytime** [comment]
@yannis666 This pull request is not in the 2015.8 branch. It will, however, be available in the next feature release, which will be 2016.3.0. The 2016.3 branch is in the release candidate testing process right now.

**Pull request merged**
