### PR TITLE
Redact HTTPS Basic Auth in states/funcs which deal with git remotes

### PR DESCRIPTION
**Pull request by terminalmage**

### CODE REVIEW

**Comment by terminalmage** [comment]
@rallytime I'll work with you on Friday to get this backported to 2015.5. I'll handle integrating these commits into that branch, since the code has changed significantly and I am most familiar with it at this point.

**Comment by terminalmage** [comment]
Backport done in https://github.com/saltstack/salt/pull/26726

**Comment by s0undt3ch** [comment]
There's conflicts that need to be resolved, sorry.

**Comment by terminalmage** [comment]
@s0undt3ch rebased

**Comment by s0undt3ch** [comment]
Awesome!

**Pull request merged**
