### PR TITLE
zpool.present: Fix wrong output in test=true run

### PR DESCRIPTION
**Pull request by L4rS6**
### What does this PR do?
zpool.present: Fix wrong output in test=true run

### Previous Behavior
Each run changes were shown:
----------
          ID: zpool_mypool
    Function: zpool.present
        Name: zmysql
      Result: True
     Comment: storage pool mypool was uptodate
     Started: 16:34:24.952043
    Duration: 56.853 ms
     Changes:
              ----------
              mypool:
                  uptodate

### New Behavior
----------
          ID: zpool_mypool
    Function: zpool.present
        Name: mypool
      Result: True
     Comment: storage pool mypool is uptodate
     Started: 11:58:46.006742
    Duration: 139.97 ms
     Changes:

### Tests written?
No

### Commits signed with GPG?
No

### CODE REVIEW

**Review by twangboy — APPROVED** [review]

**Comment by twangboy** [comment]
Could we get some tests for this?

**Comment by L4rS6** [comment]
> Could we get some tests for this?

Done. Added unit test for zpool.present in with test=true

**Review by twangboy — APPROVED** [review]

**Comment by L4rS6** [comment]
Can please somebody approve this, so it gets merged?

**Comment by Ch3LL** [comment]
we had some issues with the doc and lint tests the other day. restarting the tests and then we can merge when they are all green :) i plan on branching neon today, so I will migrate this to that branch when its created so we can ensure its included in that release

**Comment by Ch3LL** [comment]
FYI I migrated this PR from develop to neon to ensure it is included in the upcoming neon release. Let me know if this caused any issues. Thanks

**Comment by L4rS6** [comment]
> FYI I migrated this PR from develop to neon to ensure it is included in the upcoming neon release. Let me know if this caused any issues. Thanks

Thank you @Ch3LL Could you please merge this fix into 2019.2 branch as well?

**Review by Ch3LL — APPROVED** [review]

**Comment by Ch3LL** [comment]
@L4rS6 I went ahead and added the bugfix label and in the next week it will get backported to that branch. thanks :)

**Comment by L4rS6** [comment]
Could this pull request please be merged again? It's still not fixed in the latest 2019.2.2 release and I also can't find the change in the current master branch.

**Pull request merged**
