### PR TITLE
Set default Salt Master address for a Syndic (like for a Minion)

### PR DESCRIPTION
**Pull request by vutny**
### What does this PR do?
A Salt Minion is always coming up from the cold start with default Master address set as `salt`. That's how you can add hosts to your Salt infrastructure with minimum configuration (except of setting resolver properly of course).

But currently that's not the case with Salt Syndic, because `syndic_master` default value is undefined.

### What issues does this PR fix or reference?
Setting default "Master of Masters" address for Syndic allows to install and use it right out-of-the-box in easy way, just with making proper changes to a local DNS.

### Previous Behavior
Salt Syndic fails to start:
```
[ERROR   ][564] Master address: 'unknown address' could not be resolved.
Invalid or unresolveable address. Set 'syndic_master' value in minion config.
```

### New Behavior
Salt Syndic works right after the installation.

### Tests written?
No

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @vutny 

This seems reasonable but since it doesn't address a specific bug, I would prefer that we introduce it in the next major release instead of as a bug fix in the 2016.3 branch. Thoughts?

**Comment by vutny** [comment]
@cachedout Yeah, I didn't fill out an issue, but actually this affects the Salt Bootstrap usage experience.
For example, if you just try to install Syndic without any kind of pre-configuration steps, it results to the error:
```bash
# sh bootstrap-salt.sh -D -N -S -s 10 stable 2016.3
...
 *  INFO: Running install_centos_restart_daemons()
 * DEBUG: Waiting 10 seconds for processes to settle before checking for them
Starting salt-syndic daemon:                               [  OK  ]
 *  INFO: Running daemons_running()
 * DEBUG: Waiting 10 seconds for processes to settle before checking for them
 * ERROR: salt-syndic was not found running
 * ERROR: Failed to run daemons_running()!!!
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Guessing ID. The id can be explicitly set in /etc/salt/minion
[DEBUG   ] Found minion id from generate_minion_id(): c5-sysv
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Syndic Minion "c5-sysv"
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[INFO    ] Creating minion process manager
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Guessing ID. The id can be explicitly set in /etc/salt/minion
[DEBUG   ] Found minion id from generate_minion_id(): c5-sysv
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Created pidfile: /var/run/salt-syndic.pid
[WARNING ] IMPORTANT: Do not use md5 hashing algorithm! Please set "hash_type" to sha256 in Salt Syndic config!
[INFO    ] The Salt Syndic is starting up
[DEBUG   ] Syndic 'c5-sysv' trying to tune in
[DEBUG   ] sync_connect_master
[DEBUG   ] Connecting to master. Attempt 1 of 1
[ERROR   ] Master address: 'unknown address' could not be resolved. Invalid or unresolveable address. Set 'syndic_master' value in minion config.
...
```

But other Salt components work just fine with their defaults. So, I think it would be really nice to have the default value set in the future point releases.

**Comment by thatch45** [comment]
I really like this, but if we default this to `salt` then logically it will just connect to the master that the syndic is running on. I would suggest making the dns name `masterofmasters` or `syndicsalt` or `syndicmaster`

**Comment by vutny** [comment]
@thatch45 Thanks for the support!

Sure, the actual name is not really a problem, we just need something to be set for Syndic to be able to start and try to connect to higher master. Let's stay with `masterofmasters`, because it was set in the example config previously. I'll adjust my PR accordingly.

**Comment by cachedout** [comment]
@vutny I'll get this in once the tests run. Thanks for working with us on this one! Much appreciated.

**Pull request merged**
