### PR TITLE
Add "disabled" support

### PR DESCRIPTION
**Pull request by jacksontj**
this allows you to "blacklist" modules.

Addition to #20274

### CODE REVIEW

**Comment by jfindlay** [comment]
@jacksontj, there are a plethora of failed tests.  Do you mind rebasing on upstream to see if this removes most (all) of them?  Thanks.

**Comment by jacksontj** [comment]
Sure, just rebased :)

**Comment by jacksontj** [comment]
Still broken, but the failures definitely look unrelated. I guess I'll just wait a bit for someone to fix develop ;)

**Comment by jfindlay** [comment]
Yeah, a big merge forward came in right before you rebased.

**Comment by jfindlay** [comment]
I don't want to sound picky, but would you mind rebasing once more?  Thanks.

**Comment by jacksontj** [comment]
@jfindlay Actually looks like I had a commit in here that didn't belong. This should work now ;)

**Comment by jacksontj** [comment]
@jfindlay There we go, passes now :)

**Comment by jfindlay** [comment]
@jacksontj, woohoo, nice!

**Comment by jacksontj** [comment]
Can we merge this one in? Just want to make sure it goes in before #20481

**Comment by jfindlay** [comment]
@jacksontj, sure.  I'm not familiar with the code that this changes, so I'll defer to @cachedout or @thatch45 for the secondary review, but the preliminary checks look good.  Today we started triaging pull requests as you can see.  Let us know if you have any feedback.  Mainly this is to take some load off @thatch45, but also a little more process here should help with our engineering stability.

**Comment by jacksontj** [comment]
fine with me ;) @cachedout has been taking a lot of my PRs lately ;)

**Comment by jacksontj** [comment]
@cachedout ping :)

**Comment by cachedout** [comment]
Sorry for the delay @jacksontj. Thanks this looks great!

**Pull request merged**
