### PR TITLE
initial xml module/state

### PR DESCRIPTION
**Pull request by mchugh19**
### What does this PR do?
Adds new xml module to query/modify basic xml elements from an XPath query

### New Behavior
Given the file:
```
<root xmlns:foo="http://www.foo.org/" xmlns:bar="http://www.bar.org">
	<actors>
		<actor id="1">Christian Bale</actor>
		<actor id="2">Liam Neeson</actor>
		<actor id="3">Michael Caine</actor>
	</actors>
	<foo:singers>
		<foo:singer id="4">Tom Waits</foo:singer>
		<foo:singer id="5">B.B. King</foo:singer>
		<foo:singer id="6">Ray Charles</foo:singer>
	</foo:singers>
</root>
```

The following functionality is implemented:
get/set attributes
```
# salt-call xml.get_attribute /tmp/test.xml ".//actor[@id='3']"
local:
    ----------
    id:
        3

# salt-call xml.set_attribute /tmp/test.xml ".//actor[@id='3']" edited "uh-huh"
local:
    True

# salt-call xml.get_attribute /tmp/test.xml ".//actor[@id='3']"
local:
    ----------
    edited:
        uh-huh
    id:
        3
```

get/set values
```
# salt-call xml.get_value /tmp/test.xml ".//actor[@id='2']"
local:
    Liam Neeson

# salt-call xml.set_value /tmp/test.xml ".//actor[@id='2']" "Patrick Stewart"
local:
    True

# salt-call xml.get_value /tmp/test.xml ".//actor[@id='2']"
local:
    Patrick Stewart
```

It's pretty simplistic, but if this seems to be a good direction to go, it can form the foundation for a matching xml state to search/replace values.

### Tests written?
Yes

### Commits signed with GPG?
No

### CODE REVIEW

**Review by cachedout — COMMENTED** [review]
I like this! I do think that we should add information about this to the release notes prior to merging it, however.

**Comment by cachedout** [comment]
Additionally, there are two lint errors that need to be fixed before we can merge this:

https://jenkinsci.saltstack.com/job/pr-lint/job/PR-49822/3/warnings52Result/new/

**Comment by mchugh19** [comment]
Short blurb added to the release notes. However, if it's release note worthy, then this should really have an accompanying state to perform file.line or file.replace type functions. I'll take a stab at that when able.

**Comment by dwoz** [comment]
Great work here. Any chance we can get some test coverage for this?

**Comment by mchugh19** [comment]
@dwoz there are tests on the module. Do you mean the state as well? As it just calls the module, do you have a suggestion?

**Comment by rallytime** [comment]
@mchugh19 Yes, state tests would be very welcome. :)

Looks like there is also a merge conflict here with the release notes. Can you rebase this when you're ready with some more tests?

**Review by cachedout — APPROVED** [review]

**Comment by cachedout** [comment]
@dwoz Can you come by and review this, please? Thanks.

**Comment by rallytime** [comment]
@dwoz bump :)

**Review by dwoz — APPROVED** [review]

**Pull request merged**
