### PR TITLE
Inspector: enable Ubuntu/Debian!

### PR DESCRIPTION
**Pull request by isbm**
The [Salt Inspector](http://docs.saltstack.com/en/develop/ref/modules/all/salt.modules.node.html) is now working on Debian/Ubuntu!
- Brings all the functionality as on RPM distros
- Fixes many small cross-platform bugs
- Minor cleanups

P.S. Sometimes it is needed `os.popen(...)` instead of `__salt__['cmd.run](...)` as the latter is not needed and is even not there.

### CODE REVIEW

**Comment by jfindlay** [comment]
@isbm, there are some [lint errors](https://jenkins.saltstack.com/job/salt-pr-lint-n/7432/violations/).

**Comment by isbm** [comment]
@jfindlay The [E0598](https://github.com/saltstack/salt-pylint/blob/master/saltpylint/minpyver.py#L35) is quite odd here. Should we **entirely ban** the entire `importlib` from everywhere just because is not used in 2.6 which is [very dead](https://mail.python.org/pipermail/python-dev/2013-September/128287.html) anyway??

I made the try/except to support the 2.6, but not using the `importlib` in Python 3 is just a no go.

**Comment by jfindlay** [comment]
@isbm, your change handles the case when importlib is not available, so there should be no issue.  Python 2.6 may be dead but, unfortunately, CentOS 5 is not, so we need to continue to support 2.6.

**Comment by bechtoldt** [comment]
Just a personal interest:

@isbm what exactly is this inspector thing doing and why does it provide features that are already available in Salt (query system infos)?

**Comment by isbm** [comment]
@bechtoldt No, Salt provides only a smaller part of it, but does not provide you e.g. diff between vendor config file and actual etc (well, with the Inspector now it does) or does not tracks non-packaged files etc. Also Salt did not provided expanded system info, such as external mounts etc. In general, the inspector is a clone of our [Machinery](http://machinery-project.org/) and if everything sticks together, Salt will be a main part of our new [SUSE Manager 3](https://www.suse.com/products/suse-manager/). The Inspector will be soon expanded with Kiwi support and other things, so it is going to be used for provisioning new systems, based on other machines/configs etc.

Hope that helps.

**Comment by isbm** [comment]
@jfindlay I have no problems with the 2.6, we are still have SLES 10 around, imagine that! But nevertheless, my concerns were just about banning the `importlib`. However, I see we are in the agreement... :smiley:

**Pull request merged**
