### PR TITLE
Update quickstart.rst

### PR DESCRIPTION
**Pull request by becker**
### What does this PR do?
Download and execute the bootstrap salt minion script in just one line.

### CODE REVIEW

**Comment by garethgreenaway** [comment]
@becker Thanks for the PR.  I think we should include both examples, some people might want to investigate the contents of the bootstrap script or using it again later.

**Comment by Ch3LL** [comment]
I'm in favor of just keeping the example as it is, since we don't want to encourage users to run scripts without inspecting the contents first.

**Comment by Ch3LL** [comment]
I'm coming back to this. I'm okay adding both examples as long as we call out that the preferred method is to download the script and inspect the contents. @becker are you willing to implement this?

**Comment by becker** [comment]
Sure @Ch3LL! Maybe also add some checksum verification instructions using the URL https://bootstrap.saltproject.io/sha256?

**Comment by Ch3LL** [comment]
Yeah that would be great :) thanks

**Comment by MKLeb** [comment]
@becker any updates on keeping both examples here?

**Comment by becker** [comment]
Hello!

Sorry for the delay @MKLeb. I updated the file by adding the alternative option to download and execute the script in just one line, like in the [salt-bootstrap documentation](https://docs.saltproject.io/salt/install-guide/en/latest/topics/bootstrap.html#install-using-the-bootstrap-script).

**Review by MKLeb — DISMISSED** [review]

**Comment by MKLeb** [comment]
@becker Thanks for coming back to this.  Could you add some text about verifying with SHA256, and maybe also mentioned that the original method is preferred?

**Comment by becker** [comment]
Hi @MKLeb! Sorry, I totally forgot about the checksum verification. I made some changes, hope it didn't get too complicated.

**Review by garethgreenaway — APPROVED** [review]

**Review by MKLeb — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
