### PR TITLE
adding augeas_cfg unit test case

### PR DESCRIPTION
**Pull request by jayeshka**
Hi @rallytime , Please review the augeas_cfg_test case and let me know if you have any review comments.

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
@jayeshka all of these tests seem to be failing:
https://jenkins.saltstack.com/job/salt-pr-dsl/443/#showFailuresLink

**Comment by jayeshka** [comment]
Hi,
I added check for augeas python package.
As, for this test case to run python-augeas package is required.
Thank you for the comments.

**Comment by thatch45** [comment]
Thanks @jayeshka !

**Pull request merged**
