### PR TITLE
Enable salt-cloud bootstrap with ssh gateway

### PR DESCRIPTION
**Pull request by sjansen**
Also submitted to develop: https://github.com/saltstack/salt/pull/19717

### CODE REVIEW

**Comment by thatch45** [comment]
@techhat please review
We should only need this PR since it will be merge forwarded into develop

**Comment by techhat** [comment]
@sjansen, why the rename?

**Comment by sjansen** [comment]
Because that's what salt/utils/cloud.py expects. I tried to trace the git history to discover at what point this was broken, but it looks like it may never have worked before. Instead, perhaps, it just wasn't considered as part of 77bdfc4.

**Comment by thatch45** [comment]
Ahh, I get it, the mentioned commit did not test any use case outside of itself. So this change from @sjansen opens up the capability beyond just the lxc cloud driver

**Comment by techhat** [comment]
Cool, thanks for getting that @sjansen.

**Pull request merged**
