### PR TITLE
Fix state apply in test mode with file state module on user/group checking

### PR DESCRIPTION
**Pull request by vzhestkov**
### What does this PR do?

This is a follow up PR to https://github.com/saltstack/salt/pull/61847
The PR was fixing only `file.directory` state function while there are 3 more affected functions with the same issue: `file.managed`, `file.copy`, `file.recurse`. All of them are using `_check_user`.

This PR is fixing `_check_user` with writing a warning to the log instead of failing in case if the state is applied in a test mode.

### Previous Behavior
If the state file contains user/group creation and one of the mentioned functions after with setting user/group ownership ot a file or directory, the state is failing while apply in a test mode, but not failing with normal state apply.

### New Behavior
Do not fail on mentioned case, but write a warning to the log.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by Ch3LL** [comment]
@nicholasmhughes can you review please

**Comment by Ch3LL** [comment]
it looks like the mac test failures might be related to this PR

**Review by nicholasmhughes — APPROVED** [review]
:+1:

**Comment by vzhestkov** [comment]
@Ch3LL I think no, these failing tests are not related to the fix as the fix is only affecting certain `file` state functions, which are not used in these tests.

**Comment by MKLeb** [comment]
I merged in the latest master changes, if the mac tests are still failing I think we will need to investigate more.

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
