### PR TITLE
Mod state error handling

### PR DESCRIPTION
**Pull request by dirgapeter**
What does this PR do?

Fixes error handling for function _check_pillar. _check_pillar returns True/False if pillar parameter
contains errors. If None is passed it substitutes __pillar__. Check for return value of _check_pillar
is ok, but additional error info is sometimes taken from param sometimes from __pillar__. It causes
following error in real scenarios (but not test suite):

```
$ salt-run state.orch orch.ls pillar='{"region": "na-us-1", "project": "test01"}' saltenv=develop pillarenv=develop
[ERROR   ] Run failed on minions: ls01.test01.na-us-1
Failures:
    ls01.test01.na-us-1:
        The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1445, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1021, in sls
        err += __pillar__['_errors']
      File "/usr/lib/python2.7/site-packages/salt/utils/context.py", line 211, in __getitem__
        return self._dict()[key]
    KeyError: '_errors'
```

What issues does this PR fix or reference?

Found while using orchestration runner with error in pillar.

Tests written?

Yes (changed old ones)

Commits signed with GPG?

Yes

### CODE REVIEW

**Review by terminalmage — APPROVED** [review]

**Comment by terminalmage** [comment]
It looks like https://github.com/saltstack/salt/pull/44648 is also trying to fix this, and I believe that the approach in that PR is better. The only condition where we'd set the retcode is if we already have errors, so no need to return two values from that function.

**Comment by dirgapeter** [comment]
https://github.com/saltstack/salt/pull/44648 looks ok.

**Comment by rallytime** [comment]
@dirgapeter The fix in #44621 was the PR that addresses this in the `2017.7` branch. (I think it caused the merge conflicts here.) Are the changes in this PR still needed?

**Comment by dirgapeter** [comment]
nope, i will close this PR. thnx for info.

**Comment by rallytime** [comment]
@dirgapeter Sounds good. Thank you!

**Pull request closed without merging**
