### PR TITLE
Reduce duplicate code

### PR DESCRIPTION
**Pull request by dmyerscough**
### What does this PR do?

Improves the consul module with multiple bug fixes
### What issues does this PR fix or reference?

Using this module caused a few issues that made me re-write it
### Previous Behavior

Remove this section if not relevant
### New Behavior

Remove this section if not relevant

Same behavior 
### Tests written?

Yes

### CODE REVIEW

**Comment by cachedout** [comment]
Nice!

There's some lint issues and a function that needs documentation added. After that, I'll take a close look and try to get this in. Thanks, @dmyerscough !

**Comment by dmyerscough** [comment]
I'll take a look at this shortly, what function needs documented?

**Comment by cachedout** [comment]
@dmyerscough Docs error is from here: http://166.78.178.63:8080/job/PR/job/salt-pr-linode-ubuntu14-n/1481/testReport/junit/integration.modules.sysmod/SysModuleTest/test_valid_docs/

**Comment by cachedout** [comment]
Hi @dmyerscough let me know if you don't have time to add this and we'll toss it in for you. Thanks!

**Comment by dmyerscough** [comment]
Hey @cachedout sorry, I have been pretty busy for the past few days.. Ill try get to this at the weekend when I get some free time :)

**Comment by cachedout** [comment]
@dmyerscough No pressure. Just checking in with you. Thanks!

**Comment by dmyerscough** [comment]
Is there a way to kick of the checks again so I can see the violations

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@dmyerscough Done. (The phrase in the above comment will automatically restart tests.)

**Comment by cachedout** [comment]
@dmyerscough Just these to clean up and then we should be ready to go: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/2060/violations/file/salt/modules/consul.py/

**Comment by cachedout** [comment]
Bump @dmyerscough on my most recent comment. Thanks!

**Comment by dmyerscough** [comment]
@cachedout sorry I have been super busy at work and haven't been able to look at this

**Comment by garethgreenaway** [comment]
Looking through the diff, I see you removed the consul_url from all the functions?   Curious what the motivation on that was.  Also renamed a lot of the parameters, some of them make sense but changing existing functionality is a major change and could break existing usage.

**Comment by cachedout** [comment]
Hi @dmyerscough Just another bump here. Wondering if you've had time to come back to this. We'll need a rebase here and it looks like @garethgreenaway had some feedback as well. Thanks very much.

**Comment by dmyerscough** [comment]
Hi @cachedout my pull request fixed some issue I found but didn't file individual issues. I changed a lot due to some bugs that I ran into hence why I did a big rewrite.

In regards to `consul_url`, I removed this because I thought it was just easier reading from the Salt minion config.

**Comment by dmyerscough** [comment]
Also there was a lot of copy and paste in the module where two functions named differently would do the same thing.. Comments were also confusing as they were copied and pasted.

**Comment by cachedout** [comment]
@dmyerscough We just need a rebase here since there are now merge conflicts and then we can put this in. Thanks!

**Comment by cachedout** [comment]
Bump @dmyerscough 

Would you mind rebasing this, please?

**Comment by dmyerscough** [comment]
@cachedout Sorry I have been super busy, I currently dont have time to work on this at the moment so I will close the pull request and open it in the future when I get time.

**Pull request closed without merging**
