### PR TITLE
Refactor virt module integration tests

### PR DESCRIPTION
**Pull request by rst0git**
### What does this PR do?

This PR is rebased on https://github.com/saltstack/salt/pull/57431. It adds two integration test targets -- `virt_minion_0` and `virt_minion_1`. These targets are based on a container image (https://github.com/rst0git/virt-minion) with pre-installed libvirt and qemu packages. This approach allows to run more than one libvirtd+minion instance on a single system to automate the testing of features such as live migration.

### Previous Behavior
The virt module integration tests require a libvirt daemon to be running on the host system. 

### New Behavior
The virt module integration tests require a docker daemon to be running on the host system.

### CODE REVIEW

**Review by cbosdo — COMMENTED** [review]
LGTM, let's see how the CI digests it

**Comment by cbosdo** [comment]
@waynew @Ch3LL could you have a look at this PR and tell us how that could play with the CI?

**Review by cbosdo — DISMISSED** [review]
LGTM. Thanks for the code factorization.

**Review by cbosdo — DISMISSED** [review]
:+1:

**Comment by s0undt3ch** [comment]
Please do not merge this PR, it's blocked on external changes happening first.
Please read https://github.com/saltstack/salt/pull/57897#issuecomment-663855892 for context.

I will reply once the issues have been resolved to unblock this PR.

**Comment by rst0git** [comment]
Closing in favour of https://github.com/saltstack/salt/pull/57947

**Pull request closed without merging**
