### PR TITLE
Allow to override git_pillar_base per-remote

### PR DESCRIPTION
**Pull request by sathieu**
### What does this PR do?

Allow to override git_pillar_base per-remote.

Note: forward port of #51464, with failhard addition.

### What issues does this PR fix or reference?

None.

### New Behavior
Example:
```yaml

git_pillar_base: develop

ext_pillar:
  - git:
    - __env__ https://gitserver/git-pillar.git
    - __env__ https://gitserver/git-pillar2.git:
      - base: master
```

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by sathieu** [comment]
I want to add some doc, but which target release should I mention? `2019.8.0` ?

@terminalmage Please review.

**Review by terminalmage — COMMENTED** [review]
This PR is not necessary.

https://docs.saltstack.com/en/latest/topics/development/contributing.html#merge-forward-process

**Comment by sathieu** [comment]
@terminalmage #51464 was not merged. I.e. this feature is not in any branch (yet).

**Review by dwoz — APPROVED** [review]

**Comment by sathieu** [comment]
Ported (again) as #57288.

**Pull request merged**
