### PR TITLE
fixed auto assigning of floating_ips for clouds.nova

### PR DESCRIPTION
**Pull request by s-schweer**
### What does this PR do?

fix behaviour of auto-assigning floating_ips
### Tests written?

No

### CODE REVIEW

**Comment by rallytime** [comment]
@gtmanfred Can you please review this change?

**Comment by gtmanfred** [comment]
I am in the middle of a rewrite of all the nova stuff using the shade library, which handles the floating_ip assignments for us.

https://github.com/openstack-infra/shade/blob/master/shade/openstackcloud.py#L3433

And all that stuff will be available in the rewrite.

**Comment by gtmanfred** [comment]
I am going to try and find time to finish up this this weekend.

**Comment by gtmanfred** [comment]
https://github.com/saltstack/salt/compare/develop...gtmanfred:shade

**Comment by gtmanfred** [comment]
looks good to me :+1:

**Comment by rallytime** [comment]
Thanks @s-schweer!

**Pull request merged**
