### PR TITLE
Make sure SaltCacheLoader use correct fileclient

### LINKED ISSUE #60003: [BUG] salt-ssh support for extra_filerefs in Saltfile is broken
**Description**
  I use lots of map.jinjas with salt-ssh, as part of many formulas in my states git repo. Since the files are only imported I need to use extra_filerefs to include them all. I do this in my Saltfile. As of 3003 this doesn't work anymore. If I downgrade to 3002.6, it works.

I thought it might relate to this issue below, but reverting the patch didn't seem to fix it for me. Though I do question the conversion of the type of extra_filerefs from a list to a str. The only reasonable use of extra_filerefs is as a list. I have over 70 map.jinjas, and I need them all.

https://github.com/saltstack/salt/pull/59664/files

**Setup**
./Saltfile:

    salt-ssh:
      config_dir: .
      max_procs: 1
      ssh_wipe: True
      extra_filerefs:
        - salt://_grains/map.jinja

salt-formula/top.sls:

    {% from '_grains/map.jinja' import grain with context %}
    
    base:
      '*':
    {% if grain.fqdn == 'foo.bar.com' %}
        - base
    {% endif %}

**Steps to Reproduce the behavior**

    salt-ssh -i foo.bar.com state.highstate
    [ERROR   ] Rendering exception occurred
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/salt/utils/templates.py", line 497, in render_jinja_tmpl
        output = template.render(**decoded_context)
      File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/usr/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "<template>", line 1, in top-level template code
      File "/usr/lib/python3.9/site-packages/salt/utils/jinja.py", line 198, in get_source
        raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: _grains/map.jinja

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/salt/utils/templates.py", line 261, in render_tmpl
        output = render_str(tmplstr, context, tmplpath)
      File "/usr/lib/python3.9/site-packages/salt/utils/templates.py", line 542, in render_jinja_tmpl
        raise SaltRenderError(
    salt.exceptions.SaltRenderError: Jinja error: _grains/map.jinja
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/salt/utils/templates.py", line 497, in render_jinja_tmpl
        output = template.render(**decoded_context)
      File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/usr/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "<template>", line 1, in top-level template code
      File "/usr/lib/python3.9/site-packages/salt/utils/jinja.py", line 198, in get_source
        raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: _grains/map.jinja

    ; line 1

    ---
    {% from '_grains/map.jinja' import grain with context %}    <======================

    base:
      '*':
    {% if grain.fqdn == 'foo.bar.com' %}
        - base    
    [...]
    ---
    [ERROR   ] Unable to render top file: Jinja error: _grains/map.jinja
    foo.bar.com:

    Summary for foo.bar.com
    -----------
    Succeeded: 0
    Failed:   0
    -----------
    Total states run:    0
    Total run time:  0.000 ms

**Expected behavior**
It to include the map.jinja in the tgz, and not throw an error about not finding it.

**Versions Report**

    salt-ssh --versions-report
    Salt Version:
              Salt: 3003

    Dependency Versions:
              cffi: 1.14.1
          cherrypy: Not Installed
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 2.11.3
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: 1.1.3
           msgpack: 1.0.0
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.20
          pycrypto: 2.6.1
      pycryptodome: 3.10.1
            pygit2: Not Installed
            Python: 3.9.2 (default, Feb 20 2021, 00:00:00)
      python-gnupg: Not Installed
            PyYAML: 5.4.1
             PyZMQ: 22.0.3
             smmap: Not Installed
           timelib: Not Installed
           Tornado: 4.5.3
               ZMQ: 4.3.4

    System Versions:
              dist: fedora 33
            locale: utf-8
           machine: x86_64
           release: 5.11.10-200.fc33.x86_64
            system: Linux
           version: Fedora 33

### PR DESCRIPTION
**Pull request by kaszuba**
What does this PR do?

Fix problem with jinja2.exceptions.TemplateNotFound: errors in salt-ssh

What issues does this PR fix or reference?

Fixes: #60003 #61174

Problem was caused by wrong cachedir path used by fileclient (FSClient class) in SaltCacheLoader:

 * class SaltCacheLoader (in jinja) use default fsclient, with "cachedir" from salt.syspaths.CACHE_DIR
 * class Single (in SSH), use fsclient with path for minion

When execute "salt-ssh ... state.apply" BaseHighState will get fsclient from SSH (with minion path), and in compile_low_chunks() files are cached in minion cache path. But when execute jinja (in render_state) fsclient will cache files in cachedir from config (different then minion) and jinja cannot find files.

### CODE REVIEW

**Comment by vvrein** [comment]
```diff
--- /root/original_state.py                             2022-04-01 11:45:58.041040719 +0300
+++ /usr/lib/python3/dist-packages/salt/state.py        2022-04-01 11:40:48.530320452 +0300
@@ -4022,6 +4022,8 @@
             )
         else:
             try:
+                if context is None:
+                    context = {"fileclient": self.client}
                 state = compile_template(
                     fn_,
                     self.state.rend,
```

Can confirm that this PR fixes the salt-ssh (3004) work on Ubuntu 20.04

**Comment by stratusjerry** [comment]
> ```diff
> --- /root/original_state.py                             2022-04-01 11:45:58.041040719 +0300
> +++ /usr/lib/python3/dist-packages/salt/state.py        2022-04-01 11:40:48.530320452 +0300
> @@ -4022,6 +4022,8 @@
>              )
>          else:
>              try:
> +                if context is None:
> +                    context = {"fileclient": self.client}
>                  state = compile_template(
>                      fn_,
>                      self.state.rend,
> ```
> 
> Can confirm that this PR fixes the salt-ssh (3004) work on Ubuntu 20.04



> ```diff
> --- /root/original_state.py                             2022-04-01 11:45:58.041040719 +0300
> +++ /usr/lib/python3/dist-packages/salt/state.py        2022-04-01 11:40:48.530320452 +0300
> @@ -4022,6 +4022,8 @@
>              )
>          else:
>              try:
> +                if context is None:
> +                    context = {"fileclient": self.client}
>                  state = compile_template(
>                      fn_,
>                      self.state.rend,
> ```
> 
> Can confirm that this PR fixes the salt-ssh (3004) work on Ubuntu 20.04

Can also confirm salt-ssh 3004 fix on CentOS 7

**Comment by s-at-ik** [comment]
fixed `salt-ssh` 3004 on debian stable for me, thanks

**Comment by aarnaud** [comment]
Nice, thanks for the fix I had the same issue

**Comment by baby-gnu** [comment]
Hello.

There are in fact 2 kinds of issues regarding `import`:

1. from `.sls` files
2. from `file.managed` jinja templates

This PR solves the first issue, without the need of `--extra-filerefs`.

The second case still has the issue.

**Comment by baby-gnu** [comment]
@kaszuba thanks for the explanation.

Don't worry, I mostly prefer to pass `context` to simple jinja templates.

Thanks.

**Comment by Rudd-O** [comment]
When is this PR gonna get merged?  This bug is a huge regression for salt-ssh users.  Is SaltStack becoming abandonware?

**Comment by stratusjerry** [comment]
@Ch3LL is this patch being tracked for 3005 release?

**Comment by Ch3LL** [comment]
No, it looks like it was slated for 3006 on our issue tracker. But this PR will need test coverage and a changelog before it will be accepted.

**Comment by TeddyAndrieux** [comment]
Any chance we get this PR merged ? 

I'm actually stuck in Salt 3002 because of this regression

**Review by dwoz — CHANGES_REQUESTED** [review]
This needs a test case.

**Comment by eliasp** [comment]
> This needs a test case.

When writing a test for this, here's a scenario that's easy to reproduce for me, affected by this issue:
- Create `/var/tmp/some.yaml` and dump some valid YAML into it
- Create `/var/tmp/some.sls` with the following content:
  ```Jinja
  {%- import_yaml "/var/tmp/some.yaml" as imported %}
  {{ imported }}
  ```
- Execute `salt-call slsutil.renderer /var/tmp/some.sls default_renderer=jinja`

**Comment by Rudd-O** [comment]
> > This needs a test case.
> 
> When writing a test for this, here's a scenario that's easy to reproduce for me, affected by this issue:
> 
>     * Create `/var/tmp/some.yaml` and dump some valid YAML into it
> 
>     * Create `/var/tmp/some.sls` with the following content:
>       ```
>       {%- import_yaml "/var/tmp/some.yaml" as imported %}
>       {{ imported }}
>       ```
> 
>     * Execute `salt-call slsutil.renderer /var/tmp/some.sls default_renderer=jinja`

But what are the pass / fail outputs??

**Comment by Ch3LL** [comment]
Would someone be willing to try my fix here: https://github.com/saltstack/salt/pull/63184  Its still a work in progress, but it I did verify it worked with the original submitter of this issue's files: https://github.com/saltstack/salt/issues/60003. and using `state.apply` as the description states in this PR.

If it does not work, please post the exact files you are using and the exact command. I need to review all of the methods in salt/client/ssh/wrapper/state.py to ensure we are explicitly passing in context.

I think it would be a better fix to explicitly pass in context from salt-ssh to ensure we are using the entire context, not just setting fileclient.

**Comment by kaszuba** [comment]
> Would someone be willing to try my fix here: #63184 Its still a work in progress, but it I did verify it worked with the original submitter of this issue's files: #60003. and using `state.apply` as the description states in this PR.
> 
> If it does not work, please post the exact files you are using and the exact command. I need to review all of the methods in salt/client/ssh/wrapper/state.py to ensure we are explicitly passing in context.
> 
> I think it would be a better fix to explicitly pass in context from salt-ssh to ensure we are using the entire context, not just setting fileclient.

Hi @Ch3LL, thanks for looking on problem, your solution looks much better then old quick fix :)

I checked your patch and not works for me, got the same error with missing template, but it is fast fixable by adding old patch in render_highstate method
```
    def render_highstate(self, matches, context=None):
        """
        Gather the state files and render them into a single unified salt
        high data structure.
        """
        highstate = self.building_highstate
        all_errors = []
        mods = set()
        statefiles = []
        if context is None:
            context = {"fileclient": self.client}
        for saltenv, states in matches.items():
           ....
```

Probably context should be also passed to "render_highstate", now in BaseHighState it is used only as "self.render_highstate(matches)", without context passing

**Comment by kaszuba** [comment]
@Ch3LL i see there is already change for render_highstate(), probably i grab wrong patch
checked again and your patch works, thanks

**Comment by Ch3LL** [comment]
Yeah, I just recently pushed up a fix for that call. I'm currently adding tests (that's how I found that issue) and fixing up the rest of the functions in salt-ssh's state.py. Thanks for confirming. I'll go ahead and close in favor of https://github.com/saltstack/salt/pull/63184/files

**Pull request closed without merging**
