### PR TITLE
[FEATURE] retcode passthrough exitstatus

### PR DESCRIPTION
**Pull request by plastikos**
### What does this PR do?

It passes the `retcode` through to the `salt` and `salt-call` executable exit status.
### What issues does this PR fix or reference?
#18510
### Previous Behavior

The `retcode` from states was not reflected in the command line executable exit status
### New Behavior

Non-zero `retcode` from salt states is used for the exit status of `salt` and `salt-call` - unless a "higher priority" error occurs in the specific executables.
### Tests written?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by plastikos** [comment]
@cachedout , there were race conditions in the setup/tear-down of the integration tests.  The `salt-master` executable would start up, complete the integration test, but not be completely functional by the time tear-down occurred.  Consequently sub-processes did not have signal handlers installed and process would be left behind.  This resulted in the 0e98a56 being created.

I found it expedient to use the creation of the PID file as a notification that the process was ready.  Whether it was done in a reasonable way is open for debate at this point - I will certainly rework things upon better suggestions.

**Comment by cachedout** [comment]
I think this is all really solid. The only thing would be some documentation in the release notes since will definitely be a change that people want to know about. If you could add a note there, then I think we'll get this in.

**Comment by cachedout** [comment]
A lint error here too.

**Comment by plastikos** [comment]
@cachedout , help me out: where are the release notes?

**Comment by rallytime** [comment]
@plastikos The Carbon release notes are located in `doc/topics/releases/carbon.rst`. :D

**Comment by plastikos** [comment]
@rallytime, thank you.

**Comment by plastikos** [comment]
Huh.  I don't remember pushing d60d193 upstream . . . looks like I need to clean that up now.

**Comment by plastikos** [comment]
@cachedout , I just added an `exit_codes.rst` documentation page.  It's a start: it's not necessarily complete nor is it in the best location.  Additionally I'm unable to "build" the documentation so I'm unsure how it renders or if the links even work.

At this point I think I'm "feature complete" and we just need to *tweak* details.

Feedback is *welcomed*.

**Comment by plastikos** [comment]
@cachedout , oh I also noticed that this branch now has conflicts, so if we can get the details nailed down and taken care of I'll rebase everything.

**Comment by cachedout** [comment]
@plastikos I'm not sure which details you're referring to?

**Comment by plastikos** [comment]
@cachedout, is the documentation reasonable? Does it build?  Does this even look like it's doing what was intended by our discussion?

**Comment by plastikos** [comment]
I *really* wish @soundtech had coordinated with me when he improved my test framework.  It wasn't being used anyplace except my integration tests and now I have a serious rebase nightmare.

**Pull request closed without merging**
