### PR TITLE
Virt whitespace fix

### PR DESCRIPTION
**Pull request by cbosdo**
### What does this PR do?

Fixes handling of Virtual Machines with white space in their name.

### What issues does this PR fix or reference?

None

### Previous Behavior

`virt.init` called with a VM name containing a white space resulted in a failure.

### New Behavior

`virt.init` now works also for VMs with a space in their name.

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by cbosdo** [comment]
@rallytime This PR is ready for review

**Review by rallytime — APPROVED** [review]

**Review by thatch45 — APPROVED** [review]

**Comment by cbosdo** [comment]
@rallytime, @thatch45  any news on that PR? How comes it's ACKed but not merged?

**Comment by cbosdo** [comment]
Just rebased the PR one 2019.2. I hope it'll help to get it merged

**Review by brejoc — APPROVED** [review]
lgtm

**Pull request merged**
