### PR TITLE
[PY3] Add unicode_literals to salt.utils modules (T-V)

### PR DESCRIPTION
**Pull request by terminalmage**

### CODE REVIEW

**Comment by rallytime** [comment]
re-run py

**Comment by rallytime** [comment]
@terminalmage The tests here look related:
https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/18799/
```
unit.utils.vmware.test_license.GetAssignedLicensesTestCase.test_entity_name
unit.utils.vmware.test_license.AssignLicenseTestCase.test_entity_name
unit.utils.vmware.test_connection.GetServiceInstanceFromManagedObjectTestCase.test_default_name_parameter
unit.utils.vmware.test_connection.GetServiceInstanceFromManagedObjectTestCase.test_name_parameter_passed_in
```

**Comment by terminalmage** [comment]
@rallytime I missed updating those in this PR, I'll get these updated today.

**Comment by rallytime** [comment]
re-run py

**Comment by rallytime** [comment]
@terminalmage Ah, there's a merge conflict here now.

**Review by rallytime — APPROVED** [review]

**Pull request merged**
