### PR TITLE
Decode payloads on Python 2 to preserve unicode in jobs and fileclient reqs

### LINKED ISSUE #40578: UnicodeEncodeError: 'ascii' codec can't encode characters
I use file.recurse to transfer directories and files,once the file name contains chinese,there will be problems,those files couldn't be transfered to the spectified minions.debug info shows "UnicodeEncodeError: 'ascii' codec can't encode characters in position 31-34: ordinal not in range(128)".

Here are my .sls:
`test1:`
  `  file.recurse:`
    `    - name: /root/group2test`
    `    - source: salt://release/test/{{pillar["test"]}}`
    `    - mkdirs: True`
    `    - include_empty: True`
 

Here are the debug info:
----------
          ID: test1
    Function: file.recurse
        Name: /root/group2test
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1746, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1703, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/states/file.py", line 2807, in recurse
                  manage_file(dest, src)
                File "/usr/lib/python2.6/site-packages/salt/states/file.py", line 2685, in manage_file
                  **pass_kwargs)
                File "/usr/lib/python2.6/site-packages/salt/states/file.py", line 1814, in managed
                  __env__
                File "/usr/lib/python2.6/site-packages/salt/modules/file.py", line 3490, in source_list
                  contextkey = '{0}_|-{1}_|-{2}'.format(source, source_hash, saltenv)
              UnicodeEncodeError: 'ascii' codec can't encode characters in position 31-34: ordinal not in range(128)
     Started: 20:08:21.608398
    Duration: 1467.811 ms
     Changes:   
  Summary for g146
  ------------
  Succeeded: 0
  Failed:    1
  ------------
  Total states run:     1
  Total run time:   1.468 s
  [DEBUG   ] jid 20170407133951142263 found all minions set(['jenkins', 'g146'])
  ERROR: Minions returned with non-zero exit code

Here are the  debug logs:
2017-04-07 14:00:40,412 [salt.utils.event                                     ][DEBUG   ][15280] Sending event: tag = file.recurse; data = {'comment': 'An exception occurred in this state: Traceback (most recent call last):\n  File "/usr/lib/python2.6/site-packages/salt/state.py", line 1746, in call\n    **cdata[\'kwargs\'])\n  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1703, in wrapper\n    return f(*args, **kwargs)\n  File "/usr/lib/python2.6/site-packages/salt/states/file.py", line 2807, in recurse\n    manage_file(dest, src)\n  File "/usr/lib/python2.6/site-packages/salt/states/file.py", line 2685, in manage_file\n    **pass_kwargs)\n  File "/usr/lib/python2.6/site-packages/salt/states/file.py", line 1814, in managed\n    __env__\n  File "/usr/lib/python2.6/site-packages/salt/modules/file.py", line 3490, in source_list\n    contextkey = \'{0}_|-{1}_|-{2}\'.format(source, source_hash, saltenv)\nUnicodeEncodeError: \'ascii\' codec can\'t encode characters in position 31-34: ordinal not in range(128)\n', '_stamp': '2017-04-07T06:00:40.412486', 'retcode': 2, 'name': '/root/group2test', 'start_time': '20:28:36.031209', 'result': False, 'duration': 1336.1479999999999, '__run_num__': 0, 'changes': {}, '__id__': 'test1'}

Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
 
System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final

I not sure if I should modify the default coding that saltstack uesd and don't know which .py file should be modified.
My English is terrible,please forgive me

### LINKED ISSUE #45469: Write test for issue 40578
Write auto tests for https://github.com/saltstack/salt/issues/40578

### PR DESCRIPTION
**Pull request by terminalmage**
Published functions are serialized when they go over the wire and deserialized on the other end. This causes unicode CLI args to be lost on Python 2. Similarly, fileclient requests made from the minion to a master using the RemoteClient will have the same issue. This commit does the following things to ensure we don't lose unicode from CLI args, and also to ensure that fileclient requests involving unicode are successful:

1. Decodes the return from the various "list" functions in the RemoteClient.

2. Decodes the payload received from by the fileserver from a minion.  Also removes the decoding done in these same functions, because A) the backends already support unicode, and B) unicode characters will be re-encoded as part of the serialization process anyway.

3. Decodes the payload received by the minion so that the arguments passed to the function being called are unicode.

This does the last bit of work to resolve #40578, and also includes an integration test to confirm the correct behavior.

Resolves #40578.
Resolves #45469.

### CODE REVIEW

**Comment by rallytime** [comment]
@terminalmage Lint didn't like this change very much (and perhaps that's why we didn't get results from the test runs). Can you take a look?

**Comment by terminalmage** [comment]
Yeah, syntax error in my new decorator. I thought I linted everything I changed before I submitted it, but I must have forgotten that file. Should be fixed now.

**Review by rallytime — APPROVED** [review]

**Comment by thatch45** [comment]
Have you tested this with older master/minion combinations on py2 and py3? I had left some of these out for that purpose

**Comment by thatch45** [comment]
Also, just to verify, it does not look like it. But the actual file data is never encoded/decoded but is always raw bytes, correct?

**Comment by thatch45** [comment]
Otherwise, this looks good :)

**Comment by aphor** [comment]
I just discovered this also needs fixing in states/archive.py and modules/archive.py with a zipfile containing unicode Chinese characters in directory names.

I tried hacking in log.debug("extracting: {}".format(pathname)) and even that will blow up :(

I then tried to sanitize the pathname with salt.util.locales.sdecode() and this only tried ASCII decoding, and threw up the exception.

Is anyone else thinking this needs a salt.util level solution?

How is Python3 salt handling this stuff with the clean separate (unencoded)bytesting/(encoded)string objects?

**Comment by terminalmage** [comment]
@thatch45 There shouldn't be a chance of an incompatibility between older and newer versions, the reason being that the decoding happens after data is received by either the master or minion. When you throw unicode data at msgpack, it's going to encode it to a str on PY2 in the process of serialization.

Of course, trying to pass around unicode data to an older minion from a newer master would still cause problems, but that's not really avoidable, and would frankly be the case even if unicode data were sent by a pre-oxygen master to a pre-oxygen minion; it's what we're working to resolve here.

With regard to the actual file data being bytes, yes, this is still the case. The code in minion.py only performs the decode after the payload has been deserialized, at which point it's a dictionary with all strings as `str` types.

**Comment by terminalmage** [comment]
@aphor sdecode will be phased out eventually, I'd recommend using either `salt.utils.data.decode()` (more general function that recurses into data structures), or `salt.utils.stringutils.to_unicode()`, which requires the value passed to it either a str, bytes, or bytearray type (otherwise it throws a TypeError).

**Comment by terminalmage** [comment]
@aphor I'll look into the archive state/module.

**Comment by thatch45** [comment]
Perfect, just making sure!

**Review by thatch45 — APPROVED** [review]

**Comment by terminalmage** [comment]
@aphor I can't reproduce what you're talking about on either the head of the 2017.7 branch or the branch that will become the Oxygen release.

**Comment by terminalmage** [comment]
@aphor See the below docker container with an example. The `docker run` command is run from the root of a git checkout of Salt.

```
% docker run --rm -it -v $PWD:/testing terminalmage/issues:pr45772 salt-call state.apply
local:
----------
          ID: test_with_chinese_chars
    Function: archive.extracted
        Name: /tmp
      Result: True
     Comment: salt://chinese_chars.zip extracted to /tmp/, due to absence of one or more files/dirs
     Started: 23:00:09.438983
    Duration: 53.875 ms
     Changes:
              ----------
              extracted_files:
                  - 蟒蛇/
                  - 蟒蛇/foo.txt
                  - 蟒蛇/垃圾邮件.txt
                  - 蟒蛇/蛋/
                  - 蟒蛇/蛋/bar.txt
                  - 蟒蛇/蛋/baz.txt
                  - 蟒蛇/蛋/foo.txt

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  53.875 ms
```

Given that I can't reproduce, if you find a use case where you can please open a new issue and @ mention me so I can look at it.

**Comment by terminalmage** [comment]
To test with Python 3 you can replace `salt-call` with `python3 /testing/scripts/salt-call` in the `docker run` command above.

**Comment by aphor** [comment]
@terminalmage Docker is giving me "unauthorized" when it tries to pull the manifest you provided.

**Comment by terminalmage** [comment]
@aphor when you say that it's fixed, did you mean that the archive state and module are fixed?

**Comment by aphor** [comment]
No, the docker is fixed, and sadly it works with my zipfile, except when I break the container's locale settings.

Now I'm trying to figure out if my minions' locale is messed up (and if so how) or if there's some sane but still pathological reproduce test case I can reduce.

**Comment by damon-atkins** [comment]
From https://github.com/msgpack/msgpack-python/blob/master/README.rst#deprecating-encoding-option
>Deprecating encoding option encoding and unicode_errors options are deprecated.
>In case of packer, use UTF-8 always. Storing other than UTF-8 is not recommended.

i.e. Internally or between master/minion  if a bytes is needed it should be encoded UTF-8 not `__salt_system_encoding__` which is currently the default.

**Comment by rallytime** [comment]
@terminalmage - I think the test failure `integration.client.test_kwarg.StdTest.test_kwarg_type ` is related to this, and possibly `integration.modules.test_system.SystemModuleTest.test_set_computer_desc`: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/19498/#showFailuresLink

Can you take another look?

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
@terminalmage Ok, there is a lint failure here and some more related test failures. I might have missing them before.

- lint: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/18935/violations/file/salt/modules/system.py/
- PY3 Ubuntu 16: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu16-py3/6495/
- PY2 CentOS 7: https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/15980/ I think the gitfs failures are releated

**Comment by terminalmage** [comment]
@rallytime those failures should be fixed with the next run.

**Comment by aphor** [comment]
@terminalmage the docker image you provided is Ubuntu Xenial which has a sane default system locale.

`# python -c 'import salt; print(__salt_system_encoding__)'
UTF-8`

because 

`# python -c 'import os; print(repr(dict([e for e in os.environ.items() if e[0][:3] == "LC_"])))'
{'LC_ALL': 'en_US.UTF-8'}`

but if linux minions running as a service don't get a default system locale, salt/__init__.py sets __salt_system_encoding__ to 'ascii' which will create unicode decode problems all over the place.

I'm trying to fix this by getting the system locale straightened out, but maybe salt minions should impose UTF-8 encoding instead of ascii?

**Pull request merged**
