### PR TITLE
Update the FreeBSD Install documentation

### PR DESCRIPTION
**Pull request by brd**
### What does this PR do?
Update the FreeBSD install to match the current state and encourage using the Python 3 version by listing it first.

### Commits signed with GPG?
No

### CODE REVIEW

**Review by krionbsd — DISMISSED** [review]

**Comment by krionbsd** [comment]
@brd it seems I mistakenly removed this chunk of text while resolving conflicts on gh:
```
Python 3.7 can be used by setting default Python version to 3.7:  

.. code-block:: text

    echo "DEFAULT_VERSIONS+= python=3.7" >> /etc/make.conf
```
could you please re-add it into PR?

**Review by krionbsd — CHANGES_REQUESTED** [review]
Please add:
```
Python 3.7 can be used by setting default Python version to 3.7:  

.. code-block:: text

    echo "DEFAULT_VERSIONS+= python=3.7" >> /etc/make.conf
```
I can't push into your branch

**Comment by brd** [comment]
I think it is better to remove it since very few people use ports anymore I think, and those that do know how to do overrides like this. Also it can confuse people that set it and then expect it to work for pkgs as well.

**Comment by brd** [comment]
Er, sorry, rereading the diff I think we don't need to specify the default version of python because 3.7 is already the default:

https://svnweb.freebsd.org/ports/head/Mk/bsd.default-versions.mk?view=markup#l104

**Comment by krionbsd** [comment]
> Er, sorry, rereading the diff I think we don't need to specify the default version of python because 3.7 is already the default:

ok, makes sense, thanks

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
