### PR TITLE
Datetime support for msgpack for issue-21721

### PR DESCRIPTION
**Pull request by surajssd**
datetime.datetime support added. In this PR only encoding code is added working on decoding part as well.
#21721

### CODE REVIEW

**Comment by thatch45** [comment]
I like this idea but I think that it should be implemented in a more robust way. @cachedout and myself are going to talk it over and try to figure out how to make this viable. It poses a swath of security concerns and if we insert it like this it makes scaling issues and portability issues.

So in summary, this is a killer idea and I think we can implement it in a much more powerful way

**Comment by cachedout** [comment]
@surajssd We sat down and talked about this and I think what we're going to do here is merge this and then immediately refactor it into an external library just to keep the serialization code as tidy as possible. Thanks for your contribution here, it should really help!

**Comment by surajssd** [comment]
@thatch45  and @cachedout yeah writing a seperate library that handles all msgpack issues would be better and could have more additions in near future if some where it fails again. And library supports easy encoding and decoding of datatypes into msgpack.

**Comment by jfindlay** [comment]
@thatch45, @cachedout, also see #21113.

**Pull request merged**
