### PR TITLE
Fix fileserver whitelist mapping logic

### LINKED ISSUE #58041: [BUG] s3fs file server fails with "Failed to load function s3fs.envs because its module (s3fs) is not in the whitelist: ['s3']"
**Description**
Salt-master doesn't put up s3fs-based file server, with error message "Failed to load function s3fs.envs because its module (s3fs) is not in the whitelist: ['s3']".
salt-run fileserver.file_list returns the same error.

**Setup**

/etc/salt/master.d/00-master.conf : 

fileserver_backend:
  - s3fs

s3.keyid: XXX
s3.key: XXX
s3.service_url: XXX
s3.https_enable: True
s3.path_style: True
s3.verify_ssl: False
s3.location: eu-west-0

s3fs_saltenv_whitelist:
  - base
  - master
  - devel

s3.buckets:
  base:
    - xxxxx

etc.

**Steps to Reproduce the behavior**
Configure the master to use s3fs backend and start.
Run salt-run fileserver.file_list.

**Expected behavior**
With no whitelist configured, there should not be need to add a module to the whitelist. The backend should not throw this error and the file server should be running.

**Versions Report**
<details><summary>
</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: Not Installed
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.7.3 (default, Dec 20 2019, 18:57:59)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10 buster
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-8-amd64
         system: Linux
        version: Debian GNU/Linux 10 buster

```
</details>

**Additional context**
If the lines 1885 to 1893 of /usr/lib/python3/dist-packages/salt/loader.py are commented : 

    if self.whitelist and mod_name not in self.whitelist:
                log.error(
                    "Failed to load function %s because its module (%s) is "
                    "not in the whitelist: %s",
                    key,
                    mod_name,
                    self.whitelist,
                )
                raise KeyError(key)

the file server runs ok.

### PR DESCRIPTION
**Pull request by Timbus**
### What does this PR do?
Fixes the logic behind whitelisting filesystem backends with two names.

### What issues does this PR fix or reference?
Fixes: #58041 and improves on #58496 

### Previous Behavior
A less-than-optimal bit of string handling would un-whitelist any module ending in 'fs'

### New Behavior
Only `git`, `svn` and `hg` backends are treated specially. All others are kept as-is.
I used sets to prevent duplicate names, I couldn't figure out why the old logic was splitting lists but assume that might be the goal

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by Timbus** [comment]
Oh, the tests failed (see #58565) but the changes I added pass fine.. not sure if you need me to rebase or something after master is fixed?

**Review by krionbsd — DISMISSED** [review]

**Comment by Timbus** [comment]
Bump? This was approved, but is not being merged. I added a changelog if that was the issue..

**Comment by sagetherage** [comment]
the test failing here is flakey and the Core team is looking at fixing the test @garethgreenaway can you update this once that test is corrected, please?

**Comment by sagetherage** [comment]
once it passes tests I bet @dwoz will review and merge

**Comment by corywright** [comment]
We were hit very hard by this bug, causing silent failures when using `cp.get_file`. I backported this change to our loader.py from 3001.3 and it resolved the issue. I hope this can make it into the next release.

**Review by garethgreenaway — APPROVED** [review]

**Comment by erespaulo** [comment]
Hi, any news for this subject?

**Comment by sagetherage** [comment]
@erespaulo looks like the Fedora 32 test cancelled, but I have updated the PR to `master` and that will re-run the tests, so let's see if that fixes it.

**Comment by corywright** [comment]
Any idea when we will see this merged?  The fix in this PR works and I've had to backport it on each Salt upgrade.

**Review by krionbsd — APPROVED** [review]

**Review by dwoz — APPROVED** [review]

**Comment by oliver-dungey** [comment]
@Ch3LL so which release do I need to use to get this fix? Aluminium/3003 or will it be available in a 3002 update?

**Pull request merged**
