### PR TITLE
Under Py3 `TypeError` can also be raised. Handle all kinds of exceptions

### PR DESCRIPTION
**Pull request by s0undt3ch**
This was seen when running under windows:
```
14:13:11          test_invalid_kwargs_are_ignored (integration.client.test_runner.RunnerModuleTest)
14:13:11        [CPU:50.0%|MEM:24.0%]  ... 14:13:15,697 [salt.loader                                                                      :1572][ERROR   ] Failed to import auth pam, this is due most likely to a syntax error:
14:13:11        Traceback (most recent call last):
14:13:11          File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\salt\loader.py", line 1548, in _load_module
14:13:11            mod = spec.loader.load_module()
14:13:11          File "<frozen importlib._bootstrap_external>", line 396, in _check_name_wrapper
14:13:11          File "<frozen importlib._bootstrap_external>", line 817, in load_module
14:13:11          File "<frozen importlib._bootstrap_external>", line 676, in load_module
14:13:11          File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
14:13:11          File "<frozen importlib._bootstrap>", line 693, in _load
14:13:11          File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
14:13:11          File "<frozen importlib._bootstrap_external>", line 673, in exec_module
14:13:11          File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
14:13:11          File "C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\testing\salt\auth\pam.py", line 52, in <module>
14:13:11            LIBC = CDLL(find_library('c'))
14:13:11          File "C:\Python35\lib\ctypes\__init__.py", line 347, in __init__
14:13:11            self._handle = _dlopen(self._name, mode)
14:13:11        TypeError: bad argument type for built-in operation
14:13:18        OK (7.594s)
14:13:18          test_token (integration.client.test_runner.RunnerModuleTest)
14:13:26        [CPU:0.0%|MEM:24.1%]  ... args:
```
### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by terminalmage — APPROVED** [review]

**Comment by s0undt3ch** [comment]
Windows tests didn't even start `14:50:31        cmd.exe : The command line is too long.`

**Comment by terminalmage** [comment]
I'm confused as to why it would be that long when only one file is being modified by this PR.

**Comment by terminalmage** [comment]
Could this be a problem with the code used to obtain the list of changed files?

**Comment by s0undt3ch** [comment]
The matcher failures are because of the blackout tests, which is being fixed in the last 2 commits of https://github.com/saltstack/salt/pull/51041

**Review by thatch45 — APPROVED** [review]

**Pull request merged**
