### PR TITLE
Lithium deprecations

### PR DESCRIPTION
**Pull request by cachedout**

### CODE REVIEW

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
What is the status here @cachedout ?

**Comment by cachedout** [comment]
I think I'm chasing my own tail on these tests failures. I need to sit down and do a complete test run on my machine before this is ready to merge.

**Comment by s0undt3ch** [comment]
I'm going to pull this PR into my setup paths one since I won't get it to pass without this merged and I'm sure there are still some missed refs since salt version was not updated in `salt.version` which makes the deprecation warnings pop up automatically.

**Comment by cachedout** [comment]
@s0undt3ch Sounds good. Shall I close this one then?

**Comment by s0undt3ch** [comment]
Yeah. We'll take over from there.

**Pull request closed without merging**
