### PR TITLE
salt-api no longer forces the default timeout

### LINKED ISSUE #38524: salt-api seems to ignore rest_timeout since 2016.11.0
### Description of Issue/Question
We're using the Jenkins [saltstack-plugin](https://github.com/jenkinsci/saltstack-plugin) and before upgrading to 2016.11.0 (or possibly 2016.11.1) Jenkins successfully waited for the saltstack job to return. This is no longer the case, it instead reports http status code 504 after 300 seconds. Looking at the code for [api_config](https://github.com/saltstack/salt/blob/develop/salt/config/__init__.py#L3453-L3470) it changed between 2016.3.4 and 2016.11.0 and if I'm reading it correctly it will always overwrite the user set `rest_timeout` with the [defaults](https://github.com/saltstack/salt/blob/develop/salt/config/__init__.py#L1540-L1546).

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report

    $ salt --versions-report
    Salt Version:
               Salt: 2016.11.1

    Dependency Versions:
               cffi: 0.8.6
           cherrypy: 3.2.2
           dateutil: 1.5
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4

    System Versions:
               dist: centos 7.2.1511 Core
            machine: x86_64
            release: 3.10.0-327.36.3.el7.x86_64
             system: Linux
            version: CentOS Linux 7.2.1511 Core

### PR DESCRIPTION
**Pull request by rbjorklin**
### What issues does this PR fix or reference?
Fixes #38524 

### Previous Behavior
default rest_timeout was forced

### New Behavior
rest_timeout is usable again

### Tests written?
No

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Hi @rbjorklin - Can you explain a little more about why `rest_timeout` is getting reset through in the `opts.update(api_opts)` here, before this change? I think this fix is going to break some other things, namely the key updates to `pidfile` (and also `log_file` as was recently fixed in #38560).

I ran across this change during a merge forward as there was a merge-conflict here between this change and the one made in #38560. The key overriding for `pidfile` and `log_file` are intentional, and without them I think #38479 will be broken still, which @Ch3LL fixed with #38560.

After looking at these two conflicting changes, it seems to me that the `rest_timeout` should be coming through in that dictionary update call. The `rest_timeout` key from `api_opts` will just be added to the `opts` dictionary. Unless I am missing something?

For the time being, I am using the changes from 2016.3 to merge forward, and we can certainly discuss this further here and make whatever changes are needed. I want to make sure all of the moving pieces here are covered. 

Please see PR #38570 for the merge forward change.

**Comment by Ch3LL** [comment]
I think what he is attempting to say is the api default rest_timeout value of 300 is overwriting the users rest_timeout in their config is that correct? I'm assuming this because of the issue here: https://github.com/saltstack/salt/issues/38524 but the PR title here confuses me a bit as the intention.

If the intention is to not overwrite the users `rest_timeout` config what do you think about adding this:

`'rest_timeout': opts.get('rest_timeout', DEFAULT_API_OPTS['rest_timeout']),` So we ensure we are keeping the default api timeout of 300 and grabbing the users settings? Note: I have not tested this.

**Comment by rbjorklin** [comment]
@rallytime The way I'm reading the existing code we get the master.conf opts and then overwrite them with the default (here)[https://github.com/saltstack/salt/blob/develop/salt/config/__init__.py#L3465]. My proposed change get's the defaults first and then overwrite them with the ones from master.conf. This should not break the `pidfile` update as it is still done just a little differently.

@Ch3LL That's correct, sorry if I was being a bit unclear. That's basically what my change does but without the explicit step. By updating the entire config you don't have to maintain the explicit steps every time a new salt-api option is added. Did that make things any clearer?

**Comment by rallytime** [comment]
@rbjorklin and @Ch3LL - Can you guys take a look at the change I made in #38585 on the 2016.3 branch? I think that explains in code more what I mean. Hopefully that makes more sense!

**Comment by Ch3LL** [comment]
That looks great to me @rallytime ! That should grab all those configurations as you stated from what I can tell. :+1:

**Comment by rbjorklin** [comment]
@rallytime #38585 looks good! I initially missed that we stored the value from `api_pidfile` into `pidfile` and likewise for `logfile`.

**Comment by rallytime** [comment]
Ok awesome! Thanks everyone. I'll write some tests for the change in my PR.

**Pull request merged**
