### PR TITLE
[3006.x] Fix salt-ssh retcode reporting

### PR DESCRIPTION
**Pull request by lkubb**
### What does this PR do?
* Ensures invalid retcodes reported by the remote do not crash salt-ssh.
* Also generally ensures salt-ssh does not crash if `retcode` is a non-integer for whatever reason.
* Makes sure `salt.client.ssh.shell.Shell.exec_cmd` calls `term.close` before querying the exit status and returns an exit status > 128 if a process died as the result of a signal. Both changes avoid returning `None` as retcode.

While I could fairly reliably reproduce the reported behavior instrumentalizing another PR for running the test suite many times in parallel, the changes to `Shell` found here completely solved the intermittent test failures in two full runs, where previously one could find 3-4 instances per full run (which usually sorted out themselves during the re-run and thus were not spotted; full run meaning all test runs that are part of the CI pipeline for PRs, not a single full run of the suite on a system).

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/64575
Fixes: https://github.com/saltstack/salt/issues/64588

### Previous Behavior
Seldomly: `TypeError: '>' not supported between instances of 'NoneType' and 'int'`

### New Behavior
Exits with the correct exit code and returns output as usual.

### Merge requirements satisfied?cs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by s0undt3ch — DISMISSED** [review]
Would also like a review from @dwoz

**Comment by lkubb** [comment]
@dwoz Any update on this PR? Ideally, this would have made it into 3006.2. It is a proper regression vs 3006.1, not sure how frequent the linked issue appears in production though.

**Comment by lkubb** [comment]
Sorry for dismissing the review, had to resolve conflicts after the CVE fix.

@dwoz Mind doing the requested review? Shouldn't take long. :)

**Comment by lkubb** [comment]
@dwoz Friendly ping. :)

General remark: This patch has been carried by QubesOS since June to fix their relatively frequent CI failures caused by the underlying issue.

**Review by s0undt3ch — APPROVED** [review]

**Review by dwoz — APPROVED** [review]

**Pull request merged**
