### PR TITLE
boto_vpc: raise exception on boto failures

### PR DESCRIPTION
**Pull request by mgwilliams**
Per discussion with @ryan-lane, @claudiupopescu, and @tsaridas.

Also utilizes `_create/delete_resource` for additional functions.

@ryan-lane: should the boto_vpc state be updated to catch these exceptions, or let it just automatically fail the state due to the exception? It does cause a traceback in the state output. I find that useful, but others may not.

### CODE REVIEW

**Comment by mgwilliams** [comment]
I don't think the Ubuntu failures are related to my changes.

**Comment by mgwilliams** [comment]
Please hold off on merging this... discussed with @thatch45 and this may need to be rethought.

**Comment by ryan-lane** [comment]
I personally like the exception being passed through. It's really useful
when a state run fails.

**Comment by thedrow** [comment]
@ryan-lane If you're debugging, yes.
If not, it looks like a crash and that looks bad.

**Pull request closed without merging**
