### PR TITLE
Fix #40602: onfail_stop: test loop order is broken

### LINKED ISSUE #40602: onfail_stop: test loop order is broken
I ll submit appropriate test & PR

### PR DESCRIPTION
**Pull request by kiorky**

### CODE REVIEW

**Review by thatch45 — APPROVED** [review]

**Comment by thatch45** [comment]
Approved, the lint does need to be fixed though

**Comment by cachedout** [comment]
Lint fixed.

**Comment by kiorky** [comment]
:+1: @cachedout thx!

**Comment by rallytime** [comment]
Fixes #40602

**Pull request merged**
