### PR TITLE
clean up `change` attribute from interface dict

### PR DESCRIPTION
**Pull request by svinota**
The attribute is hidden in IPDB from the high-level logics since
pyroute2 version 0.4.2.

Bug-Url: https://github.com/saltstack/salt/issues/41461

### CODE REVIEW

**Review by adelcast — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Comment by isbm** [comment]
I believe such change would _require_ unit test, because nobody knows what these params means. Would be nice to have that prevented from future changes.

**Comment by svinota** [comment]
JFYI: since I have no idea about the `salt` CI, I can put such unit tests on my side in the `pyroute2` integration tests module. If you believe that's a good idea, I can do that now (I anyways plan to add the `salt` compatibility tests)

**Comment by isbm** [comment]
@svinota Just make sure your tests are passing as usually you can run them. And it needs to be re-based as well.

**Comment by cachedout** [comment]
@isbm It doesn't actually need to be rebased. We're testing out a new workflow that allows us as maintainers to rebase PRs interactively from our side without having to rely on contributors. The downside to this is that the way that GitHub has configured this feature, the only way to enable this ability is to "require" that PRs be fully up-to-date with the head of the branch. We're just experimenting for now to try to find a workflow that allows us to make sure that PRs that are merged are always of the highest quality. :]

**Comment by isbm** [comment]
@cachedout Well, Github says "branch is out of date". I hope people won't go "rebase until grey turns green"... :rofl: 

i_cant_i_simply_cant

**Comment by cachedout** [comment]
@isbm Heh, yeah. I don't love how GitHub has designed this to be honest, but this should hopefully really help to make sure that PRs are fully reviewed and high-quality before they are merged. :]

**Comment by isbm** [comment]
@cachedout but Unit tests???

**Comment by cachedout** [comment]
@isbm I assumed that those would happen in a follow-up PR, since @svinota agreed to do them in an earlier comment.

**Comment by svinota** [comment]
@isbm @cachedout pls review — https://github.com/saltstack/salt/pull/41533

**Pull request merged**
