### PR TITLE
Read Pillar files into OrderedDict to preserve source order

### PR DESCRIPTION
**Pull request by benosman**
This pull request attempts to solve Enhancement #12161.

I'm very new to Salt, but It's something i'd like for my own states so I thought working on a patch was a good way to get familiar with the internals of SaltStack.

I've tested the functionality in both master-minion and masterless setup and it keeps the pillars in an OrdererdDict. 

It does not attempt to change the 'master' values, as I don't see the need and that would mean touching the code in many places.

### CODE REVIEW

**Comment by aboe76** [comment]
@rallytime is this still an ongoing issue, because I have recently came across an issue which is similar.
and would like to see this feature in salt?

**Comment by rallytime** [comment]
@aboe76 I am not sure what the status of this is actually. The pull request was originally made against develop in November, but then was subsequently reverted a day or two later because of some unusual test failures as noted above. I am not sure if @benosman made another attempt at this or not. What were the issues you were seeing @aboe76 that might be related? (Perhaps it would be better to address those in the issue this pull request was attempting to fix, as those get more visibility that closed PRs usually...depends on what your issue is I suppose.)

**Comment by aboe76** [comment]
@rallytime thanks will fill the issue with more up to date information. thanks.

**Comment by benosman** [comment]
Sorry, but i've been unable to find the time to work on this recently, and i've found a workaround for my own requirements for now.

Would be keen to see it added in some form, but i think the msgpack version issue may need some discussion.

**Pull request merged**
