### PR TITLE
Change grains['manufacture'] to grains['manufacturer'] for Solaris

### PR DESCRIPTION
**Pull request by gheeney**
This appears to be a typo, as for all other OS's, it is 'manufacturer'.

### What does this PR do?
Renames the 'manufacture' grain to 'manufacturer' on Solaris, for consistency with Linux, etc.

### Previous Behavior
grains['manufacture'] == 'Oracle Corporation'

### New Behavior
grains['manufacturer'] == 'Oracle Corporation'

### Tests written?

No

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by twangboy — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Review by dmurphy18 — CHANGES_REQUESTED** [review]
'manufacture' has been in use for 3 years, wondering if this will break user scripts out in the field

**Comment by gheeney** [comment]
How would a change in behaviour normally be handled ? With a deprecation notice ? Is that something I need to do, or is it done as part of the deployment process ?

**Comment by dmurphy18** [comment]
@gheeney Yes, deprecation process, which means two major releases, which means if you hurry could get deprecation notice in for Neon, and then following that is Sodium.  User's can get quite annoyed when changing the name of grains without a heads up. So grains _manufacturer_ and _manufacture_ with _manufacture_ deprecated

**Comment by gheeney** [comment]
Added PR to Neon to deprecate grains['manufacture'].
https://github.com/saltstack/salt/pull/53505

**Review by dmurphy18 — CHANGES_REQUESTED** [review]
@gheeney Since you open a new PR for this #53505 can you close this PR

**Pull request closed without merging**
