### PR TITLE
systemd.py: Support both update-rc.d and chkconfig as managers of sysv services

### LINKED ISSUE #32169: CommandNotFoundError: update-rc.d during service.enabled on Centos 7
### Description of Issue/Question
I'm installing services on Centos 7.2 and get the exception below. It happens with several different services.  I tried the "develop" branch yesterday and the issue is still occurring.
```py
==> default:      Comment: An exception occurred in this state: Traceback (most recent call last):
==> default:                 File "/usr/lib/python2.7/site-packages/salt/state.py", line 1703, in call
==> default:                   **cdata['kwargs'])
==> default:                 File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1612, in wrapper
==> default:                   return f(*args, **kwargs)
==> default:                 File "/usr/lib/python2.7/site-packages/salt/states/service.py", line 469, in enabled
==> default:                   ret.update(_enable(name, None, **kwargs))
==> default:                 File "/usr/lib/python2.7/site-packages/salt/states/service.py", line 127, in _enable
==> default:                   if __salt__['service.enable'](name, **kwargs):
==> default:                 File "/usr/lib/python2.7/site-packages/salt/modules/systemd.py", line 704, in enable
==> default:                   cmd = [_get_service_exec(), '-f', name, 'defaults', '99']
==> default:                 File "/usr/lib/python2.7/site-packages/salt/modules/systemd.py", line 144, in _get_service_exec
==> default:                   salt.utils.check_or_die(executable)
==> default:                 File "/usr/lib/python2.7/site-packages/salt/utils/__init__.py", line 804, in check_or_die
==> default:                   raise CommandNotFoundError(command)
==> default:               CommandNotFoundError: update-rc.d
```
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

I've attached the config file for rabbitmq.  It has some other items related to rabbitmq and selinux

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
[salt-debug-log.txt](https://github.com/saltstack/salt/files/191088/salt-debug-log.txt)
```
sudo sh install_salt.sh -P -X
unzip the files in  /vagrant or similar directory
ln -s /vagrant/salt-enable-bug /srv/salt
sudo salt-call state.highstate --local -l debug
```
Debug log output attached
[salt-enable-bug.zip](https://github.com/saltstack/salt/files/191087/salt-enable-bug.zip)
[salt-debug-log.txt](https://github.com/saltstack/salt/files/191089/salt-debug-log.txt)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```yaml
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

### PR DESCRIPTION
**Pull request by terminalmage**
Fixes #32169

### CODE REVIEW

**Comment by cachedout** [comment]
@terminalmage Just a quick lint fix please.

**Comment by terminalmage** [comment]
@cachedout Should be good now.

**Comment by cachedout** [comment]
Many thanks.

**Comment by terminalmage** [comment]
NP... looks like Jenkins is on the fritz though.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Pull request merged**
