### PR TITLE
Fix loader integration tests which were actually unit tests

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Failures are valid.

**Comment by s0undt3ch** [comment]
Tests updated, let's see what Jenkins says now.

**Comment by rallytime** [comment]
@s0undt3ch Almost! Looks like just one more left. :)

**Comment by s0undt3ch** [comment]
This last one will have hard to track down. It only presents itself as a failure if all unit tests are executed. This means that another unit tests is messing with something that it should not, or in the wrong way.

**Comment by s0undt3ch** [comment]
Closing. Will reopen a new one which will target most(all) unittests.

**Pull request closed without merging**
