### PR TITLE
pass on huge_tree to PyEZ

### LINKED ISSUE #56386: Junos Proxy not Passing Huge Tree Option
### Description of Issue
The Junos proxy module does not pass the huge_tree option so it is not able to handle large amounts of XML data.

This issue is resolved in https://github.com/saltstack/salt/pull/55318 .

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
```
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.14.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.0
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 5.3
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.4.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core

```

### PR DESCRIPTION
**Pull request by vnitinv**
### What does this PR do?
huge_tree is used to parse huge tree XML 

### What issues does this PR fix or reference?
https://github.com/Juniper/py-junos-eznc/pull/975

### Previous Behavior
Throws error for bug XML RPC-REPLY

### New Behavior
Returns XML data

### Tests written?
No, As this is tested on part of PyEZ and ncclient

### Commits signed with GPG?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by doesitblend** [comment]
Hi @vnitinv . Thanks for submitting this PR to add in the `huge_tree` option. 

I'm using the patches provided on the `junos-eznc` module along with this patch here, but this does not seem to resolve the issue I'm seeing with `invalid command`.

**Comment by vnitinv** [comment]
@doesitblend For this change to work, we need to install PyEZ from github as the code changes are yet to be released into PyPi.

```
pip install -U git+https://github.com/Juniper/py-junos-eznc.git
```

**Comment by doesitblend** [comment]
@vnitinv Thanks for the response! Yes. I had installed this from the Git repository to test whether this solved the issue. I am happy to test again though and I will provide further information to demonstrate how I am testing and the results.

**Comment by doesitblend** [comment]
Hi @vnitinv,

Running this as a stand-alone script it seems to work as expected. However, running through a proxy minion I continue to get "invalid command" when running the following state:

```
{% set now = salt['cmd.run']("date '+%Y%m%d-%H%M%S'") %}
{% if grains['os_family'] == 'junos' %}
get vsrx configuration {{ proxy }}:
  junos.cli:
    - name: show configuration | display set
    - format: text
    - dest: /srv/salt/vsrx/configs/test_state-{{ grains['id']}}-{{ now }}.set

{% endif %}
```

Running that state always produces the following output stored in the designated file:

```
invalid command: show configuration | display set
```

I am including my versions info just to verify that we are using the same setup for testing this:

```
[root@winmaster salt]# pip freeze
Babel==0.9.6
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
bcrypt==3.1.7
cffi==1.13.2
chardet==2.2.1
configobj==4.7.2
cryptography==2.8
decorator==3.4.0
enum34==1.1.6
futures==3.1.1
iniparse==0.4
ipaddress==1.0.16
ipython==5.8.0
ipython-genutils==0.2.0
Jinja2==2.7.2
junos-eznc==2.3.1.dev0
jxmlease==1.0.1
kitchen==1.1.1
lxml==4.4.1
MarkupSafe==0.11
msgpack-python==0.5.6
ncclient==0.6.6
netaddr==0.7.19
paramiko==2.6.0
pathlib2==2.3.5
perf==0.1
pexpect==4.7.0
pickleshare==0.7.5
prompt-toolkit==1.0.18
psutil==2.2.1
ptyprocess==0.6.0
pycparser==2.19
pycrypto==2.6.1
pycurl==7.19.0
Pygments==2.5.2
pygobject==3.22.0
pygpgme==0.3
pyliblzma==0.5.3
PyNaCl==1.3.0
pyparsing==2.4.4
pyserial==3.4
python-linux-procfs==0.4.9
pyudev==0.15
pyxattr==0.5.1
PyYAML==5.1.2
pyzmq==15.3.0
requests==2.6.0
salt==2019.2.2
scandir==1.10.0
schedutils==0.4
scp==0.13.2
selectors2==2.0.1
simplegeneric==0.8.1
six==1.9.0
slip==0.4.0
slip.dbus==0.4.0
SSEAPE==6.0.1+3
tornado==4.2.1
traitlets==4.3.3
transitions==0.7.1
urlgrabber==3.10
urllib3==1.10.2
wcwidth==0.1.7
yamlordereddictloader==0.4.0
yum-metadata-parser==1.1.4

```

```
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: 1.13.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

```

**Comment by vnitinv** [comment]
@doesitblend Did you use the custom proxy module with cherry-picked changes? Asking this question as I see the salt version in use to be 
`salt==2019.2.2`

**Comment by doesitblend** [comment]
Hi @vnitinv, yes I pulled in this commit and the version of junos-eznc you specified from Github as well.

I am happy to setup a screen sharing session if that would helpful to show you how I am producing the error.

**Comment by vnitinv** [comment]
@doesitblend let me know when you want to have the call. I am fine next 2 days.

**Comment by vnitinv** [comment]
@doesitblend Ken, As discussed yesterday overcall. This patch is what is needed for huge_tree and we tested yesterday.
Please help us in merging this change.

**Comment by vnitinv** [comment]
Hi @doesitblend, what's holding saltstack to merge this simple pull request for so long?

**Review by cro — APPROVED** [review]

**Comment by vnitinv** [comment]
@garethgreenaway Can you help us get this to closure. This is just one line code change.

**Comment by doesitblend** [comment]
@garethgreenaway Can you review this PR for merge?

**Review by garethgreenaway — DISMISSED** [review]

**Review by cro — DISMISSED** [review]

**Review by twangboy — DISMISSED** [review]

**Comment by sagetherage** [comment]
@vnitinv @cro looks like this has a merge conflict, so I removed the `Merge Ready` label and this is likely due to recently merged PRs. Can this be addressed soon?

**Comment by vnitinv** [comment]
@sagetherage I have resolved the conflict. Can you please do the needful.

**Review by dwoz — APPROVED** [review]

**Comment by dwoz** [comment]
Going to merge this for now, we can do the work needed to support proxies in another PR.

**Pull request merged**
