### PR TITLE
Return an empty dict for 'changes' instead of 'None'

### LINKED ISSUE #47059: Some states incorrectly return None instead of an empty dict when there are no changes
### Description of Issue/Question

Version 2018.3.0 fails state runs when no changes are made with modules which return "None" instead of an empty dict for the 'changes' data.

See ticket #46985 

### Steps to Reproduce Issue

See the following lines in files in `salt/states/`:
```
boto_cfn.py:        ret['changes'] = None
boto_cfn.py:        ret['changes'] = None
boto_cfn.py:        ret['changes'] = None
boto_iam.py:    ret['changes'] = None
boto_iot.py:            ret['changes'] = None
glassfish.py:            ret['changes'] = None
glassfish.py:            ret['changes'] = None
glassfish.py:        ret['changes'] = None
grafana_datasource.py:            ret['changes'] = None
influxdb_user.py:                ret['changes'] = None
vault.py:        ret['changes'] = None
zenoss.py:        ret['changes'] = None
zenoss.py:        ret['changes'] = None
```

### PR DESCRIPTION
**Pull request by Orlando-Richards**
### What does this PR do?

Replaces any cases where a state would return `None` with an empty dict (`{}`).

### What issues does this PR fix or reference?

Fixes #47059

Ref #47048

### Previous Behavior
States would return `None` in some circumstances.

### New Behavior
States now return `{}` instead of `None`

### Tests written?

No

Note that this fix has not been tested for any knock-on negative effects, it's purely a speculative change against a code structure anomaly.

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by cachedout** [comment]
@ryan-lane Pinging you on Boto changes. :)

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
@OrlandoArcapix It looks like one of these tests is failing here. Can you take a look?

https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu16-py3/8861/testReport/junit/unit.states.test_grafana_datasource/GrafanaDatasourceTestCase/test_present/

**Comment by OrlandoArcapix** [comment]
Looks like the unit test was testing for "None" being returned - I've updated it to check for an empty dict (I think).
```
diff --git a/tests/unit/states/test_grafana_datasource.py b/tests/unit/states/test_grafana_datasource.py
index fb4420c6cd..bd146c7269 100644
--- a/tests/unit/states/test_grafana_datasource.py
+++ b/tests/unit/states/test_grafana_datasource.py
@@ -59,7 +59,7 @@ class GrafanaDatasourceTestCase(TestCase, LoaderModuleMockMixin):
                 )
                 self.assertTrue(ret['result'])
                 self.assertEqual(ret['comment'], 'Data source test already up-to-date')
-                self.assertEqual(ret['changes'], None)
+                self.assertEqual(ret['changes'], {})

             with patch('requests.put') as rput:
                 ret = grafana_datasource.present('test', 'type', 'newurl', profile=profile)
```

**Comment by rallytime** [comment]
@OrlandoArcapix Yep, you've got it. Thanks!

**Pull request merged**
