### PR TITLE
Workaround for py2 builtin, =<3.3 imp and >=3.4 libimport quirks

### PR DESCRIPTION
**Pull request by mgomersbach**
### What does this PR do?
Python 2 has a builtin for "reload"
Python lower than 3.3 has the "imp" module
And Python 3.4 and up switched to "importlib"
This patches to fall back through the different implementations

### What issues does this PR fix or reference?
solves #50127

### Previous Behavior
NameError: name 'reload' is not defined

### New Behavior
Works

### Tests written?

No

### Commits signed with GPG?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by gtmanfred — CHANGES_REQUESTED** [review]
Can these not be used as imports at the top of the file?

Check if `reload` is in globals(), if it is not, then import it with the ImportError exception?

**Comment by mgomersbach** [comment]
Yeah my reasoning was to not evaluate it every time the module was called.
I'll change the PR!

**Comment by mgomersbach** [comment]
The test result seems a fluke? Can it be retriggered?

**Comment by gtmanfred** [comment]
Those failures are unrelated.

**Review by gtmanfred — CHANGES_REQUESTED** [review]
Can we do something more like.

```
if not hasattr(globals()['__builtins__'], 'reload'):
    try:
        from importlib import reload
    except ImportError:
        from imp import reload
```

Also, have you verified that the builtins work on both python2 and py3? i know the handling of builtins was changed in python3

**Comment by mgomersbach** [comment]
Yes 2.7, <=3.3 and >=3.4 have been tested for that code. (does salt run on <=3.3?, because we can then simplify it even more)

**Comment by gtmanfred** [comment]
ok, perfect, then i would still ask that it be changed to be in an if statement instead of doing to try blocks.

**Comment by mgomersbach** [comment]
Will do when I arrive at my destination!
Final question, does saltstack run on python 3.3 anywhere because I can leave out the except then

**Comment by gtmanfred** [comment]
We do not run on 3.3, we support 2.7 and >= 3.4

**Comment by gtmanfred** [comment]
But I do believe we use imp instead of importlib on python3.4 for our loader, so that would probably be good to use there.

**Comment by gtmanfred** [comment]
Also, probably better to just check the python version instead of using try except blocks.

**Comment by mgomersbach** [comment]
imp is deprecated since 3.4.
Version checking would exclude any other versioning from alternative pythons (unless I make a big if else tree).
When I have access to a desktop I will implement your suggestions

**Comment by rallytime** [comment]
@mgomersbach Since we only support python == 2.7 and python >= 3.4, it shouldn't be too big of a tree. You can use the `six.PY2` and `six.PY3` variables, available from `salt.ext.six`.

**Comment by gtmanfred** [comment]
if you want to just disable that check for those two lines, that should be good enough, since you are explicitly only running the import on versions where that import is there.

pylint runs on python2, so it doesn't know that it is wrong.

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
@mgomersbach You can if you'd like to, but you don't have to. Let me know what you want to do.

**Comment by mgomersbach** [comment]
Then let's not. Comments provide enough context I guess.

**Pull request merged**
