### PR TITLE
Don't call zypper with more than one --no-refresh

### PR DESCRIPTION
**Pull request by cbosdo**
### What does this PR do?

Now zypper started being picky and errors out when --no-refresh is
passed twice. Make sure we won't hit this.

### What issues does this PR fix or reference?

None

### Previous Behavior

The following state run on an openSUSE Tumbleweed fails with zypper claiming that only one '--no-refresh' flag is accepted.

    firewall:
      pkg.installed:
        - name: firewalld 

### New Behavior

Running that same state on the same machine gets the firewalld package installed

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by cbosdo** [comment]
@rallytime This PR is ready for review

**Review by brejoc — APPROVED** [review]
lgtm

**Comment by brejoc** [comment]
@rallytime Didn't we have something like `team-suse` that got assigned by jenkins? :thinking:

**Comment by rallytime** [comment]
@brejoc No worries! Nice to "see" you! :)

I am not sure why that bot isn't working anymore. I suspect some team permissions got moved around or something. :-/ 

@Ch3LL or @dubb-b Do you know anything about that? Maybe you can help here.

**Comment by dubb-b** [comment]
@brejoc Im not sure what that functionality was. Can you explain a bit more?

**Comment by rallytime** [comment]
@dubb-b It's the tamarack bot that would assign team reviewers based on the changes in the PR. It seems to no longer be working.

**Comment by dubb-b** [comment]
@Ch3LL there is most likely a bug in the service or needs to handle something. I am seeing 500 errors being returned. 

```Content-Length: 93
Content-Type: text/html; charset=UTF-8
Date: Wed, 30 Jan 2019 20:02:08 GMT
Server: TornadoServer/4.5.3

<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>

But most are making it through. I checked the network and everything there is working.

**Comment by brejoc** [comment]
I'd say this PR is ready to be merged. The testsuite errors seem to be unrelated. @Ch3LL maybe? :wink: 

@dubb-b Any news on team-suse? Seems like it's still now working.

**Review by brejoc — APPROVED** [review]
lgtm

**Review by dwoz — APPROVED** [review]

**Pull request merged**
