### PR TITLE
Activate jid_queue also for SingleMinions (occurs on reconnect)

### PR DESCRIPTION
**Pull request by nasenbaer13**
### What does this PR do?

set jid_queue to emtpy list if not specified

### What issues does this PR fix or reference?

see above

### Tests written?

No

### CODE REVIEW

**Review by cachedout — APPROVED** [review]
This LGTM but would also like @DmitryKuzmenko to please have a look.

**Comment by cachedout** [comment]
re-run py3

**Review by DmitryKuzmenko — APPROVED** [review]
Looks good.

**Comment by nasenbaer13** [comment]
@rallytime: shall I open another pr rebased on 2017.7 branch?

**Comment by rallytime** [comment]
@nasenbaer13 That would be great. Thanks!

**Pull request merged**
