### PR TITLE
master-port 51846 and 52969

### PR DESCRIPTION
**Pull request by mchugh19**
Ports #51846 and #52969 to master.

Likely needed to be merged before #53307 can be rebased.

@gtmanfred @max-arnold

### CODE REVIEW

**Review by Akm0d — APPROVED** [review]

**Comment by Akm0d** [comment]
`unit.test_state.StateCompilerTestCase.test_render_requisite_require_disabled` and `unit.test_state.StateCompilerTestCase.test_render_requisite_require_in_disabled` need to be passing before this can be merged
```Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/test_state.py", line 102, in test_render_requisite_require_disabled
    self.assertEqual(run_num, 0)
AssertionError: 1 != 0```
```Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/test_state.py", line 130, in test_render_requisite_require_in_disabled
    self.assertEqual(run_num, 0)
AssertionError: 1 != 0```

**Comment by mchugh19** [comment]
@Akm0d I think I might need some help here. At first glance the failing tests don't seem to be calling anything in the modified code. I added a few log lines to be sure, and I don't see the output. If all went well, the only functions modified in state.py are `_run_check_unless` and `_run_check_onlyif` and the failing tests don't use those modules. 

Is it possible there is something else impacting those tests?

**Comment by Akm0d** [comment]
@mchugh19 The failing tests were added to the test suite with this PR.  If they don't touch the actual code that was changed then maybe they can be removed?   Debugging it last yesterday I found that 'step_one' and 'step_two' in `high_data` caused `__run_num__` to be incremented twice, which seems to be the correct behavior after stepping through with the debugger.  The tests will pass if `self.assertEqual(run_num, 0)` is changed to `self.assertEqual(run_num, 1)` maybe that's the change we need to make?

**Comment by mchugh19** [comment]
@Akm0d Interesting! Thanks for that! Those tests were not in the original PRs, so I didn't notice those tests in there. I don't want to over complicate things, so I've removed them here. (Looks like they were a left over from @garethgreenaway in #49955)

Thanks much!

**Comment by dwoz** [comment]
@mchugh19 Can you please re-base this on top of the current master?

**Comment by mchugh19** [comment]
Bam! Done!

**Review by garethgreenaway — APPROVED** [review]

**Review by dwoz — CHANGES_REQUESTED** [review]
@mchugh19 Looks like the test failure are related, please have a look.

**Comment by mchugh19** [comment]
@dwoz tests corrected to not rely on local files (and be Debian specific)

**Comment by dwoz** [comment]
The windows tests passed but an issue in the build is causing it to go red, we are working on resolving that issue for windows.

```
OK (total=9298, skipped=1212, passed=8086, failures=0, errors=0)
```

Merging

**Pull request merged**
