### PR TITLE
Change boto_lambda module to use __utils__ instead of salt.utils to allow overriding modules

### PR DESCRIPTION
**Pull request by ecdavis**
### What does this PR do?
Changes `boto_lambda` module to use `__utils__` instead of `salt.utils` to allow overriding modules so that backported modules can be used.

### What issues does this PR fix or reference?
N/A

### Tests written?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by rallytime** [comment]
HI @ecdavis - Thanks for updating this to use the `salt.__utils__` path. It looks like this change has caused a couple of tests to fail. Can you take a look? I suspect it's because the tests need to be updated to use the `salt.__utils__` path instead of `salt.utils.`.

https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/10632/

(Don't worry about that top test for the test_pkgrepo call. That failure isn't related.)

**Comment by ryan-lane** [comment]
+1

**Comment by ecdavis** [comment]
Right you are @rallytime, I fixed the boto_lambda module tests but when I run the module tests locally I'm getting failures in the boto_sns module tests. Not sure if they're related.

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
@ecdavis The boto_sns module tests seem to be ok on the tests running on Jenkins. I wonder if you're maybe hitting something else.

My best guess offhand, without seeing your actual failure, is that maybe a dependency isn't installed locally that the test relies on, and it's not gated properly in the test. The jenkins test runs would likely already have the dependency installed. This is just something I see from time to time, and is just a guess. :)

I think this change is good to go here, so let's get it in. Thank you!

**Pull request merged**
