### PR TITLE
Bump required Tornado version to 4.2.1

### PR DESCRIPTION
**Pull request by cachedout**

### CODE REVIEW

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
It is not clear why yet, but both CentOS and ubuntu tests are failing in the same way on this.

**Comment by s0undt3ch** [comment]
Something appears to not be right with the event system...

**Comment by cachedout** [comment]
@s0undt3ch Yes, I broke the event system briefly yesterday. It should be good now. Re-testing.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Pull request merged**
