### PR TITLE
Add ZMQ socket monitor for master queue channel

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
Refactored ZMQ socket monitor wrapper
Use add socket monnitor to master queue

### CODE REVIEW

**Comment by DmitryKuzmenko** [comment]
Related to #23774

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by DmitryKuzmenko** [comment]
Hm... looks strange. There is no 'zmq_monitor' key in the opts, but it has to be there default to False.
Will investigate.

**Comment by DmitryKuzmenko** [comment]
Missing the default value in master config. Fixed.

**Pull request merged**
