### PR TITLE
pass in empty kwarg for reactor

### PR DESCRIPTION
**Pull request by gtmanfred**
### What does this PR do?
We should just be putting the extra arguments into the main chunk, not into kwarg.

### What issues does this PR fix or reference?
fixes saltstack/salt-jenkins#460

### CODE REVIEW

**Comment by gtmanfred** [comment]
@skizunov we would like to change the chunks.update instead of chunks['kwarg'].update.

When updating kwargs, we had some tests fail for decorators.

https://github.com/saltstack/salt-jenkins/issues/460

I just want to double check that you think this should work too?

Thanks,
Daniel

**Comment by skizunov** [comment]
@gtmanfred : I believe this change will break using the reactor. The reason is that `salt.client.mixins.SyncClientMixin._low` expects the kwargs to be in `kwarg` and not in the parent.

https://github.com/saltstack/salt/blob/develop/salt/client/mixins.py#L384

Having an empty `kwarg` (which would be the result of this change) will still squelch the critical message, but it won't work as expected since it actually expects the kwargs to be in `kwarg` (which is the motivation behind that critical message).

**Comment by skizunov** [comment]
@gtmanfred : One idea is to do both (put in `kwarg` and in parent). I haven't tested that. Will that work for your needs?

**Comment by gtmanfred** [comment]
Can you give me an example of a reactor where this wouldn't work?

Thanks,
Daniel

**Comment by gtmanfred** [comment]
@skizunov what is your opinion on reverting your change, and implementing this one https://github.com/saltstack/salt/pull/42429

It will remove the error, and this reactor state still works and passes the pillar data through.

```
run_example_state:
  runner.state.orch:
    - mods: deploy
    - kwarg:
        pillar:
          event_bar: bar
```

Thanks,
Daniel

**Comment by skizunov** [comment]
@gtmanfred : Reactor sls files always use named arguments for the functions they invoke, for instance:

```
myreactor_on_minion_connect_run:
  runner.myrunner.on_minion_connect:
    - minion_id: {{ data['id'] }}
```

There are no `args` because all arguments are named. The `kwargs` are set here:
https://github.com/saltstack/salt/blob/develop/salt/client/mixins.py#L384

The function itself is invoked here:
https://github.com/saltstack/salt/blob/develop/salt/client/mixins.py#L392

As you can see, with your code change both `args` and `kwargs` that are used to invoke the function will always be empty. `args` is empty by design in this case, but `kwargs` is missing the needed arguments such as in the case above `minion_id`. So this code change will cause any reactor to malfunction if it passes in one or more arguments.

**Comment by skizunov** [comment]
@gtmanfred : Implementing #42429 will have the same issue as what I just described above.

**Comment by gtmanfred** [comment]
The error is only cosmetic, because we do not always pass kwarg.  #42429 just makes sure that we always call the `_low` with a `kwarg` key in the `low` data.  So if you do not set any kwarg object in your state, we make sure that an empty one gets passed.

It would be the equivalent of running

```
myreactor_on_minion_connect_run:
  runner.myrunner.on_minion_connect:
    - minion_id: {{ data['id'] }}
    - kwarg: {}
```

**Comment by skizunov** [comment]
@gtmanfred : The problem is that the `minion_id` won't actually be passed to the function (as intended) in your case. If doing both isn't an option, then perhaps adding in a parameter to `compile_high_data` to identify the use case of the caller will work. For example:

```
 def compile_high_data(self, high, reactor=False):
```

And then use the parent in the `reactor=False` case and use `kwarg` in the `reactor=True` case. Adjust the caller to use `reactor=True` when appropriate.

**Comment by gtmanfred** [comment]
The method that you are using was deprecated in Nitrogen 

https://github.com/saltstack/salt/blob/2016.11/salt/client/mixins.py#L384

The change in 2017.7 should be to pass it in kwarg

```
myreactor_on_minion_connect_run:
  runner.myrunner.on_minion_connect:
    - kwarg:
        minion_id: {{ data['id'] }}
```

**Comment by skizunov** [comment]
@gtmanfred : I didn't know that. My apologies for the distraction. To be complete, I would make your solution look like:

```
            if 'arg' not in kwargs:
                kwargs['arg'] = []
            if 'kwarg' not in kwargs:
                kwargs['kwarg'] = {}
```

Due to this code here:

https://github.com/saltstack/salt/blob/develop/salt/client/mixins.py#L364

**Comment by gtmanfred** [comment]
Go Go Jenkins!

**Comment by gtmanfred** [comment]
We already pass an empty arg value here.

https://github.com/saltstack/salt/blob/develop/salt/utils/reactor.py#L284

**Comment by skizunov** [comment]
@gtmanfred : I am referring to the `arg` kwarg which is different than what is passed where you stated. I believe this code will get hit with your current changes (when it shouldn't):

https://github.com/saltstack/salt/blob/develop/salt/client/mixins.py#L365

My change would prevent that code from getting hit. At least theoretically, since I am not in a position to test this out at the moment.

**Comment by gtmanfred** [comment]
So, I went back and tested the change with the fixed .update, and it was breaking the kwarg: key.

It is also worth noting that 'arg' is not required to be in the low data, so I think we are ok with just this change for now.

Thanks for the feedback,
Daniel

**Comment by skizunov** [comment]
@gtmanfred : Thanks for investigating this. If `arg` isn't required, then this change looks good as is.

**Review by skizunov — APPROVED** [review]

**Comment by cachedout** [comment]
Thank you for taking time out of your day to help, @skizunov. I appreciate it. :]

**Comment by skizunov** [comment]
@gtmanfred : I cherry-picked this change and tested it with my own branch. It looks like the change I suggested was necessary:

```
            if 'arg' not in kwargs:
                kwargs['arg'] = []
            if 'kwarg' not in kwargs:
                kwargs['kwarg'] = {}
```

I changed all my SLS files to specify `kwarg` (but not explicitly specify `arg`). Without that additional change above (and without explicitly specifying `arg`), I get this:

```
C:\Program Files\National Instruments\Shared\salt>salt-master -l warning
Exception occurred in runner nisysmgmt.on_presence_change: Traceback (most recen
t call last):
  File "C:\Program Files\National Instruments\Shared\salt\bin\lib\site-packages\
salt\client\mixins.py", line 368, in _low
    expected_extra_kws=CLIENT_INTERNAL_KEYWORDS
  File "C:\Program Files\National Instruments\Shared\salt\bin\lib\site-packages\
salt\utils\__init__.py", line 1115, in format_call
    used_args_count
salt.exceptions.SaltInvocationError: on_presence_change takes at least 3 argumen
ts (0 given)
```

With that change, it fixes this issue. A work-around is to explicitly specify an empty `arg` in the SLS file. Is there a reason not to add that code specified above? I can always use my work-around by explicitly specifying an empty `arg` in the SLS file, but your documentation doesn't document that that is required.

**Comment by gtmanfred** [comment]
Can you provide and example sls file where this shows up please? Because I
was not able to replicate this yesterday.

**Comment by skizunov** [comment]
Sure, the SLS file looks like this (we tend to use `#py` to avoid the YAML parser, but the YAML equivalent should be obvious):

nisysmgmt_presence_change.sls
```
#!py

def run():
    return {
        'nisysmgmt_on_presence_change_run': {
            'runner.nisysmgmt.on_presence_change': [
                {
                    'kwarg': {
                        'new': data['new'],
                        'lost': data['lost'],
                        'stamp': data['_stamp']
                    }
                }
            ]
        }
    }
```

Config entry:

```
presence_events: True

reactor:
  - 'salt/presence/change':
    - salt://reactor/nisysmgmt_presence_change.sls
```

Function prototype in runner:

```
def on_presence_change(new, lost, stamp):
```

It also reproduces with this SLS and config based on minion start which is a little easier to set up than presence change events:

SLS (nisysmgmt_minion_connect.sls):

```
#!py

def run():
    return {
        'nisysmgmt_on_minion_connect_run': {
            'runner.nisysmgmt.on_minion_connect': [
                {
                    'kwarg': {
                        'minion_id': data['id'],
                        'stamp': data['_stamp']
                    }
                }
            ]
        }
    }
```

Config entry:

```
reactor:
  - 'salt/minion/*/start':
    - salt://reactor/nisysmgmt_minion_connect.sls
```

Function prototype in runner:

```
def on_minion_connect(minion_id, stamp):
```

These should not be uncommon use cases for reactor events since they both are based on built-in events. Let me know if you have any further questions on setting a mock of this scenario up.

**Comment by gtmanfred** [comment]
You are right.

**Pull request merged**
