### PR TITLE
Fixing salt_proxy module to support wider outputs

### PR DESCRIPTION
**Pull request by jemershaw**
### What does this PR do?
There is an issue when piping `ps` into `grep` you miss some of the output, which will spawn another daemon of the salt_proxy.

### What issues does this PR fix or reference?
This allows the `ps` command output to contain the full output into `grep`.

### Tests written?
No

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by garethgreenaway** [comment]
@jemershaw Would you be able to rebase this PR against the master branch.  Thanks!

**Comment by sagetherage** [comment]
@jemershaw Would you be able to rebase this PR against the master branch. Thanks!

**Comment by jemershaw** [comment]
@sagetherage I updated it.

**Comment by garethgreenaway** [comment]
@jemershaw Apologies for the delay on this one.  Would you be able to write a test for this change?  If you need some assistance with this please let us know.  Thanks!

**Comment by dwoz** [comment]
Closing this due to inactivity.  Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
