### PR TITLE
Improve test suite tutorial

### PR DESCRIPTION
**Pull request by ixs**
Turns out, it's actually helpful to install the pytest tools before
trying to run the test suite.

### CODE REVIEW

**Review by waynew — APPROVED** [review]

**Review by Ch3LL — APPROVED** [review]

**Comment by ixs** [comment]
Do we wanna merge this? @Ch3LL how about it?

**Comment by waynew** [comment]
@ixs yes - but also sort of? 🙃 

We're in some discussions related to our test infrastructure stability efforts (that you may have encountered recently) that might impact what branch we merge this into. From your perspective you can consider the "merge ready" label merged.

**Comment by dwoz** [comment]
This needs to go to the `master` branch

**Comment by ixs** [comment]
@dwoz by the time this PR was opened, there was no master branch, only develop.

So what's needed to have this merged?

**Comment by mchugh19** [comment]
@ixs Since your PR was opened, there was a change of strategy with the development and release process. Previously work used to flow into the develop branch, and each release would fork from there. This meant a lot of backporting to supported branches as fixes were added to develop.
There is now a new merge/release strategy where master is always releaseable (with a significant improvement to the test suite). New work now flows into the master branch, and releases are tagged from there.

Unfortunately, this means that PRs submitted before this was done need to be rebased on top of the master branch. So in your case, this should be a hopefully simple change to rebase on top of master, and to edit this PR to apply to the master branch (or close to submit a fresh one).

**Comment by s0undt3ch** [comment]
On top of what @mchugh19 already mentioned, we also switched the way we run our test suite.
The "only" things you need is python and `nox-py2` installed.
Nox will take care of all other python dependencies when running tests.
Still, the docs need to be updated and @ch3ll already did some work around that.

This particular change should not be ported to the master branch since it's no longer accurate.

**Pull request closed without merging**
