### PR TITLE
Add function to return TLS cert expiration date

### PR DESCRIPTION
**Pull request by terminalmage**
Refs: #7424

### CODE REVIEW

**Review by cachedout — APPROVED** [review]
Nice!

**Comment by terminalmage** [comment]
I tested on an openvpn TLS cert, I didn't create a separate one specifically for a test, but I can.

**Comment by cachedout** [comment]
I'm thinking of automated tests here. Is that what you were suggesting you would create? Or just testing manually on another cert?

**Comment by terminalmage** [comment]
Yeah, I was thinking of automated tests, I just need to create a cert for the purposes of writing such a test, since I don't want to use my openvpn certs for a test.

**Comment by terminalmage** [comment]
Unit test added.

**Comment by rallytime** [comment]
re-run centos

**Pull request merged**
