### PR TITLE
Merge forward from 2015.5 to develop

### PR DESCRIPTION
**Pull request by basepi**
Merge forward from 2015.5 to develop

```
    Conflicts:
        doc/ref/modules/all/salt.modules.ipmi.rst
        doc/ref/modules/all/salt.modules.system_profiler.rst
        salt/fileclient.py
        salt/loader.py
        salt/modules/tls.py
        salt/modules/win_path.py
        salt/states/pkg.py
        salt/utils/event.py
        salt/utils/pagerduty.py
        tests/unit/modules/seed_test.py
```

### CODE REVIEW

**Comment by basepi** [comment]
@joejulian Apparently the develop and 2015.5 versions of the tls module have diverged enough that your tests need to be modified. Can you look at the Ubuntu 14.04 test failures above and advise? I don't have time at the moment to fix those tests.

**Comment by joejulian** [comment]
I can look at this on Monday.

**Comment by basepi** [comment]
@joejulian Alright, keep me posted. If we can't get those tests resolved today, I may just remove them and have you add them back in on the develop branch in a separate pull request. Merge forwards get very messy if we don't get them merged every couple of days.

**Comment by joejulian** [comment]
Looks like there's a bunch of __salt__ keys that need to be mocked. Apparently that didn't need to be done in 2015.5. I'm fixing it now.

**Comment by basepi** [comment]
@joejulian OK, thanks. Do you me to just disable them in this pull request and you can enable/fix them in a separate pull request, or do you want to do a pull request against my merge-forward-develop branch, or what?

**Comment by joejulian** [comment]
I'll have a PR for your branch shortly. 

On June 8, 2015 3:36:20 PM PDT, Colton Myers <notifications@github.com> wrote:
>@joejulian OK, thanks. Do you me to just disable them in this pull
>request and you can enable/fix them in a separate pull request, or do
>you want to do a pull request against my merge-forward-develop branch,
>or what?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/saltstack/salt/pull/24459#issuecomment-110163731

-- 
Joe Julian 
Cloud Storage Expert 
http://joejulian.name

**Pull request merged**
