### PR TITLE
Added parameters and capabilities to the create_stack boto_cfn.py module...

### PR DESCRIPTION
**Pull request by polliard**
.... These additions will help when integrating with saltstack's enterprise reactor for ServiceNow

### CODE REVIEW

**Comment by polliard** [comment]
This needs to be backported to 2015.2. Currently, working from _modules

**Comment by jfindlay** [comment]
@polliard, there are some [lint errors](https://jenkins.saltstack.com/job/salt-pr-lint-n/3688/violations/file/salt/modules/boto_cfn.py/).

**Comment by polliard** [comment]
@jfindlay, not to sound dumb but once I fix and commit, do I cancel this pull and resubmit ?

**Comment by rallytime** [comment]
@polliard Not dumb at all! Fix and commit your changes to the same local branch that you made this pull request on. Then when you push your changes, the commit will show up here and the tests will start again. Does that make sense?

**Comment by jfindlay** [comment]
@polliard, it's easier to edit or add new commits to the same branch without having to recreate a new pull request, see step 9 here, http://docs.saltstack.com/en/latest/topics/development/contributing.html#sending-a-github-pull-request.

**Comment by polliard** [comment]
@jfindlay @rallytime.  I cherry-picked the boto_cfn.py from develop and merged it into 2015.2.  I am going to wait until this jenkins completes before submitting the pull request.  The RS CENOTS 7 build is failing because of environmental issues and not my code :)

Thanks again for the help.

**Comment by polliard** [comment]
Found an error where the code is passing the arguments from the reactor incorrectly.  Withdrawing this pull request till we figure out what source.

More to come.... Sorry for the delay.

**Pull request closed without merging**
