### PR TITLE
lxc: reconfigure fixes

### PR DESCRIPTION
**Pull request by kiorky**

### CODE REVIEW

**Comment by kiorky** [comment]
cc @terminalmage

**Comment by kiorky** [comment]
wait for merge, i have other fixes to add to reconfigure

**Comment by kiorky** [comment]
done !

**Comment by terminalmage** [comment]
This is that function that's new in develop, right?

**Comment by kiorky** [comment]
yep

**Comment by terminalmage** [comment]
Cool, just making sure we got the fixes into the correct branch.

**Pull request merged**
