### PR TITLE
document and check dict type for pip env_vars

### LINKED ISSUE #27372: pip.installed state fails when env_vars is not a dict
```saltstack
pip_pkgs:
  pip.installed:
    - user: vagrant
    - bin_env: /home/vagrant/calamari/env
    - requirements: /home/vagrant/calamari/requirements/2.7/requirements.txt
    - download_cache: /vagrant/pip_cache
    - env_vars: SWIG_FEATURES=-cpperraswarn
    - require:
      - virtualenv: virtualenv
      - pip: pyzmq
```
When I run it in 2015.8.0 I get this error:
```python-traceback
 ID: pip_pkgs
    Function: pip.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1591, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/states/pip_state.py", line 694, in installed
                  trusted_host=trusted_host
                File "/usr/lib/python2.7/dist-packages/salt/modules/pip.py", line 707, in install
                  os.environ.update(env_vars)
                File "/usr/lib/python2.7/os.py", line 479, in update
                  for k, v in dict:
              ValueError: need more than 1 value to unpack
     Started: 15:39:12.626664
    Duration: 13.323 ms
     Changes:   
```

When I step through the code it works just fine when env_vars is a dict.
so this works:

```saltstack
pip_pkgs:
  pip.installed:
    - user: vagrant
    - bin_env: /home/vagrant/calamari/env
    - requirements: /home/vagrant/calamari/requirements/2.7/requirements.txt
    - download_cache: /vagrant/pip_cache
    - env_vars:
        SWIG_FEATURES: -cpperraswarn
        SOMETHING_ELSE: -completely_different
    - require:
      - virtualenv: virtualenv
      - pip: pyzmq
```

It would be nice for pip.py to fail in a more helpful way or me more tolerant of different input types.
At the least an example in the docs would go a long way.

Thank you.

### PR DESCRIPTION
**Pull request by jfindlay**
Fixes #27372.

### CODE REVIEW

**Comment by basepi** [comment]
Doesn't our OrderedDict return true on `isinstance(obj, dict)` calls? Should we just use that instead?

**Comment by jfindlay** [comment]
@basepi, what you're saying makes sense, but I don't know how you are thinking of applying it to the current situation.

**Comment by basepi** [comment]
Line 728. You used `isinstance(env_vars, Mapping)` and added a new import. Can't you just use `dict` instead of a new import?

**Comment by jfindlay** [comment]
@basepi, done.

**Comment by basepi** [comment]
Sorry to be nit-picky. I was curious as much as anything. If I was incorrect I wanted to know. =)

**Comment by jfindlay** [comment]
@basepi, no problem, my only motivation was academic, `Mapping` being the base type for all `dict`-like objects, but as you indicated, it's going to be an `OrderedDict` anyway, so saving the trouble of an import is an obvious win. :-)

**Pull request merged**
