### PR TITLE
add_dd_monitor_api_calls: Add monitor API calls to datadog_api

### PR DESCRIPTION
**Pull request by ac-hibbert**
Change-Id: I6957f6faea24ef1df6ee4d0fdd676d9558c2828e

### What does this PR do?

This PR adds functionality to the datadog_api execution module to get, create, update and delete monitors in datadog through the API

### What issues does this PR fix or reference?

N/A

### Tests written?

No

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by cachedout — CHANGES_REQUESTED** [review]
Hi @hibbert. First, welcome to the SaltStack community. We're glad you're here!

In order for us to get this in, we'll need to add some tests. Here's a good place to start reading and we're here to help if we can. Thanks!

https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html

**Comment by cachedout** [comment]
@hibbert Did you see the above comment regarding tests?

**Comment by cachedout** [comment]
Hi again @hibbert. We would love to get this in but we need some test coverage first. Do you have a little time to add that?

**Comment by hibbert** [comment]
Hey, sorry, I haven't had time to do this yet. Hopefully will get to it soon

**Comment by rallytime** [comment]
I am going to close this PR since we haven't heard back here for quite some time. We can certainly re-open this when you're ready, or feel free to submit a new pull request. Thanks!

**Pull request closed without merging**
