### PR TITLE
Bugs/py3 tests nitrogen

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
### What does this PR do?
Fixed some bugs in tests I've found during work on the Py3 tests memleak issue.

### What issues does this PR fix or reference?
Related: https://github.com/saltstack/salt-jenkins/issues/333

### CODE REVIEW

**Review by s0undt3ch — APPROVED** [review]

**Review by rallytime — CHANGES_REQUESTED** [review]
@DmitryKuzmenko It looks like one of these tests is failing here:
`integration.shell.test_master.MasterTest.test_exit_status_correct_usage` on CentOS 7.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@rallytime I suspect that was an unrelated failure. I am re-running these tests to verify.

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
@cachedout Ah, you're right. I thought it might be related, but it is passing now.

**Comment by DmitryKuzmenko** [comment]
Sorry, I've missed notifications for some reason.
@rallytime that test was failing sometimes by an issue in the test suite and I've modified it slightly to make it always fail checking that issue. After that I've submitted the fix for `pytest-salt` and Pedro merged it.
Probably that failed run has been done with old `pytest-salt`.

**Comment by rallytime** [comment]
@DmitryKuzmenko Ok, so pytest-salt needs to be updated to a newer version on the various Jenkins nodes? Because I do see that failing on some of the branch tests in nitrogen. I'll look into how that works.

**Comment by rallytime** [comment]
@DmitryKuzmenko Actually, it looks like `pytest-salt` gets installed from the `HEAD` of the master branch, so nothing needs to be updated in terms of running the latest version on the test VMs. Your PR to pytest-salt was merged in already there a couple of days ago. So it seems this has introduced some flakiness (or exposed flakiness that was already there?) into the test suite.

**Comment by DmitryKuzmenko** [comment]
@rallytime sounds good! Thanks for checking.

**Pull request merged**
