### PR TITLE
Fix apt repository key issue. #62729

### LINKED ISSUE #62729: [BUG] _decrypt_key overwrites the supplied key with an empty file.
**Description**
In aptpkg.py the _decrypt_key function only alters the decrypted file name if the supplied file has no suffix. Because of this, the gpg call has the outgoing file set to the same name as the input file and the file gets zeroed. This is on line 2293 of the aptpkg.py file in the master branch. 

**Steps to Reproduce the behavior**
Running the zabbix-repo state with the key_url added will end up with /etc/apt/keyrings/zabbix.gpg being empty key existing. 
```
  pkgrepo.managed:
    - name: deb [arch=amd64 signed-by=/etc/apt/keyrings/zabbix.gpg] https://repo.zabbix.com/zabbix/{{ zabbix.version_repo }}/{{ salt['grains.get']('os')|lower }} {{ salt['grains.get']('oscodename') }} main
    - file: /etc/apt/sources.list.d/zabbix.list
    - key_url: https://repo.zabbix.com/zabbix-official-repo.key
    - clean_file: True
    - aptkey: False
```

**Expected behavior**
 /etc/apt/keyrings/zabbix.gpg should end up with the unarmoured key. Instead it is empty and the repo fails. 

**Versions Report**
<details><summary>salt --versions-report</summary>
```
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.13 (main, Aug 23 2022, 18:31:15)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 22.04 jammy
        locale: utf-8
       machine: x86_64
       release: 5.4.0-99-generic
        system: Linux
       version: Ubuntu 22.04 jammy
```

### PR DESCRIPTION
**Pull request by waynegemmell**
### What does this PR do?
Currently the apt repository key that is download is saved as a blank file if it is armoured. This circumvents this PR puts the encrypted file into a temp file to prevent this and makes sure that the key is written to the correct location as per the repo file. 

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/62729

### Previous Behavior
Currently the apt repository key that is download is saved as a blank file if it is armoured.

### New Behavior
The file is the correct key, not an empty file. 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by Ch3LL** [comment]
I believe this PR will resolve this issue: https://github.com/saltstack/salt/pull/62571 which was in 3005.1. 

Can you test v3005.1 and see if its still an issue.

The changes for that PR will make it into the `master` branch in this merge forward PR: https://github.com/saltstack/salt/pull/62810

**Comment by waynegemmell** [comment]
Damn! What a waste of time. I was working on master and thought that if there were any updates they would be there. I'll validate in a bit but it looks like the same issue.

**Comment by waynegemmell** [comment]
@Ch3LL It looks like the PR you mentioned does the job. The only thing that doesn't look to be happening that I added was to ensure that the signed-by path is where the key ends up. 

Other point. How do I do these PRs without overlapping other's work? I was working on master, which I thought would reflect any work done.

**Comment by Ch3LL** [comment]
When we are working on a point release we submit fixes to the `freeze` branch, and then we merge forward the git tag when it's released to ensure the correct git tag version is included in the versions report when developing off of master. So in the future you can check freeze and master or previous issues already submitted.

We are prioritizing the merge of this one: https://github.com/saltstack/salt/pull/62810 

so you can rebase once thats merged in and we can get your additional fix in. Thanks.

**Comment by Ch3LL** [comment]
Looks like pre-commit, lint and some OS tests are related failures. Can you investigate the failures? thanks

**Comment by waynegemmell** [comment]
@Ch3LL I fixed the linter issue. I really have no idea about the OS issues. Can you sort or give me a pointer?

**Comment by Ch3LL** [comment]
The tests are failing because because `keyfile` is not required.

**Comment by waynegemmell** [comment]
Keyfile is the full path of the signedby value. There is quite a lot of acrobatics around deriving paths to decide where the key must be stored while the only valid location is the one in the signedby value. I simplified some of these path changes as such. You'll see that it is set explicitly in line 2870. My concern is that someone may set the keyfile or keydir parameter to a different value from the signedby value and then the configuration is invalid.

**Comment by waynegemmell** [comment]
Keyfile is the full path of the signedby value. There is quite a lot of acrobatics around deriving paths to decide where the key must be stored while the only valid location is the one in the signedby value. I simplified some of these path changes as such. You'll see that it is set explicitly in line 2870. My concern is that someone may set the keyfile or keydir parameter to a different value from the signedby value and then the configuration is invalid.

**Comment by Ch3LL** [comment]
Thanks for explaining, that makes sense. I guess one more improvement is if kefyile is set and keydir is not that keydir becomes `keyfile.parent`, because we do use that when `keyid` is set. But thats not required for this PR.

So yeah the tests will just need to be updated to ensure keyfile is required.

**Comment by waynegemmell** [comment]
Can you point me in the right direction please. I'm not sure where these tests are.

**Comment by Ch3LL** [comment]
These are the tests that are failing:

[tests.pytests.functional.modules.test_aptpkg.test_get_repo_keys[False-salt-archive-keyring.gpg]](https://jenkins.saltproject.io/job/pr-debian-10-amd64-py3-pytest/job/PR-62815/4/testReport/junit/tests.pytests.functional.modules/test_aptpkg/test_get_repo_keys_False_salt_archive_keyring_gpg_/)
    [tests.pytests.functional.modules.test_aptpkg.test_get_repo_keys[False-SALTSTACK-GPG-KEY.pub]](https://jenkins.saltproject.io/job/pr-debian-10-amd64-py3-pytest/job/PR-62815/4/testReport/junit/tests.pytests.functional.modules/test_aptpkg/test_get_repo_keys_False_SALTSTACK_GPG_KEY_pub_/)
    [tests.pytests.functional.modules.test_aptpkg.test_add_del_repo_key[False-salt-archive-keyring.gpg]](https://jenkins.saltproject.io/job/pr-debian-10-amd64-py3-pytest/job/PR-62815/4/testReport/junit/tests.pytests.functional.modules/test_aptpkg/test_add_del_repo_key_False_salt_archive_keyring_gpg_/)
    [tests.pytests.functional.modules.test_aptpkg.test_add_del_repo_key[False-SALTSTACK-GPG-KEY.pub]](https://jenkins.saltproject.io/job/pr-debian-10-amd64-py3-pytest/job/PR-62815/4/testReport/junit/tests.pytests.functional.modules/test_aptpkg/test_add_del_repo_key_False_SALTSTACK_GPG_KEY_pub_/)

So that would be in the file tests/pytests/function/modules/test_aptpkg.py

**Comment by waynegemmell** [comment]
That's odd. I haven't touched any of that. I can't see any issues. I'll look again with Monday eyes.

**Comment by waynegemmell** [comment]
I don't think the way I did this is very testable. Maybe it's worth forgetting about. I still think that there should be a check that the key path should be enforced. I just don't think it should be done this way. I think I'm going to just delete it.

**Pull request closed without merging**
