### PR TITLE
Added ES index settings methods

### PR DESCRIPTION
**Pull request by Oloremo**
### What does this PR do?
Added two Elasticsearch API methods:
put_settings
get_settings

To the Salt Elasticsearch module

### What issues does this PR fix or reference?
#53736 

### Previous Behavior
These methods were not supported 

### New Behavior
These methods now supported

### Tests written?
Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by Akm0d — APPROVED** [review]
This looks excellent. Thank your for the PR and :+1: to good tests.

**Comment by dwoz** [comment]
@Oloremo Can you please rebase and open the PR against `master`?

**Comment by Oloremo** [comment]
@dwoz yeah but it actually needs some rework since in API `put_settings(**kwargs)` and I don't support it here.

**Comment by Oloremo** [comment]
Backport to master: https://github.com/saltstack/salt/pull/55721

**Pull request closed without merging**
