### PR TITLE
Add missing files to release tarball

### PR DESCRIPTION
**Pull request by bdrung**
The release tarball misses several relevent files for documentation or the unit tests. This set of commits add them.

Add CODE_OF_CONDUCT.md, CONTRIBUTING.rst, NOTICE, and SUPPORT.rst into the release tarball, because these files are also useful there.

The unit tests in `unit.test_config.SampleConfTest` require the directories `conf/cloud.profiles.d`, `conf/cloud.providers.d`, and `conf/cloud.maps.d` to be present and to contain the relevant files.
The unit test `unit.utils.test_extend.ExtendTestCase` needs to access the files in the `templates` directory.

The test case `tests.unit.test_module.names.ZyppPluginsTestCase` requires `scripts/suse/zypper/plugins/commit/zyppnotify`.

### CODE REVIEW

**Review by dmurphy18 — CHANGES_REQUESTED** [review]
Manifest changes appear fine, but  @bdrung wondering why the deletion of write_manifest in the CloudSdist class.

**Comment by bdrung** [comment]
The forth commit explains why `write_manifest` is removed:

> Include sripts/suse in release tarball
> 
> The test case `tests.unit.test_module.names.ZyppPluginsTestCase`
> requires `scripts/suse/zypper/plugins/commit/zyppnotify`.
> 
> Therefore include `sripts/suse` in the release tarball.

**Comment by dmurphy18** [comment]
@bdrung There has been talk of making Salt-Cloud it's own thing again, similar to how to used to be years ago.  With the new Cloud Working Group, I am not sure ti they would want to keep this or if they have even plans yet.  I shall check and get their comments on it.

**Comment by dmurphy18** [comment]
@bdrung Chatted with Cloud Working Group and they need write manifest to stay as they have plans to rewrite Salt-Cloud.  Can you remove its deletion.

**Comment by bdrung** [comment]
@dmurphy18 Okay, I dropped that commit.

**Review by dmurphy18 — APPROVED** [review]

**Comment by dmurphy18** [comment]
re-run all

**Comment by dmurphy18** [comment]
re-run full all

**Review by garethgreenaway — APPROVED** [review]

**Review by s0undt3ch — APPROVED** [review]

**Pull request merged**
