### PR TITLE
Deprecating 'user'/'group' in state cmd

### PR DESCRIPTION
**Pull request by The-Loeki**
### What issues does this PR fix or reference?

https://github.com/saltstack/salt/issues/32579
### Previous Behavior

`user` is `runas`, `group` doesn't actually do anything
### New Behavior

`runas` is `user` and `user` and `group` get a deprecation warning until Nitrogen

### CODE REVIEW

**Comment by The-Loeki** [comment]
w00h00! Ready4merge :dancer:

**Comment by cachedout** [comment]
This is fine but I'm not really in favor of introducing deprecations in a point release. I would rather put this into 2016.3 or develop.

**Comment by The-Loeki** [comment]
@cachedout I (usually) agree fully but check the conversation in #32579; this is a feature that actually should've been deprecated quite a few releases ago, so that's why we figured it's OK

And just to be nice we'll keep warning until Nitrogen, so anyon still has 2/3 releases to get up to speed.

**Comment by thatch45** [comment]
@The-Loeki sorry, I am going to side with @cachedout on this one, you raise valid points but I think it will be wiser to keep with major releases only for introducing deprecation warnings, so this should go into 2016.3 or develop. Thanks!

**Comment by The-Loeki** [comment]
And there it went again :( closing this one...

**Comment by The-Loeki** [comment]
@cachedout / @thatch45 / @jfindlay : Fair enough I guess, after severly borking this PR yet again (my git-fu apparently sux) I've now created https://github.com/saltstack/salt/issues/32613 for the same against 2016.3.

**Comment by thatch45** [comment]
Thanks @The-Loeki ! You are fantasic!

**Comment by damon-atkins** [comment]
2016.3  is when the Deprecate warning starts and then warnings are removed in 2016.8 as well as the compatibility.
People currently on 2015.8 and then jump to 2016.12  will not get any warnings.

Is it documented how many versions or amount of time warning will be available for, is their a long term version strategy.  e.g. 2015.8  consider a long term release and all Deprecate warnings are back ported. And therefore before upgrade to 2016.12 people need to upgrade to 2015.8 to get the warnings first.

Is what every saltstack upgrade plan; When is support dropped.  is it documented the life cycle of products.  Had a quick look, could not see anything.

**Comment by thatch45** [comment]
we should push it back another version then, when deprecation warning are introduced they should be at least 3 releases ahead

**Comment by The-Loeki** [comment]
@damon-atkins AFAIK (@thatch is da man here) Salt supports the last 2 majors.

As part of their release process they work through all deprecation warnings and the deprecated functionality will be removed as part of that when the warning is bombed on that release.

**Pull request closed without merging**
