### PR TITLE
Adding Azure Service Principal auth for Azure ARM 

### PR DESCRIPTION
**Pull request by nzthiago**
### What does this PR do?
Extends the Azure ARM support to allow for [Service Principal authentication](https://docs.microsoft.com/en-us/azure/resource-group-authenticate-service-principal-cli). It allows scoped access to Azure resources without the need to use your own credentials. 

### What issues does this PR fix or reference?
None.

### Previous Behavior
Only Username and Password auth support for Azure ARM.

### New Behavior
Both Username and Password and Service Principal support for Azure ARM.

### Tests written?
No automated test. Has been manually tested.

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by techhat** [comment]
+1, this is awesome!

**Comment by rallytime** [comment]
Very nice. Thank you @nzthiago

**Comment by justindesilets** [comment]
I'm working on a test setup right now. Using CentOS 7 and installed salt via the bootstrap script using the development branch. Right now I've configured: ```/etc/salt/cloud.providers.d/azure.conf
azure-test:
  driver: azure
  subscription_id: $value
  tenant: $value
  client_id: $value
  secret: $value```
However when I try and test the functionality out I am receiving: ```[root@salt-cloud-test salt]# salt-cloud --list-images azure-test
[WARNING ] The required 'certificate_path' configuration setting is missing from the 'azure' driver, which is configured under the 'azure-test' alias.
[WARNING ] The cloud driver, 'azure', configured under the 'azure-test' cloud provider alias, could not be loaded. Please check your provider configuration files and ensure all required dependencies are installed for the 'azure' driver.
In rare cases, this could indicate the 'azure.get_configured_provider()' function could not be found.
Removing 'azure' from the available providers list
Error: There was an error listing images: No cloud providers matched 'azure-test'. Available selections: ```
Am I just being too eager to test this functionality or am I implementing it wrong?
```[root@salt-cloud-test salt]# salt --versions-report
Salt Version:
           Salt: 2016.11.2-2500-g89283e0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.6.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core```

```[root@salt-cloud-test salt]# pip show azure
Name: azure
Version: 1.0.3
Summary: Microsoft Azure Client Libraries for Python
Home-page: https://github.com/Azure/azure-sdk-for-python
Author: Microsoft Corporation
Author-email: ptvshelp@microsoft.com
License: Apache License 2.0
Location: /usr/lib/python2.7/site-packages
Requires: azure-mgmt, azure-servicebus, azure-storage, azure-servicemanagement-legacy```

**Comment by techhat** [comment]
Hi @justindesilets. I haven't used this functionality yet, but I do know that you need the `driver` to be set to `azurearm`. You also need to `pip install azure==2.0.0rc6`.

**Comment by justindesilets** [comment]
I was able to get the updated azure install going:
```
[root@salt-cloud-test ~]# pip show azure
Name: azure
Version: 2.0.0rc6
Summary: Microsoft Azure Client Libraries for Python
Home-page: https://github.com/Azure/azure-sdk-for-python
Author: Microsoft Corporation
Author-email: ptvshelp@microsoft.com
License: MIT License
Location: /usr/lib/python2.7/site-packages
Requires: azure-batch, azure-servicebus, azure-storage, azure-servicemanagement-legacy, azure-mgmt
```
However when I tried setting `driver: azurearm` I received this error:
```
[root@salt-cloud-test ~]# salt-cloud --list-images azure-test
[WARNING ] Missing dependency: 'azurearm'. The azurearm driver requires 'azurearm' to be installed.
[WARNING ] The cloud driver, 'azurearm', configured under the 'azure-test' cloud provider alias, could not be loaded. Please check your provider configuration files and ensure all required dependencies are installed for the 'azurearm' driver.
In rare cases, this could indicate the 'azurearm.get_configured_provider()' function could not be found.
Removing 'azurearm' from the available providers list
Error: There was an error listing images: No cloud providers matched 'azure-test'. Available selections:
```

**Comment by nzthiago** [comment]
I think things might have been updated more since this PR - I know @ritazh has done more recent work to get a nice Elasticsearch sample going. Check out her script here, hopefully it helps figure out what's different:
https://github.com/ritazh/azure-saltstack-elasticsearch/blob/master/saltstackinstall.sh

**Pull request merged**
