### PR TITLE
For #31309 - state.grains.present able to only check for present

### PR DESCRIPTION
**Pull request by Tanoti**
If value option not supplied then grain will only be checked to see if it exists otherwise operate as usual.  This allows it to work as a proper exists-only check rather than an exists-and-set check.

### CODE REVIEW

**Comment by Tanoti** [comment]
Not totally sure why this failed the tests unless the tests are expecting an older, more regulated, output which is incorrect now the operational logic is less linear?

**Comment by rallytime** [comment]
@Tanoti "unless the tests are expecting an older, more regulated, output which is incorrect now the operational logic is less linear" is exactly right. Many of these unit tests are written with very specific expected out put. So if that output or comment (or logic) changes, that may mean we need to adjust something in the test.

Are you able to take a crack at updating those failing tests? If not, let us know and we'd be happy to help.

**Comment by Tanoti** [comment]
@rallytime Point me at the test's code and I'll see what I can do.

**Comment by rallytime** [comment]
These test are located in `salt/tests/unit/states/grain_test.py`. More information about unit tests and running the test suite can be found at the following links, if that is helpful:

- https://docs.saltstack.com/en/latest/topics/development/tests/index.html
- https://docs.saltstack.com/en/latest/topics/development/tests/unit.html

Thank you! Let me know if you run into any trouble.

**Comment by cachedout** [comment]
Did this get rebased with a force push? Clearly, some unrelated commits have been pushed into this branch. @Tanoti could you please investigate? Feel free to re-open this as a new PR if you like.

**Comment by Tanoti** [comment]
I'm really not sure what I did. I was trying to follow the docs for syncing my branch with the patched code in with the changes made to /develop. I know I didn't explicitly do a force push though.

**Comment by cachedout** [comment]
@Tanoti Not sure either. It might be best to close this PR and just open a new one.

**Comment by cachedout** [comment]
@Tanoti I'm going to go ahead and close this. Please re-open a new PR with just the changes in question and we'll have a look. Thanks!

**Comment by Tanoti** [comment]
@cachedout Do I just open a new PR against the same branch in my repo or do I have to create a new one and put the changes into that?

**Comment by cro** [comment]
@Tanoti, yes, just do a `git fetch --all` and a `git pull --rebase upstream develop` in your branch. You may need to delete your branch on the github side first.

**Pull request closed without merging**
