### PR TITLE
Moar Py3 and a fix for #38121

### PR DESCRIPTION
**Pull request by s0undt3ch**
Moar Py3 and a fix for #38121

### CODE REVIEW

**Comment by ninja-** [comment]
Have you by any chance fixed the problem that makes master hang on SystemCTL restart salt-master under py3?

**Comment by s0undt3ch** [comment]
Nope haven't tacked that yet. Is there an issue for that?

**Comment by s0undt3ch** [comment]
*tackled

**Comment by ninja-** [comment]
No, sorry, I was about to gather more data and create an issue. One of the threads was crashing with exception on kill signal and thus master hang waiting for it to die.

**Comment by ninja-** [comment]
I can reproduce it every time though

**Pull request merged**
