### PR TITLE
Add support for docker's security_opt configuration (#23687)

### LINKED ISSUE #23687: Feature: Add support for docker security_opt arguments
Newer versions of the docker client (1.6.0+) support a `security_opt` keyword to control privileges provided to a container (see [client.py:start()](https://github.com/docker/docker-py/blob/master/docker/client.py)). This particular option is very important for debian/ubuntu users due to [docker issue 7276 with apparmor](https://github.com/docker/docker/issues/7276) that will overrun the system logs with a huge amount of warnings.

Currently, there is no way to use the docker.* salt states and set this option. The only work around, so far as I'm aware, is to manually build out a docker start command.

----- UPDATE -----

Due to our environment, I ended up having to create a monkey patch to add in this behavior. For anybody else in desperate need of a temporary solution, feel free to use [our monkey patch](https://github.com/xetus-oss/salt-docker-monkeypatched-module/tree/master)

### PR DESCRIPTION
**Pull request by tkent**
This a pretty small and straightforward commit that will allow SELinux and AppArmor users to properly configure security capabilities. This is specifically important to AppArmor users (Debian and Ubuntu), since many containers use features that are restricted and will either fail or fill up the logs.

This fixes #23687

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @tkent 

Looks like some spacing issues in those files. Could you please take a look at the lint test and adjust this PR accordingly? Thanks. :]

**Comment by tkent** [comment]
@cachedout 

Done! Sorry about that. I've been in Java/Groovy land for a while and forgot to update my editor settings for this patch. Fixed now.

**Comment by cachedout** [comment]
@tkent No worries. Thanks!

**Comment by cachedout** [comment]
Just some Py3 compat fixes left. I pasted the pylint output below since it's not showing up in the web interface:

```
************* Module salt.modules.dockerng
dockerng.py:237: [W1699(incompatible-py3-code), ] Incompatible Python 3 code found. Proposed fix:
 
 # Import Python Futures
 from __future__ import absolute_import
+from salt.ext import six
 
 __docformat__ = 'restructuredtext en'
 
dockerng.py:1445: [W1699(incompatible-py3-code), ] Incompatible Python 3 code found. Proposed fix:
             return
 
         try:  # check whether python knows about 'basestring'
-            basestring
+            six.string_types
         except NameError:  # no, it doesn't (it's Python3); use 'str' instead
-            basestring = str
-
-        if (not isinstance(kwargs['security_opt'], basestring) and
+            six.string_types = str
+
+        if (not isinstance(kwargs['security_opt'], six.string_types) and
                 not isinstance(kwargs['security_opt'], list)):
             raise SaltInvocationError(
                 'security_opt must be a single value or a Python list')
 
-        if isinstance(kwargs['security_opt'], basestring):
+        if isinstance(kwargs['security_opt'], six.string_types):
             kwargs['security_opt'] = [kwargs['security_opt']]
 
     def _valid_links():  # pylint: disable=unused-variable
```

**Comment by tkent** [comment]
@cachedout 

Just checked in a fix for that! I moved over to the six module instead of manually checking basestring. I'll watch to see if any other dings show up and commit fixes for them if they do.

**Comment by cachedout** [comment]
@tkent Great! That should likely do it. We'll wait for these tests to finish up and then get this in. I really appreciate the quick response!

**Pull request merged**
