### PR TITLE
Add pre and post states to SPM

### PR DESCRIPTION
**Pull request by techhat**
### What does this PR do?
As it says. See the documentation file in this PR For more details.

### Tests written?
No.

### CODE REVIEW

**Comment by gtmanfred** [comment]
This will be great to have!

**Review by cachedout — APPROVED** [review]

**Comment by cachedout** [comment]
@techhat Could you look at the lint errors, please?

**Comment by techhat** [comment]
@cachedout fixed.

**Comment by cachedout** [comment]
@techhat There are some more test failures: https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/9269/

**Pull request merged**
