### PR TITLE
[WIP] Add support for "CentOS" in "nspawn.bootstrap_container"

### PR DESCRIPTION
**Pull request by eliasp**
### What does this PR do?

It adds support for `CentOS` (`7` or newer) to `nspawn.bootstrap_container`.
### What issues does this PR fix or reference?

None
### Previous Behavior

`CentOS` containers couldn't be bootstrapped using `nspawn.bootstrap_container`
### New Behavior

`CentOS` containers can be bootstrapped now using `nspawn.bootstrap_container`
### Tests written?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by cachedout** [comment]
@eliasp Looks like some lint errors that need to be cleaned up, please.

Also, is this still a WIP? Please let me know if you're planning to add more here or if you're just curious about the test results, etc, etc. Thanks.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by eliasp** [comment]
@cachedout yes, after I created the PR I realized I was still missing a few bits and there was still room for improvements, so I added `[WIP]` to the title.
Will push updates within the next few days and notify you once I consider it to be "ready".

**Comment by cachedout** [comment]
@eliasp Sounds great! Thanks for the quick response.

**Comment by terminalmage** [comment]
@eliasp Any movement on this?

**Comment by eliasp** [comment]
@terminalmage sorry, still WIP as I re-worked quite a bit more than initially planned:
- make sure `yum`/`dnf` works properly also on non-RedHat-based distributions
- don't create machine images directly under `/var/lib/machines` which should be under strict control of `systemd-machined` as it creates a btrfs subvolume for each machine - use `systemd-importd` via DBus (`org.freedesktop.import1`) instead

… and some more refactoring which will also affect the related PRs #31610 and #31611

**Comment by cachedout** [comment]
Hi @eliasp Do you want to keep this open for the time being or close it and just re-open it when you're ready to re-run the tests?

**Comment by cachedout** [comment]
Hi again @eliasp 

Since I didn't hear back, I am closing this for the time being. Let me know when you're ready to re-open this and we'll get it in. Thanks!

**Pull request closed without merging**
