### PR TITLE
Support for assumed role policies and roles without instance profiles

### PR DESCRIPTION
**Pull request by ryan-lane**

### CODE REVIEW

**Comment by jfindlay** [comment]
@ryan-lane, will you also fix the lint errors and update the tests?  Thanks.

**Comment by rallytime** [comment]
@ryan-lane Can you also add some doc strings to the new functions you've added? That will clear up one of the tests failing:
```
AssertionError: There are some functions which do not have a docstring or do not have an example:
No docstring:
  - boto_iam.build_policy
  - boto_iam.update_assume_role_policy
```
It looks like one of the boto unit tests is failing as well. We can help out there if it's not a simple fix. Just let us know.

**Comment by ryan-lane** [comment]
Sorry. I'll try to get to some of these issues soon.

**Comment by ryan-lane** [comment]
Found a bug while adding more test coverage. Win ;). Tests should be good now, and basic coverage was added for new functions.

**Comment by rallytime** [comment]
Nice! More tests and fixing bugs FTW!

**Pull request merged**
