### PR TITLE
iptables: document 'chain' kwarg for 'flush' state

### PR DESCRIPTION
**Pull request by skrobul**
### What issues does this PR fix or reference?
Fixes: missing documentation for `iptables.flush` state.

Prior to this PR it was unclear how to flush a specific chain in a table.

### Merge requirements satisfied?
- [x] Docs
- [ ] Changelog - N/A
- [ ] Tests written/updated - N/A

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by garethgreenaway** [comment]
@skrobul Would you be able to rebase this PR against the master branch.  Thanks!

**Comment by garethgreenaway** [comment]
@skrobul Would you be able to rebase this PR against the master branch.  Thanks!

**Comment by skrobul** [comment]
@garethgreenaway this PR is opened against `develop` branch. do you want me to close it and open new one?

**Comment by skrobul** [comment]
@garethgreenaway rebased as requested

**Review by garethgreenaway — DISMISSED** [review]

**Review by dwoz — APPROVED** [review]

**Pull request merged**
