### PR TITLE
Add Amazon Kinesis support via boto3

### PR DESCRIPTION
**Pull request by mkercher**
### What does this PR do?

Adds support for kinesis management via boto, in the style of other boto modules (boto_dynamodb, boto_ec2, etc). Includes functionality to create or delete a stream, reshard a stream, change enhanced monitoring, and change retention hours. State file for boto_kinesis.present and boto_kinesis.absent; plus module file for the various useful methods.

One note: this reshards a stream such that the partition space stays balanced, which means the actual reshard process can take a really long time - it could take hours for N -> N+1 shards, but would be minutes for 2^N -> 2^N+1 shards. There are warnings in the documentation here to that effect.

I relied heavily on the existing boto_\* files and tests when writing this (especially boto_dynamodb) and thank those authors for their work.
### What issues does this PR fix or reference?
#37203
### Tests written?

Yes, some unit tests.

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @mkercher This looks good. There are some Py3 compatibility issues that I'd like you to look at:

```
************* Module salt.modules.boto_kinesis
boto_kinesis.py:53: [W1699(incompatible-py3-code), ] Incompatible Python 3 code found. Proposed fix:
 import logging
 import time
 import random
+from salt.ext.six.moves import range
 
 # Import third party libs
 # pylint: disable=unused-import
boto_kinesis.py:258: [W1699(incompatible-py3-code), ] Incompatible Python 3 code found. Proposed fix:
             log.debug("skipping closed shard {0}".format(shard_id))
             continue
         stream_details["OpenShards"].append(shard)
-        shard["HashKeyRange"]["StartingHashKey"] = long(
+        shard["HashKeyRange"]["StartingHashKey"] = int(
             shard["HashKeyRange"]["StartingHashKey"])
-        shard["HashKeyRange"]["EndingHashKey"] = long(
+        shard["HashKeyRange"]["EndingHashKey"] = int(
             shard["HashKeyRange"]["EndingHashKey"])
         if shard["HashKeyRange"]["StartingHashKey"] < min_hash_key:
             min_hash_key = shard["HashKeyRange"]["StartingHashKey"]
         if shard["HashKeyRange"]["EndingHashKey"] > max_hash_key:
             max_hash_key = shard["HashKeyRange"]["EndingHashKey"]
-    stream_details["OpenShards"].sort(key=lambda shard: long(
+    stream_details["OpenShards"].sort(key=lambda shard: int(
         shard["HashKeyRange"]["StartingHashKey"]))
```

**Comment by mkercher** [comment]
Thanks for the feedback @cachedout. I haven't worked much with python 3, but some googling led me to believe this might be the best way of handling it. This will likely still fail the compatibility check (we'll see) but given that python 2 truly needs to use a long, I think this might be the best we got.

**Comment by cachedout** [comment]
Hi @mkercher We still need some docs written for these new functions:

https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/6584/testReport/junit/integration.modules.sysmod/SysModuleTest/test_valid_docs/

Please see other execution modules for examples on how to do this.

There are still some minor lint issues that still need to be addressed as well. Please let me know if I can help at all. Thanks!

**Comment by cachedout** [comment]
From a style perspective, we typically prefer single-quotes over double-quotes and a minimum of three letters for variable names. (i.e. `ret` over `r`.)

However, the implementation here is so good that I'm going to merge this anyhow and if somebody would like to come along and change this later, it would be a quick job.

Thanks so much for this, @mkercher. It's really excellent!

**Pull request merged**
