### PR TITLE
#8705 run and key eauth

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
### What does this PR do?

Add eauth support to salt-run and salt-key CLI.
This changes salt-run and salt-key CLI behavior: now no one of them do the job by itself. All the job is sent to master. So it will not work without master running.
### What issues does this PR fix or reference?
saltstack/salt#8705
### Tests written?

No

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
So far this looks good but I want to keep looking at it. @thatch45 is going to review it as well.

**Comment by DmitryKuzmenko** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
I'm afraid this has merge conflicts now. @DmitryKuzmenko could you please rebase this?

**Comment by DmitryKuzmenko** [comment]
@cachedout no problem.

**Comment by thatch45** [comment]
@cachedout @DmitryKuzmenko This PR has cause havoc with runners. We have many runners that operate by printing to the display intermediate data while running, but this obviously no longer works, since the runner is being executed within the master. What do you think is the best way to fix this?

**Pull request merged**
