### PR TITLE
backport ipmi - 2015.2

### PR DESCRIPTION
**Pull request by steverweber**
this one is low priority for me..
but the users might like it in the release

### CODE REVIEW

**Comment by steverweber** [comment]
depends on:
https://github.com/saltstack/salt/pull/21266

to cleanup some log messages

**Comment by rallytime** [comment]
@steverweber The 2015.2 is currently in a "feature freeze" wherein we have stopped the addition of brand new features as we prepare for the new release. As such, I am not inclined to merge this pull request so we can help to reduce the velocity of code changes on this branch as we test it before the release of 2015.2.0.

I have filed #21270 to remember to document this procedure.

**Comment by thatch45** [comment]
As this does not break tests and is just a module addition I will allow it, but in the future please do not backport to frozen branches :)

**Comment by steverweber** [comment]
np thanks.

**Pull request merged**
