### PR TITLE
Simplify string manipulation

### PR DESCRIPTION
**Pull request by szviagintsev**
### What does this PR do?

Makes a chunk of code a bit easier to read

### Tests written?

No

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
This seems to change the intent of the original code to me. See: https://github.com/saltstack/salt/commit/35207578452cc9ffa399f253f018f9669aec9f1f

cc: @terminalmage

**Review by terminalmage — CHANGES_REQUESTED** [review]
@cachedout When the diff is applied, the result is:

```python
if self.info:
    if len(exc_str_prefix) > 0:
        if exc_str_prefix[-1] not in '.?!':
            exc_str_prefix += '.'
        exc_str_prefix += ' '
```

This does preserve the intent of 3520757. However, it would be more efficient to just do a simple truth check, like so:

```python
if self.info:
    if exc_str_prefix:
        if exc_str_prefix[-1] not in '.?!':
            exc_str_prefix += '.'
        exc_str_prefix += ' '
```

It seems about twice as fast to do it this way:

```python
>>> import timeit
>>> t1 = timeit.Timer('if foo: pass', 'foo = "hello world!"')
>>> t2 = timeit.Timer('if len(foo) > 0: pass', 'foo = "hello world!"')
>>> t1.repeat()
[0.04230308532714844, 0.021127939224243164, 0.020946025848388672]
>>> t2.repeat()
[0.08195710182189941, 0.061921119689941406, 0.06122088432312012]
>>>
```

**Comment by cachedout** [comment]
@terminalmage Thanks for the follow-up.

@sergeizv If you could take a look and make that change then I think we can get this in. Please let me know when it's updated. Thanks!

**Comment by sergeizv** [comment]
On Tue, Feb 07, 2017 at 11:18:42AM -0800, Erik Johnson wrote:
> terminalmage requested changes on this pull request.
> 
> @cachedout When the diff is applied, the result is:
> 
> ```python
> if self.info:
>     if len(exc_str_prefix) > 0:
>         if exc_str_prefix[-1] not in '.?!':
>             exc_str_prefix += '.'
>         exc_str_prefix += ' '
> ```
> 
> This does preserve the intent of 3520757. However, it would be more efficient to just do a simple truth check, like so:
> 
> ```python
> if self.info:
>     if exc_str_prefix:
>         if exc_str_prefix[-1] not in '.?!':
>             exc_str_prefix += '.'
>         exc_str_prefix += ' '
> ```
> 
> It seems about twice as fast to do it this way:
> 
> ```python
> >>> import timeit
> >>> t1 = timeit.Timer('if foo: pass', 'foo = "hello world!"')
> >>> t2 = timeit.Timer('if len(foo) > 0: pass', 'foo = "hello world!"')
> >>> t1.repeat()
> [0.04230308532714844, 0.021127939224243164, 0.020946025848388672]
> >>> t2.repeat()
> [0.08195710182189941, 0.061921119689941406, 0.06122088432312012]
> >>>
> ```
> 
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/saltstack/salt/pull/39056#pullrequestreview-20594723

Thank you for the explanation! I'm just diving into python gotchas, so
this is really helpful.

**Comment by sergeizv** [comment]
@cachedout I've updated the pull request with the requested change. Thank you so much for reviewing this!

**Review by terminalmage — COMMENTED** [review]
:+1:

**Review by terminalmage — APPROVED** [review]
:+1: LGTM

**Pull request merged**
