### PR TITLE
fix show_diff for test run

### PR DESCRIPTION
**Pull request by eguven**
enabled show_diff for test run if not set to False

### CODE REVIEW

**Comment by jfindlay** [comment]
@eguven, do you think this needs to be in 2015.5 or 2015.8?

**Comment by eguven** [comment]
@jfindlay I don't know the details of salt releases but if there will be more `2015.5.x` releases, I'd say both

**Comment by jfindlay** [comment]
@eguven, that's what I was thinking, but I wanted to make sure, thanks.

**Comment by rallytime** [comment]
This change relies on code that is only available in the `develop` branch, as the `pchanges` work only exists in develop, so I've closed the back-porting PR.

**Pull request merged**
