### PR TITLE
Fixes stdout user environment corruption

### PR DESCRIPTION
**Pull request by psyer**
### What does this PR do?
This fix will set a marker before the users env is created. Make the env var.
Then set a marker after it is done. Then will grab the real env info between
the markers, and throw away the markers. Any stdout noise is then mitigated.

### What issues does this PR fix or reference?
When using PAM module pam_lastlog.so with config option "showfailed", it
outputs a "Last login ..." line to stdout everytime a shell is spawned.
This corrupts a random env var and causes havoc in paths and the like.

To reproduce: PAM option was put in /etc/pam.d/su file with line:
session required pam_lastlog.so showfailed

then: salt <minion> cmd.run runas=<user> env

Which will show "Last login ..." in one of the env vars.

This fix will set a marker before the users env is created. Make the env var.
Then set a marker after it is done. Then will grab the real env info between
the markers, and throw away the markers. Any stdout noise is then mitigated.

### Previous Behavior
...
LOGNAME=username
XDG_SESSION_ID=c4Last login: Sat Mar 10 23:49:26 EST 2018 from 192.168.0.55 on pts/3
LC_COLLATE=C
...

### New Behavior
...
LOGNAME=username
XDG_SESSION_ID=c9
LC_COLLATE=C
...

### Tests written?
No

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by psyer** [comment]
The integration test that is failing for: unit.modules.test_cmdmod.CMDMODTestCase.test_os_environment_remains_intact

With error:
_CommandExecutionError: Environment could not be retrieved for User 'foobar': missing first marker, got err=None out=['{}', None]
	
Standard Error
/bin/sh: 1: foo: not found_

This error looks like it might have been happening before (I can't see the history from other builds) my code was added. It just might not have been caught,  it looks like the word 'foo' is trying to be executed by the shell during the test suite, which failed. Stderr was never exposed before, nor was checking to see if an error was happening during python code exec. Looking for the new unique tags wrapping the env code, and not finding them tripped the exception.

 When the code is figuring out how to set the cmd_env var,  sys.executable looks like it is getting set to 'foo' and then trying to be executed by the test system.  Not sure what is going on here, but that is just a guess.

**Comment by terminalmage** [comment]
@psyer Please take a look at https://github.com/psyer/salt/pull/1

**Review by terminalmage — CHANGES_REQUESTED** [review]
I've opened a PR against the OP's fork to simplify some of the logic. I'm working with the OP now to satisfy their concerns.

**Comment by terminalmage** [comment]
@psyer No need to merge the 2017.7 branch into this branch again, let's let tests finish and we should be able to merge it without syncing again with 2017.7.

**Review by terminalmage — APPROVED** [review]

**Comment by rallytime** [comment]
@terminalmage and @psyer this test failure looks related: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-cent7-py3/3322/testReport/

**Comment by psyer** [comment]
@terminalmage I'm going to let you decide how you want to handle this. I believe the previous code dealt with something like this bytes to str error if you need an example https://github.com/saltstack/salt/pull/46503/commits/e8d3d017f9dade103c48050526f91be0ec1d7f87. If you want me to take a crack at it let me know.

**Comment by terminalmage** [comment]
That's weird, GitHub appears to have pulled my latest commit from my fork into this PR, even though I didn't open this PR. I just added e8582e8 to fix the test.

**Comment by terminalmage** [comment]
I had meant to open another PR against @psyer's fork to give them a chance to review. This seems like a potential security issue with GitHub.

**Comment by terminalmage** [comment]
I've filed a support request upstream with GitHub. It's possible that because I have admin access to this repo, and I had already contributed with @psyer, there is a "feature" which allows me to directly push to the PR.

**Comment by rallytime** [comment]
@psyer and @terminalmage Is this ready to go, then?

**Comment by psyer** [comment]
@rallytime  I'm good with the current code. Let me know if you need anything else from me.

**Comment by terminalmage** [comment]
This should be good to merge. I found that the same feature we enable to allow us to sync a PR with the base branch also allows maintainer's to push to the head branch for a given PR. So, somehow my push to my local branch also ended up in @psyer's, or else I mistyped when I pushed. Either way, that explains that.

**Comment by rallytime** [comment]
Thanks y'all - merged. :)

**Pull request merged**
