### PR TITLE
Cleaner deprecation process with decorators

### PR DESCRIPTION
**Pull request by isbm**
Port of https://github.com/saltstack/salt/pull/32068

### CODE REVIEW

**Comment by cachedout** [comment]
@isbm We need this rebased, please.

**Comment by isbm** [comment]
@cachedout uhm... seems like it is all already in the code of the latest branch, so maybe we don't need this at all.

**Comment by rallytime** [comment]
@isbm The changes you made in an earlier branch (I think it was against 2015.8, if I remember correctly) were merged forward, which is probably what is causing the conflict. If the develop branch looks ok to you without this change, then we should probably just close this PR. Otherwise, if things need to be updated on the develop branch, then feel free to rebase this and we can still get the changes in.

**Comment by isbm** [comment]
@rallytime Yep. Seems to be so. Closing. Thanks!

**Pull request closed without merging**
