### PR TITLE
[master] Port #51047 (Jinja map troubleshooting)

### PR DESCRIPTION
**Pull request by max-arnold**
Master backport of #51047 (execution module for troubleshooting Jinja map files)

### CODE REVIEW

**Comment by max-arnold** [comment]
@dwoz I added a couple of tests and mentioned the feature in release notes. Could you please review the PR again?

P.S. The failing acme tests are unrelated

**Comment by max-arnold** [comment]
re-run full debian8 macosxmojave opensuse15

**Comment by max-arnold** [comment]
re-run full macosxmojave-py2 opensuse15-py2 macosxmojave-py3 opensuse15-py3

**Comment by max-arnold** [comment]
re-run macosxmojave-py3
re-run opensuse15-py2
re-run opensuse15-py3

**Comment by max-arnold** [comment]
re-run full debian8-py2
re-run full windows2019-py3

**Review by Akm0d — APPROVED** [review]

**Pull request merged**
