### PR TITLE
ignore event if reactor sent the event

### PR DESCRIPTION
**Pull request by austinpapp**
### What does this PR do?

When the reactor sends a managed leader or managed reactor event, we want to make sure we don't actual react to the event. Adding the `Reactor` user so that we gate a second unnecessary react. 

### What issues does this PR fix or reference?

Don't react to a reactor sent event for managing leader and reactors. 

### Previous Behavior

When a manage leader or manage reactor event was executed, the reactor would react to it's own sent event.

### New Behavior

Don't react to a manager leader or manage reactor event if sent from the reactor.

### Tests written?

No

### Commits signed with GPG?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by dwoz** [comment]
@austinpapp Looks like some windows tests related to the reactor are failing. Can you please take a look?

**Comment by austinpapp** [comment]
@dwoz will take a look. thanks for the heads up.

**Comment by austinpapp** [comment]
@dwoz we may have to chalk it up to the test being flaky /shrug. however, i'll try and see if i can source a windows container to do more testing.

**Comment by austinpapp** [comment]
@dwoz i just ran the reactor integration tests on a win machine without my changes are they are failing. seems this is a test failure from another situation. given the work in https://github.com/saltstack/salt/pull/51243 i can't rule that out as part of the problem. i couldn't find the test status from that run. maybe you can see it?

**Comment by austinpapp** [comment]
looks like https://github.com/saltstack/salt/pull/51710 fixed the issue.

**Review by dwoz — APPROVED** [review]

**Pull request merged**
