### PR TITLE
Update contributing and documentation pages to recommend submitting against branches

### LINKED ISSUE #28272: Update documentation contributing docs to explain how to PR against different releases
It was explained to me today by @jfindlay that with the way docs are built that it is now required to PR against the head of specific releases to get the docs into that release version. It would be great if https://docs.saltstack.com/en/latest/topics/development/conventions/documentation.html could be updated to show some examples of doing this specifically for documentation. @jacobhammons do you think you could look at adding this when you have some time?

### PR DESCRIPTION
**Pull request by rallytime**
Fixes #28272

### CODE REVIEW

**Comment by gravyboat** [comment]
@rallytime This looks really good! What do you think about adding a few examples for users showing how they can pull a specific tag?

**Comment by rallytime** [comment]
I thought about that, and started to add some examples, and then I realized I was repeating a lot what we were stating in the Contributing docs [here](https://docs.saltstack.com/en/latest/topics/development/contributing.html#sending-a-github-pull-request).

Maybe I can add some "for an example of how to submit a PR against another branch, see XXX" and update the language in that section to also apply to docfixes. Would that work @gravyboat?

**Comment by gravyboat** [comment]
@rallytime I think that would be a good addition. I'd rather double up on commands that need to be run directly than rely on users having navigated the pages in a specific way. The linking seems like a good compromise to that! :+1:

**Comment by rallytime** [comment]
Thanks! Sounds good! I've updated my PR.

**Comment by gravyboat** [comment]
Looks great @rallytime! :shipit:

**Pull request merged**
