### PR TITLE
Add new keystone module and states based on shade

### PR DESCRIPTION
**Pull request by ghost**
What does this PR do?

This PR adds a new module (keystoneng.py) to supercede keystone.py. It uses the shade library from the openstack project (https://github.com/openstack-infra/shade.git) Shade is a project that has committed to maintaining the same API forever. It may add new features and more efficient ways of doing things, but it will never remove things.

Using shade will abstract the keystone v2/v3 logic away allowing the end user to write states without having to consider which version of the api is it talking to (with the exception of trying to use new features like groups/domains on v2.0 which doesn't support it).

We are making extensive use of **kwargs to help prevent the need to maintain lots of duplicate logic that exists in shade itself.
What issues does this PR fix or reference?

N/A
Tests written?

Not yet

### CODE REVIEW

**Comment by SamYaple** [comment]
I was asked to create a new PR for this, but here is the previous one for reference

https://github.com/saltstack/salt/pull/43207

**Review by gtmanfred — APPROVED** [review]

**Comment by rallytime** [comment]
@SamYaple There are some lint errors here: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/16717/violations/

Can you fix those?

**Comment by damon-atkins** [comment]
You need to add u infront of every string or add
`from __future__ import unicode_literals` or `from __future__ import absolute_import, unicode_literals`

So that all strings are Unicode. As PY3 is Unicode Strings

**Comment by rallytime** [comment]
@damon-atkins There is already work in progress to handle the unicode issues. @terminalmage Is working on it right now for Oxygen and his fixes are different than the `unicode_literals` import approach. Thank you very much for commenting on this, but those types of changes won't be necessary. :)

**Comment by SamYaple** [comment]
Will fix the lint issues (and gpg sign my commit)

**Comment by cachedout** [comment]
@SamYaple Were you able to get to those lint fixes?

**Comment by damon-atkins** [comment]
Hi @rallytime not sure how the salt team can keep retro fixing contributions, to ensure all text strings are Unicode.   terminalmage job will never be done.

**Comment by gtmanfred** [comment]
It's Happening

**Pull request merged**
