### PR TITLE
Fix to consul cache

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Updating the code that is pulling in the list of cached minions to use `self.cache.list` instead of relying on checking the local file system, which only works for the `localfs` cache method.

### What issues does this PR fix or reference?
#40748

### Tests written?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
I would like @DmitryKuzmenko to review this, since he added this logic somewhat recently.

**Comment by garethgreenaway** [comment]
👍 Definitely.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by garethgreenaway** [comment]
Go Go Jenkins!

**Review by DmitryKuzmenko — APPROVED** [review]
Very good!
Errors are unrelated, BTW.

**Pull request merged**
