### PR TITLE
fix: netmiko support for develop and versions > 3.4.0

### LINKED ISSUE #60762: [BUG] Netmiko proxy fails with develop branch of Netmiko due to netmiko execeptions rename
**Description**
To use `salt.proxy.netmiko_py` with a set of fixes in Netmiko  the Netmiko develop branch  is installed `pip install git+https://github.com/ktbyers/netmiko.git@develop`

Netmiko Proxy fails with Proxymodule netmiko is missing.........
will not load netmiko and proxy call fails

Debugging it has tracked it to the following Netmiko - commit [Moving exceptions file to more logically named file](https://github.com/ktbyers/netmiko/commit/b8adf)

It is very likely the netmiko commit responsible for the failure goes into a a future version> 3.4.0.

I have a draft PR ready to submit to fix this

**Setup**
generic salt v3003.2 calling proxy with salt-sproxy and develop branch of Netmiko

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [X] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
with salt-sproxy installed, however will be same with just salt proxy
```bash
#install develop branch of Netmiko 
pip install git+https://github.com/ktbyers/netmiko.git@develop

salt-sproxy  router1 netmiko.send_command '/ip address print'
```

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3003.2

Dependency Versions:
          cffi: 1.14.4
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.11 (default, Jun 29 2021, 21:15:56)
  python-gnupg: 0.4.4
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: alpine 3.13.5
        locale: UTF-8
       machine: x86_64
       release: 4.19.128-microsoft-standard
        system: Linux
       version: Alpine Linux 3.13.5

salt-sproxy --version
     salt-sproxy 2021.6.1
```

</details>

**Additional context**

### PR DESCRIPTION
**Pull request by auphofBSF**
### What does this PR do?
support for Netmiko as is being refactored towards 4.x.x 
 - Issues such as fix #60762 
 - netmiko functions having typing annotations
 
Allows the proxy netmiko suppot in salt, to function with develop branch or future releases of netmiko that have the exceptions rename and function typing  included `pip install git+https://github.com/ktbyers/netmiko.git@develop`  and future releases > v3.4.0 but still maintain compatibility with 3.4.0

### What issues does this PR fix or reference?
Fixes: Netmiko - commit [Moving exceptions file to more logically named file](https://github.com/ktbyers/netmiko/commit/b8adf)
Fixes handling Netmiko function argument typing annotations as introduced by https://github.com/ktbyers/netmiko/pull/2294

### Previous Behavior
if Netmiko develop branch installed `pip install git+https://github.com/ktbyers/netmiko.git@develop` 
Netmiko Proxy fails with `Proxymodule netmiko is missing.........`
will not load netmiko and proxy call fails 

It is very likely the netmiko commit responsible for the failure [](https://github.com/ktbyers/netmiko/commit/b8adf ) goes into a a  future version> 3.4.0

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by auphofBSF** [comment]
Whilst this PR allows commands like `netmiko.send_command` to work, a command like `netmiko.send_config` fails  with  

`ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them`

The develop branch and the next version of Netmiko will have typing on function arguments. This can be seen in https://github.com/ktbyers/netmiko/blob/cde7fb435ec92dbd10276406fb933f3f764654e9/netmiko/base_connection.py#L118

The present `salt.utils.args.get_function_argspect` raises a value error if annotations exist to a functions arguments.  How is salt going to handle function arguments with annotations such as typing, as per the `BaseConnection.__init__` example above ? 

The error gets raised her https://github.com/saltstack/salt/blob/79b56313f2197d2ec92fc503ee65498130239891/salt/utils/args.py#L36,

I note that @s0undt3ch authored  #57240 15months ago, maybe he has an idea. My solution for the moment is to ignore annotations by modifying `salt.args._getargspec` , i will commit this shortly for consideration by someone with a deeper understanding of salt, for the moment I will return this PR to draft status

```
    log.trace(f'------------------ salt.args._getargspec: type func {func}, kwonlyargs: {kwonlyargs}   annotations:{ann}')
    if ann: # A work around for functions with typing annotations see; https://github.com/saltstack/salt/pull/60763
        log.warning(f'Function Arg, annotations eg `def foo(bar: str)->str` ARE NOT SUPPORTED at present salt.args._getargspec: type func {func}, annotations:{ann}')
        ann={} 

```

**Comment by garethgreenaway** [comment]
@auphofBSF Apologies for the delay, changing `salt/utils/args.py` is a big change as it's used everywhere.  Is this change necessary for the Netmiko change?  Also it looks like your change added some `F strings, which unfortunately we can't utilize yet as we need to support older versions of Python that do not support those.

**Comment by piterpunk** [comment]
> @auphofBSF Apologies for the delay, changing `salt/utils/args.py` is a big change as it's used everywhere. Is this change necessary for the Netmiko change? Also it looks like your change added some `F strings, which unfortunately we can't utilize yet as we need to support older versions of Python that do not support those.

@garethgreenaway, the commit d7145d122e7dbcc870b197ae6aefd28900ed5b74 is enough to make netmiko proxy connects and have at least some basic functionality. I didn't a lot of tests, but my netmiko states works Ok with only this one applied.

Will be nice to have d7145d122e7dbcc870b197ae6aefd28900ed5b74 and 0f4722f6ec43177626df8529d848c59094bbe327 merged.

**Comment by garethgreenaway** [comment]
Underlying issue fixed by https://github.com/saltstack/salt/pull/62412

**Pull request closed without merging**
