### PR TITLE
Fix unicode handling from last PR

### PR DESCRIPTION
**Pull request by ghost**
### What does this PR do?

Fix bad unicode handling from my last PR
### Previous Behavior

I passed non-unicode to win32API in all cases (Python <3 and Python 3).
Note that before my original pull request, what was passed to winreg depended
on the version of python. I don't think that the version of python matters when
dealing with win32api. (i.e. i believe it should be passed unicode arguments no matter
what).
### New Behavior

Everything passed to the win32API lib is unicode
### Tests written?

No

### CODE REVIEW

**Comment by hrumph** [comment]
@damon-atkins, I think this is good.

I'll paste what i believe to be the source code from win32 api below (for RegCreateKeyEx). In the source code it looks like the string params are all meant to be unicode and python 2.7 and 3 aren't treated any differently (AFAICS)

```
// @pymethod <o PyHKEY>, int|win32api|RegCreateKeyEx|Extended version of RegCreateKey
// @rdesc Returns registry handle and flag indicating if key was opened or created (REG_CREATED_NEW_KEY or REG_OPENED_EXISTING_KEY)
// @pyseeapi RegCreateKeyEx
// @comm Implemented only as Unicode (RegCreateKeyExW).  Accepts keyword arguments.
// @comm If a transaction handle is passed in, RegCreateKeyTransacted will be called (requires Vista or later)
// @pyseeapi RegCreateKeyTransacted
static PyObject *PyRegCreateKeyEx(PyObject *self, PyObject *args, PyObject *kwargs)
{
	static char *keywords[]={"Key","SubKey","samDesired","Class","Options","SecurityAttributes","Transaction", NULL};
	HKEY hKey;
	PyObject *obKey, *obsubKey, *obclass=Py_None, *obsa=Py_None, *obtrans=Py_None, *ret=NULL;
	WCHAR *subKey=NULL, *class_name=NULL;
	PSECURITY_ATTRIBUTES psa;
	DWORD access, disp, options=REG_OPTION_NON_VOLATILE, reserved=NULL;
	HKEY retKey;
	long rc;
	HANDLE htrans;
	PVOID extparam=NULL;	// Documented as Reserved

	if (!PyArg_ParseTupleAndKeywords(args, kwargs, "OOk|OkOO:RegCreateKeyEx", keywords, 
		&obKey,		// @pyparm <o PyHKEY>/int|Key||Registry key or one of win32con.HKEY_* values
		&obsubKey,	// @pyparm <o PyUnicode>|SubKey||Name of subkey to open or create.
		&access,	// @pyparm int|samDesired||Access allowed to handle, combination of win32con.KEY_* constants.  Can also contain
					//	standard access rights such as DELETE, WRITE_OWNER, etc.
		&obclass,	// @pyparm <o PyUnicode>|Class|None|Name of registry key class
		&options,	// @pyparm int|Options|REG_OPTION_NON_VOLATILE|One of the winnt.REG_OPTION_* values
		&obsa,		// @pyparm <o PySECURITY_ATTRIBUTES>|SecurityAttributes|None|Specifies security for key and handle inheritance
		&obtrans))	// @pyparm <o PyHANDLE>|Transaction|None|Handle to a transaction as returned by <om win32transaction.CreateTransaction>
		return NULL;
	if (!PyWinObject_AsHANDLE(obtrans, &htrans))
		return NULL;
	if (htrans!=NULL)
		CHECK_PFN(RegCreateKeyTransacted);

	if (PyWinObject_AsHKEY(obKey, &hKey)
		&&PyWinObject_AsWCHAR(obsubKey, &subKey, TRUE)
		&&PyWinObject_AsWCHAR(obclass, &class_name, TRUE)
		&&PyWinObject_AsSECURITY_ATTRIBUTES(obsa, &psa, TRUE)){
		if (htrans!=NULL)
			rc=(*pfnRegCreateKeyTransacted)(hKey, subKey, reserved, class_name, options,
				access, psa, &retKey, &disp, htrans, extparam);
		else
			rc=RegCreateKeyExW(hKey, subKey, reserved, class_name, options,
				access, psa, &retKey, &disp);
		if (rc!=ERROR_SUCCESS)
			PyWin_SetAPIError("RegCreateKeyEx", rc);
		else
			ret=Py_BuildValue("Nk", PyWinObject_FromHKEY(retKey), disp);
		}

	PyWinObject_FreeWCHAR(subKey);
	PyWinObject_FreeWCHAR(class_name);
	return ret;
}
```

**Comment by hrumph** [comment]
Yo,
one more thing, I took a look at the function _PyWinObject_AsWCHAR_. Which takes the post-parsed pything object. So it appears that in Python < 3 it will take either a string (byte) array or unicode, and in Python >= 3 it only takes unicode. I don't know what will happen in ultimately windows in this case. (What encoding is implied when Multibyte_to_wide_character is called, so it would be automatically doing what I'm doing manually with the unicode conversion?) Anyway I don't know, but my conclusion is that what I have done in my PR is for the best. I've chosen to go with unicode when we have the option to do so so that's a good thing

**Comment by damon-atkins** [comment]
FYI When I developed this, it was based on what python doco days....   Then I developed the test suite on windows which includes unicode chars. Like (c) (r) as a single character which are char > 125

**Comment by hrumph** [comment]
@damon-atkins 
when i started to approach this i looked at the win32api docs and I saw stuff like http://docs.activestate.com/activepython/3.4/pywin32/win32api__RegCreateKeyEx_meth.html. It really wasn't clear to me what sort of arguments it was supposed to take and unfortunately i just sort of glanced at the source code and misread it.

**Comment by hrumph** [comment]
sorry wrong link. The link that came up when I googled was http://docs.activestate.com/activepython/2.4/pywin32/win32api__RegOpenKeyEx_meth.html and being new to python I didn't realise how out of date this was.

**Comment by hrumph** [comment]
I fixed up the documentation now (someone had paragraphed it wrong originally, and the documentation for set_value is now very different (hopefully improved!). I have also included many examples of usage in the documentation. I have also tested the hell out of this. @damon-atkins i hope to learn how to use the unit tests very soon. Apologies for not doing so yet.

**Comment by damon-atkins** [comment]
See https://docs.saltstack.com/en/develop/topics/development/tests/index.html
e.g.
C:\salt\bin\python Z:\src\github\salt\tests\runtests.py  -n unit.modules.reg_win_test

**Comment by hrumph** [comment]
@damon-atkins. Thanks for the tips. I'll look into it when I get the chance.

**Pull request merged**
