### PR TITLE
Call bash only when necessary on macOS

### PR DESCRIPTION
**Pull request by cdalvaro**
### What does this PR do?

This PR fixes a bug introduced on PR #54136 (and possibly on PR #54079 too) that calls `/bin/bash` when the user's default shell is not bash.

Also, users that have set a different version of bash as their default shell, they might be calling the wrong shell.

For example, for people with `zsh` as default shell the current behaviour is not right, neither for people with `/usr/local/bin/bash` as their main `shell` since the current code is invoking `/bin/bash` instead the right one.

### New Behavior

The new behaviour introduced in this PR invokes the right bash shell only when the users default shell is bash.

This is done in this way to load the right environment as it was intended in PR #54136.

### Tests written?

✅

### Commits signed with GPG?

✅

### CODE REVIEW

**Comment by cdalvaro** [comment]
Following @waynew [advice]( https://github.com/saltstack/salt/pull/54216#issuecomment-538504386) from PR #54216 

> Hey @cdalvaro - as you may have heard, we're changing to a single branch release strategy. What does that mean for this PR?
> 
> Well, you've got tests so 👍
> 
> We will be working to migrate all PRs from non-`master` branches to `master`. If you'd like to get your PR in sooner, please rebase it against `master`, force push to your branch, and edit this PR to be against `master`. If you need any help with any of those steps, please let us know!

I have modified this PR too in order to fulfil the new release strategy.

**Comment by cdalvaro** [comment]
I would like to know if this PR will be finally merged

**Comment by cdalvaro** [comment]
Please @xeacott, could you revise this PR, it is open for nearly two months.

Thank you in advance.

**Review by weswhet — APPROVED** [review]
Looks good to me!

**Comment by cdalvaro** [comment]
Please @xeacott, could you revise this PR, it solves an issue introduced in #54136.

By accepting this pull request, #54079 could be closed since it was duplicated in #54136 in order to rebased commits into 2019.2.1 instead of 2019.2

I mention @weswhet too, because I don't know if @xeacott is actively working on this project since I haven't heard from him for a long time.

Thank you all in advance!!

**Review by dwoz — APPROVED** [review]

**Pull request merged**
