### PR TITLE
fix: https://github.com/saltstack/salt/issues/60653

### LINKED ISSUE #60653: [BUG] - nacl.dec returns byte array and is tricky to use with some jinja
**Description**

when using {{salt.nacl.dec('...')|json}} in a pillar I get error:
`'bytes' is not JSON serializable`

**Expected behavior**

The decrypted data be added to the pillar.

**Versions Report**

```
root@salt-master-p01-02:~# salt --versions-report
Salt Version:
          Salt: 3003.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: 2.0.3
     gitpython: 2.1.8
        Jinja2: 2.10
       libgit2: 0.26.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.4.7
        pygit2: 0.26.2
        Python: 3.6.9 (default, Jan 26 2021, 15:33:00)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: 2.0.3
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5
 
System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: UTF-8
       machine: x86_64
       release: 4.15.0-151-generic
        system: Linux
       version: Ubuntu 18.04 Bionic Beaver
```

### PR DESCRIPTION
**Pull request by steverweber**
### What does this PR do?

fix: https://github.com/saltstack/salt/issues/60653

### CODE REVIEW

**Comment by steverweber** [comment]
I don't expect my messy commits to be merged.. I was expecting github to have a rebase option built in... Anyways A dev can create a new fix by tossing .decode on the return for a handful of the functions.

**Comment by xeacott** [comment]
Just saw the ticket, thanks for creating this. Looks like the test failures are related. If you can address those too, I will finish off the PR with any rebasing or precommit needed to get this in.

**Review by Ch3LL — CHANGES_REQUESTED** [review]
this will require a changelog and test coverage.

**Comment by Ch3LL** [comment]
bump @steverweber did you see my review comments?

**Comment by Ch3LL** [comment]
There are also failing tests related to the change.

**Comment by steverweber** [comment]
sorry im just too busy. I hope that the little hint to toss `.decode()` helps someone work through it.

**Comment by steverweber** [comment]
feel free to close this PR and create a new fix.

**Comment by Ch3LL** [comment]
Im going to close this PR but keep the issue open and added the issue to the 3006 milestone to get fixed for that release.

**Pull request closed without merging**
