### PR TITLE
buildout: Restore python_shell for onlyif/unless

### LINKED ISSUE #20936: critical: develop: onlyif/unless is broken (python_shell=False)
This for evident compatiblity amongst existant states tree which have elaborated shell tests for onlyif/unless.
I think it should by on by default, or at least togglable on or off.
So, what to do ? another config opt or a blind python_shell=True

cc @thatch45 @rallytime

### PR DESCRIPTION
**Pull request by kiorky**
This finishes to fix #20936.
This rels #20938.

### CODE REVIEW

**Comment by kiorky** [comment]
this replaces saltstack/salt#20991

**Comment by kiorky** [comment]
cc @s0undt3ch  @thatch45 this should get in before release

**Comment by thatch45** [comment]
Adding the shell=True here can cause a potential security issue, hence why they were removed. Is there any valid reason why the execution module needs an explicit unless/onlyif? I am inclined to remove the unless/onlyif from the zcbuildout module wholesale as they should only be executed in the context of a state.

**Comment by kiorky** [comment]
closing as module is now forked in https://github.com/makinacorpus/makina-states

**Pull request closed without merging**
