### PR TITLE
win_lgpo - additional delvals fixes and string value fix

### PR DESCRIPTION
**Pull request by lomeroe**
### What does this PR do?
Ports fixes from #56060 to other places where the delvals regex was searched.

Corrects an issue where a string value with a semicolon in it would only show the first value in the setting

Adds testing of policy returned from lgpo.get for each ADMX policy test

### What issues does this PR fix or reference?
#56062

### Previous Behavior
Some delvals items would show "**delvals" as the configuration instead of "Disabled"
Items with a semicolon in them (such as the "Enter fully qualified server names separated by semicolons" of "Point and Print Restrictions") would only show the entry up to the semicolon - subsequent runs of lgpo may then reset the value to the shortened string.

### New Behavior
Delval items correctly display the policy setting in lgpo.get
Items with a semicolon show all entries

### Tests written?
Yes

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by twangboy — DISMISSED** [review]

**Comment by twangboy** [comment]
@lomeroe Need to address the test failures (lint, docs, and pre-commit). And it probably needs a rebase...

**Review by Ch3LL — DISMISSED** [review]
any chance you can follow up on @twangboy 's comments here? https://github.com/saltstack/salt/pull/56569#issuecomment-615409717

**Comment by twangboy** [comment]
@lomeroe I rebased and resolved some conflicts here... would you mind making sure I didn't mess this up?

**Review by twangboy — APPROVED** [review]

**Review by Ch3LL — APPROVED** [review]

**Comment by lomeroe** [comment]
@twangboy still looks okay to me, thanks for cleaning this up

**Pull request merged**
