### PR TITLE
Boto rds module

### PR DESCRIPTION
**Pull request by claudiupopescu**
**Implemented:**
- Check if RDS exists
- Check if option group exists
- Check if parameter group exists
- Check if subnet group exists
- Create RDS instance
- Create option group
- Create parameter group
- Create subnet group
- Update parameter group
- Get RDS instance endpoint
- Describe RDS instance
- Delete RDS instance
- Delete option group
- Delete parameter group
- Delete subnet group

There are other functions missing but for now this will do for my use case.

**Special notes:**
- In order to use update parameter group feature you need to check: https://github.com/boto/boto/pull/2169
- For update parameter group there is a limit of 20 items which can be updated at the same time.
- Update parameter group apply_method is global, this can be moved per parameter value if some one wants to.
- More checks and validation might be needed for create and other functions.

### CODE REVIEW

**Comment by thedrow** [comment]
Nice!
Well done.
I will review later today.

**Comment by jfindlay** [comment]
@claudiupopescu, there is a [lint error](https://jenkins.saltstack.com/job/salt-pr-lint-n/1835/violations/file/salt/modules/boto_rds.py).

**Comment by claudiupopescu** [comment]
Flake8 does not catch those.. :)
Should be fixed now.

**Comment by cachedout** [comment]
@thedrow Let us know when you've had a chance to look this over. Thanks!

**Comment by thedrow** [comment]
@cachedout Done.
The documentation also needs improvements.
We need to describe the arguments of each method.

**Comment by thatch45** [comment]
@claudiupopescu @thedrow please let me know when you both feel this is ready to merge

**Comment by claudiupopescu** [comment]
I will add tags support this weekend, in the mean time I am adding additional functionality.

Please feel free and jump in if something is missing or wrongly implemented.
For now I am adapting this to work for my use case so things might be missing :)

**Comment by claudiupopescu** [comment]
@thedrow For RDS2 I can't find a way to get an instance based on tags.

What I found to be close is: ```describe_db_instances(db_instance_identifier=None, filters=None, max_records=None, marker=None)``` and from this one I could use filters. But that is a list of filters and it is not even documented.

As you can see the only identifier used trough the API [documentation](http://boto.readthedocs.org/en/latest/ref/rds2.html) is db_instance_identifier.
This is the actual name of the instance which can not be changed as easy as it is with EC2 names. So from my point of view it is a pretty solid anchor.

Maybe I missed something, but if not, I would like to remove the tags where they are not needed and maybe some one can review this again.

**Comment by thatch45** [comment]
Thanks @claudiupopescu ! This looks fantastic!
We can continue the additions in another PR, this is a good place to put the stake in the ground!

**Pull request merged**
