### PR TITLE
 Adapt napalm modules to the new library structure

### PR DESCRIPTION
**Pull request by mirceaulinic**
Starting with November 2017, the NAPALM library has been reunified
into a monolithic package. This falls with a couple of changes into
the Salt codebase. While the users can continue using napalm_base,
it is recommended to upgrade to napalm 2.0.
At the same time, back in time, the napalm package used to have
a different meaning, so we need to check if the release version
is at least 2.0.

### CODE REVIEW

**Comment by cachedout** [comment]
I don't really like making changes like this in point releases. What do you think about moving this over to the develop branch for release with Oxygen? Do you think it can wait for a few more weeks?

**Comment by mirceaulinic** [comment]
Hi @cachedout - I understand you optic, you explained this before. Unfortunately I'm afraid this cannot wait any longer, as people already upgraded to the new structure, and complained that it doesn't work anymore. So please make an exception this time -- if there will be anyone complaining, or this causes any sort of issues, I will take the entire responsibility! Thanks you!

**Review by cachedout — CHANGES_REQUESTED** [review]
@mirceaulinic Could you please fix these lint errors? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/16201/violations/file/salt/utils/napalm.py/

**Comment by mirceaulinic** [comment]
Hi @cachedout - sure, they should be fixed right now. Thanks!

**Review by cachedout — APPROVED** [review]

**Pull request merged**
