### PR TITLE
addresses issue #43307, disk.format_ to disk.format

### PR DESCRIPTION
**Pull request by msummers42**
This change fixes breakage. It appears the disk.format_ func is
aliased to disk.format in modules/disk.py

### CODE REVIEW

**Comment by msummers42** [comment]
Amended commit to include proper GPG signature.

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
Thanks @msummers42 for fixing this and switching the branch.

The test results have timed out, so I have updated your branch to run them again. (This will cause the GPG check to fail, but that is OK for now.)

**Comment by mwtzzz** [comment]
Can someone please merge this into saltstack repo? I just booted up a host that installed pkg.latest (2017.7.2-1.el7.noarch) which does not contain the fix.

**Comment by rallytime** [comment]
@msummers42 This has a small test failure here. The mocked reference in `tests/unit/states/test_blockdev.py` needs to be updated from `disk.format_` to `disk.format`. Can you update that really quickly?

@mwtzzz This fix will not be included in 2017.7.2 as it has already been released. It will be in the `2017.7.3` release. In the mean time, you can place the patched file in the `_states` and [distribute the new state dynamically](https://docs.saltstack.com/en/latest/ref/file_server/dynamic-modules.html).

**Comment by msummers42** [comment]
@rallytime sure thing, one moment.

**Comment by msummers42** [comment]
Thanks!

**Comment by cblegare** [comment]
shouldn't this be in 2017.7.3 milestone?

**Comment by rallytime** [comment]
@cblegare We don't use milestones that way presently, but this will be included in the 2017.7.3 release.

**Pull request merged**
