### PR TITLE
fix: Update macOS brew list command for casks

### PR DESCRIPTION
**Pull request by cdalvaro**
### What does this PR do?

`brew cask --list` has been deprecated in favor of `brew list --cask` (https://github.com/Homebrew/brew/pull/8390).

This PR changes the command in order to avoid the fallowing warning:

```
❯ brew cask list
Warning: Calling brew cask list is deprecated! Use brew list --cask instead.
```

and prevents for future errors when the command could fail.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests updated
- [ ] ~~Docs~~

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by Akm0d — DISMISSED** [review]

**Comment by Akm0d** [comment]
@cdalvaro  Can you fix the merge conflicts?

**Comment by cdalvaro** [comment]
> @cdalvaro Thank you for the PR! Can the merge conflicts be resolved?

Done!

**Review by Akm0d — APPROVED** [review]

**Comment by cdalvaro** [comment]
After three months being deprecated this has turned into an error:

```
[ERROR   ] stderr: Error: Calling brew cask list is disabled! Use brew list [--cask] instead.
```

**Review by s0undt3ch — APPROVED** [review]

**Review by SMillerDev — APPROVED** [review]
As a brew maintainer, looks good

**Review by s0undt3ch — APPROVED** [review]

**Pull request merged**
