### PR TITLE
Refactor tests/unit/states/test_sysctl.py

### PR DESCRIPTION
**Pull request by asomers**
### What does this PR do?

The old test combined several different independent commands into a
single obese test case, with overlapping local variables.

Break it into small individual test cases.  Also, fix some of the mocks,
which only triggered correct behavior by coincidence.

### Merge requirements satisfied?
- [N/A] Docs
- [N/A] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by asomers** [comment]
Thanks @krionbsd .  Although, I already had such a commit ready to go.  In the future, should I force-push stylistic fixes ASAP rather than wait for the tests to finish?

**Comment by krionbsd** [comment]
> Thanks @krionbsd . Although, I already had such a commit ready to go. In the future, should I force-push stylistic fixes ASAP rather than wait for the tests to finish?

Yeah, that would make sense to reduce total CI run/time

**Comment by asomers** [comment]
And @krionbsd do you prefer that I push style fixes as separate commits, or that I amend the original commit and force-push?

**Comment by krionbsd** [comment]
> And @krionbsd do you prefer that I push style fixes as separate commits, or that I amend the original commit and force-push?

@asomers I think amending the original commit and force-push is ok

**Comment by asomers** [comment]
The test failure in ci/py3/ubuntu1604/m2crypto is definitely unrelated to this PR, because this PR only affects tests in a different file.

**Comment by asomers** [comment]
Again ci/py3/ubuntu1604/m2crypto failed for the exact same reason.  @krionbsd do you have any idea why?

**Review by s0undt3ch — DISMISSED** [review]

**Review by krionbsd — DISMISSED** [review]

**Comment by krionbsd** [comment]
> Again ci/py3/ubuntu1604/m2crypto failed for the exact same reason. @krionbsd do you have any idea why?

That's a magic :)

**Comment by asomers** [comment]
Rebased and squashed

**Comment by asomers** [comment]
The most recent build failure looks unrelated to this PR.

**Review by krionbsd — APPROVED** [review]

**Pull request merged**
