### PR TITLE
DO NOT MERGE: Run expanduser on all paths

### PR DESCRIPTION
**Pull request by thusoy**
### What does this PR do?
Runs `os.path.expanduser` on all file paths to make it easier to work with user-specific files.

### What issues does this PR fix or reference?
#40710

### Tests written?
Yes

This PR currently includes a lot of commits related to the sausage making process of locating and patching the states and modules, I'll remove these once we're ready to merge, just want to get a discussion going to hear if this looks good or not first.

### CODE REVIEW

**Comment by thusoy** [comment]
Ignore all changes to `fix_expanduser.py` and `whitelist.txt`, those were just helpers to help resolve this issue, will remove those before merge.

**Comment by thusoy** [comment]
I know there are some functions that accept keyword arguments that were not covered by my discovery script, but I'm not sure how common they are yet.

**Comment by damon-atkins** [comment]
I would suggest an alternative is to add expand user function to Jinja
https://docs.saltstack.com/en/develop/topics/jinja/index.html
This would allow people to selectively use it.

**Comment by thusoy** [comment]
Is there a case where you would not want expansion?

**Comment by thusoy** [comment]
Rebased. Any feedback on this, @gtmanfred or @cachedout?

**Comment by damon-atkins** [comment]
From https://docs.python.org/2/library/os.path.html
> Unlike a unix shell, Python does not do any automatic path expansions. Functions such as expanduser() and expandvars() can be invoked explicitly when an application desires shell-like path expansion. (See also the glob module.)

As a jinja filter people can selectively use it.
https://docs.saltstack.com/en/develop/topics/jinja/index.html

**Comment by thusoy** [comment]
Sure, but there's a usability trade-off in offloading that to developers, now they have to know that there's a specific jinja filter they need to use (given that the state is written in jinja, also needed for mako and the others), which most will probably not be aware of, and they have to consider for every string they're inputting (which might come from a variable somewhere) whether it needs to be expanded or not. Unless there's a common case where you really *don't* want expansion it's less work for users if states and modules expand automatically.

Is there a reason not to do it automatically in salt, apart from the extra code?

**Comment by cachedout** [comment]
I'm sorry it's taken me so long to get back to this.

I'm still not crazy about this idea. This is a lot of complexity to do something that I still feel like can (and likely should) be handled explicitly by people writing states in the manner that you describe in the original feature issue.

That said, I think that more people should look at this and offer thoughts. I will cc: @saltstack/team-core and @thatch45 to gather additional opinions.

**Comment by thatch45** [comment]
Yes, I am hesitant to approve this one, I worry that it is going to cause unexpected issues and that we should likely just keep things so that expand user is being explicitly called.

**Comment by thusoy** [comment]
To be clear, this is the least complex option to do automatic expansion, it's just manually calling expanduser for every state. All the surrounding code was just to help me find all the places it needed to be injected, which will be removed.

I'd argue for "just works" any day, but if you all disagree that's obviously off the table. In that case a filter should be added for each of the renderers, since it's not possible for a user to inject filters themselves (AFAIK). Should the file module remain as the only one that does automatic expansion then, or should that be removed?

**Comment by terminalmage** [comment]
I'm also not really sold on this. It's too brittle a solution, and we're relying on all future code submitted to the project to also conform to this convention, something that is IMO unrealistic to expect of future contributors.

**Review by terminalmage — COMMENTED** [review]
I'm also not really sold on this. It's too brittle a solution, in that we're relying on all future code submitted to the project to also conform to this convention, something that is IMO unrealistic to expect of future contributors.

**Comment by thatch45** [comment]
My follow up concern is if we should expand user on every path the could be a file. I just worry that it will pull the rug out from under someone

**Comment by cachedout** [comment]
Unfortunately, it appears that the consensus here is that this approach isn't something we'd accept right now. I'm going to go ahead and close this. Thanks, @thusoy. I'm sorry we couldn't get this in.

**Pull request closed without merging**
