### PR TITLE
Add missing devices to RAID array

### PR DESCRIPTION
**Pull request by nadvornik**
### What does this PR do?

Add support for replacing failed disk in RAID array with a new one.

### What issues does this PR fix or reference?

#40100

### Previous Behavior

In state raid.present, if a disk is replaced and has no RAID signature, it is either ignored (if the RAID is already assembled) or it fails with error message "Devices are a mix of RAID constituents and non-RAID-constituents"

### New Behavior
New disks with no signature are added to assembled array.
Added some consistency checks.

### Tests written?

No

### CODE REVIEW

**Comment by cachedout** [comment]
@nadvornik Could you please fix the lint errors outlined here? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/14698/violations/

**Comment by nadvornik** [comment]
pylint errors are fixed. I have no idea how to fix the other failures.

**Comment by cachedout** [comment]
@nadvornik We just need a new mock object added for `file.access` in this test:

https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/14844/testReport/junit/unit.states.test_mdadm/MdadmTestCase/test_present/

If you'd like a hand with that let me know and we can work together to get it figured out. Thanks.

**Comment by nadvornik** [comment]
Is it salt/tests/unit/states/test_mdadm.py ?
I will look into it.

**Review by cachedout — APPROVED** [review]

**Pull request merged**
