### PR TITLE
RFE: base/branch for gitpillars per-remote

### PR DESCRIPTION
**Pull request by The-Loeki**
Complementary to `git_pillar_branch` and `git_pillar_base` this makes both `branch` and `base` per-remote configurable.

### CODE REVIEW

**Comment by terminalmage** [comment]
This is not going to work. The ``git_pillar_base`` and ``git_pillar_branch`` values behave differently in git_pillar as they do in gitfs.

The behavior is described [here](https://docs.saltstack.com/en/latest/ref/configuration/master.html#git-pillar-base).

**Comment by The-Loeki** [comment]
@terminalmage it works on my testsetup alright, just not the way that gitfs does in that it's still git pillar, so you'll still map to a single env.

This is just to make the global configurables per-remote.

**Comment by terminalmage** [comment]
What you're describing is already possible. First of all, the branch is supposed to be submitted in the same line with the remote URL (e.g. ``lab ssh://git@yourgit.example.com/salt/salt-common-pillar.git``).

Overriding the environment can be done with a per-remote parameter called ``env`` (as explained [here](https://docs.saltstack.com/en/latest/ref/configuration/master.html#git-pillar-env)).

The configuration you would need to do what you want is:

```
ext_pillar:
  - git:
    - lab ssh://git@yourgit.example.com/salt/salt-common-pillar.git:
      - env: base
  - git:
    - ssh://git@yourgit.example.com/salt/salt-lab.git:
      - root: pillar
```

**Comment by The-Loeki** [comment]
Well I figured out as much along the way too; I just figured this change would make it a little more flexible, make the syntax more in line with the gitfs and quite frankly you guys very sneakily improved the documentation to better explain what __env__ used to be (and only after your latest pillar improvement commits did we start to fully understand the difference between gitfs and git_pillar ;) )

Anyway, as you note: per-remote `- branch: ` is superfluous with giving the branch on the definition line, and per-remote `- base:` mostly boils down to env superfluidity.

Both however as mentioned have global defaults, so I figured per-remote specific would be a nice addon even after figuring all of this out ;) 

Your call?

**Comment by terminalmage** [comment]
gitfs and git_pillar can't function 100% alike because they have a couple fundamental differences:

* gitfs doesn't check out any branches/tags, while git_pillar does
* A git_pillar remote must also specify a branch/tag to use (because it checks out that ref), while gitfs does not (as all branches and tags can be used)

Making per-remote config params for these two items (which work much differently than their gitfs counterparts) is, in my opinion, superfluous.

**Comment by The-Loeki** [comment]
aight, I'll take it back then :/ see you next time :)

**Comment by terminalmage** [comment]
Thanks, and sorry this didn't work out. Your time and consideration regarding this issue is still much appreciated. Discussions like this are how we make Salt better. We've had our minds changed in the past, so we certainly don't want to discourage engagement like this.

I feel bad that you spent time working on this only to see nothing come of it. If you have a similar concern regarding gitfs/git_pillar in the future, I'm more than happy to discuss it with you before you invest the time and effort writing code.

**Pull request closed without merging**
