### PR TITLE
Fix file comment

### LINKED ISSUE #41818: file.comment issue when multiple lines with some already commented
### Description of Issue/Question
I try to comment some lines in a FreeBSD configuration file. This file contains some comment containing itself the pattern I want to find. Result is that nothing is done.
According to documentation "comment"/"uncomment" do not have a "flags" argument, would it be relevant to add it ?

### Setup
Master(less) : Debian Stretch / virtualenv Python 2.7.13 (pip install salt-ssh) / salt-ssh 2016.11.5 (Carbon)
Minion (agentless) : FreeBSD 11.0 in virtualbox / Python 2.7.13

#### First
On minion : create a file /home/test_user/test.conf :
```
# Test sample
*.whatever;and_also 	 /bad/news

# Don't forget to configure /bad/news before enabling it .. 

*.error /bad/news
```
On master : create a test.sls :
```
test-comment:
  file.comment:
    - name: /home/test_user/test.conf
    - regex: ^.*/bad/news\s*
    - backup: False
```
And add it to top.sls
```
base:
  'the_minion':
    - test
```
#### Than
salt-ssh 'the_minion' state.apply

### What I get
```
salt-ssh 'the_minion' state.apply 
the_minion:
----------
          ID: test-comment
    Function: file.comment
        Name: /home/test_user/test.conf
      Result: True
     Comment: Pattern already commented
     Started: 20:11:39.976112
    Duration: 10.888 ms
     Changes:   

Summary for the_minion
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  10.888 ms
```

But if I replace "/bad/news" by "bAd/news" in line 4 of test.conf, I get :
```
salt-ssh 'the_minion' state.apply 
the_minion:
----------
          ID: test-comment
    Function: file.comment
        Name: /home/test_user/test.conf
      Result: True
     Comment: Commented lines successfully
     Started: 20:17:45.291284
    Duration: 14.342 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -1,7 +1,7 @@
                   # Test sample
                  -*.whatever;and_also 	 /bad/news
                  +#*.whatever;and_also 	 /bad/news
                   
                   # Don't forget to configure /bAd/news before enabling it .. 
                   
                  -*.error /bad/news
                  +#*.error /bad/news
                   

Summary for the_minion
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  14.342 ms
```

### PR DESCRIPTION
**Pull request by mbunkus**
### What does this PR do?

It fixes both the `file.comment` and `file.uncomment` state functions's behavior: both failed to do anything if the pattern is present in both commented and uncommented form.

### What issues does this PR fix or reference?

It fixes #41818.

### Previous Behavior

When both commented and uncommented lines with the pattern existed, both states did nothing and reported that the pattern was already (un)commented. Lines that could be (un)commented were not.

### New Behavior

The logic is reversed. If there's at least one line to (un)comment, all relevant lines will be (un)commented. Only if there's nothing to do will a search for an already (un)commented line be made in order to make the return message more meaningful (either "pattern already (un)commented" or "pattern not found").

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by twangboy — APPROVED** [review]

**Comment by twangboy** [comment]
@mbunkus Looks like this is causing some test failures.

**Comment by mbunkus** [comment]
I'll be out of town for several days. I'd appreciate it if someone else could fix up the tests. If not, I'll try to get around to it end of next week or so.

**Comment by mbunkus** [comment]
I cannot run the tests at the moment. I've never done that before, so I don't know what the problem might be.

I have a venv set up & activated; it's the one I use for running my changed states/modules. I did read `HACKING.rst` and installed the dev requirements for Python 2.7 in the venv. However, running `./setup.py test` results in:

```
# tons of messages about installing stuff, then:
running test
Traceback (most recent call last):
  File "/home/mosu/prog/salt/tests/runtests.py", line 61, in <module>
    from tests.integration import TestDaemon  # pylint: disable=W0403
  File "/home/mosu/prog/salt/tests/integration/__init__.py", line 34, in <module>
    from tests.support.processes import *  # pylint: disable=wildcard-import
  File "/home/mosu/prog/salt/tests/support/processes.py", line 18, in <module>
    from pytestsalt.utils import collect_child_processes, terminate_process, terminate_process_list  # pylint: disable=unused-import
ImportError: No module named pytestsalt.utils
```

Yeah… there's no file or directory whose name contains `pytestsalt`:

```
[0 mosu@sweet-chili (fix-file-comment) ~/prog/salt] find -iname '*pytestsalt*'
[0 mosu@sweet-chili (fix-file-comment) ~/prog/salt] find ~/opt/salt-dev/ -iname '*pytestsalt*'
[0 mosu@sweet-chili (fix-file-comment) ~/prog/salt]
```

So… what now?

**Comment by mbunkus** [comment]
Oh, `pip install -r requirements/pytest.txt` seems to fix that problem. Looks like `HACKING.rst` is outdated.

**Comment by mbunkus** [comment]
I've fixed the unit test logic to accommodate the change to the `file.(un)comment` state functions. That test (`unit.states.test_file`) passes for me now and should hopefully pass on the builders as well.

**Pull request merged**
