### PR TITLE
zabbix.host_get should use host instead of name to get host information

### PR DESCRIPTION
**Pull request by angeloudy**
host_get should use host to get the zabbix host info.
This was already explained in the doc.
host means the technical name of the host while name means the visible name.

So here it should use host, not name.

```
    Retrieve hosts according to the given parameters.
    NOTE: This function accepts all optional host.get parameters: keyword argument names differ depending on your
    zabbix version, see: https://www.zabbix.com/documentation/2.4/manual/api/reference/host/get

    .. versionadded:: 2016.3.0

    :param host: technical name of the host
    :param name: visible name of the host
    :param hostids: ids of the hosts
    :param _connection_user: Optional - zabbix user (can also be set in opts or pillar, see module's docstring)
    :param _connection_password: Optional - zabbix password (can also be set in opts or pillar, see module's docstring)
    :param _connection_url: Optional - url of zabbix frontend (can also be set in opts, pillar, see module's docstring)
```

### CODE REVIEW

**Comment by rallytime** [comment]
@angeloudy Looks like another conflict here. Make sure you're getting the latest from the saltstack upstream when making your changes so you can avoid the merge conflicts. :)

Please let us know if you have any questions.

**Comment by angeloudy** [comment]
It seems the latest upstream already fixed the localtime issue. When I submit the pull request, can I choose just one commit. In this case, I just want to submit my changes in zabbix_host.py.

**Comment by rallytime** [comment]
@angeloudy Yeah, that's fine.

**Comment by rallytime** [comment]
@angeloudy Did you get a chance to rebase this and fix the merge conflicts?

**Comment by angeloudy** [comment]
@rallytime I am not sure how. Do I need to submit another pull request? I don't have permission to resolve the conflicts.  I didn't want to submit "salt/states/zfs.py".

**Comment by rallytime** [comment]
Hi @angeloudy - there's some useful information in step 6 of [these docs](https://docs.saltstack.com/en/latest/topics/development/contributing.html#sending-a-github-pull-request) about rebasing.

You're pulling in extra changes into a single pull request because you haven't renamed the branch you're submitting from. Your develop branch contains commits from both of your fixes. You can learn more about branching [here](https://guides.github.com/introduction/flow/).

**Pull request closed without merging**
