### PR TITLE
clouds/ec2.py: allow to call stop, start, destroy, delvol_on_destroy, attach_volume, detach_volume as function

### PR DESCRIPTION
**Pull request by bailsman**
I would like to script creating an image on salt. For this, I'll create a temporary instance. This temporary instance will not be in any map, so I cannot use actions. But I have the instance_id, and provider, so _can_ use functions. For creating an image, I would like stop, start, destroy, delvol_on_destroy, attach_volume, detach_volume to be callable as function. ( Just like show_instance can be called both as action and as function. )

Also, it would be nice to support passing an instance_id as name.  _get_node(name) already supports this, specifically checking if name fits the format of instance_id.

Note, I am not sure I understand salt code that well. Happy to receive feedback.

Thanks.

### CODE REVIEW

**Comment by nmadhok** [comment]
@codehotter @techhat Actions are performed on instances and functions are performed on providers. If start, stop, destroy are actions, it means that they start, stop, destroy instances. If start, stop, destroy are functions instead, it would either mean that they start, stop, destroy all instances present in the provider at the same time or they start, stop, destroy objects other than instances. This would change a lot of the assumptions made in many other cloud provider actions and functions.

**Comment by codehotter** [comment]
nmadhok, thank you for your comment and clarification. It seems I went about this entirely the wrong way. I confess I don't really understand the difference between action and functions. I just saw that, as soon as I specify a provider, it's treated as function.

```
salt/cloud/__init__.py - CloudClient.action
 450         if names and not provider:
 451             self.opts['action'] = fun
 452             return mapper.do_action(names, kwargs)
 453         if provider:
 454             return mapper.do_function(provider, fun, kwargs)
```

So, if I have a provider and an instanceid, how do I call an action on that instance? Or, in general, how do I interact with instances that are not in a map? Or alternatively, how do I control what a map looks like and what provider the map is about? If I have two providers and multiple instances with the same name, how do I control what provider is being operated on?

Thank you for your time.

**Comment by rallytime** [comment]
@codehotter You can perform actions against individual VMs. The following docs might help clarify some of the points mentioned above:
- Cloud Actions: http://docs.saltstack.com/en/latest/topics/cloud/action.html
- Cloud Function: http://docs.saltstack.com/en/latest/topics/cloud/function.html
- Cloud Feature Matrix, which shows which functions and actions are available per provider. For example, some actions like stopping and starting a VM are available on EC2, but not all providers allow this functionality: http://docs.saltstack.com/en/latest/topics/cloud/features.html

**Comment by codehotter** [comment]
rallytime, thank you for your comment. I've read the links you provided but unfortunately, some questions still remain.

Consider this test case:

```
import salt.cloud
client = salt.cloud.CloudClient(path='/etc/salt/cloud')

create_args = {
    "image": "ami-e4ff5c93", # Centos 7 HVM
    "size": "t2.micro",
    "deploy": False,
    "ssh_username": "centos",
    "del_root_vol_on_destroy": True,
}

name = "test_mapper"

instance_id_1 = client.create("ec2-ireland", name, **create_args)[name]['instanceId']
instance_id_2 = client.create("ec2-ireland-test", name, **create_args)[name]['instanceId']

print("instance_id_1: " + instance_id_1)
print("instance_id_2: " + instance_id_2)
print("function_by_name_1: " + client.action("show_instance", provider="ec2-ireland", kwargs={"name": name}).values()[0].values()[0][name]['instanceId'])
print("function_by_name_2: " + client.action("show_instance", provider="ec2-ireland-test", kwargs={"name": name}).values()[0].values()[0][name]['instanceId'])
print("function_by_instance_id_1:"+ client.action("show_instance", provider="ec2-ireland", kwargs={"name": instance_id_1}).values()[0].values()[0][name]['instanceId'])
print("function_by_instance_id_2:"+ client.action("show_instance", provider="ec2-ireland-test", kwargs={"name": instance_id_2}).values()[0].values()[0][name]['instanceId'])
print("action_by_name: ", client.action("show_instance", names=name))
print("action_by_instance_id_1: ", client.action("show_instance", names=instance_id_1))
print("action_by_instance_id_2: ", client.action("show_instance", names=instance_id_2))
```

It prints the output below. I would like to call an action using provider, instance_id combination to ensure I reach the right instance.
How do I do this? I can use functions just fine, if I take care to provide instanceId and not just name. But I don't seem to be able to use actions, since the instance I've just created is not mapped.

```
instance_id_1: i-df692a75
instance_id_2: i-a92c8803
function_by_name_1: i-045a19ae          # Not guaranteed to get correct instance by name, there might be another one with the same name.
function_by_name_2: i-b048ec1a
function_by_instance_id_1:i-df692a75    # Works perfectly
function_by_instance_id_2:i-a92c8803
('action_by_name: ', {'Not Actioned/Not Running': ['a', 'e', 'm', 'p', 's', 'r', 't', '_']}) # Just created instance is not mapped, so cannot use actions
('action_by_instance_id_1: ', {'Not Actioned/Not Running': ['a', 'd', 'f', 'i', '-', '2', '5', '7', '6', '9']})
('action_by_instance_id_2: ', {'Not Actioned/Not Running': ['a', 'c', 'i', '-', '0', '3', '2', '9', '8']})
```

**Comment by rallytime** [comment]
@techhat Can you comment on this one? I think you'll be able to talk to this question more accurately than I.

**Comment by techhat** [comment]
If you have the instance-id, you should be able to use that as the "name" of the instance, so you can still call it as an action. There's no reason to call it as a function.

If calling an action on an instance-id is not working, then that needs to be fixed.

**Comment by rallytime** [comment]
If calling an action on an instance-id isn't working, then there is a bug here that should be fixed. However, I don't think that this is the correct approach to fix that bug. I am going to close this so we don't accidentally merge this in.

Thanks for your questions and work here @codehotter. We're happy to discuss any other questions you may have either on this issue, or if the instance-id action is indeed a bug, then a new issue should be filed for that. Thank you again!

**Pull request closed without merging**
