### PR TITLE
[Feedback wanted] Add basic thorium register interpolation

### PR DESCRIPTION
**Pull request by Timbus**
### What does this PR do?
This is a quick-n-dirty, but pretty effective implementation of being able to access thorium registers when invoking a 'local.cmd' from thorium.
Without this feature thorium is fairly impotent at reacting to events compared to the default reactor, which is a shame because it is (imo) a better framework for building reactive components.
I tried to follow the 'slots' convention but its just so _extra_ in its implementation and syntax, I couldn't do it. I just let jinja do the work instead.
I am willing to add this feature to other thorium modules. I'm also very open to change suggestions.

Do I think this is the best approach? Probably not. If thorium .sls files were compiled per-run this change would be unneeded. And if the register concept were more global (hint hint) then this would feel like less of a bespoke system tacked onto salt. Another approach might be to have thorium have separate runtime and compiletime .sls files, but that's a huge change.

While I have your attention: I also think registers in thorium are gimped by having a 'val', 'count' and 'total' forced into them for every usage. It's just such an insanely specialized case that detracts from their general purpose nature. Why not only add a count+total when needed?

### What issues does this PR fix or reference?
This is related to #58114 , though only slightly. 

### New Behavior
local.cmd now runs 'tgt', 'func', 'args' and 'kwarg' through jinja before passing them onto LocalClient.cmd_async

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by DmitryKuzmenko** [comment]
@Timbus could you please fix the `lint` and `pre-commit` issues? Also this change needs to be covered with some tests.
@saltstack/team-core I'm basically good with this change but could anyone please also take a look at this code too?

**Comment by Timbus** [comment]
I think I corrected the issues as reported, but I guess something else is missing.

After thinking on it a bit, I was wondering if the use of NativeEnvironment like this would be acceptable? Should it be put into the template util? Also, is the bracket usage acceptable? There could be better alternatives that more experienced python folks might know about.

**Comment by thatch45** [comment]
This is a fantastic feature, I love it. But it is a one-off language change, and we need to be really careful there. We will also need more docs for it and tests.
I am wondering if there is another way to process the jinja, and perhaps process the jinja via the renderer sequence.
In a nutshell, I love this, but I think we need to figure out a better way to make it happen

**Comment by Timbus** [comment]
> This is a fantastic feature, I love it. But it is a one-off language change, and we need to be really careful there. We will also need more docs for it and tests.

Awesome to hear, honestly. My goal was to pursue a feature that would also see utility if ported to states and orchestrations, because it ultimately allows functions to pass variables, a sore spot for me and my team as we get used to this tool.
So though it is one-off right now, I'd like to think of it as something that can be expanded.

> I am wondering if there is another way to process the jinja, and perhaps process the jinja via the renderer sequence.

The jinja NativeEnvironment seems to be a perfect way to deal with the difficulties in parsing and typing, so I was hoping this would just be a case of finding a delimiter that works for everyone..
How would you go about preparsing it? Something that takes the {| |} a placeholder at compiletime and mangles it into some long delimiters? I don't mind that idea but it forces a new renderer to be used, and I was hoping it would work with the default setup.
.. Would it be better to use a flag? A named arg that you use to 'inject' the named variables into your states, if they need them? Then you don't need to brute-force through so many jinja calls as well.
Or, how about something similar to python's new f"formatted {string}s" ? Again it narrows down the things we filter through jinja.

Thoughts on those two options?

> In a nutshell, I love this, but I think we need to figure out a better way to make it happen

:+1:

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
