### PR TITLE
allow_creation_token_boto_efs: Allow creation_token to be passed into…

### PR DESCRIPTION
**Pull request by ac-hibbert**
… create_file_system and get_file_systems

Change-Id: Iccadf6313bac1e41658228d13e294ba17205053d

What does this PR do?

Allows you to specify creation_token so you can create a file system idempotently when calling boto_efs.create_file_system and allows you to specify creation_token when searching for file systems in boto_efs.get_file_systems
What issues does this PR fix or reference?
Previous Behavior

You run salt once with a name for the EFS, it will create the EFS with a random creation_token, if you run it again you will get another file system with a different creation_token.

You cannot search for a file system using a creation_token.
New Behavior

By default the creation_token when creating the filesystem would be random but you have the option of passing it in, meaning if you try to run salt again it will fail on creating the filesystem.

When searching for a filesystem you have the option of passing in creation_token, which is useful if you have created it using the creation_token, because it is easier to search on than filesystemid which will always be unique.
Tests written?

No

Please review Salt's Contributing Guide for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
cc: @ryan-lane

**Comment by ryan-lane** [comment]
Hm. How would the usage of this look from the state module? Would you pass in the efs volume name as the creation_token? If possible we always use the resource's name for its consistent ID. Would be ideal for this module to work similarly for consistency.

**Comment by hibbert** [comment]
I guess that in the state module (there isn't one currently), the creation_token could be set based on the name and passed through.

Alternatively if the name should be the consistent ID maybe the creation_token should be set to name in the execution module and never be generated randomly. Leaving the state module just to pass in name. I was a bit unsure why this was random in the first place.

**Comment by ryan-lane** [comment]
I think it would be good to allow the creation token to be passed in, but if it isn't passed in, the name is used by default. From the state module's perspective (when it exists), it should pass in the name and leave the content token as None.

**Comment by hibbert** [comment]
Changed this but it created a new PR, I guess because the remote branch didn't exist my end anymore. It is here - https://github.com/saltstack/salt/pull/42811. I'll close this one.

**Pull request closed without merging**
