### PR TITLE
Improve error reporting in cherrypy

### PR DESCRIPTION
**Pull request by whytewolf**
### What does this PR do?

fixes 400 error reporting in cherrypy to give users more context about issue. 

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/63835

### Previous Behavior
400 error was generic

### New Behavior
adds exception message from exception that caused 400 to 400 error and log error. 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

### CODE REVIEW

**Review by s0undt3ch — DISMISSED** [review]

**Comment by s0undt3ch** [comment]
@whytewolf Mind adding a test case verifying that we now see the message that we previously didn't?

**Comment by whytewolf** [comment]
> @whytewolf Mind adding a test case verifying that we now see the message that we previously didn't?

no problem. test added. took a little longer than i wanted to do though.

**Review by s0undt3ch — APPROVED** [review]
Thank You.

**Review by Ch3LL — DISMISSED** [review]

**Review by twangboy — DISMISSED** [review]

**Review by s0undt3ch — DISMISSED** [review]

**Comment by s0undt3ch** [comment]
Approved and tests are passing. Merging.

**Pull request merged**
