### PR TITLE
Deprecate show_diff for file.serialize to mimic file.managed, closes #38853

### LINKED ISSUE #38853: file.serialize still expects show_diff instead of show_changes
### Description of Issue/Question

#30988 deprecated `show_diff` and replaced it with `show_changes` for all `file.*` states. All of them, except for `file.serialize`.

I would've made a PR, but forward-merging makes it quite challenging to me.

### Setup

Both 2016.3.4 and 2016.11.1 have this bug. It is also visible in documentation.

### PR DESCRIPTION
**Pull request by bobrik**
I also made it hide changes during the dry run.

### CODE REVIEW

**Review by cachedout — COMMENTED** [review]
We do not typically introduce deprecation warnings in minor releases. I would like to move this to the develop branch instead.

**Comment by bobrik** [comment]
I'm fine with deprecating things in `develop`, but is it possible to make `show_changes` work in the next minor release?

**Comment by cachedout** [comment]
@bobrik We typically do not add new functionality in a minor release unless it fixes a well-established bug. Limiting new functionality in minor releases is something that the community has been very vocal about. :]

**Comment by bobrik** [comment]
Inconsistency in file.* states i a bug in my opinion, see #38853. I expect the same name for a parameter that does the same thing across the all file.* states.

I would't say this functionality is new, the original (supposedly accidentally incomplete) deprecation happened in 2016.3.0.

**Comment by cachedout** [comment]
I agree. I've merged this. Thanks for clarifying, @bobrik

**Pull request merged**
