### PR TITLE
Ponies!

### PR DESCRIPTION
**Pull request by cachedout**
Because who would want a cow when they can have a pony?

### CODE REVIEW

**Comment by thatch45** [comment]
Yes, SO much better than cows

**Comment by basepi** [comment]
Will the highstate outputter barf on non-highstate data? I haven't been in outputters for a long time so I figured I'd double check.

**Comment by techhat** [comment]
This looks like something that should be gated. I know my system didn't have `ponysay` before I saw this PR. It does now of course.

**Comment by cachedout** [comment]
pony

**Comment by cachedout** [comment]
@basepi I just did a `test.ping` and it went OK. I think it will mostly fall back.

**Comment by thatch45** [comment]
yes, it is made to fall back to `nested`

**Comment by thatch45** [comment]
need to fix subprocess, this won't run on python 2.6, although I must admit, I am not too worried about that, since that is basically people still running RHEL 5 and 6, and they don't have a sense of humor :)

**Comment by cachedout** [comment]
@thatch45 I was in a hurry! This outputter was written in less than ninety seconds. ;]

**Comment by thatch45** [comment]
I just wanted to complain about our python 2.6 platforms in a comical place is all :)

**Comment by cachedout** [comment]
@thatch45 I could make the pony complain about it too. ;]

**Comment by thatch45** [comment]
Not a bad idea

**Comment by sjorge** [comment]
+1, this is great!

**Pull request merged**
