### PR TITLE
Update to PR 35899 states/pkg (refresh fix) and win_pkg (winrepo cache mgt, refresh, doco, performance)

### PR DESCRIPTION
**Pull request by damon-atkins**
### What does this PR do?

_modules/win_pkg.py_
Code clean up and improvements based on feed back on the original PR
e.g. dealing with configuration options, and  refresh_db
Also:
- add missing doco mainly around parameters for functions
- Memory caching of the metadata db per run, instead of reading it multiple times
  from disk.
- centralised the refresh test, instead of a if statement in most functions, allow better logging etc 
- list_available issue with code which tried sort the list, did not. Now Fixed
- raise_error renamed to failhard (note this was never in a production release)
- get_name_map() removed (Add to **release notes**, use get_repo_data() instead)
- previous updates for saltenv changes in develop several months ago broke compatibility with older 2015 and 2016 release, updates here to try to fix this.
  e.g.

```
2016 def list_available(*names):
develop def list_available(saltenv='base', *names)
fixed to def list_available(*names, **kwargs)  saltenv taken from kwargs
```

_states/pkg.py Fixes_
- Fixes installed() in states/pkg.py which was calling calling refresh DB to much. This involved replacing the current code with a new function called _refresh_tag_file()
- latest()  in states/pkgpy change to use the new function _refresh_tag_file()
- remove windows specific code around refreshing db

_config additions_
`winrepo_cache_expire_max` and `winrepo_cache_expire_min`
### What issues does this PR fix or reference?

See PR 35899
Thanks should go to @terminalmage for reviewing not just my code but the whole of win_pkg.py coding and improving it  and also bring all of it back into line with salt coding style.
### Previous Behavior

Carbon branch has compatibility issues with 2015 and 2016 with saltenv changes
Missing metadata db was reported as an error
### New Behavior

More compatible with 2015 and 2016 re saltenv
Package State Files fetched and metadata created if missing or stale. 
### Tests written?

No Updates tests

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by damon-atkins** [comment]
Hi @rallytime
Ready to merge passes all but
```
default — Pull Requests » Salt PR - Main Build #5229
jenkins/PR/salt-pr-rs-cent7-n — Pull Requests » Salt PR - RS CentOS 7 #5314 — FAILURE
```

**Comment by UtahDave** [comment]
Hi, @damon-atkins I'm testing this off your PR and I'm getting the following error:

```
root@bouchamaster:~# time salt davewintest state.highstate
davewintest:
----------
          ID: filezilla
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1744, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1704, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\pkg.py", line 1272, in installed
                  **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\pkg.py", line 373, in _find_install_targets
                  pkginfo = _get_package_info(name, saltenv=kwargs['saltenv'])
                File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 1569, in _get_package_info
                  return get_repo_data(saltenv).get('repo', {}).get(name, {})
                File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 1498, in get_repo_data
                  (_, _, winrepo, repo_age_sec) = _get_repo_src_dest_details(saltenv)
                File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 584, in _get_repo_src_dest_details
                  winrepo_age = time.time()-os.stat(winrepo_file).st_mtime
              NameError: global name 'time' is not defined
     Started: 12:21:41.868000
    Duration: 60767.0 ms
     Changes:   

Summary for davewintest
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  60.767 s
ERROR: Minions returned with non-zero exit code

real	1m25.816s
user	0m1.835s
sys	0m0.236s
```

**Comment by damon-atkins** [comment]
Thanks @UtahDave not sure how I missed that.  I tested every function within win_pkg. It's good to have a review process.  It will be fanatic when windows is tested in Jenkins.

**Comment by UtahDave** [comment]
I added `import time` to  `states/pkg.py` under the gated windows imports and the error went away.

**Comment by UtahDave** [comment]
Sorry, after that fix I found another thing.

Even with `refresh=False` the repo is still refreshed.

**Comment by UtahDave** [comment]
Also, I'm still seeing a pkg refresh_db for each `pkg.installed` in this sls file:

```
filezilla:
  pkg.installed

pidgin:
  pkg.installed

vlc:
  pkg.installed

ccleaner:
  pkg.installed
```

**Comment by damon-atkins** [comment]
The issue is with states/pkg.py   The same issue exist in 2016.3 and most likely earlier see issue 36133.  If you wish to test using highstate you need to use pkg.latest which works correctly
```
C:\salt>salt-call pkg.refresh_db
[ERROR   ] pkgname "dvschedulerX" version "1" within "dvscheduler2.sls", "version number" is not a string
[ERROR   ] pkgname "dvschedulerX" version "2" within "dvscheduler2.sls", "version number" is not a string
[ERROR   ] failed to compile "salt-winrepo-ng\check-mk-agent.sls", check syntax, Conflicting ID 'Not Found'
[ERROR   ] pkgname "duplicati" version "skip_urltest" within "salt-winrepo-ng\duplicati.sls", "version number" is not defined as dictionary(hash) key
[ERROR   ] failed to compile "salt-winrepo-ng\intellij.sls", check syntax, Conflicting ID '1'
Error running 'pkg.refresh_db': Error occurred while generating repo db. Additional info follows:

failed:
    4
failed_list:
    ----------
    dvscheduler2.sls:
        - pkgname "dvschedulerX", version "1" is not a string
        - pkgname "dvschedulerX", version "2" is not a string
    salt-winrepo-ng\check-mk-agent.sls:
        - failed to compile, check syntax, Conflicting ID 'Not Found'
    salt-winrepo-ng\duplicati.sls:
        - pkgname "duplicati", version "skip_urltest" is not defined as a dictionary(hash) key
    salt-winrepo-ng\intellij.sls:
        - failed to compile, check syntax, Conflicting ID '1'
success:
    228
total:
    232

C:\salt>salt-call state.single pkg.installed name=filezilla refresh=False test=True
[ERROR   ] Command 'Import-Module ServerManager' failed with return code: 1
[ERROR   ] output: Import-Module : The specified module 'ServerManager' was not loaded because no valid module file was found in any module directory.
At line:1 char:1
+ Import-Module ServerManager
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (ServerManager:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
local:
----------
          ID: filezilla
    Function: pkg.installed
      Result: None
     Comment: The following packages would be installed/updated: filezilla=3.16.0
     Started: 12:12:19.281000
    Duration: 67.0 ms
     Changes:

Summary for local
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
Total run time:  67.000 ms

C:\salt>salt-call state.single pkg.installed name=filezilla refresh=True test=True
[ERROR   ] Command 'Import-Module ServerManager' failed with return code: 1
[ERROR   ] output: Import-Module : The specified module 'ServerManager' was not loaded because no valid module file was found in any module directory.
At line:1 char:1
+ Import-Module ServerManager
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (ServerManager:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
[ERROR   ] pkgname "dvschedulerX" version "1" within "dvscheduler2.sls", "version number" is not a string
[ERROR   ] pkgname "dvschedulerX" version "2" within "dvscheduler2.sls", "version number" is not a string
[ERROR   ] failed to compile "salt-winrepo-ng\check-mk-agent.sls", check syntax, Conflicting ID 'Not Found'
[ERROR   ] pkgname "duplicati" version "skip_urltest" within "salt-winrepo-ng\duplicati.sls", "version number" is not defined as dictionary(hash) key
[ERROR   ] failed to compile "salt-winrepo-ng\intellij.sls", check syntax, Conflicting ID '1'
local:
----------
          ID: filezilla
    Function: pkg.installed
      Result: None
     Comment: The following packages would be installed/updated: filezilla=3.16.0
     Started: 12:12:45.542000
    Duration: 12465.0 ms
     Changes:

Summary for local
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
Total run time:  12.465 s

C:\salt>salt-call state.single pkg.installed name=filezilla refresh=False test=True
[ERROR   ] Command 'Import-Module ServerManager' failed with return code: 1
[ERROR   ] output: Import-Module : The specified module 'ServerManager' was not loaded because no valid module file was found in any module directory.
At line:1 char:1
+ Import-Module ServerManager
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (ServerManager:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
local:
----------
          ID: filezilla
    Function: pkg.installed
      Result: None
     Comment: The following packages would be installed/updated: filezilla=3.16.0
     Started: 12:13:24.389000
    Duration: 69.0 ms
     Changes:

Summary for local
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
Total run time:  69.000 ms

C:\salt>salt-call state.single pkg.installed name=filezilla  test=True
[ERROR   ] Command 'Import-Module ServerManager' failed with return code: 1
[ERROR   ] output: Import-Module : The specified module 'ServerManager' was not loaded because no valid module file was found in any module directory.
At line:1 char:1
+ Import-Module ServerManager
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (ServerManager:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
[ERROR   ] pkgname "dvschedulerX" version "1" within "dvscheduler2.sls", "version number" is not a string
[ERROR   ] pkgname "dvschedulerX" version "2" within "dvscheduler2.sls", "version number" is not a string
[ERROR   ] failed to compile "salt-winrepo-ng\check-mk-agent.sls", check syntax, Conflicting ID 'Not Found'
[ERROR   ] pkgname "duplicati" version "skip_urltest" within "salt-winrepo-ng\duplicati.sls", "version number" is not defined as dictionary(hash) key
[ERROR   ] failed to compile "salt-winrepo-ng\intellij.sls", check syntax, Conflicting ID '1'
local:
----------
          ID: filezilla
    Function: pkg.installed
      Result: None
     Comment: The following packages would be installed/updated: filezilla=3.16.0
     Started: 12:13:47.921000
    Duration: 12415.0 ms
     Changes:

Summary for local
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
Total run time:  12.415 s
```

**Comment by damon-atkins** [comment]
Hi @UtahDave 
I have added a patch to Issue 36133 as its not an issue which is associated with this this PR and the patch needs to be applied to at least 2016, not sure how far back it should go.

**Comment by damon-atkins** [comment]
Hi @UtahDave  please re-test.

**Comment by UtahDave** [comment]
@damon-atkins this is looking pretty good according to my tests!

**Comment by damon-atkins** [comment]
@meggiebot Please Label C4 &  Carbon

**Comment by terminalmage** [comment]
@damon-atkins I'm reviewing this right now and also working on cleaning some of this up, so please don't submit any further commits as I'm working on changes of my own.

[This parameter](https://github.com/saltstack/salt/pull/36222/files#diff-2b9074028b9f977443fd6d4337b67cc4R208) is very awkwardly named. It also doesn't exist in any of the other package providers. I don't like the idea of the same function having different features on different platforms, and since there is literally nothing in the Salt codebase which utilizes this argument, I don't think it should be here.

**Comment by terminalmage** [comment]
I also don't understand the reason for the ``raise_error`` param that's being passed around. The error contains the results printed via the nested outputter to the console, but the exception (if caught) does retain the ``info`` param passed to it as an attribute:

```python
>>> from salt.exceptions import CommandExecutionError
>>> exc = CommandExecutionError('Message goes here', info={'foo': 1, 'bar': 2})
>>> exc.info
{'foo': 1, 'bar': 2}
>>>
```

Do you have a use case for not raising an exception? In some cases (like in your `_refresh_db_conditional()` it looks like we're only doing this so we can see if something failed and then raise an exception if there were any failures. However, we're already doing this check in `refresh_db()` and raising the exception there, so this seems redundant.

**Comment by damon-atkins** [comment]
OK.   You sort of need a page with common parameter names, so people can pick from them if they need one.  I try to grep through all of the files to try and get an existing one.

The problem is that some of the function return different structures based on how many argument are passed, which means its not consistent..

**Comment by terminalmage** [comment]
`_refresh_db_conditional()` is returning a bool that nothing is ever done with.

**Comment by terminalmage** [comment]
@damon-atkins with regard to consistency, the whole reason that we return different types based on the number of arguments was because in the beginning Salt did not support handling multiple package names in the same pkg.installed/pkg.latest/etc. state. However, once this functionality was added, we couldn't just modify pkg.version, pkg.latest_version, etc. to always return a dict, because that would break backwards compatibility with the original usage.

I think there's a good case to be made to include an argument that will force the return to always be a dict, but I think it A) needs a better name and B) must be applied to all pkg virtual modules. Therefore, in my cleanup I plan on removing this, and I'll look into adding this to all pkg virtual modules in a separate pull request.

I like what I'm seeing in this PR, but it needs some changes for the sake of future maintainability. So, the overall functionality will more or less remain intact. I'm just giving it a facelift :smile:

If you could keep an eye on this thread and address any questions/comments I have, that would be awesome. Once I have this edited, I'm going to pass it on to @UtahDave for testing, and we'll go from there.

**Comment by damon-atkins** [comment]
raise CommandExecutionError   gives returns text to the calling function. It does not return a structure that you can look at and evaluate or process, hence the raise_error=False which allows the calling process or function to still get the data required.

  >_refresh_db_conditional() is returning a bool that nothing is ever done with.
True. I have always try to return if a function succeeds or not. its up to the caller to determine if they wish to do anything about it.   In python one more option which is raise.
Old behavior is not to care if refresh_db works or not.  In the future someone may want to change that.

**Comment by damon-atkins** [comment]
```
        salt-run pkg.genrepo
        salt -G 'os:windows' pkg.genrepo verbose=true raise_error=false
        salt -G 'os:windows' pkg.genrepo saltenv=base
```

**Comment by damon-atkins** [comment]
# salt -G 'os:windows' pkg.refresh_db raise_error=True
abcserver:
    ERROR: Error occurred while generating repo db. Additional info follows:
image


# salt -G 'os:windows' pkg.refresh_db raise_error=false
abcserver:
image

salt -G 'os:windows'  --out=json pkg.refresh_db raise_error=false | python summaries_info_errors.py

**Comment by damon-atkins** [comment]
Example updated of raise_error

**Comment by damon-atkins** [comment]
Example updated again

**Comment by terminalmage** [comment]
When I asked:

> Do you have a use case for not raising an exception?

I wasn't asking for CLI usage. I was asking for a practical application for suppressing the exception. I don't see one.

> raise CommandExecutionError returns text to the calling function. It does not return a structure that you can look at and evaluate or process

Yes it does, I tried to make that clear in an earlier comment. The ``info`` argument is retained as an attribute to the exception. So, let's say you capture the exception. You can then do whatever you want to process the data passed as the ``info`` param to the exception. In this example I'm just printing it: 

```
>>> try:
...     raise CommandExecutionError(
...         'Houston, we have a problem.',
...         info={'situation': 'FUBAR'}
...     )
... except CommandExecutionError as exc:
...     print(exc.info)
...
{'situation': 'FUBAR'}
>>>
```

You could also have the best of both worlds and interact with the data and then reraise the exception:

```
>>> try:
...     raise CommandExecutionError(
...         'Houston, we have a problem.',
...         info={'situation': 'FUBAR'}
...     )
... except CommandExecutionError as exc:
...     print(exc.info)
...     raise exc
...
{'situation': 'FUBAR'}
Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
salt.exceptions.CommandExecutionError: Houston, we have a problem. Additional info follows:

situation:
    FUBAR
>>>
```

So, given this information, I don't see the use for keeping the exception from being raised. Especially when ``_refresh_db_conditional()`` is passing ``raise_error=False`` to ``refresh_db()`` (ignoring, by the way, the ``raise_error`` kwarg passed into ``_refresh_db_conditional()``, then checking the return data and raising an exception itself if there were failures.

**Comment by terminalmage** [comment]
Actually, after re-reading the example and re-reading the final line I do see this as a use case. Sorry for misreading, I'll blame it on the fact that it is way past my bedtime.

In this case, the more "salty" name for a param that does something like your ``raise_error`` is ``failhard``, so I may change it to that to make it more consistent with other similar use cases.

**Comment by damon-atkins** [comment]
Fine with the name change....

**Comment by damon-atkins** [comment]
Salt Stack needs to list a common list of kwargs with a few lines indicate when to use them in code.  Maybe in the code style doco.

**Comment by damon-atkins** [comment]
@terminalmage    Thanks for the late night review. It's the afternoon here.

**Comment by terminalmage** [comment]
@damon-atkins no problem. I'm going to bed shortly and will pick this back up in about 8 hours or so. I'll work with Dave to get it tested (as I don't have a Windows box handy for that purpose) and by Saturday morning your time we should hopefully have something ready which you can review and test on your end to ensure it meets your satisfaction.

**Comment by terminalmage** [comment]
@damon-atkins I reverted the failhard default change and the commits I made because of it, and @UtahDave tested it and is happy with the results. The changes have been squashed down to a single commit, https://github.com/terminalmage/salt/commit/f237fe4d528efd621e1f9adbeb149695e94e65a1. Please take a look when you have a chance.

**Comment by damon-atkins** [comment]
Hi @UtahDave  & @terminalmage  I have reviewed the code changes from @terminalmage. I have added comments against  terminalmage@f237fe4   I will wait for @terminalmage to make changes based on my comments before testing.

**Comment by terminalmage** [comment]
@damon-atkins Thanks for the sanity check there, I made the needed changes, would you mind testing?

**Comment by terminalmage** [comment]
@damon-atkins just FYI the HEAD of that branch is now https://github.com/saltstack/terminalmage/commit/cc7f0d12, if you don't have my fork checked out then that's the revision you'd want to test.

**Comment by terminalmage** [comment]
Whoops, broken link. Here, just use https://github.com/terminalmage/salt/blob/update_to_35899_win_pkg/salt/modules/win_pkg.py, that page will show the head of the branch in my fork.

**Comment by terminalmage** [comment]
Ahh, you know what, I missed addressing one of your comments, let me take care of that and I'll update here when done. Sorry for the noise.

**Comment by terminalmage** [comment]
OK @damon-atkins, I addressed the commit I missed, see [here](https://github.com/terminalmage/salt/commit/f237fe4d528efd621e1f9adbeb149695e94e65a1#commitcomment-19120049) I'll wait to hear what you have to say about it.

**Comment by damon-atkins** [comment]
The workstation I use for testing is busy performing a task for a mate.  Should be tested by US Monday Morning.

**Comment by damon-atkins** [comment]
@twangboy  `get_name_map()`  what was the reason for making this public
in https://github.com/saltstack/salt/pull/26625  does it still need to remain public.

**Comment by twangboy** [comment]
@damon-atkins I don't think it needs to remain public. I probably did it so I could more easily see what I was getting in the name map. Probably forgot to put it back... or thought it may be useful.

**Comment by terminalmage** [comment]
OK, I made that function private again, and also made the last change that @damon-atkins mentioned. I also documented the two new parameters that @damon-atkins added to control whether or not the metadata is refreshed based on age.

I also squashed the changes again and force-pushed the changes to my fork. Once @damon-atkins has had the chance to test this early next week, and we know that no further changes need to be made, then I can submit a pull request to his fork to get my cleanup into this PR.

**Comment by damon-atkins** [comment]
Testing Almost Complete.   Looking Good So Far

**Comment by damon-atkins** [comment]
Here are the results of the testing all looking Good.

[salt-testing.bat.txt](https://github.com/saltstack/salt/files/492202/salt-testing.bat.txt)
[test.log.txt](https://github.com/saltstack/salt/files/492203/test.log.txt)

**Comment by terminalmage** [comment]
@damon-atkins OK, if you are satisfied then I can submit my changes as a pull request to your fork, and once merged my changes will show up in this PR and we can get it merged.

**Comment by damon-atkins** [comment]
Thats fine with me. Just need to line up @UtahDave to test as well.

**Comment by terminalmage** [comment]
OK, my changes have been submitted in https://github.com/damon-atkins/salt/pull/1.

**Comment by UtahDave** [comment]
This is working fine in the manual tests I've been doing

**Comment by UtahDave** [comment]
@damon-atkins if you can merge terminalmage's changes to your PR, I'll test again.

**Comment by damon-atkins** [comment]
@UtahDave What about the lint errors from @terminalmage changes.

**Comment by UtahDave** [comment]
I'll get them.  Thanks, @damon-atkins !

**Comment by terminalmage** [comment]
It looks like the lint errors did not make it in once merged.

**Comment by terminalmage** [comment]
Oh, I may not have pulled, checking again.

**Comment by terminalmage** [comment]
I did indeed forget to pull. PR incoming.

**Comment by terminalmage** [comment]
https://github.com/saltstack/salt/pull/36590 takes care of the lint and fixes a traceback that Dave found in his testing which occurs when an uninstaller does not properly clear the registry entries for the software.

**Comment by damon-atkins** [comment]
@meggiebot some items for release notes:
- get_name_map() removed as a public function, please use get_repo_data() instead which contains the same information and more.
- Fix: All platforms were performing additional refresh during a state run with pkg.installed
- New: Smart Management of the package metedata within win_pkg which includes, configuration items winrepo_cache_expire_max (6h) and winrepo_cache_expire_min (0s)
- Fix: General performance improvements to win_pkg

**Pull request merged**
