### PR TITLE
Tls add cert type option

### PR DESCRIPTION
**Pull request by gladiatr72**
From conversation w/ @quantonganh on the last series of commits, added cert_type and type_ext arguments to create_csr() and create_ca_signed_cert() to facilitate the ability to choose which set of common extensions to use.  Folded cert_type and type_ext into logic that @quantonganh committed wrt cert_filename.  If cert_filename is set it will override cert_type/type_ext

``` python
In create_csr():
  cert_type defaults to 'server'
  type_ext default to False
  if type_ext is True, append cert_type to the CN for the CSR filename format

In create_ca_signed_cert():
  cert_type defaults to None
  type_ext defaults to False
```

  If cert_type is set with create_csr(), it must be set for ccsc() to allow it to find the CSR
  If type_ext is True, cert_type is required to be set to reflect generated CSRs + appends cert_type to the CN for the filename format

  If cert_filename is set, it is used for the filename format.  In this context, type_ext is ignored.  cert_type must be set to reflect create_csr(cert_type) iaoi create_csr(type_ext) was set

### CODE REVIEW

**Comment by quantonganh** [comment]
@gladiatr72 : Should it be `cert_type`: https://github.com/saltstack/salt/blob/develop/salt/modules/tls.py#L929

**Comment by gladiatr72** [comment]
Indeed!

On Tue, May 19, 2015 at 10:07 PM, quantonganh <notifications@github.com>
wrote:

> @gladiatr72 <https://github.com/gladiatr72> : Should it be cert_type:
> https://github.com/saltstack/salt/blob/develop/salt/modules/tls.py#L929
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt/pull/23867#issuecomment-103737196>.
>



-- 
You know, I used to think it was awful that life was so unfair. Then I
thought, wouldn't it be much worse if life were fair, and all the terrible
things that happen to us come because we actually deserve them? So, now I
take great comfort in the general hostility and unfairness of the universe.

**Comment by terminalmage** [comment]
@gladiatr72 This pull request makes this module unusable on RHEL6. Please fix this, as RHEL6 only has pyOpenSSL 0.10. Please fix this.

**Comment by gladiatr72** [comment]
Does  upgrading  pyopenssl not work?  If you cannot do it because of policy, I'd suggest grabbing the tls  module from one of the 2014.7 releases and drop it in /srv/salt/_modules and sync it to your minions.  It will override the packaged version.

**Pull request merged**
