### PR TITLE
INFRA-1931 - support (present/absent) for hosted zones in states/boto_route53

### PR DESCRIPTION
**Pull request by tkwilliams**
New:
states/boto_route53
- hosted_zone_present()
- hosted_zone_absent()
- rr_present()  - alias for present()
- rr_absent()  - alias for absent()

modules/boto_route53
- describe_hosted_zones()
- list_all_zones_by_name()
- list_all_zones_by_id()
- create_hosted_zone()

Changed:
modules/boto_vpc
- describe()  - add 'region' as another interesting field to return.  Needed for route53 bits to work.
- describe_vpcs()  - ditto

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @tkwilliams 

Thanks for this! Could you please add some docs as recommended here? https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/3940/testReport/junit/integration.modules.sysmod/SysModuleTest/test_valid_docs/

Thanks.

**Comment by tkwilliams** [comment]
Howdy @cachedout 

You betcha!  Done, and done.

**Comment by tkwilliams** [comment]
Bah!  Looks like I broke a test-case too.
Fixed:
  test_that_when_describing_vpc_by_id_it_returns_the_dict_of_properties

**Comment by tkwilliams** [comment]
@cachedout  I think I've hooked up all the bits you mentioned -- anything else needed on this one? :)

**Comment by cachedout** [comment]
@tkwilliams Nope! Thanks!

**Pull request merged**
