### PR TITLE
setup.py: fix "invalid command name" error from distutils.dist for write-salt-ssh-packaging-file and write-salt-version

### PR DESCRIPTION
**Pull request by haim0n**
distutils.dist has a format for commands r'^[a-zA-Z]([a-zA-Z0-9_]*)$', this commit makes it happy for 'write-salt-ssh-packaging-file' and 'write-salt-version'

### CODE REVIEW

**Comment by s0undt3ch** [comment]
I've never stumbled on this before and at least the salt version one is there for a while now, and apparently working till today...

How did you trigger this?
Which version of Salt and which version on Python?

**Comment by haim0n** [comment]
pulled out the latest development branch
[hdaniel@hd-laptop salt (before_my_fix)]$ ./setup.py write-salt-version
2015.2.0-635-g33ce399
invalid command name 'write-salt-version'

Python 2.7.5 , FC 20

**Comment by s0undt3ch** [comment]
Ahh.. These are commands which are to be used internally, not directly from setup.py ...

K. I'll have a look if this change breaks anything, it shouldn't...


Thanks!

**Comment by thatch45** [comment]
Thanks @haim0n !

**Pull request merged**
