### PR TITLE
npm 5 and greater requires --force for cache clean

### PR DESCRIPTION
**Pull request by gtmanfred**
### What does this PR do?
This is the error

```
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and
data extracted from the cache is guaranteed to be valid. If you want to make
sure everything is consistent, use 'npm cache verify' instead.

npm ERR!
npm ERR! If you're sure you want to delete the entire cache, rerun this command
with --force.
```

### What issues does this PR fix or reference?
Fixes npm clean cache test (i don't think there is an issue)

### CODE REVIEW

**Comment by gtmanfred** [comment]
Go Go Jenkins

**Comment by gtmanfred** [comment]
Go Go Jenkins!

**Comment by garethgreenaway** [comment]
@gtmanfred Would including --force cause problems with older versions or has --force always been an available option?

**Comment by gtmanfred** [comment]
From what I have checked, it was in versions before 5.0 as well.

I checked 3.10.8 which is what is on our mac test vms.

**Comment by rallytime** [comment]
@gtmanfred Looks like there are some lint errors here.

**Comment by gtmanfred** [comment]
Yup, already updated to fix them.

**Review by rallytime — APPROVED** [review]

**Comment by dschaller** [comment]
For posterity I confirmed on npm@2.14.6 that the force flag exists as well

**Pull request merged**
