### PR TITLE
Add grains for the cloud metadata server

### PR DESCRIPTION
**Pull request by gtmanfred**
### What does this PR do?

This time we have a 1 second timeout so that the minion doesn't hang
forever on trying to connect.

### CODE REVIEW

**Comment by gtmanfred** [comment]
Is one second too long? I can drop it down to like .1 or something, I would think that this should respond relatively fast, because it should be in the same place as the gateway ip for the network is located.

Especially on openstack, the network node does a proxy to the metadata server, so it shouldn't ever be very far away.

**Comment by cachedout** [comment]
Here's the issue with this. Those grains are loaded on _every_ invocation of things like salt-call and at least once (sometimes more) on a state run. So, even 100ms is WAY too much overhead. That's a 30% increase over what salt-call should take under normal operation. If this absolutely, positively has to reach out to a network, that check needs to be behind a configuration option which is defaulted to False.

**Comment by gtmanfred** [comment]
Ok, sounds good.

**Comment by gtmanfred** [comment]
config option added, and also made sure that the docs would get rendered.

**Comment by cachedout** [comment]
Perfect! Thank you very much.

**Comment by twangboy** [comment]
@gtmanfred Is ``__salt__`` available when the minion starts? I'm seeing the following when I start the minion on Windows.
```
[ERROR   ] Exception raised when processing __virtual__ function for metadata. Module will not be loaded global name '__salt__' is not defined
Traceback (most recent call last):
  File "c:\salt-dev\salt\salt\loader.py", line 1587, in process_virtual
    virtual = getattr(mod, virtual_func)()
  File "c:\salt-dev\salt\salt\grains\metadata.py", line 33, in __virtual__
    if __salt__['config.get']('metadata_server_grains', False) is False:
NameError: global name '__salt__' is not defined
[WARNING ] salt.loaded.int.grains.metadata.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'metadata', please fix this.
```

**Comment by gtmanfred** [comment]
@twangboy this should be fixed in develop now :)

**Pull request merged**
