### PR TITLE
cron: make identifier default to state ID

### PR DESCRIPTION
**Pull request by anlutro**
Issue: #25958

### CODE REVIEW

**Comment by cachedout** [comment]
I broke the test suite for a second there. My bad. We'll re-test. :]

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by anlutro** [comment]
Looks like I missed some unit tests, I'll have a look

**Comment by anlutro** [comment]
One of the failing tests mention "aissue" 1072, but issue #1072 on github seems entirely unrelated. Any idea what that's referring to?

The other failing tests seem like legitimate failures, but I'm not sure if it's possible to work around them. I think it's possible to mitigate some of the "damage" this change might do to existing states without explicit identifiers, but not all of it.

**Comment by cachedout** [comment]
I don't have a problem with getting this into the 2015.5 branch but would like to see it well documented in the release notes. 

@anlutro Would you consider adding something to the release notes for 2015.5.4 and beryllium explaining the potential impacts of this change? Those docs can be found under `sat/docs/topics/releases'.

If they're documented as changes, I think the tests can then be changed to align with the new behaviour.

Sound good?

**Comment by anlutro** [comment]
I took the liberty to rewrite the existing tests to be more descriptive - some of the existing ones were quite noisy and unclear. Hopefully the tests show the current behavior more clearly. Ideas for more tests that can confirm the state behaves as it should would be welcome.

While I was working on this, I also found a bug in how the cron module handles multi-line comments, so I went ahead and fixed that.

I added a mention of the change in the release note file - not sure how elaborate I should be. Maybe a link to the issue/pull request would suffice?

**Comment by cachedout** [comment]
I think this is all very sensible. Looks great @anlutro! Thanks for your hard work here and for your patience with us getting this merged.

**Pull request merged**
