### PR TITLE
Clean up some bugs in the nova driver

### PR DESCRIPTION
**Pull request by gtmanfred**
I am pretty sure this will fix the following issues
#29758
#31115
#29666

Also, bring this one back inline with libcloud, which had all the ips in either private_ips or public_ips.

We were using special names for each network, which isn't necessary, cause we can just check all the ips.

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @gtmanfred 

There's just a small lint error to fix up: https://jenkins.saltstack.com/job/salt-pr-lint-n/13321/violations/

Thanks!

**Comment by gtmanfred** [comment]
Cool, I will get to it when I get into the office, had to get my eyes
checked this morning.

**Comment by cachedout** [comment]
@gtmanfred Super! Thanks for the quick fix here.

**Comment by cachedout** [comment]
Thanks, @gtmanfred

**Comment by gtmanfred** [comment]
@rallytime this will need to be merged forward to 2016.3 once 2016.3.0 is finalized

Thanks
Daniel

**Comment by rallytime** [comment]
@gtmanfred Sure thing.

**Pull request merged**
