### PR TITLE
Fix for broken /jobs/<jid> in 2016.11.4

### PR DESCRIPTION
**Pull request by senthilkumar-e**
### What does this PR do?
Fix for broken /jobs call in 2016.11.4

### What issues does this PR fix or reference?
#40845

### Previous Behavior
Returns 200. Now returning 500. 

### New Behavior
Returns 200

### Tests written?

No. Tested using API and salt-run

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by rallytime** [comment]
Thanks for fixing this @senthilkumar-e. There's a small pylint error. Would you mind fixing that really quickly?

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/10692/violations/file/salt/runner.py/

**Comment by jodv** [comment]
Given that this fixes a critical failure in the 2016.11.4 release, can we expect that 2016.11.5 will be cut promptly after this is merged?

**Review by whiteinge — APPROVED** [review]
Great. Thanks for the fix!

**Comment by cachedout** [comment]
@jodv I talked with @thatch45 about this last night and we're going to meet with the whole core team about it today. I'll get you an answer ASAP.

**Comment by PierreR** [comment]
And given the situation, adding a test case might be a good idea

**Comment by rvstaveren** [comment]
FYI, this also breaks rundeck installations using the saltstep plugin. having a test case would be cool.

```
Exception occurred in runner jobs.list_job: Traceback (most recent call last):\n  File \"/usr/local/lib/python2.7/site-packages/salt/client/mixins.py\", line 395, in _low\n    data['return'] = self.functions[fun](*args, **kwargs)\nTypeError: list_job() got an unexpected keyword argument '__current_eauth_groups'\n
```

**Comment by jodv** [comment]
Any update on cutting a fixed release?

**Comment by cachedout** [comment]
@jodv We have begun the process of cutting 2016.11.5 which will include this fix.

**Comment by jodv** [comment]
@cachedout Is there an ETA?  We're now approaching 2 weeks out from the fix being merged.

**Comment by cachedout** [comment]
The fix is already merged. We are working through the final QA process. We are hoping to do a tag today.

**Pull request merged**
