### PR TITLE
Issue-54224: Resolve yumpkg module dnf update error

### PR DESCRIPTION
**Pull request by dankolbrs**
### What does this PR do?

Add `--setopt` flag for `obsoletes=False` to resolve argument
error in DNF.

Update typo in doc string

### What issues does this PR fix or reference?

https://github.com/saltstack/salt/issues/54224

### Tests written?

~No~ _Yes_

### Commits signed with GPG?

No

### CODE REVIEW

**Review by dmurphy18 — CHANGES_REQUESTED** [review]
Thanks for the PR but Salt is now requiring tests to ensure the code changes function correctly.
This was recently introduced as a requirement (July 2019) in order to help with code stability in the drive to stabilize code/tests with releases and mitigate faster point releases.  For example: the issues in getting the first point release 2019.2.0 was seriously delayed due to lack of code/test stability, and with 2019.2.1 and subsequent releases trying to ensure this does not occur in the future.

**Comment by dankolbrs** [comment]
Added integration and unit test.

Pretty generic integration test, I'd be happy to change if there's an idea for a better approach on that one.

**Comment by dankolbrs** [comment]
The debian8 fail is https://github.com/saltstack/salt/issues/52894.

No idea on that windows one. I know there's a command to rerun a check, but couldn't find the needed syntax checking out recent PRs.

**Comment by waynew** [comment]
I think it only works for those on the core team - FWIW I just kicked them off again.

**Comment by dwoz** [comment]
@dankolbrs This needs to be re-opened against the `master` branch. We are no longer merging things to develop. Please link back to this PR on the one against master.

**Comment by sagetherage** [comment]
@cmcmarrow can you rebase this against master please?

**Comment by sagetherage** [comment]
closing as abandoned

**Pull request closed without merging**
