### PR TITLE
2019.2.1 with multimaster bb fixes

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
### What does this PR do?
Cherry-pick of #54239 into 2019.2.1 branch.

### CODE REVIEW

**Review by waynew — APPROVED** [review]

**Review by dwoz — APPROVED** [review]

**Review by Akm0d — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Comment by DmitryKuzmenko** [comment]
This got stuck for some reason after I've merged 2019.2.1 in command-line resolved conflicts. So I've tried to change the base branch and change it back. Now it looks okay. Let's wait for CI results.

**Comment by DmitryKuzmenko** [comment]
re-run full

**Comment by DmitryKuzmenko** [comment]
re-run full all

**Comment by DmitryKuzmenko** [comment]
The only alive failure is an unrelated known issue.
https://github.com/saltstack/salt/issues/53931

**Comment by shorawitz** [comment]
What is the workflow suggested with this change to handle multiple reactors executing the same thing targeting the same minion(s)?

**Pull request merged**
