### PR TITLE
Tomcat module fails to extract version number from snapshot builds #2…

### PR DESCRIPTION
**Pull request by egarbi**
This patch come form @nvx I have tested on my configuration and works. I really need this it is causing a big problem on our servers at this moment.
Issue #24520

### CODE REVIEW

**Comment by jfindlay** [comment]
@egarbi, thanks for the fix.  There are some test errors:
https://jenkins.saltstack.com/job/salt-pr-lint-n/6873/violations/file/salt/states/tomcat.py/
https://jenkins.saltstack.com/job/salt-pr-rs-ubuntu14.04-n/6436/testReport/junit/unit.states.tomcat_test/TomcatTestCase/test_war_deployed/

**Comment by egarbi** [comment]
Can anyone help me to pass this test errors?, I have no idea how to do it by myself

**Comment by jfindlay** [comment]
@egarbi, I'll look into it.

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by egarbi** [comment]
@jfindlay has a better PR for this one, thanks!!

**Pull request closed without merging**
