### PR TITLE
Always return a boolean in gen_locale()

### PR DESCRIPTION
**Pull request by F30**
`states.locale.present()` already expects a boolean return value, which is probably the cause of #21140.
Judging from #2417, there is no consensus on what modules should return. So I decided to adjust the module rather than the state and make it conistent within itself (`set_locale()` returns a boolean as well) and with the behavior an error (`False` is returned).

I'm not very familiar with your release process, but from my understanding this should also get backported.

### CODE REVIEW

**Comment by jfindlay** [comment]
@F30, thanks for the fix.  In the future, please feel free to submit fixes for issues to the oldest supported release branch affected by the issue, see http://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

**Comment by jfindlay** [comment]
The unit tests only exist on develop, but the change should probably go all the way back to 2014.7.

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
The code that this fix touches has been refactored since 2014.7. A separate fix will likely have to be made to that branch.

**Pull request merged**
