### PR TITLE
Added power cfg module and state for windows minions

### PR DESCRIPTION
**Pull request by opdude**
- Allows you to set power settings on a windows minion for things like the monitor and disk

### CODE REVIEW

**Comment by thatch45** [comment]
@jfindlay can you add the python3 absolute import and merge this in please?

**Comment by rallytime** [comment]
I grabbed it @jfindlay because I wanted to get the versionadded tags in there too.

Thanks @opdude!

**Comment by opdude** [comment]
@rallytime No problem, didn't know which version I should add it as :)

**Comment by rallytime** [comment]
@opdude No problem! Develop is currently on the Beryllium release, for future reference. That will be the case until we cut the next branch at some point down the line. We should probably get this documented somewhere, if it's not already. I've added a note to add that in #21270.

**Pull request merged**
