### PR TITLE
add more python libs info in '--versions-report'

### PR DESCRIPTION
**Pull request by TheBigBear**
OK, hopefully this one dosn't need rebasing. replaces closed one here https://github.com/saltstack/salt/pull/26666

### CODE REVIEW

**Comment by jfindlay** [comment]
@TheBigBear, there is a [lint error](https://jenkins.saltstack.com/job/salt-pr-lint-n/8798/violations/file/salt/version.py/).

**Comment by TheBigBear** [comment]
@jfindlay this lint thing is 'picky' ;-)

I have now removed the trailing space. Is there anything else I need to do on this? Or will it automatically resume form here?

**Comment by jfindlay** [comment]
@TheBigBear, should be fine, thanks.

**Comment by basepi** [comment]
Hrm, I'm not sure on this one. This seems like it will add a lot of clutter to the versions report, for libraries that a lot of people won't be using. I was under the impression we were limiting the versions report to the core deps of salt (including core deps of various transport options).

@cachedout, what are your thoughts here?

**Comment by cachedout** [comment]
@basepi I don't mind it. We include ioflo, for example, which is not a hard dependency.

**Comment by basepi** [comment]
Right, but it's a hard dep on one of our transport options.

Anyway, I'll merge this.

**Pull request merged**
