### PR TITLE
system: Update hardware clock on date/time change

### PR DESCRIPTION
**Pull request by harisokanovic**
Update hardware clock so that date/time changes persist
through reboot.

Add hwclock check to system integration test. Bump tolerance
of _same_times() helper to account for longer run-time of set
operations. Updating hardware rtc's can take more than 2 seconds.

Signed-off-by: Haris Okanovic <haris.okanovic@ni.com>
Reviewed-by: Sergey Kizunov <sergey.kizunov@ni.com>
Reviewed-by: Alejandro del Castillo <alejandro.delcastillo@ni.com>
Reviewed-by: Ioan-Adrian Ratiu <adrian.ratiu@ni.com>

### What does this PR do?
Update hardware clock on Linux in addition to software clock so the date/time changes will persist after reboot. Add test to verify hw clock is in sync with sw clock after date/time change.

### What issues does this PR fix or reference?
No salt issue number.

### Previous Behavior
Date/time changes don't persist after reboot.

### New Behavior
Now they do.

### Tests written?
Yes, system integration tests written and ran on x86 NILinuxRT VM.

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @harisokanovic 

This looks really good. Can you please address the lint errors here? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/8145/violations/

**Comment by harisokanovic** [comment]
Mike, I pushed a fix for lint and the Ubuntu issues to my dev branch, but I'm not sure how to re-run the CI. I tried closing and re-opening this PR, but that had no effect. Should I file a new PR or can you restart it?

**Comment by cachedout** [comment]
@harisokanovic It restarts each time a push is made. It can also be force-restarted via the phrase 'Go Go Jenkins!' in a Github comment. This looks fine though and I am going to go ahead and merge it. Thanks.

**Comment by harisokanovic** [comment]
Thanks Mike!

**Pull request merged**
