### PR TITLE
Merge forward from 2015.2 to develop

### PR DESCRIPTION
**Pull request by basepi**
Merge forward from 2015.2 to develop

```
Conflicts:
    salt/client/mixins.py
    salt/fileserver/gitfs.py
    salt/loader.py
    salt/renderers/pyobjects.py
    salt/utils/args.py
    salt/utils/decorators/__init__.py
    salt/utils/lazy.py
    tests/integration/loader/globals.py
    tests/integration/loader/loader.py
    salt/modules/iptables.py
```

### CODE REVIEW

**Comment by jfindlay** [comment]
@basepi, there are some lint errors.  I'm not sure where they're coming from as both branches should be lint free.

**Comment by jfindlay** [comment]
@basepi, I'll get those iptables test failures.

**Comment by basepi** [comment]
@jfindlay Thanks. I didn't think my resolution of iptables was going to be a problem, ah well.

**Comment by basepi** [comment]
Looking at lint now.

**Comment by jfindlay** [comment]
@basepi, no problem, your conflict resolution skills are excellent.  You should be a camp counselor.  It's because iptables was changed on 2015.2 and the tests on develop need to be updated accordingly.

**Pull request merged**
