### PR TITLE
Remove master caches if preserve_minions is false

### PR DESCRIPTION
**Pull request by pzipoy**
Signed-off-by: Perry Zipoy perry.zipoy@ni.com

### CODE REVIEW

**Comment by pzipoy** [comment]
@cachedout, are the default/jenkins test failures in this pull request caused by the files changed in this commit? After looking through the test logs, it looks like the failures may be caused by items other than this change.

**Comment by cachedout** [comment]
@pzipoy You are correct. Those are unrelated.

**Comment by pzipoy** [comment]
Great! Thanks, @cachedout

**Comment by junovitch** [comment]
I just opened #35840. This change in this PR impacts the check_minion_cache() logic and causes the 'preserve_minion_cache' configuration option to be ineffective on 2016.3+.  I'm trying to understand this.  What was the issue here?  This pull request doesn't mention an issue this addressed.  According to the documentation at https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html and the config file 'preserve_minion_cache' is the option used and that is respected by https://github.com/saltstack/salt/blob/2016.3/salt/key.py#L597.  It's also appears incomplete anyway as https://github.com/saltstack/salt/blob/2016.3/salt/key.py#L1331 is unchanged for the same function in RAET keys.

**Comment by pzipoy** [comment]
This pull request addressed a problem where "preserve_minions" had no effect when passed to the salt/key.py delete_key method. This would cause the minion cache to remain on the master when preserve_minions was false (the default value), which is contrary to the comment in the code, "To preserve the master caches of minions who are matched, set preserve_minions". In which case, preserve_minions didn't appear to have an effect when passed to delete_key, which is a bug. If this pull request is reverted, then there would need to be a mechanism in place to ensure the minion cache on the master is removed as expected when the minion's key is deleted and preserve_minions is false.

**Comment by junovitch** [comment]
What is the behavior that would be ideal here?  Ping @cachedout as the original committer of https://github.com/saltstack/salt/commit/bf81871b2cf4f0a67a460c3a62b7166f5be1054d.  If the user is using the delete_key() from key.py directly and specifies True/False, do we want that to have precedence over the configuration retrieved by `self.opts.get('preserve_minion_cache', False)`?

If yes and we want the explicit delete_key flag to have precedence, we need to correct the comment at https://github.com/saltstack/salt/blob/2016.3/salt/key.py#L586 and fix the logic to match.

If no and we want the config option to have precedence, we need to correct the comment https://github.com/saltstack/salt/blob/2016.3/salt/key.py#L841 and fix the logic to match.

Currently the comments in the code at the referenced line numbers are contradictory and both cannot be satisfied.

**Pull request merged**
