### PR TITLE
feat(http_pillar): added kwargs to handle extra option for http.query

### LINKED ISSUE #36138: Authorization support required in ext_pillar http_json modules.
**salt**['http.query'] function support lots of parameters via utils/http.py.
However, only 'url' parameter supported in salt/salt/pillar/http_json.py now.
Could we add support for other parameters such as header_dict so that we can do some authorization stuff by:

```
  ext_pillar:
    - http_json:
        url: http://example.com/api/minion_id
        header_dict: {foo: bar}
        key_foo: value_bar
```

### PR DESCRIPTION
**Pull request by martintamare**
### What does this PR do?
Add the hability to pass extra parameters to http_* ext_pillar
For example, add auth, or headers

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/36138

### CODE REVIEW

**Comment by MKLeb** [comment]
Hi @martintamare, would you be able to add a [changelog entry](https://docs.saltproject.io/en/latest/topics/development/contributing.html#changelog-and-commit) and relevant [tests](https://docs.saltproject.io/en/latest/topics/tutorials/writing_tests.html)?  Also, it seems that the pre-commit hook "black" has failed, could you run that against your changes?
`pre-commit run black --files <filename>`

Looks good so far, but requesting a review from @garethgreenaway for a second opinion.

**Comment by martintamare** [comment]
> Hi @martintamare, would you be able to add a [changelog entry](https://docs.saltproject.io/en/latest/topics/development/contributing.html#changelog-and-commit) and relevant [tests](https://docs.saltproject.io/en/latest/topics/tutorials/writing_tests.html)? Also, it seems that the pre-commit hook "black" has failed, could you run that against your changes? `pre-commit run black --files <filename>`
> 
> Looks good so far, but requesting a review from @garethgreenaway for a second opinion.

I've added the changelog entry, but as no tests are present for those modules, i'm not confident to add new tests ;)

**Comment by martintamare** [comment]
Is there anyone that can review this ? 🙏

**Comment by MKLeb** [comment]
@martintamare are you able to merge in the latest master branch changes?

**Comment by martintamare** [comment]
Yes of course, doing !

**Comment by martintamare** [comment]
Done @MKLeb

**Comment by MKLeb** [comment]
I'm going to try to write tests for this and we can attempt to get this merged soon.

**Comment by martintamare** [comment]
@MKLeb I can help, but starting tests from scratch is way more work that I can provided.
If you wrote a skeleton I can work from that.
Cheers

**Comment by MKLeb** [comment]
@martintamare, it seems I don't have write access to your branch, so I'll paste the skeleton I wrote here...

This is a new file, `tests/pytests/unit/pillar/test_http_json_pillar.py`
```
import pytest
import salt.utils.json
from salt.modules import http
from salt.pillar import http_json


@pytest.fixture
def configure_loader_modules():
    return {
        http_json: {
            "__salt__": {
                "http.query": http.query,
            },
        },
        http: {
            "__opts__": {},
        },
    }


@pytest.mark.requires_network
@pytest.mark.parametrize("backend", ["requests", "tornado", "urllib2"])
def test_ext_pillar_can_take_http_query_kwargs(backend, httpserver):
    response = {
        "dict": {
            "backend": backend,
            "pillar_type": "http_json",
        },
    }
    header_dict = {"custom-backend-header": backend}

    # If the headers in header_dict are not in the request, httpserver will return an empty dictionary, so we know it will fail
    httpserver.expect_request(
        "/http_json_pillar/{}".format(backend),
        headers={"custom-backend-header": backend},
    ).respond_with_data(salt.utils.json.dumps(response), content_type="text/plain")
    url = httpserver.url_for("/http_json_pillar/{}".format(backend))

    actual = http_json.ext_pillar("test-minion-id", {}, url, header_dict=header_dict)
    assert actual == response
```

This is the test I wrote for `pillar/http_json.py`.  It should be enough for that change, and all you would have to do is create a similar test in another new file `tests/pytests/unit/pillar/test_http_yaml_pillar.py` to test `pillar/http_yaml.py`.  You can add other unit tests if you'd like, but this will likely be enough to get this merged in.

A few things to note here.

The pytest docs are [here](https://docs.pytest.org/en/6.2.x/contents.html).  They're actually pretty decent.

The special pytest fixture `configure_loader_modules` is how we inject functionality into the dunders normally available in salt for our unit tests since they are not naturally loaded and injected for the unit test suite.

You'll see the `httpserver` fixture being used here.  This is from `pytest-httpserver`, and all it does is stand up a simple HTTP server for use in our tests to avoid reaching out to the internet. The (subpar) docs for this are [here](https://pytest-httpserver.readthedocs.io/en/latest/howto.html).

**Comment by martintamare** [comment]
Hi there, i'm trying to run test local but I did push.
I also see this issue https://github.com/saltstack/salt/pull/55325 which is totally related ;)

**Comment by martintamare** [comment]
Frankly, running tests on a dev platform is very hard for a non salt-dev.

I'm a venv (OK so far)
I run all the commands

python -m nox -e "pytest-3.7(coverage=False)" -- tests/pytests/unit/pillar/test_http_json_pillar.py

I have a success but with some errors.
The overhead is heavy when you are use to run a simple pytest ...

Just my frustrated opinion ;)

**Comment by MKLeb** [comment]
> Frankly, running tests on a dev platform is very hard for a non salt-dev.
> 
> I'm a venv (OK so far) I run all the commands
> 
> python -m nox -e "pytest-3.7(coverage=False)" -- tests/pytests/unit/pillar/test_http_json_pillar.py
> 
> I have a success but with some errors. The overhead is heavy when you are use to run a simple pytest ...
> 
> Just my frustrated opinion ;)

I ran your test file locally and it passed.  What are the errors you are getting?

Also, I know we are only testing headers being passed, but we may want to make sure we are returning yaml as the http response.  I mocked it up here locally, and it looks like we can just remove the `import salt.utils.json` and use the following as the test...

```
@pytest.mark.requires_network
@pytest.mark.parametrize("backend", ["requests", "tornado", "urllib2"])
def test_ext_pillar_can_take_http_query_kwargs(backend, httpserver):
    response = """
    dict:
      backend: {}
      pillar_type: http_yaml
    """.format(backend)

    expected = {
        "dict": {
            "backend": backend,
            "pillar_type": "http_yaml",
        },
    }

    header_dict = {"custom-backend-header": backend}

    # If the headers in header_dict are not in the request, httpserver will return an empty dictionary, so we know it will fail
    httpserver.expect_request(
        "/http_yaml_pillar/{}".format(backend),
        headers={"custom-backend-header": backend},
    ).respond_with_data(response, content_type="text/plain")
    url = httpserver.url_for("/http_yaml_pillar/{}".format(backend))

    actual = http_yaml.ext_pillar("test-minion-id", {}, url, header_dict=header_dict)
    assert actual == expected
``` 

Also, if you remove the `.. autofunction` lines in both of your modified files that should stop the docs check from failing.

**Comment by MKLeb** [comment]
Closing this because I ported it to https://github.com/saltstack/salt/pull/62788 to make the necessary fixes

**Pull request closed without merging**
