### PR TITLE
fix salt/modules/aptpkg.py in case HAS_APT=False

### PR DESCRIPTION
**Pull request by sakateka**
### What does this PR do?
Adds reliability in the process of parsing sources.lists

### What issues does this PR fix or reference?
Fixes: -

### Previous Behavior
`aptpkg.py` failed to parse strings with arbitrary comments in case HAS_APT=False
For example, it cannot parse empty string comments `# `

### New Behavior
Added additional checks to handle arbitrary comments in sources.list

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**
I tried to set up a test environment according to the instructions...
But I cannot run `nox` in `pyenv`, it is crashed with `Segmentation fault (core dumped)` :-(

- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by sakateka** [comment]
@waynew PTAL

**Comment by sakateka** [comment]
@waynew Are there any chances to confirm this?

**Comment by sakateka** [comment]
@Ch3LL Can you help with merging this fix?

**Review by Ch3LL — CHANGES_REQUESTED** [review]
This will need a changelog (https://docs.saltproject.io/en/latest/topics/development/changelog.html) and test coverage then I will give the fix a thorough review. Thanks for the fix btw :)

**Comment by sakateka** [comment]
@Ch3LL please take a look.

**Comment by sakateka** [comment]
@Ch3LL I have completed all the change requests, can we continue here now?

**Comment by Ch3LL** [comment]
There is a merge conflict that will need to be resolved and then I can review and we can get this in

**Comment by sakateka** [comment]
> There is a merge conflict that will need to be resolved and then I can review and we can get this in

I fixed them.

**Comment by sakateka** [comment]
re-run all full

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
