### PR TITLE
New execution module: napalm_users

### PR DESCRIPTION
**Pull request by mirceaulinic**
### What does this PR do?

Introducing a new execution module to handle the configuration of the users on network devices.

### CODE REVIEW

**Comment by cachedout** [comment]
@mirceaulinic Could you please rebase this? There is a merge conflict.

**Comment by mirceaulinic** [comment]
@cachedout I will rebase after merging https://github.com/saltstack/salt/pull/37372 as will cause the conflict again

**Comment by cachedout** [comment]
@mirceaulinic You should be safe to go ahead and rebase this now. Thanks!

**Comment by mirceaulinic** [comment]
Okay... done @cachedout. Way to go! :)

**Comment by cachedout** [comment]
Looks great! Thanks so much, @mirceaulinic

**Pull request merged**
