### PR TITLE
fixes issue in which s3.role_arn was defaulting to empty string

### PR DESCRIPTION
**Pull request by timcharper**
Resolves issue #30899

### CODE REVIEW

**Comment by timcharper** [comment]
I tested the change with role assumption and without role assumption on an AWS instance with an assigned role.

I'm noticing that role assumption isn't working if credentials are provided, which is a bit surprising. I'll send another pull request up for that soon.

**Comment by cachedout** [comment]
@timcharper There are some small lint fixes necessary here. Could you please take a look? Once that's done, will give this a review and hopefully get it in. Thanks!

**Comment by timcharper** [comment]
Sure thing. Those lint errors always get me and I should learn how to run it locally.

**Comment by cachedout** [comment]
@timcharper There's a bit on running pylint locally here, if you need it: https://docs.saltstack.com/en/latest/topics/development/conventions/style.html

**Comment by cachedout** [comment]
Hi @timcharper . Let me know if you have time to get this lint error fixed up. If not, I can take care of it, no problem. Thanks!

**Comment by timcharper** [comment]
@cachedout so sorry, it's been a crazy couple of days and I feel bad that I was so unresponsive. Thank you for getting this merged.

**Pull request merged**
