### PR TITLE
Adding the ability to specify requisites without a state module name

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Adding the ability to specify requisites without a state module name.

### What issues does this PR fix or reference?
#44446 

### Previous Behavior
Requisites such as prereq, listen, onfail, etc. required the state module to be included.

### New Behavior
If the state module is not specified then we search for the appropriate state by `id` or `name`.

### Tests written?
Yes

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by thatch45 — APPROVED** [review]

**Comment by thatch45** [comment]
For the record, I am ok with cyclomatic complexity in the state compiler and runtime, given the nature out the recursive data traversal I see this as being very difficult, if not impractical to completely avoid.

**Comment by rallytime** [comment]
re-run py3

**Comment by garethgreenaway** [comment]
re-run py3

**Review by cachedout — APPROVED** [review]
Exceedingly well-done.

**Comment by thatch45** [comment]
Yes, it is so well done and a great and elegant addition to the state system that it gets an AWESOME label

**Pull request merged**
