### PR TITLE
Add HAS_REQUIRED_CRYPTO var for m2crypto in joyent

### PR DESCRIPTION
**Pull request by Ch3LL**
### What does this PR do?
The variable `HAS_REQUIRED_CRYPTO` was missing if m2crypto was importable and the joyent cloud was not loading. Now that the variable is loaded the skipIf check in the `unit.cloud.clouds.test_joyent` test does not fail anymore and the test passes

### What issues does this PR fix or reference?
Fixes https://github.com/saltstack/salt/issues/53067

### Previous Behavior
The test `unit.cloud.clouds.test_joyent` was failing on m2crypto with:

```
Failed to import test module: unit.cloud.clouds.test_joyent Traceback (most recent call last):   File "/usr/lib64/python2.7/unittest/loader.py", line 252, in _find_tests     module = self._get_module_from_name(name)   File "/usr/lib64/python2.7/unittest/loader.py", line 230, in _get_module_from_name     __import__(name)   File "/tmp/kitchen/testing/tests/unit/cloud/clouds/test_joyent.py", line 38, in <module>     @skipIf(joyent.HAS_REQUIRED_CRYPTO is False, reason='PyCrypto or Cryptodome not installed') AttributeError: 'module' object has no attribute 'HAS_REQUIRED_CRYPTO' 
```

### New Behavior

```
[root@ip-10-27-30-248 ~]# python2.7 /tmp/kitchen/testing/tests/runtests.py -n unit.cloud.clouds.test_joyent
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Python Version: 2.7.5 (default, Apr 9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
 * Transplanting configuration files to '/tmp/salt-tests-tmpdir/config'
 * Current Directory: /tmp/kitchen/testing
 * Test suite is running under PID 15587
 * Logging tests on /tmp/salt-runtests.log
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Starting unit.cloud.clouds.test_joyent Tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
----------------------------------------------------------------------
Ran 3 tests in 0.006s

OK

===============================================================  Overall Tests Report  ================================================================
***  No Problems Found While Running Tests  ***********************************************************************************************************
=======================================================================================================================================================
OK (total=3, skipped=0, passed=3, failures=0, errors=0) 
===============================================================  Overall Tests Report  ================================================================
```

### Tests written?

No - Fixes failing test

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by s0undt3ch** [comment]
And the other cloud drivers which also try to import m2crypto?

**Review by s0undt3ch — APPROVED** [review]

**Comment by Ch3LL** [comment]
I'm not seeing any other clouds that are using `HAS_REQUIRED_CRYPTO` just joyent. The other clouds tend to only use the `HAS_M2`, `HAS_P2CRYPTO` only.

**Comment by s0undt3ch** [comment]
My bad then, sorry :)

**Comment by Ch3LL** [comment]
no worries, always better to check :)

**Pull request merged**
