### PR TITLE
add pkgrepo.absent keyid and keyid_ppa arguments

### PR DESCRIPTION
**Pull request by favadi**
I add the ability to remove keyid for pkgrepo.absent.

### CODE REVIEW

**Comment by jfindlay** [comment]
@favadi, thanks for the pull request.  We try to keep the `pkg` and `pkgrepo` execution modules and states implementation agnostic, so we will probably want this code to go into an apt-specific state.

**Comment by favadi** [comment]
@jfindlay you means move this code to [apt state](https://github.com/saltstack/salt/blob/develop/salt/states/apt.py)?

**Comment by jfindlay** [comment]
@favadi, I do not know specifically how package repo-specific states should be handled.  @whiteinge or @terminalmage may have some ideas on the subject.

**Comment by terminalmage** [comment]
@jfindlay I really haven't done much with pkgrepo states, and I'm not a Debian/Ubuntu guy so I'm not sure what this code is supposed to be doing. That said, we should not be putting platform-specific code into states. The way we should handle this is to pass the platform specific options to the ``pkg.del_repo`` function, and raise exceptions if the action failed. Those exceptions can be caught in the state and used to build the comment field in the error that is returned.

**Comment by terminalmage** [comment]
I think I know a good way to modify this code and get the desired effect. Hold off on merging.

**Comment by favadi** [comment]
On 04/21/2015 10:37 AM, Erik Johnson wrote:
> The way we should handle this is to pass the platform specific
> options to the ``pkg.del_repo`` function, and raise exceptions if the
> action failed.

That's better. I will move the code to `pkg.del_repo` module.

**Comment by favadi** [comment]
Close this PR in favor of #22886.

**Pull request closed without merging**
