### PR TITLE
Replace all check_or_die to __virtual__

### PR DESCRIPTION
**Pull request by rominf**
In some modules `check_or_die` functions are used in all functions.
I replaced it with `__virtual__`.

### CODE REVIEW

**Comment by cachedout** [comment]
@rominf This has some merge conflicts. Could you please rebase it and update your PR? Thanks.

**Comment by jfindlay** [comment]
@rominf, did you mean to also include the fish config changes as well?  It should be fine, I am only making sure you are aware of this.

**Comment by rominf** [comment]
Well, I'm in the process of rebasing. Some commits from my other branches (I'll PR them later) accidentally came with this PR.

Can you please wait for some time?

**Comment by cachedout** [comment]
@rominf No hurry. Just making sure you were aware. Just let me know when this is ready to go. Thanks.

**Comment by lorengordon** [comment]
This would be a fantastic time to update the return in __virtual__ for all these modules to say *why* the module isn't being loaded, rather than just return False...

https://docs.saltstack.com/en/latest/ref/modules/index.html#returning-error-information-from-virtual

**Comment by rominf** [comment]
@lorengordon, thank you for your input. I didn't know about it, will fix it now.

**Comment by lorengordon** [comment]
@rominf, heh, I didn't know about it until recently. I learned about it after [opening an issue](https://github.com/saltstack/salt/issues/26755) asking for the ability to link requirements to modules to improve error reporting... The docs have been updated lately to make the capability more clear (thanks @jfindlay!).

**Comment by rominf** [comment]
It seems to me, that everything is OK. Tests are broken, but not by my commits.

Can you please merge it?

**Comment by cachedout** [comment]
Looks good. Thanks, @rominf

**Pull request merged**
