### PR TITLE
Fixes for git.latest, git module integration tests, etc.

### PR DESCRIPTION
**Pull request by terminalmage**
- Fix an oversight with the tests where the global user.name and user.email
  parameters were being set in the setUp routine even when they already exist,
  stomping on the ~/.gitconfig of whomever was running the test.
- Fix how git.latest handles non-fast-forward merges, as well as checking out a
  new branch when the current branch has uncommitted changes.
- Add 2 arguments to the git.fetch function.
- Deprecate the always_fetch argument from git.latest, as the logic for
  detecting when a fetch is necessary is now much more robust.
- Properly handle short-SHA1 revs

### CODE REVIEW

**Comment by terminalmage** [comment]
And I have one more fix to make, short-SHA1s don't work properly in the rev param.

**Comment by terminalmage** [comment]
OK, that is fixed too now.

**Comment by UtahDave** [comment]
Thanks, terminalmage!

**Comment by anlutro** [comment]
@terminalmage Commit 2a6c4a7 has caused my git states to stop working. Example simple state:

```
/var/www/satis:
  git.latest:
    - name: https://github.com/composer/satis
    - target: /var/www/satis
    - force: true
    - user: www-admin
```

**Comment by anlutro** [comment]
Adding an `remote_rev != 'HEAD'` to the if statement that triggers the `_fail` call prevents the error, but the git repository isn't being updated to the latest version.

**Comment by anlutro** [comment]
I give up trying to read this huge function - I think `remote_rev` needs to default to `remote + '/HEAD'` instead of just `'HEAD'`, but I can't figure out why no checkout is being done.

As a temporary workaround I'm going to specify the branch as the rev in my states, but I hope it doesn't have to stay that way.

**Comment by terminalmage** [comment]
@anlutro Can you be a bit more specific than "stop working"? Are you getting an error message?

**Comment by anlutro** [comment]
@terminalmage yeah, sorry. I get "Failed to update repository" as a comment to the failed state. Triggered by the `_fail` call near the "Shouldn't get here" comment.

**Comment by terminalmage** [comment]
OK cool, that helps. Sorry for the inconvenience!

**Comment by terminalmage** [comment]
@anlutro I have found the issue and am working on a fix, I will @ mention you in the new pull request so that you have the opportunity to test with my updated code. Thanks again for bringing this up.

**Comment by anlutro** [comment]
Happy to help if I can!

**Comment by terminalmage** [comment]
Cool. Just FYI, you can actually check out Github pull requests into local branches, like so:

```
git fetch upstream "pull/<pr_number>/head:pr-<pr_number>"
git checkout pr-<pr_number>
```

This assumes you have the main saltstack/salt repository configured as a git remote named "upstream", replace "upstream" with whatever you're using if that is not the case.

**Pull request merged**
