### PR TITLE
Napalm library based proxy minion

### PR DESCRIPTION
**Pull request by jejenone**
This is a proxy minion working with Napalm library (https://github.com/napalm-automation/napalm)
This allows to manage network devices currently supported by Napalm: Juniper, Cisco, Arista, etc.
We provide a limited module to retrieve:
- CLI outputs
- MAC address table
- ARP table
- LLDP neighbors

### CODE REVIEW

**Comment by cachedout** [comment]
Looks great. We do have a lint error that needs to be cleaned up here before we can merge this. Please let me know when a fix has been pushed for that.

I am also going to ask @cro to take a look here, since he's the original author of the proxy-minion system.

**Comment by jejenone** [comment]
I can't see the lint error - it says "no identified error" here: https://jenkins.saltstack.com/job/salt-pr-lint-n/13692/

**Comment by cro** [comment]
@jejenone This is a great addition, thanks so much for contributing!

Try this for the lint error:

https://jenkins.saltstack.com/job/salt-pr-lint-n/13692/violations/file/salt/modules/napalm_network.py/

It's trailing whitespace.

**Comment by jejenone** [comment]
@cro weird I thought I had removed the spaces but there was one left.
Anyway, fixed. Thanks!

**Pull request merged**
