### PR TITLE
Include Parrot in grains _OS_Family_Map

### LINKED ISSUE #60249: [BUG] Cannot use pkg (and other modules?) with Parrot minions
**Description**
Some salt calls work with Parrot minions.
Attempt to use states using `pkg` fail:
```
Comment: State 'pkg.installed' was not found in SLS 'update'
Reason: 'pkg' __virtual__ returned False
```
**Setup**
Attempt to update Parrot with `pkg.uptodate`

**Steps to Reproduce the behavior**
Basic salt call to `pkg.uptodate` (or any use of `pkg`)

**Expected behavior**
Call will succeed and packages will be updated as necessary

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3002.5
 
Dependency Versions:
                cffi: 1.14.5
      cherrypy: 8.9.1
        dateutil: 2.8.1
    docker-py: Not Installed
            gitdb: Not Installed
     gitpython: Not Installed
          Jinja2: 2.11.3
         libgit2: Not Installed
    M2Crypto: Not Installed
           Mako: 1.1.3
      msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: 1.4.4
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: Not Installed
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
        dist: parrot 4.11 unknown.new.testing
        locale: utf-8
       machine: x86_64
       release: 5.4.98-1.fc25.qubes.x86_64
       system: Linux
       version: Parrot OS 4.11 unknown.new.testing
```
</details>

**Additional context**
`grains.items` shows `os_family:  Parrot`
Parrot is not referenced in `grains\core.py`.

Adding Parrot under `_OS_Family_Map` resolves the issue.

### PR DESCRIPTION
**Pull request by unman**
### What does this PR do?
Adds Parrot to OS_Family_Map in grains
### What issues does this PR fix or reference?
Fixes: #60249

### Previous Behavior
Could not use modules that referenced family

### New Behavior
Fixed

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by evelikov** [comment]
Parrot has a good [os-release file](https://github.com/ParrotSec/base-files/blob/master/etc/os-release) so this PR will be effectively superseded by my PR - parse os-release ID_LIKE token https://github.com/saltstack/salt/pull/60171. That is assuming upstream is happy to merge it :-)

**Comment by unman** [comment]
On Tue, Jun 01, 2021 at 03:30:34AM -0700, Emil Velikov wrote:
> Parrot has a good [os-release file](https://github.com/ParrotSec/base-files/blob/master/etc/os-release) so this PR will be effectively superseded by my PR - parse os-release ID_LIKE token https://github.com/saltstack/salt/pull/60171. That is assuming upstream is happy to merge it :-)
> 

Nice. But yours is more substantive, and parses an optional field,
and mine is trivial.

**Comment by evelikov** [comment]
Indeed, stacking workarounds tends to be easier than fixing things properly.

**Comment by sagetherage** [comment]
@evelikov can you please add a changelog file for this additional Debian-based OS?

**Comment by unman** [comment]
On Tue, Jun 01, 2021 at 09:19:49AM -0700, Emil Velikov wrote:
> Indeed, stacking workarounds tends to be easier than fixing things properly.
> 

It's not a workaround.
It is the current tested mechanism.
I have no idea how widespread "decent" os-release files are: nor do you.

**Review by garethgreenaway — DISMISSED** [review]

**Review by Ch3LL — CHANGES_REQUESTED** [review]
Can we also get a test added similar to https://github.com/saltstack/salt/pull/59177/files#diff-a31d52f107f2aba1214af30f17846b083d8a8ef58c4cdc76ae889f716a8df1a0R681

**Review by bryceml — DISMISSED** [review]

**Review by s0undt3ch — DISMISSED** [review]

**Comment by garethgreenaway** [comment]
@unman Let us know if you need help writing a test for the change.

**Comment by unman** [comment]
> Can we also get a test added similar to https://github.com/saltstack/salt/pull/59177/files#diff-a31d52f107f2aba1214af30f17846b083d8a8ef58c4cdc76ae889f716a8df1a0R681

Added a test (after the typo fixed) - good for you @Ch3LL ?

**Comment by Ch3LL** [comment]
@unman looks like there are some test failures that need to be cleaned up and a merge conflict. Also thanks for adding the test :)

**Comment by unman** [comment]
On Thu, Jul 29, 2021 at 09:48:35AM -0700, Megan Wilhite wrote:
> @unman looks like there are some test failures that need to be cleaned up and a merge conflict. Also thanks for adding the test :)
> 

I'll take a look

**Review by Ch3LL — DISMISSED** [review]

**Comment by Ch3LL** [comment]
@unman are willing to come back to this PR and fix up the tests?

**Comment by unman** [comment]
Thanks for the reminder.

**Review by Ch3LL — DISMISSED** [review]

**Review by twangboy — APPROVED** [review]

**Pull request merged**
