### PR TITLE
51501 states boto3 route53.py fails to validate alias a records

### PR DESCRIPTION
**Pull request by martin-paulus**
### What does this PR do?

Enable boto3_route53 state to correctly handle ALIAS (A-record) validation.

### What issues does this PR fix or reference?

51501

### Previous Behavior

Previously, boto3_route53.rr_present would crash on validating an existing ALIAS record.

### New Behavior

Now, boto3_route53.rr_present is able to correctly create, update, validate ALIAS records.

### Tests written?

No

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by dwoz — APPROVED** [review]

**Comment by anitakrueger** [comment]
@dwoz Is this going to be merged into 2019.2 as well by any chance? We are managing lots of ALIAS records with this state and it creates them over and over again because they are not correctly validated at the moment.

**Comment by martin-paulus** [comment]
@anitakrueger (and visitors:) The changes in this PR are present in 2019.2: https://github.com/saltstack/salt/blob/779bc179e25be49d3449a56648bf827bcb6d5fb6/salt/states/boto3_route53.py#L637

**Comment by anitakrueger** [comment]
@martin-paulus Unfortunately I don't see this working in 2019.2.2.
I just ran the state that should ensure one of our alias records is present for an ALB, and it got created again despite already being there. Running with test=True also says "Route 53 resource record XYZ with type A would be added."

Should I open another issue and if so, what details would be needed please?

**Comment by martin-paulus** [comment]
@anitakrueger Yes, I suppose opening another issue is the way to go. But could you just confirm if the salt/states/boto3_route53.py file in your installation contains the code in this PR? (near lines 637-693)

If the code is there, then it is definitely a different issue you are experiencing. In that case there is no need to refer to this PR or continue the discussion here.

Thank you!

**Comment by anitakrueger** [comment]
@martin-paulus Yes, the code is definitely in there.
I'm wondering how this was tested then? And if this code isn't entirely working, I would think referencing this case would actually be helpful.
I'll try to open a new issue tonight.

**Pull request merged**
