### PR TITLE
Datadog events api

### PR DESCRIPTION
**Pull request by onlyanegg**
### What does this PR do?
This pull request adds a function to the datadog api module for datadog's event api

### Tests written?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by onlyanegg** [comment]
Hey, @cachedout. Could you help me with these errors? It looks like maybe the details of the failures are no longer available.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@onlyanegg Yes, I have restarted the tests. When they finish I will have a look. Thanks!

**Comment by onlyanegg** [comment]
Thanks!

**Review by cachedout — APPROVED** [review]

**Comment by cachedout** [comment]
Hi @onlyanegg. This is great! I've merged this in. Thanks very much for your help!

**Comment by onlyanegg** [comment]
Thanks, @cachedout!

**Pull request merged**
