### PR TITLE
git.latest: Fix regression with identity file usage

### PR DESCRIPTION
**Pull request by terminalmage**
Unit test included.

Fixes https://github.com/saltstack/salt/issues/46018.

### CODE REVIEW

**Comment by twangboy** [comment]
@rallytime You'll probably need to bring this PR in too: https://github.com/saltstack/salt/pull/45511 for Windows

**Comment by terminalmage** [comment]
@twangboy that change you're referring to was already included in this PR, see here: https://github.com/saltstack/salt/pull/46036/files#diff-59a19c9338fb59c2d90efccd4a0d618fR182

I moved the check for the ssh.exe into a helper function to make unit testing on non-Windows platforms possible.

**Comment by terminalmage** [comment]
Oh I see, you're referring to the batch file changes as well?

**Comment by twangboy** [comment]
@terminalmage Yes, but there are also the changes to `build_pkg.bat` that makes sure the `ssh.py` module makes it into the build, otherwise, this will fail on packaged windows.

**Comment by twangboy** [comment]
@rallytime Verified this fix on Windows. Looks good.

**Review by twangboy — APPROVED** [review]

**Review by rallytime — APPROVED** [review]

**Pull request merged**
