### PR TITLE
Mkey cli

### PR DESCRIPTION
**Pull request by thatch45**
Add the multi key subsystem to enable the management of multiple types of keys

### CODE REVIEW

**Comment by thatch45** [comment]
@jacksontj another piece needed to make adding more transports seamless so that salt-key can function with multiple differing key/cert management backends

**Comment by jacksontj** [comment]
This appears to use the same PKI dir for both keys. IIRC they aren't
compatible keys, so we probably want a different dir per key type.

**Comment by thatch45** [comment]
It uses the same top level PKI dir, but the lower level dirs are still defined int he Key classes for the raet and zmq keys

**Comment by thatch45** [comment]
so the dirs in question are different for each transport type

**Comment by jacksontj** [comment]
That seems a bit messy to me, if we end up moving to a third transport some time in the future that means we will have 4^3 directories in pki_dir. I think it might be better to take this opportunity to namespace the pki_dir and have top level directories for the key types (rsa, ec/nacl, etc.) then we could also share a lot of the key code since at the end of the day its primarily checking if a file exists and letting some other class do the crypto

**Comment by thatch45** [comment]
I think you are missing the point here, the dirs are defined lower down in the Key class. I agree that we don't want them all in the top level pki dir, but all we have to do is define the ACC etc values in the Key classes to be in subdirs and we are done.

**Comment by thatch45** [comment]
The other problem we would need to handle would be to automate the movement of the keys, such that the upgrade would be transparent

**Comment by jacksontj** [comment]
Great thats an easy way to implement it. My other point was that there at least seems to be a lot of duplication between these classes, maybe it would be useful to create a base "key" class and separate "aeskey" and "eckey" or something that inherit?

For example the "finger_all" function looks identical:

```
--
    def finger_all(self):
        '''
        Return fingerprins for all keys
        '''
        ret = {}
        for status, keys in self.list_keys().items():
            ret[status] = {}
            for key in keys:
                if status == 'local':
                    path = os.path.join(self.opts['pki_dir'], key)
                else:
--
    def finger_all(self):
        '''
        Return fingerprints for all keys
        '''
        ret = {}
        for status, keys in self.list_keys().items():
            ret[status] = {}
            for key in keys:
                if status == 'local':
                    path = os.path.join(self.opts['pki_dir'], key)
                else:
```

**Comment by jacksontj** [comment]
Yes we would, but now is probably a better time to try and clean the mess ;) its going to be very confusing to know which key is in which folder since they have the same *basic* name (just different prefix)-- which also means when we need to do this again we'll have to come up with a third set of names that mean the same thing-- might as well namespace them IMO for clarity

**Comment by thatch45** [comment]
well yes, duh... The Key classes, of course they would be better that way

**Comment by thatch45** [comment]
Again, yes, I agree, the subdirs get defined in the Key classes, we just need to make a mechanism that makes automatically migrates the keys so that the locations can be changed in an upgrade. I agree, we should put the keys in subdirs

**Comment by jacksontj** [comment]
Cool, all on the same page now :)

I'd been thinking about how to do the transition, I'm not sure if we just
want to do that as a one-time check on startup to do the move or have the
key classes pull from a new config thats equivalent to pki_dir and always
check the old ones too until the config is removed. The first one is
simplest, but if someone has automated key management outside the daemons
#2 will be better for them (although it will come at a performance cost).

Maybe there is a more awesome idea #3, but I haven't thought of it yet ;)

**Comment by thatch45** [comment]
So I am thinking that we keep the pki_dir config the same, that way we don't need to guess what the previous config is. Then the migration routine is encapsulated in the Key classes so that the check happens when they are called. That way external automated routines that use the key libs will automatically update and we can call the routines on startup. that also can isolate the lookup to startup and when the key classes are called

**Comment by jacksontj** [comment]
That makes sense, I like it :) then you could just run list all and it
would move everything cool

**Comment by thatch45** [comment]
awesome! I need to jump over to do some master cluster work, if we get our transports right the master cluster could work for raet and zmq minions, although it would work MUCH better for raet minions :)

**Comment by kiorky** [comment]
In the upgrade steps, shall we do symlinks to keys in inner dirs to allow rollbacks to a version of a saltmaster which did not have this yet ?

**Comment by jacksontj** [comment]
Probably a good idea

**Pull request merged**
