### PR TITLE
Openstack keystone V3 API support in keystone modules.

### PR DESCRIPTION
**Pull request by jirikotlin**
### What does this PR do?

Modified openstack keystone state and execution module to be both usable with new V3 API.
### Previous Behavior

Keystone V2 API support only.
### New Behavior

Supports both openstack keystone V2 and V3 API.
### Tests written?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by gtmanfred** [comment]
@jirikotlin I am working on rewriting all of these modules with `shade` right now, this should add v3 support to keystone as well.

**Comment by gtmanfred** [comment]
https://github.com/saltstack/salt/compare/develop...gtmanfred:shade

I am hoping to finish it this week, so I am going to close this pr for now.

**Comment by jirikotlin** [comment]
Hi, ok. Will it also support domains? (was on my to do list).

**Comment by gtmanfred** [comment]
Right now, it should just be mirroring support of what is supported now, but domains was one of the things I was going to be adding before this is done.

**Comment by jirikotlin** [comment]
Hi, @gtmanfred , how is it going with keystone V3 API support?

(We are currently working on project using Salt and Keystone, but developing and using own module is not perspective for us if there will be different one.)

Thank you for info.

**Comment by gtmanfred** [comment]
RIght now it is on hold till after salt conf next week, but I am going to try and put it in the sprint for the first one after saltconf and get it done in those two weeks.

**Comment by seanjnkns** [comment]
@gtmanfred, any update?  Our organization is looking at deploying Mitaka, which only works with V3 of the API w/ fernet tokens, so it'd be preferable to utilize an official module than write one ourselves or create a series of cmd.scripts to setup and ensure endpoints and other credentials are properly established.

**Comment by gtmanfred** [comment]
I am working on this write now, I will update this issue when I am finished

https://github.com/saltstack/salt/issues/30272

**Comment by jirikotlin** [comment]
Hi, @gtmanfred  if it is desired and constructive I can offer some help with rewriting these modules.

Sorry for claiming this again :) we are realy waiting on this.

I was also looking that shade already supports domains in keystone, so I can also participate later to implement this feature.

thank you for reply

**Comment by seanjnkns** [comment]
Any update @gtmanfred?  Otherwise, @jirikotlin if you could create a PR for this, I'd be happy to test it.

**Comment by gtmanfred** [comment]
Yes, I have been delayed in finishing this, if you wanna update the
keystone client version, they would be great so it can get into carbon

**Comment by jirikotlin** [comment]
Hi @seanjnkns , @gtmanfred - so do I have to make another pull request ??

**Comment by gtmanfred** [comment]
If you wouldn't mind.  It looks like the branch this one was made against has been deleted

**Comment by jirikotlin** [comment]
Hello, ok: #35670

**Pull request closed without merging**
