### PR TITLE
Allow to override git_pillar_base per-remote (Port #51640 to master)

### PR DESCRIPTION
**Pull request by sathieu**
### What does this PR do?

Allow to override git_pillar_base per-remote.

Note: port of #51640.

### New Behavior
Example:
```yaml

git_pillar_base: develop

ext_pillar:
  - git:
    - __env__ https://gitserver/git-pillar.git
    - __env__ https://gitserver/git-pillar2.git:
      - base: master
```

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by sathieu** [comment]
@dwoz Please review again.

**Comment by sathieu** [comment]
@cmcmarrow  @dwoz Please review again.

**Review by cmcmarrow — DISMISSED** [review]

**Comment by sathieu** [comment]
@cmcmarrow You've marked this PR *Merge Ready*. I've now rebased and fixed `pre-commit` and `Pylint`. Hope you merge it now ...

**Comment by sathieu** [comment]
@sagetherage @cmcmarrow Any chance to get this reviewed and merged soon? It was marked merge-ready few months ago...


Thanks

**Comment by sagetherage** [comment]
looking into this now

**Comment by sathieu** [comment]
@cmcmarrow @sagetherage Hello. Sorry to insist, but can this be merged in magnesium ?

This MR exists since Feb 2019.

**Comment by sagetherage** [comment]
yes, labeled and I updated it with master now

**Review by dwoz — APPROVED** [review]

**Pull request merged**
