### PR TITLE
check_result: Correctly check the __extend__ state.

### PR DESCRIPTION
**Pull request by chnrxn**
### What does this PR do?
check_state_result() is expecting all highstate items to be a dict, but
states using extend are lists. This PR checks __extend__ states more accurately.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/42512

### Previous Behavior
check_result will return False when an otherwise valid state uses extends.

### New Behavior
check_result now correctly checks __extend__ states.

### Tests written?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by rallytime** [comment]
re-run ubuntu

**Comment by cachedout** [comment]
I would vastly prefer if we could cover this case with a unit test so that we don't regress here again. @chnrxn is this something you could tackle?

**Comment by cachedout** [comment]
Bump @chnrxn

**Comment by rallytime** [comment]
@chnrxn I was able to back-port this to the 2017.7 branch without any issues, but the 2016.11 back-port did not work as easily. A separate fix will need to be made there if you want this to be fixed in the 2016.11 branch.

**Pull request merged**
