### PR TITLE
Update to the newer AMIs

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title

### CODE REVIEW

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Review by garethgreenaway — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Review by cmcmarrow — APPROVED** [review]

**Pull request merged**
