### PR TITLE
fix a del in cloud vmware that crash when the key isn't there

### PR DESCRIPTION
**Pull request by remijouannet**
so I don't really understand what I've patch but this line always throw a KeyError when i try to deploy a machine on vcenter

(if that can be backport to 2017/2018 that would be great )

### CODE REVIEW

**Review by gtmanfred — APPROVED** [review]

**Comment by gtmanfred** [comment]
@saltstack/team-core this is ready and should probably be backported.

**Comment by thatch45** [comment]
Thanks @remijouannet !
Sorry, with the holidays we have been a little behind in PR merges and reviews.
Thanks @gtmanfred !

**Comment by remijouannet** [comment]
no problem, any chance for this bugfix to be include in the future 2017.7.9 ? we haven't upgrade to 2018 yet

**Comment by thatch45** [comment]
I will have to double check the release schedule, but that would be a reasonable ask :)

**Pull request merged**
