### PR TITLE
Fix windows osrelease grain

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?

Properly gets the osrelease grain for Server versions of Windows. 
### What issues does this PR fix or reference?

https://github.com/saltstack/salt/issues/36307
### Previous Behavior

OS name was removed in the python command platform.uname(). Python version 2.7.8 would return a value of "2008ServerR2" for Windows Server 2008 R2. We moved to Python 2.7.11 and later to 2.7.12 which both report the Desktop version of 7 instead of the server name of 2008ServerR2.
### New Behavior

Properly detect windows server os release grain along with any applied service packs.
### Tests written?

No

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @twangboy 

The code that was copied from StackOverflow needs to be linted so that it passes tests, please.

As far as the overall change goes, are you certain that you want to change core grains in a point release? Traditionally, this has been something that we have not done. This may make more sense in a major release.

**Comment by UtahDave** [comment]
I agree with @lorengordon, we should restore the grain to what it was before `2008ServerR2`, etc.
We'll move the Service Pack to a new grain.

**Comment by damon-atkins** [comment]
How does PY3 behavior?

**Comment by twangboy** [comment]
Py3 returns the same as Py2.7.12

**Comment by lorengordon** [comment]
PY3 also depends on the python version:
```
PS C:\Users\Administrator> C:\Python33\python.exe --version
Python 3.3.5
PS C:\Users\Administrator> C:\Python33\python.exe -c "import platform;print(platform.win32_ver())"
('2012Server', '6.2.9200', '', 'Multiprocessor Free')
PS C:\Users\Administrator> C:\Python34\python.exe --version
Python 3.4.4
PS C:\Users\Administrator> C:\Python34\python.exe -c "import platform;print(platform.win32_ver())"
('2012ServerR2', '6.3.9600', '', 'Multiprocessor Free')
PS C:\Users\Administrator> C:\Python35\python.exe --version
Python 3.5.2
PS C:\Users\Administrator> C:\Python35\python.exe -c "import platform;print(platform.win32_ver())"
('8.1', '6.3.9600', 'SP0', 'Multiprocessor Free')
```

**Comment by cachedout** [comment]
How are we all feeling about the latest changes here?

**Comment by lorengordon** [comment]
Works for me if it works for you. I tested the patch and it does fix the issue.

```
PS C:\Users\Administrator> C:\salt\salt-call.bat --version
salt-call 2015.8.12 (Beryllium)
# Without the patch
PS C:\Users\Administrator> C:\salt\salt-call.bat --local grains.get osrelease
local:
    8.1
# With the patch
PS C:\Users\Administrator> C:\salt\salt-call.bat --local grains.get osrelease
local:
    2012ServerR2
PS C:\Users\Administrator>
```

**Comment by cachedout** [comment]
Thanks, @lorengordon. I'll go ahead and get this in then.

**Pull request merged**
