### PR TITLE
Added refs to AIX module documentation

### PR DESCRIPTION
**Pull request by Akm0d**
### What does this PR do?
Add ref to documentation for AIX 

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/53333

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by bryceml — CHANGES_REQUESTED** [review]
https://github.com/bryceml/salt/commit/a905c280051324311df13537a2c7b194bcf4f27f

you have to add it to the index too.

**Comment by bryceml** [comment]
I wasn't very through on the commit I posted above, so there might be additional changes as well.

**Comment by Akm0d** [comment]
Got it, anywhere else we might need a change?  Is My description of AIX pkg correct?

**Review by bryceml — APPROVED** [review]

**Comment by mchugh19** [comment]
Likely part of #52368 as well

**Comment by Akm0d** [comment]
re-run full all

**Comment by Akm0d** [comment]
> Likely part of #52368 as well

Looks like most of it is similar.  There are some change to the index and such seem to be unique to this PR

**Review by garethgreenaway — APPROVED** [review]

**Review by waynew — APPROVED** [review]

**Pull request merged**
