### PR TITLE
Salt-Cloud Provider nova floating ip handling:

### PR DESCRIPTION
**Pull request by s-schweer**
- allow auto assigning floating ips
- allow using one of floating_ips, fixed_ips, public_ips, private_ips as ssh_interface

### CODE REVIEW

**Comment by cachedout** [comment]
@s-schweer It appears that this PR modifies more than just salt-cloud. I see some changes in the doc/ directory here. I assume those were unintentional? If so, could you please remove them before we merge this? Thanks.

**Comment by s-schweer** [comment]
Hi, 

all changes from doc folder have been reverted now

**Comment by rallytime** [comment]
@s-schweer Thank you for cleaning this up and thank you for this submission! 

@gtmanfred Would you mind reviewing this as well?

**Comment by gtmanfred** [comment]
+1

**Pull request merged**
