### PR TITLE
Avoid starting minion starting if already running

### LINKED ISSUE #25013: Multiple instances of salt-minion -d
if salt-minion -d is run multiple times on the same machine then a duplicate process will be created.  When the salt-master runs a command on the minions, it will run once for each instance of salt-minion -d.

Ideally, the "salt-minion -d" command would kill the previous daemon and then start up again, else see that there is already a daemon running and not create a new instance

### PR DESCRIPTION
**Pull request by cachedout**
Here, we check both the pid and compare the pid to the process list to try and make a decision about whether or not we're about to startup a minion which will produce duplicate returns.

Closes #25013

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Looks good. I take it you also took it for a "spin".... :)

**Comment by cachedout** [comment]
@s0undt3ch I've taken it around the block a few times. So far, I haven't crashed into anything. ;]

**Comment by s0undt3ch** [comment]
That's what we all love to hear. Go Go @cachedout!

**Comment by s0undt3ch** [comment]
The failing tests are known failures.

**Pull request merged**
