### PR TITLE
add boto3_asg state and module and boto3_lc state

### PR DESCRIPTION
**Pull request by oba11**
### What does this PR do?

This PR does
 * adds boto3 equivalent for `boto_asg` state module and execution module
* adds boto3 equivalent for `boto_lc` state module

### What issues does this PR fix or reference?

We started noticing that boto_asg was failing for some of our autoscaling groups, making the same call with boto3 works. On chatting with AWS support team, it was recommended to move to boto3 which prompted us to rewrite the state modules and execution modules in boto3

Steps to reproduce the issues
```
# ipython
In [1]: import boto.ec2.autoscale
In [2]: conn = boto.ec2.autoscale.connect_to_region()
In [3]: conn.get_all_groups()
Out[3]: 
[AutoScaleGroup<None>,
 AutoScaleGroup<None>,
 AutoScaleGroup<None>,
 AutoScaleGroup<None>,
 AutoScaleGroup<None>,
 AutoScaleGroup<None>,
 AutoScaleGroup<None>,
 AutoScaleGroup<None>,
 AutoScaleGroup<None>,
 redated,
 AutoScaleGroup<None>,
 AutoScaleGroup<None>,
 AutoScaleGroup<None>,
 AutoScaleGroup<None>,
 AutoScaleGroup<None>,
 AutoScaleGroup<None>,
 AutoScaleGroup<None>,
 AutoScaleGroup<None>,
 redacted]

In [4]: import boto3
In [5]: client = boto3.client('autoscaling')
In [6]: client.describe_auto_scaling_groups()
Out[6]: works well
```

### Previous Behavior
N/A

### New Behavior
N/A

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
@ryan-lane Is this something you'd be interested in reviewing and giving some feedback?

**Comment by ryan-lane** [comment]
Please don't split things up like this....

**Comment by ryan-lane** [comment]
The right way to approach boto3 transition is to move the execution module to boto3, then adapt the current state module to the changes in the execution module, so the state module API doesn't change at all. We're in the process of doing this with a number of other modules.

By introducing boto3_something states, it introduces a new state module api, doubles the amount of code we need to maintain, and potentially introduces new bugs that aren't going to be tested quite as well.

**Comment by ryan-lane** [comment]
I'm pretty strongly opposed to this being merged in its current form.

**Comment by oba11** [comment]
@ryan-lane thanks for reviewing the PR, there are already bunch of boto3_ [states](https://github.com/saltstack/salt/tree/develop/salt/states) and {modules](https://github.com/saltstack/salt/tree/develop/salt/modules) which have already been merged.

One thing I can suggest is a similar approach used by boto when moving to boto3 is to support both `boto_` and `boto3_` and over time cleanup `boto_`.

FYI new features are no longer added to `boto2`

**Comment by ryan-lane** [comment]
Yeah, the boto3_ modules that have been added need to be marked as
deprecated. The path forward for the modules is to modify the boto_
execution modules in place to use boto3 rather than boto, then to update
the state modules that call the execution module to be compatible.

Having boto and boto3 state modules requires end users to choose which one
to use and also requires people to rewrite their sls code. We need to keep
backwards compat with the existing state modules unless we want to lose all
of our users.

**Comment by ryan-lane** [comment]
As you have already mentioned, a good short-term option is to use both boto2 and boto3 in the same execution module. Across the boto_ modules right now, we have a mix of modules using just boto, some using boto and boto3, and others using boto3.

**Comment by oba11** [comment]
Thanks @ryan-lane , you think the PR is good to be merged for short term or needs more review?

**Comment by cachedout** [comment]
@oba11 We are not going to merge any additional modules named `boto3_*`. Beyond simply the naming, I will leave it up to @ryan-lane to lend some guidance about whether other changes might make this mergeable.

**Comment by ryan-lane** [comment]
@oba11 No, I'm saying that if you want boto_asg and boto_lc to use boto3, then you need to update the code in the boto_ modules, not add new boto3_ modules. To fix the specific issue you have, you could pull boto3 into the boto_asg or boto_lc execution module, and move just the functions you need to over to boto3, if you don't want to update the entire module.

**Pull request closed without merging**
