### PR TITLE
Fileclient testcase (2016.11)

### PR DESCRIPTION
**Pull request by isbm**
### What does this PR do?

Backports https://github.com/saltstack/salt/pull/40450

### CODE REVIEW

**Comment by cachedout** [comment]
Go Go Jenkins!

**Review by cachedout — CHANGES_REQUESTED** [review]
We have one lint issue and one test failure here.

**Comment by isbm** [comment]
Thanks, GvR, for this utter mess! ( @cachedout fixed)

**Comment by isbm** [comment]
@cachedout the test error is happening, of course, because test is right and `2016.11` is affected! :laughing: Wasn't the patch backported from the devel?..

**Comment by cachedout** [comment]
@isbm Which patch are you referring to?

**Comment by isbm** [comment]
@cachedout https://github.com/saltstack/salt/commit/43a5e30386b9759a85bc3a26a9dddce48a877587

**Comment by isbm** [comment]
@cachedout OK, I took that patch as well. Now should be OK.

**Review by cachedout — APPROVED** [review]

**Review by rallytime — APPROVED** [review]

**Pull request merged**
