### PR TITLE
cloud vmware get_instance [size] #38814

### PR DESCRIPTION
**Pull request by cetanu**
changed from str to dict

### What does this PR do?
Changes the size returned by cloud queries to vmware from a unicode string containing the number of cpu cores and ram, to a dictionary, so that users do not need to split and handle the string when accessing the data.

### What issues does this PR fix or reference?
 #38814

### CODE REVIEW

**Comment by nmadhok** [comment]
This will break functionality for other users who have been using size and expect it to return a string. The only reason it's a string and not a dictionary was to match with other cloud providers.

**Comment by cetanu** [comment]
discussion continued in: #38814

**Review by nmadhok — COMMENTED** [review]
@techhat @cachedout Did we decide to move away from cloud drivers from being standardized? If so then we also need to change a lot in the VMware cloud driver including the concept of image and size. If that is the case, I'm fine with this being merged into develop

**Comment by techhat** [comment]
Ping @gtmanfred

**Comment by gtmanfred** [comment]
We are not removing the standardization yet.  In the drivers that currently exist, they should remain standardized across.

**Review by nmadhok — CHANGES_REQUESTED** [review]
@cetanu See changes proposed in https://github.com/saltstack/salt/issues/38814#issuecomment-307943007

**Comment by cachedout** [comment]
@cetanu Did you see the above comment from @nmadhok ?

**Comment by cetanu** [comment]
@cachedout , yep, we agreed in on the change in #38814 , I'll push up the change to my patch branch now.

**Comment by cachedout** [comment]
@nmadhok Re-review requested.

**Review by nmadhok — APPROVED** [review]
@cachedout Looks good other than the comments I made

**Review by cachedout — APPROVED** [review]

**Pull request merged**
