### PR TITLE
Allowing salted annotation stamp on VMWare VM #35568

### PR DESCRIPTION
**Pull request by cetanu**
### What does this PR do?

Allows a user to set a message for the notes/annotation box in vmware vsphere for a newly created VM.

I could not find any documented limit on the message size.

### What issues does this PR fix or reference?
#35568

### CODE REVIEW

**Review by nmadhok — APPROVED** [review]

**Review by nmadhok — CHANGES_REQUESTED** [review]
I think it'll be better to cast ``annotation`` to a string since ``config_spec.annotation`` needs to always be a string!

**Comment by cetanu** [comment]
I agree, I'll add an explicit cast to string

I also commented on the tagged issue regarding inserting dynamic data into this key, what are your thoughts?

**Review by nmadhok — APPROVED** [review]
Looks Better now

**Comment by nmadhok** [comment]
Adding dynamic data will need to be handled using Jinja in the map files.

**Comment by cetanu** [comment]
Yep, that seems fair. I suppose users can also directly modify mapfiles using a YAML library and insert data prior to applying them, too.

**Comment by nmadhok** [comment]
Yes some users dynamically generate their map files using scripting/form submissions through a Web Page.

**Review by cachedout — APPROVED** [review]

**Pull request merged**
