### PR TITLE
[port jam] 49227 - add ability to pass exclude kwarg to salt.state within orchestrate

### LINKED ISSUE #49130: There no way to exclude SLS in calling salt.state inside orchestration
### Description of Issue/Question
I'm trying to make scenario for orchestrate and invoke it via reactor.
What I have now:
```my_state:
  salt.state:
    - tgt: '{{ node_name }}'
    - sls: foo
    - queue: True
    - require:
      - salt: other_state
```
That basically is equivalent to:
`salt -C node_name state.sls foo`

I need to apply state with exclude like:
`salt -C node_name state.sls foo exclude=foo.bar.buzz`
I tried a lot of variants(simple adding exclude: foo.bar.buzz, adding it via args, kwargs, running SLS via salt.function - no results), but after I found that in `salt/states/saltmod.py` there no arg named `exclude` or smth same.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```my_state:
  salt.state:
    - tgt: '{{ node_name }}'
    - sls: foo
    - exclude: foo.bar.buzz
    - queue: True
    - require:
      - salt: other_state
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
1. Setup Salt
2. Create SLS with salt.state call and add to it `exclude` flag
3. Invoke it.
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2017.7.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-101-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
P.S. Yep, I know that this is a little bit old, but I'm pretty sure, that the same issue will be reproduced with latest salt.

### PR DESCRIPTION
**Pull request by waynew**
### What does this PR do?

Port #49227
and
Closes https://github.com/saltstack/salt/pull/58547
### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by md-magenta** [comment]
@dwoz What is needed for this to be merged? It has a testcase and the failing test seems to just be a fluke.

**Comment by md-magenta** [comment]
@dwoz and @waynew Is there anything I can do to help further this along?

**Comment by Ch3LL** [comment]
pre-commit needs to be cleaned up here

**Comment by sagetherage** [comment]
looks like this is failing on macos catalina and ubuntu 16 04

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
