### PR TITLE
Create a state for the cpan module

### PR DESCRIPTION
**Pull request by Akm0d**
### What does this PR do?
Create a state for the cpan module

### What issues does this PR fix or reference?
#2130

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?
**[NOTICE] Bug fixes or features added to Salt require tests.**
Please review the [test documentation](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html) for details on how to implement tests into Salt's test suite.

Yes

### Commits signed with GPG?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by Akm0d** [comment]
```Error Message

False is not True. Salt Comment:  gzip: stdout: Broken pipe Can't locate Test/More.pm in @INC (@INC contains: /root/.cpan/build/Digest-MD5-2.55-o9E2Ry/blib/lib /root/.cpan/build/Digest-MD5-2.55-o9E2Ry/blib/arch /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at t/threads.t line 3. BEGIN failed--compilation aborted at t/threads.t line 3. Failed 1/8 test programs. 0/275 subtests failed. make: *** [test_dynamic] Error 255

Stacktrace

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/states/test_cpan.py", line 47, in test_cpan_installed_removed
    self.assertSaltTrueReturn(ret)
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 570, in assertSaltTrueReturn
    **(next(six.itervalues(ret)))
AssertionError: False is not True. Salt Comment:

gzip: stdout: Broken pipe
Can't locate Test/More.pm in @INC (@INC contains: /root/.cpan/build/Digest-MD5-2.55-o9E2Ry/blib/lib /root/.cpan/build/Digest-MD5-2.55-o9E2Ry/blib/arch /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at t/threads.t line 3.
BEGIN failed--compilation aborted at t/threads.t line 3.
Failed 1/8 test programs. 0/275 subtests failed.
make: *** [test_dynamic] Error 255
		

Standard Output

	

Standard Error

	```

**Comment by Akm0d** [comment]
```Error Message

module file cpan is missing documentation in /tmp/kitchen/testing/doc/ref/states/all

Stacktrace

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/test_doc.py", line 396, in test_states_doc_files
    self._check_doc_files(skip_module_files, module_dir, skip_doc_files, doc_dir)
  File "/tmp/kitchen/testing/tests/unit/test_doc.py", line 136, in _check_doc_files
    full_module_doc_dir))
AssertionError: module file cpan is missing documentation in /tmp/kitchen/testing/doc/ref/states/all
		

Standard Output

	

Standard Error
```

**Review by garethgreenaway — APPROVED** [review]

**Comment by Akm0d** [comment]
re-run py2-centos-6

**Review by cmcmarrow — APPROVED** [review]

**Comment by Akm0d** [comment]
re-run windows

**Comment by Akm0d** [comment]
re-run py2-centos-6

**Comment by Akm0d** [comment]
re-run centos

**Comment by Akm0d** [comment]
re-run centos

**Pull request merged**
