### PR TITLE
only keep last 10 builds of every pr on jenkins to reduce disk usage

### PR DESCRIPTION
**Pull request by bryceml**
What does this PR do?

It adjusts the jenkins pipeline files to only keep the last 10 builds of PR's so we don't fill up jenkins when some pr's have around 100 builds sitting around.
What issues does this PR fix or reference?

None
Previous Behavior

Builds for pr jobs were kept until the pr was closed.
New Behavior

Builds for pr's only are kept if they are the 20 most recent builds for a given pr.
Tests written?

N/A
Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by bryceml** [comment]
re-run full all

**Review by dwoz — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Review by Akm0d — APPROVED** [review]

**Review by dmurphy18 — COMMENTED** [review]
@bryceml  Wondering about Amazon Builds, both Linux 1 and Linux 2.  Also Fedora builds.

FYI - this got merged out from underneath me as I added my review

**Comment by bryceml** [comment]
@dmurphy18 They aren't implemented for pr's, we should make an issue if we want to test them.

**Comment by dwoz** [comment]
Once we have passing tests for them on a given branch we should add them to PR tests.

**Comment by dmurphy18** [comment]
@bryceml @dwoz Sounds like a plan

**Pull request merged**
