### PR TITLE
fixes multiple values in mof configuration

### PR DESCRIPTION
**Pull request by Inveracity**
### What does this PR do?

Inserts `;` into the command that generates the configuration to create the mof file in  `set_lcm_config()`
### What issues does this PR fix or reference?
saltstack/salt#34548
### Previous Behavior

Did not insert all values from state
### New Behavior

Inserts all values from state
### Tests written?

No

### CODE REVIEW

**Comment by cachedout** [comment]
@twangboy Can you please have a look at this?

**Comment by twangboy** [comment]
@cachedout Looks fine. Maybe should be backported to 2016.3

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by Inveracity** [comment]
:honeybee:

**Pull request merged**
