### PR TITLE
fix broken ipv6 address verification in salt.utils.validate.net, fixes #20508

### LINKED ISSUE #20508: Backport ipv6 addr validation fix into 2014.7
Please backport the ipv6 addr validation fix into 2014.7 since the (old) current version in 2014.7 is not working properly.

d03ff7d6ddd658b75c37d48ba19b5dd5da825c69

### PR DESCRIPTION
**Pull request by arnisoph**

### CODE REVIEW

**Comment by jfindlay** [comment]
@bechtoldt, the new tests are failing on jenkins, also there's some lint errors coming from the new tests as well.  Will you fix them?  Thanks for the fix.

**Comment by bechtoldt** [comment]
@jfindlay I think the PR is ready2merge. The error in the ubuntu tests is unrelated.


FYI: This repo needs to be backported into develop and 2015.2, too.

**Comment by jfindlay** [comment]
@bechtoldt, the way our git branches are setup, changes made in 2014.7 will be merged forward into the 2015.2 and develop branches every few days.

**Comment by bechtoldt** [comment]
@rallytime this PR contains some fixes in the tests

**Comment by rallytime** [comment]
@bechtoldt Just to make sure, this one should be used instead of #20535?

**Comment by bechtoldt** [comment]
@rallytime yes, sorry for the confusion!

**Comment by rallytime** [comment]
No problem! I'll close mine in favor of this one.

**Pull request merged**
