### PR TITLE
Port #50950 to master

### PR DESCRIPTION
**Pull request by alexey-zhukovin**
### What does this PR do?

Port #50950 to master

### CODE REVIEW

**Comment by xanderificnl** [comment]
It appears to add support for subuid/subgid, i.e. for LXC containers. Podman also uses subuid/subgid to provide rootless containers.

At this point: what is required to get that PR, or a PR similar to that, merged? I couldn't find any reference of subgid elsewhere in the repo (via GitHub's search.)

**Comment by garethgreenaway** [comment]
@xanderificnl Looks like we need some tests as well as a changelog file to get this merged in.

**Comment by xanderificnl** [comment]
I doubt I'll be able to get to it in the foreseeable future, my backlog is rather full at this time. If someone else wants a crack at this, please do!

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
