### PR TITLE
add module nacl

### PR DESCRIPTION
**Pull request by steverweber**

### CODE REVIEW

**Comment by thatch45** [comment]
Thanks @steverweber !

**Comment by steverweber** [comment]
i hope its not to buggy... i was sick yesterday and running on night-time cold meds.
a little review and or testing might be a good idea.

**Comment by steverweber** [comment]
shrug it looks fine. :) thanks for merging.

**Comment by thatch45** [comment]
You do things in a round about way, there are some shortcuts in libnacl that I might need to better document :)
but this is a great start and safely implemented :)

**Pull request merged**
