### PR TITLE
Update artifactory module to handle py3 encoding

### LINKED ISSUE #56660: expected bytes-like object, not str while downloading from Artifactory
### Description of Issue
Since upgrade of python version to 3.6.8.final [artifactory.downloaded ](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.artifactory.html#salt.states.artifactory.downloaded)state stopped working.  
All requests are throwing this error "expected bytes-like object".  
Same formula on python 2.7.5 was working fine. 

### Setup
Salt minion version: "2019.2.3"
Python version: 3.6.8.final .

### Steps to Reproduce Issue
Sample state to run:
```yaml
Download archive file from artifactory:
  artifactory.downloaded:
    - artifact:
       artifactory_url: "{{pillar['artifactory_url']}}"
       repository: "{{ pillar['artifactory_repository']}}"
       group_id: "{{ pillar['artifactory_group_id'] }}"
       artifact_id: "{{ pillar['artifactory_artifact_id'] }}"
       packaging: "{{pillar['artifactory_artifact_packaging']}}"
       version: "{{pillar['artifactory_artifact_version']}}"
       username: "{{ pillar['artifactory_user']}}"
       password: "{{ pillar['artifactory_api_key']}}"
    - target_file: /tmp/file-{{pillar['artifactory_artifact_version']}}.{{pillar['artifactory_artifact_packaging']}}
```

### Versions Report
salt --versions-report
Salt Version:
           Salt: 2019.2.3
Dependency Versions:
           cffi: 1.13.2
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 3.0.5
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: 0.28.2
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.28.2
         Python: 3.6.8 (default, Jun 11 2019, 15:15:01)
   python-gnupg: 0.4.4
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.7 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.12.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.7 Maipo

### PR DESCRIPTION
**Pull request by erobeson**
Fixes #56660

Py3 encoding of username and password headers requires extra handling.
Convert username:password header string to bytes then b64 encode bytes.
Handle case where py3 returns data in bytes.

### What does this PR do?
Convert username:password header string to bytes before b64 encoding.
Handle case where py3 returns data in bytes, decode to string .

### What issues does this PR fix or reference?
Fixes: 56660

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by dwoz — DISMISSED** [review]

**Comment by waynew** [comment]
@erobeson  thanks for the PR! Looks good, though we do require tests, and need a [changelog entry](https://docs.saltstack.com/en/master/topics/development/changelog.html). If you are able to get some passing tests written by Monday, we should be able to get this merged in for Sodium. If you need help writing tests, I'll be running a test clinic tomorrow morning (America time) on our [Twitch stream](https://www.twitch.tv/saltstackinc)

**Comment by erobeson** [comment]
Hi @waynew . I just added the changelog file as you requested. WRT tests, I see some tests already exist for this module. I have never written a test and I don't see an obvious way to create one specific to the changes I am committing for this bug fix. I looked at the log for the one failing test, and it appears to be caused by something outside the scope of this bug-fix.

**Comment by waynew** [comment]
@erobeson if you have some time tomorrow, I can walk you through writing a test. If we weren't doing a dev done/code freeze on Monday, I would suggest next Tuesday's test clinic. 

I think tests should be fairly straightforward here. I'm looking at this file and I'm seeing a bunch of `__` functions that don't make any sense to me.

From a Python perspective, `__` means "you have no business using this function it's literally only for my use and is irrelevant for anyone else to use." But they're used here to mean you can't call them as `artifactory.stuff`. My strong opinion weakly held is that all the double underscore functions should be changed to single underscore functions.

Anyway, let me know if you'd like some help tomorrow (or I could also help some later this evening).

**Review by waynew — CHANGES_REQUESTED** [review]
Hey @erobeson please reach out in #salt on irc.freenode.net, or hit me up on Slack, or during a Test Clinic on twitch and I can help you with writing tests for this :+1:

**Comment by DmitryKuzmenko** [comment]
@erobeson Thank you for your work. I've created a new PR based on your fix slightly updated it and wrote tests. I'm closing this one.

**Pull request closed without merging**
