### PR TITLE
Randomize fileserver update

### PR DESCRIPTION
**Pull request by jmalerbsjr**
### What does this PR do?
Randomizes fileserver update process after first iteration.

### What issues does this PR fix or reference?
Sporadic errors generated from AWS S3, when pulling a significant number of files from several masters polling on the same interval.

### Previous Behavior
Fileserver update process ran on the same fixed interval.

### New Behavior
Runs fileserver update on master service start (unchanged), then randomizes on subsequent runs between (60 and 600 seconds).

### Tests written?
No

### Commits signed with GPG?
No

### CODE REVIEW

**Review by terminalmage — COMMENTED** [review]
I am very hesitant to merge this, for two reasons:

First, many users are upset about a 60-second interval and want it refreshed more often. These users have moved to manually running `salt-run fileserver.update` before kicking off their highstates, but this is an annoying extra step. This would only be intensified as the interval is raised.

Second, while I'm not sure if there's an open issue for it, there are plans to make the interval tunable (in the same way that `root`, `mountpoint`, etc. are). This would involve spawning a thread specifically for fileserver updates, taking it out of the maintenance thread altogether.

Having a tunable interval would be a lot more flexible than this approach, as well.

**Comment by jmalerbsjr** [comment]
Fantastic, thanks for the feedback @terminalmage

**Comment by cachedout** [comment]
OK, so it sounds like the decision here then is to close this without merging it and in favor of the approach described by @terminalmage.  I'll go ahead and do so.

**Comment by terminalmage** [comment]
@jmalerbsjr thanks, I'll make sure to loop you in when we get that tunable interval implemented.

**Pull request closed without merging**
