### PR TITLE
Add macOS BigSur to CICD

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title.

### What issues does this PR fix or reference?
Refs: https://github.com/saltstack/salt/pull/57028

### CODE REVIEW

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
@weswhet FYI, Salt runs under Py3.9 on Catalina 🎉 

This PR adds BigSur, and it has some failures related to shadow tests.
There's also a problem that, mid test run, the VM no longer accepts SSH connections, and I have no clue how to fix this.

Any light and help you could bring into this, is more than welcomed.

**Comment by weswhet** [comment]
Amazing! Thank you! I can take a look this week.

**Comment by s0undt3ch** [comment]
Thank You!

**Comment by s0undt3ch** [comment]
re-run full all

**Pull request closed without merging**
