### PR TITLE
Fix forward-merged caching from 2015.5 into 2015.8 to be compatible with the new match_func

### PR DESCRIPTION
**Pull request by driskell**
Continuation from #26228 for @basepi 
All looks good - lint passing - tests passing (though I have seen random failures).

Importantly though, I am unable to test this as I can't jump to 2015.8 on any of my systems. But hopefully it's all good and can be tested further by SaltStack.

### CODE REVIEW

**Comment by driskell** [comment]
Let me know if I should put in a backwards compat layer for the `tags_regex` parameter that was added for 2015.5. Just the `match_func` to be fair makes it pretty redundant.

**Comment by driskell** [comment]
@basepi

All done now - updated description - as per previous note, let me know if I should put in a backwards compat layer for the `tags_regex` parameter that was added for 2015.5. I've removed this when fixing the merge because it becomes essentially redundant. But if there is fear something is already relying on it (even though last PR was mere week or two ago I think) let me know. But it should be easy for someone at SaltStack to just take `tags_regex` and make a single regex from it with `|` operator, throw in the given tag too quoted and between `^$`, and force the match_type to be `regex`.

**Comment by basepi** [comment]
Yeah, I'm not too worried about that particular piece of backward compat at the moment. Mostly I'm just hoping the intermittent ubuntu test failures go away now...

**Comment by driskell** [comment]
@basepi Hopefully they will. If not, I snuck in extra output on the assertion error so you can see exactly what isn't matching and hopefully ascertain quickly what is happening in those tests - such as whether or not the ZeroMQ is reordering things in the backlog etc for some reason.

**Comment by basepi** [comment]
Thanks!

**Pull request merged**
