### PR TITLE
Fix traceback when excludes are present in an included SLS file

### LINKED ISSUE #47182: state.highstate error with require_in: sls:
### Description of Issue/Question
`state.highstate test=true` returns with

```
    Passed invalid arguments to state.highstate: list indices must be integers, not unicode
```
(followed by the complete state.highstate docs).

`state.show_top` works fine, and returns the expected result.

running `state.sls` with each individual state works, too.
But `state.highstate` does not.

I found that when I removed the "require_in" block of something like

```
include:
  - slsfile1
  - slsfile2

some-state:
  test.nop:
    - require:
      - sls: slsfile1
    - require_in:
      - sls: slsfile2
```

the error no longer appears. The same states worked fine in Salt 2017.x.x

The closest Issue I found is #22852, but that's supposed to be fixed. In either case, an error message pointing to the exact location would be nice (I had to "bisect" the state tree down to the exact location).

In the minion log file (level: trace), I found this Traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1600, in _thread_return
    return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1055, in highstate
    orchestration_jid=orchestration_jid)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 3881, in call_highstate
    return self.state.call_high(high, orchestration_jid)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2693, in call_high
    high, req_in_errors = self.requisite_in(high)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1574, in requisite_in
    hinges = find_sls_ids(pname, high)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 246, in find_sls_ids
    if item['__sls__'] == sls:
TypeError: list indices must be integers, not unicode
```

### Steps to Reproduce Issue
see above

### Versions Report
Master:
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan 31 2018, 02:12:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.20.1.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final

Minion:
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

Thanks,

Martin

### PR DESCRIPTION
**Pull request by terminalmage**
This causes a traceback in `salt.state.find_sls_ids()` as it expects the high chunks to all be dicts, but the excludes are a list of excluded SLS targets.

Resolves #47182.

### CODE REVIEW

**Review by cachedout — APPROVED** [review]

**Comment by jeffdyke** [comment]
Hello.  Is there a reason that this is not in 2018.3.2?  I'm running into the same issue.

Thanks

**Comment by gtmanfred** [comment]
@jeffdyke because it was merged into 2017.7 after the release branches had already been branched.  It will be in 2018.3.3.

Once release branches are branched, we focus on getting stuff into those branches that are committed for that release, and everything else has to wait for the next release, so that we have a chance at making sure the tests are stable for the release.

**Comment by jeffdyke** [comment]
Thank you @gtmanfred, this is kind of a big deal for me, how far out is 2018.3.3?  As i'll patch all minions, if its going to be a while.   I was confused b/c 2018.3.2 was released after 2017.7.7

Appreciate the quick response.

**Comment by gtmanfred** [comment]
2018.3.3 is branched, we are working on getting it out this month.

**Comment by jeffdyke** [comment]
again thanks for the quick response @gtmanfred. Just to give a reason why this is important to me, is that I can use it for configuration compliance.  Nothing changes on our servers without salt and i like to be able to prove that.

Thanks again.

**Pull request merged**
