### PR TITLE
Add +X capability to linux_acl

### PR DESCRIPTION
**Pull request by corybolar**
### What does this PR do?
Adds capability to linux_acl to understand the 'X' permission bit.  A capital X indicates that the executable bit should only be set if the executable bit is already set for another user.
### What issues does this PR fix or reference?
#33921 and #39112

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Review by Ch3LL — CHANGES_REQUESTED** [review]
Can you please write a regression test?

**Comment by sagetherage** [comment]
@corybolar please rebase this against the master branch and let us know if you need help with writing test cases

**Comment by sagetherage** [comment]
Reviewed in Grooming 2021-APR-05 considering closing

**Comment by sagetherage** [comment]
@corybolar this needs test cases written and we are no longer taking changes against `develop` and therefore would need to be rebased against `master` - if you are no longer willing to do this work, we will consider closing this PR

**Comment by sagetherage** [comment]
@corybolar this needs test cases written and we are no longer taking changes against develop and therefore would need to be rebased against master. It has been 2 weeks and we haven't heard from you -- closing this PR. Please mention me if anything changes.

**Pull request closed without merging**
