### PR TITLE
add option for syndics to forward all events to all masters

### PR DESCRIPTION
**Pull request by tsaridas**
### What does this PR do?
Adds a configuration option to forward events to all masters connected to the syndics.

### Previous Behavior
Events were forwarded to random/sorted master

### New Behavior
User can choose to forward events to all masters.

### Tests written?

No

### CODE REVIEW

**Comment by cachedout** [comment]
Thanks for this @tsaridas 

I would like @DmitryKuzmenko to look at this.

Also, since this is a new feature I would like to move this over to the develop branch. We reserve the release branches for bug fixes only.

**Comment by DmitryKuzmenko** [comment]
@cachedout looks good for me!
@tsaridas thank you!

**Comment by cachedout** [comment]
@tsaridas I see you tried to change this to the develop branch but then changed it back. Was there a problem? If you'd like to open a new PR instead of this one, that's fine too. Once we get this on the right branch, I will get it in. Thanks.

**Comment by tsaridas** [comment]
closed in favour of https://github.com/saltstack/salt/pull/38086

**Pull request closed without merging**
