### PR TITLE
Reenable the pkg states integration tests

### PR DESCRIPTION
**Pull request by asomers**
Many of these tests were accidentally being skipped, because the pkg
module's commands are spelled slightly differently than the pkg state's
commands, and the tests were checking the wrong names.

Also, this commit fixes an undefined variable exception in
test_pkg_015_installed_held that happened on most operating systems.

### What does this PR do?
Reenables most of the pkg state integration tests

### What issues does this PR fix or reference?
None

### Previous Behavior
Most of the pkg state integration tests would be skipped in all environments.

### New Behavior
Those tests will once again be run.

### Tests written?
No

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by waynew** [comment]
Looks like there are several failures across the platforms. @asomers would you be willing/able to look into those?

**Comment by asomers** [comment]
Failure analysis:
1) ci/py2/amazon1: This test needs to be adapted for amazon1, where bash-completion is not available.  What OS is "amazon", anyway?
2) ci/py2/fedora30: It looks like the test needs to be adapted to Fedora.  An extra package needs to be installed (python2-dnf-plugin-versionlock) to use pkg.hold.
3) ci/py3/centos8: It seems that distro.LinuxDistribution().like() is returning something unexpected, as called on line 558.
4) ci/py*/macosxmojave: this looks like a genuine bug in the mac_brew_pkg module.  But I can't debug it, as I don't have a Mac.
5) ci/py*/opensuse15: It seems that distro.LinuxDistribution().id() is returning something unexpected at line 72.

With difficulty I can probably fix the opensuse, centos8, and fedora30 failures.  But I'm going to need more information regarding amazon, and there's nothing I can do about macosxmojave.  What would you like me to do about those two?

**Comment by asomers** [comment]
The latest test failures:
* ci/lint: trivial whitespace issue.  I'll fix it.
* ci/py2/amazon1: same error about bash_completion being unavailable.  I need more information to fix this.  What is "amazon1", anyway?  How can I get an instance myself?
* ci/py*/fedora*: sigh.  This works on my local VM.  I'll need help to create a VM identical to what CI uses.
* ci/py*/macosxmojave: Again, this is a bug in the mac_brew_pkg module.  I cannot debug it.
* ci/py*opensuse15: available packages have changed; the test must be updated
* ci/py3/centos7/tcp: this looks like a spurious error unrelated to my changes
* ci/py3/centos8: I don't understand what's going on here.  It looks like pkg.installed is returning 1 even though the package is indeed installed.  Might be a bug in the yumpkg module
* ci/py3/windows2019: this failure is unrelated to my changes.

**Comment by waynew** [comment]
@asomers I know at least some of the issues should be resolved on `master` now. We had some infrastructure problems on amazon1 (that's AWS's linux distro that's going away this summer. Amazon 2 is the successor).

Go ahead and rebase on master (and maybe fix the lint issue) and let's see where we are. I, or one of the core team, could help with testing some stuff on mac if there's still an issue there.

**Comment by asomers** [comment]
Rebased and squashed.  It turns out that almost everything from this PR had been independently fixed by another.

**Comment by waynew** [comment]
Looks like things are better - I just went ahead and re-built the centos6 job. Failures didn't look related to this at all, I suspect flakiness. I guess we'll see.

**Comment by asomers** [comment]
@waynew it looks like the centos6 tests passed this time.

**Review by waynew — DISMISSED** [review]

**Comment by waynew** [comment]
@asomers awesome! Not sure if we'll put this in on 3000.1 or Sodium, but we'll get this in.

**Review by Akm0d — DISMISSED** [review]

**Review by dwoz — APPROVED** [review]

**Pull request merged**
