### PR TITLE
Backport #43116 to 2016.11

### PR DESCRIPTION
**Pull request by lomeroe**
### What does this PR do?
Backports #43116 to 2016.11

also corrects a few calls to salt.utils.files.fopen, replacing them with salt.utils.fopen (2016.11 only has salt.utils.fopen)

### What issues does this PR fix or reference?
#42279 

### Previous Behavior
ADMX policies which had the same "id" property in ADMX xml files could not be properly configured.

### New Behavior
ADMX policies with the same "id" property in ADMX can be set.

### Tests written?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Review by twangboy — APPROVED** [review]

**Comment by lomeroe** [comment]
@cachedout @rallytime @twangboy please hold on merging this, I just found an issue where some policies are not being properly configured after this change.  The same issue affects #43166.  I haven't gone back to test the changes in develop (#43116) but will start my tests from scratch again and figure out where I broke down.

This PR and #43166 also fix an issue (no formal issue filed, b/c I discovered it while making these changes) that was introduced by #42795 (for 2016.11) and #42794 (for 2017.7) where changes to salt.utils (salt.utils.fopen moving to salt.utils.files.fopen) where inadvertently backported from develop.  Those changes are relatively simple, so I am open to backing out #43166, and starting with a PR to fix that and then move back to this issue, to make things a little cleaner -- totally up to you.

**Comment by twangboy** [comment]
@rickh563 I believe the most recent commit (https://github.com/saltstack/salt/pull/43154/commits/8f593b0b025d91e84d951701a7e3541ed0539234) will fix issue ZD-1542.

**Comment by rallytime** [comment]
@lomeroe Is this ready to go now, pending the latest test run?

**Comment by lomeroe** [comment]
@rallytime yes, it should be good now

**Pull request merged**
