### PR TITLE
file.serialize: Fix serialize-merging lists (#41209)

### LINKED ISSUE #41209: file.serialize JSON w/merge_if_exists fails if top-level is not a dict
### Description of Issue/Question
`file.serialize` has the `merge_if_exists` option.
When serializing to JSON, it apparently assumes the top level to be a `dict`. 
While this is of course extremely common, it's not always true, and when it's not, the serializer crashes.

### Steps to Reproduce Issue
SLS:
```
my-json-list:
  file.serialize:
    - name: /tmp/list.json
    - formatter: json
    - merge_if_exists: True
    - dataset:
        - tea
        - pot
```

```
# cat /tmp/list.json
[  "tea", "kettle" ]
```

```
          ID: my-json-list
    Function: file.serialize
        Name: /tmp/list.json
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1746, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1704, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 5144, in serialize
                  merged_data = salt.utils.dictupdate.merge_recurse(existing_data, dataset)
                File "/usr/lib/python2.7/dist-packages/salt/utils/dictupdate.py", line 82, in merge_recurse
                  return update(copied, obj_b, merge_lists=merge_lists)
                File "/usr/lib/python2.7/dist-packages/salt/utils/dictupdate.py", line 35, in update
                  raise TypeError('Cannot update using non-dict types in dictupdate.update()')
              TypeError: Cannot update using non-dict types in dictupdate.update()
     Started: 11:32:11.537613
    Duration: 3.339 ms
     Changes:   
```

### Versions Report
```
Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.10.0-20-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

### PR DESCRIPTION
**Pull request by The-Loeki**
### What does this PR do?
Fix  #41209

### What issues does this PR fix or reference?
 #41209

### CODE REVIEW

**Review by isbm — CHANGES_REQUESTED** [review]
While the fix is obvious, yet I am not sure this is the right place for this. You are merging a data to an existing data. Why would not we have  something like `salt.utils.dictupdate.merge_data` which consists of this exact logic? I am sure we will have another place for similar situation. Having one function for this would save another potential bugs.

Then you would just:

```python
merged_data = salt.utils.dictupdate.merge_data(existing_data, dataset)
```

And please provide a unit test for this. Thanks!

**Comment by The-Loeki** [comment]
@isbm another option would have been to use `salt.utils.dictupdate.merge(strategy='list') maybe.

& personally I'd be in favour of one single deepmerger as you suggest, but IMHO dictupdate.merge with a tweak or 2 is already that. Except it sits in `dictupdate`.

**Comment by isbm** [comment]
Yeah, `dictupdate` already suggests a type. We might change that too, but that's not really a problem right now. Strategy?.. :confused: Seems you do not understand my point: you _do not know_ the strategy or logic behind, because you just toss in a data to a merger. And it by its own should figure out what algorithm to apply: list/tuple or dict/set. If we add another hashable object, it should go again there, instead of be all around the place, wrapped by `if ... else...` clauses.

**Comment by The-Loeki** [comment]
I saw your point and I'm not disagreeing with it ;)
What I meant was the `stragegy=list` is already in that particular function; the tweak or 2 I mentioned would basically boil down to something along the lines of 

```
if strategy == 'smart':
  if isinstance(obj_a, (list, tuple)): 
    merge_list()
  elif isinstance(obj_a), HashMapping):
   merge_dict()
```

aside from the confusing namespace `salt.utils.dictupdate` that would already to the trick for the `merge()` function right there.

**Comment by isbm** [comment]
You're not gonna need it. We already have `merge_<foo>`, so once you want `strategy="stupid"` just use `if/else` directly. :wink:

**Comment by cachedout** [comment]
+1 to the suggestion of using a utility function for this.

**Pull request closed without merging**
