### PR TITLE
Configure logging for ZMQ PubServer daemon

### PR DESCRIPTION
**Pull request by dwoz**
### What does this PR do?

Configure logging for ZMQ PubServer daemon.

### Previous Behavior

We were not getting logs from the PubServer daemon in the master's log file.

### New Behavior

The master log file will contain PubServer logs

### Tests written?

No

### Commits signed with GPG?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by rallytime — APPROVED** [review]
Very nice!

I definitely want some other people to look at this that in the review list though.

**Review by s0undt3ch — APPROVED** [review]
Solid!

**Comment by dwoz** [comment]
This doesn't seem to work on windows.

**Comment by dwoz** [comment]
With the last few commits we are getting the logs on all platforms (including windows).

**Pull request merged**
