### PR TITLE
Fix improper exception raises (2018.3)

### PR DESCRIPTION
**Pull request by terminalmage**
This is not logging, printf-style expansion is not performed

### CODE REVIEW

**Review by garethgreenaway — APPROVED** [review]

**Comment by terminalmage** [comment]
I found some more incorrect exception raising, I may add to this PR. Marking as `Pending Changes`.

**Comment by dwoz** [comment]
@terminalmage These test failures look to be related:
https://jenkinsci.saltstack.com/job/pr-kitchen-ubuntu1604-py3/job/PR-51097/6/

**Comment by terminalmage** [comment]
@dwoz The test was incorrectly written, it was confirming that the raised exception contained a `%s` in it instead of the key name.

**Comment by terminalmage** [comment]
It has been fixed.

**Pull request merged**
