### PR TITLE
WIP: Allow for column-level privileges

### PR DESCRIPTION
**Pull request by ixs**
###What does this PR do?
This patch modifies the tokenizer appropriately to take column-level
privileges into account.

### What issues does this PR fix or reference?
The mysql grants module currently is able to deal with full grants
such as GRANT SELECT ON DATABASE.TABLE.
When defining a column-level specific grant such as GRANT SELECT
(Column1, Column2), INSERT (Column3) ON DATABASE.TABLE the module fails
as the grants are not tokenized correctly.

### Tests written?
No. I was unsure how to best extend the existing tests for the mysql_grants module. I'd really appreciate if someone who knows the test suite better could have a look and give me a few hints.

### CODE REVIEW

**Comment by Ch3LL** [comment]
probably a good place to start is at this file: tests/unit/modules/test_mysql.py and write a unit test for the `_grant_to_tokens` function there. 

There are also integration tests here: `tests/integration/modules/test_mysql.py` where you can add a test as well. Let me know if you need more direction :)

**Comment by sagetherage** [comment]
@ixs please rebase this against the master branch

**Review by Ch3LL — CHANGES_REQUESTED** [review]
any chance you will have time to come back to write tests? any more direction i can give you?

**Comment by ixs** [comment]
@Ch3LL Absolutely planning on doing this _but_ I found out it's not just the tests. I had gotten a few assumptions incorrect, so that means some code changes are needed.

I'll see if I can find a bit of time during the next few days to have another shot at this.

**Comment by ixs** [comment]
Did not get around to it but it looks like https://github.com/saltstack/salt/pull/55980 is a duplicate and got merged.

Closing this.

**Pull request closed without merging**
