### PR TITLE
Modularise eauth token storage and authentication

### PR DESCRIPTION
**Pull request by kunal-bajpai**
### What does this PR do?
Modularises the methods salt.auth.Loadauth.mk_token and salt.auth.Loadauth.get_token so that tokens can be stored in a variety of stores like filesystem, redis, etc.

### What issues does this PR fix or reference?
Fixes issue #42661 

### Previous Behavior
Eauth tokens were written only to filesystem of the master

### New Behavior
Eauth tokens can be written to filesystem, redis or any other modules that are added in future.

### Tests written?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by kunal-bajpai** [comment]
@whiteinge @gtmanfred any update for this?

**Comment by kunal-bajpai** [comment]
@cachedout can you look at the Jenkins failure? Root cause of all failures is the same Junos test module and you have made the most recent commit to the line causing the issue
```File "/usr/lib/python2.7/site-packages/jnpr/junos/utils/sw.py", line 87, in __init__
            'localre' in dev.facts['current_re'])
        TypeError: argument of type 'NoneType' is not iterable```

**Comment by kunal-bajpai** [comment]
@gtmanfred @whiteinge Jenkins is mostly ok except for build which is failing because of no apparent reason. Please review this. We are blocked on this PR.

**Comment by gtmanfred** [comment]
Those tests are all passing. the default one just gathers all the other results and sometimes fails

**Comment by whiteinge** [comment]
> Please review this. We are blocked on this PR.

I've read over the code in the PR and it looks good at first glance. Since this is a big change that touches a fairly central part of Salt it is best to have a few people weigh in here. I will pull this down locally and run it through a few paces today and tomorrow. Others tagged on the review should do the same as they can find time this week.

Very cool change! This will benefit many people. 😀

**Comment by kunal-bajpai** [comment]
Thank you @gtmanfred and @whiteinge!

**Review by DmitryKuzmenko — APPROVED** [review]
Looks good to me.

**Comment by kunal-bajpai** [comment]
@gtmanfred can we close this asap?

**Review by whiteinge — APPROVED** [review]
I gave this a local smoke-test and did not see any regressions.

**Comment by cachedout** [comment]
@kunal-bajpai We are waiting to have this reviewed by @thatch45. He is out of the office this week but after he returns we'll get that review done and then we'll hopefully get this in. Thanks for your patience.

**Review by thatch45 — APPROVED** [review]
Very well done @kunal-bajpai ! I think you may be the only non-saltstack employee to add a loader interface to Salt!

**Review by gtmanfred — CHANGES_REQUESTED** [review]
The one thing that does need to be added for this is a `saltutils.eauth_tokens` runner module to sync them from the filecache so that custom ones can be loaded.

**Comment by kunal-bajpai** [comment]
Thank you, @thatch45 ! @gtmanfred added the runner and also replaced some code that relied on localfs tokens in `salt.daemons.masterapi.clean_expired_tokens`. Please take a look.

**Review by gtmanfred — APPROVED** [review]

**Comment by dOpsCoder** [comment]
Curious if this can be added to an upcoming release. This can be an important feature for horizontally scaling salt masters in multi-master scenarios.

**Comment by gtmanfred** [comment]
It won't be in until the next major release called oxygen.

**Pull request merged**
