### PR TITLE
Fix for issue #25016

### PR DESCRIPTION
**Pull request by martinhoefling**
Remove iteration over returned minions which is done a couple of lines before in the same function.

### CODE REVIEW

**Comment by martinhoefling** [comment]
The failed build seems to be a jenkins / ssh issue.

**Comment by martinhoefling** [comment]
Can sb. take a look into the failures? They seem to be unrelated to the commit.

**Comment by jfindlay** [comment]
@martinhoefling, thanks for the fix.  Next time you are welcome to submit fixes directly to the oldest supported release branch, see https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

**Comment by martinhoefling** [comment]
On 28.06.15 00:47, Justin Findlay wrote:
> @martinhoefling, thanks for the fix.  Next time you are welcome to submit fixes directly to the oldest supported release branch, see https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

Damn! Forgot about that...

Best wishes

Martin

**Comment by jfindlay** [comment]
No problem, thanks for your work on this.

**Pull request merged**
