### PR TITLE
fix grains['virtual_subtype'] to show Docker on xen kernels

### LINKED ISSUE #46754: grain item virtual_subtype shows 'Xen PV DomU' on Docker containers
### Description of Issue/Question
Bug with _grains.item virtual_subtype output shows 'Xen PV DomU' in **Docker** containers running on Xen kernels like EC2 instances/Fargate. Expected output should be **Docker**, code was already in place but that variable is getting overwritten into 'Xen PV DomU'

### Setup

```
#salt-call --local grains.item virtual_subtype
local:
    ----------
    virtual_subtype:
        Xen PV DomU
```
```
# cat /proc/1/cgroup
11:pids:/docker/b1b955d0ecb2c31*******
10:memory:/docker/b1b955d0ecb2c31*******
9:freezer:/docker/b1b955d0ecb2c31*******
8:devices:/docker/b1b955d0ecb2c31*******
7:cpuset:/docker/b1b955d0ecb2c31*******
6:blkio:/docker/b1b955d0ecb2c31*******
5:hugetlb:/docker/b1b955d0ecb2c31*******
4:net_cls,net_prio:/docker/b1b955d0ecb2c31*******
3:perf_event:/docker/b1b955d0ecb2c31*******
2:cpu,cpuacct:/docker/b1b955d0ecb2c31*******
1:name=systemd:/docker/b1b955d0ecb2c31*******
```

Expected Output:
```
#salt-call --local grains.item virtual_subtype
local:
    ----------
    virtual_subtype:
        Docker
```

### Steps to Reproduce Issue
1. Install docker/docker-ce in any xen kernel based AWS ec2 instances or on virtual machines hosted with Xen hypervisor.
2. Run any generic linux container(centos/debian/ubuntu) from the Docker host(docker installed in step.1).
3. Install salt-minion in the newly initiated container.
3. Execute `salt-call --local grains.item virtual_subtype`

### Versions Report
```
# salt-minion -V
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.15.13-coreos
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

### PR DESCRIPTION
**Pull request by nages13**
Fixes #46754 & #43405

### What does this PR do?
Shows proper virtual_subtype as Docker for salt minions running on Docker containers based out of xen hypervisor.

### What issues does this PR fix or reference?
Moved down LXC & Docker discovery after Xen discovery in the salt.grains.core file.

### Previous Behavior
Output on Docker containers - grains['virtual_subtype'] = Xen PV DomU / Xen Dom0

### New Behavior
grains['virtual_subtype'] =Docker

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by rallytime — APPROVED** [review]
Hi @nages13 and welcome! Thanks for submitting this and apologies for the late review. This LGTM, but I'd like @terminalmage to review this as well.

**Review by terminalmage — COMMENTED** [review]
I would prefer a comment mentioning that the Docker detection should be below the hypervisors so that it is not overwritten.

**Comment by cachedout** [comment]
@nages13 Did you see the above feedback from @terminalmage ?

**Comment by nages13** [comment]
@cachedout Yes, currently I was in process of updating the PR with new commit and comments in place.
Can i submit new PR against 2018.3 version too?

**Review by terminalmage — APPROVED** [review]

**Comment by rallytime** [comment]
@nages13 Welcome and thanks for submitting this fix

**Pull request merged**
