### PR TITLE
add functions for detecting changed USE flags

### PR DESCRIPTION
**Pull request by batulin-s**
Add functions for detecting difference of USE flags for installed package and into /etc/portage/package.use

### CODE REVIEW

**Comment by batulin-s** [comment]
salt '*' portage_config.get_cleared_flags www-servers/varnish-4.0.3
|_
      - jemalloc
      - python_targets_python2_7
      - python_targets_python3_3
    |_
      - jemalloc
      - jit
      - python_targets_python2_7
      - python_targets_python3_3

**Comment by batulin-s** [comment]
I've changed arguments for new functions - now it takes name of package in format category/package, instead of category/package-version. Now 
salt '*' portage_config.get_cleared_flags www-servers/varnish
|_
      - jemalloc
      - python_targets_python2_7
      - python_targets_python3_3
    |_
      - jemalloc
      - jit
      - python_targets_python2_7
      - python_targets_python3_3
and

salt 'testsalt*' portage_config.is_changed_uses www-servers/varnish
testsalt.sergey:
    True

**Comment by batulin-s** [comment]
I can't understand, are the checks fails caused by my mistake? @jfindlay, could you please help me with it? I don't know, what i need to do for avoiding the failing checks.

**Comment by rallytime** [comment]
It appears that the failure reported in the pylint test is unrelated as the file referenced for the failure was not one that you've changed.

However, it would be awesome if you could add a version added declaration to any of the new public functions that you've added here. Basically, `.. versionadded:: Beryllium` should be added in the docstring describing the new functions.

**Comment by batulin-s** [comment]
Thank you, @jfindlay, @rallytime !

**Pull request merged**
