### PR TITLE
Make boto util get_error function compatible with newer boto modules

### PR DESCRIPTION
**Pull request by ryan-lane**
May want to check with @mgwilliams before merging.

### CODE REVIEW

**Comment by mgwilliams** [comment]
Aside from the failing tests, the approach looks good to me.

**Comment by jfindlay** [comment]
@ryan-lane, would you mind updating the unit tests?  Thanks.

**Comment by ryan-lane** [comment]
I think this needs a bit more work than just changing the unit tests. I need to push in changes.

**Comment by jfindlay** [comment]
Thanks for working on this, @ryan-lane.

**Comment by ryan-lane** [comment]
Hm. Is this a failure in the tests? Not totally sure what's wrong here.

**Comment by jfindlay** [comment]
Jenkins has been having some issues lately.

**Comment by ryan-lane** [comment]
Can the tests be re-run?

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by ryan-lane** [comment]
Fixed the last lint error and the rest of the test failures look unrelated :)

**Comment by ryan-lane** [comment]
Anything I need to do to get this one merged in? It's needed for boto_kms to properly work.

**Comment by rallytime** [comment]
Nah, just busy over here. I'll get it right now. :)

**Comment by ryan-lane** [comment]
\o/ Thanks!

**Pull request merged**
