### PR TITLE
Correct reset locale in cmd.run

### PR DESCRIPTION
**Pull request by AstraLuma**
### What does this PR do?
Intelligently set the locale in `cmd` to preserve encoding information.

### What issues does this PR fix or reference?
#42518

### Previous Behavior
Unconditionally set the locale to `C`, erasing system encoding information (including especially the filesystem).

### New Behavior
Preserves any set encoding while still setting the language to `C`.

### Tests written?

Could not find existing tests for cmd.run that this would go with.

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by astronouth7303** [comment]
Ok, I have no idea why windows broke.

I'll look into the linux tests, though.

**Review by s0undt3ch — DISMISSED** [review]

**Comment by s0undt3ch** [comment]
We should try and get tests for this. I know plain `C` works but of the system doesn't have, for example `C.UTF-8` what happens?

**Comment by astronouth7303** [comment]
It should use whatever encoding is declared. It doesn't hardcode an encoding, just forwards it.

**Review by twangboy — DISMISSED** [review]

**Comment by twangboy** [comment]
@dmurphy18 Hey, is this related to the language code stuff you were working on?

**Review by dmurphy18 — CHANGES_REQUESTED** [review]
This needs to be merged up to the master branch and have some tests associated with it, esp. given some Containers and platforms do not have C.UTF-8 for example: see PEP 538 and PEP540. Noting that this will be going into the Sodium release at a minimum at this point, where these PEP's have been back-ported to Python 3.6. Some environments only provide 'C' and POSIX, and would want to ensure that these changes work in those environments.

**Comment by astronouth7303** [comment]
What should happen is that it'll preserve the encoding of the environment.

For example, if the system is `en_US`, it should change it to `C`. If it's `en_US.UTF-8`, it'll change it to `C.UTF-8`.

I think what happened at the time was that it was declared as a UTF-8 locale without having it installed?

**Comment by astronouth7303** [comment]
But yeah, this PR needs a refresh.

**Comment by sagetherage** [comment]
@AstraLuma do you want to rebase this against the `master` branch or close it and base a new PR on this one against `master`?

**Comment by AstraLuma** [comment]
A wild necromancer appears!

I can attempt to rebase it, but I haven't really thought about this code since I wrote it.

**Comment by AstraLuma** [comment]
> Some environments only provide 'C' and POSIX, and would want to ensure that these changes work in those environments.

This should work fine in environments without UTF-8 locales installed--it only preserves the encoding in the declared locale. As written, though, it'll cause a problem if your system is declared `en_US.UTF-8` but you don't have `C.UTF-8` installed. (Which, I would argue, is a pretty unfortunate circumstance that could lead to other problems if you actually have to use unicode >127.)

**Comment by AstraLuma** [comment]
Oh, and to add insult to injury: the `locale` module doesn't provide a way to probe if a locale exists without trying to set it and seeing if it works. Given [the description](https://docs.python.org/3/library/locale.html#background-details-hints-tips-and-caveats) of locales, I would say that this method is a Bad Idea.

**Comment by AstraLuma** [comment]
it does look like there's `cmd.run` tests now, so I'll have to remember to look into that. (Between my other stuff.)

**Comment by AstraLuma** [comment]
it does look like there's `cmd.run` tests now, so I'll have to remember to look into that. (Between my other stuff.)

**Comment by Ch3LL** [comment]
@AstraLuma are you willing to come back to this PR and follow up with @dmurphy18 's feedback about test coverage?

**Review by dmurphy18 — CHANGES_REQUESTED** [review]
@AstraLuma This PR is marked pending-close since unresponsive, if you have lost interested in this PR please let us know, else can you give an estimate as to when you will address the failing tests ?

**Comment by Ch3LL** [comment]
Closing due to inactivity. Please let me know if you want me to re-open or please submit a PR against the master branch with the requested changes.

**Pull request closed without merging**
