### PR TITLE
Fix some autodoc import warnings from building docs

### PR DESCRIPTION
**Pull request by rallytime**
Refs #30816

### CODE REVIEW

**Comment by tonybaloney** [comment]
@rallytime is there a build/CI dashboard where I can check the docs and stuff? it 'looks' like a skinned RTD but as a total nobody I can't kick the build :-)

**Comment by rallytime** [comment]
@tonybaloney I just doubled checked with our docs team lead, and the docs only build every night on the live server, not every hour. (I had that wrong in another comment to you.)

If you want to look at your changes on your own before waiting for them build overnight, you can build them yourself and serve them up locally very easily. Make sure you have this PR in your develop branch, and then follow [these instructions](https://docs.saltstack.com/en/develop/topics/development/conventions/documentation.html#building-the-documentation).

**Comment by tonybaloney** [comment]
ah ok. I'll be patient. thanks @rallytime I deleted my branch now. everyone at saltstack seems to be skiing in their photos!

**Comment by rallytime** [comment]
Haha well, it's snowy here! :)

**Pull request merged**
