### PR TITLE
[WIP] state pkg.latest always uses pkg.install pkg={[pkgname: version], ...}

### PR DESCRIPTION
**Pull request by damon-atkins**
### What does this PR do?
state pkg.latest always uses `pkg.install pkg=[{pkgname: version}, ...]`

### What issues does this PR fix or reference?
#47484 `Windows: pkg.latest state not updating packages`
The fix applied to 2017.7.6 and 2018.3.1 only used `pkg.install pkg={[pkgname: version], ...}` for windows otherwise it was `pkg=[pkgname, ...]`

### Previous Behavior
Used `pkg.install pkg=[{pkgname: version}, ...]` for windows otherwise it was `pkg=[pkgname, ...]`

### New Behavior
Use `pkg.install pkg=[{pkgname: version}, ...]` for all platforms/pkg execution modules.

### Tests written?

Existing

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by brejoc — APPROVED** [review]
lgtm

**Review by isbm — APPROVED** [review]

**Comment by damon-atkins** [comment]
The first run of the test did not pickup any pkg issue. However it was hard determine if in fact it reach these unit tests. And that the test environment just fell over. Try again.
Go Go Jenkins!

**Comment by damon-atkins** [comment]
Go Go Jenkins!

**Comment by damon-atkins** [comment]
Go Go Jenkins!

**Comment by damon-atkins** [comment]
@rallytime Why are these tests failling?

**Comment by rallytime** [comment]
It looks like you've restarted them quite a bit, so I can't see until they finish running. Once I have a full test run, we can see what's failing and if it's related. We have some upstream test failures that we're working on resolving.

**Comment by damon-atkins** [comment]
From https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/19384/consoleFull
Hi @sjorge FYI
```
15:56:11  * Starting salt-master ... 15:56:11,503 [salt.loader                              :767 ][CRITICAL] Failed to load grains defined in grain file zfs.zfs in function <function zfs at 0x7f3f47f85320>, error:
15:56:11 Traceback (most recent call last):
15:56:11   File "/testing/salt/loader.py", line 760, in grains
15:56:11     ret = funcs[key](**kwargs)
15:56:11 TypeError: zfs() takes no arguments (1 given)
15:56:11 15:56:10,552 [salt.loader                              :767 ][CRITICAL] Failed to load grains defined in grain file zfs.zfs in function <function zfs at 0x7fe328c1ca28>, error:
15:56:11 Traceback (most recent call last):
15:56:11   File "/testing/salt/loader.py", line 760, in grains
15:56:11     ret = funcs[key](**kwargs)
15:56:11 TypeError: zfs() takes no arguments (1 given)
15:56:12 15:56:11,762 [salt.loader                              :767 ][CRITICAL] Failed to load grains defined in grain file zfs.zfs in function <function zfs at 0x7f3f47def398>, error:
15:56:12 Traceback (most recent call last):
15:56:12   File "/testing/salt/loader.py", line 760, in grains
15:56:12     ret = funcs[key](**kwargs)
15:56:12 TypeError: zfs() takes no arguments (1 given)
15:56:12 15:56:12,047 [salt.loader                              :767 ][CRITICAL] Failed to load grains defined in grain file zfs.zfs in function <function zfs at 0x7f3f47e1c2a8>, error:
15:56:12 Traceback (most recent call last):
15:56:12   File "/testing/salt/loader.py", line 760, in grains
15:56:12     ret = funcs[key](**kwargs)
15:56:12 TypeError: zfs() takes no arguments (1 given)
15:56:12 15:56:12,300 [salt.loader                              :767 ][CRITICAL] Failed to load grains defined in grain file zfs.zfs in function <function zfs at 0x7f3f47d44410>, error:
15:56:12 Traceback (most recent call last):
15:56:12   File "/testing/salt/loader.py", line 760, in grains
15:56:12     ret = funcs[key](**kwargs)
15:56:12 TypeError: zfs() takes no arguments (1 given)
15:56:12 

 * Starting salt-syndic ... STARTED!
15:57:44 15:57:43,826 [salt.minion                                :2991][ERROR   ] Unable to call _fire_master on localhost, that syndic is not connected
15:57:44 15:57:43,826 [salt.minion                                :3005][CRITICAL] Unable to call _fire_master on any masters!
15:57:44 15:57:43,884 [salt.utils.minions                         :110 ][ERROR   ] Failed nodegroup expansion: unknown nodegroup "mins"
15:57:44 15:57:43,885 [salt.utils.minions                         :110 ][ERROR   ] Failed nodegroup expansion: unknown nodegroup "missing_minion"
15:57:44 15:57:43,886 [salt.minion                                :3456][ERROR   ] Invalid compound target: N@missing_minion for results: 
```

**Comment by damon-atkins** [comment]
From https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu16-py3/10299/consoleFull

```
16:35:13 ----------------------------------------------------------------------
16:35:13   test_cmd_async (integration.wheel.test_client.WheelModuleTest)
16:35:13 [CPU:53.3%|MEM:24.8%]  ... OK (0.037s)
16:35:14   test_cmd_sync (integration.wheel.test_client.WheelModuleTest)
16:35:14 [CPU:0.0%|MEM:25.3%] 16:35:13,660 [salt.utils.process                  :772 ][ERROR   ] An un-handled exception from the multiprocessing process 'SignalHandlingMultiprocessingProcess-2' was caught:
16:35:14 Traceback (most recent call last):
16:35:14   File "/testing/salt/utils/process.py", line 765, in _run
16:35:14     return self._original_run()
16:35:14   File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
16:35:14     self._target(*self._args, **self._kwargs)
16:35:14   File "/testing/salt/client/mixins.py", line 481, in _proc_function
16:35:14     salt.utils.process.daemonize()
16:35:14   File "/testing/salt/utils/process.py", line 106, in daemonize
16:35:14     os.dup2(dev_null.fileno(), sys.stdout.fileno())
16:35:14 io.UnsupportedOperation: fileno
16:35:14 Process SignalHandlingMultiprocessingProcess-2:
16:35:14 Traceback (most recent call last):
16:35:14   File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
16:35:14     self.run()
16:35:14   File "/testing/salt/utils/process.py", line 765, in _run
16:35:14     return self._original_run()
16:35:14   File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
16:35:14     self._target(*self._args, **self._kwargs)
16:35:14   File "/testing/salt/client/mixins.py", line 481, in _proc_function
16:35:14     salt.utils.process.daemonize()
16:35:14   File "/testing/salt/utils/process.py", line 106, in daemonize
16:35:14     os.dup2(dev_null.fileno(), sys.stdout.fileno())
16:35:14 io.UnsupportedOperation: fileno
16:35:14  ... OK (0.259s)

16:35:20 [CPU:0.0%|MEM:24.8%] 16:35:20,568 [salt.loader                                          :767 ][CRITICAL] Failed to load grains defined in grain file zfs.zfs in function <function zfs at 0x7f7d24b1c6a8>, error:
16:35:20 Traceback (most recent call last):
16:35:20   File "/testing/salt/loader.py", line 760, in grains
16:35:20     ret = funcs[key](**kwargs)
16:35:20 TypeError: zfs() got an unexpected keyword argument 'grains'
16:35:21  ... OK (7.060s)
16:35:21   test_list_all (integration.wheel.test_key.KeyWheelModuleTest)
16:35:22 [CPU:0.0%|MEM:24.9%] 16:35:21,770 [salt.loader                                          :767 ][CRITICAL] Failed to load grains defined in grain file zfs.zfs in function <function zfs at 0x7f7d24b27ea0>, error:
16:35:22 Traceback (most recent call last):
16:35:22   File "/testing/salt/loader.py", line 760, in grains
16:35:22     ret = funcs[key](**kwargs)
16:35:22 TypeError: zfs() got an unexpected keyword argument 'grains'
16:35:22  ... OK (0.237s)

16:40:57 [DEBUG   ] Executing command: scp -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=72 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/tmp/salt-tests-tmpdir/config/salt_ssh_known_hosts -o Port=2827 -o IdentityFile=/tmp/salt-tests-tmpdir/config/key_test -o User=root  /tmp/__salt.tmp.iy1hpt72 127.0.0.1:/var/tmp/.b6f7c5/salt_state.tgz
16:40:57 [DEBUG   ] Child Forked! PID: 10924  STDOUT_FD: 15  STDERR_FD: 17
16:40:57 [DEBUG   ] Terminal Command: /bin/sh -c scp -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=72 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/tmp/salt-tests-tmpdir/config/salt_ssh_known_hosts -o Port=2827 -o IdentityFile=/tmp/salt-tests-tmpdir/config/key_test -o User=root  /tmp/__salt.tmp.iy1hpt72 127.0.0.1:/var/tmp/.b6f7c5/salt_state.tgz
16:40:57 [DEBUG   ] Performing shimmed, blocking command as follows:
16:40:57 state.pkg /var/tmp/.b6f7c5/salt_state.tgz test=None pkg_sum=9dd79a0324a071270dadc5504dd13f113e847d11f7ca67688476eddbe1d720b6 hash_type=sha256
16:40:57   File "/usr/lib/python3.5/site.py", line 182
16:40:57     file=sys.stderr)
16:40:57         ^
16:40:57 SyntaxError: invalid syntax
16:40:57 [ERROR   ] Unable to detect Python-2 version
16:40:57 [DEBUG   ] b''
16:40:57 [DEBUG   ] Adding module to the tops: "salt"
16:40:57 [DEBUG   ] Adding module to the tops: "jinja2"
16:40:57 [DEBUG   ] Adding module to the tops: "yaml"
16:40:57 [DEBUG   ] Adding module to the tops: "tornado"
16:40:57 [DEBUG   ] Adding module to the tops: "msgpack"
16:40:57 [DEBUG   ] Adding module to the tops: "certifi"
16:40:57 [DEBUG   ] Adding module to the tops: "salt.ext.ssl_match_hostname"
16:40:57 [DEBUG   ] Adding module to the tops: "markupsafe"
16:40:57 [DEBUG   ] Adding module to the tops: "salt.ext.backports_abc"
16:40:57 [ERROR   ] Failed collecting tops for Python binary python2.
16:40:57 [DEBUG   ] b'  File "/usr/lib/python3.5/site.py", line 182\n    file=sys.stderr)\n        ^\nSyntaxError: invalid syntax\n'

16:41:28 [INFO    ] Caching directory '_utils/' for environment 'base'
16:41:28 [DEBUG   ] Executing command: scp -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=72 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/tmp/salt-tests-tmpdir/config/salt_ssh_known_hosts -o Port=2827 -o IdentityFile=/tmp/salt-tests-tmpdir/config/key_test -o User=root  /tmp/__salt.tmp.6yz8w46p 127.0.0.1:/var/tmp/.66a4a4/salt_state.tgz
16:41:28 [DEBUG   ] Child Forked! PID: 11548  STDOUT_FD: 15  STDERR_FD: 17
16:41:28 [DEBUG   ] Terminal Command: /bin/sh -c scp -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=72 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/tmp/salt-tests-tmpdir/config/salt_ssh_known_hosts -o Port=2827 -o IdentityFile=/tmp/salt-tests-tmpdir/config/key_test -o User=root  /tmp/__salt.tmp.6yz8w46p 127.0.0.1:/var/tmp/.66a4a4/salt_state.tgz
16:41:28 [DEBUG   ] Performing shimmed, blocking command as follows:
16:41:28 state.pkg /var/tmp/.66a4a4/salt_state.tgz test=None pkg_sum=2bd19a013d55f8aa3dd028260b88f16272b39bff6ea0ea606847c84acf5a8b6d hash_type=sha256
16:41:28   File "/usr/lib/python3.5/site.py", line 182
16:41:28     file=sys.stderr)
16:41:28         ^
16:41:28 SyntaxError: invalid syntax
16:41:28 [ERROR   ] Unable to detect Python-2 version

16:42:00 state.pkg /var/tmp/.8630c6/salt_state.tgz test=None pkg_sum=c37256bfe80922f2fe774c1b93165a4b58098e7e617404f8e2919808e162af18 hash_type=sha256
16:42:00   File "/usr/lib/python3.5/site.py", line 182
16:42:00     file=sys.stderr)
16:42:00         ^
16:42:00 SyntaxError: invalid syntax
16:42:00 [ERROR   ] Unable to detect Python-2 version
16:42:00 [DEBUG   ] b''

16:42:16 [DEBUG   ] Terminal Command: /bin/sh -c scp -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=72 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/tmp/salt-tests-tmpdir/config/salt_ssh_known_hosts -o Port=2827 -o IdentityFile=/tmp/salt-tests-tmpdir/config/key_test -o User=root  /tmp/__salt.tmp.k2a4egxe 127.0.0.1:/var/tmp/.71afb8/salt_state.tgz
16:42:16 [DEBUG   ] Performing shimmed, blocking command as follows:
16:42:16 state.pkg /var/tmp/.71afb8/salt_state.tgz test=None pkg_sum=b41e812bf40ce9bfe6da08e361433a8d8f5b8587ba0c9f4479b06ca4e4446fed hash_type=sha256
16:42:16   File "/usr/lib/python3.5/site.py", line 182
16:42:16     file=sys.stderr)
16:42:16         ^
etc
17:05:32 17:05:32,593 [salt.utils.process                                   :772 ][ERROR   ] An un-handled exception from the multiprocessing process 'SignalHandlingMultiprocessingProcess-3' was caught:
17:05:32 Traceback (most recent call last):
17:05:32   File "/testing/salt/utils/process.py", line 765, in _run
17:05:32     return self._original_run()
17:05:32   File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
17:05:32     self._target(*self._args, **self._kwargs)
17:05:32   File "/testing/salt/client/mixins.py", line 481, in _proc_function
17:05:32     salt.utils.process.daemonize()
17:05:32   File "/testing/salt/utils/process.py", line 106, in daemonize
17:05:32     os.dup2(dev_null.fileno(), sys.stdout.fileno())
17:05:32 io.UnsupportedOperation: fileno

17:05:36 17:05:36,371 [salt.client                                          :1674][ERROR   ] Unable to connect to the salt master publisher at /tmp/salt-tests-tmpdir/tmpnvqdvr5p/sock_dir
```

**Comment by damon-atkins** [comment]
From https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-cent7-py3/5328/consoleFull

```
15:57:34   test_output_json (integration.output.test_output.OutputReturnTest)
15:57:38 [CPU:0.0%|MEM:11.1%] [CRITICAL] Failed to load grains defined in grain file matcher_grain.myfunction in function <function myfunction at 0x7f4525f5f400>, error:
15:57:38 Traceback (most recent call last):
15:57:38   File "/testing/salt/loader.py", line 760, in grains
15:57:38     ret = funcs[key](**kwargs)
15:57:38 TypeError: myfunction() got an unexpected keyword argument 'grains'

15:58:18   test_cache (integration.runners.test_cache.ManageTest)
15:58:24 [CPU:12.5%|MEM:12.0%]  ... 15:58:23,820 [salt.loader                         :767 ][CRITICAL] Failed to load grains defined in grain file zfs.zfs in function <function zfs at 0x7f1d9fcbfe18>, error:
15:58:24 Traceback (most recent call last):
15:58:24   File "/testing/salt/loader.py", line 760, in grains
15:58:24     ret = funcs[key](**kwargs)
15:58:24 TypeError: zfs() got an unexpected keyword argument 'grains'
15:58:24 15:58:24,246 [salt.loader                         :767 ][CRITICAL] Failed to load grains defined in grain file zfs.zfs in function <function zfs at 0x7f1d9fcbfea0>, error:
15:58:24 Traceback (most recent call last):
15:58:24   File "/testing/salt/loader.py", line 760, in grains
15:58:24     ret = funcs[key](**kwargs)
15:58:24 TypeError: zfs() got an unexpected keyword argument 'grains'

16:33:53 [DEBUG   ] Performing shimmed, blocking command as follows:
16:33:53 state.pkg /var/tmp/.f11017/salt_state.tgz test=None pkg_sum=036587347b3e573ef375b05edff06eab9757618a2a91e3a2c0fe40c0170f25cc hash_type=sha256
16:33:53   File "/usr/lib64/python3.4/site.py", line 176
16:33:53     file=sys.stderr)
16:33:53         ^
16:33:53 SyntaxError: invalid syntax
16:33:53 [ERROR   ] Unable to detect Python-2 version

16:35:26 [DEBUG   ] Performing shimmed, blocking command as follows:
16:35:26 state.pkg /var/tmp/.c4be05/salt_state.tgz test=None pkg_sum=9f012750b41156f346f25ec578ab9b4fda91bbf582a6366fed256aee3ec845f2 hash_type=sha256
16:35:26   File "/usr/lib64/python3.4/site.py", line 176
16:35:26     file=sys.stderr)
16:35:26         ^
16:35:26 SyntaxError: invalid syntax

18:29:13 [CPU:0.0%|MEM:15.5%]  ... OK (0.057s)
18:29:13   test_master_id_function (unit.config.test_config.ConfigTestCase)
18:29:13 [CPU:0.0%|MEM:15.5%] 18:29:10,861 [salt.loader                                               :767 ][CRITICAL] Failed to load grains defined in grain file zfs.zfs in function <function zfs at 0x7f1d9ba19bf8>, error:
18:29:13 Traceback (most recent call last):
18:29:13   File "/testing/salt/loader.py", line 760, in grains
18:29:13     ret = funcs[key](**kwargs)
18:29:13 TypeError: zfs() got an unexpected keyword argument 'grains'
18:29:13  ... OK (0.703s)

18:29:51 [CPU:14.0%|MEM:15.8%] /var/cache/salt/minion/extmods/modules/pacman.py:45: DeprecationWarning: Use of 'salt.utils.namespaced_function' detected. This function has been moved to 'salt.utils.functools.namespaced_function' as of Salt 2018.3.0. This warning will be removed in Salt Neon.
18:29:51 /var/cache/salt/minion/extmods/modules/pip.py:34: DeprecationWarning: Use of 'salt.utils.namespaced_function' detected. This function has been moved to 'salt.utils.functools.namespaced_function' as of Salt 2018.3.0. This warning will be removed in Salt Neon.
18:29:51 /var/cache/salt/minion/extmods/modules/winrepo_bootstrap.py:16: DeprecationWarning: Use of 'salt.utils.is_windows' detected. This function has been moved to 'salt.utils.platform.is_windows' as of Salt 2018.3.0. This warning will be removed in Salt Neon.
18:29:51 /var/cache/salt/minion/extmods/modules/winrepo_pkg.py:30: DeprecationWarning: Use of 'salt.utils.namespaced_function' detected. This function has been moved to 'salt.utils.functools.namespaced_function' as of Salt 2018.3.0. This warning will be removed in Salt Neon.
18:29:51 /var/cache/salt/minion/extmods/modules/winrepo_pkg.py:34: DeprecationWarning: Use of 'salt.utils.is_windows' detected. This function has been moved to 'salt.utils.platform.is_windows' as of Salt 2018.3.0. This warning will be removed in Salt Neon.
18:30:06  ... OK (15.134s)
```

**Comment by sjorge** [comment]
I’ll have a look tonight, but if I get the trace correctly the grains for zfs fail to load because they are getting an argument passed to them?

**Comment by damon-atkins** [comment]
Hi @rallytime , I have summaries the logs for you in the above posts.

**Comment by sjorge** [comment]
I had a quick look at and I don't see why it would be failing, at first glance it looks like somthing is passing a 'grains' object to the zfs grain module??

Did something change recently in relation to grains?

**Comment by sjorge** [comment]
I did some more digging, salt.grains.zfs does not seem to do much different from others like salt.grains.disks and friends. :?

**Review by terminalmage — COMMENTED** [review]
I don't understand what this is supposed to be fixing.

We only require that the versions be passed in for Windows, *NIX package managers don't have the same weird limitations that Windows does.

Furthermore, not all *NIX package manages support installing an explicit version of a package.

Can you explain why you feel this is necessary?

**Comment by damon-atkins** [comment]
> I don't understand what this is supposed to be fixing.

Consistency.
> We only require that the versions be passed in for Windows, *NIX package managers don't have the same weird limitations that Windows does.

It would have accepted "latest" as the version as well. Given it works out the current and latest version it may as well be used, so version calculated is passed. Some times the latest version will be "number string" but can also be word "latest" or "Not Found" (version not found) as it has special meaning.

On few, maybe most platforms the default is not to upgrade by default.
```
# dnf install glibc  # latest version is 2.26-28.fc27
Last metadata expiration check: 0:24:10 ago on Thu 31 May 2018 11:37:16 AM AEST.
Package glibc-2.26-27.fc27.armv7hl is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
```
> Furthermore, not all *NIX package manages support installing an explicit version of a package. 

That's a good point. I have notice at least one of the execution modules has code which ignores the extra data.

> Can you explain why you feel this is necessary?

Consistency. Maybe it should be calling then with the version as latest.

**Review by terminalmage — COMMENTED** [review]
Consistency or not, I am against this, until such time as we can confirm that passing explicit version numbers to all package managers will not result in regressions.

To me, this seems like change for change's sake, and that's rarely a great idea.

**Comment by terminalmage** [comment]
@sjorge I found and fixed the ZFS grains failures via https://github.com/saltstack/salt/pull/47932, just FYI.

**Comment by damon-atkins** [comment]
> until such time as we can confirm that passing explicit version numbers to all package managers will not result in regressions.

Thanks for the feedback. I agree 100%. I need the tests working as a starting point, to see the impact, and what required/needed.  The Jenkins run tests do not cover FreeBSD etc, so it will be a long time before this will be changed permanently.

**Comment by damon-atkins** [comment]
@terminalmage thanks for the zfs grain fix.

**Comment by sjorge** [comment]
Nice! Weird only the zfs grain was running into that though. But good to see it fixed.

**Comment by terminalmage** [comment]
@sjorge yeah it just had to do with the fact that it was a public function with a local var named `grains`. smartos.py also had one such function, but did not generate the same error, and I don't quite get why... we were capturing the exception and continuing on to the next grains func, so one traceback shouldn't have kept us from processing the subsequent grains funcs.

**Comment by terminalmage** [comment]
@damon-atkins I'm going to close this for now, if we can satisfy all of the concerns I noted a few weeks ago, we can revisit this.

**Pull request closed without merging**
