### PR TITLE
fix backward compatibility for question mark syntax

### PR DESCRIPTION
**Pull request by amalaguti**
fix provided by Joseph Hall

### What does this PR do?
fix backward compatibility for question mark syntax
### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

Yes/No

### Commits signed with GPG?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by KChandrashekhar** [comment]
Need to get this in 2019.2.1 as this fixes bug seen in customer site.

**Comment by poliva83** [comment]
Couple questions... This will get backported to 2018.3.5? When is expected release date for 2018.3.5?

**Comment by twangboy** [comment]
Please rebase this against master. Please write some tests.

**Review by techhat — APPROVED** [review]

**Comment by dwoz** [comment]
Closing this since the base branch no longer exists

#56698 replaces it.

**Pull request closed without merging**
