### PR TITLE
Fixed wrong path in LXC cloud documentation

### PR DESCRIPTION
**Pull request by jpic**

### CODE REVIEW

**Comment by kiorky** [comment]
hello @jpic i have pending (BIG) pr which will be conflicting with your pr,

i ll grab you re changeset on mine, are you ok with that ?

**Comment by kiorky** [comment]
This commit has been included in the lxc fixer PRs: #23898 #23897

Please do not merge.

thx.

**Comment by jpic** [comment]
Thanks ! keep up the great work B)

**Comment by jpic** [comment]
However, this update should appear on the website ASAP, I wasted time on that ...

**Comment by kiorky** [comment]
Can you then fill a PR, but against 2015.5, and i ll rebase my pull requests on top of it.

**Comment by kiorky** [comment]
@jpic Can you then fill a PR, but against 2015.5, and i ll rebase my pull requests on top of it.

**Comment by jpic** [comment]
Done in #23925

**Pull request closed without merging**
