### PR TITLE
Add missing support for use/use_in requisites to state.sls_id

### LINKED ISSUE #43373: use keyword breaks sls_id
### Description of Issue/Question
When one state has a 'use' clause, sls_id does not read it and fails. I find sls_id very useful for debugging, and while state.highstate does work as expected, this would be much appreciated.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Single SLS file, in this example related to MySQL:

```
le-db:
  mysql_database.present:
    - name: ledb
    - connection_host: {{ db_host }}
    - connection_user: root
    - connection_pass: {{ passwords.root }}
le-user:
  mysql_user.present:
    - name: leuser
    - password: {{ passwords.leuser }}
    - host: '%'
    - use:
      - mysql_database: le-db
```

The state checks for existence of a database and user.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
If the use: part is not present but rather connection credentials are copied, all is fine. With use, I get
salt 'minion' state.sls_id le-user lesls
'MySQL Error 2002: Can't connect to local MySQL server through socket'
which clearly shows the above setting was not read
salt 'minion' state.sls_id le-db lesls
works, as that one doesn't have a use, and it will report correctly if the DB exists

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Both are
Name        : salt-master
Version     : 2017.7.1
Release     : 1.el7
Architecture: noarch
Install Date: Tue 22 Aug 2017 04:39:41 PM UTC
From the saltstack.org repo

### PR DESCRIPTION
**Pull request by terminalmage**
Because requisite resolution doesn't happen until we run call_high, and state.sls_id doesn't run call_high (but rather calls a single low chunk from the compiled low chunks), the use/use_in requisites are ignored.  This fixes that oversight by resolving requisites in state.sls_id before we compile the high data.

Resolves #43373

### CODE REVIEW

**Comment by cachedout** [comment]
@thatch45 Could you please swing by here and review this?

**Comment by rallytime** [comment]
@terminalmage There appears to be a related test failure here: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/15039/testReport/junit/unit.modules.state_test/StateTestCase/test_sls_id/

Can you take a look?

**Comment by terminalmage** [comment]
This should be fixed.

**Review by thatch45 — APPROVED** [review]
Yes, this is exactly correct on how and where to make this addition, thanks @terminalmage !

**Pull request merged**
