### PR TITLE
Always open config file as binary

### LINKED ISSUE #61947: [BUG] UnicodeDecodeError when running under LANG=C and config file contains UTF-8 characters
**Description**
When `salt-call` is executed through a script, I see the following error:

```python traceback
[ERROR   ] 'ascii' codec can't decode byte 0xe2 in position 8516: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 196, in parse_args
    process_option_func()
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 560, in process_config_dir
    self.config.update(self.setup_config())
  File "/usr/lib/python3.6/site-packages/salt/utils/parsers.py", line 3040, in setup_config
    self.get_config_file_path(), cache_minion_id=True
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 2207, in minion_config
    exit_on_config_errors=not ignore_config_errors,
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 2082, in include_config
    opts = _read_conf_file(fn_)
  File "/usr/lib/python3.6/site-packages/salt/config/__init__.py", line 1921, in _read_conf_file
    conf_opts = salt.utils.yaml.safe_load(conf_file) or {}
  File "/usr/lib/python3.6/site-packages/salt/utils/yamlloader.py", line 178, in safe_load
    return yaml.load(stream, Loader=Loader)
  File "/usr/lib64/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib64/python3.6/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "_yaml.pyx", line 707, in _yaml.CParser.get_single_node (ext/_yaml.c:8040)
  File "_yaml.pyx", line 725, in _yaml.CParser._compose_document (ext/_yaml.c:8295)
  File "_yaml.pyx", line 776, in _yaml.CParser._compose_node (ext/_yaml.c:8983)
  File "_yaml.pyx", line 892, in _yaml.CParser._compose_mapping_node (ext/_yaml.c:10544)
  File "_yaml.pyx", line 903, in _yaml.CParser._parse_next_event (ext/_yaml.c:10698)
  File "_yaml.pyx", line 912, in _yaml.input_handler (ext/_yaml.c:10810)
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8516: ordinal not in range(128
```

The same command works fine when run from the command line.

After a bit debugging, the culprit is an UTF-8 character in the config file and the fact that `salt-call` is being executed with the environment set to `LANG=C` under the script while it is being executed with `LANG=en_US.UTF-8` when run from the command-line.

**Setup**
`/etc/salt/minion` contains the following configuration for the highstate returner:
```yaml
highstate:
  report_changes: true
  report_delivery: smtp
  report_everything: true
  report_failures: true
  report_format: html
  smtp_failure_subject: Saltstack ❌ failure minion {id} on host {host}
  smtp_recipients: server@example.net
  smtp_sender: salt-minon <root@example.net>
  smtp_server: smtp.example.net
  smtp_success_subject: Saltstack ✅ success minion {id} on host {host}
```

The ❌ and ✅ emojiis are `<U+274C>` and `<U+2705>` respectively and trigger the problem.

  
**Steps to Reproduce the behavior**
Drop the config snippet from above into /etc/salt/minion and execute `LANG=C salt-call`.

**Versions Report**
```yaml
Salt Version:
          Salt: 3004.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.59.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>

**Additional context**
The issue salt is experiencing here is described at https://github.com/yaml/pyyaml/issues/123 and suggests that the file needs to be opened with a clear encoding set for yaml to correctly decode things.

And indeed, a quick one-liner here fixes the problem:
```diff
--- /usr/lib/python3.6/site-packages/salt/config/__init__.py.orig	2022-04-13 13:00:36.913978197 +0200
+++ /usr/lib/python3.6/site-packages/salt/config/__init__.py	2022-04-13 13:03:17.091310353 +0200
@@ -1916,7 +1916,7 @@
     """
     log.debug("Reading configuration from %s", path)
     append_file_suffix_YAMLError = False
-    with salt.utils.files.fopen(path, "r") as conf_file:
+    with salt.utils.files.fopen(path, "r", encoding='utf8') as conf_file:
         try:
             conf_opts = salt.utils.yaml.safe_load(conf_file) or {}
         except salt.utils.yaml.YAMLError as err:
```

### PR DESCRIPTION
**Pull request by ixs**
### What does this PR do?
Always open the salt config files as an binary files, allowing YAML encoding detection to work.

### What issues does this PR fix or reference?
Fixes: #61947

### Previous Behavior
When run under LANG=C, UnicodeDecodeError traceback.

### New Behavior
When run under LANG=C, no UnicodeDecodeError.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by OrangeDog** [comment]
This then breaks when it's using a different encoding, with no way for the user to override it.

**Comment by ixs** [comment]
True, would it help if it is configurable?
On the other hand, I wonder what other encodings would we ever have?

**Comment by OrangeDog** [comment]
https://yaml.org/spec/1.2-old/spec.html#id2771184

> On input, a YAML processor must support the UTF-8 and UTF-16 character encodings. For JSON compatibility, the UTF-32 encodings must also be supported.

If it's opened as bytes, does the YAML parser handle the detection?

**Comment by ixs** [comment]
> https://yaml.org/spec/1.2-old/spec.html#id2771184
> 
> > On input, a YAML processor must support the UTF-8 and UTF-16 character encodings. For JSON compatibility, the UTF-32 encodings must also be supported.
> 
> If it's opened as bytes, does the YAML parser handle the detection?

It looks as if it does. Clever.

Let me update the PR...

**Comment by ixs** [comment]
Done. This should take care of your concerns I believe.

**Comment by OrangeDog** [comment]
This probably also needs tests, though I'm not sure the best way to do them.
@waynew ?

**Comment by MKLeb** [comment]
@ixs Yes, this will very likely need tests to get merged.

**Comment by ixs** [comment]
@MKLeb Great. Do you have any suggestion what kind of tests would be appropriate?

**Comment by MKLeb** [comment]
> @MKLeb Great. Do you have any suggestion what kind of tests would be appropriate?

We have a test file `tests/unit/test_config.py`.  I'm thinking maybe inside `ConfigTestCase` we can add a test where we write a couple of simple configuration files (probably no more than a few lines) under different encodings, and make sure we `_read_conf_file` loads them properly.

**Comment by OrangeDog** [comment]
New tests should be written with pytest, in `tests/pytests/unit/config/`

**Comment by MKLeb** [comment]
@ixs Are you comfortable converting the old tests file over to pytest and placing it in the location specified by @OrangeDog? If not, we can convert them over and you can write your test[s] in the new file.

**Comment by OrangeDog** [comment]
They don't _need_ converting. There are already some pytests there.

**Comment by MKLeb** [comment]
> They don't _need_ converting. There are already some pytests there.

Ah, yes, I missed that.  @ixs you can just add tests to that file then.

**Comment by OrangeDog** [comment]
> add tests to that file then

Or, better, create a new one.

**Comment by ixs** [comment]
Alright, thanks for your suggestions, I'll have a look what I can come up with...

**Comment by MKLeb** [comment]
@ixs any update on writing tests here?

**Comment by MKLeb** [comment]
Closing due to inactivity.

**Pull request closed without merging**
