### PR TITLE
Implement swap_total grain on OpenBSD

### PR DESCRIPTION
**Pull request by eradman**
### What does this PR do?

Fix method of populating the swap_total grain on OpenBSD.

### Previous Behavior

(on OpenBSD)

    (saltenv) $ doas salt-call --local grains.get swap_total
    [ERROR   ] An un-handled exception was caught by salt's global exception handler:
    ...
    Traceback (most recent call last):
    ...
      File "/home/eradman/local/saltenv/lib/python2.7/site-packages/salt/grains/core.py", line 456, in _bsd_memdata
        grains['swap_total'] = int(swap_total) // 1024 // 1024
    ValueError: invalid literal for int() with base 10: 'sysctl: second level name swap_total in vm.swap_total is invalid'

### New Behavior

    (saltenv) $ doas salt-call --local grains.get swap_total
    local:
        8058

### Tests written?

No, manually tested on OpenBSD 6.2 and FreeBSD 11

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by SEJeff — APPROVED** [review]
:+1:

**Comment by cachedout** [comment]
Could we toss a quick integration test for this into `tests.integration.grains.test_core`?

**Comment by eradman** [comment]
I added an integration test. Please posts comments since the patterns used in `integration/grains/test_core.py` will likely be copied numerous times in the future

**Comment by garethgreenaway** [comment]
@eradman Looks like one of the integration tests is failing because it's running on an Ubuntu instance.

**Comment by eradman** [comment]
@garethgreenaway, thanks for pointing that out; fixed. I was trying to call a function with `()`

**Comment by garethgreenaway** [comment]
Thanks for the fix and the integration tests. 😀

**Review by cachedout — APPROVED** [review]

**Pull request merged**
