### PR TITLE
fix wrong file parsing in salt.modules.ssh.host_keys(), fixes #21134

### LINKED ISSUE #21134: salt.modules.ssh.host_keys only reads first line of key files
I was reading #20711 and happened to notice that commit 18d24ea9 changed host_keys from doing a read() to a readline().strip(), which means it only reads the first line of each file now.  I'm not sure if this was intentional, but it prevents being able to read multi-line private keys (should someone actually want to).  As it stands today, ssh.host_keys simply shows things like this:
```
host01:
    ----------
    dsa:
        -----BEGIN DSA PRIVATE KEY-----
    dsa.pub:
        ssh-dss AAAAB3Nza...
    key:
        SSH PRIVATE KEY FILE FORMAT 1.1
    key.pub.pub:
        2048 35 280958967...
    rsa:
        -----BEGIN RSA PRIVATE KEY-----
    rsa.pub:
        ssh-rsa AAAAB3Nza...
```

### PR DESCRIPTION
**Pull request by arnisoph**
TODO:
- [ ] add tests

### CODE REVIEW

**Comment by tjstansell** [comment]
Technically, public keys can be multi line as well... https://www.ietf.org/rfc/rfc4716.txt

**Comment by bechtoldt** [comment]
@tjstansell I'll take a look at the RFC.

**Comment by jfindlay** [comment]
@bechtoldt, does this need to be backported?

**Comment by bechtoldt** [comment]
@jfindlay Yes, the target branch should have been ``2014.7``. Sorry for that.

**Comment by jfindlay** [comment]
@bechtoldt, no problem.  Thanks for the pull request.

**Comment by bechtoldt** [comment]
@tjstansell 
I changed readline().strip() to read().strip() for OpenSSH's public key files. I don't want to remove strip() for backwards compatibility reasons only. 
There are plans (#20708) to improve the usage of those keys() functions in the future.

What do you think?

**Comment by tjstansell** [comment]
I guess I don't see the point in having .pub handled differently since public and private keys share the same format rules.  I would just change the one line to be:

```diff
- keys[kname] = _fh.readline().strip()
+ keys[kname] = _fh.read().strip()
```
Keeping the strip() in there seems fine.

**Comment by bechtoldt** [comment]
I will respect your comment with the changes that I add with #20708. Until that, I don't want to break backwards compatibility.

**Comment by tjstansell** [comment]
I'm sorry, what backward compatibility are you worried about?

**Comment by bechtoldt** [comment]
In case you don't know it: strip() removes whitespace characters that are around printable chars. 

IMHO removing the trailing newline should be considered as **API CHANGE**. Things implemented by users relying on that newline *CAN* break. 

Again: This fix will be backported (at least) into 2014.7 and 2015.2. Bugfixes **MUST NOT** break things - although Salt is often known to make big changes across maintenance/ bugfix releases.

See also http://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.


I'd be interested in feedback from @jfindlay/ @basepi or others how we should proceed with this PR. I let you guys find the final decision for this.

**Comment by tjstansell** [comment]
But it's currently doing `_fh.readline().strip()` for all files.  How would changing that to `_fh.read().strip()` be a compatibility change?  They're both still doing a strip().

**Comment by bechtoldt** [comment]
Okay you're right. It won't change the public key output, I think it's only ugly/ not nice to have private keys containing newlines but are strip()'ed.

Whatever, I changed the diff to what you suggested..

**Comment by tjstansell** [comment]
Oops. I accidentally added my comment to the original issue instead of this pull request. Here it is again.

To add more heartache to this discussion, I manually changed this on my test box, and ran ssh.host_keys to see the result. One of the private keys on my test host is actually in binary format...
```
/etc/ssh/ssh_host_dsa_key:     ASCII text
/etc/ssh/ssh_host_dsa_key.pub: ASCII text, with very long lines
/etc/ssh/ssh_host_key:         data
/etc/ssh/ssh_host_key.pub:     ASCII text, with very long lines
/etc/ssh/ssh_host_rsa_key:     ASCII text
/etc/ssh/ssh_host_rsa_key.pub: ASCII text, with very long lines
```
so you get all kinds of garbled output for that key. The private keys have header lines like this:
```
# head -1 /etc/ssh/ssh_host_*key
==> /etc/ssh/ssh_host_dsa_key <==
-----BEGIN DSA PRIVATE KEY-----

==> /etc/ssh/ssh_host_key <==
SSH PRIVATE KEY FILE FORMAT 1.1

==> /etc/ssh/ssh_host_rsa_key <==
-----BEGIN RSA PRIVATE KEY-----
```
So maybe that was the original reason for only reading the first line (to get rid of all the binary junk)?

FWIW, the other host keys come across just fine.

**Comment by bechtoldt** [comment]
TODO:
- [ ] add tests

**Comment by bechtoldt** [comment]
@tjstansell what system are you running? Could it be reasonable to skip binary files?

```
# file /etc/ssh/ssh_host*
/etc/ssh/ssh_host_dsa_key:       PEM DSA private key
/etc/ssh/ssh_host_dsa_key.pub:   OpenSSH DSA public key
/etc/ssh/ssh_host_ecdsa_key:     ASCII text
/etc/ssh/ssh_host_ecdsa_key.pub: ASCII text
/etc/ssh/ssh_host_rsa_key:       PEM RSA private key
/etc/ssh/ssh_host_rsa_key.pub:   OpenSSH RSA public key
```

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.8 (wheezy)
Release:	7.8
Codename:	wheezy
```

**Comment by jfindlay** [comment]
@bechtoldt, I agree about not changing the 'API' in minor releases.  2015.2.0 is getting close, but still isn't released yet, so it should be fine to go in there.  As to the proposed changes, I don't have much of an (informed) opinion.  I would rather defer to @thatch45 or @terminalmage.

**Comment by thatch45** [comment]
I will concede on this one, but we are right down to the wire on 2015.2 and I am hesitant to let it in

**Comment by tjstansell** [comment]
This pull request has `_fh.read.strip()` instead of `_fh.read().strip()` ... which causes a traceback ...

**Comment by basepi** [comment]
@bechtoldt ^ can you fix that?

**Comment by tjstansell** [comment]
Once this is corrected, can this also get backported to 2014.7 too?

**Comment by tjstansell** [comment]
Nevermind about backporting this PR to 2014.7, as committing my fix for #21952 will include this.

**Comment by basepi** [comment]
Heh, @rallytime is too fast for you, it was backported anyway.

**Comment by basepi** [comment]
Oh, nevermind, I see that that was 2015.2. Thanks for the update on 2014.7.

**Pull request merged**
