### PR TITLE
add exception placeholder for older msgpacks

### PR DESCRIPTION
**Pull request by jfindlay**
Fix for #26705.

@cachedout, please review.

### CODE REVIEW

**Comment by cachedout** [comment]
Cool. That'll work.

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by basepi** [comment]
Pip tests are unrelated, I'm seeing failures in other places as well.

**Comment by badele** [comment]
Thank @jfindlay your path also work into v2015.8.0rc3 release

**Pull request merged**
