### PR TITLE
states/postgres_database: Update documentation of encoding kwarg

### PR DESCRIPTION
**Pull request by SteffenKockel**
### What does this PR do?

Update documenation of state module `postgres_database`

### Merge requirements satisfied?

No tests affected. Just a small clarification.

### Commits signed with GPG?

No

### CODE REVIEW

**Review by dwoz — DISMISSED** [review]

**Comment by dwoz** [comment]
@SteffenKockel Can you rebase your branch please?

**Comment by dwoz** [comment]
Replaced by #65683

**Comment by SteffenKockel** [comment]
Rebasing says: Patch already applied :o

```

**Comment by dwoz** [comment]
Looks like the same fix was applied in another PR the. I guess we're good here. Thanks for following up.

**Pull request closed without merging**
