### PR TITLE
Update to PANOS modules.

### PR DESCRIPTION
**Pull request by spenceation**
Added new PANOS functions to execution and state modules.

### What does this PR do?

- Added PANOS state modules for address and service object management.

- Changed PANOS state module to only make state change if a change is required.

- Added function to xmlutil to parse full XML data with attributes. The previous behavior was to ignore XML attributes. I previously added support in pull request 43574. However, this might cause unexpected behavior with modules dependent on this function and not currently utilizing XML attributes. (More details in previous behavior)

- Added filters to pull dirtyId tags from candidate configuration queries. This tagging marks elements as modified and is primarily an internal system tag. This causes issues with queries and parsing.

### What issues does this PR fix or reference?
Added check for required version on panos.get_uncommitted_changes execution command.

### Previous Behavior
Previous pull request 43574, the following XML string would be parsed in the following way:

`<container><member entry="1">test</member><member entry="2">test</member></container>`

Previous dictionary: `{'member': ['test', {'member': 'test'}]}`

Full dictionary: `{'member': [{'member': 'test', 'entry': '1'}, {'member': 'test', 'entry': '2'}]}`

The change might cause unexpected results on any module dependent on this new behavior. I recommend keeping the old functionality in place while allowing the full parsing to be called with an additional flag.

### New Behavior

- The xmlutil will now allow for converting XML elementree to a dictionary with XML attributes. Updated the PANOS module for parsing XML with attributes.

- The PANOS proxy module will not filter out dirtyId tags on candidate configuration to ensure proper parsing and all for state modules to accurately detect required changes.

### Tests written?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
re-run lint

**Comment by cachedout** [comment]
My primary concern here is with the XML behavior. I see the additional flag added but I want to make sure we have the same understanding. With this flag set with the default that it has, other consumers of this utility should not see a change in their XML parsing, correct?

**Comment by spenceation** [comment]
That is correct. It will operate previous to commit 43574. My concern was that parsing the attributes would change the return, and in most cases change items from strings to dicts.

This method will allow for a transition for systems requiring XML attributes.

**Comment by cachedout** [comment]
Cool. We're on the same page then. We'll keep reviewing this. Thanks!

**Comment by cachedout** [comment]
I'm a little concerned about test coverage here. Are you willing to write some tests to cover the new functionality?

**Comment by spenceation** [comment]
Sure. For the XML tests or Panos?

**Comment by cachedout** [comment]
Well, both ideally. :] The XML concerns me the most but I'd really like to have both covered if we can.

**Review by cachedout — APPROVED** [review]

**Review by rallytime — APPROVED** [review]
Well done @spenceation and thank you for adding tests

**Pull request merged**
