### PR TITLE
Pop values from new_tags set before loading into dict value

### PR DESCRIPTION
**Pull request by atengler**
This was causing state to fail with - Passed invalid arguments: can't serialize set([' tag']). Everytime when tags were defined. I described this issue here - https://github.com/saltstack/salt/issues/30681

### CODE REVIEW

**Comment by rallytime** [comment]
@atengler It looks like there is a test failing that is related here. I left a comment on the issue you filed [here](https://github.com/saltstack/salt/issues/30681#issuecomment-175842863).

**Comment by atengler** [comment]
My bad, I chose wrong way of unpacking the values from the set, but the way I use to to input the tags (as string or as list in SLS) doesn't seem to be related to my issue. My issue goes away when I unpack new_tags before loading it to ret['changes'], I'm having this issue with both approaches of defining the tags in sls. I think the failing test actually expects to have the values in set thought, which breaks states for me

**Comment by rallytime** [comment]
@atengler Thank you for double checking. If neither method of inputing tags as a string or as a list works as expected, then the test is probably just wrong. Would you mind taking a crack at updating the test here? Please let me know if you run into troubles, and I can take a look at it.

**Comment by cachedout** [comment]
@atengler Were you able to look at this test? We'd love to get this merged. Please let me know what we can do to help. Thanks!

**Comment by atengler** [comment]
I'm sorry that I didn't see this trough myself, I had to move on other issues, but I ran into this one again today while testing 2015.8.7 on CentOS 7, seems it didn't get packaged yet for neither Ubuntu 14.04 or CentOS 7, thanks for the merge though, hope this get into packages soon :+1:

**Comment by rallytime** [comment]
@atengler Yeah, it didn't make it into 2015.8.7, but it will be in 2015.8.8. Thanks again for the fix!

**Pull request merged**
