### PR TITLE
Add multiple salt-ssh state integration tests

### PR DESCRIPTION
**Pull request by Ch3LL**
### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/43627
https://github.com/saltstack/salt/issues/43626
https://github.com/saltstack/salt/issues/43624
https://github.com/saltstack/salt/issues/43623
https://github.com/saltstack/salt/issues/43622
https://github.com/saltstack/salt/issues/43621
https://github.com/saltstack/salt/issues/43620

### CODE REVIEW

**Comment by rallytime** [comment]
@Ch3LL There are some test failures here. Can you take a look?

**Comment by Ch3LL** [comment]
Okay i've been looking into this today and it looks like when you have `known_hosts_file` set in your master config file (which we are using in the test suite) and you are calling an execution module within jinja like so `{% set test = salt['cmd.run']('echo test') %}` it will fail because you get this error in the rendering of the file: `The host key needs to be accepted, to auto accept run salt-ssh with the -i flag`.

When looking at the debug logs too I notice that sometimes the ssh commands are not passing `UserKnownHostsFile` on every command when attempting to run this execution module. So just working now on tracking down on why this is occurring. I'm guessing this is a bug. will update when I found solution

**Comment by Ch3LL** [comment]
Okay I found when it was not passing `UserKnownHostsFile` to the ssh command it was because `known_hosts_file` was not under opts but `opts['__master_opts__']`. I'm not sure if this is the *best* way to fix this and really not sure why its not being added to the opts since further down in the code we add `__master_opts__` to the popts: `popts.update(opts_pkg['__master_opts__'])`. I'm guessing its related to the where the file is being rendered. But we will see if the tests pass this time. (/me crosses fingers)

**Review by rallytime — APPROVED** [review]

**Review by rallytime — APPROVED** [review]
Nicely done.

**Pull request merged**
