### PR TITLE
fix zmq hang

### LINKED ISSUE #57574: [BUG] [v3000] [vRC1 Sodium] [v3001] slsutil.renderer when called through salt-call not exiting after run
**Description**
Running salt-call slsutil.renderer is causing a freeze after the output. 

**Setup**
install salt and render a file with saltutil.renderer `salt-call slsutil.renderer` watch it stick and have to hit ctrl+c to get a prompt back.

**Steps to Reproduce the behavior**
`salt-call slsutil.renderer salt://test/init.sls` file doesn't need to exist. 

**Expected behavior**
salt-call exists after modules return.

**Screenshots**

**Versions Report**
<details><summary>salt-call test.versions</summary>

```
local:
    Salt Version:
               Salt: 3001rc1

    Dependency Versions:
               cffi: Not Installed
           cherrypy: 8.9.1
           dateutil: 2.7.3
          docker-py: Not Installed
              gitdb: 2.0.6
          gitpython: 3.0.7
             Jinja2: 2.10.1
            libgit2: 0.28.3
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.6.2
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: 3.6.1
             pygit2: 1.0.3
             Python: 3.8.2 (default, Apr 27 2020, 15:53:34)
       python-gnupg: 0.4.5
             PyYAML: 5.3.1
              PyZMQ: 18.1.1
              smmap: 2.0.5
            timelib: Not Installed
            Tornado: 4.5.3
                ZMQ: 4.3.2

    System Versions:
               dist: ubuntu 20.04 focal
             locale: utf-8
            machine: x86_64
            release: 5.4.0-29-generic
             system: Linux
            version: Ubuntu 20.04 focal
```
</details>

### LINKED ISSUE #57856: [BUG] /usr/bin/salt-call state.apply hangs at end on Xubuntu 20.04 salt 3001
**Description**
Running `/usr/bin/salt-call state.apply` on Xubuntu 20.04 minion finishes but never completes.

```
Summary for local
--------------
Succeeded: 153
Failed:      0
--------------
Total states run:     153
Total run time:    16.030 s
```

But command never returns back to terminal.

```
ps -ef |grep salt-call
root     2928868 2914767  0 08:12 pts/28   00:00:00 sudo /usr/bin/salt-call state.apply
root     2928869 2928868  0 08:12 pts/28   00:00:05 /usr/bin/python3 /usr/bin/salt-call state.apply
root     3026694 3026554  0 09:37 pts/27   00:00:00 grep --color=auto salt-call
```

Notice the command has been running over an hour but only took 16 seconds for the states to be applied.

**Setup**

**Steps to Reproduce the behavior**
Xubuntu 20.04 install with ZFS root

```
more /etc/apt/sources.list.d/saltstack.list
deb [arch=amd64] http://repo.saltstack.com/py3/ubuntu/20.04/amd64/latest focal main
```

Salt master is Ubuntu 18.04 version 3001 recently upgraded from nigrogen.
All other minions on network are 18.04 and working as expected.

**Expected behavior**
`salt-call state.apply` to finish and return to terminal.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Master:
salt --versions-report
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
        libgit2: 0.26.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.4.7
         pygit2: 0.26.2
         Python: 3.6.9 (default, Apr 18 2020, 01:56:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 17.1.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: ubuntu 18.04 Bionic Beaver
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-101-generic
         system: Linux
        version: Ubuntu 18.04 Bionic Beaver

Minion With issue:
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: 4.1.0
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.1.0
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.8.2 (default, Apr 27 2020, 15:53:34)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: ubuntu 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 5.4.0-39-generic
         system: Linux
        version: Ubuntu 20.04 focal


Working Minon:

salt-call --versions-report
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Apr 18 2020, 01:56:04)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-101-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
</details>

**Additional context**

### PR DESCRIPTION
**Pull request by cmcmarrow**
### What does this PR do?
stops zmq from deconstructing it self. zmq can deconstruct out of order

### What issues does this PR fix or reference?
Fixes:
https://github.com/saltstack/salt/issues/57856
https://github.com/saltstack/salt/issues/57574

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by waynew — CHANGES_REQUESTED** [review]
Definitely want a changelog entry or two, and I'll probably want to give this a bit deeper dive, but mostly it looks good 👍

**Comment by cmcmarrow** [comment]
re-run full all centos

**Comment by cmcmarrow** [comment]
re-run all

**Comment by cmcmarrow** [comment]
re-run full all

**Comment by cmcmarrow** [comment]
re-run full macosxmojave

**Comment by cmcmarrow** [comment]
re-run full all

**Comment by cmcmarrow** [comment]
re-run full all

**Comment by cmcmarrow** [comment]
re-run full mac

**Comment by cmcmarrow** [comment]
re-run full lint

**Comment by cmcmarrow** [comment]
re-run full pre-commit

**Review by waynew — DISMISSED** [review]

**Review by dwoz — APPROVED** [review]

**Comment by eliasp** [comment]
Only noticed this PR after it's been merged, but having huge commits like a6ac1849513a659a8ca4dcd73b26fbf4f3d8aab6 or generic commit messages like "hot fix" or "fix pre" is not good for the general repository hygiene. IMHO those should be either handled properly or be rebased as long as a PR is still WIP.
This huge commit (a6ac1849513a659a8ca4dcd73b26fbf4f3d8aab6), containing the actual fix also does a lot of other completely unrelated things. This makes it really hard at a later point to pin-point a possible regression to a specific change, e.g. when using `git bisect ...`.

As an outsider I can't really dictate any policies here, but as someone debugging those kind of issues quite often I can surely tell that this makes it really hard in being helpful providing valuable information in bug reports, e.g. pointing out a specific line or so which introduced a certain bug or finding commits by scanning over their messages.

**Comment by takeda** [comment]
I agree with @eliasp, Saltstack is a great product, but it should have stronger discipline with changes. The biggest issue with saltstack is that every release is like a lottery, it might fix your bug (like currently this one is the biggest one for me), but it can introduce another bug. It makes people hesitant to recommend it, because while it solves a lot of issue and in better ways than other CMs its weak part is stability.

This should be actually 2 PRs:

1. only the fix with the issue (and have it backported to 3001.2 and 3000.4)
2. removing py2.7 support and only merging it to master (I know there is a lot of code and it's not feasible to do that separately and it's best when making other changes, but it's so easy to make a mistake in these steps)

**Comment by fzipi** [comment]
Agreed. I've cleanup it up to look like this for us: https://gist.github.com/fzipi/af135b5e1f78128ffdafff3f8240caa9

**Comment by thatITguy2000** [comment]
I see this issue has been closed and changes merged but I'm still seeing this behavior with a RHEL7.9 Workstation OS acting as Salt Master with a Ubuntu 20.04 minion using the Latest salt-master-3002.1-1.el7.noarch.rpm installation, my installs are performed using the SaltStack repo (https://repo.saltstack.com/py3/redhat/7Workstation/x86_64/latest/) via a local Satellite mirror that syncs weekly.
I'm not certain what I'm missing but I'm hoping someone can help me along as a newbie to github and in regard to this issue specifically.
My Master and Minion are both using the latest packages from the SaltStack repos for their installations.

**Comment by jakehilton** [comment]
I recently upgraded to 2019.2.7 from 2019.2.4 for the latest CVE fixes. I am now seeing this hang issue as well. I'm on Ubuntu 18.04.

**Comment by ocfmatt** [comment]
> Agreed. I've cleaned it up to look like this for us: https://gist.github.com/fzipi/af135b5e1f78128ffdafff3f8240caa9

Applying this patch has resolved the hang issue for me. Thank you @fzipi for committing it!

@jakehilton - applying the patch has made my 2019.2.7 install consistently work without having to disable zmq transport.

Regards,
Matt.

**Pull request merged**
