### PR TITLE
Fix container detection on virtual machines

### PR DESCRIPTION
**Pull request by nkukard**
When creating an LXC container on a virtual machine which has access to /proc/cpuinfo and potentially paths in /sys, the latter part of detection in core.py overrides the correct 'virtual' grain with the virtual machine type.

This fixes the issue by skipping the inspection of /proc and /sys files if we have already determined the virtualization type being used.

### What does this PR do?

This PR fixes the issue of container detection on Linux systems when the container is running on a virtual machine.

### What issues does this PR fix or reference?

I think the patch is self explanatory. The only line being added is...
`if 'virtual' not in grains:`

### Previous Behavior

When running an LXC container on a VirtualBox virtual machine the following is observed...

> $ salt-call grains.items
> ...
>     virtual:
>        VirtualBox
> ...

### New Behavior

After applying the patch, the following is observed...

> $ salt-call grains.items
> ...
>     virtual:
>        LXC
> ...

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by nkukard** [comment]
Updated patch to only catch LXC case

**Comment by nkukard** [comment]
Rebased against develop

**Comment by xeacott** [comment]
Thanks for submitting a PR and, I will also ask for some tests for this because this introduces some new code. Also, the lint job failed here however, the complaint is because a deprecated function is being used in the file - I'll ask and see how to remedy this.

**Comment by xeacott** [comment]
Thanks for submitting a PR and, I will also ask for some tests for this because this introduces some new code. Also, the lint job failed here however, the complaint is because a deprecated function is being used in the file - I'll ask and see how to remedy this.

**Comment by nkukard** [comment]
> Thanks for submitting a PR and, I will also ask for some tests for this because this introduces some new code. Also, the lint job failed here however, the complaint is because a deprecated function is being used in the file - I'll ask and see how to remedy this.

The latest force push I made should target only when virtual = LXC.

I've tested on VirtualBox myself (with and without LXC) and on barebones systems, but I hope you have more tests you can do from your side.

**Comment by xeacott** [comment]
Unfortunately, we don't have exhaustive unit/integration tests for grains/core.py right now. Moreover, we don't have a test that would cover this change, let alone the function itself :-1: So, as part of generating a PR we do ask that you provide a written test too, which can be simple and only test your change. It helps us maintain a stable testing environment and increases our test coverage, which never hurts. I can point you over to `tests/integration/grains/text_core.py` for some quick examples in there.

**Review by sagetherage — CHANGES_REQUESTED** [review]
please point this to the master branch instead of develop

**Comment by nkukard** [comment]
> please point this to the master branch instead of develop

Done as requested. Effectively all this is is pretty much a 1 line change encapsulating the VM test if LXC was already detected.

**Comment by xeacott** [comment]
This will also need pre-commit ran in order to pass, I can run that for you and push the changes if you cannot.

**Comment by nkukard** [comment]
> This will also need pre-commit ran in order to pass, I can run that for you and push the changes if you cannot.

I installed pre-commit, re-committed the changes, it ran with no errors what I could see and I re-pushed.

I hope this is right? I was following this https://docs.saltstack.com/en/latest/topics/development/contributing.html

I'm not sure if you want me to perhaps post the output of the pre-commit? :)

**Comment by xeacott** [comment]
Ahhh I'll babysit this PR and wait for pre-commit to finish and see what's up with it...

**Comment by nkukard** [comment]
> Ahhh I'll babysit this PR and wait for pre-commit to finish and see what's up with it...

Ah I see an black fail on the CI system, I'll fix it quick.

**Comment by xeacott** [comment]
Cool looks like pre-commit passed. At this point we'll just need to get this PR a test and we'll merge it in.

**Review by xeacott — APPROVED** [review]

**Comment by sagetherage** [comment]
@toanju 
Looks like there is another PR that will fix the same issue here: https://github.com/saltstack/salt/pull/60196 - if you would and could please give a review to that PR - love to have your feedback!

**Comment by toanju** [comment]
@sagetherage, you wanted to ping me?

**Comment by sagetherage** [comment]
@toanju I must have made a mistake in pinging you, here. I can't follow my own comment - so sorry! Definitely my mistake!

**Pull request closed without merging**
