### PR TITLE
Support running git states / remote exec funcs as a different user in Windows

### PR DESCRIPTION
**Pull request by terminalmage**
This adds support for Windows minions to run git states and remote execution functions as a user other than the default. It does so by adding a `password` parameter wherever the `user` param is supported.

### CODE REVIEW

**Comment by rallytime** [comment]
@terminalmage Can you take a look at the lint failures? Once that fixed is pushed up, we can look at the test run again. The Ubuntu/CentOS runs didn't return any test results this time around.

**Comment by cachedout** [comment]
Are we putting passwords into process lists here? If so a security warning in the doc strings might be prudent.

**Comment by terminalmage** [comment]
@cachedout as far as I know the password is merely being passed to cmdmod.py to be used in the win_runas code that was added for 2016.3.0. The password is not a password for git so it's not part of the actual command being run. However, I can't with 100% certainty speak to what the win_runas code does.

@twangboy added the win_runas code, so he's more familiar with it.

@twangboy Does the password end up in the process list? In other words, is the password visible in the output from the ``tasklist`` command while a command is in progress? You should be able to test this by running ``cmd.run 'timeout 60' runas=someotheruser password=somepassword`` and then in another prompt window running ``tasklist`` (or ``tasklist | find /i "timeout"``), as well as looking at the Task Manager window.

**Comment by terminalmage** [comment]
@cachedout I did also notice that we were skipping logging the command being run when Windows runas was being used, due to an early return from the ``_run()`` func, so I moved that logging up earlier to ensure that we preserve the prior behavior.

**Comment by twangboy** [comment]
@terminalmage The process is created using windows api's. The password is passed to the API and doesn't show in the process list.

**Pull request merged**
