### PR TITLE
Docker login 51531

### PR DESCRIPTION
**Pull request by c4t3l**
### What does this PR do?
Adds functionality for setting docker login info from pillar and master/minion config files.

### What issues does this PR fix or reference?
References #51531 

### Previous Behavior
Docker login execution module only reads configuration data from Pillar.

### New Behavior
Docker login execution module now reads configuration data from minion, master, and pillar.

### Tests written?

No

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by terminalmage — COMMENTED** [review]
I am not a fan of this implementation for a couple reasons:

1. It drops support for using config keys ending in `-docker-registries`, functionality that many users likely rely on.
2. It uses `config.option` instead of `config.get` which is widely used elsewhere in dockermod.py.

In truth, the reason we limited this to Pillar to begin with is because it lets you store the secrets somewhere _other_ than the minion config file. I'm not convinced it's a great idea to store them elsewhere, but as long as it's properly documented and people are aware of the risk they are taking, I guess I'm OK with it.

However, I think it can be done in a way that doesn't break existing users' configurations. I'll see what I can come up with.

**Review by Akm0d — APPROVED** [review]

**Comment by terminalmage** [comment]
@Akm0d I'm confused as to why you approved this PR, since I gave it a negative review. Did you read my comment?

Additionally, I submitted a more comprehensive fix 4 months ago (https://github.com/saltstack/salt/pull/51677) which has yet to be merged and which should supersede this PR.

**Comment by Ch3LL** [comment]
ping @c4t3l are you okay closing this one in favor of #51677

**Comment by c4t3l** [comment]
Yes that is fine with me.  :)

**Pull request closed without merging**
