### PR TITLE
adding states/postgres_database unit test case.

### PR DESCRIPTION
**Pull request by jayeshka**
Implemented states/postgres_database_test unit test case.

### CODE REVIEW

**Comment by jfindlay** [comment]
@jayeshka, there are two [test failures](https://jenkins.saltstack.com/job/salt-pr-rs-ubuntu14.04-n/5698/).

**Comment by jayeshka** [comment]
@jfindlay test are passing at my end.
Pulled updated branch of 2015.5 and try to run th test. I don't get any failures.
Tried for both #24330 and #24331.

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
I also tested these and there does not seem to be a problem.

**Comment by jfindlay** [comment]
@cachedout, this is failing on the branch tests as well, https://jenkins.saltstack.com/view/2015.5%20Branch/job/salt-2015.5-linode-ubuntu12.04/1570/.

**Comment by jtand** [comment]
@jayeshka @cachedout We are seeing the same failures on the branch tests. I'm going to revert and we'll merge again when we figure out why these failures are happening.

**Pull request merged**
