### PR TITLE
Tests for git_pillar

### PR DESCRIPTION
**Pull request by gracinet**
I'm submitting on the develop branch, but I think it'd be a natural candidate for backport, since it's made of new tests only.
This is related to #21342

Two different calls of the `ext_pillar` entry function are checked, a
direct one and one from upper in the calling stack (more integration)
The different options show the slight differences (almost side effects
between them).

A third test is included to detect infinite recursions, to avoid future
refactors that could bring them back accidentally.

### CODE REVIEW

**Comment by rallytime** [comment]
@gracinet Awesome! Thanks so much for writing these tests! That is always much appreciated and these look excellent. 

Would you mind grabbing the pylint error really quickly here: https://jenkins.saltstack.com/job/salt-pr-lint-n/3060/violations/file/tests/unit/pillar/git_test.py/

As well as add the following to the bottom of the file:
```
if __name__ == '__main__':
    from integration import run_tests
    run_tests(GitPillarTestCase, needs_daemon=False)
```

**Comment by gracinet** [comment]
On 03/16/2015 05:12 PM, Nicole Thomas wrote:
>
> @gracinet <https://github.com/gracinet> Awesome! Thanks so much for
> writing these tests! That is always much appreciated and these look
> excellent.
>
you're welcome, actually I need these to dare touch anything ;-)
>
> Would you mind grabbing the pylint error really quickly here:
> https://jenkins.saltstack.com/job/salt-pr-lint-n/3060/violations/file/tests/unit/pillar/git_test.py/
>
> As well as add the following to the bottom of the file:
>
> |if __name__ == '__main__':
>     from integration import run_tests
>     run_tests(GitPillarTestCase, needs_daemon=False)|
|okay I wasn't sure if it was really needed, thanks for confirming that.
|

-- 
Georges Racinet
Anybox SAS, http://anybox.fr
Bureau: 09 72 39 50 97 / 09 72 39 13 06
Portable: 06 51 32 07 27
GPG: 0x33AB0A35, sur serveurs publics

**Comment by gracinet** [comment]
Speaking of style, I noticed in this part of the code quite a few cases where kwargs are passed as if they were positional, as in
```
   def f(a, b=None):
         'a function'

   f(0, 1)
```
In my experience, these are terrible sources of mistakes (it's worse with several such kwargs) especially after even minor refactorings, trigger subtle bugs in generic argument relaying such as `f(*args, **kwargs)` and make code harder to understand. Actually I wish Python never had permitted that in the first place, but that maybe juste me :-)

What does Salt code style say about these ?

**Comment by basepi** [comment]
Most of our code styling is based on our pylint setup on jenkins, which doesn't complain about passing data to kwargs in a positional manner. I tend to avoid it myself, and, as you say, it can cause errors in the long run. Maybe we should make it an official part of the style guide... *shrugs*

**Comment by rallytime** [comment]
@gracinet Thanks for cleaning that up. The `needs_daemon=False` code signals to our test running that unit tests do not need the integration test daemons configured and running to execute the tests.

**Comment by cachedout** [comment]
I think it would be worth tossing in a pylint rule for this to at least see how widespread the practice might be. I agree that this is very rarely a good idea (if ever).

**Comment by gracinet** [comment]
Thanks !

On 16 mars 2015 19:35:33 UTC+01:00, Thomas S Hatch <notifications@github.com> wrote:
>Merged #21675.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/saltstack/salt/pull/21675#event-255909572

-- 
Sent from my handheld device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
