### PR TITLE
Btrfs and XFS as supported fstypes

### PR DESCRIPTION
**Pull request by brejoc**
### What does this PR do?

Btrfs and XFS are supported by parted and mkfs. Adding them to the list.

This PR replaces https://github.com/saltstack/salt/pull/53126

### Previous Behavior
btrfs and xfs where not supported for parted and mkfs.xxx.

### New Behavior
btrfs and xfs are now supported.

### Tests written?
Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by waynew — DISMISSED** [review]
Hey @brejoc thanks for the PR! Looks great!

**Comment by waynew** [comment]
Hey @brejoc looks like there's a conflict - could you take a look at that? Thanks!

**Comment by s0undt3ch** [comment]
This PR is passing. The pending CentOS 8 build is an artifact of a bad Jenkins job.

**Comment by s0undt3ch** [comment]
Oh, dam. There's conflicts.

**Comment by s0undt3ch** [comment]
Conflicts resolved on the GH UI.

**Comment by brejoc** [comment]
Sorry guys, I was on vacation. And thanks for solving the conflict. I've just merged master into this branch again, to get the latest changes.

**Comment by brejoc** [comment]
Okay, I think this doesn't look bad. I don't know where that failure on ci/py2/amazon1 is coming from. The tests seem to have passed: `Test Result (no failures)`

**Comment by brejoc** [comment]
Merged master again. Is there anything that prevents us from merging this?

**Review by DmitryKuzmenko — DISMISSED** [review]

**Comment by brejoc** [comment]
Changes are now blacked.

**Review by DmitryKuzmenko — APPROVED** [review]

**Pull request merged**
