### PR TITLE
Fix UnicodeDecodeError when parsing hosts file with non-ascii

### LINKED ISSUE #48012: Found UnicodeDecodeError when trying to start Salt Master
### Description of Issue/Question
When I upgraded the Salt Master and was trying to start it, I got a UnicodeDecodeError:
```
# service salt-master start
Starting salt-master daemon: [ERROR   ] 'ascii' codec can't decode byte 0xe9 in position 42: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 209, in parse_args
    process_option_func()
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 547, in process_config_dir
    self.config.update(self.setup_config())
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 1770, in setup_config
    return config.master_config(self.get_config_file_path())
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 3841, in master_config
    opts = apply_master_config(overrides, defaults)
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 3931, in apply_master_config
    cache_minion_id=None)
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 3597, in get_id
    newid = salt.utils.network.generate_minion_id()
  File "/usr/lib/python2.7/site-packages/salt/utils/network.py", line 172, in generate_minion_id
    ret = salt.utils.stringutils.to_unicode(_generate_minion_id().first())
  File "/usr/lib/python2.7/site-packages/salt/utils/network.py", line 156, in _generate_minion_id
    for hst in (line.strip().split('#')[0].strip().split() or None for line in f_hdl.read().split(os.linesep)):
  File "/usr/lib/python2.7/site-packages/salt/utils/network.py", line 156, in <genexpr>
    for hst in (line.strip().split('#')[0].strip().split() or None for line in f_hdl.read().split(os.linesep)):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 42: ordinal not in range(128)
Usage: salt-master [options]

salt-master: error: Error while processing <bound method Master.process_config_dir of <salt.cli.daemons.Master object at 0x7f17a4890c50>>: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 209, in parse_args
    process_option_func()
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 547, in process_config_dir
    self.config.update(self.setup_config())
  File "/usr/lib/python2.7/site-packages/salt/utils/parsers.py", line 1770, in setup_config
    return config.master_config(self.get_config_file_path())
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 3841, in master_config
    opts = apply_master_config(overrides, defaults)
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 3931, in apply_master_config
    cache_minion_id=None)
  File "/usr/lib/python2.7/site-packages/salt/config/__init__.py", line 3597, in get_id
    newid = salt.utils.network.generate_minion_id()
  File "/usr/lib/python2.7/site-packages/salt/utils/network.py", line 172, in generate_minion_id
    ret = salt.utils.stringutils.to_unicode(_generate_minion_id().first())
  File "/usr/lib/python2.7/site-packages/salt/utils/network.py", line 156, in _generate_minion_id
    for hst in (line.strip().split('#')[0].strip().split() or None for line in f_hdl.read().split(os.linesep)):
  File "/usr/lib/python2.7/site-packages/salt/utils/network.py", line 156, in <genexpr>
    for hst in (line.strip().split('#')[0].strip().split() or None for line in f_hdl.read().split(os.linesep)):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 42: ordinal not in range(128)

```

### Setup
I think there is no need to provide it. : )

### Steps to Reproduce Issue
- Make sure `/etc/hostname` and `/etc/nodename` are all absent.
- Add some comments to `/etc/hosts` file with Chinese characters, such as:
```
# 以下为主机名解析
## ccc
127.0.0.1       localhost            # 本机
```
- Run:
```
service salt-master start
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.2 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-220.7.1.el6.x86_64
         system: Linux
        version: CentOS 6.2 Final
```

### PR DESCRIPTION
**Pull request by terminalmage**
This also adds a regression test, and I also added the following goodies to mock_open while I was writing the test:

1. Now works properly when read_data is a bytestring
2. Now works properly when mocked filehandle is iterated (e.g. `for line in fh:`)
3. Adds ability to make mocked filehandle raise an IOError when the path being opened doesn't match a pattern (or one of a list of patterns).

Fixes #48012.

### CODE REVIEW

**Comment by cachedout** [comment]
@terminalmage Failed tests here

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
@terminalmage It looks like the tests didn't like this very much.

**Comment by terminalmage** [comment]
@twangboy can you have a look at the mac_sysctl changes? I have the tests passing now but I think that `mac_sysctl.persist` had a bug in it...  `.writelines()` just does a `.write()` for each element in the iterable that is passed to it, and so they expect you to provide your own trailing newlines. However, the code in `mac_sysctl.persist` does two appends, one with the `key=value` pair and one with the newline. This technically would have produced the correct outcome, but the test would not reflect that we wrote what we would expect. I made changes to make it behave how it looks like it should, but I would appreciate another set of eyes on that.

**Review by twangboy — APPROVED** [review]
Looks good to me

**Comment by terminalmage** [comment]
Fixed up a couple lint issues, the tests should pass.

**Comment by rallytime** [comment]
@terminalmage The tests on the Ubuntu 16 Py3 build are not failing on the branch, so I think they're related to this. Can you take another look?

https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu16-py3/10699/

**Comment by terminalmage** [comment]
Test failure appears unrelated (I can't reproduce locally).

**Comment by Waterdrips** [comment]
Just bumped into this - many thanks for the fix @terminalmage .

**Pull request merged**
