### PR TITLE
Add newline after cron comment

### LINKED ISSUE #41508: cron.present - No line breaks after comments and SALT_CRON_IDENTIFIER
### Description of Issue/Question
When using comments on a 'cron.present' state it does not add a line break at the end of the last line of the comment

### Setup
```
test:
    cron.present:
        - identifier: test-01
        - comment: |
            This is line 1 of my comment
            This is line 2 of my comment
            .
        - name: COMMAND_GOES_HERE >/dev/null 2>&1
        - user: root
        - hour: 1
        - minute: 2
```
### Steps to Reproduce Issue
After running the state against a minion this is how it looks. The last comment (just a '.') is at the same line and together with SALT_CRON_IDENTIFIER. There should be a line break after it

    # Lines below here are managed by Salt, do not edit
    # This is line 1 of my comment
    # This is line 2 of my comment
    # . SALT_CRON_IDENTIFIER:test-01
    2 1 * * * COMMAND_GOES_HERE >/dev/null 2>&1

Maybe /usr/lib/python2.6/site-packages/salt/states/cron.py should be edited so a line break is added after the last comment line
(
if comment:
    ret['comment'] = comment
)

### Versions Report
Salt Version:
           Salt: 2016.3.4

Dependency Versions:
           cffi: 1.1.2
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.20.3
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: 0.8.1
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.9 Final
        machine: x86_64
        release: 2.6.32-504.23.4.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final

### PR DESCRIPTION
**Pull request by IJustWorkHere**
### What does this PR do?
Adds a newline character to the end of a cron comment

### What issues does this PR fix or reference?
Fixes #41508

### Previous Behavior
A newline was not placed after a comment if provided
```
# Lines below here are managed by Salt, do not edit
# This is line 1 of my comment
# This is line 2 of my comment
# . SALT_CRON_IDENTIFIER:test-01
2 1 * * * COMMAND_GOES_HERE >/dev/null 2>&1
```
### New Behavior
A newline is placed after the comment
```
# Lines below here are managed by Salt, do not edit
# This is line 1 of my comment
# This is line 2 of my comment
# .
# SALT_CRON_IDENTIFIER:test-01
2 1 * * * COMMAND_GOES_HERE >/dev/null 2>&1
```
### Tests written?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Review by cachedout — COMMENTED** [review]
I personally am not a very big fan of changes like this but I would like to see what @garethgreenaway and @terminalmage think about it.

**Comment by garethgreenaway** [comment]
The solution makes sense though it's curious why the newline is being stripped from the last comment line and not the others.

**Comment by shitler25oki** [comment]
@garethgreenaway it looks like everything else in _render_tab() is already adding a newline character to the end of the ret variable.  The newline that originally exists at the end of the comment passed into render_tab() is removed by the rstip().  When you mash the comment with the identifier the end result is that the last line of the comment is on the same line as the identifier.

I thought about removing the rstip() but figured it was probably there for a reason.

**Comment by garethgreenaway** [comment]
@shitler25oki I ran a quick test without the `rstrip` and it appears to give the desired results.   Couple more tests to see what led to it being introduced.

**Comment by garethgreenaway** [comment]
Based on what I'm seeing, I believe we can safely remove the `rstrip`.  The `replace` is doing the work that fixed the original issue.

**Comment by shitler25oki** [comment]
I updated the request to simply remove the ```rstrip```

**Comment by cachedout** [comment]
If we are to merge this, we'll first need this test fixed:

https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/11964/testReport/junit/unit.states.test_cron/CronTestCase/test_multiline_comments_are_updated/

**Comment by shitler25oki** [comment]
@cachedout I'm sorry about that.  I've updated the test.

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
