### PR TITLE
Detect when system needs reboot after domain join

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?
Properly detects if the system requires reboot after Joining a domain.
Adds value_exists function
Uses key_exists instead of reading and failing

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/49675

### Tests written?
No

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by twangboy** [comment]
@rallytime Probably need to backport to 2017.7, but I'll need to create separate PR.

**Comment by hrumph** [comment]
@twangboy , thanks for the fix.
There are still two more instances of the same error in the module. You also need to fix the _get_pending_update_ and _get_pending_component_servicing_. You may as well fix everything at once.

**Comment by hrumph** [comment]
@Twangboy I am now happy to see this committed.

**Comment by rallytime** [comment]
@twangboy The following windows test failures look related to me:

- integration.modules.test_system.WinSystemModuleTest.test_get_computer_name
- integration.modules.test_service.ServiceModuleTest.test_service_disable_doesnot_exist
- integration.modules.test_service.ServiceModuleTest.test_service_enable

https://jenkinsci.saltstack.com/job/pr-windows2016-py3/job/PR-49684/3/

Can you fix those?

**Comment by hrumph** [comment]
@rallytime, This is none of my business I suppose. I don't know how the testing works. Certainly, the _get_computer_name_ function works for me (on Windows 10).  (I haven't looked at the other two functions). How can one know the particulars of the test system in order to duplicate the environment? Can it be ascertained that the test system has no permissions issues and so forth?

The test issues may or may not be related to each other but I don't see how they're related to the bugs @Twangboy just fixed

**Comment by twangboy** [comment]
@rallytime Yeah, I just relaunched the tests, but I don't think the failures are related.

**Comment by rallytime** [comment]
Ok, the PR tests for windows still need some ❤️ so I was trying to make an educated guess so we don't cause more failures. Let's see how the next run goes. Thanks for chiming in!

**Review by rallytime — APPROVED** [review]

**Pull request merged**
