### PR TITLE
Update Venfi Module

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
This is a re-submission of https://github.com/saltstack/salt/pull/55286 with a fixed(more concise) git history and static requirements since I didn't have push access to the Venafi fork.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/pull/55286

/CC @arykalin

### CODE REVIEW

**Comment by arykalin** [comment]
I see strange error for ci/py2/amazon1. It is not looks like a venafi runner error:

```
[2020-01-14T06:45:22.037Z]        Running tests...
[2020-01-14T06:45:22.037Z]        ----------------------------------------------------------------------
[2020-01-14T06:45:22.037Z]          test_request (integration.externalapi.test_venafiapi.VenafiTest)
[2020-01-14T06:45:30.736Z]        [CPU:56.7%|MEM:27.9%]  ... 06:45:30,088 [salt.loader                                      :1624][ERROR   ] Failed to import runners nacl, this is due most likely to a syntax error:
[2020-01-14T06:45:30.736Z]        Traceback (most recent call last):
[2020-01-14T06:45:30.736Z]          File "/tmp/kitchen/testing/salt/loader.py", line 1607, in _load_module
[2020-01-14T06:45:30.736Z]            mod = imp.load_module(mod_namespace, fn_, fpath, desc)
[2020-01-14T06:45:30.736Z]          File "/tmp/kitchen/testing/salt/runners/nacl.py", line 119, in <module>
[2020-01-14T06:45:30.736Z]            import salt.utils.nacl
[2020-01-14T06:45:30.736Z]          File "/tmp/kitchen/testing/salt/utils/nacl.py", line 26, in <module>
[2020-01-14T06:45:30.736Z]            import libnacl.secret
[2020-01-14T06:45:30.736Z]          File "/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/local/lib/python2.7/site-packages/libnacl/__init__.py", line 119, in <module>
[2020-01-14T06:45:30.736Z]            crypto_box_SEEDBYTES = nacl.crypto_box_seedbytes()
[2020-01-14T06:45:30.736Z]          File "/usr/lib64/python2.7/ctypes/__init__.py", line 374, in __getattr__
[2020-01-14T06:45:30.736Z]            func = self.__getitem__(name)
[2020-01-14T06:45:30.736Z]          File "/usr/lib64/python2.7/ctypes/__init__.py", line 379, in __getitem__
[2020-01-14T06:45:30.736Z]            func = self._FuncPtr((name_or_ordinal, self))
[2020-01-14T06:45:30.736Z]        AttributeError: /usr/lib64/libsodium.so.4: undefined symbol: crypto_box_seedbytes
[2020-01-14T06:45:30.736Z]        OK (8.393s)
[2020-01-14T06:45:30.736Z]          test_sign (integration.externalapi.test_venafiapi.VenafiTest)
[2020-01-14T06:45:39.586Z]        [CPU:0.0%|MEM:27.9%]  ... 06:45:38,167 [salt.loader                                      :1624][ERROR   ] Failed to import runners nacl, this is due most likely to a syntax error:
[2020-01-14T06:45:39.586Z]        Traceback (most recent call last):
[2020-01-14T06:45:39.586Z]          File "/tmp/kitchen/testing/salt/loader.py", line 1607, in _load_module
[2020-01-14T06:45:39.586Z]            mod = imp.load_module(mod_namespace, fn_, fpath, desc)
[2020-01-14T06:45:39.586Z]          File "/tmp/kitchen/testing/salt/runners/nacl.py", line 119, in <module>
[2020-01-14T06:45:39.586Z]            import salt.utils.nacl
[2020-01-14T06:45:39.586Z]          File "/tmp/kitchen/testing/salt/utils/nacl.py", line 26, in <module>
[2020-01-14T06:45:39.586Z]            import libnacl.secret
[2020-01-14T06:45:39.586Z]          File "/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/local/lib/python2.7/site-packages/libnacl/__init__.py", line 119, in <module>
[2020-01-14T06:45:39.586Z]            crypto_box_SEEDBYTES = nacl.crypto_box_seedbytes()
[2020-01-14T06:45:39.586Z]          File "/usr/lib64/python2.7/ctypes/__init__.py", line 374, in __getattr__
[2020-01-14T06:45:39.586Z]            func = self.__getitem__(name)
[2020-01-14T06:45:39.586Z]          File "/usr/lib64/python2.7/ctypes/__init__.py", line 379, in __getitem__
[2020-01-14T06:45:39.586Z]            func = self._FuncPtr((name_or_ordinal, self))
[2020-01-14T06:45:39.586Z]        AttributeError: /usr/lib64/libsodium.so.4: undefined symbol: crypto_box_seedbytes
[2020-01-14T06:45:39.586Z]        OK (8.062s)
```

And for debian10 venafi tests pass, but build is failed, can't understand why

**Comment by s0undt3ch** [comment]
Unfortunately we still have some flakiness on the test suite. I kicked off another build for those two that failed.

**Review by waynew — APPROVED** [review]

**Review by xeacott — APPROVED** [review]

**Comment by tr1ck3r** [comment]
@waynew @xeacott thank you for completing your reviews. @s0undt3ch what is the ETA for the merge to master?  We're already a couple months behind on delivering this update so I'm really anxious to get it completed.

**Comment by dwoz** [comment]
@tr1ck3r This has been merged and will be included in the impending salt 3000 release.

**Comment by tr1ck3r** [comment]
Excellent!  Thank you @dwoz

**Comment by s0undt3ch** [comment]
Thank You for your patience @tr1ck3r.

**Pull request merged**
