### PR TITLE
Automate release tag, changelog and man pages

### PR DESCRIPTION
**Pull request by Ch3LL**
### What does this PR do?
Use Github Actions to help automate some release tasks. Both of these Github Actions are manually triggered, with the release version and other inputs required.

1. Generate Release changelog and man pages

release-docs

release-docs-ga-in-progress

This Github Action will generate the changelog, add the changelog to the release notes and generate the man pages. If the man pages do not need to be generated you can set man pages to false in the inputs. Once all the docs are generated it will create a PR automatically. Here is the PR that was created on my repo:

https://github.com/Ch3LL/salt/pull/16

There are still some improvements that could be made to this:
a. Detect if the release file has not been created and add the required 3005 banner at the top of the release notes file.
b. If re-generating the docs for a re-tag, figure out how to automatically add the changelog entries to the correct place. Right now this will require manually updating the PR.

2. Create Tag and Release:

create-tag

tag-release-final

This Github Action will create a 3005 tag and github release. It will also build and generate the salt tar ball. If its a re-tag, you can set retag to be true and it will delete the previous 3005 tag and release before generating the new tag and github release.

### CODE REVIEW

**Review by krionbsd — DISMISSED** [review]

**Review by barbaricyawps — DISMISSED** [review]
Looks good to me!

**Comment by bryceml** [comment]
it looks like the tag annotation was `v3005` when we've always done something like `Version 3005` in the past.

**Comment by Ch3LL** [comment]
I don't see a reason why we need the tag annotation to say "Version 3005" versus using "v3005". Looks like the github action is pending a PR https://github.com/mathieudutour/github-tag-action/pull/23 here to add the feature to add a custom annotated tag message. If there is no need for "Version 3005" I think we are okay to go forward with this.

**Review by garethgreenaway — APPROVED** [review]

**Review by s0undt3ch — APPROVED** [review]

**Comment by s0undt3ch** [comment]
@dmurphy18 it's GH Actions specific, nothing to do with whatever python versions salt supports

**Comment by Ch3LL** [comment]
ping @krionbsd would changing the annotation tag impact packaging at all?

I verified that changing the tag annotation does not impact the salt version:


```
(heist-3.8)  ch3ll@megan-precision5550  ~/git/salt  ➦ cb056ac98b <B>  git tag -a v3006.1 -m "Version 3006.1"
(heist-3.8)  ch3ll@megan-precision5550  ~/git/salt  ➦ cb056ac98b <B>  git checkout v3006.1    
HEAD is now at cb056ac98b skip if no docker and fix failing test
(heist-3.8)  ch3ll@megan-precision5550  ~/git/salt  ➦ cb056ac98b <B>  salt --version                        
salt 3006.1
```

```
(heist-3.8)  ch3ll@megan-precision5550  ~/git/salt  ➦ cb056ac98b <B>  git tag -a v3006.1 -m "v3006.1"       
(heist-3.8)  ch3ll@megan-precision5550  ~/git/salt  ➦ cb056ac98b <B>  git checkout v3006.1
HEAD is now at cb056ac98b skip if no docker and fix failing test
(heist-3.8)  ch3ll@megan-precision5550  ~/git/salt  ➦ cb056ac98b <B>  salt --version                 
salt 3006.1
```

**Comment by krionbsd** [comment]
> ping @krionbsd would changing the annotation tag impact packaging at all?

no, it shouldn't impact packaging

**Pull request merged**
