### PR TITLE
2015.2: Runner compatibility

### PR DESCRIPTION
**Pull request by jacksontj**
Please don't merge until #19729 is merged in

### CODE REVIEW

**Comment by jacksontj** [comment]
@rallytime I can't seem to get jenkins to run again :(

**Comment by rallytime** [comment]
@jacksontj He's running :)

You've got a pylint error it looks like here: https://jenkins.saltstack.com/job/salt-pr-lint-n/1211/violations/file/salt/runners/doc.py/ (if that variable is indeed already defined, pylint might need to be updated...let us know)

The other two are still running (Ubuntu 14 and CentOS 7).

**Comment by jacksontj** [comment]
@rallytime did this one finish?

**Comment by rallytime** [comment]
Yeah, it did. But only CentOS 7 came back: https://jenkins.saltstack.com/job/salt-pr-rs-cent7-n/785/

It would be nice to get some pylint data back, so I'll run these again and see if we can get Ubuntu 14 to give some results as well.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
@jacksontj There we go. Those test failures should all be relevant to this pull request in one way or another. They are not currently present on develop.

@cachedout ping

**Comment by rallytime** [comment]
This one did restart here: https://jenkins.saltstack.com/job/salt-pr-dsl/1338/

Not sure why the plugin display isn't updating here, but the results will be posted there when everything finishes up.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
@jacksontj I merged #19729 does this need any additional code before merging?

**Comment by rallytime** [comment]
@jacksontj The netapi tests are related to this change, but the other ones are not. I suspect that whatever you did to fix those test failures on the develop version of this PR just needs to be applied here as well.

**Comment by jacksontj** [comment]
@rallytime  Looks like there were some merge conflicts in some previous merge from 2015.2 to develop which I picked up in my develop version. This one should work-- the netapi tests seem to pass locally at least.

**Comment by jacksontj** [comment]
K, another batch-- this includes fixes for the tornado stuff and a rebase on a newer 2015.2

**Comment by cachedout** [comment]
@jacksontj Are the tornado fixes already in develop or do we need to try and merge those forward independently?

**Comment by jacksontj** [comment]
@cachedout Not in there, just opened #20178 to merge them into develop

**Comment by cachedout** [comment]
Many thanks!

**Comment by rallytime** [comment]
Woot! Look at all that green!

**Comment by jacksontj** [comment]
Apparently with all the rebasing i dropped my pylint fix. Just re-added it, so now we should be ready for merge.

@rallytime @cachedout

**Comment by thatch45** [comment]
WOHOOOO! Finally there!

**Pull request merged**
