### PR TITLE
Fluorine

### PR DESCRIPTION
**Pull request by rohitravirane**
### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

Yes/No

### Commits signed with GPG?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by terminalmage — CHANGES_REQUESTED** [review]
This PR looks to have been opened against the wrong branch. Can you please either A) use the "Edit" button to change the head branch, or B) close this and open a new PR?

**Comment by s0undt3ch** [comment]
This has way too many commits. And the title doesn't even suggest what to look for, ie, what was your actual change...

**Comment by s0undt3ch** [comment]
By too many commits, I mean, unrelated commits.

**Comment by terminalmage** [comment]
I'm closing this. Please open a new pull request against the appropriate branch, with more information (as I'm not even sure what this PR is supposed to address).

**Pull request closed without merging**
