### PR TITLE
Fix solaris network

### PR DESCRIPTION
**Pull request by dmurphy18**
### What does this PR do?
Fix use of tail on Solaris in execution module network

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/40170
https://github.com/saltstack/salt/pull/40164

### Previous Behavior
use of network.default_route returned an error

### New Behavior
network.default_route now returns expected output

### Tests written?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by sjorge** [comment]
My comments from the other PR still hold through, doing a fallback to ```salt.utils.which('tail')``` for the SunOS family of systems that are not Sun or Oracle Solaris would be preferred.

**Comment by dmurphy18** [comment]
@sjorge Updated changes which should be independent of which version of tail used on Solaris and Sun like OS.  Tested with both /usr/bin/tail and /usr/xpg4/bin/tail on both Solaris 10 and 11.

**Comment by sjorge** [comment]
LGTM

**Comment by cachedout** [comment]
Go Go Jenkins!

**Review by cachedout — APPROVED** [review]
Looks like these are all gated behind platform checks. :+1:

**Pull request merged**
