### PR TITLE
Update influx_retention_policy state

### PR DESCRIPTION
**Pull request by Orlando-Richards**
### What does this PR do?

Update to influx_retention_policy state to manage the state of the retention period, replication setting, and default status of the retention policy.

### What issues does this PR fix or reference?

Fixes issue #46180 

### Previous Behavior

retention period, replication setting and default status settings were not statefully managed

### New Behavior

retention period, replication setting and default status settings are statefully managed

Note that the "default" status is dependent on other policies - there will always be one, and only one, default set to true. This means that:
 * changing state from false to true on one policy will change it from true to false on all other policies;
 * if only one policy exists, it will always be set to true
This state will always report if it is different than specified in the state options, and attempt to change it if required.

### Tests written?

No - no prior tests existed to modify/extend.

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by OrlandoArcapix** [comment]
Apologies - spotted a mistake. Will re-do and open a new pull request.

**Comment by OrlandoArcapix** [comment]
Fixed the missing code issue - pull request re-opened.

**Comment by garethgreenaway** [comment]
@OrlandoArcapix Looks like there are a few LINT errors.

**Comment by cachedout** [comment]
re-run all

**Comment by rallytime** [comment]
Hi @OrlandoArcapix There are several lint errors on this: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/20722/violations/file/salt/states/influxdb_retention_policy.py/

Can you fix those up?

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
