### PR TITLE
Replace pchanges with changes to make onchanges/prereq work in test mode

### PR DESCRIPTION
**Pull request by terminalmage**
Fixes https://github.com/saltstack/salt/issues/49753
Fixes https://github.com/saltstack/salt/issues/45895

### CODE REVIEW

**Comment by cachedout** [comment]
@terminalmage There are some lint errors that need some attention, please. Thanks!

**Comment by terminalmage** [comment]
@cachedout Done.

**Review by isbm — APPROVED** [review]

**Comment by rallytime** [comment]
@terminalmage There is a test failing here: https://jenkinsci.saltstack.com/job/pr-kitchen-ubuntu1604-py2/job/PR-49832/5/

**Review by gtmanfred — APPROVED** [review]

**Comment by terminalmage** [comment]
Test should pass now, just needed to be updated to reflect pchanges removal

**Comment by terminalmage** [comment]
I'll add this on Tuesday.

**Comment by terminalmage** [comment]
@rallytime Since I just opened a PR to make a documentation addition in the same section that documentation of onchanges/prereq would have needed to go, rather than making conflicting changes that would require a rebase I decided to add them to the other PR (https://github.com/saltstack/salt/pull/49864).

**Review by twangboy — APPROVED** [review]

**Review by rallytime — APPROVED** [review]

**Comment by Oloremo** [comment]
Really I'd like this to be ported to Fluorine. Test mode makes close to 0 sense without seeing diffs.

**Comment by gtmanfred** [comment]
@saltstack/team-core based on comments from the community, it might be a good idea to backport this https://github.com/saltstack/salt/issues/45895#issuecomment-426005457

**Comment by angeloudy** [comment]
Which release will this PR be merged into?
I cannot believe that 2019.2.0 is released with such a huge bug not fixed.

**Comment by KChandrashekhar** [comment]
After discussion with Tom, it's been determined this needs to be back ported

**Pull request merged**
