### PR TITLE
Add a check workflow run workflow

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
Add a check workflow run workflow

This allows failed workflows to be restarted two more times, automatically, if less than half of the jobs failed.

This workflow should be removed as soon as we can have a more stable test suite by removing flaky test failures.

### CODE REVIEW

**Comment by ITJamie** [comment]
Just wondering is there anything tracking or documenting which tests are flaky? this would start to hide flaky runs

**Comment by s0undt3ch** [comment]
> Just wondering is there anything tracking or documenting which tests are flaky? this would start to hide flaky runs

We used to maintain a list from Jenkins failures, and we have also created some issues about failing tests.
Once we finish the work on our CI pipeline, I'm thinking on getting something cooked(coded) to get this listing created automatically.

**Comment by s0undt3ch** [comment]
I forgot to mention, because we look at the tests every day, we start to identify these flaky tests.

But your question is valid and spot on, we should keep these somewhere.

**Comment by s0undt3ch** [comment]
This PR only touches the GH actions workflows, which are passing.

Extraordinary self merge.

**Comment by ITJamie** [comment]
just a note on this. I pulled in the master branch into one of my pr branches. 
some of the jobs seem to have just been marked as cancelled and not retried? should these have been autorestarted?

https://github.com/saltstack/salt/actions/runs/4097662946/jobs/7067988187

**Comment by s0undt3ch** [comment]
> just a note on this. I pulled in the master branch into one of my pr branches. some of the jobs seem to have just been marked as cancelled and not retried? should these have been autorestarted?
> 
> https://github.com/saltstack/salt/actions/runs/4097662946/jobs/7067988187

That's another, known, issue with our self hosted runners setup which will get addressed as soon as possible.

**Comment by s0undt3ch** [comment]
And, because we can't separate human workflow cancellations from our self hosted runners setup cancellations, we don't automatically retry.

**Comment by s0undt3ch** [comment]
> would it be possible to add something like "retry cancelled" as one of the comment commands. that way it would be quick to target multiple jobs?

What do you mean exactly?

**Comment by ITJamie** [comment]
right now when on a pr to retry a failed task you need to send multiple comments like "re-run pr-arch-lts-x86_64-py3-pytest", "re-run pr-centos-7-x86_64-py3-pytest" as an example comments. it would be really nice if there was support for a "re-run cancelled" command that would re-run all the cancelled tests

**Comment by s0undt3ch** [comment]
Ah, you're talking about our Jenkins rerun "feature". We're moving away from Jenkins, and we won't be updating that functionality because of it.
With the new GH Actions pipelines, when a step(or multiple) fails, when the pipeline finishes, GH gives you an option, in their UI, to rerun all failed steps.
This PR just automates that procedure, in some conditions.

**Pull request merged**
