### PR TITLE
Don't open the logfile in vain

### PR DESCRIPTION
**Pull request by marbx**
### What does this PR do?
Don't open the logfile in vain.

### CODE REVIEW

**Comment by fdamstra** [comment]
I love the first part, return if len(0). But would the second part (filtering out other events) be better handled by the event_return_blacklist? I worry that this could be throwing away information that others want.

**Comment by markuskramerIgitt** [comment]
@fdamstra, `not 'id' in event['data']` does not block any return data, so indeed you need event_return_blacklist.

Example:

After you issue `salt \* test.ping` you will first see the 'outgoing command event', which has no `'id' in event['data']`, which is no return data:
```
{'tag': 'salt/job/20170419204355903464/new', 'data': {'tgt_type': 'glob', 'jid': '20170419204355903464', 'tgt': '*', '_stamp': '2017-04-19T18:43:55.904144', 'user': 'root', 'arg': [], 'fun': 'test.ping', 'minions': ['bob']}}
```


And then you see return data, with `'id' in event['data']`:
```
{'tag': 'salt/job/20170608115910286308/ret/bob', 'data': {'fun_args': [], 'jid': '20170608115910286308', 'return': True, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2017-06-08T09:59:12.177092', 'fun': 'test.ping', 'id': 'bob'}}
``` 


Another way to detect return data is matching tag with `salt/job/*/ret/*`.
I believe that is equivalent.

**Comment by fdamstra** [comment]
@markuskramerIgitt, I follow, and my point is that the first example, though not return data, is still _useful_ data. For my purposes, I want to keep this information as it lets me know how the minion was targeted, and this PR would discard it. 

I think the better way to discard the data would be to use whitelist or blacklist, which leaves the choice to the particular user/admin.

**Comment by markuskramerIgitt** [comment]
@fdamstra, you convinced me that non-return data should not be skipped hard-wired.
I remove the second condition and will look into flexibly blocking non-return data.

**Review by fdamstra — APPROVED** [review]
Good improvement.

**Review by cachedout — APPROVED** [review]

**Pull request merged**
