### PR TITLE
Issues/30643 merge forward fixes

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
### What does this PR do?

Merge forward #31512 and #30796 into 2015.8
### What issues does this PR fix or reference?

This is for @Ch3LL to check #30643.

### CODE REVIEW

**Comment by DmitryKuzmenko** [comment]
I'll check what's wrong with the tests on Monday.

**Comment by DmitryKuzmenko** [comment]
Sorry, had no time today to check this. Will do tomorrow.

**Comment by cachedout** [comment]
I don't believe the test failures here are related to this PR. Merging.

**Comment by DmitryKuzmenko** [comment]
Thank you!

**Pull request merged**
