### PR TITLE
How to create master profiling graphs on Windows

### PR DESCRIPTION
**Pull request by marbx**

### CODE REVIEW

**Comment by mattp-** [comment]
nice 👍

**Review by cmcmarrow — APPROVED** [review]

**Comment by cmcmarrow** [comment]
Thanks for the help!

**Review by xeacott — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Comment by markuskramerIgitt** [comment]
Thanks for approving, @twangboy, but this this PR still targets the develop branch. 

I need singe-step-by-by-steps instructions for rebase to master, or I must resubmit.

**Comment by markuskramerIgitt** [comment]
I opened  pull request #55328 because I assume merging is impossible.

Please correct me if I am wrong, and merge either one.

**Comment by markuskramerIgitt** [comment]
Closing because pull request #55328 because has been merged

**Pull request closed without merging**
