### PR TITLE
INFRA-7967 - add resource tagging functions to boto_dynamodb exec module

### PR DESCRIPTION
**Pull request by tkwilliams**
- list_tags_of_resource()
- tag_resource()
- untag_resource()

Note that the original module was written against boto2, which still has not added support for tagging dynamodb resources, so these new functions required adding boto3 imports in order to provide this functionality.

### CODE REVIEW

**Comment by tkwilliams** [comment]
@rallytime Is there anything needed on this, or it just still catchup from the holiday rush :)

**Comment by sagetherage** [comment]
@tkwilliams @rallytime we are no longer taking changes against the develop branch, can either of you rebase against the master branch or perhaps there is another PR to reference and then close this one? If not we may close this as abandoned.

**Comment by rallytime** [comment]
@sagetherage It looks to me like the author could be waiting on someone from the Salt team to review this submission. No one responded for over a year since my request for someone on the Core team to take a look. That seems a little unfair to now consider this abandoned.

**Comment by sagetherage** [comment]
@rallytime  I cannot have this reviewed as-is and it will need intervention to get a review. I have attempted to contact @tkwilliams several times outside of this PR and had no response.

**Comment by terminalmage** [comment]
So, a few things here:

- This has been awaiting review for (as of right now) **455** days. I don't know how many days you gave @tkwilliams to get back to you. Nonetheless, I would suggest that a bit of patience is in order. After all, he's been _quite_ patient in waiting for a review, wouldn't you agree?
- There is literally nothing preventing a review. There is diff right here in this PR. Assuming that it looks fine, it is also quite easy to run isort and black, and cherrypick onto master.**<sup>1</sup>**
- Bus-tossing someone who took the time to submit code is, to put it mildly, a bad look. I really wish you wouldn't do that.
- Given the **four hundred fifty-five** days this has been waiting for a review, it certainly looks like this PR has been abandoned. I just don't think it was @tkwilliams that abandoned it.

**<sup>1</sup>** I did this, and it took 5 minutes. I also added tests, which took a further 40 minutes. If I can do it, the core team certainly can.

**Comment by tkwilliams** [comment]
Hi @terminalmage @sagetherage and of course @rallytime  -- HOWDY :)

Many apologies, I'm no longer at the company where I wrote this (they were very kind in letting me devel LOTS of salt module code and contribute it back, but sadly they were bought, merged, and I became redundant in the face of the juggernaut that is Terraform - on AZURE no less :-/ )

I also find that GH whacked my salt project membership at some point - likely due to my laxness in setting up 2fa.  Though I DID finally get off my butt and do it last month at least....

Anywho, I don't have any AWS access anymore, nor in truth any interest in dynamodb (boto or otherwise) - I only wrote this because we needed it at the time.  So while it did in fact work GREAT when I PR'ed it (gosh, almost a year and a half ago), I'm not in a position to really do much with it.  If someone wants to hack it back into shape that'd be awesome, but if it falls in the bucket due to bit-rot I won't lose any sleep either :)

I have finally wangled my current boss into using salt-ssh so I may yet be able to contribute some more back to you folks, but we're in the process of moving all the legacy bare metal into GCS at the moment so I don't expect to be working on any boto code at all in the near-term.

Havahappi!

**Comment by terminalmage** [comment]
@tkwilliams The code was in decent shape and easily merged onto `master`. I took care of resubmitting it on top of master in https://github.com/saltstack/salt/pull/57500. This PR can be closed.

**Comment by tkwilliams** [comment]
As always, M'sieur @terminalmage, you are a gentleman and a scholar :)

**Comment by terminalmage** [comment]
_De rien!_

**Comment by sagetherage** [comment]
@tkwilliams contact me directly if you want to discuss adding you back into the SaltStack GH org, it is complete up to you and I can help if that is helpful to you: sagetherage at saltstack dot com

**Pull request closed without merging**
