### PR TITLE
Remove repr formatting flag in places where it is used solely for quoting

### PR DESCRIPTION
**Pull request by terminalmage**
Using repr will insert a `u` before the string in Python 2.

``` python
>>> u'something something {0!r}'.format(u'foo')
u"something something u'foo'"
```

### CODE REVIEW

**Comment by cachedout** [comment]
@terminalmage We might need the Composer test adjusted.

**Comment by terminalmage** [comment]
Lint failures will require salt-pylint to be updated in pypi, so that jenkins sees the new error case I added in https://github.com/saltstack/salt-pylint/pull/6 and referenced in f18d357.

**Comment by rallytime** [comment]
@jtand Can you help with the pylint situation ^ ?

**Comment by s0undt3ch** [comment]
A new SaltPyLint relase is out - https://pypi.python.org/pypi/SaltPyLint/2016.6.25

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by jtand** [comment]
SaltPylint is updated. Re-running.

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by terminalmage** [comment]
We have linter fixes coming up the pipe from 2015.8, once they make their way into develop I will need to rebase.

**Comment by terminalmage** [comment]
Lint fixes pushed, but it looks like the build may have failed in the middle of the pylint run, so there may be more that show up this time.

**Comment by jtand** [comment]
Go Go Jenkins!

**Pull request merged**
