### PR TITLE
Update deps osx

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?
Update dependencies in OSX for Neon

### Tests written?
No

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by waynew** [comment]
If I understood our team discussion correctly, we'll be doing this *post* Neon release, right?

**Comment by sagetherage** [comment]
this happens just after the release but yes is for Neon -- a confusing process we definitely need to review for next time.

**Comment by waynew** [comment]
@twangboy looks like some conflicts here

**Review by waynew — CHANGES_REQUESTED** [review]
@twangboy can you fix the conflicts here?

**Pull request closed without merging**
