### PR TITLE
Fix apache.config with multiple statement

### PR DESCRIPTION
**Pull request by viktorkrivak**
### What does this PR do?
At this moment when you post more than one statement in config only last
is used. Also file is rewrite multiple times until last statement is
written.

### Previous Behavior
salt '*' apache.config /etc/httpd/conf.d/ports.conf config="[{'Listen': '8080'}, {'Proxy': "Something"}]"
Ends only with
   Proxy Something
and ignore Listen 8080,

### New Behavior
salt '*' apache.config /etc/httpd/conf.d/ports.conf config="[{'Listen': '8080'}, {'Proxy': "Something"}]"
   Listen 8080
   Proxy Something

### Tests written?

No

### CODE REVIEW

**Comment by gtmanfred** [comment]
Can you rebase this and submit it against 2016.11?

https://docs.saltstack.com/en/latest/topics/development/contributing.html#the-current-release-branch

And then we will forward merge it to 2017.7 and develop?

Thanks,
Daniel

**Review by vutny — APPROVED** [review]
Excellent. Now it is finally possible to write multiple `VirtualHost` directives to one file!

**Review by vutny — APPROVED** [review]

**Comment by viktorkrivak** [comment]
@gtmanfred Ok I create new PR. Just give me a moment to persuade git to do what I want.

**Comment by gtmanfred** [comment]
Closing for #43191

**Pull request closed without merging**
