### PR TITLE
Fix boto_secgroup_test

### PR DESCRIPTION
**Pull request by justinta**
### What does this PR do?

New version of boto was released. This brings the test_get_config_single_rule_group_name in line with new changes to boto. 
### What issues does this PR fix or reference?

Fixes failing test
### Tests written?

Yes

### CODE REVIEW

**Comment by eradman** [comment]
What version of boto does this test work with? I received the following failure with boto 2.40.0:

    OrderedDict([('name', 'boto_secgroup-xyppfbvzkxte'), ('group_id',
    u'sg-a64f430e'), ('owner_id', u'111122223333'), ('description',
    'boto_secgroup-xyppfbvzkxte'), ('tags', {}), ('rules', [{'to_port': 22,
    'from_port': 22, 'ip_protocol': u'tcp', 'cidr_ip': u'0.0.0.0/0'}]),
    ('rules_egress', [{'to_port': -1, 'from_port': -1, 'ip_protocol': u'-1',
    'cidr_ip': u'0.0.0.0/0'}])])
    !=
    OrderedDict([('name', u'boto_secgroup-xyppfbvzkxte'), ('group_id',
    u'sg-a64f430e'), ('owner_id', u'111122223333'), ('description',
    u'boto_secgroup-xyppfbvzkxte'), ('tags', {}), ('rules', [{'to_port': 22,
    'from_port': 22, 'ip_protocol': u'tcp', 'cidr_ip': u'0.0.0.0/0'}]),
    ('rules_egress', [])])

**Comment by jtand** [comment]
@eradman We are using 2.40.0 as well. The change for us happened right after the 2.40.0 release.

It is interesting that what you're seeing is opposite from what we were getting in our tests. What OS are you seeing this on? Can you also post your versions report?

**Comment by eradman** [comment]
I'm running on OpenBSD 5.9

    (saltenv)$ pip2.7 list
    You are using pip version 7.0.3, however version 8.1.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    backports-abc (0.4)
    backports.ssl-match-hostname (3.5.0.1)
    boto (2.40.0)
    certifi (2016.2.28)
    Flask (0.10.1)
    funcsigs (1.0.0)
    futures (3.0.5)
    httpretty (0.8.10)
    itsdangerous (0.24)
    Jinja2 (2.8)
    MarkupSafe (0.23)
    mock (2.0.0)
    moto (0.4.23)
    msgpack-python (0.4.7)
    ordereddict (1.1)
    pbr (1.9.1)
    pip (7.0.3)
    pycrypto (2.6.1)
    PyYAML (3.11)
    pyzmq (15.2.0)
    requests (2.9.1)
    salt (2016.3.0-355-gfec256e)
    SaltTesting (2015.2.16)
    setuptools (17.0)
    singledispatch (3.4.0.3)
    six (1.10.0)
    tornado (4.3)
    Werkzeug (0.11.8)
    wheel (0.24.0)
    xmltodict (0.10.1)

Maybe worth obliterating and re-creating my virtualenv?

**Comment by eradman** [comment]
Recreating the virtualenv did solve the problem. All good!

**Pull request merged**
