### PR TITLE
Datadog execution module

### PR DESCRIPTION
**Pull request by onlyanegg**
### What does this PR do?
This pull request adds an execution module for the Datadog API. In its current form, it adds support for scheduling and canceling downtime. 

### What issues does this PR fix or reference?
None

### Tests written?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by garethgreenaway** [comment]
@onlyanegg Awesome addition!  Looks like there are a couple lint issues that need fixing.

**Comment by onlyanegg** [comment]
Thanks, @garethgreenaway. I may have been a little trigger happy. I'll make sure to go back and lint it and correct any errors.

**Comment by garethgreenaway** [comment]
@onlyanegg thanks!

**Comment by cachedout** [comment]
@onlyanegg Were you able to go back and make these lint changes?

**Comment by onlyanegg** [comment]
@cachedout, no, sorry. I've been busy with other things. I'll try to get this knocked out in the next couple of days.

**Comment by cachedout** [comment]
@onlyanegg If you feel that tests are appropriate, we would welcome them.

**Comment by onlyanegg** [comment]
@garethgreenaway, I see that you merged develop into this branch, and now my local copy is behind. I guess I should just `git pull` these updates?

**Comment by cachedout** [comment]
@onlyanegg You likely don't need to but it's best to do so just to be safe.

**Comment by onlyanegg** [comment]
ok, thx @cachedout

**Review by garethgreenaway — APPROVED** [review]

**Comment by onlyanegg** [comment]
Why don't the docs appear immediately under the development branch? 
https://docs.saltstack.com/en/develop/ref/modules/all/index.html

**Pull request merged**
