### PR TITLE
Add file pruned state

### LINKED ISSUE #62178: [FEATURE REQUEST] Add a rmdir state
**Is your feature request related to a problem? Please describe.**
There isn't really a good native solution for "remove all empty directories in this tree".

**Describe the solution you'd like**
A native rmdir state which can delete empty directories below a given root.

**Describe alternatives you've considered**
Usually this problem is solved with some Jinja gymnastics to find empty directories and pass to `file.absent`, but that can be dangerous if the find operation is too broad as `file.absent` essentially performs the equivalent of `rm -rf`

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

### PR DESCRIPTION
**Pull request by nicholasmhughes**
### What does this PR do?
This PR adds a `file.pruned` state which can delete empty directories within a given root.

### What issues does this PR fix or reference?
Fixes: #62178 

### Previous Behavior
No native state supported this workflow.

### New Behavior
Empty directories can easily be pruned from a tree. Note that the `file.rmdir` execution module operation was also slightly changed. Errors encountered previously returned the error string. This was changed to a more uniform boolean return. This is unlikely to affect any logic as users were most likely checking for `True` returns on success and then using a broad `else` statement, because "falsey" behavior wasn't possible with `True` vs `str` returns.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by OrangeDog** [comment]
I feel like this would be better as a `recursive` argument to `file.absent` than as a whole separate state.

**Comment by nicholasmhughes** [comment]
re-run pr-ubuntu-2004-amd64-py3-tcp-pytest

**Comment by nicholasmhughes** [comment]
open to suggestions

**Comment by nicholasmhughes** [comment]
re-run pr-centos-7-x86_64-py3-m2crypto-pytest

**Comment by Ch3LL** [comment]
looks like there is a merge conflict. Also maybe dir_absent instead of rmdir?

Let me ask the rest of the core team what they think of the naming of the state function here.

**Comment by whytewolf** [comment]
personally this seems more like a pruned_tree more than absent or rmdir.

**Comment by nicholasmhughes** [comment]
re-run pr-debian-11-amd64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-debian-11-amd64-py3-pytest

**Review by waynew — COMMENTED** [review]
Definitely love the idea behind this! @Ch3LL asked for some feedback:

- I don't like `rmdir` as the state name - sometimes we can't help but to name the states as verbs instead of adjectives, but generally `.removed` or `.absent` for states, with `.remove` or similar action words for the execution modules. I like Thomas' `pruned` suggestion. It's better than `dir_absent` which was the only thing I could think of :joy: That also naturally leads to the module being `prune` and the state `pruned`, which I like a lot. I guess that would mean that we'd just leave `rmdir` as is and create a `prune` module, if we wanted to make that change.
- I have some thoughts about the deleting what we can but then failing. Maybe it doesn't matter and it's OK to partially fail. We *could* check that at least the folders are empty before attempting to delete all of them - basically do the existing `for` loop but instead of 

```
os.rmdir(subdir_path)
deleted.append(subdir_path)
```

do something like

```
if os.listdir(subdir_path):
    errors.append([subdir_path, "Directory is not empty"])
else:
    to_delete.append(subdir_path)

for dir in to_delete:
    try:
        os.rmdir(dir)
    except OSError as exc:
        ...
```

But... I don't know if that's super important :shrug: - anyway, just my thoughts - I don't feel super strongly about them (aside from liking adjectives for states and verbs for modules)

**Comment by nicholasmhughes** [comment]
re-run pr-ubuntu-2204-amd64-py3-pytest

**Review by Ch3LL — APPROVED** [review]

**Review by whytewolf — APPROVED** [review]

**Review by waynew — APPROVED** [review]
I'm good with this :+1: I *did* just realize that it might just be worth noting in the documentation that it will take the steamroller approach - i.e. it will prune whatever directories it can, rather than bailing out either at the first error or looking before it leaps.

I don't think it should hold up merging the PR but it might be worth a follow-up PR :shrug:

**Pull request merged**
