### PR TITLE
Ability to set permissions in the Windows Registry

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?
Adds ability to modify the DACL to the `win_reg` module.
Moves some shared functions to the `win_dacl` salt util.
Fixes documentation formatting and spelling
Fixes an issue with resetting inherited and non inherited permissions

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/44126

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?
Yes/No

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by rallytime** [comment]
A change like this is going to need some test coverage.

**Comment by twangboy** [comment]
@rallytime I am writing tests. Hence the WIP

**Review by rallytime — APPROVED** [review]
👍 

LGTM. Thank you for writing tests and I love it when we can consolidate code like this. Well done.

I'd like someone more familiar with Windows, like @dwoz to review this, but from my perspective this looks good.

**Review by dwoz — APPROVED** [review]
Looks nice, approved.

**Pull request merged**
