### PR TITLE
Added a note regarding logging configuration.

### PR DESCRIPTION
**Pull request by abednarik**
Simple example on how to turn off logging.

Related to issue #29635

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Most of Salt's CLI tools also support `--log-level=quiet`

**Comment by abednarik** [comment]
Hi @s0undt3ch  do you think would be useful to also add that in the documentation?

Cheers.

**Comment by s0undt3ch** [comment]
Yes, I'm guessing that the `--log-level` information is also lacking, so, it might help others.

**Comment by abednarik** [comment]
Ok.  Will add that also.

**Comment by cachedout** [comment]
@abednarik Please let me know when this is ready to go. Thanks!

**Comment by abednarik** [comment]
HI @cachedout  hope is ready :)

Thanks.

**Comment by cachedout** [comment]
Thanks @abednarik

**Pull request merged**
