### PR TITLE
small enhancement to data module; pop()

### PR DESCRIPTION
**Pull request by The-Loeki**
Very simple addon to allow to pop() values from data

### CODE REVIEW

**Comment by The-Loeki** [comment]
See also the more comprehensive #24168

**Comment by rallytime** [comment]
@The-Loeki Any reason you're adding this new function to the 2015.5 branch instead of develop. New features and functions typically go into the develop branch, as you've done in the more comprehensive pull request you mentioned above.

**Comment by The-Loeki** [comment]
hi @rallytime! 3 reasons:
1. It's a very very simple addition with no consequences for the rest of the env
2. It's a very very useful addition IMHO; without it, you can either manually code the same idea (which especially in Jinja is no fun) or update the data leaving a 'stale' entry with None in it
3. I wants it in our env *now* ;)

As you saw I did a more comprehensive expansion of stuff in `develop` for the reasons you gave.

**Comment by rallytime** [comment]
No problem. Just wanted to double check. Can you add a versionadded tag to this function here as well?
```
.. versionadded:: 2015.5.2
```
Also, if these functions are the same in this PR and the one against develop, they should both end up in the correct place in the develop branch with a merge forward. However, these will conflict. Either this function should be removed from the develop PR, or @basepi should know to take this 2015.5 version on the next merge forward (so the versionadded tag is correct in our docs).

**Comment by The-Loeki** [comment]
Like this? (See also #24168)

**Comment by rallytime** [comment]
That's perfect! Thanks!

**Comment by basepi** [comment]
This looks great, thanks!

**Pull request merged**
