### PR TITLE
Some Debian network (debian_ip) refactoring

### PR DESCRIPTION
**Pull request by MTecknology**
### What does this PR do?

Commit a058e65 refactors the logic used in debian_ip._parse_settings_eth(). It re-works the logic used to put options into dictionaries and simplifies how some options are shared.

- Adds `-enable_ipv4:` which is meant for future deprecation of IPv4
- Makes better use of `-enable_ipv6:`
- Adds support for `-ipv4<opt>:` prefix (similar to `-ipv6<opt>:`)
- Adds support for sharing options between IPv4/v6
- Supports overriding any IPv4/v6 option
- Makes `-proto:` a required field

Commit 038261c adds new unit tests and updates/fixes existing tests. 

- Unit tests have been updated for modified behavior:
  + Make sure bond options are shared between IPv4/v6
  + Added tests for reported/discovered issues
- Added tests:
  + Check for v4/v6-only option sharing/overwriting
  + Check that netmask/gw is not added unless specified

Commit dad829e reworks the debian_eth.jinja template.

- Removes a lot of unique if's and turns them into a loop
- Removes extraneous newlines in interfaces file
- Cleans up redundancies
- Allows all options to be space-delimited list, line-delimited list, or string

### What issues does this PR fix or reference?

- #46388
- Fixes other unreported issues

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by MTecknology** [comment]
I have no idea how what I changed could have effected the tests that failed. Any hints?

**Review by cachedout — APPROVED** [review]

**Comment by rallytime** [comment]
@MTecknology I think this is a pretty big change that I'd like to let sit in develop for a while.

**Review by garethgreenaway — APPROVED** [review]

**Comment by dynek** [comment]
> @MTecknology I think this is a pretty big change that I'd like to let sit in develop for a while.

When wil this make it into a package available from http://repo.saltstack.com/apt/debian/9/amd64/?

**Comment by MTecknology** [comment]
@dynek It'll show up in whatever comes after 2018.3.

**Comment by dynek** [comment]
@MTecknology I missed your answer. I just checked it and I do not see any mention of neon: https://docs.saltstack.com/en/latest/topics/releases/version_numbers.html
Do you think this will make it into a version after Fluorine is released?

One more question, is this affecting server or client side? What if my server is running 2017 while clients run 2018? Just trying to grasp if I should be upgrading both or if client is sufficient.

Thank you!

**Comment by rallytime** [comment]
@dynek Yes, `Neon` is the feature release after `Fluorine`. I have updated that document in #50354 to include a few more release codenames.

**Comment by dynek** [comment]
Surprising that it takes so long to make it into a released version.

/me puzzled but will wait :-)

**Comment by MTecknology** [comment]
There's two reasons for this particular change taking a long time to land. 1) It's a really massive change that includes non-minor changes in behavior. 2) The next feature release is getting ever closer and they're shooting for stability so major changes like this won't make it in.

**Comment by MTecknology** [comment]
@dynek I guess I was wrong about those two reasons!

I think I missed the 3000.1 release, but it should wind up in the next one... this time.

**Comment by dynek** [comment]
It's been a while :-) Just tested this and I confirm it fixes the problem I was having.

Thank you @MTecknology

**Pull request merged**
