### PR TITLE
Potential solution for #38265

### PR DESCRIPTION
**Pull request by mirceaulinic**
### What does this PR do?

Inject ```__utils__``` object into proxy module.

### What issues does this PR fix or reference?

#38265

### CODE REVIEW

**Comment by mirceaulinic** [comment]
Mmm... I'm afraid this is much over my level of understanding:

```
2016-12-15 08:55:00,811 [salt.loader      ][CRITICAL][31483] Failed to load grains defined in grain file napalm.model in function <function model at 0x7fd5fe9d7c80>, error:
Traceback (most recent call last):
  File "/state/home/mircea/salt/salt/loader.py", line 724, in grains
    ret = fun(proxy)
  File "/state/home/mircea/salt/salt/grains/napalm.py", line 143, in model
    return {'model': _get_grain(proxy, 'model')}
  File "/state/home/mircea/salt/salt/grains/napalm.py", line 76, in _get_grain
    grains = _retrieve_grains(proxy)
  File "/state/home/mircea/salt/salt/grains/napalm.py", line 67, in _retrieve_grains
    GRAINS_CACHE = proxy['napalm.grains']()
  File "/state/home/mircea/salt/salt/loader.py", line 1089, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/state/home/mircea/salt/salt/utils/lazy.py", line 98, in __getitem__
    return self._dict[key]
KeyError: 'napalm.grains'
```

**Comment by rallytime** [comment]
Requested a review from @cro per [this comment](https://github.com/saltstack/salt/issues/38265#issuecomment-267502304)

**Comment by mirceaulinic** [comment]
@cro would you mind having a look and advise? Thanks!

**Comment by cachedout** [comment]
Bump @cro

**Comment by cro** [comment]
See #38829

**Comment by cro** [comment]
@mirceaulinic: I'm closing this in favor of #38829

**Pull request closed without merging**
