### PR TITLE
replaced ',' for whitespace as split seperator for rabbitmq tags

### PR DESCRIPTION
**Pull request by s-schweer**
### What does this PR do?

  fix change handling for rabbitmq user tags
### Tests written?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by rallytime** [comment]
@s-schweer It looks like this change has caused some rabbitmq-related test failures. Would you mind taking a look? http://166.78.178.63:8080/job/PR/job/salt-pr-linode-ubuntu14-n/92/#showFailuresLink The failures that are related to this change are the following:
- unit.modules.rabbitmq_test.RabbitmqTestCase.test_list_users
- unit.modules.rabbitmq_test.RabbitmqTestCase.test_list_users_with_warning
- unit.states.rabbitmq_user_test.RabbitmqUserTestCase.test_present

The other test failures are not related. It looks like there is a small [pylint error](http://166.78.178.63:8080/job/PR/job/salt-pr-lint-n/385/violations/) as well.

If you run into trouble, let us know and we can lend a hand.

**Comment by s-schweer** [comment]
Hi,

there are two options:
1: i can fix the test
2: i can change the code back, but with the old code there are errors like thie:
    "msgpack can't serialize set('administrator'])" which i can fix with changing
    the output format to list instead of a set of list.
    I think the only reason for set was the ability to compute differences in states.rabbitmq_user
   which i fiexd as well.

So which option do you prefer?

KR Stefan

**Comment by jtand** [comment]
@s-schweer I prefer option number 1. I'm all for more accurate tests :)

**Comment by rallytime** [comment]
@s-schweer Thanks for the explanation. Option sounds great - I'd rather have more accurate tests as well.

**Comment by s-schweer** [comment]
Okay, done ;)

**Comment by jtand** [comment]
@s-schweer :+1: Thanks!

**Comment by rallytime** [comment]
Ah, one more test failure here that looks legitimate: http://166.78.178.63:8080/job/PR/job/salt-pr-rs-cent7-n/542/testReport/junit/unit.states.rabbitmq_user_test/RabbitmqUserTestCase/test_present/ 

Also there is still a lint error that needs to be taken care of: http://166.78.178.63:8080/job/PR/job/salt-pr-lint-n/395/violations/file/salt/states/rabbitmq_user.py/

**Comment by s-schweer** [comment]
okay,

i think it won't be a problem that now ['user'] is returned instead of ['u','s','e','r'] ;)

**Comment by s-schweer** [comment]
The test failure and the lint error are fixed now

**Comment by rallytime** [comment]
@s-schweer Ah, looks like there is [one more](http://166.78.178.63:8080/job/PR/job/salt-pr-lint-n/400/violations/file/tests/unit/states/rabbitmq_user_test.py/) syntax error:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/testing/tests/unit/states/rabbitmq_user_test.py", line 90
    changes = {'tags': {'new': ['user], 'old': 'user'}}
```

**Comment by s-schweer** [comment]
Okay, this typo is fixed as well

**Comment by rallytime** [comment]
These changes were merged in with #32079. Thanks @s-schweer!

**Pull request merged**
