### PR TITLE
[WIP] Slack fixes & improvements

### PR DESCRIPTION
**Pull request by eliasp**
**PLEASE DO NOT MERGE THIS PR YET - STILL WIP**

### What does this PR do?

In general, it improves Salt's Slack support.
More detailed:
- Fixes issues, such as #35425
- Adds support for:
  - [message attachments](https://api.slack.com/docs/message-attachments)
  - using emojis for the message sender's avatar
  - threaded Slack messages (still WIP and not yet pushed to this PR due to Slack API issues/bugs which need to be investigated first)
- Corrects minor consistency issues (e.g. inconsistently returned datatypes)
- Improves method documentation

### Tests written?

No, but the existing tests still work as expected.

### CODE REVIEW

**Comment by cachedout** [comment]
How are we doing on this one, @eliasp ? Still planning to come back and do more work here or is this complete?

**Comment by eliasp** [comment]
@cachedout Sorry, totally lost track of this one… will take care of it and complete it.

**Comment by cachedout** [comment]
@eliasp No worries. Thank you very much!

**Comment by cachedout** [comment]
Hi again @eliasp. Just checking in here. :]

**Comment by cachedout** [comment]
Hi @eliasp 
Since I didn't hear back from you, I am closing this for the time being. When you are ready to come back to this, please drop me a line and let me know and we will happily re-open this. Thanks very much.

**Pull request closed without merging**
