### PR TITLE
Make winrepo execution module use the same code as the runner

### PR DESCRIPTION
**Pull request by terminalmage**
This will keep the update_git_repos and genrepo functions from drifting.

### CODE REVIEW

**Comment by TheBigBear** [comment]
@terminalmage L1253 in minion.rst is set to "+    winrepo_dir: 'D:\winrepo'" surely that should be more something like "c:\salt\srv\salt\win\repo" ?

**Comment by terminalmage** [comment]
No, that is just an example of usage. Most (if not all) of the config params on that page have an example of how to use the config parameter, and most of them show how to set it to something other than the default. If you look above there, you can see the default value.

**Comment by terminalmage** [comment]
The value of ``winrepo_dir`` interacts with other options like ``winrepo_cachefile``, ``file_roots``, and ``winrepo_source_dir``. The documentation I added in this PR (in windows-package-manager.rst) tries to explain how they work together.

Just FYI, I'll be AFK for several hours as it is 03:15 here and I need sleep. :smile:

Please keep the feedback coming, I'll catch up in the morning.

**Comment by TheBigBear** [comment]
@terminalmage oh ok, sorry, spke too soon, my comment was based on the diff output and I didn't see the actual context, so sorry.

**Comment by terminalmage** [comment]
No problem... if it is confusing when viewed in context, I'm happy to change it. Good night! :smile:

**Comment by terminalmage** [comment]
Tests passed last time but the ubuntu VM did not return results. I kicked off another test run.

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by terminalmage** [comment]
All tests now passing.

**Pull request merged**
