### PR TITLE
Catch CommandExecutionError when the group in group_installed doesn't exist

### LINKED ISSUE #35819: pkg.group_installed doesn't handle missing package group
### Description of Issue/Question

A malformed package group can cause a unhandled exception, even if you are trying to skip said package gruop.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

CentOS7 with epel repo enabled:

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

```
MATE Desktop:
  pkg.group_installed:
    - skip:
      - admin-tools

[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('xfce', 'pkg.group_installed'), ('MATE Desktop', OrderedDict([('pkg.group_installed', [OrderedDict([('skip', ['admin-tools'])])])])), ('install-cinnamon-for-remlinux', OrderedDict([('pkg.installed', [OrderedDict([('pkgs', ['cinnamon'])])])]))])
[PROFILE ] Time (in seconds) to render '/var/cache/salt/minion/files/extra-desktops/init.sls' using 'yaml' renderer: 0.00969314575195
[DEBUG   ] LazyLoaded pkg.install
[DEBUG   ] LazyLoaded pkg.group_installed
[DEBUG   ] You should upgrade pyOpenSSL to at least 0.14.1 to enable the use of X509 extensions in the tls module
[DEBUG   ] Could not LazyLoad pkg.ex_mod_init
[INFO    ] Running state [MATE Desktop] at time 10:31:08.515147
[INFO    ] Executing state pkg.group_installed for MATE Desktop
[INFO    ] Executing command ['yum', '--quiet', 'groupinfo', 'MATE Desktop'] in directory '/root'
[INFO    ] Executing command ['yum', '--quiet', 'groupinfo', 'admin-tools'] in directory '/root'
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1733, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1651, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 2231, in group_installed
    diff = __salt__['pkg.group_diff'](name)
  File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 1899, in group_diff
    group_pkgs = group_info(name, expand=True)
  File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 1863, in group_info
    expanded = group_info(line, expand=True)
  File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 1839, in group_info
    raise CommandExecutionError('Group \'{0}\' not found'.format(name))
CommandExecutionError: Group 'admin-tools' not found

[INFO    ] Completed state [MATE Desktop] at time 10:31:14.453135 duration_in_ms=5937.988
[DEBUG   ] LazyLoaded highstate.output
local:
----------
          ID: MATE Desktop
    Function: pkg.group_installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1733, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1651, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 2231, in group_installed
                  diff = __salt__['pkg.group_diff'](name)
                File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 1899, in group_diff
                  group_pkgs = group_info(name, expand=True)
                File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 1863, in group_info
                  expanded = group_info(line, expand=True)
                File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 1839, in group_info
                  raise CommandExecutionError('Group \'{0}\' not found'.format(name))
              CommandExecutionError: Group 'admin-tools' not found
     Started: 10:31:08.515147
    Duration: 5937.988 ms
     Changes:   
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.22.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

### PR DESCRIPTION
**Pull request by rallytime**
### What does this PR do?

Includes an integration test to make sure this doesn't regress.
### What issues does this PR fix or reference?

Fixes #35819
### Previous Behavior

When using a `pkg.group_installed` state, like this:

```
test-group-installed:
  pkg.group_installed:
    - skip:
      - admin-tools
```

and the group doesn't exist, it would stack trace:

```
ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1733, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1651, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 2231, in group_installed
    diff = __salt__['pkg.group_diff'](name)
  File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 1899, in group_diff
    group_pkgs = group_info(name, expand=True)
  File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 1863, in group_info
    expanded = group_info(line, expand=True)
  File "/usr/lib/python2.7/site-packages/salt/modules/yumpkg.py", line 1839, in group_info
    raise CommandExecutionError('Group \'{0}\' not found'.format(name))
CommandExecutionError: Group 'admin-tools' not found
```
### New Behavior

The stacktrace is cleaned up and the state returns False with the error in the comment:

```
[ERROR   ] An error was encountered while installing/updating group 'test-group-installed': Group 'test-group-installed' not found
local:
----------
          ID: test-group-installed
    Function: pkg.group_installed
      Result: False
     Comment: An error was encountered while installing/updating group 'test-group-installed': Group 'test-group-installed' not found
     Started: 17:40:20.114296
    Duration: 3732.036 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   3.732 s
```
### Tests written?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cable2999** [comment]
This looks like a good fix.  I actually didn't test if the named package group exists.  The package group I was trying to install includes another package group...  and that sub-package group doesn't actually exist.  It looks like someone fixed the "MATE Desktop" package group in CentOS7 to no longer include the admin-tools, but my original intention was to be able to skip package groups installed by other package groups.  Would also fix this bug:  https://github.com/saltstack/salt/issues/31241 in at least a manual way since you could pkg.group_install gnome-desktop, and then skip gnome-desktop?

**Comment by rallytime** [comment]
@cable2999 Ahh I see what you're saying. It looks like the code that was causing the stacktrace happens _before_ we handle the skip options. I think this fix is a good one, so we don't stacktrace on a missing groupname, like you said, but this doesn't handle the skipped options like you were thinking. If you try this with the exact same state you posted in your issue and the `admin-tools` is missing from the "MATE Desktop" package, then state will just fail instead of stacktrace. 

I think we'll need a different fix for handling the skip options before we call the `group_diff` function, which was raising the `CommandExecutionError` and causing the stacktrace.

**Comment by cachedout** [comment]
Hi @rallytime. Where are we at on this one?

**Comment by rallytime** [comment]
@cachedout I think this is good to go as it stands so at least we can avoid the stacktraces. I will need to make a new PR to address the `group_diff` handling of skips. I'm not sure that ever worked as it was intended.

**Pull request merged**
