### PR TITLE
alter sql was only considering password and not password_hash

### PR DESCRIPTION
**Pull request by jeffdyke**
### What does this PR do?
 Fixes password updates in versions that support `ALTER USER....`
### What issues does this PR fix or reference?
A second run of the highstate is not idempotent b/c of the variable used.
### Previous Behavior
Remove this section if not relevant
```2019-08-23 20:56:14,318 [salt.state       :322 ][ERROR   ][16287] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1933, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1939, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/mysql_user.py", line 174, in present
    **connection_args):
  File "/usr/lib/python2.7/dist-packages/salt/modules/mysql.py", line 1475, in user_chpass
    " IDENTIFIED BY '" + password + "';")
TypeError: coercing to Unicode: need string or buffer, NoneType found
```
**this prevented idempotency from subsequent runs and i don't it may have double encoded (which i will try to prove in another PR) the hash b/c i saw that my local users password was the PASSWORD_HASH hashed.
### New Behavior
None of the above occurs
Remove this section if not relevant

### Tests written?
no - I'll write tests, but clearly test were not written for this use case, i'm not saying that to in adversity, just let me know where i can add this specific one, i would really appreciate that.
**[NOTICE] Bug fixes or features added to Salt require tests.**
Please review the [test documentation](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html) for details on how to implement tests into Salt's test suite.

Yes/No

### Commits signed with GPG?
No
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by jeffdyke** [comment]
I may not have covered all area's b/c the version available on 18.04 is not the same as master, so I only fixed my issue.  I'll be patching all salt installations until this is resolved.  I do hope this is helpful, please ask anything of me you'd like.

**Comment by garethgreenaway** [comment]
@jeffdyke Thanks for the PR!  I thought I had addressed all the various permutations with MySQL versions and password management, but it seems I might have missed one.  What variant of MySQL and what version did you run into this issue on?  Thanks!

**Comment by jeffdyke** [comment]
Hi @garethgreenaway - On new build outs such as this, I'm installing mariadb and its picking up 10.3.17.  From what i could see it was definitely in the correct `if` branch.  I was also quickly clused into this, b/c if a quick fix is needed in an environment, i use `alter user` every time. Like you say, it seems like this one just fell through the cracks and was not converted to `password_sql`.  Glad to be of help!

**Comment by jeffdyke** [comment]
Another note, mainly if someone stumbles upon this.  In the release version (Fluorine), this problem also exists in the localhost check, but in `develop` the two are not treated differently and `Host` is set as either a IP/mask or `localhost`.  My patch is attached for both issues, but should only be applied to `Fluorine`
```
if host == 'localhost':
   if salt.utils.versions.version_cmp(server_version, '8.0.11') >= 0:
       qry = ("ALTER USER '" + user + "'@'" + host + "'"
                 " IDENTIFIED BY '" + password + "';")
``` 


[mysql.diff.txt](https://github.com/saltstack/salt/files/3537385/mysql.diff.txt)
cc: @garethgreenaway

**Comment by jeffdyke** [comment]
Hello again.  I'm not sure that this should be merged as is.  b/c of the following:

```
MariaDB [mysql]> select User, Host, Password from user where User = 'jeff';
+------+----------+-------------------------------------------+
| User | Host     | Password                                  |
+------+----------+-------------------------------------------+
| jeff | 172.16.% | *D02D4C65F4A93325D91DC9E07D45521A8CD2960B |
+------+----------+-------------------------------------------+
1 row in set (0.000 sec)

MariaDB [mysql]> alter user jeff@'172.16.%' identified by  '*D02D4C65F4A93325D91DC9E07D45521A8CD2960B';
Query OK, 0 rows affected (0.000 sec)

MariaDB [mysql]> select User, Host, Password from user where User = 'jeff';
+------+----------+-------------------------------------------+
| User | Host     | Password                                  |
+------+----------+-------------------------------------------+
| jeff | 172.16.% | *42EF65913FAC3841BEFC25DBCBBB800364B91853 |
+------+----------+-------------------------------------------+
1 row in set (0.000 sec)

MariaDB [mysql]> alter user jeff@'172.16.%' identified with mysql_native_password as '*D02D4C65F4A93325D91DC9E07D45521A8CD2960B';
Query OK, 0 rows affected (0.000 sec)

MariaDB [mysql]> select User, Host, Password from user where User = 'jeff';
+------+----------+-------------------------------------------+
| User | Host     | Password                                  |
+------+----------+-------------------------------------------+
| jeff | 172.16.% | *D02D4C65F4A93325D91DC9E07D45521A8CD2960B |
+------+----------+-------------------------------------------+
```

So i have to dig into more of mariadb and see if this behaviour changed, or....something else.  If i use SET PASSWORD FOR 'jeff'@172.16.%' = 'hashed_string', that works.  See the following:

```
ariaDB [mysql]> alter user jeff@'172.16.%' identified by '*D02D4C65F4A93325D91DC9E07D45521A8CD2960B';
Query OK, 0 rows affected (0.000 sec)

MariaDB [mysql]> select User, Host, Password from user where User = 'jeff';
+------+----------+-------------------------------------------+
| User | Host     | Password                                  |
+------+----------+-------------------------------------------+
| jeff | 172.16.% | *42EF65913FAC3841BEFC25DBCBBB800364B91853 |
+------+----------+-------------------------------------------+
1 row in set (0.000 sec)

MariaDB [mysql]> alter user jeff@'172.16.%' identified with mysql_native_password as '*D02D4C65F4A93325D91DC9E07D45521A8CD2960B';
Query OK, 0 rows affected (0.000 sec)

MariaDB [mysql]> select User, Host, Password from user where User = 'jeff';
+------+----------+-------------------------------------------+
| User | Host     | Password                                  |
+------+----------+-------------------------------------------+
| jeff | 172.16.% | *D02D4C65F4A93325D91DC9E07D45521A8CD2960B |
+------+----------+-------------------------------------------+
1 row in set (0.000 sec)
```

**Comment by jeffdyke** [comment]
more noise: i hope i'm simply doing something wrong, but posted to mariadb list:

https://lists.launchpad.net/maria-discuss/msg05536.html

**Comment by SMillerDev** [comment]
I might have missed this part of the fix in https://github.com/saltstack/salt/pull/53861 or that one is now outdated

**Comment by jeffdyke** [comment]
Closing in favor of https://github.com/saltstack/salt/pull/54343/files, its a more complete solution.

**Pull request closed without merging**
