### PR TITLE
Boto apigateway optional stacktrace in response mapping

### PR DESCRIPTION
**Pull request by castor-morveer**
### What does this PR do?
Allows user to optionally specify response template mappings

### What issues does this PR fix or reference?
N/A

### Previous Behavior
Previous behavior always used predefined response template mappings
(which should still be good for vast majority of cases)

### New Behavior
If response template mappings are not provided, existing default mappings
will be used like in previous versions. If response template mappings are provided,
those will be used instead

### Tests written?
Manually tested against AWS Apigateway

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by winstonliu1111** [comment]
Is this change okay to be pulled?  the failures doesn't seem to be related to this change.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by winstonliu1111** [comment]
looks like there is a hang in the unit test for boto_apigateway ==> test_present_when_stage_exists_and_is_to_associate_to_existing_deployment (unit.states.boto_apigateway_test.BotoApiGatewayTestCase)

**Comment by winstonliu1111** [comment]
hi, it looks like latest fixes fixed the hung tests due to boto_apigateway.  the rest of the failures seems to be from boto_vpc as opposed to boto_apigateway, and don't seem to be related to the changes here.

**Comment by rallytime** [comment]
Yes, this looks ready to go now. Thank you!

**Pull request merged**
