### PR TITLE
Normalize file mode for Python 3 compatibility

### PR DESCRIPTION
**Pull request by amendlik**
### What does this PR do?
The modules.file.stats() and modules.win_file.stats() functions
return a dictionary containing an octal representation of a file mode.
Due to a change in the built-in oct() function, that mode string was
formatted differently under Python 3. This change calls
salt.utils.files.normalize_mode() to normalize the string before
assigning it to the dictionary.

### What issues does this PR fix or reference?
#52174

### Previous Behavior
`file.stats` would return a dictionary with a `mode` element like `0644`. Under Python 3 that `mode` element would be `0o644`, which caused some calling functions to misbehave, including `states.file.directory`

### New Behavior
The `mode` element is normalized to the all-numeric format (e.g. `0644`)

### Tests written?
Yes

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by twangboy — APPROVED** [review]

**Review by dwoz — DISMISSED** [review]
@amendlik Please look into the linter and doc errors, thanks. :)

**Comment by amendlik** [comment]
@dwoz Can you point me to the details of those errors? All I see from Jenkins is a Java error: java.lang.IllegalArgumentException: Failed to prepare cleanWs step

**Comment by amendlik** [comment]
@dwoz Please tell me me what needs to be done to get this PR merged.

**Review by Akm0d — APPROVED** [review]
It works for me

**Comment by Akm0d** [comment]
I mean that there are no longer  linter or doc errors.  Merged this, can we close the PR @amendlik ?

**Comment by amendlik** [comment]
@Akmod, I'm having trouble understanding your comments throughout this PR.

1) Your first comment says "Please look into the linter and doc errors". I responded that there were no linter or doc errors, but apparent errors in the job that checks for them. I never received a reply.

2) Next I see, "Tests were created as requested", but the tests were present from the start, so no such request was ever made, nor were tests added after the PR was created.

3) And your last comment: "I mean that there are no longer linter or doc errors." This is phrased as a clarification of some earlier comment, but I'm not sure what that might be. Again, there never were linter or doc errors, and the code was not changed.

I bring this up because it's discouraging to have to wait 6-7 weeks for a simple bugfix to be merged. In this case, the PR met all the acceptance criteria from the start. Rather than taking responsibility for the delays and errors, you have repeatedly commented that I needed to change something.

@thatch45, I would encourage to work with your team to make sure that interactions with the contributor community are more positive than this one.

**Comment by amendlik** [comment]
@Akm0d This needs to be merged forward into the 2019.2.1 branch, before it gets tagged for release.

**Comment by Akm0d** [comment]
@amendlik I'm sorry you have had a negative experience interacting with us  these past few weeks.  Your concerns are valid.  Personally, my  github notifications were disabled and I wasn't watching PRs I had interacted with.  That's fixed now and I hope we can have good interactions going forward.  To explain some of the comments: 
1. "It works for me" -- I ran into the underlying issue in my own normal use of salt and didn't see it after applying your changes.   I should have been that descriptive in the first place.
2. "Tests were created as requested" -- I had to leave a comment to dismiss a review that requested tests that already existed.  (Thank you for writing tests)
3. "I mean that there are no longer linter or doc errors" -- The linter and doc errors mentioned in the first comment didn't appear when I updated the branch.  That could have been more clear.
Thanks for your feedback!

**Pull request merged**
