### PR TITLE
only blockreplace exact match

### PR DESCRIPTION
**Pull request by jfindlay**

### CODE REVIEW

**Comment by cachedout** [comment]
This seems to contradict the existing documentation for the line marker. What's the rationale here?

**Comment by jfindlay** [comment]
@cachedout, a file with multiple managed blocks may overwrite each other if one block's markers contain another block's markers.  If a file contains this block,
```
# /tmp/file
# -- start blockreplace
first
# -- end blockreplace
```
and you apply a second blockreplace 
```python
__salt__['file.blockreplace']('/tmp/file',
                              '# -- start block',
                              '# -- end block',
                              'second',
                              append_if_not_found=True)
```
the result will be,
```
# /tmp/file
# -- start blockreplace
second
# -- end blockreplace
```
rather than
```
# /tmp/file
# -- start blockreplace
first
# -- end blockreplace
# -- start block
second
# -- end block
```

**Comment by jfindlay** [comment]
@cachedout, I do not know how this contradicts the documentation, or whether this is intended behavior, but it looks wrong to me.

**Comment by jfindlay** [comment]
@cachedout, perhaps a better solution would be to caution the user to not use markers that would be super/subsets of each other.

**Pull request closed without merging**
