### PR TITLE
Use `kickstart` on macos instead of stop + start

### PR DESCRIPTION
**Pull request by thisguycodes**
### What does this PR do?
Changes `service.restart` on MacOS to use `launchctl kickstart -k` instead of `launchctl stop` + `launchctl start`

This is more atomic as both actions are handled by the OS, rather than potentially having the salt-minion die mid-restart (such as restarting itself).

### What issues does this PR fix or reference?
#50422 

### Previous Behavior
Salt-minion couldn't restart itself, as stop + start would cause it to die before the start.

### New Behavior
Salt-minion can restart itself.

### Tests written?
No.

This is strictly a refactor of existing behavior, I believe existing tests cover this.

...I suppose a test specifically covering salt-minion restarting itself would be prudent. I'll look into this, help / directional advice appreciated!

### Commits signed with GPG?

No (I'll force push with signed commit(s) in a bit).

---
This change is [Reviewable](https://reviewable.io/reviews/saltstack/salt/56400)

### CODE REVIEW

**Comment by ThisGuyCodes** [comment]
I'm reading the contributor guidelines now and will make changes as necessary. I just figured this might be pretty easy to fix and jumped on it!

**Comment by ThisGuyCodes** [comment]
I'm actually not clear on what the process is here: do I need to gpg sign my commits?

**Comment by dwoz** [comment]
@ThisGuyCodes Signing you commits is recommended but not required. The fastest way to get this merged in will be to add a test case to cover the change.

**Comment by waynew** [comment]
@ThisGuyCodes thanks for the PR! Are you able to write some tests for this? An integration test might be the most meaningful, but I think you could also write some decently meaningful unit tests.

**Comment by waynew** [comment]
@ThisGuyCodes following up again - would you be able to add some tests here? If you're unsure about writing tests, I'm running a test clinic tomorrow AM American times on our [Twitch stream](https://www.twitch.tv/saltstackinc) where I'll be talking about and writing tests.

**Review by waynew — CHANGES_REQUESTED** [review]
If you need help writing tests, ping me in #salt on freenode or Slack, or attend one of our Test Clinics!

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
