### PR TITLE
[master] Add wildcard removal for aptpkg

### LINKED ISSUE #65220: [FEATURE REQUEST] add wildcard removal for aptpkg
**Is your feature request related to a problem? Please describe.**
inconsistent functionality. `pkg.remove` doesn't accept wildcards for apt, but it does for yum.

apt ref: https://github.com/saltstack/salt/blob/caa5e39303aa8cffc6ea5b191249c6ec7fe0282e/salt/modules/aptpkg.py#L1060
yum ref: https://github.com/saltstack/salt/blob/caa5e39303aa8cffc6ea5b191249c6ec7fe0282e/salt/modules/yumpkg.py#L2161-L2171

**Describe the solution you'd like**
support wildcards in apt. as a simple fix, the yum code snippet could be turned into a utility used in both places

**Describe alternatives you've considered**
sit in the corner and sob

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

### PR DESCRIPTION
**Pull request by nicholasmhughes**
### What does this PR do?
See issue for details

### What issues does this PR fix or reference?
Fixes: #65220 

### Previous Behavior
Wildcards could not be used for apt package removal

### New Behavior
Now they can

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by Ch3LL — CHANGES_REQUESTED** [review]
Can you also add some functional tests that test the aptpkg and yumpkg code using wildcards to ensure that is also functional?

**Comment by nicholasmhughes** [comment]
@Ch3LL , test failure looks unrelated. can you confirm?

**Comment by Ch3LL** [comment]
yes, we are having issues with the AMI's. This will fix it: https://github.com/saltstack/salt/pull/65338

**Comment by whytewolf** [comment]
so, just a thought on this. and this applies to yumpkg as well. we should maybe put in a warning if `*` the only thing passed to this and include a force option to allow it.

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
