### PR TITLE
Git state: head_ref should be head_rev in "latest" function

### PR DESCRIPTION
**Pull request by rallytime**
The "head_ref" variable is not used anywhere in the state file, and should be "head_rev" instead. Without setting "head_rev" to "None", there is a potential to hit an `UnboundLocalError` further down in the file.

This was caught by a test in the nitrogen branch, but the bug is present on 2016.11 as well. Here's the output from the integration test failure:
```
   -> integration.states.test_git.GitTest.test_latest_updated_remote_rev  .........................................
       Traceback (most recent call last):
         File "/testing/tests/integration/states/test_git.py", line 365, in test_latest_updated_remote_rev
           self.assertSaltTrueReturn(ret)
         File "/testing/tests/support/mixins.py", line 547, in assertSaltTrueReturn
           **(next(six.itervalues(ret)))
       AssertionError: False is not True. Salt Comment:
       An exception occurred in this state: Traceback (most recent call last):
         File "/testing/salt/state.py", line 1822, in call
           **cdata['kwargs'])
         File "/testing/salt/loader.py", line 1727, in wrapper
           return f(*args, **kwargs)
         File "/testing/salt/states/git.py", line 727, in latest
           if head_rev is not None:
       UnboundLocalError: local variable 'head_rev' referenced before assignment
```

### CODE REVIEW

**Review by terminalmage — APPROVED** [review]
Is the 2016.3 branch CVE-only now? If not, we should open this against 2016.3 instead as the bug exists there as well.

**Comment by rallytime** [comment]
@terminalmage I am honestly not sure what the state of that branch is for fixes. @cachedout should I move this to 2016.3?

**Comment by cachedout** [comment]
2016.3 will be active until we actually release Nitrogen so you can move it there, yes.

**Comment by rallytime** [comment]
Haha I messed this up. I have replaced it with https://github.com/saltstack/salt/pull/41083, which was submitted against 2016.3.

**Pull request closed without merging**
