### PR TITLE
changed prod_state to 1000

### PR DESCRIPTION
**Pull request by papoyan**

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @papoyan. Thanks for this. Could you please explain the reasoning behind this change?

**Comment by iamseth** [comment]
This fixes a bug introduced in 873227551e3819837326272ae60a2aea77082506. The documentation states that the default prod state is 1000 but that's incorrect today. It's current None so if you do an add_device with no params, you get an error. This sets the default properly to match the documentation.

**Comment by cachedout** [comment]
@iamseth Thanks for the explanation. Makes sense. I'll wait for the test suite to finish running and then get this merged.

**Comment by iamseth** [comment]
Cool, no rush @cachedout. We've got this fixed locally but wanted to push back upstream.

**Comment by cachedout** [comment]
@iamseth Sounds good. Much appreciated!

**Comment by papoyan** [comment]
my bad @cachedout. @iamseth thanks for providing the explanation.

**Comment by cachedout** [comment]
Merged. Thanks, all!

**Pull request merged**
