### PR TITLE
[master] add show diff for new file in file.managed

### LINKED ISSUE #65546: [FEATURE REQUEST] show diff for new file in file.managed
**Is your feature request related to a problem? Please describe.**
File diffs are often used to confirm proper operation of logic. It's a lot easier to eyeball `state.test` output showing diffs.

**Describe the solution you'd like**
Add a parameter to `file-managed` to force showing diffs for new files.

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

### PR DESCRIPTION
**Pull request by nicholasmhughes**
### What does this PR do?
See issue for details.

### What issues does this PR fix or reference?
Fixes: #65546

### Previous Behavior
State output only showed `newfile: <name>` or `diff: New file` in changes.

### New Behavior
Diff is now able to be optionally shown.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by nicholasmhughes** [comment]
@twangboy do you have any ideas why these Windows tests might be failing? Not sure if there's anythign interesting about how that OS handles temp files.

**Comment by nicholasmhughes** [comment]
> @twangboy do you have any ideas why these Windows tests might be failing? Not sure if there's anything interesting about how that OS handles temp files.

@twangboy , any thoughts on this? seems to work fine for all other operating systems

Also, can someone add an `Argon v3008.0` label to this? Thanks!

cc: @dwoz

**Review by twangboy — DISMISSED** [review]

**Comment by twangboy** [comment]
I think it's trying to open that file that doesn't exist yet it's throwing that error. I don't think it's actually a permissions issue. I think that's just a misleading error message. There are also some issues with line endings... this should get you close.

```
 def test_file_managed_new_file_diff(file, tmp_path):
+    tmp_path.mkdir(exist_ok=True, parents=True)
     name = tmp_path / "new_file_diff.txt"
+    ls = os.linesep
+    expected = {"diff": f"--- \n+++ \n@@ -0,0 +1 @@\n+EITR{ls}"}
     ret = file.managed(str(name), contents="EITR", new_file_diff=True, test=True)
-    assert ret.changes == {"diff": "--- \n+++ \n@@ -0,0 +1 @@\n+EITR\n"}
+    assert ret.changes == expected
     assert not name.exists()
     ret = file.managed(str(name), contents="EITR", new_file_diff=True)
-    assert ret.changes == {"diff": "--- \n+++ \n@@ -0,0 +1 @@\n+EITR\n"}
+    assert ret.changes == expected
     assert name.exists()
```

I'm still looking at it, but I'm getting pulled to other things

**Comment by twangboy** [comment]
OK, I got the tests working on Windows. I had to change the way you were opening the temp file. For some reason the `tempfile.NamedTemporaryFile` was keeping the lock on the file so Windows couldn't open it to write its contents. I saw above where they had used a salt util to create the temporary file, so I followed that paradigm. That seemed to take care of the permission denied error.

In the test on Windows it seems to return an additional dict entry in changes for "newfile". Maybe it doesn't do that on Linux. So, all the tests will now fail on Linux. I'll let you decide if you wanna hunt that down or modify the test for Linux.

**Comment by twangboy** [comment]
Also, this still needs a rebase and conflict resolution

**Comment by twangboy** [comment]
Looks like fixing the test for Windows breaks it for everything else. I don't know why you get a "new_file" on Windows but not the other OS's. It seems to me like that would be valid output if a new file is being created.

**Review by s0undt3ch — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Pull request merged**
