### PR TITLE
Remove yaml terminator in yaml formatter.

### PR DESCRIPTION
**Pull request by wt**

### CODE REVIEW

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by wt** [comment]
Classifying this as a minor change may not be fair. The semantics of the yaml filter are changed pretty dramatically by this change.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by Titerote** [comment]
I reproduced a similar problem on version 2015.8.0-608-g905acc6 

Instead of '\n...\n' it was '\n...' , while using the salt-formula .

**Pull request merged**
