### PR TITLE
[Fix] Correctly pass subset parameter to cmd_subset

### LINKED ISSUE #58600: [BUG] --subset parameter does not work, as param was renamed.
**Description**
A somewhat recent change renamed the cmd_subset parameter `sub`, to `subset`
Cool I guess but the callsite wasn't changed to match.

**Steps to Reproduce the behavior**
`salt '*' --subset=1 test.ping` 
(you'll get three results, the default size)

**Expected behavior**
Subset parameter works.

Also why not call the parameter 'count' or something? ehhh

**Screenshots**

**Versions Report**
Salt 3001.1

### PR DESCRIPTION
**Pull request by Timbus**
### What does this PR do?
Correctly names the parameter before passing to cmd_subset.

### What issues does this PR fix or reference?
Fixes: #58600 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by Timbus** [comment]
I highly, HIGHLY recommend adding a legacy param handler for `sub`, since this is being called by the jenkins plugin, and possibly other remote or custom clients?

**Review by waynew — CHANGES_REQUESTED** [review]
Hey @Timbus thanks for the PR! I think for the most part this is entirely reasonable... though if there is an existing test to cover this we should probably set it to check for *both* options.

I'm also curious if there's any history around the **why** -- looks like it was changed in https://github.com/saltstack/salt/pull/58634?

Finally, if we're restoring this name then we definitely want to add a changelog entry 👍

**Comment by Timbus** [comment]
Dunno if you linked to the wrong commit there, but I saw it change in #56203
https://github.com/saltstack/salt/commit/6606a37cebdf3cc33237078d157f96835768d837

It seems like a classic case of trying to improve/refactor some code and accidentally breaking a callsite -- nothing too crazy.
I didn't want to go fiddling with the internals of such an important piece of code, hence I didn't want to try adding tests or running any of the posthooks.

I'll add a changelog though, seems fair.

**Comment by Timbus** [comment]
Okay so, by closing this you're fine with passing 'sub' to the client, which explicitly takes 'subset' as a param? Could someone at least explain what was wrong with my changes to get them reverted.

**Comment by Timbus** [comment]
@garethgreenaway seriously?

**Comment by garethgreenaway** [comment]
@Timbus Apologies for the delay.  Looks like I missed the notifications.  I believe this one was a mobile UI issue where I hit merge instead of approve, and meant to go back and reopen/apply the changes.  I am happy to redo the PR since the mix up was on me.

**Pull request merged**
