### PR TITLE
Fix handling of disabled apt repositories in pkgrepo.managed

### PR DESCRIPTION
**Pull request by wwentland**
The main idea here is to fix the currently broken handling of disabled repositories and the removal of the ambiguous 'enabled' option from that state.

I would also appreciate it if this could be backported to 2014.7 or 2015.2. I have already tested it on those branch and the resulting behaviour constitutes a significant improvement over the status quo.

Please refer to the individual commit messages and referenced bugs for more information.

### CODE REVIEW

**Comment by jfindlay** [comment]
Related to #22147.

**Comment by babilen** [comment]
Related information and links to the bugs in question are found in the respective commit messages of feed537 and 4957db7. I simply saw no point in repeating that information here.

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by babilen** [comment]
As I haven't really heard any criticism I took the liberty of fixing the linting error and rebasing against develop. If there is anything else you'd like me to fix I'd rather know about these things.

Is this considered a rather intrusive change? It primarily removes a lot of broken code that should have never made it into the module.

**Comment by jfindlay** [comment]
@babilen, @thatch45 has done the same in #22626, but we'll prefer yours.  You are right about the change.  We should also have a note about this in `salt/doc/topics/releases/beryllium.rst`, and rather than removing `enabled`, we should rather deprecate it in boron or something.
```python
        if kwargs.get('enabled', None):
            kwargs['disabled'] = False
            salt.utils.warn_until(
                'Boron',
                'The `enabled` argument has been deprecated in favor of '
                '`disabled`.'
            )
```

**Comment by babilen** [comment]
@jfindlay Would you like me incorporate those changes in this PR?

**Comment by jfindlay** [comment]
@babilen, yeah, that would be great, thanks.

**Comment by babilen** [comment]
@jfindlay Is that more or less what you had in mind there?

**Comment by jfindlay** [comment]
@babilen, looks good.

**Pull request merged**
