### PR TITLE
[2015.2] Merge forward from 2014.7 to 2015.2

### PR DESCRIPTION
**Pull request by basepi**
[2015.2] Merge forward from 2014.7 to 2015.2

```
Conflicts:
    salt/modules/dockerio.py
    salt/modules/localemod.py
    salt/modules/useradd.py
```

### CODE REVIEW

**Comment by basepi** [comment]
Huh, those same tests failed both times. Seems like something in the state system may be amiss.....

**Comment by s0undt3ch** [comment]
```
"Rendering SLS 'base:exclude-test' failed: Jinja variable 'salt.loader.LazyLoader object' has no attribute 'runtests_helpers.get_sys_temp_dir_for_path'"]
```

Is the LazyLoader behaving correctly with external modules!?

**Comment by s0undt3ch** [comment]
Actually, it should or develop would also be failing...

**Comment by basepi** [comment]
It's a weird one. I'm not sure what's going on.

**Comment by basepi** [comment]
Please don't merge even if it goes green. Need to figure out what to do with the state changes that were made.

**Comment by basepi** [comment]
Alright, *now* if it goes green we can merge it.

**Pull request merged**
