### PR TITLE
Smart test the payload form on rcv

### PR DESCRIPTION
**Pull request by kiorky**
This is a Workaround/Fix for #21663

### CODE REVIEW

**Comment by kiorky** [comment]
cc @thatch45 @jacksontj @cachedout

**Comment by kiorky** [comment]
Im unsure on the log verbosity to use here, i just had an hard time to find the root of my issue...

**Comment by kiorky** [comment]
Damn this changeset has now another side effect, now that the payload is handled:
```
2015-03-15 01:13:27,218 [salt.minion      ][CRITICAL] An exception occurred while polling the minion
Traceback (most recent call last):
  File "/srv/mastersalt/makina-states/src/salt/salt/minion.py", line 1857, in tune_in
    self._do_socket_recv(socks)
  File "/srv/mastersalt/makina-states/src/salt/salt/minion.py", line 1952, in _do_socket_recv
    self._handle_payload(payload)
  File "/srv/mastersalt/makina-states/src/salt/salt/minion.py", line 984, in _handle_payload
    payload['sig'] if 'sig' in payload else None)
TypeError: _handle_clear() takes exactly 2 arguments (3 given)

```

**Comment by kiorky** [comment]
ok, pushed something to handle the case.

**Comment by thatch45** [comment]
Thanks @kiorky

**Pull request merged**
