### PR TITLE
Add EndeavourOS os_family

### PR DESCRIPTION
**Pull request by droogmic**
EndeavourOS is an Arch family OS.

### What does this PR do?

Add support for EndeavourOS is OS Family Map

### Previous Behavior

```
$ sudo salt 'os:EndeavourOS' grains.get os_family
foobar:
    EndeavourOS
```

### New Behavior

```
$ sudo salt 'os:EndeavourOS' grains.get os_family
foobar:
    Arch
```

### Merge requirements satisfied?

- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by MKLeb** [comment]
Hi @droogmic , this will need tests and a changelog.  Thanks for your contribution!

**Review by MKLeb — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Comment by bdrung** [comment]
The added test case is broken due to my recent changes in the grains code. Can you update the test case? If not, can you provide the content of `/etc/os-release`? Then I can fix the test case.

**Comment by bdrung** [comment]
Commit https://github.com/saltstack/salt/commit/dab8ea5b45323a8f0f814db60ea6d6fcc6daa406 changed the parameters for `_run_suse_os_grains_tests`.

**Comment by garethgreenaway** [comment]
This should fix things https://github.com/saltstack/salt/pull/62790

**Pull request merged**
