### PR TITLE
[3006.x] Run salt minion with salt group permissions

### LINKED ISSUE #64141: [BUG] salt user HOME is in /home
**Description**
The new 3006 salt-master installers create a `salt` user to run the service as. However, this user is given a HOME of `/home/salt`, as if it were a human user.

**Steps to Reproduce the behavior**
Install 3006 via onedir package on Linux system

**Expected behavior**
The `salt` user should be a system user with a HOME of ideally `/var/opt/saltstack`.

**Additional context**
https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#optAddonApplicationSoftwarePackages

### LINKED ISSUE #64158: [BUG] 3006 Inconsistency with minion and master permissions on /etc/salt
**Description**
The salt-master package creates a group called `salt` and expects all files in `/etc/salt` to be readable by that user/group. However, the salt-minion package does not install the `salt` user. Strangely, salt-master requires access to be able to read minion config files. This creates a permissions inconsistency between machines that have only the master installed or both the master and minion installed.

For example the following works fine on a machine with only the minion installed:
```yaml
include:
  - repo.salt # provides repo_salt

salt-minion:
  pkg.installed:
    - require:
      - repo_salt
  file.managed:
    - user: root
    - group: root
    - mode: '0440'
    - makedirs: True
    - template: jinja
    - names:
      - /etc/salt/minion.d/99-myconf.conf:
        - contents: |
            master:
              - salt.example.com
              - salt2.example.com
            master_type: failover
            master_alive_interval: 30
            retry_dns: 0
```
But on a machine with both the master and minion installed, I get the exception shown below.

If I set this file to be owned by the `salt` group then it fixes the issue on the master but this group does not exist on the minion:
```yaml
  file.managed:
    - user: root
    - group: salt # fails on minion that does not have salt-master installed as well
```

**Setup**
Debian 11 amd64 with salt-master and salt-minion 3006.0.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [x] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
See above

**Expected behavior**
The master should not require read access to minion files.

**Screenshots**
```
salt-master[261583]: [ERROR   ] An un-handled exception was caught by Salt's global exception handler:
salt-master[261583]: PermissionError: [Errno 13] Permission denied: '/etc/salt/minion.d/99-myconf.conf'
salt-master[261583]: Traceback (most recent call last):
salt-master[261583]:   File "/usr/bin/salt-master", line 11, in <module>
salt-master[261583]:     sys.exit(salt_master())
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/scripts.py", line 89, in salt_master
salt-master[261583]:     master.start()
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cli/daemons.py", line 204, in start
salt-master[261583]:     self.master.start()
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/master.py", line 723, in start
salt-master[261583]:     chan = salt.channel.server.PubServerChannel.factory(opts)
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/channel/server.py", line 721, in factory
salt-master[261583]:     return cls(opts, transport, presence_events=presence_events)
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/channel/server.py", line 727, in __init__
salt-master[261583]:     self.aes_funcs = salt.master.AESFuncs(self.opts)
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/master.py", line 1233, in __init__
salt-master[261583]:     self.mminion = salt.minion.MasterMinion(
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 974, in __init__
salt-master[261583]:     self.opts = salt.config.mminion_config(
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/config/__init__.py", line 2323, in mminion_config
salt-master[261583]:     opts = minion_config(path, ignore_config_errors=ignore_config_errors, role="master")
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/config/__init__.py", line 2299, in minion_config
salt-master[261583]:     include_config(
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/config/__init__.py", line 2178, in include_config
salt-master[261583]:     opts = _read_conf_file(fn_)
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/config/__init__.py", line 2015, in _read_conf_file
salt-master[261583]:     with salt.utils.files.fopen(path, "r") as conf_file:
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/files.py", line 393, in fopen
salt-master[261583]:     f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
salt-master[261583]: PermissionError: [Errno 13] Permission denied: '/etc/salt/minion.d/99-myconf.conf'
salt-master[261583]: Traceback (most recent call last):
salt-master[261583]:   File "/usr/bin/salt-master", line 11, in <module>
salt-master[261583]:     sys.exit(salt_master())
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/scripts.py", line 89, in salt_master
salt-master[261583]:     master.start()
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/cli/daemons.py", line 204, in start
salt-master[261583]:     self.master.start()
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/master.py", line 723, in start
salt-master[261583]:     chan = salt.channel.server.PubServerChannel.factory(opts)
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/channel/server.py", line 721, in factory
salt-master[261583]:     return cls(opts, transport, presence_events=presence_events)
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/channel/server.py", line 727, in __init__
salt-master[261583]:     self.aes_funcs = salt.master.AESFuncs(self.opts)
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/master.py", line 1233, in __init__
salt-master[261583]:     self.mminion = salt.minion.MasterMinion(
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/minion.py", line 974, in __init__
salt-master[261583]:     self.opts = salt.config.mminion_config(
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/config/__init__.py", line 2323, in mminion_config
salt-master[261583]:     opts = minion_config(path, ignore_config_errors=ignore_config_errors, role="master")
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/config/__init__.py", line 2299, in minion_config
salt-master[261583]:     include_config(
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/config/__init__.py", line 2178, in include_config
salt-master[261583]:     opts = _read_conf_file(fn_)
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/config/__init__.py", line 2015, in _read_conf_file
salt-master[261583]:     with salt.utils.files.fopen(path, "r") as conf_file:
salt-master[261583]:   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/files.py", line 393, in fopen
salt-master[261583]:     f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
salt-master[261583]: PermissionError: [Errno 13] Permission denied: '/etc/salt/minion.d/99-myconf.conf'
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.0
 
Python Version:
        Python: 3.10.11 (main, Apr 14 2023, 05:57:16) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: 1.10.6
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: 1.3.0
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 1.7.0
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.11.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-21-cloud-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by dwoz**
Move the salt user creation to the common package shared all other salt packages.

- [x] Move salt user creation to common package.
- [x] Do not add user or group when it already exists.
- [x] Create user in pre scripts 

### What issues does this PR fix or reference?
Fixes: #64141
Fixes: #64158

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by barneysowood** [comment]
@dwoz - thanks for the heads up, I hadn't spotted this before working on https://github.com/saltstack/salt/pull/64194.

* The improvements on not creating the user/group if they already exist look good
* I'm not sure the fix for #64141 is the right one - why does the user need a home directory? Setting homedir to `/nonexistent` on debian derived systems and `/` on RH derived systems is a valid thing to do for service users. Having the user's homedir set to something it can't write to will avoid unexpected behaviour that could happen if any state (dotfiles changing env etc) that could occur if it has a user writable homedir. Also makes it harder for a compromise to persist state.
* If you're going to create a shared group makes sense to do in the salt-common pkg, but I'd argue that the user the `salt-master` runs as should be created in the salt-master package. I'd also say it's a good opportunity to change that user from `salt` to `salt-master` - I think it's clearer that way as it is just the user that service runs as. 
* Is creating a shared group the way to solve #64158? not sure the MasterMinion should be using config from `/etc/salt/minion.d` - it's separate from the normal minion that may be running on the master (which may not even connect to the local master).

**Comment by dwoz** [comment]
> * I'm not sure the fix for [[BUG] salt user HOME is in /home #64141](https://github.com/saltstack/salt/issues/64141) is the right one - why does the user need a home directory? Setting homedir to `/nonexistent` on debian derived systems and `/` on RH derived systems is a valid thing to do for service users. Having the user's homedir set to something it can't write to will avoid unexpected behaviour that could happen if any state (dotfiles changing env etc) that could occur if it has a user writable homedir. Also makes it harder for a compromise to persist state.

Yes, I was on the fence about using `/opt/saltstack/salt` as the home directory. IIRC there has been some debate about using `/nonexistent` and weather it's actually a best practice or not anymore. I was also thinking of `/opt/saltstack/salt` as a way of future proofing in case we need to change salt-pip to install things as user packages. Using `--target` has some bugs associated with un-installing. As far as making it harder to compromise, `/opt/saltstack/salt` will still be writable by the salt user. This is needed to ensure pip works correctly. Unless I'm missing something, `/nonexistent` doens't provide hardening in this case.

> * If you're going to create a shared group makes sense to do in the salt-common pkg, but I'd argue that the user the `salt-master` runs as should be created in the salt-master package. I'd also say it's a good opportunity to change that user from `salt` to `salt-master` - I think it's clearer that way as it is just the user that service runs as.

Yes, I'm adding the group and user in salt-common since it's looking like we need to be aware of it in the other packages.

> * Is creating a shared group the way to solve [[BUG] 3006 Inconsistency with minion and master permissions on /etc/salt #64158](https://github.com/saltstack/salt/issues/64158)? not sure the MasterMinion should be using config from `/etc/salt/minion.d` - it's separate from the normal minion that may be running on the master (which may not even connect to the local master).

I agree not reading from the salt minion's config is ideally the best solution. Though I don't think we want to try and tackle that as an issue in a bugfix release. We don't want to risk breaking people's configurations that are currently in the wild without going through a deprecation period and have everything properly documented. So for now, running the minion with the salt group permissions seems to be a reasonable solution.

**Comment by dwoz** [comment]
@barneysowood After reading through #64193 I understand where you are coming from. I propose we merge this PR and you can re-base yours and change things the way you see fit. We can have a greater discussion about the individual items on your PR. Since the cut-off for 3006.1 is May 03. Your PR will likely fall into 3006.2.

**Comment by barneysowood** [comment]
> @barneysowood After reading through #64193 I understand where you are coming from. I propose we merge this PR and you can re-base yours and change things the way you see fit. We can have a greater discussion about the individual items on your PR. Since the cut-off for 3006.1 is May 03. Your PR will likely fall into 3006.2.

@dwoz - that makes sense - I'll mark #64193 as draft and rebase once this is merged.

> I agree not reading from the salt minion's config is ideally the best solution. Though I don't think we want to try and tackle that as an issue in a bugfix release. We don't want to risk breaking people's configurations that are currently in the wild without going through a deprecation period and have everything properly documented. So for now, running the minion with the salt group permissions seems to be a reasonable solution.

Sure - sorry, I'd not really accounted for the fact you were trying to get this done for the 3006.1 bugfix release. I'll open an issue for that - I'd be happy to take a look at implementing, but it may be something for 3007.

**Review by Ch3LL — DISMISSED** [review]

**Comment by Ch3LL** [comment]
Looks like a couple of test failures need to be resolved

**Review by dmurphy18 — DISMISSED** [review]

**Review by s0undt3ch — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Comment by tvb** [comment]
Chipping in on this PR. I see the following while running `3006.1` with the user `salt` configured in the config:

```
2023-05-26 07:41:20,755 [salt.loaded.int.returner.local_cache:119 ][WARNING ][63] Could not write out jid file for job 20230526074119248612. Retrying.
2023-05-26 07:41:20,956 [salt.loaded.int.returner.local_cache:119 ][WARNING ][63] Could not write out jid file for job 20230526074119248612. Retrying.
2023-05-26 07:41:21,157 [salt.loaded.int.returner.local_cache:119 ][WARNING ][63] Could not write out jid file for job 20230526074119248612. Retrying.
2023-05-26 07:41:21,358 [salt.loaded.int.returner.local_cache:119 ][WARNING ][63] Could not write out jid file for job 20230526074119248612. Retrying.
2023-05-26 07:41:21,559 [salt.loaded.int.returner.local_cache:119 ][WARNING ][63] Could not write out jid file for job 20230526074119248612. Retrying.
2023-05-26 07:41:21,659 [salt.loaded.int.returner.local_cache:93  ][ERROR   ][63] prep_jid could not store a jid after 5 tries.
2023-05-26 07:41:21,660 [salt.utils.job   :78  ][CRITICAL][63] The specified 'local_cache' returner threw a stack trace
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/returners/local_cache.py", line 113, in prep_jid
    with salt.utils.files.fopen(os.path.join(jid_dir, "jid"), "wb+") as fn_:
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/files.py", line 393, in fopen
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/salt/master/jobs/8a/9e83fb30bd4f8d7deafa1b04b97105a51f992c919ea149fb10bb0afcc6672a/jid'
```
```
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/job.py", line 72, in store_job
    mminion.returners[jidstore_fstr](False, passed_jid=load["jid"])
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1232, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1247, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/returners/local_cache.py", line 121, in prep_jid
    return prep_jid(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/returners/local_cache.py", line 121, in prep_jid
    return prep_jid(
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/returners/local_cache.py", line 121, in prep_jid
    return prep_jid(
  [Previous line repeated 2 more times]
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/returners/local_cache.py", line 94, in prep_jid
    raise salt.exceptions.SaltCacheError(err)
salt.exceptions.SaltCacheError: prep_jid could not store a jid after 5 tries.
```

```
2023-05-26 07:41:21,660 [salt.utils.job   :143 ][CRITICAL][63] The specified 'local_cache' returner threw a stack trace
Traceback (most recent call last):
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/utils/job.py", line 141, in store_job
    mminion.returners[fstr](load)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1232, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/loader/lazy.py", line 1247, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/returners/local_cache.py", line 144, in returner
    os.makedirs(hn_dir)
  File "/opt/saltstack/salt/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/saltstack/salt/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/cache/salt/master/jobs/8a/9e83fb30bd4f8d7deafa1b04b97105a51f992c919ea149fb10bb0afcc6672a'
```

Looking at the permissions of the directories, the are all set to `salt:salt`:
```
sh-4.2# ls -la /var/cache/salt/master/
total 72
drwxr-x--- 1 salt salt 4096 May 26 07:42 .
drwxr-xr-x 1 salt salt 4096 May 25 07:50 ..
-r-------- 1 salt salt    0 May 26 07:42 .dfn
-rw------- 1 root root   76 May 26 07:35 .root_key
-rw------- 1 salt root   76 May 26 07:35 .salt_key
drwxr-xr-x 1 root root 4096 May 25 07:51 extmods
drwxr-xr-x 3 salt salt 4096 May 26 07:37 file_lists
drwx------ 3 salt salt 4096 May 26 07:36 files
drwxr-xr-x 5 salt salt 4096 May 26 07:36 gitfs
drwxr-x--- 1 salt salt 4096 May 26 07:42 jobs
drwxr-xr-x 3 salt salt 4096 May 26 07:37 minions
drwxr-x--- 2 salt salt 4096 May  5 18:05 proc
drwxr-x--- 2 salt salt 4096 May  5 18:05 queues
drwxr-x--- 2 salt salt 4096 May  5 18:05 roots
drwxr-x--- 2 salt salt 4096 May  5 18:05 syndics
drwxr-x--- 2 salt salt 4096 May  5 18:05 tokens
```
```
sh-4.2# ls -la /var/cache/salt/master/jobs/
total 572
drwxr-x--- 1 salt salt 4096 May 26 07:45 .
drwxr-x--- 1 salt salt 4096 May 26 07:46 ..
drwxr-xr-x 4 salt salt 4096 May 26 07:41 00
drwxr-xr-x 3 salt salt 4096 May 26 07:43 01
drwxr-xr-x 4 salt salt 4096 May 26 07:42 02
drwxr-xr-x 3 salt salt 4096 May 26 07:41 05
drwxr-xr-x 3 salt salt 4096 May 26 07:42 07
drwxr-xr-x 3 salt salt 4096 May 26 07:40 0b
drwxr-xr-x 3 salt salt 4096 May 26 07:37 0c
drwxr-xr-x 6 salt salt 4096 May 26 07:42 0e
drwxr-xr-x 3 salt salt 4096 May 26 07:37 0f
drwxr-xr-x 4 salt salt 4096 May 26 07:45 14
```

Is this PR present in 3006.1 already?

**Pull request merged**
