### PR TITLE
Allow deepcopies of NamespacedDictWrapper in python 2.6

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by cachedout** [comment]
Do we have a bug associated with this?

**Comment by jtand** [comment]
@cachedout Should be this one: http://166.78.178.63:8080/job/branch_tests/job/develop/job/salt-linode-cent6/213/testReport/junit/integration.cli.custom_module/SSHCustomModuleTest/test_ssh_sls_with_custom_module/

**Comment by s0undt3ch** [comment]
I can make that method conditional of running in py26 since it works OK from 2.7 onward...

**Comment by basepi** [comment]
I think it's fine. As long as the new fix works on py2.7 I'm good.

**Pull request merged**
