### PR TITLE
Develop branch fix for #23950

### PR DESCRIPTION
**Pull request by neogenix**
Develop branch fix for #23950 - iptables state generates a 0 position which is invalid in iptables cli

### CODE REVIEW

**Comment by jfindlay** [comment]
@neogenix, thanks for the fix.  It is usually not necessary to submit pull requests to more than one branch as the release branches are regularly merged forward.

**Comment by neogenix** [comment]
@jfindlay awesome. I'll sort that in future :)

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by neogenix** [comment]
Really confused atm... Can't quite tell what's breaking in the Jenkins build?

**Comment by jfindlay** [comment]
Jenkins has had some issues today.

**Comment by neogenix** [comment]
Thanks @jfindlay, I just assumed jenkins hated me.

**Pull request merged**
