### PR TITLE
Multiple bugixes for new "nagios_json" module

### PR DESCRIPTION
**Pull request by isbm**
Update: After posting this PR, I realized that originally there was some cleanups to it (#21793) but it was too late :-)

This PR has a major changes anyways:
- renamed the entire module from "nagios_json" to "nagios_rpc". The JSON is just a protocol, while "RPC" is a method of communication. It sounded similar to "zfs_ssd" or "http_network", rather then "what_what_for".
- removed whole one method from it, so now both service and host can be verified just with one call: `nagios_rpc.status`, depends on parameters.
- Quite shorter code
- Dropped True/False return approach, as it truncates valuable information.
- Ability to return numeric or textual values in return
- No need to repeat "nagios" multiple times in the Salt configuration. Instead of:

```
nagios:nagios_url = http://....
nagios:nagios_username
```

now it is more neat:

```
nagios:url = http://....
nagios:username
```

### CODE REVIEW

**Comment by thatch45** [comment]
@isbm this approach is not acceptable, we don't just remove other's code like this. Also the fact that you have not asked the original author's feedback on the PR.

While I am grateful for your work I will need to ask that you consider the work of others when you submit code like this and maintain an open dialogue, this approach we feel causes community contention.

@garethgreeaway please review this PR as it does completely replace your contribution.

**Comment by isbm** [comment]
@thatch45 I think this is a misunderstanding. I opened this PR not because I wanted to avoid opinion of @garethgreeaway , but simply somebody else (forgot the nickname) asked me to send fixes. Of course, if you like previous version more, I am fine to close this PR.

**Comment by isbm** [comment]
@thatch45 Also, I **did** asked the feedback from the original author: https://github.com/saltstack/salt/pull/21793

**Comment by thatch45** [comment]
ok, sorry for over reacting :)
I think that we can get to a good consensus here, and I had not seen #21793 yet.
Thanks! And sorry for my knee jerk reaction.

**Comment by isbm** [comment]
@thatch45 No problem! :)

**Comment by garethgreenaway** [comment]
@thatch45 Overall good changes and still using a lot of code from the original submission, the module rename makes it look like it was completely replaced.  There are some functionality changes that I disagree with, eg. having one method to check both host & service status.

**Comment by isbm** [comment]
@thatch45 BTW, I did not completely replaced the code :) I just renamed the file, so it _looks like_ replaced.

@garethgreenaway Could you prove why you would need more than one method to check similar entities? Nagios has only checks for service and host. Specifying a service in the parameter will check for the service, omitting it — just host.

**Comment by garethgreenaway** [comment]
@isbm Not really making it more complicated, if anything, making it more clear.  This addition is early on in development, host checks vs service checks return different data, it's entirely possible there will need to be different functionality for each.  Paraphrasing the unix philosophy, many small methods doing specific things....

**Comment by isbm** [comment]
@garethgreenaway Please allow me to look at your own code. The method name is "service_status":
https://github.com/garethgreenaway/salt/blob/nagios_json_module/salt/modules/nagios_json.py#L125
Here we have "host_status":
https://github.com/garethgreenaway/salt/blob/nagios_json_module/salt/modules/nagios_json.py#L158

First, looking at this proposal, I see a code duplication "code smell", which is not acceptable at all. It would semi-agreeable if there would be a multi-purpose _third_ private method like `_status(...)` and then aliased to it with other two by a different parameters for convenience purposes. That is still questionable for its needs. Second, I see that the parameter is embedded right into the method name: _**host**_status_ and _**service**_status_, while we have the same logical entity, called "status".

Do you understand the problem?

**Comment by garethgreenaway** [comment]
@isbm There is a common method between the two, _status_query.  The "code smell" that you refer to is two calls to that common function in two different methods.  We're arguing semantics and different views on how it should be done, it's clear we're not going to agree.  So I'm bowing out of the argument.

**Comment by isbm** [comment]
@thatch45 What do we do here?

**Comment by thatch45** [comment]
Sorry, I have not had time to come up to speed on this one, I will look when I can

**Comment by isbm** [comment]
@jfindlay @cachedout @thatch45 Maybe you could look at this, please?

**Comment by thatch45** [comment]
I am going to merge this, but I am also going to agree with @garethgreenaway so I will request that we do separate out the functions, I would rather have a little code copy then have an overloaded single function that does too much, this has bitten us much more then the type of code copy that @garethgreenaway is suggesting.
So to sum up, I will merge and request that we do separate out those functions

**Pull request merged**
