### PR TITLE
Adds a function to list all users from shadow file

### PR DESCRIPTION
**Pull request by lorengordon**
### What does this PR do?

Adds an execution module function `shadow.list_users` that lists all users from the shadow file.

### Tests written?

Yes

### CODE REVIEW

**Comment by lorengordon** [comment]
Umm, hopefully it wasn't something I did here that caused the tests not to run...?

**Review by cachedout — CHANGES_REQUESTED** [review]
This is going to be handy but please move it onto the develop branch, which is where all new features go. Then we'll get it merged. Thanks, @lorengordon

**Comment by lorengordon** [comment]
Ok, bummer. This addresses a problem we have in 2016.11, where `user.list_users` even returns ldap-/pam-sourced users (apparently, that's expected behavior of `pwd`). Was figuring that with no possible backwards-compatible breakage here, it would be suitable for this branch. But alright, I'll move this to develop and we'll go with a custom module.

**Comment by cachedout** [comment]
@lorengordon I know it seems arbitrary but we have to draw the line somewhere. Thanks for being understanding. :]

**Review by cachedout — APPROVED** [review]

**Comment by lorengordon** [comment]
@cachedout Alright, moved the base to `develop`. Should be good.

**Pull request merged**
