### PR TITLE
Add umask as a global state argument

### PR DESCRIPTION
**Pull request by terminalmage**
This removes the umask argument from cmd states and makes it a global state argument.

### CODE REVIEW

**Comment by garethgreenaway** [comment]
@terminalmage Looks good.  My only comment is on the change in doc/ref/states/requisites.rst, why this is temporary?  Also we need a changelog file added and the pre-commit test is failing.

**Comment by terminalmage** [comment]
It's temporary because the umask is only changed for the lifetime of a single state.

Perhaps the wording can be improved?

**Comment by garethgreenaway** [comment]
@terminalmage Thanks.  That makes more sense.  My first impression was that it was being changed for just the 3002 release and would change to a different approach in the future.

**Comment by terminalmage** [comment]
@garethgreenaway Cool. Should this just be considered an "added" changelog entry even though `umask` argument has been removed from the "cmd" state module here? The functionality will remain the same.

**Comment by terminalmage** [comment]
Also, can the changelog files contain markdown? This is not clear from the docs.

**Comment by garethgreenaway** [comment]
@terminalmage I would make it an "changed" change since you're remove the `umask` argument from `cmd` in favor of it using the global one.  It looks like town crier does have support for using markdown.

**Comment by terminalmage** [comment]
OK, thanks. Changelog file added.

**Review by garethgreenaway — DISMISSED** [review]

**Comment by Ch3LL** [comment]
@terminalmage mind resolving the merge conflicts?

**Review by dwoz — APPROVED** [review]

**Review by MKLeb — APPROVED** [review]

**Comment by terminalmage** [comment]
Merge conflicts removed, tests re-done and passing

**Comment by max-arnold** [comment]
The 3002 version number in the docs need to be changed to 3006: https://docs.saltproject.io/en/master/ref/states/requisites.html#run-state-with-a-different-umask

**Pull request merged**
