### PR TITLE
Move Linode driver to use REST API instead of libcloud/python-linode

### PR DESCRIPTION
**Pull request by rallytime**

### CODE REVIEW

**Comment by techhat** [comment]
w00t!

**Comment by bechtoldt** [comment]
I'll test this in a few days. the current implementation (create/destroy VMs) is horribly slow when working with 100-200 VMs.

**Comment by bechtoldt** [comment]
the driver doesn't work with the http utility when urllib is in use. I'm going to provide a PR that is addressing this along with some other driver-specific changes.

**Comment by bechtoldt** [comment]
@rallytime see #25017, I'm looking forward for feedback :)

**Pull request merged**
