### PR TITLE
Allow the discovery of salt extensions installed while salt is running

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title.
Additionally, it prevents loading `utils` from extensions which would be packed into `__utils__`.

### Previous Behavior
The salt daemons had to be restarted to pick up the newly installed extensions

### New Behavior
The salt daemons no longer have to be restarted to pick up the newly installed extensions.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by UtahDave** [comment]
Nice!

**Comment by s0undt3ch** [comment]
@bryceml @krionbsd @ScriptAutomate need your signoff on this PR because `importlib-metadata>=3.3.0` as a base requirement, or detecting salt-extensions without restarting the daemons won't work.

**Comment by bryceml** [comment]
we can't require a newer version than what's on the OS: https://pkgs.org/search/?q=python3-importlib-metadata

epel for centos 8 has 0.23

so we can't require newer than 0.23.

what do we do for fedora?  just leave it on an old version of salt until it's on py3.10 with fedora 36.  Do we need to get python3-import-metadata added to fedora?

also, photon os doesn't have it in it's repos.

**Review by bryceml — APPROVED** [review]
The stuff relevant to me looks good.

**Review by cmcmarrow — APPROVED** [review]

**Review by dwoz — APPROVED** [review]

**Review by ScriptAutomate — APPROVED** [review]

**Pull request merged**
