### PR TITLE
fix grains.append in nested dictionnary grains #23411

### LINKED ISSUE #23411: grains.append should work at any level of a grain
I think we should be able to append values to a list at any level of a grain. Don't you?

An example:
Provided this grain:
```yaml
list:
  - val1
  - val2
```
The command `salt-call grains.append 'list' 'val3'` will update the grain to:
```yaml
list:
  - val1
  - val2
  - val3
```

With this grain, however:
```yaml
mygrain:
  var: somevalue
  list:
    - val1
    - val2
```
the command `salt-call grains.append 'mygrain:list' 'val3'` will give that output, which is correct, IMO:
```yaml
mygrain:list:
  - val1
  - val2
  - val3
```
but the grain `mygrain` is still:
```yaml
mygrain:
  var: somevalue
  list:
    - val1
    - val2
```

EDIT: Actually, there is a new grain `mygrain:list`, containing the complete list. This is weird:
```console
$ salt-call grains.get 'mygrain:list'
local:
    - val1
    - val2
$ salt-call grains.item 'mygrain:list'
local:
    - val1
    - val2
    - val3
```

### PR DESCRIPTION
**Pull request by dr4Ke**
I propose this change to fix #23411.
I added the `delimiter` parameter, with a `versionadded` tag to be updated.

Maybe I should add some test for future regression but I would need help.

### CODE REVIEW

**Comment by jfindlay** [comment]
@dr4Ke, thanks for working on this.  @cedwards has also submitted a pull request that seems to address (part of) this issue although in a different part of the code.

**Comment by dr4Ke** [comment]
Hi @jfindlay. Do you mean the #23437 pull request?

If so, I think it concerns two different issues. His change concerns querying a nested grain, while mine concerns appending to a list in a nested grain. They surely are related, though.

**Comment by dr4Ke** [comment]
This pull request is based on `v2014.7.5`. Should I do a new pull request based on `develop`?

**Comment by jfindlay** [comment]
@dr4Ke, thanks I just wanted you to be aware.  Actually this pull request is against develop, and since it is a bug fix I would prefer that it and #23437 go into 2014.7.

**Comment by dr4Ke** [comment]
OK. So I need to cancel this pull request and submit another against the branch 2014.7. Is that right?

**Comment by jfindlay** [comment]
@dr4Ke, yes that would be great, thanks.

**Comment by dr4Ke** [comment]
Cancel, replaced by #23474

**Pull request closed without merging**
