### PR TITLE
pkgrepo: fix enabling/disabling repositories on Debian

### LINKED ISSUE #27067: pkgrepo.managed does not uncomment repos in sources.list
If an entry doesn't exist at all, it is added fine:

```
$ cat /etc/apt/sources.list
# demo sources.list file
$ sudo salt-call state.high "{'partner': {'pkgrepo': ['managed', {'name': 'deb http://archive.canonical.com/ubuntu/ trusty partner'}, {'enabled': True}, {'file': '/etc/apt/sources.list'}]}}"
[INFO    ] Loading fresh modules for state activity
[INFO    ] Running state [deb http://archive.canonical.com/ubuntu/ trusty partner] at time 15:03:14.008331
[INFO    ] Executing state pkgrepo.managed for deb http://archive.canonical.com/ubuntu/ trusty partner
[INFO    ] Executing command 'apt-get -q update' in directory '/home/carmstrong'
[INFO    ] {'repo': 'deb http://archive.canonical.com/ubuntu trusty partner'}
[INFO    ] Completed state [deb http://archive.canonical.com/ubuntu/ trusty partner] at time 15:03:16.996167
local:
    ----------
    pkgrepo_|-partner_|-deb http://archive.canonical.com/ubuntu/ trusty partner_|-managed:
        ----------
        __run_num__:
            0
        changes:
            ----------
            repo:
                deb http://archive.canonical.com/ubuntu trusty partner
        comment:
            Configured package repo 'deb http://archive.canonical.com/ubuntu/ trusty partner'
        duration:
            2987.836
        name:
            deb http://archive.canonical.com/ubuntu/ trusty partner
        result:
            True
        start_time:
            15:03:14.008331
$ cat /etc/apt/sources.list
# demo sources.list file
deb http://archive.canonical.com/ubuntu trusty partner

```

But if an entry already exists and is commented out, the state does nothing:

```
$ cat /etc/apt/sources.list
# demo sources.list file
# deb http://archive.canonical.com/ubuntu trusty partner
$ sudo salt-call state.high "{'partner': {'pkgrepo': ['managed', {'name': 'deb http://archive.canonical.com/ubuntu/ trusty partner'}, {'enabled': True}, {'file': '/etc/apt/sources.list'}]}}"
[INFO    ] Loading fresh modules for state activity
[INFO    ] Running state [deb http://archive.canonical.com/ubuntu/ trusty partner] at time 15:04:39.959589
[INFO    ] Executing state pkgrepo.managed for deb http://archive.canonical.com/ubuntu/ trusty partner
[INFO    ] Executing command 'apt-get -q update' in directory '/home/carmstrong'
[INFO    ] Configured package repo 'deb http://archive.canonical.com/ubuntu/ trusty partner'
[INFO    ] Completed state [deb http://archive.canonical.com/ubuntu/ trusty partner] at time 15:04:40.020455
local:
    ----------
    pkgrepo_|-partner_|-deb http://archive.canonical.com/ubuntu/ trusty partner_|-managed:
        ----------
        __run_num__:
            0
        changes:
            ----------
        comment:
            Configured package repo 'deb http://archive.canonical.com/ubuntu/ trusty partner'
        duration:
            60.866
        name:
            deb http://archive.canonical.com/ubuntu/ trusty partner
        result:
            True
        start_time:
            15:04:39.959589
$ cat /etc/apt/sources.list
# demo sources.list file
# deb http://archive.canonical.com/ubuntu trusty partner
```

### PR DESCRIPTION
**Pull request by marmarek**
### What does this PR do?

Fix enabling/disabling repositories on Debian.
On plain Debian, enabled/disabled argument was ignored.

### What issues does this PR fix or reference?

Fixes #27067

### Previous Behavior
Adding/enabling Debian repository with `pkgrepo.managed` state did nothing if the repository was already present but commented out.

### New Behavior
Repository correctly enabled.

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by dwoz** [comment]
@marmarek Since this is a bug, can you add a regression test?

**Comment by marmarek** [comment]
Added.

**Comment by marmarek** [comment]
When forward merging, `salt.utils.is_true` needs to be changed to `salt.utils.data.is_true`.

**Review by Akm0d — APPROVED** [review]

**Comment by dwoz** [comment]
@marmarek We are no longer accepting PRs against `2017.7`, please re-open this against `master` if it's still an issue. You can reference this PR in the new one so we can retain the history.

**Comment by marmarek** [comment]
> @marmarek We are no longer accepting PRs against `2017.7`, please re-open this against `master` if it's still an issue. You can reference this PR in the new one so we can retain the history.

Have anything changed regarding a policy for _bugfix_ pull requests? Last time they should be made against oldest supported branch, not `master`.
Anyway, sure, I can rebase it on a newer branch, but I'd like to know what I need to do, to have it merged - this one was already waiting half a year with an approving review and without any comment what's wrong.

**Pull request closed without merging**
