### PR TITLE
Always close socket even if there is no stream.

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
Fix for #21744

### CODE REVIEW

**Comment by cachedout** [comment]
@DmitryKuzmenko Much better! Good work!

**Comment by DmitryKuzmenko** [comment]
We need this in develop too.

**Comment by cachedout** [comment]
@DmitryKuzmenko We'll get it merged forward today. Is it blocking your work right now?

**Comment by DmitryKuzmenko** [comment]
@cachedout nope, just commented to not forget =)

**Comment by cachedout** [comment]
@DmitryKuzmenko Sounds good. We'll get it in. Thanks for the reminder.

**Comment by vakulich** [comment]
Hello! Is it possible to merge this fix into 2015.5 somehow?

**Comment by cachedout** [comment]
@vakulich Unfortunetely, no. The code in question doesn't exist there.

**Comment by vakulich** [comment]
I see.. But this issue could be easily reproduced on 2015.5, so the code which have this bug is there. Isn't it possible to locate it?

**Comment by cachedout** [comment]
@DmitryKuzmenko What do you think? Is it possible there's another socket that's remaining open on 2015.5?

**Comment by DmitryKuzmenko** [comment]
I'll look.

**Comment by DmitryKuzmenko** [comment]
@cachedout , @vakulich 
There is really different logic in 2015.5. It's a really big change to fix this behavior. It's because we had no async execution in 2015.5 and minion runs 2 instances sequentially.

**Comment by vakulich** [comment]
@DmitryKuzmenko Ok, we'll better workaround it on our side by removing offline masters from minion config. Thanks anyway!

**Comment by DmitryKuzmenko** [comment]
@vakulich you're welcome! Try our new 2015.8.1! ;-)

**Pull request merged**
