### PR TITLE
add data to compound matching in top

### PR DESCRIPTION
**Pull request by gtmanfred**
### What does this PR do?
Add data to compound matching for top

### Tests written?

No

### CODE REVIEW

**Review by cachedout — COMMENTED** [review]
Is this documented anywhere?

**Comment by thatch45** [comment]
The data targeting never really panned out, it should work just fine, we just ended up pushing people towards grains instead, but I might make sense to document it better.

**Comment by cachedout** [comment]
I am uncomfortable with putting this out there a little more until some automated tests are written.

**Comment by thatch45** [comment]
Agreed

**Comment by cachedout** [comment]
@gtmanfred I vote we either add tests to this or close it without merging it.

**Comment by gtmanfred** [comment]
Sounds good, I am going to close it because I do not have the bandwidth to add tests it right now.

**Pull request closed without merging**
