### PR TITLE
kubernetes: provide client certificate authentication

### PR DESCRIPTION
**Pull request by mcalmer**
### What does this PR do?

Add the possibility to authenticate using a client certificate.

You can either deploy the certificates on the minion and specify the file path via pillar or config
or you provide the data directly copied from the kubeconfig file.

### Previous Behavior

Only username/password authentication was possible.

### New Behavior

You can provide a client certificate/key to authenticate

### Tests written?

No

### CODE REVIEW

**Comment by flavio** [comment]
LGTM

**Comment by mcalmer** [comment]
squashed all commits together and fixed a lint error

**Comment by cachedout** [comment]
@mcalmer Could you please submit this to the develop branch instead? 2017.7 has been closed for feature work.

**Comment by mcalmer** [comment]
https://github.com/saltstack/salt/pull/42174

**Comment by cachedout** [comment]
@mcalmer Thanks for the quick response! Much appreciated.

**Pull request closed without merging**
