### PR TITLE
Libcloud DNS execution module

### PR DESCRIPTION
**Pull request by tonybaloney**
### What issues does this PR fix or reference?

This execution module is a wrapper for libcloud's DNS abstraction library. http://libcloud.readthedocs.org/en/latest/dns/index.html

Libcloud currently supports 23 DNS providers across the globe, this module allows you to configure various providers and collect information on zones, records and create new zones or records. 
### Tests written?

No

CC @techhat

### CODE REVIEW

**Comment by techhat** [comment]
@tonybaloney, you are my hero. +1 when tests pass.

**Comment by tonybaloney** [comment]
Refer to #32687 which I accidentally still had in my WC. That needs to be merged first if there is consensus

**Comment by tonybaloney** [comment]
I will rebase once #32687 is merged. the linting errors for this changeset are all fixed.

**Comment by cachedout** [comment]
@tonybaloney Could you fix up the line endings here? Then I'll get this in. Thanks! 

http://166.78.178.63:8080/job/PR/job/salt-pr-lint-n/1193/violations/file/salt/modules/win_psget.py/

**Comment by tonybaloney** [comment]
@cachedout done

**Pull request merged**
