### PR TITLE
Update autodoc topics for new modules added in develop

### PR DESCRIPTION
**Pull request by rallytime**
Also adjusted versionadded tags as necessary on the files that are getting new autodoc files added.

### CODE REVIEW

**Comment by rallytime** [comment]
The `junos_syslog` engine is causing these build failures. I need to look more closely to figure out how to resolve some mocking issues.

**Comment by mirceaulinic** [comment]
Perhaps because of https://github.com/saltstack/salt/blob/develop/salt/engines/junos_syslog.py#L178 which has `EOL = LineEnd().suppress()` in the `__init__` (`EOL` being imported from a third party lib)?

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Of course after poking at various doc builds today, I now can longer reproduce this error locally. Hrm.

@mirceaulinic Yes, it has something to do with that. Originally I was looking at adding `pyparsing` to the list of mocked of [MOCK_MODULES](https://github.com/saltstack/salt/blob/b01d99eaa8a3b337f4d6212a6e23b8b89421b91d/doc/conf.py#L168) in `doc/conf.py` yesterday, but I never resolved that part. When I started poking around today, that particular error went away, so I thought perhaps something else cleared it up. Very strange. I need to try and reproduce this again tomorrow.

**Comment by cachedout** [comment]
@rallytime Could you let me know where we are on this one? Let me know if you need another pair of eyes on this.

**Comment by rallytime** [comment]
I have been stuck on this for a bit. The doc mock is being strange. I have asked @whiteinge for some advice.

**Comment by rallytime** [comment]
@cachedout This should be good to review now.

**Pull request merged**
