### PR TITLE
- modify _get_pid by pidfile

### PR DESCRIPTION
**Pull request by rongzeng54**
### What does this PR do?
Fix the problem of init.d script cant support control service when someone modify the id of salt-minion.
A multi instance deployment demo with realistic value is more likely to be isolated from the configuration directory (by $CONFIG_DIR), and use different PIDFILE configuration.
When someone modify the configuration file in same path, its more likely to be same instance modifications.
The most important is single instance is more popular.

### What issues does this PR fix or reference?
No issue. But you can reproduce the problem by the following steps.
After the salt-minion started, modify the id param of salt-minion, then you cant by init.d script control the old salt-minion which used the old minion id .
After run init.d script, the system will enter an unexpected state: you will get two main process of salt-minion, one used old minion id, another used new minion id.
If You continue to modify different minion id, You will easy get more.

### Previous Behavior
_get_pid() {
    netstat $NS_NOTRIM -ap --protocol=unix 2>$ERROR_TO_DEVNULL \
        | sed -r -e "\|\s${SOCK_DIR}/minion_event_${MINION_ID_HASH}_pub\.ipc$|"'!d; s|/.*||; s/.*\s//;' \
        | uniq
}

### New Behavior
_get_pid() {
    cat $PID_FILE 2>/dev/null
}

### Tests written?
No

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by cachedout** [comment]
I'm very hesitant about this. This doesn't fix a condition that should really ever be supported in my opinion and it entirely removes functionality that has been there for a while. I'll also ask @dmurphy18 to weigh in here.

**Comment by dmurphy18** [comment]
Understanding that English may not be a first language here, the explanation for making this change in the init.d script is not clear, esp. when it is stated that there is 'no issue' being addressed, then why make a change ?

I prefer to retrieve the pid from actual instantiations (netstat) rather than what you think it should be, and I am reluctant in making changes to init.d given that after April 2018, only Redhat 6 will be reliant on init.d, of the major distributions, given the movement to systemd.

I would prefer to let sleeping dogs lye and reject this change unless a more convincing reason is provided for the change.

**Comment by cachedout** [comment]
I agree with @dmurphy18 here. Changing the identifier of a running minion and then expecting to be able to control it with the init system just doesn't strike me as a good trade-off for what we're losing here.

**Comment by rongzeng54** [comment]
ok. if we do this change,  we can improve the robustness of scripts in el6, but what will we lose?

**Comment by cachedout** [comment]
@dmurphy18 Can you please follow-up with the above question?

**Comment by dmurphy18** [comment]
@rongzeng54 I will try to get to this, but attending SaltConf and I may not be able to address it fully until next week when SaltConf is finished.

**Comment by dmurphy18** [comment]
@rongzeng54 Use of the PID file is not reliable since it currently can be easily made to not exist,

For example: the following changes the minion id from c6m to c6ma
[root@dgm-test-rh6 init.d]# ./salt-minion restart
Stopping salt-minion:root:c6m daemon: OK
Starting salt-minion:root:c6m daemon: OK
[root@dgm-test-rh6 init.d]# cat /var/run/salt-minion.pid 
23531[root@dgm-test-rh6 init.d]# 
[root@dgm-test-rh6 init.d]# 
[root@dgm-test-rh6 init.d]# ps -ef | grep -v grep | grep salt
root     23531     1  2 10:43 ?        00:00:00 /usr/bin/python2.7 /usr/bin/salt-minion -c /etc/salt -d
root     23532 23531  0 10:43 ?        00:00:00 /usr/bin/python2.7 /usr/bin/salt-minion -c /etc/salt -d
[root@dgm-test-rh6 init.d]# vim /etc/salt/minion
[root@dgm-test-rh6 init.d]# ./salt-minion restart
Service salt-minion:root:c6ma is not running
Starting salt-minion:root:c6ma daemon: FAIL
[root@dgm-test-rh6 init.d]# cat /var/run/salt-minion.pid 
cat: /var/run/salt-minion.pid: No such file or directory
[root@dgm-test-rh6 init.d]# ps -ef | grep -v grep | grep salt
root     23531     1  0 10:43 ?        00:00:00 /usr/bin/python2.7 /usr/bin/salt-minion -c /etc/salt -d
root     23532 23531  0 10:43 ?        00:00:00 /usr/bin/python2.7 /usr/bin/salt-minion -c /etc/salt -d
[root@dgm-test-rh6 init.d]# [root@dgm-test-rh6 init.d]# ./salt-minion restart
Stopping salt-minion:root:c6m daemon: OK
Starting salt-minion:root:c6m daemon: OK
[root@dgm-test-rh6 init.d]# cat /var/run/salt-minion.pid 
23531[root@dgm-test-rh6 init.d]# 
[root@dgm-test-rh6 init.d]# 
[root@dgm-test-rh6 init.d]# ps -ef | grep -v grep | grep salt
root     23531     1  2 10:43 ?        00:00:00 /usr/bin/python2.7 /usr/bin/salt-minion -c /etc/salt -d
root     23532 23531  0 10:43 ?        00:00:00 /usr/bin/python2.7 /usr/bin/salt-minion -c /etc/salt -d
[root@dgm-test-rh6 init.d]# vim /etc/salt/minion
[root@dgm-test-rh6 init.d]# ./salt-minion restart
Service salt-minion:root:c6ma is not running
Starting salt-minion:root:c6ma daemon: FAIL
[root@dgm-test-rh6 init.d]# cat /var/run/salt-minion.pid 
cat: /var/run/salt-minion.pid: No such file or directory
[root@dgm-test-rh6 init.d]# ps -ef | grep -v grep | grep salt
root     23531     1  0 10:43 ?        00:00:00 /usr/bin/python2.7 /usr/bin/salt-minion -c /etc/salt -d
root     23532 23531  0 10:43 ?        00:00:00 /usr/bin/python2.7 /usr/bin/salt-minion -c /etc/salt -d
[root@dgm-test-rh6 init.d]# 


It can be seen that the PID file becomes non-existent. and status shows the daemon as FAIL even though the minion is running, troubling but I shall examine that issue after SaltConf.  

Hence the PR to rely on the contents of the PID file which is non-existent is not a correct fix for the issue.

**Comment by rongzeng54** [comment]
@dmurphy18  I've fixed the it in the second commit.

For example: the following changes the minion id from c6m to c6ma
[root@docker ~]# service salt-minion restart
Stopping salt-minion:root:c6m daemon: OK
Starting salt-minion:root:c6m daemon: OK

[root@docker ~]# cat /var/run/salt-minion.pid
2240164

[root@docker ~]# ps -ef | grep -v grep | grep salt
root     2240164       1  0 02:09 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     2240165 2240164  0 02:09 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d

[root@docker ~]# sed -i 's#c6m#c6am#' /etc/salt/minion

[root@docker ~]# service salt-minion restart
Stopping salt-minion:root:c6am daemon: OK
Starting salt-minion:root:c6am daemon: OK

[root@docker ~]# cat /var/run/salt-minion.pid
2269468

[root@docker ~]# ps -ef | grep -v grep | grep salt
root     2269468       1  1 02:11 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     2269469 2269468  0 02:11 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d

[root@docker ~]# service salt-minion restart
Stopping salt-minion:root:c6am daemon: OK
Starting salt-minion:root:c6am daemon: OK

[root@docker ~]# cat /var/run/salt-minion.pid
2282606

[root@docker ~]# ps -ef | grep -v grep | grep salt
root     2282606       1  1 02:12 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d
root     2282607 2282606  0 02:12 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-minion -c /etc/salt -d

Of course if you already have plans to fix the issue, I can undo the PR.

**Comment by rallytime** [comment]
@dmurphy18 Can you swing by this PR one more time?

**Review by dmurphy18 — APPROVED** [review]
The updated files appear to fix the issue high-lighted  when I tested the original changes with renaming the minion and restarting with daemon FAIL.  PR should update to ensure to pickup any changes since.

**Comment by dmurphy18** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
re-run py2

**Comment by rallytime** [comment]
@rongzeng54 I haven't been able to trigger any test updates or update the branch to the latest `develop`. In my efforts to get the tests running, I closed the PR with the intention of opening it again. However, it appears I am unable to reopen this.

Can you resubmit this change in a new pull request so we can see the test result? Please be sure to link the new PR back to this one so we have a record of the change.

**Pull request closed without merging**
