### PR TITLE
[2018.3.4] Updating the mysql module to handle MariDB versions.

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Updating the mysql module to handle MariDB versions.

### What issues does this PR fix or reference?
#48204 

### Tests written?
Yes

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by Ch3LL — APPROVED** [review]

**Comment by Oloremo** [comment]
I have concerns about the line:
https://github.com/saltstack/salt/pull/51530/files#diff-29a8d4513061a20d02e36c542ea18e19R1870

It's checks version too and I'm not sure if it's right for MariaDB

**Comment by garethgreenaway** [comment]
@Oloremo I think you may be right here, it appears that "ALL PRIVILEGES" still works in later versions of MariaDB.

**Comment by garethgreenaway** [comment]
@Oloremo Updated the PR with a workaround for MariaDB in grant_exists.

**Comment by Oloremo** [comment]
Looks good to me.

**Pull request merged**
