### PR TITLE
Openscap update

### PR DESCRIPTION
**Pull request by truzzon**
### What does this PR do?

This code overhauls the openscap module and its unittest.

### Previous Behavior
The old version only supported a limited set of commands. 

### New Behavior
This update brings the capability to support all commands, that OpenSCAPs xccdf module has to offer. It returns errors if a command or operation is not supported and offers a base to implement other modules like oval, cvss, etc.

The way commands are accepted by the module has changed. I tried to keep xccdf returns the same for compatibility. 
The way you give parmeters to the module has drastically changed and is incompatible to older iterations. People, who are using the current version of the module will have to change their commands in order for it to keep working.

### Merge requirements satisfied?
- [x] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
No

### Related PR
 PR #59756 
 PR #60211

### CODE REVIEW

**Comment by truzzon** [comment]
Hello @twangboy, the PR is ready for review.

If you have questions regarding 'xccdf_eval' please contact @meaksh.

Kind regards

**Review by waynew — CHANGES_REQUESTED** [review]
Thanks for the PR! I didn't do a full code review, but there was something that I noticed here...

**Comment by waynew** [comment]
Hey, no rush, but @truzzon are you interested in finishing this?

**Comment by truzzon** [comment]
> Hey, no rush, but @truzzon are you interested in finishing this?

Hello @waynew, I am interested in finishing this. The problem is, that you discovered during one of your test clinics, that my tests aren't working properly and you proposed so many changes that I have to rewrite half of it. When I wanted to rewatch the stream, it was already deleted. This was only two or three weeks later.

Because I currently lack time to work on this right now and don't know, when I will be able to finish it, I'd close it for now, and reopen it when I am able to finish it up.

Could you have another short look at the code and give me a hint or some advice on e.g. which mechanism I should use for the parameters? I was against using argparse, because it is to static for the degree of flexibility I want to achieve. But maybe this is just my perfectionism.

Could you provide a few short notes what I should focus on, when picking up the work again?

**Comment by waynew** [comment]
@truzzon I'll put this on my list for next week, hopefully I can make some comments on it on Tuesday!

**Comment by waynew** [comment]
@truzzon were you able to make any updates to this?

**Comment by truzzon** [comment]
> @truzzon I'll put this on my list for next week, hopefully I can make some comments on it on Tuesday, thanks!

Since you haven't had the chance to post any notes and I lack the time to work on it I'll close the PR. 

Maybe I can work on it in the future.

**Pull request closed without merging**
