### PR TITLE
[master] Avoid traceback on "http.query" when there are errors with the requested URL

### PR DESCRIPTION
**Pull request by meaksh**
This PR ports #54048 to master branch, and fixes an issue at 2019.2.x release.

---
### What does this PR do?
This PR prevents traceback on `http.query` and improves error logging in cases where there are errors with the requested URL:

- Connection refused
- No route to host
- Errors with DNS servers

### Previous Behavior
In cases where the requested URL refuses the connection:

```
# salt-call --local http.query http://127.0.0.1/
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
Traceback (most recent call last):
  File "salt-call", line 27, in <module>
    salt_call()
  File "pyall/salt/scripts.py", line 431, in salt_call
    client.run()
  File "pyall/salt/cli/call.py", line 57, in run
    caller.run()
  File "pyall/salt/cli/caller.py", line 138, in run
    ret = self.call()
  File "pyall/salt/cli/caller.py", line 237, in call
    ret['return'] = self.minion.executors[fname](self.opts, data, func, args, kwargs)
  File "/var/tmp/.root_fc9778_salt/pyall/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/var/tmp/.root_fc9778_salt/pyall/salt/modules/http.py", line 41, in query
    return salt.utils.http.query(url=url, opts=opts, **kwargs)
  File "pyall/salt/utils/http.py", line 566, in query
    result = download_client.fetch(url_full, **req_kwargs)
  File "py2/tornado/httpclient.py", line 102, in fetch
    self._async_client.fetch, request, **kwargs))
  File "py2/tornado/ioloop.py", line 457, in run_sync
    return future_cell[0].result()
  File "py2/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
error: [Errno 111] Connection refused
```

### New Behavior
```
# salt-call --local http.query http://127.0.0.1/
[ERROR   ] Cannot perform 'http.query': http://127.0.0.1/ - [Errno 111] Connection refused
local:
    ----------
    error:
        [Errno 111] Connection refused
```

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by brejoc** [comment]
Is there anything missing for this to get merged?

**Comment by DmitryKuzmenko** [comment]
@meaksh could you please add something simple that proofs we don't break this fix in the future and covers just your change. Something like this placed to `tests/unit/utils/test_http.py` would be much better than nothing:
```python
    def test_query_error_handling(self):
        ret = http.query(
                'http://127.0.0.1:0'
                )
        self.assertEqual(ret, {'error': '[Errno 111] Connection refused'})
```

**Comment by meaksh** [comment]
@DmitryKuzmenko done! Thanks for the review and the test suggestion!

**Review by DmitryKuzmenko — DISMISSED** [review]

**Comment by DmitryKuzmenko** [comment]
@meaksh could you please resolve merge conflicts?

**Review by dwoz — APPROVED** [review]

**Pull request merged**
