### PR TITLE
Fix import of pip modules

### PR DESCRIPTION
**Pull request by Orlando-Richards**
### What does this PR do?

When using pip versions between 10.0 and 18.0, the import of the pip.exceptions modules in pip_state will fail, as it was moved to pip._internal.exceptions in pip version 10.0.

Ref pip 10.0.0b1 release notes:
https://pip.pypa.io/en/stable/news/#b1-2018-03-31

This PR changes 18.1 to 10.0

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/54762

### Previous Behavior
pip.installed state will fail to load with pip >=10.0  and <=18.0

### New Behavior
pip.installed state will load with pip >=10.0  and <=18.0

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by OrlandoArcapix** [comment]
Initial PR had an error in it - updated now.

**Comment by OrlandoArcapix** [comment]
Resolves https://github.com/saltstack/salt/issues/54773

**Comment by cmcmarrow** [comment]
@OrlandoArcapix could you add a warning? If the pip version is lower than 18.1 have a warning "pip versions lower than 18.1 may not function currently". Also all changes need test now. Even if its a simple regression test. I can help you with the test if you need it.

**Comment by OrlandoArcapix** [comment]
Hey @cmcmarrow -
would it be correct to put a warning in for versions < 18.1? I'm not sure that's relevant to the pip import of the exceptions module - certainly not something I could make a call on! If there's a requirement for salt to have pip >= 18.1, I'd have thought that should go elsewhere rather than in the exceptions import...

For testing - what would a suitable test be? Something like:
 * Install pip v 18.0
 * check it doesn't fail to import the module and/or do `pip install chicken`

? 

Would be great if you can give me a boost into getting a test in there!

**Comment by dwoz** [comment]
@OrlandoArcapix @cmcmarrow this needs tests to get in.

**Comment by dwoz** [comment]
Closing this in favor of #54807 which adds tests for the change

**Pull request closed without merging**
