### PR TITLE
Have salt-cloud clean up tmp files

### PR DESCRIPTION
**Pull request by clarkperkins**
### What does this PR do?

We ran in to an issue with our root partition filling up due to thousands of tmp files being left behind by salt-cloud.
### What issues does this PR fix or reference?

none
### Previous Behavior

~5 `tmp*` files were left in the `/tmp` directory for every host launched with salt-cloud
### New Behavior

tmp files in `/tmp` are cleaned up by salt-cloud
### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by terminalmage** [comment]
This still won't fix instances where an exception is raised before we get to the ``os.remove()``. It would probably be best to put this in a try/finally.

**Comment by clarkperkins** [comment]
Ah, good point - I will add that

**Comment by terminalmage** [comment]
You hit upon some good points in raising this issue, but I took a look and came up with my own solution which I think might work better:

https://github.com/saltstack/salt/pull/36484/files

For one, you made me realize that whoever created this issue in the first place was leaving open file descriptors, which my PR fixes by calling ``os.close()`` on them. Also, since we only deal with the temp file in a very small block of code, the try/finally block doesn't need to be so big. Finally, if neither ``contents`` nor ``local_file`` were passed, we'd get a ``NameError`` when we build the SSH command below. Your PR would have fixed this last thing but my PR also adds warning logging which might help in troubleshooting.

What do you think?

**Comment by terminalmage** [comment]
Actually, mkstemp returns an os-level filehandle, so opening the path for writing is entirely unnecessary, we should be using `os.write()` here. I'm updating my PR.

**Comment by terminalmage** [comment]
Closing in favor of #36484.

**Pull request closed without merging**
