### PR TITLE
Correct pip parsing

### PR DESCRIPTION
**Pull request by mchugh19**
### What does this PR do?
Corrects pip.list_upgrades and pip.upgrade_available only returning errors.

### Previous Behavior
Previous runs of pip.upgrade_available would return errors such as:
```
[ERROR   ] Can't parse line 'protobuf (3.2.0) - Latest: 3.5.0 [wheel]'
[ERROR   ] Can't parse line 'psutil (2.2.1) - Latest: 5.4.1 [sdist]'
[ERROR   ] Can't parse line 'py (1.4.34) - Latest: 1.5.2 [wheel]'
[ERROR   ] Can't parse line 'pyasn1 (0.2.2) - Latest: 0.3.7 [wheel]'
[ERROR   ] Can't parse line 'pycparser (2.17) - Latest: 2.18 [sdist]'
[ERROR   ] Can't parse line 'pycryptodomex (3.4.3) - Latest: 3.4.7 [sdist]'
```

### New Behavior
Regex was corrected for pip output and now returns the expected:
```
# salt-call pip.list_upgrades
local:
    ----------
    Babel:
        2.5.1 [wheel]
    CherryPy:
        12.0.1 [wheel]
    ...

# salt-call pip.upgrade_available boto3
local:
    True
```

### Tests written?
No

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by rallytime** [comment]
re-run docs

**Comment by rallytime** [comment]
@mchugh19 A test-case for this would be great so we can ensure this doesn't regress.

**Comment by mchugh19** [comment]
Patch updated and tests added

**Comment by rallytime** [comment]
@mchugh19 Ah, unfortunately there is a merge conflict here now. Can you take a look? Please let us know if you have any questions.

**Comment by mchugh19** [comment]
Should be less conflicted now.

**Review by terminalmage — APPROVED** [review]
:heart:

**Pull request merged**
