### PR TITLE
Remove snapshot by name feature

### PR DESCRIPTION
**Pull request by RootMePLS**
### What does this PR do?
Add new feature - remove named snapshot.
Partially closes the question with #29035. 

### Previous Behavior
It was not possible to remove the selected snapshot. 

### New Behavior
Now we could remove selected snapshot :D (by default without children) 

### Tests written?
Yes

### CODE REVIEW

**Comment by fishhead108** [comment]
Hm, [contributing guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) says nothing about commit signing.
Should I delete this PR, make a new one with the signed commit?

**Comment by cachedout** [comment]
@fishhead108 Thanks catching that. Right now, we prefer signed commits but do not require them. It is fine to leave this PR open and if you could move toward signed commits in the future we would be grateful. At a future point, we will likely end up requiring them but right now we are in a transition period. Thanks. :]

**Comment by cachedout** [comment]
@fishhead108 Can you please adding testing for this in the cloud integration tests for vmware?

**Comment by fishhead108** [comment]
@cachedout 
Oh, my fault :) 
Forgot about it, will do it in a few weeks.

**Comment by fishhead108** [comment]
test written

**Comment by rallytime** [comment]
Thanks very much for writing those tests @fishhead108. I've updated the branch here to make sure we get tests running on the most current code, and then we can get this in.

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
re-run lint

**Pull request merged**
