### PR TITLE
[3006.x] Revert changes from PR 65186

### PR DESCRIPTION
**Pull request by dmurphy18**
### What does this PR do?
Reverts code changes introduced in Salt 3006.5, PR https://github.com/saltstack/salt/pull/65186.
The fix is incomplete and is causing issues, hence revert to previous code and introduce the fix with better and fuller tests at a later point

### What issues does this PR fix or reference?
Fixes:https://github.com/saltstack/salt/issues/65692

### Previous Behavior
Upgrade from 3006.4 to 3006.5 was removing any external minions that had been cached, that is, directory /var/cache/salt/minion/extmods/grains, other commands also removing the cached external grains.

### New Behavior
Upgrade from 3006.4 to 3006.5 was preserves any external minions that had been cached, that is, directory /var/cache/salt/minion/extmods/grains and external grains no longer removed

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [X] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by lkubb** [comment]
@dmurphy18 

I went ahead and upgraded a non-essential minion to 3006.5. The behavior I found was exactly as described in https://github.com/saltstack/salt/issues/65692#issuecomment-1863145204. Custom grains were completely broken with `salt-call` (not `--local`).

I applied https://github.com/saltstack/salt/pull/65738, which makes them usable again, but every single `salt-call` logs an error:

```console
[root@testminion ~]# salt-call grains.get foo
[ERROR   ] Failed to sync grains module: 'master_uri'
local:
    bar
[root@testminion ~]# salt-call test.ping
[ERROR   ] Failed to sync grains module: 'master_uri'
local:
    True
```

Even with https://github.com/saltstack/salt/pull/65738, a simple `salt-call --local test.ping` still wipes custom grains without being asked for.

Are you sure the initial fix is even necessary? It introduces overhead and potential flakiness for avoiding a single `salt-call saltutil.sync_all` on masterless minions.

**Comment by dmurphy18** [comment]
@lkubb I haven't finished with the PR, wanted to a get a PR run in to check on it. Don't have access like I used to, to VMs, to test and unit-test fixes. There is an internal Slack channel that is used for internal review before anything is ready for merge etc., and not close, so please wait till I have a full solution merged.

Recommend attending Open hours tomorrow, going to be a discussion on Salt moving forward under Broadcom.

**Comment by dmurphy18** [comment]
@lkubb btw: salt-call --local test.ping still wipes custom grains, should be correct when it is not a masterless minion, since the custom grains should be on the master and with --local you are not contacting the master, hence they are cleared out.

Will double check with 3006.4 etc, but believe so.

**Comment by lkubb** [comment]
No worries, just trying to help. :) The behavior of wiping the grains with a single `--local` invocation is new in 3006.5 (for anything other than `saltutil.sync_(all|grains)` of course). Other module types are not wiped.

I still think the correct fix is to document custom modules better tbh.

Sadly I will likely not be able to make it tomorrow, will it be posted to the Youtube channel again?

**Comment by dmurphy18** [comment]
@lkubb Should be posted to youtube eventually, the person who does that will be on PTO (like so many) till the New Year, so may be a while, but should be up sometime in January

**Review by s0undt3ch — APPROVED** [review]

**Comment by dmurphy18** [comment]
Waiting for nightly build fixes (they are responsible for the test failures) before proceeding with this fix

**Pull request merged**
