### PR TITLE
x509 fixes

### PR DESCRIPTION
**Pull request by isbm**
### What does this PR do?

Number of bugfixes.

### What issues does this PR fix or reference?

- Python3: byte/unicode mistmatch on `text` parameter (crash)
- `None` type returned instead of an empty dictionary, once minions aren't matched or CA server unavailable (crash)
- Other minor issues

Test should pass as is.

### CODE REVIEW

**Review by terminalmage — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Comment by cachedout** [comment]
Why are we modifying the publish module in a PR for x509 fixes?

**Comment by isbm** [comment]
> Why are we modifying the publish module in a PR for x509 fixes?

Because people think it is cool to have [many returns inside the code](http://homepages.ihug.com.au/~ijoyner/Ian_Joyner/No_return.html) and wrap the way they do not understand what actually is going on. And then when it is expected to be at least an empty dictionary at the end, there is a corner case when it returns just `None` and then you get a crash, instead of expected no-op.

**Review by cachedout — APPROVED** [review]

**Comment by cachedout** [comment]
@akissa or @clinta Do either of you want to review this?

**Comment by dwoz** [comment]
The work done here might fix these two issues:

https://github.com/saltstack/salt/issues/49027
https://github.com/saltstack/salt/issues/49008

**Comment by rnickle** [comment]
Is it easy to intercept these fixes earlier?  The PPA for Ubuntu is pointing to 2018.3.3 right now.

**Pull request merged**
