### PR TITLE
WiX/MSI setup project

### LINKED ISSUE #19232: Windows minion version mismatch
I'm not sure if this also applies to 2014.1.10, but in 2014.7.0.win32 the version shown in windows control panel and the version reported by pkg.list_pkgs is 2014.7.0 while the 2014.7.0.amd64 package shows the version as v2014.7.0. This causes a bit of headache if you're trying to use winrepo to upgrade the minion and don't catch the version issue.

### PR DESCRIPTION
**Pull request by saxonww**
- create MinionMSI WiX project
- create MinionConfigurationExtension extension library
- remove pkg/windows/installer
- move pkg/windows/buildenv into MinionMSI
- simple msbuild project to restore dependencies and build the setup
  package.

See README.md for more details on this project.

Should address #19137, #14806, #12187, #4633, #4614, #4502 and #4136.
Provides a starting point for #19220, #18412, #18431 and #12804.
May resolve #19232.

NOTE 1: I've only tested install/uninstall on my own machine (Win7 x64 SP1) with a win32 build.

NOTE 2: This does not implement the vcredist install and cannot cleanly uninstall if the minion service is running. These appear to be limitations of .msi; the former could be fixed by a bundle install or (preferably) inclusion of the vc++ 2008 redist merge module, the latter by removing nssm.exe altogether.

This is a second pull request - first (which I closed) has wrong author.

### CODE REVIEW

**Comment by thatch45** [comment]
Thanks @saxonww! The licence stuff can be a real bear, I am going to sit down with @UtahDave and go over this all and figure out the best way to get it merged in, we may want to have a separate repo, but we may not, thanks for being patient with us over the holidays while we figure this out!

**Comment by UtahDave** [comment]
Hey @saxonww I've created a repo for this here: https://github.com/saltstack/salt-windows-msi

I'd really like to get this integrated into our build process, but we're going to have to do a review of the license in those files. Some of our users are VERY sensitive to having anything more viral than the Apache license.

In the meantime, could you recreate this pull request on the above repo and have it depend on be next to the salt repo for doing the building? This would really help to move this forward. Sorry for the hassle.

Send me an email at dave@saltstack.com if you want to discuss this further.

Thanks!

**Comment by saxonww** [comment]
Sounds good, I will get it pushed tonight or tomorrow.

I have some ideas on the licensing, depending on what you want to end up
with I think we can eliminate those files altogether. I will follow up w/
email.

**Comment by thatch45** [comment]
Thanks @saxonww let me know when we can close this one out and transition tot he other repo, thanks for being patient with us!

**Comment by saxonww** [comment]
Closing this PR

**Comment by thatch45** [comment]
Thanks @saxonww ! It can be really hard to keep this list clean :)
I am looking forward to getting this all taken care of!

**Pull request closed without merging**
