### PR TITLE
Correctly detect Nutanix AHV as virtual

### PR DESCRIPTION
**Pull request by rolo9707**
### What does this PR do?
Correctly detect Nutanix AHV as virtual in grains.virtual on CentOS/RHEL using virt-what.
### What issues does this PR fix or reference?
Fixes:
Nutanix AHV is detected as physical by grains.virtual
### Previous Behavior
Nutanix AHV did not get detected as virtual but physical, since the keyword nutanix_ahv was not present as a qualified virtual machine.

### New Behavior
Nutanix AHV is detected as virtual with the name Nutanix. Tested with CentOS 7 and CentOS 8 Stream

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by ggiesen** [comment]
Given that AHV runs on KVM, perhaps `grains['virtual']` should be set to `kvm` and `grains['virtual_subtype']` should be set to either `ahv` or `nutanix`?

**Comment by whytewolf** [comment]
@rolo9707 see comment by @ggiesen I do agree with his assessment. also, can you fix the conflict?

**Comment by whytewolf** [comment]
@rolo9707 just noticed this is going to need a changelog and tests as well.

**Comment by whytewolf** [comment]
@rolo9707 did you see the update requests above?

**Comment by rolo9707** [comment]
Hi.

I am sorry, but I do not know how and where to add changelog and tests.

Best regards,
Ronny

tir. 6. des. 2022 kl. 10:17 skrev Thomas Phipps ***@***.***>:

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
