### PR TITLE
Add ability to artifactory state to download the latest release of an artifact.

### PR DESCRIPTION
**Pull request by ayackel**
This adds to the artifactory state the ability to download the latest release of an artifact.  The artifactory state currently has the ability to download the latest snapshot of an artifact, though this feature is undocumented.  This pull request adds the feature, addresses the documentation, and cleans up names of some private methods.

### CODE REVIEW

**Comment by cachedout** [comment]
Nice!

There are a few lint errors outlined here: https://jenkins.saltstack.com/job/salt-pr-lint-n/12408/violations/file/salt/states/artifactory.py/

Could you please fix those up and then we can get this merged?

Great work here, @ayackel

**Comment by cachedout** [comment]
The cleanup of the names of the private funcs here has broken some tests. Is there a a reason we can't continue to use single underscores as a prefix for these?

**Comment by ayackel** [comment]
No, there's not.  There was just a mix of single and double underscores in the class.  I'm happy to undo that part.

**Comment by cachedout** [comment]
If you could pull those back to singles, I think that's the easiest fix here. Thanks.

**Comment by ayackel** [comment]
I think this also addresses issue #25844.

**Pull request merged**
