### PR TITLE
Fix shadowed builtins

### PR DESCRIPTION
**Pull request by terminalmage**
`id`, `hex`, and `list` were all shadowed, this PR fixes that.

### CODE REVIEW

**Comment by cachedout** [comment]
@terminalmage Test failure here. https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/5629/violations/file/tests/unit/modules/mac_xattr_test.py/

**Comment by terminalmage** [comment]
Fix pushed.

**Comment by rallytime** [comment]
@terminalmage Looks like some unit tests need to be updated/addressed with this change. Can you take a look?

**Comment by terminalmage** [comment]
@rallytime Pushed another commit. I was able to run the unit tests locally so this should clear up the remaining failures.

**Pull request merged**
