### PR TITLE
Add local file support for file.managed source list

### PR DESCRIPTION
**Pull request by paulnivin**
Add local file support to file.source_list along with tests and documentation for file.managed to explicitly state the kinds of URLs that can be part of a source list.

### CODE REVIEW

**Comment by cachedout** [comment]
Looks good, @paulnivin. Thanks for this!

**Comment by lorengordon** [comment]
Issues that may possibly be fixed by this, particularly if `file://` now also works with `source_hash`:

- https://github.com/saltstack/salt/issues/26398
- https://github.com/saltstack/salt/issues/26497
- https://github.com/saltstack/salt/issues/26526

**Comment by terminalmage** [comment]
@lorengordon The first two I closed, the third I opened https://github.com/saltstack/salt/pull/29289 to resolve. Thanks for the information.

**Comment by lorengordon** [comment]
@terminalmage, awesome, thanks!

**Pull request merged**
