### PR TITLE
Further clarifications on "unless" and "onlyif" requisites.

### LINKED ISSUE #14634: 'unless' documentation isn't logically plausible
http://docs.saltstack.com/en/latest/ref/states/requisites.html

22.25.15.2 states 

"Use unless to only run if any of the specified commands return False."

Implying unless = (!A or !B)

and then says "This state will not run if the vim-enhanced package is already installed, or if /usr/bin/vim exists"

Implying unless = !(A or B), which is subtly different.

Onlyif is defined as !unless, which could be !(!A or !B) [ (A and B) ], or (A or B), if my De Morgan's laws hold true!

### PR DESCRIPTION
**Pull request by rallytime**
Fixes #14634
- "unless" is actually a NAND operator
- remove usage of "opposite of unless" as that is confusing
- add note about using shell's concept of T/F vs Python's concept

### CODE REVIEW

**Comment by lorengordon** [comment]
This is funny, because these changes make it more clear that onlyif uses AND logic (all conditions are true), and so it actually is the opposite of unless (NAND literally is the opposite of AND) What previously was confusing to me was interpreting the condition reversal, 'any of false' vs 'all of true'; I actually resorted to a truth table to prove to myself 'any of false' was just NAND. :D

**Comment by rallytime** [comment]
@lorengordon oh! You're right. I had to pull out the truth table too, to make sure the NAND instead of NOR change was correct, because the words were getting muddled in my head. I guess I could add the `opposite` wording back in and add the AND for `onlyif`.

**Comment by lorengordon** [comment]
@rallytime, heh, no, probably unnecessary. I think it gets too confusing to think of them as opposites due to the difference between them in testing a false vs true return. True and false are opposites too! I'd guess that few would appreciate the AND/NAND significance. I think the most confusing of the wording is gone now and it is much more clear than it was before. I just remembered having this same confusion with the docs, seeing the reported issue and the confusion there, and so I was actually grateful to see the PR and couldn't restrain myself from commenting. Thanks! :smile:

**Comment by rallytime** [comment]
@lorengordon No problem! I'll leave it. Thanks for the feedback!

**Pull request merged**
