### PR TITLE
Update existing VMs in virt.running

### PR DESCRIPTION
**Pull request by cbosdo**
### What does this PR do?

This PR makes ``virt.running`` able to update existing VMs, running or not. If the VM is already running, the new definition will be applied for the next start and as many live updates as possible will be attempted.

A new ``virt.update`` function has been introduced in the virt execution module.

The PR also removes the use of minidom in the virt execution module for more consistency... and ElementTree helps removing some XML helper functions.

### What issues does this PR fix or reference?

None

### Previous Behavior

* ``virt.running`` on a running VM did nothing
* ``virt.running`` on a defined, but stopped VM started it

### New Behavior

* virt.running on a running VM tries hard to update it without restarting it
* virt.running on a stopped VM changes the definition and starts it.

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by cbosdo** [comment]
@rallytime @gtmanfred yet another feature (+ cleanup) PR for the virt modules that you surely want to look into.

**Review by gtmanfred — COMMENTED** [review]
Looks like some tests are failing

https://jenkinsci.saltstack.com/job/pr-kitchen-centos7-py2/job/PR-48736/2/

**Comment by cbosdo** [comment]
@gtmanfred oops... Two of the failures are indeed mine and I'll fix them, but the 3 others ones are completely unrelated to this PR.

**Comment by cbosdo** [comment]
The two unit tests are now fixed, thanks for the heads up

**Review by gtmanfred — APPROVED** [review]

**Review by rallytime — APPROVED** [review]

**Pull request merged**
