### PR TITLE
Ignore retcode when checking FS type

### PR DESCRIPTION
**Pull request by terminalmage**
This is used in part to check if the block device being checked actually exists. In these cases, a nonzero exit code is not an error condition, and thus should not have its results logged at the ERROR loglevel.

### CODE REVIEW

**Review by dwoz — COMMENTED** [review]
@terminalmage This seems like it might be a difficult one to test, but can you think of a way to add a regression test for this bugfix?

**Comment by terminalmage** [comment]
@dwoz How about that??

**Comment by twangboy** [comment]
@terminalmage Looks like you got some lint

**Review by s0undt3ch — APPROVED** [review]

**Review by dwoz — APPROVED** [review]
@terminalmage Works for me. :)

**Comment by dwoz** [comment]
The docs will pass after #52622 is merged.

**Pull request merged**
