### PR TITLE
Fix issues with win_service

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?
Add shlex.quote
Properly quote the path to the binary (`bin_path`) on `create` and `modify`. It was removing double quotes. Double quotes are needed for paths to binaries with spaces. Single quotes will fail also.
Don't crash on `service.stop` when the service is already stopped
Don't crash on `service.delete` when the service is not present
Fix issues with the exception handling

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/48828
https://github.com/saltstack/salt/issues/49234

### Tests written?
No

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by twangboy** [comment]
I still need to write some tests for this

**Comment by damon-atkins** [comment]
- Consider using from salt.utils.win_functions import **escape_argument**
- We should not convert single quotes as its a valid file name, even if its a bad idea for someone to use it in a filename.

**Comment by damon-atkins** [comment]
ping @ciiqr

**Comment by damon-atkins** [comment]
- Consider using from salt.utils.win_functions import **escape_argument** or **escape_for_cmd_exe** instead of shlex.quote
- We should not convert single quotes as its a valid file name, even if its a bad idea for someone to use it in a filename.
- Suggest you check for reporting `changes` impacts to states/service.py with the  start/stop returning true when already started/stopped etc.

The other alternative is to check for begins with " then leave it alone, otherwise wrap " around it after running  **escape_argument** or **escape_for_cmd_exe**

**Comment by twangboy** [comment]
@damon-atkins 
Neither of the `win_functions` commands will work in this case as they actually escape the quotes at the beginning and end. For example, `C:\Temp Dir\test.exe` becomes `^"C:\\Temp Dir\test.exe^"`. The command needs to be passed with unescaped double quotes.

Since this is the service module, I can't think of an instance where the path to an exe would start or end with a single quote. It would always end in `.exe` and would always start with the drive letter.

The `_cmd_quote` function only strips quotes from the beginning and the end. It doesn't strip single quotes from anything inside. This produces a valid value no matter how the bin_path is quoted in the state file.

**Comment by rallytime** [comment]
@dwoz can you take a look here?

**Review by dwoz — APPROVED** [review]

**Comment by rallytime** [comment]
@twangboy It looks like there is a related windows test failing here:

https://jenkinsci.saltstack.com/job/pr-windows2016-py2/job/PR-49327/2/testReport/junit/integration.modules.test_service/ServiceModuleTest/test_service_status_running/

Yay for catching that now! 🎉

**Comment by twangboy** [comment]
@rallytime This may be a flaky test. I can't replicate it manually. Is there a way to re run?

**Comment by cachedout** [comment]
Might be related and might not, since this PR also whitelists that test for the first time. Still, though, we'll want to mark it as a flaky or fix the test before we merge this. I'll re-reun tests now to see what comes back.

**Pull request merged**
