### PR TITLE
Fix reporting of errors for file.directory in test mode

### LINKED ISSUE #61846: [BUG] file.directory reports error in test mode
**Description**
When a user account has not yet been created and is specified as the owner of a directory, `file.directory` reports an error and shows the state as failed in test mode.

**Setup**

```yaml
# /srv/salt/dir.sls

# this user doesn't exist yet
anne:
  user.present

/tmp/anne:
  file.directory:
    - user: anne
    - require:
      - user: anne
```
  
**Steps to Reproduce the behavior**
Given the sls file above in the file root, this command:

```bash
salt-call state.apply dir test=true
```

returns this output:

```
[ERROR   ] User anne is not available 
local:
----------
          ID: anne
    Function: user.present
      Result: None
     Comment: User anne set to be added
     Started: 15:08:34.221828
    Duration: 20.913 ms
     Changes:   
----------
          ID: /tmp/anne
    Function: file.directory
      Result: False
     Comment: User anne is not available
     Started: 15:08:34.284309
    Duration: 5.662 ms
     Changes:   

Summary for local
------------
Succeeded: 1 (unchanged=1)
Failed:    1
Success %: 50.0
Failure %: 50.0
------------
Total states run:     2
Total run time:  26.575 ms
```

**Expected behavior**
Given that we're running in test mode, failures should not be reported for items which may be addressed in other states.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
               Salt: 3004
 
Dependency Versions:
               cffi: 1.15.0
           cherrypy: unknown
           dateutil: 2.7.3
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: 2.1.11
             Jinja2: 2.10
            libgit2: 1.3.0
           M2Crypto: Not Installed
               Mako: Not Installed
            msgpack: 0.5.6
       msgpack-pure: Not Installed
       mysql-python: Not Installed
          pycparser: 2.19
           pycrypto: 2.6.1
       pycryptodome: 3.6.1
             pygit2: 1.7.0
             Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
       python-gnupg: Not Installed
             PyYAML: 3.13
              PyZMQ: 17.1.2
              smmap: 2.0.5
            timelib: Not Installed
            Tornado: 4.5.3
                ZMQ: 4.3.1
 
Salt Extensions:
 saltext.prometheus: 1.0.0
 
System Versions:
               dist: debian 10 buster
             locale: UTF-8
            machine: x86_64
            release: 4.19.0-18-amd64
             system: Linux
            version: Debian GNU/Linux 10 buster
```
</details>

### PR DESCRIPTION
**Pull request by nicholasmhughes**
### What does this PR do?
When a user account has not yet been created and is specified as the owner of a directory, `file.directory` reports an error and shows the state as failed in test mode.

### What issues does this PR fix or reference?
Fixes: #61846 

### Previous Behavior
See issue for details.

### New Behavior
In test mode, a warning will be thrown about the inability to find the user/group. However, the state will not return as failed (`False`).

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by nicholasmhughes** [comment]
re-run pr-arch-lts-x86_64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-arch-lts-x86_64-py3-pytes

**Comment by nicholasmhughes** [comment]
pr-arch-lts-x86_64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-arch-lts-x86_64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-windows-2016-x64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-windows-2016-x64-py3-pytest

**Review by whytewolf — APPROVED** [review]

**Review by MKLeb — APPROVED** [review]

**Pull request merged**
