### PR TITLE
[WIP] Code cleanup for zfs/zpool

### PR DESCRIPTION
**Pull request by sjorge**
### What does this PR do?
This PR attempts to cleanup the code and reduce complexity for the zfs and zpool modules and states.

- [x] salt.utils.zfs
  - [x]  proper conversion from zfs 'values' to pythonic values
  - [x] command building with proper escaping and conversion for values
  - [x] common code like testing for feature flags, zfs support,...
- [x] salt.grains.zfs
  - [x] use __utils__['zfs.is_supported']
  - [x] use __utils__['zfs.has_feature_flags']
- [x] salt.modules.zpool
  - [x] switch to ```__utils__['zfs.zpool_command']```
  - [x] simply error handing (pass along what zpool complains about)
  - [x] refactor or clarify parsing code
- [ ] salt.modules.zfs
  - [ ] switch to ```__utils__['zfs.zfs_command']```
  - [ ] simply error handing (pass along what zfs complains about)
  - [ ] refactor or clarify parsing code
- [ ] salt.states.zpool
  - [ ] update to work with update salt.modules.zpool
- [ ] salt.states.zfs
  - [ ] update to work with update salt.modules.zfs

### What issues does this PR fix or reference?
#44801

### Previous Behavior
Lots of duplicate code

### New Behavior
Most duplicate code moved to a salt.utils.zfs, only do minimal error handling in modules (zfs/zpool command are pretty good at reporting what is wrong, so we just show that instead), more readable parsing code (hopefully).

### Tests written?
Yes

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by sjorge** [comment]
# TODO

- [X] from_bool/from_str/from_numeric/from_size
- [X] to_bool/to_str/to_numeric/to_size 
- [ ] from_auto(field, value)
- [ ] to_auto(field, value)
- [ ] is_zfs_available
- [ ] zfs_command wrapper
- [ ] zpool_command wrapper
- [ ] salt.utils.zfs tests (if possble)
- [ ] code cleanup
  - [ ] cleanup grains
  - [ ] cleanup salt.modules.zpool
  - [ ] cleanup salt.modules.zfs
  - [ ] cleanup salt.states.zpool
  - [ ] cleanup salt.modules.zfs

**Comment by sjorge** [comment]
Type conversion is done, command wrappers will probably be for next weekend.

I'm unsure how to test the to_auto and from_auto functions, I'd patch the dict to override a result but that does not seem to work for salt.utils

**Comment by sjorge** [comment]
During the week I will cleanup the code to use the zfs util for variable conversion and command generation.

Hopefully in time for the next release as I am not 100% happy with the last few fixes that happened.
Codeclimate does seem to complain about some functions but I not seeing a way to make those cleaner. Some stuff is sadly just complex :(

**Comment by sjorge** [comment]
@rallytime any idea why some of the tests I create fail? They work fine locally.

```
[isotope :: root][/workspace/salt][zfsutil_44801 ✔]
[.]# ./tests/runtests.py -n unit.utils.test_zfs
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Python Version: 2.7.13 (default, Jul 4 2017, 00:21:04) [GCC 4.9.4]
 * Transplanting configuration files to '/tmp/salt-tests-tmpdir/config'
 * Current Directory: /workspace/salt
 * Test suite is running under PID 27532
 * Logging tests on /tmp/salt-runtests.log
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Starting unit.utils.test_zfs Tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.......................................................................
----------------------------------------------------------------------
Ran 71 tests in 0.200s

OK

============================  Overall Tests Report  ============================
***  No Problems Found While Running Tests  ************************************
================================================================================
OK (total=71, skipped=0, passed=71, failures=0, errors=0)
============================  Overall Tests Report  ============================
```

**Comment by rallytime** [comment]
Hey @sjorge - thanks for all of this work! It looks like you're still working on this, so let us know when it's ready for review.

It's OK if there are functions that are exceeding the complications in the CodeClimate checks. We are just trying that out for now. We probably need to tweak some of those checks.

The feature freeze deadline for Oxygen has already passed, so this won't make it for Oxygen, unfortunately. The next feature release is Fluorine, so you should have plenty of time to get this in over the next 6 months or so.

**Comment by sjorge** [comment]
Anyone that has some more PY2 vs PY3 experience, the results for py3 of the string escaping seems to be different but I don't understand why.

to_str
```
Traceback (most recent call last):
  File "/testing/tests/unit/utils/test_zfs.py", line 458, in test_to_str_quote_space
    self.assertEqual(zfs.to_str("my pool/jorge's dataset"), "'my pool/jorge\\\\'s dataset'")
AssertionError: "'my pool/jorge\\'s dataset'" != "'my pool/jorge\\\\'s dataset'"
- 'my pool/jorge\'s dataset'
+ 'my pool/jorge\\'s dataset'
?                +
```

from_str
```
Traceback (most recent call last):
  File "/testing/tests/unit/utils/test_zfs.py", line 429, in test_from_str_quote_space
    self.assertEqual(zfs.from_str("'my pool/jorge\\\\'s dataset'"), "my pool/jorge's dataset")
AssertionError: "my pool/jorge\\'s dataset" != "my pool/jorge's dataset"
- my pool/jorge\'s dataset
?              -
+ my pool/jorge's dataset
```

The other test failures on py3 come from this as wel, since the command building code uses these functions.

**Comment by sjorge** [comment]
@rallytime Both the name escaping code in salt/modules/zfs.py (merge from someone else earlier) and the slightly modify one have the same result between py2 and py3 :/

I'm at a loss here, I cannot get it consistent between these two.

**Comment by sjorge** [comment]
Similar encoding seems to happen in salt/modules/system.py's set_computer_desc, they however use double quotes instead of single quotes, I have better results with those as wel... I will switch to double quotes, my initial tests are the same for spaces are now allowed

**Comment by sjorge** [comment]
@rallytime Can you give jenkins another kick? I want to see if the tests success on both py2 and py3 but it seems to be stuck.

**Comment by rallytime** [comment]
re-run py

**Comment by 3add3287** [comment]
Hi
@sjorge 
Only vaguely remember. There was a problem with my test cases that didn't work and I couldn't grasp after tracing how the commands in the end gets executed via Popen(). Was under time constraints and came across the escaping in another module and copied it. Might have been system.py, but don't remember the details.

**Comment by sjorge** [comment]
Alright, i’ll go with that I have now, I can always revisit (hope not because this is PITA one to get cross py2/py3) if the after the refactor spaces and such don’t work in names and paths.

Manually running the output from zfs.zfs_command on the terminal works now, but as you said that still needs to pass through salts cmd.run_all in the actually modules/states

**Comment by sjorge** [comment]
Not much progress today :( I did write test script that actually creates a real zpool and does stuff on it.
So I can compare the before and after output.

**Comment by sjorge** [comment]
# TODO

- [X] from_bool/from_str/from_numeric/from_size
- [X] to_bool/to_str/to_numeric/to_size 
- [X] from_auto(field, value)
- [X] to_auto(field, value)
- [X] is_supported
- [X] has_feature_flags
- [x] tests for conversion functions
- [x] zfs_command wrapper
- [x] zpool_command wrapper
- [x] test for command wrappers
- [ ] code cleanup
  - [x] cleanup grains
  - [ ] cleanup salt.modules.zpool
    - [x] phase 1 - switch to zfs.zpool_command
    - [ ] phase 2 - refactor code to make it cleaner (if possible, else add more comments)
    - [ ] fix broken tests 
  - [ ] cleanup salt.modules.zfs
  - [ ] cleanup salt.states.zpool
  - [ ] cleanup salt.modules.zfs

**Comment by sjorge** [comment]
@rallytime I'm running into a chicken-egg problem with the tests...

```
Traceback (most recent call last):
  File "/testing/tests/unit/modules/test_zpool.py", line 123, in test_status
    ret = zpool.status()
  File "/testing/salt/modules/zpool.py", line 161, in status
    stat_data = __utils__['zfs.from_auto_dict'](stat_data)
  File "/testing/salt/utils/zfs.py", line 543, in from_auto_dict
    values[name] = from_auto(name, value, source)
  File "/testing/salt/utils/zfs.py", line 525, in from_auto
    return _auto('from', name, value, source)
  File "/testing/salt/utils/zfs.py", line 160, in _auto
    props = property_data_zpool()
  File "/testing/salt/utils/decorators/__init__.py", line 194, in _memoize
    cache[args_] = func(*args, **kwargs)
  File "/testing/salt/utils/zfs.py", line 333, in property_data_zpool
    'autoreplace': 'replace',
  File "/testing/salt/utils/zfs.py", line 118, in _property_parse_cmd
    if cmd[-3:] != 'get':
TypeError: 'NoneType' object has no attribute '__getitem__'
```

The error is 'correct' as given that _property_parse_cmd got wrong data.

Take the snippet from test_status for example:
```
        with patch.dict(zpool.__salt__, {'cmd.run_all': mock_cmd}), \
                patch.dict(zpool.__utils__, utils_patch):
            ret = zpool.status()
            self.assertEqual('ONLINE', ret['mypool']['state'])
```

I mock the actually result of cmd.run_all that returns the data, which is working well.
I also patched the zpool.\_\_utils\_\_ dict so a few functions are mocked.

```
utils_patch = {
    'zfs.is_supported': MagicMock(return_value=True),
    'zfs.has_feature_flags': MagicMock(return_value=False),
    'zfs.property_data_zpool': MagicMock(return_value=pmap_zpool),
    'zfs.property_data_zfs': MagicMock(return_value=pmap_zfs),
    # NOTE: we make zpool_command and zfs_command a NOOP
    #       these are extensively tested in tests.unit.utils.test_zfs
    'zfs.zpool_command': MagicMock(return_value='/bin/false'),
    'zfs.zfs_command': MagicMock(return_value='/bin/false'),
}
```

This is all well for the called made via \_\_utils\_\_ from salt.modules.zpool, some of those calls e.g. ```zfs.from_auto_dict``` will make a call to ```from_auto->_auto->property_data_zpool```

As you can see above I did mock property_data_zpool actual code cannot run without having a working zfs setup. The problem is that inside salt.utils.zfs (where the sub calls happen) I cannot use \_\_utils_\_\ as it does not exists. I tried using lazy load to hack that in but of course it cannot load itself because then it would be running in circles :(

Any way to solve this? I considered mocking every single called to \_\_utils\_\_ that happens inside every function I test in tests.unit.modules.test_zpool... but that would be weeks of work. It would get complex rather fast too so there would be more hardcoded test stuff to the point were the tests themselves become nearly useless.

**Comment by sjorge** [comment]
I think I found a solution for my problem while stuck in traffic (2+h to think about it) yesterday.

*crosses fingers*

**Comment by sjorge** [comment]
Slowly making progress, refactoring is a lot less exciting than writing now code :p

**Comment by sjorge** [comment]
@rallytime is jenkins broken? I was did a about half of the zpool module today, but everytime I push everything seems to fail. But locally slint is good and all tests pass

**Comment by sjorge** [comment]
Progress is very slow, but slowly cleanup up the zpool module and adding tests.

**Comment by rallytime** [comment]
Thanks for your work @sjorge :)

**Comment by sjorge** [comment]
@rallytime any update ob jenkins?

**Comment by sjorge** [comment]
Finally some progress, salt.modules.zpool is now done.
It has a lot more tests and code is now (hopefully) more readable and consistent.
Lots of 'error' preventing code was dropped, the zpool command has very clean error messages we just report back instead.

Over the weekend I hope to start tacking salt.states.zpool... any good examples of tests for states? There are none at the moment but I might try and add a few.

**Comment by sjorge** [comment]
Started work on salt.modules.zfs, ... some stuff is currently broken (to be expected)
- test_zfs (lots of stuff that got mocked is now gone from the module, like with test_zpool)
- zpool/zfs states (will get fixed after the modules are done)

While giving the zpool stuff a good testing I found a few more issues with the to_size conversion. I asked some of the illumos devs I knew and they pointed me to the C implementation and pyzfs implementation. I now made sure those have the same results as we do.

**Comment by sjorge** [comment]
Ok the latest rebase against development really messed up this branch, it is complains that files I didn't touch will get overwritten so I lose my changes. I might close this PR and make a new one and cherry pick my commits... not certain yet.

**Pull request closed without merging**
