### PR TITLE
corrects a bug with passing tags to boto_rds module

### PR DESCRIPTION
**Pull request by jessebye**
### What does this PR do?
Fixes a bug in `salt.modules.boto_rds` where tags passed to the create function would not get parsed correctly.

### What issues does this PR fix or reference?
[Issue #38936](https://github.com/saltstack/salt/issues/38936)

### Previous Behavior
The new RDS instance is created without any tags, even though tags are passed to the boto_rds state/module.

### New Behavior
The new RDS instance is created *with* tags if tags are passed to the state/module.

### Tests written?

No

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by jessebye** [comment]
@ryan-lane @tkwilliams

**Comment by ryan-lane** [comment]
I think @tkwilliams is more familiar with this module. I haven't worked on this one at all.

**Review by tkwilliams — APPROVED** [review]
Without actually pulling and testing the change :) it LOOKS quite reasonable.  Definitely cleaner...

**Review by rallytime — APPROVED** [review]
Welcome to @jessebye! Thank you for submitting this fix.

**Pull request merged**
