### PR TITLE
Fix ini issues

### PR DESCRIPTION
**Pull request by ScoreUnder**
I recently ran `brew upgrade --HEAD saltstack` and noticed _a lot_ of breakage in ini-related states.

The first thing I discovered is that `ini.options_absent` no longer supported multiple options and would not take lists. This is both a breaking change and a huge inconvenience, requiring a separate state per key deleted (because you could only delete one key per section per state). The documentation had been modified in an attempt to reflect the changes but ended up still incorrect.

The next thing I noticed is that I had an integer being replaced in the ini file, but it was being registered as a change every time, even when the number was identical. I had to cast it to a string to fix this.

Finally, I wiped the ini file and re-ran the salt call, and to my horror it had been replaced with several lines similar to:

```
section1 = OrderedDict([...])
section2 = OrderedDict([...])
```

I've attached a set of commits which I believe fixes all these issues, undoes the breaking change, and reverts the documentation to describe the original behaviour again.

### CODE REVIEW

**Comment by ScoreUnder** [comment]
I'll investigate the unit tests, hold tight.

**Comment by ScoreUnder** [comment]
Attempted a fix to the unit tests by converting the `_Section` to a `dict` before putting it into the `changes` dictionary.

The reason I avoided just using the old value of `value` is because it could have been any data structure, including one that might have been lossily transformed when converted into a `_Section`. If that's the case, putting it into the changes dictionary would be misleading as it might indicate changes which were not actually made.

**Comment by cachedout** [comment]
Hi @ScoreUnder 

Thanks for this and apologies for the sudden breakage. A cursory glance shows that perhaps a lot of these changes you mention were introduced here: https://github.com/saltstack/salt/pull/26359

What I'd like to do is walk through that and, as best we can, ensure that we're providing a consistent experience and ensure that we're not regressing on bugs which that PR attempted to fix.

cc: @Akilesh1597

**Comment by ScoreUnder** [comment]
If the author of those commits is going to have their say, there's one thing I want to mention that puzzled me while I was reading the code.

Why is the ini file format in memory given support for nested data structures, when that's not supported by the actual format on disk? It made the _Section class (and _Ini's inheritance from it) rather confusing to read for me, and it will result in strange behaviour if someone unknowingly passes a dictionary one level too deep to their `ini.options_present` state.

**Comment by cachedout** [comment]
@ScoreUnder I'll give @Akilesh1597 until the end of the day and then if we don't hear from them, I'll just go ahead and merge this. Thanks for your patience.

**Pull request merged**
