### PR TITLE
Keep the schedule jobs in ONE place.

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
### What does this PR do?

Fix minion multimaster failover.
### What issues does this PR fix or reference?
#36134
### Previous Behavior

Minion schedule has read schedule jobs via `config` module but has modified the jobs via `self.opts` that are different objects. So minion has always being executed the schedule it read from the config on start.
### New Behavior

As discussed with @thatch45 changed schedule to modify the jobs via `config` module too.
### Tests written?

No

### CODE REVIEW

**Review by cachedout — COMMENTED** [review]
This definitely seems like the right fix but should we come up with a better name for `self.options`? It is hard to know how this is different than `self.opts`. I think some in-line documentation for this might be useful or it will be hard to know what's going on here in the future.

**Comment by DmitryKuzmenko** [comment]
Hmm... The `salt.utils.schedule.Schedule.option()` was introduced by @thatch45 when the Schedule was introduced in salt at the beginning of 2013th. Actually I'm not sure what name is better for this function. Maybe `get_merged_opt()`?

**Comment by cachedout** [comment]
Ah, I didn't realize that name was already in use. My fault. Let's go ahead and get this in and consider renaming this stuff for clarity down the road. Thanks, @DmitryKuzmenko

**Comment by thatch45** [comment]
I agree @cachedout , this threw me. It should be renamed

**Pull request merged**
