### PR TITLE
Last bit to disable codecov's PR status checks

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title

### CODE REVIEW

**Review by Ch3LL — DISMISSED** [review]

**Review by Ch3LL — DISMISSED** [review]

**Review by garethgreenaway — DISMISSED** [review]

**Comment by waynew** [comment]
I would prefer changing it to `informational: True` - then we still get the information, but it doesn't (shouldn't?) block the PR

**Comment by s0undt3ch** [comment]
@waynew agreed and updated

**Review by waynew — APPROVED** [review]
🚀

**Comment by Ch3LL** [comment]
will this still show failing tests? If i remember previously, when I try to click on codecov's results I couldn't even see them, so the failing test seemed unnecessary to include

**Review by garethgreenaway — APPROVED** [review]

**Comment by s0undt3ch** [comment]
Not tests, _per se_, you're referring to codecov's reports.

**Comment by s0undt3ch** [comment]
Some will render fine, most will, still, timeout

**Comment by Ch3LL** [comment]
yeah tests wasn't the right word to say. I mean a failing job on the PR- are we going to see a RED job if codecov fails. If this is the case and they are timing out and we can't rely on them why keep them to informational then and instead disable it all together until its resolved?

**Comment by s0undt3ch** [comment]
We should stop seeing the RED for codecov on PRs, according to their docs.

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
