### PR TITLE
fixes fail on dsc.compile_config

### LINKED ISSUE #61261: [BUG] First-time dsc.compile_config in win_dsc.py fails
**Description**
The first time a dsc.compile_config is run on a fresh install, it produces two files;
1. \<target\>.mof
1. \<target\>.meta.mof  

Properties from both of these files are returned as a `list` from the command
```
cmd.append(
        "| Select-Object -Property FullName, Extension, Exists, "
        '@{Name="LastWriteTime";Expression={Get-Date ($_.LastWriteTime) '
        "-Format g}}"
    )
cmd = " ".join(cmd)
ret = _pshell(cmd, cwd)
if ret:
        # Script compiled, return results
        if ret.get("Exists"):
```

This is from the minion log, where you see that both a `localhost.mof` and a `localhost.meta.mof` is returned:
```
2021-11-18 18:54:42,885 [salt.loaded.int.module.win_dsc:91  ][INFO    ][8024] DSC: Returning "[{'FullName': 'C:\\DryDSCConfiguration\\localhost.mof', 'Extension': '.mof', 'Exists': True, 'LastWriteTime': '18.11.2021 18:54'}, {'FullName': 'C:\\DryDSCConfiguration\\localhost.meta.mof', 'Extension': '.mof', 'Exists': True, 'LastWriteTime': '18.11.2021 18:54'}]"
```

Therefore, when `dsc.compile_config` does the following: 
```
if ret:
        # Script compiled, return results
        if ret.get("Exists"):
            log.info("DSC: Compile Config: %s", ret)
            return ret
```
the following error is returned: 
```
AttributeError: 'list' object has no attribute 'get'
```

Note that on subsequent compiles, only a .mof is produced . 

**Setup**

Please be as specific as possible and give set-up details.

- [ x ] on-prem machine
- [ x] VM vCenter
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Run a dsc.compile_config on a fresh install of windows, or a windows machine on which a dsc compilation has not been performed

**Expected behavior**
The PowerShell command that produces the return value should filter on the .mof file, so that the .meta.mof is filtered out.  
image

This is from win_dsc.py: 
image

This is from the minion log. I Added "ret info" to see for myself what was going on: 
image

**Versions Report**
Salt Version:
Salt: 3004

Dependency Versions:
cffi: Not Installed
cherrypy: Not Installed
dateutil: 2.7.3
docker-py: Not Installed
gitdb: 2.0.6
gitpython: 3.0.7
Jinja2: 2.10.1
libgit2: 0.28.3
M2Crypto: Not Installed
Mako: Not Installed
msgpack: 0.6.2
msgpack-pure: Not Installed
mysql-python: Not Installed
pycparser: Not Installed
pycrypto: 2.6.1
pycryptodome: 3.6.1
pygit2: 1.0.3
Python: 3.8.10 (default, Sep 28 2021, 16:10:42)
python-gnupg: 0.4.5
PyYAML: 5.3.1
PyZMQ: 18.1.1
smmap: 2.0.5
timelib: Not Installed
Tornado: 4.5.3
ZMQ: 4.3.2

System Versions:
dist: ubuntu 20.04 focal
locale: utf-8
machine: x86_64
release: 5.4.0-90-generic
system: Linux
version: Ubuntu 20.04 focal

```
PASTE HERE
```
</details>

**Additional context**

### PR DESCRIPTION
**Pull request by bjoernf73**
Fix for #61261

Fix so the return value for a dsc.compile_config is a 'dict', and not a list.  

### What does this PR do?
Modifies the PowerShell command, so that only the *.mof-file, and not both the *.mof and *.meta.mof, is selected in the return object ('dict'). 
 
### What issues does this PR fix or reference?
Fixes: #61261

### Previous Behavior
```python
cmd.append(
        "| Select-Object -Property FullName, Extension, Exists, "
        '@{Name="LastWriteTime";Expression={Get-Date ($_.LastWriteTime) '
        "-Format g}}"
    )
cmd = " ".join(cmd)
ret = _pshell(cmd, cwd)
if ret:
        # Script compiled, return results
        if ret.get("Exists"):
```

The `ret` variable is handled like a `dict` in the test ` if ret.get("Exists"):`. However, it may be a `list` of `dict`s, because a `dict` for all produced files from the compilation (the *.mof and it's corresponding *.meta.mof - the latter seems only to be produced on a first-time-compile for each target) is returned from the powershell command. This may produce the error below, even though the compilation succeeds: 
```
AttributeError: 'list' object has no attribute 'get'
```

### New Behavior
```python
cmd.append(
        "| Where-Object FullName -match '(?<!\.meta)\.mof$' "
        "| Select-Object -Property FullName, Extension, Exists, "
        '@{Name="LastWriteTime";Expression={Get-Date ($_.LastWriteTime) '
        "-Format g}}"
    )
cmd = " ".join(cmd)
ret = _pshell(cmd, cwd)
if ret:
        # Script compiled, return results
        if ret.get("Exists"):
```
Prepending the existing PowerShell command with `  | Where-Object FullName -match '(?<!\.meta)\.mof$' ` makes sure that only an object/dict of properties from the *.mof file - and not from the *.meta.mof-file - is returned from the call. Doing that, the variable `ret` is now a `dict`, and the test ` if ret.get("Exists"):` succeeds. 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated (test exists already)

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by MKLeb** [comment]
Hi @bjoernf73!  Would you mind adding a test for this?

**Comment by bjoernf73** [comment]
@MKLeb Actually, the test exists already, however, the test is probably not executed on a fresh windows box. 

The first time you do a dsc.compile_config on a target, you will produce a <target>.meta.mof and a <target>.mof. The existing function will fail on that task, because it returns a list of those two files. The test for this exists already, and that test will fail in this case. 

However, the second time (and third, and so on) you do dsc.compile_config for that same target, you will NOT produce a <target>.meta.mof, but only a <target.mof>. The existing function will succeed on that task, because it returns only one object, and not a list of 2 objects. The test for this exists already, and that test will succeed in this case.

My PR makes dsc.compile_config work in both the above cases. 

However, I cannot write a test that ensures that you do a first-time-compile on a fresh windows box - the test scheme should rather ensure that no other dsc-compiles have been done on the target when the test runs.

**Comment by MKLeb** [comment]
@bjoernf73 Lint and pre-commit are failing here, as well as some relevant tests if you wouldn't mind taking a look at those.  Also, I think a new test or an additional assertion in the existing test to confirm a dict is being returned would be beneficial.

**Comment by bjoernf73** [comment]
I'm sorry, @MKLeb, but it seems SaltStack isn't really trying to make the effort to get into Windows. If it were, this would be fixed long time ago. I won't be spending my time on SaltStack - I think enabling proper DSC is the only way SaltStack could ever get into the Windows market. If only developers like yourself could see the importance of this - but I don't think you do.  SaltStack is currently fiddeling in the registry, installing som packages - but this is managing windows in the 90's - SaltStack can never reach it's Windows audience without enabling DSC properly - like Ansible has. SaltStack clearly has a different vision. Good luck with the Windows-thing - it'll be needed. I'm sorry - but I don't believe it will happen. SaltStack will continue to loose markets, not because it's bad, but because of it's poor prioritization. VMWare will ultimately realize this. Good look going on

**Comment by twangboy** [comment]
Hey, @bjoernf73. I'd still love to get this in. I appreciate the work you've done on this. I'd be happy to help fix the failing pre-commit and lint tests. You may be right that we don't need additional tests. I can take a look there.

**Pull request closed without merging**
