### PR TITLE
[2019.2] Merge forward from 2018.3 (Includes move to nox)

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
Merge forward from 2018.3
Conflicts:
* doc/man/salt-api.1
* doc/man/salt-call.1
* doc/man/salt-cloud.1
* doc/man/salt-cp.1
* doc/man/salt-key.1
* doc/man/salt-master.1
* doc/man/salt-minion.1
* doc/man/salt-proxy.1
* doc/man/salt-run.1
* doc/man/salt-ssh.1
* doc/man/salt-syndic.1
* doc/man/salt-unity.1
* doc/man/salt.1
* doc/man/salt.7
* doc/man/spm.1
* salt/modules/beacons.py
* salt/modules/state.py
* tests/unit/modules/test_win_file.py

### CODE REVIEW

**Comment by s0undt3ch** [comment]
re-run full

**Comment by dwoz** [comment]
re-run all

**Comment by s0undt3ch** [comment]
Additional conflicts on additional code pulls from 2018.3:

* doc/man/salt-api.1
* doc/man/salt-call.1
* doc/man/salt-cloud.1
* doc/man/salt-cp.1
* doc/man/salt-key.1
* doc/man/salt-master.1
* doc/man/salt-minion.1
* doc/man/salt-proxy.1
* doc/man/salt-run.1
* doc/man/salt-ssh.1
* doc/man/salt-syndic.1
* doc/man/salt-unity.1
* doc/man/salt.1
* doc/man/salt.7
* doc/man/spm.1
* salt/modules/beacons.py
* salt/modules/state.py
* tests/unit/modules/test_win_file.py
---
* requirements/static/py2.7/raet-arch.txt
* requirements/static/py2.7/raet-centos-6.txt
* requirements/static/py2.7/raet-centos-7.txt
* requirements/static/py2.7/raet-debian-8.txt
* requirements/static/py2.7/raet-debian-9.txt
* requirements/static/py2.7/raet-fedora-28.txt
* requirements/static/py2.7/raet-fedora-29.txt
* requirements/static/py2.7/raet-opensuse-42.txt
* requirements/static/py2.7/raet-opensuse-leap-15.txt
* requirements/static/py2.7/raet-ubuntu-14.04.txt
* requirements/static/py2.7/raet-ubuntu-16.04.txt
* requirements/static/py2.7/raet-ubuntu-18.04.txt
* requirements/static/py2.7/raet-windows.txt
* requirements/static/py2.7/tcp-arch.txt
* requirements/static/py2.7/tcp-centos-6.txt
* requirements/static/py2.7/tcp-centos-7.txt
* requirements/static/py2.7/tcp-debian-8.txt
* requirements/static/py2.7/tcp-debian-9.txt
* requirements/static/py2.7/tcp-fedora-28.txt
* requirements/static/py2.7/tcp-fedora-29.txt
* requirements/static/py2.7/tcp-opensuse-42.txt
* requirements/static/py2.7/tcp-opensuse-leap-15.txt
* requirements/static/py2.7/tcp-ubuntu-14.04.txt
* requirements/static/py2.7/tcp-ubuntu-16.04.txt
* requirements/static/py2.7/tcp-ubuntu-18.04.txt
* requirements/static/py2.7/tcp-windows.txt
* requirements/static/py2.7/zeromq-arch.txt
* requirements/static/py2.7/zeromq-centos-6.txt
* requirements/static/py2.7/zeromq-centos-7.txt
* requirements/static/py2.7/zeromq-debian-8.txt
* requirements/static/py2.7/zeromq-debian-9.txt
* requirements/static/py2.7/zeromq-fedora-28.txt
* requirements/static/py2.7/zeromq-fedora-29.txt
* requirements/static/py2.7/zeromq-opensuse-42.txt
* requirements/static/py2.7/zeromq-opensuse-leap-15.txt
* requirements/static/py2.7/zeromq-ubuntu-14.04.txt
* requirements/static/py2.7/zeromq-ubuntu-16.04.txt
* requirements/static/py2.7/zeromq-ubuntu-18.04.txt
* requirements/static/py2.7/zeromq-windows.txt
* requirements/static/py3.4/raet-arch.txt
* requirements/static/py3.4/raet-centos-7.txt
* requirements/static/py3.4/raet-debian-8.txt
* requirements/static/py3.4/raet-debian-9.txt
* requirements/static/py3.4/raet-fedora-28.txt
* requirements/static/py3.4/raet-fedora-29.txt
* requirements/static/py3.4/raet-opensuse-42.txt
* requirements/static/py3.4/raet-opensuse-leap-15.txt
* requirements/static/py3.4/raet-ubuntu-16.04.txt
* requirements/static/py3.4/raet-ubuntu-18.04.txt
* requirements/static/py3.4/tcp-arch.txt
* requirements/static/py3.4/tcp-centos-7.txt
* requirements/static/py3.4/tcp-debian-8.txt
* requirements/static/py3.4/tcp-debian-9.txt
* requirements/static/py3.4/tcp-fedora-28.txt
* requirements/static/py3.4/tcp-fedora-29.txt
* requirements/static/py3.4/tcp-opensuse-42.txt
* requirements/static/py3.4/tcp-opensuse-leap-15.txt
* requirements/static/py3.4/tcp-ubuntu-16.04.txt
* requirements/static/py3.4/tcp-ubuntu-18.04.txt
* requirements/static/py3.4/zeromq-arch.txt
* requirements/static/py3.4/zeromq-centos-7.txt
* requirements/static/py3.4/zeromq-debian-8.txt
* requirements/static/py3.4/zeromq-debian-9.txt
* requirements/static/py3.4/zeromq-fedora-28.txt
* requirements/static/py3.4/zeromq-fedora-29.txt
* requirements/static/py3.4/zeromq-opensuse-42.txt
* requirements/static/py3.4/zeromq-opensuse-leap-15.txt
* requirements/static/py3.4/zeromq-ubuntu-16.04.txt
* requirements/static/py3.4/zeromq-ubuntu-18.04.txt
* requirements/static/py3.5/raet-arch.txt
* requirements/static/py3.5/raet-centos-7.txt
* requirements/static/py3.5/raet-debian-8.txt
* requirements/static/py3.5/raet-debian-9.txt
* requirements/static/py3.5/raet-fedora-28.txt
* requirements/static/py3.5/raet-fedora-29.txt
* requirements/static/py3.5/raet-opensuse-42.txt
* requirements/static/py3.5/raet-opensuse-leap-15.txt
* requirements/static/py3.5/raet-ubuntu-16.04.txt
* requirements/static/py3.5/raet-ubuntu-18.04.txt
* requirements/static/py3.5/raet-windows.txt
* requirements/static/py3.5/tcp-arch.txt
* requirements/static/py3.5/tcp-centos-7.txt
* requirements/static/py3.5/tcp-debian-8.txt
* requirements/static/py3.5/tcp-debian-9.txt
* requirements/static/py3.5/tcp-fedora-28.txt
* requirements/static/py3.5/tcp-fedora-29.txt
* requirements/static/py3.5/tcp-opensuse-42.txt
* requirements/static/py3.5/tcp-opensuse-leap-15.txt
* requirements/static/py3.5/tcp-ubuntu-16.04.txt
* requirements/static/py3.5/tcp-ubuntu-18.04.txt
* requirements/static/py3.5/tcp-windows.txt
* requirements/static/py3.5/zeromq-arch.txt
* requirements/static/py3.5/zeromq-centos-7.txt
* requirements/static/py3.5/zeromq-debian-8.txt
* requirements/static/py3.5/zeromq-debian-9.txt
* requirements/static/py3.5/zeromq-fedora-28.txt
* requirements/static/py3.5/zeromq-fedora-29.txt
* requirements/static/py3.5/zeromq-opensuse-42.txt
* requirements/static/py3.5/zeromq-opensuse-leap-15.txt
* requirements/static/py3.5/zeromq-ubuntu-16.04.txt
* requirements/static/py3.5/zeromq-ubuntu-18.04.txt
* requirements/static/py3.5/zeromq-windows.txt
* requirements/static/py3.6/raet-arch.txt
* requirements/static/py3.6/raet-centos-7.txt
* requirements/static/py3.6/raet-debian-8.txt
* requirements/static/py3.6/raet-debian-9.txt
* requirements/static/py3.6/raet-fedora-28.txt
* requirements/static/py3.6/raet-fedora-29.txt
* requirements/static/py3.6/raet-opensuse-42.txt
* requirements/static/py3.6/raet-opensuse-leap-15.txt
* requirements/static/py3.6/raet-ubuntu-16.04.txt
* requirements/static/py3.6/raet-ubuntu-18.04.txt
* requirements/static/py3.6/raet-windows.txt
* requirements/static/py3.6/tcp-arch.txt
* requirements/static/py3.6/tcp-centos-7.txt
* requirements/static/py3.6/tcp-debian-8.txt
* requirements/static/py3.6/tcp-debian-9.txt
* requirements/static/py3.6/tcp-fedora-28.txt
* requirements/static/py3.6/tcp-fedora-29.txt
* requirements/static/py3.6/tcp-opensuse-42.txt
* requirements/static/py3.6/tcp-opensuse-leap-15.txt
* requirements/static/py3.6/tcp-ubuntu-16.04.txt
* requirements/static/py3.6/tcp-ubuntu-18.04.txt
* requirements/static/py3.6/zeromq-arch.txt
* requirements/static/py3.6/zeromq-centos-7.txt
* requirements/static/py3.6/zeromq-debian-8.txt
* requirements/static/py3.6/zeromq-debian-9.txt
* requirements/static/py3.6/zeromq-fedora-28.txt
* requirements/static/py3.6/zeromq-fedora-29.txt
* requirements/static/py3.6/zeromq-opensuse-42.txt
* requirements/static/py3.6/zeromq-opensuse-leap-15.txt
* requirements/static/py3.6/zeromq-ubuntu-16.04.txt
* requirements/static/py3.6/zeromq-ubuntu-18.04.txt
* requirements/static/py3.6/zeromq-windows.txt
* salt/modules/cron.py
* tests/integration/modules/test_cp.py

**Comment by dwoz** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
Additional conflicts on additional code pulls from 2018.3:

* doc/Makefile

**Comment by dwoz** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by dwoz** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
Additional Conflicts:
* .ci/kitchen-centos7-py2
* .ci/kitchen-centos7-py3
* .ci/kitchen-ubuntu1604-py2
* .ci/kitchen-ubuntu1604-py3
* .ci/kitchen-windows2016-py2
* .ci/kitchen-windows2016-py3
* requirements/static/arch.in
* requirements/static/arch.txt
* requirements/static/centos-6.in
* requirements/static/centos-7.in
* requirements/static/debian-8.in
* requirements/static/debian-8.txt
* requirements/static/debian-9.in
* requirements/static/debian-9.txt
* requirements/static/fedora-28.in
* requirements/static/fedora-28.txt
* requirements/static/fedora-29.in
* requirements/static/fedora-29.txt
* requirements/static/opensuse-42.in
* requirements/static/opensuse-42.txt
* requirements/static/opensuse-leap-15.in
* requirements/static/opensuse-leap-15.txt
* requirements/static/osx.in
* requirements/static/py2.7/raet-arch.txt
* requirements/static/py2.7/raet-centos-6.txt
* requirements/static/py2.7/raet-centos-7.txt
* requirements/static/py2.7/raet-debian-8.txt
* requirements/static/py2.7/raet-debian-9.txt
* requirements/static/py2.7/raet-fedora-28.txt
* requirements/static/py2.7/raet-fedora-29.txt
* requirements/static/py2.7/raet-opensuse-42.txt
* requirements/static/py2.7/raet-opensuse-leap-15.txt
* requirements/static/py2.7/raet-ubuntu-16.04.txt
* requirements/static/py2.7/raet-ubuntu-18.04.txt
* requirements/static/py2.7/raet-windows.txt
* requirements/static/py2.7/tcp-arch.txt
* requirements/static/py2.7/tcp-centos-6.txt
* requirements/static/py2.7/tcp-centos-7.txt
* requirements/static/py2.7/tcp-debian-8.txt
* requirements/static/py2.7/tcp-debian-9.txt
* requirements/static/py2.7/tcp-fedora-28.txt
* requirements/static/py2.7/tcp-fedora-29.txt
* requirements/static/py2.7/tcp-opensuse-42.txt
* requirements/static/py2.7/tcp-opensuse-leap-15.txt
* requirements/static/py2.7/tcp-ubuntu-14.04.txt
* requirements/static/py2.7/tcp-ubuntu-16.04.txt
* requirements/static/py2.7/tcp-ubuntu-18.04.txt
* requirements/static/py2.7/tcp-windows.txt
* requirements/static/py2.7/zeromq-arch.txt
* requirements/static/py2.7/zeromq-centos-6.txt
* requirements/static/py2.7/zeromq-centos-7.txt
* requirements/static/py2.7/zeromq-debian-8.txt
* requirements/static/py2.7/zeromq-debian-9.txt
* requirements/static/py2.7/zeromq-fedora-28.txt
* requirements/static/py2.7/zeromq-fedora-29.txt
* requirements/static/py2.7/zeromq-opensuse-42.txt
* requirements/static/py2.7/zeromq-opensuse-leap-15.txt
* requirements/static/py2.7/zeromq-ubuntu-16.04.txt
* requirements/static/py2.7/zeromq-ubuntu-18.04.txt
* requirements/static/py2.7/zeromq-windows.txt
* requirements/static/py3.4/raet-arch.txt
* requirements/static/py3.4/raet-centos-7.txt
* requirements/static/py3.4/raet-debian-8.txt
* requirements/static/py3.4/raet-debian-9.txt
* requirements/static/py3.4/raet-fedora-28.txt
* requirements/static/py3.4/raet-fedora-29.txt
* requirements/static/py3.4/raet-opensuse-42.txt
* requirements/static/py3.4/raet-opensuse-leap-15.txt
* requirements/static/py3.4/raet-ubuntu-16.04.txt
* requirements/static/py3.4/raet-ubuntu-18.04.txt
* requirements/static/py3.4/tcp-arch.txt
* requirements/static/py3.4/tcp-centos-7.txt
* requirements/static/py3.4/tcp-debian-8.txt
* requirements/static/py3.4/tcp-debian-9.txt
* requirements/static/py3.4/tcp-fedora-28.txt
* requirements/static/py3.4/tcp-fedora-29.txt
* requirements/static/py3.4/tcp-opensuse-42.txt
* requirements/static/py3.4/tcp-opensuse-leap-15.txt
* requirements/static/py3.4/tcp-ubuntu-16.04.txt
* requirements/static/py3.4/tcp-ubuntu-18.04.txt
* requirements/static/py3.4/zeromq-arch.txt
* requirements/static/py3.4/zeromq-centos-7.txt
* requirements/static/py3.4/zeromq-debian-8.txt
* requirements/static/py3.4/zeromq-debian-9.txt
* requirements/static/py3.4/zeromq-fedora-28.txt
* requirements/static/py3.4/zeromq-fedora-29.txt
* requirements/static/py3.4/zeromq-opensuse-42.txt
* requirements/static/py3.4/zeromq-opensuse-leap-15.txt
* requirements/static/py3.4/zeromq-ubuntu-16.04.txt
* requirements/static/py3.4/zeromq-ubuntu-18.04.txt
* requirements/static/py3.5/raet-arch.txt
* requirements/static/py3.5/raet-centos-7.txt
* requirements/static/py3.5/raet-debian-8.txt
* requirements/static/py3.5/raet-debian-9.txt
* requirements/static/py3.5/raet-fedora-28.txt
* requirements/static/py3.5/raet-fedora-29.txt
* requirements/static/py3.5/raet-opensuse-42.txt
* requirements/static/py3.5/raet-opensuse-leap-15.txt
* requirements/static/py3.5/raet-ubuntu-16.04.txt
* requirements/static/py3.5/raet-ubuntu-18.04.txt
* requirements/static/py3.5/raet-windows.txt
* requirements/static/py3.5/tcp-arch.txt
* requirements/static/py3.5/tcp-centos-7.txt
* requirements/static/py3.5/tcp-debian-8.txt
* requirements/static/py3.5/tcp-debian-9.txt
* requirements/static/py3.5/tcp-fedora-28.txt
* requirements/static/py3.5/tcp-fedora-29.txt
* requirements/static/py3.5/tcp-opensuse-42.txt
* requirements/static/py3.5/tcp-opensuse-leap-15.txt
* requirements/static/py3.5/tcp-ubuntu-16.04.txt
* requirements/static/py3.5/tcp-ubuntu-18.04.txt
* requirements/static/py3.5/tcp-windows.txt
* requirements/static/py3.5/zeromq-arch.txt
* requirements/static/py3.5/zeromq-centos-7.txt
* requirements/static/py3.5/zeromq-debian-8.txt
* requirements/static/py3.5/zeromq-debian-9.txt
* requirements/static/py3.5/zeromq-fedora-28.txt
* requirements/static/py3.5/zeromq-fedora-29.txt
* requirements/static/py3.5/zeromq-opensuse-42.txt
* requirements/static/py3.5/zeromq-opensuse-leap-15.txt
* requirements/static/py3.5/zeromq-ubuntu-16.04.txt
* requirements/static/py3.5/zeromq-ubuntu-18.04.txt
* requirements/static/py3.5/zeromq-windows.txt
* requirements/static/py3.6/raet-arch.txt
* requirements/static/py3.6/raet-centos-7.txt
* requirements/static/py3.6/raet-debian-8.txt
* requirements/static/py3.6/raet-debian-9.txt
* requirements/static/py3.6/raet-fedora-28.txt
* requirements/static/py3.6/raet-fedora-29.txt
* requirements/static/py3.6/raet-opensuse-42.txt
* requirements/static/py3.6/raet-opensuse-leap-15.txt
* requirements/static/py3.6/raet-ubuntu-16.04.txt
* requirements/static/py3.6/raet-ubuntu-18.04.txt
* requirements/static/py3.6/raet-windows.txt
* requirements/static/py3.6/tcp-arch.txt
* requirements/static/py3.6/tcp-centos-7.txt
* requirements/static/py3.6/tcp-debian-8.txt
* requirements/static/py3.6/tcp-debian-9.txt
* requirements/static/py3.6/tcp-fedora-28.txt
* requirements/static/py3.6/tcp-fedora-29.txt
* requirements/static/py3.6/tcp-opensuse-42.txt
* requirements/static/py3.6/tcp-opensuse-leap-15.txt
* requirements/static/py3.6/tcp-ubuntu-16.04.txt
* requirements/static/py3.6/tcp-ubuntu-18.04.txt
* requirements/static/py3.6/zeromq-arch.txt
* requirements/static/py3.6/zeromq-centos-7.txt
* requirements/static/py3.6/zeromq-debian-8.txt
* requirements/static/py3.6/zeromq-debian-9.txt
* requirements/static/py3.6/zeromq-fedora-28.txt
* requirements/static/py3.6/zeromq-fedora-29.txt
* requirements/static/py3.6/zeromq-opensuse-42.txt
* requirements/static/py3.6/zeromq-opensuse-leap-15.txt
* requirements/static/py3.6/zeromq-ubuntu-16.04.txt
* requirements/static/py3.6/zeromq-ubuntu-18.04.txt
* requirements/static/py3.6/zeromq-windows.txt
* requirements/static/ubuntu-14.04.txt
* requirements/static/ubuntu-16.04.in
* requirements/static/ubuntu-16.04.txt
* requirements/static/ubuntu-18.04.in
* requirements/static/windows.in
* salt/states/pip_state.py
* tests/integration/__init__.py
* tests/integration/files/log_handlers/runtests_log_handler.py
* tests/integration/modules/test_cp.py
* tests/integration/modules/test_pip.py
* tests/integration/states/test_pip_state.py
* tests/support/generate-names-file-from-failed-test-reports.py
* tests/support/gitfs.py

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run all

**Review by twangboy — APPROVED** [review]

**Comment by s0undt3ch** [comment]
re-run all

**Comment by waynew** [comment]
#53188 fixes #52079, if you can bring that along, too.

**Comment by s0undt3ch** [comment]
I will pull in the latest 2028.3 changes

**Comment by s0undt3ch** [comment]
re-run full all

**Review by Akm0d — APPROVED** [review]

**Comment by s0undt3ch** [comment]
Done from scratch again in https://github.com/saltstack/salt/pull/53701

**Pull request closed without merging**
