### PR TITLE
[master] Porting #50428 to master

### PR DESCRIPTION
**Pull request by garethgreenaway**
Porting #50428 to master

### CODE REVIEW

**Comment by waynew** [comment]
We should probably go ahead and combine #53866 with this.

**Comment by s0undt3ch** [comment]
PR is updated/ Requirements have been compiled.

**Review by s0undt3ch — APPROVED** [review]

**Comment by max-arnold** [comment]
@s0undt3ch I combined this PR with the follow-up https://github.com/saltstack/salt/pull/53866 and submitted the result as a new PR (coz I can't edit this one).

All tests (except the unrelated unicode sls on Windows) are green, so it is potentially ready for merge: https://github.com/saltstack/salt/pull/55749

The only thing missing is that I don't know how to regenerate all the static requirements files. However, I added the `jmespath` dependency to the corresponding `*.in` files and the static ones already have it.

**Comment by s0undt3ch** [comment]
Superseded by https://github.com/saltstack/salt/pull/55749

**Pull request closed without merging**
