### PR TITLE
Add `moto` to the windows dependencies

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title.

### CODE REVIEW

**Review by dwoz — APPROVED** [review]

**Comment by dwoz** [comment]
re-run windows

**Comment by dwoz** [comment]
re-run windows2016-py2
re-run centos7-py3

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
This PR is now also backporting(forgot I had an open PR using this branch) https://github.com/saltstack/salt/pull/52797 and https://github.com/saltstack/salt/pull/52842

**Review by twangboy — APPROVED** [review]

**Comment by s0undt3ch** [comment]
Finally!!!

**Pull request merged**
