### PR TITLE
Transport leak [RFC]

### PR DESCRIPTION
**Pull request by cachedout**
This corrects a serious memory leak in the salt-minion, whereby memory is leaked on every return.

To illustrate the issue:

``` python
#!/usr/bin/python2

import salt.config
import salt.minion

from pympler import tracker, asizeof, refbrowser

tracker = tracker.SummaryTracker()

opts = salt.config.minion_config('/etc/salt/minion')
opts['master_uri'] = 'tcp://localhost:4506'
minion = salt.minion.Minion(opts)

for x in range(0, 100):
    minion._return_pub({'ret': True})
    tracker.print_diff()
    print(asizeof.asizeof(minion))
```

One will see that memory is clearly being allocated which is not released. The same results can be observed by tracking the memory usage of a running minion as returns are sent to the master.

This patch addresses the problem in two ways.

First, it removes the future from the future map after it's been successfully sent. This is likely a minor problem and does not appear to be the main cause of the leak, in my testing.

Of more concern is the second fix, which removes the `__del__` and instead requires that the consumer of the class do cleanup manually by calling the `destroy()` method. The reason appears to be that having the two `__del__` has created a reference cycle in which the Python garbage collector does not know in which order to clean up the instances which are bound to each other. While this does mean that `destroy()` will need to be called manually for consumers of the internal sending class in the ZMQ transport, this shouldn't much of an issue since it really isn't "public facing", per-se. :]

@jacksontj Would you mind having a look and telling me what you think before we merge this? You have have had a good reason for not cleaning up the future map, because I found that curious so I'd like very much to get your feedback. Thanks!

### CODE REVIEW

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Was the futures map previously a weakref which got replaced by a regular dict? That could explain the missing cleanup...

**Comment by jacksontj** [comment]
Possibly, I'll take a deeper look tomorrow morning. The pop is definitely
needed, but in general having to explicitly call the destructor is a
recipient for disaster (as someone else using the object will forget). The
repro case seems simple enough, so I can hopefully get an idea of why its
not cleaning up on its own.

**Comment by cachedout** [comment]
Yes, I am not a fan of having to explicitly call the destructor either. If there is a better way to provide hints to the GC with a reference cycle like the one we have currently, that would potentially be a lot better than this explicit approach.

**Comment by s0undt3ch** [comment]
You know which references are making GC indecisive? Ie, have you debugged that far?

**Comment by cachedout** [comment]
@s0undt3ch Yes. It's the reference between the `AsyncReqChannel `and the `AsyncReqMessageClient`.

**Comment by jacksontj** [comment]
From my testing, I don't see a leak of the messageclient. The future_map is definitely a problem (i submitted a slightly nicer PR-- single pop instead of get and pop).

The leaking you might be seeing might be because you aren't forcing a gc before printing diff-- so if not enough objects have been created the garbage collector won't bother. To better detect a leak:


```
import salt.config
import salt.minion

import gc
from pympler import tracker, asizeof, refbrowser

tracker = tracker.SummaryTracker()

opts = salt.config.minion_config('/etc/salt/minion')
opts['master_uri'] = 'tcp://localhost:4506'
minion = salt.minion.Minion(opts)

for x in range(0, 100):
    minion._return_pub({'ret': True})
    if x % 10 == 0:
        gc.collect()  # force a collect before we print a diff
        tracker.print_diff()
        print(asizeof.asizeof(minion))
```

With my testing (with the one pop() patch) I don't see anymore leaks.

**Pull request closed without merging**
