### PR TITLE
Deprecated Boron warnings in cron state.

### PR DESCRIPTION
**Pull request by abednarik**
Hope I can help with this heavy tasks :)

### CODE REVIEW

**Comment by rallytime** [comment]
@jtand FYI

**Comment by jtand** [comment]
@abednarik Excellent, thank you! I'm going to backport this and #30988 into 2016.3. Thanks for your help!

**Comment by cachedout** [comment]
Thanks, @abednarik

**Comment by abednarik** [comment]
@jtand thanks. Next time i will make this kind of PR against 2016.3. Is all about to learn  :)

**Pull request merged**
