### PR TITLE
Allow nacl survive on errors, implements salt.nacl.dec_safe [WIP]

### PR DESCRIPTION
**Pull request by epcim**
### What does this PR do?
Note as #41833 now fixes usage of None as input. This PR was updated to only contain test's for NACL.
I will rebase once #41833 is merged.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/42003

### Tests written?
Yes

### Test depends on
#41833

### CODE REVIEW

**Comment by epcim** [comment]
locally can be tested with: 
```./tests/runtests.py -v -n unit.modules.test_nacl.NaclModuleTestCase
```

**Comment by steverweber** [comment]
so basicly...
```
def dec_safe(data, **kwargs):
    try:
        return dec(data, **kwargs)
    except Exception as ex:
        pass
    return data
    # note: would rather return None.
```
Personally I don't want people to unknowingly put their system in an unpredictable state.
I feel the error is good.

perhaps you should wrap the module call using a `test.try`.
I added this function a while back for cases where a silent error is acceptable.
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.test.html#salt.modules.test.try_
```
salt.test.try.(module='nacl.dec',...)
```

**Comment by epcim** [comment]
[**@steverweber**](https://github.com/steverweber) commented on [Jun 29, 2017, 4:49 PM GMT+2](https://github.com/saltstack/salt/pull/42012#issuecomment-311990539 "2017-06-29T14:49:52Z - Replied by Github Reply Comments"):
> so basicly...
> 
>     def dec_safe(data, **kwargs):
>         try:
>             return dec(data, **kwargs)
>         except Exception as ex:
>             pass
>         return data
>         # note: would rather return None.
> 
> Personally I don't want people to unknowingly put their system in an unpredictable state.  
> 
> I feel the error is good.
> 
> perhaps you should wrap the module call using a `test.try`.  
> 
> I added this function a while back for cases where a silent error is acceptable.  
> 
> [https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.test.html#salt.modules.test.try](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.test.html#salt.modules.test.try)_
> 
>     salt.test.try.(module='nacl.dec',...)

I will probably stay with None, as the purpose was mainly to be able to `|default(xyz)`.
However if similar code will be used in jinja filter it's required to return input (will be in different file).

And mostly with https://github.com/saltstack/salt/pull/41833, https://github.com/saltstack/salt/pull/41868 + https://github.com/yagnik/salt/pull/1 I will be able to transparently decrypt values on pillar. So no kind of falback to cleartext ( if input is cleartext ) will be required.

**Comment by epcim** [comment]
[**@steverweber**](https://github.com/steverweber) commented on [Jun 29, 2017, 4:49 PM GMT+2](https://github.com/saltstack/salt/pull/42012#issuecomment-311990539 "2017-06-29T14:49:52Z - Replied by Github Reply Comments"):
> so basicly...
> 
>     def dec_safe(data, **kwargs):
>         try:
>             return dec(data, **kwargs)
>         except Exception as ex:
>             pass
>         return data
>         # note: would rather return None.
> 
> Personally I don't want people to unknowingly put their system in an unpredictable state.  
> 
> I feel the error is good.
> 
> perhaps you should wrap the module call using a `test.try`.  
> 
> I added this function a while back for cases where a silent error is acceptable.  
> 
> [https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.test.html#salt.modules.test.try](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.test.html#salt.modules.test.try)_
> 
>     salt.test.try.(module='nacl.dec',...)

I actually need help to implement properly a test in a `tests/unit/modules/test_nacl.py` to avoid `KeyError: 'config.get'`, imho `salt.test.try` will not help me sort out that configuration issue.

**Comment by steverweber** [comment]
>  imho salt.test.try will not help me sort out that configuration issue.

I was not suggesting to use `salt.test.try` to bypass the issue in the test code.
I'm suggesting to use it instead of `dec_safe`

https://github.com/saltstack/salt/pull/41833
latest version of nacl has some safety around `config.get` so test code might work.

**Comment by epcim** [comment]
closing in favor of https://github.com/steverweber/salt/pull/1

**Pull request closed without merging**
