### PR TITLE
Added the ability to delete a VPC by name and tags

### LINKED ISSUE #20621: The Boto VPC module does not support deleting by name or tags
See https://github.com/saltstack/salt/blob/develop/salt/modules/boto_vpc.py#L260

### PR DESCRIPTION
**Pull request by thedrow**
Fixes #20621
I'd be happy if someone else can contribute a test for it.
Otherwise it will have to wait for a few days.

### CODE REVIEW

**Comment by jfindlay** [comment]
@thedrow, there's a [lint error](https://jenkins.saltstack.com/job/salt-pr-lint-n/1877/violations/file/salt/modules/boto_vpc.py).

**Comment by rallytime** [comment]
@thedrow I grabbed the pylint error in the PR above. Your PR will be merged in when mine gets merged in. :)

Thanks for this addition! Looks great!

**Comment by thedrow** [comment]
@rallytime This needs a unit test. Would you mind adding it?

**Comment by rallytime** [comment]
Sure thing! I've added the "needs testcase" label to remind us to circle back around to this one. However, if you feel inclined and beat me to it, go for it!

**Pull request merged**
