### PR TITLE
Migrate ZeroMQ and TCP transport unit tests to PyTest

### LINKED ISSUE #32902: OpenSUSE hangs on ZeroMQ test on 2016.3
### Description of Issue/Question

Running the test suite causes opensuse to hang on `unit.transport.zeromq_test.AESReqTestCases.test_normalization`. This only happens the 2016.3 branch on opensuse.
### Setup

Need an opensuse VM with salt installed and a salt checkout. 
### Steps to Reproduce Issue

python tests/runtests.py -v -n unit.transport.zeromq_test
### Versions Report

``` yaml
salt --versions-report
Salt Version:
           Salt: 2015.8.8.2

Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.22
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.0.0
         Python: 2.7.8 (default, Sep 30 2014, 15:34:38) [GCC]
           RAET: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
           cffi: Not Installed
       cherrypy: 3.3.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.1
          ioflo: 1.5.1
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.0
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: 0.3.8
          smmap: 0.9.0
        timelib: 0.2.4

System Versions:
           dist: SuSE 13.2 x86_64
        machine: x86_64
        release: 4.5.0-x86_64-linode65
         system: openSUSE  13.2 x86_64
```

@meggiebot @s0undt3ch

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title

### Fixes
Fixes #32902

### CODE REVIEW

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Review by krionbsd — DISMISSED** [review]

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Review by krionbsd — DISMISSED** [review]

**Pull request merged**
