### PR TITLE
docker_image: Fix missing exc in except, pass proper args to docker.build

### PR DESCRIPTION
**Pull request by terminalmage**

### CODE REVIEW

**Review by rallytime — APPROVED** [review]

**Comment by terminalmage** [comment]
@rallytime can you re-review? I pushed more fixes, for the pillarenv stuff.

**Comment by terminalmage** [comment]
I should also add some integration tests for image building.

**Comment by terminalmage** [comment]
@rallytime let's hold off on merging until after @brianthelion has had a chance to test.

**Comment by brianthelion** [comment]
@terminalmage Looks like `pillarenv_from_saltenv` still isn't being respected. I'll dig in a little more now and try to verify.

**Comment by brianthelion** [comment]
Yeah @terminalmage , unless I am misunderstanding, it looks like the pillar is getting pushed to `_prepare_trans_tar` but not `_compile_state`, which is where the low data is getting generated.

**Comment by terminalmage** [comment]
@brianthelion Thanks for catching it, I believe I have that fixed now. I rebased to bring it up to date with the head of the `oxygen` release branch, so if you checked out the PR locally you may need to destroy the branch you used and re-fetch.

**Comment by brianthelion** [comment]
@terminalmage Awesome! I'll have some time to test tomorrow after lunch.

**Comment by terminalmage** [comment]
I've just pushed some more commits, but they're to address PY3 test failures. @brianthelion let me know if you get a chance to test on Tuesday.

**Review by rallytime — APPROVED** [review]

**Comment by brianthelion** [comment]
@terminalmage Sorry, I am just sitting down to review and test. I should have a go/no-go for you in a couple hours.

**Comment by terminalmage** [comment]
@brianthelion no problem! I've been trickling in some docker (and other) PY3 compatibility fixes to this PR, but the issue as you reported should (I think) be resolved. Thanks for your help!

**Comment by brianthelion** [comment]
So far, so good. Couple more things to check....

**Comment by brianthelion** [comment]
@terminalmage Nothing definitive yet, but it looks like I'm seeing some failures on states that use `contents_pillar: ....` inside the docker container. Any thoughts on that? I'll try to config the issue and get a minimal test case up.

**Comment by terminalmage** [comment]
@brianthelion I can't think of a reason those should fail. Is `pillarenv_from_saltenv` working as expected now, aside from `contents_pillar`? If so, I'd like to get this PR merged since it includes a bunch of PY3 test fixes that will help us stabilize the test suite a bit. Then we can tackle the `contents_pillar` issue in a separate bug report. Does that sound OK?

**Comment by terminalmage** [comment]
Also, if you want to work more directly with me on this and haven't joined our community Slack yet, you can request an invite here: http://saltstackcommunity.herokuapp.com/

**Comment by brianthelion** [comment]
@terminalmage Yeah, I *think* we're in good shape. With this pushed, I'll be upgrading some of my production code. If I hit any problems in so-doing I'll circle back with you. Thanks!

PS - I'd be psyched to join the Saltstack community as long as the XMPP integrations for Slack are turned on so I can connect through emacs. :-)

**Comment by terminalmage** [comment]
@brianthelion OK awesome, we'll get this merged once tests finish and I'll let you know once merged.

The XMPP gateway is enabled, so go for it! I'm the same username there as here.

**Comment by brianthelion** [comment]
@terminalmage I found an issue on the PR after all. Give me sec here....

**Comment by brianthelion** [comment]
```diff
diff --git a/salt/client/ssh/state.py b/salt/client/ssh/state.py
index 40eb4fd2e3..3ff53c2168 100644
--- a/salt/client/ssh/state.py
+++ b/salt/client/ssh/state.py
@@ -207,6 +207,8 @@ def prep_trans_tar(opts, file_client, chunks, file_refs, pillar=None, id_=None,
         for ref in file_refs[saltenv]:
             for name in ref:
                 short = salt.utils.url.parse(name)[0]
+                if short.startswith('/'):
+                    short = short[1:]
                 cache_dest = os.path.join(cache_dest_root, short)
                 try:
                     path = file_client.cache_file(name, saltenv, cachedir=cachedir)
```

For some reason, `short` is coming back with a leading "/", which in turn is [clobbering](https://docs.python.org/3/library/os.path.html#os.path.join) the other args in subsequent `os.path.join(...)` calls.

**Comment by rallytime** [comment]
After speaking with @terminalmage about this PR in another channel, he informed that this PR is ready to go as it stands and that the issue stated above will be handled in a different PR after more investigation is done.

Thanks for testing and for your feedback @brianthelion!

**Pull request merged**
