### PR TITLE
Adds a get_route() function to win_network.py

### PR DESCRIPTION
**Pull request by lorengordon**
Returns the same data as the get_route() function in the network.py
execution module.

### CODE REVIEW

**Comment by lorengordon** [comment]
For example:

```
~\Documents\GitHub\salt [win.get_route +0 ~1 -0 !]> salt-call --local network.get_route 192.0.0.8
local:
    ----------
    destination:
        192.0.0.8
    gateway:
        10.1.10.1
    interface:
        Wi-Fi
    source:
        10.1.10.217
```

**Comment by rallytime** [comment]
Hi @lorengordon - it looks like there is a related lint error here: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/10984/violations/file/salt/modules/win_network.py/

Do you mind fixing that up?

**Comment by lorengordon** [comment]
@rallytime Done, thanks! I also added a test.

**Comment by rallytime** [comment]
@lorengordon Wonderful! Thank you.

**Pull request merged**
