### PR TITLE
add boto dynamodb salt module and state

### PR DESCRIPTION
**Pull request by mdemmitt-lyft**

### CODE REVIEW

**Comment by thatch45** [comment]
Thanks @mdemmitt-lyft !!

**Comment by thedrow** [comment]
@thatch45 Please don't merge boto modules and states without tests or a commitment to write them from someone.
These modules will be used by salt-cloud which is sensitive.

**Comment by techhat** [comment]
@thedrow, salt-cloud does not currently use boto.

**Comment by thedrow** [comment]
I wrote that "These modules **will** be used by salt-cloud which is sensitive."
@Ryan-Lane opened an issue about it some time ago.

**Comment by ryan-lane** [comment]
@thedrow We don't plan on adding full testing to all of the boto modules. We definitely will be adding tests to critical modules (secgroup, elb, route53). It would be nice to not block module addition for lack of tests, though. We're using these internally, so they're at least being tested in production ;).

**Comment by thatch45** [comment]
SaltStack has a commitment to add more tests for all modules we accept and are working hard to do so, we have added unit tests for many modules in just the last few weeks and our test additions greatly outpace our module additions

**Comment by thedrow** [comment]
@ryan-lane I don't think it's reasonable to merge an incomplete PR unless someone else commits to complete it.
All modules are critical. A mistake or a bug in any of them can cause a company to give up on salt at best or even cause an outage which is something we really don't want.
When databases are involved it's even more sensitive.
@thatch45 I know that some modules has some unit tests and that's being worked on but new features are being added without them. Are you saying that before the next salt release all modules will have full test coverage?
Not to mention that salt still doesn't have an acceptance suite that checks all boto modules against a real AWS account.
If I or any other user is going to use salt for these kind of operations I need to trust it. That's precisely why I wrote tests when I wrote the VPC module.

**Comment by ryan-lane** [comment]
You can only create and destroy tables for DynamoDB. The worst you can mess
up is to fail to create indexes. There's no risk of data-loss here, so
though it can cause some bad feelings towards the modules, it isn't so
dangerous that people would give up on salt (they'd likely open an issue).

We will be putting efforts into adding tests to the boto modules later, but
we have other work that's taking priority over that now. We upstream the
modules when they're done because we believe people will find them useful
with or without tests.

Something to remember is that we're volunteer contributors and not
SaltStack employees.

**Pull request merged**
