### PR TITLE
script engine

### PR DESCRIPTION
**Pull request by austinpapp**
### What does this PR do?
Creates events based on an arbitrary script's stdout. 

The script engine will scrap stdout of the given script and generate an event based on the presence of the 'tag' key and it's value.

If there is a data obj available, that will also be fired along with the tag.

Example:

Given the following json output from a script's stdout:

```
            { "tag" : "lots/of/tacos",
              "data" : { "toppings" : "cilantro" }
            }
```

This will fire the event on the event bus:
```
{"tag": "lots/of/tacos", "data": {"toppings": "cilantro"}}
```

Any available serializer to salt can be specified to deserialized stdout such as yaml, json. 

### What issues does this PR fix or reference?
n/a

### Tests written?

Yes

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by garethgreenaway** [comment]
@austinpapp This looks cool!  Nicely done.  Looks like one of your tests is failing though.

**Comment by austinpapp** [comment]
@garethgreenaway will take a look. thanks. :)

**Comment by cachedout** [comment]
I have wanted to see this functionality for a while so this is awesome. One thought, though, is that this engine's name really isn't very intuitive. Is `script_events` or something better? I'm not sure. Thoughts?

**Comment by austinpapp** [comment]
@cachedout thanks! wrt the naming, yea i thought about that but essentially all engines generate events. seemed redundant to add event to the name. however, im not closely tied to any particular name so if you feel its a better choice, sounds good :)

**Review by garethgreenaway — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
