### PR TITLE
Refactor rabbitmq_user state to use test=True correctly

### PR DESCRIPTION
**Pull request by rallytime**
Refs #24856 and #25363

### CODE REVIEW

**Comment by rallytime** [comment]
@terminalmage Could you review this change when you get a moment? This is similar to the one we discussed the other day (changing a state to be more stateful and utilizing test=True functionality correctly), just with a different state file.

**Comment by cachedout** [comment]
Assigned @terminalmage for review per @rallytime

**Comment by rallytime** [comment]
I'm updating the tests now. They were written against the state looking for changes in the comments dictionary as the original state was written.

**Comment by terminalmage** [comment]
Looks good!

**Comment by rallytime** [comment]
@mbarrien I can't remember exactly why that was needed as this change was a little while ago, but it has to do with the output of the `list_user_permissions` that is used further down in the state. Can you please file a new issue and tag me in it? Please include the output of `salt --versions-report` as well as the state you're using to trigger this error. Also, do you master and minion versions match? If not, please also include the output of `salt <minion> test.versions_report`.

**Comment by mbarrien** [comment]
I can get you this info tomorrow, but I can say that I'm using salt-ssh, so there's no chance of master and minion version mismatch (and salt-ssh vs traditional salt shouldn't affect this.)  I can say that in a local fork where I stripped out the [0], things started working, and that the code https://github.com/saltstack/salt/blob/develop/salt/modules/rabbitmq.py#L381 shows that `list_user_permissions` returns a dict, so a [0] is almost definitely not correct.

I was working with the HEAD of 2015.8 as of this afternoon, because other bugs were stopping me from using 2015.8.1 (and I know the code was right at HEAD, since I had to ensure my unrelated changes from my code were being pushed to the salt-ssh "minion", and I logged into the minion to look at the tmp directory to ensure my code was pushed there). (Unrelated code was related to the pip state, nothing to do with rabbit.)

**Comment by rallytime** [comment]
@mbarrien No problem. I'll take another look today and see if I can remember why I thought that list index should be there, when clearly `list_user_permissions` returns a dictionary.

**Comment by rallytime** [comment]
@mbarrien Thanks for catching this. I added the `[0]` because there was a bug where the test suite that the original refactor PR was expecting a list to be returned from `rabbitmq.list_user_permissions`. I've adjust fixed this in #28772. Can you try that out and let me know how it goes?

**Pull request merged**
