### PR TITLE
doc: Exclude documentation_options.js from default theme

### PR DESCRIPTION
**Pull request by bdrung**
`documentation_options.js` from the default theme sets the option `URL_ROOT` to:

```
document.getElementById("documentation_options").getAttribute('data-url_root')
```

This requires that the script element for `documentation_options.js` includes the tag `id="documentation_options"` and sets the
`data-url_root` tag. Otherwise evaluating `URL_ROOT` will fail and building the documentation during the Debian package build will fail:

```
dh_sphinxdoc: error: DOCUMENTATION_OPTIONS does not define URL_ROOT
```

The variable `DOCUMENTATION_OPTIONS` is directly set `layout.html` and  therefore `documentation_options.js` does not need to be included. So just exclude it.

### CODE REVIEW

**Comment by bdrung** [comment]
Rebased on master.

**Comment by Ch3LL** [comment]
@barbaricyawps can you review here please

**Comment by barbaricyawps** [comment]
I think this PR might be out of date and that this unnecessary option was already removed. I'm looking at the file that was changed in this PR (doc > _themes > saltstack > layout.html) and I don't see this line in the file:

```
{# Remove old version of jQuery #}
{% set js_blacklist = [
    '_static/jquery.js',
] %}
```

I think this PR is stale and I recommend closing. Can you double-check that my assessment is correct, @garethgreenaway ? Then we can close this out.

**Review by barbaricyawps — COMMENTED** [review]
Recommend closing this PR as the fix appears to have been merged in by someone else, possibly later.

**Review by barbaricyawps — CHANGES_REQUESTED** [review]
@bdrung , I'm afraid I don't understand enough about javascript to understand why this PR is necessary and your description doesn't seem to help me. One thing that I'm confused about is why you're adding a reference to a file named ` _static/documentation_options.js` when this file doesn't exist in the root folder being referenced.

What does setting the js_blacklist do?

**Comment by bdrung** [comment]
js_blacklist is used in layout.html:
```js
    {% if scriptfile not in js_blacklist %}
    <script type="text/javascript" src="{{ pathto(scriptfile, 1) }}"></script>
    {% endif %}
```

`_static/documentation_options.js` is generated by sphinx, but this file is not needed since `layout.html` specifies everything needed itself:
```js
    <script>
        var DOCUMENTATION_OPTIONS = {
            URL_ROOT:    '{{ url_root }}',
            VERSION:     '{{ release|e }}',
            LANGUAGE: '{{ language }}',
            COLLAPSE_INDEX: false,
            BUILDER: '{{ builder }}',
            FILE_SUFFIX: '{{ '' if no_search_suffix else file_suffix }}',
            LINK_SUFFIX: '{{ link_suffix }}',
            HAS_SOURCE: {{ has_source|lower }},
            SOURCELINK_SUFFIX: '{{ sourcelink_suffix }}',
            NAVIGATION_WITH_KEYS: {{ 'true' if theme_navigation_with_keys|tobool else 'false'}}
        };
    </script>
```

**Comment by MKLeb** [comment]
@bdrung Would you be able to provide an example of this causing the failure you described?  Logs, screenshots, whatever works.

**Review by twangboy — APPROVED** [review]

**Comment by Ch3LL** [comment]
@bdrung can you answer @MKLeb 's question. Would like to progress this issue.

**Pull request merged**
