### PR TITLE
writing unit test cases for cassandra module

### PR DESCRIPTION
**Pull request by rupeshta**
writing unit test cases for cassandra module

### CODE REVIEW

**Comment by jfindlay** [comment]
@rupeshta, it seems that the pylint error can be avoided by removing the try, except import block since you're not using HAS_PYCASSA.

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
@rupeshta, I have fixed these unit tests in [another pull request](https://github.com/saltstack/salt/pull/19817).  For unit tests it is not necessary to mock a cassandra connection, rather the code can be mocked immediately without the function being tested.  I have done this by mocking the _sys_mgr function and SystemManager object rather than depending on pycassa in order to unit test cassandra.py.

**Pull request merged**
