### PR TITLE
We can't query installed use flags for a non installed pkg

### PR DESCRIPTION
**Pull request by RealKelsar**
Same as in the develop branch, you can't query installed information on a non installed package.

Brakes install of new packages.

### CODE REVIEW

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by RealKelsar** [comment]
Uh, one "if" to much... who do i add the corrected commit?

**Comment by rallytime** [comment]
@RealKelsar You just push the commit up to your local branch that this pull request was made from, and GitHub will pick it up and apply it here. It looks to me like you already figured that out, though. :)

Is this ready to go?

**Comment by RealKelsar** [comment]
Yes, figured it out. I am using this variant allready, should be fine.

**Pull request merged**
