### PR TITLE
don't pass jid to list_jobs

### LINKED ISSUE #41100: Exception occurred in runner jobs.list_jobs
### Description of Issue/Question
I see this in 2016.11.5
```
- "Exception occurred in runner jobs.list_jobs: Traceback (most recent call last):\n\
  \  File \"/usr/lib/python2.7/site-packages/salt/client/mixins.py\", line 395, in\
  \ _low\n    data['return'] = self.functions[fun](*args, **kwargs)\nTypeError: list_jobs()\
  \ got an unexpected keyword argument 'jid'\n"
```

### Setup
Install salt 2016.11.5 and setup salt-api
```
[root@li90-111 ~]# curl -sSk http://localhost:8000/jobs -H 'Accept: application/x-yaml' -H 'X-Auth-Token: 99e1511d6b2d0112754df005dd1259653e528e7a'
return:
- "Exception occurred in runner jobs.list_jobs: Traceback (most recent call last):\n\
  \  File \"/usr/lib/python2.7/site-packages/salt/client/mixins.py\", line 395, in\
  \ _low\n    data['return'] = self.functions[fun](*args, **kwargs)\nTypeError: list_jobs()\
  \ got an unexpected keyword argument 'jid'\n"
```

### Steps to Reproduce Issue
`salt-master -d; salt-minion -d; salt-api -d`
`curl -k -c /tmp/cookies.txt -sS localhost:8000/login -H "Accept:application/x-yaml" -d username='saltdev' -d password='saltdev' -d eauth='pam'`
`curl -sSk http://localhost:8000/jobs -H 'Accept: application/x-yaml' -H 'X-Auth-Token: <session token from earlier command'`

### Versions Report
```
[root@li90-111 ~]# salt --versions
Salt Version:
           Salt: 2016.11.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 4.9.15-x86_64-linode81
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

### PR DESCRIPTION
**Pull request by gtmanfred**
### What does this PR do?
Fix /jobs api

### What issues does this PR fix or reference?
Fixes #41100

### Tests written?

No

### CODE REVIEW

**Comment by cachedout** [comment]
Don't we want to know the jid when we list jobs?

**Comment by gtmanfred** [comment]
When you don't pass a jid, the api runs jobs.list_jids, which will return all the jids in the job cache.

**Comment by rallytime** [comment]
@gtmanfred There's a lint error here :)

**Comment by gtmanfred** [comment]
drat!

**Comment by Ch3LL** [comment]
Go Go Jenkins!

**Pull request merged**
