### PR TITLE
Refactored win_pkg to get all installed software as well as remove the win32* 3rd party module dependencies

### PR DESCRIPTION
**Pull request by belvedere-trading-user**
Motivation:
I was not be able to get all installed software on both the 32bit and Wow64 registries. The problem is that the win32api module automatically redirects to the registry hive of the platform being run (Wow64 or 32 bit).
There was no way that I was able to find a way to prevent this from happening.

More information can be found here:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa384232(v=vs.85).aspx

Furthermore, depending on if a program is 64 bit or 32 bit, when it is installed the program will be entered
in the appropriate registry hive. Thus, the win32api module will not get all installed software.

Implemantation/Fix:
The built in _winreg module allows for opening either the 64 or 32 bit hive, thus allowing for all installed software to be reported.
Furtheremore, using _winreg allows for the removal of third party dependencies as it is a built-in module for python.

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@twangboy Can you please have a look here and get this merged when it is ready? Thanks.

**Comment by twangboy** [comment]
@DennisHarper This needs to be split into two Pull Requests. 
*setup.py*
This one looks good. Please submit this one against the 2015.5 branch.
*win_pkg.py*
This one goes in the develop branch. It's failing some lint tests, specifically the `import _winreg`. This needs to be changed to `from salt.ext.six.moves import winreg as _winreg  # pylint: disable=import-error,no-name-in-module`

**Comment by twangboy** [comment]
@belvedere-trading I submitted the change to `setup.py` on the 2015.5 branch. Please make the suggested change to `win_pkg.py` and everything should be good.

**Comment by rallytime** [comment]
Looks like this was replaced by #27504, so I am going to close this one out. If this was in error, please let me know and we'll gladly re-open.

**Pull request closed without merging**
