### PR TITLE
Contribution: Module for creating temporary files & dirs

### PR DESCRIPTION
**Pull request by The-Loeki**
Small module for easily creating temp files & dirs

### CODE REVIEW

**Comment by The-Loeki** [comment]
The errors don't seem to be in the module?

**Comment by jfindlay** [comment]
@The-Loeki, there is a [lint error](https://jenkins.saltstack.com/job/salt-pr-lint-n/6666/violations/file/salt/modules/temp.py/).  Everything else is unrelated.  If you rebase your git checkout on upstream before making changes, some of the unrelated test failures will not happen, but the rest here are jenkins problems.

**Comment by The-Loeki** [comment]
@jfindlay it's a good thing I deleted that final newline to fix the earlier PyLint error regarding newlines at the end of the file then ;) tnx

**Comment by The-Loeki** [comment]
euhm

So the lint error was
```
salt/modules/temp.py:43: [W8292(no-newline-at-end-of-file), ] PEP8 W292: no newline at end of file
```

Add one newline, get:
```
salt/modules/temp.py:44: [W8391(blank-line-at-end-of-file), ] PEP8 W391: blank line at end of file`
```

LOL What gives?

**Comment by jfindlay** [comment]
In the second case there are two newlines at the end.  Pylint is uncompromising in its desire for neither zero nor many, but exactly one.

**Comment by The-Loeki** [comment]
@jfindlay, I know, but AFAICT there *is* *exactly* one newline I deleted in the first PyLint fix commit, and then readded in the second.

**Comment by The-Loeki** [comment]
w00t

**Comment by jfindlay** [comment]
@The-Loeki, nice!

**Pull request merged**
