### PR TITLE
Predatory work on the master cluster

### PR DESCRIPTION
**Pull request by SmithSamuelM**

### CODE REVIEW

**Comment by techhat** [comment]
I'm just curious, did you mean "preparatory"?

**Comment by rallytime** [comment]
Haha I lol'ed at "predatory". Master cluster will rule all.

**Comment by UtahDave** [comment]
I kinda like "predatory"   :)

**Comment by techhat** [comment]
Behold, as the salt master cluster stalks its prey. A small group of minions warily watches their surrounding area as they cautiously drink from the Internet oasis. A sickly minion, largely ignored by the others, tries to edge its way into the data. Finally, forced away from the uncaring group, the sickly minion ventures out to the further edges of the Internet oasis, determined to drink of the life-giving data. The master cluster chooses this opportunity to strike!

**Comment by rallytime** [comment]
This program is brought to you by Salt Geographic. And by viewers like you.

**Comment by techhat** [comment]
salt-geo

**Comment by SmithSamuelM** [comment]
Top of the food chain baby!!!

> On 22 Jan 2015, at 08:13 , Joseph Hall <notifications@github.com> wrote:
> 
>  <https://cloud.githubusercontent.com/assets/287147/5858192/85d6f99a-a20e-11e4-9003-a599dbf22994.png>
> —
> Reply to this email directly or view it on GitHub <https://github.com/saltstack/salt/pull/19929#issuecomment-71034882>.
> 


Samuel M. Smith Ph.D.
smith.samuel.m@gmail.com

242 East 600 North, Lindon Utah 84042-1662 USA
801-785-3185 home
801-592-8230 mobile
801-766-3528 fax

**Comment by SmithSamuelM** [comment]
Behold, as the masters in the master cluster spread out in formation stalking prey. A small group of minions warily watches their surrounding area as they cautiously drink from the Internet oasis. A sickly minion, largely ignored by the others, tries to edge its way into the data. Finally, forced away from the uncaring group, the sickly minion ventures out to the further edges of the Internet oasis, determined to drink of the life-giving data. The lead master in the master cluster chooses this opportunity to strike!

**Pull request merged**
