### PR TITLE
Back-port #50301 to 2018.3

### PR DESCRIPTION
**Pull request by rallytime**
Back-port #50301 to 2018.3

### CODE REVIEW

**Comment by cachedout** [comment]
@rallytime and @tonybaloney Looks like test failures are afoot.

**Comment by tonybaloney** [comment]
😕 errr. If I fix this, should I merge it forward to develop or leave it (I think this failure is specific to 2018.3)

**Comment by tonybaloney** [comment]
@rallytime 🎁 https://github.com/rallytime/salt/pull/32

**Comment by rallytime** [comment]
@tonybaloney Thank you! The fix you made is specific to `2018.3` so no other work is needed here. :)

**Pull request merged**
