### PR TITLE
Allow creation of volatile registry keys in reg.py module

### PR DESCRIPTION
**Pull request by ghost**
### What does this PR do?

It provides an extra option for reg.set_value which allows for the creation of volatile registry keys
### What issues does this PR fix or reference?

This will be of general use and specifically it will help with progress on #33418
### Tests written?

No, but I did extensive manual tests

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @hrumph 

Could you make the change recommended here, please? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/2121/violations/file/salt/modules/reg.py/

**Comment by hrumph** [comment]
I removed the backslash

**Comment by cachedout** [comment]
Thanks, @hrumph 

I will get this in after the tests finish running.

**Comment by damon-atkins** [comment]
This code appears to break the unicode support.  Please compare to https://github.com/saltstack/salt/blob/cf4826aad4a0c782e2586607707162fa6f46773d/salt/modules/reg.py

In particular this section is different in set_value
    if PY2:
        local_hive = _mbcs_to_unicode(hive)
        local_key = _unicode_to_mbcs(key)
        local_vname = _unicode_to_mbcs(vname)
        local_vdata = _unicode_to_mbcs(vdata)
        local_vtype = _mbcs_to_unicode(vtype)
    else:
        local_hive = hive
        local_key = key
        local_vname = vname
        local_vdata = vdata
        local_vtype = vtype

**Comment by damon-atkins** [comment]
PS Jenkins does not run the windows tests....  It would be nice if windows was added to the test platforms

**Comment by hrumph** [comment]
@damon-atkins,
About the unicode, I believe you are right. My bad. What happened was based on a misreading of the win32api source code. For some reason I thought that win32api didn't use unicode. I'll PR a fix in a few minutes.

**Comment by hrumph** [comment]
@damon-atkins,
I was actually going to ask you directly about what do do about the unicode before the initial PR but I just forgot to do it for some reason.

**Comment by hrumph** [comment]
@damon-atkins I have reverted the unicode stuff in PR #33586

**Comment by hrumph** [comment]
@damon-atkins 
It seems to me that when using win32api library, I should be using unicode no matter what version of python is being used, so it should be unicode in all cases. Can you or anyone confirm this?

**Pull request merged**
