### PR TITLE
Update postgres.py

### PR DESCRIPTION
**Pull request by kgbsd**
### What does this PR do?
Fix postgresql user on FreeBSD.
That user was updated from 'pgsql' to 'postgresql' in 2016:
https://svnweb.freebsd.org/ports/head/UPDATING?revision=502290&view=co
20160905:
  AFFECTS: users of databases/postgresql96-server
  AUTHOR: girgen@FreeBSD.org

  The default unix user used by the PostgreSQL daemon has changed to
  `postgres' to reflect the long time upstream's convention. Any scripts
  you have using the old `pgsql' unix user should be modified when upgrading to
  PostgreSQL version 9.6. Older versions of PostgreSQL will continue using
  `pgsql' until their end-of-life.

### What issues does this PR fix or reference?
 able to manage postgresql databases with salt

### Previous Behavior
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python3.6/site-packages/salt/modules/cmdmod.py", line 425, in _run
                  pwd.getpwnam(runas)
              KeyError: "getpwnam(): name not found: 'pgsql'"
              
              During handling of the above exception, another exception occurred:
              
              Traceback (most recent call last):
                File "/usr/local/lib/python3.6/site-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/local/lib/python3.6/site-packages/salt/loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "/usr/local/lib/python3.6/site-packages/salt/states/postgres_database.py", line 98, in present
                  dbs = __salt__['postgres.db_list'](**db_args)
                File "/usr/local/lib/python3.6/site-packages/salt/modules/postgres.py", line 488, in db_list
                  password=password)
                File "/usr/local/lib/python3.6/site-packages/salt/modules/postgres.py", line 438, in psql_query
                  password=password)
                File "/usr/local/lib/python3.6/site-packages/salt/modules/postgres.py", line 377, in _psql_prepare_and_run
                  rcmd, runas=runas, password=password, host=host, port=port, user=user)
                File "/usr/local/lib/python3.6/site-packages/salt/modules/postgres.py", line 186, in _run_psql
                  ret = __salt__['cmd.run_all'](cmd, python_shell=False, **kwargs)
                File "/usr/local/lib/python3.6/site-packages/salt/modules/cmdmod.py", line 2069, in run_all
                  **kwargs)
                File "/usr/local/lib/python3.6/site-packages/salt/modules/cmdmod.py", line 428, in _run
                  'User \'{0}\' is not available'.format(runas)
              salt.exceptions.CommandExecutionError: User 'pgsql' is not available
     Started: 09:44:32.474881
    Duration: 7.452 ms
     Changes:  

### New Behavior
  runs without error.

### Tests written?
No

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by garethgreenaway — APPROVED** [review]

**Review by waynew — CHANGES_REQUESTED** [review]
Hi @kgbsd - we've changed our process to have a single `master` branch - would you be able to rebase this on master?

Additionally, we're also requiring tests. Would you be willing to write some tests for this?

Thanks!

**Comment by kgbsd** [comment]
So far git is not wanting to rebase this on master, too many conflicts.  I'm not a git expert, and so far this looks like it'll be easier to close this, and do a new pull request unless you have a simpler solution?

**Comment by waynew** [comment]
@kgbsd you should be able to do an interactive rebase:

```
git checkout develop
git fetch upstream   #assuming salt's repo is upstream
git rebase --interactive upstream/master
```

You only need the one commit: 37c62a99088bdf2f62c88f9f9895ba9674c22579

There shouldn't be (m)any merge conflicts.

**Comment by s0undt3ch** [comment]
We're no longer accepting PRs against the `develop` branch. Please reopen against the `master` branch.

**Comment by s0undt3ch** [comment]
Sorry, just noticed the instructions from Wayne are to rebase against master.

**Comment by sagetherage** [comment]
closing as abandoned

**Pull request closed without merging**
