### PR TITLE
Make the Salt Proxy environment aware

### PR DESCRIPTION
**Pull request by bdrung**
The Salt proxy minion is looking for proxy minion modules in `salt://_proxy/`. It does so however only in the default `base` environment. On setups which do not use `base` or shall be executed in a different environment this breaks:

/etc/salt/master:
```
...
file_roots:
  noc:
    - /srv/salt
...
```

```
$ grep "proxyenabled" /srv/salt/_proxy/junos_manager.py
__proxyenabled__ = ['junos_manager']

$ salt-proxy --proxyid=dev1 -l debug
...
[DEBUG   ] rest_sample proxy __virtual__() called...
[INFO    ] ssh_sample proxy __virtual__() called...
[DEBUG   ] Could not LazyLoad junos_manager.grains
[DEBUG   ] Could not LazyLoad junos_manager.init
[ERROR   ] Proxymodule junos_manager is missing an init() or a
shutdown() or both. Check your proxymodule.  Salt-proxy aborted.
[WARNING ] Stopping the Salt Proxy Minion
[ERROR   ] -1
[INFO    ] The proxy minion is shutting down..
[INFO    ] The Salt ProxyMinion is shut down
```

This is because the loader only looks for _proxy modules in the `base` environment. This commit fixes this (but might possibly break other things, though I did not find side-effects).

The initial pull request #36704 were merged quite some time ago, but one part of it is missing in the 2019.2 release (again?).

### CODE REVIEW

**Review by twangboy — DISMISSED** [review]

**Comment by twangboy** [comment]
Hey, @bdrung 

Looks like this needs to be rebased and have pre-commit run on it. Do you mind doing that?

https://docs.saltstack.com/en/latest/topics/development/contributing.html#quickstart

**Comment by bdrung** [comment]
I rebased it yesterday and pre-commit was successfully run.

**Comment by twangboy** [comment]
Sweet... now we need to figure out why these tests are failing

**Comment by bdrung** [comment]
Only codecov/project is failing, which makes no sense since this merge request just changes one line.

**Comment by waynew** [comment]
codecov can be ignored - on the newest master it should be.

Question: Why is it `"saltenv"` on this branch, but `"environment"` on the develop branch PR?

**Comment by bdrung** [comment]
In one salt release, the `environment` option was replaced by `saltenv`.

**Review by waynew — DISMISSED** [review]

**Review by twangboy — DISMISSED** [review]

**Comment by twangboy** [comment]
@bdrung  Unless this gets a test today, it's not going to make it into Sodium.

**Review by twangboy — APPROVED** [review]

**Comment by Ch3LL** [comment]
@bdrung would you be willing to add a changelog and test coverage?

**Review by twangboy — CHANGES_REQUESTED** [review]
Please add a changelog and a test case

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
