### PR TITLE
Update psutil to 5.8.0

### PR DESCRIPTION
**Pull request by krionbsd**
### What does this PR do?
Update psutil to 5.7.3

### CODE REVIEW

**Comment by s0undt3ch** [comment]
This version extends support for FreeBSD

**Review by s0undt3ch — DISMISSED** [review]

**Review by s0undt3ch — APPROVED** [review]

**Comment by s0undt3ch** [comment]
@bryceml, @krionbsd: this doesn't bring any packaging issues?

**Comment by krionbsd** [comment]
re-run ubuntu1804

**Comment by krionbsd** [comment]
re-run macosxcatalina

**Comment by krionbsd** [comment]
re-run macosxmojave

**Comment by krionbsd** [comment]
re-run macosxmojave

**Review by bryceml — APPROVED** [review]

**Comment by s0undt3ch** [comment]
Got a 👍 from @bryceml

**Pull request merged**
