### PR TITLE
Migrate NAPALM modules to be used in both proxy and regular minion

### PR DESCRIPTION
**Pull request by mirceaulinic**
### What does this PR do?

Transforms the existing NAPALM modules to be usable with both proxy minions and straight minions. The key of this PR is the ```proxy_napalm_wrap``` decorator which injects the global var ```napalm_device``` in the module function.

Direct implications:

- moved the logic from the proxy module in the utils, in order to be re-used
- allow **kwargs for all functions
- ```__virtual__()``` returns the  ```__virtualname__``` no matter if proxy or not (but still fails if NAPALM is not installed)
- configuration-related functions need to pass an argument ```inherit_napalm_device``` with the original ```napalm_device``` object containing the configuration session. If this is not sent, at each function underneath will be open another config DB which leads to failure, as network devices allow one single config session open at a time.

Otherwise, everything remains unchanged.

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @mirceaulinic. Could you please take a look at these lint errors? Thanks! https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/7555/violations/

**Comment by mirceaulinic** [comment]
Hi @cachedout - yes, definitely I will need fix some. But others such: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/7555/violations/file/salt/modules/napalm_ntp.py/ cannot be fixed, as the linter complains that ```napalm_device``` variable is undefined, although it is injected by the decorator. Would you recommend to comment those lines?

However, I realised earlier today that I also need to adapt the grains and state modules; so I still have some work to be done here... :)

**Comment by mirceaulinic** [comment]
It is complaining about:

```
2016-12-20 05:48:18,128 [salt.loader                                 ][ERROR   ][19502]
Exception raised when processing __virtual__ function for napalm. Module will 
not be loaded 'module' object has no attribute 'is_proxy'
2016-12-20 05:48:18,129 [salt.loader                                 ][WARNING ][19502] 
salt.loaded.int.grains.napalm.__virtual__() is wrongly returning `None`. 
It should either return `True`, `False` or a new name. 
If you're the developer of the module 'napalm', please fix this.
```

Which I don't understand:

```python
def __virtual__():

    '''
    NAPALM library must be installed for this module to work and run in a (proxy) minion.
    '''

    if HAS_NAPALM \
       and (salt.utils.napalm.is_proxy(__opts__) or salt.utils.napalm.is_minion(__opts__)):
        return __virtualname__
    else:
        return False
```

What should be changed here?

**Comment by mirceaulinic** [comment]
Hi @cro - I have finished migrating. Would you mind having a look here?
I have tested on both proxies and straight minions and looks good so far (or, at least, nothing broke yet).

**Comment by cachedout** [comment]
Bump @cro

**Comment by cro** [comment]
@mirceaulinic This looks great!  Nice to see that the pattern I developed for sharing functions between proxy/modules is working out!

There is one minor lint error, and one failing test that I'm not sure about.  I'm looking at it now.

**Comment by mirceaulinic** [comment]
> Nice to see that the pattern I developed for sharing functions between proxy/modules is working out!

I never had any doubts - thanks very much once again! Event the docstring is almost the same :D

**Comment by cro** [comment]
Would you mind rebasing this against current develop and fixing that one lint error?  If you push the branch up then I think the tests will pass.

**Comment by cachedout** [comment]
@mirceaulinic Did you see the message about the needed rebase?

**Comment by mirceaulinic** [comment]
Hi @cro, @cachedout - sorry for delay; I have pushed the required changes.

**Comment by cachedout** [comment]
@mirceaulinic We're still seeing a merge conflict here. One more rebase might be needed. Apologies.

**Comment by mirceaulinic** [comment]
No worries @cachedout - I'll rebase. I just realised there would be required one more fix in the 2016.11 branch (which would be then ported into develop) before 2016.11.2 which is more urgent. The changes from the PR are for Nitrogen only so there's no rush.
BTW: are you aware what's the current release plan for 2016.11.2?

**Comment by cachedout** [comment]
@mirceaulinic Thanks for the promised rebase. Last I heard we were hoping for Friday for 2016.11.2 but @meggiebot is the authority there.

**Comment by cachedout** [comment]
@mirceaulinic I'm ready to get this in once the rebase is done. Let me know. Thanks! :]

**Comment by mirceaulinic** [comment]
Sure, please put this on hold for a few days, as I expect few more changes changes in the develop that will create more conflicts. I will keep you posted @cachedout, thanks for understanding!

**Comment by cachedout** [comment]
@mirceaulinic Just checking in with you here. Let me know how we're looking on this one. No hurry. :]

**Comment by mirceaulinic** [comment]
Hi @cachedout @cro I have rebased this branch.

While I'm very excited about these changes, bugfixes ported from the `2016.11` branch to `develop` will be more painful as there are many structural changes in the execution modules and especially in the proxy.

**Comment by cro** [comment]
Go Go Jenkins!

**Comment by cro** [comment]
@cachedout, @rallytime -- I think this is ready to be merged.  The test failures look unrelated or bogus.

**Pull request merged**
