### PR TITLE
Handle ifconfig output differently for NetBSD >= 8.0

### PR DESCRIPTION
**Pull request by travispaul**
### What does this PR do?
Calls a new function: ``netbsd_interfaces()`` to get networking info on NetBSD.

If the NetBSD version is >= 8.0 ``_netbsd_interfaces_ifconfig()`` is used to parse the output of ifconfig.

### What issues does this PR fix or reference?
#48856

### Previous Behavior
Salt fails to start on NetBSD 8.0 due to changes in ifconfig output.

### New Behavior
Salt no longer fails to start and the new ifconfig output is parsed.

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by gtmanfred — CHANGES_REQUESTED** [review]
This looks good, can we get some unittests for this, just so that we can make sure it doesn't break because we do not ever run integration tests on netbsd.

**Comment by travispaul** [comment]
@gtmanfred sure, I can do that. Just a heads-up it might take a week or so given my current workload.

**Review by terminalmage — APPROVED** [review]

**Comment by travispaul** [comment]
Please let me know if any other tests or changes are needed. Thanks.

**Comment by rallytime** [comment]
@travispaul There are some lint errors that need to be fixed: https://jenkinsci.saltstack.com/job/pr-lint/job/PR-48926/2/warnings52Result/

**Review by gtmanfred — APPROVED** [review]

**Comment by gtmanfred** [comment]
Thanks for adding the test!

**Review by garethgreenaway — APPROVED** [review]
Nice!

**Pull request merged**
