### PR TITLE
Fix usage of dockerng "cmd"

### PR DESCRIPTION
**Pull request by terminalmage**
We need to use "command" under the hood instead of "cmd", as docker-py
expects "command".

Refs #27331, #27444.

### CODE REVIEW

**Comment by ticosax** [comment]
@terminalmage I don't like the way you impersonate my contributions.
It matters for me to keep an history of my work.
I think you can just add your commits on top of #27444

**Comment by terminalmage** [comment]
@ticosax I think you are misunderstanding. I made my own commit to reverse command/cmd, then cherry-picked your commit on top of it, expecting to discard changes to the state and execution module and keep the test. It turned out that doing so did not change either states/dockerng.py or modules/dockerng.py, which is when I realized that your fix was initially correct (minus some additional changes to the comments).

I actually took special care to incorporate your work, otherwise I wouldn't have cherry-picked in the first place and the test you added would have been under my name and not yours.

**Comment by terminalmage** [comment]
I honestly don't care who gets credit for what, my top concern is that this is fixed. I reworked the PR to place the differences between your changes and mine after your commit, rather than cherry-picking your PR into the changes I made.

Hopefully, in the future we can resolve these sort of misunderstandings with discussion (I'm almost always on freenode) rather than accusation.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by ticosax** [comment]
@terminalmage Sincerely thank you !
I apologize for the way I claim the ownership of my contributions. Ididn't realize I was accusing you until you point it out. 

I like contributing for saltstack, I think wonderful people are working here. The last thing I want is to break the trust you put in contributions coming from the community.

Back to business:
I'll fix the test soon (same as #27451)

**Comment by cachedout** [comment]
Superceded by #27465

**Pull request merged**
