### PR TITLE
Fix #34587 provide users a hint about how to get initdb on path when …

### LINKED ISSUE #34587: postgres_initdb.present fails on Redhat with PostgreSQL provided installation
### Setup
The following state:

```
db-data-dir:                                                                    
   postgres_initdb.present:                                                      
     - name: /var/lib/pgsql/9.4/data/                                            
```

Fails with:

```
[INFO    ] Executing state postgres_initdb.present for /var/lib/pgsql/9.4/data/
[ERROR   ] initdb not found in path
[ERROR   ] Postgres data directory /var/lib/pgsql/9.4/data/ initialization failed
```

When using the the PostgreSQL provided repositories on RHEL 7 because initdb is located in `/usr/pgsql-<postgres-version>/bin/initdb`. This is not in root's path:

`/sbin:/bin:/usr/sbin:/usr/bin`

### Steps to Reproduce Issue
1. Use a RedHat 7 machine
2. Install the official PostgreSQL rpm: `# yum -y install http://yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgdg-redhat94-9.4-1.noarch.rpm`
3. Install the _PostgreSQL Server_ group: `# yum -y groupinstall "PostgreSQL Database Server 9.4 PGDG"`

Attempt to use the `postgres_initdb.present` state.

### Versions Report

```
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 11 2015, 17:47:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 7.2 Maipo
        machine: x86_64
        release: 3.10.0-327.13.1.el7.x86_64
         system: Linux
```

### PR DESCRIPTION
**Pull request by benhosmer**
### What does this PR do?

Update the postgres_initdb state docs.
### What issues does this PR fix or reference?

34587

### CODE REVIEW

**Comment by cachedout** [comment]
@benhosmer Thanks for this. Would you mind removing the trailing whitespace that's mentioned here: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/3391/violations/file/salt/states/postgres_initdb.py/

Thanks!

**Comment by benhosmer** [comment]
I'm glad the bot caught that. I also added some highlighting to make the directories look a little cleaner too.

**Comment by eradman** [comment]
Does this update to the docs cover enough functionality? If you symlink `initdb` other commands will still fail, such as

    salt 'myhost' postgres.db_list

This is a separate topic, but I wonder if the postgres module itself needs to be extended to support a new argument such as `pg_bin=/usr/pgsql-9.5/bin` so that multiple versions can be supported at the same time.

**Comment by benhosmer** [comment]
@eradman you bring up a valid point that I hadn't considered. 

I originally encountered this issue when I installed PostgreSQL from the official postgres repos using RedHat 7. 

I see value in having the ability to supply the locations of pgsql, initd etc with the module or state calls.

**Comment by benhosmer** [comment]
This is superceded by https://github.com/saltstack/salt/pull/34947

**Pull request closed without merging**
