### PR TITLE
rvm deb package support

### LINKED ISSUE #62904: [FEATURE REQUEST] rvm deb package support
**Is your feature request related to a problem? Please describe.**
The rvm Salt module cannot find the rvm binary if it was installed as an apt package.
Salt is hard coded to use `/usr/local/rvm/bin/rvm` but the apt package installs rvm into `/usr/share/rvm/bin/rvm`

This causes issues if, for example, RVM was installed from the official rvm PPA https://github.com/rvm/ubuntu_rvm.

You can replicate this by running the following states.
The second state will try to install RVM fresh despite it already being present on the system (https://github.com/saltstack/salt/blob/master/salt/modules/rvm.py#L68)
```
rvm:
  pkgrepo.managed:
    - ppa: rael-gc/rvm
  pkg.installed:
    - name: rvm
    - require:
      - pkgrepo: rvm

ruby-3.1.2:
  rvm.installed
```

**Describe the solution you'd like**
Salt to detect rvm is installed under `/usr/share/rvm/bin/rvm`.

**Describe alternatives you've considered**
I also considered making the rvm binary path a variable you can pass to states however this is a much bigger change.

**Additional context**

### PR DESCRIPTION
**Pull request by ghost**
### What does this PR do?
Added alternative rvm path meeting Debian convention, as used by the official PPA (https://github.com/rvm/ubuntu_rvm).

### What issues does this PR fix or reference?
Fixes: #62904

### Previous Behavior
If you have RVM installed on the minion via the PPA, Salt module ignores that install and start installing a duplicate install. 

### New Behavior
RVM now uses the PPA install if available. 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by OrangeDog** [comment]
This should use `salt.util.path.which` or `salt.util.path.which_bin` to search all the common paths.

**Comment by MKLeb** [comment]
> This should use `salt.util.path.which` or `salt.util.path.which_bin` to search all the common paths.

@OrangeDog makes a good point, and also this will need a test or two to get merged.

**Comment by RobHooper** [comment]
@OrangeDog @MKLeb , I've been testing `salt.util.path.which` but it doesn't work in this use-case. 
I think this is a quirk of the RVM install, Salt doesn't find `/usr/share/rvm/bin` in `$PATH` and always returns `None`.

Digging further, I can see the RVM directory in `os.environ.get("PATH")` running it directly in python on the server, however it isn't there when I run this with salt. 
From what I can tell this directory is added to `$PATH` in `/etc/profile.d/rvm.sh`, maybe this isn't loaded when Salt executes?

This `$PATH` quirk is true for both installation methods (the rvm bash script and the apt install), perhaps this is why it was hardcoded in the first place.

**Comment by OrangeDog** [comment]
The code should always check the PATH for executables. It sounds like this should also check some additional ones.

Environment settings in `/etc/profile.d/` usually won't affect services, no.

**Comment by RobHooper** [comment]
Regarding testing, my current PR has broken the current tests which check for the hardcoded RVM path. So todo:
- [ ] Add test for RVM installed into /usr/share/rvm/bin/rvm
- [ ] Add test for RVM installed into /usr/local/rvm/bin/rvm
- [ ] Update broken tests

I'm still learning about testing, I'm not sure how to upload a file in the mock environment in-order to test this. Any advise would be appreciated.

**Comment by whytewolf** [comment]
> Regarding testing, my current PR has broken the current tests which check for the hardcoded RVM path. So todo:
> 
>     * [ ]  Add test for RVM installed into /usr/share/rvm/bin/rvm
> 
>     * [ ]  Add test for RVM installed into /usr/local/rvm/bin/rvm
> 
>     * [ ]  Update broken tests
> 
> 
> I'm still learning about testing, I'm not sure how to upload a file in the mock environment in-order to test this. Any advise would be appreciated.

it isn't about inserting the file in a mock enviroment. mock means it is pretending to be the __salt__['cmd.run_all'] and seeing if it is called with variables instead of actually running it. but because you change changed the default behavior from outputing a path to outputing none if the path isn't found it breaks. isn't matching the path given in https://github.com/saltstack/salt/blob/master/tests/unit/modules/test_rvm.py#L18-L28

if the file really existed in the fileserver it would be found. so to your tests. you would have a test create a file in one place. run the check. delete the file create the file in another location and delete the file. 

either way I'm not sure None is a good answer. as the code that runs this command isn't set to keep cmd.run_all from running if the directory doesn't exist. which means you are not sure what the command being run is. the command that runs this should be updated to make sure that None is a valid answer.

**Comment by OrangeDog** [comment]
> make sure that None is a valid answer

or raise an exception, as presumably nothing else is going to work if it can't find the command

**Comment by RobHooper** [comment]
> either way I'm not sure None is a good answer. as the code that runs this command isn't set to keep cmd.run_all from running if the directory doesn't exist. which means you are not sure what the command being run is. the command that runs this should be updated to make sure that None is a valid answer.
...
> or raise an exception instead of returning, as presumably nothing else is going to work if it can't find the command
> You could even do the check in `__virtual__()` and then not load the module at all if `rvm` is missing.

Code wise, None works in practice - when ` _get_rvm_location()` is executed it is (currently) always passed through `is_installed()` checking that the rvm binary is executable handling None fine.

However, I agree that None isn't the best response from the function and that it may be called in different ways in the future.

I like the suggestion of raising an exception or stopping the module from loading however this will break the `_check_and_install_ruby()` function in the state file.
https://github.com/saltstack/salt/blob/master/salt/states/rvm.py#L116

I think returning a path by default (`/usr/local/rvm/bin/rvm`), even if it doesn't exist, may be best for legacy support.

**Comment by RobHooper** [comment]
@whytewolf, I doubt the tests for this PR will be ready anytime soon. 

All of the RVM module tests need porting over to the new pytest suite, especially since the change breaks existing tests.

**Pull request closed without merging**
