### PR TITLE
Changes to gpg.py module

### PR DESCRIPTION
**Pull request by garethgreenaway**
Ability to specify the location where GPG related files are kept. #20033

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
These failures do not appear to be related but they do appear to be new....

**Comment by thatch45** [comment]
@garethgreenaway can you please rebase? To help us make sure these test failures are not valid?

**Comment by garethgreenaway** [comment]
Definitely.  Will push an update in a minute.

**Comment by thatch45** [comment]
Thanks for the rebase @garethgreenaway !

**Pull request merged**
