### PR TITLE
windows support for ipv4 detection

### PR DESCRIPTION
**Pull request by attiasr**
inet_pton is not available on windows (https://bugs.python.org/issue7171)

### CODE REVIEW

**Comment by UtahDave** [comment]
I believe this was fixed with a pull request recently that added this function.

Hold off on merging this until I can confirm with @twangboy

**Comment by twangboy** [comment]
This was modified with the PR in November:
https://github.com/saltstack/salt/commit/d03ff7d6ddd658b75c37d48ba19b5dd5da825c69
Which apparently broke this on windows. The purpose of the fix was to fix IPv6 verfication. The old way used aton which is what this fix reverts back to. So the question is... has this patch been tested with IPv6? If it works with both, perhaps we should ditch my PR for this one because it doesn't require an ext library.

**Comment by c0m4** [comment]
The current state support ipv4/6 on Linux but doesn't work at all on windows. 
The patch I've suggested support ipv4/6 on Linux but support ipv4 only on windows.

**Comment by cachedout** [comment]
@twangboy What's the status here?

**Comment by twangboy** [comment]
@cachedout @UtahDave #23688 Adds inet_pton for windows. But it requires adding an external library. I thought if his solution supported IP6, it was a much cleaner fix. But it doesn't, so I recommend we do not merge this.

**Comment by jfindlay** [comment]
@UtahDave, @twangboy, any progress on this?

**Comment by twangboy** [comment]
@jfindlay I recommend we do not merge this.

**Comment by jfindlay** [comment]
@c0m4, thanks for the work on this.  It looks like we've resolved this in another fix, thanks.

**Comment by c0m4** [comment]
np, thanks

**Pull request closed without merging**
