### PR TITLE
#62626 moved bin_env to example

### LINKED ISSUE #62626: [DOCS] pip.installed bin_env example is in the wrong place
**Description**
image

**Suggested Fix**
Move the example up to the correct param section

**Type of documentation**
Salt modules,

**Location or format of documentation**
https://docs.saltproject.io/en/latest/ref/states/all/salt.states.pip_state.html#salt.states.pip_state.installed

### PR DESCRIPTION
**Pull request by muckitymuck**
### What does this PR do?
Moves the bin_env down to its example in file salt.7

### What issues does this PR fix or reference?
Fixes: #62626

### Merge requirements satisfied?

- [ X] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by whytewolf** [comment]
This does not fix the problem. This is only moving it in the man page. This needs to be fixed in https://github.com/saltstack/salt/blob/master/salt/states/pip_state.py#L568-L618 which will also end up fixing the man page.

**Comment by whytewolf** [comment]
@muckitymuck This is not the fix for that ticket. This isn't even going to work as the man page is generated. I pointed out what needs to change in the above comment. If you want to make that change i would be happy to review this. but if not i will go ahead and close this PR without merging.

**Comment by Ch3LL** [comment]
@muckitymuck did you see @whytewolf 's comments?

**Comment by muckitymuck** [comment]
Sorry, all.  I am trying to set up my sphinx but no luck.  I think someone else will have to finish it.

**Comment by whytewolf** [comment]
@muckitymuck No problem. I'll go ahead and close his PR.

**Pull request closed without merging**
