### PR TITLE
Pass 'sock_dir' for all 'salt.utils.cloud.fire_event()' calls (#34806)

### PR DESCRIPTION
**Pull request by jerrykan**
Fix for saltstack/salt#34806 

If no 'sock_dir' value is passed into the 'fire_event()' function it would default to a value that ignores the 'base_dir' value set in the master config file.

We need to explicitly pass the 'sock_dir' value when calling 'fire_event()' so that the correct directory is used. Because of this change it no longer makes sense for 'sock_dir' to be an optional parameter for 'fire_event()' so the function parameters need to be reordered as well.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
We can't simply turn a keyword argument into a positional argument this late in the game(after so many releases).

While this works for salt because you update all calls, anyone who has written a custom cloud module(an internal cloud setup, an adaptation/modification of one of the salt cloud drivers) which is served from their state tree would be immediately broken.

We should instead deprecate, but this kind of deprecation is really hard because its a new positional argument (if it was removing a positional argument it would be simpler).

So, I suggest that you keep it as a positional argument. On top of that, instead of defaulting to the syapaths socket directory when its None, we should error out or log a warning thus, forcing everyone to start passing sock_dir.

**Comment by s0undt3ch** [comment]
Sorry, keep it as a keyword argument, not positional argument.

**Comment by jerrykan** [comment]
> We can't simply turn a keyword argument into a positional argument this late in the game(after so many releases).

That is fair enough

> So, I suggest that you keep it as a [keyword] argument. On top of that, instead of defaulting to the syapaths socket directory when its None, we should error out or log a warning thus, forcing everyone to start passing sock_dir.

I was hoping to avoid that my rearranging the arguments, but as you say that is not really workable. If you are happy to recommend an exception type then I can update the pull request.

**Comment by jerrykan** [comment]
I've updated the pull request so that `sock_dir` remains a keyword argument (ie. the `fire_event()` function remains unchanged). All cloud drivers should now work correctly, but any 3rd party drivers exhibit the existing behaviour.

The two lines in `fire_event()` [to check to see if `sock_dir` is `None`](https://github.com/jerrykan/salt/blob/0f5b506ec0e4649adbeb5b1c314a2edf6ac0c84b/salt/utils/cloud.py#L1730) could be removed, which should eventually result in an exception being raised somewhere in the call stack, but that would break existing behaviour. Maybe a deprecation warning could be added within the conditional code block for the next release, then the code block removed in the following release?

**Comment by s0undt3ch** [comment]
Yes, a deprecation path is better..

**Comment by jerrykan** [comment]
DeprecationWarning now added.

**Comment by s0undt3ch** [comment]
Please have a look at `salt.utils.warn_until()` and grep Salt's source code for example usage.

**Comment by jerrykan** [comment]
I wasn't aware of `salt.utils.warn_until()`, I used DeprecationWarning because that was being used in the rest of `salt/utils/cloud.py`. I've updated the pull request to use `warn_until()`.

**Pull request merged**
