### PR TITLE
Fix #22991 Correctly set result when test=True

### LINKED ISSUE #22991: npm.installed ignores test=True
```console
$ salt-call --versions-report
                  Salt: 2014.7.5
                Python: 2.7.3 (default, Mar 13 2014, 11:03:55)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.6
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 13.1.0
                  RAET: Not Installed
                   ZMQ: 3.2.3
                  Mako: 0.7.0
 Debian source package: 2014.7.5+ds-1~bpo70+1

$ sudo salt-call state.highstate
[ ... ]
local:

Summary
-----------
Succeeded: 0
Failed:   0
-----------
Total states run:    0

$ sudo salt-call state.highstate test=True
[ ... ]
ID: gulp
    Function: npm.installed
      Result: None
     Comment: Package(s) 'gulp' satisfied by gulp@3.8.11
     Started: 16:34:28.282854
    Duration: 3997.858 ms
     Changes:   
[ ... ]
Summary
-------------
Succeeded: 37 (unchanged=37)
Failed:     0
-------------
Total states run:     37
```

### PR DESCRIPTION
**Pull request by nicholascapo**

### CODE REVIEW

**Comment by jfindlay** [comment]
@nicholascapo, thanks for the fix.  Will you also update the associated [unit test](https://jenkins.saltstack.com/job/salt-pr-rs-cent7-n/5687/testReport/junit/unit.states.npm_test/NpmTestCase/test_installed/)?

**Comment by nicholascapo** [comment]
@jfindlay The integration/unit tests pass for me now, I'm not sure what caused the failure in Jenkins.

**Comment by jfindlay** [comment]
@nicholascapo, jenkins has been having issues recently that I haven't tracked down yet.

**Comment by jfindlay** [comment]
#22991.

**Pull request merged**
