### PR TITLE
[master] remove salt.payload.Serial

### LINKED ISSUE #64459: [TECH DEBT] Remove salt.payload.Serial
```
236 class Serial:                                                                                                                                    
237 +---  4 lines: """-------------------------------------------------------------------------------------------------------------------------------
241                                                                                                                                                  
242     def __init__(self, *args, **kwargs):                                                                                                         
243         salt.utils.versions.warn_until(                                                                                                          
244             "Chlorine",                                                                                                                          
245             "The `salt.payload.Serial` class has been deprecated, "                                                                              
246             "and is set to be removed in {version}. "                                                                                            
247             "Please use `salt.payload.loads` and `salt.payload.dumps`.",                                                                         
248         )                                                                                                                                        
249                              
```

salt.payload.Serial has previously been deprecated and needs to be removed in 3007.0

### PR DESCRIPTION
**Pull request by cmcmarrow**
### What does this PR do?
remove salt.payload.Serial

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/64459

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by Ch3LL** [comment]
This needs to be pointed to the master branch.

**Review by MKLeb — DISMISSED** [review]

**Review by s0undt3ch — DISMISSED** [review]

**Comment by s0undt3ch** [comment]
Test failures are valid.

**Review by Ch3LL — DISMISSED** [review]
Code looks good just looks like there is some test failures

**Review by s0undt3ch — CHANGES_REQUESTED** [review]
Test failures are valid

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
