### PR TITLE
Glance state module

### PR DESCRIPTION
**Pull request by 0xf10e**
Hi,

here's the promised state module for Glance. For now just the `glance.image_present` function
but maybe one of you is willing to take a look at the code while I move this to a newer revision
of 2015.5 - or 2015.8 if you prefer.
I think I'll add a `glance.image_absent`, too.

Regards, FLorian

### CODE REVIEW

**Comment by jfindlay** [comment]
@0xf10e, it seems you have accidentally included some extra commits.

**Comment by 0xf10e** [comment]
Yes, again… Not looking forward to the cherrypick-fest tomorrow :(
I'll make a new one when I've got this right.

But can you answer me the question whether I should take 2015.5 or 2015.8 as the base? Don't want to do this twice ;)

Am 16. Juli 2015 17:25:41 MESZ, schrieb Justin Findlay <notifications@github.com>:

**Comment by jfindlay** [comment]
2015.8 is going to be better, thanks.  I can also rebase your commits if you want.

**Comment by 0xf10e** [comment]
Naah, I have to learn how to do this by myself ;)

**Pull request closed without merging**
