### PR TITLE
Remove outdated installation method in FreeBSD

### PR DESCRIPTION
**Pull request by AstraLuma**
### What does this PR do?

Removes the outdated mention of repo.saltstack.com from the FreeBSD docs. This repo has not been updated since 2016.11.

It looks like develop has already been updated, but this change has not been applied to previous versions.

### What issues does this PR fix or reference?

None.

### CODE REVIEW

**Comment by dwoz** [comment]
@astronouth7303 I see the following error in the docs build, please have a look.

```
08:32:12 /var/jenkins/workspace/pr-doc_PR-51505-UTL7O2Y2VBAE3IMNUQOUTTCZKLTYTGEG3YOX6QR7PO5XHHV6VZZQ/doc/topics/releases/2015.8.0.rst:24:undefined label: freebsd-upstream (if the link has no caption the label must precede a section header)
```

**Comment by astronouth7303** [comment]
The dead link is in a changelog. I'm not sure what's the best way to handle it, since it's generally considered in poor taste to modify changelogs later.

**Comment by astronouth7303** [comment]
https://docs.saltstack.com/en/latest/topics/releases/2015.8.0.html#new-saltstack-installation-repositories

And what it wants to link to is what this is removing; there isn't a place to link to anymore. I would just remove the link altogether, except it's a changelog.

**Comment by Ch3LL** [comment]
I found out this was fixed here: https://github.com/saltstack/salt/pull/47005

and the `freebsd-upstream` ref was removed here: 04a80673a242a6e0229cdb6e8c786d188523659b

Are you okay to close here and I'll backport the #47005 PR

**Comment by astronouth7303** [comment]
Backporting the original is totally a-okay by me!

**Pull request closed without merging**
