### PR TITLE
Reduce fileclient latency by merging _file_hash and _find_file

### PR DESCRIPTION
**Pull request by ninja-**
### What does this PR do?

1. Creates new master function _file_hash_and_stat
(sadly that's backwards incompatible, which means you need to update your master before you update minions)
2. Changes fileclient.py to use one call to _file_hash_and_stat instead of calling _file_hash and then _find_file.

This reduces latency to access file's metadata in minion<-> master setup when they are in different datacenter - in my case the ping latency is 10ms.

This somehow added to closer to 40ms than 20ms when requesting file metadata from master.
This commit reduced our deploy times - 7 machines - from 27 seconds to 22 seconds, by cutting access times in half.
(both of these timings include my not-yet-finished ZeroMQ connection caching patch from #39338, which saves additional 50x50ms = 2500ms, around 50 re-connections per highstate with 50ms handshake time, as well as a the new WIP plugin loader)

There is still big room for improvement in near future - I'd like to add last modified dates to _file_list, update file list once when a job is requested, and then latency to check if file is up to date would be 0ms. 🙃 

Note: file_hash_and_stat was an already existing function in filesystem module, but wasn't hooked to the public API for some reason 😕 

### What issues does this PR fix or reference?

Related to #39338, though this is a seperate problem.

### Previous Behavior
For any requested file that is up-to-date in cache, _file_hash would be requested and then _file_find.

### New Behavior
For any requested file that is up-to-date in cache, only one API request _file_hash_and_stat would be send instead of two.

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by thatch45** [comment]
Looks good to me, good thinking @ninja-

**Comment by cachedout** [comment]
@terminalmage If you could swing by this one too, please.

**Comment by terminalmage** [comment]
No, please don't merge this. It was written that way for a reason. We can't just stat the file as it exists locally on the master, because in the case of gitfs (the only fileserver backend other than roots which supports mode preservation in Salt) we need to get the mode of the file from the git repository's metadata for that file. So, we need to query the fileserver backend, which is why the RemoteClient needs to run the ``_file_find`` master func to have it query the fileserver to return the file mode.

**Comment by ninja-** [comment]
@terminalmage it supports file chmods correctly, I doubt this could break gitfs backend

**Comment by terminalmage** [comment]
What supports file chmods? I don't understand.

**Comment by ninja-** [comment]
> ) we need to get the mode of the file from the git repository's metadata for that file

**Comment by ninja-** [comment]
It does exactly the same work look i.e. here https://github.com/saltstack/salt/blob/develop/salt/fileserver/__init__.py#L640

**Comment by ninja-** [comment]
If you are referring to https://github.com/ninja-/salt/blob/94c62388e792884cebc11095db20e3db81fa1348/salt/fileclient.py#L1278 that's only used when the url is local and without salt:// prefix

**Comment by ninja-** [comment]
> We can't just stat the file as it exists locally on the master, because in the case of gitfs (the only fileserver backend other than roots which supports mode preservation in Salt) we need to get the mode of the file from the git repository's metadata for that file. 

If that's really the case then the chmod should be preserved in master's cached file....

**Comment by ninja-** [comment]
@terminalmage I double checked and I guarantee you 100% that it's calling the same find_file function interally and returning it's stats from find_file(...)['stats'])

**Comment by terminalmage** [comment]
Yes, after looking at the full file, I can see that the ``os.stat()`` was being done for local files only. The stat logic is only being performed at this time for the mode preservation feature added in 2016.11.0 for file states.

Sorry for the misunderstanding, I misinterpreted the diff and thought you were getting the stats from the cached copy rather than the remote copy.

**Comment by ninja-** [comment]
👼

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by ninja-** [comment]
@cachedout ❤️

**Comment by twangboy** [comment]
@ninja- This PR breaks the state system on Windows. Could you take a look at it?
https://github.com/saltstack/salt/issues/39905

**Pull request merged**
