### PR TITLE
Disable tests on FreeBSD

### PR DESCRIPTION
**Pull request by krionbsd**
### What does this PR do?
Disable tests on FreeBSD

### CODE REVIEW

**Comment by waynew** [comment]
Why do we want to disable these tests on FreeBSD? Are they just irrelevant on that platform?

**Comment by krionbsd** [comment]
@waynew exactly, inotify/watchdog have very limited support on FreeBSD at this moment. I temporary disabled shell tests as FreeBSD uses csh as root shell.

**Review by waynew — CHANGES_REQUESTED** [review]
Should we change the message to indicate that? Like`"Skip on FreeBSD - does not yet have inotify/watchdog support"`?

**Comment by krionbsd** [comment]
@waynew that's a bit complicated, FreeBSD has kind of limited inotify support, it doesn't support working with symlinks, as well as directory notifications with `IN_MOVED_FROM` / `IN_MOVED_TO`, and some open/close notifications like `IN_OPEN` / `IN_CLOSE_NOWRITE`. Maybe the skipif like `Skip on FreeBSD - does not yet have full inotify/watchdog support` ?

**Review by waynew — APPROVED** [review]
👍 looks great, thanks!

I like to have a minimum, but complete amount of information available - that way when future Wayne/Kirill comes looking into these tests after we've learned that there's good inotify support on FreeBSD that we can say, "Oh! We need to re-enable these tests!"

Otherwise we just assume that they need to be skipped forever, or have to dig into why the heck we skipped them in the first place 🙃

**Pull request merged**
