### PR TITLE
Several fixes for RDS DB parameter group management

### PR DESCRIPTION
**Pull request by defanator**
### What does this PR do?

This PR provides improvements related to RDS DB parameter group management, in particular:

 - it is now possible to manage all the parameters in a group,
   without limiting to MaxRecords=100 (thanks to pagination);

 - update_parameter_group() now composes valid JSON payload,
   automatically substitutes boolean values to 'on' / 'off' strings;

 - parameter_present() now shows actual error message produced by
   ModifyDBParameterGroup API call.

### What issues does this PR fix or reference?

None that I'm aware of.

### Previous Behavior

Applying the following state does not actually do anything:

```
test db parameter group:
  boto_rds.parameter_present:
     - name: my-postgres94-pg
     - profile: {'region': 'us-west-2', 'keyid': 'xxx', 'key': 'yyy'}
     - db_parameter_group_family: postgres9.4
     - description: PostgreSQL 9.4 custom parameters
     - parameters:
       - synchronous_commit: off
       - log_min_duration_statement: 30000
       - rds.log_retention_period: 1440
       - work_mem: 16384
```

The reason is that none of the mentioned parameters are in the first 100 returned by `describe-db-parameters` API call:

```
$ aws rds describe-db-parameters --db-parameter-group-name my-postgres94-pg | fgrep ParameterName | nl | egrep '"synchronous_commit|"log_min_duration_statement|"rds.log_retention_period|"work_mem'
   105	            "ParameterName": "log_min_duration_statement", 
   142	            "ParameterName": "rds.log_retention_period", 
   167	            "ParameterName": "synchronous_commit", 
   204	            "ParameterName": "work_mem", 
```

### New Behavior

The above state applies successfully.

Also, errors are being reported correctly, e.g. in case of specifying `synchronous_commit: 0` we will get the following:

```
local:
----------
          ID: test db parameter group
    Function: boto_rds.parameter_present
        Name: my-postgres94-pg
      Result: False
     Comment: Parameter group my-postgres94-pg present.
              Failed to change parameters {'synchronous_commit': '0'} for group my-postgres94-pg:
              An error occurred (InvalidParameterValue) when calling the ModifyDBParameterGroup operation: Invalid parameter value: 0 for: synchronous_commit allowed values are: local,on,off
     Started: 05:33:03.424630
    Duration: 252.031 ms
     Changes:   
```

### Tests written?

No.

### CODE REVIEW

**Comment by cachedout** [comment]
Paging @saltstack/team-boto

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by ryan-lane** [comment]
+1

**Review by rallytime — APPROVED** [review]
Thanks!

**Comment by defanator** [comment]
@saltstack/team-boto @rallytime @cachedout will it be backported to 2016.11?

**Comment by rallytime** [comment]
@defanator Sure, we can backport this. Thanks for letting us know.

**Pull request merged**
