### PR TITLE
Update note around password field on user.present wrt Windows

### PR DESCRIPTION
**Pull request by ggiesen**
### What does this PR do?
Clarifies docs around password field behaviour on user.present on Windows

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by dnessett** [comment]
I agree that the language in the documentation for salt.states.user.present variables "password" and "hash_password" is confusing. I am coming at this from a linux perspective, not a windows perspective, so I think the problem is general. I would suggest changing the documentation as follows:

password - A password value to set for the user. For Linux, FreeBSD, NetBSD, OpenBSD, and Solaris, this may be either a cleartext password or a hash of the cleartext password. For Windows this must be a cleartext password. If the empty_password argument is set to True, then password is ignored. The treatment of this value depends on the value specified for hash_password.

hash_password - For Linux, FreeBSD, NetBSD, OpenBSD, and Solaris,  if this is set to True, hash the clear text password specified in variable password. Default is False.

**Comment by dnessett** [comment]
In my original comment I left off the note about how to generate the hash. After some discussion on https://app.slack.com, it might be useful to keep that note, but modify it to: For Linux, the hash can be generated in a number of different ways, e.g., using salt.modules.linux_shadow.gen_password() or shadow.gen_password ().

**Review by barbaricyawps — APPROVED** [review]
Thanks for your docs PR, @ggiesen !

This looks good to me. We'll also need a core member to verify it's technically accurate, but it seems pretty straightforward to me.

**Review by dmurphy18 — APPROVED** [review]

**Comment by Ch3LL** [comment]
@ggiesen did you see the feedback from @dnessett . Are you wanting to implement the feedback?

**Comment by ggiesen** [comment]
> @ggiesen did you see the feedback from @dnessett . Are you wanting to implement the feedback?

@Ch3LL @barbaricyawps sorry yes I'd like to implement @dnessett's feedback as we discussed it over Slack. I unfortunately haven't had the time to get back to it and I don't think I'll be able to until mid-March. So we have the choice as to whether to 1) merge as-is, and implement @dnessett's feedback in a separate PR; 2) have someone else write up the changes and I can quickly incorporate them, or 3) wait until I'm able to get back to it.

I tend to lean towards the first option as it clarifies the docs now (even if it's not as much as we want) and will help to get it into the 3006 release, but if anyone else feels strongly another way then I'm entirely open to that.

**Comment by Ch3LL** [comment]
Just following up here as it is that march time frame. Are you willing to follow up here @ggiesen ?

**Comment by barbaricyawps** [comment]
@ggiesen , just following up with you on this PR. Is there anything you need from us to help you with this PR?

**Pull request merged**
