### PR TITLE
Prevent reuse of file client if cachedir does not match

### LINKED ISSUE #60003: [BUG] salt-ssh support for extra_filerefs in Saltfile is broken
**Description**
  I use lots of map.jinjas with salt-ssh, as part of many formulas in my states git repo. Since the files are only imported I need to use extra_filerefs to include them all. I do this in my Saltfile. As of 3003 this doesn't work anymore. If I downgrade to 3002.6, it works.

I thought it might relate to this issue below, but reverting the patch didn't seem to fix it for me. Though I do question the conversion of the type of extra_filerefs from a list to a str. The only reasonable use of extra_filerefs is as a list. I have over 70 map.jinjas, and I need them all.

https://github.com/saltstack/salt/pull/59664/files

**Setup**
./Saltfile:

    salt-ssh:
      config_dir: .
      max_procs: 1
      ssh_wipe: True
      extra_filerefs:
        - salt://_grains/map.jinja

salt-formula/top.sls:

    {% from '_grains/map.jinja' import grain with context %}
    
    base:
      '*':
    {% if grain.fqdn == 'foo.bar.com' %}
        - base
    {% endif %}

**Steps to Reproduce the behavior**

    salt-ssh -i foo.bar.com state.highstate
    [ERROR   ] Rendering exception occurred
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/salt/utils/templates.py", line 497, in render_jinja_tmpl
        output = template.render(**decoded_context)
      File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/usr/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "<template>", line 1, in top-level template code
      File "/usr/lib/python3.9/site-packages/salt/utils/jinja.py", line 198, in get_source
        raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: _grains/map.jinja

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/salt/utils/templates.py", line 261, in render_tmpl
        output = render_str(tmplstr, context, tmplpath)
      File "/usr/lib/python3.9/site-packages/salt/utils/templates.py", line 542, in render_jinja_tmpl
        raise SaltRenderError(
    salt.exceptions.SaltRenderError: Jinja error: _grains/map.jinja
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/salt/utils/templates.py", line 497, in render_jinja_tmpl
        output = template.render(**decoded_context)
      File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/usr/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "<template>", line 1, in top-level template code
      File "/usr/lib/python3.9/site-packages/salt/utils/jinja.py", line 198, in get_source
        raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: _grains/map.jinja

    ; line 1

    ---
    {% from '_grains/map.jinja' import grain with context %}    <======================

    base:
      '*':
    {% if grain.fqdn == 'foo.bar.com' %}
        - base    
    [...]
    ---
    [ERROR   ] Unable to render top file: Jinja error: _grains/map.jinja
    foo.bar.com:

    Summary for foo.bar.com
    -----------
    Succeeded: 0
    Failed:   0
    -----------
    Total states run:    0
    Total run time:  0.000 ms

**Expected behavior**
It to include the map.jinja in the tgz, and not throw an error about not finding it.

**Versions Report**

    salt-ssh --versions-report
    Salt Version:
              Salt: 3003

    Dependency Versions:
              cffi: 1.14.1
          cherrypy: Not Installed
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 2.11.3
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: 1.1.3
           msgpack: 1.0.0
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.20
          pycrypto: 2.6.1
      pycryptodome: 3.10.1
            pygit2: Not Installed
            Python: 3.9.2 (default, Feb 20 2021, 00:00:00)
      python-gnupg: Not Installed
            PyYAML: 5.4.1
             PyZMQ: 22.0.3
             smmap: Not Installed
           timelib: Not Installed
           Tornado: 4.5.3
               ZMQ: 4.3.4

    System Versions:
              dist: fedora 33
            locale: utf-8
           machine: x86_64
           release: 5.11.10-200.fc33.x86_64
            system: Linux
           version: Fedora 33

### PR DESCRIPTION
**Pull request by marmarek**
### What does this PR do?
Complementary change to https://github.com/saltstack/salt/pull/62043, fixing final corner case in salt-ssh (using fileclient with mismatching cachedir)

### What issues does this PR fix or reference?
Fixes: #60003

### Previous Behavior
salt-ssh was looking for jinja includes in cache in /var/tmp/... on the master node.

### New Behavior
salt-ssh is looking for jinja includes in cache in /var/cache/salt (or wherever salt is configured for salt-ssh).

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by garethgreenaway** [comment]
@marmarek Thanks for the PR!  This change will require a test case and a changelog detailing the changes.  Thanks!

**Comment by marmarek** [comment]
> @marmarek Thanks for the PR! This change will require a test case and a changelog detailing the changes. Thanks!

Changelog pushed, but for the test I'll need some help. There is a test that (I think) already test this thing here: https://github.com/saltstack/salt/blob/master/tests/pytests/integration/ssh/test_state.py#L40-L68. But currently it passes because it ssh to localhost, so using paths from remote system locally works because they are the same system... I think using a fixture from `test_ssh_setup.py` (which seems to create a separate container) would be enough, but I'm not sure what's the best way to do it. I'll try some naive approach, but any hints are appropriate.

**Comment by marmarek** [comment]
Which job is supposed to run tests marked as "slow_test"?

**Comment by garethgreenaway** [comment]
@marmarek I'm looking at the changes for this PR and I only see the change to the test file?  Were there additional changes?

**Comment by marmarek** [comment]
> @marmarek I'm looking at the changes for this PR and I only see the change to the test file? Were there additional changes?

The "[DO NOT MERGE]" commit reverts the fix, to see if the test is effective. But it seems all "slow tests" are skipped in CI (or I can't find where it runs)". Any idea? The test makes sense only if it's going to be called...

**Comment by marmarek** [comment]
I think the centos-7 failure is unrelated to the changes in this PR.

**Comment by Ch3LL** [comment]
@marmarek  My fix here https://github.com/saltstack/salt/pull/63184 is still a work in progress, but can you give it a try?

I'm worried with this fix it will lead to slow down to re-generate the fileclient.

This should resolve the `state.highstate` call. I'm going to review other state calls to ensure we are also explicitly passing in context.

**Comment by Ch3LL** [comment]
Closing in favor of https://github.com/saltstack/salt/pull/63184

**Pull request closed without merging**
