### PR TITLE
Fix dunder virtual for runit execution module

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?

Uses 'get' to pull the 'init' grain. This was failing on os's where there is no 'init' grain.
### What issues does this PR fix or reference?

https://github.com/saltstack/zh/issues/900
### Previous Behavior

```
[ERROR   ] Exception raised when processing __virtual__ function for runit. Module will not be loaded 'init'
[WARNING ] salt.loaded.int.module.runit.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'runit', please fix this.
```
### New Behavior

no error
### Tests written?

NA

### CODE REVIEW

**Comment by cachedout** [comment]
Isn't the analog to *NIX init systems in Windows the Service Manager or something like that? Would it be better to just modify the grains so we get a value here?

**Comment by twangboy** [comment]
@cachedout Added the init grain for Mac and Windows. Reverted back to original code.

**Comment by cachedout** [comment]
Perfect. Thanks.

**Comment by vnitinv** [comment]
Is this releated. getting below error on latest code in github

 sudo salt-proxy --proxyid=CPE1 start
[ERROR   ] Exception raised when processing __virtual__ function for runit. Module will not be loaded 'init'
[WARNING ] salt.loader.192.168.17.5.int.module.runit.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'runit', please fix this.

**Comment by twangboy** [comment]
I dont' think this is related. @cro?

**Pull request merged**
