### PR TITLE
Allow minions to return job information to any configured master

### PR DESCRIPTION
**Pull request by sbrennan4**
### What does this PR do?

This PR introduces a new minion configuration option, `master_return_strategy`. Can be `source` or `any`. The default of `source` preserves the current behavior, namely, the minion will only attempt to return the job results to the master that sent the job. If set to `any`, then the minion will first attempt to return the job results to the master that sent the job. If that fails then the minion will attempt to return the job results to the other configured masters, one by one, until successful or the master list has been exhausted. `master_alive_interval` must also be set. This is used to keep track of which masters are currently connected.

### Previous Behavior

When a master becomes unavailable after sending a job but before receiving the return information, that return info will never make it back to the masters. If relying on `master_job_cache` or `event_returns` on the master side then the job return information is lost forever.

### New Behavior

When the initiating master becomes unavailable after firing a job to a minion then the minion will attempt to return the job information to another configured master.

### Tests written?

Hoping current tests are sufficient.

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by doesitblend** [comment]
ZD-3445

**Comment by cro** [comment]
This PR is much appreciated!

Two things--there is a test failure on Windows 2016.  Second, we do need test cases for this new feature.  Thanks!

**Comment by sbrennan4** [comment]
Thanks @cro, looks like all the tests are passing after updating the branch although I can't see what codeclimate is unhappy about. What kind of test case are you looking for here? I don't see anything similar in the current code base. Would you mind pointing me in the right direction?

**Comment by cro** [comment]
@sbrennan4 let me see if I can find an example...

**Comment by sbrennan4** [comment]
@cro any luck finding an example?

**Comment by Ch3LL** [comment]
FYI I migrated this PR from develop to neon to ensure it is included in the upcoming neon release. Let me know if this caused any issues. Thanks


also bump @cro

**Comment by mattp-** [comment]
can we hold off on merge here until tests are added?

**Comment by DmitryKuzmenko** [comment]
I like this change. Just one thing I have to say: currently I'm working on the multimaster integration tests infrastructure. @sbrennan4 I hope you'll be ok to wait until it will be ready and write a test for this change before we'll merge it.

**Comment by sbrennan4** [comment]
@DmitryKuzmenko thanks for the update. I'm ok with waiting.

**Comment by DmitryKuzmenko** [comment]
@sbrennan4 can we add a test for this now? You can find examples in `tests/multimaster` directory. Master disconnect could be simulated with iptables as it's done for `tests/multimaster/minion/test_event.py`. Feel free to ask questions.

**Comment by DmitryKuzmenko** [comment]
Also could you please rebase your PR to `master` branch?

**Comment by sbrennan4** [comment]
@DmitryKuzmenko thanks for the update. One question, I would like to test both values for this option so does the test suite provide support for setting minion_opts dynamically?

**Comment by DmitryKuzmenko** [comment]
@sbrennan4 at this moment it should be okay to statically change the config of the second minion in multimaster environment.
But that's a good point, we currently have no good way for integration testing dynamic configurations.
@saltstack/team-core  do anyone have better ideas?

**Comment by dwoz** [comment]
@sbrennan4 @DmitryKuzmenko This needs to be rebased to the `master` branch.

**Comment by sagetherage** [comment]
@sbrennan4 can you rebase this one?

**Comment by sagetherage** [comment]
or @mattp- can you help here?

**Comment by sbrennan4** [comment]
https://github.com/saltstack/salt/pull/55907 - easier to create a new PR than it is to rebase.

**Pull request closed without merging**
