### PR TITLE
Verify password

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?
`shadow.verify_password`:
Adds a new function to `win_shadow.py` called `verify_password`. This function attempts to log on with the supplied username and password. If it is successful, it returns True. If it fails to login, it checks if the account was locked as a result of the attempt. If it is locked, it unlocks the account and returns False.

`user.present`
Uses the new `verify_password` function to detect the status of the password for the state so that it behaves similar to other operating systems that allow you to compare a hash.

Adds some tests

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/29867

### Previous Behavior
There was no way to tell if the password in user.present was already set

### New Behavior
Now we can only set the password if it is incorrect

### Tests written?
Yes

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by damon-atkins — CHANGES_REQUESTED** [review]
I do not think having the state check the password like this is a good idea.   In large companies these audit events are look at and reported on and investigated.  If states are run often like every 10 minutes you giving someone an opportunity to try passwords, and have the fail count reset to 0, and then try again.

**Comment by twangboy** [comment]
@damon-atkins The only time this would cause a `failed logon audit event` would be if the password it's checking is wrong. But that would then cause salt to change the password. I guess if you ran the state every 10 minutes with `test=True` you would see the `failed logon audit events` every time... assuming the password is wrong.

The `failed logon attempt counter` increments each time. There's no way to reset that. Once you reach the failed attempt limit, the account is locked and salt will unlock it. I believe that resets the failed logon attempt counter. The counter is also reset when the `logon attempt timer` reaches it's limit, which is usually 30 minutes on enterprise systems, I believe.

I couldn't find any other way to validate a Windows password without logging in and triggering these events. Strangely, this is Microsofts recommended method for validating credentials.

https://support.microsoft.com/en-us/help/180548/how-to-validate-user-credentials-on-microsoft-operating-systems

Do you have any suggestions on how to better approach this? Should we let the account get locked out if someone runs the state with `test=True` 3 times within 30 minutes?
Or...
Do we continue as we are and just set the password each time the state is run (which has its own problem of constantly updating the password changed date)? I know there are folks a lot smarter than I am. I'm open to suggestions.

**Comment by damon-atkins** [comment]
I suppose if salt only resets failed logon when it needs to change the password is ok. And their are no false positives.  i.e the account is locked, therefore the login fails, so salt mistakenly resets the password.   ????

**Comment by twangboy** [comment]
@damon-atkins You're right... let me see what happens with a locked account.

**Comment by twangboy** [comment]
@damon-atkins So, apparently, you can't verify the password at all if the account is locked. It will always return account locked. That probably makes sense from a security perspective. So, I set it up to raise a CommandExecutionError if the account is locked.

The others I tested returned `ERROR_LOGON_FAILURE` if the password was incorrect. Otherwise, they return their respective errors.

**Review by damon-atkins — APPROVED** [review]
Approved based on the change being made.

**Pull request merged**
