### PR TITLE
Remove quadratic behaviour from postgres.role_get

### PR DESCRIPTION
**Pull request by ferringb**
See #35070; in #20980, role_get was modified so that it constantly re-asked
the DB for what roles existed.  Caching should exist, but the intent isn't bad-
however the implementation was such that every single role required another
psql invocation.  If you're provisioning 100 users, this gets painfull quickly
since it's quadratic.

Instead, modify the "collect all users" query to pull role membership,
converting role_get back down to a single query.  The syntax used should be
compatible at least back to postgres 8.3 (array_ag usage specifically).

In terms of performance difference, with this change, a provisioning for
my local setup for 102 users takes under a minute- less than that, but my
test case has unrelated states.  Without this change, it takes well over 30
minutes (exact time, I don't know- I gave up waiting on it).

### CODE REVIEW

**Comment by ferringb** [comment]
Unless I'm missing something, the various build tests you've got wired there all look fairly broke- and not by my change.

**Comment by garethgreenaway** [comment]
Looks like there is some cross over with #45966 that might require a rebase depending on which is merged first.

**Review by garethgreenaway — APPROVED** [review]

**Comment by rallytime** [comment]
Hi @ferringb - I know there are several test failures in the builds that are not related to your change, there are two test failures that are:
- unit.modules.test_postgres.PostgresTestCase.test_user_exists
- unit.modules.test_postgres.PostgresTestCase.test_user_list

Can you take a look at those, please? Thanks!

**Comment by rallytime** [comment]
@ferringb Just a bump on the request above. :)

**Comment by rallytime** [comment]
Since we haven't heard back here, I am going to close this PR. We will happily reopen this if traction picks up again on this change. Thanks!

**Pull request closed without merging**
