### PR TITLE
Win_license module update

### PR DESCRIPTION
**Pull request by jeffclay**
… win_license module

### What does this PR do?
Adds functions for more windows license management tasks and removes hard coded file paths.

### New Behavior
Added feature to manually set a KMS host server.
Added feature to manually set the KMS product key based on the OS version.
Added feature to remove product key from registry.
Added feature to rearm the existing license.
Added feature to report the type of license currently installed.
Changed all hard paths to slmgr.vbs to use the systemroot environment variable to allow the code to be more accepting of all types of installations.

### Tests written?
Was tested for Windows 7 Pro, Windows 7 Enterprise, Windows 10 Enterprise and Windows 10 Pro. Those are the only salted systems in my environment.

### CODE REVIEW

**Comment by jeffclay** [comment]
would someone please point out what i did wrong? this code worked fine in production on 58 windows minions today from a centos master all 2016.3.

**Review by cachedout — CHANGES_REQUESTED** [review]
Hi @jeffclay 

There are a few lint errors here: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/7964/violations/file/salt/modules/win_license.py/

Could you please resolve these before we merge this? Let me know if I can help. Thanks!

**Comment by jeffclay** [comment]
@cachedout I reviewed the errors you listed. I'm new to this, but in my opinion, those are not errors with the code. It seems that the test is expecting a hard coded file path where I have placed system environment variables. The variable used is supported in all salt supported Windows operating systems. From my experiences, it is always best to code with an environment variable rather than a hard coded path because everyone might not have installed windows on C:\ or their Windows directory might be named something else due to OS upgrades, etc. Using the environment variable %systemroot% will always point to the appropriate location that contains the "System32" directory.

**Comment by cachedout** [comment]
Hi @jeffclay I think you might be misinterpreting the warnings here. They're talking about anomalous backslashs in strings. If you just prefix the strings with an `r` then the backslashes won't be interpreted by the parser and will be seen as literal strings. For example:

Wrong (on line 60):

`cmd = r'cscript ' + os.path.expandvars("%systemroot%") + '\System32\slmgr.vbs /ipk {0}'.format(product_key)`

Fixed:

`cmd = r'cscript ' + os.path.expandvars("%systemroot%") + r'\System32\slmgr.vbs /ipk {0}'.format(product_key)`  <--Note the `r` added to the string beginning with `\System32..`

**Comment by jeffclay** [comment]
ah, ok. only the strings with back-slashes should be pre-pended, not all strings right?

**Comment by cachedout** [comment]
@jeffclay Correct. The link to the lint report lists them all.

**Comment by jeffclay** [comment]
closing this to make a new one. not really sure what the gitdesktop app was doing adding those other files that i hadn't touched to my commit...

**Pull request closed without merging**
