### PR TITLE
A quick fix for Cache has no 'list' attribute.

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
### What does this PR do?
Fixes the cache test failure in @rallytime 's merge forward 2016.11 into develop #40494 

### What issues does this PR fix or reference?
#40494 

### Tests written?
No

### CODE REVIEW

**Review by techhat — APPROVED** [review]

**Review by rallytime — COMMENTED** [review]
Oh! Thanks for grabbing this @DmitryKuzmenko . I am wondering if this is a good time to use the `salt.utils.alias_function` call instead?

**Comment by rallytime** [comment]
I just spoke with @cachedout and this is fine as-is. Thanks again @DmitryKuzmenko!

**Review by rallytime — APPROVED** [review]

**Comment by DmitryKuzmenko** [comment]
@rallytime anyway I want to remove those aliases and replace the `list` with `ls` everywhere.
Thank you too!

**Comment by DmitryKuzmenko** [comment]
@techhat hm... I thought that the `list` name that I've introduced in the cache wasn't a good choice for a module function because it crosses with the global `list` constructor. We have a workaround, but I thought it's good idea to rename to something not conflicting at all.

**Comment by techhat** [comment]
@DmitryKuzmenko I understand what you're saying, but that's something that we addressed years ago using the `__func_alias__` `dict`.

**Comment by DmitryKuzmenko** [comment]
@techhat ok, let it be as is then.

**Pull request merged**
