### PR TITLE
Add execution module and state module to base64 encode/decode files

### PR DESCRIPTION
**Pull request by whiteinge**
Reopening #19935 with less lofty goals...

### CODE REVIEW

**Comment by jfindlay** [comment]
@whiteinge, will you add `.. versionadded:: Boron` to the new functions?  Thanks.

**Comment by whiteinge** [comment]
Doh. Old branch. Thanks for the catch.

**Comment by jfindlay** [comment]
Cool, thanks.

**Comment by basepi** [comment]
Go Go Jenkins!

**Pull request merged**
