### PR TITLE
Refactored win_pkg to get all installed software as well as remove the win32* 3rd party module dependencies

### PR DESCRIPTION
**Pull request by belvedere-trading-user**
Refactored win_pkg to get all installed software as well as remove the win32\* 3rd party module dependencies

Motivation:
I was not be able to get all installed software on both the 32bit and Wow64 registries. The problem is that the win32api module automatically redirects to the registry hive of the platform being run (Wow64 or 32 bit).
There was no way that I was able to find a way to prevent this from happening.

More information can be found here:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa384232(v=vs.85).aspx

Furthermore, depending on if a program is 64 bit or 32 bit, when it is installed the program will be entered
in the appropriate registry hive. Thus, the win32api module will not get all installed software.

Implemantation/Fix:
The built in _winreg module allows for opening either the 64 or 32 bit hive, thus allowing for all installed software to be reported.
Furtheremore, using _winreg allows for the removal of third party dependencies as it is a built-in module for python.

### CODE REVIEW

**Comment by cachedout** [comment]
@twangboy Please have a look here and merge this when you're ready.

**Comment by DennisHarper** [comment]
@twangboy I have a new patch for this commit that fixes the history (takes out "fix for: saltstack#27373" and squashes all of the other patches into one commit). 
I can re-write history for this branch, or issue a new pull request with the cleaner history. How do you guys prefer that we go about this?

Also, I am not sure why the Centos 7 build failed. Is that something on my side... it looks like some type networking error with the job itself, but again I am not sure.

**Comment by rallytime** [comment]
@belvedere-trading You're correct. That test failure is not related to this PR. 

However, it looks like your "fix for: saltstack#27373" commit is still present in this pull request, as the changes to `setup.py` are still present.

**Comment by rallytime** [comment]
I've grabbed the relevant commits in #27694, which has now been merged, which supersedes this PR so I will close this. Thanks for your work here @belvedere-trading! It's much appreciated. 

@twangboy Tested your commits and it looks good! :D

**Pull request closed without merging**
