### PR TITLE
Adding options to be able to connect the Minion using a certain source IP / port

### PR DESCRIPTION
**Pull request by mirceaulinic**
### What does this PR do?

Adds a couple of options necessary to select a different source IP / port combination when the Minion connects to the Master:

- ``source_interface_name``
- ``source_address``
- ``source_ret_port``
- ``source_publish_port``

### What issues does this PR fix or reference?

#38744

### Previous Behavior

Unable to use a specific IP address / interface / port to connect to the Master.

### New Behavior

Can connect to the Master using a specific IP address / interface / port. 

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by cachedout — APPROVED** [review]
I have been wanting to do this for a long time and this is perfectly implemented. Thanks, @mirceaulinic !

**Comment by mirceaulinic** [comment]
Thanks @cachedout - glad to hear that!

**Comment by rallytime** [comment]
@mirceaulinic This is neat!

Unfortunately, it looks like the test suite doesn't like the changes as they sit. When attempting to run the first tests, this stack trace occurs:
```
16:59:13 16:59:12,979 [tests.support.parser                       :66  ][ERROR   ] An un-handled exception was caught by salt-testing's global exception handler:
16:59:13 SaltClientError: 'master_ip'
16:59:13 Traceback (most recent call last):
16:59:13   File "/testing/salt/client/__init__.py", line 338, in run_job
16:59:13     **kwargs)
16:59:13   File "/testing/salt/client/__init__.py", line 1801, in pub
16:59:13     master_uri=master_uri)
16:59:13   File "/testing/salt/transport/__init__.py", line 53, in factory
16:59:13     return ReqChannel.factory(opts, **kwargs)
16:59:13   File "/testing/salt/transport/client.py", line 25, in factory
16:59:13     sync = SyncWrapper(AsyncReqChannel.factory, (opts,), kwargs)
16:59:13   File "/testing/salt/utils/async.py", line 60, in __init__
16:59:13     self.async = method(*args, **kwargs)
16:59:13   File "/testing/salt/transport/client.py", line 108, in factory
16:59:13     return salt.transport.zeromq.AsyncZeroMQReqChannel(opts, **kwargs)
16:59:13   File "/testing/salt/transport/zeromq.py", line 133, in __new__
16:59:13     obj.__singleton_init__(opts, **kwargs)
16:59:13   File "/testing/salt/transport/zeromq.py", line 193, in __singleton_init__
16:59:13     log.debug('Connecting the Minion to the Master URI (for the return server): %s', self.master_uri)
16:59:13   File "/testing/salt/transport/zeromq.py", line 210, in master_uri
16:59:13     return _get_master_uri(self.opts['master_ip'],
16:59:13 KeyError: 'master_ip'
```
Can you take a look? Can you also address the code climate error?

**Comment by mirceaulinic** [comment]
Hi @rallytime - sure, I will take a look. But I'm pretty sure the logic for `master_ip` hasn't been changed at all, as you can see in https://github.com/saltstack/salt/pull/44642/files#diff-b5732eecf0273ccf6a96e1c720198dc6. Let me investigate this further...

**Comment by mirceaulinic** [comment]
Also, I don't see how this codeclimate is any related to my changes? https://codeclimate.com/github/saltstack/salt/pull/44642

**Comment by mirceaulinic** [comment]
No, it really doesn't make sense: the `master_uri` is build using `master_ip` and `master_port`, so these two options must always be available in the opts: https://github.com/saltstack/salt/blob/develop/salt/minion.py#L217-L218, unless there's a hack in the tests that allowed them to pass somehow.

**Comment by mirceaulinic** [comment]
@rallytime @cachedout I pushed this commit: https://github.com/saltstack/salt/pull/44642/commits/b7df7e75cf28cadf00c818d0838fb7ad613d79c7 hope this fixes the tests, though I still can't see a way the `master_ip` is not in the opts. If that's still not alright, please let me know what's the way to go. Thanks!

**Comment by mirceaulinic** [comment]
I think the tests good to me now - @rallytime would you be able to confirm please?

**Comment by rallytime** [comment]
@mirceaulinic Ah, unfortunately there is a merge conflict here. Can you resolve that? Then I can swing back around and see how the tests are doing.

**Comment by mirceaulinic** [comment]
@rallytime I fixed the document conflict, thanks.

**Review by rallytime — APPROVED** [review]

**Comment by mirceaulinic** [comment]
Thanks for merging this.
@rallytime @cachedout I have tested these changes, though I'd like to ask you to check them manually too - I'd feel really bad if I introduced any bugs.

**Comment by Ch3LL** [comment]
@mirceaulinic thanks for bringing this to our attention I've add this issue https://github.com/saltstack/salt/issues/44870 to track adding tests for this. This has been added to the tracking of our QA Test plan for oxygen so will be completed sometime after we branch for oxygen.

**Comment by mirceaulinic** [comment]
Alright @Ch3LL - If you can guide me little where to add more tests for this, I'd be happy to try adding some. I actually wanted to add them to this PR, but I just don't have enough experience with the Salt test infra, sorry! :D

**Comment by Ch3LL** [comment]
@mirceaulinic apologies on missing this ping. Our testing documentation is here: https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html

Since my response is delayed i was going to try to attack writing some unit tests for this today and early next week so we can get this tested for oxygen.

**Pull request merged**
