### PR TITLE
Windows Registry Unicode Support and PY2 character encoding (module.reg)

### PR DESCRIPTION
**Pull request by damon-atkins**
### What does this PR do?

salt module reg (reg.py)
- Start at PY3 support, however not tested against PY3
- Change to Unicode including from **future** import unicode_literals
- If PY2 converts all parameter input unicode to local encoding i.e. Unicode to String
- If PY3 stays as Unicode as PY3 uses Windows Wide Char
- Supports non-asiic characters i.e. > 126
- All output is Unicode, before most of it was Unicode output
- Added a safty check to recursive delete to try and prevent a mistake like removing all of SOFTWARE
- Fixed all the pylint errors
- add _ prefix to internal functions
- Provided unit test see reg_win_test.py

reg_win_test.py
- All tests currently make real changes to the registry
- All changes are performed under SOFTWARE\SaltStackTest under HKEY_LOCAL_MACHINE and HKEY_CURRENT_USER
- Their is still room for more tests to be developed
- Test target the new Unicode features of reg.py e.g. Copyright, Tradmark and Register characters
- General the values set in the registy contain date/time and then checked that they are the current date/time to make sure they are not left over from old tests
### What issues does this PR fix or reference?

*Current version did not support unicode input
*Output was mostly unicode, now all output should be unicode
*No Unit tests
### Previous Behavior

Mixed Unicode Support
Not reliable Unicode Support
No PY3 support
### New Behavior

PY3 Support (not tested)
Handles unicode parameter input.
Outputs only unicode
### Tests written?

Yes

### CODE REVIEW

**Comment by damon-atkins** [comment]
FYI @hrumph @twangboy, @thebigbear, @UtahDave @jfindlay

**Comment by rallytime** [comment]
@damon-atkins It looks like one of the tests is failing from this change. Can you take a look?

**Comment by damon-atkins** [comment]
How do I configure a test to only run on Windows, as it does not make sense for it to run on Unix/Linux as it has since  _wnreg module does not exist on Unix/Linux

ImportError: Failed to import test module: unit.modules.reg_win_test
Traceback (most recent call last):
  File "/testing/tests/unit/modules/reg_win_test.py", line 15, in <module>
    import _winreg
ImportError: No module named _winreg

**Comment by damon-atkins** [comment]
Thanks for Merging it.

**Pull request merged**
