### PR TITLE
install python3-venv on ubuntu 18.04

### PR DESCRIPTION
**Pull request by Akm0d**
### What does this PR do?
Installs python3-venv to ubuntu 18.04 for kitchen tests

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/52076

### Tests written?

N/A

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by garethgreenaway — APPROVED** [review]

**Review by dwoz — CHANGES_REQUESTED** [review]
Good job tracking this down. This may fix #52076 for you when running kitchen locally however:

- It should be noted that our Jenkins builds don't use this `.kitchen.yml` file. Instead, we use the kitchen configs found in [sre-jenkins](https://github.com/saltstack/sre-jenkins/blob/master/states/services/jenkins-node/kitchen-install.sls)

- Dependencies like this are installed via the states in [salt-jenkins](https://github.com/saltstack/salt-jenkins), if needed it should be installed from a state rather than kitchen's provision command. The reason is too keep with the established convention and keep things as kitchen agnostic as possible.

- It's probably worth syncing with @s0undt3ch on this since it may not be an issue anymore once the nox changes get merged.

**Comment by Akm0d** [comment]
re-run full all

**Comment by Akm0d** [comment]
re-run full all

**Comment by Akm0d** [comment]
re-run full all

**Pull request closed without merging**
