### PR TITLE
Add "osmajorrelease" grain (2016.3)

### PR DESCRIPTION
**Pull request by isbm**
Backport of https://github.com/saltstack/salt/pull/34671

### CODE REVIEW

**Comment by isbm** [comment]
@cachedout OK, I am keeping string type here, as per https://github.com/saltstack/salt/pull/34671#issuecomment-233372779

**Comment by cachedout** [comment]
Thanks for keeping the string type. I think this is the best approach for the point release.

**Comment by cachedout** [comment]
@isbm If you'd grab that lint error then we'll be good to merge this: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/3445/violations/file/salt/grains/core.py/

**Comment by isbm** [comment]
@cachedout done.

**Pull request merged**
