### PR TITLE
Cleanup and performance tweaks

### PR DESCRIPTION
**Pull request by jacksontj**
The caching the auth object in channels saves ~200ms in my testing for a salt-call test.ping (with minion and master local) or ~7s on a saltutil.sync_all.

Also found a bug in the master where an improperly encrypted minion request will cause the master to just return empty string-- thereby misleading the minion.

### CODE REVIEW

**Comment by thatch45** [comment]
These all look ok, I am re-running tests

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Nice!

**Comment by jacksontj** [comment]
@thatch45 @rallytime The tests have been running for ~3 hours... seems a bit long ;)

**Comment by rallytime** [comment]
Thanks for letting us know @jacksontj. Seems something is up with Jenkins again. I've stopped the latest run and will trigger a new one shortly.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
This looks about ready! Those test failures are due to something else we are hunting down. Lemme review it one more time

**Comment by cachedout** [comment]
This has broken the test suite, I'm afraid. runtests.py now produces:

```
Traceback (most recent call last):
  File "./runtests.py", line 411, in <module>
    main()
  File "./runtests.py", line 396, in main
    status = parser.run_integration_tests()
  File "./runtests.py", line 316, in run_integration_tests
    with TestDaemon(self):
  File "/home/mp/Devel/salt/tests/integration/__init__.py", line 185, in __enter__
    self.start_zeromq_daemons()
  File "/home/mp/Devel/salt/tests/integration/__init__.py", line 246, in start_zeromq_daemons
    sub_minion = salt.minion.Minion(self.sub_minion_opts)
  File "/home/mp/Devel/salt/salt/minion.py", line 626, in __init__
    opts['environment']
  File "/home/mp/Devel/salt/salt/pillar/__init__.py", line 93, in compile_pillar
    timeout=7200,
  File "/home/mp/Devel/salt/salt/transport/__init__.py", line 287, in crypted_transfer_decode_dictentry
    aes = key.private_decrypt(ret['key'], 4)
  File "/usr/lib/python2.7/dist-packages/M2Crypto/RSA.py", line 63, in private_decrypt
    return m2.rsa_private_decrypt(self.rsa, data, padding)
M2Crypto.RSA.RSAError: oaep decoding error
```

**Comment by cachedout** [comment]
Looks like something to have to do with the sub minion starting up.. odd.

**Comment by thatch45** [comment]
bah! Why did the tests pass on Jenkins for the PR then? But yes, that is a serious break!

**Comment by jacksontj** [comment]
I'm looking into it now

**Comment by cachedout** [comment]
@thatch45 Not sure. It's definitely broken now though. Jenkins was wedged solid. @jacksontj Thanks as always for looking into it. Much appreciated.

**Comment by jacksontj** [comment]
@thatch45 @cachedout fixed

**Pull request merged**
