### PR TITLE
Add support for mongod indexes in mongo_future_return

### PR DESCRIPTION
**Pull request by Lothiraldan**
This will greatly improve performances as we use only a subset of fields to filter on in queries.

### CODE REVIEW

**Comment by Lothiraldan** [comment]
Any reason this commit is not available either on 2014.7.4 or 2015.2.0?

**Comment by rallytime** [comment]
@Lothiraldan Since you made the change against the `develop` branch, that's the only place it lives now. We can backport this to an older branch though. I'll do that now.

In the future, feel free to submit bug fixes to the "oldest supported release branch" (currently that is 2014.7) that the bug occurs on. We will then merge it forward from 2014.7 into 2015.2, and then 2015.2 into develop. You can read more about our process [here](http://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch)

**Comment by Lothiraldan** [comment]
Ok great, I should have missed this documentation page the last time I checked the contribution guide, thank you very much for pointing me to this page.

**Comment by rallytime** [comment]
No problem! Thanks for contributing!

**Comment by rallytime** [comment]
Ok, the code is a bit different in this file in 2014.7 than 2015.2 and develop, so I backported the change to 2015.2. It should make it into the 2015.2.0 release. Thanks again!

**Pull request merged**
