### PR TITLE
Add more tests to cron.

### PR DESCRIPTION
**Pull request by steveno**
### What does this PR do?
Adds more tests to the cron module

### What issues does this PR fix or reference?
None.

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by rallytime** [comment]
Thanks again for this @steveno! This is great!

There's one lint error that needs to be fixed, but otherwise this looks good. Can you fix that really quickly?
```
19:56:24 ************* Module tests.unit.modules.test_cron
19:56:24 tests/unit/modules/test_cron.py:17: [W1699(incompatible-py3-code), ] Incompatible Python 3 code found. Proposed fix:
19:56:24  # Import Salt libs
19:56:24  import salt.modules.cron as cron
19:56:24  from salt.ext.six.moves import builtins, StringIO
19:56:24 +from salt.ext.six.moves import range
```
For PY2/PY3 compatibility, you just need to the `range` function from `six` as that last line states.

**Comment by steveno** [comment]
@rallytime I added `range` from the `six` library as requested. I'm sure this isn't the right place to ask this, but how did you get that output? When I run `pylint` as shown [here](https://docs.saltstack.com/en/latest/topics/development/conventions/style.html#pylint-instructions) it never looks like that.

**Comment by rallytime** [comment]
That's fine to ask that here. :)

I grabbed that output from the `Console Output`, which is on the left-hand side of the pylint output: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/22999/

Here's the output from the job that failed before your fix: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/22965/console

**Comment by steveno** [comment]
@rallytime Thanks for the explanation. I suppose this is ready for merge whenever.

**Review by rallytime — APPROVED** [review]

**Pull request merged**
