### PR TITLE
Fix state "svn.latest" diff output in test mode

### LINKED ISSUE #41022: State svn always test against latest revision with test=True
Let's say I have this state:
```
hubsession-zope-{{ instance }}-appy:
  svn.latest:
    - name: https://svn.forge.pallavi.be/appy
    - target: /mnt/data/{{ instance }}/lib/python/appy
    - rev: 34
```
If I run the highstate with test=True, it will test against the latest revision available.

### PR DESCRIPTION
**Pull request by sebw**
### What does this PR do?

It fixes incorrect returned info from `svn.latest` when run in test mode.

### What issues does this PR fix or reference?

It fixes https://github.com/saltstack/salt/issues/41022

### Previous Behavior

Problematic scenario:

- current checked out code on minion is at revision 1
- we define the desired revision `rev: 2` in our svn.latest state
- latest revision on the SVN repository has already reached revision 3

In test mode, the output would show the diff between revision 3 and "working copy" (1), instead of showing a diff between revision 1 and 2:

```
----------
          ID: svn_repo
    Function: svn.latest
        Name: file:///home/svn
      Result: None
     Comment: Index: /var/www/svn/README.md
              ===================================================================
              --- /var/www/svn/README.md	(revision 3)
              +++ /var/www/svn/README.md	(working copy)
              @@ -1,3 +1,3 @@
               initial import
               -------------
              -rev 3
              +rev 1
     Started: 22:11:01.241382
    Duration: 18.837 ms
     Changes:
```

This output presents two other problems:

- diff is confusing giving the idea that text "rev 1" will be added to README.md while it is already there
- output is not giving an idea of the current checked out revision, just "working copy"

The proposed output:

```
----------
          ID: svn_repo
    Function: svn.latest
        Name: file:///home/svn
      Result: None
     Comment: Index: /var/www/svn/README.md
              ===================================================================
              --- /var/www/svn/README.md	(revision 1)
              +++ /var/www/svn/README.md	(revision 2)
              @@ -1,3 +1,3 @@
               initial import
               -------------
              -rev 1
              +rev 2
     Started: 22:11:01.241382
    Duration: 18.837 ms
     Changes:
```

This output is better:

- it compares against the desired revision
- it shows current version number instead of "working copy"
- diff is actually showing what will happen when state is run

What was the problem:

`-r HEAD` was hardcoded in the test block section instead of comparing with `-r current_rev:new_rev`.

### New Behavior

svn.latest now compares current code against the desired revision.

### Tests written?

No

### Additional note

This is my first PR, I've read the guidelines, but please bear with me if I made an obvious mistake :)

### CODE REVIEW

**Comment by sebw** [comment]
@cachedout here's the new MR based on the latest develop from a couple of minutes ago. Hope Jenkins tests will complete now :)

**Comment by cachedout** [comment]
@sebw This looks much better. We do have one failing svn test though: https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/11630/testReport/junit/unit.states.test_svn/SvnTestCase/test_latest/

**Comment by cachedout** [comment]
@sebw Did you see my comment above about the failing test?

**Comment by sebw** [comment]
Yes, but I don't know what to do from that and don't really understand the failure as it is not really verbose. It refers to c://salt, so I assume the test is failing on a Windows node?

I git blamed the test case and this part was written two years ago and the author was somewhat inactive on Github in a while. I would need help to better understand why this test case fails. On my end I could only test on Redhat/Centos 7.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Hi @sebw 

The test just needs to be adjusted a bit. Try this patch:

```
diff --git a/tests/unit/states/test_svn.py b/tests/unit/states/test_svn.py
index d174749e98..4f430d9540 100644
--- a/tests/unit/states/test_svn.py
+++ b/tests/unit/states/test_svn.py
@@ -53,7 +53,8 @@ class SvnTestCase(TestCase, LoaderModuleMockMixin):
                 mock = MagicMock(side_effect=[False, True])
                 with patch.object(os.path, 'exists', mock):
                     mock = MagicMock(return_value=True)
-                    with patch.dict(svn.__salt__, {'svn.diff': mock}):
+                    info_mock = MagicMock(return_value=[{'Revision': 'mocked'}])
+                    with patch.dict(svn.__salt__, {'svn.diff': mock, 'svn.info': info_mock}):
                         mock = MagicMock(return_value=["Dude"])
                         with patch.object(svn, '_neutral_test', mock):
                             self.assertListEqual(svn.latest("salt",
```

**Pull request merged**
