### PR TITLE
Fixed bug and reverted some unnecessary changes where .six.itervalues was applied 

### PR DESCRIPTION
**Pull request by SmithSamuelM**
The core.py SaltLoadPillar behavior was selecting a master via an iterator with next(). This was wrong as the iterator was
being recreated each time the behavior ran so it would always select the first one. The behavior  already had code to
select a master either randomly if opt random_master or to select the first one if not. So removed the next (iterator).

Also throughout the code many for loops the had .values() were replaced with six.itervalues().  This is a questionable choice because the need for six only arises iff the python2 code is using .itervalues() not .values().   .values() in a for expressing is already python2 and python3 compliant. So at the risk of making the code much less readable, six.itervalues() was used but not needed.

One could argue that the original python2 code that used .values() could be refactored to use .itervalues() which would then require six.itervalues() for python 2 and 3 compliance. But there is no statistically significant advantage in performance to using itervalues over values on a dict when iterated in a for loop. Python already optimizes the code under the hood.

timeit runs in python 2.7 of

for v in x.values():
   pass

vs

or v in x.itervalues():
   pass

are statistically the same (sometime one if faster than the other)

So refactoring to use itervalues actually makes the code much less readable and requires using six to get python2to3
compatibility. 

It should be the case in general to use .values() as this already works performantly in both python2 and 3 

 (at least in python2.7, I didn't test python2.6)

### CODE REVIEW

**Comment by thatch45** [comment]
@s0undt3ch

**Comment by s0undt3ch** [comment]
First, sorry for breaking your code @SmithSamuelM, though, for me to add a `next()`, there should be `next()` before, or selecting the first object from a list(`obj.values()[0]`)....

.... looking through history ....

Exactly, [at some point in time](https://github.com/saltstack/salt/blob/b39106752bc85e9eebe829c907ac790e58de6501/salt/daemons/flo/core.py#L554), there was a `next()` there.

The problem here is most likely due to the fact that my Py3 compat PR was open for at least two and half months, with, I really don't know how many, rebases. I must have messed up on one of the rebases.

The reason why `six.itervalues(obj)` was preferred over `obj.values()` is because under Py3, what's returned from a `.values()` or `.keys()` or even `.items()` is an iterator. Since it's an iterator under Py3, make it an iterator under Py2 was my though. On top of this, the library we're using to check for Py3 compatibility casts the calls to  `.values()`, `.keys()`, `.items()` to a list.

```diff
salt/daemons/flo/core.py:1320: [W1699(incompatible-py3-code), ] Incompatible Python 3 code found. Proposed fix:
         master = self.road_stack.value.nameRemotes.get(self.master_estate_name.value)
         if not master or not master.alived:  # select a different master
             available_masters = [remote for remote in
-                                 self.road_stack.value.remotes.values()
+                                 list(self.road_stack.value.remotes.values())
                                                        if remote.alived]
             if available_masters:
                 random_master = opts.get('random_master')
```

I believe the library cast's to a list because we're used to see `obj.values()[0]` on python code, which, under Py3:
```python
>>> {1: 1, 2: 2}.values()[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'dict_values' object does not support indexing
>>> 
```

That automated py3 compat helping hand can only be smart up to a point.

At first glance, although we're using an external library, the code appeared more readable when using `six.itervalues(obj)`  than when using `list(obj.values())` or ever worse `list(obj.itervalues())`. That `list()`call always makes me stop reading the code and wonder why we're casting to a `list()`.

The next time PyLint runs on the develop branch, this module will be flagged with incompatible Py3 code(we're currently not checking that in PR's to make it easier on our Jenkins setup).

So, we either disable the Py3 compat checks on the whole module, or we add about 15 `pylint disabled` comments throughout the code. None of these solutions seems right.

What should be done instead?

**Comment by SmithSamuelM** [comment]
Python3 code for a list comprehension of the form

[ a for a in x.value()]

Is perfectly correct code. If a lint module is  converting this to 
[a for z in list(x.value())]

Then the problem is with the lint module. Not the code. Stop using that lint module or change its rules.

**Comment by SmithSamuelM** [comment]
The problem is the lint module is too stupid to understand when .values() is used in an iteration such
as a for loop or a list comprehension and when it is not used in an iteration.  But making code less readable just to satisfy a stupid lint module means to me to not use that lint module.

**Comment by s0undt3ch** [comment]
I'm not saying it was perfect :)

`py2to3` is not perfect, nor the modernize library which glues `six` and we already fixed some of its rules. Unfortunately, right now, that's all there is.

The alterative is by hand py3 checks and salt's code is massive.

When I have the time I'll see if we can smart it up...

**Comment by SmithSamuelM** [comment]
At some point it might be better to manually confirm by looking at the code if it is correct code. I don't like putting multiple lint exceptions sprinkled throughout the code. But this particular lint check is problematic and is not needed. (not all p3 but the .values() check) since in 99.999% of the cases it will work in both python3 and python2 if it ever worked in one of them.

**Comment by SmithSamuelM** [comment]
Yes if there is a way to smarten it up, that would be best. If it can be disabled its good enough as its an extremely uncommon 2to3 problem.

**Comment by SmithSamuelM** [comment]
Knowing that in Python3, .values() returns a view not a list means that

list(dict.values()) is the correct way to get a list from a view. So it should not be confusing at all. One should instantly recognize that that is the intent. It is just misplaced if it is in an iteration expression because in an iteration expression .values() stands alone.    In python3  list(dict.values()) is the only way
to do slicing on the values in a dict as the view is not sliceable.  so one must do  list(dict.values())[0] So one should expect to see this quite frequently in Python3 code.

**Comment by SmithSamuelM** [comment]
Frankly I think it is one of the biggest mistakes in the design of python3 to change .items and .values to be views instead of just using .iteritems and .itervalues.    Don't know what Guido was smoking at the time.

**Comment by SmithSamuelM** [comment]
or  .viewitems and .viewvalues

**Comment by s0undt3ch** [comment]
I think we can globally disable the py3 checker for `.items()`, `.values()` and `.items()`, as long as I find the right checker name.... I'll investigate.

I know `list(dict.values())` is the right way to have the same object type in both py2 and py3, but it's most commonly used to iterate in a for loop so, why create another object(unless we need a copy)...

As for `list(dict.values())[0]`, which is commonly seen(zero index of a list of keys or values of a dictionary), why is it preferable over `next(dict.itervalues())`? The end result is the same...

```python
Python 2.7.8 (default, Oct 27 2014, 04:23:15) 
[GCC 4.9.1 20140903 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> list({1: 1, 2: 2}.values())[0]
1
>>> next({1: 1, 2: 2}.itervalues())
1
>>>
```

Hmmm

A view in py3 is not even an iterable!?!?!?
```python
Python 3.4.2 (default, Jan 12 2015, 11:38:40) 
[GCC 4.9.2 20141224 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> list({1: 1, 2: 2}.values())[0]
1
>>> next({1: 1, 2: 2}.values())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'dict_values' object is not an iterator
>>> 
```

What's the reasoning behind this!? .... need to search for the PEP....

Anyway, I'm just getting my feet wet in Py3....

**Pull request merged**
