### PR TITLE
Improve the net.load_config execution function

### PR DESCRIPTION
**Pull request by mirceaulinic**
This function used to fail whenever the proxy minion run elsewhere
than the master, and it was invoked usign the filename arg.
With this change, the user can specify the filename using any of
the usual Salt URI, i.e., salt://, besides https:// etc.
Not only that is an improvement for reading files from whatever
location, but also readin files from the disk using the underlying
napalm function was very susceptible to race conditions. From now
on, the resource is read using the cp.get_file_str execution fun
and pass the result to napalm, as text to be loaded on the device.

### CODE REVIEW

**Review by rallytime — APPROVED** [review]

**Review by cachedout — COMMENTED** [review]
Can we cover this with unit testing?

**Comment by mirceaulinic** [comment]
As much as I would love to add tests for this, I'm afraid this would be very long, as there are no tests at all for any NAPALM modules unfortunately. I know that's terrible -- but without being a poor excuse, despite the fact that there's a pretty good number of network engineers currently using Salt with NAPALM, they usually don't have any software development skills, and I'm still stuck being the main developer. In other words, I would be more than happy to write tests (it's in my bucket list), but I unfortunately don't have the time to do everything.

If I recall correctly, some time ago @tonybaloney volunteered to help in this exact direction, but I'm not sure what's the status here (Anthony would you have any news)?

At the same time, if SaltStack would have any resources to give a helping hand with that, it would be greatly appreciated. Thanks!

**Comment by tonybaloney** [comment]
Submitted a WIP PR upstream https://github.com/cloudflare/salt/pull/9

**Comment by mirceaulinic** [comment]
Many thanks @tonybaloney, that's a great start.
I don't have any problem to submit the PR agains the CF clone, just that I believe the tests should be added in a separate PR, as I assume we'll have a lot of work there, so it might make more sense to submit it directly as a PR to the Salt codebase. But that's just how you prefer.
Thanks again for help, much appreciated!

**Comment by tonybaloney** [comment]
Don’t mind. It only gets complicated if whilst writing tests I uncover a bug. But I would probably submit the fix along with the test proving it’s existence once the base test fixtures Are done

**Comment by rallytime** [comment]
@mirceaulinic Were you going to pull in the testing PR to this one? I think getting those in is a good start at least.

**Comment by tonybaloney** [comment]
@mirceaulinic @rallytime added unit tests for all the remaining methods in the module upstream. https://github.com/cloudflare/salt/pull/10

**Comment by mirceaulinic** [comment]
Hi @rallytime @cachedout I added @tonybaloney's commits to this PR.
@tonybaloney - many thanks again for your help!

**Comment by cachedout** [comment]
@mirceaulinic and @tonybaloney Thanks! Just some minor lint errors here: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/16311/violations/file/tests/unit/modules/test_napalm_network.py/

**Comment by mirceaulinic** [comment]
@cachedout - thanks for your patience.
I fixed one of the lint errors, but I'm not sure I grasp the other one at line 243. Could you please explain a little how to fix that (sorry for dumb question here, but I don't have enough experience with the Salt testing infra 😄).

**Comment by mirceaulinic** [comment]
@cachedout @rallytime - is this branch waiting for anything else? Just checking to make sure the changes will make it into 2017.7.3. Thanks!

**Comment by rallytime** [comment]
@mirceaulinic We do need to work out that final lint error. I took a swing at it last week, but I wasn't able to get the `mock` options working AND the tests passing to resolve the lint error. 

I've restarted the tests so we can see some results though, since the last run timed out.

**Comment by tonybaloney** [comment]
@rallytime it seemed like the best way to mock out the method wrapper. Since decorators are declared upfront (ie at import) you can't simply use a mock or patch() to replace them. I'm not sure if it's a false-positive.

**Comment by rallytime** [comment]
@tonybaloney Right. I was trying to figure out a way to do just that, and wasn't successful. I think that message is OK to disable for lint.

Unfortunately, two of these new tests are failing on Python3: 
- unit.modules.test_napalm_network.NapalmNetworkModuleTestCase.test_ping
- unit.modules.test_napalm_network.NapalmNetworkModuleTestCase.test_traceroute

https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu16-py3/3732/testReport/junit/

With the following error:
```
Error Message

'dict_keys' object does not support indexing
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/unit/modules/test_napalm_network.py", line 318, in test_ping
    assert ret['out'].keys()[0] == 'success'
TypeError: 'dict_keys' object does not support indexing
```

**Comment by rallytime** [comment]
The remaining test failures are unrelated. Thanks everyone!

**Pull request merged**
