### PR TITLE
adding a new logging handler to support log4mongo

### PR DESCRIPTION
**Pull request by blaffoy**
Reissue of https://github.com/saltstack/salt/pull/20749 with some fixes for linter errors

### CODE REVIEW

**Comment by jfindlay** [comment]
@tensorproduct, just so you know, you can push (or even rewrite using 'push --force') commits to the same branch that corresponds to an existing pull request without having to close and reopen pull requests.  If new or changed commits come in for an existing pull request, the tests will also be rerun.

**Comment by tensorproduct** [comment]
Thanks. I'm a relative newbie to git. I've much more experience with Mercurial, and Git often confuses me.

**Comment by jfindlay** [comment]
No problem, thanks for the new logger!

**Comment by thatch45** [comment]
Thanks @tensorproduct ! We don't get very many log handler modules :)

**Pull request merged**
