### PR TITLE
Fix RST link format in Carbon release notes

### PR DESCRIPTION
**Pull request by mirceaulinic**
### What does this PR do?

In the previous PR https://github.com/saltstack/salt/pull/37944 I've formatted improperly the external links - did not use the correct RST syntax. Apologies for that!

### CODE REVIEW

**Comment by mirceaulinic** [comment]
@rallytime any idea when these changes will appear in https://docs.saltstack.com/en/develop/topics/releases/carbon.html?

**Comment by rallytime** [comment]
@mirceaulinic Hrm...That carbon release note link should not be there any more. That should have been renamed to 2016.11.0 release notes (which is where you have made your change). I am not sure why those carbon release notes are still available. I don't see them in the codebase, so they must be stashed on our doc build server somewhere.

The changes you've made here on the 2016.11.0 release notes should be available sometime later today, after this is merged. (Docs rebuild periodically through out the day.)

**Comment by mirceaulinic** [comment]
Thanks very much @rallytime for clarifying this!

**Comment by rallytime** [comment]
Anytime!

**Pull request merged**
