### PR TITLE
fix raven

### PR DESCRIPTION
**Pull request by trananhkma**
support raven ver 5.5.0

### CODE REVIEW

**Comment by jfindlay** [comment]
@trananhkma, there are some [lint errors](https://jenkins.saltstack.com/job/salt-pr-lint-n/8581/violations/file/salt/log/handlers/sentry_mod.py/).

**Comment by jfindlay** [comment]
@trananhkma, thanks for fixing the lint errors.  From my reading it looks like the `options` dictionary still needs to be handled in the 5.5.0 case as well.

**Comment by trananhkma** [comment]
@jfindlay, because ver 5.5.0 does not contain load() method, and sorry for my bad english.

**Comment by jfindlay** [comment]
Awesome, thanks @trananhkma.

**Pull request merged**
