### PR TITLE
Add convert_to_template feature for cloud.vmware

### PR DESCRIPTION
**Pull request by RootMePLS**
### What does this PR do?
Add new feature - convert a VM to template.

### What issues does this PR fix or reference?
#32855

### Tests written?
Yes

### CODE REVIEW

**Comment by fishhead108** [comment]
Agrh, there is some unnecessary commits e37d2c9 and 94df1a0.

**Comment by cachedout** [comment]
Could you please add some basic unit tests here to ensure that this doesn't regress in the future?

**Comment by fishhead108** [comment]
@cachedout 
Oh, my fault :) 
Forgot about it, will do it in a few weeks.

**Comment by cachedout** [comment]
@fishhead108 Sounds good. Thank you!

**Comment by fishhead108** [comment]
test written

**Review by rallytime — APPROVED** [review]

**Pull request merged**
