### PR TITLE
Support for Advanced Policy Firewall (APF)

### PR DESCRIPTION
**Pull request by mostafahussein**
### What does this PR do?

Adding Support for APF as an execution module in Salt.

### CODE REVIEW

**Comment by damon-atkins** [comment]
Would this be better off in iptables module as apf is a front end to iptables??????   You might also consider  writing '{0} -L -n | grep -iom1 sanity | wc -l'.format(salt.utils.which('iptables'))   in python vs calling grep and wc

**Comment by mostafahussein** [comment]
Hello @damon-atkins,
The reason of using `'iptables -L -n | grep -iom1 sanity | wc -l'` is to check if APF is actually running on the system or disabled.

For using `.format(salt.utils.which('iptables')` I have checked other modules that are using `grep` for example they are not passing it to `salt.utils.which($cmd)` which i thought it will be better to follow same standards as others.

**Comment by damon-atkins** [comment]
I think you missed the point.... Which was to write the grep and wc  in python and not call a commands.
i.e. call iptables pull the data into python check it with python code.   e.g.

`
for line in __salt__['cmd.run']('lsmod').splitlines():
`

**Comment by mostafahussein** [comment]
OK. you mean to use python code instead of bash, am i right ? if you mean so i will update it. That would be better. is there any other suggestions ?

**Comment by mostafahussein** [comment]
@cachedout I made a new commit without re-forking the repository. is that ok ?

**Comment by cachedout** [comment]
@mostafahussein Totally fine. Thanks!

**Comment by damon-atkins** [comment]
Your code looks nice,  you just have this left to clean up
cmd = '{0} -L -n | grep -iom1 sanity | wc -l'.format(salt.utils.which('iptables'))
Capture the output from the command and use python re.*  to find sanity

**Comment by mostafahussein** [comment]
@damon-atkins I will try you suggestion. thanks for the assist!

**Comment by mostafahussein** [comment]
@damon-atkins I made it work by using [python-iptables](https://github.com/ldx/python-iptables) library, you may check the code now.

**Comment by damon-atkins** [comment]
import iptc  you need to place a test around this 
I have added the tests to this https://github.com/vtek21/salt/blob/develop/salt/modules/reg.py including a message that says the import item is missing.

**Comment by mostafahussein** [comment]
exception added!

**Comment by cachedout** [comment]
Great job here, @mostafahussein !

**Pull request merged**
