### PR TITLE
Move PR #44053 to develop branch

### PR DESCRIPTION
**Pull request by rallytime**
### What does this PR do?
Moves the commit from #44053 to the `develop` branch, as this PR was closed since it was against the `2017.7.2` branch. After discussing the change, it was decided this bug fix should be submitted to develop.

Original PR message from @ari:
> Better exception

>  After spending an hour trying to figure out why I had a key error in an orchestration state I realised that saltstack requires a runner id with a dot. A clearer error message will save the next person wasting the same time.

### What issues does this PR fix or reference?
#44053

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
@rallytime I know this isn't your code but can you toss a really quick unit test in for this?

**Comment by rallytime** [comment]
@cachedout I have written a quick unit test for this just now.

**Review by cachedout — APPROVED** [review]

**Comment by rallytime** [comment]
re-run py3

**Comment by rallytime** [comment]
Just so I don't lose the record of the test failure in the next couple of days, the new test is failing on PY3 with the following error:
```
Traceback (most recent call last):
  File "/testing/tests/unit/loader/test_loader.py", line 305, in test_single_item_no_dot
    self.assertEqual(err.exception[0], expected_msg)
TypeError: 'KeyError' object is not subscriptable
```
I'll need to come back to this and fix it next week.

**Comment by rallytime** [comment]
re-run ubuntu

**Pull request merged**
