### PR TITLE
Add arg to hide file.append or file.prepend output

### LINKED ISSUE #59329: [FEATURE REQUEST] Add show_changes arg to file.(pre|ap)pend
**Is your feature request related to a problem? Please describe.**
I don't want sensitive lines logged, but would like to use `file.append` or `file.prepend` in my state files.

**Describe the solution you'd like**
I'd like the `show_changes` argument to be available here, similar to `file.managed`.

**Describe alternatives you've considered**
Not using `file.append` or `file.prepend`. This is less than ideal.

**Additional context**
Lots of `file.*` states accept this argument. `file.append` and `file.prepend` should probably accept it too.

### PR DESCRIPTION
**Pull request by boltronics**
### What does this PR do?
Adds `show_changes` to the `file.append` and `file.prepend` state modules, for restricting output similarly to how this argument behaves in `file.managed` and others.

### What issues does this PR fix or reference?
[FEATURE REQUEST] Add show_changes arg to file.(pre|ap)pend #59329

### Previous Behavior
You could not use `file.append` to, for example, append a line containing a password, unless you were happy to have that output logged.

### New Behavior
Now you can.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**
- [x] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

### Other
I don't know if this really works (I haven't gotten around to setting up a [self-contained development version](https://docs.saltproject.io/en/latest/topics/development/hacking.html#running-a-self-contained-development-version))... but the pre-commit hook tests pass and I'm sure they wouldn't lie! However I'll try to see if it actually works if I have time later in the week, unless someone else beats me to it or unless everyone is already confident.

As a side note, it's weird that `file.append` was completely void of unit tests, but `file.prepend` (which is nearly identical in terms of how it's implemented) has them. I hope I didn't overlook something.

Further, it looks like one was just a copy/paste of the other method at one point (with only the most minor changes) but because of this, over time, some people added patches to one but not the other so they have diverged slightly. It looks like the file state module could use some refactoring work and these could be consolidated and regain feature parity.

### CODE REVIEW

**Comment by boltronics** [comment]
My testing shows that the patch to `file.append` and `file.prepend` look good.
```
     Changes:   
              ----------
              diff:
                  <show_changes=False>
```

However the tests are failing - specifically https://github.com/saltstack/salt/pull/59330/commits/02d995e6cfad9b49adda07cbbd5e58f0facff79e - because the mock file is insufficiently accurate to allow a diff to properly be generated.

I'll have to look into that more closely when I have time, unless someone wants to beat me to it, or unless we can simply drop that patch - `file.append` didn't have a single test to begin with anyway.

**Comment by Ch3LL** [comment]
any update on the test failures?

**Comment by boltronics** [comment]
Sorry, I'm unexpectedly moving house and a bit busy right now. I'll look into it when I have more time, unless someone else beats me to it.

**Comment by Ch3LL** [comment]
No worries at all :) Thanks for the update and good luck with moving.

ping @saltstack/team-core does anyone have time to help here?

**Comment by sagetherage** [comment]
this is failing a bunch of tests, removing it from AL for now, will attempt to plan for the AL point release, if possible

**Comment by sagetherage** [comment]
since this is a feature it will need to go into a major release - labeling for `Silicon`

**Comment by Ch3LL** [comment]
ping @waynew would you be willing to tackle the test failures on this PR in your test clinic?

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
