### PR TITLE
Archlinux support in timezone.zone_compare where /etc/localtime doesn't exist for comparison.

### PR DESCRIPTION
**Pull request by ipaqmaster**
### What does this PR do?

This PR adds timezone setting support for Archlinux hosts where /etc/localtime does not exist and the compare check cannot be made, throwing an error.

### What issues does this PR fix or reference?
Fixes: issue #61296

### Previous Behavior

`$ sudo salt-call timezone.zone_compare UTC`
`Error running 'timezone.zone_compare': Failed to read /etc/localtime to determine current timezone: No such file or directory`

Attempting to set the time with timezone.system where /etc/localtime is missing reaches timezone.zone_compare and fails on Archlinux.

### New Behavior

Above comparison command works and the timezone.system state also works. /etc/localtime gets created if missing on Archlinux hosts with the requested timezone.

Running `salt-call timezone.zone_compare UTC` alone is enough to experience the error when /etc/localtime is missing.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by ipaqmaster** [comment]
Pulling this change to install Salt on an Archlinux machine, then deleting /etc/localtime before running a timezone.system salt state was able to create the missing /etc/timezone symlink without error. Where previously it would error.

**Comment by OrangeDog** [comment]
Why does the file exists check have to be OS-specific in the first place?

**Comment by ipaqmaster** [comment]
I've just tacked Arch into the original solution used for FreeBSD but I agree, this could probably be changed to not do the os_family if check, only doing the os.path.isfile check for any *nix host and just creating the file whenever missing.

**Comment by ipaqmaster** [comment]
Would it be worth resubmitting this change without the os_family check and only keeping the `if not os.path.isfile` check to cover any distro missing the symlink?

**Comment by ipaqmaster** [comment]
Anything else needed for this one?

**Pull request closed without merging**
