### PR TITLE
modules.http.wait_for_successful_query: Allow to ignore exceptions

### PR DESCRIPTION
**Pull request by eliasp**
Older versions of Tornado will raise unpleasant exceptions which will
kill any execution relying on `modules.http`. The option
`ignore_exceptions` allows to ignore those, as in some scenarios it
might be more important to return a working result than to properly
handle exceptions.

Signed-off-by: Elias Probst <e.probst@ssc-services.de>

### What does this PR do?
It allows to use `modules.http.wait_for_successful_query`, even when the underlying HTTP library causes an exception which might happen in the case of Tornado, when the service providing the corresponding HTTP endpoint is not fully started yet.
This is especially important in orchestration scenarios, when waiting for an HTTP service to be up and running again after a server reboot.

### What issues does this PR fix or reference?
None

### Previous Behavior
**Execution:**
```
$ salt some-windows-host http.wait_for_successful_query http://localhost:1234/some/where wait_for=10
some-windows-host:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1607, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\http.py", line 67, in wait_for_successful_query
        raise caught_exception  # pylint: disable=E0702
    error: [Errno 10061] Unknown error
```
**Versions Information:**
```
     Salt Version:
               Salt: 2018.3.3    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2008ServerR2
             system: Windows
            version: 2008ServerR2 6.1.7601 SP1 Multiprocessor Free
```
### New Behavior
`http.wait_for_successful_query` works as designed.

### Tests written?
No

### Commits signed with GPG?
Yes

### Additional Information

This should be simply cherry-pickable to be backported to older releases. I originally developed the fix for 2018.3 and was able to simply cherry-pick it to `develop`.

### CODE REVIEW

**Comment by cmcmarrow** [comment]
Its looks good, but can you add two test please?

**Review by cmcmarrow — CHANGES_REQUESTED** [review]
Its looks good, but can you add two test please?

**Comment by sagetherage** [comment]
@eliasp can you rebase this against the master branch, please?

**Comment by sagetherage** [comment]
Reviewed in Grooming 2021-APR-05 considering closing

**Comment by sagetherage** [comment]
@eliasp can you please rebase against the master branch? 

Discussed in Grooming 2021-APR-19 I will give this 2 more weeks and if no response, will close.

**Comment by sagetherage** [comment]
Reviewed in Grooming 2021-MAY-03 closing

**Pull request closed without merging**
