### PR TITLE
rewrote the implementation and documentation for get_uuid, get_on_poweroff, get_on_reboot and the usage of get_xml

### PR DESCRIPTION
**Pull request by waheedi**
### What does this PR do?

- It fixes few bugs with the current module and sticks to the standard way of implementing virt module functions, there were inconsistencies in the implementation of few functions like get_on_poweroff, get_on_crash, get_on_reboot, get_uuid and get_profiles and in their documentation too. 

- removed function get_xml as it does not belong here

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/52431

### Previous Behavior
`salt '*' virt.vm_info`
The VM "<libvirt.virDomain object at 0x7f24e9e73198>" is not present
### New Behavior
`salt '*' virt.vm_info`
```
minion:
    ----------
    minion-1:
        ----------
        cpu:
            1
        cputime:
            0
        disks:
            ----------
            vda:
                ----------
                cluster size:
                    65536
                disk size:
                    3065716736
                file:
                    /var/lib/libvirt/images/ubuntu16.04.qcow2
                file format:
                    qcow2
                type:
                    disk
                virtual size:
                    10737418240
        graphics:
            ----------
            autoport:
                yes
            keymap:
                None
            listen:
                None
            port:
                None
            type:
                spice
        loader:
            ----------
            path:
                None
        maxMem:
            819200
        mem:
            819200
        nics:
            ----------
            52:54:00:70:b7:63:
                ----------
                address:
                    ----------
                    bus:
                        0x00
                    domain:
                        0x0000
                    function:
                        0x0
                    slot:
                        0x03
                    type:
                        pci
                mac:
                    52:54:00:70:b7:63
                model:
                    virtio
                source:
                    ----------
                    network:
                        default
                type:
                    network
        on_crash:
            destroy
        on_poweroff:
            destroy
        on_reboot:
            restart
        state:
            shutdown
        uuid:
            e6e3f990-8997-4a5e-8cb7-ea835eae4bbe
```
### Tests written?

No (but tested)

### Commits signed with GPG?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by Ch3LL** [comment]
@waheedi looks like there are some test failures and a merge conflict. Also any chance you can write some tests for these changes?

**Comment by dakwak** [comment]
@Ch3LL Yes, I will try my best to fix the conflicts, any guidelines on tests would be great. Are there some documents to read on this?

Thanks,

**Comment by waheedi** [comment]
@Ch3LL I will be closing this PR and create a new one with a fresh version

**Comment by Ch3LL** [comment]
There is some documentation here: https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html

Thanks! Let me know if you have any questions.

**Pull request closed without merging**
