### PR TITLE
[3006.x] Revert "Fix file.directory clobbering paths in test mode when backupname=True"

### PR DESCRIPTION
**Pull request by s0undt3ch**
This reverts commit 7386c6e.Reverts saltstack/salt#66120

This broke the nightly builds, [see here](https://github.com/saltstack/salt/actions/runs/8012832305/job/21936165946#step:23:11316).

### CODE REVIEW

**Comment by s0undt3ch** [comment]
/CC @terminalmage are you interested in re-submitting with the fixed test?

**Comment by terminalmage** [comment]
@s0undt3ch I don't use Windows, don't have access to a Windows box on which to test, and don't understand why it failed. Perhaps @twangboy can offer some insight?

**Comment by terminalmage** [comment]
It seems like `readlink()` made the Path object different, adding those extra characters before the `C:`... but I'm not familiar with how `readlink()` works on Windows. @twangboy would adding a `.resolve()` after the `.readlink()` help here?

**Comment by terminalmage** [comment]
Is anyone available to assist with the Windows tests?

**Pull request merged**
