### PR TITLE
Revert "Updated dict .keys() and .values() indexed calls for py3"

### PR DESCRIPTION
**Pull request by s0undt3ch**
Reverts saltstack/salt#56243

### CODE REVIEW

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by raddessi** [comment]
Hey I'm sorry, we have been heavily sidetracked with other work so I haven't had time to check in and continue on this project. What is the issue with #56243 that needs a revert?

**Comment by s0undt3ch** [comment]
Honestly, too much time has passed. Not even I remember.
It was something about some tests either failing or hanging, which is no longer present in the master branch. Closing.

**Pull request closed without merging**
