### PR TITLE
Fix REST CherryPY append the default permissions every request

### LINKED ISSUE #60955: [BUG] salt-api reaches maximum memory when using REST CherryPY
**Description**
REST CherryPy appends default permisions every request that make the returned JSON keep increasing until reach maximum memory.

**Setup**
In `/srv/configs/master/api.conf`

```
rest_cherrypy:
  port: 8000
  root_prefix: /api/
  disable_ssl: True
  socket_queue_size: 100
  thread_pool: 200
  collect_stats: True
```

**Steps to Reproduce the behavior**
Run `curl` to send request to `/api`
```shell
curl -X POST http://127.0.0.1:8000/api/login -H "Content-Type: application/json" -d '{"eauth":"rest","username":"test@example.com","password":"ac230fc3-cf42-4b04-a00b-de1ca906a830"}'
```

Returned JSON keeps appending the default permissions.
```json
{
  "return": [
    {
      "token": "752a9004db630b48a314fc68e1fbe2c23e00c9dd",
      "expire": 1629491964.8055215,
      "start": 1629448764.8055215,
      "user": "test@example.com",
      "eauth": "rest",
      "perms": [
        {
          "centOS-*": [
            "cmd.run_all",
            {
              "cp.get_url": {
                "kwargs": {
                  "path": "https://example.com/.*"
                }
              }
            }
          ]
        },
        {
          "default-*": [
            "grains.items",
            "test.ping",
            "test.arg",
            "status.uptime",
            "cmd.run_all",
            {
              "cmd.script": {
                "kwargs": {
                  "source": "https://google.com/.*"
                }
              }
            }
          ]
        },
        {
          "default-*": [
            "grains.items",
            "test.ping",
            "test.arg",
            "status.uptime",
            "cmd.run_all",
            {
              "cmd.script": {
                "kwargs": {
                  "source": "https://google.com/.*"
                }
              }
            }
          ]
        },
        {
          "default-*": [
            "grains.items",
            "test.ping",
            "test.arg",
            "status.uptime",
            "cmd.run_all",
            {
              "cmd.script": {
                "kwargs": {
                  "source": "https://google.com/.*"
                }
              }
            }
          ]
        }
      ]
    }
  ]
}
```

**Expected behavior**
Returned JSON should be only user's permissions + default permission for subsequent requests.
```json
{
  "return": [
    {
      "token": "752a9004db630b48a314fc68e1fbe2c23e00c9dd",
      "expire": 1629491964.8055215,
      "start": 1629448764.8055215,
      "user": "test@example.com",
      "eauth": "rest",
      "perms": [
        {
          "centOS-*": [
            "cmd.run_all",
            {
              "cp.get_url": {
                "kwargs": {
                  "path": "https://example.com/.*"
                }
              }
            }
          ]
        },
        {
          "default-*": [
            "grains.items",
            "test.ping",
            "test.arg",
            "status.uptime",
            "cmd.run_all",
            {
              "cmd.script": {
                "kwargs": {
                  "source": "https://google.com/.*"
                }
              }
            }
          ]
        }
      ]
    }
  ]
}
```

**Versions Report**
```
Salt Version:
          Salt: 3002.7

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: debian 10 buster
        locale: utf-8
       machine: x86_64
       release: 4.14.231-173.361.amzn2.x86_64
        system: Linux
       version: Debian GNU/Linux 10 buster
```

### PR DESCRIPTION
**Pull request by phatt-ngo**
- Use copy() to copy dictionary object

### What does this PR do?

Fix REST CherryPy append the default permisions every request.

### What issues does this PR fix or reference?
Fixes: #60955

### Previous Behavior
```json
{
  "return": [
    {
      "token": "752a9004db630b48a314fc68e1fbe2c23e00c9dd",
      "expire": 1629491964.8055215,
      "start": 1629448764.8055215,
      "user": "test@example.com",
      "eauth": "rest",
      "perms": [
        {
          "centOS-*": [
            "cmd.run_all",
            {
              "cp.get_url": {
                "kwargs": {
                  "path": "https://example.com/.*"
                }
              }
            }
          ]
        },
        {
          "default-*": [
            "grains.items",
            "test.ping",
            "test.arg",
            "status.uptime",
            "cmd.run_all",
            {
              "cmd.script": {
                "kwargs": {
                  "source": "https://google.com/.*"
                }
              }
            }
          ]
        },
        {
          "default-*": [
            "grains.items",
            "test.ping",
            "test.arg",
            "status.uptime",
            "cmd.run_all",
            {
              "cmd.script": {
                "kwargs": {
                  "source": "https://google.com/.*"
                }
              }
            }
          ]
        },
        {
          "default-*": [
            "grains.items",
            "test.ping",
            "test.arg",
            "status.uptime",
            "cmd.run_all",
            {
              "cmd.script": {
                "kwargs": {
                  "source": "https://google.com/.*"
                }
              }
            }
          ]
        }
      ]
    }
  ]
}
``

### New Behavior
```json
{
  "return": [
    {
      "token": "752a9004db630b48a314fc68e1fbe2c23e00c9dd",
      "expire": 1629491964.8055215,
      "start": 1629448764.8055215,
      "user": "test@example.com",
      "eauth": "rest",
      "perms": [
        {
          "centOS-*": [
            "cmd.run_all",
            {
              "cp.get_url": {
                "kwargs": {
                  "path": "https://example.com/.*"
                }
              }
            }
          ]
        },
        {
          "default-*": [
            "grains.items",
            "test.ping",
            "test.arg",
            "status.uptime",
            "cmd.run_all",
            {
              "cmd.script": {
                "kwargs": {
                  "source": "https://google.com/.*"
                }
              }
            }
          ]
        }
      ]
    }
  ]
}
```

### CODE REVIEW

**Review by vkaylee — APPROVED** [review]

**Comment by marty-macfly** [comment]
Hello,

@Ch3LL do you have any ETA for the review ? Or about what need to be done to move forward on that PR and related issue ?

Thanks for your support,

**Review by Ch3LL — CHANGES_REQUESTED** [review]
This will require a changelog and would you be willing to add test coverage, so this does not occur in the future?

**Comment by Ch3LL** [comment]
@marty-macfly thanks for bumping this one for me. I added some feedback.

**Comment by marty-macfly** [comment]
@Ch3LL I've done the work to add test and change-log as required I'm not the author of the original PR, it's an ex-colleague onot sure is still following that PR so I've create a new PR with all the change https://github.com/saltstack/salt/pull/61676 that should allow the merged, if you kind enough to do the review.

**Pull request closed without merging**
