### PR TITLE
[develop] Merge forward from 2017.7 to develop

### PR DESCRIPTION
**Pull request by rallytime**
No conflicts.

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
These failing tests concern me...

**Comment by rallytime** [comment]
@cachedout I just checked and these failing tests are present already on 2017.7.

**Comment by rallytime** [comment]
After some digging around, I have confirmed that these tests are failing on 2017.7 and 2017.7.1 already, caused by the changes in #42031. The tests are fixed with #42548.

Since we don't want to introduce these failures upstream, I'll close this for now. Once #42548 is available in the 2017.7 branch and the tests are happy, I will re-do this merge-forward.

**Pull request closed without merging**
