### PR TITLE
Python3 compatibility fix

### PR DESCRIPTION
**Pull request by justinta**

### CODE REVIEW

**Comment by cachedout** [comment]
This looks fine but does it need to go into an earlier branch?

**Comment by jtand** [comment]
I'm not sure. It was found on the develop branch.

**Comment by jfindlay** [comment]
@cachedout, py3 linting only happens on the develop branch tests (currently).  It does not happen on develop pull requests because of the overhead required.  @s0undt3ch made one huge pull request many weeks ago to fixup develop into a py3 compatible state while also introducing the py3 linting.  This has been an ongoing effort since then but isn't too bad since problems like this only happen occasionally.  As the project moves forward all branches will eventually be py3 linted.  We thought this would be simpler and involve less work than aggressively py3 linting all things at the same time.

**Comment by jfindlay** [comment]
Additionally, @thatch45 and I were discussing yesterday that we would like pull requests to be tested on a python 2.6 and a python 3.4, python 2.7 being the most compatible python should cause the least problems in this regard, since the majority of the branch lint-like fixes we do are related to these versions, so having them run pull requests will be better than any linting anyway as they will catch things the linter won't and incur the submitter to fix their own code before merging.

**Pull request merged**
