### PR TITLE
Bugfix: always return a string "list" on unknown job target type.

### PR DESCRIPTION
**Pull request by isbm**
Backport of https://github.com/saltstack/salt/pull/43974

### CODE REVIEW

**Comment by isbm** [comment]
@cachedout oops, I think I should have been post it here, so the `develop` just gets automatically propagated.

**Comment by rallytime** [comment]
@isbm The 2017.7.2 branch is currently closed for fixes. Can you move this to the `2017.7` branch?

**Comment by isbm** [comment]
@rallytime ah, dang, didn't noticed. Done!

**Comment by rallytime** [comment]
@isbm No worries! :) It looks like this needs to be rebased now. There are conflicting files and the commit list isn't super clean. Would you mind rebasing this?

**Comment by isbm** [comment]
@rallytime I am closing this, there is another PR that does all this just clean https://github.com/saltstack/salt/pull/44045

**Comment by isbm** [comment]
@rallytime I don't get what just happened. I created another PR, as this one refused to be rebased and continued keep conflicting files. So I **closed** this PR, and then my new PR just gone. :disappointed: And this seems OK. But now GitHub shows me 404 on my PR and this seems opened with an old branch. Cold you please double-check?

**Pull request closed without merging**
