### PR TITLE
file.line respect quiet flag

### PR DESCRIPTION
**Pull request by toanju**
Despite passing quiet=True to file.line the result is not quiet. This PR
silences the error returned in case quiet is true. The same pattern as
in the replace function is applied.

### CODE REVIEW

**Review by twangboy — DISMISSED** [review]

**Comment by dwoz** [comment]
@toanju Can you please write a regression test for this?

**Comment by dwoz** [comment]
@toanju I've rebased this to the `master` branch.

**Review by twangboy — CHANGES_REQUESTED** [review]
This needs a testcase and a changelog

**Comment by Ch3LL** [comment]
Closing due to inactivity. Please let me know if we need to re-open or you can open a new PR based off of master with the feedback included above.

**Pull request closed without merging**
