### PR TITLE
document `regex_replace` Jinja filter

### PR DESCRIPTION
**Pull request by mbunkus**
### What does this PR do?

It adds documentation for the existing `regex_replace` Jinja filter to the "Understanding Jinja" document.

### What issues does this PR fix or reference?

#48952 

### Tests written?

No, but I did build the HTML docs and verified that the resulting HTML page looks correct.

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by rallytime — APPROVED** [review]

**Comment by lorengordon** [comment]
@rallytime It would be awesome to backport this simple doc patch back to 2018.3 and 2019.2, so it showed up in the current stable docs... Right now it only shows up in the "develop" docs...

**Comment by rallytime** [comment]
@lorengordon For sure, good call.

@garethgreenaway or @Ch3LL can you help out here?

**Comment by Ch3LL** [comment]
Thanks for the heads up @rallytime I added the label and it will get backported here soon. thanks!

**Comment by sagetherage** [comment]
Notes from Community Port Jam: already in master-skipped

**Pull request merged**
