### PR TITLE
Fixes for Zabbix module issues and compatibility fixes

### LINKED ISSUE #60795: [BUG] zabbix_host.present groupid is missing
**Description**
When I try to create a host via zabbix states, it doesn't work, but I think I've everything in the sls file. 

Edit: it looks like that it only happens to hosts that are already exist/ that are created manually in the past
```
----------
          ID: create_host_to_zabbix
    Function: zabbix_host.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2172, in call                                                                                                                                                                                                                                      
                  *cdata["args"], **cdata["kwargs"]                                                                                                                                                                                                                                                                          
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1241, in __call__                                                                                                                                                                                                                                 
                  return self.loader.run(run_func, *args, **kwargs)                                                                                                                                                                                                                                                          
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2274, in run                                                                                                                                                                                                                                      
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)                                                                                                                                                                                                                              
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2289, in _run_as                                                                                                                                                                                                                                  
                  return _func_or_method(*args, **kwargs)                                                                                                                                                                                                                                                                    
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2322, in wrapper                                                                                                                                                                                                                                  
                  return f(*args, **kwargs)                                                                                                                                                                                                                                                                                  
                File "/usr/lib/python3/dist-packages/salt/states/zabbix_host.py", line 415, in present                                                                                                                                                                                                                       
                  hostid, groups=groups, **connection_args                                                                                                                                                                                                                                                                   
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1241, in __call__                                                                                                                                                                                                                                 
                  return self.loader.run(run_func, *args, **kwargs)                                                                                                                                                                                                                                                          
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2274, in run                                                                                                                                                                                                                                      
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)                                                                                                                                                                                                                              
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2289, in _run_as                                                                                                                                                                                                                                  
                  return _func_or_method(*args, **kwargs)                                                                                                                                                                                                                                                                    
                File "/usr/lib/python3/dist-packages/salt/modules/zabbix.py", line 1391, in host_update                                                                                                                                                                                                                      
                  ret = _query(method, params, conn_args["url"], conn_args["auth"])                                                                                                                                                                                                                                          
                File "/usr/lib/python3/dist-packages/salt/modules/zabbix.py", line 187, in _query                                                                                                                                                                                                                            
                  ret["error"]["message"], ret["error"]["data"]                                                                                                                                                                                                                                                              
              salt.exceptions.SaltException: Zabbix API: Invalid params. (Incorrect value for field "groups": the parameter "groupid" is missing.)                                                                                                                                                                           
     Started: 09:48:56.212143
    Duration: 1088.088 ms
     Changes:
```
**Setup**
we use zabbix 5.4.1

```
create_host_to_zabbix:
  zabbix_host.present:
    - host: {{ grains['host'] }}
    - groups:
      - 2
    - interfaces:
      - {{ grains['fqdn'] }}:
        - ip: {{ grains['ipv4'][1] }}
        - type: agent
        - port: 10050
        - main: true
        - useip: true
    - require:
      - pkg: zabbix-agent
    - _connection_user: ***
    - _connection_password: ****
    - _connection_url: https://monitoring.example.de/api_jsonrpc.php

assign_templates_to_host:
  zabbix_host.assign_templates:
    - host: {{ grains['host'] }}
    - templates:
      - "Template OS Linux"
    - _connection_user: ***
    - _connection_password: ****
    - _connection_url: https://monitoring.example.de/api_jsonrpc.php
```
  
**Expected behavior**
Just to add a host in zabbix


**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
salt-master:
salt --versions-report
Salt Version:
          Salt: 3003.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: 2.1.11
        Jinja2: 2.10
       libgit2: 0.27.7
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: 0.27.4
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-17-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```

```
salt-minion --versions-report
Salt Version:
          Salt: 3003.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.5.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.9.4
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.5.3 (default, Apr  5 2021, 09:00:41)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.1
 
System Versions:
          dist: debian 9 stretch
        locale: UTF-8
       machine: x86_64
       release: 4.9.0-15-amd64
        system: Linux
       version: Debian GNU/Linux 9 stretch
```
</details>

**Additional context**

### PR DESCRIPTION
**Pull request by t0fik**
ISSUES FIXED: #60795
### What does this PR do?
- Fixed errors on calling `zabbix_user.admin_password_present` state, due to changed error message in Zabbix 6.0
- Fixed `zabbix.host_update` not mapping group ids list to list of dicts in format `[{"groupid": groupid}, ...]` (#60795)
- Fixed `zabbix.user_update` not mapping usergroup id list to list of dicts in format `[{"usrgrpid": usrgrpid}, ...]`
- Added support for changed user object in Zabbix 5.4+
- Added compatibility with Zabbix 4.0+ for `zabbix.user_getmedia` method
- Added support for setting medias in `zabbix.user_update` for Zabbix 3.4+
- Changed `zabbix.user_get` to return full user info with groups and medias
- Changed `zabbix.user_addmedia` to return error with comment for Zabbix 4.0+ due to `user.addmedia` method removal
- Changed `zabbix.user_deletemedia` to return error with comment for Zabbix 4.0+ due to `user.deletemedia` method removal
- Added missing `CLI Example` sections

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by garethgreenaway** [comment]
@t0fik Thanks!  This looks fantastic!  We have a number of open issues related to the Zabbix modules would you mind linking those issues to this PR so they'll get closed once this PR is merged? One additional ask, would you mind converting the tests over to PyTest?  We can offer assistance if needed.  Thanks again!

**Comment by t0fik** [comment]
@garethgreenaway I've found only one issue, which is fixed by this PR.
I can take care about rest of them but I did not want to push to much code.
I did not review all functions in the module so not all bugs in zabbix module might be fixed, also refactorisation to the module is needed. I wanted to do that after merging this PR.
I can try to migrate tests, but I would need link to docs how to do it, if docs exists.

**Comment by garethgreenaway** [comment]
@t0fik all good.  Just making sure the PR addresses the right issues, if this doesn't cover all the other issues but future PRs might that's great.  The Zabbix modules are one collection of modules that we've considered moving out into a Salt extension separate from the main Salt code.  This will allow it to be updated quicker than it has previously.  It would live under a community controlled organization but wouldn't be actively maintained by the Salt core team. Would you be interested in being the owner of such an extension?

**Review by garethgreenaway — APPROVED** [review]

**Comment by t0fik** [comment]
@garethgreenaway Sorry for late response. I was loaded with other tasks. I think, that I'm not the best candidate to be the owner. I will contribute when I find any problem.

**Pull request merged**
