### PR TITLE
pillar/http_json and yaml: replace %s with minion_id in urls

### PR DESCRIPTION
**Pull request by the-glu**
### What does this PR do?

Add a feature in pillar / http_json and http_yaml: %s is replaced with minion id.

### What issues does this PR fix or reference?

#41062 and #40850 has been fixed via #41576, but using grains. This version is more simpler and just use the minion id.

This is the same behaviour used in cmd_json and cmd_yaml.

This should also increase the security, since minions can manipulate grains but not he minion id. (but I'm not sure about this ;) )

### Tests written?
No

### CODE REVIEW

**Review by cachedout — APPROVED** [review]

**Review by terminalmage — APPROVED** [review]
This looks good, but for clarity in the docs we should probably indent the docstring changes four spaces, and above the new docs add a `.. versionchanged:: Oxygen` line. This will make it explicit that this feature was added in Oxygen.

**Comment by the-glu** [comment]
Ok, I fixed the doc with the `versionchanged`. Looks good ? I'm not sure about the indent, the code block has only 2 spaces ;)

**Comment by terminalmage** [comment]
@the-glu The text in the code block should also be indented 4 spaces, so please indent the example SLS an additional 2 spaces.

**Comment by terminalmage** [comment]
:+1:

**Pull request merged**
