### PR TITLE
Add 'uuid', 'on_reboot', 'on_restart', and 'on_crash' settings to the…

### PR DESCRIPTION
**Pull request by pm17788**
### What does this PR do?
Adds 'uuid', 'on_reboot', 'on_restart', and 'on_crash' settings to the `virt.vm_info` and `virt.full_info` outputs

### What issues does this PR fix or reference?
The need to parse XML to get this data.

### New Behavior
Both `virt.vm_info` and `virt.full_info` outputs now include the parsed values (or Null) for `uuid`, `on_reboot`, `on_restart`, and `on_crash`. The highest utility is in mass parsing of output of things like
`salt --out=json '*' virt.full_info`

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by pm17788** [comment]
The use case we have for this is matching, with a high degree of confidence, the data set get from a salt minion which runs on a guest *and* when the same VM shows up as a part of `virt.vm_info` or `virt.full_info` output produced by the salt minion running on the hypervisor.
Right now, I'm forced to use a hacky "let's match the MAC address of the NIC(s) seen by the guest minion to a MAC address reported as part of `virt.vm_info`", and I already have collisions (unsurprisingly).

If `uuid` was available, it'd be matched to the output of `dmidecode --string system-uuid` (just have to `.lower()` the string), and the match would be a lot more deterministic.

**Comment by pm17788** [comment]
Re: Failing checks - sorry, not sure how to fix any of them. None of the failures seemed actual failures. I tried to follow the pattern already established by functions such as `_get_nics(dom)`.

**Comment by rallytime** [comment]
Hi @pm17788 - Apologies for not commenting on this sooner. It got lost in my tabs. :)

The original test run actually hit a race-condition we have in our jenkins server, that's why there weren't any test results there.

However, the lint failures will need to be fixed up for sure: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/22808/violations/file/salt/modules/virt.py/

Can you grab those?

Also, welcome! Thanks for contributing. :)

**Comment by pm17788** [comment]
@rallytime: Thank you for catching up with this. 

The linter and I are now in the battle of wits. :)

**Comment by rallytime** [comment]
@pm17788 :)

_Almost_ there!

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/22812/violations/file/salt/modules/virt.py/

**Comment by pm17788** [comment]
@rallytime: I _think_ I got it this time. So many checks seem to come back angry-red, though, sadly, I'm at a loss how to fix 'em.

**Comment by rallytime** [comment]
@pm17788 Thanks! Yeah, those other test failures are not related to this PR.

**Review by rallytime — APPROVED** [review]

**Comment by pm17788** [comment]
@rallytime : Huzzah! :)

**Review by gtmanfred — APPROVED** [review]

**Pull request merged**
