### PR TITLE
Add ttp modules and tests

### PR DESCRIPTION
**Pull request by dmulyalin**
### What does this PR do?

Added two new modules:
 - TTP execution module
 - TTP runner module

TTP is a library for parsing semi structured text using templates. New execution and runner modules allow to run commands against minions to obtain output in a text format for the sake of parsing and processing using TTP templates to transform it in structured data such as lists or dictionaries.

Sample use cases that TTP can help to address
- reporting across several minions by parsing text output and returning text tables
- transforming text data in structured format for storing in mine
- time series data can be produced using TTP templates and pushed to databases using returners
- compliance testing by parsing text into structured data with further processing and analysis to detect deviations

Given that text data can be transformed into structured data of arbitrary hierarchy, this modules can significantly expand functionality in the area of minions state analysis and processing.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by cmcmarrow** [comment]
Thanks for the PR @dmulyalin. Do you have an issue for this PR? The salt team and the community probably wants to discuss this PR before it gets merged into salt.

**Comment by cmcmarrow** [comment]
I would also open an issue here https://github.com/saltstack/salt-enhancement-proposals.

**Comment by dmulyalin** [comment]
@cmcmarrow thank you for the advice, raised https://github.com/saltstack/salt/issues/58779 issue to have a discussion about TTP modules.

Also had a look at https://github.com/saltstack/salt-enhancement-proposals, do not think that TTP complies with SEP requirements, quote:
In short, to get a **major feature added to Salt,** one must submit the SEP via pull-request

IMHO, while TTP modules definitely extend SALT functionality, they hardly can be considered a major feature.

**Comment by network-shark** [comment]
push

**Comment by dmulyalin** [comment]
No longer needed/valid. Sorry for not clising it earlier.

**Comment by garethgreenaway** [comment]
@dmulyalin Thanks for closing this out.

**Pull request closed without merging**
