### PR TITLE
modules.debian_ip: Fix resolv.conf handling

### PR DESCRIPTION
**Pull request by eliasp**
### What does this PR do?
Don't try to write `/etc/resolv.conf` if it's a symlink.

`resolv.conf` might be runtime-managed by `systemd-resolved`,
`resolvconf` or similar tools, which is indicated by `/etc/resolv.conf`
just being a symlink e.g. to `/run/systemd/resolve/stub-resolv.conf`

Just skip any kind of modifications of `resolv.conf` in those cases, as
this intrudes the domain of those tools and leads to broken resolvers
and causes flip-flopping of the corresponding state.

Furthermore, it ensures no empty `search` entries are written to `resolv.conf`.

### What issues does this PR fix or reference?
None

### Previous Behavior
Using `modules.debian_ip` (e.g. through a `network.hostname` state) caused corruption of DNS resolution through empty `search` entries and modifying `resolv.conf` which might be actually runtime-managed e.g. by `systemd-resolved`.

### New Behavior
- don't touch `/etc/resolv.conf` if it's a symlink
- don't write empty `search` entries to `resolv.conf`

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by garethgreenaway — APPROVED** [review]

**Comment by rallytime** [comment]
@eliasp Looks like there is a related test failure on this: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/19233/

- unit.modules.test_debian_ip.DebianIpTestCase.test_build_network_settings

**Comment by eliasp** [comment]
@rallytime weird - I suspect this `KeyError` might have been caused by `/etc/resolv.conf` not being present in the CI environment, but I can't make really sense of this error in this context.

Replaced now the `file.readlink` usage which was a bit clumsy anyways with the right tool for the right job (which I simply didn't know about before): `file.is_link`.

Let's see what Jenkins has to say now… :)

**Comment by rallytime** [comment]
@eliasp It seems the test is still failing: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/19532/

**Comment by eliasp** [comment]
@rallytime it's still the `KeyError`:
```
Traceback (most recent call last):
  File "/testing/tests/unit/modules/test_debian_ip.py", line 254, in test_build_network_settings
    self.assertEqual(debian_ip.build_network_settings(),
  File "/testing/salt/modules/debian_ip.py", line 2102, in build_network_settings
    if not __salt__['file.is_link'](_DEB_RESOLV_FILE):
KeyError: 'file.is_link'
```
Any idea, why `__salt__['file.is_link'](_DEB_RESOLV_FILE)` would lead to a `KeyError` in this context? I don't have the slightest clue…

**Comment by cachedout** [comment]
@eliasp `__salt__['file.is_link']` just needs to be mocked in the unit test.

**Comment by rallytime** [comment]
Hi @eliasp - Were you able to come back to this after @cachedout's suggestion?

**Comment by rallytime** [comment]
I am going to close this one since we haven't heard anything back here for a while. We will be happy to reopen this again once that test is fixed up. Thanks!

**Comment by eliasp** [comment]
@rallytime I've pushed updates to the corresponding branch with the intention of finally finishing this and then also forward-porting it to 2018.3 and newer… could you re-open the PR so I can see whether my latest commit fixes the failing test?

**Comment by rallytime** [comment]
@eliasp Hrm...It looks like I am unable to open the PR again. Which is odd, that usually doesn't happen.

Can you make a new PR instead and link to this one for PR review and historical context?

**Pull request closed without merging**
