### PR TITLE
Probes state update

### PR DESCRIPTION
**Pull request by mirceaulinic**
### What does this PR do?

In pair with https://github.com/saltstack/salt/pull/37369, opening this PR for some slight changes for the probes state.

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @mirceaulinic Could you please look at the very minor lint errors? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/6449/violations/file/salt/states/probes.py/

**Comment by mirceaulinic** [comment]
Hmm... that's odd - could you please point out the issue with these lines @cachedout? I don't see what's wrong - the length is not > 120 chars. The well known phrase: "it works on my machine"

```
Global evaluation
-----------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```

**Comment by mirceaulinic** [comment]
Got it - some extra blank lines & fixed.

**Comment by mirceaulinic** [comment]
Could you please have a look also at https://github.com/saltstack/salt/pull/37369 as this state makes use of the execution module? Also https://github.com/saltstack/salt/pull/37311 might be ready if no further changes needed

**Comment by cachedout** [comment]
Go Go Jenkins!

**Pull request merged**
