### PR TITLE
Carbons status uptime

### PR DESCRIPTION
**Pull request by sjorge**
### What does this PR do?

Fixes status.uptime inside SmartOS zones.
### What issues does this PR fix or reference?
saltstack/salt#37318
### Previous Behavior

Used nawk' srand to get the current unixtimestamp, this was used to get the uptime in seconds instead of the unixtimestamp of the system's boot_time.

This failed inside a SmartOS zone
### New Behavior

We use time.time() to get a unixtimestamp instead.
### Tests written?

No
### test data

``` yaml
cronos:
    ----------
    days:
        1
    seconds:
        108374
    since_iso:
        2016-10-27T17:08:05.494677
    since_t:
        1477580885.0
    time:
        6:6
    users:
        1
mantle:
    ----------
    days:
        1
    seconds:
        108508
    since_iso:
        2016-10-27T17:05:54.715199
    since_t:
        1477587954.0
    time:
        6:8
    users:
        1
```

mantle is the hardware host, cronos is the zone that was booted a couple of minutes later.

### CODE REVIEW

**Comment by isbm** [comment]
@cachedout @sjorge LGTM :+1:
The only quite a problem I have is with that "fall-back" thing. I'd vote to remove it completely and raise an exception, because the output supposed to be a fixed structure type across the platforms. It is not nice that you never know what API is going to throw at your face.

After all, one can always `cmd.run` on minority systems.

**Comment by damon-atkins** [comment]
@sjorge Does BSD have a /proc file system?

**Comment by sjorge** [comment]
@damon-atkins OpenBSD does not:
```
[!]$ uname -a ; ls /proc/uptime
OpenBSD exosphere 6.0 GENERIC.MP#6 amd64
colorls: /proc/uptime: No such file or directory
```

**Comment by damon-atkins** [comment]
I do not have a place to test this with just a /proc file systems.    Free free to merge this code in.
Get Uptime from /proc/0 or /proc/1
```
import os.path
#import utmp
import datetime
import time

def test():

    if os.path.exists('kjdkljslkfjsdlfk'):
      print 'hello'
    elif os.path.exists('/proc/0'):
      utc_raw  = os.path.getmtime('/proc/0')
      utc_time = datetime.datetime.utcfromtimestamp(utc_raw)
    elif os.path.exists('/proc/1'):
      utc_raw  = os.path.getmtime('/proc/1')
      utc_time = datetime.datetime.utcfromtimestamp(utc_raw)

    ut_ret={}
    if 'seconds' not in ut_ret:
      # use timetuple as its avaiable on pre 2.7 python, total_seconds() is not
      ut_ret['seconds'] =  int(time.time()-time.mktime(utc_time.timetuple()))
    ut_ret['since_iso'] = utc_time.isoformat()
    ut_ret['since_t'] = time.mktime(utc_time.timetuple())
    ut_ret['days'] = ut_ret['seconds'] // 60 // 60 // 24
    hours = (ut_ret['seconds'] - (ut_ret['days'] * 24 * 60 * 60)) // 60 // 60
    minutes = ((ut_ret['seconds'] - (ut_ret['days'] * 24 * 60 * 60)) // 60) - hours * 60
    ut_ret['time'] = '{0}:{1}'.format(hours, minutes)

    print ut_ret

test()
```

**Comment by sjorge** [comment]
@damon-atkins 
This is what I get on OpenBSD, which was to be expected:
```
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    test()
  File "test.py", line 20, in test
    ut_ret['seconds'] =  int(time.time()-time.mktime(utc_time.timetuple()))
UnboundLocalError: local variable 'utc_time' referenced before assignment
```

**Comment by damon-atkins** [comment]
OK... Looks like we can not test it, once its placed inside the salt code.

**Comment by damon-atkins** [comment]
total_seconds()  does not work on my old Solaris 11 system. Running an old version of python 2.6

**Comment by sjorge** [comment]
@damon-atkins just pushed that fix, I saw your comment in the test  code 👍

**Comment by sjorge** [comment]
@isbm @cachedout yeah I'm conflicted about this too. I cleaned up the comment. Then added it back...

I'm a bit undecided I can easy remove it again. @cachedout you call I guess

**Comment by sjorge** [comment]
I actually got working test code on OpenBSD... give ma few

**Comment by sjorge** [comment]
```
root@:/opt/salt/lib/python2.7/site-packages/salt/modules # /opt/salt/bin/salt-call --local status.uptime ; uptime
local:
    ----------
    days:
        0
    seconds:
        3239
    since_iso:
        2016-10-29T17:15:34
    since_t:
        1477761334.0
    time:
        0:53
    users:
        2
 6:09PM  up 54 mins, 2 users, load averages: 0.22, 0.29, 0.31
root@:/opt/salt/lib/python2.7/site-packages/salt/modules # uname -a
FreeBSD  11.0-RELEASE-p1 FreeBSD 11.0-RELEASE-p1 #0 r306420: Thu Sep 29 01:43:23 UTC 2016     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
```

**Comment by sjorge** [comment]
So after some back and forth...
status.uptime now gives the same output on the following platforms:
- linux (using /proc/uptime)
- solaris (using kstat)
- openbsd (sysctl)
- freebsd (sysctl)

The fallback was removed again so the output is the save everywhere.

**Comment by sjorge** [comment]
Le sigh, stop the presses. NetBSD support incoming.

**Comment by isbm** [comment]
@sjorge this is mad!! :laughing: Well done!

**Comment by sjorge** [comment]
```
(salt) # salt-call --local grains.get osfinger
local:
    NetBSD-7
(salt) # salt-call --local status.uptime
local:
    ----------
    days:
        0
    seconds:
        531
    since_iso:
        2016-10-29T20:59:38
    since_t:
        1477767578.0
    time:
        0:8
    users:
        2
```

**Comment by sjorge** [comment]
NetBSD is the same as FreeBSD! I'm off to enjoy my Saturday now.

**Comment by isbm** [comment]
@sjorge Maybe you could cherrypick what @jfindlay did in https://github.com/saltstack/salt/pull/37157 ? Because it would make more sense than the other way around.

**Comment by sjorge** [comment]
I've added the tests, but I'm not sure they are working?

I get the same results before patching the SunOS and 'other' test... which should have had 2 failures I think? Can someone who is more experienced with tests have a look?

```
[.]# ./tests/runtests.py -n unit.modules.status_test
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Transplanting configuration files to '/tmp/salt-tests-tmpdir/config'
 * Current Directory: /workspace/salt
 * Test suite is running under PID 71749
 * Logging tests on /tmp/salt-runtests.log
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Starting unit.modules.status_test Tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK

============================  Overall Tests Report  ============================
***  No Problems Found While Running Tests  ************************************
================================================================================
OK (total=5, skipped=0, passed=5, failures=0, errors=0)
============================  Overall Tests Report  ============================
```

**Comment by cachedout** [comment]
Looks like we might just need to add some mocks into the unit tests. @sjorge let me know if I can help at all. This is looking really good.

**Comment by sjorge** [comment]
@cachedout Just the unit tests really. I copied the work from @jfindlay and patched it up for the changes from this PR and they pass... but I'm not sure they are working correctly or more is needed.

**Comment by cachedout** [comment]
@sjorge I still see two failures here: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/6190/

Are you saying that they're passing for you locally? I may misunderstand.

**Comment by sjorge** [comment]
@cachedout yeah they passed locally I ran:
```./tests/runtests.py -n unit.modules.status_test```

I pushed 2 new commits, one leftover cmd.run_all in the freebsd/macos code path that I removed (yay tests!) and I think I fixed the sunos test.

Probably good to squash-merge once this is ready.

**Comment by cachedout** [comment]
K. I typically squash commits on merge unless somebody specifically asks me not to. :]

If these pass with this test run then I'll get it in. Thanks sir!

**Comment by sjorge** [comment]
One failure left, let have a look

**Comment by sjorge** [comment]
@cachedout tests look good now. Can you verify?

**Comment by cachedout** [comment]
LGTM. I'll get this in. Great work as always, @sjorge

**Comment by sjorge** [comment]
@cachout can we get a back port to carbon for this as it fixes the kstat stuff already in that branch. Must have opened it against develop by mistake.

**Comment by isbm** [comment]
@sjorge  it is @cachedout :)

**Comment by sjorge** [comment]
Oops, was on mobile so autocomplete got in the way :/

~ sjorge

**Comment by sjorge** [comment]
Thanks for back-porting @rallytime !

**Comment by rallytime** [comment]
Definitely!

**Pull request merged**
