### PR TITLE
[WIP] Porting Async Batch #50546

### PR DESCRIPTION
**Pull request by dincamihai**
### What does this PR do?
Porting Async Batch #50546

### Tests written?

Yes

### Commits signed with GPG?

No

### CODE REVIEW

**Review by waynew — COMMENTED** [review]
Hey @dincamihai this is looking great - it's labeled [WIP], what else is needed here?

**Comment by DmitryKuzmenko** [comment]
@dincamihai could you please update the status of this?
Isn't it done yet?
Do you plan to finish work on this?

**Comment by dincamihai** [comment]
@DmitryKuzmenko  This had some memory issues and I can't tell if this has all the fixes. @meaksh could you add the missing patches on top of this? Thanks!

**Comment by DmitryKuzmenko** [comment]
@dincamihai thank you for update. There are also lint failures.

**Comment by DmitryKuzmenko** [comment]
@dincamihai @meaksh any chance to get an update on this?

**Comment by hybby** [comment]
Heya. Any update on this? It would be super-helpful to be able to run async jobs in batches...

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it they want to see it through to the end in a release cycle.

**Pull request closed without merging**
