### PR TITLE
Update pricing for SoftlayerHW

### PR DESCRIPTION
**Pull request by techhat**
Ping @underscorephil.

### CODE REVIEW

**Comment by techhat** [comment]
Go Go Jenkins!

**Comment by underscorephil** [comment]
@techhat I would suggest using a smaller bandwidth option. The unlimited 100mbps option is a bit costly. Eventually we need to move over to package 200, which is the new hotness for bare metal hourly.

**Comment by techhat** [comment]
Thanks Phil. The old one disappeared on me, and I didn't know what to use. 200 is a good default then?

**Comment by underscorephil** [comment]
You will want to use price ID 1800 for bandwidth. There are no longer bandwidth chunks for hourly servers, they bill at $0.09/GB.

Package 200 is the new bare metal server with hourly option that will eventually deprecate package ID 50. No rush to move over, but something to throw on the TODO.

**Comment by techhat** [comment]
@underscorephil, updated.

**Pull request merged**
