### PR TITLE
Fix hardcoded role in Azure input endpoints

### PR DESCRIPTION
**Pull request by techhat**

### CODE REVIEW

**Comment by jfindlay** [comment]
@techhat, do you realize that with this change, you've deliberately absconded from having the sole azure master?

**Comment by techhat** [comment]
@jfindlay, there can be only one techhatmaster. But I will allow other Azure masters.

**Comment by basepi** [comment]
I was mostly waiting on lint to merge this, but it appears to have failed, but with no violations. Any ideas @jfindlay?

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by techhat** [comment]
@basepi, perhaps I was destined to serve in the techhatmaster role?

**Comment by rallytime** [comment]
@basepi Something went wrong on the pylint run, so I triggered a new on.

**Comment by jfindlay** [comment]
@rallytime knows all.

**Pull request merged**
