### PR TITLE
Fixes inconsistent exception handling in rest_tornado.

### PR DESCRIPTION
**Pull request by kstreee**
### What does this PR do?

Fixes inconsistent exception handling in rest_tornado.

### What issues does this PR fix or reference?

x

### Previous Behavior

If `EauthAuthenticationError` occurred while processing API using `rest_tornado`, the client `local` returned another message in comparison to the other clients (`local_async`, `local_batch`, etc.).

### New Behavior

Return the same message with other clients. Because caller `_disbatch_` will handle the exception like the other clients.

### Tests written?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
Can we please add a test case here?

**Comment by kstreee** [comment]
@cachedout Sure, after adding some test cases about this commit and let you know.

**Comment by kstreee** [comment]
@cachedout Hi, I added a test case to check the consistency of exception handling in `rest_tornado`.

**Comment by cachedout** [comment]
@kstreee This is great! I'm really happy about the test case! Thanks so very much.

**Review by rallytime — APPROVED** [review]

**Comment by kstreee** [comment]
I found a typo, so just fixed and committed. Sorry for the typo.

**Comment by rallytime** [comment]
re-run lint

**Review by cachedout — APPROVED** [review]

**Pull request merged**
