### PR TITLE
Replace yaml usage with a helper to ensure unicode is handled properly

### PR DESCRIPTION
**Pull request by terminalmage**
Without `allow_unicode=True`, unicode characters are processed through the
`str` representer and on Python 2 are dumped as a Unicode code point (i.e.
a literal `\u0414`). This commit makes `allow_unicode=True` the default in
our `salt.utils.yamlloader.safe_dump()` helper. It also adds a new
`salt.utils.yamlloader.dump()` helper which wraps `yaml.dump()` and also
makes `allow_unicode=True` the default.

To make importing and using our custom yaml loader/dumper easier, a
convenience module called `salt.utils.yaml` has been added, which does a
wildcard import from both `salt.utils.yamldumper` and
`salt.utils.yamlloader`.

Refs to yaml.load/dump and yaml.safe_load/safe_dump have been updated to
salt.utils.yaml, to ensure that unicode is handled properly.

### CODE REVIEW

**Comment by rallytime** [comment]
re-run py3

**Comment by terminalmage** [comment]
re-run ubuntu

**Comment by terminalmage** [comment]
re-run ubuntu

**Comment by terminalmage** [comment]
re-run ubuntu

**Comment by terminalmage** [comment]
re-run ubuntu

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by terminalmage** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Review by rallytime — APPROVED** [review]

**Pull request merged**
