### PR TITLE
Make assigned IPs available to bootstrap script

### PR DESCRIPTION
**Pull request by hwhesselink**
### What does this PR do?

Make public_ips and private_ips available in the bootstrap script.

### Tests written?

No, but in production use.

### CODE REVIEW

**Comment by rallytime** [comment]
@hwhesselink Can you rebase this? It's conflicting with the develop branch now, likely because I just merged in your other change to the linode driver.

**Comment by hwhesselink** [comment]
@rallytime Oops, didn't see your comment.  I'll resubmit.

**Comment by hwhesselink** [comment]
@rallytime Resubmitted as bootstrap_ips_2

**Comment by rallytime** [comment]
Thanks!

**Pull request closed without merging**
