### PR TITLE
Allow Jinja2 templates to specify their own rendering parameters

### PR DESCRIPTION
**Pull request by Lillecarl**
### What does this PR do?

Implements the ability to add
````
#jinja2: { "lstrip_blocks": true, "trim_blocks": true }
````
(Or any other JSON dict) as options within the template itself

### What issues does this PR fix or reference?
Fixes:
https://github.com/saltstack/salt/issues/35398

### Previous Behavior
These settings can only be configured on the master, which means that if you change Jinja settings all formulas can break, which is bad for the community. Since most people probably want lstrip_blocks and trim_blocks, considering what saltstack is used for.

### New Behavior
Now every template can specify Jinja2 options to tell it how to render properly, which is great.

### Merge requirements satisfied?
- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
No

Since this is my first try at a contribution to salt and my first open-source contribution in awhile I'm all ears for input. I'll look into tests, docs, changelog and GPG (don't use GPG now so I'll have to configure it).

### CODE REVIEW

**Comment by Lillecarl** [comment]
I've now implemented some tests that make sure options can be set, overrides master.

We now remove the "#jinja2:" lines before rendering to enable the feature to be used by everyone, whatever language / format they're targeting.

**Comment by Lillecarl** [comment]
@barbaricyawps Could you bat an eye regarding docs&changelog?
I'm thinking [here](https://docs.saltproject.io/salt/user-guide/en/latest/topics/jinja.html#using-the-jinja-renderer) would be a good place to describe this added functionality, what do you think? 😄

**Comment by Lillecarl** [comment]
Tagged as ready for review even though there are no docs other than changelog and comments yet. Eager for feedback ❣️

**Comment by Lillecarl** [comment]
@dwoz Do you have any input? :)

**Comment by Lillecarl** [comment]
@dwoz Do you have any feedback? 😄

**Comment by ggiesen** [comment]
@Lillecarl Should this work with `file.managed`? I've been testing this and not been able to make it work so far (3005 Onedir)

**Comment by ggiesen** [comment]
@Lillecarl,

Here's how I'm testing so you can reproduce:

```
> mkdir salt-jinja && cd salt-jinja && vagrant init almalinux/8 && vagrant up && vagrant ssh

[vagrant@localhost ~]$ sudo rpm --import https://repo.saltproject.io/salt/py3/redhat/8/x86_64/3005/SALTSTACK-GPG-KEY.pub
[vagrant@localhost ~]$ curl -fsSL https://repo.saltproject.io/salt/py3/redhat/8/x86_64/3005.repo | sudo tee /etc/yum.repos.d/salt.repo
[vagrant@localhost ~]$ sudo dnf install -y salt-master salt-minion


[vagrant@localhost ~]$ cat << EOF | tee ~/salt_63746.patch
--- a/salt/utils/templates.py     2023-01-06 22:49:46.000000000 +0000
+++ b/salt/utils/templates.py     2023-03-23 14:16:54.924826967 +0000
@@ -7,6 +7,7 @@
 import sys
 import tempfile
 import traceback
+import json
 from pathlib import Path

 import jinja2
@@ -417,10 +418,56 @@
             else:
                 log.warning("Jinja2 environment %s is not recognized", k)

+    def parse_jinja_file_opts(tmplstr: str, env: str):
+        # Same Jinja override prefix as Ansible
+        # Instead of complex parsing logic we use JSON as config format
+        JINJA2_OVERRIDE = "#jinja2:"
+
+        # Template string split into list of string
+        tmpllines = tmplstr.splitlines()
+        # Lines to be removed, we do this to enable usage of this feature in
+        # any target language/format not everything supports # as comments.
+        removelines: list[str] = list()
+
+        # Loop starting lines beginning with # or are empty
+        for line in tmpllines:
+            # We only support one-line JSON dicts.
+            if not line.startswith(JINJA2_OVERRIDE):
+                continue
+
+            # Remove JINJA2_OVERRIDE prefix from line
+            jstring = line.replace(JINJA2_OVERRIDE, "")
+            try:
+                # Try parsing the remainder of the line as JSON
+                jdata = json.loads(jstring)
+                # JSON parsing succeeded, pass dict to helper injecting options to renderer
+                opt_jinja_env_helper(jdata, env)
+                # Add line for removal
+                removelines.append(line)
+            except:
+                # Should we log more here?
+                log.warning("Unable to parse Jinja2 options string")
+
+        # Remove jinja2 option line(s)
+        for line in removelines:
+            tmpllines.remove(line)
+
+        # Reassemble lines array into template string
+        return str(newline).join(tmpllines)
+
+    optname: str = "jinja_env"
+    renderoptions: dict[str, str] = opt_jinja_env
+
+
     if "sls" in context and context["sls"] != "":
-        opt_jinja_env_helper(opt_jinja_sls_env, "jinja_sls_env")
-    else:
-        opt_jinja_env_helper(opt_jinja_env, "jinja_env")
+        optname = "jinja_sls_env"
+        renderoptions = opt_jinja_sls_env
+
+    # Parse configured options into Jinja rendering options
+    opt_jinja_env_helper(renderoptions, "jinja_env")
+    # Parse template, look for jinja rendering options to set
+    # Update template string, we remove jinja option lines from template
+    tmplstr = parse_jinja_file_opts(tmplstr, "jinja_fileopts")

     if opts.get("allow_undefined", False):
         jinja_env = jinja2.sandbox.SandboxedEnvironment(**env_args)
EOF

[vagrant@localhost ~]$ cd /opt/saltstack/salt/run && sudo patch -p1 < ~/salt_63746.patch && cd ~

[vagrant@localhost ~]$ sudo mkdir /srv/salt && sudo mkdir /srv/salt/files

[vagrant@localhost ~]$ cat << EOF | sudo tee /srv/salt/state.sls
file_/tmp/file.txt:
  file.managed:
    - name: /tmp/file.txt
    - source: salt://files/template.j2
    - user: root
    - group: root
    - mode: '0644'
    - template: jinja
EOF

[vagrant@localhost ~]$ cat << EOF | sudo tee /srv/salt/files/template.j2
#jinja2: { "lstrip_blocks": true, "trim_blocks": true }
{% for n in range(1,10) %}
 text{{ n }}
{% endfor %}
EOF

[vagrant@localhost ~]$ sudo echo "127.0.0.1   salt" >> /etc/hosts
[vagrant@localhost ~]$ sudo echo "id: salt-minion" >> /etc/salt/minion.d/minion.conf

[vagrant@localhost ~]$ sudo systemctl enable salt-master && sudo systemctl start salt-master
[vagrant@localhost ~]$ sudo systemctl enable salt-minion && sudo systemctl start salt-minion
[vagrant@localhost ~]$ sudo salt-key -A -y

[vagrant@localhost ~]$ sudo salt salt-minion state.apply state

[vagrant@localhost ~]$ cat /tmp/file.txt 
#jinja2: { "lstrip_blocks": true, "trim_blocks": true }

 text1

 text2

 text3

 text4

 text5

 text6

 text7

 text8

 text9

# Try with the master trim_blocks/lstrip_blocks:
[vagrant@localhost ~]$ cat << EOF | sudo tee /etc/salt/master.d/master.conf
jinja_env:
  trim_blocks: True
  lstrip_blocks: True
EOF

[vagrant@localhost ~]$ sudo systemctl restart salt-master && sudo systemctl restart salt-minion

[vagrant@localhost ~]$ sudo salt salt-minion state.apply state

[vagrant@localhost ~]$ cat /tmp/file.txt 
#jinja2: { "lstrip_blocks": true, "trim_blocks": true }
 text1
 text2
 text3
 text4
 text5
 text6
 text7
 text8
 text9

**Comment by ggiesen** [comment]
@Lillecarl Also note the PR needs to be rebased as there have been changes merged to templates.py since it was created.

**Comment by Lillecarl** [comment]
Rebased. As mentioned in Slack I'll have a look at reproducing your issues next week! 😄

**Comment by Lillecarl** [comment]
https://asciinema.org/a/5cwyGzWONgP0aJXf04fpZXroV With your vagrant setup i was able to reproduce your issue.

But in my NixOS setup I was unable to reproduce: https://asciinema.org/a/qsWfmwWZY6KZ5sIOGlT3b8Acv

I'll look into it further, just thought I'd share an update. Very odd 🤷🏿

**Comment by ggiesen** [comment]
I've been playing around with inserting some debug statements this but no closer to understanding what's broken. I've put debug statements on either side of:

https://github.com/saltstack/salt/blob/eaeccf72c62f153e4408996c01e1032b27aa9b12/salt/modules/file.py#L4800-L4815

And I see both of them show up, but anything I put in [salt/utils/templates.](https://github.com/saltstack/salt/blob/master/salt/utils/templates.py), does not show up. I don't understand how the function wrapping works well enough, perhaps debug statements don't pass through the function wrapping.

**Comment by ggiesen** [comment]
I'm not at all experienced with pdb, but I set a breakpoint at https://github.com/saltstack/salt/blob/eaeccf72c62f153e4408996c01e1032b27aa9b12/salt/modules/file.py#L4800 (I can't seem to set one inside of https://github.com/saltstack/salt/blob/master/salt/utils/templates.py) and stepped through the code until I got to this point:

```
> /opt/saltstack/salt/run/salt/salt/utils/templates.py(432)render_jinja_tmpl()
-> # Loop starting lines beginning with # or are empty
(Pdb) s
> /opt/saltstack/salt/run/salt/salt/utils/templates.py(433)render_jinja_tmpl()
-> for line in tmpllines:
(Pdb) p line
*** NameError: name 'line' is not defined
(Pdb) p tmpllines
*** NameError: name 'tmpllines' is not defined
(Pdb) s
> /opt/saltstack/salt/run/salt/salt/utils/templates.py(434)render_jinja_tmpl()
-> # We only support one-line JSON dicts.
(Pdb) p line
*** NameError: name 'line' is not defined
(Pdb) s
> /opt/saltstack/salt/run/salt/salt/utils/templates.py(435)render_jinja_tmpl()
-> if not line.startswith(JINJA2_OVERRIDE):
(Pdb) p line
*** NameError: name 'line' is not defined
(Pdb) p JINJA2_OVERRIDE
*** NameError: name 'JINJA2_OVERRIDE' is not defined
```

I'm not sure if that's at all helpful, but it appears `tmpllines` and 'JINJA2_OVERRIDE' is not being set correctly, and therefore the loop to check the first line for the JSON config string is not working as a result.

**Comment by ggiesen** [comment]
@Lillecarl, so this appears to be a Tiamat-related bug. Testing with 3005 Classic works:

```
> mkdir salt-jinja && cd salt-jinja && vagrant init almalinux/8 && vagrant up && vagrant ssh

[vagrant@localhost ~]$ sudo rpm --import https://repo.saltproject.io/py3/redhat/8/x86_64/3005/SALTSTACK-GPG-KEY.pub
[vagrant@localhost ~]$ curl -fsSL https://repo.saltproject.io/py3/redhat/8/x86_64/3005.repo | sudo tee /etc/yum.repos.d/salt.repo
[vagrant@localhost ~]$ sudo dnf install -y patch salt-master salt-minion

[vagrant@localhost ~]$ cat << EOF | tee ~/salt_63746.patch
--- a/salt/utils/templates.py     2023-01-06 22:49:46.000000000 +0000
+++ b/salt/utils/templates.py     2023-03-23 14:16:54.924826967 +0000
@@ -7,6 +7,7 @@
 import sys
 import tempfile
 import traceback
+import json
 from pathlib import Path

 import jinja2
@@ -417,10 +418,56 @@
             else:
                 log.warning("Jinja2 environment %s is not recognized", k)

+    def parse_jinja_file_opts(tmplstr: str, env: str):
+        # Same Jinja override prefix as Ansible
+        # Instead of complex parsing logic we use JSON as config format
+        JINJA2_OVERRIDE = "#jinja2:"
+
+        # Template string split into list of string
+        tmpllines = tmplstr.splitlines()
+        # Lines to be removed, we do this to enable usage of this feature in
+        # any target language/format not everything supports # as comments.
+        removelines: list[str] = list()
+
+        # Loop starting lines beginning with # or are empty
+        for line in tmpllines:
+            # We only support one-line JSON dicts.
+            if not line.startswith(JINJA2_OVERRIDE):
+                continue
+
+            # Remove JINJA2_OVERRIDE prefix from line
+            jstring = line.replace(JINJA2_OVERRIDE, "")
+            try:
+                # Try parsing the remainder of the line as JSON
+                jdata = json.loads(jstring)
+                # JSON parsing succeeded, pass dict to helper injecting options to renderer
+                opt_jinja_env_helper(jdata, env)
+                # Add line for removal
+                removelines.append(line)
+            except:
+                # Should we log more here?
+                log.warning("Unable to parse Jinja2 options string")
+
+        # Remove jinja2 option line(s)
+        for line in removelines:
+            tmpllines.remove(line)
+
+        # Reassemble lines array into template string
+        return str(newline).join(tmpllines)
+
+    optname: str = "jinja_env"
+    renderoptions: dict[str, str] = opt_jinja_env
+
+
     if "sls" in context and context["sls"] != "":
-        opt_jinja_env_helper(opt_jinja_sls_env, "jinja_sls_env")
-    else:
-        opt_jinja_env_helper(opt_jinja_env, "jinja_env")
+        optname = "jinja_sls_env"
+        renderoptions = opt_jinja_sls_env
+
+    # Parse configured options into Jinja rendering options
+    opt_jinja_env_helper(renderoptions, "jinja_env")
+    # Parse template, look for jinja rendering options to set
+    # Update template string, we remove jinja option lines from template
+    tmplstr = parse_jinja_file_opts(tmplstr, "jinja_fileopts")

     if opts.get("allow_undefined", False):
         jinja_env = jinja2.sandbox.SandboxedEnvironment(**env_args)
EOF

[vagrant@localhost ~]$ cd /usr/lib/python3.6/site-packages && sudo patch -p1 < ~/salt_63746.patch && cd ~

[vagrant@localhost ~]$ sudo mkdir /srv/salt && sudo mkdir /srv/salt/files

[vagrant@localhost ~]$ cat << EOF | sudo tee /srv/salt/state.sls
file_/tmp/file.txt:
  file.managed:
    - name: /tmp/file.txt
    - source: salt://files/template.j2
    - user: root
    - group: root
    - mode: '0644'
    - template: jinja
EOF

[vagrant@localhost ~]$ cat << EOF | sudo tee /srv/salt/files/template.j2
#jinja2: { "lstrip_blocks": true, "trim_blocks": true }
{% for n in range(1,10) %}
 text{{ n }}
{% endfor %}
EOF

[vagrant@localhost ~]$ echo "127.0.0.1   salt" | sudo tee -a /etc/hosts
[vagrant@localhost ~]$ echo "id: salt-minion" | sudo tee /etc/salt/minion.d/minion.conf

[vagrant@localhost ~]$ sudo systemctl enable salt-master && sudo systemctl start salt-master
[vagrant@localhost ~]$ sudo systemctl enable salt-minion && sudo systemctl start salt-minion
[vagrant@localhost ~]$ sudo salt-key -A -y

[vagrant@localhost ~]$ sudo salt salt-minion state.apply state

[vagrant@localhost ~]$ cat /tmp/file.txt
 text1
 text2
 text3
 text4
 text5
 text6
 text7
 text8
 text9
```

As well as 3006rc3 relenv:

```
> mkdir salt-jinja && cd salt-jinja && vagrant init almalinux/8 && vagrant up && vagrant ssh

[vagrant@localhost ~]$ sudo rpm --import https://staging.repo.saltproject.io/salt_rc/salt/py3/redhat/8/x86_64/minor/latest/SALT-PROJECT-GPG-PUBKEY-2023.pub
[vagrant@localhost ~]$ curl -fsSL https://staging.repo.saltproject.io/salt_rc/salt/py3/redhat/8/x86_64/3006.repo | sudo tee /etc/yum.repos.d/salt.repo
[vagrant@localhost ~]$ sudo dnf install -y patch salt-master salt-minion

[vagrant@localhost ~]$ cat << EOF | tee ~/salt_63746.patch
--- a/salt/utils/templates.py    2023-03-29 19:52:38.000000000 +0000
+++ b/salt/utils/templates.py    2023-04-04 04:11:36.360505024 +0000
@@ -7,6 +7,7 @@
 import sys
 import tempfile
 import traceback
+import json
 from pathlib import Path

 import jinja2
@@ -419,10 +420,56 @@
             else:
                 log.warning("Jinja2 environment %s is not recognized", k)

+    def parse_jinja_file_opts(tmplstr: str, env: str):
+        # Same Jinja override prefix as Ansible
+        # Instead of complex parsing logic we use JSON as config format
+        JINJA2_OVERRIDE = "#jinja2:"
+
+        # Template string split into list of string
+        tmpllines = tmplstr.splitlines()
+        # Lines to be removed, we do this to enable usage of this feature in
+        # any target language/format not everything supports # as comments.
+        removelines: list[str] = list()
+
+        # Loop starting lines beginning with # or are empty
+        for line in tmpllines:
+            # We only support one-line JSON dicts.
+            if not line.startswith(JINJA2_OVERRIDE):
+                continue
+
+            # Remove JINJA2_OVERRIDE prefix from line
+            jstring = line.replace(JINJA2_OVERRIDE, "")
+            try:
+                # Try parsing the remainder of the line as JSON
+                jdata = json.loads(jstring)
+                # JSON parsing succeeded, pass dict to helper injecting options to renderer
+                opt_jinja_env_helper(jdata, env)
+                # Add line for removal
+                removelines.append(line)
+            except:
+                # Should we log more here?
+                log.warning("Unable to parse Jinja2 options string")
+
+        # Remove jinja2 option line(s)
+        for line in removelines:
+            tmpllines.remove(line)
+
+        # Reassemble lines array into template string
+        return str(newline).join(tmpllines)
+
+    optname: str = "jinja_env"
+    renderoptions: dict[str, str] = opt_jinja_env
+
+
     if "sls" in context and context["sls"] != "":
-        opt_jinja_env_helper(opt_jinja_sls_env, "jinja_sls_env")
-    else:
-        opt_jinja_env_helper(opt_jinja_env, "jinja_env")
+        optname = "jinja_sls_env"
+        renderoptions = opt_jinja_sls_env
+
+    # Parse configured options into Jinja rendering options
+    opt_jinja_env_helper(renderoptions, "jinja_env")
+    # Parse template, look for jinja rendering options to set
+    # Update template string, we remove jinja option lines from template
+    tmplstr = parse_jinja_file_opts(tmplstr, "jinja_fileopts")

     if opts.get("allow_undefined", False):
         jinja_env = jinja2.sandbox.SandboxedEnvironment(**env_args)
EOF

[vagrant@localhost ~]$ cd /opt/saltstack/salt/lib/python3.10/site-packages/ && sudo patch -p1 < ~/salt_63746.patch && cd ~ 

[vagrant@localhost ~]$ sudo mkdir /srv/salt && sudo mkdir /srv/salt/files

[vagrant@localhost ~]$ cat << EOF | sudo tee /srv/salt/state.sls
file_/tmp/file.txt:
  file.managed:
    - name: /tmp/file.txt
    - source: salt://files/template.j2
    - user: root
    - group: root
    - mode: '0644'
    - template: jinja
EOF

[vagrant@localhost ~]$ cat << EOF | sudo tee /srv/salt/files/template.j2
#jinja2: { "lstrip_blocks": true, "trim_blocks": true }
{% for n in range(1,10) %}
 text{{ n }}
{% endfor %}
EOF

[vagrant@localhost ~]$ echo "127.0.0.1   salt" | sudo tee -a /etc/hosts
[vagrant@localhost ~]$ echo "id: salt-minion" | sudo tee /etc/salt/minion.d/minion.conf

[vagrant@localhost ~]$ sudo systemctl enable salt-master && sudo systemctl start salt-master
[vagrant@localhost ~]$ sudo systemctl enable salt-minion && sudo systemctl start salt-minion
[vagrant@localhost ~]$ sudo salt-key -A -y

[vagrant@localhost ~]$ sudo salt salt-minion state.apply state

[vagrant@localhost ~]$ cat /tmp/file.txt
 text1
 text2
 text3
 text4
 text5
 text6
 text7
 text8
 text9
```

I'll continue poking this, but from my perspective, LGTM.

**Comment by Lillecarl** [comment]
I've rebased again. Thanks for the further testing @ggiesen, I'd say it's ready for primetime 😄

**Comment by ggiesen** [comment]
> @barbaricyawps Could you bat an eye regarding docs&changelog? I'm thinking [here](https://docs.saltproject.io/salt/user-guide/en/latest/topics/jinja.html#using-the-jinja-renderer) would be a good place to describe this added functionality, what do you think? 😄

It probably also needs a reference in [salt.renderers.jinja](https://docs.saltproject.io/en/latest/ref/renderers/all/salt.renderers.jinja.html) and maybe [here](https://docs.saltproject.io/en/latest/ref/configuration/master.html#std-conf_master-jinja_env) and [here](https://docs.saltproject.io/en/latest/ref/configuration/master.html#jinja-sls-env).

**Review by whytewolf — DISMISSED** [review]

**Review by twangboy — DISMISSED** [review]

**Comment by ggiesen** [comment]
Docs are done, this should be merge-ready.

**Review by whytewolf — DISMISSED** [review]

**Comment by Lillecarl** [comment]
@ggiesen i owe you one itchy feature implementation 😄

**Review by Ch3LL — CHANGES_REQUESTED** [review]
Just one small change request, and there looks to be a merge conflict that needs to be resolved.

**Comment by ggiesen** [comment]
@Lillecarl 

I've been poking at this more now that 3006.1 is out and is fairly usable... and I've see to have found a couple issues:

1) If using a jinja include block `{% include 'file.j2' %}` with a file that also has the header, the header is printed.
2) It seems to be chopping off the last trailing newline from the file on include blocks

I'll work on getting clean test cases for you, but I've spent the last couple hours poking at this

**Comment by ziz** [comment]
@ggiesen 
> 1. If using a jinja include block `{% include 'file.j2' %}` with a file that also has the header, the header is printed.

This is also the behavior in ansible, fwiw.  The `lstrip_blocks`/`trim_blocks` options are set on the jinja Environment, which is (designed to be) static throughout the entirety of a single template's load, including all of the additional files that might be pulled in with `{% include %}` or similar, so only the top-level template will realistically be impacted without tearing into Jinja internals in a significant way.

A _partial_ solution might be to look for a Jinja comment on the first line, like
```{# #jinja2: {json blob} #}``` 
except looking for the Jinja environment `comment_start_string` and `comment_end_string` rather than `{#` and `#}`.  That way, even if the override will not take effect (because the file was included rather than rendered at the top level), the magic line will likely not render.

Two edge cases:
1. In situations where `comment_start_string` and `comment_end_string` are changed globally but a file includes default jinja syntax comments, the magic line will still render in the output.  This is a low risk issue; many other things are likely to break if the comment delimiters are changed and template files are shared with other installs that have different configurations.
2. A similar concern, but if the delimiters are changed _locally_.  This could be handled by restricting the options that the magic line can reset to "things that aren't the comment delimiters", if desired.

**Comment by Lillecarl** [comment]
@ziz That format would indeed solve the issue. I'm not using salt since my job change, but I'll see if I can get a masterless setup going and implement it either way. It's pretty awful that this feature doesn't exist.

**Comment by Ch3LL** [comment]
Any updates here?

**Comment by Lillecarl** [comment]
I'd recommend VMware to implement this on their own considering the lack of interest in community contributions. It's a simple feature, but it's obvious external contributions are held to a different and higher standard (seen on cloudflare contributions too) than internal ones, I don't use Salt anymore and will not spend my free time swimming upstream.

**Comment by andreasdijkman** [comment]
@dwoz Is it possible to put this on the list of Broadcom/VMware to implement? As seen in this thread it's almost done and it would solve a lot of headaches with formatting of templates.

**Comment by andreasdijkman** [comment]
I already did that but some side effects are really annoying. Inline content from pillar-data for example can't be indented for example because of global lstrip-settings that are applied after all the template-rendering.

**Pull request closed without merging**
