### PR TITLE
gpg: Fix ownership in delete_key()

### PR DESCRIPTION
**Pull request by lubo**
### What issues does this PR fix or reference?

See the commit message.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by Ch3LL — CHANGES_REQUESTED** [review]
this will require test coverage and a changelog entry.

**Comment by lubo** [comment]
Hi @Ch3LL, thanks for the reply. I've taken a look at the `gpg` tests briefly and it seems like there isn't even a similar test case. If that's so, then unfortunately, I'm not willing to put in the necessary effort in the near future. I hope somebody else will be able to pick this up.

**Comment by Ch3LL** [comment]
I do see some `delete_key` tests in `tests/unit/modules/test_gpg.py` that you could start from. I'm definitely willing to help give more direction if needed.

**Comment by lubo** [comment]
What I meant is there are no tests for `_restore_ownership` and since I haven't added or modified that functionality, it sounds like an out-of-the-scope request to me.

**Comment by Ch3LL** [comment]
I'm willing to help write one here if you share with me the use case you are trying to fix.

Can you provide:

**Comment by lubo** [comment]
Command: `sudo salt-call state.highstate`
State:

```sls
remove old pgp key:
  module.run:
    - name: gpg.delete_key
    - fingerprint: <fingerprint>
    - delete_secret: True
    - user: <non-root-user>
```

This causes the keyring ownership to be changed to `root`, which makes `<non-root-user>` unable to access it. It's my understanding that `_restore_ownership` decorator exists to solve this issue in other `gpg` functions with side effects like `create_key`.

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
