### PR TITLE
Update pythonnet to 3.0.1 to support Python 3.10

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?
Updates pythonnet to 3.0.1 to support python 3.10 on Windows

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by Ch3LL** [comment]
pre-commit is failing

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
@twangboy the windows failures are valid and likely due to the new library version.

**Comment by twangboy** [comment]
Yeah, pre-commit doesn't run on Windows so I have to do all this stuff by hand.

**Comment by s0undt3ch** [comment]
> Yeah, pre-commit doesn't run on Windows so I have to do all this stuff by hand.

The windows tests don't start with this new version. Can you have a look a fix that?

**Comment by s0undt3ch** [comment]
Not today, of course 😁

**Comment by twangboy** [comment]
Looks like the new version of pythonnet may have broken one of the grains

**Review by s0undt3ch — APPROVED** [review]

**Pull request merged**
