### PR TITLE
WIP: Fix repobuild

### PR DESCRIPTION
**Pull request by github-abcde**
### What does this PR do?
It fixes several problems with the `rpmbuild.py`-module:
- make_repo can be used to sign packages, but it only signed packages in the root of `repodir`. This has been changed to recursively walk the filesystem (without following symlinks).
- make_repo: Documentation of the keyid-parameter included information about storing private keys in the pillar, however this specific pillar-data is never used. Removed this documentation and added a bit to explain how the pillar variables *are* used.
- make_repo: Documentation of the keyid-parameter did not mention that only the last 8 hex-digits of the GPG-keyid should be supplied. This has been added.
- make_repo: The command used to sign packages is executed via salt.utils.vt.Terminal, however the `gnupghome`-parameter was not used here, causing package signing to fail. It has been added to the `env`-paramater passed to the proc.

This commit also includes some small pylint-inspired changes.

### What issues does this PR fix or reference?
None that I'm aware of.

### Previous Behavior
- make_repo does not sign packages if GNUPGHOME environment variable is not set correctly on the minion it is executed on, even though a `gnupghome`-parameter is available.
- make_repo only signs packages in the root of the supplied `repodir`.

### New Behavior
- make_repo signs packages in all subdirs of the supplied `repodir`.
- make_repo signs packages even if the GNUPGHOME environment variable is not present on the minion it is executed on.

### Tests written?
No

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by dmurphy18 — COMMENTED** [review]
Thanks for the great  work.
I did have a walking version internally but dropped it due to time constraints, so great to have this. Some of these changes are applicable to debbbuild.py too, env will help with some gpg issues experiencing on Raspbian.

There is an issue around directory walking in the new code.  Currently due to historical customer issues, SaltStack ships a base copy of some original Centos 7 rpms in the base sub-directory and these are signed with the original Centos 7 signing key.  The walk code needs to skip this special base sub-directory otherwise resigning them with a different key.  I had to do that and similar on Debian family to ignore conf, db, dists, pool too.

Can you make that change allowing for the base and the repodata sub-directory, repodata to prevent needless walk and any possible further side-effects

**Comment by github-abcde** [comment]
@dmurphy18 Sure, would you prefer to avoid re-signing packages altogether, or just skip some dirs?
In case it is the latter, could you point out where exactly you are referring to with 'SaltStack ships a base copy of some original Centos 7 rpms in the base sub-directory'? (And other directories you are referring to; I can't find any preinstalled rpm's on a freshly provisioned-and-bootstrapped Amazon EC2 instance, nor can I find a 'repodata' directory, so I'm assuming I'm missing a bit of context :) )

**Comment by dmurphy18** [comment]
@github-abcde Sorry for delay in reply, SaltStack is in process of moving offices.  The base sub-directory can be seen here, http://repo.saltstack.com/yum/redhat/7/x86_64/latest/base.  As for the sub-directory repodata, it is created as a by-product of the creation/signing process and can also be found here http://repo.saltstack.com/yum/redhat/7/x86_64/latest/repodata.  

Hence I believe the best approach would be to have a list of excluded sub-directories and skip members of that list when performing the directory walk. This prevents re-signing the already signed Centos 7 rpms, and any possible side affects now or in the future in repodata.

The base sub-directory only exists for Redhat 7.  The current Amazon Linux 1 is based on Redhat 6 (implies no base sub-directory). However the beta Amazon Linux 2 appears to be based on Redhat 7, and after a small adjustment in the install repo for Amazon Linux 2, it appears that the Redhat 7 rpms for Salt are functional on Amazon Linux 2.

**Comment by cachedout** [comment]
@github-abcde Just checking in here. Are you planning on coming back to this?

**Comment by github-abcde** [comment]
@cachedout Certainly, however it might take a bit of time. I'm only available to work on salt for about 1 day a week.
Also, there are other improvements I have made to the `rpmbuild.py`, which I'll have to port to `debbuild.py` along with dmurphy18's requests.

**Comment by rallytime** [comment]
@github-abcde Just checking in here. Were you able to come back to this? If so, it will need a rebase as well.

**Comment by github-abcde** [comment]
@rallytime Certainly, I'll try to squeeze some work in tomorrow. I've had to prioritize some other projects and as such unfortunately haven't had time to work on this.

**Comment by rallytime** [comment]
Since we haven't heard back on this yet, I am going to close this. When you're ready to incorporate that feedback we can of course open this up again and will do so gladly. :)

If it's easier for you to just open a new PR, then that is fine too, just be sure to link back to this one for context.

Also, this has a merge-conflict now in `rpmbuild.py`, so this will need to be rebased against the HEAD of the branch and fixed up as well.

Thank you for your work here and please let us know if you have any questions!

**Pull request closed without merging**
