### PR TITLE
TheBigBear add winrepo "wusa" support [WIP]

### PR DESCRIPTION
**Pull request by TheBigBear**
!!! Do NOT merge yet! WIP !!!

@twangboy @alxbse (thanks Alexander for the pointer) I now tried adding `wusa` support trying to copy the existing `msiexec` support. 

But I am missing something. As it still tells me that it can't find the installer for a `wusa`sls file "`no installer:`". 
Can you point me in the right direction, please?

I have created a winrepo sls file for the `Windows Management Framework 5.0 Production Preview (KB3066439)` (that contains powershell 5 and oneget etc - installable to any win >= win7), the only line I have added is a `wusa: True`
here is the sls file:

``` saltstack
# source: https://www.microsoft.com/en-us/download/details.aspx?id=48729
#
# http://download.microsoft.com/download/3/F/D/3FD04B49-26F9-4D9A-8C34-4533B9D5B020/W2K12-KB3066438-x64.msu
# http://download.microsoft.com/download/3/F/D/3FD04B49-26F9-4D9A-8C34-4533B9D5B020/Win7AndW2K8R2-KB3066439-x64.msu
# http://download.microsoft.com/download/3/F/D/3FD04B49-26F9-4D9A-8C34-4533B9D5B020/Win7AndW2K8R2-KB3066439-x86.msu
# http://download.microsoft.com/download/3/F/D/3FD04B49-26F9-4D9A-8C34-4533B9D5B020/Win8.1AndW2K12R2-KB3066437-x64.msu
# http://download.microsoft.com/download/3/F/D/3FD04B49-26F9-4D9A-8C34-4533B9D5B020/Win8.1AndW2K12R2-KB3066437-x86.msu
wmf5pp:
  Not Found:
    full_name: 'Windows Management Framework 5.0 Production Preview (KB3066439)'
    {% if grains['cpuarch'] == 'AMD64' %}
      {% if salt['pkg.compare_versions'](grains['osversion'], '==', '6.2') %}
      installer: 'http://download.microsoft.com/download/3/F/D/3FD04B49-26F9-4D9A-8C34-4533B9D5B020/W2K12-KB3066438-x64.msu'
      {% elif salt['pkg.compare_versions'](grains['osversion'], '==', '6.1') %}
      installer: 'http://download.microsoft.com/download/3/F/D/3FD04B49-26F9-4D9A-8C34-4533B9D5B020/Win7AndW2K8R2-KB3066439-x64.msu'
      {% elif salt['pkg.compare_versions'](grains['osversion'], '==', '6.3') %}
      installer: 'http://download.microsoft.com/download/3/F/D/3FD04B49-26F9-4D9A-8C34-4533B9D5B020/Win8.1AndW2K12R2-KB3066437-x64.msu'
      {% endif %}
    {% elif grains['cpuarch'] == 'x86' %}
      {% if salt['pkg.compare_versions'](grains['osversion'], '==', '6.1') %}
      installer: 'http://download.microsoft.com/download/3/F/D/3FD04B49-26F9-4D9A-8C34-4533B9D5B020/Win7AndW2K8R2-KB3066439-x86.msu'
      {% elif salt['pkg.compare_versions'](grains['osversion'], '==', '6.3') %}
      installer: 'http://download.microsoft.com/download/3/F/D/3FD04B49-26F9-4D9A-8C34-4533B9D5B020/Win8.1AndW2K12R2-KB3066437-x86.msu'
      {% endif %}
    {% endif %}
    install_flags: '/quiet /norestart'
    {% if grains['cpuarch'] == 'AMD64' %}
      {% if salt['pkg.compare_versions'](grains['osversion'], '==', '6.2') %}
      uninstaller: 'http://download.microsoft.com/download/3/F/D/3FD04B49-26F9-4D9A-8C34-4533B9D5B020/W2K12-KB3066438-x64.msu'
      {% elif salt['pkg.compare_versions'](grains['osversion'], '==', '6.1') %}
      uninstaller: 'http://download.microsoft.com/download/3/F/D/3FD04B49-26F9-4D9A-8C34-4533B9D5B020/Win7AndW2K8R2-KB3066439-x64.msu'
      {% elif salt['pkg.compare_versions'](grains['osversion'], '==', '6.3') %}
      uninstaller: 'http://download.microsoft.com/download/3/F/D/3FD04B49-26F9-4D9A-8C34-4533B9D5B020/Win8.1AndW2K12R2-KB3066437-x64.msu'
      {% endif %}
    {% elif grains['cpuarch'] == 'x86' %}
      {% if salt['pkg.compare_versions'](grains['osversion'], '==', '6.1') %}
      uninstaller: 'http://download.microsoft.com/download/3/F/D/3FD04B49-26F9-4D9A-8C34-4533B9D5B020/Win7AndW2K8R2-KB3066439-x86.msu'
      {% elif salt['pkg.compare_versions'](grains['osversion'], '==', '6.3') %}
      uninstaller: 'http://download.microsoft.com/download/3/F/D/3FD04B49-26F9-4D9A-8C34-4533B9D5B020/Win8.1AndW2K12R2-KB3066437-x86.msu'
      {% endif %}
    {% endif %}
    uninstall_flags: '/quiet /norestart'
    msiexec: False
    wusa: True
    locale: en_US
    reboot: False
```

But when running it on this branch I still get:

```
C:\>salt-call pkg.install wmf5pp
[ERROR   ] No installer configured for version Not Found of package wmf5pp
local:
    ----------
    wmf5pp:
        ----------
        no installer:
            Not Found
```

PS: 
BTW the 'strange' version number in the second line "  Not Found:", is (hopefully) only temporary, until I can see what version winrepo detects it as in the windows registry. (and for those pkgs that don't set a version in the registry it stays a bit more permanently. ;-)

About MS wusa:
https://support.microsoft.com/en-us/kb/934307

### CODE REVIEW

**Comment by TheBigBear** [comment]
@twangboy the issue raised in implementing this ```wusa``` ```*.msu``` installer support in https://github.com/saltstack/salt/issues/27193 has now been tested and works for me. 

The winrepo file I tested it with is:
"```https://github.com/saltstack/salt-winrepo-ng/blob/master/wmf5pp.sls```"

Any chance this can even be merged back into 2015.8 branch maybe for 2015.8.1 (or before?)

**Comment by TheBigBear** [comment]
@twangboy please hold fire on this one. 

Just had an ```error 87``` returned that I need to investigate. 

Will update this when it is ready and then also remove the first line in top comment once it is no longer WIP.

**Comment by cachedout** [comment]
Edited title to reflect WIP.

**Comment by TheBigBear** [comment]
This is not suitable to be installed by winrepo, as the installed software is not being show by the built-in add/remove software controls. 
This will have to be a standalone sls installation recipe.

**Pull request closed without merging**
