### PR TITLE
Fixed returned path for virtualenv pip binary on Windows

### PR DESCRIPTION
**Pull request by opdude**
- Makes sure we have the slashes correctly escaped

### CODE REVIEW

**Comment by jfindlay** [comment]
@UtahDave

**Comment by UtahDave** [comment]
@opdude shouldn't the os.path.join take care of the proper path separator? Or does virtualenv need the `\\`?

**Comment by opdude** [comment]
That is indeed what I thought, I tried the following state.

    test:
      virtualenv.managed:
        - name: C:/Users/builduser/buildbot-venv
        - system_site_packages: False
        - requirements: salt://common/yumi/requirements.txt

Which gave me the following return
    ----------
              ID: test
        Function: virtualenv.managed
            Name: C:\Users\builduser/buildbot-venv
          Result: False
         Comment: An exception occurred in this state: Traceback (most recent call last):
                    File "c:\users\builduser\salt\salt\state.py", line 1551, in call
                      **cdata['kwargs'])
                    File "c:\users\builduser\salt\salt\states\virtualenv_mod.py", line 183, in managed
                      before = set(__salt__['pip.freeze'](bin_env=name, user=user, use_vt=use_vt))
                    File "c:\users\builduser\salt\salt\modules\pip.py", line 736, in freeze
                      result = __salt__['cmd.run_all'](' '.join(cmd), **cmd_kwargs)
                    File "c:\users\builduser\salt\salt\modules\cmdmod.py", line 996, in run_all
                      use_vt=use_vt)
                    File "c:\users\builduser\salt\salt\modules\cmdmod.py", line 370, in _run
                      .format(cmd, kwargs, exc)
                  CommandExecutionError: Unable to run command ['C:Usersbuilduser/buildbot-venvScriptspip.exe', 'freeze'] with the context {'with_communicate': True, 'shell': False, 'env': {'TMP': 'C:\\Users\\BUILDU~1\\AppData\\Local\\Temp', 'COMPUTERNAME': 'LOCALHOST', 'CONEMUANSI': 'ON', 'USERDOMAIN': 'localhost', 'CONEMUBACKHWND': '0x000101BA', 'PSMODULEPATH': 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\', 'CHOCOLATEYINSTALL': 'C:\\ProgramData\\chocolatey', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 62 Stepping 4, GenuineIntel', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR_REVISION': '3e04', 'CONEMUPID': '3712', 'PATH': 'C:\\Program Files\\ConEmu\\ConEmu;C:\\Program Files\\ConEmu;C:\\Python27\\;C:\\Python27\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Mercurial;;C:\\Python27\\Scripts\\;C:\\Program Files\\Mercurial\\;C:\\git\\bin\\;C:\\ProgramData\\chocolatey\\bin;C:\\git;C:\\tools\\cygwin', 'CONEMUWORKDRIVE': 'C:', 'CONEMUHWND': '0x0008003E', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'VIRTUAL_ENV': 'C:\\Users\\builduser/buildbot-venv', 'TEMP': 'C:\\Users\\BUILDU~1\\AppData\\Local\\Temp', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'CONEMUDIR': 'C:\\Program Files\\ConEmu', 'CONEMUDRIVE': 'C:', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'LOCALAPPDATA': 'C:\\Users\\builduser\\AppData\\Local', 'HOMEPATH': '\\Users\\builduser', 'USERDOMAIN_ROAMINGPROFILE': 'localhost', 'CONEMUSERVERPID': '3684', 'CONEMUHOOKS': 'Enabled', 'USERNAME': 'builduser', 'CONEMUBUILD': '140923', 'LOGONSERVER': '\\\\LOCALHOST', 'SYSTEMROOT': 'C:\\Windows', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'PROGRAMDATA': 'C:\\ProgramData', 'CONEMUBASEDIR': 'C:\\Program Files\\ConEmu\\ConEmu', 'PROMPT': '$P$G', 'PUBLIC': 'C:\\Users\\Public', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'FP_NO_HOST_CHECK': 'NO', 'WINDIR': 'C:\\Windows', 'OPENSSL_CONF': 'C:\\Program Files\\OpenSSL\\bin\\openssl.cfg', 'HOMEDRIVE': 'C:', 'APPDATA': 'C:\\Users\\builduser\\AppData\\Roaming', 'SYSTEMDRIVE': 'C:', 'NUMBER_OF_PROCESSORS': '8', 'PROCESSOR_LEVEL': '6', 'PROGRAMW6432': 'C:\\Program Files', 'CONEMUDRAWHWND': '0x000101BC', 'CONEMUWORKDIR': 'C:\\Users\\builduser', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'OS': 'Windows_NT', 'CONEMUANSILOG': '', 'USERPROFILE': 'C:\\Users\\builduser'}, 'stdout': -1, 'stdin': None, 'stderr': -1, 'cwd': 'C:\\Users\\builduser'}, reason: [Error 2] The system cannot find the file specified
         Started: 16:43:23.916000
        Duration: 78.0 ms
         Changes:

    Summary
    ------------
    Succeeded: 0
    Failed:    1
    ------------

Hence the attempt at adding the encode, give me a shout if you think there's a better way I'm open to improvements :)

**Comment by jfindlay** [comment]
@UtahDave does it makes sense to make a salt utility that handles windows paths for cases like this?

**Pull request merged**
