### PR TITLE
Philips HUE lamps Proxy Minion: remove 'requests'

### PR DESCRIPTION
**Pull request by isbm**
@cro You asked. :wink: However, I couldn't manage easily use 'PUT' method with the `salt.utils.http`, unless I am seriously missing something. So I used `httplib` and `http.client`, in case Python 3. This is sufficient for this piece of hardware.

### CODE REVIEW

**Comment by jtand** [comment]
@isbm Thanks for this PR. I believe the Centos 7 failure is unrelated. 
Can you look into this [lint issue](https://jenkins.saltstack.com/job/salt-pr-lint-n/10006/violations/)?

**Comment by isbm** [comment]
@jtand Whoa! How this is happening and how to fix that? [It is resolvable](https://github.com/saltstack/salt/blob/develop/salt/ext/six.py#L265) and other code [does the same](https://github.com/saltstack/salt/blob/develop/salt/modules/hipchat.py#L29).

**Comment by s0undt3ch** [comment]
@isbm Some lines above the code you linked you'll see that we ignore those lint errors because puking does not grasp six. That's what @jtand was referring to.

**Comment by s0undt3ch** [comment]
Err... pylint! Not puking...

Dam phone....

**Comment by isbm** [comment]
@s0undt3ch Ah, I see. You got lucky "six" was not autocorrected... :laughing:

**Pull request merged**
