### PR TITLE
Azure Blob ext_pillar

### PR DESCRIPTION
**Pull request by Ajnbro**
### What does this PR do?
This PR creates an external pillar interface for Microsoft Azure Blob Storage.

### What issues does this PR fix or reference?
#54374

### Tests written?
Yes

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by Akm0d** [comment]
re-run full lint

**Comment by Akm0d** [comment]
re-run full windows2019

**Comment by Akm0d** [comment]
@Ajnbro It looks like pre-commit is failing, i'm very sure that it's becasue we recently switched to black over pylint, can you blacken your PR so we can get this merged?  Thanks :)

**Comment by Akm0d** [comment]
One last pre-commit error ```The module at salt/pillar/azureblob.py does not have a sphinx stub at doc/ref/pillar/all/salt.pillar.azureblob.rst```

**Review by dwoz — APPROVED** [review]

**Pull request merged**
