### PR TITLE
fix broken salt-cloud openstack query

### PR DESCRIPTION
**Pull request by Akm0d**
### What does this PR do?
Cherry pick https://github.com/saltstack/salt/pull/54761 into Master

### CODE REVIEW

**Comment by dwoz** [comment]
re-run full all

**Review by cmcmarrow — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Review by s0undt3ch — APPROVED** [review]

**Comment by sblaisot** [comment]
This has been merged in branch 2019.2.1 but has not landed into master.
Should you open another PR against master or will this one be merged in master automatically ?

**Comment by waynew** [comment]
Looks like it's in master now, @sblaisot 👍

**Comment by sblaisot** [comment]
Thanks

**Pull request merged**
