### PR TITLE
Merge forward from 2014.7 to 2015.2

### PR DESCRIPTION
**Pull request by basepi**
Merge forward from 2014.7 to 2015.2

### CODE REVIEW

**Comment by thatch45** [comment]
Looks like a bad merge, the lint error shows it, that var will cause the minion to stack trace in the install

**Comment by s0undt3ch** [comment]
The changes to syspaths coming from 2014.7 should be ignored.

**Comment by basepi** [comment]
I did ignore the syspaths changes. Let me inspect the other failures and see if I can figure out what went wrong. This was far from clean, but I thought I did it right.

**Comment by basepi** [comment]
I think that not all the changes to syspaths.py showed up as conflicts. So I'm just going to revert that file to the current 2015.2.

**Comment by basepi** [comment]
@s0undt3ch It would be convenient if you would double check that syspaths now looks correct.

**Comment by s0undt3ch** [comment]
As it I'd now, no changes were made to syspaths, so I assume all is right. But I'll double check I once this gets mergedbjust to make sure.

**Comment by s0undt3ch** [comment]
*as it is now

**Comment by s0undt3ch** [comment]
Dam phone....

**Comment by s0undt3ch** [comment]
I think this is safe to merge. The Ubuntu failures seem due to an apt mirror issue.

**Comment by basepi** [comment]
Thanks, @s0undt3ch!

**Pull request merged**
