### PR TITLE
Fix changing a user's password using a password hash on MariaDB

### PR DESCRIPTION
**Pull request by pprkut**
### What does this PR do?
Update the mysql_user.present state to that changing a password on MariaDB works as expected.

Reference: https://mariadb.com/kb/en/alter-user/

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by SMillerDev** [comment]
Since MariaDB 10.2 is deprecated by now, maybe just rebase this and declare it good to go?

**Comment by garethgreenaway** [comment]
@pprkut As @SMillerDev pointed out, 10.2 is deprecated so can this PR be closed?

**Comment by SMillerDev** [comment]
It shouldn't be closed since it's still broken since this PR was made. The only thing is that the backwards compatibility is no longer needed.

**Comment by pprkut** [comment]
MariaDB 10.4 introduced authentication plugins and thus also `IDENTIFIED VIA`. As such, 10.2 being EOL doesn't have any impact on this particular change as supporting that in 10.3 would need to same adjustment.

That said, as mentioned before, my original change (for fixing changing a user's password) is already available in master, so the only thing this pull request would add, is supporting newer syntax on older releases. With the added complexity of authentication plugins missing, this doesn't seem to add too much and I also don't have the time to look at that any time soon. So as far as I'm concerned, I'm fine with this PR being closed.

**Pull request closed without merging**
