### PR TITLE
Checking for jid before returning data

### PR DESCRIPTION
**Pull request by brejoc**
### What does this PR do?

Seems raw can have returns for the same minion, but an other job. In order to not return resutls from the wrong job, we need to check for the jid.

### What issues does this PR fix or reference?

https://github.com/saltstack/salt/issues/50927

### Previous Behavior

Wrong job results might be returned. Please take a look at https://github.com/saltstack/salt/issues/50927

### New Behavior

Only the correct jobs results should be returned.

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by Ch3LL — CHANGES_REQUESTED** [review]
Can you write a test for this change?

**Comment by brejoc** [comment]
@Ch3LL Sorry for dragging my feet here for so long, but finally I've just added two test cases. Could you please check your the test runs? Hudson seems to have problems fetching the changes.

**Comment by Ch3LL** [comment]
I restarted the tests. I went ahead and tested this PR against my test case i pasted in the issue and unfortunately im still seeing the issue:

```
(salt-py2) ➜  ~ for i in {1..100}; do sudo python2 ~/programa.py; done
[sudo] password for ch3ll: 
{u'newrecipe': {u'ret': u'testa'}}
{u'newrecipe': {u'ret': u'testa'}}
{u'newrecipe': {u'ret': u'testa'}}
{u'newrecipe': {u'ret': u'testa'}}
{u'newrecipe': {u'ret': u'testb'}}
{u'newrecipe': {u'ret': u'testa'}}
```

are you seeing it fixed for you? I tried multiple times to make sure.

**Comment by brejoc** [comment]
@Ch3LL I've been re-running the tests several times and for me the issue is gone. As soon as I remove the patch, I see it again. Are you running both scripts on the master?

**Comment by brejoc** [comment]
@Ch3LL I'm closing this PR because I've just opened the same PR against the master branch: https://github.com/saltstack/salt/pull/55216

**Pull request closed without merging**
