### PR TITLE
Utilize prepared grains var in master-side ipcidr matching

### LINKED ISSUE #29188: Unable to target minions via ipcidr in 2015.8
Targeting minions via cidr/ip doesn't work. (ok in 2015.5.3).

    Salt Version:
               Salt: 2015.8.1
     
    Dependency Versions:
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
               Mako: Not Installed
             PyYAML: 3.10
              PyZMQ: 14.7.0
             Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist: centos 7.0.1406 Core
            machine: x86_64
            release: 3.10.0-123.9.3.el7.x86_64
             system: CentOS Linux 7.0.1406 Core

--
    [root@saltmaster]# salt 'test01*' test.ping
    test01:
       True
    [root@saltmaster]# salt 'test01*' grains.item ipv4
    test01:
      ----------
      ipv4:
          - 10.3.139.1
          - 127.0.0.1
    [root@saltmaster]# salt -S '10.3.139.1' test.ping
    No minions matched the target. No command was sent, no jid was assigned.
    ERROR: No return received
    [root@saltmaster]# salt -C 'S@10.3.139.1' test.ping
    No minions matched the target. No command was sent, no jid was assigned.
    ERROR: No return received

### PR DESCRIPTION
**Pull request by The-Loeki**
At least partially fixes #29188 (see discussion there), #30169, #30962, #29733, #29188 et al. (tnx @fantasy86 for analysis)

### CODE REVIEW

**Comment by cachedout** [comment]
Looks good to me. Thanks, @The-Loeki

**Comment by roshan3133** [comment]
i have upgrade salt to salt-master 2015.8.7 (Beryllium) but still   salt -S <ipaddress> test.ping command output getting list of minions which did not not return. #29733 issue not resloved which i mention

**Comment by The-Loeki** [comment]
@roshan3133 that's because the commit (apparently) didn't make it into 2015.8.7

**Comment by rallytime** [comment]
@The-Loeki and @roshan3133 Correct - this fix is available in the HEAD of the 2015.8 branch and will be available in packages when we tag/test/release 2015.8.8.

**Comment by roshan3133** [comment]
can any one help me how & from where do i start to solve and commit the issues, i am quite good in python development.

**Comment by The-Loeki** [comment]
@roshan3133 as both I and @rallytime mentioned, the issue is already solved, but it was solved too late to be included in 2015.8.7. It will therefore be in 2015.8.8. 
If you can't wait for that you can:
* backport the commit (you can see https://github.com/saltstack/salt/pull/31201/files for what changed)
* or run the master(s) temporarily from the git branch rather than the packages

Of course you're welcome to actively commit (other) fixes to Saltstack. To get started: 
https://docs.saltstack.com/en/latest/topics/development/index.html
And more specifically:
https://docs.saltstack.com/en/latest/topics/development/contributing.html
https://docs.saltstack.com/en/latest/topics/development/conventions/style.html

**Pull request merged**
