### PR TITLE
Fix _compat for py3

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?
Fixes some code that is incompatible with PY3.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/51831

### Tests written?
No

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by dwoz** [comment]
@twangboy Is it possible to write a regression test for this?

**Comment by twangboy** [comment]
@dwoz Probably. I'll give it a shot.

**Comment by twangboy** [comment]
Closed in favor of https://github.com/saltstack/salt/pull/51931

**Comment by afischer-opentext-com** [comment]
@twangboy , sorry, but are we sure that #51931 fixes this issue? In https://github.com/saltstack/salt/pull/51931/files#diff-246af447f37621b35b4927bacd8a23c8L194 I still see invalid Python 3 (line 193) as Python 3 bytearray() method requires at 2 arguments, not only one. Just asking...

**Comment by twangboy** [comment]
@afischer-opentext-com Do you have some sample data that failes on Py3 and not Py2. I'm going to have to write some tests for this.

**Comment by afischer-opentext-com** [comment]
@twangboy , in our case it's a simple `b's3.amazonaws.com'` which causes the method to fail.

**Comment by twangboy** [comment]
Sweet! Thanks. I'll get started on a test for that case.

**Review by dwoz — APPROVED** [review]

**Pull request merged**
