### PR TITLE
Improve virt state module

### LINKED ISSUE #27489: virt module inconsistencies/ideas for improvement
After working with the new `virt` state module in `develop` (introduced in #25453), I'd like to provide the following feedback:

- certain functions (`rebooted`, `reverted`) seem to disagree with the rest of the built-in state modules (I'm unable to find a state module that restarts or reverts an entity _each time_ a highstate is applied). I would propose removing these and reserving such functions for the execution module.
- the `running` function should be extended to enable the definition and starting of a domain that does not exist, given parameters (most of which can just be popped from `kwargs` in the state)

### PR DESCRIPTION
**Pull request by systembell**
Closes #27489. 

This changes the behavior of `virt.running` so that it:
- starts an existing domain that is _not_ running, or
- defines a new domain and starts it, using values plucked from args and passing them to the `virt` execution module

### CODE REVIEW

**Comment by pravka** [comment]
Fixing lint issues now.

**Comment by cachedout** [comment]
@pravka Looks like one more lint error. Just kill that blank line at the end of the file and we'll get this merged. Thanks!

**Comment by pravka** [comment]
@cachedout done. Thanks!

**Comment by pravka** [comment]
Huh, I tore out the last blank line, and it's still failing @cachedout. Any suggestions?

**Comment by pravka** [comment]
Can we merge this today?

**Comment by cachedout** [comment]
@pravka It looks like you've removed/changed some function names in here? This is going to break existing states that use this module. Do these names need to be changed? If so, can we include a deprecation warning before just removing them completely?

**Comment by pravka** [comment]
Done. Thanks for following up on that @cachedout.

**Comment by cachedout** [comment]
Much better! I'm just going to let the tests finish running and I'll get this in. I appreciate your patience.

**Comment by pravka** [comment]
Good to go now

**Comment by cachedout** [comment]
Merged! Thanks.

**Pull request merged**
