### PR TITLE
Cherry pick non-proxy related changes from #54878

### PR DESCRIPTION
**Pull request by Akm0d**
### What does this PR do?
Fix linter errors

### CODE REVIEW

**Comment by Akm0d** [comment]
re-run full debian8

**Comment by Akm0d** [comment]
re-run full opensuse15

**Comment by Akm0d** [comment]
re-run full windows2016

**Comment by Akm0d** [comment]
re-run full windows2019

**Comment by Akm0d** [comment]
Separated from https://github.com/saltstack/salt/pull/54878

**Review by dwoz — APPROVED** [review]

**Pull request merged**
