### PR TITLE
Kill bare excepts with fire

### PR DESCRIPTION
**Pull request by terminalmage**
These prevent the signal handlers from shutting down a process via a raising a SystemExit. They are ticking time bombs of race conditions that leave processes running when daemons are shut down or restarted.

Friends don't let friends use bare excepts.

### CODE REVIEW

**Review by cachedout — APPROVED** [review]
Nice.

**Review by rallytime — APPROVED** [review]
Yay! Nice to have this cleaned up.

**Review by skizunov — APPROVED** [review]

**Review by DmitryKuzmenko — APPROVED** [review]
Awesome! Now I'm happy:
```
$ grep -Rn "^ *except:" salt/ | wc -l
0
```

**Review by isbm — APPROVED** [review]

**Comment by damon-atkins** [comment]
Should this be added to the pylint tests?

**Pull request merged**
