### PR TITLE
Add a bunch of flags to lvcreate

### PR DESCRIPTION
**Pull request by dseomn**
### What does this PR do?

Adds flags to lvcreate.

### What issues does this PR fix or reference?
Fixes: none

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

Are any of these relevant for this PR? I don't think the existing flags are documented or tested individually.

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by garethgreenaway** [comment]
@dseomn Thanks for the PR. Can you please add a changelog file with a short description of the changes.  Thanks!

**Comment by dseomn** [comment]
> @dseomn Thanks for the PR. Can you please add a changelog file with a short description of the changes. Thanks!

Sure, done.

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Comment by dseomn** [comment]
> Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

Is that a comment for reviewers/maintainers or for me? I responded to the only comment I got, and I don't want to put more effort into this unless it will actually get merged.

**Pull request closed without merging**
