### PR TITLE
Fix error retry handling for Route53

### PR DESCRIPTION
**Pull request by kaidokert**
### What does this PR do?

Fixes error handling, as not all errors should be retried. Currently, if a wrong AWS key is used with no access, the error is not reported at all.

### Previous Behavior
Configure `route53.key` in pillar to an invalid value, the access errors are not reported

### New Behavior
With invalid key provided, the exception is correctly raised and reported on state run

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Review by dwoz — COMMENTED** [review]
@kaidokert It looks there are some failing tests related to this change. Can you take a look?

**Comment by kaidokert** [comment]
Checked, i'm completely lost on how any of those changes could result in these errors. It seems completely unrelated.

**Comment by kaidokert** [comment]
Ok jenkins finally showed me the actual issue, linting. Cleaned up

**Review by Akm0d — APPROVED** [review]

**Comment by terminalmage** [comment]
Ported to master in https://github.com/saltstack/salt/pull/56696

**Pull request merged**
