### PR TITLE
Don't remount loop back filesystems upon every state run

### PR DESCRIPTION
**Pull request by jrgp**
Per #20855, upon each run don't remount filesystems that are loop back devices. This is a problem I have where squashfs mounts remount every time even though their options have not changed.

### CODE REVIEW

**Comment by jfindlay** [comment]
Wouldn't this cause loop mounted filesystems to not be remounted even if there were a change?

**Comment by RobertFach** [comment]
@jfindlay Well, the only change that would cause the loop device to not be remounted is if you remove the loop option. So you're right, it's not correct from a semantic point of view. However, I think it doesn't matter for that case, because a looback device without loop option is not a loopback device anymore. Hence, one wouldn't hopefully do that :) I think to do that correctly, one would need to implement some special handling for loopback devices and refine the change detection code...

**Comment by jfindlay** [comment]
I've only ever loop mounted filesystems contained in a file, and am unaware (after impatiently scanning the mount manpage) of any other use case.  If you're mounting a file, I guess it's unlikely you're going to change the filesystem of that file.  Sorry for being obtuse, it's been a long day.

**Comment by jfindlay** [comment]
@RobertFach, if you're interested in pursuing this idea further, please feel welcome to do so.  I think the change is sufficient for almost all use cases.

**Pull request merged**
