### PR TITLE
Allow pillar relative includes

### PR DESCRIPTION
**Pull request by waynew**
### What does this PR do?

Implements longstanding request #8875 - allows for pillar relative includes

### What issues does this PR fix or reference?

#8875 - there are probably others

### Previous Behavior

A leading dot in a pillar include was a nop. If you had a pillar like:

**foo/bar/baz.sls**
```
include:
  - .bang
```

That would not refer to `foo/bar/bang.sls`, but `bang.sls` at the pillar root.

### New Behavior

Now leading dots in includes refer to relative imports :tada:

### Tests written?

Yes

### Commits signed with GPG?

Yes

---

I'm operating under the assumption that https://github.com/saltstack/salt/pull/52008 will be merged.. forward?

### CODE REVIEW

**Review by dmurphy18 — APPROVED** [review]

**Comment by mchugh19** [comment]
Can/should this be added to release notes?

**Comment by max-arnold** [comment]
@waynew It would be nice if this feature worked exactly as in states, i.e. multiple dots should also work: https://docs.saltstack.com/en/latest/ref/states/include.html#relative-include

```
include:
  - ..http
  - ...base
```

Also, no docs at all 😞

**Comment by waynew** [comment]
@max-arnold Do pillar relative includes work that way?

**Comment by max-arnold** [comment]
@waynew 
> Do pillar relative includes work that way?

No, **pillar** includes do not work that way, but it makes sense to implement because **state** includes support this, and feature symmetry is generally a good thing. See the states doc I mentioned earlier: https://docs.saltstack.com/en/latest/ref/states/include.html#relative-include

**Comment by waynew** [comment]
Wow, I'm not sure *at all* what I meant there 🙃 

I think it's probably worth creating an issue/feature request. I don't know if it's significant enough to create a SEP, but I agree with the feature symmetry point.

**Comment by waynew** [comment]
When porting this to master it should be noted that it closes #56186

**Pull request merged**
