### PR TITLE
Add saltcloud module for Dimension Data Cloud

### PR DESCRIPTION
**Pull request by tonybaloney**
- [x] - Complete driver implementation for nodes
- [x] - Complete driver implementation for lb
- [x] - Update documentation

Imported from https://github.com/dddrew/salt-dimensiondata (credits @…dddrew) worked on PEP8 compliance.

### CODE REVIEW

**Comment by techhat** [comment]
Hey @tonybaloney, other than the lint issues, this is looking really good!

**Comment by tonybaloney** [comment]
Should saltpylint at least be in one of the requirements files?

**Comment by techhat** [comment]
It's not required to use or build; it's  just helpful to have installed before submitting PRs. Personally, I just submit PRs and wait for Jenkins to do the lint tests for me.

**Comment by tonybaloney** [comment]
@techhat all done. is someone available to check please and provide feedback? have done some integration tests on a deployment of this branch in ubuntu 14.

**Comment by rallytime** [comment]
This looks great! Thanks @tonybaloney!

**Comment by tonybaloney** [comment]
woo! thanks @rallytime

**Pull request merged**
