### PR TITLE
Loader nomerge: Don't allow modules to "merge"

### PR DESCRIPTION
**Pull request by jacksontj**
In the current loader (and previous one) you are allowed to create a module with a **virtual_name** which can add its functions to the namespace (within **salt**) of another module. This is very confusing, and inconsistent (not to mention hard to debug). From talking it out in #20481 we determined there aren't use-cases that _require_ this functionality, so we are going to remove it and move the few cases over to decorators, **load**, or something similarly less-magical.

### CODE REVIEW

**Comment by steverweber** [comment]
Thanks for merging the submodule support.

removing the "merge" option looks like fun.

**Comment by jfindlay** [comment]
The intent of your patch seems to make [this test](https://jenkins.saltstack.com/job/salt-pr-rs-cent7-n/1352/testReport/junit/integration.cli.custom_module/SSHCustomModuleTest/test_ssh_custom_module/) invalid on purpose, right?

**Comment by jacksontj** [comment]
Yes, although the last time i submitted this that one test didn't fail-- but the equivalent non-ssh one did ;)

**Comment by thatch45** [comment]
I really dislike this PR, we have a lot of deployments that use this feature. I don't think that being confused is a valid reason here.

**Comment by thatch45** [comment]
@jacksontj I will only let this in if it is config gated, this is going to break a lot of people's environments and should not be on by default

**Comment by jacksontj** [comment]
@thatch45 We talked about it a *lot* in another PR. Its not so much a case of "im confused" its more of a case of "we can't know what its doing". From our other conversation it sounds like we agreed this would be a good feature to kill off-- which will require some time (since people could be using the feature).

From chatting in the other PR it seems that there isn't really a valid use-case that requires this complexity that couldn't be solved in a more simple way. Do you have a use-case that requires this? If not I think its a good idea to start the process of removing this feature.

**Comment by thatch45** [comment]
Looks like we have a number of test failures here

**Comment by jacksontj** [comment]
Yea, from your last comment it sounded like this was still under dispute--
although from this comment it sounds like we are okay with this.

I need to add some deprecation warnings etc. and find the few places that
still use this functionality. I'm going to get back to this after I finish
our internal 2015.2 rollout

**Comment by thatch45** [comment]
Sounds good, with the deprecation warnings I am ok putting this in develop

**Comment by kiorky** [comment]
This will break saltstack/salt#21314 in its current form.

**Comment by jacksontj** [comment]
This will also break the deb apache modules. We won't be merging this for a
while. Need to put a deprecation warning and switch people over to
decorators

**Comment by jfindlay** [comment]
@thatch45, @jacksontj, what think ye all about this pull request?

**Comment by thatch45** [comment]
I am going to close this out for a while, once activity starts again we can re-open

**Pull request closed without merging**
