### PR TITLE
make salt-api arg/kwarg handling the same as cli for all clients

### LINKED ISSUE #99: pepper vs. salt has different `test.arg_repr` output types
When using `pepper` versus the standard `salt` command you get different results in terms of returned data types. 

This seems related to #57 but different in the details.

```bash
(envsalt)  >>> pepper -a pam --username=saltvirt --password=saltvirt 'sip-cannon' test.arg_repr trunktest2 2 '2048' image=/var/lib/libvit/images/centos66.qcow2 enable_vnc=True config='{"master": "goodboy.qa.sangoma.local"}' start=False enable_qcow=True                     
{
    "return": [
        {
            "sip-cannon": {
                "args": "('trunktest2', '2', '2048')",
                "kwargs": "{'__pub_user': 'saltvirt', '__pub_arg': ['trunktest2', '2', '2048', 'image=/var/lib/libvirt/images/centos66.qcow2', 'enable_vnc=True', 'config={\"master\": \"goodboy.qa.sangoma.local\"}', 'start=False', 'enable_qcow=True'], 'start': False, 'config
': {'master': 'goodboy.qa.sangoma.local'}, 'image': '/var/lib/libvirt/images/centos66.qcow2', '__pub_fun': 'test.arg_repr', 'enable_qcow$
: True, '__pub_jid': '20170301004836803665', '__pub_tgt': 'sip-cannon', '__pub_tgt_type': 'glob', 'enable_vnc': True, '__pub_ret': ''}"
            }
        }
    ]
}
 
(envsalt)  >>> sudo salt 'sip-cannon' test.arg_repr trunktest2 2 2048 image=/var/lib/libvirt/images/centos66.qcow2 enable_vnc=True con$
ig='{"master": "goodboy.qa.sangoma.local"}' start=False enable_qcow=True
sip-cannon:
    ----------
    args:
        ('trunktest2', 2, 2048)
    kwargs:
        {'__pub_user': 'sudo_tyler', '__pub_arg': ['trunktest2', 2, 2048, {'enable_qcow': True, 'image': '/var/lib/libvirt/images/centos66.qcow2', 'start': False, 'config': {'master': 'goodboy.qa.sangoma.local'}, 'enable_vnc': True}], 'enable_qcow': True, 'config': {'master': 'goodboy.qa.sangoma.local'}, 'image': '/var/lib/libvirt/images/centos66.qcow2', '__pub_fun': 'test.arg_repr', 'start': False, '__pub_id': '20170301004859437566', '__pub_tgt': 'sip-cannon', '__pub_tgt_type': 'glob', 'enable_vnc': True, '__pub_ret': ''}
```

Notably the `arg` array contains different types (in this case most obviously `int` versus `str`),
- `pepper`:
```python
('trunktest2', '2', '2048')
```

- `salt`: 
```python
('trunktest2', 2, 2048)
```

In my case this is turn causes a parsing problem downstream in the `salt.modules.virt.init()` function:
```
00:34:44 [ 2382] [DEBUG   ] Generating VM XML                                                                                            
libvirt: Domain Config error : XML error: Invalid value '20482048204820482048204820482048204820482048204820482048204820482048204820482048
20482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482
04820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820
48204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204
82048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048
20482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482
04820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820
482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204820482048204                                
```

### PR DESCRIPTION
**Pull request by mattp-**
### What does this PR do?
both cherrypy and saltnado now pass all args through parse_input to
allow for behavior equivalent to salt cli yaml based arg parsing. This
will allow for pepper to behave more like salt cli, or direct api users.

also included is a minor feature to saltnado/cherrypy, a new X-Salt-Version
header for usage in pepper to determine if this feature among others
is available to use.

### What issues does this PR fix or reference?
will fix https://github.com/saltstack/pepper/issues/99 when equivalent pepper changes are made.

### Previous Behavior
yaml based foo=bar args are not passed through parse_input

### New Behavior
args are passed through parse_input

### Tests written?
yes

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by mattp-** [comment]
@rallytime I notice you disabled one of the other saltnado tests for being too flaky, the one I've added is essentially the same. It's not clear to me what race condition was the problem, but we can turn this test off for now as well if you like.

**Review by gtmanfred — CHANGES_REQUESTED** [review]
looks like we just need some tests expected results updated for this change, and also pylint has one error, otherwise this looks perfect.

Thanks!
Daniel

**Comment by mchugh19** [comment]
I'd suggest throwing something into the release notes as well. Modifying the args/kwargs handling of salt-api and the version header is a pretty large (and positive) change.

**Comment by mattp-** [comment]
@gtmanfred ok, should have the tests/lint fixed up. will let jenkins chew on it for a bit
@mchugh19 seems reasonable, but i think generally the release note management is done by the release team when they cut releases, not in this PR :)

**Comment by gtmanfred** [comment]
Nope, we do it in the PRs when we add features, it would be great to include this in the Neon release notes.

**Comment by mattp-** [comment]
ah gotcha, added salt-api release notes to neon.rst

**Review by gtmanfred — APPROVED** [review]

**Comment by rallytime** [comment]
@whiteinge Is this something you'd like to review?

**Comment by whiteinge** [comment]
Thanks for the ping, @rallytime. This functionality should already be baked into Salt and I did not include this functionality in salt-api on purpose for the reasons described below. That said, I'll happily defer to the wishes of the core team and any contributors that want to put in the actual work. Please consider or disregard as you see fit.

Parsing the `arg=val` strings into kwargs is a central workflow in Salt and thus should live in a central place and work consistently regardless if you are calling Salt from the CLI, from a REST API, from a Python wrapper, HTML form fields, a Slack bot, and many, many other examples we've seen. The best central place to do that is Salt's Python API (`LocalClient`, `RunnerClient`, `WheelClient`, etc). That is what the above-linked Pepper issue is discussing. All those client interfaces **should** run the `arg` (singular) array values through the utils function we have that splits `arg=val` strings apart and parses the right-hand side of that as YAML. I know for certain this has worked correctly in the past for LocalClient and RunnerClient (I don't recall offhand where WheelClient stood), because I have used it many, many times and even wrote tests for some of it. However this functionality has also regressed more than once (again the Pepper discussion) and I can't speak to the current state of things.

https://github.com/saltstack/salt/blob/23e0d40d833c965fe573bee88c11be677f5b8e5c/tests/integration/client/test_runner.py#L108-L135

IMO the best fix is to figure out how to prevent future regressions, to keep this functionality in the `*client` interfaces and to _not_ to bake this into salt-api.

A concrete example of why this is best done in Salt instead of salt-api is [this discussion about the Slack engine](https://github.com/saltstack/salt/issues/39783#issuecomment-284116852). A Slack bot would be accepting `arg=val` strings because people are typing them into a chat interface -- just like the CLI, just like webhooks, just like Pepper, just like HTML forms, etc. It would be ideal for any module type that goes through the Python API (not just the REST API which of course uses the Python API, just like all the other module types) to not have to reinvent this over and over.

It is easier to put this into salt-api, for sure, and fixing this (and avoiding future regressions) in core may be quite difficult indeed (https://github.com/saltstack/salt/pull/39472). But I do feel that is the better solution.

My $0.02. I sincerely wish whoever takes either path good luck and godspeed. 😄

**Comment by mattp-** [comment]
@whiteinge thanks for chiming in, appreciate your input. I actually _did_ start off with a separate PR to put parse_input in localclient directly (https://github.com/saltstack/salt/pull/49886), however after some chat with @cachedout / @terminalmage we were hesitant to put a change in localclient directly that manhandles args since its such a sensitive codepath (some tests surfaced expected behavior in the contrary). however if 'arg={yaml: foo}'  is a documented behavior of localclient at the *api layer*, I think the original change makes sense, and we can change those tests.
That said, I don't call the shots on what goes into salt either :) I lean towards your proposal since runnerclient already works that way. Anyone else have any thoughts/decisions?

**Comment by rallytime** [comment]
I agree with @whiteinge on this one. I wasn't aware of that history. Thanks for filling that in!

I am definitely curious what @cachedout and @terminalmage may have to say, given @whiteinge's explanation above.

**Review by terminalmage — APPROVED** [review]

**Comment by terminalmage** [comment]
I need to re-evaluate this, I did not see all the conversation here.

**Comment by mattp-** [comment]
per slack convo with @terminalmage im going to close this in favor of #49886 once that is fixed up and ready for merge.

**Comment by mchugh19** [comment]
WIth #49886 being merged, the release notes and X-Salt-Version header from this PR would still be very helpful and resolve part of #42491

**Pull request closed without merging**
