### PR TITLE
Making vmware cloud driver Python3 compatible and other additions

### PR DESCRIPTION
**Pull request by nmadhok**
Made vmware salt-cloud driver Python3 compatible.

Added ability to modify/create SCSI adapters in `create()` in vmware salt-cloud driver and also adding docs for it
Refs feature request #22364 filed by @angystardust

Combining duplicate code for network adapter mapping in a single helper function called `_set_network_adapter_mapping_helper()`

@techhat

### CODE REVIEW

**Comment by angystardust** [comment]
Awsome, @nmadhok! 
Just one question: taking a look at the code, it doesn't seem possible to attach a disk to a specific scsi controller. Maybe this will implemented in another PR?

**Comment by nmadhok** [comment]
@angystardust Disks cannot be attached yet but I'll be working on it once I find some free time. Right now it will only create the SCSI controller if it's not present otherwise modify the existing controller.

**Comment by angystardust** [comment]
No prob...by the way, I think this driver it's coming up nicely (big :+1:  for the vmware-tools upgrade feature). I'm gonna testing it next week ;)

**Comment by nmadhok** [comment]
@angystardust Thanks! @rmgoodberlet worked on the ``upgrade_tools`` action.

**Pull request merged**
