### PR TITLE
Also search groupattribute when using ipa client (extending #45859)

### PR DESCRIPTION
**Pull request by Tanoti**
### What does this PR do?

Adds the attribute 'groupattribute' to the search path when using freeipa client to support configurations where authentication is by group.

NOTE: This is a re-application of #45859 

### What issues does this PR fix or reference?

N/A

### Previous Behavior

Only the 'accountattributename' attribute was searched.

### New Behavior

First 'accountattributename' is searched then 'groupattribute' to provide extended search functionality similar to that in the "else" section of the code block

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Review by gtmanfred — APPROVED** [review]

**Comment by rallytime** [comment]
@Tanoti Can you fix the lint error please?

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/21512/violations/file/salt/auth/ldap.py/

**Review by cro — APPROVED** [review]

**Comment by cachedout** [comment]
@Tanoti Can you please add some documentation regarding this change? We'll want to put it in the release notes for Fluorine as a minimum. Thanks!

**Comment by Tanoti** [comment]
@cachedout Done. I hope they are sufficient.

**Comment by rallytime** [comment]
@Tanoti Can you rebased this?

**Comment by gtmanfred** [comment]
@Tanoti this isn't a rebase, this was just a pull/merge.

We need your commits rebased on top of all of the other commits that have now been added to this pr.

Thanks,
Daniel

**Comment by Tanoti** [comment]
@gtmanfred I've tried again. If this does not work then I am going to need someone to walk me through the steps as I've followed the guidelines in https://docs.saltstack.com/en/latest/topics/development/contributing.html and, as far as I know, I'm doing it all correctly.

**Comment by Tanoti** [comment]
@gtmanfred Many thanks, in some ways git is still very much a black art to me!

**Comment by gtmanfred** [comment]
:+1: happy to help.

Thanks for the contribution!

**Pull request merged**
