### PR TITLE
Avoid KeyError: 'multiprocessing' in the master logs

### PR DESCRIPTION
**Pull request by mirceaulinic**
Fix for #39059

### CODE REVIEW

**Comment by cachedout** [comment]
I'm still not following why this key isn't present in the options dictionary in this case. Why isn't this being set in the default opts?

**Comment by mirceaulinic** [comment]
Hey @cachedout - yes I was wondering the same.
I supposed this is due to the `multiprocessing` set as `False` in the proxy config file (SSH-based proxy), without digging into the problem.
Perhaps @cro knows more about that.

**Comment by cachedout** [comment]
@mirceaulinic Let's see what @cro has to say. I am leery of these types of fixes because they often mask a bug higher up the call stack.

**Comment by mirceaulinic** [comment]
Yes, I agree with you! I have expected this... and somehow I was actually waiting for this discussion :)

Unfortunately over the next few days I won't have the time to go a bit deeper into this problem. But it's not a blocker so we can revisit anytime.

**Comment by cachedout** [comment]
@mirceaulinic No problem at all. That's why we do code reviews. :] We'll leave this one in the queue for now.

**Comment by cro** [comment]
So @mirceaulinic, since your stacktraces are appearing in the master log, do you know what you are running on the master that is calling this function in salt.utils.minion?  `multiprocessing` is not a valid opt for the master, so this would indeed stacktrace when run on the master.

Your fix looks innocent enough, I'm just struggling a little to know how the master got here.

**Comment by mirceaulinic** [comment]
Hi @cro 

> since your stacktraces are appearing in the master log, do you know what you are running on the master that is calling this function in salt.utils.minion?

I have a scheduler runner (only the name is fake below - sorry, it's because of the company policy...):

```yaml
redis:
  some_scheduled_runner:
    function: my_runner.my_fun
    minutes: 5
```

Inside `my_fun` it's calling a function from a different runner, say `my_other_runner.my_other_fun`.
In `my_other_fun` I have something like:


```python
client = salt.client.get_local_client(__opts__['conf_file'])
ret = client.cmd(tgt, fun, some_arg=some_value)
```

Wondering if the local_client is the cause of this.

Anyway, please allow me some time to dig a little bit more into this and see what the root cause.

**Comment by cro** [comment]
local_client might be the cause.  In any case, I'm OK with the fix, I think it's a better fix than adding `multiprocessing` as a valid master config option.  I'll tag this to circle back in a couple of days and ping you.

**Pull request merged**
