### PR TITLE
Pylint fix for develop

### PR DESCRIPTION
**Pull request by rallytime**
Make sure this runs and passes before merging. Something might not be quite right here.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Integration should be imported after the call to `ensure_in_syspath()`...

**Comment by jfindlay** [comment]
Still errors on `integration`.

**Comment by rallytime** [comment]
@s0undt3ch I'm really not sure why that is failing. Seems like a strange failure and we're not ignoring that import in other test files.

**Comment by s0undt3ch** [comment]
@rallytime not ignoring, but importing salt libs, even libs under `tests/` needs to be done after that ensure call....

Oh it failed again... dunno...

**Comment by jfindlay** [comment]
@s0undt3ch is out of ideas. this is grave.

**Comment by s0undt3ch** [comment]
Well I know what the problem is, we're munging with the python path too much :)

**Comment by s0undt3ch** [comment]
And absolute imports tend to trigger this more often...

**Pull request merged**
