### PR TITLE
Ability to specify a custom port for the connection to Proxmox

### PR DESCRIPTION
**Pull request by mahalel**
It will default to 8006 if not specified

### What does this PR do?
Allows to specify custom port for the connection to Proxmox, if for example you are using a reverse proxy listening on :443

### What issues does this PR fix or reference?
N/A

### Previous Behavior
salt-cloud would always attempt a connection on port 8006 to proxmox

### New Behavior
salt-cloud will attempt a connection on the custom port specified in the configuration file.

### Tests written?

No

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by gtmanfred — APPROVED** [review]

**Review by cachedout — COMMENTED** [review]
I believe this change should be included in the Neon release notes. Could you add an entry describing the change before we merge this, please?

**Comment by cachedout** [comment]
This also has a lint error that needs to be addressed before we can merge this: https://jenkinsci.saltstack.com/job/pr-lint/job/PR-50620/1/warnings52Result/new/

**Comment by mahalel** [comment]
Sorry bit new to this, so I'm hoping the last merge request passes the lint test :)

As for an entry describing the change:

"Salt-Cloud/Proxmox module - Added ability to specify custom port for connection to Proxmox."

Hope this is ok, appreciate the patience.

**Comment by cachedout** [comment]
@mahalel Looks good. Merged! Thanks very much.

**Comment by terminalmage** [comment]
These commits are already in master, so this can be removed from the list of PRs to port.

**Pull request merged**
