### PR TITLE
lxc: dont use cache in exists, if not existant

### LINKED ISSUE #22644: lxc.exists use too much cache
lxc.ls should not cache in certain cases

Im pushing a fix

cc @terminalmage

### PR DESCRIPTION
**Pull request by kiorky**
This fixes #22644

### CODE REVIEW

**Comment by kiorky** [comment]
cc @terminalmage

**Comment by terminalmage** [comment]
The ``create()`` function clears the LXC context variables, so this shouldn't be necessary. What particular use case does this address?

**Comment by kiorky** [comment]
it does not cover all cases, download a prebacked lxc container not with of lxc module and you are dead.

**Comment by terminalmage** [comment]
I spoke with @kiorky in IRC and he pointed out an edge case in which, if the context cache had been created already, unpacking a tar'ed LXC container's rootfs and unpacking the tarball into /var/lib/lxc would then result in a container that exists, which the output of ``lxc.ls`` doesn't include.

This PR addresses this edge case sufficiently, I will merge.

**Pull request merged**
