### PR TITLE
Remove Salt Search system, this never worked

### PR DESCRIPTION
**Pull request by thatch45**
Seeing how this never worked, is basically undocumented and was never finished, we should pull it put of the code

### CODE REVIEW

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
Closes #4308

**Comment by rallytime** [comment]
@thatch45 It looks like there is some more code that needs to be removed with this change.

**Comment by thatch45** [comment]
Ok, those should help

**Comment by thatch45** [comment]
Ok, I think that has done it

**Pull request merged**
