### PR TITLE
Fixed issue #55149

### PR DESCRIPTION
**Pull request by Akm0d**
### What does this PR do?
- Removed `opts` from the call to `compound_match.match`
- Fixes issue #55149

### CODE REVIEW

**Comment by dwoz** [comment]
@Akm0d Can you create a port of this to `2019.2.3` too?

**Review by dwoz — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Review by cmcmarrow — APPROVED** [review]

**Comment by Akm0d** [comment]
re-run full tcp

**Comment by Akm0d** [comment]
re-run full debian9

**Comment by Akm0d** [comment]
re-run macosxmojave

**Comment by Akm0d** [comment]
re-run full macosxmojave

**Comment by Akm0d** [comment]
re-run full macosxmojave

**Comment by Akm0d** [comment]
re-run full tcp

**Comment by Akm0d** [comment]
re-run full tcp

**Comment by Akm0d** [comment]
re-run full amazon2

**Comment by Akm0d** [comment]
re-run full amazon2

**Pull request merged**
