### PR TITLE
git_pillar: Fix all_saltenvs on base env

### PR DESCRIPTION
**Pull request by sathieu**
### What does this PR do?

Fixes #50768.

### What issues does this PR fix or reference?

PR #50768. This fix was too lake for 2018.3.4 (see #51597).

### Previous Behavior
```
minion:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Specified SLS 'projects.gitlab' in environment 'prod' is not available on the salt master
```

### New Behavior

State applies succesfully.

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by sathieu** [comment]
@terminalmage please review and merge.

**Comment by dwoz** [comment]
@sathieu are you able to write a test for this?

**Comment by sathieu** [comment]
@dwoz:
> @sathieu are you able to write a test for this?

In progress.

**Comment by sathieu** [comment]
@dwoz I've written tests. Please merge.

**Review by twangboy — APPROVED** [review]

**Comment by sathieu** [comment]
This bugfix PR is waiting to be merged in 2018.3 (for 2018.3.5) and needs to go in 2019.2.1 too.

**Comment by sathieu** [comment]
@garethgreenaway This one is already merged in master, per #51661, please tag accordingly

**Pull request merged**
