### PR TITLE
Fix fopen resetting badly permissions...

### LINKED ISSUE #20931: critical: develop: blockreplace looses file ownership & permissions
detected in #20908 & #20914
to illustrate the bug, the current sls
```
postgresql-pg_hba-conf:
  file.managed:
    - name: /tmp/tests
    - content: foo
    - user: ubuntu
    - mode: 750
    - group: root
    - template: jinja


append-to-pg-hba--block:
  file.blockreplace:
    - name: /tmp/tests
    - marker_start: "#-- start salt managed zonestart -- PLEASE, DO NOT EDIT"
    - marker_end: "#-- end salt managed zonestart --"
    - content: ''
    - append_if_not_found: True
    - backup: '.bak'
    - show_changes: True
    - require:
        - file: postgresql-pg_hba-conf

```

produces:
```
local:
----------
          ID: postgresql-pg_hba-conf
    Function: file.managed
        Name: /tmp/tests
      Result: True
     Comment: Empty file
     Started: 18:51:03.768306
    Duration: 1.534 ms
     Changes:
              ----------
              mode:
                  0750
              new:
                  file /tmp/tests created
              user:
                  ubuntu
----------
          ID: append-to-pg-hba--block
    Function: file.blockreplace
        Name: /tmp/tests
      Result: True
     Comment: Changes were made
     Started: 18:51:03.770175
    Duration: 34.258 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -0,0 +1,3 @@
                  +#-- start salt managed zonestart -- PLEASE, DO NOT EDIT
                  +
                  +#-- end salt managed zonestart --


Summary
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2


-rwxr-x--- 1 root root 91 févr. 23 18:51 /tmp/tests
```

If the blockreplace is omitted:
```
postgresql-pg_hba-conf:
  file.managed:
    - name: /tmp/tests
    - content: foo
    - user: ubuntu
    - mode: 750
    - group: root
    - template: jinja

{#
append-to-pg-hba--block:
  file.blockreplace:
    - name: /tmp/tests
    - marker_start: "#-- start salt managed zonestart -- PLEASE, DO NOT EDIT"
    - marker_end: "#-- end salt managed zonestart --"
    - content: ''
    - append_if_not_found: True
    - backup: '.bak'
    - show_changes: True
    - require:
        - file: postgresql-pg_hba-conf
#}

```
this produces 
```
local:
----------
          ID: postgresql-pg_hba-conf
    Function: file.managed
        Name: /tmp/tests
      Result: True
     Comment:
     Started: 18:52:33.258766
    Duration: 1.081 ms
     Changes:
              ----------
              user:
                  ubuntu

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
-rwxr-x--- 1 ubuntu root 91 févr. 23 18:51 /tmp/tests
```

here the user is correctly set

### PR DESCRIPTION
**Pull request by kiorky**
This fixes #20931.
this rels  #20908 & #20914.

### CODE REVIEW

**Comment by kiorky** [comment]
cc @thatch45 @basepi @rallytime

**Comment by jfindlay** [comment]
@kiorky, this is [already fixed](https://github.com/saltstack/salt/pull/20887) in 2015.2, and a merge forward will bring it into develop.

**Comment by jfindlay** [comment]
@kiorky, would you mind submitting the `mode = kwargs.pop('mode', None)` fix to 2015.2?  Thanks.

**Comment by kiorky** [comment]
i can submit it yes, let me do the pr, but it is not a minor change, this can be dramatic in term of permissions :)

**Comment by jfindlay** [comment]
@kiorky, thanks, man!

**Comment by jfindlay** [comment]
The 'Minor Change' label mainly refers simply to the lines of code modified.

**Comment by kiorky** [comment]
Let me do the git foo, do not merge ! i ll poke you when done

**Comment by kiorky** [comment]
see & merge also https://github.com/saltstack/salt/pull/20939
(git foo is done)

**Comment by kiorky** [comment]
what do we do about this one @jfindlay  ?

**Comment by jfindlay** [comment]
@kiorky, a 2015.2 -> develop merge came in today, bringing in the fixes that went into that branch, including yours.  Github "can't automatically merge this", and I think you'll find it's already fixed. :-)

**Comment by kiorky** [comment]
yep, i was just waiting for you to close tis PR, we are on the same line

**Pull request closed without merging**
