### PR TITLE
Standardize requirements files format

### PR DESCRIPTION
**Pull request by TheBigBear**
I don't know the first thing about where those files do get used, but I didn't like the way the formatting was different amongst them. Some had whitepspaces before and after the comparison operator and some didn't. 

I am suggesting to always have the space before and after to help readability.

No offense taken if this is discarded, or maybe even wrong and breaking things?

### CODE REVIEW

**Comment by jfindlay** [comment]
@TheBigBear, it is conventional to not use the spacing, but I don't think it matters.

https://pip.readthedocs.org/en/latest/reference/pip_install.html#requirement-specifiers

**Comment by TheBigBear** [comment]
@jfindlay I just did't like the variations, some with whitepsace and some without. Maybe I should redo this and remove all the whitespace?
It's all the same to me, and if it's closer to the pep the better. No?

**Comment by jfindlay** [comment]
The pep specifically says, "whitespace between a conditional operator and the following version identifier is optional," so the only thing specifying no spaces is convention.  Since this is going to be what most people are used to, I think it would probably be better to use the no space version.

**Comment by TheBigBear** [comment]
no problem, will redo this, 
BTW what do you make of this note? Is PEP 7.0 related to setuptools v 7, or how or when does PEP 7.0 come into play?
 
In other words, is salt going to be impacted on the windos side - where we currently use 'wheels'?

```
Since version 7.0 pip supports controlling the command line options given to setup.py via requirements files. This disables the use of wheels (cached or otherwise) for that package, as setup.py does not exist for wheels.
```
Is it OK if I leave this for tonight. and then redo it tomorrow actually removing all the whitespace befoe and after the comparison operator?

**Comment by jfindlay** [comment]
@TheBigBear, I think that that is saying that if you put command line arguments into the requirements file then wheels will not work.  Since salt's requirements' files do not do this, I think it will be fine.  Also, it is perfectly fine for you to come back to this later.

**Comment by TheBigBear** [comment]
@twangboy sorry to be messing about, but it was such a small edit that I did it before retring to the horizontal position. 

So this is now __*done*__ the conventional way, but uni-form.

BTW
I keep looking out for the winrepo-ng refactoring based on the google docs doc from last Friday's google hangout call, but it's not there, yet, that I can see? I had asked Dave how things were going and he said he would do it yesterday between yourself and him. 

I guess things are very hectic with you guys around a release freeze?

**Pull request merged**
