### PR TITLE
Allow EC2 userdata to be templated

### PR DESCRIPTION
**Pull request by techhat**
### What does this PR do?

As it says.
### What issues does this PR fix or reference?
#32662
### Tests written?

No

### CODE REVIEW

**Comment by rallytime** [comment]
@techhat Looks like you have a [lint error](http://166.78.178.63:8080/job/PR/job/salt-pr-lint-n/1178/violations/file/salt/cloud/clouds/ec2.py/).

**Comment by ffjia** [comment]
Hi there,

When I'm testing this feature with `cloudinit' format userdata, there's a type error, did I do anything wrong? Please refer to the following error message, thanks.

```
[ERROR   ] Template does not exist:
#cloud-config

apt_sources:
  - source: "ppa:saltstack/salt"

hostname: {{ minion }}
fqdn: {{ minion }}
manage_etc_hosts: false

package_update: true
package_upgrade: false
package_reboot_if_required: false
packages:
  - python-software-properties
  - salt-minion

runcmd:
  - echo `curl http://169.254.169.254/latest/meta-data/local-ipv4` {{ minion }} {{ minion }} > /etc/hosts

[ERROR   ] There was a profile error: must be string or buffer, not dict
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 277, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1439, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1274, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2498, in create
    data, vm_ = request_instance(vm_, location)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 1705, in request_instance
    params[spot_prefix + 'UserData'] = base64.b64encode(userdata)
  File "/usr/lib/python2.7/base64.py", line 53, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: must be string or buffer, not dict
```

**Comment by techhat** [comment]
@ffjia, would you please open up a new issue for this?

**Comment by ffjia** [comment]
@techhat, issue created #33194.

**Pull request merged**
