### PR TITLE
A more brute force approach to try to reduce memory usage on test runs.

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
A more brute force approach to try to reduce memory usage on test runs.

We just keep a record of all the test case class attributes prior to
running the test and then just delete it afterwards.
We also issue a warning log message to tell the users how to cleanup
such references.

### CODE REVIEW

**Comment by cachedout** [comment]
Test suite wasn't so happy about this though. :-/

**Comment by s0undt3ch** [comment]
Bah I need to check if the attributes are set before deleting them...

**Comment by s0undt3ch** [comment]
OK, I know why those tests are failing:
```

**Comment by s0undt3ch** [comment]
OK, I know why those tests are failing:
```
FILES PATH: //testing/tests/integration/files  grail fs path: //testing/tests/integration/files/file/base/grail/scene33 grail: //testing/tests/integration/files/file/base/grail/scene33
```

Now I need to see why those paths are being built like that because they don't here....

**Pull request merged**
