### PR TITLE
[2018.3] Fixes to test_pip state sls files

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Adding an jinja if statement to only the python parameter if the result from get_python_executable is a valid value.  Maintaining backwards compatibilty to run tests without Nox.

### What issues does this PR fix or reference?
N/A

### Tests written?
No.  Fixing existing tests.

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by s0undt3ch — APPROVED** [review]

**Comment by dwoz** [comment]
I want to run the full suite on this before merging.

**Comment by garethgreenaway** [comment]
re-run full all

**Comment by garethgreenaway** [comment]
re-run ubuntu1804-py3

**Comment by dwoz** [comment]
re-run ubuntu1804-py3

**Comment by dwoz** [comment]
re-run all

**Review by twangboy — APPROVED** [review]

**Comment by twangboy** [comment]
@garethgreenaway Looks like you got some lint.... and I don't know what's up with that CentOS test.

**Review by s0undt3ch — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Comment by twangboy** [comment]
Failing on 2019.2.1:
May 22, 2019 1:37:37 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-windows-2019-py2/59/
May 22, 2019 1:36:36 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-windows-2016-py2/52/
May 20, 2019 8:00:00 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-windows-2019-py3/48/
May 22, 2019 1:36:36 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py2-tornado/49/
May 22, 2019 1:36:36 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py2-tornado/47/
May 22, 2019 1:36:36 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py3-transport/50/
May 22, 2019 1:36:36 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py2-transport/52/
May 22, 2019 1:36:36 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py2-transport/48/
May 22, 2019 1:37:37 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py2-m2crypto/54/
May 22, 2019 1:37:37 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py2-pycryptodomex/53/
May 22, 2019 1:37:37 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py2-m2crypto/52/
May 22, 2019 1:36:36 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py3-m2crypto/49/

**Comment by twangboy** [comment]
Need to make sure this gets merged forward

**Pull request merged**
