### PR TITLE
add describe_replication_group to boto_elasticache

### PR DESCRIPTION
**Pull request by tsaridas**
describe_replication_group function that returns the parameters of a replication group
- status
- description
- replication_group_id
- member_clusters
- node_groups
  - node_group_id
  - node_group_members
    - cache_cluster_id
    - cache_node_id
    - current_role
    - preferred_availability_zone
    - read_endpoint
      - address
      - port
  - primary_endpoint
    - address
    - port

### CODE REVIEW

**Comment by jfindlay** [comment]
@tsaridas, will you rebase your pull request on develop?  Thanks.

**Comment by tsaridas** [comment]
is this ok ?

**Comment by jfindlay** [comment]
@tsaridas, I'm still getting 'We can’t automatically merge this pull request.' from github.  I'm not sure what the conflicts are.  I can look into this in about half an hour.

**Comment by tsaridas** [comment]
I'm going to create another pull request since I will be making more changes.

**Comment by jfindlay** [comment]
Thanks, @tsaridas.

**Pull request closed without merging**
