### PR TITLE
Boto apigateway

### PR DESCRIPTION
**Pull request by winstonliu1111**
This is to support the deployment of rest api resources defined in Swagger spec 2.0 in AWS API Gateway and tie the resource handling functions to AWS Lambda Functions to enable a Serverless architecture.

### CODE REVIEW

**Comment by winstonliu1111** [comment]
the failure is the following (the same test passed on ubuntu):

02:27:59   test_get_no_mid (integration.netapi.rest_tornado.test_app.TestMinionSaltAPIHandler)
02:28:09 02:26:35,102 [tornado.application                                 :124 ][ERROR   ] Future exception was never retrieved: TimeoutException
02:28:09 [CPU:33.3%|MEM:57.3%|Z:0]  ... FAIL (10.561s)

**Comment by winstonliu1111** [comment]
@cachedout 
Hi, is there a way to re-trigger the checks?  the failure on centos seems to be a timing issue on a test not related to the changes in this pull request.  Thank you.

**Comment by cachedout** [comment]
Absolutely outstanding! This is really fantastic. Thank you so much for your hard work on this one. This will be a great addition to Salt.

**Comment by kraney** [comment]
Yes, great work, guys!

I would just like to point out that at this point, AWS doesn't even have support for API Gateway in their own CloudFormation orchestration solution.

**Pull request merged**
