### PR TITLE
Keep track of SyncWrapper's IOLoop usage

### PR DESCRIPTION
**Pull request by jacksontj**
While thinking through issues that might cause #25718 I ran into this case-- where you can create 2 sync wrappers with the same parent IOLoop and run into problems because you can't start/stop the loop multiple times like that and have the call tree work correctly. To solve this (since it _should_ be the exceptional case) I'm making SyncWrapper keep track of which loops are in use-- then if someone attempts this situation it will simply make another one.

This error previously resulted in the following exception:

```
RuntimeError: IOLoop is already running
```

### CODE REVIEW

**Comment by jacksontj** [comment]
@jacobhammons Misclose?

**Comment by basepi** [comment]
Yep, sorry about that @jacksontj.

**Comment by jacksontj** [comment]
Looks like the tests passed, although they didn't even run on centos :/

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Pull request merged**
