### PR TITLE
Add support for virtual machines endpoint

### PR DESCRIPTION
**Pull request by avermeer-tc**
### What issues does this PR fix or reference?
Allows pillar to search for Virtual Machines or Devices.

### Previous Behavior
The previous version would only allow you to search for devices.

### New Behavior
The new behavior will let you toggle between devices or vms.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [X] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by DmitryKuzmenko** [comment]
@avermeer-tc could you please write tests covering your chanes?

**Comment by avermeer-tc** [comment]
@DmitryKuzmenko I started working on the test cases. But to be honest, I don't know how to write them effectively. Could you give me some pointers on where to start?

**Comment by DmitryKuzmenko** [comment]
@avermeer-tc thank you for the interest! By a quick look I'd say you need to create a test file `tests/unit/pillar/test_netbox.py` you can copy paste one of the test class headers from any other pillar tests from that directory. Then you'll need to mock `salt.utils.http.query` to return something similar you're seeing in the real life, that will let the `netbox.ext_pillar` function execute correctly. It's better to keep this minimal so check the code for data it uses from the return. Then you can assert that the `salt.utils.http.query` mocked function was called with the correctly formed url containing endpoint you've passed via kwargs. An example of mocking `salt.utils.http.query` function and checking it's calls could be found here: `tests/unit/modules/test_kapacitor.py` (just first thing where I've grepped `http.query`)

Also feel free to reach me in the Community Slack for faster communication. Or write your further questions here.
Glad to help.

**Comment by funzoneq** [comment]
Thanks for the help in getting the test cases + CI solved @DmitryKuzmenko !

**Review by DmitryKuzmenko — APPROVED** [review]

**Comment by DmitryKuzmenko** [comment]
@funzoneq thank you for your work!

**Comment by funzoneq** [comment]
@dwoz there is a test case in this PR.

**Comment by ggiesen** [comment]
Note I have also included a virtual-machines endpoint in #59500

**Comment by nicholasmhughes** [comment]
Jamie Murphy
  [3:10 PM](https://saltstackcommunity.slack.com/archives/C8832QN4U/p1685387455083539)
just a note. this old pr can be closed out: https://github.com/saltstack/salt/pull/58036

**Pull request closed without merging**
