### PR TITLE
Fix ARN lookup when using IAM roles in boto_iam module

### PR DESCRIPTION
**Pull request by ryan-lane**

### CODE REVIEW

**Comment by jfindlay** [comment]
@ryan-lane, is it possible to merge this into 2014.7 or 2015.2?  Thanks.

**Comment by ryan-lane** [comment]
I'd really love for it to be included in at least 2015.2. I don't think this module exists in 2014.7.

**Comment by jfindlay** [comment]
@ryan-lane, you may not know, but since 2014.7, we've changed our pull request workflow, where bug fixes are merged directly into release branches and features are added to develop.  This way, release branches can be regularly merged into develop without having to move extra commits around to keep the branches synchronized.

http://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch

**Comment by rallytime** [comment]
@ryan-lane Backported!

**Pull request merged**
