### PR TITLE
Add pkg.latest_version windows test

### PR DESCRIPTION
**Pull request by Ch3LL**
### What does this PR do?
make sure the test `test_pkg_latest_version` can run on windows as well

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/45004

### CODE REVIEW

**Review by dwoz — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Comment by rallytime** [comment]
@Ch3LL Can you check and see if this test failure for CentOS 7 is correct?

- integration.modules.test_pkg.PkgModuleTest.test_pkg_upgrade_has_pending_upgrades

I don't recall if that one is failing elsewhere or not, but it seems that it could be related to this change.

https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-cent7-py3/4933/

**Comment by damon-atkins** [comment]
To test pkg.x   states  would it not be best to develop some fake bits of software.
e.g. rpm called salt-package-test   1.0   and 1.6 and 2.0z etc.   and for windows develop some fake msi

Both  only install a flag file or  something so you can test the install work and the removed worked. Or test for corner cases.

In Windows lots of software does weird stuff.

**Comment by Ch3LL** [comment]
@damon-atkins can you clarify `In Windows lots of software does weird stuff` and why that would impact testing if putty was installed/removed.

@rallytime i'm not seeing how that would impact that test. i'm not even touching that test and on the linux side of things i just changed the multiple references from htop to a variable, i didn't change anything else on the linux side of the test. I also checked and htop is not being tested in that test so i'm pretty certain this new test is not the cause of that failure.

**Comment by Ch3LL** [comment]
talked with @rallytime offline and I will try to test tomorrow to triple check that this test isn't impacting the other :)

**Comment by Ch3LL** [comment]
awesome thanks for elaborating @damon-atkins . I agree we could get a lot more flexibility and speed using custom packages. I was asking about the putty install just to make sure I wouldn't be missing something if we did merge this.

I will ago ahead and open an issue when I get back to this PR tomorrow to add custom packages to our test infrastructure but I think its okay to merge this when its ready and add the custom packages later :)

**Comment by Ch3LL** [comment]
I was not able to replicate the test failure using the same VMs the PR test runs use: 

```
[root@ip-10-0-0-55 testing]# python3 tests/runtests.py -n integration.modules.test_pkg --run-destructive
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Python Version: 3.4.8 (default, Mar 23 2018, 10:04:27) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
 * Transplanting configuration files to '/tmp/salt-tests-tmpdir/config'
 * Current Directory: /testing
 * Test suite is running under PID 18769
 * Logging tests on /tmp/salt-runtests.log
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Max open files settings is too low (soft: 1024, hard: 4096) for running the tests
 * Trying to raise the limits to soft: 3072, hard: 4096
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Setting up Salt daemons to execute tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Starting salt-master ... STARTED!
 * Starting salt-minion ... STARTED!
 * Starting sub salt-minion ... STARTED!
 * Starting syndic salt-master ... STARTED!
 * Starting salt-syndic ... STARTED!
=======================================================================================================================================================
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Starting integration.modules.test_pkg Tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
........ss
----------------------------------------------------------------------
Ran 10 tests in 297.955s

OK (skipped=2)

===============================================================  Overall Tests Report  ================================================================
*** integration.modules.test_pkg Tests  ***************************************************************************************************************
 --------  Skipped Tests  -----------------------------------------------------------------------------------------------------------------------------
   -> integration.modules.test_pkg.PkgModuleTest.test_refresh_db   ->  WARNING(SHOULD NOT HAPPEN #1935): Failed to get 'pkg.refresh_db' from the minion 'minion'. Command output: {'minion': None}
   -> integration.modules.test_pkg.PkgModuleTest.test_version_cmp  ->  pkg.version_cmp is unavailable on RedHat
 ------------------------------------------------------------------------------------------------------------------------------------------------------
=======================================================================================================================================================
OK (total=10, skipped=2, passed=8, failures=0, errors=0)
===============================================================  Overall Tests Report  ================================================================
```

i'll restart the tests to make sure this is the case.

**Comment by Ch3LL** [comment]
re-run py3

**Pull request merged**
