### PR TITLE
make http.query supports python 3

### PR DESCRIPTION
**Pull request by angeloudy**
this fixes the bytes object required error.

I am not sure if this will fix all http.query issues. At least this worked for me.

### CODE REVIEW

**Comment by rallytime** [comment]
Hi @angeloudy - can you add some checks here for py3 usage? Similar to #45201.

**Comment by rallytime** [comment]
Hi @angeloudy Thanks for updating this. There are not some conflicting files. Can you rebase this and fix the conflicts? Let us know if you have questions.

**Comment by rallytime** [comment]
@angeloudy Just a bump here to see if you saw my comments above.

**Comment by rallytime** [comment]
@angeloudy bump

**Comment by terminalmage** [comment]
This PR was opened against the develop branch when it looks like you branched off of 2017.7 to make your changes. Please click "Edit" and change the base branch to 2017.7, otherwise we will not be able to merge this.

**Comment by rallytime** [comment]
Since this PR is not submitted against the correct branch (there are many conflicting files and extra commits in here), I am going to close this. Please feel free to open a new PR against the correct branch. Thanks!

**Pull request closed without merging**
