### PR TITLE
Fix SELinux get policy with trailing whitespace

### LINKED ISSUE #63336: [BUG] SELinux fcontext can sometimes not be retrieved
**Description**
It seems that sometimes the output from `semanage fcontext -l` can contain a trailing whitespace. This leads to erroneous returns when checked if a specific file context exists. If it exists it will return an error like

```
Error adding new rule: {'pid': 5778, 'retcode': 1, 'stdout': '',
'stderr': 'ValueError: File context for /var/log/rsyslog-target(/.*)?
already defined'}
```

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [x] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
Add fcontext via the state - the first time it will succeed and afterwards it will fail, see error above.

**Expected behavior**
It should be noticed it is already there and not tried to add it again.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: 1.1.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 1.6.1
        Python: 3.7.13 (default, Apr 20 2022, 03:16:50)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: alpine 3.14.6 
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-408.el8.x86_64
        system: Linux
       version: Alpine Linux 3.14.6 
```
</details>

**Additional context**

### PR DESCRIPTION
**Pull request by derdeagle**
It seems that sometimes the output from `semanage fcontext -l` can contain a trailing whitespace. This leads to erroneous returns when checked if a specific file context exists. If it exists it will return an error like

```
Error adding new rule: {'pid': 5778, 'retcode': 1, 'stdout': '',
'stderr': 'ValueError: File context for /var/log/rsyslog-target(/.*)?
already defined'}
```

This commit adds support for optional trailing whitespaces in the output of `semanage fcontext -l`.

### What does this PR do?
This PR adds support for trailing whitespaces in the output of `semanage fcontext -l`.

### What issues does this PR fix or reference?
Fixes: #63336

### Previous Behavior
If there were trailing whitespaces in the output of `semanage fcontext -l` the function `selinux.fcontext_get_policy` would return no result even though there is one.

### New Behavior
Now the function `selinux.fcontext_get_policy` will return the result even if there is a trailing whitespace.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated
I tried to come up with a test scenario for it but at least I couldn't do it as for this part the regular expression used in the module is never used in the test cases. One option would be to just get all fcontext entries via `semanage fcontext -l` and filter it out in python instead of using ` | egrep ...`. As that would change the way the data is retrieved too much for my change I didn't do that. Maybe somebody else can evaluate if this is suitable.

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by derdeagle** [comment]
@garethgreenaway may I please ask you to take a look at this PR and tell me if I need to get something else done to be conform? It's the first time I have the opportunity to contribute and unfortunately it took some time to get it sorted - in the meantime I also added the changelog file.

**Comment by garethgreenaway** [comment]
@derdeagle Thanks for the contribution.  We'll also need a test case for the changes, let me know if you require assistance in writing that.  Thanks!

**Comment by derdeagle** [comment]
@garethgreenaway Thank you for your offer which I'd like to accept without hesitation.
Currently the test patches the `cmd.shell` return value which is the one that needs to be tested. How can a test for this be written other than changing from:
getting only the matching (via egrep) file contexts
to
getting all the file contexts and then filter inside of Python?

**Comment by dmurphy18** [comment]
@derdeagle Wondering if you are still interested in this PR, otherwise I was going to port the fix to the 3006.x branch and write a test case for it.

**Comment by derdeagle** [comment]
@dmurphy18 Thanks for jumping in. I never lost interest in this as I still need it - I pushed my changes to all the minions. As stated in one of my comments I just don't know to write a test case for this so if you offer to do so that'd be great. Thank you ;)

**Comment by dmurphy18** [comment]
@derdeagle Can you review PR https://github.com/saltstack/salt/pull/64950, which replaces this.  Modified existing selinux tests to allow for extra spaces and tab too.

Can you leave any comments on that PR and if satisfied, please consider closing this PR.

Wanted to get this into the Salt 3006.x branch which should be released sooner rather than master (which will be used for Salt 3007).

**Comment by derdeagle** [comment]
@dmurphy18 Sorry I missed your comment. I added a note and then saw it was already merged. Thank you for your help, I will close this PR now.

**Pull request closed without merging**
