### PR TITLE
Kapacitor state and module

### PR DESCRIPTION
**Pull request by anlutro**
Kapacitor is a monitoring/alerting system for InfluxDB.

This is somewhat WIP, and I've yet to write tests. Don't merge quite yet.

Normally I'd target develop for new features but since this doesn't touch any existing files I figured it'd be OK to target 2016.3, in hopes of it being done and merged before the official release.

### CODE REVIEW

**Comment by rallytime** [comment]
@anlutro Actually, can you please move this to develop? The 2016.3 branch is feature frozen, and since this is a new module and state, the `_modules` and `_states` directories can be used to sync these new features out to your minions. That was this can soak in the develop branch for a little while and any bugs can be worked out before adding it to an official release.

Also, thank you very much for writing tests! :)

**Comment by anlutro** [comment]
Sure thing. We've actually tested these for a week or so, but enforcing a feature freeze is something I support you doing.

**Comment by anlutro** [comment]
https://github.com/saltstack/salt/pull/31761

**Comment by rallytime** [comment]
Thanks!

**Pull request closed without merging**
