### PR TITLE
GCE Cloud tests

### PR DESCRIPTION
**Pull request by tonybaloney**
### What does this PR do?

Strip out all the mocks and just focus on the certificate and import process for the GCE cloud module. The test suite needs expanding, the GCE cloud module has a ton of untested behaviours, dict mappings and all sorts of assumptions about environment and configuration that are not tested.
Change also updates all the of the temporary fixes around certificates for SuSE and MacOS/brew/ports. Libcloud 1.0 + supports `certifi` as the source of SSL/PEM files. 
### What issues does this PR fix or reference?

Issue saltstack/salt#34852
### Previous Behavior

GCE tests would hang trying to instantiate driver, GCE changed the token logic in a recent version of libcloud.
### New Behavior

Remove this section if not relevant
### Tests written?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by tonybaloney** [comment]
CC @supertom @erjohnso

**Comment by tonybaloney** [comment]
CC @cachedout @rallytime 
p.s. I'm curious if there are integration tests how they never picked up issue #32743

**Comment by rallytime** [comment]
@tonybaloney This doesn't look quite right. :) The only changes appear to be merge conflict lines.

As to why the test suite didn't uncover that issue, it is because the cloud integration tests (since they spin up a bunch of VMs for each cloud provider) are only run on two distributions currently: CentOS 7 and Ubuntu 14. I bet I can convince @jtand to add SUSE to that mix though.

**Comment by rallytime** [comment]
@tonybaloney Oh, I must have been looking at an old reference before. Thanks for taking another crack at this. Can you take a look at the [small pylint error](https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/3539/violations/file/tests/unit/cloud/clouds/gce_test.py/), as well as the [related test failure](https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/3686/testReport/junit/unittest.loader/ModuleImportFailure/gce_test/) when you get a chance?

**Comment by tonybaloney** [comment]
done and done @rallytime

**Comment by cachedout** [comment]
@tonybaloney Looks like some merge conflicts. Could you rebase this please?

**Comment by tonybaloney** [comment]
rebased.

**Comment by rallytime** [comment]
Awesome! thanks @tonybaloney - Looks like Jenkins is having a rough time in general on our end. I'll trigger a new test run.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Thanks for cleaning these up @tonybaloney - this looks great.

**Pull request merged**
