### PR TITLE
requisite_any

### PR DESCRIPTION
**Pull request by thatch45**
### What does this PR do?
This PR adds 4 new requisites:
require_any
watch_any
onchanges_any
onfail_any
### What issues does this PR fix or reference?
None
### Previous Behavior
Remarkably less awesome

### New Behavior
Significantly more awesome

### Tests written?
No, but this really needs some tests

### CODE REVIEW

**Comment by thatch45** [comment]
Please note, I have not tried to make `prereq_any` yet, that might be insane.

**Comment by rallytime** [comment]
Fixes #43292

**Comment by rallytime** [comment]
This is neat!

This can likely happen in a follow up PR, but this new feature needs the following additions:
- Oxygen release notes
- Tests
- Documentation about how this works [here](https://docs.saltstack.com/en/latest/ref/states/requisites.html)

I just wanted to mention that here so it's on the radar. We can make an issue to follow up with whatever needs to be completed in the list when this is merged.

ping @cachedout and @Ch3LL

**Comment by mirceaulinic** [comment]
This is great, thank you!

It would be nice to add these options to the requisites doc too: https://docs.saltstack.com/en/develop/ref/states/requisites.html.

**Comment by rallytime** [comment]
@thatch24 This made a couple of requisite unit tests unhappy, I'm afraid.

**Comment by thatch45** [comment]
@rallytime that was my main concern, to see what the Jenkins tests looked like. This is a part of the code where it is easy to make a mistake.

**Comment by thatch45** [comment]
That is an infinite recursion error, I might have to go back to the drawing board on this one....

**Comment by thatch45** [comment]
```
Traceback (most recent call last):
  File "/testing/tests/integration/modules/test_state.py", line 557, in test_requisites_mixed_require_prereq_use
    result = self.normalize_ret(ret)
  File "/testing/tests/integration/modules/test_state.py", line 596, in normalize_ret
    for item, descr in six.iteritems(ret):
  File "/testing/salt/ext/six.py", line 606, in iteritems
    return d.iteritems(**kw)
AttributeError: 'str' object has no attribute 'iteritems'
```

**Comment by thatch45** [comment]
```
 File "/testing/salt/state.py", line 2399, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/testing/salt/state.py", line 2399, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/testing/salt/state.py", line 2399, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/testing/salt/state.py", line 2399, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/testing/salt/state.py", line 2399, in call_chunk
    running = self.call_chunk(low, running, chunks)
  File "/testing/salt/state.py", line 2388, in call_chunk
    running = self.call_chunk(chunk, running, chunks)
  File "/testing/salt/state.py", line 2405, in call_chunk
    self.pre[tag] = self.call(low, chunks, running)
  File "/testing/salt/state.py", line 1741, in call
    local_start_time.time().isoformat()
  File "/usr/lib/python2.7/logging/__init__.py", line 1152, in info
    self._log(INFO, msg, args, **kwargs)
  File "/testing/salt/log/setup.py", line 328, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/usr/lib/python2.7/logging/handlers.py", line 429, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 942, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 879, in emit
    self.handleError(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 802, in handleError
    None, sys.stderr)
  File "/usr/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib/python2.7/traceback.py", line 69, in print_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/usr/lib/python2.7/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
  File "/usr/lib/python2.7/linecache.py", line 40, in getlines
    return updatecache(filename, module_globals)
RuntimeError: maximum recursion depth exceeded
```

**Pull request closed without merging**
