### PR TITLE
Consul SDB driver

### PR DESCRIPTION
**Pull request by ashald**
A simple SDB driver for Consul. Allows full control over client options.

### CODE REVIEW

**Comment by techhat** [comment]
Nice! +1

**Comment by Ashald** [comment]
PS: Already tested in production. :)

**Comment by Ashald** [comment]
P.P.S.: Intended to be used with #31145 as Consul uses `/` in keys

**Comment by techhat** [comment]
Hey @Ashald, you've got a lint error here, would you mind cleaning that up?

**Comment by Ashald** [comment]
All green. :)

**Comment by Ashald** [comment]
Thanks!

**Pull request merged**
