### PR TITLE
Add beacon to monitor network settings

### PR DESCRIPTION
**Pull request by adelcast**
This beacon uses pyroute2.

Signed-off-by: Alejandro del Castillo alejandro.delcastillo@ni.com

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @adelcast. I submitted a minor fix against your branch. Please take a look and merge it and then we'll get this merged. Thanks!

**Comment by cachedout** [comment]
Saw that you merged that. Thanks! This is now merged in upstream. :]

**Comment by adelcast** [comment]
thanks a bunch!

**Comment by cachedout** [comment]
Sure thing. Thanks for this excellent contribution!

**Pull request merged**
