### PR TITLE
Fix the lazy loader to keep a top level key ref

### PR DESCRIPTION
**Pull request by thatch45**
this allows jinja to do the salt.test.ping lookup

also adds some tests for it courtesy of @whiteinge

### CODE REVIEW

**Comment by thatch45** [comment]
I am going to try to add a top level attribute ref as well so we can:

```
__salt__.test.ping()
```

**Comment by thatch45** [comment]
@jacksontj do you see any issues in here that I have overlooked? The lazy loader broke some Jinjaisms that this should solve

**Comment by thatch45** [comment]
This last fix should do it

**Comment by jacksontj** [comment]
I don't like keeping the `mod.func` and `mod` stuff all in the same dict... but it does fix the problem :/ I just really don't like all of the `if '.' not in foo: continue` stuff-- it seems like a bit of a mess. What we could do is keep a dict of modules that have been loaded as a separate dict... let me play around with that idea...

**Pull request merged**
