### PR TITLE
Issues/23373 reactor race condition

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
**Please DO NOT immediately merge**

My approach for #23373

### CODE REVIEW

**Comment by cachedout** [comment]
@DmitryKuzmenko I think you'll want to also look at #27843 for an alternative implementation.

**Comment by DmitryKuzmenko** [comment]
@cachedout saw it yesterday, just shared my solution. Now I'm looking to Tom's solution in details. At least it looks closer to Tornado and Pythonic.

**Comment by cachedout** [comment]
@DmitryKuzmenko Sounds good. I was just making sure you saw it. Thanks!

**Comment by DmitryKuzmenko** [comment]
@cachedout thank you for taking care of this =)

**Comment by DmitryKuzmenko** [comment]
I've picked bugfixes for the existing non-related bugs from this PR and published them as separate PRs. The main bugfix would be done by Thomas so I close this one.

**Pull request closed without merging**
