### PR TITLE
Move all pipelines to be fully scripted

### PR DESCRIPTION
**Pull request by KaiSforza**
This allows us to properly clean out the workspace before a job run.

### What does this PR do?

Changes the Jenkinsfiles to use scripted pipelines, not declarative pipelines. Should fix the failures we were getting with old workspaces being used. Not sure exactly how it's going to work if we are actually using old workspaces...but this should make new builds work.

### What issues does this PR fix or reference?

Not cleaning up our workspace before the build. We now clean the workspace, clone the git repo, and then do the build.

### Commits signed with GPG?

Yes

@gtmanfred @dubb-b @rallytime

### CODE REVIEW

**Comment by KaiSforza** [comment]
This jenkins job was run with the new scripted pipeline, only ran a single test for speed, though.

https://jenkinsci.saltstack.com/job/pr-kitchen-centos7-py2/job/PR-48809/43/console

**Review by gtmanfred — APPROVED** [review]

**Comment by damon-atkins** [comment]
The `agent` statement cleans up when it checks out the scm.  For example if each stage had a `agent` line it would clean up between stages.

You can also set this in the stage
`options { skipDefaultCheckout() }`
and then do your own
```
cleanWS 
checkout scm
```
There is no need to convert to "fully scripted"

**Comment by KaiSforza** [comment]
@damon-atkins Looking back at some of the tests, it was only cleaning up on successful builds if it got to the end, the `agent` statement wasn't doing anything to clean up. 

There are also other reasons why I want to convert to a scripted style, as well.

**Comment by damon-atkins** [comment]
Maybe in post the junit was failing and it never reached the cleanWS

By the way the BlueOcean interface works well for users, makes the logs and unit tests easier to read as well.

**Comment by KaiSforza** [comment]
@damon-atkins That's what I think was happening. Again, this isn't just because of the failed cleanups, but other stuff we want to do that *can't* be done in the declarative pipelines.

 Us devops people have been wanting to switch over to it, I personally want it, but there are reasons we haven't switched.

**Pull request merged**
