### PR TITLE
New provider for 1&1 Cloud Servers

### PR DESCRIPTION
**Pull request by edevenport**
### What does this PR do?

Adds a new cloud provider for 1&1 Cloud Servers.

### Tests written?

Yes

### CODE REVIEW

**Comment by rallytime** [comment]
Thank you for adding this new driver @edevenport! It looks like there are several [lint errors](https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/13482/violations/file/salt/cloud/clouds/oneandone.py/). Can you clean those up?

**Review by gtmanfred — APPROVED** [review]
Looks good to me.

Thanks for the tests!

**Review by cachedout — APPROVED** [review]
This is really nicely done! Thanks!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@edevenport Could you please fix these lint errors before we merge this? Thanks!

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/13694/violations/file/salt/cloud/clouds/oneandone.py/

**Comment by edevenport** [comment]
@cachedout @rallytime The lint errors have been addressed, I pulled the latest from development, and rebased. The tests are running now and fingers crossed.

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
👍

**Pull request merged**
