### PR TITLE
virt.network_update: handle missing ipv4 netmask attribute

### LINKED ISSUE #59692: virt.network_update fails to update virtual network with prefix attribute rather than netmask
### Description of Issue

`virt.network_update` fails to update virtual network with `prefix='..'` rather than `netmask='..'`.

### Steps to Reproduce Issue

* Defined a virtual network with such a libvirt XML definition:

```xml
<network>
  <name>private0</name>
  <uuid>1ff4eea5-5902-4c4f-a359-29c8521c9b31</uuid>
  <forward mode='open'/>
  <bridge name='virbr2' stp='on' delay='0'/>
  <mtu size='7000'/>
  <mac address='52:54:00:91:17:83'/>
  <ip family='ipv4' address='192.168.10.1' prefix='24'>
  </ip>
</network>
```
* run a `salt virthost virt.network_update ...` call with any parameter

Actual behavior: fails with the following backtrace:

```
  File "/usr/lib/python3.6/site-packages/salt/state.py", line 1987, in call
    ret = self.states[cdata['full']](*cdata['args'], **cdata['kwargs'])
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2031, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/states/virt.py", line 1805, in network_running
    password=password,
  File "/usr/lib/python3.6/site-packages/salt/states/virt.py", line 1498, in network_defined
    password=password,
  File "/usr/lib/python3.6/site-packages/salt/modules/virt.py", line 7319, in network_update
    netmask = ip_node.attrib.pop("netmask")
KeyError: 'netmask
```

Expected behavior: update the virtual network

### PR DESCRIPTION
**Pull request by cbosdo**
### What does this PR do?

In the libvirt definition, the IPv4 netmask XML attribute may be
replaced by the prefix one. Handle this situation gracefully rather than
miserably failing.

### What issues does this PR fix or reference?
Fixes: #59692

### Merge requirements satisfied?
- [X] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by cbosdo** [comment]
re-run centos7-py3-tcp-pytest

**Comment by cbosdo** [comment]
re-run macosxmojave-py3-pytest

**Comment by cbosdo** [comment]
@Akm0d @s0undt3ch could one of you review that (simple) long-standing PR?

**Review by s0undt3ch — APPROVED** [review]

**Comment by cbosdo** [comment]
re-run freebsd-122-amd64-py3-pytest

**Comment by cbosdo** [comment]
re-run macosx-catalina-x86_64-py3-pytest

**Comment by cbosdo** [comment]
re-run macosx-catalina-x86_64-py3-pytest

**Comment by cbosdo** [comment]
re-run full macos

**Comment by cbosdo** [comment]
re-run full macos

**Comment by cbosdo** [comment]
re-run full macos

**Comment by cbosdo** [comment]
re-run full macos

**Comment by cbosdo** [comment]
re-run full macos

**Review by Ch3LL — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
