### PR TITLE
Add fileserver syncing

### PR DESCRIPTION
**Pull request by basepi**
### What does this PR do?

Adds custom fileserver syncing from `salt://_fileserver/`

### What issues does this PR fix or reference?

n/a

### Tests written?

No

### CODE REVIEW

**Review by gtmanfred — APPROVED** [review]

**Comment by cachedout** [comment]
Nice!

**Comment by terminalmage** [comment]
@basepi Have you confirmed that the loader pulls in the fileserver modules from within extmods? It should, but I haven't tested it.

**Comment by terminalmage** [comment]
It looks like it does via ``_module_dirs(opts, 'fileserver')`` when a fileserver loader instance is spawned.

**Comment by basepi** [comment]
Yep, checked loader.py first. :)

**Pull request merged**
