### PR TITLE
[PR port] Port #52317 - Fixes to manage_schedule in minion.py

### PR DESCRIPTION
**Pull request by piterpunk**
PR port #52317
- [X] Changelog
- [X] Tests written/updated

### CODE REVIEW

**Comment by piterpunk** [comment]
All the failed tests seems to fail on unit.states.test_network.NetworkTestCase.test_managed, which is not part of this PR.

**Comment by piterpunk** [comment]
@dwoz can you re-run the failed tests? The failures didn't seems to be related with the code itself.

**Comment by Akm0d** [comment]
There are merge conflicts that need to be resolved on the command line

**Comment by piterpunk** [comment]
> There are merge conflicts that need to be resolved on the command line

Hi @Akm0d , conflicts resolved. Now there is one errored check, but it was aborted by timeout, not by an actual error.

**Comment by piterpunk** [comment]
re-run pr-freebsd122-py3-pytest

**Comment by piterpunk** [comment]
Ok, now this port to master looks Ok to ask for merge again. But I don't know if this is still needed.

@garethgreenaway , as the original author, this change is still needed or the best is to cancel this MR?

**Comment by garethgreenaway** [comment]
@piterpunk Thanks for the MR, looking at the changes it appears this is different than the original PR though, and is removing some functionality.  It also looks like the changes in question are already in place.

**Comment by piterpunk** [comment]
> @piterpunk Thanks for the MR, looking at the changes it appears this is different than the original PR though, and is removing some functionality. It also looks like the changes in question are already in place.

Nice! So I will close it. Thank you!

**Pull request closed without merging**
