### PR TITLE
adding states/mount unit test case

### PR DESCRIPTION
**Pull request by jayeshka**
Implemented states/mount_test unit test case.

### CODE REVIEW

**Comment by jayeshka** [comment]
@jfindlay after merging the issue  #24063, should fix the above error.

**Comment by jfindlay** [comment]
Thanks, @jayeshka.

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
In order for this pull request to successfully pass the test, it needed to be rebased on the branch after the fix came through.  I have done this in #24090.

**Comment by rallytime** [comment]
@jfindlay Hrm...shouldn't this have merged in when I merged your PR above? Should this be closed since it didn't seem to work with the merge above?

**Comment by jfindlay** [comment]
It might be because I had to rebase the commit, but in any case, the tests have been added.  Thanks @jayeshka.

**Pull request closed without merging**
