### PR TITLE
Do not close singleton instances.

### PR DESCRIPTION
**Pull request by mattp-**
This must be done by GC when there are no references to it.

this is a forward port of https://github.com/saltstack/salt/pull/45839 to develop so I can see what jenkins does with it

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by DmitryKuzmenko — APPROVED** [review]
I had such PR before but it has failed tests and I had no time to check that yet. So nice to see this! Looks good.

**Comment by mattp-** [comment]
yep! no coincidence, I started seeing this issue under high load and found your pr. I actually git am'd it so you are still committer/author.

**Comment by DmitryKuzmenko** [comment]
Yay! So you've just rebased it and tests passed?
This was what I've expected originally but for some reason test suite failed when I've made that PR.
Anyway thank you!

**Comment by mattp-** [comment]
@DmitryKuzmenko the ipc test needed one or two tweaks, i think the main thing was https://github.com/saltstack/salt/pull/50798/files#diff-93d61077044d24949e87f89b9221d1c0R102 
moving the super() call after the chanenl close() in the test class cleanup, nothing in the actual code though.
unfortunately wrt the bug your changes aimed to squash, seems to be still lurking elsewhere, as I'm still seeing the StreamClosed exception under very hgih orchestration load :( will keep investigating.

**Pull request merged**
