### PR TITLE
Added 'once' support to the scheduler

### PR DESCRIPTION
**Pull request by whiteinge**

### CODE REVIEW

**Comment by whiteinge** [comment]
@garethgreenaway may I trouble you to check my work here?

**Comment by garethgreenaway** [comment]
Definitely like the cleanup of the conflicts, a lot better :) For running a command at at certain time and ensuring it's only run once, the existing when argument would work.  Just give it a specific date and time, instead of something arbitrary like '8pm'.

**Comment by whiteinge** [comment]
Thank you, sir!

Sorry, I should have clarified intent here (it's late). We're happily using `when` for one-time runs in most places. But we came across a dependency sensitive use-case and wanted something parseable only using stdlib tools. I liked the encapsulated `WHEN_SUPPORTED` code structure and didn't want to muddy that by trying to shoehorn both use cases there.

**Comment by garethgreenaway** [comment]
Ah!  I realized that might be the case as soon as I sent off the response.  Overall it looks good to me, the only thing I was uncertain about was setting seconds to 1 instead of 0, but looks closer at the code until the time is reached the job is just skipped by the continue.

**Pull request merged**
