### PR TITLE
replace infoblox module and state with different implantation

### PR DESCRIPTION
**Pull request by steverweber**
### What does this PR do?

replace infoblox module and state with different implantation

### What issues does this PR fix or reference?

https://github.com/saltstack/salt/issues/41907

### Previous Behavior

simple api to infoblox

### New Behavior

more advanced options and improved state management that includes
change in state updates.

### Tests written?

No

### CODE REVIEW

**Comment by steverweber** [comment]
this PR is a WIP will likely need some lint and doc fixes.
Also note this does not support backwards compatibility.

**Comment by lomeroe** [comment]
What's your thought process behind the change to individualized states for the different record types?  Selfishly, I'd prefer to keep (as much) backward compatibility as possible.

I'm personally not opposed to switching to your external API, though I will admit I like not having any dependencies other than the minion to manage things.

**Comment by steverweber** [comment]
> individualized states for the different record types

reduces code in the corresponding state files like `infoblox_host_record`
also little more user friendly when deleting records.

 > I will admit I like not having any dependencies other than the minion to manage things
I think you're referencing 'libinfoblox' I also felt the same on this. Was tempted to include it embedded in the module.. however I do have places outside salt where I access infoblox from script files and found that the python module is a clean solution.

**Comment by cachedout** [comment]
@lomeroe Did you have any additional comments on this one?

**Comment by lomeroe** [comment]
@cachedout My main concern is the potential for rework for people (like me) who are already extensively using infoblox.present.  I could be one of a few that it would really impact, since the module/state has only been in releases since 2016.3 (though I have been using it since putting it into develop).  I was also concerned that it may break the integration that I added to boto_elb to allow adding ELB cnames into infoblox, but I just noticed [this commit](https://github.com/saltstack/salt/commit/997f3f0ba37a93b74049b259424e3f388a8bbbc4) has removed that functionality (perhaps unintentionally).

I can go either way on if I personally like the change or not.  On one hand, I do see the benefits that @steverweber  has listed, but I also see the benefit of having some commonality between the DNS type states (like route53/ddns) which are a single state with a present function that accepts arguments.

Perhaps if the infoblox was kept around (at least for some time) and called out to the other states based on parameters and/or function?

**Comment by cachedout** [comment]
@steverweber Thoughts on the above at all?

**Comment by steverweber** [comment]
I agree with @lomeroe on most thoughts.

 > Perhaps if the infoblox was kept around (at least for some time) and called out to the other states based on parameters and/or function?

I assume you are saying it would be nice to include some of the previous function definitions so it's backwards compatible. In your case @lomeroe.. i'd just override this PR with your own module so you can keep your current salt states untouched until or if you ever want to migrate to the code in this PR.

If we want to maintain backwards compatible perhaps this PR can be renamed something like `infobox_extra`. or this PR can have a little help added to the top of the doc string that says how to restore the past behavior by adding the previous version of `infoblox` to their `_modules/ , _states/`

sorry i didn't get around to submitting this a few years ago.. I personally didn't think infoblox was that popular.

**Comment by steverweber** [comment]
gogo jenkins

**Comment by steverweber** [comment]
moved to: https://github.com/saltstack/salt/pull/42324

**Pull request closed without merging**
