### PR TITLE
glob on absolute path instead of relative path

### PR DESCRIPTION
**Pull request by angeloudy**
### What does this PR do?
Resubmitting PR #54808 to master branch

### Tests written?
**[NOTICE] Bug fixes or features added to Salt require tests.**
Please review the [test documentation](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html) for details on how to implement tests into Salt's test suite.

Not needed

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by dwoz** [comment]
re-run full centos

**Comment by dwoz** [comment]
@angeloudy Can you write a test for this change?

**Comment by DmitryKuzmenko** [comment]
Here's the PR where the basename match was added https://github.com/saltstack/salt/pull/27917
There's no details wy. I'm just not sure how the change could affect others. Maybe it's better to make the full path match an option? @saltstack/team-core

**Comment by DmitryKuzmenko** [comment]
@angeloudy thank you for contribution. We definitely need tests here as DWos asked. Also could you please install the pre-commit hook on your repo and update this PR?

**Comment by waynew** [comment]
I was able to track the discussion down to https://groups.google.com/g/salt-users/c/qZvmtdGxLKg/m/awL8FwfiCQAJ

> eg
`salt-call cp.push_dir /etc/sysconfig/network-scripts glob='ifcfg-*'`
> does not work, but:
`salt-call cp.push_dir /etc/salt/minion.d glob='*.conf'`
> does.
> Bug or feature? (It looks buggy to me, and it sure is annoying.)
Using 2015.5.3 (Lithium).

I'll probably go ahead and write some tests for this during Tuesday's test clinic

**Comment by waynew** [comment]
Writing tests currently - just discovered that this desired behavior would definitely break backwards compatibility, the aforementioned intended behavior. However, we can introduce a flag - `glob_recurse=True` for example, that would allow *this* desired behavior.

**Comment by waynew** [comment]
I went ahead and added test cases for this. As previously mentioned, it would be impossible/unfeasible to try and both maintain backwards compatibility along with having the recursive capabilities. This introduces the ability to use recursive globbing, but doesn't clobber any of the existing intentional functionality.

**Review by Akm0d — DISMISSED** [review]

**Comment by waynew** [comment]
Doc build failed. Fixed docs as well as went ahead and Boy Scout'ed the rest of the docs in this module. Should be good *now*.

**Comment by Ch3LL** [comment]
Looks like some test failures on windows here still

**Comment by sagetherage** [comment]
Removing from `Aluminium` for now

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
