### PR TITLE
RedHat IPv6 static routes

### PR DESCRIPTION
**Pull request by t0fik**
1. Added support for setting IPv6 static routes in RedHat systems.
2. New template for static routes file in Redhat systems 6+

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Thanks @t0fik!

Can you fix up the pylint errors when you get a moment? https://jenkins.saltstack.com/job/salt-pr-lint-n/6029/violations/file/salt/modules/rh_ip.py/

**Comment by t0fik** [comment]
@rallytime,
Problems has been solved.

**Comment by rallytime** [comment]
Awesome! Thanks very much!

**Pull request merged**
