### PR TITLE
Use timedatectl set-timezone to tzsetting if available

### LINKED ISSUE #26122: Bug: `timezone.get_zone` returns old tzname
```shell
root# lsb_release -rd
Description:	Ubuntu 14.04.3 LTS
Release:	14.04

root# salt-call --version
salt-call 2015.5.3 (Lithium)

root# salt-call timezone.get_zone
[INFO    ] Executing command 'timedatectl' in directory '/root'
local:
    Europe/Moscow

root# salt-call timezone.set_zone Etc/UTC
local:
    True

root# salt-call timezone.get_zone
[INFO    ] Executing command 'timedatectl' in directory '/root'
local:
    Europe/Moscow

root# cat /etc/timezone
Etc/UTC

root# ls -l /etc/localtime
lrwxrwxrwx 1 root root 27 Aug  8 01:38 /etc/localtime -> /usr/share/zoneinfo/Etc/UTC
```

**See also**:
[timedatectl status prints old timezone](https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1482808)

I can reproduce this bug on:
* Ubuntu (Trusty, Vivid)
* Debian (Jessie)

Affects to https://github.com/saltstack/salt/pull/26117

### PR DESCRIPTION
**Pull request by evverx**
Fixed #26122

### CODE REVIEW

**Comment by evverx** [comment]
Note:
> If the RTC is configured to be in the local time, this will also update the RTC time

Is it an expected behaviour?

**Comment by cro** [comment]
Go Go Jenkins!

**Comment by evverx** [comment]
@cro, Jenkins looks fine:)

**Comment by cachedout** [comment]
Thanks @evverx

**Pull request merged**
