### PR TITLE
Grafana4 salt module and states

### PR DESCRIPTION
**Pull request by bbinet**
### What does this PR do?

Add grafana4 salt module and states.

### What issues does this PR fix or reference?

This PR address the limitations described in the following comment:
https://github.com/saltstack/salt/issues/29648#issuecomment-263628222

### Tests written?

No

### CODE REVIEW

**Comment by mirceaulinic** [comment]
👍

**Comment by cachedout** [comment]
Nice!

@bbinet Could you please fix these lint errors up? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/7480/violations/

**Comment by bbinet** [comment]
@cachedout: Hopefully commit ed33183 should fix these lint errors.

**Comment by bbinet** [comment]
I will add docstring to the grafana4 module function to fix https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/7352/testReport/junit/integration.modules.sysmod/SysModuleTest/test_valid_docs/

**Pull request merged**
