### PR TITLE
OpenBSD salt package: update list of dependencies.

### PR DESCRIPTION
**Pull request by ajacoutot**

### CODE REVIEW

**Comment by jfindlay** [comment]
@ajacoutot, thanks for the update.  Does this need to go into 2015.5 or 2015.8?

**Comment by ajacoutot** [comment]
@jfindlay Hi Justin. Ideally, both :-)

**Comment by jfindlay** [comment]
Great, thanks @ajacoutot.  In the future you are welcome to submit fixes directly to the oldest supported release branch, see https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

**Comment by ajacoutot** [comment]
Noted, thanks :-)

**Comment by cachedout** [comment]
Thanks for this fix, @ajacoutot

**Comment by rallytime** [comment]
@ajacoutot Thanks! I've backported your change to 2015.8. Turns out that the openbsd installation doc wasn't present on the 2015.5 branch, so I've created it in #28140 and made sure it had your changes in it.

**Comment by ajacoutot** [comment]
Awesome, thank you all :-)

**Pull request merged**
