### PR TITLE
[2018.3] Ensure salt.utils.dateutils is available for templates via salt-ssh

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Including salt.utils.dateutils so various jinja_filters are available when using salt-ssh.

### What issues does this PR fix or reference?
#46668 

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by terminalmage — APPROVED** [review]
This is a good catch. I wonder which other jinja filters may have this issue.

**Comment by rallytime** [comment]
re-run py

**Comment by rallytime** [comment]
re-run py

**Comment by lorengordon** [comment]
Ohhhh, with the utils modules getting reorganized, the decorator approach might be insufficient as is.

* [decorators](https://github.com/saltstack/salt/blob/develop/salt/utils/decorators/jinja.py)
* [jinja env updates](https://github.com/saltstack/salt/blob/develop/salt/utils/templates.py#L359-L361)

May want instead to import all the functions providing jinja filters/tests/globals in a central place, and create the mapping there...? A little less intuitive for a new dev when adding a new jinja filter/test/global, but more sustainable over time...

**Pull request merged**
