### PR TITLE
add wait_for_ip_timeout

### PR DESCRIPTION
**Pull request by steverweber**
add wait_for_ip_timeout like what is available in openstack and cleanup some code to use seconds vs minutes.

https://github.com/saltstack/salt/issues/25614

### CODE REVIEW

**Comment by steverweber** [comment]
sorry this still needs some work and testing.  please done merge yes.
thanks!

**Comment by nmadhok** [comment]
@steverweber @rallytime This needs review. Don't merge yet!

**Comment by steverweber** [comment]
@nmadhok  thoughts on using something like:
`
max_wait_vmware_tools = max_wait
if max_wait_vmware_tools > (15 * 60):
    max_wait_vmware_tools = 15 * 60
`

**Comment by steverweber** [comment]
disregard that last comment... how about:
```
max_wait_vmware_tools = max_wait
max_wait_ip = max_wait
```

**Comment by techhat** [comment]
I like this, but I'm worried about inconsistencies between drivers. IMHO, all timeouts in Salt Cloud should be in seconds, which negates the need for explicitly declaring `_minutes` in a function name. But consistency between drivers should be a priority. Once this is merged, we need to make sure to get a TODO on making any other drivers like this consistent.

**Comment by nmadhok** [comment]
@techhat Agreed. What should we use for the option name? I remember us discussing about the consistency between the cloud drivers before.

**Comment by steverweber** [comment]
I used the same option name as openstack `wait_for_ip_timeout`. 
I'm good with reverting to seconds in the logs.
Still have that last issue:

I'm happy with:
```
max_wait_vmware_tools = max_wait
max_wait_ip = max_wait
```

**Comment by steverweber** [comment]
im happy... are we good to go?

**Comment by nmadhok** [comment]
@steverweber sorry haven't had the time/chance to look at this yet. Will be looking into it this week. Thanks!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@nmadhok Let us know when you've had a chance to look at this, or if you just want us to merge it if tests pass. Thanks!

**Comment by steverweber** [comment]
@nmadhok , if you don't have time to review, I suggest you be open to trust someone else to review.

**Comment by nmadhok** [comment]
@steverweber I trust everybody in the community. There were additional fixes to the driver that were made which happen to be on the same lines as the changes you had made. 

@rallytime lets go ahead and merge all changes made by @steverweber so he doesn't have to rebase them. I'll make additional PR's if the changes break anything once I get some time to test/review.

**Comment by steverweber** [comment]
thanks!

**Comment by nmadhok** [comment]
@steverweber ``wait_for_ip_timeout`` has to be specified by the user in minutes or seconds?

**Comment by nmadhok** [comment]
@rallytime Will review this once #26144 is merged into develop.

**Comment by steverweber** [comment]
seconds. https://github.com/saltstack/salt/commit/18b376680d245b71478b57d7fe1ed28de1f2da95

**Pull request merged**
