### PR TITLE
performance improvement: stop iterating runner dunder

### PR DESCRIPTION
**Pull request by mattp-**
### What does this PR do?
seems some naive iterating of runners in salt.clients.mixin._low was
causing all runners to be loaded non-lazily. this is slow and
unneccessary, so we update globals on any already loaded mods and use
the inject_globals decorator built into LazyLoader instead. 

this is particularly annoying if runners have noisy or slow virtual funcs.

### Previous Behavior
runners loaded all runners all the time.

### New Behavior
they are loaded lazily like minion mods

### Tests written?
yes
**[NOTICE] Bug fixes or features added to Salt require tests.**
Please review the [test documentation](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html) for details on how to implement tests into Salt's test suite.

### Commits signed with GPG?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by DmitryKuzmenko — APPROVED** [review]
I'm ok here except pylint failures.

**Comment by mattp-** [comment]
@DmitryKuzmenko should be to good now 👍

**Review by marbx — COMMENTED** [review]
Hi @mattp, 
congratulations, although I do not yet understand how lazy loading works.

Here you lazyload functions.
Would it also be possible to lazyload a dictionary?

I would like to lazyload grains, which are currently set with

    self.opts['grains'] = salt.loader.grains(opts)

Thank you!

**Review by s0undt3ch — APPROVED** [review]

**Comment by markuskramerIgitt** [comment]
Oh good.

**Comment by sagetherage** [comment]
@mattp- can you rebase this against master or perhaps there is another PR to reference, here?

**Comment by sagetherage** [comment]
Closing as per author

**Pull request closed without merging**
