### PR TITLE
Fixes for masterless winrepo

### LINKED ISSUE #26743: 2015.8.0rc4_TheBigBear git rel. 'gcb9fddd' global name 'PER_REMOTE_PARAMS' is not defined
This might all be based on the issue behind #26739 or probably #26740 

but ```salt-call --local winrepo.update_git_repos``` comes up with a key error, which I guess means it didn't get set, which is probably as it says because ```__opts__``` are missing

So I won't create any more issues now. ;-)

```
C:\salt-dev\salt>salt-call  --local winrepo.update_git_repos
[ERROR   ] Failed to import log_handlers sentry_mod, this is due most likely to
a syntax error:
Traceback (most recent call last):
  File "c:\salt-dev\salt\salt\loader.py", line 1105, in _load_module
    ), fn_, fpath, desc)
  File "c:\salt-dev\salt\salt\log\handlers\sentry_mod.py", line 96, in <module>
    __grains__ = salt.loader.grains(__opts__)
NameError: name '__opts__' is not defined
[ERROR   ] An un-handled exception was caught by salt's global exception handler
:
KeyError: 'winrepo_remotes_ng'
Traceback (most recent call last):
  File "c:\python27\scripts\salt-call-script.py", line 9, in <module>
    load_entry_point('salt===2015.8.0rc3-114-g2f9b40c', 'console_scripts', 'salt
-call')()
  File "c:\salt-dev\salt\salt\scripts.py", line 331, in salt_call
    client.run()
  File "c:\salt-dev\salt\salt\cli\call.py", line 50, in run
    caller.run()
  File "c:\salt-dev\salt\salt\cli\caller.py", line 133, in run
    ret = self.call()
  File "c:\salt-dev\salt\salt\cli\caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "c:\salt-dev\salt\salt\modules\win_repo.py", line 101, in update_git_repo
s
    return _update_git_repos(opts=__opts__, masterless=True)
  File "c:\salt-dev\salt\salt\runners\winrepo.py", line 177, in update_git_repos

    (opts['winrepo_remotes_ng'], opts['winrepo_dir_ng'])]
KeyError: 'winrepo_remotes_ng'
Traceback (most recent call last):
  File "c:\python27\scripts\salt-call-script.py", line 9, in <module>
    load_entry_point('salt===2015.8.0rc3-114-g2f9b40c', 'console_scripts', 'salt
-call')()
  File "c:\salt-dev\salt\salt\scripts.py", line 331, in salt_call
    client.run()
  File "c:\salt-dev\salt\salt\cli\call.py", line 50, in run
    caller.run()
  File "c:\salt-dev\salt\salt\cli\caller.py", line 133, in run
    ret = self.call()
  File "c:\salt-dev\salt\salt\cli\caller.py", line 196, in call
    ret['return'] = func(*args, **kwargs)
  File "c:\salt-dev\salt\salt\modules\win_repo.py", line 101, in update_git_repo
s
    return _update_git_repos(opts=__opts__, masterless=True)
  File "c:\salt-dev\salt\salt\runners\winrepo.py", line 177, in update_git_repos

    (opts['winrepo_remotes_ng'], opts['winrepo_dir_ng'])]
KeyError: 'winrepo_remotes_ng'
```

### PR DESCRIPTION
**Pull request by terminalmage**
rev can no longer be None, it defaults to HEAD

Also fixes #26743

### CODE REVIEW

**Comment by terminalmage** [comment]
Looks like I need to add another commit to fix https://github.com/saltstack/salt/issues/26743#issuecomment-135849971, don't merge yet.

**Comment by terminalmage** [comment]
OK, added.

**Comment by jfindlay** [comment]
@terminalmage, there is one [lint error](https://jenkins.saltstack.com/job/salt-pr-lint-n/8892/violations/file/salt/modules/win_repo.py/).

**Comment by terminalmage** [comment]
Should be fixed with the latest push.

**Comment by TheBigBear** [comment]
@terminalmage I have merged your patch here locally, but I am not much further ;-( now I get 

Any ideas what I need to do next?

```
C:\salt-dev\salt>salt-call  --local winrepo.update_git_repos
[ERROR   ] Failed to update winrepo_remotes: 'winrepo_user'
local:
    Failed to update winrepo_remotes: 'winrepo_user'
```

**Comment by terminalmage** [comment]
You shouldn't be seeing any of this using git.latest, are you testing with gitpython or something?

**Comment by terminalmage** [comment]
@TheBigBear It looks like that is what you were doing, so I added another commit to  add default values for the options required for gitpython/pygit2.

**Comment by TheBigBear** [comment]
@terminalmage yes, I am using pygit2 but @UtahDave 's winrepo fixes https://github.com/saltstack/salt/pull/26720 also merged in the following:
```
https://github.com/UtahDave/salt/blob/2ceed47ecee423f9b848966421321ce7dc361180/salt/runners/winrepo.py#L187-L190
```

So that is only true on non windows, then? And If I didn't have pygit2 installed my code woudl not go into this part, right? Sorry, but at least we now have defaults for those that do have pygit2 or gitpython libs on windows. ;-)

**Comment by terminalmage** [comment]
Yes this is definitely necessary if we're going to allow masterless winrepo to use pygit2/gitpython, so that's a good catch.

**Comment by TheBigBear** [comment]
@terminalmage 

so if I remofe pygit2 and use git.latest I still get this:

```
C:\salt-dev\salt>salt-call --local winrepo.update_git_repos
[INFO    ] Loading fresh modules for state activity
[INFO    ] Running state [https://github.com/saltstack/salt-winrepo.git] at time 22:07:34.113000
[INFO    ] Executing state git.latest for https://github.com/saltstack/salt-winrepo.git
[INFO    ] Checking remote revision for https://github.com/saltstack/salt-winrepo.git
[INFO    ] Executing command ['git', 'ls-remote', 'https://github.com/saltstack/salt-winrepo.git'] in directory 'C:\\Users\\sysadmin.uk'
[ERROR   ] No revision matching 'None' exists in the remote repository
[INFO    ] Completed state [https://github.com/saltstack/salt-winrepo.git] at time 22:07:35.053000
[INFO    ] Loading fresh modules for state activity
[INFO    ] Running state [https://github.com/saltstack/salt-winrepo-ng.git] at time 22:07:35.112000
[INFO    ] Executing state git.latest for https://github.com/saltstack/salt-winrepo-ng.git
[INFO    ] Checking remote revision for https://github.com/saltstack/salt-winrepo-ng.git
[INFO    ] Executing command ['git', 'ls-remote', 'https://github.com/saltstack/salt-winrepo-ng.git'] in directory 'C:\\Users\\sysadmin.uk'
[ERROR   ] No revision matching 'None' exists in the remote repository
[INFO    ] Completed state [https://github.com/saltstack/salt-winrepo-ng.git] at time 22:07:35.841000
local:
    ----------
    https://github.com/saltstack/salt-winrepo-ng.git:
        False
    https://github.com/saltstack/salt-winrepo.git:
        False
```

Is this going to fixed in your earlier fix as well?

**Comment by terminalmage** [comment]
@TheBigBear Yes, that is fixed by the very first commit in this PR, https://github.com/terminalmage/salt/commit/d165c9cb315c133d7a56c15b9be7c0bd06738bf3

**Comment by terminalmage** [comment]
Actually, it's a mix of that commit and this one: https://github.com/terminalmage/salt/commit/791c2dac94af323b39175f8535e12ebbbee82581

**Comment by TheBigBear** [comment]
OK, I'll take a break from testing and wait fro this to be 'merged' first..

**Pull request merged**
