### PR TITLE
states.smartos.config_present, fixed bug where spaces broke the smartos config parser

### PR DESCRIPTION
**Pull request by sjorge**
some minor fix if the value has a space in it, it no longer breaks the config parser!

### CODE REVIEW

**Comment by sjorge** [comment]
Tests look OK.

**Comment by cachedout** [comment]
Thank you, @sjorge

**Comment by sjorge** [comment]
@cachedout this one should also be backported to 2016.3 sorry about this. I didn't see the 2016.3 branch appear. This is still broken in 2016.3.

**Comment by sjorge** [comment]
Alright looks like it made it to both develop and 2016.3 :+1:

**Pull request merged**
