### PR TITLE
[master] Porting #44499 to master

### PR DESCRIPTION
**Pull request by garethgreenaway**
Porting #44499 to master

### CODE REVIEW

**Comment by dwoz** [comment]
Test failures are legit.

**Comment by msummers42** [comment]
This should fix it
```
diff --git a/salt/_extensions/roster/dir.py b/salt/_extensions/roster/dir.py
index 2702c517b..8db4f4cbe 100644
--- a/salt/roster/dir.py
+++ b/salt/roster/dir.py
@@ -15,7 +15,7 @@ import salt.loader
 import salt.config
 from salt.template import compile_template
 
-from salt.roster.flat import HAS_RANGE, _convert_range_to_list
+from salt.utils.roster_matcher import HAS_RANGE, _convert_range_to_list
 
 # Import Salt libs
```

**Comment by msummers42** [comment]
@garethgreenaway is there anything I can do to get this merged into master? It's a fairly simply fix that needs to be applied that I included in a comment above, as far as I can tell. Please let me know! Thanks :-)

**Comment by garethgreenaway** [comment]
@msummers42 Apologies for the delay in responding.  I'm looking at your comment above and I don't see the line you're removing in the existing file and also don't see those functions being used.  Maybe I'm missing something?

**Comment by msummers42** [comment]
This looks positive
```
<testcase classname="tests.unit.roster.test_dir.DirRosterTestCase" name="test_badfile" time="0.045" />
<testcase classname="tests.unit.roster.test_dir.DirRosterTestCase" name="test_badfile_logging" time="0.044" />
<testcase classname="tests.unit.roster.test_dir.DirRosterTestCase" name="test_basic_glob" time="0.041" />
<testcase classname="tests.unit.roster.test_dir.DirRosterTestCase" name="test_basic_list" time="0.041" />
<testcase classname="tests.unit.roster.test_dir.DirRosterTestCase" name="test_basic_re" time="0.040" />
<testcase classname="tests.unit.roster.test_dir.DirRosterTestCase" name="test_empty" time="0.037" />
<testcase classname="tests.unit.roster.test_dir.DirRosterTestCase" name="test_nomatch" time="0.030" />
<testcase classname="tests.unit.roster.test_dir.DirRosterTestCase" name="test_roster_domain" time="0.039" />
```
From https://jenkins.saltproject.io/job/pr-debian-10-amd64-py3-pytest/job/PR-54619/2/artifact/artifacts/xml-unittests-output/test-results-20210611153204.664.xml/*view*/

**Comment by garethgreenaway** [comment]
@msummers42 All good :) Just making sure I wasn't missing something obvious.  If you have changes from your version that you want to see incorporated.  The one failing tests is because this PR was based on an earlier version of Salt before a version change.  I'm opening a new PR with the changes based on the master branch.

**Comment by garethgreenaway** [comment]
Closing in favor of https://github.com/saltstack/salt/pull/60364

**Pull request closed without merging**
