### PR TITLE
Fix regression in masterless pillar generation

### LINKED ISSUE #19540: regression from 2014.7 to git/2014.7 branch: masterless salt-call, pillar jinja rendering can not import/load files from pillar
* affected: github 2014.7 branch
   *  salt-call 2014.7.0-1213-gfd174db (Helium)
   *  salt-call 2014.7.0-1149-g615921b (Helium)
 * not affected: 2014.7 release
   * salt-call 2014.7.0 (Helium)
 * use case:
   * as a devop i want to import some common data into pillar files for reusing them in other pillar files
 * reproduction:
   * change to a new/empty directory
   * paste attached file into directory
   * chmod +x setup_issue.sh
   * ./setup_issue.sh
   * ./sc.sh pillar.items -l debug

---
setup_issue.sh
```
#!/bin/sh
#
myprog=`readlink -f $0`
mydir=`dirname $myprog`
myesc=`echo "$mydir" | sed -re 's/\\//\\\\\\//g'`

sed -re "s/\\+BASE\\+/$myesc/g" > $mydir/minion <<EOF

root_dir: +BASE+/_run

pidfile: salt-minion.pid
pki_dir: pki
cachedir: cache
sock_dir: run

file_client: local

fileserver_backend:
  - roots

pillar_roots:
  base:
    - +BASE+/pillar

file_roots:
  base:
    - +BASE+/salt

EOF

echo "id: pillar_test" >> $mydir/minion

cat > $mydir/sc.sh <<"EOF"
#!/bin/sh
myprog=`readlink -f $0`
mydir=`dirname $myprog`
sudo salt-call --local --config-dir=$mydir $@
EOF

chmod +x $mydir/sc.sh
mkdir $mydir/salt
mkdir $mydir/pillar

cat > $mydir/salt/top.sls <<EOF
base:
  '*':
    - test_state

EOF

cat > $mydir/salt/test_state.sls <<EOF
curl:
  pkg:
    - installed

EOF

cat > $mydir/pillar/top.sls <<EOF
base:
  '*':
    - included_pillar

EOF

cat > $mydir/pillar/included_pillar.sls <<"EOF"

{% import_yaml "loaded_yaml.sls" as t with context %}

test:
  me: true
{%- for a,d in t.iteritems() %}
  {{ a }}: {{ d }}
{%- endfor %}

EOF

cat > $mydir/pillar/loaded_yaml.sls <<EOF

another_me: true

EOF

```

### PR DESCRIPTION
**Pull request by terminalmage**
Fixes #19540.

### CODE REVIEW

**Comment by davidjb** [comment]
Fixes #19546 as well, essentially a duplicate of #19540.

**Comment by terminalmage** [comment]
@davidjb did you test this pull req on your issue? I saw it yesterday and thought it might have been a slightly different issue, but I didn't look too closely into it. Just want to make sure we're not assuming this was fixed when there is still work to do.

**Comment by davidjb** [comment]
@terminalmage Yes, tested and does fix my issue. They're the same underlying cause.

**Comment by terminalmage** [comment]
@davidjb awesome, thanks for confirming! I didn't get a good enough look at it yesterday to be able to tell if it was indeed the same issue.

**Comment by terminalmage** [comment]
Also, even though this has already been merged, I've renamed the title of the pull request as it didn't really involve caching. The reason for the regression was as follows:

1. Originally, the jinja search path only looked in the local files (``file_roots`` or ``pillar_roots``).
2. Support for using other fileserver backends was added to masterless salt for 2014.7.0.
3. This caused the jinja search path to fail for files that came from gitfs and other fileserver backends, since salt was still looking in ``file_roots``.
4. I changed the jinja cache loader to look in the minion file cache (where files from ``file_roots``, gitfs, etc. are cached locally on the minion), to enable gitfs files to be able to be found by jinja.
5. This fix caused the pillar regression, as for the purposes of pillar compilation ``file_roots`` is essentially ``pillar_roots``. Jinja was looking in the place where files from the salt fileserver are normally cached, not in ``pillar_roots`` where it should have been.
6. This pull request was opened to tell jinja to look in the local ``pillar_roots`` when compiling pillar data.

Thanks to those that reported, this regression will not make it into an official Salt release. We really appreciate it!

**Comment by davidjb** [comment]
@terminalmage thanks for fixing it and the detailed  explanation!

**Comment by khrisrichardson** [comment]
@terminalmage this appears to have caused a regression to the behavior reported in #17963

It appears that self.opts.get('__pillar') is True even in a state that does not interact with pillar.

```
# salt-call state.sls python-pip
[INFO    ] pygit2 gitfs_provider enabled
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** u'python-pip/init.sls'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'python-pip/map.jinja'
[CRITICAL] Rendering SLS 'base:python-pip' failed: Jinja error: python-pip/map.jinja
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 280, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 3, in top-level template code
  File "/usr/lib/python2.7/dist-packages/salt/utils/jinja.py", line 132, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: python-pip/map.jinja

; line 3

---
# vi: set ft=yaml.jinja :

{% from 'python-pip/map.jinja' import map with context %}    <======================

python-pip:
  pkg.installed:
    - name:     {{ map.get('pkg', {}).get('name') }}

[...]
---
local:
    Data failed to compile:
----------
    Rendering SLS 'base:python-pip' failed: Jinja error: python-pip/map.jinja
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 280, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 3, in top-level template code
  File "/usr/lib/python2.7/dist-packages/salt/utils/jinja.py", line 132, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: python-pip/map.jinja

; line 3

---
# vi: set ft=yaml.jinja :

{% from 'python-pip/map.jinja' import map with context %}    <======================

python-pip:
  pkg.installed:
    - name:     {{ map.get('pkg', {}).get('name') }}

[...]
---
```

```
# salt-call --versions-report
           Salt: 2014.7.1-133-gfd8e474
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

**Comment by terminalmage** [comment]
Thanks for the heads-up, I'll take a look.

**Comment by terminalmage** [comment]
@khrisrichardson Can you test the one-line change I made in https://github.com/saltstack/salt/pull/20000?

**Comment by khrisrichardson** [comment]
@terminalmage unfortunately I get the same traceback with pop instead of get.

**Comment by terminalmage** [comment]
OK, thanks for the info.

**Comment by terminalmage** [comment]
@khrisrichardson I'm tracking this in a new issue, on which I've CC'ed you: https://github.com/saltstack/salt/issues/20004

**Pull request merged**
