### PR TITLE
Port 54636

### PR DESCRIPTION
**Pull request by whytewolf**
### What does this PR do?

PR to merge #54636 to master

### Tests written?
Tests already in merge

### Commits signed with GPG?

No

### CODE REVIEW

**Review by dwoz — DISMISSED** [review]
@whytewolf There are booth linter and test failures that need to be addressed

**Comment by whytewolf** [comment]
ok, I fixed the lint issue/test issue that was wrong with the test file this actually touched. The new lint errors look to be in files that were not touched by this set of commits. Were these taken care of in a different PR? and updating the branch should fix them?

**Comment by dwoz** [comment]
@whytewolf Linter still complaining ;)

**Comment by whytewolf** [comment]
@dwoz looks like lint is passing now. I don't know about those added failures though. some other thing that was fixed/broken in the test suites elsewhere?

**Review by DmitryKuzmenko — DISMISSED** [review]

**Review by DmitryKuzmenko — APPROVED** [review]

**Pull request merged**
