### PR TITLE
Summary: Add two neutron api about listing and showing firewall.

### PR DESCRIPTION
**Pull request by MIBc**
Description:
Add function list_firewalls and show_firewall in salt/modules/neutron.py
Add object function list_firewalls, show_firewall and _fetch_firewall in
salt/utils/openstack/neutron.py

### CODE REVIEW

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@MIBc This has some lint errors. Could you please take a second look?

**Comment by MIBc** [comment]
@cachedout  I'll check it as soon as possible.

**Comment by cachedout** [comment]
Looks good! THanks, @MIBc

**Pull request merged**
