### PR TITLE
Ensure that terminating null-bytes are being removed from registry values fetched from salt.utils.win_reg.

### PR DESCRIPTION
**Pull request by arizvisa**
### What does this PR do?
Please see the original issue at #51940. I'm really getting tired of creating PRs and filling out forms as I just really want things to work. So, merge this if you want.

### What issues does this PR fix or reference?
This closes issue #51940.

### Previous Behavior
When fetching a REG_SZ value from the registry, terminating null-bytes may be returned. Some calls assume that a correct string is returned such as when dealing with the timezone when a  minion initializes. Since null bytes are returned, these calls can fail as described in the initial report).

### New Behavior
This removes terminating null-bytes. This may not be what the caller intends as Null-bytes are considered part of the registry value, however there are numerous places in salt that assume that values read from the registry are assumed to contain no null bytes and therefore this is the quickest and easiest fix rather than going through all of them and fixing that code.

### Tests written?
No

### Commits signed with GPG?
No

### CODE REVIEW

**Review by twangboy — APPROVED** [review]

**Comment by twangboy** [comment]
We're going to revert #51941 and check the return from `reg.read_value` at the call in each module. There may be instances where we want to know if there's a trailing Null Byte.

**Comment by arizvisa** [comment]
Okay, cool. Yeah, I was thinking that as well as removing the null-bytes changes the semantics despite most of salt assuming that it returns a well-formed string.

Maybe something like a `reg.read_string` might be more clear perhaps.

**Comment by arizvisa** [comment]
Can you let me know what the PR for that is whenever you guys start working on it? (Either here, or in the related issue)

**Comment by twangboy** [comment]
Hey, here's the PR
https://github.com/saltstack/salt/pull/52013

**Comment by twangboy** [comment]
We need to check the return from the registry when we're calling it. I think it only needs to be done if we're querying REG_SZ and possibly REG_MULTI_SZ.

This no longer applies to the `timezone` issue you fixed this for as you changed it to use the command line tool `tzutil` instead of querying the registry.

**Comment by arizvisa** [comment]
Awesome. Thanks.

**Comment by Ch3LL** [comment]
@twangboy did you still want this backported, seems its getting reverted if i'm reading this correctly?

**Comment by twangboy** [comment]
@ch3ll No, do not back port this... it is being reverted

**Pull request merged**
