### PR TITLE
Merge 2015.8 forward to develop

### PR DESCRIPTION
**Pull request by s0undt3ch**
Closes https://github.com/saltstack/salt/pull/26919

### CODE REVIEW

**Comment by s0undt3ch** [comment]
The 6 failed tests in Cent7 are also happening in the develop tests.
Re-running tests because on Ubuntu there's more failed tests than on the develop tests.

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
@s0undt3ch, I've been seeing those failures on other develop ubuntu tests (sometimes more, sometimes less).  It makes me think that jenkins isn't cleaning up the workspace before running new pull request tests.

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Switched the PR Ubuntu to Linode and both Cent and Ubuntu show the exact same failures. Ubuntu from RS is have memory issue(why would we be leaking on the VM from RS and not Linode? Weird...)

Merging.

**Comment by jfindlay** [comment]
@s0undt3ch, it could be due to this: http://www.rackspace.com/knowledge_center/article/choosing-a-virtualization-mode-pv-versus-pvhvm.

**Comment by s0undt3ch** [comment]
Could be...

**Pull request merged**
