### PR TITLE
[3006.x] Add support for Debian 12

### PR DESCRIPTION
**Pull request by ScriptAutomate**
### What does this PR do?

Adds Debian 12 to Salt test suite and package publishing

### What issues does this PR fix or reference?

Fixes: #64223

### CODE REVIEW

**Review by s0undt3ch — DISMISSED** [review]

**Comment by ScriptAutomate** [comment]
Issues for Debian 12:

## cron.service does not exist

> Error running 'service.enable': Failed to enable unit: Unit file cron.service does not exist.

I'm going to troubleshoot this and see if we need to get `cron` installed on the AMIs, or if the test logic needs to change in regards to Debian 12.

```
            =========================== short test summary info ============================
           FAILED tests/pytests/integration/ssh/test_master.py::test_service - assert 20 == 0
            +  where 20 = ProcessResult(returncode=20, stdout='{\n"localhost": {\n"stdout": "",\n"stderr": "Error running \'service.enable\': Failed to enable unit: Unit file cron.service does not exist.",\n"retcode": 1\n}\n}\n', stderr='', cmdline=['/tmp/testing/.nox/ci-test-onedir/bin/python', '/tmp/stsuite/scripts/cli_salt_ssh.py', '--ignore-host-keys', '--roster-file=/tmp/stsuite/master-0QAlf2/conf/roster', '--priv=/tmp/stsuite/sshd/client_key', '--user=root', '--config-dir=/tmp/stsuite/master-0QAlf2/conf', '--out=json', '--out-indent=0', '--log-level=critical', 'localhost', 'service.enable', 'cron'], data_key=None, data={'stdout': '', 'stderr': "Error running 'service.enable': Failed to enable unit: Unit file cron.service does not exist.", 'retcode': 1}).returncode
```

## Failing to install nano

@s0undt3ch Can't tell if this is a problem with `salt`, or with the AMI.

```
           FAILED tests/pytests/functional/modules/test_pkg.py::test_pkg_install_port - salt.exceptions.SaltInvocationError: Path mirror+file:/etc/apt/mirrors/debian.list/pool/main/n/nano/nano_7.2-1_amd64.deb for package nano is either not absolute or an invalid protocol
```

https://github.com/saltstack/salt/blob/5d86ead778983fd87e074a2093abe002e244aab8/tests/pytests/functional/modules/test_pkg.py#L541-L563

## Failing to use pkgrepo for expected Debian 12 salt repo location

@s0undt3ch Am I understanding this output below correctly? Seems like a chicken/egg problem. Am I supposed to change my PR to make up for this, and to add it in sometime after a release makes these?

```
           FAILED tests/pytests/functional/states/pkgrepo/test_debian.py::test_adding_repo_file_signedby[With(aptsources.sourceslist)] - AssertionError: assert '' == 'deb [arch=amd64 signed-by=/usr/share/keyrings/salt-archive-keyring.gpg] https://repo.saltproject.io/py3/debian/12/amd64/latest bookworm main'
             - deb [arch=amd64 signed-by=/usr/share/keyrings/salt-archive-keyring.gpg] https://repo.saltproject.io/py3/debian/12/amd64/latest bookworm main
           FAILED tests/pytests/functional/states/pkgrepo/test_debian.py::test_adding_repo_file_keyserver_key_url[With(aptsources.sourceslist)] - AssertionError: assert '' == 'deb [arch=amd64] https://repo.saltproject.io/py3/debian/12/amd64/latest bookworm main'
             - deb [arch=amd64] https://repo.saltproject.io/py3/debian/12/amd64/latest bookworm main
           FAILED tests/pytests/functional/states/pkgrepo/test_debian.py::test_adding_repo_file_signedby_alt_file[With(aptsources.sourceslist)] - AssertionError: assert '' == 'deb [arch=amd64 signed-by=/usr/share/keyrings/salt-archive-keyring.gpg] https://repo.saltproject.io/py3/debian/12/amd64/latest bookworm main'
             - deb [arch=amd64 signed-by=/usr/share/keyrings/salt-archive-keyring.gpg] https://repo.saltproject.io/py3/debian/12/amd64/latest bookworm main
           FAILED tests/pytests/functional/states/pkgrepo/test_debian.py::test_adding_repo_file_signedby[Without(aptsources.sourceslist)] - AssertionError: assert '' == 'deb [arch=amd64 signed-by=/usr/share/keyrings/salt-archive-keyring.gpg] https://repo.saltproject.io/py3/debian/12/amd64/latest bookworm main'
             - deb [arch=amd64 signed-by=/usr/share/keyrings/salt-archive-keyring.gpg] https://repo.saltproject.io/py3/debian/12/amd64/latest bookworm main
           FAILED tests/pytests/functional/states/pkgrepo/test_debian.py::test_adding_repo_file_keyserver_key_url[Without(aptsources.sourceslist)] - AssertionError: assert '' == 'deb [arch=amd64] https://repo.saltproject.io/py3/debian/12/amd64/latest bookworm main'
             - deb [arch=amd64] https://repo.saltproject.io/py3/debian/12/amd64/latest bookworm main
           FAILED tests/pytests/functional/states/pkgrepo/test_debian.py::test_adding_repo_file_signedby_alt_file[Without(aptsources.sourceslist)] - AssertionError: assert '' == 'deb [arch=amd64 signed-by=/usr/share/keyrings/salt-archive-keyring.gpg] https://repo.saltproject.io/py3/debian/12/amd64/latest bookworm main'
             - deb [arch=amd64 signed-by=/usr/share/keyrings/salt-archive-keyring.gpg] https://repo.saltproject.io/py3/debian/12/amd64/latest bookworm main
```

**Review by dmurphy18 — DISMISSED** [review]

**Comment by s0undt3ch** [comment]
## Failing to install nano

Try to do the same commands on the VM(what salt does), if it succeeds, then the problem is likely Salt and something that changed on Debian 12

## Failing to use pkgrepo for expected Debian 12 salt repo location

Skip the tests depending on the salt version(since the repo doesn't yet exist)

**Review by s0undt3ch — DISMISSED** [review]

**Review by twangboy — DISMISSED** [review]

**Review by dmurphy18 — DISMISSED** [review]

**Review by dmurphy18 — APPROVED** [review]
So reviewed this this morning, and major additions - feel like - hit me up when it is done.
This is supposed to be adding Debian 12, so add Debian 12, and use another PR for refactoring how things are built.  That way, adding a new platform is a simple C & P from the last for whoever has to add a platform later.

Lastly, these files have way too much 
```
      nox-version: 2022.8.7
      python-version: "3.10"
```
use of magic numbers. When the change from to a different version for nox or python, invariably one entry will be missed.  This has been bad practice for decades, and should be fixed with global, or variable at head of file.  Understand inherited this, but that is a problem waiting to happen.

**Comment by s0undt3ch** [comment]
> So reviewed this this morning, and major additions - feel like - hit me up when it is done. This is supposed to be adding Debian 12, so add Debian 12, and use another PR for refactoring how things are built. That way, adding a new platform is a simple C & P from the last for whoever has to add a platform later.

So, how do you know the OS you added passes tests, or build packages, etc, if you don't do the necessary changes to run tests through it on the PR adding it?


> 
> Lastly, these files have way too much
> 
> ```
>       nox-version: 2022.8.7
>       python-version: "3.10"
> ```
> 
> use of magic numbers. When the change from to a different version for nox or python, invariably one entry will be missed. This has been bad practice for decades, and should be fixed with global, or variable at head of file. Understand inherited this, but that is a problem waiting to happen.

This is not a problem as the variables you're referring to, although it doesn't look like it, is using "magic numbers", ie, the values are templatized and when we need to Change them, we change them in one single place.

**Review by s0undt3ch — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
