### PR TITLE
Don't return False when target exists (file.rename)

### PR DESCRIPTION
**Pull request by MTecknology**
### What does this PR do?

This PR applies the change recommended by @DickerDackel in #49748.

### Previous Behavior

When using file.rename and then creating a new file in it's place, subsequent executions will fail due to a file existing in it's place.

### New Behavior

This patch removes the ``False`` return when a destination file exists if ``-force:False``.

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by rallytime** [comment]
@MTecknology Thanks for submitting this! There's a test failing here: https://jenkinsci.saltstack.com/job/pr-kitchen-ubuntu1604-py2/job/PR-49843/1/

Can you take a look?

**Review by terminalmage — APPROVED** [review]
This looks good and the failing test just needs to be updated to reflect the new return value.

**Comment by damon-atkins** [comment]
Please doco the change in behavior in doc/topics/releases/neon.rst

On a side note, not an issue with this PR.   However file.copy() has been change to file.copy_() in develop branch?

**Comment by terminalmage** [comment]
You can ignore that, @MTecknology, there is no need to document a bugfix in the release notes.

**Comment by terminalmage** [comment]
We run a changelog script that adds sort of stuff for us.

**Comment by terminalmage** [comment]
Ahh, after reading the original issue it's clear that this was not 100% bugfix, so I'll get the change documented.

**Comment by MTecknology** [comment]
@terminalmage Thanks!

**Pull request merged**
