### PR TITLE
Added KMS and other features and more system flexibility

### PR DESCRIPTION
**Pull request by jeffclay**
### What does this PR do?
Adds functions for more windows license management tasks and removes hard coded file paths.

### New Behavior
Added feature to manually set a KMS host server.
Added feature to manually set the KMS product key based on the OS version.
Added feature to remove product key from registry.
Added feature to rearm the existing license.
Added feature to report the type of license currently installed.
Changed all hard paths to slmgr.vbs to use the systemroot environment variable to allow the code to be more accepting of all types of installations.

### Tests written?
Was tested for Windows 7 Pro, Windows 7 Enterprise, Windows 10 Enterprise and Windows 10 Pro. Those are the only salted systems in my environment.

### CODE REVIEW

**Review by cachedout — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Comment by cachedout** [comment]
@jeffclay These changes look good but we will need the unit tests adjusted before we can get this in since this PR causes them to fail. Looks like the failures are happening in `unit.modules.win_license_test.LicenseTestCase.test_info`. Let us know if you need help doing so. After that's fixed up, we can get this merged. Thanks!

**Comment by cachedout** [comment]
@jeffclay Did you see my comment above on the failing tests? We can't get this merged until they are fixed. Please let me know if I can help. Thanks.

**Comment by cachedout** [comment]
@jeffclay Please let me know if you'll be able to come back to this. If I don't hear from you, I'll have to close this without merging it. Thanks.

**Comment by cachedout** [comment]
I have not heard back from you on this and I am closing it as a result. When you're ready to come back to this one and can have a look at the tests, when things are passing then we can get this merged. Thanks, @jeffclay

**Pull request closed without merging**
