### PR TITLE
Added installArgs/overrideArgs to chocolatey

### PR DESCRIPTION
**Pull request by opdude**
Added the ability to give choco install args and allow for overriding the original arguments in a packages

### CODE REVIEW

**Comment by jfindlay** [comment]
Thanks, @opdude.  Do you think that these additional options could also be added to other chocolatey functions?

**Comment by jfindlay** [comment]
@UtahDave

**Comment by opdude** [comment]
@jfindlay Yes, will add these to upgrade and uninstall :). Not sure if the install cygwin, ruby, webpi, python allow for these options

**Comment by UtahDave** [comment]
Thanks, @opdude!   Hey, when you get a chance, would you mind adding a CLI example that uses these new args?  Thanks!

**Comment by jfindlay** [comment]
It appears that @UtahDave has merged a commit that contains the changes in this pull request.  I'm not sure that happened without closing this PR.  Usually github will automagically do that.  Do I need to close this pull request?

**Pull request merged**
