### PR TITLE
Update sdb/yaml.py

### PR DESCRIPTION
**Pull request by Kassec**
What issues does this PR fix or reference?
Solve issue #47473

Tests written?
No

Commits signed with GPG?
No

### CODE REVIEW

**Review by gtmanfred — APPROVED** [review]

**Comment by cachedout** [comment]
@Kassec This failed a test: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/22572/testReport/junit/unit.sdb.test_yaml/TestYamlRenderer/test_nested/

**Review by gtmanfred — CHANGES_REQUESTED** [review]
Thank goodness for tests.

@Kassec if you wouldn't mind changing this to be configurable in the sdb definition, and just allow specifying the separator, I think that will be easier than deprecating the `:`

**Comment by rallytime** [comment]
Hi @Kassec - Did you see the comments above? Were you able to come back to this?

**Comment by Kassec** [comment]
Hello,
Sorry for the delay, I've been away from this :(
I just need to understand. This patch sticks to the doc specifing sdb URIs use '/':
https://docs.saltstack.com/en/latest/topics/sdb/#sdb-uris

**Comment by gtmanfred** [comment]
Yes, but we need to make sure not to break the ways that other people have been using this one.

Also, the tests were failing.

Would you like us to reopen this PR?

**Pull request closed without merging**
