### PR TITLE
[RFC] add rfc for loader changes in Fluorine

### PR DESCRIPTION
**Pull request by gtmanfred**
### What does this PR do?
RFC for loader changes to include package information

### Commits signed with GPG?

Yes

@cachedout @terminalmage

### CODE REVIEW

**Review by rallytime — APPROVED** [review]
I like this idea.

**Comment by cachedout** [comment]
This is good but IMHO it needs more information about the transition from a single Python module, which is abstracted in the salt dunder as `module.func` to a set of modules that can exist in a Python package, all files in which should be _combined_ to do the same.

For example, would a function defined in `my_salt_module/__init__.py` always take precedence over a function named the same in `my_salt_module/foo.py`?

**Comment by gtmanfred** [comment]
I was not aware that that is what we were discussing.

Are you talking about taking all the functions from a python package, and putting them all under one module namespace of <packagename>.<functionname>?

Because what I was proposing that we do instead is add an extra layer to that abstraction, so that we could do <packagename>:<modulename>.<functionname>, so for your example, nothing could be put in __init__.py, but the rest of the modules in the same module package do not overwrite each other at all, and if you had another package that had the same module/function name combination, you could explicitly reach one by prefixing the package name, or setting the priority higher.

**Review by terminalmage — COMMENTED** [review]
How would we establish the priority, and what would stop a user from setting a priority of 1 to their own modules? Or do we not care (i.e. "give them enough rope to hang themselves")?

**Comment by gtmanfred** [comment]
@terminalmage after talking to mike, I am working on rewriting this rfc.  Some of the priority stuff is going to be split into a different rfc, which will be all the priority and seperate pip packages stuff.

**Pull request closed without merging**
