### PR TITLE
Allow cross calling of state modules

### PR DESCRIPTION
**Pull request by jacksontj**
Issue: #21214

### CODE REVIEW

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by thusoy** [comment]
Thanks for working on this! This fails on my machines:
```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1585, in call
    **cdata['kwargs'])
  File "/var/cache/salt/minion/extmods/states/init_script.py", line 30, in managed
    file_ret = file_managed(**args)
  File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1371, in managed
    accum_data, _ = _load_accumulators()
  File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 288, in _load_accumulators
    loaded = _deserialize(_get_accumulator_filepath())
  File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 273, in _get_accumulator_filepath
    __instance_id__)
NameError: global name '__instance_id__' is not defined
```

`__instance_id__` is present in the state calling `__states__['file.managed']`, but is not present in  file.managed is called. All the other dunder's are there, but not instance_id.

**Comment by cachedout** [comment]
@jacksontj Just  pinging you to ensure you saw the comment above. Thanks!

**Comment by jacksontj** [comment]
@cachedout thanks :) We are actually having a bit more discussion back in the issue :) The use cases presented there don't seem to necessitate this feature, so we might not do it... still chatting :)

**Comment by cachedout** [comment]
@jacksontj Ah! DIdn't realize. Thanks for the update.

**Comment by jacksontj** [comment]
No worries, I *just* replied on the discussion issue :)

**Pull request closed without merging**
