### PR TITLE
Uses ConfigParser to read yum config files

### LINKED ISSUE #42041: pkg.list_repo_pkgs fails to find pkgs with spaces around yum repo enabled value
### Description of Issue/Question

`pkg.list_repo_pkgs` fails to find pkgs if the "enabled" line in the yum repo definition contains spaces around the value. i.e.:

works: `enabled=1`
fails: `enabled = 1`

The problem is in the parser used by `pkg.list_repos`:

- https://github.com/saltstack/salt/blob/2016.11/salt/modules/yumpkg.py#L2539-L2540

### Setup

Modify a .repo file in /etc/yum.repos.d and change an enabled repo from `enabled=1` to `enabled = 1`.

### Steps to Reproduce Issue

Run `salt-call --local pkg.list_repo_pkgs <pkg-in-modified-repo>`.

### Versions Report
```
Salt Version:
           Salt: 2016.11.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
        machine: x86_64
        release: 3.10.0-514.21.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

### PR DESCRIPTION
**Pull request by lorengordon**
### What does this PR do?

Replaces #42045

### What issues does this PR fix or reference?

Fixes #42041

### Tests written?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by lorengordon** [comment]
Opening to get the tests to run, I'll be fixing the py3 errors here...

**Comment by lorengordon** [comment]
@rallytime I just saw the updated comment on the last PR saying this was good to go for 2016.11. I rebase on that branch. I expect that runs the 2016.11 tests, instead of develop tests?

**Comment by rallytime** [comment]
@lorengordon oh, yeah. It should restart the tests when you change the branch and will run the appropriate tests. Py3 tests don't run on 2016.11 though, so we might have that build hanging around here because it won't restart it.

**Comment by lorengordon** [comment]
Ugh, this would be easier if rebase actually worked, but it pulls in a ton of other commits. Trying another tack...

**Comment by lorengordon** [comment]
There we go, ended up cherry-picking each commit to get it to do what I wanted.

**Comment by rallytime** [comment]
Thanks for grabbing this @lorengordon.

**Review by rallytime — APPROVED** [review]

**Comment by lorengordon** [comment]
oh so pretty! passing tests! thanks @rallytime and @arount!

**Pull request merged**
