### PR TITLE
Additional riak functions

### PR DESCRIPTION
**Pull request by dmyerscough**

### CODE REVIEW

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by dmyerscough** [comment]
I noticed Jenkins marks a few builds as failures, is there a reason for this?

**Comment by cachedout** [comment]
I grabbed your fork and tested this by hand. It looks like the lint errors were legit and the other test failures were spurious. I'll go ahead and merge this and then clean up the lint errors real quick. Thanks for your good work here, @dmyerscough. These will be good additions!

**Comment by dmyerscough** [comment]
Thanks @cachedout !

**Comment by cachedout** [comment]
My pleasure. Thank you for this addition!

**Pull request merged**
