### PR TITLE
Enhance defaults.merge function.

### PR DESCRIPTION
**Pull request by aabouzaid**
### What does this PR do?
In `defaults.merge` function:
- Add `merge_lists` option.
- Add `in_place` option.
- Write unit tests.

### Previous Behavior
Lists were not merged, and no unit test for `merge` function.

### New Behavior
- Allow to merge lists.
- Allow to keep original dicts untouched and create new dict.
- Unit test.

### Tests written?
Yes

### Commits signed with GPG?
Not yet

### CODE REVIEW

**Comment by rallytime** [comment]
@AAbouZaid Can you fix this lint error? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/17053/violations/file/tests/unit/modules/test_defaults.py/

**Comment by AAbouZaid** [comment]
@rallytime Akh, a type :face_with_head_bandage: 
Fixed :-)

**Comment by AAbouZaid** [comment]
I also added an arg to don't copy in place, so it keeps the orig dicts untouched.
The original behavior still the same (`in_place=True` by default).

**Comment by garethgreenaway** [comment]
@AAbouZaid Looks like there are still a couple more lint errors.  Would you mind taking care of those?

**Comment by AAbouZaid** [comment]
@garethgreenaway Fixed :-)

**Comment by garethgreenaway** [comment]
@AAbouZaid Awesome!  Thanks!  Just waiting for automated tests to finish then we should be good to go.

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
