### PR TITLE
Remove deprecated Legacy Git Pillar code

### PR DESCRIPTION
**Pull request by rallytime**
The legacy git pillar code has been deprecated for some time and is to be removed in `Oxygen`. Thank you to @terminalmage who helped review this already. Let's see what the tests think. ;)

### CODE REVIEW

**Comment by rallytime** [comment]
run lint test

**Comment by rallytime** [comment]
re-run docs

**Comment by terminalmage** [comment]
@rallytime needs a rebase

**Comment by rallytime** [comment]
@terminalmage Yeah. There are test failures here too. I am testing some new jenkins features here.

**Review by terminalmage — APPROVED** [review]

**Comment by terminalmage** [comment]
@rallytime appoved PR but it needs another rebase before merging.

**Comment by rallytime** [comment]
Bah! I even double-checked that this morning. One rebase coming up shortly!

**Comment by terminalmage** [comment]
Legacy git_pillar is officially dead. :clap:

**Pull request merged**
