### PR TITLE
Updates to Venafi module

### PR DESCRIPTION
**Pull request by tr1ck3r**
### What does this PR do?
Transitions solution to Venafi preferred integration interface (VCert-Python) and updated to align with Venafi standard use cases for DevOps

### What issues does this PR fix or reference?
Restores interoperability with Venafi Cloud

### Previous Behavior
Supported only Venafi Cloud

### New Behavior
Adds support for Venafi Trust Protection Platform

### Tests written?
Yes

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by arykalin** [comment]
Hi, looks like integration tests are failing because our Venafi runner need vcert library, how we can add it to requirements? Also is it possible to provide credentials for our public cloud environment for this tests?

**Comment by waynew** [comment]
Hi @tr1ck3r thanks for the PR! Looking into this now. I think the requirements will belong in `requirements/base.txt` but I'm not certain - double checking that now. I know that if requirements are added currently we require `pre-commit` to run and rebuild the static requirement files.

I'm not sure exactly how to add the cloud credentials, but I know it's possible to add them.

I'll let you know what I find out!

**Comment by waynew** [comment]
@arykalin looks like the requirements should be added to `requirements/static/*.in` files, whichever are necessary. Please use a pinned version. Then install `pre-commit` (you could do it like `python -m pip install --user pre-commit`, if you don't already have a venv activated), and run it - `pre-commit`. It will "error" if there are requirements to change. If you run it again it should not fail.

You should be able to add & commit the new requirements files and push those changes.

Let me know if you have any issues!

**Comment by arykalin** [comment]
Hi @waynew I added vcert depdendency to operating systems *.in files (https://github.com/saltstack/salt/pull/54695/commits/8832390e3a6d1f6227277d3eadd814da1ea12d2c)  and run pre-commit but looks like vcert is still not installed during jenkins job run - https://jenkinsci.saltstack.com/job/pr-kitchen-centos7-py3/job/PR-54695/5/consoleFull

Here is output of pre-commit:

```
$ ./.venv/bin/pre-commit
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/arykalin/.cache/pre-commit/patch1570005163.
[INFO] Initializing environment for https://github.com/saltstack/pip-tools-compile-impersonate.
[INFO] Installing environment for https://github.com/saltstack/pip-tools-compile-impersonate.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Linux Py3.4 ZeroMQ Requirements..........................................Passed
Cloud Py3.4 Requirements.............................(no files to check)Skipped
Lint Py3.4 Requirements..............................(no files to check)Skipped
Linux Py3.5 ZeroMQ Requirements..........................................Passed
OSX Py3.5 ZeroMQ Requirements........................(no files to check)Skipped
Windows Py3.5 ZeroMQ Requirements....................(no files to check)Skipped
Cloud Py3.5 Requirements.............................(no files to check)Skipped
Lint Py3.5 Requirements..............................(no files to check)Skipped
Docs Py3.5 Requirements..............................(no files to check)Skipped
Linux Py3.6 ZeroMQ Requirements..........................................Passed
OSX Py3.6 ZeroMQ Requirements........................(no files to check)Skipped
Windows Py3.6 ZeroMQ Requirements....................(no files to check)Skipped
Cloud Py3.6 Requirements.............................(no files to check)Skipped
Lint Py3.6 Requirements..............................(no files to check)Skipped
Docs Py3.6 Requirements..............................(no files to check)Skipped
Linux Py3.7 ZeroMQ Requirements..........................................Passed
OSX Py3.7 ZeroMQ Requirements........................(no files to check)Skipped
Windows Py3.7 ZeroMQ Requirements....................(no files to check)Skipped
Cloud Py3.7 Requirements.............................(no files to check)Skipped
Lint Py3.7 Requirements..............................(no files to check)Skipped
Docs Py3.7 Requirements..............................(no files to check)Skipped
```
Maybe I did something wrong?

**Comment by waynew** [comment]
@arykalin It looks like you only committed `.in` files - were there changes to other requirements files? From what I understand, there should have been.

**Comment by arykalin** [comment]
@waynew From your post earlier I understand that I should add vcert only to *.in file 

>  looks like the requirements should be added to requirements/static/*.in files, whichever are necessary.

Do you now to what other file I should add our vcert requirement?

**Comment by arykalin** [comment]
I added vcert to tests.txt requirement but nothing changes

**Comment by waynew** [comment]
@s0undt3ch do we have documentation on what to do here?

**Comment by s0undt3ch** [comment]
No, not yet we don't.

I will try to create a docker container which is capable of compiling the requirements and update docs.

**Comment by tr1ck3r** [comment]
@waynew as I understand from my team, the current issue is that many of our tests require a few variables to be set by the test runner in the test execution environment (e.g. the URL for our cloud service, the zone for certificate policy, and most importantly the credentials for authenticating with our cloud service).  Usually we ask partners to register for their own Venafi Cloud at https://www.venafi.com/platform/cloud/devops for this purpose.  There's a small amount of configuration that is necessary after registering (I can help you with that), but once that is done and you configure your test runner to set the variables I mentioned, the tests should pass.  Will that work?

**Comment by arykalin** [comment]
Hi @waynew we added fake account support to our tests, so there should be no need for credentials, alos we fixed all linter problems. But I see a problem in logs which is not applied to vcert:

```
16:25:02  >>>>>> Class: Kitchen::ActionFailed
16:25:02  >>>>>> Message: 1 actions failed.
16:25:02  >>>>>>     Failed to complete #create action: [Neither image_id nor an image_search specified for instance py3-centos-7! Please specify one or the other.] on py3-centos-7
```

Also codeclimate is issuing digicert files.
Could you help us with resolving this issues?

**Comment by bryceml** [comment]
> Hi @waynew we added fake account support to our tests, so there should be no need for credentials, alos we fixed all linter problems. But I see a problem in logs which is not applied to vcert:
> 
> ```
> 16:25:02  >>>>>> Class: Kitchen::ActionFailed
> 16:25:02  >>>>>> Message: 1 actions failed.
> 16:25:02  >>>>>>     Failed to complete #create action: [Neither image_id nor an image_search specified for instance py3-centos-7! Please specify one or the other.] on py3-centos-7
> ```
> 
> Also codeclimate is issuing digicert files.
> Could you help us with resolving this issues?

To fix this, you must open your pr against the master branch.  The images for develop have been deleted.

**Comment by waynew** [comment]
@tr1ck3r you'll also want to run `git rebase --interactive master`, pick your commits, and then `git push --force`

**Comment by arykalin** [comment]
Moving it to https://github.com/saltstack/salt/pull/55267
@tr1ck3r could you close this request?

**Pull request closed without merging**
