### PR TITLE
Azure MSI support

### PR DESCRIPTION
**Pull request by edlane**
### What does this PR do?

Enable rudimentary support for Azure MSI-style authentication described here:
https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/overview
This prevents the requirement to put secure credentials into config files.

This is similar to a **salt-cloud** feature when using IAM authentication in EC2 described here:
https://docs.saltstack.com/en/latest/topics/cloud/aws.html#iam-profile

### What issues does this PR fix or reference?

No public sources known

### Previous Behavior
No support currently exists in salt-cloud for MSI authentication so credentials are often placed in
salt-cloud config files.

### New Behavior
When running salt-cloud in a VM, with appropriate MSI "roles"  assigned to it, the VM can perform all valid salt-cloud functions in Azure.
No credentials need to be placed in config files.

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Review by gtmanfred — APPROVED** [review]

**Comment by rallytime** [comment]
@edlane This has a merge conflict. Can you rebase and fix it, please?

**Comment by edlane** [comment]
@rallytime 
Is it ok to submit PRs for **2018.3** or must they be made for **develop** only ?

**Comment by rallytime** [comment]
@edlane new features go in develop, bug fixes can go into older branches.

https://docs.saltstack.com/en/latest/topics/development/contributing.html#salt-s-branch-topology

**Comment by cachedout** [comment]
Hi @edlane. We still need this merge conflict resolved before we can get this in, please. Thanks.

**Comment by edlane** [comment]
@rallytime , @cachedout 
Please close this PR in lieu of this new one made for the **develop** branch as instructed above: https://github.com/saltstack/salt/pull/49063

(azurearm in the **develop** branch has incurred a major refactor since the **2018.3** branch which made this necessary)

-Thanks.

**Comment by cachedout** [comment]
Thanks, @edlane. I'll close this.

**Pull request closed without merging**
