### PR TITLE
Make AES key never hit disk on the master

### PR DESCRIPTION
**Pull request by jacksontj**
In the past we've been doing coordination of the aes key using dropfiles etc. Not only is this significantly more costly (at least 1 stat per reqserver request) it also means that the symmetric key we use to pub/req messages has been on disk. This re-works the aes key to be a multiprocessing.Array() (char array) which is shared amongst the processes. Now the dropfile is just a request for the master to rotate the key, and this means that _all_ key rotation on the master will generate the appropriate event (instead of just ones who passed in sock_dir to dropfile())

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by jacksontj** [comment]
@thatch45 And that it did ;) It appears that the aes key is passed in the opts all over creation-- and multiprocessing.Array is not deepcopy-able (which the git external pillar does). This should fix the issue for now, but as part of my cleanup I plan on moving the AES key out of the opts dict all together.

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
I agree, this is great stuff, thanks!

**Comment by jacksontj** [comment]
That test failure seems unrelated ;)

**Comment by thatch45** [comment]
W00t! tests ran!

**Comment by jacksontj** [comment]
Very exciting, From my local testing this compared to just the stat (not the reading of the aes key of disk) will be at least an order of magnitude faster! Very exciting

**Comment by cachedout** [comment]
This is seriously awesome.

**Pull request merged**
