### PR TITLE
fix systemd_service.get_enabled, get_disabled and get_static on newer systemd version

### LINKED ISSUE #59526: [BUG] module service.get_enabled/disabled/static nolonger work with latest systemd
**Description**
in older systemd version, the output of list-unit-files looked like this
```
boot-complete.target                                                    static                                                                                                                                                                
cryptsetup-pre.target                                                   static                                                                                                                                                                
cryptsetup.target                                                       static                                                                                                                                                                
ctrl-alt-del.target                                                     disabled                                                                                                                                                              
default.target                                                          static                                                                                                                                                                
emergency.target                                                        static                                                                                                                                                                
exit.target                                                             disabled                                                                                                                                                              
final.target                                                            static                                                                                                                                                                
getty-pre.target                                                        static                                                                                                                                                                
getty.target                                                            static                                                                                                                                                                
graphical.target                                                        static                                                                                                                                                                
halt.target                                                             disabled    
```
with only 2 fields, The unit name and the enabled state.
On newer version of systemd, they added a new field, the `VENDOR_PRESET`
```
boot-efi.mount                                       generated       -            
boot.mount                                           generated       -            
dev-hugepages.mount                                  static          -            
dev-mqueue.mount                                     static          -            
home-guillaumedk-.steam-library.mount                enabled         disabled     
home-guillaumedk-Nas.mount                           disabled        disabled     
home.mount                                           generated       -            
mnt-media.mount                                      disabled        disabled     
proc-fs-nfsd.mount                                   static          -            
proc-sys-fs-binfmt_misc.mount                        disabled        disabled     
run-vmblock\x2dfuse.mount                            disabled        disabled     
sys-fs-fuse-connections.mount                        static          -            
sys-kernel-config.mount                              static          -            
sys-kernel-debug.mount                               static          -            
```
Resulting in issue when parsed by this script.
unit_state would look like `'static -'`

so i get 
```
~$ sudo salt-call service.get_static
local:
```
Instead of
```
~$ sudo salt-call service.get_static
local:
    - apt-daily
    - apt-daily-upgrade
    - auth-rpcgss-module
    - basic.target
    - blockdev@.target
    - bluetooth.target
    - boot-complete.target
    - container-getty@
    - cryptsetup-pre.target
    - cryptsetup.target
    - dbus
    - dbus.socket
    - dev-hugepages.mount
...
```

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info).

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)
I am running `systemd 246 (246.6-2~bpo10+1)` on Debian 10
i can see that the old behavior was still working as of `systemd 241 (241)`

**Expected behavior**
Module `service.get_static` `service.get_disabled` and `service.get_enabled` return the requested data with both the old and new output format of systemd `list-unit-files`

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3002.1

Dependency Versions:
           cffi: 1.14.0
       cherrypy: 3.5.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
         Jinja2: 2.9.4
        libgit2: 0.99.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: 1.1.1
         Python: 3.5.3 (default, Jul  9 2020, 13:00:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.1.2
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9 stretch
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-14-amd64
         system: Linux
        version: Debian GNU/Linux 9 stretch

```
</details>

**Additional context**
Fixed with https://github.com/saltstack/salt/pull/59525

### PR DESCRIPTION
**Pull request by Vaarlion**
### What does this PR do?

This PR fix systemd_service.get_enabled, get_disabled and get_static on newer systemd version

in older systemd version, the output of list-unit-files looked like this
```
boot-complete.target                                                    static                                                                                                                                                                
cryptsetup-pre.target                                                   static                                                                                                                                                                
cryptsetup.target                                                       static                                                                                                                                                                
ctrl-alt-del.target                                                     disabled                                                                                                                                                              
default.target                                                          static                                                                                                                                                                
emergency.target                                                        static                                                                                                                                                                
exit.target                                                             disabled                                                                                                                                                              
final.target                                                            static                                                                                                                                                                
getty-pre.target                                                        static                                                                                                                                                                
getty.target                                                            static                                                                                                                                                                
graphical.target                                                        static                                                                                                                                                                
halt.target                                                             disabled    
```
with only 2 fields, The unit name and the enabled state.
On newer version of systemd, they added a new field, the VENDOR_PRESET
```
boot-efi.mount                                       generated       -            
boot.mount                                           generated       -            
dev-hugepages.mount                                  static          -            
dev-mqueue.mount                                     static          -            
home-guillaumedk-.steam-library.mount                enabled         disabled     
home-guillaumedk-Nas.mount                           disabled        disabled     
home.mount                                           generated       -            
mnt-media.mount                                      disabled        disabled     
proc-fs-nfsd.mount                                   static          -            
proc-sys-fs-binfmt_misc.mount                        disabled        disabled     
run-vmblock\x2dfuse.mount                            disabled        disabled     
sys-fs-fuse-connections.mount                        static          -            
sys-kernel-config.mount                              static          -            
sys-kernel-debug.mount                               static          -            
```
Resulting in issue when parsed by this module.
`unit_state` would look like `'static          -'`

This fix allow any number of field to be split, but only keep the first 2.

### What issues does this PR fix or reference?
Fixes: #59526

### Previous Behavior
```
~$ sudo salt-call service.get_static
local:
```

### New Behavior
```
~$ sudo salt-call service.get_static
local:
    - apt-daily
    - apt-daily-upgrade
    - auth-rpcgss-module
    - basic.target
    - blockdev@.target
    - bluetooth.target
    - boot-complete.target
    - container-getty@
    - cryptsetup-pre.target
    - cryptsetup.target
    - dbus
    - dbus.socket
    - dev-hugepages.mount
...
```

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by sagetherage** [comment]
@Vaarlion we no longer use the `develop` branch please point this to `master`

**Review by twangboy — CHANGES_REQUESTED** [review]
Please add some tests for the two different outputs to `unit/modules/test_systemd_service.py`

Also, please rebase this against the master branch. Develop is no longer used...

**Comment by Vaarlion** [comment]
Dammit ! i explicitly rebased from master to develop :(

**Comment by Vaarlion** [comment]
> Please add some tests for the two different outputs to `unit/modules/test_systemd_service.py`
> 
> Also, please rebase this against the master branch. Develop is no longer used...

test have been added and the pre-commit did some cleanup.

**Comment by Vaarlion** [comment]
sorry for all the noise.
I had to look how to run test locally
I don't get how, but somehow the fake service `foo` have to be ignored, `bar` disable et `baz` enable.
I've just matched the test to that, but i have no idea how it work so i couldn't add `qux`for static.

I hop this is enough

**Comment by sagetherage** [comment]
looking good! I have updated the labels to reflect all your work and thank you!!

**Comment by sagetherage** [comment]
it would be nice to get a [changelog](https://docs.saltproject.io/en/latest/topics/development/changelog.html) file since this fixes a bug @Vaarlion

**Comment by twangboy** [comment]
Does this change break those functions on older systemd versions? Or does it now handle both? Can you test the for the old system and for the new system?

**Comment by Vaarlion** [comment]
> it would be nice to get a [changelog](https://docs.saltproject.io/en/latest/topics/development/changelog.html) file since this fixes a bug @Vaarlion

I was confused about changelog, reading that those should only be done when in a release ? I'll look into it :+1: 



> @Vaarlion Does this change break those functions on older systemd versions? Or does it now handle both? Can you test the for the old system and for the new system?

The change allow to work with both the old and new format, and the test are making sure both will work down the line.
I believe there is no reason to remove support anytime soon :D

**Review by twangboy — DISMISSED** [review]

**Comment by Vaarlion** [comment]
Is that changelog good enough ?

**Review by twangboy — APPROVED** [review]

**Review by xeacott — APPROVED** [review]

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
