### PR TITLE
addresses issue #43307, disk.format_ to disk.format

### PR DESCRIPTION
**Pull request by msummers42**
This change fixes breakage. It appears the disk.format_ func is
aliased to disk.format in modules/disk.py

https://github.com/saltstack/salt/issues/43307

### CODE REVIEW

**Comment by msummers42** [comment]
cc @Ch3LL

**Comment by rallytime** [comment]
@msummers42 Thanks for submitting this fix and welcome! Can you move this to be submitted against the `2017.7` branch instead of the `2017.7.2` branch? The `2017.7.2` branch is currently closed for fixes.

**Comment by msummers42** [comment]
I am going to close this and create a new one.

**Comment by msummers42** [comment]
@rallytime new PR#44029

**Comment by rallytime** [comment]
Thank you very much @msummers42

**Pull request closed without merging**
