### PR TITLE
gpg module: fix result checking of import_key()

### LINKED ISSUE #24082: gpg module: AttributeError: 'ImportResult' object has no attribute 'imported'
salt-call --versions-report

```
                  Salt: 2014.7.5
                Python: 2.7.3 (default, Dec 18 2014, 19:10:20)
                Jinja2: 2.6
              M2Crypto: 0.21.1
        msgpack-python: 0.1.10
          msgpack-pure: Not Installed
              pycrypto: 2.4.1
               libnacl: Not Installed
                PyYAML: 3.11
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: Not Installed
 Debian source package: 2014.7.5+ds-1precise1
```

`gpg` module is copied from the upstream.

Trying to import a PRIVATE key:

```
salt-call gpg.import_key filename=/root/.gnupg/secring.txt
```

and got this:

```
[DEBUG   ] imported_data ['stderr', 'fingerprints', 'results', '_problem_reason', '_ok_reason', '_gpg', 'counts', '_fields', 'data']
[DEBUG   ] imported_data OrderedDict([('count', 1), ('no_user_id', 0), ('imported', 0), ('imported_rsa', 0), ('unchanged', 0), ('n_uids', 0), ('n_subk', 0), ('n_sigs', 0), ('n_revoc', 0), ('sec_read', 1), ('sec_imported', 0), ('sec_dups', 1), ('not_imported', 0)])
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'ImportResult' object has no attribute 'imported'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/pymodules/python2.7/salt/scripts.py", line 82, in salt_call
    client.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/__init__.py", line 319, in run
    caller.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/caller.py", line 144, in run
    ret = self.call()
  File "/usr/lib/pymodules/python2.7/salt/cli/caller.py", line 81, in call
    ret['return'] = func(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/gpg.py", line 652, in import_key
    if import_result.imported or import_result.imported_rsa:
AttributeError: 'ImportResult' object has no attribute 'imported'
```

### PR DESCRIPTION
**Pull request by quantonganh**
Fix #24082

### CODE REVIEW

**Comment by jfindlay** [comment]
@quantonganh, will you also update the [failing unit test](https://jenkins.saltstack.com/job/salt-pr-rs-ubuntu14.04-n/5383/testReport/junit/unit.modules.gpg_test/GpgTestCase/test_import_key/)?  Thanks.  Let me know if you can't figure it out.

**Comment by quantonganh** [comment]
@jfindlay: Even when text is just a header, I cannot reproduce that:

```
>>> text = '-BEGIN PGP PUBLIC KEY BLOCK-'
>>> import_result = gpg.import_keys(text)
>>> print(import_result.counts)
OrderedDict([('count', 0), ('no_user_id', 0), ('imported', 0), ('imported_rsa', 0), ('unchanged', 0), ('n_uids', 0), ('n_subk', 0), ('n_sigs', 0), ('n_revoc',
 0), ('sec_read', 0), ('sec_imported', 0), ('sec_dups', 0), ('not_imported', 0)])
>>> counts = import_result.counts
>>> print(counts['imported'])
0
```

**Comment by jfindlay** [comment]
@quantonganh, I'll look at this and try to fix the failing test, thanks.

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
I fixed this up in #24760.

Thanks @quantonganh !

**Pull request merged**
