### PR TITLE
Add get_properties() to modules/win_file.py

### PR DESCRIPTION
**Pull request by amalaguti**
### What does this PR do?
Add get_properties() to modules/win_file.py

### What issues does this PR fix or reference?
Fixes:
#59702 

### Previous Behavior
Function not present

### New Behavior
This function returns Windows file properties

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by xeacott** [comment]
Thanks again for getting this PR up @amalaguti - as it currently stands, there's a couple more things we need to add this...
1. changelog file
2. run `pre-commit` on it
3. add tests

1 and 2 should be relatively quick; generating a changelog file is as easy as just creating a file called `59888.added` and then add a message that says `add get_properties function to win_file.py` and as for running `pre-commit` I can do that momentarily.

As for tests, you'll need to write some for `tests/unit/modules/test_win_file.py` so that we can ensure this behavior wont break in future changes. Unfortunately this file will also need to be converted into a pytest file and follow our pytest guidelines. If any of this sounds too much or if you don't have time, please let me know I'd be happy to help or show examples!

**Comment by amalaguti** [comment]
@xeacott Joe, I'll need your help.
On creating the changelog, my doubt is why the file has to be named 59888.added (where is the 59888 coming from ? wondering if you mean 59770)

On the pre-commit, I'll leave it to you, thanks :)

About creating test, sorry not sure how to create one.

**Comment by xeacott** [comment]
Yeah! So sorry, meant 59702. It's the issue # not the PR number we're after. 😄 As for pre-commit ill run that on your branch and push up. 

So as far as adding some tests to `tests/unit/modules/test_win_file.py`... a good idea would be to test that your new function is doing what its suppose to be doing. Something like this will probably be good enough, again just making sure that if someone modifies the function in the future, they aren't breaking anything that you established with it.
```
    def test_get_properties(self):
        """
        Test that given a file all properties return.
        """
        file = "C:\Program Files\Google\Chrome\Application\chrome.exe"

        expected = {{"permissions": {{'FixedFileInfo': None, 'StringFileInfo': None, 'FileVersion': None}} }
        ret = win_file.get_properties(fname=file)
        self.assertDictEqual(ret, expected)
```

**Comment by twangboy** [comment]
These changes were added with https://github.com/saltstack/salt/pull/62054

**Pull request closed without merging**
