### PR TITLE
change python_shell default to False

### PR DESCRIPTION
**Pull request by jfindlay**

### CODE REVIEW

**Comment by thatch45** [comment]
@jfindlay do any of these errors apply? The cmd one looks like it might, but I could just be jumbled in the ones that were broken at the time

**Comment by rallytime** [comment]
The cmd one does. @jfindlay has asked me to look at it, since I wrote that test.

**Comment by thatch45** [comment]
@rallytime any status on this?

**Comment by rallytime** [comment]
No, sorry. I have been wrestling with Jenkins. I'll do this today, if we can get Jenkins back online.

**Comment by thatch45** [comment]
Thanks @rallytime, just checking

**Comment by iggy** [comment]
That seems like a rather large backward incompatible change... I've been seeing traces of this all over. Notably with | (pipes) in cmd.run's

This seems like something that should have emitted a warning for a version or two before changing. There's also no versionchanged information in the docs to even sort of help people figure out what was going on.

It would also be nice if there was an option to restore previous functionality (in the absence of any kind of grace period with a warning).

```
bjackson@dev-salt01:~$ sudo salt-call cmd.run "ps -ef | grep salt"
[INFO    ] Executing command 'ps -ef | grep salt' in directory '/root'
[ERROR   ] Command 'ps -ef | grep salt' failed with return code: 1
[ERROR   ] output: error: garbage option

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
local:
    error: garbage option
    
    Usage:
     ps [options]
    
     Try 'ps --help <simple|list|output|threads|misc|all>'
      or 'ps --help <s|l|o|t|m|a>'
     for additional help text.
    
    For more details see ps(1).
bjackson@dev-salt01:~$ sudo salt-call cmd.run "ps -ef | grep salt" python_shell=True
[INFO    ] Executing command 'ps -ef | grep salt' in directory '/root'
local:
    root       925 31247  0 16:29 pts/0    00:00:00 sudo salt-call cmd.run ps -ef | grep salt python_shell=True
    root       926   925 44 16:29 pts/0    00:00:00 /usr/bin/python /usr/bin/salt-call cmd.run ps -ef | grep salt python_shell=True
    root       956   926  0 16:29 pts/0    00:00:00 /bin/bash -c ps -ef | grep salt
    root       958   956  0 16:29 pts/0    00:00:00 grep salt
    root     20179     1  0 Mar19 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion
    root     20196 20179  0 Mar19 ?        00:03:38 /usr/bin/python /usr/bin/salt-minion
    root     28112     1  0 Mar19 ?        00:00:00 /usr/bin/python /usr/bin/salt-master -d
    root     28113 28112  0 Mar19 ?        00:35:20 /usr/bin/python /usr/bin/salt-master -d
    root     28114 28112  0 Mar19 ?        00:00:00 /usr/bin/python /usr/bin/salt-master -d
    root     28115 28112  0 Mar19 ?        00:00:00 /usr/bin/python /usr/bin/salt-master -d
    root     28160 28112  0 Mar19 ?        01:25:28 /usr/bin/python /usr/bin/salt-master -d
    root     28161 28112  0 Mar19 ?        00:00:00 /usr/bin/python /usr/bin/salt-master -d
    root     28163 28161  0 Mar19 ?        00:00:22 /usr/bin/python /usr/bin/salt-master -d
    root     28166 28161  0 Mar19 ?        00:00:22 /usr/bin/python /usr/bin/salt-master -d
    root     28169 28161  0 Mar19 ?        00:00:22 /usr/bin/python /usr/bin/salt-master -d
    root     28170 28161  0 Mar19 ?        00:00:22 /usr/bin/python /usr/bin/salt-master -d
    root     28171 28161  0 Mar19 ?        00:00:22 /usr/bin/python /usr/bin/salt-master -d
    root     28183 28161  0 Mar19 ?        00:00:11 /usr/bin/python /usr/bin/salt-master -d
bjackson@dev-salt01:~$ 
```

**Pull request merged**
