### PR TITLE
Fix list nodes

### LINKED ISSUE #19596: Azure: Deleting instances does not work when using service_name
```
           Salt: 2015.2.0-75-gea2b826
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.3
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.4.1
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed
```

### LINKED ISSUE #19609: Azure: when using service_name a VM is not seen as created when runnning salt-cloud again
It then tries to create the VM again which results in a conflict error.

### PR DESCRIPTION
**Pull request by flavianh**
Fixes #19609
Fixes #19596 
Changes list_full_nodes so that the vm name is at the root of the returned dictionary

### CODE REVIEW

**Comment by thatch45** [comment]
@techhat please be aware that I am merging this

**Comment by thatch45** [comment]
Thanks @traxair you are fantastic!

**Comment by techhat** [comment]
@thatch45, thanks, I was working with @traxair on this this morning.

**Comment by traxair** [comment]
Yup, I am happy to share half the fantasticity with techhat

**Pull request merged**
