### PR TITLE
boto_ec2 module

### PR DESCRIPTION
**Pull request by mgwilliams**
Ref #21674 -- whichever of these is merged first then needs to be merged into the other.

@techhat, @tsaridas

### CODE REVIEW

**Comment by jfindlay** [comment]
@mgwilliams, there is a documentation error.  Thanks for the excellent work.

**Comment by techhat** [comment]
@mgwilliams, sorry, I went with the other one.

**Comment by mgwilliams** [comment]
@techhat no problem, I"ll merge them

**Comment by mgwilliams** [comment]
@techhat if tests pass this should be ready to merge

**Pull request merged**
