### PR TITLE
saltcheck module

### PR DESCRIPTION
**Pull request by wcannon**
### What does this PR do?
This pull request adds a salt module for salt state logic checking

### What issues does this PR fix or reference?
none

### New Behavior
Remove this section if not relevant
Allows for unit-test-like testing of salt states and highstates

### Tests written?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
I do like this quite a lot but I wouldn't feel comfortable getting it in until there is more substantial documentation in the Salt docs themselves, versus just having it in the module.

@gtmanfred What do you think about perhaps creating a `Testing` tutorial that talks about both this approach and the new salt-kitchen stuff?

**Comment by gtmanfred** [comment]
I think that would be great!

**Comment by wcannon** [comment]
Adding a tutorial seems very sensible.  So, how should we proceed?

**Comment by cachedout** [comment]
@wcannon or @gtmanfred Any volunteers to start on a tutorial? :] I'm happy to merge this before then but it would be great if we could get started ASAP so it's not forgotten.

**Comment by gtmanfred** [comment]
I will add it to my list.

**Comment by wcannon** [comment]
Mike - a couple questions about this:
1.  what format should be used?
2.  where should the tutorial be placed for review?
3.  any specific content you would like to see in the tutorial?  I'm open
to suggestions.

**Comment by gtmanfred** [comment]
@wcannon don't worry about the tutorial, I am going to go through and
document all of this.  I will be giving a talk about testing salt states
for SaltConf 2017

**Comment by wcannon** [comment]
Thanks Daniel (@gtmanfred).  I'll skip working on the tutorial.

btw, I'm giving a talk on testing salt states at saltconf too.  See you
there!

**Comment by cachedout** [comment]
@gtmanfred How do you want to handle this. Do you want to just submit a PR to @wcannon 's branch or do something independently?

**Comment by gtmanfred** [comment]
Can we merge this PR, and then I will start on the documentation for this and the tutorial for testing next week?

Thanks,
Daniel

**Comment by cachedout** [comment]
@gtmanfred Yes, I have no problem with that at all. It does look like it failed a lint check though. I'll re-run the test and then hopefully @wcannon can fix it right up.

**Comment by cachedout** [comment]
re-run lint

**Comment by wcannon** [comment]
Anything else left to do?

**Review by gtmanfred — APPROVED** [review]

**Pull request merged**
