### PR TITLE
Add missing super in tearDown

### LINKED ISSUE #57253: [BUG] scheduler unit tests are failing on Windows
https://github.com/saltstack/salt/pull/57238

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?
Fixes the following tests in Windows:

```
unit.utils.scheduler.test_eval.SchedulerEvalTest.test_eval_after
unit.utils.scheduler.test_eval.SchedulerEvalTest.test_eval_enabled
unit.utils.scheduler.test_eval.SchedulerEvalTest.test_eval_enabled_key
unit.utils.scheduler.test_eval.SchedulerEvalTest.test_eval_hours
unit.utils.scheduler.test_eval.SchedulerEvalTest.test_eval_loop_interval
unit.utils.scheduler.test_eval.SchedulerEvalTest.test_eval_minutes
unit.utils.scheduler.test_eval.SchedulerEvalTest.test_eval_multiple_whens
unit.utils.scheduler.test_eval.SchedulerEvalTest.test_eval_multiple_whens_loop_interval
unit.utils.scheduler.test_eval.SchedulerEvalTest.test_eval_once
unit.utils.scheduler.test_eval.SchedulerEvalTest.test_eval_once_loop_interval
unit.utils.scheduler.test_eval.SchedulerEvalTest.test_eval_run_on_start
unit.utils.scheduler.test_eval.SchedulerEvalTest.test_eval_seconds
unit.utils.scheduler.test_eval.SchedulerEvalTest.test_eval_splay
unit.utils.scheduler.test_eval.SchedulerEvalTest.test_eval_splay_global
unit.utils.scheduler.test_eval.SchedulerEvalTest.test_eval_splay_range
unit.utils.scheduler.test_eval.SchedulerEvalTest.test_eval_until
unit.utils.scheduler.test_eval.SchedulerEvalTest.test_eval_when_splay
unit.utils.scheduler.test_eval.SchedulerEvalTest.test_eval_whens
unit.utils.scheduler.test_skip.SchedulerSkipTest.test_run_seconds_skip
unit.utils.scheduler.test_skip.SchedulerSkipTest.test_skip
unit.utils.scheduler.test_skip.SchedulerSkipTest.test_skip_during_range
unit.utils.scheduler.test_skip.SchedulerSkipTest.test_skip_during_range_global
```

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/57253

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by s0undt3ch — DISMISSED** [review]
Do all of the other test classes for scheduler which inherit from the base class also call super?

**Review by cmcmarrow — DISMISSED** [review]

**Comment by twangboy** [comment]
@s0undt3ch Looks like all scheduler tests inherit the base class. One test does not call setUp or tearDown (`test_schedule`). The rest all have `setUp` functions with a super. There are two other test files that have a `setUp` that calls super with a `tearDown` that does not call super.

```
test_postpone
test_skip
```

Should we add a super to the `tearDown` of those as well?

**Comment by s0undt3ch** [comment]
Yes, please.

**Comment by twangboy** [comment]
Done

**Review by dwoz — APPROVED** [review]

**Pull request merged**
