### PR TITLE
Don't send passwords after shim delimiter is found

### LINKED ISSUE #29422: Salt-SSH JSON render failed - dumping password as string in output?
Hi,

Bit of a strange one here and I've not been able to get to the bottom of it - or figured out how to reliably replicate it.

Salt-SSH occasionally gets itself into a state where it will randomly output the password used for SSHing to the server into the JSON output it's trying to render, causing a render failure. When it's doing this it will always output the password at the end of the JSON output, but I've also found that it appears random *in* the output. For example:

```
[ERROR   ] JSON Render failed for: {
    "local": {
        "fun_args": [
            "/var/lib/acme/salt//salt_state.tgz", 
            "test=None", 
            "pkg_sum=953bb413acfa01c1e9a65c7e5258f449", 
            "hash_type=md5"
        ], 
        "jid": "20151204095708560039", 
        "return": {
   ... snip ...
            "file_|-/var/www/vhosts_|-/var/www/vhosts_|-directory": {
                "comment": "Directory /var/www/vhosts is in the correct state", THEPASSWORD
    
                "name": "/var/www/vhosts", 
                "start_time": "09:57:34.040038", 
                "result": true, 
                "duration": 0.823, 
                "__run_num__": 52, 
                "changes": {}
            }, 
    ... snip ...
        }, 
        "retcode": 0, 
        "fun": "state.pkg", 
        "id": "SID1000000", 
        "out": "highstate"
    }
}
THEPASSWORD
```

I've tried removing the thin dir on the remote, and also disabling keeping the thin dir just in case, but it still happens. I'm not sure what triggers it but I'm unable to make it stop doing this! There's nothing else that stands out in the debug output that I believe it related to this.

Versions info:

```
Salt Version:
           Salt: 2015.8.3
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: 1.0.2
         PyYAML: 3.11
          PyZMQ: Not Installed
         Python: 2.7.10 (default, Oct 14 2015, 16:09:02)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed
           cffi: 1.1.2
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.4
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed
 
System Versions:
           dist: Ubuntu 15.10 wily
        machine: x86_64
        release: 4.2.0-19-generic
         system: Ubuntu 15.10 wily
```

### PR DESCRIPTION
**Pull request by Xiol**
### What does this PR do?

The SSH_PASSWORD_PROMPT_RE regexp used to detect if SSH is requesting a password can be triggered if the shim is returning data to the server with text that matches the regex, including inside JSON results. Because the passwords sent over then appear randomly in the JSON output, the server unable to parse the JSON. This patch fixes this issue by looking for the shim delimiter in the output and disabling the sending of passwords after the delimiter is found.
### What issues does this PR fix or reference?

Fixes #29422.
### Tests written?

No

### CODE REVIEW

**Comment by cachedout** [comment]
@thatch45 Could you please take a look here?

**Comment by thatch45** [comment]
BRILLIANT! AMAZING! you totally win @Xiol !!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
lets backport to at least 2016.3 before the release

**Pull request merged**
