### PR TITLE
test #27238 prevent keyerror when partition doesn't exist

### PR DESCRIPTION
**Pull request by arnisoph**
Test case for #27238

### CODE REVIEW

**Comment by bechtoldt** [comment]
The test test_percent_args_nonexisting_partition is expected to fail.

**Comment by bechtoldt** [comment]
hmm, why didn't it fail?

**Comment by cachedout** [comment]
@bechtoldt Is this ready to go?

**Comment by bechtoldt** [comment]
@cachedout Nope, see comments.

**Comment by cachedout** [comment]
@bechtoldt OK. Should we keep this open or just close it? Let me know if there's something I can do to help.

**Comment by bechtoldt** [comment]
I think the test is useless at the moment since it doesn't recognize the exception that was fixed in #27238 . In case of a future regression, the test won't fail.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Pull request closed without merging**
