### PR TITLE
Add keep-alive support to TCP transport

### PR DESCRIPTION
**Pull request by skizunov**
salt/transport/tcp.py:
- Added a utility function `_set_tcp_keepalive`. This function supports
  both Windows `SIO_KEEPALIVE_VALS` and non Windows `TCP_KEEPIDLE`,
  `TCP_KEEPCNT`, `TCP_KEEPINTVL` variants of the tuning methods for
  keep-alive.
- Added keep-alive support for all incoming and outgoing non-IPC
  connections: `TCPReqServerChannel`, `TCPPubServerChannel`,
  `AsyncTCPReqChannel` (via SaltMessageClient), `AsyncTCPPubChannel`
  (via SaltMessageClient)
- To support SaltMessageClient, created a class `TCPClientKeepAlive`
  which wraps `tornado.tcpclient.TCPClient` and overrides `_create_stream`
  to be able to make the sockets keep-alive.

salt/config/**init**.py
- For the master side, added default values for `tcp_keepalive` and
  friends. Turned this on by default. These master-side versions aren't
  (currently) used in the zeromq transport, but are in the TCP transport.
  Some benefits to having master-side `tcp_keepalive`:
  - The master will correctly detect the lack of presence of disconnected
    minions (which were disconnectly via non-standard means such as
    ethernet cable yank or cut power). eg, for events
    `salt/presence/present` and `salt/presence/change`.
  - Will clean up resources associated with no longer present minions.

Signed-off-by: Sergey Kizunov sergey.kizunov@ni.com

### CODE REVIEW

**Comment by cachedout** [comment]
Paging @jacksontj

**Comment by skizunov** [comment]
I fixed the Pylint error, all the tests pass now.

**Comment by cachedout** [comment]
@skizunov I took a look at it this morning and it looks great. I'm going to go ahead and merge this and we'll run the full test suite against it. Unfortunetely we don't have PR tests for the TCP transport yet. Thanks again for your very hard work here. This will be a good addition!

**Comment by jacksontj** [comment]
LGTM, thanks for the addition :)

**Pull request merged**
