### PR TITLE
calling range is going up to the upper limit but not including it

### PR DESCRIPTION
**Pull request by mcalmer**
### What does this PR do?

Fix tests marked as flaky. Such a test is called 4 times but a "FAILED" is never shown.

### Previous Behavior

In case a flaky tagged test is really failing it does not return with "FAILED".

### New Behavior

A failed test is detected correctly.

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by mcalmer** [comment]
Seems that now the test failures are shown which were hidden before by this bug.

**Comment by mcalmer** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
re-run py2

**Comment by rallytime** [comment]
re-run py2

**Comment by rallytime** [comment]
@mcalmer There were test results here when I checked yesterday, but they've already timed-out. I have restarted them one more time.

I am happy to get this fix in, but we would need these test failures fixed before we can do so. I realize those failures were not caused by this change, but we want to try to limit adding test failures into the branch as much as possible.

**Comment by mcalmer** [comment]
@rallytime no problem. I think this one can be seen as a bug and can be backported also after the branch to Oxygen. I will try to rebase it to see if current develop looks better

**Comment by rallytime** [comment]
@mcalmer Yes, I agree. We can certainly back-port this as a bugfix when it is ready to go. Thank you!

**Review by cachedout — APPROVED** [review]

**Pull request merged**
