### PR TITLE
saltstack#57318 add conn.open to junos.cli

### PR DESCRIPTION
**Pull request by jtraub91**
### What does this PR do?
Adds `conn.open` call to `junos.cli` to refresh the stale ssh connection

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/57318

### Previous Behavior
Stale connections sometimes do not display newlines as it should.

### New Behavior
Connection is effectively refreshed and output is as expected.

### CODE REVIEW

**Comment by vnitinv** [comment]
This change is not required. Stale connection should be fixed by keep-alive feature.

**Comment by jtraub91** [comment]
@vnitinv Then there seems to be a bug in the keep alive feature. The default config should achieve this but it does not. Can we please take a closer look here https://github.com/saltstack/salt/issues/57318 ?

**Comment by vnitinv** [comment]
@jtraub91 Not getting o/p in multiple lines has nothing to do with connectivity. Must be something to do with Normalize.

**Comment by jtraub91** [comment]
@vnitinv Do you happen to know why calling conn.open() again resolves the problem? I could refactor `proxy.junos.alive` to call this, but it sounds like you're suggesting a more elegant solution?

**Comment by vnitinv** [comment]
@jtraub91 Can you share with me the state file which was executed before encountering this issue?

**Comment by jtraub91** [comment]
@vnitinv No state file. The details are documented in https://github.com/saltstack/salt/issues/57318. The command I ran was 
```
$ salt <minion-id> junos.cli "show ntp associations no-resolve"
```

**Review by dmurphy18 — COMMENTED** [review]
While this appears to fix the issue, from the comments it appears that this resolves the symptom but is not the cure.  Better to fix the underlying reason, also fix would need a test-case, which in providing would high-light were the correct fix needs to be made.

**Comment by dmurphy18** [comment]
@jtraub91 Any movement on this issue, there have been updates to junos support since then and if they have resolved your issue since this is issue should really be why keep_alive not working rather than fixing the symptom.

Note have a fix to make to salt/modules/junos.py which is under test at the moment https://github.com/saltstack/salt/issues/59020

**Review by dmurphy18 — CHANGES_REQUESTED** [review]
@jtraub91 Are you still interested in this PR ?, if unresponsive, this PR will be closed after several days

**Comment by jtraub91** [comment]
@dmurphy18 I agree that this probably belongs in the `keep_alive` functionality if the problem persists. I'm OK with closing it.

**Comment by dmurphy18** [comment]
@jtraub91 Going to close this, as the Juniper native minion is going to be opened to the public, going through the VMware processes at the moment, so cannot give a timeline but hopefully soon, already approved to do so.
Also since 27 failing checks and PR over 2 years old.

**Pull request closed without merging**
