### PR TITLE
[backport] salt-proxy:  Fix systemd unit file to handle more proxy names

### PR DESCRIPTION
**Pull request by mirceaulinic**
- Ports https://github.com/saltstack/salt/pull/41304 into Nitrogen
- Adds the proxy service file into the deb package. Ping @dmurphy18 - is this alright from your perspective?

### CODE REVIEW

**Comment by mirceaulinic** [comment]
@cro @dmurphy18 I was wondering if we could include the proxy service file in few other packages. Unfortunately, I'm afraid that I have only Deb to test... But I think the same file would work fine on CentOS too.

**Comment by bdrung** [comment]
Please do not add `pkg/deb/salt-proxy@.service`. The Debian package (from upstream and the Debian project) use the service files from the `pkg` directory (`pkg/*.service`).

**Comment by mirceaulinic** [comment]
I imagine that should be the case. However, I don't understand why the service files are explicitly under https://github.com/saltstack/salt/tree/develop/pkg/deb.
Additionally, under https://github.com/saltstack/salt/issues/39395 @dmurphy18 clarifies that the salt-proxy binary is included in the salt-minion package. But installing salt-minion does not provide the salt-proxy services file too.

**Comment by cro** [comment]
The service files under pkg/deb are probably a historical artifact. I'll check with @dmurphy18.

**Comment by bdrung** [comment]
`salt/cloud/deploy/bootstrap-salt.sh` seams to refer to it. The Debian packages do not use them:
```sh
$ grep pkg debian/*.install 
debian/salt-api.install:pkg/salt-api.service /lib/systemd/system
debian/salt-master.install:pkg/salt-master.service /lib/systemd/system
debian/salt-minion.install:pkg/salt-minion.service /lib/systemd/system
debian/salt-syndic.install:pkg/salt-syndic.service /lib/systemd/system
```

**Comment by cro** [comment]
@s0undt3ch or @rallytime can you comment?  I understand the service files in `pkg/deb` are there for the times when the bootstrap script installs from source, pip, or git, but can bootstrap share the ones in `pkg/` so we only have one set and there is less confusion?

**Comment by cro** [comment]
@mirceaulinic hey, we need to check in with @dmurphy18 about this & he'll be back after Memorial Day.  @rallytime and I think there are some areas where this could be streamlined so the bootstrap script as well as distro & SaltStack produced packages all use the same .service files.  It looks like over time the paths have diverged a little (`pkg/` vs `pkg/deb/` vs `pkg/debian/`) and while there doesn't appear to be any substantive difference between the .service files in `pkg/` and `pkg/deb/` it doesn't make sense that they are different at all.

**Comment by mirceaulinic** [comment]
No worries, @cro. Thanks very much for looking.
I'm happy to close this & glad that we discussed and pointed this out. I am confident we'll get this sorted before releasing Nitrogen and have the service files in the package(s). When @dmurphy18 is back, just let me know if and how can I help.

**Comment by dmurphy18** [comment]
The service files for Salt's Debian and Ubuntu packages are taken from pkg/*.service files as @bdrung stated above, similar to Debian's  project and upstream.
The pkg/deb and pkg/debian are historical artifacts which have not been cleaned up due to time and resources to check if anyone was making use of them before deletion.

**Comment by mirceaulinic** [comment]
Hi @dmurphy18 - thanks for clarifying this.
@bdrung has also stated that the salt-proxy service file is missing. Is this wanted?

**Comment by rallytime** [comment]
I have filed an issue in the salt-bootstrap repo to update the service file paths to be consistent. ^ Thanks for the discussion and clarifications!

**Comment by cachedout** [comment]
@cro or @dmurphy18 can one of you please respond to that last question from @mirceaulinic ?

**Comment by dmurphy18** [comment]
@mirceaulinic The salt-proxy.service file was added with the Salt 2016.11.5 point release.  
The Debian project is not yet up to this version, however I did see an email yesterday for someone adding their version of packages for Salt 2016.11.5.  As to how and where the Debian project place that file is a matter of concern for how they package salt-proxy.

Otherwise I have no issue with the changes as they currently exist, noting that the file pkg/deb/salt-proxy@.service is not currently used.

**Comment by cachedout** [comment]
OK, so it sounds like everybody is all right with this going in. I'll leave this open for a bit for any last-minute objections or suggestions.

**Pull request merged**
