### PR TITLE
Break out SPM components into loaders

### PR DESCRIPTION
**Pull request by techhat**
This PR breaks out SPM file handling and package database handling into their own separate loaders. This is especially important for external filesystems which need to interface with SPM, but it will also allow for secure databases to be used for package management.

Ping @msteed.

### CODE REVIEW

**Comment by techhat** [comment]
@cachedout, could you please review this before it gets merged?

**Comment by cachedout** [comment]
@techhat I'll start looking at the code but could you clean up the lint errors in the meantime? Thanks.

**Comment by cachedout** [comment]
The main question I have here is whether it's reasonable to trust the inputs to the SPM database. I don't see anywhere that they're been sanitized before insertion. If the inputs are safe, then the rest looks totally fine.

**Comment by techhat** [comment]
@cachedout, I don't think we have much to worry about here. The database is used entirely for informational purposes; none of the information in there will be used to execute anything. And because sqlite is an open, unencrypted, unprotected database, there's nothing stopping other malicious entities from modifying it.

Fortunately, with this ability to drop in your own database, it is possible to use a backend that can be appropriately protected. So I think for the moment we're good.

**Pull request merged**
