### PR TITLE
Closes #31078 - Add options for syslog returner

### LINKED ISSUE #31078: Feature: Allow specifying syslog facilty, level and tag for syslog returner
Currently everythong goes to default facility, INFO level:

```
def returner(ret):
    '''
    Return data to the local syslog
    '''
    syslog.syslog(syslog.LOG_INFO, '{0}'.format(json.dumps(ret)))
```

### PR DESCRIPTION
**Pull request by carsonoid**
### What does this PR do?

Adds options to the syslog returner for level, facility, tag, and extra flags.
### What issues does this PR fix or reference?
#31078
### Tests written?

No, but all options were extensively tested.

### CODE REVIEW

**Comment by carsonoid** [comment]
Ok looks like I need to fix some lint issues. I'll update the branch in a bit.

**Comment by carsonoid** [comment]
So i've been looking at the issue and the linter is complaining that `__salt__` and `__opts__` don't exist in the `_get_options` function. But all the returners that call salt.returners.get_returner_options pass them just like I do.Also, the option fetching has also worked just fine. Is this just a problem with the linting? Should I pass some extra options to the linter to have it ignore these or can it be merged anyway?

**Comment by cachedout** [comment]
Are you just running pylint locally? You should be using the lint errors that appear here as a reference:

http://166.78.178.63:8080/job/PR/job/salt-pr-lint-n/925/violations/file/salt/returners/syslog_return.py/

Looks like just some pretty basic whitespace cleanup for the most part.

**Comment by carsonoid** [comment]
Good catch. That's exactly what it was. I followed the console log in Jenkins, not the lint report. I just pushed up the lint updates.

**Comment by carsonoid** [comment]
Lint passes now. Anything else needed from me?

**Comment by cachedout** [comment]
Looks good! Merged. Thanks, @carsonoid

**Pull request merged**
