### PR TITLE
Fix Homebrew Taps And Other Oddities

### PR DESCRIPTION
**Pull request by eligundry**
### What does this PR do?

Simply put, it increases the reliability of Homebrew's `pkg` module/states by accounting for it's bizarre behavior caused by it's loose naming schemes.

* Fix issue where `pkg.installed` would succeed in installing from Homebrew Cask (i.e. name = cask/caskroom/docker) but would report a failure because it wasn't in the list of installed packages.
* Fix issue where installing Homebrew package by an alias would internally succeed but report a failure because `brew list` returns the canonical name (i.e. name = npm, which installs node and reports it as such).
* Fix issues where having multiple versions of a Brew package would fail exact version matching.

### What issues does this PR fix or reference?

* https://github.com/saltstack/salt/issues/26414
* https://github.com/saltstack/salt/issues/26407 (?)

#### Casks

Given the following state on MacOS:

```yaml
docker:
  pkg.installed:
    - name: caskroom/casks/docker
```

The package will install to the system but will be reported as a failure because `brew list` won't return Casks.

#### Aliases

Given the following state on MacOS:

```yaml
npm:
  pkg.installed
```

The package this represents will be installed but will be reported as a failure because `npm` will not be returned in `brew list`. This is because `npm` is an alias for `node`, which is returned by `brew list`.

#### Full Names For Non-Casks

Given the following state on MacOS:

```yaml
php:
  pkg.installed:
    - pkgs:
      - homebrew/php/composer
      - homebrew/php/php72
```

The packages listed will be installed to the system but will be reported as failing. This is because a Brew `full_name` was provided for a regular package, but `brew list` would only return it's short name (`composer` and `php72`, respectively).

### New Behavior

All of the above issues are solved, with one caveat. Because of Homebrew's extremely flexible naming policies, every package's name, full name, and aliases are completely valid identifiers to install with `brew install`. For example, here are the keys that I am talking about for the above `npm` example.

```shell
$ brew info --json=v1 npm | jq
```
```json
{
    "name": "node",
    "full_name": "node",
    "desc": "Platform built on V8 to build network applications",
    "homepage": "https://nodejs.org/",
    "oldname": null,
    "aliases": [
        "node@9",
        "nodejs",
        "node.js",
        "npm"
    ]
}
```
(I omitted a lot of keys in this example, but you should checkout it's output, it's so detailed!)

Because `pkg.list_pkgs` doesn't know or care what name was used in `pkg.install`, I have to add all of the names to the cached packages array. That means the `pkg.list_pkgs` will return something like this for the above example:

```yaml
local:
    ----------
    node:
        9.3.0_1
    node.js:
        9.3.0_1
    node@9:
        9.3.0_1
    nodejs:
        9.3.0_1
    npm:
        9.3.0_1
```

As far as I can tell, this doesn't break anything going backwards, but the output is definitely different and repetitive, so I figured I should bring it up.

### Tests written?

No. I couldn't find any other Homebrew tests, but if they exist, I would be happy to add these to it! With that said, I have an **insane** amount of Homebrew packages that I manage with Salt in my repo and they all finally pass!

https://github.com/eligundry/salt.eligundry.com

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by gtmanfred — APPROVED** [review]
seems reasonable to me.

Thanks,
Daniel

**Review by garethgreenaway — APPROVED** [review]

**Comment by rallytime** [comment]
re-run py

**Comment by rallytime** [comment]
re-run lint

**Comment by rallytime** [comment]
Thank you @eligundry and welcome!

**Pull request merged**
