### PR TITLE
Failed to load /var/cache/salt/minion/roots/mtime_map when it contains invalid UTF-8 data

### LINKED ISSUE #60535: [BUG] Failed to load /var/cache/salt/minion/roots/mtime_map
**Description**
It seems that `mtime_map` sometimes contains invalid UTF-8 data that causes `salt.utils.files.fopen` to fail.

```
File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 2122, in cmd
    return self.sminion.functions[fun](*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/state.py", line 360, in orchestrate
    pillarenv=pillarenv,
  File "/usr/lib/python3/dist-packages/salt/runners/state.py", line 125, in orchestrate
    orchestration_jid=orchestration_jid,
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/state.py", line 1343, in sls
    initial_pillar=_get_initial_pillar(opts),
  File "/usr/lib/python3/dist-packages/salt/state.py", line 4634, in __init__
    self.client = salt.fileclient.get_file_client(self.opts)
  File "/usr/lib/python3/dist-packages/salt/fileclient.py", line 55, in get_file_client
    )(opts)
  File "/usr/lib/python3/dist-packages/salt/fileclient.py", line 1422, in __init__
    self.channel = salt.fileserver.FSChan(opts)
  File "/usr/lib/python3/dist-packages/salt/fileserver/__init__.py", line 871, in __init__
    self.fs.update()
  File "/usr/lib/python3/dist-packages/salt/fileserver/__init__.py", line 486, in update
    self.servers[fstr](**kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/fileserver/roots.py", line 161, in update
    for line in fp_:
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 1: invalid continuation byte
```

I think this is a regression of https://github.com/saltstack/salt/commit/5ea3fb2cf241bbc18656fc65752f0a92e950266d#diff-1f96c1bf1efb4edbad6f6ea24768d127521489e238b3e5ff466a1c56323257d6.

I suggest to enhance the try/catch block by adding `UnicodeDecodeError` at https://github.com/saltstack/salt/blob/master/salt/fileserver/roots.py#L159-L176. This makes sense after forcing `UTF-8` with the mentioned PR/commit above.

```
try:
    with salt.utils.files.fopen(mtime_map_path, encoding="utf-8") as fp_:
        for line in fp_:
            ...
    except (OSError, UnicodeDecodeError):
        pass
```

**Expected behavior**
If the `/var/cache/salt/minion/roots/mtime_map` is malformed related to UTF-8, i expect that decoding errors are catched and handled properly.

**Versions Report**
Salt 3003.1

**Additional context**
This error was reported by multiple users of the software which is using Salt.
- https://forum.openmediavault.org/index.php?thread/39602-error-applying-config-changes-salt-unicodedecodeerror/
- https://forum.openmediavault.org/index.php?thread/32724-cannot-install-openmediavault-5-error-setting-up-salt-environment/

### PR DESCRIPTION
**Pull request by votdev**
UTF-8 encoding was forced by https://github.com/saltstack/salt/commit/5ea3fb2cf241bbc18656fc65752f0a92e950266d, but decoding exceptions are not handled. This will be fixed by this PR.

Fixes: https://github.com/saltstack/salt/issues/60535

Signed-off-by: Volker Theile <votdev@gmx.de>

### CODE REVIEW

**Review by twangboy — DISMISSED** [review]

**Review by Ch3LL — CHANGES_REQUESTED** [review]
This will require tests and a changelog entry

**Comment by votdev** [comment]
> This will require tests and a changelog entry

Please point me to a documentation or example tests that can easily adapted for this PR. 

It's a little bit confusing that this PR requires tests, but the commit https://github.com/saltstack/salt/commit/5ea3fb2cf241bbc18656fc65752f0a92e950266d which introduces the regression doesn't have tests. With tests, the regression wouldn't have happened.

Please note that you can not expect that the community or a simple user like me is familiar with the SaltStack test framework, therefore it sometimes makes sense to forego tests when a PR like this is so trivial.

**Comment by Ch3LL** [comment]
> Please point me to a documentation or example tests that can easily adapted for this PR.

You can take a look at the current test: `test_update_mtime_map` to work from. 

> It's a little bit confusing that this PR requires tests, but the commit 5ea3fb2 which introduces the regression doesn't have tests. With tests, the regression wouldn't have happened.

We usually require tests for all bug fixes and features. There are exceptions to that rule and require 3 core team members approval in order to merge. In this case, that commit change was fixing a test that was failing on windows, so the test coverage was not added. 

> Please note that you can not expect that the community or a simple user like me is familiar with the SaltStack test framework, therefore it sometimes makes sense to forego tests when a PR like this is so trivial.

I understand adding test coverage can be difficult so I'm more than willing to write a test just let me know and I will be more than willing, but we do want to ensure this does not regress in the future before merging.

**Comment by votdev** [comment]
> > Please point me to a documentation or example tests that can easily adapted for this PR.
> 
> You can take a look at the current test: `test_update_mtime_map` to work from.
> 
> > It's a little bit confusing that this PR requires tests, but the commit [5ea3fb2](https://github.com/saltstack/salt/commit/5ea3fb2cf241bbc18656fc65752f0a92e950266d) which introduces the regression doesn't have tests. With tests, the regression wouldn't have happened.
> 
> We usually require tests for all bug fixes and features. There are exceptions to that rule and require 3 core team members approval in order to merge. In this case, that commit change was fixing a test that was failing on windows, so the test coverage was not added.
> 
> > Please note that you can not expect that the community or a simple user like me is familiar with the SaltStack test framework, therefore it sometimes makes sense to forego tests when a PR like this is so trivial.
> 
> I understand adding test coverage can be difficult so I'm more than willing to write a test just let me know and I will be more than willing, but we do want to ensure this does not regress in the future before merging.

I tried to adapt the mentioned unit test, but i'm not able to run the test locally. Please modify the test if necessary to get this regression fixed asap.

**Comment by votdev** [comment]
Could someone please assist in fixing the unit test and getting it to work?

**Comment by Ch3LL** [comment]
Can you try this: 

```    
def test_update_mtime_map_unicode_error(self):
        """
        Test that a malformed mtime_map (which causes an UnicodeDecodeError
        exception) is handled properly.
        """
        new_mtime_map = {
            "/srv/salt/große:Datei.txt": 1594263261.0616212,
        }
        with tempfile.TemporaryDirectory() as tmpdirname:
            mtime_map_path = os.path.join(tmpdirname, "roots", "mtime_map")
            os.makedirs(os.path.dirname(mtime_map_path))
            with salt.utils.files.fopen(mtime_map_path, 'wb') as fp:
                fp.write(b"\x9c")

            with patch(
                "salt.fileserver.reap_fileserver_cache_dir", MagicMock(return_value=True)
            ), patch(
                "salt.fileserver.generate_mtime_map", MagicMock(return_value=new_mtime_map)
            ), patch.dict(
                roots.__opts__, {"fileserver_events": False, "cachedir":
                                 tmpdirname},
            ):
                ret = roots.update()

        assert ret == {
            "changed": True,
            "files": {
                "changed": [],
                "removed": [],
                "added": ["/srv/salt/große:Datei.txt"],
            },
            "backend": "roots",
        }, ret
```

I confirmed this fails without your change, and passes with it.

**Comment by votdev** [comment]
> Can you try this:
> 
> ```
> def test_update_mtime_map_unicode_error(self):
>         """
>         Test that a malformed mtime_map (which causes an UnicodeDecodeError
>         exception) is handled properly.
>         """
>         new_mtime_map = {
>             "/srv/salt/große:Datei.txt": 1594263261.0616212,
>         }
>         with tempfile.TemporaryDirectory() as tmpdirname:
>             mtime_map_path = os.path.join(tmpdirname, "roots", "mtime_map")
>             os.makedirs(os.path.dirname(mtime_map_path))
>             with salt.utils.files.fopen(mtime_map_path, 'wb') as fp:
>                 fp.write(b"\x9c")
> 
>             with patch(
>                 "salt.fileserver.reap_fileserver_cache_dir", MagicMock(return_value=True)
>             ), patch(
>                 "salt.fileserver.generate_mtime_map", MagicMock(return_value=new_mtime_map)
>             ), patch.dict(
>                 roots.__opts__, {"fileserver_events": False, "cachedir":
>                                  tmpdirname},
>             ):
>                 ret = roots.update()
> 
>         assert ret == {
>             "changed": True,
>             "files": {
>                 "changed": [],
>                 "removed": [],
>                 "added": ["/srv/salt/große:Datei.txt"],
>             },
>             "backend": "roots",
>         }, ret
> ```
> 
> I confirmed this fails without your change, and passes with it.

Thanks for your help.

**Review by Ch3LL — DISMISSED** [review]

**Comment by Ch3LL** [comment]
I started writing a test for file_hash as well, and what I found is if a UnicodeDecodeError is raised it never hits the code where you are trying to catch the exception, because UnicodeDecodeError is a subclass of ValueError, so it will never hit the code you are intending it to hit. Where you also running into an error with this part of the code?

**Comment by votdev** [comment]
> I started writing a test for file_hash as well, and what I found is if a UnicodeDecodeError is raised it never hits the code where you are trying to catch the exception, because UnicodeDecodeError is a subclass of ValueError, so it will never hit the code you are intending it to hit. Where you also running into an error with this part of the code?

Which code line are we talking about? 

If i guess you are talking about line [249](https://github.com/saltstack/salt/blob/4ad175902f5a8c0f41360f28b36c319162900111/salt/fileserver/roots.py#L249) and the corresponding catch block, right? I removed the useless `UnicodeDecodeError` in this catch block. So now only the code is fixed that is mentioned in #60535.

**Review by Ch3LL — DISMISSED** [review]

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
