### PR TITLE
Adding NPM cache_cleaned state & module functions

### PR DESCRIPTION
**Pull request by dschaller**
Adding state for NPM cache cleaned. This state ensures that either the whole cache is cleaned or that a specific package is either not present or cleaned if it is.
Also, the NPM module now has cache_clean, cache_list, and cache_path functions.
- cache_clean: cleans either all packages in a specified path or the entire cache if no path is specified
- cache_list: lists either all cached packages or if a path is specified, it will list all cached packages within that path
- cache_path: prints the absolute path to the NPM cache

All added functionality has unit tests and the cache_cleaned state has additional integration tests.

### CODE REVIEW

**Comment by cachedout** [comment]
@dschaller Thanks for this! Looks like a couple of those tests aren't passing though. Could you please take another look? Let me know if there are any questions I can answer. Once those are passing, we'll do a review and hopefully get this merged. Thanks!

**Comment by dschaller** [comment]
@cachedout thanks! I have one unit test that implies there is either an error in my logic or an error in the test so I need to figure that out and then it should be good to go

**Comment by cachedout** [comment]
@dschaller Great! Keep me posted. I appreciate your work. :]

**Comment by dschaller** [comment]
@cachedout Looks like this is good to go except for the default which is failing on `GitHub commit status is ERROR`

**Comment by cachedout** [comment]
Merged! Thanks, @dschaller

**Pull request merged**
