### PR TITLE
Add the ability to specify a base pattern for carbon returner

### PR DESCRIPTION
**Pull request by MrCitron**
One can customize the path for the metrics.
E.g : 
    carbon.metric_base_pattern: carbon.[minion_id].[module].[function]

### CODE REVIEW

**Comment by jfindlay** [comment]
@MrCitron, thanks for the pull request.  Technically new features need to go into develop and the 2014.7 branch is no longer active, but we'll get this merged.

**Comment by MrCitron** [comment]
Hi @jfindlay,

actually I needed this feature in 2014.7 branch since I am still using this version.
I was planning to push the same feature to 2015.5 branch and in the develop branch.

**Comment by jfindlay** [comment]
@MrCitron, sounds good.  2014.7 has reached end of life and won't have any new releases.  Unless the code has changed significantly between branches, it shouldn't be necessary to submit multiple pull requests containing the same changes as we merge our release branches forward regularly.  Thanks.

**Comment by MrCitron** [comment]
Ok, then I will wait for my feature to be merged either in 2015.5 or 2015.8 before upgrading.
Let me know If I can help merging this code.

**Pull request merged**
