### PR TITLE
Pillar django_orm compatibility with 1.7 and above

### PR DESCRIPTION
**Pull request by claudiupopescu**
According to the docs: https://docs.djangoproject.com/en/dev/releases/1.7/#standalone-scripts

Starting with django 1.7 you must initialise django with: django.setup()
In order to avoid AppRegistryNotReady exceptions.

### CODE REVIEW

**Comment by thatch45** [comment]
The tests that are failing are doing so because of an out of memory error, it makes me worry that perhaps the django import is allocating a large amount of memory. I am going to re-run these tests to make sure, but if this is the case we may need to find a better way, perhaps a single http call requestion the version?
But first lets re-run the tests

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by claudiupopescu** [comment]
Now only setup is imported from django so let's hope the tests won't fail.

**Comment by thatch45** [comment]
Huh, still seeing the out of memory errors, can you try rebasing with the latest develop? maybe it is not related....

**Comment by claudiupopescu** [comment]
Yeah, so I didn't create a new pull request for this new issue. How would one fix this? :)

**Comment by claudiupopescu** [comment]
Closing the pull request since more testing needs to be done and by mistake I include other changes to boto into this pull.

**Pull request closed without merging**
