### PR TITLE
Loading of libcrypto on smartos esky fixed

### PR DESCRIPTION
**Pull request by sjorge**
This is a fix for issue #25757

Based on the code snipped provided by @nshalman, tested on latest smartos platform image.

### CODE REVIEW

**Comment by basepi** [comment]
This was inadvertently closed. Sorry!

**Comment by sjorge** [comment]
Do I need to create a seperate PR against develop or will this be pulled into it automatically?

**Comment by rallytime** [comment]
@sjorge Nope, you're good. We do merge-forwards every couple of days. This will get merged into develop the next time @basepi does a 2015.8 --> develop merge.

**Comment by sjorge** [comment]
Excellent.

**Pull request merged**
