### PR TITLE
Update esky smartos

### PR DESCRIPTION
**Pull request by mguegan**
### What does this PR do?
This will update instructions (.md) and script in order to build latest esky version with SmartOS (pkgsrc 2016Q4 LTS)

### What issues does this PR fix or reference?
#40227

### Previous Behavior
Won't build

### New Behavior
Building tarball is OK

### Tests written?
No

### CODE REVIEW

**Comment by sjorge** [comment]
Are you sure if it works without patchelf in the global zone? I never got it to work without it before.
Works fine without it in a native zone because all the library paths usually exists.

**Comment by mguegan** [comment]
@sjorge I have tested it briefly in development server (into GZ) 
```
[root@smartos01 /opt]# /opt/salt/bin/salt-call --version
salt-call 2016.11.3 (Carbon)
```
In fact, `patchelf` is still used by `bbfreeze` and will be applied during the build. I only removed it for the `console.exe`. 

I'll do some test in production next week, but if you can check on your side, it would be nice !

Thanks !

**Comment by sjorge** [comment]
@mguegan neat! I was having a lot of issues on 2016Q4 on getting the esky stuff compile, I sort of gave up on it and started providing a pkgsrc package for the gz-tools bootstrap.

But if it still works, that also great. I'll give building it another go tomorrow.

**Comment by mguegan** [comment]
@sjorge : I should have done more testing : `salt-master` and `salt-minion` were failing due to some cython `*.so` files badly linked. I just upload a fix which seems to be running on the GZ. I did a master / minion test before submitting it. Anyway, you can grab my tarball [here](https://repository.virtua.ch/smartos/salt-2016.11.3-esky-smartos.tar.gz).

**Comment by sjorge** [comment]
@mguegan looking good, it applies all my states

```
[root@mantle /tmp]# /tmp/salt/bin/salt-call -c /opt/tools/etc/salt/ state.apply
local:
  Name: smartos.scrub::schedule-zones - Function: schedule.present - Result: Clean Started: - 21:39:27.575070 Duration: 24.282 ms
  Name: smartos.monitoring::schedule-fmadm - Function: schedule.present - Result: Clean Started: - 21:39:27.599675 Duration: 16.899 ms
  Name: smartos.monitoring::schedule-zpool - Function: schedule.present - Result: Clean Started: - 21:39:27.616898 Duration: 18.315 ms
  Name: hostname - Function: smartos.config_present - Result: Clean Started: - 21:39:27.638236 Duration: 2.733 ms
  Name: dns_domain - Function: smartos.config_present - Result: Clean Started: - 21:39:27.641516 Duration: 2.422 ms
  Name: dns_resolvers - Function: smartos.config_present - Result: Clean Started: - 21:39:27.644231 Duration: 1.418 ms
  Name: ntp_conf_file - Function: smartos.config_absent - Result: Clean Started: - 21:39:27.645937 Duration: 1.388 ms
  Name: ntp_hosts - Function: smartos.config_present - Result: Clean Started: - 21:39:27.647610 Duration: 1.39 ms
  Name: root - Function: user.present - Result: Clean Started: - 21:39:27.650878 Duration: 6.379 ms
  Name: root_authorized_keys_file - Function: smartos.config_present - Result: Clean Started: - 21:39:27.657559 Duration: 1.494 ms
  Name: AAAAB3NzaC1yc2EAAAABIwAAAQEA7st+KRfqBdNGhyEDBxzssIv9xVH7yl5fMOUVHLk1VTmpOyCpYi/+yI2QsMIdndFqWK7rM4xgCK+osKP2kj/edy7FTzi78c6vP3Jli+Dt17ZgC/CxlEReJe+o0/l1tdWbl+kg9nB0DtGMSvntFcIdQmn5ZiPOzGrLKvI9Tngt0BWLrYXlQzBkq65MBbizoxkErR4nHppt9mLeTR9ZY6YsRi2roVVNUJWKat/RvC6ncPs4+Mpy56330MA+40cGlFFlucQnlzIx6ghey13P+RdZYuexJP6JunyZOntCcieahNJ+FklCEeeVChhjO0tFtioz49udCEOxo9kmfDUOiqi61w== - Function: ssh_auth.present - Result: Clean Started: - 21:39:27.660285 Duration: 11.276 ms
  Name: admin_nic - Function: smartos.config_present - Result: Clean Started: - 21:39:27.672193 Duration: 2.698 ms
  Name: admin_ip - Function: smartos.config_present - Result: Clean Started: - 21:39:27.675431 Duration: 2.698 ms
  Name: admin_netmask - Function: smartos.config_present - Result: Clean Started: - 21:39:27.678665 Duration: 2.672 ms
  Name: admin_gateway - Function: smartos.config_present - Result: Clean Started: - 21:39:27.681867 Duration: 2.215 ms
  Name: admin_ip6 - Function: smartos.config_present - Result: Clean Started: - 21:39:27.684365 Duration: 1.375 ms
  Name: storage_nic - Function: smartos.config_present - Result: Clean Started: - 21:39:27.686023 Duration: 1.387 ms
  Name: storage_mtu - Function: smartos.config_present - Result: Clean Started: - 21:39:27.687718 Duration: 1.396 ms
  Name: storage0_ip - Function: smartos.config_present - Result: Clean Started: - 21:39:27.689395 Duration: 1.381 ms
  Name: storage0_netmask - Function: smartos.config_present - Result: Clean Started: - 21:39:27.691058 Duration: 1.375 ms
  Name: storage0_ip6 - Function: smartos.config_present - Result: Clean Started: - 21:39:27.692713 Duration: 1.561 ms
  Name: storage0_vlan_id - Function: smartos.config_present - Result: Clean Started: - 21:39:27.694706 Duration: 2.815 ms
  Name: external_nic - Function: smartos.config_present - Result: Clean Started: - 21:39:27.698127 Duration: 2.766 ms
  Name: external_mtu - Function: smartos.config_present - Result: Clean Started: - 21:39:27.701436 Duration: 2.772 ms
  Name: trunk0_aggr - Function: smartos.config_present - Result: Clean Started: - 21:39:27.704794 Duration: 1.817 ms
  Name: trunk0_mtu - Function: smartos.config_present - Result: Clean Started: - 21:39:27.706920 Duration: 1.464 ms
  Name: trunk0_lacp_mode - Function: smartos.config_present - Result: Clean Started: - 21:39:27.708698 Duration: 1.455 ms
  Name: trunk_nic - Function: smartos.config_present - Result: Clean Started: - 21:39:27.710440 Duration: 1.438 ms
  Name: /root/.profile - Function: file.managed - Result: Clean Started: - 21:39:27.716609 Duration: 54.749 ms
  Name: /root/.inputrc - Function: file.managed - Result: Clean Started: - 21:39:27.771983 Duration: 32.751 ms
  Name: /root/.vimrc - Function: file.managed - Result: Clean Started: - 21:39:27.805306 Duration: 34.486 ms
  Name: 05140a7e-279f-11e6-aedf-47d4f69d2887 - Function: smartos.image_present - Result: Clean Started: - 21:39:27.840357 Duration: 955.49 ms
  Name: 32de63f8-8b6f-11e6-beb6-b3e46c186cc2 - Function: smartos.image_present - Result: Clean Started: - 21:39:28.797083 Duration: 927.367 ms
  Name: 1f32508c-e6e9-11e6-bc05-8fea9e979940 - Function: smartos.image_present - Result: Clean Started: - 21:39:29.725127 Duration: 932.678 ms
  Name: 08589eda-d64e-11e6-89a3-0b55371be927 - Function: smartos.image_present - Result: Clean Started: - 21:39:30.658460 Duration: 926.346 ms
  Name: zones/data - Function: zfs.filesystem_present - Result: Clean Started: - 21:39:31.591769 Duration: 272.035 ms
  Name: zones/data/apollo - Function: zfs.filesystem_present - Result: Clean Started: - 21:39:31.870384 Duration: 269.212 ms
  Name: zones/data/cronos - Function: zfs.filesystem_present - Result: Clean Started: - 21:39:32.144699 Duration: 267.273 ms
  Name: exosphere - Function: smartos.vm_present - Result: Clean Started: - 21:39:32.413149 Duration: 2369.65 ms
  Name: apollo - Function: smartos.vm_present - Result: Clean Started: - 21:39:34.783436 Duration: 2329.759 ms
  Name: cronos - Function: smartos.vm_present - Result: Clean Started: - 21:39:37.113932 Duration: 2304.087 ms
  Name: eris - Function: smartos.vm_present - Result: Clean Started: - 21:39:39.418681 Duration: 2358.583 ms
  Name: states - Function: grains.present - Result: Clean Started: - 21:39:41.779718 Duration: 2.02 ms
  Name: salt:minion - Function: service.running - Result: Clean Started: - 21:39:41.783466 Duration: 938.918 ms
  Name: /usbkey/salt/minion - Function: file.managed - Result: Clean Started: - 21:39:42.723627 Duration: 59.824 ms
  Name: /usbkey/salt/minion.d - Function: file.directory - Result: Clean Started: - 21:39:42.783882 Duration: 3.062 ms
  Name: /usbkey/salt/minion.d/smtp.conf - Function: file.managed - Result: Clean Started: - 21:39:42.790039 Duration: 226.201 ms
  Name: salt.minion::schedule-apply - Function: schedule.present - Result: Clean Started: - 21:39:43.016586 Duration: 18.914 ms
  Name: zfs.snapshot::scheduler - Function: schedule.present - Result: Clean Started: - 21:39:43.036106 Duration: 24.109 ms
  Name: /opt/custom/svc/nethacks-ipv6 - Function: file.managed - Result: Clean Started: - 21:39:43.060725 Duration: 9.639 ms
  Name: /opt/custom/smf/nethacks.xml - Function: file.managed - Result: Clean Started: - 21:39:43.073934 Duration: 5.812 ms
  Name: svccfg import /opt/custom/smf/nethacks.xml - Function: cmd.wait - Result: Clean Started: - 21:39:43.085377 Duration: 1.034 ms
  Name: salt.minion::restarter - Function: at.watch - Result: Clean Started: - 21:39:43.095266 Duration: 1.159 ms

Summary for local
-------------
Succeeded: 53
Failed:     0
-------------
Total states run:     53
Total run time:   15.446 s
```

**Comment by cachedout** [comment]
@mguegan and @sjorge is this all ready to go from your perspective?

**Comment by sjorge** [comment]
minion/salt-call work for me, never ran a master in the global zone, so did not test that. 

But Everything looks good to me.

**Comment by mguegan** [comment]
@cachedout @sjorge I did a test with salt-master / salt-minion in the GZ and I could do a test.ping. I think it's ready to merge. But if you would like to wait a couple of days (one week), I could test it in a production environment.

**Comment by sjorge** [comment]
Most issues with the Esky stuff shows up when it tries to load some of the shared objects, probably using something that uses some of th crypto triggers most crashes. I'd say if my minion and salt-call test could talk to a master most of those for hit. Same with your master test.

**Comment by cachedout** [comment]
This looks like it is ready to go to me. Thanks @mguegan and @sjorge

**Comment by nshalman** [comment]
Amazing that this stuff still works! Thanks for saving my work from the indignities of bitrot!

**Pull request merged**
