### PR TITLE
Fix broken pip state test

### PR DESCRIPTION
**Pull request by dwoz**
### What does this PR do?

Fixing test failure found [here](https://jenkinsci.saltstack.com/job/pr-kitchen-ubuntu1604-py2/job/PR-52705/27/testReport/junit/unit.states.test_pip_state/PipStateTest/test_install_requirements_parsing/)

### Tests written?

No - Fixing existing test

### Commits signed with GPG?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by dwoz** [comment]
re-run full all

**Comment by dwoz** [comment]
re-run full all

**Review by s0undt3ch — APPROVED** [review]

**Comment by dwoz** [comment]
Please wait for the full test runs to finish before merging:

re-run full all

**Comment by dwoz** [comment]
Please wait for the full test runs to finish before merging:

re-run full all

**Comment by dwoz** [comment]
re-run debian

**Comment by dwoz** [comment]
Please wait for the full test runs to finish before merging:

re-run full all

**Comment by dwoz** [comment]
re-run all

**Review by s0undt3ch — APPROVED** [review]

**Pull request merged**
