### PR TITLE
git.latest: add auth to merge/reset calls when LFS used with SSH auth

### LINKED ISSUE #51255: git.latest smudge filter failed to update lfs tracked objects
### Description of Issue/Question
git.latest is failed to download the latest version or the file tracked by LFS. 
1. First download of LFS tracked file works. 
2. Other text file are updated as per repo. 
ERROR: 
Downloading test_binary_file (24 B)
              Error downloading object: test_binary_file (4cf7033): Smudge error: Error downloading test_binary_file (4cf7033562783a50dc185a66bd535eb66002b3aad946e255c1d458b6d04694d6): batch request: Permission denied (publickey).: exit status 255
Errors logged to /opt/management-agent/.git/lfs/logs/20190121T004633.928000968.log
              Use `git lfs logs last` to view the log.
              error: external filter git-lfs smudge -- %f failed 2
              error: external filter git-lfs smudge -- %f failed
              fatal: test_binary_file: smudge filter lfs failed

Errors out as Permission denied (publickey), but the same key is used to update the files when manually run. `sudo ssh-agent sh -c 'ssh-add /root/.ssh/gitlab_id_rsa; git fetch; git reset --hard; git pull'`

### Setup
```
git.latest:
    - name: {{ iotransit.management_agent_repo }}
    - rev: {{ iotransit.branch_commit }}
    - branch: {{ iotransit.branch_commit }}
    - target: /opt/management-agent
    - force_reset: True
    - force_checkout: True
    - force_fetch: True
    - fetch_tags: True
    - identity: {{ iotransit.gitlab_id_rsa }}
    - require:
      - file: iotransit_private_key
      - pkg: iotransit_gitlfs_install
      - cmd: iotransit_initialize_gitlfs
```

### Steps to Reproduce Issue
update the binary file in the repo and the above salt state fails as it couldnt update the LFS tracked files
### Versions Report
salt-master versions report: 
```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.0-1065-aws
         system: Linux
        version: Ubuntu 16.04 xenial

salt-minion version:
salt-minion 2018.3.3 (Oxygen)
```

### PR DESCRIPTION
**Pull request by terminalmage**
In these cases, if the commands are not auth'ed then the git LFS subcommands don't know which identity file to use and will fall back to the one from `~/.ssh/config`. By ensuring that the command is auth'ed, the LFS subcommands are able to download files when needed.

Normally we don't need to auth to the remote repo for this, since we have made sure that we already have the needed objects downloaded, and that is why these commands were not auth'ed before.

Also, this fixes a bunch of external links that were broken. When I initially added those external links they were correct, but included a URL-encoded space (i.e. `%20`). In the intervening weeks/months/etc. the URL-encoded space seems to have been replaced by an underscore, so the links in our docs were out-of-date.

Resolves #51255.

### CODE REVIEW

**Review by s0undt3ch — APPROVED** [review]

**Comment by s0undt3ch** [comment]
Test failures seem related to the changes.

**Comment by terminalmage** [comment]
Should be fixed now. I had added a check in the global gitconfig for the lfs filter settings that get added when you initialize the LFS plugin. But I told it to run the command from the local path where the repo has been cloned. But, if the repo has never been cloned before (as in the case of the integration tests), that directory does not yet exist.

Since the config check only needs the global config, the cwd is actually not important.

**Comment by s0undt3ch** [comment]
One last test failure.

**Comment by terminalmage** [comment]
OK, that last one should now be fixed.

**Review by s0undt3ch — APPROVED** [review]

**Pull request merged**
