### PR TITLE
[cherrybomb] MTecknology's Masterless Contributions

### PR DESCRIPTION
**Pull request by MTecknology**
### What does this PR do?

:musical_note: Hello Salt. Hello Friends. Here's your... ch-ch-ch-cherry bomb! :musical_note:

This PR cherry-picks of all my previously-accepted PRs which have not been merged from ``develop`` to ``master`` and do not appear to be part of any current merge effort. These previously accepted PRs are also present in the [PRs to port to master](https://github.com/saltstack/salt/projects/5) project board and have been (personally) reviewed for current relevancy/accuracy.

The two areas of salt impacted by these changes are: ['Documentation', 'Debian Networking]

### What PRs* does this PR fix or reference?

- #50070
- #49962
- #49940
- #49906
- #49887
- #49843
- #49462
- #49355

### Tests included*?

Yes; I may have gotten a tiny bit carried away with creativity, but I also tried to break my own code and documented even the silly attempts as tests.

### Commits signed with GPG?

Yes, absolutely.

### CODE REVIEW

**Comment by MTecknology** [comment]
Okay! This /should/ be the last change. I expect every single test to pass with absolute perfection, because there's absolutely no other possible outcome! :D

**Comment by MTecknology** [comment]
Okay! This /should/ be the last change. I expect every single test to pass with absolute perfection, because there's absolutely no other possible outcome! :D

**Comment by dwoz** [comment]
@MTecknology Thank you for doing this.

**Review by waynew — COMMENTED** [review]
@MTecknology thanks for the port PR! 🎉 

Just one question on it, but otherwise it looks good to *me* 👍

**Review by waynew — DISMISSED** [review]
Tests definitely fail when the Debian IP code was reverted, and they pass when the Debian IP changes were re-applied 👍

**Comment by Ch3LL** [comment]
looks like there are some merge conflicts that need to be resolved and pre-commit is failing.

**Comment by MTecknology** [comment]
There's nothing I can do about the pre-commit thing. That looks like it didn't find the revision it was looking for.

This has been sitting around untouched for nearly a month. If I fix the merge conflicts, will the changes be merged before it needs to happen again? Should I wait to fix the conflicts?

**Comment by MTecknology** [comment]
This is going to be a very non-trivial merge and will likely take me many hours (or days) to work through. I need to know that this will be merged before I put in the effort... again.

**Comment by waynew** [comment]
@MTecknology I just opened a PR against your branch that *should* address any of the questionable conflicts here.

I got my changes by doing this:

```
git fetch salt master
git checkout salt/master
git fetch salt refs/pull/56353/head
git checkout FETCH_HEAD -- doc/ref/states/requisites.rst doc/topics/releases/3000.rst salt/modules/debian_ip.py salt/renderers/gpg.py salt/states/file.py salt/templates/debian_ip/debian_eth.jinja tests/unit/modules/test_debian_ip.py
git add .
pre-commit run isort  # fix any issues, git add . and  re-run
pre-commit run black  # fix any issues, re-run isort and then black
git commit  # fix any lint issues
```

I would keep a branch name pointing to this cherry bomb commit but my PR *should* solve any code formatting disagreements on this PR :crossed_fingers:

**Comment by waynew** [comment]
I guess Jenkins failed to report this success: https://jenkinsci.saltstack.com/job/pr-macosxmojave-py3/job/PR-56353/25/

**Comment by waynew** [comment]
Fixed the merge conflicts (since I was responsible for them :trollface: )

Let's see if it works this time!

**Review by waynew — APPROVED** [review]

**Pull request merged**
