### PR TITLE
FIX#53244/s3fs cache file exception

### LINKED ISSUE #53244: [python3] Uncaught exception while updating s3fs fileserver cache
### Description of Issue/Question

During startup, the following error appears:
```
[ERROR   ] Uncaught exception while updating s3fs fileserver cache
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/salt/master.py", line 459, in _do_update
    update_func(*args)
  File "/usr/lib/python3.7/site-packages/salt/fileserver/s3fs.py", line 126, in update
    metadata = _init()
  File "/usr/lib/python3.7/site-packages/salt/fileserver/s3fs.py", line 366, in _init
    metadata = _refresh_buckets_cache_file(cache_file)
  File "/usr/lib/python3.7/site-packages/salt/fileserver/s3fs.py", line 551, in _refresh_buckets_cache_file
    pickle.dump(metadata, fp_)
TypeError: write() argument must be str, not bytes
```

### Setup

Relevant part of master config:
```yml
s3:
  keyid: myuser
  key: mykey
  buckets:
    base:
      - mybucket
  service_url: minio.example.com
  path_style: True
  https_enable: True

fileserver_backend:
  - rootfs
  - s3fs
```

### Steps to Reproduce Issue

Install salt-master (latest, on alpine edge, with python3.7).
Set up s3 (as per above).
Run `salt-master`.

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.28.1
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.28.1
         Python: 3.7.3 (default, Apr 17 2019, 11:48:37)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.19.41-0-vanilla
         system: Linux
        version: Not Installed
```

Some minions are on version 2018.3.3 (latest non-edge), but we don't really get to that point.
Apologies on the edit spam - I accidentally clicked "enter" while writing the bug title, and figured it'd be less invasive to simply edit rather than close and open a new one.

### PR DESCRIPTION
**Pull request by natemellendorf**
### What does this PR do?
Opens the cache_file in binary format, as bytes are returned in Python3.
Referenced: https://github.com/saltstack/salt/blob/5949f05e23d91622c0fd9f239af58a8f3abd1044/salt/pillar/s3.py#L409

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/53244

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [X] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

#### Notes:
Open cache_file in binary format, as bytes are returned.
Could be placed inside a try statement, if desired.

After reading and following the contributing guide, I opened this PR and removed the original I created.

### CODE REVIEW

**Comment by natemellendorf** [comment]
@dwoz Thank you for tagging this with needing a test case.

With the edit being so minor, I jumped into Salts unit tests to see if I can make that slight modification. However, I’m having trouble finding the test case for this S3 backend. I would expect to see it [here](https://github.com/saltstack/salt/tree/master/tests/unit/fileserver).

Is it possible that I’m searching in the wrong directory?

**Comment by DmitryKuzmenko** [comment]
@natemellendorf I see this is a minor change and yes you're right we have not any tests for s3fs fileserver module. But learning our previous experience currently we can't accept any little thing that's not covered with a test. The requirements for such small changes are minimal: the test should cover the code to check it works on all platforms CI runs on and to ensure this change will not be regressed in the future. So a good example could be the gitfs test `tests/unit/fileserver/test_gitfs.py`. All you need is mock external calls and ensure the test will reach your code.
Thank you for understanding.

**Comment by oeuftete** [comment]
@natemellendorf @DmitryKuzmenko @jerem991 I've opened yet another PR to fix this, including a unit test to cover the cache problem: #57402.

**Comment by natemellendorf** [comment]
@oeuftete Perfect! Thank you much! I’ll close this PR then. Well done!

**Pull request closed without merging**
