### PR TITLE
check for exception in ret['comment'] in highstate

### LINKED ISSUE #25920: Check ret comment type
on master latest.
in salt/output/highstate.py the _format_host needs to check if ret['comment'] is of an exception type not only assume it is a string.

### PR DESCRIPTION
**Pull request by jfindlay**
Fixes #25920.

### CODE REVIEW

**Comment by cachedout** [comment]
This doesn't make a lot of sense to me. Is there a state module that's actually assigning an exception to a comment key in a return? I'm struggling to figure out how this is even happening to begin with.

**Comment by jfindlay** [comment]
@cachedout, ask @jmdcal.

**Comment by jmdcal** [comment]
Yes, this happened when there is an error in using some state. I think it was artifactory connect failed or git checkout failed, in any case an error condition using the network in some state/module.  Suffice to say that not all modules return strings in comments! Will have to look into it again. I don't have much time right now to go back and look for what caused it. Sorry.

**Comment by jfindlay** [comment]
@jmdcal, no problem, sorry to bug you about it.  A better approach will be to fix the artifactory state.  I'll look into doing that, thanks.

**Comment by cachedout** [comment]
If a state is assigning an exception to a comment we need to fix that instead of doing this. I would prefer that we find the root cause of this problem instead of patching it in this way.

**Comment by jfindlay** [comment]
@jmdcal, if you find the specific comment that was being returned as an exception, let me know and we'll track it down.  I have looked through the artifactory and git states and didn't find anything that wasn't a string except one case in artifactory which was a `None`.

**Comment by jmdcal** [comment]
ok, then will do, fine with me.

**Pull request closed without merging**
