### PR TITLE
Enhanced wait_for_successful_query with request_interval

### PR DESCRIPTION
**Pull request by daxroc**
### What does this PR do?
Enhancement to wait_for_successful_query to add an optional delay requests by a defined interval to reduce the number of requests made.

### CODE REVIEW

**Review by cachedout — APPROVED** [review]
Looks good. This should be ready to go after the automated tests finish running.

**Review by cachedout — CHANGES_REQUESTED** [review]
Whoops, looks like the linter caught some mixed spaces and tabs:

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/7977/violations/file/salt/states/http.py/

If you could fix those up, then we could get this in.

**Comment by daxroc** [comment]
Thanks, Let me know if there is anything else outstanding.

**Comment by cachedout** [comment]
Nope, we're set. All merged. Thanks very much, @daxroc

**Pull request merged**
