### PR TITLE
Migrate changelog snippets and release notes to markdown

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title

### CODE REVIEW

**Review by barbaricyawps — DISMISSED** [review]
Nice! Looks good to me. Have you tested whether it builds correctly in the docs? I think there are a few changes that need to be in the configuration (or possibly adding an extension) to get it to work. Is that included in this commit?

**Comment by s0undt3ch** [comment]
> Nice! Looks good to me. Have you tested whether it builds correctly in the docs? I think there are a few changes that need to be in the configuration (or possibly adding an extension) to get it to work. Is that included in this commit?

There's definitely some issues with the rendered release notes....

image

Moving PR to draft.

**Comment by s0undt3ch** [comment]
[docs.tar.gz](https://github.com/saltstack/salt/files/10726738/docs.tar.gz)

Rendering issues addressed.

**Review by twangboy — DISMISSED** [review]

**Review by Ch3LL — CHANGES_REQUESTED** [review]
Will PR submitters need to include the `.md` file extension now? If so, we need to update the documentation.

**Comment by s0undt3ch** [comment]
> Will PR submitters need to include the `.md` file extension now? If so, we need to update the documentation.

Yes, they will, and pre-commit will tell them that.

**Comment by s0undt3ch** [comment]
Which doc?

**Comment by s0undt3ch** [comment]
Docs updated and also the `changelog` target for nox.

**Comment by s0undt3ch** [comment]
Failing build has nothing to do with the changes and review comments have been addressed. Merging.

**Pull request merged**
