### PR TITLE
Correctly identify TurnKey Linux as a Debian derivative (grains)

### PR DESCRIPTION
**Pull request by dafyddj**
### What does this PR do?
Amends the core grains to correctly identify TurnKey Linux as a Debian derivative (os_family: Debian). 

### What issues does this PR fix or reference?
NA
### Previous Behavior
Pkg module doesn't work. e.g.
```
$ salt-call -l debug pkg.install certbot
...
[DEBUG   ] Could not LazyLoad pkg.install: 'pkg.install' is not available.
'pkg.install' is not available.
```

### New Behavior
Pkg module works.

### Tests written?

No

### Commits signed with GPG?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by gtmanfred** [comment]
@saltstack/team-core can yall review this?

Request from #slack

**Comment by gtmanfred** [comment]
probably should also be backported.

**Review by thatch45 — APPROVED** [review]

**Review by terminalmage — APPROVED** [review]
Yes, this should be backported. In the meantime @dafyddj, you can use the [`providers`](https://docs.saltstack.com/en/latest/ref/configuration/minion.html#providers) option in the minion config file to manually set the `pkg` virtual module on those boxes:

```yaml
providers:
  pkg: aptpkg
```

**Comment by terminalmage** [comment]
Backported in https://github.com/saltstack/salt/pull/51599.

**Pull request merged**
