### PR TITLE
fix various bugs in augeas modules

### LINKED ISSUE #29842: Various bugs in augeas execution and state modules
- Using `augeas.change` without supplying the `context` as in the following example will generate an exception:

```
redis-conf:
  augeas.change:
    - changes:
      - set /files/etc/redis/redis.conf/bind 0.0.0.0
```

Exception
```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 1594, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1491, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 42, in func_globals_inject
    yield
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1491, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/states/augeas.py", line 191, in change
    result = __salt__['augeas.execute'](context=context, lens=lens, commands=changes)
  File "/usr/lib/python2.6/site-packages/salt/modules/augeas_cfg.py", line 138, in execute
    aug.add_transform(lens, re.sub('^/files', '', context))
  File "/usr/lib64/python2.6/re.py", line 151, in sub
    return _compile(pattern, 0).sub(repl, string, count)
TypeError: expected string or buffer
```

- If a context is set and user still uses the full path, context is appended to the change duplicating
the path.

`set: {'path': "/files/etc/redis/redis.conf/files/etc/redis/redis.conf/bind'", 'value': '0.0.0.0'}`

Of course when that is sent to the underlying liberary it will generate an error as the path will not be found.

- When invalid change options are set, it will raise an exception instead of handling that and returning an error message.

Exception

```
2015-12-18 09:29:30,139 [salt.state       ][ERROR   ][24362] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 1594, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1491, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib64/python2.6/contextlib.py", line 34, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.6/site-packages/salt/utils/context.py", line 42, in func_globals_inject
    yield
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1491, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/states/augeas.py", line 191, in change
    result = __salt__['augeas.execute'](context=context, lens=lens, commands=changes)
  File "/usr/lib/python2.6/site-packages/salt/modules/augeas_cfg.py", line 149, in execute
    cmd, arg = command.split(' ', 1)
ValueError: need more than 1 value to unpack
```

- Tests require improvement as the above could not be picked up with the current single test.

### PR DESCRIPTION
**Pull request by akissa**
fix various bugs in augeas modules

add more tests

Fixes #29842

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @akissa There are a few minor lint error here. Could you please have a look?

**Comment by akissa** [comment]
@cachedout picked that up, i have submitted the fixes.

**Comment by akissa** [comment]
Rebasing seems to have messed up the commits in the PR, closing and will resubmit a clean one.

**Comment by akissa** [comment]
Resubmitted as https://github.com/saltstack/salt/pull/29851

**Pull request closed without merging**
