### PR TITLE
Update cffi to 1.14.4

### PR DESCRIPTION
**Pull request by krionbsd**
### What does this PR do?
Update cffi to 1.14.4

### CODE REVIEW

**Review by s0undt3ch — DISMISSED** [review]
@bryceml , @Ch3LL : this will not raise any issues with tiamat right?

**Comment by s0undt3ch** [comment]
re-run all

**Comment by s0undt3ch** [comment]
The above question still needs to be answered

**Review by Ch3LL — APPROVED** [review]

**Comment by bryceml** [comment]
I'm not sure unless we tried building a tiamat package with it.  My guess is it's probably fine.

**Pull request merged**
