### PR TITLE
Refactoring random.org module to use salt.utils.http instead of requests

### PR DESCRIPTION
**Pull request by garethgreenaway**
Refactoring random.org module to use salt.utils.http instead of requests

### CODE REVIEW

**Comment by rallytime** [comment]
@garethgreenaway Can you grab the pylint error here? https://jenkins.saltstack.com/job/salt-pr-lint-n/6300/violations/file/salt/modules/random_org.py/

Also there were some `unit.utils.random_org_test` failures that are likely related here, but I didn't look close enough to tell if that was just because of the pylint error or not.

**Comment by garethgreenaway** [comment]
Missed that check in the virtual method, I'll fix that and take a look at why the tests are failing.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by garethgreenaway** [comment]
These tests are passing locally.

**Comment by garethgreenaway** [comment]
The tests specific to the random_org module are now passing, others not related are failing.

**Comment by rallytime** [comment]
Thanks @garethgreenaway. Jenkins is having a tough time again and I'm looking into it. I think these are likely unrelated.

**Pull request merged**
