### PR TITLE
Exception handling in vault module

### PR DESCRIPTION
**Pull request by beornf**
### What does this PR do?
Adds behaviour to handle all exceptions in the vault module meaning jinja templates can be used without breaking.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/44243

### Previous Behavior
Exceptions are raised that causes sls rendering to sometimes fail.

### New Behavior
Exceptions are logged and execution of sls templates can continue.

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by rallytime** [comment]
@beornf There's a lint error on this change: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/20627/violations/file/salt/modules/vault.py/

**Comment by cachedout** [comment]
I'm not sure this is the right place for this fix. Many modules raise exceptions, as they should be able to, and they should be handled appropriately. IMHO, this should be fixed inside of the jinja renderer instead.

I'd also like @terminalmage to weigh in on this.

**Review by terminalmage — COMMENTED** [review]
@cachedout I think that the reasoning is that Jinja provides no means of performing a try/except (at least none of which I know). I'm not sure there's even a way to fix this inside the Jinja renderer, given that the exception would be generated within jinja itself, at runtime.

**Review by cachedout — APPROVED** [review]
Approved after talking to @terminalmage

**Comment by gpaggi** [comment]
@beornf / @cachedout this doesn't look like a good idea to me.

In case Vault is unavailable for any reason, Jinja will render the string None in place of the secret. This caused a production incident where passwords were replaced by None and the rendered config file was hot-reloaded by the database (Clickhouse), causing connections to fail.

Have you considered making this behavior configurable? default_none=True, or something like that?
Silently swallowing and ignoring exceptions while rendering a template it's not safe.
For the time being I switched to a self-written Vault module.

**Comment by cachedout** [comment]
@gpaggi Sorry to hear of the production issue. :-/ TBH, I don't remember the specifics of the conversation with @terminalmage as it was a long time ago and I'm not totally sure why we agreed on this approach.

IMHO, a revert of this commit would be reasonable to return to the previous behavior and a new option could then be introduced to continue to render the template even if errors were encountered.

**Comment by beornf** [comment]
@gpaggi Sorry I didn't expect this would happen. I added checks for secrets to ensure they aren't None in Jinja which is extra work and shouldn't be necessary by the principle of least astonishment.

**Comment by terminalmage** [comment]
Yeah, I think it makes sense to treat this like pillar.get works, when `pillar_raise_on_missing` is set. By default we can raise, but an added argument called `default` can be used to suppress the error and return some other value.

**Comment by terminalmage** [comment]
I just opened a pull request, let me know what you think: https://github.com/saltstack/salt/pull/56311

**Pull request merged**
