### PR TITLE
Add postgres init data dir support

### PR DESCRIPTION
**Pull request by akissa**

### CODE REVIEW

**Comment by cachedout** [comment]
Great! Thanks as always, @akissa

**Comment by ticosax** [comment]
HI @akissa, on some distros (like ubuntu, debian) `initdb` is not in the `$PATH` and is provided by
`postgresql-9.x.deb` package which is the server.

I leads to two issue:
  1. I'm not interested in installing server side pg dependencies to manage our databases. Client utils should be enough.
  1. I must now declare manually `/usr/lib/postgresql/9.4/bin/` to be in the `$PATH`. Or `which('initdb')` should be run by `postgres` user, so the executable can be found.

Is it possible to move `datadir_init` to its own execution module ? so users like me can still provision pg databases without the pain point aforementioned ? 
Do you have something else to suggest ?

**Comment by akissa** [comment]
@ticosax The above pull request should fix the issue.

**Comment by ticosax** [comment]
@akissa Thank you for the quick response. #31310 should do the trick.

**Pull request merged**
