### PR TITLE
Thread safe loader 2018.3.3

### PR DESCRIPTION
**Pull request by smarsching**
This is a new version of #48598 that is now based against the 2018.3.3 branch. I made a few modifications that might fix (at least some of) the test failures we see in the original PR.

I only created this PR so that I can run Jenkins on my changes. When testing changes locally, I get sporadic errors that do not really seem to be related to my changes (the same code sometimes runs and sometimes fails). I want to debug things in a well-defined environment so that I can concentrate on what effects certain changes have...

I do not intend this PR to be merged and will close it in favor of #48598 once I have finished my tests.

### CODE REVIEW

**Review by isbm — CHANGES_REQUESTED** [review]
This has to be rebased/cherrypicked instead.

**Comment by smarsching** [comment]
@isbm: Sure, I will create a proper PR with my changes neatly squashed into one commit as soon as I have figured out what's causing the problems.

I started this try out on the 2018.3.3 branch, but then decided to switch develop because it seemed like Jenkins was not running the tests at all and I though that it might work with the develop branch. Seems like even with that branch, the tests do not run at all in the Ubuntu 16.04 test environment. 

Incidentally, I also use a Ubuntu 16.04 VM for my test environment and the fact that I am having funny problems in that environment was the main reason why I created this PR in the first place (to have a playground where I can test various approaches without having to worry about a working test environment).

**Comment by mattp-** [comment]
👍 👍

**Comment by cachedout** [comment]
Really glad to see this, @smarsching. We want to be very focused on getting this in as soon as we can. I sincerely apologize for the ridiculous delay on this. It's our fault and we appreciate you sticking with us. :)

**Comment by smarsching** [comment]
Just so that you know: I found the solution to why my changes caused so many problems and an elegant fix for these problems.

Now, I have to clean up my branch (it got really messy from trying so many different things), and the I will force-push this changes to the branch referenced by this PR.

I will keep the branch based against 2018.3.3 (as I need a patch for that version for internal use anyway), but from that point it should be pretty straight forward of porting the changes to the develop branch.

I cannot promise that I will get this done today (its already 7 pm around here), but if not you can expect to have the cleaned up version by tomorrow.

**Comment by isbm** [comment]
@smarsching that is very cool. Looking forward for your final PR!

**Comment by smarsching** [comment]
From my point of view, the code is complete, but Jenkins did not run the tests (most likely because now it is again based on 2018.3.3). Therefore, I created a new PR #50655 that is now based on develop. Let's see whether the tests run now or whether there are still some problems.

**Pull request closed without merging**
