### PR TITLE
fix: Fedora configuration fails because the sysctls don't exist

### PR DESCRIPTION
**Pull request by joshland**
### What does this PR do?

Fixes a situation where bridge configuration fails on Fedora boxes.

### Previous Behavior
sysctl's don't exist, and the salt calls to set the sysctl raised an uncaught exception.

### New Behavior
Attempt to call the sysctls, log a warning if it fails, keep going with the config changes.

### Tests written?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
@joshland Could you please fix the lint errors that were detected in this test? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/13115/violations/file/salt/modules/rh_ip.py/

**Comment by joshland** [comment]
yeah, no problem.  I couldn't seem to locate the correct lint failure report.  I'll get these fixed shortly.

**Comment by joshland** [comment]
Do you have an opinion on the fitness of this?  The central issue is that you _must_ load the module 'br_netfilter' if you want to use the bridge filter.  Ignoring the situation is fine with me, but is this the correct behavior?

**Review by cachedout — APPROVED** [review]

**Comment by cachedout** [comment]
Go Go Jenkins!

**Review by rallytime — APPROVED** [review]

**Pull request merged**
