### PR TITLE
Virt fixes

### PR DESCRIPTION
**Pull request by cbosdo**
### What does this PR do?

This PR brings a few changes to features of the virt execution module introduced for fluorine:
`network_info` and `pool_info` are return the data for all networks or pools if no name is provided.
Thus the output of these calls has been slightly modified to include the names of the networks/pools.

This PR also includes doc and pylint fixes

Note that we may want to backport this fo Fluorine (at least the tiny doc fix) to avoid later disruptive change.

### What issues does this PR fix or reference?

None

### Previous Behavior

The name parameter in `virt.network_info` and `virt.pool_info` where mandatory.
The output returned the info as a dict.

### New Behavior

The name parameter in `virt.network_info` and `virt.pool_info` is now optional.
The output returns dicts following this scheme:

    { 'thename': previously_return_dict}

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by cbosdo** [comment]
@meaksh @rallytime This one is ready for review. Not sure how much of it you want to have backported to fluorine.

**Review by gtmanfred — APPROVED** [review]
This seems fine to me, i have no strong opinions about not backporting this to fluorine.

**Review by rallytime — APPROVED** [review]

**Comment by terminalmage** [comment]
These commits are already in master, so this PR can be removed from the list of PRs to be ported.

**Comment by cbosdo** [comment]
@terminalmage indeed... I confirm that all virt-related PRs have been ported to master

**Pull request merged**
