### PR TITLE
the data type is dict and need no json.loads

### PR DESCRIPTION
**Pull request by ihakh**
but for making sure i add a if for string type

### What does this PR do?
eliminates the warning of '[WARNING ] Returner unavailable: expected string or buffer'
### What issues does this PR fix or reference?
the type(data) is dict and there is no need for json.loads(data)
### Previous Behavior
[WARNING ] Returner unavailable: expected string or buffer
### New Behavior
No warning

### Tests written?

No

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by Ch3LL — CHANGES_REQUESTED** [review]
looks like this needs a rebase

**Comment by Ch3LL** [comment]
Following up here. Any bandwidth to finish this PR? This will also need test coverage and a changelog.

**Comment by Ch3LL** [comment]
bump @ihakh did you see my review comments?

**Comment by ihakh** [comment]
I actually did not clone the whole project
I just used the online github editor to fix things up
this is not a big change
anyone can make it right with a rebase or just a new commit

**Comment by dwoz** [comment]
Closing this due to inactivity.  Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
