### PR TITLE
make file envs compatible with fileclient formats

### PR DESCRIPTION
**Pull request by gtmanfred**
### What issues does this PR fix or reference?
Bug brought up in #dev in corporate slack

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by dwoz — APPROVED** [review]

**Review by dwoz — CHANGES_REQUESTED** [review]
@gtmanfred load needs to be optional: https://jenkinsci.saltstack.com/job/pr-lint/job/PR-49389/1/warnings52Result/new/

**Review by terminalmage — APPROVED** [review]
I tried to submit a review RE: passing the payload directly to `self.envs()` and @gtmanfred went and fixed it in the time it took me to type my review. :+1:

**Comment by cachedout** [comment]
@gtmanfred We have a failed test here: `integration.modules.test_cp.CPModuleTest.test_envs`

**Review by dwoz — APPROVED** [review]

**Comment by gtmanfred** [comment]
The test /should/ be fixed, may need to sort it.

**Pull request merged**
