### PR TITLE
[develop] Adding ability to disable requisites

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Adding the ability to disable requisites during State runs.

### What issues does this PR fix or reference?
N/A

### Tests written?
Yes.

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by garethgreenaway** [comment]
Manual tests for disabling requisites:

Require State file:
```
vim-tiny:
  pkg.installed:
    - require:
      - file: /tmp/vimrc

/tmp/vimrc:
  file.managed:
    - source: salt://test/edit/vimrc
```

Require disabled:
```
disabled_requisites: require
```

Normal run:
```
local:
----------
          ID: /tmp/vimrc
    Function: file.managed
      Result: True
     Comment: File /tmp/vimrc is in the correct state
     Started: 15:23:22.162520
    Duration: 20.0000000186 ms
     Changes:   
----------
          ID: vim-tiny
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 15:23:22.185465
    Duration: 89.999999851 ms
     Changes:   

Summary for local
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
Total run time: 110.000 ms
```

Disabled run:
```
local:
----------
          ID: vim-tiny
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 15:24:22.655635
    Duration: 89.999999851 ms
     Changes:   
----------
          ID: /tmp/vimrc
    Function: file.managed
      Result: True
     Comment: The file /tmp/vimrc is in the correct state
     Started: 15:24:22.747198
    Duration: 20.0000000186 ms
     Changes:   

Summary for local
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
Total run time: 110.000 ms
```

Require_In State File:
```
vim-tiny:
  pkg.installed

/tmp/vimrc:
  file.managed:
    - source: salt://test/edit/vimrc
    - require_in:
      - pkg: vim-tiny
```

Normal Run:
```
local:
----------
          ID: /tmp/vimrc
    Function: file.managed
      Result: True
     Comment: The file /tmp/vimrc is in the correct state
     Started: 16:12:41.378112
    Duration: 10.0000000093 ms
     Changes:   
----------
          ID: vim-tiny
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 16:12:41.393692
    Duration: 90.0000000838 ms
     Changes:   

Summary for local
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
Total run time: 100.000 ms
```

Disabled_run:
```
[WARNING ] The require_in requisite has been disabled, Ignoring.
local:
----------
          ID: vim-tiny
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 16:13:17.053604
    Duration: 90.0000000838 ms
     Changes:   
----------
          ID: /tmp/vimrc
    Function: file.managed
      Result: True
     Comment: The file /tmp/vimrc is in the correct state
     Started: 16:13:17.149302
    Duration: 10.0000000093 ms
     Changes:   

Summary for local
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
Total run time: 100.000 ms
```

**Review by isbm — COMMENTED** [review]
@garethgreenaway I would definitely start with some more unit tests in `tests/unit/test_state.py` for specific functions in the state compiler. The ` def requisite_in(self, high):` deserves nearly a whole class of unit tests on its own due to its enormous size and complexity. And probably refactoring...

**Review by terminalmage — COMMENTED** [review]
Perhaps the best way to test this is to unit test some of the intermediate functions in the state compiler.  `tests/unit/test_state.py` does this, see `test_render_error_on_invalid_requisite` for an example.

This approach would require you to provide the high data, and then then call the `salt.state.State` object's `requisite_in` method.

I wonder also if it would be a good idea to add a message to the error list when a disabled requisite is used, which would cause the states not to run and return an error message.

**Comment by gtmanfred** [comment]
https://jenkinsci.saltstack.com/job/pr-lint/job/PR-49955/5/warnings52Result/new/ lint warning on the test

**Comment by cachedout** [comment]
@terminalmage and @isbm Re-review requested.

**Review by cachedout — APPROVED** [review]
LGTM. I think this fits the bill.

**Review by isbm — APPROVED** [review]

**Comment by isbm** [comment]
I would _still_ write a bit more UTs though.

**Comment by rallytime** [comment]
@garethgreenaway There is a merge conflict here now unfortunately. Can you rebase and resolve the conflicts?

**Review by terminalmage — APPROVED** [review]

**Pull request merged**
