### PR TITLE
fix for two parameters in match-set #29423

### PR DESCRIPTION
**Pull request by l13t**

### CODE REVIEW

**Comment by jfindlay** [comment]
Fixes #29423.

**Comment by thusoy** [comment]
As far as I understand it, it should be possible to either specify match sets like this:
```yaml
match-set: src dest,dest2
```
or like this:
```yaml
match-set:
  - src dest
  - other_src flag1,flag2
```
Thus like I mentioned in #29423, you can't split the string on commas, as it would break the string case with multiple flags.

Also like mentioned, rule is a list, so you have to use `rule.append()`.

You also need to take care to extract negations properly, so that it's possible to specify the following rule:
```yaml
match-set:
  - ! src dest
```
The current suggestion would build the rule as `-m set --match-set ! src dest`, while the correct rule would be `-m set ! --match-set src dest`.

There is a function to help with the negations, `maybe_add_negation`, but it's made specifically for string keys, thus might need some tweaking to support list arguments like this.

**Comment by cachedout** [comment]
@l13t Did you see the above comment from @thusoy ? We'd love to have your feedback so we can get this PR modified if necessary and then merged. Thanks!

**Comment by l13t** [comment]
@cachedout
Hello
I saw this answer. And we proceeded discussion in Issue https://github.com/saltstack/salt/issues/29423 .
Sorry. I got few tasks at work and did upload changes to github. I'll try to do this today.

**Comment by cachedout** [comment]
Thanks @l13t . Please let me know when this is ready to go.

**Comment by thusoy** [comment]
@l13t Good work on the negations! Just remember to use `rule.append()` as well.

**Comment by l13t** [comment]
Oh... Only now I understand about what you were talking ((((:
If it's so necessary I change it tomorrow.
But after weeks of investigation of module/state and working on my own firewall formula I finally understand that it should be totally rewritten ))):

**Comment by cachedout** [comment]
Hi @l13t . Are there still changes to be made with this one? Please let me know when it is ready to go. Thanks!

**Comment by l13t** [comment]
You can merge this changes. I'll try later to rewrite this module in state like in was suggested with python-iptables.

**Comment by thusoy** [comment]
Negative, this can not be merged until the change uses rule.append or it won't work. Write a simple test case to build_url (there are several already) and you'll see.

**Comment by thusoy** [comment]
Based on @l13t's work I added some tests, the suggested fix doesn't remove the negated string from the original match-set, and as I've pointed out, fails to append the rule since it doesn't use rule.append. I fixed these issues and added tests in [this commit](https://github.com/thusoy/salt/commit/1f1021f5f0316c2976cb67fadc1f01e8c77f6b78), which I can open a new PR for if desired and then we close this, or the changes can be ported by @l13t into this PR and rebased.

**Comment by l13t** [comment]
@thusoy 
please open PR from your side.
i didn't know about some test changes ))):

**Comment by cachedout** [comment]
OK, based on what I'm reading here it sounds like the decision is to close this PR and wait for a new one from @thusoy . I'll close this one for the time being. Thanks to you both for the good discussion here.

**Comment by thusoy** [comment]
@cachedout Cool, new PR is [here](https://github.com/saltstack/salt/pull/29718)

**Pull request closed without merging**
