### PR TITLE
Fix/cmdmod powershell

### PR DESCRIPTION
**Pull request by xeacott**
### What does this PR do?
Add logic to allow cmd.run_all to accept a list argument for powershell shell.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/55213

### Tests written?

Yes

### Commits signed with GPG?

No

### CODE REVIEW

**Review by Ch3LL — DISMISSED** [review]

**Review by twangboy — DISMISSED** [review]

**Review by DmitryKuzmenko — DISMISSED** [review]

**Comment by DmitryKuzmenko** [comment]
@xeacott There is a lint warning. Also test failures are related.

**Comment by twangboy** [comment]
@xeacott Looks like you need to fix a few blacken issues

**Review by dwoz — APPROVED** [review]

**Review by dwoz — APPROVED** [review]

**Comment by dwoz** [comment]
We really need to do a better job about not having our method arguments allow multiple types, in this case both lists and strings for cmd.

**Comment by xeacott** [comment]
> We really need to do a better job about not having our method arguments allow multiple types, in this case both lists and strings for cmd.

Noted!

**Pull request merged**
