### PR TITLE
[2019.2.1] Disabling test_get_set_computer_name on OS X and Py3

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Disabling test_get_set_computer_name on OS X and Py3.

### What issues does this PR fix or reference?
N/A

### Tests written?
**[NOTICE] Bug fixes or features added to Salt require tests.**
Please review the [test documentation](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html) for details on how to implement tests into Salt's test suite.
No

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by waynew** [comment]
Per our discussion, we're disabling this until https://github.com/saltstack/salt/pull/53566 gets merged. We're testing the theory that the round-trip is causing a hang for some reason.

**Comment by waynew** [comment]
@garethgreenaway apparently you're missing a six import 😑

**Review by waynew — CHANGES_REQUESTED** [review]
Need that six import, then 👍

**Review by waynew — APPROVED** [review]

**Review by cmcmarrow — APPROVED** [review]

**Review by waynew — APPROVED** [review]

**Review by Ch3LL — APPROVED** [review]

**Comment by dwoz** [comment]
Merging without PR tests because they are flaky ATM

**Pull request merged**
