### PR TITLE
Fix zeromq stream.send exception message

### PR DESCRIPTION
**Pull request by vzhestkov**
### What does this PR do?

Porting https://github.com/saltstack/salt/pull/50545

Replacement for https://github.com/saltstack/salt/pull/55237

### CODE REVIEW

**Comment by waynew** [comment]
@vzhestkov thanks for the PR! Sorry for the delay in review - do you think you could 
add a [changelog entry](https://docs.saltstack.com/en/latest/topics/development/changelog.html)?

**Review by waynew — DISMISSED** [review]

**Comment by waynew** [comment]
@vzhestkov Hey, looks like there's a merge conflict - probably from dwoz's recent transport refactor. Do you think you could take a look? Thanks!

**Comment by vzhestkov** [comment]
@waynew sorry for the delay, it was bit more complex than I expected, the change is rebased

**Comment by waynew** [comment]
There was a lint issue - I just merged in master, not sure if that will solve the problem. Otherwise I'll review this soon!

**Comment by garethgreenaway** [comment]
@vzhestkov A few merge conflicts on this one as well.

**Comment by vzhestkov** [comment]
@garethgreenaway thanks for pinging, I'll resolve them once I get some time for it, will try to do it as soon as possible

**Review by twangboy — DISMISSED** [review]

**Review by dwoz — CHANGES_REQUESTED** [review]
@vzhestkov 

Please update this PR with my changes found here https://github.com/vzhestkov/salt-saltstack/pull/2

- Removes the use of `__del__`
- Fixes failing tests

**Comment by vzhestkov** [comment]
@dwoz sorry, I rebased this PR due to the conflicts, but after rebasing the PR you made is showing the conflicts. Could you please check your PR? Sorry for the mess.

**Comment by garethgreenaway** [comment]
@vzhestkov Looks like the merge conflicts are gone but the tests are still failing and they seem related.

**Review by dwoz — APPROVED** [review]
Looks good now!

**Pull request merged**
