### PR TITLE
Roster to provide PDSH/ClusterShell like hostname inputs

### PR DESCRIPTION
**Pull request by matdrapeau**
see: https://github.com/saltstack/salt/issues/22208

### CODE REVIEW

**Comment by matdrapeau** [comment]
How can I add the dependency ```clustershell`` to the project?

**Comment by thatch45** [comment]
Looks like we have some minor lint fix up:
https://jenkins.saltstack.com/job/salt-pr-lint-n/3736/violations/file/salt/roster/clustershell.py/

We would not add clustershell as a dep, this is an optional dep so we reqiore that it is installed separately to support the roster. So we need to document that this requires that ClusterShell is required for it. Take a look at:
https://github.com/saltstack/salt/blob/develop/salt/modules/nacl.py#L3

**Comment by matdrapeau** [comment]
@thatch45 Thanks for your input!
Let me know if there is other things to be modified

**Comment by thatch45** [comment]
Looks good! Thanks @matdrapeau !

**Pull request merged**
