### PR TITLE
[2015.2] Pass the `fun` to the returners in salt-ssh

### PR DESCRIPTION
**Pull request by basepi**
@pitatus ping

### CODE REVIEW

**Comment by basepi** [comment]
I'm betting these are fluke failures, but I'll let @rallytime or @jfindlay tell for sure.

**Comment by rallytime** [comment]
Hrm. Those state test failures are not on the "flaky" list. I'm going to run this again to see.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
Same failures.

**Pull request merged**
