### PR TITLE
Add runas message

### LINKED ISSUE #57951: [BUG] Better error message lacks password input on Windows
The following code snippet is the only place where there is any mention of using the password field:
https://github.com/saltstack/salt/blob/53cc103cf80cc4ab51449a36e25fdd52e0170aa4/salt/states/cmd.py#L869-L873

The documentation should warn of this as well.

Also, the error that I get when this is omitted (On 2019.2) is "embedded null character". There should be better error detection for a lack of password input on Windows.

The state code to reproduce the issue is relatively simple:
```mystatename:
   cmd.run:
    - name: |
        my commands here
    - shell: powershell
    - runas: Administrator
```

### PR DESCRIPTION
**Pull request by cmcmarrow**
### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/57951

### Previous Behavior
The salt state will crash and given a error that is not very helpful

### New Behavior
Salt warns that a password was not given if the current user is not an admin

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by cmcmarrow** [comment]
still need to run pre-commit

**Review by s0undt3ch — APPROVED** [review]

**Comment by s0undt3ch** [comment]
Lint and pre-commit needs to be fixed.

**Review by s0undt3ch — CHANGES_REQUESTED** [review]
Lint and pre-commit needs to be fixed.

**Comment by Ch3LL** [comment]
@cmcmarrow can you take a look here and fix the merge conflicts?

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
