### PR TITLE
Python 3 Fixes (Pt. 2)

### PR DESCRIPTION
**Pull request by s0undt3ch**
This should clear the remaining failures under Python 3 on the Cent7 VM

### CODE REVIEW

**Comment by ninja-** [comment]
@s0undt3ch have you investigated the problem where salt-master fails to exit cleanly on python3
(systemctl restart salt-master hangs) because of crash in some subprocess?

**Comment by cachedout** [comment]
@s0undt3ch Merge conflict. Could you please rebase?

**Comment by s0undt3ch** [comment]
@ninja-: I'm currently fixing the test suite failures under Py3 to make sure we can run it under Py2 and Py3. Once that's done, if there's still issues on Py3, we'll fix those as well

**Comment by s0undt3ch** [comment]
Rebased.

**Pull request merged**
