### PR TITLE
Update `tojson` to allow arbitrary args

### LINKED ISSUE #56012: No way to sort keys (or pass extra args) on `tojson` in Python3/`json_encode_dict` doesn't produce valid JSON
# Context

https://github.com/saltstack/salt/issues/55911 raised an issue that `tojson`, the recommended replacement for `json_decode_dict` changed to sort keys, which was undesired behavior. As it turns out, `json_decode_dict` was misnamed - it should have been `json_encode_dict`. That functionality works for their desired use-case.

# Problem 1 - bytes aren't JSON

In Python2, just using `json_encode_dict` works as expected, because text and bytes are the same thing.

In Python3, text and bytes are different, so `json_encode_dict({'z': 'zaz', 'y': 'yay', 'x': 'xax'})` produces: `{b'z': b'zaz', b'y':b'yay': b'x': b'xax'}`, which is not valid JSON. This is probably a bug.

# Problem (feature?) 2 - `tojson` sorts

The other part of this issue is that while `json.dump(s)` provides a `sort_keys` argument, the underlying Jinja2 implementation of `tojson` fails to expose the ability to pass arbitrary kwargs to the underlying JSON dump, so at least `tojson(sort_keys=False)` could be used to mimic the old behavior of `json_encode_dict`. We default to the Jinja2 [tojson](https://jinja.palletsprojects.com/en/2.10.x/templates/#tojson) function, but fall back to our own internal implementation. It may be, in order to preserve feature parity, that we should go ahead and override the builtin `tojson` always, with our own implementation that allows passing arbitrary args.

The implementation would actually be *super simple*. We [already have the code](https://github.com/saltstack/salt/blob/c6871f7355790bc3ddeb135c7a48700efb77e3b0/salt/utils/jinja.py#L337-L354), all we would have to do is change the function signature from

```
def tojson(val, indent=None):
```

to 

```
def tojson(val, indent=None, **options):
```

Then we would change https://github.com/saltstack/salt/blob/c6871f7355790bc3ddeb135c7a48700efb77e3b0/salt/utils/jinja.py#L344

to 

```
options.setdefault('ensure_ascii', True)
```

That's all that would be require to change our filter to provide the capability to do

```
{{ {'z': 'zzz', 'y': 'yyy', 'x': 'xxx'}|to_json(sort_keys=False) }}
```

Though, we'll have to also change things to always use our filter.

### PR DESCRIPTION
**Pull request by waynew**
### What does this PR do?

The [builtin Jinja tojson filter](https://jinja.palletsprojects.com/en/2.11.x/templates/#tojson) only supports `indent` as an arg that can be passed to the [underlying json dump function](https://docs.python.org/3/library/json.html#json.dumps). This doesn't allow [all the functionality people might want](https://github.com/saltstack/salt/issues/55911).

This updates the `tojson` filter to allow arbitrary keyword arguments to be passed along to the underlying JSON library.

### What issues does this PR fix or reference?

#55911 and closes #56012 

### Previous Behavior

It was impossible to get unsorted JSON, or use other functionality.

### New Behavior

It's possible to specify sorted or unsorted JSON, as well as pass arbitrary arguments to the underlying JSON dump function.

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by cmcmarrow — DISMISSED** [review]

**Review by DmitryKuzmenko — DISMISSED** [review]

**Comment by DmitryKuzmenko** [comment]
@waynew it looks failures are related.

**Review by dwoz — DISMISSED** [review]

**Review by DmitryKuzmenko — DISMISSED** [review]

**Comment by waynew** [comment]
rebased + py2 drop precommit. Should be good *now* (or in a couple hours when all tests are done)

**Comment by Ch3LL** [comment]
ping @waynew theres some failing tests here

**Comment by sagetherage** [comment]
moving this to another release

**Comment by waynew** [comment]
@sagetherage  hopefully this should pass the broken tests -- I  fell victim to one of the classic blunders - no, not "Never get involved in a land war in Asia,"... and no, not "Never go up against a Sicilian when death is on the line"  This one was, "Earlier versions of Python are arbitrary with their dictionary ordering no matter how lucky you think you are."

Anyway, this should be better now, please let me know if it isn't!

**Review by Ch3LL — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Review by s0undt3ch — APPROVED** [review]

**Comment by myii** [comment]
@waynew Note that the `tojson` section in https://github.com/saltstack/salt/blob/master/doc/topics/jinja/index.rst also needs to be updated.

**Pull request merged**
