### PR TITLE
add docker-ce to docker subtype grains check

### LINKED ISSUE #44292: grains['virtual_subtype'] assignment for Docker broken on Mac
### Description of Issue/Question

The following check in `salt/salt/grains/core.py` looks to have broken with the latest Docker for Mac Edge release.

```
                with salt.utils.files.fopen('/proc/1/cgroup', 'r') as fhr:
                    fhr_contents = fhr.read()
                    if ':/docker/' in fhr_contents or ':/system.slice/docker' in fhr_contents:
grains['virtual_subtype'] = 'Docker'
```

The latest release of Docker for Mac Edge has the following file content which uses `docker-ce` instead of `docker`:
```
[root@c7283528b9b3 /]# cat /proc/1/cgroup
13:name=systemd:/docker-ce/docker/c7283528b9b384fe982156edecd205573ab33421f72b8ae9aa2740d856c20c2e
12:pids:/docker-ce/docker/c7283528b9b384fe982156edecd205573ab33421f72b8ae9aa2740d856c20c2e
11:hugetlb:/docker-ce/docker/c7283528b9b384fe982156edecd205573ab33421f72b8ae9aa2740d856c20c2e
10:net_prio:/docker-ce/docker/c7283528b9b384fe982156edecd205573ab33421f72b8ae9aa2740d856c20c2e
9:perf_event:/docker-ce/docker/c7283528b9b384fe982156edecd205573ab33421f72b8ae9aa2740d856c20c2e
8:net_cls:/docker-ce/docker/c7283528b9b384fe982156edecd205573ab33421f72b8ae9aa2740d856c20c2e
7:freezer:/docker-ce/docker/c7283528b9b384fe982156edecd205573ab33421f72b8ae9aa2740d856c20c2e
6:devices:/docker-ce/docker/c7283528b9b384fe982156edecd205573ab33421f72b8ae9aa2740d856c20c2e
5:memory:/docker-ce/docker/c7283528b9b384fe982156edecd205573ab33421f72b8ae9aa2740d856c20c2e
4:blkio:/docker-ce/docker/c7283528b9b384fe982156edecd205573ab33421f72b8ae9aa2740d856c20c2e
3:cpuacct:/docker-ce/docker/c7283528b9b384fe982156edecd205573ab33421f72b8ae9aa2740d856c20c2e
2:cpu:/docker-ce/docker/c7283528b9b384fe982156edecd205573ab33421f72b8ae9aa2740d856c20c2e
1:cpuset:/docker-ce/docker/c7283528b9b384fe982156edecd205573ab33421f72b8ae9aa2740d856c20c2e
```

Prior releases looked like:
```
[root@6f2eaf8239b4 ~]# cat /proc/1/cgroup
14:name=systemd:/docker/6f2eaf8239b401962042af5dc3b17a6274cabbc1fcbcd50ca78c2b6351617a10
13:pids:/docker/6f2eaf8239b401962042af5dc3b17a6274cabbc1fcbcd50ca78c2b6351617a10
12:hugetlb:/docker/6f2eaf8239b401962042af5dc3b17a6274cabbc1fcbcd50ca78c2b6351617a10
11:net_prio:/docker/6f2eaf8239b401962042af5dc3b17a6274cabbc1fcbcd50ca78c2b6351617a10
10:perf_event:/docker/6f2eaf8239b401962042af5dc3b17a6274cabbc1fcbcd50ca78c2b6351617a10
9:net_cls:/docker/6f2eaf8239b401962042af5dc3b17a6274cabbc1fcbcd50ca78c2b6351617a10
8:freezer:/docker/6f2eaf8239b401962042af5dc3b17a6274cabbc1fcbcd50ca78c2b6351617a10
7:devices:/docker/6f2eaf8239b401962042af5dc3b17a6274cabbc1fcbcd50ca78c2b6351617a10
6:memory:/docker/6f2eaf8239b401962042af5dc3b17a6274cabbc1fcbcd50ca78c2b6351617a10
5:blkio:/docker/6f2eaf8239b401962042af5dc3b17a6274cabbc1fcbcd50ca78c2b6351617a10
4:cpuacct:/docker/6f2eaf8239b401962042af5dc3b17a6274cabbc1fcbcd50ca78c2b6351617a10
3:cpu:/docker/6f2eaf8239b401962042af5dc3b17a6274cabbc1fcbcd50ca78c2b6351617a10
2:cpuset:/docker/6f2eaf8239b401962042af5dc3b17a6274cabbc1fcbcd50ca78c2b6351617a10
1:name=openrc:/docker
```

### PR DESCRIPTION
**Pull request by gtmanfred**
### What does this PR do?
apparently the new community edition of docker for mac is changing this key

### What issues does this PR fix or reference?
Fixes #44292

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by rallytime — APPROVED** [review]

**Review by cachedout — CHANGES_REQUESTED** [review]
Spoke directly with @gtmanfred about this and we both think it's best to write a quick unit test here just to guarantee the intended behavior in future releases.

**Review by terminalmage — APPROVED** [review]
This looks straightforward, we just need a quick test as noted by @cachedout. We should make sure that all items in `dstrings`are tested.

**Comment by cachedout** [comment]
Bump @gtmanfred on the unit test case, please.

**Comment by gtmanfred** [comment]
I will get to this this week.

Thanks,
Daniel

**Comment by terminalmage** [comment]
https://github.com/gtmanfred/salt/pull/4

**Comment by gtmanfred** [comment]
@terminalmage you are just the best kind of person!

Thanks!
Daniel

**Comment by gtmanfred** [comment]
@cachedout can you rereview this?

Thanks,
Daniel

**Comment by rallytime** [comment]
re-run lint

**Review by cachedout — APPROVED** [review]

**Comment by rallytime** [comment]
@gtmanfred Ah, the lint is failing on the unit test here. Py 2.6 can't run tests with multiple context managers like Py 2.7 can. You'll need to change that to use multiple nested with statements since this is for 2016.11.

**Pull request merged**
