### PR TITLE
[fluorine] Merge forward from 2018.3 to fluorine

### PR DESCRIPTION
**Pull request by rallytime**
Conflicts:
  - doc/man/salt.7

### CODE REVIEW

**Review by gtmanfred — APPROVED** [review]

**Comment by cachedout** [comment]
These test failures seem related to this change.

**Comment by rallytime** [comment]
The test that is failing on this was written by @gtmanfred for the fluorine branch (they don't exist in 2018.3). The change that is causing the failure is from @garethgreenaway's change to the vault utils module in PR #49820, which is merged forward here.

I don't know vault well enough to trouble shoot that change vs the test failure. @garethgreenaway Would you mind helping out? I know you wrote some other tests around this recently, too, so you're probably a better person to look at this than I am.

**Comment by cachedout** [comment]
Assigned to @garethgreenaway

**Comment by garethgreenaway** [comment]
Spending some time on this and it appears unrelated to the changes but seems to be caused by the Vault docker container not starting up properly.  Still investigating why.

**Comment by cachedout** [comment]
@garethgreenaway Any news here?

**Pull request merged**
