### PR TITLE
Stop the deprecation path started in 0.17 about ext_pillar

### PR DESCRIPTION
**Pull request by s0undt3ch**
The `ext_pillar` functions **must** now accept a minion ID as the first argument.
This stops the deprecation path started in Salt [0.17.x](https://github.com/saltstack/salt/blob/0.17/salt/pillar/__init__.py#L429). Before this minion ID first argument was introduced, the minion ID could be retrieved accessing `__opts__['id']` loosing the reference to the master ID initially set in opts.
This is no longer the case, `__opts__['id']` will be kept as the master ID.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
This won't run until the pip error(s) are taken care of...

**Comment by cachedout** [comment]
I didn't look too closely but I think these might have been git checkout errors. We saw some on other PRs. I think GH might have burped last night.

**Comment by s0undt3ch** [comment]
Nope, the problem is acttualy six:

```
Installing collected packages: six, unittest-xml-reporting
Found existing installation: six 1.3.0 Detected a distutils installed project ('six') which we cannot uninstall. The metadata provided by distutils does not contain a list of files which have been installed, so pip does not know which files to uninstall.
```

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by jtand** [comment]
Pip issues are fixed, re-running jenkins

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Finally a build that went all the way...
Now, are these failures known or triggered by my changes?

**Comment by jtand** [comment]
@s0undt3ch The boto_vpc_test and event_test are known. The others are new failures, if you could look into them, that would be great.

**Comment by cachedout** [comment]
Hrm. I have seen those pop up on occasion but I don't know why. A re-run will probably produce better results, but I do wish I knew why those happened.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Let's see how this last test run goes but it should be good now.

**Comment by s0undt3ch** [comment]
Nope, still more fixing to do...

**Comment by cachedout** [comment]
@s0undt3ch OK. Just let me know. :]

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
I think the failures are narrowed to the know ones. If not, let me know please.

**Comment by s0undt3ch** [comment]
Superb!

**Comment by jacobhammons** [comment]
Removing the release notes tag since this PR already includes an addition to the release notes (well done!)

**Pull request merged**
