### PR TITLE
[develop] Merge forward from 2016.3 to develop

### PR DESCRIPTION
**Pull request by rallytime**
Conflicts:
- salt/grains/core.py
- tests/unit/grains/core_test.py

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Only 180 tests run. Something isn't right here.

**Comment by rallytime** [comment]
@cachedout I have seen that on odd PRs every now and then. Let's run these again and see what happens.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
I am going to redo this once #34852 is merged.

**Pull request closed without merging**
