### PR TITLE
iptables changes for match recent

### PR DESCRIPTION
**Pull request by svenauhagen**
Hi,

this change allows for iptables to have more options for match recent.
Recent can be used for example to rate limit access like SSH:

iptables -I INPUT -p tcp --dport 22 -i eth0 -m state --state NEW -m recent --set --name SSH
iptables -I INPUT -p tcp --dport 22 -i eth0 -m state --state NEW -m recent  --update --name SSH --seconds 60 --hitcount 4 -j DROP

This only allows 3 connections every 60 seconds from a host.

Currently this is not possible with Salt since:

a) a single argument is not allowed for iptables but recent requires set, update
b) a name for the list where the tracking should happen is not possible.
this was actually discussed in #30013 

This commit adds a check to allow single arguments for iptables and picks up the discussion to add a variable _name for name when the argument is recent.

Please let me know what you think.

Best
Sven

### CODE REVIEW

**Comment by cachedout** [comment]
I would like to see if @thusoy has any feedback here.

**Comment by thusoy** [comment]
@svenauhagen Good catch, this would be great. As per the discussion you linked to, I'd prefer for the variable to be named `name_`, since there would be a precedent for naming conflicts that way. I'd also suggest the following to avoid the repetitive nesting:
```python
for key, value in kwargs.items():
    negation = maybe_add_negation(key)
    flag = '-' if len(key) == 1 else '--'
    value = '' if value in (None, '') else ' {0}'.format(value)
    rule.append('{0}{1}{2}{3}'.format(negation, flag, key, value))
```

Would be great if you could also add the following test cases to verify this and ensure we don't regress:
```python
    # should allow escaped name
    self.assertEqual(iptables.build_rule(**{'match': 'recent', 'name_': 'SSH'}),
                     '-m recent --name SSH')

    # should allow empty arguments
    self.assertEqual(iptables.build_rule(**{'match': 'recent', 'update': None}),
                     '-m recent --update')
```

**Comment by svenauhagen** [comment]
@thusoy thanks for the feedback.
I added the changes and test cases and pushed the code.

**Review by thusoy — APPROVED** [review]
@svenauhagen Excellent!

@cachedout LGTM, but I haven't investigated the lint errors.

**Pull request merged**
