### PR TITLE
Pass saltenv to call to latest_version in list_upgrades function

### PR DESCRIPTION
**Pull request by ghost**
### What does this PR do?

saltenv is not passed to call to latest version in list_upgrades version
### What issues does this PR fix or reference?

None at the moment. This only applies to the devel version.
(Question for the salt maintainers. Should issues be created for small fixes to the devel branch?)
### Previous Behavior

Not sure but latest_version definitely needs saltenv because it calls
list_pkgs which also needs saltenv
### New Behavior

Things should be better than they were before.
### Tests written?

No

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @hrumph. This should go on the oldest supported branch that exhibits the issue (starting with 2015.8). I can merge this, though, and we'll just backport it. Thanks.

**Comment by hrumph** [comment]
hi #cachedout, before making the PR, I looked in previous branches and I didn't see the saltenv variable being passed around so I'm not sure what I was looking at then. I'll take another look. Sorry my bad if I messed up. Thanks for backporting if it's necessary.

**Comment by hrumph** [comment]
@cachedout I took another look. I didn't think that the fix was applicable to pre-devel, and that's still my sense of things.

**Comment by rallytime** [comment]
Yeah, you're right @hrumph. `saltenv` isn't passed in the same way in this module in earlier versions. If the bug you're running into is exhibiting itself on older branches, we might need to try to pull `saltenv` out of `**kwargs`, which will require a different fix and more investigation on the older branch(es).

@cachedout I am removing the `Bugfix - back-port` label here. I am not sure if we need to file a new issue for this for the older branches. What do you think?

**Comment by hrumph** [comment]
@rallytime, I'll assume for now that there is no bug in previous versions. As a matter of fact I hadn't actually encountered any bug personally. I just knew it was wrong from looking at the code. I haven't actually worked multiple salt environments yet. Presumably before the devel branch, you couldn't have different repositories for different salt environments. I wouldn't know.

**Pull request merged**
