### PR TITLE
Multiple fixes for Proxmox salt-cloud driver

### LINKED ISSUE #62211: [BUG] proxmox salt-cloud driver provides inadequate information on errors
I'm not sure if this is a bug exactly, but it's also not exactly a feature request, since there's not really a "new" feature that requires documentation.

### Description
The salt-cloud proxmox driver provides misleading error messages on authentication failure and incomplete messages on parameter validation failure.

Pull request with fix and tests to follow.

### Setup
- salt master (hostname "salt") is running in a container on the Proxmox host.
- Proxmox (hostname "pve") is running on bare metal, on-premises.
<details><summary>/etc/salt/cloud.providers.d/proxmox.conf</summary>

```
proxmox:
  minion:
    master: salt
  user: mysaltuser@pve
  password: notreallythepassword
  url: pve
  driver: proxmox
```
</details>
<details><summary>/etc/salt/cloud.profiles.d/proxmox.conf</summary>

```yaml
ol8:
  provider: proxmox
  pool: mypool
  image: local:vztmpl/oraclelinux-8-official_amd64.tar.gz
  storage: local-zfs
  technology: lxc
  host: pve
  onboot: 1
  pubkey: mypubkey
  ip_address: 192.168.0.222
```
</details>

#### Authentication errors:
Set the password in cloud.providers.d/proxmox.conf to the wrong password.
`salt-cloud --list-images proxmox`
<details><summary>Output</summary>

```
[ERROR   ] Failed to get the output of 'proxmox.avail_images()': 'NoneType' object is not subscriptable
proxmox:
    ----------
```  
</details>
"'NoneType' object is not subscriptable"...  Guess what's wrong with your configuration?

#### Parameter validation errors:
Set the password in cloud.providers.d/proxmox.conf back to the right password if necessary.
Change the value of "onboot" in cloud.profiles.d/proxmox.conf from "1" to "true".
`salt-cloud -p ol8 testvm2`
<details><summary>Output</summary>

```
[ERROR   ] Error creating testvm2 on PROXMOX

The following exception was thrown when trying to run the initial deployment: 
400 Client Error: Parameter verification failed. for url: https://pve:8006/api2/json/nodes/pve/lxc
Error: There was a profile error: Failed to deploy VM
```
</details>
What parameter failed?  Who knows...

#### Authentication errors:
`salt-cloud --list-images proxmox`
<details><summary>Output</summary>

```
[ERROR   ] Failed to get the output of 'proxmox.avail_locations()': 401 Client Error: authentication failure for url: https://pve:8006/api2/json/access/ticket
proxmox:
    ----------
```  
</details>
Oh, there's something wrong with my credentials!

#### Parameter validation errors:
`salt-cloud -p ol8 testvm2`
<details><summary>Output</summary>

```
[ERROR   ] Error creating testvm2 on PROXMOX

The following exception was thrown when trying to run the initial deployment: 
400 Client Error: Parameter verification failed. for url: https://pve:8006/api2/json/nodes/pve/lxc
{"data":null,"errors":{"onboot":"type check ('boolean') failed - got 'True'"}}
Error: There was a profile error: Failed to deploy VM
```
</details>
There's the missing detail provided by the Proxmox server:  Proxmox doesn't like textual booleans!

### Versions Report
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3004.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Apr 11 2022, 08:25:52)
  python-gnupg: 0.4.6
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: oracle 8.6 
        locale: UTF-8
       machine: x86_64
       release: 5.15.35-1-pve
        system: Linux
       version: Oracle Linux Server 8.6  
```
</details>

### LINKED ISSUE #62521: [BUG] proxmox salt-cloud driver doesn't pass the "pool" parameter when cloning a VM
**Description**
When attempting to clone a qemu VM on a Proxmox VE host, the salt-cloud proxmox driver fails to relay the "pool" parameter specified by the profile.

This causes cloning to fail for any user that does not have a global VM.Allocate permission (i.e. their permissions are restricted to their pool).

Pull request with fix and tests to follow.

**Setup**
- salt master (hostname "salt") is running in a container on the Proxmox host.
- Proxmox (hostname "pve") is running on bare metal, on-premises.
<details><summary>/etc/salt/cloud.providers.d/proxmox.conf</summary>

```
proxmox:
  minion:
    master: salt
  user: mysaltuser@pve
  password: notreallythepassword
  url: pve
  driver: proxmox
```
</details>
<details><summary>/etc/salt/cloud.profiles.d/proxmox.conf</summary>

```yaml
ol8:
  provider: proxmox
  pool: mypool
  technology: qemu
  image: ''  # work around bug in salt
  clone: True
  clone_full: 0
  clone_from: 200
  host: pve
  onboot: 1
  pubkey: mypubkey
  cores: 1
```
</details>

**Steps to Reproduce the behavior**
`salt-cloud -p -l all ol8 testvm`
<details><summary>Excerpt of debug log</summary>

```
...
[DEBUG   ] Sending event: tag = salt/cloud/testvm/requesting; data = {'kwargs': {'cores': 1, 'onboot': 1, 'name': 'testvm', 'pool': 'mypool', 'vmid': 105}, 'event': 'requesting instance', '_stamp': '2022-08-23T15:56:46.656308'}
[DEBUG   ] Closing IPCMessageClient instance
[DEBUG   ] Preparing to generate a node using these parameters: {'vmid': 105, 'onboot': 1, 'cores': 1, 'pool': 'mypool', 'name': 'testvm'} 
[DEBUG   ] post: https://pve:8006/api2/json/nodes/pve/qemu/200/clone ({'newid': 105, 'full': 0})
[DEBUG   ] Starting new HTTPS connection (1): pve:8006
[DEBUG   ] https://pve:8006 "POST /api2/json/nodes/pve/qemu/200/clone HTTP/1.1" 403 13
[ERROR   ] Error creating testvm on PROXMOX

The following exception was thrown when trying to run the initial deployment: 
403 Client Error: Permission check failed for url: https://pve:8006/api2/json/nodes/pve/qemu/200/clone
{"data":null}
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/cloud/clouds/proxmox.py", line 658, in create
    data = create_node(vm_, newid)
  File "/usr/lib/python3.6/site-packages/salt/cloud/clouds/proxmox.py", line 953, in create_node
    postParams,
  File "/usr/lib/python3.6/site-packages/salt/cloud/clouds/proxmox.py", line 195, in query
    response.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Permission check failed for url: https://pve:8006/api2/json/nodes/pve/qemu/200/clone
Error: There was a profile error: Failed to deploy VM
```  
</details>

**Expected behavior**
Passing the specified pool in order to enable successful creation of the VM, e.g.:

```
[DEBUG   ] post: https://pve:8006/api2/json/nodes/pve/qemu/200/clone ({'newid': 105, 'pool': 'mypool', 'full': 0})
```

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3004.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Apr 11 2022, 08:25:52)
  python-gnupg: 0.4.6
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: oracle 8.6 
        locale: UTF-8
       machine: x86_64
       release: 5.15.35-3-pve
        system: Linux
       version: Oracle Linux Server 8.6  
```
</details>

### LINKED ISSUE #62558: [BUG] proxmox salt-cloud driver fails to provision a cloned VM with a specified id
**Description**
When attempting to clone a qemu VM on a Proxmox VE host, the salt-cloud proxmox driver uses the specified ID to clone the new VM, but uses the "next available" ID to bootstrap.

Since the next-available VM doesn't exist, bootstrapping fails.

Pull request with fix and tests to follow.

**Setup**
- salt master (hostname "salt") is running in a container on the Proxmox host.
- Proxmox (hostname "pve") is running on bare metal, on-premises.
<details><summary>/etc/salt/cloud.providers.d/proxmox.conf</summary>

```
proxmox:
  minion:
    master: salt
  user: mysaltuser@pve
  password: notreallythepassword
  url: pve
  driver: proxmox
```
</details>
<details><summary>/etc/salt/cloud.profiles.d/proxmox.conf</summary>

```yaml
ol8:
  provider: proxmox
  pool: mypool
  technology: qemu
  image: ''  # work around bug in salt
  clone: True
  clone_full: 0
  clone_from: 200
  host: pve
  onboot: 1
  pubkey: mypubkey
  cores: 1
```
</details>

<details><summary>cloud.map</summary>

```yaml
ol8:
  - testvm:
      vmid: 300
```
</details>

**Steps to Reproduce the behavior**
`salt-cloud -l all -m cloud.map testvm`
<details><summary>Excerpt of debug log</summary>

```
...
[DEBUG   ] post: https://pve:8006/api2/json/nodes/pve/qemu/200/clone ({'newid': 300, 'pool': 'mypool', 'full': 0})
[DEBUG   ] Starting new HTTPS connection (1): pve:8006
[DEBUG   ] https://pve:8006 "POST /api2/json/nodes/pve/qemu/200/clone HTTP/1.1" 200 75
[DEBUG   ] Using IP address 10.10.10.10
[DEBUG   ] Getting creation status for upid: UPID:pve:00112233:44556677:8899AABB:qmclone:200:mysaltuser@pve:
[DEBUG   ] get: https://pve:8006/api2/json/cluster/tasks (None)
[DEBUG   ] Starting new HTTPS connection (1): pve:8006
[DEBUG   ] https://pve:8006 "GET /api2/json/cluster/tasks HTTP/1.1" 200 426
[DEBUG   ] Found upid task: {'id': '200', 'type': 'qmclone', 'user': 'mysaltuser@pve', 'node': 'pve', 'pid': 701325, 'upid': 'UPID:pve:00112233:44556677:8899AABB:qmclone:200:mysaltuser@pve:', 'starttime': 1661797302}
[DEBUG   ] Getting creation status for upid: UPID:pve:00112233:44556677:8899AABB:qmclone:200:mysaltuser@pve:
[DEBUG   ] get: https://pve:8006/api2/json/cluster/tasks (None)
[DEBUG   ] Starting new HTTPS connection (1): pve:8006
[DEBUG   ] https://pve:8006 "GET /api2/json/cluster/tasks HTTP/1.1" 200 432
[DEBUG   ] Found upid task: {'node': 'pve', 'starttime': 1661797302, 'status': 'OK', 'saved': 1, 'type': 'qmclone', 'user': 'mysaltuser@pve', 'endtime': 1661797303, 'upid': 'UPID:pve:00112233:44556677:8899AABB:qmclone:200:mysaltuser@pve:', 'id': '200'}
[DEBUG   ] Host has been created!
[INFO    ] Configuring cloned VM
[DEBUG   ] get: https://pve:8006/api2/json/nodes/pve/qemu/110/config (None)
[DEBUG   ] Starting new HTTPS connection (1): pve:8006
[DEBUG   ] https://pve:8006 "GET /api2/json/nodes/pve/qemu/110/config HTTP/1.1" 500 13
[ERROR   ] There was a query error: 500 Server Error: Configuration file 'nodes/pve/qemu-server/110.conf' does not exist for url: https://pve:8006/api2/json/nodes/pve/qemu/110/config
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/cloud/cli.py", line 319, in run
    ret = mapper.run_map(dmap)
  File "/usr/lib/python3.6/site-packages/salt/cloud/__init__.py", line 2196, in run_map
    output[name] = self.create(profile, local_master=local_master)
  File "/usr/lib/python3.6/site-packages/salt/cloud/__init__.py", line 1226, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/cloud/clouds/proxmox.py", line 703, in create
    _reconfigure_clone(vm_, vmid)
  File "/usr/lib/python3.6/site-packages/salt/cloud/clouds/proxmox.py", line 583, in _reconfigure_clone
    data = query("get", "nodes/{}/qemu/{}/config".format(vm_["host"], vmid))
  File "/usr/lib/python3.6/site-packages/salt/cloud/clouds/proxmox.py", line 195, in query
    response.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Configuration file 'nodes/pve/qemu-server/110.conf' does not exist for url: https://pve:8006/api2/json/nodes/pve/qemu/110/config
```  
</details>

**Expected behavior**
Configuring the proper VM ID in order to enable successful creation of the VM, e.g.:

```
[DEBUG   ] get: https://pve:8006/api2/json/nodes/pve/qemu/300/config (None)
```

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3004.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Apr 11 2022, 08:25:52)
  python-gnupg: 0.4.6
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: oracle 8.6 
        locale: UTF-8
       machine: x86_64
       release: 5.15.35-3-pve
        system: Linux
       version: Oracle Linux Server 8.6  
```
</details>

### LINKED ISSUE #62580: [BUG] proxmox salt-cloud driver fails to configure a cloned VM with all specified parameters
**Description**
When attempting to clone a qemu VM on a Proxmox VE host, the salt-cloud proxmox driver only configures ide/sata/scsi/net parameters.

It neglects to pass all other parameters, such as name, description, memory, number of cores, SSH keys, etc.

Pull request with fix and tests to follow.

**Setup**
- salt master (hostname "salt") is running in a container on the Proxmox host.
- Proxmox (hostname "pve") is running on bare metal, on-premises.
<details><summary>/etc/salt/cloud.providers.d/proxmox.conf</summary>

```
proxmox:
  minion:
    master: salt
  user: mysaltuser@pve
  password: notreallythepassword
  url: pve
  driver: proxmox
```
</details>
<details><summary>/etc/salt/cloud.profiles.d/proxmox.conf</summary>

```yaml
ol8:
  provider: proxmox
  pool: mypool
  technology: qemu
  image: ''  # work around bug in salt
  clone: True
  clone_full: 0
  clone_from: 200
  host: pve
  onboot: 1
  sshkeys: mypubkey
  cores: 1
  net0: model=virtio,bridge=vmbr0
```
</details>

<details><summary>cloud.map</summary>

```yaml
ol8:
  - testvm:
      vmid: 300
```
</details>

**Steps to Reproduce the behavior**
`salt-cloud -l all -m cloud.map testvm`

<details><summary>Excerpt of debug log</summary>

```
...
[DEBUG   ] Host has been created!
[INFO    ] Configuring cloned VM
[DEBUG   ] get: https://pve:8006/api2/json/nodes/pve/qemu/300/config (None)
[DEBUG   ] Starting new HTTPS connection (1): pve:8006
[DEBUG   ] https://pve:8006 "GET /api2/json/nodes/pve/qemu/300/config HTTP/1.1" 200 944
[DEBUG   ] post: https://pve:8006/api2/json/nodes/pve/qemu/300/config ({'net0': 'model=virtio,bridge=vmbr0'})
[DEBUG   ] Starting new HTTPS connection (1): pve:8006
[DEBUG   ] https://pve:8006 "POST /api2/json/nodes/pve/qemu/300/config HTTP/1.1" 200 75
[DEBUG   ] Start: testvm (300) = Start
...
```
</details>

**Expected behavior**
Configuring all valid VM parameters specified in the profile or cloud map

<details><summary>Expected excerpt of debug log</summary>

```
...
[DEBUG   ] Host has been created!
[INFO    ] Configuring cloned VM
[DEBUG   ] post: https://pve:8006/api2/json/nodes/pve/qemu/300/config ({'onboot': 1})
[DEBUG   ] Starting new HTTPS connection (1): pve:8006
[DEBUG   ] https://pve:8006 "POST /api2/json/nodes/pve/qemu/300/config HTTP/1.1" 200 75
[DEBUG   ] post: https://pve:8006/api2/json/nodes/pve/qemu/300/config ({'sshkeys': 'mypubkey'})
[DEBUG   ] Starting new HTTPS connection (1): pve:8006
[DEBUG   ] https://pve:8006 "POST /api2/json/nodes/pve/qemu/300/config HTTP/1.1" 200 75
[DEBUG   ] get: https://pve:8006/api2/json/nodes/pve/qemu/300/config (None)
[DEBUG   ] Starting new HTTPS connection (1): pve:8006
[DEBUG   ] https://pve:8006 "GET /api2/json/nodes/pve/qemu/300/config HTTP/1.1" 200 1028
[DEBUG   ] post: https://pve:8006/api2/json/nodes/pve/qemu/300/config ({'net0': 'model=virtio,bridge=vmbr0'})
[DEBUG   ] Starting new HTTPS connection (1): pve:8006
[DEBUG   ] https://pve:8006 "POST /api2/json/nodes/pve/qemu/300/config HTTP/1.1" 200 75
[DEBUG   ] post: https://pve:8006/api2/json/nodes/pve/qemu/300/config ({'cores': 1})
[DEBUG   ] Starting new HTTPS connection (1): pve:8006
[DEBUG   ] https://pve:8006 "POST /api2/json/nodes/pve/qemu/300/config HTTP/1.1" 200 75
[DEBUG   ] post: https://pve:8006/api2/json/nodes/pve/qemu/300/config ({'name': 'testvm'})
[DEBUG   ] Starting new HTTPS connection (1): pve:8006
[DEBUG   ] https://pve:8006 "POST /api2/json/nodes/pve/qemu/300/config HTTP/1.1" 200 75
[DEBUG   ] Start: testvm (300) = Start
...
```
</details>

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3004.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Apr 11 2022, 08:25:52)
  python-gnupg: 0.4.6
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: oracle 8.6 
        locale: UTF-8
       machine: x86_64
       release: 5.15.35-3-pve
        system: Linux
       version: Oracle Linux Server 8.6  
```
</details>

### PR DESCRIPTION
**Pull request by pjcreath**
### What does this PR do?
Resolves multiple outstanding issues in the proxmox salt-cloud driver, see the individual issues linked below for details.

### What issues does this PR fix or reference?
Fixes: #62211
Fixes: #62521
Fixes: #62558
Fixes: #62580

### Merge requirements satisfied?
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by pjcreath** [comment]
Found another bug in the proxmox driver, new issue and commit coming soon.

**Review by twangboy — APPROVED** [review]

**Review by whytewolf — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Comment by pjcreath** [comment]
re-run pr-amazon-2-x86_64-py3-pytest
re-run pr-freebsd-131-amd64-py3-pytest

**Comment by pjcreath** [comment]
re-run pr-fedora-35-x86_64-py3-pytest
re-run pr-opensuse-15-x86_64-py3-pytest
re-run pr-ubuntu-2004-amd64-py3-m2crypto-pytest
re-run pr-ubuntu-2004-amd64-py3-pycryptodome-pytest
re-run pr-ubuntu-2004-amd64-py3-tcp-pytest
re-run pr-ubuntu-2004-arm64-py3-pytest
re-run pr-ubuntu-2204-amd64-py3-pytest

**Comment by pjcreath** [comment]
re-run pr-ubuntu-2204-amd64-py3-pycryptodome-pytest
re-run pr-macosx-catalina-x86_64-py3-pytest
re-run pr-freebsd-131-amd64-py3-pytest

**Pull request merged**
