### PR TITLE
Use declared yaml options

### LINKED ISSUE #20647: file.serialize fails to serialize due to ordered dicts
It's possible file.serialize has been broken since everything has been switched to ordered dicts. It seems to pass data structures without transforming them and ordered dicts aren't serializable.

### PR DESCRIPTION
**Pull request by cachedout**
Fixes #20647

### CODE REVIEW

**Comment by cachedout** [comment]
Please let these tests run all the way through before merging. This could have unintended side-effects.

**Comment by thatch45** [comment]
I bet we only need to change the serialize option

**Comment by rallytime** [comment]
So my favorite thing about the test that is failing here is this:
```
# BLAAM! yml_src is not valid !
         final_obj = yaml.deserialize(yml_src)
         assert obj != final_obj
```
@cachedout - this PR now seems to negate this testing assertion, yes? # BLAAM!

**Comment by thatch45** [comment]
@cachedout what is the status on this one?

**Comment by cachedout** [comment]
Will look at today. This test failure could well be legit.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Pull request merged**
