### PR TITLE
Write tests for Venafi runner

### PR DESCRIPTION
**Pull request by gtmanfred**
### What does this PR do?
Add integration tests for creating certificates for the Venafi runner.  

Run against https://api.staging.venafi.io/v1

```
venafi:
  api_key: <apikey>
  base_url: https://api.staging.venafi.io/v1
ext_pillar:
  - venafi: True
```

Closes https://github.com/saltstack/qa/issues/282
### Tests written?

Yes

### CODE REVIEW

**Review by techhat — APPROVED** [review]

**Comment by gtmanfred** [comment]
@cachedout @Ch3LL it looks like this is running the venafi tests even though i have specified them as false, and I missing something?

https://github.com/saltstack/salt/pull/41413/commits/3a1eb2ed54ddc1526efe74f62682138fe672ace4

I thought that the above commit would make it so that the venafi tests only run when `--venafi` is passed?

https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/11449/
https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/11579/

**Comment by gtmanfred** [comment]
Should we just put these tests under the cloud tests?

**Comment by cachedout** [comment]
@gtmanfred I wouldn't be opposed to just putting them under the cloud tests but let's also bring in @saltstack/team-core to discuss.

**Comment by rallytime** [comment]
Cloud tests sound good to me.

**Comment by gtmanfred** [comment]
I created a `--external-api-tests` flag that we can just add to the cloud providers test runs in jenkins until we have more external api tests.

**Comment by cachedout** [comment]
@gtmanfred Some test failures: https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/11608/testReport/junit/unittest.loader.ModuleImportFailure.integration/externalapi/test_venafi/

**Comment by gtmanfred** [comment]
Bah, that is because i put the expensive and destructive on the random names function and not the TestCase, this one should hopefully pass

**Review by rallytime — APPROVED** [review]

**Pull request merged**
