### PR TITLE
Add AWS KMS support to S3

### PR DESCRIPTION
**Pull request by techhat**

### CODE REVIEW

**Comment by rallytime** [comment]
Refs #25246

**Comment by rterbush** [comment]
@rallytime any chance this could make it into 2015.8.2?

**Comment by rallytime** [comment]
@rterbush I think this one should stay in develop. It touches a lot of files and after chatting with @techhat about the change, we'd like this change to have a chance to simmer in the develop branch and get any bugs worked out before making it into an official release.

**Comment by rterbush** [comment]
What, if any, is the suggested work around to be able to use KMS encryption keys in the meantime?

**Comment by rallytime** [comment]
The only thing to do in the mean time would be to apply this patch to your Salt installation.

**Comment by rterbush** [comment]
I suspect that would mean patching minions as well, and in environment
where I am also managing Windows minions, this seems to be too far on the
edge.

I'd happily get out there if there was some reasonable short window that
was needed to validate these changes. Let me know if I can help to get this
out sooner than later. This may be a show stopper for us.

--
Randy

**Comment by lorengordon** [comment]
@rterbush, it's not all that difficult to drop in custom modules...try adding the boto modules into a '_modules' directory within your file_roots base environment.

**Pull request merged**
