### PR TITLE
Normalize pkg.upgrade and raise CommandExecutionError on failure

### LINKED ISSUE #36422: No error Reporting for (yum)pkg.upgrade
Running the module pkg.upgrade or state pkg.uptodate, there is no error logged back to the master if the yum-command behind it errors. Hence the state or module succeeds but in fact it isn't. The minion logs this message in the logfile but nothing is passed back to the master. This is very similar to  **No error Reporting for pkg.install #3433**, but this is with yum, not apt.

### Setup
Running two systems with CentOS/RHEL/OracleLinux 7.2 with the following message in the salt-minion-logfile:
```
2016-09-19 22:20:56,075 [salt.fileclient  ][INFO    ][2635] Fetching file from saltenv 'base', ** done ** 'maintenance/check-updates.sls'
2016-09-19 22:20:56,081 [salt.state       ][INFO    ][2635] Running state [pkg.upgrade] at time 22:20:56.081200
2016-09-19 22:20:56,081 [salt.state       ][INFO    ][2635] Executing state module.run for pkg.upgrade
2016-09-19 22:20:56,140 [salt.loaded.int.module.cmdmod][INFO    ][2635] Executing command ['yum', '--quiet', 'clean', 'expire-cache'] in directory '/root'
2016-09-19 22:20:56,309 [salt.loaded.int.module.cmdmod][INFO    ][2635] Executing command ['yum', '--quiet', 'check-update'] in directory '/root'
2016-09-19 22:20:59,406 [salt.loaded.int.module.cmdmod][INFO    ][2635] Executing command ['rpm', '-qa', '--queryformat', '%{NAME}_|-%{EPOCH}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-(none)\n'] in directory '/root'
2016-09-19 22:20:59,907 [salt.loaded.int.module.cmdmod][INFO    ][2635] Executing command ['systemd-run', '--scope', 'yum', '--quiet', '-y', 'upgrade'] in directory '/root'
2016-09-19 22:21:00,950 [salt.minion      ][INFO    ][2428] User root Executing command saltutil.find_job with jid 20160919222100949159
2016-09-19 22:21:01,004 [salt.minion      ][INFO    ][2648] Starting a new job with PID 2648
2016-09-19 22:21:01,026 [salt.minion      ][INFO    ][2648] Returning information for job: 20160919222100949159
2016-09-19 22:21:02,648 [salt.loaded.int.module.cmdmod][ERROR   ][2635] Command '['systemd-run', '--scope', 'yum', '--quiet', '-y', 'upgrade']' failed with return code: 1
2016-09-19 22:21:02,648 [salt.loaded.int.module.cmdmod][ERROR   ][2635] output: Running as unit run-2645.scope.
Error: Package: kernel-uek-4.1.12-61.1.6.el7uek.x86_64 (oraclelinux7-uek4-x86_64)
           Requires: dracut-kernel >= 033-360.0.3
           Installed: dracut-033-359.0.1.el7.x86_64 (@anaconda/7.2)
               dracut-kernel = 033-359.0.1.el7
Error: Package: kernel-uek-4.1.12-61.1.6.el7uek.x86_64 (oraclelinux7-uek4-x86_64)
           Requires: linux-firmware >= 20160604-44.git57b649d9.0.2
           Installed: linux-firmware-20150904-43.git6ebf5d5.0.1.el7.noarch (@anaconda/7.2)
               linux-firmware = 20150904-43.git6ebf5d5.0.1.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
2016-09-19 22:21:02,649 [salt.loaded.int.module.cmdmod][INFO    ][2635] Executing command ['rpm', '-qa', '--queryformat', '%{NAME}_|-%{EPOCH}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-(none)\n'] in directory '/root'
2016-09-19 22:21:03,124 [salt.state       ][INFO    ][2635] {'ret': {}}
2016-09-19 22:21:03,124 [salt.state       ][INFO    ][2635] Completed state [pkg.upgrade] at time 22:21:03.124381 duration_in_ms=7043.181
2016-09-19 22:21:03,127 [salt.minion      ][INFO    ][2635] Returning information for job: 20160919222055924376
```

On the master we see nothing:
```
2016-09-19 22:21:00,951 [salt.master      ][INFO    ][14175] User root Published command saltutil.find_job with jid 20160919222100949159
2016-09-19 22:21:01,081 [salt.utils.job   ][INFO    ][14188] Got return from minion for job 20160919222100949159
2016-09-19 22:21:03,139 [salt.utils.job   ][INFO    ][14177] Got return from minion for job 20160919222055924376
```

### Steps to Reproduce Issue
Remove something that breaks the yum-upgrade-process, for instance a dependancy, some repo or the GPG-key and run the state or module. Watch the salt-minion-logfile report the error and the error-code (1) and watch an empty state or module output on the master, running the job.

### Versions Report
My setup is as follows on my master:
```
[root@master maintenance]# salt-call --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 14 2016, 08:35:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: oracle 7.2
        machine: x86_64
        release: 4.1.12-61.1.6.el7uek.x86_64
         system: Linux
        version: Oracle Linux Server 7.2
````

My minion:
````
[root@minion maintenance]# salt-call --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 21 2015, 00:39:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: oracle 7.2
        machine: x86_64
        release: 4.1.12-37.6.3.el7uek.x86_64
         system: Linux
        version: Oracle Linux Server 7.2
````

### PR DESCRIPTION
**Pull request by terminalmage**
CommandExecutionError was modified starting in the 2016.3 branch to allow for
additional info to be included and printed in the exception output. The
pkg.uptodate state was modified to look for these exceptions, but the
pkg.upgrade funcs were never modified to actually raise these exceptions
when the install returned a nonzero exit status. In the process of
adding these exception raises to the pkg providers, I realized that they
also have inconsistent returns. This commit normalizes the pkg.upgrade
funcs to only return the changes, similar to pkg.install, and raises an
exception containing the changes and cmd.run_all return data in the
exception info.

It also sets the versionadded properly for the new xbps module, and
removes some of the "XXX" messages from the top-level docstring so that
they are hidden from the docs. I think the original submitter of this
code just did not know they would be included in the docs.

Resolves #36422.

### CODE REVIEW

**Comment by lorengordon** [comment]
I'm strangely excited about this normalization. I've been getting more frustrated by the variation in returns from salt modules. What do you think about describing the return type and structure in the docstring?

**Comment by cachedout** [comment]
If this is something that can be sensibly documented in a docstring then I certainly echo @lorengordon 's suggestion.

**Comment by terminalmage** [comment]
Yeah, that's a great idea. I also need to run another test on the error catching. It just occurred to me that if there are additional non-changes data in the "info" param passed when raising the exception, they may not be indented in the comment field of the highstate output. So you may have the additional info be all the way to the left of the console, making it tough to read. Would be an easy fix if this is the case, just need to test it.

**Comment by terminalmage** [comment]
OK, the output is already properly indented, that was just a hunch that I had but hadn't followed up on. I can confirm however that the additional info, when displayed in the highstate outputter, is properly indented.

@lorengordon with regard to the information on the return data, this was already there in all (or nearly all) implementations of ``pkg.upgrade``, but I fixed the formatting to use a python code block which will give these mentions a cosmetic change with Python syntax highlighting.

Interestingly enough, even the functions that were returning pseudo-state return dicts (with ``name``, ``comment``, etc.) keys, still had the documentation in their docstrings saying that they were returning just the changes. So the documentation was completely inaccurate there until I changed the return data for them.

**Comment by terminalmage** [comment]
Pending any futher concerns this is probably good to merge, then.

**Comment by lorengordon** [comment]
Thanks @terminalmage. I admit my comment was a more general frustration that's been building over time than one specific to this PR/function. Sorry for the noise.

Do you know, does salt's sphinx template support `:return:` and `:rtype:` fields?

http://www.sphinx-doc.org/en/stable/domains.html#info-field-lists

**Comment by terminalmage** [comment]
It does, and I think they're already in use in some places (like [here](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html#salt.states.pkg.installed)).

**Comment by terminalmage** [comment]
And don't worry about the noise, I was able to get a productive change out of it, altering these examples to have Python syntax highlighting. That's a win in my book. :smile:

**Comment by cachedout** [comment]
@terminalmage Could you please fix up the lint errors?

**Comment by terminalmage** [comment]
@cachedout Lint should be fixed, but this will conflict with https://github.com/saltstack/salt/pull/36495 and should be rebased once that PR is merged.

**Comment by cachedout** [comment]
@terminalmage It merged cleanly.

**Comment by terminalmage** [comment]
OK cool, it seemed to me that it shouldn't have. Thanks for following up.

**Pull request merged**
