### PR TITLE
Prevent ssh_auth.absent from running when test=True

### LINKED ISSUE #29262: ssh_auth.absent removes keys when test=True
Title says it all.

This only affects 2015.8, possibly `develop` as well. 2015.5 is fine.

### PR DESCRIPTION
**Pull request by anlutro**
fixes #29262

### CODE REVIEW

**Comment by anlutro** [comment]
Anything I should do with the test that's failing? It seems unrelated.

**Comment by cachedout** [comment]
@anlutro It looks as though it might be related.

@jfindlay Could you jump in and have a look here please? Perhaps you can help out.

**Comment by anlutro** [comment]
I see why it's failing - the `source` arg needs to be checked before the `if __opts__['test']`.

**Comment by anlutro** [comment]
Nevermind, the mocks in the tests were flawed - set up to return values they shouldn't return.

**Comment by cachedout** [comment]
@anlutro OK. Could you modify the tests and include them in this PR?

**Comment by anlutro** [comment]
@jfindlay done - hopefully the commit message explains what was wrong well

**Comment by anlutro** [comment]
Er, that mention above was for @cachedout - oops.

**Comment by cachedout** [comment]
Looks good. Thanks, @anlutro

**Pull request merged**
