### PR TITLE
Add execution and state modules for managing Windows SMTP server

### PR DESCRIPTION
**Pull request by m03**
### What does this PR do?
- Adds ability to manage native Windows 2008/2012 Server SMTP virtual servers.
### What issues does this PR fix or reference?
- None.
### Previous Behavior
- Ability to manage native Windows SMTP server via Salt modules did not previously exist.
### New Behavior
- Adds ability to manage native Windows 2008/2012 Server SMTP virtual servers.
### Tests written?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by m03** [comment]
The build failures seem to revolve around missing docstrings for boto_* modules, Tornado IOLoop errors, and TestMinionSaltAPIHandler.test_get_no_mid, of which I don't think any apply to the changes in this PR.

**Comment by cachedout** [comment]
Hi @m03 

Overall, this looks pretty good. My main concern are the argspecs that rely on `*args` and `**kwargs`. Typically, we try to go to great lengths to make these explicit. There are some internal validation routines that check the argspecs to make sure that we're passing sane values and those aren't able to run correctly with simple `*args` and `**kwargs`. Secondly, we do some parsing of those argspecs to generate docs and we'd prefer to make it as easy as possible for people to understand what to pass to these functions.

Could you let me know what you think about possibly changing some of those to be more explicit? Thanks.

**Comment by m03** [comment]
@cachedout No sweat, I was trying to aim for ease of use when using the execution module, but I see your point. Will follow up with changes in the next couple of days.

**Comment by cachedout** [comment]
@m03 Great! Thanks very much. I look forward to getting this one in.

**Comment by cachedout** [comment]
@m03 Just following up with you here. Could you let me know where we are on this one, please?

**Comment by m03** [comment]
@cachedout Hectic schedule got in the way. I'm planning on having the changes tested and ready to re-review this weekend.

**Comment by m03** [comment]
@cachedout To clarify for my own understanding and impact on other modules I'm working on, is the issue more with naming the arguments 'args' and 'kwargs', or how they're being used (or abused) in the module, or a combination of both?

**Comment by cachedout** [comment]
The issue is that we want them to be explicit, wherever possible. So, instead of taking `*args` and then splitting them out positionally inside the function to `my_arg1`, `my_arg2`, we'd rather just see the function argpsec have `my_func(my_arg1, my_arg2):`.

Same goes for kwargs. Of course, sometimes you don't know what the kwargs will be. In those cases, we prefer something like `additional_opts=None` versus just blindly accepting `**kwargs`. This makes documentation easier and it's easier for people coming to the function for the first time to understand what sort of data the function is expecting.

Does that help?

**Comment by m03** [comment]
@cachedout It does help. I've made changes accordingly, just need to test everything before I push the revised version.

**Comment by cachedout** [comment]
@m03 Sounds great. Just ping me when it's all ready to go. Thanks!

**Comment by m03** [comment]
Not sure why the failure with salt-pr-lint-n is happening...it's reporting "No problems were identified" in the details, and manually running pylint with Salt's .pylintrc gives 10/10 for both the execution and state modules.

**Comment by m03** [comment]
@cachedout Ping. Ready for re-review.

**Comment by cachedout** [comment]
Looks great. Merged! Thanks for this excellent contribution, @m03

**Pull request merged**
