### PR TITLE
add ability to customize cloud config options in cloud runner functio…

### PR DESCRIPTION
**Pull request by jacobweinstock**
add ability to customize cloud config options in cloud runner functions: destroy and action

### What does this PR do?
This adds the ability to pass in custom cloud config options, like providers, through the opts variable.
### What issues does this PR fix or reference?
N/A

### Tests written?

No

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by cachedout** [comment]
I'd like to have @gtmanfred have a look at this?

**Review by gtmanfred — APPROVED** [review]
This seems good, we already allow this to be done with the other cloud functions.

**Comment by gtmanfred** [comment]
Can you also add this for `map_run`?

Thanks,
Daniel

**Comment by cachedout** [comment]
Bump @jacobweinstock

**Comment by jacobweinstock** [comment]
Ahh, sorry. I don't think i can fix this branch anymore, screwed it up pretty good. I'm going to remove this pull request and submit a new one. Apologizes.

**Comment by jacobweinstock** [comment]
@cachedout - New Pull Request: https://github.com/saltstack/salt/pull/44523

**Pull request closed without merging**
