### PR TITLE
Add --no-parse CLI option to salt, salt-call, salt-run, and salt-ssh

### LINKED ISSUE #39986: JSON array structure incorrectly rendered
### Description of Issue/Question
The JSON standard for an array is that it starts with a [ (left bracket) and ends with a ] (right bracket), with values between these being separated by a comma (http://www.json.org/index.html).

When using the salt runner module the array structure is being incorrectly formatted with whole array being wrapped in quotation marks("), including the left and right brackets, which makes the JSON structure incorrect.

### Steps to Reproduce Issue
I am running the following salt-run command against a Pure Storage FlashArray's RestAPI service:
```
# salt-run http.query https://10.234.112.107/api/1.8/host/salt-host method=POST data='{"wwnlist": ["0011223344556677","1122334455667788"]}' persist_session=True verify_ssl=false
error:
    HTTP 400: BAD REQUEST
status:
    400
```

Log file from storage array receiving incorrectly formed JSON structure:

```
2017-03-13 11:19:26.095 [INFO] 10.234.112.46 >> POST http://10.234.112.107/api/1.8/host/salt-host
{
  "wwnlist":"['0011223344556677', '1122334455667788']"
}
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pure/rest/controller/util.py", line 97, in execute
    (command, args) = get_args(command_list, version, params)
  File "/usr/lib/python2.7/dist-packages/pure/rest/controller/util.py", line 392, in get_args
    raise RestException("Value of argument {} needs to be one of {}.".format(key, arg.arg_type), Code.BAD_REQUEST)
RestException: Value of argument wwnlist needs to be one of ['list'].
2017-03-13 11:19:26.101 [WARNING] << 400 BAD REQUEST
{
  "msg":"Value of argument wwnlist needs to be one of ['list']."
}
```
The Pure Storage RestAPI works with Ansible URI module calls as well as Puppet and Python calls. Only Salt causes this error.

### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-21-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

### PR DESCRIPTION
**Pull request by terminalmage**
# SUMMARY

This allows for these commands to bypass Salt's normal behavior of passing CLI input through PyYAML to ensure it is loaded as a proper Python data type.

**NOTE:** This only works on named CLI arguments (e.g. ``argname=value``), since ``salt.utils.args.parse_input()`` doesn't have access to the function name, nor the argspec of the function being called.

Fixes #39986.

# Testing Instructions

## Launch Docker container
Replace ``~/git/salt/issue39986`` with location of your git checkout. Use [this walkthrough](https://help.github.com/articles/checking-out-pull-requests-locally/) if you would like to checkout this PR into a local branch in your clone.

```
% docker run --rm -it -v ~/git/salt/issue39986:/testing terminalmage/issues:39986
```

## Test salt-ssh
The first command below launches sshd so you can test salt-ssh with localhost.
```
[root@83bf50621724 /]# /usr/sbin/sshd
[root@83bf50621724 /]# salt-ssh test test.arg foo='{bar: baz}' bar='{bar: baz}' abc=9 def=9 --no-parse=foo,abc --out=pprint
{'test': {'args': [],
          'kwargs': {'__pub_fun': 'test.arg',
                     '__pub_jid': '20170524214617987786',
                     '__pub_pid': 96,
                     '__pub_tgt': 'salt-call',
                     'abc': '9',
                     'bar': {'bar': 'baz'},
                     'def': 9,
                     'foo': '{bar: baz}'}}}
```

## Test masterless salt-call
```
[root@83bf50621724 /]# salt-call --local test.arg foo='{bar: baz}' bar='{bar: baz}' abc=9 def=9 --no-parse=foo,abc --out=pprint
{'local': {'args': (),
           'kwargs': {'__pub_fun': 'test.arg',
                      '__pub_jid': '20170524214653027465',
                      '__pub_pid': 143,
                      '__pub_tgt': 'salt-call',
                      'abc': '9',
                      'bar': {'bar': 'baz'},
                      'def': 9,
                      'foo': '{bar: baz}'}}}
```

## Test normal salt-call
The first command below starts the master and minion daemons.
```
[root@83bf50621724 /]# salt-master -d; salt-minion -d
[root@83bf50621724 /]# salt-call test.arg foo='{bar: baz}' bar='{bar: baz}' abc=9 def=9 --no-parse=foo,abc --out=pprint
{'local': {'args': (),
           'kwargs': {'__pub_fun': 'test.arg',
                      '__pub_jid': '20170524214740783331',
                      '__pub_pid': 700,
                      '__pub_tgt': 'salt-call',
                      'abc': '9',
                      'bar': {'bar': 'baz'},
                      'def': 9,
                      'foo': '{bar: baz}'}}}
```

## Test command published from the master
```
[root@83bf50621724 /]# salt test test.arg foo='{bar: baz}' bar='{bar: baz}' abc=9 def=9 --no-parse=foo,abc --out=pprint
{'test': {'args': [],
          'kwargs': {'__pub_arg': [{'abc': '9',
                                    'bar': {'bar': 'baz'},
                                    'def': 9,
                                    'foo': '{bar: baz}'}],
                     '__pub_fun': 'test.arg',
                     '__pub_jid': '20170524214926205767',
                     '__pub_ret': '',
                     '__pub_tgt': 'test',
                     '__pub_tgt_type': 'glob',
                     '__pub_user': 'root',
                     'abc': '9',
                     'bar': {'bar': 'baz'},
                     'def': 9,
                     'foo': '{bar: baz}'}}}
```

## Test runner
```
[root@83bf50621724 /]# salt-run test.arg foo='{bar: baz}' bar='{bar: baz}' abc=9 def=9 --no-parse=foo,abc --out=pprint
{'args': (),
 'kwargs': {'abc': '9', 'bar': {'bar': 'baz'}, 'def': 9, 'foo': '{bar: baz}'}}
[root@83bf50621724 /]# salt-call publish.publish test test.arg foo='{bar: baz}' bar='{bar: baz}' abc=9 def=9 --no-parse=foo,abc --out=pprint
The following keyword arguments are not valid: foo={bar: baz}, bar={'bar': 'baz'}, abc=9, def=9
[root@83bf50621724 /]# salt-call publish.publish test test.arg arg='["foo={bar: baz}", "bar={bar: baz}", abc=9, def=9]' --no-parse=foo,abc --out=pprint
{'local': {'test': {'args': [],
                    'kwargs': {'__pub_arg': [{'abc': '9',
                                              'bar': {'bar': 'baz'},
                                              'def': 9,
                                              'foo': '{bar: baz}'}],
                               '__pub_fun': 'test.arg',
                               '__pub_id': 'test',
                               '__pub_jid': '20170524215150058398',
                               '__pub_ret': '',
                               '__pub_tgt': 'test',
                               '__pub_tgt_type': 'glob',
                               '__pub_user': 'root',
                               'abc': '9',
                               'bar': {'bar': 'baz'},
                               'def': 9,
                               'foo': '{bar: baz}'}}}}
```

## Test peer-publishing a remote-exec func
```
[root@f8b423e56470 /]# salt-call publish.publish test test.arg arg='["foo={bar: baz}", "bar={bar: baz}", abc=9, def=9]' --no-parse=foo,abc --out=pprint
{'local': {'test': {'args': [],
                    'kwargs': {'__pub_arg': [{'abc': '9',
                                              'bar': {'bar': 'baz'},
                                              'def': 9,
                                              'foo': '{bar: baz}'}],
                               '__pub_fun': 'test.arg',
                               '__pub_id': 'test',
                               '__pub_jid': '20170524220332429444',
                               '__pub_ret': '',
                               '__pub_tgt': 'test',
                               '__pub_tgt_type': 'glob',
                               '__pub_user': 'root',
                               'abc': '9',
                               'bar': {'bar': 'baz'},
                               'def': 9,
                               'foo': '{bar: baz}'}}}}
```

## Test peer-publishing a runner func
```
[root@83bf50621724 /]# salt-call publish.runner test.arg arg='["foo={bar: baz}", "bar={bar: baz}", abc=9, def=9]' --no-parse=foo,abc --out=pprint
{'local': {'args': [],
           'kwargs': {'abc': '9',
                      'bar': {'bar': 'baz'},
                      'def': 9,
                      'foo': '{bar: baz}'}}}
```

### CODE REVIEW

**Comment by rallytime** [comment]
Looks like a related test needs some ❤️ here @terminalmage :)

**Review by cachedout — COMMENTED** [review]
I see no way for a user to discern what this flag does. Am I missing it?

**Comment by terminalmage** [comment]
@cachedout There is an explanation when you run ``salt -h``. It's at or near the bottom of the output.

**Comment by terminalmage** [comment]
However, I'm open to ideas for making the functionality more visible/apparent.

**Comment by terminalmage** [comment]
I could not reproduce the test failures locally, but regardless I'm pretty certain I know what caused them. I just pushed a commit, we'll see if the test passes.

**Comment by terminalmage** [comment]
Test is passing now.

**Pull request merged**
