### PR TITLE
Added request_interval feature to wait_for_successful_query module

### PR DESCRIPTION
**Pull request by Oloremo**
### What does this PR do?
Added `request_interval` kwargs to the http.wait_for_successful_query module to be aligned with the state.

### What issues does this PR fix or reference?
#53738 

### Previous Behavior
`request_interval` was not supported in the `http.wait_for_successful_query` module

### New Behavior
`request_interval` now supported in the `http.wait_for_successful_query` module

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by dwoz** [comment]
re-run full centos-7-py2

**Comment by dwoz** [comment]
re-run full debian10-py3

**Review by dwoz — APPROVED** [review]

**Review by Ch3LL — APPROVED** [review]

**Review by s0undt3ch — APPROVED** [review]

**Comment by Oloremo** [comment]
re-run full amazon2-py2

**Comment by Oloremo** [comment]
re-run full centos7-py3-pycryptodomex

**Comment by Oloremo** [comment]
re-run full macosxmojave-py2

**Comment by Oloremo** [comment]
re-run full macosxmojave-py3

**Pull request merged**
