### PR TITLE
Backport systemd and yum/dnf optimizations from develop into 2015.8

### PR DESCRIPTION
**Pull request by terminalmage**

### CODE REVIEW

**Comment by terminalmage** [comment]
The systemd unit tests need to be revised after these changes.

**Comment by terminalmage** [comment]
I have no idea why this code is triggering our custom lint warning, this is an empty line. @s0undt3ch, thoughts?

https://jenkins.saltstack.com/job/salt-pr-lint-n/12926/violations/file/salt/modules/yumpkg.py/

**Comment by terminalmage** [comment]
I found the actual pylint error in the console output and have fixed it. I have also fixed the systemd tests. We should see them all passing now.

**Comment by terminalmage** [comment]
OK, remaining test failures should be resolved once these tests run.

**Comment by terminalmage** [comment]
Tests passing.

**Comment by cachedout** [comment]
Nice one, @terminalmage. These changes are the goodness.

**Pull request merged**
