### PR TITLE
Added test and fix for #28608.

### PR DESCRIPTION
**Pull request by scott-w**
This PR modifes the `_strip_listing_to_done` to also remove `WARNING` strings.

### CODE REVIEW

**Comment by cachedout** [comment]
@scott-w This is not passing this RabbitMQ tests. Could you please have another look? Thanks.

**Comment by scott-w** [comment]
Yeah I'll give it a once over when I've got a chance next week.

**Comment by cachedout** [comment]
@scott-w Great! Thank you.

**Comment by jfindlay** [comment]
Fixes #28608.

**Comment by cachedout** [comment]
Thanks @scott-w ! Much appreciated.

**Pull request merged**
