### PR TITLE
Add support for __env__ catchall in topfile

### PR DESCRIPTION
**Pull request by streambinder**
### What does this PR do?

Add support for `__env__` catchall saltenv in topfile.

### What issues does this PR fix or reference?

None.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [X] Docs (not applicable)
- [X] Changelog
- [X] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by streambinder** [comment]
Hey, @dhiltonp, no updates about this?

**Comment by waynew** [comment]
Hey @streambinder, just got a chance to look at this... what is the purpose of this proposed `__env__`?

**Comment by streambinder** [comment]
It's basically adding, at the topfile level, the [same behaviour applied on `file_roots`](https://docs.saltproject.io/en/latest/topics/tutorials/gitfs.html#using-gitfs-alongside-other-backends), where you can use the `__env__` keyword to define a default env, if none of the explicitly defined ones match with the one requested by the minion.

**Comment by waynew** [comment]
Ah, bringing thing into consistency *is* quite a good thing. I'll take a closer look at this probably tomorrow

**Comment by whytewolf** [comment]
I'm trying to figure what the benefit of this over

```
{{saltenv}}:
  'minion':
    - thing
```

**Review by twangboy — APPROVED** [review]

**Comment by waynew** [comment]
I'm agreeing with @whytewolf here, also we're missing details about how this is even supposed to work.

I tried this top.sls

```
base:
  '*':
    - all_success

bloop:
  '*':
    - some_success

__env__:
  '*':
    - test_success
```

(using a file_roots with an `__env__`, and the sls files are just a couple of `bloop: test.nop` states)

When I run 

    salt-call --local state.apply saltenv=bloop

I get the expected some_success

When I run without saltenv I actually get all_success and test_success. Which I don't think is supposed to happen?

    salt-call --local state.apply saltenv=fnord
    
Doesn't actually work. Interestingly enough, using the `{{ saltenv }}` approach:

- bloop fails, because there's a duplicate id
- no env only does `all_success`
- a non-existent saltenv gives the `test_success`

@streambinder  If you're still interested in this functionality, could you explain what the intended behavior is for these scenarios are/how this should be used, and why `{{ saltenv }}` wont work?

**Comment by streambinder** [comment]
It could be, at the time of writing, I was not aware of `{{ saltenv }}` catch-all in topfiles.
I figured proposing an approach consistent to how file_roots behave was the best.
Anyhow, I'm no more working with SaltStack, so I'm not explicitly interested in this to get merged anymore, so feel free to do what you believe it's the best in terms of direction :)

**Comment by whytewolf** [comment]
lets go ahead and close this as I believe the functionality is already supposed to exist. and while dunders are useful in the master config. putting them into the state tree is not something consistent.

**Pull request closed without merging**
