### PR TITLE
Sqlite3 state shouldn't change anything if the rows already match, even when update=True

### PR DESCRIPTION
**Pull request by clinta**

### CODE REVIEW

**Comment by jfindlay** [comment]
@clinta, do you think this should go into 2015.5 and 2015.8?

**Comment by clinta** [comment]
I think it should be in 2015.5. Using `update=true` without it is pretty problematic.

**Comment by jfindlay** [comment]
Thanks, @clinta.  You are welcome to submit fixes directly to the oldest supported release branch in that case.  You don't need to do it this time, though, we'll backport it.  Thanks for the excellent work.

**Comment by rallytime** [comment]
The Sqlite3 state is new to the develop branch, so I'm not going to backport this change. :)

**Pull request merged**
