### PR TITLE
remove GPG_1_3_1 check

### LINKED ISSUE #62895: [BUG] Remove outdated gnupg check
**Description**
Remove the following check
```GPG_1_3_1 = _LooseVersion(gnupg.__version__) >= _LooseVersion("1.3.1")```
from the ```gpg.py``` execution module.   

I'm not even sure what version that's referring to. The current release is ```0.5.0```  
It appears that this ```1.3.1``` version never existed. 
https://github.com/vsajip/python-gnupg#050

The oldest version of ```gnupg.py``` on github dates back to 2008
https://github.com/vsajip/python-gnupg/blob/5f3d64b4865d88991bed261798f66aa63c490adc/gnupg.py

And even this version doesn't need to the conditions enforced by that ```GPG_1_3_1``` check. 

**Setup**

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
N/A code maintenance issue

**Expected behavior**
N/A code maintenance issue. 

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: 4.0.9
     gitpython: 3.1.27
        Jinja2: 3.0.3
       libgit2: 1.3.1
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.15.0
        pygit2: 1.7.1
        Python: 3.11.0rc2 (main, Sep 13 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-1)]
  python-gnupg: 0.5.1.dev0
        PyYAML: 6.0
         PyZMQ: 23.2.0
         smmap: 5.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: fedora 37 Thirty Seven
        locale: utf-8
       machine: x86_64
       release: 5.19.14-300.fc37.x86_64
        system: Linux
       version: Fedora Linux 37 Thirty Seven
```
</details>

### PR DESCRIPTION
**Pull request by leifliddy**
### What does this PR do?
Removes unneeded GPG_1_3_1 check from the ```gpg.py``` execution module

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/62895

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html

### Commits signed with GPG?
Yes

Note:
This is the first of multiple PR's I have planned for the ```gpg.py``` execution model

### CODE REVIEW

**Comment by leifliddy** [comment]
@garethgreenaway I'm not sure a test case applies here as this is simply a code maintenance issue -- it's not resolving a bug or adding a new feature. It's simply removing a check for an ancient version of `python-gnupg`. How would you propose creating a testcase for something like that?

**Review by OrangeDog — COMMENTED** [review]
As discussed on the issue, author was looking at the wrong library.

**Comment by leifliddy** [comment]
Just to recap. The version `1.3.1` refers to the https://pypi.org/project/gnupg/ library which salt doesn't (officially) support. 
According to the gpg module documentation https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.gpg.html
The `python-gnupg` library is the officially supported library -- and that library has never had a version 1.3.1 release.

**Comment by garethgreenaway** [comment]
@leifliddy I added the "TestCase" labels based on the quick glance at the files changed, anytime any functionality is changed we want to see a test(s) added to ensure the changes work as expected and additionally to ensure the underlying code isn't changed later with the tests not being updated to reflect those changes, eg. code changed and tests fail.  As far as the different versions of GPG, I believe I originally wrote that code and support for both versions was included because at the time different distributions provided different packaged versions of the GPG python library.  If one of those two libraries is no longer actively being developed  then we should deprecate that version, but that will need to follow our normal deprecation path of at least two major versions.

**Comment by leifliddy** [comment]
Cool, thanks for the explanation!

So are we assuming that `python-gnupg` and `gnupg` have feature parity with each other? 
If the salt documentation specifically states that `python-gnupg` 
 must be installed in order for the gpg module to function https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.gpg.html
then the question becomes was the `gnupg` version every officially supported? I think a lot of assumptions have to made to make that case. Maybe it just worked and nobody really noticed. Is there any documentation that shows that `gnupg` is a salt-compatible library? Because if we're going to deprecate something -- it must have been supported in the first place right? Otherwise, what are we deprecating it from?

**Comment by OrangeDog** [comment]
> `python-gnupg` and `gnupg` have feature parity with each other?

Not exactly, that's why the code you're trying to delete is there.

> do you think they were testing it against both `python-gnupg` and `gnupg`?

Yes. Salt tests world have (or still are) run on platforms that ship the fork as `python-gnupg`.

> was the `gnupg` version ever officially supported?

"Officially" is very hard to pin down, as a lot of Salt has bad tests and bad documentation. Salt was (or still is?) officially shipped with the fork rather than the original `pythobn-gnupg` library.

IMO the easiest and most useful solution is to just add "or `gnupg`" to the documentation.

**Comment by leifliddy** [comment]
>Not exactly, that's why the code you're trying to delete is there.

C'mon I'm obviously refering to `gnupg` versions >= 1.3.1 
And no...if you look at the this https://github.com/vsajip/python-gnupg
There are many functions that don't appear in this project: https://github.com/isislovecruft/python-gnupg
How do you suggest that we reconcile that? That project is dead and hasn't been updated in several years. 
If you can only use functions that both libraries support, that's going to be a severaly limiting factor going forwards. 
Can you think of any other examples of where salt supports two different libraries for the same functionality? 
I'm not seeing any here:
https://github.com/saltstack/salt/blob/master/DEPENDENCIES.md

Also, what platform are still shipping `gnupg`? And do those platforms also ship `python-gnupg`?
Also which CI processes are testing with `gnupg`?

**Comment by OrangeDog** [comment]
> Can you think of any other examples of where salt supports two variants of the same library?

`pygit2` and `gitpython`
`MySQLdb`, `mysqlclient`, and `PyMYSQL`

> And do those platforms also ship python-gnupg?

No, they won't. They will have a package called `python-gnupg` or `python3-gnupg`, and it will be the forked version instead of the original.

**Comment by leifliddy** [comment]
>No, they won't. They will have a package called python-gnupg or python3-gnupg, and it will be the forked version instead of the original.

I'm looking for specifics. Exactly which distros are you referrring to?

**Comment by OrangeDog** [comment]
None that I can see, but perhaps @garethgreenaway remembers what it was.

**Comment by leifliddy** [comment]
`pygit2` and `gitpython` are not the same library.
ie
`import pygit2`
vs
`import git`
It's the same thing with the mysql packages you listed 
They all have different module names. 

What I was asking is whether there are any other python libraries (besides `python-gnupg` and `gnupg` ) that share the same module name that salt supports. 
Does that make sense?

**Comment by OrangeDog** [comment]
True, you do have to do `pymysql.install_as_MySQLdb()` first to get the idenatical module names.

How about `Pycrypto` and `Pycryptodome`?

**Comment by garethgreenaway** [comment]
I do not recall which distributions or which operating systems were using which GPG libraries by default, I just remember there was a need and a desire to support both at the time.  I'm sure some investigating using `git blame` could turn up some issues with details.  If the plan is to remove functionality or support for any particular Python libraries, then it will need to follow the standard deprecation path.  Including a warning if/when the particular libraries is imported or detected indicating that support for it will be removed in future versions.

**Comment by leifliddy** [comment]
> Including a warning if/when the particular libraries is imported

How could we possibly do that when both `python-gnupg` and `gnupg` share the same module name? `import gnupg`
I've asked this question multiple times, but where does it show that `gnupg` was ever supported in the first place?

**Comment by OrangeDog** [comment]
> How could we possibly do that 

By checking the version number, and presuming that the original library won't suddenly release 1.0 before the deprecation is complete.

**Comment by leifliddy** [comment]
Because `gnupg` is dead and ensuring compatibility between a dead library and an active one is not sustainable. 
First off, if someone modifies the `gnupg` execution module how would they know that they should test their changes against both library variants? Are any of the reviewers checking for that?  
The `python-gnupg` library has a function called `trust_keys` https://github.com/vsajip/python-gnupg/blob/master/gnupg.py
Let's say that I would like update the salt module to use this function vs using `cmd.run_all` . Ahhhh, but that `gnupg` library doesn't have a `trust_keys` function.

Same thing with the `INV_RECP` codes. The `gnupg` library doesn't support these. 
```
_INVALID_KEY_REASONS = {
    0: 'no specific reason given',
    1: 'not found',
    2: 'ambiguous specification',
    3: 'wrong key usage',
    4: 'key revoked',
    5: 'key expired',
    6: 'no crl known',
    7: 'crl too old',
    8: 'policy mismatch',
    9: 'not a secret key',
    10: 'key not trusted',
    11: 'missing certificate',
    12: 'missing issuer certificate',
    13: 'key disabled',
    14: 'syntax error in specification',
}
```
It's not clear that the salt gnupg module fully supports the `gnupg` library. Have you tested out every function? (I haven't)
There really should be a list of exactly what is supported and what isn't. How else can you write, test, and review code changes if it was just some ephemeral concept? Well...it seems to work, so I guess it's supported right? 
Simply because a `gnupg` version check exists with that module doesn't validate that check. What if the author was simply using the `gnupg` library and didn't realize they weren't using `python-gnupg`? Also, simply because thing seem to work between both library variants also doesn't validate its use. It just means we haven't run into compatibility issues yet. This will always (eventually) be the case with divergent code bases. I think the documentation should absolutely clear on what is and isn't supported. Let's sort the documentation issue out first. Because if that's not considered to be authoritative then everything else falls apart. 

But, just to be clear, you're suggesting that we perform a version check -- that version `>= 1.0` will be unsupported after a certain date. Well what happens when the `python-gnupg` version hits version 1.0? I think we need a better plan then that.

**Review by twangboy — DISMISSED** [review]

**Comment by leifliddy** [comment]
@OrangeDog Can you please approve this PR when you have a chance? If you still have issues with it, could you please give us some guidance on how we should be supporting two competing libraries? Also.....I have some more PR's in the pipeline that I'd like you to review : ) Thanks.

**Comment by OrangeDog** [comment]
I'm afraid I don't approve, for reasons @garethgreenaway and I have already detailed.
But then I'm also not staff so it doesn't matter what I think.

**Comment by leifliddy** [comment]
Ok, no worries. How do you think we should write, test, and review code using two variants of the same library?

**Comment by leifliddy** [comment]
@OrangeDog 
>IMO the easiest and most useful solution is to just add "or gnupg" to the documentation.

Just to be clear, your proposed solution to this is to retroactively add support for the `gnupg` library to the documentation?! 
Don't you think we should add that library to the unit and CI test's first!? 
The latest version of the `gnupg` library is this: https://pypi.org/project/pretty-bad-protocol/
Should we just chuck that library variant into the documentation as well?   
I still don't get how you would expect developers to test our their changes using multiple library variants.   
If you're going to propose a _solution_ like that -- then you need to back it up with an actual plan.

@garethgreenaway  
> If the plan is to remove functionality or support for any particular Python libraries, then it will need to follow the standard deprecation path. 

No worries, can you please show me the salt documentation where `gnupg` is listed as a supported library?
Or where we're performing any testing with the `gnupg` library?

**Comment by leifliddy** [comment]
@garethgreenaway Can you please comment on what specific steps need to be taken to merge this PR?

**Comment by leifliddy** [comment]
There are some changes I'd like to make to the `encrypt` function and I'm not sure how to deal with that `if GPG_1_3_1:` conditional check...or how to test for that condition. The `test_gpg` unit test doesn't use that `gnupg` library.

**Comment by leifliddy** [comment]
Just for the heck for it I installed that latest version of `gnupg`
```
gnupg                    2.3.1
```

And ran though the current `test_gpg` tests
```
python3 -m pytest -ra ./tests/pytests/unit/modules/test_gpg.py

============================================== short test summary info ===============================================
FAILED tests/pytests/unit/modules/test_gpg.py::test_search_keys - salt.exceptions.SaltInvocationError: The search_k...
FAILED tests/pytests/unit/modules/test_gpg.py::test_gpg_import_priv_key - assert False is True
FAILED tests/pytests/unit/modules/test_gpg.py::test_gpg_sign - assert False is True
===================================== 3 failed, 13 passed, 38 warnings in 4.00s ======================================
```
It failed on three. If anyone was testing with this library they would have caught these errors by now right?

**Comment by garethgreenaway** [comment]
@leifliddy Let's update the documentation for the module and include a note that the now outdated `gnupg` Python library and `pretty-bad-protocol` are not supported by this module, only `python-gnupg` and then I'm good to merge it.

**Comment by leifliddy** [comment]
@garethgreenaway Cool, thanks! I'll do that.

**Comment by leifliddy** [comment]
Interesting...I never realized the documentation was derived from the modules themselves. Ok, I modified the documentation with the requested change.
Feel free to edit that change if it's needed to fit a particular style.

**Pull request merged**
