### PR TITLE
SMTP documentation update

### PR DESCRIPTION
**Pull request by cingeyedog**
### What does this PR do?
Adds documentation to send email to multiple recipients.  The code was added in 2015.8, but the documentation wasn't added at the time.
### What issues does this PR fix or reference?
None. 

### Tests written?
No.  Change was documentation only.  Added to the 2018.3 as it was the oldest supported branch (as described in [Contributing](https://docs.saltstack.com/en/latest/topics/development/contributing.html).  It will need to be pulled forward.  I note that the examples are updated in 2019 branches.

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by DmitryKuzmenko** [comment]
@cingeyedog thank you for contribution. Could you please resolve merge conflicts?

**Comment by cingeyedog** [comment]
@DmitryKuzmenko I apologize.  Apparently I did the merge request incorrectly.  my only intent was to add the comments to salt/modules/smtp.py

**Comment by cingeyedog** [comment]
Should i close this request and try it again?

**Comment by DmitryKuzmenko** [comment]
@cingeyedog you can update this one or create a new one. Any way comfortable for you is appreciated.

**Review by dwoz — APPROVED** [review]

**Pull request merged**
