### PR TITLE
Make sure the path we're removing is present first - avoid an OSError

### PR DESCRIPTION
**Pull request by rallytime**
### What does this PR do?

Protects against hitting an OSError if the `t_path` we're trying to remove doesn't exist. 
### What issues does this PR fix or reference?

The original change was in #33328
### Previous Behavior

If the `t_path` directory didn't exist, an OSError would be thrown, causing the maintenance process on the master to die and restart in a loop.
### New Behavior

Avoids killing the process by not trying to remove a path that doesn't exist.

Thanks to @cachedout for the heads-up on this one.

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Let's do one check to see if it exists in the outer `for` loop instead of three per inner and just store the result. This is too inefficient right now.

**Comment by rallytime** [comment]
@cachedout Good call. I've updated the PR.

**Comment by cachedout** [comment]
Solid. Nice work.

**Pull request merged**
