### PR TITLE
fixes #20198: virt.get_graphics and virt.get_nics calls in module virt

### LINKED ISSUE #20198: virt.get_graphics, virt.get_nics are broken, in turn breaking other things
Given
```
# salt --versions-report
           Salt: 2014.7.1
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.5
   msgpack-pure: 0.1.3
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.0.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: 0.9.1
```
When I try to get more info with virt.full_info
```
# salt x01 virt.full_info    
x01:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1022, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/virt.py", line 1076, in full_info
        'vm_info': vm_info()}
      File "/usr/lib/python2.7/dist-packages/salt/modules/virt.py", line 720, in vm_info
        info[vm_] = _info(vm_)
      File "/usr/lib/python2.7/dist-packages/salt/modules/virt.py", line 710, in _info
        'graphics': get_graphics(vm_),
      File "/usr/lib/python2.7/dist-packages/salt/modules/virt.py", line 860, in get_graphics
        for key in g_node.attributes:
      File "/usr/lib/python2.7/xml/dom/minidom.py", line 522, in __getitem__
        return self._attrs[attname_or_tuple]
    KeyError: 0
```
And...
```
root@x01:/srv/scripts# salt x01 virt.get_graphics wheezy
x01:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1022, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/virt.py", line 860, in get_graphics
        for key in g_node.attributes:
      File "/usr/lib/python2.7/xml/dom/minidom.py", line 522, in __getitem__
        return self._attrs[attname_or_tuple]
    KeyError: 0
```

### PR DESCRIPTION
**Pull request by vdesjardins**

### CODE REVIEW

**Comment by rallytime** [comment]
Thanks for putting this fix together, @vdesjardins!

Refs #20198

**Comment by rallytime** [comment]
I have marked this pull request for back-porting, but, in the future, feel free to make bug-fixes against the earliest supported branch (that's 2014.7 right now) that needs the fix. Then, we will merge the changes forward so the fix can be present on all of the affected branches. Don't worry about this one, we will get it, but just for future reference.

We're happy to answer any questions about this workflow, or you can also read up on it here: http://docs.saltstack.com/en/latest/topics/development/contributing.html#id1

Thanks again!

**Comment by rallytime** [comment]
Also, thanks very much for writing a test!

**Comment by rallytime** [comment]
@vdesjardins Mind grabbing this pylint error really quickly?

https://jenkins.saltstack.com/job/salt-pr-lint-n/2824/violations/file/salt/modules/virt.py/

**Comment by vdesjardins** [comment]
Hi!

No problem for the patch! I'm happy to help where I can.

Thanks for the link on the workflow. I'm going to read it before my next contribution!

**Comment by rallytime** [comment]
Awesome! Thanks so much!

**Pull request merged**
