### PR TITLE
Correct network.wolmatch that failed on invalid arguments and ignore Loopback Interface for all OS

### PR DESCRIPTION
**Pull request by davidme4**
### What does this PR do?
Correction BUG on `network.wolmatch`  : 
- https://github.com/saltstack/salt/issues/57473 : invalid argument
- https://github.com/saltstack/salt/issues/57476 : error on Windows Loopback interface not ignored -> I propose to ignore interface base on mac not on name, as the interface name can be change on Windows...

### What issues does this PR fix or reference?
Fixes:
- https://github.com/saltstack/salt/issues/57473
- https://github.com/saltstack/salt/issues/57476

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs -> No impact on the doc 
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated -> No Existing test for network runner : test manually with 2 CentOS minion, 1 Windows7 and 1 Windows10

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by DmitryKuzmenko** [comment]
@davidme4 thank you for PR. We're not accepting changes not covered by tests anymore. Could you please consider writing tests for this? You can use any of the existing runners unit tests as an example. Let me know if you'll need help.
Also please address the lint and pre-commit ci failures. You can check what's wrong by clicking "details" and then "console output".

**Comment by xeacott** [comment]
@davidme4 Hey, is there any chance you would be able to write a test or two for this PR?

**Comment by davidme4** [comment]
Sorry I have no time for the moment

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
