### PR TITLE
Windows defaults to multiprocessing true

### LINKED ISSUE #30938: Windows: Upgrade overwrites minion config file
I just upgraded a Windows minion from 2015.8.0 to 2015.8.5 and noticed that the prior `minion` config file was overwritten. I thought based on the closing of a handful of other issues that this was no longer occurring, but it does not seem to be fixed yet.

It would really be nice to merge settings from a prior `minion` config file into the new `minion` config file.

### PR DESCRIPTION
**Pull request by twangboy**
Fixes #30938 

Multiprocessing defaults to True for windows
Removed special handling for windows in `config.py`

### CODE REVIEW

**Comment by cachedout** [comment]
Is this a change from the previous default?

**Comment by twangboy** [comment]
@cachedout Windows used to default False for multiprocessing. With 2015.8, it needs to default to True.

**Comment by cachedout** [comment]
Isn't this going to ensure a serious performance regression as outlined in #27866?

**Comment by twangboy** [comment]
@cachedout It's already the default... It's just that it sets multiprocessing: true through the config file on install instead of it being a minion default.
There are other issues that multiprocessing: true fixes. It was a trade off between slower performance and these two issues:
https://github.com/saltstack/salt/issues/23303#issuecomment-101757692
https://github.com/saltstack/salt/issues/14691

**Comment by twangboy** [comment]
We've been setting multiprocessing: True since 2015.8.0 via the config file. It needs to be moved to defaults since it's the default expected behavior for 2015.8

**Comment by cachedout** [comment]
We can merge this in order to keep the flag consistent but we *really* need to find a better solution for those issues than to do this. A performance decrease between 100% and 600% just to fix those two bugs is honestly just unacceptable.

**Pull request merged**
