### PR TITLE
Update

### PR DESCRIPTION
**Pull request by supertom**
Added documentation to support using the JSON format private key file instead of the .p12 file for versions of libcloud >= 0.17.0.

### CODE REVIEW

**Comment by jtand** [comment]
@supertom Thanks for the PR!

**Comment by supertom** [comment]
Looks like checks failed for 2a262a6?

**Comment by cachedout** [comment]
@rallytime Could you please take a look here? Thanks.

**Comment by rallytime** [comment]
Looks like the only change here is a doc fix, so the test failures are unrelated. The commit from me has already been merged into salt is fine. Thanks @supertom!

**Pull request merged**
