### PR TITLE
Rename obsolete beacon validation function

### PR DESCRIPTION
**Pull request by max-arnold**
### What does this PR do?

Small follow-up bugfix for #42317 to rename two remaining instances of beacon validation function from `__validate__` to `validate`:

* Use proper function name in the docs
* Rename validation function in the `aix_account` beacon (all other beacons are ok)

### Previous Behavior

`aix_account` beacon validator was ignored

### New Behavior

`aix_account` beacon validator should be called. 

### Tests written?

No. I don't have any AIX machine at hand :)

### CODE REVIEW

**Comment by max-arnold** [comment]
@garethgreenaway Aside from this fix, it looks like #35374 is no longer used and can be removed. I can try to roll it back if that is true.

**Comment by garethgreenaway** [comment]
@max-arnold Thanks!  PR looks good.  You are correct, the `__validate__` was renamed back to `validate` as it's called by the various beacon execution & state execution modules when a beacon is added.

**Comment by max-arnold** [comment]
Do you think it is worth undoing #35374? I can submit it as a separate PR, but I need some reassurance that it is not used somewhere else (like Salt Enterprise).

**Comment by garethgreenaway** [comment]
@max-arnold The changes in that PR should have already been undone.  Do you see a change in that PR that still exists somewhere in the code?  All the beacons, except for the aix beacon, have their validate functions in the correct state.  The only thing that still remains is probably the virtual_funcs, which I think we can safely leave as it might find a use at a later date.

**Comment by max-arnold** [comment]
Yep, I'm talking specifically about the `virtual_funcs`.

**Pull request merged**
