### PR TITLE
modules.trafficserver: Use lists for popen's commands and arguments

### LINKED ISSUE #45274: Trafficserver module fails when constructing arguments
### Description of Issue/Question
The trafficserver state and module always fail with:
`Passed invalid arguments: can only concatenate list (not "tuple") to list.`

This seems to boil down to: https://github.com/saltstack/salt/blob/80d90307b07b3703428ecbb7c8bb468e28a9ae6d/salt/modules/trafficserver.py#L35-L36
https://github.com/saltstack/salt/blob/80d90307b07b3703428ecbb7c8bb468e28a9ae6d/salt/modules/trafficserver.py#L39-L40

As a quick hack, converting the tuple to a list and stringifying seems to work around the issue (beware of potential for problems with shell escaping):
`return ' '.join([_TRAFFICCTL] + [str(arg) for arg in args])`
`return ' '.join([_TRAFFICLINE] + [str(arg) for arg in args])`

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
`apt install trafficserver`

### Steps to Reproduce Issue
`salt-call --local trafficserver.status`

### Versions Report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.10.0-42-generic
         system: Linux
        version: Ubuntu 16.04 xenial

### PR DESCRIPTION
**Pull request by NTmatter**
Fixes #45274

### What does this PR do?
Works around a failure to concatenate strings into a command line. Commands and arguments are instead passed around as lists, removing the need to escape spaces for the underlying shell.

Multiple debug statements are also moved into _subprocess method.

### What issues does this PR fix or reference?
Fixes #45274

### Tests written?
No

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by garethgreenaway — CHANGES_REQUESTED** [review]

**Comment by rallytime** [comment]
Hi @NTmatter - just a bump here to see if you saw the comments above.

**Comment by NTmatter** [comment]
Apologies for the delay. Back-to-Work season :) I've stripped out the extraneous list(), and things seem to be working after some limited testing.

**Comment by garethgreenaway** [comment]
@NTmatter thanks for the updated PR.  Looks like you've got a conflict here.

**Comment by rallytime** [comment]
@NTmatter Are you able to come back to this and resolve the merge conflict?

**Comment by NTmatter** [comment]
I should be able to get to it this weekend.

**Comment by NTmatter** [comment]
Rebased to current Develop branch.

**Comment by rallytime** [comment]
@garethgreenaway Can you come back to this and review it when you get a moment?

**Review by garethgreenaway — APPROVED** [review]

**Comment by garethgreenaway** [comment]
@NTmatter Looks like there is a merge conflict, can you circle back and take a look?

**Comment by rallytime** [comment]
@NTmatter Bump - can you resolve the merge conflicts here? We'd love to get this in.

**Comment by cachedout** [comment]
@rallytime I just went ahead and resolved them. Re-running tests now.

**Pull request merged**
