### PR TITLE
Replace salt.utils.locales.sdecode with salt.utils.data.decode

### PR DESCRIPTION
**Pull request by terminalmage**
With salt.utils.data.decode() being added in 2018.3.0, sdecode is now redundant. This commit deprecates sdecode in favor of salt.utils.data.decode().

### CODE REVIEW

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
@terminalmage There's a test failure on this PR:

- integration.states.test_file.FileTest.test_binary_contents

https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/22801/

Can you take a look?

**Review by isbm — APPROVED** [review]
Except the failing tests, the changes themselves looks OK.

**Comment by terminalmage** [comment]
@rallytime The grains test I could not reproduce and I don't think was related, but I've fixed the other test.

**Comment by isbm** [comment]
@terminalmage actually, in this case, shouldn't we entirely kill now unused code for `sdecode` and `sdecode_if_string` in `salt/utils/locales.py`?

**Comment by rallytime** [comment]
@terminalmage Yeah, the grains test is fixed upstream (or will be soon with a merge forward - I can't quite remember where that is at presently.)

But the binary contents test is still failing. And there is some lint to fix up: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/21854/violations/

**Comment by terminalmage** [comment]
D'oh, I did test, and thought I did on both Python 2 and 3, but I clearly did not on Python 3. This has been fixed in the most recent commit, and I've also fixed the lint issues and rebased.

**Review by cachedout — APPROVED** [review]

**Pull request merged**
