### PR TITLE
The traceback.*_exc() functions do not have an exc argument.

### LINKED ISSUE #60330: [BUG] salt-minion.service: main process exited, code=exited, status=1/FAILURE      TypeError: '>=' not supported between instances of 'OSError' and 'int'
**Description**
I can't use salt-call command in one of minion in my dev, checked its status,  got this error:
```
[root@olndsaltminion02 ~]# systemctl status salt-minion
● salt-minion.service - The Salt Minion
   Loaded: loaded (/usr/lib/systemd/system/salt-minion.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2021-06-08 14:52:20 EST; 6min ago
     Docs: man:salt-minion(1)
           file:///usr/share/doc/salt/html/contents.html
           https://docs.saltstack.com/en/latest/contents.html
  Process: 23397 ExecStart=/usr/bin/salt-minion (code=exited, status=1/FAILURE)
 Main PID: 23397 (code=exited, status=1/FAILURE)

Jun 08 14:52:20 olndsaltminion02 salt-minion[23397]: File "/usr/lib64/python3.6/traceback.py", line 121, in format_exception
Jun 08 14:52:20 olndsaltminion02 salt-minion[23397]: type(value), value, tb, limit=limit).format(chain=chain))
Jun 08 14:52:20 olndsaltminion02 salt-minion[23397]: File "/usr/lib64/python3.6/traceback.py", line 509, in __init__
Jun 08 14:52:20 olndsaltminion02 salt-minion[23397]: capture_locals=capture_locals)
Jun 08 14:52:20 olndsaltminion02 salt-minion[23397]: File "/usr/lib64/python3.6/traceback.py", line 338, in extract
Jun 08 14:52:20 olndsaltminion02 salt-minion[23397]: if limit >= 0:
Jun 08 14:52:20 olndsaltminion02 salt-minion[23397]: TypeError: '>=' not supported between instances of 'OSError' and 'int'
Jun 08 14:52:20 olndsaltminion02 systemd[1]: salt-minion.service: main process exited, code=exited, status=1/FAILURE
Jun 08 14:52:20 olndsaltminion02 systemd[1]: Unit salt-minion.service entered failed state.
Jun 08 14:52:20 olndsaltminion02 systemd[1]: salt-minion.service failed.
[root@olndsaltminion02 ~]# 
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
[root@olndsaltminion02 ~]# yum info salt-minion
Loaded plugins: ulninfo
Installed Packages
Name        : salt-minion
Arch        : noarch
Version     : 3003
Release     : 1.el7
Size        : 72 k
Repo        : installed
From repo   : saltstack-repo
Summary     : Client component for Salt, a parallel remote execution system
URL         : http://saltstack.org/
License     : ASL 2.0
Description : The Salt minion is the agent component of Salt. It listens for instructions
            : from the master, runs jobs, and returns results back to the master.
            : Supports Python 3.

You have mail in /var/spool/mail/root
[root@olndsaltminion02 ~]#

```
</details>

### PR DESCRIPTION
**Pull request by OrangeDog**
### What does this PR do?
Fixes some incorrect usage of `traceback` functions.

### What issues does this PR fix or reference?
Fixes:  #60330

### Previous Behavior
```
During handling of the above exception, another exception occurred:
TypeError: '>=' not supported between instances of 'OSError' and 'int'
```

### New Behavior
Correctly returns details of the first exception.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### CODE REVIEW

**Review by s0undt3ch — DISMISSED** [review]

**Review by Ch3LL — DISMISSED** [review]

**Comment by Ch3LL** [comment]
This failure looks like its related to the change: https://jenkins.saltproject.io/job/pr-debian-9-amd64-py3-pytest/job/PR-60342/1/

**Comment by OrangeDog** [comment]
@Ch3LL I didn't remove any docstrings, so I'm not sure how. Wouldn't it also fail on every platform rather than a single one?

**Comment by s0undt3ch** [comment]
That's test that is getting factored out into a pre-commit step on a separate PR, but we can't ignore it yet. Also, some tests only run on some platforms, not all, yes, even unit tests...
I've restarted the build.

**Comment by Ch3LL** [comment]
Can you elaborate @s0undt3ch ? Does that mean we need to fix the test in this PR before merging or you are stating we can ignore the failure? Looks like its still failing after you restarted it.

**Comment by s0undt3ch** [comment]
@Ch3LL so, we need to do something about this test, because it also failed on a full run.

What I might suggest is skip it on Debian.
Once https://github.com/saltstack/salt/pull/58539 is merged, that test will go away and we will be doing proper doc checks at the pre-commit level.

**Comment by s0undt3ch** [comment]
However, it's weird why this test is failing on this PR.

**Comment by Ch3LL** [comment]
K, yeah I think it would be worth it to atleast dive in a bit to see if anything is obvious. Ill see what I can find.

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
