### PR TITLE
Use os.getpid() to filter results in status.pid

### LINKED ISSUE #57634: [BUG] [RC1 Sodium] Wrong PIDs in service.status when using sysvinit
**Description**
When using service.status in a pure sysvinit environment, the PID of the python running the "service.status" always is in the results list. So, it always return at least one PID as result, even for non-existent services:

```
root@marvin:~# salt-call service.status service_that_dont_exists
local:
    8645
root@marvin:~# salt-call service.status service_that_dont_exists
local:
    8837
```

**Setup**
Nothing special, Salt 3001 (git202006091336) in two Slackware Linux machines.

**Steps to Reproduce the behavior**
Run "service.status" with a non-existent service, in a machine with pure sysvinit backend:

```
root@marvin:~# salt-call grains.get init
local:
    sysvinit
root@marvin:~# salt-call service.status another_service_that_dont_exists
local:
    9457
```

**Expected behavior**
It's expected to not have the python own PID in the output list.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: 1.1.3
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.8.3 (default, May 15 2020, 05:51:00)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.1.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: slackware 14.2 current
         locale: utf-8
        machine: i686
        release: 5.4.45
         system: Linux
        version: Slackware 14.2 current

```
</details>

### PR DESCRIPTION
**Pull request by piterpunk**
### What does this PR do?
In modules/status.py, status.pid used to use the string "status.pid" to filter out its own execution PID from results. This brokes linux_service.status, which uses status.pid to search for processes but have "service.status" as its execution string.

Changed the filter to use os.getpid to remove python own execution from the "ps" results.

### What issues does this PR fix or reference?
Fixes: #57634 

### Previous Behavior
The PID of python running "service.status" is shown in the output:
```
root@marvin:~# salt-call service.status dnsmasq
local:
    10686
    30556
root@marvin:~# salt-call service.status ntpd
local:
    10742
    1410
```

### New Behavior
No PID of python running "service.status" is shown in the output
```
root@marvin:~# salt-call service.status dnsmasq
local:
    30556
root@marvin:~# salt-call service.status ntpd
local:
    1410
```

### Merge requirements satisfied?
[salt-runtests-20200611024304.log](https://github.com/saltstack/salt/files/4762816/salt-runtests-20200611024304.log)

### Commits signed with GPG?
No

### CODE REVIEW

**Review by twangboy — DISMISSED** [review]

**Comment by twangboy** [comment]
Could you write a test for this please

**Comment by piterpunk** [comment]
> Could you write a test for this please

Just modified the actual test_status_pid integration test to compare the full PID list instead of only one random PID.

**Comment by piterpunk** [comment]
@twangboy I really don't know what to do here.

The only processes that I know for sure are running during the integration tests are the ones from the test process itself, but the working list is mutable while running, so, checking the whole list doesn't works.  To check only for #57634  a possible approach would be to get and search for the PID  of status.pid execution in its own results, but I don't know how to get the PID of a run_function call.

This PR code pass the actual test_status_pid, but the old code that return the wrong results pass the actual test_status_pid, too.

**Comment by piterpunk** [comment]
Added the unit tests for this PR
Nothing like a good sleep night.

**Review by dwoz — APPROVED** [review]

**Pull request merged**
