### PR TITLE
Pass cmd.run arguments to onlyif/unless cmd execution

### LINKED ISSUE #57760: [BUG] random "bad signature" error on minions after upgrade to 3001
**Description**
Yesterday we have upgraded our infrastructure to 3001-1 and discovered strange random failures.
Cronned salt-call for highstate hangs (until killed manually) and following error occurs:
```2020-06-23 12:07:51,175 [salt.crypt       :1041][ERROR   ][13523] There was an error while verifying the masters public-key signature
2020-06-23 12:07:51,176 [tornado.application:640 ][ERROR   ][13523] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fd3b1b73ea0>, <salt.ext.tornado.concurren
t.Future object at 0x7fd3b1b694a8>)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/crypt.py", line 1022, in verify_signing_master
    if self.verify_pubkey_sig(payload["pub_key"], payload["pub_sig"]):
  File "/usr/lib/python3.6/site-packages/salt/crypt.py", line 994, in verify_pubkey_sig
    res = verify_signature(path, message, binascii.a2b_base64(sig))
  File "/usr/lib/python3.6/site-packages/salt/crypt.py", line 265, in verify_signature
    return pubkey.verify(digest, signature)
  File "/usr/lib64/python3.6/site-packages/M2Crypto/RSA.py", line 284, in verify
    return m2.rsa_verify(self.rsa, data, signature, digest_type)
M2Crypto.RSA.RSAError: bad signature

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/ioloop.py", line 606, in _run_callback
    ret = callback()
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/stack_context.py", line 278, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/ioloop.py", line 628, in _discard_future_result
    future.result()
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.6/site-packages/salt/crypt.py", line 644, in _authenticate
    creds = yield self.sign_in(channel=channel)
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/gen.py", line 1070, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python3.6/site-packages/salt/crypt.py", line 805, in sign_in
    auth["aes"] = self.verify_master(payload, master_pub="token" in sign_in_payload)
  File "/usr/lib/python3.6/site-packages/salt/crypt.py", line 1141, in verify_master
    if self.verify_signing_master(payload):
  File "/usr/lib/python3.6/site-packages/salt/crypt.py", line 1043, in verify_signing_master
    raise Exception(sign_exc)
Exception: bad signature
```
Setting master_use_pubkey_signature to false helps, but it is very hard to cleanup, because cmd.run from master reports nodes as failed and I can't kill hanging python3 (salt-call) processess - have to do it one by one via ssh.

**Setup**
I guess it doesn't matter - any state/highstate fails.

**Steps to Reproduce the behavior**
Enabling master_use_pubkey_signature and running multiple salt-call will cause error.

**Expected behavior**
Smooth finish.

**Versions Report**
<details><summary>salt --versions-report</summary>
```
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: 1.12.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.3
        libgit2: 0.26.6
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.9.6
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 5.4.34-1-pve
         system: Linux
        version: CentOS Linux 7 Core
```
</details>

During upgrade salt removed old server keys and generated new one - I'm not sure why it happend. I remember, that about year ago we had similar behaviour (keys cleaning during saltstack upgrade), but I couldn't investigate the reasons.

### PR DESCRIPTION
**Pull request by mchugh19**
### What does this PR do?
Extends the global onlyif/unless cmd handling to accept arguments defined in the cmd.run state. 

### What issues does this PR fix or reference?
Fixes: #57760

### Previous Behavior
Previous to #55974, the cmd.run state handled its own unless and onlyif support. This included passing any of the cmd.run arguments for the state into the onlyif and unless cmd as well (https://github.com/saltstack/salt/pull/55974/files#diff-6617770c26f25c18a6adeeaf4ccdebd3L336)

When this behavior was removed in favor of using the global onlyif/unless requisites this behavior was not included, so arguments like `shell: /bin/bash` which were defined for cmd.run were not honored by the cmd.retcode execution used by onlyif/unless.

### New Behavior
Arguments accepted by cmd.run (which make sense) are now passed to cmd.retcode used by onlyif and unless.

- cwd
- root
- runas
- env
- prepend_path
- umask
- timeout
- success_retcodes

Other possible arguments such as `name`, `output_loglevel`, or `creates`, don't make sense for the unless/onlyif cmd.retcode use, while the arguments `bg` and `use_vt` would break functionality. 

Support of `shell` is a special case, and will be pulled first from the state arguments, then from the value of the shell grain if either exist.

**Risks:** it is possible that generic terms like `cwd`, `env`, or `root`, may exist in other states with different meanings than is intended for the cmd.retcode use in onlyif/unless. If desired, a gate could be added to optionally ignore inclusion of arguments to cmd.retcode, but has not yet been included as I don't know if the risk is worth the additional option complexity.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
No

### CODE REVIEW

**Review by cmcmarrow — DISMISSED** [review]

**Comment by jdelic** [comment]
From reading this patch it brings back `env` for `onlyif`. Removing the setting of environment variables for cmd.run requisites has broken my whole setup across multiple machines and required a lot of manual fixes. 

Can this land as a (in my case urgent) bugfix for 3001 in the short term?

**Review by garethgreenaway — DISMISSED** [review]

**Comment by krionbsd** [comment]
@mchugh19 LGTM, could you please run `pre-commit run` and re-submit the patch?

**Comment by Silvenga** [comment]
I would also agree with @jdelic - this breaks a lot for us. PowerShell is a lot different from cmd.

Can we get this backported to 3001?

**Comment by mchugh19** [comment]
@krionbsd @garethgreenaway since pre-commit ran the py2 cleanup process, and this touches state.py, it'd be nice to get lots of eyes on this.

**Review by dwoz — APPROVED** [review]

**Review by Ch3LL — APPROVED** [review]

**Review by dwoz — APPROVED** [review]

**Pull request merged**
