### PR TITLE
[2015.2] Add list targeting to salt-ssh flat roster

### LINKED ISSUE #22703: salt-ssh does not work with list matcher
Hi,

```
[root@saltmaster ~]# salt --versions
           Salt: 2015.2.0rc2-272-g34526d5
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.4
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.4
           Mako: Not Installed
```

I'm having trouble using the list matcher with salt-ssh. For example, my roster file (we're autogenerating these which is why the hostname is a UUID):

```
8feb256a-c4a4-4879-a814-eb50de700b2c:
  host: 172.16.32.59
  port: 22
  user: root
  passwd: password
  sudo: false
  tty: false
  timeout: 60
  thin_dir: /var/lib/acmecorp/salt/
f828da3e-9bf2-4564-8fa9-d931b2ac0554:
  host: 172.16.32.57
  port: 22
  user: root
  passwd: password
  sudo: false
  tty: false
  timeout: 60
  thin_dir: /var/lib/acmecorp/salt/
```

Then, when trying to perform a list match against them:

```
/usr/bin/salt-ssh --out yaml --no-color --roster-file roster.tmp -L 'f828da3e-9bf2-4564-8fa9-d931b2ac0554,8feb256a-c4a4-4879-a814-eb50de700b2c' state.sls basic_cluster.0_both pillar='{...}'
```

I'm getting this back:

```
No hosts found with target ['f828da3e-9bf2-4564-8fa9-d931b2ac0554', '8feb256a-c4a4-4879-a814-eb50de700b2c'] of type list
```

Changing the UUIDs to friendlier names also results in the same error. The main/normal 'salt' binary has no problem using the list matcher as far as I can tell.

### PR DESCRIPTION
**Pull request by basepi**
Fixes #22703

### CODE REVIEW

**Comment by msummers42** [comment]
Any interest in back-porting this for 2014.7.6 (assuming there will be such a release)? It's a documented feature for salt-ssh.

**Comment by basepi** [comment]
Documented where, out of curiosity?

**Comment by msummers42** [comment]
It's in the docs on the web and in the salt-ssh help under "Target Selection Options"

$ salt-ssh --versions-report
           Salt: 2014.7.5
         Python: 2.7.9 (default, Dec 30 2014, 09:52:01)
         Jinja2: 2.7.3
       M2Crypto: Not Installed
 msgpack-python: 0.4.6
   msgpack-pure: 0.1.3
       pycrypto: Not Installed
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: Not Installed
           RAET: Not Installed
            ZMQ: Not Installed
           Mako: Not Installed


$ salt-ssh --help
Usage: salt-ssh [options]

Options:
  --version             show program's version number and exit
  --versions-report     show program's dependencies version number and exit
  -h, --help            show this help message and exit
  --saltfile=SALTFILE   Specify the path to a Saltfile. If not passed, on will
                        be searched for in the current working directory
  -c CONFIG_DIR, --config-dir=CONFIG_DIR
                        Pass in an alternative configuration directory.
                        Default: /etc/salt
  --hard-crash          Raise any original exception rather than exiting
                        gracefully Default: False
  -r, --raw, --raw-shell
                        Don't execute a salt routine on the targets, execute a
                        raw shell command
  --roster=ROSTER       Define which roster system to use, this defines if a
                        database backend, scanner, or custom roster system is
                        used. Default is the flat file roster.
  --roster-file=ROSTER_FILE
                        define an alternative location for the default roster
                        file location. The default roster file is called
                        roster and is found in the same directory as the
                        master config file.
  --refresh, --refresh-cache
                        Force a refresh of the master side data cache of the
                        target's data. This is needed if a target's grains
                        have been changed and the auto refresh timeframe has
                        not been reached.
  --max-procs=SSH_MAX_PROCS
                        Set the number of concurrent minions to communicate
                        with. This value defines how many processes are opened
                        up at a time to manage connections, the more running
                        processes the faster communication should be, default
                        is 25
  --extra-filerefs=EXTRA_FILEREFS
                        Pass in extra files to include in the state tarball
  -v, --verbose         Turn on command verbosity, display jid
  -s, --static          Return the data from minions as a group after they all
                        return.
  -w, --wipe            Remove the deployment of the salt files when done
                        executing.
  -W, --rand-thin-dir   Select a random temp dir to deploy on the remote
                        system. The dir will be cleaned after the execution.

  Logging Options:
    Logging options which override any settings defined on the
    configuration files.

    -l LOG_LEVEL, --log-level=LOG_LEVEL
                        Console logging log level. One of 'all', 'garbage',
                        'trace', 'debug', 'info', 'warning', 'error',
                        'critical', 'quiet'. Default: 'warning'.
    --log-file=LOG_FILE
                        Log file path. Default: /var/log/salt/ssh.
    --log-file-level=LOG_LEVEL_LOGFILE
                        Logfile logging log level. One of 'all', 'garbage',
                        'trace', 'debug', 'info', 'warning', 'error',
                        'critical', 'quiet'. Default: 'warning'.

  Target Options:
    Target Selection Options

    -E, --pcre          Instead of using shell globs to evaluate the target
                        servers, use pcre regular expressions
    -L, --list          Instead of using shell globs to evaluate the target
                        servers, take a comma or space delimited list of
                        servers.
    -G, --grain         Instead of using shell globs to evaluate the target
                        use a grain value to identify targets, the syntax for
                        the target is the grain key followed by a
                        globexpression: "os:Arch*"
    --grain-pcre        Instead of using shell globs to evaluate the target
                        use a grain value to identify targets, the syntax for
                        the target is the grain key followed by a pcre regular
                        expression: "os:Arch.*"
    -N, --nodegroup     Instead of using shell globs to evaluate the target
                        use one of the predefined nodegroups to identify a
                        list of targets.
    -R, --range         Instead of using shell globs to evaluate the target
                        use a range expression to identify targets. Range
                        expressions look like %cluster

  Output Options:
    Configure your preferred output format

    --out=OUTPUT, --output=OUTPUT
                        Print the output from the 'salt-ssh' command using the
                        specified outputter. The builtins are 'compact',
                        'txt', 'grains', 'overstatestage', 'pprint', 'json',
                        'nested', 'raw', 'highstate', 'quiet', 'yaml', 'key',
                        'no_return', 'newline_values_only', 'virt_query'.
    --out-indent=OUTPUT_INDENT, --output-indent=OUTPUT_INDENT
                        Print the output indented by the provided value in
                        spaces. Negative values disables indentation. Only
                        applicable in outputters that support indentation.
    --out-file=OUTPUT_FILE, --output-file=OUTPUT_FILE
                        Write the output to the specified file
    --no-color, --no-colour
                        Disable all colored output
    --force-color, --force-colour
                        Force colored output
    --state-output=STATE_OUTPUT, --state_output=STATE_OUTPUT
                        Override the configured state_output value for minion
                        output. Default: full

  Authentication Options:
    Parameters affecting authentication

    --priv=SSH_PRIV     Ssh private key file
    -i, --ignore-host-keys
                        By default ssh host keys are honored and connections
                        will ask for approval
    --passwd=SSH_PASSWD
                        Set the default password to attempt to use when
                        authenticating
    --askpass           Interactively ask for the SSH password with no echo -
                        avoids password in process args and stored in history
    --key-deploy        Set this flag to attempt to deploy the authorized ssh
                        key with all minions. This combined with --passwd can
                        make initial deployment of keys very fast and easy

You can find additional help about salt-ssh issuing "man salt-ssh" or on
http://docs.saltstack.org

**Comment by basepi** [comment]
I knew it was in the help message, because we have the same command line parsers as salt uses. The problem is each roster has to support each match type independently. We may have to split out the parsers.

**Comment by msummers42** [comment]
I suppose it's the same sort of deal for the docs on the web. I understand that nodegroup targeting is a bigger monkey than list targeting. Either/both would be super awesome to have, but since list targeting is done that'll be awesome to have backported.

**Comment by basepi** [comment]
Yep, list is easy, and it looks like @rallytime backported it.

The others are harder. We don't have grains data without reaching out to the minion, and we don't have pillar data at the targeting step (at least not without some work).

**Pull request merged**
