### PR TITLE
Add Bower execution and state modules

### LINKED ISSUE #20587: Bower state module
Hello, SaltStack team!
Would it be possible to add a state module for Bower package manager support? I don't need all of commands, just `install` and `uninstall` commands (something like `salt.states.npm` - it has `bootstrap`, `installed` and `removed` commands).

**P.S.** I suppose I can work on this new state module. I have read the code for the `npm` state module and have found it pretty straightforward. I think it would not be too hard to implement the feature (just some time and proper testing, you know).

### PR DESCRIPTION
**Pull request by aspyatkin**
This pull request adds Bower execution and state module to SaltStack proposed by me. It was highly inspired by npm execution and state modules.

I managed to write a bunch of unit and integration tests. Documentation is also available. Resolves #20587.

### CODE REVIEW

**Comment by jfindlay** [comment]
@aspyatkin, looks awesome, thanks!

**Comment by rallytime** [comment]
Tests, too! Nice work!

**Comment by aspyatkin** [comment]
New integration tests (integration.states.bower) were skipped, as I had seen from Jenkins logs. I don't know, would it be better to add additional states to each of them (npm.installed bower)? Or you can install Bower on Jenkins machines?

**Comment by jfindlay** [comment]
@aspyatkin, I think the best thing to do here is add bower to the tests dependency states in saltstack/salt-testing.

**Comment by aspyatkin** [comment]
OK, I just have made a PR to https://github.com/saltstack/salt-jenkins/pull/69.

**Comment by thatch45** [comment]
@aspyatkin this looks great! We just need the test=True stuff in the states, here is an example:
https://github.com/saltstack/salt/blob/develop/salt/states/grains.py#L44

Let me know if you need any help here, I will be happy to get this code in for you if needs be :)

**Comment by aspyatkin** [comment]
I am afraid I made it wrong when merged changes from develop. Is it possible to rebase after pushing changes?

**Comment by jfindlay** [comment]
@aspyatkin, feel tree to do whatever you need, even if that means creating a new pull request.

**Comment by aspyatkin** [comment]
I think I will make a new one PR. Would be better.

**Pull request closed without merging**
