### PR TITLE
timezone module: handle timedatectl errors

### PR DESCRIPTION
**Pull request by anlutro**
See issue #26313

I think the tests will fail, as I didn't quite understand the way things were mocked.

### CODE REVIEW

**Comment by cachedout** [comment]
@anlutro Looks like a minor lint error.

@jfindlay Could you provide some guidance on the test failure?

**Comment by jfindlay** [comment]
@anlutro, see https://github.com/alprs/salt/pull/1 for the associated change to the unit tests.

**Comment by anlutro** [comment]
I pushed your commit, but there is a failing test, at least on my machine:

```
$ python -m unittest tests.unit.modules.timezone_test.TimezoneTestCase.test_get_zone
F
======================================================================
FAIL: test_get_zone (tests.unit.modules.timezone_test.TimezoneTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit/modules/timezone_test.py", line 71, in test_get_zone
    self.assertEqual(timezone.get_zone(), '')
AssertionError: '#\nA' != ''
```

**Comment by jfindlay** [comment]
@anlutro, that is interesting.  I cannot replicate that error.  I don't have time to look into right now, but I suspect there is something funny going on with the mocking.  What platform are you running the tests on?  Also, how are you running the tests?  When I try your command I get this:
```python-traceback
python2 -m unittest tests.unit.modules.timezone_test
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'timezone_test'
```
Normally I run unit tests like this, `python tests/runtests.py -v -n unit.modules.timezone_test.TimezoneTestCase`.

**Comment by anlutro** [comment]
I just create a py2 virtualenv with `pip install -r requirements/dev_python27`. I get the same error regardless of how I run the tests, on a Debian 8 installation.

**Comment by jfindlay** [comment]
That makes sense (I was running the tests on a system without the dev requirements installed).  I am now getting the error you are seeing,
```python-traceback
python2 -m unittest tests.unit.modules.timezone_test
..F....
======================================================================
FAIL: test_get_zone (tests.unit.modules.timezone_test.TimezoneTestCase)
[CPU:37.7%|MEM:23.0%|Z:0] 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit/modules/timezone_test.py", line 71, in test_get_zone
    self.assertEqual(timezone.get_zone(), '#\nA')
AssertionError: '' != '#\nA'

----------------------------------------------------------------------
Ran 7 tests in 0.018s

FAILED (failures=1)
```
salt-testing ships with a version of `mock_open` that ships with python 3 in order to support more sophisticated file reading mocking, and this is probably not getting used if the tests aren't run by `tests/runtest.py`.

**Comment by jfindlay** [comment]
It appears I am wrong, you can see I have updated the code, so it is not the same test.  Running your command on unmodified code I get:
```
python2 -m unittest tests.unit.modules.timezone_test
.......
----------------------------------------------------------------------
Ran 7 tests in 0.020s

OK
```

**Comment by anlutro** [comment]
I checked out the 2015.8 branch and the same test is failing there - it's not related to this PR, but might be my test environment...

I don't understand why the test expects the result to be an empty string. Doesn't the mock specify that the contents of /etc/timezone should be the same in both the debian and gentoo scenario?

**Comment by anlutro** [comment]
I re-created my virtualenv from scratch and removed all pycache files, so I doubt my environment is to blame - could python versions have something to say here, since the jenkins builds aren't failing? My python version is 2.7.9, as shipped with Debian 8/Jessie.

**Comment by jfindlay** [comment]
@anlutro, do you get the same problem running the test with `tests/runtests.py`?

**Comment by anlutro** [comment]
Yes, I get the same failure regardless of how I run it.

**Pull request merged**
