### PR TITLE
Fix multimaster failover on more than two masters and failback behaviour

### PR DESCRIPTION
**Pull request by hu-dabao**
### What does this PR do?

Fix the broken failover behavior when minion is configured to achieve multi-master setup, failover and failback. Actually, there is a bug in the code which cause this. See the following section for details. 

Some config piece:

```
master:
  - master1
  - master2
  - master3
master_type: failover
master_alive_interval: 30
master_failback: True
master_failback_interval: 30 
```
### What issues does this PR fix or reference?

Basically, this PR is trying to fix the broken behavior for multi-master failover. As designed in [multi-master doc](https://docs.saltstack.com/en/latest/topics/tutorials/multimaster_pki.html), salt-minion is supposed to failover to the masters in the list from the first master to the second one and then third, etc. <br>
Following sections have the details about what is the broken behavior right now. 
### Previous Behavior

masters:
`[master1, master2, master3]`
master1 is the master minion is currently connecting.
1. shutdown salt-master service on master1
2. minion connect to master2 based on order,  the local master list changes to <br>
   `[master2, master3, master1]`
3. shutdown salt-master service on master2, the local master list changes to  <br>
   `[master1, master3, master2]`
4. minion connect to master1 
   for step 4, minion is supposed to switch to connect to master3 by design. The reason is <br>

``` python
opts['master'] = [x for x in opts['master_list'] if opts['master'] != x]
```

makes local master list still shuffles in original master list rather than the updated one in step 2 and so forth.
5. minion fails to connect to master1 due to step 1 and it changes to connect to master2 again since it's local master list is wrongly changed to <br>
`[master2, master3, master1]` <br>
The code in step 4 I mentioned is the same cause. 
6. Later on, minion keeps on trying to connect to master1 and master2 in a dead loop behavior. 
### New Behavior
1. shutdown salt-master service on master1
2. minion connect to master2 based on order,  the local master list changes to <br>
   `[master2, master3, master1]`
3. shutdown salt-master service on master2, the local master list changes to <br>
   `[master3, master1, master2]`
4. minion connect to master3 
### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
@DmitryKuzmenko Could you please review these changes and make sure they are in line with what you have been working on in this area? Thanks.

**Comment by hu-dabao** [comment]
@DmitryKuzmenko please feel free to let me know if anything I can help with here as this bug is pretty straightforward and currently break multi-master failover functionalities in 2016.3.1. I'd like to help to fix it in a timely manner. 

@cachedout thanks for letting me know. BTW, I am new to the community :) , how should I follow up this issue?

Thanks.

**Comment by DmitryKuzmenko** [comment]
@cachedout this patch looks good for me!

@hu-dabao :+1: Thank you for good catch and patch!

**Comment by cachedout** [comment]
@hu-dabao I've merged this into Salt! Thanks for your help. We really appreciate it.

**Pull request merged**
