### PR TITLE
Move legacy docker state/exec module to salt-contrib, rename dockerng to docker

### PR DESCRIPTION
**Pull request by terminalmage**
Using the new ``__virtual_aliases__`` feature, the new ``docker.py`` will be
loaded both as ``docker`` and ``dockerng``. This fulfills the scheduled
deprecation and removal of the legacy docker state/execution module.

### CODE REVIEW

**Comment by cachedout** [comment]
Some lint violations to clean up: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/8699/violations/ and also some failing unit tests.

I'd also like to cc: @ticosax here just so everybody is on the same page. :]

**Comment by terminalmage** [comment]
Couple typos and forgot to change the naming in the tests. Fixed and rebased, tests _should_ pass now.

**Comment by terminalmage** [comment]
There are unit tests failing but they appear to have been broken in 17521fb23c92122c0ac045b092bb46e1ff958080.

**Comment by terminalmage** [comment]
Might actually have been broken earlier, not sure. I'll investigate more over the weekend.

**Comment by terminalmage** [comment]
Don't know why tests were failing here, but the mocking was not set up properly for certain functions that were part of ``salt.modules.docker`` (née ``salt.modules.dockerng``). The ``__salt__`` dunder was being mocked for functions like ``docker.run_alll`` and ``docker.copy_to``, when we should have been using ``patch.object`` to mock the function attributes themselves.

**Comment by terminalmage** [comment]
Tests appear to be green, the Ubuntu VM didn't complete the job for some reason but the results show that all tests passed:

```
%  links -dump https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/8683/consoleFull | grep -A2 'tests in'
 02:18:36 Ran 8 tests in 6.045s
 02:18:36
 02:18:36 OK
--
 02:18:48 Ran 8 tests in 12.807s
 02:18:48
 02:18:48 OK
--
 02:25:06 Ran 107 tests in 377.671s
 02:25:06
 02:25:06 OK (skipped=3)
--
 02:26:12 Ran 11 tests in 66.412s
 02:26:12
 02:26:12 OK
--
 02:26:15 Ran 21 tests in 2.065s
 02:26:15
 02:26:15 OK (skipped=3)
--
 02:26:36 Ran 46 tests in 21.053s
 02:26:36
 02:26:36 OK (skipped=5)
--
 02:26:37 Ran 4 tests in 1.089s
 02:26:37
 02:26:37 OK
--
 02:40:12 Ran 488 tests in 800.608s
 02:40:12
 02:40:12 OK (skipped=153)
--
 02:42:36 Ran 43 tests in 144.307s
 02:42:36
 02:42:36 OK (skipped=1)
--
 02:43:43 Ran 10 tests in 66.825s
 02:43:43
 02:43:43 OK
--
 02:57:05 Ran 204 tests in 801.080s
 02:57:05
 02:57:05 OK (skipped=30)
--
 02:57:42 Ran 20 tests in 36.912s
 02:57:42
 02:57:42 OK (skipped=3)
--
 02:58:54 Ran 20 tests in 71.374s
 02:58:54
 02:58:54 OK (skipped=1)
```

**Comment by ticosax** [comment]
@cachedout thx for the heads up.
it looks OK, I will run some internal testing with this version.

**Pull request merged**
