### PR TITLE
fix salt-api's default opts were covered by salt-master #35734

### PR DESCRIPTION
**Pull request by xiaoanyunfei**
### What does this PR do?

just refer to  [fix salt-api's default opts](https://github.com/saltstack/salt/pull/35734)
### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by whiteinge** [comment]
@xiaoanyunfei This change breaks the `-c` flag to salt-api. Do you know a quick fix?

```
/usr/bin/salt-api -c /path/to/etc/salt
Failed to create path "/var/log/salt/api" - [Errno 13] Permission denied: '/var/log/salt'
```

**Comment by xiaoanyunfei** [comment]
@whiteinge It's normal on my computer. Are you sure the directory '/var/log/salt' is owned by the user setted in /etc/salt/master? It seemed like a  problem of user rights
 for me 
  /etc/salt/master **user: sun**
$ll /var/log/
drwxr-x---  2 **sun               sun**       4096 8月  31 14:18 salt/

**Comment by whiteinge** [comment]
@xiaoanyunfei apologies for the terrible bug report. I'll clarify now:

* I tried with and without the commit in this PR and the problem is only present with this commit.
* I'm using a custom master config via the `-c` flag. In that config I'm using `root_dir` to specify a non-default location.
* I don't know if my custom config isn't getting read, or if it is getting read but is getting applied in the wrong order. But either way my custom config file is definitely not working after this commit.

**Comment by whiteinge** [comment]
(Filed the issue above to make sure this is fixed or temporarily reverted for the next 2016.3 point-release.)

**Pull request merged**
