### PR TITLE
Remove sshpass checks

### PR DESCRIPTION
**Pull request by rallytime**
ping @techhat and @s0undt3ch for review. I tested a couple of these, but a review would be helpful to make sure I did this correctly.

### CODE REVIEW

**Comment by rallytime** [comment]
Refs #19219

**Comment by s0undt3ch** [comment]
Need @techhat to review the deploy setting you're removing.

You also remove the key filename checks when used(along with ssh pass). You really want to remove all checks?

**Comment by rallytime** [comment]
@s0undt3ch Thanks! That what I was wondering about. When I've removed those deploy lines, it's because we're calling the deploy function later down. Those ones were only used for the sshpass checks. The key_filename checks were the ones I was concerned about. Before my last three commits, I had more/different checks in there, but in my testing, I couldn't get past them. I'll chat with @techhat to make sure I am on the right page today.

**Comment by techhat** [comment]
I'm going to agree with @rallytime here, the `deploy` setting should be getting checked further down. Unfortunately, I don't think it is. That needs to be investigated further. This, however, I'm fine with.

**Comment by rallytime** [comment]
@techhat Removed the last check, as we discussed. This should be good to go.

**Pull request merged**
