### PR TITLE
Add "osmajorrelease" grain

### PR DESCRIPTION
**Pull request by isbm**
### What does this PR do?

Adds `osmajorrelease` grain for every supported OS.
Bonus: refactors `osfinger`.
### Tests written?

Yes

### CODE REVIEW

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by isbm** [comment]
Mr.Jenkins is in the bad mood lately on everything. We need to feed him some cookies or so... :wink:

**Comment by cachedout** [comment]
@isbm This looks like it could be related. Could you please investigate? 

https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/3482/testReport/junit/integration.states.pkg/PkgTest/test_pkg_008_epoch_in_version/

**Comment by isbm** [comment]
@cachedout I went across everywhere and removed different assumptions how `osmajorrelease` should look like in favour of `int` type. Test was expecting an array, others prefer converting to a float then compare, elsewhere a string etc. All that fixed.

**Comment by cachedout** [comment]
@isbm Hmm. I wonder if this is going to affect people attempting to match this in templating language like Jinja...

**Comment by isbm** [comment]
Well, I think so. :wink: But my gut feeling is that they don't use it much and they can fix that on their own. Because I would call it a bug (or mess-production) than the same value comes in different types.

**Comment by isbm** [comment]
@cachedout As for "released version" we might still keep string though. But I would be cautious about that, since in my eyes it is actually a bug. Otherwise why on Earth an always number should come out as a string? That doesn't make sense to me. Especially that Salt is auto-converting such things into a numbers e.g. through CLI.

What you think?

**Comment by cachedout** [comment]
@isbm I am OK with this change going into develop but I am very hesitant to put that change into the 2016.3 branch. We try to make every effort to avoid changes in point releases which require that people update their states. An upgrade in a minor release should not require a user to modify any files, in my opinion.

**Comment by cachedout** [comment]
@isbm Still not quite there on some of the tests as well I'm afraid.

**Comment by isbm** [comment]
@cachedout Oops, forgot that SUSE test is no longer targeting by `os_release`. :wink: Fixed.

**Pull request merged**
