### PR TITLE
Remove m2crypto

### PR DESCRIPTION
**Pull request by msteed**
Remove M2Crypto as a dependency. Backward-compatible functionality is implemented using PyCrypto and calls into OpenSSL libcrypto.

### CODE REVIEW

**Comment by cachedout** [comment]
Awesome!

**Comment by rallytime** [comment]
Gah! I was going to apply the `Awesome` label, but @cachedout beat me to it.

AWESOME!

**Comment by msteed** [comment]
Failures are due to the PyCrypto RNG not being re-initialized after a fork(). Doing this is a one-liner but after looking at the stack traces I'm not sure where to put it. Maybe @cachedout or @thatch45 can help?

**Comment by techhat** [comment]
+1

**Comment by thatch45** [comment]
Yes, good call @msteed! PyCrypto needs the RNG to be massaged. Likely in the MWorker in master.py, maybe in the start method

**Pull request merged**
