### PR TITLE
[beacons.network_settings] adopt new pyroute2 API

### PR DESCRIPTION
**Pull request by svinota**
... and prepare for pyroute2.IPDB to be dropped.

This commit provides no logic change, only some compat code.

Reason: pyroute2.IPDB will be dropped in future releases, and
the successor module pyroute2.NDB does not provide a drop-in
replacement API.

Solution: use NDB if ipdb_interfaces_view() is available
(will be available @ pyroute2 >= 0.7.1), otherwise fall back
to IPDB (while it's provided).

Related: https://github.com/svinota/pyroute2/discussions/788

### CODE REVIEW

**Comment by svinota** [comment]
Not sure why `pr-centos-7-x86_64-py3-tcp-pytest` is failing.

**Comment by garethgreenaway** [comment]
@svinota Can you add a changelog for these changes?

**Comment by svinota** [comment]
@garethgreenaway sure thing, will be done tomorrow

**Comment by garethgreenaway** [comment]
@svinota Thanks!

**Comment by svinota** [comment]
@garethgreenaway done

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
