### PR TITLE
non-SSL access ability of netscaler module (#36452)

### PR DESCRIPTION
**Pull request by dreampuf**
To enable the non-ssl access of netscaler module.
https://github.com/saltstack/salt/issues/36452

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @dreampuf. Looks like the test suite had some issues with this. Would you mind please taking a look? Thanks very much.

**Comment by cachedout** [comment]
@dreampuf Did you see my comments above?

**Comment by dreampuf** [comment]
Hi @cachedout , I check out the branch from 'develop' branch. Is that the reason of testing failure?  
Only what I do is changing `modules/netscaler.py` one file.

**Comment by rallytime** [comment]
It appears that the tests that are failing were already present on the develop branch when you submitted this. Thanks for double checking.

**Pull request merged**
