### PR TITLE
Add firewall and SSH keys to Vultr

### PR DESCRIPTION
**Pull request by richardsimko**
### What does this PR do?
Improves the Vultr provider for Salt Cloud by adding options for `firewallgroupid` (#53677) and SSH keys.

### What issues does this PR fix or reference?
#53677

### Tests written?
No, there were no tests for these functions earlier. If there is a way to mock the integration towards Vultr I'm happy to write them.

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by dwoz** [comment]
@richardsimko Please re-open this PR against `master`, we are moving away from using the `develop` branch. See [SEP 14](https://github.com/saltstack/salt-enhancement-proposals/pull/20) for more details.

**Comment by richardsimko** [comment]
@dwoz Done!

**Comment by richardsimko** [comment]
@dwoz When can this be reviewed and merged? :)

**Comment by kkliebersbach** [comment]
Hey @twangboy or whoever needs to review, I am really hanging out for this feature! Would love to help if anything else needs to be done to get this in!

**Comment by richardsimko** [comment]
I'm going to close this PR and resubmit it in the hopes to get some attention. It's been here nearly a year now.

**Pull request closed without merging**
