### PR TITLE
Py3 master

### PR DESCRIPTION
**Pull request by thatch45**
### What does this PR do?

This gets the master to start in python 3 and almost gets the minion through the initial handshake, it should all work on python2 but I want to see what jenkins says
### What issues does this PR fix or reference?

Work towards py3 compat
### Previous Behavior

Master would crash immediately when starting in python3
### New Behavior

Master starts and gets much further but the minion still fails to hook in
### Tests written?
- [X] Yes - existing tests will check all of this code
- [ ] No

All of the issues here are bytestring related

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Test failures are unrelated.

**Comment by thatch45** [comment]
Wow! Really? That's awesome! I am on the right track :)

**Comment by rallytime** [comment]
I've got a really big merge-forward waiting to go into develop. Can we hold off on merging this in case it causes a refactor of that merge forward?

**Comment by thatch45** [comment]
Of course, no hurry here. I mostly wanted Jenkins to run to make sure I was doing the py3 stuff right :)

**Comment by rallytime** [comment]
Totally! :D

**Comment by s0undt3ch** [comment]
Py3 incoming!

**Comment by rallytime** [comment]
Ok, merge-forward is in! Looks like this one now needs a rebase though.

**Comment by thatch45** [comment]
Dang it! I messed it up, I don't have to do git magic enough anymore

**Comment by cachedout** [comment]
I'm not sure what happened to this rebase, but it sure went sideways. :]

I'm going to close this. (Sorry!) Could you just re-open another PR?

**Comment by thatch45** [comment]
Yes, I will submit a new one

**Comment by cachedout** [comment]
Thank you. :]

**Pull request closed without merging**
