### PR TITLE
Document pillar cache options

### LINKED ISSUE #32144: Pillar targeting starts to work only after calling `saltutil.refresh_pillar`
### Description of Issue/Question

Salt Master is unable to get a response from the Minion targeted using Pillar from a command line until I call `saltutil.refresh_pillar` function against that Minion (or `saltutil.sync_all` or `state.highstate`).
### Setup

I did a fresh setup of Master and Minion (named `test`) without any additional configuration (except of `pillar_roots` option).
My files:

``` yaml
# pillar/top.sls
base:
  'test':
    - test
```

``` yaml
# pillar/test.sls
test: 'string'
```
### Steps to Reproduce Issue

Pillar is visible on Minion `test`:

``` console
# salt test pillar.items
test:
    ----------
    test:
        string
```

[Pillar targeting](https://docs.saltstack.com/en/latest/topics/targeting/pillar.html) seems to work, but there is no return from the Minion:

``` console
# salt -l debug -I 'test:string' pillar.items
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/b3/a65df54bfaed4f07b17f4da7e2d205/.minions.p
[DEBUG   ] get_iter_returns for jid 20160325130624345444 sent to set(['test']) will timeout at 13:06:29.350370
[DEBUG   ] Checking whether jid 20160325130624345444 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] LazyLoaded no_return.output
test:
    Minion did not return. [No response]

```

If there are no Minions to match the target, Salt behaves as expected:

``` console
# salt -l debug -I 'test:other_string' pillar.items
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: ipc:///var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt_master', 'tcp://127.0.0.1:4506', 'clear')
No minions matched the target. No command was sent, no jid was assigned.
[DEBUG   ] LazyLoaded nested.output
ERROR: No return received
```

And after I ran `salt '*' saltutil.refresh_pillar` Pillar targeting started to behave correctly.
### Concerns
1. It's hard to figure out that manual Pillar refreshing is a requirement for this targeting method.
   Such thing should be reflected in the documentation.
2. Also it's easy to forget to do refresh all the time after Pillar data was changed.
   I think we need to ship a scheduled job configuration with the minion like it's already done for `mine.update`.
   For example:
   
   ``` yaml
   # /etc/salt/minion.d/_schedule.conf 
   schedule:
     __mine_interval: {function: mine.update, jid_include: true, maxrunning: 2, minutes: 60}
     __pillar_interval: {function: saltutil.refresh_pillar, jid_include: true, maxrunning: 2, minutes: 60}
   ```
   
   By the way, `mine.get` with [compound matches](https://docs.saltstack.com/en/latest/topics/targeting/compound.html) using Pillar would definitely need this.
3. Looks strange that Salt actually performs Minion lookup by Pillar data correctly.
   **It just unable to provide return from requested function** (`test.ping` gives the same result).
   Does Salt really needs the Pillar data cache for targeting and providing return if it already does a half of the job without any cache?
### Versions Report

```
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: 0.21.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.21.4
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.10.1.el7.x86_64
         system: CentOS Linux 7.2.1511 Core
```

### PR DESCRIPTION
**Pull request by vutny**
### What does this PR do?

Documents pillar cache options for Salt Master and pillar targeting requirements for CLI and Salt Mine.
### What issues does this PR fix or reference?

It should partially resolve #32144.

### CODE REVIEW

**Comment by cachedout** [comment]
I do not like adding this schedule by default. I'm fine with documenting that it may need to be added, but this has the potential to really cause a lot of havoc for installations running with large numbers of minions. Thoughts?

**Comment by vutny** [comment]
@cachedout I've run this on few hundreds of Minions without any issues. However, not sure about how it will go on thousands or more...

I can remove or comment the persistent scheduled job configuration in favor of the documentation updates to be merged now, and we could continue the discussion in #32144.
Is it OK?

**Comment by cachedout** [comment]
That's fine.I don't think we're willing to merge the schedule update right now but if it's removed the rest looks fine. I propose that we go just with the documentation updates instead. Thanks!

**Comment by vutny** [comment]
@cachedout I've removed the code which schedules pillar refreshing job. Thank you.

**Comment by cachedout** [comment]
Thanks, @vutny

**Pull request merged**
