### PR TITLE
Add ifelse function as found in CFEngine

### LINKED ISSUE #62508: [FEATURE REQUEST] add "ifelse" Jinja function as found in CFEngine
**Describe the solution you'd like**
Some users transitioning over from CFEngine have expressed a desire to have functionality similar to [the ifelse function found in CFEngine](https://docs.cfengine.com/docs/3.18/reference-functions-ifelse.html).

**Describe alternatives you've considered**
The concept is very similar to `match.filter_by`, but necessitates adding all items into a dictionary in order to perform the evaluation.

**Additional context**
Providing this functionality should be pretty low effort considering it could be a wrapper that passes to `match.filter_by`.

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

### PR DESCRIPTION
**Pull request by nicholasmhughes**
### What does this PR do?
See issue for details.

### What issues does this PR fix or reference?
Fixes: #62508 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by nicholasmhughes** [comment]
re-run pr-ubuntu-2004-amd64-py3-m2crypto-pytest

**Comment by whytewolf** [comment]
I'm confused. is this only meant to be a Jinja function? if so it doesn't belong in modules.match. but if it is meant to be more than just a jinja function the wording on the docstring needs to be updated to show how it can be useful outside ofjinja as well.

**Comment by nicholasmhughes** [comment]
I'm not sure what needs to be updated in the docstring... It has a command line example. Can you provide some direction on what you think should be updated?

**Comment by whytewolf** [comment]
You are correct, not sure what i was thinking about. Yes you are correct the module does have an example for inline use.

**Review by whytewolf — APPROVED** [review]

**Pull request merged**
