### PR TITLE
Update archive.py to use python_shell=False (2014.1 branch)

### PR DESCRIPTION
**Pull request by terminalmage**
Also improve the docstrings

### CODE REVIEW

**Comment by terminalmage** [comment]
I jumped the gun and submitted this before testing locally. Hold off on merging until I have tested.

**Comment by terminalmage** [comment]
OK, tested, looks good.

**Comment by thatch45** [comment]
Looks like the tests are failing....

**Comment by terminalmage** [comment]
Tests have been updated, backported from fixes in #19539 and modified to remove arguments not present in the 2014.1 branch.

**Comment by terminalmage** [comment]
Should be good to merge this, pending the archive tests passing.

**Pull request merged**
