### PR TITLE
Boto secgroup tags

### LINKED ISSUE #27622: Add tags support in boto_secgroup
Add ability to set/delete tags from EC2 security groups via boto_secgroup state/module

### PR DESCRIPTION
**Pull request by lomeroe**
Adds ability to set/delete EC2 security groups

Fixes #27622

### CODE REVIEW

**Comment by lomeroe** [comment]
attempted to update the test module that was causing the failure...

**Comment by rallytime** [comment]
Thanks @lomeroe! Looks good.

@ryan-lane Anything to add here?

**Comment by rallytime** [comment]
@lomeroe I did notice that the code-blocks are missing from the CLI examples, so I made a quick PR against your branch here https://github.com/lomeroe/salt/pull/1

**Comment by ryan-lane** [comment]
Nice change. This looks good to me!

**Comment by basepi** [comment]
Crap. I missed the fact there was an open pull request. @rallytime mind resubmitting against develop? /me hangs head in shame

**Comment by rallytime** [comment]
No problem. I did that a little weird probably. Done! https://github.com/saltstack/salt/pull/27700

**Comment by lomeroe** [comment]
Thanks everyone...

**Pull request merged**
