### PR TITLE
Fix useradd hard-coded relative command names

### LINKED ISSUE #62087: [BUG] useradd.* functions hard code relative command name
**Description**
Functions in the `useradd` execution module have hard-coded command names for `useradd`, `usermod`, and `userdel` which rely on the `PATH` environment variable to be properly set in order to run correctly.

**Steps to Reproduce the behavior**
On a Debian 10 system, the `PATH` variable was modified to remove "sbin" locations where the `usermod` command would be found:

```bash
# /root/.bashrc
export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/bin"
```

Then, any calls to `usermod` (or `useradd` and `userdel`) will fail with the following error:

```
# salt-call user.chshell susan /bin/sh

Error running 'user.chshell': Unable to run command '['usermod', '-s', '/bin/sh', 'susan']' with the context ...
No such file or directory: 'usermod': 'usermod'
```

**Expected behavior**
It would be nice if the functions made an effort to locate the full path to the binaries.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3004.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: 2.1.11
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-20-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```
</details>

### PR DESCRIPTION
**Pull request by nicholasmhughes**
### What does this PR do?
This PR adds support for searching for `useradd`, `usermod`, and `userdel` binaries using the `salt.utils.path.which` function instead of solely relying on the `PATH` environment variable to find them.

### What issues does this PR fix or reference?
Fixes: #62087 

### Previous Behavior
Binaries would not be found if some "sbin" locations were not in the `PATH`, despite being installed.

### New Behavior
The `salt.utils.path.which` function adds some standard paths into the search locations, so the binaries will still be found if in a "standard" location like `/sbin/` even if that directory isn't in the `PATH`.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by whytewolf** [comment]
Hey Nick,

Nice pr, looks like the tests will need to be skipped on a couple of operating systems.

**Comment by nicholasmhughes** [comment]
hmmm... looks like it's failing the old style tests because the `which` return isn't mocked. I guess I should probably ensure full pytest coverage and just remove the old unit tests.

**Comment by whytewolf** [comment]
Hey @nicholasmhughes so, my two cents on the mocking of which. I would rather know these fail on some operating systems that don't have useradd and the like. and have the tests account for that change. then to mock which and have it "work" when the module wouldn't actually work on an operating system. 

but that is just my two cents. @waynew what do you think?

**Comment by nicholasmhughes** [comment]
re-run pr-opensuse-15-x86_64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-fedora-34-x86_64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-centos-7-x86_64-py3-tcp-pytest

**Comment by waynew** [comment]
@whytewolf when it comes to a unit test, mocking is preferable, but it wouldn't hurt at all to have a functional test that fails on Windows or other systems without useradd. Could do something like:

```
@pytest.mark.skipIf(..., "Should only fail on Windows/Mac")  # or whatever
def test_errors_out_when_no_useradd_exists():
    with pytest.raises(CommandExecutionError):
        ...
```

It might be worthwhile adding another test for successful platforms, but I think we actually do have some of those already? :thinking:

**Review by whytewolf — APPROVED** [review]

**Comment by whytewolf** [comment]
> @whytewolf when it comes to a unit test, mocking is preferable, but it wouldn't hurt at all to have a functional test that fails on Windows or other systems without useradd. Could do something like:
> 
> ```
> @pytest.mark.skipIf(..., "Should only fail on Windows/Mac")  # or whatever
> def test_errors_out_when_no_useradd_exists():
>     with pytest.raises(CommandExecutionError):
>         ...
> ```
> 
> It might be worthwhile adding another test for successful platforms, but I think we actually do have some of those already? 🤔

Woops totally didn't notice they were unit thought they were functional for some reason. You're right. unit should be mocked. the new test looks to cover my concern so approving.

**Review by waynew — APPROVED** [review]
:rocket: You rock!

**Comment by nicholasmhughes** [comment]
re-run pr-arch-lts-x86_64-py3-pytest

**Pull request merged**
