### PR TITLE
Winrepo sls files now run through the templating system

### PR DESCRIPTION
**Pull request by twangboy**

### CODE REVIEW

**Comment by thatch45** [comment]
Looks good @twangboy ! Since these two files have copied code we should look into moving the code to a location in utils and just calling it from the runner and module in the future

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
@twangboy please clean up that lint issue:
https://jenkins.saltstack.com/job/salt-pr-lint-n/4295/violations/

**Comment by lorengordon** [comment]
There are issues this fixes. Can we tag them in the commit message?

**Comment by rallytime** [comment]
@lorengordon It's probably too late to tag them in the commit messages, but tag them here so they'll show up and we'll remember what's all connected to this fix. (I don't know which ones they are myself, but anything you can link up would be much appreciated!)

**Comment by lorengordon** [comment]
I think the oldest one is issue #6859. Lots of other issues link to that as a reference.

**Comment by twangboy** [comment]
That's not code I changed and I don't see what's wrong with it.

**Comment by rallytime** [comment]
@twangboy The pylint failures are happening here because you deleted the code that was calling the yaml import. So now that import isn't needed anymore. :)

**Comment by twangboy** [comment]
Thank you, I will fix that in the morning. Man pylint is smart.

On Wed, Apr 15, 2015 at 8:22 PM, Nicole Thomas <notifications@github.com>
wrote:

> @twangboy <https://github.com/twangboy> The pylint failures are happening
> here because you deleted the code that was calling the yaml import. So now
> that import isn't needed anymore. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saltstack/salt/pull/22675#issuecomment-93619772>.
>



-- 
*Shane Lee*
*Windows Platform Engineer*
Salt Stack, Inc.

Join us at SaltConf15 <http://www.saltconf.com/> - March 3-5, 2015 - Salt
Lake City

**Pull request merged**
