### PR TITLE
Mac utils tests

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?

Adds unit tests for the mac_utils salt utility
https://github.com/saltstack/zh/issues/546
### Tests written?
- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by cachedout** [comment]
Very good. These are nice.

**Comment by cachedout** [comment]
Please fix the lint errors.

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
This still has lint errors. Could you please take another look?

**Comment by rallytime** [comment]
Go Go Jenkins!

**Pull request merged**
