### PR TITLE
verify template_name exists before attempting to render prefixes

### PR DESCRIPTION
**Pull request by wasabi222**
This fixes a bug in the napalm_network module that prevents users from only specifying an inline template with the template_source kwarg.

The template_name variable defaults to None in this function, so when a user calls net.load_template without the template_name var defined (for example, if they want to specify an inline template with the template_source kwarg), this errors out due to the following:

if not isinstance(template_name, (tuple, list)): # this will run since template_name is a NoneType
        for salt_render_prefix in salt_render_prefixes:
            if not salt_render:
                salt_render = salt_render or template_name.startswith(salt_render_prefix) # <-- the bug is here - NoneType has no attribute 'startswith'

this replaces https://github.com/saltstack/salt/pull/52328 which I'll now close

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
This currently produces the following traceback:

   The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1607, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/utils/napalm.py", line 430, in func_wrapper
        return func(*args, **kwargs)
      File "/var/cache/salt/proxy/extmods/junos/modules/napalm_network.py", line 1920, in load_template
        salt_render = salt_render or template_name.startswith(salt_render_prefix)
    AttributeError: 'NoneType' object has no attribute 'startswith'

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ X] Docs
- [X ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [X ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by krionbsd** [comment]
@wasabi222 could you please run `pre-commit`? Something like `python3 -m pip install --user pre-commit` `pre-commit install --install-hooks` and commit new version

**Comment by wasabi222** [comment]
I did this but don't see anything neew to commit:

```
salt git:(master) pre-commit
Linux Py3.5 ZeroMQ Requirements......................(no files to check)Skipped
Linux Py3.6 ZeroMQ Requirements......................(no files to check)Skipped
Linux Py3.7 ZeroMQ Requirements......................(no files to check)Skipped
Linux Py3.8 ZeroMQ Requirements......................(no files to check)Skipped
Linux Py3.9 ZeroMQ Requirements......................(no files to check)Skipped
Linux Py3.5 Crypto Requirements......................(no files to check)Skipped
Linux Py3.6 Crypto Requirements......................(no files to check)Skipped
Linux Py3.7 Crypto Requirements......................(no files to check)Skipped
Linux Py3.8 Crypto Requirements......................(no files to check)Skipped
Linux Py3.9 Crypto Requirements......................(no files to check)Skipped
FreeBSD Py3.5 ZeroMQ Requirements....................(no files to check)Skipped
FreeBSD Py3.6 ZeroMQ Requirements....................(no files to check)Skipped
FreeBSD Py3.7 ZeroMQ Requirements....................(no files to check)Skipped
FreeBSD Py3.8 ZeroMQ Requirements....................(no files to check)Skipped
FreeBSD Py3.9 ZeroMQ Requirements....................(no files to check)Skipped
FreeBSD Py3.5 Crypto Requirements....................(no files to check)Skipped
FreeBSD Py3.6 Crypto Requirements....................(no files to check)Skipped
FreeBSD Py3.7 Crypto Requirements....................(no files to check)Skipped
FreeBSD Py3.8 Crypto Requirements....................(no files to check)Skipped
FreeBSD Py3.9 Crypto Requirements....................(no files to check)Skipped
Darwin Py3.5 ZeroMQ Requirements.....................(no files to check)Skipped
Darwin Py3.6 ZeroMQ Requirements.....................(no files to check)Skipped
Darwin Py3.7 ZeroMQ Requirements.....................(no files to check)Skipped
Darwin Py3.8 ZeroMQ Requirements.....................(no files to check)Skipped
Darwin Py3.9 ZeroMQ Requirements.....................(no files to check)Skipped
Darwin Py3.5 Crypto Requirements.....................(no files to check)Skipped
Darwin Py3.6 Crypto Requirements.....................(no files to check)Skipped
Darwin Py3.7 Crypto Requirements.....................(no files to check)Skipped
Darwin Py3.8 Crypto Requirements.....................(no files to check)Skipped
Darwin Py3.9 Crypto Requirements.....................(no files to check)Skipped
Windows Py3.5 ZeroMQ Requirements....................(no files to check)Skipped
Windows Py3.6 ZeroMQ Requirements....................(no files to check)Skipped
Windows Py3.7 ZeroMQ Requirements....................(no files to check)Skipped
Windows Py3.5 Crypto Requirements....................(no files to check)Skipped
Windows Py3.6 Crypto Requirements....................(no files to check)Skipped
Windows Py3.7 Crypto Requirements....................(no files to check)Skipped
Docs Py3.5 Requirements..............................(no files to check)Skipped
Docs Py3.6 Requirements..............................(no files to check)Skipped
Docs Py3.7 Requirements..............................(no files to check)Skipped
Docs Py3.8 Requirements..............................(no files to check)Skipped
Docs Py3.9 Requirements..............................(no files to check)Skipped
Lint Py3.5 Requirements..............................(no files to check)Skipped
Lint Py3.6 Requirements..............................(no files to check)Skipped
Lint Py3.7 Requirements..............................(no files to check)Skipped
Lint Py3.8 Requirements..............................(no files to check)Skipped
Lint Py3.9 Requirements..............................(no files to check)Skipped
Cloud Py3.5 Requirements.............................(no files to check)Skipped
Cloud Py3.6 Requirements.............................(no files to check)Skipped
Cloud Py3.7 Requirements.............................(no files to check)Skipped
Cloud Py3.8 Requirements.............................(no files to check)Skipped
Cloud Py3.9 Requirements.............................(no files to check)Skipped
Changelog Py3.5 Requirements.........................(no files to check)Skipped
Changelog Py3.6 Requirements.........................(no files to check)Skipped
Changelog Py3.7 Requirements.........................(no files to check)Skipped
Linux Py3.5 Invoke Requirements......................(no files to check)Skipped
Linux Py3.6 Invoke Requirements......................(no files to check)Skipped
Linux Py3.7 Invoke Requirements......................(no files to check)Skipped
Linux Py3.8 Invoke Requirements......................(no files to check)Skipped
Linux Py3.9 Invoke Requirements......................(no files to check)Skipped
Drop six usage and Py2 support.......................(no files to check)Skipped
isort................................................(no files to check)Skipped
black................................................(no files to check)Skipped
blacken-docs.........................................(no files to check)Skipped
Lint Salt............................................(no files to check)Skipped
Lint Tests...........................................(no files to check)Skipped
Check Docs...........................................(no files to check)Skipped
Check Filename Map Change Matching...................(no files to check)Skipped
➜  salt git:(master) git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by krionbsd** [comment]
@wasabi222 please run `git commit --amend && git push -f origin $branch`

**Review by Ch3LL — CHANGES_REQUESTED** [review]
can we get a test case added here and a changelog entry

**Comment by wasabi222** [comment]
This is a bugfix so a test case should already exist. Where do I put the changelog entry? (new contributor here)

**Comment by Ch3LL** [comment]
we still need a testcase even if its a bug fix. There is not test coverage for this bug or else we would have previously caught this issue.  

Also heres the documentation for changelog: https://docs.saltstack.com/en/master/topics/development/changelog.html

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
