### PR TITLE
dont allow using no_use_wheel for pip 10.0.0 or newer

### PR DESCRIPTION
**Pull request by gtmanfred**
### What does this PR do?
The --no-use-wheel flag has been deprecated in pip 10.0.0

### Tests written?

Yes, there is a test that uses this right now, which is failing, and will stop failing once this has been merged.

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by gtmanfred** [comment]
integration.states.test_virtualenv.VirtualenvTest.test_issue_1959_virtualenv_runas 

Fixes this test.

**Comment by gtmanfred** [comment]
re-run py

**Comment by gtmanfred** [comment]
re-run py

**Review by rallytime — APPROVED** [review]

**Comment by gtmanfred** [comment]
🎉

**Comment by piersf** [comment]
Hi,

Is this fix included in 2017.7.5 (Nitrogen)? I just upgraded both master and minion to 2017.7.5 from 2017.7.3 and the error described above still occurs.

Thanks,

**Comment by gtmanfred** [comment]
no, 2017.7.5 was released before pip 10.0.0 was, this will be in the next release.

**Pull request merged**
