### PR TITLE
Remove usually-wrong advice to raise worker threads

### PR DESCRIPTION
**Pull request by basepi**
This removes the suggestion to increase `worker_threads` when you get the "master not responding" error.

The problem is that that suggestion is usually wrong. At large scale, salt will usually fail to respond to '*'-targeted jobs on the command line as the event bus gets overloaded. Most large scale deployments standardize on using `--async` to avoid these issues, and then look at the job cache afterwards.

But for people new to salt or who don't understand what's happening, this error often misdiagnoses the issue. I've seen multiple instances where admins have increased that setting way above reasonable limits (i.e. `worker_threads: 50` on a 4 or 8 core machine).

We could also add more potential solutions to this error. Recommendations to increase the resources on your master (cores/ram) or maybe a more qualified suggestion about worker_threads (making it clear that you should never set it to more than 2x the number of cores on your master).

Thoughts?

### CODE REVIEW

**Comment by cachedout** [comment]
I am in favor or re-wording this. If `--async` is going to be the recommendation though, I think we should be clear about what that means for a new CLI user who might not realize how behavior will change.

**Comment by basepi** [comment]
Valid. Let me toy with the wording a little bit.

**Review by cachedout — APPROVED** [review]

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Pull request merged**
