### PR TITLE
Fix tls cert unknown extensions

### PR DESCRIPTION
**Pull request by jleproust**
When analyzing a TLS certificate with unknown extensions, for example from
https://datanova.laposte.fr/, OpenSSL raises an OpenSSL.crypto.Error on
str(cert.get_extension()). The only useful thing to do with the
extension is then to print the content as a string.

### What issues does this PR fix or reference?
No issue created yet. #24338 may be relevant but I'm not sure, it seems already fixed.

### Previous Behavior
Throws an uncaught OpenSSL.crypto.Error and fails

### New Behavior
Return relevant information about the certificate, with strings for unknown extensions, and no uncaught exception

### Tests written?
Yes

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by jleproust** [comment]
Hello, can we have an idea of the timeline for merging this? Thanks in advance.

**Comment by jleproust** [comment]
Any news on this please? The fix is trivial, I added a unit test, and it's blocking for us. I'd really like to stop patching salt code in production. Forking and re-packaging shouldn't be necessary for this...

**Comment by jleproust** [comment]
Ping?

**Comment by dwoz** [comment]
Closing this due to inactivity.  Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
