### PR TITLE
update salt.utils.stringutils.human_to_bytes for broader use

### LINKED ISSUE #61831: [FEATURE REQUEST] update salt.utils.stringutils.human_to_bytes for broader use
**Is your feature request related to a problem? Please describe.**
The `stringutils.human_to_bytes` utility is pretty narrow in its implementation. It doesn't handle sizes above a petabyte, and also doesn't handle units specified in more than a character (KB or KiB vs K).

**Describe the solution you'd like**
The `virt` module has a `_handle_unit` function that handles this functionality pretty well. This function could be moved over to replace `human_to_bytes`, centralizing and improving the logic. It'd also be great to have this as a Jinja filter.

**Describe alternatives you've considered**
Just deal with it?  :wink:   It works as-is... it's just picky about input.

**Additional context**
Stumbled upon this while looking at `file.tidied`, which only accepts sizes in bytes.

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

### PR DESCRIPTION
**Pull request by nicholasmhughes**
### What does this PR do?
This PR moves the `_handle_unit` function from the `virt` module to the `stringutils.human_to_bytes` utility in order to replace the narrow functionality there. It also tags the function as a Jinja filter.

### What issues does this PR fix or reference?
Fixes: #61831

### Previous Behavior
`human_to_bytes` didn't handle sizes above a petabyte, and also didn't handle units specified in more than a character (KB or KiB vs K).

### New Behavior
The function is now much more flexible and is exposed as a Jinja filter.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by nicholasmhughes** [comment]
re-run pr-ubuntu-2004-amd64-py3-tcp-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-arch-lts-x86_64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-arch-lts-x86_64-py3-pytest

**Review by Ch3LL — APPROVED** [review]

**Review by waynew — APPROVED** [review]
I suppose Yottabytes is probably a reasonable place to stop for now :trollface:

**Review by twangboy — APPROVED** [review]

**Pull request merged**
