### PR TITLE
[PyTest #34] Switch to plain asserts

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title

### CODE REVIEW

**Comment by mchugh19** [comment]
I had actually just written some new tests and adjusted the old ones to be in the self.assert<whatever> model. What's the reason for the conversation to plain asserts? When looking at test output, I do find the diff model rather helpful.

**Comment by s0undt3ch** [comment]
The PR is to be merged after we switch to PyTest.

PyTest is smart enough to show us proper diff's, at least for built-in types.

Asserting dictionary equality in pytest is as simple as:
```python
assert {1: 1} == {2: 2}
```
Which would fail and we'd get a nice diff printed.

**Comment by s0undt3ch** [comment]
https://docs.pytest.org/en/latest/assert.html

**Comment by s0undt3ch** [comment]
So, in conclusion, we write more readable code without loosing the diff

**Comment by s0undt3ch** [comment]
Removed from Aluminum and actually closing. We now have salt-rewrite in place and once we're ready, it will rewrite the whole test suite. Right now, it's only sensible to `tests/pytests`

**Pull request closed without merging**
