### PR TITLE
backport nacl - 2015.2

### PR DESCRIPTION
**Pull request by steverweber**
I would like to see this in the release because our organization will use it heavily in pillars. 
If it's too late for the release that's fine.

thanks.

### CODE REVIEW

**Comment by steverweber** [comment]
depends on
https://github.com/saltstack/salt/pull/21266

**Comment by thatch45** [comment]
I will accept this for a backport based purely on the awesomeness of the module

**Comment by jacksontj** [comment]
@thatch45 the nacl module's example:

```
 salt-call nacl.enc mypass keyfile=/root/.nacl
```

*will* end up (by default at least) sending the password and keyfile (the low object) into the master's job cache and the master's event bus. I don' t know if we have an API to allow modules to return "nocache" or "noreturn", but this would be an excellent use case ;)

**Comment by steverweber** [comment]
umm i thought that salt-call  would run on the local minion... the key file should be local to the minion... if you want to use the key relative to the master use. salt-run nacl.

is there any good docs on the details of the low object... I wish to learn more of the salt inner workings so i dont program stuff wrong :)

**Comment by jacksontj** [comment]
It will run on the minion, but minions return to the master.. Now it may
just return the encrypted string (just the ret not the low).

The low object in this context is the job publish which would include
everything in the cli

**Comment by steverweber** [comment]
so if i use salt-call on a minion that call (low) and result (ret) might both be sent to a master?
interesting... honestly I dont see why the master should be notified at all.

**Comment by steverweber** [comment]
Personally i think it would be best if I could install a standalone minion and be able to pass it some sls files to set a highstate.  This would be a good gateway for new users to start using Salt.

**Comment by steverweber** [comment]
opps disregard :)
```
s8weber@mbp:~$ sudo salt-call --local test.ping
local:
    True
```

**Comment by jacksontj** [comment]
Yea, it definietly sends it back to the master:

```
(salt)[root@Thomas-PC salt]# salt-call test.arg a b c
local:
    ----------
    args:
        - a
        - b
        - c
    kwargs:
        ----------
        __pub_fun:
            test.arg
        __pub_jid:
            20150306102422716577
        __pub_pid:
            27669
        __pub_tgt:
            salt-call
```

```
(salt)[root@Thomas-PC salt]# salt-run jobs.list_job 20150306102422757814
Arguments:
    - a
    - b
    - c
Function:
    test.arg
Minions:
    - Thomas-PC.jacksontj.dyndns.org
Result:
    ----------
    Thomas-PC.jacksontj.dyndns.org:
        ----------
        return:
            ----------
            args:
                - a
                - b
                - c
            kwargs:
                ----------
                __pub_fun:
                    test.arg
                __pub_jid:
                    20150306102422716577
                __pub_pid:
                    27669
                __pub_tgt:
                    salt-call
StartTime:
    2015, Mar 06 10:24:22.757814
Target:
    Thomas-PC.jacksontj.dyndns.org
Target-type:
    glob
User:
    root
jid:
    20150306102422757814
```

If you run master-less or add --local to the command it won't do any of that.

**Comment by steverweber** [comment]
yap. thanks!
ill update docs to use --local

**Comment by steverweber** [comment]
whats run masterless?

**Comment by thatch45** [comment]
yes, --local will run salt-call masterless
thanks @jacksontj for the catch!

**Comment by kiorky** [comment]
@steverweber minion notifying the master in a connected workflow is totally normal.
Even with using salt-call. Unless using --local (meaning masterless), you are connected.
This means that you are allowed to have bidirectional deployments and results dispatching (Getting your master to run a job on a bunch of minion(s) using ``salt`` is one of the possibilities you have, where the results will be published when the job(s) are finished back to the master.
One another solution is to run a job directly from a specific minion, using ``salt-call``, but this minion has still to return the result to make the master aware of it.

**Comment by steverweber** [comment]
yap... I thought salt-call defaulted to local mode.. But i just learned today that I need to use the --local switch.

**Pull request merged**
