### PR TITLE
Add Astra Linux fix to grains

### LINKED ISSUE #59332: [FEATURE REQUEST] Astra Linux compability
I am working closely with Astra Linux GNU/Linux which [is a Debian derivative](https://wiki.debian.org/Derivatives/Census/AstraLinux). It have two editions, Common and Secure, which have `os_family` `AstraLinuxCE` and `AstraLinuxSE`. Both editions use the Debian packages toolchain and should be decided fully compatible with `modules.aptpkg`. I'd like to make a PR to match Astra Linux with `aptpkg`, but I failed to find logic where `os_family` is testing.

For now there is just workarounds with `/etc/lsb_release` or grains to make `modules.pkg` working with this distro.

### PR DESCRIPTION
**Pull request by bergentroll**
### What does this PR do?
It supposed to make `module.apt_pkg` usable on Astra Linux distribution, but there is some mismatch between tests and a real host.

### What issues does this PR fix or reference?
Fixes: #59332

### Merge requirements satisfied?
- [x] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by bergentroll** [comment]
I figure out my fault and fix it. Tested both on Astra Linux Orel and Astra Linux Smolensk hosts.

**Comment by bergentroll** [comment]
@ScriptAutomate, I rebased from master.

**Comment by bergentroll** [comment]
@ScriptAutomate, I rebased from master.

**Review by Ch3LL — DISMISSED** [review]

**Comment by Ch3LL** [comment]
looks like there is just a merge conflict that needs to be cleaned up here.

**Review by twangboy — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
