### PR TITLE
rooted config

### PR DESCRIPTION
**Pull request by h4ck3rm1k3**
This is a patch to allow for salt cloud to be used without installing it and includes a tutorial on that.

### CODE REVIEW

**Comment by h4ck3rm1k3** [comment]
some of those jenkins jobs are 404
https://jenkins.saltstack.com/job/salt-pr-linode-ubuntu14.04-n/225/
https://jenkins.saltstack.com/job/salt-pr-linode-cent7-n/225/
also the pylint stuff i cannot see the details, only the numbers.

**Comment by whiteinge** [comment]
Go Go Jenkins!

**Comment by whiteinge** [comment]
That should trigger a rebuild. For the pylint errors, click on the 'violations' link in the sidebar.

**Comment by h4ck3rm1k3** [comment]
This is strange
I fixed the outstanding lint issues, but not the lint job is reporting issues on files not even in the repo!

> 12:40:56 salt/client/ssh/wrapper/mine.py:1: [W9903(no-encoding-in-file), ] PEP263: Use UTF-8 file encoding
> 12:40:56 salt/client/ssh/wrapper/mine.py:49: [E1123(unexpected-keyword-arg), get] Unexpected keyword argument 'mine' in method call
> 12:40:56 ************* Module salt.returners.kafka_return
> 12:40:56 salt/returners/kafka_return.py:85: [W8391(blank-line-at-end-of-file), ] PEP8 W391: blank line at end of file
> 12:40:56 salt/returners/kafka_return.py:35: [W0611(unused-import), ] Unused import SimpleConsumer
> 12:40:56 salt/returners/kafka_return.py:31: [W0611(unused-import), ] Unused import salt

https://jenkins.saltstack.com/job/salt-pr-lint-n/323/console

**Comment by h4ck3rm1k3** [comment]
rebased and squashed for convenience.

**Comment by s0undt3ch** [comment]
Rule of thumb, on files which you didn't touch there's no need to fix the lint issues. Unless you ever happen to move a module which causes the lint error.

**Comment by h4ck3rm1k3** [comment]
Yes I fixed my issues, but just commenting on the strangeness in the build.

**Comment by h4ck3rm1k3** [comment]
Yeah! thanks!

**Pull request merged**
