### PR TITLE
Move mdata grains from core.py to mdata.py

### PR DESCRIPTION
**Pull request by sjorge**
### What does this PR do?
Filters out the mdata grains from core.py and moves them to mdata.py

Less stuff in core.py is probably a long term goal to improve readability of it.

### What issues does this PR fix or reference?
N/a

### Previous Behavior
Code was in core.py

### New Behavior
Code is now in mdata.py

We now also parse the SDC grains defined in there specifications.

### Tests written?
No

@cachedout @rallytime any way to properly announce deprecation of grains? I would like to drop the hypervisor_uuid and datacenter grains in favor of grabbing the from mdata:sdc:*

### CODE REVIEW

**Comment by sjorge** [comment]
Test failure seems unrelated? Unless I am missing something.

**Review by cachedout — APPROVED** [review]

**Comment by sjorge** [comment]
So idea how to deprecate grains?
I guess we could just drop them and add a release note about it, as the data is still available.

**Comment by cachedout** [comment]
We just need to include them in the release announcement to put them on a deprecation path.

**Comment by sjorge** [comment]
Cool, then the following should end up in the notes for the next release:
```
hypervisor_uuid -> mdata:sdc:server_uuid
datacenter -> mdata:sdc:datacenter_name
```

**Comment by cachedout** [comment]
@sjorge The release notes are here if you would like to update them: https://github.com/saltstack/salt/blob/develop/doc/topics/releases/oxygen.rst

**Comment by sjorge** [comment]
What 2 release after oxygen? So I can mention the correct name in the follow up pr.

**Comment by rallytime** [comment]
@sjorge Looks like `Neon` is two features after `Oxygen`.

**Pull request merged**
