### PR TITLE
WIP for GCE salt cloud volume support.

### PR DESCRIPTION
**Pull request by Cidan**
### What does this PR do?

This PR adds support for a volume list in salt cloud GCE profiles.
### What issues does this PR fix or reference?

None.
### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by Cidan** [comment]
Hey everyone,

This is still a semi-WIP. I'm submitting this PR to solicit feedback and realize there are (probably?) some linting errors and a few things that need to be cleaned up.

Essentially, while migrating our services from AWS -> GCE, we found the current volume definition method for GCE instances in Salt cloud using `ex_disks_gce_struct` to be extremely cumbersome and not flexible enough. I've essentially mimicked the EC2 driver behavior by allowing a profile definition to contain an array of volumes that will be created post-instance launch and attached in order.

I am aware that GCE is capable of creating an instance with disks defined in one API call, but opted against implementing volumes in such a manner for two different reasons:

1) As previously mentioned, the `ex_disks_gce_struct` definition is extremely complex and I did not want to implement logic to handle boot versus non boot drives, first drive, etc.

2) All of the code we need is already written and tested in Salt cloud. I wanted to reduce complexity and lines of code as to minimize bugs in general.

I've tested this in our infrastructure and everything works great. I still want to do a bit more testing for various scenarios and clean up some stuff.

Any and all feedback and thoughts would be great.

Thanks!

**Comment by rallytime** [comment]
Hi @Cidan That explanation sounds good to me. There are some [pylint errors](https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/5016/violations/file/salt/cloud/clouds/gce.py/) that need to be cleaned up, also added some docs for your new function would be great as well. 

@erjohnso Can you take a look at this one as well?

**Comment by erjohnso** [comment]
@Cidan - Thanks for this!  Yes, that `ex_disks_gce_struct` was a bad call on my part and I was being very lazy. :(  Ideally, we'd make a fix in libcloud to be more developer-friendly and not force you to play with an underlying JSON snippet.

@rallytime - LGTM once jenkins is happy.

/cc @supertom in case you want to look at fixing up my past poor decisions.

**Comment by Cidan** [comment]
@erjohnso No worries! I'll make sure to fix up the Jenkins bits a bit later today. To be clear, I think `ex_disks_gce_struct` is just fine for a lower level API, it's just a bit terse to configure in a yaml definition, etc.

**Comment by rallytime** [comment]
@Cidan A couple more small changes for pylint, if you wouldn't mind grabbing those:
https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/5089/violations/file/salt/cloud/clouds/gce.py/

**Comment by Cidan** [comment]
@rallytime Is there an easy way for me to lint locally?

**Comment by rallytime** [comment]
@Cidan Definitely! Check out [these docs](https://docs.saltstack.com/en/latest/topics/development/conventions/style.html#linting). There are two lint files that come with salt. The `.pylintrc` is the most comprehensive one. The one that jenkins uses is the `.testing.pylintrc` file.

**Comment by Cidan** [comment]
@rallytime It looks like some of the tests were aborted/cancelled, but this should be good to go. Would like to get a full green run before hand though!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Thanks for the bump. I was hoping we'd sorted out the testing issues we had earlier this afternoon. I've kicked the tests off again. Hopefully there aren't any hiccups this time around.

**Comment by Cidan** [comment]
@rallytime Awesome, :)

**Comment by cachedout** [comment]
Looks great. Thank you very much, @Cidan

**Pull request merged**
