### PR TITLE
Handle lack of exception class in older git backends

### PR DESCRIPTION
**Pull request by cachedout**
Some older gitbackends do not have the required exception handling classes. Handle this by logging a general exception.

### CODE REVIEW

**Comment by terminalmage** [comment]
Do we get a `NameError` as a result when this happens?

**Comment by terminalmage** [comment]
I just checked and GitPython 0.3.2 (the earliest supported version) does indeed have these exception classes:

```
>>> import git
>>> git.__version__
'0.3.2'
>>> git.exc.NoSuchPathError
<class 'git.exc.NoSuchPathError'>
>>> git.exc.InvalidGitRepositoryError
<class 'git.exc.InvalidGitRepositoryError'>
>>>
```

Can I see an example of this problem?

**Comment by cachedout** [comment]
IIRC it was a NameError but I am blanking on which platform I saw this on. I did, at the time, attempt to import the given package `git.exc` and it failed but I didn't go beyond that. I'll poke around tomorrow and try to reproduce this again.

**Comment by cachedout** [comment]
@terminalmage I lost track of this and I don't remember now where I saw this. I don't see any harm in getting it in if you don't though.

**Comment by terminalmage** [comment]
I guess it's not going to hurt anything, but I'm wondering why the inner try/except was moved inside the if block.

**Comment by cachedout** [comment]
Sheesh. What was I thinking? Good eye. Thanks.

**Comment by cachedout** [comment]
Err, wait. No it wasn't. There's a try up there at the top. Still, this is a terrible way to format this. I'll redo it.

**Comment by terminalmage** [comment]
Oh you're right, I lost the ``try`` line because I was focusing on the red lines in the diff. My bad!

**Comment by terminalmage** [comment]
This looks good. Perhaps the only change I would make to this would be to tweak the exception logging to recommend that this be reported, so that we can properly account for future changes to GitPython which would evade the first except block there.

**Comment by terminalmage** [comment]
The idea being that if we tell someone to report this in the log message, they're more likely to do so than to just shrug their shoulders and move on.

**Comment by cachedout** [comment]
@terminalmage I'm glad you mention it. I considered it and then didn't do it. This persuades me. Will update.

**Comment by terminalmage** [comment]
Looks great!

**Pull request merged**
