### PR TITLE
Windows Status Addendum

### PR DESCRIPTION
**Pull request by Narcolapser**
Some updates in the windows status module. Hoping to get it a little closer to it's linux counter part. I'm a linux man myself, so I do not attest to the ways I get the information to be the best way, but they are ways that work, and involve no new external programs or python libraries. Trying to keep this pure Salt-y-ness.

### CODE REVIEW

**Comment by thatch45** [comment]
please review @UtahDave

**Comment by rallytime** [comment]
@Narcolapser mind grabbing the pylint errors for the win_* files? The ddns ones are not related:

https://jenkins.saltstack.com/job/salt-pr-lint-n/1361/violations/

**Comment by Narcolapser** [comment]
That should do it. Here's hoping...

**Comment by Narcolapser** [comment]
Never mind. Got a lot to work on with it now. I'll see if I can fix these today.

**Comment by UtahDave** [comment]
Go Go Jenkins!

**Comment by UtahDave** [comment]
Hey, @Narcolapser this code looks really good! Thanks for your work on this.
There are just a couple more lint fixes.

Also, we really try to avoid using subprocess in execution modules. Would you mind swapping out the use of subprocess with ```cmd.run```?  Here's an example of the usage in another module: https://github.com/saltstack/salt/blob/f4b1688ad8e9ffc47a4e44a54ff67b35c9948e39/salt/modules/win_service.py#L320
Using ```cmd.run``` allows us to better control the security off shell calls among other things.

Thanks!

**Comment by Narcolapser** [comment]
Alright, the remaining lint errors are not in my file. Let me know if there are any other details you want me to fix.

**Comment by UtahDave** [comment]
Thanks for the great work, @Narcolapser!

**Pull request merged**
