### PR TITLE
Fix sanitize_win_path function

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?
Fixes problem where the `salt.utils.path.sanitize_win_path` function would fail if it received a Unicode value. This was a problem as the `fileclient` started sending Unicode values on the develop branch. This would cause any state run to fail with the following stacktrace:

```
Traceback (most recent call last):
  File "c:\salt-dev\salt\salt\minion.py", line 1536, in _thread_return
    return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
  File "c:\salt-dev\salt\salt\executors\direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "c:\salt-dev\salt\salt\modules\state.py", line 1186, in sls
    high_, errors = st_.render_highstate({opts['environment']: mods})
  File "c:\salt-dev\salt\salt\state.py", line 3728, in render_highstate
    sls, saltenv, mods, matches)
  File "c:\salt-dev\salt\salt\state.py", line 3382, in render_state
    state_data = self.client.get_state(sls, saltenv)
  File "c:\salt-dev\salt\salt\fileclient.py", line 406, in get_state
    sls_url = salt.utils.url.create(sls + u'.sls')
  File "c:\salt-dev\salt\salt\utils\url.py", line 48, in create
    path = salt.utils.path.sanitize_win_path(path)
  File "c:\salt-dev\salt\salt\utils\path.py", line 343, in sanitize_win_path
    winpath = winpath.translate(trantab)
TypeError: character mapping must return integer, None or unicode
```

### What issues does this PR fix or reference?
Found while trying to test another issue

### Tests written?
No

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by damon-atkins** [comment]
Should have `sanitize_win_path` call  `salt.utils.file.safe_filepath(file_path_name, dir_sep=None)`  or replace the use of `sanitize_win_path` with `safe_filepath`.  It supports all platforms, and means salt code is consistent across platforms.

**Comment by damon-atkins** [comment]
https://github.com/saltstack/salt/issues/44793

**Comment by twangboy** [comment]
@terminalmage Should we replace the `salt.utils.path.sanitize_win_path` function with the `salt.utils.files.safe_filepath` function?

**Comment by damon-atkins** [comment]
salt.utils.files.safe_filepath() just need to ensure on windows that if you have a  `/` (i.e. posix or url path) path that you convert to `\` before hand, assuming you want sub-directories.   It could be enhance to convert as well e.g. convert_from_sep=None i.e no conversion by default.

**Review by rallytime — APPROVED** [review]

**Pull request merged**
