### PR TITLE
Merge 2015.2 forward into develop

### PR DESCRIPTION
**Pull request by rallytime**

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by traxair** [comment]
Hey, could you merge 80197a0 into 2015.2 too?

**Comment by techhat** [comment]
Ping @rallytime.

**Comment by rallytime** [comment]
@traxair Sure. I've marked the original pull request, which went into develop, for backporting.

**Pull request merged**
