### PR TITLE
Add event_return and move toward using slack.post_message for sending…

### PR DESCRIPTION
**Pull request by rterbush**
Not even sure if this is a good idea, but am sure some kind soul will tell me if it isn't. :smile: 

Python is not my native language, so I am looking forward to any critique of my approach. There must be a better way of getting to these json key/values.

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @rterbush 

Thanks for sending this over. The event return bit looks fairly all right. It might be a good idea to check some list lengths before attempting to retrieve elements so that Python doesn't throw a nasty error on an attempt to access an element that isn't present.

I'm a little more concerned about the other refactoring, though. This looks like we're changing configuration value names around for people, which will likely bite at least a few. Is the intention here simply DRY to consolidate the functionality into the state? We should probably discuss this bit a little bit more before we merge. Thanks!

**Comment by rterbush** [comment]
@cachedout Thanks for the feedback on the code. I'll look into how to accomplish the check of list lengths.

The other refactoring was inspired by trying to get the behavior I was seeing in the state. With the current returner, I was unable to post a message to slack with an identity other than my own account identity. This has the side effect of not triggering an alert sound since I assume the app believes I am the message author. Rather than go down the path of using a webhook instead, it made sense to take the existing functionality of the state and while I was at it, align the configuration parameters. The benefit here being that it may be possible to share those credential values between state and returner.

**Comment by cachedout** [comment]
@rall0r Thanks for the response. I think that's fine and totally beneficial so long as we don't break existing configurations for people. So long as we can ensure a smooth transition for users, I'm on board with a refactor in this area.

**Comment by basepi** [comment]
Based on @cachedout's concerns, would it be wise to introduce a deprecation path for the old configuration values? Allow both for a time, with a `warn_until`?

**Comment by cachedout** [comment]
Bump @rterbush 

Just checking to see where we are on this one. Thanks!

**Comment by rterbush** [comment]
I'm not going to be able to get to this in the short term. Working on first public release this week...

**Comment by cachedout** [comment]
@rterbush Since it sounds like you're busy right now and blocked on working on this, I'm going to close this for the time being. Let me know when you're ready and I'll happily re-open it or you can submit a new one. It just helps us manage the incoming flow of PRs a little easier if we don't let them languish like this. (And it will prevent merge conflicts as well.) We're still looking forward to having this in, though! Thanks.

**Pull request closed without merging**
