### PR TITLE
Fix value of `virtual` grain when using `virt-what`

### PR DESCRIPTION
**Pull request by eliasp**
### What does this PR do?

`virt-what` might return multiple lines, depending on what it detected (e.g. `lxc` inside a `HyperV` VM), where the last line corresponds to the most likely match.

Until now, Salt evaluated the whole multi-line output as a single string, which caused quite inaccurate matches. This commit changes this behavior to only evaluate the last line of the `virt-what` output.

### What issues does this PR fix or reference?

A similar issue is described in #25697, but might actually have a different root cause.

### Previous Behavior
The `virtual` grain reported `HyperV`, although Salt was executed in a `systemd-nspawn` container inside a HyperV-based Ubuntu VM.

### New Behavior

The `virtual` grain reports now `lxc` which reflects what `virt-what` determines.

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by cachedout — COMMENTED** [review]
I am hesitant to merge this without calling it out in the release notes. We should make it very clear whenever a grain that may be used for targeting is modified so that people can test their upgrade paths.

**Comment by cachedout** [comment]
@eliasp Can you add this to the release notes? Then I think we can safely get this in.

**Comment by cachedout** [comment]
Bump @eliasp

**Comment by eliasp** [comment]
@cachedout Done.

**Pull request merged**
