### PR TITLE
fix issue #26161: on RedHat family systems touch /var/lock/subsys/$SE…

### PR DESCRIPTION
**Pull request by bastiaanb**
…RVICE to ensure the daemon will be stopped on shutdown.

### CODE REVIEW

**Comment by jfindlay** [comment]
@dmurphy18, please review.

**Comment by dmurphy18** [comment]
[ $RETVAL = 0 ] is not a proper test, presume you really want  [ $RETVAL-eq 0 ], rather than attempting assignment here.

**Comment by bastiaanb** [comment]
@dmurphy18 : [ $RETVAL =  0 ] is a proper equally test, not an assignment, see 'man test'. However -eq is better indeed, because that is an arithmetic rather than a string comparison.
I'll update the PR.

**Comment by dmurphy18** [comment]
Actually I was being polite,

using a string comparison for return values has been problematic in shell
scripts in the past on some platforms, hence use of -eq is preferred.

David Murphy
Unix Engineer
SaltStack

3400 North Ashton Blvd., Suite 110 | Lehi, UT 84043, USA

office 801-207-7440 | mobile 385-333-1060
dmurphy@saltstack.com |  www.saltstack.com
*SaltConf16 - Salt Lake City - April 19-21, 2016​ - www.saltconf.com
<http://www.saltconf.com/>​*

**Comment by cachedout** [comment]
Great! Thank you very much @bastiaanb. This fix is much appreciated.

**Comment by bastiaanb** [comment]
Your welcome. Thanks for merging this so quickly.
@dmurphy18 : that's what I get for lazily copying that line from the centos6 httpd initscript ;-)

**Pull request merged**
