### PR TITLE
[DOCS] Fix RST formatting for success_retcodes option in cmd states

### PR DESCRIPTION
**Pull request by terminalmage**
This fixes some bad RST formatting for this option's docs, and also rewords them slightly.

### CODE REVIEW

**Review by DmitryKuzmenko — DISMISSED** [review]
@terminalmage could you please run pre-commit on this?

**Comment by terminalmage** [comment]
@DmitryKuzmenko Done.

**Comment by DmitryKuzmenko** [comment]
@terminalmage failed again.

**Comment by DmitryKuzmenko** [comment]
Also please remove import six manually.

**Review by DmitryKuzmenko — DISMISSED** [review]

**Comment by terminalmage** [comment]
@DmitryKuzmenko All passing now

**Comment by DmitryKuzmenko** [comment]
@terminalmage awesome!

**Review by s0undt3ch — DISMISSED** [review]

**Comment by Ch3LL** [comment]
@terminalmage mind fixing the merge conflict here?

**Comment by terminalmage** [comment]
@Ch3LL done! :slightly_smiling_face:

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
