### PR TITLE
Add ability to ignore service state actions when in chroot

### LINKED ISSUE #62446: [FEATURE REQUEST] Ignore service state actions when in chroot
**Is your feature request related to a problem? Please describe.**
We have a common workflow where we need to manage services, but only when Salt is not running in a chroot. Unless we gate the state blocks with Jinja, it runs and fails since the chroot does not have enough access to perform the action.

**Describe the solution you'd like**
Simple parameter for every state module function which will ignore actions while in chroot, but act normally when outside of it.

**Describe alternatives you've considered**
Wrapper Jinja around _every_ service state block (or macros):

```
{% if grains.get("virtual_subtype") != "chroot" -%}
manage_service:
  service.running:
    - name: service_name

{% endif -%}
```

**Additional context**
Somewhat related to issue #38751, although we **don't** want to take action with this workflow... whereas the solution to that issue would allow some actions to be be taken from within the chroot if allowed.

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

### PR DESCRIPTION
**Pull request by nicholasmhughes**
### What does this PR do?
See issue.

### What issues does this PR fix or reference?
Fixes: #62446 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by OrangeDog** [comment]
👎 https://github.com/saltstack/salt/issues/62446#issuecomment-1211009983

**Comment by Ch3LL** [comment]
I think I tend to side with @OrangeDog 's concern that this argument is a very specific use case others would likely not use, and would best be settled with using jinja logic.  Let me get some more feedback from the core team though.

**Review by twangboy — DISMISSED** [review]

**Comment by nicholasmhughes** [comment]
re-run full all

**Comment by OrangeDog** [comment]
> Let me get some more feedback from the core team though.

Did that happen?

**Comment by nicholasmhughes** [comment]
re-run pr-freebsd-131-amd64-py3-pytest

**Review by twangboy — APPROVED** [review]

**Comment by nicholasmhughes** [comment]
Closing in favor of #62717

**Pull request closed without merging**
