### PR TITLE
Fixes #36240

### LINKED ISSUE #36240: win_certutil add_store state not installing certificates
### Description of Issue/Question
The add_store function in the win_certutil module is not adding new certificates.

### Setup

Here is an example state file called
certificates.sls
```
salt://win/OURSISCAcert.cer:
   certutil.add_store:
       - store: TrustedPublisher
```

### Steps to Reproduce Issue
run the following

```
salt '000004' state.apply certificates
```
The output will be something like:

```
000004:
----------
          ID: salt://win/OURSISCAcert.cer
    Function: certutil.add_store
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1733, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1651, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\var\cache\salt\minion\extmods\states\win_certutil.py", line 66, in add_store
                  out = __salt__['certutil.add_store'](cert_file, store)
                File "c:\salt\var\cache\salt\minion\extmods\modules\win_certutil.py", line 87, in add_store
                  cert_file = __salt__['cp.cache_file'](source, saltenv)
                File "C:\salt\bin\lib\site-packages\salt\modules\cp.py", line 421, in cache_file
                  result = _client().cache_file(path, saltenv)
                File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 178, in cache_file
                  return self.get_url(path, '', True, saltenv, cachedir=cachedir)
                File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 706, in get_url
                  **get_kwargs
                File "C:\salt\bin\lib\site-packages\salt\utils\http.py", line 484, in query
                  **req_kwargs
                File "C:\salt\bin\lib\site-packages\tornado\httpclient.py", line 102, in fetch
                  self._async_client.fetch, request, **kwargs))
                File "C:\salt\bin\lib\site-packages\tornado\ioloop.py", line 453, in run_sync
                  return future_cell[0].result()
                File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 232, in result
                  raise_exc_info(self._exc_info)
                File "<string>", line 3, in raise_exc_info
              ValueError: Unsupported url scheme: c:\salt\var\cache\salt\minion\files\base\win\OURSISCAcert.cer
     Started: 14:46:34.557000
    Duration: 406.0 ms
     Changes:   

```

### Versions Report
```
Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: 1.4.2
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.11 (default, Aug  9 2016, 15:45:42)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.4.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.5
 
System Versions:
           dist: fedora 23 Twenty Three
        machine: x86_64
        release: 4.6.7-200.fc23.x86_64
         system: Linux
        version: Fedora 23 Twenty Three

```

### PR DESCRIPTION
**Pull request by ghost**
### What does this PR do?

The  _add_store_ function is failing with a bit traceback. This PR is an effort to fix this
### What issues does this PR fix or reference?
#36240
### Previous Behavior

Before this PR, the _add_store_ state function will call the identically named module function, passing the name of the cached file as an argument. However the module function wants to parse it and cache it all over again creating problems. Specifically we can see something like the following traceback

```
----------
          ID: salt://win/OURSISCAcert.cer
    Function: certutil.add_store
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1733, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1651, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\var\cache\salt\minion\extmods\states\win_certutil.py", line 66, in add_store
                  out = __salt__['certutil.add_store'](cert_file, store)
                File "c:\salt\var\cache\salt\minion\extmods\modules\win_certutil.py", line 87, in add_store
                  cert_file = __salt__['cp.cache_file'](source, saltenv)
                File "C:\salt\bin\lib\site-packages\salt\modules\cp.py", line 421, in cache_file
                  result = _client().cache_file(path, saltenv)
                File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 178, in cache_file
                  return self.get_url(path, '', True, saltenv, cachedir=cachedir)
                File "C:\salt\bin\lib\site-packages\salt\fileclient.py", line 706, in get_url
                  **get_kwargs
                File "C:\salt\bin\lib\site-packages\salt\utils\http.py", line 484, in query
                  **req_kwargs
                File "C:\salt\bin\lib\site-packages\tornado\httpclient.py", line 102, in fetch
                  self._async_client.fetch, request, **kwargs))
                File "C:\salt\bin\lib\site-packages\tornado\ioloop.py", line 453, in run_sync
                  return future_cell[0].result()
                File "C:\salt\bin\lib\site-packages\tornado\concurrent.py", line 232, in result
                  raise_exc_info(self._exc_info)
                File "<string>", line 3, in raise_exc_info
              ValueError: Unsupported url scheme: c:\salt\var\cache\salt\minion\files\base\win\OURSISCAcert.cer
     Started: 14:46:34.557000
    Duration: 406.0 ms
     Changes:   
```
### New Behavior

If I just pass the URL to the module function everything is fine and then I get the following traceback.

```
000004:
----------
          ID: salt://win/OURSISCAcert.cer
    Function: certutil.add_store
      Result: True
     Comment: 
     Started: 15:20:24.432000
    Duration: 375.0 ms
     Changes:   
              ----------
              added:
                  salt://win/OURSISCAcert.cer
```
### Tests written?

No

### CODE REVIEW

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by hrumph** [comment]
This fixes #33589. I shoud have referecned this issue and not created a new one (didn't do a search first. my bad.)

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@opdude Any comments on this one?

**Comment by opdude** [comment]
@cachedout Does salt know not to cache the file twice? If it does then this is fine from me.

Otherwise maybe we should check if the file is local or not before we try and cache it?

**Comment by hrumph** [comment]
@opdude AFAICS the salt minion sees that the file has already been cached and doesn't recache it, so there isn't all that much duplication of work.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@hrumph We had some tests fail that look like they are related to this. Would you mind taking a look?

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by hrumph** [comment]
@rallytime, I still haven't looked into the failed tests. Sorry about this. stuff came up in my life. Will try to get back to this later in the week unless someone else wants to take it over. @opdude?

**Comment by rallytime** [comment]
Hi @hrumph - I have made a pull request against your branch that fixes up the test failures. I think when you merge that in, this PR should update with the change and we can merge this all in. If that doesn't work, I can make a separate pull request to Salt directly with both of our changes to replace this one. Let me know what you'd like to do.

Thanks again for this change!

**Comment by hrumph** [comment]
Thanks for this @rallytime. I do apologise for this fail. I hate the idea of leaving a PR in limbo as much as anyone. Some things happened IRL that I had to take care of.

**Comment by rallytime** [comment]
@hrumph No problem at all! We <3 fixes and want to help get them in. :)

**Pull request merged**
