### PR TITLE
adding chef unit test case

### PR DESCRIPTION
**Pull request by jayeshka**
Hi @rallytime , Please review the chef_test case and let me know if you have any review comments.

### CODE REVIEW

**Comment by rallytime** [comment]
It looks like these tests had a hard time completing. Let's try again.

**Comment by rallytime** [comment]
@jayeshka Did you mean to close this pull request? It looks like you deleted the branch perhaps on accident and closed the PR?

**Comment by jayeshka** [comment]
Sorry I accidently closed it. I didn't mean to close it.

**Comment by rallytime** [comment]
Not a problem, I just wanted to make sure. :)

**Pull request merged**
