### PR TITLE
Fix requirements files paths

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by aboe76** [comment]
@s0undt3ch thanks, can this be merged upstream to develop branch?

**Comment by jfindlay** [comment]
@s0undt3ch, I believe this is the change you want:
```
-SALT_REQS = os.path.join(os.path.abspath(SETUP_DIRNAME), '_requirements.txt')
-SALT_ZEROMQ_REQS = os.path.join(os.path.abspath(SETUP_DIRNAME), 'zeromq-requirements.txt')
-SALT_CLOUD_REQS = os.path.join(os.path.abspath(SETUP_DIRNAME), 'cloud-requirements.txt')
-SALT_RAET_REQS = os.path.join(os.path.abspath(SETUP_DIRNAME), 'raet-requirements.txt')
+SALT_REQS = os.path.join(os.path.abspath(SETUP_DIRNAME), 'requirements', 'base.txt')
+SALT_ZEROMQ_REQS = os.path.join(os.path.abspath(SETUP_DIRNAME), 'requirements', 'zeromq.txt')
+SALT_CLOUD_REQS = os.path.join(os.path.abspath(SETUP_DIRNAME), 'requirements', 'cloud.txt')
+SALT_RAET_REQS = os.path.join(os.path.abspath(SETUP_DIRNAME), 'requirements', 'raet.txt')
```

**Comment by s0undt3ch** [comment]
@jfindlay you are correct, I was too fast ;)

**Comment by s0undt3ch** [comment]
New PR https://github.com/saltstack/salt/pull/19655

**Pull request closed without merging**
