### PR TITLE
keep cache_copied_files variable a list

### PR DESCRIPTION
**Pull request by mchugh19**
### What does this PR do?
Retains list datatype of cache_copied_files variable

### What issues does this PR fix or reference?
#56324 

### Previous Behavior
Capable of runtime error `AttributeError: 'set' object has no attribute 'extend'`

### New Behavior
Datatype of cache_copied_files is consistently a list 

### Tests written?
Yes 

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by mchugh19** [comment]
Minor fix with no change in functionality. Would be nice to get into a backport.

**Comment by garethgreenaway** [comment]
@mchugh19 Thanks for the fix.  Would be great to get a testcase on this one to prevent regressions.

**Comment by mchugh19** [comment]
@garethgreenaway tests added! Looks like the issue can be replicated with includes. I've validated the issue is present with the saltcheck integration test without the fix, and corrected with the patch. This should be good to go!

**Comment by mchugh19** [comment]
@Ch3LL it'd be nice if this could make 3000.1

**Comment by Ch3LL** [comment]
let me update the branch, and have the tests run and see about getting it in. i'll let ya know

**Review by s0undt3ch — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Review by cmcmarrow — APPROVED** [review]

**Review by Ch3LL — APPROVED** [review]

**Comment by Ch3LL** [comment]
@mchugh19 been merged and will be included in 3000.1. thanks for the headsup.

**Pull request merged**
