### PR TITLE
Add bigip partition & iRule support

### PR DESCRIPTION
**Pull request by jayok007**
### What does this PR do?

It allows you to specify the partition when you want to work with virtual servers, pools, profiles, monitors & nodes. I also added the feature to work with iRule.

It adds the parameter partition in each REST request to the API inside the payload or in the URI.

### What issues does this PR fix or reference?

It's just feature.

### Tests written?

No, but I execute all states functions to make sure everything is working fine on a Big-IP instance.

### Commits signed with GPG?

No.

### CODE REVIEW

**Review by dwoz — CHANGES_REQUESTED** [review]
@jayok007 Thanks for your contribution. Are you able to please make sure this change has test coverage?

**Comment by jayok007** [comment]
So I test it again one more time on a Big-IP instance all stuff that were in place are still working, create object, check each fields, then execute a second time, check idempotence (correct two things in last commits). So yes i'm very confident that nothing will stop working since the code logic is still the same if you don't have partition. And partition wise, we have been for the few last months in my company and no issue.

**Comment by jayok007** [comment]
> @jayok007 Thanks for your contribution. Are you able to please make sure this change has test coverage?

What do you want me to do ?

**Comment by Ch3LL** [comment]
thanks for testing that against your infrastructure. we also want to ensure some written tests are added so this does not regress in the future as others add changes as well. We have some documentation here: https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html on how to add to our test runner. I think a unit test will be the best approach here as it looks like it would require a device otherwise.

**Comment by sagetherage** [comment]
@jayok007 please rebase this against the master branch

**Comment by sagetherage** [comment]
@jayok007 please rebase this against the master branch

**Comment by sagetherage** [comment]
Reviewed in Grooming 2021-APR-05 tests are not complete and would need to be rebased against master - considering closing

**Comment by varyoo** [comment]
@jayok007 please rebase ;-)

**Comment by sagetherage** [comment]
@jayok007 can you please rebase against the master branch? we are no longer taking changes against develop.

Discussed in Grooming 2021-APR-19 I will give this 2 more weeks and if no response, will close.

**Comment by sagetherage** [comment]
Reviewed in Grooming 2021-MAY-03 closing

**Pull request closed without merging**
