### PR TITLE
Fixes the zfs state module to not send -t options to zfs get on Solaris as Solaris does not have the -t for zfs get

### PR DESCRIPTION
**Pull request by jnieuwen**
### What does this PR do?
When using the zfs.filesystem_present state module properties are not correctly set on Solaris. This pull request fixes this.

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
zfs.filesystem_present calls _dataset_present. This function always sends a type to the zfs.get execution/module function, causing -t be added to the zfs get command. Solaris does not have the -t option for zfs get. However the -t is also not necessary for the command. 

### New Behavior
This change makes sure the type option/parameter is not sent to the zfs.get execution module/function when run on Solaris.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by cmcmarrow** [comment]
@jnieuwen thank you for the PR. Can we get a test? I know Salt Stack does not test Solaris on GitHub but we do run tests for Solaris when developing for it.

**Comment by dmurphy18** [comment]
@jnieuwen Wondering what versions of Solaris and for which platforms you are running on ?

**Comment by dmurphy18** [comment]
@jnieuwen Reminder, what versions of Solaris and platforms

**Comment by sagetherage** [comment]
with no tests written we will have to move this to Magnesium - updating

**Comment by sagetherage** [comment]
Test case has still not be written - de-scoping from Magnesium release

**Comment by dmurphy18** [comment]
@sagetherage I fixed this independently recently and it has already been merged in , https://github.com/saltstack/salt/pull/59998

**Pull request closed without merging**
