### PR TITLE
Fix `unit.utils.test_process` for Windows

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?
Fixes the pickling error on Windows for the 4 ProcessManager tests. Uses decorators to create the utility functions for `add_process`.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt-jenkins/issues/439

### Tests written?
Yes

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by rallytime — APPROVED** [review]
Nice!

**Review by terminalmage — APPROVED** [review]

**Review by cachedout — APPROVED** [review]
Very nice.

**Comment by rallytime** [comment]
@twangboy Lint :)

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/16800/violations/file/tests/unit/utils/test_process.py/

**Comment by twangboy** [comment]
Rebased...

**Pull request merged**
