### PR TITLE
Fix handling of zfs datasets/snapshots/mountpoints with spaces

### PR DESCRIPTION
**Pull request by 3add3287**
### What does this PR do?
Properly quote the names of zfs datasets, snapshots and mount point names where necessary to handle cases where the path contains spaces

### What issues does this PR fix or reference?
#44401

### Previous Behavior
When paths for zfs filesystems/datasets/mount points had a space in them, the zfs command would be executed with the wrong arguments and throw an error.

### New Behavior
Dataset names or mount points are now properly quoted so spaces work as they should

### Tests written?
No

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by sjorge — APPROVED** [review]

**Comment by sjorge** [comment]
Thanks for getting this fixed, I was waiting on this before giving both the zpool and zfs modules a cleanup pass (which is needed tbh)!

**Comment by 3add3287** [comment]
Sorry for taking so long. Travel followed by the pre-holiday craziness took it's toll on my schedule

**Comment by rallytime** [comment]
Thanks for opening this up @3add3287. There are some tests failing here that need to be addressed before we can get this in:
- unit.modules.test_zfs.ZfsTestCase.test_create_error_missing_dataset
- unit.modules.test_zfs.ZfsTestCase.test_create_error_missing_parent
- unit.modules.test_zfs.ZfsTestCase.test_create_error_no_such_pool
- unit.modules.test_zfs.ZfsTestCase.test_create_error_trailing_slash
- unit.modules.test_zfs.ZfsTestCase.test_create_success
- unit.modules.test_zfs.ZfsTestCase.test_create_success_with_create_parent

https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/18106/

**Comment by rallytime** [comment]
Thanks @3add3287!

**Pull request merged**
