### PR TITLE
Salt is now pip install'able in windows

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Fixes #26305

**Comment by s0undt3ch** [comment]
Still missing putting the DLLs in place

**Comment by twangboy** [comment]
Should also fix #23371

**Comment by s0undt3ch** [comment]
@terminalmage this PR will fix the issue you filed, #11046.
@ryan-lane this PR will fix the issue you filed, #25094.

Since both issues refer to using `pip --editable`, you both have 2 options, pass `--install-option='<look up the new option flags>'` or set the corresponding environment variables.
I advise using the environment variables because pip passes the options to all dependencies being installed which will trigger errors.

**Comment by s0undt3ch** [comment]
@twangboy, yes, this PR also fixes #23371.

**Comment by s0undt3ch** [comment]
This PR needs to be merged forwarded.

**Comment by ryan-lane** [comment]
Can you add some docs on how this works? A cursory scan over the code gives me no idea what I'm supposed to do. Is there any reason I can't just have this magically work, rather than passing some weird installation flag?

**Comment by s0undt3ch** [comment]
'pip --editable` runs setuptools `develop` command.
The setuptools develop command is used to use your local checkout as the "installation" source. Any edits that you do will automatically reflect on the next execution. We can't make the develop command behave the same as install since it hardcodes Salt's version. If you do some more commits, pull commits from the repo, tag the source after those files are generated, no changes are reflected, specially version changes.

**Comment by lorengordon** [comment]
Awesome, thanks!

**Comment by s0undt3ch** [comment]
@ryan-lane the last commit documents the environment variables and what they do.

**Comment by ryan-lane** [comment]
Awesome. Thanks!

**Comment by terminalmage** [comment]
:tada:

**Comment by cachedout** [comment]
@s0undt3ch Some merge conflicts, it looks like. Could you have a peek?

**Comment by s0undt3ch** [comment]
Rebased.

**Pull request merged**
