### PR TITLE
Adds enabled kwarg

### PR DESCRIPTION
**Pull request by brejoc**
## What does this PR do?
aptpkg is using the keyword argument 'disabled', while zypper and
yum are using enabled. This change allows to also pass 'disabled'
to mod_repo from the aptpkg module.

### Previous Behavior

`pkg.mod_repo` would only be used with `disabled=True`.

### New Behavior

`pkg.mod_repo` can now also be used with `enabled=False`.

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by brejoc** [comment]
@saltstack/team-core @cmcmarrow  Could someone please take a look here? Thanks!

**Comment by s0undt3ch** [comment]
There's 2 lint issues to address.
Thanks @brejoc!

**Comment by brejoc** [comment]
@s0undt3ch Sorry, totally missed that. I've pushed a change and solved a conflict. Hopefully it's looking better now.

**Comment by s0undt3ch** [comment]
No worries, though, the lint issues still exist.

**Comment by brejoc** [comment]
@s0undt3ch Ah, sorry. Seems like I overlooked that completely! :man_facepalming:

**Review by dwoz — APPROVED** [review]

**Pull request merged**
