### PR TITLE
Insert NAPALM modules into 2016.11

### PR DESCRIPTION
**Pull request by mirceaulinic**
### What does this PR do?

Currently there are just a few NAPALM modules into the Carbon branch, most are under ```develop```. Do you think would be possible to alleviate this into the next release? - the community is really waiting for these features.

Thanks!

### CODE REVIEW

**Comment by cachedout** [comment]
@mirceaulinic If you can get me a PR with what you want in it in the next few hours I will try my best to get it in. :]

**Comment by mirceaulinic** [comment]
Hi @cachedout thanks very much for pushing this into ```2016.11``` - much appreciated & sorry for late additions! I will keep an eye from now on the announcements to synchronise.

I have just open a new PR (the last one, I promise): https://github.com/saltstack/salt/pull/37764 to address some small details. I previously missed again some doc details, e.g.: https://docs.saltstack.com/en/develop/ref/modules/all/salt.modules.napalm_network.html#salt.modules.napalm_network.load_template

**Comment by cachedout** [comment]
@mirceaulinic We've tagged it already I'm afraid. I got this PR in but #37764 won't make it until the .1 release.

**Comment by mirceaulinic** [comment]
No worries @cachedout, it's fine if they'll be included in ```2016.11.1```! Should I close the PR and push the changes to ```develop```?

**Comment by cachedout** [comment]
Whew, glad to hear it! Sorry we missed it but we have to draw the line somewhere. :] Thanks for being so understanding.

Please keep this PR open. It's on the correct branch for being included in the .1 release that's forthcoming. Thanks!

**Comment by mirceaulinic** [comment]
Fantastic, thanks very much!

**Pull request merged**
