### PR TITLE
[2015.8] pip >= 7.0.0 and the removed mirrors, no_install and no_download support

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
@s0undt3ch, does this also fix #21845, possibly?

**Comment by s0undt3ch** [comment]
Nope, I did't take care of that issue in this PR.

**Comment by s0undt3ch** [comment]
I need to clean this up at another time.

**Comment by jfindlay** [comment]
ok, thanks @s0undt3ch.

**Comment by cachedout** [comment]
Closed per @s0undt3ch

**Pull request closed without merging**
