### PR TITLE
adding sysmod unit test case.

### PR DESCRIPTION
**Pull request by jayeshka**
Implemented sysmod unit test case.

### CODE REVIEW

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
@thatch45, this seems to be causing unrelated test failures similar to #22232, which was merged then reverted.  @rallytime and I are still trying to figure out why.

**Comment by rallytime** [comment]
These lines are overwriting the modules that are used by the entire test suite. 
```
sysmod.salt.state = Mockstate
sysmod.salt.runner = Mockrunner
sysmod.salt.loader = Mockloader()
```
I would say just use `@patch` or the `setUp` and `tearDown` functions.

**Comment by jfindlay** [comment]
Looks great, @jayeshka, thanks.

**Pull request merged**
