### PR TITLE
fix attempt to alter immutable DEFAULT_MASTER_OPTS

### PR DESCRIPTION
**Pull request by hwhesselink**
Dict salt.config.DEFAULT_MASTER_OPTS is a frozen immutable so the attempt to update it with "conf_path/master" causes an exception. This PR makes a copy and updates the copy.

### What issues does this PR fix or reference?
Fixes:

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by krionbsd** [comment]
@hwhesselink thank you for contribution! Could you please run `pre-commit -av` and re-commit the changes? Could you please add a test case for this change?

**Comment by hwhesselink** [comment]
Hi @krionbsd, a couple of questions: I'm not familiar with Jenkins but I installed pre-commit and ran "pre-commit run -av" in the cicd/jenkins directory and the 1-line diff is now +/- 200,000 lines so I suspect I'm not doing it right:-)  How am I supposed to do this?  Also, the error seems timing-related, I suspect the code in question only gets called when the new minion is slow, so I have no idea how to write a test for that.

**Comment by hwhesselink** [comment]
Hi @krionbsd, any update on this?

**Review by s0undt3ch — DISMISSED** [review]

**Review by krionbsd — APPROVED** [review]

**Comment by ari** [comment]
This problem appears to cause

```
[ERROR   ] There was a profile error: 'ImmutableDict' object has no attribute 'update'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/salt/cloud/cli.py", line 290, in run
    ret = mapper.run_profile(self.options.profile, self.config.get("names"))
  File "/usr/local/lib/python3.7/site-packages/salt/cloud/__init__.py", line 1407, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/local/lib/python3.7/site-packages/salt/cloud/__init__.py", line 1247, in create
    mopts_.update(
AttributeError: 'ImmutableDict' object has no attribute 'update'
```

and I cannot find a workaround to be able to use `salt-cloud create`

**Comment by ari** [comment]
Sorry, I see. It is just `sync_after_install` which is not supported. If this is not going to be fixed, can we just remove `sync_after_install` from the documentation to save other people wasting their time?

**Comment by dwoz** [comment]
This needs to be rebased.

**Review by dwoz — CHANGES_REQUESTED** [review]
This needs to be rebased.

**Comment by dwoz** [comment]
@ari Are you willing to write a regression test for this? If so, we can get it into the next release.

**Comment by ari** [comment]
I'm not the right person to work on this. My contribution here was nothing more than a suggestion to just remove the entire sync_after_install feature since its been broken for a couple of years, and no one seems to care too much. Just document the way to do this with the reactor.

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
