### PR TITLE
adding win_groupadd unit test case.

### PR DESCRIPTION
**Pull request by jayeshka**
Implemented win_groupadd_test unit test case.

### CODE REVIEW

**Comment by jayeshka** [comment]
Lot many changes on 2015.5 branch.
Will fix this first.

**Comment by jfindlay** [comment]
@jayeshka, while we can't mock modules using patch, unit tests that rely on external libraries should be written as if that library is available
```python
...
try:
    import win_lib
    HAS_WIN_LIB = True
except ImportError:
    HAS_WIN_LIB = False
...
@skipIf(not HAS_WIN_LIB, 'these tests can only run with win_lib installed')
class WinLibTestCase(TestCase):
...
```
Is it possible for you to rewrite this test in this case?  I think it should be mostly just removing the mock classes and adding the necessary imports.  Thanks.

**Comment by jayeshka** [comment]
Will fix this.
Thanks @jfindlay

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Pull request merged**
