### PR TITLE
[master] Moving tests/integration/modules/test_cmdmod.py to pytest, Gareth J Greenaway original author

### PR DESCRIPTION
**Pull request by dmurphy18**
### What does this PR do?
moving tests/integration/modules/test_cmdmod.py to pytest.

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by twangboy — DISMISSED** [review]

**Review by s0undt3ch — CHANGES_REQUESTED** [review]
The reviews asked on original PR apply here also.
https://github.com/saltstack/salt/pull/62322#pullrequestreview-1796119390

**Comment by dmurphy18** [comment]
@s0undt3ch  Thanks for that, picked up suggestions and running them now with the PR

**Review by s0undt3ch — DISMISSED** [review]

**Review by twangboy — DISMISSED** [review]

**Comment by dmurphy18** [comment]
Need https://github.com/saltstack/salt/pull/65775 pulled into master branch

**Review by twangboy — DISMISSED** [review]

**Comment by dmurphy18** [comment]
This PR should fix Gareth's o;d PR https://github.com/saltstack/salt/pull/62322

**Review by twangboy — DISMISSED** [review]

**Review by twangboy — APPROVED** [review]

**Pull request merged**
