### PR TITLE
parse pkgng output in quiet mode for >= 1.6.1

### LINKED ISSUE #27501: [FreeBSD] "pkg search" behavior changed since 1.5 series
`pkg search` starting from version 1.6.0 defaults to show comments what makes at least `pkg.latest` got broken:
```yaml
[...]
[INFO    ] Executing state pkg.latest for pkg
[INFO    ] Executing command 'pkg info -ao' in directory '/home/yz'
[INFO    ] Executing command 'pkg search pkg' in directory '/home/yz'
[DEBUG   ] Could not LazyLoad pkg.version_cmp
[DEBUG   ] Could not LazyLoad pkg.normalize_name
[INFO    ] Executing command 'pkg install  -y pkg' in directory '/home/yz'
[INFO    ] Executing command 'pkg info -ao' in directory '/home/yz'
[ERROR   ] Package pkg failed to update.
[INFO    ] Completed state [pkg] at time 13:30:27.804182
[DEBUG   ] File /var/cache/salt/minion/accumulator/34577839904 does not exist, no need to cleanup.
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/usr/local/etc/salt/pki/minion', 'dt-bal02', 'tcp://192.168.90.19:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/usr/local/etc/salt/pki/minion', 'dt-bal02', 'tcp://192.168.90.19:4506')
[DEBUG   ] LazyLoaded highstate.output
local:
----------
          ID: pkg
    Function: pkg.latest
      Result: False
     Comment: Package pkg failed to update.
     Started: 13:30:26.840506
    Duration: 963.676 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 963.676 ms
```
Please, consider checking `pkg` version and adding `-q` if version >= 1.6.0 (`pkg search -q pkg_name`) and please help me fix this until release, as I've got a bunch of my `sls`'s broken =( Would it be sufficient to just add `-q` into `cmd` definition in function `latest_version` in `python2.7/site-packages/salt/modules/pkgng.py`?

### PR DESCRIPTION
**Pull request by jfindlay**
Fixes #27501.

@yermulnik, please review.

### CODE REVIEW

**Comment by yermulnik** [comment]
Version to compare with **should** be `1.6.0` (`pkg search` default behavior changed in `1.6.0`)
Everything else seems to be fine.
Thanx

**Comment by jfindlay** [comment]
@yermulnik, done, thanks.

**Comment by yermulnik** [comment]
thanx!

**Comment by yermulnik** [comment]
Hi there!
When it's going to be committed into release?
I've upgraded to 2015.8.1 on my FreeBSD today, but it has no patch for this issue =(

**Comment by basepi** [comment]
I think this came in just after we tagged 2015.8.1 for internal testing. It should be in 2015.8.2. Sorry for the inconvenience.

**Pull request merged**
