### PR TITLE
opkg.py: make owner fuction return value, instead of iterator

### PR DESCRIPTION
**Pull request by adelcast**
Signed-off-by: Alejandro del Castillo <alejandro.delcastillo@ni.com>

### Tests written?

/No

### Commits signed with GPG?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by adelcast** [comment]
hi @rallytime, is there anything else I need to do to move this PR forward? (rebase, etc)

**Comment by rallytime** [comment]
Hi @adelcast - apologies for the delay here. We've had a lot of PRs going in lately and I missed this one. I'm going to ask @terminalmage to review this since he was in this code recently. Thanks!

**Review by terminalmage — APPROVED** [review]
@rallytime this needs a backport to 2016.11 and should be added to all bugfix releases.

**Comment by rallytime** [comment]
We've already tagged 2016.11.9, so it won't be in that release. But I can get it in for 2016.11.10/2017.7.3. Thanks @adelcast!

**Pull request merged**
