### PR TITLE
Fix beacons telegram attribute error message

### PR DESCRIPTION
**Pull request by MedourMehdi**
### What does this PR do?
Fix error message "AttributeError: 'NoneType' object has no attribute 'chat'"
### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/49945

### Tests written?
No

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by gtmanfred — CHANGES_REQUESTED** [review]
Can you rebase this to remove the extra commits?

Thanks,
Daniel

**Review by terminalmage — CHANGES_REQUESTED** [review]
It looks like something went wrong here, it appears that you opened this pull request against a different branch from which you branched to make your changes. Can you fix this up so that only your commits are part of the PR?

**Comment by MedourMehdi** [comment]
Hi,

Yes I've followed 2018.3.3 and make my PR on develop it seems.

Can you cancel the PR then I make a new PR on develop?

Many thanks

**Comment by DmitryKuzmenko** [comment]
@MedourMehdi you can fix it here. Press the `Edit` button right on PR name and choose another target branch under the PR name.

**Pull request closed without merging**
