### PR TITLE
RFC: Update salt codebase to use alternately-named pycrypto and tornado

### PR DESCRIPTION
**Pull request by terminalmage**
In order to keep the repo.saltstack.com yum repos from forcing users to upgrade
python-crypto and python-tornado, salt-pack has been updated with packages
which patch the pycrypto and tornado source code to rename them and allow our
repos to provide an RPM that can be installed alongside the one from EPEL, and
used in place of them.

The renamed pycrypto imports as `Crypto_salt` instead of `Crypto`, while
the renamed tornado imports as `tornado_salt` instead of `tornado`.

This pull request makes the needed changes to the Salt codebase to look for
these alternately-named Python modules first, and fall back to plain-old
`Crypto` or `tornado` when they aren't available.

Pycrypto is pretty easy, the parts we use are classes imported from a module,
so we can do a `from Crypto_salt.Submodule import Someclass`, and in the
event of an ImportError fall back to `from Crypto.Submodule import Someclass`.

Tornado is a bit more complex. Most of tornado's functionality is in submodules
underneath the tornado namespace, and are typicall loaded as
`tornado.modname`. This requires each of these to be loaded under a common
name (i.e. `tornado_salt.netutil` or `tornado.netutil` would be loaded as
`tornado_netutil`), and then all references to `tornado.netutil` in that
file must also be updated to `tornado_netutil`.

References:
- [python-crypto-salt build files](https://github.com/saltstack/salt-pack/tree/master/file_roots/pkg/python-crypto-salt/2_6_1)
- [python-tornado-salt build files](https://github.com/saltstack/salt-pack/tree/master/file_roots/pkg/python-tornado-salt/4_2_1)

### CODE REVIEW

**Comment by terminalmage** [comment]
Just pushed a few fixes for syntax and other errors.

**Comment by cachedout** [comment]
I get where you're going here, but I'm not a huge fan of this. Effectively, this means that we'll have to code by convention for every use of these libraries, duplicating the same try/except technique. I'm wondering about the possibility of creating a factory-esque wrapper class that can handle this? So, we'd just `import salt.tornado` and then let a factory decide which version of the library to deliver to us. Thoughts?

cc: @jacksontj @thatch45

**Comment by thatch45** [comment]
I do like that approach much more @cachedout , although we still have the issue of tornado being used in zeromq, can we cross the streams like that?

**Comment by cachedout** [comment]
@thatch45 Pretty good question. It's worth fiddling around a little bit with but if we get into too much magic, we should reconsider...

**Comment by thatch45** [comment]
I think that moreso, we are treading on the territory of making all encompassing packages, where we bundle python itself for older platforms like RHEL instead of dealing with the out of date python deps, or we bundle all python deps and prepend a python path

**Comment by thatch45** [comment]
It is just becoming far too difficult to maintain compatibility with such old deps in these enterprise releases, and other distros like Suse will allow for at least somewhat clean updates of python deps

**Comment by cachedout** [comment]
Additional changes coming, per @terminalmage

**Comment by terminalmage** [comment]
I didn't catch the chatter here before @cachedout and I talked. I'm all for @cachedout's solution here. It can be applied to pyzmq as well once I've patched it to load the renamed tornado. I might end up just closing this and opening a new PR with the updated approach.

**Comment by cachedout** [comment]
@terminalmage Unless this is on the really short-term task list I'd rather close this and re-open a new one when we're ready. The PR queue is getting a little hard to manage.

**Comment by cachedout** [comment]
Closing pending rewrite, per @terminalmage

**Comment by jacksontj** [comment]
@thatch45 If the intent here is to try and bundle in all deps (as you mentioned python potentially) maybe we want to try and tackle that with something other than embedding it into salt itself? There are solutions to this (virtualenv, pex, etc.) which can solve the problem at build time instead of in the source tree.

**Comment by terminalmage** [comment]
He wasn't talking about including the deps in the source tree. What @thatch45 was talking about is something akin to what we do for Windows, in which we bundle Python 2.7 along with all needed deps.

**Comment by jacksontj** [comment]
I see, the original PR does embed the deps in the source tree though ;) So the intent here is to do what then? From the last comments from @cachedout and @terminalmage it seems like the plan is to still embed the deps?

**Comment by thatch45** [comment]
What is the redhat doctrine on making a rpm that deploys an app in a virtualenv?

**Comment by jacksontj** [comment]
TBH I'm not sure. I can't think of (nor find with some quick google-ing) another project that does deploy with virtualenvs in RPMs. From the python side I would imagine you'd be fine, but once you start getting into modules with C extensions it'll get a little bit more complicated. If we want to investigate, we'll probably want to ping someone in redhat to get some feedback :)

**Pull request closed without merging**
