### PR TITLE
 Merge 2015.8 into develop

### PR DESCRIPTION
**Pull request by rallytime**

### CODE REVIEW

**Comment by cachedout** [comment]
Do you have a list of merge conflicts on this one? These lint errors are pretty worrying.

**Comment by rallytime** [comment]
I'll have to take another look.

**Comment by rallytime** [comment]
The conflicts are in the commit message at the bottom. All of the files that have pylint errors had conflicts.

**Comment by rallytime** [comment]
Replaced by #30369

**Pull request closed without merging**
