### PR TITLE
[Don't merge] Inject module __grains__ data into opts before create a state

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
Thus state will use actual grains data.
Related to #24073

### CODE REVIEW

**Comment by rallytime** [comment]
@DmitryKuzmenko I think the `unit.modules.state_test.StateTestCase.test_pkg` is a related failure here. It's probably just because the `__grains__` object isn't mocked in the test file. Can you take a look at that? I can help out if you get stuck. Thanks!

**Comment by DmitryKuzmenko** [comment]
@rallytime sure. Thank you for ping me!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by DmitryKuzmenko** [comment]
I have a better, but more risky solution. Please don't merge this fix until I'll check another way.

**Comment by DmitryKuzmenko** [comment]
There is a better solution: https://github.com/saltstack/salt/pull/24451. Closing this.

**Pull request closed without merging**
