### PR TITLE
fixed the venv docs once again

### PR DESCRIPTION
**Pull request by srkunze**

### CODE REVIEW

**Comment by jfindlay** [comment]
@srkunze, is this intended to fix #27858?

**Comment by srkunze** [comment]
No, just three clean up commits. https://github.com/saltstack/salt/issues/27858 has its roots deep in the state system, I think.

**Comment by cachedout** [comment]
Thanks @srkunze

**Comment by rallytime** [comment]
This change only affects code on the develop branch, so I won't be back-porting this.

**Comment by srkunze** [comment]
@rallytime Just to get it right, what exactly do you mean backporting?

**Comment by rallytime** [comment]
Oh, when bug fixes are made against the develop branch, but they might actually be applicable to an earlier branch, we throw the "Bugfix - back-port" label on the PR. Then I will go through and apply the change to the earlier branch. Once that's done, I will link the PRs, remove the "Bugfix - back-port" label, and apply the "Bugfix - [Done] back-ported" label so we can keep track of what does and doesn't need to be backported.

In this case, I just removed the "Bugfix - back-port" label and left a comment explaining why I didn't do the rest of the process. Make sense?

There's some docs on those labels [here](https://docs.saltstack.com/en/latest/topics/development/labels.html#status) in case what I said doesn't quite make sense.

**Comment by srkunze** [comment]
There is a doc page about it? Great! I finally know what P1 to P4 means. :D Will redirect this to some coworkers as they were wondering as well.

In any case, what you said make perfectly sense. Thanks again.

**Comment by rallytime** [comment]
There is indeed! But, as you've pointed out in other issues, docs are hard to find unless you know what you're looking for. :)

**Pull request merged**
