### PR TITLE
Make sys.argspec handle functions with annotations

### LINKED ISSUE #48735: getfullargspec and annotations
### Description of Issue/Question
I've got a strange error when I use type hinting for my salt module:

```
  The minion function caused an exception: Traceback (most recent call last):  File "/opt/alt/python35/lib/python3.5/site-packages/salt/minion.py", line 1589, in _thread_return
    data)
  File "/opt/alt/python35/lib/python3.5/site-packages/salt/minion.py", line 323, in load_args_and_kwargs
    argspec = salt.utils.args.get_function_argspec(func)
  File "/opt/alt/python35/lib/python3.5/site-packages/salt/utils/args.py", line 265, in get_function_argspec
    aspec = _getargspec(func)  # pylint: disable=redefined-variable-type
  File "/opt/alt/python35/lib/python3.5/site-packages/salt/utils/args.py", line 225, in _getargspec
    raise ValueError(\'Function has keyword-only arguments or annotations\'
   ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them
   
'}}
```

The problem is that you check function annotations and raise an error when it has some annotations:

`site-packages/salt/utils/args.py`
```
   def _getargspec(func):
        '''
        Python 3 wrapper for inspect.getargsspec

        inspect.getargsspec is deprecated and will be removed in Python 3.6.
        '''
        args, varargs, varkw, defaults, kwonlyargs, _, ann = \
            inspect.getfullargspec(func)  # pylint: disable=no-member
        if kwonlyargs or ann:
            raise ValueError('Function has keyword-only arguments or annotations'
                             ', use getfullargspec() API which can support them')
        return _ArgSpec(args, varargs, varkw, defaults)
```

The code looks strange! There is a warning about `getargsspec` but you don't use `getargsspec`. There is exception message that give you advice to use `getfullargspec`, but you already use `getfullargspec`.

And I still don't know why do you raise an error if the function has an annotations. What is the reason?

### Versions Report
salt-minion 2018.3.0 (Oxygen)

### PR DESCRIPTION
**Pull request by msteed**
### What does this PR do?
Makes sys.argspec not die on functions that use annotations

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/48735

### Previous Behavior
Calling `sys.argspec` on a salt function that used annotations failed with
> `ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them`

### New Behavior
Calling `sys.argspec` on a salt function with annotations works (annotations are ignored)

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by OrangeDog** [comment]
Build log is truncated, so no idea what's wrong with those tests.

I assume they're just broken like usual?

**Comment by msteed** [comment]
@xeacott - can I get a review please?

**Comment by msteed** [comment]
@xeacott - I already added a test to cover the previously failing case. Is there something else I should be testing?

I know lint has passed on this PR before. I'll update from `master` and let it run again.

**Comment by xeacott** [comment]
@msteed Oh thought that test file was inside pytest. Would you be able to covert it? Previously that's been an ask for smaller files (to convert an older test file to pytest) from the core team.

**Comment by msteed** [comment]
Converted :heavy_check_mark:

**Comment by xeacott** [comment]
re-run full all

**Comment by msteed** [comment]
Failing checks seem unrelated to these changes (failing to create VMs)

**Review by s0undt3ch — APPROVED** [review]

**Comment by dmurphy18** [comment]
@msteed We are all waiting for the amazon and windows tests to work, SRE looking into it

**Review by twangboy — APPROVED** [review]

**Pull request merged**
