### PR TITLE
Proposed update to resolve saltstack/salt#52538

### PR DESCRIPTION
**Pull request by que5o**
Simply remove reading the target csv file in binary format

### What does this PR do?
resolves issue with csvpillar.py attempting to read csv file in binary format instead of text

### What issues does this PR fix or reference?
saltstack/salt#52538

### Previous Behavior
Reads target csv file from disk in binary format

### New Behavior
Reads target csv file in text format

### Tests written?
No

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by waynew** [comment]
Hi @que5o thanks for the PR!

Pretty sure this looks good - is this issue just in develop, or does it also exist against 2018? If so, if you rebase & retarget your PR against 2018.3, we will merge it forward to 2019.2 & develop.

Also, would it be possible to write some tests for this?

**Comment by que5o** [comment]
Yes looks like this exists in 2018.3 branch. I'll look into how to re-base the PR. I'll also look into adding a some unit testing

**Comment by que5o** [comment]
I f****d this all up. Since it's a one letter change, I'm going to redo the pull request from scratch. The original PR gets to live on to display my shame.

**Comment by waynew** [comment]
No harm no foul ;)

When I first started with Git I don't even *know* what I did to completely hork up a repo I was working in. Someone walked me through, step by step, to rewrite my history and make things better.

**Comment by que5o** [comment]
I have submitted a new PR to replace this mess:
https://github.com/saltstack/salt/pull/52747

**Pull request closed without merging**
