### PR TITLE
grains: Use platform.freedesktop_os_release

### PR DESCRIPTION
**Pull request by bdrung**
Python 3.10 introduced `platform.freedesktop_os_release` which does the same as `_parse_os_release("/etc/os-release", "/usr/lib/os-release")`.

The parsing of the os-release file is very similar and differs only slightly in the used regular expressions. In contrast to
`_parse_os_release`, `platform.freedesktop_os_release` caches the result of the parsed os-release file.

Use `platform.freedesktop_os_release` when available. When salt drops the support for Python < 3.10 (some time in the distant future), `_parse_os_release` can be removed.

Also update the OS grains test cases to use /etc/os-release data from still supported Debian/Ubuntu releases.

This merge request contains the commits from the merge request https://github.com/saltstack/salt/pull/61597. So I recommend to review and merge https://github.com/saltstack/salt/pull/61597 first.

### CODE REVIEW

**Comment by bdrung** [comment]
Updated the code so that `_parse_os_release` throws an `OSError` if no os-release file can be read.

**Review by dmurphy18 — COMMENTED** [review]
Looks good, need to get all tests passing, updated against branch and hopefully Windows VM and Apple VM will behave 
Ready to approve once all the tests pass

**Review by dmurphy18 — CHANGES_REQUESTED** [review]
Need to address Windows issues, no /etc/os-release on Windows
Restarted MacOS test, but nest check not same issue as on Windows

**Comment by bdrung** [comment]
`freedesktop_os_release` shouldn't be called on Windows/Mac. I changed this function to a private function named `_freedesktop_os_release`. Let's see if that solves the test failure.

**Comment by bdrung** [comment]
Making `freedesktop_os_release` private solved it. All test runs pass except for `pr-windows-2016-x64-py3-pytest` that has four failing tests with `FactoryNotStarted`, but that looks unrelated to my merge request.

**Review by dmurphy18 — APPROVED** [review]

**Pull request merged**
