### PR TITLE
aptpkg.py support KDE neon distro

### PR DESCRIPTION
**Pull request by mhlavac**
### What does this PR do?
Fixes saltstack on KDE neon

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/32198

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

KDE Neon just released LTS version based on LTS Ubuntu 16.04, unfortunately it's release as "neon" dist.

I get error while installing packages.

Salt state:
```
lame:
  pkg.latest
```

```
          ID: lame
    Function: pkg.latest
      Result: False
     Comment: State 'pkg.latest' was not found in SLS 'lame'
              Reason: 'pkg' __virtual__ returned False                                                                                                                                                                                                                                                                               
     Changes:   
```

```
$ salt-call --versions-report
Salt Version:
           Salt: 2016.11.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: neon 16.04 xenial
        machine: x86_64
        release: 4.4.0-53-generic
         system: Linux
        version: neon 16.04 xenial
```

### CODE REVIEW

**Comment by mhlavac** [comment]
@cachedout thanks for merging this so fast. Would it make sense to make "mapping" to Debian at some point? There are more and more distros like this and it might make sense to do these changes just in one place

**Comment by cachedout** [comment]
This sort of mapping happens in the core grains library under `os_family`. We could do it there, if it makes sense.

**Comment by mhlavac** [comment]
@cachedout can you guide me? I am new to this. Even though I am using saltstack for some time I didn't touch the code running behind it yet

**Comment by cachedout** [comment]
You'd want to have a look at salt/grains/core.py. In there is a function that specifies which distros are mapped to which `os_family` grains. You'd want to modify it is that when `salt-call --local grains.get os_family` is run on your machine, `Debian` is returned.

**Pull request merged**
