### PR TITLE
introduce recurse_list pillar_source_merging_strategy

### PR DESCRIPTION
**Pull request by dkiser**
First attempt at #27890

### CODE REVIEW

**Comment by cachedout** [comment]
This looks excellent. Well done! Thank you!

**Comment by dkiser** [comment]
@cachedout - i didn't see a unit/integration test for the pillar merge strategies, I wanted to get that test in before you merged it in, thoughts?

**Comment by jfindlay** [comment]
@dkiser, you are very welcome to create another pull request for tests.  Tests are always good.

**Comment by basepi** [comment]
Backport to 2015.8, please.

**Comment by rallytime** [comment]
@basepi Done!

**Comment by basepi** [comment]
Thanks!

**Pull request merged**
