### PR TITLE
E-Auth refactoring

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
### What does this PR do?
* Moves most of the auth-related code into `salt.auth`
* Adds an ability to use different modules for authentication and authorization.

### What issues does this PR fix or reference?
Fixes https://github.com/saltstack/zh/issues/864
Relates to #34167

### Tests written?
Just updated the existing.

### CODE REVIEW

**Comment by DmitryKuzmenko** [comment]
I need to add release notes and I want to hear review comments.

**Comment by DmitryKuzmenko** [comment]
Added RN, waiting for review.

**Review by thatch45 — APPROVED** [review]
This is a monster, but it looks good to me

**Comment by DmitryKuzmenko** [comment]
@thatch45 I've expected to get it looking much simpler but there are different auth logic in different places (master vs masterapi; publish vs runner vs wheel). So I've tried to make it as simple as possible. But I'm open for discussion. =)

**Pull request merged**
