### PR TITLE
Add __opts__ and __utils__ to SDB

### PR DESCRIPTION
**Pull request by techhat**
### What issues does this PR fix or reference?
Ref #39143.

### Tests written?
No.

### CODE REVIEW

**Comment by carlpett** [comment]
Great! Should any of the other dunders be thrown in there at the same time? `__salt__` comes to mind, for example, and what about `__pillar__`? Maybe `__pillar__` could introduce some weird circular dependencies, though (a minion with a pillar `some_pillar: {{ salt['sdb.get']('mysdb://something') }}` for example).

**Comment by techhat** [comment]
@carlpett I hear what you're saying, but since SDB is master/minion agnostic, and things like `__salt__`, `__pillar__`, etc are minion-specific, I would tend to avoid adding those things here.

**Comment by carlpett** [comment]
@techhat Ah, I see! Well then, in that case I'm very happy with this :)

**Review by cachedout — COMMENTED** [review]
Calling the loader to get utils on every gettr/settr operation is going to be very slow. Would it be possible to find a way to instead store utils somewhere up the stack and pass them in when needed?

**Comment by techhat** [comment]
@cachedout I'll see if I can find a less expensive way to get that in there.

**Comment by cachedout** [comment]
@techhat Thank you very much. Please let me know if I can be of assistance.

**Comment by techhat** [comment]
@cachedout what do you think about this new commit?

**Review by cachedout — APPROVED** [review]
Perfect!

**Pull request merged**
