### PR TITLE
Added new options for RH interface configuration

### PR DESCRIPTION
**Pull request by t0fik**
1. Added new option for RH interface configuration, like PREFIX which is recomended instead NETMASK config option
2. Removal of requirements/cloud.txt reference from  MANIFEST.in and pkg/smartos/esky/requirements.txt

### CODE REVIEW

**Comment by jfindlay** [comment]
@t0fik, thanks for the pull request.  Next time remember to put unrelated changes into separate pull requests, thanks.

**Comment by t0fik** [comment]
Ok, I will remember about that.

**Comment by t0fik** [comment]
I'll open cleaned up pull request.

**Comment by jfindlay** [comment]
@t0fik, thanks for doing that.

**Pull request closed without merging**
