### PR TITLE
Added event_return() support to postgres_local_cache

### PR DESCRIPTION
**Pull request by MadsRC**
Patched postgres_local_cache to support event_return() as I had a need to use postgres both as master cache and for storing Salt's events.

Tested on my CentOS 7 servers, and has run stable for nearly a week now.

### CODE REVIEW

**Comment by MadsRC** [comment]
I'll have a look at the failed lint test and push it when I get home

**Comment by cachedout** [comment]
@MadsRC Thank you! Please let me know when this is ready to go.

**Comment by MadsRC** [comment]
I've fixed the PEP8 related warning and the lint check should complete (Mine sure did, forgot to install PEP8 on the first run).

I've beene looking at the other Postgres returner and was thinking of replacing it entirely with this one? Where do I find a place to discuss that? Here, IRC or mailinglist?

**Comment by cachedout** [comment]
@MadsRC Probably best to open a Github issue with your proposal and then announce it on the mailing list. Take a look at the git history for that runner and you'll likely find a few people you'll want to tag specifically for a discussion. Let me know if I can help. :]

**Comment by cachedout** [comment]
@MadsRC Did you mean to remove that other returner in this PR? The additions look find but I'm confused about the removal.

**Comment by MadsRC** [comment]
@cachedout - Yeah, I meant to remove the postgres.py returner and rename postgres_local_cache.py.

From what I see, they serve the same purpose. The only difference is that  one returns a lot more data to the database (Which in my opinion is great) and that the other doesn't have a maintainer.

But there could be a reason for as to why there is 2 postgres returners. I'll look through the Git history and start an issue later.

**Comment by MadsRC** [comment]
@cachedout - I readded the postgres.py returner. I get why you're confused about the removal, as that was not intentional. That shouldn't have been in this commit. I readded it, and fixed some linting issues.

**Comment by cachedout** [comment]
@MadsRC Cool. Thanks!

**Comment by cachedout** [comment]
Merged. Thanks, @MadsRC

**Pull request merged**
