### PR TITLE
Add jid to return from runner/wheel funcs executed within orchestration

### PR DESCRIPTION
**Pull request by terminalmage**

### CODE REVIEW

**Comment by terminalmage** [comment]
I kinda feel like it might be a better idea to write a cmd func in the RunnerClient class and then invoke the parent class' cmd func (as we do in the WheelClient). This would make [this warning](https://github.com/saltstack/salt/pull/34977/files#diff-f039891ad8c749233c14fce7bdf4fc65R22) unnecessary and the code less likely to regress

**Comment by cachedout** [comment]
Oh, I agree with you 100%. That's the way to go.

**Comment by terminalmage** [comment]
OK, I've added the func to the Runnerclient in 1e0c533.

**Comment by cachedout** [comment]
A test failure here: https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/3811/testReport/junit/unit.states.saltmod_test/SaltmodTestCase/test_wheel/

**Comment by terminalmage** [comment]
Looks like ``out`` just needs to be mocked in that test, I'll take care of that today.

**Comment by cachedout** [comment]
Here as well, just FYI: https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/3811/testReport/junit/unit.states.saltmod_test/SaltmodTestCase/test_runner/

**Comment by terminalmage** [comment]
Thanks!

**Comment by terminalmage** [comment]
Unit tests have been updated to change the mocking to match the new behavior of the RunnerClient and WheelClient.

**Pull request merged**
