### PR TITLE
fix_Indefinitely_code

### PR DESCRIPTION
**Pull request by cmcmarrow**
### What does this PR do?
fix Indefinitely code

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/55273

### Tests written?
yes

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by xeacott — APPROVED** [review]

**Comment by UnknownGnome** [comment]
Sweet!

**Review by dwoz — CHANGES_REQUESTED** [review]
Bug fixes need regression tests.

**Comment by cmcmarrow** [comment]
re-run full amazon2

**Comment by cmcmarrow** [comment]
re-run full amazon2

**Comment by cmcmarrow** [comment]
re-run full amazon2

**Comment by cmcmarrow** [comment]
re-run full amazon1

**Comment by cmcmarrow** [comment]
re-run full windows

**Comment by cmcmarrow** [comment]
re-run full windows

**Comment by cmcmarrow** [comment]
re-run full windows

**Comment by cmcmarrow** [comment]
re-run full windows

**Review by dwoz — APPROVED** [review]

**Pull request merged**
