### PR TITLE
Index new modules introduced in Nitrogen

### PR DESCRIPTION
**Pull request by mirceaulinic**
### What does this PR do?

- Index new modules introduced in Nitrogen.
- Fix indentation for some lists.
- Remove the reference to the `profile` outputter, as it's not included in the Nitrogen branch.
- Add `versionadded` to a new function under the `mine` runner.
- Notes regarding other new features.

### CODE REVIEW

**Review by terminalmage — APPROVED** [review]
:clap:

**Review by rallytime — APPROVED** [review]
👍

**Comment by mirceaulinic** [comment]
Meanwhile I pushed this commit https://github.com/saltstack/salt/pull/41607/commits/bba8c278732cc01c712a67916e4a631c46992055 to have direct referenced to Jinja filter (as we have for opts, for example). But I think we need to define the `jinja_ref` directive somewhere... and I don't know exactly where.

**Comment by garethgreenaway** [comment]
Go Go Jenkins!

**Review by cachedout — APPROVED** [review]

**Comment by whiteinge** [comment]
@mirceaulinic sorry for the slow reply, I'm a tad backlogged this week (slowly catching up though).

This should add the full list of filters to the main index:

```py
diff --git a/doc/_ext/saltdomain.py b/doc/_ext/saltdomain.py
index bc0dcbb81e..c1f73ddc39 100644
--- a/doc/_ext/saltdomain.py
+++ b/doc/_ext/saltdomain.py
@@ -309,3 +309,5 @@ def setup(app):
             indextemplate="pair: %s; conf/proxy")
     app.add_crossref_type(directivename="conf_log", rolename="conf_log",
             indextemplate="pair: %s; conf/logging")
+    app.add_crossref_type(directivename="jinja_ref", rolename="jinja_ref",
+            indextemplate="pair: %s; jinja filters")
```

**Comment by mirceaulinic** [comment]
Thanks @whiteinge. I will add it next week.

**Pull request merged**
