### PR TITLE
Always transfer bytes from fileserver roots

### PR DESCRIPTION
**Pull request by dwoz**
### What does this PR do?

Fixes a state test on windows (py3) where utf-8 data was getting
improperly decoded before fileserver sends the data to a client.

### What issues does this PR fix or reference?

https://jenkinsci.saltstack.com/job/2018.3/view/Python3/job/salt-windows-2016-py3/100/testReport/junit/integration.modules.test_state/StateModuleTest/test_state_sls_unicode_characters/

### Tests written?

Yes - Adding new test to show command output nuances on windows.

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by twangboy — APPROVED** [review]

**Comment by dwoz** [comment]
re-run py

**Comment by dwoz** [comment]
re-run py

**Comment by dwoz** [comment]
re-run py

**Comment by dwoz** [comment]
@terminalmage ping. :)

**Review by terminalmage — APPROVED** [review]
This is good to merge pending test results and @dwoz ensuring that my contributions did not break tests on Windows.

**Review by twangboy — APPROVED** [review]

**Pull request merged**
