### PR TITLE
Fix typo in s3fs fix

### PR DESCRIPTION
**Pull request by joehoyle**
Sorry about that!

### CODE REVIEW

**Comment by jfindlay** [comment]
Thanks, @joehoyle, next time you'll only need to submit the pull request against the older branch, http://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

**Comment by rallytime** [comment]
Thanks @joehoyle! @jfindlay is correct is saying that since you submitted the fix to 2014.7, that fix will make it's way through the branches as we merge them forward. (We merge 2014.7 --> 2015.2, and then 2015.2 --> develop on a daily basis.) But, since this fix is the same, we can merge both for now. Just for your future knowledge.

Does that make sense as to why you don't need to submit both fixes? We're happy to answer any questions. Thanks!

**Comment by joehoyle** [comment]
@rallytime yup, sorry about that! Getting there one PR at a time! :D

**Comment by rallytime** [comment]
No worries at all! Thanks again for contributing!

**Pull request merged**
