### PR TITLE
Skip test requiring crypto when none available

### PR DESCRIPTION
**Pull request by Akm0d**
### What does this PR do?
Skips tests if crypto isn't set up

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/52721

### Previous Behavior
Remove this section if not relevant

Yes

### CODE REVIEW

**Review by twangboy — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Comment by Akm0d** [comment]
re-run

**Comment by Akm0d** [comment]
re-run full all

**Comment by Akm0d** [comment]
re-run

**Comment by dwoz** [comment]
re-run centos

**Comment by Akm0d** [comment]
re-run centos-7

**Comment by Akm0d** [comment]
re-run centos-7

**Comment by Akm0d** [comment]
re-run centos-7

**Comment by Akm0d** [comment]
re-run full all

**Comment by Akm0d** [comment]
re-run centos-7

**Review by s0undt3ch — APPROVED** [review]

**Comment by s0undt3ch** [comment]
There seems to be some linting to be fixed.

**Pull request merged**
