### PR TITLE
Fix /jobs endpoint's return

### PR DESCRIPTION
**Pull request by jacksontj**
The /jobs endpoint apparently has a very odd return type.

This fixes an issue found in tinyclues/saltpad#40

### CODE REVIEW

**Comment by rallytime** [comment]
Thanks @jacksontj!

We had some trouble with Jenkins today, so that's why the Ubuntu and CentOS tests look unhappy right now, but I think it's cleared up. However, it looks like you've got a pylint error here: 

https://jenkins.saltstack.com/job/salt-pr-lint-n/4464/violations/

**Comment by jacksontj** [comment]
There's the pylint fix.

**Comment by jfindlay** [comment]
@jacksontj, we've been having problems with the tests that have failed on this pull request.  They fail intermittently.  Do you have any ideas?  This happens on the 2015.2 and develop branches.  I haven't had time to track this down yet.

**Comment by jacksontj** [comment]
@jfindlay I dug into this a bit this morning and it seems to be a bit of a mess. There as a commit (0d6691a) which attempted to consolidate some job storage logic, but it ended up calling save_load once per minion return. In addition to being wasteful, this also means its *really* easy to have multiple writers on the file-- which causes the errors you are seeing. I'm working on cleaning up that patch, after that's done I'll see about switching everything over to atomics or something to avoid this issue if someone adds it back in :/

**Comment by jacksontj** [comment]
There we go, that switches it over to atomics, which should make the issue not repeat-- although we should probably come up with some way of detecting this and logging a warning or something ;)

**Comment by jfindlay** [comment]
@jacksontj, nice, thanks.

**Comment by jfindlay** [comment]
It seems that the merge forward has conflicted this pull request.

**Comment by jfindlay** [comment]
@jacksontj, there seems to be a conflict here with #22855.  A function, `get_retcode` was added to salt/utils/job.py, whereas this pull request removes that file but without updating the `get_retcode` related code.

**Comment by jacksontj** [comment]
That should fix our conflict :)

**Comment by jacksontj** [comment]
I can't reproduce the jobs failure locally, and the other one *sounds* unrelated.

**Comment by jfindlay** [comment]
I am working on fixing the `integration.wheel.client.WheelModuleTest.test_cmd_async` test.

**Comment by jacksontj** [comment]
Cool, are you able to repro the other failure locally? I can't :/

**Comment by jfindlay** [comment]
@jacksontj, not yet, but I'll keep trying.

**Comment by jfindlay** [comment]
@jacksontj, the wheel test failure is a little beyond my current knowledge level.  Somehow opts is getting (re)set as an ImmutableDict which prevents `opts['grains']` from getting defined.

**Comment by thatch45** [comment]
This wheel issue is very odd, we don't ever make the opts dict immutable....

**Comment by thatch45** [comment]
In the integration test suite @s0undt3ch added freezing the opts dict for the running daemons. So this issue is localized to the test suite, maybe @s0undt3ch will have an idea on how to handle it

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
@jacksontj, we've decided today to delete the 2015.2 branch and create a 2015.5 branch since we're going to release next week.  I haven't done any work on this beyond the other pull request I created.

**Pull request closed without merging**
