### PR TITLE
Shutdown multiprocessing logging before forkink and restart it once forked

### LINKED ISSUE #26672: salt-minion and salt-master displaying traceback when started
When starting/restarting salt-master/salt-minion on latest develop branch, it displays a traceback and gets hung. After a KeyBoard Interrupt, it displays ``OK``. 

```
root@nitin-salt-develop:~/salt$ service salt-master stop
Stopping salt-master daemon:                               [  OK  ]
root@nitin-salt-develop:~/salt$ service salt-master start
Starting salt-master daemon: Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/multiprocessing/util.py", line 269, in _exit_function
    p.join()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 117, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/multiprocessing/util.py", line 269, in _exit_function
    p.join()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 117, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/multiprocessing/util.py", line 269, in _exit_function
    p.join()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 119, in join
    res = self._popen.wait(timeout)
  File "/usr/lib64/python2.6/multiprocessing/forking.py", line 122, in wait
    return self.poll(0)
  File "/usr/lib64/python2.6/multiprocessing/forking.py", line 107, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Error in sys.exitfunc:
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/log/setup.py", line 906, in __global_logging_exception_handler
    shutdown_multiprocessing_logging_listener()
  File "/usr/lib/python2.6/site-packages/salt/log/setup.py", line 800, in shutdown_multiprocessing_logging_listener
    __MP_LOGGING_QUEUE_PROCESS.terminate()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 111, in terminate
    self._popen.terminate()
  File "/usr/lib64/python2.6/multiprocessing/forking.py", line 139, in terminate
    os.kill(self.pid, signal.SIGTERM)
OSError: [Errno 3] No such process

Original exception was:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/multiprocessing/util.py", line 269, in _exit_function
    p.join()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 119, in join
    res = self._popen.wait(timeout)
  File "/usr/lib64/python2.6/multiprocessing/forking.py", line 122, in wait
    return self.poll(0)
  File "/usr/lib64/python2.6/multiprocessing/forking.py", line 107, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
                                                           [  OK  ]
```

### PR DESCRIPTION
**Pull request by s0undt3ch**
Fixes #26672

### CODE REVIEW

**Comment by s0undt3ch** [comment]
The lint is fixed in the signals PR

**Comment by s0undt3ch** [comment]
The loader failures is because of the lint issue.

**Comment by s0undt3ch** [comment]
The failures seem consistent with the failures in current develop branch...

**Comment by cachedout** [comment]
Merged! Thanks, @s0undt3ch

**Pull request merged**
