### PR TITLE
Add macos Big Sur

### PR DESCRIPTION
**Pull request by krionbsd**
### What does this PR do?
Add macos Big Sur

### CODE REVIEW

**Review by bryceml — DISMISSED** [review]

**Review by twangboy — DISMISSED** [review]

**Comment by Ch3LL** [comment]
Looks like there is quit a few failures on sur

**Comment by Ch3LL** [comment]
@bryceml are you looking into these failures or do we need to assign someone else to look into them?

**Comment by Ch3LL** [comment]
actually it looks like sur is passing tests, but I want to make sure we run the full test suite first

**Comment by Ch3LL** [comment]
re-run full all

**Comment by Ch3LL** [comment]
Yes, looks like there are many failure:

`= 25 failed, 10934 passed, 1820 skipped, 1 xfailed, 1758 warnings in 17768.10s (4:56:08) =`

where can we help here @bryceml ?

**Pull request closed without merging**
