### PR TITLE
missing blank line to render rst-list

### PR DESCRIPTION
**Pull request by rolszewo**
before a list a blank line is needed to render correct

### What does this PR do?
fix list in documentation of beacon.watchdog

### What issues does this PR fix or reference?
Fixes: -

### Previous Behavior
List is not rendered properly. It looks like a normal sentence.

### New Behavior
List will be rendered as list in rst.document

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by rolszewo** [comment]
Hi friendly PR bot,
the missing docstrings are another topic.
This patch is only to repair the list in existing docstring.

**Review by whytewolf — APPROVED** [review]

**Comment by Ch3LL** [comment]
pre-commit and lint are failing

**Comment by rolszewo** [comment]
looks like the linter does not unterstand, that this empty line is needed for rst-document.
```
nox > Command pylint --rcfile=.pylintrc --disable=I salt/beacons/watchdog.py failed with exit code 16
************* Module salt.beacons.watchdog
salt/beacons/watchdog.py:194: [C0303(trailing-whitespace), ] Trailing whitespace
```

line 194 is the added emty line of this PR. 
And this is wanted and needed.

**Comment by Ch3LL** [comment]
I believe there might be something off with tabs or something else, because pre-commit is even showing it wants you to remove the entire line. When I locally tested adding a blank line, lint and pre-commit both passed.

**Comment by Ch3LL** [comment]
For some reason I could not directly push to your branch so I opened a new PR but made sure to cherry-pick your initial commit. https://github.com/saltstack/salt/pull/62764

There was a tab character and that's what was causing the issues. I'll monitor the tests in PR https://github.com/saltstack/salt/pull/62764

**Pull request closed without merging**
