### PR TITLE
[NEW FEATURE] modules and states to manage Helm. 

### PR DESCRIPTION
**Pull request by ArthurREGNARD**
Signed-off-by: REGNARD <areganrd@leni.fr>

### What does this PR do?
Add some Modules and States to manage Helm. 

### What issues does this PR fix or reference?
None

### Previous Behavior
None

### New Behavior
Manage Helm with Modules and States.

### Tests written?
Yes

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by ArthurREGNARD** [comment]
@DmitryKuzmenko @team-core, 

Are you interested on this feature ?

**Comment by DmitryKuzmenko** [comment]
re-run full amazon1-py2
re-run full centos6-py2
re-run full windows2019

**Comment by DmitryKuzmenko** [comment]
@ArthurREGNARD thank you for contribution.
@saltstack/team-core what do you think?

**Comment by ArthurREGNARD** [comment]
re-run full amazon1-py2
re-run full centos6-py2

**Comment by ArthurREGNARD** [comment]
re-run full amazon1-py2
re-run full centos6-py2

**Comment by ArthurREGNARD** [comment]
re-run full centos6-py2

**Comment by ArthurREGNARD** [comment]
re-run full centos6-py2

**Comment by ArthurREGNARD** [comment]
re-run full centos6-py2

**Comment by ArthurREGNARD** [comment]
re-run full centos6-py2

**Comment by ArthurREGNARD** [comment]
re-run full centos6-py2

**Comment by ArthurREGNARD** [comment]
@saltstack/team-core, @DmitryKuzmenko ,

I re-run some times the ci/py2/centos6`, and the result is a probleme of Memory ...

The PR is ready to merge.

**Review by DmitryKuzmenko — DISMISSED** [review]

**Comment by DmitryKuzmenko** [comment]
I'm approving this and confirming that centos6 failure is not related.

**Review by dwoz — APPROVED** [review]

**Comment by brianthelion** [comment]
@ArthurREGNARD How do you set the `--kubeconfig` for these states? I tried adding it to the `kvflags` but that didn't seem to work.

**Comment by ArthurREGNARD** [comment]
> @ArthurREGNARD How do you set the `--kubeconfig` for these states? I tried adding it to the `kvflags` but that didn't seem to work.

You work with Helm version 3.
Have you done something like that ?

```yaml
helm_release_is_present:
    helm.release_present:
        - name: release_name
        - chart: repo/chart
        - kvflags:
            kubeconfig: "/path/to/kubeconfig/file"
```

**Comment by brianthelion** [comment]
Yes, I think the problem is that `--kubeconfig` needs to go before `install` like so:

```bash
helm  \
  --kubeconfig=/path/to/kubeconfig \
  install \
  ....
```
whereas the [source code](https://github.com/saltstack/salt/blob/4f3cb36955d84c6793efcbeabf53963067922d90/salt/modules/helm.py#L87) puts all the `kvflags` at the end of the list.

**Pull request merged**
