### PR TITLE
Fixes a bug of rest_tornado's 'local' client, complement fix of #46326

### PR DESCRIPTION
**Pull request by kstreee**
### What does this PR do?

Targeting minions to subscribe before publishing  a requested job. The exact targeted minions can get after publishing a job, but this newer version of 'local' client subscribes minion's return before publishing the job, to not miss the results. Thus, to get what minions will be targeted, this fix changes the logic to use the `ckminions`' `check_minions` method.

### What issues does this PR fix or reference?

This fix is a complement fix of #46326, and a relevant discussion is in #47200 too.

 ### Tests written?

No, but re-enabled the two tests will cover the cases what I missed.

### Commits signed with GPG?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by cachedout — APPROVED** [review]
LGTM

**Comment by gtmanfred** [comment]
@kstreee does this set of PRs with the saltnado syndic timeout fix this issue? https://github.com/saltstack/salt/issues/42659

Thanks,
Daniel

**Comment by rallytime** [comment]
@kstreee It appears that the Python 3 tests have some related failures. Can you take a look?

https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu16-py3/9477/

**Comment by kstreee** [comment]
@gtmanfred Hi, the bug was fixed by the pr #46692, but the target branch of the pr is develop. To resolve conflict between the pr and 2017.7 version of 'local' client fixes (what I have been working), I proposed this pr. I think the manually copied test case what I added right before can check whether this pr fix the syndic issue or not.
It's a little bit confusing that working with several branches to me. Sorry for that 😂.

**Comment by gtmanfred** [comment]
Awesome, thank you very much for this!  Saves me a bit of work having to get more familiar with the saltnado and fixing that issue for a customer.

Thanks!
Daniel

**Comment by rallytime** [comment]
Hey @kstreee - would you mind taking a look at the 2018.3 branch for this? I have merged this change forward with #47435 to the 2018.3 branch, but the tests that you enabled here were not working in the merge-forward and I had to add the skipIfs back in. I am not sure what is different there compared to 2017.7, but after looking at this most of the day today, I think having someone more familiar with that part of the code look would be best. 

Would you mind taking a look at that when you get a chance?

**Pull request merged**
