### PR TITLE
Chroot logs

### PR DESCRIPTION
**Pull request by danfoster**
### What does this PR do?

Makes logs from a module call from inside a chroot via `chroot.call` visible. 

### Previous Behavior

While calling a salt module shows logs, e.g.:

```# salt-call --local log.error "Something went wrong" -l error
[ERROR   ] Something went wrong
local:
    True
```

Calling the module via chroot.call make the logs not visible, e.g.:

```
salt-call --local -l error chroot.call /var/workdir/chroot log.error \"Something went wrong\"
local:
    True
```

### New Behavior

Logs are not properated from the chroot at the correct log level and prefixed with the string `(chroot)` to signify where they have come from. e.g.

```
# salt-call --local -l error chroot.call /var/workdir/chroot log.error \"Something went wrong\"
[ERROR   ] (chroot) Something went wrong
local:
    True
```

### CODE REVIEW

**Review by waynew — CHANGES_REQUESTED** [review]
Hey @danfoster thanks for the PR! This looks pretty great!

The only thing that this PR needs is a [changelog entry](https://docs.saltstack.com/en/latest/topics/development/changelog.html) - I see that you've fixed some existing tests, that you're testing the relog, and that you're testing that the log actually gets emitted up through relog, so... excellent job! Get that changelog entry in here and I can go ahead and approve the PR :rocket:

**Comment by danfoster** [comment]
Hi @waynew - Thanks for reviewing!

I've added the changelog and attempted to fix as many of the automated tests as possible. I'm now stuck at `ci/py3/windows*/pytest` failing, it looks like it's a CI failure rather than the tests failing:

```
11:37:57  [Pipeline] stage
11:37:57  [Pipeline] { (Download Artefacts)
11:37:57  [Pipeline] withEnv
11:37:57  [Pipeline] {
11:37:57  [Pipeline] sh
11:37:58  + bundle exec kitchen verify py3-windows-2019
11:37:58  -----> Starting Kitchen (v2.2.5)
11:38:00  -----> Verifying <py3-windows-2019>...
11:38:00         [Nox] Only downloading artefacts from instance py3-windows-2019 with state={:username=>"administrator", :server_id=>"i-00f09a799f6917bfc", :hostname=>"10.74.119.127", :password=>"qpCsOI8g@Cyox3nt$6)(lwlO2zb3D$@I", :last_action=>"setup", :last_error=>"Kitchen::Transport::WinrmFailed"}
11:38:12         
11:38:12         7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
11:38:12         
11:38:12         Scanning the drive:
11:38:12         0 files, 0 bytes
11:38:12         
11:38:12         Creating archive: C:\Users\ADMINI~1\AppData\Local\Temp\kitchen/testing/artifacts/artifacts.zip
11:38:12         
11:38:12         Add new data to archive: 0 files, 0 bytes
11:38:12         
11:38:12         
11:38:12         Files read from disk: 0
11:38:12         Archive size: 22 bytes (1 KiB)
11:38:12         
11:38:12         Scan WARNINGS for files and folders:
11:38:12         
11:38:12         C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\testing\artifacts : The system cannot find the file specified.
11:38:12         ----------------
11:38:12         Scan WARNINGS: 1
11:38:12  $$$$$$ 7z.exe : 
11:38:12      + CategoryInfo          : NotSpecified: (:String) [], RemoteException
11:38:12      + FullyQualifiedErrorId : NativeCommandError
11:38:12  WARNING: The system cannot find the file specified.C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\testing\artifacts
11:38:12         7z.exe failed, attempting zip with powershell Compress-Archive
11:38:16         Copying $env:KitchenTestingDir/artifacts/ to /var/jenkins/workspace/_windows2019-py3-pytest_PR-58978
11:38:18  unzip:  cannot find or open artifacts.zip, artifacts.zip.zip or artifacts.zip.ZIP.
11:38:18  rm: cannot remove 'artifacts.zip': No such file or directory
11:38:18         [Nox] Download artefacts completed.
11:38:18         Finished verifying <py3-windows-2019> (0m18.39s).
11:38:18  -----> Kitchen is finished. (0m19.77s)
11:38:18  [Pipeline] }
11:38:18  [Pipeline] // withEnv
11:38:18  [Pipeline] sh
11:38:19  + '[' -s .kitchen/logs/py3-windows-2019.log ']'
11:38:19  + mv .kitchen/logs/py3-windows-2019.log .kitchen/logs/py3-windows-2019-full-download.log
11:38:19  + '[' -s .kitchen/logs/kitchen.log ']'
11:38:19  + mv .kitchen/logs/kitchen.log .kitchen/logs/kitchen-full-download.log
11:38:19  [Pipeline] }
11:38:19  [Pipeline] // stage
11:38:19  [Pipeline] sh
11:38:19  + xz .kitchen/logs/kitchen-full-verify.log .kitchen/logs/py3-windows-2019-full-verify.log
11:38:19  + xz 'artifacts/logs/runtests-*'
11:38:19  xz: artifacts/logs/runtests-*: No such file or directory
11:38:19  + true
```

Can you advise on how to proceed?

**Comment by waynew** [comment]
Hey @danfoster sorry for the late response, this seems to have fallen through the cracks. Looks like there are some merge conflicts - would you mind fixing those?

Thanks!

**Comment by waynew** [comment]
@danfoster just another ping on this - looks like some merge conflicts are kicking around.

**Comment by waynew** [comment]
Thanks for the rebase! I should be able to take a look at this next week

**Comment by waynew** [comment]
@danfoster looks like there's a pre-commit failure (see https://docs.saltproject.io/en/latest/topics/development/contributing.html#pre-commit-and-nox-setup for some more info on setting it up)

**Comment by waynew** [comment]
@danfoster no rush - is this something that you're interested in getting completed?

**Comment by danfoster** [comment]
@waynew thanks for the reminder. I would be happy to keep trying to get this over the line. I've just pushed some changes that passed `pre-commit`, let's see what CI makes of it...

**Comment by waynew** [comment]
I've updated the PR with the latest changes, so hopefully the tests will all pass, and I can give this a re-review :+1:

**Comment by waynew** [comment]
Ahhh, oops - **https://jenkins.saltproject.io/job/pr-centosstream-8-x86_64-py3-pytest/job/PR-58978/5/testReport/junit/tests.unit.modules.test_chroot/ChrootTestCase/test_relog_plain/**

Looks like the logging changes that we recently merged broke some things :upside_down_face: mind taking a look?

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
