### PR TITLE
Pyobjects Map: prioritize grains by declaration order.

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
### What does this PR do?
The `pyobjects.Map` implementation assumed that iterating on the class `__dict__` iterates in the declaration order but it's not guaranteed by Python and could be implementation specific.

So this PR makes the Map working so later declared values override the previous ones.

Note: this fix makes the Map work as it was initially designed and doesn't conflict with #41951. In the case `priority` is set it will override the declaration order.

### What issues does this PR fix or reference?
Fixes https://github.com/saltstack/salt-jenkins/issues/435
Related to https://github.com/saltstack/salt/pull/41951

### Tests written?
No

### CODE REVIEW

**Review by terminalmage — COMMENTED** [review]
This does work to preserve declaration order, but as much as I like it, I think it might not be the right approach. The reason for this is that the `match_groups` OrderedDict has the grain name as the key. All `os_family` classes will be under the `os_family` key, all `os` classes will be under the `os` key. And because it's an OrderedDict, the definition order only matters for the first time a class for that grain is matched. Consider the following map:

```
class Samba(Map):

    class Debian:
        foo = 'bar'

    class Ubuntu:
        __grain__ = 'os'
        foo = 'baz'

    class CentOS:
        __grain__ = 'os'
        foo = 'hello'

    class RedHat:
        foo = 'world'
```

A CentOS minion would match both on the `CentOS` and `RedHat` classes. Given the declaration order, it would be assumed that `Samba.foo` would be assigned the value `world` (since the `Redhat` class comes later), but remember that the classes were entered into the `match_groups` in the order they were declared. That means that the `Debian` class would be processed first, and since it matches on the `os_family` grain, the `match_groups` OrderedDict's first key would be `os_family`, not `os`. So, when we loop through the `match_groups` below, `os_family` would be processed first, and `os` second, and the result would be that a CentOS minion would have the value `hello` assigned to `Samba.foo`.

**Comment by cachedout** [comment]
@DmitryKuzmenko Please see the above comment as soon as you possibly can. This the the last thing we need before we tag the release.

**Comment by terminalmage** [comment]
Something like the below patch (which I haven't tested yet) would do away with the `match_groups` and `grains.filter_by` in favor of using `grains.item` to get all of the targeted grains, and then manually performing the comparison and updating the `attrs` dict accordingly. Note that this would conflict with the merging of my PR (https://github.com/saltstack/salt/pull/41951), so we should hold off on merging that for now.

```diff
diff --git a/salt/utils/pyobjects.py b/salt/utils/pyobjects.py
index 89bb3344d4..76b2188290 100644
--- a/salt/utils/pyobjects.py
+++ b/salt/utils/pyobjects.py
@@ -308,7 +308,8 @@ class MapMeta(six.with_metaclass(Prepareable, type)):
         super(MapMeta, cls).__init__(name, bases, nmspc)
 
     def __set_attributes__(cls):
-        match_groups = OrderedDict([])
+        match_info = []
+        grain_targets = set()
 
         # find all of our filters
         for item in cls.__ordered_attrs__:
@@ -323,8 +324,7 @@ class MapMeta(six.with_metaclass(Prepareable, type)):
 
             # which grain are we filtering on
             grain = getattr(filt, '__grain__', 'os_family')
-            if grain not in match_groups:
-                match_groups[grain] = OrderedDict([])
+            grain_targets.add(grain)
 
             # does the object pointed to have a __match__ attribute?
             # if so use it, otherwise use the name of the object
@@ -335,19 +335,22 @@ class MapMeta(six.with_metaclass(Prepareable, type)):
             else:
                 match = item
 
-            match_groups[grain][match] = OrderedDict([])
+            match_attrs = {}
             for name in filt.__dict__:
-                if name[0] == '_':
-                    continue
+                if name[0] != '_':
+                    match_attrs[name] = filt.__dict__[name]
 
-                match_groups[grain][match][name] = filt.__dict__[name]
+            match_info.append((grain, match, match_attrs))
 
+        # Check for matches and update the attrs dict accordingly
+        grain_vals = Map.__salt__['grains.item'](*grain_targets)
         attrs = {}
-        for grain in match_groups:
-            filtered = Map.__salt__['grains.filter_by'](match_groups[grain],
-                                                        grain=grain)
-            if filtered:
-                attrs.update(filtered)
+        for grain, match, match_attrs in match_info:
+            try:
+                if grain_vals[grain] == match:
+                    attrs.update(match_attrs)
+            except KeyError:
+                continue
 
         if hasattr(cls, 'merge'):
             pillar = Map.__salt__['pillar.get'](cls.merge)
```

**Comment by DmitryKuzmenko** [comment]
@terminalmage You're completely right about that note. And I like this patch.
What about the `Map` functionality as it designed, I dislike that approach to use the declaration order as a significant value. Because in a common case class fields shouldn't be an order specific. I've just tried to keep the initial design as is.
So if it will not break the existing user experience I vote for the `priority` based approach and don't merge this PR keeping the only #41951.

**Comment by terminalmage** [comment]
I think there's no reason we can't do both. Declaration order is easy for people to understand, and they can always override that using my `priority` feature.

If we merge your PR, I can rebase and rework my PR to comply with the updated approach.

**Comment by DmitryKuzmenko** [comment]
@terminalmage I've done here. Could you review it please?

**Comment by terminalmage** [comment]
@DmitryKuzmenko Looking now

**Review by terminalmage — APPROVED** [review]
Tested and confirmed it works. :+1:

**Review by cachedout — APPROVED** [review]

**Pull request merged**
