### PR TITLE
Fix: parsing issue when detecting ASN1 vs PEM encoded certificates.

### LINKED ISSUE #59503: [BUG]. keystore state/module unable to list ASN1 - DER certs in keystore
### Description of Issue
This seems a python3 issue.

When a new keystore is created and a new cert added (python-36 at the moment), keystore.list is unable to determine the cert type (ASN1)

### Setup
formula.app.saml.keystore:
  keystore.managed:
    - name: '{{ app.saml.keystore.url }}'
    - passphrase: '{{ app.saml.keystore.pass }}'
    - force_remove: True
    - entries:
      - alias: '{{ app.saml.keystore.key }}'
        certificate: '{{ app.saml.cert }}'
        private_key: '{{ app.saml.key }}'

### Steps to Reproduce Issue
Re-run your state in debug and test mode
```
salt-call -l debug formula.app test=True
          ID: formula.app.saml.keystore
    Function: keystore.managed
        Name: /opt/app/conf/saml.jks
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/behavox/salt/venv/lib64/python3.6/site-packages/salt/state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/opt/behavox/salt/venv/lib64/python3.6/site-packages/salt/loader.py", line 2087, in wrapper
                  return f(*args, **kwargs)
                File "/opt/behavox/salt/library/extmods/states/keystore.py", line 90, in managed
                  existing_entries = __salt__["keystore.list"](name, passphrase)
                File "/opt/behavox/salt/library/extmods/modules/keystore.py", line 120, in list
                  if "\x30" in cert_result[0]:
              TypeError: argument of type 'int' is not iterable
     Started: 15:45:19.325124
    Duration: 5.537 ms
     Changes:   
```
I also tried to run the keystore.list module directly:
```
    Passed invalid arguments to keystore.list: argument of type 'int' is not iterable
    
        Lists certificates in a keytool managed keystore.
    
    
        :param keystore: The path to the keystore file to query
        :param passphrase: The passphrase to use to decode the keystore
        :param alias: (Optional) If found, displays details on only this key
        :param return_certs: (Optional) Also return certificate PEM.
    
        .. warning::
    
            There are security implications for using return_cert to return decrypted certificates.
    
        CLI Example:
    
        .. code-block:: bash
    
            salt '*' keystore.list /usr/lib/jvm/java-8/jre/lib/security/cacerts changeit
            salt '*' keystore.list /usr/lib/jvm/java-8/jre/lib/security/cacerts changeit debian:verisign_-_g5.pem
```

### Versions Report

Salt Version:
           Salt: 3001.3
 
Dependency Versions:
           cffi: 1.14.4
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: 0.37.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: Not Installed
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.18.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core

### PR DESCRIPTION
**Pull request by zeroschism**
Also addresses a few other locations where bytes vs string encoding was causing an issue.  Finally, we fix an issue where aliases are specified in mixed case or upper case, but are automatically lowercased by the underlying pyjks library.  Documentation is also updated to indicate dependent libraries without which the module will not work

### What does this PR do?
* Fixes a byte encoding issue when trying to detect ASN1 vs PEM encoded certificates/keys
* Corrects a few other locations where bytes were incorrectly used instead of str
* Fixes an issue where mixed-case alias names wouldn't properly be managed due to the underlying library forcing them to lowercase.
* Updates the documentation to identify dependencies

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/59503

### Previous Behavior
Exception thrown when managing an existing keystore, or re-applying the state after initial creation of keystore

### New Behavior
Properly loads and manages all the certificates and keys in the keystore

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by Ch3LL** [comment]
@zeroschism would you mind resolving the merge conflicts here

**Review by Ch3LL — CHANGES_REQUESTED** [review]
This will require test coverage. Once added I'll give this a closer review.

**Comment by zeroschism** [comment]
I think I've sorted out the merge conflicts @Ch3LL.  I can take a stab at adding a test.

**Comment by zeroschism** [comment]
@Ch3LL I've added a test case.  Let me know if you need anything else

**Review by Ch3LL — CHANGES_REQUESTED** [review]
This just needs a changelog file. Looks like this PR https://github.com/saltstack/salt/issues/59503 resolved some of the issues. Can you add another changelog file that points to this PR and includes details on this specific fix.

**Comment by Ch3LL** [comment]
Also, it looks like there are valid test failures related to this PR

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
