### PR TITLE
Changed references from MacOS to Mac

### PR DESCRIPTION
**Pull request by twangboy**
os grain for mac was changed from 'MacOS' to 'Mac'
Changed references to the old grain
Used 'salt.utils.is_darwin()' where possible

### CODE REVIEW

**Comment by cachedout** [comment]
If I'm reading this right, this grain got changed back here? https://github.com/saltstack/salt/pull/30050/files

Changing an OS grain like that is going to break everybody who is targeting via the `MacOS` grain and force them to rewrite their SLS files to account for the difference. Is there a migration plan for these people?

**Comment by twangboy** [comment]
No, should I change the os grain back to MacOS then?

**Comment by cachedout** [comment]
Has the grains rename change gone out into a release?

**Comment by twangboy** [comment]
No, this is all on the develop branch.

**Comment by twangboy** [comment]
Unless core has been backported...

**Pull request closed without merging**
