### PR TITLE
[UPGRADE] Migrate Salt Cloud cachedir to the new location

### PR DESCRIPTION
**Pull request by vutny**
### What does this PR do?

It assists the transition of old path for [Salt Cloud Cache](https://docs.saltstack.com/en/latest/topics/cloud/misc.html#salt-cloud-cache) dir (set as default to `/var/cache/salt/cloud` previously) to the new one (`/var/cache/salt/master/cloud`), which based on `cachedir` option value.

This is a breaking change introduced in version `2016.3.3` (and `2015.8.12`). It will cause Salt Cloud cache to be populated again **from scratch**.
If user has configured [Salt Cloud Reactor](https://github.com/saltstack-formulas/salt-cloud-reactor) or [Autoscale Reactor](https://github.com/saltstack-formulas/ec2-autoscale-reactor) or has any custom implementation depending on `salt/cloud/*/cache_node_new` event tags, all actions will be repeated for each existing machine. But `salt/cloud/*/cache_node_missing` and `salt/cloud/*/cache_node_diff` events will be lost.

Such all-of-sudden activity may have undesired effects across user's Salt infrastructure. And it might be kinda hard to figure out what happened and why.
### What issues does this PR fix or reference?

Salt Cloud cachedir path change was added by merging PR #35483
### Previous Behavior

After upgrading to version `2016.3.3` (`2015.8.12`) from git, Salt Cloud forgets about cached information.
### New Behavior

Salt Cloud cachedir will be moved to the new location if there is no directory already in place where.
### Tests written?

No

### CODE REVIEW

**Comment by techhat** [comment]
Okay, this is a problem. The cloud `cachedir` should not be `/var/cache/salt/master/cloud/`, because cloud commands can be run on a minion too, or even on a machine that is neither master nor minion. The default should always be `/var/cache/salt/cloud/`.

@gtmanfred, would you please take a look?

**Comment by vutny** [comment]
@techhat Thanks for the quick feedback! I've really thought that changing to `/var/cache/salt/master/cloud/` was intended... It's totally another matter. I will come up with another PR to address this.

**Comment by gtmanfred** [comment]
The problem appears that the cache_dir in opts is not /var/cache/salt, and is instead /var/cache/salt/master.  I think I have a solution for this

**Comment by vutny** [comment]
I'm closing this in favor of #35898

**Pull request closed without merging**
