### PR TITLE
[develop] Merge forward from 2016.11 to develop

### PR DESCRIPTION
**Pull request by rallytime**
No conflicts.

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
We will need to rebase and then retest this. It was broken by #37717

**Comment by rallytime** [comment]
Can do. Probably just easier to re-do the PR. Thanks for looking into this @cachedout!

**Comment by rallytime** [comment]
Replaced by #37729

**Pull request closed without merging**
