### PR TITLE
2019.2: bug: executors lazyloader is missing functions and proxy args

### PR DESCRIPTION
**Pull request by mattp-**
What does this PR do?
these are needed for this functionality to work

### Tests written?
should be covered by existing tests

### Commits signed with GPG?
no

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by waynew** [comment]
@mattp- thanks for the PR!

Is there a test that this fixes, or would it be possible to throw together a regression test?

**Comment by mattp-** [comment]
the bug is only seen in the sudo executor in core, for which there are no tests. I am working on a replacement implementation of that executor that doesn't rely on sudo but it is not ready for upstream

**Comment by mattp-** [comment]
@waynew i worked out adding an integration test that exercises the bug, however I can't backport it to #52772 because it relies on salt-call having --module-executors via salt-call, which is new functionality added elsewhere in 2019. while doing this i uncovered that executors weren't actually exposed via saltutil.sync* in runner & module, so added that in both pr's. looks like serializer was also added in 2019 but not 2018, so i added it there as well in the other PR.

**Comment by mattp-** [comment]
@waynew clean now. py3 windows seems hung from unrelated issue, but py2 windows passed along with the others.

**Comment by waynew** [comment]
Looks like last couple passed, just waiting on this current build to finish

**Comment by waynew** [comment]
Oi. Looks like this is out of date again 😜

**Comment by mattp-** [comment]
something seems wrong with that win2k16 build, its been running for 2 hours. I'll update branch maybe it will pass this time

**Comment by mattp-** [comment]
@waynew clean now

**Review by waynew — APPROVED** [review]

**Comment by max-arnold** [comment]
I'm pretty sure this could cause some conflicts during a forward-merge, because I added `sync_executors` to develop (Neon): #51427

**Pull request merged**
