### PR TITLE
Added all input variables for Joyent CreateMachine API call, fixed an…

### PR DESCRIPTION
**Pull request by wise0wl**
### What does this PR do?
* Added all input variables for Joyent CreateMachine API call (tag, locality, metadata, firewall_enabled)
* Fixed an ClouAPI call and validated against VALID_RESPONSE_CODES
* Fixed query function, allowing use account sub-users
* Added functionality to list networks with ability to call from salt-cloud module action function

### What issues does this PR fix or reference?
* https://github.com/saltstack/salt/issues/37755

### CODE REVIEW

**Comment by ptariche** [comment]
=D

**Comment by cachedout** [comment]
Hi @wise0wl Thanks for this! Could you please take a look at these lint errors? Thanks very much.

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/6867/violations/file/salt/cloud/clouds/joyent.py/

**Comment by cachedout** [comment]
@wise0wl It also appears that this test has failed:

https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/7014/testReport/junit/unit.cloud.clouds.joyent_test/JoyentTestCase/test_create_fail/

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@wise0wl Were you able to look into this failing test?

**Comment by eradman** [comment]
Since I wrote `tests/unit/cloud/clouds/joyent_test.py` I took a close look at this failure. `test_create_fail()` works for what it was created for, but the setup fixture does not sufficiently configure a provider/profile to enable `salt.config.is_profile_configured()` to function.

I spent a solid hour on improving this but did not succeed at constructing a fixture that works well enough to pass this change. It's always sad to disable a test, but I think this one will need to be removed or disabled.

I did some light manual testing with this PR and it seems to work fine.

**Comment by cachedout** [comment]
@eradman I really appreciate you jumping in on this one. Thanks! I'll submit a PR to remove the test per your investigation. After that's in, I'll go ahead and re-test and then merge this. Thanks again.

**Comment by wise0wl** [comment]
My appologies---I have been incommunicado for the Thanksgiving holiday.  I appreciate the follow up!  If there are any other changes that need to be made to the PR before merging I will be watching this thread.

**Comment by cachedout** [comment]
@wise0wl We do need the lint errors fixed before we can get this in. Could you take a look? I'm getting the test removed right now.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@wise0wl We still have a very minor lint error and a failing test as well:

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/7292/violations/file/salt/cloud/clouds/joyent.py/

https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/7439/testReport/junit/unit.cloud.clouds.joyent_test/JoyentTestCase/test_create_fail/

**Comment by cachedout** [comment]
@wise0wl Did you see my comments above regarding the lint and the test failure?

**Comment by cachedout** [comment]
@wise0wl Are you able to address the issues with the lint failures and the test that isn't passing?

**Comment by cachedout** [comment]
Go Go Jenkins!

**Pull request merged**
