### PR TITLE
Overhaul Joyent driver, mostly for new API

### PR DESCRIPTION
**Pull request by techhat**
Ping @rallytime, @cro.

### CODE REVIEW

**Comment by rallytime** [comment]
Fixes #18979

**Comment by rallytime** [comment]
Don't merge this yet please - I found a stacktrace in my testing.

**Comment by techhat** [comment]
Fixed the image list, to report from the configured data center. Still trying to figure out a profile error. Please don't merge yet.

**Comment by techhat** [comment]
Okay, looks like create() works now. Ready for testing.

**Comment by rallytime** [comment]
Found a new stacktrace. Don't merge yet, please.

**Comment by techhat** [comment]
Ready for testing again

**Comment by rallytime** [comment]
I've tested this and it looks good!

**Comment by thatch45** [comment]
For the record the pycrypto here is good because we only handle one side of the handshake

**Pull request merged**
