### PR TITLE
Ignore ordering when comparing mount options

### PR DESCRIPTION
**Pull request by thusoy**
### What does this PR do?

Ignore ordering differences when comparing bind mounts. Prior to this a bind mount would always cause the fstab to be rewritten since the opts coming to the module from the `mount.mount` are randomized. This prevents that behavior.

### What issues does this PR fix or reference?
Fixes:
https://github.com/saltstack/salt/issues/19003
https://github.com/saltstack/salt/issues/55769

### Previous Behavior
`mount.mounted` would always remount bind mounts.

### New Behavior
`mount.mounted` only remounts if some parameter changes.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by DmitryKuzmenko — DISMISSED** [review]

**Comment by thusoy** [comment]
What is needed to get a PR merged these days? This was approved in May and is still hanging around 3 months later.

**Comment by DmitryKuzmenko** [comment]
This needs to have green tests and be approved. I've updated it to master, let's see will tests pass this time or not.

**Comment by nicholasmhughes** [comment]
@thusoy , are you interested in picking this back up?

**Comment by nicholasmhughes** [comment]
Closing in favor of #62557

**Comment by thusoy** [comment]
Thanks for getting this issue fixed, @nicholasmhughes, I'm not online much these days as I'm on leave. Honestly I was so discouraged from trying to get anything merged from how poorly this was handled that I didn't have much energy to try to get anything fixed anymore. All related tests were green and this was ready to merge and should have been shipped many releases ago, but unrelated test failures kept it from getting merged and it was just pushed around for weeks before being abandoned. Hoping the process has improved significantly since then.

**Pull request closed without merging**
