### PR TITLE
Add psutil

### LINKED ISSUE #60523: [BUG] pidfile is removed on check (salt 3003)
Hi!
I already reported the same bug in #57794 but seems it is introduced again.
The same. When one minion is running when I start it again it exits with:
```
18:11:20 [INFO    ] salt.cli.daemons:293 Setting up the Salt Minion "90520736270401"
18:11:20 [INFO    ] salt.cli.daemons:88 An instance is already running. Exiting the Salt Minion
18:11:20 [INFO    ] salt.cli.daemons:88 Shutting down the Salt Minion
```
And it removes the pid file. So when I start minion for the 3-rd time  it starts and I have 2 minions running.

### PR DESCRIPTION
**Pull request by cmcmarrow**
### What does this PR do?
Make all platforms have `psutils`. This PR will prevent a minion from starting if an instance is all ready running.

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/60523

### Previous Behavior
Remove this section if not relevant
More than one minion can be started.

### New Behavior
Remove this section if not relevant
Only one minion can be stated at a time.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by krionbsd** [comment]
Can we use socket module to check if minion port is open or not, that should work on windows too imho?

**Review by s0undt3ch — CHANGES_REQUESTED** [review]
Please remove the same requirement from the darwin/windows/FreeBSD requirements since it's now part of base.txt

**Comment by cmcmarrow** [comment]
> Can we use socket module to check if minion port is open or not, that should work on windows too imho?

Unlike the master that uses the same port and IP every time the minion does not us the same port every time. We could assignee the minion the same port every time, but I don't think this behavior would be wanted.

Also before my changes that want `pstuil` they used a file to check the minion state but deleted it after, which allows a minion to start on the 2nd attempt.

**Comment by cmcmarrow** [comment]
Also if someone has multiple minions on the same computer for some reason they would need to change the minion port in the config if we assigned the minion a port.

**Review by s0undt3ch — CHANGES_REQUESTED** [review]
Also remove `psutil` from `requirements/static/pkg/linux.in`

**Review by bryceml — DISMISSED** [review]

**Review by s0undt3ch — DISMISSED** [review]

**Comment by s0undt3ch** [comment]
You needs to rebase the PR, it's still trying to pull in `suds` dependency....

**Comment by cmcmarrow** [comment]
https://github.com/saltstack/salt/pull/60946

**Pull request closed without merging**
