### PR TITLE
Print stdout on apt install failure

### PR DESCRIPTION
**Pull request by piotr1212**
When apt install fails it is not clear from the stderr output what went wrong, ex:

 ```
  errors:
     - Running scope as unit: run-r5851ebada9ac4ae0a1ef7288de7c4b69.scope
       E: Unable to correct problems, you have held broken packages.
```
After adding the stdout it shows why it failed:

```
  errors:
      - Reading package lists...
        Building dependency tree...
        Reading state information...
        Some packages could not be installed. This may mean that you have
        requested an impossible situation or if you are using the unstable
        distribution that some required packages have not yet been created
        or been moved out of Incoming.
        The following information may help to resolve the situation:

        The following packages have unmet dependencies:
         bla:i386 : Depends: libsomethingorrather:i386 (>= 1.2.13) but it is not installable
                    Depends: anotherDependency:i386 (>= 1.2.6) but it is not installable
      - Running scope as unit: run-r0097166ab0f9412c879647df0955982f.scope
        E: Unable to correct problems, you have held broken packages.
```

### What does this PR do?
Print stdout when apt install fails.

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Only print stderr

### New Behavior
print stderr and stdout

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by piotr1212** [comment]
https://github.com/saltstack/salt/issues/43079

**Comment by piotr1212** [comment]
Wondering if this would be useful for all failures of apt, not only install or that this should be configurable with a loglevel.

**Review by Ch3LL — CHANGES_REQUESTED** [review]
Can you add some test coverage. Also the changelog file only needs the PR number and I would not label this as a new feature. Can you rename the file to 57252.fixed, since its fixing an issue where not all output is included in the error?

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
