### PR TITLE
New execution module: napalm helpers

### PR DESCRIPTION
**Pull request by mirceaulinic**
### What does this PR do?

Introduces a new NAPALM module for the proxy keepalive.
The required feature has been introduced in https://github.com/saltstack/salt/pull/38829 and will be available only in Nitrogen.

I understand it is not common to introduce new modules/features in a minor release, but I hear this request more and more often. Would be possible to make and exception and gate this into 2016.11.3?

Thanks,
Mircea

### CODE REVIEW

**Comment by cachedout** [comment]
We do get this type of request a lot but we've made a commitment to the community not to do this. While I appreciate that people want this in, we'd very much prefer not to. Would having them drop the updated module in the masters ext_dir and then syncing it allow people a suitable workaround?

**Comment by mirceaulinic** [comment]
Sure, I totally understand that - this is the current way to provide this feature. 
At the same time, looking at PRs such https://github.com/saltstack/salt/pull/38377 I understand that sometime small exceptions are accepted.
Anyway, I personally believe that the community won't be very unhappy having this in :)

**Comment by cachedout** [comment]
I know. I just have to end up rejecting stuff that I believe to be safe because otherwise it just ends up being a slippery slope and more and more people end up asking for exceptions. It's a little unfair and frustrating but we've been down this road before and it hasn't ended well. Thanks for understanding.

**Comment by mirceaulinic** [comment]
Yes, I understand. Let's close this.

**Comment by mirceaulinic** [comment]
Hi @cachedout I have reopened this PR targeting the develop branch this time.
I do see benefits having this module in Nitrogen so please let's reconsider.

**Comment by mirceaulinic** [comment]
I still need to apply some adjustments here. Please let's keep this on hold a bit! Thanks!

**Comment by mirceaulinic** [comment]
I'm done here @cachedout... if linter agrees, this is ready to be reviewed! ;)

**Comment by cachedout** [comment]
Really nice. Thanks @mirceaulinic

**Pull request merged**
