### PR TITLE
Adding Digital Ocean ssh_interface feature

### PR DESCRIPTION
**Pull request by ankitforcode**
- What does this PR do?
  This will add ssh_interface feature for bootstrapping droplets on Digital Ocean Cloud.
- What issues does this PR fix or reference?
  There is no fix or reference.

### CODE REVIEW

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@ankitforcode Could you please address these lint issues? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/3795/violations/file/salt/cloud/clouds/digital_ocean.py/ Thanks!

**Comment by ankitforcode** [comment]
Done.

**Comment by cachedout** [comment]
Thanks, @ankitforcode. Merged.

**Pull request merged**
