### PR TITLE
Populate changes dictionary on system.join_domain

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?
Fixes issue with the `system.join_domain` state where the changes dictionary was not being populated when changes were made to the system.

- Populate the changes dictionary
- Fix docs formatting
- Clean up code
- Use explicit function calls
- Add comment about reboot status

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/49660

### Tests written?
No

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by rallytime — APPROVED** [review]

**Comment by hrumph** [comment]
Thanks @Twangboy. I have to point out that I think that the restart switch for this function should probably be deprecated, since we now have the system.reboot state (which is supposed to know about the pending domain join). Also the restart switch comes with no options, which means that it always has a five minute timeout. A sysadmin doing a domain join typically won't want a five minute timeout at that time since joining is usually a deployment step. Even if the reboot flag isn't deprecated it should result in an immediate reboot.

**Comment by dwoz** [comment]
@twangboy Can you look into this test failure?

`integration.modules.test_groupadd.GroupModuleTest.test_members`

**Comment by twangboy** [comment]
@dwoz The above failure is not related to this PR. However, I will look at the test to see if maybe it's flaky.

**Comment by twangboy** [comment]
@dwoz I can't replicate it locally, but it's doing several `run_function`s. Maybe one of them is failing. I modified the test so that it actually checks the results of the `group.members` function on Windows.

https://github.com/saltstack/salt/pull/49794

**Comment by rallytime** [comment]
@dwoz since @twangboy is addressing that test concern in another PR, how does this look to you now?

**Review by dwoz — APPROVED** [review]

**Comment by dwoz** [comment]
@rallytime That seems okay to me.

**Pull request merged**
