### PR TITLE
Simplify saltify cloud driver

### PR DESCRIPTION
**Pull request by vernondcole**
### What does this PR do?

Using the lessons learned during development of the Vagrant driver, switch from using
NetAPI calls to LocalAPI calls, thus making the code, and the setup, much smaller.

Also, add unit tests for most of the functions.

### What issues does this PR fix or reference?

None.

### New Behavior

Salt-api is no longer required to operate the advanced functions.

### Tests written?

Yes!.

### CODE REVIEW

**Comment by vernondcole** [comment]
@cachedout  @gtmanfred 
you may wish to review this update.

**Review by gtmanfred — APPROVED** [review]

**Comment by rallytime** [comment]
Thanks for submitting this @vernondcole.

Can you clean up these lint errors? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/15797/violations/file/tests/unit/cloud/clouds/test_saltify.py/

**Review by rallytime — APPROVED** [review]
Thanks @vernondcole - this looks good. Once those lint errors are cleaned up, we can get this in.

**Review by cachedout — APPROVED** [review]
This is really well done. Nice work here, @vernondcole

**Pull request merged**
