### PR TITLE
[DON'T MERGE] Add pkg runner, list available pkg upgrades and group by packages

### PR DESCRIPTION
**Pull request by arnisoph**
```
# salt-run pkg.list_upgrades jid=20150123193640519478
mysql-server-core-5.5:
    ----------
    5.5.41-0+wheezy1:
        ----------
        hosts:
            - ipm1013.domain.de
            - ypm1024.domain.de
            - ypm1007.domain.de
            - ypfo1030.domain.de
php54:
    ----------
    5.4.37~arbe-1-201501231844:
        ----------
        hosts:
            - wpm1003.domain.de
            - wpfo1031.domain.de
            - wpm1015.domain.de
php55:
    ----------
    5.5.21~arbe-1-201501231844:
        ----------
        hosts:
            - wpm1003.domain.de
            - wpfo1031.domain.de
            - wpm1015.domain.de
```

### CODE REVIEW

**Comment by thatch45** [comment]
Since we have seen no activity here for a long time I am going to close it out. Please feel free to re-open this PR when/if you feel it is ready to be merged

**Comment by bechtoldt** [comment]
Alright I'm going to make my last changes during the next 1-2 weeks.

**Comment by thatch45** [comment]
Sounds good, just re-open when you are ready to merge, these not ready to merge ones can slow down the process of merging PRs so I like to close them after they have been idle for a while

**Comment by bechtoldt** [comment]
Created new PR #20029

**Pull request closed without merging**
