### PR TITLE
Addition of powershell_all function

### PR DESCRIPTION
**Pull request by ghost**
### What does this PR do?
Adds a powershell_all function which combines cmd.powershell with cmd.run_all

### Tests written?

No

### CODE REVIEW

**Comment by damon-atkins** [comment]
I would suggest you take the current `def powershell,` turn it into def `powershell_all `(by calling run_all instead of run) and then have a new `powershell` call `powershell_all` and filter out the unwanted data.

As 95% of the code is the same.   And to save on doco space refer poweshell to powershell_all and then document the different output (i.e. filtered).

Had a quick look at how data is return, seems most often is response['result'] instead of response['outdict']
``
or h in result out outdict dict data value ; do echo $h $(fgrep -R "['$h']"  /usr/lib/python2.7/site-packages/salt/modules | wc -l ) ; done
result 312
out 52
outdict 0
dict 14
data 80
value 27
```
Thanks for adding this.

**Comment by hrumph** [comment]
@damon-atkins, I have changed 'outdict' to result. I am not entirely opposed to making powershell
based off of powershell_all, but I don't want to rock the boat too much. If I were to do something like
that I would like to make breaking changes to the behaviour of cmd.powershell.

Since cmd.powerhsell is based off of cmd.run, It will try to jsonise the output even if the output is from
stderr, and I don't think that that is good behaviour. Also when it can't jsonise the output it will return
{} instead of False or None. If it were based off of powershell_all it's behaviour could be improved a lot.
It could be easily made to return False or None on failure and it wouldn't try to jsonise error output.
Anyway I'm going to leave it alone unless @twangboy (or others salt maintainers) indicate that they are OK with that kind of thing.

**Comment by hrumph** [comment]
I was just thinking that sometimes windows exectuables return with non-0 exit codes sometimes even when they haven't failed so, I no longer replace the result with None, just because the retcode is non-0.
When stdout cannnot be parsed by Python, the result is ``False`` now instead of just ``None``. I have expanded the description of ``retcode`` in the documentation.

I also added the ``encoded_cmd`` paramater to cmd.run_all, so we can an encode_cmd param in cmd.powershell_all.

**Comment by cachedout** [comment]
@damon-atkins How are you feeling about this one now?

**Comment by damon-atkins** [comment]
The only differance between  powershell and the new powershell_all is
On error powershell returns `{}` on json conversion error i.e. empty dict
On error powershell_all returns with `result` set to `False`.   Should `result` be `False` or `{}` on json conversion error

@twangboy  Every thing else is fine.  What was the reason for "powershell returns `{}` on json conversion error" and should powershell_all match?

**Comment by hrumph** [comment]
@damon-atkins. I wanted it to return false because otherwise an empty dictionary makes it looks like the conversion worked. There is another important difference. powershell_all is only attempting to make a dictionary from stdout (which is what Powershell attempted to json-ify in the first place). AFAICS cmd.powershell is trying to make a python dictionary from *all* of the output of cmd.run (even the non-jsonified stuff written stderr will be included in what cmd.run attempts to parse). That makes no sense to me.

**Comment by hrumph** [comment]
Everyone, I'm personally fairly happy with powershell_all. I do wonder if I should have left stdout in the dictionary just for good measure.

**Comment by damon-atkins** [comment]
if stdout has data when their is an error yes, but only included it when their is an error.  The small amount of testing I did indicated on error stdout was empty.  i.e. would it be useful when their is an error.

If `def powershell` needs fixing it should get fixed.   But that can happen outside of this PR. It needs @twangboy  thoughts.

Notice the doco is
`salt '*' cmd.run_all '$PSVersionTable.CLRVersion'`

What do you expect back from
`salt '*' cmd.powershell_all '$doesnotexist'`

**Comment by hrumph** [comment]
@damon-atkins,
here's a test.
```
salt  '010101' cmd.powershell lsl
```

The result is
```
010101:
    'lsl' is not recognized as an internal or external command,
    operable program or batch file.
```
As I thought, the content ot stderr went into the output of cmd.run. It then follows that if we did the same thing with cmd.powershell, cmd.powerhshell will try to treat that same error output as json, which it simply isn't. The result of cmd.run could combine some perfectly fine json in stdout and some errors in from stderr that are not json. We shouldn't assume that this combined output is all json and attempt to read it into a dictionary.

**Comment by hrumph** [comment]
OK because I don't think anyone is listening, I am going to give a concrete example:

First consider the powershell code
```
$(@('item1','item2') ; $host.ui.WriteErrorLine('some error'))
```
If first creates a Powershell Array, then it writes out an error, but I put it inside $() to make it a single unit of execution.

Now when I run
```
salt -t 20 '000004' cmd.run "\$(@('item1','item2') ; \$host.ui.WriteErrorLine('some error'))" shell=powershell
```
I end up with
```
000004:
    some error
    item1
    item2
```
As I epected the non-error output is combined with the error output.
Now when I add __| ConvertTo-JSON as follows:
```
salt -t 20 '000004' cmd.run "\$(@('item1','item2') ; \$host.ui.WriteErrorLine('some error')) | ConvertTo-JSON" shell=powershell
```
I get a combination of things. First I get the error message (which belongs in stderr), and I get the json array, (which belongs in stdout).
```
000004:
    some error
    [
        "item1",
        "item2"
    ]
```

Now If were to treat this all as a single unit of json data, which cmd.powershell will do, obviously it won't parse. That's why when I run:
```
salt -t 20 '000004' cmd.powershell "\$(@('item1','item2') ; \$host.ui.WriteErrorLine('some error'))"
```
I get an empty list (because that's how the exception is handled).

Now if run __powershell_all__, I get the following output
```
000004:
    ----------
    pid:
        6368
    result:
        - item1
        - item2
    retcode:
        0
    stderr:
        some error
```
This is exactly what I think should happen. Stdout is treated as json and a parse is attempted of that and stderr is left alone. I believe that cmd.powershell sould do the same. That being said I don't want to fight about it but at the very least I think that the different of behaviour of powershell_all is 100% defensible.

**Comment by damon-atkins** [comment]
I would test if stdoutput is empty before `json.loads(stdoutput)`  and set `result` to `False` or Empty String or `None`.  Saves having a python stack trace `json.loads(stdoutput)`  when we know it does not like it.

```
C:\>powershell "$donotexist |  ConvertTo-JSON"

C:\>powershell "$donotexist"

C:\>c:\salt\salt-call.bat cmd.run_all  --out=json shell=powershell "$donotexist"
{
    "local": {
        "pid": 12864,
        "retcode": 0,
        "stderr": "",
        "stdout": ""
    }
}

C:\>c:\salt\salt-call.bat cmd.powershell_all "$donotexist"
[ERROR   ] cmdmod.powershell_all Error converting PowerShell JSON return
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\modules\cmdmod.py", line 3331, in powershell_all
    response['result'] = json.loads(stdoutput)
  File "c:\salt\bin\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "c:\salt\bin\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\salt\bin\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
local:
    ----------
    pid:
        23136
    result:
        False
    retcode:
        0
    stderr:

C:\>c:\salt\salt-call.bat cmd.powershell "$donotexist"
[ERROR   ] cmdmod.powershell Error converting PowerShell JSON return
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\modules\cmdmod.py", line 3091, in powershell
    return json.loads(response)
  File "c:\salt\bin\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "c:\salt\bin\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\salt\bin\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
local:
    ----------
```

**Comment by damon-atkins** [comment]
> @damon-atkins. I wanted it to return false because otherwise an empty dictionary makes it looks like the conversion worked.

  So does False as its a valid result,  I would lean towards `None` or not setting result.

**Comment by hrumph** [comment]
@damon-atkins, yes you are right. I hadn't thought about it. Also None is a valid result too, because
the result of 
```
[DBNull]::Value | ConvertTo-JSON 
```
is __null__, which will translate into __None__ in Python.
In light of the valid points you have just raised, I will do the following

- I will test to see if stdout is empty. If this is the case then "result" will not be added to the the dictionary.
- If an exception is raised, once again, "result" simply will not exist as a key in the dictionary.
- I will try to make it abundantly clear why we don't have a "result" key, instead of using None or False
because this may not seem sensible at first glance.

**Comment by damon-atkins** [comment]
Sounds Good.

**Comment by twangboy** [comment]
@damon-atkins The reason "powershell returns {}" could be a question for @whiteinge. In my opinion, if there was an error converting JSON, then a `CommandExecutionError` should be raised. Additionally, return types should not be mixed (str, bool, dict, etc), though it seems to happen a lot. So, if a function is supposed to return a dict, it either returns a dict or raises an error.

**Comment by whiteinge** [comment]
Agreed. Raising an exception sounds reasonable since the function couldn't do what it was being asked to do (produce json).

**Comment by damon-atkins** [comment]
> Agreed. Raising an exception sounds reasonable since the function couldn't do what it was being asked to do (produce json).

The following is valid
```
C:\>c:\salt\salt-call.bat cmd.run_all  --out=json shell=powershell "$donotexist"
{
    "local": {
        "pid": 12864,
        "retcode": 0,
        "stderr": "",
        "stdout": ""
    }
}
```
If an empty string is return then result should not be defined within the dict and also an error should not be raised.   If stdin contains something and json.loads(stdoutput) fails I see no issue with it raise an error.  To help hrumph  out, which error should it raise?   It needs to return the stderr so things can be debugged.

**Comment by hrumph** [comment]
WHen you said that a return should have one type, I think that most people agree, but the problem is that json can parse to about a dozen or so types (including dict, bool, and NoneType) and all of the types are used to represent JSon data. Therefore if we insist on one type, then, IMO, that type should be dict, and people using the function will be expected to  coax their powershell functions into always producing dicts (which shouldn't be a huge problem [since dict is the usual type for powershell commandlets] although this strikes me as a bit on the anal side). So I propose to do the following with the __powershell_all__ function:

- Raise an error when stdout is non-empty and the parse fails
- Have result set to False when stdout is the empty string.
- Raise an error when the parse succeeds but the result type is not __dict__
- In the remaining cases result will be a Python __dict__ representing a json dictionary object.
.

@twangboy are you ok with this? If you are not, then tell me _exactly_ what the behaviour of powershell_all should be because I'm having trouble getting any consensus about anything.

**Comment by damon-atkins** [comment]
Sample return dict
```
local:
    ----------
    pid:
        23136
    result:
        <result is not included in the dict if no data return in
             stdout which allows for $doesnotexist see above examples>
    retcode:
        0
    stderr:
```

```
If stdout contains data and json.loads(response) fails with an error, raise an error as suggest, may be 
        raise CommandExecutionError(
            'Invalid JSON returned',
            info=response
        )
```

Someone may wish to output something to stderr (examples have been given above by @hrumph )
Someone may wish to set the retcode to non-zero

I believe the above give the best coverage.   And hopefully meets @hrumph "use" needs.

**Comment by hrumph** [comment]
@damon-atkins, @twangboy is implying that a polymorphic result type is not acceptable. I'm sort of indifferent. I just want to get this done now.

**Comment by hrumph** [comment]
I have made the changes I proposed. I am not sure that I really like returning False when stdout is empty. I think I should have just raised an except there too, but let's hear what others think. Take a look at the code. I tried hard to document it well.

**Comment by hrumph** [comment]
Now, where there is empty stdout it raises an exception. (No more returning false)

**Comment by damon-atkins** [comment]
Hi @hrumph,  you may have not notice, whiteinge, has thumb up my above response.

**Comment by hrumph** [comment]
@damon-atkins In any case I think that __dict__ is a mistake. It should be __list__ if we are going to settle on a single data type. BTW Yes you are right about what you said. 

_HOWEVER_. Consider the following

```
dir testdir
```
It testdir is empty. this, will cause stdout to be empty [as you are pointing out I believe]. (We will not get an empty list even though this is logically what we would hope to see)

If testdir has exactly one item, then we will get a dictionary representing a single directory item (not a singleton list even though this is logically what we would like to see).

If testdir has multiple items, then we will get a list of dictionaries each one representing a dictionary item (which is what we would hope to see).

What we can do then is as follows:
- If stdout is empty, return an empty list
- If stdout is not empty and the parse results in a non-list item, then create a singleton list with that item as the sole member.
- If stdout is not empty and the parse results in a list, then leave it alone.

This will be better than what you are proposing, because this way salt will be regularising the results in a way that will be beneficial 99% of the time. 

I'm interested in hearing what you have to say to this.

**Comment by damon-atkins** [comment]
result inside the dict can be any type.  However I can see where you are  from what a pain, that dir for example at a high level becomes an array when their is more then one item.

For example list_pkgs as the option of "versions_as_list=False"

Only thing I can think of is add an option like force_list=False
if the high level data type is not a list it placed inside a list which will only contain one item of the return data.  This will give the caller the power.

**Comment by damon-atkins** [comment]
Hi @hrumph  @twangboy  @whiteinge please have a look at the code in https://github.com/saltstack/salt/pull/41294#issuecomment-302848572

**Comment by hrumph** [comment]
OK, so here we are again. I have allowed the polymorphism again. I have added the force_list paramater (default value False). If force_list is false and stdout ends up being empty, you will get an exception, because I somewhat disagree with result not being set in the return dictionary. OTO if force_list is true, the result will be the empty list. Likewise when force_list is true, if the Python object you get is not a list, the result will be a singleton list based on that object. I think this happiest compromise we can get.

Since "result" always exists in the return dictionary, we can (in the future) use this function to make a new cmd.powershell function.

@Twangboy I think this is one situation where polymorphism is completely forgivable. I hope you can be persuaded to agree.

**Comment by hrumph** [comment]
@damon-atkins, I have done what you wanted 90%, but I did not allow result be non-existant. Instead I throw an exception. I really feel that that is the right choice.

**Comment by damon-atkins** [comment]
run_all does not through an exception.  Hence base on its behaviour and fact someone might what to check that something does not exist that why the code allows for an empty result instead of through an exception.  See that the others think.

**Comment by hrumph** [comment]
@damon-atkins, @whiteinge, I have changed it again to try to make everyone happy. Now when stdout is empty the value of result will be None (I still outright don't like the idea of not setting result to anything).

There is also a new field in the result dictionary called "result_none_reason". This field only appears when result is None and it's value is one of two strings

- no_ps_output
- null_ps_output

Is everyone happy now?

**Comment by damon-atkins** [comment]
See https://github.com/saltstack/salt/pull/41294#issuecomment-302765111 which has whiteinge approval.   i.e. He is happen for result to be left out of the dict. 

foo=powershell_all(...)
result=foo.get('result', None) # use can choose the default when result is not included in the dict

And if your keen on Failing when no result the add failhard_empty=False when True you raise an error on empty result instead of a list or not setting result inside the dict depending on force_list..

e.g.
 ```
# powershell sometimes provides a dict when the results is a single item, and then
 # when the result is more than one item it provides a list of dict.  force_list allows the user to
 # get consistent outcome of a list in those cases.

 force_list = salt.utils.is_true(force_list)
 failhard_empty = salt.utils.is_true(failhard_empty)
 # response contains stdout, stderr, retcode, pid from calling run_all we
 # remove stdout which contains json text or is empty and add result if there is data

 # Handle the valid case of no data found. i.e. stdout is empty
 if not response['stdout']:
     if failhard_empty:   
         raise CommandExecutionError(
             "cmd.powershell_all empty result from Powershell output.",
             info=response
            )
     response.pop('stdout')  # no longer needed
     if force_list:
         response['result']=[]  # empty list i.e. no data elements
         return response
     else
        # we do not set response['result'] so the caller knows that no data was found
        return response

 # Handle the valid case we have json data in stdout 
 # If we fail to parse json from stdout we will raise a CommandExecutionError
 try:
     response['result'] = json.loads(stdoutput)
 except Exception:
     raise CommandExecutionError(
         "cmd.powershell_all cannot parse Powershell json output.",
         info=response
         )
 response.pop("stdout") # no longer needed

 if  force_list and type(result) is not list:
     response['result']=[response['result']]

 return response
```

**Comment by hrumph** [comment]
@damon-atkins it doesn't fail on no result any more. Instead of having the result_none_reason key, I'll add a paramater called something like "no_output_result" with default None

**Comment by hrumph** [comment]
@damon-atkins well you win then. I've done it mostly your way now. No __return__ key gets added now when force_list is false and the powershell output is empty. I haven't added failhard_empty. I can't imagine anyone using it. If @Twangboy or one of the salt maintainers says it's necessary then I'll add it.

**Comment by cachedout** [comment]
@hrumph Thanks for being patient while we sort this one out. :]

We do need some minor lint errors fixed and then I think this will be ready for a final review: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/11355/violations/file/salt/modules/cmdmod.py/

**Comment by hrumph** [comment]
@cachedout lint test has passed.

**Review by twangboy — APPROVED** [review]

**Comment by hrumph** [comment]
Thanks @Twangboy (sorry if I got a bit snotty but no one was agreeing on _anything_). Next step, after this gets merged, is to rewrite cmd.powershell, making it a wrapper for cmd.powerhsell_all. @damon-atkins do you want to do this?

**Comment by twangboy** [comment]
@hrumph It's frustrating communicating via GitHub with often many days between responses... I understand.

**Comment by cachedout** [comment]
Glad we appear to finally have things all sorted out here. As best I can tell from this discussion, this is ready to go in so I'm going to go ahead and merge it and we can continue the discussion wrt follow-up work either here or (preferably) in a new GitHub issue. Thanks very much to everybody for your help on this one and to @hrumph for taking the time to get this one ready to go.

**Pull request merged**
