### PR TITLE
fixed backslash literal bytestring for file.replace

### LINKED ISSUE #61944: [BUG] file.replace backslash_literal=True causing bytes issues
**Description**

file.replace with backslash_literal throwing the following traceback. 

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 218, in call
    ret["return"] = self.minion.executors[fname](
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/file.py", line 2566, in replace
    repl.replace("\\", "\\\\") if backslash_literal else repl,
TypeError: a bytes-like object is required, not 'str'
```

**Setup**

add a file to the filesystem at /tmp/test witht eh contents

```
a
b
c
```

and run `salt-call file.replace path="/tmp/test"   pattern='c' repl='c-replaced'  backslash_literal=True -l debug`

you will get the following tracepath

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 218, in call
    ret["return"] = self.minion.executors[fname](
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 10, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1201, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/file.py", line 2566, in replace
    repl.replace("\\", "\\\\") if backslash_literal else repl,
TypeError: a bytes-like object is required, not 'str'
```

looks like the `"\\"` and `"\\\\"` should be bytes not strings. 

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [x] VM running on a cloud service, please be explicit and add details
- [x] container (Kubernetes, Docker, containerd, etc. please specify)
- [x] or a combination, please be explicit
- [x] jails if it is FreeBSD

  

**Expected behavior**
the replace happens. or doesn't. but doesn't return an error.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
❯ salt-call --versions
Salt Version:
          Salt: 3004.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Mar 15 2022, 12:22:08)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: pop 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.15.8-76051508-generic
        system: Linux
       version: Pop!_OS 20.04 focal

```
</details>

### PR DESCRIPTION
**Pull request by emmadionne1**
### What does this PR do? 
see issue for details

### What issues does this PR fix or reference?
Fixes: #61944

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by nicholasmhughes** [comment]
re-run full all

**Comment by nicholasmhughes** [comment]
re-run pr-alma-8-x86_64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-centosstream-8-x86_64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-centosstream-8-x86_64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-freebsd-130-amd64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-arch-lts-x86_64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-fedora-35-x86_64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-centos-7-x86_64-py3-pycryptodome-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-centos-7-x86_64-py3-pycryptodome-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-amazon-2-x86_64-py3-pytest

**Review by nicholasmhughes — APPROVED** [review]

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
