### PR TITLE
Fix static requirements

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title

### CODE REVIEW

**Review by Ch3LL — COMMENTED** [review]
Why are we removing 3.7 for windows?

**Comment by s0undt3ch** [comment]
> Why are we removing 3.7 for windows?

Because we don't use 3.7 on windows, either testing or packaging, so one less requirements file to maintain.

**Review by whytewolf — APPROVED** [review]

**Comment by Ch3LL** [comment]
Pedro will re-add the requirements in a follow up PR

**Comment by s0undt3ch** [comment]
Follow-up PR https://github.com/saltstack/salt/pull/63247

**Pull request merged**
