### PR TITLE
Migrate boto_rds to boto3

### PR DESCRIPTION
**Pull request by rterbush**
### What does this PR do?

Migrates boto_rds states and modules to boto3 and enables support for things like StorageType.
### What issues does this PR fix or reference?
#26784

Possibly #23607
### New Behavior

Support for setting StorageType as well as many other AWS RDS features found in newer API.
### Tests written?

No

This started off being an attempt to add support for StorageType and ended up being a full helping of Boto3 and Salt. I am sure there is some more work to do here but would like to offer this in hopes that I can take away some feedback to make it an acceptable PR. Green on Python and Salt module/state development.

### CODE REVIEW

**Comment by ryan-lane** [comment]
This is great! Thanks for working on this. It looks good to me.

**Comment by rterbush** [comment]
Amended PR with a couple of bugs I have found. Working in my environment.

**Comment by cachedout** [comment]
This looks pretty good but I am reluctant to put a dependency change into a point release. Could you resubmit this against the develop branch?

**Comment by cachedout** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rterbush** [comment]
@cachedout I'm happy to look at what it takes to submit this against develop. Might take me a bit to get setup with a develop system that I can test against since I am not running it. No idea what the differences might be.

**Comment by rterbush** [comment]
@cachedout I've looked at this code in develop and will work on providing a PR.

Just an observation that there is some new functionality in modules/boto_rds.py between 2016.3 and develop that I will port to Boto3. The method, modify_db_instance() cannot possibly work in develop given it is passing parameters that are unsupported in boto2 and also unsupported when providing "None" as a value, which this does.

I'll fix up and resubmit.

**Comment by rterbush** [comment]
Will revive this after some more work.

**Pull request closed without merging**
