### PR TITLE
Signal handling improvements

### PR DESCRIPTION
**Pull request by s0undt3ch**
This PR improves signal handling a little bit but not enough to fix the hanging issue with the test suite.

It requires the develop HEAD of salt-testing.

**Let's carefully review and test this before merging**

### CODE REVIEW

**Comment by cachedout** [comment]
Doesn't look like things went so well with the tests here. :-/

**Comment by s0undt3ch** [comment]
One failed the other aborted. Just retriggered.

**Comment by s0undt3ch** [comment]
But yes, this should only be merged into master when we at least have the same behavior/test failures currently present on develop.

**Comment by s0undt3ch** [comment]
These test failures seem more reasonable... No?

**Comment by cachedout** [comment]
Go Go Jenkins!

**Pull request merged**
