### PR TITLE
Document Windows default for ipc_mode

### PR DESCRIPTION
**Pull request by marbx**
### What does this PR do?
Resolves documentation task https://github.com/saltstack/community/issues/32 of Working group https://github.com/saltstack/community/projects/4

### CODE REVIEW

**Review by twangboy — APPROVED** [review]

**Comment by twangboy** [comment]
@markuskramerIgitt  Please rebase this or resubmit this against the master branch

**Comment by markuskramerIgitt** [comment]
What did I wrong?

I should have avoided to:
"Merge branch 'develop' into doc_ipc_mode_Windows", I assume?

I simply leave these branches alone?

I will try to resubmit or rebase tomorrow

**Comment by twangboy** [comment]
@markuskramerIgitt You didn't do anything wrong. We're changing our branching strategy. All PR's will now go into master. Details explaining the strategy and the reasons for it are in the Salt Enhancement Proposal (SEP).
https://github.com/saltstack/salt-enhancement-proposals/pull/20/files

**Comment by markuskramerIgitt** [comment]
Closing because opened https://github.com/saltstack/salt/pull/55039

**Comment by markuskramerIgitt** [comment]
I tried to rebase, found 3500 merge conflicts and no way out.

I will only try again with step-by-step instructions.

**Pull request closed without merging**
