### PR TITLE
Port #49377 to master

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
Port #49377 to master

Honor make_master also if master already exists
If make_master: True in a map, it'll be applied to other minions, even
if the master already exists.

### CODE REVIEW

**Comment by cmcmarrow** [comment]
re-run all

**Comment by cmcmarrow** [comment]
re-run full all

**Comment by cmcmarrow** [comment]
Hi, @DmitryKuzmenko. Thanks for the PR master port. If you need help with test writing please message me on slack `saltstackcommunity.slack.com` my user name is `Chad McMarrow`. I will be happy to have a zoom meeting with you and show you how to write and setup tests.

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
