### PR TITLE
minor tweaks to master initialization / EventReturn

### PR DESCRIPTION
**Pull request by mattp-**
### What does this PR do?
- moved creating a masterMinion object for EventReturn into the child proc to avoid loader churn (funcs, grains, etc). Theres no reason for this to happen in parent proc then get pickled down post fork. This should improve master startup time.
- move EventReturn creation to _after_ ReqServer, since it emits events on initialization.

### What issues does this PR fix or reference?
n/a

### Tests written?
Not really applicable to this change.

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by DmitryKuzmenko — APPROVED** [review]
Sounds reasonable, looks good.

**Comment by rares-pop** [comment]
I see you did this in 'develop', but all releases can benefit from it. Can you add some flags so this can be backported?

**Comment by mattp-** [comment]
@rares-pop I am not a salt employee / unable to add flags to PRs. maybe @DmitryKuzmenko can help?

**Comment by DmitryKuzmenko** [comment]
To decide what branch this change should go to we need to see the bug description and reproducing steps i.e. a properly formed issue.
Here I just see the code that looks correct for me. I'm not sure how critical is that.
So @mattp- could you please describe the original issue you're fixing here or create a separate GH issue to track this?

@saltstack/team-core could anybody please confirm I'm right here?

**Comment by mattp-** [comment]
@DmitryKuzmenko wasn't actually a bug, behavior should be the same before as after, just something I uncovered tuning our test suite. i think given the usual rules just sticking it in develop for neon and not backporting makes sense.

**Comment by DmitryKuzmenko** [comment]
@mattp- thank you for explanation. Since this touches major business code and it doesn't fix anything critical I see no reason to speed it up to the current releases. Let it leave in develop and show it as good as it looks.

**Review by dwoz — CHANGES_REQUESTED** [review]
@mattp- All too often simple changes like these cause hard to track down bugs. If this is truly a bugfix or is going to get back ported into any stable branch it should have some kind of regression test.

**Comment by mattp-** [comment]
@dwoz it isn't a bugfix, just a minor optimization; i think we can disregard / remove the bugfix backport label. I'm not exactly sure how you would write a test to assert the change, or if you had one it would be very useful

**Comment by waynew** [comment]
Hey @mattp- looks like it's been a while here - would you be able to rebase this on the `master` branch?

One thought about how you could test this is by mocking some of the calls and ensuring that the calls happen in the correct order. I'd probably make liberal use of comments in the test explaining why the order is important.

Does that make sense?

**Comment by waynew** [comment]
@mattp- hope you're doing well - do you have any interest in driving this to completion?

**Comment by sagetherage** [comment]
closing as abandoned

**Pull request closed without merging**
