### PR TITLE
Add test to query results of /jobs call in api

### PR DESCRIPTION
**Pull request by Ch3LL**
### What does this PR do?
Add test to check the results of the query to /jobs using the salt-api.

This will help to make sure the following issues don't occur again:

https://github.com/saltstack/salt/issues/41100
https://github.com/saltstack/salt/issues/40845

NOTE: This will fail until this is merged:  https://github.com/saltstack/salt/pull/41102

### Tests written?

Yes

### CODE REVIEW

**Comment by Ch3LL** [comment]
Go Go Jenkins!

**Review by cachedout — APPROVED** [review]

**Comment by cachedout** [comment]
@Ch3LL Please rebase this so we can see if this passes now.

**Comment by Ch3LL** [comment]
@cachedout k done

**Comment by rallytime** [comment]
Nice work @Ch3LL

**Pull request merged**
