### PR TITLE
Update os_family grain to be "Suse" instead of "SUSE" for localemod

### PR DESCRIPTION
**Pull request by rallytime**
Also update some of the test functions to be a little more clear

### CODE REVIEW

**Review by boltronics — COMMENTED** [review]
The tests look good to me. I don't understand why SUSE is being changed to Suse though. I can understand SUSE or SuSE, but not Suse - especially when we've got RedHat (not Redhat).

Edit: I get that `os_family` is probably already used that way so this is just a fix, but should we be doubling down on the wrong capitalisation instead of fixing it everywhere where it's wrong?

**Comment by damon-atkins** [comment]
@boltronics  The gain returns Suse  and this code changes fixes looking for the wrong value in localemod.py

**Comment by boltronics** [comment]
@damon-atkins Thanks, but why would the grain return `Suse` and not `SUSE` or `SuSE`? Neither the company name or distribution is named `Suse`. Shouldn't the root of the problem (where the grain is initially set in `salt/grains/core.py`) be fixed instead to avoid further confusion?

There aren't that many references throughout the codebase to 'Suse', so it wouldn't be that hard to fix properly.

**Comment by damon-atkins** [comment]
Most likely the grain has return that value for some time.  And people would have developed states with that case lettering.  So the impact is larger than salts code.

**Comment by boltronics** [comment]
Could be (in which case the above patch makes sense for point releases of existing major releases), but fixing this properly is a once-off change that can be thrown in the release notes and deployed in the next major release. Better than living with the problem forever, no?

**Comment by rallytime** [comment]
@boltronics Those are good questions and thank you for bringing them up. However, engineers from the SUSE team were the ones who change the value of the grain in #35415. Given that they were the ones who changed and normalized the grain there, and have been making subsequent fixes in the tests similar to this one, I think we should leave this as-is.

**Comment by boltronics** [comment]
Thanks @rallytime. It doesn't explain the logic behind the inconsistent naming though. I suspect they were  just aiming for consistency with 2015.8 and 2016.3, so did some digging and found 0e8550e2.

Looks like Thomas added it back in the original commit - where `RedHat` and `VMware` and `MacOS` were also used for `os_family` in the same commit. Seems it was originally a typo or an oversight, as opposed to something the SUSE team originally desired.

**Pull request merged**
