### PR TITLE
use salt.utils.which to determine the path to sysctl

### PR DESCRIPTION
**Pull request by adamjacobmuller**
This is more of a request for comments than perhaps an actual pull request.

Does anyone see any inherent issues with doing this?

### CODE REVIEW

**Comment by cachedout** [comment]
I don't see any real issue with this. There's possibly a tiny amount more overhead with this approach, but not much. Out of curiosity, what's your reasoning behind wanting to make this change?

**Comment by AdamJacobMuller** [comment]
when salt is executed on some platforms via cron, it does not always have a complete PATH set.

I'm actually kind of thinking that reading and writing via /proc/sys would be a significantly better fix, and a significantly cleaner module in general, thoughts?

**Comment by cachedout** [comment]
@AdamJacobMuller Hmm, I'm not completely sure. I see where you're going with that idea, but at the same time it's nice to have a system utility which abstracts away any quirks and provides a unified interface to the manipulation of kernel settings.

**Comment by cachedout** [comment]
@AdamJacobMuller Did you see my above comment? Just trying to determine if we want to keep this PR open, etc. Thanks.

**Comment by AdamJacobMuller** [comment]
I did, apologies, been very busy so not had a ton of time to consider this.

I am going to kill this PR and will reopen one that implements my suggestion of writing/reading from /proc/sys directly and can discuss more there.

entirely unrelatedly, is the salt jenkins/github integration stuff documented anywhere (if its custom)? really digging the status in here.

**Pull request closed without merging**
