### PR TITLE
Don't assume package installation order.

### PR DESCRIPTION
**Pull request by s0undt3ch**
Additionally pep8 when installed using wheel, reports the version
together with the name.

```
Collecting pep8
  Using cached pep8-1.6.2-py2.py3-none-any.whl
Obtaining Blinker from git+https://github.com/jek/blinker.git#egg=Blinker
  Cloning https://github.com/jek/blinker.git to /tmp/tmpmWlmv7/venv/src/blinker
Obtaining SaltTesting from git+https://github.com/saltstack/salt-testing.git#egg=SaltTesting
  Cloning https://github.com/saltstack/salt-testing.git to /tmp/tmpmWlmv7/venv/src/salttesting
Installing collected packages: pep8, Blinker, SaltTesting
  Running setup.py develop for Blinker
  Running setup.py develop for SaltTesting
Successfully installed Blinker SaltTesting pep8-1.6.2
```

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Pull request merged**
