### PR TITLE
Features/28154 denied keys

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
Feature implementation for #28154

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Fixes #30570

**Comment by s0undt3ch** [comment]
@meggiebot I believe this needs to be backported to 2016.3

**Comment by cachedout** [comment]
This looks right to me. I have also asked @thatch45 to review it just for a second opinion.

**Comment by basepi** [comment]
:thumbsup:

**Comment by thatch45** [comment]
Looks good

**Pull request merged**
