### PR TITLE
"dictionary changed size during iteration" issue fixed in config.py for ...

### PR DESCRIPTION
**Pull request by vladislavPV**
...salt-cloud

iterating over dict fixed "RuntimeError: dictionary changed size during iteration" issue

### CODE REVIEW

**Comment by jfindlay** [comment]
@vladislav-jomedia, will you rebase your changes on the latest develop branch?  There are a glut of test failures coming from old code in that branch, thanks.

**Comment by vladislav-jomedia** [comment]
Hello , 
I cant find how to add labels , so  can you add "BUG" label for me 
Without this fix you will not be able to create vms on AWS using salt-cloud 
salt 2014.7.1 (Helium)
Tx

**Comment by jfindlay** [comment]
@vladislav-jomedia, we usually reserve bug labels for issues that aren't pull requests.  The only reason I haven't merged this pull request is that I am not familiar with the affected code enough to feel confident merging it myself.  I'm sure @thatch45 will be around momentarily. :-)

**Comment by jfindlay** [comment]
@vladislav-jomedia, also if this is a legitimate bug, then it needs to be applied to the 2014.7.  You can either resubmit a pull request against that branch or we can backport this one.  Since you've already submitted the pull request and it's ready to go, I'll add the backport label.

**Comment by thatch45** [comment]
Please backport to 2014.7

**Comment by vladislav-jomedia** [comment]
Thank you guys, 
Sorry about not committing to helium branch , I am new in this field

**Comment by thatch45** [comment]
No worries :)
We are just communicating how we do things, thanks for the bugfix!

**Comment by jfindlay** [comment]
@vladislav-jomedia, no problem, you rock!

**Pull request merged**
