### PR TITLE
Fix azure cloud service

### PR DESCRIPTION
**Pull request by flavianh**
Creating several virtual machines under the same cloud service works. You have to specify a port number in the map file for SSH that had to be different for every machine.

TODO:
- Deletion was not tested.
- show_instance was based on cloud services and should be renamed "show_service". A real show_instance has to be written from conn.get_role

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by traxair** [comment]
BTW I tested deletion and it does not work. I think this is linked to the second issue with show_instance/show_service but I can't find exactly where anything fails

**Comment by techhat** [comment]
@traxair there's some lint issues with trailing whitespace that need to be cleaned up.

I'm happy to merge this now, since you didn't actually touch deletion (unless I'm missing something), unless you want to work on that first.

**Comment by traxair** [comment]
May I leave the two last issues on deletion and show_* to you guys? I'm happy with the changes I made, I can keep going on what I was doing, plus you'll be faster than I am, since I've cleared out the way

**Comment by thatch45** [comment]
@traxair your code is impeccable! Thanks! Again some lint issues, but they are just trailing whitespace, so I can clean them up!

**Comment by traxair** [comment]
Thanks! I wish I could have integrated it properly into your tests, but tests for azure were kind of sparse

**Comment by thatch45** [comment]
Yes, we need to bolster those tests, hence the breakage, I am sure! I will mark this fix to be backported to our next release

**Comment by traxair** [comment]
Careful, it's still missing two features, do you want me to open issues for that?

**Comment by techhat** [comment]
@traxair, please do. Small pull requests tend to be a lot easier to manage anyway.

**Comment by thatch45** [comment]
Please do! a number of the clouds are still just bare bones, we need to be able to get them all filled out!

**Pull request merged**
