### PR TITLE
Port #50460 to master

### PR DESCRIPTION
**Pull request by alexey-zhukovin**
### What does this PR do?
Port #50460 to master

### CODE REVIEW

**Comment by cdalvaro** [comment]
When will this PR be merged?

**Comment by cdalvaro** [comment]
Any news here??

**Review by Ch3LL — CHANGES_REQUESTED** [review]
this will require a changelog and test coverage

**Comment by Ch3LL** [comment]
we will need a changelog and test coverage to get this one over the line.

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
