### PR TITLE
Fix git state identity lacking of user expansion #48461

### PR DESCRIPTION
**Pull request by babs**
### What does this PR do?

This PR fixes a lack of user expansion on the identity attribute of git states.

### What issues does this PR fix or reference?

Fix issue #48461

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by rallytime** [comment]
Hi @babs - Can you fix these lint violations?

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/23140/violations/

**Comment by babs** [comment]
Hi @rallytime, should I squash the commits ?

**Comment by rallytime** [comment]
Hi @babs - You can squash them if you like and I personally think that is cleaner, but you don't have to. 

However, you've still got some lint violations. ;)

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/23169/violations/

**Review by terminalmage — APPROVED** [review]

**Comment by rallytime** [comment]
@babs Any luck fixing these lint errors?

**Comment by babs** [comment]
sorry missed the message. reports ends up in 404 is there a way to restart the job ?

**Comment by rallytime** [comment]
@babs Restarted :)

**Comment by babs** [comment]
@rallytime thanks, I'll take a look once finished.

**Comment by babs** [comment]
@rallytime should be good now. next time, I'll try to wake up my brain before committing

**Comment by rallytime** [comment]
@babs _Almost_ there. There are still some lint errors, which are involved around PY3 compatibility. The details of how to fix it are in the console output here: https://jenkinsci.saltstack.com/job/pr-lint/job/PR-48462/13/console

LMK if you have any questions.

You can also run the same lint file that these tests run locally by following [these docs](https://docs.saltstack.com/en/latest/topics/development/conventions/style.html#pylint-instructions) and using the `.testing.pylintrc` file in the salt clone.

**Comment by babs** [comment]
@rallytime the thing is the issue regarding py3 comes from lines like those ones:
```
06:52:07 [salt linting] -        identity = map(os.path.expanduser, identity)
06:52:07 [salt linting] +        identity = list(map(os.path.expanduser, identity))
```
Except in my patch the line is ` identity = map(os.path.expanduser, identity)`, no surrounding `list` nor `from salt.ext.six.moves import map` at the top.

I can rewrite it as a list comprehension but I'm curious of what is currently rewriting those lines and adding the irrelevant map.

**Comment by rallytime** [comment]
I think it's just the linter's way of trying to provide a helpful solution since `map` changed in Py3. The way you have it now looks good.

**Pull request merged**
