### PR TITLE
[develop] Merge forward from fluorine to develop

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title.

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by terminalmage — APPROVED** [review]

**Comment by terminalmage** [comment]
This looks OK, but there are some test failures that should be investigated.

**Review by twangboy — APPROVED** [review]
Windows stuff looks good

**Comment by s0undt3ch** [comment]
This PR is now waiting for https://github.com/saltstack/salt/pull/51084 to be merged

**Comment by s0undt3ch** [comment]
As talked with @dwoz, I'm merging this PR.

**Pull request merged**
