### PR TITLE
A more graceful salt-master exit + Multiprocessing logging

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by cachedout** [comment]
Way awesome!

**Comment by cachedout** [comment]
@s0undt3ch A git bisect is leading me to believe this is throwing a stacktrace when launching the master with `-d`.

```
mp@silver ~/devel/salt % sudo salt-master -d                                                                                                            (git)-[25ef141...|bisect] 
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
    p.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 143, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
    p.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 143, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
    p.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Error in sys.exitfunc:
```

**Comment by s0undt3ch** [comment]
I believe something was  changed because of a similar stack trace.... And I believe the code is in parsers... Ie, if we're forking, shutdown multiprocessing logging and set it up once detached...

**Comment by s0undt3ch** [comment]
This is happening in current develop?

**Comment by rallytime** [comment]
Yeah.

**Comment by s0undt3ch** [comment]
OK. I'll have another look at it...

Could one of you open an issue, link to this one and assign it to me please? ... I'm on my phone...

**Comment by rallytime** [comment]
Done: https://github.com/saltstack/salt/issues/30247

Feel free to change those labels if I got them wrong.

**Comment by s0undt3ch** [comment]
Thanks!

**Pull request merged**
