### PR TITLE
Add team-suse to CODEOWNERS file for zypper files

### PR DESCRIPTION
**Pull request by rallytime**
This addition will enable automatic reviews from team-suse for PRs that touch the zypper files.

### CODE REVIEW

**Comment by rallytime** [comment]
@saltstack/team-suse - this is just a the start of what you "own" and will be auto-requested for reviews. Please feel free to add your team to other files as you see fit. For example, I imagine the `yumpkg` module and the kubernetes files come to mind.

**Comment by isbm** [comment]
While xfs/btrfs modules are also ours, as per conversation, I think we are fine to keep an eye on the entire `/*`.

**Review by isbm — COMMENTED** [review]
While xfs/btrfs modules are also ours, as per conversation, I think we are fine to keep an eye on the entire /* being a backup of yours. Thanks for doing this!

**Comment by rallytime** [comment]
OK, I added those files here as well. I need to implement the "mirroring" of the team-core files on the bot itself. I probably won't be able to do that until next week. So this change will just make sure `team-suse` is specifically requested to review changes to these files.

**Review by meaksh — COMMENTED** [review]
Hey @rallytime , `salt/**/*snapper*` should be also set to `team-suse`. Thanks!

**Comment by isbm** [comment]
And `*pkg*`.

**Comment by rallytime** [comment]
Ah, yeah good call @isbm and @meaksh! How does that look now?

**Pull request merged**
