### PR TITLE
Update the mongodb module with a new update_one() method

### PR DESCRIPTION
**Pull request by remyd1**
### What does this PR do?

This PR aims to provide a way to update a mongodb document from a salt module/method. It would be useful in case of ext_pillar with reactor kind of things.
### What issues does this PR fix or reference?

It just adds the method "update_one" for this module:
https://github.com/saltstack/salt/blob/develop/salt/modules/mongodb.py
### Tests written?

No

### CODE REVIEW

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Hi @remyd1 

There are a few lint warnings here. Would you mind please fixing them up? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/4648/violations/file/salt/modules/mongodb.py/

**Comment by remyd1** [comment]
Updated!

**Comment by cachedout** [comment]
@remyd1 Thank you so much for the quick response! I'll try to get this in today. Much appreciated.

**Comment by remyd1** [comment]
BTW, I am wondering if it is not a better choice to use the same delimiter as in update_one() specification, that is to say something like:
http://api.mongodb.com/python/current/api/pymongo/collection.html#pymongo.collection.Collection.update_one

```python
result = db.test.update_one({'x': 1}, {'$inc': {'x': 3}})
```

It is more a json like syntax or a python like function with "," separator.

In my case, I am doing in the salt module:
```bash
salt '*' mongodb.update_one '{"_id": "my_minion"} {"bar": "document_content"}' mycollection <user> <password> <host> <port> <database>
```
Note, there is only a whitespace (could be many) as a separator.

It is not very important, and the code to modify is just the regexp.

What do you think ?

IMHO, I prefer without the comma, but the real function in pymongo takes one, so ?

**Comment by rallytime** [comment]
This looks good as it is.

**Pull request merged**
