### PR TITLE
[PY3] Add unicode_literals to cache and cli modules

### PR DESCRIPTION
**Pull request by terminalmage**

### CODE REVIEW

**Comment by damon-atkins** [comment]
Hi @terminalmage keep in mine that the cmd line arguments in PY2 need to be converted to Unicode.

**Comment by rallytime** [comment]
@terminalmage There are some related test failures here.

**Comment by terminalmage** [comment]
@damon-atkins That will be done in due time once salt.utils.parsers is updated.

**Comment by terminalmage** [comment]
@rallytime tests updated

**Comment by rallytime** [comment]
@terminalmage Looks like there are still 2 tests failures on PY3:

- integration.output.test_output.OutputReturnTest.test_output_pprint
- integration.output.test_output.OutputReturnTest.test_output_raw

**Comment by terminalmage** [comment]
Oh, derp, of course those two tests wouldn't have a `u` before the unicode string on Python 3. This should be fixed with the next test run.

**Comment by rallytime** [comment]
re-run py

**Comment by rallytime** [comment]
re-run py3

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
re-run py

**Comment by terminalmage** [comment]
This has been rebased to include the PR which fixes the test daemon timeouts.

**Comment by rallytime** [comment]
re-run py

**Pull request merged**
