### PR TITLE
Key fingerprints

### PR DESCRIPTION
**Pull request by amendlik**
### What does this PR do?
1) Adds a wheel function to return the master public key fingerprint
2) Adds a hash_type argument to these fingerprint functions:
 - wheel.key.finger
 - wheel.key.finger_master (new)
 - modules.key.finger
 - modules.key.finger_master

### What issues does this PR fix or reference?
None

### Previous Behavior
1) There was no way to call a wheel module to return the master fingerprint.
2) The purpose of a key fingerprint is to allow comparison to verify the identity of a remote system. The behavior of the functions mentioned above produces a fingerprint according to the algorithm set by the hash_type configuration option. The problem with this approach is that, if the master and minion have different hash_type settings, it is impossible to compare the key fingerprints and, thus, verify the identity of the system.

### New Behavior
1) A new wheel.key.finger_master function has been added to return the master key fingerprint.
2) All the functions mentioned above still default to the algorithm specified by the hash_type configuration option. They now also accept an optional hash_type argument to override the default. This allows fingerprints to be calculated with a specific algorithm, regardless of the setting.

### Tests written?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
The linter picked up a couple of concerns here: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/7726/violations/file/salt/key.py/

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@amendlik Did you see my comment above about the lint issues? We need those fixed before we can merge this. Please let me know if you have questions.

**Comment by amendlik** [comment]
@cachedout I saw that these changes were incompatible with the RAET fingerprinting class, but since that class doesn't work anyway, I wasn't sure how much effort to put into it. Do you still want me to work on that?

**Comment by cachedout** [comment]
@amendlik No need at all. I made the quick changes myself and everything is merged in now. We're set! Thanks. :]

**Pull request merged**
