### PR TITLE
fix dimensiondata, gce unit test certs on MacOS

### PR DESCRIPTION
**Pull request by jfindlay**
### What does this PR do?

fix failing unit tests, ping @tonybaloney
### What issues does this PR fix or reference?

similar to #32921
### Tests written?

Yes

### CODE REVIEW

**Comment by jtand** [comment]
@jfindlay There are some lint failures :)

**Comment by tonybaloney** [comment]
The CRT paths are actually coded into libcloud (unlike #32921) but it requires that the curl-ca-bundle port is installed - https://www.macports.org/ports.php?by=library&substr=curl-ca-bundle

**Comment by jtand** [comment]
@jfindlay https://github.com/apache/libcloud/blob/trunk/libcloud/security.py#L51-L52 is the crt path he's referring to.

**Comment by jfindlay** [comment]
@jtand, @tonybaloney: updated.  See also https://github.com/saltstack/salt-jenkins/pull/165.

**Pull request merged**
