### PR TITLE
[merge jam] #49648 - Fix salt.module.pdbedit with samba 4.8

### PR DESCRIPTION
**Pull request by waynew**
### What does this PR do?
ports #49648

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by waynew** [comment]
I guess technically this isn't a merge forward at this point - I realized that the code was already there, whoops! Anyway... I added some tests, and then I did a bit of refactoring, though, not 100% sure if we want the results of that refactoring 🤔 

Can change the one test if we don't want that change.

**Comment by waynew** [comment]
re-run centos7, fedora33, macosx-mojave

**Comment by waynew** [comment]
re-run macosx

**Comment by waynew** [comment]
re-run centos7-x86_64

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
