### PR TITLE
saltclass: Reference classes with globs

### PR DESCRIPTION
**Pull request by awerner**
### What does this PR do?

This PR extends the saltclass external pillar and master_tops to allow globbing when including classes.

This feature was influenced by the `meta`-directory of modern salt-formulas, that use reclass and custom modules to include the `meta/<integration>.yml` files to provide integration from one formula for others.

### What issues does this PR fix or reference?

New PR , as #47080 could not be reopened.

### Previous Behavior

Example saltclass:

```yaml
classes:
  - roles.app
  - roles.nginx
```

### New Behavior

```yaml
classes:
  - roles.*
  - services.*.meta.monitoring
```

### Tests written?

Yes

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by rallytime** [comment]
@awerner This has some lint failures: https://jenkinsci.saltstack.com/job/pr-lint/job/PR-49070/2/warnings52Result/

Can you fix those up?

**Review by gtmanfred — APPROVED** [review]
This looks good to me, but I would really like to have @olivier-mauras review it too.

**Review by cachedout — CHANGES_REQUESTED** [review]
There are some lint errors here which need to be resolved, please:

https://jenkinsci.saltstack.com/job/pr-lint/job/PR-49070/2/warnings52Result/new/

**Comment by cachedout** [comment]
I just went ahead and fixed the lint errors directly.

**Comment by awerner** [comment]
@cachedout thank you, am on vacation until 30th and only quite seldom in front of a monitor :)

**Review by cachedout — APPROVED** [review]

**Comment by s0undt3ch** [comment]
Port to master https://github.com/saltstack/salt/pull/56758

**Pull request merged**
