### PR TITLE
Initial Azure ARM driver commit

### PR DESCRIPTION
**Pull request by techhat**
### What does this PR do?

As it says.
### What issues does this PR fix or reference?

None.
### Previous Behavior

No ARM driver.
### New Behavior

ARM driver.
### Tests written?

Nay.

### CODE REVIEW

**Comment by cachedout** [comment]
Linter caught a possible issue: http://166.78.178.63:8080/job/PR/job/salt-pr-lint-n/1644/violations/file/salt/cloud/clouds/azurearm.py/

**Comment by techhat** [comment]
Thanks @cachedout, fix pushed.

**Comment by techhat** [comment]
Waiting on testing from @shorawitz.

**Comment by techhat** [comment]
Okay, pending Jenkins, this should be ready to be merged.

**Pull request merged**
