### PR TITLE
Added execution functions to work with base64 encoded files; added state function to manage base64 encoded files

### PR DESCRIPTION
**Pull request by whiteinge**
Still needs:
- [ ] permission handling on destination file
- [ ] tests
- [ ] better minion-side Pillar integration
- [ ] better master-side Pillar integration

Existing minion-side Pillar integration looks like this:

``` yaml
write_base64_encoded_string_to_a_file:
  file.decode:
    - name: /tmp/new_file
    - encoding_type: base64
    - encoded_data: |
        {{ salt.pillar.get('path:to:data') | indent(8) }}
```

Existing master-side Pillar integration looks like this:

``` yaml
path:
  to:
    data: |
      {{ salt.hashutil.base64_encodefile('/path/to/binary_file') | indent(6) }}
```

### CODE REVIEW

**Comment by whiteinge** [comment]
One way to integrate Pillar is to just add a `contents_pillar` argument (ala file.managed). It would be a two-line change. Another way would be to introduce something like a ``pillar://path:to:data`` construct. I prefer the latter but it deviates from existing Salt patterns (e.g., `contents_pillar`) and it also steals the ``pillar://`` namespace which may be unfortunate if we ever decide to add better Pillar-based file transfers (i.e., without resorting to base64 encoding).

Thoughts?

**Comment by whiteinge** [comment]
I think the best way to better master-side integration is to wrap this with an ext_pillar module. Syntax could look like this:

```yaml
ext_pillar:
  - base64_encode:
      path:to:data1: /path/to/file1
      path:to:data2: /path/to/file2
```

Available via a `pillar.get('path:to:data2')` call, where `data2` would be clobbered if it already existed in Pillar.

**Comment by thatch45** [comment]
Yes, I think that we should stick with contents_pillar, and lean on the file.managed stuff as much as possible

**Comment by whiteinge** [comment]
Roger that. I can't re-use file.managed for this but I will add a
contents_pillar to the new file.decode state module.

**Comment by whiteinge** [comment]
More commits incoming...

**Comment by thatch45** [comment]
@whiteinge what is the status here?

**Comment by whiteinge** [comment]
Swamped with business-needs work. Still need to get this done.

**Comment by cachedout** [comment]
Bump @whiteinge. Just looking for a status update here. Thanks!

**Comment by whiteinge** [comment]
Thanks for the ping. I'm realistically four weeks out before I can return to this. :-/

I'll reopen this at that time.

**Comment by baniobloom** [comment]
@whiteinge Hello, any progress on this feature?

**Comment by whiteinge** [comment]
@baniobloom I don't have any time to work on the bullets listed above. That said the execution and state module are perfectly functional. I've opened #26690 with the `contents_pillar` addition. We can augment and add features to these functions over time.

**Pull request closed without merging**
