### PR TITLE
Remove PendingDeprecationWarning

### PR DESCRIPTION
**Pull request by johnvox**
### What does this PR do?
It avoid future deprecated function

### What issues does this PR fix or reference?
None (except pytest's testinfra warning issue)

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by dwoz** [comment]
This should resolve #51398

**Review by terminalmage — APPROVED** [review]
This will require a backport. Do we know where this popped up the first time? Was it just in the RC?

**Comment by garethgreenaway** [comment]
This should also resolve #51666

**Comment by Oloremo** [comment]
Looking forward for this to be merged.

**Comment by waynew** [comment]
FWIW, the `raw` keyword doesn't exist in older distributions of msgpack, which is why some of those builds are failing. Will we have dropped support for those older versions by the time `develop` is released?

**Comment by s0undt3ch** [comment]
A simple `try/except TypeError` falling back to the old kwargs might be enough to maintain compat with older versions.

**Comment by waynew** [comment]
FWIW, `encoding='utf-8'` is found in test/integration/__init__.py

Not sure if there are any other places we would want to fix this.

**Comment by waynew** [comment]
I'm pretty sure that this has been solved by https://github.com/saltstack/salt/pull/55354

**Pull request closed without merging**
