### PR TITLE
Don't double encode s3 paths

### PR DESCRIPTION
**Pull request by benjumanji**
As s3.query already knows how to quote paths, don't quote the passed in
path: s3.query will handle it.

### What does this PR do?
Prevents double urlencoding s3 paths in s3fs fetch code.

### What issues does this PR fix or reference?
#53539
### Previous Behavior
Paths double encoded leading to 404s for legit bucket items

### New Behavior
Paths encoded just the once, items are located as one might expect

### Tests written?
Nope

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by benjumanji** [comment]
I'd be happy to do something with testing if someone could point me to the right test infrastructure. I've been using salt for about 3 days.

**Review by garethgreenaway — APPROVED** [review]

**Comment by benjumanji** [comment]
What's the standard mo for out of date branches? is it rebase or merge?

**Comment by benjumanji** [comment]
I already have patches in my provisioning for salt-master so I don't mind if this gets merged one way or the other but it would be cool if someone could point me to a similar test that I could copy. AFAICT there are _no_ extant tests for `s3fs` which makes it a little challenging for a drive-by contributor to add the test case that it seems I need to get this merged.

**Comment by benjumanji** [comment]
@garethgreenaway is there any likelihood of this getting merged without further work?

**Comment by benjumanji** [comment]
This is one of the weirder interactions I've had on github. This is a 3 line change, obviously fixes a bug, all status checks pass and was reviewed reviewed super promptly. I've had three contributors interact with it and yet I'm stuck in a cycle of checking once every few days, rebasing and generally talking to myself with no idea if it will ever be merged.

**Comment by benjumanji** [comment]
Ok. I've learnt my lesson. Don't bother with upstream, it's a total waste of time.

**Comment by garethgreenaway** [comment]
@benjumanji Apologies for the delay and thank you for the PR!  We definitely want to get this merged but need some tests associated with the change, I'll comment in a bit with some suggestions.

**Comment by garethgreenaway** [comment]
@benjumanji I've added a test, to ensure that the path argument that is passed along to the `s3.query` function is the same one that is passed into `_get_file_from_s3` function.  One the tests pass, we can go ahead and merge this in.  Thanks for your patience.

**Review by dwoz — APPROVED** [review]

**Comment by waynew** [comment]
@garethgreenaway / @benjumanji is there a way to test this and verify that a file with a space in the name works fine with this change?

I did some code archaeology and discovered that was the reason that `quote` was added in the first place. I'd like to be sure that this change doesn't affect that case, at least!

**Comment by garethgreenaway** [comment]
@waynew Updated the test to include a test to ensure URLs with spaces are quoted properly.

**Review by waynew — APPROVED** [review]

**Pull request merged**
