### PR TITLE
[saltstack/salt#31194] Fix issue of running multiple salt-api instances.

### PR DESCRIPTION
**Pull request by kstreee**
- Change return value from 'True' to '**virtualname**' in rest_cherrypy/**init**.py
  The **virtualname** value must be set as name of salt-api instance, thus the code try to get the instance name from **init**.py's directory name.
- Change setting **virtualname** logic because the rest_tornado has a same issue with the rest_cherrypy.
- Typo, 'orig_sesion' to 'orig_session' in rest_cherrypy/app.py

### CODE REVIEW

**Comment by kstreee** [comment]
I have no ideas how to fix the failure of 'X default', ( https://jenkins.saltstack.com/job/salt-pr-rs-cent7-n/12574/ ).

```
03:07:33 Connection to 104.239.240.171 closed.
03:07:33 Error: There was a profile error: Command "ssh -t -t -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -p 22 root@104.239.240.171 '/tmp/.saltcloud-17e05dce-cb67-4c89-9ab7-ba65b32f11d2/deploy.sh -c /tmp/.saltcloud-17e05dce-cb67-4c89-9ab7-ba65b32f11d2 -ZD git v2014.7.0'" failed. Exit code: 1
03:07:33  * ERROR: Failed to run install_centos_git_deps()!!!
03:07:33  * DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
03:07:34 ----------------------------------------------------------------------------------------------------------------------------------------------------------------
03:07:34  * Failed execute command. Exit code: 1
03:07:34 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
03:07:34 
 * Failed to bootstrap the cloud minion
```

It looks like that some connection fails on the build server, but I don't know how to handle this.

**Comment by whiteinge** [comment]
The try...except in my JSON file example was to catch if the JSON file didn't exist, had missing data, or was malformed. This try...except doesn't do much since there are very few things that will trigger the except -- perhaps only when `__file__` is an empty string. How about this instead?

```python
os.path.abspath(__file__).rsplit('/')[-2] or 'rest_cherrypy'
```

Please also add documentation underneath the 'configuration' section. Something like:

```restructuredtext
.. versionadded:: Boron
   Multiple instances.

This module supports multiple running instances by copying the entire
`rest_cherrypy` parent folder and renaming it. The configuration block in the
Salt Master config must match the name of the folder in order for salt-api to
detect and start it.
```

**Comment by kstreee** [comment]
Sure, I will commit about documentations for it, and code fix soon. Thank you for your advice.

**Comment by kstreee** [comment]
I committed an additional documentation of running multiple salt-api instances and code-fix which is reviewed by @whiteinge, thanks.
Please review it.

**Comment by whiteinge** [comment]
Looks good. :+1: Thanks for the changes!

**Pull request merged**
