### PR TITLE
Allow saltutil.refresh_modules to wait for completion

### PR DESCRIPTION
**Pull request by cachedout**
Also added raet support to eventlisten as well as added functionality to connect to to an existing minion.

### CODE REVIEW

**Comment by cachedout** [comment]
Go go jenkins

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
@cachedout Gotta be exactly like that ^^ for jenkins to trigger a new build. :)

**Comment by cachedout** [comment]
We've gotta find a new method for that. :]

**Pull request merged**
