### PR TITLE
#22080 part 1: Addition of Python 3 compatible ipaddress module

### PR DESCRIPTION
**Pull request by The-Loeki**
First drop of #22080 solution
See how 
https://bitbucket.org/kwi/py2-ipaddress/
works out
(the code in `py2-ipaddress` is in much better shape than `ipaddress`)

### CODE REVIEW

**Comment by The-Loeki** [comment]
What can I do against the massive lint fails? The code is, aside from patches, almost verbatim Python 3.4, including said fails, and I think we'd better keep it that way?

**Comment by The-Loeki** [comment]
Also, the module is licensed under the Python 2.0 license, do I need to add that to `COPYING` and if yes, what's the choice for summary text in there?

**Comment by techhat** [comment]
@The-Loeki see the comments at the top of `salt/ext/ssl_match_hostname.py` for an example of how to handle this.

**Comment by The-Loeki** [comment]
Thanks @techhat, this should be better then :+1:

**Pull request merged**
