### PR TITLE
Cleanup of virtual_err

### LINKED ISSUE #21185: Unused modules with error messages are logged
The somewhat undocumented feature of returning a tuple from the `__virtual__` function in modules describing why the module could not be loaded causes error logging even if the module was not going to be used. I'm not sure how widely this feature is used, but at least the new ipmi and nacl modules use it, and cause error logging on develop.

### PR DESCRIPTION
**Pull request by jacksontj**
Since now logging this, we've noticed its a bit noisy. To cut down on that I've changed the log level to debug. In addition, I changed the loader to keep a dict of mod -> error so that the caller (if so interested) can look up the error later. I switched caller and minion to use this new API. Now if you send a job to a minion with a module that isn't loaded you get a return like:

```
'mod_name'' __virtual__ returned False: <error message here>

```

Fixes #21185 
Replaces #21246 (since we want this in 2015.2)

### CODE REVIEW

**Comment by cachedout** [comment]
Agreed that this needs to get into 2015.2 asap. Looks like a test may need to be updated. (I haven't looked too closely though.) I'll try to get the test fixed today unless you get to it first. :]

**Comment by jacksontj** [comment]
@cachedout easy fix. We have 2 "test" modules (to verify merging-- which we'll kill off later). The problem was that we had "test" as a failed virtual load, but it actuall *had* loaded a test module. So I added in the "loaded modules" tracking so we can give a better error message-- and we'll need to enforce the no-merge policy we plan on adding in ;)

**Comment by jacksontj** [comment]
@cachedout This next one also fixes the fun and exciting globals packing problem :)

**Comment by jacksontj** [comment]
Looks like *lots* of people are writing into __opts__... I'll remove that commit from this PR, we'll have to add some code so we can nicely deprecate it-- but thats no reason to hold up the nicer error messages :)

**Comment by jacksontj** [comment]
@cachedout There we go, all ready for merging :)

**Pull request merged**
