### PR TITLE
Fix unable to lazyload slack_notify module

### PR DESCRIPTION
**Pull request by deuscapturus**
### What does this PR do?

Allow this module to run
### What issues does this PR fix or reference?

No reference.  amazing.  I guess nobody has tried to use it.
### Previous Behavior

I don't know that it ever worked.
### New Behavior

At least the module loads.  I don't know if it will work beyond that.
### Tests written?
- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by s0undt3ch** [comment]
I'm not the author of the module but `__virtual name__` is something the is set to rename the module once loaded within the salt loader context.

How did it fail to load? Was there any additional error message?

**Comment by deuscapturus** [comment]
Without this change this is the output you get for any of these module commands:
```
[root@centos7 ~]# salt-call -l debug slack_notify.list_rooms
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: centos7.tcowan-laptop
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'centos7.tcowan-laptop', 'tcp://192.168.200.1:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (8064)
[DEBUG   ] Setting zmq_reconnect_ivl to '8064ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'centos7.tcowan-laptop', 'tcp://192.168.200.1:4506', 'aes')
[DEBUG   ] Initializing new SAuth for ('/etc/salt/pki/minion', 'centos7.tcowan-laptop', 'tcp://192.168.200.1:4506')
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'centos7.tcowan-laptop', 'tcp://192.168.200.1:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Error loading module.ifttt: IFTTT Secret Key Unavailable, not loading.
[DEBUG   ] Error loading module.victorops: No VictorOps api key found.
[DEBUG   ] Error loading module.rh_service: Cannot load rh_service module on RedHat >= 7
[DEBUG   ] Error loading module.win_status: Cannot load win_status module on non-windows
[DEBUG   ] Error loading module.tls: PyOpenSSL version 0.10 or later must be installed before this module can be used.
[DEBUG   ] Error loading module.glusterfs: glusterfs server is not installed
[DEBUG   ] Error loading module.vsphere: Missing dependency: The vSphere module requires the pyVmomi Python module.
[DEBUG   ] Error loading module.nacl: libnacl import error, perhaps missing python libnacl package
[DEBUG   ] Error loading module.dockerng: Docker module could not get imported
[DEBUG   ] Error loading module.ipmi: No module named pyghmi.ipmi
[DEBUG   ] Error loading module.npm: npm execution module could not be loaded because the npm binary could not be located
[DEBUG   ] Error loading module.boto_cloudwatch: The boto_cloudwatch module cannot be loaded: boto libraries are unavailable.
[DEBUG   ] Could not LazyLoad slack_notify.list_rooms
'slack_notify.list_rooms' is not available.
```

**Comment by s0undt3ch** [comment]
This is the command you should use, remember that `__virtualname__` variable?
```
salt-call -l debug slack.list_rooms
```

**Comment by deuscapturus** [comment]
Ok.  Then I'll produce a pull request with documentation updates.

**Pull request closed without merging**
