### PR TITLE
Bump to pytest-salt-factories 0.905.x

### LINKED ISSUE #60201: [TEST FAILURE] MacOS proxy test failures
MacOS proxty tests started failing each time:

`tests.pytests.integration.proxy.test_simple.test_can_it_ping`
`tests.pytests.integration.proxy.test_simple.test_list_pkgs`

https://jenkins.saltproject.io/job/pr-macosx-catalina-x86_64-py3-pytest/job/PR-60200/3/#showFailuresLink
https://jenkins.saltproject.io/job/pr-macosx-mojave-x86_64-py3-pytest/job/PR-60200/4/#showFailuresLink

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title

### What issues does this PR fix or reference?
Fixes: #60201

### CODE REVIEW

**Comment by s0undt3ch** [comment]
re-run all

**Comment by s0undt3ch** [comment]
re-run all

**Comment by s0undt3ch** [comment]
re-run all

**Comment by s0undt3ch** [comment]
re-run all

**Review by cmcmarrow — APPROVED** [review]

**Review by Ch3LL — APPROVED** [review]

**Pull request closed without merging**
