### PR TITLE
add describe_vpcs and cache connection in __context__ in boto_vpc

### PR DESCRIPTION
**Pull request by mgwilliams**

### CODE REVIEW

**Comment by mgwilliams** [comment]
@jfindlay regarding all these failures... do the test cases not use the loader... and therefore have no `__context__`?

**Comment by thatch45** [comment]
it looks like the unit tests for this module just does not mock the context, so we will need to get that in

**Comment by jfindlay** [comment]
@mgwilliams, yes.  Unit tests are very basic and operate on plain, static code.  In particular loading magic has not happened, so they will need to define `__context__`, `__salt__`, etc.

```python
...
from salt.modules import boto_vpc
...
boto_vpc.__context__ = {}
...
```

**Comment by jfindlay** [comment]
@mgwilliams, looks like there's just one more test failure.

**Pull request merged**
