### PR TITLE
Cloud roster fixes

### PR DESCRIPTION
**Pull request by szviagintsev**
### What does this PR do?

Makes the cloud roster alive on 2016.3 and 2016.11. Tested on EC2 and GCE.

### What issues does this PR fix or reference?

#31005,  #40251

### Tests written?

No

### CODE REVIEW

**Comment by gtmanfred** [comment]
Please check the cloud roster in develop.

I have already made some of these changes to use the cache.cloud runner to do the matching instead of reading the files directly.

**Comment by sergeizv** [comment]
@gtmanfred I plan another PR on develop, but need some time for it as there are more issues to be addressed (like maintaining the cache index by cloud providers). This PR however does the job on the release branches.

**Comment by cachedout** [comment]
@sergeizv 2016.3 and 2016.11 are bugfix-only branches. Does this address an open GitHub issue?

**Comment by sergeizv** [comment]
@cachedout Each commit from this pull request is a bugfix, and together they aim to address #31005 on the release branches. I didn't get why #31005 was closed before this is merged, because the issues are still there. If the commit messages don't contain enough information on the problems they fix, I might provide more detailed descriptions of the issues in this PR or open another GitHub issue(s) for this (or #31005 might be reopened).

What would you suggest in this case?

**Comment by gtmanfred** [comment]
Can you try the roster in develop?

If that one works, i think the better option would be to backport the changes made there, instead of making extra changes here.

Thanks,
Daniel

**Comment by sergeizv** [comment]
@cachedout ok, I opened #40251 

@gtmanfred Yes, I checked it. The cloud roster in develop is buggy as well together with the cloud cache runner and today I'm going to submit a PR on that with some bits of this PR forward-ported. This PR targets 2016.3 and 2016.11 release branches and is limited to bugfixes. Back-porting the roster from develop (but it firstly needs to be fixed there) from my opinion is not in spirit of maintaining stable branches, as the roster has been rewritten there and does things in different way. But that's up to maintainers :)

**Review by gtmanfred — APPROVED** [review]

**Comment by cachedout** [comment]
@sergeizv Thanks for the detailed explanation! Thanks for helping us get up to speed and for filing the requested issue. I completely agree with your position. :]

**Review by cachedout — APPROVED** [review]

**Pull request merged**
