### PR TITLE
Tests for cloud GCE provider 

### PR DESCRIPTION
**Pull request by junckritter**
Adds basic test for Google Compute Engine, based on test for EC2. 
Related to #8754 and #20239

### CODE REVIEW

**Comment by thedrow** [comment]
:+1:

**Comment by thatch45** [comment]
@erjohnso please take a look.
@junckritter there are some little lint issues, I will get them

**Comment by erjohnso** [comment]
Awesome! Thanks for getting this started @junckritter and @rallytime!  I'm assuming over time we can work together to make it more comprehensive.

How often do you run the tests?

**Comment by junckritter** [comment]
My first PR :) I've just started with salt tests because I found out that salt cloud does not support some parameters of libcloud for GCE. So that would follow shortly.

**Comment by rallytime** [comment]
@erjohnso Usually the cloud tests run nightly, but I don't have Jenkins set up with the correct key information quite yet, since this is so new.

Thanks for diving in here @junckritter. I meant to write these ages ago, but I was struggling to get salt-cloud working with GCE (I think we were waiting on a newer version of libcloud, but that is out now.) I will add this to my list to make sure theses get running on the nightly cloud tests soon.

**Pull request merged**
