### PR TITLE
Fixed salt.runner test mode output

### LINKED ISSUE #54382: salt.runner test mode not working
### Description of Issue
If I run an orchestration with `salt.runner` notation and with `test=True` I get the following:
https://gist.github.com/Oloremo/5a1ab1f0dad78a62c920b0d8229cc265

To make it even worse - it has an exit code `0`.

Running the same with `test=False` works as expected. 

### Setup
My orchestration:
```
orch.runner.java:
  salt.runner:
      - name: state.orchestrate
      - parallel: False
      - kwarg:
          mods: orch/services/java
```

`orch/services/java`:
```
orch.java.install:
  salt.state:
    - tgt: '*'
    - sls:
      - formula.java
```

### Steps to Reproduce Issue
Create the orchestration with `salt.runner` and run it with `test=True`.

### Versions Report
Everything is on 2019.2.0

```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.6 (default, Aug 13 2018, 18:24:23)
   python-gnupg: 0.4.4
         PyYAML: 5.1.1
          PyZMQ: 18.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

### PR DESCRIPTION
**Pull request by Oloremo**
### What does this PR do?
Fixed the salt.runner execution with test=True

### What issues does this PR fix or reference?
Fixes: #54382

### Previous Behavior
Before this change salt.runner executed with test=True returned stackstrace: https://gist.github.com/Oloremo/5a1ab1f0dad78a62c920b0d8229cc265

### New Behavior
Now it returns a bit useless but correct output.

### Merge requirements satisfied?
- [?] Docs
- [YES] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [YES] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by cmcmarrow — CHANGES_REQUESTED** [review]
Hey, @Oloremo thanks for the PR! Looks like arch tests has failed. I don’t think arch failed because of your changes. Also Salt requites tests whenever code changes are made. Feel free to message me if you need help with tests.

**Comment by sagetherage** [comment]
Windows tests timed out, re-run all

**Comment by Oloremo** [comment]
@sagetherage Tests passed.

I tried to write a test for this one back in May and kinda failed and didn't have time since. :-(

**Comment by sagetherage** [comment]
@Oloremo no worries! thanks for trying! I will attempt to get some help on writing a test :)

**Comment by Oloremo** [comment]
@dwoz @cmcmarrow tests are green now yet there is still no tests for the bugfix itself

**Comment by Oloremo** [comment]
@cmcmarrow Just ping to highlight that:

1) There are no more failing tests
2) Tests added via courtesy of Wayne

**Comment by sagetherage** [comment]
@Oloremo cmcmarrow won't get to reviewing this today, but I have manually updated the labels and rebased against master.

**Review by cmcmarrow — APPROVED** [review]

**Comment by sagetherage** [comment]
@Oloremo we are looking into the failures on FreeBSD - seems to be global and not your PR.

**Pull request merged**
