### PR TITLE
Boto VPC state draft proposal

### PR DESCRIPTION
**Pull request by claudiupopescu**
I tested both present and absent, but only by name. Tags should work as well.
Not sure if this is the right way of doing it, but it works for my use case :)

### CODE REVIEW

**Comment by thedrow** [comment]
Ohh nice.
I'm gonna review this in a bit.

**Comment by jfindlay** [comment]
Thanks, @claudiupopescu, @thedrow.

**Comment by thedrow** [comment]
I don't think that the CIDER block is an optional attribute for VPCs.
In fact the VPC module does not allow you to omit it.

Note that while it is possible to create a VPC without a name using the module it should **not** be possible to do so with the state since we got to have an anchor to look for.

What happens if I specify a VPC name and change the tags?
If I add new tags then new tags should be added to the VPC and if I remove other tags they should be removed from the VPC.
Since states change **state** then the state of the existing VPC should be changed.

Attempting to create a new VPC with the same name and new tags might result in an error but on a second thought it is more likely to not result on an error since the name is just another tag.
This will cause problems since we use the name as an anchor and we'll get two existing VPCs instead of one.
This is another good reason to alter the existing properties of an existing VPC.

What happens if I change any other attribute? As it stands now, the state will fail. It should instead alter the current VPC's properties.
You can use the ```get_id()``` method (can be found at https://github.com/saltstack/salt/blob/develop/salt/modules/boto_vpc.py#L168) in order to search for a VPC.

Attempting to create a VPC with the same CIDER block will almost surely result in an error. We need to verify that and ensure that the error message is clear.

The present state output should be what the ```describe()``` method (found in https://github.com/saltstack/salt/blob/develop/salt/modules/boto_vpc.py#L1267) outputs.

What about Subnets, Table Routes, Network ACL and DHCP Options?
Are you going to implement those?
If not I might give it a shot over the weekend or the next one.

**Comment by jfindlay** [comment]
@thedrow, I don't have any opinions about that failure message, but don't let that prevent you from suggesting something better if you have it. :-)

**Comment by claudiupopescu** [comment]
Good points :)

1. What about changing the anchor to CIDR? I don't know yet if it is possible, but the CIDR is unique and and it can not be changed/edited.
2. I will update the code to use get_id(), thanks.
3. I plan to implement the remaining features but if you have time to jump in it is even better.

Now in regards to remaining implementations (subnets, routing, etc). I don't know if those should be in their own state (something like boto_vpc_subnet.py) or inside this one. What do you think?

**Comment by thedrow** [comment]
1. CIDR is not something that a user can remember off the top of his head. A VPC name tag is, on the other hand.
It is possible to use it as an anchor though.
2. Great
3. I'm not sure if I have the time. Let's talk closer to Friday and I'll see what I can do about it.

They should be in the same state since they are related to the VPC entity.
Much like the RDS state, you should be able to attach a subnet or a route table to a VPC, replace or remove it.
There are subnets elsewhere which are related to EC2 or other entities in AWS.

**Comment by claudiupopescu** [comment]
Sure, I will remove the IP prefix check from the state.
And using iptools might be a good idea. So this needs to be implemented in boto_vpc module. Will you do it?

Now about my latest commit, is that what you had in mind with an anchor?

**Comment by claudiupopescu** [comment]
Unfortunately is is not possible to alter tags after creating the VPC.
And it is not possible to obtain DNS details after creating the VPC.

So making sure that the VPC is in the desired state with the current version of boto is not possible.
Please correct me if I am wrong. Maybe I missed something...

If this is true then this state should be final, at least for VPC present and absent. Any thoughts?

**Comment by thedrow** [comment]
You can use https://github.com/boto/boto/blob/develop/boto/ec2/ec2object.py#L82 to add tags and https://github.com/boto/boto/blob/develop/boto/ec2/ec2object.py#L122 to remove tags.

**Comment by thedrow** [comment]
You are correct that obtaining a VPC by DNS details is not possible,
That's exactly why we use the name as an anchor.

**Comment by claudiupopescu** [comment]
I found those as well, problem is that I can't find how to use them when already having a VPC created.
The ec2object is returned only after creating the VPC according to their documentation. So if I lookup a VPC I will not get the ec2object. Any suggestions how to get past this?

As for DNS, I was referring to describe. How could one obtain the DSN details and return them in describe()? I didn't find get_dns or something like that in boto VPC.

Btw, the "Name" tag is actually the name of the VPC. If you use that as an anchor is the same thing as using VPC name as anchor. So renaming a VPC name will rename the "Name" tag as well (from AWS web console). That is the reason why I created a new tag "salt_id" and using that as anchor. This way if one would edit the name from web, it will not break the salt state if applied again. Am I on the right track? :)

**Comment by thatch45** [comment]
@claudiupopescu @thedrow lets get the tags in another PR and get this one in so that we have the foundation to work from!

**Pull request merged**
