### PR TITLE
Add appoptics returner.

### PR DESCRIPTION
**Pull request by pcn**
- Test based on the librato test

### What does this PR do?

Adds a returner for the appoptics platform.

### What issues does this PR fix or reference?
N/A

### New Behavior
The appoptics returner will provide return data to the appoptics platform.

### Tests written?

Yes

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @pcn. Thanks for this!

Would you mind fixing up the lint errors? They can be found here: https://jenkinsci.saltstack.com/job/pr-lint/job/PR-49066/1/warnings52Result/

**Comment by pcn** [comment]
Cool, I thought pylint guidance in the past was to use `%` formatting for logging messages, but this is low-volume, so I'm OK either way.

**Comment by pcn** [comment]
I don't think that codeclimate should be made happy at this point - the complexity of `_calculate_runtimes` seems to be about as simple as it can practically be.

The common code chunk in the librato and appoptics returners don't seem like they're enough to recommend refactoring - unless there's a better chunk of library code to achieve the same end?  Is there?

@cachedout let me know if I'm off-base about this. 

Thanks!

**Review by cachedout — APPROVED** [review]

**Comment by cachedout** [comment]
This is way cool! Do you have examples or screenshots of this in action? I'd love to see some.

**Comment by cachedout** [comment]
@pcn We use CodeClimate just as signposts to let us know if there's a better way. Oftentimes there isn't, as in this case, and that's just fine. :)

**Comment by pcn** [comment]
> This is way cool! Do you have examples or screenshots of this in action? I'd love to see some.

We'll get something pretty for it.

**Comment by terminalmage** [comment]
I have taken care of the backport for this PR. You can feel free to remove this from the `PRs to port to master` project.

**Pull request merged**
