### PR TITLE
Executors redesign and documentation

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
### What does this PR do?
* Redesigned executors to don't use classes. Thus now them look more understandable and simple.
* Implemented an ability to provide executors opts by command line and via API.
* Wrote documentation.

### What issues does this PR fix or reference?
#39054, #39055

### Tests written?
No

### CODE REVIEW

**Comment by DmitryKuzmenko** [comment]
@cachedout is 2016.11 the right place for this PR?
@rallytime could you please take a look to the docs? At least I didn't understood how to make `ref/executors/index.html` and `ref/executors/all/index.html` to have the correctly generated sidebar navigation menu opened in the current doc...

**Comment by cachedout** [comment]
@DmitryKuzmenko I would prefer that you make this PR against the develop branch.

**Comment by DmitryKuzmenko** [comment]
@cachedout I've rebased it and changed the base to develop.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
@DmitryKuzmenko I looked over your documentation changes and they look correct to me based on the other examples. I didn't see any build errors when I built the docs locally for your change, but I was having trouble viewing the docs for pretty much everything on the develop branch, so I think something else must be wrong with my setup.

**Review by cachedout — APPROVED** [review]

**Pull request merged**
