### PR TITLE
Preserve existing, unspecified network settings

### LINKED ISSUE #33006: Preserve unspecified, existing settings when applying `network.system` state
### Description of Issue/Question

When applying the `network.system` state, any unspecified settings are removed from /etc/sysconfig/network. If I _just_ want to set the hostname, I do not want to have to know and set every other networking setting.

### Setup
`hostname.sls`:
```
Set hostname:
  network.system:
    - hostname: foo.example.com
    - apply_hostname: True
```

### Steps to Reproduce Issue

Note in below output that the line `NETWORKING_IPV6=no` was removed.

`salt-call --local state.sls hostname`:
```
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** skipped ** latest already in cache u'salt://hostname.sls'
[INFO    ] Running state [Set hostname] at time 13:30:44.576415
[INFO    ] Executing state network.system for Set hostname
[INFO    ] Using existing setting -- Setting: networking Value: yes
[INFO    ] Executing command '/bin/hostname -f' in directory '/root'
[INFO    ] Executing command '/bin/hostname foo.example.com' in directory '/root'
[INFO    ] Executing command '/sbin/service network restart' in directory '/root'
[INFO    ] {'network_settings': '---  \n+++  \n@@ -1,3 +1,2 @@\n NETWORKING=yes\n-NETWORKING_IPV6=no\n-HOSTNAME=ip-172-31-44-123.ec2.internal\n+HOSTNAME=foo.example.com'                       }
[INFO    ] Completed state [Set hostname] at time 13:30:49.361969
local:
----------
          ID: Set hostname
    Function: network.system
      Result: True
     Comment: Global network settings are up to date.
     Started: 13:30:44.576415
    Duration: 4785.554 ms
     Changes:
              ----------
              network_settings:
                  ---
                  +++
                  @@ -1,3 +1,2 @@
                   NETWORKING=yes
                  -NETWORKING_IPV6=no
                  -HOSTNAME=ip-172-31-44-123.ec2.internal
                  +HOSTNAME=foo.example.com

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
```

### Suggested Patch
`git diff`:
```
diff --git a/salt/modules/rh_ip.py b/salt/modules/rh_ip.py
index 6132038..60f5d90 100644
--- a/salt/modules/rh_ip.py
+++ b/salt/modules/rh_ip.py
@@ -776,7 +776,7 @@ def _parse_network_settings(opts, current):
     # Normalize keys
     opts = dict((k.lower(), v) for (k, v) in six.iteritems(opts))
     current = dict((k.lower(), v) for (k, v) in six.iteritems(current))
-    result = {}
+    result = current

     valid = _CONFIG_TRUE + _CONFIG_FALSE
     if 'enabled' not in opts:
diff --git a/salt/templates/rh_ip/network.jinja b/salt/templates/rh_ip/network.jinja
index 4006b12..db9880a 100644
--- a/salt/templates/rh_ip/network.jinja
+++ b/salt/templates/rh_ip/network.jinja
@@ -1,4 +1,5 @@
 {% if networking %}NETWORKING={{networking}}
+{%endif%}{% if networking_ipv6 %}NETWORKING_IPV6={{network_ipv6}}
 {%endif%}{% if hostname %}HOSTNAME={{hostname}}
 {%endif%}{% if gateway %}GATEWAY={{gateway}}
 {%endif%}{% if gatewaydev %}GATEWAYDEV={{gatewaydev}}
```

### Versions Report
`# salt-call --local --versions-report`:
```
Salt Version:
           Salt: 2015.8.5

Dependency Versions:
         Jinja2: 2.2.1
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.22.1.el6.x86_64
         system: CentOS 6.7 Final
```

### PR DESCRIPTION
**Pull request by lorengordon**
### What does this PR do?
- When building the network configuration, retain any existing settings that are not explicitly specified by the user.
- Also adds support to the network template for the NETWORKING_IPV6 configuration setting.
### What issues does this PR fix or reference?

Fixes #33006
### Previous Behavior

Previously, unspecified network settings would be removed from the network configuration file.
### New Behavior

Adds a parameter, `retain_settings`, with a default `False` value. This default preserves prior behavior. If the user passes `retain_settings = True`, then existing network settings that are not otherwise specified in the state will be retained.
### Tests written?

No

### CODE REVIEW

**Comment by lorengordon** [comment]
I realized I could parameter-gate this if you would prefer to default to the current behavior. Maybe something like:

```
retain_settings = opts.get('retain_settings', False)
result = current if retain_settings else {}
```

**Comment by cachedout** [comment]
I think that config-gating this makes some sense, as you mention. Let's try that.

**Comment by lorengordon** [comment]
Ok, I'll work that out when I get back to a computer this afternoon.

**Comment by lorengordon** [comment]
@cachedout, what is the next version to be called? I'd like to add a note about the new param in the state doc.

**Comment by rallytime** [comment]
@lorengordon Carbon is the next feature release version.

**Comment by lorengordon** [comment]
@rallytime, thanks! Updated the note with the correct version.

**Pull request merged**
