### PR TITLE
 [develop] Properly deprecate template context data

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Removing deprecation warnings from salt/utils/args.py.  Ensuring allpreviously failing testes are working.  Updating various auth modules to ensure **kwargs in all auth functions.

### What issues does this PR fix or reference?
#35777 

### Tests written?
Yes.  Tests exist, one test updated.

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by garethgreenaway** [comment]
@cachedout Before that change one of the tests was failing, `integration.wheel.test_client.WheelModuleTest.test_cmd_sync`.
Looking close at the code I found a better approach.

**Review by terminalmage — APPROVED** [review]

**Comment by rallytime** [comment]
re-run py

**Comment by rallytime** [comment]
@garethgreenaway Something isn't quite right here. It looks like the tests are only running about 600-700 tests before they time out. I am not seeing this behavior on other recent PRs or the branch itself, so something in the code is causing trouble.

**Comment by cachedout** [comment]
^^ @garethgreenaway You're up. :]

**Comment by garethgreenaway** [comment]
re-run all

**Pull request merged**
