### PR TITLE
pylint #20885

### PR DESCRIPTION
**Pull request by jfindlay**

### CODE REVIEW

**Comment by jfindlay** [comment]
Backport to 2014.7.

**Comment by joehoyle** [comment]
@jfindlay as this was merged into `develop`I might be missing something, but how has this been backported? Shouldn't this have been merged into the ` 2014.7` branch?

**Comment by rallytime** [comment]
@joehoyle That was a note for us to backport this bug fix to 2014.7. Since you made your original pull request against develop, that's where the pull request was merged. 

Typically we like feature work done in the develop branch, and then bug fixes should be submitted against the branch where the bug occurs. In this case, that was 2014.7. You can check out the documentation on how to do that here: http://docs.saltstack.com/en/latest/topics/development/contributing.html

However, if a bug fix comes in against develop and we know that is should have been against an earlier branch, then we'll mark it for backporting so that the bugfix can be in all of affected branches. Does that help to answer your question?

**Comment by joehoyle** [comment]
@rallytime ahh I see - in that case shall I open a pull-request against `2014.7` with my fix? Want to make it easy as possible for you folks to get the fix in :)

**Comment by rallytime** [comment]
@joehoyle Not this time! The pull request linked above does that already. But it is definitely helpful to keep that in mind for future contributions. And, we're definitely more than happy to answer any questions you might have on the matter. :)

Thanks again for this contribution!

**Comment by joehoyle** [comment]
Oh sorry, didn't see your created the PR already! thanks

**Comment by rallytime** [comment]
No worries!

**Pull request merged**
