### PR TITLE
[master] Acme state/module features and a bug fix.

### PR DESCRIPTION
**Pull request by jeffclay**
#### Acme State
Added `dns_plugin_propogate_seconds` option to cert().
Added option to replace an existing staging/test certificate with a production cert.

#### Acme Module
Added `dns_plugin_propogate_seconds` option to cert(). This was previously in the doc string but not actually coded anywhere.
Added revoke() with optional reason.
Added delete().

### What issues does this PR fix or reference?
Fixes:
https://github.com/saltstack/salt/issues/63700
https://github.com/saltstack/salt/issues/64686

### Previous Behavior

1. `dns_plugin_propogate_seconds` only existed in doc strings.
2. After creating a certificate using `test_cert` flag then removing the flag, the result was nothing happening due to:
   1.  Acme state does check to see if cert exists and if it does it just checks if it needs renewed. No consideration for replacing a staging certificate. https://github.com/saltstack/salt/blob/75269c4ae22cce7cef1e681e2b1625368d6e18f5/salt/states/acme.py#L104 
   2. Acme module did not have capability to revoke or delete a certificate.

### New Behavior

1. `dns_plugin_propogate_seconds`  exists in Acme state and module
2. Acme state has new bool option `replace_staging` that will revoke and delete a staging certificate as long as "STAGING" is in the cert issuer dictionary and `test_cert` is no longer requested.
3. Acme module has new `revoke` capability which will delete a cert after revocation due to the `--non-interactive` cmd switch.
4. Acme module has new `delete` capability which deletes certificates. (No need to call this after revoke in sls state or Acme state, just seemed like a natural thing to add along with `revoke`.)

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [X] Docs
- [X] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by jeffclay** [comment]
I'm new to writing tests, used chatgpt 4 to help with these, please review them for accuracy and relevance.

**Comment by garethgreenaway** [comment]
@jeffclay Thanks for the PR, looks like pre-commit tests are failing.  Did you install pre-commit locally so it's able to run when you commit the changes?

**Comment by jeffclay** [comment]
> @jeffclay Thanks for the PR, looks like pre-commit tests are failing. Did you install pre-commit locally so it's able to run when you commit the changes?

I had, but was getting errors on unrelated weird stuff like mercurial dependencies. I'll see if I can't figure it out. I had hoped the tests would pass in a known-working environment.

**Review by dwoz — COMMENTED** [review]
@jeffclay Needs the conflicts resolve, preferably by re-basing. Otherwise it looks good.

**Comment by jeffclay** [comment]
i managed to really bork this. going to delete and try again.

**Pull request closed without merging**
