### PR TITLE
Initial rework of grafana_datasource

### PR DESCRIPTION
**Pull request by vodik**
Started hacking on grafana_datasource, since my workplace does use it internally. Not happy with it, nor is it fully tested, but its something.

Mainly hoping to get some feedback on where and how to improve it, where it should go, and how it fits in to #29648

### CODE REVIEW

**Comment by cachedout** [comment]
@anlutro Can you take a look here and provide feedback?

**Comment by vodik** [comment]
Thanks, appreciate it.

**Comment by anlutro** [comment]
Without knowing the internals of `salt.utils.http.query` that well, I thought you had to pass the `data` kwarg instead of `params` for passing POST data?

**Comment by cachedout** [comment]
@vodik Did you see the feedback from @anlutro here?

**Comment by vodik** [comment]
@cachedout yeah, just low on free time. Looking into it now.

**Comment by vodik** [comment]
@anlutro good catch.

If I was to add some unit tests to this, is there any good documentation/examples to follow?

**Comment by rallytime** [comment]
Hi @vodik - there is a getting started tutorial for our test suite [here](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html) and there are links at the bottom of that page for more detailed docs of various portions of the test suite, including a link to how to write unit tests for Salt.

Please let us know if you have any questions there!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@vodik It looks like the tests are failing. Could you have a look? https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/6755/

**Comment by vodik** [comment]
Hey, so I haven't forgotten about this, I'm hoping to get back to this PR by the end of the week.

I'm currently busy working on/with the Jenkins salt modules/states, trying to flush our a few things (looking to add support for orchestrating credentials, executors, and plugins).

**Comment by cachedout** [comment]
@vodik I really appreciate the follow-up. Hopefully we can get this one in soon!

**Comment by cachedout** [comment]
Hi @vodik. Just checking with you again here. :]

**Comment by cachedout** [comment]
Hi @vodik. Checking with you here again. Please let me know if you have time to work on this or if it would be better to close it until you have time to get back to it. Thanks!

**Comment by vodik** [comment]
Yeah, I don't have enough time to work on this as the moment. My focus at work has shifted away from this at the moment.

And I think it might need deeper reworking. It failed on Grafana 4.

**Pull request closed without merging**
