### PR TITLE
Master webconfig settings

### LINKED ISSUE #48792: Feature-Request:  add the ability to use Set-WebConfiguration command set to win_iis
### Description of Issue/Question

The [win_iis](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.win_iis.html) module needs the ability to use set-WebConfiguration from the [webadministration PowerShell module](https://docs.microsoft.com/en-us/powershell/module/webadministration/?view=win10-ps). 

The win_iis state module should also reflect this change.

This is to allow setting items like `/system.webServer/security/authentication/anonymouseAuthentication -name 'userName'` 

This will allow much wider ability to configure the web services within IIS.

### PR DESCRIPTION
**Pull request by Akm0d**
### What does this PR do?
Merge https://github.com/saltstack/salt/pull/49399 from neon into master.
Resolves https://github.com/saltstack/salt/issues/48792

### CODE REVIEW

**Comment by Akm0d** [comment]
re-run windows2016

**Comment by Akm0d** [comment]
re-run windows2019

**Comment by Akm0d** [comment]
re-run centos7

**Comment by Akm0d** [comment]
re-run debian10

**Review by waynew — APPROVED** [review]

**Comment by Akm0d** [comment]
re-run macosxmojave

**Comment by Akm0d** [comment]
re-run full all

**Comment by Akm0d** [comment]
re-run full ubuntu1604

**Review by dwoz — CHANGES_REQUESTED** [review]

**Review by cmcmarrow — APPROVED** [review]

**Comment by Akm0d** [comment]
re-run full centos

**Comment by Akm0d** [comment]
re-run full debian10

**Comment by Akm0d** [comment]
re-run full centos

**Comment by Akm0d** [comment]
re-run full debian10

**Comment by Akm0d** [comment]
re-run full pycryptodomex

**Comment by Akm0d** [comment]
re-run full m2crypto

**Comment by Akm0d** [comment]
re-run full centos7

**Comment by Akm0d** [comment]
re-run full centos7

**Review by dwoz — APPROVED** [review]

**Pull request merged**
