### PR TITLE
[master] Add file contents via function call

### LINKED ISSUE #65222: [FEATURE REQUEST] support for contents via function call in file state modules
**Is your feature request related to a problem? Please describe.**
Currently, the ways to insert ad-hoc data from a function call into a file are limited to Jinja templating mechanisms such as:

```
something:
  file.managed:
    - name: /tmp/stuff
    - contents: |
        {% set things = salt.vault.read_secret("secret/my/secret") -%}
        {{ things }}
```

or

```
something:
  file.managed:
    - name: /tmp/stuff
    - template: jinja
    - source: salt://template.jinja
```

```
# /srv/salt/template.jinja
{% set things = salt.vault.read_secret("secret/my/secret") -%}
{{ things }}
```

The first option is problematic because secrets could be shown in `show_sls` output. The second is a pain because you'd need different template files for each set of function calls and parameters in use... or some terrible macro setup.

**Describe the solution you'd like**
It would be great if file state functions such as `file.managed` and `file.serialize` supported an integrated way to insert output from an execution module function call into a file via a `contents_function` parameter.

```yaml
something:
  file.managed:
    - name: /tmp/stuff
    - contents_function:
        - fun: vault.get
          args:
            - secret/my/secret
```

**Describe alternatives you've considered**
Workarounds shown in problem description.

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

### PR DESCRIPTION
**Pull request by nicholasmhughes**
### What does this PR do?
See issue for details.

### What issues does this PR fix or reference?
Fixes: #65222 

### New Behavior
Can use execution module function calls to populate file contents natively.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by frebib** [comment]
This is neat. Does it add any functionality that can't already be had with `__slot__`s?

**Comment by OrangeDog** [comment]
I don't think `file.managed` needs yet another parameter when Slots should already solve this.

**Comment by nicholasmhughes** [comment]
I keep forgetting that slots exist. They don't get much love, do they?

Agree that the use case is handled by slots. I do like the explicit nature of this though... It makes it very clear how to solve this problem without needing to be aware of lesser-known features such as slots.

Will keep open for core team input and will close if consensus is to use slots.

**Comment by nicholasmhughes** [comment]
closing in favor of #65289

**Pull request closed without merging**
