### PR TITLE
Fix to esxdatacenter proxy

### PR DESCRIPTION
**Pull request by alexbleotu**
### What does this PR do?
Fixes esxdatacenter proxy to support getting the `proxy` key both from the pillar and from the proxy configuration file. The key is merged from the two locations. 

### Previous Behavior
Proxy only supported to get its configuration from the opts parameter

### New Behavior
Proxy configuration is merged from the `__pillar__` dunder and from the `opts` param

### Tests written?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Review by rallytime — APPROVED** [review]

**Comment by alexbleotu** [comment]
@cachedout  can you quickly merge this one as wel please

**Review by mirceaulinic — APPROVED** [review]
Looks good to me.
@alexbleotu you might also want to take a look at the `proxy_merge_pillar_in_opts` config option: https://docs.saltstack.com/en/latest/ref/configuration/proxy.html#proxy-merge-pillar-in-opts, available in 2017.7.3, which would do the same (unless I misunderstood your use case).

**Comment by alexbleotu** [comment]
thanks @mirceaulinic I wasn't familiar with that. Yeah this is pretty much the same. I just changed the proxy code to do the merge effectively, even if the option is not set on the proxy. Should the option default to `True`?

**Comment by mirceaulinic** [comment]
> Should the option default to True?

What option @alexbleotu?
If you refer to `proxy_merge_pillar_in_opts`, it will default to `False` for the time being, and we will see later if it's really worth merging pillar data by default into opts. I am worried that the opts object can grow way too much when you have a lot of pillar data. But that's an open discussion and maybe @cro has an opinion about that too.

**Comment by alexbleotu** [comment]
Yep I see. You are absolutely right - this code just merges the `proxy` key from the `pillar` and the config and used that to run. It doesn't merge the entire pillar. This was because this key, which is essentially proxy config was initially placed in the pillar for convenience.

**Pull request merged**
