### PR TITLE
Deprecate client_acl with publisher_acl (rename)

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
Keeping client_acl support

For #23157

### CODE REVIEW

**Comment by cachedout** [comment]
@DmitryKuzmenko Can you please rebase this? There are merge conflicts.

**Comment by basepi** [comment]
Additionally, could you please add deprecation warnings when people try to use client_acl? `salt.utils.warn_until` is perfect for this purpose. I recommend targeting Nitrogen for deprecation.

**Comment by DmitryKuzmenko** [comment]
@cachedout @basepi Done. Thank you for suggestions.

**Comment by cachedout** [comment]
@DmitryKuzmenko It looks like there are some masteracl tests that need to be updated before we can merge this. Could you have another look? Thanks!

**Comment by DmitryKuzmenko** [comment]
Surely. I've just dropped it to another desktop while tests run.

**Comment by cachedout** [comment]
@jacobhammons This will need to be featured very prominently in the release notes.

**Pull request merged**
