### PR TITLE
Port #50797 to master

### PR DESCRIPTION
**Pull request by terminalmage**
See https://github.com/saltstack/salt/pull/50797

### CODE REVIEW

**Review by cmcmarrow — CHANGES_REQUESTED** [review]
Can we get test for your new functions?

**Comment by terminalmage** [comment]
No, I just backported an existing PR to get things started. I didn't write this code originally.

You'll need to write the tests yourself.

**Comment by terminalmage** [comment]
You might also want to loop in @rjeschmi, who authored the original PR.

**Comment by waynew** [comment]
@sagetherage Not sure if @cmcmarrow is available to (re)review this or if we need another to help out, but should be good for a review!

**Review by s0undt3ch — DISMISSED** [review]
I have a problem with long function names, which is not a blocker, but aside from that, looks great!

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
