### PR TITLE
Support mock 2.0.0 again

### LINKED ISSUE #58720: [BUG] Failing test cases when using mock 2.0.0
When running the test suite with mock 2.0.0, these test cases fail:

```
======================================================================
ERROR: test_request_instance_should_be_able_to_provide_a_dictionary_for_network (unit.cloud.clouds.test_openstack.OpenstackTestCase)
[CPU:0.0%|MEM:4.1%] 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/unit/cloud/clouds/test_openstack.py", line 196, in test_request_instance_should_be_able_to_provide_a_dictionary_for_network
    self.assertDictEqual(call.kwargs["network"], expected_network)
TypeError: tuple indices must be integers or slices, not str

======================================================================
ERROR: test_request_instance_should_be_able_to_provide_a_list_of_dictionaries_for_network (unit.cloud.clouds.test_openstack.OpenstackTestCase)
[CPU:0.0%|MEM:4.1%] 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/unit/cloud/clouds/test_openstack.py", line 213, in test_request_instance_should_be_able_to_provide_a_list_of_dictionaries_for_network
    assert call.kwargs["network"] == expected_network
TypeError: tuple indices must be integers or slices, not str

======================================================================
ERROR: test_request_instance_should_be_able_to_provide_a_list_of_single_ids_or_names_for_network (unit.cloud.clouds.test_openstack.OpenstackTestCase)
[CPU:0.0%|MEM:4.1%] 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/unit/cloud/clouds/test_openstack.py", line 230, in test_request_instance_should_be_able_to_provide_a_list_of_single_ids_or_names_for_network
    assert call.kwargs["network"] == expected_network
TypeError: tuple indices must be integers or slices, not str

======================================================================
ERROR: test_pack_alternatives_path_doesnot_exist (unit.utils.test_thin.SSHThinTestCase)
[CPU:0.0%|MEM:4.1%] 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/unit/utils/test_thin.py", line 1269, in test_pack_alternatives_path_doesnot_exist
    for x in calls
  File "/<<PKGBUILDDIR>>/tests/unit/utils/test_thin.py", line 1270, in <listcomp>
    if os.path.join("test", "pyall", _file) in x.kwargs["arcname"]
TypeError: tuple indices must be integers or slices, not str

======================================================================
FAIL: test_pack_alternatives (unit.utils.test_thin.SSHThinTestCase)
[CPU:0.0%|MEM:4.1%] 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/unit/utils/test_thin.py", line 1221, in test_pack_alternatives
    assert [x for x in calls if "{}".format(_file) in x.args]
AssertionError

======================================================================
FAIL: test_pack_alternatives_auto_detect (unit.utils.test_thin.SSHThinTestCase)
[CPU:0.0%|MEM:4.1%] 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/unit/utils/test_thin.py", line 1308, in test_pack_alternatives_auto_detect
    assert [x for x in calls if "{}".format(_file) in x.args]
AssertionError

======================================================================
FAIL: test_pack_alternatives_empty_dependencies (unit.utils.test_thin.SSHThinTestCase)
[CPU:0.0%|MEM:4.1%] 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/unit/utils/test_thin.py", line 1340, in test_pack_alternatives_empty_dependencies
    assert [x for x in calls if "{}".format(_file) in x.args]
AssertionError

======================================================================
FAIL: test_pack_alternatives_exclude (unit.utils.test_thin.SSHThinTestCase)
[CPU:0.0%|MEM:4.1%] 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/unit/utils/test_thin.py", line 1211, in test_pack_alternatives_exclude
    assert [x for x in calls if "{}".format(_file) in x.args]
AssertionError

======================================================================
FAIL: test_pack_alternatives_not_normalized (unit.utils.test_thin.SSHThinTestCase)
[CPU:0.0%|MEM:4.1%] 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/unit/utils/test_thin.py", line 1239, in test_pack_alternatives_not_normalized
    assert [x for x in calls if "{}".format(_file) in x.args]
AssertionError
```

These test cases use `mock._Call.kwargs` or `mock._Call.args` which was introduced in `mock` 3.0 or Python 3.7 `unittest.mock`.

There are two possible solutions:

* Require mock >= 3.0
* Change the test cases to access the `mock._Call` object:
  * Replace `mock._Call.kwargs` by `mock._Call[-1]`
  * Replace `mock._Call.args` by `mock._Call[-2]`

Which solution do you prefer? Then I can create a merge request for it.

### PR DESCRIPTION
**Pull request by bdrung**
The property `mock._Call.kwargs` was added in `mock` version 3.0 and `unittest.mock` Python 3.7 [1]. Support mock 2.0.0 again by accessing the call object tuple instead, because Debian <= 10 (buster) contains only python3-mock 2.0.0.

Fixes https://github.com/saltstack/salt/issues/58720
[1] https://docs.python.org/3.7/library/unittest.mock.html?highlight=mock_calls#calls-as-tuples

### CODE REVIEW

**Comment by s0undt3ch** [comment]
You should be using nox to run the test suite, and, unless our test requirements are not pulling a recent enough version of mock, then there's no need to fix this code.

**Comment by bdrung** [comment]
Unless we build a Debian package, where all dependencies needs to be provided by Debian packages.

Since salt claims to need mock >= 2.0, it should work with mock 2.0 or otherwise raise the needed version (making it harder to build Debian packages for older releases).

**Comment by s0undt3ch** [comment]
> Unless we build a Debian package, where all dependencies needs to be provided by Debian packages.

Why are you building test dependencies into your debian package?

> Since salt claims to need mock >= 2.0, it should work with mock 2.0

Fair point.

> or otherwise raise the needed version (making it harder to build Debian packages for older releases).

If these are the only two changes required to support 2.x, no need to bump requirements just yet.

**Comment by bdrung** [comment]
> Why are you building test dependencies into your debian package?

I do not put test dependencies in the Debian, but specify the test dependencies as build dependencies. These build dependencies will be installed via apt and therefore there need to be Debian package for them.

> If these are the only two changes required to support 2.x, no need to bump requirements just yet.

These are the only two changes to make the unit tests work (a haven't tested anything besides the unit tests since we only run the unit tests during package build).

**Comment by dwoz** [comment]
re-run full all

**Comment by dwoz** [comment]
re-run full all

**Review by krionbsd — APPROVED** [review]

**Pull request merged**
