### PR TITLE
[dockerng] fix mounting

### PR DESCRIPTION
**Pull request by ticosax**
@terminalmage can you have a look please ?

This PR fixes volume mounting. host and container values were swapped.

### CODE REVIEW

**Comment by rallytime** [comment]
Thanks @ticosax for the fix and adding the test! Awesome!

Would you mind grabbing the [pylint error](https://jenkins.saltstack.com/job/salt-pr-lint-n/5512/violations/file/tests/unit/states/dockerng_test.py/)?

**Comment by rallytime** [comment]
@jfindlay You're right. I didn't even look. Just saw the pylint errors. @ticosax If you circle back around to this before I do, please have a look at one of the other unit test files in the test directory. There are several things that should be included with this test file. I will add comments on the affected lines.

**Comment by rallytime** [comment]
@ticosax I've created a pull request against your branch in your fork. That should clean up the boilerplate necessities for the new test file as well as the pylint errors. Once you merge my pull request into your branch, the tests here should kick off again. Thanks again!

**Comment by ticosax** [comment]
@rallytime thx a lot ! I will remember it for the nex test module I might create.

**Comment by ticosax** [comment]
It is still failing. But when I follow links to jenkins I'm unable to get the origin of the culprit.
Is it documented somewhere ?

**Comment by rallytime** [comment]
@ticosax No problem! Happy to help and thanks for getting it started. That test failure looks like an unrelated problem to me (the test runner timed out). I'm marking this as "Test Passed". Thanks again!

**Pull request merged**
