### PR TITLE
Backwards compat for mine.get on pre-Nitrogen minions

### PR DESCRIPTION
**Pull request by gracinet**
### What does this PR do?

Fix a backwards compatibility issue involving mine.get on 2016.11 minions. 
I think it should ultimately target the 2017.7 stable branch, but here's still polishing to be done (see below about tests), and feedback needed about the deprecation warning.

In the meanwhile it already demonstrates that a fix is not hard.

### What issues does this PR fix or reference?
This solves issue #42713.
### Previous Behavior
Only glob selection can work in mine.get on a 2016.11 or earlier minion if the master has 2017.7

### Tests written?

Not yet, it's been a while since my previous contributions. Let me see first the clues that CI bots can give me. 
For now I have successfully tested in my testing lab (master 2017.7, live patched with the same diff) with 2016.11 and 2017.7 minions. 

### Commits signed with GPG?

Didn't think of that, should do it later

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by terminalmage — APPROVED** [review]

**Comment by rallytime** [comment]
Hi @gracinet - thanks for submitting this fix. Were you going to add some tests to this? Does this fix need to be applied to earlier branches?

**Comment by gracinet** [comment]
@rallytime my pleasure! Yes I'd like to add tests and sign the final commit, but didn't get to it yet. Please hold a bit, if I can't do it today, I'll do it next week.

About earlier branches, I think it's mostly useful for Nitrogen. I tied the deprecation warning to Neon, but that's just a hunch, mere copying of what I saw of similar ones in current develop branch.
Will you want me to submit a separate PR towards 2017.7 ?

**Comment by gracinet** [comment]
@rallytime just pushed a tentative unit test, hope I got it right.
Have to go offline now, but If you need me to squash, make a final rebase etc, I can do it next week.

**Comment by gracinet** [comment]
I'll still check Jenkins results, later this evening, though

**Comment by rallytime** [comment]
@gracinet Sounds great and thank you for adding the unit test. We'll see how the tests go.

I think using Neon is great. We can back-port this to 2017.7 once it's been merged in. I've added the back-port label so I know to grab it later.

**Comment by gracinet** [comment]
I don't really understand the salt-pr-lint-n build failure, Jenkins shows me a flat graph with value 0.
Tried to run pylint on the two files I changed and compare with the base of the fork (develop branch), here are my results:

Before:
* pylint --rcfile .pylintrc tests/unit/daemons/test_masterapi.py: 5.68/10
* pylint --rcfile .pylintrc tests/unit/daemons/test_masterapi.py: 9.47/10

After:
* pylint --rcfile .pylintrc tests/unit/daemons/test_masterapi.py: 5.88/10
* pylint --rcfile .pylintrc tests/unit/daemons/test_masterapi.py: 9.48/10

**Comment by gracinet** [comment]
@cachedout thanks for the merge!

**Comment by cachedout** [comment]
@gracinet It hasn't been merged yet. Just bringing in the latest changes so we can re-run the tests. Hopefully we'll get this merged into Salt soon, though. Thanks for your patience!

**Comment by gracinet** [comment]
@cachedout yes of course I meant the merge from develop into my branch. In any case, don't hesitate to point me at what's to be done for merging the PR itself.

**Comment by gracinet** [comment]
Thanks for the final merge into develop!

**Comment by rallytime** [comment]
@gracinet I was attempting to back-port this today to 2017.7, but it's not back-porting as cleanly as I would like. Would you be able to make this fix against 2017.7 instead of me back-porting it?

**Comment by gracinet** [comment]
@rallytime sure, will look at it tomorrow (timezone Europe/Paris). As a PR towards the 2017.7 branch, right ?

**Comment by rallytime** [comment]
@gracinet Yes, 2017.7 branch. Thank you!

**Comment by gracinet** [comment]
@rallytime this is PR #44735

**Pull request merged**
