### PR TITLE
Jinja include path

### PR DESCRIPTION
**Pull request by steverweber**
https://github.com/saltstack/salt/issues/21198

### CODE REVIEW

**Comment by steverweber** [comment]
i would not mine if we deprecated:

slsdotpath
slscolonpath
sls_path
slspath

I added these in lastyear and its kinda just code blot with me likly being the only person that used them.

**Comment by steverweber** [comment]
some test...


mfcf/cloud/test/init.sls
```
{%- from tpldir + '/woot/vars.jinja' import vars %}
{%- from tpldir + '/woot2/vars.jinja' import vars as varswoot2 %}

{{ tpl }}:
    template: {{ template }}
    tpl: {{ tpl }}
    tpldir: {{ tpldir }}
    
{{ tpl }}.woot: {{ vars }}

{{ tpl }}.woot2: {{ varswoot2 }}
```


mfcf/cloud/test/andback/vars.jinja
mfcf/cloud/test/woot/vars.jinja
```
{% set vars = { 'tpl': tpl, 'template': template, 'tpldir': tpldir } %}
```

mfcf/cloud/test/woot2/vars.jinja
```
{%- from 'mfcf/cloud/test/andback/vars.jinja' import vars as andback %}
{% set vars = { 'tpl': tpl, 'template': template, 'tpldir': tpldir, 'andback': andback } %}
```

salt minion pillar.items
```
    mfcf.cloud.test:
        ----------
        template:
            mfcf/cloud/test/init.sls
        tpl:
            mfcf.cloud.test
        tpldir:
            mfcf/cloud/test
    mfcf.cloud.test.woot:
        ----------
        template:
            u'mfcf/cloud/test/woot/vars.jinja'
        tpl:
            u'mfcf.cloud.test.woot'
        tpldir:
            u'mfcf/cloud/test/woot'
    mfcf.cloud.test.woot2:
        ----------
        andback:
            ----------
            template:
                mfcf/cloud/test/andback/vars.jinja
            tpl:
                mfcf.cloud.test.andback
            tpldir:
                mfcf/cloud/test/andback
        template:
            u'mfcf/cloud/test/woot2/vars.jinja'
        tpl:
            u'mfcf.cloud.test.woot2'
        tpldir:
            u'mfcf/cloud/test/woot2'
```
i could remove the unicode if need.

**Comment by steverweber** [comment]
i might rename the vars to.. :
* tplfile
* tpldot
* tpldir

**Comment by steverweber** [comment]
i think i'm done wiggling around.  sorry about not squashing.
I took a look at added a unit test for this... but did't seem simple to attempt.

**Comment by rallytime** [comment]
@steverweber We can backport this, no problem. However, in the future if you're fixing a bug that needs to go into another branch, please make that change on the appropriate supported release branch. That way when we merge forward, the fix will be on all of the branches that have the bug and we don't have to backport fixes. 

You can read more about this here: http://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch and of course let us know if you have any questions! Thanks!

**Comment by steverweber** [comment]
i'll change gears and focus testing the 2015.2 release.  Please let me now when this is merged and i'll highstate this and ensure the release passes my env.

thanks/

**Comment by steverweber** [comment]
whats the state of this.... I can create a new PR using the 2015.2 branch with this fix...

**Comment by steverweber** [comment]
i backported it to 2015.

**Pull request closed without merging**
