### PR TITLE
Fixed the 'status.procs' and 'status.pid' functions for openvzhn environments

### PR DESCRIPTION
**Pull request by hathawsh**
### What does this PR do?

This pull request fixes the 'status.procs' and 'status.pid' functions for openvzhn environments and any other environment where the command specified by grains['ps'] must run as a shell command. It simply adds 'python_shell=True' to the cmd calls.

### What issues does this PR fix or reference?

None.

### Tests written?

No, but tested manually.

### CODE REVIEW

**Review by sjorge — APPROVED** [review]
LGTM. jenkins error also seem to be unrelated/

**Review by cachedout — APPROVED** [review]

**Review by cachedout — COMMENTED** [review]
Hrm, I think this might have subtly altered the open_scap test. We need to investigate before we merge this.

**Comment by sjorge** [comment]
For those like me who overlooked the small difference:
```
['oscap', 'xccdf', 'eval', '--oval-results', '--results', 'results.xml', '--report', 'report.html', '--profile', 'Default', '/policy/file']
```
vs
```
['oscap', 'xccdf', 'eval', '--oval-results', '--results', 'results.xml', '--report', 'report.html', '--profile', 'Default', '--param', 'Default', '/policy/file']
```

```'--param', 'Default'``` Got inserted before /policy/file

**Comment by rallytime** [comment]
It looks like the openscap test failure was introduced in another PR. I'll get a fix in for this today.

**Pull request merged**
