### PR TITLE
Create cluster gh

### PR DESCRIPTION
**Pull request by alexbleotu**
### What does this PR do?

Added utils.vmware.create_clusterd
    
- creates a cluster in a datacenter based on a cluster spec

### Tests written?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by rallytime** [comment]
Looks like a couple of lint errors on the test file: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/6422/violations/file/tests/unit/utils/vmware_test/cluster_test.py/

Mind cleaning those up? Then we can get this in!

**Comment by alexbleotu** [comment]
any further issues?

**Comment by rallytime** [comment]
Heh, since I merged in your other PR, this now has merge conflicts. @alexbleotu Can you rebase this one?

**Comment by alexbleotu** [comment]
@rallytime I will rebase it after https://github.com/saltstack/salt/pull/37348 gets merged in cause it will cause another set of conflicts

**Comment by cachedout** [comment]
@alexbleotu We're ready to have this rebased, please.

**Comment by alexbleotu** [comment]
False failiure, can be merge :+1:

**Comment by cachedout** [comment]
Thanks, @alexbleotu

**Pull request merged**
