### PR TITLE
Corrected struct value in wtmp/btmp beacons

### PR DESCRIPTION
**Pull request by githubcdr**
### Previous Behavior
username was incorrect

### New Behavior
username as expected

### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by cachedout** [comment]
What platform did you discover this to be broken on? I'm kind of surprised this wasn't found as an issue before today and I want to make sure we don't regress somewhere else.

**Comment by UtahDave** [comment]
I believe Tom wrote this originally on either an Arch or CentOS box. The original code gave me partially wrong user names on Ubuntu. Apparently almost every OS has a different struct depending on how it was compiled or something or other.  Somebody suggested querying for the proper struct somehow, but I don't think anyone did anything with that.

**Comment by cachedout** [comment]
@UtahDave Good memory! Yes, that's my exact concern here.

**Comment by githubcdr** [comment]
I noticed that CentOS, Archlinux and Ubuntu gave me errors with original struct value.

**Comment by damon-atkins** [comment]
The structure should not change to much otherwise programs compiled against old versions of an OS would not work.  But between different versions of an OS Family be very different.  Might be worth seeing if anything is in  the POSIX standard  about it.   This needs to use the OS Family or kernel specific grain to determine the structure as a minimum.

**Comment by cachedout** [comment]
Given the above discussion, my mind would be greatly eased if we included a test for this.

**Comment by damon-atkins** [comment]
https://en.wikipedia.org/wiki/Utmp is an interesting read

**Comment by cachedout** [comment]
@githubcdr Do you have any interest in writing a test for this? I'd love to get this in but I still have concerns about regressing this on some platforms so I'd like to find a good solution.

**Comment by githubcdr** [comment]
Maybe I can change the code to include the struct value for known OS'es with fallback to the original struct? I'm just starting with Python.

Like you mentioned, it is hard to get the scope of this change, but I know all recent OS'es only work with the new struct. (Arch, CentOS, Ubuntu)

**Comment by cachedout** [comment]
@githubcdr A fallback sounds like a reasonable approach to start with. Do you want to give that a go?

**Comment by githubcdr** [comment]
@cachedout I would love to help but I'm no Python programmer. For now I use a 'corrected' beacon in my _modules fileroot, it fixes my problem and won't cause any regression.

One thing I noticed is that the utmp packages also uses almost the same struct value. (https://pypi.python.org/pypi/utmp) So it might end up in the main code some day ;)

**Comment by cachedout** [comment]
@gtmanfred Is this something you can help chase down?

**Comment by gtmanfred** [comment]
Yeah, i will try to make a look later today.

**Comment by gtmanfred** [comment]
Sorry, i completely forgot about this. Looking today

**Comment by cachedout** [comment]
Thanks, @gtmanfred. Please ping me when this is ready to go.

**Comment by gtmanfred** [comment]
I have tested this on Centos 6/7, RHEL 6/7, Debian 7/8/testing, ubuntu 14.04/16.04, and sles 11/12 and they all work better with the new value.

I am also having problem seeing it even work on archlinux, so I would go ahead and merge this.

This is also an older issue that has been mentioned several times before

https://github.com/saltstack/salt/issues/26294
https://github.com/saltstack/salt/issues/21203

And in https://github.com/saltstack/salt/issues/26294#issuecomment-133028883 It actually mentions this new value.

Thanks,
Daniel

**Comment by cachedout** [comment]
Thanks to everybody for the good work on this one!

**Pull request merged**
