### PR TITLE
[2018.3] Merge forward from 2018.3.0rc1 to 2018.3

### PR DESCRIPTION
**Pull request by rallytime**
Conflicts:
  - doc/topics/releases/2018.3.0.rst

### CODE REVIEW

**Review by cachedout — APPROVED** [review]

**Comment by damon-atkins** [comment]
@Ch3LL Looks like this missed the web site update. 
Given the headings style/size are wrong in https://docs.saltstack.com/en/latest/topics/releases/2018.3.0.html

**Comment by Ch3LL** [comment]
looks like its there now from what i can tell

**Comment by damon-atkins** [comment]
It is, what branch is the web site based on?

**Comment by rallytime** [comment]
It's based on the main release branches. 2017.7, 2018.3, develop right now

**Pull request merged**
