### PR TITLE
Fix a SYNTAXERROR!!! from a merge forward

### PR DESCRIPTION
**Pull request by basepi**
https://github.com/saltstack/salt/commit/b0fe5cc955bb4b19bcfe0619ebb9d06cc42fdc6a#commitcomment-10500444

### CODE REVIEW

**Comment by kiorky** [comment]
@basepi i already opened a PR, did you noticed it ?

**Comment by kiorky** [comment]
dup of already merged https://github.com/saltstack/salt/pull/22198, can be deleted.

**Comment by thatch45** [comment]
I merged @kiorky 's
Thanks :)

**Comment by basepi** [comment]
Sorry @kiorky, I missed yours.

**Pull request closed without merging**
