### PR TITLE
[master] Porting #49624 to master

### PR DESCRIPTION
**Pull request by garethgreenaway**
Porting #49624 to master

### CODE REVIEW

**Review by dwoz — CHANGES_REQUESTED** [review]
Needs a test.

**Review by cmcmarrow — CHANGES_REQUESTED** [review]
Need test

**Comment by Ch3LL** [comment]
@cmcmarrow and @dwoz this now has a test. Since i wrote the test can you re-review.

**Comment by Ch3LL** [comment]
@cmcmarrow and @dwoz i re-ran black. this is ready for re-review please

**Review by dwoz — APPROVED** [review]

**Pull request merged**
