### PR TITLE
[Don't merge yet] Py3 compat changes & Update pylintrc to load the py3modernize plugin

### PR DESCRIPTION
**Pull request by s0undt3ch**
[Review on Reviewable](https://reviewable.io/reviews/saltstack/salt/17883)

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
@s0undt3ch looks like this might be ready after a rebase!

**Comment by s0undt3ch** [comment]
I've been working on this to fix the failing tests. I think I still have at least the lxc ones to fix.

I'll rebase to confirm, but yeah, its close!

**Comment by s0undt3ch** [comment]
Lint failure is unrelated. This PR is ready.

**Comment by thatch45** [comment]
Is this locale test related @s0undt3ch ?

**Comment by s0undt3ch** [comment]
It was ALL green! But then i had to rebase....

Failures unrelated...

**Pull request merged**
