### PR TITLE
update fix bug 60915 parse terraform.tfstate error

### PR DESCRIPTION
**Pull request by hzwns520**
### What does this PR do?
After terraform v0.12.0, terraform parsed terraform.tfstate incorrectly, so  added a new version of terraform.tfstate parse. No problem testing locally
### What issues does this PR fix or reference?
Fixes:
#60915

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by MKLeb** [comment]
Hi @hzwns520.  Are you able to rebase this on master and change the target branch to `saltstack:master`?

Also, would you mind adding a changelog and a test or two?

**Comment by MKLeb** [comment]
Hi @hzwns520, any updates on rebasing to the master branch?

**Comment by hzwns520** [comment]
yes,&nbsp; only update terraform.py


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "saltstack/salt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月20日(星期四) 上午6:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [saltstack/salt] update fix bug 60915 parse terraform.tfstate error (PR #61311)





 
Hi @hzwns520, any updates on rebasing to the master branch?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MKLeb** [comment]
@hzwns520 I have ported this over to master.   Would you mind writing a few tests for this?

**Comment by MKLeb** [comment]
hi @hzwns520 , any chance you could write a test or two here?

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
