### PR TITLE
[2016.11] Merge forward from 2016.3 to 2016.11

### PR DESCRIPTION
**Pull request by rallytime**
Conflicts:
  - doc/topics/tutorials/gitfs.rst
  - salt/fileserver/roots.py
  - salt/loader.py

### CODE REVIEW

**Comment by rallytime** [comment]
The test failures here are related. One test was already failing in 2016.3 (`integration.fileserver.roots_test.RootsTest.test_symlink_list`) and was likely caused by #39337. The other test failure also seems related to that change, though it isn't failing on the 2016.3 branch.

**Comment by rallytime** [comment]
This needs the changes from @terminalmage in #39409, so I'll close this and re-do the merge-forward once those changes go in.

**Comment by terminalmage** [comment]
Sorry for the extra work @rallytime

**Comment by rallytime** [comment]
No problem at all :) thanks for fixing that up

**Pull request closed without merging**
