### PR TITLE
Lxc profiles

### PR DESCRIPTION
**Pull request by kiorky**
refs #23772 #23833

Allow no profile to have sane fallbacks and correct handling of network profiles options

Second PR to apply in the serie

should be applied after #23806
should be applied before #23808

### CODE REVIEW

**Comment by jfindlay** [comment]
@terminalmage, please review when you have time, thanks.

**Comment by kiorky** [comment]
I think we are mostly there, @terminalmage with @cheuschober 
There are still maybe a detail from @cheuschober on salt cloud, which i can not reproduce locally.

**Comment by kiorky** [comment]
(always hold, i ll ping when ready)

**Comment by kiorky** [comment]
failures unrelated.

**Comment by kiorky** [comment]
@terminalmage PTAL now, seems a bit more stable.

**Comment by kiorky** [comment]
wont be approved.

**Comment by kiorky** [comment]
@cheuschober im sorry my patches have a chance not to go futrther.

**Comment by basepi** [comment]
See my comment here: https://github.com/saltstack/salt/pull/23805#issuecomment-103238312

**Comment by basepi** [comment]
@kiorky Please wait for https://github.com/saltstack/salt/pull/23893 then you can make your changes on top.

**Comment by kiorky** [comment]
@basepi wtf this pr is not about develop

**Comment by basepi** [comment]
Ah, sorry, I thought they were all develop. Sorry for the confusion. Can you please open a new one? It won't let me re-open this one because "The lxc_profiles branch was force-pushed or recreated."

**Comment by kiorky** [comment]
i was just reediting the messages. ok.

**Pull request closed without merging**
