### PR TITLE
adding netscaler unit test case

### PR DESCRIPTION
**Pull request by jayeshka**
Implemented netscaler_test unit test case.

### CODE REVIEW

**Comment by thatch45** [comment]
Well, thats a ton of failures :)

**Comment by jayeshka** [comment]
Well seems like some extra library is installed at my end. So, it ran well
at my end and didn't got any failures.
Will fix this soon. :)

**Comment by jayeshka** [comment]
Hey @jfindlay is this unit test case ready to merge.
I don't see any errors in this. Please review it.

**Comment by jfindlay** [comment]
@jayeshka, yes, looks good, thanks.

**Pull request merged**
