### PR TITLE
patches salt grains locale_info decode error

### PR DESCRIPTION
**Pull request by cmcmarrow**
### What does this PR do?
Patches python2 timezone decode error
### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/53856

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?
Yes

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by cmcmarrow** [comment]
grains['locale_info']['timezone'] = time.tznam[0].decode('mbcs')

**Review by xeacott — APPROVED** [review]

**Review by dwoz — APPROVED** [review]

**Review by Akm0d — APPROVED** [review]

**Comment by cmcmarrow** [comment]
re-run ci/py3/centos7, ci/py3/fedora29

**Comment by cmcmarrow** [comment]
re-run centos7

**Comment by cmcmarrow** [comment]
re-run ci/py3/fedora29

**Comment by cmcmarrow** [comment]
re-run fedora29

**Comment by cmcmarrow** [comment]
re-run centos7

**Comment by cmcmarrow** [comment]
re-run ubuntu1604/tcp

**Comment by cmcmarrow** [comment]
buntu1604

**Comment by cmcmarrow** [comment]
re-run ubuntu1604/tcp

**Comment by cmcmarrow** [comment]
re-run ubuntu1604

**Comment by cmcmarrow** [comment]
re-run centos7

**Pull request merged**
