### PR TITLE
[develop] Adding jids in master & minion logs

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
This change adds the optional ability to include the JIDs in the master & minion logs for all entries related to a particular Salt job.

### What issues does this PR fix or reference?
#45282

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by isbm — CHANGES_REQUESTED** [review]
Unit Tests? :wink:

**Review by gtmanfred — APPROVED** [review]
Nice, well done.

[blind-review](https://github.com/zombie/blind-reviews "Review performed in blind mode")

**Review by rallytime — CHANGES_REQUESTED** [review]
I have a _very_ minor change request.

Otherwise, great idea using tornado's `StackContext`!

**Review by rallytime — APPROVED** [review]

**Comment by garethgreenaway** [comment]
Tests will pass under Python3 is logging is not disabled
```
➜ python ~/code/salt/tests/runtests.py -n integration.logging.test_jid_logging
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Python Version: 3.6.5 (default, Jul 27 2018, 13:22:44) [GCC 7.3.0]
 * Transplanting configuration files to '/tmp/salt-tests-tmpdir/config'
 * Current Directory: /home/gareth/code/salt
 * Test suite is running under PID 18747
 * Logging tests on /tmp/salt-runtests.log
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Max open files settings is too low (soft: 1024, hard: 4096) for running the tests
 * Trying to raise the limits to soft: 3072, hard: 4096
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Setting up Salt daemons to execute tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Starting salt-master ... STARTED!                                                                                                                                                                                                          
 * Starting salt-minion ... STARTED!                                                                                                                                                                                                          
 * Starting sub salt-minion ... STARTED!                                                                                                                                                                                                      
 * Starting syndic salt-master ... STARTED!                                                                                                                                                                                                   
 * Starting salt-syndic ... STARTED!                                                                                                                                                                                                          
==============================================================================================================================================================================================================================================
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Starting integration.logging.test_jid_logging Tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.
----------------------------------------------------------------------
Ran 1 test in 0.272s

OK

===========================================================================================================  Overall Tests Report  ===========================================================================================================
***  No Problems Found While Running Tests  **************************************************************************************************************************************************************************************************
==============================================================================================================================================================================================================================================
OK (total=1, skipped=0, passed=1, failures=0, errors=0) 
===========================================================================================================  Overall Tests Report  ===========================================================================================================
```

**Review by isbm — APPROVED** [review]
:+1:

**Comment by rallytime** [comment]
@garethgreenaway One lint failure here. Can you fix that up, please?

https://jenkinsci.saltstack.com/job/pr-lint/job/PR-48660/2/warnings52Result/

**Comment by garethgreenaway** [comment]
re-run all

**Review by cachedout — APPROVED** [review]
This is extremely well-done. Hats off, @garethgreenaway

**Pull request merged**
