### PR TITLE
Multi syndic: Multi-master support

### PR DESCRIPTION
**Pull request by jacksontj**
**\* Don't merge immediately ***

This PR has a few cleanups to the MultiSyndic, primarily around the failure cases-- we now stall 15s instead of 180s. 

This also add support for Syndics to run on multi top level masters-- the config is a little magic, but it works. To explain:

Lets say we have 3 masters-- and we want minions to connect to one of them (using failover minion), but we only want to log onto one master to start the job. With the code here you can now configure a syndic on each box (configured to talk to the other 2) and it will forward only publishes and returns. This basically "clusters" masters-- since a publish anywhere ends up on all minions.

This new forwarding mode is controlled by an opt "syndic_mode" (sync or cluster).

### CODE REVIEW

**Comment by cachedout** [comment]
This is a very cool approch. I like it!

We're theoertically in feature-freeze on 2015.2. I assume your preference is to try and get this in? Or is merging into develop an option you'd feel comfortable with?

**Comment by jacksontj** [comment]
I'd like to get it in if possible. That majority of this PR is fixing the
multisyndic. And the "new" stuff is all config wrapped so it should be fine.

**Comment by jacksontj** [comment]
So basically the new feature is a "dark launch"

**Comment by cachedout** [comment]
@jacksontj Sounds good. Let's get it in!

**Pull request merged**
