### PR TITLE
test_vcenter_connection should raise system exception when it fails

### PR DESCRIPTION
**Pull request by guillermo-menjivar**
### What does this PR do?
This PR allows 

### Previous Behavior
The cloud.vmware.test_vscenter_connection function returned a exit 0 even when it failed to connect to vsphere

### New Behavior
The cloud.vmware.test_vscener_connection function now raises the SaltCloudSystemExit exception on failure. This allows for the shell to receive the correct "failed" exit code.

### Tests written?

No

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by rallytime — APPROVED** [review]

**Review by gtmanfred — CHANGES_REQUESTED** [review]
can you set `__context__['retcode'] = 1` and see if it returns the retcode.

This function should be run with `salt-cloud -f test_vcenter_connection <something>` if someone chooses to use this from their CloudClient using client.action() and passing in the provider name, we don't want to raise a SystemExit, because then it will just exit fully.  It would be better to actually just set the return code for if salt-cloud exits after the failure, though i am not sure the __context__ retcode stuff is built into the command.

But overall, I am against this SystemExit.

**Comment by videte47** [comment]
Ah cool thanks @gtmanfred for the feedback. I will amend the PR with your feedback.

**Comment by cachedout** [comment]
@videte47 Were you going to amend this PR?

**Comment by cachedout** [comment]
We didn't get a response from @videte47 so I'm going to close this. If @videte47 can come back to this, we can re-open it easily.

**Pull request closed without merging**
