### PR TITLE
Update salt-cloud azurearm to work with latest sdk

### PR DESCRIPTION
**Pull request by asyncmind0**
- allows compatibility with azure-cli

### What does this PR do?

#42839

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Tests written?

Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Review by arouene — APPROVED** [review]
Seems good to me

**Review by gtmanfred — APPROVED** [review]

**Review by rallytime — CHANGES_REQUESTED** [review]
I think this looks like a good change, but I'd like to see some version checking for the new `>=2.0.12` Azure Cli dependency. This can be done in the `get_dependencies` function.

I'd also like to see a note in the [Oxygen release notes](https://github.com/saltstack/salt/blob/develop/doc/topics/releases/oxygen.rst) about this dependency change to help people know to upgrade.

Once those two things are updated, we can get this in. :)

**Comment by cachedout** [comment]
@jagguli Do you think you'll be able to address those requested changes from @rallytime? We would love to get this in.

**Comment by cachedout** [comment]
@jagguli Did you see the above request from @rallytime?

@techhat We would really like you to sign off on this if you have a moment. Thanks.

**Review by techhat — APPROVED** [review]
This looks okay to me.

**Comment by jagguli** [comment]
@cachedout Implemented changes as requested

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
re-run lint

**Comment by rallytime** [comment]
Thank you @jagguli!

**Pull request merged**
