### PR TITLE
Set system.set_reboot_required_witnessed to use /tmp/salt

### LINKED ISSUE #58125: [BUG] system.reboot_required_witnessed sticks on True after setting it and rebooting
**Description**
system.get_reboot_required_witnessed returns always true once set.

**Setup**
- QEMU/kvm virtual machine, master and minion on same machine
- happens also with master and minion on different machines

Config files:
```
/etc/salt/master:
interface: 127.0.0.1

/etc/salt/minion:
master: 127.0.0.1
id: localminion
```

**Steps to Reproduce the behavior**
- start and enable both master and minion services
- accept minion key
```
[tqre@salt-debug ~]$ sudo salt '*' system.get_reboot_required_witnessed
localminion:
    False
[tqre@salt-debug ~]$ sudo salt '*' system.set_reboot_required_witnessed
localminion:
    True
[tqre@salt-debug ~]$ sudo reboot
Connection to 192.168.0.10 closed by remote host.
Connection to 192.168.0.10 closed.
...reconnect after machine has booted...
[tqre@salt-debug ~]$ sudo salt '*' system.get_reboot_required_witnessed
localminion:
    True
```

**Expected behavior**
system.reboot_required_witnessed should reset to False after reboot.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: 0.36.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.8.5 (default, Jul 27 2020, 08:42:51)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: arch
         locale: utf-8
        machine: x86_64
        release: 5.7.12-arch1-1
         system: Linux
        version: Arch Linux
```
</details>

### PR DESCRIPTION
**Pull request by tqre**
Fixes #58125

Removed the depends-decorator as it was not functioning correctly. The file was touched always in the NILinuxRT -specific directory. Made a simple check for the os_family instead. Also added clarification on module functionality on setting the reboot flag. Renamed the file created to be more precise on it's meaning.

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by tqre** [comment]
Found a typo and removed the unused import. However, I'm not sure what is the correct string formatting here, I changed it according to https://docs.saltstack.com/en/latest/topics/development/conventions/style.html#formatting-strings

**Review by Ch3LL — CHANGES_REQUESTED** [review]
This needs a test and pre-commit will need to be run as well. Let me know if i can help here.

**Comment by sagetherage** [comment]
Since this doesn't have a test case, dropping it from the scope for the Magnesium release.

**Comment by mdschmitt** [comment]
Is there anything that can be done to un-block this?

**Comment by Ch3LL** [comment]
This PR requires a test case, a changelog file and looks like previously pre-commit was failing.

**Comment by Ch3LL** [comment]
Anyone willing to push this one to completion?

**Review by twangboy — CHANGES_REQUESTED** [review]
Please add a changelog and a test case

**Comment by Ch3LL** [comment]
Closing due to inactivity. Please let me know if you want me to re-open this PR or open a new PR against the master branch including the feedback in the PR

**Pull request closed without merging**
