### PR TITLE
Improvements to osx packaging scripts

### PR DESCRIPTION
**Pull request by twangboy**
Split the build script up into different tasks:
- `build_dev.sh` will build a dev environment with everything but salt
- `build_pkg.sh` will take the contents of `/opt/salt` and create a mac osx .pkg installer
- `build_sig.sh` will sign a package
- 'build.sh`runs`build_dev`, installs salt, and then runs`build_pkg`

Broke requirements file into a regular and an extra requirements
- `req.txt` : packages that require no additional parameters
- `req_ext.txt` : packages that require additional parameters to install correctly (can't be installed with the rest)
- All versions are downloaded from pypi with specific versions noted in the req files

Changed License, Welcome, and Conclusion to `.rtf` format
Changed the SaltStack graphic to fit properly in the wizard

My attempts at rebase failed for #29858, ergo this PR

### CODE REVIEW

**Comment by cachedout** [comment]
It seems like this is downloading various pieces of software without checking checksums or in many cases, even using HTTPS. Is that correct?

**Comment by twangboy** [comment]
I'm using the same links that CR used in the original script. I had to use curl instead of wget because that's not installed on a fresh image. We're not checking sha's... yet... that will be added.

**Comment by thatch45** [comment]
Lets get the sha checks in here before we merge, it should not be a hard add. Just add a sha checking function and call it for each download. Add the shas in the script at the top as variables like
LIBSODIUM_SHA='shashashasha'
And use sha512, since blake is probably not there :P

**Comment by cachedout** [comment]
I am going to close this until we have the verification requested by @thatch45 added. Please re-open when that's in place and this is ready to go. Thanks.

**Comment by cachedout** [comment]
Great! Looks much better. After the tests run, I'll get this in.

**Comment by twangboy** [comment]
Thanks!

**Pull request merged**
