### PR TITLE
allow for nova servers to be built with premade volumes

### PR DESCRIPTION
**Pull request by gtmanfred**
if the boot_volume is specified, allow for that to be used instead of an image

### CODE REVIEW

**Comment by gtmanfred** [comment]
@rallytime and this one.

I was looking through the work flow, will all fixes in this branch be merged forward to 2016.3 eventually or only forward to develop?

Thanks
Daniel

**Comment by rallytime** [comment]
@gtmanfred Yes, all fixes in each branch get merged forward into the newer branches. So 2015.5 gets merged into 2015.8, 2015.8 into 2016.3, then 2016.3 to develop. So for example, fixes that go into 2015.8 go into all _newer_ branches, but not 2015.5.

**Comment by gtmanfred** [comment]
Awesome, then I will let the regular process handle them :) thanks!

**Comment by rallytime** [comment]
Definitely!

**Pull request merged**
