### PR TITLE
when I use zmq_filtering on 2015.5.3 ,I think there is a bug 

### PR DESCRIPTION
**Pull request by double-yaya**
question #26844

### CODE REVIEW

**Comment by jfindlay** [comment]
@double-yaya, there is one [lint error](https://jenkins.saltstack.com/job/salt-pr-lint-n/9316/violations/file/salt/minion.py/).

**Comment by cachedout** [comment]
@double-yaya I'm not certain this is the correct fix. Could you please explain your reasoning here?

**Comment by double-yaya** [comment]
when I enable zmq_filtering on master and part of minions, then I excute state.sls happend like this:
The function "state.sls" is running as PID XXXX and was started at .... with jid XXXX always shows the current jid on the  minion which is not configured zmq_filtering,because the master  zmq_filtering for loop  send multiple commands  and  resulting in this part minion which is not configured zmq_filtering will  receive the number of tgt multiple commands ,then this part minion will excute multiple commands  cause conflict

Here is the zmq_filtering for loop codes:
```
if self.opts['zmq_filtering']:
                        # if you have a specific topic list, use that
                        if 'topic_lst' in unpacked_package:
                            for topic in unpacked_package['topic_lst']:
                                # zmq filters are substring match, hash the topic
                                # to avoid collisions
                                htopic = hashlib.sha1(topic).hexdigest()
                                pub_sock.send(htopic, flags=zmq.SNDMORE)
                                pub_sock.send(payload)
                                # otherwise its a broadcast

                        else:
                            # TODO: constants file for "broadcast"
                            pub_sock.send('broadcast', flags=zmq.SNDMORE)
                            pub_sock.send(payload)
```

**Comment by cachedout** [comment]
@jacksontj IIRC, you implemented `zmq_filering` originally. Any thoughts here?

**Comment by jacksontj** [comment]
It sounds like the problem you are seeing is that the job ends up on a minion more than once? I tested locally, and I cannot reproduce that behavior. Also, I'm not sure how this PR helps the situation any. Right now the minions are configured to handle filtered or unfiltered messages-- so you can actually have a mix of minions (enabled/disabled)-- but once it is enabled on a single minion the master needs to have it enabled.

Given the double JIDs it looks like you might have some weird publishing loops-- what does your master setup look like?

**Comment by double-yaya** [comment]
I did this test minion is mix of minions (enabled/disabled)， if I enable zmq_filtering on all minions work well.
After  I modified the code , my test no problem
Did  you use -L to test ? 
if you use three minion  to test,master will pub three commands who have different topic,and the minion will receives all three commands  which not enable zmq_filtering ,so the minion will excute three command.You can send a few more commands to test, sometimes once or twice is not reproducible.

master status:

service salt-master status
```
salt-master (pid  2546) is running...
```

ps -ef|grep salt-master
```
505       2546     1  0 10:08 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-master -d ProcessManager
505       2547  2546  0 10:08 ?        00:01:04 /usr/bin/python2.6 /usr/bin/salt-master -d Maintenance
505       2548  2546  0 10:08 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-master -d Publisher
505       2549  2546  0 10:08 ?        00:00:01 /usr/bin/python2.6 /usr/bin/salt-master -d EventPublisher
505       2554  2546  0 10:08 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-master -d ReqServer_ProcessManager
505       2555  2554  0 10:08 ?        00:00:02 /usr/bin/python2.6 /usr/bin/salt-master -d MWorker
505       2556  2554  0 10:08 ?        00:00:02 /usr/bin/python2.6 /usr/bin/salt-master -d MWorker
505       2559  2554  0 10:08 ?        00:00:02 /usr/bin/python2.6 /usr/bin/salt-master -d MWorker
505       2562  2554  0 10:08 ?        00:00:02 /usr/bin/python2.6 /usr/bin/salt-master -d MWorker
505       2565  2554  0 10:08 ?        00:00:02 /usr/bin/python2.6 /usr/bin/salt-master -d MWorker
505       2570  2554  0 10:08 ?        00:00:00 /usr/bin/python2.6 /usr/bin/salt-master -d MWorkerQueue
root     13497 13473  0 14:49 pts/0    00:00:00 grep salt-master
```

**Comment by cachedout** [comment]
@jacksontj Just pinging you to ensure you saw the above reply. Thanks!

**Comment by jacksontj** [comment]
OIC, yea that is a problem :) PR #28097 (2015.5) and #28098 (2015.8) for the fixes :)

**Comment by cachedout** [comment]
Closing in favor of #28097

**Pull request closed without merging**
