### PR TITLE
correct encoding for subprocess environments

### PR DESCRIPTION
**Pull request by unixtastic**
### What does this PR do?
Salt states that start a subprocess fail on a UnicodeEncodeError. This affects many kinds of salt states. This PR fixes the environment provided to subprocesses. 

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/45783

### Previous Behavior

Unicode failures whilst starting subprocesses. This affects many states, one example is cron.present

      ID: clean_tmp
    Function: cron.present
        Name: find /tmp -name test.tmp -delete
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1843, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/cron.py", line 349, in present
                  identifier=identifier)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cron.py", line 461, in set_job
                  lst = list_tab(user)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cron.py", line 293, in list_tab
                  data = raw_cron(user)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cron.py", line 270, in raw_cron
                  python_shell=False)).splitlines(True)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 1318, in run_stdout
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 547, in _run
                  proc = salt.utils.timed_subprocess.TimedProc(cmd, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/utils/timed_subprocess.py", line 42, in __init__
                  self.process = subprocess.Popen(args, **kwargs)
                File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
                  errread, errwrite)
                File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
                  raise child_exception
              UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-32: ordinal not in     range(128)
     Started: 17:41:19.429815
    Duration: 106.483 ms

### New Behavior
States that depend on starting a subprocess work as expected.

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by damon-atkins** [comment]
https://github.com/unixtastic/salt/blob/oxygen/salt/modules/cmdmod.py#L437

**Comment by unixtastic** [comment]
@damon-atkins Can you add a couple of sentences explaining what you mean?

**Comment by damon-atkins** [comment]
FYI https://github.com/unixtastic/salt/blob/oxygen/salt/modules/cmdmod.py#L437  this code in this section is the same fix you are trying to do.  From a point of merging code forward it would be best if its the same.  Pls review.

**Review by terminalmage — CHANGES_REQUESTED** [review]
We shouldn't be encoding the environment variables, this produces a bytestring on Python 3 which causes a completely separate set of problems, this was fixed already in the `oxygen` branch as part of a larger effort toward improving unicode support.

**Comment by damon-atkins** [comment]
@terminalmage   I think it might be best to announce PY3 and 2018.2 first version to support international languages.  And push people to PY3 2018.2 if they want  international languages.  i.e. note on the download page.  (Not PY2 at this stage, esp. Windows)

Hence this PR could be closed?

**Comment by terminalmage** [comment]
Yeah, this definitely isn't going to be fixed in the 2017.7 release cycle, I would ask the OP to re-evaluate on 2018.3.0.

**Comment by rallytime** [comment]
@unixtastic Thank you for submitting this fix. However, given the discussion above, and all of the unicode work we've been doing in the 2018.3 branch, I am going to close this PR.

Please give the 2018.3 branch a try and see if you are still running into this issue, and if so, then a fix against that branch will be considered. Thanks again!

**Pull request closed without merging**
