### PR TITLE
Master spot instances

### PR DESCRIPTION
**Pull request by bryceml**
### What does this PR do?
It uses spot instances if they are available at the moment

### Previous Behavior
We always used on-demand instances

### New Behavior
It attempts to use a spot instance before trying an on-demand instance

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by garethgreenaway — APPROVED** [review]

**Review by s0undt3ch — APPROVED** [review]
We should probably do this in sre jenkins? Specially now that we have a master branch off of 2019.2.1?

**Comment by bryceml** [comment]
Yeah, we'll have to do it there too.  We'll need it here too for PR's.

**Comment by bryceml** [comment]
I realized we also need to reduce the timeout from 6 hours to something like 5 hours and 45 minutes so that we can still attempt to download artifacts if it times out.

**Comment by bryceml** [comment]
re-run full all

**Comment by bryceml** [comment]
@s0undt3ch 
centos7 tcp died
fedora-29 and amazon-2 had a salt-minion or salt-master not start up for the multi-master test
centos7 couldn't finish in time

Can we extend the startup time for the multi-master test and then just leave centos 7 out of spot instances and leave it on a c5.xlarge or something?

**Comment by s0undt3ch** [comment]
I'd say yes to all accounts.
For multimaster, look at `tests/multimaster/__init__.py`

**Review by twangboy — APPROVED** [review]

**Review by Akm0d — APPROVED** [review]

**Comment by Akm0d** [comment]
re-run debian9

**Comment by Akm0d** [comment]
re-run opensuse15

**Comment by Akm0d** [comment]
re-run centos7

**Comment by Akm0d** [comment]
re-run fedora29

**Comment by Akm0d** [comment]
re-run macosxmojave

**Comment by Akm0d** [comment]
re-run windows2019

**Review by s0undt3ch — APPROVED** [review]

**Review by waynew — APPROVED** [review]

**Review by Akm0d — APPROVED** [review]

**Review by dwoz — APPROVED** [review]

**Pull request merged**
