### PR TITLE
Hide minion config page, add master config file

### PR DESCRIPTION
**Pull request by twangboy**
### What does this PR do?
- Hides minion config installer page when minion not set for install
- Adds master config file
### What issues does this PR fix or reference?

https://github.com/saltstack/zh/issues/893
### Tests written?

NA

### CODE REVIEW

**Comment by cachedout** [comment]
Does this mean that what's in `pkg/windows/buildenv/conf/master` will be used as the default master config file for Windows?

**Comment by twangboy** [comment]
@cachedout Yes, but I believe it's all commented out right now. I went through and changed what I thought was applicable to Windows to show Windows type paths instead of Linuxy ones. I just got a sample config from one of our customers who's been using Master on Windows for some time. I'm going to go through that and see what needs to apply here. He also said he has some customizations that they use for Python 3. So, apparently they've been using Windows Master with Python 3. He's been pushing those commits to develop.

**Comment by cachedout** [comment]
I am extremely reluctant to start down the road of splitting off config files by platform. The last thing I want to get into is a situation where we have to update a bunch of configuration files by hand every time somebody wants to make a simple documentation change, for example.

If we need different configuration values by platform, we should be handling those cases as we have always done -- by implementing that logic in the config parser itself.

**Comment by twangboy** [comment]
@cachedout This is how the minion config file for Windows is handled. How should we approach this then?
@UtahDave any suggestions?

**Comment by UtahDave** [comment]
Hm. We've been shipping a custom minion config in the Salt Windows installer since the beginning. Partially because it was the easier quick fix. I saw it kind of like the little patches that packagers often add to the rpm packages.

This will complicate how we build the Windows installers.
Mike are you ok with adding this change to the shipped master config for now and creating another issue to modify the config parser to work with defaults in Windows? That would be another project to work on .

**Comment by cachedout** [comment]
I'm OK with it so long as sync'ing the master/minion config files from their primary location in the repo to the `pkg/` dir is something that's added to the packaging checklist. Yes, let's also create a separate issue to try to reduce duplication since this sort of thing kind of drives me nuts. ;]

**Pull request merged**
