### PR TITLE
[2016.11] Dynamic DNS Runner and VMware cloud driver Refactors

### PR DESCRIPTION
**Pull request by nmadhok**
### What does this PR do?

Dynamic DNS Runner Refactors
VMware Cloud Driver Refactors

### CODE REVIEW

**Comment by nmadhok** [comment]
@rallytime

**Comment by nmadhok** [comment]
@rallytime I have no idea why the lint test is failing

**Comment by cachedout** [comment]
Hi @nmadhok 

Thanks for this.

Typically we don't put refactors into minor releases, since they are bug-fix only. Could we move this to the develop branch?

**Comment by nmadhok** [comment]
@cachedout I'll create a Pull Request for the develop branch shortly. Thanks!

**Pull request closed without merging**
