### PR TITLE
add module and state to help create txt docs from highstate data

### PR DESCRIPTION
**Pull request by steverweber**
### What does this PR do?

auto generates system documents in markdown format using highstate information.

### CODE REVIEW

**Comment by steverweber** [comment]
this was a best efforts to create meaningful documents.. it is still lacking in functionality..

That said, it works well for the states I manage, so it's a start.

**Comment by steverweber** [comment]
example output:


__Short description__: CPU server biglinux servers are (four-socket and large memory good for parallel jobs)

Configuration Management
===============================================================================

```
####################################################
fqdn: cpubig-pr1-01.math.private.uwaterloo.ca
os: Ubuntu
osfinger: Ubuntu-16.04
mem_total: 257841MB
num_cpus: 112
ipv4: ['127.0.0.1', '172.27.7.113']
master: salt.math.private.uwaterloo.ca
####################################################
```

This system is fully or partly managed using Salt.

The following sections are a rendered view of what the configuration management system
manages on this system. Each item is handled in order from top to bottom unless some requisites like `require`
or `after changes, run or update` force other ordering.

file: uwl.hosts
-----------------------------------------------------------------
* state: file.managed
* name: ```/etc/hosts```

file stat /etc/hosts
```
gid: 0
group: root
mode: '0644'
size: 2360
uid: 0
user: root
```
file data /etc/hosts
```
# define ipv4 after ipv6 so the ipv4 address is used when referencing localhost
::1                 localhost localhost.localdomain localhost6 localhost6.localdomain6
127.0.0.1           localhost localhost.localdomain localhost4 localhost4.localdomain4
```


pkg: mfcf._common.xhier_auth pkgs
-----------------------------------------------------------------
* state: pkg.installed
* name: ```mfcf._common.xhier_auth pkgs```


```
install: ['tcsh', 'bash', 'ksh']
```


cmd: uwl.sysctl
-----------------------------------------------------------------
* state: cmd.wait
* name: ```sysctl --system```

run or update after changes in:
 * [file: uwl.sysctl.config](#file-uwlsysctlconfig)



file: uwl.sysctl.config
-----------------------------------------------------------------
* state: file.blockreplace
* name: ```/etc/sysctl.conf```

after changes, run or update:
 * [cmd: uwl.sysctl](#cmd-uwlsysctl)

ensure block of content is in file
```
#uwl.sysctl.config
# ipv6 causes issues with sshd xforwarding.. slow 60sec timeout
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1

```


Other information
==================================

```

salt grain: ip_interfaces
-----------------------------------------------------------------
[('eno1', ['1.7.7.113']), ('eno2', []), ('eno3', []), ('eno4', []), ('lo', ['127.0.0.1'])]


salt grain: hwaddr_interfaces
-----------------------------------------------------------------
[('eno1', '8:66:da:f1:4f:2c'), ('eno2', '01:66:da:f1:4f:2d'), ('eno3', '01:66:da:f1:4f:2e'), ('eno4', '10:66:da:f1:4f:2f'), ('lo', '00:00:00:00:00:00')]


# iptables-save
-----------------------------------------------------------------
*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -s 0.0.111.18/32 -p tcp -m state --state NEW -m tcp --dport 5666 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -p udp -m state --state NEW -m udp --dport 60000:61000 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
COMMIT


# ip6tables-save
-----------------------------------------------------------------
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT DROP [0:0]
COMMIT

**Comment by cachedout** [comment]
This is WAY COOL! I love this!

Even though it's a first revision, I would like to ship this with Oxygen so we can get people using and improving it. I am going to tag @saltstack/team-core for other thoughts.

**Comment by steverweber** [comment]
@cachedout Oxygen = doxygen ?

**Comment by steverweber** [comment]
opps disregard Oxygen is version alias :)

**Comment by rallytime** [comment]
I like it! A very cool idea.

But I agree that this should go into `develop` for the Oxygen release.

**Comment by steverweber** [comment]
@rallytime  so a new PR on develop branch.. sure i'll do that

**Pull request closed without merging**
