### PR TITLE
[FEATURE] retcode passthrough exitstatus (take 2)

### PR DESCRIPTION
**Pull request by plastikos**
### What does this PR do?

It passes the `retcode` through to the `salt` and `salt-call` executable exit status.

This is a rebase of #35282
### What issues does this PR fix or reference?
#18510
### Previous Behavior

The `retcode` from states was not reflected in the command line executable exit status
### New Behavior

Non-zero `retcode` from salt states is used for the exit status of `salt` and `salt-call` - unless a "higher priority" error occurs in the specific executables.
### Tests written?

Yes

### CODE REVIEW

**Comment by plastikos** [comment]
I am unable to reproduce the documentation build failure and It's unclear what the failure is.  I do notice that ``exit_codes.rst`` isn't included in any TOC - although that's true of *many* pages.

**Comment by thatch45** [comment]
Sorry @plastikos but I don't think we are going to be able to get this into Carbon :(
We are branching today, or at least that is the goal, and this is far to invasive to push yet

**Comment by plastikos** [comment]
Bummer.

**Comment by plastikos** [comment]
Obsoleted by #36065

**Pull request closed without merging**
