### PR TITLE
Fix #24360

### PR DESCRIPTION
**Pull request by jfindlay**
Fix #24360

### CODE REVIEW

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
@dr4Ke, I spent some time digging through [this error](https://jenkins.saltstack.com/job/salt-pr-rs-ubuntu14.04-n/6219/testReport/junit/unit.states.grains_test/GrainsTestCase/test_absent_delete/) but haven't found the bottom.  It seems that there is something broken in the code that this test is legitimately catching.

**Comment by dr4Ke** [comment]
You're right. I checked out my branch, ran the test and it triggered the same error. Then I edited the `grains_test.py` file, with no meaningful change, and the error was gone. I couldn't reproduce it after that. I don't understand why it was happening in the first place…
Could it be a not clean git working directory? But for jenkins, it seems odd, as it's working on a completely new tree each time, right?

**Comment by jfindlay** [comment]
@dr4Ke, my experience was similar.  It makes me wonder whether the test is creating actual grains on the system and this is somehow affecting the test.

**Comment by dr4Ke** [comment]
OK. After digging a little, I can reproduce this issue reliably. It happens only once on my computer. The second execution always works. After the first execution, there is a `/tmp/grains` file remaining, and it contains `foo: null`. When this file exists and has a `foo` grain, the test succeeds. When this file doesn't exist or contains a `foo` grain, it fails.
Now, I'll have to find a way to fix this issue.

**Comment by dr4Ke** [comment]
I nailed it. Fixed in 09d0071ac5a18206978c6a2092485f55b8177ee6

**Comment by jfindlay** [comment]
@dr4Ke, nice, thanks.  It will be easiest if you you include that commit in your pull request, #24360, and also https://github.com/jfindlay/salt/commit/1f5836d0bb4635de4bd0fe39fb8121b197e11cc1, then we can close this one.

**Pull request closed without merging**
