### PR TITLE
Various SMTP returner fixes

### PR DESCRIPTION
**Pull request by whiteinge**
### What does this PR do?

SMTP returner breakage.
### What issues does this PR fix or reference?

The  `renderer` & `template` additions to the SMTP returner are not working with default settings. The resulting email was blank and the Subject line was `<StringIO object>`. Switching to only the 'jinja' renderer produces `<StringIO object>` for both the body and the subject.
### Previous Behavior

Not working with default settings.
### New Behavior

Backward-compatible fixes assuming the `renderer` & `template` additions were indeed broken as previously asserted.
### Tests written?
- [ ] Yes
- [ ] No
- [x] Not sure

### CODE REVIEW

**Comment by whiteinge** [comment]
I would appreciate a little assistance on this, if someone has time. I didn't dive back to see if they were broken recently or broken on arrival. There are tests for this module but I didn't look at them to see what they missed.

**Comment by whiteinge** [comment]
Re: the test failure in Jenkins. `compile_template` can return a variety of things depending on the renderer(s) used, which makes sense. The email body & subject need to be strings. How to enforce?

**Comment by rallytime** [comment]
@jfindlay Can you take a look here when you get a moment?

**Comment by whiteinge** [comment]
I found the subject setting was also messed up.

Based on @rallytime's feedback I added a commit to explicitly check for the StringIO object that Jinja returns. This should be more error-tolerant.

**Comment by whiteinge** [comment]
Go Go Jenkins!

**Comment by whiteinge** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Pull request merged**
