### PR TITLE
Improvements to data module; behave much more like a dict

### PR DESCRIPTION
**Pull request by The-Loeki**
Adding 
`keys()`
`items()`
`values()`
`pop(key, default=None)`
`get(key, default=None)` (with additional list support)
`has_key(key)`

methods for utilizing it much more like a dict

deprecate `getval` and `getvals`

### CODE REVIEW

**Comment by rallytime** [comment]
Thanks @The-Loeki! Can you add version added directives to all of the new functions you added here? Right after the function definition, just add `.. versionadded:: Beryllium`.

**Comment by The-Loeki** [comment]
Sure @rallytime, there you go :)

**Comment by rallytime** [comment]
Thanks!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by The-Loeki** [comment]
w00h00 Jenkins went & kicked arse :+1:

**Comment by thatch45** [comment]
Very nice! Thanks @The-Loeki !

**Pull request merged**
