### PR TITLE
Adding SCP_NOT_FOUND exit code

### PR DESCRIPTION
**Pull request by zyio**
Not having scp/openssh-clients on the client server will result in a generic thin based error.

Testing for scp and then throwing a new error appropriately.

Re: #25478 and #25026

### CODE REVIEW

**Comment by jfindlay** [comment]
@zyio, excellent, thanks.  In the future you are welcome to submit fixes directly to the oldest supported release branch, see https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

**Comment by zyio** [comment]
Ahh, cheers @jfindlay . Wasn't too sure with this one if it was classed as a bug-fix or new functionality.

**Comment by jfindlay** [comment]
@zyio, yes, I was just thinking that, sorry.  I think it would definitely add value to the two situations you linked to, but I'll let @thatch45 or @basepi decide.

**Comment by tjstansell** [comment]
The method used here for finding scp isn't exactly a portable one.  Some of our boxes (solaris) don't have /bin/bash (we install our own in /usr/local/bin/bash) so it leads to an obscure failure.  I hacked our version of the code to simply run `/bin/env which scp` to get around it, but someone should re-think the best way to detect if scp exists on the remote box.

**Comment by basepi** [comment]
@zylo Any reason `/bin/env which scp` wouldn't work for you as well? That seems like the better path here.

**Comment by zyio** [comment]
That solution seems fine to me.

My original intention was to just use ```command -v scp``` which I think should be POSIX compliant, but then I got tripped up by popen and whacked ```/bin/bash -c``` in front of it to make it work, previous intentions temporarily forgotten.

**Comment by basepi** [comment]
@tjstansell if you have a few minutes, could you submit your fix as a pull request?

**Comment by tjstansell** [comment]
I simply changed it to /bin/sh, because after doing some research, /bin/env doesn't exist everywhere and supposedly even /usr/bin/env doesn't exist everywhere ... though i'm not sure where it is missing.  Also, there is quite a bit of disagreement around `which` being portable too ... and `command -v` seems to be POSIX compliant as @zyio mentioned, so this seems to be the most portable method to find a command.

**Comment by basepi** [comment]
Thanks, that's perfect!

**Comment by zyio** [comment]
Nice one, cheers folks.

**Pull request merged**
