### PR TITLE
Fix pillar include merge order

### PR DESCRIPTION
**Pull request by steverweber**
### What does this PR do?
fix Pillar includes so they don't override whats in the current sls file.

### possible breakage
this change could cause breakage... so perhaps should add a configuration option and have a migration strategy.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/39860

### Tests written?
Yes, however could use another test for pillars with multiple layers of includes

### CODE REVIEW

**Comment by dubb-b** [comment]
Go Go Jenkins!

**Comment by steverweber** [comment]
sorry I merged to develop, I think this should be back ported,

**Review by terminalmage — APPROVED** [review]

**Comment by rallytime** [comment]
@steverweber There is a related test failure on this: `unit.test_pillar.PillarTestCase.test_malformed_pillar_sls`. Can you take a look?

https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/18258/testReport/junit/unit.test_pillar/PillarTestCase/test_malformed_pillar_sls/

**Comment by steverweber** [comment]
seems the test cases were written with the idea that includes override the pillar vars.

I strongly feel this should be changed to be the other way around.
However this change can cause possible breakage... so perhaps should add a configuration option and have a migration strategy.

needs more feedback.

**Comment by vbatoufflet** [comment]
Hi all,

When I read “this change could cause breakage... so perhaps should add a configuration option and have a migration strategy.” and I see that the change has however been merged, I wonder where is such option to switch back to the old behavior?

The logic has been changed in a **minor** release from 2017.7.2 to 2017.7.3, breaking all the pillar inclusion logic for already existing setups.

Do you plan to implement such switch?

Thanks in advance for your help.

**Comment by steverweber** [comment]
untested

on your salt master include the previous infoblox.py and infoblox.py
https://docs.saltstack.com/en/latest/ref/configuration/master.html#std:conf_master-file_roots

```
mkdir -p /srv/salt/_modules
cd /srv/salt/_modules
wget https://raw.githubusercontent.com/saltstack/salt/2017.7/salt/modules/infoblox.py
mkdir -p /srv/salt/_states
cd /srv/salt/_states
wget https://raw.githubusercontent.com/saltstack/salt/2017.7/salt/states/infoblox.py
```

salt \* saltutils._sync_all

**Comment by steverweber** [comment]
@vbatoufflet 
I agree this should not have been merged on minor.
sorry, to have caused frustration to you and others.

**Comment by terminalmage** [comment]
@steverweber Can you work on gating this behind a config option?

**Comment by vbatoufflet** [comment]
@steverweber any chance that you can switch back to the old behavior on the 2017.7 branch?

**Comment by steverweber** [comment]
I'm too swamped. Keep in mind flipping it around could then cause breakage to users expecting includes to be over-writable.

**Comment by terminalmage** [comment]
I'll look at adding an option to switch back to the old behavior.

**Comment by vbatoufflet** [comment]
@steverweber so I'll keep my production servers pinned to the 2017.7.2 version if I want Salt not to break my setup…

@terminalmage thanks!

**Comment by terminalmage** [comment]
@vbatoufflet https://github.com/saltstack/salt/pull/46669

**Comment by vbatoufflet** [comment]
Great @terminalmage, thanks. I'll follow the progress on the linked issue then 👍

**Pull request merged**
