### PR TITLE
moving to salt.utils.pushover

### PR DESCRIPTION
**Pull request by garethgreenaway**
Moving common code from pushover module and returner to salt.utils.pushover.
A few general bug fixes.

### CODE REVIEW

**Comment by jfindlay** [comment]
@garethgreenaway, excellent.  There seems to be some test errors.

**Comment by garethgreenaway** [comment]
Looks like ones from a previous change to the slack module and returner.

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Looks great, thanks as always @garethgreenaway !

**Pull request merged**
