### PR TITLE
Load faster versions of safe loaders as well

### PR DESCRIPTION
**Pull request by jacksontj**
The C versions of the loader/dumper are 5-10x faster than the python
versions. We already do this for the "unsafe" ones, this diff simply
adds it for the "safe" ones.

### CODE REVIEW

**Comment by jacksontj** [comment]
Seems like CI doesn't like me:

- The py3 failures seem unrelated, 
- jenkins/PR/salt-pr-rs-cent7-n also seems unrelated
- jenkins/PR/salt-pr-linode-ubuntu14-n unable to reproduce those errors locally

**Comment by jacksontj** [comment]
@cachedout want me to rebase and try again?

**Comment by jacksontj** [comment]
@rallytime any ideas/details why this one is failing?

**Comment by rallytime** [comment]
@jacksontj I wasn't able to check these results before they timed out, so I have restarted them.

**Review by terminalmage — APPROVED** [review]
This makes sense. @rallytime any objections with backporting this into 2018.3?

**Comment by terminalmage** [comment]
re-run all

**Comment by rallytime** [comment]
@terminalmage Nope, no objections. Labeled for backport.

**Comment by rallytime** [comment]
There are a couple of related test failures on this one, however:

- unit.utils.test_yamlloader.YamlLoaderTestCase.test_yaml_with_colon_in_inline_dict
- unit.templates.test_jinja.TestCustomExtensions.test_load_yaml

@jacksontj Can you take a look?

**Comment by terminalmage** [comment]
I don't know that we're going to be able to merge this. Those failures are happening because we have subclassed the SafeLoader and have made modifications on top of it. Those changes don't work when the CSafeLoader takes the place of the SafeLoader.

**Comment by jacksontj** [comment]
@terminalmage got a way to reproduce the error locally? I'd gladly take some time to dig into it, I'm just unable to repro these failures locally (so maybe some yaml version difference or something).

**Comment by terminalmage** [comment]
@jacksontj Sure. The failure is a test I added to confirm a fix that was made to handle colons in inline python unicode literals, see https://github.com/saltstack/salt/pull/47104. And you can reproduce the failure like so:

```
>>> import salt.utils.yaml
>>> salt.utils.yaml.safe_load('''\
... foo: {u'url': u'https://foo.com'}
... ''')
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/testing/salt/utils/yamlloader.py", line 226, in safe_load
    return yaml.load(stream, Loader=Loader)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib64/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "_yaml.pyx", line 707, in _yaml.CParser.get_single_node (ext/_yaml.c:8308)
  File "_yaml.pyx", line 725, in _yaml.CParser._compose_document (ext/_yaml.c:8581)
  File "_yaml.pyx", line 776, in _yaml.CParser._compose_node (ext/_yaml.c:9306)
  File "_yaml.pyx", line 890, in _yaml.CParser._compose_mapping_node (ext/_yaml.c:10838)
  File "_yaml.pyx", line 776, in _yaml.CParser._compose_node (ext/_yaml.c:9306)
  File "_yaml.pyx", line 890, in _yaml.CParser._compose_mapping_node (ext/_yaml.c:10838)
  File "_yaml.pyx", line 732, in _yaml.CParser._compose_node (ext/_yaml.c:8685)
  File "_yaml.pyx", line 905, in _yaml.CParser._parse_next_event (ext/_yaml.c:11045)
yaml.scanner.ScannerError: while scanning a plain scalar
  in "<byte string>", line 1, column 15
found unexpected ':'
  in "<byte string>", line 1, column 22
```

The reason we needed that fix is because one of the ways people use Salt is using the `json` Jinja filter to dump a data structure to inline JSON with an SLS file. Since PyYAML is able to load inline Python data structures, loading a string like the one in the example above will result in a ScannerError.

**Comment by jacksontj** [comment]
That sounds like we should have made that behavior (loading raw prints of python objects) as a special loader, since that *is* invalid yaml :/ How tied are we to that behavior? If very, then maybe I can add a "high-perf" loader option that doesn't have that magic behavior?

**Comment by jacksontj** [comment]
Superseded by #48194

**Comment by rallytime** [comment]
@jacksontj and @terminalmage I think this has been replaced with #48309, yes?

**Comment by rallytime** [comment]
I'm fairly certain this was replaced by #48309 so I will close this.

If I have closed this too quickly, let me know I will re-open. :)

Note, there is a merge conflict in `salt.utils.yamlloader.py` that will need to be fixed first.

**Comment by jacksontj** [comment]
Your assessment looks accurate :) Thanks!

**Pull request closed without merging**
