### PR TITLE
sysutils/py-salt: fix the efi grain on FreeBSD

### PR DESCRIPTION
**Pull request by asomers**
The logic to detect whether we booted from EFI only worked on Linux and Apple, AFAICT.

### What does this PR do?

Correctly detects EFI on FreeBSD

### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
grains.get efi would always return False on FreeBSD

### New Behavior
grains.get efi will return the correct value on FreeBSD

### Merge requirements satisfied?
- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by twangboy — CHANGES_REQUESTED** [review]
This is gonna need a test and a changelog.

**Comment by asomers** [comment]
> This is gonna need a test and a changelog.

I can add a changelog entry.  But as for tests, there is literally nothing that this function would do except return the value of our mock function.  In other words, there's no way to write a test for this function that's different from simply writing the function itself.  That's why one-liners usually don't need to be unit-tested.

**Comment by dwoz** [comment]
@asomers Please add a changelog file.

**Review by dwoz — DISMISSED** [review]
Approved pending changelog.

**Comment by asomers** [comment]
@dwoz changelog added.

**Review by dwoz — APPROVED** [review]

**Pull request merged**
