### PR TITLE
note only applies to `salt` and `salt-ssh` commands

### PR DESCRIPTION
**Pull request by vernondcole**
### What does this PR do?
Removes a NOTE which does not apply to several CLI commands

### What issues does this PR fix or reference?
#40888

### Old Behavior
Note was included with salt-call, salt-key, and salt-cloud commands, which do not have a --static option. Attempt to add the option suggested by the Note would give an error.

### New Behavior
Note is only included in docs for `salt` and `salt-ssh` commands.

### Tests written?
No.  PR addresses documentation only.

`make html` was run and correct results appear on the appropriate pages.

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by vernondcole** [comment]
@Ch3LL This is a (requested) documentation-only PR. Do we _really_ have to have all tests pass before merge is possible? Am I expected to debug the failing tests?

**Comment by Ch3LL** [comment]
we just need to ensure the doc tests pass. can you please apply your patch onto the master branch and not 2019.2.3 branch.

**Comment by vernondcole** [comment]
will submit a new PR without the git foul-ups

**Comment by vernondcole** [comment]
@Ch3LL new, simplified, PR to master branch.

**Pull request closed without merging**
