### PR TITLE
Fix pylint on 2015.2 branch

### PR DESCRIPTION
**Pull request by rallytime**

### CODE REVIEW

**Comment by thatch45** [comment]
Thanks @rallytime the pylint display has been broken for PRs for a while now....

**Comment by rallytime** [comment]
Oh really? That's not good.

**Comment by s0undt3ch** [comment]
You need to go to the console and click the pylint job and from there you can see the violations.

**Comment by s0undt3ch** [comment]
Its something broken in one of the plugins. Or something I need to fix on the build params.

**Comment by thatch45** [comment]
Ahh, ok, I will click around some more, I keep getting a blank screen

**Comment by s0undt3ch** [comment]
On the main PR job, click console. Once there click on the pylint job and then violations.

Its something not working as I thought it would which needs some love.

**Comment by s0undt3ch** [comment]
We might need 2 bit checkouts for it to work which is not good.

**Comment by s0undt3ch** [comment]
Git

**Comment by thatch45** [comment]
Ahh, ok :)

**Pull request merged**
