### PR TITLE
Add boardname grain

### LINKED ISSUE #63131: [FEATURE REQUEST] add boardname grain
**Describe the solution you'd like**
Add a grain to capture `board_name` information.

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

### PR DESCRIPTION
**Pull request by nicholasmhughes**
### What does this PR do?
See issue for details.

### What issues does this PR fix or reference?
Fixes: #63131

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by nicholasmhughes** [comment]
re-run pr-centos-7-x86_64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-ubuntu-2204-amd64-py3-pytest

**Comment by nicholasmhughes** [comment]
re-run pr-ubuntu-2004-amd64-py3-pytest

**Comment by lukasraska** [comment]
@nicholasmhughes what about other operating systems / architectures? Seems like the information can be retrieved from dmidecode as well, for Windows I assume https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-baseboard might be the correct WMI class.

For DeviceTree, the most reasonable field is `model`, but it's already being used for `productname` (https://github.com/saltstack/salt/blob/master/salt/grains/core.py#L1656 , this is for example value of `model` on RPi - `Raspberry Pi 4 Model B Rev 1.1` ), so that could be just ignored I guess.

**Review by twangboy — APPROVED** [review]

**Comment by Ch3LL** [comment]
@nicholasmhughes any thoughts on @lukasraska 's comment?

**Comment by nicholasmhughes** [comment]
I don't have a use case for other operating systems and I don't have any way to test them. I'd prefer to contribute this piece and allow the community to expand on it as the need arises.

**Pull request merged**
