### PR TITLE
Improvements on Debian-style apache utilities a2(en|dis)(mode|site|conf)

### PR DESCRIPTION
**Pull request by zigarn**
- Some fix on apache modules handling
- Add state for `a2xxsite` + tests
- Add module functions and state for `a2xxconf` + tests

:warning: `versionadded::` are left blank for setting the right version when merging this PR.

### CODE REVIEW

**Comment by cachedout** [comment]
@zigarn The `versionadded` will be `Boron`.

It looks like there are some failing tests here. Could you please have a look?

**Comment by zigarn** [comment]
Yark! I forgot to test after adding the `which` decorator...
Will set the `versionadded`.

**Comment by zigarn** [comment]
Humm, no, it's simply that `a2enconf` is available for me!

**Comment by cachedout** [comment]
Looks likeyou left a stray debug statement in there. Take a look at the lint report, please. :]

**Comment by cachedout** [comment]
This is really nicely done. Thank you very much @zigarn. This will be an excellent addition.

**Pull request merged**
