### PR TITLE
Provide a helper function so that merging in jinja in formulas can be…

### PR DESCRIPTION
**Pull request by puneetk**
… similar to merging in pillars.

### CODE REVIEW

**Comment by babilen** [comment]
It might make sense to provide this as jinja filter, but for that we need to think about some global design goals. It doesn't necessarily fit the "execution module" semantics, but is urgently needed in a number of places in which you have to merge data.

So, this would definitely be an improvement, but I have the feeling as if this should rather be solved by either making it easier to use `_utils/*` in other renderers or, at least, providing this as jinja filter.

**Comment by cachedout** [comment]
@babilen I agree with your point that this would potentially be more useful as a jinja filter but I don't think that precludes it from existing on the exec module layer either. I'm going to go ahead and merge this and we'll hopefully get a jinja filter added for this down the road as well.

**Comment by babilen** [comment]
@cachedout Yeah, absolutely. I was just summarising a discussion I had with @puneetk in `#salt` about this issue. Thanks for merging it, salt is definitely better of with it.

**Comment by cachedout** [comment]
@babilen Agreed on all points. Thanks for the excellent feedback on this one. This will definitely be a good improvement.

**Pull request merged**
