### PR TITLE
Port #50617 to master

### PR DESCRIPTION
**Pull request by alexey-zhukovin**
### What does this PR do?

Port #50617 to master

### CODE REVIEW

**Comment by mchugh19** [comment]
As this is an RFC, the `Needs Testcase` label isn't needed.

Since this was not submitted, by @isbm, is the intent to continue this work? While I'd be in full support of developing capabilities, if there isn't intent to complete the RFC then there probably isn't much point in discussing it.

**Comment by isbm** [comment]
I have no idea what "needs testcase" means here.

**Comment by dwoz** [comment]
The should be a SEP if it is still needed.

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
