### PR TITLE
Fix test_pkgrepo_01_managed and test_pkgrepo_02_absent for Ubuntu.

### PR DESCRIPTION
**Pull request by ldav1s**
requires_salt_modules decorator always disabled these tests.
removed test skipping, the salt states should handle it now.
Obsolete python-software-properties replaced by software-properties-common.
Removed PPA which has not been updated in 3 years.

### What does this PR do?
Fixes two test cases that never seem to be run on Ubuntu.

### What issues does this PR fix or reference?
In the process of looking at  issue #27181 I noticed that these two test cases never
seemed to be executed on Ubuntu.  When I did figure out why they never were run,
and ran them, they referenced an obsoleted package and referenced PPA repositories
which had not been updated in a while one not updated in years.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs -- not applicable
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html -- not applicable
- [X] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by ldav1s** [comment]
There's a couple of concerns about what I did here:

I don't really understand what the `requires_salt_modules` decorator is really doing, or if `requires_salt_states` is really what should be there.  I commented out `requires_salt_modules` while trying to get the testcase to actually run.  So not sure that this the right thing to do.

I also am concerned about how to keep the PPA tests current, and what happens when there are none of them to run, as any particular PPA may drop support for any distro at any time or go away completely, as what happened in the case of both of the previous tests.  Maybe there's a way to emulate a PPA repo locally, but maybe not.

**Review by s0undt3ch — DISMISSED** [review]

**Comment by s0undt3ch** [comment]
`requires_salt_states` is the right decorator to use.
As for the PPAs going missing, guess we'll have to continuously update them.

**Comment by s0undt3ch** [comment]
Also, `requires_salt_states` skips the test of the state module was not loaded by salt.
As for `requires_salt_modules` it's the same as `requires_salt_states` but for execution modules.

**Comment by ldav1s** [comment]
OK.  Do I need to add any additional docs?  I'm kind of assuming I need to run through the changelog workflow to generate a changelog entry as well as GPG sign the commit.

**Review by Akm0d — DISMISSED** [review]

**Comment by ldav1s** [comment]
The only thing that should have changed is the commit is now GPG signed.

**Comment by ldav1s** [comment]
Hmm...signing that commit seemed to break some checks.

**Comment by ldav1s** [comment]
So why are those 6 builds erroring out?

**Review by s0undt3ch — APPROVED** [review]

**Comment by ldav1s** [comment]
OK.  Is there anything else that's needed from me to merge?

**Comment by ldav1s** [comment]
Is there anything else I need to do for this to be merged?

**Comment by ldav1s** [comment]
Is there anything else I need to do for this to be merged?

**Comment by ldav1s** [comment]
Is there anything else I need to do for this to be merged?

**Comment by ldav1s** [comment]
What (if anything else) is required for this to be merged?

**Comment by s0undt3ch** [comment]
You need to run `pre-commit` on the files you changed, `pre-commit run -av` should do it

**Comment by s0undt3ch** [comment]
The reason it fails now is that, recently we enabled a pre commit hook which cleans up Py2 specific code and six every time we change a file so that we slowly migrate to a Py3 only code base and don't disrupt all open pull requests at once.

**Review by s0undt3ch — APPROVED** [review]

**Comment by ldav1s** [comment]
I guess someone else fixed the pre-commit hook failure.  Seeing all checks pass now.

**Review by s0undt3ch — APPROVED** [review]

**Comment by ldav1s** [comment]
What (if anything else) is required for this to be merged?

**Review by s0undt3ch — APPROVED** [review]

**Comment by s0undt3ch** [comment]
Nothing on your end @ldav1s 
Thank You!

**Pull request merged**
