### PR TITLE
Add the ability to replace existing certificates

### PR DESCRIPTION
**Pull request by joejulian**
Add the option to replace existing tls certificates.

### CODE REVIEW

**Comment by joejulian** [comment]
Is there a way, short of doing a dummy push, to re-trigger the checks? That lint check failed because it was running when I amended my commit.

**Comment by thatch45** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
Thats how :)

**Comment by thatch45** [comment]
Of you can close and re-open the PR

**Pull request merged**
