### PR TITLE
Added check for PyMySQL if MySQLdb import fails

### LINKED ISSUE #26754: MySQLdb-python package should be included with windows minion installer
```yaml
Salt: 2015.5.2
Python: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
Jinja2: 2.7.3
M2Crypto: 0.21.1
msgpack-python: 0.4.5
msgpack-pure: Not Installed
pycrypto: 2.6
libnacl: Not Installed
PyYAML: 3.11
ioflo: Not Installed
PyZMQ: 14.6.0
RAET: Not Installed
ZMQ: 4.0.5
Mako: Not Installed
```
The MySQLdb-python package is a huge pain to install on windows with pip or easy_install since it needs to compile native code and doing that from pip is broken unless you have a magic Visual Studio 2008 setup that I can't seem to replicate.  There is a binary available but it has no .msi so I can't silent install (and therefore can't highstate it onto my own minions).  It would be super convenient if everything could just be included with the windows minion installer.  The mysql module depends on this package.  Without it being bundled, I have to manually run the binary installer .exe and point the GUI at the correct directory which sort of defeats the purpose of being able to highstate my machine into having everything it needs.

Alternatively since it appears MySQLdb-python isn't really being developed anymore you could make the mysql module depend on something like PyMySql instead, which installs just fine on Windows with pip and advertises that it's a drop-in replacement for MySQLdb-python.  It seems like it's under much more active development and is a pure python MySQL client.

If there's some sort of standard way to work around this issue then it's not in any documentation that I can find beyond "install the module somehow"

### PR DESCRIPTION
**Pull request by twangboy**
- Added PyMySQL to dependencies for windows so that it will be bundled with Salt. See the following PRs:
  https://github.com/saltstack/salt-windows-dev/pull/24
  https://github.com/saltstack/salt-windows-dev/pull/25

Fixes #26754

### CODE REVIEW

**Comment by cachedout** [comment]
@twangboy We can merge this but it does mean that the test suite will not test the MySQL module for cases where PyMySQL is installed and MySQLdb is not. Is the use of PyMySQL intended to be a fully-supported configuration? As I understand it, PyMySQL is being bundled with the Windows installer. Is that correct?

**Comment by twangboy** [comment]
@cachedout Yes, PyMySQL is bundled with our windows installation and is supposed to be a drop in replacement for MySQLdb. Is the issue here that we'll now have to support PyMySQL as well as MySQLdb?

@UtahDave ^^^

**Comment by s0undt3ch** [comment]
Also, double check that when freezing, our setup.py picks up that lib.

**Comment by twangboy** [comment]
@s0undt3ch We're not freezing anymore for windows builds. Are we freezing for something else? Should PyMySQL be added to setup.py as a prereq then?

**Comment by cachedout** [comment]
@twangboy The issue is that the test suite tests assumes the MySQLdb. If you replace that connector with something else for certain cases, then you have no assurance that the Salt mysql functionality is working with that secondary connector for those users. If you are OK with Windows users having no test coverage for the salt mysql module, then feel free to merge this at your discretion.

**Comment by s0undt3ch** [comment]
We freeze for smartos I think, but not everything, unlike we did for Windows, so, my concerns are addressed.

**Pull request merged**
