### PR TITLE
Fix masterless jinja imports

### PR DESCRIPTION
**Pull request by dwoz**
### What does this PR do?

Fixes and adds tests for #54765 #54768

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by dwoz** [comment]
re-run full all

**Review by cmcmarrow — APPROVED** [review]

**Comment by kiemlicz** [comment]
I've pulled the `jinja.py` and added to `_utils` dir in state tree root

Still getting:
```
{% from "_common/util.jinja" import retry with context %}    <======================
```

**Comment by s0undt3ch** [comment]
@kiemlicz this PR adds a test which covers the proposed fix.

It seems that what you're trying to do is to "push" the fix to the minions through your state tree. That should be filed as a separate issue so we can better track it. It's not related to the change this PR is addressing.

**Comment by dwoz** [comment]
re-run full all

**Comment by dwoz** [comment]
This PR has the same patch as #54774 and adds tests

**Comment by kiemlicz** [comment]
@s0undt3ch thanks for reply, now I'm truly disappointed

I know I can override the execution modules, state modules etc. using e.g. `_utils` dir from local state tree. 
It was always the fastest way to 'port' the fixes to the running salt version, however it turns that it doesn't work for `utils/jinja.py`: **why?**

Overriding the local installed file: `cp /srv/salt/base/_utils/jinja.py /usr/lib/python3/dist-packages/salt/utils/jinja.py` proves that the fix is working, however the sudden inability to use `_utils/` dir is frightening! Could you explain this please?

**Review by twangboy — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
