### PR TITLE
Add Kafka event return support

### PR DESCRIPTION
**Pull request by zmingee**
### What does this PR do?

Add event return support to Kafka returner module.

Also added a test module and refactored the module.

### Previous Behavior
Event returns were not supported by the Kafka returner module.

### New Behavior
Event returns are now supported by the Kafka returner module.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [Y] Docs
- [N] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [Y] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by krionbsd** [comment]
@zmingee could you move the test under `tests/pytests/unit/returners` and create changelog entry?

**Comment by zmingee** [comment]
@krionbsd I've moved the test module and added the changelog entry as requested.

**Comment by whytewolf** [comment]
@zmingee There seems to be some problems with this PR, some items are being pulled in from other PRs from the last time you pulled in from master. and there are conflicts. Can you please correct these issues.

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
