### PR TITLE
Merge forward from 2014.7 to 2015.2

### PR DESCRIPTION
**Pull request by basepi**
Merge forward from 2014.7 to 2015.2

### CODE REVIEW

**Comment by basepi** [comment]
Hey @belvedere-trading, I just merged this forward your fixes from here: https://github.com/saltstack/salt/pull/19295

Could you double check that I did it correctly? @garethgreenaway had done substantial work on that file in 2015.2, and so the merge forward was not clean. I think I resolved it correctly but it could use a second look.

**Comment by basepi** [comment]
Once this is merged, I will merge from 2015.2 to develop.

**Comment by belvedere-trading** [comment]
I'll take a look when I have a few minutes (should be today/tomorrow).

**Comment by belvedere-trading** [comment]
The merge looks good to me.  Thanks!

**Pull request merged**
