### PR TITLE
utils.jinja: use utils.yamldumper for safe yaml dumping

### PR DESCRIPTION
**Pull request by The-Loeki**
### What does this PR do?
When directly dumping pillar data through jinja's `yaml` filter, the dreaded python unicode objects appear
### What issues does this PR fix or reference?
Seems regression of: 
#30454
#38554

Though I'm not sure that even did it in this case.

I tore out the YAML encoding from the `jinja` util and used the one in `utils.yamldumper`. 

### Previous Behavior
state:
```
my-awesome-conf:
  file.managed:
    - name: /tmp/test
    - source: salt://{{slspath}}/b0rk.jinja
    - template: jinja
```
tmpl:
```
{%- set p_data = salt.pillar.get('salt:master:config', False) %}
{%- if p_data %}
{{ p_data|yaml(False) }}
{%- endif %}
```

result:
```
nodegroups: !!python/unicode ams1: !!python/unicode '*.ams1.*'                                                                                                                                          [1000/1862]
!!python/unicode bastion: !!python/unicode pampus*
!!python/unicode workers: !!python/unicode w*.kube*.*
log_granular_levels: !!python/unicode salt.config: !!python/unicode info
!!python/unicode salt.crypt: !!python/unicode info
!!python/unicode salt.loader: !!python/unicode info
!!python/unicode salt.transport.ipc: !!python/unicode info
!!python/unicode salt.transport.mixins.auth: !!python/unicode info
!!python/unicode salt.transport.zeromq: !!python/unicode warning
!!python/unicode salt.utils.event: !!python/unicode info
!!python/unicode salt.utils.fileserver: !!python/unicode info
!!python/unicode salt.utils.gitfs: !!python/unicode info
!!python/unicode salt.utils.lazy: !!python/unicode info
!!python/unicode salt.utils.process: !!python/unicode info
mine_get: !!python/unicode .*: []
state_output: !!python/unicode mixed_id
log_level_logfile: !!python/unicode debug
pillar_roots: !!python/unicode base:
```
(ah well, you get the point)

### New Behavior
Nice & proper yaml output

### CODE REVIEW

**Comment by The-Loeki** [comment]
* I'm not entirely sure why the test is failing: https://github.com/saltstack/salt/blob/2017.7/tests/unit/templates/test_jinja.py#L564 seems to suggest that the test fails because it's actually rendered properly???

* the other thing is the yaml.load: https://github.com/saltstack/salt/blob/develop/salt/utils/jinja.py#L851 shouldn't that be using the util yamlloader as well (and if yes, how?); 

* otoh I saw mentions that fixing the `yaml` rendering makes the changes global whenever `yaml` is imported; does that mean we have to fix the problem somewhere else?

**Comment by cachedout** [comment]
I'd like @rallytime and @terminalmage to please take a look here.

**Review by terminalmage — COMMENTED** [review]
:+1:

**Comment by sokratisg** [comment]
Dummy question: We're having the exact same issue and we're running Salt on python2.7. Is this PR going to fix problems on python2.7 based Salt as well or not?

**Comment by The-Loeki** [comment]
@sokratisg this was on Py2.7 ;) so the fix should work for you. Beware however that we've encountered similar behaviour for a number of different reasons, so YMMV. https://docs.saltstack.com/en/latest/topics/jinja/index.html#json-decode-list

**Comment by sokratisg** [comment]
@The-Loeki thank you for the prompt response. So, based on your suggestion a better alternative would be to 
A. First pass the yaml list through jinja's yaml serializer and
B. Also pass it through json_decode_list ?

Let's say we have the following yaml list in pillars:
```
this_is_a_list:
  - stringA
  - stringB
  - integerA
```

Should it be parsed like that? `{{ this_is_a_list|yaml|json_decode_list }}`

**Comment by The-Loeki** [comment]
Usually we try to 'just' dump it in the file/yaml first. This mostly 'just works'. In the off chance it doesn't we filter through `yaml`, which then mostly 'just works':

```
this-probably-works: {{ mydict (or list) }}
this-probably-wont:
  {{ mydict }}
this-probably-will:
  {{ mydict|yaml(False)|indent(2) }}
```
Not sure about the decode_list; it's just one of the new jinja filters I noticed (and never used yet) 

Point is that both syntaxes should work fine and mostly do. It's been a regular moving target when the !!unicode things show up for a variety of reasons (and IMHO never should)

**Comment by rallytime** [comment]
@cachedout and @The-Loeki This caused a test failure in the 2017.7 branch: `unit.templates.test_jinja.TestCustomExtensions.test_serialize_yaml_unicode`

**Comment by The-Loeki** [comment]
@rallytime is this failure related to my earlier comments here? https://github.com/saltstack/salt/pull/42064#issuecomment-312421380

**Comment by rallytime** [comment]
@The-Loeki Yes, that test failure is related to your comment, though I am still looking into answers to your questions. I think @terminalmage is the most familiar with that section of the code.

**Comment by rallytime** [comment]
As a reference, this test was added in PR #38554

**Comment by terminalmage** [comment]
So, according to the YAML spec, `!!something` explicitly tags what comes after it with a tag called ``something``, which it is then up to the person implementing the YAML loader/dumper to write a constructor to handle (see [here](http://www.yaml.org/refcard.html)). So, it was technically strictly correct YAML according to the spec, but one of the reasons we have our custom dumper is because including that tag in the dumped output is not useful in Salt.

The test before was written to test the behavior with the YAML tag present, so the test just needed to be updated. I've opened https://github.com/saltstack/salt/pull/44541 to do this.

**Pull request merged**
