### PR TITLE
Boto cfn

### PR DESCRIPTION
**Pull request by tsaridas**
module + state

### CODE REVIEW

**Comment by tsaridas** [comment]
@jfindlay 
I don't know what the rest of the fails are for. Also, you might have a conflict with #21993

**Comment by jfindlay** [comment]
@tsaridas, there's still this [lint error](https://jenkins.saltstack.com/job/salt-pr-lint-n/3886/violations/file/salt/states/boto_cfn.py/).

**Comment by jfindlay** [comment]
@tsaridas, no problem.  You and @mgwilliams can work out any possible conflicts with both of your changes, thanks.

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Pull request merged**
