### PR TITLE
Fix pillar roots order

### LINKED ISSUE #24501: Order in top.sls file is not respected for pillar data in local mode
My pillar setup looks like this:

In the `minion.conf` the `pillar_roots` config looks like this:

``` yaml
pillar_roots:
  lib:
    - /srv/salt/salt-lib/pillar
  base:
    - /srv/salt/pillar
```

My pillar `top.sls` file in `/srv/salt/pillar/top.sls` looks like this:

``` yaml
lib:
  '*':
    - main

base:
  '*':
    - basic
```

The main.sls file in `/srv/salt/salt-lib/pillar/` contains:

``` yaml
test:
  setting: myvalue-main
```

The `basic.sls` file in `/srv/salt/pillar/` contains:

``` yaml
test:
  setting: myvalue-override
```

When I now run 

``` bash
sudo salt-call --local pillar.get test:setting
```

the output is:

```
local:
    myvalue-main
```

The **expected** output would be:

```
local:
    myvalue-override
```

The salt version is 2014.7.1

Is this related to #1432 ?

### PR DESCRIPTION
**Pull request by mkirkland4874**
### What does this PR do?

_get_envs() returns pillar_roots in a non-deterministic order. Update _get_envs() to preserve the order of pillar_roots similar to https://github.com/saltstack/salt/commit/e36d6839d19a669d85ad424aa722d16abd8fc219 for file_roots in state.py.

### What issues does this PR fix or reference?
Fixes: #24501

### Previous Behavior
_get_envs() returns pillar_roots in a non-deterministic order

### New Behavior
_get_envs() preserves the order of pillar_roots

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [N/A] Docs
- [X] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Are you comfortable with adding a unit test for this change?
If not let me know so I can work on it after the 4th of Jan.

And, Thank You!
Happy New Year!

**Comment by mkirkland4874** [comment]
I'm not comfortable adding a unit test for the change but hope the PR is helpful. Thanks.

**Comment by s0undt3ch** [comment]
@mkirkland4874 no worries. I'll add a test for this.

**Review by s0undt3ch — CHANGES_REQUESTED** [review]
We need tests covering this change. A simple unit test asserting proper order is enough.

**Comment by s0undt3ch** [comment]
Oh, I self asigned this to create the tests :)

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
