### PR TITLE
Merge forward 2015.5 -> develop

### PR DESCRIPTION
**Pull request by kiorky**
depends on #24065 #24080
cc @basepi 

```
Conflicts:
  6         doc/topics/tutorials/index.rst
  7         salt/modules/lxc.py
  8         salt/states/file.py
  9         salt/utils/event.py
```

### CODE REVIEW

**Comment by kiorky** [comment]
i will let @basepi do as, usual.

**Comment by kiorky** [comment]
in fact no :) i need it, but wait, im pushing an updated one

**Comment by kiorky** [comment]
im testing the file.managed stuff :...

**Comment by kiorky** [comment]
file stuff is working

**Comment by kiorky** [comment]
(ill ping you when im done with all the stuff i have to orchestrate for the lxc forward success ...)

**Comment by kiorky** [comment]
blocks #23982

**Comment by kiorky** [comment]
do not merge that for the moment, we are doing stuff with @basepi ;)

**Comment by basepi** [comment]
I am going to close this until when I get back from vacation and can merge #24080.

**Pull request closed without merging**
