### PR TITLE
Extend the functionality of ssh_pre_flight with ssh_pre_flight_args

### PR DESCRIPTION
**Pull request by vzhestkov**
### What issues does this PR fix or reference?
Make it possible to pass extra parameters to salt-ssh pre flight script with `ssh_pre_flight_args` from the roster.

### Previous Behavior
No way to pass any parameters to pre flight script.

### New Behavior
Pre flight script can be executed with extra arguments specified in `ssh_pre_flight_args`

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by Ch3LL — CHANGES_REQUESTED** [review]
This will require a changelog and tests. One test I was hoping to add in addition to just ensuring the functionality works, was to ensure someone cannot pass shell injections when using `ssh_pre_flight_args`. For example piping another command or using `;` to then run a different command.

**Comment by vzhestkov** [comment]
@Ch3LL there was a change from @meaksh with the injection prevention fix and additionally different types of tests for it as well as changelog entry.

The only point left is the documentation for the new roster parameter. Could you please give a hint where the documentation regarding the roster file parameters shold be appended?

**Comment by Ch3LL** [comment]
doc/topics/ssh/roster.rst

**Review by Ch3LL — DISMISSED** [review]

**Comment by Ch3LL** [comment]
I just want to get another review on this one. Ping @dwoz can you review please?

**Comment by Ch3LL** [comment]
There are some test failures on windows that are related to this test failure

**Review by dwoz — APPROVED** [review]

**Pull request merged**
