### PR TITLE
Revert PR 60890, different fix for brew pkg

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Reverting https://github.com/saltstack/salt/pull/60890 and taking a different approach to fixing the Mac brew failures.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
This gets us back to using `su` so, Mac tests will hang again?

**Comment by garethgreenaway** [comment]
@s0undt3ch Nope.  The change was shifted to the mac_brew_pkg directly, using sudo, handling the runas in the module, then setting runas to None so it by passing that code block in cmdmod.  Tests do not hand.

**Comment by s0undt3ch** [comment]
This gets us back to using `su` so, Mac tests will hang again?

> @s0undt3ch Nope. The change was shifted to the mac_brew_pkg directly, using sudo, handling the runas in the module, then setting runas to None so it by passing that code block in cmdmod. Tests do not hang.

Huh. That works 😁

**Review by s0undt3ch — DISMISSED** [review]

**Comment by weswhet** [comment]
Nice! This seems like the better approach. A one size fits all approach to running code as a user is gonna be nearly impossible.

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
