### PR TITLE
Fixed powercfg on windows 7

### PR DESCRIPTION
**Pull request by opdude**

### CODE REVIEW

**Comment by jfindlay** [comment]
@opdude, thanks for the fix.  Do you mind if we backport it to the 2015.5 branch?

**Comment by opdude** [comment]
@jfindlay Sure, do you want me to do it in a new PR or will you guys handle it?

**Comment by jfindlay** [comment]
@opdude, we can backport it.

**Comment by rallytime** [comment]
These files aren't present on the 2015.5 branch, so I won't be backporting these. Thanks for the fix @opdude!

**Pull request merged**
