### PR TITLE
Use config data as pillar overrides

### PR DESCRIPTION
**Pull request by alexbleotu**
### What does this PR do?
Added ability to use config data as pillar overrides; the data can then be used as input in external pillar functions. 

This is specially useful if the proxy configuration (`proxy` key) is set in the configuration file and not in the pillar, but any additional configuration data can be included in the pillar so there is more info about the minion, in addition to the `minion_id`

### What issues does this PR fix or reference?
https://github.com/saltstack/morganstanley/issues/20

### Previous Behavior
Config data could not be included as pillar overrides

### New Behavior
`add_to_pillar` key can be added to the config containing the list of config keys to be included as pillar overrides. Subkeys are supported using the the : notation (i.e. `key:subkey`)

### Tests written?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by alexbleotu** [comment]
@cro This is the pull request that includes config data in the pillar, that we have been discussing on the calls

**Comment by damon-atkins** [comment]
Whats the benefit over existing ways to get data from minions?

**Comment by alexbleotu** [comment]
Not sure what other ways you are referring to.

I can describe the benefits for us:

1. The current setup just differentiates the minion as far as external pillars go by minion id, which is not enough for us, as we have a consistent naming scheme (which becomes the minion id), but different teams owning different hosts. Those minions will need to be differentiated by something else, besides the minion_id - an this is where this PR comes in. 

1. Another benefit is where you have different types of minions by definition (i.e. proxy minions). Initially the type of the proxy minion was in the pillar only so it was available in external pillar calls, now it can be in the config as well which makes it not available in the pillar. This PR makes it available as well.

**Comment by garethgreenaway** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
I have some concerns here.

My main issue is that this really undercuts a common usage of pillars as security sandboxes. Often, teams organize multiple git pillars, for example, and assign one team to each time. This change allows for a place where keys are silently replaced, outside of the control of those teams.

I also think it makes pillars even harder to reason about, since now one must also check the configuration for keys that could have been overwritten.

**Comment by thatch45** [comment]
I am going to agree with @cachedout here, I worry about using pillar this way. It is also noteworthy that the `opts` key is available inside of states and configurations and can easily be used as source of minion defined data, and using opts allows us to separate concerns and models.

**Comment by alexbleotu** [comment]
@cachedout, @thatch45 ok I understand the concerns. 

What do you think of restricting the extra config data to be passed to external pillar calls only (an additional optional parameter when invoking external pillars)? This would be fully backwards compatible and would allow better control of the external pillar behaviour, without actually making the data available in the pillar?

**Comment by thatch45** [comment]
Ok, let me make sure I follow, this would be configuration data on the minion that gets passed to external pillars. Then it becomes up to the external pillar how to handle that data.
I think that would be an optimal solution, because it maintains the model of decisions being made in the ext pillar but allows the configuration to exist on the minion and allows for the changes to happen without modifying grains.
I think this would work well, what do you think @cachedout ?
btw, @cachedout is out for a few days so he might not get back right away

**Comment by alexbleotu** [comment]
thanks for the reply @thatch45. Yes that's exactly what I am proposing: the data in the config will not be included in the pillar directly, it will be passed to the external pillar functions as an additional parameter influencing the logic in the external pillars only. I am on vacation as well right now, so I will work on this probably next week anyway.

**Comment by thatch45** [comment]
Perfect, I will be out of town next week but you already have an endorsement from me on the path forward, I am glad we were able to figure this one out in a good way!

**Comment by cachedout** [comment]
Based on the above discussion, I am closing this for the time begin. When a different approach is ready to go, we can begin the discussion anew in another PR. Thanks, @alexbleotu

**Comment by alexbleotu** [comment]
Thanks @cachedout. I will submit a new PR shortly. It's going through internal review and everybody is on vacation.

**Pull request closed without merging**
