### PR TITLE
state smartos - fixes from dogfooding

### PR DESCRIPTION
**Pull request by sjorge**
So I've been eating my own dogfood for the last few days and fixed a few more things that popped up.

@cachedout also no docs showing up for this one:
https://docs.saltstack.com/en/develop/ref/states/all/salt.states.smartos.html#module-salt.states.smartos

I assume this is where it should show up.

### CODE REVIEW

**Comment by jfindlay** [comment]
@sjorge, regarding the documentation, you may want to ask @jacobhammons.

**Comment by jacobhammons** [comment]
@sjorge I just submitted https://github.com/saltstack/salt/pull/29026 to add the doc stub file and a few formatting updates for this module, that doc link will work tomorrow morning. Thanks!

**Comment by sjorge** [comment]
Jenkins errors look unrelated to my change. Or am I missing something?

**Comment by sjorge** [comment]
There is one more commit pending... waiting on feedback from someone

**Comment by sjorge** [comment]
alright that should be it (hopefully, unless someone else pokes me with problems)

**Comment by cachedout** [comment]
Looks good as always! Thanks, @sjorge

**Comment by sjorge** [comment]
@jacobhammons:still nothing showed up in the docs?

**Comment by jacobhammons** [comment]
@sjorge let me know if you still aren't seeing this page, thanks.

**Comment by sjorge** [comment]
Still not seeing it listed: https://docs.saltstack.com/en/develop/ref/states/all/index.html

Seems it is available here now though: https://docs.saltstack.com/en/develop/ref/states/all/salt.states.smartos.html, will check for errors in layout/text later this week.

**Comment by jacobhammons** [comment]
@sjorge I'm not seeing it there either, I'll investigate. Thanks.

**Pull request merged**
