### PR TITLE
Pygit2: re-read repo on config change.

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
### What does this PR do?
Fixes pygit2 tests error `index out of range`.
The error is produced because pygit2 doesn't re-read the remotes config in case we access remote by index. But our code changes git config directly adding remote to the config file after pygit2 repository object is already created.

### What issues does this PR fix or reference?
N/A

### Previous Behavior
1. Create a new git repo with pygit2 getting a new pygit2 repo handler: `self.repo = pygit2.init_repository(self.cachedir)`.
2. Update git config file not using the pygit2 handler adding the origin remote.
3. Access the remote using pygit2 handler: `origin = self.repo.remotes[0]`
At step 3 self.repo has no remotes because it doesn't look for changes in the repo filesystem.

### New Behavior
1. Create a new git repo with pygit2 getting a new pygit2 repo handler: `self.repo = pygit2.init_repository(self.cachedir)`.
2. Update git config file not using the pygit2 handler adding the origin remote.
2.1 If config file changed re-init pygit2 repository handler
3. Access the remote using pygit2 handler: `origin = self.repo.remotes[0]`
At step 3 self.repo has all remotes we're added on step 2.

### Tests written?
Current tests cover this case.

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by waynew** [comment]
Is there any way we could get some tests for this?

**Comment by DmitryKuzmenko** [comment]
@waynew as I wrote: the case is already covered by current tests. I found it by simple run of `sudo ./tests/runtests.py --run-destructive -n integration.pillar.test_git_pillar.TestPygit2SSH` in any my venv (py2, py3) and any or active branches.
@s0undt3ch @Ch3LL I'm not sure does our CI installs pygit2 for tests?

**Comment by Ch3LL** [comment]
yep: https://github.com/saltstack/salt-jenkins/blob/develop/git/salt.sls#L114

**Comment by waynew** [comment]
I know we run on several supported platforms, so https://github.com/saltstack/salt-jenkins/blob/fb8dc3163bfc196f6ee7ba603683e2ad167a2b06/python/pygit2.sls#L18 should at least be getting tested on one thing or another, but shouldn't the current test(s) be failing then? 😕

**Comment by DmitryKuzmenko** [comment]
@waynew @Ch3LL I've just opened the output of all the 6 tests jobs passed for this PR and tried to `Ctrl-F` for `integration.pillar`. No results in any.

**Comment by s0undt3ch** [comment]
Oh, someone pointed to the right pygit2

**Comment by s0undt3ch** [comment]
*pygit2 sls

**Comment by Ch3LL** [comment]
The PR tests have some logic added to them to only run certain tests based on which files are being edited. So i'm guessing that logic is not adding the `integration.pillar` tests based off of your change if your not seeing it run. You might need to run a full test run from your branch on jenkins.

**Comment by Ch3LL** [comment]
i believe this is the new switch that was added `--from-filenames=salt/utils/gitfs.py` that adds that logic if you want to look at the `from-filenames`arg to make sure those tests are run

**Comment by dwoz** [comment]
If tests are not running that should we can also update the [mapping](https://github.com/saltstack/salt/blob/develop/tests/filename_map.yml)

**Comment by waynew** [comment]
So to make sure I grok this right - the existing tests cover this case and they *would* have failed if they were running, but they aren't running since none of the last N PRs failed due to this error. And they're not running this test, because none of the PRs touched this code?

**Comment by DmitryKuzmenko** [comment]
You're right guys. The pygit2 pillar tests are passing in the branch tests.
I'll take another look at that tomorrow.
Thank you all.

**Comment by Ch3LL** [comment]
i'm seeing some failures here: https://jenkinsci.saltstack.com/job/2018.3/job/salt-centos-7-py2/146/#showFailuresLink

```
integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_includes_disabled
integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_includes_enabled
integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_includes_enabled_solves___env___with_mountpoint
integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_mountpoint_parameter
integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_multiple_sources_dev_master_merge_lists
integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_multiple_sources_dev_master_no_merge_lists
integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_multiple_sources_master_dev_merge_lists
integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_multiple_sources_master_dev_no_merge_lists
integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_multiple_sources_with_pillarenv
integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_root_and_mountpoint_parameters
integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_root_parameter
integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_single_source
```

**Comment by DmitryKuzmenko** [comment]
Looks not related. But thank you anyway.

**Comment by DmitryKuzmenko** [comment]
Nice. It was an environment issue. I have native  libgit2 ver 0.27 on my Arch. And pip installed pygit2 0.28 to my virtualenv. In that case it works in that way: remotes doesn't got updated in our case.
I've tested pairs of same versions for 0.24-0.27 all works good.
This is it. =(

**Pull request closed without merging**
