### PR TITLE
56449 fetch master pubkey

### PR DESCRIPTION
**Pull request by alexz71**
### What does this PR do?
Implements feature #56449 (API call to fetch master public key) in file wheel/key.py

### What issues does this PR fix or reference?
#56449

### Tests written?

Yes

### Commits signed with GPG?

No

### CODE REVIEW

**Review by DmitryKuzmenko — DISMISSED** [review]

**Comment by DmitryKuzmenko** [comment]
I'm good with this and formally it's merge ready. Anyway I want to see more reviews from @saltstack/team-core .

**Comment by DmitryKuzmenko** [comment]
@alexz71 could you please resolve merge conflicts?

**Comment by alexz71** [comment]
@DmitryKuzmenko conflicts resolved, files blackened

**Comment by DmitryKuzmenko** [comment]
Checked locally:
```
sort....................................................................Passed
black....................................................................Passed
```
I re-ran failed fedora31 build. Let's wait for result.

**Review by DmitryKuzmenko — APPROVED** [review]

**Comment by dwoz** [comment]
Windows 2016  passed on build 8
https://jenkinsci.saltstack.com/job/pr-windows2016-py3/job/PR-56550/8/

**Review by dwoz — APPROVED** [review]

**Pull request merged**
