### PR TITLE
Added logic to pull vault config from pillar data

### PR DESCRIPTION
**Pull request by justindesilets**
### What does this PR do?
This adds the ability to load vault config values from pillars. This includes being able to use GPG encrypted pillars to be able to store vault config values. I have been able to successfully test using encrypted vault policy tokens.

### What issues does this PR fix or reference?
With vault, each time a new policy is created, the vault token needs to be updated for all masters. In a large, multi-tenant vault deployment, this can mean updating the token multiple times per week or even day. This forces you to have to restart all of your salt masters to pick up the updated token values each time. Adding the option to keep the data in pillars allows you to update the value without the need to restart your salt-masters

### Tests written?

No. I have tried to test the functionality to the best of my ability in our current vault environment. I am unable to validate all vault functions as I am not the owner of our vault service and cannot reproduce all the use cases that the vault runner covers. I welcome help in trying to validate the changes I've made.

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by dwoz** [comment]
@justindesilets Have you looked at our existing fault tests here?

https://github.com/saltstack/salt/blob/develop/tests/integration/modules/test_vault.py

They spin up an instance of vault for the test locally. Does this help point you in the right direction to get this change covered by a test?

**Review by dwoz — COMMENTED** [review]
@justindesilets Have you looked at our existing fault tests here?

https://github.com/saltstack/salt/blob/develop/tests/integration/modules/test_vault.py

They spin up an instance of vault for the test locally. Does this help point you in the right direction to get this change covered by a test?

**Comment by justindesilets** [comment]
I've been able to get the module tests run for vault. Here was the result.
```
python tests/runtests.py -n integration.modules.test_vault --run-destructive
==  Overall Tests Report  ==
**  No Problems Found While Running Tests  **
OK (total=4, skipped=0, passed=4, failures=0, errors=0)
==  Overall Tests Report  ==
```

**Comment by justindesilets** [comment]
Right now, it looks like my update broke the unit.runners.test_vault test. I am looking into what needs to be updated in the test to get the running and the testing synced back together.

**Comment by justindesilets** [comment]
@dwoz I have been able to get all testing work, but in doing so, triggered a code climate check.
```
File test_vault.py has 257 lines of code (exceeds 250 allowed).

Found in tests/unit/runners/test_vault.py
```
Do you have any advice on how to resolved this?

**Comment by sagetherage** [comment]
Reviewed in Grooming 2021-APR-05. We have not follow up here to your questions, if you are willing to write tests this would also need to be rebased against the `master` branch.

**Comment by justindesilets** [comment]
@sagetherage , I had completely forgotten about this PR. I can try and make some time to merge the latest updates into my branch and see if even still works. From there I can try and see about getting past the error I was hitting last time. If it looks like too much will change to get it working, I'll close this PR and start a new one.

**Comment by sagetherage** [comment]
@justindesilets what is your timeframe, here?

Discussed in Grooming 2021-APR-19 I will give this 2 more weeks and let us know if you need help or if you simply want to close it. Thanks!

**Comment by justindesilets** [comment]
@sagetherage , closing this PR. I will revisit this feature request when I have some time to dig into it.

**Pull request closed without merging**
