### PR TITLE
fix multiprocessing mode on windows.

### PR DESCRIPTION
**Pull request by jizhilong**
Refs #30313

### CODE REVIEW

**Comment by cachedout** [comment]
I believe this is fine.

@s0undt3ch, @thatch45 or @jacksontj Do any of you have comments before I merge this?

**Comment by thatch45** [comment]
Yes, this should be fine, lets make sure @UtahDave  and @twangboy are aware and test this out

**Comment by jacksontj** [comment]
Seems good, if this is done in more than just here we might want to think about making a library method to do the re-inflate of the object.

**Comment by cachedout** [comment]
@jacksontj I can't think of another place offhand, but +1 on a library if it becomes a pattern.

**Pull request merged**
