### PR TITLE
Remove obsolete unicode handling in pkg.info_installed

### PR DESCRIPTION
**Pull request by dincamihai**
### What does this PR do?

Removes obsolete unicode encode/decode handling

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by dincamihai** [comment]
It seems that this might break something in zypper module. I have to investigate more.

**Comment by rallytime** [comment]
@dincamihai Since you're still working on this PR, can I move the base branch here to `oxygen` instead of `oxygen.rc1`? We're getting close to moving away from the codenamed branch to a versioned branch and I don't consider this PR a blocker for the RC.

**Comment by dincamihai** [comment]
@rallytime sorry for the late reply. i've changed the base and i have removed the WIP.
the change seem to be ok according to our tests.

**Comment by rallytime** [comment]
@dincamihai Ok, thanks. Let's see how this run goes. :)

**Review by terminalmage — APPROVED** [review]

**Review by rallytime — APPROVED** [review]

**Pull request merged**
