### PR TITLE
fix loading of libcrypto on various platforms

### PR DESCRIPTION
**Pull request by msteed**
I think this will fix the massive jenkins breakage : /

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Let's confirm :)

**Comment by cachedout** [comment]
Looks good!

**Comment by lorengordon** [comment]
Has this been tested on Windows? I was doing some testing and installed from develop earlier today (commit 9514964075d5f6e43d0d577af33d16db011deb65). Just trying to get a versions-report and I keep getting an error indicating that 'libeay32' is not available. 

C:\Users\Administrator> salt-call.exe --versions-report:
```
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\Programs\Python27\Scripts\salt-call-script.py", line 9, in <module>
    load_entry_point('salt==2015.5.0-1422-g9514964', 'console_scripts', 'salt-call')()
  File "c:\users\administrator\documents\git\salt\salt\scripts.py", line 218, in salt_call
    import salt.cli.call
  File "c:\users\administrator\documents\git\salt\salt\cli\call.py", line 6, in <module>
    from salt.utils import parsers
  File "c:\users\administrator\documents\git\salt\salt\utils\parsers.py", line 26, in <module>
    import salt.config as config
  File "c:\users\administrator\documents\git\salt\salt\config.py", line 39, in <module>
    import salt.utils.sdb
  File "c:\users\administrator\documents\git\salt\salt\utils\sdb.py", line 9, in <module>
    import salt.loader
  File "c:\users\administrator\documents\git\salt\salt\loader.py", line 27, in <module>
    import salt.utils.event
  File "c:\users\administrator\documents\git\salt\salt\utils\event.py", line 80, in <module>
    import salt.payload
  File "c:\users\administrator\documents\git\salt\salt\payload.py", line 17, in <module>
    import salt.crypt
  File "c:\users\administrator\documents\git\salt\salt\crypt.py", line 37, in <module>
    import salt.utils.rsax931
  File "c:\users\administrator\documents\git\salt\salt\utils\rsax931.py", line 54, in <module>
    libcrypto = _init_libcrypto()
  File "c:\users\administrator\documents\git\salt\salt\utils\rsax931.py", line 32, in _init_libcrypto
    libcrypto = _load_libcrypto()
  File "c:\users\administrator\documents\git\salt\salt\utils\rsax931.py", line 20, in _load_libcrypto
    return cdll.LoadLibrary('libeay32')
  File "C:\Users\Administrator\Documents\Programs\Python27\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Administrator\Documents\Programs\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
```

That dll typically comes from OpenSSL packages and doesn't appear to be distributed with salt. I pulled the dll from OpenSSL, dropped it in C:\Windows\System32, and got a new error...

C:\Users\Administrator> salt-call.exe --versions-report:
```
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\Programs\Python27\Scripts\salt-call-script.py", line 9, in <module>
    load_entry_point('salt==2015.5.0-1422-g9514964', 'console_scripts', 'salt-call')()
  File "c:\users\administrator\documents\git\salt\salt\scripts.py", line 218, in salt_call
    import salt.cli.call
  File "c:\users\administrator\documents\git\salt\salt\cli\call.py", line 6, in <module>
    from salt.utils import parsers
  File "c:\users\administrator\documents\git\salt\salt\utils\parsers.py", line 26, in <module>
    import salt.config as config
  File "c:\users\administrator\documents\git\salt\salt\config.py", line 39, in <module>
    import salt.utils.sdb
  File "c:\users\administrator\documents\git\salt\salt\utils\sdb.py", line 9, in <module>
    import salt.loader
  File "c:\users\administrator\documents\git\salt\salt\loader.py", line 27, in <module>
    import salt.utils.event
  File "c:\users\administrator\documents\git\salt\salt\utils\event.py", line 80, in <module>
    import salt.payload
  File "c:\users\administrator\documents\git\salt\salt\payload.py", line 17, in <module>
    import salt.crypt
  File "c:\users\administrator\documents\git\salt\salt\crypt.py", line 37, in <module>
    import salt.utils.rsax931
  File "c:\users\administrator\documents\git\salt\salt\utils\rsax931.py", line 54, in <module>
    libcrypto = _init_libcrypto()
  File "c:\users\administrator\documents\git\salt\salt\utils\rsax931.py", line 32, in _init_libcrypto
    libcrypto = _load_libcrypto()
  File "c:\users\administrator\documents\git\salt\salt\utils\rsax931.py", line 20, in _load_libcrypto
    return cdll.LoadLibrary('libeay32')
  File "C:\Users\Administrator\Documents\Programs\Python27\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Administrator\Documents\Programs\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 193] %1 is not a valid Win32 application
```

Any idea how to get this to work?

**Comment by msteed** [comment]
@lorengordon - this has been tested on Windows. Pinging @twangboy - can you help with the details?

**Comment by twangboy** [comment]
I copied libeay.dll to C:\Python27. I got it from the M2Crypto egg before I uninstalled it... I'm going to do a fresh set up now to see what exactly has to be done to run develop...

**Comment by lorengordon** [comment]
Ok, cool. Seems part of my problem was that the version of the dll I had doesn't work quite this way. I just grabbed the dll from M2Crypto, dropped it into the path, and am in business. Thanks! (Not to be greedy, but it would be great to get this step into the salt-windows-dev build. :wink: )

**Comment by twangboy** [comment]
These are the steps that worked for me:
Run dev_env.ps1 to set up the environment
Copy ```libeay.dll``` from ```C:\Python27\Lib\site-packages\M2Crypto-0.21.1-py2.7-win-amd64.egg\M2Crypto``` to ```C:\Python27\```
pip uninstall m2crypto
pip install tornado
Pull down the latest salt from the develop branch
go into the salt clone and pip install salt ```pip install -e .```
start the salt-minion

**Comment by twangboy** [comment]
These are the steps that worked for me:
Run dev_env.ps1 to set up the environment (from https://github.com/saltstack/salt-windows-dev)
Copy libeay.dll from C:\Python27\Lib\site-packages\M2Crypto-0.21.1-py2.7-win-amd64.egg\M2Crypto to C:\Python27\
pip uninstall m2crypto
pip install tornado
Pull down the latest salt from the develop branch
go into the salt clone and pip install salt pip install -e .
start the salt-minion

**Comment by twangboy** [comment]
Sorry, didn't see your reply above. I'm gonna setup salt-windows-dev to branch like the salt versions. So, to build the 2015.5 branch of salt, you'd use the 2015.5 branch of salt-windows-dev.

**Comment by lorengordon** [comment]
It's working for me right now to use `pip uninstall salt`, checkout the branch/tag I want to test, then use the `pip install -e` method. I just couldn't get the 'develop' branch to work because I didn't have the dll. Also, 'tornado' is in the requirements file for the develop branch, so it installs automatically... Nice work on salt-windows-dev, btw, that makes it super easy to work from source on Windows!

**Pull request merged**
