### PR TITLE
Merge changes for pull#26083 and pull#25632 into 2015.8

### PR DESCRIPTION
**Pull request by TheScriptSage**

### CODE REVIEW

**Comment by whiteinge** [comment]
Looks good! Thanks for doing the work. Waiting to see what Jenkins has to say about it, then we'll get this in.

**Comment by TheScriptSage** [comment]
You rock!  Thanks.  Sorry for the delay for getting this request up, but if this happens tonight I would be ecstatic. :)

Seeing as this passed against develop I'm gonna hope it passes here, so I'll wait to see what Jenkins has to say.

**Comment by TheScriptSage** [comment]
Wow I think that's the first time I've gotten greens on the first go.

**Comment by TheScriptSage** [comment]
@whiteinge I know it's late so I'll only ping once, but it looks good. :D  

Thanks if you get to this tonight, if not I'll check back with you tomorrow morning.  You guys are awesome. \ o /

**Comment by whiteinge** [comment]
Woot.

**Pull request merged**
