### PR TITLE
Catch Attribute Error when docker.version_info doesn't exist

### LINKED ISSUE #32261: dockerng : AttributeError: 'module' object has no attribute 'version_info'
### Description of Issue/Question
```
2016-03-31 08:45:04,976 [salt.loader      ][ERROR   ][9448] Exception raised when processing __virtual__ function for dockerng. Module will not be loaded 'module' object has no attribute 'version_info'
2016-03-31 08:45:04,980 [salt.loader      ][WARNING ][9448] salt.loaded.int.module.dockerng.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'dockerng', please fix this.
```
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
# salt-minion --versions-report
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
           Mako: 1.0.0
         PyYAML: 3.11
          PyZMQ: 14.4.0
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
           cffi: 0.8.6
       cherrypy: 2.3.0
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
 
System Versions:
           dist: debian 8.3 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: debian 8.3 
# dpkg -l python-docker

ii  python-docker                     0.5.3-1               all                   Python wrapper to access docker.io's control socket

```

### PR DESCRIPTION
**Pull request by arthurzenika**
### What issues does this PR fix or reference?
#32261
### Previous Behavior

bunch of errors in the log
### New Behavior

catch old versions of docker-python
### Tests written?

No

fixes #32261

### CODE REVIEW

**Comment by ticosax** [comment]
`dockerng` requires docker-py >= 1.4

:-1: on this pull request.

**Comment by arthurlogilab** [comment]
@ticosax sure, but what about minions installed on a machine that doesn't have docker-py >= 1.4 (and don't need it). Should they spew out a log every 5 minutes about it ?

**Comment by ticosax** [comment]
@arthurlogilab I see your point now. I didn't realized it was blowing up even when you are not interested into using `dockerng`.
I will submit another pull request with a more explicit error message.
Thanks for the report

**Comment by cachedout** [comment]
@arthurlogilab I'm going to go ahead and close this in favor of #32268. Let me know if you don't agree and we'll re-visit it. Thanks!

**Pull request closed without merging**
