### PR TITLE
runner: Force mminion loading not to clutter output

### PR DESCRIPTION
**Pull request by kiorky**

### CODE REVIEW

**Comment by kiorky** [comment]
cc @jacksontj

**Comment by jacksontj** [comment]
This still "clutters" the output, it just moves it up before the return. IMO if you are running debug or above (which is the only thing where mminion logs) then you more or less expect a lot of output.

**Comment by kiorky** [comment]
Expecting more output doesnt mean that we should or cloud notnot try to make the user life easier :).
mminion will be called sooner or later anyway, when we are on that portion of the code, so let just make its output go where it should be and not clutter the rest of the execution display...

**Comment by kiorky** [comment]
In the actual state, without my patch, the result coming to the console is just drowned way back in the trace, because of the module loading debug, which is totally useless on that part, except for making life of the reader harder & tedious.

**Comment by thatch45** [comment]
So far as I can tell this is a safe check that the mminion is loaded, so I will merge it in

**Comment by kiorky** [comment]
@thatch45
the real problem here is that if we have a high debug level,
and if lazyload only at the end of the runner return, (like the code without my patch).
the modules loading debug floods the console and the result is then lost in the flaw of unuseful information.

Thus, by forcing the load just before executing the runner funtion, (as anyway when we are here, we will load that mminion sooner or later), the debug output will arrise before the runner return outputting, and so the user will have a change to read it more easily on the console.

**Comment by kiorky** [comment]
anyways, that's merged :), so no problem anymore ^^

**Pull request merged**
