### PR TITLE
lxc.set_dns: handle also resolvconf based installs

### PR DESCRIPTION
**Pull request by kiorky**
cc @terminalmage

### CODE REVIEW

**Comment by kiorky** [comment]
jenkins got a boohbooh ?

**Comment by kiorky** [comment]
go go jenkins ?

**Comment by kiorky** [comment]
unrelated failure

**Comment by kiorky** [comment]
go go jenkins ?

**Comment by kiorky** [comment]
unrelated failure

**Comment by cachedout** [comment]
Reviewed by @terminalmage. Merged.

**Pull request merged**
