### PR TITLE
Add support for architectures for APT pkgrepo.managed states

### LINKED ISSUE #49619: Add an execution module to test load_yaml/load_json
This would be a function that would import the same code used by our Jinja renderer to handle load_yaml/load_json, to be used as a sanity check so one can see what data that map file contains. This would be very helpful to troubleshoot instances in which the data that is loaded doesn't match what the user expects, resulting in SLS errors.

Additionally, it would be useful to also have an option to use grains.filter_by to see what a given platform would load out of that map file.

### LINKED ISSUE #49894: pkgrepo not correctly recognize architecture for apt in test=true
### Description of Issue/Question

pkgrepo.managed is not correctly recognizing the architecture for apt based systems when running with test=true. with below scenario test=true always return a change even the repository is correctly setup.

it does not work with the following variations:
* having `[arch=amd64]` in the name attribute of the pkgrepo.managed state
* having `architecture: amd64` as attribute of the pkgrepo.managed state

### Setup
sls
```
salt_minion_repo:
  pkgrepo.managed:
    - name: deb [arch=amd64] http://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest bionic main
    - file: /etc/apt/sources.list.d/saltstack.list
    - key_url: salt://{{ slspath }}/files/SALTSTACK-GPG-KEY.pub
```

### Steps to Reproduce Issue
1. create file `/etc/apt/sources.list.d/saltstack.list` on salt minion containing the repository with `[arch=amd64]`
2. run highstate against the minion with `test=true` => should show a change (NOT OK)
3. run highstate against the minion with `test=false` => not showing a change (OK)

### Versions Report
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-36-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

### PR DESCRIPTION
**Pull request by terminalmage**
Fixes #49894.

### CODE REVIEW

**Comment by do3meli** [comment]
@terminalmage what is the status of this PR?

**Comment by terminalmage** [comment]
@do3meli It is failing the test I wrote for it, which is why it hasn't been merged yet. I'll take a look at it on Thursday.

**Comment by terminalmage** [comment]
Ahh OK, I see the problem. I'm creating a tempfile using a decorator, which fails on non-APT systems. Will be an easy fix, I'll get that done after lunch.

**Comment by terminalmage** [comment]
OK, tests should pass now, should be good to merge once done.

**Review by thatch45 — APPROVED** [review]

**Comment by do3meli** [comment]
Cool thanks @thatch45 and @terminalmage

Willthes be merged into master as well?

**Comment by thatch45** [comment]
Yes, this will be merged forward into 2019.2 and into develop

**Comment by terminalmage** [comment]
@do3meli Yeah, see here for how we manage bugfixes: https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch

**Pull request merged**
