### PR TITLE
Add --state-verbose command line option to salt cmd

### PR DESCRIPTION
**Pull request by ctrlrsf**
This overrides the state_verbose setting that may be set in master config. 

Closes issue https://github.com/saltstack/salt/issues/13640

If master has state_verbose set to True

--state-verbose=False would suppress states that didn't change.

If master config has state_verbose set to False

--state-verbose=True would still show states that didn't have changes.

Below is test output with state_verbose=True in ./etc/salt/master:

```
$ salt -c ./etc/salt '*' --state-verbose=True  state.highstate
salt-dev:
----------
          ID: test_file.txt
    Function: file.managed
        Name: /tmp/test_file.txt
      Result: True
     Comment: File /tmp/test_file.txt exists with proper permissions. No changes made.
     Started: 13:51:15.798599
    Duration: 7.176 ms
     Changes:

Summary for salt-dev
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   7.176 ms

$ salt -c ./etc/salt '*' --state-verbose=False  state.highstate
salt-dev:

Summary for salt-dev
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   8.589 ms
```

### CODE REVIEW

**Comment by cachedout** [comment]
Great! Thank you!

**Comment by yermulnik** [comment]
```shell
(jail) [root#jail_salt][w:9][j:0][.../salt/states]> salt --version
salt 2015.8.0 (Beryllium)
(jail) [root#jail_salt][w:9][j:0][.../salt/states]> salt jail_salt --state-verbose=False state.highstate test=true
Usage: salt [options] '<target>' <function> [arguments]

salt: error: no such option: --state-verbose
```

**Comment by ctrlrsf** [comment]
@yermulnik This was merged into develop branch. Were you running 2015.08 branch? Notice --version difference below.

```
$ salt --version
salt 2015.8.0-412-gd4533d0 (Beryllium)
```

```
salt --help
...snip...
    --state-verbose=STATE_VERBOSE, --state_verbose=STATE_VERBOSE
                        Override the configured state_verbose value for minion
                        output. Set to True or FalseDefault: True
```

```
$ salt --state-verbose
Usage: salt [options] '<target>' <function> [arguments]

salt: error: --state-verbose option requires an argument
```

**Comment by yermulnik** [comment]
> This was merged into develop branch. Were you running 2015.08 branch?

@ctrlrsf guess it's not a dev branch on my side, is it?
```
(jail) [root#jail_salt][w:9][j:0][.../salt/states]> salt --versions-report
Salt Version:
           Salt: 2015.8.0

[...]

System Versions:
           dist:
        machine: amd64
        release: 10.1-RELEASE-p19
```
It's FreeBSD.

ps: I thought this option was merged into 2015.8.0. excuses for the noise =)

**Comment by Grokzen** [comment]
@ctrlrsf  In what release is this in? 8.0 or 8.1? Any backport to 5.x?

**Pull request merged**
