### PR TITLE
tutorial about moving logic from maps.jinja to an execution module

### PR DESCRIPTION
**Pull request by ahammond**
### What does this PR do?

Adds a tutorial that demonstrates moving logic from a maps.jinja file to an execution module
### What issues does this PR fix or reference?

I had a conversation with @thatch45 at SaltConf 2016:

Me: I don't like Jinja because maps.jinja gets too clever and then it's a huge problem accessing that logic from other renders

Tom: You should move that logic to an execution module.

Me: How do I do that?

Tom: It's really easy, I guess I should write a quick tutorial.

Me: I can probably do that.

…dule

### CODE REVIEW

**Comment by rallytime** [comment]
@ahammond Great! This will be a very useful tutorial to have. 

My only question/feedback here is I am wondering if `Execution Modules` is the right name for this tutorial. While the meat of the doc revolves around moving your maps.jinja code to an execution module, the title seems to suggest that is about the broader topic of execution modules within Salt. Which to me could include "using execution modules", "writing execution modules", "how execution modules fit within the salt ecosystem" or any of those things. Maybe the title of the tutorial should be a little more specific? What do you think?

**Comment by rallytime** [comment]
I also would like to backport this tutorial to 2015.8, so it can be included in the current doc landing page and future releases off of the 2015.8 branch as this is very useful information. I will grab the backport (and update the versionadded tag) once this is merged into develop. 

Thanks again!

**Comment by ahammond** [comment]
@rallytime I agree, it should have a more specific title. How about "My First Execution Module" or something like that?

**Comment by rallytime** [comment]
I think the title could be even more descriptive. Maybe something like `How to Convert Jinja Logic to an Execution Module`?

**Comment by ahammond** [comment]
I like that. Implemented. :)

**Comment by rallytime** [comment]
Nice! Thank you!

**Comment by jacobhammons** [comment]
@ahammond Just came across this, great addition! I've added a link to it from the Understanding Jinja topic.

**Pull request merged**
