### PR TITLE
renderers/py: support pipelining e.g. with jinja

### LINKED ISSUE #18487: Py renderer does not support chaining
Per discussion with @basepi on the salt google group, the py renderer ignores input from any upstream renderer. Here is an example:

```
webserver2.sls

#!jinja|py
{% include "someinclude.sls" %}

def run():
    config = {}
    return config
```

```
someinclude.sls

def test1():
    pass
```

running:
`#salt-call --local state.sls webserver2 test=True`

gives following output/error:

```
[DEBUG   ] Rendered data from file: /srv/salt/webserver2.sls:
#!jinja|py
def test1():
    pass

def run():
    config = {}
    return config

[CRITICAL] Rendering SLS webserver2 failed, render error: invalid syntax (webserver2.sls, line 2)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 2350, in render_state
    sls, rendered_sls=mods
  File "/usr/lib/python2.7/dist-packages/salt/template.py", line 84, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/renderers/py.py", line 108, in render
    **kws)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 369, in py
    sfn
  File "/srv/salt/webserver2.sls", line 2
    {% include "someinclude.sls" %}
     ^
SyntaxError: invalid syntax
[DEBUG   ] LazyLoaded .returner

```

First this template is processed by the jinja renderer and then the output is passed to the py renderer. However the py renderer ignores the input content, instead it uses the template path as its input and then process it.

If you the check source code of the py renderer you can see that the variable _'template'_ is immediately overwritten with a path to the template file being rendered. Normally this variable contains content produced by a previous renderer (if any):

https://github.com/saltstack/salt/blob/develop/salt/renderers/py.py

```
def render(template, saltenv='base', sls='', tmplpath=None, **kws):

template = tmplpath
```

The reason for that may be in salt.utils.templates.py.py()

https://github.com/saltstack/salt/blob/develop/salt/utils/templates.py

```
def py(sfn, string=False, **kwargs):
....
mod = imp.load_source(os.path.basename(sfn).split('.')[0], sfn)
```

where 'imp' is a python builtin.

According to the official documentation, `imp.load_source()` requires _"a real file object"_:

https://docs.python.org/2/library/imp.html
_"...It must currently be a real file object, not a user-defined class emulating a file"_

Possible solution would require either replacing imp.load_source with something that would accepts content instead of a file system path. Another possible solution would be to save content to a temporary file first. Both solution would need to take into account relative imports (although I do not think that is supported at the moment anyway).

If this going to be marked as _won't fix_ then possibly py renderer should throw an exception if py renderer receives any input.

### LINKED ISSUE #45521: Import jinja template in py renderer
### Description of question
Typically using salt, we define `map.jinja` file that defines some defaults (e.g. per OS basis)  
Such file can easily be used in `*.sls` files like so:

```
{% from "some/state/map.jinja" import state_data with context %}
some_state:
  x.y:
    - name: {{ state_data.something_fancy }}
```

How to achieve the same using `py` renderer?

```
#!py


def run():
  # how to import some/state/map.jinja ???
```

### PR DESCRIPTION
**Pull request by TheJJ**
### What does this PR do?

This adds support for piping other renderers into the py renderer:

```
#!jinja|py
```

### What issues does this PR fix or reference?

fixes #45521
fixes #18487

### Previous Behavior
One could not pipe a previous renderer into the `py` renderer

### New Behavior
Finally, code can be piped into the `py` renderer.

### Tests written?
**[NOTICE] Bug fixes or features added to Salt require tests.**
Please review the [test documentation](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html) for details on how to implement tests into Salt's test suite.

No not yet, please give feedback first.

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by dwoz** [comment]
@TheJJ Thanks for the contribution. We need some tests to cover this change and it looks like the linter is failing.

**Comment by mchugh19** [comment]
looks like tests have been added, but there's still a couple of lint errors. These will likely get cleaned up by the black merge for sodium

**Comment by TheJJ** [comment]
I couldn't get the whole test setup to run, so I rely on the CI runs, which takes some time, and then I forget about it. I'll try to fix the issues soon™.

**Comment by TheJJ** [comment]
Thank you, salt, for the marvellous change from `'` to `"`, so that all patches are now broken. I really hope this was worth it.........

**Comment by DmitryKuzmenko** [comment]
@TheJJ I'm very sorry about it. It was a real need. It's pretty simple to automatically update your PR running the pre-commit script on your code to re-format it with isort and black we're using now.
```
pip install pre-commit
pre-commit install
FILES="$(git show --pretty="" --name-only master..HEAD)"
pre-commit run isort $FILES
pre-commit run black $FILES
```
next time you'll commit it will be ran automatically.

**Comment by twangboy** [comment]
@TheJJ looks like some of the tests are failing.

**Comment by TheJJ** [comment]
I'd be glad if someone more familiar with the salt codebase could support me in writing a proper test, since that seems to be the only thing holding this back. Thanks.

**Comment by twangboy** [comment]
@TheJJ Would you mind looking into these test failures?

**Comment by twangboy** [comment]
@TheJJ Got some lint failures

**Comment by DmitryKuzmenko** [comment]
@TheJJ it looks failures are relative. Could you please follow up?

**Comment by TheJJ** [comment]
Oh, sorry, I forgot about this. And I won't have time the next few weeks.
What do you mean by "relative" failures?

**Comment by waynew** [comment]
@TheJJ - related, probably - https://jenkinsci.saltstack.com/job/pr-centos7-py3-m2crypto/job/PR-55390/24/testReport/junit/unit.renderers.test_py/PyRendererTestCase/test_py_render_string/

**Comment by DmitryKuzmenko** [comment]
@TheJJ yes, related. Sorry for mistype.

**Comment by twangboy** [comment]
@TheJJ  The test failures are related to the changes in this PR.

**Comment by sagetherage** [comment]
@TheJJ we will have to remove this from the Magnesium release, but keeping it open to be worked for future releases.

**Review by waynew — CHANGES_REQUESTED** [review]
@TheJJ do you have plans to come back and pick this up and finish the tests? If life is busy for you (as one does), no problem! W e can add the Help Wanted label to indicate that we need someone to adopt this and get it over the finish line. Just let us know! (If I don't hear back in a week or two, I'll assume that we should go ahead and add that label!)

**Comment by TheJJ** [comment]
Since we're migrating to ansible, I won't put any more work into saltstack. It would be nice if anyone else could carry this feature over the finish line though.

**Comment by twangboy** [comment]
Tests need to be migrated to pytest and a changelog needs to be added.

**Pull request closed without merging**
