### PR TITLE
Partial revert 20799

### PR DESCRIPTION
**Pull request by ticosax**
This PR reverts 8d201fb7c095123b327d63ff0d39a5c95195c9ae.
And explain in documentation how to solve this use case, as per #20799 conversation.

### CODE REVIEW

**Comment by jfindlay** [comment]
@ticosax, thanks for the pull request.  There is a [lint error](https://jenkins.saltstack.com/job/salt-pr-lint-n/3069/violations/file/salt/states/dockerio.py/).

**Comment by ticosax** [comment]
@jfindlay I wasn't sure it was a false positive or not.
thank you, I will fix it.

**Comment by jfindlay** [comment]
@ticosax, nice, thanks.

**Comment by ticosax** [comment]
@jfindlay seems good to go now.

**Pull request merged**
