### PR TITLE
Reactor: fix traceback when salt:// path is nonexistant

### PR DESCRIPTION
**Pull request by terminalmage**
The get_file() function is what is run when a minion requests a file
using cp.cache_file. The expected return data from cp.cache_file is a
string, not a bool. This is likely the root cause of #36121.

### CODE REVIEW

**Review by cachedout — APPROVED** [review]

**Comment by cachedout** [comment]
There are two tests here that look like they were written to expect a bool.

**Comment by terminalmage** [comment]
@cachedout I'll take a look at them. If it is indeed the case that a ``False`` result is needed in those instances, we will need to modify ``cp.cache_file`` such that it returns an empty string when the result is ``False``. But it might also be a case of writing the test to fit the behavior. I'll figure out which is the case.

**Comment by cachedout** [comment]
@terminalmage Many thanks as always.

**Comment by terminalmage** [comment]
@cachedout I looked back and it seems like ``cp.cache_file`` was modified for 2015.5.0 to return ``False`` instead of an empty string. So, I'm not convinced that this is the best change. I talked to Tom and he agreed, so I removed that commit and instead modified the reactor.

**Review by cachedout — APPROVED** [review]

**Pull request merged**
