### PR TITLE
fix multimaster tests failing

### PR DESCRIPTION
**Pull request by MKLeb**
### What does this PR do?
Fixes multimaster tests failing on windows and debian.  Timeout was too short for test cmds

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by MKLeb** [comment]
re-run full all

**Comment by MKLeb** [comment]
re-run full all

**Comment by MKLeb** [comment]
re-run full all

**Comment by MKLeb** [comment]
re-run full all

**Comment by MKLeb** [comment]
re-run full all

**Comment by MKLeb** [comment]
re-run full all

**Comment by MKLeb** [comment]
re-run full all

**Comment by MKLeb** [comment]
re-run full all

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
