### PR TITLE
[master] Porting #51142 to master

### PR DESCRIPTION
**Pull request by garethgreenaway**
Porting #51142 to master

### CODE REVIEW

**Review by DmitryKuzmenko — APPROVED** [review]

**Review by DmitryKuzmenko — DISMISSED** [review]

**Comment by DmitryKuzmenko** [comment]
re-run full macosxmojave-py2

**Comment by DmitryKuzmenko** [comment]
re-run full macosxmojave-py2
re-run full windows2019-py3
re-run full centos7-py2-m2crypto
re-run full amazon2-py2

**Comment by dwoz** [comment]
Black needs to be run on this.

**Comment by waynew** [comment]
Just added some tests for this, also rebased on the latest master 👍

**Comment by dwoz** [comment]
Closing this due to inactivity.  Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
