### PR TITLE
fix 46902: wait dpkg lock

### PR DESCRIPTION
**Pull request by aarnaud**
### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/46902

### Previous Behavior
All pkg related states failed when dpkg lock cause by unattended-upgrade for example

### New Behavior
aptpkg wait for dpkg lock before continue, it will continue anyway if lock still present after 5min.

### Tests written?

No

### Commits signed with GPG?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by aarnaud** [comment]
Thanks to @johanfleury, i updated my PR to use a better way to check the dpkg lock

**Review by rares-pop — CHANGES_REQUESTED** [review]
The logic is flawed again. You fixed it in the previous PR, but for some reason you went back.

Again, you have a race-condition - your _wait_dpkg_lock() can say it's not locked, but when you actually do the __salt__['cmd.runall'](cmd, **params) be locked.

**Comment by johanfleury** [comment]
@rares-pop the way this repository is managed forces us to create multiple PRs to be sure our changes are pushed to every existing releases (this is honestly the worst way of doing release management I've seen, and [I'm not the only one](https://github.com/saltstack/salt/issues/34096)).

**Comment by johanfleury** [comment]
The way Salt releases are managed in this repository forces us to create multiple PRs if we want to see our changes published. This is honestly the worst way of doing release management I've seen (multiple release branches, new releases not sync'ed with develop, etc.) and [others share that feeling too](https://github.com/saltstack/salt/issues/34096).

I think @aarnaud only forgot to update this PR. The “correct” one (the one where discussions took place) is #52378.

**Comment by rares-pop** [comment]
> The way Salt releases are managed in this repository forces us to create multiple PRs if we want to see our changes published. This is honestly the worst way of doing release management I've seen (multiple release branches, new releases not sync'ed with develop, etc.) and [others share that feeling too](https://github.com/saltstack/salt/issues/34096).

I think you got it wrong. Creating multiple PRs won't help you much. There is actually a policy for salt changes, which is - bug fixes should go *only* in the oldest supported release that manifest the bug (and from there on it's saltstack's responsibility to forward-port it everywhere). Features should *only* go in 'develop', and it will make it in the next release (not the one that has feature-frozen due to immediate release).

> I think @aarnaud only forgot to update this PR. The “correct” one (the one where discussions took place) is #52378.

Again, you should decide if it's a fix, or a feature, and create just one PR in the right place.

Once you mentioned this, I saw it's an older PR. Apologize.

**Comment by aarnaud** [comment]
It's a bugfix for me. I close this PR and we keep #52378.

**Pull request closed without merging**
