### PR TITLE
Typo in options fields '_minion_conf_file' and '_master_conf_file' fixed

### PR DESCRIPTION
**Pull request by gongled**

### CODE REVIEW

**Comment by cachedout** [comment]
@gongled Some tests are failing here. I think it may be possible that some code is dependent on the old (bad) variable names. Could you investigate?

**Comment by cachedout** [comment]
@gongled Did you see my comment above regarding the failing tests?

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
@gongled why do you feel that this is a typo? Changing this around will break the syndic config load.

**Comment by cachedout** [comment]
@gongled I'm going to close this since I don't think we believe this is the right fix. If you have additional comments, you'll still be able to leave them here and we can definietely continue the discussion if there's a problem that needs to be addressed. Thanks.

**Pull request closed without merging**
