### PR TITLE
Extend Jinja options support (line statements)

### PR DESCRIPTION
**Pull request by epcim**
### What does this PR do?

Extends config options for Jinja environment defaults

### What issues does this PR fix or reference?

Addresses feature: https://github.com/saltstack/salt/issues/41043

### Tests written?

Yes

NOTE: Let me know if rebase or redesign is needed. This bit leaked over "just a few lines of code".

### CODE REVIEW

**Comment by epcim** [comment]
```OSError: [Errno 2] No such file or directory: '/tmp/salt-tests-tmpdir/prod-cheese-file'```
doesn't seem as introduced error.

**Comment by cachedout** [comment]
@epcim This is very interesting!

Could you please resolve these lint errors? After that, we'll have a few people review this. Thanks!

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/11065/violations/file/salt/utils/templates.py/

**Comment by cachedout** [comment]
@epcim It looks like a test may have failed here: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/11134/testReport/junit/integration.modules.test_state/StateModuleTest/test_get_file_from_env_in_top_match/

**Comment by epcim** [comment]
[**@cachedout**](https://github.com/cachedout) commented on [May 12, 2017, 7:11 PM GMT+2](https://github.com/saltstack/salt/pull/41166#issuecomment-301133520 "2017-05-12T17:11:09Z - Replied by Github Reply Comments"):
> [@epcim](https://github.com/epcim) It looks like a test may have failed here: [https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/11134/testReport/junit/integration.modules.test_state/StateModuleTest/test_get_file_from_env_in_top_match/](https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/11134/testReport/junit/integration.modules.test_state/StateModuleTest/test_get_file_from_env_in_top_match/)

I dont think so. State failed to create a file or it was not run. It's error in different context.
```
 def test_get_file_from_env_in_top_match(self):
     tgt = os.path.join(TMP, 'prod-cheese-file')
     try:
         ret = self.run_function(
             'state.highstate', minion_tgt='sub_minion'
         )
         self.assertSaltTrueReturn(ret)
         self.assertTrue(os.path.isfile(tgt))
         with salt.utils.fopen(tgt, 'r') as cheese:
             data = cheese.read()                                
             self.assertIn('Gromit', data)
             self.assertIn('Comte', data)
     finally:
         os.unlink(tgt)
```

```
➜  salt git:(pr/jinja_line_statements) ✗ cat ./tests/integration/files/file/prod/cheese
I could just fancy some cheese, Gromit. What do you say? Cheddar? Comte?
➜  salt git:(pr/jinja_line_statements) ✗ cat ./tests/integration/files/file/base/cheese
I could just fancy some cheese, Gromit. What do you say? Cheddar?
➜  salt git:(pr/jinja_line_statements) ✗ cat tests/integration/files/file/prod/issue-8196.sls:
zsh: correct 'tests/integration/files/file/prod/issue-8196.sls:' to 'tests/integration/files/file/prod/issue-8196.sls' [nyae]? y
{{ salt['runtests_helpers.get_salt_temp_dir_for_path']('prod-cheese-file') }}:
  file.managed:
    - source: salt://cheese
```

**Comment by epcim** [comment]
Go Go Jenkins!

@cachedout what will be next step - should I rebase? I dont see any conjunction between my code and the failed test. Anybody who may comment?

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@epcim After this test runs I will take a look and update you.

**Comment by cachedout** [comment]
@epcim Could you please go ahead and rebase this against the head of develop? Thanks.

**Comment by epcim** [comment]
okOn 22 May 2017 18:54, Mike Place <notifications@github.com> wrote:@epcim Could you please go ahead and rebase this against the head of develop? Thanks.

**Pull request closed without merging**
