### PR TITLE
requisite_any: dont fall in an infinite loop when req doesnt exist

### PR DESCRIPTION
**Pull request by mattp-**
### What does this PR do?
the missing req logic wasn't picking up the _any variants causing an
infinite loop. this fixes that.

### What issues does this PR fix or reference?
not sure if any outstanding issues, but if you try to run a state with onchange_any: something_nonexistant the state engine will recursively loop and stacktrace.

### Tests written?
Yes

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by mattp-** [comment]
put this on hold for the moment - need to review what test failures this change has accrued

**Comment by cachedout** [comment]
@mattp- Will do. You know what to do when this is ready to go. ;)

**Comment by KChandrashekhar** [comment]
> put this on hold for the moment - need to review what test failures this change has accrued

Matt, did you get a chance to look into the failing test cases ?

**Comment by mattp-** [comment]
Kavya, no I have not had time.

**Review by dwoz — APPROVED** [review]

**Comment by mattp-** [comment]
please do not merge this / consider on hold 🙂 haven't had time to work on whatever is going on with tests. I can close if easier

**Comment by dwoz** [comment]
@mattp- Are you able to rebase this to the `master` branch?

**Comment by dwoz** [comment]
@mattp- I've opened #55777 against master to see if the tests still fail

**Comment by sagetherage** [comment]
closing this in favor of #55777

**Pull request closed without merging**
