### PR TITLE
fix broken develop on smartos + fixes for salt.states.smartos

### PR DESCRIPTION
**Pull request by sjorge**

### CODE REVIEW

**Comment by s0undt3ch** [comment]
This needs to be backported to 2016.3

**Comment by s0undt3ch** [comment]
At least the syspaths fix.

**Comment by sjorge** [comment]
Probably the other commit also, if we want stable SmartOS support in 2016.3.

**Comment by rallytime** [comment]
@sjorge The latter, if you don't mind. Bug fixes should go into the "oldest supported release branch" that the fix applies to. Then we merge each older branch into the newer ones. (For example, we'll merge 2015.8 --> 2016.3, and then 2016.3 into develop.) That way all bugfixes will be present in each branch. Check out [these docs](https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch) for more info.

I can grab this back-port for now, no problem, but that information will likely be useful for you in the future. (Note that new features still go into the develop branch.)

**Comment by jfindlay** [comment]
Fixes #30968.

**Pull request merged**
