### PR TITLE
Update apt module regarding upgrade against hold packages.

### LINKED ISSUE #41231: PR #30777 misses an update to the documentation for pkg.installed and hold:true
After PR #30777 has been merged, the documentation for pkg.installed for apt with ```hold == True``` seems not updated. The behavior might furthermore be confusing with ```update_holds``` and would need some clarification:

Does apt require ```update_holds == True``` to also consider updating held packages or is this done transparently as soon as ```hold == True``` and current package version is unequal to desired package version? As far as browsing the commit d511dda90a843cb587fe56a11646f2f9485b2016 it seems the first approach was chosen.

### PR DESCRIPTION
**Pull request by abednarik**
### What does this PR do?

Update apt module documentation 

### What issues does this PR fix or reference?

Fixes #41231 and related to #30777

### Tests written?

No

### CODE REVIEW

**Comment by terminalmage** [comment]
@rallytime this docs update should be backported to 2016.11 as the change being referenced was introduced in 2016.11.0:

```
% git tag --contains d511dda90a
v2016.11
v2016.11.0
v2016.11.0rc1
v2016.11.0rc2
v2016.11.0rc3
v2016.11.1
v2016.11.2
v2016.11.3
v2016.11.4
v2016.11.5
v2016.9
v2016.9.0alpha1
v2017.5
```

**Comment by abednarik** [comment]
Let me know If creating a new PR against 2016.11 helps.

Cheers.

**Comment by terminalmage** [comment]
@abednarik No need, I backported in https://github.com/saltstack/salt/pull/41283.

**Comment by rallytime** [comment]
Thanks @terminalmage and @abednarik!

**Pull request merged**
