### PR TITLE
Add salt-ssh grains.items test

### PR DESCRIPTION
**Pull request by Ch3LL**
### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/43614

### CODE REVIEW

**Review by cachedout — APPROVED** [review]

**Comment by rallytime** [comment]
@Ch3LL Hmm...I don't think this new test ran. I don't see it in the test report.

**Comment by garethgreenaway** [comment]
@rallytime Apologies.  Missed your comment and only saw that the tests had passed before merging.

**Comment by Ch3LL** [comment]
For record I fixed this in https://github.com/saltstack/salt/pull/44317   this test is now running

**Comment by rallytime** [comment]
Awesome! Thanks for following up @Ch3LL.

**Pull request merged**
