### PR TITLE
[master] fix nightly repofile path

### LINKED ISSUE #64700: [BUG] nightly repo files - incorrect baseurl gpgkey url
**Description**
the nightly repo files have an incorrect path in them. it should be `https://repo.saltproject.io/salt-dev/master/latest/salt` but it is `https://repo.saltproject.io/salt-dev/master/salt`, notice the missing "latest" before salt 

```
curl https://repo.saltproject.io/salt-dev/master/latest/salt/py3/redhat/8/x86_64/minor/nightly.repo

[salt-nightly-repo]
name=Salt repo for RHEL/CentOS 8 PY3
baseurl=https://repo.saltproject.io/salt-dev/master/salt/py3/redhat/8/x86_64/minor/3006.1+768.g0a98359776
skip_if_unavailable=True
priority=10
enabled=1
enabled_metadata=1
gpgcheck=1
gpgkey=https://repo.saltproject.io/salt-dev/master/salt/py3/redhat/8/x86_64/minor/3006.1+768.g0a98359776/SALT-PROJECT-GPG-PUBKEY-2023.pub
```

### PR DESCRIPTION
**Pull request by ITJamie**
### What does this PR do?
fixes invalid path in nightly repo file

### What issues does this PR fix or reference?
Fixes: https://github.com/saltstack/salt/issues/64700

### Previous Behavior
path was missing date and thus was invalid

### New Behavior
path now has date and thus points to a valid repo

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

### CODE REVIEW

**Review by twangboy — APPROVED** [review]

**Review by s0undt3ch — APPROVED** [review]
Sorry it took me this long.

**Comment by ITJamie** [comment]
> Sorry it took me this long.

No worries. Is there any guidance on running these locally to test the repo file outputs? Theres a few more adjustments id like to propose

**Comment by s0undt3ch** [comment]
This PR was passing before I added the backport label, which triggered another run.

Merging.

**Comment by s0undt3ch** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[](https://github.com/saltstack/salt/pull/64918)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by s0undt3ch** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[](https://github.com/saltstack/salt/pull/64918)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by s0undt3ch** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[](https://github.com/saltstack/salt/pull/64918)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by s0undt3ch** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|3006.x|[](https://github.com/saltstack/salt/pull/64918)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
