### PR TITLE
Let docker-py auto detect version if not defined by user

### PR DESCRIPTION
**Pull request by loa**
Docker-py will auto detect docker version incase version 'auto' is used.
Reference: docker/docker-py#673

### CODE REVIEW

**Comment by loa** [comment]
This is untested, would really want to test but been unable to build rpm. Got stuck here: saltstack/salt#18789

**Comment by jfindlay** [comment]
@loa, regarding your desire to test from a package, we are getting close to autogenerating packages as part of our continuous integration processes using the rpmbuild, debbuild, etc. exec modules.

**Comment by loa** [comment]
@jfindlay Would be great!

**Comment by loa** [comment]
@jfindlay is it okey to add an PR to get into authors list? would be nice to be official contributor to salt :)

**Comment by jfindlay** [comment]
@loa, I don't think that would be a problem. :-)

**Pull request merged**
