### PR TITLE
Implement #6691 cmd in background

### PR DESCRIPTION
**Pull request by The-Loeki**
A fire&forget function & arg for the `cmdmod` module.

WIP & RFC

Would solve #6691

### CODE REVIEW

**Comment by The-Loeki** [comment]
@basepi I'm not done with this yet, but I'd like some feedback.

I've refactored the `TimedProc` slightly to take a wait arg.

Then I've wired it as `wait=True` in `run`, `shell`, `run_chroot`, `script`.

Lastly I've added a `run_bg`.

Two things I'd like to know:

* Are we happy like this? I'll finish up the doc & refine `run_bg` a bit further
* What do we think about the changing behaviour of the aforementioned functions when one adds the `wait` arg? A number of args would basically be useless. Is that something we leave up to the user or do I remove those args again and leave it at `run_bg`?

**Comment by The-Loeki** [comment]
@basepi: Happy New Year & bump :)

**Comment by basepi** [comment]
> Are we happy like this? I'll finish up the doc & refine run_bg a bit further

It's looking pretty good so far! I think I'm pretty happy with the direction you've taken.

> What do we think about the changing behaviour of the aforementioned functions when one adds the wait arg? A number of args would basically be useless. Is that something we leave up to the user or do I remove those args again and leave it at run_bg?

I guess I don't have a strong preference either way. I think it's pretty obvious that you won't get stdout and whatnot if you're not waiting for the results, but we could also add some argument checking if we wanted. I think to start your solution is fine once you finish up the docs. Thanks @The-Loeki !

**Comment by The-Loeki** [comment]
I'm not the one trippin' up Jenkins there ;)

**Comment by basepi** [comment]
This is looking really good. I think it's ready to merge! Thanks @The-Loeki, solid work!

**Comment by The-Loeki** [comment]
You welcome & thanks @basepi :)

**Comment by ozialien** [comment]
Latest bootstrap doesn't seem to have the fix.

**Pull request merged**
