### PR TITLE
Set Thy name, properly.

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
Sets Salt's main process to be called, `MainProcess` and makes sure the remaining processes started by Salt have meaningful names.
This is particularly useful when getting debug information from the system

### CODE REVIEW

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Review by krionbsd — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
