### PR TITLE
Fix /etc/hosts not being modified when hostname is changed

### LINKED ISSUE #42926: network.system not setting hostname in hosts file, preventing sudo.
### Description of Issue/Question
I'm currently using https://docs.saltstack.com/en/latest/ref/states/all/salt.states.network.html to set the hostname of my instance with
```
system:
  network.system:
    - enabled: True # only neccessary as a bypass for https://github.com/saltstack/salt/issues/6922
    - hostname: 'sample-hostname'
    - apply_hostname: True
    - retain_settings: True
```

This does modify my `/etc/hostname` correctly, but it does not set the hostname in `/etc/hosts`, instead, there it is the same as before the salt state was ran, so now there's a mismatch. Granted, I'm aware that https://docs.saltstack.com/en/latest/ref/states/all/salt.states.host.html exists, which allows for further modifications of `/etc/hosts`, but I assumed the network state call would completely set my hostname, across the whole system. Is it not supposed to? For me with the hostname mismatch, I couldn't use sudo.  See https://askubuntu.com/questions/59458/error-message-when-i-run-sudo-unable-to-resolve-host-none as to why sudo stops working in this case. I'm sure many other things would break too.

I'm unclear. I want to call this a bug, because I don't know why you'd want to change the hostname in only one place. I would have expected it to wipe out all remnants of the previous hostname. Perhaps it is meant to be this way though, in which case a documentation change should really happen to explain more precisely what this state is supposed to do.

### Setup
Debian 8 with
```
system:
  network.system:
    - enabled: True # only necessary as a bypass for https://github.com/saltstack/salt/issues/6922
    - hostname: 'sample-hostname'
    - apply_hostname: True
    - retain_settings: True
```

### Steps to Reproduce Issue
Provision an Debian 8 instance with the above state.

### Versions Report
Salt: 2017.7.0

### PR DESCRIPTION
**Pull request by mattLLVW**
### What does this PR do?
This PR fix `/etc/hosts` not being modified when the hostname is changed using module `network.system`
### What issues does this PR fix or reference?
Fixes #42926
### Previous Behavior
Because `/etc/hostname` was changed during `build_network_settings` in `salt.modules.debian_ip.py`,
`/etc/hosts` was not updated by `mod_hostname` in `salt.modules.network.py` (see issue).

### New Behavior
`/etc/hosts` is now updated accordingly
### Tests written?

No

### CODE REVIEW

**Comment by rallytime** [comment]
re-run py3

**Comment by cachedout** [comment]
@garethgreenaway You added some of the code a few years ago that is being removed here. Do you by chance remember what condition you were catching?

**Comment by garethgreenaway** [comment]
@mattLLVW Not entirely sure about this change.  Without the code that you're removing here how is the hostname in /etc/hostname going to be updated?

**Comment by mattLLVW** [comment]
@garethgreenaway sorry, i put the explanation in the issue, not the PR description.

`/etc/hostname` is changed by `modules.network.mod_hostname`.

`modules.network.mod_hostname` is called by `apply_network_settings`, so there is no new for it to be called twice.

**Comment by garethgreenaway** [comment]
@mattLLVW You're absolutely right.  It's been awhile since I've looked through this module.  Thanks!

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
