### PR TITLE
Remove support for aliasing cmd.run to cmd.shell

### PR DESCRIPTION
**Pull request by rallytime**
It's time to remove the aliasing for cmd.run to cmd.shell. This deprecation path has been here for a while.

### CODE REVIEW

**Comment by cachedout** [comment]
Hrm, these tests are all over the place. :-/

**Comment by rallytime** [comment]
While there are definitely some related errors in here, I think there is something broader going on with the test suite on the develop branch. I have been seeing these memory allocation errors sporadically on other PRs.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
The `integration.shell.enabled.EnabledTest.test_template_default_enabled` test is a related failure for sure here. I need to look at this.

**Comment by cachedout** [comment]
@rallytime We will need a rebase too, please.

**Comment by cachedout** [comment]
Bump @rallytime

**Comment by rallytime** [comment]
Ok, this is rebased and I fixed up the failing test. This should be good to go @cachedout once the tests are done running.

**Comment by cachedout** [comment]
@rallytime Thanks!

**Pull request merged**
