### PR TITLE
Revert "Reduce fileclient.get_file latency by merging _file_find and …

### PR DESCRIPTION
**Pull request by gtmanfred**
…_file_hash"

This reverts commit 94c62388e792884cebc11095db20e3db81fa1348.

Revert this commit because it breaks backwards compatibility with older masters.

@ninja- if you wanted to submit a new change to reimplement this, we would greatly appreciate it, but it is causing breakage when running older masters and 2017.7 minions.

@thatch45 

Thanks,
Daniel

### CODE REVIEW

**Comment by ninja-** [comment]
@gtmanfred I thought we agreed users should upgrade masters before they upgrade minions ???

**Comment by ninja-** [comment]
@gtmanfred um how about 

```
try {
ret = _file_hash_and_stat(...)
} catch (e) {
ret[0] = _file_find(...)
ret[1] = _file_hash(...)
}
```

?

It will add a bit of latency to these with old master, but will keep the 'access time cut in half' benefits for users which upgrade the master.
Or maybe a smarter if condition that checks protocol version, but I don't think there's such a thing as protocol version here.

**Comment by gtmanfred** [comment]
@ninja- yeah, technically that is correct, but we really prefer to not break that backwards compatibility.

After talking to @thatch45 we decided that this didn't give enough benefit as is to justify breaking backwards compatibilty.  I am on vacation starting a couple hours ago, but I think if you can check that that works for both older minions and newer minions, then I would bet that we can get this in, but please open a PR as soon as possible because we are looking at freezing and testing the 2017.7.2 release soon.

@rallytime @Ch3LL 

Thanks,
Daniel

**Comment by thatch45** [comment]
I think that I need to add a clarification here, while we advise users to upgrade the master first as best practice it should be required only as a last resort. If it is ever possible to maintain compatibility with old masters it should be done.
The project and users typically sustain a fair amount of damage from master/minion compatibility issues and we have avoided them for a long time now. The goal is that any supported releases of Salt can have bi-directional communication without issue.

**Pull request merged**
