### PR TITLE
pkgbuild.repo: add `timeout` parameter for waiting passphrase prompt

### PR DESCRIPTION
**Pull request by vutny**
### What does this PR do?

It adds `timeout` parameter with `15` seconds default value instead of hard-coded variable which controls how much time to wait for the GnuPG passphrase prompt when signing packages in a repo.
Also, corrected state and exec module function docstrings.
### What issues does this PR fix or reference?

The reason for this change is that if you have very large packages (hundreds of MiBs) or your system has temporarily slowed down by CPU or I/O, there could be not enough time to get a prompt for the passphrase from GnuPG.
### Previous Behavior

I have expected this from time to time:

``` yaml
    ----------
              ID: Create YUM repo in /srv/repo
        Function: pkgbuild.repo
            Name: /srv/repo
          Result: False
         Comment: An exception occurred in this state: Traceback (most recent call last):
                    File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1733, in call
                      **cdata['kwargs'])
                    File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1653, in wrapper
                      return f(*args, **kwargs)
                    File "/usr/lib/python2.7/dist-packages/salt/states/pkgbuild.py", line 366, in repo
                      res = __salt__[func](name, keyid, env, use_passphrase, gnupghome, runas)
                    File "/usr/lib/python2.7/dist-packages/salt/modules/rpmbuild.py", line 452, in make_repo
                      'Attemping to sign file {0} failed, timed out after {1} loops'.format(abs_file, times_looped)
                  SaltInvocationError: Attemping to sign file /srv/repo/dummy-1.0-x86_64.rpm failed, timed out after 21 loops
         Started: 11:07:07.941672
        Duration: 28925.478 ms
         Changes:   
```
### New Behavior

Now I am able to specify the timeout value as the state (and exec module) parameter:

``` yaml
Create YUM repo in /srv/repo:
  pkgbuild.repo:
    - name: /srv/repo
    - runas: root
    - keyid: 1122AABB
    - use_passphrase: True
    - timeout: 20
```
### Tests written?

No

### CODE REVIEW

**Comment by cachedout** [comment]
@dmurphy18 Could you please have a look here and ensure this all works for you?

**Comment by dmurphy18** [comment]
@cachedout Typically I prefer to add new parameters to the end of an API's parameter list, but the location for timeout makes sense. Looks fine to me, no issues, except close to tagging

**Comment by cachedout** [comment]
@dmurphy18 I agree.

@vutny Would you consider moving that kwarg to the end of the list?

**Comment by vutny** [comment]
@cachedout Sure thing. Moved the `timeout` kwarg to the end of the list in the `pkgbuild.repo` state function and both corresponding exec modules. Please review. Thanks.

**Pull request merged**
