### PR TITLE
tar option exclude

### PR DESCRIPTION
**Pull request by SlicerDicer**
### What does this PR do?
ability to use tar option exclude

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### CODE REVIEW

**Review by waynew — CHANGES_REQUESTED** [review]
@SlicerDicer This should be pretty easy to write some tests for - I'm pretty sure we have existing tests that you can either update or adapt to ensure that the `--exclude` parameter is included when provided.

This will also need a [changelog entry](https://docs.saltstack.com/en/master/topics/development/changelog.html#how-do-i-add-a-changelog-entry) marking that it's been added. Probably should also include the versionadded to the exclude part of the docstring.

**Comment by krionbsd** [comment]
@SlicerDicer you might test this test case, should work but it's untested by me

```
diff --git a/tests/pytests/unit/modules/test_archive.py b/tests/pytests/unit/modules/test_archive.py                                    
index c2a7f24d1d..ecfb45db84 100644                                                                                                     
--- a/tests/pytests/unit/modules/test_archive.py                                                                                        
+++ b/tests/pytests/unit/modules/test_archive.py                                                                                        
@@ -75,6 +75,39 @@ def test_tar():                                                                                                      
                 )                                                                                                                      
                                                                                                                                        
                                                                                                                                        
+def test_tar_with_exclude():                                                                                                           
+    with patch("glob.glob", lambda pathname: [pathname]):                                                                              
+        with patch("salt.utils.path.which", lambda exe: exe):                                                                          
+            mock = MagicMock(return_value="salt")                                                                                      
+            with patch.dict(archive.__salt__, {"cmd.run": mock}):                                                                      
+                ret = archive.tar(                                                                                                     
+                    "-zcvf",                                                                                                           
+                    "foo.tar",                                                                                                         
+                    ["/tmp/something-to-compress-1", "/tmp/something-to-compress-2"],                                                  
+                    "-C",                                                                                                              
+                    "--exclude",                                                                                                       
+                    "/tmp/something-to-compress-1/something-to-exclude",                                                               
+                    template=None,                                                                                                     
+                )                                                                                                                      
+                assert ["salt"] == ret                                                                                                 
+                mock.assert_called_once_with(                                                                                          
+                    [                                                                                                                  
+                        "tar",                                                                                                         
+                        "-zcvf",                                                                                                       
+                        "foo.tar",                                                                                                     
+                        "/tmp/something-to-compress-1",                                                                                
+                        "/tmp/something-to-compress-2",                                                                                
+                        "-C",                                                                                                          
+                        "--exclude",                                                                                                   
+                        "something-to-exclude",                                                                                        
+                    ],                                                                                                                 
+                    runas=None,                                                                                                        
+                    python_shell=False,                                                                                                
+                    template=None,                                                                                                     
+                    cwd=None,                                                                                                          
+                )                                                                                                                      
+                                                                                                                                       
+                                                                                                                                       
 def test_tar_raises_exception_if_not_found():                                                                                          
     with patch("salt.utils.path.which", lambda exe: None):                                                                             
         mock = MagicMock(return_value="salt")
```
poke me if you need more help

**Comment by SlicerDicer** [comment]
Appreciate the help there, I had to correct some syntax. 

That also shows me how to write a test for this thanks again.

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
