### PR TITLE
3010 exit codes Remembered for boot session

### PR DESCRIPTION
**Pull request by ghost**
### What does this PR do?
1.  win_pgk.install has a new paramater _report_reboot_exit_codes=True_. When this paramater has a value of True and an install ends with a 3010 exit code, win_system.set_reboot_required_witnessed is called. _win_system.set_reboot_required_witnessed_ creates(or leaves unchanged) the volatile registry key, _HKLM\SYSTEM\CurrentControlSet\Services\salt-minion\Volatile-Data_,  and underneath this key, the name 'Reboot required' has its value set to 1. _win_system.get_reboot_required_witnessed_ is the companion function to _win_system.get_reboot_required_witnessed_ and returns _True_ if the key exists and the name 'Reboot required' has a value of 1. Finally _win_system.get_pending_reboot_ also checks _win_system.get_reboot_required_witnessed_.
2. In _win_system_ _import read_value from reg_ was taken out and instead I'm using __salt__['reg.read_value']. @Twangboy indicates that what was done originally was probably a smallish mistake so this is for the best.
### What issues does this PR fix or reference?

This may conclude #33418 
### Tests written?

No

### CODE REVIEW

**Comment by lorengordon** [comment]
Nice, thanks @hrumph. Wondering though, since `win_pkg.install()` accepts `**kwargs`, and this isn't a param common across pkg providers, would it be better to pop `report_reboot_exit_codes` from `kwargs`?

i.e.:
```python
def install(name=None, refresh=False, pkgs=None, saltenv='base', **kwargs):
# ...
report_reboot_exit_codes=kwargs.pop('report_reboot_exit_codes', True)
```

**Comment by hrumph** [comment]
@lorengordon, yes your are right. I have made the recommmended change in the latest commit

**Comment by cachedout** [comment]
@twangboy and @lorengordon You guys both good with this now?

**Comment by lorengordon** [comment]
Makes sense to me. I'd maybe recommend [adding a doc note to states/pkg.py](https://github.com/saltstack/salt/blob/develop/salt/states/pkg.py#L1013) mentioning the new platform-specific kwarg and describe what it does.

**Comment by hrumph** [comment]
@lorengordon @cachedout, i have modified the documentation in state.py both for the _install_ and _latest_ functions.

**Comment by lorengordon** [comment]
:+1:

**Comment by twangboy** [comment]
Probably need to add a few `.. versionadded:: Carbon` in the doc string for new parameters and functions. Other than that, I think it's fine.

**Comment by hrumph** [comment]
@cachedout, I've implemented the doc fix suggested by @twangboy

**Pull request merged**
