### PR TITLE
Clean up tox + pytest

### PR DESCRIPTION
**Pull request by gtmanfred**
### What does this PR do?
Fixes `--run-destructive` and `--run-expensive` with pytest
Cleanup and simplify tox
Use requirements/tests.txt for installing python dependencies instead of git.salt from salt-jenkins (this will use git.minimal)

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by s0undt3ch — APPROVED** [review]
The same needs to be done for `expensive_test`

**Comment by s0undt3ch** [comment]
:star: :star::star::star::star:

**Comment by gtmanfred** [comment]
Expensive Tests added

**Review by s0undt3ch — APPROVED** [review]

**Review by terminalmage — APPROVED** [review]

**Comment by gtmanfred** [comment]
Ok, this is ready to go, and tests can be run using `tox` now.

The last thing to do is get the junits and coverage.xml dumped for Jenkins.

Daniel

**Pull request merged**
