### PR TITLE
Pr/remove duplicate unicode

### PR DESCRIPTION
**Pull request by breshead**
### What does this PR do?
Fixes previous pull request to convert to unicode unless it will result in an error. In that case return the raw value. 

### What issues does this PR fix or reference?
Remove duplicate unicode encoding for bug #46942 #49133

### Tests written?
No

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by terminalmage — COMMENTED** [review]
Is there a reason you opened a separate PR for this instead of just adding the change to https://github.com/saltstack/salt/pull/49133? Is https://github.com/saltstack/salt/pull/49133 now obsolete? If so, please close it.

**Comment by breshead** [comment]
First time doing PR's wasn't sure how things worked. Still not sure how to put this content in #49133.

**Comment by rallytime** [comment]
@breshead You can push commits directly up to your branch and GitHub will update teh pull request automatically.

**Comment by breshead** [comment]
Closing this as it is a duplicate.

**Pull request closed without merging**
