### PR TITLE
Update win_file.py

### PR DESCRIPTION
**Pull request by spenceation**
### What does this PR do?
Added support for grep like functionality on Windows minions. 

### What issues does this PR fix or reference?
N/A

### New Behavior
Added findstr method for Windows minions.

`salt '*' file.findstr 'c:\windows\system32\drivers\etc\hosts' myhost`

`foobar:`
`    127.0.0.1               myhost`
### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by rallytime** [comment]
Thanks @spenceation - Can you write some tests for this new function?

**Review by twangboy — APPROVED** [review]

**Comment by damon-atkins** [comment]
Unless findstr supports grep regex patterns this should be implemented in pure python code
e.g. use os.walker and open each file found and then regex search it.

**Review by damon-atkins — CHANGES_REQUESTED** [review]
Please ensure this supports regex string matching.

**Comment by morganwillcock** [comment]
You do have to be a bit careful with `findstr`. /r is needed to turn on the regex mode, and that is really a cut down version of what you get with grep (the running process is labelled as qgrep, but not sure what the q stands for). It also uses spaces to separate multiple search terms, so in `grep` the pattern "a b" will look for the string "a b", whereas the same search pattern with `findstr` will look for "a" and "b" separately unless you prefix it with /c: (but that then breaks the parameters of the function, pattern before args). So I think if this is labelled as `file.grep` it probably does need to be approximated in python, otherwise people won't get the expected results.

**Comment by spenceation** [comment]
This was in a previous closed pull request. I originally had submitted this as findstr and raised the same points. https://github.com/saltstack/salt/pull/43814

**Comment by damon-atkins** [comment]
@spenceation could you spend the time to write this in pure python please. This would be great, should be able to find. It does not need to support all of the grep options. If it stand runs faster enough it can be the same on all platforms.

**Comment by damon-atkins** [comment]
salt/utils/find.py:class GrepOption(Option)

**Pull request closed without merging**
