### PR TITLE
[PR port] Port #48148 and #50257 - Property managment in dracr module and state

### PR DESCRIPTION
**Pull request by roaldnefs**
PR port #48148 and #50257
- [x] Docs
- [ ] Changelog
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by roaldnefs** [comment]
Currently working on fixing the doc issue.

**Comment by roaldnefs** [comment]
Fixed markup in docstrings (579f194) and build the documentation locally to verify it's fixed.

**Review by Ch3LL — CHANGES_REQUESTED** [review]
We just need a changelog and some test coverage here.

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
