### PR TITLE
INFRA-4842 - boto_elb should return None when test=True and changes are pending

### PR DESCRIPTION
**Pull request by tkwilliams**
ELB module returns True rather than None when test=True and changes are scheduled.  This just updates the return code to None in these cases so things show up in the right colors, and also updates summary report numbers at the bottom.

### CODE REVIEW

**Comment by tkwilliams** [comment]
Hrm.  Introduced an error somewhere.  Closing momentarily...

**Comment by tkwilliams** [comment]
OK, figured it out - it was my state definition that was wrong, not this change :)  Re-opening.

**Comment by ryan-lane** [comment]
+1 looks great. thanks for the change :)

**Comment by tkwilliams** [comment]
Actually "Ooops" - it seems it now returns None even when it does NOT find a change is pending....  
Don't merge just yet please :)

**Comment by tkwilliams** [comment]
This may require a bit of an overhaul the the sub-dunder-function logic to allow it to do the right things at the right times...

**Comment by cachedout** [comment]
@tkwilliams Please let me know when you think that this is ready to go. Thanks!

**Comment by tkwilliams** [comment]
@cachedout  OK, I did a bit of an overhaul of the return logic from the sub-functions into the main state function.  It's looking good on my local system but let's see what the unit tests have to say :)

Thanks
t.

**Comment by tkwilliams** [comment]
@cachedout Sorry, finally got the unit tests all straightened out.  I really need to spend a couple of hours sometime soon wrapping my head around the MagicMock stuff - it is REALLY opaque at first glance (for me anyway :) ).

**Comment by cachedout** [comment]
@tkwilliams Oh no doubt! It took me a while to grok that stuff. It can be very...well, magic. ;]

**Comment by lomeroe** [comment]
@tkwilliams 

Sorry I'm late to this party, was the removal of the ability to specify a "dns_provider" in the cnames section intentional and part of the cause of the issue?

**Pull request merged**
