### PR TITLE
Fixes #34501 Bug-fix. Hiera didn't work without key

### LINKED ISSUE #34501: Error with hiera ext_pillar
### Description of Issue/Question

Fresh install from vagrant up. When i add hiera as ext_pillar i see in logs of salt-master error:

```
2016-07-06 22:16:04,829 [salt.master      ][ERROR   ][20878] Error in function _pillar:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1540, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1276, in _pillar
    data = pillar.compile_pillar(pillar_dirs=pillar_dirs)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 806, in compile_pillar
    pillar, pillar_dirs, errors=errors)
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 782, in ext_pillar
    self.opts.get('pillar_merge_lists', False))
  File "/usr/lib/python2.7/dist-packages/salt/utils/dictupdate.py", line 108, in merge
    merged = merge_recurse(obj_a, obj_b, merge_lists)
  File "/usr/lib/python2.7/dist-packages/salt/utils/dictupdate.py", line 84, in merge_recurse
    return update(copied, obj_b, merge_lists=merge_lists)
  File "/usr/lib/python2.7/dist-packages/salt/utils/dictupdate.py", line 38, in update
    raise TypeError('Cannot update using non-dict types in dictupdate.update()')
TypeError: Cannot update using non-dict types in dictupdate.update()
```
### Setup

```
root@saltmaster:/srv# cat /etc/salt/master | egrep -v '(^$|^#)'
interface: 192.168.50.10
ext_pillar:
  - hiera: /srv/hiera.yaml 
```

```
root@saltmaster:/srv# cat /srv/hiera.yaml 
:backends:
  - yaml
:yaml:
  :datadir: '/srv/hiera'
:hierarchy:
  - "hiera/test"
  - "hiera/test2"
```

```
Dirs tree:
root@saltmaster:/srv# tree /srv/hiera
/srv/hiera
├── hiera
│   ├── test2.yaml
│   └── test.yaml
└── qwerty
```

```
root@saltmaster:/srv# cat /srv/hiera/hiera/test2.yaml 
test2:
  123: 123
```
### Steps to Reproduce Issue

```
root@saltminion1:~# salt-call -l debug pillar.items
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.50.10:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (2412)
[DEBUG   ] Setting zmq_reconnect_ivl to '2412ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.50.10:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.50.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.50.10:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[ERROR   ] Got a bad pillar from master, type str, expecting dict: 
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded pillar.items
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.50.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.50.10:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[ERROR   ] Got a bad pillar from master, type str, expecting dict: 
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.50.10:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'minion1', 'tcp://192.168.50.10:4506')
[DEBUG   ] LazyLoaded nested.output
```

In logs i see:
`[ERROR   ] Got a bad pillar from master, type str, expecting dict:`
### Versions Report

```
root@saltmaster:/srv# salt --versions-report
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-91-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

### PR DESCRIPTION
**Pull request by fedusia**
### What does this PR do?

Fixes work hiera in salt
### What issues does this PR fix or reference?

https://github.com/saltstack/salt/issues/34501
### Previous Behavior

Hiera didn't work :(
### New Behavior

Salt can lookup pillar data from hiera db
### Tests written?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by fedusia** [comment]
I think it's wrong fix and should not merge it. I think i know workaround. when hiera enabled in config we have 2 problems:
1. if no keys passed to func ext_pillar in hiera.py then func return string should dict.
2. Need to pass pillars but i don't know how to tell salt to find pillars in hiera not in top.sls

**Comment by cachedout** [comment]
@fedusia Is this ready for us to have a look or are you still working on it?

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by fedusia** [comment]
@cachedout, Mike i'm working at this issue when i have free time. It's not ready for you yet. If you would like i can close this PR and create new when finish with this issue.

**Comment by cachedout** [comment]
@fedusia I'll go ahead and close this and when you're ready to go, please open a new one. Thank you very much!

**Pull request closed without merging**
