### PR TITLE
Added a beacon for GLXInfo

### PR DESCRIPTION
**Pull request by opdude**
It's current use is to create an event when no display is found

### CODE REVIEW

**Comment by fracklen** [comment]
I think the history would look nicer if you rebased instead of merging develop

Btw - test errors...

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
This is a clever idea! Nice work here.

**Comment by opdude** [comment]
Ha it's been quite essential for us, for some of our graphics test machines. No monitor no tests ;)

**Pull request merged**
