### PR TITLE
Add `fun` and `state` to the runtime internal keywords listing

### LINKED ISSUE #21120: highstate changes spurious warnings
At first, @s0undt3ch & @thatch45 i would be happy that the highstate behavior stay in the form as @s0undt3ch just commited, with the warnings summary, it's awsome.

Now, i have spurious warnings, from time to time, where i dont have those 'fun' & 'state' kwargs, i dont understand from where they are injected and throw the warnings:

```
ID: npm-version-0_10_36auto
Function: archive.extracted
Name: /srv/apps/node/0.10.36
Result: True
Comment: /srv/apps/node/0.10.36/bin/.node_0.10.36 already exists
Started: 17:54:00.978127
Duration: 0.643 ms
Changes:   
Warnings: 'fun' and 'state' are invalid keyword arguments for
          'archive.extracted'. If you were trying to pass additional data to
          be used in a template context, please populate 'context' with
          'key: value' pairs. Your approach will work until Salt Carbon is
          out. Please update your state files.
```

### PR DESCRIPTION
**Pull request by s0undt3ch**
Fixes #21120
Refs #21133
Refs https://github.com/saltstack/salt/issues/18806#issuecomment-76532356

### CODE REVIEW

**Comment by thusoy** [comment]
@s0undt3ch Could this be merged to develop as well? Otherwise develop still fails like in #21133 .

**Comment by s0undt3ch** [comment]
It will, on the next merge forward which shouldn't take that long...

**Comment by thusoy** [comment]
Awesome. :+1:

**Comment by anlutro** [comment]
Any reason bugfixes like these aren't being merged into existing stable releases?

**Comment by s0undt3ch** [comment]
This was missed and not backported to 2014.7 because I failed to submit the PR to 2014.7 and I also failed to tag the fix to be backported(I added it in #22365). Sorry for the trouble, The next 2015.2.x release will have this fix in and the next 2014.7.x release will also have it.

**Comment by anlutro** [comment]
Ah, my mistake for coming to quick conclusions. Thanks!

**Comment by s0undt3ch** [comment]
No worries! I only spotted it a few hours before you mentioning it because we had another issue similar to this one :)

If we hadn't had that issue, your comment would have brought this to my attention and I would have backported it.

So, keep'em coming!

**Comment by lorengordon** [comment]
You guys are awesome! Love searching issues and PRs and finding the answer to my question! :smile: (I also just ran into these warnings in 2014.7.4, with a simple file.touch/file.append state.)

**Comment by vladionescu** [comment]
Just upgraded to 2014.7.4 and ran into this as well - all my iptables states are broken.

Any chance of an immediate hotfix release to remedy this blocking issue?

**Comment by s0undt3ch** [comment]
The states don't fail because of this, so, why are your states broken? Because of the extra output?

**Comment by vladionescu** [comment]
I was under the impression this is causing it because my states fail with, for example, the following output:

```
Comment: Failed to set iptables rule for default_iptables-existing.
Attempted rule was /usr/sbin/iptables -t filter -A INPUT -m state --state RELATED,ESTABLISHED --fun append --jump ACCEPT for ipv4
```

If I run that command on my host I get the following:

```
# /usr/sbin/iptables -t filter -A INPUT -m state --state RELATED,ESTABLISHED --fun append --jump ACCEPT
iptables v1.4.21: unknown option "--fun"
Try 'iptables -h' or 'iptables --help' for more information.
```

This was not an issue in 2014.7.2 and cursory research led me to the issues referenced in this PR and then here.

**Comment by lorengordon** [comment]
Ahh, yes, I also have iptables states failing with that same error in v2014.7.4.

It's reported in issue #21133.

**Comment by vladionescu** [comment]
Mmhm, and #21133 is referenced in this PR, which makes me wonder if this will be back ported to 2014.7.4 and re-released.

**Comment by rallytime** [comment]
This does not need to be backported to 2014.7 as it was already fixed there in #22365. We won't be re-releasing 2014.7.4, but the fix will be included in the next release (either 2015.7.5, if we do one there, or in 2015.2.0, which should be out very soon).

**Comment by vladionescu** [comment]
Thank you!

Is there a release schedule or timeline available?

**Comment by rallytime** [comment]
Not officially. We just try to get them out as stable as we can as soon as we can. I know the 2015.2.0 is in the final stages of our testing process.

**Comment by vladionescu** [comment]
Thanks for the info, I appreciate it.

**Comment by rallytime** [comment]
Sure thing. I've added the PR above to alert users to this issue in 2014.7.4. Thanks!

**Pull request merged**
