### PR TITLE
[DO NOT MERGE] switch nova driver to using shade

### PR DESCRIPTION
**Pull request by gtmanfred**

### CODE REVIEW

**Comment by cachedout** [comment]
@gtmanfred What's the status on this one? Did you just want to see how the tests ran? Let me know if you're ready to have this one reviewed or if you'd like to close it. Thanks.

**Comment by gtmanfred** [comment]
I am working on some more stuff to it, and am going to be pushing a couple more commits to it in the next day or so.

Once I have it all stable, I am going to reopen the PR with more comments about the stuff I changed.

Thanks!

**Comment by cachedout** [comment]
@gtmanfred Sounds good. Thanks!

**Comment by gtmanfred** [comment]
I am waiting on a couple upstream patches to shade to go through to finish the last of the keystone stuff up.

https://review.openstack.org/#/c/268404
https://review.openstack.org/#/c/268361/

**Comment by cachedout** [comment]
@gtmanfred Sounds good. Just keep me posted.

**Comment by cachedout** [comment]
@gtmanfred In the meantime there are a few lint errors here that will need to be fixed before we're ready. Thanks.

**Comment by gtmanfred** [comment]
Yar, i am going to close this, and finish up the shade stuff (salt works on the stuff I finished making locally) and once I get shade updated, i will recreate this with the commits squashed :100:

**Comment by cachedout** [comment]
@gtmanfred Sounds great. Thanks for the follow-up.

**Pull request closed without merging**
