### PR TITLE
Bump to ``pytest-salt-factories>=1.0.0rc16``

### LINKED ISSUE #61909: [TEST FAILURE] `TestVirtMigrationTest.test_tls_migration` is flaky
[https://jenkins.saltproject.io/job/Full-PR/job/full-pr-fedora-35-x86_64/job/PR-1740/19/t[…]modules.test_virt/TestVirtMigrateTest/test_tls_migration/](https://jenkins.saltproject.io/job/Full-PR/job/full-pr-fedora-35-x86_64/job/PR-1740/19/testReport/junit/tests.pytests.integration.modules.test_virt/TestVirtMigrateTest/test_tls_migration/)
At least on Fedora-35, this is flaky.  Have not confirmed on other OS's yet

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title

### What issues does this PR fix or reference?
Extracted from the original changes in https://github.com/saltstack/salt/pull/61629

#### Additional Info About Changes In PR

The attributes ``.exitcode`` and ``.json`` still work but are now deprecated by ``.returncode`` and ``.data``.

Fixes https://github.com/saltstack/salt/issues/61909

### CODE REVIEW

**Review by garethgreenaway — DISMISSED** [review]

**Comment by garethgreenaway** [comment]
@s0undt3ch Looks like some tests failures here that may be related to the changes?

**Comment by s0undt3ch** [comment]
@garethgreenaway yes, they are. Should be fixed on next run.

**Comment by s0undt3ch** [comment]
re-run all

**Comment by s0undt3ch** [comment]
re-run all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Review by twangboy — DISMISSED** [review]

**Review by twangboy — APPROVED** [review]

**Pull request merged**
