### PR TITLE
add networking_config to container create fixes #51723

### LINKED ISSUE #51723: docker.container_running network_mode does not work with ipv4_address or ipv6_address
### Description of Issue/Question

`docker.container_running state` does not use the supplied `ipv6_address` if a custom `network_mode` is used.

### Setup
```sls
mynet:
  docker_network.present:
    - enable_ipv6: True
    - ipam_pools:
      - subnet: 10.0.20.0/24
        gateway: 10.0.20.1
      - subnet: fe3f:2180:26:1::/64
        gateway: fe3f:2180:26:1::1

test:
  docker_container.running:
    - image: busybox:latest
    - rm: true
    - detach: True
    - command: sleep 60000
    - network_mode: mynet
    - networks:
      - mynet:
        - ipv4_address: 10.0.20.50
        - ipv6_address: fe3f:2180:26:1::50
```

### Steps to Reproduce Issue
Run the above state. Run docker inspect test and notice that the addresses for the mynet connection are not the requested addresses. This fails when specifying both ipv4 and ipv6 or just ipv4 or just ipv6.

If you do not specify `network_mode`, the requested address is assigned, but the container is attached to both `mynet` and the default `bridge` network.

### Versions Report
```
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 3.7.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 3.7.3
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Jan 10 2019, 23:20:52)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.3.1
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.20.8-arch1-1-ARCH
         system: Linux
        version: Not Installed
```

### PR DESCRIPTION
**Pull request by clinta**
### What does this PR do?

This sets the networking options in the docker_container.running state

### What issues does this PR fix or reference?

#51723

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by dwoz — COMMENTED** [review]
@clinta It looks like a few docker related tests failed, please have a look.

**Comment by clinta** [comment]
Fixed the tests by making sure this option is only set for for the network specified by `network_mode`.

If this looks good I can squash the commits.

**Comment by dwoz** [comment]
@clinta Looks good now but it would be ideal if you could also add a test for this issue to ensure there are no regressions in the future.

**Comment by clinta** [comment]
I will try, I've been having a heck of a time getting the tests to even run locally though. I discovered that these [docs](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html) are no longer relevant. Is there an updated guide to salt tests somewhere else?

**Comment by clinta** [comment]
I never could get the tests running locally, but after abusing the jenkins server I've got a test demonstrating the issue in 092922d and fixed in 408d167.

**Comment by clinta** [comment]
This is freshly rebased with all CI checks passing.

**Review by twangboy — APPROVED** [review]

**Pull request merged**
