### PR TITLE
add ipmi support

### PR DESCRIPTION
**Pull request by steverweber**
ipmi module and state.
also including the pyghmi lib for shits and giggles.

### CODE REVIEW

**Comment by jfindlay** [comment]
@steverweber, there are some lint and documentation errors.

**Comment by cachedout** [comment]
It looks like this includes pyghmi. What is the reasoning behind bundling this with Salt versus just making pyghmi an optional dependency? I am not too inclined to ship a third-party library with Salt unless there is a very good reason.

**Comment by steverweber** [comment]
@cachedout inc the pyghmi was just for fun... the final PR wont have it.
yaya, doc and lint issues, when i have the time.

**Comment by cachedout** [comment]
@steverweber Thanks for the clarification

I am going to close this so that it does not accidentally get merged

Please re-submit this PR when it is ready to go and pygmi has been removed

**Pull request closed without merging**
