### PR TITLE
Boto_ASG fixes for scaling policy rate limiting and tag conversion

### PR DESCRIPTION
**Pull request by nasenbaer13**
### What does this PR do?

- fixes some edge cases of tags returned from aws
- retries reading scaling policies as this is easily rate limited by aws.

### What issues does this PR fix or reference?

- no reported ones, see above

### Tests written?

No

### CODE REVIEW

**Comment by nasenbaer13** [comment]
Please backport to 2017.7 if possible

**Comment by cachedout** [comment]
@saltstack/team-boto please have a look

**Review by tkwilliams — CHANGES_REQUESTED** [review]
This actually doesn't work as it should.  Per http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html, tags are actually UTF-8.
While admittedly the original code was broken WRT tags, if we're going to special case them in an attempt to fix, we may as well encode them to UTF-8 rather than ascii while we're in there :)

**Review by tkwilliams — COMMENTED** [review]
I would also strongly recommend a retry loop (look at other modules for some simple cases), rather than a single sleep for 2 seconds.  Generally when AWS start rate limiting a given endpoint, throttles will come hot and heavy on that service for a little while before catching up, so the common pattern is a loop with a 5 second wait, and some number of retries -- often as high as 30 to handle pathological cases.  This is generally OK because the retries won't be USED unless the service really is out to lunch.

**Comment by nasenbaer13** [comment]
@tkwilliams tags keys/values are now converted to utf8. 30 retries, each waiting for 5 secs implemented as suggested.

**Review by tkwilliams — APPROVED** [review]
A
```log.debug('Throttled by API, will retry in 5 seconds')```
inside the except clause, just to give the "Max retries" error at the end some context would be cool, but not essential.  That would be my only other recommended tweak, and otherwise this looks good to m...

**Comment by nasenbaer13** [comment]
@cachedout @tkwilliams, "retry" logging message added.

**Comment by cachedout** [comment]
Bump @ryan-lane. Do you have a thumbs up or down on this?

**Comment by ryan-lane** [comment]
+1

**Comment by rallytime** [comment]
Thanks everyone!

Test failures are not related.

**Pull request merged**
