### PR TITLE
Non-recursive fibonacci implementation.

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
### What does this PR do?
Non-recursive `test.fib` implementation.
- faster
- unlimited

### What issues does this PR fix or reference?
#41042

### Previous Behavior
```
$ python -m timeit -s 'import salt.modules.test as t' 't.fib_old(10)'
100000 loops, best of 3: 18.4 usec per loop
$ python -m timeit -s 'import salt.modules.test as t' 't.fib_old(20)'
100 loops, best of 3: 2.21 msec per loop
```

### New Behavior
```
$ python -m timeit -s 'import salt.modules.test as t' 't.fib(10)'
1000000 loops, best of 3: 1.07 usec per loop
$ python -m timeit -s 'import salt.modules.test as t' 't.fib(20)'
1000000 loops, best of 3: 1.58 usec per loop
```

### Tests written?
No

### CODE REVIEW

**Comment by thatch45** [comment]
Why close this? Looks good to me :)

**Comment by DmitryKuzmenko** [comment]
Ok, if @thatch45 approved this, it must be merged! =)

**Review by rallytime — APPROVED** [review]
Nice! 😆

**Comment by thatch45** [comment]
At least there is no complaining about my implementation of the collatz conjecture :)

**Comment by cachedout** [comment]
@thatch45 You are tempting fate.

**Comment by thatch45** [comment]
I would not mind seeing a better one :)

**Comment by basepi** [comment]
For the record, I purposely broke this years ago to make it slower, because it wasn't actually useful for showing delays in jobs. Turns out fibonacci is not hard to calculate to very high values in milliseconds.

**Comment by thatch45** [comment]
I am honestly amazed that this has seen so much attention, no love for the collatz conjecture

**Pull request merged**
