### PR TITLE
49855 fix file.line issues

### PR DESCRIPTION
**Pull request by waynew**
### What does this PR do?
This changes the tokenized approach for string comparison
and shifts it to direct comparison of the content and the line in question
to determine if any changes should be made during file.line insert/ensure before or after

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/49855

### Previous Behavior
Weird comparison of words that begin a line to determine if changes should be made

### New Behavior
Direct comparison on lines and content to be added.

### Tests written?
Manually tested by replacing site-packages files.
Adjusted unit tests to match new functionality.

### CODE REVIEW

**Review by Akm0d — DISMISSED** [review]

**Comment by icycle77** [comment]
Thank you @waynew for addressing this `2018.3` regression. Do you know if and when it'll merge to 2019? How about 2018, will it be backported? I think it should be since that's the release that broke it.

**Comment by waynew** [comment]
Now this backports https://github.com/saltstack/salt/pull/53889

**Comment by sagetherage** [comment]
@waynew can you rebase, please?

**Comment by sagetherage** [comment]
@waynew does this need rebase, again?

**Comment by waynew** [comment]
Yeah, looks like it. Pretty sure those failures will pass on the updated master.

**Comment by waynew** [comment]
Something is broken with this PR, opening a new one instead.

**Pull request closed without merging**
