### PR TITLE
Returning security group when no VPC id is given

### PR DESCRIPTION
**Pull request by ruxandraburtica**

### CODE REVIEW

**Comment by rallytime** [comment]
@ruxandraburtica Thank you for submitting this change!

It looks like you've got some [pylint errors](https://jenkins.saltstack.com/job/salt-pr-lint-n/11604/violations/file/salt/modules/boto_secgroup.py/). Would you mind fixing those up?

**Comment by ruxandraburtica** [comment]
@rallytime fixed the errors, but there are still some jobs failing, are those tests known for failing?

**Comment by jfindlay** [comment]
@ruxandraburtica, yes, those are known failures.

**Comment by cachedout** [comment]
Hi @ruxandraburtica . We don't typically raise exceptions in Salt execution modules. The typical pattern is to log an error message instead and, potentially, return information about what went wrong in the return. Is there a specific reason for this exception?

**Pull request merged**
