### PR TITLE
Made state-level failhard override global failhard.

### PR DESCRIPTION
**Pull request by github-abcde**
Also update documentation for failhard and onfail-requisites.
(I hope I got the refs right)

### What does this PR do?
It allows a global failhard setting to be overriden by a state-level failhard setting.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/20496

### Previous Behavior
Whenever global failhard is `True`, even setting failhard to `False` in the state still causes the state run to be aborted. 

### New Behavior
A state-level failhard  setting of `False` overrides (for that state only) a global failhard.

### Tests written?
No

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by garethgreenaway — APPROVED** [review]

**Comment by thatch45** [comment]
Just make sure that this is never backported into a point release because this is a behavior change :)

**Comment by rallytime** [comment]
@github-abcde Can you add a mention of this to the `Fluorine` release notes, please?

**Comment by github-abcde** [comment]
@rallytime This is new to me. Does this mean I have to add an entry to `docs/topics/releases/fluorine.rst'? (And would that be including the mention not to backport it?)

**Comment by rallytime** [comment]
@github-abcde Yeah, sorry for being unclear there. We need to make sure that behavior changes of this kind are documented in the release notes. In this case, that means the `Fluorine.rst` file. You don't need to worry about mentioning not to back-port this in the release notes.

**Comment by rallytime** [comment]
@garethgreenaway Can you review this again, now that some doc updates have been added?

**Review by garethgreenaway — APPROVED** [review]

**Comment by rallytime** [comment]
@github-abcde Ah, there looks to be a merge conflict in the release notes. Can you rebase this and fix the conflicts? Thanks!

**Comment by github-abcde** [comment]
@rallytime Done

**Review by cachedout — APPROVED** [review]

**Pull request merged**
