### PR TITLE
Re-open #35533 to resolve merge conflicts

### PR DESCRIPTION
**Pull request by terminalmage**
See #35533.

### CODE REVIEW

**Review by vutny — COMMENTED** [review]
This is great.

How about to update doc-strings for `cp` execution module to reflect this new functionality?

**Comment by terminalmage** [comment]
@vutny Good idea, I just pushed an extra commit to do this.

**Comment by rallytime** [comment]
@terminalmage It looks like some related tests are failing with this change.

**Comment by terminalmage** [comment]
@rallytime tests should be fixed now, I found the reason for the failures and all of the failing tests are now passing locally.

**Pull request merged**
