### PR TITLE
[nitrogen] Merge forward from 2016.11 to nitrogen

### PR DESCRIPTION
**Pull request by rallytime**
Conflicts:
  - salt/config/__init__.py

### CODE REVIEW

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@rallytime This is seeing weird failures. Could you bring it fully up-to-date with 2016.11 and see if things improve?

**Comment by rallytime** [comment]
Yeah, no problem. I'll submit a new PR.

**Comment by rallytime** [comment]
Oh, @cachedout I know what it is. I mishandled a merge-conflict that caused an error in `config/__init__.py`. There is a `.` instead of a `,` in a list. This is fixed in #41641. That should fare better.

**Pull request closed without merging**
