### PR TITLE
Use salt.utils.normalize_mode() instead of coercing int modes to octal

### PR DESCRIPTION
**Pull request by terminalmage**
This function was written by me a few weeks ago in the process of implementing mode preservation in `file.managed` and `file.recurse` states. However, upon discovering how much we were manually using `oct()` in Salt code to obtain octal mode strings, I realized that these instances would be negatively impacted when run in Python 3.

This pull request consolidates `salt.utils.st_mode_to_octal()` into `salt.utils.normalize_mode()`, and makes a change to normalize_mode which strips the Python 3 octal string specifier (i.e. the `0o` in `0o2775`).

This helps us in two ways:
1. Provides a single interface in Salt for returning a 4-character octal mode string, even when an integer mode is passed in.
2. Corrects for differences in the output of `oct()` between Python 2 and 3. For example:
#### Python 2

``` python
Python 2.7.12 (default, Jun 28 2016, 08:31:05)
[GCC 6.1.1 20160602] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> oct(420)
'0644'
>>> import salt.utils
>>> salt.utils.normalize_mode(420)
'0644'
>>>
>>> salt.utils.normalize_mode('644')
'0644'
>>> salt.utils.normalize_mode('0644')
'0644'
```
#### Python 3

``` python
Python 3.5.2 (default, Jun 28 2016, 08:46:01)
[GCC 6.1.1 20160602] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> oct(420)
'0o644'
>>>
>>> import salt.utils
>>> salt.utils.normalize_mode(420)
'0644'
>>> salt.utils.normalize_mode('644')
'0644'
>>> salt.utils.normalize_mode('0o644')
'0644'
```

### CODE REVIEW

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@terminalmage Some failures here:

```
integration.states.file.FileTest.test_managed_dir_mode
integration.states.file.FileTest.test_managed_file_mode_keep
integration.states.file.FileTest.test_managed_file_mode_keep_local_source
```

**Comment by terminalmage** [comment]
Thanks, I'll get these soon.

**Comment by cachedout** [comment]
@terminalmage Gentle bump ;]

**Comment by terminalmage** [comment]
Test failures have aged out from Jenkins, running the tests again.

**Comment by terminalmage** [comment]
OK, this was written based on some incorrect assumptions about our arg parsing. The states are all passing around modes as strings, while our custom yaml loader will load ``0700`` as an integer ``700``.

I'll need to refactor this.

**Comment by terminalmage** [comment]
By the time I get around to addressing this, the code may diverge, and I don't want to make any incorrect assumptions and cause breakage. Better to start this over from scratch when I have the time. This is not an immediate need, as we're not slated to support PY3 in even an experimental way until Nitrogen.

**Pull request closed without merging**
