### PR TITLE
LXC: Major fix & enhancements

### PR DESCRIPTION
**Pull request by kiorky**
This reconciles back makinacorpus's LXC fork into upstream.

This fixes various breakages introduced by the refactor which are so numerous that we cant enumerate them all :).

This also introduce some new features like network reconfiguration  and container reboot which will eventually readded later, in develop branch as 2015.2 is on a feature freeze.

This replace #20916 #21011 #20933

### CODE REVIEW

**Comment by kiorky** [comment]
hold on merge until discussed, i have also the password stuff to rewrite (@terminalmage solution in #20933 is not good either, i ll do something better in the next hours)

**Comment by terminalmage** [comment]
At this point, enhancements should go into develop. Let's make this pull request bugfixes only. I'm available on Freenode right now.

**Comment by terminalmage** [comment]
I'm currently in IRC with @kiorky and we are working through this PR diff by diff to make sure we are on the same page.

**Comment by terminalmage** [comment]
OK, we're done with the review, @kiorky will test and we'll continue to discuss if necessary.

**Comment by kiorky** [comment]
if @rallytime would do the tests on her setup she did the last time to see your use case, for me it's working fine for now.

**Comment by kiorky** [comment]
https://github.com/makinacorpus/salt/commit/e129ed534b414c115ca6da780118f2ffa846d64f should be merged to develop as soon as possible, for the record.

**Comment by rallytime** [comment]
@kiorky Sure, no problem. I will try and run the battery of tests sometime today. Mind fixing up that pylint error really quickly?

**Comment by terminalmage** [comment]
Yeah, looks like an extra space after ``'commented',``

https://jenkins.saltstack.com/job/salt-pr-lint-n/2367/violations/file/salt/modules/lxc.py/

**Comment by kiorky** [comment]
damn sry, too much github noise, i didnt saw the notice quickly, merged @terminalmage & thx

**Comment by terminalmage** [comment]
The Ubuntu test did not return results, I closed/reopened to kick off another round of tests.

**Comment by terminalmage** [comment]
@kiorky We are having issues with the modifications you made to the network profile support. Here is the profile data:

```yaml
lxc.container_profile:
  cent6:
    template: download
    options:
      dist: centos
      release: 6
      arch: amd64
 
lxc.network_profile:
  cent6:
    eth0:
      link: br0
      type: veth
      flags: up
```

Running the following ``lxc.create`` command generates a traceback:

```
salt myminion lxc.create profile=cent6 network_profile=cent6
```

Here is the traceback:

```
myminion:
    The minion function caused an exception: Traceback (most recent call last):
      File "/root/SaltStack/salt/salt/minion.py", line 1114, in _thread_return
        return_data = func(*args, **kwargs)
      File "/root/SaltStack/salt/salt/modules/lxc.py", line 1646, in create
        network_changes = apply_network_profile(name, network_profile)
      File "/root/SaltStack/salt/salt/modules/lxc.py", line 3649, in apply_network_profile
        edit_conf(path, out_format='commented', **network_params)
      File "/root/SaltStack/salt/salt/modules/lxc.py", line 3594, in edit_conf
        'nic_opts': nic_opts})
      File "/root/SaltStack/salt/salt/modules/lxc.py", line 704, in _config_list
        net_datas = _network_conf(conf_tuples=conf_tuples, **kwargs)
      File "/root/SaltStack/salt/salt/modules/lxc.py", line 522, in _network_conf
        old = _get_veths(conf_tuples)
      File "/root/SaltStack/salt/salt/modules/lxc.py", line 725, in _get_veths
        current_nic[item[0].strip()] = item[1].strip()
    IndexError: string index out of range
```

**Comment by terminalmage** [comment]
@kiorky The issue seems to be related to the data being passed to ``_get_veths()``. Here is the value of ``net_data`` in the call that generates this traceback:

```python
['# Template used to create this container: /usr/share/lxc/templates/lxc-download\n',
 '# Parameters pass ed to the template: --release 6 --dist centos --arch amd64\n',
 '# For additional config options, please look at lxc.container.conf(5)\n',
 '\n',
 '# Distribution configuration\n',
 {'lxc.include': '/usr/share/lxc/config/centos.common.conf'},
 {'lxc.arch': 'x86_64'},
 '\n',
 '# Container specific configuration\n',
 {'lxc.rootfs': '/var/lib/lxc/foo/rootfs'},
 {'lxc.utsname': 'foo'},
 '\n',
 '# Network configuration\n',
 {'lxc.network.type': 'empty'}]
```

**Comment by kiorky** [comment]
i will have a look tomorrow morning !

**Comment by terminalmage** [comment]
No problem, thanks for taking a look. Hope the information above is helpful

**Comment by kiorky** [comment]
i ve done the setup to reproduce, so just ready to debug at wake up ;)

**Comment by kiorky** [comment]
@terminalmage there is another thing considering which http://images.linuxcontainers.org/images/

Most images rely on dhcp, so they will ignore hardcoded network conf in configs, do we outsmart the users to also go edit the network conf.

To use the injected conf via the lxc config, we need to disable any network configuration inside containers because if not the container at boot time will (de)(re)configure the network nic(s).

**Comment by kiorky** [comment]
Also, i have pushed two new changesets: one for the specific fix about your former problem with centos template & another to make the "nic_opts" override trick avalaible consistently amongst all methods.

**Comment by kiorky** [comment]
damn fuck, the reconfigure/reboot are coming base, im going to rebase again to exclude them, sry !

**Comment by kiorky** [comment]
so you can read the two last changeset on that last list, those are the changes i just posted.

**Comment by kiorky** [comment]
GoGo Jenkins !

**Comment by terminalmage** [comment]
*Most images rely on dhcp, so they will ignore hardcoded network conf in configs, do we outsmart the users to also go edit the network conf.*

The CentOS images come with ``lxc.network.type=empty``. In ``lxc.create``, the network profile is only applied if it is passed, otherwise nothing will be applied. I haven't checked to see what will happen for ``lxc.init``, but I think that if you don't specify a profile then you should expect for the downloaded container to have the initial network config. Does that sound reasonable?

**Comment by kiorky** [comment]
for me, i dont bother as i use rootfs, so it's more for you :)

**Comment by kiorky** [comment]
important lxc extract
```
16:30 <kiorky> the thing is that if we specify explicitly a network profile
16:30 <kiorky> but we are still using an image which use dhcp under the hood
16:30 <kiorky> the network profile wont really be used at container time (well the network conf will be applied the container reconfigure itself up)
16:30 <kiorky> do you follow me ?
16:31 <kiorky> lxc.init just wrap commands directly in the container, so it will work, even if the network configuration is inconsistent with the network profile.
16:32 <kiorky> if the container has net, commands will certainly suceed without a glitch
```

**Comment by rallytime** [comment]
This looks great now! Thanks for making those fixes @kiorky! I've tested them and all looks well.

**Comment by terminalmage** [comment]
OK, we have added some documentation fixes and are waiting on jenkins to merge this PR.

**Comment by kiorky** [comment]
green !

**Comment by terminalmage** [comment]
Awesome. We are in the process of merging forward from 2014.7 -> 2015.2 right now, so I'm going to hold off on merging until that is complete, and then I'll resolve any resulting merge conflicts and get this PR merged.

**Comment by kiorky** [comment]
thx @terminalmage !

**Comment by kiorky** [comment]
oh so we need to make it up to develop to merge reconfigure & reboot @terminalmage

**Comment by terminalmage** [comment]
Yeah. I'll ping you once we've merged from 2015.2 -> develop and give you the green light to submit your PR for the new functions to develop.

**Pull request merged**
