### PR TITLE
Wrap properties loop with a check for None.  Closes GH-47696

### LINKED ISSUE #47696: 2017.7.5 zpool.present does not check for properties=None before attempting to enumerate properties
#37932 is not fixed in 2017.7.5

The zpool state still attempts to enumerate the contents of 'properties' when properties is None throwing a ```TypeError: 'NoneType' object is not iterable```

https://github.com/saltstack/salt/blob/19bb725698c1ead096a06749d99aad59266fbad8/salt/states/zpool.py#L199

It is fixed in 2018.  Can the fix be backported?

https://github.com/saltstack/salt/blob/fb3bf1ff3e8593b60b515ff6d40ed87a5a6d846c/salt/states/zpool.py#L269

### PR DESCRIPTION
**Pull request by darkpixel**
### What does this PR do?
Fixes #47696 

### What issues does this PR fix or reference?
Fixes #47696 

### Previous Behavior
Crash when properties are not specified due to attempting to enumerate a variable with the value None.

### New Behavior
Checks if properties is set to None before attempting to enumerate.

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by darkpixel** [comment]
Oops--I was supposed to be targeting v2017.7.6, not develop.  That should fix it.

**Comment by cachedout** [comment]
@sjorge Can you please look at this?

**Review by sjorge — APPROVED** [review]
LGTM

**Review by rallytime — APPROVED** [review]
Welcome @darkpixel! And thank you for submitting this fix.

**Comment by rallytime** [comment]
@darkpixel The 2017.7.7 release was a quick release with only a small number of critical fixes based off of the 2017.7.6 release.

This fix will be in the upcoming 2017.7.8 release.

**Pull request merged**
