### PR TITLE
fix for no grains in salt-ssh

### PR DESCRIPTION
**Pull request by thatch45**
### What does this PR do?

Fixes missing grains and pillar in salt-ssh due to the context dict in the loader, also adds msgpack to the thin
### Previous Behavior

Remove this section if not relevant
### New Behavior

Remove this section if not relevant
### Tests written?

Yes/No

### CODE REVIEW

**Comment by thatch45** [comment]
Was this test failing before? I can only reproduce it when I have salt installed with an older version.

**Comment by cachedout** [comment]
This test is failing as a result of this fix and was not failing before. I can reproduce it here.

**Comment by thatch45** [comment]
But it passes on my box when I uninstall salt locally. Also, I can't imagine this passing without the grains fix, so I am confused is all

**Comment by cachedout** [comment]
I can make it pass by reverting this fix on the same branch and the error I get is consistent with what would happen inside the loader with this fix applied, so we're crossing wires somewhere. I will be down there in a bit and we can go over it.

**Comment by thatch45** [comment]
Sounds good

**Pull request merged**
