### PR TITLE
Prevent spurious "Template does not exist" error

### PR DESCRIPTION
**Pull request by jettero**
I submitted this once before and it was merged in  #39516

I'm not sure if if it got left out because I PR'd in the wrong place or from some other conflict, but the same issue still exists in 2017.7.1 now.

### CODE REVIEW

**Comment by jettero** [comment]
Looks like @terminalmage merged it in some other places. Is there somewhere else I should PR this?

**Comment by cachedout** [comment]
I see the commit in the 2017.7.1 branch. Are you positive that it's the same issue?

**Comment by rallytime** [comment]
@jettero Did you see the question from @cachedout the other day?

**Comment by jettero** [comment]
@rallytime no, I did not. Thanks.

@cachedout Yes, pretty sure. It was a week ago, but I was getting a bunch of "Template does not exist: " errors (note, no template named in error); determined it was in the same code block, fixed it with vim on the live masters, and then made this PR. I don't feel as confident now as I did when I made the PR, but I'm pretty sure.

**Review by terminalmage — APPROVED** [review]
It looks like this change was lost in 2017.7.1, maybe due to a merge conflict resolution.

I've changed the head branch for this to 2017.7, we'll need to cherrypick this into the 2017.7.2 release branch to get it into that release.

**Review by cachedout — APPROVED** [review]

**Pull request merged**
