### PR TITLE
Add master_id to new job event load

### PR DESCRIPTION
**Pull request by pengyao**
### What does this PR do?

Add master_id to new job event load

### What issues does this PR fix or reference?

No

### Previous Behavior

`master_id`  is not exist in new job event load when clear_load have `master_id` 

### New Behavior

`master_id` is requesting in MultiMaster. Add `master_id` to new job event load when `master_id` in opts or clear_load

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by DmitryKuzmenko** [comment]
The change is not complex and looks good by the code.
But the reason of having `master_id` in the new_job local event that is fired only on the master's local event bus is questionable.
@pengyao could you please give me an example of using this?

**Comment by pengyao** [comment]
@DmitryKuzmenko `master_id` is required in MultiMaster. It identify the event come from which master, and can avoid event redundancy when aggregate multi master event bus

**Comment by DmitryKuzmenko** [comment]
The event bus is local. So each master in any configuration (multi or single master) has it's own event bus where the only this particular master's events could appear. This is the reason I'm asking for a particular usage example. Because I don't understand where it could be useful.

**Comment by sagetherage** [comment]
@pengyao can you rebase this against the master branch, please?

**Comment by sagetherage** [comment]
closing as abandoned

**Pull request closed without merging**
