### PR TITLE
add optional arguments for service.start

### PR DESCRIPTION
**Pull request by angeloudy**
A lot of FreeBSD services support optional arguments.
For example
`service jail start jail1`
`service  mysql-server start --wsrep-new-cluster`

### CODE REVIEW

**Comment by dwoz** [comment]
@angeloudy please look into the linter failure wha you can, thanks! :)

**Review by dwoz — APPROVED** [review]

**Comment by Ch3LL** [comment]
@angeloudy we are only accepting PRs to the master branch now. Any chance you can migrate to the master branch and add some tests for this change? If not i can definitely cherry-pic your commit onto the master branch for you.

**Comment by sagetherage** [comment]
@angeloudy looks like we have not heard from you in sometime, this may be closed as abandon by the author.

**Comment by sagetherage** [comment]
Reviewed in Grooming 2021-APR-05 we have attempted to communicate and will close

**Pull request closed without merging**
