### PR TITLE
Add full_return arg to LocalClient and RunnerClient

### PR DESCRIPTION
**Pull request by whiteinge**
### What does this PR do?

Add (or expose) `full_return` argument to LocalClient and RunnerClient so the exit code can be visible from salt-api or Salt's Python API if the user opts-in.

### What issues does this PR fix or reference?

#39452

### New Behavior

No changes to existing interfaces. If the new kwarg is given the the return structure is different.

### Tests written?

Yes

### CODE REVIEW

**Comment by cachedout** [comment]
@whiteinge Looks like this test wasn't very happy. https://jenkins.saltstack.com/job/PR/job/salt-pr-rs-cent7-n/8898/testReport/junit/integration.client.runner/RunnerModuleTest/test_full_return_kwarg/

**Comment by cachedout** [comment]
@whiteinge This also has a merge conflict, I'm afraid. Could you please rebase it?

**Comment by whiteinge** [comment]
Rebased.

**Comment by cachedout** [comment]
I didn't get to this in time. Sorry! One more rebase, please. :]

**Comment by whiteinge** [comment]
No worries. Easy fix. :-)

**Comment by cachedout** [comment]
@whiteinge One more lint error: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/9187/violations/file/salt/wheel/__init__.py/

**Comment by whiteinge** [comment]
That's an impressive catch by pylint. Kudos.

**Pull request merged**
