### PR TITLE
Add '*' case to api_acl.

### PR DESCRIPTION
**Pull request by TheScriptSage**
Hey folks.

In https://github.com/saltstack/salt/pull/25632 I added the api acl option, though we realized we also need a default case ('*'), so It's been added.

Should be a relatively minor change, I'll see what the tests say.

### CODE REVIEW

**Comment by TheScriptSage** [comment]
Tests look unrelated.

Will wait til you guys get back to me. 

Thanks.

**Comment by whiteinge** [comment]
Failures are unrelated. Thanks for the udpate.

**Comment by TheScriptSage** [comment]
@whiteinge;

Hey, can this possibly make it into 2015.8? (The api_acl and the change), I see it's in develop but we want to cut a release internally and want to use it.

Thanks either way!

**Comment by whiteinge** [comment]
@TheScriptSage the addition is safely config-gated so I'm good with it. If you open the pull req against 2015.8 I will sneak it in.

**Comment by TheScriptSage** [comment]
@whiteinge - See https://github.com/saltstack/salt/pull/26279.

I hope I did this right, I'd like to look into getting this merged.  :D  Thanks!

**Pull request merged**
