### PR TITLE
[dockerng] Enforce environment values to be strings.

### PR DESCRIPTION
**Pull request by ticosax**
@terminalmage Please can you review ?

### CODE REVIEW

**Comment by terminalmage** [comment]
@ticosax can you replace the raw string formatters? They cause formatting issues when the value is unicode, which we can't have as we try to make Salt run both on Python 2 and 3. For example:

```python
>>> import six
>>> non_string = 999
>>> stringified = six.text_type(non_string)
>>> 'The following is a raw string: {0!r}'.format(stringified)
"The following is a raw string: u'999'"
```

You'll need to quote these manually.

**Comment by ticosax** [comment]
sure, I will do that

**Comment by ticosax** [comment]
BTW, everything but a string will be formatted. So it should be good as it is ?

**Comment by thatch45** [comment]
@ticosax looks like we need a rebase, likely because I merged your other PR :)

**Comment by ticosax** [comment]
on it

**Comment by ticosax** [comment]
rebased

**Comment by rallytime** [comment]
@ticosax Ah! Looks like it needs another rebase. Probably because I just merged in your other pull request. Sorry about that!

**Comment by ticosax** [comment]
rebased.

**Pull request merged**
