### PR TITLE
Use pytoml for Toml Jinja filter

### PR DESCRIPTION
**Pull request by ghost**
### New Behavior

Support `|toml` as a Jinja filter for writing Toml configuration files.

### Tests written?

No

### CODE REVIEW

**Review by cachedout — CHANGES_REQUESTED** [review]
This will introduce a hard dependency on `pytoml` which we aren't willing to do. We need to find a way to do this that will work seamlessly if `pytoml` is not installed on a system.

**Comment by whiteinge** [comment]
There are a few places in Salt where things like this are hard-coded deps -- Jinja filters, supported template languages for `file.managed`, (some) outputters, (some) renderers. Now that we have the concept of [serializers](https://docs.saltstack.com/en/latest/ref/serializers/all/) as a module type I think it would make sense to add a generic interface (an execution module) around calling those. E.g., `{{ foo | serialize('toml') }}` or `{{ salt.slsutil.serialize(foo, 'toml') }}` or `salt '*' test.ping --serialize=toml`.

toml would make a great self-contained addition as a serializer module.

**Comment by grobinson-blockchain** [comment]
@cachedout I'm not sure I understand the issue? Saltstack already has a hard dep on PyYaml and many other python packages (which also aren't installed on most Linux/Unix systems by default)? Why is one extra pip package an issue?

**Comment by grobinson-blockchain** [comment]
@whiteinge that would be awesome!

**Comment by mirceaulinic** [comment]
@grobinson-blockchain you have to make this Jinja filter available only if the user has the library installed - see https://github.com/saltstack/salt/blob/develop/salt/utils/__init__.py#L48-L52.

> Why is one extra pip package an issue? Pytoml can just be installed as part of setup.py?

If that would be the case, we'd end up having thousands of dependencies. `pyyaml` is used for the core o salt, while `pytoml` is not critical.

Also, please make sure to document this filter: https://github.com/saltstack/salt/blob/develop/doc/topics/jinja/index.rst#filters and emphasise that pytoml is required.

**Comment by cachedout** [comment]
@grobinson-blockchain I echo the comments of @mirceaulinic. I'm happy to explain our reasoning in more depth if needed, but we won't be adding `pytoml` as a hard dependency to Salt.

**Comment by grobinson-blockchain** [comment]
Hello!

How would I go about adding a serializer for salt, re https://github.com/saltstack/salt/pull/41946#issuecomment-311471083. I'd like to migrate my Jinja macros for writing Toml to pytoml if possible.

**Comment by grobinson-blockchain** [comment]
@cachedout @mirceaulinic @whiteinge How would I go about adding a serializer for salt, re #41946 (comment). I'd like to migrate my Jinja macros for writing Toml to pytoml. Is it possible to do with the current version of salt, or does it require changes to the codebase?

**Comment by whiteinge** [comment]
@grobinson-blockchain They're pretty straightforward: add a Python module in [the serializers directory](https://github.com/saltstack/salt/tree/develop/salt/serializers) that implements `serialize` and `deserialize` functions ([for example](https://github.com/saltstack/salt/blob/develop/salt/serializers/json.py)). I made a quick PR #42376 to add the interface I mentioned above.

These kinds of additions do work with the current version of Salt if you're comfortable using Salt's `/srv/salt/_seralizers` & `/srv/salt/_modules` [dynamic modules](https://docs.saltstack.com/en/latest/ref/file_server/dynamic-modules.html) mechanism. If not then it will require waiting for the next Salt release.

**Pull request closed without merging**
