### PR TITLE
fix msg_pack

### PR DESCRIPTION
**Pull request by cmcmarrow**
PR:
Upgrade msg_pack to V1.0.0

Issue:
https://github.com/saltstack/salt/issues/57536

### GPG yes

### CODE REVIEW

**Review by xeacott — DISMISSED** [review]

**Review by bryceml — DISMISSED** [review]

**Review by xeacott — DISMISSED** [review]

**Comment by cmcmarrow** [comment]
re-run full

**Comment by cmcmarrow** [comment]
re-run full all

**Comment by cmcmarrow** [comment]
re-run full centos8

**Comment by cmcmarrow** [comment]
re-run full all

**Comment by cmcmarrow** [comment]
rerun-full all

**Comment by cmcmarrow** [comment]
re-run full all

**Comment by cmcmarrow** [comment]
re-run full all

**Review by xeacott — APPROVED** [review]

**Review by waynew — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Comment by cmcmarrow** [comment]
re-run full all

**Comment by cmcmarrow** [comment]
re-run full all

**Comment by dwoz** [comment]
re-run full all

**Comment by prometheanfire** [comment]
one of these times this will merge......

**Comment by cmcmarrow** [comment]
re-run macosxmojave all

**Comment by cmcmarrow** [comment]
re-run m2crypto all

**Comment by cmcmarrow** [comment]
re-run m2crypto all

**Comment by cmcmarrow** [comment]
re-run m2crypto all

**Comment by cmcmarrow** [comment]
re-run m2crypto all

**Comment by cmcmarrow** [comment]
re-run m2crypto all

**Comment by cmcmarrow** [comment]
re-run full all

**Comment by dwoz** [comment]
re-run full all

**Pull request merged**
