### PR TITLE
grains: Split os_data into smaller functions

### PR DESCRIPTION
**Pull request by bdrung**
The `os_data` function is huge (531 lines for one function is too long) and also deeply nested (8 levels deep). That make reading, modifying, and testing this function harder.

Split `os_data` into smaller functions to a readable 167 lines with only a nesting level of three.

`os_data` has a case-like statement to differentiate the different operating systems, but this is split into two parts.

To make the code more readable, combine all case-like statement in `os_data` to use one long if-elif chain.

### CODE REVIEW

**Comment by bdrung** [comment]
Rebased and added two more commits. `os_data` is now much cleaner and readable.

**Comment by bdrung** [comment]
Rebased and added a test case for `_linux_lsb_distrib_data()`.

**Review by dmurphy18 — CHANGES_REQUESTED** [review]
@bdrung Need to resolve the file conflicts and wondering how this interacts with changes in PR https://github.com/saltstack/salt/pull/61626, that is, does one need to be integrated before the other ?

Also needs a changelog entry

**Comment by bdrung** [comment]
@dmurphy18 https://github.com/saltstack/salt/pull/61626 is the final merge request containing all changes. Since that merge request is big, I split it into multiple smaller chunks (that stack on each other). This merge request is the first one. I rebased it on master and resolved the conflict.

**Review by dmurphy18 — DISMISSED** [review]

**Review by dmurphy18 — CHANGES_REQUESTED** [review]
Sorry forgot this will still need a changelog entry before can approve and merge.
Retrying failing tests - passed, but changes looks good.

**Comment by bdrung** [comment]
Why does this pull request need a changelog entry? It does not change anything for the user. Only https://github.com/saltstack/salt/pull/61626 has user facing changes and changelog entries.

**Review by dmurphy18 — APPROVED** [review]

**Comment by bdrung** [comment]
Thanks. The next pull request in this series is https://github.com/saltstack/salt/pull/61589

**Pull request merged**
