### PR TITLE
Backport #21199 to 2015.2

### PR DESCRIPTION
**Pull request by rallytime**
Backport #21199 to 2015.2

### CODE REVIEW

**Comment by steverweber** [comment]
fyi i cleaned up the commit on the dev branch. it was squashed,

**Comment by steverweber** [comment]
this backport should be recreated.  sorry.

**Comment by steverweber** [comment]
I cherrypicked it for ya in.
https://github.com/saltstack/salt/pull/21257

**Comment by steverweber** [comment]
/CLOSE/

**Comment by steverweber** [comment]
grr this was to be CLOSED!

**Comment by rallytime** [comment]
@steverweber Why did you cherrypick the changes in your new pull request when this pull request had already been made to backport the original changes? Did you make additional changes in your new cherry-picking pull request? Just curious; I feel like we're duplicating work.

**Comment by steverweber** [comment]
there was no changes... just cleaned up the git tree.
its no big deal that this was merged.. git is fine.

**Pull request merged**
