### PR TITLE
Make default pki directory configurable

### PR DESCRIPTION
**Pull request by bdrung**
The files in `/etc/salt/pki` are not configuration files in the sense of the FHS ("local file used to control the operation of a program"). Debian wants to change the default location to `/var/lib/salt/pki` (to properly follow FHS and to allow setting StateDirectory in the salt master systemd configuration).

Therefore introduce a `STATE_DIR` syspaths variable which defaults to `CONFIG_DIR`, but can be individually customized.

This merge proposal is a follow-up of merge proposal #46129.

fixes #3396
Bug-Debian: https://bugs.debian.org/698898

### CODE REVIEW

**Review by cachedout — COMMENTED** [review]
I'm curious how you came up with the `VARIABLE_STATE_DIR` variable name. It doesn't seem very descriptive for what's really being configured here. Would it be more appropriate to change this to something that references the PKI directory specifically?

**Comment by bdrung** [comment]
That's simple to answer: I am using the nomenclature of FHS. They call /var/lib "Variable state information". See http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s08.html
Autoconf uses a similar naming schema.

**Comment by cachedout** [comment]
@bdrung That is cool! I learned something new. Thanks!

**Review by cachedout — CHANGES_REQUESTED** [review]
I would like to see some documentation added for this before we merge it, please.

**Comment by bdrung** [comment]
Where should I add this documentation to?

**Comment by terminalmage** [comment]
@bdrung It looks like `doc/topics/installation/index.rst` would be a good place.

@cachedout what do you think?

**Comment by eliasp** [comment]
See also my proposal from a few years ago in #28070 with a few suggestions how to handle the transition from `/etc/salt/pki` to `/var/lib/salt/pki`…

**Comment by rallytime** [comment]
Hi @bdrung - Were you able to add the requested documentation for this? Also, this will need a rebase as well as a merge conflict has occurred.

**Comment by rallytime** [comment]
Since we haven't heard back here for a while, I am going to close this. We will gladly re-open this when you're ready or you can open a new PR with the requested changes. Whichever is easiest for you!

**Comment by bdrung** [comment]
Finally rebased on master and added the requested documentation. @terminalmage and @rallytime please reopen this merge request.

**Comment by terminalmage** [comment]
@bdrung Neither of us are able to do that, but one of @garethgreenaway @dwoz @waynew should be able to help.

**Comment by rallytime** [comment]
Hi @bdrung! Yeah, apologies I can't help out here now. I don't work at salt anymore, so i don't have permissions to open this again.

**Pull request closed without merging**
