### PR TITLE
Add minion.restart

### PR DESCRIPTION
**Pull request by plastikos**
### What does this PR do?

Adds minion.restart (and improves minion.kill)
### New Behavior

Can now restart minions from master
### Tests written?
- [ ] Yes
- [X] Not yet - coming
- Improve minion.kill for use by minion.restart
  - Add "retcode" status
  - Wait until the process dies (add timeout value)
  - Provide meaningful "comment" information when appropriate
- Add minion.restart: kills minion with minion.kill and then starts a new minion process
  - Can provide a specific `minion_restart_command` arg vector in minion configuration
  - If no `minion_restart_command` is available then uses `argv` of current process
  - If minion is not daemonized then it will kill but not restart - allows for
    direct management of minion by init, systemd or other direct process
    manager.
- Add EX_TEMPFAIL to exitcodes for timeout situtations (used by minion.kill)

TODO: integration tests

### CODE REVIEW

**Comment by cachedout** [comment]
I really like this. +1

**Comment by cachedout** [comment]
@plastikos Do you want to get this in now and follow-up with an additional PR with the TODOs or hold off until they're done? I'm fine either way.

**Comment by kev009** [comment]
Built in support for minion restart and upgrade has been a long time deficiency.  Can this be a state as well for watches?

**Comment by plastikos** [comment]
@kev009, I've been using this as an external module at our local site.  It works well for us, but may need some tweaking for ``systemd`` or other special cases.  I did allow for a local, custom restart argv configuration although maybe that should be a salt grain.

Once we get this accepted it seems reasonable to make it a state and do some additional things.  It's unclear what it means to continue a state on the other side of a restart.

**Comment by plastikos** [comment]
@cachedout, the integration tests are stalled-out waiting to be finalized in #32025 - this is likely okay to merge since it adds ``minion.restart`` as a new command and ``minion.kill`` is likely not widely-used so the modifications there shouldn't be too disruptive.

**Comment by plastikos** [comment]
@cachedout, let me clean-up the pylint and I'll call for a merge.

**Pull request closed without merging**
