### PR TITLE
[2016.3] Merge forward from 2015.8 to 2016.3

### PR DESCRIPTION
**Pull request by rallytime**
Conflicts:
- salt/cli/daemons.py
- salt/config/**init**.py
- salt/exceptions.py
- salt/pillar/foreman.py
- salt/returners/local_cache.py
- salt/states/saltmod.py
- salt/utils/**init**.py
- salt/utils/cloud.py

### CODE REVIEW

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
Go Go Jenkins!

**Pull request merged**
