### PR TITLE
Fix for multicast entries ipv6 routes on Linux

### PR DESCRIPTION
**Pull request by mkosmach**
### What does this PR do?
Add processing for multicast entries in ip -6 route show table all output

### What issues does this PR fix or reference?
Patrial fix (only for multicast entries for now) for saltstack/salt#58377

### Previous Behavior
backtrace whan network.routes used on LInux without netstat

### New Behavior
correct ipv6 route entry in network.routes

### Commits signed with GPG?
No

### CODE REVIEW

**Review by Ch3LL — CHANGES_REQUESTED** [review]
This will require test coverage and a changelog file

**Review by votdev — APPROVED** [review]
LGFM

Here is the output of my test:
```
root@omv6box:/home/vagrant# ip -6 route show table all
::1 dev lo proto kernel metric 256 pref medium
fe80::/64 dev ens6 proto kernel metric 256 pref medium
fe80::/64 dev ens8 proto kernel metric 256 pref medium
local ::1 dev lo table local proto kernel metric 0 pref medium
local fe80::5054:ff:fe27:25a6 dev ens8 table local proto kernel metric 0 pref medium
local fe80::5054:ff:fe58:56f dev ens6 table local proto kernel metric 0 pref medium
multicast ff00::/8 dev ens6 table local proto kernel metric 256 pref medium
multicast ff00::/8 dev ens8 table local proto kernel metric 256 pref medium
root@omv6box:/home/vagrant#
root@omv6box:/home/vagrant#
root@omv6box:/home/vagrant# salt-call --local --retcode-passthrough --no-color --out=json network.routes inet6
{
    "local": [
        {
            "addr_family": "inet6",
            "destination": "::1",
            "gateway": "::",
            "netmask": "",
            "flags": "U",
            "interface": "lo"
        },
        {
            "addr_family": "inet6",
            "destination": "fe80::/64",
            "gateway": "::",
            "netmask": "",
            "flags": "U",
            "interface": "ens6"
        },
        {
            "addr_family": "inet6",
            "destination": "fe80::/64",
            "gateway": "::",
            "netmask": "",
            "flags": "U",
            "interface": "ens8"
        },
        {
            "addr_family": "inet6",
            "destination": "::1/128",
            "gateway": "::",
            "netmask": "",
            "flags": "U",
            "interface": "lo"
        },
        {
            "addr_family": "inet6",
            "destination": "fe80::5054:ff:fe27:25a6/128",
            "gateway": "::",
            "netmask": "",
            "flags": "U",
            "interface": "ens8"
        },
        {
            "addr_family": "inet6",
            "destination": "fe80::5054:ff:fe58:56f/128",
            "gateway": "::",
            "netmask": "",
            "flags": "U",
            "interface": "ens6"
        },
        {
            "addr_family": "inet6",
            "destination": "ff00::/8",
            "gateway": "table",
            "netmask": "",
            "flags": "U",
            "interface": "ens6"
        },
        {
            "addr_family": "inet6",
            "destination": "ff00::/8",
            "gateway": "table",
            "netmask": "",
            "flags": "U",
            "interface": "ens8"
        }
    ]
}
```

**Comment by Ch3LL** [comment]
@mkosmach you okay closing this based on @votdev 's feedback?

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
