### PR TITLE
The docker state is not in beta

### PR DESCRIPTION
**Pull request by cachedout**

### CODE REVIEW

**Comment by cachedout** [comment]
cc: @kiorky (Please let me know if you agree that it is OK to remove this label.)

**Comment by kiorky** [comment]
Well i authored the module a long time ago, but i m not using it anymore for a long time.
We use internally LXC, and a fork of the lxc modules (before @terminalmage messes in it and bock contributions).

The people that i personally know to have an interrest in this modules :
 * @ticosax
 * @holmboe
 * @westurner
 * @eliasp

**Comment by westurner** [comment]
Are there tests to indicate whether this functionality is working?

**Comment by ticosax** [comment]
Hi, I've been keep away from docker technology, so I can not assert if it is stable or not, as I'm not using this module since few month.

**Comment by thatch45** [comment]
Yes, we have tests in place, but we still do need some more. But yes, we feel this is API stable

**Pull request merged**
