### PR TITLE
Fix versionadded in style guide

### PR DESCRIPTION
**Pull request by jasperla**
### What does this PR do?

The provided sample code incorrectly uses 'versionadded' in this instance.

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by jasperla** [comment]
re-run full all

**Comment by jasperla** [comment]
@dwoz Could you please tell me what the testcase should cover? I mean this is a documentation fix only.

**Comment by jasperla** [comment]
re-run full all

**Comment by jasperla** [comment]
@dwoz Could you please explain why you added the "Needs Testcase" label because I honestly cannot think of a testcase to write. Also, the test failure seems unrelated to my changes, no?

**Comment by waynew** [comment]
re-run macos

**Comment by waynew** [comment]
@dwoz not sure what the failing test was about... pretty sure unrelated to this docs-only PR 🙃  - https://jenkinsci.saltstack.com/job/pr-macosxmojave-py3/job/PR-57967/5/ if it turns out that test is flaky

**Review by waynew — APPROVED** [review]

**Comment by jasperla** [comment]
@dwoz the failing https://jenkinsci.saltstack.com/job/pr-opensuse15-py3/job/PR-57967/6/ test is unrelated to my documentation change, no?

@waynew could you please remove the label again? 🙃 

This is literally a two character patch...it feels pointless to keep submitting patches when stuff like this takes ages to get through 😞

**Comment by jasperla** [comment]
re-run all

**Review by waynew — APPROVED** [review]

**Pull request merged**
