### PR TITLE
salt/runner: respect `--timeout` argument when using `eauth`

### PR DESCRIPTION
**Pull request by eliasp**
When using external authentication, the `--timeout` argument for `salt-run` had no effect.

### What does this PR do?
It makes the `--timeout` argument for `salt-run` work once again in setups using external authentication.

### What issues does this PR fix or reference?
None

### Previous Behavior
Specifying `--timeout` on the CLI when using `salt-run` had no effect at all.

### New Behavior
`--timeout` is now respected again

### Tests written?
Yes

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by dwoz** [comment]
@eliasp Looks like multiple test suites are failing https://jenkinsci.saltstack.com/job/pr-opensuse15-py2/job/PR-55915/8/

**Comment by eliasp** [comment]
Anyone willing to take a stab at the tests? Can't figure out right now what's actually wrong and don't have much time to spare to dive into this again...

**Comment by eliasp** [comment]
I rebased this PR on current `master`, tests look good on my local box.
As I won't be involved with SaltStack in the foreseeable future, feel free to pick up the current branch to move forward with this PR.

**Comment by dwoz** [comment]
@eliasp Is this still something you would like to get in?

**Comment by eliasp** [comment]
Since I'm not using Salt anymore, unfortunately I can't dedicate any time to work on related PRs.

Feel free to either pick it up from here, since the change is quite trivial or close it and keep the bug.

**Comment by dwoz** [comment]
@eliasp I've rebased the changes and got the tests into a state where they run. However, they tests are failing and by the looks of the failures the timeout doesn't seem to be getting honored.

**Comment by dwoz** [comment]
This can be re-based and re-opened if it should get into `3008.x`

**Pull request closed without merging**
