### PR TITLE
Backport runtests.py modifications from develop to 2018.3

### PR DESCRIPTION
**Pull request by terminalmage**
This will allow us to run only the tests corresponding to the files that were changed, on PRs opened against 2018.3 (and Fluorine, once merged forward)

Refs: https://github.com/saltstack/salt/issues/50050

### CODE REVIEW

**Comment by gtmanfred** [comment]
You will probably want to backport this one as well https://github.com/saltstack/salt/commit/8a6692da153ade44df23aada004c7caa2492a8f4

**Comment by gtmanfred** [comment]
so that it runs the filemaps in this pr and we can verify.

**Comment by terminalmage** [comment]
@gtmanfred will that one commit there turn on the filename-based testing right away, or do you also need to make changes in `.ci/` as well?

**Comment by gtmanfred** [comment]
That is the only one needed, nothing from .ci/ was changed for this.

**Review by gtmanfred — APPROVED** [review]

**Review by rallytime — CHANGES_REQUESTED** [review]
In addition to the commit needed that @gtmanfred mentioned above, it looks like some of the test module renames (or new tests not in 2018.3?) need to be addressed. (See the lint failure.)

**Comment by rallytime** [comment]
OK, the rest of the test failures should all be fixed up now. 🤞

**Review by rallytime — APPROVED** [review]

**Pull request merged**
