### PR TITLE
Add a compat layer on zc.buildout state.

### LINKED ISSUE #20184: zc.buildout module broken in develop ...
```
         File "/srv/salt/makina-states/src/salt/salt/utils/__init__.py", line 801, in format_call
            '' if 'full' not in ret else ' Please update your state files.'
        SaltInvocationError: 'output_loglevel' and 'group' are invalid keyword arguments for buildout.installed. If you were trying to pass additional data to be used in a template context, please populate 'context' with 'key: value' pairs. Please update your state files.
````

### PR DESCRIPTION
**Pull request by kiorky**
This fixes #20184

### CODE REVIEW

**Comment by cachedout** [comment]
Could you clean up the pylint error please, @kiorky ? Then we'll get this merged. Thanks!

**Comment by kiorky** [comment]
ha. ok, sure.

**Comment by kiorky** [comment]
done.

**Comment by kiorky** [comment]
failed test seems unrelated

**Comment by cachedout** [comment]
Thanks, @kiorky

**Pull request merged**
