### PR TITLE
Pack log handlers with grains and mods

### PR DESCRIPTION
**Pull request by cachedout**
Refs #28999

### CODE REVIEW

**Comment by s0undt3ch** [comment]
I had this in place but then we had to revert it. Can't search for it since I'm on my phone.

Just so you know....

**Comment by cachedout** [comment]
@s0undt3ch Oh, dang. I wonder why? If you find it, let me know. We'll see how the tests do with it this time.

**Comment by s0undt3ch** [comment]
https://github.com/saltstack/salt/pull/26399

**Comment by cachedout** [comment]
@s0undt3ch FWIW, I cannot replicate that stacktrace against my PR.

**Comment by s0undt3ch** [comment]
And https://github.com/s0undt3ch/salt/commit/f3a7d9145753f3e6e5efa9b91db60023045d3026

**Comment by s0undt3ch** [comment]
Then we're probably cool now... Don't know what changed, but, AWSOME!

**Comment by cachedout** [comment]
@s0undt3ch Sounds good. If the test pass I'll merge this and let it sit in develop for a while and we'll see how it goes.

**Comment by s0undt3ch** [comment]
Be sure to grep the runtests log file for tracebacks...

**Comment by cachedout** [comment]
@s0undt3ch Good call. Will do.

**Comment by cachedout** [comment]
I don't seen any exceptions which appear to be caused by this. I'm going to go ahead and merge it.

**Comment by adelcast** [comment]
Seems like this change introduced an extra grains load operation, which can be expensive.

https://github.com/saltstack/salt/issues/29175

**Pull request merged**
