### PR TITLE
Loader: Also pack opts

### LINKED ISSUE #20908: develop: highstate interfers with __opts__ (breaks at least tls mod)
I think by the lazyloader stuff,  __opts__ is not more global for all modules
```

(Pdb) __salt__['tls.set_ca_path'].__globals__['__opts__'] is  __salt__['config.option'].__globals__['__opts__'] 
False
```

### PR DESCRIPTION
**Pull request by kiorky**
This fixes #20908

### CODE REVIEW

**Comment by kiorky** [comment]
damn errors seems unrelated

**Comment by kiorky** [comment]
seems stateconf failures are legit, looking.

**Comment by kiorky** [comment]
tests are far better now, dont know if the remaining failures are legit;

**Comment by kiorky** [comment]
Just pushed another changeset that must fix the remaining falling states, or go a bit further.

**Comment by kiorky** [comment]
lint errors are unrelated, and status is green for what was broken by this pr introduction at first.

So green to review and apply.

**Comment by kiorky** [comment]
i may have a side effect here, with the file.managed + blockreplace combination, the user is no more respected. If i remove the blockreplace state, the user is honoured correctly, and i'm wondering if it is the opt['test'] thing which activates too much.
So im veryfing if it is related to this introduced fix or another cornercase/bug to fix.

**Comment by kiorky** [comment]
uhm, it may be unrelated as i produce this new misbehavior during a "state.sls", and not during an highstate

**Comment by kiorky** [comment]
to illustrate the bug, the current sls
```
postgresql-pg_hba-conf:
  file.managed:
    - name: /tmp/tests
    - content: foo
    - user: ubuntu
    - mode: 750
    - group: root
    - template: jinja


append-to-pg-hba--block:
  file.blockreplace:
    - name: /tmp/tests
    - marker_start: "#-- start salt managed zonestart -- PLEASE, DO NOT EDIT"
    - marker_end: "#-- end salt managed zonestart --"
    - content: ''
    - append_if_not_found: True
    - backup: '.bak'
    - show_changes: True
    - require:
        - file: postgresql-pg_hba-conf

```


produces:
```
local:
----------
          ID: postgresql-pg_hba-conf
    Function: file.managed
        Name: /tmp/tests
      Result: True
     Comment: Empty file
     Started: 18:51:03.768306
    Duration: 1.534 ms
     Changes:
              ----------
              mode:
                  0750
              new:
                  file /tmp/tests created
              user:
                  ubuntu
----------
          ID: append-to-pg-hba--block
    Function: file.blockreplace
        Name: /tmp/tests
      Result: True
     Comment: Changes were made
     Started: 18:51:03.770175
    Duration: 34.258 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -0,0 +1,3 @@
                  +#-- start salt managed zonestart -- PLEASE, DO NOT EDIT
                  +
                  +#-- end salt managed zonestart --


Summary
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2


-rwxr-x--- 1 root root 91 févr. 23 18:51 /tmp/tests
```



If the blockreplace is omitted:
```
postgresql-pg_hba-conf:
  file.managed:
    - name: /tmp/tests
    - content: foo
    - user: ubuntu
    - mode: 750
    - group: root
    - template: jinja

{#
append-to-pg-hba--block:
  file.blockreplace:
    - name: /tmp/tests
    - marker_start: "#-- start salt managed zonestart -- PLEASE, DO NOT EDIT"
    - marker_end: "#-- end salt managed zonestart --"
    - content: ''
    - append_if_not_found: True
    - backup: '.bak'
    - show_changes: True
    - require:
        - file: postgresql-pg_hba-conf
#}

```
this procuces 
```
local:
----------
          ID: postgresql-pg_hba-conf
    Function: file.managed
        Name: /tmp/tests
      Result: True
     Comment:
     Started: 18:52:33.258766
    Duration: 1.081 ms
     Changes:
              ----------
              user:
                  ubuntu

Summary
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
-rwxr-x--- 1 ubuntu root 91 févr. 23 18:51 /tmp/tests
```

here the user is correctly set

**Comment by kiorky** [comment]
I think this may be yet another salt.utils.fopen bug, veryfing, i think i had quickfixed by switching to regular open() sometimes ago in our salt fork, but this may have diseappeared to rego to salt.utils.fopen and here comes problems.

**Comment by kiorky** [comment]
so its another bug, filling it, will try to post a fix

**Comment by cachedout** [comment]
I am closing this *only* because the discussion in #20908 has not been resolved and I don't want it to be accidentially merged until everybody is in agreement. (I'm not commenting one way or another on whether this is the right fix -- only that the discussion is ongoing.)

@kiorky Once that discussion has been resolved, please re-open this PR with any changes. Thanks. :]

**Comment by kiorky** [comment]
@cachedout @jacksontj @thatch45 i think this PR is afterall not on the line salt is going.

Im going to fix the tls mode to also use context retrieval.

Im also reverting that stuff in our local install.

**Pull request closed without merging**
