### PR TITLE
Allow for multiple versions of pkg with pkg.latest

### LINKED ISSUE #60931: [BUG] RHEL8 - pkg.latest shows failed when actually successful when updating kernel
**Description**
Using **pkg.latest** on RHEL8 and compatible systems to update the kernel the state will fail as multiple versions are now installed and the expected target doesn't match.
  
**Steps to Reproduce the behavior**
The following is the state which will fail on a successful patch.
 
```
common::patch::kernel:
  pkg.latest:
    - name: kernel
    - refresh: True
```

With the following output:
```
          ID: common::patch::kernel
    Function: pkg.latest
      Result: False
     Comment: The following packages failed to update: kernel
     Started: 22:29:33.006972
    Duration: 62886.163 ms
     Changes:   
              ----------
              kernel:
                  ----------
                  new:
                      4.18.0-305.19.1.el8_4,4.18.0-305.17.1.el8_4
                  old:
                      4.18.0-305.17.1.el8_4
              kernel-core:
                  ----------
                  new:
                      4.18.0-305.17.1.el8_4,4.18.0-305.19.1.el8_4
                  old:
                      4.18.0-305.17.1.el8_4
              kernel-modules:
                  ----------
                  new:
                      4.18.0-305.17.1.el8_4,4.18.0-305.19.1.el8_4
                  old:
                      4.18.0-305.17.1.el8_4
```

**Expected behavior**

Expects the pkg.latest to succeed as it has installed the expected version.

**Versions Report**

This is running on a masterless minion.

```
Salt Version:
          Salt: 3003.3

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Sep 21 2021, 10:09:35)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: oracle 8.4
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-305.17.1.el8_4.x86_64
        system: Linux
       version: Oracle Linux Server 8.4
```
</details>

### PR DESCRIPTION
**Pull request by owmtia**
### What issues does this PR fix or reference?
Fixes: #60931

### Previous Behavior
Previously it expected the version string to match exactly this isn't the case when multiple versions of the same package are installed. This is particularly noticeable when updating kernels.

### New Behavior
The new version will check if the target version exists in the , separated list and not fail when multiple versions are installed

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

### CODE REVIEW

**Review by Ch3LL — CHANGES_REQUESTED** [review]
this will require a changelog and test coverage.

**Comment by Ch3LL** [comment]
bump @owmtia did you see my review feedback?

**Review by twangboy — CHANGES_REQUESTED** [review]
Please add a changelog and a test case for this

**Comment by Ch3LL** [comment]
Closing due to inactivity. Please let me know if I need to re-open, or open a new PR against master with teh requested changes.

**Pull request closed without merging**
