### PR TITLE
Updating installation documentation to include new archive locations

### LINKED ISSUE #57706: [BUG] [DOCS] repo.saltstack.com incorrect links since SEP22 and needs more review of possible other dead/incorrect links
**Description**
repo.saltstack misses multiple older releases, for example http://repo.saltstack.com/apt/debian/9/amd64/archive/
This causes bootstrap issues, etc (master running on 2019.2.0, for ex) This also originally appears as incorrect GPG keys and confuses troubleshooting

**Setup**
Bootstrap CentOS7 or Debian9 (other repos might be also affected) with salt-bootstrap script, with for example these settings:
-F -P -I stable 2019.2.0

**Steps to Reproduce the behavior**
Results
CentOS
```
error: /tmp/salt-gpg-nMpYnO0T.pub: key 1 not an armored public key.
--
* ERROR: Failed to run install_centos_stable_deps()!!!
Process Process-5:
Traceback (most recent call last):
File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1288, in create
output = self.clouds[func](vm_)
File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/opennebula.py", line 1155, in create
ret = __utils__['cloud.bootstrap'](vm_, __opts__)
File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 644, in bootstrap
deployed = deploy_script(**deploy_kwargs)
File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 1762, in deploy_script
if root_cmd(deploy_command, tty, sudo, **ssh_kwargs) != 0:
File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 2372, in root_cmd
retcode = _exec_ssh_cmd(cmd, allow_failure=allow_failure, **kwargs)
File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 2047, in _exec_ssh_cmd
cmd, proc.exitstatus
```
Debian
```
Warning: apt-key output should not be parsed (stdout is not a terminal)
--
gpg: no valid OpenPGP data found.
* ERROR: Failed to run install_debian_deps()!!!
Process Process-5:
Traceback (most recent call last):
File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1288, in create
output = self.clouds[func](vm_)
File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/opennebula.py", line 1155, in create
ret = __utils__['cloud.bootstrap'](vm_, __opts__)
File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 644, in bootstrap
deployed = deploy_script(**deploy_kwargs)
File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 1762, in deploy_script
if root_cmd(deploy_command, tty, sudo, **ssh_kwargs) != 0:
File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 2372, in root_cmd
retcode = _exec_ssh_cmd(cmd, allow_failure=allow_failure, **kwargs)
File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 2047, in _exec_ssh_cmd
cmd, proc.exitstatus


```

**Expected behavior**
Archived versions either available or point to latest. 

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.13.2
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.3.8
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: 1.6.1
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: 3.7.3
         pygit2: 0.26.4
         Python: 2.7.5 (default, Apr  9 2019, 14:30:50)
   python-gnupg: 0.4.3
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 4.4.164-1.el7.elrepo.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```
</details>

### LINKED ISSUE #57885: [BUG] Archived salt repo 2017.7 points to the wrong repo URL
**Description**
When installing https://archive.repo.saltstack.com/yum/redhat/salt-repo-2017.7.el7.noarch.rpm it has the wrong URL in the file etc/yum.repos.d/salt-2017.7.repo that is created by installing this package.

The URL points to repo.saltstack.com instead of the correct archive.repo.saltstack.com

**Setup**
Standard CentOS 7 system with Salt 2017

**Steps to Reproduce the behavior**
yum -y install https://archive.repo.saltstack.com/yum/redhat/salt-repo-2017.7.el7.noarch.rpm
yum -y install salt-minion
Fails to install because it points the wrong repo URL

**Expected behavior**
The repo URL should be correct and it would be able to install the salt packages.

**Screenshots**

**Versions Report**
Salt 2017.7

### PR DESCRIPTION
**Pull request by ScriptAutomate**
### What does this PR do?
Updates installation documentation to point to new archive locations for particular operating systems, and update supported operating systems.

### What issues does this PR fix or reference?
Addresses broken links and directions in the installation documentation.

- Fixes #57706 
- Fixes #57885

### Previous Behavior
- Broken links were given when it came to referencing archived minions, or broken Python 2 download links were provided for 3001 (starting with 3001/Sodium, new salt minions are no longer built for Python 2).
- Outdated information in regard to what operating systems were supported.
- No release checklist item mentioning need to review installation docs.

### New Behavior
- Links to archives now work, and Python 2 links to non-existent 3001 downloads have been removed.
- Supported OS information has been updated for several target platforms.
- Release checklist item added about need to review installation docs.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by bryceml — DISMISSED** [review]
I didn't dig too far into this, but it looks good from what I can tell.

**Comment by ScriptAutomate** [comment]
Note: On being merged, #57807 can also be closed as it is duplicating one of the changes covered by this PR.

**Comment by ScriptAutomate** [comment]
Included additional archive steps to documentation, per #57885.

**Comment by ScriptAutomate** [comment]
@bryceml This now includes some additional `doc/conf.py` changes that were automatically applied by `pre-commit` (the pre-commit tests weren't present initially when the PR was first made). I've done some local tests with building the docs and they work as expected. I wasn't sure if the changes I made could have any unknown negative impacts that you could tell.

**Review by bryceml — APPROVED** [review]
Looks good.  Long term I think it would be nice for the documentation for this to only be in one place and have other places link to that one place.

**Comment by bryceml** [comment]
> @bryceml This now includes some additional `doc/conf.py` changes that were automatically applied by `pre-commit` (the pre-commit tests weren't present initially when the PR was first made). I've done some local tests with building the docs and they work as expected. I wasn't sure if the changes I made could have any unknown negative impacts that you could tell.

No idea if it breaks stuff, if it works for you and on the pr, we should be good I think.

**Comment by ScriptAutomate** [comment]
@dwoz This looks like it passes all tests, but the `macosxcatalina` test has an error where it couldn't finish downloading something, and is unrelated to this documentation update.

**Pull request merged**
