### PR TITLE
Make sha256 the default hash_type

### PR DESCRIPTION
**Pull request by dincamihai**
### What does this PR do?

sets the default hast_type to sha256 for master and minion
### Previous Behavior

currently the default is md5
### Tests written?

Yes

### CODE REVIEW

**Comment by isbm** [comment]
It is time, @thatch45 :wink:

**Comment by cachedout** [comment]
My concern here is what will happen on upgrades. We need to carefully test that scenario.

**Comment by isbm** [comment]
@cachedout We already using this in 2015.8, JFYI. We just thought it is a good idea to have it in `devel` so people naturally find it out. :laughing:

**Comment by isbm** [comment]
But last time we kind agreed that this should go to `devel` at some point anyway.

**Comment by cachedout** [comment]
Right, I remember that discussion. I just want to make sure we understand (and document) any effects encountered during an upgrade.

**Comment by thatch45** [comment]
If tests pass I say we take it. While the hash_sum value is not used for anything cryptographic or security related (file and cache integrity validation, we could technically use crc) it does unnecessarily freak people out. Also, the SUSE team has already tested this on upgrades and I have reviewed what the upgrade changes are. I think that we do it, we should be safe.

**Comment by cachedout** [comment]
I believe these test failures may be related and need to be addressed first:

```
unit.pillar.git_test.GitPillarTestCase.test_from_upper
unit.pillar.git_test.GitPillarTestCase.test_no_loop
integration.modules.cp.CPModuleTest.test_hash_file
integration.fileserver.roots_test.RootsTest.test_file_hash
```

**Comment by dincamihai** [comment]
@cachedout thanks for letting me know. I'm going to take a look now.

**Comment by cachedout** [comment]
Thanks, @dincamihai. Please let me know what you discover.

**Comment by dincamihai** [comment]
@cachedout
it seems that these two are also failing on `develop` and I'm not sure if these are related
- `unit.pillar.git_test.GitPillarTestCase.test_from_upper`
- `unit.pillar.git_test.GitPillarTestCase.test_no_loop`

for the other two I think I will have to change the tests because they do some assertions that expect md5. I'm going to do this tomorrow.

**Comment by thatch45** [comment]
Thanks @dincamihai , I assumed as much

**Comment by dincamihai** [comment]
@cachedout I've fixed these two tests:
- `integration.modules.cp.CPModuleTest.test_hash_file`
- `integration.fileserver.roots_test.RootsTest.test_file_hash`

**Comment by thatch45** [comment]
Very nice @dincamihai ! Thanks!
I will let the core team merge since they are more familiar with the state of tests on develop right now

**Comment by cachedout** [comment]
Hi @dincamihai We still need the event tests fixed please: `unit.utils.event_test.TestSaltEvent`

**Comment by dincamihai** [comment]
@cachedout fixed

**Comment by cachedout** [comment]
Merged! Thanks, @dincamihai . Great job here!

**Pull request merged**
