### PR TITLE
WIP: fix consul.acl_create rule creation

### PR DESCRIPTION
**Pull request by cesan3**
### What does this PR do?
Fixes an issue with the consul.acl_create function, where 'Rules' are provided. The structure is not supporting the format that is required for the consul ACL rules

### What issues does this PR fix or reference?
Fixes:TBD

### Previous Behavior
Remove this section if not relevant

If Rules attribute was provided, the rules text added was incorrectly formatted

### New Behavior
Consul ACL rules are correctly created. If we show the rules with acl_list:
For example, having a state that takes the rules as a list:
```
consul.acl_create_agent_token.{{ host }}:
  my_utils.acl_create:
    - name: {{ policy }}
    - consul_url: {{ consul.url }}
    - token: {{ secrets.mgmt_token }}
    - rules:
      - node: "{{ host + '.' + grains.domain }}"
        policy: "write"
      - agent: "{{ host + '.' + grains.domain }}"
        policy: "write"
      - session: "{{ host + '.' + grains.domain }}"
        policy: "write"
      - key: ""
        policy: "read"
      - service: ""
        policy: "read"

```
Then to check:
```
salt `hostname` consul.acl_list

          CreateIndex:                                                                                                                                                             
              81
          ID:
              e3d6e184-660a-381f-d2fe-d6978395b057
          ModifyIndex:
              82
          Name:
              host agent token
          Rules:
              node "host" {
                policy = "write"
              }
              service "" {
                policy = "read"
              }
              agent "host" {
                policy = "write"
              }
              session "host" {
                policy = "write"
              }
              key "" {
                policy = "read"
              }
          Type:
              client 
```

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Comment by cesan3** [comment]
I forgot I had this in WIP.  I'd still like to move through.

**Comment by cesan3** [comment]
Quick question, is the consul module being moved to an extension? or is kept in 'core' for now?

**Comment by dwoz** [comment]
@cesan3 it's going to end up as a community managed extension.

**Comment by dwoz** [comment]
@cesan3 Are you able to open a new PR with a changelog and test?

**Comment by cesan3** [comment]
> @cesan3 Are you able to open a new PR with a changelog and test?

Hello @dwoz  Ok, I'll open another MR and I'll add the changelog and test.

**Comment by dwoz** [comment]
> Hello @dwoz Ok, I'll open another MR and I'll add the changelog and test.

@cesan3 

Awesome, thanks!

**Pull request closed without merging**
