### PR TITLE
backport Add config option to pin pillarenv to effective saltenv to 2016.11

### PR DESCRIPTION
**Pull request by disaster123**
This is a backport of #38404 to 2016.11

### CODE REVIEW

**Comment by cachedout** [comment]
This is a feature, which we typically do not merge into bugfix branches, per policy. I would prefer that this stay in develop.

**Comment by disaster123** [comment]
This depends on the view. To me this is a bugfix. As the pillarenv implementation in 2016.11 is not usable. If you do not specificy pillarenv it uses all pillarenvs. There's no default pillarenv which you can override and there's no state_top_pillarenv or pillar_top_file_merging_strategy either.

**Comment by cachedout** [comment]
@disaster123 Is there an issue filed against this that we can look at?

**Comment by disaster123** [comment]
#28682
#4389

**Comment by terminalmage** [comment]
@disaster123 You are wrong about there being no default pillarenv to override. You can set ``pillarenv: foo`` in the minion config file and that will be the default pillarenv for that minion.

**Comment by terminalmage** [comment]
Note that leaving ``pillarenv`` unset does result in there being no specific pillarenv, and then the minion will use all environments. You should be able to do what you need by setting ``pillarenv`` in the minion config file. I don't think this feature should be merged, as it does not fix any bugs.

**Comment by disaster123** [comment]
To me this does not work.
salt-call pillar.items pillarenv=XYZ

still uses base if pillarenv: base is set in the minion config.

**Comment by terminalmage** [comment]
``pillarenv`` is not a master configuration parameter, it is a minion configuration parameter. I'll investigate why setting it there is interfering, but you should remove it.

**Comment by terminalmage** [comment]
@disaster123 Fix for the precedence of master vs. minion config is in https://github.com/saltstack/salt/pull/39286

**Comment by disaster123** [comment]
Not sure about the fix. But even if i remove pillarenv from the master config. It does not work when pillarenv: base is in the minion config as well. pillarenv on the cli does not seems to have any effect then.

salt-call pillar.items pillarenv=XYZ still uses the base pillar when base is defined in the minion config.

**Comment by terminalmage** [comment]
What version is your minion?

**Comment by disaster123** [comment]
2016.11.2

**Comment by terminalmage** [comment]
OK, I tried with the master and minion both running 2016.11.2 and I can't reproduce. My guess is that you have a problem with your Pillar configuration.

```
[root@5543f600e5fd /]# cat /etc/salt/master
pillar_roots:
  base:
    - /srv/pillar/base
  foo:
    - /srv/pillar/foo
[root@5543f600e5fd /]# cat /etc/salt/minion
master: localhost
id: test
pillarenv: base
[root@5543f600e5fd /]# for filename in `find /srv/pillar -type f`; do echo $filename; echo -------------------------; cat $filename; echo; done
/srv/pillar/base/top.sls
-------------------------
base:
  'test':
    - test

/srv/pillar/base/test.sls
-------------------------
base: True

/srv/pillar/foo/top.sls
-------------------------
foo:
  'test':
    - test

/srv/pillar/foo/test.sls
-------------------------
foo: True

[root@5543f600e5fd /]# salt test pillar.items
test:
    ----------
    base:
        True
[root@5543f600e5fd /]# salt test pillar.items pillarenv=foo
test:
    ----------
    foo:
        True
[root@5543f600e5fd /]# salt --versions-report
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Dec 21 2016, 07:16:46)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.0

System Versions:
           dist:
        machine: x86_64
        release: 4.9.8-1-ARCH
         system: Linux
        version: Not Installed

[root@5543f600e5fd /]# salt test test.versions_report
test:
    Salt Version:
               Salt: 2016.11.2

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.6.0
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.9.4
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.24.0
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.13 (default, Dec 21 2016, 07:16:46)
       python-gnupg: Not Installed
             PyYAML: 3.12
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.4.2
                ZMQ: 4.2.0

    System Versions:
               dist:
            machine: x86_64
            release: 4.9.8-1-ARCH
             system: Linux
            version: Not Installed
```

**Comment by disaster123** [comment]
OK found the problem. The problem is that my roots are checked out git branches which have the same base.

So the top file is the same in each environment.

for the saltenv i solved this by using:
top.sls:
{{ saltenv }}:
  '*':
    ...

while for the pillar top i have:
top.sls
{{ env }}:
  '*':
    ...

but it seems env is not the current pillarenv. But it seems there is no {{ pillarenv }} either?

**Comment by terminalmage** [comment]
I created a docker container you can use to test this:

```
% docker run --rm -it terminalmage/issues:pr39211
[root@a2e75a98fd45 /]# salt-master -d; salt-minion -d
[root@a2e75a98fd45 /]# salt test pillar.items
test:
    ----------
    base:
        True
[root@a2e75a98fd45 /]# salt test pillar.items pillarenv=foo
test:
    ----------
    foo:
        True
```

**Comment by disaster123** [comment]
@terminalmage  thanks a lot. See my last post. I found my problem but i've no idea how to fix it without saltenv = pillarenv. Can you have a look? I'm missing a jinja var with the current pillarenv

**Comment by terminalmage** [comment]
There is no ``{{ pillarenv }}`` in the jinja context. Because pillar uses some of the same code that states use to parse top files, the jinja variable for the environment is acually ``{{ saltenv }}``, even in pillar.  ``{{ env }}`` has been deprecated in the jinja context (and in salt in general) for several feature releases, and support for using ``{{ env }}`` was dropped in 2016.11.0.

The ``pillarenv`` param is still kind of new in Salt. It has been around for several releases but had a very narrow scope until recently, and I have been working to expand its use so that it is more distinct from the saltenv.

**Comment by disaster123** [comment]
thanks but saltenv is saltenv so having a
pillar/top.sls
{{ saltenv }}:
 ...

does not work for a command like
salt-call pillar.items pillarenv=ABC

as saltenv is still base - to the top.sls does not match. Is there no chance to get the pillarenv in a jinja template?

**Comment by terminalmage** [comment]
Did you even test this? Sorry if I seem annoyed, but I gave you a very clear explanation of why you should be using ``{{saltenv}}`` in the pillar top files to represent the pillar environment; pillar compilation uses the same logic to parse top files, so the pillar environment takes the place of ``{{saltenv}}`` in the jinja context, during pillar compilation.

```
%  docker run --rm -it terminalmage/issues:pr39211
[root@ec9b55bb6b38 /]# for filename in `find /srv/pillar -type f`; do echo $filename; echo -------------------------; cat $filename; echo; done
/srv/pillar/base/test.sls
-------------------------
base: True

/srv/pillar/base/top.sls
-------------------------
{{saltenv}}:
  'test':
    - test

/srv/pillar/foo/test.sls
-------------------------
foo: True

/srv/pillar/foo/top.sls
-------------------------
{{saltenv}}:
  'test':
    - test

[root@ec9b55bb6b38 /]# salt-master -d; salt-minion -d
[root@ec9b55bb6b38 /]# salt test pillar.items
test:
    ----------
    base:
        True
[root@ec9b55bb6b38 /]# salt test pillar.items pillarenv=foo
test:
    ----------
    foo:
        True
```

**Comment by disaster123** [comment]
I'm so sorry. Too late here. Thanks a lot! Now i got it.

**Comment by terminalmage** [comment]
OK, I added a section to the docs [here](https://github.com/saltstack/salt/pull/39291/files) that should hopefully clear this up.

Should we close this PR, then?

**Comment by disaster123** [comment]
yes thanks

**Pull request closed without merging**
