### PR TITLE
Revoke auth immediately on minion key deletion

### LINKED ISSUE #25124: salt-minion still communicating with salt-master after "salt-key -d hostname"
```
root@ursa:~# salt-key -d ursa
The following keys are going to be deleted:
Accepted Keys:
ursa
Proceed? [N/y] y
Key for minion ursa deleted.
root@ursa:~# salt \* state.highstate test=True
ursa:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1142, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/state.py", line 507, in highstate
        st_ = salt.state.HighState(opts, pillar, kwargs.get('__pub_jid'))
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 3029, in __init__
        self.state = State(self.opts, pillar, jid)
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 579, in __init__
        self.opts['pillar'] = self._gather_pillar()
      File "/usr/lib/python2.7/dist-packages/salt/state.py", line 600, in _gather_pillar
        ret = pillar.compile_pillar()
      File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 83, in compile_pillar
        dictkey='pillar',
      File "/usr/lib/python2.7/dist-packages/salt/transport/__init__.py", line 271, in crypted_transfer_decode_dictentry
        ret = self.sreq.send('aes', self.auth.crypticle.dumps(load), tries, timeout)
      File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 275, in send
        return self.serial.loads(self.socket.recv())
      File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 98, in loads
        return msgpack.loads(msg, use_list=True)
      File "_unpacker.pyx", line 114, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:114)
    ExtraData: unpack(b) recieved extra data.
Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
root@ursa:~# salt --versions-report
                  Salt: 2015.5.0
                Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
                Jinja2: 2.7.2
              M2Crypto: 0.21.1
        msgpack-python: 0.3.0
          msgpack-pure: Not Installed
              pycrypto: 2.6.1
               libnacl: Not Installed
                PyYAML: 3.10
                 ioflo: Not Installed
                 PyZMQ: 14.0.1
                  RAET: Not Installed
                   ZMQ: 4.0.4
                  Mako: 0.9.1
 Debian source package: 2015.5.0+ds-1trusty1
```

### PR DESCRIPTION
**Pull request by cachedout**
Fixes #25124

### CODE REVIEW

**Comment by jfindlay** [comment]
@cachedout, [this test](https://jenkins.saltstack.com/job/salt-pr-rs-cent7-n/7871/testReport/junit/integration.shell.key/KeyTest/test_keys_generation_no_configdir/) might be related.

**Comment by cachedout** [comment]
Hrm. I cannot replicate those failures at all. How odd.

**Comment by jodv** [comment]
I'm concerned that this might clobber the `--rotate-aes-key=False` option to salt-key.  Was that something that you tested, @cachedout ?

**Comment by cachedout** [comment]
I don't see how this would trigger an AES key rotation. Could you elaborate?

**Comment by jodv** [comment]
The module function `saltutil.revoke_auth` calls `delete_key` and rotates the AES key by default as shown in the below output

```
[INFO    ] User sudo_jrosenba Published command saltutil.revoke_auth with jid 20150908163522910957
[DEBUG   ] Published command details {'tgt_type': 'glob', 'jid': '20150908163522910957', 'tgt': 'jodv_venv_minion', 'ret': '', 'user': 'sudo_jrosenba', 'arg': [], 'fun': 'saltutil.revoke_auth'}
[DEBUG   ] Gathering reactors for tag salt/job/20150908163522910957/new
[DEBUG   ] MasterEvent PUB socket URI: ipc:///Users/jrosenba/.virtualenvs/jodv-salt-new/var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: ipc:///Users/jrosenba/.virtualenvs/jodv-salt-new/var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event - data = {'id': 'jodv_venv_minion', '_stamp': '2015-09-08T23:35:22.966643', 'result': True, 'act': 'delete'}
[INFO    ] Rotating AES key
[DEBUG   ] Gathering reactors for tag salt/key
[DEBUG   ] LazyLoaded local_cache.prep_jid
[INFO    ] Got return from jodv_venv_minion for job 20150908163522910957
[DEBUG   ] Sending event - data = {'fun_args': [], 'jid': '20150908163522910957', 'return': True, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2015-09-08T23:35:23.004961', 'fun': 'saltutil.revoke_auth', 'id': 'jodv_venv_minion'}
[DEBUG   ] Gathering reactors for tag salt/job/20150908163522910957/ret/jodv_venv_minion
```

Here's what I think will happen:

When `saltutil.revoke_auth` is sent to the minion from the initial `delete_key` call, any value for `rotate_aes_key` in the opts for the `Key` instance set from the CLI execution won't be passed.  The minion will send back a `revoke_auth` request as defined in the module function and the master will instantiate a new `Key` object with its own opts (i.e. not the ones passed in by the salt-key CLI execution).  Then, `rotate_aes_key` will default to True unless it happens to be specifically set to False in the master config when `delete_key` is called.

I'm looking at https://github.com/saltstack/salt/blob/develop/salt/modules/saltutil.py#L765 and https://github.com/saltstack/salt/blob/develop/salt/daemons/masterapi.py#L993

Let me know if that makes sense.  Thanks!

**Comment by cachedout** [comment]
Ah, yes. Good catch. That's an unintended side-effect. We'll need to fix that before we merge this. Thanks for the careful review!

**Comment by cachedout** [comment]
@jodv So, funny story. It turns out that option wasn't respected at all because it was being parsed as a string and evaluated as a bool. Fun times. :]

So, I fixed that and then added a check to see if that option was set before deciding whether or not to revoke a key. A warning is thrown otherwise.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by jodv** [comment]
@cachedout  Heh, that *is* funny ;)  Thanks for diving into this!

**Pull request merged**
