### PR TITLE
Fix etcd with sdb (fixes #52268)

### LINKED ISSUE #52268: trivial bug when using etcd with sdb
### Description of Issue/Question
After configuring etcd as an sdb target, running a command like this produces an error:
salt-call sdb.set sdb://mysdb/mynewkey mynewval
...
  File "/usr/lib/python2.7/site-packages/salt/sdb/etcd_db.py", line 78, in get
    return result.value
AttributeError: 'unicode' object has no attribute 'value'

The 'get' function in the EtcdClient class defined in utils/etcd_util.py already returns just the 'value' attribute of the python-etcd return object:
    return getattr(result, 'value', None)

But then 'get' in sdb/etcd_db.py tries to get the value of the value, which fails:
    client = _get_conn(profile)
    result = client.get(key)
    return result.value

Patching that to just 'return result' fixes the issue.

--- sdb/etcd_db.py.orig	2019-03-20 16:57:18.326708536 -0400
+++ sdb/etcd_db.py	2019-03-20 16:57:49.103070138 -0400
@@ -74,8 +74,9 @@
     Get a value from the etcd service
     '''
     client = _get_conn(profile)
-    result = client.get(key)
-    return result.value
+    return client.get(key)
 
 def delete(key, service=None, profile=None):  # pylint: disable=W0613

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

### PR DESCRIPTION
**Pull request by jnielsendotnet**
### What does this PR do?
fixes #52268

### What issues does this PR fix or reference?
fixes #52268

### Previous Behavior
code tried to get the 'value' attribute twice, resulting in
AttributeError: 'unicode' object has no attribute 'value'

### New Behavior
Just return the already-extracted value

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Review by dwoz — CHANGES_REQUESTED** [review]
@jnielsendotnet Can you please write a test for this change. I'm concerned that this failure happens depending on the version of etc python library installed.

**Comment by jnielsendotnet** [comment]
I don't have the depth or exposure to the code to write a competent test. I'm also fairly certain that my proposed change should have been included as part of 455f40b0d23d955e3ae85776968a5f71ec28815c but sdb was overlooked. Care to comment, @sjmh ?

**Comment by jnielsendotnet** [comment]
Also all the interaction with the etcd python library happens in utils/etcd_util.py and not in the file I'm changing. My change just makes the salt-side code in sdb/etcd_db.py consistent with the EtcdClient class defined in utils/etcd_util.py. The 'get' method hasn't changed since Steve H's refactor of the rest of the etcd code in 455f40b0d23

455f40b0d23 (Steve Hajducko      2015-10-29 22:44:33 -0700 192)         return getattr(result, 'value', None)

**Comment by jnielsendotnet** [comment]
ping @dwoz 
Any response to my prior comments?

**Comment by dwoz** [comment]
@jnielsendotnet Looks like this fell by the wayside. If you still want to move this forward we need to open a PR against the `master` branch.

**Comment by jnielsendotnet** [comment]
I just opened PR https://github.com/saltstack/salt/pull/57482

**Comment by garethgreenaway** [comment]
Closing this in favor of #57482

**Pull request closed without merging**
