### PR TITLE
Fix issue #55149

### PR DESCRIPTION
**Pull request by Akm0d**
### What does this PR do?
Port #55497 to 2019.2.3 for the point release

### CODE REVIEW

**Comment by Akm0d** [comment]
re-run full all

**Comment by Akm0d** [comment]
re-run full debian10

**Comment by Akm0d** [comment]
re-run full centos8

**Comment by Akm0d** [comment]
re-run full macosxmojave

**Comment by Akm0d** [comment]
re-run full macosxmojave

**Comment by Akm0d** [comment]
Weird, the first to times the macosxmojave build ran it skipped installing `pyyaml`

**Comment by Akm0d** [comment]
re-run full centos8

**Comment by Akm0d** [comment]
re-run full debian10

**Review by s0undt3ch — APPROVED** [review]

**Comment by Akm0d** [comment]
re-run full macosxmojave

**Comment by Akm0d** [comment]
re-run full macosxmojave

**Comment by Akm0d** [comment]
re-run full macosxmojave

**Comment by Akm0d** [comment]
re-run full amazon2

**Comment by Akm0d** [comment]
re-run full macosxmojave

**Comment by Akm0d** [comment]
re-run full macosxmojave

**Comment by Akm0d** [comment]
re-run full macosxmojave

**Comment by Akm0d** [comment]
re-run full macosxmojave

**Comment by Akm0d** [comment]
re-run full macosxmojave

**Pull request closed without merging**
