### PR TITLE
Document default permission modes for file module

### PR DESCRIPTION
**Pull request by bobrik**
### What does this PR do?

Documents default permission modes for file module.

### What issues does this PR fix or reference?

* #39482

### CODE REVIEW

**Comment by cachedout** [comment]
Hmm, I wonder if a better and more accurate way to put this would be that the default permissions correspond to the umask of the user under which Salt is running.

**Comment by bobrik** [comment]
Just to confirm, is this what you are proposing?

Instead of this:

* The default mode for files is 0644.

You suggest something like this (I added more details for clarity):

* The default mode for new files corresponds umask of salt process. For existing files it's not enforced.

**Comment by cachedout** [comment]
@bobrik Correct.

**Comment by bobrik** [comment]
Updated. I used the same universal paragraph everywhere to make it easier to find and change.

**Comment by cachedout** [comment]
Thanks, @bobrik !

**Pull request merged**
