### PR TITLE
Fix merge wart

### PR DESCRIPTION
**Pull request by dwoz**
### What does this PR do?

Fix wart in `whitelist.txt`

### Tests written?

No

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by rallytime** [comment]
@dwoz Ah sorry, I mixed this up in my merge-forward. Thanks for fixing this again. :)

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
@dwoz Any idea on why so many of the windows tests are failing on PRs, but not on the branch? I see only 6 tests failing on the Py3 windows tests for 2018.3 branch, for example, but there are 27 on this PR.

I have been seeing more tests fail on PRs than I think are failing on the branches. I just wanted to make sure that was something you're aware of.

**Comment by dwoz** [comment]
@rallytime I'm not sure why there is a difference in the number of failures. So far I've been chalking things like that up to flaky test runs. I've re-launched the windows PR builds to see if the results are consistent.

**Comment by rallytime** [comment]
@dwoz Sounds good. Let's get those flaky tests fixed or marked as such so we can make sure the signaling is as best as it can be, as long as that is on your radar!

**Pull request merged**
