### PR TITLE
[2018.3] Merge forward from 2017.7 to 2018.3

### PR DESCRIPTION
**Pull request by rallytime**
Conflicts:
  - tests/integration/modules/test_state.py
  - tests/unit/templates/test_jinja.py
  - tests/unit/test_minion.py

### CODE REVIEW

**Review by twangboy — APPROVED** [review]
Powershell scripts look good

**Comment by rallytime** [comment]
I will fix the lint on this later today.

**Comment by rallytime** [comment]
re-run py

**Comment by rallytime** [comment]
There is a related test failure I need to look at on this.

**Comment by rallytime** [comment]
re-run py2

**Comment by gtmanfred** [comment]
🎉

**Pull request merged**
