### PR TITLE
Fix netconfig intermittent test bug

### PR DESCRIPTION
**Pull request by darylturner**
### What does this PR do?
revert use of config.merge function when evaluating the 
test flag. There seems to be a possible race conditon   
whereby the flag supplied at the cli is unset and some  
changes are applied regardless of intention.
     
### What issues does this PR fix or reference?
n/a

### Previous Behavior
Test flag supplied at the CLI can become unset and apply changes.

### New Behavior
Revert to pre config.merge behaviour.

### Tests written?
No

### Commits signed with GPG?
No

### CODE REVIEW

**Review by mirceaulinic — APPROVED** [review]

**Comment by mirceaulinic** [comment]
This bug has been introduced with my previous commit https://github.com/saltstack/salt/commit/ad8002810429d5b4e5cd71c3ad9832f600aa451c#diff-c953ac80a03f178ddfa8f5ed289a4747, which has affected every version beginning with 2017.7.6.
I think it would be a good idea to backport @darylturner's commit to the 2018.3 and 2019.2 branches. Thanks!

**Review by dwoz — CHANGES_REQUESTED** [review]
We should have regression test for this bugfix.

**Comment by sagetherage** [comment]
@darylturner please point this to the master branch instead of develop

**Comment by sagetherage** [comment]
@darylturner 
Reviewed in Grooming considering closing

**Comment by sagetherage** [comment]
Reviewed in Grooming this week closing

**Pull request closed without merging**
