### PR TITLE
Initial commit of unit tests for vmware cloud driver

### PR DESCRIPTION
**Pull request by nmadhok**

### CODE REVIEW

**Comment by rallytime** [comment]
@nmadhok Thanks for adding these unit tests! Are all of these PRs the same (this one, #26248, and #26249) but just to different branches? If so, it's better to just made the one change against 2015.5, and then we'll merge the PR forward.

It's fine to keep them open as is right now, so no worries, but I just noticed you've been doing a lot of back-porting and committing to each branch lately. Just don't want to make extra work for you when we already have merge-forward and back-porting processes in place. :)

**Comment by nmadhok** [comment]
@rallytime In this case these 3 branches/PR are the same. The reason I create different PR's for back porting and forward porting is because some of them will cause merge conflicts when forward porting them. I test the code I commit on each branch anyway so creating PR for it isn't a problem for me. It'll just make things easier on your side :)

**Comment by rallytime** [comment]
Ok sounds good. Just making sure :)

**Comment by nmadhok** [comment]
No problem! :)

You can merge these branches for now. I will be working on additional unit tests (There are way too many) and create more PR's for them as we go. Since there are way too many unit tests that will be there, I will create a set of unit tests and create PR for them so we can review them too.

**Comment by rallytime** [comment]
@nmadhok Can you take a look at these test failures? Then I'll be happy to get this merged.

**Comment by nmadhok** [comment]
@rallytime Looks fine. I already back ported the functions it's failing on. This was the reason I created multiple PR's to back port myself :stuck_out_tongue_closed_eyes:

**Comment by rallytime** [comment]
Unfortunately if I run these tests again, it only runs on the code as it was in the pull request - from the time that you made this branch, despite other merges into Salt since this was made. So you're saying this is safe to merge despite these failures? They won't fail on the main branch?

**Comment by nmadhok** [comment]
@rallytime They won't fail on the main branch.

**Pull request merged**
