### PR TITLE
Partially revert 1b84bee06. Fixes #40517

### LINKED ISSUE #40517: Revert loader modules dir sorting
### Description of Issue/Question
Sorting the loader modules dir broke preexisting behavior.
Revert the commit that broke it while maintaining Py3 compat.

Discussion of the issue:
  https://github.com/saltstack/salt/pull/39611#commitcomment-21206405

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
Partially revert 1b84bee06.

### What issues does this PR fix or reference?
#40517

### CODE REVIEW

**Comment by cachedout** [comment]
Per @s0undt3ch this make break a test on Py3.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@s0undt3ch It looks like this broke a Py2 test. Any chance you can look?

**Comment by s0undt3ch** [comment]
@ninja- can you confirm this change fixes the problem reported [here](https://github.com/saltstack/salt/commit/1b84bee06f049aedb27d7076fd2d65fc10ef453b#commitcomment-21206405)

**Comment by cachedout** [comment]
@ninja- Did you see the ping above?

**Comment by ninja-** [comment]
@cachedout sorry. The code looks good and should fix the bug.

**Pull request merged**
