### PR TITLE
Merge forward from 2015.2 to develop

### PR DESCRIPTION
**Pull request by basepi**
Merge forward from 2015.2 to develop

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by thatch45** [comment]
This is a lot of new failures, I assume they are related, I bet it has to do with the major changes in salt-key on develop

**Comment by basepi** [comment]
Interestingly there were no merge conflicts around salt-key code. So I'm not sure how I could have merged forward differently.

**Comment by basepi** [comment]
Someone else is welcome to give the merge forward a try, but I'm afraid we may just have to fix the failures since there wasn't merge conflicts.

**Comment by basepi** [comment]
(I should clarify -- there were a few conflicts but nothing I expect to cause failures of this magnitude.

**Pull request closed without merging**
