### PR TITLE
[master] Make reactor engine less blocking the EventPublisher

### PR DESCRIPTION
**Pull request by vzhestkov**
### What does this PR do?

The `reactor` engine in some cases could cause blocking on reading the events from EventPublisher so it has to hold the events until they will be retrived by the engine.

This change improves the way of handling the events by the `reactor` engine by pushing more work to the thread pool which is already available inside the engine, in this case more work is handled with the distinct thread instead of performing this work with the main thread of the `reactor` engine.

### Previous Behavior
In some cases could cause some growth of the memory consumption with `EventPublisher` as it has to hold the events to be consumed by the stream from `reactor` engine.

### New Behavior
The events from the stream from `EventPublisher` are handled faster.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by whytewolf** [comment]
This change needs tests and a changelog.

**Comment by vzhestkov** [comment]
@whytewolf sorry, I've missed the notification. Not sure about the test is it good enough, but the idea is to move the process to the separate thread as soon as possible.

**Comment by whytewolf** [comment]
@vzhestkov hey there. unfortunately i don't really do much with salt anymore. I left the core team. I am tagging @dwoz in reviewing this.

**Comment by vzhestkov** [comment]
Seems this change has some negative effect in combination with `gitfs`. Closing the PR for now.

**Pull request closed without merging**
