### PR TITLE
fix encoding problem aws responses

### LINKED ISSUE #35088: salt/cloud/ec2.py encoding problems.
### Setup

A node with a tag containing the letter "Ø" crashes the command salt-cloud -m maps/mymap.map
We have a similar setup in development, but in production that letter is here, since it is in the name of the account admin. 
### Steps to Reproduce Issue

Simply create a tag on any node in your setup containing the letter "Æ, Ø or Å" (copy from this text)

The error you se when you run the command with "-l debug" is as follows:

```
[DEBUG   ] Failed to execute 'ec2.list_nodes()' while querying for running nodes: 'ascii' codec can't encode character u'\xd8' in position 165422: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2364, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 3425, in list_nodes
    nodes = list_nodes_full(get_location())
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 3275, in list_nodes_full
    return _list_nodes_full(location)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 3361, in _list_nodes_full
    sigver='4')
  File "/usr/lib/python2.7/dist-packages/salt/utils/aws.py", line 463, in query
    result.text
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd8' in position 165422: ordinal not in range(128)
The following virtual machines are set to be created:
```

The unicode character for xd8 is "Ø". But why is this using ascii encoding and not unicode? Would this not fail if there are tags in German, Icelandic, Russian, Chinese etc..???
### Versions Report

```
Salt Version:
           Salt: 2016.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.5.3
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 3.13.0-74-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

### PR DESCRIPTION
**Pull request by attiasr**
### What does this PR do?
fix encoding problems in aws reponses

### What issues does this PR fix or reference?

fixes #35088

### CODE REVIEW

**Comment by cachedout** [comment]
What if we used `salt.utils.locales.sdecode` here instead of forcing utf-8?

**Comment by s0undt3ch** [comment]
Does AWS send the used encoding in the headers? `sdecode` is probably not the best choice because it tries to use the systems encoding...

**Comment by cachedout** [comment]
@s0undt3ch Right, I know. Headers would be best though, I agree.

**Comment by cachedout** [comment]
@attiasr Did you see the feedback here? Just wanted to check in with you.

**Comment by attiasr** [comment]
@cachedout sure, is using the Requests response encoding is good?

**Comment by cachedout** [comment]
@attiasr I think that's what we have in mind here, yes.

**Pull request merged**
