### PR TITLE
[master] Make Salt Cloud Hetzner module detect image architecture from instanc…

### LINKED ISSUE #65888: [TECH DEBT] Salt-Cloud: Hetzner doesn't support ARM-images
### Description of the tech debt to be addressed, include links and screenshots
Hetzner Cloud now supports ARM64 machines and their respective images, but the salt-cloud hetzner provider is not ready, yet.
Using a ARM64 VM with a generic image name, like `debian-12`, which has an x86 and arm version, yields the following error:

```
[ERROR   ] There was a profile error: image has incompatible architecture
```

It's not possible to define an image ID or the architecture or detect the latter from the VM type, yet:

```
salt-cloud: error: There was a profile error: The server image is not supported
```

### Versions Report

```
Salt Version:
          Salt: 3006.5
 
Python Version:
        Python: 3.10.13 (main, Nov 15 2023, 04:34:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: 0.40.1
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.14.2
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 12 bookworm
        locale: utf-8
       machine: x86_64
       release: 6.1.0-16-amd64
        system: Linux
       version: Debian GNU/Linux 12 bookworm
```

### PR DESCRIPTION
**Pull request by HerHde**
…e type

Previously, creating an arm64 instance failed, because the x86 image was selected by name only

### What does this PR do?
Allow Salt Cloud Hetzner module to create machines with another architecture than x86.

### What issues does this PR fix or reference?
Fixes: #65888

### Previous Behavior
Installing an ARM64 instance like the `cax11` type with failed:

```
[ERROR   ] There was a profile error: image has incompatible architecture
```

The image was selected with the [deprecated `get_by_name()` method](https://hcloud-python.readthedocs.io/en/stable/api.clients.images.html#hcloud.images.client.ImagesClient.get_by_name) which always returns the x86 version.

### New Behavior
Now the [`get_by_name_and_architecture()` method](https://hcloud-python.readthedocs.io/en/stable/api.clients.images.html#hcloud.images.client.ImagesClient.get_by_name_and_architecture) is used and fed with the architecture returned from the server type.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by twangboy — DISMISSED** [review]

**Comment by HerHde** [comment]
Thanks for the approval! How will this be merged?

**Comment by twangboy** [comment]
I just rebased to see if that fixes the failing tests... then we can look at merging.

**Comment by twangboy** [comment]
Looks like the failure may be valid: This is from a Windows machine:
```
tests/pytests/unit/cloud/clouds/test_hetzner.py::test_create - AttributeError: 'ModelMock' object has no attribute 'architecture'
```

**Comment by HerHde** [comment]
Alright, I'll have a look into that. Is there a way to run the tests in my pre-installed Python environment (or without installing multiple)?

**Comment by twangboy** [comment]
Maybe... I run things out of a virtual environment... so my process would be something like this:

```
# On a Windows machine
cd <salt source directory>

# Install the vs build tools (this tasks a while... like 15 minutes or so)
cd pkg\windows
.\install_vs_buildtools.cmd

# Create a virtual environment
python -m venv venv
.\venv\Scripts\activate

# Install nox
pip install nox

# Run the test
nox -e "test-zeromq-3(coverage=False)" -- .\tests\pytests\unit\cloud\clouds\test_hetzner.py::test_create --run-slow --core-tests --run-destructive
```

It takes a minute to run as it builds the testing environments first, then runs the tests... subsequent runs don't take as long... additionally, you can add an environment variable to skip the environment check completely if you've already run it once.

```
$env:SKIP_REQUIREMENTS_INSTALL=1
```

**Comment by HerHde** [comment]
Thanks @twangboy, those instructions helped me out. I should have adapted the tests to mock the new method now, as well as some minor improvements, like checking for expected error messages.

r4r

**Review by twangboy — APPROVED** [review]

**Comment by HerHde** [comment]
Thanks a lot, much appreciated.

**Pull request merged**
