### PR TITLE
Move changelog entries

### PR DESCRIPTION
**Pull request by aplanas**
### What does this PR do?

Move some changelog entries wrongly placed in salt/modules back into the changelog directory

### CODE REVIEW

**Comment by aplanas** [comment]
Please, note that the change should not affect any test as is a documentation patch.

**Comment by aplanas** [comment]
uhm a test case for moving a changelog file?

**Review by waynew — DISMISSED** [review]

**Comment by s0undt3ch** [comment]
The changelog entries are already moved in the master branch(https://github.com/saltstack/salt/pull/58757), we did that before the release.
And now `changelog/` is empty master.

So, this PR is no longer needed?

**Comment by s0undt3ch** [comment]
Also, @aplanas the needs test case label is applied by a script :)

**Comment by aplanas** [comment]
@s0undt3ch indeed! Seems that all was already fixed before. Closing and thanks!

**Comment by s0undt3ch** [comment]
No worries. Thank You.

**Pull request closed without merging**
