### PR TITLE
WIP Test i18n

### PR DESCRIPTION
**Pull request by marbx**
### What does this PR do?
Test the ability to process characters present in non English operating systems vocabulary.
In German, `volume` is `Datenträger`, `executed` is `ausgeführt`

Windows issues are: 
 - ü (Unicode U+00FC) causes UnicodeDecodeError: 'utf8' codec can't decode byte 0xfc
 - ä (Unicode U+00E4) causes UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4

### What issues does this PR  reference?
https://github.com/saltstack/salt/issues/54447
https://github.com/saltstack/salt/issues/50650

### Original test situation this PR automates

`file.line` on a file containing `Datenträger` provokes a UnicodeDecodeError

```
check_i18n_de_volume:
  file.line:
    - name: /somewhere/de_volume.txt
    - content: Datenträger
    - mode: insert
    - location: start
```
Error is

```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 1746, in call
    **cdata['kwargs'])
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1703, in wrapper
    return f(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\states\file.py", line 3191, in line
    backup=backup, quiet=quiet, indent=indent)
  File "C:\salt\bin\lib\site-packages\salt\modules\file.py", line 1737, in line
    body = ''.join([content, body])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 7: ordinal not in range(128)
```

### Probable  causes on Windows
cmd.run sets codepage 437 (for details see issue above)
Salt for reading tries a number of codepages except 437 and finally in 7-bit ascii

### CODE REVIEW

**Comment by waynew** [comment]
Are there other bytes/encodings that we should try, for other languages?

**Comment by markuskramerIgitt** [comment]
I think utf-8 is the dominant encoding for Unicode and Unicode the best way to cover all languages.

**Comment by s0undt3ch** [comment]
What version(s) of python did you test with?

**Comment by markuskramerIgitt** [comment]
2 an 3

**Comment by s0undt3ch** [comment]
And to clarify, on both python versions Salt throws a Unicode error, correct?

**Comment by markuskramerIgitt** [comment]
Yes, we use Python 2 and I tested Python 3. Both Python versions throw UnicodeDecodeError.

**Comment by markuskramerIgitt** [comment]
@waynew , @s0undt3ch 
could you please advise me with the error below?
I tried to add imports, but this does not help and now I'm out of options.


### Error Message
'i18nTestCase' object has no attribute 'run_state'

### Stacktrace
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 1052, in <lambda>
    lambda testcase, *args, **kwargs: self.wrap(testcase, *args, **kwargs)  # pylint: disable=W0108
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 1060, in wrap
    return self.func(testcase, tempdir, *args, **kwargs)
  File "/tmp/kitchen/testing/tests/unit/test_i18n.py", line 30, in test_i18n_characters_with_file_line
    ret = self.run_state('file.line',
AttributeError: 'i18nTestCase' object has no attribute 'run_state'

**Comment by waynew** [comment]
@markuskramerIgitt You'll want to inherit from `ModuleCase` in tests/support/case.py if you want to be running a state - but then this test absolutely doesn't belong in the `unit` tests, since it's making a master/minion round trip.

@s0undt3ch is working on adding support for functional testing, I'm not sure if that's actually available yet, but that would be another alternative here. I know he's pretty busy with the Neon release right now, so he may not be able to respond on this soon, but I've made a note to circle back on this.

**Comment by markuskramerIgitt** [comment]
Thnks, I will try ModuleCase

What do you think of new place integration/client?

**Comment by markuskramerIgitt** [comment]
The last 2 builds (16 and 17) timed out for Windows.

Can we configure the test suite so that it is only build for Windows, not for Unix?

This PR is only for Windows, contains "skipIf(not Windows) " but is build for Unix too.

**Comment by Akm0d** [comment]
> The last 2 builds (16 and 17) timed out for Windows.
> 
> Can we configure the test suite so that it is only build for Windows, not for Unix?
> 
> This PR is only for Windows, contains "skipIf(not Windows) " but is build for Unix too.

The PR is only for windows, but it looks like some of the unix test failures are because of this PR:
`unit.test_module_names.BadTestModuleNamesTestCase.test_module_name_source_match`

```The following 1 test module(s) could not be matched to a source code file:  unit.test_i18n (expected: salt/i18n.py) ```

**Comment by Akm0d** [comment]
Let's move the test file to the integration test folder and add it's path to the `ignore` tuple in `salt.tests.unit.test_module_names.py/test_module_name_source_match`

**Comment by markuskramerIgitt** [comment]
The 4 windows checks have passed: unfortunately, they are false positives.

I [installed the latest minion](https://github.com/saltstack/salt/issues/55179) and created a file called `äü.txt` 

    salt-call --local cmd.run "dir"
    [ERROR   ] Failed to decode stdout from command chcp 437 > nul & dir, non-decodable characters have been replaced

Code page 437 means the minion cannot decode characters above 7-bit ASCII. 

    salt-call --local file.line \tmp\tmp.txt content=äü mode=insert location=start
    [WARNING ] c:\git\salt\salt\utils\platform.py:55: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal

The automated test does not work and should not be merged.

**Comment by waynew** [comment]
@markuskramerIgitt What's the next steps on this PR?

**Comment by twangboy** [comment]
@waynew This PR is pending a fix we're working on for Python 3 unicode support. He submitted the test here.

**Pull request closed without merging**
