### PR TITLE
Virt init disks

### LINKED ISSUE #57005: Create VMs with disks on volume disks
**Is your feature request related to a problem? Please describe.**

When using the `virt.running()` state or the `virt.init()` / `virt.update()` functions to create a VM, the disks are assumed to be files. This is rather file for qcow2 or raw files stored locally or on a mounted share, but this is not enough to use an iSCSI or RBD storage pool for instance.

**Describe the solution you'd like**

A state like the following would create a VM with the `data` disk being on an RBD volume:
```yaml
myvm:
  virt.running:
    - name: mvvm
    - cpu: 1
    - mem: 512
    - disks:
      - name: system
        pool: default 
        image: /var/testsuite-data/disk-image-template.qcow2
        size: 122880
      - name: data
        model: virtio
        format: raw
        pool: test-rbd
        size: 512
```

For this to work, the pool property would have to be an existing libvirt storage pool name. This would not only allow using RBD volumes as disks, but also LVM, disk partitions or iSCSI volumes.

**Describe alternatives you've considered**

Calling `virt.define_xml_str()` with a custom computed XML would do the job, but it's way simpler for users once integrated with the `virt.defined` and `virt.running` states.

### PR DESCRIPTION
**Pull request by cbosdo**
### What does this PR do?

Enables volume support in virt module and states.

### What issues does this PR fix or reference?
Fixes: #57005

### Previous Behavior

`virt.running`, `virt.purge`, etc could only handle file disk images.

### New Behavior

`virt.running`, `virt.purge`, etc can also handle volume disk images. This allows to use RBD, iSCSI, etc volumes in VMs.

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog
- [X] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by cbosdo** [comment]
@DmitryKuzmenko don't spend too much time reviewing that PR for the while: the code is still subject to changes

**Comment by cbosdo** [comment]
@dwoz Don't loose time to blacken this PR for the while: code it still subject to changes: I'll handle the blackening before removing the WIP flag.

**Comment by cbosdo** [comment]
@DmitryKuzmenko This PR is ready for review now

**Comment by twangboy** [comment]
@cbosdo Looks like we got some test failures on Windows

**Comment by cbosdo** [comment]
@twangboy should be fixed with the latest push... sadly `urlparse` is considering the windows path as valid and parses the drive letter as the URL scheme.

**Comment by cbosdo** [comment]
All green now :)

**Review by DmitryKuzmenko — DISMISSED** [review]

**Comment by cbosdo** [comment]
rebased on master

**Review by dwoz — APPROVED** [review]

**Pull request merged**
