### PR TITLE
Get more useful output from stateful commands

### LINKED ISSUE #23709: cmdmod: enhancement is really needed for stateful commands
Consider
```

aaa:
  cmd.run:
    - name: 'echo "there was a big problem";/bin/false'
    - stateful: true

```
This actually results in 
```
local:
----------
          ID: aaa
    Function: cmd.run
        Name: echo "there was a big problem";/bin/false
      Result: False
     Comment: Failed parsing script output! Stdout must be JSON or a line of name=value pairs.
     Started: 15:49:30.257597
    Duration: 5.761 ms
     Changes:

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1

```
Which is a bit awful to track down as the only mean is to parse the minion log, and hope that the log level was enougth

We should really grab back all the output from the commands back to the changes dict, like the regular cmdrun, in case of a false return.

Im going to see if i can implement it.

cc @thatch45

### PR DESCRIPTION
**Pull request by kiorky**
This fixes #23709

Signed-off-by: Mathieu Le Marec - Pasquet kiorky@cryptelium.net

### CODE REVIEW

**Comment by kiorky** [comment]
Im letting the suite failling down (i think to fix all the tests).
Basically it adds only basic stuff to the changes dict, so it must only break those which check full ouputs.

**Comment by kiorky** [comment]
Seems it does not break tests for now, failures are unrelated.

**Comment by kiorky** [comment]
i ve another thing to add, wait for merge

**Comment by kiorky** [comment]
@rallytime no in fact, it is already good, go ahead.

**Comment by rallytime** [comment]
Ah, ok. I was just going off your last comment. Thanks! :)

**Pull request merged**
