### PR TITLE
Execute choot on the correct path

### PR DESCRIPTION
**Pull request by techhat**
Ping @Ch3LL.

### CODE REVIEW

**Comment by techhat** [comment]
Please don't merge yet; we're still checking the validity of removing `-c`.

**Comment by Ch3LL** [comment]
My tests for this PR are passing now. We did end up having to add back the `-c`

**Comment by cachedout** [comment]
@techhat and @Ch3LL  Is this ready to go now?

**Comment by techhat** [comment]
@cachedout ready.

**Pull request merged**
