### PR TITLE
Bugfix: prevent snapper module crash on load if no DBus is available in the system

### PR DESCRIPTION
**Pull request by isbm**
### What does this PR do?

Bugfix
### What issues does this PR fix or reference?

If an OS has no DBus installed but does have python bindings to it installed, then the module crashes, while loading.
### Previous Behavior

`salt.modules.snapper` crashes if no DBus installed.
### New Behavior

`salt.module.snapper` shows the following error in the log instead:

```
[ERROR   ] org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused
```
### Tests written?

No

### CODE REVIEW

**Comment by isbm** [comment]
@meaksh take a look, pls

**Comment by meaksh** [comment]
@isbm Thanks for fixing this! Seems everything is OK :+1:

**Comment by meaksh** [comment]
It would be great to include this before "Carbon" freeze :smile:

**Comment by thatch45** [comment]
@rallytime I highly doubt these test errors are related, can you please confirm?

@isbm does the snapper module as it exists give us what we need to apply snapper snapshots when running states? I am just asking to confirm so I can add that to the state system before the Carbon freeze

**Comment by rallytime** [comment]
@thatch45 They are not related.

**Comment by thatch45** [comment]
Thanks @rallytime !

**Comment by isbm** [comment]
@thatch45 There is also states snapper: https://github.com/saltstack/salt/blob/develop/salt/states/snapper.py

**Comment by thatch45** [comment]
Thanks @isbm , for some reason I was under the impression that I still needed more from your team here before jumping in. The problem I have with trying to juggle 100 things at once!
I think that between the snapper states and the new native support I added that we have covered the complete use case. I am excited to see this in action!

**Pull request merged**
