### PR TITLE
[2019.2.1] newer msgpack ipc fixes

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
Re-submit #52934 fixed after being reverted in #52755

### What issues does this PR fix or reference?
#52934, #52755, #52487

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Only merge after re-running all full tests

**Review by dwoz — APPROVED** [review]

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
This is not the only required change and I can't devote more time to this right now.

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
I think I got it to properly work under Py2 and Py3.

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Review by twangboy — APPROVED** [review]

**Pull request merged**
