### PR TITLE
zeromq dependency: pycrypto --> cryptodome

### PR DESCRIPTION
**Pull request by aphor**
I was unable to pip install pycrypto because of an autoconf error, and found 

This
https://github.com/dlitz/pycrypto/issues/168

which led me to  this
`tl;dr: PyCrypto is dead. Switch to PyCryptodome (GitHub: https://github.com/Legrandin/pycryptodome PyPi: https://pypi.python.org/pypi/pycryptodome). Do not report any new bugs here!`
https://github.com/dlitz/pycrypto/issues/238

Support for salt with pycryptodome in some form has been around since 31c6a10d1b9ce854bb857ca6b0287650093d2f8b

### What does this PR do?

Switches pip dependency from pycrypto (unmaintained) to cryptodome

### What issues does this PR fix or reference?
No known issues yet, maybe this will create some? :)
It's probably worth it.

### Previous Behavior
pip installation of salt would attempt to install pycrypto, which has become orphaned, and subsumed by the drop-in replacement pycryptodome

### New Behavior
pip installation of salt would attempt to install pycryptodome to provide functionality previously provided by pycrypto, as a drop-in replacement.

### Tests written?

No

There is already much code in salt to accommodate pycryptodome.
eg. #41882 #40503

### Commits signed with GPG?

Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by gtmanfred — CHANGES_REQUESTED** [review]
My concern is we still use pycrypto for the distro packages.

I would be ok with switching to pycryptodomex as long as we fully test everything this time.  Because last time this happened there was a bug, that caused problems.

I think @dwoz was the one who went through the pycyrpotdomex and found which version was bad, if we make sure to include that as the minimal version, then I would be ok with this.

This also needs to be updated in the Pipfile as well

**Comment by dwoz** [comment]
@aphor pycrytodome needs to be [>= 3.4.7](https://github.com/saltstack/salt/issues/46868#issuecomment-380610654)

**Comment by gtmanfred** [comment]
Don't worry about the windows builds scripts.

Those are updated at packaging time.

**Comment by gtmanfred** [comment]
Can you also update it here https://github.com/saltstack/salt/blob/develop/Pipfile ?

also @rallytime we should talk about this during planning on Monday

**Comment by gtmanfred** [comment]
@aphor which version of python are you using, and can you provide your exact autoconf error?

**Comment by aphor** [comment]
These errors are just the brittleness of mixing old and new software. Pycrypto was last updated in 2014. I had a 2016 flavor of gcc installed. Its time to move on. I switched my gcc to gcc7 @7.3.0_1 and pycrypto works. The setup.py/configure is broken however in that if it depends on gcc newer than gcc4 @4.9.4, the configure should enforce that check and fail with an appropriate error.

Python version:

    Python Version: 3.6.5 (default, Mar 29 2018, 15:38:43) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]

setup.py build

    running build_ext
    running build_configure
    checking for gcc... gcc
    checking whether the C compiler works... no
    configure: error: in `/Users/aphor/build/python36-salt/foo/pycrypto-2.6.1':
    configure: error: C compiler cannot create executables
    See `config.log' for more details
    Traceback (most recent call last):
      File "setup.py", line 456, in <module>
        core.setup(**kw)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "setup.py", line 251, in run
        self.run_command(cmd_name)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "setup.py", line 278, in run
        raise RuntimeError("autoconf error")
    RuntimeError: autoconf error

config.log excerpt

    ## ----------- ##
    ## Core tests. ##
    ## ----------- ##

    configure:2357: checking for gcc
    configure:2373: found /opt/local/bin/gcc
    configure:2384: result: gcc
    configure:2613: checking for C compiler version
    configure:2622: gcc --version >&5
    gcc (MacPorts gcc49 4.9.4_2) 4.9.4
    Copyright (C) 2015 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    configure:2633: $? = 0
    configure:2622: gcc -v >&5
    Using built-in specs.
    COLLECT_GCC=gcc
    COLLECT_LTO_WRAPPER=/opt/local/libexec/gcc/x86_64-apple-darwin16/4.9.4/lto-wrapper
    Target: x86_64-apple-darwin16
    Configured with: /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_lang_gcc49/gcc49/work/gcc-4.9.4/configure --prefix=/opt/local --build=x86_64-apple-darwin16 --enable-lan
    guages=c,c++,objc,obj-c++,lto,fortran,java --libdir=/opt/local/lib/gcc49 --includedir=/opt/local/include/gcc49 --infodir=/opt/local/share/info --mandir=/opt/local/share/man --datarootdir=/opt/local/
    share/gcc-4.9 --with-local-prefix=/opt/local --with-system-zlib --disable-nls --program-suffix=-mp-4.9 --with-gxx-include-dir=/opt/local/include/gcc49/c++/ --with-gmp=/opt/local --with-mpfr=/opt/loc
    al --with-mpc=/opt/local --with-isl=/opt/local --disable-isl-version-check --with-cloog=/opt/local --disable-cloog-version-check --enable-stage1-checking --disable-multilib --enable-lto --enable-lib
    stdcxx-time --with-build-config=bootstrap-debug --with-as=/opt/local/bin/as --with-ld=/opt/local/bin/ld --with-ar=/opt/local/bin/ar --with-bugurl=https://trac.macports.org/newticket --disable-tls --
    with-pkgversion='MacPorts gcc49 4.9.4_2' --with-build-config=bootstrap-debug
    Thread model: posix
    gcc version 4.9.4 (MacPorts gcc49 4.9.4_2) 
    configure:2633: $? = 0
    configure:2622: gcc -V >&5
    gcc: error: unrecognized command line option '-V'
    gcc: fatal error: no input files
    compilation terminated.
    configure:2633: $? = 1
    configure:2622: gcc -qversion >&5
    gcc: error: unrecognized command line option '-qversion'
    gcc: fatal error: no input files
    compilation terminated.
    configure:2633: $? = 1
    configure:2653: checking whether the C compiler works
    configure:2675: gcc    conftest.c  >&5
    dyld: Library not loaded: /opt/local/lib/libmpfr.4.dylib
      Referenced from: /opt/local/libexec/gcc/x86_64-apple-darwin16/4.9.4/cc1
      Reason: image not found
    gcc: internal compiler error: Abort trap: 6 (program cc1)
    configure: line 2677: 13804 Abort trap: 6           $CC $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5
    configure:2679: $? = 134
    configure:2717: result: no
    configure: failed program was:
    | /* confdefs.h */
    | #define PACKAGE_NAME "FULL-PACKAGE-NAME"
    | #define PACKAGE_TARNAME "full-package-name"
    | #define PACKAGE_VERSION "VERSION"
    | #define PACKAGE_STRING "FULL-PACKAGE-NAME VERSION"
    | #define PACKAGE_BUGREPORT "BUG-REPORT-ADDRESS"
    | #define PACKAGE_URL ""
    | /* end confdefs.h.  */
    | 
    | int
    | main ()
    | {
    | 
    |   ;
    |   return 0;
    | }
    configure:2722: error: in `/Users/aphor/build/python36-salt/foo/pycrypto-2.6.1':
    configure:2724: error: C compiler cannot create executables

**Review by dmurphy18 — COMMENTED** [review]
Not in favor of the removal of pycrypto as a base level for the following reasons:
1. Currently only provide support form SaltStack for pycryptodomex on RHEL7 and RHEL6 in 64-bit mode (RHEL6 in 32bit mode fails to build pycryptodomex owning to assumptions made about supported size - and RHEL6 32bit still needed). Amazon Linux 1 also only uses pycrypto.
2. pycryptodomex is not built by SaltStack for Debian or Ubuntu, even though it is available on Ubuntu 18.04 and later Debian, there is still Debian 8 and Ubuntu 14.04 support to consider (noting stretch-backports, buster and sid)
3. The order of preference is M2crypto, pycryptodomex and at a minimum pycrypto.  With M2Crypto which has recently been revived and includes Python 3 support, is the preferred choice, if SaltStack was to move away from using pycrypto as a minimum, noting that Debian/Ubuntu families need to update to latest versions available.
4. Use of pycryptodomex allows for coexistence with pycrypto, pycryptodome is used to replace use of pycrypto and only pycryptodome is available from Debian.  Therefore pycryptodome would need to be used to replace use of pycrypto on all platforms and not pycryptodomex which is only built by SaltStack for co-existence on RHEL 7 & 6.

However will discuss this internally and give further comments.

**Pull request closed without merging**
