### PR TITLE
Verify installed packages even if source is remote

### PR DESCRIPTION
**Pull request by buchanan**
### What does this PR do?
Verify installed remote packages when pkg_verify=True is set

### Previous Behavior
Packages that contain have sources set would not be verified even when the flag pkg_verify was set.

### New Behavior
Packages using sources will be verified when the flag pkg_verify is set

### Tests written?
No

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by cmcmarrow — APPROVED** [review]

**Review by xeacott — APPROVED** [review]

**Review by cmcmarrow — APPROVED** [review]

**Comment by cmcmarrow** [comment]
@buchanan for your code to be merged ci/lint most be green

**Comment by cmcmarrow** [comment]
For example pylint does not like 'ok' just changine 'ok' to 'okay' will fix that pylint warning.

**Review by cmcmarrow — CHANGES_REQUESTED** [review]
Lint is falling as well

**Comment by sagetherage** [comment]
@buchanan please rebase this against the master branch

**Comment by sagetherage** [comment]
@buchanan please rebase this against the master branch

**Comment by sagetherage** [comment]
Reviewed in Grooming 2021-MAY-03 closing

**Pull request closed without merging**
