### PR TITLE
Virt console

### LINKED ISSUE #58844: Better serials and consoles support in the virt module
The `virt.init()` function has some hidden parameters to generate console devices on the virtual machine. This needs to be exposed publicly and enhanced to support more console and serial device types and configurations.

Similar to what is currently available for disks and network interfaces, creating `serials` and `consoles` parameters allowing multiple device definitions would be more flexible and future proof.

### PR DESCRIPTION
**Pull request by cbosdo**
### What does this PR do?

Adds support for consoles and serials in the `virt.running`, `virt.defined` states and `virt.init()` and `virt.update()` execution modules. Even if some console or serial configurations may not be supported yet, this change keeps the door opened for such improvements.

This PR is an follow up of PR #56430 and supersedes it.

### What issues does this PR fix or reference?

Fixes: #58844 

### Merge requirements satisfied?
- [X] Docs
- [X] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by cbosdo** [comment]
Rebased on master after other virt PR merges. Ready for review again

**Comment by cbosdo** [comment]
@Akm0d would you have some time to look at the PR? Way shorter than the last ones :wink:

**Comment by cbosdo** [comment]
re-run pr-centos7-py3-pycryptodome-pytest

**Comment by cbosdo** [comment]
re-run pr-freebsd122-py3-pytest

**Review by Akm0d — APPROVED** [review]

**Comment by cbosdo** [comment]
@dwoz @sagetherage this PR is ready for merge too, likely to conflict with #58591

**Pull request merged**
