### PR TITLE
Fix flaky mine_tests

### PR DESCRIPTION
**Pull request by dwoz**
### What does this PR do?

Fix mine tests:
```
integration.modules.test_mine.MineTest.test_mine_flush
integration.modules.test_mine.MineTest.test_mine_delete
```

**Wait till these tests pass to mere: https://jenkinsci.saltstack.com/job/2018.3/job/dwoz-fedora28-py2/**

### Tests written?

No - Fix flaky tests

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Updated the PR to resolve the conflict

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by Ch3LL** [comment]
it looks like the tests are still failing. i dove into this a bit and it looks like the mine is event base, so monitoring for running jobs wont catch it each time.

**Comment by Ch3LL** [comment]
i increased the timeout and running the tests here: : https://jenkinsci.saltstack.com/job/2019.2.1/job/ch3ll-mine-salt-fedora-28-py2/1/console to ensure we just are not waiting long enough for the mine to get updated. I also found the `test_get` test was getting skipped each time because it was returning None because it did not have anything in its configuration for the `sub_minion`.

**Comment by s0undt3ch** [comment]
There's also https://github.com/saltstack/salt/commit/8db788b3dd785d90a6a0256f64f5115b77a1ed8b

**Comment by s0undt3ch** [comment]
Pulled in the fixes made in https://github.com/saltstack/salt/pull/52687

**Comment by Ch3LL** [comment]
yay its passing here: https://jenkinsci.saltstack.com/job/2018.3/job/dwoz-fedora28-py2/26/

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
