### PR TITLE
Fix for Issue #46727

### PR DESCRIPTION
**Pull request by colin-stubbs**
### What does this PR do?

Pass headers dict and full_headers bool from module functions to underlying util function which already supports these variables.

### What issues does this PR fix or reference?

Fix for Issue #46727

### Previous Behavior

Custom HTTP headers could not be sent as part of salt.modules.s3 function usage; which is necessary to ensure objects uploaded to S3 have the correct mime type set (e.g. text/html), as well as offering users the ability to set S3 metadata tags.

This is despite the underlying utils/s3.py code supporting custom headers.

### New Behavior

Users can pass a headers dict to all current functions in salt.modules.s3 in order to set custom headers.

Users can set full_headers boolean value to improve debug level output by ensuring unmodified headers are returned by underlying functions.

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Review by cachedout — COMMENTED** [review]
This change seems fine but I think that it should be documented in the release notes before we merge it in.

**Comment by cachedout** [comment]
Hi @colin-stubbs. Did you see the above comment about release notes? Let us know if you have questions. Thanks!

**Comment by colin-stubbs** [comment]
Can do... where exactly do I add release notes though, given there's no draft release???

**Comment by rallytime** [comment]
@colin-stubbs Oh, those would be the Fluorine release notes: https://github.com/saltstack/salt/blob/develop/doc/topics/releases/fluorine.rst

**Comment by cachedout** [comment]
Hi @colin-stubbs. Looks like @rallytime got your questions answered. Could you let me know when we're ready to go here? Thanks!

**Comment by cachedout** [comment]
Hi again @colin-stubbs. Are you able to fix the lint errors and add the requested documentation?

**Comment by rallytime** [comment]
Since we haven't heard back here for a while, I am going to close this. We would be happy to open this again when you're ready. Or you can open a new PR. Whichever is easier for you. :)

Thanks!

**Pull request closed without merging**
