### PR TITLE
make sure to pass arg as well

### PR DESCRIPTION
**Pull request by gtmanfred**
Close the loop on #42548

### CODE REVIEW

**Comment by gtmanfred** [comment]
Go Go Jenkins!

**Review by skizunov — APPROVED** [review]

**Comment by terminalmage** [comment]
This caused https://github.com/saltstack/salt/issues/43077 and has broken calling runners and wheel functions (at least) in 2017.7.1.

**Comment by skizunov** [comment]
If this is reverted, then it will mean that the reactor SLS file that wants to only call a function with `kwarg` values must still always pass an empty `arg` list. I am ok with this behavior as long as it is documented.

**Comment by terminalmage** [comment]
I think that the greater problem here is that we are calling `format_call` in the ReactWrap member function and not the function being wrapped.

**Pull request merged**
