### PR TITLE
Add feature request 51919 (wait for static IP during VM creation in VMware)

### LINKED ISSUE #51919: Feature request: salt-cloud vmware ip handaling
Currently With the current way saltstack handles `wait_for_ip_timeout` the connection it will grab the first IP that is returned by vmware tools and hold onto it for trying to connect. 

However, in mixed environments where DHCP and static IPs are used The first IP might not be the one that salt needs. And DNS might also not cover the host in question. 

What would be good is if there was another option that says if we fail to connect to the first address we got from VMware tools query VMware tools again for the IP. Or an option to only accept the IP if it matches a list/cidr or is in the list of IPs set in the network devices.

### PR DESCRIPTION
**Pull request by alfotos**
Fixes #51919

This change adds the functionality of waiting for predefined static IPs
when deploying a new VM in VMWare. Instead of picking the first available
IP assigned to a VM, it waits for a certain IP to be used in the VM.
This is controlled by the parameter "wait_for_ip_priority".
Old behaviour still remains if parameter is set to "any".

### What does this PR do?
Implement new feature in the VMware cloud module to give the option to wait for a pre-defined static IP when creating a new VM. The new parameter "wait_for_ip_priority" can be set to "any", "dhcp", "static" or "ip" to control the behaviour of the "_wait_for_ip" function.

### What issues does this PR fix or reference?
Fixes #51919

### Previous Behavior
At the moment, the _wait_for_ip uses the first IP configured in the VM during the deployment. This can be an issue if you are deploying a VM in a DHCP-enabled subnet but you want to use a given static IP. This can lead to a timeout later, as Salt will try to connect to an IP which was only used fore few seconds (time between the DHCP IP and the static IP configured by VMware tools). More details are explained in the issue #51919

### New Behavior
The current behaviour is maintained by default, or by setting the "wait_for_ip_priority" to "dhcp" or "any". On the other hand, if you have a static IP and want to be sure that one is used the parameter can be set to "static", this will filter the registered IP and will only accept one of the IPs defined in the network devices. The specific use case of this is "ip", when you also have to use the parameter "wait_for_ip_address".

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/latest/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by Ch3LL** [comment]
looks like there is some lint failures here. Can you also write a regression test for this?

**Comment by DmitryKuzmenko** [comment]
@alfotos could you please follow this up?

**Review by Ch3LL — CHANGES_REQUESTED** [review]
bump for the requests in this comment https://github.com/saltstack/salt/pull/56701#issuecomment-622402984

**Comment by Ch3LL** [comment]
@alfotos any updates here?

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
