### PR TITLE
[cloud:EC2] Move SourceDest logic to _update_enis and add  alias for delete_interface_on_terminate

### PR DESCRIPTION
**Pull request by ruzarowski**
- SourceDest Flag is now also honored, when we attach an existing interface (_update_enis is a post-flight update)
- delete_interface_on_terminate is DeleteOnTermination at the EC2 Api, this alias makes it possible to keep the config consistent with api parameter

### CODE REVIEW

**Comment by jfindlay** [comment]
@ruzarowski, there is a [lint error](https://jenkins.saltstack.com/job/salt-pr-lint-n/7267/violations/file/salt/cloud/clouds/ec2.py/).
```python
def _modify_eni_properties(eni_id, properties=None):
...
    if properties == None:
        properties = {}
```

**Comment by ruzarowski** [comment]
Done.

**Comment by jfindlay** [comment]
@ruzarowski, one more https://jenkins.saltstack.com/job/salt-pr-lint-n/7274/violations/file/salt/cloud/clouds/ec2.py/

**Comment by ruzarowski** [comment]
My bad, the quickfix was a little too quick, CopyPastie fixed.

**Comment by jfindlay** [comment]
Thanks, @ruzarowski.  You can also use `if not isinstance(properties, dict)`.

**Comment by rallytime** [comment]
@ruzarowski It looks like this pull request needs to be rebased with 2015.8, now that I have merged some of your other PRs.

**Comment by ruzarowski** [comment]
Should work now. Let's wait for Jenkins' final call though.

**Comment by cachedout** [comment]
This rebase doesn't look right. I assume only the cloud changes are yours?

**Comment by ruzarowski** [comment]
Sorry, i forgot merge after rebase. Now it looks as it should.

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
This has a couple of cases where `type()` should be `isinstance()` but I will go ahead and merge this and then change those, since @rallytime has reviewed the rest. Thanks for your hard work here, @ruzarowski

**Pull request merged**
