### PR TITLE
Fix user.present detecting primary group being moved to "groups" arg

### LINKED ISSUE #56061: user.present fails to both change primary group, and set old primary group as an additional group in same run
### Description of Issue

When you change the default group of a user, but put their old default group into the `groups` list, the `_changes()` helper function in salt/states/user.py that determines what needs to be modified does not catch that the user's old default group will need to be added back. Because of this, that change is not made, causing the state to fail reporting that it couldn't properly set the groups. It must then be run a second time to add that group for the user.

### Setup

I've put this into a Docker container for easy inspection and reproducibility. Run these Docker commands from the root of a git checkout of Salt.

**NOTE: I've edited out a traceback that currently appears when you run this from the head of the master branch. I've reported that separately [here](https://github.com/saltstack/salt/issues/56063).**

```
% docker run --rm -it -v $PWD:/testing terminalmage/issues:56061 tail -n2 /etc/group
oldprimary:x:223344:
foo:x:112233:
% docker run --rm -it -v $PWD:/testing terminalmage/issues:56061 tail -n1 /etc/passwd
foo:x:112233:223344::/home/foo:/bin/bash
% docker run --rm -it -v $PWD:/testing terminalmage/issues:56061 cat /srv/salt/users.sls
foo:
  user.present:
    - uid: 112233
    - gid: 112233
    - allow_gid_change: True
    - groups:
      - oldprimary
```

### Steps to Reproduce Issue

```
% docker run --rm -it -v $PWD:/testing terminalmage/issues:56061 salt-call state.apply
[ERROR   ] {u'gid': 112233, u'groups': ['foo']}
local:
----------
          ID: foo
    Function: user.present
      Result: False
     Comment: These values could not be changed: {u'groups': [u'oldprimary']}
     Started: 22:46:26.497176
    Duration: 1441.022 ms
     Changes:
              ----------
              gid:
                  112233
              groups:
                  - foo

Summary for local
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time:   1.441 s
```

### Versions Report

```
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.3.0
       dateutil: 2.8.0
      docker-py: 3.7.2
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.10.1
        libgit2: 0.28.2
       M2Crypto: Not Installed
           Mako: 1.1.0
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.8.1
   pycryptodome: Not Installed
         pygit2: 0.28.2
         Python: 2.7.5 (default, Jun 20 2019, 20:27:34)
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 5.4.15-arch1-1
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

### PR DESCRIPTION
**Pull request by terminalmage**
### What does this PR do?

Fixes #56061 

### Previous Behavior

```
% docker run --rm -it -v $PWD:/testing terminalmage/issues:56061 salt-call state.apply
[ERROR   ] {u'gid': 112233, u'groups': ['foo']}
local:
----------
          ID: foo
    Function: user.present
      Result: False
     Comment: These values could not be changed: {u'groups': [u'oldprimary']}
     Started: 22:46:26.497176
    Duration: 1441.022 ms
     Changes:
              ----------
              gid:
                  112233
              groups:
                  - foo

Summary for local
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time:   1.441 s
```

### New Behavior

```
% docker run --rm -it -v $PWD:/testing terminalmage/issues:56061 salt-call state.apply
local:
----------
          ID: foo
    Function: user.present
      Result: True
     Comment: Updated user foo
     Started: 22:47:28.045623
    Duration: 2113.802 ms
     Changes:
              ----------
              gid:
                  112233
              groups:
                  - foo
                  - oldprimary

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   2.114 s
```

### Tests written?

Yes, and affected unit tests also updated to reflect change in `salt/states/user.py`.

### Commits signed with GPG?

No

### CODE REVIEW

**Review by waynew — DISMISSED** [review]

**Comment by terminalmage** [comment]
Windows integration tests for user states are failing, and the console does not provide debug logging. I don't have a Windows box available for testing. Can I get an assist from @saltstack/team-core ?

**Comment by terminalmage** [comment]
Any chance of getting some help here?

**Comment by DmitryKuzmenko** [comment]
@terminalmage thank you for updating the code. Black and isort are glad now.
Could you please address the tests failures? They look related.

**Comment by terminalmage** [comment]
@DmitryKuzmenko I've asked for help twice now on the Windows tests. I don't have a way of addressing them. At the time they were all that were failing. Now, MacOS is also failing, and I don't have a way of testing that either.

I can't reproduce the failures on Ubuntu.

**Comment by terminalmage** [comment]
It turns out that the failures I couldn't reproduce were happening due to dictionary iteration order. I don't know why I couldn't reproduce it at the time, because I can now. Perhaps I mistakenly tested on Python 2 instead of 3.

Because the functions that are run to make user changes are done by iterating over a dictionary, depending on platform the groups might be changed before the gid is modified. When this happens, the test fails, and rightly so as the groups were not properly being set.

I've changed how changes are applied so that they now happen in a predictable order, and since doing so have not been able to make any of the platforms I've tested fail. I've just pushed these changes and this should take care of these test failures.

I also fixed it so that `iteritems` is not imported out of six into the module, causing it to be added to the Sphinx docs. :man_facepalming:

**Review by dwoz — APPROVED** [review]

**Pull request merged**
