### PR TITLE
add some more python libs '--versions-report' into output

### PR DESCRIPTION
**Pull request by TheBigBear**

### CODE REVIEW

**Comment by basepi** [comment]
@TheBigBear looks like this needs to be rebased, it's not merging cleanly.

**Comment by TheBigBear** [comment]
Hi @basepi sorry, I still don't quite get my head around git rebase, ;-( 

so I tried making another commit direclty on my  ```TheBigBear/thebigbear_add-to-versions-report_2015.8``` branch and hoping this woudl do the trick, and I can see this new second commit in this PR. But apparently that is not good enough?
 
The merge conflict was the line adding the ``dateutil``` info in, when it was already there. 
Not sure how to fix this, now.

**Comment by basepi** [comment]
Try this:

```
git remote add upstream git://github.com/saltstack/salt
git fetch upstream
git rebase upstream/2015.8
```

Theoretically that should reset your branch to upstream/2015.8 and then put your two commits on top. You'll probably have to resolve a conflict as part of it, just follow the instructions that the rebase gives you.

**Comment by TheBigBear** [comment]
@basepi, help! I thought I did as asked. but my simple one file comit has now seemingly become a case of 13 commits inot 7 files? Maybe I need to close this off. and start again with a clean slate?

**Comment by TheBigBear** [comment]
@basepi I am scared by this rebsse result. So I will close this and start again, with a clean slate from an up to date repo and a clean 2015.8 branch. Sorry, but this small change is not worth your time, trying to teach me git foo from remote. Thanks for your help.
You said I should add a 'upstream' I already had a 'upstream' defined pointing to my own TheBigBear salt repo. So I thought I could substitue the rebase upstream with a rebase origin, but that rebased my work on top of all the other comits that happened in between and I just don't like the way the results look, so I am bailing out. 
I have now read up on git rebase and understand the concept (I think) , but this one I want to abandon and do fresh. Call me a chicken, but sorry I am out. ;-)

**Comment by basepi** [comment]
Totally fine. The weird rebase results were probably the result of a merge commit or a non-clean local 2015.8 branch.

Whenever I create a working branch I do it from an upstream branch.

```
git fetch upstream
git branch upstream/2015.8 my_bugfix_branch
git checkout my_bugfix_branch
```

If you do it this way, you'll always know you have a completely clean branch going in.

**Pull request closed without merging**
