### PR TITLE
fixed incorrect git function variable

### PR DESCRIPTION
**Pull request by alan-cugler**
### What does this PR do?
Made the optional argument `target` a required positional arguement for three git functions.

### What issues does this PR fix or reference?
#52364 

### Tests taken
Tested each function without `target` set, all three failed with error: target required.

### Previous Behavior
Docs said you could leave target to default `None,` but @garethgreenaway tested and found this is incorrect, a Target is required.

### New Behavior
Docs function 

### Commits signed with GPG?
Yes

### CODE REVIEW

**Review by dwoz — CHANGES_REQUESTED** [review]
@alan-cugler Thanks for your contribution. Please include a regression test with this.

**Comment by alan-cugler** [comment]
@dwoz, I took one look at the related docs and the existing git module tests and realized this is something that would take a week or two for me to familiarize myself with. I've never worked with it before and the imported mock library isnt intuitive.

I advise accepting this PR now, and then we can make a separate issue and PR for the unit testing. I know the changes are valid from manual testing befoer and after the changes.

**Comment by waynew** [comment]
We could always correct the documentation, as that doesn't require tests. Then we can update this PR with some tests.

**Comment by alan-cugler** [comment]
I'm fine with that @waynew, I am currently to busy to be pushing PR's, I am mostly just trying to track any issues I come across in Saltstack docs or open-salt bugs while working. I hope to devote more time towards this in the coming months.

**Comment by twangboy** [comment]
Please rebase this against the master branch

**Comment by twangboy** [comment]
Closed in favor of https://github.com/saltstack/salt/pull/56375

**Pull request closed without merging**
