### PR TITLE
Fix bug #56238: AttributeError in salt.modules.virtualenv_mod

### PR DESCRIPTION
**Pull request by shivamMg**
### What does this PR do?
virtualenv>=20.0.0 removes support for legacy `virtualenv_version` attribute, which is resulting in AttributeError while using `salt.modules.virtualenv_mod`. This PR fixes it.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/56238 

### Previous Behavior
`salt.modules.virtualenv_mod` fails with virtualenv>=20.0.0.

### New Behavior
`salt.modules.virtualenv_mod` should work with virtualenv>=20.0.0.

### Tests written?

Yes

### Commits signed with GPG?

No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by shivamMg** [comment]
I'm not sure why `ci/lint` failed. Can anyone help me with that.

**Review by twangboy — DISMISSED** [review]

**Comment by frogunder** [comment]
@shivamMg Seems like there are some test failures here, you mind taking a look?

Thanks.

**Comment by shivamMg** [comment]
will do

**Review by cmcmarrow — DISMISSED** [review]

**Comment by frogunder** [comment]
@shivamMg Seems like the fix for this already is present in master branch.
https://github.com/saltstack/salt/blob/master/salt/modules/virtualenv_mod.py#L55

**Comment by shivamMg** [comment]
@frogunder yes. i guess this can be closed then.

**Pull request closed without merging**
