### PR TITLE
pillar_stack: add *fetch* method as an alias to salt.utils.data.traverse_dict_and_list

### PR DESCRIPTION
**Pull request by n-rodriguez**
### What does this PR do?

Add *fetch* method as an alias to salt.utils.data.traverse_dict_and_list in pillar stack.

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by n-rodriguez** [comment]
This simple addition allows to easily fetch pillars in pillar stack :

```jinja
{% set foo = fetch(stack, 'foo:bar:baz', []) %}
{% set bar = fetch(pillar, 'bar:bar:baz', {}) %}
{% set baz = fetch(__grains__, 'baz:bar:baz', false) %}
```

**Comment by n-rodriguez** [comment]
ping @dwoz

**Comment by n-rodriguez** [comment]
hi there! any news?

**Comment by waynew** [comment]
Hi @n-rodriguez thanks for the PR! We like this feature, but we would also like a test or two, just something that ensures that the filter is present in the jinja environment. I was looking around, I'm not sure but I *think* that `tests/support/jinja_filters.py` would be the appropriate place to add a test for that. @garethgreenaway or @dwoz - do either of you have any other recommendations?

**Comment by n-rodriguez** [comment]
@waynew thank for your reply! actually I was thinking about another approach/naming to match with the existing [`traverse`](https://docs.saltstack.com/en/latest/topics/jinja/index.html#traverse)

**Comment by n-rodriguez** [comment]
>  I was looking around, I'm not sure but I _think_ that `tests/support/jinja_filters.py` would be the appropriate place to add a test for that. @garethgreenaway or @dwoz - do either of you have any other recommendations?

Hi there any news?

**Pull request closed without merging**
