### PR TITLE
Proposed feature implementation for #31661

### PR DESCRIPTION
**Pull request by dkiser**
### What does this PR do?

Allows configurable regex filters to redact output from `iptables-save` commands in the `iptables.save` function of the `iptables` execution module.
### What issues does this PR fix or reference?

 Proposed implementation for #31661
### Previous Behavior

`iptables-save` saves all rules and tables to persistent file.
### New Behavior

`iptables-save` output is can now optionally be redacted before saved to persistent file.
### Tests written?
- [ ] Yes
- [X] No

Feature: allow configurable regex filters to redact iptabes-save output

### CODE REVIEW

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@dkiser Could you please have a look at these lint errors and push up some fixes? Thanks.

https://jenkins.saltstack.com/job/salt-pr-lint-n/13995/violations/file/salt/modules/iptables.py/

**Comment by dkiser** [comment]
@cachedout - sure, when I get a free moment.  Maybe be a day or two.

**Comment by cachedout** [comment]
@dkiser Sounds good. Let me know when you get a chance. Thanks.

**Comment by dkiser** [comment]
@cachedout  lint fixes pushed

**Comment by rallytime** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
@dkiser It looks like this change is causing one of the iptables tests to fail. Can you take a look? https://jenkins.saltstack.com/job/salt-pr-rs-cent7-n/13204/

Let us know if you need any help!

**Comment by dkiser** [comment]
@rallytime was that error due to `__context__` not being available during the test run?

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by dkiser** [comment]
@cachedout have any insight to my previous comment in the thread?  I haven't had time to look into it myself yet.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
@dkiser Looks like we purged the results of the test run. I will look at it after this run finishes.

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by cachedout** [comment]
Go Go Jenkins!

**Comment by dkiser** [comment]
@cachedout - lol so where we at on this one?

**Comment by cachedout** [comment]
Go Go Jenkins!

**Pull request merged**
