### PR TITLE
IPv6AddressScoped: define self._scope_id for python3.9+ compatibility

### PR DESCRIPTION
**Pull request by fepitre**
### What does this PR do?

Define `_scope_id` for `IPv6AddressScoped` for python3.9+ compatibility

### What issues does this PR fix or reference?
Fixes:

```
Example of trace:

          Traceback (most recent call last):
            File "/var/tmp/.root_dd8a91_salt/salt-call", line 27, in <module>
              salt_call()
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/scripts.py", line 472, in salt_call
              client.run()
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/cli/call.py", line 48, in run
              caller = salt.cli.caller.Caller.factory(self.config)
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/cli/caller.py", line 64, in factory
              return ZeroMQCaller(opts, **kwargs)
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/cli/caller.py", line 329, in __init__
              super(ZeroMQCaller, self).__init__(opts)
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/cli/caller.py", line 89, in __init__
              self.minion = salt.minion.SMinion(opts)
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/minion.py", line 912, in __init__
              opts["grains"] = salt.loader.grains(opts)
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/loader.py", line 825, in grains
              ret = funcs[key]()
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/grains/core.py", line 2369, in ip_fqdn
              ret["ipv6"] = salt.utils.network.ip_addrs6(include_loopback=True)
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/utils/network.py", line 1353, in ip_addrs6
              return _ip_addrs(interface, include_loopback, interface_data, "inet6")
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/utils/network.py", line 1333, in _ip_addrs
              ret.add(addr)
            File "/usr/lib64/python3.9/ipaddress.py", line 1920, in __hash__
              return hash((self._ip, self._scope_id))
          AttributeError: _scope_id
```

See: https://github.com/saltstack/salt/issues/57456#issuecomment-692842325

### CODE REVIEW

**Comment by Akm0d** [comment]
@fepitre thank you for the PR! The file you changed has some unrelated pre-commit  errors that need to be fixed before we can merge

**Comment by fepitre** [comment]
> @fepitre thank you for the PR! The file you changed has some unrelated pre-commit errors that need to be fixed before we can merge

Sure. Don't hesitate to ask if I can help in something.

**Comment by Akm0d** [comment]
@fepitre  Run `pre-commit run -av` on your local branch and add that to the PR

**Comment by s0undt3ch** [comment]
Whoa! 6.5k changed files?
A rebase gone bad?

**Comment by fepitre** [comment]
> Whoa! 6.5k changed files?
> A rebase gone bad?

I don't know the tool but if it's only a matter of rebasing my commit, I can simply do it then rerun the requested command?

**Comment by bryceml** [comment]
It should have been `pre-commit run --files salt/_compat.py`  I'm running that now and can update your pr.

**Review by s0undt3ch — APPROVED** [review]

**Review by dwoz — CHANGES_REQUESTED** [review]
Test case?

**Pull request closed without merging**
