### PR TITLE
Add proxmox api introspection

### PR DESCRIPTION
**Pull request by hobgoblinsmaster**
### What does this PR do?
This PR allow to get properties from proxmox API documentation installed on requested node. This then allow to set all possible parameters in cloud.profile.

### Previous Behavior
From a profile as:

```yaml
proxmox-std-linux:
  provider: proxmox-pve1-config
  technology: qemu
  image: local:iso/debian-8.4.0-amd64-netinst.iso
  host: pve1
  balloon: 1024
  boot: ncd
  bootdisk: scsi0
  cores: 2
  description: Serveur Linux standard
  ide2: local:iso/debian-8.4.0-amd64-netinst.iso,media=cdrom
  memory: 2048
  name: tmpl-linux
  net0: virtio,bridge=vmbr0,tag=1
  numa: 0
  onboot: 1
  ostype: l26
  scsi0: local-zfs:32,format=raw,cache=writeback,discard=on,size=32G
  scsihw: virtio-scsi-pci
  sockets: 1
  vga: qxl
  size: ''
```

The created VM (as salt-cloud -F) as this parameters

```
VM 103:
            ----------
            config:
                ----------
                cores:
                    2
                description:
                    Serveur Linux standard
                digest:
                    050c9293f3f2d362ff6a0037348647a8d85fec8f
                ide2:
                    local:iso/debian-8.4.0-amd64-netinst.iso,media=cdrom
                memory:
                    2048
                net0:
                    virtio=2E:09:00:A4:2F:F9,bridge=vmbr0,tag=1
                onboot:
                    1
                ostype:
                    l26
                smbios1:
                    uuid=b2be002b-7d08-4afd-980f-a5e744c701f5
            cpu:
                0
            disk:
                0
            diskread:
                0
            diskwrite:
                0
            id:
                qemu/103
            maxcpu:
                2
            maxdisk:
                0
            maxmem:
                2147483648
            mem:
                0
            name:
                VM 103
            netin:
                0
            netout:
                0
            node:
                pve1
            status:
                stopped
            template:
                0
            type:
                qemu
            uptime:
                0
            vmid:
                103
```

### New Behavior
With th same profile, created VM is:

```
test-proxmox-api:
            ----------
            config:
                ----------
                balloon:
                    1024
                boot:
                    ncd
                bootdisk:
                    scsi0
                cores:
                    2
                description:
                    Serveur Linux standard
                digest:
                    9573464fcbb425477fa9888b2c4fa12620d7d5d4
                ide2:
                    local:iso/debian-8.4.0-amd64-netinst.iso,media=cdrom
                memory:
                    2048
                name:
                    test-proxmox-api
                net0:
                    virtio=5A:E7:92:97:D8:9C,bridge=vmbr0,tag=1
                numa:
                    0
                onboot:
                    1
                ostype:
                    l26
                scsi0:
                    local-zfs:vm-102-disk-1,cache=writeback,discard=on,size=32G
                scsihw:
                    virtio-scsi-pci
                smbios1:
                    uuid=e21059c4-dadd-4a0f-9018-573ea76b25a9
                sockets:
                    1
                vga:
                    qxl
            cpu:
                0
            disk:
                0
            diskread:
                0
            diskwrite:
                0
            id:
                qemu/102
            maxcpu:
                2
            maxdisk:
                34359738368
            maxmem:
                2147483648
            mem:
                0
            name:
                test-proxmox-api
            netin:
                0
            netout:
                0
            node:
                pve1
            status:
                stopped
            template:
                0
            type:
                qemu
            uptime:
                0
            vmid:
                102
```

### Tests written?
No

### CODE REVIEW

**Review by cachedout — CHANGES_REQUESTED** [review]
There are some lint errors which need to be fixed up before we can merge this. They are here: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/9482/violations/file/salt/cloud/clouds/proxmox.py/

**Comment by hobgoblinsmaster** [comment]
Fixed errors on lines 674 and 733.
For the warning on line 49, I didn't touch this part and don't know how to fix it beiing sur it won't introduce unwanted changes.

Believe I did something bad when updating my PR, it seams now mixed with all merged code since yesterday. If needed, feel free to close it, I can start a fresh one.

**Comment by cachedout** [comment]
@hobgoblinsmaster Yes it looks like something got messed up here. You can either rebase this against develop or close this PR and open a new one. Whichever is easiest for you is fine. Thanks.

**Comment by hobgoblinsmaster** [comment]
Revorked in https://github.com/saltstack/salt/pull/40116

**Pull request closed without merging**
