### PR TITLE
adding states/postgres_schema unit test case.

### PR DESCRIPTION
**Pull request by jayeshka**
Implemented states/postgres_schema_test unit test case.

### CODE REVIEW

**Comment by jfindlay** [comment]
@jayeshka, there are some [test failures](https://jenkins.saltstack.com/job/salt-pr-rs-ubuntu14.04-n/5772/).

**Comment by jayeshka** [comment]
@jfindlay These failures are same as of #24330.
Running at my end on updated branch.

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
Go Go Jenkins!

**Pull request merged**
