### PR TITLE
inspectlib cleanup

### PR DESCRIPTION
**Pull request by isbm**
### What does this PR do?
1. Cleans up the `salt.modules.inspectlib`.
2. Integrates new [Kiwi](https://github.com/suse/kiwi) (export only)
### Previous Behavior

Minion needed always to be extra-configured in order `inspectlib` started.
### New Behavior

No more need to configure minion for `inspectlib` function.
### Tests written?

Yes

### CODE REVIEW

**Comment by thatch45** [comment]
While this is on 2016.3 it is isolated to the inspectlib system and adds more tests, so I will permit it

**Comment by isbm** [comment]
@cachedout @thatch45 @rallytime Will this go at some point "automagically" to the `develop` or I should open another PR?

**Comment by rallytime** [comment]
@isbm It will be merged-forward to develop in the next day or two. :)

**Comment by thatch45** [comment]
https://docs.saltstack.com/en/latest/topics/development/contributing.html#the-current-release-branch

**Pull request merged**
