### PR TITLE
[2018.3] Fixes sphynx syntax #51477

### LINKED ISSUE #51477: Vault module missing some examples from documentation
### Description of Issue/Question
On the [documentation for the Vault module](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.vault.html), under `configuration:auth:`,

```
auth

    Currently only token auth is supported. The token must be able to create tokens with the policies that should be assigned to minions. Required.

    You can still use the token via a OS environment variable via this config example:
    <MISSING EXAMPLE>

    And then export the VAULT_TOKEN variable in your OS:
    <MISSING EXAMPLE>
```

### PR DESCRIPTION
**Pull request by johnnybubonic**
The documentation on the website wasn't rendering the examples for
the 'auth' section due to single colons instead of double.

### What does this PR do?
Should allow the examples for auth section to render properly on docs.saltstack.com.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt/issues/51477

### Tests written?

No (doc fix)

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by dwoz** [comment]
@johnnybubonic The docs build failed, please take a look and thanks for the contribution.

**Comment by johnnybubonic** [comment]
@dwoz i think it's because i missed a newline after line 65. any chance you can fix it or should i close this out and just resubmit?

**Comment by Akm0d** [comment]
re-run docs

**Comment by bryceml** [comment]
Having an unknown repository as a source breaks jenkins. If you would like this PR to make it in, please re-submit and link to the original.

**Pull request closed without merging**
