### PR TITLE
Add note about new flatpak module

### PR DESCRIPTION
**Pull request by steveno**
### What does this PR do?
Add new flatpak module to Neon release notes.

### What issues does this PR fix or reference?
N/A

### Tests written?

N/A

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by steveno** [comment]
@rallytime This is ready for review.

I know all the tests are failing, but I don't know how. I didn't change any code :(

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
Yeah, those failures aren't related to your change.

**Comment by steveno** [comment]
@rallytime Can this be added to the Neon branch? I don't want to miss this being in the release notes.

**Comment by steveno** [comment]
@rallytime or @Ch3LL I don't want to be a nuisance, but this needs the Neon label.

**Review by Akm0d — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Comment by sagetherage** [comment]
https://github.com/saltstack/salt/pull/58068

**Pull request merged**
