### PR TITLE
Simple patch for #41971

### PR DESCRIPTION
**Pull request by fake-name**
### What does this PR do?

Fixes what I think is a typo in some of the salt-cloud refactoring.

### What issues does this PR fix or reference?

https://github.com/saltstack/salt/issues/41971

### Tests written?

No, but there weren't any tests beforehand, or it wouldn't have been broken by someone's refactoring, so not much has changed here /snark.

### CODE REVIEW

**Comment by fake-name** [comment]
Ok, I don't think this actually fixed the issue, as it no longer crashes, but it also no longer can even create a VPS at all (at least for digital ocean).

Arrrrgh.

**Comment by cachedout** [comment]
@techhat or @rallytime can one of you jump in here?

**Comment by techhat** [comment]
@rallytime will have to confirm, but this looks correct.

**Comment by gtmanfred** [comment]
Looks like it should be changed, it is already changed at the top of `create()`

https://github.com/saltstack/salt/blob/develop/salt/cloud/__init__.py#L1182

**Comment by rallytime** [comment]
I am looking at the accompanying issue now, but I don't think this is the right fix as it stands, as it will break situations as described in [this comment](https://github.com/saltstack/salt/pull/38166#issuecomment-266157498).

**Comment by rallytime** [comment]
Since this PR will cause regressions when using salt-cloud profiles (instead of the salt.cloud.CloudClient.create() function), I am going to close this. This is replaced by #42034. Thanks again for bringing this to our attention @fake-name.

**Pull request closed without merging**
