### PR TITLE
The SSH API supports multiple IPs

### PR DESCRIPTION
**Pull request by frieda1220**
### What issues does this PR fix or reference?
Fixes:

### Previous Behavior
Remove this section if not relevant

### New Behavior
Remove this section if not relevant

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes/No

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by DmitryKuzmenko** [comment]
Thank you for contribution!
This PR is duplicate of #57799. Could you please review it and provide your opinion?

**Comment by frieda1220** [comment]
We do the same thing, I have less code.

**Comment by DmitryKuzmenko** [comment]
@frieda1220 Yep, thank you for pointing this out, I've found that putting all the code inside the loop for `target` list is redundant. I've updated my code. So now it contains your good approach.

**Comment by Ch3LL** [comment]
closing as a duplicate of #57799

**Pull request closed without merging**
