### PR TITLE
revert dict comprehension back to loop for py-2.6

### PR DESCRIPTION
**Pull request by jfindlay**

### CODE REVIEW

**Comment by thatch45** [comment]
Did this get past lint?

**Comment by s0undt3ch** [comment]
We don't have a py26 code checker...
And the current pylint is running under py27.

**Comment by thatch45** [comment]
Ahh, we used to check on 2.6, this could bite us....

**Comment by s0undt3ch** [comment]
In thinking on a common py26 pitfalls pylint plugin...

**Comment by s0undt3ch** [comment]
https://github.com/ghewgill/pyqver/blob/master/pyqver2.py might help

**Pull request merged**
