### PR TITLE
Python 3 compatability refactor

### PR DESCRIPTION
**Pull request by ckochenower**
sorting using a 'cmp' is no longer supported in Py3.
'key' works in both Py2 and Py3. 'cmp' has been removed in Py3.
String and binary data are treated differently in Py3.

The following script proves that the new `key` implementation is a functional equivalent to the `cmp` implementation.

To run the "SCRIPT" at the end of this comment in Python 2 and 3, do the following:
1. Copy the script to <filename>.
2. Run the script with Python 2 ...
    <pre>
    python &lt;filename&gt;
    </pre>
3. Note that both cmp and key implementations produce identical results.
4. Replace ...
    <pre>
        if how_to_sort == 'cmp':
            return sorted(hostname_list, cmp=_cmp_hostname)
        else:
            return sorted(hostname_list, key=_key_hostname)
    </pre>
    ... with ...
    <pre>
        return sorted(hostname_list, key=_key_hostname)
    </pre>
    ... and re-run the script using python3...
    <pre>
    python3 <filename>
    </pre>

SCRIPT:

<pre>
def _sort_hostnames(hostname_list, how_to_sort):
    '''
    sort minion ids favoring in order of:
        - FQDN
        - public ipaddress
        - localhost alias
        - private ipaddress
    '''
    # punish matches in order of preference
    punish = [
        'localhost.localdomain',
        'localhost.my.domain',
        'localhost4.localdomain4',
        'localhost',
        'ip6-localhost',
        'ip6-loopback',
        'ipv6-localhost',
        'ipv6-loopback',
        '127.0.2.1',
        '127.0.1.1',
        '127.0.0.1',
        '0.0.0.0',
        '::1',
        'fe00::',
        'fe02::',
    ]

    def _cmp_hostname(a, b):
        # should never have a space in hostname
        if ' ' in a:
            return 1
        if ' ' in b:
            return -1

        # punish localhost list
        if a in punish:
            if b in punish:
                return punish.index(a) - punish.index(b)
            return 1
        if b in punish:
            return -1

        # punish ipv6
        if ':' in a or ':' in b:
            return a.count(':') - b.count(':')

        # punish ipv4
        a_is_ipv4 = a.count('.') == 3 and not any(c.isalpha() for c in a)
        b_is_ipv4 = b.count('.') == 3 and not any(c.isalpha() for c in b)
        if a_is_ipv4 and a.startswith('127.'):
            return 1
        if b_is_ipv4 and b.startswith('127.'):
            return -1
        if a_is_ipv4 and not b_is_ipv4:
            return 1
        if a_is_ipv4 and b_is_ipv4:
            return 0
        if not a_is_ipv4 and b_is_ipv4:
            return -1

        # favor hosts with more dots
        diff = b.count('.') - a.count('.')
        if diff != 0:
            return diff

        # favor longest fqdn
        return len(b) - len(a)

    def _key_hostname(e):
        # should never have a space in hostname
        # favor hostnames w/o spaces
        if ' ' in e:
            first = 1
        else:
            first = -1

        # punish localhost list
        if e in punish:
            second = punish.index(e)
        else:
            second = -1

        # punish ipv6
        third = e.count(':')

        # punish ipv4
        e_is_ipv4 = e.count('.') == 3 and not any(c.isalpha() for c in e)
        if e_is_ipv4 and e.startswith('127.'):
            fourth = 1
        if e_is_ipv4:
            fourth = 1
        if not e_is_ipv4:
            fourth = -1

        # favor hosts with more dots
        fifth = -(e.count('.'))

        # favor longest fqdn
        sixth = -(len(e))

        return (first, second, third, fourth, fifth, sixth)

    if how_to_sort == 'cmp':
        return sorted(hostname_list, cmp=_cmp_hostname)
    else:
        return sorted(hostname_list, key=_key_hostname)

def comp(list1, list2, verbose):
    if len(list1) != len(list2):
        if verbose:
            print("Lists are not the same length!")
        return False

    is_same = True
    for idx, val1 in enumerate(list1):
        val2 = list2[idx]
        if val1 != val2:
            if verbose:
                print("ERROR: list1[{0}] <{1}> != list2[{2}] <{3}>".format(idx, val1, idx, val2))
            is_same = False
        else:
            if verbose:
                print("list1[{0}] <{1}> == list2[{2}] <{3}>".format(idx, val1, idx, val2))
    return is_same

hosts = [
    '128.187.10.3',
    '128.187.20.5',
    '192.168.1.1',
    '192.168.2.1',
    '1 2 3 4',
    '1.2.3.4',
    'www.1.com',
    'www.2.com',
    'www.a.com',
    'www.b.com',
    'www.one.com',
    'www.two.com',
    'www.alpha.com',
    'www.beta.com',
    'localhost.localdomain',
    'localhost.my.domain',
    'localhost4.localdomain4',
    'localhost',
    'ip6-localhost',
    'ip6-loopback',
    'ipv6-localhost',
    'ipv6-loopback',
    '127.0.2.1',
    '127.0.1.1',
    '127.0.0.1',
    '0.0.0.0',
    '::1',
    'fe00::',
    'fe02::',
]

cmp_sorted_hosts = _sort_hostnames(hosts, "cmp")
key_sorted_hosts = _sort_hostnames(hosts, "key")

if comp(cmp_sorted_hosts, key_sorted_hosts, True):
    print("cmp_sorted_hosts and key_sorted_hosts produce the same results.")
else:
    print("ERROR: cmp_sorted_hosts and key_sorted_hosts produce different results!")
</pre>

### CODE REVIEW

**Comment by ckochenower** [comment]
The following modules use the cmd kwarg when calling sorted and will need similar refactoring to be Py3 compatible:

./salt/modules/brew.py
./salt/modules/portage_config.py
./salt/modules/win_pkg.py

**Comment by skizunov** [comment]
@ckochenower:
Shouldn't this:
        if e_is_ipv4:
            fourth = 1
Be this:
        if e_is_ipv4:
            fourth = 0
Since the original code "punished" more for:
"e_is_ipv4 and e.startswith('127.')"

If not, you could probably safely remove:
        if e_is_ipv4 and e.startswith('127.'):
            fourth = 1
Since it is redundant with:
        if e_is_ipv4:
            fourth = 1

**Comment by ckochenower** [comment]
@skizunov - Good catch. I will submit another pull request with the following change:

        # punish ipv4
        e_is_ipv4 = e.count('.') == 3 and not any(c.isalpha() for c in e)
        if e_is_ipv4 and e.startswith('127.'):
            fourth = 1
        if e_is_ipv4:
            fourth = 0
        if not e_is_ipv4:
            fourth = -1

**Comment by ckochenower** [comment]
@skizunov - Excellent. Would you mind submitting a pull request with your changes?

**Comment by ckochenower** [comment]
@skizunov - I hope you don't mind, but I submitted a PR with your changes. 
https://github.com/saltstack/salt/pull/23500
Thank you for the code review.

**Comment by skizunov** [comment]
I did too: #23497
I thought that you would get the notification of this. I guess I was wrong.

**Pull request merged**
