### PR TITLE
Let ext_pillar_first determine the override order

### PR DESCRIPTION
**Pull request by kraney**
Currently, regardless of the value of the ext_pillar_first, ext_pillar values will override the local pillar_roots values. Ext_pillar_first causes the ext_pillars to be parsed before the local roots, but still merged second. This seems to me to defeat the purpose of ext_pillar_first, unless it has another purpose I'm not aware of.

This change reverses the order of the merge, so that a local pillar can override ext_pillar.

I ran into this issue because I'm using a gitfs pillar. In order to test changes before I push them up there, I want to check out that repo into the local pillar, and try the changes there. So I need the local changes to override identical settings from gitfs.

This could be related to #24501 and #19332

### CODE REVIEW

**Comment by cachedout** [comment]
@kraney This does seem like the better behavior, but I have some concerns about the impact on existing installations. What do you think about possibly config-gating this and allowing a person to choose their override strategy?

**Comment by kraney** [comment]
I understand your concern. I just changed the behavior directly because I was unable to discern any other purpose for the ext_pillar_first setting, if it doesn't affect this override behavior. Yes, technically the ext_pillar data gets loaded chronologically first, but that has no external effect that I could find. It seemed like a bug. So I felt doubtful that anyone would be using the flag and therefore surprised by this change in behavior.

What about deprecating the old ext_pillar_first setting, and using a new name for it? That would prevent people from being surprised. I'd just hate to leave ext_pillar_first there as kind of a useless setting.

**Comment by kraney** [comment]
... however I'm open to suggestions of better implementations.

**Comment by thatch45** [comment]
I agree, make the new behavior replace the etc_pillar_first flag, so we would make a new flag with the new behavior and set a deprecation on ext_pillar _first

**Comment by cachedout** [comment]
@kraney Just a bump to make sure you saw the comments from @thatch45 above. I want to make sure we don't lose track of this one. :] Thanks!

**Comment by kraney** [comment]
OK, that sounds reasonable. I don't actually know how to deprecate something, can someone point me to an example? And any suggestions on a new name for the setting?

**Comment by cachedout** [comment]
Sure thing. `salt.utils.warn_until` is what's normally used. I don't have any strong preferences on the name.

**Comment by rallytime** [comment]
@kraney There's also some documentation on [Deprecating Salt Code](https://docs.saltstack.com/en/latest/topics/development/deprecations.html), if you haven't seen it already.

**Comment by kraney** [comment]
Thanks for the links, I had not seen those. What would be the correct value for the 'warn until' release at this point?

... will fix the pylint warning

**Comment by cachedout** [comment]
Probably `Nitrogen` would be best.

**Comment by cachedout** [comment]
Whoops, looks like there's a merge conflict. If you can rebase this, we'll get it in today. Thanks, @kraney

**Comment by cachedout** [comment]
Looks like a lint error now I'm afraid.

**Comment by kraney** [comment]
Lint caught me in a merge mistake. Well done, lint.

**Comment by cachedout** [comment]
Thought that might be the case. ;] Thanks, @kraney

**Comment by rsuarezsoto** [comment]
Is there any workaround for this while there is no fixed version in the repos? I'm also trying to use local and gitfs pillars, and I can't make them work because of this issue.

Thanks in advance.

**Comment by kraney** [comment]
I wasn't able to find one. I should also note, even with this fix, I had trouble with unexpected behavior using a local checkout of a gitfs pillar. Things still didn't override in the way I expected.

**Comment by terminalmage** [comment]
@kraney It turns out that your initial intuition was correct. I recently fixed exactly this issue in #36807 several weeks ago in an earlier release branch. I spoke with @cachedout and @thatch45 at the time and we came to a consensus that it was the correct fix.

Since ``ext_pillar_first`` was simply not behaving correctly, and reversing the merge order resolves this (a conclusion you and I both reached separately), I'm reverting the config option that you added after discussion with our dev team. It is redundant, and more people are likely to be using ``ext_pillar_first`` since it has been around for a year and a half now. See #37979 for more details.

@rsuarezsoto the fix I made several weeks ago in #36807 did make it into 2016.3.4, as well as 2016.11.0.

**Pull request merged**
