### PR TITLE
 #60700 Autostart option for virt module

### PR DESCRIPTION
**Pull request by XelK**
### What does this PR do?
 #60700 add autostart option to virt module. Implemented in virt.running and virt.defined
### What issues does this PR fix or reference?
 [FEATURE REQUEST] salt.states.virt: support autostart for VMs #60700 

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [ ] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated
Automatic tests passed

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by XelK** [comment]
> ### Hi! I'm your friendly PR bot!
> 
> You might be wondering what I'm doing commenting here on your PR.
> 
> **Yes, as a matter of fact, I am...**
> 
> I'm just here to help us improve the documentation. I can't respond to questions or anything, but what I _can_ do, I do well!
> 
> **Okay... so what do you do?**
> 
> I detect modules that are missing docstrings or "CLI Example" on existing docstrings! When I was created we had a _lot_ of these. The documentation for these modules need some love and attention to make Salt better for our users.
> 
> **So what does that have to do with my PR?**
> 
> I noticed that in this PR there are some files changed that have some of these issues. So I'm leaving this comment to let you know your options.
> 
> **Okay, what are they?**
> 
> Well, my favorite, is that since you were making changes here I'm hoping that you would be the most familiar with this module and be able to add some other examples or fix any of the reported issues.
> 
> **If I can, then what?**
> 
> Well, you can either add them to this PR or add them to another PR. Either way is fine!
> 
> **Well... what if I can't, or don't want to?**
> 
> That's also fine! We appreciate _all_ contributions to the Salt Project. If you can't add those other examples, either because you're too busy, or unfamiliar, or you just aren't interested, we still appreciate the contributions that you've made already.
> 
> Whatever approach you decide to take, just drop a comment here letting us know!
> Detected Issues (click me)
> 
> Thanks again!

Functions with the issues were not updated with this pr.

**Comment by cbosdo** [comment]
Could you please adapt the unit tests to add the new parameter? You can see the errors by clicking the red tests in this PR. This opens a page with a `View more details on ...` link to the report at the bottom.

**Comment by MKLeb** [comment]
Hi @XelK, it looks like there are some related failing virt tests here.  Also, would you mind adding some additional tests to test this specific addition and a changelog?

**Comment by MKLeb** [comment]
@cbosdo I have updated the tests and added a new one for the `update` func if you wanted to take a quick look and re-review

**Review by s0undt3ch — DISMISSED** [review]

**Review by cbosdo — DISMISSED** [review]
Thanks a lot for the PR and the tests adjustments 👍🏻

**Review by Ch3LL — APPROVED** [review]

**Comment by Ch3LL** [comment]
merging, as there were passing tests before the changelog commit.

**Pull request merged**
