### PR TITLE
Use 'minion_id' in cmd_{yaml{,ex},json} ext_pillar functions

### PR DESCRIPTION
**Pull request by 0xf10e**
Hi,

added the option to use a '%s' in `cmd_*` external pillars to insert the minion id.
Enables some simple ext_pillar like 

```
ext_pillar:
  - cmd_yaml: grep ^roles /srv/salt/pillar/hosts/%s.sls
```

to get a line like `roles: [foo, bar]` from a minion's pillar.

While I thought this would enable pillar based targeting inside pillar (like I suggested to someone [on salt-users here](https://groups.google.com/d/msg/salt-users/kla2TKQqa2w/eK6RSnLkyMAJ)) it at least makes the cmd_\* ext_pillars slightly more useful examples. Or maybe my CentOS 6.6 master is just to outdated.

PS: You can ignore the network part - or with sufficiently strong git-fu (mine is not) split it off by rebasing or something.

### CODE REVIEW

**Comment by 0xf10e** [comment]
Oh, btw: simple way to try this on a master not running 'develop' is 
 - adding something like the following to your master's config
```
extension_modules: /srv/salt/modules
external_pillar_first: True
ext_pillar:
  - cmd_yaml: grep ^roles /srv/salt/pillar/hosts/%s.sls
```
 - create `/srv/salt/modules/pillar` and place the updated `cmd_*.py` of your choice there
 - restart the master

**Comment by jfindlay** [comment]
@0xf10e, seems like a great idea.  Would it be better to use a more specific token for `minion_id` than `%s`?  How about `{minion_id}` or `{minion}` or `{m_id}`?

**Comment by 0xf10e** [comment]
@jfindlay I've just wanted something quick w/o to much headache to check is this would enable pillar-based targeting inside pillar ;)

But you're right, I would prefer {minion_id}, too.

**Comment by Grokzen** [comment]
@0xf10e @thatch45 In what release can we expect to see this? It is not part of the 2015.5.1 release.

**Comment by jfindlay** [comment]
Beryllium is scheduled to be released in August.

**Pull request merged**
