### PR TITLE
Replace args and kwargs (plural) by arg and kwarg (singular) for ``RunnerClient``

### PR DESCRIPTION
**Pull request by pass-by-value**
### What does this PR do?
- Adds support for `arg` and `kwarg` to `RunnerClient`
- Removes  `args` and `kwargs` from `RunnerClient`
### What issues does this PR fix or reference?

First 2 steps of #32778 
### Previous Behavior

`RunnerClient` would be called with `args` and `kwargs`
### New Behavior

`RunnerClient` now to be called with `arg` and `kwarg`
### Tests written?

Yes

### CODE REVIEW

**Comment by rallytime** [comment]
@pass-by-value Looks like your new test needs a little love. :)

**Comment by cachedout** [comment]
This looks like it changes what RunnerClient _itself_ expects in terms of named arguments. Is this the case?

**Comment by pass-by-value** [comment]
@cachedout: Yes `RunnerClient` should now accept `arg` and `kwarg` for passing arguments.

**Comment by cachedout** [comment]
Right, but what I'm asking is whether this is going to affect any consumer of the RunnerClient. If it requires that they make a change to how they're interacting with it, then we need to be very careful.

**Comment by pass-by-value** [comment]
@cachedout: Yes, clients will need to be aware of this change. That way we have a consistent way of talking to LocalClient and RunnerClient and all RunnerClient's consumers call RunnerClient with the same argument names. Would like to hear your suggestions on this rationale.

**Comment by cachedout** [comment]
The issue here is that I know of a number of large installations that instantiate the RunnerClient directly and changing that interface out from underneath them is going to break their stuff massively. Given that RunnerClient is a public API, I don't like this sort of sudden and undocumented change.

IMHO, we need to deprecate this change and document it as-such.

**Comment by pass-by-value** [comment]
I was just thinking of putting this on a deprecation path so that

1. RunnerClient accepts `arg` and `kwarg` per this new change
1. RunnerClient still accepts `args` and `kwargs` but logs a warning about deprecation when consumers pass  the plural form
1. Once the deprecation is complete RunnerClient will only accept the singular form (`arg` and `kwarg`)

That way the change isn't sudden and lets us add documentation around it.

@cachedout: Please let me know if you'd like anything additionally or differently. Thanks for your help!!

**Comment by cachedout** [comment]
@pass-by-value Much better. Please make it so. :]

**Comment by cachedout** [comment]
@pass-by-value Where are we on this one?

**Comment by pass-by-value** [comment]
@cachedout and @rallytime I've updated this. @cachedout I'm having some trouble with the warning not showing when I call it via salt api. Please let me know if this is a good way to handle deprecation.

**Comment by cachedout** [comment]
@pass-by-value That's an unsolved problem AFAIK. Could you file a GH issue on it?

I'd like to also add a warning to the release notes before we get this in, please. Once that's there go ahead and ping me and I'll merge it. Thanks.

**Comment by pass-by-value** [comment]
@cachedout: Created #33024 and added a warning to the release notes.

**Comment by whiteinge** [comment]
I'm way late to this party, but the args/kwargs (plural) addition to RunnerClient was never documented. I'm presuming it was added for a reason but I don't know what that reason was. Though a deprecation warning is always a good idea, of course.

**Pull request merged**
