### PR TITLE
Use proper query method from CloudClient

### PR DESCRIPTION
**Pull request by techhat**
Fixes #18320. Ping @jmdcal.

QA: Please review this carefully; the `list_nodes_min` optimization has proven to be tricky.

### CODE REVIEW

**Comment by rallytime** [comment]
@techhat Is this something that can/should be backported?

**Comment by jmdcal** [comment]
You can test it easily on a given version, so if you have this error in the old version, you will want to backport it.

**Comment by sebest** [comment]
I backported it as it is broken on 2014.7 which is the current version afaik?
So my question is will you release a 2014.7.1 with this fix?

**Comment by techhat** [comment]
@rallytime, if it can be backported (and it sounds like it can) then it should be.

**Pull request merged**
