### PR TITLE
cloud/digitalocean: Don't add ssh_interface to kwargs (Fixes: #54373).

### LINKED ISSUE #54373: Unable to create Digitalocean droplets using salt-cloud
### Description of Issue
Digitalocean might have changed something on their side.
```
salt-cloud -p asx-salt-test asx-jj-test
[ERROR   ] Error creating asx-jj-test on DIGITALOCEAN

The following exception was thrown when trying to run the initial deployment: An error occurred while querying DigitalOcean. HTTP Code: 400  Error: '{"id":"bad request","message":"found unpermitted parameters: ssh_interface"}'
Error: There was a profile error: Failed to deploy VM
```

### Setup
Digitalocean provider configuration:
do:
  driver: digital_ocean
  personal_access_token: xxxxxxxxxxx
  ssh_key_file: /etc/salt/pki/cloud/do.pem
  ssh_key_names: asx-salt
  script: bootstrap-salt
  script_args: stable 2018.3.4

Digitalocean profile configuration:
asx-base:
  provider: do
  image: ubuntu-16-04-x64
  location: ams3
  private_networking: true

asx-salt-test:
  extends: asx-base
  size: s-1vcpu-2gb
  tags:
    - TEST

### Steps to Reproduce Issue
salt-cloud -l debug -p asx-salt-test asx-jj-test
```
[DEBUG   ] Reading configuration from /etc/salt/cloud
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: asx-salt
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/digitalocean.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/digitalocean.conf
[DEBUG   ] Missing configuration file: /etc/salt/cloud.profiles
[DEBUG   ] Including configuration from '/etc/salt/cloud.profiles.d/digitalocean.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles.d/digitalocean.conf
[DEBUG   ] Configuration file path: /etc/salt/cloud
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[DEBUG   ] Marking 'base64_encode' as a jinja filter
[DEBUG   ] Marking 'base64_decode' as a jinja filter
[DEBUG   ] Marking 'md5' as a jinja filter
[DEBUG   ] Marking 'sha256' as a jinja filter
[DEBUG   ] Marking 'sha512' as a jinja filter
[DEBUG   ] Marking 'hmac' as a jinja filter
[DEBUG   ] Marking 'random_hash' as a jinja filter
[DEBUG   ] Marking 'rand_str' as a jinja filter
[DEBUG   ] Marking 'file_hashsum' as a jinja filter
[DEBUG   ] Marking 'http_query' as a jinja filter
[DEBUG   ] Marking 'strftime' as a jinja filter
[DEBUG   ] Marking 'date_format' as a jinja filter
[DEBUG   ] Marking 'yaml_dquote' as a jinja filter
[DEBUG   ] Marking 'yaml_squote' as a jinja filter
[DEBUG   ] Marking 'yaml_encode' as a jinja filter
[DEBUG   ] Marking 'raise' as a jinja global
[DEBUG   ] Marking 'match' as a jinja test
[DEBUG   ] Marking 'equalto' as a jinja test
[DEBUG   ] Marking 'skip' as a jinja filter
[DEBUG   ] Marking 'sequence' as a jinja filter
[DEBUG   ] Marking 'to_bool' as a jinja filter
[DEBUG   ] Marking 'tojson' as a jinja filter
[DEBUG   ] Marking 'quote' as a jinja filter
[DEBUG   ] Marking 'regex_escape' as a jinja filter
[DEBUG   ] Marking 'regex_search' as a jinja filter
[DEBUG   ] Marking 'regex_match' as a jinja filter
[DEBUG   ] Marking 'regex_replace' as a jinja filter
[DEBUG   ] Marking 'uuid' as a jinja filter
[DEBUG   ] Marking 'unique' as a jinja filter
[DEBUG   ] Marking 'min' as a jinja filter
[DEBUG   ] Marking 'max' as a jinja filter
[DEBUG   ] Marking 'avg' as a jinja filter
[DEBUG   ] Marking 'union' as a jinja filter
[DEBUG   ] Marking 'intersect' as a jinja filter
[DEBUG   ] Marking 'difference' as a jinja filter
[DEBUG   ] Marking 'symmetric_difference' as a jinja filter
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad digital_ocean.optimize_providers: 'digital_ocean.optimize_providers' is not available.
[DEBUG   ] The 'digital_ocean' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad digital_ocean.list_nodes_min: 'digital_ocean.list_nodes_min' is not available.
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Starting new HTTPS connection (1): api.digitalocean.com
[DEBUG   ] https://api.digitalocean.com:443 "GET /v2/droplets/?page=1&per_page=200 HTTP/1.1" 200 None
[DEBUG   ] https://api.digitalocean.com/v2/droplets/?page=1&per_page=200
[DEBUG   ] Generating minion keys for 'asx-jj-test'
[DEBUG   ] LazyLoaded cloud.fire_event
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/cloud/asx-jj-test/creating; data = {u'profile': u'asx-salt-test', u'_stamp': '2019-09-01T15:18:12.006856', u'name': u'asx-jj-test', u'driver': u'digital_ocean', u'provider': u'do:digital_ocean', u'event': u'starting create'}
[INFO    ] Creating Cloud VM asx-jj-test
[DEBUG   ] Starting new HTTPS connection (1): api.digitalocean.com
[DEBUG   ] https://api.digitalocean.com:443 "GET /v2/sizes/?per_page=100 HTTP/1.1" 200 None
[DEBUG   ] https://api.digitalocean.com/v2/sizes/?per_page=100
[DEBUG   ] Starting new HTTPS connection (1): api.digitalocean.com
[DEBUG   ] https://api.digitalocean.com:443 "GET /v2/images/?page=1&per_page=200 HTTP/1.1" 200 None
[DEBUG   ] https://api.digitalocean.com/v2/images/?page=1&per_page=200
[DEBUG   ] Starting new HTTPS connection (1): api.digitalocean.com
[DEBUG   ] https://api.digitalocean.com:443 "GET /v2/regions/ HTTP/1.1" 200 None
[DEBUG   ] https://api.digitalocean.com/v2/regions/
[DEBUG   ] Starting new HTTPS connection (1): api.digitalocean.com
[DEBUG   ] https://api.digitalocean.com:443 "GET /v2/account/keys/?page=1&per_page=100 HTTP/1.1" 200 None
[DEBUG   ] https://api.digitalocean.com/v2/account/keys/?page=1&per_page=100
[INFO    ] ssh_interface: Setting interface for ssh to public
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/cloud/asx-jj-test/requesting; data = {u'event': u'requesting instance', u'_stamp': '2019-09-01T15:18:14.059552', u'ssh_keys': [u'17578289'], u'tags': [u'TEST'], u'region': u'ams3', u'ssh_interface': u'public', u'private_networking': True, u'size': u's-1vcpu-2gb', u'image': u'ubuntu-16-04-x64', u'name': u'asx-jj-test'}
[DEBUG   ] Starting new HTTPS connection (1): api.digitalocean.com
[DEBUG   ] https://api.digitalocean.com:443 "POST /v2/droplets/ HTTP/1.1" 400 76
[ERROR   ] Error creating asx-jj-test on DIGITALOCEAN

The following exception was thrown when trying to run the initial deployment: An error occurred while querying DigitalOcean. HTTP Code: 400  Error: '{"id":"bad request","message":"found unpermitted parameters: ssh_interface"}'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/digitalocean.py", line 449, in create
    ret = create_node(kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/digitalocean.py", line 269, in create_node
    node = query(method='droplets', args=args, http_method='post')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/digitalocean.py", line 577, in query
    request.text
SaltCloudSystemExit: An error occurred while querying DigitalOcean. HTTP Code: 400  Error: '{"id":"bad request","message":"found unpermitted parameters: ssh_interface"}'
Error: There was a profile error: Failed to deploy VM
```

### Versions Report
Salt Version:
           Salt: 2018.3.4
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-134-generic
         system: Linux
        version: Ubuntu 16.04 xenial

### PR DESCRIPTION
**Pull request by andrewsomething**
### What does this PR do?

`ssh_interface` is an option internal to Salt specifying which interface connect over. This PR stops adding it to the `kwargs` provided when launching a new instance this attribute is not part of the DigitalOcean API.

### What issues does this PR fix or reference?

Fixes: https://github.com/saltstack/salt/issues/54373

### Tests written?

No - The existing integration test should continue to pass

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by twangboy** [comment]
Please rebase this against the master branch.

**Comment by andrewsomething** [comment]
@twangboy Re-based on master.

**Comment by sagetherage** [comment]
rebased with Master assigning @s0undt3ch as I have you assigned to the issue tied to the PR, let's try to get this into Sodium

**Comment by sagetherage** [comment]
rebase against master, again

**Pull request merged**
