### PR TITLE
Code block start comment typo

### PR DESCRIPTION
**Pull request by matyunin**

### CODE REVIEW

**Comment by thatch45** [comment]
I don't see what the typo is, won't line 647 break the setup.py?

**Comment by s0undt3ch** [comment]
It will.

**Comment by matyunin** [comment]
Yes, you are right, i removed "Static" word.

Typo is in the end of comment line. In all comment lines (starting a code block) it's "--->" but on line 646 in "develop" branch it's "----".

Thats my small fix :)

**Comment by thatch45** [comment]
Thanks :), this I can merge :)

**Pull request merged**
