### PR TITLE
Mongo returners patch 1

### PR DESCRIPTION
**Pull request by rhealitycheck**
Cleaning up the rest of the bugfix from https://github.com/saltstack/salt/issues/27125 looks like there's an issue where pymongo changes what should be static data. I'll raise an issue with them on that point but for now this should fix all issues with the returners in the 2015.8 release

### CODE REVIEW

**Comment by jfindlay** [comment]
Nice, thanks, @rhealitycheck.  In the future you are welcome to submit fixes directly to the applicable release branch, see https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch.

**Comment by rhealitycheck** [comment]
@jfindlay sure will do. i'll clean up the pylint errors on this one and then i'll submit these fixes to the 2015.8 branch as well.

**Comment by rhealitycheck** [comment]
@jfindlay so i'm getting some pylint complaints that i'm not sure why it's complaining this second time around, i removed the trailing whitespaces which it was complaining about initially. any advice? also the mongo_return.py seems to be having more issues than the mongo_future_return.py and the mongo_return.py is no longer even valid because it doesn't have a save_load function. is there a recommendation on deprecating modules like that?

**Comment by jfindlay** [comment]
@rhealitycheck, the whitespace complaints are for trailing whitespace on lines rather than blank lines.

**Comment by jtand** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
@rhealitycheck, just one more comma, https://jenkins.saltstack.com/job/salt-pr-lint-n/9441/violations/file/salt/returners/mongo_return.py/.

**Comment by rhealitycheck** [comment]
@jfindlay thanks for catching that, with all the linting trailing spaces that was hard to see.

**Comment by basepi** [comment]
Great work, thanks!

**Comment by blueyed** [comment]
Thanks for the changes.

However, this should have probably been rebased / amended into a single commit (or some smaller units/commits), with actual information about the changes in the commit message.
It's too late for now, but I've just noticed this when looking at the recent changes.

(I don't want to sound grumpy nor disrespectful - just wanted to provide this advise / suggestion for the future.  Thanks again! :octocat: )

**Comment by rhealitycheck** [comment]
@blueyed thanks for the comment, however, all but two of the commits were linting errors for trailing whitespace, they don't have comments because they aren't meaningful. the first commit has all the meaningful changes.

**Comment by blueyed** [comment]
@rhealitycheck 
So it could just have been a single commit (or two) then - which was my point.
Anyway, thanks again!

**Pull request merged**
