### PR TITLE
git_pillar: Add tests for mountpoint parameter

### PR DESCRIPTION
**Pull request by sathieu**
### What does this PR do?

git_pillar: Add tests for mountpoint parameter

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by sathieu** [comment]
I plan to backport #50378, #50407 and this one to 2018.03.

My target is to fix #50364.

**Comment by cachedout** [comment]
@sathieu There are some merge conflicts here. Can you please resolve them?

**Comment by sathieu** [comment]
It has been backported to 2018.3 as #50427.

I thought it would be forward ported as part of 2018.3 to develop regular merge.

**Comment by terminalmage** [comment]
@sathieu In that case, I think we can close this since https://github.com/saltstack/salt/pull/50427 was merged.

**Comment by sathieu** [comment]
OK. Thanks.

**Pull request closed without merging**
