### PR TITLE
Add support for syncing netapi modules

### PR DESCRIPTION
**Pull request by kriberg**
### What does this PR do?
According to the [documentation](https://docs.saltproject.io/en/latest/topics/netapi/writing.html),
it should be possible to add custom netapi modules. Currently, there's no way
to sync those from filesystem or gitfs to the local cachethough. This PR adds
sync_netapi to the saltutil runner.

### What issues does this PR fix or reference?
Fixes:

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by mchugh19** [comment]
Cool! If you're now able to sync netapi modules, can you add support to to the saltutil.sync* states?

**Comment by kriberg** [comment]
> Cool! If you're now able to sync netapi modules, can you add support to to the saltutil.sync* states?

Sure, I'll add it. Didn't see the use case for syncing them to minions.

**Review by Ch3LL — CHANGES_REQUESTED** [review]
can we also get a changelog and test coverage for these new functions.

**Comment by dwoz** [comment]
Closing this due to inactivity. Anyone should feel free to re-open it if they want to see it through to the end in one release cycle.

**Pull request closed without merging**
