### PR TITLE
Implements status.nproc on FreeBSD

### PR DESCRIPTION
**Pull request by kim0**

### CODE REVIEW

**Comment by kim0** [comment]
I'll just use the default error handling mechanism for the method, which is to return zero

**Comment by jfindlay** [comment]
@kim0, @rodrigc feel free to pull request these against 2014.7 rather than if you want, since they may be considered bug fixes in addition to features (since we claim to support FreeBSD).  2015.2 has been forked from develop already, thus a stable branch including code going into develop is going to be 2-3 months out.

**Comment by thatch45** [comment]
This is a good start so I will merge it in, but we should consider adding more checks for more platforms

**Comment by kim0** [comment]
@thatch45 @jfindlay suggested I PR to 2014.7, so I closed this one and opened #20080 .. I'm by no means an expert coder, so bare with me

**Pull request closed without merging**
