### PR TITLE
Revert PR 41278

### PR DESCRIPTION
**Pull request by terminalmage**
PR #41278 should not have been merged, as there are very good reasons for
keeping the `mongodb_database` and `mongodb_user` state modules separate.
Additionally, role management was already supported at the time the PR
was merged.

Since this PR has not been in an official release of Salt, I'm reverting
it now to prevent any confusion.

### CODE REVIEW

**Comment by terminalmage** [comment]
re-run all

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
re-run py

**Comment by jettero** [comment]
For the record, I don't remember why I submitted the PR or what I was trying to fix. It's possible I simply misunderstood something at the time. I lost interest in mongodb almost immediately and forgot all the details related to this anyway.

In short, revert away, no hard feelings or argument. Thanks.

**Comment by rallytime** [comment]
re-run py

**Comment by rallytime** [comment]
@terminalmage There are some test failures that need to be addressed with this change:

https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu14-n/20933/#showFailuresLink

- unit.states.test_mongodb_user.MongodbUserTestCase.test_absent
- unit.states.test_mongodb_database.MongodbDatabaseTestCase.test_absent

**Comment by terminalmage** [comment]
@jettero no problem!

**Pull request merged**
