### PR TITLE
Follow-up fix for #46575

### PR DESCRIPTION
**Pull request by isbm**
### What does this PR do?

Follow-up fix on https://github.com/saltstack/salt/pull/46575/

/cc: @terminalmage @mbologna

### CODE REVIEW

**Review by terminalmage — APPROVED** [review]

**Comment by mbologna** [comment]
Looks good

**Comment by cachedout** [comment]
A test failed here and needs investigation: https://jenkins.saltstack.com/job/PR/job/salt-pr-linode-ubuntu16-py3/8073/testReport/junit/unit.grains.test_core/CoreGrainsTestCase/test_fqdns_return/

**Comment by rallytime** [comment]
@isbm Thanks for fixing that test. It looks like there's a merge conflict on the `test_core` file now. Can you rebase this? That will also clear up some of those other test failures as they've been fixed upstream now. :D

**Comment by rallytime** [comment]
re-run py3

**Pull request merged**
