### PR TITLE
Fix libcloud_dns state module bug

### LINKED ISSUE #40177: libcloud_dns state "global name '__salt__' is not defined" in salt.cmd runner
### Description of Issue/Question
I got this stack trace:
```
An exception occurred in this state: Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/salt/state.py", line 1746, in call
            **cdata['kwargs'])
          File "/usr/local/lib/python2.7/dist-packages/salt/loader.py", line 1704, in wrapper
            return f(*args, **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/salt/states/libcloud_dns.py", line 169, in record_present
            zones = libcloud_dns_module.list_zones(profile)
          File "/usr/local/lib/python2.7/dist-packages/salt/modules/libcloud_dns.py", line 109, in list_zones
            conn = _get_driver(profile=profile)
          File "/usr/local/lib/python2.7/dist-packages/salt/modules/libcloud_dns.py", line 69, in _get_driver
            config = __salt__['config.option']('libcloud_dns')[profile]
        NameError: global name '__salt__' is not defined
```
when running salt states that call libcloud_dns.record_present function using salt.cmd runner.

EDIT: It seems that __salt__ is still defined in /usr/local/lib/python2.7/dist-packages/salt/states/libcloud_dns.py:169,  but when calling into libcloud_dns_module.list_zones the module doesn't have it's own copy of __salt__ - maybe the libcloud_dns module doesn't load correctly when calling it from the state?

### Setup
my sls - godaddy.sls:
update_dns:
    libcloud_dns.record_present:
        - name: subdomain
        - zone: example.com
        - type: A
        - data: 1.1.1.1
        - profile: profile1

### Steps to Reproduce Issue
Just run:
sudo salt-run salt.cmd state.apply godaddy

### Versions Report
Salt Version:
           Salt: 2016.11.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 2.6.0
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6

System Versions:
           dist: Ubuntu 14.04 trusty
        machine: x86_64
        release: 4.4.0-31-generic
         system: Linux
        version: Ubuntu 14.04 trusty

### PR DESCRIPTION
**Pull request by tonybaloney**
### What does this PR do?
Fix #40177 by using `__salt__` instead of importing the module directly

### What issues does this PR fix or reference?
 #40177

### Tests written?

Yes - existing tests updated

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Review by cachedout — CHANGES_REQUESTED** [review]
Hi @tonybaloney !

Could you make some minor style changes as outlined here, please?

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/9783/violations/file/tests/unit/states/test_libcloud_dns.py/

**Comment by tonybaloney** [comment]
@cachedout that should do it. I have a feeling some of my other state modules might be vulnerable to the same issue as this is a pattern I've used elsewhere. I'll have a look.

**Comment by rallytime** [comment]
@tonybaloney Another lint error snuck in here after you fixed up the unit test failures. Mind taking one more look? :)

https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/9850/violations/file/tests/unit/states/test_libcloud_dns.py/

**Comment by tonybaloney** [comment]
@rallytime done (for the last time I hope)!

also, ftr,  I checked my other state modules and this was the only one I made this mistake, so we're all good.

**Comment by rallytime** [comment]
Thank you for fixing this @tonybaloney!

**Pull request merged**
