### PR TITLE
Allow specifying which modules should be used when running saltutil.sync_*

### PR DESCRIPTION
**Pull request by gtmanfred**
### What issues does this PR fix or reference?
Before, all modules were being synced, this allows only specific modules to be synced when specified.

### What issues does this PR fix or reference?

https://github.com/saltstack/zh/issues/990

### Tests written?

Yes!

### CODE REVIEW

**Comment by gtmanfred** [comment]
I am going to add a couple integration tests in a minute.

**Comment by gtmanfred** [comment]
Let me know what you think about the last commit, i can live with or without it.

Thanks,
Daniel

**Review by cachedout — APPROVED** [review]
I really like this. It has earned the much-coveted `Awesome` label. :]

**Comment by gtmanfred** [comment]
😊

**Pull request merged**
