### PR TITLE
Addresses #42938 - disk.format_ documentation

### PR DESCRIPTION
**Pull request by corywright**
### What does this PR do?

Fixes a documentation issue in `disk.format_`.

### What issues does this PR fix or reference?

Addresses issue #42938 

This is submitted against `2016.11` but also should be applied to all newer branches.

### CODE REVIEW

**Comment by rallytime** [comment]
@corywright Wouldn't it be better to just add the alias in? Checkout the `__func_alias__` definition in various execution modules for some examples.

**Comment by corywright** [comment]
@rallytime I assumed that was an intentional omission. 

I'd certainly prefer a `format` alias, so I can add it if that is what is wanted.

**Comment by rallytime** [comment]
@corywright I don't think it is an intentional omission. If you could update this to include a `format` alias instead, making the doc change unnecessary, that would be great.

**Comment by terminalmage** [comment]
As @rallytime pointed out, an alias is the way to go here. I've found an example for you: https://github.com/saltstack/salt/blob/3184168/salt/modules/state.py#L60-L62

Just add a `__func_alias__` dict like that, mapping the `format_` function to `format`, and revert the docs change, and this will in effect change it so that the function is called with `disk.format` instead of `disk.format_`.

**Comment by terminalmage** [comment]
As a bit of background, we have the `__func_alias__` so that we don't overwrite builtin functions like `format()`, `set()`, `list()`, etc. Our module loader will check for a `__func_alias__` during the loading process, and use it to change the name under which that function is loaded for the purposes of being invoked within Salt.

**Comment by cachedout** [comment]
@corywright Any chance you'll be able to make the changes requested by @terminalmage? We'd love to get this one in. Thanks!

**Comment by corywright** [comment]
@cachedout Yes, sorry, I've been busy crisscrossing the country to see the sun disappear. :) 

I'll get a PR submitted soon.

**Comment by corywright** [comment]
@cachedout @terminalmage @rallytime Should the addition of the alias still be branched off of 2016.11?  

Maybe it would make sense to create a new issue/PR for alias instead, since the existing documentation would remain the same, and this current issue and PR are about fixing documentation.

**Comment by cachedout** [comment]
I'll let @terminalmage field that one. :]

**Comment by terminalmage** [comment]
In my opinion, the lack of a `__func_alias__` is a bug. There should be no documentation change made, we should fix the bug. Since bugfixes should go in the oldest non-EOL release branch where the bug exists, 2016.11 is the way to go here. You can feel free to close this PR and open a new one, if you like.

**Comment by corywright** [comment]
@terminalmage Thanks, I'll get this in soon.

**Comment by corywright** [comment]
Closing this documentation bug as the fix was introduced in #43199.

**Comment by terminalmage** [comment]
@corywright Thanks!

**Pull request closed without merging**
