### PR TITLE
add support for other types of projections in global secondary indexes

### PR DESCRIPTION
**Pull request by eapolinario**
### What does this PR do?

Adds support for the remaining types of projections of Global Secondary Indexes, as described in [the documentation](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GSI.html#GSI.Projections).
### What issues does this PR fix or reference?

none.
### Tests written?

No

@ryan-lane

### CODE REVIEW

**Comment by cachedout** [comment]
This may have failed a test: unit.modules.boto_lambda_test.BotoLambdaFunctionTestCase.test_that_when_describing_function_it_returns_the_dict_of_properties_returns_true

**Comment by ryan-lane** [comment]
I don't think the lambda test is related (it's a total different module and these changes don't affect it).

**Comment by eapolinario** [comment]
@cachedout , @ryan-lane : any way I can run these tests locally?

**Comment by ryan-lane** [comment]
@eapolinario https://docs.saltstack.com/en/develop/topics/development/tests/index.html

**Comment by cachedout** [comment]
@ryan-lane Thanks for the clarification. The boto tests can be a twisty maze at times. :]

**Pull request merged**
