### PR TITLE
Don't float exceptions on auth errors in mine

### PR DESCRIPTION
**Pull request by cachedout**
Refs #20735 but is not a complete fix.

### CODE REVIEW

**Comment by thedrow** [comment]
Can we add a testcase here to ensure this issue doesn't regress?
#20735 seems pretty severe.

**Comment by cachedout** [comment]
Certainly. I will re-open #20735 and mark it as needing a test case. Good call, @thedrow

**Comment by msciciel** [comment]
Any chances of downporting this fix to 2014.7.X branch ?

**Comment by rallytime** [comment]
@msciciel I took a quick look at this fix to see if it could be backported, but the fix occurred on code that has been refactored in the 2015.2 branch since 2014.7. But perhaps we can take a closer look to see how to apply this to the 2014.7 code. I've labeled this as needing a back-port.

**Comment by rallytime** [comment]
@msciciel I've backported this fix into 2014.7 in the above pull request. Would you be able to give that a try?

**Comment by msciciel** [comment]
I have problem with reproducing problem before applying patch. Dropping minion traffic on master and calling salt-call mine.update is not enough.

**Pull request merged**
