### PR TITLE
Backports git_pillar tests improvements to 2018.3

### PR DESCRIPTION
**Pull request by sathieu**
### What does this PR do?

Backports of #50378, #50407 and #50425.

### What issues does this PR fix or reference?

 #50378, #50407 and #50425.

### Tests written?

Yes. Improved coverage

### Commits signed with GPG?

Yes

### CODE REVIEW

**Review by terminalmage — APPROVED** [review]

**Comment by cachedout** [comment]
@sathieu I'm afraid there are some merge conflicts which need to be resolved before we can get this in. Could you please take a look?

**Comment by sathieu** [comment]
I've ended up using:
```
git fetch orign
git format-patch HEAD^^^
git reset --hard origin/2018.3
git am -S      0001-Don-t-fail-on-git_pillar-tests-when-destructive-test.patch
git am -S -C 1 0002-git_pillar-Add-tests-for-root-parameter.patch
git am -S -C 1 0003-git_pillar-Add-tests-for-mountpoint-parameter.patch
```
I looks like I only needed to do:
```
git fetch orign
git rebase -S -C 1 origin/2018.3
```

**Comment by sathieu** [comment]
It looks like #50417 broke my tests.

This is what I got too when I tested #50417 on our qa (we use mountpoints). @meaksh any idea?

**Comment by sathieu** [comment]
Reverting #50417 doesn't fix the tests ...

**Comment by sathieu** [comment]
> Reverting [59894e2](https://github.com/saltstack/salt/commit/59894e2c830585f7a0412dcc6b6637797459fe84). doesn't fix the tests ...

... but reverting the whole  #50417 does. :thinking:

**Comment by meaksh** [comment]
@sathieu - I've fixed the issue here. I created a PR to your PR https://github.com/sathieu/salt/pull/1 :smile:

**Comment by sathieu** [comment]
> @sathieu - I fixed the issue you have here. It seems Git messed up when you rebased your changes with latest `2018.3` branch.
> 
> I've created a PR to your PR [sathieu#1](https://github.com/sathieu/salt/pull/1) smile

Yes. Thanks! I've squashed your commit for clean history.

**Comment by rallytime** [comment]
@sathieu There is a related test failure here: https://jenkinsci.saltstack.com/job/pr-kitchen-ubuntu1604-py2/job/PR-50427/5/

Can you take a look?

**Comment by sathieu** [comment]
@rallytime: fixed (a `root` param was missing)

**Pull request merged**
