### PR TITLE
[develop] Merge forward from 2016.3 to develop

### PR DESCRIPTION
**Pull request by rallytime**
Conflicts:
- salt/minion.py

### CODE REVIEW

**Comment by cachedout** [comment]
We went pretty sideways on tests here. Maybe take another look at that minion.py merge conflict?

**Comment by rallytime** [comment]
Yeah I need to take another look here. The weird thing is that the merge conflicts were very easy on this one. I think something else is going on besides there minion.py conflict. I'll look today.

**Comment by rallytime** [comment]
These tests are failing because the test suite's sub-minion isn't spinning up and connecting correctly to the test suite's salt master. When the integration test suite starts, the following stacktrace occurs:
```
* Starting salt-master ... STARTED!
 * Starting salt-minion ... STARTED!
 * Starting sub salt-minion ... Traceback (most recent call last):
  File "/tmp/salt-tests-tmpdir/scripts/cli_salt_minion.py", line 27, in <module>
    salt_minion()
  File "/root/SaltStack/salt/salt/scripts.py", line 121, in salt_minion
    minion.start()
  File "/root/SaltStack/salt/salt/cli/daemons.py", line 356, in start
    self.minion.tune_in()
  File "/root/SaltStack/salt/salt/minion.py", line 1972, in tune_in
    io_loop=self.io_loop,
  File "/root/SaltStack/salt/salt/utils/event.py", line 901, in __init__
    self.publisher.start()
  File "/root/SaltStack/salt/salt/transport/ipc.py", line 477, in start
    self.sock.bind(('127.0.0.1', self.socket_path))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
 * Starting sub salt-minion ... STARTED!
 * Starting syndic salt-master ... STARTED!
 * Starting salt-syndic ... STARTED!
```
But I can't seem to figure out what is causing this problem in this merge-foward.

**Comment by cachedout** [comment]
@rallytime This might need a rebase from 2016.3 I think.

**Comment by rallytime** [comment]
@cachedout Maybe. I tried rebasing this with newer 2016.3 and develop versions twice yesterday because I thought I had a merge-conflict wrong, but that wasn't the case. The merge conflicts in minion.py really was quite simple - a one-line function definition that had changed (with your grains addition). I can try again tomorrow, but this is stumping me.

**Comment by rallytime** [comment]
Oh, sorry. I see what your'e saying now. I didn't see the comment above about the change to minion.py. I've submitted a new merge-forward in #33711.

**Pull request closed without merging**
