### PR TITLE
Feature/Add support for event_return to Slack Webhook returner

### LINKED ISSUE #57182: [FEATURE REQUEST] slack_webhook returner missing event_return function
**Is your feature request related to a problem? Please describe.**
Today, the slack_webhook returner can be configured on the salt-minion to return job results to a channel in Slack. This is wonderful, but it requires additional configuration on the minion and to pass the webhook URL to the minion. If possible, I'd like to have all jobs returned to the salt-master and then sent to a Slack channel.

**Describe the solution you'd like**
I'd like to have the salt-master send returned events to Slack, as opposed to the minion.

**Describe alternatives you've considered**
As a work around, I could configure my pillar to relay the webhook information to a minion. The minion should have what it needs to send the job results to Slack. 

**Additional context**
I believe all that's needed for this is to add an event_return function to the existing slack_webhook returner. Referencing other returners, I believe the following code is what's needed, per [the returner docs](https://docs.saltstack.com/en/latest/ref/returners/#event-support):

```
def event_return(events):
    """
    Return event data via Slack Webhook
    """

    for event in events:
        ret = event.get("data", False)

        if ret:
            returner(ret)
```

I've forked Salt and added these changes [here](https://github.com/natemellendorf/salt/blob/master/salt/returners/slack_webhook_return.py).
However, this needs to be tested.

### PR DESCRIPTION
**Pull request by natemellendorf**
### What does this PR do?
Adds the event_return function to the Slack Webhook returner.
This is needed, if you wish to run this returner on a salt-master and not directly from a salt-minion.

### What issues does this PR fix or reference?
Fixes: #57480

### Previous Behavior
Returner will POST to Slack API from a salt-minion

### New Behavior
Returner will POST to Slack API from a salt-minion or salt-master (if configured)

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [x] Docs
- [x] Changelog
- [x] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by natemellendorf** [comment]
Related to this [issue/request](https://github.com/saltstack/salt/issues/57182)

**Comment by natemellendorf** [comment]
All checks have passed. I believe this is ready for review.
If changes are needed, please let me know.
Thanks!

**Review by Akm0d — DISMISSED** [review]

**Comment by natemellendorf** [comment]
Good evening, @Akm0d and team!
I’m excited to see that Salt 3001 has just released. 

With that, please let me know if you need anything more before we can see this PR approved / merged in. Thanks in advance and have a great weekend!

**Comment by Akm0d** [comment]
@natemellendorf thank you for your PR :)  We're in a code freeze right now since sodium just released --  until July 8th.  You're PR will likely be merged towards the beginning of the Magnesium release after July 8th.

**Comment by natemellendorf** [comment]
@Akm0d 
Thanks for the insight! It looks like master is being updated again, so I'll try and keep tabs on this PR and keep it in sync with master. Let me know if anything else is needed.

Regards,

**Comment by natemellendorf** [comment]
Errors do not appear related to changes in this PR. Master branch is currently in a failed state. Once master is passing, I’ll rebase this with master to run tests again.

**Review by dwoz — APPROVED** [review]

**Pull request merged**
