### PR TITLE
Added AWS v4 signature support

### PR DESCRIPTION
**Pull request by forestvoyager**
This patch adds AWS v4 signature support and fixes issue #20518

### CODE REVIEW

**Comment by jfindlay** [comment]
@slinu3d, thanks for fixing this.  Will you also fix these [lint errors](https://jenkins.saltstack.com/job/salt-pr-lint-n/5151/violations/file/salt/cloud/clouds/ec2.py/)?  Thanks.

**Comment by slinu3d** [comment]
The lint error just does not make sense since there is a space after ',' for sure.

**Comment by jfindlay** [comment]
It's probably complaining about not having a space after the `:` characters.

**Comment by basepi** [comment]
@slinu3d Because of new features and changes in the 2015.5 branch, this fix is not merging forward cleanly. Could you please make these same changes in a pull request against the 2015.5 branch? Otherwise this fix will not continue into new releases of salt.

**Comment by slinu3d** [comment]
Created PR (https://github.com/saltstack/salt/pull/23547) for 2015.5.

**Comment by jfindlay** [comment]
Thanks @slinu3d.

**Comment by basepi** [comment]
Thanks!

**Pull request merged**
