### PR TITLE
Fix composer, issue #21349

### PR DESCRIPTION
**Pull request by ross-p**
Composer recently updated such that it does not produce any output.  That completely breaks the previous composer.py module/state which inspect stdout to determine success.  (Issue #21349)

This PR fixes it so that we rely on the exit code 0 to indicate success, regardless of what the output says or doesn't say.

Additionally, I've added the new state composer.update which will run `composer update` in the directory.  Doing so was virtually the same as running `composer.install` and so I refactored the code so as not to cut/paste a huge amount.

I modified the composer module such that it follows documented best practices like throwing exceptions instead of returning a string that you have to interpret whether it worked or not, and supporting `__opts__['test']`, etc.

### CODE REVIEW

**Comment by ross-p** [comment]
@cachedout @rallytime I saw you folks were involved with composer in the past, please take a look if you have time and let me know what you think.  Thanks  :)

**Comment by rallytime** [comment]
@ross-p This appears to be causing some merge-conflicts as I am trying to backport this. Would you mind taking a look at that and backporting the change to 2014.7?

**Comment by ross-p** [comment]
No problem, will do today.

**Comment by ross-p** [comment]
@rallytime I think that did it.

**Comment by rallytime** [comment]
Awesome! Thnanks @ross-p!

**Pull request merged**
