### PR TITLE
fix yamlloader.DuplicateKeyWarning leaking

### PR DESCRIPTION
**Pull request by sakateka**
`yamlloader.DuplicateKeyWarning` leaks through the external `warnings` module,
every time `LazyLoader` loads the `yamlloader` module,
`yamlloader` adds a new `DuplicateKeyWarning` class (with new address and hash)
to the internal list of warnings of the `warnings` module.

After this #8589 the code about adding warnings is dead code, so just delete it.

### What does this PR do?
Fixing memory leak in `yamlloader` and `yamlloader_old` modules.

### What issues does this PR fix or reference?
Fixes:
may be https://github.com/saltstack/salt/issues/61988

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Review by MKLeb — DISMISSED** [review]

**Review by twangboy — DISMISSED** [review]

**Review by dmurphy18 — APPROVED** [review]

**Comment by sakateka** [comment]
Hi, please tell me who will merge it, I can't do it myself.

**Comment by sakateka** [comment]
@dmurphy18 I don't have the right to merge it, can you merge?

**Comment by dmurphy18** [comment]
@sakateka I don't have merge rights either, but just re-reviewing this, QQ is the change already covered by existing tests ?, if not, it should have a test to show the fix is working.

**Comment by sakateka** [comment]
> change already covered by existing tests ?

This is just removing dead code, there is no impact on existing code.

**Comment by dmurphy18** [comment]
Updated PR with current master branch and re-running tests, if no fails will push to get it in -  got to fix those leaks

**Comment by dmurphy18** [comment]
@sakateka Can you look at the failing tests on Ubuntu 22.04.  I believe this might be due to directory changes on Ubuntu 22.04 from /usr/share to /etc/api. Take a look at @Ch3LL PR https://github.com/saltstack/salt/pull/62159, so might have to wait till this goes in and then re-run tests

**Comment by sakateka** [comment]
!merge

**Review by Ch3LL — APPROVED** [review]

**Review by garethgreenaway — APPROVED** [review]

**Review by twangboy — APPROVED** [review]

**Comment by sakateka** [comment]
`4 approvals` - It's very cool, but I can't merge, I don't have rights

image

**Comment by sakateka** [comment]
re-run pr-ubuntu-2204-amd64-py3-m2crypto-pytest
re-run pr-photon-3-x86_64-py3-pytes

**Pull request merged**
