### PR TITLE
Reduce mem leaks on py3 test runs & Py3 Fixes

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by cachedout** [comment]
@s0undt3ch Do you have a moment to look at the lint errors here? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/10557/violations/

**Comment by s0undt3ch** [comment]
I'm fixing those and also a brew test failure which happened to pass because it was reusing previous `@patch`es :/

Can we block `@patch` altogether?

**Comment by cachedout** [comment]
@s0undt3ch What do you mean by "block". Like, override it or just check for it in lint tests?

**Comment by s0undt3ch** [comment]
Check for it in lint and just deny its use

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by rallytime** [comment]
@s0undt3ch Looks like this needs to be rebased.

**Comment by s0undt3ch** [comment]
Rebased

**Pull request merged**
