### PR TITLE
[2018.3] Minion blackout tests - Add the missing, and required, top pillar file

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Review by waynew — APPROVED** [review]

**Comment by waynew** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
Tests passed, merging.

**Pull request merged**
