### PR TITLE
utils.http: catch requests exceptions and return error

### LINKED ISSUE #29162: salt.utils.http inconsistent http errors and Exception handling
If you're on Tornado backend, it just catches the HTTPError exception and returns with no exception:

```
        except tornado.httpclient.HTTPError as exc:
            ret['status'] = exc.code
            ret['error'] = str(exc)
            return ret
```

with requests backend, it just propagates exceptions:

https://github.com/saltstack/salt/blob/develop/salt/utils/http.py#L297

```
        result = sess.request(
            method, url, params=params, data=data, **req_kwargs
        )
        result.raise_for_status()
```

I think this needs to be consistently dealt. Wether the library should just propagates exceptions or circumvent them is up to the implementor, but that should be consistent. In my opinion, we should try to not throw exceptions for HTTP errors and just return responses.

### PR DESCRIPTION
**Pull request by jfindlay**
Fixes #29162.

### CODE REVIEW

**Comment by jejenone** [comment]
in the case of HTTPError we might still be interested in return text and headers - they're available at least in requests:

exception requests.HTTPError(url, code, msg, hdrs, fp)

Why not return them as we would with a 200 ?

**Comment by cachedout** [comment]
@jfindlay Please let me know when this one is ready to go.

**Comment by cachedout** [comment]
@jfindlay What's the story on this one?

**Comment by jfindlay** [comment]
@cachedout, I'll come back to this when I have time.

**Pull request closed without merging**
