### PR TITLE
Update states.chef for version 16.x and 17.x Chef Infra Client output

### LINKED ISSUE #61891: [BUG] salt.states.chef.client AttributeError: 'NoneType' object has no attribute 'group'
**Description**
When calling salt.states.chef.client against minions with Chef Infra Client version 16.17.18 or 17.9.18, the chef command will complete successfully on the minion, but the output on the master will throw "AttributeError: 'NoneType' object has no attribute 'group'". The reason is because of salt/states/chef.py L163
`regex = re.search(r"Chef Client finished, (\d+)", _summary(stdout), re.IGNORECASE)`

Version 16.x Chef Infra Client has the following output line at the end of a successful chef-client run:
`Chef Infra Client finished, 47 resources updated`

Version 17.x Chef Infra Client has the following output line at the end of a successful chef-client run:
`Infra Phase complete, 36 resources updated`

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)
```
cat /srv/salt/top.sls
base:
  '*':
    - chef

cat /srv/salt/chef/init.sls
cheffing:
  chef.client: []
```

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ X ] VM running on a cloud service, AWS EC2, Ubuntu 18.04 and 20.04
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)
salt '*' state.apply
...
----------
          ID: cheffing
    Function: chef.client
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2180, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1201, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/contextvars/__init__.py", line 38, in run
                  return callable(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1216, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1249, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/chef.py", line 92, in client
                  return _run(name, "chef.client", kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/chef.py", line 145, in _run
                  if _has_changes(result["stdout"]):
                File "/usr/lib/python3/dist-packages/salt/states/chef.py", line 164, in _has_changes
                  return int(regex.group(1)) > 0
              AttributeError: 'NoneType' object has no attribute 'group'
     Started: 00:20:04.915861
    Duration: 45899.217 ms
     Changes:

**Expected behavior**
There should be no AttributeError and the stdout output should be displayed since the chef.client completed successfully with a retcode of 0.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
salt -V
Salt Version:
          Salt: 3004.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 0.28.3
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: 1.0.3
        Python: 3.8.10 (default, Mar 15 2022, 12:22:08)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.13.0-1019-aws
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Additional context**
Versions 16.x and 17.x of Chef Infra Client are the currently supported versions, any earlier versions are EOL. I plan to open a PR with the suggested fix as follows:
```
diff --git a/salt/states/chef.py b/salt/states/chef.py
index b511a95d5b..f3921dc8a5 100644
--- a/salt/states/chef.py
+++ b/salt/states/chef.py
@@ -160,5 +160,5 @@ def _summary(stdout):
 
 
 def _has_changes(stdout):
-    regex = re.search(r"Chef Client finished, (\d+)", _summary(stdout), re.IGNORECASE)
-    return int(regex.group(1)) > 0
+    regex = re.search(r"Infra \w+ (complete|finished), (\d+)", _summary(stdout), re.IGNORECASE)
+    return int(regex.group(2)) > 0
```

### PR DESCRIPTION
**Pull request by ericham**
### What does this PR do?
Update the regex search for output lines of Chef Infra Client versions 16.x and 17.x to not throw "              AttributeError: 'NoneType' object has no attribute 'group'".

### What issues does this PR fix or reference?
Fixes: #61891 

### Previous Behavior
The regex searched for "Chef Client finished, (\d+)" which appears to match some EOL version of Chef Infra Client. The currently supported versions of Chef Infra Client are 16.x and 17.x which no longer output this line at the end of a chef-client run.

### New Behavior
The regex now searches for "Infra \w+ (complete|finished), (\d+)" which will match the output as follows:

Version 16.x Chef Infra Client has the following output line at the end of a successful chef-client run:
`Chef Infra Client finished, 47 resources updated`

Version 17.x Chef Infra Client has the following output line at the end of a successful chef-client run:
`Infra Phase complete, 36 resources updated`

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

~- [ ] Docs~
- [x] Changelog - https://docs.saltproject.io/en/master/topics/development/changelog.html
- [x] Tests written/updated

I have applied these changes successfully on my Ubuntu 18.04 and 20.04 minions, the AttributeError no longer occurs and the stdout is displayed correctly. I'm not sure if a new or existing test needs to be written or updated.

### Commits signed with GPG?
No

Please review [Salt's Contributing Guide](https://docs.saltproject.io/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by ericham** [comment]
As to the `needs-changelog-file` label, I did include `changelog/61891.fixed` in this PR, is that not the correct way to do it?

As to the `Needs-Testcase`, I see there is `salt/tests/pytests/unit/states/test_chef.py`. However, I am new to unit tests and I'm not sure what I'm looking at here. Does this existing test cover my change? Or do I need to modify this test somehow or create a brand new test?

**Comment by garethgreenaway** [comment]
@ericham Apologies.  I missed that there was in fact a changelog included with the PR.

**Comment by garethgreenaway** [comment]
@ericham Looking at the changes and the current tests, this would require additional test coverage.  Another concern would be whether support needs to be preserved for previous versions of Chef with the current test.

**Comment by ericham** [comment]
I've changed the regex to maintain the original version output and add my changes to support the 2 current versions of Chef.

"(Chef Client finished|Chef Infra Client finished|Infra Phase complete), (\d+)"

Previous versions
`Chef Client finished, 45 resources updated`
Version 16.x
`Chef Infra Client finished, 56 resources updated`
Version 17.x
`Infra Phase complete, 67 resources updated`

I plan to attend the Twitch Test Clinic tomorrow to get help on writing the test case.

**Comment by waynew** [comment]
This PR is also blocked by #61919 - when that's merged (and tests a la test-clinic) have been added this should be ready for a re-review :+1:

**Comment by ericham** [comment]
@waynew thanks again for all the help today in the Twitch Test Clinic, I've cherry-picked your 2 commits to add the necessary unit test.

**Comment by waynew** [comment]
@ericham #61919 was fixed, so if all goes well everything should be :+1: and this should be ready for a re-review/merge later today :tada:

**Comment by ericham** [comment]
@waynew  after your merge there were 2 tests that failed, I decided to merge from master again as there were more commits outstanding, and now there is 1 failing test. So not sure if there is still an issue in the test suite or something with my code?

**Comment by waynew** [comment]
For some of the tests I had to (re)approve and run, so those are going now :+1:

**Comment by ericham** [comment]
@waynew I merged from master again and got 27 successful tests, I believe the 6 expected checks get triggered on review?

@garethgreenaway I believe this is ready for review now as the `Needs-Testcase` label has been satisfied with Wayne's help on the unit test.

**Comment by ericham** [comment]
@dwoz I see you're assigned as the reviewer, I believe this is ready now to be reviewed? If not, please let me know what else I need to complete.

**Review by Ch3LL — APPROVED** [review]

**Pull request merged**
