### PR TITLE
Lxc seeding

### PR DESCRIPTION
**Pull request by kiorky**
refs #23772 #23847

On a bare minion, do no seed by default if not using runner, first or a pr serie

### CODE REVIEW

**Comment by kiorky** [comment]
should be applied before #23807 #23808

**Comment by kiorky** [comment]
please hold on merge, i have few commits more for systemd based containers

**Comment by kiorky** [comment]
@terminalmage PTAL now, seems a bit more stable.

**Comment by kiorky** [comment]
wont be approved.

**Comment by basepi** [comment]
See my comment here: https://github.com/saltstack/salt/pull/23805#issuecomment-103238312

**Comment by basepi** [comment]
@kiorky Please wait for #23893 then you can make your changes on top.

**Comment by kiorky** [comment]
@basepi this is to go on 2015.5, not on develop here O;0

**Comment by basepi** [comment]
Same as the other one, I thought all four were develop-related. Sorry for the confusion.

**Comment by basepi** [comment]
This appears to be fine.

**Comment by kiorky** [comment]
only #23808 which is a clever editing and merge from all the 2015.5 pr

**Comment by kiorky** [comment]
i know what a merge forward is, but come on, that's not appliable to any case.

**Comment by basepi** [comment]
I already apologized, it was just a miscommunication.

**Comment by kiorky** [comment]
You can check all the commits from #23808 (that i now need to reedit) but rally, ... i take care of that and that's not for nothing ;)
@basepi no problem, it's more on the Erik position, i really dont see the point where there is a point of divergence, anyway the merge forward wont work, so 2 aside PRs with already cherrypicked commits would do the same and ensure next merge forwards not to conflict, i really do not understand the problem here.

**Comment by kiorky** [comment]
so next is #23807 and i now need to check it's ok with all that mess ;)

**Comment by basepi** [comment]
Hmmm, I have a feeling that even with your develop changes it would still conflict on the merge forward. I think Erik is done for the night so we may have to pick this up tomorrow. There was some miscommunication, and a lack of patience on both yours and Erik's part that caused some frustration. Everyone needs to be more patient and try to communicate better.

**Comment by kiorky** [comment]
at least, you have the winner by doing a git show salt/modules/lxc.py on my last develp changeset instead of blindly trying to merge it :)

**Comment by basepi** [comment]
I'm leaning towards still having you wait on the develop changes. When I merge forward (and it conflicts) I will just take the develop version. Then have you do your pull request on top of that. That will definitely prevent merge conflicts, and I think will be the cleanest way to proceed (even if it's not the fastest way to prceed). Does that sound OK?

**Comment by basepi** [comment]
Because even if you try to make it not conflict, I bet it still conflicts. It's hard to get it exactly the same to prevent conflicts. =\

**Comment by basepi** [comment]
(FYI, I'm leaving the office right now, I may or may not be able to discuss more until tomorrow morning)

**Comment by kiorky** [comment]
the problem is not that it is not the fastest, but it is too tedious to have to wait between too interdependant changesets, with no eta on that, as in between, i just will forget what are the real details of divergence.

If i have aside, and preferrably mostly identical changesets, at least, nothing got lost in the netsplit and the contribution is done in a reasonnable timeframe.

**Comment by kiorky** [comment]
cc @basepi

**Comment by basepi** [comment]
@kiorky That's all well and good in theory, but I still request that you follow instructions. I know you want to get your fixes in as efficiently as possible, but we've been working to slow large changes down to prevent breakage.

**Comment by kiorky** [comment]
@basepi i really dont see the point, and even here github is more smarter than you, once the 2015.5 PR will be merged, only the commits which are diverging will appear on the develop tracked pull request, ensuring that we can track down what's is left to be done on the develop related code...

I'm not asking about merging concurrently, but on letting open the PR simultaneously to have both changesets, on both side, which certains are differents, and where they will be tracked by tools that know correctly how to do it.

**Pull request merged**
