### PR TITLE
More VM tuning in virt module and states

### PR DESCRIPTION
**Pull request by cbosdo**
### What does this PR do?

In order to be able to create big performance-optimized VM, we need to expose more parameters like the kvm `hint-dedicated` feature flag or the clock configuration.

This pull request also includes a few follow up fixes from PR #58196.

### Merge requirements satisfied?
- [X] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [X] Tests written/updated

### Commits signed with GPG?
Yes

### CODE REVIEW

**Comment by cbosdo** [comment]
@krionbsd no need to hurry up reviewing this one before PR #58196 is merged ;)

**Comment by cbosdo** [comment]
@krionbsd now the PR has been rebased, and you can review it, unless @Akm0d wants to look into it since he reviewed already a number of virt-related PRs of mine

**Review by krionbsd — APPROVED** [review]

**Comment by cbosdo** [comment]
rerun centos7/tcp/pytest

**Comment by cbosdo** [comment]
re-run pr-centos8-py3-pytest

**Comment by cbosdo** [comment]
re-run pr-freebsd122-py3-pytest

**Comment by cbosdo** [comment]
@dwoz could you merge this follow up PR for the virt module?

**Pull request merged**
