### PR TITLE
Adding reg.py unit test

### PR DESCRIPTION
**Pull request by rahulhan**
Adding reg_test.py

### CODE REVIEW

**Comment by rallytime** [comment]
Many of these test failures look similar to the ones that were introduced to the develop branch when #22143 was merged, but it would be good to be sure that there are different ones sneaking in here. 

@rahulhan Can you rebase this pull request to the HEAD of develop once #22189  is merged so we can run the tests cleanly?

**Comment by rahulhan** [comment]
@rallytime Yeah sure.

**Comment by rahulhan** [comment]
@rallytime <https://github.com/rallytime> #22189
<https://github.com/saltstack/salt/pull/22189> was deleted, I'm not very
sure what is to be done. Can you please explain.
And also what is to be done for pull request #22186
<https://github.com/saltstack/salt/pull/22186> , #22184
<https://github.com/saltstack/salt/pull/22184> , #22143
<https://github.com/saltstack/salt/pull/22143>.

I follow the following steps to create new pull request :-

git branch
git checkout develop
git fetch upstream
get rebase develop
git pull upstream develop
git checkout -b state_unit_test
git status
git add unit/modules/state_test.py
git commit -m "Adding state.py unit test"
git push origin state_unit_test

**Comment by jfindlay** [comment]
@rahulhan, if you want to pick up new changes on develop, you'll need to do `git rebase upstream/develop` after `git fetch upstream`.  Or you could also do,
```
git fetch upstream
git checkout -b state_unit_test upstream/develop
```

**Comment by jfindlay** [comment]
To rebase this branch as @rallytime suggests, you can do
```
git fetch upstream
git checkout reg_unit_test
git rebase upstream/develop
git push --force origin reg_unit_test  # carefully
```

**Comment by rahulhan** [comment]
Thanks @jfindlay . Should i do the same for #22186 and #22143 ? I guess #22143 is deleted.

**Comment by rallytime** [comment]
@rahulhan If you could do the same for #22186, that would be great. For #22143, you'll need to submit that pull request again. #22143 was the one that was causing these test failures, but I am not sure why yet. We'll have to take a closer look to see what's going on. Would you mind resubmitting the changes you made in #22143 in a new pull request?

**Comment by rahulhan** [comment]
@rallytime Yeah sure i'll resubmit #22143 and also #22186. Thanks

**Comment by rahulhan** [comment]
@rallytime Will resubmit.

**Pull request closed without merging**
