### PR TITLE
Nested outputter colors depending on the function retcode

### PR DESCRIPTION
**Pull request by mirceaulinic**
As discussed under #44485, it would be nice that the colors
of the nested outputter to depend on the execution function
retcode (from the __context__, when available).
If the retcode is non-zero, the output will be mostly red
to emphasise that's an error.

Well, it's not that easy as I expected, so the `__context__` dict is empty inside the outputter.
It looks like the `__context__` should be passed to this function: https://github.com/saltstack/salt/blob/develop/salt/loader.py#L387 but I'm not sure where this function should be called with the context. Any input would be much appreciated, no rush. Thanks!

PS. for the record this is how the color scheme would look like (some output hidden):

screen shot 2017-11-14 at 13 55 56

### CODE REVIEW

**Comment by mirceaulinic** [comment]
Pinging @saltstack/team-core: nothing urgent here, but it would be great if you could take a few moments to look into this, and give me a hint. Thanks!

**Comment by rallytime** [comment]
I think this is a neat idea! I have asked @cachedout to review this. Some tests for this change would be a good idea as well.

**Review by cachedout — APPROVED** [review]

**Comment by cachedout** [comment]
I have no issue with this. I think it looks good but would like to see tests for this before we get it in.

**Comment by mirceaulinic** [comment]
Thanks for reviewing this @rallytime @cachedout.
I'm afraid I failed again to explain this properly: the code in this branch is incomplete as the `__context__` dunder is not not available in the outputters. The screenshot I shared is just how it _would_ look like (I just hardcoded `__context__['retcode'] = 1` in my hacks.

Could you please ping someone to show me how to make the context available in the outputters (if that would make sense, of course)? Thanks!

**Comment by mirceaulinic** [comment]
Okay, I think I found it: the cli caller has the retcode already (otherwise will assume it's 0 so it won't change any colors and so).
I'm passing this value to the outputter function under the `_retcode` key in the kwargs (with `_` just to avoid messing with any eventual values that may be there, even though it just `retcode` should be equally safe): https://github.com/saltstack/salt/pull/44533/commits/b3d86fd0991b1f218d8d8b83ef6059e326694326

And it seems to be working fine (without any hacks):

screen shot 2017-12-06 at 23 01 29

Please let me know if my changes make sense, if so I will start working on the tests.

**Comment by mirceaulinic** [comment]
Alright, I've also added some test cases: https://github.com/saltstack/salt/pull/44533/commits/e22295c0c6c64c680bf27be1123ed542b7b46825

**Comment by mirceaulinic** [comment]
Bump @rallytime @cachedout - that's my last PR for Oxygen :)

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
re-run centos

**Review by gtmanfred — APPROVED** [review]

**Pull request merged**
