### PR TITLE
tornado50 merge forward for 2018.3

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
### What does this PR do?
#47106 has a lot of conflicts with #46002 so I've merged that my PR forward.

### Previous Behavior
@rallytime :'-(

### New Behavior
@rallytime :-D

### CODE REVIEW

**Comment by rallytime** [comment]
Thanks @DmitryKuzmenko! You rock!

**Comment by gtmanfred** [comment]
This is failing with ```
  File "/tmp/salt-tests-tmpdir/scripts/cli_minion.py", line 27, in <module>
    salt_minion()
  File "/tmp/kitchen/testing/salt/scripts.py", line 181, in salt_minion
    minion.start()
  File "/tmp/kitchen/testing/salt/cli/daemons.py", line 343, in start
    super(Minion, self).start()
  File "/tmp/kitchen/testing/salt/utils/parsers.py", line 1036, in start
    self.prepare()
  File "/tmp/kitchen/testing/salt/cli/daemons.py", line 320, in prepare
    self.minion = salt.minion.MinionManager(self.config)
  File "/tmp/kitchen/testing/salt/minion.py", line 926, in __init__
    install_zmq()
  File "/tmp/kitchen/testing/salt/utils/zeromq.py", line 51, in install_zmq
    zmq.eventloop.ioloop.install()
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/ioloop.py", line 195, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'
01:01:14,382 [salt.log.setup                           :1165][ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: type object 'IOLoop' has no attribute 'initialized'
Traceback (most recent call last):
  File "/tmp/salt-tests-tmpdir/scripts/cli_minion.py", line 27, in <module>
    salt_minion()
  File "/tmp/kitchen/testing/salt/scripts.py", line 181, in salt_minion
    minion.start()
  File "/tmp/kitchen/testing/salt/cli/daemons.py", line 343, in start
    super(Minion, self).start()
  File "/tmp/kitchen/testing/salt/utils/parsers.py", line 1036, in start
    self.prepare()
  File "/tmp/kitchen/testing/salt/cli/daemons.py", line 320, in prepare
    self.minion = salt.minion.MinionManager(self.config)
  File "/tmp/kitchen/testing/salt/minion.py", line 926, in __init__
    install_zmq()
  File "/tmp/kitchen/testing/salt/utils/zeromq.py", line 51, in install_zmq
    zmq.eventloop.ioloop.install()
  File "/usr/lib64/python2.7/site-packages/zmq/eventloop/ioloop.py", line 195, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'
```

When using pyzmq 17.0.0 and tornado 5.0.2 for the test suite.

**Comment by DmitryKuzmenko** [comment]
@gtmanfred could you please double check the error case. What is `import zmq; zmq.__version__` output in that case.
I'm asking because the fail appears here:
https://github.com/saltstack/salt/blob/2afe4bee95fe78e9cdfa53c6b3958a66adf2fc26/salt/utils/zeromq.py#L50-L51
Where we check for the ZMQ version before do this.
Probably you've used ZeroMQ<17.0 with Tornado>=5.0 that is incorrect case because ZeroMQ has Tornado50 compatibility fixes only from 17.0 version.

**Review by gtmanfred — APPROVED** [review]

**Comment by gtmanfred** [comment]
Yup, it looks like our salt states didn't actually run the `python.pyzmq`, I will fix that for our tornado 50 states, to make sure we are also testing pyzmq 17 on that as well.

**Comment by DmitryKuzmenko** [comment]
Good catches @gtmanfred thank you for taking care of this!

**Comment by gtmanfred** [comment]
My pleasure, enjoy your time off!

**Pull request merged**
