### PR TITLE
Fix minor issues with #42572

### PR DESCRIPTION
**Pull request by terminalmage**
See https://github.com/saltstack/salt/pull/42572#pullrequestreview-55270580

### CODE REVIEW

**Review by rallytime — APPROVED** [review]

**Comment by damon-atkins** [comment]
Suggest salt/cli/call.py is reviewed.
e.g.
`self.config['file_roots'] = {'base': _expand_glob_path([file_root])}`
From PY2
```
>>> a={'hello': 'fred'}
>>> print a['hello']
fred
>>> print a[u'hello']
fred
>>> a={u'hello': u'fred'}
>>> print a['hello']
fred
>>> a
{u'hello': u'fred'}
```

Also suggest looking at salt/utils/parsers.py
Somewhere in here for PY2 I suspect you need to take each string/bytes on the command line.
`decode(__salt_system_encoding__)` turning it into Unicode.   As the console  text on the command line will be `__salt_system_encoding__`   vs SLS files and Salt Code which are utf8

**Comment by terminalmage** [comment]
@damon-atkins Sorry, but I don't understand what you're talking about. The last PR didn't change unicode handling in `salt/cli/call.py`.

**Comment by damon-atkins** [comment]
@terminalmage OK.  I will wait for the other PR to appear for u prefixing, etc.  Thanks

**Comment by terminalmage** [comment]
@damon-atkins Just FYI, there will be a number of PRs coming in to add the `u`  prefixing, due to the fact that we have a couple thousand .py files to modify.

**Pull request merged**
