### PR TITLE
Added the ability to change the "hostname" on windows minions

### PR DESCRIPTION
**Pull request by opdude**
Setting the computer name didn't serve my purpose well so added the ability to set the hostname as well :)

### CODE REVIEW

**Comment by cachedout** [comment]
@opdude There are some minor lint errors in one of the tests you wrote. Could you fix those up and then we'll get this merged? Thanks.

**Comment by cachedout** [comment]
@opdude You're quick! Thank you!

**Comment by opdude** [comment]
;) No problem, thanks for merging

**Comment by twangboy** [comment]
@opdude Do you mind my asking what the problem is with set_computer_name? Is the function not working correctly?

**Comment by opdude** [comment]
@twangboy In this case I wanted to set the hostname specifically because setting the computer name didn't change the automatic minion name, but changing the hostname directly seemed to work better for that

**Pull request merged**
