### PR TITLE
salt-cloud provider for libvirt

### LINKED ISSUE #12908: feature request: use libvirt as a provider for salt-cloud
Salt-virt is good and all, but i think it makes sense to be able to use libvirt as a provider for salt-cloud. This would make manageing different providers and local libvirt setups easier to maintain without having to set up something like openstack.

Heres a selective cut and paste from the relevant discussion on #salt irc.

09:57 < mortis> anyone know if its possible / will be possible (in the future) to use libvirt as a provider for salt-cloud?
10:13 < jcockhren> mortis: yeah. salt-cloud was merged into salt
10:13 < jcockhren> you mean like a backport?
10:14 < mortis> jcockhren: yeah, thats really nice, and im thinking ...if you could use salt-cloud with libvirt as a provider, you could manage vms in
                the cloud or on your local libvirt setup without having to go for something like openstack
10:17 < jcockhren> mortis: hm. I'm not seeing a libvirt module. I see a runner
10:17 < jcockhren> I don't know/see of any reason why that couldn't be added
10:18 < mortis> hm yeah
10:18 < jcockhren> ah. I see the module
10:18 < mortis> wouldnt it be simpler to relate to only salt-cloud and not salt-cloud and salt-virt together?
10:19 < mortis> just an idea
10:20 < jcockhren> well. the underlying functionality is already persent in modules.virt
10:20 < jcockhren> it'll make sense to build the salt-cloud extras on top of that
10:21 < jcockhren> in fact, that basically how eveything works: built on top of modules
10:21 < jcockhren> as a provider, have salt-cloud make the right calls to module.virt
10:23 < mortis> that would be really cool
10:23 < mortis> i wonder if that is something i should make a github feature request from..
10:23 < jcockhren> yep
10:23 < mortis> ill try, and see what response it gets

### PR DESCRIPTION
**Pull request by rklaren**
### What does this PR do?

Add salt-cloud provider for libvirt.
### What issues does this PR fix or reference?

Fixes: #12908
### Tests written?

No. Bit tricky with the setup needed. I'm willing to investigate this though.

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html) for best practices.

### CODE REVIEW

**Comment by techhat** [comment]
+1

**Comment by cachedout** [comment]
@rklaren Wow! This is great!

There are some minor style issues outlined here: https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/5730/violations/file/salt/cloud/clouds/libvirt.py/

If you could fix those up, I think we can get this in. Thanks!

**Comment by rklaren** [comment]
@cachedout I tweaked things for the pylint warnings. I disabled one pylint check for a place where I want cleanups to happen as much as possible, since it's very inconvenient to clean up orphan disks (and vm's) if something unexpected goes wrong. Hope things are ok like this. Feedback is of course welcome :)

**Comment by cachedout** [comment]
@rklaren You actually left this comment right while I was reviewing. Yes, disabling the pylint check was the right thing to do I think. Thanks so much for this submission. It's excellent!

**Comment by rklaren** [comment]
@cachedout Thanks for merging!

**Pull request merged**
