### PR TITLE
Fix ipset state with multiple entries and subtypes separated with comma

### PR DESCRIPTION
**Pull request by skjaro**
### What does this PR do?
Fix for problem with adding multiple entries in ipset state and subtypes separated with comma like:
bitmap:ip,mac

### What issues does this PR fix or reference?
#39552
#44298

### Tests written?

No

### Commits signed with GPG?

No

### CODE REVIEW

**Comment by cachedout** [comment]
@skjaro can you please make the changes outlined here? https://jenkins.saltstack.com/job/PR/job/salt-pr-lint-n/16074/violations/file/salt/modules/ipset.py/

**Comment by skjaro** [comment]
@cachedout I fix this lint violation, maybe would be better to move this fix to 2017.7 branch.

**Comment by cachedout** [comment]
@skjaro I will mark this for backporting so that it gets into 2017.7.

**Comment by Xiami2012** [comment]
Glad to see this got resolved finally. 😄

**Pull request merged**
