### PR TITLE
[PyTest] Add `LoaderModuleMockMixin` pytest replacement code & Update docs

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title
### What issues does this PR fix or reference?
Refs: https://github.com/saltstack/salt/pull/55890

### CODE REVIEW

**Comment by s0undt3ch** [comment]
re-run full all

**Review by cmcmarrow — APPROVED** [review]

**Comment by dwoz** [comment]
re-run full all

**Comment by s0undt3ch** [comment]
If the tests were passing and you ran tests again, and so far we have no failures, why does your script day it has failing tests @dwoz?

**Comment by dwoz** [comment]
> If the tests were passing and you ran tests again, and so far we have no failures, why does your script say it has failing tests @dwoz?

I don't think they were passing.

**Comment by s0undt3ch** [comment]
> I don't think they were passing.

They were. This morning I left all the PRs I linked in Slack in a passing state.

**Comment by dwoz** [comment]
> > I don't think they were passing.
> 
> They were. This morning I left all the PRs I linked in Slack in a passing state.

Looks like if there are in-progress builds the script will set the `has-test-failure` label, not ideal. I will update the script when I have some time.

**Comment by s0undt3ch** [comment]
Yeah, that's what I thought too.

**Pull request merged**
