### PR TITLE
[#40971] Fix TypeError: must be str, not bytes for ssh_py_shim

### PR DESCRIPTION
**Pull request by ezh**
salt-ssh '*' test.ping
...
[DEBUG   ] RETCODE localhost: 1
[DEBUG   ] SHIM retcode(1) and command: Traceback (most recent call last):
[DEBUG   ] LazyLoaded raw.output
{'ezh': {'stdout': 'Traceback (most recent call last):\n  File "<string>", line 155, in <module>\n  File "<string>", line 264, in <module>\n  File "<string>", line 251, in main\nTypeError: must be str, not bytes', 'retcode': 1, 'stderr': 'command-line line 0: Unsupported option "gssapiauthentication"\r\nConnection to localhost closed.\r\n'}

### What does this PR do?

Fix TypeError in SSH SHIM

### What issues does this PR fix or reference?

#40971

### Tests written?

No

### CODE REVIEW

**Comment by gtmanfred** [comment]
Thanks for the PR, can you rebase this against our nitrogen release branch?  This will be our next major release and the first where we are fully supporting py3.

Thanks,
Daniel

**Comment by ezh** [comment]
@gtmanfred Is develop branch are outside of Python 3?
I ask this because some patches are going to one branch and other patches go to other branch.
1. I don't want that some changes are lost
2. Is it possible to merge it to develop and then backport to release?
3. All my fixes are Python 2 compatible
Or will this PR be backported to develop branch from the nitrogen one?

**Comment by gtmanfred** [comment]
We merge forward all commits.

So if you make it against nitrogen, all of the nitrogen commits will be merged forward to develop.

https://github.com/saltstack/salt/pull/40956 This is an example.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Here is a guide on how we do our management.
https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch

Thanks,
Daniel

**Comment by ezh** [comment]
@gtmanfred done, Jenkins failures have no relation to code

**Pull request merged**
