### PR TITLE
Add new module to release notes for 2019.2.0

### PR DESCRIPTION
**Pull request by sdodsley**
### What does this PR do?
Add a new module to the 2019.2.0 Release Notes

### CODE REVIEW

**Review by terminalmage — APPROVED** [review]

**Comment by terminalmage** [comment]
Needs to be backported to 2019.2.

**Comment by sdodsley** [comment]
@terminalmage will do when this is merged to develop

**Comment by dwoz** [comment]
@sdodsley Please cherry-pick this to 2019.2

**Comment by sdodsley** [comment]
@dwoz Cherry-pick submitted: #51761

**Pull request merged**
