### PR TITLE
fix: Replace `get_returns_noblock` function with `def get_returns_raw…

### LINKED ISSUE #56273: Salt minion sometime return empty ret dict and it fails if failhard set to True
### Description of Issue
So Salt has this logic for batch execution: https://github.com/saltstack/salt/blob/master/salt/cli/batch.py#L246-L259

I have an orchestration, with batch and `failhard` set to `True` and sometimes get this exception:
```
2020-02-28 14:59:44,383 [salt.state] [ERROR]  An exception occurred in this state: Traceback (most recent call last):
  File "/opt/behavox/salt/venv/lib/python3.6/site-packages/salt/state.py", line 1933, in call
    **cdata['kwargs'])
  File "/opt/behavox/salt/venv/lib/python3.6/site-packages/salt/loader.py", line 1951, in wrapper
    return f(*args, **kwargs)
  File "/opt/behavox/salt/venv/lib/python3.6/site-packages/salt/states/saltmod.py", line 331, in state
    cmd_ret = __salt__['saltutil.cmd'](tgt, fun, **cmd_kw)
  File "/opt/behavox/salt/venv/lib/python3.6/site-packages/salt/modules/saltutil.py", line 1503, in cmd
    client, tgt, fun, arg, timeout, tgt_type, ret, kwarg, **kwargs)
  File "/opt/behavox/salt/venv/lib/python3.6/site-packages/salt/modules/saltutil.py", line 1467, in _exec
    for ret_comp in _cmd(**cmd_kwargs):
  File "/opt/behavox/salt/venv/lib/python3.6/site-packages/salt/client/__init__.py", line 574, in cmd_batch
    for ret in batch.run():
  File "/opt/behavox/salt/venv/lib/python3.6/site-packages/salt/cli/batch.py", line 258, in run
    if self.opts.get('failhard') and data['retcode'] > 0:
KeyError: 'retcode'
```

So I dig in and printed the `minion` and `data` variables from this logic during error and the problem was that for one minion data is `{'ret': {}}`.

I checked this minions logs and see that it has finished its logic correctly and sent the results back to master:
``` 
2020-02-28 14:56:08,445 [salt.minion] [INFO] [JID: 20200228145436184480] Returning information for job: 20200228145436184480
```

### Steps to Reproduce Issue
It's flapping and looks like only happening during the load.

### Versions Report
Same for master and minion.
```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: 0.4.5
         PyYAML: 3.11
          PyZMQ: 18.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

### PR DESCRIPTION
**Pull request by GLaN1K**
### What does this PR do?

In case of batch jobs execution we use iteration over generator from `def get_returns_no_block`
`salt/venv/lib/python3.6/site-packages/salt/client/__init__.py`
```
    # TODO: tests!!
    def get_returns_no_block(self, tag, match_type=None):
        """
        Raw function to just return events of jid excluding timeout logic
        Yield either the raw event data or None
        Pass a list of additional regular expressions as `tags_regex` to search
        the event bus for non-return data, such as minion lists returned from
        syndics.
        """
        while True:
            raw = self.event.get_event(
                wait=0.01,
                tag=tag,
                match_type=match_type,
                full=True,
                no_block=True,
                auto_reconnect=self.auto_reconnect,
            )
            yield raw
```
First of the problems here is:
```
wait=0.01,
no_block=True,
```
In case of `no_block=True` here, `wait=0.01` will be omitted inside of `def get_event`:
`salt/venv/lib/python3.6/site-packages/salt/utils/event.py`
```
     if no_block is True:
            wait = 0
        elif wait == 0:
            # If no_block is False and wait is 0, that
            # means an infinite timeout.
            wait = None
```
Second problem is what `no_block=True` leads to race condition
Like, here we have in iterator over generator which was returned by `def get_returns_no_block`:
`salt/venv_bkp/lib/python3.6/site-packages/salt/client/__init__.py`
```
while True:
    # Process events until timeout is reached or all minions have returned
    for raw in ret_iter:
```
Despite the fact what minion successfully executed job and returned the result, that generator may never return it (due to race condition) and eventually logic inside of that `while True` loop will go into timeout clause:
```
            if time.time() > timeout_at and minions_running:
                log.debug("its timed out")
                # since this is a new ping, no one has responded yet
                log.debug("go to gather job info")
                jinfo = self.gather_job_info(
                    jid, list(minions - found), "list", **kwargs
                )
```
Which will try to check if job is already running (it's not, because it was already finished and due to `no_block=True` race condition `def get_returns_no_block` never returned it's result)
And will fail with exception like in https://github.com/saltstack/salt/issues/56273
```
020-02-28 14:59:44,383 [salt.state] [ERROR]  An exception occurred in this state: Traceback (most recent call last):
  File "/opt/behavox/salt/venv/lib/python3.6/site-packages/salt/state.py", line 1933, in call
    **cdata['kwargs'])
  File "/opt/behavox/salt/venv/lib/python3.6/site-packages/salt/loader.py", line 1951, in wrapper
    return f(*args, **kwargs)
  File "/opt/behavox/salt/venv/lib/python3.6/site-packages/salt/states/saltmod.py", line 331, in state
    cmd_ret = __salt__['saltutil.cmd'](tgt, fun, **cmd_kw)
  File "/opt/behavox/salt/venv/lib/python3.6/site-packages/salt/modules/saltutil.py", line 1503, in cmd
    client, tgt, fun, arg, timeout, tgt_type, ret, kwarg, **kwargs)
  File "/opt/behavox/salt/venv/lib/python3.6/site-packages/salt/modules/saltutil.py", line 1467, in _exec
    for ret_comp in _cmd(**cmd_kwargs):
  File "/opt/behavox/salt/venv/lib/python3.6/site-packages/salt/client/__init__.py", line 574, in cmd_batch
    for ret in batch.run():
  File "/opt/behavox/salt/venv/lib/python3.6/site-packages/salt/cli/batch.py", line 258, in run
    if self.opts.get('failhard') and data['retcode'] > 0:
KeyError: 'retcode'
```

So, probably the most correct solution will be fixing something inside of `def get_event` to make it not lost events in case of `no_block=True`, but unfortunately i can't do that and i can't see any reason why we use `no_block: True` at all for that case (also, `def get_returns_no_block` is not used _anywhere_ else in salt code except that case)

So, here is my PR which remove `no_block=True`
 
### What issues does this PR fix or reference?
Fixes https://github.com/saltstack/salt/issues/56273

### Previous Behavior
`def get_returns_noblock` used in batch execution leads to race condition where job result never returns 

### New Behavior
Without `no_block` (which is `False` by default) and by removing `wait: 0.01` (to make it default value - `5`) race condition is eliminated (at least now it's significantly more rare, can’t reproduce anymore)

### Merge requirements satisfied?
**[NOTICE] Bug fixes or features added to Salt require tests.**

- [ ] Docs
- [ ] Changelog - https://docs.saltstack.com/en/master/topics/development/changelog.html
- [ ] Tests written/updated

### Commits signed with GPG?
Yes

Please review [Salt's Contributing Guide](https://docs.saltstack.com/en/master/topics/development/contributing.html) for best practices.

See GitHub's [page on GPG signing](https://help.github.com/articles/signing-commits-using-gpg/) for more information about signing commits with GPG.

### CODE REVIEW

**Comment by Oloremo** [comment]
@garethgreenaway Please remind us how to re-run a specific test. I don't think it's reasonable to re-run the whole CI due to a single failed test, since it costs you, folks, some money.

**Comment by garethgreenaway** [comment]
I restarted the Ubuntu 20.04 test.

**Comment by GLaN1K** [comment]
How to reproduce original issue:

Cluster topology: 
1 master
30 minions

1) Create formula:
```
debug:
  cmd.run:
    - name: /bin/true
```
2) Create orch:
```
orch.debug:
  salt.state:
    - tgt: '*'
    - sls:
      - formula.debug
    - batch: 10
    - queue: true
```
3) Do orch execution in a loop with break on failure:
```
while true; do salt-run -c salt/ state.orchestrate  orch.debug pillar="$(cat /tmp/pillars.json)" -l debug  || break ; sleep 1; done
```
4) After 3-4 runs you should get this error:
```
xtb-rm-01.aws.internal_master:
----------
          ID: orch.debug
    Function: salt.state
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/opt/behavox/salt/venv/lib64/python3.6/site-packages/salt/state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/opt/behavox/salt/venv/lib64/python3.6/site-packages/salt/loader.py", line 2087, in wrapper
                  return f(*args, **kwargs)
                File "/opt/behavox/salt/venv/lib/python3.6/site-packages/salt/states/saltmod.py", line 327, in state
                  cmd_ret = __salt__["saltutil.cmd"](tgt, fun, **cmd_kw)
                File "/opt/behavox/salt/venv/lib/python3.6/site-packages/salt/modules/saltutil.py", line 1657, in cmd
                  fcn_ret = _exec(client, tgt, fun, arg, timeout, tgt_type, ret, kwarg, **kwargs)
                File "/opt/behavox/salt/venv/lib/python3.6/site-packages/salt/modules/saltutil.py", line 1609, in _exec
                  for ret_comp in _cmd(**cmd_kwargs):
                File "/opt/behavox/salt/venv/lib64/python3.6/site-packages/salt/client/__init__.py", line 586, in cmd_batch
                  for ret in batch.run():
                File "/opt/behavox/salt/venv/lib64/python3.6/site-packages/salt/cli/batch.py", line 293, in run
                  if self.opts.get("failhard") and data["retcode"] > 0:
              KeyError: 'retcode'
     Started: 14:17:47.716655
    Duration: 249333.567 ms
     Changes:
```

With fix from this PR i have tried to leave it for 2 days, 0 failures

**Comment by waynew** [comment]
@garethgreenaway I ran through this a bit on the Test Clinic.

A couple of takeaways:

- I feel like it should be possible, maybe even reasonable to actually write some automated tests for this.
- This function evolved over time. It used to just say "hey zmq give me a message, non-blocking". Now it does much *much* more.
- basically everything eventually hits this code: cmd, cmd_cli, and cmd_iter functions all depend on this functionality.
- As mentioned earlier in this PR, the `wait` param gets discarded basically... well that's interesting. I was thinking that it was wrong behavior but I just dug into it and it's actually creating a `FutureWithTimeout`, which sets the timeout to `0.1` if it's not None and <0.1s. Interesting!

Anyway, I plan to see what kind of testing I can do next week for the Test Clinic, but those insights may be helpful!

**Comment by GLaN1K** [comment]
Regarding performance concerns

I have tried to do the following:

Using steps described here: https://github.com/saltstack/salt/pull/59474#issuecomment-777497765
I have changed formula to:
```
debug:
  cmd.run:
    - name: sleep 120
```
And set timeouts to 30 in master conf:
```
# Timeouts
gather_job_timeout: 30
timeout: 30
```

So, my plan is to make execution go into timeout branch, so all code changed in this PR will be executed several times.

Result without fix (3 runs):
```
real    8m57.898s
user    0m15.400s
sys     0m3.478s
```
```
real    8m54.591s
user    0m14.476s
sys     0m3.191s
```
```
real    8m54.201s
user    0m15.257s
sys     0m3.696s
```
Result with fix (3 runs):
```
real    9m24.575s
user    0m9.982s
sys     0m3.203s
```
```
real    9m17.799s
user    0m10.104s
sys     0m3.288s
```
```
real    9m27.155s
user    0m9.758s
sys     0m3.079s
```

So, there **is** performance degradation.

I will try to change default `wait=5` back to `wait=0.01` (but without `no_block=True`) and will check performance once again
Also i will leave it running in a loop for a day or so to make sure what it's stable

**Comment by GLaN1K** [comment]
Okay, i have tried `wait` in `0.01`, `0.1`, `0.5`, issue reproduces in just several runs.
But with `wait` in `1`, after execution in a loop for two days in a row - zero failure cases.
So, i'm assume what `1` is fine for our cluster size (30 nodes)
But i do not know how that's scales
Test was performed on 30 nodes cluster, now i will try to perform just the same test with 300 nodes cluster and will see if `1` is still fine.

About performance degradation:
Results with the same fix from this PR, but with `wait: 1`
```
real    8m55.982s
user    0m10.520s
sys     0m2.961s
```
```
real    9m8.464s
user    0m10.373s
sys     0m2.911s
```
```
real    9m10.892s
user    0m9.855s
sys     0m2.894s
```
Results without any fix:
```
real    8m57.898s
user    0m15.400s
sys     0m3.478s
```
```
real    8m54.591s
user    0m14.476s
sys     0m3.191s
```
```
real    8m54.201s
user    0m15.257s
sys     0m3.696s
```

Degradation is still there, but it's smaller than with `wait: 5` (Test with `5` is here: https://github.com/saltstack/salt/pull/59474#issuecomment-778227703)

**Comment by GLaN1K** [comment]
Hello, @garethgreenaway !

Sorry for nudging you, but can you comment on this, please?

Just want to know what/when to expect

Thanks!

**Comment by whytewolf** [comment]
anyway we can get a tests for this so that if passes it can be merged?

**Comment by Oloremo** [comment]
@whytewolf 
1. This is not really a fix, more like reducing a race window
2. We won't be able to write tests for this. @waynew was puzzled as well.

**Comment by dwoz** [comment]
I am starting to dig into this today.

**Comment by dwoz** [comment]
Check out my comment here https://github.com/saltstack/salt/issues/56273#issuecomment-846401661

**Comment by dwoz** [comment]
I've created a regression test for this issue: #60256

**Comment by dwoz** [comment]
@GLaN1K Thank you for taking a stab at fixing this issue. After taking a look I think #60256 is a more comprehensive fix.

**Comment by GLaN1K** [comment]
@dwoz 

> #60256 is a more comprehensive fix.

indeed!
Thank you very much for it!
I will close this MR.

**Pull request closed without merging**
