### PR TITLE
Allow slashes in file_roots envs.

### LINKED ISSUE #51211: file_roots envs with slash leads to "No such file or directory: '/var/cache/salt/master/file_lists/roots/.foo/bar.w'
### Description of Issue/Question
Using this master config (to workaround #48132):
```yaml
file_roots:
  base:
    - /srv/salt
  feature/2:
    - /srv/salt
```
Salt works incorrectly and logs:
```log
2019-01-08 09:57:23,653 [salt.master      :1795][ERROR   ][28091] Error in function _file_list:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1788, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/utils/decorators/__init__.py", line 594, in wrapped
    **salt.utils.data.decode_dict(kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 752, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/roots.py", line 422, in file_list
    return _file_lists(load, 'files')
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/roots.py", line 310, in _file_lists
    __opts__, form, list_cache, w_lock
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 116, in check_file_list_cache
    if not os.path.isfile(list_cache) and _lock_cache(w_lock):
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 50, in _lock_cache
    os.mkdir(w_lock)
OSError: [Errno 2] No such file or directory: '/var/cache/salt/master/file_lists/roots/.feature/2.w'
```

### Setup
See above.

### Steps to Reproduce Issue
See above

### Versions Report
2018.3.3 with additionnal patches (#50417, #49987, #50626, #50768, #50783, but those are not related).

### PR DESCRIPTION
**Pull request by sathieu**
### What does this PR do?

Allow slashes in `file_roots` envs.

### What issues does this PR fix or reference?

Fixes #51211.

### Previous Behavior
Using this master config (to workaround #48132):
```yaml
file_roots:
  base:
    - /srv/salt
  feature/2:
    - /srv/salt
```
Salt works incorrectly and logs:
```log
2019-01-08 09:57:23,653 [salt.master      :1795][ERROR   ][28091] Error in function _file_list:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1788, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/utils/decorators/__init__.py", line 594, in wrapped
    **salt.utils.data.decode_dict(kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 752, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/roots.py", line 422, in file_list
    return _file_lists(load, 'files')
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/roots.py", line 310, in _file_lists
    __opts__, form, list_cache, w_lock
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 116, in check_file_list_cache
    if not os.path.isfile(list_cache) and _lock_cache(w_lock):
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 50, in _lock_cache
    os.mkdir(w_lock)
OSError: [Errno 2] No such file or directory: '/var/cache/salt/master/file_lists/roots/.feature/2.w'
```

### New Behavior
Slashes in `file_roots` envs are allowed.

### Tests written?

Yes

### Commits signed with GPG?

Yes

### CODE REVIEW

**Comment by sathieu** [comment]
I'm trying TDD. Another commit will come with the proposed fix.

**Comment by sathieu** [comment]
Confirmed [failing](https://jenkinsci.saltstack.com/job/pr-kitchen-ubuntu1604-py2/job/PR-51212/1/console):
```
11:54:32        ERROR [0.045s]: test_file_list_with_slash (unit.fileserver.test_roots.RootsTest)
11:54:32        ----------------------------------------------------------------------
11:54:32        Traceback (most recent call last):
11:54:32          File "/tmp/kitchen/testing/tests/unit/fileserver/test_roots.py", line 163, in test_file_list_with_slash
11:54:32            ret = roots.file_list(load)
11:54:32          File "/tmp/kitchen/testing/salt/fileserver/roots.py", line 422, in file_list
11:54:32            return _file_lists(load, 'files')
11:54:32          File "/tmp/kitchen/testing/salt/fileserver/roots.py", line 310, in _file_lists
11:54:32            __opts__, form, list_cache, w_lock
11:54:32          File "/tmp/kitchen/testing/salt/fileserver/__init__.py", line 122, in check_file_list_cache
11:54:32            if not os.path.isfile(list_cache) and _lock_cache(w_lock):
11:54:32          File "/tmp/kitchen/testing/salt/fileserver/__init__.py", line 56, in _lock_cache
11:54:32            os.mkdir(w_lock)
11:54:32        OSError: [Errno 2] No such file or directory: '/tmp/salt-tests-tmpdir/tmpaGcNUd/file_lists/roots/.foo/bar.w'
```

**Comment by sathieu** [comment]
Re-pushed with signature.

**Review by terminalmage — APPROVED** [review]

**Review by dwoz — APPROVED** [review]

**Comment by sathieu** [comment]
Sadly, this PR is not in 2019.2.0 (like #51317).

**Comment by sathieu** [comment]
@dwoz @terminalmage Sadly, this PR is not in 2019.2.0 (like #51317).

**Pull request merged**
