### PR TITLE
Fix Parameter Names of get_resource_path and get_resource_content

### PR DESCRIPTION
**Pull request by srkunze**
The names are totally misleading and too long. I hope we can fix them like this.

### CODE REVIEW

**Comment by rallytime** [comment]
@srkunze I'm definitely all for making things clearer and easier to use, but unfortunately we can't change the arguments to these functions so easily. This constitutes an API change, so the appropriate [deprecation steps](https://docs.saltstack.com/en/latest/topics/development/deprecations.html) must be taken to ensure we don't pull the rug out from anyone used to using this module as-is.

That being said, if you want to change this so that these arguments are placed on an appropriate deprecation path, that'd be great.

**Comment by srkunze** [comment]
Alright. I'll look into it and see what I can do here.

**Comment by cachedout** [comment]
@srkunze I'm going to close this so it isn't accidentially merged in its present state. When you have this ready to go with a deprecation path or an alternative approach, please re-open and we'll have a look. Thanks!

**Comment by srkunze** [comment]
Just one question. What are the next planned release names? The deprecation page says: "assume that Sodium is under development, then you need to use Aluminum". Shall I use Aluminum? I couldn't found a roadmap for salt. :(

**Comment by rallytime** [comment]
@srkunze Our releases are based on the Periodic Table. The next/current feature release we are on is Salt Boron. Beryllium was just release as 2015.8.0. After Boron comes Carbon, then Nitrogen, etc. 

I'll add a note about that to these docs because I don't see anything in there referencing the Periodic Table, which kind of makes those examples not super useful... :)

**Comment by srkunze** [comment]
I just thought about so but I better asked twice to make sure. I am not a big friend of implicit assumptions. So big thank you. :)

**Comment by srkunze** [comment]
Btw. I am going with "Nitrogen" then I assume.

**Comment by rallytime** [comment]
@srkunze Yep, correct. I added #27874 to make sure we mention how we're using the Periodic Table to track feature release names.

**Pull request closed without merging**
