### PR TITLE
Single schedule for MultiMinion, EventBus managed by MultiMinion.

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
### What does this PR do?

Reworked the schedule and MultiMinion design:
1. MultiMinion renamed to MinionManager
2. MinionManager manages:
        a) Minions
        b) EventBus
3. Minions are subscribed to events with MinionEvent
4. Single Minion is now a multiminion with multiplicity of 1
5. Schedule is now a singleton
6. Own master alive schedule job for each master
(__master_alive_<master-id>)
7. All previously persisted __master_alive\* jobs are cleared up on Minion start.
### What issues does this PR fix or reference?
#26311
### Tests written?

No

### CODE REVIEW

**Comment by cachedout** [comment]
Hi @DmitryKuzmenko 

Could you take a look at the failing tests here? They might need to be rewritten to accommodate this new approach. I'll work on reviewing the rest in the meantime. Thanks!

**Comment by DmitryKuzmenko** [comment]
@cachedout sure, I've seen this yesterday, but had no enough time to fix. Thank you!

**Comment by cachedout** [comment]
This is absolutely beautiful code. Really well done, @DmitryKuzmenko

**Comment by DmitryKuzmenko** [comment]
Thank you @cachedout! :blush:

**Pull request merged**
