### PR TITLE
Fix auth rest

### LINKED ISSUE #53197: salt.auth.rest response merged doesn't seems to work
### salt.auth.rest response merged doesn't seems to work

Thanks for the work done on Salt that a really nice product.

The rest auth documentation https://docs.saltstack.com/en/latest/ref/auth/all/salt.auth.rest.html is saying:

```
If there are entries underneath the ^url entry then they are merged with any responses from the REST call. In the above example, assuming the REST call does not return any additional ACLs, this will authenticate Fred via a REST call and allow him to run any execution module and all runners.
```
I've tried many setup and may be the json returned by the rest api is not in proper format, but documentation is may be not clear enough about it.

### Setup

In `/etc/salt/master.d/auth.conf` I've tried the following configuration

```
external_auth:
    rest:
        ^url: http://myauth.service.local
```

With a rest call returning the folowing acl in json:

```
[TRACE   ] Response Text: [".*","@wheel","@jobs","@runner"]
[DEBUG   ] eauth REST call returned 200: {u'body': '[".*","@wheel","@jobs","@runner"]', u'status': 200, u'dict': [u'.*', u'@wheel', u'@jobs', u'@runner']}
[TRACE   ] Compiled auth_list: []
[WARNING ] Authentication failure of type "token" occurred.
```
Compile list is empty. So merrge didn't happen

With the following:

```
[TRACE   ] Response Text: {"service-account-lbn-ttc-matrix-sid@placeholder.org":[".*","@wheel","@jobs","@runner"]}
[DEBUG   ] eauth REST call returned 200: {u'body': '{"fred":[".*","@wheel","@jobs","@runner"]}', u'status': 200, u'dict': {u'fred': [u'.*', u'@wheel', u'@jobs', u'@runner']}}
[TRACE   ] Compiled auth_list: []
```

Same than previous. With:

```
external_auth:
    rest:
        ^url: http://myauth.service.local
        'fred':
```

I've test with the same json as previous and I've got the following stack trace:

```
[ERROR   ] Some exception handling a payload from minion
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 750, in handle_message
    ret, req_opts = yield self.payload_handler(payload)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 270, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1064, in _handle_payload
    'clear': self._handle_clear}[key](load)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1095, in _handle_clear
    ret = getattr(self.clear_funcs, cmd)(load), {'fun': 'send_clear'}
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 2077, in publish
    auth_check = self.loadauth.check_authentication(extra, auth_type)
  File "/usr/lib/python2.7/dist-packages/salt/auth/__init__.py", line 436, in check_authentication
    auth_list = self.get_auth_list(load, token=token)
  File "/usr/lib/python2.7/dist-packages/salt/auth/__init__.py", line 396, in get_auth_list
    groups)
  File "/usr/lib/python2.7/dist-packages/salt/utils/minions.py", line 1014, in fill_auth_list
    auth_list.extend(auth_provider[match])
TypeError: 'NoneType' object is not iterable
[ERROR   ] Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 444, in _handle_events
    self._handle_send()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 487, in _handle_send
    status = self.socket.send_multipart(msg, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zmq/sugar/socket.py", line 363, in send_multipart
    i, rmsg,
TypeError: Frame 0 (u'Some exception handling minion...) does not support the buffer interface.
[ERROR   ] Exception in callback None
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 444, in _handle_events
    self._handle_send()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 487, in _handle_send
    status = self.socket.send_multipart(msg, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zmq/sugar/socket.py", line 363, in send_multipart
    i, rmsg,
TypeError: Frame 0 (u'Some exception handling minion...) does not support the buffer interface.
[TRACE   ] Process manager iteration
```

Error during the merge because list is empty. And with the following configuration with the same two senario of rest reply:

```
external_auth:
    rest:
        ^url: http://myauth.service.local
        'fred':
            - test.ping
```

Reply in both json case is:

```
[TRACE   ] Compiled auth_list: [u'test.ping']
```
So the list define in the `auth.conf` file override everything and is not merged. Or be the meaning of merge is not the one I'm thinking about or may be my json format is not correct so an example of json would be much appreciate.

### Versions Report

```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.24.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.6 
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 5.1.4-zen1-1-zen
         system: Linux
        version: debian 9.6 
 ```

### PR DESCRIPTION
**Pull request by simmel**
### What does this PR do?
Fixes a bug where eauth didn't use the acls that eauth rest returned.
Also the documentation promises that acls returned from eauth rest would be merged with the acls configured in `external_auth` and this was not the case.

### What issues does this PR fix or reference?
Fixes #53197 

### Tests written?
**[NOTICE] Bug fixes or features added to Salt require tests.**
Please review the [test documentation](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html) for details on how to implement tests into Salt's test suite.

No. Sadly I can't find any tests for anything auth-related.

### Commits signed with GPG?

No.

Please squash commits if you want to.

### CODE REVIEW

**Comment by simmel** [comment]
@cmcmarrow there you go

**Comment by simmel** [comment]
@dwoz @cmcmarrow Requiring tests, where tests didn’t exist in the first place, for fixes to bugs is not a great way to encourage people to contribute imo.

Do you have any pointers on where and how to start adding tests for authentication?

**Comment by simmel** [comment]
In #53197 it was asked again to provide tests but since there were none for this in the first place, how do I improve non-existant tests?

I'll gladly add tests but I need some hand holding. Got any links to existing tests which can be adapted or something like that?

Sorry for the CC madness @Ch3LL @dwoz @cmcmarrow

**Comment by Ch3LL** [comment]
The documentation for testing is located here: https://docs.saltstack.com/en/master/topics/tutorials/writing_tests.html

You can add a test in tests/unit/auth. You could get inspiration from tests/unit/auth/test_ldap.py.

But heres something to get started:

```
import salt.auth.rest
from tests.support.mixins import LoaderModuleMockMixin
from tests.support.unit import TestCase


class RestAuthTestCase(TestCase, LoaderModuleMockMixin):
    """
    Unit tests for salt.auth.rest
    """
    def setup_loader_modules(self):
        opts = {'external_auth': {'rest': {'^url': "https://test_url/rest",
                                    'fred': ['.*', '@runner']}}}
        return {salt.auth.rest: {"__opts__": opts}}


    def test_rest_auth_setup(self):
        ret = salt.auth.rest.rest_auth_setup()
        assert ret == "https://test_url/rest"
```

Let me know if i can help any further :)

**Comment by sagetherage** [comment]
We also hold on Tuesdays from 1-2 pm Mountain and Thursdays from 8-10 am Mountain Test Clinics with @waynew on [Twitch](https://www.twitch.tv/saltprojectoss) and this is the [schedule](https://www.twitch.tv/saltprojectoss/schedule). Wayne can help even if there isn't great test coverage, today. He is pretty amazing!

**Comment by marty-macfly** [comment]
I've push the following test to cover that case https://github.com/simmel/salt/pull/8

**Comment by marty-macfly** [comment]
@simmel & @Ch3LL did you get the opportunity to check my PR https://github.com/simmel/salt/pull/8 to add some tests. If it's ok and @simmel  doesn't have time to merge my PR I can PR directly the salt project with fix + test case.

**Comment by Ch3LL** [comment]
It looks like that PR has a lot of commits in it that where not intended to be there. Would you mind cleaning it up to just include the test. Thanks for being willing to do the work here.

**Comment by simmel** [comment]
Sorry for being AWOL = /

@marty-macfly the tests look great!

Can you elaborate @marty-macfly (because the commit message wasn't that thorough) why the cache was removed? Except to not hit the REST API twice I have a vague memory that it was another reason I added it (like that you could inherit ACLs from other eauths or something like that). Now that I look at my code I realize that I never invalidate the cache either so it was probably a good idea to remove it (since now the tests proves that it works!).

Should I close this and we only continue in #60576 @Ch3LL?

**Comment by simmel** [comment]
I took the liberty of taking your commit and cleaning them up so there are only two additional commits to mine @marty-macfly I hope that's OK!

**Comment by marty-macfly** [comment]
> Sorry for being AWOL = /

I was wondering if you completely disappear, so I've create a new https://github.com/saltstack/salt/pull/60576 with the changes to try to make it merge :(

> @marty-macfly the tests look great!
> 
> Can you elaborate @marty-macfly (because the commit message wasn't that thorough) why the cache was removed? Except to not hit the REST API twice I have a vague memory that it was another reason I added it (like that you could inherit ACLs from other eauths or something like that). Now that I look at my code I realize that I never invalidate the cache either so it was probably a good idea to remove it (since now the tests proves that it works!).

It was requested by dwoz and s0undt3ch in the new PR https://github.com/saltstack/salt/pull/60576#discussion_r675892076 that's the main reason that I'removed it. As I said to them _I'm not the original writer of the PR, I think it's mainly to reduce the number of API call..._ but was not sure if it was only your original goal, you are the only one that can tell :) but as you said it works without it and cache was not invalidate.

> 
> Should I close this and we only continue in #60576 @Ch3LL?

I think it will be useless to have to 2 of them also I don't want to remove your part of the commit by doing so.

**Comment by simmel** [comment]
> > Sorry for being AWOL = /
> 
> I was wondering if you completely disappear, so I've create a new PR #60576 with the changes to try to make it merge :(

Life got in the way ; (

> > @marty-macfly the tests look great!
> > Can you elaborate @marty-macfly (because the commit message wasn't that thorough) why the cache was removed? Except to not hit the REST API twice I have a vague memory that it was another reason I added it (like that you could inherit ACLs from other eauths or something like that). Now that I look at my code I realize that I never invalidate the cache either so it was probably a good idea to remove it (since now the tests proves that it works!).
> 
> It was requested by dwoz and s0undt3ch in the new PR [#60576 (comment)](https://github.com/saltstack/salt/pull/60576#discussion_r675892076) that's the main reason that I'removed it. As I said to them _I'm not the original writer of the PR, I think it's mainly to reduce the number of API call..._ but was not sure if it was only your original goal, you are the only one that can tell :) but as you said it works without it and cache was not invalidate.

Ah, I totally missed that part! Makes sense, I'm OK with it!

> > Should I close this and we only continue in #60576 @Ch3LL?
> 
> I think it will be useless to have to 2 of them also I don't want to remove your part of the commit by doing so.

My commits are there. Let's let salt decide 👌

**Comment by simmel** [comment]
I  also fixed style problems pylint and black indicated.

**Comment by marty-macfly** [comment]
I'll close mine #60576 so we can finish what has been started here, sorry for duplicate PR @s0undt3ch @dwoz but everything is back to the original place. So if we can have an idea of what need to be done to complete the PR would really appreciate ?

**Review by s0undt3ch — DISMISSED** [review]

**Review by Ch3LL — CHANGES_REQUESTED** [review]
this will require a changelog https://docs.saltproject.io/en/latest/topics/development/changelog.html

**Comment by Ch3LL** [comment]
ping @dwoz can you review please

**Comment by simmel** [comment]
> this will require a changelog https://docs.saltproject.io/en/latest/topics/development/changelog.html

How does that look? Please help with wording = )

**Review by Ch3LL — APPROVED** [review]

**Comment by marty-macfly** [comment]
@sagetherage  what do we still need to do to be able to finish the merge ?

**Comment by marty-macfly** [comment]
> @marty-macfly we just need all tests passing and one more review.

Ok, I've checked why the test is failing and it seems to be due to an error on test environment and not in the code, so we can't do anything to fix that, unless I miss something and if so tell me where I can find the error that test are facing so I can help to fix it.

```
18:54:52  + bundle exec kitchen verify py3-ubuntu-2004-arm64
18:54:52  -----> Starting Test Kitchen (v3.1.0)
18:54:54  -----> Verifying <py3-ubuntu-2004-arm64>...
18:54:54         Preparing files for transfer
18:54:54         [Nox] Only downloading artefacts from instance py3-ubuntu-2004-arm64 with state={:username=>"ubuntu", :server_id=>"i-0e490d4a9c036add9", :hostname=>"10.74.122.186", :last_action=>"setup", :last_error=>"IOError"}
18:57:16         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
18:59:23         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:01:30         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:03:53         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:06:00         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:08:22         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:10:29         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:12:36         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:14:59         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:17:06  $$$$$$ [SSH] connection failed, terminating (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:17:06  >>>>>> Failed to chown /tmp/kitchen :: SSH session could not be established
19:19:13         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:21:35         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:23:43         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:26:05         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:28:12         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:30:19         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:32:41         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:34:49         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:37:11         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:39:18  $$$$$$ [SSH] connection failed, terminating (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:39:18  >>>>>> Failed to chown /tmp/kitchen/testing/artifacts/ :: SSH session could not be established
19:39:18         Copying /tmp/kitchen/testing/artifacts/ to /var/jenkins/workspace/u-2004-arm64-py3-pytest_PR-55654
19:41:25         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:43:47         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:45:54         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:48:16         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:50:24         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:52:31         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:54:53         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:57:00         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
19:59:07         [SSH] connection failed, retrying in 2 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
20:01:30  $$$$$$ [SSH] connection failed, terminating (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
20:01:30  >>>>>> Failed to copy /tmp/kitchen/testing/artifacts/ to /var/jenkins/workspace/u-2004-arm64-py3-pytest_PR-55654 :: SSH session could not be established
20:01:30         [Nox] Download artefacts completed.
20:01:30         Finished verifying <py3-ubuntu-2004-arm64> (66m26.51s).
20:01:30  -----> Test Kitchen is finished. (66m27.98s)
```

**Review by dwoz — APPROVED** [review]

**Pull request merged**
